### ISSUE TITLE
`primary_author.profile_image` returns unsecure url

### ISSUE THREAD

**Issue by Leandros** [TryGhost/Ghost#10024]
Starting with 2.0, the `primary_author.profile_image` returns an unsecure URL on a secure site, resulting in mixed-content warnings. This was working in 1.x.

**Comment by kevinansfield** [comment]
@Leandros further information would be useful to help pin this down as this hasn't been observable on any other sites so far.

- what is the url in your `config.production.json` file, does it start with `https://`?
- is it all profile images or only some of them?
- what's stored in the DB for the profile image in question?
- are you using any storage adapter?

**Comment by Leandros** [comment]
- The url in `config.production.json` is `https://arvid.io`
- It's a profile image which still exists from an upgrade
- The absolute url, including the `http` is stored in the database. 
- I'm not using any storage adapter.

I gave it a try to simply reupload the images, which does indeed update the urls to a `https://` prefix, and therefore fixes the issue.
Even though I could fix it, I'd still consider it a bug (or design flaw) to save an absolute URL in the database.

**Comment by kevinansfield** [comment]
I've tested and I'm only seeing relative URLs stored in the database. I think this may have something to do with a recent change to return absolute URLs via the API - /cc @kirrg001

**Comment by kevinansfield** [comment]
@Leandros can you confirm you're seeing absolute URLs in the database itself rather than what's returned in the theme or via the API?

**Comment by kirrg001** [comment]
@Leandros 

Which version of Ghost 2.x are you on? 

Do you still have the 1.0 backup JSON? If yes, could you please share the target post from your JSON backup file?

**Comment by Leandros** [comment]
@kevinansfield 

```
$ mysql -u root -p
> use ghost;
> select profile_image from users;
+------------------------------------------------------------+
| profile_image                                              |
+------------------------------------------------------------+
| https://arvid.io/content/images/2018/10/profile_blog-1.jpg |
+------------------------------------------------------------+
1 row in set (0.00 sec)

@kirrg001 I'm on latest (v2.2.3). Unfortunately, I only backed up the ghost folder, not the database or exported a json backup.

**Comment by Leandros** [comment]
For some reason, my authors are also duplicated after the 2.0 upgrade.
<img width="1086" alt="screen shot 2018-10-17 at 18 52 35" src="https://user-images.githubusercontent.com/396475/47102756-d567fc80-d23d-11e8-8fcc-4800a5b29bec.png">

**Comment by Leandros** [comment]
And I also just noticed that the posts are duplicated when scrolling through the post list.

**Comment by kirrg001** [comment]
@Leandros And where exactly do you get mixed content?

---

There is definitely a bug introduced by API v2.

1. Ghost stores images without domain
2. API V2 returns e.g. users with absolute urls 
3. Ghost-Admin sends absolute urls back on any save e.g. update user
4. This will override the relative image path to absolute

**Comment by kirrg001** [comment]
> And I also just noticed that the posts are duplicated when scrolling through the post list, it starts at the beginning again once I reach the end.

That sounds like a different issue. Can you please either report it in our [forum](https://forum.ghost.org) and ask for help or raise a new bug issue if you think it's a bug (**Please put steps to reproduce and as much as possible information**!).

**Comment by kevinansfield** [comment]
> Ghost-Admin sends absolute urls back on any save e.g. update user
Hmm, that's an interesting one. We probably have a few places where that will be the case 🤔 I'm not sure there's too much we can do about it on the client-side, maybe there's some checks we can do server-side to strip the base URL from image fields if it matches the configured URL?

**Comment by kirrg001** [comment]
> not sure there's too much we can do about it on the client-side, maybe there's some checks we can do server-side to strip the base URL from image fields if it matches the configured URL?

This needs protection on the server side 👍

**Comment by kirrg001** [comment]
I am not really sure how big the outcome of this bug is 🤔I guess it's only a problem if you change your domain or your protocol. Not sure it's super critical, but we should look into the fix and a migration file asap.

I need steps to reproduce to get the mixed content issue, because obviously the profile image is stored correctly with https.

**Comment by Leandros** [comment]
@kirrg001 I got the mixed content in places where my profile picture was displayed, for example on a post. 

I'm guessing you could reproduce it by creating an instance on HTTP, uploading a profile picture (which will write the absolute URL to the database), and than changing to HTTPS.
