### ISSUE TITLE
Enable MySQL SSL

### ISSUE THREAD

**Issue by cchatfield** [TryGhost/Ghost#10026]
I use an external cloud hosted mySQL DB for local development after verifying with sqlite.

I didn't see any documentation on how to enable via configuration.

I added 
```
        if(dbConfig.connection.ssl && dbConfig.connection.ssl.ca){
            dbConfig.connection.ssl.ca = fs.readFileSync(dbConfig.connection.ssl.ca);
        }
```
to core/server/data/connection.js

Is this the correct way to enable ssl for mySQL

**Comment by kevinansfield** [comment]
Hey @cchatfield  👋 Friendly reminder: help or support is not available on Github. Our default issue templates pointed you to our [forum](https://forum.ghost.org) for this type of question 😄 We use GitHub solely for bug-tracking and on-going feature development so we try to keep it noise free.

Many questions can be answered by reviewing our docs for [self-hosters](https://docs.ghost.org), our [theme API](https://themes.ghost.org), or our [public API](https://api.ghost.org). If you can't find an answer then our [forum](https://forum.ghost.org) is a great place to get community support, plus it helps create a central location for searching problems/solutions.

FYI: Many projects have their own support guidelines and GitHub will highlight them for you, or the project owners will use issue templates to point you in the right direction. Reading the guidelines or issue templates before opening issues can save you and other project maintainers some valuable time.
