### ISSUE TITLE
Koenig Renderer "b" tag not rendered

### ISSUE THREAD

**Issue by PhoenixPeca** [TryGhost/Ghost#10027]
Hi Dev Team,

While publishing a post, I found an issue where the "b" html tag is not rendered just like the "strong" html tag in the rendered koenig editor.

Insert this HTML in the editor:
![image](https://user-images.githubusercontent.com/9730242/47129819-7bad1400-d2c9-11e8-9b77-6dec83aae395.png)

Then you'll get this result:
![image](https://user-images.githubusercontent.com/9730242/47129857-a6976800-d2c9-11e8-995b-073a5010a81b.png)

My intuition tells me that both tags should yield identical output.

I am about to open a PR to fix this, but I am afraid I can't find the right file to edit. So, here you go, would be nice if you can help me with this. 😄

Thanks!

**Comment by kevinansfield** [comment]
@PhoenixPeca thanks for reporting!

> I can't find the right file to edit

The relevant CSS is in our Spirit CSS framework which is not currently public. We'll get it sorted 😄

**Comment by peterzimon** [comment]
Closed by https://github.com/TryGhost/Ghost-Admin/commit/060450bb5f19c544316828088b7b19c3a6257a44
