### ISSUE TITLE
Duplicate AJAX records

### ISSUE THREAD

**Issue by PFre888437** [TryGhost/Ghost#10029]
2.2.3 doesnt work well -> ajax calls for extra stories or team lists are returning duplicate records. Downgraded to 2.2.2 and problem was fixed

**Comment by allouis** [comment]
Hi there! Thanks for the report :memo: 

Would you be able to provide us some more information, so we can easier fix/find the problem? :relaxed: 

What database are you using?
What version did you upgrade from?
Is this just in the ajax calls, or is it visible in the UI?

Danke!

**Comment by PFre888437** [comment]
Greetings!
Mysql 5.7
Ghost 2.2.2 -> 2.3.1 through the cli
It is visible in the UI
I just did a clean install -> if you put 31 posts in and get to the point of ajax loading more posts in the stories section you will see the issue

**Comment by allouis** [comment]
:+1: Thanks! Replicated - working on a fix now.

**Comment by PFre888437** [comment]
👍 🥇
