### ISSUE TITLE
Unable to log in after upgrading

### ISSUE THREAD

**Issue by cshawaus** [TryGhost/Ghost#10028]
Hi,

After upgrading to the latest version today I'm no longer able to authenticate with the admin panel, I simply get the below error which makes me think a breaking change was made to the API layer.

Below is the error in question.
```bash
[2018-10-18 16:05:39] ERROR "GET /ghost/api/v2/admin/users/me/?include=roles" 401 1ms

NAME: UnauthorizedError
MESSAGE: Access denied.

level: normal

empty
empty
ERROR DETAILS:
    empty

UnauthorizedError: Access denied.
    at new UnauthorizedError (/var/www/blog/versions/2.2.3/node_modules/ghost-ignition/lib/errors/index.js:101:23)
    at ensureUser (/var/www/blog/versions/2.2.3/core/server/services/auth/session/middleware.js:95:10)
    at Layer.handle [as handle_request] (/var/www/blog/versions/2.2.3/node_modules/express/lib/router/layer.js:95:5)
    at next (/var/www/blog/versions/2.2.3/node_modules/express/lib/router/route.js:137:13)
    at getUser (/var/www/blog/versions/2.2.3/core/server/services/auth/session/middleware.js:79:16)
    at Layer.handle [as handle_request] (/var/www/blog/versions/2.2.3/node_modules/express/lib/router/layer.js:95:5)
    at next (/var/www/blog/versions/2.2.3/node_modules/express/lib/router/route.js:137:13)
    at cookieCsrfProtection (/var/www/blog/versions/2.2.3/core/server/services/auth/session/middleware.js:104:16)
    at Layer.handle [as handle_request] (/var/www/blog/versions/2.2.3/node_modules/express/lib/router/layer.js:95:5)
    at next (/var/www/blog/versions/2.2.3/node_modules/express/lib/router/route.js:137:13)
    at session (/var/www/blog/versions/2.2.3/node_modules/express-session/index.js:454:7)
    at getSession (/var/www/blog/versions/2.2.3/core/server/services/auth/session/middleware.js:48:12)
    at Layer.handle [as handle_request] (/var/www/blog/versions/2.2.3/node_modules/express/lib/router/layer.js:95:5)
    at next (/var/www/blog/versions/2.2.3/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/var/www/blog/versions/2.2.3/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/var/www/blog/versions/2.2.3/node_modules/express/lib/router/layer.js:95:5)
```

Rolling back to my previous 2.1.3 install fixes the issue.

### System Details
- Ubuntu 16.04.5 LTS
- nginx 1.14.0
- Ghost-CLI version: 1.9.6

**Comment by allouis** [comment]
Hey :wave: Is that error _after_ you enter your username and password into the admin panel?

**Comment by cshawaus** [comment]
Yes, immediately upon hitting the Sign in button it redirects back to the login screen with that 401 message in the console.

**Comment by allouis** [comment]
What does the request to the `/session` endpoint look like when signing in? Is that successful? Can you see the session cookie in the developer tools?

**Comment by cshawaus** [comment]
`/ghost/api/v2/admin/session` responds with a 201 code but the body in chrome is:

> Failed to load response data

**Comment by allouis** [comment]
That's strange - the response data should be the string `'Created'`..

Any more data you could give would be appreciated!

Are you seeing the `Set-Cookie` header in the response?
Are you able to see the session cookie in the developer tools?
Are you able to see the cookie sent in the `Cookie` header on the request to `/ghost/api/v2/admin/users/me/?include=roles`?

**Comment by cshawaus** [comment]
Once I'm back in front of my Mac I'll let you know about the headers. As for cookies, they are on and work since rolling back yields a successful result.

**Comment by kevinansfield** [comment]
> As for cookies, they are on and work since rolling back yields a successful result.

2.1.3 doesn't use cookies so that's not an indication that cookies are working.

"Failed to load response data" in Chrome suggests you may be using the preserve log function? It won't show you the response data for requests after you navigate away so it may be a red herring. Could you try again? Do you see any redirects happening?

Do you get any errors in the DevTools console when trying to log in? If for some reason CORS is tripping up then there would be an error there.

**Comment by cshawaus** [comment]
> That's strange - the response data should be the string `'Created'`..
> 
> Any more data you could give would be appreciated!
> 
> Are you seeing the `Set-Cookie` header in the response?
> Are you able to see the session cookie in the developer tools?
> Are you able to see the cookie sent in the `Cookie` header on the request to `/ghost/api/v2/admin/users/me/?include=roles`?

I don't see any cookies being sent back from the server, upon just loading the sign in page it fails with a 401 error code.

> > As for cookies, they are on and work since rolling back yields a successful result.
> 
> 2.1.3 doesn't use cookies so that's not an indication that cookies are working.
> 
> "Failed to load response data" in Chrome suggests you may be using the preserve log function? It won't show you the response data for requests after you navigate away so it may be a red herring. Could you try again? Do you see any redirects happening?
> 
> Do you get any errors in the DevTools console when trying to log in? If for some reason CORS is tripping up then there would be an error there.

I'm using my MacBook at home whereas I was on my iMac at work earlier and the issue is persistent so it's not a browser issue on my end.

For quicker debugging from your end, below is the URL for my sign in page.

https://cshaw.tech/ghost/#/signin

**Comment by kevinansfield** [comment]
@cshawaus the 401 error is expected on initial load because you won't be logged in after upgrading to 2.2.3, the 401 is what tells the admin area to show the signin screen.

Can you clarify that you're unable to log in with your username/password?

**Comment by cshawaus** [comment]
Yep, same username and password that works if I rollback fails with 2.2.3.

**Comment by kevinansfield** [comment]
> For quicker debugging from your end, below is the URL for my sign in page. https://cshaw.tech/ghost/#/signin

Your sign in page is behaving as expected but we're not able to test the login because we don't have the username/password (please don't share that!)

Can you share the exact reproduction steps you are trying? This is what is expected after upgrading even if you were logged in on 2.1:

1. Load you admin page https://cshaw.tech/ghost/
    - you'll see a 401 in the network requests for `/ghost/api/v2/admin/users/me/?include=roles` _this is expected_
2. You're redirected to https://cshaw.tech/ghost/#/signin
3. You need to put your username/password in and click on "Sign In"
4. A `POST` request will be made to https://cshaw.tech/ghost/api/v2/admin/session
    - response should be a 201
    - if you inspect the _response_ it should have a `set-cookie: ghost-admin-api-session=....` header

If you don't see the `set-cookie` header please let us know what you see in the _request's_ `origin` and `referer` headers.

**Comment by cshawaus** [comment]
Here are the request headers.

```
origin: https://cshaw.tech
referer: https://cshaw.tech/ghost/
```

Looking at the response for `/session`, there is no `set-cookie` header attached to it. Below is the complete headers I get back from nginx.

```
cache-control: no-cache, private, no-store, must-revalidate, max-stale=0, post-check=0, pre-check=0
content-length: 7
content-type: text/plain; charset=utf-8
date: Thu, 18 Oct 2018 12:00:10 GMT
etag: W/"7-rM9AyJuqT6iOan/xHh+AW+7K/T8"
server: nginx
status: 201
vary: Accept-Encoding
```

**Comment by allouis** [comment]
> Looking at the response for /session, there is no set-cookie header attached to it.

This is the problem, maybe your nginx is not configured to forward `Set-Cookie` headers? Can you think of anything else between the node process and your browser that might remove that header?

Maybe you could share your nginx config here?

**Comment by cshawaus** [comment]
Now I feel dumb, turns out I had `proxy_hide_header Set-Cookie;` set for the `ghost` and `signout` paths. Not sure if I put it there a year or so ago or I copied the vhost from something else but all is good now.

🤦‍♂️

**Comment by allouis** [comment]
:dancer: Glad you can sign in now!
