### ISSUE TITLE
Public API link to developer guide goes to 404

### ISSUE THREAD

**Issue by kolbma** [TryGhost/Ghost#10038]
### Issue Summary

The link to the developer guide is to https://help.ghost.org/hc/en-us/articles/115000301672-Public-API-Beta which returns a 404-page.

### To Reproduce

Go to admin -> Settings -> Labs -> Public API
There is a link.

### Technical details:

* Ghost Version: 2.2.3
* Node Version: v8.12.0
* Browser/OS:Firefox Windows
* Database:SQlite3

**Comment by kirrg001** [comment]
Thanks for the report 👻We will add a redirect asap 👍

**Comment by kirrg001** [comment]
The redirect is in place 🙊

**Comment by kirrg001** [comment]
The redirect is in place 🙊
