### ISSUE TITLE
The Infinite Scroll of Articles in "Stories" are looping Twice... Then Halts.

### ISSUE THREAD

**Issue by PhoenixPeca** [TryGhost/Ghost#10032]
Hi,

The first 30 articles in the "Stories" page are being repeated the second time by the infinite-scroll feature.
Then, the infinite-scroll feature stops completely even when scrolled to the last article.

I can confirmed this issue with Google Chrome and Microsoft Edge.

### Here's my Ghost Instace Details:
**Version** 2.2.3
**Environment** production
**Database** mysql
**Mail** SMTP

**Comment by allouis** [comment]
Hey! Thanks for raising the issue :relaxed: This has literally _just_ been fixed in version 2.2.4! https://github.com/TryGhost/Ghost/commit/e865d2218c1b6e392831db67552fa397ccd31eac
