### ISSUE TITLE
[Feature] relative links update automatically

### ISSUE THREAD

**Issue by fallerOfFalls** [TryGhost/Ghost#10037]
Every time I change the URL of a post, I have to find all the other posts that link to it and change them. The problem is I can't always remember which posts I've linked from, so I'm probably leaving a bunch of broken links around my blog.

Is there any reason why relative links can't update themselves whenever the URL of their target is changed?

**Comment by kevinansfield** [comment]
Hey @fallerOfFalls 👋 Friendly reminder: we don't track feature requests on GitHub. Our default issue templates pointed you to our [forum](https://forum.ghost.org) for this type of question - the [Ideas](https://forum.ghost.org/c/Ideas/l/votes) topic will let you propose features and let others vote on them 😄. We use GitHub solely for bug-tracking and on-going feature development so we try to keep it noise free.

FYI: Many projects have their own support guidelines and GitHub will highlight them for you, or the project owners will use issue templates to point you in the right direction. Reading the guidelines or issue templates before opening issues can save you and other project maintainers some valuable time..

**Comment by fallerOfFalls** [comment]
Ah thanks. The mobile version of GitHub doesn't show anything. Now I tried creating an issue with the desktop version and I see what you mean.
