### ISSUE TITLE
Ghost forcing trailing slash on asset directories

### ISSUE THREAD

**Issue by azariah001** [TryGhost/Ghost#10044]
### Issue Summary
I'm migrating a clients site from Ghost 0.x to 2.0 and so far everything has gone smoothly with one exception. I built the site in 2016 and utilised a handful of web-components for both stylistic and maintainability reasons.

Those were naturally installed using Bower and I've still got all of the original files under the `/assets/bower_components/` directory.

The issue appears to be that Ghost 2.0 doesn't take kindly to custom asset subdirectories, and is adding a forward slash `/` on to the end of all of the `.js` and `.html` paths which means that they're all 404'ing.

I've tried typing in the URL's and have found that it's also redirecting from  `/assets/bower_components/paper-tabs/paper-tabs.html` to `/assets/bower_components/paper-tabs/paper-tabs.html/`. I found some information in the docs for redirects that says "Ghost automatically forces trailing slashes." How do I tell it to not for the assets directory?

Edit: I've just manually cd'd into the theme directory and bower_components is being stripped from the upload... which is even more frustrating. Why!?

Chrome
Edge
Brave (Chromium)

### To Reproduce

1. Add a non default folder under `/assets/` in your theme, in this case `/assets/bower_components/`
2. Upload and activate the theme and try to access any file under that directory.

### Technical details:

* Ghost Version: 2.3.0
* Node Version: 8.10.0
* Browser/OS: Chrome/Windows
* Database: MySQL

**Comment by allouis** [comment]
Hey! Sorry to hear you're having trouble with this.

Would you be able to store the `bower_components` directory in the `assets/js` directory? e.g `assets/js/bower_components/paper-tabs/paper-tabs.html`

That should work for now :relaxed:

**Comment by azariah001** [comment]
> Hey! Sorry to hear you're having trouble with this.
> 
> Would you be able to store the `bower_components` directory in the `assets/js` directory? e.g `assets/js/bower_components/paper-tabs/paper-tabs.html`
> 
> That should work for now ☺️

that's possible... Manually uploading the theme has bypassed the engine stripping the `bower_components` directory so it should just be a matter of `cp`'ing and changing links.

Thanks for the suggestion.
