### ISSUE TITLE
Correct handling of 'Content-Length' header

### ISSUE THREAD

**Issue by gargol** [TryGhost/Ghost#10041]
The issue is based on https://github.com/TryGhost/Ghost/pull/10019#discussion_r226306369 . 

>The Content-Length entity-header field indicates the size of the entity-body, in decimal number of OCTETs
(https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html)

>String.prototype.length returns:
>This property returns the number of code units in the string

Places that use `String.prototype.length` (e.g: [here](https://github.com/TryGhost/Ghost/blob/959912eca316e12715808b1cbaa7bc55ebfb81cb/core/server/api/shared/headers.js#L24)) to calculate Content-Length should switch to [Buffer.byteLength](https://nodejs.org/api/buffer.html#buffer_class_method_buffer_bytelength_string_encoding) instead.

**Comment by dnguneratne** [comment]
I took a shot at this in [PR 10046](https://github.com/TryGhost/Ghost/pull/10046)
