### ISSUE TITLE
Ghost timeout when uploading huge theme (20mb)

### ISSUE THREAD

**Issue by maxime1992** [TryGhost/Ghost#10052]
### Issue Summary

We've been creating a Ghost theme and it includes several pictures which are quite heavy.

The total zip file is ~20mb. When uploading the theme to `ghost.io` we often get a timeout...

Could that timeout be increased? It's really inconvenient to upload large file. Maybe only increase the timeout for the theme upload and not the rest of the API?

### To Reproduce

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

I'd expect to be able to upload my theme without having to retry a lot.

### Technical details:

* Ghost Version: 2
* Node Version: The one on ghost.io
* Browser/OS: Ubuntu chrome
* Database: The one on ghost.io

**Comment by kevinansfield** [comment]
Hey @maxime1992 👋 For any Ghost(Pro) issues please e-mail support@ghost.org

**Comment by maxime1992** [comment]
In case anyone has the same problem, bottom line of this issue was that we are pushing the new theme as part of our CI/CD pipeline and forgot to exclude... the node_modules folder :sweat_smile: So we were uploading nearly 1gb on CI (not locally...) and then our Ghost instance was dead.
