### ISSUE TITLE
Content API V2: change /users to /authors

### ISSUE THREAD

**Issue by kirrg001** [TryGhost/Ghost#10061]
_(refs #9866)_

This is a change for **API v2** only.
The **Content API** should change /users/ to /authors/.

This implicitly makes this possible in V2:

routes.yaml
```
routes:
  /test/:
    data: author.slug
```

theme helper
```
{{#get "authors"}}
```

**Comment by galopin** [comment]
@kirrg001 I think there is _another_ use case besides the Content API…

I'm a fairly new Ghost(Pro) user and submitted today a support request where I asked if it was possible to not list authors with no posts in the XML sitemap:

> […] I'd like to know if Ghost(Pro) developers team would consider modifying the current behavior and make suitable changes so that some authors (e.g., admins) would not be listed in the "https://yourdomain.example/sitemap-authors.xml" file?
>
> I really don't want to be indexed as a potential author by robots, you know. One way I can think of would be to skip authors who haven't authored a single post yet. Is this doable?

https://github.com/kirrg001/Ghost/blob/9b10f1d39c55a44072c92dc61f4462345f25b035/core/server/data/xml/sitemap/user-generator.js#L7-L26

**Comment by ErisDS** [comment]
There's a subtle difference to the intention of this change, which I think got lost in my documentation - sorry. The intention is that instead of having users available from the Content API, we will have authors. 

The definition of authors is "users who have written at least one post". 

So we also want to change the endpoints to be /authors/.

**Comment by kirrg001** [comment]
Prio 1: /authors/
Prio 2: Don't return tags/authors with no posts

**Comment by kirrg001** [comment]
> don't return tags/authors with no posts

That is not easy to fix, because `filter=count.posts:>0` is not supported by GQL.

**Comment by kirrg001** [comment]
We've created a new issue for "do not return authors/tags without posts" - [see](https://github.com/TryGhost/Ghost/issues/10124). This has a much bigger underlying architecture problem now that we support multiple api versions. Have a read.

**Comment by kirrg001** [comment]
Closed via https://github.com/TryGhost/Ghost/commit/ff6bf5f318aec6446a7bc741d39da7a6664a38f1
