### ISSUE TITLE
API V2 complete controller set

### ISSUE THREAD

**Issue by kirrg001** [TryGhost/Ghost#10060]
_(refs #9866)_

There are some controllers missing in V2.

- [x] configuration @rishabhgrg (https://github.com/TryGhost/Ghost/pull/10056)
- [x] db @gargol (https://github.com/TryGhost/Ghost/pull/10051)
- [x] redirects @gargol  (https://github.com/TryGhost/Ghost/pull/10053) <-- ~blocked by #10051~)
- [x] oemed @rishabhgrg https://github.com/TryGhost/Ghost/pull/10057
  - [ ] Move generic checks to validation from query (https://github.com/TryGhost/Ghost/pull/10057#discussion_r230300407)
- [x] slack @rishabhgrg (https://github.com/TryGhost/Ghost/pull/10086)
- [x] themes @kirrg001
- [x] authentication @gargol
  - [x] needs cleanup before moving to v2!!! (https://github.com/TryGhost/Ghost/pull/10893)
  - [x] migration (https://github.com/TryGhost/Ghost/pull/10950)
- [ ] schedules @gargol (https://github.com/TryGhost/Ghost/pull/10975) 
  - [ ] post imlementation - take into account https://github.com/TryGhost/Ghost/pull/10726#issuecomment-489557162 (scheduler adapter changes)

**Comment by m1guelpf** [comment]
Need help with this? What steps should I take to migrate a controller to the v2 API?

**Comment by kirrg001** [comment]
@m1guelpf Thanks for your interest. The Ghost team is working on this issue.
I'd suggest you choose an issue from this [list](https://github.com/TryGhost/Ghost/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22+label%3A%22good+first+issue%22) (issues which are labelled with "help wanted" and/or "good-first-issue".

**Comment by kirrg001** [comment]
>  themes

Working on this.

**Comment by rishabhgrg** [comment]
🎉
