### ISSUE TITLE
Wrong Link Destination

### ISSUE THREAD

**Issue by ljgrohn** [TryGhost/Ghost#10066]
On this page https://docs.ghost.org/faq/using-custom-domains/, the Namecheap link goes to the GoDaddy tutorial. 

Here is the correct Namecheap link: https://docs.ghost.org/faq/namecheap-domain-setup-guide/

**Comment by ErisDS** [comment]
Hi @ljgrohn - I've fixed that link. FYI our docs site is also open source and lives at https://github.com/TryGhost/docs, so you can raise issues directly there.
