### ISSUE TITLE
Content API V2: Date formatting

### ISSUE THREAD

**Issue by gargol** [TryGhost/Ghost#10065]
refs #9866

### Why do we need yet another way of date format in our API?

We want to avoid unnecessary work on the client doing date conversions. At the moment steps would be:

1. Make a request to another endpoint to get the time zone
2. Load utilities like `moment-timezone` (which is big overhead compared to just loading `moment`) 
3. Know how to use that to format the date correctly

All these steps can be obliterated once we return formatted date directly from the API.

### How do we solve this problem?

Based on our research and internal conversations, the best solution for this problem would be adding [UTC offset](https://en.wikipedia.org/wiki/UTC_offset) information to an existing date field, that way it will follow current [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format. For blog instance that is configured with `Europe/Oslo` timezone, example response would contain information like:
```

"updated_at": "2014-01-01T00:58:58+01:00"

```
comparing to currently returned:
```
"updated_at": "2013-12-31T23:58:58Z"
```
The implementation of this additional field should be solved in a similar fashion to the one here https://github.com/TryGhost/Ghost/issues/10062

**Comment by moso** [comment]
Sorry for commenting on a closed issue.
But is the point that we now have to load `moment` to format the date correctly? If so, it would be a nice addition to the documentation (at least it's currently missing in the JS Content API client library documentation)

**Comment by kirrg001** [comment]
@moso It depends what the consumer prefers and if he wants to format the dates? 

You can also use the native Date or [Intl](https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Global_Objects/DateTimeFormat) to format the date. You can also downloade minified moment.

**Comment by gaupoit** [comment]
How about's Webhook payload? It seem doesn't apply date formatting also.
