### ISSUE TITLE
Base Model: use transactions by default

### ISSUE THREAD

**Issue by kirrg001** [TryGhost/Ghost#10063]
We are using database transactions in a lot of places in Ghost already.

IMO the most important resources in Ghost are:
- posts
- users
- tags

**These are the reasons** i can think of right now, why we should use transactions for add/update/delete by default:
- a resource has relations, we need multiple queries for an update action (if one of those queries fails, we need to undo all queries, otherwise your database is in an inconsistent state)
- with #9865, it will be possible that multiple clients write on the same resource (even on multiple api versions) (database locking)

We should ensure that the basic and most important actions are transactional.

**NOTE: The update action for our Post Model is already transactional and makes use of the `FOR UPDATE` database feature.**

IMO this feature should live in the base model. 

- [ ] double check the post model and figure out if we have to refactor anything before making this possible (i know that some implementations don't use the base model at all)
- [ ] double check the tag model and figure out if we have to refactor anything before making this possible (i know that some implementations don't use the base model at all)
- [ ] double check the user model and figure out if we have to refactor anything before making this possible (i know that some implementations don't use the base model at all)
- [ ] transactional: edit
- [ ] transactional: delete
- [ ] transactional: add

**Comment by dexterleng** [comment]
I would like to work on this!

**Comment by dexterleng** [comment]
Is the end goal being able to do something like this?

From:
https://github.com/TryGhost/Ghost/blob/3d7b4dc0f52b4cd3c9f1cc9ece4d2ef781b2a001/core/test/integration/model/model_posts_spec.js#L419

```
            it('[failure] multiple edits in one transaction', function () {
                const options = _.cloneDeep(context),
                    data = {
                        status: 'published'
                    };

                return models.Post.edit(data, _.merge({id: testUtils.DataGenerator.Content.posts[3].id}, options))
                    .then(function ({transaction}) {
                        const optionsTwo = Object.assign({transaction}, options);
                        return models.Post.edit(data, _.merge({id: testUtils.DataGenerator.Content.posts[5].id}, optionsTwo));
                    })
                    .then(function () {
                        // force rollback
                        throw new Error();
                    })
                    .catch(function () {
                    // txn was rolled back
                    Object.keys(eventsTriggered).length.should.eql(0);
                });
            });
```

**Comment by dexterleng** [comment]
I'm not sure what you meant by "use transactions by default" in the base model.

**Comment by kirrg001** [comment]
So currently, the post model is the only model which runs database requests by default through a transaction. See reasoning on top.

Any model should use the **base model** for the main actions: edit, add, destroy.
Not all of the models use the base model currently - that's why the first tasks exist (see tasks on top). This needs solving first.

The base model should run any query through a transaction by default (for edit, add, destroy). If a transaction exists already (you pass a txn from outside, options.transacting), you skip, if not you create a transaction (see post model for reference)

I hope that helps - thanks for your time & help :) If you have any further questions, don't hesitate to ask 👍

**Comment by dexterleng** [comment]
@kirrg001 

>The base model should run any query through a transaction by default (for edit, add, destroy). If a transaction exists already (you pass a txn from outside, options.transacting), you skip, if not you create a transaction (see post model for reference)

I've done this [here](https://github.com/dexterleng/Ghost/blob/75d198901f319db420c888a78f1069e38d24a69b/core/server/models/base/index.js#L774).

I'm not sure starting a transaction from the base model method would do anything, since you cannot pull the created `options.transacting` out of it, which means in the `edit` method of the post model still needs to create a transaction.

And there's only one [database action inside](https://github.com/dexterleng/Ghost/blob/75d198901f319db420c888a78f1069e38d24a69b/core/server/models/base/index.js#L779) the base `edit` method.

**Comment by kirrg001** [comment]
> I'm not sure starting a transaction from the base model method would do anything, since you cannot pull the created options.transacting out of it, which means in the edit method of the post model still needs to create a transaction.

Could you expand this statement? I am not sure i understand what you mean :) Sorry for late response!
