### ISSUE TITLE
Content API V2: always return a post excerpt (calculated field)

### ISSUE THREAD

**Issue by kirrg001** [TryGhost/Ghost#10062]
_(refs #9866)_

The `custom_excerpt` is a field in the post resource. But it's null by default.

We offer a handlebars helper to return an excerpt based on the html content if the `custom_excerpt` field is null.

**But if you use the Content V2 API directly,** you won't get this extra feature.

@ErisDS is working on making this easily possible. What we basically have to do is, we have to extract the logic from our theme helpers and create a set of generic functions, which can be then used in our theme layer (handlebars helpers) and in our Content API V2. 

This serializsation will happen in **the Content V2 output serializer.**  
Performance? This _might_ slow down the request a little. The one who works on this task, should make a quick test to get a picture/idea. We might have to use an internal cache, but we'll see.

See:
https://github.com/TryGhost/gatsby-starter-ghost/blob/3ed004e99d9870eaee382f19dcbefaa9c03236f9/src/utils/getPostExcerpt.js#L1

**Comment by JohnONolan** [comment]
Sorry for re-opening,

I thought I found a bug but it turns out I didn't. Sometimes I think I'm smart but I'm not 🙃
