### ISSUE TITLE
Subscribers Page Should Have a Filename on Exported CSV Files

### ISSUE THREAD

**Issue by PhoenixPeca** [TryGhost/Ghost#10075]
Hi,

Clicking the "Export CSV" button in Subscribers Page does not generates a well named CSV file as shown in the picture below:

![image](https://user-images.githubusercontent.com/9730242/47605612-6065a580-da3b-11e8-8952-96bff3c5e055.png)

![image](https://user-images.githubusercontent.com/9730242/47605564-d74e6e80-da3a-11e8-9bd8-8037aee63436.png)

---

I am expecting a well-named files just like the ones generated by downloading the "redirects.json", "routes.yml" as well as the export all content feature in the Labs..

**Comment by kirrg001** [comment]
Confirmed. Will be released on Tuesday 👍
