### ISSUE TITLE
Subscribers Page Infinitescroll/Pagination NOT WORKING

### ISSUE THREAD

**Issue by PhoenixPeca** [TryGhost/Ghost#10074]
Hi, 

As the title suggests, the infinite scroll in "Subscribers" page in ghost admin panel does not work..

![image](https://user-images.githubusercontent.com/9730242/47605536-6c9d3300-da3a-11e8-8960-f0db9da0f361.png)

**Comment by kirrg001** [comment]
Confirmed. Will be released on Tuesday 👍
