### ISSUE TITLE
Privacy config not respected when configured using environment variables

### ISSUE THREAD

**Issue by mcoms** [TryGhost/Ghost#10073]
### Issue Summary

Ghost ignores the privacy settings you supply via environment variables when using `ghost:latest` from the Docker Hub.

### To Reproduce

1. Launch ghost, disabling gravatar and the other privacy features:

```
➜  ~ docker run -p 34567:2368 --rm \
  -e 'url=http://localhost:34567/' \
  -e 'privacy__useTinfoil=true' \
  -e 'privacy__useUpdateCheck=false' \
  -e 'privacy__useGravatar=false' \
  -e 'privacy__useRpcPing=false' \
  -e 'privacy__useStructuredData=false' \
  -e 'DEBUG=ghost:*,ghost-config' ghost
```
Note: Same behaviour regardless of whether you enable debug, or only set `useTinfoil`.

2. Start the setup wizard (http://localhost:34567/ghost/) and register

![image](https://user-images.githubusercontent.com/517837/47604609-0db4cb00-d9f4-11e8-8243-28dc724ae014.png)
If you enter an email address that has a gravatar, it appears as your profile image during the signup.

3. Publish a story and view it

![image](https://user-images.githubusercontent.com/517837/47604631-48b6fe80-d9f4-11e8-82b4-a5a45c549bec.png)
The gravatar is visible.

4. View the story page's source

![image](https://user-images.githubusercontent.com/517837/47604655-68e6bd80-d9f4-11e8-9333-6cc2614eba4b.png)
![image](https://user-images.githubusercontent.com/517837/47604659-7734d980-d9f4-11e8-81eb-7e76e2349363.png)
Twitter/OG metadata is present, as is the image hotlink to gravatar.com.

#### Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

Expected: No gravatar links, or structured data (per [PRIVACY.md](https://github.com/TryGhost/Ghost/blob/master/PRIVACY.md))

I wonder if this is because of the way config is handled from environment variables? Note `'false'` instead of `false`:

```
➜  ~ docker run -p 34567:2368 --rm -e 'url=http://localhost:34567/' -e 'privacy__useTinfoil=true' -e 'privacy__useUpdateCheck=false' -e 'privacy__useGravatar=false' -e 'privacy__useRpcPing=false' -e 'privacy__useStructuredData=false' -e 'DEBUG=ghost:*,ghost-config' ghost

Sat, 27 Oct 2018 13:21:10 GMT ghost:boot:index First requires...
Sat, 27 Oct 2018 13:21:10 GMT ghost:config config start
Sat, 27 Oct 2018 13:21:10 GMT ghost:config { url: 'http://localhost:34567/',
  server: { host: '0.0.0.0', port: 2368 },
  updateCheck: { url: 'https://updates.ghost.org', forceUpdate: false },
  privacy: 
   { useRpcPing: 'false',
     useGravatar: 'false',
     useStructuredData: 'false',
     useUpdateCheck: 'false',
     useTinfoil: 'true' },
  useMinFiles: true,
  paths: 
   { contentPath: '/var/lib/ghost/content',
     appRoot: '/var/lib/ghost/versions/2.3.0',
...
```

```
➜  ~ docker exec a0159d991bae env
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=a0159d991bae
privacy__useStructuredData=false
DEBUG=ghost:*,ghost-config
url=http://localhost:34567/
privacy__useTinfoil=true
privacy__useUpdateCheck=false
privacy__useGravatar=false
privacy__useRpcPing=false
NODE_VERSION=8.12.0
YARN_VERSION=1.9.4
GOSU_VERSION=1.10
NODE_ENV=production
GHOST_CLI_VERSION=1.9.6
GHOST_INSTALL=/var/lib/ghost
GHOST_CONTENT=/var/lib/ghost/content
GHOST_VERSION=2.3.0
HOME=/root
```

### Technical details:

* Ghost Version: 2.3.0
* Node Version: v8.12.0
* Browser/OS: Version 70.0.3538.77 (Official Build) (64-bit), OSX Mojave 10.14
* Database: sqlite3
* Docker: 18.06.1-ce-mac73 (26764), stable
* Docker image: ghost:latest (5b10cfa2d627774ddf399ae31db70b0a533d3bd94686015b0baf9af7a6effceb)

**Comment by kirrg001** [comment]
@mcoms Thanks for the detailed report 👍 

> I wonder if this is because of the way config is handled from environment variables? Note 'false' instead of false:

Yeah this is the reason.

This issue refs https://github.com/TryGhost/Ghost/issues/8940 (see [comment](https://github.com/TryGhost/Ghost/issues/8940#issuecomment-418302189)). It's the same underlying problem.

`nconf` now supports `parseValues`:

```
    nconf.env({
        separator: '__',
        parseValues: true
    });
```

PR is welcome and should close this issue and #8940.
