### ISSUE TITLE
Cleaning up permissions

### ISSUE THREAD

**Issue by allouis** [TryGhost/Ghost#10080]
# Permissions Issue

The permissions service in ghost is not as good as it could be.

One of the biggest issues is that it has a lot of work offloaded to the model layer in `permissible` functions, this makes the logic for permissions scattered and hard to determine/audit from a single place. But there are some smaller issues we can tackle to help make fixin that easier.

### Nested loops

Due to the permissions service being quite complex, it is quite hard to see what is going on and reason about it. This is in part due to the API the permissions service provides e.g. `canThis(context).edit.posts(model, unsafeAttrs)` It need to do numerous loops to build up the data structure, only for it to be used once and thrown away.

If we were to make a change to the `canThis` api along the lines of:

```javascript
canThis(context, 'edit', 'post', model, unsafeAttrs);
```

I think it would result in huge improvement of readability and mantianablity of the module.

### External context

As the permissions service has grown it has become necessary to add permissions to unauthenticated requests, we've done this via an `external` property on the `context` - this has now split permissions outside of the permissions service. If we were able to bring those permissions back into the permission service, we can again make it more maintaniable, and easier to make future changes.

I think the solution here is to add an `Unauthenticated` or `Anonymous` role. To begin with we would just give this role permissions for `add` and `edit` actions on the `subscriber` object.

### Owner permissions

We also have scattered through the permissible functions, references and check to the Owner role, this again moves permission logic outside of where it belongs.

To address this we should probably give the Owner role all permissions

(There would still need to be checks to ensure the owner could not remove their role or delete themselves)

### App context

We have an app context, that has further complicated the permissions service, as we have to check the permissions of the user AND the app. From initial searching - I don't believe the functionality is used anywhere in ghost, nor has it been documented.

Can we delete it?

**Comment by kirrg001** [comment]
@allouis Did you see https://github.com/TryGhost/Ghost/issues/9043?
I am not sure we need to issues for this topic?

**Comment by allouis** [comment]
:+1:

**Comment by kirrg001** [comment]
@allouis Wanne merge your ideas into #9043? :)

**Comment by allouis** [comment]
aw yis i would love to @kirrg001
