### ISSUE TITLE
Maybe Bug?->Failed to send email. Reason: Can't send mail - all recipients were rejected.

### ISSUE THREAD

**Issue by foleman** [TryGhost/Ghost#10089]
I'm running ghost in a docker with my own mail server (docker too). Everything works great, till today, when I wanted to send an invitation. I got the error of the title, and digging down I get this error in postfix

`NOQUEUE: reject: RCPT from unknown[192.168.128.1]: 553 5.7.1 <ghost@notanengineer.com>: Sender address rejected: not owned by user test@notanengineer.com; from=<ghost@notanengineer.com> to=<test2@notanengineer.com> proto=ESMTP helo=<[127.0.0.1]>`

So, i thought maybe it is a bug? I don't want to report it as a bug, because I'm not sure, but I thought that maybe the from field shouldn't be ghost@domain... instead test@domain... .
I have the mail server correctly configured as it works in all my devices and services. This is my ghost config:
```
 environment:
      - url=https://notanengineer.com
      - mail__transport=SMTP
      - mail__options__host=mail.notanengineer.com
      - mail__options__secureConnection=true
      - mail__options__port=465
      - mail__options__auth__user=test@notanengineer.com
      - mail__options__auth__pass=<...>
```
Port 465 is open, and I'm running ghost 2.3.0.

**Comment by kevinansfield** [comment]
Hey @foleman 👋 You can configure the from address - https://docs.ghost.org/concepts/config/#from-address

For any future help requests please use [the forum](https://forum.ghost.org) as suggested in the issue template 😉
