### ISSUE TITLE
Use post title for editor title

### ISSUE THREAD

**Issue by JohnONolan** [TryGhost/Ghost#10088]
I'm editing 3 different posts, but I don't know which tab is which 
![image](https://user-images.githubusercontent.com/120485/47715178-8bd1d580-dc71-11e8-9aa8-e239736225cc.png)

I think it would be useful if the post title was the first thing in the `<title>` ?

**Comment by Jgriebel1990** [comment]
I can try and take this one on

**Comment by Neatoro** [comment]
I created a pull request of that multiple days ago, but after the first review, nothing happened yet.

**Comment by kevinansfield** [comment]
@Neatoro we generally have Mondays available for bug fixes, PR reviews, etc, but sometimes there are higher priority items that need addressing. Please be patient, the changes haven't gone unnoticed 🙂

**Comment by Neatoro** [comment]
Okay thank you for your notification :) Did not know that and since there wasn't a reaction for roughly two weeks, I was curious.

**Comment by NCHydr4** [comment]
Hi @Neatoro, are you still working on this issue? because we are a student crew interested by it, and maybe could work with you on.

**Comment by kevinansfield** [comment]
@NCHydr4 the PR is open for it here https://github.com/TryGhost/Ghost-Admin/pull/1072, it's just waiting for review by the Ghost team
