### ISSUE TITLE
Permission stage overrides the whole context object

### ISSUE THREAD

**Issue by kirrg001** [TryGhost/Ghost#10099]
For the new API frame we pass values from the authentication layer:

- the user who is logged in
- or the content key object (if available)

You can access these information by using `frame.options.context`. That is cool, **but** as soon as the request enters the permission stage, the permission layer overrides this object, [see](https://github.com/TryGhost/Ghost/blob/2.4.0/core/server/api/v2/utils/permissions.js#L58).

> frame.options.context = permissions.parseContext(frame.options.context);

This is A) hard to understand and B) hard to maintain.

**This has the consequence, that input serializers need to rely on the auth input (e.g. `frame.options.api_key` and output serializers needs to rely on the permissions context. (e.g. `frame.options.public`**

### Suggestion

- `frame.options.auth` (auth)
- `frame.options.context` (permissions)

---

Furthermore: if do a functional call, `frame.options.context` is an empty object (!). It's super hard to detect if it's a content access, because you need to check against an empty object.

**Comment by allouis** [comment]
```js
    frame.options.context = permissions.parseContext(frame.options.context);
```
That line is only used to determine if the public permissions stuff should run, and it should be removed eventually (see [here](https://github.com/TryGhost/Ghost/blob/master/core/server/services/permissions/index.js#L21)) when we have less fragmented permission system

To clean this up for now we could just do
```js
if (permissions.parseContext(frame.options.context).public) {

}
```

**Comment by kirrg001** [comment]
> That line is only used to determine if the public permissions stuff should run, and it should be removed eventually (see here) when we have less fragmented permission system

Not really. This line ensures that we transform auth context to permission context.

`frame.options.context.internal`
`frame.options.context.public`
`frame.options.context.user`

**Comment by kirrg001** [comment]
I think the context parsing needs to happen earlier in the API frame.

**Comment by kirrg001** [comment]
FYI: the permission stage runs after the validation+serialization because the stage accesses the incoming body structure.

**Comment by allouis** [comment]
> This line ensures that we transform auth context to permission context.

Yeah it does that, but that is unnecessary right? The only reason we transform that is so we can make that switch? Any permissions that aren't in the public stuff are handled by the permissions service and the permissible methods? Unless we're fragmenting the permissions even more, I don't see why the parsed context needs to be on the frame at all?

**Comment by allouis** [comment]
I'm thinking about this for the members stuff for example, we have the option of doing something like this in the post output serializer (or the `mapper.mapPost` stuff)
```javascript
if (labs.isSet('members') && frame.options.context.members && post.hasTag('memberonly')) {
  delete post.stuff;
  delete post.whatever;
}
```

But if we were to keep permissions central, we could do something like

```javascript
const propsToRemove = permissions.getBlacklistedProps(post, frame.options.context); // ['stuff', 'whatever']
for (propRemove in propsToRemove) {
  delete post[propToRemove]
}
```

Or in more in the style of what we have already

```javascript
post = utils.blacklistPropsForPost(post, frame);
```

This has the benefit of being able to write generic logic in the output serializer layer to handle permissions, and to dynamically update that logic by only touching the permissions service.

**Comment by kirrg001** [comment]
> Unless we're fragmenting the permissions even more, I don't see why the parsed context needs to be on the frame at all?

e.g. because the whole model layer uses the values from this parsed object. The controllers forward this parsed context object to the model layer. _This is how it works currently._

---

This issue is about that we have two different context objects currently. This issue is about inconsistenty. We receive information from auth layer (e.g. member, api_key, user) and the permission layer creates a new context.

**Comment by allouis** [comment]
> e.g. because the whole model layer uses the values from this parsed object. The controllers forward this parsed context object to the model layer. This is how it works currently.

Ah, I see, I didn't notice at first it did that - I couldn't see where it happened in v0.1!

Though - v0.1 has slightly different functionality to what we have with the new stuff, v0.1 would only forward the parsed context object from the `browse` and `read` controllers (because those called the `handlePublicPermissions`, which is where the context got parsed and overwritten). I'm guessing that was a bug though so all is good :+1:

---

As for the two different context objects, we _could_ just use `frame.original.context` for now, but i think `auth.api_key` and `auth.user` makes a lot of sense too :+1:

**Comment by kirrg001** [comment]
> As for the two different context objects, we could just use frame.original.context for now, but i think auth.api_key and auth.user makes a lot of sense too 👍

👍 I think the one who works on that, needs to play with it a little and post here what makes sense and what doesn't :)

**Comment by allouis** [comment]
> I think the context parsing needs to happen earlier in the API frame.

After working with the permissions for the members stuff, I totally agree, the `isContentAPI` function was basically replicating the check for public in `permmisions/parse-context`
