### ISSUE TITLE
Editor scrolljump when pasting a link

### ISSUE THREAD

**Issue by JohnONolan** [TryGhost/Ghost#10090]
When pasting a URL over the top of highlighted text to create a link, the editor scroll position jumps by a large amount, which can be very disorienting.

Example in Chrome 70, Ghost on latest Pro:
![ex](https://user-images.githubusercontent.com/120485/47777832-2c82cc80-dd28-11e8-9398-49f93a633722.gif)

**Comment by kevinansfield** [comment]
Not stale

**Comment by kevinansfield** [comment]
Not stale

**Comment by JohnONolan** [comment]
Still not stale

**Comment by lunaticmonk** [comment]
Couldn't reproduce this. Is this one fixed?
