### ISSUE TITLE
The rendering of posts should not include content if the post is private

### ISSUE THREAD

**Issue by allouis** [TryGhost/Ghost#10117]
We determine private in the same way that the content api does - via a tag for now

**Comment by allouis** [comment]
This is achievable once https://github.com/TryGhost/Ghost/pull/10154 is merged and a theme sets it's package.json like so
```json
{
  "engines": {
    "ghost-api": "v2"
  }
}
```

**Comment by rishabhgrg** [comment]
Closed with https://github.com/TryGhost/Ghost/pull/10154
