### ISSUE TITLE
Standarize API vs Api in auth service

### ISSUE THREAD

**Issue by allouis** [TryGhost/Ghost#10120]
We currently use a mix of `API` and `Api`.

The admin api stuff that hasn't been merged conflicts with what we have too. 

I think `Api` is better?

**Comment by kevinansfield** [comment]
I had tried to settle on `Api` in the now-closed admin key auth PR, I think that's the easiest route to consistency.

**Comment by allouis** [comment]
This should have been closed with the above commit :thinking:

**Comment by kirrg001** [comment]
@allouis The PR is still open - https://github.com/TryGhost/Ghost/pull/10142.

**Comment by allouis** [comment]
fucking hell :joy: what is wrong with me
