### ISSUE TITLE
360 Degree Panoramic Photo Viewer ?

### ISSUE THREAD

**Issue by rodvay** [TryGhost/Ghost#10130]
Hello
Very good ghost platform

im need added projets 360 degree panoramic photo viewer

Sample:  https://photo-sphere-viewer.js.org/
Sample: https://revolution.themepunch.com/360-degree-real-estate-virtual-tour/

as possible

this feature is available ? ghost platform
Thank you

**Comment by allouis** [comment]
Hey @rodvay :wave: Friendly reminder: we don't track feature requests on GitHub. Our default issue templates pointed you to our forum for this type of question - the Ideas topic will let you propose features and let others vote on them :smile:. We use GitHub solely for bug-tracking and on-going feature development so we try to keep it noise free.

FYI: Many projects have their own support guidelines and GitHub will highlight them for you, or the project owners will use issue templates to point you in the right direction. Reading the guidelines or issue templates before opening issues can save you and other project maintainers some valuable time..
