### ISSUE TITLE
Thumbnail on Reddit

### ISSUE THREAD

**Issue by gbourne1** [TryGhost/Ghost#10134]
On Reddit, it seems Ghost posting thumbnails aren't showing. 

For example: https://www.reddit.com/r/retirement/comments/9uszqj/who_are_your_midterm_candidates/ doesn't show the thumbnail. Reddit uses og:image, so everything should be ok, but seems all posts I've done have had an issue.

Using Ghost 2.4.0, Node 10.13.0

**Comment by kevinansfield** [comment]
Hey @gbourne1  👋 Friendly reminder: help or support is not available on Github. Our default issue templates pointed you to our [forum](https://forum.ghost.org) for this type of question 😄 We use GitHub solely for bug-tracking and on-going feature development so we try to keep it noise free.

Many questions can be answered by reviewing our docs for [self-hosters](https://docs.ghost.org), our [theme API](https://themes.ghost.org), or our [public API](https://api.ghost.org). If you can't find an answer then our [forum](https://forum.ghost.org) is a great place to get community support, plus it helps create a central location for searching problems/solutions.

FYI: Many projects have their own support guidelines and GitHub will highlight them for you, or the project owners will use issue templates to point you in the right direction. Reading the guidelines or issue templates before opening issues can save you and other project maintainers some valuable time.
