### ISSUE TITLE
Using Data Helper 'primary_tag' returns empty

### ISSUE THREAD

**Issue by foleman** [TryGhost/Ghost#10140]
### Issue Summary
Using Data Helper 'primary_tag' inside page with a post returns empty instead of url (neither relative nor absolute work).

### To Reproduce
1. Added this code to header template (After <\/header>):
```
{{#is "post"}}
    <li class="breadcrumb-item" style="display: inline-block">
        <a href="{{post.primary_tag.url}}">{{post.primary_tag.name}}</a>
    </li>
    <li class="breadcrumb-item" style="display: inline-block">{{post.title}}</li>
{{/is}}
```

2. Renders:
```
<li class="breadcrumb-item" style="display: inline-block">
    <a href="">General but Relevant</a>
</li>
```
3. Added the #post data helper:

```
{{#is "post"}}{{#post}}
    <li class="breadcrumb-item" style="display: inline-block">
        <a href="{{primary_tag.url}}">{{primary_tag.name}}</a>
    </li>
    <li class="breadcrumb-item" style="display: inline-block">{{title}}</li>
{{/post}}{{/is}}
```
4. Exact same result. All the other code I have works, just the primary_tag.url syntax loads empty.

I forgot to mention, I have a custom route for tags (instead of '/tag/slug/' it's '/slug/'). And the strange thing is that inside the post body it does get the correct url, but it's because it uses the tags method:

```
{{#if tags}}
    <p class="post-tags">{{tags separator=" "}}</p>
{{/if}}
```

### Technical details:

* Ghost Version: 2.5.0
* Node Version: 8.12.0
* Browser/OS: Docker Alpine on Ubuntu 18
* Database: MariaDB

**Comment by kirrg001** [comment]
Hey @foleman!

```
{{#post}}
    {{#primary_tag}}
        {{url}}
    {{/primary_tag}}
{{/post}}
```

---

Many questions can be answered by reviewing our docs for [self-hosters](https://docs.ghost.org), our [theme API](https://themes.ghost.org), or our [public API](https://api.ghost.org). If you can't find an answer then our [forum](https://forum.ghost.org) is a great place to get community support, plus it helps create a central location for searching problems/solutions.

**Comment by foleman** [comment]
@kirrg001 Yes, I've read them. 
So you are telling me that all the data helpers work just fine (**post.title**, **post.primary_tag.name**, **author.name**,... etc) but accessing **post.primary_tag.url** not? Why can I not access **post.primary_tag.url** with that syntax, but can access **post.primary_tag.name** and every other object (as I said, **post.author**, **post.title**, **post.slug**, ....).
And outside a post context too. If I'm in an author page I can access **author.name**, **author.slug**.. etc. I don't think it's natural that **post.primary_tag.url** doesn't return the url, but does return it's other attributes.

**Comment by SirLemuel** [comment]
@foleman Raised a few valid questions that deserved a response. I am also seeing this issue in the default RSS Feed configuration where the <category></category> element containing {{primary_tag}} does not render.
