### ISSUE TITLE
Pre-optimized image size increases after upload

### ISSUE THREAD

**Issue by gargol** [TryGhost/Ghost#10144]
### Issue Summary

When uploading a pre-optimized image to Ghost, its size is sometimes increased. Samples:
- The image is being uploaded: https://d.pr/i/76ZVry
- Output, higher size image: https://d.pr/i/FPGvW2

### To Reproduce

1. Upload the image that had its quality set to lower than the default (80%)
2. Check the processed image size, in this case, increase from ~120kB to ~650kB 

### Technical details:

* Ghost Version: 2.5.0
* Node Version: v8.11.4
* Browser/OS: Ubuntu/Linux
* Database: MySQL 5.7.24

**Comment by b166ar** [comment]
Is it live now? Or I need to wait Ghost Pro update?

**Comment by kevinansfield** [comment]
@b166ar no, you need to wait for the next release to be cut (Ghost 2.6.0, should be cut today) and then for it to roll out on Ghost(Pro) if you are a customer, Ghost(Pro) rollouts usually happen a day or two after the release.
