### ISSUE TITLE
Apps: AppSandbox require proxy function bug

### ISSUE THREAD

**Issue by zce** [TryGhost/Ghost#10157]
### Issue Summary

I tried to add a new custom App.

Unfortunately, I got an `unsafeAppRequire` error.

```
Unsafe App require: ../../../../../../../../../content/apps/lib/router
```

### To Reproduce

1. Add a new custom app

  ```diff
   content
   ├── adapters
   ├── apps
  +│   └── member
  +│       ├── index.js
  +│       ├── lib
  +│       │   ├── middleware.js
  +│       │   └── router.js
  +│       └── package.json
   ├── data
   ├── images
   ├── logs
   ├── settings
   └── themes
  ```

2. Restart ghost application

3. An error has occurred

  ```
  NAME: InternalServerError
  MESSAGE: The server has encountered an error.

  level:normal

  "The app will not be loaded"
  "Check with the app creator, or read the app documentation for more details on app requirements"
  ERROR DETAILS:
      empty

  InternalServerError: The server has encountered an error.
      at new GhostError (<...>/ghost/core/server/lib/common/errors.js:10:26)

  Error: Unsafe App require: ../../../../../../../../../content/apps/lib/router
      at Module.requireProxy [as require] (<...>/ghost/core/server/services/apps/sandbox.js:65:23)
      at require (internal/modules/cjs/helpers.js:20:18)
  ```

#### The location of the problem in the code

https://github.com/TryGhost/Ghost/blob/master/core/server/services/apps/sandbox.js#L57-L68

```js
// Load relative modules with their own sandbox
if (firstTwo === './' || firstTwo === '..') {
    // Get the path relative to the modules directory
    resolvedPath = path.resolve(moduleDir, module);
    console.log('moduleDir', moduleDir)
    console.log('module', module)
    console.log('resolvedPath', resolvedPath)

    // Check relative path from the appRoot for outside requires
    relPath = path.relative(appRoot, resolvedPath);
    console.log('relPath', relPath)
    if (relPath.slice(0, 2) === '..') {
        throw new Error(common.i18n.t('errors.apps.unsafeAppRequire.error', {msg: relPath}));
    }

    // Assign as new module path
    module = resolvedPath;
```

output

```
moduleDir: ../../../../../../../content/apps
module: ./lib/router
resolvedPath: /content/apps/lib/router
relPath: ../../../../../../../../../content/apps/lib/router
```

I think the core issue is here.

```js
// Get the path relative to the modules directory
resolvedPath = path.resolve(moduleDir, module);
```

`moduleDir` should be current module dir, not apps dir.

I will try to submit a pull request.

### Technical details:

* Ghost Version: master
* Node Version: 10.13.0

**Comment by kirrg001** [comment]
Hey @zce 👋

Sorry for late response.

First of all: apps are not a thing yet. The purpose of the existing app code is that people can build smaller demo post. You might know this already.

---

To your question: The sandbox does not allow to require modules outside of your app scope. That's why it's a sandbox. I'd suggest to wait till Apps are officially supported. The Ghost team needs to spend time on the design of how apps will and should work. You can require files in your app folder. But you can't randomly require files in Ghost. The app sandbox offers an interface to communicate to. This is the **current** design of the **example code living in Ghost.**

**Comment by zce** [comment]
👋 Thanks for response

I understand the purpose of sandbox design. But I think this problem is not related to sandbox.

```js
// `path.resolve` first argument cannot be relative path
// `moduleDir` is a rel path when `loadModule` was called for the first time
// => '../../../../../../../content/apps'
resolvedPath = path.resolve(moduleDir, module);
```

https://github.com/TryGhost/Ghost/blob/master/core/server/services/apps/sandbox.js#L59

The original function of the sandbox was not removed from my pull request.

Maybe you should try to add a custom app to find out the problem.

> Sorry for my English 😀
