### ISSUE TITLE
Administrators are unable to edit webhooks

### ISSUE THREAD

**Issue by kevinansfield** [TryGhost/Ghost#10152]
When logged in as an administrator it's possible to create and delete webhooks but it's not possible to edit webhooks. This is because the [migration adding the edit webhook permission](https://github.com/TryGhost/Ghost/blob/master/core/server/data/migrations/versions/2.3/2-add-webhook-edit-permission.js) adds the `permissions` record but doesn't add the `permissions_role` relation record.

**Comment by kirrg001** [comment]
@rishabhgrg I've assigned you. This issue is required for the release 👍
