### ISSUE TITLE
Relplace enforced/default/custom/extra filter merging logic

### ISSUE THREAD

**Issue by gargol** [TryGhost/Ghost#10167]
### Goal

Write a simple utility that would combine string based filters based on their priority `enforced->custom->extra->default`. This is an attempt to achieve current filter merging logic with string based filters. More complex statement based (mongo-json) utility might be created later as an expansion on this utility. 

### Strategy

Cover all existing combinations of enforced/default/custom filters based on research in https://github.com/NexesJS/NQL/issues/2.

**Comment by kirrg001** [comment]
Attempt was added via https://github.com/TryGhost/Ghost/pull/10159/commits/9443bed93013f47c97c7c75d3617021e1d5ae9e7. Can this be closed now? I know the PR is still open, but i think it will be kept open for another while.

**Comment by kirrg001** [comment]
@gargol

**Comment by gargol** [comment]
yup. agree, we can close this as this whole functionality is 'done' :+1:
