### ISSUE TITLE
Check internal tags are present for all types of post fetches (inc. taxonomies)

### ISSUE THREAD

**Issue by allouis** [TryGhost/Ghost#10165]
RE: https://github.com/TryGhost/Ghost/commit/b2201d4179438eddaa5dcb9609efd29c838cc04f#r31294108 

We need to correctly fetch the internal tags.

Make sure to speak w/ @kirrg001 about solution

**Comment by allouis** [comment]
Update - internal tags _should_ always be available in the content API.

**Comment by ErisDS** [comment]
@allouis was this just a misunderstanding or is there some work to do here?

**Comment by allouis** [comment]
@ErisDS As far as I know this was a misunderstanding. It _might_ be worth leaving open into content api cleanup is done, and i can double check everything works as expected?

**Comment by allouis** [comment]
Testing locally shows this is all good :+1:
