### ISSUE TITLE
Ghost changes URL to lowercase (with a redirect)

### ISSUE THREAD

**Issue by velobarplus** [TryGhost/Ghost#10164]
I'm using dynamic routing, and i have something like this:
```
/about/team/:id/:
    data: page.about
    redirect: false
    template:
      - custom-team
```
The url is this: `/about/team/Z2lkOi8vdGVhbS9tZW1iZXIvMTcwMTg5Nzg5NjAyNQ==/`
Notice the :id has upper and lower case.
When loading the page it is transformed to: `/about/team/z2lkoi8vdgvhbs9tzw1izxivmtcwmtg5nzg5njaynq==/`

For whatever reason the pathname gets all lowercase. Is there a way to not make it lowercase?

To answer my own question. Yes, Ghost does this. With uncapitalise.js
But why?

Is there a way to add an option to the routes.yaml so it explicitly tells not to lowercase anything at that given URL?

I might do something with 3rd party APIs and I need to pass some case sensitive strings in the URL.
I think this is a problem with Ghost. It should not redirect to an all lowercase URL.
First I thought the browser was acting up. Then I checked on youtube and all worked fine (yes they have upper and lower case strings in the URL). So the only problem provider left was Ghost.
If you check in `uncapitalise.js` it has exceptions for signup and api related URLs.
Why? There is no logical reason for this.

It looks like a bug to me.

* Ghost Version: 2.6.0
* Node Version: 10.13
* Browser/OS: Chrome
* Database: mysql

**Comment by kevinansfield** [comment]
Hey @velobarplus 👋 There is already on-going support discussion on [your forum topic](https://forum.ghost.org/t/is-ghost-lower-casing-the-url/3952), if it's determined there is a bug in Ghost then an issue can be opened.
