### ISSUE TITLE
Ghost can only find one page template when several are available

### ISSUE THREAD

**Issue by pkail** [TryGhost/Ghost#10178]
### Issue Summary
A summary of the issue and the browser/OS environment in which it occurs.
According to the documentation, Ghost will pick up a template of the form page-[whatever].hbs and use this instead of the default page for slug [whatever].  It does this for one of several such templates, but not for the others.  In other words, one slug gets its template from page-whatever.hbs, whereas the others get it from page.hbs.

### To Reproduce
Create several identical templates, e.g., page-1.hbs, page-2.hbs, etc.
Create slugs in the Ghost navigation with names 1, 2, etc.
Create posts converted into pages through the Ghost editor, pointing at slugs 1,2,3.

Any other info e.g. Why do you consider this to be a bug?
Given that the documentation is opaque on this matter, it could be a 'feature' instead of a bug.  However, it would obviously be hugely helpful if it worked.

Ghost Version: 2.6.0
Node Version: 8.11.3
Browser/OS: Chrome 70.0.3538.102 (Official Build) (64-bit)
Database: default (presumably MySQL).

**Comment by allouis** [comment]
Following the steps you've given I couldn't replicate this issue unfortunately.

>  Create slugs in the Ghost navigation with names 1, 2, etc.

What do you mean by this? Slugs are created in the settings sidebar of the editor - do you think it's possible you've used tags, rather than changing the slugs?

**Comment by pkail** [comment]
I know the difference between tags and slugs, obviously.

What operating system are you using?

**Comment by allouis** [comment]
Cool :relaxed: I'm trying to replicate it on Linux! What are you running?

What is the contents of your `page-1.hbs`, `page-2.hbs` etc..? Have you run the theme through gscan?

**Comment by pkail** [comment]
Sorry, this should have been at the top.  I'm running Windows 10 Pro 64bit.

There are a number of apparently related issues, all to do with no finding files.  Is Ghost supposed to be able to run directly on Windows, or does it need the WSL?

**Comment by allouis** [comment]
You shouldn't need WSL, no.

As far as this issues goes, it can't be reproduced so I'd suggest going to the [community forums](https://forum.ghost.org/) and asking for help building themes there - if you do manage to find a reproducible bug, feel free to raise an issue with everything we need to replicate it! 

I'm going to close this issue now - I hope you get your problem fixed through the forum :smile:

**Comment by pkail** [comment]
>>, it can't be reproduced 
It can't be reproduced on Linux, but it can on Windows.
