### ISSUE TITLE
Ghost cannot find template in /partials

### ISSUE THREAD

**Issue by pkail** [TryGhost/Ghost#10173]
### Issue Summary

A summary of the issue and the browser/OS environment in which it occurs.
Ghost cannot find template in /partials directory.

### To Reproduce
1. This is the first step:

```
<header>
        <div class="hero is-info">
            <div class="hero-body">
                <div class="container">
                    <h1 class="title is-size-1">{{@blog.title}}</h1>
                </div>
            </div>
        </div>
        {{> "site-nav"}}
</header>
{{> frontpage}}
```
In index.hbs

Blank file frontpage.hbs in /partials

N.B. Github appears to have replace my HTML with {{blog.title}} for some unknown reason.

2. This is the second step, etc.
ghost restart
I get error: "500 [index.hbs] The partial frontpage could not be found."
Comment out reference to frontpage: page loads normally.
Replace {{> frontpage}} with {{> "frontpage"}}: I get the 500 server error again.
Comment out reference to frontpage: page loads normally.
### Technical details:

    Ghost Version: 2.6.0
    Node Version: 8.11.3
    Browser/OS: Chrome 70.0.3538.102 (Official Build) (64-bit)
    Database: default (presumably MySQL).

**Comment by notanengineercom** [comment]
Hey @pkail 
I just tried your setup. I have no troubles. Was frontpage.hbs created before declaring it in your index file?
When I declared it before creating, I got the 500 code, with this error:

> InternalServerError: [index.hbs] The partial frontpage could not be found
>     at new GhostError (/Users/enriquefoleman/Documents/ghost source/Ghost/core/server/lib/common/errors.js:10:26)

I then created the file (frontpage.hbs) in my partials folder, restarted ghost and it worked like it's supposed to. You need to restart ghost to rebuild the theme. If you are developing a theme I really recommend you to enable live reload. You can read it on the official docs of Ghost: https://docs.ghost.org/install/local/#developing-themes

**Comment by pkail** [comment]
Thanks for your help.

>>Was frontpage.hbs created before declaring it in your index file?
Yes, it was.

>> I got the 500 code, with this error:
I got a different error message (see my original post).

>>You need to restart ghost to rebuild the theme. 
I do restart it after adding any new file to partials.

**Comment by pkail** [comment]
What operating system are you using?  

Most probably this is a problem caused by Ghost's inability to find the right path.  It returns the correct value from {{asset}}, so it's not totally confused.  But it can't find a new file in /partials.

There are some suggestions online that you need to run Ghost on Ubuntu using the Windows Subsystem for Linux.  However, the fact that it does actually partially work when running directly on Windows suggests that this is not necessary.

**Comment by notanengineercom** [comment]
Could you paste the console output of the error?

**Comment by gargol** [comment]
ping @pkail. would be very helpful to see the the console output as @notanengineercom suggested :smiley:

**Comment by pkail** [comment]
There's no error message: as I mentioned, Ghost takes its output from the page.hbs template for these other pages, it doesn't crash.  On the other hand, it does crash if these unused templates are removed.

**Comment by ErisDS** [comment]
@pkail I'm going to close both your issues. The 3-4 issues & forum topics you've raised that are new, unreproducible issues indicate either an environment issue or a misunderstanding.

It may also be that there's a windows-specific bug to do with themes somewhere, but we're not going to be able to get to the bottom of it without simple, clear reproduction steps.

I recommend you [read this](https://ghost.org/conduct/) and then update your topic on the forum with clear and complete details of your setup, everything from how and where you installed, what theme you're using what custom routes, etc etc and then very importantly, the details of what you're actually trying to accomplish. From there, maybe we can get to the bottom of what you're experiencing.
