### ISSUE TITLE
Ghost cannot find templates **in Windows**

### ISSUE THREAD

**Issue by pkail** [TryGhost/Ghost#10185]
Issue Summary
Reposting, because issue has ***not*** been tested.  It obviously occurs in Windows but not in Linux.

A summary of the issue and the browser/OS environment in which it occurs.
According to the documentation, Ghost will pick up a template of the form page-[whatever].hbs and use this instead of the default page for slug [whatever]. It does this for one of several such templates, but not for the others. In other words, one slug gets its template from page-whatever.hbs, whereas the others get it from page.hbs.
To Reproduce

Create several identical templates, e.g., page-1.hbs, page-2.hbs, etc.
Create slugs in the Ghost navigation with names 1, 2, etc.
Create posts converted into pages through the Ghost editor, pointing at slugs 1,2,3.

Any other info e.g. Why do you consider this to be a bug?
Given that the documentation is opaque on this matter, it could be a 'feature' instead of a bug. However, it would obviously be hugely helpful if it worked.

Ghost Version: 2.6.0
Node Version: 8.11.3
Browser/OS: Chrome 70.0.3538.102 (Official Build) (64-bit)
Database: default (presumably MySQL).

**Comment by ErisDS** [comment]
@pkail if this is in reference to an earlier issue that you raised, please update that issue with the missing info rather than opening a new one, the very reason that we close bugs that aren't reproducible is to reduce clutter and noise so that our devs can see what needs their attention.
