### ISSUE TITLE
Mount/wireup members app/service to the Ghost api

### ISSUE THREAD

**Issue by allouis** [TryGhost/Ghost#10188]
Currently thinking to mount it on `/ghost/members`

This would be the url that members pages and apis live on.

**Comment by allouis** [comment]
@kevinansfield We were interested in your opinion on where to mount it

**Comment by allouis** [comment]
@peterzimon Can you have a look at this please? :smile:

**Comment by allouis** [comment]
We will be mounting the members service in two different places.
### `/ghost/api/v2/members`
For the endpoints
### `/members`
For the pages

@peterzimon Can you confirm this?

**Comment by peterzimon** [comment]
Moving issue to a note
