### ISSUE TITLE
Members `/secure/token` sets issuer of token

### ISSUE THREAD

**Issue by allouis** [TryGhost/Ghost#10197]
Should use the "url" config property

**Comment by allouis** [comment]
@kevinansfield Do you have any thoughts on this?

**Comment by kevinansfield** [comment]
I think keeping the issuer the same as the config `url` value should be 👍 With versioned APIs we want to avoid storing version-relative paths if we're validating the `issuer` so that JWTs are still valid after major version upgrades?

**Comment by allouis** [comment]
Great point yeah :+1:
