### ISSUE TITLE
Members API Service accepts an RSA keypair as config

### ISSUE THREAD

**Issue by allouis** [TryGhost/Ghost#10198]
With openssl?
via a node module?

**Comment by allouis** [comment]
@kevinansfield Another one you might be interested in :+1: 

Thinking is accept a path to the keypair, and if they're not there, then it can generate them. https://www.npmjs.com/package/keypair is a nice module to do so

**Comment by kevinansfield** [comment]
Other discussion outcomes:

- use pure js key generation solution for now to minimise any potential installation problems where openssl is assumed to exist
- auto generation of keys happens as part of the default settings generation but the impact needs measuring in case it has a detrimental effect on initial boot time
