### ISSUE TITLE
Source Code build keep failed

### ISSUE THREAD

**Issue by msacar** [TryGhost/Ghost#10215]
Hello ; 
I tried to built source code and i was failed 
https://docs.ghost.org/install/source/#ghost-core 
first  documentation  is insufficient :  example  ghost working with submodules  but there is no telling  any info about submodules.. 
my node version is v8.12.0
using yarn via npm global module 

nvm i cloned ghost into a directory with 
 ```
#First clone Ghost and make it your working dir
git clone git@github.com:TryGhost/Ghost.git && cd Ghost

#also i make
git submodule update --init 
#then  checkout all modules to 2.6 except casper
git checkout git 2.6.0 
cd core/client/ && git checkout 2.6.0 
cd ../../
yarn cache clean 
yarn setup  
#then output of yarn is  
```

yarn run v1.12.3
$ yarn install && knex-migrator init && grunt symlink && grunt init || true

DEPRECATION: ember-cli-babel 5.x has been deprecated. Please upgrade to at least ember-cli-babel 6.6. Version 5.2.8 located: ghost-admin -> ember-light-table -> ember-scrollable -> ember-component-inbound-actions -> ember-cli-babel
DEPRECATION: ember-cli-babel 5.x has been deprecated. Please upgrade to at least ember-cli-babel 6.6. Version 5.2.8 located: ghost-admin -> ember-light-table -> ember-scrollable -> ember-element-resize-detector -> ember-cli-babel
DEPRECATION: ember-cli-babel 5.x has been deprecated. Please upgrade to at least ember-cli-babel 6.6. Version 5.2.8 located: ghost-admin -> ember-responsive -> ember-getowner-polyfill -> ember-cli-

![screenshot from 2018-11-18 13-36-49](https://user-images.githubusercontent.com/22613730/48672647-a816b300-eb49-11e8-89ff-e182cbe5de04.png)

but there is no problem with if i use ghost-cli local  the problem inside source code compiling

**Comment by lunaticmonk** [comment]
@msacar Did you run `yarn global add knex-migrator grunt-cli ember-cli bower` before running all of the above commands that you mentioned? Also, the above screenshot seems vague, can you paste the logs here or the screenshot which includes which command did you run there?

**Comment by msacar** [comment]
`yarn global add knex-migrator grunt-cli ember-cli bower`

**Comment by rishabhgrg** [comment]
Hi @msacar 👋

We're sorry to hear you're having problems, however this looks like a problem with how you're using Ghost rather than a bug. We only keep Github issues open for bugs and in-progress feature work, please read our [support guide](https://github.com/TryGhost/Ghost/blob/master/.github/SUPPORT.md). You can always use our [forum](https://forum.ghost.org/) - https://forum.ghost.org, if you're not able to find the answer in our [documentation](https://docs.ghost.org/) - https://docs.ghost.org.
