### ISSUE TITLE
Embedded card iframe fixed at 600px

### ISSUE THREAD

**Issue by cpwc** [TryGhost/Ghost#10211]
Welcome to Ghost's GitHub repo! 👋🎉

We use GitHub only for bug reports 🐛

Anything else should be posted to https://forum.ghost.org 👫

🚨For support, help & questions use https://forum.ghost.org/c/help
💡For feature requests & ideas you can post and vote on https://forum.ghost.org/c/Ideas

If your issue is with Ghost CLI, please report it on the CLI repo ➡️ https://github.com/TryGhost/Ghost-CLI/issues/new.

### Issue Summary

Adding an embed to a link the embedded iframe will have a fixed height and width causing it not to be mobile responsive.

### To Reproduce

1. Add a embed link `https://www.mumbrella.asia/2018/10/whole-of-government-creative-services-tender-results-in-39-agencies-on-roster`
2. Preview post in mobile.

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

### Technical details:

* Ghost Version: 2.6.0
* Node Version: 8
* Browser/OS: Chrome/Mac
* Database: MySQL

**Comment by kevinansfield** [comment]
@cpwc if you want responsive iframes you need to handle that in your theme. For an example the [default Casper theme](https://github.com/TryGhost/Casper) uses [fitvidsjs](http://fitvidsjs.com) for this but there are other options such as [reframe.js/noframe.js](https://dollarshaveclub.github.io/reframe.js/) that do not require jquery.

**Comment by kevinansfield** [comment]
Friendly reminder: help or support is not available on Github. Our default issue templates pointed you to our [forum](https://forum.ghost.org) for this type of question 😄 We use GitHub solely for bug-tracking and on-going feature development so we try to keep it noise free.

Many questions can be answered by reviewing our docs for [self-hosters](https://docs.ghost.org), our [theme API](https://themes.ghost.org), or our [public API](https://api.ghost.org). If you can't find an answer then our [forum](https://forum.ghost.org) is a great place to get community support, plus it helps create a central location for searching problems/solutions.

FYI: Many projects have their own support guidelines and GitHub will highlight them for you, or the project owners will use issue templates to point you in the right direction. Reading the guidelines or issue templates before opening issues can save you and other project maintainers some valuable time.

**Comment by cpwc** [comment]
@kevinansfield I am using the default Casper theme and that's happening tho.

**Comment by allouis** [comment]
@cpwc Casper uses [fitvidsjs](http://fitvidsjs.com/) which supports these video players: https://github.com/davatron5000/FitVids.js#currently-supported-players

**Comment by cpwc** [comment]
@allouis Yeah. I understand that however those embed are not video player but links embeds.

**Comment by kevinansfield** [comment]
@cpwc Casper covers the typical use-case of video embeds, if you are using particular embeds that need a different solution it's up to you to handle those as you see fit in your theme. If you need help doing that please [ask on our forum](https://forum.ghost.org).

**Comment by cpwc** [comment]
Noted. Thanks for the heads up.
