### ISSUE TITLE
Multiple editors with access can't edit the common article

### ISSUE THREAD

**Issue by kacperduras** [TryGhost/Ghost#10212]
### To Reproduce

1. Create new article
2. Add 2+ people
3. Try edit:
![obraz](https://user-images.githubusercontent.com/20678785/48864056-b5db6b00-edcb-11e8-84f6-ff03e3db0ee2.png)

Only the first person on the list can edit the content (any time).
**Editing by single person, never more in one moment.**

### Technical details:

* Ghost Version: latest (2.6.1)
* Node Version: 10.13.0 LTS
* Browser/OS: Firefox, latest stable/W10
* Database: MySQL

**Comment by gargol** [comment]
Hi @kacperduras :wave: Could you please add more details about which roles those 2+ people are assigned to, what's the role of the user who is trying to edit the post?

**Comment by kacperduras** [comment]
Hi @gargol, they have permissions from `Author` template.

**Comment by gargol** [comment]
Thanks, @kacperduras. Just to make sure I understand this correctly: when having multiple authors (all having roles of `Author`) assigned to a post, only the first author in the list is able to edit the post, correct?

**Comment by kacperduras** [comment]
@gargor yes

**Comment by kacperduras** [comment]
IMHO, one method is better option than separate function - we check author permissions for users, but we have the order not because of the access level, but the addition list.

I will create PR soon, maybe today.
