### ISSUE TITLE
update add one hour to publish date

### ISSUE THREAD

**Issue by PierreBrisorgueil** [TryGhost/Ghost#10225]
### Issue Summary

Update a post changes its publication date to one more hour

### To Reproduce

1. Open an old blog post
2. Edit it or not
3. Quick check the publish date in post settings (for example 06:30)
4. Close the panel and update 
5. Check the publish date again, in my case their is an hour more  (07:30)

<img width="347" alt="screenshot 2018-11-29 at 09 11 12" src="https://user-images.githubusercontent.com/6069599/49207963-c173f680-f3b6-11e8-9b69-7e97b1ab342d.png">

I observe this problem since several versions, installed via Yarn. I do not understand why. This can sometimes be a problem, if you just created a post, and you modify it just after the publication, the date will go in the future with this +1 .. and therefore error message.

I have found no trace about this outside of https://github.com/TryGhost/Ghost/issues/2684

I am on a recent installation, it's really strange.

### Technical details:

* Ghost Version: 2.6.2
* Node Version: v8.9.4
* Browser/OS: Safari Version 12.0.1 || Chrome Version 70.0.3538.110 / macOS 10.14.1 
* Database: mysql MariaDB10.1.26-MariaDB-0+deb9u1 Debian 9.1

**Comment by PierreBrisorgueil** [comment]
> Is this on a local installation? If not - is it possible the time on your server is incorrect?

Hello, thanks for the quick response, Unfortunately I do not think so. 
<img width="208" alt="screenshot 2018-11-29 at 09 29 43" src="https://user-images.githubusercontent.com/6069599/49208895-57a91c00-f3b9-11e8-8928-63f678292c71.png">

It's ok, from France. 

If this is not reproduced on your side, I can try a new test installation in parallel. 

It's not an installation by the cli, i downloaded the ghost zip, installed the dependencies via yarn, set up the prod conf and knex file, and i update directly via yarn. It does not change anything normally.

**Comment by allouis** [comment]
Hmmm, I can't think what that would be! 

I can take a look at trying to replicate this next Monday. In the meantime, maybe see if you can get some exact steps for replication? (e.g. config, knex file, any custom stuff)

Out of interest, is there a reason you're not using the cli to install ghost?

Thanks :)

**Comment by PierreBrisorgueil** [comment]
Okok, thx. 

Yes, nothing special on Knex, default cone, this is the ghost conf : 

```
{
    "url": "https://xxx",
    "server": {
        "host": "127.0.0.1",
        "port": 2368
    },
    "database": {
        "client": "mysql",
        "connection": {
            "host"     : "127.0.0.1",
            "user"     : "xxx",
            "password" : "xxx",
            "database" : "xxx-blog"
        }
    },
    "auth": {
        "type": "password"
    },
    "paths": {
        "contentPath": "content"
    },
    "logging": {
        "level": "info",
        "rotation": {
            "enabled": true
        },
        "transports": ["file", "stdout"]
    }
}
```

Everything is behind a reverse proxy apache with let's encrypt, but it seems to be ok, no error and access.log ok. 

Nothing else, everything is like a default install. A single line is changed in the casper theme to call a different background every hour of the day to make it dynamic, but nothing can impact.

Absolutely no valid reason. I use ghost since the first versions, and as a big feigner I just avoided installing the global package and installed it as a npm module also because I really used it as a module in test in a project just before. I have a second server similar, I will test the installation via the cli quickly to see if I have the same problem.

**Comment by PierreBrisorgueil** [comment]
Ok, I realised two fresh install behind Nginx on another server, with and without cli, I don't have this issue. 

can't be a problem with apache, i try on the server with the problem now.

**Comment by PierreBrisorgueil** [comment]
@allouis 

Ok that's really strange, try to help with some feedback :  (ok = no bug)

- fresh install without cli on new server : ok 
- fresh install with cli on new server : ok 
- fresh install with cli on the same server : ok 
- fresh install with cli on the same server, with old db, same theme, behind apache and let's encrypt, : ok 

the only difference beetween the two instances (old with bug and new without) is this : 

```
  "process": "systemd",
  "paths": {
    "contentPath": "/var/www/weaos_blog/ghost/content"
  },
  "bootstrap-socket": {
    "port": 8000,
    "host": "localhost"
  }
```

of course that's change nothing. 

New install work fine with both configs. 

I have no other ideas apart from a relicate of the maj on maj ... really sorry can't help more, at least the issue is logged in case others have this problem.

I hope this has solved a second problem on the programmed post O.O. The queries in the access.log file were good but sometimes the post was not published. I will test that quickly.

I closed the issue.
