### ISSUE TITLE
Permissions for author and contributor need a review and unit test coverage

### ISSUE THREAD

**Issue by gargol** [TryGhost/Ghost#10234]
This issue is a follow up for https://github.com/TryGhost/Ghost/pull/10214#issuecomment-443719237 

We need to review and cover with unit tests the differences between Author and Contributor roles permissions in authors models permissions: https://github.com/TryGhost/Ghost/blob/master/core/server/models/relations/authors.js#L321-L333. Specifically there should be a clarification on whether there's a difference between user being a co-author or a primary author.

---
Additional tasks:
- [ ] update docs accordingly https://docs.ghost.org/faq/managing-your-team/#user-roles

**Comment by kirrg001** [comment]
FYI: We have many, many [unit tests in the `post_spec`](https://github.com/TryGhost/Ghost/blob/2.6.2/core/test/unit/models/post_spec.js#L1524).
