### ISSUE TITLE
White Navbar Block

### ISSUE THREAD

**Issue by owner** [TryGhost/Ghost#10231]
After install, I open any page on Ghost and found a CSS bug. Check an attached photo.

![welcome to ghost - mozilla firefox 2018-12-02 01 26 46](https://user-images.githubusercontent.com/24358937/49333548-ceb8fd00-f5d1-11e8-9209-bffe88d681dd.png)

* Ghost Version: Latest (2.6.2)
* Node Version: Ubuntu 16.04 LTS (Final / Latest Version)
* Browser/OS: Mozilla Firefox (Latest)
* Database: MySQL (Latest)

**Comment by allouis** [comment]
I think this issue would be more approprate in the https://github.com/TryGhost/Casper repo! Could you also make sure you can replicate this in an incognito session, to ensure it is nothing to do with extensions?

FWIW - I run ghost daily in firefox for linux and have never seen this.
