### ISSUE TITLE
Ghost 0.11.14 install failure

### ISSUE THREAD

**Issue by hwdsl2** [TryGhost/Ghost#10244]
### Issue Summary

Ghost 0.11.14 depends on har-validator 5.1.2, which has been unpublished.

### To Reproduce

Install Ghost 0.11.14. You'll likely encounter failures like:
```
npm ERR! fetch failed https://registry.npmjs.org/har-validator/-/har-validator-5.1.2.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 404
npm ERR! fetch failed https://registry.npmjs.org/har-validator/-/har-validator-5.1.2.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 404
npm ERR! fetch failed https://registry.npmjs.org/har-validator/-/har-validator-5.1.2.tgz
npm ERR! Linux 3.13.0-115-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "--production"
npm ERR! node v6.11.0
npm ERR! npm  v3.10.10
```

This is because npm-shrinkwrap.json specifies har-validator 5.1.2, which has been unpublished. See:
https://github.com/ahmadnassri/node-har-validator/issues/112

To make the problem worse, the NPM registry returns inconsistent results for the unpublished 5.1.2 version. This command sometimes returns 200, sometimes returns 404 Not Found:
```
curl -I https://registry.npmjs.org/har-validator/-/har-validator-5.1.2.tgz
```

Suggested fix: Update to har-validator 5.1.3 in npm-shrinkwrap.json.

### Technical details:

* Ghost Version: 0.11.14
* Node Version: 6.11.0
* Browser/OS: Linux
* Database: SQLite

**Comment by allouis** [comment]
> This is because npm-shrinkwrap.json specifies har-validator 5.1.2, which has been unpublished. 

![why](https://user-images.githubusercontent.com/3218915/49566590-bb08f000-f95d-11e8-92ca-37dec5a557bd.gif)

Thanks for the report - i can sort out a fix on monday, but if you can put together a PR it would be appreciated :relaxed: 

The 0.11.14 release is on the [lts branch](https://github.com/TryGhost/Ghost/tree/lts)

**Comment by ErisDS** [comment]
Support for the LTS version of Ghost ends on Dec 31st - so in 25 days - this will probably be the last fix.

**Comment by hwdsl2** [comment]
@allouis @ErisDS I tried to search for `har-validator` in the `lts` branch but could not find any reference. So I'm unable to make a pull request for this. Maybe we simply need a repackage of Ghost 0.11.14 (which will generate a new `npm-shrinkwrap.json`?

**Comment by allouis** [comment]
Repackage of shrinkwrap could work! Give it a go :)

If you run `npm ls` you should see where `har-validator` is in the dep tree, spoiler: 

```
├─┬ sqlite3@4.0.3
│ ├── nan@2.10.0
│ ├─┬ node-pre-gyp@0.10.3
│ │ ├── detect-libc@1.0.3 deduped
│ │ ├── mkdirp@0.5.1 deduped
│ │ ├─┬ needle@2.2.4
│ │ │ ├── debug@2.6.9 deduped
│ │ │ ├── iconv-lite@0.4.24 deduped
│ │ │ └── sax@1.2.4
│ │ ├─┬ nopt@4.0.1
│ │ │ ├── abbrev@1.1.1 deduped
│ │ │ └── osenv@0.1.5 deduped
│ │ ├─┬ npm-packlist@1.1.12
│ │ │ ├─┬ ignore-walk@3.0.1
│ │ │ │ └── minimatch@3.0.4 deduped
│ │ │ └── npm-bundled@1.0.5
│ │ ├── npmlog@4.1.2 deduped
│ │ ├── rc@1.2.8 deduped
│ │ ├── rimraf@2.6.2 deduped
│ │ ├── semver@5.6.0 deduped
│ │ └── tar@4.4.6 deduped
│ └─┬ request@2.88.0
│   ├── aws-sign2@0.7.0
│   ├── aws4@1.8.0
│   ├── caseless@0.12.0
│   ├─┬ combined-stream@1.0.7
│   │ └── delayed-stream@1.0.0
│   ├── extend@3.0.2 deduped
│   ├── forever-agent@0.6.1
│   ├── form-data@2.3.3 deduped
│   ├─┬ har-validator@5.1.0 <-------------------------------- here
│   │ ├── ajv@5.5.2 deduped
│   │ └── har-schema@2.0.0
```

So you _might_ find that the sqlite dep has had a patch version since that that could fix the issue!

Thanks for taking a look :nerd_face:

**Comment by hwdsl2** [comment]
@allouis @ErisDS I've run `npm ls` on my Ghost 0.11.14 install. Here's the location of `har-validator` in the output:
```
... ...
├─┬ gscan@0.2.6
│ ├── bluebird@3.4.6
│ ├── chalk@1.1.1
│ ├─┬ commander@2.9.0
│ │ └── graceful-readlink@1.0.1
│ ├─┬ express-hbs@1.0.3
│ │ └── js-beautify@1.6.4
│ ├─┬ fs-extra@0.26.2
│ │ └── klaw@1.3.1
│ ├─┬ ghost-ignition@2.9.6
│ │ ├─┬ bunyan@1.8.12
│ │ │ ├─┬ dtrace-provider@0.8.7
│ │ │ │ └── nan@2.11.1
│ │ │ ├─┬ mv@2.1.1
│ │ │ │ ├── ncp@2.0.0
│ │ │ │ └─┬ rimraf@2.4.5
│ │ │ │   └── glob@6.0.4
│ │ │ └── safe-json-stringify@1.2.0
│ │ ├─┬ bunyan-loggly@1.3.5
│ │ │ └─┬ node-loggly-bulk@2.2.4
│ │ │   └─┬ request@2.88.0
│ │ │     ├── aws-sign2@0.7.0
│ │ │     ├── aws4@1.8.0
│ │ │     ├── caseless@0.12.0
│ │ │     ├── forever-agent@0.6.1
│ │ │     ├─┬ har-validator@5.1.2 <-------------------------------- here
│ │ │     │ ├─┬ ajv@6.5.5
│ │ │     │ │ ├── fast-deep-equal@2.0.1
│ │ │     │ │ ├── fast-json-stable-stringify@2.0.0
│ │ │     │ │ ├── json-schema-traverse@0.4.1
│ │ │     │ │ └─┬ uri-js@4.2.2
│ │ │     │ │   └── punycode@2.1.1
│ │ │     │ └── har-schema@2.0.0
... ...
```
I think that instead to fix it, your team might need to release a new version of `gscan` or `ghost-ignition`, which bumps up the dependency version of `har-validator`.

Alternatively, as I said above, maybe a simple repackaging of Ghost 0.11.14 will suffice, because there is no direct reference to `har-validator@5.1.2` in `package.json`, and when you repackage, a new `npm-shrinkwrap.json` will be generated which will use the correct version `har-validator@5.1.3` instead. I'm not sure how to repackage 0.11.14 but it seems to me that it cannot be done via a pull request in the Git repo.

**Comment by hwdsl2** [comment]
@JohnONolan Thanks for the recommendation. This issue may also affect existing users who upgrade to 0.11.14 because `har-validator@5.1.2` is in `npm-shrinkwrap.json` which now 404s.

However I am good with whichever way the Ghost blog team decides. Thank you for the awesome product.

**Comment by ErisDS** [comment]
Agree w/ John. I've just gone through and closed all remaining LTS bugs. 

There is no need to upgrade to 0.11.14 before doing a major upgrade. At the moment the best course of action is a fresh 1.0 install. We will be introducing a mechanism for upgrading straight from LTS -> 2.0 soon as per #10276.

Closing this as a wontfix.
