### ISSUE TITLE
{{slug}} attribute in navigation.hbs skips most if not all non-ascii characters

### ISSUE THREAD

**Issue by TJYSunset** [TryGhost/Ghost#10258]
### Issue Summary

`{{slug}}` attribute in navigation.hbs ignores non-ascii characters such as `À` (Latin-1 Supplement), `А` (Cyrillic) and `文` (CJK Unified Idegraphs).

### To Reproduce

1. Add an entry with the label "ÀА文" in Settings > Design > Navigation.
2. Set theme to Casper so the `{{slug}}` attribute will be added to the html tag's `class`.
3. Inspect source in your browser - the html tag should look like
```html
<li class="nav-" role="menuitem"><a href="url">ÀА文</a></li>
```

> Why do you consider this to be a bug?

This emits an empty string for every label consisting only non-ASCII characters, making the `{{slug}}` attribute virtually useless or unexpectedly-behaving on non-English sites.

> What did you expect to happen instead?

Consider romanizing slugs like the automatic post url generation did.

**And,** consider making slugs customizable via Settings > Design > Navigation.

**And,** consider providing a `{{slug-base64}}` or something similar that yields base64 encoded utf-8 data, to handle non-romanizable characters (emojis?) and characters with multiple romanizations [(`乐` in Mandarin Chinese can be romanized as either `le` or `yue`)](https://en.wiktionary.org/wiki/樂) better.

### Technical details:

* Ghost Version: 2.7.1

**Comment by kirrg001** [comment]
Hey 👋 Thanks for your report.

Can confirm the bug report. The [slugify function](https://github.com/TryGhost/Ghost/blob/2.7.1/core/server/helpers/navigation.js#L43) probably can just use our [safe string utility.
](https://github.com/TryGhost/Ghost/blob/2.7.1/core/server/lib/security/string.js)
PR is welcome 👍
