### ISSUE TITLE
Ghost's frontent fails silently when uploading an image goes wrong with NGINX proxy

### ISSUE THREAD

**Issue by ThomasGravekamp** [TryGhost/Ghost#10255]
### Issue Summary

From a users point of view: When I try to upload an image, Ghost lets me select an image and then exactly nothing happens.

What actually happens: Ghost is served via an NGINX instance configured as reverse proxy on my server. When I upload an image that is considered too large (file size) by NGINX, it returns an HTTP error page. The frontend of Ghost expects a JSON file to be returned, but a HTML file is returned. Parsing the HTML file as if it were a JSON file fails, obviously.

I know I can configure NGINX to accept files that are larger than the image I tried to upload, but wouldn't it be nice if Ghost somehow told the user that the image upload failed. I had to dig through the network calls to look for something that went wrong, as this error does not show up in the browsers console.

### To Reproduce

1. Have a Ghost instance running
2. Have a NGINX instance running, configured as reverse proxy for Ghost
3. Create a new post
4. Add a new markdown block
5. Insert an image larger than NGINX's `client_max_body_size` default size (1MiB)
6. Observe... nothing actually... NGINX responds with a HTTP status 413 Request Entity Too Large

It would be nice if Ghost at least lets the user know something went wrong while sending the image to the server.

### Technical details:

* Ghost Version: 2.1.1
* Node Version: 8.12.0
* Browser/OS: Firefox 63.0.3 @ Windows 10
* Database: sqlite3

**Comment by kevinansfield** [comment]
Where in the admin area were you uploading the image? Eg, was it a feature image? If so was it a tag or post feature image? Somewhere in the settings? In the editor? We need full reproduction steps because each area is handled differently.

Also, you say nginx was returning a html page, what the response code?

**Comment by ThomasGravekamp** [comment]
> Where in the admin area were you uploading the image? Eg, was it a feature image? If so was it a tag or post feature image? Somewhere in the settings? In the editor? We need full reproduction steps because each area is handled differently.

It happend while inserting an image in a post in a markdown field/block. So you would create a markdown block, then insert an image that would be too large and then, well, nothing happens. I will add this to the issue reproduction steps.

> Also, you say nginx was returning a html page, what the response code?

The HTTP code was 412:

```
<html>
<head><title>413 Request Entity Too Large</title></head>
<body bgcolor=\"white\">
<center><h1>413 Request Entity Too Large</h1></center>
<hr><center>nginx/1.13.7</center>
</body>
</html>
```

**Comment by kirrg001** [comment]
Hey @ThomasGravekamp   👋 Friendly reminder: help or support is not available on Github. Our default issue templates pointed you to our [forum](https://forum.ghost.org) for this type of question 😄 We use GitHub solely for bug-tracking and on-going feature development so we try to keep it noise free.

Many questions can be answered by reviewing our docs for [self-hosters](https://docs.ghost.org), our [theme API](https://themes.ghost.org), or our [public API](https://api.ghost.org). If you can't find an answer then our [forum](https://forum.ghost.org) is a great place to get community support, plus it helps create a central location for searching problems/solutions.

FYI: Many projects have their own support guidelines and GitHub will highlight them for you, or the project owners will use issue templates to point you in the right direction. Reading the guidelines or issue templates before opening issues can save you and other project maintainers some valuable time.

**Comment by ThomasGravekamp** [comment]
Well, I wasn't here to get any help or support, which you may have noticed if you read the issue. I stumbled upon this issue while using Ghost and considered this to be at least something that could use some better UX. There is nothing in Ghost that tells you that something goes wrong while uploading the image this way (!).

I honestly don't care what you do with this issue, it's just a heads up to the devs and anyone involved to let you guys know this type of "errors" exist.
