### ISSUE TITLE
Ability to import from any version

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#10276]
In the build up to the release of 2.0 we decided on a policy of supporting the current major Ghost version, and one previous version, across the various areas of our product. That included imports, gscan, and a few other things.

Since the release of 2.0, the pain that has created for users still on LTS has been apparent, as they have had to upgrade to 1.0 first. Moving forward, we will continue to make regular major versions of Ghost (roughly 1x per year), and we always want to make it as easy as possible to upgrade.

The immediate concern is re-enabling LTS imports in Ghost 2.0. Longer term we need a plan to make it always possible to import into the current Ghost version from any previous version.

I suggest that we implement this via a dependency that is able to transform any older Ghost import file to being valid for the current version of Ghost. That way we can keep complex handling out of models and Ghost core.

The importer should upload the file, run it through a transform if it is out of date, and then run the transformed version through the import process.

The dependency can live in the new [migrate](https://github.com/TryGhost/migrate) mono repo, which should hold any and all tooling for imports and exports that it is possible to split out.

**Comment by kirrg001** [comment]
Not stale.
