### ISSUE TITLE
I can't login my ghost website

### ISSUE THREAD

**Issue by lzcdev** [TryGhost/Ghost#10278]
![6521544684463_ pic_hd](https://user-images.githubusercontent.com/16014249/49925123-fb82e380-fef2-11e8-9bb6-ebbd93515d8a.jpg)

what's wrong with this?what should I do?

**Comment by kevinansfield** [comment]
Hey @lzxdev 👋 Friendly reminder: help or support is not available on Github. Our default issue templates pointed you to our [forum](https://forum.ghost.org) for this type of question 😄 We use GitHub solely for bug-tracking and on-going feature development so we try to keep it noise free.

Many questions can be answered by reviewing our docs for [self-hosters](https://docs.ghost.org), our [theme API](https://themes.ghost.org), or our [public API](https://api.ghost.org). If you can't find an answer then our [forum](https://forum.ghost.org) is a great place to get community support, plus it helps create a central location for searching problems/solutions.

FYI: Many projects have their own support guidelines and GitHub will highlight them for you, or the project owners will use issue templates to point you in the right direction. Reading the guidelines or issue templates before opening issues can save you and other project maintainers some valuable time.
