### ISSUE TITLE
Embedded JS is parsed as a html content

### ISSUE THREAD

**Issue by ronny35** [TryGhost/Ghost#10298]
### Issue Summary

During creation one story, Post-embedded JS scripts in html content are being recognized by the editor, but after publishing, javascript is rendering like a simple text

### To Reproduce

```
<div> Test </div>
<div id="mapid" style="width: 600px; height: 400px;"></div>
<link rel="stylesheet" href="https://unpkg.com/leaflet@1.3.4/dist/leaflet.css" integrity="sha512-puBpdR0798OZvTTbP4A8Ix/l+A4dHDD0DGqYW6RQ+9jxkRFclaxxQb/SJAWZfWAkuyeQUytO7+7N4QKrDh+drA==" crossorigin=""/>
<script src="https://unpkg.com/leaflet@1.3.4/dist/leaflet.js" integrity="sha512-nMMmRyTVoLYqjP9hrbed9S+FzjZHW5gY1TWCHA5ckwXZBadntCNs8kEqAWdrb9O7rxbCaA4lKTIWjDXZxflOcA==" crossorigin="">
</script>
<script>
    
    var mymap = L.map('mapid').setView([51.505, -0.09], 13);
	L.tileLayer('https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token=pk.eyJ1IjoibWFwYm94IiwiYSI6ImNpejY4NXVycTA2emYycXBndHRqcmZ3N3gifQ.rJcFIG214AriISLbB6B5aw', {
		maxZoom: 18,
		attribution: 'Map data &copy; <a href="https://www.openstreetmap.org/">OpenStreetMap</a> contributors, ' +
			'<a href="https://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, ' +
			'Imagery © <a href="https://www.mapbox.com/">Mapbox</a>',
		id: 'mapbox.streets'
	}).addTo(mymap);

	L.marker([51.5, -0.09]).addTo(mymap)
		.bindPopup("<b>Hello world!</b><br />I am a popup.").openPopup();

	L.circle([51.508, -0.11], 500, {
		color: 'red',
		fillColor: '#f03',
		fillOpacity: 0.5
	}).addTo(mymap).bindPopup("I am a circle.");

	L.polygon([
		[51.509, -0.08],
		[51.503, -0.06],
		[51.51, -0.047]
	]).addTo(mymap).bindPopup("I am a polygon.");


	var popup = L.popup();

	function onMapClick(e) {
		popup
			.setLatLng(e.latlng)
			.setContent("You clicked the map at " + e.latlng.toString())
			.openOn(mymap);
	}

	mymap.on('click', onMapClick);

</script>
```
And the result :

```
<section class="post-card-excerpt">
                <p>var mymap = L.map('mapid').setView([51.505, -0.09], 13); 	L.tileLayer('https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token=pk.eyJ1IjoibWFwYm94IiwiYSI6ImNpejY4NXVycTA2emYycXBndHRqcmZ3N3gifQ.rJcFIG214AriISLbB6B5aw', { 		maxZoom:</p>
</section>
```

### Technical details:

* Ghost Version: Docker ghost:2.7-alpine

**Comment by kevinansfield** [comment]
@ronny35 the excerpt helper is unable to parse the content properly. I would suggest using the [custom excerpt](https://docs.ghost.org/faq/publishing-options/#add-a-custom-excerpt) feature to provide a human readable excerpt.

**Comment by kevinansfield** [comment]
Hmm, I would say this is pointing to a bug in either our plaintext generation or the excerpt helper - neither should be outputting contents of `<script>` tags.

**Comment by ErisDS** [comment]
Do we have enough information to reproduce this issue? If not, what do we need?

**Comment by ErisDS** [comment]
OK - in that case I'm gonna close this as either not-a-bug or wont-fix depending on how you look at it.

The conversion to plaintext does the right thing, it's just a bit weird in this context. There's no simple configuration that I can see in [html-to-text](https://www.npmjs.com/package/html-to-text) that would allow us to tell it not to include script tags. Therefore it's a non trivial fix.

Meanwhile, there are also two available workarounds: 1. don't include a script as the first thing, or 2. use a custom excerpt.

It's also effectively the same issue as https://github.com/TryGhost/Ghost/issues/3846 which was never cared about enough to warrant a fix on account of there being workarounds.
