### ISSUE TITLE
No support for persian language in editor and reading time helper.

### ISSUE THREAD

**Issue by ahmadpn** [TryGhost/Ghost#10303]
### Issue Summary

The editor could not count words in Persian language. 

### To Reproduce

1. When typing in editor, the word count shows 0 and editor can not calculate number of words.
2. So the reading time helper because of above issue always shows 1 min read.

### Technical details:

* Ghost Version: 2.9
* Node Version: 10
* Browser/OS: 
* Database:

**Comment by gargol** [comment]
@kevinansfield was able to reproduced this bug when using 'فارسی' word (taken from [wikipedia](https://en.wikipedia.org/wiki/Persian_language))
