### ISSUE TITLE
Incorrect redirect on subdirectory collides with same post slug

### ISSUE THREAD

**Issue by kirrg001** [TryGhost/Ghost#10309]
Reported in the forum: https://forum.ghost.org/t/problem-with-path-redirects/4652

## Reproduce

1. Set up your blog on a subdirectory /blog
2. Create a post with a slug called "blog-something"
3. Try to navigate that post
4. You are getting redirected from /blog/blog-something/ to /blog-something

## Why?

I guess there is a logic bug in the entry controller, [see line.](https://github.com/TryGhost/Ghost/blob/2.9.1/core/server/services/routing/controllers/entry.js#L73)

Ghost: latest

**Comment by kirrg001** [comment]
This issue might suffer from the same underlying problem described in https://github.com/TryGhost/Ghost/issues/9687. Needs investigation. Any help is very appreciated 🙂

**Comment by ErisDS** [comment]
All issues tagged with `routing` have been tagged with `later` and closed until we prioritise working on the Routing feature again.
