### ISSUE TITLE
301 Redirect

### ISSUE THREAD

**Issue by arifzeeshan** [TryGhost/Ghost#10300]
I have hosted Ghost on Heroku platform and I want to redirect all traffic from appname.herokuapp.com to my custom domain. I read about the docs here [https://docs.ghost.org/concepts/redirects/](https://docs.ghost.org/concepts/redirects/). 

This is my redirect.json file -

```
{
  "type":"301",
  "from": "https://arifzeeshan.herokuapp.com" ,
  "to":  "https://arifzeeshan.com",
  "permanent": true
}
```
It fails to redirect.

**Comment by ErisDS** [comment]
Hey @arifzeeshan   👋 We ask that you please do not use GitHub for help or support, the default issue template pointed you to our [forum](https://forum.ghost.org) for this type of question 😄 We use GitHub solely for bug-tracking and on-going feature development so we try to keep it noise free.

Many questions can be answered by reviewing our docs for [self-hosters](https://docs.ghost.org), our [theme API](https://themes.ghost.org), or our [public API](https://api.ghost.org). If you can't find an answer then our [forum](https://forum.ghost.org) is a great place to get community support, plus it helps create a central location for searching problems/solutions.

FYI: Many projects have their own support guidelines and GitHub will highlight them for you, or the project owners will use issue templates to point you in the right direction, please read them before opening issues
