### ISSUE TITLE
SVG 'seen as' PNG

### ISSUE THREAD

**Issue by stefanovazzocell** [TryGhost/Ghost#10317]
**Update**

As per @gargol suggestion, this is probably going to be resolved in #10315 

----

### Issue Summary

After updating to 2.9.1 I found that some of my SVG files were [unable](https://stefanovazzoler.com/content/images/size/w1000/2017/09/studyspaces.svg) to be properly displayed. It looks like Ghost is trying to convert them or read them as "PNG" but failes to do so... In general ends up being unable to deal with (some) svg images on my site. I purposely left a [post](https://stefanovazzoler.com/tales_from_ubc_4/) up showing the issue. The images are also available on a Google Drive [shared folder](https://drive.google.com/open?id=1FthDFfTzWr3gcDRMHmEaZkGsykesOlfB).
Those svg files are highly optimized, I'm wondering if that is messing up with Ghost's system and makes it unable to detect the proper format... but I checked on some [online validation sites](https://validator.w3.org/nu/) and they appeared to validate my svg.
If you look at the file that the server returns, it starts with "PNG", life it ghost tries to convert them, although I am unable to open the file as such (by changing the extension).

### To Reproduce

1. Update to 2.9.1
2. Check svg files on the site

### Technical details:

* Ghost Version: (from 2.8.0 to) 2.9.1
* Node Version: v6.16
* Browser/OS: Chrome 71 on Windows 10
* Server OS: Ubuntu 16.04

**Comment by gargol** [comment]
@stefanovazzocell yes, it's the same very issue. Closing this one to keep things tidy
