### ISSUE TITLE
Dynamic Routing: All hard-coded public routes (e.g. page) are configurable inc homepage

### ISSUE THREAD

**Issue by kirrg001** [TryGhost/Ghost#10312]
**Extracted from https://github.com/TryGhost/Ghost/issues/9601. Dynamic Routing is currently in Beta and was shipped in Ghost 1.24.0.**

This is one missing sub feature which we weren't able to put into Ghost yet.
Leaving this here as a placeholder, so we won't forget about it.

**Comment by ErisDS** [comment]
All issues tagged with `routing` have been tagged with `later` and closed until we prioritise working on the Routing feature again.
