### ISSUE TITLE
Dynamic Routing: disable sitemaps, disable pagination

### ISSUE THREAD

**Issue by kirrg001** [TryGhost/Ghost#10313]
**Extracted from https://github.com/TryGhost/Ghost/issues/9601. Dynamic Routing is currently in Beta and was shipped in Ghost 1.24.0.**

This is one missing sub feature which we weren't able to put into Ghost yet.
Leaving this here as a placeholder, so we won't forget about it.

**This issue needs more info.**

**Comment by ErisDS** [comment]
All issues tagged with `routing` have been tagged with `later` and closed until we prioritise working on the Routing feature again.
