### ISSUE TITLE
Non-printable characters break RSS feed

### ISSUE THREAD

**Issue by gargol** [TryGhost/Ghost#10316]
When using non-printable characters in posts title or content RSS feed breaks. For following post content (used `0x07` here):
```
invisible  hi
```
rss returns:
```
This page contains the following errors:
error on line 1 at column 758: Input is not proper UTF-8, indicate encoding !
Bytes: 0x07 0x20 0x68 0x69
Below is a rendering of the page up to the first error.
```

refs https://github.com/TryGhost/Ghost/issues/9826

**Comment by ErisDS** [comment]
Duplicate of https://github.com/TryGhost/Ghost/issues/8442 ?

**Comment by gargol** [comment]
Good catch @ErisDS . Looks like we keep running into the same issue in multiple places. https://github.com/dylang/node-rss/issues/49 needs a little bit of :dash: and :heart:
