### ISSUE TITLE
Suggestion /[Feature request] Add support for Webmention into Ghost

### ISSUE THREAD

**Issue by marek-lach** [TryGhost/Ghost#10320]
This is an interesting idea you should consider implementing: https://www.w3.org/TR/webmention.

More info about implementing it here: https://indieweb.org/webmention
https://alistapart.com/article/webmentions-enabling-better-communication-on-the-internet
https://allinthehead.com/retro/378/implementing-webmentions

Thank you,

**Comment by gargol** [comment]
Hey @marek-lach  👋 We ask that you please do not use GitHub for feature requests, the default issue templates pointed you to our [forum](https://forum.ghost.org) for this type of question - the [Ideas](https://forum.ghost.org/c/Ideas/l/votes) topic will let you propose features and let others vote on them 😄. We use GitHub solely for bug-tracking and on-going feature development so we try to keep it noise free.

FYI: Many projects have their own support guidelines and GitHub will highlight them for you, or the project owners will use issue templates to point you in the right direction, please read them before opening issues.

**Comment by shreyas-makes** [comment]
I've figured out a solution to implement webmentions to your Ghost blog as a replacement to the native Ghost comments: https://shreyasprakash.com/publish-originally-syndicate-elsewhere/
