### ISSUE TITLE
Posts endpoint: Markdown property bug (creation of post)

### ISSUE THREAD

**Issue by donutloop** [TryGhost/Ghost#10324]
Hi, 

I'm trying to create a post via the posts endpoint but it doesn't recognize the "markdown" property in my JSON object.

I have followed the instructions in the doc for creating a post object.

Ref: https://api.ghost.org/docs/user-authentication#retrieve-a-bearer-token-via-curl

Ghost version: 2.9.1

### Example call

```bash
curl -i \                              
    -H "Accept: application/json" \
    -H "Content-Type: application/json" \
    -H "Authorization: Bearer oHt7NwU3kbPMegfy2ULDPrWzRWXNCqtJa1BRaaDJIaeopHoarkWEiej7fqcq9wJmCRB0bmTaUs8F1qRJnq3NqRYCZG6JnIFf5OjvTcGJeRWKaIulcxFLNGosryA9MtLohoBtbRxqWfP5tcrce38U9t1dFi0PqsuOkzO3ZNFOwubhlt1zsbCGGFUeF6noLmP" \
    -X POST -d '{"posts": [{"title": "My API post", "markdown": "##Some text", "status": "published", "feature_image": "https://www.gettyimages.ie/gi-resources/images/Homepage/Hero/UK/CMS_Creative_164657191_Kingfisher.jpg" }]}' \     
    http://localhost:2368/ghost/api/v0.1/posts/
```

**Comment by ErisDS** [comment]
Hey @donutloop   👋 We ask that you please do not use GitHub for help or support, the default issue template pointed you to our [forum](https://forum.ghost.org) for this type of question 😄 We use GitHub solely for bug-tracking and on-going feature development so we try to keep it noise free.

Many questions can be answered by reviewing our docs for [self-hosters](https://docs.ghost.org), our [theme API](https://themes.ghost.org), or our [public API](https://api.ghost.org). If you can't find an answer then our [forum](https://forum.ghost.org) is a great place to get community support, plus it helps create a central location for searching problems/solutions.

FYI: Many projects have their own support guidelines and GitHub will highlight them for you, or the project owners will use issue templates to point you in the right direction, please read them before opening issues

**Comment by donutloop** [comment]
I think! it's bug please read my bug ticket

**Comment by bsodmike** [comment]
@donutloop agonised over this today, and I even noticed that specifying a post as 'published' via the API call, has no effect.  It seems like whatever endpoint that's internally used to publish posts (or in this case accept the Markdown content) is just not being processed.

Making the API call

```python
import requests
import json

url = 'http://localhost:2368/ghost/api/v0.1/posts'
payload = {
  "posts": [{ "markdown": "<p>Some content goes here</p>", "title": "Testing New Post", "status": "published"}]
}

headers = {
  "Authorization": "Bearer QiadcmwqCdynYf8SVKkQ3sQG6aWI6o9m1XyYmYaOOK9sI5kIr6e2ofo6bWMibDdCpXG26Iw7aCtKDHMI0T3Zqr7Wllku6BuI7xDzw6ZXpKu5G1M09g4V3at8KDEBvfIg6GiwAqplQcJ8ABk4YC8zyd6KWG5XyAWRzRF08OEWALrI1jyp3GfHyvbGtCbfFdQ"
}
r = requests.post(url, json=payload, headers=headers)
print(r.content)
print(r.status_code)
```

Response showing that the `html` content hasn't been updated.

```
{
  "posts": [
    {
      "id": "5c3e098c2747160001dbb8e0",
      "uuid": "659ec6bd-399d-4ddc-9e2a-26130a4d2360",
      "title": "Testing New Post",
      "slug": "testing-new-post",
      "html": "<p></p>",
      "comment_id": "5c3e098c2747160001dbb8e0",
      "feature_image": null,
      "featured": false,
      "page": false,
      "status": "published",
      "locale": null,
      "visibility": "public",
      "meta_title": null,
      "meta_description": null,
      "created_at": "2019-01-15T16:25:48.000Z",
      "created_by": "1",
      "updated_at": "2019-01-15T16:25:48.000Z",
      "updated_by": "1",
      "published_at": "2019-01-15T16:25:48.000Z",
      "published_by": "1",
      "custom_excerpt": null,
      "codeinjection_head": null,
      "codeinjection_foot": null,
      "og_image": null,
      "og_title": null,
      "og_description": null,
      "twitter_image": null,
      "twitter_title": null,
      "twitter_description": null,
      "custom_template": null,
      "author": "1",
      "primary_author": null,
      "primary_tag": null,
      "url": "/404/"
    }
  ]
}
```

**Comment by kirrg001** [comment]
Please use our [forum](https://forum.ghost.org) for further questions.

---

We have recently shipped the new [Content API v2 (read-only)](https://docs.ghost.org/api/content/) and we are working on the [Admin API v2](https://github.com/TryGhost/Ghost/issues/9865) soon.
