### ISSUE TITLE
Invite People Email Fails:  `Validation (FieldIsInvalid) failed for ["role_id"]`

### ISSUE THREAD

**Issue by reustonium** [TryGhost/Ghost#10330]
### Issue Summary

Ubuntu 18.04.1 LTS
Ghost 2.9.1
Ghost-CLI 1.9.8

### To Reproduce

1. Login to Admin Console
2. Select 'Team'
3. Click 'Invite People'
3a. For already invited people click 'RESEND'
4. Observe error `Validation (FieldIsInvalid) failed for ["role_id"]`
5. Observe no email received.

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

### Technical details:

* Ghost Version: 2.9.1
* Node Version: 8.10.0
* Browser/OS: Chrome/Ubuntu 18.04.1 LTS

**Comment by kirrg001** [comment]
Thanks for your report.

I have re-opened https://github.com/TryGhost/Ghost/issues/10071.
