### ISSUE TITLE
Values that have been removed return as "" instead of null

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#10345]
The API should always represent empty values as null. This is working correctly, except in the case where a value is added and then removed/set to empty string.

E.g. `meta_title` on a tag. 

### To Reproduce

1. Add a meta title to a tag in the UI
2. Remove that meta title from the tag
3. Check the V2 Content API response

The meta_title is now `""` instead of `null`.
This should always be consistently `null` so that our tooling can depend on it properly.

### Technical details:

* Ghost Version: master
* Database: tested on sqlite3

**Comment by rishabhgrg** [comment]
API output fixed in https://github.com/TryGhost/Ghost/pull/10378. Closed in favour of https://github.com/TryGhost/Ghost/issues/10388.
