### ISSUE TITLE
Raw knex query has to respect withRelatedFields parameter

### ISSUE THREAD

**Issue by gargol** [TryGhost/Ghost#10348]
When raw query is performed in base model, [withRelatedFields](https://github.com/TryGhost/Ghost/blob/7e944506e99bf998ad6f6d343e974b81b85c43c1/core/server/services/url/Resources.js#L117) is not respected. 

Initially discussed [here](https://github.com/TryGhost/Ghost/pull/10336/files#r245641316)

**Comment by kirrg001** [comment]
@gargol This issue can be closed with #10361 or?

**Comment by gargol** [comment]
This is a different issue. The fields that are in model configurations for resources service, specifically `withRelatedFields` are not respected when fetching the resource.

**Comment by kevinansfield** [comment]
Although this is a known defect it's not something that is causing any bugs or other issues at this time. 

Closing for now, we can re-open if we run into a problem where this is the culprit.
