### ISSUE TITLE
Not able to require the `ghost-storage-base` in custom storage module.

### ISSUE THREAD

**Issue by robincsamuel** [TryGhost/Ghost#10349]
I authored the package [ghost-google-drive](https://github.com/robincsamuel/ghost-google-drive/). I’m not able to require the `ghost-storage-base` from the module. It works if I install `ghost-storage-base` in the storage module separate.

Ghost-CLI version: 1.9.8
Ghost version: 2.9.1

**Comment by allouis** [comment]
> It works if I install ghost-storage-base in the storage module separate.

This is expected, you must install the package to use it :relaxed:

**Comment by robincsamuel** [comment]
@allouis Oh ok! But Ghost docs says this,

> A custom storage adapter must inherit from your base storage adapter. By default the Base Storage Adapter is installed by Ghost and should be available in your custom adapter.

https://docs.ghost.org/concepts/storage-adapters/
