### ISSUE TITLE
there have three spaces for code in markdown editor.

### ISSUE THREAD

**Issue by QAQFaker** [TryGhost/Ghost#10347]
have a code like :

![image](https://user-images.githubusercontent.com/10682635/50773604-3bf43800-12cc-11e9-9b44-8b59d9d3f67f.png)

there always have three spaces like:
any code have this issue, not only shell script.

![image](https://user-images.githubusercontent.com/10682635/50773666-59c19d00-12cc-11e9-877e-efa0eb33decf.png)

known issue? or something wrong with me?

version: ghost:2.9

**Comment by kevinansfield** [comment]
@QAQFaker this is a theming issue. For help/support for modifying themes, please use the forum (https://forum.ghost.org/c/themes) or contact your theme developer.
