### ISSUE TITLE
Update api versions

### ISSUE THREAD

**Issue by kirrg001** [TryGhost/Ghost#10357]
The goal is to support three API versions in the future.

We currently use the naming:

- active
- stable
- deprecated

_**_We want to rename "active" to "experimental"._**_

**Comment by ErisDS** [comment]
Where is this mentioned in the codebase?

**Comment by kirrg001** [comment]
e.g. https://github.com/TryGhost/Ghost/blob/2.10.1/core/server/config/overrides.json#L69

**Comment by ErisDS** [comment]
Ok... what does that do?! 

The v2 Content API is now stable, not experimental.

**Comment by kirrg001** [comment]
> Ok... what does that do?

Anywhere in Ghost you can ask for the e.g. current deprecated version instead of asking for a hardcoded v0.1 version url.

`urlFor('api, 'v0.1')`

vs

`urlFor('api, 'deprecated')`

It's a simple lookup object. This avoids that we have to change all api url occurrences if the api versions iterate. 

> The v2 Content API is now stable, not experimental.

Yes 👍 It wasn't changed for the release. Will make two sub tasks for this issue.

**Comment by ErisDS** [comment]
The idea that there is a fixed "deprecated", "stable" and "active" version across the whole API has been iterated on - that world doesn't exist right now (we have 1 part of the API that is stable) and I don't think we'll ever get to that world - it will always be in flux - and therefore I think it's very hard to use this to reason about in code.

When we remove the v0.1 api, we won't have another deprecated API for a while. Meanwhile the admin API will have a stability index per endpoint, part of it stable, other parts experimental. At the same time, the members API might not be stable before v3.

The stability index is something we use to communicate a promise to the community, i.e. a documentation and marketing thing. I wasn't aware it had been codified, else I would have explained the changes to everyone.
