### ISSUE TITLE
Content API should have brute protection

### ISSUE THREAD

**Issue by allouis** [TryGhost/Ghost#10359]
The content api currently has no protection against brute attacks at the moment.

We implemented ([and removed](https://github.com/TryGhost/Ghost/commit/63c8c310fb54746306ffe3544f02fae69c2b49c4)) some work for this - but the removal was necessary as it was causing deadlocks.

An explanation of why this was causing deadlocks from @pysysops

>It's because when something hits the api or more than one API endpoint at a time a transaction to insert or update the row is in progress while a delete is trying to happen. In MySQL / InnoDB every command is wrapped in a transaction behind the scenes: https://dev.mysql.com/doc/refman/5.7/en/innodb-autocommit-commit-rollback.html

> In the case of the brute implementation, a deadlock is absolutely to be expected from a DB point of view.

Ideally we want a solution that is able to blacklist an `ip` based on previous response codes. e.g. after receiving N 4xx status codes in a row - you are blocked for T hours

**Comment by kirrg001** [comment]
I just saw that we are using [`req.brute.reset`](https://github.com/TryGhost/Ghost/blob/2.10.1/core/server/web/shared/middlewares/brute.js#L91) after each request, which removes the whole key.

If we would just reset the count of the target key to 0, it would prevent deadlocks.

The deadlock arrises so often because we delete the key after each request:
- if two requests come in, they will both create a txn with a lock on the target row
- if the key does not exist, both will try to insert
- brute-knex was designed to operate on existing rows to ensure the lock works properly

**Comment by allouis** [comment]
Does that mean `brute-knex` should be updated to fix it's `reset` method? https://github.com/llambda/brute-knex/blob/master/lib/index.js#L89-L95

It seems odd to me that brute-knex requires the `ip` to exist in the database otherwise it has a chance of causing deadlocks - the rows are pruned on every request if they're out of date, so it shouldn't be that infrequent that a request comes in from an `ip` not in the database

**Comment by kirrg001** [comment]
>  the rows are pruned on every request if they're out of date

? If you call `brute.reset`, it just removes the key as far as i am aware.

> this.store.reset(key, function (err) {

**Comment by kirrg001** [comment]
> Does that mean brute-knex should be updated to fix it's reset method? 

Hmm either this or we could for now just add a `resetCount` fn, which locks the row and resets the count of the target brute key. And we figure out later if we want replace brute-knex completely or improve it or whatever. A deadlock is nothing critical, it just says you are basically doing something wrong which you could prevent.

FYI I have write permissions for brute-knex. Let me know if you need help :) 

---

Any brute key get's automatically cleaned up after while based on the lifetime property.

**Comment by allouis** [comment]
If the deadlock is caused by getting two requests from an ip that doesn't exist in our table, like you explained in your bullet points - I'm not 100% sure how the `resetCount` method will fix the issue, because like you said, any brute keys get cleanup automatically, so we're still going to be in a state where 2 requests come in, both try to create locks, etc...?
