### ISSUE TITLE
pm2 blog account got deleted

### ISSUE THREAD

**Issue by shubs** [TryGhost/Ghost#10358]
Hi,

I am the one in charge of the pm2.io blog (we have a lot of content about ghost)

We canceled our account thinking that it will last until the end of the subscription.
But your system deleted our account + Put our blog offline .

This is a big issue on our end, can you please, reactivate our account? 
We have a lot of users who are reporting the down of our website.

Kind regards

**Comment by allouis** [comment]
Hey @shubs :wave: 

All Ghost(Pro) issues should go through our dedicated support channel! Please send an email to support@ghost.org with your details :relaxed:

**Comment by vmarchaud** [comment]
@allouis No one is answering since yesterday afternoon :(
