### ISSUE TITLE
Strange behavior with subpath and Apache redirect

### ISSUE THREAD

**Issue by Dixeran** [TryGhost/Ghost#10368]
### Issue Summary

I'm using Apache2 with ProxyPass. But all static files (/public) are loaded in a wrong path.

### To Reproduce
My apache config:
```
ProxyPass /ghost http://127.0.0.1:2368/
ProxyPassReverse /ghost http://127.0.0.1:2368/
<Proxy *>
           Order Deny,Allow
           Allow from all
</Proxy>
```

My ghost config:
```
"url": "http://example.top/",
  "server": {
    "port": 2368,
    "host": "127.0.0.1"
  },
  "database": {
    "client": "sqlite3",
    "connection": {
      "filename": "./content/data/ghost.db"
    }
  }
```

now I can open the frontpage(http://example.top/ghost), but all static files are failed. Ghost is still try to read from root path.
![](https://i.loli.net/2019/01/13/5c3a1cdee45d0.jpg)

The right path should be`https://example.top/ghost/public/ghost-sdk.min.js?v=4bc39e7c89` while `/ghost` was missing.

BUT if I consider use the config bellow:
```
"url": "http://example.top/ghost",
  "server": {
    "port": 2368,
    "host": "127.0.0.1"
  }
```

I will get this (http://example.top/ghost)
```
Cannot GET /
```

### Technical details:

* Ghost Version: 2.10.1
* Node Version: 8.11.4
* Browser/OS: Ubuntu 18
* Database: sqlite3

**Comment by kevinansfield** [comment]
Hey @Dixeran 👋 Friendly reminder: help or support is not available on Github. Our default issue templates pointed you to our [forum](https://forum.ghost.org) for this type of question 😄 We use GitHub solely for bug-tracking and on-going feature development so we try to keep it noise free.

Many questions can be answered by reviewing our docs for [self-hosters](https://docs.ghost.org), our [theme API](https://themes.ghost.org), or our [public API](https://api.ghost.org). If you can't find an answer then our [forum](https://forum.ghost.org) is a great place to get community support, plus it helps create a central location for searching problems/solutions.

FYI: Many projects have their own support guidelines and GitHub will highlight them for you, or the project owners will use issue templates to point you in the right direction. Reading the guidelines or issue templates before opening issues can save you and other project maintainers some valuable time.
