### ISSUE TITLE
URL service decoupling

### ISSUE THREAD

**Issue by gargol** [TryGhost/Ghost#10360]
## Known Problems

1. The URL service uses the model layer directly. The decision was made before we invented API versions. The decision was made because raw knex queries are so much faster than using Bookshelf. _We couple the URL Service (frontend) with the model layer._ 

2. The URL service listens on Ghost events and sometimes we have to re-fetch the data from the database because these events are API independent (!) e.g. v2 does only show authors with posts. But the model layer doesn't know that.

3. Because of (2), we run into the problem reported [here](https://github.com/TryGhost/Ghost/issues/10356). We can't do any async operations if the Ghost events are triggered, because otherwise, the API will return 404 urls. We couple the API with the URL service.

4. URL Utils are used throughout codebase which couples it to every module in the system. (solved in https://github.com/TryGhost/Ghost/issues/10773)

## Future Architecture

Imagine you split Ghost into two repositories:

- API (models...)
- Frontend (Handlebars, Dynamic Routing ....all the frontend features....)

You can't because it's too coupled.

### Known Challenges:

- How to listen on API events? Webhooks?
- Use the Content API directly
- Can we continue using [knex_raw](e)? (described [here](https://github.com/TryGhost/Ghost/issues/10124)) or should we look for an alternative approach?

### Also to consider
Some tests were disabled due to delay introduced by additional db call in resources service and would be re-enabled after the new mechanism is in place. Related [convo](https://github.com/TryGhost/Ghost/commit/df1ba8aee1e3a9f2032d3a96b0684b8c1a3cd353#r31932511)

**Comment by kirrg001** [comment]
Updated the issue description a little. More coming soon...

**Comment by kirrg001** [comment]
@ErisDS 🤔 Could you pls leave a reason why you've closed this issue?

**Comment by ErisDS** [comment]
All issues tagged with `routing` have been tagged with `later` and closed until we prioritise working on the Routing feature again.
