### ISSUE TITLE
Please add an example of edition / creation / deletion of post.

### ISSUE THREAD

**Issue by gustawdaniel** [TryGhost/Ghost#10394]
Please add an example of edition / creation / deletion of post.

> https://api.ghost.org/docs/post

I cant suggest it on this page because I do not have an account on Readme.io

> https://api.ghost.org/login

It is connected with https://github.com/TryGhost/Ghost/issues/10324 where working on Admin API v2 is promised. I can wait with automatization of my process but It would be very nice for me if any estimated time of publishing API v2 would be presented.

**Comment by kirrg001** [comment]
Hey @gustawdaniel   👋 Friendly reminder: help or support is not available on Github. Our default issue templates pointed you to our [forum](https://forum.ghost.org) for this type of question 😄 We use GitHub solely for bug-tracking and on-going feature development so we try to keep it noise free.

Many questions can be answered by reviewing our docs for [self-hosters](https://docs.ghost.org), our [theme API](https://themes.ghost.org), or our [public API](https://api.ghost.org). If you can't find an answer then our [forum](https://forum.ghost.org) is a great place to get community support, plus it helps create a central location for searching problems/solutions.

FYI: Many projects have their own support guidelines and GitHub will highlight them for you, or the project owners will use issue templates to point you in the right direction. Reading the guidelines or issue templates before opening issues can save you and other project maintainers some valuable time.

**Comment by gustawdaniel** [comment]
Thank you. For people that will find this issue in future:

> https://forum.ghost.org/t/to-publish-a-post-with-api-v0-1-should-be-used/3828

> https://forum.ghost.org/t/post-by-api-failure/3126
