### ISSUE TITLE
Enforced filter logic has incorrect grouping

### ISSUE THREAD

**Issue by gargol** [TryGhost/Ghost#10398]
As c3e22b6ab9bae249aee131094bae10ea5c5ed2ea was investigated similar logic has been spoted in custom [filter](https://github.com/TryGhost/Ghost/blob/master/core/server/models/plugins/filter.js#L72): 
```
custom = `${custom}+${extra}`;
``` 
A correct one would be:
```
custom = `(${custom})+${extra}`;
``` 

To reproduce this bug a custom filter with multiple `or` conditions should be defined and applied to the model which has `extra` filters defined (e.g.: post with `staticPages`), concrete example of the NQL filter:
```
?filter=page:[false,true],published=true&status=all
```
the filter above would wrongly group `published` with `status` into an `and` group and would leave `page` as a separate `or` and what actually whould happen in `page` and `published` should be in an or group and `status` should be in separate `and` grouping, something like:
```
$and: [
  {$or: [
    {page: ...},
    {published: ...}
  ]}
  {status: ...}
]
```

When working on this issue [known grouping nql bug](https://github.com/NexesJS/NQL-Lang/issues/7) should be taken into account and made sure we don't run into it. The reason is using multiple parentheses for correct grouping on different levels (here and in c3e22b6ab9bae249aee131094bae10ea5c5ed2ea) makes the risk of running into this bug very high.

**Comment by ErisDS** [comment]
Is this a bug in NQL, or in Ghost? How does one reproduce it? If it's really just a 2 char change, could it not be done and closed?

**Comment by gargol** [comment]
@ErisDS updated the issue to be more clear and have a reproducible example. It looks like a 2 char change, but the implications of causing NQL bug need to be taken into account and probably solved before such change goes into master. 

Was planning to look closer into this following Monday and created just a small issue/note not to forget  :smiley:  Can we place it back into backlog?
