### ISSUE TITLE
Pages inadvertently returned in posts query with Ghost 2.11.1

### ISSUE THREAD

**Issue by luciandavidescu** [TryGhost/Ghost#10395]
When I do a complex query like...

`{{#get "posts" limit="5" filter="author:{{primary_author.slug}}+id:-{{id}},tag:{{primary_tag.slug}}+id:-{{id}},featured:true+id:-{{id}}"}}`

...it also returns some pages. In order to achieve the intended outcome, I need to specifically exclude pages from each grouping like this:

`{{#get "posts" limit="5" filter="author:{{primary_author.slug}}+id:-{{id}}+page:false,tag:{{primary_tag.slug}}+id:-{{id}}+page:false,featured:true+id:-{{id}}+page:false"}}`

It does work, but I suppose pages shouldn't have been there in the first place.

**Comment by gargol** [comment]
Hey @luciandavidescu :wave: Thanks for reporting the bug! It's has been fixed and will be present in  the next release (tomorrow), so no need for `+page:false` filters anymore :smiley:
