### ISSUE TITLE
Preact watch should not clear the console

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#10409]
Optimize Preact watch script to not clear console on start. Currently it clears output once on start in watch mode, which can lead to losing some imp startup info.

## Steps to reproduce

- run `grunt dev`

**Comment by rishabhgrg** [comment]
## Context

Members static frontend was setup using [Preact CLI](https://github.com/developit/preact-cli) and by default `preact-cli` is also the build tool for its dev and production modes out of the box. Running `grunt dev` at root level also runs `preact watch` in the members static [folder](https://github.com/TryGhost/Ghost/blob/master/core/server/lib/members/static/auth/package.json#L7), which starts a webpack dev server with live reloading on `localhost:8080` to build members UI. Currently `preact watch` clears console after its run,  removing any startup info logged before it.

## Problem
Preact cli currently doesn't provide any config option which can disable this forced behaviour of clearing console on running, the guilty code itself being a one-liner [here](https://github.com/developit/preact-cli/blob/master/src/lib/webpack/run-webpack.js#L63). There are some discussions around possibly adding this feature in future [here](https://github.com/developit/preact-cli/issues/289#issuecomment-323606890), but isn't possible at the moment. 

Simplest fix which allows us to take advantage of all preact-cli's built in optimizations while not clearing console atm is to fork and publish modified version of cli, which will just remove the one line. A longer fix would be to replace `preact-cli` with our custom build step which does something similar, though personally it seems its better to go with former to take advantage of preact-cli's build optimizations.
