### ISSUE TITLE
Content API v2: Authors 404

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#10410]
This is a very similar bug to https://github.com/TryGhost/Ghost/issues/8710, https://github.com/TryGhost/Ghost/issues/4525, https://github.com/TryGhost/Ghost/issues/5947

Expected behaviour:

v0.1 Public API /users/ -> returns all users
v2 Content API / authors/ -> returns all authors that have content

This should be regardless of the `status` field, the `status` field is for locking users out of the backend, not removing them from the frontend.

### To Reproduce

1. Create an author that is suspended
2. Set your theme to use the v0.1 API
3. Visit the authors page (it will render)
4. Switch to the v2 API
5. Refresh the authors page and it will 404

Also reported here: https://forum.ghost.org/t/imported-users-are-locked/5190/3, is that this is happening for locked users, but I haven't managed to reproduce yet.

### Technical details:

* Ghost Version: master

**Comment by ErisDS** [comment]
Note: there's now significant useful info in the forum thread, there appears to be a cluster of small bugs here.

**Comment by kirrg001** [comment]
Priority for Monday 👍

**Comment by kirrg001** [comment]
This bug appears on v0.1 and v2 if you suspend a user on runtime. 

The model layer triggers a deactivated event and the url service removes the url. 
If you restart Ghost, the bug disappears.
