### ISSUE TITLE
Active theme is not always available

### ISSUE THREAD

**Issue by kirrg001** [TryGhost/Ghost#10416]
Example reference: https://forum.ghost.org/t/after-update-ghost-dont-start/4949/19

## Problem

We have a theme service and a couple of places where we ask for the active theme.

But if you start Ghost and the active theme cannot be found (e.g. does not exist on your server), the active theme is not available -> `themeService.getActive().engine` will crash.

We allow Ghost to start up, because we want to allow serving the admin panel.

## Possible solution

- Protect the code areas against `themeService.getActive()` beeing null

**The solution needs to be confirmed first.**

Any help is appreciated :)

Ghost: master

**Comment by ErisDS** [comment]
FWIW - this is a regression bug. Ghost should _always_ start without an active theme, and the admin panel must be accessible.

**Comment by kirrg001** [comment]
Oh yeah just tested it. Ghost does not start at all.
