### ISSUE TITLE
Error "Cannot read property 'substring' of null" when post/page is empty

### ISSUE THREAD

**Issue by fueko** [TryGhost/Ghost#10429]
### Issue Summary

Error "Cannot read property 'substring' of null" when post/page is empty

### To Reproduce

1. Create new post with title but with empty content
2. Publish
3. Error 500 - "Cannot read property 'substring' of null"

For posts - it block the entire blog.
For pages - only page.

### Technical details:

* Ghost Version: 2.13.0
* Node Version: 8.12.0
* Browser/OS: Safari / macOS 10.14.3
* Database: SQLite

**Comment by gargol** [comment]
Hey @fueko Thanks for the quick report! Already fixed it here bc90b8ec27fda3b056a7493c76e0c3f00d090606
