### ISSUE TITLE
eslint node min version is ^8.10

### ISSUE THREAD

**Issue by kirrg001** [TryGhost/Ghost#10420]
Decision: https://github.com/eslint/tsc-meetings/blob/4604d91e9e0c546b9bf336ed24dc9a7998a17010/notes/2018/2018-04-12.md#drop-supporting-nodejs-4

Forum: https://forum.ghost.org/t/cant-update-ghost-to-the-latest-version-2-12/5277

> @not-an-aardvark proposed supporting ^6.14.0 || ^8.10.0 || >=9.10.0, which includes AWS Lambda support.
👍 from @mysticatea, @kaicataldo, @btmills, @alberto, @not-an-aardvark

---

I am not sure why it complains, because it's a **dev dependency only**?

**Comment by vikaspotluri123** [comment]
I think it's an issue with brute knex - eslint [is a dependency](https://github.com/llambda/brute-knex/blob/master/package.json) (not a devDep); same with `should` which should also be converted to a devDep

```bash
yarn why eslint
$ yarn why v1.13.0
[1/4] 🤔  Why do we have the module "eslint"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "eslint@5.12.1"
info Has been hoisted to "eslint"
info Reasons this module exists
   - Specified in "devDependencies"
   - Hoisted from "grunt-eslint#eslint"
=> Found "brute-knex#eslint@4.19.1"
info This module exists because "brute-knex" depends on it.
=> Found "rewire#eslint@4.19.1"
info This module exists because "rewire" depends on it.
=> Found "eslint-plugin-sort-imports-es6-autofix#eslint@4.19.1"
info This module exists because "eslint-plugin-ghost#eslint-plugin-sort-imports-es6-autofix" depends on it.
✨  Done in 1.42s.
```
