### ISSUE TITLE
Admin API v2 Validation Improvements & Breaking changes

### ISSUE THREAD

**Issue by kirrg001** [TryGhost/Ghost#10438]
We have tested the Admin API v2 and detected a couple of bugs and misbehaviours for input and output streams.

###  Introduce a **JSON Input schema** to fix these input bugs and 500's: @gargol 
  - [x] merge first minimal version of JSON input schema for posts
  - [x] Getting 500 for POST to /posts with "feature_image": 1
  - [x] Can create a post just with an `id` property and it returns undefined title/slug. Expect that it minimum requires a `title` field 
  - [x] Can send status:'any' and it accepts and returns this value 
  - [x] Sending "tags": [{}] to /posts it is accepted and interpreted as the first tag
  - [x] 500 when sending wrong mobiledoc format e.g. mobiledoc=”test”
  - [x] /posts feature_image can be set to arbitrary sting (doesn't have to be a url)
  - [x] /posts accepts  `id:'any'` when adding resources and returns it
  ~when making a POST to /uploads with empty `uploadimage` key (couldn't reproduce) @gargol~   
  - [x] Investigate logic when sending  "tags": [{}] and it is interpreted as the first tag (raised https://github.com/TryGhost/bookshelf-relations/issues/6)
  - [x] /tags feature_image can be set to arbitrary sting (doesn't have to be a url)
  - [x] when trying to set a tag for a post which does not exist
    - `posts = [{tags: [{id: "5c62c213f16105281dac0281"}]}]`
  - [x] Make sure `tags: [ ]` syntax works for posts when removing all related tags
  - [x] Review: Normalize empty fields to null instead of empty string 
(https://github.com/TryGhost/Ghost/issues/10388 , https://github.com/TryGhost/Ghost/pull/10425) 
    - empty fields are handled on the model layer atm, and validation layer doesn't have to intervene with them
  - [x] Scan Admin API v2 input serializer and look for code pieces which can be solved with JSON schema (https://github.com/TryGhost/Ghost/pull/10495)
  - [x] Input schema for pages (if we have splitted posts & pages) @kirrg001 

###  Optimise **error messages** @gargol 
  - [x] Make error message visible on the frontend more informative
    - [x] include action that failed to perform in `message` of error returned by API
    - [x] update [JSONErrorRenderrer](https://github.com/TryGhost/Ghost/blob/master/core/server/web/shared/middlewares/error-handler.js#L64) to include error id, help, and code properties
  - [ ] Fix https://github.com/TryGhost/Ignition/issues/69
  - [x] Sending the body requires a root key (e.g. posts = []), but if i send the root key with an empty array, it still complains about the root key
  - [x] We throw a validation error for incorrect date format for e.g. created_at, but you can’t set created_at field. Note: these fields are now stripped and don't have validation on therm
  - [x] When sending an empty request to /uploads message is: “Please select an image." but the errorType "NoPermissionError" 
- [x] discuss validation errors

###  Optimise/Discuss Relations @kirrg001 
- [x] sum up how the current state works
- [x] discuss which format is useful & wishful
- [x] implement shortcut for authors + tags (https://github.com/TryGhost/Ghost/issues/10504)
- [x] discuss how we require setting the author for integrations
- [x] discuss that authors[*].id is required

### Other **Breaking Changes**
  - [x] Fix returned path for the asset from relative to absolute in the response from /uploads (to be /images) @gargol 
  - [x] handle creating posts & authors for integrations short-term
  - [x] Add /images/ next to /uploads/
  - [x] /images/ returns relative to path
  - [x] drop /uploads/ for now and return an object instead of a string @gargol 
  - [x] ~POST /posts should throw 404~ Not important atm
  - [x] collision detection - require updated_at for post updates?
  - [x] v2 config endpoint returns client id and secret
  - [x] split posts & pages as we did in content api v2 (https://github.com/TryGhost/Ghost/pull/10494)
  - [x] get rid of status=all (this is an old behaviour of the v0.1 API, because public & admin api lived on one url @kirrg001 
  - [x] rename `/images` `uploadimage` FormData field to `file` @gargol
    - [x] update the rest of endpoints that accept uploads themese, routes etc. to have `file` field in them
###  **Output serialisation** @kirrg001 
  - [x]  `tag.parent`
  - [x]  `ghost_auth_id`
  - [x]  single author e.g. `post.author_id` or `post.author` for `/post` endpoint
  - [x] remove all unused fields!

**To be continued** 🙂

**Comment by kirrg001** [comment]
FYI: 

The Admin client currently always sends "updated_at". It is the last time stamp it received from the server from GET.

The collision plugin was pretty simple implemented and won't work anymore if the client does not send "updated_at". In worst case, integrations will update other updates.

**Comment by gargol** [comment]
> possibly changes the output format of /images endpoint to something more future-proof (responds with just a url at the moment)

Current example response to an uploaded image is:
```
"http://ghost.local/content/images/2019/02/image-1.png"
```
This format is very unflexible for any future changes because for example, if we decide to return `original_url` along with current one (resized/optimized image url) there would be no way to do that without breaking current format.

If we replace the current response with following form:
```
{
    url: 'http://ghost.local/content/images/2019/02/image-1.png'
}
```
that gives us space for later to add more inforation without breaking change, e.g:
```
{
    url: 'http://ghost.local/content/images/2019/02/image-1.png',
    original_url: 'http://ghost.local/content/images/2019/02/image-1_o.png'
}
```
@kirrg001 let me know what you think :thinking:

**Comment by kevinansfield** [comment]
> * POST /posts is not redirected to /posts/

POST requests can't be redirected. It's possible we could send a 307 back but I don't know how many clients can actually handle that. My guess is that if `POST /posts` is not allowed then it should error rather than redirect.

**Comment by kirrg001** [comment]
> POST requests can't be redirected.

Yeah this task should look at 307 or 404 ✌🏻

**Comment by kirrg001** [comment]
Closing. Added the Ignition design bug to the project board.
