### ISSUE TITLE
Has helper bug

### ISSUE THREAD

**Issue by furyscript** [TryGhost/Ghost#10436]
I have found an issue with `has` helpers. 
Think on line https://github.com/TryGhost/Ghost/blob/master/core/server/helpers/has.js#L110
Because if you try to use `{{#has any="next"}}` not work.
Lodash `isEmpty` only works for map, object not for basic value.

**Comment by kevinansfield** [comment]
You haven't said what context `{{#has any="next"}}` is being used in. `next`/`prev` are only available inside the pagination helper, you can see examples of usage here https://forum.ghost.org/t/conditionals-in-handlebars/1928/.

Closing as there's no reproducible bug here. Please use the [forum](https://forum.ghost.org) to get support for your particular usage, be sure to include enough information for someone to help you such as the full code snippet of what you're trying and which file it's in.

**Comment by furyscript** [comment]
Yes, sorry I used this in `index.hbs` so I have `next` available. I have debug ghost and I see that `!_.isEmpty(...)` return me false because variable `next` isn't an array or object.

**Comment by kevinansfield** [comment]
Please use the forum for support. Thanks.

**Comment by furyscript** [comment]
Bha... It's very simple to test, not need to open and register another account into forum. Sorry. You can just put this bug into to do list.

**Comment by furyscript** [comment]
for now i resolve with this bad practice into `pagination.hbs`

```
{{#if prev}}
{{> pagination-content}}
{{else if next}}
{{> pagination-content}}
{{/if}}
```
