### ISSUE TITLE
iOS: CMD+S shortcut works intermittently in editor

### ISSUE THREAD

**Issue by littke** [TryGhost/Ghost#10437]
### Issue Summary

Sometimes CMD + S does not work when saving edits to a published post in the new editor. Sometimes it does. 

I know mobile editing is not yet supported, but I thought I’d submit issues here for a potential day where you decide to support it. Please close if you don’t want these reports.

### To Reproduce

1. Edit a published post in the admin using iPad
2. Hit CMD-S

Expected: Saves
Actual: Sometimes it saves, sometimes it doesn’t

### Technical details:

* Ghost Version: latest
* Node Version: ?
* Browser/OS: iOS
* Database: ?

**Comment by kevinansfield** [comment]
> This is a problem because without CMD + S, there’s no obvious way of saving edits made to a draft

Changes to drafts are auto-saved, you shouldn't need to hit CMD+S at all.

Mobile support is not currently a core focus but any PRs are welcome.

**Comment by littke** [comment]
Okay, I’ve updated the post to not mention drafts. I haven’t seen drafts auto-saving properly so perhaps that’s another bug, I’ll check.

Do you still appreciate bugs filed for iOS despite it not being a core-team focus? 

Thanks for your great work.

**Comment by littke** [comment]
Auto-saving works fine on iOS. ✅
