### ISSUE TITLE
Public API does work with {{get}} element

### ISSUE THREAD

**Issue by owner** [TryGhost/Ghost#10447]
In my Ghost blog, based on Ubuntu 16.04 server - does work {{get}} element. 

`<script>console.error("The {{get}} helper is not available. The Public API flag must be enabled in labs if you wish to use the {{get}} helper. See https://docs.ghost.org/faq/api-versioning/");</script>`

I cant found a Public API button for activate this.

![2019-02-04-15 23 43](https://user-images.githubusercontent.com/24358937/52208214-e3936480-2890-11e9-8079-af26f4e7aef6.png)

* Ghost Version: 2.13.1 (latest)
* Node Version: latest
* Browser/OS: Google Chrome
* Database: MySQL

**Comment by ErisDS** [comment]
Hi @owner 

The Public API has been deprecated. This is explained in the doc link that the error points you to:

https://docs.ghost.org/faq/api-versioning/

As it is deprecated, we have removed the checkbox from any brand new install. Instead we recommend switching to the v2 API, which can be done by updating your theme's package.json as described here: https://docs.ghost.org/api/handlebars-themes/packagejson/

I realise the error is out of date, so I will update this to explain the current situation more clearly.

We also have some updates to the get helper docs planned to make this clearer. They'll happen later in the week.

**Comment by helloitse** [comment]
My package.json doc is identical to the one described in the documentation
`"engines": {
        "ghost-api": "v2"
    },`

However I'm still getting this error. I've tried deactivating and activating the theme. What could be the reason {{get}} helpers are not working?

**Comment by ErisDS** [comment]
Are you on the latest version of Ghost? 

If so, please open a topic on forum.ghost.org filling in all the details.
