### ISSUE TITLE
iOS: Can’t undo edits in admin editor

### ISSUE THREAD

**Issue by littke** [TryGhost/Ghost#10440]
### Issue Summary

There’s no way to undo changes when editing a post on an iPad. CMD+Z does not work, the software keyboard’s Undo button does nothing, there’s no “Undo” action in the browser, etc.

### To Reproduce

1. Edit a post in Safari on iPad
2. Make a change
3. Try to undo with CMD+Z or other way

Expected: Undo works
Actual: No way to undo

### Technical details:

* Ghost Version: latest
* Node Version: ?
* Browser/OS: Safari, Chrome, iPad
* Database: ?

**Comment by littke** [comment]
May be related to #10437.

**Comment by b166ar** [comment]
I vote for a better iPad support!

**Comment by littke** [comment]
@b166ar Me too. This is the best way to vote for it: 
https://forum.ghost.org/t/support-for-admin-in-ios-browsers/3763
