### ISSUE TITLE
ETA on API v2 Completion

### ISSUE THREAD

**Issue by kyuknis** [TryGhost/Ghost#10454]
I see there's been quite a few commit since 10 Dec 2018, and that there aren't many issues open for the API v2 portion of Ghost. Do we happen to have an ETA on when this will be done? I'm still eager to complete the iOS provider and model logic on the app.

**Comment by gargol** [comment]
Hey @kyuknis thanks for the interest, but GitHub is not the best medium to ask these types of questions. The default issue templates pointed you to our [forum](https://forum.ghost.org) for inquiries like this. We use GitHub solely for bug-tracking and on-going feature development so we try to keep it noise free.

The short answer is, we don’t do ETAs and we are very actively working on it, so please track our latest announcements. Content API has been released some time ago and feel free to base your work on that :+1:
