### ISSUE TITLE
Uploaded image's url is an absolute path

### ISSUE THREAD

**Issue by ddhp** [TryGhost/Ghost#10466]
### Issue Summary
Uploaded image's url is an absolute path in admin page
Is this expected?

![](https://imgur.com/sWzQpEW.jpg)

### To Reproduce

upload an image in admin page

it was a relative path before at least on v2.11.1

### Technical details:

* Ghost Version: v2.13.2
* Node Version: v8.11
* Browser/OS: Chrome
* Database: sqlite 3

Thanks in advance

**Comment by gargol** [comment]
Hey @ddhp! Yes, all images are expected to have absolute paths since the introduction of Content API :+1:

**Comment by ddhp** [comment]
Hi @gargol , thank for your reply!
I find the discussion [#1354](https://github.com/TryGhost/Ghost/issues/1354), will explain my situation there

**Comment by kirrg001** [comment]
@ddhp https://github.com/TryGhost/Ghost/releases/tag/2.14.1 was released.
