### ISSUE TITLE
admin setting missing

### ISSUE THREAD

**Issue by xiaoweizha** [TryGhost/Ghost#10465]
![image](https://user-images.githubusercontent.com/24364040/52384539-dfe22680-2ab8-11e9-945b-fafcaf952b6e.png)
my admin panel have only three options ,is this right?  I think there shuld have a system setting option?
should i set something?

**Comment by gargol** [comment]
Hi @xiaoweizha :wave: This looks like a default view for non-admin user (e.g `author` or `editor`), there are more options available if you are logged in as ad `administrator` or `owner`.  Let me know if that's not a case  :+1: but closing this issue for now.
