### ISSUE TITLE
Absolute paths in `html` field

### ISSUE THREAD

**Issue by kirrg001** [TryGhost/Ghost#10472]
Refs:
https://github.com/TryGhost/Ghost/issues/10466
https://github.com/TryGhost/Ghost/issues/1354
https://forum.ghost.org/t/json-file-from-ghost-1-to-ghost-2-help/5580

Introduced via https://github.com/TryGhost/Ghost/commit/a463a56971c5d39673e8b4f58502cf3fdeb2a46f.

**Need to figure out if this behaviour is really broken or it was wishful from the beginning.**

But the commit definitely changed a behaviour, which breaks an import/export flow.
This either needs to be handled differently for import/export, fix the html or documented correctly.

---

Previously:
- you uploaded an image in the editor
- it was returned relative and stored relative in the html field in the db
- you served the post and the API automatically transforms asset paths to absolute
- you export a JSON and import the JSON into a different domain, everything is fine, because paths are stored relative and served absolute

Now:
- you uploaded an image in the editor
- it is returned absolute and stored absolute in the html field in the db
- you served the post and the asset paths are already absolute
- you export the JSON and import the JSON into a different domain, everything is "broken", because paths are stored absolute, but domain might/has changed

---

Ghost: master/latest

**Comment by kirrg001** [comment]
Need to figure out if this behaviour is really broken or it was wishful from the beginning.

e.g. see https://github.com/TryGhost/Ghost/issues/9832

**Comment by gargol** [comment]
As summed up in https://github.com/TryGhost/Ghost/issues/10477, current behavior (returning absolute URL for /images endpoint) is correct. The transform needs to be applied to any asset in `mobiledoc` field (consequently `html`) containing absolute URLs to be changed into relative ones :+1:
