### ISSUE TITLE
Error: getaddrinfo ENOTFOUND mysql mysql:3306

### ISSUE THREAD

**Issue by b0red** [TryGhost/Ghost#10481]
When trying to run this container and connect to mysql, I keep getting the error: 
_`Error: getaddrinfo ENOTFOUND mysql mysql:3306`_

This is my ghostfile:
` `
ghost:
  image: "ghost:1-alpine"
  container_name: ghost
  hostname: ghost
  restart: unless-stopped
  ports:
    - "85:2368"
  volumes:
    - ${USERDIR}/docker/ghost/config:/config
    - ${USERDIR}/docker/ghost/data:/var/lib/ghost/content
  environment:
    - NODE_ENV=production
    - database__client=mysql
    - database__connection__host=mysql
    - database__connection__user=root
    - database__connection__password="password"
    - database__connection__database=gh0st_db
    - PUID=${PUID}
    - PGID=${PGID}
    - TZ=${TZ}
  depends_on:
    - mysql
  command: ["node", "current/index.js"]
  networks:
    - traefik_proxy
 ` `
And this is the mysql portion:
 `
`mysql:
  image: "mysql:5.7"
  container_name: mysql
  hostname: mysql
  restart: always
  volumes:
    - /etc/localtime:/etc/localtime:ro
    - ${USERDIR}/docker/mysql:/config
    - ${USERDIR}/docker/mysql:/var/lib/mysql
  environment:
    - MYSQL_ROOT_PASSWORD="password"
    - MYSQL_USER_ROOT=root
    - MYSQL_DATABASE_GHOST=gh0st_db
    - PUID=${PUID}
    - PGID=${PGID}` `
(the indentation borks out, sorry about that). 
Any tips? I've tried with - database__connection__host=mysql/localhost/127.0.0.1 but I keep getting errors.

**Comment by allouis** [comment]
The Ghost docker image is a community project not maintained by the core team, so you might want to raise the issue at [docker-library/ghost](https://github.com/docker-library/ghost) or look for community support on the forum http://forum.ghost.org :relaxed: 

Our official install guides are found in the README here: https://github.com/TryGhost/Ghost#quickstart-install

**Comment by b0red** [comment]
OK. Thanx
