### ISSUE TITLE
Dynamic Routing `filter: primary_tag:{slug}` is broken

### ISSUE THREAD

**Issue by kirrg001** [TryGhost/Ghost#10482]
I assume we introduced this bug when we've replaced GQL with NQL.

### Reproduce

1. Create a collection using `filter:primary_tag:newsletter`
2. Ensure a post has this tag as primary tag
3. Try serving the post. **It will 404.**

### Details

The URL generator tries to match JSON against a filter, but I assume the key mapping is missing, because `primary_tag: slug` is a short cut for `primary_tag.slug = slug`.

I assume `primary_author` is broken too.

Will be fixed & released asap (next Tuesday).

### Workaround

Use `filter=tag:slug` for now till this got fixed.

Ghost: master

**Comment by kirrg001** [comment]
High priority!

**Comment by pascalandy** [comment]
Hi, 
Is it fixed in 2.14.1? 

Thanks!

**Comment by kirrg001** [comment]
@pascalandy No 😐The release was already done when the bug was discovered. Will be fixed next Monday!
