### ISSUE TITLE
Update Docs

### ISSUE THREAD

**Issue by larsauswsw** [TryGhost/Ghost#10498]
In Release notes of release 2.13.2 is node v10 recommend.
In https://docs.ghost.org/faq/node-versions/ the recommended version is still v8.

What is correct?

**Comment by vikaspotluri123** [comment]
![image](https://user-images.githubusercontent.com/4383564/52862114-feb86c80-30f9-11e9-9bc3-4f04e2e1eb1f.png)

v10 has been recommended for a while now. If it's not showing up, clear your cache and check again

**Comment by larsauswsw** [comment]
Ok. Sorry. Then it was a cache problem.
