### ISSUE TITLE
Turning on Night Shift isn't storred

### ISSUE THREAD

**Issue by andreborud** [TryGhost/Ghost#10509]
### Issue Summary

When Night Shift was released I turned it on and have left it on since. But in the latest release, 2.14.3 or 2.14.2 or 2.14.1, not sure when it started, but one of these, the Night Shift setting is off by default. If I turn it on and then just reload the admin area Night Shift is off again. 

### To Reproduce

1. Enter Labs, turn on Night Shift. 
2. Reload the page.

Turning on/off public api is stored and kept between reloads. And this issue happens across multiple ghost installations I have. 

### Technical details:

* Ghost Version: 2.14.3
* Node Version: 10.14 LTS
* Browser/OS: All
* Database: MySQL

**Comment by kirrg001** [comment]
Was already fixed, will be released tomorrow.

See: https://github.com/TryGhost/Ghost/commit/40f359a2389929b1d4ff5c3954392430038d83c9

**Comment by andreborud** [comment]
Sweet. Looking forward to it! :)
