### ISSUE TITLE
iOS: Text replacements don’t work in the editor

### ISSUE THREAD

**Issue by littke** [TryGhost/Ghost#10508]
### Issue Summary

When typing in the editor using iPad, the keyboard’s text replacements should replace `:nerd_face:` with 🤓, etc. 

### To Reproduce

1. Switch to the English keyboard (Settings → General → Keyboard)
2. Edit a post in the Ghost admin using Safari or Chrome
3. Type `:nerd_face:`

Expected: Converts into emoji
Actual: Nothing

### Technical details:

* Ghost Version: latest
* Browser/OS: iPad Pro 11”, latest iOS, Chrome/Safari

**Comment by kevinansfield** [comment]
There is no text replacement for emojis in Ghost's editor so this is expected. If you want emoji autocomplete you could add your vote to the feature on the Ideas board https://forum.ghost.org/t/emoji-autocomplete/882.
