### ISSUE TITLE
iOS: Cursor becomes invisible in editor

### ISSUE THREAD

**Issue by littke** [TryGhost/Ghost#10507]
### Issue Summary

When using the editor, sometimes the cursor becomes invisible. You can still type and edit, you just don’t see the blinking cursor. 

Tapping in the browser’s URL bar and then back into the editor makes it reappear.

### To Reproduce

Don’t have a 100% reproduction yet but it happens consistently enough that I had to report it.

1. Start editing a post in Safari or Chrome on iPad
2. Tab between tabs in the browser? Tab between apps? Then come back
3. Note how the cursor is no longer visible

### Technical details:

* Ghost Version: latest
* Browser/OS: iPad 11”, latest iOS, Chrome & Safari

**Comment by kirrg001** [comment]
@kevinansfield ping 🙂
