### ISSUE TITLE
Settings API response is missing `value` properties for code injection settings

### ISSUE THREAD

**Issue by kevinansfield** [TryGhost/Ghost#10518]
### Issue Summary

After clicking Save on the Code Injection screen with empty inputs the `/settings/` API response will be missing the `value` properties for `ghost_head`/`ghost_foot`/`code_injection_head`/`code_injection_foot`.

Before https://github.com/TryGhost/Ghost-Admin/commit/5727dc8ed53a85f9d567d89105a91ef11cf3b38d this meant that the Code Injection inputs were broken.

### To Reproduce

1. Initialise a new blog and start it up
2. Open the Code Injection screen
3. Click "Save"
4. Inspect the network response for the settings endpoint

<img width="544" alt="screenshot 2019-02-23 at 10 32 47" src="https://user-images.githubusercontent.com/415/53281148-6d2ea780-3756-11e9-84de-4a0406705696.png">

### Technical details:

* Ghost Version: 2.15.0
* Node Version: 10.15.1
* Browser/OS: Chrome / macOS
* Database: MySQL

**Comment by kirrg001** [comment]
Thanks @kevinansfield We will take a look asap. Priority for Monday.

Ref: https://forum.ghost.org/t/i-cant-input-any-code-to-the-code-injection-blog-header/5672/11

**Comment by kirrg001** [comment]
Can reproduce 👍
