### ISSUE TITLE
Double error on collision detection

### ISSUE THREAD

**Issue by JohnONolan** [TryGhost/Ghost#10514]
Chrome / Latest Pro

When someone else is editing and you try to update a page:

![image](https://user-images.githubusercontent.com/120485/53233614-62293800-36c0-11e9-9012-f5c21797cbe0.png)

**Comment by kirrg001** [comment]
I can't reproduce. Do you have steps to reproduce?

**Comment by JohnONolan** [comment]
- open a post which is already published on one computer, and make some edits
- open the same post on another computer, make some edits, and try to 'update'

expected: 1 error, got: 2 errors

**Comment by kirrg001** [comment]
I don't have two computers. I am not getting two error messages when using two tabs.

**Comment by JohnONolan** [comment]
I don't know what to tell you, you can see from the screenshot that it happened, and I've described what lead up to it 🙃

sounds like a race condition between these two error messages, I can't really suggest much more than that

**Comment by kirrg001** [comment]
@kevinansfield Any idea how this is possible? Thanks

**Comment by kevinansfield** [comment]
Hmm, the first error is coming from the [editor controller's `_showErrorAlert`](https://github.com/TryGhost/Ghost-Admin/blob/master/app/controllers/editor.js#L771-L797) function (found by the "Update failed:" prefix). The second doesn't have the prefixed text which suggests the error wasn't fully handled and as a result it bubbled up to the application route and hit the generic network error handling.

Alerts in the admin are keyed to avoid showing the same error twice but that won't work if an error gets handled in two different places in the app with alerts being generated with a different key in each.

I can't reproduce when editing text but maybe it was a different action that triggered a save. I'll try and dig further.

**Comment by kevinansfield** [comment]
A slightly hacky fix but one that could help avoid similar situations could be to remove the prefixes added by the editor alert display (no longer necessary with the updated API errors anyway) and then update our notifications service to de-duplicate on message content as well as key.
