### ISSUE TITLE
Safari: Scrolling on stories pane does not load older items

### ISSUE THREAD

**Issue by marcbinz** [TryGhost/Ghost#10521]
### Issue Summary

When scrolling the stories pane down to the bottom, the spinner indicating the loading of older stories appears, but the entries do not get loaded and the spinner stays indefinitely.
This issue seems to only occur in the Safari browser, when testing with Chrome or Firefox the issue is not reproducible. As far as I can tell, it looks like no request to `api/v2/admin/posts/` is triggered.

The issue #9493 might be related to this problem (already closed).

The version of Safari in use is 12.0.3 (14606.4.5) with MacOS 10.14.3 (Mojave).

### To Reproduce

1. Open the admin panel of your ghost installation (`/ghost`) in Safari. You will automatically land on the list of stories.
2. Scroll down to the end of the list to trigger the spinner. If you take a look at the browsers dev tools you should neither see any request to the API nor an error in the console.

### Technical details:

* Ghost Version: 2.14.3
* Browser/OS: Safari (12.0.3) / MacOS 10.14.3
* Database: MariaDB (10.4.2)

**Comment by like-a-freedom** [comment]
I see the same issue on my standalone installation.

Mac OS 10.14.3 (18D109)
Safari version 12.0.3 (14606.4.5)
Ghost-CLI version: 1.9.9
Ghost version: 2.15.0 (at /var/www/ghost)
mysql  Ver 14.14 Distrib 5.7.25, for Linux (x86_64) using  EditLine wrapper

**Comment by kirrg001** [comment]
@kevinansfield ping 🙂
