### ISSUE TITLE
Copying text into the Ghost Editor results in weird double spaces

### ISSUE THREAD

**Issue by jesseonslow** [TryGhost/Ghost#10530]
When pasting text from the clipboard the ghost editor seems to insert additional spaces on new lines. I've included a screenshot below. Pasting without formatting makes no difference.

![spacing](https://user-images.githubusercontent.com/40768768/53318915-cbe95200-390b-11e9-95e4-ca8c36a6b54b.png)

**Comment by ErisDS** [comment]
Hey @jesseonslow   👋 When you raised this bug you were presented with a template to fill out, which explained what details we need.

Without the details of how to reproduce the bug, we can't understand what is happening, and therefore there's no way it can be fixed. 

If you want support - please use the [forum](https://forum.ghost.org), if you want to raise a bug, please provide the full details.
