### ISSUE TITLE
No space between paragraphs in excerpt

### ISSUE THREAD

**Issue by gargol** [TryGhost/Ghost#10531]
### Issue Summary

It occurs in Ghost 2.15.0 with default Casper theme.

### To Reproduce

1. Create a post with two paragraphs that would produce html similar to: 
```
<p>Testing.</p><p>Space before this text.</p>
```
2. Publish the post.
3. Go to blog's main page and check the excerpt of the newly published post.

The text of the excerpt reads: `Testing.Space before this text.` but should be `Testing. Space before this text.`

### Technical details:

* Ghost Version: 2.15.0
* Node Version: v10.15.1
* Browser/OS: Ubuntu 18.04
* Database: MySQL

**Comment by kirrg001** [comment]
Is that a critical bug?

**Comment by gargol** [comment]
Not critical, just something @JohnONolan asked about today.

**Comment by kirrg001** [comment]
Okay if not critical, it has no priority for today 👍

**Comment by gargol** [comment]
If somebody picks this up, here is a PR with a test case that describes the issue -https://github.com/TryGhost/Ghost/pull/10532 :wink:

**Comment by Hassanraja447** [comment]
I want to do this but can anyone guide me where I can solve this issue?

**Comment by gargol** [comment]
Hey @Hassanraja447 :wave: Would start with looking at the test case in the PR I mentioned above and work your way into the place where it's most suitable to do the change. From a very quick glance seems like https://github.com/TryGhost/Ghost/blob/master/core/server/data/meta/excerpt.js is a good candidate :wink:

**Comment by Hassanraja447** [comment]
> Hey @Hassanraja447 👋 Would start with looking at the test case in the PR I mentioned above and work your way into the place where it's most suitable to do the change. From a very quick glance seems like https://github.com/TryGhost/Ghost/blob/master/core/server/data/meta/excerpt.js is a good candidate 😉

Thank you I will give it a shot

**Comment by NCHydr4** [comment]
Hello @gargol you are right the issue was on the  https://github.com/TryGhost/Ghost/blob/master/core/server/data/meta/excerpt.js file line 9 - 10

```
excerpt = excerpt.replace(/<\/?[^>]+>/gi, ' ');    <--- I added a space.
excerpt = excerpt.replace(/(\r\n|\n|\r)+/gm, ' ');

```
Now after the restart there is a space betweed 
`Testing. Space before this text.`

**Comment by gargol** [comment]
@NCHydr4 this regexp catches all of html tags, and would produce extra spaces in places we don't really want, e.g. `<a href...>link</a>`  would give you extra space. We probably want to be very specific about the type of tags that are transformed into additional space, `<p></p>` would be a good start :+1: Alternatively, could substitute all tags with space, and dedup double spaces :thinking:  Think this case needs some playing around to find the best approach :wink:

**Comment by NCHydr4** [comment]
@gargol Thx for your reply, I guess adding something like` excerpt = excerpt.replace(/<\/p>/g," ");`  before the two excerpt could be a good start (I've tried it and it works).
I dont know if it is neccesary to add a replace rule for the <p>.

```
    excerpt = excerpt.replace(/<\/p>/g,' ');
    excerpt = excerpt.replace(/<\/?[^>]+>/gi, '');
    excerpt = excerpt.replace(/(\r\n|\n|\r)+/gm, ' ');
```
I dont know if that could be a real solution, I keep looking for something more suitable.

**Comment by kscott5** [comment]
@nchydr4. defensive code is good. A unit test helps here if possible. @gargol

**Comment by JohnONolan** [comment]
Not stale. 

@gargol would you be able to choose an approach and get this closed?

**Comment by lunaticmonk** [comment]
@gargol @JohnONolan  How about using an array of the regex for which we want to introduce a whitespace?
Somewhat like this:

```js
const whiteSpaceExcerptRegex = new Array(/<\/p>/g);
for (const regex of whiteSpaceExcerptRegex) {
    excerpt = excerpt.replace(regex, ' ');
}
```

I tried this approach. Seems to work fine. Let me know your thoughts on this.

**Comment by gargol** [comment]
@lunaticmonk in #11053, took the most simplistic approach to the issue and added a single substitution rule for closing `</p>` tag and line break `<br>` - that's the case that covers 99% of HTML that comes out of internal mobiledoc format. In case there are more cases surfacing in the future more cases can be added to the grouping in the RegExp: `/(<\/p>|<br>|other_cases...)/`
