### ISSUE TITLE
The image preview is not updating when we upload a new header picture

### ISSUE THREAD

**Issue by pascalandy** [TryGhost/Ghost#10544]
### Issue Summary

the image preview is not updating

### To Reproduce

write a post
upload a picture as the header pic
publish a post

changed my mind
delete the picture
update another picture

share my post
the image preview is the OLD pic

### what should happen

ghost should update the image preview with the latest image uploaded

### old picture

![screen shot 2019-02-26 at 10 56 27 am](https://user-images.githubusercontent.com/6694151/53426989-0b6c7880-39b6-11e9-8811-7d5e51f8aa79.jpg)

this is wrong

### newest picture

![screen shot 2019-02-26 at 10 56 21 am](https://user-images.githubusercontent.com/6694151/53427000-12938680-39b6-11e9-958a-9d46120ce1aa.jpg)

ghost don't see this one. You can see the date is not the same.

### Technical details:

* Ghost Version: 2.13.0
* CLI version: 1.9.9
* Node Version: 10.15.1
* Browser: Chrome 71
* OS X: 10.13.6
* Server: Docker [using this image](https://travis-ci.org/firepress-org/ghostfire/jobs/428717032)
* Database: SQLite

**Comment by kirrg001** [comment]
@allouis Might be related: https://forum.ghost.org/t/pulication-icon-cant-be-changed/5925

**Comment by kirrg001** [comment]
Cannot reproduce on my production blog (2.15).

**Comment by pascalandy** [comment]
Humm, I just retried using 2.15.0
Works as it should.

Sorry about this :-p

**Comment by kirrg001** [comment]
@pascalandy 🙊no problem! Happy it works now 👍
