### ISSUE TITLE
url helper output broken if post is published, but does not live anywhere (shows preview link)

### ISSUE THREAD

**Issue by kirrg001** [TryGhost/Ghost#10541]
core/server/data/meta/url.js:

> if (data.status !== 'published' && urlService.getUrlByResourceId(data.id) === '/404/') {

Content API v2 no longer returns the status.

Steps to reproduce:

- setup a blog under /blog/
- filter by a tag which won't find posts
- see 404 on /
- see that related posts show a preview link
- click on it, you get a /404/, which is correct

**Comment by ErisDS** [comment]
Requires #10477
