### ISSUE TITLE
Issue with {{url}} for {{next_post}} and {{prev_post}} helpers

### ISSUE THREAD

**Issue by fueko** [TryGhost/Ghost#10546]
### Issue Summary

{{url}} for {{next_post}} and {{prev_post}} helpers give results `<a href="/"></a>`

### To Reproduce

Install Ghost 2.16.0-2.16.2 and open any post (with Casper theme) - after clicking `next_post` or `prev_post`, we return to the home page.

### Technical details:

* Ghost Version: 2.16.2
* Node Version: 8.12.0
* Browser/OS: Safari / macOS 10.14.2
* Database: SQLite

**Comment by kirrg001** [comment]
Can confirm. Thanks for the report 👍
