### ISSUE TITLE
Issue with {{amp_content}} helper

### ISSUE THREAD

**Issue by hichnicksemen** [TryGhost/Ghost#10547]
### Issue Summary

Empty amp page

### To Reproduce

1. Update to 2.16.2
2. Open any post in amp

### Technical details:

* Ghost Version: 2.16.2
* Node Version: 6.16.0
* Browser/OS: Chrome/Ubuntu
* Database: MySQL

**Comment by kirrg001** [comment]
Can confirm. Thanks for report 👻
