### ISSUE TITLE
Text transformations breaks editor

### ISSUE THREAD

**Issue by Caucasus-and-Mercury** [TryGhost/Ghost#10551]
### Issue Summary

When editing a post on a Mac, marking text and doing right-click: _Transformations_ and for example _Make Upper Case_ freezes and breaks the editor. No choice but reloading the window, edits are lost.

### To Reproduce

1. Mark some text
2. Right-click
3. Choose Transformations
4. Choose Make Upper Case
5. Kaput.

Any other info:

Sometimes the editor doesn't freeze at once, but it's not possible to edit and format anything further.

### Technical details:

* Ghost Version: 2.16.2
* Node Version: 10 - something
* Browser/OS: Safari/MacOS 10.14.3
* Database: mysql

**Comment by kevinansfield** [comment]
Hey @Caucasus-and-Mercury 👋 I have been trying to reproduce this but have been unable to so far. Does this happen for you with every post, even new ones with only text? How much content do you have in your posts where you see the problem and do they have any cards?

**Comment by Caucasus-and-Mercury** [comment]
Ok,

I've had a number of different situations where I had the cursor dancing around, strange behaviour and the editing process freezing. But here's  one example you should be able to reproduce:

1: Start editing a post, like this:

Title

some text
an image (jpeg)

## H2
text text

### H3
text text

an image (jpeg)

2: Then select one of the rows that reads "text text", mark the text, select _Transformations_, select _Capitalize_, fire away.

3: What happens now in my browser is the two images are gone, and there are some alien points and formatting and the word _"Upload"_ written where the pics used to be (see below). If I start typing **anywhere** in the text, the cursor immidiately jumps to the last row and text shows up there.

The whole thing is possible to fix with cmd-z, but, editing does not work anymore; the cursor and typing doesn't follow orders, as per above.

Can't copy the thing, but this is what it looks like:

Before:
![screenshot 1](https://user-images.githubusercontent.com/1909798/53928068-121b7f80-4089-11e9-8903-ecb72b9f96e1.png)

Try transformations-Capitalize....result:
![screenshot 2](https://user-images.githubusercontent.com/1909798/53928069-12b41600-4089-11e9-9417-bdf727f132fe.png)

I'm on the very latest version fo ghost. Whta you say?

**Comment by kevinansfield** [comment]
Thanks, I can confirm the bug. This looks like an issue in the upstream mobiledoc-kit library with how it's handling Safari's modifications of the contenteditable DOM but it needs further investigation.

**Comment by fadeevab** [comment]
The same bug after little manipulations in mobile Firefox (Android). Because mobile version is not totally functioning, what I have done is adding a new block of text. I've lost entire formatting including images.

Steps:
1. Go into Ghost > Edit Post in mobile Firefox Android.
2. Add new empty block.
3. Remove that empty block.
Result: existing markdown/image blocks are replaced with a plain text and big black circles are instead of old blocks.

**Comment by fadeevab** [comment]
Just double checked: it's still reproducible on 2.25.4 Firefox on Android
