### ISSUE TITLE
Next or Previous post helper Not working in API v2

### ISSUE THREAD

**Issue by mskian** [TryGhost/Ghost#10565]
next or previous post helper Not working in API v2 - https://docs.ghost.org/api/handlebars-themes/helpers/prev_next_post/

```handlebars
{{#next_post}}
<p>What's Next? - <a href="{{url}}" title="{{title}}">{{title}}</a></p>
{{else}}
<p>Oops No more New posts! Goto &rarr; <a href="{{@site.url}}">Homepage</a></p>
{{/next_post}}
```
it does not fetch the Post URL it fetch the Homepage URL

```html
<p>What's Next? - <a href="/" title="Post title">Post description</a></p>
```
PS: working well in API `v0.1`

**Comment by gargol** [comment]
Hi @mskian! This seems like the same issue that was already fixed [here](https://github.com/TryGhost/Ghost/issues/10389) & [here](https://github.com/TryGhost/Ghost/issues/10554). Please feel free to reopen if it's a different case :)
