### ISSUE TITLE
Add missing JSON schemas

### ISSUE THREAD

**Issue by kirrg001** [TryGhost/Ghost#10568]
We have already added tags, posts, pages, and images JSON schemas. 

The JSON schemas help us:
- handling input validation in a centralised place
- defining which are allowed/disallowed/required/skipped fields
- handling errors in a centralised place 

### Missing schemas for integration authentication (priority, stable endpoints)
- webhooks
- theme upload ([images endpoint schema](https://github.com/TryGhost/Ghost/blob/master/core/server/api/v2/utils/validators/input/schemas/images.json) for reference) 

### Missing schemas for user authentication (lower priority)
- users
- integrations
- settings
- notifications
- invites

**Comment by gargol** [comment]
@kirrg001 updated the issue regarding `images` schema as we have one already :wink:
