### ISSUE TITLE
Custom Integrations are not re-imported

### ISSUE THREAD

**Issue by cajoy** [TryGhost/Ghost#10579]
### Issue Summary

Integrations not re-imported

### To Reproduce

1. Login to admin panel
2. Create custom integration
3. Export as json
4. Reset ghost cms
5. login and import json

Custom integrations are not imported but exists in dump json file

### Technical details:

* Ghost Version: 2.16.3
* Database: mysql

**Comment by kevinansfield** [comment]
Confirmed reproduction, thanks for the report!

**Comment by kirrg001** [comment]
Yeah this was not implemented yet 👍

**Comment by gargol** [comment]
Related issue https://github.com/TryGhost/Ghost/issues/10273

**Comment by ErisDS** [comment]
On reflection I think this is desirable behaviour.

The main use cases for the importer are:
- helping with migrating a site from one place to another
- creating a local/staging clone of a site for development purposes

When migrating a site, it's annoying to copy across some settings manually, but it is a one-time thing. 
If you're creating a local development or staging clone of your site, auto-importing custom integrations could have unintended side effects. I don't think it's expected that production keys should work on a staging site, or that a staging site make webhook calls as if it is production.

For that reason, I think it's "correct" that you have to re-create integrations after a move. 

Note this has also only been reported a handful of times, so I think that this is also in line with most people's expectations.
