### ISSUE TITLE
content helper outputs absolute asset urls by default when using v2 api

### ISSUE THREAD

**Issue by allouis** [TryGhost/Ghost#10598]
Docs: https://docs.ghost.org/api/handlebars-themes/helpers/content
Refs: #10578

We've introduced a breaking change by mistake. With Ghost 2.0 the content helper has always output relative urls by default.

Steps to reproduce:

- Upload an image for a post
- Use theme with v2 api (Casper >= 2.9.0) 
- Use {{content}} in post template
- See that it outputs absolute url for the image

**Comment by kirrg001** [comment]
Will think about this task before Monday. Might need to prioritise.

**Comment by gargol** [comment]
Blocked by https://github.com/TryGhost/Ghost/issues/10477. The issue needs to be rechecked once the blocking one is finished

**Comment by gargol** [comment]
@kevinansfield maybe something to note/check when working on URLs soon.
