### ISSUE TITLE
Wrong Meta Description show in posts

### ISSUE THREAD

**Issue by danielperez9430** [TryGhost/Ghost#10591]
Good afternoon, I just recently discovered that from ghost 2.12.0 to the latest version 2.16.4 included. I'm having a problem with the meta description of the post.

Ghost taking the meta_description and put the content of "excerpt" inside the meta_description. In the content api is all right, but it seems that this information is not sending well to the ghost themes.

- Node: v10.14.0
- Ghost: 2.16.4
- OS Ubuntu 16.04

## Example

**Source Post**

![](https://i.imgur.com/sXOBOhc.png)

**Content API** 
![](https://i.imgur.com/kyb2slc.png)

Although as you can see excerpt is void and ghost generates an excerpt in the content api. The meta description is correct, but it does not appear in the web post. I tests with several ghost themes with the same result.

![](https://i.imgur.com/iAckK2S.png)

**Comment by mskian** [comment]
Yaaa I am already reported about this #10387
