### ISSUE TITLE
404 error when visiting the URL for a tag with no posts

### ISSUE THREAD

**Issue by dlford** [TryGhost/Ghost#10604]
### Issue Summary

404 error when visiting the URL for a tag with no posts.

I know this is a duplicate of issue  #10433 that was concluded to be expected behavior, but I implore you to reconsider, please see my comment below:

In my use case this is a bug.
One of the sites I run is for a music group, it has a tag for "Upcoming Events" in the nav bar that occasionally has no posts, but the custom theme in use still has a link in that tags page to another tag "Past Events". With this new behavior I would have to add the "Past Events" tag the the nav bar, but even then having the "Upcoming Events" link return a 404 is not a good solution when there are no upcoming events, I don't want to have to keep removing "Upcoming Events" from the nav bar and adding it back, that is confusing for users and site admins.

### To Reproduce

1. Create a new tag
2. Visit URL for new tag (e.g. mysite.com/tag/something)

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

### Technical details:

* Ghost Version: 2.17.2
* Node Version: 8.15.1
* Browser/OS: Firefox / Windows 10
* Database: MySQL

**Comment by kevinansfield** [comment]
Closing as a duplicate and a cross-post of https://github.com/TryGhost/Ghost/issues/10433#issuecomment-472435554 - a reply was added to your previous comment. If you need any further help/support please ask on [our forum](https://forum.ghost.org).
