### ISSUE TITLE
Switch to Ghost-SDK helpers

### ISSUE THREAD

**Issue by rishabhgrg** [TryGhost/Ghost#10618]
We have started to add and maintain collection of tools/helpers to interact with Ghost APIs in [Ghost-SDK], and in line with goal to streamline Ghost Core to be more headless/APIs, aim here is to update Core with existing helpers in SDK along with extracting more helpers/lib to SDK that don't belong in core

This issue collects list of existing and possible new helpers in SDK to update existing code in Ghost core:

- [x] Use [Visibility util/helper](https://github.com/TryGhost/Ghost-SDK/blob/master/packages/helpers/lib/utils/visibility.js) to replace
  - [x] in [model](https://github.com/TryGhost/Ghost/blob/master/core/server/models/base/index.js#L1170)
  - [x] in [author helper](https://github.com/TryGhost/Ghost/blob/74a6a413ed170ce3cf2fb9ea79902db520f9e58d/core/server/helpers/authors.js#L39_)
  - [x] in [foreach helper](https://github.com/TryGhost/Ghost/blob/74a6a413ed170ce3cf2fb9ea79902db520f9e58d/core/server/helpers/foreach.js)
  - [x] in [keywords helper](https://github.com/TryGhost/Ghost/blob/74a6a413ed170ce3cf2fb9ea79902db520f9e58d/core/server/data/meta/keywords.js)
- [x] Use [slugify lib](https://github.com/TryGhost/Ghost-SDK/blob/master/packages/string/lib/slugify.js)
  - [x] in [model](https://github.com/TryGhost/Ghost/blob/master/core/server/models/base/index.js#L1087-L1098)
- [x] Update `countWords`, `countImages` helper in Ghost, Ghost-Admin
- [x] Update `readingTime` helper in Ghost
  - [ ] Update `readingTime` helper in Ghost Admin to take `wordPerMinute` param
- [ ] Update `readingTime` helper in Ghost Admin
- [x] Extract social-urls from [social/urls](https://github.com/TryGhost/Ghost/blob/2.23.3/core/server/lib/social/urls.js ) (@gargol)

**Comment by ErisDS** [comment]
countWords should also be cleaned up - it's used in Ghost, Ghost-Admin and Ghost-SDK as part of the reading time helper.

**Comment by gargol** [comment]
@rishabhgrg can you please update the check list on what's done and what's left to close this issue out :wink:

**Comment by ErisDS** [comment]
Closing in favour of having specific tasks when we need them
