### ISSUE TITLE
Use JSON Schema validations from SDK 

### ISSUE THREAD

**Issue by naz** [TryGhost/Ghost#10628]
### Summary
JSON Schema used for validation has been extracted into [SDK](https://github.com/TryGhost/Ghost-SDK/pull/69) and Ghost needs to take advantage of this.

### Implementation notes
When migrating to use `@tryghost/admin-api-schema` in the validation layer, the error handling needs extra work as the library no longer returns a promise rejection with `Ignition.ValidationError`, but rather information about validation. Error handling has to be done on Ghost's side.

**Comment by gargol** [comment]
Not stale
