### ISSUE TITLE
Admin api create post. Author property ignored

### ISSUE THREAD

**Issue by cajoy** [TryGhost/Ghost#10625]
### Issue Summary

I am trying to create blog post via admin api and assign it to particular author. But it has been ignored and it always equal to 1 (admin user)

### To Reproduce

```
api.posts.add({
   title: 'My first API post',
   author_id: 2
});
```

### Technical details:

* Ghost Version: latest

**Comment by gargol** [comment]
Hi @cajoy :wave: The author in Admin API is assigned through this syntax: 
```
api.posts.add({
  title: 'My API post`,
  authors: [{"id": "5c739b7c8a59a6c8ddc164a1"}, {"id": "5c739b7c8a59a6c8ddc167d9"}] 
});
```
Please have a look for more in [our docs](https://docs.ghost.org/api/admin/#tags-and-authors). Cheers! :wink:

**Comment by cajoy** [comment]
Thanks, 

Documentation was not absolutely clear about it.

I see I can create post with HTML and it will be converted to mobiledoc

Is there any way I can create post with Markdown and it will be converted to proper markdown mobiledoc?

**Comment by gargol** [comment]
At the moment Admin API only supports HTML and mobiledoc inputs. You'd need to use [markdown card](https://docs.ghost.org/api/migration/#converting-markdown) inside of mobiledoc to be able to use markdown content.
