### ISSUE TITLE
Research: Look into retrieving casperjs screenshots from travis

### ISSUE THREAD

**Issue by gotdibbs** [TryGhost/Ghost#1063]
I happened upon this article on [Sharing Travis CI  Generated Files](http://sleepycoders.blogspot.com/2013/03/sharing-travis-ci-generated-files.html) and realized that we could probably do something similar with the screenshots from casperjs test failures. I think this would help immensely with troubleshooting failures that appear to be specific to travis. I'm not sure if we would actually want to post to GitHub or some other server/service, but I definitely think this warrants further thought.

**Comment by ErisDS** [comment]
We're planning to remove casper.js now as soon as possible, so this won't be necessary.
