### ISSUE TITLE
Custom length for custom_excerpt

### ISSUE THREAD

**Issue by rserentill** [TryGhost/Ghost#10638]
It would be nice if we could change the maxLength of custom_excerpt field without changing the core.
In the DB the limit is 2000 characters for this field, but the schema has a length validation of 300. Instead of a hardcoded value like 300, couldn't we use a value from the configuration file?

**Comment by allouis** [comment]
Hey @rserentill!

This seems more like an idea/feature request that would be better placed on our [forum](https://forum.ghost.org)! 

We use GitHub solely for bug-tracking and on-going feature development.
