### ISSUE TITLE
Custom admin causes the View Site to not render

### ISSUE THREAD

**Issue by itsbhanusharma** [TryGhost/Ghost#10646]
### Issue Summary

Ghost v2.19.1 with custom admin path `admin.example.com` causes the new Admin feature to view site not work correctly. due to cross origin issues

### To Reproduce

On a ghost hosted with custom admin path, logging into admin does not render the default view site tab. 

I followed this guide to setup the custom domain
https://docs.ghost.org/concepts/config/#admin-url
The exact error reported by the <kbd>F12</kbd> is this

```
Load denied by X-Frame-Options: https://example.com/ does not permit cross-origin framing.
```

### Technical details:

* Ghost Version: v2.19.1
* Node Version: v10.15.3
* Browser/OS: Ubuntu 18.04 (Server Side) / Firefox v66.0 on Windows 10
* Database: MySQL

**Comment by kevinansfield** [comment]
@itsbhanusharma this is expected as the "view site" screen works via an iframe and from the error message you've pasted it shows you have an `X-Frame-Options` header set in your proxy config.

You will need to update the header to allow frame requests from your custom admin URL for the "view site" screen to work. If you need any help with that please ask on our [forum](https://forum.ghost.org) 🙂

**Comment by itsbhanusharma** [comment]
Fixed by adding the following to the nginx location block:
`add_header X-Frame-Options "allow-from https://admin.example.com/";`
