### ISSUE TITLE
Post says undefined with MySQL database and Digitalocean storage driver

### ISSUE THREAD

**Issue by nubela** [TryGhost/Ghost#10648]
### Issue Summary

Ghost posts which are saved show "undefined" after you navigate to the page, see: https://accountgram.com/c/what-are-the-best-ocr-apps-for-scanning-receipts/

Draft posts when previewed, shows 404.

All the posts are saved in the (MySQL) database, even draft posts.

### To Reproduce
Cannot reproduce, only on my database AFTER a ghost restart

### Technical details:

* Ghost Version: 

2.19.1

* Node Version:

$ node -v
v10.15.2

* Browser/OS:

Verified on both MacOSX and Ubuntu 14.04

* Database:
MySQL

**Comment by kevinansfield** [comment]
@nubela I'm finding it rather difficult to follow your issue. The URL which you've supplied doesn't show "undefined" and I'm unable to reproduce draft posts showing 404s.

> Cannot reproduce, only on my database AFTER a ghost restart

What exactly do you mean by this? You started seeing problems after a restart, or?

**Comment by nubela** [comment]
Sorry, I have exported the posts into json, deleted and recreatedthe database, and reimported, and fixed the issue.
