### ISSUE TITLE
Wrong Last Modified Date for Post Tag in XML Sitemap

### ISSUE THREAD

**Issue by mskian** [TryGhost/Ghost#10640]
XML Sitemap  Wrong Last Modified Date for Post Tag it shown `1970-01-01 00:00`

check - https://blog.ghost.org/sitemap.xml

![Kazam_screenshot_00000](https://user-images.githubusercontent.com/10300271/55072370-f10ae500-50b0-11e9-91a4-855587bcd238.png)

**Comment by mskian** [comment]
@rishabhgrg After Update it displays the post tag published Date only, not a Post Tag Last Modified date

**Comment by rishabhgrg** [comment]
Hey @mskian, is this on local testing with latest release/version(2.19.4) ? If so, can you please provide some more details - steps, logs or screenshot. :)

**Comment by mskian** [comment]
@rishabhgrg tested on Production version it will display the post tag publish date only 
not updated the Last Modified date

**Comment by mskian** [comment]
See this screenshot post tag date too updated once we updated or publish a blog post
but its not updated display the Published date only

![Kazam_screenshotmsk_00001](https://user-images.githubusercontent.com/10300271/55855968-8ebce480-5b86-11e9-83c4-181bf1994e64.png)

**Comment by rishabhgrg** [comment]
@mskian Which sitemap page is the screenshot for? If its the index page( `/sitemap.xml`), the date for `sitemap-tags` will be last modified date of any tag, and will not be affected by updating or publishing a blog post which does not has a new tag. For the tag date to update, you'll need to edit an existing tag or add a new tag.

**Comment by mskian** [comment]
`sitemap-tags.xml`

Yes I update the existing it's not Updating the Last Modified date

![Kazam_screenshotmsk_00002](https://user-images.githubusercontent.com/10300271/55858237-cc247080-5b8c-11e9-9df9-e897b883b397.png)

**Comment by rishabhgrg** [comment]
@mskian Updating an existing post will not update Last modified dates on `sitemap-tags.xml`, as those are only updated if a tag data is updated from Admin, which you can do at - `/ghost/#/settings/tags`. Updating existing Post will update the Last Modified date for that post in `sitemap-posts.xml`.
