### ISSUE TITLE
Make Update Notifications per-user, rather than per-site

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#10656]
Related to https://github.com/TryGhost/Ghost/issues/9546 and https://github.com/TryGhost/Ghost/issues/9875

Currently, when a dismissible update notification is dismissed, it is dismissed for all users, rather than for the user who has acknowledged the notification. 

Instead, we need to change the system to be per-user, so that the notification is displayed to all users, and dismissed by each user as they see it.

Related to https://github.com/TryGhost/Ghost/issues/9875, we need to make sure that no user sees the notification once it becomes irrelevant (after an upgrade).

TODO:
- [x] introduce per-user notification in Admin API v2
- [ ] refactor notifications logic from Admin API Controller into separate service
- [ ] remove notifications access to Integrations? ([discussion](https://ghost.slack.com/archives/C02G9E68C/p1555513629061200?thread_ts=1555498068.048000&cid=C02G9E68C))

**Comment by gargol** [comment]
Investigated our current notifications implementation and have a couple of observations regarding a possible solution. 

We currently store all of notifications information as one JSON object in `settings` table under `key = notifications`. The current shape of the notification object:
```
{
    "dismissible":true,
    "location":"bottom",
    "status":"alert",
    "id":"5831eae0-5ace-11e9-bfd9-8dae19ff968c",
    "custom":false,
    "createdAt":"2019-04-09T12:49:50.000Z",
    "type":"info",
    "top":false,
    "message":"custom message",
    "seen":false,
    "addedAt":"2019-04-10T02:22:06.316Z"
}
```
To control if the notification should be shown to the user the `seen` flag is used. 

To control per-user the notification dismissal, we could introduce a new field `seenBy` which would contain a list of `ids`  of users that have dismissed (seen) notifications. The notification can be marked as `seen` after all users that could see the notification dismiss it. The main **pro** of this approach is that it would be back compatible with notification logic in API v0.1, so no changes would be needed there. 

### Future considerations
Current notifications logic lives purely in the controller layer and storage as a JSON object might become a maintenance burden if we consider having more regular notifications or have to introduce changes in API v3. The controller logic could be refactored into separate service (to avoid code duplication) and a model with its own table might need to be added (to have more conventional control over notification resources). It hasn't proven to be an issue in [last 4 years](https://github.com/TryGhost/Ghost/issues/5071#issuecomment-132963888) though :smiley:

**Comment by gargol** [comment]
Updated issue description with some extra todo items that think need to be done based on previous [slack discussion](https://ghost.slack.com/archives/C02G9E68C/p1555498094048300?thread_ts=1555498068.048000&cid=C02G9E68C).

**Comment by ErisDS** [comment]
To confirm - the main part of this was done, correct?

**Comment by gargol** [comment]
Yes, correct. The rest were cleanup tasks that never had hands to complete :man_shrugging:
