### ISSUE TITLE
Fix Ember deprecations

### ISSUE THREAD

**Issue by kevinansfield** [TryGhost/Ghost#10651]
We had to silence deprecations in https://github.com/TryGhost/Ghost-Admin/commit/f628e27dbf2a14394c159dc98b30c6461492833e so that Travis builds would complete successfully.

There are two main deprecations that are in our own code rather than addons and are causing a lot of warnings to be generated:

- `ember-views.curly-components.jquery-element`
  - "Using Ember.$() has been deprecated, use `import jQuery from 'jquery';` instead"
  - this is caused by using `this.$()` within components
  - guide: https://deprecations.emberjs.com/v3.x/#toc_jquery-apis
- `application-controller.router-properties`
  - "DEPRECATION: Accessing `currentPath` on `controller:application` is deprecated, use the `currentPath` property on `service:router` instead"
  - no guide but should be a straightforward switch

Deprecations can be re-enabled by modifying the [`config/deprecation-workflow.js`](https://github.com/TryGhost/Ghost-Admin/blob/master/config/deprecation-workflow.js) file. There is a full guide on handling deprecations here https://guides.emberjs.com/release/configuring-ember/handling-deprecations/

**Comment by romgere** [comment]
I try to Fix this issue. Pretty easy to fix in ghostAdmin code, but  a lot of deprecation warning come from modules, especialy from liquid-fire (in version 0.29.5).

All usage of "Ember.$()" was remove in liquid-fire@0.30, can I try to update to this version ?

About the `application-controller.router-properties` deprecations, I have enabled (`handler: 'log'`) deprecation in https://github.com/TryGhost/Ghost-Admin/blob/master/config/deprecation-workflow.js but no deprecation was found... Did I miss somethink ?
