### ISSUE TITLE
Use correct label when publishing new page

### ISSUE THREAD

**Issue by JohnONolan** [TryGhost/Ghost#10658]
This should probably say "page" both in the heading and in the description, when publishing a new page

![image](https://user-images.githubusercontent.com/120485/55551651-a0604100-56db-11e9-92dc-91e286e1a5c3.png)

**Comment by JohnONolan** [comment]
Also after publication

![image](https://user-images.githubusercontent.com/120485/55551741-cd145880-56db-11e9-84b1-f9af25802f5e.png)

**Comment by JohnONolan** [comment]
and in this button

![image](https://user-images.githubusercontent.com/120485/55551783-e4ebdc80-56db-11e9-928f-8928b3de2629.png)

**Comment by vikaspotluri123** [comment]
I'll try to take a look at this Friday 😄
