### ISSUE TITLE
Quote formatting is inconsistent between Markdown and Koenig

### ISSUE THREAD

**Issue by fadeevab** [TryGhost/Ghost#10666]
### Issue Summary

![quote-inconsistency](https://user-images.githubusercontent.com/5967447/55682811-f550c100-5940-11e9-9d25-9b63829db5a2.png)

### To Reproduce

1. Add markdown block and type "> Test".
Resulting HTML:
```html
<blockquote><p>Markdown</p></blockquote>
```
2. Type "> Test" right into Ghost editor.
Resulting HTML:
```html
<blockquote>Not markdown</blockquote>
```

### Technical details:
Ghost Version: Version 2.19.3
Node Version: 8.15.1
Browser/OS: Firefox 66.0.2 (Windows)
Database: MySQL

**Comment by kevinansfield** [comment]
The difference in HTML output with an inner `<p>` vs no inner `<p>` is a known difference between the markdown renderer output and the rich-text renderer output and is not a bug in the editor.

Themes should be prepared to handle the variation as both are valid HTML, if you are using [Casper](https://github.com/TryGhost/Casper) could you open an issue on that repo or report the issue on the respective theme repo or theme developer. Thanks 🙂

**Comment by fadeevab** [comment]
@kevinansfield, Are you really sure that theme developers are aware and properly informed about blockquotes handling? According to current Casper theme which had this big: it's not true.

I think the good result of this issue is a few lines into documentation.

BTW, the link to the "full and extensible documentation" at the https://demo.ghost.io/themes/ article is broken (broken link is https://themes.ghost.org/v2.0.0/docs).
