### ISSUE TITLE
Link for jumping to footnotes not considering floating header bar

### ISSUE THREAD

**Issue by y1zhou** [TryGhost/Ghost#10663]
### Issue Summary
As stated in the title, when clicking on the link to the footnote, the note is masked by the floating header bar.

### To Reproduce
1. Make a footnote.
2. Click on the footnote link.

Also the link for jumping back behaves similarly.

### Technical details:
* Ghost Version: 2.19.3
* Node Version: v8.15.0
* Browser/OS: Chrome 73.0.3683.86, Windows 10 1809
* Database: Ver 8.0.15 for Linux on x86_64 (MySQL Community Server - GPL)

**Comment by kevinansfield** [comment]
@y1zhou are you referring to how visitors see your site or something in the editor? If it's how visitors see your site then this is something to do with your theme rather than Ghost core, in the case of the default Casper theme this is a duplicate of https://github.com/TryGhost/Casper/issues/369

**Comment by y1zhou** [comment]
Yeah I guess it's more of a theming issue. Thanks for your help!
