### ISSUE TITLE
Firefox: selection of the last word in a line doesn't work properly

### ISSUE THREAD

**Issue by fadeevab** [TryGhost/Ghost#10665]
### Issue Summary

Double clicking on the last word in any line of multiline paragraph leads to unexpected behavior.

### To Reproduce

Write a long long line which wraps to 2 lines at least.

Case 1:
1. Double-click just on the last word of the 1st line.
2. Type new characters instead of that word.
3. **Unexpected 1:**
Expected result: old word is substituted with a new chars. **Actual**: chars are types left of the old word.

![OStmgBxlkT](https://user-images.githubusercontent.com/5967447/55734038-8b5f1700-5a27-11e9-93ee-951ca0e0e78d.gif)

Case 2:
1. Double-click far from the last word (shift mouse right of the word, mouse pointer should turn to an arrow - needs to be outside of the editor canvas, beyond the point long lines wrap).
2. Word is selected, popup menu with transformation appears.
3. **Unexpected 2:** Type new characters: **nothing happens**.
4. **Unexpected 3:** Press Backspace: browser goes back in the history to the previous page.

![VXS0FApj2m](https://user-images.githubusercontent.com/5967447/55734361-15a77b00-5a28-11e9-983e-e5d7a28af8b0.gif)

### Technical details:

* Ghost Version: Version 2.19.3
* Node Version: 8.15.1
* Browser/OS: Firefox 66.0.2 (Windows)
* Database: MySQL

**Comment by fadeevab** [comment]
Case 3:
1. Double-click on the head which contain only 1 word.
2. Type a new word.
3. **Unexpected 4:** A new word appears in the latest block of entire post.

**Comment by lori21bishop** [comment]
My


On Apr 6, 2019 9:48 AM, "Alexandr Fadeev" <notifications@github.com> wrote:

Case 3:

   1. Double-click on the head which contain only 1 word.
   2. Type a new word.
   3. *Unexpected 4:* A new word appears in the latest block of entire post.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/TryGhost/Ghost/issues/10665#issuecomment-480509916>,
or mute
the thread

**Comment by gargol** [comment]
Hi @fadeevab ! Was able to reproduce strange behavior of case 3 you and @lori21bishop described only in FireFox (v66.0.2) running on Ubuntu 18.04. The rest of the cases (1 and 2) might be Windows specific, as I couldn't reproduce them. Would be great if you could provide very short recordings for case 1 and 2, to make sure we have an exact way to reproduce.Thanks for reports :+1:

**Comment by fadeevab** [comment]
![Te2aqqv3JG](https://user-images.githubusercontent.com/5967447/55719712-8c804c00-5a07-11e9-8991-c44f340158fe.gif)

I found 2 bugs there: all text is removed in no block before "word", and text is appended if any block above the "word" exists

**Comment by fadeevab** [comment]
I added screen records into the original post.

**Comment by kevinansfield** [comment]
@fadeevab are you using line breaks (<kbd>Shift+Enter</kbd>) in your cases 1 and 2? The width of the line seems far too short for the amount of space you have to the right of it for a normal paragraph.

**Comment by fadeevab** [comment]
@kevinansfield, Yes, in my test I'm using `Ctrl+Enter`, but I was able to reproduce with a automatically wrapped line.

**Comment by lori21bishop** [comment]
(#10665) explain
