### ISSUE TITLE
Editor: changes are lost during auto-saving

### ISSUE THREAD

**Issue by fadeevab** [TryGhost/Ghost#10661]
### Issue Summary

Annoying user experience while editing the post.
1. Text is lost during automatic saving and focus is being lost.
2. New Markdown/Image/HTML block is not being inserted if the inserting coincides with  
saving: new block is inserted for a moment and then automatically removed (it looks like a blink).

### To Reproduce

1. You type a new post and BOOM! - the focus is lost and a final words of your text is lost, and you're typing into the emptiness.
2. You add the new Markdown block and BOOM! - the block is automatically removed in a second. After that you can try to add a new block again.

### Technical details:
* Ghost Version: Ghost 2.19.2 
* Node Version: 8.15.1
* Browser/OS: Firefox 66.0.2
* Database: MySQL

**Comment by fadeevab** [comment]
Here is no any errors in web console.

**Comment by fadeevab** [comment]
The most annoying thing is that when the focus lost, and you haven't noticed, you press "Backspace" while editing the text, and you go back in the browser history, out of the current page.

**Comment by kevinansfield** [comment]
@fadeevab are you sure you are on Ghost 2.19.2? You can go to https://yoursite.com/ghost/#/about to see the version. This bug sounds similar to an issue that was present in Ghost 2.18.2-2.19.0.

If you are definitely on 2.19.2 can you please try using the admin in an Incognito window or a different browser to rule out interference by extensions.

**Comment by fadeevab** [comment]
@kevinansfield,
Yes, I just updated a Ghost yesterday, and I wrote down the version from the Ghost admin > About menu.

I will try from incognito mode and tell you feedback.

**Comment by fadeevab** [comment]
Seems like my bad: incomplete update and a confused Ghost version. I was sure I'd updated a Ghost (but I stuck on point of updating ghost-cli) and I looked at the "Here is a new version" field instead.

Sorry for disturbing.

**Comment by kevinansfield** [comment]
No worries, glad it's working now! 👍
