### ISSUE TITLE
Current styling is lost when markdown expansions are completed

### ISSUE THREAD

**Issue by kevinansfield** [TryGhost/Ghost#10677]
### Issue Summary

Whilst typing styled text, if you use any markdown expansions the existing styling is lost as soon as the expansion is completed.

### To Reproduce

1. Press <kbd>Cmd+B</kbd> and start typing
2. Whilst typing in bold, use a markdown expansion `_test text_` to insert some italicised text
3. Note that "test text" has lost the bold formatting and if you continue typing the bold formatting is not continued there either

![text-formatting](https://user-images.githubusercontent.com/415/55912453-9d34eb80-5bda-11e9-9a1b-e2760cdb040f.gif)

### Technical details:

* Ghost Version: 2.19.4
* Browser/OS: Chrome/macOS

**Comment by fadeevab** [comment]
The same in Firefox/Windows
