### ISSUE TITLE
Scheduled Posts never publish

### ISSUE THREAD

**Issue by r3wt** [TryGhost/Ghost#10674]
### Issue Summary

<img width="754" alt="Screen Shot 2019-04-09 at 11 24 31" src="https://user-images.githubusercontent.com/4483325/55824265-28be5780-5ac9-11e9-8133-921879d46f96.png">

Our content editor has scheduled posts for April 1st and April 5th, and neither one were published, and are still sitting in the scheduled queue.

The only modification i have done to ghost is to inject a script that will redirect frontend ghost url's to our external webapp for viewing the blog. all admin and api routes still accessible,nginx config is not changed.

### To Reproduce

1. Setup ghost
2. Schedule post
3. wait for the scheduled date to pass
4. observe the scheduled post did not publish.

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead? 

**It's obviously a bug when an advertised feature does not work as expected**

### Technical details:

* Ghost Version: 2.14.0
* Node Version: 10.15.3
* Browser/OS: Ubuntu 18.04.2
* Database: MariaDB 10.1.38

**Comment by gargol** [comment]
Hi @r3wt if this is an exact problem observed in https://github.com/TryGhost/Ghost/issues/8485, would recommend adding the details about your case there. Closing this issue as a duplicate :upside_down_face: 

If you could please provide in the original issue answers to these questions: https://github.com/TryGhost/Ghost/issues/8485#issuecomment-303797404 and  https://github.com/TryGhost/Ghost/issues/8485#issuecomment-304062693 
Thanks!

**Comment by r3wt** [comment]
@gargol the original issue was never solved, that's why i opened a new issue. very frustrating that you would close my issue without even investigating the other thread first. please reopen my issue and give it the proper respect it deserves.

**Comment by gargol** [comment]
@r3wt no disrespect meant here. Just trying to keep things grouped up as they belong together. Would rather reopen original issue with updated information so that whole context is kept in one place. Cheers!
