### ISSUE TITLE
UpdateCollisionError when calling `api.posts.edit`

### ISSUE THREAD

**Issue by nendonerd** [TryGhost/Ghost#10691]
### Issue Summary

409: UpdateCollisionError when calling `api.posts.edit`

### To Reproduce

1. When I'm using the Admin-API nodejs package, calling `api.posts.edit({id: xxxxx, updated_at: new Date().toISOString()}) ` will always result in error 409: `UpdateCollisionError: Saving failed! Someone else is editing this post` I have clear both browser and cloudflare cache, and have disabled cdn cache for `/ghost/*` route.

2. I followed the stack trace and found [core/server/models/plugins/collision.js:60](https://github.com/TryGhost/Ghost/blob/ab3b0d95a2f6f113b8fc630e453cf404356c4146/core/server/models/plugins/collision.js#L60) is causing the problem. Because `(clientUpdatedAt.diff(serverUpdatedAt) !== 0) ` will always be true and throw the error

3. client's updated_at is definitely different than server's updated_at due to network latency. So am I calling `api.posts.edit({id: xxxxx, updated_at: new Date().toISOString()})` wrong? What should be the value of `updated_at`? I couldn't find any examples about it.

### Technical details:

<details>
* Ghost Version: 2.18.0<br>
* Node Version: 8.15.1<br>
* Browser/OS: Client: Chrome73/MacOS; Server: ghost:alpine/Docker18.09.3/Debian9<br>
* Database: Sqlite<br>
<br>
* Stack Trace:<br>
<code>
UpdateCollisionError: Saving failed! Someone else is editing this post. at UpdateCollisionError.GhostError (/var/lib/ghost/versions/2.18.3/core/server/lib/common/errors.js:10:26) at new UpdateCollisionError (/var/lib/ghost/versions/2.18.3/core/server/lib/common/errors.js:53:20) at originalUpdateSync.apply.then (/var/lib/ghost/versions/2.18.3/core/server/models/plugins/collision.js:62:55) at tryCatcher (/var/lib/ghost/versions/2.18.3/node_modules/bluebird/js/release/util.js:16:23) at Promise._settlePromiseFromHandler (/var/lib/ghost/versions/2.18.3/node_modules/bluebird/js/release/promise.js:512:31) at Promise._settlePromise (/var/lib/ghost/versions/2.18.3/node_modules/bluebird/js/release/promise.js:569:18) at Promise._settlePromise0 (/var/lib/ghost/versions/2.18.3/node_modules/bluebird/js/release/promise.js:614:10) at Promise._settlePromises (/var/lib/ghost/versions/2.18.3/node_modules/bluebird/js/release/promise.js:694:18) at _drainQueueStep (/var/lib/ghost/versions/2.18.3/node_modules/bluebird/js/release/async.js:138:12) at _drainQueue (/var/lib/ghost/versions/2.18.3/node_modules/bluebird/js/release/async.js:131:9) at Async._drainQueues (/var/lib/ghost/versions/2.18.3/node_modules/bluebird/js/release/async.js:147:5) at Immediate.Async.drainQueues (/var/lib/ghost/versions/2.18.3/node_modules/bluebird/js/release/async.js:17:14) at runCallback (timers.js:810:20) at tryOnImmediate (timers.js:768:5) at processImmediate [as _immediateCallback] (timers.js:745:5)
</code>
</details>

**Comment by kevinansfield** [comment]
For PUT requests the `updated_at` value you send to the API needs to be the same value that is stored on the server, that's how the collision detection works.

Simplified example of collision detection considering `updated_at` is an incremental integer, showing the value that is stored in the server at each stage.

Client A fetches post, `updated_at: 1`
Client B fetches post, `updated_at: 1`
Client B updates post, sends `updated_at: 1`, server is now `updated_at: 2`
Client A updates post, sends `updated_at: 1`, server is `updated_at: 2`, throws a collision error

If you need support using the API please post on [our forum](https://forum.ghost.org) rather than opening bug reports, thank you!.

**Comment by nendonerd** [comment]
> For PUT requests the `updated_at` value you send to the API needs to be the same value that is stored on the server, that's how the collision detection works.
> 
> Simplified example of collision detection considering `updated_at` is an incremental integer:
> 
> Client A fetches post, `updated_at: 1`
> Client B fetches post, `updated_at: 1`
> Client B updates post, sends `updated_at: 1`, server is now `updated_at: 2`
> Client A updates post, sends `updated_at: 1` but server has `updated_at: 2`, throws a collision error
> 
> If you need support using the API please post on [our forum](https://forum.ghost.org) rather than opening bug reports, thank you!.

Sorry about opening the bug report. I have fix it now. The value of `updated_at` in `api.posts.edit({id:xxx, updated_at: xxx})` should be the post's latest `updated_at`, not `new Date().toISOString`
