### ISSUE TITLE
#get "posts" ignores from parameter

### ISSUE THREAD

**Issue by mheland** [TryGhost/Ghost#10715]
### Issue Summary

When creating a small thumbnail gallery of posts not visible as post-card I use

```
   {{#get "posts" from=10 limit=10 as |minipost|}}
             {{#foreach minipost }}
                 {{> "post-minilist"}}
             {{/foreach}}
  {{/get}}

```
### To Reproduce

1. Create a post-minilist.hbs - displaying a linked 100px thumbnail
2. Add {{#get .... as above in index.hbs in post-feed
3. Test. The posts always start from first post, `from=` is ignored. `limit=` is correctly parsed

Expected result: the list should start from post 10, the nine previous post are already visible.

### Technical details:

* Ghost Version: 2.14.3
* Node Version: 10.15.3
* Browser/OS: Linux/Debian/Xubuntu - Chrome/Firefox
* Database: localhost, development install

**Comment by vikaspotluri123** [comment]
The `from` parameter doesn't exist in the get helper. I think you're looking for the [page](https://docs.ghost.org/api/handlebars-themes/helpers/get/#page) option

**Comment by mheland** [comment]
Indeed, that very much seems to be the case.
 
`#get "posts" page=2 limit=9`

does the trick. I can see why this is a better way. Thx!
`#foreach` has a `from=` this is where I got confused.
