### ISSUE TITLE
canonical_url not added to table posts when upgrading ghost

### ISSUE THREAD

**Issue by th-h** [TryGhost/Ghost#10714]
### Issue Summary

Adding ``canonical_url`` to the ``posts`` table when upgrading seems to fail due to row size constraints on *MariaDB*s *InnoDB* engine.

### To Reproduce

After upgrading ghost (from < 2.17) to 2.21.0, I get 503 errors as reported on [this forum thread](https://forum.ghost.org/t/503-error-after-upgrade-from-2-15-0-to-2-18-1/6270). I'm upgrading ghost manually as documented in https://lab.uberspace.de/guide_ghost.html, like the reporter in that thread for the same reasons, and I get the same error messages, starting with ``Unhandled rejection Error: ER_BAD_FIELD_ERROR: Unknown column 'canonical_url' in 'field list'``, due to the ``canonical_url`` column missing in the ``posts`` table.

After checking the migration script and the schema, it seems the column has to be 2000 chars wide, so I tried to add a ``canonical_url`` field of ``VARCHAR(2000)`` to my ``posts`` table on MariaDB 10.3.14 manually.  This fails with

    ERROR 1118 (42000): Row size too large. The maximum row size for the used table type, not counting BLOBs, is 65535. This includes storage overhead, check the manual. You have to change some columns to TEXT or BLOBs.

Using a type of ``VARCHAR(20)`` works. Using a type of ``TEXT`` works, too.

I think the migration script failed to add the ``canonical_url`` field to the database table due to those row size constraints. (?)

### Technical details:

* Ghost Version: 2.21.0
* Node Version: 8.13.0
* Database: MariaDB 10.3.14

**Comment by kevinansfield** [comment]
@th-h manually adding the `canonical_url` column as a `VARCHAR(2000)` won't work, the column should be of type `TEXT`.
