### ISSUE TITLE
images flipped 180 degrees

### ISSUE THREAD

**Issue by chovy** [TryGhost/Ghost#10724]
I just started using the ghost:alpine2 docker image and it works fine except when I add animage to a post it is rotated 180 degrees in the preview from when you actually publish it. So I have to add my images upside down in order for them to be right side up in the production post.

**Comment by allouis** [comment]
Hey @chovy I can't replicate this on my local Ghost install, does this only happen for you inside the ghost:alpine2 docker image?

**Comment by jedidja** [comment]
I experienced something similar: adding images to a gallery showed them rotated in preview mode, but after publishing the post, they appeared properly.

**Comment by gargol** [comment]
@jedidja would you mind providing a sample of the image that was flipped?

**Comment by jedidja** [comment]
![IMG_2388](https://user-images.githubusercontent.com/484442/58491288-b965fb00-813c-11e9-9c64-a68a3d5f70b5.JPG)

Sorry for the delay @gargol  ... what's weird is that when I first drag it into the editor, it's rotated, but after saving the post and editing afterwards, it appears the correct way.

**Comment by jedidja** [comment]
Also - Github is displaying it rotated, but the preview in Finder shows it as normal and you can see that the resolution means it should be vertical (3024x4032)

![image](https://user-images.githubusercontent.com/484442/58491494-1366c080-813d-11e9-9f05-f67779194e99.png)

**Comment by gargol** [comment]
@jedidja thanks for the image. Have been able to replicate it on the local environment as well. Also confirming the image itself is displayed correctly when it's published with a post. Additionally, it is displayed correctly when you re-enter the post editor/refresh the editor page. So, it's only the initial image preview after uploading that is broken.

**Comment by kevinansfield** [comment]
The image shown as a preview whilst uploading and once initially uploaded is how the browser itself handles the raw image file. There's not much we can do about that other than not showing image previews whilst uploading but that makes the experience worse for the vast majority of images which don't have odd exif rotation data.

**Comment by gargol** [comment]
@kevinansfield think the main issue is the confusion that is left after the image is uploaded and stays in the flipped state in the editor. Think reloading showed image with uploaded one would solve this?

**Comment by kevinansfield** [comment]
@gargol we can but it produces a lot of UI jank with images disappearing/re-appearing, this was especially noticeable with the gallery card. It would need deeper investigation to resolve it fully I think and so far we've had very few complaints (the rotation based on exif can be browser dependent, @jedidja I'd be interested to hear which browser you are using).

This issue also appears to have been split now? The wrong rotation during upload problem is not the same as the symptoms of the original issue.

**Comment by gargol** [comment]
@kevinansfield understood. 

For future reference, was able to reproduce this incorrectly flipped behavior after initial upload on Chrome 74 running Ubuntu 18.04.

> This issue also appears to have been split now? 

It's unclear what if the original issue was something else :thinking: @chovy would be great if you could provide more information about your scenario with some examples

**Comment by jedidja** [comment]
> @gargol we can but it produces a lot of UI jank with images disappearing/re-appearing, this was especially noticeable with the gallery card. It would need deeper investigation to resolve it fully I think and so far we've had very few complaints (the rotation based on exif can be browser dependent, @jedidja I'd be interested to hear which browser you are using).
> 
> This issue also appears to have been split now? The wrong rotation during upload problem is not the same as the symptoms of the original issue.

@kevinansfield Chrome on macOS (whatever was the released version a couple weeks ago). That's unfortunate it's a browser issue :( Maybe there's a place to subtly warn users this might happen?

@gargol Agree that the only problem only exists with initial upload, and after that it's fine.
