### ISSUE TITLE
Images in {{amp_content}} not showing

### ISSUE THREAD

**Issue by schliflo** [TryGhost/Ghost#10720]
### Issue Summary

AMP versions of posts do not contain images

### To Reproduce

1. Setup clean ghost instance `docker run -d --name some-ghost -e server__port=3001 -e url=http://localhost:3001 -p 3001:3001 ghost` (I used docker, but the same issue occurs locally)
2. Create sample post with an image in content
3. Go to the AMP version of the post ( add `/amp/` to post URL)
4. Image in content is missing while the non-AMP version shows it just fine

![Screenshot 2019-04-25 at 18 12 45](https://user-images.githubusercontent.com/9881672/57010180-a1619100-6bfb-11e9-8446-798182d5b7dc.jpg)

I've tried reporting this trough [the forums](https://forum.ghost.org/t/amp-images-in-content-seem-to-be-broken/7012), but this wasn't too helpful...

### Technical details:

* Ghost Version: 2.21.1
* Node Version: docker image // locally v10.15.3
* Browser/OS: Chrome 74.0.3729.108 / MacOS 10.14.4 (18E226)
* Database: SQLite

**Comment by gargol** [comment]
Hi @schliflo :wave: Let's keep the discussion to the forum for now, as this is not a clear case to open an issue in Ghost's core repository :+1:
