### ISSUE TITLE
Windows Local Install 2.21.1

### ISSUE THREAD

**Issue by irensaltali** [TryGhost/Ghost#10732]
### Issue Summary
`ghost install local` fails on Windows.

### Terminal Output

```
 ..\Ghost> ghost install local
√ Checking system Node.js version
√ Checking current folder permissions
√ Checking memory availability
√ Checking for latest Ghost version
√ Setting up install directory
× Downloading and installing Ghost v2.21.1
A ProcessError occurred.

Message: Command failed: yarn install --no-emoji --no-progress
warning ghost@2.21.1: The engine "cli" appears to be invalid.
'cp' is not recognized as an internal or external command,
operable program or batch file.
error Command failed with exit code 1.

yarn install v1.15.2
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
[4/5] Linking dependencies...
[5/5] Building fresh packages...
$ cp node_modules/@tryghost/members-theme-bindings/build/members-theme-bindings.js core/server/public/
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

Exit code: 1


Debug Information:
    OS: Microsoft Windows, v10.0.17134
    Node Version: v10.15.3
    Ghost-CLI Version: 1.10.0
    Environment: development
    Command: 'ghost install local'

Additional log info available in: C:\Users\isaltali\.ghost\logs\ghost-cli-debug-2019-05-06T10_30_18_558Z.log

Try running ghost doctor to check your system for known issues.

You can always refer to https://docs.ghost.org/api/ghost-cli/ for troubleshooting.
```

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

### Log File
Debug Information:
    OS: Microsoft Windows, v10.0.17134
    Node Version: v10.15.3
    Ghost-CLI Version: 1.10.0
    Environment: development
    Command: 'ghost install local'
Message: Command failed: yarn install --no-emoji --no-progress
warning ghost@2.21.1: The engine "cli" appears to be invalid.
'cp' is not recognized as an internal or external command,
operable program or batch file.
error Command failed with exit code 1.

yarn install v1.15.2
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
[4/5] Linking dependencies...
[5/5] Building fresh packages...
$ cp node_modules/@tryghost/members-theme-bindings/build/members-theme-bindings.js core/server/public/
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

Exit code: 1

--------------- stdout ---------------
yarn install v1.15.2
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
[4/5] Linking dependencies...
[5/5] Building fresh packages...
$ cp node_modules/@tryghost/members-theme-bindings/build/members-theme-bindings.js core/server/public/
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

--------------- stderr ---------------
warning ghost@2.21.1: The engine "cli" appears to be invalid.
'cp' is not recognized as an internal or external command,
operable program or batch file.
error Command failed with exit code 1.

### Soluton That I Used
I installed version 2.21.0
`ghost install 2.21.0 --local`
It worked.

**Comment by allouis** [comment]
This has been fixed here: https://github.com/TryGhost/Ghost/pull/10722 and will be included in the 2.22.0 release tomorrow :relaxed:
