### ISSUE TITLE
Headers shouldn't be configured in API controllers

### ISSUE THREAD

**Issue by kirrg001** [TryGhost/Ghost#10734]
Each API controller can currently set options to set headers.

e.g.

```
posts: {
  edit: {
    headers: {
       cacheInvalidate: true
    }
  }
}
```

**Problem**:
- API controllers are either used via HTTP or as a function call for internal purposes
- internal access has no concept of HTTP headers 
- API controllers are coupled with HTTP knowledge

**Challenges**:

- Setting headers can be conditional e.g. a post has changed from draft to published
- We need access to the full model, which we get automatically, because API controllers have to return models and not plain JSON, because stages which are executed after controller execution might need access to the full model e.g. output formatting, headers etc..

**Possible implementation 1**:

Remove header implementation from API controllers and make it possible to register custom stages.

HTTP should be able to register a new custom stage called "headers" as part of the pipeline.

1. input validation
2. input serialisation
3. ctrl execution
4. headers
5. output serialisation

The custom header stage needs to live inside each API version and needs to implement each API resource, which needs to set headers e.g. posts, pages etc (very similar to how validators or serialisers work).

**Possible implementation 2**:

Remove header implementation from API controllers and attach original models to the frame as part of the output serializer stage (e.g. `frame.models = models`). The frame gets modified by reference, that means the HTTP wrapper is able to access `frame.models` after the pipeline execution. Each header implementation needs to be moved from controller to its own file as part of the target API version (e.g. headers/posts.js). I think this approach is more hacky but easier!

**Comment by badrimurali** [comment]
Can I work on this issue?

**Comment by allouis** [comment]
@badrimurali Sure, I would start by taking a look at the API layer in Ghost, and then posting an update here on a proposed solution/approach (either one of the ones mentioned above, or you're own) - that way the core team can collaborate and you don't work on something that isn't in the right direction w/ the rest of Ghost :relaxed:

**Comment by badrimurali** [comment]
Sure. Thanks.
