### ISSUE TITLE
Clean up model layer after we've dropped v0.1

### ISSUE THREAD

**Issue by kirrg001** [TryGhost/Ghost#10737]
The goal is to remove and move as much as possible code from model layer. Code which **either belongs to the API layer**, code which was already deprecated in v2 or code which was only added for v0.1

**Examples**
- `toJSON` contains API specific logic ([see](https://github.com/TryGhost/Ghost/blob/2.21.1/core/server/models/user.js#L223)). Go over all `toJSON` implementations. Only keep generic handling e.g. security features like removing the password from a user or inbuilt features like mobiledoc revisions.
- Go over the support of `data.status` for browse/fetch ([see](https://github.com/TryGhost/Ghost/blob/2.21.1/core/server/models/user.js#L302), [see](https://github.com/TryGhost/Ghost/blob/2.21.1/core/server/models/post.js#L610)) and consider dropping the support completely. We should use "filter" instead. Look around where it's still used.
  - Remove `extraFilters`
- [We no longer need to support integrations for v0.1.](https://github.com/TryGhost/Ghost/blob/2.21.1/core/server/models/base/index.js#L563)
- Drop single author support completely (Go over [authors relation](https://github.com/TryGhost/Ghost/blob/2.21.1/core/server/models/relations/authors.js) and look for other places).
- Reduce usage of `options.context`. This couples authentication with the model layer. Probably worth raising a complete own issue out of this problem.
  - Reconsider enforced and default filters. The API v2 input serializer layer already forces filter behaviour e.g. `page=true`. This will reduce the usage of `options.context` and it gives a single responsibility who forces filters. 

**Look for more places** and complete the list.

**Comment by goku321** [comment]
Is it open to be taken?

**Comment by gargol** [comment]
@goku321 we are still actively supporting v0.1, this issue is for after we ship Ghost v3 :)
