### ISSUE TITLE
Theme Casper needs **Active** maintainers

### ISSUE THREAD

**Issue by 0xsuid** [TryGhost/Ghost#10749]
It's been **5 days** and no one seems to take care of PRs, where are **maintainers/owner** ??

**Comment by kevinansfield** [comment]
You won't get anywhere opening issues like that. Please read https://ghost.org/conduct/

**Comment by 0xsuid** [comment]
I won't go anywhere but where did maintainer gone? @kevinansfield

**Comment by allouis** [comment]
Did you read the "Don't be a dick" section of the code of conduct linked above? Feel free to ping on a PR, but making demands on a brand new issue in a separate repo isn't acceptable.
