### ISSUE TITLE
MaxListenersExceededWarning when uploading JSON

### ISSUE THREAD

**Issue by orkun1675** [TryGhost/Ghost#10748]
I see this in my docker container logs when I upload a JSON data via the admin panel. Using Ubuntu Xenial LTS. No idea exactly where it is coming from. Let me know if I can help further by providing any other data. Doesn't seem to break anything, looks harmless.

https://pastebin.com/jDyPEagH

**Comment by rishabhgrg** [comment]
👋 Hey @orkun1675, thanks for reporting, can you please also share which node version and ghost version your setup is using? Thanks.

**Comment by orkun1675** [comment]
I am running Ghost inside Docker.

"NODE_VERSION=10.15.3",
"YARN_VERSION=1.13.0",
"NODE_ENV=production",
"GHOST_CLI_VERSION=1.10.0",
"GHOST_VERSION=2.22.0"

**Comment by rishabhgrg** [comment]
@orkun1675 We have an investigation planned for `MaxListenersExceededWarning` internally, closing this issue in its favor, thanks for reporting 😄
