### ISSUE TITLE
404 on blog post

### ISSUE THREAD

**Issue by smorele** [TryGhost/Ghost#10747]
Hi,
I'm having an issue with this configuration:
```
Debug Information:
    OS: Mac OS X, v10.14.4
    Node Version: v10.15.2
    Ghost-CLI Version: 1.9.9
    Environment: production

```
After publishing mypost, I can find it in blog post list but when trying to access it, it returns a 404.
From the frontend, in the blog posts list, the url is: `http://localhost:2368/p/f3e44130-b8cb-45fa-b90d-0d4e38e7515f/` instead of `http://localhost:2368/test-de-post`

Any idea ?

**Comment by smorele** [comment]
I do not need support, it appears to be a bug

**Comment by gargol** [comment]
@smorele this is a very basic post publishing case that is definitely covered by lots of tests. This is why I'm rather leaning towards exploring what could be going wrong on the forum first, and filing an issue here once it is a very clear, reproducible bug
