### ISSUE TITLE
Creation of first user via Ghost cli or API

### ISSUE THREAD

**Issue by hdegorce** [TryGhost/Ghost#10745]
Hello,

With source install, once we created the blog, Ghost is running but we don't have an admin user. I didn't find how to created it via command line (equivalent of https://$URL/ghost/#/setup/two). Is there a way to do it ? And if not is it planned?

**Comment by brownemint** [comment]
@hdegorce Did you manage to sort this out? I'm running into a similar problem where I can't create a first user after installation via ghost-cli
