### ISSUE TITLE
Non-breaking space dosn't work in Editor, also no highlighting

### ISSUE THREAD

**Issue by b166ar** [TryGhost/Ghost#10757]
### Issue Summary

Non-breaking spaces work great in markdown blocs. But it doesn't work with usual text blocs. Now I have to compose my posts with many markdown blocs...

Please, make it work. 

### Technical details:
* Ghost Pro user:
* Browser/OS: Safari, macOS 10.14.5

**Comment by kevinansfield** [comment]
Non-breaking spaces are entered using the default system key commands for typing non-breaking spaces (<kbd>Shift+Space</kbd> on Mac or <kbd>Crtl+Shift+Windows</kbd>). What exactly isn't working? When opening bugs always include as much information as possible, what are you trying, what are you expecting to see, what are you seeing instead, and so on, screenshots are really useful too.

> also no highlighting

I have no idea what this is referring to, if you need help or are requesting a feature please [use the forum](https://forum.ghost.org) as mentioned in the issue template.

**Comment by b166ar** [comment]
> Non-breaking spaces are entered using the default system key commands for typing non-breaking spaces (Shift+Space on Mac or Crtl+Shift+Space on Windows). 

Actually it is `Alt+Space` on Mac. 

> What exactly isn't working?

I will show you in the pictures.

Here are two blocks of text with Non-breaking spaces: usual text and markdown block.
![1](https://user-images.githubusercontent.com/44132159/58253644-940a7300-7d71-11e9-92c4-2bf6741b17ba.png)

And here the result after posting:
![2](https://user-images.githubusercontent.com/44132159/58253657-9967bd80-7d71-11e9-94ae-7740994f0bf0.png)

**Comment by b166ar** [comment]
> Actually it is Alt+Space on Mac.

Probably it depends on the keyboard layout. Anyway, it is Alt+ Shift for me.

**Comment by gargol** [comment]
@kevinansfield seems like a bug with enough information to reproduce?

**Comment by kevinansfield** [comment]
Yeah, sorry, I forgot to update the issue. The problem is that mobiledoc-kit is rendering a space and an nbsp so there are still points where breaks can occur. I need to investigate a bit more, it may be that this issue is moved upstream.

**Comment by xDEADC0DE** [comment]
Was this solved? I have the same issue ; ctrl+shift+space (on Windows) does nothing, neither does pasting a non-breaking space copied from a web page or a word processor.

**Comment by xDEADC0DE** [comment]
I copied a non-breaking space + a semi colon, and only the semi colon got pasted into the editor.
