### ISSUE TITLE
Update knex.js

### ISSUE THREAD

**Issue by kibertoad** [TryGhost/Ghost#10755]
Currently Ghost is two major versions (soon to be three) behind the current latest and greatest of knex. Are there any particular reasons, e. g. known backwards incompatibilities or regressions that resulted in locking knex to an old version?
If anything needs to be done to make update feasible, I would like to volunteer for that effort :)

**Comment by vikaspotluri123** [comment]
I know one of the blockers is bookshelf and its dependencies - the latest release of bookshelf has a peer dep of knex `>=0.6.10 <0.15.0` - knex was initially updated, but reverted in c862110 because of it

**Comment by gargol** [comment]
@kibertoad would be great to bump the version of knex to the latest, but as Vikas pointed out, it would require a bookshelf version release first because it's master is quite ahead of the last release in December :disappointed: and already contains peer dependency of almost latest knex.

**Comment by kibertoad** [comment]
@gargol New bookshelf is out! Created a PR for the upgrade :D
