### ISSUE TITLE
Canonical URLs not working

### ISSUE THREAD

**Issue by themarcba** [TryGhost/Ghost#10769]
### Issue Summary

It seems that setting the canonical url in the meta tags of a post don't change the <link rel="canonical" href="XXX" /> in the rendered page later on. (The post's canonical URL from the own domain stays there)

I'm using a self-hosted version of ghost.

EDIT: If this helps: I checked in the database, and the right value is definitely there. It just doesn't seem to be taken into account on the time of rendering the HTML.

### To Reproduce

1. Create post
2. Change canonical URL in meta tags
3. Publish post
4. In my case, the canonical URL is still set to my own domain.

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

### Technical details:

* Ghost Version: Ghost-CLI version: 1.10.1, Ghost version: 2.23.1
* Node Version: v8.10.0
* Browser/OS: Mac, Chrome 74
* Database: MySQL

**Comment by vikaspotluri123** [comment]
Can you check that your theme is using the v2 API? Canonical URLs are only available if you're using the v2 API

**Comment by themarcba** [comment]
Oooh that was it, thanks! I used a modified version of the Casper theme (to comply with GDPR), but that version apparently didn't use the current API.

Sorry for the bother, it works now 😄
