### ISSUE TITLE
Feedly API error

### ISSUE THREAD

**Issue by ardyfeb** [TryGhost/Ghost#10768]
### Issue Summary

Feedly api error when click subscribe text below subscribe button. Feedly show error
```
{"errorCode":404,"errorId":"ap7int-sv2.2019060115.2262607","errorMessage":"API version not found"}
```
I already search this error, but no one can help me

### To Reproduce

1. Click subscribe text
2. Browser redirect to `https://feedly.com/subscription/feed/https://www.some-domain.com/rss/`
2. Get error

### Technical details:

* Ghost Version: 2.22.2
* Node Version: Latest
* Browser/OS: All browser
* Database: mysql

**Comment by gargol** [comment]
Hi @ardyfeb! It looks like you are redirecting from your local development environment to Feedly (based on `https://www.some-domain.com` address for the redirect you provided). To be able to subscribe to a feed, your blog has to run on a publicly accessible domain. For example, when visiting subscribe link on Ghost's blog - https://blog.ghost.org/author/kevin-ansfield/  it works as expected :+1:

**Comment by ardyfeb** [comment]
> Hi @ardyfeb! It looks like you are redirecting from your local development environment to Feedly (based on `https://www.some-domain.com` address for the redirect you provided). To be able to subscribe to a feed, your blog has to run on a publicly accessible domain. For example, when visiting subscribe link on Ghost's blog - https://blog.ghost.org/author/kevin-ansfield/ it works as expected

That domain is example. My blog currenly running on production / publicy access

**Comment by gargol** [comment]
@ardyfeb could you please provide the link to your blog then :smiley: ? Can't reproduce the error you are having.

**Comment by ardyfeb** [comment]
https://kolabstack.com/menyiapkan-eslint-prettier-airbnb-style-di-vscode/

Subscribe form at the bottom

**Comment by vikaspotluri123** [comment]
@ardyfeb it looks like your theme hasn't been updated to support Feedly's updated url - it should be using

```hbs
https://feedly.com/i/subscription/feed/{{@site.url}}/rss/
```

This was fixed last year in Casper:

https://github.com/TryGhost/Casper/pull/418

**Comment by ardyfeb** [comment]
> @ardyfeb it looks like your theme hasn't been updated to support Feedly's updated url - it should be using
> 
> ```
> https://feedly.com/i/subscription/feed/{{@site.url}}/rss/
> ```
> 
> This was fixed last year in Casper:
> 
> [TryGhost/Casper#418](https://github.com/TryGhost/Casper/pull/418)

Oh, thanks! You are save my day
