### ISSUE TITLE
Turn this post into a page checkbox is missing

### ISSUE THREAD

**Issue by HeikoMueller** [TryGhost/Ghost#10772]
### Issue Summary

"Turn this post into a page" checkbox is missing. I have two static pages in my site data and they are shown correctly under "Pages" in the admin menu. However, I am not able to turn new posts into pages or to disable the page status of the two current pages. The checkbox is not shown, neither for new posts nor for existing ones. 

Not sure: Is this a feature or a bug (Do I have to enable the checkbox globally somewhere?)

### Technical details:

Ghost Version 2.23.1
Environment production
Database mysql
Mail Direct
Browser/OS: Safari, Chrome, Firefox
Node-Version 8.12.0

![Bildschirmfoto 2019-06-03 um 20 38 48](https://user-images.githubusercontent.com/2492274/58825894-b3da4a80-863f-11e9-8036-5dc7224f97d3.png)

**Comment by gargol** [comment]
Hi @HeikoMueller! The short answer is: this a feature :smiley:  

Posts and pages were deliberately separated into more distinct resources when working on [Admin API v2](https://github.com/TryGhost/Ghost/issues/10438) a specific set of changes that removed this checkbox is [here](https://github.com/TryGhost/Ghost-Admin/pull/1101). 

You can still turn a post into a page with a single flag in the database: `posts` table `page` field, in case you really need to do so :wink:

**Comment by HeikoMueller** [comment]
Thank you @gargol for pointing this out ! :)

One little remark: I was a bit confused by the fact that in the sidebar of the admin menu, there is a 'plus' button next to posts, but not to pages. I now see that there is also a green "New page" button on the upper right. Might it be a good idea putting a plus button next to pages in the side panel as well ?

![Bildschirmfoto 2019-06-04 um 10 42 07](https://user-images.githubusercontent.com/2492274/58865108-44537200-86b6-11e9-8cf4-e3dae7cbd0a8.png)

**Comment by kevinansfield** [comment]
>  there is a 'plus' button next to posts, but not to pages

@HeikoMueller this is intentional, the plus button is next to the Posts menu item because it's the most common action. Creating new pages is rare after the initial site setup so an extra button would add noise/clutter to the UI.

**Comment by HeikoMueller** [comment]
@kevinansfield  ...sounds reasonable. thanks for explaining.

**Comment by newschapmj1** [comment]
How do we get the docs updated?  (assuming it has been wrong from 2+ years)

How to convert post to a page

https://ghost.org/docs/publishing/
Inside Ghost-Admin, any post can be turned into a page by checking the relevant box at the bottom of the Post Settings Menu. Equally, within the Content API, a page is just a post with a parameter of "page": true.
