### ISSUE TITLE
Scheduled posts without auto saving

### ISSUE THREAD

**Issue by MaluNoPeleke** [TryGhost/Ghost#10783]
### Issue Summary

With new posts which are not published yet (draft status) changes are saved automatically always. This feature is disabled as soon as you schedule an article for publication. Additionally changes to the main title of that article are not detected by ghost unless you manually click on "Reschedule". I wondered for some time why the preview of a scheduled post does not show the updated title and is also not reminding me about unsaved changes when leaving the article page in editor view.

### To Reproduce

1. Create a new article
2. Write something including title (main headline) and body content
3. Schedule article for later
4. Modify the title
5. Title won't change / be saved unless you click on "Reschedule"

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

### Technical details:

* Ghost Version: 2.23.2
* Node Version: 10
* Browser/OS: Chrome 75 macOS
* Database: MariaDB

**Comment by kevinansfield** [comment]
@MaluNoPeleke you can also hit <kbd>Ctrl/Cmd+S</kbd> to save. A scheduled post is the same as a "published" post in that the content is deemed to be final which is why an explicit save is required rather than the auto-save of drafts.

The behaviour is as expected so it's not a bug. However we are aware of the non-optimal UI of the save/publish post menu and it's on our internal roadmap for a redesign.

**Comment by MaluNoPeleke** [comment]
Thanks for the information and clarification.
Are you aware that changes to the title are currently also not detected in this mode so the browser won't stop you from leaving the page if you modified the title (which it does if you modify the body content)?

**Comment by kevinansfield** [comment]
> Are you aware that changes to the title are currently also not detected in this mode so the browser won't stop you from leaving the page if you modified the title

Strange, I'm not able to replicate that at all. If I change the title on a scheduled post then try to navigate away without saving I get the unsaved changes modal.

**Comment by MaluNoPeleke** [comment]
Yes, you are right, it must have been a one time only issue.
