### ISSUE TITLE
Imports override privacy mode setting

### ISSUE THREAD

**Issue by JohnONolan** [TryGhost/Ghost#10788]
I'm certain this has come up before in the past, but not sure if tracked anywhere useful. Currently, if you import a JSON content file into Ghost, it also imports and overrides your currently active "private site mode" setting.

So what ends up happening is you're working on a new site, privately, and you import content from an old/existing site - and now suddenly your private site is public, without warning. There's actually no way of knowing anything happened at all unless you happen to notice that the setting has changed, or your site starts being indexed in Google.

This is a pretty bad bug.

IMO the site privacy setting should never be changed by any import - it should stay exactly as it has been manually set by the user.

**Comment by allouis** [comment]
Updates to this issue from @kevinansfield and @peterzimon in slack:

```
to confirm changes needed:
1. don't import the private setting
2. show a warning to that effect if the setting in the export file is different to the current site
```

**Comment by allouis** [comment]
Update to this issue: We only want to show the warning if we are importing *from* a private site *into* a _non-private_ site
