### ISSUE TITLE
Editor breaks when switching to Markdown mode

### ISSUE THREAD

**Issue by Charizard** [TryGhost/Ghost#10782]
### Issue Summary

Editor breaks when switching to Markdown mode.

### To Reproduce

In editor while creating a new post, switching to markdown breaks the editor. The following error is thrown:
<img width="1440" alt="Screenshot 2019-06-11 at 4 56 50 AM" src="https://user-images.githubusercontent.com/1897178/59233376-ca673f80-8c05-11e9-9ed0-206d9a7d80ae.png">

### Technical details:

* Ghost Version: 2.23.3
* Node Version: 8.10.0
* Browser/OS: Ubuntu 18.04
* Database: mysql

**Comment by Charizard** [comment]
Noticed that this doesn't happen in development.

Further on debugging the production environment, noticed that before the `lazyLoader` service gets a chance to load simpleMDE, the promise resolved and `SimpleMDE is undefined`.

**Comment by rishabhgrg** [comment]
👋 Hey @Charizard ,  I am unable to reproduce the issue with above information in production. Can you please add detailed reproduction steps for the issue as that will help us narrow it down faster ? :)

**Comment by Charizard** [comment]
@rishabhgrg If it's any help, I used the digital ocean one click droplet to create my ghost instance. But, I can try this once again by tomorrow.

**Comment by rishabhgrg** [comment]
@Charizard Sure, thanks. What's also gonna be useful is if you can elaborate the exact steps on editor which reproduces the issue consistently.

**Comment by Charizard** [comment]
@rishabhgrg It was constantly replicable. Fresh DO Ghost droplet. Finish setup. Create new post. Change to markdown mode. Editor breaks (It just shows a focused input field and nothing can be inputted). Open the console and I see this error.

**Comment by Charizard** [comment]
@rishabhgrg Wait!!! I just now opened up the same ghost instance and it works 😭 Early morning it was happening though. I will keep an eye out for this and close this issue for now. Thanks for the help.
