### ISSUE TITLE
HTML attribute quotes are switched from '->" on published posts

### ISSUE THREAD

**Issue by billyzoellers** [TryGhost/Ghost#10793]
### Issue Summary

Running Ghost 2.23.4/2.5.0 on Ubuntu - the exact HTML I enter into the editor is modified on the frontend page.

### To Reproduce

I entered the following HTML block into the editor - note the single quotes.
![ghost-editor](https://user-images.githubusercontent.com/2947130/59694962-70dbb380-91b7-11e9-9d1d-2a6112047c5d.PNG)

`<span class="text-success" data-toggle="typed" data-options='{"strings": ["item1", "item2"]}'></span>.
`

On the front end, single quotes are reflected as double quotes
![ghost-frontend](https://user-images.githubusercontent.com/2947130/59695099-a7193300-91b7-11e9-9acd-b119411533a3.PNG)

`<span class="text-success" data-toggle="typed" data-options="{"strings": ["item1", "item2"]}"></span>.
`

### Technical details:

* Ghost Version: 2.25.0
* Node Version: 10.16.0
* Browser/OS: Chrome/Firefox on Windows
* Database: MySQL & SQLite (dev)

**Comment by kevinansfield** [comment]
@billyzoellers how are you inspecting the code output? I've just checked this and I can't reproduce. In Chrome's web inspector it _appears_ as though there are double quotes because its inspector automatically changes them because it always uses double quotes for attribute values. However, looking at the raw data in the response from Ghost the single quotes are preserved.

**Comment by billyzoellers** [comment]
@kevinansfield I as looking in view source in Chrome. I see the same issue in view source in Firefox as well.

'data-options' is being parsed by a js script that is throwing an error due to the quotes, so I believe the 'bad' HTML is making it to that js script somehow.

I have confirmed that if I hardcode the HTML onto the .hbs template, things work as expected.

**Comment by kevinansfield** [comment]
Hmm, this is very strange. I can only see the `'`->`"` switch happening when a published post served. After putting the post back to draft without changing the contents, no switch is apparent.

It appears this is not related to the editor at all, the data saved in the HTML card inside mobiledoc is always correct, as is the rendered `html` field. There is something in the rendering layer that is causing the problem 🤔

**Comment by kevinansfield** [comment]
> There is something in the handlebars rendering layer that is causing the problem 🤔

Scratch that, it's in the API layer rather than the handlebars layer. When performing API requests to the v2 Admin/Content APIs for the post in question the quotes are returned incorrectly in the `html` field...

```
➜ curl 'http://ghost.blog/ghost/api/v2/content/posts/5d08fc7b26720fe7f85df7d0/?formats=html&key=95bb077bf727261b118b0c72e8' | jq 
######################################################################## 100.0%
{
  "posts": [
    {
      ...
      "html": "<!--kg-card-begin: html--><span class=\"text-success\" data-toggle=\"typed\" data-options=\"{\"strings\": [\"item1\", \"item2\"]}\"></span><!--kg-card-end: html--><p>Testing</p>",
      ...
```

The key point being `data-options=\"{`.

The data in the database is correct:

```html
<!--kg-card-begin: html--><span class="text-success" data-toggle="typed" data-options='{"strings": ["item1", "item2"]}'></span><!--kg-card-end: html--><p>Testing</p>
```

**Comment by billyzoellers** [comment]
@kevinansfield Interesting! I can confirm that draft mode works for me as well.

**Comment by kevinansfield** [comment]
Adding some extra context, the mangling is much worse if you try to escape the quotes with backslashes...

html card content:
```html
<span class="text-success" data-toggle="typed" data-options="{\"strings\": [\"item1\", \"item2\"]}"></span>.
```

becomes:
```html
<!--kg-card-begin: html--><span class="text-success" data-toggle="typed" data-options="{\" strings\":="" [\"item1\",="" \"item2\"]}"=""></span>.<!--kg-card-end: html-->
```

---

@billyzoellers the core team is unlikely to get to this until at least next Monday but maybe a contributor will get there first 😄 In the meantime you can workaround the issue by using html-escape codes if that's possible (html escaped chars appear the actual char to JS when reading attributes):

```html
<span class="text-success" data-toggle="typed" data-options="{&quot;strings&quot;: [&quot;item1&quot;, &quot;item2&quot]}"></span>.
```

**Comment by kevinansfield** [comment]
This issue is now being tracked in our SDK package repo https://github.com/TryGhost/Ghost-SDK/issues/124

**Comment by kevinansfield** [comment]
This issue was resolved via https://github.com/TryGhost/Ghost/pull/11027
