### ISSUE TITLE
`allowtransparency` in apm-iframe throws amp validation error in Google Search Console 

### ISSUE THREAD

**Issue by pankajpatel** [TryGhost/Ghost#10796]
### Issue Summary

`allowtransparency` in apm-iframe of embed like Codepen throws amp validation error in Google Search Console

### To Reproduce

1. embed a codepen pen in the post
2. publish the post
3. Head to https://search.google.com/search-console/ for respective domain
4. put the newly published post url in the URL Inspect bar
5. Check the amp errors

When I removed the attribute from the iframe by manually editing the database field and then updating the post meta to force-refresh/flush the amp cache; the error was resolved

### Technical details:

* Ghost Version: 2.23.1
* Node Version: v8.16.0
* Browser/OS: Chrome 75
* Database: mysql

**Comment by kevinansfield** [comment]
@pankajpatel this deserves an issue in the upstream [`amperize`](https://github.com/jbhannah/amperize/) project - perhaps it should be removing invalid attributes when converting `<iframe>` tags to `<amp-iframe>`

**Comment by pankajpatel** [comment]
@kevinansfield Makes sense; Though I seem to be wrong in this. The actual issue is with the values of the attribute.

I came across this doc from `ampproject` which shows the expected values for different attributes on `apm-iframe`: https://github.com/ampproject/amphtml/blob/master/extensions/amp-iframe/validator-amp-iframe.protoascii

I checked the upstream project as well and there they don't touch any attribute other than width, layout and height https://github.com/jbhannah/amperize/blob/b9d2a68738fd09bfc08a136ad1a5a6c0b7496a1f/lib/amperize.js#L290

**Comment by kevinansfield** [comment]
> I checked the upstream project as well and there they don't touch any attribute other than width, layout and height

@pankajpatel correct, but the upstream project is still the right place for this to happen as it's what Ghost is using to convert a post's html content to amp content. The html content can be anything (in this case it's the html that Codepen gives us, it's not anything generated by Ghost) and the html-to-amp conversion done by `amperize` should handle that as best it can.

**Comment by kevinansfield** [comment]
This issue is now being tracked upstream in https://github.com/jbhannah/amperize/issues/126
