### ISSUE TITLE
to load automatically new custom cards definitions

### ISSUE THREAD

**Issue by luizamboni** [TryGhost/Ghost#10808]
in
core/server/lib/mobiledoc/cards/index.js

```javascript
const fs = require('fs');

module.exports = fs.readdirSync(__dirname)
    .filter(filename => ['index.js'].indexOf(filename) === -1)
    .map(filename => require(`./${filename}`));
```
- This approach have a blocked call, but only run in first requirement of module. And require already is block (this is not a problema to me)
- this can be extended to load other adicional folder, to get cards defined in costum plugins (a convention must be created)

Thanks for attention ;)

**Comment by kevinansfield** [comment]
@luizamboni custom cards is on our long-term radar but it's much more involved than this outline. If you are making a feature request please use the Ideas category on our forum https://forum.ghost.org/c/Ideas/l/votes

**Comment by luizamboni** [comment]
hey, i really use wrong category... i see but my fingers igore.. :)

Already have any feature or release branch that i can see the project path ?

One more time, thanks for your time.

**Comment by luizamboni** [comment]
And yes, plugins and custom cards involved many other detais, but...

The code above is very simple and not have any impact in actual code and functionality. 

Its aid a developer that need a customized solution, is less a file to be change. 

If the intent is create for example a docker container, all it need is add your custom card file in core/server/lib/mobiledoc/cards/ folder, by volume (not altering the source)

Well, its only my opinion
