### ISSUE TITLE
Post Editor Help Icon Pointing to Wrong URL

### ISSUE THREAD

**Issue by pqpxo** [TryGhost/Ghost#10803]
**Issue Summary**
The small help icon (far bottom right of the screen) in editor (post page) is pointing to https://docs.ghost.org/faq/using-the-editor/ which no longer exists. 

**Steps to Reproduce**
Navigate to any post to edit
Click on help icon (next to word count)
URL opens new window to incorrect URL

Correct URL is https://ghost.org/faq/using-the-editor/

**Comment by amoury** [comment]
I will take this up! Will send a PR shortly
