### ISSUE TITLE
Preview link doesn't work when the page is unpublished

### ISSUE THREAD

**Issue by truekasun** [TryGhost/Ghost#10811]
### Issue Summary

When we create a page from Ghost Admin and before we publish the page, we can use the preview link to see a preview of the page. But when we publish the page and again unpublish the same, then the preview link wont work anymore.

### To Reproduce

1. Create a page from Ghost admin
2. Click publish button of the page
3. Unpublish the page again
4. Click on the Preview Link of the page
5. You get a 404 page with the published URL (not the preview URL)

### Technical details:

* Ghost Version: 2.25.1
* Node Version: v8.15.1
* Browser/OS: Chrome
* Database: MySQL

**Comment by kevinansfield** [comment]
@truekasun I'm unable to reproduce this behaviour. I would suggest checking to make sure that a redirect is not being cached somewhere, maybe also check that you have your url configured as `https://...` if you are accessing your site via https?
