### ISSUE TITLE
Newer(?) TLD rejected from forgot password process

### ISSUE THREAD

**Issue by daetal-us** [TryGhost/Ghost#10812]
### Issue Summary

Newer TLD rejected by forgot password process.

### To Reproduce

1. Create a user with an email at a newer TLD, e.g. `user@example.press`
2. Try to initiate the forgot your password process in the admin login.
3. Address rejected and error reports bad sender syntax.

### Technical details:

* Ghost Version: 2.25.1
* Node Version: v10.16.0
* Browser/OS: MacOS 10.14.5
* Database: sqlite3

**Comment by kevinansfield** [comment]
@daetal-us I'm not able to replicate this, from the description of your error message it sounds like it's possibly a problem at your smtp providers end. Ghost doesn't have any of its own error messages which would output a "bad sender syntax" error so I'm going to close this as an environment issue. If you need further support please use [our forum](https://forum.ghost.org).
