### ISSUE TITLE
Not-saved alert shows when content is saved

### ISSUE THREAD

**Issue by nathfreder** [TryGhost/Ghost#10819]
### Issue Summary
When composing a new post or page, adding an image will cause Ghost to alert you every time you try to go back to the admin interface even if the post has been saved (Command-S).

### To Reproduce

1. Create a new post
2. Add an image to the post
3. Save the post (Command-S)
4. Click "< Posts"

### Technical details:

* Ghost Version: v2.25.1
* Node Version: v8.10.0
* Browser/OS: Firefox 68.0b10 (64-bit)
* Database: MySQL

**Comment by gargol** [comment]
Hey @nathfreder :wave: This bug is a part of the issue described in https://github.com/TryGhost/Ghost/issues/10477 and it has to do to how URL's are stored for different content in Ghost. Closing this issue in favor of the above mentioned.
