### ISSUE TITLE
hi,why not surport node 10.8.x,if so,I am very happy

### ISSUE THREAD

**Issue by cici-admin** [TryGhost/Ghost#10817]
--------------^ Click "Preview" for a nicer view!

We use GitHub only for bug reports 🐛

Anything else should be posted to https://forum.ghost.org 👫.

🚨For support, help & questions use https://forum.ghost.org/c/help
💡For feature requests & ideas you can post and vote on https://forum.ghost.org/c/Ideas

Alternatively, check out these resources below. Thanks! 😁.

- [Forum](https://forum.ghost.org/c/help)
- [Theme Support](https://forum.ghost.org/c/themes)
- [Theme Docs](http://themes.ghost.org/)
- [API Docs](https://api.ghost.org/)
- [Feature Requests / Ideas](https://forum.ghost.org/c/Ideas)
- [Contributing Guide](https://docs.ghost.org/docs/contributing)
- [Self-hoster Docs](https://docs.ghost.org/)

**Comment by allouis** [comment]
We do! https://ghost.org/faq/node-versions/ :male_detective:

**Comment by cici-admin** [comment]
thank
