### ISSUE TITLE
Disabled labs error message is incorrect

### ISSUE THREAD

**Issue by vikaspotluri123** [TryGhost/Ghost#10875]
Situation:
- Trying to use `get` helper
- [probably] have not specified API version in package.json
- Disabled v0.1 Public API in labs

In this situation, html should be output that writes an error to the console. What's happening instead is the function signature (i.e. Function.toString) is the only html that's sent. I'm guessing this might have happened when express-hbs was bumped to v2, but there are plenty of other possible causes. I think the fix is just resolving with the error text rather than a function that returns the error text.

Relevant source:

https://github.com/TryGhost/Ghost/blob/2048ea5cb281ebe31dea7d6c2c8d742b3df43003/core/server/services/labs.js#L43-L51

Originally reported at the [forum](https://forum.ghost.org/t/function-asyncerror-return-errstring-when-attempting-to-retrieve-posts/8152). Ghost version in page source was 2.25.x, running on Ghost (Pro).

Output screenshot (rendered to visitor):

![image](https://user-images.githubusercontent.com/4383564/60760973-c9f37600-a004-11e9-9658-f51b656a07dc.png)

HTML output snippet:

```html
    </section> 
function asyncError() {
            return errString;
        }
  	<section>
```

**Comment by ErisDS** [comment]
I've also seen this issue appear - it's fairly new, last 3 weeks maybe as I was testing this behaviour not long ago and it was working ok.
