### ISSUE TITLE
Running `yarn setup` while installing from source fails on Windows

### ISSUE THREAD

**Issue by itssamuelrowe** [TryGhost/Ghost#10890]
I am trying to setup a development environment to customize Ghost. I'm following the instructions explained [here](https://docs.ghost.org/install/source/).
I'm following the steps and everything seems to be fine until I run `yarn setup`. After installing the required modules and initializing the database, I get this error.

```
$ cpy node_modules/@tryghost/members-theme-bindings/build/members-theme-bindings.js core/server/public/
[2019-07-09 16:44:36] INFO Finished database init!
Running "symlink:githooks" (symlink) task
>> Error: EPERM: operation not permitted, symlink '..\..\.github\hooks\pre-commit' -> '.git/hooks/pre-commit'
Warning: Failed to create symlink: (file) .git/hooks/pre-commit -> ..\..\.github\hooks\pre-commit. Use --force to continue.

Aborted due to warnings.
'true' is not recognized as an internal or external command,
operable program or batch file.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by vikaspotluri123** [comment]
@itssamuelrowe I highly suggest you try to use a VM or something like WSL if your base OS is Windows. While it's possible to get Ghost from source set up on Windows, it can be difficult, and you'll run into multiple issues along the way. The entire development team uses Unix-based systems, so even if you can get it set up now, any future setup changes aren't guaranteed to work on Windows. I personally use WSL, and while it's sometimes a bit slow, there are no issues with functionality.

**Comment by allouis** [comment]
Hey @itssamuelrowe it seems like there are two problems here:

1. Our usage of the `true` command
2. A permissions error on your end

We'd like to try and fix 1. buy replacing the usage of `|| true` with `|| (exit 0)` on line 29 of package.json - would you be able to test that change for us - before we commit it to master?

**Comment by TechGuyTN** [comment]
I had same issue with PowerShell 7 on Windows 10. I changed line 29 as suggested and also ran powershell as admin to resolve issue. 

```
Replace || true with || (exit 0) on line 29 of package.json
Run Powershell as admin
```

**Comment by allouis** [comment]
Cool! Feel free to submit a PR for it :relaxed:
