### ISSUE TITLE
Default frontend 404 page is broken

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#10899]
Default admin 404 page is pretty:

![image](https://user-images.githubusercontent.com/101513/61134017-91e1ac80-a4b6-11e9-81f0-a1d04a5ef25e.png)

Default frontend 404 page is not:

![image](https://user-images.githubusercontent.com/101513/61134232-16ccc600-a4b7-11e9-8e44-f32232d344d8.png)

It used to show this lil ghosty thing:

![image](https://user-images.githubusercontent.com/101513/61134256-251ae200-a4b7-11e9-9fa7-89dbf1166391.png)

### To Reproduce

1. Use a theme that doesn't have a default error page (e.g. Casper 1.4) or remove the error-404.hbs AND error.hbs templates from modern Casper 
2. Try to visit a non existent page on the frontend
3. See a broken image icon

Not sure if we should be fixing the broken image, or looking to update this template more inline with the new backend 404 cc @peterzimon 

### Technical details:

* Ghost Version: master

**Comment by peterzimon** [comment]
fixed with https://github.com/TryGhost/Ghost/pull/10915
