### ISSUE TITLE
Add ability to pull in total number of members to theme

### ISSUE THREAD

**Issue by allouis** [TryGhost/Ghost#10897]
Add ability to display total number of active members (broken down by plan) on frontend (use case: powering signup CTA)

**Comment by allouis** [comment]
@rishabhgrg I initially added "(broken down by plan)" to this as it made sense to be able to have how many people on each plan - but that would require extra calls to stripe atm (as we don't store the info locally)

Maybe we should drop that requirement, especially as it doesn't fit with when members is in "free" mode?

**Comment by rishabhgrg** [comment]
@allouis Yeah I would consider dropping it as well, as I feel its not needed to power the CTA with that detail, and the count of total members should be enough.

**Comment by allouis** [comment]
@rishabhgrg Does this tie in with the work you started on the theme helpers btw?

**Comment by rishabhgrg** [comment]
@allouis 🤔 Yeah think it can tie-in as this can be extended as a helper

**Comment by signalnerve** [comment]
sorry to resurrect an old thread, but was curious if support for this ever landed in ghost? would love `{{ members_count }}` or something in my templates 😄
