### ISSUE TITLE
Issue with Gallery

### ISSUE THREAD

**Issue by jhaaaa** [TryGhost/Ghost#10913]
Loving Ghost and Casper!

I am running into an issue when I create a post and include the Gallery element.

I included the max of 9 images.

It looks great locally.

However when I deploy it, it looks like this: https://jhaaaa.github.io/jha_land/photo-test-post/

There are two issues:

1. The featured image is broken. The code looks like this - (added line breaks just to make it readable) - something is messing with the `.png` extension:

```
<img srcset="../content/images/size/w300/2019/07/the-parting-sm-1.png 300w, 
../content/images/size/w600/2019/07/the-parting-sm-1.pngg 600w, 
../content/images/size/w1000/2019/07/the-parting-sm-1.pngng 1000w, 
../content/images/size/w2000/2019/07/the-parting-sm-1.pngpng 2000w" 
sizes="(max-width: 800px) 400px, (max-width: 1170px) 700px, 1400px" 
src="../content/images/size/w2000/2019/07/the-parting-sm-1.png" 
alt="June 2019 Gallery">
```

2. The images in the gallery are distorted.

### Technical details

* Casper Version: Where do I find this? I basically used the version provided by Ghost 2.25.6
* Ghost Version: 2.25.6
* Browser Version: Chrome Version 75.0.3770.100 (Official Build) (64-bit)
* OS Version: Mac Mojave 10.14.5

Thank you for any guidance you can provide!

**Comment by allouis** [comment]
Hi @jhaaaa ! 

Thanks for the bug report :relaxed: 

I'm trying to replicate this locally - but I can't, could you give some information about the filename of the featured image that you're uploading? I'm guessing it's `the-parting-sm.png`? is that right?

**Comment by allouis** [comment]
It seems that you're using a third party tool to generate the output - could you try running your Ghost instance locally and visiting the page/post and see if the `srcset` is correct there? If it is then this problem is most likely with https://github.com/axitkhurana/buster/ - and an issue should be raised there!

**Comment by jhaaaa** [comment]
Thank you so much for your reply, @allouis! 

Ah, I see your point about the third-party tool. I'm so new to this toolchain I'm using -- I didn't quite understand that separation until now. I appreciate your thoughtful reply that helped me understand it. 

Yes, when I look at the local instance of the gallery post, it looks great. It is only after the `buster-generate` and my push that I see this on my live site. I'll investigate on that end.

Thank you again!

**Comment by allouis** [comment]
Not a problem! I hope you get it working! :relaxed:
