### ISSUE TITLE
Broken Link: https://ghost.org/slack == 404

### ISSUE THREAD

**Issue by phillhocking** [TryGhost/Ghost#10918]
https://ghost.org/blog/ghost-slack/ has a link to https://ghost.org/slack to access the public Slack team which results in a 404.

**Comment by crotel** [comment]
r u make change inside route.yaml?

**Comment by kevinansfield** [comment]
It's not a broken link. You're looking at a really old blog entry from when the Slack team was introduced, it's since been replaced with [the forum](https://forum.ghost.org) and there's a redirect in place for https://ghost.org/slack to https://forum.ghost.org

**Comment by crotel** [comment]
my misunderstand. ha
