### ISSUE TITLE
Replace `page` column on `posts` table with `type` column

### ISSUE THREAD

**Issue by allouis** [TryGhost/Ghost#10922]
Currently we have a `page` column which is a non-nullable boolean column which defaults to `false`

We want to replace this column with a `type` column,
non-nullable string which defaults to `'post'` and has validations to ensure it is obly ever set to `'page'` or `'post'`

- [x] Remove `page` column from schema
- [x] Add `type` column to schema
- [x] Add migration for copying data from `page` -> `type` column
- [x] Add migrations for dropping the `page` column
- [x] Update the model layer to reflect changes
- [x] Update the serialiser layer to reflect changes

**Comment by allouis** [comment]
@gargol Would be cool if you could give the checkboxes here a once over to confirm it makes sense

**Comment by gargol** [comment]
@allouis the plan looks :ok_hand: 

Just to expand the topic on serialization level. In v2 I see a pretty straight forward solution modifying the input serializer to fit the new model. Guess the bigger deal will be fitting the new field with v01 controllers :thinking: 

Also as for model layer changes, it would need a little more details on the approach. Is it going to be something similar to `Author` model we have where it's a separate model that extends `User` or the change is purely "cosmetical" in `Post` model where the flag `page` will be substituted by appropriate `type` (this approach seems the most appropriate in terms of time/impact)?

**Comment by gargol** [comment]
> I think both input & output serialiser would need to be changed right?

Yup :+1: 

> but tbh a new model is a more complete approach

Yes, this is true and I don't think it's worth an effort just to be "clean" in respect of model separation. Changing existing `post` model should be enough.

**Comment by allouis** [comment]
Awesome - I agree :dancer:

**Comment by allouis** [comment]
Closed via #10944
