### ISSUE TITLE
Can't change password for staff users

### ISSUE THREAD

**Issue by JohnONolan** [TryGhost/Ghost#10927]
I'm the owner user of demo.ghost.io trying to change the password of an author, it fails, and shows this.

First of all it's not a great error message, but it's also extra confusing because there is no "oldPassword" field in the UI:

---

![image](https://user-images.githubusercontent.com/120485/61511508-91eb2a80-aa29-11e9-8391-3c9da3ad39d4.png)

---

![image](https://user-images.githubusercontent.com/120485/61511555-b1825300-aa29-11e9-9c9b-d7304fb6382e.png)

**Comment by gargol** [comment]
This issue should've been solved by https://github.com/TryGhost/Ghost/issues/10427 :thinking:
