### ISSUE TITLE
Problem with \" escape character: Can't use `{{tags autolink="false"}}` in `{{#get "posts" filter="..."}}`

### ISSUE THREAD

**Issue by guenp** [TryGhost/Ghost#10938]
### Issue Summary

Can't use `{{tags autolink="false"}}` in `{{#get "posts" filter="..."}}`

My goal is to get a list of all posts that have the same tags as the current post.

### To Reproduce

1. Used the following code in post.hds file:
```
{{#post}}
    {{#get "posts" filter="tags:[{{tags autolink="false"}}]" }}
        {{#foreach posts}}
            <li>
                <a href="/{{slug}}/">{{title}}</a>
            </li>
        {{/foreach}}
    {{/get}}
{{/post}}
```

Response received:

```
Activation failed
Fatal Errors
Must-fix to activate theme

 Templates must contain valid Handlebars
Oops! You seemed to have used invalid Handlebars syntax. This mostly happens, when you use a helper that is not supported.
See the full list of available helpers here.

Affected files:
post.hbs: Parse error on line 71: ...s:[{{tags autolink="false"}}]" order="sl -----------------------^ Expecting 'CLOSE_RAW_BLOCK', 'CLOSE', 'CLOSE_UNESCAPED', 'OPEN_SEXPR', 'CLOSE_SEXPR', 'ID', 'OPEN_BLOCK_PARAMS', 'STRING', 'NUMBER', 'BOOLEAN', 'UNDEFINED', 'NULL', 'DATA', got 'INVALID'
```

2. When trying the following:
`{{#get "posts" filter="tags:[{{tags autolink='false'}}]"}}`
or
`{{#get "posts" filter="tags:[{{tags autolink=\"false\"}}]"}}`

No error is shown but the template does not get updated.

### Technical details:

* Ghost Version: 2.25.8
* Node Version: v6.11.2
* Browser/OS: chrome 71.0.3578.98
* Database: sqlite
* Used Docker image: https://hub.docker.com/_/ghost

**Comment by ErisDS** [comment]
@guenp this is not a bug, it's a misuse of the theme API. The get helper filter attribute has extra handling for paths, but not for helpers - it's the difference between substituting variables (works) and expecting functions (does not).

There's a guide for doing this exact thing here: https://ghost.org/tutorials/related-posts-block/.
