### ISSUE TITLE
Notification opacity clash

### ISSUE THREAD

**Issue by JohnONolan** [TryGhost/Ghost#10939]
These notification bubbles have a lot of issues anyway, but this reducted opacity is making them illegible now -- so I think we should prob fix that at minimum.

![image](https://user-images.githubusercontent.com/120485/61604105-c56cc580-ac72-11e9-8681-328794d6c902.png)

**Comment by kevinansfield** [comment]
@peterzimon as a temporary workaround I've disabled the opacity in https://github.com/TryGhost/Ghost-Admin/commit/c6ed684ab0274b6adf65f98c997ad4d798f63693
