### ISSUE TITLE
Native app doesn't install on Ubuntu 19.04

### ISSUE THREAD

**Issue by johnnyasantoss** [TryGhost/Ghost#10931]
### Issue Summary

_This might not be the best place, but as I could not find the correct repo for the native apps, I will post it here (feel free to move/close/etc)._

The native app for Ubuntu doesn't work on Pop_OS! (or Ubuntu 19.04)
There's a dependency that is misspelled. The dep is `libgconf2-4` but on 19.04 it has a `-` before the numbers (`libgconf-2-4`)

### To Reproduce

1. Download the `.deb` from https://ghost.org/downloads/ (1.7.0)
2. Try to install it with `sudo dpkg -i ./ghost-desktop-1.7.0-debian.deb`

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

### Technical details:

* OS Info: `Linux laptop-johnny 5.0.0-21-generic #22+system76-Ubuntu SMP Tue Jul 16 19:57:52 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`
* Distro: `Pop_OS! 19.04 (Ubuntu based)`
* Distro Info: 
```log
Distributor ID:	Ubuntu
Description:	Pop!_OS 19.04
Release:	19.04
Codename:	disco
```

### Logs

```log
$ sudo dpkg -i ./ghost-desktop-1.7.0-debian.deb
Selecting previously unselected package ghost.
(Reading database ... 241771 files and directories currently installed.)
Preparing to unpack .../ghost-desktop-1.7.0-debian.deb ...
Unpacking ghost (1.7.0-1) ...
dpkg: dependency problems prevent configuration of ghost:
 ghost depends on libgconf2-4; however:
  Package libgconf2-4 is not installed.

dpkg: error processing package ghost (--install):
 dependency problems - leaving unconfigured
Processing triggers for gnome-menus (3.32.0-1ubuntu1) ...
Processing triggers for desktop-file-utils (0.23-4ubuntu1) ...
Processing triggers for mime-support (3.60ubuntu1) ...
Errors were encountered while processing:
 ghost
$ sudo apt install libgconf-2-4 libgconf2-4
Reading package lists... Done
Building dependency tree
Reading state information... Done
Package libgconf2-4 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'libgconf2-4' has no installation candidate
```

**Comment by daviddarnes** [comment]
Hey @johnnyasantoss! Do you mind opening this issue on this repo? https://github.com/TryGhost/Ghost-Desktop Thanks 🙏

**Comment by acburdine** [comment]
Gonna close this in favor of https://github.com/TryGhost/Ghost-Desktop/issues/343, which seems to report the same issue 😄

**Comment by acburdine** [comment]
Of note: https://github.com/TryGhost/Ghost-Desktop/issues/343 appears to report the same issue.

**Comment by daviddarnes** [comment]
@acburdine thanks Austin!
