### ISSUE TITLE
404 link for integrations from Admin UI

### ISSUE THREAD

**Issue by tpiros** [TryGhost/Ghost#10943]
### Issue Summary

Dead link from Ghost Admin interface

### To Reproduce

1. Login to the Ghost Admin Interface
2. Select "Integrations"
3. Click on "More ..."

This leads to a dead link (404): https://docs.ghost.org/integrations/

### Technical details:

* Ghost Version: Version 2.25.7
* Node Version:-
* Browser/OS: -
* Database: -

**Comment by kevinansfield** [comment]
I'm seeing that link work correctly as a redirect, it redirects from https://docs.ghost.org/integrations/ to  https://ghost.org/integrations/.

In any case, the link was updated in https://github.com/TryGhost/Ghost-Admin/pull/1276 and will go out in tomorrow's release so I'm going to close this issue. Thanks for reporting!
