### ISSUE TITLE
Not possible to link navigation item to content page

### ISSUE THREAD

**Issue by thorque** [TryGhost/Ghost#10942]
Hello :)

### Issue Summary
I have the problem that no new navigation items can be stored.

### To Reproduce

1. Open admin frontend and switch to Design
2. Add a new navigation item with a link to a page you've created via Koenig editor
3. Press on save. The entered link will be changed to the root address, eg. http://localhost:2368

Is this not possible to create a new item linking to created content?

### Technical details:

* Ghost Version: 2.2.5.8
* Node Version: v10.15.3
* Browser/OS: Safari & Firefox on MacOs 10.1.4.5
* Database: embedded SQLlite due to development mode

**Comment by kevinansfield** [comment]
@thorque I'm not able to replicate this issue at all. Could you provide some more specifics about what you are entering in the navigation fields? A screen recording would be very helpful!

**Comment by thorque** [comment]
[Small screen recording](http://g.recordit.co/sqzBuBdn98.gif) - hope this helps

**Comment by kevinansfield** [comment]
That's very strange - using the exact same steps as your video shows I'm not able to reproduce the problem in Chrome, Safari, or Firefox. I've tested with multiple types of `url` config too 😕

Can you share your `url` configuration from your `config.{development/production}.json` file?

**Comment by thorque** [comment]
Yes, that's it:

`{
  "url": "http://pictor-mbp:2368/",
  "server": {
    "port": 2368,
    "host": "pictor-mbp"
  },
[...]`

**Comment by PeekyEater** [comment]
Hey guys! Just try to click on something else before cliking on "save" button.

**Comment by ekrister** [comment]
Hi, I'm having this problem too. It is possible to save any other url like `http://myserver:1234/example`, but I cannot save the URL with the correct server name and port number that I'm actually using. If I try to do that, the value keeps resetting to the previous value that was saved.

Using the Docker installation, Ghost version 4.34.0. Tested on Chrome and Firefox.

**Comment by bland328** [comment]
New Ghost user here, self-hosting with official Docker image, and I'm also running into this problem.

Has anyone had any luck overcoming this?
