### ISSUE TITLE
v2 API throws a 500 error for malformed query param

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#10948]
Malformed query params can cause a 500 error. E.g.

https://demo.ghost.io/ghost/api/v2/content/posts?format=json&include=tags&key=&key=22444f78447824223cefc48062

The malformed part is that there's an empty key, and then a correct key.

### To Reproduce

1. Click on https://demo.ghost.io/ghost/api/v2/content/posts?format=json&format=json&include=tags&include=tags&key=&key=22444f78447824223cefc48062
2. Notice the generic 500

IMO this should throw a 400, not a 500, the same as if you provide other incorrect params:

https://demo.ghost.io/ghost/api/v2/content/posts/?format=json&include=&key=22444f78447824223cefc48062

### Technical details:

* Ghost Version: master

**Comment by pbmiguel** [comment]
Hi @ErisDS. Thanks for reporting this issue.

I am going to give it a try, and see if I can help fix it.
