### ISSUE TITLE
Koening-card-image inconsistency during save card

### ISSUE THREAD

**Issue by ronny35** [TryGhost/Ghost#10951]
### Issue Summary

When I create a new post with one image and publish it, warning appears after any action on the menu :

![warning](https://user-images.githubusercontent.com/15168987/61932890-c3fa1080-af84-11e9-8b41-1f8180ca4cc6.png)

### To Reproduce

1. Create a new post or edit one
2. Add image
3. Publish
4. Do any action on menu

It seems that url is not correcty update in post object because caption update is ok.

### Technical details:

* Ghost Version: 2.25.9
* Node Version: 10.16
* Browser/OS: Ubuntu
* Database: sqlLite

**Comment by gargol** [comment]
Hey @ronny35 :wave: This bug is a part of the issue described in #10477 and it has to do to how URL's are stored for different content in Ghost. Closing this issue in favor of the above mentioned
