### ISSUE TITLE
Bug: Inviting user resulting in 503 error

### ISSUE THREAD

**Issue by utkarsh-var** [TryGhost/Ghost#10952]
### Issue Summary

Unable to send invitations to the user, the `POST /api/v2/admin/invites` returning a [503 response](https://cl.ly/77b6c03a460d). No email is sent to the user, although refreshing the blog shows the invited user under the staff tab.

These are the [Ghost logs](https://cl.ly/7658d83fedde) that I received on sending the user invites.

### To Reproduce

1. Click on staff
2. Click on invite people
3. Enter the email, choose the role and click on send invitation now

### Technical details:

* Ghost Version: 2.25.9
* Node Version: 10.16.0
* Browser/OS: Brave/ macOS Mojave
* Database: MySQL v5.7.27

**Comment by gargol** [comment]
Hi @utkarsh-var :wave: Have you followed [our guide](https://ghost.org/docs/concepts/config/#mail) to set up email configuration? 
Just tried it locally and it worked just fine with default configuration running Admin API v2.

**Comment by lunaticmonk** [comment]
@gargol @utkarsh-var Tried locally and works fine for me too. @utkarsh-var If you have hosted your blog on GCP, may be this would help: https://ghost.org/faq/mail-config-error-google-cloud/

**Comment by bradinator** [comment]
I'm not sure if it is related or not, but I am having an issue sending mail to users on a different domain.  Ie i can successfully invite users on myblogdomain.com, but it gives a 500 error and doesn't send the email when inviting  user@gmail.com

**Comment by gargol** [comment]
Looks like it's an issue with misconfiguration of email service. Feel free to raise a topic on our [forum ](https://forum.ghost.org/) to go through the details and we can move it here once it's a confirmed bug :wink:

**Comment by utkarsh-var** [comment]
The issue is solved after adding Mailgun for the email service. Thanks, @gargol @lunaticmonk
