### ISSUE TITLE
Creating code block in editor using Chrome browser corrupts document

### ISSUE THREAD

**Issue by dbclinton** [TryGhost/Ghost#10965]
When editing a document in the Ghost editor using Chrome on Ubuntu 18.04 and macOS, inserting a code block (```), and then deleting text, the document becomes corrupted and ctrl+z doesn't work to undo the damage.
This does NOT occur for me when doing the exact operation in Firefox on Ubuntu 18.04. See the screencast video linked below for an example (the only step that can't be seen is my hitting Del right before the end).
http://ghostdemo2.s3-website-us-east-1.amazonaws.com

**Comment by dbclinton** [comment]
When editing a document in the Ghost editor using Chrome on Ubuntu 18.04 and macOS, inserting a code block (```), and then deleting text, the document becomes corrupted and ctrl+z doesn't work to undo the damage. 
This does NOT occur for me when doing the exact operation in Firefox on Ubuntu 18.04. See the screencast video linked below for an example (the only step that can't be seen is my hitting Del right before the end).
http://ghostdemo2.s3-website-us-east-1.amazonaws.com

**Comment by kevinansfield** [comment]
@dbclinton unfortunately I'm not able to reproduce following the same steps shown in your screencast video when using Chrome on macOS. When the problem occurs do you see any errors in the web inspector console?

**Comment by dbclinton** [comment]
> @dbclinton unfortunately I'm not able to reproduce following the same steps shown in your screencast video when using Chrome on macOS. When the problem occurs do you see any errors in the web inspector console?

I just tried it again (on Ubuntu 18.04 - Quincy is the one who encountered it on macOS) with two different documents and got the same error. Nothing showed up in the dev console. This time it happened after selecting a paragraph below the code block and hitting Del.
