### ISSUE TITLE
v2.26.0 crashes 

### ISSUE THREAD

**Issue by damionx7** [TryGhost/Ghost#10967]
<img width="696" alt="Screenshot 2019-07-31 at 12 33 33 PM" src="https://user-images.githubusercontent.com/6530843/62190834-ec707900-b38f-11e9-9d82-26222c7166a2.png">

I upgraded the ghost version using 'ghost update'. and got the error message above. Check the attached screenshot for error message.

**Comment by allouis** [comment]
This looks like a node version issue https://ghost.org/faq/node-versions/

**Comment by damionx7** [comment]
<img width="315" alt="Screenshot 2019-07-31 at 12 42 38 PM" src="https://user-images.githubusercontent.com/6530843/62191207-aec02000-b390-11e9-8110-ff256048aa0b.png">

my node version is v10.15.3 and the recommend is v10+

<img width="417" alt="Screenshot 2019-07-31 at 12 43 08 PM" src="https://user-images.githubusercontent.com/6530843/62191271-d4e5c000-b390-11e9-963b-5a0cc0ddda66.png">
