### ISSUE TITLE
Canonical URL not working with V2 theme

### ISSUE THREAD

**Issue by magnolialogic** [TryGhost/Ghost#10978]
### Issue Summary

Canonical URL not used in post's `rel="canonical"` element.

### To Reproduce

1. Specify canonical URL in Post Settings → Meta Data
2. Publish
3. View source for newly published post

### Results

Expected: `rel="canonical"` element in `<head>` uses specified canonical URL
Actual: `canonical` element still uses post's permalink

### Technical details

Ghost 2.25.9, Node 8.10.0

### Additional information

- [I see this is expected behavior for themes using the V1 API](https://github.com/TryGhost/Ghost/issues/10769), but I'm using V2 in my theme/package.json
- [Associated forum post](https://forum.ghost.org/t/clarification-on-canonical-url-behavior/8503)
- I don't know if this matters but FWIW the site I'm working on is currently set to private

**Comment by gargol** [comment]
Hi @magnolialogic! I tried reproducing this issue but with no success. Tried both default Casper and custom themes and canonical URL set from post settings menu appeared when theme was configured with API v2:
```
    "ghost-api": "v2"
```
and was defaulting to the permalink when this attribute was not present of version was set to v1 (as expected). 
Also tried putting the site into private mode and it didn't effect the behavior.

Can you please provide more details about the environment you are using: theme, theme configuration, db version, Ghost instance configuration etc.? Might also help if you post a sample data you are setting in Canonical URL for the post (I have tried both local reference and external one when testing).
