### ISSUE TITLE
Error Sending Email.

### ISSUE THREAD

**Issue by zazaalaza** [TryGhost/Ghost#10996]
Hello,

I've set up my ghost with a gmail account:

       "mail": {
                "from": "me@gmail.com",
                "transport": "SMTP",
                "host": "smtp.gmail.com",
                "options": {
                        "service": "Gmail",
                        "port": 587,
                        "secure": true,
                        "auth": {
                                "user": "me@gmail.com",
                                "pass": "mypassword"
                        }
                }
        },

However I get the following error:

Error sending email! Error sending email: Failed to send email. Reason: 140579932546880:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332: . Please check your email settings and resend the invitation.

What I gather there is different versions of ssl3? However I am unable to figure out how to solve the problem.

**Comment by reubano** [comment]
I got a similar error w Ghost 3.8 and mailgun

`Reason: 140405610432320:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332: `

**Comment by sunknudsen** [comment]
Using following worked for me (port: `587`, requireTLS: `true` and secure: `false`).

```json
{
  "mail": {
    "from": "John Doe <john@example.net>",
    "transport": "SMTP",
    "options": {
      "service": "Mailgun",
      "host": "smtp.eu.mailgun.org",
      "port": 587,
      "requireTLS": true,
      "secure": false,
      "auth": {
        "user": "postmaster@example.net",
        "pass": "…"
      }
    }
  }
}
```

**Comment by wilchak** [comment]
Thanks @sunknudsen. That fixed it for me. Don't you wish this would be DOCUMENTED in the DOCUMENTATION?
