### ISSUE TITLE
Using the control+H to backspace shortcut will delete all images in article

### ISSUE THREAD

**Issue by QuincyLarson** [TryGhost/Ghost#10994]
### Issue Summary

As a mac user, I use the global control shortcuts to quickly manipulate text when I type. One of these is 

### To Reproduce

1. Use control+h to delete characters. 
2. Once you delete the last character on the line, and press control+d again, instead of just deleting the newline character at the end and of the line and bringing the subsequent paragraph upward, Ghost will instead replace all images in an article with a series of bullet point characters.

I've recorded this video to demonstrate this behavior:

https://youtu.be/HkbxeuO7j8k

**Comment by allouis** [comment]
@rishabhgrg Was able to replicate this also :grimacing:

**Comment by kevinansfield** [comment]
@QuincyLarson @allouis were you using <kbd>Ctrl+h</kbd> as per the issue title or <kbd>Ctrl+h</kbd> as per the issue description?

If this is about <kbd>Ctrl+d</kbd> then this is a duplicate of https://github.com/TryGhost/Ghost/issues/10240

**Comment by rishabhgrg** [comment]
@kevinansfield Ah, I tried both <kbd>Ctrl+h</kbd> and <kbd>Ctrl+d</kbd> and hit the same behavior in both cases, maybe worth updating the original issue with <kbd>Ctrl+h</kbd>.

**Comment by QuincyLarson** [comment]
@rishabhgrg Agreed.

@kevinansfield Thanks for finding this. I'm closing this issue and I've commented over on #10240.
