### ISSUE TITLE
Webhook fails with "UNABLE_TO_VERIFY_LEAF_SIGNATURE"

### ISSUE THREAD

**Issue by ReFruity** [TryGhost/Ghost#11001]
### Issue Summary

I have node.js app listening at `https://myserver.com/webhook`. Ghost blog is also at `https://myserver.com`. When I add a webhook on event post published and publish a post it fails with `Request to https://myserver.com/webhook failed because of: UNABLE_TO_VERIFY_LEAF_SIGNATURE.`

I am sorry if it is not ghost related issue, I couldn't find the answer anywhere. In case it's not here is my nginx config:

```
server {
  server_name myserver.com;
  listen 443;
  ssl on;
  client_max_body_size 4G;
  keepalive_timeout 5;

  ssl_certificate /etc/letsencrypt/live/myserver.com-0001/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/myserver.com-0001/privkey.pem;

  location /webhook {
    proxy_read_timeout 6000s;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header Host $http_host;
    proxy_redirect off;
    proxy_pass http://localhost:3001;
  }

  location / {
    proxy_read_timeout 6000s;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header Host $http_host;
    proxy_redirect off;
    proxy_pass http://localhost:2368;
  }
}

server {
  server_name myserver.com;
  listen 80;

  location / {
    return 301 https://$server_name$request_uri;
  }

  location /.well-known/ {
    alias /var/www/html/.well-known/;
  }
}
```
And also `index.js`:

```javascript
const express = require('express')
const config = require('./config')

const app = express()
const port = config.port

app.post('/webhook', (req, res) => {
  console.log('Post triggered')
  res.send('Hello World!')
})

app.listen(port, () => console.log(`Example app listening on port ${port}!`))
```

### Technical details:

* Ghost Version: 2.27.0
* Node Version: 8.10.0
* OS: Ubuntu 18.04.2 LTS
* Database: mysql

**Comment by kevinansfield** [comment]
@ReFruity this isn't specifically Ghost, or even node.js related, the problem is that your host system's ssl configuration is not recognising the CA of your webhook receiver's certificate.

I suggest searching for the `UNABLE_TO_VERIFY_LEAF_SIGNATURE ` error to find a solution that works for you. If you need further help, feel free to post on our [forum](https://forum.ghost.org).
