### ISSUE TITLE
Text expansions do not work immediately after a soft-break atom

### ISSUE THREAD

**Issue by kevinansfield** [TryGhost/Ghost#11020]
### Issue Summary

If you use <kbd>Shift+Enter</kbd> to create a soft-break atom, then at the beginning of the new line type a markdown expansion, it's not recognised by the text expansions and won't apply formatting when you close the markdown.

### To Reproduce

1. Create a new post in the editor
2. Type something then press <kbd>Shift+Enter</kbd>
3. Type `*testing*`
4. Note that the text does not change to italic when typing the closing `*`

If you repeat the steps but type a space or anything else before `*testing*` then the expansion will complete correctly.

The problem likely lies with the [text-expansion regexes](https://github.com/TryGhost/Ghost-Admin/blob/master/lib/koenig-editor/addon/options/text-expansions.js#L199) where it's not recognising the soft-break as a start of a section (`^`) or as whitespace (`\s`).

**Comment by marek-lach** [comment]
What’s the current status for addressing this?
