### ISSUE TITLE
Cannot use https site url with reverse proxy.

### ISSUE THREAD

**Issue by AndrewRademacher** [TryGhost/Ghost#11039]
### Issue Summary

Our setup terminates all SSL traffic in an Nginx instance. Then forwards HTTP traffic to ghost. The intuitive thing to do is to set the root url to an 'https' value. When doing this ghost does not respond to http traffic, and the browser gets caught in a cycle of following 301 links.

If the url in ghost is set to an 'http' value and you use the content API. Images in blog posts are linked using http. Which results in mixed security assets being loaded on the client page. Given that the proxy 301 redirects all https traffic to http this results in mixed security content in spite of actually loading images from https.

### To Reproduce

1. Have nginx reverse proxy that 301 redirects http to https.
```
server {
    listen      80;
    listen      [::]:80;
    server_name _;
    return 301 https://$host$request_uri;
}

server {
    listen              443 ssl;
    listen              [::]:443 ssl;
    server_name         staging-ghost.naut.app;
    keepalive_timeout   75s;

    ssl_certificate     ...;
    ssl_certificate_key ...;
    ssl_protocols       TLSv1 TLSv1.1 TLSv1.2;
    ssl_ciphers         HIGH:!aNULL:!MD5;

    location / {
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header HOST $http_host;
        proxy_set_header X-NginX-Proxy true;

        proxy_pass http://ghost/;
        proxy_redirect off;
    }
}
```
2. Configure ghost with https.
```
spec:
      containers:
      - name: ghost
        image: ghost:2.26.0
        env:
        - name: url
          value: https://staging-ghost.naut.app
```
3. Attempt to navigate to page.
<img width="709" alt="Screen Shot 2019-08-19 at 17 21 28" src="https://user-images.githubusercontent.com/2389419/63303574-dc202f80-c2a5-11e9-8f9a-7eecbd05c171.png">

### If ghost URL is not HTTPS
<img width="751" alt="Screen Shot 2019-08-19 at 17 24 28" src="https://user-images.githubusercontent.com/2389419/63303715-3b7e3f80-c2a6-11e9-85de-2b551c316110.png">

### Technical details:

* Ghost Version: 2.26.0 - docker
* Browser/OS: All

**Comment by acburdine** [comment]
I believe you're missing the X-Forwarded-Proto directive (see the Ghost-CLI nginx conf template here: https://github.com/TryGhost/Ghost-CLI/blob/master/extensions/nginx/templates/nginx-ssl.conf#L14

**Comment by AndrewRademacher** [comment]
Thank you @acburdine for illuminating this detail of the setup. Forwarding this field does allow ghost to return requests. However, this may just reveal a further issue in that the URL configuration doesn't not cause the feature_image to be returned as `https` as you would intuitively expect it to.

Configuration:
```      
- name: ghost
        image: ghost:2.26.0
        env:
        - name: url
          value: https://staging-ghost.naut.app
```

Output
<img width="317" alt="Screen Shot 2019-08-19 at 20 17 36" src="https://user-images.githubusercontent.com/2389419/63309981-6d030500-c2be-11e9-8c0e-f63eec9fb392.png">

**Comment by acburdine** [comment]
@AndrewRademacher apologies, should have clarified further. In addition to adding the x-forwarded-proto directive, you’ll need to also put https in the url you use to configure Ghost.

**Comment by AndrewRademacher** [comment]
No worries, you were clear about it. The configuration described above is specifying https. Using the ghost docker images environment variable configuration.
