### ISSUE TITLE
Clean up mocha eslint errors

### ISSUE THREAD

**Issue by kevinansfield** [TryGhost/Ghost#11038]
We've moved to `eslint-plugin-ghost@0.5.0` which includes [`eslint-plugin-mocha`](https://github.com/lo1tuma/eslint-plugin-mocha).

A number of the mocha linting rules are quite valuable for keeping tests performant and readable but were turned off in Ghost because they caused a lot of noise with our existing codebase. It would be great to resolve the issues so that we can turn the rules back on.

You can find the list of rules that were turned off here https://github.com/TryGhost/Ghost/blob/master/core/test/.eslintrc.json#L24-L27

For anyone picking this issue up, a separate PR for each rule would be the preferred approach, please comment on this issue if you make a start to avoid duplicate work 🙂 

General approach:
1. Choose a rule and check the [rule's docs](https://github.com/lo1tuma/eslint-plugin-mocha/tree/master/docs/rules) to make sure you understand what it's checking for and how to fix reported problems
2. Remove the line from `core/test/.eslintrc.json` that corresponds with the rule that you are enabling
3. Run `yarn lint:test`
4. Work through the reported problems - make a change to the code then run `yarn lint:test` again to make sure the problem disappears. If you have eslint configured in your editor you should be able to get some immediate feedback too
5. Periodically run `grunt test:unit` to make sure there haven't been any non-linting problems introduced by the code changes

**Comment by dhuang612** [comment]
starting on rule:
camelcase

**Comment by nip10** [comment]
working on rule ghost/mocha/no-identical-title

**Comment by dhuang612** [comment]
Hi, 
created PR #11140
for max-top-level-suites
Thanks!

**Comment by dhuang612** [comment]
I'm going to start on the next available one:
no-setup-in-describe

**Comment by dhuang612** [comment]
I also reviewed nip10's PR and refactored the two pieces of code he was stuck on.
Once they are fixed it should be ready to be merged.

**Comment by dhuang612** [comment]
completed no-setup-in-describe
#11154

I still need to merge these PR with the updates that were completed over the last few days.

**Comment by dhuang612** [comment]
Hi,

I did a git pull push origin on my local repo.
Completed refactor changes and resubmitted PR 
which is now #11164

Please let me know if any changes need to be made!

**Comment by anusreePrakash** [comment]
I am picking ghost/mocha/no-sibling-hooks

**Comment by dsuarezlogans** [comment]
Hello! are all the rules fixed? can I pick one?

**Comment by dhuang612** [comment]
Hi, I believe they've all been claimed @dsuarezlogans

**Comment by dhuang612** [comment]
Hi, 
@gargol 
Updated PR #11154 after I accidentally pulled in some additional code into this commit. 
passes
```
npm run test
npm run lint

```
Please let me know if anything else needs to be changed!

**Comment by nmizoguchi** [comment]
👋 Hello! Saw this was marked as `stale`, and the work done previously got outdated. Opened https://github.com/TryGhost/Ghost/pull/19720 to handle both `ghost/mocha/no-identical-title` and `ghost/mocha/max-top-level-suites`. I plan to finish the remaining ones in separate PRs!

In any case, it was a good opportunity to learn more about the codebase 🙌 
cc @kevinansfield
