### ISSUE TITLE
`fields=url` return 404 error

### ISSUE THREAD

**Issue by fueko** [TryGhost/Ghost#11043]
### Issue Summary

All URLs from post's API are /404/ if url specified in fields field.

### To Reproduce

Get some data from post's API:

`&fields=url` would return correct url
`&fields=url,title` would return **404**

Adding an `id` temporarily fixes issue: 

`&fields=url,title,id` would return correct url

### Technical details:

* Ghost Version: 2.29.0
* Node Version: 10.13.0
* Database: sqlite3

**Comment by ErisDS** [comment]
@fueko do you have a custom routes.yaml file?

I think this is a regression but needs to be verified.

**Comment by fueko** [comment]
@ErisDS I don't have. I installed a completely new installation (localhost), added the API key - the problem still appears. I checked - and the problem starts with version `2.28.1`

**Comment by fueko** [comment]
@ErisDS Look at [demo.ghost.io](https://demo.ghost.io/ghost/api/v2/content/posts/?key=22444f78447824223cefc48062&fields=url,title)

**Comment by rishabhgrg** [comment]
👋 Hi @fueko, thanks for reporting the issue. Can confirm this is a regression and the bug was introduced in `2.28.1` release as you mentioned. We are working on a fix for this and will release it asap.

**Comment by rishabhgrg** [comment]
@fueko This has now been fixed in [latest version](https://github.com/TryGhost/Ghost/releases/tag/2.29.1) (2.29.1), thanks again for reporting. 😄
