### ISSUE TITLE
Database migration not working

### ISSUE THREAD

**Issue by mbernard** [TryGhost/Ghost#11047]
Hi,

I'm trying to update from version 2.1.0 to 2.29. Everything seems fine, I got no error messages during database upgrade. If look at the migration table (see image below) everything seems ok also. However, no changes were made to my DB, many table and column that should have been added are not there. 

![image](https://user-images.githubusercontent.com/1928530/63596500-65c34c00-c589-11e9-8b93-4a75bd97ebd9.png)

If you look at this image you can see that many tables are missing. ie. Sessions
![image](https://user-images.githubusercontent.com/1928530/63596732-e1bd9400-c589-11e9-96b4-2f4ac976b8a5.png)

* Ghost Version: 2.29.1
* Node Version: 10.15.2
* Database: SQLite

**Comment by allouis** [comment]
Hey @mbernard I guess you got your issue solved? Do you know what it was?

**Comment by kevinansfield** [comment]
Re-opening this issue because we've had other reports and no underlying reason has been found or fix applied.

**Comment by gargol** [comment]
There haven't been more reports around this and the issue doesn't seem critical. Will reopen if it becomes a bottleneck.
