### ISSUE TITLE
Add native image lazy loading support

### ISSUE THREAD

**Issue by Cherry** [TryGhost/Ghost#11052]
As of Chrome 76, native lazy loading has come to the web!

Setting images in blog posts to `loading="lazy"` (or user-configurable) could provide massive performance benefits, especially on blog posts with lots of images. The engineering team over at the BBC did [a write-up about this](https://medium.com/bbc-design-engineering/native-lazy-loading-has-arrived-c37a165d70a5) and showed page load times reduced by 50%.

https://web.dev/native-lazy-loading

Wordpress is also looking to do this by default very soon as per https://core.trac.wordpress.org/ticket/44427. 

Whilst this is only currently [supported in Chrome](https://caniuse.com/#feat=loading-lazy-attr), [Safari has expressed interest](https://github.com/whatwg/html/issues/2806#issuecomment-378831265), and Chrome does account for over 50% of the web. 

This is a completely non-destructive and backwards-compatible change, so implementing it now will only mean further benefits in the future as other browser vendors implement the spec.

PS. I know that feature requests generally aren't tracked here, but I was advised to create this issue as per https://forum.ghost.org/t/add-native-image-lazy-loading-support/8799/2

**Comment by daviddarnes** [comment]
@Cherry My bad, features are kept on the forum as feature requests on the repo are typically closed. We can track interest on the forums over here https://forum.ghost.org/t/add-native-image-lazy-loading-support/8799. Sorry for the confusion :slightly_smiling_face:

**Comment by angristan** [comment]
Looks like it's been added as part of v4! https://github.com/TryGhost/Ghost/commit/074ce4efb0a9ebd43ffb5d2a8643d814641c8850
