### ISSUE TITLE
Gallery images appear blurry on mobile

### ISSUE THREAD

**Issue by daviddarnes** [TryGhost/Ghost#11051]
### Issue Summary

Images within galleries appear to be poor resolution when expanded on a mobile device. This does not correlate when the same image is expanded on a desktop machine.

> When I look at gallery images on my iPhone XR or 2017 iPad the thumbnails look fine, but expand the images they appear blurry. The more images that are in the gallery (And the small the thumbnail) the worse the loss in quality is.

### To Reproduce

1. Create a new post with a set of images to construct a galley
2. Publish the post and navigate to it on a mobile device
3. Tap on one of the image and compare it's resolution with itself on a desktop screen

### Technical details:

* Ghost Version: 2.29.1
* Node Version: N/A
* Browser/OS: Safari iOS
* Database: N/A

First reported here: https://forum.ghost.org/t/gallery-images-blurry-on-mobile/8794

**Comment by kevinansfield** [comment]
@daviddarnes do you know if this is in the admin area or in a particular theme?

> Tap on one of the image

This sounds like it might be a theme problem. Casper doesn't have any functionality where it loads a different image when tapping.

**Comment by daviddarnes** [comment]
@kevinansfield they didn't say what theme they're using but that is a good assumption. Should this be transferred to the Casper repo?

**Comment by kevinansfield** [comment]
@daviddarnes sounds like something that should be handled on the forum unless a bug has been verified in one of our themes.

**Comment by daviddarnes** [comment]
@kevinansfield I'm going to clarify which theme this is and then I'll reopen / move depending on the answer
