### ISSUE TITLE
Closing tab while post editor is open tells me I can't leave or I lose progress

### ISSUE THREAD

**Issue by levelsio** [TryGhost/Ghost#11062]
Closing tab while post editor is open tells me I can't leave or I lose progress but the post is already saved.

**Comment by gargol** [comment]
Hi @levelsio! This is most likely the same bug like this on https://github.com/TryGhost/Ghost/issues/10620 and will be tackled as a part of this issue https://github.com/TryGhost/Ghost/issues/10477. In case it's something else feel free to reopen :wink:
