### ISSUE TITLE
Unable to View Site on Admin for private sites with custom domain

### ISSUE THREAD

**Issue by rishabhgrg** [TryGhost/Ghost#11078]
### Issue Summary
When trying to `View Site` on admin for private sites which have custom domain setup, it fails to load the page with `500` error on screen and CORS error on console.

![admin](https://user-images.githubusercontent.com/3461456/64316731-4be72780-cfd3-11e9-99a8-f3659142e113.png)

![cors error](https://user-images.githubusercontent.com/3461456/64319754-be0f3a80-cfda-11e9-9d80-6985c0ef7679.png)

### To Reproduce

1. Set a site with custom domain to private from settings in Admin
2. Click on `View Site` in Admin
3. It shows 500 error on screen instead of site

### Technical details:
Ghost Version: v2.30.2
Node Version: v10.15.3

**Comment by kevinansfield** [comment]
Switched this to a server-side bug, the problem is that the `/private/` route in the `front-end` app is not returning CORS headers that allow the configured admin url.
