### ISSUE TITLE
Cannot preview an unpublished post

### ISSUE THREAD

**Issue by Laul0** [TryGhost/Ghost#11077]
### Issue Summary

For any reason, if I need to unpublish a post, edit it again and preview the result before to publish it again, I can't.

### To Reproduce

1. Create a new post
2. Publish this same post
3. Unpublish this same post
4. Edit it and try to show the preview
    * Save and click at the bottom "Save. View preview"
    * Click on there gear (top right) and click on "Preview"

You should have a 404 error page because the preview try to use the publish URL rather than a temporary one like any current not published post (never published).

### Technical details:

* Ghost Version: 2.30.2
* Node Version: 10.16.3
* Browser/OS: Edge/Chrome/Safari
* Database: MySQL

**Comment by kevinansfield** [comment]
@Laul0 I'm not able to replicate this. Do you have any more details about your hosting setup?

**Comment by Laul0** [comment]
Hi @kevinansfield, thank you for your investigation.

Informations about my hosting:
- [Docker](https://hub.docker.com/_/ghost)
- Self-hosted

Something else that can be useful for you?

**Comment by Laul0** [comment]
Hey ! I updated my environment with the latest version of Ghost (2.31.0) and the problem seems solved.
I close this issue.
