### ISSUE TITLE
Can't add XSRF headers

### ISSUE THREAD

**Issue by arlopezg** [TryGhost/Ghost#11086]
```
{
    "errorType": "TypeError",
    "errorMessage": "Cannot read property 'charAt' of undefined",
    "stack": [
        "TypeError: Cannot read property 'charAt' of undefined",
        "    at resolveURL (webpack:///./node_modules/@tryghost/content-api/es/content-api.js?:2057:46)",
        (...)
    ]
}
```

### Issue Summary

Hello guys :)

I'm trying to consume the Content API via JS and running into an error while authenticating to my Ghost blog. Seems like `urlParsingNode.pathname` equals to `undefined` in the resolveURL function (`@tryghost/content-api/es/content-api.js@2056`).  This causes the script to crash.

I'm using Angular@7.2.11 and Ghost Content API@1.2.7.

### To Reproduce

1. Install `@tryghost/content-api`
2. Import on the project `import GhostContentAPI from '@tryghost/content-api`
3. Set Ghost's credentials (URL, API key, version 'v2' as shown in the API docs)
4. `ng build` the project
5. Access the component that consumes the blog's content
6. Get the error described at the start of this issue

The expected behaviour would be to get the content I'm trying to retrieve (in this case, my most recent posts).

### Technical details:

* Ghost Version: v1.2.7 (Content API)
* Node Version: v11.12.0
* Browser/OS: Chrome 78/OSX

**Comment by gargol** [comment]
hi @arlopezg :wave: 	 the use of Ghost SDK doesn't belong to this repository and the report seems to have anything to do with XSRF :smiley:  The best way to get help around usecases for the SDK is at our forum here https://forum.ghost.org Also, would be great if you could prep a reproducible stand-alone example to check if it's something to do with build tool (Webpack in this case) or some misconfiguration.
