### ISSUE TITLE
Missing `prettyUrls` behaviour on a number of Admin API routes

### ISSUE THREAD

**Issue by kevinansfield** [TryGhost/Ghost#11083]
I first noticed this on the `/api/v2/admin/site` route but looking at the [v2 routes file](https://github.com/TryGhost/Ghost/blob/master/core/server/web/api/v2/admin/routes.js) we have a number of routes that are missing the the `prettyUrls` middleware which enforces our trailing-slash standard.

Currently we only include the `prettyUrls` middleware in the `mw.authAdminApi` group. We should review the endpoints which don't use that to see if it needs adding separately, or alternatively look at whether we can apply it in a more general fashion.

**Comment by orafaelfragoso** [comment]
@kevinansfield How do I check for pretty urls in the other routes? How do I know if these routes need pretty urls?

I would love to tackle that for you.
