### ISSUE TITLE
Creating Internal Tag with # not generating "hash-" prefix at tag screen.

### ISSUE THREAD

**Issue by biswajit-saha** [TryGhost/Ghost#11105]
### Issue Summary

When creating internal tag by clicking on "New Tag" button at tag screen, If I input tag name `#abc` It should generate the slug `hash-abc` by default. But it is generating the slug `abc` same as external tag.

But when we add an already non existing internal tag while editing post (from the post setting panel) It works as expected.  If I add non existing tag `#xyz` from the post setting panel, and check the newly added tag in tag screen. It's slug is perfectly prefixed with `hash-`. so it is `hash-xyz`.

### To Reproduce

1. Go to "Tags" screen Click on "New tag" button.
2. Add any tag name prefixed with # for make it internal tag.
3. Click outside of the name input box.
4. Check the auto generated slug is without `hash-` prefix

### Technical details:

Local Installation for development

* Ghost Version: 2.31.0
* Node Version: 10.16.0
* Browser/OS: Chrome/Windows 10
* Database: SQLite

**Comment by rishabhgrg** [comment]
👋 Hey @biswajit-saha, thanks for reporting this issue. Can confirm the bug, it got introduced in `2.30.0` with our tags screen refresh. We'll add in a fix for this asap and should be released with next version.
