### ISSUE TITLE
🦊[Firefox] - Various issues with WYSIWYG edior

### ISSUE THREAD

**Issue by ScreamZ** [TryGhost/Ghost#11112]
Hello,

I'll report one sure bug in the following, but it seems that it break other things.

# Introduction
I've just pached my ghost instance with `2.31.0` and I started writing a new article.

As a French 🇫🇷 developer I used to use commons French chars like ^ (ê, â, …) but also the `backtilde` caracter to highlight some part on my words / code.

## 1st issue: Strange issue with caracters on Firefox

On chrome I'm almost sure it work well, but sometime i also get the bug, but on Firefox, things are getting complicated:

When I push 
- ` + `space` -> I get two ` ` (on chrome I get only one)
- `^` + `e` -> I get `^ê`
- one time backtilde and one more backtilde -> I get 3 backtilde

And so on, you can try with various combination of French letters (I know core team is French 🥖)

It could be related to the new release with the card but I'm sure of nothing, I could investigate deeper but I would like to know if I'm the only one facing those kind of issue (and it should be related to my environment) or someone else also got ?

Here on github everything seems fine :)

## 2nd issue: UI broke upon using those characters

I was trying to detect the issue using what we saw above, and by trying that I successfully broke my card UI into something like this:

![Screenshot_2019-09-13 Les services workers — 2ème partie Mise-à-jour - Modern Javascript](https://user-images.githubusercontent.com/6640835/64890509-1f38ad00-d670-11e9-89af-2d7062ce9ceb.png)

For that bug, I'm not able to say if this is specific to firefox or also on chrome / others. But as you can see if my mouse hover the content, there is still the edition box 

<img width="1020" alt="Screenshot 2019-09-13 at 21 48 39" src="https://user-images.githubusercontent.com/6640835/64890603-54dd9600-d670-11e9-8cb8-1c85c0a997ff.png">

### Technical details:

* MacOS laptop
* Ghost Version: 2.31.0
* Firefox 70.0b4 (64-bit)(Aurora)
* Chrome 76.0.3809.132

Thank you,

Andréas

**Comment by gargol** [comment]
Hi @ScreamZ :wave: I wasn't able to reproduce any of these issues on my local environment. Was able to type in `développeur` with no problem :smile: I suspect it's an issue with your local config. To figure that out would suggest posting on our forum https://forum.ghost.org/ :wink:

**Comment by ScreamZ** [comment]
@gargol 

Many issues get resolved by : https://www.foobarflies.io/backticks-on-the-mac-keyboard/

Looks like medium are ghost editor are very sensible to this.
