### ISSUE TITLE
Image URL does not render correctly

### ISSUE THREAD

**Issue by diwakergupta** [TryGhost/Ghost#11136]
### Issue Summary

Pasting in an image URL into the editor doesn't render the image. The image of the image card is also inconsistent depending on how it is invoked.

### To Reproduce

*Case 1*

1. Paste in an image URL into the editor (e.g. `https://imgs.xkcd.com/comics/the_general_problem.png`)
2. Expected: an image is rendered using the image card. Actual: just the image link.

*Case 2*
1. Paste in the image URL _after_ entering `/image`
2. Expected and actual: image card rendered correctly

*Case 3*
1. Open the image card by choosing from the `+` button in the left sidebar
2. Expected: some way to provide image URL. Actual: no way to provide image URL, only allows uploads

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

See above.

### Technical details:

Version 2.31.0
Environment production
Database sqlite3
Mail SMTP
Node / OS version: whatever is in `ghost:alpine` Docker image
Browser: Chrome

**Comment by kevinansfield** [comment]
@diwakergupta this is all as expected based on our current functionality. If you would like to suggest features, please use the [Ideas category](https://forum.ghost.org/c/Ideas/l/latest?order=votes) on our forum 🙂
