### ISSUE TITLE
CMD + S key command doesn't save tag changes

### ISSUE THREAD

**Issue by daviddarnes** [TryGhost/Ghost#11138]
### Issue Summary

Using save shortcut key command (CMD + S) doesn't save changes in a tag.

### To Reproduce

1. View an existing tag in the admin
2. Make any change
3. Hit CMD + S (see the save button update)
4. Attempt to leave the page, unsaved changes prompt will appear

### Technical details:

* Ghost Version: 2.31.0
* Node Version: -
* Browser/OS: Chrome 76.0.3809.132 / macOS Mojave
* Database: Pro account

Originally reported here: https://forum.ghost.org/t/admin-bug-the-tag-edit-page-could-not-be-saved-using-the-shortcut-key-cmd-s/9129

**Comment by web-man** [comment]
@daviddarnes I'll take this one

**Comment by Netoun** [comment]
Issue fix in : https://github.com/TryGhost/Ghost-Admin/pull/1368

**Comment by stevenans9859** [comment]
?

**Comment by web-man** [comment]
@daviddarnes @gargol This guy has worked on this one, and it seems that he had created a fix for it, should I continue working on it?

**Comment by kevinansfield** [comment]
This issue was resolved in https://github.com/TryGhost/Ghost-Admin/commit/35b53e7712a57a27b06785bd33145a04439c4f6c
