### ISSUE TITLE
Add Edit Post button when reading post as logged in admin user

### ISSUE THREAD

**Issue by levelsio** [TryGhost/Ghost#11137]
On other blog platforms I will have an [ EDIT POST ] button in the top right if I am browsing my blog and reading a post while being logged in.

Many types I will read my post and have a typo and want to quickly click through to the Edit Post page. But instead I have to login, go to posts, search the post, open it, edit.

I know I can add /edit to a URL but that means people have to edit URLs which especially sucks on mobile. I just want to tap a button and go to the editor.

**Comment by gargol** [comment]
Hey @levelsio :) There is no way to check if the user is logged in from the frontend layer. It is by design isolated from admin area and knows nothing about admin users. A similar topic has been raised here - https://forum.ghost.org/t/link-from-the-front-end-to-the-edit-page/8051/2
