### ISSUE TITLE
Bookmark card: Better url handling and error message

### ISSUE THREAD

**Issue by rishabhgrg** [TryGhost/Ghost#11212]
### Issue Summary

Bookmark card has few minor issues atm as listed below - 

- Better error message handling: Currently bookmark card fails with `Unable to parse URL` error in case of all failures including insufficient metadata available. We should differentiate between "unable to parse" and "page has insufficient metadata" cases and show appropriate error message to avoid confusion (ref: https://github.com/TryGhost/Ghost/issues/11201)

- Storing original url on payload: We currently store the url grabbed from page's metadata in the bookmark card payload, which might not be pointing to original pasted url in many cases. We should improve our handling of this by storing the url that is pasted in rather than one that is grabbed from the page. (ref: https://github.com/TryGhost/Ghost/issues/11209)

- Fixing empty payload for invalid cases: In case of invalid bookmark card, we currently store `payload` as `{}`, unlike `embed` card which stores original `url` as part of payload - `payload: {url: '....'}`. Bookmark card payload needs to be updated to mimic same behavior because it lets the user click the retry/paste as link buttons to get their original url back.

**Comment by jenlky** [comment]
Hi I would like to pick up this issue

**Comment by souravdasslg** [comment]
Hey @rishabhgrg , is this issue taken up by anybody ? I'd like to take this up :)

**Comment by kamranayub** [comment]
Oh wow, the second bullet point is huge if someone's trying to showcase affiliate-based links. Yikes!

I also noticed that even for relatively large sites like Amazon, you don't seem to get the right image previews and information.

For example, if I want to feature some products I'm reviewing/using, I get this:

![image](https://user-images.githubusercontent.com/563819/66885810-1a328a80-ef9b-11e9-98ab-fccab65011be.png)

But if posted to Facebook, the open graph meta tags seem correctly interpreted:

https://developers.facebook.com/tools/debug/sharing/?q=https%3A%2F%2Fwww.amazon.com%2FSmart-Enabled-Google-Assistant-HomeKit%2Fdp%2FB076J8SLSF

![image](https://user-images.githubusercontent.com/563819/66885927-73022300-ef9b-11e9-9cbf-0bca73c7dca9.png)

I love this new feature but especially preserving what I pasted in is critical. It would be ideal to be able to have a fly-out to customize the fields if it failed to parse or doesn't look right, to fix issues like that, too.

**Comment by devaman** [comment]
Hi @rishabhgrg , I have tried resolving this issue... Can you take a look at it?

**Comment by kevinansfield** [comment]
> I also noticed that even for relatively large sites like Amazon, you don't seem to get the right image previews and information.

Unfortunately Amazon make it difficult to reliably extract product images from their pages. They don't include any of the standardised opengraph data so it's necessary to parse the html and find an element containing the image that Amazon is showing as the primary image - this is easier said than done because they use different html and classes across different types of product page (even for the same product in my testing).

There's an upstream issue for the library we use to extract metadata for bookmark cards here https://github.com/microlinkhq/metascraper/issues/50. I tested adding the `metascraper-amazon` dependency to our metascraper plugins but it didn't improve the situation there.
