### ISSUE TITLE
Instagram Embed Issue - No Image

### ISSUE THREAD

**Issue by mchlbowyer** [TryGhost/Ghost#11216]
### Issue Summary

Instagram Embed does not show image, only image description.

### To Reproduce

1. Create New Post
2. Either paste an instagram URL or click add then instagram then paste image URL.

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

Image should display on page.

It appears that Ghost adds the instagram URL in front of the embed URL. Looking at the network traffic when loading the post, a request is made to https://www.instagram.com//www.instagram.com/static/bundles/es6/EmbedSDK.js/47c7ec92d91e.js (as you see instagram.com is displayed twice). I cannot actually find where this is done in the code, so am unsure how to fix myself, however I believe this is the point where it fails.

### Technical details:

* Ghost Version: 2.31.1
* Node Version: 10.16.3
* Browser/OS: Chrome
* Database: MySQL

**Comment by kevinansfield** [comment]
@mchlbowyer I'm not able to reproduce this, it's possible that Instagram had a bug in their embed code when you tried. Could you try again (you may need to delete then re-create the embed) and let me know if it's working now?

**Comment by mchlbowyer** [comment]
@kevinansfield have tried again and still the same. The dev output shows:

(index):201 GET https://www.instagram.com//www.instagram.com/static/bundles/es6/EmbedSDK.js/2fe3a16f6aeb.js net::ERR_ABORTED 404

**Comment by kevinansfield** [comment]
@mchlbowyer did you delete the embed card and re-paste the original link to create a new one? When embed cards are created the html code is fetched from the source - we don't have any control over it. If the embed code Instagram is returning is buggy then that buggy code will be saved, it won't start or start working unless it's deleted and re-created with Instagram responding with non-buggy code.

If you inspect the response from `/ghost/api/v2/admin/oembed/` when creating the embed card then you'll be able to see the code that Instagram has provided.

**Comment by mchlbowyer** [comment]
@kevinansfield so I think I may have found the issue - Ghost presumably calls 'https://www.instagram.com/embed.js' to get the embed Javascript, however calling that URL redirects to 'https://www.instagram.com//www.instagram.com/static/bundles/es6/EmbedSDK.js/2fe3a16f6aeb.js' which I think is causing the issue with the image not displaying (this also seems to be a common issue as even the Instagram embed documentation shows an embedded post without an image, although I can't for the life of me find a way to report this to Instagram).
