### ISSUE TITLE
Admin API doesn't work without Access-Control-Allow-Credentials

### ISSUE THREAD

**Issue by penalosa** [TryGhost/Ghost#11234]
### Issue Summary

I can't use the admin API from a browser client, as CORs prefetch fails due to Access-Control-Allow-Credentials. This is with user authentication, so I assumed this would be possible.

#### Login
```
await fetch(`$ADMIN_URL/session`, {
  method: "post",
  headers: {
    "content-type": "application/json"
  },
  body: JSON.stringify({
    username: $USERNAME,
    password: $PASSWORD
  })
});
```

#### Attempt to get user data
```
await fetch(`$ADMIN_URL/users/me`, {
  method: "get",
  credentials: "include",
  headers: {
    "content-type": "application/json"
  }
});
```
This fails with a CORs error - Access-Control-Allow-Credentials not present

I expected this to return the user data for the logged in user

### Technical details:

* Admin Api version: v2 & canary
* Ghost Version: 2.X
* Node Version: 
* Browser/OS: Firefox, Chrome, Safari on macOS
* Database:

**Comment by ErisDS** [comment]
I believe that with fetch you have to add `credentials: "include",` to both requests. If that doesn't resolve the issue please raise a topic on the forum.
