### ISSUE TITLE
Broken link in installation docs

### ISSUE THREAD

**Issue by dandv** [TryGhost/Ghost#11255]
Sorry if this is the wrong repo, but https://github.com/TryGhost/docs is archived and doesn't point to where to go instead.

What I wanted to report is that at https://ghost.org/docs/install/ubuntu/#prerequisites, clicking the link to the "supported version"s of Node leads to a 404 page. The link works fine if opened in a new tab.

![image](https://user-images.githubusercontent.com/33569/67169193-95b38380-f36f-11e9-95b9-e31200ad374f.png)

**Comment by gargol** [comment]
Thanks for reporting @dandv! Have opened this issue internally :wink:
