### ISSUE TITLE
Safari crash when editing a staff's role.

### ISSUE THREAD

**Issue by cityhunter14** [TryGhost/Ghost#11257]
### Issue Summary

Safari crash when editing a staff's role.

---
### To Reproduce

1. In the Admin Panel, Select Manage->Staff.
2. Select a user to edit.
3. Click the role section and wait for a while, then the Safari crash.
4. Need to force quit the Safari.

This does not happen in Chrome.

---
### Technical details:

* Ghost Version: 2.37.0
* Node Version: v10.16.3
* Browser/OS: Safari v13.0.2 / macOS Mojave
* Database: mysql v5.7
* Environment:  production

**Comment by codykrieger** [comment]
@cityhunter14 Ensure you are running Safari 13.0.2 (14608.2.40.1.3)—that contains a fix for the hang when interacting with `<select>` boxes.

I suspect you are running 13.0.2 (14608.2.40.1.2) (note the “.2” vs the “.3” in the part of the version number that's in parentheses).

**Comment by cityhunter14** [comment]
> @cityhunter14 Ensure you are running Safari 13.0.2 (14608.2.40.1.3)—that contains a fix for the hang when interacting with `<select>` boxes.
> 
> I suspect you are running 13.0.2 (14608.2.40.1.2) (note the “.2” vs the “.3” in the part of the version number that's in parentheses, which denotes the WebKit version).

yes, you are right. I was running 13.0.2(14608.2.40.1.2).
Now, I updated the safari to 13.0.2(14608.2.40.1.3) and the problem has gone. 
Thank you for answering and I am closing this issue.
