### ISSUE TITLE
The /admin route gives a 404 error on V3.0

### ISSUE THREAD

**Issue by darrenmhill** [TryGhost/Ghost#11267]
Welcome to Ghost's GitHub repo! 👋🎉

We use GitHub only for bug reports 🐛

Anything else should be posted to https://forum.ghost.org 👫

🚨For support, help & questions use https://forum.ghost.org/c/help
💡For feature requests & ideas you can post and vote on https://forum.ghost.org/c/Ideas

If your issue is with Ghost CLI, please report it on the CLI repo ➡️ https://github.com/TryGhost/Ghost-CLI/issues/new.

### Issue Summary

A summary of the issue and the browser/OS environment in which it occurs.

### To Reproduce

1. This is the first step
2. This is the second step, etc.

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

### Technical details:

* Ghost Version:
* Node Version:
* Browser/OS:
* Database:

**Comment by allouis** [comment]
Hey! This is expected behaviour in 3.x :grinning: 

Previously the `/admin` route was a redirect to `/ghost` - which is where the admin has always lived - we've since removed the redirect as we're working toward a separation of the admin and the frontend.

You can still administer your site from `/ghost` :relaxed:

**Comment by darrenmhill** [comment]
Fair enough

**Comment by kopax** [comment]
I can't reach the `webhooks` api, but `site` is working, is it related ? I use `/ghost/api/v3/admin/webhooks` and `/ghost/api/v3/admin/site`:

```java
public interface GhostBlogAdminApiService {

    @Headers({
            "Accept: application/json; charset=utf-8",
            "Content-Type: application/json; charset=utf-8",
    })
    @GET("site")
    Call<GhostResponse.Admin.Site> getSite();

    @Headers({
            "Accept: application/json; charset=utf-8",
            "Content-Type: application/json; charset=utf-8",
    })
    @GET("webooks")
    Call<GhostResponse.Admin.Webhooks> getWebhooks();
}
```
