### ISSUE TITLE
Incorrect body class on page (Ghost V3)

### ISSUE THREAD

**Issue by danymill** [TryGhost/Ghost#11262]
On pages {{body_class}} returns `post-template` as class instead of `page-template`.

OS: Mac OS X, v10.15
Node Version: v10.16.0
Ghost-CLI Version: 1.12.0
Ghost Version: 3.0.0

**Comment by gargol** [comment]
Confirming this behavior in v3.0.0. The bug is also there when API v2 is configured in the theme.
