### ISSUE TITLE
RSS feed contains unpublished posts

### ISSUE THREAD

**Issue by amo13** [TryGhost/Ghost#11266]
I just noticed that when I use the RSS feed button on the top right corner of my Ghost page (casper theme), on feedly.com I see posts that I did not publish (yet) and even a post that have already deleted in the past. I also seem to miss a published post.
You can check if out for yourself: 
Ghost: https://adaptief.de
Feedly: https://feedly.com/i/subscription/feed/http://adaptief.de/rss/

### Technical details:

* Ghost Version: 3.0.0
* Database: MariaDB (MYSQL)

**Comment by gargol** [comment]
Hi @amo13! Have quickly compared what's returned in your site's RSS https://adaptief.de/rss/ with the contents displayed on the main page and didn't spot anything. Do you have some particular post(s) in mind? 

It would be best if you could get a reproducible scenario for the "leak" to happen. Cheers!

**Comment by amo13** [comment]
Thanks for your reply!
You are right about adaptief.de/rss, but how is it possible then that [feedly](https://feedly.com/i/subscription/feed/http://adaptief.de/rss/) lists unpublished posts like "Adaptief altes set 2017" at the bottom? 
This feedly page is where I get when I click the RSS logo in the top right of the home page for my ghost blog.

**Comment by grantwinney** [comment]
Just a drive-by commenter here... any chance you published the post at one point, even very briefly, and then unpublished it again? Feedly may have "seen" it before you unpublished it.

I had to re-setup Ghost last month and then migrate my posts from the old instance to the new. For a few minutes, the default "welcome" posts that get installed with Ghost were visible, before I deleted them. When I view my feed on Feedly, those welcome posts are visible, although they lead to 404's now.

**Comment by amo13** [comment]
Yes, the unpublished posts have been published at some point, but that's a long time ago already... They still appear even if I hit "refresh" on freedly. And even that "refresh" on feedly does not make the missing post (called "kassel-berlin-diplomatie") appear in the list. 
So maybe feedly is serving cached content _and_ the refresh button on their site does not work? That could explain this strange RSS reading on feedly, but it still sounds odd...

**Comment by grantwinney** [comment]
It seems weirder to me that Feedly wouldn't have picked up a _published_ post, than that they wouldn't clear out unpublished posts.

That missed post doesn't show in your RSS feed anymore since it's older, but it seems likely your feed _did_ include it and that Feedly is to blame somehow. That's just a guess though, and may be wrong.

I wonder what the point of that "Refresh" button even is? It doesn't seem to actually refresh the list to match what's currently in your RSS feed, like _"Unsere Fans lieben den Brave-Browser!"_.

**Comment by gargol** [comment]
Good thinking @grantwinney. Based on this:
> Yes, the unpublished posts have been published at some point, but that's a long time ago already... 

I'm assuming it's Feedly's fault as we haven't spotted any similar leaks like this before. If you'd be able to reproduce a behavior where **unpublished** post appears in the RSS I'd be happy to reopen & dig deeper into this :wink:
