### ISSUE TITLE
Special characters double escaped in titles/descriptions

### ISSUE THREAD

**Issue by Cherry** [TryGhost/Ghost#11274]
### Issue Summary

Page titles/other tags are seemingly double escaped, resulting in text like `3D2D Textscreens - Garry&#x27;s Mod Workshop Addon` in page titles/OG tags.

### To Reproduce

1. Create a page using the latest (3.0.0) Ghost Version
2. Set the title/description to include a special character like `'`
3. Check the resulting `<title>`, `og:title`, `og:description` etc. tags.

The same is also true for tag pages, such as https://jross.me/tag/garrys-mod/. The tag is `Garry's Mod` and is displayed appropriately in posts/pages and on my tag cloud, but on the tag's page, it displays as `Garry&#x27;s Mod`, including the `<title>` etc. tags as per before. My theme is just using `{{tag.name}}` here, but as it affects the `title` tags too which aren't in my control, it appears to be a Ghost issue.

### Technical details:

I'm using the paid hosted version of Ghost(Pro). https://jross.me/3d2d-textscreens/ is an example page where this occurs.

* Ghost Version: 3.0.0
* Node Version: Unknown to me - controlled by hosted Ghost(Pro) platform
* Browser/OS: Chrome 78, Windows 10
* Database: MySQL

**Comment by kevinansfield** [comment]
@Cherry there is no double-escaping happening here for the `<title>`, `og:title`, etc data as `&#x27;` is the html-entity (specified in hex) for the apostrophe character and is valid as per the html and ld+json specs.

The display of the title in the tag page is being double escaped however.

**Comment by kevinansfield** [comment]
@Cherry I'm not able to reproduce this and viewing the output directly from your Ghost instance using `curl https://jamesross.ghost.io/tag/garrys-mod/` shows the output is correct.

I suggest you look at whatever system you are using to simulate a custom Ghost(Pro) domain and/or any non-standard caching you have in place. If you need any specific Ghost(Pro) support please reach out to support@ghost.org.
