### ISSUE TITLE
Issue with public {{excerpt}} when post is set 'members' or 'paid-members'

### ISSUE THREAD

**Issue by fueko** [TryGhost/Ghost#11277]
### Issue Summary

{{excerpt}} helper is publicly not available when the post is set 'members' or 'paid-members'

### To Reproduce

Use this code in post.hbs file:
```
{{#if access}}
{{content}}
{{else}}
{{excerpt}}
{{/if}}
```
Set post as 'members' or 'paid-members'.

If the post's {(custom_excerpt}} property is set - works fine.

### Technical details:

* Ghost Version: 3.0
* Node Version: 10.16.3
* Browser/OS: all
* Database: sqlite3

**Comment by allouis** [comment]
Hey! The `excerpt` helper requires all of the html to generate the excerpt - as it is dynamic in size! This is currently expected behaviour - but we are thinking about how we can generate the `excerpt` at the API level so that we can send just that down.

**Comment by gargol** [comment]
> can generate the excerpt at the API level so that we can send just that down.

@allouis just double checked on this one as I remember seeing this field in responses when working on content gating :grimacing: We do have `excerpt` field generated on the API level even when `memebers`/`paid-members` are enabled, so the fix here should be rather straight forward and similar to this one for [{{reading_time}}](https://github.com/TryGhost/Ghost-SDK/commit/f9a7d88776b540f1cdf5de3f49905da9517738f3)

> it is dynamic in size

This bit would need a little more discussion, but I think the default behavior could limit the `{{excerpt}}` output to whatever is available under `post.excerpt` if `post.html` is missing :thinking:

**Comment by allouis** [comment]
@matthanley Unsure if this should have been closed or not :thinking:

**Comment by matthanley** [comment]
I've allowed this to close because we're tracking similar functionality internally that needs shaping. Right now we have no way of generating a public excerpt from gated content because we can't assume that _any_ of it should be public.
