### ISSUE TITLE
Pages have an `amphtml` link that 404s

### ISSUE THREAD

**Issue by Cherry** [TryGhost/Ghost#11273]
### Issue Summary

With AMP enabled, pages (not-posts) have an `ampthml` link injected, but browsing to the AMP version of these pages results in a 404. AMP on posts still works as expected.

### To Reproduce

1. Create a page using the latest (3.0.0) Ghost Version
2. Check the page source for an `amphtml` link tag
3. Browse to the AMP variant to see a 404

The page should either not have an `amphtml` link injected, or it should not 404. I was first alerted to this issue when my Google Search Console reported AMP errors on my site.

### Technical details:

I'm using the paid hosted version of Ghost(Pro). https://jross.me/3d2d-textscreens/ is an example page where this occurs.

* Ghost Version: 3.0.0
* Node Version: Unknown to me - controlled by hosted Ghost(Pro) platform
* Browser/OS: Chrome 78, Windows 10
* Database: MySQL

**Comment by AileenCGN** [comment]
@gargol This is maybe related to https://github.com/TryGhost/Ghost/issues/11262 ?

**Comment by AileenCGN** [comment]
Pages should definitely **not** have an `amphtml` property. Only posts should have it.

**Comment by gargol** [comment]
Confirming @AileenCGN clue about #11262 being related, good catch!
@Cherry thanks for the report! The fix for this issue is already in master and we plan to release a new version tomorrow :wink: 

Closing this issue as it's been fixed in master already.
