### ISSUE TITLE
GET /posts fails with `?limit=all` parameter on SQLite instances

### ISSUE THREAD

**Issue by naz** [TryGhost/Ghost#11303]
### Issue Summary

The issue happens when running Ghost 3.0 on the SQLite database with the number of posts having `posts_meta` records that exceed 999. 

When issuing the following Admin API request (same works for Content API):
```
GET /ghost/api/v3/admin/posts/?limit=all
```

It fails with 400, `type: BadRequestError` and `code: SQLITE_ERROR`.

In the internal logs following error show up:
```
Error: SQLITE_ERROR: too many SQL variables
```
It's a direct result of `SELECT` statement that has all posts listed in `IN` clause when the max limit for SQL parameters is [999](https://sqlite.org/limits.html#max_variable_number). 

Relevant discussion and small workaround the issue: https://github.com/TryGhost/Ghost/pull/11300.

### To Reproduce

1. Set up an instance on SQLite database
2. Create 1000 posts with `meta_*` entries
3. Call `GET /posts` with `?limit=all` parameter (e.g. through Ghost-SDK with following script https://gist.github.com/gargol/b71619cb04d35e0de97a91f8b41f95a0)

The expectation would be having all posts fetched with no error.

### Technical details:

* Ghost Version: 3.0.0
* Node Version: v10.15.1
* Database: SQLite 3.22.0
* OS: Ubuntu 18.04

**Comment by ErisDS** [comment]
Closing this against https://github.com/TryGhost/Ghost/issues/12032 as this is now fixed in SQLite 3.32, which is soon to be the default.

The correct solution is to upgrade SQLite3
