### ISSUE TITLE
Logo in Schema is not generated as URL or ImageObject

### ISSUE THREAD

**Issue by aslamabbas** [TryGhost/Ghost#11304]
Hi Ghost team,

Having issues with schema generation. 

Steps to reproduce:
1) Visit this link to see the error - https://search.google.com/structured-data/testing-tool/u/0/#url=https%3A%2F%2Fcollect.chat%2Fblog%2Fsee-how-this-web-scraping-platform-datahut-is-collecting-their-leads%2F

You can see the schema error for the Publication Logo as "A value for the url field is required". 

2) Resolution of image used for Publication Logo is 600x135 - https://collect.chat/blog/content/images/2019/10/600x135.png 

Ghost version is 3.0.1

**Comment by gargol** [comment]
Initially reported at https://forum.ghost.org/t/schema-error-a-value-for-the-url-field-is-required/9723

**Comment by uksitebuilder** [comment]
Still a problem with this

**Comment by aileen** [comment]
This was fixed, and therefore closed, but the fix had an issue with duplicating the `url` property.
The fix got reverted with https://github.com/tryghost/ghost/commit/7ac614030d80a3c172a117f44b7736dec197dba2 which legitimates this issue to be re-opened.

The correct fix would be a mix of both. Will open a PR in a min.
