### ISSUE TITLE
HTML embeds do not work and are throwing an error

### ISSUE THREAD

**Issue by ilovecats516** [TryGhost/Ghost#11310]
### Issue Summary

HTML embeds do not show up.

### To Reproduce

1. Create a new post
2. Create a new embed and add code

Console reports `Refused to display 'https://trends.google.com/trends/' in a frame because it set 'X-Frame-Options' to 'SAMEORIGIN'.` (Google Trends is what I'm trying to embed.)

### Technical details:

* Ghost Version: 3.0.2
* Node Version: Unsure
* Browser/OS: Safari 13.0.2, MacOS Catalina 10.15
* Database: mysql

**Comment by rishabhgrg** [comment]
Hey @ilovecats516, I am unable to reproduce the issue with generic google trends embed script, and from the console report this looks more of an issue with code being used in embed. I'd recommend posting this on our [forum](https://forum.ghost.org/) as its a great place to get community support for common issues, plus it helps create a central location for searching problems/solutions. 😄

**Comment by ilovecats516** [comment]
That's odd, I used a Google Trends script as well. I'll try another browser and see if that fixes the problem. If you could, what script did you use exactly?

**Comment by ilovecats516** [comment]
Update: It seems to be a Safari issue. Thank you for your time.
