### ISSUE TITLE
Meta og:description and twitter:description use generated excerpt instead of meta description

### ISSUE THREAD

**Issue by octave** [TryGhost/Ghost#11317]
Meta og:description and twitter:description use generated excerpt by default instead of meta description. The Facebook and Twitter card preview display the meta description properly but in the article page it uses a generated excerpt instead. Screenshots attached.

### Technical details:

* Ghost Version: 3.0.2
* Node Version: 10.17

![Screen Shot 2019-11-02 at 6 38 52 PM](https://user-images.githubusercontent.com/343/68079086-c1d3f900-fda0-11e9-96aa-30399e4f1e1c.png)
![Screen Shot 2019-11-02 at 6 39 19 PM](https://user-images.githubusercontent.com/343/68079088-c4cee980-fda0-11e9-9d64-cc6b6d7cf960.png)

**Comment by mskian** [comment]
Me too already reported still not fixed

already 2 issue ticket's are opened

- #10591 
- #10387

**Comment by octave** [comment]
@mskian What can we do to help fix it?

**Comment by gargol** [comment]
Thanks for the reports guys! This was a new issue that was a consequence of 3.0 refactorings. Will go out as a part of the release today (v3.0.3)

**Comment by octave** [comment]
@gargol Still have the issue with 3.0.3 :(

**Comment by gargol** [comment]
@octave hm. Could you please give a step by step way to reproduce this, maybe I'm missing something? I was able to reproduce this on 'pages' yesterday and confirmed a fix. Also, please include the details of which API version your theme is connected to.

**Comment by mskian** [comment]
@gargol same still having the issue
check this - https://github.com/TryGhost/Ghost/issues/10387#issuecomment-460951040
Forum post - https://forum.ghost.org/t/social-meta-description-issue/5230/4

**Comment by octave** [comment]
@gargol If I create a post with no excerpt but add a meta description. Then og:description and twitter:description meta tags use a generated excerpt instead of the meta description.

My theme uses api v3. I tried with latest Casper (3.0.3) and same issue.
