### ISSUE TITLE
Integrations page in dark mode is missing transparent icons.

### ISSUE THREAD

**Issue by aidenmitchell** [TryGhost/Ghost#11342]
### Issue Summary

Integrations page in dark mode is missing transparent icons.

### To Reproduce

1. Switch to Dark Mode
2. Go to the Integrations tab

Zapier and AMP icons are not transparent and have a white background.
Similar to #10161

### Technical details:

* Ghost Version: 3.0.2
* Node Version: Unsure
* Browser/OS: Safari, MacOS Catalina
* Database: mysql

![Screen Shot 2019-11-05 at 7 16 35 PM](https://user-images.githubusercontent.com/30846409/68265595-5d63a480-0001-11ea-8f5e-14387e3169db.png)

**Comment by ilovecats516** [comment]
Update: Also the More ellipsis icon has a darker shade of black than the rest of the UI.

**Comment by umuur** [comment]
can I take this?

**Comment by ilovecats516** [comment]
Still hasn't been fixed as of 3.11.0

**Comment by peterzimon** [comment]
Fixed with https://github.com/TryGhost/Ghost-Admin/commit/00b7ec2874722246f65207e45c49bdfa562c649f
