### ISSUE TITLE
Meta titles missing in 'page' pages

### ISSUE THREAD

**Issue by gargol** [TryGhost/Ghost#11357]
### Issue Summary

Page First reported in https://forum.ghost.org/t/why-do-pages-not-have-their-meta-titles-in-ghost-casper-3-0/10100;

### To Reproduce

1. Create a 'page' and publish it
2. Visit the page frontend and the meta title is set to whatever is configured as a 'site title'

The expected title is page's title, not a generic site-wide title. 

The bug is originating from this change: https://github.com/TryGhost/Ghost/commit/cbca480b97c747c051b9e90b83d7100968636c5f. The `if` condition was confused with general v0.1 format but was there because of legacy data shape described in detail here: https://github.com/TryGhost/Ghost/issues/10042  

### Technical details:

* Ghost Version: 3.02
* Node Version: v10
* Browser/OS: Chrome	
* Database: MySQL

**Comment by kevinansfield** [comment]
This should be fixed in https://github.com/TryGhost/Ghost/pull/11068 too, there are cleaned up tests for title behaviour there https://github.com/TryGhost/Ghost/blob/12c0273ea1b2ef970b5333914cc3a47cb5587345/core/test/unit/data/meta/title_spec.js#L63-L103
