### ISSUE TITLE
Outdated list of supported webhook events

### ISSUE THREAD

**Issue by dandv** [TryGhost/Ghost#11384]
https://ghost.org/docs/api/v3/webhooks/ says

> Currently Ghost has support for below 2 events [sic] 

but I see a lot more in the dropdown:

![image](https://user-images.githubusercontent.com/33569/68564557-f2f69e00-041e-11ea-9ed8-9bd0ea0d5110.png)

**Comment by gargol** [comment]
Thanks for bringing up @dandv! I have passed the info and the docs will be reviewed shortly. Closing the issue for now as we don't track non-Ghost core issues her :smiley:

**Comment by dandv** [comment]
Thanks for the quick reply! Is there a better repo for docs-related issues?

**Comment by gargol** [comment]
At the moment we don't have a public repo. We will definitely point to one in the docs once there will be :)
