### ISSUE TITLE
Twitter/Opengraph metadata falls back to excerpt before metaDescription

### ISSUE THREAD

**Issue by jloh** [TryGhost/Ghost#11403]
### Issue Summary

At the moment how structured data is generated `metaDescription` is used as the fall back for `excerpt` which always exists. This means that if you set a custom Meta Description via the Meta tab on a post, Twitter and Opengraph data don't fall back and use this data, instead they use the excerpt.

https://github.com/TryGhost/Ghost/blob/fb7afd1672e8237c86dd7cc12ba37984a6c2f0bc/core/frontend/meta/structured_data.js#L28

Ghost Admin also shows the custom excerpt, its just the front end that doesn't.

### To Reproduce

1. Create a random post and set alternative data in the 'Meta Description' field via the Meta tab
1. Go to the Twitter or Facebook cards and see the preview in Ghost Admin shows your custom excerpt
1. View post and see that `og:description` and `twitter:description` use the default value of `metaData.excerpt`

### Technical details:

3.0.3

**Comment by kevinansfield** [comment]
This should be resolved by https://github.com/TryGhost/Ghost/pull/11068 that is due to be updated and merged shortly - you can also see the table of intended fallbacks for each meta/og/twitter property there.

**Comment by jloh** [comment]
I just noticed the `CASE` statement above this code, but I'm not sure this holds true still?

https://github.com/TryGhost/Ghost/blob/fb7afd1672e8237c86dd7cc12ba37984a6c2f0bc/core/frontend/meta/structured_data.js#L15-L18

**Comment by jloh** [comment]
Thanks Kevin! ❤️
