### ISSUE TITLE
Emojis within text causes lag when editing

### ISSUE THREAD

**Issue by frantzypants** [TryGhost/Ghost#11412]
### Issue Summary

In some paragraphs, where an emoji is used as the first character, going back to edit the published post causes a lag when editing those specific paragraphs. The lag is about 10 seconds after typing.

### To Reproduce

1. Insert an emoji as the first character in multiple paragraphs of a post
2. Save/Publish the post
3. Return to post to edit content.

### Technical details:

* Ghost Version: v3.0.3
* Browser/OS: Any latest
* Environment: production or development
* Database: sqlite3

**Comment by polarathene** [comment]
Not a Ghost user, but did you actually confirm it's an issue with each OS? Is Ghost using it's own emoji(faked with images) or the system/browser provided emoji?(actual emoji fonts)

On Linux, there is a lot more control/flexibility regarding emoji handling, and I have noticed a similar issue in browsers when messing with my font configuration to improve the emoji experience in my linux distro. If you're on Linux, even if you have not touched your font config, the distro itself might be different from others, which could cause such a problem. 

Unlikely to be an issue on Windows or macOS afaik, assuming Ghost is using native emoji fonts, if they're using images, then it's probably a Ghost problem with how they're parsing text and choosing to render it.

**Comment by khairihz** [comment]
I tried to reproduce this on a local environment, but I didn't find any issue, can you tell us more information about your environment setup? 

And what kind of Emoji ? is it an Os Emoji or a custom one?

**Comment by kevinansfield** [comment]
We're using native OS emojis. If I'm remembering correctly from when I first looked at this I believe the issue is to do with our markdown text expansions, they use regexes to match text and emoji's at the beginning of the section cause them to have performance problems.
