### ISSUE TITLE
Sync problem of themes when deploying with docker in multiple nodes.

### ISSUE THREAD

**Issue by HADB** [TryGhost/Ghost#11425]
### Issue Summary

My blog is deploying using docker in 2 nodes and they share the same volume mounted on "/var/lib/ghost/content".

I upgraded my ghost blog from 2.x to 3.1.0 today and found out that it only affects one node when I delete or active a theme from "Settings/Design/Installed Themes" which causes two nodes have different active themes.

It's wired and never happened in version 2.x. 

It seems themes list and activation status are saved out of "/var/lib/ghost/content".

Am I missing something when upgrade from 2.x or is this a bug of version 3.x?

### Technical details:

* Ghost Version: 3.1.0
* Browser/OS: Chrome, Ghost desktop app

**Comment by kevinansfield** [comment]
https://ghost.org/faq/clustering-sharding-multi-server/

> Ghost does not support load-balanced clustering or multi-server setups of any description, there should only be one Ghost instance per site.

It's not been supported in any version of Ghost. It may have _looked_ like you had a working setup across 2 nodes but I can guarantee that there were maybe unseen problems, especially if you are editing frequently or using Zapier or other API integrations.
