### ISSUE TITLE
Why not remove `{{@ labs.subscribers}` from the v3.0 API documentation?

### ISSUE THREAD

**Issue by liby** [TryGhost/Ghost#11435]
- You indicated in the [Update description](https://ghost.org/faq/upgrades/#ghost-3-0) that the Subscribers feature has been replaced.

    ![image](https://user-images.githubusercontent.com/38807139/70196823-e1b26000-1744-11ea-8160-7a0f6bea4281.png)

- Why the [API](https://ghost.org/docs/api/v3/handlebars-themes/helpers/labs/) documentation is not updated?

    ![image](https://user-images.githubusercontent.com/38807139/70196605-3d301e00-1744-11ea-8824-68ab613c67bd.png)

**Comment by gargol** [comment]
Hi @liby the subscriber feature has been removed indeed and the leftover in this topic has been brought up on forum recently as well - https://forum.ghost.org/t/ghost-subscribers-members-in-v3/10518/3?u=gargol. We will be updating the documentation soon, just haven't had time to do so yet.

**Comment by dschwertfeger** [comment]
I just stumbled over this as well and was confused: https://ghost.org/docs/themes/helpers/labs/.  Same example as in the screenshot above. iMaybe it's time to update the documentation :)

**Comment by liby** [comment]
@dschwertfeger 
Uh, sounds regrettable. I don't know if any of them are pushing for document updates, maybe you can go to the community and ask.
