### ISSUE TITLE
Minor regression: darkmode input bg color

### ISSUE THREAD

**Issue by JohnONolan** [TryGhost/Ghost#11445]
Ghost 3.1.1

![image](https://user-images.githubusercontent.com/120485/70860543-945c9c80-1f55-11ea-95b2-6e7b35dd2017.png)

**Comment by JohnONolan** [comment]
cal too
![image](https://user-images.githubusercontent.com/120485/70867153-a44f9d00-1fa4-11ea-9464-cf4bb31fd173.png)

**Comment by peterzimon** [comment]
Fixed with https://github.com/TryGhost/Ghost-Admin/commit/85518b3b6aecb98dfbaf888d1cf41c410aa48845
