### ISSUE TITLE
Can I use koenig-editor only for my project

### ISSUE THREAD

**Issue by deepaksisodiya** [TryGhost/Ghost#11467]
Can I use koenig-editor only for my project?
like tiptap, slate.js and draft.js

**Comment by allouis** [comment]
As long as you abide by the license agreement you can :relaxed: 

https://github.com/TryGhost/Koenig/blob/master/LICENSE
https://github.com/TryGhost/Ghost/blob/master/LICENSE
https://github.com/TryGhost/Ghost-Admin/blob/master/LICENSE

**Comment by anhnv07** [comment]
please, Are there any docs that guide how to integrate into my project?

**Comment by anhnv07** [comment]
Thank you for your support, can I copy the admin module into my project and use it as a separate package?

**Comment by anhnv07** [comment]
I'm using Next.js and after integrating the KoenigLexicalEditor component, I'm encountering this error. Do you have any solutions to fix it? Please help me!
<img width="907" alt="Screenshot 2024-03-21 at 09 51 07" src="https://github.com/TryGhost/Ghost/assets/80376994/b08950fc-88b9-4cc6-b315-618961fde3cc">
