### ISSUE TITLE
routes.yaml ignores internal tags for filter

### ISSUE THREAD

**Issue by jeremy-seipelt** [TryGhost/Ghost#11465]
### Issue Summary

Collections seem to ignore internal tags, or I falsly use them inside my routes.yaml.

Example yaml
```
routes:

collections:
  /blog/:
    permalink:    /blog/{slug}/
    template:     index
    filter:       'tag:blog'

  /testimonial/:
    permalink:    /testimonial/{slug}/
    template:     index
    filter:       'tag:#program'

  /:
    permalink:    /
    template:     index
```
### To Reproduce

1. Create Post with an internal Tag 
2. Build collection using routes yaml and the internal tag
3. See that the filter rule for the tag is ignored

Expected behaviour:
Filter rule should apply and build the corresponding permalinks for the site and the sitemap.

### Technical details:

* Ghost Version: ghost@3.0.0
* Node Version: v10.15.3
* Browser/OS:Firefox Developer Edition
* Database:MYSQL

**Comment by rozhok** [comment]
@jeremy-seipelt looks like Ghost filters by tags using their slugs, not names. So make sure your internal tag have `hash-program` slug and then use it in filter like `'tag:hash-program'`
I've spent a good 20 mins to figure our it.
