### ISSUE TITLE
IME Bug: Ghost suffering IME bug for 2 years and Never Fix it

### ISSUE THREAD

**Issue by wuliaopage** [TryGhost/Ghost#11460]
### Bug summery
Don't be surprised. I'm referring to https://github.com/TryGhost/Ghost/issues/9801

#9801 is a serious bug for all IME(input method editor) user. The first character in each paragraph will not be recognized when typing non-latin language such as Chinese, Japanese, Korean in Ghost.
 
This has been seriously damaged Ghost user experience. For those people in Asian, this bug makes Ghost **an unuseable platform**, as no one can easily, smoothly type out a single paragraph. 

### Bug history
This bug has been existing for more than 2 years and neither Ghost nor its editor mobiledoc's maintainer fixed it. Issues related to this bug have been proposed many times, as listed below.
https://github.com/bustle/mobiledoc-kit/issues/548
https://github.com/bustle/mobiledoc-kit/issues/589
https://github.com/TryGhost/Ghost/issues/9801

A PR has been proposed one year ago, neither Ghost or mobiledoc merge it!! why???
PR: https://github.com/bustle/mobiledoc-kit/pull/661
https://github.com/soulteary/mobiledoc-kit

### Mobiledoc reaction
Ghost direct user to discuss this bug in mobiledoc community and push them to fix this bug.

**BUT,** I have emailed all maintainers in mobiledoc team to push them merge that PR, also post messages in the community, leave messages in developer's twitter. After one month the only one replied me is an auto-reply email from a passed away developer. I'm sorry for that. But it seems mobiledoc has become a depercated or at least partially deprecated project. 

**Ghost should not depend on a deprecated editor!!**
**or Please Fix this bug by yourself!!**

Some people may not know what exactly this bug is, please look at the following issue.

## Issue Summary
non-latin languages input problem in koenig editor

![image](https://user-images.githubusercontent.com/4370770/44322775-99a0f880-a481-11e8-9b13-083bfed63679.gif)

As the screen recording above shown, I want to input 你好 using Chinese Pinyin Input method of Mac OS X on the start of line，I type nihao，then got i好n.

The first typed n is inserted after cursor.

## To Reproduce
1. Add a Chinese or Japanese or Korean language in your system
2. Switch your input language to Chinese or Japanese or Korean
3. Open Ghost, start a new post
4. Type some letter like nihao, or anything, you can find this bug

This bug also can be reproduced on https://bustle.github.io/mobiledoc-kit/demo/

**Comment by DaZiYuan** [comment]
![jonbb1VvVs](https://user-images.githubusercontent.com/80653/70874429-0cc26c80-1fed-11ea-9fba-031eb348bb90.gif)

same issue...

**Comment by Blakeatuk** [comment]
we are still suffering

**Comment by kevinansfield** [comment]
> The first character in each paragraph will not be recognized when typing non-latin language such as Chinese, Japanese, Korean in Ghost.

The proposed PR does not fix this issue, it's entirely separate to the IME input problem and much effort has been put in behind the scenes to resolve it but there is a deeper rework of some of mobiledoc's internals required.

We are aware of the issue but harassment and bullying is not the way to go about getting help. Closing as a violation of our code of conduct https://ghost.org/conduct/.
