### ISSUE TITLE
Casper 3 puts `{ post.custom_excerpt}` in the page. Ghost doesn't render that content in the RSS feed or amp template.

### ISSUE THREAD

**Issue by jessehouwing** [TryGhost/Ghost#11490]
### Issue Summary

The new Casper theme puts the `{post.custom_excerpt}` in the post template. The `amp.hbs` and the rss feed don't. Customizing `amp.hbs` was easy, but since there is no `rss.hbs` with the default template, it's not easy to fix that.
 
### To Reproduce

This was introduced with Casper 3.0.It may be a Casper bug or an unwanted use of `{post.custom_excerpt}`. But at the moment these 2 are conflicting.

### Technical details:

* Ghost Version: 3
* Casper Version: 3

**Comment by gargol** [comment]
Hi @jessehouwing :wave: Can't really follow what are you referring to by `{post.exerpt}` here. There is no direct output of `{post.excerpt}` anywhere in the Casper theme, `post.hbs` template only outputs `{{custom_excerpt}}` if anything related to excerpts :) Are you running on a customized version of Casper? Please provide some more details on how to reproduce the problem you are seeing.

**Comment by jessehouwing** [comment]
You're totally right. Composed this item on my phone.

**Comment by gargol** [comment]
Ok. In this case, I think it's not a bug but rather intentional behavior of Ghost and how it outputs AMP and RSS information. Would suggest opening a topic on the forum for feature changes like this :wink: Happy Holidays!

**Comment by jessehouwing** [comment]
I think it was an intentional decision, until ghost 3 came about. Now it feels like an unintentional oversight or bug.

**Comment by jessehouwing** [comment]
Cross referencing: https://github.com/TryGhost/Casper/issues/645
