### ISSUE TITLE
can't use https in this way

### ISSUE THREAD

**Issue by ghostry** [TryGhost/Ghost#11493]
start docker
```
docker run -it --rm \
    --name ghost \
    -e url=http://en.blog.ghostry.cn \
    -p 2368:2368 \
    ghost:3-alpine
```
config https proxy in apache to http://172.17.0.1:2368
than i can't change http://en.blog.ghostry.cn to https://en.blog.ghostry.cn in settings->design

and if i use other way 
start docker
```
docker run -it --rm \
    --name ghost \
    -e url=https://en.blog.ghostry.cn \
    -p 2368:2368 \
    ghost:3-alpine
```
config https proxy in apache to http://172.17.0.1:2368
than i have ERR_TOO_MANY_REDIRECTS

and if config https proxy in apache to https://172.17.0.1:2368
i have the other error. Error during SSL Handshake with remote server

**Comment by ghostry** [comment]
I think it's a bug, you guys think it's a support-request.
Ok i will give up using ghost

**Comment by limosin** [comment]
Faced the same. I agree with @ghostry that its a bit messed up. The behavior must be coherent both in case of `http` and `https`. I don't wish to add ssl to ghost, instead I want to have a Loadbalancer with the ssl certificates. I don't want to use another nginx instance, but instead have my LB do the redirection. `http` or `https` - the instance should be accessible on localhost.

**Comment by ErisDS** [comment]
That is _exactly_ what a reverse proxy is for. Going to close and lock this with a link to https://github.com/TryGhost/Ghost/issues/2796#issuecomment-669920971.
