### ISSUE TITLE
Env variables set but "No transport method defined"

### ISSUE THREAD

**Issue by LM1LC3N7** [TryGhost/Ghost#11508]
### Issue Summary

I use environment variables into my docker-compose file to configure Ghost, as explained [on the documentation](https://ghost.org/docs/concepts/config/#section-running-ghost-with-config-env-variables).

```
NODE_ENV=production
url=https://myblog.example.tld
server__host=0.0.0.0
server__port=2368

database__client=mysql
database__connection__host=ghost-db
database__connection__user=ghost
database__connection__database=ghost
database__debug=false
database__connection__password=SECRET

mail__transport=STMP
mail__options__port=587
mail__options__host=smtp.example.tld
mail__options__auth__user=smtp_user
mail__options__auth__pass=smtp-pass
mail__from=myblog@example.tld

imageOptimization__resize=true
```

Database and mail configuration is set as you can see, but Ghost seems not to use the mail part.
When I click on the test button, it does not work: "Failed to send email. Reason: No transport method defined."

![image](https://user-images.githubusercontent.com/14235706/72082484-2018dd00-32f8-11ea-9fe8-aca62d3ad305.png)

![image](https://user-images.githubusercontent.com/14235706/72082503-29a24500-32f8-11ea-98f3-4392c1aa3c4a.png)

But in the "About Ghost" part, I can see "Mail" set to "SMTP":

![image](https://user-images.githubusercontent.com/14235706/72082797-a503f680-32f8-11ea-9779-cef567a66f83.png)

### To Reproduce

1. Create a Ghost container built from GitHub code
2. Start it with environment variables to configure Ghost
3. Connect to the web interface and click on "test mail" button 

### Technical details:

* Ghost Version: 3.2.0
* Node Version: 8.15.0
* Browser/OS: Firefox 72
* Database: mysql 5.5

**Comment by allouis** [comment]
You have a typo, STMP should be SMTP :relaxed:

**Comment by LM1LC3N7** [comment]
God 🤣 
Thanks it was fast as light!

**Comment by allouis** [comment]
No probs!!
