### ISSUE TITLE
route / template v 3.2.0

### ISSUE THREAD

**Issue by bjoern2610** [TryGhost/Ghost#11500]
Hallo togehter,

i set this in routes.yaml.

routes:
  /subscribe/: members/subscribe

But on open url i get this message.

Missing template subscribe.hbs for route "/subscribe/".

But template is there surley there. 
I think it must be a bug on v 3.2.0

Greetings

**Comment by Hygor** [comment]
Are you sure there's no space between the comma and the text in: `/subscribe/:  members/subscribe`?
