### ISSUE TITLE
Double spacings on copy/paste into editor (Firefox)

### ISSUE THREAD

**Issue by jaydenroberts** [TryGhost/Ghost#11519]
### Issue Summary
When copying text from a webpage and pasting into the editor, occasional double spaces are added where the original only has singles. The default Casper template then renders these double spaces in the published version.

This has been reproduced by 2 people, I have had a 3rd try and could not replicate.

- Chrome works as expected.

### To Reproduce
1. Using the second paragraph from this article as an example:  
https://www.theguardian.com/commentisfree/2019/dec/29/decade-technology-privacy-tech-backlash
Copy the text
2. Paste into a new section within the editor

### Technical details:
* Ghost Version: v3.2.0
* Browser/OS: Firefox 72.0.1/MacOS 10.15.2

**Comment by kevinansfield** [comment]
Closing as this is being tracked upstream here https://github.com/bustle/mobiledoc-kit/issues/707
