### ISSUE TITLE
ghost post show unordered list markdown as  asterisk?

### ISSUE THREAD

**Issue by inevity** [TryGhost/Ghost#11523]
### Issue Summary

A summary of the issue and the browser/OS environment in which it occurs.

### To Reproduce

1. create post have  unordered list use * or -.
2. preview ok
3. publish post
4. post show *, not markdown preview result. 
    see example: https://blog.approachai.com/test-2/

### Technical details:

* Ghost Version: 0.11.11 or 3.3
* Node Version: v10.18.1 
* Browser/OS: safari or chrome
* Database: mysql

**Comment by daviddarnes** [comment]
Hey @inevity, that's part of the design within the theme you chose. You can see an example of the bullet points here on the theme demo site: https://attila.zutrinken.com/the-editor/
