### ISSUE TITLE
Typos is getting started tutorial

### ISSUE THREAD

**Issue by jordantomax** [TryGhost/Ghost#11520]
Apologies if this is the wrong place to document this. I'm not sure if the getting started content is part of the repo.

<img width="852" alt="Screenshot 2020-01-14 14 54 31" src="https://user-images.githubusercontent.com/37018/72377885-51215500-36de-11ea-9d42-78f0ea680694.png">

### To Reproduce

1. Create a new hosted pro blog
2. Look at creating a custom theme post
3. Scroll down to bulleted list of files

**Comment by gargol** [comment]
Thanks for the report @jordansexton! It's fixed and should be working for all new Ghost installs starting with the next release :tada:

**Comment by jordantomax** [comment]
👍 Glad to help!
