### ISSUE TITLE
Changing month in datepicker updates input value but does not save the value

### ISSUE THREAD

**Issue by JonathanHolvey** [TryGhost/Ghost#11522]
### Issue Summary

When updating a post's publish date, the chosen value isn't retained after publishing the changes and refreshing the page.

### To Reproduce

Using the Ghost Docker image:

1. Run `docker run --rm -p 2368:2368 ghost:3.3.0`
2. Visit `http://localhost:2368/ghost` in a browser (I'm using Chrome)
3. Follow the steps to set up a site and owner account
4. Once logged in, select posts from the menu
5. Select any of the default posts to edit it
6. Open the post settings panel and change the publish date
7. Close the post settings panel and publish the changes using the update menu
8. Refresh the page and open the post settings menu to check the publish date

### Expected behaviour

The post should show the new publish date selected in step 6, as per the [documentation](https://ghost.org/faq/publishing-options/#change-the-publish-date).

### Observed behaviour

The post retains the original publish date after refreshing the page.

### Technical details:

* Ghost Version: 3.3.0 (Docker)
* Node Version: 12.14.1
* Browser/OS: Chrome 79.0.3945.88 on Debian 10
* Database: sqlite3

**Comment by kevinansfield** [comment]
@JonathanHolvey I'm not able to reproduce this. When you say you are changing the publish date, how are you doing that? Are you using the calendar picker or typing a date?

**Comment by kevinansfield** [comment]
Ah yes, I see what you mean now. Thanks for the explanation 🙂
