### ISSUE TITLE
Email newsletter rendering issues in Microsoft Outlook (Windows)

### ISSUE THREAD

**Issue by jaydenroberts** [TryGhost/Ghost#11536]
### Issue Summary

**Problem 1**

Native email newsletters are not wrapping text or images when viewing within Outlook for Microsoft Windows, content continues outside of the viewing pane, even when viewing the individual message in a separate window.

![Capture01](https://user-images.githubusercontent.com/6936935/72865460-daacd480-3d27-11ea-97ff-ca8cb694e6b5.JPG)
![Capture02](https://user-images.githubusercontent.com/6936935/72865461-db456b00-3d27-11ea-8d4f-e6dbb8867e83.JPG)

In comparison to Outlook for Mac

![Screen Shot 2020-01-22 at 3 06 06 pm](https://user-images.githubusercontent.com/6936935/72865779-f6fd4100-3d28-11ea-9b10-baf176324e10.png)

**Problem 2**

Outlook renders apostrophes as `&apos;`

### To Reproduce
View in Outlook for Windows

### Technical details:

* Ghost Version:  3.3.0
* Browser/OS: Microsoft Outlook (Office 365 ProPlus) v1902 Build 11328.20492
Windows 10 Pro v1903 build 18362.592

**Comment by n1n10** [comment]
Apparently this is also a problem for som users using Outlook on Mac. See the attached image where the bookmark in Outlook is way off, but it looks right in Apple Mail 
![Issues. ghost Outlook Mac](https://user-images.githubusercontent.com/45498499/74948552-c2020e00-53fc-11ea-92d9-be3a50ffc726.jpg)

**Comment by drorpoleg** [comment]
Hi,
My readers are reporting the same issue. In addition, Outlook also renders apostrophes as "&apos;" for some reason.

**Comment by krrisis** [comment]
+1

**Comment by ErisDS** [comment]
Note: I believe the apostrophe bug may be to do with some encoding issues that I've been talking to mailgun about

**Comment by matthanley** [comment]
There's a reference [here](https://webmasters.stackexchange.com/questions/12335/should-i-escape-the-apostrophe-character-with-its-html-entity-39/12358#comment170877_12358) that mentions lack of support for `&apos;` in Outlook, and to switch to `&#39;`

> if you have to support legacy browsers or writing HTML emails for Outlook then you're best sticking to `&#39;`

**Comment by greenhamsam** [comment]
Hiya! I just wanted to hop in here and say that the &apos; issue was reported by one of my readers, too. I'd love to see this fixed, please. Thanks team :)

**Comment by matthanley** [comment]
Hey @greenhamsam! The `&apos;` issue should be fixed in the next release 👍

**Comment by daniellockyer** [comment]
@greenhamsam Hey! :wave: We just released 3.29.2 with a fix for the `&apos;` issue, so please update using Ghost-CLI :slightly_smiling_face:
