### ISSUE TITLE
gallery.js: Wrong image sizes in attributes

### ISSUE THREAD

**Issue by tobiaseichert** [TryGhost/Ghost#11548]
### Issue Summary

A summary of the issue and the browser/OS environment in which it occurs.

### To Reproduce

1. Create a new post. Inside the post, pull an image (preferably > 2000x1500) to the gallery card, the correct image dimensions are inserted as seen in the browser developer tools.
2. Save the post and publish it.
3. Have a look at the published content. The original image has been replaced by an optimised version (2000x1500); however the image width and height attributes still carry the dimensions of the original image. This may lead to problems when using additional gallery related libraries like a lightbox.

### Technical details:

* Ghost Version: 3.2.0
* Node Version: 10.18.1
* Browser/OS:
* Database: MySQL

![image_dimensions](https://user-images.githubusercontent.com/29119234/73270920-f7da1b00-41df-11ea-8540-de8f75717022.png)

**Comment by jdcauley** [comment]
Can some one assign me I can look at this week after next?

**Comment by ErisDS** [comment]
I can and have reopened this.
