### ISSUE TITLE
Tag overview: a tag shows "x posts"  even though that tag is in pages only

### ISSUE THREAD

**Issue by tvld** [TryGhost/Ghost#11554]
Issue:
1 - tag overview table shows  "8 **posts**" but I don't have post with that tag only **pages**
2 - clicking on that "8 posts" shows empty page

Expected:
1 - Next to "0 posts" it also should show "8 pages" in a second column in the table. 
2 - Clicking on the "8 pages" should show the pages with that tag.

![Screenshot from 2020-01-29 17-23-01](https://user-images.githubusercontent.com/986182/73375767-976cdb80-42bc-11ea-9deb-d266c789922a.png)

**Comment by gargol** [comment]
Thanks for the report @tvld
