### ISSUE TITLE
Pages do not show CTA (banner) upon changes to "Post Access"

### ISSUE THREAD

**Issue by pateskinasy** [TryGhost/Ghost#11575]
### Issue Summary

Pages do not respond to changes to "Post Access", maybe because they are "Post" and not Page" access 😊

### To Reproduce

1. Install Lyra, Turn ON and set up Members in Labs
2. Create a page
3. Change "Post access" for the page from public to members-only or paid-members-only
4. The page continues to be public

### Technical details:

* Ghost Version: 3.5.0
* Node Version: 10.19
* Browser/OS: Brave/Chrome/Safari/Opera
* Database: MySQL

**Comment by gargol** [comment]
Hi @pateskinasy , I'm not sure what you mean by `The page continues to be public`. The page is supposed to stay accessible to the public, but it's contents should not be visible (just like for the posts). I've tested it quickly and seems to work as expected. I'll close this issue for now, but feel free to reopen in case I'm misunderstanding something :smiley:

**Comment by pateskinasy** [comment]
Thanks for reverting @gargol.
 
My bad, I mistook the page "continuing to be public" with the lack of a CTA to either "subscribe" or "become a paid member". I've adjusted also the title of this issue to help others (going through the same find this in future)

In other words, I do not get a CTA when a page is made "Members-only" or "Paid-members only"

To reproduce:

**Public Pages** --> it works
1. Install Lyra, Turn ON and set up Members in Labs
2. Create a page
3. Make "Post access" for the page public 
4. Make sure the page has contents on the body
5. Check if contents are available to public and members
6. All good here, it works

**Members-only Pages**
1. Install Lyra, Turn ON and set up Members in Labs
2. Create a page
3. Make "Post access" for the page **"members only"** 
4. Make sure the page has contents on the body
5. Check if contents are available to public and members
6. No contents are visible (only title) but most importantly, no CTA to sign up

Not logged-in member sees (no content but NO CTA to subscribe seen) <-- **issue**
<img width="1008" alt="Screenshot 2020-02-11 at 17 41 34" src="https://user-images.githubusercontent.com/18645509/74263856-829a3a00-4cf7-11ea-884a-0a3c2feafd40.png">

Logged-in member sees (sees content --> all OK)
<img width="932" alt="Screenshot 2020-02-11 at 17 42 05" src="https://user-images.githubusercontent.com/18645509/74263944-b4ab9c00-4cf7-11ea-8e13-4bfbd2d45338.png">

**Paid-members only Pages**
1. Install Lyra, Turn ON and set up Members in Labs
2. Create a page
3. Make "Post access" for the page **"paid-members only"** 
4. Make sure the page has contents on the body
5. Check if contents are available to public and members
6. No contents are visible (only title) but most importantly, no CTA to sign up, nor to become paid member

Not logged-in member sees (no content but NO CTA to subscribe seen) <-- **issue**
<img width="932" alt="Screenshot 2020-02-11 at 17 44 18" src="https://user-images.githubusercontent.com/18645509/74264185-24218b80-4cf8-11ea-9b57-6ced41c5786d.png">

Logged-in member sees (no content but sees no CTA to become a paid member) <-- **issue**
<img width="932" alt="Screenshot 2020-02-11 at 17 44 30" src="https://user-images.githubusercontent.com/18645509/74264289-529f6680-4cf8-11ea-9d3f-fc94359951bd.png">

**Comment by gargol** [comment]
Might be related to https://github.com/TryGhost/Ghost/issues/11574

**Comment by kevinansfield** [comment]
The [Lyra theme](https://github.com/TryGhost/Lyra) is not set up to show CTAs in it's [page.hbs](https://github.com/TryGhost/Lyra/blob/master/page.hbs). You can modify the theme to suit your needs if you require member-only pages with CTAs, perhaps taking some clues from the theme's [post.hbs](https://github.com/TryGhost/Lyra/blob/master/post.hbs#L88-L134).

Closing as this is not a server-side bug but a specific theme issue.
