### ISSUE TITLE
Posts need content in their body, otherwise, Public posts become member-only and member-only become Paid-members-only

### ISSUE THREAD

**Issue by pateskinasy** [TryGhost/Ghost#11574]
### Issue Summary

Posts need content in their body, otherwise, Public posts become member-only and member-only become Paid-members-only.

Opening this issue here and not in Lyra as I'm unsure where the issue lies.

### To Reproduce

For public post:
1. Install Lyra, Turn ON and set up Members in Labs
2. Create a public post, 
2. Write only a title and no content in the body,
3. Publish the post
4. The post will not be visible (a subscribe banner will cover it)

For member-only post:
1. Install Lyra, Turn ON and set up Members in Labs
2. Create a member-only post, 
2. Write only a title and no content in the body,
3. Publish the post
4. Log in as a member
4. The post will not be visible (a become a paid subscriber banner will cover it)

### Technical details:

* Ghost Version: 3.5.0
* Node Version: 10.19
* Browser/OS: Brave/Chrome/Safari/Opera
* Database: MySQL

**Comment by gargol** [comment]
Thanks for the report @pateskinasy! Was able to reproduce this issue and after quick searches seems like it comes from this condition here - https://github.com/TryGhost/Ghost/blob/master/core/frontend/services/routing/controllers/entry.js#L88, should probably instead compare the `visibility` property on the `entry` if available.

**Comment by ErisDS** [comment]
Re-opening as this needs looking at.

**Comment by digitalextremist** [comment]
Pardon me if I am missing something, but this seems open to me, with another nuance:

- [ ] `access` does not appear in scope at all in templates.

There seemed to be an issue talking about the above but I cannot find it now, and it too was closed as resolved.
