### ISSUE TITLE
Members cannot be deleted

### ISSUE THREAD

**Issue by oreniko26** [TryGhost/Ghost#11589]
Steps to reproduce:
1. Select a test member you created via the full sign-up flow from the Members screen.
2. Scroll down to the details and press Delete Member.

**Result: 404 Not Found.**

This is what I was able to glean from the network:
**Request:**
DELETE https://[my domain]/ghost/api/v3/admin/members/5e419e2e72c3a568b2a786f1/

**Response:**
{"errors":[{"message":"Resource not found error, cannot delete member.","context":"Resource could not be found.","type":"NotFoundError","details":null,"property":null,"help":null,"code":"resource_missing","id":"36d9a350-4c32-11ea-864a-f1dd464908e2"}]}

Additional details:
- The version of Ghost I'm running is the latest (3.5.1). the issue occurred on 3.5.0 and 3.4.0. I didn't check on versions prior to that.
- I'm running Ghost on an Ubuntu 18.04 machine on AWS.
- The user that was created was a non-paying one without a complimentary subscription. I signed up with one of my emails into my sign up form and then activated the account in the mail. I would expect the fix, of course, to allow me to delete members in any situation.

Side-note: I managed to fix the issue on my own deployment of ghost (at least for non-paying, non-complimentary users) by adding:
```
data: [
'id'
]
```
into the `destroy` section inside core/server/api/canary/members.js.

**Comment by gargol** [comment]
Hey @oreniko26 :wave: Could you provide some more details about the version of Ghost you are running and the environment. Also, how did you create the member? Is it a paid member or a member with "Complimentary" plan? Would really help to have a clear reproduction scenario. Thanks

**Comment by oreniko26** [comment]
Edited the original comment with some additional info. Thanks :)

**Comment by gargol** [comment]
Thanks @oreniko26 have fixed it in master and should be going out with today's release. Very strange bug indeed, the behaviour of `frame.options` was tricky comparing to 'read' method :sweat_smile:
