### ISSUE TITLE
Does not round to the end of the current word

### ISSUE THREAD

**Issue by thanosisalive** [TryGhost/Ghost#11585]
### Issue Summary

From [docs](https://ghost.org/docs/api/v3/handlebars-themes/helpers/excerpt/):

> {{excerpt characters="140"}} will output 140 characters of text (rounding to the end of the current word).

It does not round to the end of the current word (as it should). The word is just truncated.

### To Reproduce

1. Create a post where the first paragraph is long enough (140+ characters)
2. Check the last word of `{{excerpt characters="140"}}`

**Comment by gargol** [comment]
Hi @thanosisalive, I suspec you might have misunderstood the use of `{{excerpt}}` helper. The characters parameter is meant to be a number not a string as you provided in the example :wink:

**Comment by thanosisalive** [comment]
> Hi @thanosisalive, I suspec you might have misunderstood the use of `{{excerpt}}` helper. The characters parameter is meant to be a number not a string as you provided in the example 😉

Hi @gargol! I should have indicated that by asterisks I meant any number. This is a bug report, not a support request. 😋

**Comment by gargol** [comment]
Oh! In that case would need to double-check this case. Can you maybe provide a quick unit test to illustrate the bug?

**Comment by thanosisalive** [comment]
> Oh! In that case would need to double-check this case. Can you maybe provide a quick unit test to illustrate the bug?

I'm afraid I can't do that right now. I took a couple of screenshots if that helps.

In the first screenshot, several words are highlighted with a total length of 143 characters.
![143-characters](https://user-images.githubusercontent.com/60091007/74231921-4caa8500-4cfa-11ea-9df0-6549c4723c40.png)

The second screenshot shows what the excerpt looks like with `{{excerpt characters=140}}…`.
![truncated](https://user-images.githubusercontent.com/60091007/74232021-7e235080-4cfa-11ea-87c9-46212dab9ab5.png)

The last word "excerpt" was truncated to "exce". Exactly 140 characters, 3 missing. It did not round to the end of the word.
