### ISSUE TITLE
Word count doesn't support Devanagari script

### ISSUE THREAD

**Issue by amanmehara** [TryGhost/Ghost#11599]
### Issue Summary

Words written in Devanagari script are not recognized by the editor.
![snippet](https://user-images.githubusercontent.com/6859488/74582923-d94d8f80-4fe7-11ea-8056-660a9ae8d194.png)
 
### To Reproduce

1. Write few words in Devanagari script in the editor.
2. Number of words in the bottom right corner will not increase.

This might lead to incorrect time to read.

### Technical details:

* Ghost Version: 3.6.0
* Database: mysql

**Comment by lunaticmonk** [comment]
Looks like the code here: https://github.com/sparksuite/simplemde-markdown-editor/blob/6abda7ab68cc20f4aca870eb243747951b90ab04/src/js/simplemde.js#L1054-L1067 is being used to count words. And it is not taking devnagari in consideration.

**Comment by Necr0** [comment]
Taking it a look at the project it might also be worth considering changing from simplemde to [EasyMDE](https://github.com/Ionaru/easy-markdown-editor/)   seeing as SimpleMDE hasn't been updated in the past 3 years and EasyMDE is actively being maintained (and also 350 commits ahead of SimpleMDE).

**Comment by sumukshashidhar** [comment]
I second @Necr0 here, the code linked by @lunaticmonk looks like its just counting some regular unicode characters.

EasyMDE is definitely a better option

**Comment by ErisDS** [comment]
This is the same issue as https://github.com/TryGhost/Ghost/issues/10303 and https://github.com/TryGhost/Ghost/issues/8467.

Core team has no plan to fix it. Contributions are welcome but will likely be required upstream

**Comment by SimonHausdorf** [comment]
So I was checking regarding Thai as we have the same problem. It seems like the only thing which will work is a dictionary for Thai but I don't think it's a solution ghost would consider?

Example could be usage of: https://github.com/veer66/wordcut
Which leads to
```bash
echo 'จะถูกเปิดตัว' | wordcut                        
จะ ถูก เปิด ตัว
```

But that is a solution only working for Thai and I don't think that there are any solutions out there which work for all languages anyways.

What could be the right approach here?

**Comment by arjunraj1523** [comment]
In Devanagari the words are separated by space so it should be easy to solve. Also the end of a sentence is a “|” instead of a “.”. I’d like to take this issue up

**Comment by ErisDS** [comment]
The reading time code is based on the simpleMDE code, but is implemented with customisations here: https://github.com/TryGhost/Ghost-SDK/blob/master/packages/helpers/lib/utils/count-words.js
