### ISSUE TITLE
Save warning displayed when no changes made to Design settings

### ISSUE THREAD

**Issue by frantzypants** [TryGhost/Ghost#11590]
## Issue Summary

When clicking on a label or link path in the navigation, even if no changes are made, you are still presented with an alert asking if you are sure you want to leave when clicking to other areas of Ghost admin. 

### To Reproduce

1. Go to the Design settings in Ghost admin
2. Click inside the label of an existing navigation item
3. Make no changes to the field, and click on "Posts" or any other location within the admin
4. See warning notification 

### Technical details:

Version 3.5.2
Environment production
Database mysql
Browser/OS: Any

**Comment by TheodoreChu** [comment]
Thank you, @frantzypants for writing this up. This occurs for both the primary and secondary navigation. The warning does not show if we click or type into the final empty "Label" box, but it does show if we click or type into the final corresponding link.
