### ISSUE TITLE
{{#if access}} fails when there is no post content

### ISSUE THREAD

**Issue by minimaluminium** [TryGhost/Ghost#11594]
### Issue Summary

When there is no post content, `{{#if access}}` fails even when the post visibility was set as public.

```hbs
{{#if access}}
  {{content}}
{{else}}
  No access...
{{/if}}
```

It shows "No access..." in this example.

### To Reproduce

1. Create a new post with no content or delete the content of an existing post.
2. Add `{{#if access}}` condition to `post.hbs` like above.

### Technical details:

* Ghost Version: 3.5.2
* Database: mysql/sqlite3

**Comment by gargol** [comment]
Thanks for reporting @minimaluminium! The root of this issue is most likely the same as described here - https://github.com/TryGhost/Ghost/issues/11575. Closing this one in flavor of the older as it has a lot more reproduction information.
