### ISSUE TITLE
The url environment var is not flexible

### ISSUE THREAD

**Issue by prawnsalad** [TryGhost/Ghost#11595]
### Issue Summary

When running Ghost behind a reverse proxy it can be awkward to configure the hostname that Ghost is accessible by. Eg. nginx listening on multiple hostnames *and* http or https, but Ghost can only be configured to use a single address. Especially awkward when using in development as different devs may be using localhost/ghost.dev/127.0.0.1/etc.

To improve this, either:
* Allow the `url` environment variable to be only a path. Eg. `url=/cms/ghost/`. Any redirects or links will still work and will be relative to any http/https or hostname in use.
* Auto detect the URL environment via common incoming HTTP headers
  * {X-Forwarded-Proto}://{Host}/{configured_base_path}

**Comment by prawnsalad** [comment]
Is it not considered a bug when Ghost can't track the URL to access itself correctly?

**Comment by allouis** [comment]
What do you mean by track the URL to access itself? This is part of Ghost's config, set via the config.*.json file or through environment variables.

If you think there is a bug please give reproducible steps so we can see the functionality not working as intended!

**Comment by prawnsalad** [comment]
Sure. As mentioned in the first comment, lets use nginx as a reverse proxy to Ghost using this config:
~~~nginx
server {
    listen       80;
    listen       443 ssl;
    server_name  server.com;

    location /cms/ {
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_pass http://localhost:2368/cms/;
    }
}
~~~

Then start Ghost with docker `docker run -d --name some-ghost -e url=http://localhost/cms/ -p 2368:2368 ghost` (I assume this would also work when running the source directly since it reads the same environment vars)

Now accessing Ghost:
* http://localhost/cms/ - works
* https://localhost/cms/ - parts of the admin UI breaks
* http(s)://127.0.0.1/cms/ - parts of the admin uses different URIs
* http(s)://local.dev/cms/ - parts of the admin UI breaks
* http(s)://server.com/cms/ - parts of the admin UI breaks

In all cases, it is expected to use the scheme+hostname that I used to access Ghost.

Two ways that could potentially fix Ghost to using correct URIs in the admin:
* Allow the url environment variable to be only a path. Eg. url=/cms/. Any redirects or links will still work and will be relative to any http/https or hostname in use.
* Auto detect the URL environment via common incoming HTTP headers
{X-Forwarded-Proto}://{Host}/{configured_base_path}

**Comment by allouis** [comment]
You have configured a proxy to serve Ghost `https://server.com/cms` - so you need to set the url in config to `https://server.com/cms` - with this everything will be correct :relaxed: 

Ghost doesn't support being hosted on multiple domains. You can however have one domain for the admin and one for the frontend, e.g. https://admin.site.com and https://blog.site.com

**Comment by prawnsalad** [comment]
I've had a brief look at what the limitation could be and it seems that most of it comes from the fact that the `url-utils` lib is handling URL generation without any consideration from the incoming request at all.

> Ghost doesn't support being hosted on multiple domains

Is this by design or would you accept a PR to fix this bug and have it respecting reverse proxy headers? If a PR is cool, are there any other places that generate URLs outside of the request -> response loop that you can think of?

**Comment by kevinansfield** [comment]
> Is this by design or would you accept a PR to fix this bug and have it respecting reverse proxy headers?

It's by design. Having Ghost respond to multiple domains makes it far too easy for site owners to shoot themselves in the foot with duplicate-content penalties and creates easy routes for malicious actors to abuse.
