### ISSUE TITLE
Ghost admin failing to load posts upon scroll

### ISSUE THREAD

**Issue by toddbirchard** [TryGhost/Ghost#11608]
### Issue Summary

As of Ghost 3.7, Ghost admin fails to load additional posts when infinite scrolling. This issue is reproducible in the latest versions of Firefox, Chrome, and Safari on OSX:

![Posts load forever](https://i.imgur.com/m1sQ86K.gif) 

### To Reproduce

1. Log in to Ghost admin
2. Navigate to "posts" section
3. Scroll to bottom

### Technical details:

* Ghost Version: 3.7
* Node Version: 12
* Browser/OS: Firefox, Chrome, and Safari on OSX
* Database: MySQL v8

**Comment by robotnealan** [comment]
Experiencing the same issue except with Node v10. It appears as though the JSON is being returned correctly on scroll but never rendered into the page.

**Comment by gaplo917** [comment]
Experiencing the same issue on the managed service(ghost.io). The work around is grab the post id in the api response and edit the post via `https://xxx.ghost.io/ghost/#/editor/post/{id}`

This is a very serious bug for non-technical writers.
