### ISSUE TITLE
Total members email display shows wrong total

### ISSUE THREAD

**Issue by rickdonato** [TryGhost/Ghost#11620]
### Issue Summary

When sending an email to paid members the total emails shown shows all members. 

### To Reproduce

1. This is the first step
Create a list of users. Containing paid members and standard members
2. This is the second step, etc.
Set post to paid members only. Publish a post and send mail. 
You will see the total emails sent says that it has sent to everyone on the members list. However this is not the case. So this issue is a display issue.

### Technical details:

* Ghost Version: 3.6.0
* Node Version: TBC
* Browser/OS: Chrome Windows 10
* Database: TBC

**Comment by kevinansfield** [comment]
This was resolved in 3.8.0 for any newly created emails 🙂
