### ISSUE TITLE
Add TODOs Badge to README

### ISSUE THREAD

**Issue by patrickdevivo** [TryGhost/Ghost#11635]
Hi there! I wanted to propose adding the following badge to the README to indicate how many `TODO` comments are in this codebase:

[![TODOs](https://badgen.net/https/api.tickgit.com/badgen/github.com/TryGhost/Ghost)](https://www.tickgit.com/browse?repo=github.com/TryGhost/Ghost)

The badge links to `tickgit.com` which is a free service that indexes and displays TODO comments in public github repos. It can help surface latent work and be a way for contributors to find areas of code to improve, that might not be otherwise documented.

The markdown is:

```
[![TODOs](https://badgen.net/https/api.tickgit.com/badgen/github.com/TryGhost/Ghost)](https://www.tickgit.com/browse?repo=github.com/TryGhost/Ghost)
```

Thanks for considering, feel free to close this issue if it's not appropriate or you prefer not to!

(full disclosure, I am the creator/maintainer of `tickgit`)

(If this is more appropriate for the forum, I can move there as well!)

**Comment by gargol** [comment]
Hi @patrickdevivo :wave: We don't have any particular problem that this badge would solve, so would rather pass on adding more dependencies to the project. Thanks for your suggestion!

**Comment by patrickdevivo** [comment]
Understood! Thank you for considering!
