### ISSUE TITLE
3.10.0 Complimentary Subscription no longer works/saves

### ISSUE THREAD

**Issue by uksitebuilder** [TryGhost/Ghost#11648]
After upgrading to 3.0.10 and changing membership plan pricing currency to GBP, can no longer give complimentary membership to members

### To Reproduce

In admin visit members section
Edit a member that has no pricing plan/subscription yet
Toggle/enable Complimentary Subscription button
Save settings

Following error is returned:

Internal server error, cannot edit member. Cannot read property ‘id’ of undefined

### Technical details:

* Ghost Version: 3.10.0
* Node Version: 10.19.0
* Browser/OS: Chrome (latest) macos
* Database: mySQL 5.7.29 on Ubuntu 18.04

**Comment by gargol** [comment]
Related issue https://github.com/TryGhost/Ghost/issues/11649 (the cause is most likely the same)

**Comment by uksitebuilder** [comment]
Reopen please as updating to 3.11.0 did not solve the issue
