### ISSUE TITLE
Ghost import function validate file extension instead of its content

### ISSUE THREAD

**Issue by z3niths** [TryGhost/Ghost#11657]
### Issue Summary

When we export blog using ghost-cli `ghost export`, we can name it using any filename and extension. But when we import it into the other ghost server using ghost-cli `ghost import`, if we use the file which is not a JSON extension (.json) the cli vaidation will thow an error.

### Expected
it shouldn't validate using file extension and using JSON (content) validation instead.
So any file name without .json but contain the JSON content should've worked as well.

```
✖ Running blog import
An error occurred.
Message: 'Response code 415 (Unsupported Media Type)'

```

### To Reproduce

1. `ghost export testimportfile`
2. `ghost import testimportfile`

### Technical details:

Debug Information:
    OS: Ubuntu, v18.04.4 LTS
    Node Version: v10.19.0
    Ghost Version: 3.11.0
    Ghost-CLI Version: 1.13.1
    Environment: production
    Command: 'ghost import bckfile'

**Comment by MohAnghabo** [comment]
I've solved this problem by adding `.json` to the name of the export file.
