### ISSUE TITLE
Can not input Chinese in the editor...

### ISSUE THREAD

**Issue by Jiachen-Zhang** [TryGhost/Ghost#11658]
### Issue Summary

It's not possible to input Chinese (maybe no-ascii) characters just in the editor. It's ok to input in the markdown block or input letters of an alphabet first.

### To Reproduce

1. Start a new post
2. Use Microsoft Chinese input method, input Chinese directly in the text area

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

I think this is insufficient support for non-ascii letters

### Technical details:

* Ghost Version: v3.5.0
* Node Version:  v12.13.1
* Browser/OS: Ubuntu 18.04 LTS
* Database: SQLite

**Comment by jsxzljx** [comment]
I have the same problem, which has lasted for a long time after the release of Koenig editor.

Specifically, when I type any characters on **a blank line** with an input method on (not raw input), the first character unexpectedly appears on the editor and is behind my cursor. Normally, it should stay in the input method until I finish my Chinese typing. The "behind behavior" also appears when texting `-` or `#` characters.

However, if I texting on a line which is not blank, there is no such problem.
Hope this GIF would help explain this issue.
![5](https://user-images.githubusercontent.com/20895293/77223549-92c7f380-6b98-11ea-84e7-01046845e514.gif)

**Comment by kevinansfield** [comment]
This is tracked on the upstream mobiledoc-kit repo https://github.com/bustle/mobiledoc-kit
