### ISSUE TITLE
Tooltips on multiline links are not reachable

### ISSUE THREAD

**Issue by jaydenroberts** [TryGhost/Ghost#11668]
### Issue Summary

When creating multiline links, if the link is the last letter, or on the end of a line, and spans onto a second line you are not able to reach the tooltip to edit/remove the link.

![Screen Shot 2020-03-16 at 5 56 35 pm](https://user-images.githubusercontent.com/6936935/76733687-3be5a700-67b1-11ea-99d9-c5d9fe035cea.png)

The tooltip disappears too quickly when you try to select it, however re-selecting the original link text, will allow tooltip to stay, allowing you to edit/remove the link.

### Technical details:

* Ghost Version: v3.9.0
* Browser/OS: Chrome 80.0.3987.132 / macOS 10.15.3

**Comment by kevinansfield** [comment]
This was fixed in Ghost [3.10.0](https://github.com/TryGhost/Ghost/releases/tag/3.10.0) 🙂 Original issue here https://github.com/TryGhost/Ghost/issues/9792
