### ISSUE TITLE
Unable to schedule post to members

### ISSUE THREAD

**Issue by cmorbitzer** [TryGhost/Ghost#11689]
### Issue Summary

I am unable to schedule a post and send it to members in the admin using Ghost 3.12.0.

### To Reproduce

1. Enable members and add at least one member
2. Create a new draft post with any title and body
3. Click `Publish`
4. Click `Schedule it for later`
5. Click on the date and in the calendar choose any date in the future

Here a console error appears: `TypeError: t is null` and the Send an email dialog sometimes does not appear. If it does, and I enable it and still click Schedule, the box may or may not disappear but the post is not scheduled

### Technical details:

* Ghost Version: 3.12.0
* Node Version: 12.16.1

**Comment by daniellockyer** [comment]
Hi @cmorbitzer! :wave: This was fixed today in 3.12.1 so please update using Ghost-CLI :smile:
