### ISSUE TITLE
Ghost Admin does not work in browser with full ES6 support

### ISSUE THREAD

**Issue by bil-ash** [TryGhost/Ghost#11686]
### Issue Summary

Since Ghost-Admin has issue creation disabled so I am opening the issue here.

Ghost-Admin targets [only last two versions of browsers](https://github.com/TryGhost/Ghost-Admin/blob/master/config/targets.js) . So async functions(an ES7 feature) are not transpiled(to ES6) and thus it leads to the admin not working on Firefox 50 which has full ES6 support but no ES7 support. I agree that there is no need to [support IE11](https://forum.ghost.org/t/admin-page-keeps-loading-in-ie11/8308) but I believe ghost admin client should support the browsers for at least 5 years (browserlist config **last 5 years** ). This config would automatically remove support for older browsers every year.

### To Reproduce

1. Open ghost admin on any browser which does not support async functions (data can be obtained from MDN)
2. The admin does not load and only the spinner is displayed. Now open browser console, check the error message related to ghost.min.js, find the line number& offset corresponding to the error and you will notice that the error is because browser does not understand the **async** keyword.

Any other info e.g. **Why do you consider this to be a bug? What did you expect to happen instead?**

I expect the admin client to open in a  3 years 9 month old browser.

### Technical details:

* Ghost Version: 3.12.0 (irrelevant)
* Node Version: 10.x (irrelevant)
* Browser/OS: Firefox 50/Windows 10
* Database: Irrelevant

**Comment by kevinansfield** [comment]
For the last few years Ghost has only supported the latest few versions of evergreen browsers and we have no plans to change that. If you wish to use Ghost please upgrade to a modern browser.

**Comment by bil-ash** [comment]
I generally use Ghost Admin from Edge where it works fine. Just yesterday, I came to across this thing and thought that it is a bug(which isn't since you have no plans to support older browsers). But I would  like to still ask you to support the last 10 versions(~1 year) of browsers like chrome and firefox which have a fast release cycle.
