### ISSUE TITLE
Email mismatch bug with google pay in members payment flow

### ISSUE THREAD

**Issue by filmstorm** [TryGhost/Ghost#11695]
Hi there,

I have noticed this major flaw in the payment flow inside Ghost for Stripe. 

### Issue Summary

For this example, I have a user signed up for a free account in Ghost with email: **test@ghost.com**

When the user **test@ghost.com** loads checkout to pay for their chosen upgrade subscription, and they choose to pay with Google Pay, if their email address associated with Google Pay is different i.e **test-google@ghost.com**, to the email address signed up through the Ghost site, after payment is completed the user is set up with another account and not the one they already have with Ghost. 

So the user now has two accounts but ghost redirects to the home page and reports that the user was signed up successfully. If the user then goes to their account it says they are still a free member and not paid - this causes confusion as they have been charged but not linked correctly.

### To Reproduce

1. Sign up for a free account on ghost using one email i.e **test@ghost.com**
2. Go to upgrade the membership in Ghost and try to pay with Google Pay which uses another email address on their file i.e, **test-google@ghost.com**
3. After test payment is successful Ghost will redirect to the homepage and show successful subscription notification.
4. Go to account again and see that it still says free for member - when in fact they have paid. (As it has set up another account instead of linking to the current one)

### Technical details:

* Ghost Version: 3.12.1

**Comment by pascalandy** [comment]
+1 since I upgraded to v3.12.1

The subscriptions were good and now stripe webhook can't push the confirmation to Ghost.

### stripe dashboard

![Screen Shot 2020-04-06 at 11 00 47 PM](https://user-images.githubusercontent.com/6694151/78625698-c1152680-785a-11ea-9ef2-690b4a5cbec2.jpg)

### stripe email error

![Screen Shot 2020-04-06 at 11 01 46 PM](https://user-images.githubusercontent.com/6694151/78625706-c83c3480-785a-11ea-96a2-49bc7a7f8e4e.jpg)

Thanks!

**Comment by gargol** [comment]
@pascalandy is the webhook failure you are experiencing related to an email mismatch as well or is it something else?

**Comment by filmstorm** [comment]
My problem occurs with a fully functional email setup- using Mailgun for all events.

**Comment by pascalandy** [comment]
@gargol I'm snot sure to understand what you mean by an email mismatch here.

> is the webhook failure you are experiencing related to an email mismatch as well or is it something else?

**Comment by kevinansfield** [comment]
@pascalandy the question was to determine if your report is related to this issue. What you've provided so far suggests it isn't, can you move to the forum to try and debug separately please?

**Comment by pascalandy** [comment]
Oh I see. I have a "Major Bug for Members Payment Flow in Stripe" but it's not the same scenario. Will document separately. Thanks!

**Comment by matthanley** [comment]
@allouis is this still an issue now that #12055 is closed?

**Comment by allouis** [comment]
I haven't replicated this yet, but I don't think the fix for #12055 will have affected this
