### ISSUE TITLE
Private Bucket/ACL works for images in post but not for Featured Images

### ISSUE THREAD

**Issue by eugeneniemand** [TryGhost/Ghost#11698]
### Issue Summary

My ACL/Bucket is private and so is the blog

When I upload a picture using the settings on the right it uploads the image to spaces but does not load/display the image

![image](https://user-images.githubusercontent.com/6813309/77834432-aa751e00-713c-11ea-8335-dcbab499c695.png)

![image](https://user-images.githubusercontent.com/6813309/77834455-bcef5780-713c-11ea-9e7b-a7edd73458d3.png)

However adding the exact same image to the main post works fine

### Technical details:

Version 3.11.0
Environment production
Database sqlite3

**Comment by ErisDS** [comment]
Hi @eugeneniemand, it sounds like this is an issue with whatever storage adapter you're using and not Ghost core.

We can reopen if you can provide enough information to demonstrate a bug in core 🙂
