### ISSUE TITLE
Cannot save the post, js error

### ISSUE THREAD

**Issue by neok** [TryGhost/Ghost#11693]
### Issue Summary

When I trying to edit a post and click update I receive this error
Uncaught (in promise) TypeError: Cannot read property 'appendChild' of null
### To Reproduce

1. Go to `#/editor/post/{post-id}`
2. Edit text, click update(everything ok),
3. Edit text once again, click update -  nothing happens
The expected result, the post should be updated.

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?
![image](https://user-images.githubusercontent.com/600233/77666293-76a5c700-6f89-11ea-9bae-70078cf1a530.png)

### Technical details:

* Ghost Version: 3.12.0
* Node Version: v10.16.0
* Browser/OS:
* Database: mysql

**Comment by daniellockyer** [comment]
Hi @neok! :wave: This was just fixed in [3.12.1](https://github.com/TryGhost/Ghost/releases/tag/3.12.1) so please update through Ghost-CLI. :smile:
