### ISSUE TITLE
kg-bookmark tags available on RSS feed XML

### ISSUE THREAD

**Issue by truekasun** [TryGhost/Ghost#11705]
### Issue Summary

When we create a post and include a Bookmark card, the RSS Feed XML includes it as a <figure> with the "kg-bookmark" classes. Those classes do not mean anything to outside services unless they are using the site styles.

![chrome_2020-04-01_12-47-23](https://user-images.githubusercontent.com/278469/78088461-57d78280-7418-11ea-86a8-91a0ade723ee.png)

Because of this issue, services depending on RSS feed (like Facebook instant articles, RSS Feed readers) trying to show this as an image instead of a link. This makes the bookmark is useless as no one can click on it and go to the respective page.

I think this should be replaced with an HTML link instead of a figure.

### To Reproduce

1. Create a post with a Bookmark card and publish it
2. Check the RSS Feed (sitename.com/rss)

### Technical details:

* Ghost Version: 3.12.1

**Comment by matthanley** [comment]
Reopened as we have an open PR awaiting review
