### ISSUE TITLE
Mention the /ghost admin URL in the QuickStart

### ISSUE THREAD

**Issue by jpaugh** [TryGhost/Ghost#11703]
The [QuickStart Guide](https://github.com/TryGhost/Ghost#quickstart-install) in the README should mention how to login to a newly installed site.

This information is also lacking from the two or three install guides that I looked over, including the Ubuntu preferred install guide,and the Docker one. I finally found it from a third-party blog site. I also filed an issue with the Docker team, as they do not have the info, either. https://github.com/docker-library/ghost/issues/217

**Comment by daviddarnes** [comment]
@jpaugh hey Jonathan 👋 
The `ghost-cli` will show you how to access Ghost Admin once it's been installed. However we've added a note that the admin will be available at `/ghost` here:
https://ghost.org/docs/install/ubuntu/#run-the-install-process
