### ISSUE TITLE
JS exception while adding tags to a post using Ghost editor

### ISSUE THREAD

**Issue by RajatNair** [TryGhost/Ghost#11721]
### Issue Summary

Adding tags to a new post in Ghost editor throws JS exceptions which makes certain buttons on the page unresponsive and in certain situations - the entire page/editor unresponsive.  

### To Reproduce

1. Create a new blog post using Ghost editor
2. Chose a markdown template
3. Clicked on `Post Settings` and added `Tags` to post.
4. You can see errors in browser console. Sometimes the entire page become unresponsive and only solution is a hard refresh.
5. Also, if this JS exception is thrown, certain buttons on editor become unresponsive. 

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?
![image](https://user-images.githubusercontent.com/3319907/78705137-a611e780-792a-11ea-9f29-1e52ffff111c.png)

### Technical details:

* Ghost Version: 3.12.0
* Browser/OS: Chrome 80.0.3987.163 on Windows 10
* Database: MySQL

**Comment by daniellockyer** [comment]
Hey @RajatNair :wave: 3.12.1 contained a fix for this, but I'd recommend updating to the latest, 3.13.1, using the Ghost CLI :smile:
