### ISSUE TITLE
The blog logo doesn't appear in front page if the SVG doesn't integrate width and height properties

### ISSUE THREAD

**Issue by DarthJahus** [TryGhost/Ghost#11734]
### Issue Summary

The SVG file set as "Publication logo" will have null-size in the front page if the SVG doesn't contain `width` and `height` properties (Adobe Illustrator default export doesn't include them).

### To Reproduce

0. Export an illustration as SVG from Adobe Illustrator (or other), make sure it doesn't have `width` and `height`
1. Set a SVG file as Publication logo
2. Check the front page

Example of SVG header:
```
<?xml version="1.0" encoding="utf-8"?>
<!-- Generator: Adobe Illustrator 24.0.0, SVG Export Plug-In . SVG Version: 6.00 Build 0)  -->
<svg version="1.1" id="Calque_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	 viewBox="0 0 604 204" style="enable-background:new 0 0 604 204;" xml:space="preserve">
```

### More details

If you manually add `width` and `height` to the SVG file, the logo appears correctly.

Example of SVG header:
```
<?xml version="1.0" encoding="utf-8"?>
<!-- Generator: Adobe Illustrator 24.0.0, SVG Export Plug-In . SVG Version: 6.00 Build 0)  -->
<svg version="1.1" id="Calque_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	 viewBox="0 0 604 204" style="enable-background:new 0 0 604 204;" xml:space="preserve">
```

### Technical details:

* Ghost Version: 3.13.1

**Comment by kevinansfield** [comment]
@DarthJahus this is down to theme-specific styling. Please open an issue on the relevant theme (Ghost's default theme Casper is here https://github.com/TryGhost/Casper), contact your theme developer, or adjust the styles in your theme to work with the SVGs you are using.
