### ISSUE TITLE
Structured data error

### ISSUE THREAD

**Issue by alwaysmpe** [TryGhost/Ghost#11746]
### Issue Summary

I received an email from google notifying me of "Error in required structured data element".

In particular, the publisher logo is a double nested ImageObject:

    "publisher": {
        "@type": "Organization",
        "name": "example",
        "url": "https://example.com/",
        "logo": {
            "@type": "ImageObject",
            "url":{
                "@type": "ImageObject",
                "url": "https://example.com/favicon.png",
                "width": 60,
                "height": 60
            }
        }
    },

### To Reproduce

1. deployed using digital ocean 1-click
2. uploaded custom icon of size 512x512

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

Google considers it an error

### Technical details:

I've traced the error to here: https://github.com/TryGhost/Ghost/blob/9fce5d8ac0433c478e5242cad9b0c1a20cbb4dae/core/frontend/meta/schema.js#L32

Depending on the arguments, schemaImageObject can either return a url or an ImageObject. As far as I can tell (tested in prod 😀), changing the value of logo to the return of the schemaImageObject function works for me, but I suspect in the situation when a url is returned, the structure will also have an error.

I don't know the code well enough to create a proper fix, but hopefully this'll give you a good start!

* Ghost Version: 3.13.3
* Node Version: Unknown
* Browser/OS: chrome/w10
* Database: mysql

**Comment by daniellockyer** [comment]
Hey @alwaysmpe! :wave: Thanks for the report. A fix has been made and should be released in the next version :grin:
