### ISSUE TITLE
Spam config parameter name

### ISSUE THREAD

**Issue by nstefan** [TryGhost/Ghost#11740]
Issue:
Wrong spam parameter name here: https://github.com/TryGhost/Ghost/blob/7409a4247c0c49f24451175278e02904689de609/core/server/config/defaults.json#L71

Current behavior:
`private_block`

Expected result:
`private_blog` from spam-prevention.js: https://github.com/TryGhost/Ghost/blob/7409a4247c0c49f24451175278e02904689de609/core/server/web/shared/middlewares/api/spam-prevention.js#L9

Or maybe it's the other way around and spam-prevention.js should read `private_block` instead…

**Comment by daniellockyer** [comment]
Hey @nstefan! :wave:

Reallllly nice spot :grin: We've decided to switch the code to `private_block` in order to avoid breaking configs. Thanks for the report!

**Comment by nstefan** [comment]
Hey, that was fast, thank you! 👍

**Comment by daniellockyer** [comment]
Fix will be out in the next release :grinning:
