### ISSUE TITLE
Getting a 404 error on "Author" and "Tag" page, after removing the default ghost user.

### ISSUE THREAD

**Issue by maathimself** [TryGhost/Ghost#11751]
Welcome to Ghost's GitHub repo! 👋🎉

We use GitHub only for bug reports 🐛

Anything else should be posted to https://forum.ghost.org 👫

🚨For support, help & questions use https://forum.ghost.org/c/help
💡For feature requests & ideas you can post and vote on https://forum.ghost.org/c/Ideas

If your issue is with Ghost CLI, please report it on the CLI repo ➡️ https://github.com/TryGhost/Ghost-CLI/issues/new.

### Issue Summary
I originally installed ghost on an ubuntu 18.04 server, started poking around(and really liked it), then I decided to dig into some customization. I had my own owner account, and a couple posts, and i also had another active user added. Following the advice of some of the default content, I deleted the default ghost user to remove the welcome posts. After I did this I was getting a 404 error on the tags and author page. I check my routes.yaml file and it appears to be correct, I haven't made any changes to it all because I don't know what I'm doing, yet.

### To Reproduce

I decided, to install ghost locally on my Macbook to test and got the same error after deleting the user.

I think this is either a bug or I'm missing something, which is entirely possible.

### Technical details:

* Ghost-CLI version: 1.13.1
   Ghost version: 3.13.3
* Node Version: v12.16.2
* Browser/OS: Newest - Firefox, Chrome, Safari
* Database: Production install with MariaDB and Local install

Please let me know if you need any additional information. Thank you

**Comment by sumukshashidhar** [comment]
Hey!

I know the contributors can't answer this because they're much too busy, but I will!

You're getting those 404 errors because the links are still to the "Ghost" Author, when in face, you've deleted them

You can simply fix that by going to one of the settings pane, and changing the "slug" for the author page

(Each user has a specific slug, if you didn't know!)
