### ISSUE TITLE
Member management UI issues

### ISSUE THREAD

**Issue by JohnONolan** [TryGhost/Ghost#11755]
When navigating to the members screen in Ghost Admin, there are several UI issues which we need to get on top of:

- [x] Loading spinner in the wrong place, not vertically centered
- [x] Intermittently loads only 1 member for 5-10 seconds
- [x] When the rest are loaded, the screen scrolls all the way to the very bottom of the list
- [x] It is impossible to scroll up, again, with screen jumping around all over the place

**Comment by kevinansfield** [comment]
https://github.com/TryGhost/Ghost-Admin/commit/3be0fcc2867dc34898004441d9a8f5f70a916d11 fixed the slightly janky scrolling I was seeing in Firefox 75 but I wasn't able to reproduce any of these in Firefox or other browsers:

>  - Intermittently loads only 1 member for 5-10 seconds
>  - When the rest are loaded, the screen scrolls all the way to the very bottom of the list
>  - It is impossible to scroll up, again, with screen jumping around all over the place

**Comment by ErisDS** [comment]
Worth checking if this is still reproducible once the new performant dashboard is in production.

**Comment by ErisDS** [comment]
These are now all definitely in production

**Comment by JohnONolan** [comment]
Yesss this is fast and smooth now!
