### ISSUE TITLE
Iframe content: A tag on this page requires an AMP component 'script' tag, which is missing. 

### ISSUE THREAD

**Issue by ucg8j** [TryGhost/Ghost#11762]
# Issue Summary

After upgrading to the latest image a week ago, a blog post written several years ago began to be flagged by Google Search Console.
![Screen Shot 2020-04-21 at 22 16 38](https://user-images.githubusercontent.com/6220504/79914847-d921a400-841d-11ea-943e-7f4b0ad6865e.png)

I tried including including the [amp-iframe script](https://amp.dev/documentation/components/amp-iframe/#iframe-viewability) in the blog header, then the footer, then both header and footer to no avail.

### To Reproduce
Load the amp [version of the blog post.](https://lukesingham.com/map-of-australia-using-osm-psma-and-shiny/amp/#development=1)

Related research
- [Exact same issue here - but solutions didn't work for me](https://peterdaugaardrasmussen.com/2020/04/04/how-to-solve-a-tag-on-this-page-requires-an-amp-component-script-tag-which-is-missing-for-amp-iframes/)
- [Closest issue I could find](https://github.com/TryGhost/Ghost/issues/10972)

### Technical details:

* Ghost Version: 3.13.1
* Node Version: `$ node -v` #v0.12.0
* Browser/OS: Chrome / Mac
* Database: sqlite3

**Comment by PeterDRasmussen** [comment]
I own the blog linked to in related research. I run Ghost blog Pro and I just wanted to note that my issue started on the 29th of March. I spent a lot of time fiddling around with this, but I could not find any simple pattern on this. When I wrote that I moved it further down the page, I believe I also added more text before the iframe.

**Comment by aileen** [comment]
I was able to reproduce this issue locally. This was caused by the regex that detects `iframe` not taking potential line breaks into count. Fix incoming!
