### ISSUE TITLE
Infinite redirect when using different admin URL locally

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#11766]
When trying to test out the behaviour of the admin vs frontend URLs locally, I hit an infinite redirect. This will always happen for any admin URL that uses a port, because we compare one string that contains the port with another that does not.

### To Reproduce

1. In `/etc/hosts` assign a second value to 127.0.0.1 e.g. `admin.localhost` 
2. In your local dev env, open `config.development.json` and add your second URL as admin url:
```
"admin": {
    "url": "http://admin.localhost:2368"
}
```
3. (re)start your dev env, and try to visit `http://localhost:2368/ghost`or `http://admin.localhost:2368/ghost`
4. See an infinite redirect loop

I expect to be able to use any valid URL for the admin URL. 

### Technical details:

* Ghost Version: master

**Comment by ErisDS** [comment]
I think this was caused by this change: https://github.com/TryGhost/Ghost/commit/7284227f1ebb8835f2f9a91dea988332383fc219#diff-95ca75e05f86961a3f30db14087f0a7bR99

See the PR https://github.com/TryGhost/Ghost/pull/11767

When the switch was made from host to hostname [here](https://github.com/TryGhost/Ghost/commit/7284227f1ebb8835f2f9a91dea988332383fc219#diff-95ca75e05f86961a3f30db14087f0a7bR99) the behaviour changed from being the full host to just the hostname (similar to url.parse().host vs url.parse().hostname). The main difference is hostname does not include any ports.

The tests do not currently reflect this [as they just return host](https://github.com/TryGhost/Ghost/commit/7284227f1ebb8835f2f9a91dea988332383fc219#diff-440175ca485d10a10315a23e52197153R17) giving us false confidence that the code is working.

**Comment by thosmos** [comment]
I'm having trouble getting access to the admin panel.  I've tried a few different things.  
given:
```
  "server": {
    "port": 9580,
    "host": "127.0.0.1"
  },
```
This redirects endlessly
```
  "admin": {
    "url": "http://localhost:9850"
  },
```
As does this:
```
  "admin": {
    "url": "https://ghost.mydoman.org"
  },
```
with an nginx of:
```
upstream ghost {
  server 127.0.0.1:9580;
  keepalive 128;
}
server {
    server_name ghost.mydomain.org;
    client_max_body_size 128m;
    proxy_read_timeout 60;
    access_log "/var/log/ghost_access_log";
    error_log "/var/log/ghost_error_log";
    root /home/myuser/web;
location / {
        proxy_pass http://ghost;
        proxy_set_header Connection "";
        proxy_set_header Host             $http_host;
        proxy_set_header X-Real-IP        $remote_addr;
        proxy_set_header X-Forwarded-For  $proxy_add_x_forwarded_for;
}
    listen 443 ssl; 
}

```

**Comment by ErisDS** [comment]
Yeah, that's the same issue - fun that you hit it the same day I did after it's been in the codebase for 6 months and no one spotted it. 

You'll need to either apply my patch or wait for the next release.
