### ISSUE TITLE
HTTPS connection is "not safe" due to images

### ISSUE THREAD

**Issue by winters-brown** [TryGhost/Ghost#11771]
### Issue Summary

A summary of the issue and the browser/OS environment in which it occurs.

This would be my first time setting up a ghost blog and had a wonderful experience doing so. The LetsEncrypt bot was really smooth and figured everything out for me without much configuration. The entire site worked fine except for two things that really bother me. I do want to state that it might just be user error on my part and I skipped documentation or something. If I did feel free to let me know.

After making a post, I upload an associated image to correlate with the post. Doing so breaks the security of the website by loading it locally allowing for an attacker to substitute the image with something else. I was notified by firefox's secure connection.

![image](https://user-images.githubusercontent.com/17482298/80220543-0171f400-8612-11ea-9afe-8a9794719138.png)

After viewing the source of the website I noticed it is because of the way the cms include the images. For example if you visit this link https://unorthodoxdev.com/modern-tracking-methods/
enter debug mode and check the source destination of my image, you will notice it is referenced locally not through the websites https path.

![image](https://user-images.githubusercontent.com/17482298/80220721-4433cc00-8612-11ea-84c6-f1cf4e223edd.png)

the solution would be to replace
```/content/images/size/w2000/2020/04/anthony-rosset-5r5554u-mHo-unsplash.jpg```
with
```https://unorthodoxdev.com/content/images/size/w2000/2020/04/anthony-rosset-5r5554u-mHo-unsplash.jpg```

this is generally a standard as even Github does this. If you were to inspect the source of this post you would see that the images I added to this are loaded via https:// instead of referenced locally.

IE
```
https://user-images.githubusercontent.com/17482298/80220721-4433cc00-8612-11ea-84c6-f1cf4e223edd.png
```

maybe this is because not everyone who develops for ghost is running it on a VPS and isn't able to run the production version, or again I don't know what I'm doing and ive done something wrong. 

This bug is reproducible as well on edge. I would like to try on chrome but don't have it downloaded. I would assume that this is not a browser-specific bug.

### To Reproduce

1. Go to your admin page, and sign in.
2. Create a new post, and publish (NOTE: for some reason when previewing the website is secure. Seems kind of funny). 
3. Visit your new page

### Technical details:

* Ghost Version: 1.13.1
* Node Version: v10.20.1
* Browser/OS: All browsers (only tested on firefox and edge). Windows
* Database: hmmm default?

**Comment by winters-brown** [comment]
Fixed an accidental code block.

**Comment by ErisDS** [comment]
I think @naz misunderstood your comment to mean you had fixed the issue.

Still this sounds like a support request relating to configuring https.

**Comment by lyricat** [comment]
Same issue. Even though I have already set the base url to `https://example.com` in config file.

**Comment by kevinansfield** [comment]
@lyricat if you need support, please use the forum https://forum.ghost.org

**Comment by lyricat** [comment]
@kevinansfield actually, i think it's a bug.

**Comment by winters-brown** [comment]
@lyricat 

for reference did you follow these instructions [here](https://forum.ghost.org/t/ghost-blog-returning-images-via-http-instead-of-https/9582) and restart your server?

https://forum.ghost.org/t/ghost-blog-returning-images-via-http-instead-of-https/9582

I will be testing on my personal server relatively soon... and will update here.

**Comment by winters-brown** [comment]
> 
> 
> @lyricat
> 
> for reference did you follow these instructions [here](https://forum.ghost.org/t/ghost-blog-returning-images-via-http-instead-of-https/9582) and restart your server?
> 
> https://forum.ghost.org/t/ghost-blog-returning-images-via-http-instead-of-https/9582
> 
> I will be testing on my personal server relatively soon... and will update here.

Upon making the mods and rebooting appears my website is now completely secure. If you would like you can view here

https://unorthodoxdev.com/https-connection-is-not-safe-due-to-images/

and view the images source.

**Comment by lyricat** [comment]
@winters-brown I have read both of the links before. But thank you for reminding me again, because i found that the true reason is that i forget to use `{{ img_url ... }}` some where. 

my website works fine now.

**Comment by winters-brown** [comment]
All good! Love to help
