### ISSUE TITLE
Upgrade from 3.5.0 to 3.14.0 Causes Members list to Disappear.

### ISSUE THREAD

**Issue by chukaofili** [TryGhost/Ghost#11778]
### Issue Summary

Upgrade from 3.5.0 to 3.14.0 Causes Members list to Disappear.

### To Reproduce

1. Install 2.38.1
2. Add subscribers
3. Upgrade to 3.5.0
4. Enable members & visit members list, confirm subscribers migrated ok.
5. Upgrade to 3.14.0
6. Visit members page to see empty list.

Expect to see migrated members list.

### Technical details:

* Ghost Version: v12.16.2
* Node Version: v12.16.2
* Browser/OS: Alpine (Docker Image ghost:3.14.0-alpine)
* Database: SQLite

### Logs

```
 [2020-04-28 06:02:34] ERROR "GET /ghost/api/v3/admin/members/?limit=all&order=created_at%20desc&include=labels" 400 1648ms
 
 Could not understand request.
 
 Error ID:
  da9492f0-8915-11ea-bdbe-1582ef1c85c9
 
 Error Code:
  SQLITE_ERROR
 
 ----------------------------------------
 
 BadRequestError: Could not understand request.
  at new BadRequestError (/var/lib/ghost/versions/3.14.0/node_modules/ghost-ignition/lib/errors/index.js:113:23)
  at /var/lib/ghost/versions/3.14.0/core/server/models/plugins/pagination.js:212:27
  at async listMembers (/var/lib/ghost/versions/3.14.0/core/server/api/canary/members.js:80:18)
 
 Error: SQLITE_ERROR: too many SQL variables
```

**Comment by pascalandy** [comment]
Try to update to 3.0.0, then to 3.14.0.

**Comment by chukaofili** [comment]
@pascalandy ok so I tried that, and i've still got the same issue.

**Comment by kevinansfield** [comment]
@chukaofili SQLite doesn't support the way members are loaded when you have a lot of members. You should switch to using MySQL for any production sites.

**Comment by chukaofili** [comment]
@kevinansfield Thanks, that solved the problem. Closing issue now.
