### ISSUE TITLE
Wrong navigation markup depending on the include order

### ISSUE THREAD

**Issue by eekes** [TryGhost/Ghost#11772]
### Issue Summary

It's my first time building a Ghost template or even working with Ghost, so I'm not sure if it's a bug or if it's just me doing something wrong.

I've been following the [documentation on navigations](https://ghost.org/docs/api/v3/handlebars-themes/helpers/navigation/) to create modify the custom markup of my primary and secondary navigations, but the output appears to be incorrect depending on the order I include the navigations.

### To Reproduce

I have 2 navigations like this:

- **Primary**
  - Home
  - About
- **Secondary**
  - Copyright

`partials/navigations.hbs` looks like this:

```
{{#if isSecondary}}
    <h2>Secondary</h2>

    {{#foreach navigation}}
        {{ label }}<br />
    {{/foreach}}

{{else}}
    <h2>Primary</h2>

    {{#foreach navigation}}
        {{ label }}<br />
    {{/foreach}}
{{/if}}
```

When doing this in`default.hbs`:

```
{{navigation}}
{{navigation type="secondary"}}
```

The output is correct:

```
<h2>Primary</h2>
Home<br />
About<br />

<h2>Secondary</h2>
Copyright<br />
```

If I'm doing this though:

```
{{navigation type="secondary"}}
{{navigation}}
```

This is the output:

```
<h2>Secondary</h2>
Copyright<br />

<h2>Secondary</h2>
Home<br />
About<br />
```

So the pages are always correct, but when including the secondary navigation first it always seems to be outputted as a secondary navigation.

### Technical details:

* Ghost Version: 3.13.4
* Node Version: 10.20.1
* Browser/OS: macOS Catalina
* Database: SQLite3 (local development)

*Ghost is amazing BTW* 😄❤️

**Comment by mattrjk** [comment]
Can confirm this issue as well. I've come up with a workaround that doesn't seem to have any ill effects. Assuming the default Casper theme:

1. Move the `{{> site-header}}` partial declaration above the `<header>`
2. Set the z-index for the special `home-template` class to 1000 (line 595 on screen.css)

I'd submit a PR, but I'm unsure if this is the best way without further testing.

**Comment by SKozak** [comment]
I fix this by change site-nav.hbs

{{navigation}}

to

{{navigation type="primary"}}

**Comment by mattrjk** [comment]
I like that idea better. Going to revert my changes and use the specific primary/secondary. That'll avoid any other issues with relocating the site-header partial.
