### ISSUE TITLE
OEmbed parsing does not correctly pass URL parameters

### ISSUE THREAD

**Issue by TeNNoX** [TryGhost/Ghost#11785]
### Issue Summary

I pass URL parameters to embedded content (in my case vimeo embed), but when pasting the URL it resolves only the plain URL (as oembed needs the parameters passed as actual parameters - not as part of the URL parameter)

### To Reproduce

1. Paste URL with params into Koenig: `https://vimeo.com/193244589?muted=true`
2. See that embedded video is not muted

When I get manually the oembed info - it works only when I put the original parameters as separate parameters:
`GET https://vimeo.com/api/oembed.json?url=https%3A%2F%2Fvimeo.com%2F260321751&muted=true`  
(instead of `https://vimeo.com/api/oembed.json?url=https%3A%2F%2Fvimeo.com%2F260321751%3Fmuted%3Dtrue`)

### Technical details:

* Ghost Version: 3.13.4
* Node Version: v12.16.1
* Browser/OS: Firefox Dev on elementary OS Juno
* Database: SQLite

**Comment by TeNNoX** [comment]
Vimeo reference:
https://developer.vimeo.com/api/oembed/videos

**Comment by TeNNoX** [comment]
It's not stale...

**Comment by ErisDS** [comment]
Stale bot is here to close issues that don't have any traction. This helps keep focus on the issues that matter the most and to the most people. I understand this is important to you, however that doesn't mean someone else will fix it. Ghost is open source, you always have the ability to submit fixes or find someone to fix a bug you care about.

If you have more input, or someone wants to work on this we can always reopen the issue.
