### ISSUE TITLE
CMD+S on tags input in post triggers browser save instead of post.

### ISSUE THREAD

**Issue by rishabhgrg** [TryGhost/Ghost#11786]
#### To Reproduce

In Ghost-Admin, focus on tags/author input in Post settings menu while editing a post and press Ctrl/CMD+S, it will trigger a browser save rather than saving the post which is expected behavior.

**Comment by rishabhgrg** [comment]
Update: The issue exists for all token input fields, including author and tags which blocks all our standard shortcuts on editor.

**Comment by matthanley** [comment]
This issue is also present on the social accounts inputs, so we'll need to test all inputs as part of this issue.

**Comment by rishabhgrg** [comment]
> This issue is also present on the social accounts inputs

@matthanley 🤔 Think the issue on social accounts is a different one, where doing CMD+S while staying on input after making changes shows the Save on Admin being run but doesn't save its value in DB.

The issue defined here is on all the token input styles in Admin where CMD+S triggers browser save instead of the Admin save behavior.

**Comment by rishabhgrg** [comment]
Hey @kevinansfield , will really appreciate your 👀 on this next week as I have hit a bit of mental block with my investigation on this. 

The problem is for all token input fields like tags or authors in post settings menu, where they are blocking out the keyboard shortcuts and so Cmd/Ctrl+S is triggering browser save window than our `save` action. I haven't been able to figure out where exactly the shortcuts is being prevented or if its not registered at all, any direction or inputs or if its a quick fix i am just not able to see will be very helpful :)

**Comment by ErisDS** [comment]
@rishabhgrg could you please share full details of what debugging you have done so that Kevin can pick up from where you've gotten to rather than having to start from scratch?

**Comment by rishabhgrg** [comment]
Updated the [original comment](https://github.com/TryGhost/Ghost/issues/11786#issuecomment-659960676) with debugging details.

**Comment by matthanley** [comment]
This is blocked needing some ❤️ from @kevinansfield 😄
