### ISSUE TITLE
Change password button does not reset its state

### ISSUE THREAD

**Issue by kevinansfield** [TryGhost/Ghost#11789]
On the staff user edit screen in Ghost-Admin, the change password button does not reset its state automatically.

If you enter non-matching passwords or passwords that are too short the button turns red and says "Retry". If you fix the passwords and retry the button stays red rather than turning green for the success state and does not automatically reset after a few seconds as buttons should now.

**Comment by m1kl** [comment]
I'm working on this issue. I'll submit a pull request as soon as possible.
