### ISSUE TITLE
When downloading installed theme the .well-known folder is not included

### ISSUE THREAD

**Issue by ScottHelme** [TryGhost/Ghost#11794]
### Issue Summary

When downloading my currently installed theme the `.well-known` folder is not included. There are various security standards [1][2] that require website operators to host files in the `.well-known` folder. It would be useful if this folder and the contained files were included when downloading an installed theme.

[1] [Improving email security with MTA-STS](https://scotthelme.co.uk/improving-email-security-with-mta-sts/)
[2] [Say hello to security.txt](https://scotthelme.co.uk/say-hello-to-security-txt/)

### To Reproduce

1. In the root of a theme create a folder called `.well-known`.
2. Upload the theme in the Design section of Settings.
3. Download the theme and note that the `.well-known` folder is missing.

As these files are added in the theme it seems they should also be downloaded with the theme.

### Technical details:

I'm using hosted Ghost(Pro) and have not tried to reproduce this on a self-hosted installation.

**Comment by ErisDS** [comment]
FYI you should find this works now.

**Comment by ScottHelme** [comment]
@ErisDS confirming this now works as intended! Thanks 👍
