### ISSUE TITLE
Missing <meta "description"> in the posts

### ISSUE THREAD

**Issue by ltoinel** [TryGhost/Ghost#11803]
### Issue Summary

The meta tag description seems to have disappears from the gost_headers on the post pages.
However the og:description, json-ld and twitter:description are well filled.

The correct behavior should be to use the excerpt or the beginning of the HTML post to generate this description automatically if this meta description is not filled on the admin page, correct ? 

### To Reproduce

Write  a post with no meta description but with an excerpt and check the presence of the meta description on the post HTML page. The meta description is missing.

### Analyze

The only way to add this meta description header is to fill the "Meta data description" in the admin panel.

The excerpt is ignored, and the HTML content also ignored to generate a summary of the post.

The issue come from the "description.js".  The excerpt and the html content is used only of the "option" attribute is fulled in the getDescription function.

``` javascript
    } else if (_.includes(context, 'post') && data.post) {
        if (options.property) {

            // In the case of twitter description or OpenGraph, everything is OK !
           // The excerpt is used and the HTML content also to generate a meta description.

            description = data.post[`${options.property}_description`]
                || data.post.custom_excerpt
                || data.post.meta_description
                || getExcerpt(data.post.html || '', {words: 50})
                || settingsCache.get('description')
                || '';
        } else {

            // In the case of the getDescription for a Meta Description for a page
            // We only is the value of the meta_description filled in the portal.

            description = data.post.meta_description || '';
        }
```
### Technical details:

* Ghost Version: 3.15.3

**Comment by kevinansfield** [comment]
> The correct behavior should be to use the excerpt or the beginning of the HTML post to generate this description automatically if this meta description is not filled on the admin page, correct ?

No, if you need a custom meta description you need to fill in a meta description. This allows for search engines to more often highlight the relevant areas of your page when searching rather than always showing a less-specific/relevant automatically-filled description (actual behaviour is always search-engine specific).

Closing as the current behaviour is as-intended.

**Comment by ltoinel** [comment]
Thank-you, what about the excerpt ? 
This excerpt cannot be used is a specific meta description is not filled ?

**Comment by ErisDS** [comment]
> No, if you need a custom meta description you need to fill in a meta description. **This allows for search engines to more often highlight the relevant areas of your page when searching rather than always showing a less-specific/relevant automatically-filled description** (actual behaviour is always search-engine specific).
