### ISSUE TITLE
RSS feed is broken since (at least) Sep 2018 for markdown and html cards

### ISSUE THREAD

**Issue by fadeevab** [TryGhost/Ghost#11804]
### Issue Summary
Because my articles contain Markdown cards, there is an error in Firefox (which doesn't allow to use RSS clients as well).

Go to `https://<blog>/rss/`  (I fixed on my website already, so it's not reproducible there!) and you will see:

![image](https://user-images.githubusercontent.com/49716172/81423267-eef0d200-915c-11ea-98bc-5b4e4423699e.png)

### To Reproduce
1. Create an empty post.
2. Insert Markdown card. Write something.
![image](https://user-images.githubusercontent.com/5967447/81432040-dd162b80-916a-11ea-8bd8-68a5efcd5497.png)
3. View preview.
![image](https://user-images.githubusercontent.com/5967447/81429862-1e0c4100-9167-11ea-8ae5-e9670c0c2336.png)
4. View sources of the preview page.
![image](https://user-images.githubusercontent.com/5967447/81429943-43994a80-9167-11ea-8f4f-fac76e70e4e0.png)
5. There is `<!--kg-card-begin: markdown-->` tag inside.

### Technical details:

* Ghost Version: 3.3.0, 3.15.3
* Node Version: 12.16.2
* Browser/OS: Firefox 76.0
* Database:

### Investigation

Here the root of cause:
```
$ grep -rni commentWrapper
node_modules/@tryghost/kg-default-cards/lib/cards/html.js:10:        commentWrapper: true
node_modules/@tryghost/kg-default-cards/lib/cards/_markdown.js:14:            commentWrapper: true
```
**Definition of done:** `commentWrapper: false`

Even after bugfix the content remains "corrupted". After the upgrade it's necessary to traverse all pages, edit them, and re-save.
1. Edit.
2. Add symbol
3. Save.
4. Remove char.
5. Save.

After that tags `<!--kg-card-start: markdown-->` and `<!--kg-card-end-->` will be eliminated and RSS starts working.

**Comment by ErisDS** [comment]
Hey @fadeevab could you please provide a full reproduction case and version info as required by our issue template? I cannot reproduce markdown cards breaking RSS in firefox.

**Comment by fadeevab** [comment]
Done.

**Comment by fadeevab** [comment]
Also you can find the example here: https://fadeevab.com/p/5238b4f1-0fb3-466f-9ea5-71b875e38cc2/
(I will remove it later)

**Comment by fadeevab** [comment]
And how it looks like when you edit:
![image](https://user-images.githubusercontent.com/5967447/81432040-dd162b80-916a-11ea-8bd8-68a5efcd5497.png)

**Comment by ErisDS** [comment]
It looks to me like you've maybe copy and pasted a control character in the admin?

Here's me following your steps on a live site, all done in firefox 76:

https://hannah.wf/untitled-5/
https://hannah.wf/rss/

**Comment by fadeevab** [comment]
Right, this is from your site:
![image](https://user-images.githubusercontent.com/5967447/81433915-ff5d7880-916d-11ea-8ea5-76e3035a5e60.png)
Just RSS is not shown as broken

**Comment by fadeevab** [comment]
Do you think the RSS error is not directly related to , but to something near it while adding the card? I just had to fix all my posts starting from 2018 to eliminate the error, and all of them were related to  somehow...

**Comment by fadeevab** [comment]
Yeah, I returned that comment back, and re-saved one page, where bug previously reproduced, and RSS is still alive, so seems like the bug is not about it.

**Comment by fadeevab** [comment]
Ok, next time I reproduce I will create another issue. Thank you for your assistance.
