### ISSUE TITLE
Structured data error

### ISSUE THREAD

**Issue by alwaysmpe** [TryGhost/Ghost#11816]
### Issue Summary

When validating a post structured data using [Google's structured data testing tool](https://search.google.com/structured-data/testing-tool/) I receive an error.

### To Reproduce

As per #11746 I'm receiving a structured data error, same place with different circumstances.

Steps:
1. Site with icon and logo configured
2. Create post
3. Validate post structured data - error is shown

The page I was validating: https://adhdwhat.com/bad-adhd-cant-stop/
Quick link to page validation: [structured testing tool](https://search.google.com/structured-data/testing-tool/u/0/#url=https%3A%2F%2Fadhdwhat.com%2Fbad-adhd-cant-stop%2F) (NB: the error message is a bit confusing)

current format:
```
    "publisher": {
        "@type": "Organization",
        "name": "ADHD, what?",
        "url": "https://adhdwhat.com/",
        "logo": "https://adhdwhat.com/content/images/2020/05/ADHDwhat-full.jpg"
    }
```
expected format (modifying to this and revalidating fixes the error):
```
    "publisher": {
        "@type": "Organization",
        "name": "ADHD, what?",
        "url": "https://adhdwhat.com/",
        "logo": {
            "@type": "ImageObject",
            "url":"https://adhdwhat.com/content/images/2020/05/ADHDwhat-full.jpg"
        }
    }
```
### Technical details:

As per #11746 the following function is responsible:
https://github.com/TryGhost/Ghost/blob/17ee76c01336d8f2af9a7eac0322f050c3f7c5cf/core/frontend/meta/schema.js#L6
The function is returning a url instead of an ImageObject, as far as I can tell (I don't know anything about structured data!) the only valid return value is an ImageObject (or null).

I don't have a dev environment of Ghost (yet, I suspect I will before long), so can't verify the fix.

* Ghost Version: 3.15.3

**Comment by pr3d** [comment]
To narrow this down, I just tried a couple of things. Hope it helps. =)

1. With no `Publication icon` and no `Publication logo`:

```json
"publisher": {
        "@type": "Organization",
        "name": "BB",
        "url": "http://localhost:2368/",
        "logo": {
            "@type": "ImageObject",
            "url": "http://localhost:2368/favicon.ico",
            "width": 48,
            "height": 48
        }
    },
```

2. With `Publication icon` (650x650px) and no `Publication logo`:

```json
"publisher": {
        "@type": "Organization",
        "name": "BB",
        "url": "http://localhost:2368/",
        "logo": {
            "@type": "ImageObject",
            "url": "http://localhost:2368/favicon.png",
            "width": 60,
            "height": 60
        }
    },
```

3. With no `Publication icon` and `Publication logo` (601x73px):

```json
"publisher": {
        "@type": "Organization",
        "name": "BB",
        "url": "http://localhost:2368/",
        "logo": "http://localhost:2368/content/images/2020/05/601_73.png"
    },
```

4. With `Publication icon` (650x650px) and `Publication logo` (650x650px):

```json
"publisher": {
        "@type": "Organization",
        "name": "BB",
        "url": "http://localhost:2368/",
        "logo": {
            "@type": "ImageObject",
            "url": "http://localhost:2368/content/images/2020/05/650x650-2.png",
            "width": 60,
            "height": 60
        }
    },
```

5. With `Publication icon` (650x650px) and `Publication logo` (601x73px):

```json
"publisher": {
        "@type": "Organization",
        "name": "BB",
        "url": "http://localhost:2368/",
        "logo": "http://localhost:2368/content/images/2020/05/601_73-1.png"
    },
```

- Image 650x650px:  
https://user-images.githubusercontent.com/9925957/81982831-ab053d80-9632-11ea-98fd-d5601f4641d7.png
- Image 601x73px:  
https://user-images.githubusercontent.com/9925957/81982832-ab9dd400-9632-11ea-84ec-394943e68ac6.png)

**Comment by aileen** [comment]
I've re-opened the original issue, as it was not fixed.

We definitely always need to output the publisher logo as an `ImageObject` which has changed since the code was first implemented. I'm working on a fix for this.

wrt to the last message and the dimensions being listed or not: Ghost follows the guidelines for AMP publisher logo as described [here](https://developers.google.com/search/docs/data-types/article#logo-guidelines). We only output the publisher logo image dimensions when they actually fit the requirements that are listed in there.

Going to close this issue, as I re-opened the [original](https://github.com/TryGhost/Ghost/issues/11304)

**Comment by alwaysmpe** [comment]
Awesome @aileen, I wasn't sure where the best place to raise it was, I couldn't reopen the other issue and didn't want a comment to be lost in the aether! Also worth mentioning (I've not looked too much into this), I think the image dimensions don't always match the image when they are output (pr3d included some examples).

Aside, is there anywhere high priority/planned work is listed? I'm a software engineer not currently working so I might have some time to get my hands dirty soon :)

**Comment by ErisDS** [comment]
@alwaysmpe we use the [help wanted](https://github.com/TryGhost/Ghost/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22) label for any issues we think are worth tackling but that the Ghost team are not likely to get to work on.
