### ISSUE TITLE
Storage S3 adapter broken with 3.15.3

### ISSUE THREAD

**Issue by yakhatape** [TryGhost/Ghost#11810]
### Issue Summary
Storage S3 adapter looks like broken with the new release 3.15.3 where it was working under 3.14.0.

On start ghost return adapter S3 not able to found in folder content/adapters/storage

### To Reproduce

1. Install the S3 adapter storage 
2. Setup your config json prod
3. Start your ghost instance you will see the error

This is a bug to my pov because the same setup is working like a charm on 3.14

Both stack are deploy by the same ansible playbook roles etc.. 

Just ghost version change because my ansible role install the latest ghost version. 

### Technical details:

* Ghost Version: 3.15.3
* Node Version: 12
* Browser/OS:ubuntu 18.04
* Database: mysql

 Staying at disposal if needed

**Comment by rishabhgrg** [comment]
👋 Hey @yakhatape , can you please specify which S3 storage adapter you are using in this case ?

**Comment by ErisDS** [comment]
Gonna close this as based on the information we have it seems like a problem with a specific storage adapter. Can reopen if more information is provided that shows this isn't true.
