### ISSUE TITLE
Ghost ignores Publication Language

### ISSUE THREAD

**Issue by chibiribiri** [TryGhost/Ghost#11817]
### Issue Summary

I'm not pretty sure, if this is really an issue with Ghost or maybe with the theme I use.

I use the theme _Astro_ by EckoThemes and did a translation. So i put the json-file in the folder _locales_ in the theme-directory. I uploaded and activated the theme. Beforehand I filled the textfield _Publication Language_ with _de_.

But it didn't work. So i removed the _en.json_-file. Same result.

Next step: Restarting Ghost - somehow this works... as long I don't upload an edited version of the theme through Ghost-Admin or switch themes (e.g. to Casper and then back to Astro). 
It can be only fixed by restarting Ghost.

### To Reproduce

1. Create translation and put it in the correct folder of the theme-directory (locales)
2. Zip the theme
3. Upload the theme through _Ghost-Admin_
4. Set the _Publication Language_

Can be temporary fixed by restarting Ghost.

### Technical details:

* Ghost Version: 3.14.0
* Node Version: 10.19.0
* Browser/OS: Edge (Chromium based)/Windows 10 19H2
* Database: 5.5.5-10.3.22-MariaDB

**Comment by naz** [comment]
Hey @chibiribiri :wave: As pointed out in Ghost's documentation - https://ghost.org/docs/api/v3/handlebars-themes/helpers/translate/#7-reactivate-the-theme, you need to restart Ghost process with `ghost restart` after for translation related changes to take effect :wink:

**Comment by naz** [comment]
@chibiribiri, was trying to dig a little bit more deeper into the issue to make sure I understood the problem correctly. Have tried changing  "Publication Language" through admin panel using [Attila](https://github.com/zutrinken/attila) theme which has [very big list](https://github.com/zutrinken/attila/tree/master/locales) of supported languages.
2 things that have noticed:
1. There is no need to restart Ghost instance between Publication Language change. After saving the setting and reloading a page with a post it picks up correct locale.
2. The localization works correctly with properly configured theme like Attila (this gives a clue there might be a problem with a theme you are using)

I tried this flow on both latest Ghost master and `3.14.0` which you referenced running on Node v12. Could you confirm if the localization works properly with Attila theme for you?

**Comment by ErisDS** [comment]
Gonna close this for now as it seems it's likely a theme problem more suited to https://forum.ghost.org.

We can always reopen if that turns out to be wrong.
