### ISSUE TITLE
Code tag within a heading in the editor ignores font-size

### ISSUE THREAD

**Issue by javorszky** [TryGhost/Ghost#11814]
### Issue Summary

In the editor
when I want to write a heading that contains a code block
then the formatting of the code block ignores heading font-size, but not font-weight

See this gif:

![Screen Capture on 2020-05-12 at 10-51-29](https://user-images.githubusercontent.com/1196299/81669822-a841f700-943e-11ea-939c-a388b2b5ff2d.gif)

### To Reproduce

1. Start writing a heading.
2. Add something in single backticks: `code`
3. See that it is a different size.

I think it's a bug because if the editor formats my heading, it should probably format all of the heading and not exclude the code.

If the code is inside a markdown block, it should probably not format it, though I haven't checked that outcome.

### Technical details:

  * Ghost Version: 3.15.3
  * Node Version: whatever is on (pro)
  * Browser/OS: Firefox 76.0.1 (64-bit) / macOS Catalina 10.15.4 (19E287)
  * Database: whatever is used on (pro)

**Comment by kevinansfield** [comment]
This is a CSS issue within the editor only, it does not affect the output of the editor which is entirely up to the installed theme. 

Happy for any contributions 🙂

**Comment by pmartijena** [comment]
New to open source, but I’ll take a stab at this :-)

**Comment by devaman** [comment]
I like to look in this 😃
