### ISSUE TITLE
Ghost is a scam - Ghost CMS is buggy and rubbish!

### ISSUE THREAD

**Issue by warlockeg** [TryGhost/Ghost#11818]
Ghost is full of bugs on Ubuntu 18 and Debian, i tried every Ghost image on Google Cloud and none of them worked properly, why you do not have a real reliable image bug free there and do not ask me to post on your forum, it is not Google indexed!

the only reason you are asking people not to report bugs on github is:
1- Your forum bugs report is not Google indexed, you simply blocked Google bots from indexing them to avoid scaring people with thousands of bugs reports every day.

2- Sooner or later you will need to hire smart developers who can fix the Ghost bugs and turn it into a real Blogging CMS instead of a bug training arena where users get to learn about how to solve Systemd and NodeJs issues when they update Ghost and how to take a Database dumb and export it to import it on a new server with new Ghost and in the end how to switch back from Ghost to WordPress !!!!!!!!!!!!!!!!!!!!!!

**Comment by naz** [comment]
Please be advised to follow our community guidelines - https://ghost.org/conduct/#community-dbad
