### ISSUE TITLE
Administrator user cannot edit owner user posts

### ISSUE THREAD

**Issue by frantzypants** [TryGhost/Ghost#11825]
### Issue Summary

While logged in as an administrator user it is not possible to edit an owner user's post without receiving a permission error.

![image](https://user-images.githubusercontent.com/6034248/82355146-d2ac2b00-99cf-11ea-98ba-e6e6ca0daedb.png)
<img width="1184" alt="Screen Shot 2020-05-19 at 12 48 51 PM" src="https://user-images.githubusercontent.com/6034248/82355180-ddff5680-99cf-11ea-8e8f-73ec1d39c397.png">

### To Reproduce

1. Create a post as the owner user
2. Login as an administrator user
3. Observe you **cannot edit** an owner user's post
4. Login as an editor user
5. Observe that you **can edit** an owner user's post.

Expectation would be that an admin can edit an owner user's content.

### Technical details:

Version 3.15.3
Environment production
Database mysql
Mail SMTP

**Comment by daviddarnes** [comment]
Also reported on the forum: https://forum.ghost.org/t/admin-cant-change-post-access-type/14431
