### ISSUE TITLE
wrong cyrillic transliteration for Bulgarian

### ISSUE THREAD

**Issue by lordcris** [TryGhost/Ghost#11831]
I have a ghost blog where I write using the cyrillic alphabet ( Bulgarian ).
When I publish my post the transliteration of the url and tags is a bit off.
example:

“без” -> “biez”
instead of
“без” -> “bez”

Where can I change the transliteration map?
thanks

**Comment by allouis** [comment]
This is handled by https://www.npmjs.com/package/unidecode! I would open an issue there :relaxed:
