### ISSUE TITLE
Accessibility: Remove overcealous menu semantics from navigation helper

### ISSUE THREAD

**Issue by MarcoZehe** [TryGhost/Ghost#11832]
### Issue Summary

The navigation that gets injected in the header of Caspar (and possibly other themes), if navigation items are defined in Admin/Design, uses menu and menu item roles on the ul and li elements respectively. This is overcealous, and hides the actual links from assistive technologies, making them difficult to reach (Windows), or even inaccessible (iOS). Furthermore, menu and menu item roles set an expectation of a certain keyboard navigation model, which is not met. See the [WAI-ARIA design pattern](https://www.w3.org/TR/wai-aria-practices-1.1/#menu) for further details.

Affected browser and assistive technologies range from Firefox+NVDA on Windows to Safari+VoiceOver on iOS and iPadoS.

### To Reproduce

1. Launch a default Ghost install on your favorite platform, or visit a web site that uses Caspar.
2. On iOS, go to Settings/Accessibility and scroll down to accessibility shortcut. Set it to be VoiceOver. Then return to Safari and triple-tap your home button (if your device has one) or the power button to turn VoiceOver on.
3. Start swiping to the right, and after the logo/site, listen to VoiceOver saying "menu item", "menu item", but nothing else. Later, if there are social links, it will read "Facebook, link" or such.

Instead, I expect VoiceOver to read the navigation link items followed by "link", possibly accompanied by list item semantics.

### Technical details:

* Ghost Version: Current, for example on Ghost Pro.
* Node Version: Same.
* Browser/OS: Firefox 76 on Windows, or Safari on iPadOS.
* Database: All.

**Comment by MarcoZehe** [comment]
@ErisDS can the documentation [here](https://ghost.org/tutorials/adding-social-network-links/) be updated to no longer mention these menu and menuitem roles as well? Otherwise, people following this guide in the future might add the problems back to their copy of Caspar.

**Comment by daviddarnes** [comment]
Hey @MarcoZehe, just wanted to let you know that I've updated the tutorial. Thanks for highlighting this 😊
