### ISSUE TITLE
Memberships don't work when both publishers and subscribers are from India

### ISSUE THREAD

**Issue by sudhirj** [TryGhost/Ghost#11839]
### Issue Summary

When a publisher sets up a Stripe account based in India, the following rules apply to all transactions initiated on that account: https://support.stripe.com/questions/requirements-for-india-export-charges

This means that when the publisher sets up a membership with prices in USD, it works everywhere in the world except for India – because the subscriber is trying to pay with an INR payment method, but because the seller is an INR Stripe account presenting in USD, they're not allow to sell back into INR. Transactions that are Buyer INR -> Stripe presenting USD -> Seller INR will fail on Stripe with a message pointing to the rules above. 

### To Reproduce

Try to subscribe to https://dbProject.RED and choose your billing country as India. The set is currently configured with test keys, so you can use the cards on https://stripe.com/docs/testing

You'll see that all attempts to subscribe fail only when the billing address country is India. 

I'd suggest Ghost ask for billing currency before sending people to the Stripe checkout page, and keep different prices per currency for the same plan (this is already supported by Stripe). This will allow us to handle this problem by specifying a separate price for INR, and will also help those who want to offer lower prices for countries / currencies at different economic levels of development. 

It will also help non-USD publishers avoid the ~3% conversion of worldwide subscribers to USD, and then the ~3% for changing USD back to their base currency.

### Technical details:

* Ghost Version: All
* Node Version:
* Browser/OS:
* Database:

**Comment by gaurav569** [comment]
Please Consider Adding Support For INR

**Comment by ErisDS** [comment]
We recently added [support for INR](https://github.com/TryGhost/Ghost/commit/edff7ac85305017b90f740a00ec5d48a089445c0) as a currency, which I believe is an effective fix for this issue, as sellers can now sell directly in INR.

Multiple currency support is a feature request, which we don't track on GitHub. There are several posts about it on the forum though 🙂
