### ISSUE TITLE
Enhance editor styling support (strikethrough)

### ISSUE THREAD

**Issue by apfelbox** [TryGhost/Ghost#11843]
### Issue Summary

Right now strikethrough (~~test~~) isn't supported anymore in the editor anymore? It used to work with markdown's style in the old editor `~~test~~`, but isn't triggered anymore.

While mobiledockit does support it, there doesn't seem to be an input scheme or a hotkey to toggle it?

(if it's relevant: I am using German keyboard layout, where the `~` itself is a dead key.)

### To Reproduce

1. Try to strike any text.

### Technical details:

* Ghost Version: –
* Node Version: –
* Browser/OS: –
* Database: –

**Comment by apfelbox** [comment]
There are other styles that don't seem to be supported as well.. are they important enough to add?

**Comment by ErisDS** [comment]
I can't reproduce an issue here - strikethrough works perfectly for me. so either it's a German keyboard bug, or perhaps a usage error?

Markdown expansions happen as you type, so if you're not typing the characters sequentially it wouldn't be triggered. That is to say if you type `~~test~~` you should find the strikethrough is triggered on the final `~`.

**Comment by apfelbox** [comment]
Doesn't work for me:

![Kapture 2020-05-26 at 20 06 05](https://user-images.githubusercontent.com/1032411/82934818-68c1f180-9f8c-11ea-8131-6db6e3eb7915.gif)

Probably related to the dead keys (you can see it with the underline). Probably the same fix from https://github.com/TryGhost/Ghost/issues/9825 needed here?

**Comment by loicortola** [comment]
Hello, looking at the same feature here! Any solution to implement strikethrough?

**Comment by Gymnae** [comment]
I am also suffering from this bug, please reopne
