### ISSUE TITLE
Minor warning cli@ The engine "cli" appears to be invalid.

### ISSUE THREAD

**Issue by thisconnect** [TryGhost/Ghost#11844]
### Issue Summary

When installing ghost install there is a minor warning 
`warning ghost@3.16.1: The engine "cli" appears to be invalid.`

### To Reproduce

1. `ghost install --verbose`

### Technical details:

* Ghost Version: 3.16.1
* Node Version: v12.16.3
* Browser/OS: -
* Database: -

**Comment by ErisDS** [comment]
This is a warning, not an error. Ghost CLI requires this.

**Comment by mlc-mlapis** [comment]
@ErisDS It's a warning, OK, but how to eliminate it? Is there a known reason why it appears? And what to do to correct it?

> The engine "cli" appears to be invalid.

**Comment by ErisDS** [comment]
It’s a warning from npm saying that the engines value “appears incorrect” because it’s something npm doesn’t & isn’t supposed to recognise - it’s for Ghost-CLI.

Nothing is wrong, there’s nothing to correct, just ignore it.
