### ISSUE TITLE
Plain text format for Ghost emails

### ISSUE THREAD

**Issue by jloh** [TryGhost/Ghost#11859]
At the moment Ghost doesn't send a plain-text formatted email for some of its email notifications like Password Resets, Members Sign Ups/Ins and others.

To give email readers a fallback options (and a better preview!) it would be good to add a plain text version of these emails.

**Comment by ErisDS** [comment]
Not sure this is correct, or at least by my understanding of what it means to include a fallback. Waiting for more info.

**Comment by jloh** [comment]
Damn, you're totally right. Sorry for the noise. I must've completely misread the source email I tested off AND missed the setting on the tool I was using 😭

Closing issue.
