### ISSUE TITLE
Staff profile editing incorrectly show "Saved" state

### ISSUE THREAD

**Issue by hkdobrev** [TryGhost/Ghost#11866]
### Issue Summary

When you're editing a staff profile in the admin, edits to the slug make the "Save" button to change to "Saved" even though nothing is saved yet until the "Saved" button is clicked.

### To Reproduce

1. Log in as an administrator.
1. Go to "Staff" section from the sidebar.
1. Edit an author profile.
1. Change the ~name~ <ins>slug</ins>.
1. Click outside the input to unfocus it.
1. Notice the blue "Save" button changes to green "Saved". At this point, most would consider that it has autosaved the changes.
1. Navigate to another page, you will get prompt if you're sure as changes are not saved.
1. If you reload the page, you are not prompted and changes are indeed not saved.
1. You are able to click the green "Saved" button to actually save changes.

Potential solutions:

- introduce actual autosaving on every form 😉 
- make the "Save" / "Saved" buttons on the author edit page behave like everywhere else - keep the blue "Save" button until data is indeed saved.

Other considerations:

When the form is not saved, reloading the page could also trigger a prompt from the browser to confirm the navigation during that dirty state.

### Technical details:

* Ghost Version: 3.17.1
* Node Version: 12.16.2
* Browser/OS: Google Chrome Version 84.0.4143.7 (Official Build) dev (64-bit)
* Database: local install using `ghost install local`

**Comment by rishabhgrg** [comment]
Can reproduce this issue on both 3.17.1 and the latest version, but only on changing the user slug field and not on changing the name, working on a fix

**Comment by hkdobrev** [comment]
I can confirm I was indeed changing the slug, but when writing up the issue I didn't test whether the problem was field-specific. Updated the steps to mention editing the slug. Thanks!

**Comment by rishabhgrg** [comment]
Weirdly, it seems ember-concurrency seems to be triggering all the tasks in a task group as in this case we are explicitly passing down the save task to task button but its states are still triggered when the updateSlug task in the same task group is called, although from the docs i couldn't find anything that suggests this or how to bypass this.

I added a check to our task buttons to always check if the last task's name is same as the task name passed down before updating state, which takes care of group tasks and also shouldn't cause any side-effects imo, but want to run this by for review in case I missed anything that this will break or if there is a better way to handle this.

**Comment by rishabhgrg** [comment]
Just waiting on the final review on approach before merge :)
