### ISSUE TITLE
html iframe will not close properly; Subsequent content is not shown.

### ISSUE THREAD

**Issue by dbauszus-glx** [TryGhost/Ghost#11891]
I am using a hosted ghost(pro) instance. I'd like to say v3 but that is not clear from the ghost(pro) interface.

I create iframe html embeds which work for starters but for some odd reason the iframe html embed is not closed and content after the embed is not shown.

Creating a `<div width=100%>foo</div>` works as expected.

![image](https://user-images.githubusercontent.com/22201617/84161888-aa13d000-aa67-11ea-8f1a-7eb28ef026e8.png)

This iframe however will display without a closing note in the dom and any content after the embed will not be shown in the content pane.

```
<iframe width=100% src="https://geolytix.xyz/geodata/view/blog?layers=Mapbox%20Baselayer,Mapbox%20Labels,Postal%20Sector,Postal%20District,Postal%20Areas&locations=Postal%20District!website.vw_london_glx_geodata_postal_district!1480000745&host=/geodata&locale=London&lat=51.54669457515874&lng=-0.036424811718581265&z=12.658892118456206">
```

**Comment by daviddarnes** [comment]
Hey @dbauszus-glx, just answered your query on the forum:
https://forum.ghost.org/t/content-not-shown-after-embedded-iframe/14986/2
