### ISSUE TITLE
Error in example data (JSON-LD)

### ISSUE THREAD

**Issue by tidyui** [TryGhost/Ghost#11908]
After creating a new local site with the latest version of `ghost-cli` and `ghost`, the page "Publishing options" contains malformed content in the `JSON-LD` example:

~~~json
{
    "@context": "https://schema.org",
    "@type": "Article",
    "publisher": {
        "@type": "Organization",
        "name": "Publishing options",
        "logo": "https://static.ghost.org/ghost-logo.svg"
    },
    "author": {
        "@type": "Person",
        "name": "Ghost",
        "url": "http://demo.ghost.io/author/ghost/",
        "sameAs": []
    },
    "headline": "Publishing options",
    "url": "http://demo.ghost.io/publishing-options",
    "datePublished": "2018-08-08T11:44:00.000Z",
    "dateModified": "2018-08-09T12:06:21.000Z",
    "keywords": "Getting Started",
    "description": "The Ghost editor has everything you need to fully optimise your content. This is where you can add tags and authors, feature a post, or turn a post into a page.",
    }
}
~~~

After `description` there's a right curly bracket too much. When pasting the exampled into the google validation tool linked above in the article validation fails.

Best regards.

**Comment by ErisDS** [comment]
I'm not able to reproduce what you're saying, either on a brand new site:

**Comment by ErisDS** [comment]
Pressed enter too soon. Please provide more info.

**Comment by tidyui** [comment]
No, there’s nothing wrong in the REAL functionality! The error is in the example content in the page that you read, ie the default seeded content of a new site. The code block that renders the example JSON that I posted (which is the same in your link) has a curly bracket too much.

Again, this is NOT a functional error, just a content error in the default seeded post.

Regards
