### ISSUE TITLE
Various radio buttons and check boxes in the Ghost admin not accessible

### ISSUE THREAD

**Issue by MarcoZehe** [TryGhost/Ghost#11923]
### Issue Summary

Several checkboxes and radio buttons in the Ghost admin interface are not screen reader accessible. They simply do not show up as checkboxes or radio buttons. Examples include:

- The Pin This Post checkbox at the bottom of the post screen.
- The radio buttons to publish now or publish later in the Publishing popover.
- The Radio buttons in the Labs Members section that indicate whether a post should be public, members-only or paid-members only by default.

There are more, but these are the common ones. There are also checkboxes that are not inaccessible, such as the one in the Publishing popover that says "Send this to members via e-mail".

### To Reproduce

1. With Firefox or Chrome and NVDA on Windows, or Safari and VoiceOver on Mac, navigate to the post screen, for an existing or new post.
2. Focus the Pin This Item near the bottom of the screen.

A screen reader user will not know if this is checked or not, nor that it is actually a checkbox.

### Technical details:

* Ghost Version: All recent versions, including 3.19.2.
* Node Version: Current.
* Browser/OS: Firefox 77 on Windows 10, Safari 13 on macOS Catalina, Chrome 83 or whatever latest version on either Windows or Mac.
* Database: N/A.

For more info, and the correct way to style checkboxes and represent them with an SVG in an all inclusive, accessible manner, see [this very recent article](https://www.sarasoueidan.com/blog/inclusively-hiding-and-styling-checkboxes-and-radio-buttons/) by @SaraSoueidan.

**Comment by rkingett** [comment]
This also applies to sighted keyboard users because focus can't be reliable. [Here's a general overview of keyboard accessibility.](https://webaim.org/techniques/keyboard/)

**Comment by MarcoZehe** [comment]
This issue is still present in current Ghost.

**Comment by sbeinlich** [comment]
I will attempt to work on this issue

**Comment by tuijapalovuori** [comment]
Me and my group will try to work on this. If you have a fuller list of problems to give, that would be very useful to us, but we can also look for them ourselves.

**Comment by rkingett** [comment]
There are too many to list, but this Access bot can help look for accessibility issues in pull requests. https://github.com/marketplace/accesslint

**Comment by rkingett** [comment]
Unfortunately, this is still an issue and there are way too many to list, even in 4.0.
