### ISSUE TITLE
AMP Validation Error: A mandatory attribute is missing form an HTML tag

### ISSUE THREAD

**Issue by yeldarby** [TryGhost/Ghost#11920]
### Issue Summary

Google Search Console sent us an email that we had an AMP validation issue on one of our blog's Ghost pages. Turns out that it was a missing `src` attribute on several `amp-img` tags. After digging in, the root of the issue was that the non-amp post was using a `data-url` and the `amp` version simply omitted the attribute in that case.

Our workaround was to right click the image, save to disk, and re-upload so it would be a normal `src` link rather than a `data-url`.

### To Reproduce

1. Create a graph in Excel
2. Copy/paste that graph into a Ghost Post
3. Publish
4. Run the amp version through [Google's amp validator](https://search.google.com/test/amp)

The main post will look fine and have the image with a `data-url` `src` attribute.
The amp post image will be broken and produce validation errors.

### Technical details:

* Ghost Version: Hosted (Standard)

**Comment by ErisDS** [comment]
Can you please share example content/data that we can use to reproduce the problem? No one here has Excel.

**Comment by yeldarby** [comment]
Drag and drop [the cat image from this page](https://dopiaza.org/tools/datauri/examples/index.php) into a ghost post from another browser window and you will end up with a `data:image/jpeg` link that works in a normal post:
![image](https://user-images.githubusercontent.com/870796/84825817-a3490800-afe7-11ea-845a-2cf69202d3bd.png)

But doesn't work in `amp` because it's missing an `src`:
![image](https://user-images.githubusercontent.com/870796/84825963-de4b3b80-afe7-11ea-9329-8d6d6de3d1f2.png)

**Comment by yeldarby** [comment]
This is still an issue.

**Comment by JohnONolan** [comment]
If you can provide a reproducible test case then we can look into this but based on the screenshots you've posted you are not running on the latest version of Ghost and you've not given any further details that would allow anyone to debug or reproduce the behaviour you're talking about. 

The image above worked no problem when tested here:

<img width="806" alt="image" src="https://user-images.githubusercontent.com/120485/93474146-2ba9b280-f921-11ea-9f05-152a76046396.png">

This issue has been open for 3 months without any clear info or reproducible steps to verify any bug exists, so I'm closing it from here - If you want to update to the latest version of Ghost and/or provide more information, we can certainly look into it.

**Comment by yeldarby** [comment]
First off: yikes, what a user hostile way to respond to a bug report in your software. The reason it has been open for 3 months is that nobody responded to the repro case...

Second: we pay for you all to host our site. If we're not on the latest version of Ghost that sounds like a you problem. (But likely it's just that the bug report was ignored for 3 months so obviously a 3 month old screenshot was not teleported back in time from the presen.)

Third: this is still a problem with that test case image. As mentioned, drag and drop it from another browser window. It's reproducible:
![image](https://user-images.githubusercontent.com/870796/93486580-fd4cb880-f8c9-11ea-9b5f-3611f3726367.png)

**Comment by JohnONolan** [comment]
You are literally responding to a screenshot of me following your exact reproduction steps and the issue was demonstrably _not_ reproduced. Yikes!

If you refuse to provide a test case or any information, and nobody else experiences the same issues or has any way of investigating it - then yes - issues get closed. That's how open source works. If you want to investigate it _yourself_ and submit a PR, please feel free!
