### ISSUE TITLE
"You are currently using an old version": Am I, though?

### ISSUE THREAD

**Issue by xobs** [TryGhost/Ghost#11937]
### Issue Summary

Ghost keeps telling me to upgrade, but I'm pretty sure I'm on the latest version.

### To Reproduce

1. Log onto Ghost
2. See the banner saying version 2.20.2 needs to be upgraded
3. Upgrade to the latest 2.x branch (2.38.2)
4. Upgrade to the latest (3.20.2)
5. Log on to see the banner

![image](https://user-images.githubusercontent.com/238325/85189937-eeb02e80-b2e5-11ea-8c81-b3b12047b95f.png)

### Technical details:

* Ghost Version: 3.20.2
* Node Version: Docker image `ghost:3.20.2`
* Browser/OS: Firefox 77.0.1 Windows 10 19.04
* Database: `mariadb:10`

**Comment by sunlanterns** [comment]
There was a `3.20.3` version released 3 days ago. Maybe that's why you're still getting the banner? The banner does seem to imply you're still on v2 though with the wording.

**Comment by xobs** [comment]
The latest version on docker is [3.20.2](https://hub.docker.com/_/ghost?tab=tags) which was released three days ago.

**Comment by xobs** [comment]
![image](https://user-images.githubusercontent.com/238325/86504859-45426000-bdf0-11ea-9c4e-2fa82aab8f0d.png)

**Comment by xobs** [comment]
![Screenshot_20200706_101332_org mozilla firefox](https://user-images.githubusercontent.com/238325/86549152-68e0e400-bf71-11ea-8050-06b0e70fb384.jpg)

This is also happening on the mobile interface.

**Comment by ErisDS** [comment]
@xobs Whilst I am not dismissing that you are seeing this, it seems to be isolated to your setup. I've not seen another report of anything like this happening in several years. 

Therefore I believe it's a configuration issue best discussed on the forum, not a bug.
