### ISSUE TITLE
Update favicon output

### ISSUE THREAD

**Issue by JohnONolan** [TryGhost/Ghost#11932]
Currently Ghost outputs favicons in the document `<head>` like this

```html
// If a publication icon is set
<link rel="shortcut icon" href="/favicon.png" type="image/png" />

// If a publication icon is NOT set
<link rel="shortcut icon" href="/favicon.ico" type="image/x-icon" />
```

This is a slightly dated implementation based on [how browsers have evolved](https://bitsofco.de/all-about-favicons-and-touch-icons/), and could do with a small update.

We'd like to update this syntax to work as follows:

```html
// If a publication icon is set
<link rel="icon" href="/favicon.png" type="image/png" />

// If a publication icon is NOT set
// No output in <head>
```

- [ ] rel shortened to just `icon`
- [ ] no output in `<head>` if no publication icon is set

**Comment by RenCloud** [comment]
Hey, i would like to help with that issue. 
I saw that it will need changes to the `ghost_head.js` and the related test file.
There are 2 .hbs files with the line ([error.hbs](https://github.com/TryGhost/Ghost/blob/93433bac379b990eb3ad5b4e493498c36f8f3bcb/core/server/views/error.hbs#L15), [private.hbs](https://github.com/TryGhost/Ghost/blob/93433bac379b990eb3ad5b4e493498c36f8f3bcb/core/frontend/apps/private-blogging/lib/views/private.hbs#L15))
`<link rel="shortcut icon" href="{{asset "favicon.ico"}}">`
shoud  these also be adapted?

**Comment by JohnONolan** [comment]
I think the favicon references in those two files can be completely removed, yes :)

**Comment by ErisDS** [comment]
@JohnONolan I was thinking about this when looking at merging the PR, and realised there is a missing case for subdirectory sites.

For any site with a subdirectory this change means there's no longer a default Ghost favicon - and Ghost will only render the uploaded custom favicon if it is a png, not if it's an .ico.

I think the actual logic we want is to only output the favicon link tag in head if the favicon path is not exactly `/favicon.ico`, which is what the browser looks for by default.

I also got a bit confused trying to test this, as our icon uploader requires a file that's between 60px and 100px and square - which I think is something to do with, but our default favicon.ico is only 48x48px, which is also the biggest size I can get out of https://favicon.io/favicon-converter/ 😬

**Comment by ErisDS** [comment]
Ok after discussing this quickly, my logic is incorrect as well - we don't care about outputting a default favicon for subdirectory sites, it's fine and actually correct to fallback to using the favicon.ico from the root site. 

But the logic should be don’t output anything if no custom pub icon is set, which is also not what is implemented on the PR.

**Comment by JohnONolan** [comment]
Thank you @RenCloud ! :)
