### ISSUE TITLE
Bad paths for assets

### ISSUE THREAD

**Issue by michaldev** [TryGhost/Ghost#11933]
Hi. I would like to run ghost cms by docker and nginx. My path should look like example.pl/blog. I've two problems.

1. You set bad relative paths.
This is not possible, because you add paths for assets like this:
`<link rel="stylesheet" type="text/css" href="/assets/built/screen.css?v=6006647930" />`
and it search assets in example.pl/assets instead of in example.pl/blog/assets. This should look like:
`<link rel="stylesheet" type="text/css" href="assets/built/screen.css?v=6006647930" />`

2. URL in docker-compose doesn't work with subdirectory. If I entry 127.0.0.1:8000 in url work good, but in some places bad paths remain (example: <link rel="canonical"href="http://127.0.0.1:8080/" />). If I entry https://example.pl/blog nginx not found reverse proxy.

**Comment by michaldev** [comment]
```
This is not possible, because you add paths for assets like this:
<link rel="stylesheet" type="text/css" href="/assets/built/screen.css?v=6006647930" />
and it search assets in example.pl/assets instead of in example.pl/blog/assets. This should look like:
<link rel="stylesheet" type="text/css" href="assets/built/screen.css?v=6006647930" />
```

This is bug.

**Comment by ErisDS** [comment]
Nope. You've misconfigured your site.
