### ISSUE TITLE
CI NotFoundError: Resource cold not be found

### ISSUE THREAD

**Issue by thisconnect** [TryGhost/Ghost#11941]
### Issue Summary

Error in CI latest master and last tag `3.20.3`  in  Run grunt test-acceptance --verbose
"NotFoundError: Resource cold not be found"

### To Reproduce

1. current master
2. CI Error
    - https://github.com/TryGhost/Ghost/runs/788733876#step:9:611
    - https://github.com/TryGhost/Ghost/runs/788734028#step:9:450
    - https://github.com/TryGhost/Ghost/runs/788733920#step:9:449

The error occurs in CI after  Members disabled > Routes > should not serve members subscription endpoint 

### Technical details:

* Ghost Version: 3.20.3 & master 
* Node Version: Test Suite / 10.13.0 & 12.10.0
* Browser/OS: -
* Database: mysql & sqlite3

**Comment by ErisDS** [comment]
This is not an error, just some extraneous test output. There is plenty. By all means clean things up if you wanna but we don't need an issue open to track things like this.
