### ISSUE TITLE
Meta tags not updated until theme changed

### ISSUE THREAD

**Issue by nickpunt** [TryGhost/Ghost#11955]
### Issue Summary

After publishing a post without Facebook or Twitter card images, adding a new Facebook or Twitter card image will not show up in [Twitter Card Validator](https://cards-dev.twitter.com/validator) or [Facebook Share Debugger](https://developers.facebook.com/tools/debug/) until the blog theme is changed.

### To Reproduce

1. Post something with a regular post image (I did this with a png), but without custom Twitter or Facebook images
2. Update post with custom Twitter or Facebook images (jpg)
3. Refresh post and/or purge caches (any number of times), look at the post's meta tags, which still show meta tags with a link to the regular post image
4. Switch blog theme in Design (e.g. from custom theme -> Casper)
5. Look at the post's meta tags, which show meta tags with new post images
6. Switch blog theme back to original theme

Expected result:

* upon adding custom post images, meta tags in post are updated.

### Technical details:

* Cloudflare caches were purged, post URL was refreshed many times
* Custom theme was used, however the new/correct meta tags showed up after switching back to it so its not theme related
* Ghost Version: 3.20.0
* Node Version: whatever is on ghost.org hosting
* Browser/OS: whatever is on ghost.org hosting
* Database: whatever is on ghost.org hosting

### Optional additional feature

Facebook Share Debugger threw errors on jpg image used, which was solved by making smaller image. Feature suggestion: throw error if Facebook card image uploaded via Ghost is too large / not right format for Facebook.

**Comment by ErisDS** [comment]
Hi there! If you're having any issue with a **Ghost(Pro)** site, please drop us an email on support@ghost.org and we'll be more than happy to give you a hand directly :slight_smile: This is not a bug 🐛
