### ISSUE TITLE
Can't install ghost on a cPanel server.

### ISSUE THREAD

**Issue by genx1** [TryGhost/Ghost#11960]
You cant literally install ghost on a server which don't have Ubuntu as a server.
I uses cPanel I tried every method to install ghost on my Redhat cpanel server. I tried doing cPanel's deploy node.js app and also tried installing it via ssh but no it just don't work.

**Comment by matthanley** [comment]
Hey 👋 We ask that you please do not use GitHub for help or support 😄. We use GitHub solely for bug-tracking and on-going feature development.

Many questions can be answered by reviewing our documentation. If you can't find an answer then our [forum](https://forum.ghost.org/) is a great place to get community support, plus it helps create a central location for searching problems/solutions.

Thanks!
