### ISSUE TITLE
Better newsletter email error handling

### ISSUE THREAD

**Issue by rishabhgrg** [TryGhost/Ghost#11971]
### Issue Summary

Currently, any email failures while sending newsletter while publishing a post or in preview newsletter mode shows a catch-all "Please check your mailgun config error" in Ghost-Admin, which is not helpful or confusing in most cases. 

We use [Mailgun API](https://ghost.org/faq/mailgun-newsletters/) for sending email newsletters as well as its preview, but in most cases email errors happen due to invalid "From" addresses or any other reason unrelated to provider being used. 

We should ideally deliver an accurate error message to deal with whats the actual error, like "Invalid recipient address" being used instead of catch-all Mailgun error. 

Note: We are already passing down the error from Mail provider from our server to Admin in most cases. While Mailgun gives standard [error codes](https://documentation.mailgun.com/en/latest/api-intro.html#errors) for most failures, the error text message is mostly targeted for developers which will need tweaking before being shown in Admin and needs more thought.

**Comment by rishabhgrg** [comment]
Update: The structure for reading Mailgun's status code and error messages, and passing these down to Admin to show in UI is in place for preview email failures. PRs are here in [Ghost](https://github.com/TryGhost/Ghost/pull/12041) and [Admin](https://github.com/TryGhost/Ghost-Admin/pull/1635). 

Mailgun returns standard error [status codes](https://documentation.mailgun.com/en/latest/api-intro.html#errors) for email failures and an error message which is developer oriented. As the developer oriented error messages are not helpful in context of showing in Ghost-Admin, we need to create our own custom error messages for these status codes as well as specific failures.

The changes here need final review on wording of our custom error messages based on Mailgun status codes/message, including for commonly occurring errors like `Invalid recipient address` or `DMARC failures`. (cc @matthanley)

<img width="1073" alt="mailgun-error-codes" src="https://user-images.githubusercontent.com/3461456/87183009-e48cb900-c302-11ea-84fd-1dbd121e3bf5.png">

Placeholders for these custom error messages is currently [here] as well as below (https://github.com/TryGhost/Ghost/pull/12041/files#diff-09f445914155bf1fa0e091bcac64279bR28-R43).

For Error/Status Code
401 - 'Invalid Mailgun credentials'
400 + 'to' parameter is not a valid address - Recipient is not a valid address
400(Generic) - 'Failed to send mail, please check your request'
402 - 'Request failed, please try again in a bit'
Catch All - 'Email could not be sent, verify mail settings'

For Error message
Includes DMARC - 'DMARC is not supported'

**Comment by matthanley** [comment]
IMO we can't give the user enough actionable information to be useful for 400/402 so these should use the generic fallback.

5xx - `Mailgun reported a server error - please try again`
401 - `Email failed to send - please verify your <a href="https://app.mailgun.com/app/account/security/api_keys">Mailgun credentials</a> and try again`
Invalid recipient - `Recipient is not a valid address`
Fallback - `Email failed to send - please verify your email settings`

DMARC - @rishabhgrg could you provide the actual error returned by Mailgun for this one? It's not clear to me when we might encounter this and what info we can give the user to help them solve it.

**Comment by rishabhgrg** [comment]
Changes landed in master, closing.

**Comment by RubyAquaMarine** [comment]
Email service is currently unavailable - please try again! 

What would cause this error when using mailgun bulk email when publish & send emails
