### ISSUE TITLE
The 'sizes' attribute affects the width of the <img>

### ISSUE THREAD

**Issue by fueko** [TryGhost/Ghost#11978]
### Issue Summary

If the post content is wider than 720px, the image with the css attribute "max-width: 100%" will not reach 100%, but only a maximum of 720px.

### To Reproduce

1. Increase post content `.post-full-content` in Casper theme to e.g. 800px.
2. Add image.

Result: the maximum image width is 720px (image dimensions: 1000x667px).

![Zrzut ekranu 2020-06-30 o 22 06 15](https://user-images.githubusercontent.com/23366922/86173047-a1bb2c00-bb1f-11ea-8e99-d288314822b4.png)

![Zrzut ekranu 2020-06-30 o 22 06 35](https://user-images.githubusercontent.com/23366922/86173237-f65ea700-bb1f-11ea-98f9-fd413a3ee777.png)
![Zrzut ekranu 2020-06-30 o 22 06 53](https://user-images.githubusercontent.com/23366922/86173063-ab449400-bb1f-11ea-81b9-2b3b88adf34d.png)

I expect the image to always reach 100% of the width of the post content (if its dimensions allows it).

### Technical details:

* Ghost Version: 3.21.1
* Node Version: 12.18.1
* Browser/OS: All / macOS 10.15.5
* Database: sqlite3

**Comment by JohnONolan** [comment]
Heyo - responsive images are designed around best practice patterns, including optimal line length for readability. More info here: https://baymard.com/blog/line-length-readability - so it's expected that the average post content base column width to be around 720px.

For clarity: The sizes attribute does _not_ dictate the size of the image, it only tells the browser what the expected size will be. You can override with CSS if you want the image to stretch to be wider than its intrinsic dimensions - or you can disable responsive images in content completely by adjusting your config with:

```
"imageOptimization": {
   "srcsets": false
},
```

**Comment by fueko** [comment]
Hey @JohnONolan, I understand the idea of number of characters and it is right.

But, the post content layout can be a little larger, e.g. 760px and still having the right number of characters per line (different font type, size, etc). In this case, the 720px image looks bad.

> For clarity: The sizes attribute does not dictate the rendered size of the image, it only tells the browser what the expected dimensions will be.

Yes that's true, that's why I reported a bug. An image with 1000px width is displayed with a maximum of 720px width. 

The `sizes="(min-width: 720px) 720px"` attribute should not affect the layout, it should only inform the browser what image to download. 

> You can override with CSS if you want the image to stretch

If I use `width: 100%` (which solves the problem) then the user will not be able to insert small images to post content - they will be scaled to 100%.

I understand, if this is your end decision, but I would ask you to think about it again :)

**Comment by JohnONolan** [comment]
Images which need to be wider can always be set to "wide" in the editor, and small images do not have any `sizes` output - so these defaults make the most sense of the most number of usecases. There's no simple way to cover all of them (we spent a long time testing all of them)

I'm pretty sure you can work around this in several ways, either with `object-fit` on the image, different positioning logic, or JS.

It's expected that doing something different to the default needs a little more work, in this case

**Comment by fueko** [comment]
Now everything is clear, thank you for your explanation :)
