### ISSUE TITLE
Add setting for AMP Google Analytics tracking

### ISSUE THREAD

**Issue by JohnONolan** [TryGhost/Ghost#11980]
AMP does not include any scripts, or any code injection, so it does not get reported in Google Analytics. Making it work is relatively simple : https://www.pixelite.co.nz/article/adding-google-analytics-to-amp-posts-in-ghost/ - but it would be nice if this wasn't required.

Could we allow AMP to have a single setting, a text field, for 

---

**Google Analytics Tracking ID**
Tracks AMP traffic in Google Analytics, find your ID [here](https://ghost.org/faq/how-to-find-your-google-analytics-tracking-id/)

`<input type="text" placeholder="UA-XXXXXXX-X" />`

---

If set, then it should output:

Inside `<head>` right [here](https://github.com/TryGhost/Ghost/blob/master/core/frontend/apps/amp/lib/views/amp.hbs#L23) (or inside `{{amp_components}}`?)
```handlebars
<script async custom-element="amp-analytics" src="https://cdn.ampproject.org/v0/amp-analytics-0.1.js"></script>
```

Right before `</body>`
```handlebars
<amp-analytics type="gtag" data-credentials="include">
    <script type="application/json">
        {
            "vars" : {
                "gtag_id": "UA-XXXXXXX-X",
                "config" : {
                    "UA-XXXXXXX-X": { "groups": "default" }
                }
            }
        }
    </script>
</amp-analytics>
```

Working URL example:
https://ghost.org/blog/how-to-create-a-newsletter/amp/

Validator:
https://search.google.com/test/amp

I don't think we need to do detailed validation / try to prevent broken inputs. If people do something wrong, Google will send them 1 million emails about it anyway.

**Appetite:** 1 day

**Comment by matthanley** [comment]
This will require a new setting `amp_gtag_id` added in group `amp`, configured via the existing AMP integration configuration page in Admin (at `#/settings/integrations/amp`). Text input should follow the UI conventions used in the equivalent Slack integration config screen (exact copy TBD).

**Comment by allouis** [comment]
@matthanley Is there any update on the exact copy wanted to the screen?

**Comment by allouis** [comment]
https://github.com/TryGhost/Ghost-Admin/pull/1638 I've added the initial UI work here

**Comment by JohnONolan** [comment]
Exact copy is in first comment of this issue - between the two `<hr>` lines - should be safe to use that

This can go straight out and be reviewed alongside release or whatever, should be small enough to not need any formal review or anything

**Comment by allouis** [comment]
This is now in master!

https://github.com/TryGhost/Ghost/pull/12039 - Migrations, database & template updates
https://github.com/TryGhost/Ghost-Admin/pull/1638 - UI updates
