### ISSUE TITLE
The currency symbol is not rendered

### ISSUE THREAD

**Issue by fueko** [TryGhost/Ghost#11984]
### Issue Summary

Helper {{@price.currency_symbol}} is not rendered

### To Reproduce

1. Use Ghost 3.22.0 with Lyra theme.
2. Enable members function.
2. Subscribe and go to the account page.

Result:

![Zrzut ekranu 2020-07-1 o 12 21 53](https://user-images.githubusercontent.com/23366922/86237326-dc62aa00-bb9b-11ea-9f08-283bb2166087.png)

### Technical details:

* Ghost Version: 3.22.0
* Node Version: 12.18.1
* Browser/OS: All / macOS 10.15.5
* Database: sqlite3

**Comment by allouis** [comment]
Thanks!
