### ISSUE TITLE
 Unknown version of mobiledoc parser requested: 0.3.2

### ISSUE THREAD

**Issue by ichitaka** [TryGhost/Ghost#11985]
### Issue Summary

So the title of this issue is what I am getting in the console in my admin page of **some** of my articles. Also for those articles, the editor does not load the article but only half of the title.

https://i.ibb.co/FWpvKBq/Screenshot-2020-07-01-Bio-Siegel-im-Vergleich-gustar-io.png

 It is not really clear to me what causes this.

### To Reproduce

Sadly I do not know that.

### Technical details:

* Ghost Version: 3.7
* Node Version: v12.16.1
* Browser/OS: Tested Chrome, Firefox,  Safari on macOS  and Windows
* Database: MariaDB

**Comment by ErisDS** [comment]
Please upgrade to latest Ghost.
