### ISSUE TITLE
Return API results in exact order when filter contains slug-is-in rule 

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#11994]
## Problem:

If I want to fetch a subset of my data to iterate over in a template, I can do this really easily with the API, but I can't properly control the order because the API enforces a default order:

E.g. fetch a set of pages that should be listed in a specific order:

```
{{#get "pages" filter="slug[about, team, contact]"}}
   {{#foreach pages}}
      // Will list in title order: About, Contact, Team
  {{/foreach}}
{{/get}}
```

e.g. fetch all my tags that are tied to collections to list out on a custom collection list page:

```
{{#get "tags" filter="slug[blog, podcast, design]"}}
    {{#foreach tags}}
     // Will be in order blog, design, podcast
   {{/foreach}}
{{/get}}
```

If you created your resources in the right order, you might get some traction by adding `order="id"` but that's really lucky.

**Appetite**: 1 day

## Solution:

API v3 requests for a list from any public resource (post, page, tag, author) that contains a slug-is-in filter like this should automatically change the default order to match the order the slugs are provided in.

**Implementation Notes**

We already have some similar automatic order changing when filtering posts by tag-is-in or author-is-in: https://github.com/TryGhost/Ghost/blob/master/core/server/models/post.js#L768-L775

However this custom ordering logic is super API-specific and IMO should live somewhere in the API (probably in the input serialisers?). 

I did a very [quick test implementation](https://github.com/ErisDS/Ghost/commit/af93880d0da76a73f043bed5ad29bd06fcf6ed52), not fully tested and no strong opinions, but might be useful to see how easy it is to build the right order query using a CASE statement.

Bonus points if the implementation includes moving the existing custom ordering logic for posts out of the model layer up into the same part of the API. 

Note: ATM we seem to only set these orders for the Content API, and I'm not 100% sure why, but we should probably follow that pattern for now. This reinforces the need to implement at the API level, as we will probably want to change this in the Admin API at some point.

Note: this should only apply to the v3 and canary APIs.

**Comment by naz** [comment]
Had a small peak into the sample implementation. The reasoning for putting the ordering in serializer layer makes sense to me :+1:  

The thing I'm a bit uneazy about is having API know even more about raw SQL and essentially table structure. The model layer is the only place which should be building this kind of queries. That said, don't have any better idea where to extract ordering logic to freeing up model from API-specific behavior :shrug: (read this as me thinking out loud  and coming to the same conclusion as you did :laughing: )

**Comment by ErisDS** [comment]
> The thing I'm a bit uneazy about is having API know even more about raw SQL and essentially table structure. The model layer is the only place which should be building this kind of queries. 

This is totally fair to feel uncomfortable about. 

Providing that nothing new gets exposed via the API, I think it'd be perfectly reasonable to introduce a named concept at the API-implementation level, and have the model interpret and understand the name to build the relevant query. This would separate the concept of the order from its query implementation.

E.g. instead of setting orderRaw at the API level, set `autoOrder = slugOrderInFilter` and similarly for posts where we order by tags or authors `autoOrder = matchingTagCount`. Whatever we do here, as long as `orderRaw` or `autoOrder` can't be explicitly set by users, I think this works.

Note: users should be able to set a standard order, e.g. `?order=slug%2Fasc` and override the automagic ordering logic.

Note: we don't want to expose these options to the outside world for several reasons: 1. at present there's no use case for these orders outside of them being automatic. If there was a use case then 2. we'd want to properly design a naming convention of some sort for API orders and 3. we'd need to do lots of additional testing to ensure it wasn't possible to trigger SQL injection attacks. Think `?order=slug:a,b,c' and a whole new NQL style system. There's no appetite!
