### ISSUE TITLE
Checksum for routes.yaml file

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#11999]
## Problem

We don't currently have a mechanism to determine if a site is using the default routes.yaml, or if the file has changed between restarts.

**Appetite:** 1 day

## Solution

On boot, create a checksum that represents the content of the routes.yaml file. If it's different to the existing checksum we have, then update the checksum. The checksum should be stored in the settings table similar to db hash.

The default checksum should be stored as a constant in Ghost, so that we can easily say "this is the default". 

This is a precursor to being able to optimise loading routes in future, there's nothing else to do for now.

We should use the default checksum to create an integrity unit test in test/unit/data/schema/integrity_spec.js

**Comment by naz** [comment]
Have been working on these changes and have couple notes on decisions I've made along the way:
1. Naming for the new setting key will be `routes_hash` and goes into `core` group. Both naming and group inspired by [db_hash](https://github.com/TryGhost/Ghost/blob/7884481ce527c7ba4d3aa807df9edb553c8fcec4/core/server/data/schema/default-settings.json#L3-L6) setting as it's very similar in it's purpose.
2. IMO storage of "default routes checksum" constant along with "current routes checksum" belong to [frontend's settings module](https://github.com/TryGhost/Ghost/blob/master/core/frontend/services/settings/index.js) and will be exposed through: `getDefaultRoutesHash` and `getCurrentRoutesHash` functions. Reasoning: the default constant naturally belongs there as this settings module manages settings extracted from loaded `routes.yaml` file; the current hash also finds it's place here naturally and can be easily set during module's "init" phase
3. The `getCurrentRoutesHash` from above point is needed to give Ghost's boot process data necessary to decide on updating `routes_hash` value in the db. This is done through model layer, which is intentionally not used directly in frontend's services to keep them decoupled.

@matthanley pts. 2 and 3 are an fyi notes. Let me know if you have different opinion on **pt.1** -  naming of the new settings key for routes hash.

**Comment by matthanley** [comment]
`routes_hash` lgtm 👍

**Comment by naz** [comment]
Changes from https://github.com/TryGhost/Ghost/compare/master...naz:routes-checksum will need to be merged to close this issue once [migrations PR](https://github.com/TryGhost/Ghost/pull/12171) lands in master.

**Comment by naz** [comment]
@matthanley something that wanted to note around this point in the spec:
> **On boot**, create a checksum that represents the content of the routes.yaml file. If it's different to the existing checksum we have, then update the checksum. The checksum should be stored in the settings table similar to db hash.

The implementation I've done now does literally what the spec says - check is done **only** during boot. What I think might be missing from the spec is same check and save in the db when a new [routes.yaml is uploaded](https://github.com/TryGhost/Ghost/blob/5d47398d932c7c54ffdb197088636a94dca7f3a7/core/server/api/canary/settings.js#L295) and [soft reload](https://github.com/TryGhost/Ghost/blob/5d47398d932c7c54ffdb197088636a94dca7f3a7/core/server/web/site/app.js#L200-L213) of the site is done. If we add the check during soft reload it would allow us to be always up to date with the checksum of currently active routes.yaml config, not just between restarts. 

Let me know if adding a check during soft reload would make sense, or are the usecases limited to the boot and current implementation is fine.

**Comment by ErisDS** [comment]
Just jumping in to confirm the expectation is when file changes === hash changes.

**Comment by naz** [comment]
Thanks Hannah! :woman_dancing:
