### ISSUE TITLE
Implement additional settings validation

### ISSUE THREAD

**Issue by allouis** [TryGhost/Ghost#12001]
Implement additional validation on settings to ensure we don't encounter any unexpected errors from malformed settings.

List of settings to validate:

- stripe_publishable_key
- stripe_secret_key
- stripe_connect_publishable_key
- stripe_connect_secret_key
- stripe_plans
  - Need to validate `amount`, `currency`, `interval` & `name`

Ensure Stripe keys `matches` e.g. `/^[ps]k_(?>live|test)_[a-zA-Z0-9]{26}/` (confirm exact format - [length may vary](https://support.stripe.com/questions/new-api-keys-are-longer-than-existing-keys)). We can also hit the Stripe API to validate secret keys.

Appetite: **1 day**

Stretch goals:
- Look at a sensible generalised way to validate the objects nested in settings of `type=array` (*navigation, stripe_plans, portal_plans, views)

Optional stretch stretch-goals:
- accent_color matches e.g. `#[0-9a-fA-F]{6}`
- mailgun_* validations
- amp_gtag_id matches Google Analytics format

**Comment by allouis** [comment]
Hey @matthanley what's the appetite for this?

**Comment by matthanley** [comment]
@allouis appetite for the main validation issue is 1 day - I don't expect the stretch goal(s) to be anywhere near completed within that, but hopefully we can get a good idea of how we _could_ implement generic validation for settings nested in arrays, with a separate tech debt issue written up.

**Comment by allouis** [comment]
@matthanley I wrote up a tech debt issue here: https://github.com/TryGhost/Ghost/issues/12051
