### ISSUE TITLE
Canonical URLs refer to themselves

### ISSUE THREAD

**Issue by adamhenson** [TryGhost/Ghost#12007]
### Issue Summary

A canonical URL should be set when a page duplicates another.

> Add a <link> tag in the code for all duplicate pages, pointing to the canonical page.

https://support.google.com/webmasters/answer/139066?hl=en

It seems that Ghost adds a canonical URL to all pages / posts by default and there is no way of opting out. Canonicals point to themselves. The issue is that this behavior excludes URLs from being indexed. Screenshot of Google Search Console below.

![ghost](https://user-images.githubusercontent.com/747743/86556042-2511be80-bf20-11ea-8520-c022ac3d0b44.png)

### To Reproduce

1. Navigate to any Ghost page and view the source. In my case https://www.foo.software/
2. Note the tag in my case looks like this `<link rel="canonical" href="http://www.foo.software/" />`

## Expected:

Canonical should only be added when specified by the admin. It should not be added by default unless it does in fact duplicate content of another page (example: an amp format page is a good use case).

### Technical details:

* Ghost Version: `3.22`
* Node Version: `10`

**Comment by ErisDS** [comment]
Looks like an incorrectly configured site to me.

**Comment by adamhenson** [comment]
Ya, I actually didn’t notice the http vs https mismatch until after I opened this. This is definitely a config problem. When using the Docker container and attempting to proxy with a separate NGINX container (in a Kubernetes cluster) - I’ve found major issues in attempting to configure. It doesn’t seem possible. This is a separate can of worms.

@ErisDS the point of this issue was to call out that a canonical URL shouldn’t reference itself. But, since it seems I have bigger problems I’m fine with you closing this. I do think you missed my point however.

**Comment by ErisDS** [comment]
Nope, I didn't miss it. It's opinion, not a bug, so I ignored it.

Your config issue is genuine but belongs on the forum, I've always got an eye on there.

**Comment by adamhenson** [comment]
Thanks @ErisDS. Fair enough. Appreciate your time.
