### ISSUE TITLE
Soundcloud OEmbeds too large

### ISSUE THREAD

**Issue by kymellis** [TryGhost/Ghost#12018]
### Issue Summary

SoundCloud embeds (using OEmbed) appear too large on the front-end, and expand off the edge of the screen. 

### To Reproduce

1. Paste the URL of any Soundcloud track into the Ghost editor.
2. Preview the post

Example: 
<img width="1133" alt="screenshot_2020-07-07_at_13 11 47" src="https://user-images.githubusercontent.com/16795687/86760812-b5aae480-c06f-11ea-81dc-946b48498c75.png">

### Technical details:

* Ghost Version: 3.21.1 - Ghost(Pro)
* Browser/OS: Firefox

**Comment by iamscottcab** [comment]
@kevinansfield I thought I would take a dig into this today to see if it's an easy fix or not given I did my first PR to this project the other day, and it went well so I thought I'd keep at it while I had some spare time...

Just a quick note that this effects a lot of oembeds not just soundcloud (dailymotion has the same problem).

My understanding from mucking around with this the last hour or so is that the oembed is generated when you paste it into the Admin Panel in editor (at least I can get a `console.log` to fire at that point). Is that correct?

If I look in `server/api/canary/oembed` I can see a commit 4 months ago that added `maxwidth` when fetching oembed data for larger images. I can change this to `maxwidth: 100%` but then I get other issues like daily motion coming out too small (and soundcloud coming out enormous in the Admin panel). Do those embed widgets get constructed in the client when requested or are they server rendered?

Any css based fix for this seemed sketchy, it was easy to fix the width but you don't always know the height (setting auto or 100% didn't seem to work well for me unless I am missing something). Any chance you can point me in a direction to follow this one through? My gut says we want to request a large oembed size. But force the resulting inline css on the iframes to `width: 100%; height: whatever-oembed-returned`?

**Comment by sainthkh** [comment]
I've submitted 2 PRs for this issue. But there are still more problems. 

- [ ] Facebook and Instagram issue. The old oembed endpoint has been deprecated since October 24 2020. We need to update oembed-parser to 1.4.3. And check if it works correctly. 
- [ ] We need to fix the embedded elements created before these PRs are merged. width=1280 is hard coded into mobiledoc and html in the database. And we need to change them.
