### ISSUE TITLE
Regression: start date on members chart X axis disappeared

### ISSUE THREAD

**Issue by peterzimon** [TryGhost/Ghost#12014]
### Issue
The left end of the X axis of the members chart should display the start date of the selected date range (as the right end of the axis is fixed "Today", e.g. for "30 days" range it should be `(today - 30 days)`). ATM there's nothing there. 

Formatting of the start date should be: `D MMM YYYY` (similar to the one in the tooltip)

<img width="906" alt="Screenshot 2020-07-06 at 18 06 17" src="https://user-images.githubusercontent.com/353959/86614546-77e88600-bfb3-11ea-9852-f8bc836f7bcc.png">

**Comment by umuur** [comment]
Hello, can I take this issue?

**Comment by ErisDS** [comment]
Sure thing

**Comment by umuur** [comment]
I'm having troubles about which file generates the members view? Could you please inform me about it?

![image](https://user-images.githubusercontent.com/8915912/87852063-92055b00-c907-11ea-8d1a-794610c7248b.png)

**Comment by umuur** [comment]
I think I've found the necessary files to fix this issue. 

It looks the startDateLabel variable set to empty string. 

https://github.com/TryGhost/Ghost-Admin/blob/213b44bf9ca7ca4d930b4d14d78ea1fdd2c0d9a1/app/components/gh-members-chart.js#L21

**Comment by umuur** [comment]
I've submit a PR [#1644](https://github.com/TryGhost/Ghost-Admin/pull/1644) for this issue.
