### ISSUE TITLE
Tags which are starting with a 0 (zero) in the slug can't be filtered

### ISSUE THREAD

**Issue by sfaujour** [TryGhost/Ghost#12010]
### Issue Summary

When creating a new tag e.g. with name "030", the auto generated slug is also "030" (zero, three, zero).
In the tags overview, it shows up all pages/posts which have this tag, but if you click on the no. of posts with this tag, the list is empty.
The same happens, when trying to filter with the #get helper inside a template.

### To Reproduce

1. Login to ghost admin
2. Click Tags
3. Create a new tag called "030" (also slug should be 030)
4. Create a post, and tag it with "030"
5. Go back to Tag list, and click on the "# post(s)" in the row of tag "030"
6. Page shows no posts / pages 

## What did you expect to happen instead?
Page should show all posts with this tag and filtering with get helper should recognize this posts/pages too.

### Technical details:

* Ghost Version: 3.22.0
* Node Version: 12.10.0
* Browser/OS: Chrome (83.0.4103.116)
* Database: sqlite (default after local setup)

**Comment by iamscottcab** [comment]
I've clearly got too much spare time today... 🤦‍♂️

Anyway I've tracked this down to the use of the package [NQL](https://github.com/NexesJS/NQL). Basically it's (probably correctly) parsing out the tag it to a number which drops the leading 0. When it's doing a DB search it doesn't pull back the correct record. You can easily confirm this by making a tag `30` and the result using the tag `030` will show up there instead to mimic that behaviour.

Also fwiw a super easy repro to show that `nql` is doing this would be the following:

```
const nql = require('@nexes/nql');
const res = nql('tag:030').toJSON();
console.log(res);

// { tag: 30 }
```

I guess there are two options here, somehow stringify the all tags before parsing them through NQL or change the behavior of NQL? Not knowing enough of the semantics of this app (yet) I'm guessing I'd have to defer how best to fix / not fix this to one of the maintainers. Hope this helps the dev team though...

**Comment by sfaujour** [comment]
@iamscottcab Thank you for breaking this down. I've not had the time to do so. 👍
