### ISSUE TITLE
Changes to post_meta fields are not detected as model changes 

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#12016]
Making changes to any of the `post_meta` fields doesn't set `post.wasChanged` to true and subsequently doesn't trigger cache invalidation 

1. Create a post in the editor, making sure you add some content else you'll hit https://github.com/TryGhost/Ghost/issues/12015
2. Make sure the post is fully saved
3. Open the post settings menu and edit a meta field e.g. twitter_title
4. Open the network tab, hit cmd+s and notice the response headers don't include x-cache-invalidate 
5. Edit a main post field 
4. Open the network tab, hit cmd+s and notice the response headers _does_ include x-cache-invalidate 

The correct behaviour is that `wasChanged` and x-cache-invalidate should be set when any real change is made.

### Technical details:

* Ghost Version: master

**Comment by naz** [comment]
I have tests confirming the bug and have dug into the model layer. What I'm thinking on doing is tracking any properties [done on edit](https://github.com/TryGhost/Ghost/blob/d6267340a13ed7c78c66c27c78ecd819bbd94576/core/server/models/post.js#L885-L888) like so:
```js
found.relations.posts_meta._previousAttributes = post.relations.posts_meta._previousAttributes;
found.relations.posts_meta._changed = post.relations.posts_meta._changed;
```

And then would need  some generic way to hook into these changes from model's `wasChanged()` method. Right now only current models `_changed` attributes are tracked, but think overloading this method or calling something like `this.relatedChanged()` from base model would be best.

**Comment by naz** [comment]
For reference to anybody digging through the issue, here is a discussion on why this kind of change tracking is not natively supported by bookshelf - https://github.com/bookshelf/bookshelf/issues/1943.

**Comment by naz** [comment]
Note on one of the side-effects that happened with this fix. Previously changes to `post_meta` didn't create records in `actions` table as those also used [wasChanged method](https://github.com/TryGhost/Ghost/blob/a75e1e27db356267ef5574c3026b9a719961f421/core/server/models/base/index.js#L112). Creating a record in the `actions` table is a correct behavior IMO.
