### ISSUE TITLE
Members: Allow for collecting name with theme forms

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#12029]
## Problem:

Members can have a name, but currently it's not possible to collect this using members forms in themes.

This was originally requested here: https://github.com/TryGhost/Lyra/issues/35#issue-562748711

**Appetite** 1 day

## Solution

Add the ability to collect names the same way that we can set labels.

**Comment by sainthkh** [comment]
This can be closed because it's fixed in #12191.

**Comment by rishabhgrg** [comment]
Yup, thanks for pushing this up @sainthkh :)
