### ISSUE TITLE
Updating to 3.22.0 via ghost-cli may corrupt site settings

### ISSUE THREAD

**Issue by allouis** [TryGhost/Ghost#12020]
### Issue Summary

When upgrading to 3.22.0 via ghost-cli the settings cache does not get reset following settings migrations on startup. This leads to the settings cache being in an inconsistent state with the database, and the settings API returning an empty settings array `[]` to the admin client.

If a user subsequently attempts to modify any settings via Ghost-Admin (such as enabling Members), the server settings get overridden with null/false values.

### Who's affected?

This bug only affects sites which:
* were installed prior to version 3.22.0
* were upgraded to 3.22.0 via ghost-cli
* were not restarted again prior to saving settings via Ghost-Admin, and
* the site administrator attempted to update the site settings via Ghost-Admin

### Restore Settings

If you have installed version 3.22.0 but _not_ attempted to update any settings, you **must** restart Ghost by issuing `ghost restart` immediately, and upgrade to the latest version as soon as possible.

If you have installed version 3.22.0 and have experienced corruption of your site's settings, you may be able to restore your settings:
1. Rollback to 3.21.1
2. Import the JSON backup file created by ghost-cli as part of the initial `ghost upgrade` to 3.22.0 (stored in `./content/data`)
3. Update to the latest version

---

### To Reproduce

1. `ghost install 3.21.1 --local`
2. Set up the site and set up members
3. `ghost update 3.22.0 --local`
4. Visit the labs settings and see members is disabled; attempt to enable it and observe the `isLang` validation error.
5. `ghost update 3.22.2 --local`
6. Visit the labs settings and see the Stripe Subscription price settings are not rendering. Ghost logs errors when trying to configure stripe.
7. `select * from settings;` 
8. See that the `stripe_plans` and other settings have an empty value, and that all bool values are now `false`.

#### Possible States

* Prior to the 3.22.0 update, the database is in a consistent state.
* Immediately following the update to 3.22.0, the database contains the correct settings values, but the settings API returns an empty settings array `settings: []`
* After attempting to update the site settings via Ghost-Admin, the settings in the database are overridden with empty (`null`/`false`) values

### Technical details:

* Ghost Version: 3.22.0
* Node Version: any
* Browser/OS: any
* Database: any

**Comment by allouis** [comment]
This will result in the `stripe_plans` setting being empty, the correct fix for this is to rollback to 3.21.1 and restore your settings from the backup created at migration (stored in `./content/data`). 

There is a [migration for 3.23 in PR](https://github.com/TryGhost/Ghost/pull/12019) which forces the `stripe_plan` setting to the default value if they are not configured correctly

**Comment by matthanley** [comment]
Closing as this has been fixed in 3.22.1 onwards, and directions for restoring broken settings are available in the issue description.
