### ISSUE TITLE
Show custom_excerpt in edit mode

### ISSUE THREAD

**Issue by thisconnect** [TryGhost/Ghost#12035]
### Issue Summary

The custom_excerpt is not visible in edit mode

### To Reproduce

1. Create a new post
2. Enter a Excerpt in the post settings

Excerpt should be visible in the ghost blog editor page, maybe in readonly (not editable)

### Technical details:

* Ghost Version: 3.17.1
* Node Version: v12.16.3
* Browser/OS: any
* Database: any

**Comment by ErisDS** [comment]
I appreciate the feedback but this is not a bug.

**Comment by thisconnect** [comment]
> I appreciate the feedback but this is not a bug.

So it shouldn't be there in edit mode?

Should I have opened it as feature request?
