### ISSUE TITLE
Contributor dashboard text causes confusion

### ISSUE THREAD

**Issue by QuincyLarson** [TryGhost/Ghost#12047]
With our community publication, we have opted to keep authors in the "contributor" role and have them submit stories through email to our editorial team. This is to ensure sufficient quality control on each article.

But one of the issues we're facing is caused by a single confusing line of text in the Ghost CMS.

<img width="1753" alt="Posts_-_freeCodeCamp_org" src="https://user-images.githubusercontent.com/985197/87464988-a11f9c80-c5d9-11ea-97f5-1913bda0d3b2.png">

As a contributor, if you sign into Ghost, and you don't have any active drafts, you will see the following message: "You haven't written any posts yet!"

But in many cases, the contributor has written posts and published them. So many of our authors have reported that they thought they had signed into the wrong account, or worse that their stories had been deleted.

At our current scale, with hundreds of contributors, this single line of text has caused quite a bit of confusion, and I've had to get on several calls to reassure authors there's nothing wrong.

So I propose that instead of saying "You haven't written any posts yet!" this could be reworded to say "You don't currently have any drafts." or something like that (and without the out-of-place exclamation mark).

**Comment by JohnONolan** [comment]
Huh. 🤔  this is a totally valid point - I'm not sure if the copy is the only problem here, either! We'll have a look in detail and follow up. Thanks for bringing this to our attention :)

**Comment by JohnONolan** [comment]
Actually, just for some extra context @QuincyLarson - would you be able to give us a summary of your current editorial process in as much detail as you're able to? Whatever format is most convenient, if you just want to share the same docs you would normally give a new contributor to explain to them what to do / and any info about what the editors are then expected to do.

We'll fix this specific issue either way — but would love to see if we could maybe also do more than that

**Comment by souravseal99** [comment]
Hi, if anyone isn't working with this issue, can I give it a try ?

**Comment by matthanley** [comment]
Ghost now has a restructured interface for contributors, which addresses all of the points raised in this issue. @QuincyLarson thanks for the feedback!
