### ISSUE TITLE
Incorrect spelling of parameter doesn't throw error when uploading routes.YAML

### ISSUE THREAD

**Issue by MarkErik** [TryGhost/Ghost#12054]
### Issue Summary

Incorrect spelling in Routes.YAML doesn't throw error during upload.
Was expecting some validation (similar to how it returns an error if the YAML formatting isn't correct).

### To Reproduce

If you follow the tutorial to make a static home page, you'll end up with the following code. Notice that I misspelled template.

```
  /:
    data: page.home
    templage: home
```

Upload the routes files via the admin panel. No errors visible to the user through the UI.

At first I didn't catch this because I was running the docker image as a daemon -d . 

I was wondering why my site wasn't working, and finally found that I didn't spell it correctly.

Afterwords I ran the docker image without the -d command and I could see the following error in the console:
Missing template  for route "/".
Error ID:
    2596fdb0-c82c-11ea-baf4-1d77ff89bbfc

It would be good to immediately find out that there is a problem with the routes file when you try to upload it.

### Technical details:

* Ghost Version: Latest docker image 3.25
* Browser/OS: Safari
* Database: sqlite

**Comment by ErisDS** [comment]
This isn't really a bug - although I totally understand it's annoying - it's a feature request. 

Implementing validation for various keys now would cause a breaking change. The value of implementing it would not exceed the cost from both a technical perspective or the difficulty of managing a breaking change, even in a beta feature.

What we do want to do is overhaul how dynamic routing works to give users a better overall experience, and that's something that's being thought about already.
