### ISSUE TITLE
Article structured data is invalid on pages

### ISSUE THREAD

**Issue by adamhenson** [TryGhost/Ghost#12059]
### Issue Summary

Based on the [test from Google Structured Data Testing Tool](https://search.google.com/structured-data/testing-tool/u/0/#url=https%3A%2F%2Fdemo.ghost.io%2Fabout%2F), it seems that the Article structured data is invalid on pages. It's missing `datePublished` which is identified as an "error" by the tool. Image shows correctly when you upload one. There is a "warning" about `dateModified` missing.

<img width="1291" alt="Screen Shot 2020-07-18 at 7 42 47 PM" src="https://user-images.githubusercontent.com/747743/87863904-f12a9600-c92e-11ea-86f5-04f10cc8b999.png">

<img width="1291" alt="Screen Shot 2020-07-18 at 7 43 00 PM" src="https://user-images.githubusercontent.com/747743/87863902-ee2fa580-c92e-11ea-8a9c-afeef9c705bb.png">

This issue only exists for page types. Posts work as expected.

### To Reproduce

1. Run a test on any Ghost page using [Google's Structured Data Tool](https://search.google.com/structured-data/testing-tool).

## Expected:

The test using the tool above should pass the way it does for posts.
- `datePublished` should be populated.
- `dateModified` should be populated.

### Technical details:

* Ghost Version: `3.22`
* Node Version: `10`

**Comment by adamhenson** [comment]
If someone could point me in the direction of where these types of templates are in the codebase, I could work on a PR. I'm not familiar with the codebase and in doing a search for the word "@type" in this repo, I didn't find anything. Is it in another repo?

**Comment by daniellockyer** [comment]
@adamhenson You'll probably want https://github.com/TryGhost/Ghost/blob/master/core/frontend/meta/schema.js :slightly_smiling_face:

**Comment by adamhenson** [comment]
Perfect, thanks @daniellockyer. Not sure why I wasn't finding it in GitHub search 🤷

**Comment by adamhenson** [comment]
If someone comes back to this issue and it's open, and it's no longer July, 2020 - that means I probably didn't get around to submitting a PR. I'm hoping to get to it though.

**Comment by roshandash411** [comment]
The context was 'page' but the data contained only 'post' because 'page' is an extension of 'post'. This was the reason null was being returned. I've added the fix. Could somebody please check and merge. Thank you. My first commit into the Ghost repository 😅

**Comment by daniellockyer** [comment]
@roshandash411 Thanks for the contribution!

@adamhenson The fix for this was just released in 3.29.2, so please update with Ghost-CLI :slightly_smiling_face:

**Comment by adamhenson** [comment]
Thanks so much for your work on this @roshandash411, @ErisDS, and @daniellockyer 🙌
