### ISSUE TITLE
Update stripe email when updating member email

### ISSUE THREAD

**Issue by JohnONolan** [TryGhost/Ghost#12055]
At the moment if an admin user updates a member email address in Ghost Admin, the Stripe customer is not updated. This is a problem, because now the Member receives newsletters (Ghost) and payment receipts (Stripe) to 2 different email addresses.

Whenever the member email address is updated in Ghost, it would be great if we also updated it in the Stripe customer object

**Comment by umuur** [comment]
can I take this since #12014 is done?

**Comment by ErisDS** [comment]
We should probably do this for name as well as email at the same time

@umuur FYI we have a curated list of issues that we specifically are looking for contributors to work on - all tagged `help wanted` - these are issues you can be sure noone from our core team is working on. Alternatively, please just submit PRs, we'll merge / or provide feedback.

**Comment by umuur** [comment]
Alright, thank you for informing me. I'll look for names as well.

**Comment by JohnONolan** [comment]
Hi @umuur - are you still looking at this? :)

**Comment by allouis** [comment]
Stripe Checkout does not collect names for customers - it only assigns a name to the card, which I think is something we do not want to update? As it could invalidate the card, or at least result in incorrect data assigned to the card?

As for updating the email, this is straight forward to do as an ongoing thing - e.g. future updates to the member's email in Ghost will update the email in Stripe - however, what do we want to do about existing members? A migration to update all of the Customers in Stripe would be very large and not something we'd generally do inside a migration.

We could:
1. Create a one-time script that would iterate through all paying members and sync their email
2. Do nothing?

cc @JohnONolan @matthanley What are your thoughts on the above?

**Comment by matthanley** [comment]
Agree we shouldn't be updating any card details, including the name.

imo when we update a member model, we should push those changes to Stripe (both customer name + email). Over time I'd expect existing customers to be populated in Stripe (names and email addresses) anyway, so I don't think we need any special handling for it.

**Comment by allouis** [comment]
:+1: Okay cool, existing members will be left untouched for now then :relaxed:

**Comment by allouis** [comment]
Syncing email changes in Ghost to Stripe was completed here: https://github.com/TryGhost/Members/pull/206

Waiting on renovate to bump the package in Ghost, which'll close this issue :)

**Comment by allouis** [comment]
This landed here https://github.com/TryGhost/Ghost/pull/12236
