### ISSUE TITLE
Auto-embedded links send incorrectly with email newsletter

### ISSUE THREAD

**Issue by 2JJ1** [TryGhost/Ghost#12063]
When publishing a test post, I used the built-in feature to send a newsletter for the post. When viewing the email, I noticed that the embedded link looks like [this](https://gyazo.com/4b905868b9c7ce1a2f5ca3c8db05ac11). Viewing the website post, the embedded link looks like [this](https://gyazo.com/5a6b94ea0c9a32ed91168c0832b671b3), which is expected. The issue occurs when embedding almost any other link. I expected the email version of the embed to look like it does on the website. I didn't expect it to be stretched out and have text overlap it.

To reproduce, create a new post. Paste in "https://github.com/2JJ1/Private-Discord-Bot/releases" and press enter so Ghost will automatically embed it. Send a test email using the Ghost members newsletter feature. I am using Ghost version 3.25.0.

**Comment by ErisDS** [comment]
Closing in favour of https://github.com/TryGhost/Ghost/issues/12078, which I think is the same and has the correct format.

@2JJ1 please use the bug template in future.
