### ISSUE TITLE
🐛 Intermittent error when (re)configuring Stripe

### ISSUE THREAD

**Issue by allouis** [TryGhost/Ghost#12065]
### Issue Summary

The Members service listens for changes to the Stripe settings, and reloads the module when they've changed, this ensures that updated plans are created, new api keys are used, basically so that the state of the settings matches the state of the running code.

Since https://github.com/TryGhost/Ghost/commit/ee786aaa5d552cc24eea03e60c7bafb2bf340b6e the settings were split out into individual string settings we now listen to the changes of 11 different settings: 

https://github.com/TryGhost/Ghost/blob/ee786aaa5d552cc24eea03e60c7bafb2bf340b6e/core/server/services/members/index.js#L26-L38

Many of these settings are changed in parallel, causing the members module to be reloaded up to 6 times in quick succession, this can cause a race condition during the setup of Stripe Plans which usually follows this logic:

1. Generate ID of plan
2. Fetch plan from the API
3. If it's missing, create it.

However if the race condition occurs, a missing plan may be created between step 2 & 3, resulting in an unexpected error and the halting of the Stripe setup.

If this occurs. the Admin will think that Stripe is correctly configured, however the API will be unable to complete any Stripe related functions until Ghost is restarted.

### To Reproduce

1. `ghost install --local 3.25.0`
2. `ghost log -f`
3. Setup stripe
4. Check logs for multiple errors, if not present, disconnect from Stripe and reconnect.

### Technical details:

* Ghost Version: 3.25.0

**Comment by ErisDS** [comment]
Can you link me to the exact lines of code that do steps 2 and 3 please?

**Comment by allouis** [comment]
https://github.com/TryGhost/Members/blob/b3d03501403714fbefb59f07557602a896671d41/packages/members-api/lib/stripe/api/createDeterministicApi.js#L64-L70

**Comment by ErisDS** [comment]
What does createDeterministicApi mean/do? I've never understood that bit of code.

As it stands it looks like this is due to a lack of an idempotency key?

**Comment by allouis** [comment]
It's deterministic because given an initial starting state it will always give back the same results when an operation is applied to it, the main feature is the `ensure` method which will ensure that a plan exists, creating it if it doesn't already.

> As far as I can tell it looks like this is due to a lack of an idempotency key?

It could be fixed with an idempotency key, we'd need a way of generating it that was the same between multiple restarts of the module - I think that could work by using the ID of the object we're trying to create

**Comment by ErisDS** [comment]
> On second thoughts I think we could use the "id" of the object we're creating as the idempotency key 👍 I think that's a nice solution.

This is what I would suggest. IMO it's elegant, and inline with what I understand you were trying to do with the deterministic API - surely idempotency is required for it to be truly deterministic?

**Comment by allouis** [comment]
> IMO it's elegant

:100: I really like it

Yeah you're right, this kind of "completes" it :relaxed: I'll start on that now so it's ready for tomorrow, should be a 1 line change, but I want to add test coverage!

**Comment by allouis** [comment]
When testing this solution earlier I received an error which said that you cannot make two requests at the same time with the same `Idempotency-Key'.

I haven't been able to replicate it since (I guess it's a timing issue/face condition) but this suggests to me to reconsider the solution completely.

> The API supports idempotency for safely retrying requests without accidentally performing the same operation twice. This is useful when an API call is disrupted in transit and you do not receive a response.
> -- https://stripe.com/docs/api/idempotent_requests

Their docs also hint at this, _retrying_ requests I think is key.

For now I would suggest that we `catch` errors of attempting to create resources, and if the resource already exists, return that.

something like:
```js
 .catch((err) => {
    if (err.code !== 'resource_already_exists') {
        throw err;
    }
    return stripeRetrieve(stripe, resource, id);
});
```

**Comment by ErisDS** [comment]
OK this sounds good as a fix for now. 

Not sure how we're managing to send duplicate requests at the exact same time, but can you confirm you're seeing that Stripe returns errors for both requests in that case? Rather than handling one and erroring the second?

**Comment by allouis** [comment]
> Not sure how we're managing to send duplicate requests at the exact same time

It's rare for sure, but it's a timing issue with how/when the `members-api` is "restarted" on the settings change, if the settings.editing events are emitted almost simultaneously then we have multiple instances started in parallel

> can you confirm you're seeing that Stripe returns errors for both requests in that case? Rather than handling one and erroring the second?

Do you mean the idempotent key errors? And if so, I haven't confirmed that, do you want me to confirm that before I proceed with the fix?

**Comment by ErisDS** [comment]
> It's rare for sure, but it's a timing issue with how/when the members-api is "restarted" on the settings change, if the settings.editing events are emitted almost simultaneously then we have multiple instances started in parallel

OK this sounds like it needs debouncing - but not right this second.

> Do you mean the idempotent key errors? And if so, I haven't confirmed that, do you want me to confirm that before I proceed with the fix?

Yes, I'm responding to the problem you reported. You said:

> When testing this solution earlier I received an error which said that you cannot make two requests at the same time with the same `Idempotency-Key'.

Unless you are reporting that 2 requests made at the exact same time **both** result in an error, then you are reporting that the idempotency key is working as expected? 

---

For now, catching the resource error is an acceptable solution. It's simpler to reason about. But once that is in master you need to revisit the idempotency key and confirm the behaviour you saw as it doesn't make sense to me.

**Comment by allouis** [comment]
> OK this sounds like it needs debouncing - but not right this second.

Yeah, makes sense!

> Unless you are reporting that 2 requests made at the exact same time both result in an error, then you are reporting that the idempotency key is working as expected?

I don't think so? If the second request errors then we are still in a situation where the request errored, it's just instead of an `'resource_already_exists'` errors it's an idempotency once, and we'd need code to catch that and then make a request to fetch the (presumably) created resource.

My understanding was that the idempotency key would solve this problem by _removing_ the error from duplicate requests, but if the requests are made simultaneously the error isn't removed, it's just changed.

 > But once that is in master you need to revisit the idempotency key and confirm the behaviour you saw as it doesn't make sense to me.

:ok_hand: WIll do, and i'll update this issue with the findings!

**Comment by ErisDS** [comment]
> I don't think so? If the second request errors then we are still in a situation where the request errored, it's just instead of an 'resource_already_exists' errors it's an idempotency once, and we'd need code to catch that and then make a request to fetch the (presumably) created resource.

> My understanding was that the idempotency key would solve this problem by removing the error from duplicate requests, but if the requests are made simultaneously the error isn't removed, it's just changed.

Right OK - that's what we're seeing differently. I am using idempotency keys in the work I'm doing to migrate stripe subscriptions, so I know that's not how it works - you get a StripeIdempotencyError

BUT you are correct in that the documentation _says_ something different:

https://stripe.com/docs/api/idempotent_requests

Still would be good to confirm (later) whether you saw a different time-based error than I see, so we can dig into this and properly understand how to do fully deterministic requests.

**Comment by allouis** [comment]
OH! Okay that clears a lot of things up! 

> Still would be good to confirm (later) whether you saw a different time-based error than I see, so we can dig into this and properly understand how to do fully deterministic requests.

:ok_hand: On a todo list for when I have some downtime :relaxed:
