### ISSUE TITLE
Error when deleting non-existent webhook using API token

### ISSUE THREAD

**Issue by daniellockyer** [TryGhost/Ghost#12064]
### Issue Summary

Attempting to edit/delete a webhook that does not exist, when using token auth as is used in the Admin-API, will cause Ghost to throw a 500 error. There is no handling to catch empty responses and further code relies on non-null variables.

This affects both the v2 & canary API for both editing & deleting webhooks.

```
[2020-07-20 13:37:17] ERROR "DELETE /ghost/api/v3/admin/webhooks/5f158f3f74f881da4668041f/" 500 8ms

Cannot read property 'get' of null

Error ID:
    befaa5a0-ca85-11ea-a85c-6f16a3bc205a

----------------------------------------

InternalServerError: Cannot read property 'get' of null
    at new GhostError (/home/neo/ghost/Ghost/node_modules/@tryghost/errors/lib/errors.js:10:26)
    at _private.prepareError (/home/neo/ghost/Ghost/core/server/web/shared/middlewares/error-handler.js:53:19)
[...]

TypeError: Cannot read property 'get' of null
    at Child.<anonymous> (/home/neo/ghost/Ghost/core/server/api/canary/webhooks.js:98:41)
    at Child.tryCatcher (/home/neo/ghost/Ghost/node_modules/bluebird/js/release/util.js:16:23)
[...]
```

### To Reproduce

1. Using the Admin-API:

```javascript
api.webhooks.delete({
    id: "5f158f3f74f881da4668041f" // this webhook does not exist
})
.then(console.log)
.catch(console.log);
```

2. :boom: Error as seen above.

Originally spotted in Sentry: https://sentry.io/organizations/ghost-foundation/issues/1792452009/

### Technical details:

* Ghost Version: 3.25.0
* Node Version: 12.18.0
* Browser/OS: Firefox/Linux
* Database: SQLite

**Comment by matthanley** [comment]
To confirm: expected behaviour here is to 404.

**Comment by naz** [comment]
As a reference for other places which throw 404 in permission checking context, [here](https://github.com/TryGhost/Ghost/blob/60907a7ae430647a6b639e57419c78ad7daf56f5/core/server/models/relations/authors.js#L355-L358) is handling for `post` resource. 

---

Random aside. @matthanley when looking for a reference found that referenced post's handling has `level: 'critical'`. I don't think this is a correct 'level' for this error as `critical` is meant to be something unpredictable like internal error, something worthy attention ([as described in Ignition](https://github.com/TryGhost/Ignition/blob/3439456d941753adf25c67b0d6ea29e61f214f68/README.md#list-of-errors)). This error level was introduced with [this PR](https://github.com/TryGhost/Ghost/pull/9426), but there is no context provided why this specific value was used. 

Plan to **not** use 'critical' when fixing this issue. Let me know what you think about changing referenced code :wink:

**Comment by matthanley** [comment]
> Let me know what you think about changing referenced code

@naz Makes sense to me to update to `normal` as docs suggest 👍
