### ISSUE TITLE
Members chart shows flat growth line for (GMT - X) timezones

### ISSUE THREAD

**Issue by rishabhgrg** [TryGhost/Ghost#12083]
### Issue Summary

If the site's timezone is set to any value before GMT/UTC, i.e. ( GMT - X ) timezones, the members chart in Admin incorrectly shows flatline with total number of current members since the start of date range, which is not the correct representation. 

<img width="1203" alt="chart-flat" src="https://user-images.githubusercontent.com/3461456/88509400-9ebc3a00-cffe-11ea-9ecd-b25fd839042e.png">

The 106 new members added in this date range should have been reflected in the chart correctly as growth instead of flat line.

### To Reproduce

1. Change the `Site timezone` to any (GMT - X) timezone in `Settings -> General` in Ghost Admin
2. Make sure you have new members added to site in the selected date range
3. The members chart on top will incorrectly show a flat line since start of range, instead of upward curve on date new members were added in that range.

### Technical details:

* Database: SQLite/Mysql

**Comment by sonyamann** [comment]
Hi, is there an ETA on the fix for this? Support sent me to this GitHub issue.

**Comment by ceohockey60** [comment]
Hi there, any update on the progress of this bug? Would appreciate an ETA. Thanks!

**Comment by sonyamann** [comment]
I still see a flat line in my dashboard. Fix not deployed yet?

**Comment by daniellockyer** [comment]
@sonyamann This will be released later today in 3.39.0. If you're a Pro customer, it'll be rolled out on Thursday 🙂
