### ISSUE TITLE
Incorrect date in toast box after scheduling a post

### ISSUE THREAD

**Issue by rishabhgrg** [TryGhost/Ghost#12102]
### Issue Summary

<img width="321" alt="incorrect-date" src="https://user-images.githubusercontent.com/3461456/89182277-10722600-d5b3-11ea-8a41-d39b3c03ce37.png">

When scheduling a post, the blue toast box incorrectly shows the month number (August -> 8) as the date of scheduled post instead of the actual date selected. This is only a UI bug, the post is scheduled correctly to the date selected.

### To Reproduce

1. Open a draft post in Ghost-Admin and schedule it for a later date and click "Schedule"
2. Notice the blue toast popup on bottom left with incorrect date (shows month number) as scheduled date, which can be confusing

**Comment by roshandash411** [comment]
Yeah I've found the fix `core/client/app/controllers/editor.js:849` had the format as `MMM Mo` . It needs to be changed to `MMM Do` . Raising a PR for this

**Comment by roshandash411** [comment]
This PR should fix it. https://github.com/TryGhost/Ghost-Admin/pull/1663

**Comment by rishabhgrg** [comment]
Thanks @roshandash411 , the fix is in master now and will be part of next release 🙌
