### ISSUE TITLE
Admin > Membership > Edit buttons responsivness 

### ISSUE THREAD

**Issue by KudMath** [TryGhost/Ghost#12101]
### Issue Summary

Admin > Membership > Edit -> Buttons responsivness is bad.

### To Reproduce

1. Admin > Membership
2. Clic Edit
3. You "may" see this depending on the window aspect ratio: 
![Screenshot 2020-08-03 at 12 48 23](https://user-images.githubusercontent.com/3056289/89175414-04bd3a00-d588-11ea-8b8c-c662ede3ef82.png)

### Technical details:

* Ghost Version: 3.25.0
* Browser/OS: Chrome / macOs

**Comment by ErisDS** [comment]
This was only ever an experimental feature and no longer exists. Please upgrade to latest.
