### ISSUE TITLE
Non-active themes are not listed on Design page 

### ISSUE THREAD

**Issue by daniellockyer** [TryGhost/Ghost#12118]
### Issue Summary

Originally reported in the [forum](https://forum.ghost.org/t/theme-not-available-from-git-clone/16407). 

In 3.29.0, any themes aside from the active one are not loaded upon boot, so they do not show up in the Design page.

I have bisected this back to https://github.com/TryGhost/Ghost/commit/71f02d25e9da2bbae727d5c3ead5c6d9b0de02ef, and the root cause is https://github.com/TryGhost/Ghost/commit/71f02d25e9da2bbae727d5c3ead5c6d9b0de02ef#diff-235914be5d0ec0f82a16a21e2e94618aL270. `server.start` is no longer emitted, but the theme service listens for it to be able to load all other themes - https://github.com/TryGhost/Ghost/blob/master/core/frontend/services/themes/index.js#L26

### To Reproduce

1. Install 3.29.0
1. `git clone` a theme to `content/themes`
1. Restart Ghost, and see it is not listed

### Technical details:

* Ghost Version: 3.29.0
* Node Version: 12.18.0
* Browser/OS: Firefox/Linux
* Database: SQLite

**Comment by ErisDS** [comment]
💩 will get that fixed today. With tests!
