### ISSUE TITLE
Enable Stripe promo codes via config

### ISSUE THREAD

**Issue by matthanley** [TryGhost/Ghost#12111]
Stripe have released a feature for [applying promo codes to subscriptions](https://twitter.com/stripe/status/1291441519585406976).

Ghost should expose (via config) an option to enable this functionality in Stripe. There's an [open PR](https://github.com/TryGhost/Members/pull/194) to enable this in Members, but the value is not taken from config.

The config flag (and the `allow_promotion_codes` flag passed to Stripe) should be disabled by default.

**Comment by signalnerve** [comment]
hey @matthanley! i'm interested in helping bring this over the finish line alongside my open PR in the members repo if you're interested - can you give me some guidance re: where to implement this?

**Comment by matthanley** [comment]
@signalnerve check out the docs for config [here](https://ghost.org/docs/concepts/config/).

The config module is implemented [here](https://github.com/TryGhost/Ghost/tree/master/core/shared/config), and you can see a usage example (with `compress`) [here](https://github.com/TryGhost/Ghost/blob/310ecd37c4433f4894952231f38bcb3352ef5d66/core/server/web/parent/app.js#L23).

**Comment by signalnerve** [comment]
thanks @matthanley! Finally have some to look at this today. Would it be appropriate to add a bool like `enableStripePromoCodes`? happy to add documentation too, just want to make sure I'm going about it the right way.

**Comment by allouis** [comment]
@signalnerve I think we'd pass the config from Ghost core, into the `members-api` instance. Probably around here: https://github.com/TryGhost/Ghost/blob/master/core/server/services/members/api.js#L144-L146 :relaxed:
