### ISSUE TITLE
Dialog Boxes do not gain focus using a screen reader.

### ISSUE THREAD

**Issue by rkingett** [TryGhost/Ghost#12114]
When using a screen reader, on any browser, dialog boxes do not automatically gain focus.

For example, upon first signing up, and creating a new blog, I hit the link, create a new blog, but was completely unaware that a dialog beneath the footer opened in order to confirm the action.

This, unfortunately, is happening across the whole dashboard with all dialog boxes.
Ideally, I'd like the dialog box to pop up and instantly gain focus, as well as the ability to interact with it with the keyboard independent of the rest of the page. 
 
### Technical details:

* Ghost Version:
3.2.3
* Browser/OS:

Firefox 79, Windows 10, 2004.

**Comment by sbeinlich** [comment]
I will attempt to work on this issue.

**Comment by rkingett** [comment]
Unfortunately, this issue is still a problem in 4.0.
