### ISSUE TITLE
Grant Administrator users ability to impersonate members

### ISSUE THREAD

**Issue by matthanley** [TryGhost/Ghost#12126]
### Issue Summary

Logging in as the Owner user is currently the only way to impersonate a member, but this should also be possible as an Administrator user.

Viewing a member page as the Owner user, the _Impersonate_ button is present:
<img width="1223" alt="Screenshot 2020-08-13 at 15 57 04" src="https://user-images.githubusercontent.com/3798302/90151808-0c968e80-dd7f-11ea-946e-5588b089a5b1.png">

Viewing the same page logged in as an Administrator user, the _Impersonate_ button is **not** present:
<img width="1274" alt="Screenshot 2020-08-13 at 15 58 21" src="https://user-images.githubusercontent.com/3798302/90151890-20da8b80-dd7f-11ea-9209-c68eeb84e1f9.png">

**Comment by rishabhgrg** [comment]
Waiting for final review on migration [PR](https://github.com/TryGhost/Ghost/pull/12132) before merge and release, no blockers otherwise.
