### ISSUE TITLE
Allow any email address from the ghost domain

### ISSUE THREAD

**Issue by anandkumar** [TryGhost/Ghost#12138]
With members feature Ghost has now option to send newsletters directly from the dashboard but it restricts the "FROM" address to the installation domain. Rather than it should just check if the email originating from the same domain.

For example:
If ghost site is live/installed at:

1. example.com, or
2. www.example.com, or
3. subdomain.example.com

Then using `foo@example.com` is perfect option. Rather than forcing users to choose from `foo@www.example.com` or `foo@subdomain.example.com`.

For sake of user experience please allow all subdomains. Of course we could verify if the email address belongs to the user or not.

**Comment by ErisDS** [comment]
This is neither how Ghost works currently, nor the correct place to discuss feature requests.
