### ISSUE TITLE
🐛 Draft posts can be accessed from anyone with the slug

### ISSUE THREAD

**Issue by MohmmedAshraf** [TryGhost/Ghost#12155]
By mistake, Zapier publish one of my draft posts on the Facebook page, so I've tried to access all draft posts with the slug and it's accessible, and am sure it's bug draft posts shouldn't access like this from anyone know the slug

* Ghost Version: 3.30.2
* Node Version: v10.21.0
* Database: MySQL

**Comment by ErisDS** [comment]
We have a bug report template for a reason! This is not reproducible for me using what I think are obvious steps, and you didn't include reproduction case. Therefore I assume there's something odd about your specific setup - please go to the forum, use the help template there and provide as much detail as you possibly can including a demonstration of the problem.

If it does turn out to be a bug, we can reopen this.
