### ISSUE TITLE
Code editor in Night Shift has barely-visible cursor

### ISSUE THREAD

**Issue by arktronic** [TryGhost/Ghost#12154]
### Issue Summary

The CodeMirror code editor in Ghost-Admin has a dark cursor when Night Shift is enabled:
![image](https://user-images.githubusercontent.com/344911/90986379-79b0dd80-e550-11ea-8359-22bbd4a9cc4b.png)

(Observe the cursor at the end of line 3 👆)

Note, the issue is NOT present for the Markdown-specific code editor.

### To Reproduce

1. Enable night shift
2. Start editing the default post "Writing posts with Ghost ✍️"
3. Click the code sample located under "Need to share some code? Embed code blocks directly" to get into edit mode
4. Click inside the editor to place the cursor anywhere in it

The cursor in Night Shift mode should instead be light colored so that it's easily visible.

### Technical details:

* Ghost Version: 3.30.2 (Docker official Debian-based image)
* Node Version: 12.18.3
* Browser/OS: Windows 10, latest Firefox as well as Chromium Edge
* Database: SQLite

**Comment by iamscottcab** [comment]
Not sure how to properly link these across repos but I have put a PR in for this one at https://github.com/TryGhost/Ghost-Admin/pull/1688

**Comment by iamscottcab** [comment]
@arktronic this was merged into 3.31.1 yesterday and I tested it by updating my personal blog today seems to work. Can you update version, this should be able to be closed now?

**Comment by arktronic** [comment]
Perfect! Thanks for the super fast turnaround, everyone!
