### ISSUE TITLE
Can't upload favicon in png or ico

### ISSUE THREAD

**Issue by inputuserhere** [TryGhost/Ghost#12166]
### Issue Summary

I attempted to upload a .ico file that is 15KB and 68x68 as well as favicon-68x68.png

Error: **Icon must be a square .ico or .png file between 60px – 1,000px, under 100kb.**

Referencing issue #8797 

### To Reproduce

1. Create a png file
2. This is the second step, etc.

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

### Technical details:

* Ghost Version: 3.31.2
* Node Version: 6.14.6
* Browser/OS: Chrome @latest / Ubuntu 18.04
* Database: mysql  Ver 14.14 Distrib 5.7.31
* Ghost-CLI version: 1.14.1

**Comment by ErisDS** [comment]
I can't reproduce this, can you share the files you're not able to upload?
