### ISSUE TITLE
Error when update complimentary plan to member

### ISSUE THREAD

**Issue by sbounmy** [TryGhost/Ghost#12162]
### Issue Summary

Following up my issue when trying to applying complimentary plan to user
https://github.com/TryGhost/Ghost/issues/11765?notification_referrer_id=MDE4Ok5vdGlmaWNhdGlvblRocmVhZDgzNDg3NDYwNzoxNTk4MTQ%3D#issuecomment-676180980

### To Reproduce

1. Go to Members
2. Edit a member
3. Set Complimentary Plan to yes
4. Hit Save
5. Error `Internal server error, cannot edit member. Cannot read property 'id' of undefined`

Note that User is correctly created on Stripe.

### Technical details:

* Ghost Version: 3.31.2
* Node Version: 10.16.2
* Browser/OS:  84.0.4147.125
* Database:

* Stack
`
{"name":"Log","hostname":"ghost-bounmy-io","pid":32455,"level":50,"req":{"meta":{"requestId":"31bf3216-fe18-4656-a50b-f2db2aced59c","userId":"1"},"url":"/members/5f451c2ceccfec7ec77e2025/?include=labels","method":"PUT","originalUrl":"/ghost/api/v3/admin/members/5f451c2ceccfec7ec77e2025/?include=labels","params":{},"headers":{"x-forwarded-for":"90.120.66.85","x-forwarded-proto":"https","x-real-ip":"*******","host":"sbounmy.com","connection":"close","content-length":"226","accept":"application/json, text/javascript, */*; q=0.01","x-requested-with":"XMLHttpRequest","x-ghost-version":"3.31","app-pragma":"no-cache","user-agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.125 Safari/537.36","content-type":"application/json; charset=UTF-8","origin":"https://sbounmy.com","sec-fetch-site":"same-origin","sec-fetch-mode":"cors","sec-fetch-dest":"empty","referer":"https://sbounmy.com/ghost/","accept-encoding":"gzip, deflate, br","accept-language":"en-US,en;q=0.9,fr;q=0.8","cookie":"**REDACTED**"},"query":{"include":"labels"}},"res":{"_headers":{"x-powered-by":"Express","cache-control":"no-cache, private, no-store, must-revalidate, max-stale=0, post-check=0, pre-check=0","access-control-allow-origin":"https://sbounmy.com","vary":"Origin, Accept-Encoding","content-type":"application/json; charset=utf-8","content-length":"248","etag":"W/\"f8-rlYZy0u9BBjUlD+1dt15E4A/2JA\""},"statusCode":500,"responseTime":"556ms"},"err":{"id":"4c4c4850-e6dd-11ea-8473-57401c385b67","domain":"https://sbounmy.com","code":null,"name":"InternalServerError","statusCode":500,"level":"normal","message":"Cannot read property 'id' of undefined","stack":"InternalServerError: Cannot read property 'id' of undefined\n    at new GhostError (/var/www/ghost/versions/3.31.2/node_modules/@tryghost/errors/lib/errors.js:10:26)\n    at _private.prepareError (/var/www/ghost/versions/3.31.2/core/server/web/shared/middlewares/error-handler.js:53:19)\n    at Layer.handle_error (/var/www/ghost/versions/3.31.2/node_modules/express/lib/router/layer.js:71:5)\n    at trim_prefix (/var/www/ghost/versions/3.31.2/node_modules/express/lib/router/index.js:315:13)\n    at /var/www/ghost/versions/3.31.2/node_modules/express/lib/router/index.js:284:7\n    at Function.process_params (/var/www/ghost/versions/3.31.2/node_modules/express/lib/router/index.js:335:12)\n    at next (/var/www/ghost/versions/3.31.2/node_modules/express/lib/router/index.js:275:10)\n    at Layer.handle_error (/var/www/ghost/versions/3.31.2/node_modules/express/lib/router/layer.js:67:12)\n    at trim_prefix (/var/www/ghost/versions/3.31.2/node_modules/express/lib/router/index.js:315:13)\n    at /var/www/ghost/versions/3.31.2/node_modules/express/lib/router/index.js:284:7\n    at Function.process_params (/var/www/ghost/versions/3.31.2/node_modules/express/lib/router/index.js:335:12)\n    at next (/var/www/ghost/versions/3.31.2/node_modules/express/lib/router/index.js:275:10)\n    at /var/www/ghost/versions/3.31.2/node_modules/express/lib/router/index.js:635:15\n    at next (/var/www/ghost/versions/3.31.2/node_modules/express/lib/router/index.js:260:14)\n    at next (/var/www/ghost/versions/3.31.2/node_modules/express/lib/router/route.js:127:14)\n    at apiImpl.then.then.catch (/var/www/ghost/versions/3.31.2/core/server/api/shared/http.js:96:17)\n\nTypeError: Cannot read property 'id' of undefined\n    at StripePaymentProcessor.setComplimentarySubscription (/var/www/ghost/versions/3.31.2/node_modules/@tryghost/members-api/lib/stripe/index.js:331:45)"},"msg":"Cannot read property 'id' of undefined","time":"2020-08-25T14:14:33.051Z","v":0}`

**Comment by sbounmy** [comment]
My members settings ![Screenshot 2020-08-25 at 16 28 42](https://user-images.githubusercontent.com/159814/91187194-2ecdcc00-e6f0-11ea-837d-25c31f27efd9.jpg)

**Comment by matthanley** [comment]
@sbounmy could you confirm if [a complimentary plan has been created](https://forum.ghost.org/t/complimentary-premium-plan-return-an-error/13738/3) in your Stripe account?

**Comment by sbounmy** [comment]
@matthanley thanks for helping out.

I didnt have the complimentary plan so I decided to disconnect my stripe account https://forum.ghost.org/t/cannot-disconnect-while-there-are-members-with-active-stripe-subscriptions/15591

Then connecting a new Stripe account worked it created a complimentary plan + others
![Screenshot 2020-09-15 at 09 22 06](https://user-images.githubusercontent.com/159814/93179329-ce054280-f735-11ea-9b22-b82bff16a000.jpg)
![Screenshot 2020-09-15 at 09 26 19](https://user-images.githubusercontent.com/159814/93179358-d8bfd780-f735-11ea-8b37-abd5cc306ac2.jpg)
