### ISSUE TITLE
Cannot edit a image caption after adding a hyperlink

### ISSUE THREAD

**Issue by curiousdungbeetle** [TryGhost/Ghost#12188]
### Issue Summary

In both my browser (Firefox 80) and in the Windows Ghost app, if I add an image, edit a caption and add a hyperlink to part of the caption, afterwards I cannot edit the caption. The only solution is to remove and re-add the image.

### To Reproduce

1. Add an image
2. Write text in the caption, e.g. "Illustration by Author, from Website"
3. Right-click "Website" and add a hyperlink.
4. If I then want to add text, or add a hyperlink to another part like "Author", clicking anywhere in the caption results in nothing (no blinking cursor, nothing happens if I then type). Closing and reopening the browser or app sometimes allows re-editing, but not consistently. 

### Technical details:

* Ghost Version:  3.32.1
* Node Version: 12.18.3
* Browser/OS: Firefox 80.0.1 on Windows 10, also in Windows Ghost app
* Database: mysql

**Comment by matthanley** [comment]
Hey @curiousdungbeetle! I've been unable to repro this issue in Chrome or Firefox, but if you're pasting in the URL from a rich-text source you may be running into the same issue as #11779 - could you confirm if this is the case?

**Comment by curiousdungbeetle** [comment]
Hi Matt. No, it happens when I type in normal text (no copy/paste). It tends to happen if I edit the text, add a hyperlink with Ctrl-H, then go out of the caption and try to click in again. 
I have recorded my screen when doing this with the Windows app: https://youtu.be/mcmrjQmCbmc (from 40s, I'm trying to click back in the caption, to no avail, but I can edit the rest).

**Comment by kevinansfield** [comment]
@curiousdungbeetle I've been trying to replicate this and followed your video steps as closely as possible with both Chrome and Firefox but so far have been unable to reproduce.

You mentioned <kbd>Ctrl-H</kbd>, is that a typo? In captions that shouldn't do anything, in the main editor it would cycle header levels rather than add links.

**Comment by curiousdungbeetle** [comment]
Oh yes apologies, Ctrl-K for hyperlink. But also simply when selecting text and using the hyperlink function in the hoverbox.
