### ISSUE TITLE
Members list is not refreshed when clicking on "Members" menu

### ISSUE THREAD

**Issue by peterzimon** [TryGhost/Ghost#12185]
### Issue Summary

The list of members is not refreshed when clicking on the "Members" menu item.

### To Reproduce

0. Go to "Members" in Ghost Admin to doublecheck your latest members.
1. Click on a different menu item (e.g. "Staff" or "Posts")
2. Sign up as a member on the site. Click on "Activate my account" in the confirmation email.
3. Go back to the Admin and click on Members

💥 The new member doesn't appear automatically in the list of members, only if you refresh the Admin. The member list should refresh when navigating to it. 

### Technical details:

* Ghost Version: 3.32.0
* Node Version: 12.18.1
* Browser/OS: Firefox
* Database: sqlite

**Comment by matthanley** [comment]
> The members list data is only refreshed once it's >60sec old when navigating around so that navigation speed away from then back to the members list is reasonable.

Closing as this is expected behaviour, but can reopen if we need to review the timeout.
