### ISSUE TITLE
Authors dropdown not allowing add/remove author in post settings menu

### ISSUE THREAD

**Issue by rishabhgrg** [TryGhost/Ghost#12198]
### Issue Summary

The author selection and removal is not working correctly in Ghost-Admin from Post settings menu. This issue is present in both 3.32.0/3.32.1 releases, caused by a bump to ember-core dependency by renovate.

### To Reproduce

1. Open Post settings menu for any existing Post in Ghost-Admin
2. Try adding a new Author from the Author dropdown in settings, the selected author doesn't show up in the list
3. On saving and refresh, the author is shown in the list. Try removing the author with `x` or by selecting them from author list. The author is not removed from the selected authors.

### Technical details:

* Ghost Version: 3.32.0-3.32.1

**Comment by planksip** [comment]
And for a site like planksip.org, we heavily rely on changing and updating authors in the posts. Thanks, guys for working on this so quickly.
