### ISSUE TITLE
Superscript and Subscript do not render in a Markdown card

### ISSUE THREAD

**Issue by frantzypants** [TryGhost/Ghost#12219]
### Issue Summary

When trying to insert a superscript or subscript in a Markdown card within the editor, the `^test^` and `~test~` do not render their expected results.

### To Reproduce

1. Create a new post
2. Select a Markdown card from the "+" menu
3. Type in the markdown for either superscript (`^supertext^`) or subscript (`~subtext~`)
4. Observe that neither bits of text are transformed.

That said, both **do** work in the regular editor using Markdown.

### Technical details:

* Ghost Version: v3.33.0
* Database mysql

**Comment by sbeinlich** [comment]
I will look into working on this

**Comment by JasonCEC** [comment]
This seems to remain an open problem, using the `normal~subscript~` syntax renders subscript in the editor but not the published page.

**Comment by coreyasmith** [comment]
> This seems to remain an open problem, using the `normal~subscript~` syntax renders subscript in the editor but not the published page.

I noticed this as well. I've put in a pull request to fix this issue: [Koenig/#400](https://github.com/TryGhost/Koenig/pull/400).
