### ISSUE TITLE
Impersonate modal stays open when navigating between members

### ISSUE THREAD

**Issue by peterzimon** [TryGhost/Ghost#12214]
### Issue Summary

When navigation back and forth between different members, the impersonation popup remains open if it was opened before.

### To Reproduce

1. Go to a member's detail screen
2. Click "Impersonate"
3. Click the browser's back button. The modal is closed (expected)
4. Go to the details of a member.

💥 The impersonation modal automatically opens with dummy data in it. The expected behaviour would be that the impersonation (or any) modal closes when the context is not relevant anymore and going back to the screen shouldn't re-open it.

### Technical details:

* Ghost Version: 3.33.0
* Browser/OS: Firefox
* Database: sqlite

**Comment by sbeinlich** [comment]
@matthanley I can work on this. Do you think it's reasonable to simply call the modal's close() action upon willDestroyElement()?

**Comment by sbeinlich** [comment]
I can work on this
