### ISSUE TITLE
Posts with changed tags always at top in channel

### ISSUE THREAD

**Issue by cduerselenBX** [TryGhost/Ghost#12223]
### Issue Summary

If the tags of a post got edited/changed the posts always appear first in a channel view. Even newly created posts are below the posts which have been edited.

### To Reproduce

1. Create a post A with tags not relevant for a channel
2. Create a different post B with tags relevant for a channel
3. Change post A's tags so it gets relevant for the cannel
4. Create a post C with tags relevant for a channel

Post B will always be at the top of the channel view no matter how many posts will be added

### Technical details:

* Ghost Version: 3.27.0
* Node Version: v12.18.3
* Browser/OS: Windows 10 / Edge Chromium

**Comment by lunaticmonk** [comment]
@cduerselenBX Was trying to replicate this. Can you please elaborate what a channel means here? Please correct me if I am missing something, didn't get the context on the channel.

**Comment by cduerselenBX** [comment]
Hi @lunaticmonk, thank you for your response. I mean channels as described in this documentation article: https://ghost.org/docs/api/v3/handlebars-themes/routing/channels/

**Comment by sbeinlich** [comment]
I was unable to reproduce this following the steps outlined. I see an ordering of Post C, Post B, Post A. Is this the behavior you're expecting @cduerselenBX ? If not, what order are you expecting?

**Comment by cduerselenBX** [comment]
strange - the order mentioned by you is as I would have expected it. have you looked at it in the channels view? in my main view (all posts) the order of the posts is also normal on my computer. but in the specific channel view (only the posts belonging to the channel) it is Post A, Post C, Post B. i am using a local instance fyi. thank you very much for your help!

**Comment by sbeinlich** [comment]
No problem @cduerselenBX. I was indeed looking at the channels view, I spun up a local instance with a small example. I couldn't reproduce it in either view. Can you show me your routes.yaml and list the corresponding tags on Post A, C, B?

**Comment by cduerselenBX** [comment]
hi @sbeinlich , yes for sure. you can find my routes.yaml attached (as a txt file so github allows the upload). I also started to analyze the problem a little bit more: You were completely right. I spun up a new instance of ghost, followed my steps and got the same result as you did with the right order. Then I checked the difference to my original environment and found out that the proplem seems not to be the process of changing the tags but adding another tag to the post. So I tried this on my fresh instance and got the same wrong results and an ordering of Post A, Post C, Post B. 

To sum it up I did the following steps:

- Added Post A without a Tag
- Added Post B with a Tag relevant for the Channel
- Changed Post A Tag so it got relevant for the Channel
- Added Post C with a Tag relevant for the Channel - until then everything worked fine
- Added a second Tag to Post A - Post A is now always at the front in the channel view

I also added two pictures to proove this and so you do not think I am a complete idiot ;-) 

Thank you so much for your support!

[routes.txt](https://github.com/TryGhost/Ghost/files/5525775/routes.txt)
![image](https://user-images.githubusercontent.com/64377439/98844169-3ded2c00-244c-11eb-8130-3a29678c0f0a.png)
![image](https://user-images.githubusercontent.com/64377439/98844645-ed2a0300-244c-11eb-9704-387ebfa9e293.png)

**Comment by cduerselenBX** [comment]
oh and regarding the tags: all posts first got the lc20 tag and post A then got the getting-started tag as well.

**Comment by sbeinlich** [comment]
Ah I see. Seems to be an issue with [this query ordering filter.](https://github.com/TryGhost/Ghost/blob/6ba6e9c3077a35237fd1bccd801936433775ea50/core/server/models/post.js#L815-L818). 

I don't think I understand the case where the above code is useful, or the similar code that checks for authors under it. The COUNT(*) query fragment does not account for whether or not you're counting tags that are being queried for, so whichever posts have the most tags will appear highest in the list. Perhaps a maintainer could comment on this, it seems to have been added by @kirrg001, but it doesn't seem she's active anymore.

**Comment by ErisDS** [comment]
I have only just caught up on this - it's totally expected behaviour. 

99% of the time, when someone uses an IN query with tags, they're trying to get related posts. Therefore we automatically change the order of the posts to be most-matching-tags-first. This is an extremely complex order and there's no way to specify it using the API, so it being the default behaviour makes it _possible_ as well as more frequently the desired behaviour.

Meanwhile, if you want to change the order to reverse chronological you would add `order: published_at desc` to your channel, e.g.

```
/zen/:
    controller: channel
    filter: primary_tag:[zen,all]
    order: published_at desc
```
