### ISSUE TITLE
Issue with attribute 'data-members-name'

### ISSUE THREAD

**Issue by fueko** [TryGhost/Ghost#12249]
## Issue Summary

In Ghost 3.35.0 added support for 'data-members-name' in themes but if the theme uses only attribute 'data-members-email' (e.g. Casper) you cannot register (error in console 'null is not an object' inside members.js).

### To Reproduce

1. Install Ghost 3.35.0 and start with default Casper theme.
2. Attempt to register.

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

The 'data-members-name' attribute should be optional, not mandatory.

### Technical details:

* Ghost Version: 3.35.0
* Node Version: v12.18.1
* Browser/OS: Safari / MacOS
* Database: v12.18.1

**Comment by matthanley** [comment]
Refs #12029

**Comment by allouis** [comment]
Fixed in 3.35.1 https://github.com/TryGhost/Ghost/releases/tag/3.35.1
