### ISSUE TITLE
Appending page drafts with /edit results in a 404

### ISSUE THREAD

**Issue by stromfeldt** [TryGhost/Ghost#12258]
### Issue Summary

There was an earlier bug whereby appending a (published) page with `/edit` sent one to `/ghost/#/editor/post/{id}/` rather than `/ghost/#/editor/page/{id}/`. That was fixed about a year and a half ago (I can't locate the issue #). I just noticed that the issue partially still exists, but only when trying to add the `/edit` to a page in _draft_ mode.

### To Reproduce

1. Create a new page, but don't publish it
2. Preview the page
3. Add `/edit` to `/p/{id}/` in order to get to the editor
4. Result is a 404

### Technical details:

* Ghost Version: 3.35.3

**Comment by sbeinlich** [comment]
Looking into this, it's related to the [fact that the preview handler is generic.](https://github.com/TryGhost/Ghost/blob/2a921b86598184fcd5a2d95fefae4283bba1042a/core/frontend/services/routing/controllers/preview.js#L40-L43).
