### ISSUE TITLE
[Members] Subscriptions listed for members only include `active` and `trialing` 

### ISSUE THREAD

**Issue by allouis** [TryGhost/Ghost#12256]
Currently when listing subscriptions for Members in both the Admin and the Theme, we only show the subscriptions which have a status of `trialing` or `active`.

When https://github.com/TryGhost/Ghost/issues/12255 is completed we will be supporting subscriptions with the `unpaid` and `past_due` status as paid subscriptions, and as such it makes sense for these to appear when listing a members subscription.

As well as this it is probably useful to be able to see previously cancelled subscriptions, so the proposal for this issue is to list _all_ subscriptions for members in both the Admin and the Theme.

The theme layer can use the `status` as a class on the subscription element, so the site owner will retain the ability to only show specific subscriptions to the user on the site.

Tasks

- [x] Add support for `unpaid` and `past_due` subscriptions as active members
- [x] Add support for cancelled (all) subscriptions

**Comment by allouis** [comment]
@peterzimon Would love some feedback on this and what you think makes sense!

**Comment by rishabhgrg** [comment]
Closed with https://github.com/TryGhost/Ghost/commit/0ce5f87616742ebf9c9b88f8e674ec5d006f7784 , we added subscriptions with `past_due` and `unpaid` status to be listed as active subscriptions for a member.

**Comment by allouis** [comment]
@rishabhgrg I believe that commit was missing this:

> As well as this it is probably useful to be able to see previously cancelled subscriptions, so the proposal for this issue is to list all subscriptions for members in both the Admin and the Theme.

That commit only adds support for `unpaid` and `past_due` :thinking:

**Comment by rishabhgrg** [comment]
@allouis Ah yeah good point, reopening and breaking down original description with updated task list 👍

**Comment by allouis** [comment]
This landed in master with https://github.com/TryGhost/Ghost/commit/18b87d97341af371a5fcaf5ed65f3877d2b69eff and some admin refinements based on the changes here: https://github.com/TryGhost/Ghost-Admin/commit/b246f614d7f103efe95d01d7a55ab6292eb6e56b
