### ISSUE TITLE
[Portal] Hitting ESC quits Portal preview in Admin

### ISSUE THREAD

**Issue by peterzimon** [TryGhost/Ghost#12264]
### Issue Summary

Hitting ESC in Portal settings quits the portal modal and shows the live preview of the Ghost site.

### To Reproduce

1. Open Portal settings from Labs
2. Hit ESC
3. 💥 The popup modal is closed and the live site preview is displayed in the preview iframe

It is a bug as ESC should quit the portal settings popup and not the Portal modal.

**Comment by rishabhgrg** [comment]
Fixed with https://github.com/TryGhost/Portal/commit/f276769d4a2aeb6194a93491c9daf5ed10159a3b
