### ISSUE TITLE
Mathjax doesn't work well in ghost blog. 

### ISSUE THREAD

**Issue by ML2jinmyoung** [TryGhost/Ghost#12267]
Hello! I added Mathjax to ghost blog. 
Most of them are well rendered, but 'left \right' (or \mathcal) is not rendered as follow.
<img width="767" alt="스크린샷 2020-09-28 오후 6 19 13" src="https://user-images.githubusercontent.com/52397255/95423753-95dfd100-097c-11eb-8e14-2f7ce9d54350.png">

Here is my MathJax config in Code injection. 

```
<script type="text/javascript"
        src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-AMS_HTML"></script> 
<script type="text/javascript"
   		src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-AMS-MML_CHTML">
</script>
<script type="text/x-mathjax-config">
  MathJax.Hub.Config({
    jax: ["input/TeX","output/HTML-CSS"], 
    TeX: {
     
      extensions: ["tex2jax.js", "TeX/AMSmath.js", "TeX/AMSsymbols.js"],
      equationNumbers: {
      autoNumber: "AMS"
      },
      tags: "AMS"
    },
    tex2jax: {
      inlineMath: [ ['$','$'], ["\\(","\\)"]  ],
      displayMath: [ ['$$','$$'],["\\(","\\)"]  ],
      processEscapes: true
    },
    loader: {load: ['[tex]/ams']},
  	tex: {packages: {'[+]': ['ams']}}
  });
</script>
```

I couldn't figure out what is the problem. Please help!

**Comment by ruiokada** [comment]
`{` and `}` are special characters in TeX, like you usually use them as "wrappers": $x_{n - 1} = e^{n-1}$. In order to make a set you need to escape the curly braces: $$\mathcal{X} = \left\{x_1, x_2, \ldots, x_n \right\}$$.

**Comment by ML2jinmyoung** [comment]
Thank you for your quick answer.
I included \ when I wrote from the md file, but I found that` \left \ `changed to` \left` when it was rendered. I don't know the exact cause, but when I switched to` \left \\`, the problem was solved.
I fixed the config as you pointed out. Thank you.
