### ISSUE TITLE
[Bug Fixed] Long-existing non-latin IME bug fixed, please update & merge latest mobiledoc-kit

### ISSUE THREAD

**Issue by xufangda** [TryGhost/Ghost#12268]
# Issue Summary
A long-lasting editor bug for typing in non-Latin characters has been repeatedly proposed in last two years but never resolved by mobiledoc-kit. This bug seriously damaged  user experience for non-latin Ghost users. Now it has been fixed by mobiledoc-kit, please pull and merge latest mobiledoc-kit.

# Description
Every time when non-Latin language user typing in Japanese / Chinese / Korea character, unwanted Latin character will appear. For the details of this bug, please refers to:
https://github.com/TryGhost/Ghost/issues/9801
https://github.com/TryGhost/Ghost/issues/9289
https://github.com/TryGhost/Ghost/issues/9012
https://github.com/TryGhost/Ghost/issues/8319

**NOW THIS BUG HAS BEEN FIXED, YOU ONLY NEED TO PULL & UPDATE YOUR mobiledoc-kit!!**
For people who don't know, mobiledoc-kit is the rich-text editor that ghost is using. 

# Solution
**THIS BUG HAS BEEN FIXED BY mobiledoc-kit side**
For people who don't know, mobiledoc-kit is the rich-text editor that ghost is using. 

**mobiledoc-kit MERGED the bugfix PR on 2020-07-15** 
[fix IME bugs: mobiledoc-kit PR #738](https://github.com/bustle/mobiledoc-kit/pull/738)

**mobiledoc-kit LATEST RELEASE on 2020-10-06**

**COULD YOU PLEASE PULL AND MERGE the latest mobiledoc-kit to GHOST?**

This will save thousands of non-Latin users. This bug has been existing for 2 years, and pushed so many non-latin Ghost lovers away.

THANKS FOR FIXING THIS BUG!!!!

**Comment by kaynAw** [comment]
STILL WAITING RELEASE

**Comment by tnmt** [comment]
I made PR TryGhost/mobiledoc-kit#15 to solve the Issue.

Could you check it?

**Comment by Windfarer** [comment]
They just don't care about CJK users.

**Comment by Ewocker** [comment]
+1

**Comment by daniellockyer** [comment]
Hi all! Thank you for your patience. We've merged the upstream fix into our fork of mobiledoc-kit and bumped this in Ghost-Admin. You should see this getting released in the next version of Ghost 🙂

**Comment by shincurry** [comment]
Ghost v3.38.3 seems to solved this issue.
