### ISSUE TITLE
Dated permalinks always use UTC instead of site timezone

### ISSUE THREAD

**Issue by kevinansfield** [TryGhost/Ghost#12280]
### Issue Summary

If you use dated permalinks in your routes.yaml file for a collection (`permalink: /{year}/{month/{day}/{slug}/`) and you have your site timezone set to something other than UTC then the date in the url may not match the publish date.

### To Reproduce

1. Modify your `routes.yaml` to use dated permalinks
2. Set your timezone to non-UTC (a large timezone difference makes this easier to test)
3. Publish a post with a publish date that would result in a different date when converted to UTC (eg, if you've chosen UTC+8 as your site timezone, publish a post with a time between 00:00 and 08:00 to see a URL one day earlier than expected)
4. Examine the URL that is given to the post to see that it's +/- 1 day from the expected date

### Technical details:

This bug was introduced in https://github.com/TryGhost/Ghost/pull/10787 where our url-utils package was extracted. The problem arises because the [`replacePermalink()` method](https://github.com/TryGhost/Ghost-SDK/blob/master/packages/url-utils/lib/utils/replace-permalink.js#L6) expects a third argument which is the site's timezone (defaulting to `UTC` when not present) but the [`UrlGenerator` code which calls that method](https://github.com/TryGhost/Ghost/blob/master/core/frontend/services/url/UrlGenerator.js#L196) does not pass any argument.

## Problems with a fix

Implementing a straightforward fix would introduce a breaking change for any site using dated permalinks and non-UTC timezones. Any of the site's posts with an "incorrect" date in the url would immediately get a new URL after the upgrade meaning that external links to the post would result in a 404. With the fix in place, changing the site's timezone would also modify post's URLs so we should make this clearer in the admin UI.

The bug has been in place for ~16 months so that's potentially quite a big unexpected breaking change for some sites.

There aren't too many options to work around the problem whilst keeping dated permalinks. If dated permalinks are dropped then it's possible to set up generic redirects using the `{slug}` value that is still present in the URL. If dated permalinks want to be kept then it would be necessary to work out which posts would receive a different URL and manually create a redirect for them.

**Comment by ErisDS** [comment]
Going to close this - it's still tracked as a potential change to make with 5.0 and will fit more when we look at reworking our routing layer. We haven't had any complaints, so I don't think anyone is seriously impacted.
