### ISSUE TITLE
Ctrl/Cmd+V not working for tags in post settings menu

### ISSUE THREAD

**Issue by daniellockyer** [TryGhost/Ghost#12294]
### Issue Summary

Pasting in text, via Ctrl/Cmd+V, to the Tags field doesn't work in the post settings menu.

### To Reproduce

1. Have some text copied in your clipboard
1. Open the post settings menu 
1. Click in the Tags field and try to paste via Ctrl/Cmd+V
1. Note that nothing is entered.

Workaround is to use the mouse to right click and paste.

### Technical details:

* Ghost Version: 3.35.5
* Node Version: 12.18.0
* Browser/OS: Firefox/Linux
* Database: MySQL

**Comment by kevinansfield** [comment]
Note: This bug was possibly introduced as a side-effect of fixing the Cmd+S shortcut when token inputs have focus https://github.com/TryGhost/Ghost-Admin/pull/1707

**Comment by sainthkh** [comment]
Confirmed that my PR caused the problem. I'm currently finding a solution.
