### ISSUE TITLE
Console error when member is not logged in

### ISSUE THREAD

**Issue by fueko** [TryGhost/Ghost#12328]
### Issue Summary

Console error when member is not logged in:

![Zrzut ekranu 2020-11-4 o 11 10 02](https://user-images.githubusercontent.com/23366922/98098494-b4a78980-1e8e-11eb-9dc8-e9398dbf41c7.png)

### Technical details:

* Ghost Version: 3.37.1
* Node Version: v12.18.1
* Browser/OS: All / macOS 10.15.7
* Database: sqlite3

**Comment by matthanley** [comment]
Closing as this isn't a bug.
