### ISSUE TITLE
"Contact support" mailto link not working in portal

### ISSUE THREAD

**Issue by astab** [TryGhost/Ghost#12367]
The "Contact support" mailto link is not working in the portal account settings screen.

### To Reproduce

1. Sign in to a Ghost site
2. Open portal account settings screen
3. Click on the "Contact support" button

### Technical details:

* Ghost Version: 3.37.1

**Comment by rorysaur** [comment]
FWIW, the "Publish with Ghost" button on the same view doesn't seem to work either.

I'm on version 3.38.2.

**Comment by rishabhgrg** [comment]
Thanks @astab and @rorysaur for the report, we have pushed a fix for this in Portal now and should be out soon with next Portal release 😄
