### ISSUE TITLE
tag based code injection does not work

### ISSUE THREAD

**Issue by danielnachtrub** [TryGhost/Ghost#12363]
### Issue Summary

Setting code injection on tags does not work. This affects headers as well as footer tags. Global or post based code injection works as expected.

### To Reproduce

1. Create a new tag
2. Add code injection (header or footer)
3. Refresh post

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

### Technical details:

* Ghost Version: 3.37
* Node Version: 6.14.8
* Browser/OS: chrome
* Database: mysql

**Comment by matthanley** [comment]
Hey @danielnachtrub 👋  Tag-based code injection is only intended to work on the tag index page, rather than on individual posts with the tag applied. You'd need to handle this in the theme if you'd like to inject code to a post based on the tags applied.
