### ISSUE TITLE
Home Icon Appearing when turning on Night Mode

### ISSUE THREAD

**Issue by mcnaveen** [TryGhost/Ghost#12396]
### Issue Summary
Home Icon Appearing when turning on/off night mode inside Ghost Admin Panel

### To Reproduce

1. Open Ghost Admin
2. Go to Labs
3. Turn ON/OFF Night Shift

### Additional
* I have made a quick video
 https://www.loom.com/share/de8c885095c44c68adc7a049bb7b5cbd

### Technical details:

* Ghost Version: 3.34.0
* Node Version: 12.19.1
* Browser/OS: Chrome 87.0.4280.66 /Ubuntu 20.04
* Database: MySQL

**Comment by asperger99** [comment]
Can I work on this? @matthanley

**Comment by matthanley** [comment]
@asperger99 feel free to submit a PR! Note that the team are on a break over Christmas so the feedback loop may be slower than usual.
