### ISSUE TITLE
email_recipient_filter=free misses users in notifications (3.38.2)

### ISSUE THREAD

**Issue by os72** [TryGhost/Ghost#12417]
Posting with `free` option (both manual and via API) seems to miss out users in the email notification

On my test site, for the free option, it misses 1 user. On the manual publish preview it shows 3 free members, but then the email is sent only to 2

Sending to `all` does include all subscribers

Related conversation
https://github.com/TryGhost/Ghost/pull/12343
https://forum.ghost.org/t/posting-via-api-does-not-send-email-notification/18139

**Comment by allouis** [comment]
This is part of a larger problem with listing free members and is tracked here https://github.com/TryGhost/Ghost/issues/12160
