### ISSUE TITLE
paid post with email_recipient_filter=all delivers content to everyone (3.38.2)

### ISSUE THREAD

**Issue by os72** [TryGhost/Ghost#12418]
Not sure this is by design, and I believe the behavior used to be different with `send_email_when_published=true`

There is an inconsistency of sorts because `paid` post with `email_recipient_filter=all` seems to deliver the post content (not just the title) to everyone, not just paid subscribers. I believe that wasn't the case earlier

Related conversation
https://github.com/TryGhost/Ghost/pull/12343
https://forum.ghost.org/t/posting-via-api-does-not-send-email-notification/18139

**Comment by allouis** [comment]
This is expected behaviour, if you would like to send an email only to paid members you can use `email_recipient_filter=paid`
