### ISSUE TITLE
Cookie ghost-members-ssr not found in logs (and 400 code returned to client)

### ISSUE THREAD

**Issue by iprok** [TryGhost/Ghost#12433]
### Issue Summary

When members option is turned on my site I see error with http response 400 in browser console while visiting main page of the site on request /members/api/member/ . I can see warning "WARN Cookie ghost-members-ssr not found" in logs connected with the error. In general ghost is working but spamming log with the warning annoys me a little bit. If it's expected behaviour can you please lower the logging level of the message to info?

### To Reproduce

Turn on members option in your ghost installation. Visit the main page and look in your browser console.

### Technical details:

* Ghost Version: 3.38.3
* Node Version: (don't know, I'm using the latest official docker image: ghost:3-alpine)
* Browser/OS: any, e.g. chromium 86.0.4240.198
* Database: MySQL

**Comment by nehalist** [comment]
Wanted to test out the latest version of Ghost locally and get the same error. Node version in my case is `12.19.1`. Trying to sign up results in a 500 from `/members/api/send-magic-link/` with the following response

```
{
  "errors": [
    {
      "message": "Resource not found",
      "context": null,
      "type": "NotFoundError",
      "details": null,
      "property": null,
      "help": null,
      "code": null,
      "id": "d80fbff0-3252-11eb-b588-bd5eb2255e14"
    }
  ]
}
```

**Comment by nehalist** [comment]
Wait a second - being unable to test the highly praised new features due to an obvious bug and the issue is "just closed" without even saying a single word about the issue? No "we know about that and it'll be fixed", "must be your fault", "we don't give a single fck" - just... nothing?

**Comment by iprok** [comment]
I'm not related to the ghost development from any side, I'm an author of the thread and I'm sure that the task is not related to any serious problem to members functionality in ghost.

 I tried the functionality yesterday and it's working. It's only about warning in the logs.

Are you sure that you have turned on the functionality in Labs section?

**Comment by matthanley** [comment]
@nehalist if you believe there's an additional bug, please open a new issue following our issue template. The error you've provided isn't related to the original issue raised, which isn't a bug - it's expected behaviour at the moment.
