### ISSUE TITLE
Exclude Stripe keys from exports

### ISSUE THREAD

**Issue by daniellockyer** [TryGhost/Ghost#12449]
### Issue Summary

When exporting a Ghost site, all the Stripe keys are included in the produced backup. We would expect someone re-importing to need to reconnect their Stripe, and including them and so we shouldn't include these keys in the export.

This can also cause things related to https://github.com/TryGhost/Ghost/issues/12448 where the keys are used locally and wipe the live webhooks.

I recently produced a backup and set the following keys to `null` just to be sure:
* `stripe_connect_publishable_key`
* `stripe_connect_secret_key`
* `stripe_secret_key`
* `stripe_publishable_key`
* `stripe_connect_account_id`
* `members_stripe_webhook_id`
* `members_stripe_webhook_secret`

### To Reproduce

1. Produce an export for a site with Stripe connected
2. Check the values of the keys mentioned above

### Technical details:

* Ghost Version: 3.39.0
* Node Version: 12.18.0
* Database: MySQL

**Comment by matthanley** [comment]
ref https://github.com/TryGhost/Ghost/pull/12573
