### ISSUE TITLE
Implement OAuth2

### ISSUE THREAD

**Issue by finn-ball** [TryGhost/Ghost#12452]
### Issue Summary

Implement OAuth2. It seems to be the [most voted for non-planned feature on the forums](https://forum.ghost.org/t/third-party-single-sign-on-sso/3321). Is there a place that open source developers can discuss contributing and proposing methods of implementations with the Ghost developers?

### To Reproduce

1. Start Ghost in docker
2. Look for OAuth2.

### Technical details:

* Ghost Version: 3.38.3
* Node Version:
* Browser/OS:
* Database:

**Comment by finn-ball** [comment]
How does one actually discuss feature requests with the developers?

**Comment by matthanley** [comment]
Hey @finn-ball 👋 We're currently tracking this feature internally.

**Comment by finn-ball** [comment]
Hey! Thanks for the reply :) Care to open source the tracking of this feature?

Do you have any early implementations?

**Comment by finn-ball** [comment]
@matthanley - Scanning down here, there seems to be a closed sourced version of OAuth for the paid plan only:

https://ghost.org/pricing/

Are there any plans to open source this?

**Comment by jwmarshall** [comment]
Any update? This is really, unfortunately, a nail in the coffin feature for me. 🙏
