### ISSUE TITLE
Svg badges are displayed incorrectly in the markdown card after post publication

### ISSUE THREAD

**Issue by GenZmeY** [TryGhost/Ghost#12456]
### Issue Summary

A set of svg badges on one line are displayed on separate lines in the markdown card after publication.
However, inside the editor the badges are displayed correctly (on one line).

### To Reproduce

1. Create a new post
2. Select a Markdown card from the "+" menu
3. Add multiple svg badges on one line, like this:
```
[![DeviantArt](https://img.shields.io/static/v1?message=DeviantArt&logo=deviantart&labelColor=5c5c5c&color=00DC96&logoColor=white&label=%20)]() [![Steam](https://img.shields.io/static/v1?message=Steam&logo=steam&labelColor=5c5c5c&color=gray&logoColor=white&label=%20)]() [![Shikimori](https://img.shields.io/static/v1?message=Shikimori&logo=shikimori&labelColor=gray&color=lightgray&logoColor=white&label=%20)](https://genzmey.su) [![PlayStation](https://img.shields.io/static/v1?message=PlayStation&logo=playstation&labelColor=gray&color=blue&logoColor=white&label=%20)]() [![GitHub](https://img.shields.io/static/v1?message=GitHub&logo=github&labelColor=gray&color=green&logoColor=white&label=%20)]() [![LiveLib](https://img.shields.io/static/v1?message=LiveLib&logo=libreoffice&labelColor=gray&color=53BDFB&logoColor=white&label=%20)]() [![YouTube](https://img.shields.io/static/v1?message=YouTube&logo=youtube&labelColor=gray&color=red&logoColor=white&label=%20)]()
```
4. In the editor preview you will see the badges on one line (as expected):
![image](https://user-images.githubusercontent.com/24222426/101272985-4a8e4700-37a2-11eb-8f83-ac9d2503c176.png)
5. Publish the post and see the result:
![image](https://user-images.githubusercontent.com/24222426/101273118-c9d04a80-37a3-11eb-9a77-b30f0b9e7bed.png)
Badges are placed under each other

**Why do you consider this to be a bug?**
1. Other services using markdown put badges on one line in this case
2. The editor preview is different from the final result

**What did you expect to happen instead?**
All badges on one line, just like the editor preview

### Technical details:

* Ghost Version: 3.39.0 (Ubuntu 20.04.1 LTS)
* Node Version: v12.20.0
* Browser/OS: Mozilla Firefox 83.0 (64-bit) / Windows 10
* Database: MySQL 8.0.22

**Comment by GenZmeY** [comment]
Uh, I'm sorry but I didn't think to check it out with different themes right away

Looks like this is a casper theme issue (I tried the theme [Massively](https://github.com/TryGhost/Massively) and everything is displayed correctly)

Should I close this issue and open the same one in the [casper repository](https://github.com/TryGhost/Casper)?

**Comment by naz** [comment]
@GenZmeY yes, please reopen in theme repositories you think are appropriate for this issue.
