### ISSUE TITLE
subdirectory not appearing in users profile_image

### ISSUE THREAD

**Issue by Rafael17** [TryGhost/Ghost#12464]
### Issue Summary

If site `url` variable in .env has a subdirectory, then user's `profile_image` lacks that subdirectory in its path. This bug also appears in the Admin. 

### To Reproduce

1. Set `url="http://localhost:2368/subdirectory-name"` in .env file
2. Upload a profile image for a user

`profile_image` url should be: `/subdirectory-name/content/images/img.jpg`
But currently it is: `/content/images/img.jpg`

### Technical details:

Ghost Version: 3.36.0
Node Version: 12.18.0
Database: MySQL & SQLite

**Comment by matthanley** [comment]
Hey @Rafael17 👋  I'm unable to reproduce this locally - could you confirm this is still an issue in the latest release and provide the config you're using?

**Comment by vikaspotluri123** [comment]
@Rafael17 what `.env` file are you referring to? The syntax you're using suggests you're referencing dotenv which Ghost doesn't use. Are you updating the URL in `config.development.json`?

**Comment by ErisDS** [comment]
This sounds like an issue with your environment rather than with Ghost. Please raise a topic on the forum if you still need help
