### ISSUE TITLE
Entering Japanese text via Mac into Ghost's post editor is hard to use

### ISSUE THREAD

**Issue by goralight** [TryGhost/Ghost#12497]
### Issue Summary

When using Ghost's post editor to input Japanese on a Mac (using its built in Kana input on the mac), Ghost's input try's to take over instead of letting the input of the Japanese to finish

### To Reproduce

1. Go to Ghost's page editor
2. click onto a new section to begin typing
3. make sure you have Japanese input on
4. type in a Kana character which is two english letters in sound (は、わ、て、せ, etc)
5. notice how it will accept the first letter as English instead of letting the Mac finish its input

Simply just using the post editor is very clunky when trying to input Japanese. For the time being Im having to use the Markdown block to make it easier to input the text.

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

### Technical details:

* Ghost Version: 3.35.4
* Node Version: 12.10.0
* Browser/OS: Vivaldi & Chrome / MacOS
* Database: /

### Note
I know the steps to reproduce are a bit vague, if it is easier, I can make a video of the bug and share it with you.

**Comment by specialsnowyowl** [comment]
This issue is resolved in [v3.38.3](https://github.com/TryGhost/Ghost/issues/12268). Try updating your Ghost to the latest version.

**Comment by goralight** [comment]
Ah, Really sorry about that!
