### ISSUE TITLE
Filesystem errors cause active theme to be deleted

### ISSUE THREAD

**Issue by allouis** [TryGhost/Ghost#12506]
### Issue Summary

When uploading a new version of the active theme, an error when copying the theme to the `content/themes` directory can cause the operation to fail, removing the existing theme - resulting in an invalid state for Ghost.

### To Reproduce

1. Upload a theme to Ghost (e.g. Lyra)
2. Modify this line https://github.com/TryGhost/Ghost/blob/3.40.3/core/frontend/services/themes/storage.js#L65 to `throw` an error
3. Restart Ghost
4. Upload the same theme to Ghost
5. Check the `content/themes` directory to see the active theme is missing
6. Load the frontend to see handlebars errors

### Expectation

If anything goes wrong during a theme upload, the filesystem and active theme should be in the same state as before the upload was initiated.

### Technical details:

* Ghost Version: 3.40.3

**Comment by matthanley** [comment]
Refs Cycle 1 pitch for Publishing
