### ISSUE TITLE
Editor: Images flicker/reload when Ctrl-Z Undo'ing

### ISSUE THREAD

**Issue by mhansen** [TryGhost/Ghost#12511]
### Issue Summary

Editor: Images flicker/reload when Ctrl-Z Undo'ing

### To Reproduce

1. Write some text
2. Add an image or a few images
3. Edit some text
4. Press Ctrl-Z to undo

### Expected
Text edit is undone, nothing else jumps around on the screen.

### Actual
Text edit is undone, and often (but not every time), the images flicker on/off: it seems like they're reloading. While they're reloading, the page re-layouts: text jumps up and down as the images disappear then reappear.

### Technical details:

* Ghost Version: whatever's in prod right now
* Node Version: whatever's in prod right now
* Browser/OS: macOS, Chrome and Safari both experience this
* Database: whatever's in prod right now

**Comment by aidenmitchell** [comment]
BTW "whatever's in prod right now" changes a lot, so I'd recommend adding version numbers.

**Comment by mhansen** [comment]
Not sure how to find what version of node ghost.io is running.

It's been happening for about a year so shouldn't be too hard to repro.
