### ISSUE TITLE
Admin interface is making lots of requests to many foreign domains

### ISSUE THREAD

**Issue by eauchat** [TryGhost/Ghost#12520]
### Issue Summary

I don't want to pollute ghost issue tracker, maybe this refers to a feature not a bug, so feel free to close the issue if you find it inappropriate.

I noticed using the ghost administrative interface that after some usage of it, my browser had made requests to the following domains:
```
mydomain.tld <= the domain on which ghost is installed
bootstrapcdn.com / maxcdn.bootstrapcdn.com
cloudflare.net
ghost.io / mainframe.ghost.io
ghost.org / static.ghost.org
hwcdn.net
jquery.com
jsdelivr.net
```

I'm aware that most of those domains are cdn delivering code. I guess those cdn are used to speed up the ghost admin interface.
Since ghost is locally hosted, all those contents could be installed in the server and loaded from it, instead of being gotten from those cdn.
Is there a real speed gain that is worth the privacy issue of relying on external party to provide this code?
As far as I've seen, those cdn are only called from the admin interface, to enable some part of it. So it's already a great gain for site user's privacy, since it affects only administration.

Thank you for your attention, and also a huge thank you for making this great quality software, I'm discovering it and it's been a long time I was looking for such kind of tool! :heart: :heart: :heart:

### To Reproduce

Use the ghost administrative interface, for example editing a page and adding some markdown contents...

### Technical details:

* Ghost Version: 3.38.2
* Node Version: 14.15.4
* Browser/OS: Firefox/Linux

**Comment by ErisDS** [comment]
If this is something you'd like to see improved, there is a set of privacy configurations inside of Ghost that could be expanded to introduce local hosting of these files. However, as you mentioned it's not a bug so it's not an issue we'd keep open in our bug tracker.

Let us know if your interested in implementing the changes though and we can discuss it further 😄

**Comment by MattDHill** [comment]
Hi @ErisDS , we are preparing to launch Ghost on the (EmbassyOS)[https://github.com/Start9Labs/embassy-os] and would be interested in taking this on. Can we set up a time to discuss. Tagging @k0gen

**Comment by ErisDS** [comment]
@MattDHill I'm about to take some leave, but a good way to move forward in the meantime might be to put together a more detailed problem statement and fix proposal and put it either here or in the contributing section on the forum?
