### ISSUE TITLE
[newsletters] Template substitution is displaying `recipient.replacement_1` instead of first name

### ISSUE THREAD

**Issue by kamranayub** [TryGhost/Ghost#12538]
### Issue Summary

Today was the first day I tried scheduling a post using the email snippet and was aghast when I saw this in my newsletter (in the email in my inbox):

![image](https://user-images.githubusercontent.com/563819/104471781-def97f80-5580-11eb-8b19-8aaee7a89b9c.png)

😱 

I think perhaps something is wrong with the template substitution? Also a lot of my members probably don't have first names and I would expect that fallback to appear as the editor shows:

![image](https://user-images.githubusercontent.com/563819/104471761-d86b0800-5580-11eb-91b3-87bfa60e95bb.png)

### To Reproduce

1. Add email snippet to post, don't edit the template substitution
1. Schedule the post for a future date
1. Wait until the time passes and check inbox

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

I expected to see my name or "there" instead of the template syntax.

### Technical details:

* Ghost Version: 3.40.4
* Node Version: 12
* Browser/OS: Ubuntu
* Database: MySQL

**Comment by kevinansfield** [comment]
@kamranayub are you seeing `%recipient.replacement_1%` in an actual email or are you viewing it via Mailgun's "quick view"? If you're using Mailgun's quick view then it's expected to appear like that because they don't perform substitution there, in the actual email that is sent out it would be using the appropriate variable values.

I've tried to replicate the problem but have been unable to when looking at the emails that are delivered.

**Comment by kamranayub** [comment]
@kevinansfield Thanks, yes, that screenshot above is from my inbox... I've had Ghost for over a year now through multiple upgrades so I am not sure whether something is up with my database (or how to check / diagnose this). I can run through any steps if someone can provide them. Tonight I can also try upgrading to 3.40.5. I could make myself a "paid" member and try doing a test post.

**Comment by kamranayub** [comment]
I just tried using the Send Test Newsletter function and I still get the same result. I have not yet upgraded to 3.40.5 so I can try that next and report back.

![image](https://user-images.githubusercontent.com/563819/104615565-fb63ed80-564e-11eb-91ce-b48642ffa8e7.png)

Other factors:

- I've customized the footer of the newsletter with our mailing address
- My user doesn't have a first name defined
- Have upgraded from previous versions over the course of a year

**Comment by kevinansfield** [comment]
@kamranayub I'm rather stumped on this, I've tried many different ways to reproduce the problem by fuzzing intentionally "bad" data in the database and even across different node versions and mysql/sqlite.

Have you verified this problem across multiple members or is it limited to a specific member on your site?

**Comment by kevinansfield** [comment]
Also, could you verify that this particular site is definitely on 3.40.4? You can check from the about "About Ghost" link after opening the user menu in the bottom left of the admin screens.

3.35.3 did suffer from [this same issue](https://github.com/TryGhost/Ghost/issues/12257) but it was fixed in 3.35.4 and the related code hasn't changed since then.

**Comment by kamranayub** [comment]
> Also, could you verify that this particular site is definitely on 3.40.4? You can check from the about "About Ghost" link after opening the user menu in the bottom left of the admin screens.

From the admin UI, yes, that's what it says. However, if you want me to dive into `node_modules` to check a version for a package, let me know.

I still have to do the upgrade to .5 and will report back once I do that. In the worst case I suppose I may reset the installation and reinstall latest. 🤷‍♂️ Trying to avoid that since I may mess something up.

**Comment by ErisDS** [comment]
As you're the only person reporting this issue I think we should probably close it and move to the [forum](https://forum.ghost.org) to debug your environment. 

@kamranayub if you're still experiencing this issue after upgrading can you please open a forum post with all the details of your setup so we can try to help you get to the bottom of it?
