### ISSUE TITLE
404 on all images when updating to v3.14.0

### ISSUE THREAD

**Issue by Kerumen** [TryGhost/Ghost#12548]
### Issue Summary

I had a very outdated Ghost instance which was running `v3.13.3`. I tried to update it to the latest version but I had 404 on all my images. So I rolled back and wanted to upgrade version by version to find which version was causing problem. `v3.13.4` worked fine but starting from `v3.14.0` all of my images in the `content` folder were returning 404:

```
Cannot GET /content/images/2020/03/hero.jpg
```

I looked at [the diff](https://github.com/tryghost/ghost/compare/3.13.4...3.14.0) and found some changes related to serving static assets between the 2 versions but I'm not sure if it's the problem. Is it because it's a new minor? Or is it a coincidence?

If I rollback to `v3.13.4` it works again. All of my images are still in the `content` folder, it appears to be a problem with the serving only.

### To Reproduce

Upgrade from version `v3.13.4` to `v3.14.0`.

### Technical details:

* Ghost Version: `v3.13.4`
* Node Version: `v12.14.1`
* Browser/OS: Archlinux
* Database: MySQL

**Comment by Kerumen** [comment]
I think I've found the culprit: https://github.com/TryGhost/Ghost/commit/406218489c555666b3d81f5de7241eac65f39829

I forgot to mention that my admin is on a separate domain than my blog. I try to request static images from the admin URL, and it's still not working. I have my admin on `https://admin.theblog.com` and even when I directly request the image, I have a 404:

```
https://admin.theblog.com/content/images/2020/03/image.jpg
```

Even if I try to upload a new image, it gets uploaded but it's still a 404 on the request.

This is the relevant part of the Ghost config:

```
  "url": "https://theblog.com/",
  "admin": {
    "url": "https://admin.theblog.com/"
  }
```

I understand that the change can be needed and maybe I need to adapt my configuration?

**Comment by Kerumen** [comment]
Continuing my investigation, I found an easy way to reproduce the bug locally, even with the latest Ghost version:

1. Configure your `config.development.json` with these values:

```
"url": "https://www.google.com/",
"admin": {
  "url": "http://localhost:2368/"
}
```

(the blog URL can be whatever, we don't care for to reproduce the bug - it just needs to be **different** than the admin's one)

2. Run `ghost` in development with `ghost run -D` and upload a new image in a new blog post.
3. Get the image URL and replace `https://www.google.com/` with `http://localhost:2368/`.
4. Try to load the image.

The image is not served by Ghost as it should be (and was in v3.13.x).

**Comment by matthanley** [comment]
@Kerumen could you provide some information on your use-case for requesting images using the admin URL instead of the site URL?

**Comment by Kerumen** [comment]
@matthanley

I have a custom frontend with Gatsby, I can't serve the images from there. Previously I setup a redirect to serve content from `theblog.com/content` to `admin.theblog.com/content` this way I could see the images both on the blog and in the Ghost Admin. Now I can't because the admin doesn't serve the images anymore.

You can easily reproduce it with your starter repo: https://github.com/TryGhost/gatsby-starter-ghost

- Init the starter repo
- Init a new Ghost instance locally
- Run `ngrok http 8000` to proxy another domain to the Gatsby frontend
- Edit the `config.development.json` file: set the `url` field to the `ngrok` URL and the `admin.url` to `http://localhost:2368`
- Run you Ghost instance with `ghost run -D`
- Run your Gatsby frontend
- Try to upload an image in the admin
 
The URL would be `http://hash.ngrok.io/content/images/2021/01/image.png` and it would not display both on the admin and on the blog.

I'm surprised being the only one to have the problem? 🤔  Maybe my configuration is wrong?

**Comment by ErisDS** [comment]
@Kerumen you're right, I removed the code that also served images over the admin URL, however it was an internal API not something we'd documented or expected anyone to rely on. 

I think for the rest of this, it's a support issue better discussed on the forum. Standard practice with gatsby, as far as I am aware is to serve images from the frontend Ghost url (which is basically just an asset URL) not the backend. As far as I can see, it's your redirect that's the unexpected setup and means that you are (to the best of my knowledge) the only person who has run into this.

**Comment by Kerumen** [comment]
@ErisDS thanks for your reply!

My redirect was a temporary fix because it was the only way I found to serve my images.

I've fixed by removing the `admin.url` config key. Even though my admin is on a different domain, it's working now and I don't know what this key is made for.

**Comment by Kerumen** [comment]
But basically my setup is the same as you have at https://gatsby.ghost.org. Your admin is on https://gatsby.ghost.io/ghost. What's the value of `url` and `admin.url` config keys? If you are running the latest Ghost version you should have the same problem as me, no?
