### ISSUE TITLE
Improve 3rd party loaded scripts

### ISSUE THREAD

**Issue by ScottHelme** [TryGhost/Ghost#12558]
### Issue Summary

There are two scripts loaded from 3rd parties that could be improved, located in `ghost_head.js` [here](https://github.com/TryGhost/Ghost/blob/master/core/frontend/helpers/ghost_head.js#L44) and [here](https://github.com/TryGhost/Ghost/blob/master/core/frontend/helpers/ghost_head.js#L47).

Both of these scripts could be improved by adding the `crossorigin="anonymous"` attribute to them to ensure that no credentials (cookies) are sent with the requests. You can find more details about the `crossorigin` HTML attribute in the MDN docs [here](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/crossorigin#example_crossorigin_with_the_script_element). The addition of the `crossorigin="anonymous"` attribute also allows site operators the possibility to explore features like Cross-Origin-Embedder-Policy before 3rd parties, like Stripe and unpkg, enable Cross-Origin-Resource-Policy on the assets they host.

**Comment by ErisDS** [comment]
Hi @ScottHelme 👋 

Thanks for this, we'd be happy to merge a PR for this (and with GitHub's tools these days it'd prob be quicker for us both!). Any suggestions like this that make clear improvements to security are always welcome as PRs 👍 

Closing as we don't need to track it as an issue.
