### ISSUE TITLE
Ghost admin displays emails analytics despite being disabled

### ISSUE THREAD

**Issue by onurozer** [TryGhost/Ghost#12559]
### Issue Summary

_Reporting based on suggestion by @naz in https://github.com/TryGhost/Ghost/issues/12496#issuecomment-764906785_

Ghost admin displays emails received and opened under member details although `newsletter open-rate analytics` is disabled under Labs > Members. 

**Reference screenshot:**

<img width="656" alt="member-summary" src="https://user-images.githubusercontent.com/55616/105478361-617def80-5ca3-11eb-8f4e-79154530e936.png">

### Issue Details

I have exactly the same issue as others reported in #12496 - ghost crashes with an error message that seems to be related to email analytics. I turned off email analytics as soon as I discovered that ghost was crashing, shortly after the feature was originally released. 

My expectation was that the `INFO Worker for job "email-analytics-fetch-latest" exited with code 0` error in issue #12496  would go away since there would be no email analytics to fetch to begin with. However, seeing the email open and click rates in member details makes me think that the ghost is ignoring the settings in the admin panel.  

I'm on a digital ocean droplet built from the ghost image, using mailgun integration for emails without any issues. 

### Technical details:

* Ghost Version: 3.40.5
* Node Version: v12.20.1
* Browser/OS: Safari Version 14.0.2 on macOS Big Sur
* Database: mysql  Ver 14.14 Distrib 5.7.32

**Comment by ErisDS** [comment]
Hi @onurozer,

As [explained in the referenced issue](https://github.com/TryGhost/Ghost/issues/12496#issuecomment-770880113), the "newsletter open-rate analytics" checkbox only changes a flag that is set on outgoing emails sent via Mailgun's API, it does not turn on or off anything to do with workers or jobs. It also will not hide the UI. It is preventing stats being generated going forward, not historically.

As also [explained in the same issue](https://github.com/TryGhost/Ghost/issues/12496#issuecomment-773585550) there are two config options you can use to control this behaviour, one of which will hide the UI if you don't want it.

This is all as expected at the moment, not a bug.
