### ISSUE TITLE
Remove "apps" database tables

### ISSUE THREAD

**Issue by naz** [TryGhost/Ghost#12565]
refs https://github.com/TryGhost/Team/issues/221

## Context
The concept of "apps" has been removed in Ghost some time ago but there were database tables left as these would be potentially long running migrations. With a preparation of Ghost 4.0 we can add migrations which would need longer time to run. 

### Solution
Remove the tables apps, app_settings, app_fields and permissions_apps - as they are not used.
 
 - [x] drop tables (https://github.com/TryGhost/Ghost/commit/606212d18767d7ed5a61b62be7a68341224c7ed7)
 - [x] cleanup old data (https://github.com/TryGhost/Ghost/pull/12596) 
 
 
### Related
- https://github.com/TryGhost/Ghost/pull/10682

**Comment by Fhiltyphil88** [comment]
> refs https://github.com/TryGhost/Team/issues/221
> 
> 
> 
> ## Context
> 
> The concept of "apps" has been removed in Ghost some time ago but there were database tables left as these would be potentially long running migrations. With a preparation of Ghost 4.0 we can add migrations which would need longer time to run. 
> 
> 
> 
> ### Solution
> 
> Remove the tables apps, app_settings, app_fields and permissions_apps - as they are not used.
> 
>  
> 
> ### Related
> 
> - https://github.com/TryGhost/Ghost/pull/10682

**Comment by naz** [comment]
The https://github.com/TryGhost/Ghost/pull/12596 landed in master, which was last bit needed for full cleanup.
