### ISSUE TITLE
Rename cookie for private site mode

### ISSUE THREAD

**Issue by naz** [TryGhost/Ghost#12564]
refs https://github.com/TryGhost/Team/issues/221

## Context
At the moment the cookie that controls "private" site mode is set to [a  default name](https://github.com/expressjs/cookie-session/tree/1.x#name): `express:sess`. This creates multiple problems: (1) with the version bump to cookie-session v2 the default name will change to `session`, possibly breaking any infrastructure using current default cookie name; (2) it is hard to identify Ghost cookies in the storage with default naming.

### Solution
The cookie should be named following a convention used for other cookies starting with `ghost-` prefix, e.g: [ghost-members-ssr](https://github.com/TryGhost/Ghost/blob/01126cf1bb6113cb46dc3478fd22cbd34f512bba/core/server/services/members/index.js#L90).

Final name for the cookie should be: `ghost-private`

Note, there is an [open bug report](https://github.com/TryGhost/Ghost/issues/12173) that has to do to this cookie. While on the topic it's worth giving it a look.

**Comment by tpatel** [comment]
The [open bug report](https://github.com/TryGhost/Ghost/issues/12173) is solved after discussing with Kevin and Hannah, it has been closed as won't fix.
