### ISSUE TITLE
Documentation content missing: "Building a custom front-end for Ghost"

### ISSUE THREAD

**Issue by jonathanarbely** [TryGhost/Ghost#12584]
### Issue Summary

Documentation content missing: "Building a custom front-end for Ghost". [Opening the page](https://ghost.org/docs/jamstack/custom) returns no content, only the header.

### Technical details:

* Tested on latest Chrome/Safari on macOS 11.1

**Comment by ErisDS** [comment]
Thanks for letting us know.
