### ISSUE TITLE
Add background and pricing parameter support to portal preview

### ISSUE THREAD

**Issue by kevinansfield** [TryGhost/Ghost#12594]
The new launch-site wizard uses the portal preview when configuring subscription pricing to give a live indication of how pricing changes affect the signup screen in-situ on the site. To do this there are additional query parameters that the preview needs to listen to:

- `currency` - lowercase currency value such as `gbp` or `usd`
- `monthlyPrice` - integer
- `yearlyPrice` - integer
- `disableBackground` - boolean to turn off the overlay added by the preview, set to `true` when the theme should be visible behind the subscription popup

**Comment by rishabhgrg** [comment]
Closed with https://github.com/TryGhost/Portal/commit/12c921a66e2ab3137b5d56e555cfe18e45965077 and release of `portal@1.0.0-rc.3`
