### ISSUE TITLE
Bookmark Cards Can Cause Security Warning

### ISSUE THREAD

**Issue by willkramer** [TryGhost/Ghost#12590]
### Issue Summary

Bookmark cards aren't defaulting to HTTPS for the img src tag. This may cause browsers to give a security warning like: "Parts of this page are not secure (such as images)."

### To Reproduce

1. Create a new post and insert a bookmark card for a Squarespace hosted website
    * The site that produced this issue for me is https://www.theblinkdate.com/
2. The published post will use http:// for the bookmark card img src.

The image src tag should be relative and use // instead of hard coding http or https. Squarespace's CDN supports https and redirects all http request to https.

### Technical details:

* Ghost Version: 3.38.3 
* Node Version: 12.18.0
* Browser/OS: Firefox 84.0.2 on macOS Catalina
* Database: MySQL

**Comment by ErisDS** [comment]
This is a duplicate of https://github.com/TryGhost/Ghost/issues/11870 - TLDR the bug lies with Squarespace, not Ghost.

**Comment by willkramer** [comment]
@ErisDS, I'm not too familiar with how the Ghost cards are created; so I apologize if my question below is obvious.

When I look at the problematic post  in the posts table in the MySQL database, I see that it the post html was inserted with the img src being "http://static1.squarespace.com/static/..."

I modified the html column for that post so the img src was "//static1.squarespace.com/static/..." and it fixed the security warning.

Would a possible solution be to search post content for any "http://" references  in src tags and replace it with protocol relative URLs before inserting into the database?

**Comment by ErisDS** [comment]
Please refer to & use the original issue - duplicates create huge overhead for us as maintainers.
