### ISSUE TITLE
Feature: Article history/revisions

### ISSUE THREAD

**Issue by wedneyyuri** [TryGhost/Ghost#12609]
This feature was previously discussed [in the forum](https://forum.ghost.org/t/article-history-revisions/2892).

We are currently creating (and modifying) posts on another service and we want to send creations (and updates) through Zapier. A part of the content is written in the first service and we use Ghost to finalize the post before publishing (adding images, title, subtitle, tags, canonical, …).

For content creation, what already exists is sufficient. We send the posts in draft mode and make the necessary changes before publishing. However, after the content update process in the first tool, we cannot directly publish the content in production before completing the content. Publishing as draft mode is also not an option as this would take the current article down.

I believe that we can add an option to work on articles (which are already published) without reflecting the change in production after saving changes (something similar to Medium). In this case, instead of Zapier publishing directly for production, he would be sending a new “history revision” of the article for editing.

What do you think? Can I develop this on top of Ghost@3? Is it interesting for you to add this functionality?

**Comment by ErisDS** [comment]
Hi @wedneyyuri thanks for this! I've sent you a DM about it so that we can try to move it forward. In the meantime the issue will be closed here on GitHub.
