### ISSUE TITLE
member unsubscribing from newsletter erases their membership labels

### ISSUE THREAD

**Issue by os72** [TryGhost/Ghost#12600]
member unsubscribing from newsletter erases their membership labels
ghost 3.40.5

apply label(s) to a member and have them unsubscribe from newsletter (by clicking on link in newsletter email, didn't test via portal)

-> label(s) have disappeared

**Comment by matthanley** [comment]
I've reproduced this issue to confirm it. @os72 in future please use the issue template provided. Thanks!

**Comment by daniellockyer** [comment]
Hey @os72! 👋🏻 We've just released 3.41.4 which contains the fix for this, so please update with Ghost-CLI 🙂

**Comment by os72** [comment]
Thanks! I use a managed service so they control the upgrades. But I report whatever I find as a user :)
