### ISSUE TITLE
Portal login does not show an error when the incorrect email is used

### ISSUE THREAD

**Issue by KiraLT** [TryGhost/Ghost#12607]
### Issue Summary

Portal login does not show an error when the incorrect email is used. Users always get a `We've sent you a login link!` message instead of an error message. 

### To Reproduce

1. Open portal login popup
2. Type incorrect email and press `Continue`
3. You get `We've sent you a login link!` text instead of an error.

When a user mistypes an email, he still gets a `We've sent you a login link!` message during the login process. Then he is confused why he doesn't get an email. It should display `Incorrect email` or a similar error.

The issue is in [TryGhost/Members](https://github.com/TryGhost/Members/blob/master/packages/members-api/lib/controllers/router/index.js#L318) package, where is a check if the user email is valid, but do nothing otherwise.

I have already received complaints from users about not getting emails (when they mistyped). Some users may try entering email again, but it's still a bad user experience. 

P.S. I am not sure if this is a bug or feature. It could be intended security behavior to prevent guessing emails (if that is the case, maybe you should add a comment there).

### Technical details:

* Ghost Version: 3.41.3
* Node Version: 12
* Browser/OS:  Chrome, Fedora
* Database: Mysql

**Comment by matthanley** [comment]
Hey @KiraLT! This is intended behaviour for the reason you mentioned:
> It could be intended security behavior to prevent guessing emails

**Comment by KiraLT** [comment]
Thank you for the reply, that makes sense. I checked slack (it also has magic link support), and it has a much better message. It would improve UX if the message would include an email address and a phrase like:  `Wrong email address? Please re-enter the email address.`

![Screenshot from 2021-02-10 17-17-27](https://user-images.githubusercontent.com/10944908/107530292-66f49880-6bc4-11eb-94c6-632d498dca90.png)

**Comment by matthanley** [comment]
Hey @KiraLT - feel free to submit a PR with the change for consideration 😃
