### ISSUE TITLE
Missing Filter for Posts

### ISSUE THREAD

**Issue by rickdonato** [TryGhost/Ghost#12630]
Within 3.41.2 the filter for showing the level of access for a post is gone.
Within 3.40.4 you can see the filter, as shown below:
![image](https://user-images.githubusercontent.com/4304301/107419411-aca35980-6b0f-11eb-8d08-f9ced50c0355.png)

Thanks,

**Comment by ErisDS** [comment]
Hi @rickdonato when you filled out your issue there was a template with the details we ask for, please do not delete it.

I don't have enough information here, and I cannot reproduce your issue. 

Please update the issue with reproduction steps and the full details of your environment.

**Comment by ErisDS** [comment]
Closing this for now as there's nothing we can do - we can reopen if/when more information is provided.
