### ISSUE TITLE
Update mobiledoc/markdown rendering for 4.0

### ISSUE THREAD

**Issue by kevinansfield** [TryGhost/Ghost#12646]
We want the ability to make changes in our rendered HTML output without breaking old content. An example of such a change in 4.0 will be modifying header elements' `id` attribute value to better serve non-English languages. If we were to make that change without considering old content then any time old content is re-rendered (through editing old posts, or forced re-render in a major upgrade) then deep-links could break from `id` attributes adopting the newer scheme.

By introducing the concept of "Ghost version" to our mobiledoc (separate to the underlying mobiledoc spec version) we can use it in our card renderers and post-render modifiers to change the output in new content without breaking the old.

We also want to remove the outdated/deprecated markdown card alias (Ghost 1.0 had a different name for markdown cards) and the custom card-only version that was added to facilitate adding the 1.0 wrapper element. This is a cleanup task.

- [x] Test `mobiledoc-kit` and `mobiledoc-dom-renderer` to make sure there are no problems adding top-level properties to mobiledoc documents
- [x] Decide on versioning scheme
    - tied to Ghost major or separate so we can modify HTML output without breaking changes outside of major releases?
- [x] Migration to modify mobiledoc of all posts
  - [x] add a `ghostVersion` property to mobiledoc of all posts
  - [x] change markdown card names from `card-markdown` to `markdown` (cleanup of 1.0 content)
- [x] Ensure newer `ghostVersion` is set for all newly created mobiledoc (Ghost + Admin)
  - the alternative would be setting the version at time of publication _but_ we run into potential problems there with content being unpublished and republished for any reason (send as email, force automations to run, etc)
- [x] Remove card-markdown card alias in `kg-default-cards`
- [x] Remove handling of `cardOptions.version` that is no longer used
- [x] Update mobiledoc renderers to use top-level `ghostVersion`
- [x] Update header id generation to use a less destructive algorithm (closes https://github.com/TryGhost/Ghost/issues/9740)
  - [x] [Top-level DOM modifier](https://github.com/TryGhost/Koenig/blob/master/packages/kg-mobiledoc-html-renderer/lib/mobiledoc-html-renderer.js#L34-L55)
  - [x] [Markdown renderer](https://github.com/TryGhost/Koenig/blob/master/packages/kg-markdown-html-renderer/lib/markdown-html-renderer.js#L11-L20)

**Comment by kevinansfield** [comment]
> Test mobiledoc-kit and mobiledoc-dom-renderer to make sure there are no problems adding top-level properties to mobiledoc documents

`mobiledoc-kit` uses an internal linked-list representation of document contents when editing and will not preserve any top-level properties through the `deserialise->{internal representation}->serialise` process used when working on the mobiledoc document format. This is fairly straightforward for us to work around by persisting our custom top-level properties from the supplied mobiledoc through to the updated mobiledoc each time a change occurs in https://github.com/TryGhost/Admin/blob/main/lib/koenig-editor/addon/components/koenig-editor.js#L739-L740

**Comment by kevinansfield** [comment]
> tied to Ghost major or separate so we can modify HTML output without breaking changes outside of major releases?

Tied to Ghost versions but with `{major}.{minor}`. All existing content will have `ghostVersion: '3.0'`, newly created content will have `ghostVersion: '4.0'`. If at some point in the future we want to introduce other changes we have the possibility of using `ghostVersion: '4.x'` where `x` matches Ghost's minor version without needing to wait for a full major release.

**Comment by ErisDS** [comment]
This is super cool 😎

**Comment by kevinansfield** [comment]
For the heading IDs there are various options but they depend on what our intended use-case is for changing them:

1. Avoiding URL escaping - Translate chars into ascii equivalents to get "nicer" urls in source code and non-browser environments. We could target a subset of chars such as converting `ãàáäâåčçďẽèéëêìíïîñõòóöôřšťùúüûýž` to `aaaaaaccdeeeeeiiiinooooorstuuuuyz` but the list will always be incomplete and won't cover all languages (it [wouldn't help Russian](https://github.com/TryGhost/Koenig/pull/72) or logogram based languages for example).
    1.  Alternative is to use the same algorithm we use to [convert post titles to slugs](https://github.com/TryGhost/SDK/blob/master/packages/string/lib/slugify.js) which is a lot more complex and uses an unmaintained library (unidecode). We also have regular requests to disable that auto-translation so we'd be back in the same situation at some point.
2. Maximum language compatibility - URL encode everything after stripping special chars. Anchors in source code or when copy/pasted will look more complicated, eg `Tésting` would have an id of `t%C3%A9sting` but browsers will show `#tésting` in the URL bar when linked to and the same in the status bar when a link is hovered.

For now I'm opting for approach 2 as it maintains the original text and I'm not aware of any downside other than more complex URLs when copy/pasting deep links.

**Comment by kevinansfield** [comment]
Closing as all aspects of this issue have landed in the respective repositories.

**Comment by meleu** [comment]
This is awesome! Many thanks for that! :heart:

Do you know if it's already available if I do a fresh `ghost-cli` install?

**Comment by kevinansfield** [comment]
@meleu it's not available to install yet, it will be in the Ghost 4.0 release.
