### ISSUE TITLE
Discrepancies in time fields precision between Admin API responses and Webhook requests for Posts

### ISSUE THREAD

**Issue by rozhok** [TryGhost/Ghost#12762]
### Issue Summary

Time values in `updated_at` field and other time fields are different between API responses and Webhook requests.
API response nullifies milliseconds while Webhook request includes milliseconds.

Example API response:
```
{
  "posts": [
    {
      "uuid": "39c42a38-5c4a-4405-981f-ff3f84b86568",
      "created_at": "2021-03-14T15:02:26.000Z",
      "updated_at": "2021-03-14T15:02:26.000Z",
      "published_at": "2021-03-14T15:02:26.000Z",
```

"Post published" Webhook request for this post:
```
{
  "posts": [
    {
      "uuid": "39c42a38-5c4a-4405-981f-ff3f84b86568",
      "created_at": "2021-03-14T15:02:26.033Z",
      "updated_at": "2021-03-14T15:02:26.033Z",
      "published_at": "2021-03-14T15:02:26.034Z",
```

You can see milliseconds included into latter request but missing in former. I've encountered this issue during writing sync engine to replicate posts between Ghost and other sources. Since I use same server for updating Ghost and receiving webhooks, I use `updated_at` field do determine if post was edited by my system or by user.

### To Reproduce

1. Create POST via admin API. 
2. Receive webhook for created post.
3. Notice difference in milliseconds.

Excepted result: datetime fields are exactly same.

### Technical details:

* Ghost Version: 3.41.3
* Node Version: v12.19.0
* Browser/OS: Linux
* Database: SQLite

**Comment by ErisDS** [comment]
Thanks for the report! I can see why that would be an issue. 

We'll try to take a look at this soon but in the meantime a PR would be welcome!
