### ISSUE TITLE
Whitespace between tags is not considered as part of markup when publishing HTML content via Admin API

### ISSUE THREAD

**Issue by rozhok** [TryGhost/Ghost#12769]
### Issue Summary

When creating post via Ghost Admin API, empty space between tags is stripped to zero.

### To Reproduce

1. Submit `spaces are good <b>test</b> <b>test</b>` as HTML content to Ghost Admin API:
```json
{
	"posts": [
		{
			"title": "test",
			"html": "spaces are good <b>test</b> <b>test</b>",
			"status": "draft"
		}
	]
}
```
2. Look at the post created

Excepted result:
Post text is "spaces are good **test** **test**"

Actual result:
Post text is "spaces are good **testtest**"

3. Submit `spaces are good <b>test</b> middle <b>test</b>` as HTML content to Ghost Admin API:
```json
{
	"posts": [
		{
			"title": "test",
			"html": "spaces are good <b>test</b> middle <b>test</b>",
			"status": "draft"
		}
	]
}
```
4. Look at the post created.

Excepted result:
Post text is "spaces are good **test** middle **test**"

Actual result:
Post text is "spaces are good **test** middle **test**"

Everything is fine.

### Technical details:

* Ghost Version: 3.41.3
* Node Version: v12.19.0
* Browser/OS: Linux
* Database: SQLite

**Comment by kevinansfield** [comment]
This is a bug in the upstream [mobiledoc-kit](https://github.com/bustle/mobiledoc-kit) library. As a workaround you can wrap your contents in a `<p>` tag or other container element, that way each text node and element is not treated as a top-level node and spacing is preserved.

**Comment by ErisDS** [comment]
Although it would be good if the upstream library handled this, IMO this is expected from Ghost's perspective.

From our docs:

> the conversion generates the best available mobiledoc representation, meaning this operation is lossy and the HTML rendered by Ghost may be different from the source HTML.

IMO it's not unreasonable that the conversion needs HTML content to be well-formed, and contain some sort of block-level element such as a `<p>`, `<div>`, `<blockquote>` etc. 

I have updated the docs to include additional clarification around expectations, and I think that's all that's needed here:

> For the best results ensure your HTML is well-formed, e.g. uses block and inline elements correctly.

**Comment by rozhok** [comment]
Wrapping content into a `<div>` helped, thanks!
