### ISSUE TITLE
Dark mode "Preview in browser" link has background color

### ISSUE THREAD

**Issue by stromfeldt** [TryGhost/Ghost#12767]
### Issue Summary

Although the dark mode "Preview" link under "Post settings" appears as green on a transparent background, the "Preview in browser" link under "Email newsletter" settings appears as green on a shaded background. It also has a shaded hover color.

<img width="353" alt="Screen Shot 2021-03-16 at 11 53 50 am" src="https://user-images.githubusercontent.com/27488257/111247004-646dde80-865b-11eb-8e58-ab8672a70d42.png">

Versus:

<img width="353" alt="Screen Shot 2021-03-16 at 11 53 33 am" src="https://user-images.githubusercontent.com/27488257/111247044-7059a080-865b-11eb-8182-1bc82149b2a0.png">

Apologies as although I'd fix it myself I haven't faintest idea around the file setup, nor would I know how to compile and thus test it all if I even found the relevant file(s).

### Technical details:

* Ghost Version: 4.0.0
* Browser/OS: Firefox, Chrome

**Comment by iamsanteri** [comment]
I'm not sure if this is the case for others, but since upgrading to Ghost V4 in dark mode, also the links cannot be seen in my previous posts. See picture below: 

Light mode: 
<img width="768" alt="Screenshot 2021-03-16 at 12 24 27" src="https://user-images.githubusercontent.com/11017096/111301558-a6deed80-8652-11eb-9eab-a855d2ad3eab.png">

Dark mode:

**Comment by stromfeldt** [comment]
@iamsanteri From what I've just noticed, the color used for links and such in the editor is the same color as the accent color set up on the Branding settings page. I presume your branding color is close to the #151719 background color used in the dark mode editor, and that for stylistic reasons you wouldn't want to switch away from that color. As your issue is a a different issue from this one that I opened up you should probably open up a separate issue.

**Comment by iamsanteri** [comment]
@stromfeldt this was it, thank you! And now it's also fixed by the team.
