### ISSUE TITLE
Use class fluid-width-video-container for more embedds

### ISSUE THREAD

**Issue by akoyaxd** [TryGhost/Ghost#12763]
### Issue Summary
The Class fluid-width-video-container is only used for some whitelisted Services like Youtube. I'd like to embed some Videos from my PeerTube Instance or [Odysee](odysee.com). But Videos from those sites are embedded with the "kg-card kg-embed-card" class, which does not properly size the Video, on Desktop it's to small and on mobile it is too large.

### To Reproduce
1. Install Ghost, with default theme
2. Create a New Post
3. Paste the link of a YouTube Video
4. Paste the link of a Odysee / Newpipe Video.
5. Look at the Preview from the Post

Now you see, they are sized differently and use different classes (use the debug tools from your browser):

**YouTube:**
`class="fluid-width-video-container"`

**Odysee:**
`class="kg-card kg-embed-card"`

In the Post editor they are sized correctly.

### Workaround
Adding custom html and enforcing the embed with the correct class works
`<div class="fluid-width-video-container"><div class="fluid-width-video-wrapper" style="padding-top: 56.1798%;"><iframe src="https://tube.example.com/videos/embed/7d2d935c-1218-4149-900f-2d6261272db3" frameborder="0" allowfullscreen></iframe></div></div>`

But with this workaround they are not correctly shown in the Newsletter E-Mail.

**Comment by kevinansfield** [comment]
@akoyaxd this is a theme-level concern, Ghost itself doesn't have any whitelist to generate different output for different embeds. You can see the related JS in Casper here https://github.com/TryGhost/Casper/blob/main/assets/js/lib/jquery.fitvids.js - you can modify that or use a different library in your theme to cater for your specific needs.

**Comment by ErisDS** [comment]
Thanks for the explanation @kevinansfield
