### ISSUE TITLE
Scrolling glitch in post editor on iOS

### ISSUE THREAD

**Issue by JBYoshi** [TryGhost/Ghost#12801]
### Issue Summary

The scrolling behavior in the post editor on iOS Safari feels inconsistent. It seems that Safari thinks there are two scrollable areas in the post editor, one inside the other.

### To Reproduce

1. Open a post in the admin client that takes up at least two screens worth of content.
2. Flick up on the screen to scroll as far down as Safari will let you until the screen bounces at the end. Notice the last three lines or so are covered up, along with the word count.
3. Pause for a few seconds and swipe up again. The screen will slide up the rest of the way, and a second scroll bar will briefly appear on top of the first. Also notice that the top bar has now disappeared.
4. Flick-scroll back to the top of the page. Notice that the scroll bar bounces before reaching the top with the title. To see the title, you need to pause and scroll up again.

I'd expect to be able to scroll from the top to the bottom without having to pause in the middle of scrolling. Having to wait in the middle feels awkward and unnatural.

### Technical details:

* Ghost Version: 4.1.0
* Node Version: 12.21.0
* Browser/OS: Safari iOS 14.4.1
* Database: MySQL 8.0.23-0ubuntu0.20.04.1

**Comment by JBYoshi** [comment]
Still happens on Ghost 4.8.3 / Safari iOS 14.6.

**Comment by concentrateddon** [comment]
Not experiencing this on iPadOS 15 beta 4.
