### ISSUE TITLE
Email Settings Only Visible By Site Owner

### ISSUE THREAD

**Issue by joehand** [TryGhost/Ghost#12822]
### Issue Summary

The Email Settings and Newsletter design area is only available to Site Owners but is linked in the dashboard for non-owners leading to a blank page. See [more details here](https://forum.ghost.org/t/settings-email-newsletter-showing-blank-page/20904/7).

_Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?_

* (**_Preference_**) Site administrators should be able to access email settings area.
* **OR** Email Settings link should be removed from dashboard for all non-owners.

### Technical details:

* Ghost Version: 4.x
* Node Version: 12.x

**Comment by joehand** [comment]
Is there any way to get this bug addressed?

**Comment by ErisDS** [comment]
This has been fixed along with a few other cases. We're also conducting an internal review of how we manage permissions across the codebase so that this can't happen again. Thanks for bearing with us.
