### ISSUE TITLE
Unable to set "Page URL" to desired value - UI seems to replace /'s with -'s

### ISSUE THREAD

**Issue by a-c-m** [TryGhost/Ghost#12824]
### Issue Summary

Using the latest (4.1.2) version, when editing a page or post, setting the "Page URL" in the UI does not save correctly. 

Say I wanted to create a page with the URL "p/testing", the slug is translated, client side, to "p-testing" before its submitted to the API.

### To Reproduce

1. create a page
2. Set a custom Page URL containing a /
3. Save
4. Visit the page

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

### Technical details:

* Ghost Version: 4.1.2
* Node Version: v12.14.1
* Browser/OS: Firefox/OSx/87.0 64-bit
* Database: sqlite3

**Comment by ErisDS** [comment]
This is not a bug, it is expected behaviour at present. Ghost does not support nested slugs for pages.

If you want to have complex routes you need to use the dynamic routing feature. For support with that feature please use https://forum.ghost.org.

**Comment by a-c-m** [comment]
Odd, but fine. The preview in the UI is showing nested slugs (and no error/warning/info) - which to me feels like a UI bug if nothing else.
