### ISSUE TITLE
Remove portal code from site when not used

### ISSUE THREAD

**Issue by Bammede** [TryGhost/Ghost#12835]
```
<script defer src="https://unpkg.com/@tryghost/portal@~1.0.0/umd/portal.min.js" ....></script><style> .gh-post-upgrade-cta-content ...
```
I do not use Portal feature as my theme has its own membership sites. After I disabled the Portal feature in Ghost Admin, there should be no Portal code inserted to the site anymore.

Why load scripts and styles even the feature is not used?

**Comment by ErisDS** [comment]
See: https://github.com/TryGhost/Ghost/issues/12793#issuecomment-803540358

If you are using membership features, then you are using the portal script, regardless of whether you use its UI or your own.

**Comment by Louvki** [comment]
This is ridiculous. The script is crashing my pagespeed insights 
![Uploading image.png…]()

**Comment by ErisDS** [comment]
Putting this here for discoverability:

If you want to load a different portal.min.js file you can do so by modifying your Ghost config.environment.json file.

The default config is:

```
"portal": {
        "url": "https://unpkg.com/@tryghost/portal@~1.1.0/umd/portal.min.js",
        "version": "~1.1.0"
    }
```

You can add this to your config.environment.json to change it if you want to load locally or a forked version or remove the URL

Again though, I stress, the script is used for theme-based Members features, not just portal and so it's in use more than people realise.
