### ISSUE TITLE
Code Injection highlighting issues in dark mode

### ISSUE THREAD

**Issue by jessehouwing** [TryGhost/Ghost#12831]
As requested: https://github.com/TryGhost/Casper/issues/789#issuecomment-811649867

## Admin panel:

In the admin panel, the code highlights render some keywords black on black:

Dark-mode:
![image](https://user-images.githubusercontent.com/4173387/113016037-61f0a600-917e-11eb-8334-e2e4668c0d16.png)

Light-mode:
![image](https://user-images.githubusercontent.com/4173387/113016116-7339b280-917e-11eb-9b1a-d5685f52996f.png)

**Comment by dm17** [comment]
Same here; on the login screen for ghost it is blinding white regardless of which force dark mode extension I use.

**Comment by stromfeldt** [comment]
Is this not a duplicate of [#12774](https://github.com/TryGhost/Ghost/issues/12774)?
