### ISSUE TITLE
Need to update the username

### ISSUE THREAD

**Issue by hzb** [TryGhost/Ghost#12833]
As a person who highly recommends ghost, recommend some friends to use it and buy themes, in a way, I am helping to build ghost and build an ecosystem.

And I ask for help to update the username to hzb on this issue(https://github.com/TryGhost/Ghost/issues/12832#issue-849531118).

I also emailed you to explain the situation, why didn't you update it for me? @ErisDS

**Comment by iBotPeaches** [comment]
You are pinging people like crazy. Emailing the staff? Opening multiple tickets n over. All over an outdated username from a bot (machine). What is the concern here? I'm almost tempted to just post the old username again, but that would be pretty petty so I won't.

I can't pretend to understand this.

**Comment by hzb** [comment]
@iBotPeaches 

Before I submit the issue that I need to update the username, I try to email her public mailbox shown on GitHub and asked for help and explained the reason. Is this wrong?

Of course, she has reasons to not reply to my email, that's ok. But at least she replied to me under the issue that she doesn't want to or could not do so, instead of just closing my issue and not saying anything. 

Am I too crazy or you guys are too self-righteous?  BTW, if you don't understand why I need to update the username on that issue, you can contact me and I will tell why.
