### ISSUE TITLE
Font family not support unicode

### ISSUE THREAD

**Issue by dangviettuan** [TryGhost/Ghost#12857]
### Issue Summary

Font family in Editor (georgia) not support Unicode

### To Reproduce

1. Create a new post
2. Type string with Unicode characters
![IMG_20210413_003654](https://user-images.githubusercontent.com/11323132/114437197-6c845400-9bf0-11eb-8ee9-9ab6570e68b8.jpg)

### Technical details:

* Ghost Version: 4.1.2
* Node Version:
* Browser/OS:
* Database:

**Comment by viettranx** [comment]
Fork về sửa luôn bạn ơi, hoặc sống chung với lũ thôi :)). Bọn nó ko có thèm coi issue trên này đâu :))

Fork to modify the font in admin. The issue just happen on admin site, not client site. BTW, Ghost engineers are not working on Github issue, use their form instead.
