### ISSUE TITLE
Disable Gravatar Feature Not Working

### ISSUE THREAD

**Issue by rkafp** [TryGhost/Ghost#12860]
### Issue Summary

When trying to disable the Gravatar feature by using "useGravatar": false it doesn't work.

### To Reproduce

1. Open config.production.json
2. Add this line

```
"privacy": {
     "useGravatar": false
}
```

3. ghost restart

### Technical details:

* Ghost Version: 4.2.0
* Node Version: 12.2.1
* Browser/OS: Ubuntu
* Database: MySQL

**Comment by ErisDS** [comment]
Please provide more information about what isn't working how you would expect.

**Comment by ErisDS** [comment]
Closing now as there's not enough info here.
