### ISSUE TITLE
No Alt Tag for Site Logo Image in E-mail Newsletter

### ISSUE THREAD

**Issue by rub-a-dub-dub** [TryGhost/Ghost#12871]
### Issue Summary

A user reported an issue with my newsletter getting stuck in her spam inbox. After some investigation with mail-tester.com, I was able to determine the root cause but also discovered that the lack of an `alt` property on the `img` tag for the logo was dinging the newsletter score by 0.5. 

This seems like a small fix (`/var/www/ghost/current/core/server/services/mega/template.js`) and also seems like it would help in non-image and screenreader environments.

### To Reproduce

1. Visit mail-tester.com and get a testing e-mail address auto-generated
2. In a separate tab/window, create a draft post (or reuse an existing one)
3. Hit `Preview` and select the email tab
4. Enter the auto-generated e-mail address into the `Send a test newsletter` field
5. Hit Send
6. Return to the mail-tester.com tab/window and wait until they receive the message
7. Review the results and you'll notice under "Message Body" there is a section for "images without an alt attribute" that has a negative score attached. (Note my settings are localised in French so the English translation may be somewhat different). See below for an example.

<img width="1126" alt="image" src="https://user-images.githubusercontent.com/7365557/114483675-a851f600-9bbd-11eb-8af9-97d4861c1312.png">

I consider this a bug since it seems the non-logo option does include `site.title` and this was omitted for the logo version, affecting e-mail reachability (albeit not much). This is also a gap for non-image or screenreader environments.

### Technical details:

* Ghost Version: 4.2.0
* Node Version: N/A
* Browser/OS: N/A
* Database: N/A

**Comment by nscalf561** [comment]
Can we reopen this issue?  I'm still seeing this issue, and it is impacting email deliverability for all users.
