### ISSUE TITLE
Database migrations fail on 4.3.2

### ISSUE THREAD

**Issue by brainwarped** [TryGhost/Ghost#12897]
### Issue Summary

When migrating from 3.42.5 to 4.3.2, the database migrations fail. Cannot rollback.

Ghost was able to start, but errored during boot with: update `members_stripe_customers_subscriptions` set `stripe_price_id` = '' - ER_BAD_FIELD_ERROR: Unknown column 'stripe_price_id' in 'field list'.

### To Reproduce

1. Run command `ghost update`
2. Error.

### Technical details:

Debug Information:
    OS: Ubuntu, v16.04.6 LTS
    Node Version: v10.16.0
    Ghost Version: 4.3.2
    Ghost-CLI Version: 1.16.3
    Environment: production
    Command: 'ghost update'

Database: MySQL

**Comment by hnq90** [comment]
I got another issue related to DB migration:

```
Message: Ghost was able to start, but errored during boot with: alter table `stripe_products` add unique `stripe_products_stripe_product_id_unique`(`stripe_product_id`) - ER_INDEX_COLUMN_TOO_LONG: Index column size too large. The maximum column size is 767 bytes.
Help: Error occurred while executing the following migration: 05-add-stripe-products-table.js
```

**Comment by ErisDS** [comment]
Closed as a support request because these sound like database administration issues that belong on the forum.
