### ISSUE TITLE
🚨 Potential Cross-site Scripting (XSS) - Stored (CWE-79)

### ISSUE THREAD

**Issue by huntr-helper** [TryGhost/Ghost#12922]
👋 Hello, @ErisDS, @kirrg001, @kevinansfield - a potential high severity Cross-site Scripting (XSS) - Stored (CWE-79) vulnerability in your repository has been disclosed to us.

#### Next Steps

1️⃣  Visit **https://huntr.dev/bounties/1-other-TryGhost/Ghost** for more advisory information.

2️⃣  **[Sign-up](https://huntr.dev/)** to validate or speak to the researcher for more assistance.

3️⃣ Propose a patch or outsource it to our community - whoever fixes it gets paid.

---

#### Confused or need more help?

- Join us on our **[Discord](https://huntr.dev/discord)** and a member of our team will be happy to help! 🤗

- Speak to a member of our team: @JamieSlome

---

*This issue was automatically generated by [huntr.dev](https://huntr.dev) - a bug bounty board for securing open source code.*

**Comment by ErisDS** [comment]
At Ghost we take security and responsible disclosure _extremely_ seriously. Our security policy, and how to report vulnerabilities to us can be found in our [SECURITY.md](https://github.com/TryGhost/Ghost/blob/main/SECURITY.md) file. 

This issue doesn't follow our policies and does not represent responsible disclosure. Furthermore as we haven't signed up for this service, this constitutes spam and will be reported to GitHub as such.
