### ISSUE TITLE
Regex redirect ignores regex expression parts trailing a greedy capture

### ISSUE THREAD

**Issue by xsdg** [TryGhost/Ghost#12943]
### Issue Summary

I'm still on the 14-day Ghost(PRO) demo, so I'm using whatever version is current.

I uploaded this redirects.yaml:
```
301:
    # Redirect /2012/09/my-post-name.html to /2012/09/my-post-name/
    ^\\/(\\d+)\\/(\\d+)\\/(.+)\\.html: /$1/$2/$3/
```

Except when I uploaded it, it unexpectedly redirected `…/my-post-name.html` to `…/my-post-name.html/`:
```
$curl -I 'https://doppler-photo.ghost.io/1234/56/this-is-a-test.html'
HTTP/2 301 
date: Sat, 08 May 2021 18:59:07 GMT
content-length: 0
set-cookie: __cfduid=da6ef41497bbc18557fb33d36e5e3fbd61620500346; expires=Mon, 07-Jun-21 18:59:06 GMT; path=/; domain=.ghost.io; HttpOnly; SameSite=Lax
status: 301 Moved Permanently
x-request-id: 4485941276581ce59d8187563cc9f4d2
location: /1234/56/this-is-a-test.html/
age: 0
x-cache: MISS
cache-control: public, max-age=31536000
x-request-id: 4485941276581ce59d8187563cc9f4d2
cf-cache-status: DYNAMIC
cf-request-id: 09eef2105800003b3f1196a000000001
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
set-cookie: __cflb=02DiuCzDjsTNptQXPzsE4eZ4sKasgpcwPTvgomMNEfg3v; SameSite=Lax; path=/; expires=Sun, 09-May-21 17:59:07 GMT; HttpOnly
server: cloudflare
cf-ray: 64c4ec608ebb3b3f-SJC
```
Here are some other mappings which I'm currently seeing.  Clearly, it's ignoring the `\.html` at the end of the regex:
```
$curl -s -I 'https://doppler-photo.ghost.io/1234/56/another-test.html' | egrep 'HTTP|location'
HTTP/2 301 
location: /1234/56/another-test.html/

$curl -s -I 'https://doppler-photo.ghost.io/1234/56/is-a-directory/' | egrep 'HTTP|location'
HTTP/2 404 

$curl -s -I 'https://doppler-photo.ghost.io/1234/56/contains-no-dot' | egrep 'HTTP|location'
HTTP/2 301 
location: /1234/56/contains-no-dot/

$curl -s -I 'https://doppler-photo.ghost.io/1234/56/' | egrep 'HTTP|location'
HTTP/2 404 
```

Just to verbalize what seems obvious, I would expect this to not discard parts of the regex pattern.  What that means in this case is that I would expect this rule to not-match and not-apply in cases where the URL doesn't contain `.html`, and further, I would expect it to only capture the parts of the URL that precede and do not include the part of the regex which is outside of a capture group.

**Comment by xsdg** [comment]
One note: in light of #12945, I'm really confused as to how the original redirect file here was loaded without causing an exception of some kind.

**Comment by ErisDS** [comment]
Hi there! If you're having any issue with a **Ghost(Pro)** site, please drop us an email on support@ghost.org and we'll be more than happy to give you a hand directly 🙂

**Comment by xsdg** [comment]
Ditto #12944, this is an obvious platform bug, so this issue should remain open unless/until it's fixed.

**Comment by ErisDS** [comment]
I have closed these issues and pointed you to support because they are not bugs. In this case, this is the standard behaviour of regular expressions in JavaScript.

I suggest waiting for support or reviewing the [docs](https://ghost.org/docs/tutorials/implementing-redirects/).
