### ISSUE TITLE
Broken redirect cannot be unset

### ISSUE THREAD

**Issue by xsdg** [TryGhost/Ghost#12944]
I have a 14-day-trial Ghost(PRO) site.

I uploaded a redirect which was affected by #12943 .  Now, I've noticed that the redirect rule itself seems to have become permanent.

To be clear: I would reasonably expect that cloudflare cache will maintain a 301 for a long period of time once a redirected URL has been requested.  What I am seeing is that the broken redirect is still being applied to cache *misses*, even after I've attempted to set an empty redirects file.  Obviously, this makes things… challenging…

I initially tried just fixing the redirect rule (in the context of #12943, I tried replacing the greedy capture `.+` with a non-greedy capture `.+?`).  That had no effect.  Then I tried changing the 301 to a 302.  No effect.  Finally, I tried uploading an empty json redirect file, `[]`.  Again, no effect.

I had also tried uploading an empty (zero bytes) YAML file, and it complained about not finding a 302 key.  That is probably its own bug, but anyway, it didn't work.

Even 5 minutes after uploading the empty JSON redirect file, I'm seeing cache misses being redirected inappropriately:
```
$curl -s -I 'https://doppler-photo.ghost.io/1234/56/checking-if-redirect-is-still-present'
HTTP/2 301 
date: Sat, 08 May 2021 19:43:36 GMT
content-length: 0
set-cookie: __cfduid=dbe696d15f7e75f54294fc5a61ed5c9391620503016; expires=Mon, 07-Jun-21 19:43:36 GMT; path=/; domain=.ghost.io; HttpOnly; SameSite=Lax
status: 301 Moved Permanently
x-request-id: c2a4e585e7960cafe708b5515c76cfbe
location: /1234/56/checking-if-redirect-is-still-present/
age: 0
x-cache: MISS
cache-control: public, max-age=31536000
x-request-id: c2a4e585e7960cafe708b5515c76cfbe
cf-cache-status: DYNAMIC
cf-request-id: 09ef1acb5700001ee4c72c7000000001
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
set-cookie: __cflb=02DiuCzDjsTNptQXPzsE4eZ4sKasgpcwPEhTAJWeBAVrL; SameSite=Lax; path=/; expires=Sun, 09-May-21 18:43:36 GMT; HttpOnly
server: cloudflare
cf-ray: 64c52d8bb8321ee4-SJC
```

**Comment by xsdg** [comment]
FWIW, after tracking down #12945, I managed to create an empty YAML redirects file using the following contents.  Again, the stuck redirect is still present.
```
301:

302:
```

```
$curl -s -I 'https://doppler-photo.ghost.io/1234/56/redirect2'
HTTP/2 301 
date: Sat, 08 May 2021 20:57:35 GMT
content-length: 0
set-cookie: __cfduid=dd53455c737e0ecdfa9d2e879dd3b09851620507455; expires=Mon, 07-Jun-21 20:57:35 GMT; path=/; domain=.ghost.io; HttpOnly; SameSite=Lax
status: 301 Moved Permanently
x-request-id: 1e848f40f20ae27552106a315bc8db39
location: /1234/56/redirect2/
age: 0
x-cache: MISS
cache-control: public, max-age=31536000
x-request-id: 1e848f40f20ae27552106a315bc8db39
cf-cache-status: DYNAMIC
cf-request-id: 09ef5e8702000093ca6b9d3000000001
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
set-cookie: __cflb=02DiuCzDjsTNptQXPzsE4eZ4sKasgpcwNiXiMfvJCMa8U; SameSite=Lax; path=/; expires=Sun, 09-May-21 19:57:35 GMT; HttpOnly
server: cloudflare
cf-ray: 64c599eb3fd593ca-SJC
```

**Comment by ErisDS** [comment]
Hi there! If you're having any issue with a **Ghost(Pro)** site, please drop us an email on support@ghost.org and we'll be more than happy to give you a hand directly :slight_smile:

**Comment by xsdg** [comment]
Hi Eris.  I had already sent an email referencing this Issue.  Regardless of that, this seems like a bug in the platform, so it feels like this report should be reopened unless there's evidence that it's not actually a bug in the platform
