### ISSUE TITLE
members/api/member/ 401

### ISSUE THREAD

**Issue by Taxick** [TryGhost/Ghost#12940]
Hi :)

### Issue Summary

When I'm logout from my ghost site.. (https://futurenode.dk) I get this error in the console.

`GET https://www.futurenode.dk/members/api/member/ 401 portal.min.js:3 `

The error disappears when im log in to my site.

### To Reproduce

1. Go to https://www.futurenode.dk and log out and the error will show in the console.
2. If you login to my site, the error is gone after login

### Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

The error show up in the console, so that's why I think it's a bug! I have also tested in other browsers! The error has not always been there!

Btw.. I hate errors and I hope they can be fixed!

### G-Scan

https://gscan.ghost.org/ validate my theme with 100 / 100

### Technical details:

* Selfhosted
* Ghost Version: 4.4.0 (at /var/www/ghost)
* Ghost-CLI version: 1.16.3
* Node Version: v14.16.1
* Npm Version: 7.11.1
* Server OS: Ubuntu 20.04 
* Database: Mysql  Ver 8.0.23
* Client OS: Windows 10 with last updates
* Client Browser # 1: Chrome Version 90.0.4430.93
* Client Browser # 2 : Brave: Version 1.24.82 Chromium: 90.0.4430.93

Regads: 

Thomas from: Futurenode.dk

**Comment by rishabhgrg** [comment]
Hey @Taxick , while the 401 error on console is not a bug and does not affect any functionality, we have now removed that error [here](https://github.com/TryGhost/Ghost/commit/196cdafe6b68fc5b1412b03a7ab91897eebbe702) and will not show up on console starting from next release of Ghost.
