### ISSUE TITLE
Typo in docs

### ISSUE THREAD

**Issue by lfuelling** [TryGhost/Ghost#12959]
### Issue Summary

On the [Themes>Contexts>Author](https://ghost.org/docs/themes/contexts/author/) docs page there is a typo in the source code example at the bottom.

The Docs repo is unfortunuately read-only and I'm unable to find a way to edit the docs myself and create a PR.

### To Reproduce

1. Go to https://ghost.org/docs/themes/helpers/img_url/#example-code
2. Search for: `<img src="{{profile_image}})" alt="{{name}}'s Picture" />`

The `src` attribute in the `img` tag is invalid, there is a `)` at the end that causes the image url to always end with `)`.

Additionally (I'm not sure about this) the `img_url` helper is missing.

### Technical details:

* Ghost Version: Docs
* Node Version: Docs
* Browser/OS: Firefox macOS
* Database: Docs

**Comment by matthanley** [comment]
Hey @lfuelling - thanks for the report. This has now been fixed.
