### ISSUE TITLE
Add ability to hide "powered-by" badge in subscription portal

### ISSUE THREAD

**Issue by lfuelling** [TryGhost/Ghost#12960]
### Issue Summary

I'd really like to remove the design-breaking "Publish with Ghost" badge from the subscription modal since I already have a link to ghost in my site footer.

### To Reproduce

1. Open any Ghost Blog (preferably with a custom theme so it stings more)
2. Click the subscription button
3. The badge is at the lower left corner

There is an option to remove the same badge from emails, I can't see why the same shouldn't be possible for the portal.

### Technical details:

* Ghost Version: 4.5.0
* Node Version: 14.17.0
* Browser/OS: Firefox/macOS
* Database: not sure but probably not relevant

**Comment by noahsbwilliams** [comment]
I agree. Though I'm happy to promote Ghost - including in the footer of my site and emails - I'm not big on this particular placement. Doesn't fit well, IMO, and not being able to turn it off seems off-step for Ghost.

**Comment by lfuelling** [comment]
What the even...

I surely won't sign up for yet another stupid forum. I guess I'll just use a better blogging platform then.
