### ISSUE TITLE
Overriding some config values is impossible

### ISSUE THREAD

**Issue by rubik** [TryGhost/Ghost#12962]
### Issue Summary

If I specify a custom URL in my `config.production.js` for the `portal:url` config value, the portal URL is not updated on the site.

### To Reproduce

1. Add a custom script `portal.min.js` to your theme root folder
2. Upload the theme
3. Add the following JSON to `config.production.json`:
```json
"portal": {
  "url": "https://<your ghost site URL>/portal.min.js"
}
```
4. Restart Ghost with `ghost restart`
5. Check the portal URL in the <head>, and verify that it's the default one instead of the custom one.

### Technical details:

* Ghost Version: Ghost-CLI 1.17.0, Ghost 4.4.0
* Node Version: 14.16.1
* Browser/OS: Firefox, Chrome
* Database: MySQL
* Environment: `production` (confirmed with `ghost doctor`)

**Comment by ErisDS** [comment]
I'm not able to reproduce this at all - I've tried several times. The config is designed to be overridden and I've also heard several people talking about having done it successfully on the forum.
