### ISSUE TITLE
The currency change is not updated for {{price currency=@price.currency}} helper

### ISSUE THREAD

**Issue by fueko** [TryGhost/Ghost#12986]
Hi!

In the Ghost 4.6.1 the currency change is not updated for `{{price currency=@price.currency}}` helper. Works fine with the `{{price @price.monthly}}` helper. 

The helper `{{price currency=@price.currency}}` is used e.g. in the[ Lyra theme](https://github.com/TryGhost/Lyra/blob/dc85130cf7a203c32835d0dd5ebacd956aec368a/members/signup.hbs#L24) to display the currency independently of the price (what is important when you want to add a special style for the currency sign).

### To Reproduce

1. Install Ghost with e.g Lyra theme.
2. Connect with Stripe.
3. After a currency change, the page is not updated:

Dashboard:
![Zrzut ekranu 2021-05-26 o 20 28 11](https://user-images.githubusercontent.com/23366922/119713173-b902b680-be61-11eb-92aa-19c58b41f3f3.png)

Theme:
![Zrzut ekranu 2021-05-26 o 20 27 48](https://user-images.githubusercontent.com/23366922/119713132-adaf8b00-be61-11eb-81a6-23e8a0e7776d.png)

Portal:
![Zrzut ekranu 2021-05-26 o 20 34 49](https://user-images.githubusercontent.com/23366922/119713318-d9327580-be61-11eb-8c41-3b74e84f4d9f.png)

### Technical details:

* Ghost Version: 4.6.1
* Node Version:  12.22.1
* Browser/OS: All
* Database: sqlite3

**Comment by rishabhgrg** [comment]
Thanks for the report @fueko , can reproduce the issue and we'll patch it asap in the next release
