### ISSUE TITLE
Bug: Adding an "admin.url" config option causes the API to return 404 errors.

### ISSUE THREAD

**Issue by surdaft** [TryGhost/Ghost#12989]
### Issue Summary
When applying the config option admin.url within the config, the api no longer outputs correct URI's for tags.
I wanted to create a quick docker example however admin.url config forced a https redirect on the domain, so this was not possible.

Server:
Ubuntu 20.04
Ghost latest

Browser:
Linux
Firefox 88

### To Reproduce

1. Set admin url within config:
```
"admin": {
    "url": "https://admin.example.com"
}
```
2. Create a new integration
3. Copy the key
4. Curl the webpage
```
curl -L -H "Accept: application/json" "https://admin.example.com/ghost/api/v2/content/tags/?key=XXX"
```
5. Identify the response url for tags to contain 404 page as url

This seems to be a regression for #11043

### Technical details:

* Ghost Version: 4.6 (Latest, I think it's 4.6)
* Node Version: v14
* Browser/OS: Firefox
* Database: MySQL 8

**Comment by ErisDS** [comment]
I'm not able to reproduce this on the v2, v3 or v4 API nor can I think of any reason why those two things would be related.

Can you restart Ghost and try again?
