### ISSUE TITLE
Docs typo

### ISSUE THREAD

**Issue by a2br** [TryGhost/Ghost#12984]
Didn't find where I could make a PR; there's a typo here: 

[Theme structure](https://ghost.org/docs/themes/structure) > Templates > home.hbs > "is only be used to"

**Comment by meenal21** [comment]
Fork the repository and then you can find it in your repositories. Makes changes there and raise a PR there.

**Comment by a2br** [comment]
@meenal21 Oh, so the docs are here?

**Comment by matthanley** [comment]
Thanks @a2br - this has been fixed.
