### ISSUE TITLE
Trigger Webhook Timezone is incorrect Ghost Settings

### ISSUE THREAD

**Issue by cuongtqtran** [TryGhost/Ghost#12993]
![](https://p215.p3.n0.cdn.getcloudapp.com/items/rRujJbz1/36ed5354-0cc0-4531-818a-fcc0e43db30d.png?v=604c4659d177d31d72b01f6b3c5b4b6c)

## The ghost setting ↓

![](https://p215.p3.n0.cdn.getcloudapp.com/items/4gunYlRx/8112b3a7-7432-44bc-931d-c4554c7c5362.png?v=dfc8356caf1a0f666e03255963f4187d)

**Comment by ErisDS** [comment]
In raising this issue you have deleted our issue template. Please fill out the template fully so that we have the information we need to help you.
