### ISSUE TITLE
Complimentary sub breaks when adding labels to a member

### ISSUE THREAD

**Issue by mhelf** [TryGhost/Ghost#13003]
### Issue Summary

Complimentary subscription disappears when labels are added to member.

### To Reproduce

1. Navigate to single member in ghost admin
2. Add complimentary premium subscription
3. Add 2 different labels to member
4. Watch complimentary subscription disappear
5. Save member
6. Refresh page
5. Another complimentary sub cannot be added

### Technical details:

Tested on my local and live environment.

* Ghost Version: 4.6.4
* Node Version: 14.16.1
* Browser/OS: Safari / Mac OSX
* Database: MySQL 8.0.23

**Comment by matthanley** [comment]
@mhelf Thanks for the report - this has been resolved in https://github.com/TryGhost/Ghost/pull/13008

**Comment by ErisDS** [comment]
This was released in 4.6.5 just now.
