### ISSUE TITLE
Backticks in numbered lists cause removal of all images and distortion of content

### ISSUE THREAD

**Issue by cmprmsd** [TryGhost/Ghost#13058]
### Issue Summary

On Firefox (maybe others) when I write articles and try to use \``` in a numbered list after pressing Shift+Enter for a newline Ghost will distort my content and remove any images. 

![image](https://user-images.githubusercontent.com/73472903/122230060-950f1f80-ceb9-11eb-8dc1-6115d5ee0f1d.png)

### To Reproduce

1. Create a blog entry
2. Insert some images
3. Insert a numbered list
4. Press `shift+Enter` for a newline without getting a new number in the list
5. Add two backticks and the editor will break all images (and sadly autosave)

### Technical details:

* Ghost Version: 4.7.0
* Node Version: 14
* Browser/OS: Firefox Linux
* Database: Sqlite

Additional info:
The issue does only occur when deadkeys are enabled and one presses backspace after the first backtick.
I did not have this issue after disabling them `setxkbmap de nodeadkeys`

**Comment by ErisDS** [comment]
Hi @cmprmsd as per your update, this isn't reproducible for me on a mac+firefox. I'm not sure what deadkeys are, or why you would have them enabled 😬 

If this is something you would like to contribute a fix for, then I'd love a PR, otherwise I think we should close this as being very edge case?

**Comment by cmprmsd** [comment]
Hi ErisDS, 
You can try it yourself with a Linux virtual machine and the command `loadkeys de` or `setxkbmap de`.
Deadkeys wait for another key after inserting a backtick in order to write accents in different languages. 

I think this might be benefitial for the project to fix it. 
I'm fine with the workaround I use now. But I'm sure people not knowing such tricks might think the editor is really buggy, which was my first thought, too. 

I'm no programmer. Maybe someone wants to pick this up. It's fine for me, if you close it as wontfix.

**Comment by mauskin** [comment]
@ErisDS on a Mac such symbols could be entered (using U.S. layout in this instance) holding an Option key. If you open Keyboard Viewer and hold Option those symbols would highlight in orange.

**Comment by ErisDS** [comment]
If this issue matters to you, PRs are welcome :)
