### ISSUE TITLE
Critical security update notification while on latest version (self-hosted)

### ISSUE THREAD

**Issue by olegtarasov** [TryGhost/Ghost#13096]
### Issue Summary

“Critical security update available — please update Ghost as soon as possible” is displayed on every page in admin ui despite updating to the latest version. If closed, it reappears on page reload.

### To Reproduce

This happens every time I load any page in admin ui.

### Technical details:

* Ghost Version: 4.8.3
* Node Version: v14.17.1
* Browser/OS: Safari / MacOS
* Database: mysql

**Comment by ErisDS** [comment]
This is a known issue, fixed in main. It'll be released in the next minor - so 4.9
