### ISSUE TITLE
Keyboard suggestions / autocorrect do not work on iOS

### ISSUE THREAD

**Issue by JBYoshi** [TryGhost/Ghost#13097]
### Issue Summary

When typing in the post editor on iOS, keyboard suggestions and autocorrect do not work.

In most apps and websites, you should see suggested words show above the keyboard as you type. These don't appear in the Ghost editor - that section is blank. Also, if you make a typo, the keyboard will automatically correct it; this doesn't happen in the Ghost editor.

I did a bit of investigation on my own, and this seems to have something to do with calling preventDefault() on the key events.

### To Reproduce

1. Create a new post.
2. Start typing in the body. Notice that the suggestion bar at the top of the keyboard stops updating after one or two keypresses.
3. Make a typo in a word. Notice that the keyboard does not suggest or correct it, as it would in other apps.

### Technical details:

* Ghost Version: 4.6.3
* Node Version: 14.7.1
* Browser/OS: Safari iOS 14.6
* Database: MySQL 8.0.25

**Comment by ErisDS** [comment]
Until recently, we had a big banner saying we didn't officially support the editor on mobile. We took that away as it largely works, especially on iPad and the banner got in the way. However, no work has been done to make the editor experience tailored to mobile.

I use the editor on my phone a lot and this also bugs me, would love to see a PR which makes this work!

**Comment by johlym** [comment]
Could `contenteditable="true"` and or `spellcheck="true"` be helpful on each of the `div`s in the editor? 

Poking at this for a moment, and using textbox.io as a comparison, that appears to be the only big difference I can see. 

Also curiously enough, I can reproduce this, but only if I don't tap a predictive suggestion first. If I do that, it works fine for as long as I want 🤔

**Comment by JBYoshi** [comment]
After a bit of experimentation, I found that switching to `preventDefault()` on the `beforeinput` event (instead of `keydown`) *does* work as expected with autocorrect/suggestions. Although it does have a different API, it should provide the same behavior, along with support for other inputs like pastes.

**Comment by JBYoshi** [comment]
This is reproducible with just mobiledoc-kit, so I'm moving the issue there.
