### ISSUE TITLE
Emails going to spam due to DMARC failures

### ISSUE THREAD

**Issue by jeffywu** [TryGhost/Ghost#13119]
Welcome 👋   
Please keep in mind that GitHub is our office. We invite you to share any bug reports here 🐛..  
For anything else please use https://forum.ghost.org 👫

### Issue Summary

Email confirmations from the ghost hosted platforms are going to spam in Gmail due to DMARC alignment check failures. Here the header from an email signup confirmation link:

```
header.from=example.org
Return-Path: <bounce+82dff3.12271d-jeff=example.org@ghost.io>
Received: from relay1.ghost.io (relay1.ghost.io. [161.38.194.233])
        by mx.google.com with UTF8SMTPS id u9si10669486ybp.85.2021.07.05.04.45.25
        for <jeff@example.org>
        (version=TLS1_3 cipher=TLS_AES_128_GCM_SHA256 bits=128/128);
        Mon, 05 Jul 2021 04:45:29 -0700 (PDT)
Received-SPF: pass (google.com: domain of bounce+82dff3.12271d-jeff=example.org@ghost.io designates 161.38.194.233 as permitted sender) client-ip=161.38.194.233;
Authentication-Results: mx.google.com;
       dkim=pass header.i=@ghost.io header.s=smtp header.b=Aj2llx0G;
       spf=pass (google.com: domain of bounce+82dff3.12271d-jeff=example.org@ghost.io designates 161.38.194.233 as permitted sender) smtp.mailfrom="bounce+82dff3.12271d-jeff=example.org@ghost.io";
       dmarc=fail (p=QUARANTINE sp=QUARANTINE dis=QUARANTINE) header.from=example.org
From: Support <support@example.org>
To: jeff@example.org
Subject: 🔑 Secure sign in link for example.org
Content-Type: multipart/alternative; boundary="----Nodemailer-0.7.1-?=_1-1625485503385"
MIME-Version: 1.0
```

DMARC alignment fails (I think) because the return path domain `Return-Path: <bounce+82dff3.12271d-jeff=example.org@ghost.io>` does not match the `From: Support <support@example.org>` path. In order to get this to go through to the inbox by avoiding the spam folder I had to turn off DMARC. I've enabled SPF for ghost.io but the DMARC alignment will still fail because return path does not equal the from address.

I couldn't find any documentation on how to change the return path or update this so that I can still have DMARC enabled for my domain.

**Comment by ErisDS** [comment]
Hi there! If you're having any issue with a **Ghost(Pro)** site, please drop us an email on support@ghost.org and we'll be more than happy to give you a hand directly :slight_smile:
