### ISSUE TITLE
Code block Hyperlinks

### ISSUE THREAD

**Issue by Stono** [TryGhost/Ghost#13127]
Hey,
This is basically the same as https://github.com/TryGhost/Ghost/issues/9566 which is closed, and I'm honestly not sure why...

Here you can see how in the code block the `apiVersion` has been turned into a link which then hides the value as links are the same colour as my code block background.

![Screenshot 2021-07-07 at 16 45 42](https://user-images.githubusercontent.com/1486729/124790097-c9b74980-df42-11eb-9ef7-b83db40e2595.png)

![Screenshot 2021-07-07 at 16 45 37](https://user-images.githubusercontent.com/1486729/124790094-c91eb300-df42-11eb-9c0a-d4fba7a8897b.png)

It's not just styling to be honest, `networking.istio.io/v1alpha3`, isn't a link.... there's no protocol on that.

Same happens on this bit:
```
          typed_config:
            '@type': 'type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua'
```

**Comment by ErisDS** [comment]
Hi @Stono,

1) the issue you linked to relates to a previous incarnation of our editor and code that no longer exists unless you're running a very very outdated version of Ghost.
2) the main reason that issue got closed (other than that we were about to replace the editor) was that the report wasn't filled out properly with a reproduction case, something you have repeated in that you have deleted the issue template, not provided a reproduction case or the details we ask for.

I understand that you are frustrated, however if you're asking for us to fix a problem, I really think the very least that you could do is provide us with proper information in the format that we ask for it.

**Comment by Stono** [comment]
> the main reason that issue got closed (other than that we were about to replace the editor) was that the report wasn't filled out properly with a reproduction case

Yet the issue states:

> I'm going to close this issue because it's the expected behaviour and would be a breaking change if the behaviour was modified

So that's not strictly true, is it?

Seeing as there was already an existing discussion about the subject, I (albeit incorrectly) assumed you wouldn't need a complete issue template to be completed again.
