### ISSUE TITLE
knex 0.21.19 is not compatible with bookshelf 0.15.2 and deprecation errors

### ISSUE THREAD

**Issue by drussell393** [TryGhost/Ghost#13135]
### Issue Summary

Installing on AlmaLinux 8.4 (RHEL branch-off) with npm from source (GitHub). I'm getting the following error:

```
npm ERR! Found: knex@0.21.19
npm ERR! node_modules/knex
npm ERR!   knex@"0.21.19" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer knex@">=0.13.0 <0.18.0" from bookshelf@0.15.2
npm ERR! node_modules/bookshelf
npm ERR!   bookshelf@"0.15.2" from the root project
```

bookshelf expects a dependency of knex =0.13.0 and <0.18.0, but Ghost is installing 0.21.19

Upgrading package.json to bookshelf 1.2.0 (the latest version of bookshelf) appears to solve this issue, but a slew of other dependencies required by Ghost or other packages are giving security vulnerability warnings and deprecation errors in NodeJS (npm):

#### uuid
```
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
```

#### nodemailer
```
npm WARN deprecated nodemailer@0.7.1: All versions below 4.0.1 of Nodemailer are deprecated. See https://nodemailer.com/status/
```

#### request and request-promise
```
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated request-promise@4.2.6: request-promise has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
```

#### intl-messageformat-parser
```
npm WARN deprecated intl-messageformat-parser@2.1.3: We've written a new parser that's 6x faster and is backwards compatible. Please use @formatjs/icu-messageformat-parser
```

#### debug
```
npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
```

So, question on the deprecated ones - some are backwards compatible (like int-message-formatparser), but would upgrading the others myself via `package.json` work with Ghost still? A bit worried regarding some of the security vulnerabilities on that stuff.

### To Reproduce

Download the latest version (4.9.3) from GitHub and run `npm install --production`.

### Technical details:

* Ghost Version: 4.9.3
* Node Version: 14.17.0
* Browser/OS: AlmaLinux 8.4
* Database: MySQL

**Edit: It looks like `yarn setup` seems to ignore the dependency issues and deprecation errors, though I am still a bit concerned about the possible security issues of having those deprecated modules involved.**

**Comment by ErisDS** [comment]
As per our [documentation](https://ghost.org/docs/install/source/) you need to use yarn to install Ghost's dependencies. not npm.

Any dependencies that are pinned in Ghost are pinned for (hopefully obviously) a good reason and represent significant work to upgrade, which we will prioritise as and when we can or it becomes necessary. 

With the network of packages, there are often reports of vulnerabilities in dependencies where there is no possible way for it to affect Ghost. All security reports are reviewed at regular intervals, and any dependencies which have security issues where the vector affects Ghost in some way are handled immediately.

**Comment by drussell393** [comment]
> 
> 
> As per our [documentation](https://ghost.org/docs/install/source/) you need to use yarn to install Ghost's dependencies. not npm.
> 
> Any dependencies that are pinned in Ghost are pinned for - hopefully obviously, as we maintain 100s of dependencies - a good reason and represent significant work to upgrade, which we will prioritise as and when we can or it becomes necessary.
> 
> With the network of packages, there are often reports of vulnerabilities in dependencies where there is no possible way for it to affect Ghost. All security reports are reviewed at regular intervals, and any dependencies which have security issues where the vector affects Ghost in some way are handled immediately.

Super happy with this answer, and glad to hear that the vulnerabilities are watched and don't affect Ghost. That covers all of my concerns, so happy to proceed using Ghost :) Thanks for your time.
