### ISSUE TITLE
Path bug for windows machine ( Local )

### ISSUE THREAD

**Issue by themeix** [TryGhost/Ghost#13156]
### Issue Summary

Installing themes giving fatal errors because of the path issue.  Partial Files could not be found for the Casper theme too.

![image](https://user-images.githubusercontent.com/28748452/126022756-b6b67e97-403a-4226-adbc-459c751e77de.png)

### To Reproduce

1. Install the Latest version ghost with Node -version: v14.17.3
2. Actiave Casper or Edition theme

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

### Technical details:

Ghost-CLI version: 1.17.3
Ghost version: 4.9.4
Node -version: v14.17.3

Forum Topic : https://forum.ghost.org/t/ghost-new-version-get-fatal-error/24212

**Comment by tpatel** [comment]
Thanks for the report, I've [written a fix](https://github.com/TryGhost/Ghost/commit/8425fb480d3975d9bdac4ad9a8b241ebeea9df15) that will land in the next Ghost version.

**Comment by daniellockyer** [comment]
This was fixed and released in 4.10.0 🙂
