### ISSUE TITLE
redirect doesn't start at base of url

### ISSUE THREAD

**Issue by tedserbinski** [TryGhost/Ghost#13159]
### Issue Summary

It appears there is a bug in the redirect code that doesn't start at the root url but at the first instance in the path.

### To Reproduce

http://tedserbinski.com/tag/mobility  =>  404 page [should goto the tag page like others]

In redirects.json I have
`{
    "from": "/mobility/",
    "to": "https://tedserbinski.com/mobility-startup-innovation/",
    "permanent": true
}`

### Technical details:

hosted at ghost.org

Version 4.9.4
Environment production
Database mysql
Mail SMTP

**Comment by johlym** [comment]
Two notes:

First, JSON support is likely to be pulled at some point. `YAML` is the de facto format for redirects, now. ([link](https://ghost.org/docs/tutorials/implementing-redirects/))

Second, with the first bullet in mind, something like: 

```yaml
301:
    /^\/mobility\//i: /mobility-startup-innovation/
```

Should do the trick. The `^` indicates the match should start at the beginning of the URI.

**Comment by ErisDS** [comment]
This is intended behaviour - not everyone's site lives at the root url. You can force the start using regex syntax as explained above.
