### ISSUE TITLE
ghost-members-ssr cookie [object Object] after member logs out

### ISSUE THREAD

**Issue by mhelf** [TryGhost/Ghost#13160]
### Issue Summary

Hi
I found a possible issue related to the ghost-members-ssr cookie.
After a member logs out the cookie gets a value of "object Object".

### To Reproduce

1. Login as a member
2. Logout
3. Observe value of cookie ghost-members-ssr in devtools.

### Technical details:

* Ghost Version: 4.8
* Node Version: 14.16.1
* Browser/OS: Chrome / Safari

**Comment by allouis** [comment]
closed by https://github.com/TryGhost/Members/pull/302 & https://github.com/TryGhost/Ghost/pull/13166
