### ISSUE TITLE
Site preview does not follow redirect

### ISSUE THREAD

**Issue by yamsellem** [TryGhost/Ghost#13175]
### Issue Summary

If a site is configured with an http url, the preview in the admin fails with `Mixed Content: The page at 'https://xxx/ghost/#/site' was loaded over HTTPS, but requested an insecure frame 'http://xxx/?v=1627043265096'. This request has been blocked; the content must be served over HTTPS`

### To Reproduce

* Deploy Ghost with an `http` url (using --no-prompt [seems to force to do so](https://github.com/TryGhost/Ghost/issues/13155))
* Go to the admin dashboard and preview site

### Technical details:

* Ghost CLI Version 1.17.3
* Ghost Version 4.9.4
* Node Version 14.17.3
* Browser/OS: Chrome/MacOS 10.14
* Database: MySQL

**Comment by vikaspotluri123** [comment]
If you're using SSL for your site, the URL **has** to start with `https` :wink:

Case: My admin panel is https, but my site is http --> the error you're seeing is correct!
Case: My admin panel and site are the same, configured as http, but serving https --> this is a configuration error
