### ISSUE TITLE
Adding member via @tryghost/admin-api does not send subscribe or signup email

### ISSUE THREAD

**Issue by jakewies** [TryGhost/Ghost#13222]
### Issue Summary

I am using Ghost as a Headless CMS with a NextJS front-end. I have been using `@tryghost/admin-api` to build out UI to allow readers to subscribe to the site using the members api. Unfortunately the members api is undocumented, though I have been able to navigate the repositories to string this together:

```js
import GhostAdminApi from '@tryghost/admin-api'

const api = new GhostAdminApi({/* config */})
const member = { email: 'foo@bar.com' }
const options = { send_email: true, email_type: 'subscribe' }

// ...

await api.members.add(member, options)
```

This gets me 90% of the way there. Triggering the above code will fire off a POST request to:

`/ghost/api/v3/admin/members/?send_email=true&email_type=subscribe` 

And because I am also supplying the `send_email` and `email_type` options, [I expect to have an email sent to the reader](https://github.com/TryGhost/Ghost/blob/235597a5e4ba9dd9768e55c8b761efe9947a7261/core/server/api/v3/members.js#L135), and the content of that email to be [the `subscribe.js` email template](https://github.com/TryGhost/Ghost/blob/main/core/server/services/members/emails/subscribe.js). Unfortunately, every request I make generates a [`signin.js` email template](https://github.com/TryGhost/Ghost/blob/main/core/server/services/members/emails/signin.js) only.

![Screen Shot 2021-08-12 at 3 04 05 PM](https://user-images.githubusercontent.com/12075916/129253978-cf39640f-9f33-4f74-bdd5-21f2b205052c.png)

I've done some digging on this and have managed to (I think) find the flow of logic that leads to a potential problem:

1. Call `api.members.add` from `@tryghost/admin-api`
2. This triggers [a handler function to process the request](https://github.com/TryGhost/Ghost/blob/235597a5e4ba9dd9768e55c8b761efe9947a7261/core/server/api/v3/members.js#L109)
3. Because `send_email: true` is supplied as a request option, the [`membersService.api.sendEmailWithMagicLink` function](https://github.com/TryGhost/Members/blob/97a270bdd9c6ff7094552c43f4af3c42c7572711/packages/members-api/lib/MembersAPI.js#L225) is executed. It receives the `email` of the newly added member and the `email_type` (renamed to `requestedType`)
4. [This conditional passes](https://github.com/TryGhost/Members/blob/97a270bdd9c6ff7094552c43f4af3c42c7572711/packages/members-api/lib/MembersAPI.js#L227) since the `options.forceEmailType` argument is not supplied, and is defaulting to `false`
5. [This conditional passes](https://github.com/TryGhost/Members/blob/97a270bdd9c6ff7094552c43f4af3c42c7572711/packages/members-api/lib/MembersAPI.js#L229) since a member was generated [a few steps prior](https://github.com/TryGhost/Ghost/blob/235597a5e4ba9dd9768e55c8b761efe9947a7261/core/server/api/v3/members.js#L125)

Now I don't have full context of Ghost's services, but it would seem that in order for the admin-api to properly allow for other email templates to be utilized other than `'signin'`, [this execution site of `sendEmailWithMagicLink`](https://github.com/TryGhost/Ghost/blob/235597a5e4ba9dd9768e55c8b761efe9947a7261/core/server/api/v3/members.js#L136) needs to "force" the email type. If it passed in `options.forceEmailType: true`, the `email_type` option to the request would be respected.

### To Reproduce

1. Call the `api.members.add` function from `@tryghost/admin-api` with an email to add and the options `{ email_type: 'subscribe', send_email: true }`
2. Notice that the email you receive is the `'signin'` email

### Technical details:

* Ghost Version: 4.10.2
* Node Version: 12.18.3
* Browser/OS: Chrome
* Database: default Ghost DB (not sure)

**Comment by mainawycliffe** [comment]
I can confirm this is an issue I have experienced as well. Maybe this is because the membership API is still in canary.

**Comment by allouis** [comment]
Fixed here https://github.com/TryGhost/Ghost/commit/c45afc7f2614483b40b467d47f9bc484ebe37281
