### ISSUE TITLE
Content import fails: Unable to update nested relation. [object Object]

### ISSUE THREAD

**Issue by TaliNation** [TryGhost/Ghost#13261]
### Issue Summary

When I try to import my content in a local Ghost 4.12.0 and above, it fails with the following error:

![firefox_u3q18cdvA4](https://user-images.githubusercontent.com/33716117/131036125-3ff80030-9933-4c92-b0c7-d8aac6f783ae.png)

![image](https://user-images.githubusercontent.com/33716117/131038679-33316b8e-989e-45b4-98d4-a238525446a2.png)

...with the following response body:

```json
{
   "errors":[
      {
         "message":"Unable to update nested relation.",
         "context":{
            "key":"posts_meta",
            "tableName":"posts",
            "method":"setHasOne"
         },
         "type":"BookshelfRelationsError",
         "details":null,
         "property":null,
         "help":"Post",
         "code":"UPDATE_RELATION",
         "id":"45a4c930-06b4-11ec-8bcf-31ea7323048b"
      }
   ]
}
```

My JSON content file was exported on Ghost 3.13.1. **I tried on 4.11.0 and it works perfectly.**

### To Reproduce

1. Install Ghost locally with ghost-cli: `ghost install local`
2. Setup the site
3. Delete all content through Settings > Labs
4. Import content

### Technical details

* Ghost Version: 4.12.0 and above
* Node Version: 14.17.5
* Browser/OS: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:91.0) Gecko/20100101 Firefox/91.0
* Database: SQLite

**Comment by frisodubach** [comment]
I have the same exact issue, and sadly no idea how to fix it. I've tried to migrate even on the same hardware, using the same Ghost version, but it doesn't help.

**Comment by matthanley** [comment]
I believe this should have been fixed in 4.13.0 via https://github.com/TryGhost/Ghost/pull/13284

**Comment by lesbaa** [comment]
Unfortunately this is still happening for me on 4.13.0...

**Comment by matthanley** [comment]
@lesbaa the original issue is related to content imports, which based on your logs is not the same problem you have. If you believe you've run into a different bug, please create a new issue using the template provided - thanks!
