### ISSUE TITLE
Multiple Segment Labels Frontend Do Not Work

### ISSUE THREAD

**Issue by websitehelperuk** [TryGhost/Ghost#13268]
Assigning more than one selected label at signup does not work. 

As of now the HTTP request contains all of the labels, not just the checked ones.

This is because Portal doesn’t follow regular form behavior, and takes the value attribute of the checkboxes with no regard to its checked status.

[Thread](https://forum.ghost.org/t/adding-labels-to-members-on-signup-isnt-working/21583/19)

**Comment by matthanley** [comment]
Hey @websitehelperuk - this doesn't appear to be a bug in Ghost but an issue with a custom theme, and we ask that you please do not use GitHub for help or support 😄. We use GitHub solely for bug-tracking and on-going feature development.

Thanks!

**Comment by websitehelperuk** [comment]
> Hey @websitehelperuk - this doesn't appear to be a bug in Ghost but an issue with a custom theme, and we ask that you please do not use GitHub for help or support 😄. We use GitHub solely for bug-tracking and on-going feature development.
> 
> Thanks!

I reported a bug, if it’s not a bug that is all you need to say.

I didn’t come to request support.
