### ISSUE TITLE
HTML file size too big as images are converted to base64 by default.

### ISSUE THREAD

**Issue by JPrasad21** [TryGhost/Ghost#13278]
Preview Link: [https://www.botminds.ai/release/botminds-v10-5](https://www.botminds.ai/release/botminds-v10-5)

**To Reproduce**

1. Create a new post in ghost.
2. Upload 4-5 images.
3. Check the preview of the post.

Images are converted to base64 by default and causing big HTML file size.
In my case 1.5Mb which is too large.

**Expected Behaviour**
Uploaded images to be in url format 
like this `<img src="content/images/2020/03/test.jpg" />` 
rather than `<img src="data:image/gif;base64,R0lGODlhAA...." />`

**Technical Details**
1. Ghost Version: 4.10.0
2. Environment: production
3. Database: sqlite3

**Comment by ErisDS** [comment]
Hi @JPrasad21, apologies for the slow reply here.

Ghost is designed to upload any image, not convert it to base64. I've never heard a report of it doing this before, nor can I reproduce it. I've tried dragging and dropping from file, from apple photos and using both the image and gallery cards.

Could you please provide the exact reproduction steps you used to create this effect, including how you installed Ghost & your operating system and browser.

You may find it easier to close this issue and open a brand new one as we now have a much better issue template which has clear fields to fill out for all the things we need to know. 

Thanks!
