### ISSUE TITLE
"From" field in emails are not rendering correctly

### ISSUE THREAD

**Issue by hkrsmk** [TryGhost/Ghost#13280]
### Issue Summary

The 'From' field of sent emails are not rendering correctly. Relevant 

### To Reproduce

1. Set desired email name in production.config.json
2. Send an email by publishing a test post that sends out to newsletter subscribers.
3. The 'From' field takes the blog title as the sender name.

### Technical details:

* Ghost Version: 4.12.1
* Node Version: 14.17.2
* Browser/OS: Firefox/Ubuntu 20.04
* Database: MySQL

### Related forum posts
I've previously posted about this but hasn't seen a good fix.
1. [A thread I read](https://forum.ghost.org/t/email-received-is-a-different-email-than-my-from-email-in-admin-area/15213/39)
2. [A thread with a proposed fix, but it is hardcoded](https://forum.ghost.org/t/is-there-a-way-to-edit-the-name-associated-with-the-from-address-of-newsletter-emails/18256/7)
3. [A thread I started](https://forum.ghost.org/t/from-field-in-sent-emails-not-taking-the-same-value-as-from-field-in-config-file/22773)

### Steps taken to attempt a fix
1. Playing with the `config.production.json` file: remove quotes from name, tried escaped double quotes, swapped single and double quotes.
2. Looking at the `getFromAddress` function in [GhostMailer.js](https://github.com/TryGhost/Ghost/blob/main/core/server/services/mail/GhostMailer.js), `validator.isEmail` (though not the `@tryghost` one), and nodemailer, but the logic looks right

Really have no idea where the issue is. Perhaps there is something wrong with the `message.from` object but I can't tell.

**Comment by danimajo** [comment]
In server services/mega/mega.js

In getfromadress:


`const siteTitle = settingsCache.get('title') ? settingsCache.get('title').replace(/"/g, '\\"') : '';`
`return siteTitle ? '"${siteTitle}"<${fromAddress}>' : fromAddress;`

So it's always the siteTitle as name from (if siteTitle is set).
In my opinion we would need a new setting (members_from_name) for that

I can work on it, if needed.

**Comment by hkrsmk** [comment]
That's great news!

2022年4月28日(木) 19:43 Hannah Wolfe ***@***.***>:
