### ISSUE TITLE
Images are rendering incorrectly on Microsoft Outlook

### ISSUE THREAD

**Issue by yirenlu92** [TryGhost/Ghost#13297]
The images look abnormally large, and the bullet points for some reason are not appearing...
Do I need to make sure that the images are a certain size, or is there some issue with responsiveness settings?

https://www.loom.com/share/ddd56f8935af4d618d1c193765ca6a11

**Comment by ErisDS** [comment]
Please can you fill out the following details?

### Technical details:

* Ghost Version:
* Node Version:
* Browser/OS:
* Database:
