### ISSUE TITLE
Public previews + admin api upload not working with source html

### ISSUE THREAD

**Issue by mhelf** [TryGhost/Ghost#13309]
Hi I found a possible bug related to the admin-api upload of posts with a public-preview configured.

I opened the original issue in the Koenig repo and already created a **pull request** with a possible fix.

Please have a look:
https://github.com/TryGhost/Koenig/issues/267

**Comment by ErisDS** [comment]
Closing as there's already an issue & PR open in the relevant repo - will take a look soon.
