### ISSUE TITLE
Ghost 4.14.0 contains critical vulnerability

### ISSUE THREAD

**Issue by jkirkpatrick** [TryGhost/Ghost#13310]
### Issue Summary
Install or update to ghost 4.14.0 contains one critical vulnerability: https://www.npmjs.com/advisories/1708

"nodemailer before version 6.4.16 is vulnerable to command injection. Use of crafted recipient email addresses may result in arbitrary command flag injection in sendmail transport for sending mails."

### To Reproduce

1. Install  / update latest version of ghost
2. `npm audit`
3. View the critical issue 
```bash
|  Critical     │ Command Injection                                            │
│ Package       │ nodemailer                                                   │
│ Patched in    │ >=6.4.16                                                     │
│ Dependency of │ ghost                                                        │
│ Path          │ ghost > nodemailer                                           │
│ More info     │ https://npmjs.com/advisories/1708                            |
```
Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

This is an upstream package; information on how to mitigate the issue is provided in the advisory. I expect that running `npm audit` would return 0 issues - and especially none marked critical.  

### Technical details:

* Ghost Version: 4.14.0
* Node Version: 12.22.6
* Browser/OS: n/a (issue affects all)
* Database: n/a (issue affects all)

**Comment by jkirkpatrick** [comment]
PR is WIP here: https://github.com/TryGhost/Ghost/pull/13301

**Comment by ErisDS** [comment]
Please follow our responsible disclosure guidelines when reporting vulnerabilitie

https://github.com/TryGhost/Ghost/security/policy

Most GitHub repos have these front and center.

As you can see, the problem is being worked on.

This issue will be deleted from our repo.
