### ISSUE TITLE
Support animated webp images

### ISSUE THREAD

**Issue by yaroslavvb** [TryGhost/Ghost#13319]
Animated webp become static when adding them to Ghost. To reproduce.

0. Create new post
1. drag animated webp (like [this](https://aws1.discourse-cdn.com/business4/uploads/ghost2/original/2X/e/e06710da861f0e7d91f383c9c9bfe755df18fac0.webp)), into editor
2. Click Preview

The preview webp is static (example [page](https://machine-learning-etc.ghost.io/p/0b4618c3-2989-4e8d-9f5c-0199b6a831ac/)). Related [discussion](https://forum.ghost.org/t/use-webp-images-for-posts/6710/20)

**Comment by uniqmuz** [comment]
It seems optimize when upload. It's 400k but it has 40k after upload.

**Comment by sideeffectdk** [comment]
+1
I've also bumped into the related discussion you linked. It seems to be related to the way Ghost uses the sharp image processing library when uploading images.

Adding options for how the imageOptimizer works would be handy as well. The sharp library seems very capable, and having options in the [ghost config file](https://ghost.org/docs/config/#image-optimisation) (or maybe even in the admin panel), where you could decide on compression ratio/quality, max size, output filetype, filter for exclusion of filetypes/image sizes smaller than x, keeping original, etc. would be nice.

**Comment by matthanley** [comment]
The animation is stripped by the sharp optimisation, which we don't want to skip right now. We'd be happy to review a PR that adds support for animated webp images while retaining optimisations for static images though.

For now, we've recently released native editor support for [inserting gifs](https://ghost.org/changelog/gifs/) into posts which is the best alternative.
