### ISSUE TITLE
Locking a Post to Multiple (BETA) Subscription Tiers makes post uneditable

### ISSUE THREAD

**Issue by OutpostRyan** [TryGhost/Ghost#13316]
Welcome 👋   
Please keep in mind that GitHub is our office. We invite you to share any bug reports here 🐛..  
For anything else please use https://forum.ghost.org 👫

### Issue Summary

Using the new beta Tiers feature, if you set access for a post to a number of tiers, the post becomes undeditable and you get the error message: "Validation error, cannot edit post. Value in [posts.visibility] exceeds maximum length of 50 characters. posts.visibility"

### To Reproduce

1. Create multiple subscription tiers
2. Create a new post
3. Restrict visibility of your new post to 3 or more tiers
4. Get error message

![image](https://user-images.githubusercontent.com/83042054/133707076-ef9b8777-ddf6-455e-826f-6d73d87817b0.png)

### Technical details:

* Ghost Version: 4.14
* Node Version:
* Browser/OS:
* Database:

**Comment by matthanley** [comment]
This has now been resolved 🎉

**Comment by sneko** [comment]
Just for record, I was trying to publish to specific tiers and was getting:
```
Validation error, cannot edit post. Value in [posts.email_recipient_filter] exceeds maximum length of 50 characters. posts.email_recipient_filter
```

It seems your fix in the last releases made it, it works after upgrading!
