### ISSUE TITLE
Membership Bug. Expired Members Still Permitted Access

### ISSUE THREAD

**Issue by rickdonato** [TryGhost/Ghost#13328]
Welcome 👋   
Please keep in mind that GitHub is our office. We invite you to share any bug reports here 🐛..  
For anything else please use https://forum.ghost.org 👫

### Issue Summary

Previously paid members that now do not have a paid subscription are still considered as a paid members and have full access to the paid content etc.

### To Reproduce

1. User subscribes to a paid membership.
2. They cancel their membership
3. After their subscription has expired for the time period. And no subscriptions are shown in the members / subscriptions section, then impersonate user.
4. You will now still be provided with full access.

Another way to see an issue is if you export all the paid members from Ghost you also get the previously paid members that are no longer paid members. 

### Technical details:

* Ghost Version: Version 4.11.0
* Node Version: TBC
* Browser/OS: All
* Database: mySQL

**Comment by prschulz** [comment]
Hi @rickdonato - Members will continue to have access for the remainder of the period that they paid for. This should be reflected in their subscription on the Member show page. 

![image](https://user-images.githubusercontent.com/4165449/134215165-e0e654df-f8e1-42fc-a1dc-36da23eeecde.png)

**Comment by rickdonato** [comment]
Thanks. But this isnt the case here. I have users that have exceeded their access until and still have access. 
For example, I have a user which had a monthly subscription expire on 21 July. I can impersonate their account and get access to all content. 
Their subscription shows empty. 
![image](https://user-images.githubusercontent.com/4304301/134231053-7ab36828-fd3d-4c98-9957-c2d32e11542d.png)
However, when export the paid users via the UI this user is included and also shows his customer_id.

This situation appears to be the same for all users that have an expired subscription! :-( 
Can you please assist?

**Comment by rickdonato** [comment]
I upgraded to 4.15.0. And this resolved the issue. Which is great. But cannot see anything in the releases about this as an issue. Might be worth updating folks about this problem. Thanks.
