### ISSUE TITLE
Security banner not being removed after successfull upgrade

### ISSUE THREAD

**Issue by tbhaxor** [TryGhost/Ghost#13366]
### Issue Summary

From the official documentation I have tried the forceful upgrade of ghost to latest version but even after successful upgrade, it's still showing the Upgrade banner in the ghost admin 

![image](https://user-images.githubusercontent.com/28386721/134810117-167ead4c-6b98-4e96-bacc-8333dfe447f1.png)

### To Reproduce

1. sudo -i -u ghost-mgr
2. cd /path/to/ghost
3. ghost update -f

### Technical details:

* Ghost Version:
* Node Version:
* Browser/OS:
* Database:

**Comment by justathoughtor2** [comment]
Yeah, a self-hosted instance that I manage is suffering from the same problem. We still have the security vulnerability warning present after upgrading (without force in our case) to 4.16.0.

**Comment by tbhaxor** [comment]
The banner is not a problem right now. I believe the team will fix it asap. I want to know whether my website is secure or not. If I manually have to fix some package, plz let me know

**Comment by gavranha** [comment]
same here, same latest version

**Comment by ErisDS** [comment]
The upgrade banner in Ghost admin is not currently being automatically dismissed. We realise that doesn't inspire confidence and are tracking getting that fixed ASAP.

In the meantime:

If `ghost -v` and/or the "What's new" page in Ghost admin say that you are on 4.15.1 or higher, then your site is patched and secure.

If you are on 4.15.1 or higher then you are safe to dismiss the banner by clicking the ✖️  on the right hand side.

**Comment by Kylotan** [comment]
> If `ghost -v` and/or the "What's new" page in Ghost admin say that you are on 4.15.1 or higher, then your site is patched and secure.
> 
> If you are on 4.15.1 or higher then you are safe to dismiss the banner by clicking the ✖️ on the right hand side.

I found that `ghost -v` doesn't always work - for example, I just get this output `Ghost-CLI version: 1.17.3` and nothing about Ghost itself.

Also, the "✖️ on the right hand side." isn't easy to see if you're in dark mode. Got it now though!

**Comment by ErisDS** [comment]
This bug was closed by https://github.com/naz/Ghost/commit/c0d59db5bee2643b8b1ab7ec36797be51f62b965
