### ISSUE TITLE
SVG Images are really small

### ISSUE THREAD

**Issue by mhansen** [TryGhost/Ghost#13422]
### Issue Summary

Chrome on macOS, this shows what it looks like when I add a PNG and a SVG image, the SVG is at the bottom:

![image](https://user-images.githubusercontent.com/105529/135701336-4f074b4c-7739-4d86-ade1-261011b99b95.png)

### To Reproduce

1. Add a /image with PNG: ![Profilepedia (3)](https://user-images.githubusercontent.com/105529/135701343-412c3c6f-ef2d-40b3-9ff8-d435cdc22ff9.png)
2. Add a /image with SVG (ungzip it first, I had to gzip it to attach)
[Profilepedia.svg.gz](https://github.com/TryGhost/Ghost/files/7270784/Profilepedia.svg.gz)

Expected: SVG scales to the right size, like it does in the WYSIWYG editor
Actual: what you get is a tiny image 300x92. Not sure why.

This is on markhansen.co.nz, forgot the name of the theme.

### Technical details:

* Ghost Version: Whatever Ghost(Pro) is running right now (I don't know how to find this, maybe add instructions to your github issue template?)

**Comment by mhansen** [comment]
I'd rather have smooth images on every resolution but this is pushing me to use PNG which will give me jagged text resizing. It's a shame.

**Comment by mhansen** [comment]
Theme is alto Version 1.0.0

**Comment by ErisDS** [comment]
Hi there! If you're having any issue with a **Ghost(Pro)** site, please drop us an email on support@ghost.org and we'll be more than happy to give you a hand directly :slight_smile:
