### ISSUE TITLE
Email Sending does not work in newer Version

### ISSUE THREAD

**Issue by antonstech** [TryGhost/Ghost#13440]
### Issue Summary

So i am trying to invite some people to my Blog and i cant send out any Emails because of `queryA EREFUSED smtp.web.de`

This is the Full Error:
`{"name":"Log","hostname":"vServer-5r6Z6","pid":2468556,"level":40,"msg":"Error sending email: Failed to send email. Reason: queryA EREFUSED smtp.web.de. Please check your email settings and resend the invitation.","time":"2021-10-04T15:23:37.235Z","v":0}
`

### Technical details:

* Ghost Version: 4.17.1
* Ghost-CLI version: 1.17.3
* Node Version: v14.18.0
* NPM Version: 6.14.15
* Browser/OS: Chrome 93.0.4577.99 via Vivaldi 4.2.2406.54 running on Windows 10
* Debian 11
* Database: MYSQL Ver 8.0.26 for Linux on x86_64

**Comment by antonstech** [comment]
I would not consider this a "support-request" because i have another Ghost installation running on Version 4.13 and there the Email sending works (1 to 1 same Settings)

**Comment by avimanyu786** [comment]
I've just updated to v4.17.1 and logins & signups via email seem to work fine. You're using web.de for SMTP. Perhaps the other installation uses a different SMTP service/configuration? Here are some related references that could help:

- [AWS SES Setup Correctly - Email Working but can’t invite staff](https://forum.ghost.org/t/aws-ses-setup-correctly-email-working-but-cant-invite-staff)

- [Why Ghost admin invitations are sent to some emails but not others?](https://forum.ghost.org/t/why-ghost-admin-invitations-are-sent-to-some-emails-but-not-others)

- [Error sending email!](https://forum.ghost.org/t/error-sending-email)

- [Team>Invite - Not sending email](https://forum.ghost.org/t/team-invite-not-sending-email)

**Comment by avimanyu786** [comment]
It indeed looks like your email settings are  incorrect somewhere. I just confirmed that staff email invitations are also working fine on our updated setup.

**Comment by antonstech** [comment]
@avimanyu786

**Comment by antonstech** [comment]
@avimanyu786 So i am running a Private VPS with no Restrictions so this shouldnt be the Problem
