### ISSUE TITLE
Redirect loop when trying to redirect from /foo.bar/ to /foo-bar/

### ISSUE THREAD

**Issue by mhansen** [TryGhost/Ghost#13547]
Hi there, in #13493 I reported that I wanted to capture traffic to https://www.markhansen.co.nz/scatter.fm/ (with a dot, not a dash), and it was suggested to use redirects.

So I made a redirects.yaml:
```
302:
  /scatter.fm/: /scatter-fm/
```

But this gives me a redirect loop from `/scatter-fm/` to `/scatter-fm/`: note the `location: /scatter-fm/` header and the `Request URL: https://www.markhansen.co.nz/scatter.fm/`.

![image](https://user-images.githubusercontent.com/105529/136650045-c88ef055-b76f-44bd-9d75-d761af48c1b2.png)

My guess is maybe the redirects engine is normalising the dots to dashes or vice versa somewhere? Not sure.

**Comment by mhansen** [comment]
The first redirects work fine:

- from /scatter.fm to /scatter.fm/
- from /scatter.fm/ to /scatter-fm/
- then it loops

**Comment by mhansen** [comment]
I have reverted it now but should be easy to reproduce. Try to redirect any blogpost URL from the dot.version to the dashed-version.

BTW when trying to upload an empty redirects file I got an error: can't read property 302 of undefined, so I had to upload this file to clear out the redirect:

```
302:
```

**Comment by vikaspotluri123** [comment]
I'm guessing your redirect is interpreted as a regex - can you try this: `/scatter\.fm/: /scatter-fm`

**Comment by mhansen** [comment]
d'oh. Thanks, that worked.
