### ISSUE TITLE
Remove "The team at X" from transactional emails

### ISSUE THREAD

**Issue by JohnONolan** [TryGhost/Ghost#13613]
Several site owners have complained about the language used in our transactional emails, which have a sign-off that reads:

```
The team at $site.title
```

This is a confusing message coming from solo-creators who have no team, and publish under their own name.

The sign-off is non-essential, so we'd like to just remove this line completely from the emails where it appears:

https://github.com/TryGhost/Ghost/search?q=%22The+team+at%22 

<img width="583" alt="CleanShot 2021-10-15 at 14 47 38@2x" src="https://user-images.githubusercontent.com/120485/137537614-4ae4115f-84a4-44e5-af7c-c1e95ff72bfa.png">

**Comment by fcoiuri** [comment]
Hi, can I work on this issue?

**Comment by Sen-442b** [comment]
Though I haven't been assigned this issue but I submitted a pull request regardless, kindly consider checking that out .

**Comment by joemcgee4151986** [comment]
Mind if I can work on this?
