### ISSUE TITLE
KBD tag colors are incorrect when switching to dark mode

### ISSUE THREAD

**Issue by artemkovalyov** [TryGhost/Ghost#13616]
### Issue Summary

KBD macro doesn't look correct with inverse colors (dark mode)

### To Reproduce

1. Switch to dark mode in admin
2. Add MD snippet with <kbd> tag
3. Here's how it looks like
![image](https://user-images.githubusercontent.com/10460752/137622223-3fb668fb-536c-440b-86a0-f1ac1eeb9aa3.png)

### Technical details:

* Ghost Version: irrelevant for CSS issue
* Node Version: irrelevant for CSS issue
* Browser/OS: Chrome
* Database: irrelevant for CSS issue

**Comment by jyoung0519** [comment]
Hi @ErisDS  we'd like to give it a try to resolve this bug! We are a group of students currently in a software course, and were assigned a task of help contributing to an open-source project!

**Comment by danimajo** [comment]
I tried to reproduce this, but failed. Could you please explain each step to reproduce this behavior?

**Comment by justin-carver** [comment]
Was able to reproduce this following these steps:

1. Install Ghost
2. Select night-shift toggle on bottom-left of home page after account creation.
3. Create post, enter markdown block, begin `<kbd>` tag.
4. `<kbd>` tag unfortunately has `ghost-dark...` css color property set to: `#e8ebed`, should be something darker, like `#394047`, which is default for light theme.

Was able to correct issue locally via inspector, but unsure on how `ghost-dark-485081d359d3ce1412ccd09a8f5b83d9.css` is generated.

**Comment by danimajo** [comment]
I fixed this in admin - Here is the PR: https://github.com/TryGhost/Admin/pull/2176

**Comment by moreofmorris** [comment]
Thanks for this @danimajo! This has now been merged into main. https://github.com/TryGhost/Admin/commit/8591f893bc27cbdffdb88e2e7d9ac37a0bb86ffc
