### ISSUE TITLE
[GDPR] Unecessary Twitter scripts added to tweet embeds

### ISSUE THREAD

**Issue by kuba-orlik** [TryGhost/Ghost#13631]
### Issue Summary

When pasting a link to a tweet, Ghost editor creates an embedded version of that tweet.

That unfortunately causes Twitter JS scripts to be added to the page with that embed, sending PII to Twitter, which is against GDPR unless there's a valid consent for that.

Because of that, we had to remove all Twitter embeds from all our articles.

The embed should be static and not include any scripts.

### To Reproduce

1. Create an article with an embedded tweet by pasting a link to that tweet into the content of the article
2. Publish or preview the article
3. See in Network Inspector that Twitter scripts are loaded and some PII (id from cookies) is sent to Twitter

This is a problem because such processing of PII requires getting a valid consent and can become an unexpected trouble for admins who didn't know that Ghost doesn't just grab the tweet content, but also loads Twitter scripts and who didn't put it in their privacy policy and in their consent framework.

### Technical details:

* Ghost Version: 3.42.6
* Node Version: v12.22.6
* Browser/OS: node
* Database: sqlite

**Comment by ErisDS** [comment]
Ghost embeds use the oembed standard, therefore we are presenting Twitter embeds the way Twitter intends them to be presented.

Ghost does not set any cookies for Twitter. Twitter can only interact with its own cookies.

We've developed Ghost such that it can be used in a GDPR-compliant way, however anyone using Ghost will want to make their own decisions and should take the advice of their own legal teams where necessary.

**Comment by kuba-orlik** [comment]
> Ghost does not set any cookies for Twitter. Twitter can only interact with its own cookies.

That's true, although this kind of data processing is not GDPR compliant. See [Judgement of the EU Court in Case C‑40/17](https://curia.europa.eu/juris/document/document.jsf?text=&docid=216555&pageIndex=0&doclang=EN&mode=lst&dir=&occ=first&part=1&cid=1254905), aka "Fashion ID", which shows that even embedding a "like" button makes the website admin responsible for properly gathering consent.

So that makes it extremely easy for someone to make the website accidentally not GDPR-compliant.
