### ISSUE TITLE
Hey, I could clean up all of the 'or' statements similar to this one if you'd like?

### ISSUE THREAD

**Issue by VanillaSpoon** [TryGhost/Ghost#13646]
###### Hey, not sure if this would be of interest but:

https://github.com/TryGhost/Ghost/blob/28283b54acd7f3797ed3e0b854d0aea993f0f584/core/frontend/meta/twitter-image.js#L15

```diff
-  if (_.includes(context, 'post') || _.includes(context, 'page') || _.includes(context, 'amp')) { 
+  if (['post','page','amp'].some(one => _.includes(context, one))) {
```

**Comment by ErisDS** [comment]
Thank you for the offer, although I think this kind of change is very subjective. 

If you'd like to discuss contributing to Ghost there is a section on the forum for this: https://forum.ghost.org/c/contributing/27, There is much work that we'd love to have help with, and you'll see those tasks marked `help wanted` here in GitHub.
