### ISSUE TITLE
Add ability to filter posts with partial matches

### ISSUE THREAD

**Issue by peledies** [TryGhost/Ghost#13702]
### Issue Summary
As per the documentation on the Ghost API:
NQL does not support filtering base on `like` or `partial matches` yet.
https://ghost.org/docs/content-api/#filtering

Is there any indication as to when this functionality will be added?

We are trying to switch from wordpress to ghost and this is the only blocker for us at the moment :(

**Comment by jesders** [comment]
This is very much needed for us as well.
