### ISSUE TITLE
Error due to asset file permissions when booting

### ISSUE THREAD

**Issue by Lastofthefirst** [TryGhost/Ghost#13739]
### Issue Summary

DO one click did not work. ghost doesnt start, web page shows 502 bad gateway.

### Steps to Reproduce

1. start digital ocean one click droplet
2. enter url and email

### Ghost Version

current

### Node.js Version

current

### How did you install Ghost?

DO one click

### Database type

MySQL 8

### Relevant log / error output

```shell
Message: Ghost was able to start, but errored during boot with: EACCES: permission denied, open '/var/www/ghost/versions/4.22.2/core/frontend/public/cards.min.css'
Suggestion: journalctl -u ghost_letters-shoghi-cc -n 50

Debug Information:
    OS: Ubuntu, v20.04.3 LTS
    Node Version: v14.18.1
    Ghost Version: 4.22.2
    Ghost-CLI Version: 1.18.0
    Environment: production
    Command: 'ghost start'

Additional log info available in: /home/ghost-mgr/.ghost/logs/ghost-cli-debug-2021-11-12T19_20_14_361Z.log
Message: Ghost was able to start, but errored during boot with: EACCES: permission denied, open '/var/www/ghost/versions/4.22.2/core/frontend/public/cards.min.css'
Suggestion: journalctl -u ghost_letters-shoghi-cc -n 50

Debug Information:
    OS: Ubuntu, v20.04.3 LTS
    Node Version: v14.18.1
    Ghost Version: 4.22.2
    Ghost-CLI Version: 1.18.0
    Environment: production
    Command: 'ghost start'

Additional log info available in: /home/ghost-mgr/.ghost/logs/ghost-cli-debug-2021-11-12T19_20_14_361Z.log


 /home/ghost-mgr/.ghost/logs/ghost-cli-debug-2021-11-12T19_20_14_361Z.log
Debug Information:
    OS: Ubuntu, v20.04.3 LTS
    Node Version: v14.18.1
    Ghost Version: 4.22.2
    Ghost-CLI Version: 1.18.0
    Environment: production
    Command: 'ghost start'
Message: Ghost was able to start, but errored during boot with: EACCES: permission denied, open '/var/www/ghost/versions/4.22.2/core/frontend/public/cards.min.css'
Suggestion: journalctl -u ghost_letters-shoghi-cc -n 50
Stack: Error: Ghost was able to start, but errored during boot with: EACCES: permission denied, open '/var/www/ghost/versions/4.22.2/core/frontend/public/cards.min.css'
    at Server.<anonymous> (/usr/lib/node_modules/ghost-cli/lib/utils/port-polling.js:73:28)
    at Object.onceWrapper (events.js:519:28)
    at Server.emit (events.js:400:28)
    at emitCloseNT (net.js:1677:8)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
```

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by luvncoco** [comment]
same for me, on the exact same file, was trying a second dropplet and i have the same issue

**Comment by mrtrombley** [comment]
Same here, unable to upgrade from 4.22.1 because of this issue

**Comment by ceylon23** [comment]
I'm also having this same issue. I started from 4.18.0 and updated each minor version and subversion all the way to 4.22.1. Each time I installed a new version I tried to force update to 4.22.2 and each time I got the same error and had to roll back.

**Comment by Lastofthefirst** [comment]
The same issue occurs when you try to install manually following installation instructions in docs.

**Comment by katoitalia** [comment]
same here, haven't seen ghost failing this spectacularly in a very long time

**Comment by Lastofthefirst** [comment]
Is there a way to force a fresh installation to 4.18.0? 😁

**Comment by katoitalia** [comment]
`/path/to/ghost/versions/4.22.2/core/frontend/public/cards.min.css`

doesn't even exist

**Comment by ceylon23** [comment]
> Is there a way to force a fresh installation to 4.18.0? 😁

I do not think there is a downgrade option for the ghost-cli command. There is only a rollback option to previous install. If you wanted to do a clean install you could use the ghost-cli command: ghost install 4.18.0

**Comment by katoitalia** [comment]
> > Is there a way to force a fresh installation to 4.18.0? 😁
> 
> I do not think there is a downgrade option for the ghost-cli command. There is only a rollback option to previous install. If you wanted to do a clean install you could use the ghost-cli command: ghost install 4.18.0

that probably should be added in cases like this.....this is gonna impact hundreds of thousands of blogs in the next few hours if not fixed quickly and a downgrade option would mitigate this kind of issues in the future

**Comment by katoitalia** [comment]
I would also like to point out that timing is perfect: friday night
this is [r/ProgrammerHumor](https://www.reddit.com/r/ProgrammerHumor/comments/qi7wlt/deploy_on_a_friday_itll_be_fine_they_said/) material

**Comment by yannickcof** [comment]
Same here !!!

**Comment by daniellockyer** [comment]
Hey all 👋🏻 Apologies for the bug. 4.22.2 has been deprecated in NPM so Ghost-CLI shouldn't update to it.

If you're already on 4.22.2 and stuck, you should be able to run `ghost update --force` to re-download 4.22.1 and switch to that version.

**Comment by jackdanielux** [comment]
That's why all DO people, keep 2 working snapshots (images) of the droplet :)

**Comment by ErisDS** [comment]
4.22.3 has a fix so this issue won't prevent Ghost from booting. Further fixes are coming. 

Some clarity on the commands because there seems to be some confusion:

If you upgrade Ghost and it doesn't work, `ghost update --rollback` will take you safely back to the last working version. 

If you're installing Ghost and it fails, then you don't have a previous version to rollback to and therefore a fresh install is required. The install command can target a specific version.

Once we spot the issue and deprecate the broken version, then `ghost update --force` will work in both scenarios. 

We're working on making sure the docs around this are clear, but this is not a common occurrence that we optimise for 😬
