### ISSUE TITLE
Editor area doesn't follow CMD+Backspace behavior on MacOS

### ISSUE THREAD

**Issue by olehomelchenko** [TryGhost/Ghost#13748]
### Issue Summary

On MacOS, I have a habit of using  CMD+Backspace keyboard shortcut whenever I want to delete a whole line of text in the editor up to the beginning of the line. 

As far as I know, this is a default behavior in any edit field in any app that I use on MacOS. 

However, in Ghost editor mode, when I press CMD+Backspace, only the last character gets deleted. 

This behavior can be observed in latest versions Chrome and Firefox

### Steps to Reproduce

1. In the Ghost Posts admin page, click on "New Post" plus sign
2. Focus on "post body" area below "Post Title" input
3. Enter several letters or words in the area.
4. Press CMD+Backspace

Expected behavior: whole text in current line gets deleted
Actual behavior: only the last character gets deleted

https://user-images.githubusercontent.com/79406976/141865287-e3cf02f6-8b30-47a9-ac84-5353916933ed.mp4

### Ghost Version

1.18.0

### Node.js Version

14.18.1

### How did you install Ghost?

Via the CLI on Ubuntu (DigitalOcean)

### Database type

MySQL 8

### Browser & OS version

Chrome 95.0.4638.69, Firefox 94.0.1

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by ErisDS** [comment]
Hi there 👋 

This is an upstream issue in [mobiledoc-kit](https://github.com/bustle/mobiledoc-kit). 

There's quite an old spike into getting it working here: https://github.com/bustle/mobiledoc-kit/pull/636

PRS resolving this issue would be very welcome :)
