### ISSUE TITLE
Handlebars can't handle nested <a> tags

### ISSUE THREAD

**Issue by snird** [TryGhost/Ghost#13756]
### Issue Summary

If I have an <a> tag that has another <a> within it, in a theme, handlebars duplicate the first <a> under every nested tag.

### Steps to Reproduce

So for example if I have:
```
<a href="1">
  <div class="hello">
     <div class="wow">
        <a href="2">try</a>
    </div>
  </div>
</a>
```

the output will be:
```
<a href="1">
  <div class="hello">
    <a href="1">
       <div class="wow">
          <a href="1">
            <a href="2">try</a>
          </a>
      </div>
    </a>
  </div>
</a>
```

### Ghost Version

4.22

### Node.js Version

14

### How did you install Ghost?

managed

### Database type

MySQL 5.7

### Browser & OS version

any

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by kevinansfield** [comment]
Nested anchor tags are not valid HTML. There’s no right/wrong/expected output in this case because you’re trying to do something that isn’t allowed within the HTML specification with no defined behaviour for when the spec is broken.

https://html.spec.whatwg.org/multipage/text-level-semantics.html#the-a-element

> Content model:
> Transparent, but there must be no interactive content descendant, a element descendant, or descendant with the tabindex attribute specified.

> The a element can be wrapped around entire paragraphs, lists, tables, and so forth, even entire sections, so long as there is no interactive content within (e.g., buttons or other links).
