### ISSUE TITLE
Cannot activate default theme Casper after activating another theme

### ISSUE THREAD

**Issue by hyvyys** [TryGhost/Ghost#13761]
### Issue Summary

Cannot activate default theme Casper after installing another theme from zip. I see an error popup saying:

```
Install theme

Casper failed to install.

Supplied GitHub theme does not exist or is inaccessible
```

Changing to any other theme from the listed ones works fine.

### Steps to Reproduce

1. Install ghost locally.
2. Change theme (either to one of the default ones or from zip).
3. Try changing back to Casper.

### Ghost Version

4.22.3

### Node.js Version

16.13.0

### How did you install Ghost?

npm, macOS Big Sur (M1)

### Database type

SQLite3

### Browser & OS version

Brave, macOS Big Sur

### Relevant log / error output

```shell
Install theme

Casper failed to install.

Supplied GitHub theme does not exist or is inaccessible
```

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by matthanley** [comment]
Hey @hyvyys! Thanks for the report. This is already fixed in https://github.com/TryGhost/Admin/commit/2373d3c8acd59bd47cea47446af197a0f71e75cd, which will be in the next release (tomorrow).

**Comment by matthanley** [comment]
ℹ️ The workaround until the next release is to activate Casper from the "Advanced" theme table dropdown.

<img width="968" alt="image" src="https://user-images.githubusercontent.com/3798302/142417512-9eedf486-b6c3-4bfa-aa81-1d12913ac518.png">
