### ISSUE TITLE
Redirects Error

### ISSUE THREAD

**Issue by rkafp** [TryGhost/Ghost#13813]
### Issue Summary

URL redirects doesn't work properly if it has a structure like this

`/category/article/`
or 
`/category/subcategory/article/`

------------------------------------------------
If You want to redirect the URL:
`/article/` to `/category/subcategory/article/`
or
`/article/` to `/category/article/`

the system will loop, so that it gives the wrong address which result is:

/category/subcategory/category/subcategory/category/subcategory/category/subcategory/category/subcategory/category/subcategory/category/subcategory/category/subcategory/category/subcategory/category/subcategory/category/subcategory/category/subcategory/category/subcategory/category/subcategory/category/subcategory/category/subcategory/category/subcategory/category/subcategory/category/subcategory/category/subcategory/category/subcategory/category/subcategory/category/subcategory/category/subcategory/category/subcategory/category/subcategory/category/subcategory/category/subcategory/category/subcategory/category/subcategory/category/subcategory/category/subcategory/category/subcategory/category/subcategory/category/subcategory/category/subcategory/category/subcategory/category/subcategory/article/

------------------------------------------------
However, if You change part of the old address on the new address to a different one, there will be no error:
`/article/` to `/category/subcategory/articlenew/`
or
`/article/` to `/category/articlenew/`

This bug happens on 301 and 302 redirects!

### YAML

1. Create redirects.yaml file
2. Write

```
301:
  /article/: /category/subcategory/article/

302:
  /post/: /category/subcategory/post/
```
  
  3. Save
  
  
### JSON

1. Create redirects.json file
2. Write

```
[
{
    "from": "/article/",
    "to": "/category/subcategory/article/",
    "permanent": true
},
{
    "from": "/post/",
    "to": "/category/subcategory/post/",
    "permanent": false
}
]
```

3. Save

### Ghost Version

4.20.4

### Node.js Version

v14.17.0

### How did you install Ghost?

Nginx - Ubuntu

### Database type

MySQL 8

### Browser & OS version

Windows 10

### Relevant log / error output

```shell
/category/subcategory/category/subcategory/category/subcategory/category/subcategory/category/subcategory/category/subcategory/category/subcategory/category/subcategory/category/subcategory/category/subcategory/category/subcategory/category/subcategory/category/subcategory/category/subcategory/category/subcategory/category/subcategory/category/subcategory/category/subcategory/category/subcategory/category/subcategory/category/subcategory/category/subcategory/category/subcategory/category/subcategory/category/subcategory/category/subcategory/category/subcategory/category/subcategory/category/subcategory/category/subcategory/category/subcategory/category/subcategory/category/subcategory/category/subcategory/category/subcategory/category/subcategory/category/subcategory/category/subcategory/post/
```

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by matthanley** [comment]
@rkafp this isn't a bug - you just need to use regular expressions to define your redirects as documented [here](https://ghost.org/docs/tutorials/implementing-redirects/#using-regular-expressions).
