### ISSUE TITLE
Add an option to ghost CLI to refactor unused image

### ISSUE THREAD

**Issue by tbhaxor** [TryGhost/Ghost#13810]
_Originally posted by @ErisDS in https://github.com/TryGhost/Ghost/issues/4311#issuecomment-59792273_

I see the images are not getting deleted when you delete them from the POST. There should be some feature in the CLI to find the unused images in the POST and allow us to delete them to free space. In my blog images folder is taking around 1 GB space which is a lot for 47 posts

**Comment by Maxszik** [comment]
@tbhaxor I just want to let you know there's another solution if you need to delete unused images: [ghost-purge-images](https://github.com/ghostboard/ghost-purge-images)
