### ISSUE TITLE
Ghost downgrade?

### ISSUE THREAD

**Issue by snird** [TryGhost/Ghost#13840]
### Issue Summary

Version 4.25.1 is broken. It's the weekend, and there is no easy way to go back to 4.25.0.
As long as previous versions doesn't have db migrations, maybe we should be able to downgrade?

### Steps to Reproduce

Do "ghost update" on a version released on the weekend

### Ghost Version

4.25.1

### Node.js Version

14

### How did you install Ghost?

ubuntu at DO

### Database type

MySQL 8

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by snird** [comment]
To get around the CLI stopping you from "downgrading" by `ghost update 4.25.0` (when you are at a broken 4.25.1 for example)
What can be done is to edit the `update.js` file on the GhostCLI directly:
`sudo nano /usr/lib/node_modules/ghost-cli/lib/commands/update.js`
then change the line here: https://github.com/TryGhost/Ghost-CLI/blob/56f9b6fb6f9da881ccc5d9fc32ca4850d84d33d5/packages/ghost-cli/lib/commands/update.js#L44
to be something like:
`activeVersion: "4.24.0"`
to trick the system to allow you to "update" to older version.

Not recommended obviously, but having your site down is even less recommended. So use as needed.

**Comment by philheijkoop** [comment]
From a fresh install (no db migrations) that suffered from #13837 , this allows me to "downgrade" the version, and no errors return for `ghost doctor`, but site is still down.

**Comment by daniellockyer** [comment]
Please see https://github.com/TryGhost/Ghost/issues/13837#issuecomment-986544022 for instructions for the issue this relates to. We'll be reviewing tooling and documentation on rollbacks shortly 🙂
