### ISSUE TITLE
Slugify heading IDs instead of escaping?

### ISSUE THREAD

**Issue by nag** [TryGhost/Ghost#13876]
### Issue Summary

This is how the IDs look now in Cyrillic (russian):

![image](https://user-images.githubusercontent.com/35629662/145660197-8f6f25e8-4bc7-446b-9f53-45e63f7f0d6a.png)

They should look something like this:

![image](https://user-images.githubusercontent.com/35629662/145660270-0c0bfe43-0fd7-45ef-b758-d9c224e1a6da.png)

Is this the correct behavior? I expected IDs to be generated in the same way as slugs.

### Steps to Reproduce

1. Create a heading with non-latin text.
2. Check the generated heading ID.

### Ghost Version

4.27.2

### Node.js Version

16.13.1

### How did you install Ghost?

ghost install local

### Database type

SQLite3

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by matthanley** [comment]
Hey @nag - this behaviour is [by design](https://github.com/TryGhost/Koenig/commit/5f0c2fb8bc22042caf9948781ccc26d003e22533), so that
> links or urls are displayed by browsers they will appear as native characters

**Comment by testtest0121** [comment]
> Hey @nag - this behaviour is [by design](https://github.com/TryGhost/Koenig/commit/5f0c2fb8bc22042caf9948781ccc26d003e22533), so that
> 
> > when links or urls are displayed by browsers they will appear as native characters

I can confirm this issue. While using accented characters I get some ugly IDs which break the use of for example a TOC.

Looking at ? for example, they are actually removed from the generated IDs but not ¿¡!= %C2%A1%C2%BF

Why not keep it like the Post Url slugs? All special characters are removed and accented ones are turned into A-Z, a-z.

It's been almost a decade and Ghost's still lacking in multilingual support compared to WP.
