### ISSUE TITLE
Global css setting causes problems for new cards

### ISSUE THREAD

**Issue by fueko** [TryGhost/Ghost#13874]
### Issue Summary

New cards like NFT, for example, use the global setting (present in official Ghost themes):

```
* {
    box-sizing: border-box;
}
```

However, not all themes have this setting defined, which causes content problems:

![Zrzut ekranu 2021-12-10 o 13 26 12](https://user-images.githubusercontent.com/23366922/145574672-2557474f-64e6-4c68-9161-b8137ca6a315.png)

A solution could be to add code but only for editor cards:

```
.kg-card,
.kg-card * {
    box-sizing: border-box;
}
```

### Steps to Reproduce

New cards should have as much compatibility with themes as possible, so it's better not to use global settings.

### Ghost Version

4.27.1

### Node.js Version

16.13.0

### How did you install Ghost?

localhost

### Database type

SQLite3

### Browser & OS version

All

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by peterzimon** [comment]
Fixed with https://github.com/TryGhost/Ghost/commit/25748f420ce60a4fd498df58a2834293b015a2b5
