### ISSUE TITLE
Can't install a ghost instance

### ISSUE THREAD

**Issue by vednig** [TryGhost/Ghost#13882]
### Issue Summary

Running 'ghost install local' causes error
OS: Debian 11/Raspberry Pi OS and Windows 10
### Steps to Reproduce

After installing ghost-cli via npm
run ghost install local

### Ghost Version

1.18.1

### Node.js Version

16.13.x / 14.7.1

### How did you install Ghost?

Windows 10 and  Linux

### Database type

SQLite3

### Relevant log / error output

<details>Debug Information:
    OS: Microsoft Windows 10 Pro, v10.0.19043
    Node Version: v16.13.0
    Ghost-CLI Version: 1.18.1
    Environment: development
    Command: 'ghost install local'
Message: spawn yarn ENOENT
Exit code: ENOENT

--------------- stdout ---------------
yarn install v1.22.15
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info If you think this is a bug, please open a bug report with the information provided in "E:\\blog-rug\\versions\\4.28.0\\yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
info There appears to be trouble with your network connection. Retrying...

--------------- stderr ---------------
warning ghost@4.28.0: The engine "cli" appears to be invalid.
warning Resolution field "moment@2.24.0" is incompatible with requested version "moment@^2.29.1"
warning Resolution field "moment-timezone@0.5.23" is incompatible with requested version "moment-timezone@^0.5.33"
warning Resolution field "@tryghost/logging@2.0.0" is incompatible with requested version "@tryghost/logging@^1.0.2"
warning Resolution field "@tryghost/logging@2.0.0" is incompatible with requested version "@tryghost/logging@^1.0.2"
warning Resolution field "moment@2.24.0" is incompatible with requested version "moment@^2.29.1"
warning Resolution field "@tryghost/logging@2.0.0" is incompatible with requested version "@tryghost/logging@^1.0.2"
warning Resolution field "moment@2.24.0" is incompatible with requested version "moment@^2.27.0"
warning Resolution field "moment-timezone@0.5.23" is incompatible with requested version "moment-timezone@^0.5.31"
warning Lockfile has incorrect entry for "@tryghost/logging@1.0.2". Ignoring it.
warning Resolution field "@tryghost/logging@2.0.0" is incompatible with requested version "@tryghost/logging@^1.0.0"
warning Resolution field "moment@2.24.0" is incompatible with requested version "moment@2.27.0"
warning Resolution field "moment@2.24.0" is incompatible with requested version "moment@2.27.0"
warning Resolution field "@tryghost/logging@2.0.0" is incompatible with requested version "@tryghost/logging@1.0.2"
warning Resolution field "@tryghost/logging@2.0.0" is incompatible with requested version "@tryghost/logging@^1.0.0"
warning Resolution field "moment@2.24.0" is incompatible with requested version "moment@^2.29.1"
error An unexpected error occurred: "https://registry.npmjs.org/date-fns/-/date-fns-2.27.0.tgz: ESOCKETTIMEDOUT".
</details>

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by daniellockyer** [comment]
Hey @vednig! 👋🏻 The logs you've pasted seem to show it's an internet connection issue. Can you check your internet and try `ping registry.npmjs.org`?

Closing as this is not a issue with Ghost 🙂
