### ISSUE TITLE
Audio file duration missing digit in editor

### ISSUE THREAD

**Issue by stromfeldt** [TryGhost/Ghost#13894]
### Issue Summary

Although the length of a particular audio file appears correct in the preview of a post:
<img width="761" alt="Screen Shot 2021-12-15 at 6 10 58 pm" src="https://user-images.githubusercontent.com/27488257/146140685-9649aea6-95ef-4a1d-83e0-d3069a4a601b.png">

When looking at the audio card of that same audio file in the editor it is missing the first digit in the seconds column, in this case the zero:
<img width="761" alt="Screen Shot 2021-12-15 at 6 11 19 pm" src="https://user-images.githubusercontent.com/27488257/146140804-e4ee23cb-db28-4022-84c4-4c33b2b05ca6.png">

Although I presume the issue is that the zero is not displayed because it's "null" (for lack of a better word), I have not tested this issue with audio files whose length in the seconds column is greater than 9 seconds.

### Steps to Reproduce

1. Create an audio card with an audio file whose length in the seconds column is less than 10 seconds.
2. See that the zero is missing while in the editor.

### Ghost Version

4.29.0

### Node.js Version

14.18.1

### How did you install Ghost?

Linode, via CLI

### Database type

MySQL 5.7

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by daniellockyer** [comment]
Hey @stromfeldt! 👋🏻 This was fixed and released in v4.31.0 🙂
