### ISSUE TITLE
Admin API feature_image_alt in posts not working as expected

### ISSUE THREAD

**Issue by sampathcredid** [TryGhost/Ghost#13905]
### Issue Summary

<img width="202" alt="Screenshot 2021-12-16 at 7 56 41 PM" src="https://user-images.githubusercontent.com/96100760/146390483-9bca5f48-e7cf-4bb6-8d08-810e90a38d34.png">

Can't set or read feature_image_alt on admin API.
when set it from admin API it return an error 
 status: 422,
    statusText: 'Unprocessable Entity',

### Steps to Reproduce

Just set feature_image_alt. on post object and send, or get a post with alt text, it not come in response.

### Ghost Version

Ghost-CLI version: 1.18.0 | Ghost version: 4.31.0

### Node.js Version

v16.13.0

### How did you install Ghost?

Cento OS using Ghost CLI

### Database type

MySQL 8

### Relevant log / error output

```shell
status: 422,
    statusText: 'Unprocessable Entity',
```

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by ErisDS** [comment]
The Ghost editor uses the Admin API to set the feature image alt and it is working just fine. Therefore this must be an issue with your code. Please provide the full reproduction steps for how you are setting the value & sending it to the server... the more code and details the better.

**Comment by luckymayokashi** [comment]
Hello! I am going to hijack this post a bit and also include some more details as I am running into the same issue. 

I am using the out-of-the-box content-api in a NextJS project, using it as a headless API. Here are the steps I am going through. 


```
import GhostContentAPI from "@tryghost/content-api";

const api = new GhostContentAPI({
  url: "https://myblog.ghost.io",
  key: "GHOST_KEY",
  version: "v3",
});
```

This is the function that I am using to grab the content from the API for blog post pages. 

```
export async function getSinglePost(slug) {
  return await api.posts
    .browse({
      include: "tags,authors,feature_image_alt,feature_image_caption",
      filter: `slug:${slug}`,
    })
    .catch((err) => {
      console.error(err);
    });
}
```

This is the function I'm using within getStaticProps to make the call, and then I am passing it as a prop. 

```
const post = await getSinglePost(context.params.postSlug);
```

Then just console logging props. 

I tried with and without the specific includes, with the same result as the initial issue. It's just not returning those values at all. 


```
email_subject: null
excerpt: "EXCERPT"
feature_image: "LINK"
featured: false
frontmatter: null
```

Hope this helps, I just launched this blog and I don't want Google to bash me for no alt tags. 

Love Ghost tho! Hope this helps.

**Comment by matthanley** [comment]
Hey @luckymayokashi - the fields referenced in the original issue above aren't available in the `v3` API - updating your code to use the `v4` API version should fix it for you.

**Comment by luckymayokashi** [comment]
@matthanley Ah, and just like that, it's working. Should have checked that first. Thank you for the help!
