### ISSUE TITLE
unable to upload/add new video card

### ISSUE THREAD

**Issue by yannickcof** [TryGhost/Ghost#13913]
### Issue Summary

.../unable to upload/add new video card

### Steps to Reproduce

since 4.30.0

### Ghost Version

4.32.0

### Node.js Version

14.18.2

### How did you install Ghost?

linux

### Database type

Other

### Relevant log / error output

```shell
none!!!
```

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by matthanley** [comment]
Hey @yannickcof - I've been unable to reproduce this issue with the few details you've given. Feel free to comment with a full reproduction case on a fresh install.
