### ISSUE TITLE
Error while executing migration 01-add-oauth-user-data.js

### ISSUE THREAD

**Issue by DevSchmidtchen** [TryGhost/Ghost#13916]
### Issue Summary

I wanted to update my Ghost installation from version 4.10.0 to the latest version (4.32.0). Doing that I encountered an issue with the database migration (`01-add-oauth-user-data.js`), which says `Referencing column 'user_id' and referenced column 'id' in foreign key constraint 'oauth_user_id_foreign' are incompatible`. The error also occurred when trying to update to version 4.11.0.

### Steps to Reproduce

1. Run `ghost update` (using 4.10.0) ➙ should work normally

### Ghost Version

4.10.0

### Node.js Version

12.22.6

### How did you install Ghost?

DigitalOcean Droplet

### Database type

MySQL 8

### Relevant log / error output

```shell
✖ Restarting Ghost
A GhostError occurred.

Message: Ghost was able to start, but errored during boot with: alter table `oauth` add constraint `oauth_user_id_foreign` foreign key (`user_id`) references `users` (`id`) - UNKNOWN_CODE_PLEASE_REPORT: Referencing column 'user_id' and referenced column 'id' in foreign key constraint 'oauth_user_id_foreign' are incompatible.
Help: Error occurred while executing the following migration: 01-add-oauth-user-data.js
Suggestion: journalctl -u ghost_blog-artistconnect-de -n 50

Debug Information:
    OS: Ubuntu, v20.04.3 LTS
    Node Version: v12.22.6
    Ghost Version: 4.32.0
    Ghost-CLI Version: 1.18.1
    Environment: production
    Command: 'ghost update'
```

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by matthanley** [comment]
Hey @DevSchmidtchen - see [this comment](https://github.com/TryGhost/Ghost/issues/13426#issuecomment-966264799) for the resolution.
