### ISSUE TITLE
Gateway timeout (504) when signing up using an offer

### ISSUE THREAD

**Issue by pesla** [TryGhost/Ghost#13918]
### Issue Summary

Whenever a user signs up using an offer, the endpoint `members/api/create-stripe-checkout-session` times out (`504` response code). The user is presented with a generic error message (`Failed to sign up, please try again`).

We’re running Ghost `4.27.2` on a Digital Ocean droplet (`Ubuntu 18.04.4 LTS`). The following payload is posted to the API endpoint mentioned above:

```json
{
  "priceId": null,
  "offerId": "61c0b237d76bd63633c9c78b",
  "identity": null,
  "metadata": {
    "name": "Peter",
    "requestSrc": "portal"
  },
  "cancelUrl": "https://bitcoinalpha.nl/?stripe=cancel",
  "customerEmail": "peter@gmail.com"
}
```

Chrome inspector shows request as `pending` until nginx (`1.14.0`) kills the request with a `504 Gateway Time-out`. Ghost logs the request as successful, see `INFO` line included.

### Steps to Reproduce

1. Open [this page](https://bitcoinalpha.nl/alphakerst21) 
2. Enter details
3. Click `Continue`
4. After 60 seconds the request times out

### Ghost Version

4.27.2

### Node.js Version

4.17.2

### How did you install Ghost?

Digital Ocean droplet, Ubuntu 18.04.4 LTS

### Database type

MySQL 5.7

### Relevant log / error output

```shell
# INFO line in log when 504 triggers
[2021-12-20 20:35:25] INFO "POST /members/api/create-stripe-checkout-session/" 200 60004ms
```

### Code of Conduct

- [x] I agree to be friendly and polite to people in this repository

**Comment by wildan3105** [comment]
Hi, I'm experiencing the same here. But after trying your link, apparently it's resolved? Can you share what you did to resolve that please @pesla ? Thanks a bunch!
