### ISSUE TITLE
Product Card bug

### ISSUE THREAD

**Issue by ever-blogger** [TryGhost/Ghost#13915]
### Issue Summary

Browser crush when exit from Product card

### Steps to Reproduce

1. Call product card
2. Exit exit product card edit

### Ghost Version

Latest 4.32

### Node.js Version

Latest

### How did you install Ghost?

Digital Ocean one click install

### Database type

MySQL 8

### Browser & OS version

Firefox windows 11

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by matthanley** [comment]
Hey @ever-blogger - I've been unable to reproduce this issue. Please add a more detailed reproduction case so we can investigate further.

**Comment by ever-blogger** [comment]
I also couldn't reproduce the same issue from my end recently, maybe it has fixed after several updates.
