### ISSUE TITLE
AMP: Google Search Console > AMP page is invalid

### ISSUE THREAD

**Issue by jorisbontje** [TryGhost/Ghost#13914]
### Issue Summary

Google Search Console reports

**AMP page is invalid**
**It won't appear in Google Search results.**

<img width="774" alt="Screenshot 2021-12-19 at 17 13 10" src="https://user-images.githubusercontent.com/620959/146682163-e161916a-be2c-4dd4-af61-e7be6eba5bb5.png">

Issues (4x)
Usage of the !important CSS qualifier is not allowed.
Issue documentation: https://amp.dev/documentation/guides-and-tutorials/develop/style_and_layout/style_pages/

<img width="568" alt="Screenshot 2021-12-19 at 17 09 28" src="https://user-images.githubusercontent.com/620959/146682038-b13dc0ac-06b7-4c33-ae14-035f88ab76f1.png">

<img width="562" alt="Screenshot 2021-12-19 at 17 09 40" src="https://user-images.githubusercontent.com/620959/146682047-014da62e-dc97-4c26-95e0-ee910ecb66e7.png">

<img width="542" alt="Screenshot 2021-12-19 at 17 09 46" src="https://user-images.githubusercontent.com/620959/146682051-557fd27e-0049-4116-9172-b919ea37af55.png">

<img width="564" alt="Screenshot 2021-12-19 at 17 09 55" src="https://user-images.githubusercontent.com/620959/146682054-a0eeb0e7-e883-4ff6-80b6-b28f283993cf.png">

These seem to originate from https://github.com/TryGhost/Ghost/blob/main/core/frontend/apps/amp/lib/views/amp.hbs

### Steps to Reproduce

Submit Ghost site with Casper theme (default) and AMP Integration enabled (default) to Google Search Console
URL Inspection on an blog post url
"Request Indexing"
... wait a couple days for Google Bot to visit...

Go back to URL Inspection and check the same url. Then review Issues.

### Ghost Version

4.32.0

### Node.js Version

v14.18.2

### How did you install Ghost?

Digital Ocean ghost marketplace

### Database type

MySQL 8

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by jorisbontje** [comment]
See PR #13912 for a fix.

**Comment by ilyazub** [comment]
Experiencing the same.

![image](https://user-images.githubusercontent.com/282605/146808807-6a103f5b-67f1-46b3-9350-b8692e689af1.png)

Those CSS rules were added in 5dc30ba6a9e64da19a61a4f65fdec8640a1792a2.

@moreofmorris can you take a look?

**Comment by ilyazub** [comment]
ghost.org itself has invalid AMP pages for now. 

https://validator.ampproject.org/#url=https%3A%2F%2Fghost.org%2Fchangelog%2Fheaders%2Famp%2F
https://search.google.com/test/amp/result?id=kzpnUIU7WLmCK7fT7Ef_Tg

![invalid AMP page on ghost.org](https://user-images.githubusercontent.com/282605/146973699-586bf912-a286-4f20-b2d0-93332c72cfbb.png)

**Comment by xilou31** [comment]
I have the same problem with 4.32.0, how can I fix it, is it "ghost update" or something?

**Comment by seanhamlin** [comment]
Looks like the fix was committed to main in https://github.com/TryGhost/Ghost/commit/76cde7918687304af21b3f89c8ca51399f9d3bea, we just need a release of ghost now (4.33 anyone?)
