### ISSUE TITLE
Product Card Title Dark Mode Styling Bug

### ISSUE THREAD

**Issue by mackenly** [TryGhost/Ghost#13923]
### Issue Summary

When in dark mode the title field of the product card takes on the styles of this class: `.kg-product-card-title h4` which makes it impossible to read.

When editing:
![Screenshot 2021-12-29 003150](https://user-images.githubusercontent.com/53151058/147631400-0d1d8c4d-a4da-483f-a88e-309470c2be2b.jpg)

When not editing:
![Screenshot 2021-12-29 003208](https://user-images.githubusercontent.com/53151058/147631390-09c59633-e12a-49dd-8cdd-eb28259fee41.jpg)

Cross-posted to[ this forum post](https://forum.ghost.org/t/product-card-title-dark-mode-styling-bug/27609).

### Steps to Reproduce

1. Select dark mode in the admin dashboard
2. Create a new post with a product card
3. Attempt to edit the title field

### Ghost Version

Ghost Pro (4.32.0)

### Node.js Version

Ghost Pro (not sure what they're running)

### How did you install Ghost?

N/A

### Database type

MySQL 8

### Browser & OS version

Chrome  96.0.4664.110 & Windows 10

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by kumarrus** [comment]
Hi, I'm a new contributor. Can I take this bug?

**Comment by djordjevlais** [comment]
Hey @kumarrus, this has already been fixed [here](https://github.com/TryGhost/Admin/commit/3bea5825921c71f26e20c7abfa8516a4d2f43d63) and it will be included in the next release. Hope you find something else that looks interesting to you :)
