### ISSUE TITLE
Docs: MarkDown rendering problem

### ISSUE THREAD

**Issue by dichotommy** [TryGhost/Ghost#13931]
### Issue Summary

Hey there 👋🏻 I found a trivial MarkDown rendering problem in your documentation. I would normally open a PR for this kind of thing, but I see that your docs are closed-source, so I'm instead creating an issue here (in **explicitly the wrong place** 😬 ). I hope it's not a problem, and feel free to close this issue if it is.

There is a small MarkDown rendering problem in [this tutorial](https://ghost.org/docs/tutorials/code-syntax-highlighting/#create-a-code-block). It should be fixed by using a backslash (`\`) to escape the backtick character (`` ` ``). If you want to display a backtick character within a code snippet, you can also use double backticks to introduce and end the code snippet.

Hope this helps 👋🏻 

### Steps to Reproduce

1. Go to the "Create a code block" section of the [code syntax highlighting tutorial](https://ghost.org/docs/tutorials/code-syntax-highlighting/).
2. Read the first paragraph
3. ???
4. Profit

### Ghost Version

N/A

### Node.js Version

N/A

### How did you install Ghost?

N/A

### Database type

Other

### Browser & OS version

N/A

### Relevant log / error output

```shell
N/A
```

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by matthanley** [comment]
Thanks for the report - this has now been fixed 🎉
