### ISSUE TITLE
/edit url suffix for authors redirects to wrong admin url

### ISSUE THREAD

**Issue by xdivby0** [TryGhost/Ghost#13942]
### Issue Summary

When you are viewing an author page e.g. `/author/ghost`  and add `/edit` to it, the redirect goes to `/ghost/#/staff/ghost`, but should go to `/ghost/#/settings/staff/ghost`.

### Steps to Reproduce

1. Navigate to an author page
2. Add  `/edit` to the url

Result: Page not Found

### Ghost Version

4.32.0

### Node.js Version

14.18.2

### How did you install Ghost?

Dockerized Fresh Setup

### Database type

SQLite3

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by matthanley** [comment]
Hey @xdivby0 thanks for the report - this has now been resolved.
