### ISSUE TITLE
Product Card button text color same as background color

### ISSUE THREAD

**Issue by richtaur** [TryGhost/Ghost#13951]
### Issue Summary

The text inside a Product Card button is the same color as the background, making it invisible. This only happens when viewing the site, not editing it. (This happens in 3 different themes I tested, but not in Casper.)

When editing:
![product_card_1_editor](https://user-images.githubusercontent.com/24601/148848169-8746a51c-af56-4e01-b4c3-2c155b3355df.png)

When not logged in:
![product_card_2_public](https://user-images.githubusercontent.com/24601/148848216-13b10469-c80a-4eaf-bced-8f3ebd7d1a8a.png)

Here's the same image but with all text selected to make it visible:
![product_card_3_public_selected](https://user-images.githubusercontent.com/24601/148848271-53f323b5-5732-4340-82df-f6ae9170d08e.png)

You can see this bug live [here](https://www.valadria.com/how-to-make-a-video-game-all-by-yourself/) (password "letmein").

### Steps to Reproduce

1. Install a theme other than Casper (e.g. Edition theme).
2. Add a Product Card with a button and some text.
3. Note that the value in (Settings / Site Design / Brand / Accent color) appears as both product button background and text color.

### Ghost Version

Ghost(Pro)

### Node.js Version

Ghost(Pro)

### How did you install Ghost?

Ghost(Pro)

### Database type

Other

### Browser & OS version

Google Chrome Version 96.0.4664.110 (Official Build) (x86_64), OS X 11.6

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by minimaluminium** [comment]
Hey @richtaur, I've just checked your site and found that the Edition theme installed on your site isn't up-to-date. If you're seeing the issue on other official themes as well, make sure you're using the latest copy of the themes.

[This](https://edition.ghost.io/p/f369fdf6-24c3-40cd-b50f-b94fb62fdb50/) is how it looks on Edition theme demo site.

**Comment by richtaur** [comment]
Ahh yes that was it, thanks!
