### ISSUE TITLE
AssetHelper not working with svg 

### ISSUE THREAD

**Issue by torstenzander** [TryGhost/Ghost#13971]
### Issue Summary

The asset helper does not work with svg images using # because it adds a query param.

### Steps to Reproduce

```
 <svg class="icon icon__primary quote__line">
        <use xlink:href="{{asset "images/solid.svg#minus"}}"></use>
</svg>
```

Using this does not show the svg images it renders to:
xlink:href="/assets/images/solid.svg#minus?v=094ca0c660"

When I remove the param it works fine and also of cource if  I don't use the helper but this raises a gscan error

### Ghost Version

4.32.0

### Node.js Version

14.18.2

### How did you install Ghost?

Docker Image

### Database type

SQLite3

### Browser & OS version

Chrome / safari

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by ErisDS** [comment]
Hi @torstenzander thanks for the report. A PR that fixes this issue would be very welcome :)
