### ISSUE TITLE
Invite new staff user scroll is broken

### ISSUE THREAD

**Issue by zsid** [TryGhost/Ghost#13975]
### Issue Summary

Hi. I am just starting with ghost and playing around the dashboard. I have discovered that when you want to invite new staff members, the scroll behaviour of the modal/popup is broken - not scrolling at all.

### Steps to Reproduce

Open Settings -> Staff -> Invite people

<img width="1275" alt="Screen Shot 2022-01-13 at 22 09 25" src="https://user-images.githubusercontent.com/11786608/149402202-b3dcd81e-dcb2-4daa-8c63-7a137143e47f.png">

### Ghost Version

4.32.2

### Node.js Version

v16.13.2

### How did you install Ghost?

I have followed https://ghost.org/docs/install/local/. macOS Sierra

### Database type

SQLite3

### Browser & OS version

Google chrome 97.0.4692.71, mocOS Sierra

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by zsid** [comment]
Hi. I have found the problem and fixed it locally. I will have a look this week into the contribution guidelines and raise a PR.

**Comment by sanne-san** [comment]
Hey @zsid, the issue has just been fixed in [this commit](https://github.com/TryGhost/Admin/commit/33fb1c51cdde4e63151a6ffdc77b1d6d2eac390b) – thanks a lot for creating the issue and helping out!
