### ISSUE TITLE
Audio Card does not render once published

### ISSUE THREAD

**Issue by SamHasler** [TryGhost/Ghost#13979]
### Issue Summary

Audio cards render like this and cannot be interacted with:
![image](https://user-images.githubusercontent.com/54277/149637926-59c77453-6b54-4cbd-8230-9fb0c9046648.png)

### Steps to Reproduce

1. Insert and Audio card into a post
2. Publish the post
3. View the post

### Ghost Version

4.32.3

### Node.js Version

v14.17.0

### How did you install Ghost?

npm install -g ghost-cli@latest # in Windows Terminal Powershell 5.1.19041.1320

### Database type

Other

### Browser & OS version

Version 97.0.4692.71 (Official Build) (64-bit) Windows

### Relevant log / error output

```shell
No errors in Chrome Dev Tools console

NB: Selected Other for database as I don't know. It will be whatever the default is.


Ghost-CLI version: 1.18.1
Ghost version: 4.32.3 (at ~\Documents\TOLD\Website\ghost-new)
```

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by matthanley** [comment]
Hey @SamHasler 👋🏼 I'm unable to reproduce this, but I don't have a Windows PC available to test with in case it's a Windows-specific issue. Is the site available anywhere publicly so that we can see the rendered page? Is the issue reproducible on multiple Ghost installs?
