### ISSUE TITLE
No metadata on author's articles pages

### ISSUE THREAD

**Issue by ZsharE** [TryGhost/Ghost#13973]
### Issue Summary

The metadata are not generated on the author's article pages, except the first page.

### Steps to Reproduce

1. Go to an author page, for example: https://alto.ghost.io/author/kelly/ .  I choosed Alto theme because is _Powered by Ghost_.
2. View source this page. The metas are generated.
```html
<meta property="og:site_name" content="Alto" />
<meta property="og:type" content="profile" />
<meta property="og:title" content="Kelly Brown - Alto" />
<meta property="og:description" content="Malesuada fames ac turpis egestas sed tempus urna et pharetra. Egestas maecenas pharetra convallis posuere morbi leo urna molestie at." />
<meta property="og:url" content="https://alto.ghost.io/author/kelly/" />
<meta property="article:publisher" content="https://www.facebook.com/ghost" />
<meta property="article:author" content="https://www.facebook.com/iveel.co" />
<meta name="twitter:card" content="summary" />
<meta name="twitter:title" content="Kelly Brown - Alto" />
<meta name="twitter:description" content="Malesuada fames ac turpis egestas sed tempus urna et pharetra. Egestas maecenas pharetra convallis posuere morbi leo urna molestie at." />
<meta name="twitter:url" content="https://alto.ghost.io/author/kelly/" />
<meta name="twitter:site" content="@tryghost" />
<meta name="twitter:creator" content="@iveel.co" />
```
3. Next, go to the second page of the author's articles: https://alto.ghost.io/author/kelly/page/2/
4. View source this page. The metas are not generated anymore.

### Ghost Version

4.32.0

### Node.js Version

12.22.1

### How did you install Ghost?

Digital Ocean, Linux

### Database type

SQLite3

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by ErisDS** [comment]
Hi @ZsharE thanks for the report. 

This is expected behaviour for subsequent results pages, we stop outputting metadata to prevent having lots of duplicate pages with the same metadata, which doesn't look great to search engines.

**Comment by ThomasArdal** [comment]
I totally understand why you wouldn't want to include duplicate meta tags which would cause warnings in various website validators too. Having no meta description on page 2, etc. also creates warnings. So, with the current solution, you cannot avoid getting these warnings. I believe I have seen other tools mark page 2 and forward on a paginated result with a `nofollow` meta robots element. Would be nice to either have this option or at least be able to enable it through the Ghost Admin.
