### ISSUE TITLE
Chinese characters in the file name are replaced by "-" when stored in the server

### ISSUE THREAD

**Issue by CicoZhang** [TryGhost/Ghost#13987]
### Issue Summary

When uploading files with Chinese Characters via File card, audio card or video card, the name of the files stored in server has Chinese characters replace by "-".

It might not be an big issue, but it is not convenient to manage the media files on the server, with all those "-"s.

![image](https://user-images.githubusercontent.com/11710225/149843895-728a6077-63a6-4ad1-82eb-e4f1742337bd.png)

### Steps to Reproduce

1. Upload an audio file whose name has Chinese characters
2. The file stored on the server, but the name of the file has the Chinese characters replaced by "-" when checking it via SSH login into the server.

### Ghost Version

4.32.3

### Node.js Version

14.18.3

### How did you install Ghost?

Manually install via Ghost CLI

### Database type

MySQL 8

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by ErisDS** [comment]
Please can you provide an example file or filename that we can use to reproduce?
