### ISSUE TITLE
adsense integration

### ISSUE THREAD

**Issue by foolioo** [TryGhost/Ghost#13981]
### Issue Summary

I have followed [Display ads in specific areas of your site using Ad units](https://ghost.org/integrations/google-adsense/#display-ads-in-specific-areas-of-your-site-using-ad-units) on ghost.org.

> If you want to display ads on a specific post or page where the content exists in Ghost Admin, it’s possible to use an HTML card within the editor to display ad blocks in-line with your content

![image](https://user-images.githubusercontent.com/28758375/149662681-c2a65bb3-0fd5-4112-ba3b-2b557348a9f5.png)

although I did just that, there are no ads (attached a screenshot) and the browser console displays the error
> Failed to load resource: the server responded with a status of 400 ()

![image](https://user-images.githubusercontent.com/28758375/149662863-f967902b-01f8-49da-a66f-6f89e4adf1fd.png)

The AdUnit and the website are not new.
I am running Ghost as a static website, could this be the issue?

### Steps to Reproduce

1. Run Ghost on docker instance
2. Follow the link in the Issue Summary and follow the guide
3. Visit the Ghost website locally or export it as a static website, deploy and visit your domain
4. Look at the browser console when you are visiting the post with embedded html block with the ad unit code

### Ghost Version

4.32.2

### Node.js Version

14.18.3

### How did you install Ghost?

docker

### Database type

SQLite3

### Browser & OS version

cross browsers on mac\linux

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by ErisDS** [comment]
The 400 is coming from adsense, not Ghost. I'd hazzard a guess that it's a domain mismatch, but I don't know enough. Either way, definitely not a Ghost bug so the best place to get help would be our [community](https://forum.ghost.org/).
