### ISSUE TITLE
Metadata is not populated with ghost_head tag

### ISSUE THREAD

**Issue by tiendq** [TryGhost/Ghost#13983]
### Issue Summary

Metadata is not populated with `ghost_head` tag e.g. `og` tags.

### Steps to Reproduce

1. `ghost install local`, default configuration
2. View a pre-created post e.g. http://localhost:2368/design/
3. No `og` tag
4. Add Facebook title, description manually for this post
5. View again, still no `og` tag

### Ghost Version

4.31.0

### Node.js Version

v14.17.0

### How did you install Ghost?

ghost install local

### Database type

SQLite3

### Browser & OS version

Chrome, macOS 11.1

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by tiendq** [comment]
I don't agree with environment specific assumption. It works if I manually add `og` tags, post's metadata is available, `ghost_head` tag just doesn't work.

**Comment by ErisDS** [comment]
I've tested your repro steps on a few different envs including `ghost install local` on mac and on a DO one-click install and I cannot reproduce what you're saying.

Here's a fresh local install /write/ page that I've not edited anything yet:

![image](https://user-images.githubusercontent.com/101513/150150852-a0fd003f-5759-491e-a7e9-00025a975053.png)

Same install, /design/ page where I have edited the metadata:

![image](https://user-images.githubusercontent.com/101513/150150770-f5ccdf57-18ac-4b1a-ba7f-7470a36d6626.png)

There has to be something really specific about what you're doing to get it to break, or you're not looking in the right place.
