### ISSUE TITLE
Pasted markdown text does not render properly

### ISSUE THREAD

**Issue by spirosag** [TryGhost/Ghost#13982]
### Issue Summary

When text containing markdown is pasted into the editor, the markdown is not parsed. I don't mean in a markdown box, but in the regular editor. If you write the markdown by hand it renders correctly.

### Steps to Reproduce

1. Open the ghost editor
2. Write `HH some text`
3. Observe that as you press the space after `HH` the editor parses the markdown and changes the format accordingly
4. Paste `HH some text`
5. Observe that this time the editor does not parse and format the the markdown.

I would prefer to write posts in an external markdown editor and then paste them raw in the ghost editor.

### Ghost Version

hosted in ghost.org

### Node.js Version

hosted in ghost.org

### How did you install Ghost?

hosted in ghost.org

### Database type

Other

### Browser & OS version

mac os monterey, chrome

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by ErisDS** [comment]
This is currently the expected behaviour - the Ghost editor understands markdown as you type it but is not a markdown based editor.

If you want to copy from a markdown based editor you would need to paste into a markdown card to get your desired effect.
