### ISSUE TITLE
invalid opcode in libvips-cpp.so.42 when resizing images crashes Ghost

### ISSUE THREAD

**Issue by idmacdonald** [TryGhost/Ghost#13986]
### Issue Summary

I am having problems similar to what has been reported in #12967 when uploading images to Ghost. It seems there is still some sort of problem with the sharp module and libvips on Ubuntu focal. The kernel reports `traps: node[189195] trap invalid opcode ip:7fa9b6137dfb sp:7ffe10b72c70 error:0 in libvips-cpp.so.42[7fa9b5e2a000+aac000]` and then Ghost dies and respawns, if being run via a systemd service.

I have tested with various NodeJS versions, various Ghost versions, and on Ubuntu bionic and Ubuntu focal. I have also tried using the latest Docker images (standard and Alpine). In all cases, libvips crashes upon attempting to resize an image.

I have also tried with the Ubuntu libvips42 and libvips-dev packages installed on the server, or with those packages absent, the libvips crash happens either way.

### Steps to Reproduce

1. Set up a fresh Ubuntu focal install (OS: Ubuntu, v20.04.3 LTS)
2. Follow the instructions at https://ghost.org/docs/install/ubuntu/ to install NodeJS, npm, ghost-cli
3. Run `ghost install` to install ghost
4. Log into the install at https://example.org/ghost
5. On any post, click on the 'add feature image' button. Upload an image.
6. The image uploads, but then on the post edit page, there is an error 'Request was rejected due to server error'.
7. Ghost crashes, with the kernel reporting `traps: node[189195] trap invalid opcode ip:7fa9b6137dfb sp:7ffe10b72c70 error:0 in libvips-cpp.so.42[7fa9b5e2a000+aac000]`
8. The image field is empty rather than containing the uploaded image

### Ghost Version

4.32.3

### Node.js Version

16.13.2

### How did you install Ghost?

Installed Ubuntu 20.04.3 LTS, followed instructions at https://ghost.org/docs/install/ubuntu/

### Database type

Other

### Browser & OS version

Database is MariaDB 10.3.32

### Relevant log / error output

```shell
The last thing logged by Ghost before it crashes is this:

`{"name":"Log","hostname":"ghost","pid":190756,"level":30,"req":{"meta":{"requestId":"7467f806-ea20-49df-b456-554b39945208","userId":"1"},"url":"/snippets/?limit=all","method":"GET","originalUrl":"/ghost/api/canary/admin/snippets/?limit=all","params":{},"headers":{"x-forwarded-for":"xxx.182.87.104","x-forwarded-proto":"https","x-real-ip":"xxx.182.87.104","host":"dev.example.org","connection":"close","user-agent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:96.0) Gecko/20100101 Firefox/96.0","accept":"application/json, text/javascript, */*; q=0.01","accept-language":"en-GB,en;q=0.7,en-US;q=0.3","accept-encoding":"gzip, deflate, br","referer":"https://dev.greenhousethinktank.org/ghost/","content-type":"application/json; charset=UTF-8","x-ghost-version":"4.32","app-pragma":"no-cache","x-requested-with":"XMLHttpRequest","sec-fetch-dest":"empty","sec-fetch-mode":"cors","sec-fetch-site":"same-origin","cookie":"**REDACTED**"},"query":{"limit":"all"}},"res":{"_headers":{"x-powered-by":"Express","cache-control":"no-cache, private, no-store, must-revalidate, max-stale=0, post-check=0, pre-check=0","content-type":"application/json; charset=utf-8","etag":"W/\"5de-Am7y2fMulaaoXAKXSzsm4R4Tu2g\"","vary":"Accept-Encoding","content-encoding":"gzip"},"statusCode":200,"responseTime":"40ms"},"msg":"","time":"2022-01-17T14:01:46.600Z","v":0}`

The kernel reports Ghost crashing with:
`traps: node[189195] trap invalid opcode ip:7fa9b6137dfb sp:7ffe10b72c70 error:0 in libvips-cpp.so.42[7fa9b5e2a000+aac000]`
```

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by idmacdonald** [comment]
This seems very similar to the problems that have been reported in #12967 and #13225, I am seeing it on Debian and Ubuntu, with a manual installation of Ghost as well as when running the official Docker image.

**Comment by ErisDS** [comment]
I hear that this is very frustrating, but the most useful thing to do here would be to raise this on the [sharp](https://github.com/lovell/sharp) repo, making sure to provide sample images as all the relevant codepaths are in their module and not ours :) 

Sharp is totally optional, so the best way around it short term would be to do `yarn remove sharp` in your install and remove it. Then Ghost won't try to resize images. Not ideal of course but at least prevents the fatal error. You can also disable optimisation via [config](https://ghost.org/docs/config/#image-optimisation).

I'm going to close this here as there's not really anything for us to do until it's fixed upstream.

**Comment by ErisDS** [comment]
Also to followup - whilst I don't doubt you're experiencing this issue, it is not a generally reproducible issue nor the same as the previous issues, so it is something you need to raise and provide lots of detail around if you want help getting to the bottom of it!

Our DigitalOcean 1-click app runs on Ubuntu 20.04 and it's not reproducible there :)

**Comment by idmacdonald** [comment]
Hi @ErisDS,

Here is the issue that I filed for `sharp`: https://github.com/lovell/sharp/issues/3047

It looks like the root cause was that the default builds of sharp for amd64 platforms require a CPU with SSE4.2. So, sharp will crash on older or simpler CPU platforms that don't support SSE4.2. In that case, the only option would be to custom compile `sharp` and related libraries.

Perhaps it would be good to mention in the Ghost documentation that image resizing functions on amd64 platforms requires a CPU with SSE4.2.
