### ISSUE TITLE
Webhook URL validation is too strict

### ISSUE THREAD

**Issue by uPagge** [TryGhost/Ghost#14014]
### Issue Summary

The problem is that when I try to use the name of the container as a url in docker-compose, it shows that the url is not valid

<img width="581" alt="Снимок экрана 2022-01-19 в 00 24 15" src="https://user-images.githubusercontent.com/40397740/150021021-e4c7cf13-3823-4d1d-b231-140729424484.png">

<img width="340" alt="Снимок экрана 2022-01-19 в 00 25 55" src="https://user-images.githubusercontent.com/40397740/150021256-0718b607-1f09-4ffc-9d56-69e84594845a.png">

### Steps to Reproduce

Screenshot

### Ghost Version

4.32.0-debian

### Node.js Version

none

### How did you install Ghost?

docker

### Database type

Other

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by uPagge** [comment]
In general, I easily got around the problem, but perhaps this is excessive validation

<img width="530" alt="Снимок экрана 2022-01-19 в 00 28 18" src="https://user-images.githubusercontent.com/40397740/150021541-4b180b12-76df-4806-b151-1944ab73a194.png">

<img width="328" alt="Снимок экрана 2022-01-19 в 00 28 29" src="https://user-images.githubusercontent.com/40397740/150021569-87ea2825-498f-4d10-a37e-e9d9ecd9bff9.png">

**Comment by ErisDS** [comment]
This is a duplicate of https://github.com/TryGhost/Ghost/issues/12933, although sadly I never got around to triaging this issue.

I can see that it's annoying, although it's also fairly trivial to work around.

Would happily accept a PR that fixes it though :)

**Comment by KitaPDev** [comment]
@ErisDS Hi, I would like to work on this issue. Could you please assign this to me?

**Comment by ErisDS** [comment]
Hi @KitaPDev you are welcome to work on this issue and submit a PR, however we are unable to assign issues to people who do not have a history of contributing to the project. Thanks!

**Comment by KitaPDev** [comment]
Alright @ErisDS . I'll get started working on this.
