### ISSUE TITLE
api.members.add seems to activate member without opt-in from magic link

### ISSUE THREAD

**Issue by rosano** [TryGhost/Ghost#14035]
### Issue Summary

Not sure if this is intended but when adding an email via the JavaScript API, there is a member created and it seems I can even send email without waiting for the opt-in. This happens whether `email_type` is `subscribe` or `signup`.

### Steps to Reproduce

I ran the following code via node.js:

```javascript
const GhostAdminApi = require('@tryghost/admin-api');

const api = new GhostAdminApi({
	url: `https://${ ghost_domain }.com`,
	key: api_key,
	version: 'canary'
})
await api.members.add({
	email: email_address,
}, {
	send_email: true,
	email_type: 'subscribe',
	// email_type: 'signup',
	label: 'alfa',
})
```

I was expecting that the member would not be visible in the admin UI until they click the button from the magic link.

### Ghost Version

4.32.3

### Node.js Version

?

### How did you install Ghost?

Cloudron

### Database type

Other

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by rosano** [comment]
Seems to have the same issue via cURL too:

```bash
GHOST_DOMAIN="XXXXX"
GHOST_API_KEY="XXXXX"
GHOST_API_VERSION="v4"

# CREATE JWT_TOKEN
TMPIFS=$IFS
IFS=':' read ID SECRET <<< "$GHOST_API_KEY"
IFS=$TMPIFS
NOW=$(date +'%s')
FIVE_MINS=$(($NOW + 300))
HEADER="{\"alg\": \"HS256\",\"typ\": \"JWT\", \"kid\": \"$ID\"}"
PAYLOAD="{\"iat\":$NOW,\"exp\":$FIVE_MINS,\"aud\": \"/$GHOST_API_VERSION/admin/\"}"
base64_url_encode() {
    declare input=${1:-$(</dev/stdin)}
    # Use `tr` to URL encode the output from base64.
    printf '%s' "${input}" | base64 | tr -d '=' | tr '+' '-' |  tr '/' '_'
}
header_base64=$(base64_url_encode "$HEADER")
payload_base64=$(base64_url_encode "$PAYLOAD")
header_payload="${header_base64}.${payload_base64}"
signature=$(printf '%s' "${header_payload}" | openssl dgst -binary -sha256 -mac HMAC -macopt hexkey:$SECRET | base64_url_encode)
JWT_TOKEN="${header_payload}.${signature}"

# testing GET posts
# curl --insecure -H "Authorization: Ghost $JWT_TOKEN" "https://$GHOST_DOMAIN/ghost/api/$GHOST_API_VERSION/admin/posts/"

# testing GET members
# curl --insecure -H "Authorization: Ghost $JWT_TOKEN" "https://$GHOST_DOMAIN/ghost/api/$GHOST_API_VERSION/admin/members/"

# POST members
curl --insecure -H "Authorization: Ghost $JWT_TOKEN" -H "Content-Type: application/json" -d '{"members":[{"email":"XXXXX"}]}' "https://$GHOST_DOMAIN/ghost/api/$GHOST_API_VERSION/admin/members?send_email=true&email_type=subscribe"
```

**Comment by matthanley** [comment]
Hey @rosano 👋🏼 It's expected behaviour that members are added immediately when added via the API. You can POST to the `/members/api/send-magic-link/` endpoint to trigger the magic link signup mechanism, but the links expire after 24h and it's intended to be used for member self signup.

Could you provide more details on your use-case and what you're hoping to achieve?

**Comment by rosano** [comment]
Posting to that endpoint seems to work, but I'm somehow not able to activate when making the request server-side via node.js—see #14045.
