### ISSUE TITLE
API returns incorrect excerpt

### ISSUE THREAD

**Issue by joeljfischer** [TryGhost/Ghost#14047]
### Issue Summary

The API is not returning my custom excerpt but is instead returning the first lines of the text (in markdown?).

### Steps to Reproduce

1. Create a post with a custom excerpt.
2. Retrieve the post via the API.
3. The JSON value of key "excerpt" does not contain the custom excerpt.

### Ghost Version

4.32.3

### Node.js Version

n/a - hosted by Ghost

### How did you install Ghost?

Hosted by Ghost

### Database type

Other

### Relevant log / error output

```shell
My custom excerpt:
> Best Christian Music of 2021, Paradise Lost, Shame Deserved and Undeserved, and more...

Post API response:
{
...
> "excerpt" : "Bible Study: Hebrews Part 7 (2:1–4) — Pay Attention to Jesus\n[https:\/\/www.thegardenweekly.com\/bible-study-hebrews-part-7\/]\nIn Hebrews 1, we saw an introduction (Hebrews 1:1–4) that tells us about a Son\nof God. Then, seven quotations from the Hebrew scriptures form an argument that\nthis Son is greater than the angels. That this Son is distinct from the Father,\nbut nonetheless fully deity.\n\nThe author breaks off his argument to give a short aside and application of his\nargument in Hebrews 1…\n\nKeep",
...
}
```

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by ErisDS** [comment]
Hi there @joeljfischer. This is expected behaviour. The custom excerpt is returned in the field `custom_excerpt`.
