### ISSUE TITLE
Blank 'custom settings' after renaming theme archive name

### ISSUE THREAD

**Issue by fueko** [TryGhost/Ghost#14056]
### Issue Summary

I noticed that 'custom settings' are assigned to the zip archive name: e.g. casper-v1.zip and casper-v2.zip and will be treated by Ghost as different themes, even though in the package.json file the theme name is "casper" (currently additional new fields are created in the database for each new theme archive name).

Is the current behavior intentional or a bug?

### Steps to Reproduce

1. Upload two versions of the same theme, but rename them, e.g. casper-v1.zip and casper-v2.zip
2. Check the database

### Ghost Version

4.33.1

### Node.js Version

v16.13.0

### How did you install Ghost?

localhost

### Database type

SQLite3

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by ErisDS** [comment]
Hi there!

If you upload a different archive, it'll land in a new folder in `content/themes` called casper-v1, casper-v2 etc. As it's a new folder, it's a new theme! 

This is intended behaviour as any alternative path e.g. trying to create a folder name based on the theme's package.json name, or overwriting a theme based on just them having the same package.json name leads to even harder to understand behaviour.
