### ISSUE TITLE
Python Example Code (in Admin API website) Has Bug

### ISSUE THREAD

**Issue by DeoluA** [TryGhost/Ghost#14058]
### Issue Summary

Wasn't sure where exactly to raise this, so trying here:
On your [Admin API explainer website](https://ghost.org/docs/admin-api/), on the _Token Generation Examples_ section, the code in the Python tab produces an error:

```
Traceback (most recent call last):
  File "/path/to/handler.py", line 92, in <module>
    headers = {'Authorization': 'Ghost {}'.format(token.decode())}
AttributeError: 'str' object has no attribute 'decode'
```

**The fix was removing** `.decode()` **from** `token` **in line** `26`:
```
headers = {'Authorization': 'Ghost {}'.format(token)}
```

### Steps to Reproduce

1. Copy code from `python` section in website
2. Fill in necessary details (such as `ADMIN_API_KEY`)
3. Run

**The fix was removing** `.decode()` **from** `token` **in line** `26`:
```
headers = {'Authorization': 'Ghost {}'.format(token)}
```

### Ghost Version

N/A

### Node.js Version

N/A

### How did you install Ghost?

N/A

### Database type

Other

### Relevant log / error output

```shell
Traceback (most recent call last):
  File "/path/to/handler.py", line 92, in <module>
    headers = {'Authorization': 'Ghost {}'.format(token.decode())}
AttributeError: 'str' object has no attribute 'decode'


**The fix was removing** `.decode()` **from** `token` **in line** `26`:

headers = {'Authorization': 'Ghost {}'.format(token)}
```
```


### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by ErisDS** [comment]
Thanks for sharing this 🙏 - I finally got around to updating the example 😬
