### ISSUE TITLE
Member subscription checkout fails due to stripe request missing parameter success_url

### ISSUE THREAD

**Issue by realandrew** [TryGhost/Ghost#14082]
### Issue Summary

When a user tries to upgrade to a paid plan from portal, an error pops up saying "Failed to process checkout, please try again" and the console logs a 400 request `POST https://<mysite>.com/members/api/create-stripe-checkout-session/ 400`. Possibly related I had a similar error when trying to give a complimentary subscription, however, I solved that by enabling tiered subscriptions. I'm running the docker version of Ghost and have it running through Cloudflare (in dev mode to prevent caching issues).

### Steps to Reproduce

1. Try to upgrade from a free to a paid plan from portal.
2. "Failed to process checkout, please try again" error message appears along with a 400 error in the console. The expected behavior is the Stripe checkout appears.

### Ghost Version

4.34.0

### Node.js Version

14.18.3

### How did you install Ghost?

latest docker ghost:4 image

### Database type

SQLite3

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by realandrew** [comment]
I should also note, I checked my Stripe account to make sure it's fine, turns out Ghost created 31 Stripe customers for 1 account. Seems each time the error appears it creates another customer. (The customer is my test account so it's not a big deal for me to delete them, but it's related so I figured I'd mention it).

**Comment by realandrew** [comment]
Looking at my Stripe logs I just noticed a "400 POST ERROR /v1/checkout/sessions" due to `parameter_missing - success_url`. I didn't have a welcome page set in my membership settings so I tried setting one and it won't actually save even though the save button says it has. So this is likely the problem, the welcome page isn't being saved (and isn't set as required) so Stripe is sending a 400 due to not having a success_url parameter.

**Comment by allouis** [comment]
I'm not able to replicate this - would you be able to share the full errors logs?

**Comment by realandrew** [comment]
I'll share the relevant piece of the log, the whole log file is very long (it shows up in the standard log, not the errors log) but if you want the full log file too I'm willing to share it.

```JSON
{"name":"Log","hostname":"ditd-ghost-ix-chart-6c4c77574-rfvwp","pid":1,"level":30,"req":{"meta":{"requestId":"04344f89-9c1c-4517-9953-c0db95322a6d","userId":null},"url":"/api/create-stripe-checkout-session/","method":"POST","originalUrl":"/members/api/create-stripe-checkout-session/","params":{},"headers":{"host":"divingintothedeep.com","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36","content-length":"704","accept":"*/*","accept-encoding":"gzip","accept-language":"en-US,en;q=0.9","cdn-loop":"cloudflare","cf-cloudflared-proxy-tunnel-hostname":"svbbblht4scqi0db5n406anlguevvxe09b0phkfzspxl8e7kyx10.cftunnel.com","cf-connecting-ip":"193.148.18.67","cf-ray":"6d58c921cd8a1770-EWR","cf-visitor":"{\"scheme\":\"https\"}","cf-warp-tag-id":"38594462-a196-49d0-82d7-f517d02f99be","connection":"keep-alive","content-type":"application/json","cookie":"**REDACTED**","dnt":"1","origin":"https://divingintothedeep.com","referer":"https://divingintothedeep.com/","sec-fetch-dest":"empty","sec-fetch-mode":"cors","sec-fetch-site":"same-origin","sec-gpc":"1","x-forwarded-for":"193.148.18.67","x-forwarded-proto":"https"},"query":{}},"res":{"_headers":{"x-powered-by":"Express","cache-control":"no-cache, private, no-store, must-revalidate, max-stale=0, post-check=0, pre-check=0","access-control-allow-origin":"*"},"statusCode":400,"responseTime":"956ms"},"msg":"","time":"2022-01-30T06:53:53.267Z","v":0}
```

**Comment by realandrew** [comment]
I updated to Ghost 4.34.2 and still have the same error. I was able to set welcome URLs, but still get the 400 error when trying to upgrade to a paid member.

**Comment by matthanley** [comment]
@realandrew could you provide the request body for the failing network request from your browser's dev tools network tab?

**Comment by realandrew** [comment]
Headers
```
:authority: divingintothedeep.com
:method: POST
:path: /members/api/create-stripe-checkout-session/
:scheme: https
accept: */*
accept-encoding: gzip, deflate, br
accept-language: en-US,en;q=0.9
cache-control: no-cache
content-length: 704
content-type: application/json
cookie: __stripe_mid=3a8518d6-8264-491d-814f-458b123639e757ef7b; ghost-members-ssr=a******0@gmail.com; ghost-members-ssr.sig=IyfoUoli8-2rcPOWEcdpIaWoif4; __cf_bm=NHSsyWGLDXpOgZrxKpZn9kweVUuEbBF2JMLno2_tad4-1643814337-0-Ac79opKo+X8TspolM0vPrkbN3vRTl+imtFLG7eMRJuU8a4LEiY6NFJMFv+Fp5DQoq3DYbD02do0SZ2jnkTwm6pUr61BOa5RQdcg7zEqitWeMtLLDFLIpMt3UNj2E7KoMwA==; __stripe_sid=29a63d8f-07ce-40ef-9c9a-8bcd0a0092b7f9466f
dnt: 1
origin: https://divingintothedeep.com
pragma: no-cache
referer: https://divingintothedeep.com/
sec-fetch-dest: empty
sec-fetch-mode: cors
sec-fetch-site: same-origin
sec-gpc: 1
user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36
```

Payload
```
{priceId: "61fa2d07a751910165aef9b4",…}
cancelUrl: "https://divingintothedeep.com/?stripe=cancel"
identity: "eyJhbGciOiJSUzUxMiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhbmRyZXdqbWl0Y2hlbGwyMDAwQGdtYWlsLmNvbSIsImtpZCI6Ik1xUXhURWYyZkFFQXd5RmFrM2toRGxBSUotOGcwT0VsalZwUDlOaE9uZTQiLCJpYXQiOjE2NDM4MTQzNDMsImV4cCI6MTY0MzgxNDk0MywiYXVkIjoiaHR0cHM6Ly9kaXZpbmdpbnRvdGhlZGVlcC5jb20vZ2hvc3QvYXBpL3VuZGVmaW5lZC8iLCJpc3MiOiJodHRwczovL2RpdmluZ2ludG90aGVkZWVwLmNvbS9naG9zdC9hcGkvdW5kZWZpbmVkLyJ9.KSs37TECS7zf5bwC0e0v9xw3QCgt5RaJjRFIC7h02qmlTjGPZKrAcPcOUv6W60WEUFVNOu1NKnuj6tQrcm28srrmA_lBjj51ZvKnKo3HCxMASCHie5Lz28kyU9W5P_XwRmymOqBGv0WM25jeMvyl08Q1BlR-8DCqgsfMjdaAKxI"
metadata: {requestSrc: "portal", checkoutType: "upgrade"}
priceId: "61fa2d07a751910165aef9b4"
```
I'm fairly sure the problem is there is no success URL being supplied, my Stripe logs tell me that is the problem.

**Comment by realandrew** [comment]
Doing some quick debugging, I can see in the browser dev tools, api.js has a checkoutPlan method which takes a successUrl as one of its options, but checkoutPlan in actions.js is calling it without giving it a successUrl. So as I mentioned this issue is almost certainly due to Stripe not getting a successUrl passed to it (which is a required parameter).

**Comment by realandrew** [comment]
An easy fix would be to copy what is done with cancelUrl. Which is
```
if (!cancelUrl) {
    const checkoutCancelUrl = window.location.href.startsWith(siteUrlObj.href) ? new URL(window.location.href) : new URL(siteUrl);
    checkoutCancelUrl.searchParams.set('stripe', 'cancel');
    cancelUrl = checkoutCancelUrl.href;
 }
```
Basically, if a successUrl isn't being passed in we could set it to baseUrl/?stripe=success. It's still worth investigating why successUrl isn't being passed as it should, but this is a good fallback to prevent errors.

**Comment by realandrew** [comment]
I did a clean install of Ghost Docker today (which meant tiered membership wasn't enabled as it was before) and the bug doesn't appear. So seems it has to do with tiered membership.

**Comment by luisda0** [comment]
Yes, it seems that it has to do with the tiered memberships
I reproduced the bug by:
- doing a clean install
- Activating stripe test account
- activating tiered memberships
- creating a new member
- trying to upgrade the free member to a paid membership.

**Comment by allouis** [comment]
Thanks for the report and the repro case - this has been fixed here https://github.com/TryGhost/Ghost/commit/f88b6bd02f30f7616690963768360fd93f222b06 and will be in the next release. 

For now if you are still experiencing the issue, a work around is to stop and restart Ghost once you've connected to Stripe
