### ISSUE TITLE
Unable to load responsive images

### ISSUE THREAD

**Issue by l0u1sg** [TryGhost/Ghost#14081]
### Issue Summary

Hello to all,

I installed my Ghost but I have a problem, the images don’t load, it concerns the “responsive” images apparently, with the URL “[…]/content/images/size/w2000/[…]”, when I copy and paste the direct link of the image that doesn’t load, I get the error "We’ll be right back. Here are the technical details of my installation:

Direct Link: https://blog.louisgallet.ga/content/images/2022/01/46707587.jpg
Responsive Link: https://blog.louisgallet.ga/content/images/size/w100/2022/01/46707587.jpg (This link does not work and is the one used for the article covers)
Does anyone have a solution?

### Steps to Reproduce

Just install Ghost on Docker and create an article with pictures

### Ghost Version

latest

### Node.js Version

docker image nodejs version

### How did you install Ghost?

Docker on Ubuntu 

### Database type

SQLite3

### Browser & OS version

All browser & OS versions

### Relevant log / error output

```shell
No errors or warnings in the logs
```

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by matthanley** [comment]
Hey @l0u1sg - I'm unable to reproduce this, and can't see any issues on your site other than missing images (they're responding 404 Not Found). Could you provide a clear reproduction case?
