### ISSUE TITLE
Duplicate views cannot be deleted 

### ISSUE THREAD

**Issue by ever-blogger** [TryGhost/Ghost#14123]
### Issue Summary

Unable to delete '得到' filter view which is same filter as Draft, but there is not issue to create the new filter view and delete. 
When I select '得到' it will link me to Draft view.

![image](https://user-images.githubusercontent.com/63139255/152663900-81e2907e-a071-4414-95cc-57dd15d9682c.png)

### Steps to Reproduce

NA

### Ghost Version

4.5.0

### Node.js Version

14.19

### How did you install Ghost?

Ubuntu 20.04

### Database type

MySQL 8

### Browser & OS version

Firefox Windows 11

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by ErisDS** [comment]
The issue here is with creating a filter that matches the draft view. It is possible to delete it from your console something like this:

```
let view = GhostAdmin.__container__.lookup('service:customViews').viewList.findBy('name', '得到');

GhostAdmin.__container__.lookup('service:customViews').deleteViewTask.perform(view)
```

I think the only way to solve this is to prevent the creation of views that mirror built-in functionality.

A PR that prevents this would be very welcome!

**Comment by ever-blogger** [comment]
How can I use it the console ? I pasted the commend below, but it return error as **syntax error near unexpected token `'service:customViews''**

`let view = GhostAdmin.__container__.lookup('service:customViews').viewList.findBy('name', '得到');`

`GhostAdmin.__container__.lookup('service:customViews').deleteViewTask.perform(view)`

**Comment by AndrewSerra** [comment]
Is anyone working on this? If not, can I take a shot at it? How urgent is it?
