### ISSUE TITLE
Cannot update Premium Price

### ISSUE THREAD

**Issue by cultureclap** [TryGhost/Ghost#14178]
### Issue Summary

When I try to update the monthly price for subscriptions, I am not able to do so; when I click save, I am told to retry;

![GhostMembershipForms](https://user-images.githubusercontent.com/4434370/154819105-8f89e439-c606-4c94-be67-6e5104c9a197.png)

 and here is the error:

![GhostError](https://user-images.githubusercontent.com/4434370/154819083-18823830-bfc6-4d74-807a-81fe7ac19bdd.png)

How can I update my pricing ? maybe disconnect and reconnect stripe ?!?

### Steps to Reproduce

1) Changed the monthly and yearly price
2) Clicked Save

### Ghost Version

4.36.2

### Node.js Version

v14.18.2

### How did you install Ghost?

Ubuntu, from source, I think ...

### Database type

MySQL 8

### Browser & OS version

Brave / ArchLinus

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by matthanley** [comment]
Hey @cultureclap 👋🏼

I've been unable to replicate this on the latest Ghost version. So we can continue to look into this, could you provide the response from the `ghost/api/canary/admin/products/` endpoint from your browser's network tab when you load Ghost Admin, as well as the request triggered by the save action (this should be a PUT request to e.g. `/ghost/api/canary/admin/products/6213bd772f6c95bfb0cf2d84/`)?

**Comment by matthanley** [comment]
Note that this can also occur if you've made changes directly in the Stripe account, such as deleting the product or price.

**Comment by cultureclap** [comment]
I get a 404 error when I got to the  "ghost/api/canary/admin/products/" ... I've never changed the original settings ... perhaps the product page was added in since Sept 2021 ?? which is when I first created the Ghost instance ?

**Comment by cultureclap** [comment]
all good; thank you - I just deleted the account and made a new Strip connection :)
