### ISSUE TITLE
Cannot apply change on Custom Integrations

### ISSUE THREAD

**Issue by chibiribiri** [TryGhost/Ghost#14181]
### Issue Summary

Save does nothing

### Steps to Reproduce

1. Create custom integration
2. While configuring type a description
3. Maybe upload an icon too
4. Try to save the changes
5. Nothing happens

### Ghost Version

4.36.2

### Node.js Version

14.19.0

### How did you install Ghost?

CentOS 7

### Database type

Other

### Browser & OS version

Safari 15.2, Edge 98.0.1108.56

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by kevinansfield** [comment]
Fixed via https://github.com/TryGhost/Admin/commit/f4dce9f47961a99a16bfc956013a25c24ba131c0

**Comment by daniellockyer** [comment]
@chibiribiri Thanks for the report! The fix for this was released in v4.36.3 so please update using Ghost-CLI 🙂
