### ISSUE TITLE
Can't scroll subscription page on mobile browser

### ISSUE THREAD

**Issue by yogurtpops** [TryGhost/Ghost#14214]
### Issue Summary

Can't scroll the subscription page using mobile browser, the screen recording is attached below

https://user-images.githubusercontent.com/30436755/155955803-0dc0a526-a656-4ae6-a6df-a1cf8a861e04.mov

### Steps to Reproduce

Open the page then go to the subscription page by click on the subscribe button. On the subscription page, we can't scroll farther than the first plan.

### Ghost Version

4.36.3

### Node.js Version

16.x (Node v16 Gallium LTS)

### How did you install Ghost?

Ghost Pro

### Database type

MySQL 5.7

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by matthanley** [comment]
Hey @yogurtpops 👋🏼 Could you confirm which mobile browser this is in? The answer was omitted from our issue template, but is essential info for troubleshooting this specific issue. Thanks!

**Comment by GV3** [comment]
I have experienced this bug on Firefox, Safari and Chrome on iOS 14.3 (iPhone 12 Pro Max)

**Comment by yogurtpops** [comment]
@matthanley as mentioned by @GV3 in any browser on iphone 12 . I checked that its fine on android and iphone 7 plus. Could it be os based problem?

**Comment by matthanley** [comment]
I'm unable to reproduce this in Safari on iOS 15.3.1 so it may be a browser bug. Could you confirm what version of iOS you're using, and try updating to the latest to see if the issue persists?

**Comment by stromfeldt** [comment]
@matthanley I had this occur on an iPhone 7 Plus, using iOS 13.3.1, as [reported on the forum](https://forum.ghost.org/t/membership-tiers-beta-feedback-issues/25681/70) a few months ago. The problem occurs in portrait mode but not landscape mode. I too have a video if you'd like, if you have a method in which I can privately share it with you.
