### ISSUE TITLE
"Header two" formatting toolbar button is as H3

### ISSUE THREAD

**Issue by Bammede** [TryGhost/Ghost#14219]
### Issue Summary

"Header two" formatting toolbar button is as H3

### Steps to Reproduce

select text in post and choose heading Two

### Ghost Version

4.37

### Node.js Version

14.x

### How did you install Ghost?

localhost

### Database type

MySQL 8

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by matthanley** [comment]
This is expected behaviour - the post title will usually be rendered as a top-level heading (`h1`), with the in-content headers expected taking lower-level headings `h2` and `h3`.

**Comment by Bammede** [comment]
Toolbar displays ALT title: "Heading One" which is H2 and "Headin Two" which is H3. Is it normal?
