### ISSUE TITLE
Editor's toolbar is hidden under android's text menu.

### ISSUE THREAD

**Issue by GregFdz** [TryGhost/Ghost#14287]
### Issue Summary

Hi
When I use the post editor on my android phone, the "copy/cut/past" pops over ghost's text toolbar.
As android's is set to display on the upper side of the selected text, I suggest that ghost's should be updated to appear downer at leat for smartphones.

Thanks !

### Steps to Reproduce

1. Go in ghost's post editor with an android 11 smartphone
2. Select a piece of text

### Ghost Version

Las

### Node.js Version

Las

### How did you install Ghost?

Ssh

### Database type

MySQL 8

### Browser & OS version

Chrome and android 11 both updated to last version

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by ErisDS** [comment]
Ghost's editor isn't at all optimised for mobile. There are many much deeper issues that this. If you'd like to submit a PR to fix this particular problem, we'd be happy to merge it.

**Comment by jdaviescoates** [comment]
> Ghost's editor isn't at all optimised for mobile.

This is a mighty shame. I was hoping to start offering all sorts of people and project Ghost hosting, but with an unusable mobile editor in a mobile-first world it makes Ghost as good as useless for many :( such a shame :(
