### ISSUE TITLE
Issue with address ‚localhost' for Product and Video card instead of __GHOST_URL__

### ISSUE THREAD

**Issue by fueko** [TryGhost/Ghost#14344]
### Issue Summary

Product and Video card thumbnails have the address `http://localhost:2368` when exported, which causes thumbnail location issues when importing json file.

![Zrzut ekranu 2022-03-20 o 20 36 42](https://user-images.githubusercontent.com/23366922/159179658-36e0cb82-485d-41bf-b842-13fdb8341540.png)

### Steps to Reproduce

1. Add thumbnail to Product card and export json file from Labs settings.
2. Check the thumbnail address.

### Ghost Version

4.40.0

### Node.js Version

v16.13.0

### How did you install Ghost?

localhost / macOS

### Database type

SQLite3

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by ErisDS** [comment]
@naz could you take a little look at this one please?

**Comment by naz** [comment]
Hey @fueko :wave:  Thanks for the report. I've tried reproducing it on the latest 4.41.0 and wasn't able to. The export file seems to have correctly put `__GHOST_URL__` in place of the url's. Example from an export of mobiledoc field for the post I did:
```
"{\"version\":\"0.3.1\",\"atoms\":[],\"cards\":[[\"video\",{\"loop\":false,\"src\":\"__GHOST_URL__/content/media/2022/03/1323s_to_1334_5s_E1115_Emergency_Pod_Collapsing_.mp4\",\"fileName\":\"1323s_to_1334_5s_E1115_Emergency_Pod_Collapsing_.mp4\",\"width\":1280,\"height\":720,\"duration\":11.517097,\"mimeType\":\"video/mp4\",\"thumbnailSrc\":\"__GHOST_URL__/content/images/2022/03/media-thumbnail-ember472.jpg\",\"thumbnailWidth\":1280,\"thumbnailHeight\":720,\"cardWidth\":\"wide\",\"customThumbnailSrc\":\"__GHOST_URL__/content/images/2022/03/68omdg.png\"}],[\"product\",{\"productButtonEnabled\":true,\"productRatingEnabled\":false,\"productStarRating\":5,\"productImageSrc\":\"__GHOST_URL__/content/images/2022/03/1500x500.jpeg\",\"productTitle\":\"hey there\",\"productDescription\":\"<p>product button</p>\"}]],\"markups\":[],\"sections\":[[1,\"p\",[[0,[],0,\"export me\"]]],[10,0],[10,1],[1,\"p\",[]]],\"ghostVersion\":\"4.0\"}"
```

Import worked just fine too. Can you please add more details on how this could be reproduced? I might be missing some steps to get the bug right :)

Can you also check what configuration your instance was running with? Did you make any modifications to a default local configuration? Hide it behind a local proxy?

**Comment by fueko** [comment]
Hi @naz!

I see you have checked "mobiledoc" and the problem is only in "html" as below:

![Zrzut ekranu 2022-03-23 o 10 26 54](https://user-images.githubusercontent.com/23366922/159667758-0436790a-1802-418c-83ef-5abeb33606a2.png)

For me, the problem occurs in both localhost and production installations. I am not making any changes to the Ghost core.

**Comment by naz** [comment]
Yup! Confirming a bug. Will dig slightly deeper while in the context to find the cause.

From my local installation:
![Screenshot from 2022-03-28 11-48-16](https://user-images.githubusercontent.com/675397/160323330-6044e740-b447-4190-9637-20b3a4e6f6f9.png)

Something's up transforming `"customThumbnailSrc":"__GHOST_URL__/content/images/2022/03/68omdg.png"` into `transparent url('http://localhost:2368/content/images/2022/03/68omdg.png'`

**Comment by naz** [comment]
![Screenshot from 2022-03-31 19-24-37](https://user-images.githubusercontent.com/675397/161044444-18cb4aee-8d24-4f56-8b57-5d27e6c2abd2.png)

nice

**Comment by naz** [comment]
The product card is also broken. Investigating that now

**Comment by naz** [comment]
For the product card we have been generating an invalid HTML markup - used unqouted `src` attribute. @kevinansfield pointed out two places where the card has to start using qoutes:
- https://github.com/TryGhost/Koenig/blob/main/packages/kg-default-cards/lib/cards/product.js#L27
- https://github.com/TryGhost/Koenig/blob/main/packages/kg-default-cards/lib/cards/product.js#L43

**Comment by naz** [comment]
Tracking the cleanup migrations in https://github.com/TryGhost/Team/issues/449. As a workaround, the html should be regenerated once a buggy post is opened and save again.
