### ISSUE TITLE
Ghost changes "send-only" posts to "post and send" after rescheduling

### ISSUE THREAD

**Issue by coderecruit** [TryGhost/Ghost#14354]
### Issue Summary

Hello, I want to report a bug with Ghost.

As the title says, this issue happens when I reschedule a send-only post to members. 

Context, I use Ghost as a blog and send my newsletter without publishing on the blog. But I found a strange behavior when I click on reschedule for those send-only posts. 

So, when I go back to edit a post that was already scheduled to only send by email, I have to revert to draft, or rescheduling will turn this post into a "send & post" without me wanting it to happen. 

### Steps to Reproduce

1. Schedule a post to **send-only by email**
2. Exit the editor
3. Go back to the editor and update the post
4. Go to publish and click **Reschedule** the post
5. Look at the pop up in the bottom left saying the post will be "published and delivered" without you changing it (see screenshot below)

<img width="328" alt="CleanShot 2022-03-22 at 08 28 20@2x" src="https://user-images.githubusercontent.com/79269148/159449683-0ae8de80-f1d2-42c0-b616-949e7b74f8f3.png">
 

### Ghost Version

4.36.1

### Node.js Version

I'm using managed hosting, I don't know

### How did you install Ghost?

I'm using Midnight managed hosting

### Database type

Other

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by daniellockyer** [comment]
Thank you for the report! I can reproduce this so we shall take a look internally 🙂
