### ISSUE TITLE
Wordcount in editor does not work for RTL Languages (Arabic, or Hebrew) 

### ISSUE THREAD

**Issue by alfarhan** [TryGhost/Ghost#14365]
### Issue Summary

If i type Arabic words, the wordcounter in editor bottom does not work. I think this applies to RTL Languages. For your testing, i suggest you copy text from https://ar.lipsum.com/ 
this javascript works for RTL languages 
https://www.javascripttutorial.net/javascript-dom/javascript-word-counter/ 
![CleanShot 2022-03-23 at 00 10 15@2x](https://user-images.githubusercontent.com/2324349/159577003-0d913423-face-4efd-81e9-2c051b5a3424.png)

### Steps to Reproduce

1. add new post
2. copy Arabic text from https://ar.lipsum.com/
3. you'll notice the word counter does not change. 

### Ghost Version

4.41.0

### Node.js Version

latest

### How did you install Ghost?

self hosting on digitalocean

### Database type

MySQL 8

### Browser & OS version

all browsers

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by alfarhan** [comment]
as mentioned above, you can find other javascript codes which calculate RTL words (Arabic, Hebrew, etc..) correctly. For example here 
https://www.javascripttutorial.net/javascript-dom/javascript-word-counter/

**Comment by ErisDS** [comment]
This has been raised many times before and not been fixed. We're very happy to accept PRs improving this behaviour 😄

**Comment by alfarhan** [comment]
well.. unfortunately, the last code i wrote was 20 years ago 🙃

**Comment by avinasha** [comment]
@ErisDS to work on this issue, the `countWords` helper here needs to be updated. 
https://github.com/TryGhost/SDK/blob/main/packages/helpers/lib/utils/count-words.js#L20

Can I send a PR to that repo? How can I proceed?

**Comment by Emmanuel-Melon** [comment]
> @ErisDS to work on this issue, the `countWords` helper here needs to be updated. https://github.com/TryGhost/SDK/blob/main/packages/helpers/lib/utils/count-words.js#L20
> 
> Can I send a PR to that repo? How can I proceed?

Can I submit a PR to that repo?

**Comment by ErisDS** [comment]
The repo has PRs open - anyone is welcome to submit a PR. I cannot guarantee it will be merged but it will be reviewed.
