### ISSUE TITLE
MacOS text replacements get inserted automatically.

### ISSUE THREAD

**Issue by MrAtiebatie** [TryGhost/Ghost#14383]
### Issue Summary

I have a lot of text replacements for my Mac to replace a shortcode with a longer word/sentence. For example; eg gets replaced by e.g. 

However, the Ghost editor always inserts this text replacement no matter what. Normally it's after a space. The Medium editor handles this well though. 

For me, it's not possible to write my blog posts in the Ghost editor because of my text replacements.

### Steps to Reproduce

1. Add a text replacement for macOS in System Preferences -> Keyboard -> Text
2. Replace "eg" with "e.g."
3. Open the Ghost editor
4. Write egg

```
# Normally
eg+space -> e.g.
# Ghost editor:
egg -> e.g.g
```

### Ghost Version

4.33

### Node.js Version

v14.18.1

### How did you install Ghost?

Ghost CLI on Ubuntu 20.04

### Database type

MySQL 8

### Browser & OS version

MacOS Big Sur Version 11.6 - Chrome Version 99.0.4844.83 (Official Build) (arm64)

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by ErisDS** [comment]
I've not seen this crop up before. Would be happy to accept a PR improving the behaviour :)
