### ISSUE TITLE
Unable to Install Theme

### ISSUE THREAD

**Issue by SergeyTsalkov** [TryGhost/Ghost#14415]
### Issue Summary

When I go to Change Theme and preview a free theme, the page looks distorted (like the top of the page is cut off) and the button to install the theme is missing. Screenshot attached.
![ghost](https://user-images.githubusercontent.com/3589642/161410397-9ae55da1-679c-443c-910c-80fd10aefd6d.png)

### Steps to Reproduce

1. Go to settings
2. Click on Design
3. Click on Change Theme
4. Select any free theme, such as Journal
5. You see distorted preview page that's missing the button to install the theme.

### Ghost Version

4.42.0

### Node.js Version

16.14.2

### How did you install Ghost?

Ubuntu 20.04LTS

### Database type

MySQL 8

### Browser & OS version

Chrome 99.0.4844.84 on Windows 10

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by daniellockyer** [comment]
Thank you for the report 🙂 I can reproduce this so we shall investigate internally.

**Comment by daniellockyer** [comment]
This was fixed and released in Ghost 4.42.1 🙂
