### ISSUE TITLE
4.42.0 update erred out on ghost-cli/sqlite/knex (vscode?) deps

### ISSUE THREAD

**Issue by tobiasboyd** [TryGhost/Ghost#14413]
### Issue Summary

Doing a routine upgrade from 4.41.3 to 4.42 I got a node dep error.

### Steps to Reproduce

As root I updated npm to 8.6, and ghost-cli@latest. I switched to my ghost user, and did `ghost update` which erred out, saying `Cannot find module '@vscode/sqlite3'\n"` from the knex node package. It offered to roll back to the last version, but failed, and then the site wasn't able to be manually brought back up with `ghost restart` or `ghost start`. It's on a VM at DO, so I just reverted the whole VM to a recent backup to recover.

### Ghost Version

4.42

### Node.js Version

12.2

### How did you install Ghost?

ghost-cli

### Database type

SQLite3

### Browser & OS version

NA

### Relevant log / error output

```shell
Sorry, I was scrambling to get it back up so I only snagged `Cannot find module '@vscode/sqlite3'\n"` which seemed to be an error from `knex` - the fact that when the upgrade failed the offered rollback not working was making me sweat bullets! The output also suggested reinstalling `ghost-cli` to fix probs with `sqlite3` but when I tried that it didn't seem to change anything, either way `ghost doctor` didn't report anything wrong.
```

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by grndng** [comment]
Same here plus I can't even clean install on another server due to some dependency mismatch and a yarn error.

**Comment by helpme1** [comment]
I encounter exactly the same problem. Can't even revert back to old version with "ghost update --rollback"

**Comment by daniellockyer** [comment]
Please see [this comment](https://forum.ghost.org/t/ghost-local-installation-fail-because-of-sqlite3/29363/2) on the forum for the reason and fix 🙂
