### ISSUE TITLE
AMP pages have no alt text on images

### ISSUE THREAD

**Issue by nlaughton** [TryGhost/Ghost#14440]
### Issue Summary

This issue was reported by SEMRush. None of the /amp/ versions of the pages on our Ghost blog have alt text on the images.

It looks like <amp-img> supports the alt tag. Is there a reason it doesn't get set in the amp pages?

Thanks.

### Steps to Reproduce

1. Create a post with image
2. look at /amp page for that post

### Ghost Version

4

### Node.js Version

unknown

### How did you install Ghost?

Hosted by mymidnight

### Database type

SQLite3

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by ErisDS** [comment]
We'd welcome a PR to improve this feature.
