### ISSUE TITLE
{{tiers}} helper with custom prefix, separator, last separator, and/or suffix does not pass GScan

### ISSUE THREAD

**Issue by fueko** [TryGhost/Ghost#14452]
### Issue Summary

A theme includes `{{tiers}}` helper with custom prefix, separator, last separator, and/or suffix does not pass GScan.

E.g. using `{{tiers prefix="Access with:"}}` we receive an error during activation:
![Zrzut ekranu 2022-04-9 o 22 43 32](https://user-images.githubusercontent.com/23366922/162592830-7359fec0-1843-4e7f-b17f-fa892e9f0573.png)

Custom prefix, separator, last separator, and/or suffix are consistent with the documentation => https://ghost.org/docs/themes/helpers/tiers/

### Steps to Reproduce

1. Add a custom prefix, such as: `{{tiers prefix="Access with:"}}
2. Upload and activate the theme in the Ghost Admin.

### Ghost Version

4.43.0

### Node.js Version

v16.13.0

### How did you install Ghost?

production / ubuntu

### Database type

MySQL 5.7

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by naz** [comment]
Confirming the bug. Needs a fix in [gscan](https://github.com/TryGhost/gscan)

**Comment by daniellockyer** [comment]
@fueko Thanks for the report 🙂 This was fixed in Ghost v4.43.1

**Comment by naz** [comment]
Dzięki @fueko :pray:
