### ISSUE TITLE
Setting Publication Language to 'en_GB' rather than 'en' doesn't change spell check in editor

### ISSUE THREAD

**Issue by p-sims** [TryGhost/Ghost#14549]
### Issue Summary

We are publishing a website using Ghost in British English. We have set the Publication Language to 'en_GB' rather than 'en'. However even after doing so spell check in post editor still put red lines under words spelt correctly for English (UK), and then proposed US English spellings.
![Screenshot 2022-04-21 at 16 59 08](https://user-images.githubusercontent.com/64636731/164502342-774bc76f-23ad-49e2-a46d-c3d462d51efb.png)
 

### Steps to Reproduce

1) Change Publication Language to 'en_GB'
2) Type word 'characterise' into post editor and see if red line appears.

### Ghost Version

4.32

### Node.js Version

v14.18.1

### How did you install Ghost?

debian

### Database type

MySQL 8

### Browser & OS version

FireFox 98.0.2 (64-bit)

### Relevant log / error output

```shell
N/A
```

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by ErisDS** [comment]
To the best of my knowledge modern browsers do not provide a consistent, reliable API to set the language on a content editable field, instead the user's language choice in the browser is always preferred.  

If it was even possible, we'd then need to discuss whether changing the language in the editor is a desired impact of the language setting, as the current intention of the setting is to do with the output of the frontend.
 
As this is the first ever mention, I'm going to close for now as a wont/cant fix 🙂  Feel free to raise a feature request on the forum to see if there's wider interest & if anyone knows a way to do this reliably, then we can always revisit.
