### ISSUE TITLE
Sender email address gets set to Reply-to email when left blank

### ISSUE THREAD

**Issue by hkrsmk** [TryGhost/Ghost#14633]
### Issue Summary

If the sender email address is not set but the reply-to email is set, the sending is still from the reply-to email.

### Steps to Reproduce

1. Set a reply-to email
2. Leave sender email blank
3. Publish a test blog post
4. Observe that the sender email is the same as the reply-to email in the email header

### Ghost Version

4.46.0

### Node.js Version

14.19.1

### How did you install Ghost?

DigitalOcean one click

### Database type

MySQL 8

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by ErisDS** [comment]
Hey @hkrsmk, I can confirm this is the intended behaviour. Not sure what it was you had expected, but the sender address has to be set to something 🙂

**Comment by hkrsmk** [comment]
Oh - I meant it as the sender being set to noreply@domain instead of the reply-to email, actually. Does that make sense?
