### ISSUE TITLE
Lacking Proper Unicode/Multilingual Support for Post URL, HTML Tag ID

### ISSUE THREAD

**Issue by anaclumos** [TryGhost/Ghost#14662]
### Issue Summary

Let's face it — This is a long-standing issue. I have seen multiple posts on Ghost Forum and GitHub Issue that complains about the lacking proper support for Unicodes. These are some examples:

- #3224
- https://forum.ghost.org/t/feed-unicode-non-alphabet-characters-through-a-romanizer/6765
- https://forum.ghost.org/t/unicode-support-for-url/15216

More than half of the world lives in non-Roman sprachraums and I believe this can now be considered a **bug**. 🐛 

I know that Ghost 5 is imminent for shipping; I hope Ghost 5 adds proper **Multilingual Post Support** & **Unicode Support**.

### Steps to Reproduce

Type any Unicode character to Post URL or the editor. Ghost tends to not play well with non-Roman characters.

### Ghost Version

All types

### Node.js Version

All types

### How did you install Ghost?

All types

### Database type

Other

### Browser & OS version

All types

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by ErisDS** [comment]
Hi @anaclumos, I hear that you are frustrated by this, however you're asking for significant new functionalities to be created by somebody and that constitutes a feature request. 

I'd be more than happy to chat with contributors on the forum about how to get some of these things implemented.

**Comment by PopChicken** [comment]
I found all things about this feature are in a single file 'packages/string/slugify.js' under TryGhost/SDK repo. I believe simply changing its behavior into encodeURI should be a quick solution. In addition, it may be good to add some global config that enable some users using different languages to switch the behavior of slugify to encodeURI from default (as before), which also makes it transparent for most people who uses English.

**Comment by ErisDS** [comment]
@PopChicken you're correct, if we're going to change the slugify package we need to be extremely careful, as it is fundamental to many parts of Ghost.

We'd need to test the changes everywhere it's used, making sure that standard Ghost setups with Ghost CLI can handle the changes to data stored in the DB and the characters in the URL.

It's not a small piece of work :) 

That being said, I'm very keen for someone with expertise to make these changes and happy to support that. Hence why I suggested starting a conversation in the contributor section of the forum, where we can have deep chats about approach and plan what needs to be done to get a PR over the line.

**Comment by anaclumos** [comment]
Small side note, this was a dealbreaker for me and made me move away to other frameworks.
A much bigger global audience will feel this problem.
Alas, the global population is 6 times bigger than English sprachraums!
I am sure Ghost can tap into a much bigger international market if it properly supports i18n.
