### ISSUE TITLE
Ignoring invalid configuration option passed to Connection: filename.

### ISSUE THREAD

**Issue by boycottseattle** [TryGhost/Ghost#14735]
### Issue Summary

First off, I realize that the docker container isn't officially supported, but if you watch the log when connected to a MySQL database docker. You get this error again and again:

```Ignoring invalid configuration option passed to Connection: filename.```

The site appears to work fine, but unless you're watching the back end, you would never know. I'm certain the same thing happens on a regular ghost installation.

Thanks for looking into this.

### Steps to Reproduce

Watch the log of the Ghost docker or the backend of a regular ghost installation. You'll notice it for sure on boot / initialization of ghost.

### Ghost Version

4.47.0

### Node.js Version

I don't know the answer to that.

### How did you install Ghost?

Docker

### Database type

MySQL 8

### Relevant log / error output

```shell
Ignoring invalid configuration option passed to Connection: filename. This is currently a warning, but in future versions of MySQL2, an error will be thrown if you pass an invalid configuration option to a Connection
```

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by raccoonyy** [comment]
I tried to upload an image to my ghost blog that runs on docker and I met this error also.
But there are other messages like below:

```
Ignoring invalid configuration option passed to Connection: filename. This is currently a warning, but in future versions of MySQL2, an error will be thrown if you pass an invalid configuration option to a Connection
Ignoring invalid configuration option passed to Connection: filename. This is currently a warning, but in future versions of MySQL2, an error will be thrown if you pass an invalid configuration option to a Connection
[2022-05-16 07:59:33] ERROR Unknown Request error.

Unknown Request error.

"http://localhost:8080/favicon.ico"

Error ID:
    1f7c7d80-d4ee-11ec-a139-b9811e0b3309

Error Code:
    IMAGE_SIZE_URL

----------------------------------------

Error: connect ECONNREFUSED 127.0.0.1:8080
    at /var/lib/ghost/versions/4.47.1/core/server/lib/image/image-size.js:192:35
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:16)
```

**Comment by ErisDS** [comment]
This is a pure warning, it _cannot_ cause an issue with your site. We've got it tracked to get rid of the warning, but if you're seeing an issue - it's nothing to do with tis.

**Comment by raccoonyy** [comment]
I understand that you mentioned. Thank you.

But the image uploading is failing still.
I struggled for several days but I can't resolve it. 

My environment: Synology + Docker (It works well on my M1 laptop.)
I tried some variations like the below:
- ghost 4.47 / 4.32.3
- MySQL 8 / Sqlite3

This is one of my settings for the Synology docker container.
```
{
   "cap_add" : null,
   "cap_drop" : null,
   "cmd" : "node current/index.js",
   "cpu_priority" : 90,
   "devices" : null,
   "enable_publish_all_ports" : false,
   "enable_restart_policy" : true,
   "enabled" : true,
   "entrypoint_default" : "docker-entrypoint.sh",
   "env_variables" : [
      {
         "key" : "PATH",
         "value" : "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      },
      {
         "key" : "NODE_VERSION",
         "value" : "14.18.2"
      },
      {
         "key" : "YARN_VERSION",
         "value" : "1.22.15"
      },
      {
         "key" : "GOSU_VERSION",
         "value" : "1.12"
      },
      {
         "key" : "NODE_ENV",
         "value" : "production"
      },
      {
         "key" : "GHOST_CLI_VERSION",
         "value" : "1.18.1"
      },
      {
         "key" : "GHOST_INSTALL",
         "value" : "/var/lib/ghost"
      },
      {
         "key" : "GHOST_CONTENT",
         "value" : "/var/lib/ghost/content"
      },
      {
         "key" : "GHOST_VERSION",
         "value" : "4.29.0"
      },
      {
         "key" : "url",
         "value" : "http://localhost:2368"
      },
      {
         "key" : "database__connection__filename",
         "value" : "content/data/ghost.db"
      },
      {
         "key" : "database__client",
         "value" : "sqlite3"
      }
   ],
   "exporting" : false,
   "id" : "6bacb53a641f9f911511bcc47c5a2c8d29e355e2554dc6eebccb5ee4f910de4e",
   "image" : "ghost:latest",
   "is_ddsm" : false,
   "is_package" : false,
   "links" : [],
   "memory_limit" : 4294967296,
   "name" : "ghost",
   "network" : [
      {
         "driver" : "bridge",
         "name" : "bridge"
      }
   ],
   "network_mode" : "bridge",
   "port_bindings" : [
      {
         "container_port" : 2368,
         "host_port" : 2368,
         "type" : "tcp"
      }
   ],
   "privileged" : true,
   "shortcut" : {
      "enable_shortcut" : false
   },
   "use_host_network" : false,
   "volume_bindings" : []
}

```

**Comment by ErisDS** [comment]
On second thoughts with this - I think this issue is specific to the docker setup. 

It seems either the config file incorrectly has a mix of mysql & sqlite3 config, OR that the docker image is being run in development mode which pulls in the default sqlite3 config and then overriding that with a mysql DB.

If you're intentionally using docker for development that's fine, then you can simply ignore the warning as correct but irrelevant. If you're meant to be in production then that's a bigger problem.

The same issue has been raised on the [docker repo](https://github.com/docker-library/ghost/issues/310) and I suggest any discussion continues there.
