### ISSUE TITLE
Can not paginate RSS feed

### ISSUE THREAD

**Issue by djbusstop** [TryGhost/Ghost#14785]
### Issue Summary

I need to get access to all my posts via RSS. I would like to paginate my RSS feed so that I can import all my posts elsewhere. However, I have tried `mydomain.com/rss/2` to get the second page and it doesn't work. This is what I have found for how to paginate on ghost forums, so I'm filing a bug report.

### Steps to Reproduce

1. Navigate to Ghost URL + `/rss/2`
2. Redirects to  404 page

### Ghost Version

4.x

### Node.js Version

unknown

### How did you install Ghost?

Hosted

### Database type

Other

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by ErisDS** [comment]
Hi there @djbusstop, the RSS pagination behaviour was deliberately removed a some major versions ago. Instead Ghost has an extensive API & related tooling that you can use to get all of your content. If you need some help using it, reach out via the [forums](https://forum.ghost.org) and we'll give you a hand.
