### ISSUE TITLE
redirects.yaml documentation link points to 404

### ISSUE THREAD

**Issue by xdivby0** [TryGhost/Ghost#14888]
### Issue Summary

The page that's linked from ghost/#/settings/labs for redirects (anchor text "the docs") is nonexistent (anymore probably).

The url is https://ghost.org/tutorials/redirects-in-ghost/ and I also found that when searching on Google, so you better do a redirect to somewhere valid (probably https://ghost.org/tutorials/implementing-redirects) before Google starts de-ranking your 404 result :)

Thanks for the awesome platform by the way 👌

### Steps to Reproduce

1. visit https://ghost.org/tutorials/implementing-redirects
2. see 404

### Ghost Version

4.32

### Node.js Version

not sure but shouldn't matter

### How did you install Ghost?

dockerized

### Database type

SQLite3

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by ErisDS** [comment]
Thanks for the report, I've both updated the URL and fixed the 301.
