### ISSUE TITLE
Unable to upgrade to Ghost 5 from 4.48

### ISSUE THREAD

**Issue by Elrondo46** [TryGhost/Ghost#14916]
### Issue Summary

Unable to upgrade from 4.48

### Steps to Reproduce

Just ghost update and... not functionnal

### Ghost Version

4.48

### Node.js Version

v14.19.1

### How did you install Ghost?

Docker

### Database type

MySQL 8

### Browser & OS version

Alpine Linux, v3.14.6 (container)

### Relevant log / error output

```shell
the changelogs for full details:
* Ghost - https://github.com/tryghost/ghost/compare/v5.0.0...v5.0.1
* Admin - https://github.com/tryghost/admin/compare/v5.0.0...v5.0.1

🪄 Love open source? We're hiring [Node.js Engineers](https://careers.ghost.org/product-engineer-node-js) to work on Ghost full-time

✔ Fetched release notes
✔ Downloading and updating Ghost to v5.0.1
✖ Updating to a major version
An error occurred.
Message: 'SELECT value FROM settings WHERE `key` = "active_theme"; - SQLITE_ERROR: no such table: settings'
```

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by Elrondo46** [comment]
It's a bug from your tool, it upgrade all v4 versions and now it can't detect my database in settings.... It watch about SQLite... I'm in Mysql8 and I have active_theme key

**Comment by Elrondo46** [comment]
That's YOUR docker image I use

**Comment by ErisDS** [comment]
The Docker image is Docker's official Ghost image, and is maintained by the community.
