### ISSUE TITLE
[ghost admin] Inserting items doesn't work on mobile post/page editor

### ISSUE THREAD

**Issue by BirbEXE** [TryGhost/Ghost#14948]
### Issue Summary

On mobile, in either the post or page editor you cannot insert items suchas an image or web embed, without switching to the much less polished, disproportioned desktop site.

### Steps to Reproduce

on a new line, there is not a ➕ icon like the desktop editor, to add objects other than text.
also, typing a / on mobile, doesn't bring up a list like the plus button should.

### Ghost Version

latest [5.1.1]

### Node.js Version

NodeJS v16.14.2

### How did you install Ghost?

Hosted on a digitalocean droplet. Ubuntu 20.04

### Database type

MySQL 8

### Browser & OS version

Google Pixel 5, Chrome [all UTD]

### Code of Conduct

- [x] I agree to be friendly and polite to people in this repository

**Comment by pelmers** [comment]
just a heads-up I sent a pull request for this issue at https://github.com/TryGhost/Admin/pull/2417

**Comment by ErisDS** [comment]
Hey @pelmers - Thank you for the report and for your PR. The PR has been merged, hopefully this is fixed now :)
