### ISSUE TITLE
‘ copyError is not a function’ on request for new staff member password

### ISSUE THREAD

**Issue by luytendries** [TryGhost/Ghost#14975]
### Issue Summary

When requesting a new password via the “Forgot?” link on the backend login page /ghost staff users get the message ‘copyError is not a function’ and nothing else happens.

### Steps to Reproduce

1. Go to the admin login page
2. Click “Forgot?” after entering your password and Password (you thought you still remembered)
3. The message “copyError is not a function” appears beneath the Sign in button

### Ghost Version

5.2.2

### Node.js Version

16.14.2

### How did you install Ghost?

On Ubuntu via Digital Ocean marketplace

### Database type

MySQL 8

### Browser & OS version

Chrome

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by luytendries** [comment]
I was the bug. Not Ghost. Sorry!

**Comment by cowang4** [comment]
@luytendries What was the issue? I'm having the same problem.

**Comment by luytendries** [comment]
> @luytendries What was the issue? I'm having the same problem.

It has been a while, but probably some incorrect smpt mail settings in the package.json file. ;)

Let me know if you've solved it, and if not what you've tried. We'll solve it. ;)

**Comment by cowang4** [comment]
Thanks for replying, I did fix it, and the issue was SMTP settings in the config.production.json. By following https://ghost.org/docs/config/#mail and using secure SMTP settings I got it to work.
