### ISSUE TITLE
The submission page for new themes not working

### ISSUE THREAD

**Issue by tsubasa-majid** [TryGhost/Ghost#14974]
### Issue Summary

Hi,
The submission page for new themes not working, even though I check all theme requirements, the button submit still not showing.

<img src="https://aws1.discourse-cdn.com/business4/uploads/ghost2/optimized/3X/a/5/a56cad8eacd3ca1bbdc80e4f26a3ba049b4485a7_2_260x500.jpeg" alt="">
Thanks.

### Steps to Reproduce

1. I expect that the submit button will apear when I check all theme requirements list

### Ghost Version

5.0

### Node.js Version

16

### How did you install Ghost?

lcoally

### Database type

MySQL 8

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by daniellockyer** [comment]
Hey @tsubasa-majid, thanks for the report - we'll take a look. I'll close this for now as it doesn't relate to Ghost-as-software.

In the mean time, could you tell us which browser and browser version you're using? 🙂

**Comment by tsubasa-majid** [comment]
Hey @daniellockyer, I use Google Chrome and Firefox (Latest version)

**Comment by tsubasa-majid** [comment]
It's working now. Thanks
