### ISSUE TITLE
Meta tags missing on pages that are not the 1st page

### ISSUE THREAD

**Issue by miloradb-podium** [TryGhost/Ghost#14978]
### Issue Summary

There are Twitter and OpenGraph tags missing when you go further from the first page.
I have {{ghost_head}} imported correctly in my .hbs file. On the fedault(1st page) everything works fine(you can see in the image below
![Screenshot_2](https://user-images.githubusercontent.com/105811684/174386459-18668e33-19ff-4e40-9fe7-8878634b1075.png)
)
But when I go to the second page of that tag, meta tags disappear. OG and Twitter ones.
![Screenshot_3](https://user-images.githubusercontent.com/105811684/174386768-77b3b10d-4eca-4b60-80a2-5fc8671fe581.png)

Looks like it's losing the tags or that "_.includes(context, **'page'**)" is not considered. Can anyone help?

### Steps to Reproduce

Go to the ghost page that has multiple post pages.
Go to the second page, there should be Twitter and OpenGraph meta tags missing.

### Ghost Version

Ghost-CLI version: 1.21.0 Ghost version: 3.5.2

### Node.js Version

v16.13.0

### How did you install Ghost?

 npm install ghost-cli@latest -g and then  npm install ghost-cli@latest -g

### Database type

Other

### Browser & OS version

Chrome, Windows 10

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by ErisDS** [comment]
Hi @miloradb-podium, thanks for the report. What you're describing is expected behaviour, as having duplicate meta on the subsequent pages would be bad for SEO.
