### ISSUE TITLE
Error when parsing bookmark cards

### ISSUE THREAD

**Issue by Majirefy** [TryGhost/Ghost#14973]
### Issue Summary

When I copy a URL to my post and it turns to Bookmark card automatically.
But for some site(e.g. some Chinese site), it fails to parse correct content with error encoding. Some fails to fetch icon and thumbnail preview. It’s not site problem, I am sure there is something wrong with Ghost cause I can get these correctly in other CMS system.

### Steps to Reproduce

Please try to paste these in post:

http://slide.news.sina.com.cn/slide_1_86058_547338.html#p=1

https://new.qq.com/omn/20220613/20220613A0A3G200.html

![](https://aws1.discourse-cdn.com/business4/uploads/ghost2/original/3X/0/5/05c28b59479a84620b726c41e38a7224d0f048dd.jpeg)

### Ghost Version

5.2.2

### Node.js Version

16.15.1

### How did you install Ghost?

Follow official tutorial.

### Database type

MySQL 8

### Browser & OS version

Ubuntu 20.04LTS

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by ErisDS** [comment]
Hey there, thank you so much for the detailed bug report.

That does look like something that shouldn't happen! A PR to fix this issue would be very welcome 🙂

**Comment by h2akim** [comment]
Hi @Majirefy,

I might need your help to verify the parsing result. I saw that there are like repetition of `锟斤` characters. Is it normal and correct is render correctly or at least readable?

<img width="766" alt="Screenshot 2022-10-10 at 1 03 42 AM" src="https://user-images.githubusercontent.com/514048/194770003-2c5cbb20-55d3-4613-95e1-493bd66cc0d6.png">

Thanks
