### ISSUE TITLE
[Content API] Url set to 404 for tags when using multiple fields

### ISSUE THREAD

**Issue by benjaminrancourt** [TryGhost/Ghost#14983]
### Issue Summary

When using multiple [fields](https://ghost.org/docs/content-api/#fields) on the Content API, the tag URLs are set to `https://demo.ghost.io/404/` instead of their corresponding URL.

### Steps to Reproduce

✅ https://demo.ghost.io/ghost/api/content/tags/?key=22444f78447824223cefc48062&filter=visibility%3Apublic&fields=name

```json
{
  "tags": [
    {
      "name": "Fables"
    },
    {
      "name": "Fiction"
    },
    {
      "name": "Getting Started"
    },
    {
      "name": "Speeches"
    }
  ],
  "meta": {
    "pagination": {
      "page": 1,
      "limit": 15,
      "pages": 1,
      "total": 8,
      "next": null,
      "prev": null
    }
  }
}
```

✅ https://demo.ghost.io/ghost/api/content/tags/?key=22444f78447824223cefc48062&filter=visibility%3Apublic&fields=url
```json
{
  "tags": [
    {
      "url": "https://demo.ghost.io/tag/fables/"
    },
    {
      "url": "https://demo.ghost.io/tag/fiction/"
    },
    {
      "url": "https://demo.ghost.io/tag/getting-started/"
    },
    {
      "url": "https://demo.ghost.io/tag/speeches/"
    }
  ],
  "meta": {
    "pagination": {
      "page": 1,
      "limit": 15,
      "pages": 1,
      "total": 8,
      "next": null,
      "prev": null
    }
  }
}
```

❌ https://demo.ghost.io/ghost/api/content/tags/?key=22444f78447824223cefc48062&filter=visibility%3Apublic&fields=name,url
❌ https://demo.ghost.io/ghost/api/content/tags/?key=22444f78447824223cefc48062&filter=visibility%3Apublic&fields=url,name
❌ https://demo.ghost.io/ghost/api/content/tags/?key=22444f78447824223cefc48062&filter=visibility%3Apublic&fields=name%2Curl
❌ https://demo.ghost.io/ghost/api/content/tags/?key=22444f78447824223cefc48062&filter=visibility%3Apublic&fields=url%2Cname
```json
{
  "tags": [
    {
      "name": "Fables",
      "url": "https://demo.ghost.io/404/"
    },
    {
      "name": "Fiction",
      "url": "https://demo.ghost.io/404/"
    },
    {
      "name": "Getting Started",
      "url": "https://demo.ghost.io/404/"
    },
    {
      "name": "Speeches",
      "url": "https://demo.ghost.io/404/"
    }
  ],
  "meta": {
    "pagination": {
      "page": 1,
      "limit": 15,
      "pages": 1,
      "total": 8,
      "next": null,
      "prev": null
    }
  }
}
```

### Ghost Version

5.2.3

### Node.js Version

16

### How did you install Ghost?

Docker

### Database type

MySQL 8

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by matthanley** [comment]
Closing as a dup of https://github.com/TryGhost/Ghost/issues/10396, because it's the same underlying issue.
