### ISSUE TITLE
Tenor V1 API has been decomissioned, unable to load Gifs from editor.

### ISSUE THREAD

**Issue by arsereg** [TryGhost/Ghost#14980]
### Issue Summary

Whenever trying to insert a gif from Tenor on the editor, the error "Unable to connect to Tenor, please check your connection" intermittently appears. The reason for this is that Tenor V1 API has been deprecated and migrated to a Google Api.

### Steps to Reproduce

1. Start writing a Post or a new Page
2. on the editor enter the `/tenor` command to open the GIF Search card
3. Tenor will display the error `Uh oh! Trouble reaching the Tenor API, please check your connection`

### Ghost Version

5.2

### Node.js Version

16.15.0

### How did you install Ghost?

Docker

### Database type

MySQL 8

### Browser & OS version

Chrome, Mac OS Monterey 12.4

### Relevant log / error output

```shell
GET https://g1.tenor.com/v1/trending?media_filter=minimal&key=null&contentfilter=off 401 (Unauthorized)
```

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by ErisDS** [comment]
Thank you for reporting this, we'll take a look at the PRs ASAP.

**Comment by ErisDS** [comment]
Hey @arsereg thank you for bringing this to our attention & taking the time to get the ball rolling on the changes required. !

@markstos thanks to you too for asking all the important questions about the changes, this made it easier for us to review the PR :) 

The first part is merged, the second part will be merged later this week after we merge admin into the monorepo, and before Friday's automated release.

Really appreciate all the time and effort here!

**Comment by ErisDS** [comment]
Thanks again for this @arseg & @markstos. These changes will be in the next release of Ghost & changes to docs will go live shortly.
