### ISSUE TITLE
Cannot connect to database

### ISSUE THREAD

**Issue by altyne** [TryGhost/Ghost#14995]
### Issue Summary

Stop after starting the image.

But you connect manually using CLI or any database clients I was able to connect.

MariaDB 10.5.16

### Steps to Reproduce

1. Install the image from Unraid community application - bitnami/latest
2. Start the image

### Ghost Version

bitnami/ghost:latest 5.2.3

### Node.js Version

14.19.3

### How did you install Ghost?

Thru Unraid community app 

### Database type

Other

### Browser & OS version

Vivaldi / Windows 10

### Relevant log / error output

```shell
ghost 17:41:22.74 Welcome to the Bitnami ghost container
ghost 17:41:22.75 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-ghost
ghost 17:41:22.75 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-ghost/issues
ghost 17:41:22.75 
ghost 17:41:22.75 INFO  ==> Configuring libnss_wrapper
ghost 17:41:22.76 INFO  ==> Validating settings in MYSQL_CLIENT_* env vars
ghost 17:41:22.79 INFO  ==> Ensuring Ghost directories exist
ghost 17:41:22.79 INFO  ==> Trying to connect to the database server
ghost 17:42:22.90 ERROR ==> Could not connect to the database
```

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by ErisDS** [comment]
This looks like something Bitnami specific. I recommend posting in the [Bitnami repo](https://github.com/bitnami/bitnami-docker-ghost/issues) (shown in the error logs you pasted) in order to get support from other Bitnami users who will more likely be able to help you.
