### ISSUE TITLE
[ERROR] "Schedule for later" on publishing does not work

### ISSUE THREAD

**Issue by reraxe** [TryGhost/Ghost#14999]
### Issue Summary

I scheduled a post, and it did not publish on the date/time of scheduling.

I have tried publishing 5 minutes advance and it did not work.

Regular publishing works, not scheduling.

### Steps to Reproduce

On Posts/Drafts/blog/editor

1. Publish
2. Schedule for later
3. In 5 minutes (In my case, I tried to schedule a week in advance)
4. Continue, final review
5. Publish post, on ...
6. All set! Your post will be published today at ...

### Ghost Version

ghost:5.2.3

### Node.js Version

v16.15.1

### How did you install Ghost?

Docker & amd64

### Database type

SQLite3

### Browser & OS version

Edge & Version 103.0.1264.44 (Official build) (64-bit)

### Relevant log / error output

```shell
[2022-07-04 14:43:17] INFO "GET /content/images/2021/11/2745c156-cc72-4615-a2f8-cb962ef92266.png" 200 2ms
(node:1) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 committed listeners added to [Function]. Use emitter.setMaxListeners() to increase limit
(Use `node --trace-warnings ...` to show where the warning was created)
[2022-07-04 14:43:31] INFO "PUT /ghost/api/admin/posts/62af758dcf04f70001e09b3a/" 200 587ms
[2022-07-04 14:43:31] INFO "GET /content/images/2022/06/fuelfilter.png" 200 7ms
[2022-07-04 14:43:31] INFO "GET /content/images/size/w256h256/2022/07/favicon-1.png" 200 4ms
[2022-07-04 14:48:26] ERROR The server has encountered an error.
The server has encountered an error.
Error ID:
    5c263c90-fba8-11ec-a1cb-450ae2361ad4
----------------------------------------
HTTPError: Response code 302 (Moved Temporarily)
    at /var/lib/ghost/versions/5.2.3/core/server/adapters/scheduling/SchedulingDefault.js:319:23
    at EventEmitter.<anonymous> (/var/lib/ghost/versions/5.2.3/node_modules/got/source/as-promise.js:74:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```
Also posted issues on: https://github.com/docker-library/ghost/issues/316#issue-1293327851

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by ErisDS** [comment]
The scheduling functionality works by Ghost sending an HTTPS request to itself to trigger the publish. Scheduling is working in general, therefore I assume this is related to your docker setup and the issue there (or posting on the forum) would be the best way to get useful support from other docker users 🙂
