### ISSUE TITLE
Always failed when installing ghost locally with an error message: Cannot read properties of undefined (reading 'statusCode')

### ISSUE THREAD

**Issue by tcmonster** [TryGhost/Ghost#14991]
### Issue Summary

✔ Checking system Node.js version - found v16.13.0
✔ Checking current folder permissions
✔ Checking memory availability
✔ Checking free space
✖ Checking for latest Ghost version
An error occurred.
Message: 'Cannot read properties of undefined (reading 'statusCode')'

Debug Information:
    OS: macOS, v12.4
    Node Version: v16.13.0
    Ghost-CLI Version: 1.21.0
    Environment: development
    Command: 'ghost install local'

Additional log info available in: /Users/tc/.ghost/logs/ghost-cli-debug-2022-06-29T17_44_54_226Z.log

### Steps to Reproduce

run ghost install local

### Ghost Version

1.21

### Node.js Version

16.13

### How did you install Ghost?

macOS, v12.4

### Database type

SQLite3

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by tcmonster** [comment]
I found that something error with my network connection
and i fixed this issue by configuring a proxy

**Comment by ztm0929** [comment]
> I found that something error with my network connection and i fixed this issue by configuring a proxy

@tcmonster Hi, 具体是如何解决的？我好像成功配置了代理依然报错。

**Comment by tcmonster** [comment]
> > I found that something error with my network connection and i fixed this issue by configuring a proxy
> 
> @tcmonster Hi, 具体是如何解决的？我好像成功配置了代理依然报错。

我不清楚你的网络情况，我好像就是给命令行开了个梯子就好了，你试下全局代理
