### ISSUE TITLE
Cannot get reading time from API via ?fields param

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#15007]
### Issue Summary

When making a request to the Content API for posts and including `reading_time` as a field, it is not returned.

### Steps to Reproduce

Request the demo site with `reading_time`:

https://demo.ghost.io/ghost/api/canary/content/posts/?key=22444f78447824223cefc48062&fields=title,url,reading_time

Note that it does work if you include the `html` field, which reading time is calculated based on.

https://demo.ghost.io/ghost/api/canary/content/posts/?key=22444f78447824223cefc48062&fields=title,url,reading_time,html

### Ghost Version

5.2

### Node.js Version

14

### How did you install Ghost?

ghost cli

### Database type

MySQL 8

### Browser & OS version

N/a

### Relevant log / error output

```shell
n/a
```

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by raulmar0** [comment]
I have the exact problem. I've seen that when you request some specific fields you need to try with slightly different names than the ones marked on the fields from the GET/posts response. For example, in the GET/posts response it is marked "tags" in plural but when you add the "&fields" to the request you need to put "tag" in singular. Although I haven't found the correct name for reading_time.

**Comment by devvrat011** [comment]
Sir plss assign this to me. I can fix this bug

**Comment by as-ajitsingh** [comment]
Field `reading_time` doesn't work if field `html` is not present. You need to add field `html` too to get it.
