### ISSUE TITLE
Custom pagination not work on next page, but default pagination worked on next page

### ISSUE THREAD

**Issue by GrigoriySchetintsev** [TryGhost/Ghost#15000]
### Issue Summary

Custom pagination not work on next page, but default pagination worked on next page.

### Steps to Reproduce

Example FAQ page
```hbs
{{#get "posts" filter="tag:faq" limit=@config.posts_per_page order="published_at desc" page=pagination.page}}
{{#foreach posts visibility="all"}}
{{/foreach}}
{{pagination}}
{{/get}}
```
1. Run on as default pagination template. First page - Ok, second page - Ok.
2. Create custom pagination.hbs like default
3. Run on custom pagination.hbs. First page - Ok, second page - not ok (blank #get)

### Ghost Version

5.2.4

### Node.js Version

16.15.0

### How did you install Ghost?

ghost local

### Database type

SQLite3

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by ErisDS** [comment]
Hi @GrigoriySchetintsev thanks for the report.  Pagination applies to a set of pages at the routing level, the get helper fetches data to render inside a portion of a page. Therefore the pagination helper is not expected to work inside of a get helper call.

It sounds like what you're looking for is actually [dynamic routing](https://ghost.org/docs/themes/routing/) and probably a custom collection or channel.

**Comment by GrigoriySchetintsev** [comment]
Hi @ErisDS sounds very strange...
But the pagination helper works in the get helper, not the user one, but the base one!

Only the custom pagination does not work.

No, I'm not interested in dynamic routing or collections (this is just used in a collection), I need to page out a large amount of articles and use a custom **pagination.hbs** for this.

Perhaps you need to explain why basic pagination works in a get helper, but custom pagination does not.

**Comment by GrigoriySchetintsev** [comment]
@ErisDS Perhaps I will repeat myself, but why then does pagination work correctly in the get helper if I do not create a custom component pagination.hbs?

The paginator installed in the get works correctly if you do not create your own pagination.hbs!!! Page transitions work!

So far I don't see an answer to this question.

**Comment by ErisDS** [comment]
If you need further help with how Ghost works, please use the [forum](https://forum.ghost.org/).

**Comment by GrigoriySchetintsev** [comment]
It is a pity that the developers themselves are not able to explain why the product they have created works the way they say it should not work and send it to the forum ... not very friendly.

Thanks to.

**Comment by ErisDS** [comment]
You raised a bug which is not a bug, and I have closed it with a clear explanation (twice) that it is not a bug and why. That is what GitHub is for - managing bug reports and contributions.

You're asking for support to understand how the product works and why, which is great, but that conversation belongs in the community of users on the forum. It does not belong here in GitHub where it is actively detracting from my ability to support our contributors.
