### ISSUE TITLE
No manifest for amd64 in 5.3 specific tags (Dockerhub)

### ISSUE THREAD

**Issue by neilmfrench** [TryGhost/Ghost#15021]
### Issue Summary

Only arm digests seem to be uploaded, but the latest tag seems to have the amd64 digest. 

### Steps to Reproduce

1. Go to https://hub.docker.com/_/ghost?tab=tags
2. Look at the 5.3 specific images and check the digests

### Ghost Version

5.3.0

### Node.js Version

N/A

### How did you install Ghost?

Docker

### Database type

MySQL 8

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by daniellockyer** [comment]
Hey @neilmfrench - the Ghost Docker image is a community effort and is not maintained by the Ghost Core team. You'll need to go and open an issue on their repo: https://github.com/docker-library/ghost
