### ISSUE TITLE
built-in site search functionality

### ISSUE THREAD

**Issue by yannickcof** [TryGhost/Ghost#15025]
### Issue Summary

Doesn't seem to be working!
Do we need to enable something or ... ?

### Steps to Reproduce

upgrade to 5.3.1

### Ghost Version

5.3.1

### Node.js Version

1.21.0

### How did you install Ghost?

linux

### Database type

MySQL 8

### Browser & OS version

Chrome Version 103.0.5060.114

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by daniellockyer** [comment]
Hi @yannickcof - the feature will work out-of-the-box if you've followed the docs: https://ghost.org/docs/themes/search/

If you need help setting it up, I'd suggest posting on the forum: https://forum.ghost.org/
