### ISSUE TITLE
Lazy loading images above the fold breaks CLS

### ISSUE THREAD

**Issue by ThomasArdal** [TryGhost/Ghost#15042]
### Issue Summary

Lazy loading images in Ghost 4 is a nice improvement. But it looks to include a lazy loading attribute on all images and not just the images below the fold. Marking images shown above the fold with lazy makes Cumulative Layout Shift (CLS) in PageSpeed Insights break with the following message:

> Above-the-fold images that are lazily loaded render later in the page lifecycle, which can delay the largest contentful paint.

### Steps to Reproduce

1. Add a new image section in the top of a Ghost post.
2. The `img` element is marked with `loading="lazy"`.

### Ghost Version

5.2.3

### Node.js Version

12

### How did you install Ghost?

DigitalOcean

### Database type

MySQL 8

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by ErisDS** [comment]
I am not sure how we would approach calculating what is/isn't above the fold, given that Ghost has custom theme support. This seems to me like it's really an issue with the browser's interpretation / implementation of lazy-load (after all - in a dynamic contact environment the browser has a more information than the server about how content is going to render). 

However, I'd love to hear any ideas you have about how to solve this.

**Comment by ThomasArdal** [comment]
I totally understand why it is not possible to make this dynamic. Maybe a setting on the image when uploading it on Ghost and including it in the post.

**Comment by ErisDS** [comment]
This is not the kind of thing we put into the UI because the majority of our users are non-technical and wouldn't know what to do with it.

**Comment by ThomasArdal** [comment]
Yeah, I guess you're right. Not sure how this could be done. Let's close.

**Comment by ErisDS** [comment]
Cool ok - I'm totally all ears for any suggestions anyone comes up with for how to solve this - but I am fairly sure this is one of those things that either requires additions to the spec for lazy loading or the browsers will have to sort amongst themselves.
