### ISSUE TITLE
Post previews have unformatted markdown

### ISSUE THREAD

**Issue by tonilampela** [TryGhost/Ghost#15049]
### Issue Summary

Not sure when this got broken, but after updating to 5.4.1 I noticed that on my blog's home page post preview texts display unformatted markdown - e.g. clickable URLs are not showing etc. Tried with different themes (including Casper) and the issue remains.

### Steps to Reproduce

1. Update to latest version of Ghost
2. Witness that your post previews display markdown unformatted

### Ghost Version

5.4.1

### Node.js Version

14.20.0

### How did you install Ghost?

Ubuntu 20.04.4 LTS

### Database type

MySQL 8

### Browser & OS version

Safari, Firefox / macOS 12

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by tonilampela** [comment]
Think I figured this out... At some point posts had been converted into markdown "blocks" when viewing them in the editor. Cutting the text, removing the markdown block and then pasting text back into editor fixed the issue.

**Comment by ErisDS** [comment]
Glad you figured it out 🙂
