### ISSUE TITLE
EADDRINUSE https port is not available no matter where set

### ISSUE THREAD

**Issue by wibed** [TryGhost/Ghost#15047]
### Issue Summary

i am currently using a reverse proxy to access ghost via https, but the installation runs on http.
it has been impossible to map a https port successfully for ghost as it returns the EADDRINUSE error and stops working.

this is a serious problem, because id like to use the portal feature.

i tried manually changing the port: 
  which resulted in the same error as above

### Steps to Reproduce

https://bitnami.com/stack/ghost

install on your preferred kubernetes solution.
i am running rancher desktop, which works fine.

try to enable https using `ghostEnableHttps` option.
the `containerPorts` parameter allows you to specify the port the application will listen to.
default is 2368

### Ghost Version

5.2.4

### Node.js Version

14.19.3

### How did you install Ghost?

helm chart

### Database type

MySQL 8

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by ErisDS** [comment]
I recommend trying bitnami's own community to get help with this issue.
