### ISSUE TITLE
Potential Search (speed) problem

### ISSUE THREAD

**Issue by rusty1281** [TryGhost/Ghost#15066]
### Issue Summary

Hello!

Just wanted to see if anyone has a similar experience with the new search functionality. It works great no problem at all, but I did notice that since moving to 5.3.1 the other day, all of my instances behave the same (regardless of the browser or device).

What happens is that if I invoke search over a keyboard shortcut or a button/link it can take up to 20-30 seconds for the search to appear. At the same time, all links on the page are not clickable (menu items, posts, nothing). After some time, the search box pops up, and after that, it is all fine. Then after a while, the same things happen.

I have just now updated to 5.4.1, and after a fresh boot, all instances are working as intended, search pops up instantly.

### Steps to Reproduce

Trying to invoke search, causes a delay

### Ghost Version

5.3.1

### Node.js Version

16.16.0

### How did you install Ghost?

Docker image on a Synology NAS (last 5years)

### Database type

MySQL 8

### Browser & OS version

Any macOS or iOS device using both Safari or Amazon browser

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by daniellockyer** [comment]
Hey @rusty1281 👋🏻 I believe this issue was opened when unpkg, the CDN we use to serve the search JS script, was having issues. In Ghost v5.5.0, we've switched to jsDelivr, which is a much bigger CDN with more redundancy.

If you'd like to update Ghost to v5.5.0, downtime of the search script should now be much less likely. 🙂

**Comment by rusty1281** [comment]
Tnx for the info! Waiting for the docker image update!
