### ISSUE TITLE
Ghost docker container exits when trying to upload admin profile cover photo.

### ISSUE THREAD

**Issue by DillFrescott** [TryGhost/Ghost#15109]
### Issue Summary

Ghost docker container exits when trying to upload admin profile cover photo.

### Steps to Reproduce

1. Try to upload cover photo as main admin.
2. Docker container exits

### Ghost Version

5.5.0 (I think) It's just the latest container as of this post.

### Node.js Version

I would assume 18 but I have no idea what version it runs internally. I'm sorry!

### How did you install Ghost?

Docker on Linux

### Database type

SQLite3

### Browser & OS version

Brave Browser | Windows 11 Pro

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by DillFrescott** [comment]
Update: No error in the docker container, just a clean exit

**Comment by ErisDS** [comment]
Hi there @DillFrescott - the Ghost Docker image is a community effort and is not maintained by the Ghost Core team. You'll probably be better off opening an issue on their repo: [docker-library/ghost](https://github.com/docker-library/ghost).
