### ISSUE TITLE
Port should be 465 for secure emails in config.production

### ISSUE THREAD

**Issue by anujdeshpande** [TryGhost/Ghost#15133]
### Issue Summary

https://ghost.org/docs/config/#mail

Above documentation says that after adding secure as true, and setting the port should be 587. That doesn't work and it throws a ssl version error in the logs.

### Steps to Reproduce

1. Set up new ghost instance
2. Connect mailgun
3. Configure mailgun with https://ghost.org/docs/config/#mail 
4. Opt for secure connection

### Ghost Version

5.7.0

### Node.js Version

16.16.0

### How did you install Ghost?

Instructions for Ubuntu

### Database type

MySQL 8

### Relevant log / error output

```shell
Aug 03 06:13:04 ip-172-26-8-210 node[4272]: [2022-08-03 06:13:04] ERROR Failed to send email. Reason: 13966910>
Aug 03 06:13:04 ip-172-26-8-210 node[4272]: .
Aug 03 06:13:04 ip-172-26-8-210 node[4272]: 
Aug 03 06:13:04 ip-172-26-8-210 node[4272]: Failed to send email. Reason: 139669108275136:error:1408F10B:SSL r>
Aug 03 06:13:04 ip-172-26-8-210 node[4272]: .
Aug 03 06:13:04 ip-172-26-8-210 node[4272]: "Please see https://ghost.org/docs/config/#mail for instructions o>
Aug 03 06:13:04 ip-172-26-8-210 node[4272]: Error ID:
Aug 03 06:13:04 ip-172-26-8-210 node[4272]:     55a59020-12f3-11ed-85cb-5fb445e8b2d5
Aug 03 06:13:04 ip-172-26-8-210 node[4272]: Error Code: 
Aug 03 06:13:04 ip-172-26-8-210 node[4272]:     ESOCKET
Aug 03 06:13:04 ip-172-26-8-210 node[4272]: ----------------------------------------
Aug 03 06:13:04 ip-172-26-8-210 node[4272]: Error: 139669108275136:error:1408F10B:SSL routines:ssl3_get_record>
Aug 03 06:13:04 ip-172-26-8-210 node[4272]: .
```

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by ErisDS** [comment]
I've submitted a patch to our docs internally, and this issue will auto-close once the patch is added to the site.
