### ISSUE TITLE
Disable "sodo-search" (Premium Search)

### ISSUE THREAD

**Issue by joseftw** [TryGhost/Ghost#15162]
### Issue Summary

I updated my ghost instance and now the following javascript file are loaded:

```
https://cdn.jsdelivr.net/npm/@tryghost/sodo-search@~1.1/umd/sodo-search.min.js - 94,37 KB (277,88 KB size)
```
I assume that this is related to the new search feature: https://forum.ghost.org/t/native-search-ghost-changelog/31303
I don't want to use this feature, how do I disable it so that Ghost doesn't load this JS file?

### Steps to Reproduce

- Update Ghost to the latest version
- Navigate to home page
- Inspect the network requests, sodo-search.min.js is loaded.

### Ghost Version

5.7.0

### Node.js Version

16

### How did you install Ghost?

Self hosted on Ubuntu

### Database type

MySQL 8

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by ErisDS** [comment]
Exact details can be found here: https://forum.ghost.org/t/is-it-possible-to-disable-jsdelivr-cdn/31761/6

**Comment by joseftw** [comment]
Thank you @ErisDS .
Going forward, it would be awesome if new features could be enabled/disabled in the admin, maybe in the Labs section? Thank you again! :)

**Comment by yetithefoot** [comment]
Hello, I use hosted Ghost 5.22 and after update, PageSpeed Performance results decreased a bit. I do not use the search on my blog, but the page loads sodoSearch anyway. Is there a way to disable unused scripts?

**Comment by angelopublio** [comment]
I'm looking for this solution too.

I'm using Ghost(Pro) with a custom theme and I need to disable the sodo-search JavaScript to increase the PageSpeed score.

**Comment by PeterDRasmussen** [comment]
Same here.. I tried the Ghost forum but the question got closed:
https://forum.ghost.org/t/disabling-sodo-search-min-js-script-on-ghost-blog/31934

I have also written to support. So they are aware of this.

**Comment by yetithefoot** [comment]
@ErisDS I see that the solution for original issue related to the self-hosted version is resolved in the linked post's comment. 

However, for managed Ghost Pro version the `sodosearch.min.js` file is [**always loaded**](https://github.com/TryGhost/Ghost/blob/d6af8fbb8f68e3f094186e0bef25a04e4335e7ab/ghost/core/core/frontend/helpers/ghost_head.js#L217)to the page. It hurts PageSpeed ratings 😞 

Is there any recommendation on how to avoid such behavior? I'm more than happy to contribute, just point me in the right direction.

**Comment by cathysarisky** [comment]
I've got a PR (https://github.com/TryGhost/Ghost/pull/21229)  in that should make this possible, along with lots of other stuff, @yetithefoot .  Unless you're on one of the starter plans that doesn't allow loading a theme.

**Comment by yetithefoot** [comment]
Until the PR is merged you may use a workaround and override CSP headers in HTML. It should be placed before sodo-search script tag, in my case in default.hbs.

```html
  <meta
    http-equiv="Content-Security-Policy"
    content="script-src 'self' cdnjs.cloudflare.com www.googletagmanager.com" />
```

The downside is that you have to specify every domain/URL there except sodo-search.js. Works for us as a workaround.
