### ISSUE TITLE
"toggle" sections don't render/work correctly

### ISSUE THREAD

**Issue by ItsIgnacioPortal** [TryGhost/Ghost#15188]
### Issue Summary

When editing a post, there's an option to add a "Toggle" section. They don't seem to render correctly neither in Chromium nor in Firefox. They only look normal when viewed from the editor.

A "Toggle" section as viewed in the editor from Firefox 103.0.1
![2022-08-05 10_53_45-Window](https://user-images.githubusercontent.com/46269721/183091878-3ec1e38f-9728-4720-8326-6f80facaca04.png)

A "Toggle" section viewed from Chromium Version 101.0.4951.54 (Developer Build, ungoogled-chromium)
![chrome](https://user-images.githubusercontent.com/46269721/183091916-3c7014c8-5abd-49f2-a88d-cd16bc443b85.png)

A "Toggle" section viewed from Firefox 103.0.1 (at 70% zoom because the button is really big and I couldn't get the whole thing in a single image without zooming out)
![firefox](https://user-images.githubusercontent.com/46269721/183091952-a51dca32-839d-46ee-b3d6-dd06fb50f53f.png)

### Steps to Reproduce

1. Install ghost
2. Run ghost
3. Create a post
4. Create a "Toggle" section
5. Put some text in it
6. Load the page 

### Ghost Version

5.7.0

### Node.js Version

v16.14.2

### How did you install Ghost?

I installed it locally through NPM, on Windows 10

### Database type

I don't know. I just installed ghost and it worked straight away :p

### Browser & OS version

Windows 10:
Edition	Windows 10 Home Single Language
Version	21H1
Installed on	‎2020-‎09-‎18
OS build	19043.1826
Experience	Windows Feature Experience Pack 120.2212.4180.0

Firefox 103.0.1

Chromium Version 101.0.4951.54 (Developer Build, ungoogled-chromium)

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by ErisDS** [comment]
Hi @ItsIgnacioPortal, thanks for the detailed bug report. From what I can tell, this issue would be specific to the theme you are using - it is not reproducible in Casper (the default theme) on main. If this is an official theme, let us know which one - otherwise please contact the theme developer.

**Comment by ItsIgnacioPortal** [comment]
> Hi @ItsIgnacioPortal, thanks for the detailed bug report. From what I can tell, this issue would be specific to the theme you are using - it is not reproducible in Casper (the default theme) on main. If this is an official theme, let us know which one - otherwise please contact the theme developer.

Well, that's odd. I'm using Casper v5.2.2. I use the "HTML Injection" feature to add some CSS, but even after removing those modifications the "toggle sections" don't render correctly. I've also tried disabling all browser addons, but no change.

I've recently updated from Ghost from v4.47.0 to v5.7.0 through the ghost cli, could that have had any influence?

This is my casper folder: (I zipped Ghost-Server\current\content\themes\casper): https://mega.nz/file/c4oghQjQ#sRpe8yZ5dOXua6-m6Iz_HDaVNp-UMFhd_HHoGBa600w

**Comment by ErisDS** [comment]
I can't think of any way the update could have caused this. I've tested the latest casper (there are no relevant changes tho) on Firefox & chromium and do not see the artefacts. 

My next step other than this would be to ask for the URL to review, but I assume as it's local that's not possible.

I guess this could be some sort of windows bug because the site is currently running on windows, that would go away if you try to deploy it to a production env & get a url.
