### ISSUE TITLE
Mail 'from' option shows no effect

### ISSUE THREAD

**Issue by aronmal** [TryGhost/Ghost#15191]
### Issue Summary

When I try to sign up I get an error "Failed to send magic link email" and looking in the log it shows an error.

I host the ghost blog at the subdomain blog.domain.de and want to send from ...@domain.de. I have added the "from" attribute to the config but it does not seem to be respected.

### Steps to Reproduce

1. install ghost docker container
2. map custom production json config with:
```
  "mail": {
    "transport": "SMTP",
    "from": "'Blog domain.de' <noreply@domain.de>",
    "options": {
      "host": "smtp.domain.de",
      "port": 465,
      "secure": true,
      "auth": {
        "user": "noreply@domain.de",
        "pass": "SeCuRePaSsWoRd"
      }
    }
  },
```
3. Go to main Paige and Sign up
4. Getting error message displayed

### Ghost Version

latest official docker container

### Node.js Version

latest official docker container

### How did you install Ghost?

docker

### Database type

MySQL 5.7

### Browser & OS version

Firefox

### Relevant log / error output

```shell
Error from container logs:


[2022-08-06 19:40:33] ERROR Failed to send email. Reason: Can't send mail - all recipients were rejected: 553 5.7.1 <noreply@blog.domain.de>: Sender address rejected: not owned by user noreply@domain.de.

Failed to send email. Reason: Can't send mail - all recipients were rejected: 553 5.7.1 <noreply@blog.domain.de>: Sender address rejected: not owned by user noreply@domain.de.
```
```


### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by aronmal** [comment]
Hello,

I already searched in the forum for an answer to my problem. I added the mail configuration to my config but got this error. So I kindly ask you if it could be a bug (what I don't hope, but my config is how it should be, according to the docs and forum posts). So how could that be?

Thanks for replies.

**Comment by marnixhoh** [comment]
I am running into the same issue.

The `from` email is used when inviting a new staff member, but not when someone subscribes...

Any help / guidance would be greatly appreciated

**Comment by ErisDS** [comment]
There is a forum thread here: https://forum.ghost.org/t/mail-from-option-shows-no-effect/31857
