### ISSUE TITLE
Ghost Docker image 5.9.4 db connection issue

### ISSUE THREAD

**Issue by edwardchenchen** [TryGhost/Ghost#15244]
### Issue Summary

I updated from ghost docker image 5.9 with an older version updated after 11th Aug 2022
(I cannot find which exact version of this, it seems the docker hub tags of old versions are actively removed)
to 5.9 with `sha256:3e3d6bbf18cd48db00f59ab10c3788738eae6014d22187644ba02125be8a7377` which is 5.9.4

I am using the default image with no db related related ENV, so SQLite setup

and I get the following error
```onnect ECONNREFUSED 127.0.0.1:3306

"Unknown database error"

Error ID:
    500

Error Code: 
    ECONNREFUSED

----------------------------------------

Error: connect ECONNREFUSED 127.0.0.1:3306
    at /var/lib/ghost/versions/5.9.4/node_modules/knex-migrator/lib/database.js:57:19
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1247:16)
```

### Steps to Reproduce

docker 5.9.4 with default setup

### Ghost Version

5.9.4

### Node.js Version

docker 5.9.4

### How did you install Ghost?

docker 5.9.4

### Database type

SQLite3

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by ErisDS** [comment]
Hi @edwardchenchen, Docker's official Ghost image is managed by them and their community [over in this repo](https://github.com/docker-library/ghost).

The info on the breaking change is [in this pr](https://github.com/docker-library/ghost/pull/323).
