### ISSUE TITLE
Content API Filtering (Documentation?) Bug

### ISSUE THREAD

**Issue by gartesi-n2g** [TryGhost/Ghost#15257]
### Issue Summary

Hi everyone,

I was following the Content API documentation at the [filtering section](https://ghost.org/docs/content-api/#filtering). I was trying to filter tags with the operator "contains" defined as "\~=" in the documentation which didn't work. After a while, I found that "contains" works with "~" operator only.

I'm not sure if the docs are wrong or if it is an actual bug.

### Steps to Reproduce

First, I implemented the operator as documentation says:
```
{{#get "tags" limit="all" filter="description:~='tutorial'"}}
        {{#foreach tags}}
            <a href={{slug}}>{{name}}</a>
        {{/foreach}}
{{/get}}
```

Then, trying with other alternatives, I discovered that this works:
```
{{#get "tags" limit="all" filter="description:~'tutorial'"}}
        {{#foreach tags}}
            <a href={{slug}}>{{name}}</a>
        {{/foreach}}
{{/get}}
```

### Ghost Version

5.9.4

### Node.js Version

16.15.1

### How did you install Ghost?

Local (Development), Ubuntu 22.04 LTS

### Database type

SQLite3

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by ErisDS** [comment]
Hi @gartesi-n2g Thanks for raising this, it's a typo in the docs, I've submitted a fix and the site should update itself momentarily.
