### ISSUE TITLE
Manage your email preferences -> undefinedghost

### ISSUE THREAD

**Issue by ryansechrest** [TryGhost/Ghost#15251]
### Issue Summary

When I leave a comment on my blog, I get an email notification with the comment. In the footer of that email is a link to "Manage your email preferences". When I click on that link, it leads me to: http://undefinedghost/#/settings/staff/ryan

### Steps to Reproduce

1. Leave a comment on a blog post
2. Wait for email notification that a comment has been posted
3. Click on "Manage your email preferences" in footer of email
4. Observe browser going to http://undefinedghost/#/settings/staff/username

### Ghost Version

5.9.4

### Node.js Version

16.15

### How did you install Ghost?

Ubuntu 20.04.4 LTS

### Database type

MySQL 8

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by ryansechrest** [comment]
Thank you, @ErisDS

**Comment by ErisDS** [comment]
No worries, thanks for the bug report - this was an easy one to fix 😬
