### ISSUE TITLE
Links with cyrillic characters are not being redirected

### ISSUE THREAD

**Issue by zolbayars** [TryGhost/Ghost#15267]
### Issue Summary

I added some redirects through `Ghost admin panel → Settings → Labs → Redirects`. But the redirects with Cyrillic characters are not working - it just shows the 404 page. Here's the content of a YAML file I uploaded:

```
301:
    /joloonii-surgaltuud/b-angilal/: /joloonii-angilal/#в-ангилал
    /joloonii-surgaltuud/c-angilal/: /joloonii-angilal/#с-ангилал
    /joloonii-surgaltuud/а-ангилал/: /joloonii-angilal/#а-ангилал
    /joloonii-surgaltuud/м-ангилал: /joloonii-angilal/#м-ангилал
```
The first two works fine, but not the last two (I assume it's because they contain Cyrillic characters like `л, г, н`, etc)

### Steps to Reproduce

1. Upload a `.yaml` file containing redirects with Cyrillic characters on `Ghost admin panel → Settings → Labs → Redirects`
2. Check if the redirect works

### Ghost Version

5.9.4

### Node.js Version

v16.14.2

### How did you install Ghost?

Ubuntu 20.04.4 LTS

### Database type

MySQL 8

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by ErisDS** [comment]
Hey @zolbayars, thank you so much for the detailed bug report.

That does look like something that shouldn't happen! A PR to fix this issue would be very welcome 🙂

**Comment by zolbayars** [comment]
I'm gonna take a look 🙂
