### ISSUE TITLE
Native comments moderation doesn't work on local Windows installation

### ISSUE THREAD

**Issue by Backspaze** [TryGhost/Ghost#15272]
### Issue Summary

When using [Ghost native comments](https://ghost.org/help/commenting/) you should be able to [moderate the comments](https://ghost.org/help/commenting/#moderating-comments) by hiding/unhiding them. This feature doesn't work on a [local Windows installation](https://ghost.org/docs/install/local/). The option for hiding/unhiding isn't available as the site doesn't recognize that you're logged in as both a staff user and a member, so the site behaves just as if you're only logged in as a member and shows only the **Report comment** option for others comments and **Edit** and **Delete** for your own comments.

I'm adding the `comment-counts.min.js` error  from the browser console in the **Relevant log / error output** section below with reference to [this comment](https://forum.ghost.org/t/moderating-ghost-comments/32045/13) in the Ghost forum as it's the only relevant log I have. I see no trace of the `admin-auth` script in the browser console.

In the linked comment from the forum there's a theory that this has to do with script generation not working on Windows which is the same issue as in #14278. I can confirm this as the `content/public` folder is empty on Windows, but on my local test installation in Ubuntu 20.04 using [WSL](https://docs.microsoft.com/en-us/windows/wsl/install) that folder is populated correctly:
```
/ghost/content/public$ ls
admin-auth  cards.min.css  cards.min.js  comment-counts.min.js  member-attribution.min.js
```

### Steps to Reproduce

1. [Install Ghost locally on Windows](https://ghost.org/docs/install/local/).
2. Log in to the admin dashboard.
3. [Enable comments](https://ghost.org/help/commenting/#how-to-enable-comments-in-ghost).
4. Add yourself as a member.
5. Add another test member.
6. Sign in to the site as member 1.
7. Write at least one comment as member 1.
8. Sign out member 1.
9. Sign in as member 2.
10. Click the three dots on the other members comment and notice how the **Hide** option isn't shown, instead it shows only **Report comment**.

### Ghost Version

5.10.1

### Node.js Version

16.16.0

### How did you install Ghost?

Local installation on Windows 10 Pro 21H2 (19044.1889)

### Database type

SQLite3

### Browser & OS version

Chrome (104.0.5112.102) Firefox (103.0.2) Windows 10 Pro 21H2 (19044.1889)

### Relevant log / error output

```shell
GET http://192.168.2.100:2368/public/comment-counts.min.js?v=d0ac7496d9 net::ERR_ABORTED 404 (Not Found)
```

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by ErisDS** [comment]
Hey @Backspaze thanks for the report. This looks like the same issue as https://github.com/TryGhost/Ghost/issues/14278 as you said. I've generalised the title on the other issue, and will close this issue in favour of that one.
