### ISSUE TITLE
Import of Ghost Content Failed

### ISSUE THREAD

**Issue by DrDinosaur** [TryGhost/Ghost#15273]
### Issue Summary

I am migrating a Ghost instance to a new server. I exported the old content successfully as a json file, but I get an error when attempting to import it into the new instance. 

![image](https://user-images.githubusercontent.com/4646697/185824551-aa44d91c-6bf3-464f-99fc-e4aed98df4ab.png)

### Steps to Reproduce

1. Log into Ghost Admin, navigate to the Labs view, and click Export to download all content
2. To begin the content migration, head to the Labs section of Ghost Admin and import the ghost.json backup which you exported earlier.

### Ghost Version

Original server: Ghost-CLI version: 1.9.2 Ghost Version: 2.30.2 New server: Ghost-CLI version: 1.22.0 Ghost version: 5.10.1 

### Node.js Version

Old server: v8.10.0 New server: v16.17.0

### How did you install Ghost?

Old: Ubuntu 18.04 New: Ubuntu 20.04

### Database type

MySQL 8

### Relevant log / error output

```shell
Import failed
ValidationError: Validation (isEmpty) failed for unsplash ValidationError: Validation (isIn) failed for unsplash

{"key":"unsplash","group":"unsplash","type":"boolean","flags":null,"created_by":1,"created_at":"2017-08-27T02:22:32.000Z","updated_by":1,"updated_at":"2017-09-17T23:13:21.000Z"}
```

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by ErisDS** [comment]
Are you able to share the export file, or at least the few lines related to unsplash settings? Without that, I'd be guessing at a reproduction case.

**Comment by DrDinosaur** [comment]
```{"id":"59a22ce83b86f02460405846","key":"unsplash","value":"{\"errors\":{},\"hasValidated\":[]}","type":"blog","created_at":"2017-08-27T02:22:32.000Z","updated_at":"2017-09-17T23:13:21.000Z"}```

I could share the entire export file privately, but this was the only line I found with unsplash.

**Comment by DrDinosaur** [comment]
Do you have an update on this?

**Comment by OIdiotLin** [comment]
Any updates here? I met the same error.

**Comment by Sheepeer** [comment]
Met this error too. But what happend to me is not "import failed" but I received an email which said "Import unsuccessful"

**Comment by ErisDS** [comment]
Sorry - I was hoping to find time to push a small fix to the importer, but it's been a crazy end to the year.

The fix to get the import to work would be to remove the item from the settings array - so delete `{"id":"59a22ce83b86f02460405846","key":"unsplash","value":"{\"errors\":{},\"hasValidated\":[]}","type":"blog","created_at":"2017-08-27T02:22:32.000Z","updated_at":"2017-09-17T23:13:21.000Z"}` from your JSON file. That'll get the import to work .

@Sheepeer your issue is something entirely different.
