### ISSUE TITLE
The ld+json generated by {{ ghost_head }} doesn't use specified canonical url

### ISSUE THREAD

**Issue by digitalWestie** [TryGhost/Ghost#15281]
### Issue Summary

The ld+json generated by {{ ghost_head }} doesn't use the specified page canonical url.

I've set a canonical url in one of my pages. I can see this coming through in page source. However, the LD+JSON description doesn't use the canonical version in the article URL.  

What is currently happening:
 
`<link rel="canonical" href="https://mysite.com/learn-stuff" />`
 
```   
<script type="application/ld+json">
{
    "@context": "https://schema.org",
    "@type": "Article",
    ...
    "url": "https://mysite.com/another-way-to-learn-stuff",
```

### Steps to Reproduce

1 Create a page
2 Set the canonical url on the page
3 Publish
4 View source

I would expect to see the canonical url: 
 
`<link rel="canonical" href="https://mysite.com/learn-stuff" />`
 
Match in the article ld+json:

```   
<script type="application/ld+json">
{
    "@context": "https://schema.org",
    "@type": "Article",
    ...
    "url": "https://mysite.com/learn-stuff",
```

### Ghost Version

5.2.2

### Node.js Version

v16.15.1

### How did you install Ghost?

Ghost CLI on Ubuntu 18.04.6 LTS

### Database type

MySQL 8

### Browser & OS version

Ubuntu & Firefox

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by ErisDS** [comment]
I believe this is the correct behaviour for the schema data. Do you have a reference that suggests otherwise?

**Comment by digitalWestie** [comment]
> I believe this is the correct behaviour for the schema data. Do you have a reference that suggests otherwise?

Fair enough if this is the intended behaviour. I assumed you'd want to use the canonical URL.

**Comment by ErisDS** [comment]
We follow the LD+JSON specification to the letter, if you find we are following it incorrectly we're happy to review.

**Comment by digitalWestie** [comment]
My understanding of it is this: there should only be one structured description of a resource for each resource. 

I think this stack answer describes what I mean:  https://webmasters.stackexchange.com/questions/119078/how-to-define-an-url-in-article-schema-on-mobile-domain

In the stack-exchange answer, you've got a similar situation to mine: the same article sitting in two different places (in their case a desktop and a mobile vers).  The structured data should say "this one thing exists", and use the same representation of it otherwise search-engines and the like can get confused.
