### ISSUE TITLE
Changing emoji in callout card causes page jump in Safari

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#15295]
### Issue Summary

When trying to update an emoji in a callout card using Safari, it jumps to the top of the editor (and successfully changes the icon).

### Steps to Reproduce

1. Open Safari
2. Create a new post with several paragraphs of content, and insert a call out card after them
3. Try to change the emoji of the callout card, observe you're jumped up to the top of the editor

### Ghost Version

5.10

### Node.js Version

16

### How did you install Ghost?

ghost install

### Database type

MySQL 8

### Browser & OS version

Safari 15.6 (17613.3.9.1.5) / Mac OS 12.5

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by akp111** [comment]
I want to take this up @ErisDS
