### ISSUE TITLE
Adding a new member with Admin API does not trigger member email alerts

### ISSUE THREAD

**Issue by VeloAddict** [TryGhost/Ghost#15324]
### Issue Summary

When adding a new member with the Admin API endpoint the new member is added but the notification is not sent to the staff users and all staff users have notifications enabled.

### Steps to Reproduce

Enable new signup email alerts for staff users.
Create a new member using the Admin API.
The user is created, it is listed in the members page.
Staff users do not receive email about new member.
Email sending works, other email (ex: staff user invite) are sent and received.

### Ghost Version

5.12.0

### Node.js Version

16.17.0

### How did you install Ghost?

digital ocean + ubuntu

### Database type

MySQL 8

### Relevant log / error output

```shell
No errors
```

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by ErisDS** [comment]
Hi @VeloAddict, thanks for the detailed report.

I can confirm this is a bug. The fix is known and we’re working on getting it shipped asap.

**Comment by rishabhgrg** [comment]
Fixed in https://github.com/TryGhost/Ghost/commit/054833992eb46f7fa50ff4d4bfe2ee5345ed4eba
