### ISSUE TITLE
host error limit cannot edit post 

### ISSUE THREAD

**Issue by aaronpartnerhacker** [TryGhost/Ghost#15396]
### Issue Summary

Newsletter won't go to subs. Can't schedule/post
![Screenshot 2022-09-12 8 05 14 AM](https://user-images.githubusercontent.com/113367391/189686069-35bc856f-fdc2-43ba-8eb2-1d692b49c972.png)

### Steps to Reproduce

Try scheduling post. Won't allow.

### Ghost Version

unsure

### Node.js Version

unsure

### How did you install Ghost?

pro

### Database type

Other

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by kevinansfield** [comment]
Hey @aaronpartnerhacker  👋 Friendly reminder: help or support is not available on Github.

This is a Ghost(Pro) specific error related to your plan limits. Please contact support@ghost.org where they can give you personalised help.
