### ISSUE TITLE
Can't migrate past v5.9.4 due to mysql error

### ISSUE THREAD

**Issue by rkrueger11** [TryGhost/Ghost#15392]
### Issue Summary

Attempting to migrate from 5.9.4 to 5.10.1 (or anything higher) and receiving the following error: 

Message: Ghost was able to start, but errored during boot with: alter table `members_created_events` add constraint `members_created_events_member_id_foreign` foreign key (`member_id`) references `members` (`id`) on delete CASCADE - Referencing column 'member_id' and referenced column 'id' in foreign key constraint 'members_created_events_member_id_foreign' are incompatible.
Help: Error occurred while executing the following migration: 2022-08-16-14-25-add-member-created-events-table.js
Suggestion: journalctl -u ghost_ryansjourney-blog -n 50

Debug Information:
    OS: Ubuntu, v20.04.4 LTS
    Node Version: v16.16.0
    Ghost Version: 5.10.1
    Ghost-CLI Version: 1.23.0
    Environment: production
    Command: 'ghost update 5.10.1'

MySQL Version: mysql  Ver 8.0.30-0ubuntu0.20.04.2 for Linux on x86_64 ((Ubuntu))

### Steps to Reproduce

1. ghost update 5.10.1
2. Error is shown

### Ghost Version

v5.9.4

### Node.js Version

v16.16.0

### How did you install Ghost?

Digital Ocean Droplet

### Database type

MySQL 8

### Relevant log / error output

```shell
Message: Ghost was able to start, but errored during boot with: alter table `members_created_events` add constraint `members_created_events_member_id_foreign` foreign key (`member_id`) references `members` (`id`) on delete CASCADE - Referencing column 'member_id' and referenced column 'id' in foreign key constraint 'members_created_events_member_id_foreign' are incompatible.
Help: Error occurred while executing the following migration: 2022-08-16-14-25-add-member-created-events-table.js
Suggestion: journalctl -u ghost_ryansjourney-blog -n 50
```

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by rkrueger11** [comment]
Fixed. Due to collation issues.

**Comment by kogir** [comment]
Hello @rkrueger11,

I'm also experiencing this same error. Would you be willing to give a high level description of how you addressed it, so I can read the right MySQL docs and figure out a fix?

Cheers!
