### ISSUE TITLE
Sender in config not honored for comment email

### ISSUE THREAD

**Issue by ryansechrest** [TryGhost/Ghost#15427]
### Issue Summary

I'm torn on whether this is an issue or not, so feel free to close this if it's out of place.

When you receive an email that a new comment was posted on your website, I expected the sender to be set to whatever `from` was set to in `config.production.json` (e.g. `no-reply@example.org`) vs. it being the support email address (e.g. `support@example.org`) set in: Settings > Membership > Customize Portal > Account page settings > Support email address.

Considering that comments can only be left by members, I can see the reasoning behind the support email address, but generally such notifications are intended to be a one-way communication.

In addition, depending on what the website owner figured as their support email address (e.g. `support@example.org`), I worry that it might give the illusion that this is like a ticketing system where one can simply reply to the email to reply to the comment.

Last, making this change would also be in line with the new member sign-up email notification behavior, which does use the `from` configuration from `config.production.json`.

### Steps to Reproduce

1. Configure a `from` address in `config.production.json`
2. Set up a support email address in settings
3. Leave a comment on a blog post
4. Observe the sender of the email notification

### Ghost Version

5.15

### Node.js Version

16.17.0

### How did you install Ghost?

Ubuntu 20.04.5 LTS

### Database type

MySQL 8

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by ErisDS** [comment]
Hey @ryansechrest I just want to ack this as something we're investigating. There's a few different ways in which transactional vs bulk mail in Ghost has gotten confusing, particularly around what the from address is and we're planning an overhaul that will likely hoover this issue up.

**Comment by ryansechrest** [comment]
Hi @ErisDS That all makes sense, thank you!
