### ISSUE TITLE
Mailgun : The server encountered an error whilst sending email

### ISSUE THREAD

**Issue by ltoinel** [TryGhost/Ghost#15437]
### Issue Summary

Since I updated my blog and I changed my hosting, I'm not able to send new newsletters to the blog's members.
Maybe due to the latest updates on the mailgun client in august ? 

### Steps to Reproduce

1. My server contains a SMTP parameter (config file) and a Mailgun config (filled in Ghost admin)
2. When I send a mail with curl from the my Server to Mailgun API with private key   : OK
3. When I send a test newsletter from Ghost admin : OK. I can receive the mail on all my email boxes.
4. When I write a new post and I publish the post + post newsletter : KO. Nothing in the mailgun logs. The number of subscribed members is valid.

### Ghost Version

v5.15.0

### Node.js Version

v16.17.0

### How did you install Ghost?

Ghost CLI + Ghost Update

### Database type

MySQL 8

### Relevant log / error output

```shell
level: normal

"The email service was unable to send an email batch."
EmailError: The server encountered an error whilst sending email.
    at Object.send (/data/www/xxxx/versions/5.15.0/core/server/services/bulk-email/bulk-email-processor.js:256:30)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.processEmailBatch (/data/www/xxxx/versions/5.15.0/core/server/services/bulk-email/bulk-email-processor.js:179:34)
    at async Promise.map.concurrency (/data/www/xxxx/versions/5.15.0/core/server/services/bulk-email/bulk-email-processor.js:104:17)

------

{"name":"Log","hostname":"sd-130779","pid":311727,"level":40,"err":{"id":"0d79dee0-3860-11ed-862a-fd41727eca91","domain":"https://xxxxx","code":"BULK_EMAIL_SEND_FAILED","name":"EmailError","statusCode":500,"level":"normal","message":"The server encountered an error whilst sending email.","context":"\"The email service was unable to send an email batch.\"","stack":"EmailError: The server encountered an error whilst sending email.\n    at Object.send (/data/www/xxxxx/versions/5.15.0/core/server/services/bulk-email/bulk-email-processor.js:256:30)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async Object.processEmailBatch (/data/www/xxxx/versions/5.15.0/core/server/services/bulk-email/bulk-email-processor.js:179:34)\n    at async Promise.map.concurrency (/data/www/xxxx/versions/5.15.0/core/server/services/bulk-email/bulk-email-processor.js:104:17)","hideStack":false},"msg":"The server encountered an error whilst sending email.","time":"2022-09-19T21:14:31.255Z","v":0}
```

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by ErisDS** [comment]
The error here is coming from mailgun, however the way Ghost is handling it is overwriting it and masking the underlying error. You may still be able to find the error in your mailgun logs to find out what's wrong, but it will be [one of these](https://documentation.mailgun.com/en/latest/api-intro.html#status-codes).

We need to update the code here to not totally overwrite the error, as it makes debugging impossible, but I don't think Ghost is causing the actual problem - it'll be a mailgun config issue.

**Comment by ltoinel** [comment]
In my case the mailgun response was a 403 error  : "Domain xxx is not allowed to send large batches yet"

**Comment by ErisDS** [comment]
Closed by https://github.com/TryGhost/Ghost/commit/79ffdd9b7e7f29db37940d7cfa92659aab03b069

**Comment by ltoinel** [comment]
To fix the 403 error, you have to open a ticket on the Mailgun portal.
Then a person contacts you and asks you what service you want to provide with Mailgun (what domain, how many mails .... etc).

**Comment by ltoinel** [comment]
Thank-you @ErisDS ! 
I'm developping quickly Mailknife to replace Mailgun : https://github.com/ltoinel/Mailknife

**Comment by B1Z0N** [comment]
Same here. Can't send a single post through mailgun, while sending test emails works perfectly. Any suggestions?

**Comment by heavyelement** [comment]
Is there any way to send the newsletter in batches and customize the number of recipients in each batch? My account is limited to 9 recipients per batch.

**Comment by PhillipMwaniki** [comment]
I presently have this issue with Mailgun. Has anyone found a permanent fix to it? The error I'm getting from the logs is 
```
{"code":"BULK_EMAIL_SEND_FAILED","name":"EmailError","statusCode":500,"level":"normal","message":"Error sending email 6494d3a75ce0cd55f2c422f9","stack":"EmailError: An unexpected error occurred, please retry sending your newsletter.\n    at BatchSendingService.emailJob (/var/www/ghost/versions/5.52.0/node_modules/@tryghost/email-service/lib/BatchSendingService.js:162:32)\n    at BatchSendingService.sendBatches (/var/www/ghost/versions/5.52.0/node_modules/@tryghost/email-service/lib/BatchSendingService.js:371:19)\n    at async BatchSendingService.sendEmail (/var/www/ghost/versions/5.52.0/node_modules/@tryghost/email-service/lib/BatchSendingService.js:208:9)\n    at async BatchSendingService.emailJob (/var/www/ghost/versions/5.52.0/node_modules/@tryghost/email-service/lib/BatchSendingService.js:153:13)\n    at async /var/www/ghost/versions/5.52.0/node_modules/@tryghost/job-manager/lib/JobManager.js:244:25\n    at async JobManager.worker (/var/www/ghost/versions/5.52.0/node_modules/@tryghost/job-manager/lib/JobManager.js:16:22)","hideStack":false},"msg":"Error sending email 6494d3a75ce0cd55f2c422f9","time":"2023-06-24T11:48:27.179Z","v":0}
```
