### ISSUE TITLE
Keyboard shortcut to save does not save data in admin members form

### ISSUE THREAD

**Issue by adamrhunter** [TryGhost/Ghost#15450]
### Issue Summary

When using the cmd+s keyboard shortcut while editing a Member _when the input field is focused_  the change not actually saved - When the page is reloaded, the data is not present.  *This only seems to happen if the input field is focused*.  If no field is focused (no green outline) then the save works as expected.

### Steps to Reproduce

1. default install of ghost 5.15
2. create a member
3. select (focus) the "Note" input and add some content
4. keeping the note field focused (green outline) use the cmd+s "save" shortcut.  The "saved" green button indicator is shown (top right of right admin panel)
5. reload the page - observe the data added to note field is not saved

note: the shortcut works if the field is not focused.

### Ghost Version

5.15

### Node.js Version

16

### How did you install Ghost?

self hosted (EC2) on Ubuntu 22.04. followed self-host guide from ghost documentation

### Database type

MySQL 8

### Browser & OS version

Chrome (105.0.5195.125) & Mac OS (12.4)

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by ryansechrest** [comment]
I can reproduce this. It looks like the value isn't updated in the DOM until that particular field is blurred, because it simply sends the existing value in the payload when the form is saved using the keyboard shortcut. I tested this on Staff, Tags, and Navigation, and everything works as expected there.
