### ISSUE TITLE
Menu items lose active state when "New ..." modal is open

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#15506]
### Issue Summary

The relevant item in the left-hand menu should remain bold when the "New X" modal is open

<img width="1181" alt="image" src="https://user-images.githubusercontent.com/101513/193123657-99e81c05-7ffb-4e72-b4bc-2f9a35b818c5.png">

<img width="1191" alt="image" src="https://user-images.githubusercontent.com/101513/193123751-738decd0-19bb-4ab5-b1e0-907f01f2f947.png">

### Steps to Reproduce

1. Open Ghost admin
2. Click on tags, note that "Tags" in the left menu is bold
3. Click on "New tag" and notice that "Tags" in the left menu is no longer bold

Same for Members, Offers, etc.

### Ghost Version

5.16

### Node.js Version

16

### How did you install Ghost?

ghost install

### Database type

MySQL 8

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by satyamraghuwanshi136** [comment]
Hi @ErisDS, I would like to work on this issue.

**Comment by parulgupta26** [comment]
Hey can I work on this issue?

**Comment by parulgupta26** [comment]
Hi @ErisDS  I would like to work on this issue. Please assign to me.

**Comment by ErisDS** [comment]
Hi @parulgupta26 we only assign issues to regular contributors. There is already an open PR for this now, so I suggest choosing something else.
