### ISSUE TITLE
An error occurs when display Member activity

### ISSUE THREAD

**Issue by rbtnn** [TryGhost/Ghost#15515]
### Issue Summary

It seems that e.data.link may not always have a "to" property.

![image](https://user-images.githubusercontent.com/1595779/193472912-6da462e8-2675-4c0c-82b6-1b5047e49982.png)
![image](https://user-images.githubusercontent.com/1595779/193472923-f6fff7c0-d26d-4419-b5a6-3308e667e7c7.png)

https://github.com/TryGhost/Ghost/blob/0b41fbf102a77893667d265478a150753ae5c004/ghost/admin/app/helpers/parse-member-event.js#L235

### Steps to Reproduce

1. open ghost/#/dashboard
2. click Member acrivity

### Ghost Version

5.17.0

### Node.js Version

v14.17.3

### How did you install Ghost?

https://backspace.fm/ & Ubuntu 20.04.1 LTS (GNU/Linux 5.4.0-52-generic x86_64))

### Database type

MySQL 8

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by rbtnn** [comment]
I can at least confirm that it works correctly with the following modifications.
![image](https://user-images.githubusercontent.com/1595779/193476043-e4915254-f824-47e9-8dfd-494c601b1bbc.png)

**Comment by daniellockyer** [comment]
This was fixed and released in v5.17.1 🙂

**Comment by rbtnn** [comment]
Thanks you for fixing
