### ISSUE TITLE
Update command breaks docker from working

### ISSUE THREAD

**Issue by ASAMedia** [TryGhost/Ghost#15524]
### Issue Summary

Created a custom zip/tgz file with`yarn build` and tried to upgrade a docker install of ghost(5.14.2) to it (5.15.0) with `ghost update --zip .../../` to the custom one.
It upgrades without a problem, but when trying to start ghost back up I get some weird errors as shown further down.
Why is the directory structure on the docker instances still the same as in the older 4. versions of Ghost?
How can I upgrade without changing to the old structure?

Please let me know where the problem lies so I can fix it.
My guess is that the update command **was'nt** rewritten to work with the new directory structure introduced in ver. 5

### Steps to Reproduce

1. Run Ghost as Docker and `docker exec -it <Container> bash` into it.
2. From there go to /var/lib/ghost and examine the directories
3. As you can see the directory structure is not nearly identical to the new 5. Versions
4. Create a zip/tgz with `yarn build` on your local 5.15.0 instance and copy it to the docker
5. Run `ghost update --zip .../../` inside the docker and watch the log afterwards
6. As you can see, the update command broke everything.

### Ghost Version

5.15.0

### Node.js Version

14.20

### How did you install Ghost?

According to the doc as docker

### Database type

MySQL 8

### Relevant log / error output

```shell
user@user-OptiPlex:~/Dokumente/webtest$ sudo docker-compose logs -f
Attaching to lfg-ghost
lfg-ghost    | node:internal/modules/cjs/loader:959
lfg-ghost    |   throw err;
lfg-ghost    |   ^
lfg-ghost    | 
lfg-ghost    | Error: Cannot find module '/var/lib/ghost/current/index.js'
lfg-ghost    |     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:956:15)
lfg-ghost    |     at Function.Module._load (node:internal/modules/cjs/loader:804:27)
lfg-ghost    |     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
lfg-ghost    |     at node:internal/main/run_main_module:17:47 {
lfg-ghost    |   code: 'MODULE_NOT_FOUND',
lfg-ghost    |   requireStack: []
lfg-ghost    | }
lfg-ghost    | node:internal/modules/cjs/loader:959
lfg-ghost    |   throw err;
lfg-ghost    |   ^
lfg-ghost    | 
lfg-ghost    | Error: Cannot find module '/var/lib/ghost/current/index.js'
lfg-ghost    |     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:956:15)
lfg-ghost    |     at Function.Module._load (node:internal/modules/cjs/loader:804:27)
lfg-ghost    |     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
lfg-ghost    |     at node:internal/main/run_main_module:17:47 {
lfg-ghost    |   code: 'MODULE_NOT_FOUND',
lfg-ghost    |   requireStack: []
lfg-ghost    | }
lfg-ghost    | node:internal/modules/cjs/loader:959
lfg-ghost    |   throw err;
lfg-ghost    |   ^
lfg-ghost    | 
lfg-ghost    | Error: Cannot find module '/var/lib/ghost/current/index.js'
lfg-ghost    |     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:956:15)
lfg-ghost    |     at Function.Module._load (node:internal/modules/cjs/loader:804:27)
lfg-ghost    |     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
lfg-ghost    |     at node:internal/main/run_main_module:17:47 {
lfg-ghost    |   code: 'MODULE_NOT_FOUND',
lfg-ghost    |   requireStack: []
lfg-ghost    | }
```

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by daniellockyer** [comment]
Hello again 🙂 I believe this problem arises from the .tgz you're building. I've posted some workarounds in https://github.com/TryGhost/Ghost/issues/15523#issuecomment-1266362936

**Comment by ASAMedia** [comment]
Hi @daniellockyer ,
thanks for your quick response.
I migrated to the newest version and re-build the .tgz archive.
[Here](https://we.tl/t-CZwYphLJYB) is a link to the .tgz in case you want to take a look at it (was to big for attachment).
When I run the update command as node user in docker after copying the archive I get the following output:

```
/var/lib/ghost $ ghost update --force --zip /var/lib/Ghost-5.17.2.tgz

Love open source? We’re hiring JavaScript Engineers to work on Ghost full-time.
https://careers.ghost.org



Process manager 'systemd' will not run on this system, defaulting to 'local'
✔ Checking system Node.js version - found v16.17.1
✔ Ensuring user is not logged in as ghost user
✔ Checking if logged in user is directory owner
✔ Checking current folder permissions
✔ Checking folder permissions
✔ Checking file permissions
✔ Checking memory availability
✔ Checking free space
✔ Checking for available migrations
✖ Checking for latest Ghost version
A SystemError occurred.

Message: Archive file does not contain a Ghost release.

Debug Information:
    OS: Alpine Linux, v3.16.2
    Node Version: v16.17.1
    Ghost Version: 5.17.1
    Ghost-CLI Version: 1.23.1
    Environment: production
    Command: 'ghost update --force --zip /var/lib/Ghost-5.17.2.tgz'

Try running ghost doctor to check your system for known issues.

You can always refer to https://ghost.org/docs/ghost-cli/ for troubleshooting.

```
