### ISSUE TITLE
Disable border or change template for Native Comments

### ISSUE THREAD

**Issue by javierencalada** [TryGhost/Ghost#15528]
### Issue Summary

Hello!, i'm Javier from EstudioPatagon themes.

When using Native Comments, the border colors do not looks good: https://prnt.sc/JVTJ_xEU4jwH depending of the container color. The current solution works very nice for White or Black background, but not so well for other kind of colors.

Live example: https://ghost.estudiopatagon.com/groovy/far-far-away/

It could be really good a new option to remove those borders, like `{{comments title="" count=true mode="light" borders=false}}`

Or a more complex solution in the future, like adding partials/comments.hbs template (same as partials/content-cta.hbs) or include a comments-style.css just for that iframe (similar to cards.min.css) so we can fully manipulate the styling.

There are some workarounds injecting CSS via Javascript over the comments iframe, but i don't think it is a really good idea in the long term.

Thank you very much!

### Steps to Reproduce

1. Add `{{comments title="" count=true mode="light"}}` into post.hbs
2. Change the container color to something different than "white".

### Ghost Version

5.15.0

### Node.js Version

14.17.6

### How did you install Ghost?

Windows 10 Local Installation

### Database type

SQLite3

### Browser & OS version

Chrome & Windows 10

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by peterzimon** [comment]
Hey @javierencalada, thank you for your report we've added it to our bug backlog.
