### ISSUE TITLE
yarn build produces non compliant output .tgz

### ISSUE THREAD

**Issue by ASAMedia** [TryGhost/Ghost#15523]
### Issue Summary

The output tgz file when after running `yarn build` is not compliant with the requested compressed file when running `ghost update --zip path/to/file.zip`.
The packages.yml file has the wrong name tag as well as the wrong version tag.
Besides that, the compressed file should directly include the main directory not a directory wich includes the main.

Am I the first one discovering this or do I just use old commands?

### Steps to Reproduce

1. Run `yarn build`
2. Setup a ghost instance as described in the Ghost documentation
3. Run `ghost update --zip path/to/file.tgz` or `ghost update --zip path/to/file.zip`

### Ghost Version

5.15.0

### Node.js Version

12.40

### How did you install Ghost?

As described in doc

### Database type

MySQL 8

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by daniellockyer** [comment]
Hey @ASAMedia 👋🏻 The functionality of `yarn build` was fixed shortly before [this comment](https://github.com/TryGhost/Ghost/issues/15099#issuecomment-1258842099), which was just over a week ago. You'll need a more recent copy of the Ghost repo in order for it to work.

That being said, running `npm pack` from `ghost/core` should still work on the revision of the repo you likely have 🙂
