### ISSUE TITLE
Webhook test coverage 

### ISSUE THREAD

**Issue by naz** [TryGhost/Ghost#15537]
Webhooks have been a part of Ghost since very first versions. This area has been constantly lagging behind with solid test coverage. Having tests would add confidence to webhooks stability. Snapshot tests would be a great source of example data webhooks deliver to external integrations. 

To improve this situation, Ghost has introduced a special purpose Webhooks snapshot tests. These are snapshot-based tests (similar to the[ end-to-end API tests](https://github.com/TryGhost/Ghost/tree/a6c76dadc3c369d61e9e7fb3e65c42570efb9273/ghost/core/test/e2e-api/admin)) with one big difference - they test the outgoing request payload instead of API responses.

To understand how end-to-end testing works at Ghost have a read through [this guide](https://ghost.notion.site/End-to-end-Testing-6a2ef073b1754b18aff42e24a632a007). The concepts applied in end-to-end API tests are very similar to ones used in webhook tests.

Here is an [example of a webhook test suite](https://github.com/TryGhost/Ghost/blob/78c97d10a6f6a86c7b132534bcc71a6623688799/ghost/core/test/e2e-webhooks/posts.test.js) for for `post.published` and `post.added` events.

The above suite covers two event's which Webhook events listen to. There are 29 total events Webhooks can respond to, 27 left to cover. We need help writing tests for them!  

Below are some pointers around what you could help us with. For the most part it's covering all of the webhook events with at least one "happy path" test.

### 1. Write a test
First, find one webhook event listener to cover - search for an event that has no test coverage in the list of [all webhook event listeners](https://github.com/TryGhost/Ghost/blob/66f11d5e4548db3b3c4d9242e5e217863aac088b/ghost/core/core/server/services/webhooks/listen.js#L12-L45).

<details>
<summary>Copy of all events below for quick reference and ✅ for the ones with at least one test:</summary>

- [x] 'site.changed' (https://github.com/TryGhost/Ghost/pull/15595)
- [x] 'post.added' (https://github.com/TryGhost/Ghost/commit/b536cf5d9c93dd3dde6dca05c82d6761384c2fb3)
- [x] 'post.deleted' (https://github.com/TryGhost/Ghost/pull/15572)
- [x] 'post.edited' (https://github.com/TryGhost/Ghost/pull/15625)
- [x] 'post.published' (https://github.com/TryGhost/Ghost/commit/0f4aeaaa802738f06aed066ece39f9666f2ec1ce)
- [x] 'post.published.edited' (https://github.com/TryGhost/Ghost/pull/15642)
- [x] 'post.unpublished' (https://github.com/TryGhost/Ghost/pull/15628)
- [x] 'post.scheduled' (https://github.com/TryGhost/Ghost/pull/15561)
- [x] 'post.unscheduled' (https://github.com/TryGhost/Ghost/pull/15675)
- [ ] 'post.rescheduled' (https://github.com/TryGhost/Ghost/pull/15735)
- [x] 'page.added' (https://github.com/TryGhost/Ghost/pull/15548)
- [x] 'page.deleted' (https://github.com/TryGhost/Ghost/pull/15723)
- [x] 'page.edited' (https://github.com/TryGhost/Ghost/pull/15627)
- [x] 'page.published' (https://github.com/TryGhost/Ghost/pull/15724)
- [x] 'page.published.edited' (https://github.com/TryGhost/Ghost/pull/15724)
- [x] 'page.unpublished' (https://github.com/TryGhost/Ghost/pull/15613)
- [x] 'page.scheduled' (https://github.com/TryGhost/Ghost/pull/15609)
- [ ] 'page.unscheduled' (https://github.com/TryGhost/Ghost/pull/15722)
- [ ] 'page.rescheduled' (https://github.com/TryGhost/Ghost/pull/15736)
- [x] 'tag.added' (https://github.com/TryGhost/Ghost/pull/15540)
- [x] 'tag.edited' (https://github.com/TryGhost/Ghost/pull/15555)
- [x] 'tag.deleted' (https://github.com/TryGhost/Ghost/pull/15553)
- [x] 'member.added' (https://github.com/TryGhost/Ghost/pull/15554)
- [x] 'member.deleted' (https://github.com/TryGhost/Ghost/pull/15570)
- [x] 'member.edited' (https://github.com/TryGhost/Ghost/pull/15620)
- [x] 'post.tag.attached' (https://github.com/TryGhost/Ghost/pull/15576)
- [x] 'post.tag.detached' (https://github.com/TryGhost/Ghost/pull/15651)
- [x] 'page.tag.attached' (https://github.com/TryGhost/Ghost/pull/15648)
- [x] 'page.tag.detached' (https://github.com/TryGhost/Ghost/pull/15651)

Before digging deep into work please double check if the list is up to date - check if there are any open or closed [Pull Requests open](https://github.com/TryGhost/Ghost/pulls) with the name of the event you are about to pick up.
</details>

Let's pick `site.changed` event to cover with _example_ a test.
 
Webhook tests are located in `ghost/core/test/e2e-webhooks/{model_name}.test.js` (e.g.: [test/e2e-webhooks/posts.test.js](https://github.com/TryGhost/Ghost/blob/78c97d10a6f6a86c7b132534bcc71a6623688799/ghost/core/test/e2e-webhooks/posts.test.js)). As there is no `site.test.js` suite in the [e2e-webhooks folder](https://github.com/TryGhost/Ghost/tree/a6c76dadc3c369d61e9e7fb3e65c42570efb9273/ghost/core/test/e2e-webhooks) - create a `site.test.js` file. Note, for  `post.rescheduled` event, there is a `posts.test.js` test suite already. In this case, we would add test cases to existing `posts.test.js` test suite. The convention is to group test suites by common model name - `{model_name}.test.js`.

Write the test in the newly created file following concepts in [end-to-end testing guide](https://ghost.notion.site/End-to-end-Testing-6a2ef073b1754b18aff42e24a632a007). For an easy start it's usually a good idea to copy a similar working test suite into your new file and tweak it. 

<details>
<summary>
Notes on Webhook test case structure
</summary>

Webhook tests follow a setup->action->assert structure used commonly when writing other types of tests, like unit tests:
1. **Setup**
  - [Create a webhook](https://github.com/TryGhost/Ghost/blob/78c97d10a6f6a86c7b132534bcc71a6623688799/ghost/core/test/e2e-webhooks/posts.test.js#L69-L74) database entry
2. **Action**
  - Find under which conditions the event under test is triggered (usually a [result of API call(s)](https://github.com/TryGhost/Ghost/blob/78c97d10a6f6a86c7b132534bcc71a6623688799/ghost/core/test/e2e-webhooks/posts.test.js#L76-L95)).  This might take a little bit of research and experimentation. If you are completely lost and did not find the pathway after searching feel free to leave a comment here for more guidance.
3. **Assertion**
  - [Wait for](https://github.com/TryGhost/Ghost/blob/78c97d10a6f6a86c7b132534bcc71a6623688799/ghost/core/test/e2e-webhooks/posts.test.js#L97) webhook events propagation and [write an assertion](https://github.com/TryGhost/Ghost/blob/78c97d10a6f6a86c7b132534bcc71a6623688799/ghost/core/test/e2e-webhooks/posts.test.js#L99-L115) about the expected format of the snapshot.
</details>

### 2. Run the test and record a snapshot
Use the `yarn test:single` command inside `ghost/core` to run the test suite you've been working on:
```
yarn test:single test/e2e-webhooks/site.test.js
```

After the test run, there will be a snapshot file created with recorder webhook payload ([example](https://github.com/TryGhost/Ghost/blob/a6c76dadc3c369d61e9e7fb3e65c42570efb9273/ghost/core/test/e2e-webhooks/__snapshots__/posts.test.js.snap#L137-L324)). 

Check the **[Snapshot Testing](https://ghost.notioån.site/End-to-end-Testing-6a2ef073b1754b18aff42e24a632a007)** section of the end-to-end testing guide for more information about the inner workings of snapshot-based tests.

### 3. Open a PR

To make sure you've not broken anything & followed our code standard, run `yarn test:all`. You can also use `yarn lint` to check formatting issues.

Commit and push the test suite code and the snapshot to your working branch. Open up a separate PR for each webhook even you cover. 

🎉 All done! we will try to review your contribution ASAP.

----

Please follow our contribution guidelines as closely as you can, particularly being sure to reference this issue in your commit. Test coverage commits should not use emojis as they are not user-facing changes.

This issue is going to improve the ease of bug reproductions and will let all Ghost developers sleep better after modifying webhook-related code. This means a lot for the team and contributors!

Thank you 🙏 💚

**Comment by dshubhadeep** [comment]
hi @naz 
I would like to work on `tag.*` events

**Comment by naz** [comment]
Hey @dshubhadeep 👋  Feel free to pick one event at a time, will try my best to review ASAP. And feel free to ask questions if anything is unclear!

**Comment by dshubhadeep** [comment]
Thanks, I'll start with `tag.added` event.

**Comment by illiteratewriter** [comment]
I'd like to work on `member.added` event

**Comment by JohnGrisham** [comment]
I'll try my hand at page.added

**Comment by jennyxchang** [comment]
I can work on `post.scheduled` event.

**Comment by kritikash18** [comment]
working on post.deleted event

**Comment by Prathamesh010** [comment]
Working on `post.unpublished` event

**Comment by kritikash18** [comment]
working on `post.tag.attached` event

**Comment by UncannyValle** [comment]
Hi there! I'll start working on `page.deleted`!

**Comment by halldorbjarni** [comment]
Hi all! I can work on the `site.changed` event.

**Comment by kritikash18** [comment]
working on `post.tag.detached` event

**Comment by dshubhadeep** [comment]
Will start working on `page.scheduled` event

**Comment by halldorbjarni** [comment]
Taking a stab at the `page.unpublished` event next!

**Comment by dshubhadeep** [comment]
will work on `post.edited` event

**Comment by shngt** [comment]
Taking a stab at page.edited, if that's okay

**Comment by kritikash18** [comment]
working on `post.published.edited` event

**Comment by leonyangela** [comment]
Hi, can I work on 'page.tag.attached'. Thank you.

**Comment by Dark-Knight11** [comment]
I would like to work on `page.tag.detached` event

**Comment by Dark-Knight11** [comment]
I would like to work on `page.published` event

**Comment by yahya-cloud** [comment]
I'd like to work on  post.unscheduled event

**Comment by Jaya-sys** [comment]
Hey can you assign this issue to me?

**Comment by dom96** [comment]
@yahya-cloud I've already got a PR out for that here: https://github.com/TryGhost/Ghost/pull/15675

**Comment by naz** [comment]
@Jaya-sys hey-hey 👋  There is no need to assign anything, just pick one of the event's you'd like to cover and submit a PR. This issue is designed to be shared 😄

**Comment by debmalya37** [comment]
Hey !! Can I do it ??

**Comment by naz** [comment]
@debmalya37 sure you can!

**Comment by ErisDS** [comment]
We now have either a merged or open PR for every single webhook. Thank you to everyone who contributed ❤️ this is incredible - you've all helped us to make a sea-change in our test coverage and ability to support webhooks and zapier going forward.

Thank you 🙏
