### ISSUE TITLE
Create a theme unit test guide

### ISSUE THREAD

**Issue by hswolff** [TryGhost/Ghost#1553]
Just like what WordPress has (http://codex.wordpress.org/Theme_Unit_Test) it'd be useful to have a .db dump of all types of content that theme developers can test against.

**Comment by nickisnoble** [comment]
I needed this so I did the basics, based on WordPress's version: https://github.com/nickisnoble/ghost-theme-unit-test

**Comment by ErisDS** [comment]
We have a [style test](https://demo.ghost.io/style-test/) post on the demo blog. I figured the raw markdown for that might be useful, so I dropped it in a [gist](https://gist.github.com/ErisDS/7e3455b70133640823c0) - you can grab the raw HTML & markdown for the post there.

I think between this and @nickisnoble's repo, we can probably close this issue for now. I'm going to add a link to this issue to the theme documentation, so if anyone else has something similar they'd like to share, post it here and theme devs will hopefully find it :)

**Comment by kevinSuttle** [comment]
How would you used exported content from your hosted Ghost blog to test themes locally? I'm not sure how to run or link the admin locally to import.
