### ISSUE TITLE
Unexpected behaviour with Cmd+C keybinding on post page

### ISSUE THREAD

**Issue by AlexRoar** [TryGhost/Ghost#15563]
### Issue Summary

When trying to copy text from an article using the Cmd+C key combination, the scroll goes straight to the comments section. When your blog provides code snippets that are frequently copied, this is really bad behaviour

### Steps to Reproduce

If it makes difference, the Journal theme activated

1. Visit any post page 
2. Press Cmd+C

### Ghost Version

5.17.2

### Node.js Version

v16.15.1

### How did you install Ghost?

Ubuntu, Ghost-CLI 1.19.3

### Database type

MySQL 5.7

### Browser & OS version

Safari, MacOS 12.6

### Relevant log / error output

```shell
-
```

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by ErisDS** [comment]
Good catch, that should only be happening for the `c` key, not when used in combo with meta keys. We'll get it fixed up asap.

**Comment by SimonBackx** [comment]
This has been fixed. You don't need to update your Ghost install as long as you are running at least v5.18.0 😊

**Comment by AlexRoar** [comment]
> This has been fixed. You don't need to update your Ghost install as long as you are running at least v5.18.0 😊

Great!
Thanks for the fast issue resolving and for creating a fantastic product
