### ISSUE TITLE
Update command not working with .tgz file

### ISSUE THREAD

**Issue by ASAMedia** [TryGhost/Ghost#15591]
### Issue Summary

Issue Summary

Created a custom zip/tgz file with `yarn build` and tried to upgrade a docker install of ghost(5.17.1) to it (5.17.2) with `ghost update --zip .../../` to the custom one.
I'm thinking the package.json has wrong parameters https://github.com/TryGhost/Ghost/issues/15523.
When I run the update command as node user in docker after copying the archive I get the output as seen in the log section.
Please let me know where the problem lies so I can fix it.

### Steps to Reproduce

1.     Run Ghost as Docker and `docker exec -it <Container> bash` into it.
2.     From there go to `/var/lib/ghost` and examine the directories
3.     As you can see the directory structure is not nearly identical to the new 5. Versions
4.     Create a zip/tgz with yarn build on your local 5.17.2 instance and copy it to the docker
5.     Run `ghost update --zip .../../` inside the docker as node user and watch the log
6.     As you can see, the update command is terminating with the log shown below.

### Ghost Version

5.17.1

### Node.js Version

14.20

### How did you install Ghost?

Docker

### Database type

SQLite3

### Relevant log / error output

```shell
/var/lib/ghost $ ghost update --force --zip /var/lib/Ghost-5.17.2.tgz

Love open source? We’re hiring JavaScript Engineers to work on Ghost full-time.
https://careers.ghost.org



Process manager 'systemd' will not run on this system, defaulting to 'local'
✔ Checking system Node.js version - found v16.17.1
✔ Ensuring user is not logged in as ghost user
✔ Checking if logged in user is directory owner
✔ Checking current folder permissions
✔ Checking folder permissions
✔ Checking file permissions
✔ Checking memory availability
✔ Checking free space
✔ Checking for available migrations
✖ Checking for latest Ghost version
A SystemError occurred.

Message: Archive file does not contain a Ghost release.

Debug Information:
    OS: Alpine Linux, v3.16.2
    Node Version: v16.17.1
    Ghost Version: 5.17.1
    Ghost-CLI Version: 1.23.1
    Environment: production
    Command: 'ghost update --force --zip /var/lib/Ghost-5.17.2.tgz'

Try running ghost doctor to check your system for known issues.

You can always refer to https://ghost.org/docs/ghost-cli/ for troubleshooting.
```

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by ASAMedia** [comment]
Hi @ErisDS ,
as written in #15523 , I already build the tgz file by running the build command.
I now want to update a already working Ghost install to my version with the `ghost update --zip .../../` command as written over [here](https://ghost.org/docs/ghost-cli/).
When I use the before mentioned command with my tgz file it fails with the error log I posted at the beginning of this issue.
There were some changes according the portal build process on the last release, please let me know if this should fix the issue.

**Comment by ErisDS** [comment]
You've raised a bug report claiming that `ghost update` doesn't work, but the command is not failing to work, it's telling you your build is not a valid build.

**Comment by ASAMedia** [comment]
Its not working with the tgz build from the ghost client. 
And thats because the package.json inside the tgz is not where the update command expects it to be.
When I move the package.json one directory up and change the name and version tag inside it gets detected but afterwards the whole ghost install fails. 
And thats because the tgz filestructure is different from the one the ghost update command expects inside of docker.

I dont know its sounds like a problem one both sides (the build and the update procedure) to me.
I also tried the old zip archive from Version 4.18.0 and its works, but its filestructure is coherent with what the update command expects.

**Comment by ErisDS** [comment]
Can you provide the full reproduction steps including _exactly_ how you run `yarn build` and the .tgz file you end up with? It sounds like you're not running `yarn build` in the right place.

**Comment by ASAMedia** [comment]
I forked version 5.17.1 and made some custom changes according its apearance.
I ran `yarn setup` to install all dependencies.
Afterwards I tested it with `yarn dev`.
Everything seems to be working fine at this point.
Now I run `yarn build` in the root directory which includes `ghost  LICENSE  node_modules  package.json  PRIVACY.md  README.md  SECURITY.md  yarn-error.log  yarn.lock`.
The generated file `ghost-monorepo-0.0.0-private.tgz` appears in `/ghost/core`.

Now I run the docker-alpine image ver5.17.2, copy the tgz file into it.
I `docker exec -it <Docker> bash` into it and run the `ghost update -zip /../... .tgz`command as described before with the tgz file.
Because the tgz file has the wrong structure for the update command, at least that what I'm thinking, its not working. 

The tgz is to big to be attached so I uploaded it to [wetransfer](https://we.tl/t-dAADYF2q5S).

**Comment by ASAMedia** [comment]
Hi @ErisDS,
are there any updates on this topic?

**Comment by ErisDS** [comment]
> The generated file `ghost-monorepo-0.0.0-private.tgz` appears in `/ghost/core`.

This isn't the behaviour on an up-to-date and unmodified version of the monorepo. I suggest trying to run `yarn build` without any modifications applied first, to see if that build works for you.

**Comment by ErisDS** [comment]
It seems like you're trying to run `yarn build` on the already built downloads. It only works on the source code... You need to follow https://ghost.org/docs/install/source/

**Comment by ASAMedia** [comment]
First of all, I followed the instructions from [https://ghost.org/docs/install/source/](https://ghost.org/docs/install/source/), but foked the latest release from here [https://github.com/TryGhost/Ghost/tree/v5.19.3](https://github.com/TryGhost/Ghost/tree/v5.19.3).
Second of all, it would be very kind of you, if you could try it out yourself by following my instructions from the last [comment](https://github.com/TryGhost/Ghost/issues/15591#issuecomment-1286261747) to reproduce the issue.

As I sad and described three times by now, the **tgz** produced by the `yarn build` command is not at all compatible with the `ghost update` command. 
Besides the huge differences in structure the package.json has the wrongly formated name `"ghost-monorepo"` instead of the from the [ghost-cli](https://github.com/TryGhost/Ghost-CLI/) expected exact name [`"ghost"`](https://github.com/TryGhost/Ghost-CLI/blob/54eb82f8dbc7a260b551a93f34dae1f81780bcdc/lib/utils/version.js#L204).

Please help me out and reopen the issue.
Maybe @daniellockyer should have a look at it!?

**Comment by ErisDS** [comment]
> It would be very kind of you, if you could try it out yourself

I did try it out. I tried running `yarn build` on multiple versions both in the root directory and in the `ghost/core` directory.

I get a file called `ghost-5.x.x.tgz` output in the root directory, not the weirdly named file you get in `ghost/core`.

After trying it out, I said:

> This isn't the behaviour on an up-to-date and unmodified version of the monorepo.

I also know that the issues you had yesterday with grunt were fixed in the main branch already.

If I cannot reproduce the issue, and noone else is reporting it, I have to assume the issue is specific to you and your ghost clone on your machine... which is why I asked you to test without having made any changes.

What version of `yarn` do you have installed?

**Comment by ErisDS** [comment]
> May you do me a favour and provide your package.json from the root directory

It's this file here:

https://github.com/TryGhost/Ghost/blob/main/package.json

What OS are you on? What version of git &  npm etc?

**Comment by ASAMedia** [comment]
Im on Ubuntu 22.04 with git 2.38.1 and npm 6.14.17
It looks like the `npm pack` command from the [/ghost/core/package.json](https://github.com/TryGhost/Ghost/blob/main/ghost/core/package.json) uses the wrong package.json as reference for packing the tarball file. When I change the name and version of the root [package.json](https://github.com/TryGhost/Ghost/blob/main/package.json), the tgz file has the expected name.
Has this anything to do with the workspace?
When executing `yarn build` I'm in the root directory, but the behaviour stays the same when I switch to /ghost/core

**Comment by ErisDS** [comment]
Can you try updating npm? I'm on 8.19.2

**Comment by ASAMedia** [comment]
Well thats kind of interesting.
I updated npm with `npm install -g npm@latest` to version 8.19.2.
I run again `yarn build` and **now it works as expected**.
The tgz file is generated in the root directory.
This is a very interesting behaviour.🤔 
How can the `npm pack` command work in a different way on different versions?

I will try the `ghost update` command with the tgz of my fork later in the day.

First of all many thanks for your support.
Hopefully I'll be back with great news after running the update command.

**Comment by ASAMedia** [comment]
Everything works now!
Thanks for your help nailing down the problem.
