### ISSUE TITLE
post URL will show preview link if it gets filtered in collection and not included in any other

### ISSUE THREAD

**Issue by Banbeucmas** [TryGhost/Ghost#15645]
### Issue Summary
Like the title suggest.

I put two versions here since it seems to happen with both versions. The odd thing is that the problem didn't occur during 5.17.2 when  I installed it the first time. It happened after I upgraded it to 5.19.1.

Downgrading to 5.17.2 doesn't fix the issue
I am not sure if this is intended behavior or not as well as I can't see why the bug doesn't occurred to me initially

### Steps to Reproduce

1. Upload a redirect.yml entry. The error seem to work on both 301 and 302 but I will only use 301
```yaml
301:
    ^\/azre-([0-9]+)\/$: "/projects/azre-$1"
```
2. Use a template that involves the `#get` helper and fetch the post (hash-works was used to fetch these specific posts, I will describe my intention down below)
```html 
         {{#get "posts" limit="9" filter="tag:hash-works" order="published_at desc" as |works|}}
                {{#foreach works}}
                <article class="{{post_class}}">
                    {{#if feature_image}}
                        <a class="az-works-card-image-link" href="{{url}}">
                            <img srcset="{{img_url feature_image size="s"}} 300w,
                                        {{img_url feature_image size="m"}} 600w,
                                        {{img_url feature_image size="l"}} 1000w,
                                        {{img_url feature_image size="xl"}} 2000w"
                                sizes="(max-width: 1000px) 400px, 800px" 
                                src="{{img_url feature_image size="xl"}}"
                                loading="lazy"/>
                        </a>
                    {{/if}}
                </article>
                {{/foreach}}
            {{/get}}
```
3. Creat post with the tag that fit the filter condition

**Expected result:** {{url}} should return the custom URL link defined in the Admin Panel (Which also would match the redirect Entry)
**Reality**: {{url}} return the preview link `/p/<Insert UUID>` 

It's a bit confusing if one would ask about my intention for this. Basically, I am creating a portfolio index but specific part of them  required to be redirected to either external site or custom make htmls (Hence the /projects/ on redirect.yaml, all of the custom HTML are stored there)
What I came up with was creating dummy posts with internal tags and use `#get` helper to fetch and display it on the page since I want to have the dummy post take care of showing the picture and the `href`

Please know that I am in a situation where I have concluded Dynamic Routing is not feasible. Since the template I am loading this from (`home.hbs`) also have a section that fetch the posts but with `hash-works` filtered out

### Current workaround:
Use pages instead. It works without issue but I am not sure if the issue would spread to pages since I know both are store in the same place in the database
For now, no replication found though, seem highly to be a posts related issue

### Ghost Version

5.19.1 and 5.17.2

### Node.js Version

16.16.0

### How did you install Ghost?

`ghost install local`, rollback with `ghost update --rollback` later on

### Database type

SQLite3

### Browser & OS version

Arch Linux w/ Google Chrome 105.0.5195.102 (Official Build) (64-bit)

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by naz** [comment]
Hey @Banbeucmas 👋  I've followed the steps you've described and was not able to reproduce this on neither SQLite nor MySQL 8 databases. The link for posts with `/azre-0` slug and `hash-works` tag do redirect correctly to `/projects/azre-0` page. When the post is unpublished it no longer is shown on the frontend - this is the only case when the post would have a preview URL formed with `/p/{uuid}` format.

Do you possibly have any custom modifications of the Routes (through routes.yaml)? Can you please check if the bug happens on the latest version of Ghost too?

**Comment by Banbeucmas** [comment]
> Do you possibly have any custom modifications of the Routes (through routes.yaml)? Can you please check if the bug happens on the latest version of Ghost too?
Indeed there is
```
routes:
  /: home
collections:
  /posts/:
    permalink: /{slug}/
    template: index
    filter: "tag:-hash-works"

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
```
This is happening on the `home.hbs` template. Which has 2 sections that involves the `#get` and `#forEach` helper. Before the `#get` helper mentioned on the top above was used. This was the other `#get` helper

```html
        {{#get "posts" limit="3" filter="tag:-hash-works"}}
        <div class="az-news-content-wrapper">
            {{#foreach posts}}
            <a class="news-posts" href="{{url}}">
                <span>
                    <b>[<time datetime="{{date format="YYYY-MM-DD"}}">{{date format="DD/MM/YYYY"}}</time>] </b> 
                        {{title words="8"}}
                </span>
            </a>
            {{/foreach}}
       </div>
        {{/get}}
```

Beyond this, there is no other section in this file that use any other helper.

As for testing against the latest version, I will try to replicate it when I have time.  I also have a different machine as well so I will also try to do it on that machine and verify if this a system-specific issue or not.

**Comment by Banbeucmas** [comment]
@naz Getting back to the Issue since I just tested it in a different machine. Seem like the issue is not machine independant. On the latest version as well

I will also provide the log of me trying to replicate the issue with timestamp comments to aid
[ghost.log](https://github.com/TryGhost/Ghost/files/9826250/ghost.log)

I would also provide the full redirect.yaml (With external URL redacted) since seem like there is an exception thrown
```yaml
301:
    /elfrideanstories/: "/projects/azre-0002"
    ^\/azre-([0-9]+)\/$: "/projects/azre-$1"
302:
    /grimoire-academia/: "<Insert URL Here>"
    /azre-0001/: "<Insert URL Here>"

```

**Comment by Banbeucmas** [comment]
May I have an update to this issue?

**Comment by Banbeucmas** [comment]
@naz Have you found a way to replicate this issue now? Because if not I am willing to try and provide more details.

**Comment by naz** [comment]
Will be having a look at the issue with the details you've provided @Banbeucmas. Thanks for following up and patience 🙏

**Comment by naz** [comment]
This bit is quite interesting. Wonder what is causing this error.
```
// Uploading redirect.yaml

[2022-10-20 04:21:05] [36mINFO[39m "POST /ghost/api/admin/redirects/upload/" [32m200[39m 29ms
[2022-10-20 04:21:09] [31mERROR[39m This should not happen.
[31m
[31mThis should not happen.[39m

[1m[37mError ID:[39m[22m
    [90m9f9bf7f0-502e-11ed-96a1-71dd67ca7bc0[39m

[1m[37mError Code: [39m[22m
    [90mURLSERVICE_RESOURCE_DUPLICATE[39m

[90m----------------------------------------[39m

[90mInternalServerError: This should not happen.
    at Urls.add (/home/banbeucmas/Projects/ghost-fresh/versions/5.19.3/core/server/services/url/Urls.js:44:27)
    at UrlGenerator._try (/home/banbeucmas/Projects/ghost-fresh/versions/5.19.3/core/server/services/url/UrlGenerator.js:176:23)
    at /home/banbeucmas/Projects/ghost-fresh/versions/5.19.3/core/server/services/url/UrlGenerator.js:132:18
    at arrayEach (/home/banbeucmas/Projects/ghost-fresh/versions/5.19.3/node_modules/lodash/lodash.js:530:11)
    at Function.forEach (/home/banbeucmas/Projects/ghost-fresh/versions/5.19.3/node_modules/lodash/lodash.js:9410:14)
    at UrlGenerator._onInit (/home/banbeucmas/Projects/ghost-fresh/versions/5.19.3/core/server/services/url/UrlGenerator.js:131:11)
    at Queue.run (/home/banbeucmas/Projects/ghost-fresh/versions/5.19.3/core/server/services/url/Queue.js:125:17)
    at Queue.run (/home/banbeucmas/Projects/ghost-fresh/versions/5.19.3/core/server/services/url/Queue.js:129:22)
    at Queue.run (/home/banbeucmas/Projects/ghost-fresh/versions/5.19.3/core/server/services/url/Queue.js:129:22)
    at Queue.run (/home/banbeucmas/Projects/ghost-fresh/versions/5.19.3/core/server/services/url/Queue.js:129:22)
    at Queue.start (/home/banbeucmas/Projects/ghost-fresh/versions/5.19.3/core/server/services/url/Queue.js:216:14)
    at Bridge.reloadFrontend (/home/banbeucmas/Projects/ghost-fresh/versions/5.19.3/core/bridge.js:106:26)
    at async RouteSettings.setFromFilePath (/home/banbeucmas/Projects/ghost-fresh/versions/5.19.3/core/server/services/route-settings/route-settings.js:110:13)
    at async Object.query (/home/banbeucmas/Projects/ghost-fresh/versions/5.19.3/core/server/api/endpoints/settings.js:150:13)[39m
[39m
[2022-10-20 04:21:10] [36mINFO[39m Ghost URL Service Ready in 567.21s
```

Will try replicating with the redirects config from above:
```yaml
301:
    /elfrideanstories/: "/projects/azre-0002"
    ^\/azre-([0-9]+)\/$: "/projects/azre-$1"
302:
    /grimoire-academia/: "<Insert URL Here>"
    /azre-0001/: "<Insert URL Here>"
```

**Comment by naz** [comment]
I was not able to reproduce the case on my machine. I suspect it has something to do with the posts or pages present on the instance, base on the log review and not being able to get the bug working locally. The error present in the logs happens when the post's url is being generated [here](https://github.com/TryGhost/Ghost/blob/409377476d5107190b774cd1ee28e9ab1d89a03a/ghost/core/core/server/services/url/Urls.js#L43-L50). It clashes with an existing resource url (somehow the routing/redirecs rules configured on the instance are producing the same result). Are you able to debug the error further and see which resources are clashing?

**Comment by naz** [comment]
Also, would be great if you could come up with a state that reproduces this issue on someone else's environment  🙌

**Comment by Banbeucmas** [comment]
@naz Thanks for the insight, I have decided to look further more into the issue. It just gets weirder however but seem like I also have found the trigger to this issue on my machine.
Can you try to see if using the filter in `routes.yml` while also using the same filter in {#get} would cause the issue?
Commenting it seem to resolve the issue for me.

```yaml
routes:
  /: home
collections:
  /posts/:
    permalink: /{slug}/
    template: index
#    filter: "tag:-hash-works"

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
```

**Comment by Banbeucmas** [comment]
@naz In case you haven't seen it yet, I have included more edits to the above comments. I think this is the crux of the issue we are having where collections need to have all of the post mentioned to work.

**Comment by naz** [comment]
Just had some time to have another look and was able to reproduce the bug with the `routes.yaml` modification [described above](https://github.com/TryGhost/Ghost/issues/15645#issuecomment-1292989916) 🎉

**Comment by naz** [comment]
To be very clear,the issue has nothing to do with redirects. It's has to do only with the "filter" configuration in the `routes.yaml`

**Comment by Banbeucmas** [comment]
> To be very clear,the issue has nothing to do with redirects. It's has to do only with the "filter" configuration in the `routes.yaml`

I think the correct title here is that "posts will show preview link if it gets filtered in collection". Pretty sure this situation happens with `routes:` as well.

**Comment by naz** [comment]
Have figured out the issue... so the correct behavior in this case should be a `/404/` link. This is because if we exclude all of the posts from the "collection" they should not have _any url_ assigned at all. Current behavior where we server a preview link as a [fix for very old Discus bug](https://github.com/TryGhost/Ghost/blob/6c5553d059f64785a189b5217070eedc67875a61/ghost/core/core/frontend/meta/url.js#L17-L31). 

I think the right was forward here is removing the Discus patch code completely (needs to be checked first if that would effect any/many production sites running Ghost v5).

**Comment by Banbeucmas** [comment]
> Have figured out the issue... so the correct behavior in this case should be a `/404/` link. This is because if we exclude all of the posts from the "collection" they should not have _any url_ assigned at all. Current behavior where we server a preview link as a [fix for very old Discus bug](https://github.com/TryGhost/Ghost/blob/6c5553d059f64785a189b5217070eedc67875a61/ghost/core/core/frontend/meta/url.js#L17-L31).
> 
> I think the right was forward here is removing the Discus patch code completely (needs to be checked first if that would effect any/many production sites running Ghost v5).

So if I am understanding this correctly, the intended behavior is that routes.yml `collection` should include all of the post that is filtered into right?

**Comment by naz** [comment]
Yes, for the post to have a correct URL it should always be included at least in one of the collections. Otherwise there's no way for it to calculate the URL.

**Comment by naz** [comment]
The reproduction of this bug collides with a fix to a [Disqus comments bug](https://github.com/TryGhost/Ghost/issues/9727).

**Comment by Banbeucmas** [comment]
> Yes, for the post to have a correct URL it should always be included at least in one of the collections. Otherwise, there's no way for it to calculate the URL.

I see, it seems like it is also a bit on my part for not knowing it (Since I didn't aware of the collection has to document the post needed). Though glad that this also accidentally activate a reproducible bug

Cheers

**Comment by naz** [comment]
@Banbeucmas thanks for helping out debugging it and staying patient 😅 In your case I think the "fix" would be to have a collection with posts having "hash-" slug. The underlying issue itself might be fixed in the future, but I don't see it as a super high priority bug atm.

**Comment by Banbeucmas** [comment]
> @Banbeucmas thanks for helping out debugging it and staying patient sweat_smile In your case I think the "fix" would be to have a collection with posts having "hash-" slug. The underlying issue itself might be fixed in the future, but I don't see it as a super high priority bug atm.

Yeah, I figured it out when I found out how to reproduce it.
 
In the meantime, I think this issue will be left open (I might see if I can do a PR if I have time). Thanks for the support :+1:
