### ISSUE TITLE
Security vulnerabilities in dependencies

### ISSUE THREAD

**Issue by mlc-mlapis** [TryGhost/Ghost#15683]
### Issue Summary

GitHub reports: We found potential security vulnerabilities in your dependencies.

### Steps to Reproduce

![image](https://user-images.githubusercontent.com/5693835/197505732-b9dc9d5e-662f-4d4f-ade2-33b7073cb110.png)

### Ghost Version

5.20.0

### Node.js Version

14.x, 16.x, ...

### How did you install Ghost?

Standard way

### Database type

MySQL 8

### Browser & OS version

any

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by ErisDS** [comment]
Hi there again @mlc-mlapis,

We have internal policies and process for monitoring and reviewing vulnerability reports from npm & GitHub, and in the majority of cases the warnings aren't relevant to the security of Ghost. You can read more about why this is the case [here](https://overreacted.io/npm-audit-broken-by-design/).

If there’s a specific package that you believe does compromise the security of Ghost, we encourage you to follow our Responsible Disclosure Guidelines (https://docs.ghost.org/concepts/vulnerabilities/). Most projects on GitHub have a security policy published on their repository and you would have been shown this when you went to raise this issue:

![image](https://user-images.githubusercontent.com/101513/137867951-c98edd58-a211-4e1c-aef6-0139154013f0.png)

For now I am going to close and delete this, as having discussions about vulnerabilities in public is extremely bad practice.
