### ISSUE TITLE
Update flow requires double update between v4 and v5

### ISSUE THREAD

**Issue by TomGranot** [TryGhost/Ghost#15692]
### Issue Summary

When trying to update from v3 to v5 (latest), I came across a situation in which I need to double-update v4 in order to get the truly latest v4, before being able to finally upgrade to v5. I think this flow is a bit weird - 

### Steps to Reproduce

1. Update from v3 using `ghost update`
2. Get asked to update to v4 first, run `ghost update v4`
3. Try running `ghost update v5` and `ghost update` but fail since latest v4 is not installed
4. Run `ghost update v4` again to get (really) latest v4
6. Run `ghost update` to get latest ghost v5
7. Profit 

### Ghost Version

3.*

### Node.js Version

16

### How did you install Ghost?

Directly on Ubuntu

### Database type

MySQL 8

### Browser & OS version

Ubuntu 18

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by yeshwantthota** [comment]
@TomGranot hey I am a beginner to open source can I contribute to this issue?

**Comment by ErisDS** [comment]
@TomGranot this is certainly not expected but I'm missing a few details to reproduce:

1. What exact version of Ghost v3 did you start on?
2. Which exact version of Ghost v4 did you upgrade to, and when?
3. When did you upgrade to v5 / how long was there between the two upgrades?

My best guess is that a new version of v4 was released in the middle of your upgrade process.

**Comment by TomGranot** [comment]
@yeshwantthota stay tuned, let's see what gives. Thank you for offering!!

@ErisDS Everything happened in the span of a few hours, so I assume that might be what happened.

Can't recall which v3 or v4 unfortunately. Feel free to close if this contains too little info

**Comment by ErisDS** [comment]
OK great - I will close this for now and move it over to the Ghost CLI repo. If we get more reports we can reopen and investigate further.
