### ISSUE TITLE
Ghost code snippet doesn't work with nginx code listing

### ISSUE THREAD

**Issue by Vadimkin** [TryGhost/Ghost#15726]
### Issue Summary

I want to show some nginx-code example in code snippet, but ghost will not highlight it. I am using `nginx` as code language.

In the editor, it looks like:
![CleanShot 2022-10-30 at 12 48 59](https://user-images.githubusercontent.com/2240404/198874661-d342e6d9-c7a7-4b60-944d-27113a90f2dd.png)

In the post page:
![CleanShot 2022-10-30 at 12 49 21](https://user-images.githubusercontent.com/2240404/198874679-537795af-2df1-4e61-a952-e3c3096c762a.png)

Without `nginx` language, `hightlight.js` uses bash language to highlight it (which is wrong).

Nginx is supported by `hightlight.js`: https://highlightjs.org/static/demo/. Select "config" language category and search for "Nginx config":
![CleanShot 2022-10-30 at 13 00 12](https://user-images.githubusercontent.com/2240404/198875078-bb12e5b0-d44c-43c8-a025-35fca51114c7.png)

### Steps to Reproduce

1. Add a comment snippet to the post and set a language `nginx`.
```nginx
server {
    # ...
    location /ping/ {
        default_type 'application/json';
        content_by_lua '...';
    }
}
```
2. Publish this post
3. Nginx config will not be highlighted, but it should be

### Ghost Version

5.20.0

### Node.js Version

v16.18.0

### How did you install Ghost?

Docker container, host system Ubuntu 20.04.5

### Database type

MySQL 8

### Browser & OS version

Safari 16.1, macOS 13.0 (22A380)

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by ErisDS** [comment]
Hey @Vadimkin, can you confirm what theme you're using? This seems like a theme specific issue.

**Comment by ivangil-dev** [comment]
The problem is that the casper theme doesn't seem to include highlight.js but its own version generated with css style files
It is mentioned here: [https://github.com/TryGhost/Casper/issues/372#issuecomment-324375929](https://github.com/TryGhost/Casper/issues/372#issuecomment-324375929)

So it seems more like your specific theme problem than the Ghost Blog itself, maybe you can include hightlight.js in your theme directly by adding this in your head `<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/highlight.js/11.7.0/styles/default.min.css">`

and this in your footer: `<script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/11.7.0/highlight.min.js"></script>`

**Comment by Vadimkin** [comment]
Hi @ivangil-dev 

Thank you very much! I didn't realize that casper contains their own hightlight styles and scripts.

My solution:

Added to `<head>`:
```
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/highlight.js/11.7.0/styles/default.min.css">
```

Site footer (`nginx.min.js` needs to be imported since base package doesn't contain nginx config notation):
```
<script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/11.7.0/highlight.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/11.7.0/languages/nginx.min.js"></script>
```

Use `nginx` language in the post:
<img width="883" alt="CleanShot 2022-12-03 at 21 33 55@2x" src="https://user-images.githubusercontent.com/2240404/205458606-4c2b7056-ccf1-401e-949c-8780215e4828.png">

How it looks in the post (casper theme):
<img width="950" alt="CleanShot 2022-12-03 at 21 34 22@2x" src="https://user-images.githubusercontent.com/2240404/205458629-c99faefa-db73-4584-b563-60ab009b9c0b.png">
