### ISSUE TITLE
Search Function does not work due to CORS access control

### ISSUE THREAD

**Issue by Ex10si0n** [TryGhost/Ghost#15728]
### Issue Summary

I use docker ghost 5.17.2 version from [https://hub.docker.com/_/ghost](https://hub.docker.com/_/ghost). The built-in search is not work due to CORS access control checks. I do not use ghost as a CMS. Instead, I use the casper theme. I think that this bug is caused due to CORS access control policy, so where could I specify the Access-Control-Allow-Origin in HTTP request in the backend.

### Steps to Reproduce

1. Click search button on website
2. No response
3. Open Developer Tools
4. Logs provided as follow

### Ghost Version

5.17.2

### Node.js Version

16.17.1

### How did you install Ghost?

Docker run on Ubuntu Linux

### Database type

SQLite3

### Relevant log / error output

```shell
[Error] Preflight response is not successful. Status code: 301
[Error] XMLHttpRequest cannot load https://aspires.cc/ghost/api/content/posts/?key=87e71ee411e5a336cff00b0906&limit=10000&fields=id%2Cslug%2Ctitle%2Cexcerpt%2Curl%2Cupdated_at%2Cvisibility&order=updated_at%20DESC due to access control checks.
[Error] Failed to load resource: Preflight response is not successful. Status code: 301 (posts, line 0)
[Error] Unhandled Promise Rejection: AxiosError: Network Error
	dispatchException (sodo-search.min.js:2:254618)
	(anonymous function) (sodo-search.min.js:2:250803)
	v (sodo-search.min.js:2:256363)
	a (sodo-search.min.js:2:256603)
	promiseReactionJob
```

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by ErisDS** [comment]
The search function is working as expected on all standard setups.

>  I do not use ghost as a CMS. Instead, I use the casper theme.

I couldn't make sense of what you mean by this. Can you explain more about your setup? Particularly everything to do with your domain/url configuration.

**Comment by Ex10si0n** [comment]
I deployed Ghost using docker deploy command: `docker run -d --name some-ghost -e NODE_ENV=development -p 80:2368 -v /var/www/aspires:/var/lib/ghost/content -e url=https://aspires.cc ghost` with nothing changed inside the docker container. However, the search function does not work. The error log (from web debugger) is displayed below.

- PS. I use Cloudflare to proxy my domain's DNS server, I don't know if this make the problem

<img width="1492" alt="Screenshot 2022-11-02 at 11 41 15" src="https://user-images.githubusercontent.com/29248341/199390109-a8b80f36-d88c-47e1-a0be-524a8c347eb3.png">

**Comment by ErisDS** [comment]
This doesn't seem like a bug in Ghost. You shouldn't be deploying Ghost in development onto a production site - although I doubt that's the problem. You can get help with docker from the docker community that maintains the [docker image for Ghost](https://github.com/docker-library/ghost/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) or from our [forum](https://ghost.org). Forum is probably best to solve this specific issue as it's likely cloudflare.
