### ISSUE TITLE
Mailgun BATCH_SIZE with a fix value of 1000 is incompatible with new users

### ISSUE THREAD

**Issue by ltoinel** [TryGhost/Ghost#15725]
### Issue Summary

Hi,

When you want to use Mailgun with the flex offer, they block your account to a maximum BATCH_SIZE to 10.
This value is currently to defined to 1000 and cannot be overide with settings by the end user.

in bulk-email-processor.js : 
`
module.exports = {
    BATCH_SIZE: MailgunClient.BATCH_SIZE,
`

Could be  : 
`
module.exports = {
    BATCH_SIZE: bulkEmailConfig?.mailgun?.batch_size,
`

A new setting to allow the users to set a BATCH_SIZE to 10 could be great to allow Mailgun to evaluate the mail quality before to increase to 1000 the batch size.

Thank-you ! 

### Steps to Reproduce

1. Create a ghost instance.
2. Create a Mailgun account.
3. Add 11 members to the newsletter
4. Send a newsletter
5. Mailgun will not accept more that 10 members in the recipient.

### Ghost Version

v5.19.0

### Node.js Version

v16.17.0

### How did you install Ghost?

Ghost CLI + Ghost Update

### Database type

MySQL 8

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by dest4** [comment]
The new setting is probably the best idea.

Other, probably worse, approaches:
- start with batch size of 1000 but if Mailgun account limitation is detected, retry with 10 (no config needed, but more complex to implement?).
- set the batch size to 10 by default for all users (trivial to implement, but slow delivery for big publishers?)

**Comment by ltoinel** [comment]
@dest4  : Overwise use a dynamic batch size regarding your members count ? This allows you to start your blog with the mailgun restrictions.

`if (nb_members < 100) 
     batch_size =10;
else {
      batch_size =1000;
}`

**Comment by ErisDS** [comment]
We are actively talking to mailgun about how to make the onboarding process work more smoothly. I've raised this to them as, as far as I know, there is no way for us to auto-detect when the account is limited.

**Comment by dest4** [comment]
Knowing before trying that the account is limited is probably not possible. But once the call to Mailgun API fails, it seems to be possible to infer it.

Here are a couple of lines of log when sending fails due to account limitation

```
[2022-10-31 19:38:29] WARN The email service received an error from mailgun and was unable to send.

The email service received an error from mailgun and was unable to send.

"Mailgun Error 403: Domain mg.XXXXX.fr is not allowed to send large batches yet"
"https://ghost.org/docs/newsletters/#bulk-email-configuration"

Error ID:
    9856dae0-5953-11ed-a2d9-XXXXXXXXX

Error Code: 
    BULK_EMAIL_SEND_FAILED

----------------------------------------

EmailError: The email service received an error from mailgun and was unable to send.
    at Object.send (/var/lib/ghost/versions/5.20.0/core/server/services/bulk-email/bulk-email-processor.js:260:30)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.processEmailBatch (/var/lib/ghost/versions/5.20.0/core/server/services/bulk-email/bulk-email-processor.js:179:34)
    at async Promise.map.concurrency (/var/lib/ghost/versions/5.20.0/core/server/services/bulk-email/bulk-email-processor.js:104:17)
```

The `is not allowed to send large batches yet` seems specific-enough. Though I don't know how stable over time this heuristic can be.

**Comment by encodedguy** [comment]
In my case it is BATCH_SIZE=1000 but I am still not able to send mail to more than 10 members.

**Comment by ltoinel** [comment]
@encodedguy  : Me too since few days ... The limitation of 10 recipients max seems to be reduced by Mailgun. 
I have 23 subscribers. My two batchs of 10 recipients have refused, only the batch of 3 recipients has been accepted ... 
I'm trying to understand what is the new limit ... 5 maybe ?

**Comment by ltoinel** [comment]
New tests done tonight with a BATCH_SIZE = 5 with 28 subscribers on my newsletter.

- The 5 first batchs of 5 recipients has been accepted by Mailgun.
- The last batch with 3 recipients has been rejected with "Domain xx is not allowed to send: recipient limit exceeded"

Is there a new max recipient limit plus a quota limit on the number of emails per minutes ?  Strange.

**Comment by olearycrew** [comment]
It would be great if we could make this configurable - I'm currently having the problem as well with only 37 subscribers....and I'm running Ghost in Docker so I can't easily modify the code.

**Comment by dest4** [comment]
Note that SendInBlue seems to have a free tier, with up to 300 messages per day, with an added logo though. https://www.sendinblue.com/pricing/

**Comment by ugurcany** [comment]
How will adding unique tag to mailgun requests resolve batch limit issue? Could someone please explain? We are stuck at 10 subscribers while sending newsletters.

**Comment by ErisDS** [comment]
It is not a fix, but rather surfacing information to mailgun so they can understand the issues self hosted Ghost users are having with onboarding.

**Comment by dest4** [comment]
Hi, is there progress to report on this topic?

In the meantime, for other users who would have issues, you have two solutions:

1 - Change `BATCH_SIZE` to e.g. 1 in https://github.com/TryGhost/Ghost/blob/main/ghost/mailgun-client/lib/mailgun-client.js#L10. This needs to be done before the first attempt to send the campaign. Also make sure to restart the server.

2 - If you have a stuck campaign, do step 1 anyway but also edit the same file below https://github.com/TryGhost/Ghost/blob/main/ghost/mailgun-client/lib/mailgun-client.js#L91
```
let response;
for (let i = 0; i < messageData.to.length; i++) {
    response = await mailgunInstance.messages.create(mailgunConfig.domain, { ...messageData, to: messageData.to[i] });
}
```
This explicitly sends the messages one by one.

-----

Users of the Docker image, don't despair, you can still do this (and subsequently after each update):

1 - Get in the Docker image: `sudo docker exec -ti my-ghost-image-name /bin/bash`

2  - In the image shell, do your edits as described above
```
apt-get update && apt-get install nano
nano ./versions/5.30.0/node_modules/\@tryghost/mailgun-client/lib/mailgun-client.js
```
Note that 5.30.0 is subject to change

3 - Restart Ghost `sudo docker restart my-ghost-image-name`

**Comment by ErisDS** [comment]
Could anyone and everyone experiencing this issue please share the exact error that they get back from Mailgun.

Also, everyone who is talking about the batch size limit being 10 - can you clarify how you figured this out?

**Comment by dest4** [comment]
@ErisDS for the exact error message see above https://github.com/TryGhost/Ghost/issues/15725#issuecomment-1301307570

**Comment by ErisDS** [comment]
Yeah @dest4 I saw yours - but you're the only one who provided a concrete error. I am struggling to get anywhere with this issue because there's too much speculation on the solution, and not enough clarity on what the problem _actually_ is. 

I need more copy-pasted mailgun errors, and more exact information about how limits are being determined, from more than one person please.

**Comment by DLMorgan** [comment]
@ErisDS Hope this helps.

```{"name":"Log","hostname":"d234f5229521","pid":1,"level":30,"version":"5.33.6","msg":"Starting email job for email 63e14e54a36f6f000126ba97","time":"2023-02-06T19:28:55.317Z","v":0}
{"name":"Log","hostname":"d234f5229521","pid":1,"level":30,"version":"5.33.6","msg":"Sending email 63e14e54a36f6f000126ba97","time":"2023-02-06T19:28:55.322Z","v":0}
{"name":"Log","hostname":"d234f5229521","pid":1,"level":30,"version":"5.33.6","msg":"Getting batches for email 63e14e54a36f6f000126ba97","time":"2023-02-06T19:28:55.325Z","v":0}
{"name":"Log","hostname":"d234f5229521","pid":1,"level":30,"version":"5.33.6","msg":"Sending 1 batches for email 63e14e54a36f6f000126ba97","time":"2023-02-06T19:28:55.327Z","v":0}
{"name":"Log","hostname":"d234f5229521","pid":1,"level":30,"version":"5.33.6","msg":"Sending batch 63e14e54a36f6f000126ba98 for email 63e14e54a36f6f000126ba97","time":"2023-02-06T19:28:55.328Z","v":0}
{"name":"Log","hostname":"d234f5229521","pid":1,"level":30,"version":"5.33.6","msg":"Sending email to 21 recipients","time":"2023-02-06T19:28:55.461Z","v":0}
{"name":"Log","hostname":"d234f5229521","pid":1,"level":50,"version":"5.33.6","err":{"domain":"https://my_domain_name_here.com","message":"Forbidden","stack":""},"msg":"Forbidden","time":"2023-02-06T19:28:55.743Z","v":0}
{"name":"Log","hostname":"d234f5229521","pid":1,"level":50,"version":"5.33.6","err":{"id":"7f0dd4f0-a654-11ed-a868-63651d2accb9","domain":"https://my_domain_name_here.com","code":"BULK_EMAIL_SEND_FAILED","name":"EmailError","statusCode":403,"level":"normal","message":"Forbidden: Domain my_domain_name_here.com is not allowed to send large batches yet","context":"\"Mailgun Error 403: Domain my_domain_name_here.com is not allowed to send large batches yet\"","help":"\"https://ghost.org/docs/newsletters/#bulk-email-configuration\"","stack":"EmailError: Forbidden: Domain my_domain_name_here.com is not allowed to send large batches yet\n    at MailgunEmailProvider.send (/var/lib/ghost/versions/5.33.6/node_modules/@tryghost/email-service/lib/mailgun-email-provider.js:153:30)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async SendingService.send (/var/lib/ghost/versions/5.33.6/node_modules/@tryghost/email-service/lib/sending-service.js:96:16)\n    at async BatchSendingService.sendBatch (/var/lib/ghost/versions/5.33.6/node_modules/@tryghost/email-service/lib/batch-sending-service.js:392:30)\n    at async runNext (/var/lib/ghost/versions/5.33.6/node_modules/@tryghost/email-service/lib/batch-sending-service.js:329:21)\n    at async Promise.all (index 0)\n    at async BatchSendingService.sendBatches (/var/lib/ghost/versions/5.33.6/node_modules/@tryghost/email-service/lib/batch-sending-service.js:337:9)\n    at async BatchSendingService.sendEmail (/var/lib/ghost/versions/5.33.6/node_modules/@tryghost/email-service/lib/batch-sending-service.js:185:9)\n    at async BatchSendingService.emailJob (/var/lib/ghost/versions/5.33.6/node_modules/@tryghost/email-service/lib/batch-sending-service.js:129:13)\n    at async /var/lib/ghost/versions/5.33.6/node_modules/@tryghost/job-manager/lib/job-manager.js:224:25\n    at async JobManager.worker (/var/lib/ghost/versions/5.33.6/node_modules/@tryghost/job-manager/lib/job-manager.js:16:22)","hideStack":false,"errorDetails":"\"{\\\"error\\\":{\\\"status\\\":403,\\\"message\\\":\\\"Forbidden\\\",\\\"details\\\":\\\"Domain my_domain_name_here.com is not allowed to send large batches yet\\\"},\\\"messageData\\\":{email_content_here}}\""},"msg":"Forbidden: Domain my_domain_name_here.com is not allowed to send large batches yet","time":"2023-02-06T19:28:55.746Z","v":0}
{"name":"Log","hostname":"d234f5229521","pid":1,"level":30,"version":"5.33.6","msg":"Capturing error for mailgun email provider service","time":"2023-02-06T19:28:55.746Z","v":0}
{"name":"Log","hostname":"d234f5229521","pid":1,"level":50,"version":"5.33.6","err":{"id":"7f10e230-a654-11ed-a868-63651d2accb9","domain":"https://my_domain_name_here.com","code":"BULK_EMAIL_SEND_FAILED","name":"EmailError","statusCode":500,"level":"normal","message":"Error sending email 63e14e54a36f6f000126ba97","stack":"EmailError: An unexpected error occurred, please retry sending your newsletter.\n    at BatchSendingService.emailJob (/var/lib/ghost/versions/5.33.6/node_modules/@tryghost/email-service/lib/batch-sending-service.js:139:32)\n    at BatchSendingService.sendBatches (/var/lib/ghost/versions/5.33.6/node_modules/@tryghost/email-service/lib/batch-sending-service.js:345:19)\n    at async BatchSendingService.sendEmail (/var/lib/ghost/versions/5.33.6/node_modules/@tryghost/email-service/lib/batch-sending-service.js:185:9)\n    at async BatchSendingService.emailJob (/var/lib/ghost/versions/5.33.6/node_modules/@tryghost/email-service/lib/batch-sending-service.js:129:13)\n    at async /var/lib/ghost/versions/5.33.6/node_modules/@tryghost/job-manager/lib/job-manager.js:224:25\n    at async JobManager.worker (/var/lib/ghost/versions/5.33.6/node_modules/@tryghost/job-manager/lib/job-manager.js:16:22)","hideStack":false},"msg":"Error sending email 63e14e54a36f6f000126ba97","time":"2023-02-06T19:28:55.764Z","v":0}
{"name":"Log","hostname":"d234f5229521","pid":1,"level":30,"version":"5.33.6","req":{"meta":{"requestId":"59bb1c6f-9881-4f6e-a415-5de11bd26202","userId":"1"},"url":"/emails/63e14e54a36f6f000126ba97/","method":"GET","originalUrl":"/ghost/api/admin/emails/63e14e54a36f6f000126ba97/","params":{"id":"63e14e54a36f6f000126ba97"},"headers":{"host":"my_domain_name_here.com","x-forwarded-scheme":"https","x-forwarded-proto":"https","x-forwarded-for":"172.71.146.79","x-real-ip":"172.71.146.79","cf-ipcountry":"US","cdn-loop":"cloudflare","accept-encoding":"gzip","cf-ray":"79564ab0dfb7308d-SEA","cf-visitor":"{\"scheme\":\"https\"}","accept":"application/json, text/javascript, */*; q=0.01","x-requested-with":"XMLHttpRequest","x-ghost-version":"5.33","app-pragma":"no-cache","user-agent":"Mozilla/5.0 (Linux; Android 9; SAMSUNG SM-G950U) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/19.0 Chrome/102.0.5005.125 Mobile Safari/537.36","content-type":"application/json; charset=UTF-8","sec-fetch-site":"same-origin","sec-fetch-mode":"cors","sec-fetch-dest":"empty","referer":"https://my_domain_name_here.com/ghost/","accept-language":"en-US,en;q=0.9","cf-connecting-ip":"2607:fb90:82a8:37c0:f926:37c5:9936:f109","cookie":"**REDACTED**"},"query":{}},"res":{"_headers":{"x-powered-by":"Express","content-version":"v5.33","vary":"Accept-Version, Accept-Encoding","cache-control":"no-cache, private, no-store, must-revalidate, max-stale=0, post-check=0, pre-check=0","content-type":"application/json; charset=utf-8","etag":"W/\"1490-EEn37yGCnuMp4UYeOmdUh6w95NI\"","content-encoding":"gzip"},"statusCode":200,"responseTime":"7ms"},"msg":"","time":"2023-02-06T19:28:56.481Z","v":0}
{"name":"Log","hostname":"d234f5229521","pid":1,"level":30,"version":"5.33.6","worker":{"resourceLimits":{"maxYoungGenerationSizeMb":48,"maxOldGenerationSizeMb":4096,"codeRangeSizeMb":0,"stackSizeMb":4},"threadId":441},"msg":"Worker for job \"email-analytics-fetch-latest\" online","time":"2023-02-06T19:28:57.785Z","v":0}
{"name":"Log","hostname":"d234f5229521","pid":1,"level":30,"version":"5.33.6","msg":"Worker for job email-analytics-fetch-latest sent a message: Fetched 4 events and aggregated stats for 1 emails in 1418ms","time":"2023-02-06T19:28:59.492Z","v":0}
{"name":"Log","hostname":"d234f5229521","pid":1,"level":30,"version":"5.33.6","msg":"Worker for job email-analytics-fetch-latest sent a message: done","time":"2023-02-06T19:28:59.492Z","v":0}
{"name":"Log","hostname":"d234f5229521","pid":1,"level":30,"version":"5.33.6","req":{"meta":{"requestId":"f630a9d7-6917-405d-8e99-ac15fece074f","userId":null},"url":"/","method":"GET","originalUrl":"/","params":{},"headers":{"host":"my_domain_name_here.com","x-forwarded-scheme":"https","x-forwarded-proto":"https","x-forwarded-for":"172.70.206.232","x-real-ip":"172.70.206.232","cf-ipcountry":"US","cdn-loop":"cloudflare","accept-encoding":"gzip","cf-ray":"79564b565df27edb-LAX","cf-visitor":"{\"scheme\":\"https\"}","accept":"text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9","user-agent":"Uptime-Kuma/1.19.6","cf-connecting-ip":"67.181.xxx.xxx"},"query":{}},"res":{"_headers":{"x-powered-by":"Express","cache-control":"public, max-age=0","content-type":"text/html; charset=utf-8","etag":"W/\"4a8c-7BOYvRHtBZIJUXJIozIpJL/TO6Q\"","vary":"Accept-Encoding","content-encoding":"gzip"},"statusCode":200,"responseTime":"24ms"},"msg":"","time":"2023-02-06T19:29:23.031Z","v":0}
{"name":"Log","hostname":"d234f5229521","pid":1,"level":30,"version":"5.33.6","req":{"meta":{"requestId":"dc97a466-7c5d-4d5a-a95f-bf08fe820330","userId":null},"url":"/","method":"GET","originalUrl":"/","params":{},"headers":{"host":"my_domain_name_here.com","x-forwarded-scheme":"https","x-forwarded-proto":"https","x-forwarded-for":"172.69.34.99","x-real-ip":"172.69.34.99","cf-ipcountry":"US","cdn-loop":"cloudflare","accept-encoding":"gzip","cf-ray":"79564cceaf1628fa-LAX","cf-visitor":"{\"scheme\":\"https\"}","accept":"text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9","user-agent":"Uptime-Kuma/1.19.6","cf-connecting-ip":"67.181.xxx.xxx"},"query":{}},"res":{"_headers":{"x-powered-by":"Express","cache-control":"public, max-age=0","content-type":"text/html; charset=utf-8","etag":"W/\"4a8c-7BOYvRHtBZIJUXJIozIpJL/TO6Q\"","vary":"Accept-Encoding","content-encoding":"gzip"},"statusCode":200,"responseTime":"25ms"},"msg":"","time":"2023-02-06T19:30:23.243Z","v":0}
{"name":"Log","hostname":"d234f5229521","pid":1,"level":40,"version":"5.33.6","err":{"domain":"https://my_domain_name_here.com","code":"ECONNREFUSED","message":"connect ECONNREFUSED 0.0.0.0:443","stack":"RequestError: connect ECONNREFUSED 0.0.0.0:443\n    at ClientRequest.<anonymous> (/var/lib/ghost/versions/5.33.6/node_modules/got/source/request-as-event-emitter.js:178:14)\n    at Object.onceWrapper (node:events:628:26)\n    at ClientRequest.emit (node:events:525:35)\n    at ClientRequest.origin.emit (/var/lib/ghost/versions/5.33.6/node_modules/@szmarczak/http-timer/source/index.js:37:11)\n    at TLSSocket.socketErrorListener (node:_http_client:494:9)\n    at TLSSocket.emit (node:events:513:28)\n    at emitErrorNT (node:internal/streams/destroy:157:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:122:3)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)"},"msg":"connect ECONNREFUSED 0.0.0.0:443","time":"2023-02-06T19:30:40.660Z","v":0}
```

When I reached out to mailgun about the issue, they told me

> Sending is going to be limited to 100/hour across the entire account, with a max of 10 recipients per batch. This includes CC and BCC recipients, and verifications are disabled. There isn't going to be a way to increase the limit. Once 3-5 of consistent sending history is established, please reply and we will be able to review at that time.
 

They later clarified, they need 

> 3-5 days of consistent sending in order to re-evaluate the account to see if the probationary limit can be lifted.  There would not be a way to pay to have this increased

**Comment by alias-rahil** [comment]
> Email recipient subsets can be chosen but it sometimes still sends to everyone when retrying #16125

[2023-02-22 10:03:32] ERROR status code 420
[2023-02-22 10:03:32] WARN The email service received an error from mailgun and was unable to send.

The email service received an error from mailgun and was unable to send.

"Mailgun Error 420: Domain mg.domain.tld is not allowed to send: recipient limit exceeded, try again after Wed, 22 Feb 2023 10:04:01 UTC"
"https://ghost.org/docs/newsletters/#bulk-email-configuration"

Error ID:
    298f8c80-b298-11ed-975a-39d45aee3345

Error Code: 
    BULK_EMAIL_SEND_FAILED

----------------------------------------

EmailError: The email service received an error from mailgun and was unable to send.
    at Object.send (/var/lib/ghost/versions/5.25.0/core/server/services/bulk-email/bulk-email-processor.js:248:30)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.processEmailBatch (/var/lib/ghost/versions/5.25.0/core/server/services/bulk-email/bulk-email-processor.js:163:34)
    at async Promise.map.concurrency (/var/lib/ghost/versions/5.25.0/core/server/services/bulk-email/bulk-email-processor.js:85:17)

**Comment by alias-rahil** [comment]
I verified the current actual limit using a simple script. It seems to be 9 right now. Here's the relevant code:

```js
import formData from "form-data";
import Mailgun from "mailgun.js";

const domain = process.env.MAILGUN_DOMAIN;
const mailgun = new Mailgun(formData);

const mg = mailgun.client({
  username: "api",
  key: process.env.MAILGUN_API_KEY,
  url: process.env.MAILGUN_BASE_URL,
});

const dummyEmails = [
  "jimfromjax@hotmail.com",
  "terry@townsend-engineering.com",
  "jlee.str@gmail.com",
  "dean.penny@kimley-horn.com",
  "jevelas2@gmail.com",
  "dilmax100@hotmail.com",
  "rcwmspe@gmail.com",
  "acelugo@gmail.com",
  "projects@sitti.net",
  "nbhaggan@gmail.com",
  "felipegonzalez1@comcast.net",
  "ppurisudh@gmail.com",
  "jarichards4336@comcast.net",
  "kapoeltl@gmail.com",
  "briankeiter@hotmail.com",
  "gfr1983@gmail.com",
  "walbertoperez13@gmail.com",
  "ncaronna7@gmail.com",
  "haneynathaniel@gmail.com",
  "alvadavis1@gmail.com",
  "dwilcox.swa@gmail.com",
  "yasuko.dodd@basf.com",
  "yamilina06@gmail.com",
  "aneesh.goly@radise.net",
  "timothy.barry@rsandh.com",
  "saltrick@hotmail.com",
  "kamil_972@hotmail.com",
  "ddaly@groteenterprises.com",
  "jason.webber@kimley-horn.com",
  "alex.g.fortunato@gmail.com",
  "katijecmenica@gmail.com",
  "dingo0202@comcast.net",
  "sk8ertim@gmail.com",
  "jenningsdt@gmail.com",
  "dwoodington@gmail.com",
  "rwall23@gmail.com",
  "mark.ramseur@gmail.com",
];

/**
 * Note(alias-rahil):
 *  1. For N<=9: Executes successfully
 *  2. For N=10: Status is 403, Message is "Domain mg.domain.tld is not allowed to send large batches yet"
 *  3. For N=11: Status is 420, Message is "Domain mg.domain.tld is not allowed to send: recipient limit exceeded, try again after Thu, 23 Feb 2023 07:22:06 UTC"
 */
const N = 10;

const messageData = {
  to: emails.slice(0, N),
  from: `api <noreply@${domain}>`,
  subject: "test",
  text: "test",
  html: "<p>test</p>",
};

await mg.messages.create(domain, messageData);
```

**Comment by benbowler** [comment]
FYI this still occurred for me in 2025. I can see in the code that you get the batch size from the Mailgun API now but my account seemed to be in some kind of new account limited phase and so batches failed to send unless I hard coded the Mailgun response to a batch size of 1.

Then after sending 100 messages an alert was triggered from Mailgun so that I could verify my business with them in order to unblock this. I suppose this is more of a Mailgun issue unless they have an API to detect if an account is in this probation phase and severly limit emails being send until Mailgun can lift this limit.

I imagine most users start from 0 members and build up and the current implementation works for them, however I migrated two established mailing lists from Mailchimp to Ghost and this has been a really painful experience.
