### ISSUE TITLE
Cannot update membership tier descriptions

### ISSUE THREAD

**Issue by ericalli** [TryGhost/Ghost#15740]
### Issue Summary

I can't seem to add/update the description for any membership tiers. Entering a description and then saving clears out whatever value was entered. The database also does not get the updated value either.

https://user-images.githubusercontent.com/13506/199175848-c10bb422-68ff-4622-86c2-1b9ece1ae716.mov

I've tested this with fresh installs of Ghost both locally and on a DO droplet where I host several other Ghost instances. This functionality appears to be working fine on another instance of Ghost running v5.11 but not on the latest version at the time of this report v5.22.1.

### Steps to Reproduce

1. Install a new Ghost instance (v5.22.1)
2. Connect Ghost to Stripe account
3. Add a description to any membership tier
4. Description does not save and no error message is displayed

### Ghost Version

5.22.1

### Node.js Version

14.17.0

### How did you install Ghost?

Locally / Ubuntu 18.04

### Database type

SQLite3

### Relevant log / error output

```shell
No output in error logs
```

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by ErisDS** [comment]
This has been fixed and released. Please update to 5.22.2 :)
