### ISSUE TITLE
Ghost shows unconfigured paid tier with filter="visibility:public+type=paid"

### ISSUE THREAD

**Issue by fueko** [TryGhost/Ghost#15759]
### Issue Summary

Ghost shows an unconfigured paid tier $5/$50 with `filter="visibility:public+type:paid"` and an unconnected Stripe also this tier cannot be removed in the Portal options.

![Zrzut ekranu 2022-11-2 o 20 24 19](https://user-images.githubusercontent.com/23366922/199584171-e1afb2f3-a265-4d8f-bbb1-9373291d75b5.png)

### Steps to Reproduce

Test the setting for `{{#get}}` helper with `filter="visibility:public+type:paid"` without configuring Stripe and it will return a paid tier of $5/$50.

### Ghost Version

5.22.4

### Node.js Version

v16.13.0

### How did you install Ghost?

Tested on localhost and server

### Database type

SQLite3

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by ErisDS** [comment]
Hey @fueko, so sorry for taking such a long time to get back to you on this one!

We agree the API behaviour is a little odd in this case, but from the perspective of creating themes, the best approach is to wrap the get helper in `{{#if @site.paid_members_enabled}}{{/if}}` ([docs here](https://ghost.org/docs/themes/helpers/site/#site-feature-flags)). Using the feature flags for members you have full control over the behaviour of your themes based on the different settings. 

In that regard - if there are any more feature flags that would be useful to help make themes more robust against the ever-expanding membership & newsletter settings, let us know!

I'll leave this open, as it would still probably make sense to change the tiers API to return nothing if paid memberships are not enabled.

**Comment by fueko** [comment]
Thanks very much for the clarifications, @ErisDS. I completely forgot about this helper, thanks!

**Comment by snoseeds** [comment]
Hi @ErisDS, kindly assign this issue to me

**Comment by snoseeds** [comment]
Hi @ErisDS, gentle reminder on this

**Comment by ErisDS** [comment]
@snoseeds A PR would be very welcome. We only assign issues to regular contributors.

**Comment by farhan787** [comment]
@ErisDS, I've opened a PR to fix this, need first time contributor approval to run the PR workflows.
