### ISSUE TITLE
@tryghost/http-stream@^0.1.14 not found 

### ISSUE THREAD

**Issue by niklaspeura** [TryGhost/Ghost#15790]
### Issue Summary

ghost-cli depends on @tryghost/http-stream 0.1.14 which does not exist (latest is 0.1.13)

### Steps to Reproduce

1. run npm install ghost-cli

### Ghost Version

latest

### Node.js Version

14.20.0

### How did you install Ghost?

lightsail bitnami

### Database type

MySQL 8

### Relevant log / error output

```shell
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @tryghost/http-stream@^0.1.14.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of '@tryghost/logging'
npm ERR! notarget
```

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by ErisDS** [comment]
This was due to an error during publishing and has been fixed now.
