### ISSUE TITLE
Upgrading from 5.20.0 to anything after makes all posts (in admin interface) become a 404 page

### ISSUE THREAD

**Issue by sanjay** [TryGhost/Ghost#15806]
### Issue Summary

Whenever I upgrade from 5.20.0 to anything afterwards, all of my posts - published and drafts - are wiped out from the interface.  The page shows a 404 page.  Doing a rollback to 5.20.0 brings everything back.  I've been trying updates as they've been issued but at this point I decided to give up and file a bug report since my issue doesn't seem to be going away.  I started with the self-hosted image of Ghost on Digital Ocean and have been regularly upgrading that over time.

### Steps to Reproduce

1. Upgrade from 5.20.0 to any version after that.
2. Open the Ghost Admin web interface and go to any tab within "Posts"
3. See a 404 page.
4. Be sad the update didn't work and go back and rollback the Ghost version to 5.20.0 and everything is back again.

### Ghost Version

5.20.0

### Node.js Version

14.20.1

### How did you install Ghost?

Linux 4.15.0-194

### Database type

MySQL 5.7

### Browser & OS version

Firefox 106.0.5

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by KazaiMazai** [comment]
It looks like a database issue. You are using MySQL 5.7, but the required version is 8.
I would suggest a complete recover to a functioning snapshot of your instance.
Then updating MySQL to 8.x and only then updating the ghost.

**Comment by sanjay** [comment]
Oh! I didn't realize that requirement was already in place post 5.20.0. My apologies for goofing on that.  I'll try the upgrade and then see if it moves up with me.  Thanks!

**Comment by sanjay** [comment]
Boom!  That was it.  Many thanks @KazaiMazai!
