### ISSUE TITLE
Update from 5.12.0 to 5.22.10. "Add redirects table" migration issue.

### ISSUE THREAD

**Issue by KazaiMazai** [TryGhost/Ghost#15808]
### Issue Summary

Not sure if it's related, but still.

Beforehand, I was having a MySQL 5.7 running with ghost 5.12.0, however without issues. 
Then I updated MySQL to 8.0.31 successfully. 
Ghost was running without any issues.

### Steps to Reproduce

1. Updated ghost from 5.12.0 to 5.22.10 successfully
2. `ghost start` fails with the message log below

### Ghost Version

5.22.10

### Node.js Version

v16.13.0

### How did you install Ghost?

Ubuntu v18.04.1 LTS

### Database type

MySQL 8

### Relevant log / error output

```shell
Debug Information:
    OS: Ubuntu, v18.04.1 LTS
    Node Version: v16.13.0
    Ghost Version: 5.22.10
    Ghost-CLI Version: 1.21.0
    Environment: production
    Command: 'ghost restart'
Message: Ghost was able to start, but errored during boot with: alter table `redirects` add constraint `redirects_post_id_foreign` foreign key (`post_id`) references `posts` (`id`) on delete SET NULL - Referencing column 'post_id' and referenced column 'id' in foreign key constraint 'redirects_post_id_foreign' are incompatible.
Help: Error occurred while executing the following migration: 2022-09-27-13-55-add-redirects-table.js
Suggestion: journalctl -u ghost_kazaimazai-com -n 50
Stack: Error: Ghost was able to start, but errored during boot with: alter table `redirects` add constraint `redirects_post_id_foreign` foreign key (`post_id`) references `posts` (`id`) on delete SET NULL - Referencing column 'post_id' and referenced column 'id' in foreign key constraint 'redirects_post_id_foreign' are incompatible.
    at Server.<anonymous> (/usr/local/lib/node_modules/ghost-cli/lib/utils/port-polling.js:73:28)
    at Object.onceWrapper (node:events:509:28)
    at Server.emit (node:events:390:28)
    at emitCloseNT (node:net:1681:8)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
```

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by ErisDS** [comment]
Please see the docs on [troubleshooting mysql issues](https://ghost.org/docs/faq/troubleshooting-mysql-database/#error-er_cant_create_table-with-_foreign-key-constraint-is-incorrectly-formed_)
