### ISSUE TITLE
Why doesn't the official {{t}} tag be added?

### ISSUE THREAD

**Issue by qsthhm** [TryGhost/Ghost#15811]
### Issue Summary

Every time I upgrade the version, I have to find it manually and then add it, which is very troublesome. So why doesn't the official version have that label? For example, in the member comment area

### Steps to Reproduce

add  {{t}} tag in official version

### Ghost Version

5.22.10

### Node.js Version

8

### How did you install Ghost?

host

### Database type

Other

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by ErisDS** [comment]
Please see https://forum.ghost.org/t/hacktoberfest-project-i18n-for-portal-member-emails-comments-ui-sodosearch/33062
