### ISSUE TITLE
Missing spaces in New Member Signup event on Dashboard->Member Activity

### ISSUE THREAD

**Issue by paulknulst** [TryGhost/Ghost#15838]
### Issue Summary

After a new signup for my newsletter on a self-hosted Ghost blog (version [5.22.10]) the string showing where a new member has signed up is wrong. 

It looks like this:
![image](https://user-images.githubusercontent.com/5755794/202279966-4be5ffc3-cdf8-46a0-913f-d10194b6d387.png)

This is the produced HTML:
```
<span class="gh-members-activity-description feature-memberAttribution">
                                                        <span class="gh-members-activity-event-text">Signed up</span>
                                                            <span class="highlight">Free</span>
                                                            <span class="gh-members-activity-event-join">on</span>
                                                            <a class="ghost-members-activity-object-link" href="https://www.paulsblog.dev/newsletter/" target="_blank" rel="noopener noreferrer">Newsletter</a>
                                                    </span>
```

### Steps to Reproduce

1. Get a new Newsletter signup
2. Switch to Ghost dashboard.
3. Open Member activity

### Ghost Version

5.22.10

### Node.js Version

node:16-bullseye-slim

### How did you install Ghost?

Installed using Docker Container from Docker Hub (latest)

### Database type

MySQL 8

### Browser & OS version

Opera, Firefox, Chrome

### Relevant log / error output

```shell
no log, see screenshot and html
```

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by paulknulst** [comment]
One addition the missing spaces also apply if a user clicks on a link within an article that was sent as an email newsletter.

![image](https://user-images.githubusercontent.com/5755794/202281155-510ff418-cffb-4581-a68f-4f2d33b531cf.png)

**Comment by ErisDS** [comment]
This is fixed in main already here: https://github.com/TryGhost/Ghost/commit/42bf8471420320024b4e5dfcad2a6132b21b1019 and will go out in tomorrow's release.
