### ISSUE TITLE
The mandatory attribute 'height' is missing in tag 'amp-youtube'.

### ISSUE THREAD

**Issue by ribeirogab** [TryGhost/Ghost#15878]
### Issue Summary

After fixing this [issue](https://github.com/TryGhost/Ghost/pull/15826), an error on YouTube videos on AMP pages started to occur.

The error is due to the `amp-youtube` component not having a height attribute, which is mandatory, this ends up invalidating all AMP pages that have this component.

**Error:**
The mandatory attribute `height` is missing in tag `amp-youtube`. [Debug](https://validator.amp.dev/#url=https://tobruxo.com.br/melhores-mangas-yuri/amp/&errno=0). [Learn more](https://amp.dev/documentation/components/amp-youtube).

### Steps to Reproduce

1. Install extension: [AMP Validator](https://chrome.google.com/webstore/detail/amp-validator/nmoffdblmcmgeicmolmhobpoocbbmknc?hl=pt-BR)
2. Create a page/post
3. Add a YouTube video
4. Enter the AMP page
5. Check for error in AMP Validator extension

### Ghost Version

5.23.0

### Node.js Version

16.18.1

### How did you install Ghost?

Digital Ocean Droplet and Ghost Cloud

### Database type

MySQL 8

### Browser & OS version

Google Chrome on Ubuntu 22.04.01

### Relevant log / error output

```shell
The mandatory attribute 'height' is missing in tag 'amp-youtube'.
```

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by KrashTime** [comment]
I have the same problem after the update

**Comment by bumaruf** [comment]
I had some problems with it too :/
