### ISSUE TITLE
Import content unsuccessful

### ISSUE THREAD

**Issue by Sheepeer** [TryGhost/Ghost#15905]
### Issue Summary

summary:
I wanna copy content data from one old version ghost to another new version ghost, but it failed.

result:
I received an email said:
![image](https://user-images.githubusercontent.com/78125933/204757318-402ed335-6121-49d9-a1ce-6201a7d15c98.png)

However, I just succed importing content several weeks ago with version 5.22. But after updating to ghost latest, it failed.

ps: There's no error log in ghost container.

### Steps to Reproduce

1. Export content from my old version ghost
2. Delete all content from my new ghost (version latest)
3. Import content to my new ghost

### Ghost Version

5.23

### Node.js Version

16.13.0

### How did you install Ghost?

from dockerhub

### Database type

MySQL 8

### Browser & OS version

chrome win10

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by Sheepeer** [comment]
anyone could help me ? TAT

**Comment by jiangjiali** [comment]
我记得官方文档里面有的哦。

**Comment by ErisDS** [comment]
Side note - I realised we were no longer outputting errors even in the logs and fixed that. Improvements to the error messages are coming soon. In the meantime, debugging help is better sought on the forum.
