### ISSUE TITLE
Changing asset path in config.json doesn't add ?v= to asset URL

### ISSUE THREAD

**Issue by ivangil-dev** [TryGhost/Ghost#15916]
### Issue Summary

When you specify a file in config.production.json such as portal.js to load directly from a theme or comments-ui.min.js they load without the assetshash function and no ?v= is added after their name so could lead to stale file cache issues and malfunctions

### Steps to Reproduce

Modifying the portal.js path from config.production.json expects getAssetUrl to be called and invokes config.set to set the assetHash

### Ghost Version

5.24.2

### Node.js Version

16.14.1

### How did you install Ghost?

Ubuntu server 22.04, Windows 11 & CentOS 7

### Database type

MySQL 8

### Browser & OS version

Google Chrome v108.0.5359.71 (Build oficial) (64 bits)

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by ErisDS** [comment]
He there @ivangil-dev, could you provide a reproduction case please? 
It sounds like a bug but your reproduction case doesn't make sense to me as it's talking about how the code works?

**Comment by ivangil-dev** [comment]
In a self-hosted solution we have set the loading of portal.min.js to the theme path
```
  "portal": {
    "url": "https://omniscientia.es/assets/built/portal.min.js"
  }
```
Then the theme contains the **portal.min.js** file in the path **/assets/built/** and the file is injected into ```{{ ghost_head }}```successfully.

The problem is that when the file is inserted it does so in the following way:
```"https://omniscientia.es/assets/built/portal.min.js"``` and should be ```https://omniscientia.es/assets/built/portal.min.js?v=XXXXXXXXXX"```

![portal min](https://user-images.githubusercontent.com/10148051/208406570-09ceb907-41d4-4167-a8dd-9145606bf1f7.png)


By not adding a version when loading the resource, if we make changes to **portal.min.js** these are not applied since the client already has the file saved in the browser's cache or memory.

![carga  portal min](https://user-images.githubusercontent.com/10148051/208407489-3567b006-09bf-4a50-b140-c2273eca3be4.png)

The same thing happens if we alter the "comments-ui" path: 
```
{
    "url": "https://omniscientia.es/assets/built/comments-ui.min.js"
}
```

I apologize for my english...
