### ISSUE TITLE
`EACCES: permission denied, mkdir '/tmp/root/if-you-need-to-delete-this-open-an-issue-async-disk-cache/` when upgrading ghost

### ISSUE THREAD

**Issue by eauchat** [TryGhost/Ghost#15911]
### Issue Summary

I'm trying to upgrade a website from ghost 5.8.3 to 5.20.0 but the process fails with the logs shown below.
The server is running multiple ghost websites, and the directory `/tmp/root/if-you-need-to-delete-this-open-an-issue-async-disk-cache/` has the following permissions and users: `drwxr-xr-x ghost__4 ghost__4`.
The site I'm trying to upgrade belongs to a different user, hence the permission denial issue.
I'm wondering why `async-disk-cache` is identifying the user to be `root` and not `ghost__3`, and therefore is trying to access to a directory that is used by other ghost websites on the server, this creating a mess and this permission issue.

I'm not 100% sure the bug is coming from ghost itself. It may come from [async-disk-cache](https://github.com/stefanpenner/async-disk-cache), or from the way the yunohost package is relating to it. But I thought it'd be good in any case to report here to keep track of the issue in case people have similar problems.

### Steps to Reproduce

Install multiple ghost websites with yunohost package [ghost_ynh](https://github.com/YunoHost-Apps/ghost_ynh/).
Try to upgrade one of them. 

### Ghost Version

5.8.3

### Node.js Version

16.18.1

### How did you install Ghost?

With yunohost package [ghost_ynh](https://github.com/YunoHost-Apps/ghost_ynh/)

### Database type

Other

### Relevant log / error output

```shell
Build Error (broccoli-persistent-filter:Babel > [Babel: @ember/test-helpers]) in @ember/test-helpers/-internal/build-registry.js
EACCES: permission denied, mkdir '/tmp/root/if-you-need-to-delete-this-open-an-issue-async-disk-cache/28ddc1335da8019171c513606ea4cd358c2289e3'
```

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by ErisDS** [comment]
Sorry for the slow response. These errors are not coming from Ghost itself. Seems like this definitely an issue very specific to your setup with yuno host, as I think you've found from the issues you've raised and has more response to on the other repos.
