### ISSUE TITLE
ghost version check

### ISSUE THREAD

**Issue by jostreff** [TryGhost/Ghost#15925]
### Issue Summary

<img width="525" alt="image" src="https://user-images.githubusercontent.com/14915659/205340741-113805f3-54bc-4d7b-b8c3-f52ee43bb6fc.png">

### Steps to Reproduce

1. ghost update
2. restart process
browse ghost about via GUI

### Ghost Version

5.25.0

### Node.js Version

v16.18.1

### How did you install Ghost?

via ghost-cli

### Database type

MySQL 8

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by neerajkrbansal1996** [comment]
Hi @ErisDS ,

I would love to take this ticket!

**Comment by ErisDS** [comment]
I'm not able to reproduce this issue. @jostreff are you seeing the same if you update again now?

@neerajkrbansal1996 if you are able to repro, feel free to submit a PR.
