### ISSUE TITLE
cancel_at_period_end should be `true` for complimentary subscriptions

### ISSUE THREAD

**Issue by rosano** [TryGhost/Ghost#15933]
### Issue Summary

In my theme, it seems like `cancel_at_period_end` returns false when the member is comped, so my 'renews' text shows instead of 'expires' even though it's shows as 'expires' in the Ghost built-in views.

### Steps to Reproduce

```
{{#foreach @member.subscriptions}}
	{{#if cancel_at_period_end}}
		expires
	{{else}}
		renews
	{{/if}}
{{/foreach}}
```

### Ghost Version

5.25.0

### Node.js Version

?

### How did you install Ghost?

Cloudron

### Database type

MySQL 8

### Browser & OS version

Firefox latest, macOS catalina

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by ErisDS** [comment]
This needs a bit of a deeper review to see what fields we're using to calculate this on the internal screens and whether they are or should be exposed to themes.

Will take a look, but it won't be until after the new year.
