### ISSUE TITLE
`latest` tag on NPM is not updated for @tryghost/portal

### ISSUE THREAD

**Issue by mmiszy** [TryGhost/Ghost#15931]
https://unpkg.com/@tryghost/portal@latest/umd/portal.min.js still points to an outdated version – 2.13.2 – but it should to 2.21.0.

The problem is that the `latest` tag has not been updated after a few last releases – NPM also shows outdated version:

<img width="389" alt="Screenshot 2022-12-13 at 13 10 57" src="https://user-images.githubusercontent.com/1338731/207314549-62ea365e-1718-408c-a1d7-d1363ae95473.png">

<img width="775" alt="Screenshot 2022-12-13 at 13 11 21" src="https://user-images.githubusercontent.com/1338731/207314620-f1bb1612-9837-49d2-a34d-e41c339106d2.png">

<details>
  <summary>Original (incorrect) issue</summary>

### Issue Summary

When a request to `members/api/create-stripe-checkout-session/` is made, the response is an object with a single field: `{url: "…"}`. Yet, some functions do not handled that well. For example, it's correctly handled here:
https://github.com/TryGhost/Ghost/blob/74d0fee1259476cd29962ecae2181c7e13b3932b/ghost/portal/src/utils/api.js#L385-L387
but not here:
https://github.com/TryGhost/Ghost/blob/74d0fee1259476cd29962ecae2181c7e13b3932b/ghost/portal/src/utils/api.js#L432

### Steps to Reproduce
1. Go to https://news.typeofweb.com
2. Scroll down a bit
3. Click on the blue floating "Subskrybuj" button in the bottom right corner.
4. Continue with a paid subscription PLN 5/month
5. See error in the console.
6. Inspect network tab and notice that the endpoint returned `{url}` instead of `{publicKey}`

### Ghost Version

74d0fee1259476cd29962ecae2181c7e13b3932b

### Node.js Version

irrelevant

### How did you install Ghost?

irrelevant

### Database type

MySQL 5.7

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

</details>

**Comment by ErisDS** [comment]
@mmiszy can you please update this to include reproduction steps for the bug?

I realise you’ve proposed a fix but that also doesn’t include tests, so whilst I’m sure it’s valid it is not possible for us to verify what problem there is that is being solved.

**Comment by mmiszy** [comment]
@ErisDS it's the same problem that was solved here: https://github.com/TryGhost/Ghost/commit/4f54cbc37a5328d80ddd4a7c88b3a2ac1aa6c8ee
It's just that some spots were not updated.

**Comment by mmiszy** [comment]
Added steps to reproduce on my live website. Hope that helps!

**Comment by allouis** [comment]
Could you give steps to reproduce on a local install?

**Comment by mmiszy** [comment]
No, I'm afraid I can't.
But I don't quite understand the problem here - it's exactly the bug that was partially fixed ere https://github.com/TryGhost/Ghost/commit/4f54cbc37a5328d80ddd4a7c88b3a2ac1aa6c8ee - just some spots were not updated. It's the same endpoint being called but the expected response is still a public key instead of an URL.

Do you have a trouble reproducing it @allouis ?

**Comment by allouis** [comment]
@mmiszy I can't reproduce this and your PR adds handling for the `url` property of the response from a different endpoint to the one mentioned in this issue.

`npm install -g ghost && ghost install local` is a quick way to get a local ghost install up an running if you do find time to give reproduction steps.

**Comment by mmiszy** [comment]
I'm so sorry – I was wrong.
The issue is that Found https://unpkg.com/@tryghost/portal@latest/umd/portal.min.js still points to an outdated version – 2.13.2 – but it should to 2.21.0.
The problem is that the `latest` tag has not been updated after a few last releases – NPM also shows outdated version:

<img width="389" alt="Screenshot 2022-12-13 at 13 10 57" src="https://user-images.githubusercontent.com/1338731/207314549-62ea365e-1718-408c-a1d7-d1363ae95473.png">

<img width="775" alt="Screenshot 2022-12-13 at 13 11 21" src="https://user-images.githubusercontent.com/1338731/207314620-f1bb1612-9837-49d2-a34d-e41c339106d2.png">

**Comment by allouis** [comment]
Oooph - good catch, that makes sense why I couldn't reproduce! 

Have you updated your config to set the portal URL manually? It should be using the jsDelivr CDN with a version, rather than latest - https://github.com/TryGhost/Ghost/blob/main/ghost/core/core/shared/config/defaults.json#L162-L165

Hoping that fixing your config can get your site working so you're not blocked on this issue

**Comment by mmiszy** [comment]
Yes, I've pinned it to a specific version.
