### ISSUE TITLE
Updating Ghost from v5.18.0 to v5.25.2 failed on "ALTER table `subscriptions` ADD constraint [...]"

### ISSUE THREAD

**Issue by sylvainreiter** [TryGhost/Ghost#15955]
### Issue Summary

Updating Ghost from v5.18.0 to v5.25.2 failed with the following error

_Ghost was able to start, but errored during boot with: alter table `subscriptions` add constraint `subscriptions_member_id_foreign` foreign key (`member_id`) references `members` (`id`) on delete CASCADE - Referencing column 'member_id' and referenced column 'id' in foreign key constraint 'subscriptions_member_id_foreign' are incompatible._

### Steps to Reproduce

Run "ghost update" in cli from v5.18.0

### Ghost Version

5.25.2

### Node.js Version

14.21.1

### How did you install Ghost?

cli on DigitalOcean

### Database type

MySQL 8

### Relevant log / error output

```shell
✔ Fetched release notes
✔ Downloading and updating Ghost to v5.25.2
+ sudo systemctl stop ghost_domain
✔ Stopping Ghost
✔ Linking latest Ghost and recording versions
+ sudo systemctl start ghost_domain
+ sudo systemctl stop ghost_domain
✖ Restarting Ghost
A GhostError occurred.

Message: Ghost was able to start, but errored during boot with: alter table `subscriptions` add constraint `subscriptions_member_id_foreign` foreign key (`member_id`) references `members` (`id`) on delete CASCADE - Referencing column 'member_id' and referenced column 'id' in foreign key constraint 'subscriptions_member_id_foreign' are incompatible.
Help: Error occurred while executing the following migration: 2022-10-10-06-58-add-subscriptions-table.js
Suggestion: journalctl -u ghost_domain -n 50

Debug Information:
    OS: Ubuntu, v18.04.6 LTS
    Node Version: v14.21.1
    Ghost Version: 5.25.2
    Ghost-CLI Version: 1.23.1
    Environment: production
    Command: 'ghost update'

Additional log info available in: /home/ghost-mgr/.ghost/logs/ghost-cli-debug-2022-12-07T10_04_19_708Z.log

Try running ghost doctor to check your system for known issues.

You can always refer to https://ghost.org/docs/ghost-cli/ for troubleshooting.
```

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by DLukovkin** [comment]
Exactly the same problem when upgrading from 5.18 to 5.25.3. Mysql 8 (recently updated from 5.7) | Ubuntu 18.04.1 LTS
```
Message: Ghost was able to start, but errored during boot with: alter table `subscriptions` add constraint `subscriptions_member_id_foreign` foreign key (`member_id`) references `members` (`id`) on delete CASCADE - Referencing column 'member_id' and referenced column 'id' in foreign key constraint 'subscriptions_member_id_foreign' are incompatible.
Help: Error occurred while executing the following migration: 2022-10-10-06-58-add-subscriptions-table.js
```
I suspect the problem is with mysql settings. The update was performed according to the instructions from [https://ghost.org/docs/faq/supported-databases/](url)
But this command doesn't work for me:
mysql <database> -u <username> -p 'set foreign_key_checks=0; <ALTER TABLE COMMANDS> set foreign_key_checks=1;'
Any ideas?

**Comment by DLukovkin** [comment]
Resolved for me! The problem is that the old ```TABLE_COLLATION``` value is left in the database. It was default for mysql 5.7 - ```utf8mb4_general_ci```, which is different from the default for mysql 8 - ```utf8mb4_0900_ai_ci```.
Executed a view query for all tables:
```
set foreign_key_checks=0;
alter table api_keys convert to character set utf8mb4 collate utf8mb4_0900_ai_ci;
...
set foreign_key_checks=1;
```
And the update was successful!

**Comment by ErisDS** [comment]
This sounds like an issue with collation in the database. See:
https://ghost.org/docs/faq/troubleshooting-mysql-database/#error-er_cant_create_table-with-_foreign-key-constraint-is-incorrectly-formed_
https://ghost.org/docs/faq/supported-databases/#how-to-update-mysql-5-to-mysql-8

Root cause may be https://github.com/TryGhost/Ghost-CLI/issues/1718
