### ISSUE TITLE
Ghost as a user doesn't work if admin url is not accessible

### ISSUE THREAD

**Issue by brunoais** [TryGhost/Ghost#15978]
### Issue Summary

If I setup the URL to a publicly accessible domain and I set the admin url to a privately accessible domain, all javascript in ghost doesn't run due to inaccessible destination.

### Steps to Reproduce

1. Setup ghost with the following env vars
    ```
    export url="https://my-public.domain.com"
    export admin__url="http://10.2.6.1:2368"
    ```
2. Access using `admin__url` to setup ghost.
3. Disconnect from private network (disconnect VPN or connect to different network)
4. Access https://my-public.domain.com
5. Access to API is denied by the browser due to CSP
    ![image](https://user-images.githubusercontent.com/639467/206720032-ea6551d6-9a9a-4ebf-8f7f-f6b64df90127.png)
    However, if I try to access the correct URL, I get status 404
    ![image](https://user-images.githubusercontent.com/639467/206721887-eaa0e956-c2bd-4b5c-819f-5a441b8ce5b8.png)

### Ghost Version

5.25.0

### Node.js Version

16.18.1

### How did you install Ghost?

Docker container with ghost and a few tweaks

### Database type

SQLite3

### Browser & OS version

firefox 107

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by ErisDS** [comment]
Ghost's API lives on the admin domain. If you're using dynamic features like members, you'll need the API to be accessible and loaded over HTTPS. This is expected behaviour.

**Comment by brunoais** [comment]
@ErisDS That information is not specified here:
![image](https://user-images.githubusercontent.com/639467/208234992-3d8b4c96-cfd0-4f3a-a34c-7cce9180849e.png)
https://ghost.org/docs/config/#admin-url
There's no warning that the non-administrative API ghost needs is included in the admin URL and that the admin URL must be publicly accessible.

Additionally, it states:

> Admin can be used to specify a different protocol for your admin panel

In practice, this is not true due to `CSP`. If I specify an HTTPS protocol for ghost and an HTTP protocol for the admin, CSP that ghost sets leads the browser to reject the HTTP URLs. Even if there wasn't CSP, nowadays browsers reject downgrading from HTTPS to HTTP for everything except images (mixed-content).


How do I make a change request so the website API lives in the website URL and admin API lives in the admin URL (Ofc both in the path `/ghost/api`)
