### ISSUE TITLE
post url 404 after publishing

### ISSUE THREAD

**Issue by Sheepeer** [TryGhost/Ghost#15984]
### Issue Summary

After publishing a new post and clicking the card of published post, it ran into 404
![image](https://user-images.githubusercontent.com/78125933/207013044-c91e12ef-d41f-4449-bc8f-64012a31db39.png)
![image](https://user-images.githubusercontent.com/78125933/207013124-c19ab304-109b-4270-ae27-2fb77c142956.png)

Then I refresh the page, the post occurred. 
![image](https://user-images.githubusercontent.com/78125933/207013411-f72a5c25-0616-4eed-b176-2f21cb905393.png)

But!!! when I refresh the page again, it run into 404 again too! 
![image](https://user-images.githubusercontent.com/78125933/207013468-42b834b1-c744-401e-b4e0-5a809173186f.png)

My site is self hosted with ghost, and to explore this issue, I did some test and found that the issue only comes out when using nginx, but I have no idea why yet.

### Steps to Reproduce

1. install ghost image by docker
2. deploy ghost with k8s and use nginx ro do proxying
3. enter background and publish a new post
4. click the post's card and there is 404

### Ghost Version

5.22

### Node.js Version

16.13.0

### How did you install Ghost?

from dockerhub

### Database type

MySQL 8

### Browser & OS version

chrome win10

### Relevant log / error output

```shell
nginx logs when 404：
clicking post's card after publishing:
"GET /post-title-1/ HTTP/1.1" 404 2245 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36”
refresh the post's page:
"GET /post-title-1/ HTTP/1.1" 404 2245 "http://10.224.149.94/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
```

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by Sheepeer** [comment]
I found that 404 shows is because I’m using k8s development with several pods. When the pod used to fetch new post is the same with the one used to publish the new post, 200 returned; otherwise there will be 404.

I still don't known why the pods don't return the same result. Is there any reason with ghost's api or cache?

**Comment by ErisDS** [comment]
Sounds like you need to read this: https://ghost.org/docs/faq/clustering-sharding-multi-server/

**Comment by Sheepeer** [comment]
> Sounds like you need to read this: https://ghost.org/docs/faq/clustering-sharding-multi-server/

Soooo many thx !!! And could U please tell why multi-server is not supposed? Is this because the frontstage pages generated with handlebars are cached and will be update only after posts change (.e.g, publish a new post)?  

I looked at the log of mysql, when I refresh the home page, there will be a sql to select posts. But in my thought if there is a cache, this sql log won't be there. I'm confused and eager the explaination :)
