### ISSUE TITLE
RSS or Atom Feed Support

### ISSUE THREAD

**Issue by kidehen** [TryGhost/Ghost#15988]
### Issue Summary

I don't see support for content syndication using RSS or Atom. This is a feature of Wordpress and many other alternatives.

### Steps to Reproduce

1. Open and Ghost page
2. Look for RSS or Atom feed

### Ghost Version

Any

### Node.js Version

Any

### How did you install Ghost?

Manually

### Database type

MySQL 5.7

### Browser & OS version

Any

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by ErisDS** [comment]
Ghost has always had RSS feed support, including feeds for index, tags, authors and even private feeds for members. 

<img width="712" alt="image" src="https://user-images.githubusercontent.com/101513/208202101-e1b802ac-a887-474c-9a74-58de4619d5f5.png">

**Comment by kidehen** [comment]
I can see now that RSS is supported. 

I looked in the wrong place initially.

https://careerhackers.com/?ref=ghost-explore  -- and others do actually demonstrate RSS support.
