### ISSUE TITLE
Schema.org metadata only includes primary author

### ISSUE THREAD

**Issue by mfenner** [TryGhost/Ghost#16001]
### Issue Summary

The schema.org metadata in JSON-LD only shows the primary author. For multi-author posts that means that author information is missing even though multiple authors are shown elsewhere.

### Steps to Reproduce

On a recent Ghost version (I use Ghost Pro) look at the schema.org of a post with multiple authors (either in the page source or with a browser plugin).

### Ghost Version

5.25.3

### Node.js Version

16

### How did you install Ghost?

Ghost Pro

### Database type

MySQL 8

### Browser & OS version

Chrome 108 (arm64)

### Relevant log / error output

```shell
n/a
```

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by ErisDS** [comment]
What was it that you were expecting to see? References for how to handle this correctly in Schema.org would be great.

**Comment by mfenner** [comment]
I expected to see all authors I added in the Ghost editor to show up in the schema.org markup, just as they do in the Ghost API. Basically generating the schema.org from authors (which can be one or more JSON objects) instead of generating the schema.org from the primary author. I can do a pull request if that helps.

**Comment by mfenner** [comment]
I left a comment a while ago that described the issue. I will make a pull request to clarify what needs to be done, maybe that is easier.
