### ISSUE TITLE
alter table error while attempting to upgrade to v5.25.5

### ISSUE THREAD

**Issue by 84adam** [TryGhost/Ghost#16020]
### Issue Summary

A GhostError occurred during the update process from v5.3.1 to v5.25.5. Had to revert back as a result.

### Steps to Reproduce

ghost backup
ghost update

### Ghost Version

v5.25.5

### Node.js Version

v16.15.1

### How did you install Ghost?

Ubuntu, v20.04.5 LTS

### Database type

MySQL 8

### Relevant log / error output

```shell
Message: Ghost was able to start, but errored during boot with: alter table `members_created_events` add constraint `members_created_events_member_id_foreign` foreign key (`member_id`) references `members` (`id`) on delete CASCADE

Referencing column 'member_id' and referenced column 'id' in foreign key constraint 'members_created_events_member_id_foreign' are incompatible.

Help: Error occurred while executing the following migration: 2022-<DATE-TIME>-add-member-created-events-table.js

Debug Information:
    OS: Ubuntu, v20.04.5 LTS
    Node Version: v16.15.1
    Ghost Version: 5.25.5
    Ghost-CLI Version: 1.23.1
    Environment: production
    Command: 'ghost update'
```

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by improvethings** [comment]
I am having the same issue after an upgrade from ghost 3 which included moving from MariaDB to MySQL 8.

Ubuntu 22.04.1 LTS
node v14.21.1
Ghost-CLI version: 1.23.1
Ghost version: 5.25.5

mysql> SHOW COLUMNS FROM members_status_events WHERE Field = 'member_id';
+-----------+-------------+------+-----+---------+-------+
| Field     | Type        | Null | Key | Default | Extra |
+-----------+-------------+------+-----+---------+-------+
| member_id | varchar(24) | NO   |     | NULL    |       |
+-----------+-------------+------+-----+---------+-------+
1 row in set (0,87 sec)

mysql> SHOW COLUMNS FROM members WHERE Field = 'id';
+-------+-------------+------+-----+---------+-------+
| Field | Type        | Null | Key | Default | Extra |
+-------+-------------+------+-----+---------+-------+
| id    | varchar(24) | NO   | PRI | NULL    |       |
+-------+-------------+------+-----+---------+-------+

**Comment by ErisDS** [comment]
This sounds like an issue with collation in the database. See:
https://ghost.org/docs/faq/troubleshooting-mysql-database/#error-er_cant_create_table-with-_foreign-key-constraint-is-incorrectly-formed_
https://ghost.org/docs/faq/supported-databases/#how-to-update-mysql-5-to-mysql-8

Root cause may be https://github.com/TryGhost/Ghost-CLI/issues/1718

**Comment by 84adam** [comment]
I am not upgrading from MySQL 5 to MySQL 8. I already have 8. Maybe this is not specific to my environment.

> "there is a disparity between what the CLI does and what the documentation suggests"

**Comment by improvethings** [comment]
row_format is Dynamic for all via `show table status;`
'show variables like '%collation_connection%';` shows "utf8mb4_0900_ai_ci"

**Comment by improvethings** [comment]
Considering neither of us with the same error are coming from MySQL 5, I would appreciate if this was re-opened, it seems to be a ghost-cli migration during upgrade issue. I'm upgrading from MariaDB 10 while 84adam is already on MySQL 8. I was upgrading from ghost 3.42.9 and he was upgrading from v5.3.1.
