### ISSUE TITLE
Jenkins Setup

### ISSUE THREAD

**Issue by jgillich** [TryGhost/Ghost#1603]
This is a follow-up to TryGhost/Ghost-Config#8 where the idea came up that we could set up a instance of [Jenkins](http://jenkins-ci.org/) to do various things:

* Automatic building of RPM packages
* Automatic building & upload of release ZIP's
* Run tests on more platforms (Windows, OS X, FreeBSD etc - Travis runs on Ubuntu 12.04)
* Build docs from the code
* ...

I could host either a build slave or the entire Jenkins setup. My box runs FreeBSD and has plenty of RAM and disk space, but a rather shitty internet connection (16mbit down, 1mbit up).

**Comment by ErisDS** [comment]
Closing this as it has never had traction, and if we do want to do non-travis builds we would likely do them with some other CI solution than Jenkins.
