### ISSUE TITLE
Last-modified response header is not present

### ISSUE THREAD

**Issue by adityapatadia** [TryGhost/Ghost#16045]
### Issue Summary

Last-modified response header should be set for effective cache validation. The header is currently not set.

### Steps to Reproduce

Check response header from Ghost for an article. Last-modified header will be absent.

### Ghost Version

5.24

### Node.js Version

16

### How did you install Ghost?

Kubernets

### Database type

MySQL 8

### Browser & OS version

Chrome 108 - Macos

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by ErisDS** [comment]
I've marked this as a feature request as in 10 years of working with Ghost + caching I've not come across a need for this header.
