### ISSUE TITLE
Overrides not recognized until custom partial is used

### ISSUE THREAD

**Issue by PatrickGotthard** [TryGhost/Ghost#16040]
### Issue Summary

According to the documentation under https://ghost.org/docs/themes/helpers/navigation/#changing-the-template and https://ghost.org/docs/themes/helpers/pagination/#default-template I wanted to customize the navigation and pagination of my first theme.

Unfortunately that didn't work until I added a custom partial to my theme. Here's a forum post from last year describing the exact same problem: https://forum.ghost.org/t/trouble-getting-navigation-hbs-to-get-recognized/24656

### Steps to Reproduce

1. Create a partial for pagination and/or navigation and make sure no other custom partials are used in your template --> pagination and navigation templates are not recognized
2. Create a custom partial and include it in the template that uses a pagination or navigation --> pagination and navigation template should be recognized

### Ghost Version

5.26.1

### Node.js Version

16.19.0

### How did you install Ghost?

Docker Hub / ghost:5

### Database type

SQLite3

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by ErisDS** [comment]
Hey there, thank you so much for the detailed bug report.

That does look like something that shouldn't happen! A PR to fix this issue would be very welcome 🙂

**Comment by monkeysees** [comment]
I accidentally submitted issue https://github.com/TryGhost/Ghost/issues/16334 about the same problem.
I’m reposting my codebase investigation contained in case someone finds it useful.

1. Navigation helper produces `navigation` template:
https://github.com/TryGhost/Ghost/blob/9f3d8ec67dac95fd4e67834c483ba042e6ce836e/ghost/core/core/frontend/helpers/navigation.js#L89
2. Template is returned by Handlebars service:
https://github.com/TryGhost/Ghost/blob/9f3d8ec67dac95fd4e67834c483ba042e6ce836e/ghost/core/core/frontend/services/handlebars.js#L17
3. Which uses theme engine to find (and then return) partial:
https://github.com/TryGhost/Ghost/blob/9f3d8ec67dac95fd4e67834c483ba042e6ce836e/ghost/core/core/frontend/services/theme-engine/handlebars/template.js#L15
4. Partials are set in the engine when it is being configured with partials path passed:
https://github.com/TryGhost/Ghost/blob/9f3d8ec67dac95fd4e67834c483ba042e6ce836e/ghost/core/core/frontend/services/theme-engine/engine.js#L12
5. Engine is configured when we active theme is being set:
https://github.com/TryGhost/Ghost/blob/9f3d8ec67dac95fd4e67834c483ba042e6ce836e/ghost/core/core/frontend/services/theme-engine/active.js#L115
6. Active theme returns partials path when it knows about at least one partial:
https://github.com/TryGhost/Ghost/blob/9f3d8ec67dac95fd4e67834c483ba042e6ce836e/ghost/core/core/frontend/services/theme-engine/active.js#L71
7. Active theme learns about partials from a [GScan](https://github.com/TryGhost/gscan) check:
https://github.com/TryGhost/Ghost/blob/9f3d8ec67dac95fd4e67834c483ba042e6ce836e/ghost/core/core/frontend/services/theme-engine/active.js#L44
8. GScan returns only those partials that are used by other templates:
https://github.com/TryGhost/gscan/blob/3642f519f832cfa744f27074300e1cf9563281c5/lib/checks/005-template-compile.js#L38

**Comment by monkeysees** [comment]
@ErisDS I can work on a PR. As I understand it, this problem should be fixed in the [GScan template processor](https://github.com/TryGhost/gscan/blob/3642f519f832cfa744f27074300e1cf9563281c5/lib/checks/005-template-compile.js#L38)? Should I create an issue in the GScan repo?

**Comment by kingspride** [comment]
I'd like to reopen this since the latest version 5.79.1 still has this bug.

I was wondering why my `navigation.hbs` is not working, but then I discovered this issue and "solved" like so:

I could create an empty `dummy.hbs` partial and load that before `{{navigation}}` in default.hbs, to force ghost to actually use my custom` navigation.hbs`.

**Comment by puresick** [comment]
I would like to reopen this issue again aswell. I stumbled across this bug while trying to customize the pagination helper. I added `partials/pagination.hbs` but it was not recognized until I did the trick @kingspride describes above by adding a `dummy.hbs`.

**Comment by izcream** [comment]
This happens to me on ghost 5.87.2 too. Workaround solution from @kingspride still work😅
