### ISSUE TITLE
Time to read for Persian articles not processed

### ISSUE THREAD

**Issue by Savy97** [TryGhost/Ghost#16046]
### Issue Summary

I am using Ghost in the Persian language for my blog. When I wrote the article, no matter how many characters it contained (1500 words), the time to read for that was 1 min!

### Steps to Reproduce

adding a blog in Persian language (1500 words)
clicking on the preview button
the written time for reading this article is 1 min!

### Ghost Version

5.26.3

### Node.js Version

16

### How did you install Ghost?

by ghost cli

### Database type

MySQL 8

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by ErisDS** [comment]
Hey there, thank you so much for the detailed bug report.

That does look like something that shouldn't happen! A PR to fix this issue would be very welcome 🙂

**Comment by prajwal0024** [comment]
@ErisDS can I give this a try?

**Comment by daniellockyer** [comment]
@prajwal0024 You're more than welcome to submit a PR for this 🙂
