### ISSUE TITLE
Contradicting nodejs requirements during install

### ISSUE THREAD

**Issue by rico666** [TryGhost/Ghost#16051]
### Issue Summary

Ubuntu Server 22, trying to install Ghost 5.x "by the book" a.k.a. https://ghost.org/docs/install/ubuntu/

First "ghost install" fails with the words:

Ghost v5.26.4 is not compatible with the current Node version. Your node version is 12.22.9, but Ghost v5.26.4 requires ^14.17.0 || ^16.13.0 || ^18.0.0

Now  I am not sure what "^" is supposed to mean in that formalism, hopefully not "NOT" or "XOR", but maybe ^x means "x or higher"

So I go and install node 18-something after going through some hoops removing the system 12.x nodejs, 

the second "ghost install" fails with

Message: The version of Node.js you are using is not supported.
Supported: ^12.22.1 || ^14.17.0 || ^16.13.0
Installed: 18.12.1

Which is the precise moment I write this issue, because let's be honest: 

<meme>
👌 One does not simply install Ghost.
</meme>

First, it claims that 12.22.9 was not enough and that 14,16 or 18 is required
Then, it claims that 18 is not supported but  12,14 or 16 is. 

Yeah, I will manage. Will try nodejs 16, but you know...

### Steps to Reproduce

1. Run Ghost 3.3x, in Debian LXC, update it all the way up to 4.x only to find out 5.x will not work because Mysql 8
2. Install Ubuntu Server 22 and go by https://ghost.org/docs/install/ubuntu/
3. Find out ghost 5.26 does not like nodejs 12 which is Ubuntu Server 22 standardm instead it wants 14,16 or 18
4. Ditch that documentation, because nodejs
5. go with https://askubuntu.com/questions/426750/how-can-i-update-my-nodejs-to-the-latest-version and install nodejs 18
6. find out that ghost made fun of you and 18 is not supported either
7. write github issue
8. probably install nodejs 16
9. probably profit

### Ghost Version

5.26.x

### Node.js Version

12.22.9 and 18.12.1

### How did you install Ghost?

Ubuntu Server 22

### Database type

MySQL 8

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by rico666** [comment]
And just a short feedback that nodejs 16 did work.

**Comment by ErisDS** [comment]
Apologies, this was due to a failed publish of Ghost-CLI when I updated both to support node 18... so Ghost and Ghost-CLI are giving conflicting errors.

The updated version of Ghost-CLI has been properly published now, so if you update this shouldn't happen again.
