### ISSUE TITLE
Ghost appears to redundantly create Stripe Customer objects via API

### ISSUE THREAD

**Issue by patio11** [TryGhost/Ghost#16057]
### Issue Summary

While this isn't high impact, it appears that checkouts initiated in Ghost to create new subscriptions will redundantly create customer objects in Stripe, with one copy having only a name/email address and the other copy having the actual subscription inside of it. This will pollute search results and make customer counts inaccurate.

Note here, for example, how the count of new customers is almost 2X the count of new successful payments.

<img width="680" alt="スクリーンショット 2023-01-03 10 25 20" src="https://user-images.githubusercontent.com/32929/210289537-65d2f069-15b2-43af-bfcf-2f6db9e714c1.png">

I believe I've figured out what is happening via Ghost's invocation of Stripe APIs. Here's what the history of API calls looks like for a single new subscriber:

<img width="561" alt="スクリーンショット 2023-01-03 10 17 43" src="https://user-images.githubusercontent.com/32929/210289211-f6eacd83-a02b-458c-88bb-fad8ced723ca.png">

We see Ghost pre-creating a Customer object prior to creating a Checkout session, which is one valid way to do it. However, the call to create the checkout session (POST /v1/checkout/sessions) does not reference the created Customer object. This results in Stripe creating a second Customer "at need", per the description [here](https://stripe.com/docs/api/checkout/sessions/create)

> customer: ... If blank for Checkout Sessions in payment or subscription mode, Checkout will create a new Customer object based on information provided during the payment flow.

The fix is simple, I think: cause the /v1/checkout/sessions POST API call to contain the customer ID, which will look something like cust_... , in the request.

There's some cleanup which could be done relatively trivially by Ghost on users' behalf, or in the alternative, you could release a snippet for users to query their Stripe API, search for the empty customers that duplicate live customers, and delete the empties. (I might write a script for this.)

### Steps to Reproduce

I think this should be observable for any Ghost instance making new subscriptions against Stripe.

1. Connect Ghost to Stripe.
2. Start a new paid subscription using a new email address.
3. Wait a few seconds for bookkeeping to happen.
4. Check the associated Stripe account; you will likely see two new customer objects, one with only the name/email and the other with the name/email and associated subscription/payment method/etc.

### Ghost Version

Current version via Ghost Pro hosting

### Node.js Version

Current version via Ghost Pro hosting

### How did you install Ghost?

Current version via Ghost Pro hosting

### Database type

MySQL 5.7

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by patio11** [comment]
I'm still fighting my local JS environment to test the above code against the Stripe test environment to verify it actually fixes the issue, though I think from perusal of the code it likely will. Feel free to run with it or wait for me to get to it; it might take a day or two.

**Comment by ErisDS** [comment]
Hey @patio11 thanks for the detailed bug report and the WIP fix. @allouis would be happy to work with you to get the fix over the line 🙂

**Comment by patio11** [comment]
@ErisDS Thanks much! It turned out that I did need to do the manual testing, as the Stripe API did not like when I specified a customer object and customer email in the same Checkout session creation request. I've fixed this issue.

@allouis I believe the above PR should work.
