### ISSUE TITLE
Native Search partially works on Private Posts

### ISSUE THREAD

**Issue by javierencalada** [TryGhost/Ghost#16067]
### Issue Summary

Hello!

Today i received a issue request from a customer and after some tests, i found the Native Search just search on Titles if you have just member articles.

The optimal solution would be to search entirely in the Article (title + content) even if is private, but at least should search in the excerpt if is manually assigned.

Thank you very much!

### Steps to Reproduce

1. Create a member Article.
2. Add manually a excerpt.
3. Search for any keyword that was added in the excerpt or content https://prnt.sc/Fx9vbrQEJomo
4. The post will not appear on the  search results: https://prnt.sc/N-i0KK8XcW4k

Here is a full screenshot of the customer back-end: https://prnt.sc/eo6vCQzMHNcT

### Ghost Version

6.26

### Node.js Version

14.17.6

### How did you install Ghost?

Windows 10 Local Installation

### Database type

SQLite3

### Browser & OS version

Chrome & Windows 10

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by ErisDS** [comment]
As far as I can tell, you're describing the default behaviour for search with all posts - nothing to do with the page being for members only.

Search looks across the title and excerpt field for all posts. In the case of the post you screenshotted, the excerpt is empty, so it will be whatever Ghost auto-generated and may not have included the word "rather".

**Comment by javierencalada** [comment]
Hello, thank you very much for your reply.

Here is a full test (member article with excerpt assigned): https://prnt.sc/QTyxEc48MsAc

![image](https://user-images.githubusercontent.com/5891905/214093557-fdcd69f4-42c1-4c22-8484-599a5b8174a6.png)

And when i search on the front-end:

![image](https://user-images.githubusercontent.com/5891905/214093742-6a78a35d-b983-4503-8f87-ab385e306abc.png)

If you need more information, just let me know, regards

**Comment by halilhanbadem** [comment]
I confirm the same error. Although there are related "words" in the excerpt section, if the post is only open to members (or premium or any other tier), the search section is not functional.
