### ISSUE TITLE
Native comments not stylable

### ISSUE THREAD

**Issue by kirkbushell** [TryGhost/Ghost#16082]
### Issue Summary

Unless I've missed something very obvious, I cannot figure out how to style native ghost comments, which blows my mind.

It currently makes some custom themes unusable, due to incorrect fonts/colours on the comments section.

### Steps to Reproduce

1. Enable comments
2. Try and style them.

### Ghost Version

5.*

### Node.js Version

14

### How did you install Ghost?

Using Midnightpress

### Database type

MySQL 5.7

### Browser & OS version

Chrome

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by ErisDS** [comment]
Ghost's native comments are an embeddable widget, the same as Portal. There are configuration options in the docs: https://ghost.org/docs/themes/helpers/comments/

If you have a need for styling it beyond these, a feature request would be more appropriate.
