### ISSUE TITLE
ghost.org/changelog links on your site do not work (dns error)

### ISSUE THREAD

**Issue by amj** [TryGhost/Ghost#16088]
### Issue Summary

clicking through any of the links to your changelog redirects to errors.ghost.org

### Steps to Reproduce

clicked the 'our public changelog' link from https://ghost.org/docs/product/ 

### Ghost Version

n/a

### Node.js Version

n/a

### How did you install Ghost?

n/a

### Database type

Other

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by daniellockyer** [comment]
This has been resolved 🙂
