### ISSUE TITLE
Internal site (your own site) bookmarks fail to render images

### ISSUE THREAD

**Issue by kirkbushell** [TryGhost/Ghost#16083]
### Issue Summary

There appears to be an issue with the CSS when rendering your own site's bookmarks within a post (email seems fine). The issue is that the image for the thumbnail is rendered with a height of 0, thereby effectively hiding the image (it fetches the image fine).

I'm using bookmarks to create a monthly recap of the articles of the month, that will also be sent to subscribers. Currently, those bookmarks to my own articles are not rendering the thumbnails, making the post on the site look rather drab.

### Steps to Reproduce

1. Create a post you'd like to link to via a bookmark
2. Create a new post, and add a bookmark - use the URL of the post in point 1 for the bookmark
3. Preview or view the new post with the bookmark, you'll see thumbnail is not displayed.

### Ghost Version

5.*

### Node.js Version

16+

### How did you install Ghost?

Using Midnightpress

### Database type

MySQL 5.7

### Browser & OS version

PC Chrome, Mac OS Chrome.

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by ErisDS** [comment]
Hi @there, thanks for the detailed bug report. From what I can tell, this issue would be specific to the theme you are using - it is not reproducible in Casper (the default theme) on main. If this is an official theme, let us know which one - otherwise please contact the theme developer.
