### ISSUE TITLE
Subresource Integrity (SRI) - "integrity" attribute missing on Javascript delivered via CDN

### ISSUE THREAD

**Issue by ronthedrummer** [TryGhost/Ghost#16090]
### Issue Summary

Any resources delivered via a CDN should have the integrity attribute with a SHA hash to ensure the resource has not been modified, creating a potential vulnerability. 

### Steps to Reproduce

1. Deploy a Ghost site
2. JS assets served via a CDN included within the default template do not have an integrity attribute

### Ghost Version

5.26.3

### Node.js Version

16.19.0

### How did you install Ghost?

local and server

### Database type

Other

### Browser & OS version

N/A

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by ronthedrummer** [comment]
I'm looking into a solution for this. 
Initial thoughts are to:
1. add the hash to the `ghost/core/core/shared/config/defaults.json`
2. Update the `getFrontendAppConfig` function
3. Update any logic that uses `getFrontendAppConfig`

**Comment by ErisDS** [comment]
Marked this as a feature request. I've reopened it as it seems you're looking to add support yourself and I'm happy to accept a PR for this as an additional security feature.

However, please note this will need to be implemented such that it's optional, as we pin to minor versions, not patches, and this would break that. Seems like something that's fine to opt into, but is not for the majority of users.
