### ISSUE TITLE
Custom Storage Adapter delete not called when deleting the image

### ISSUE THREAD

**Issue by as-ajitsingh** [TryGhost/Ghost#16118]
### Issue Summary

When using custom storage I can see save is called when uploading the image but delete method is not called when deleting the image. 

### Steps to Reproduce

1. Upload any image and check for save method called from custom storage adapter
2. Delete image and check for delete method called from custom storage adapter

### Ghost Version

 5.28.0

### Node.js Version

v16.19.0

### How did you install Ghost?

ghost-cli

### Database type

SQLite3

### Browser & OS version

chrome and macos ventura

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by ErisDS** [comment]
Ghost doesn't have any tooling for deleting an image, so I'm not sure what you mean when you say "delete the image"?

Do you mean removing it from a post? This deliberately does not delete the image, as it may be used elsewhere and we have no way to know.

I suspect this is the expected behaviour, but want to double check before closing.

**Comment by as-ajitsingh** [comment]
When using custom storage adapters (https://ghost.org/docs/config/#creating-a-custom-storage-adapter), we extend base adapter which tells to implement following methods - 
 1. exists()
 2. save() 
 3. serve() 
 4. delete() 
 5. read()
 
out of all these delete() method is not called from ghost side. Which results in functionalities like save, server etc working fine but not delete().

In my case I have written a custom firebase adapter and implemented all above methods but the call for delete method is not happening.

**Comment by as-ajitsingh** [comment]
gentle reminder !!
