### ISSUE TITLE
scriptUrl.includes is not a function when SodoSearch has url:false

### ISSUE THREAD

**Issue by ltoinel** [TryGhost/Ghost#16120]
### Issue Summary

Hi Ghost Team,

When you want to disable the loading of SodoSearch library on Ghost using url:false described in the documentation : 

`  
"sodoSearch": {
    "url": false
}
`

Ghost returns this message in the error log : 

`
"ScriptUrl.includes is not a function at getFrontendAppConfig (/data/www/www.xxxx.org/versions/5.30.0/core/frontend/utils/frontend-apps.js:7:19)
`
The code : 
`  
let scriptUrl = config.get(`${app}:url`);
let stylesUrl = config.get(`${app}:styles`);
if (scriptUrl.includes('{version}')) {
        scriptUrl = scriptUrl.replace('{version}', appVersion);
}
if (stylesUrl?.includes('{version}')) {
        stylesUrl = stylesUrl.replace('{version}', appVersion);
 }
`

Its look like a merge error : style.include and stylesUrl?.include are present twice in the function ? 

https://github.com/TryGhost/Ghost/blob/main/ghost/core/core/frontend/utils/frontend-apps.js 

### Steps to Reproduce

1. Disable SodoSearch in the config file.
2. Check the Ghost error log 

### Ghost Version

v5.30.0

### Node.js Version

v16.19.0

### How did you install Ghost?

Ghost CLI + Ghost Update

### Database type

MySQL 8

### Relevant log / error output

```shell
{"name":"Log","hostname":"sd-130779","pid":1942748,"level":50,"version":"5.30.0","err":{"domain":"https://www.xxx.org","message":"scriptUrl.includes is not a function","stack":"TypeError: scriptUrl.includes is not a function\n    at getFrontendAppConfig (/data/www/www.xxx.org/versions/5.30.0/core/frontend/utils/frontend-apps.js:7:19)\n    at getSearchHelper (/data/www/www.xxx.org/versions/5.30.0/core/frontend/helpers/ghost_head.js:74:36)\n    at Object.ghost_head (/data/www/www.xxx.org/versions/5.30.0/core/frontend/helpers/ghost_head.js:217:23)\n    at async Object.returnAsync (/data/www/www.xxx.org/versions/5.30.0/core/frontend/services/helpers/handlebars.js:16:30)"},"msg":"scriptUrl.includes is not a function","time":"2023-01-14T15:22:33.637Z","v":0}
```

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by ltoinel** [comment]
The String type check on my PR is not enough. The script is still included in the DOM with a false URL.

`
<script src="false" ...> 
`

**Comment by ErisDS** [comment]
Hey there, thank you so much for the detailed bug report.

That does look like something that shouldn't happen! There are a couple of open PRs about this which is great - having a slow January but we'll get to reviewing them soon :)

**Comment by ltoinel** [comment]
Another behaviour identified, the "Ghost_head" is not injected in the pages when  ""sodoSearch": { "url": false }" is defined in the configuration

**Comment by smoebody** [comment]
This is case for `"portal": {"url": false }` as well. It leads to problems with the image gallery, see #16601

**Comment by ZhelinCheng** [comment]
> Another behaviour identified, the "Ghost_head" is not injected in the pages when ""sodoSearch": { "url": false }" is defined in the configuration

Did you solve this problem? @ltoinel

**Comment by ZhelinCheng** [comment]
> Another behaviour identified, the "Ghost_head" is not injected in the pages when ""sodoSearch": { "url": false }" is defined in the configuration识别出的另一种行为是，当在配置中定义了“sodoSearch”：{“url”：false }”时，“Ghost_head”不会注入页面

I have installed the latest version, but the issue still persists.

**Comment by daniellockyer** [comment]
This should be fixed in the next release of Ghost and the correct method to disable search is still putting this in config:

```
  "sodoSearch": {
    "url": false
  }
```
