### ISSUE TITLE
Email recipient subsets can be chosen but it sometimes still sends to everyone when retrying

### ISSUE THREAD

**Issue by backspace** [TryGhost/Ghost#16125]
### Issue Summary

A grassroots group I’m part of is wanting to start sending out a newsletter but we ran into the same problems helpfully documented in #15725. As an experiment, I tried creating a label so I could send to a subset of subscribers of under 100. I’ve been trying this repeatedly as I continue to try to get it sent and I’ve found in a specific circumstance that after I complete the penultimate step it says it’s going to send to all subscribers despite me having chosen the label, like this:

![ghost-subscriber-filter-broken](https://user-images.githubusercontent.com/43280/212576117-c6803b90-aa09-4745-a2b3-c9705ad81295.gif)

If I understand this correctly, it’s a UI-only problem, since the records in `email_receipients` have already been created and will be reused, so the actual subset will still be used.

Thanks for all the work on this over the years 💞

### Steps to Reproduce

1. Publish a post that includes emailing a subset of subscribers, but have the emailing fail.
2. Unpublish the post.
3. Refresh the browser.
4. Try publishing again with emailing, it will show initially that it will send only to the subset but then on the last step will show that’s emailing everyone.

### Ghost Version

5.30.0

### Node.js Version

16.19.0

### How did you install Ghost?

Docker image served by Dokku on Ubuntu 16.04

### Database type

MySQL 8

### Browser & OS version

Brave 1.41.100 (Chromium 103.0.5060.134) on macOS 13.1

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by ErisDS** [comment]
cc @55sketch

**Comment by allouis** [comment]
I can reproduce this, and I can also confirm that it's just a UI problem.

I believe the offending code is here: https://github.com/TryGhost/Ghost/blob/v5.31.0/ghost/admin/app/utils/publish-options.js#L170-L172

We're not taking into account the `this.post.emailSegment` property, which seems to be fine when the post is new, because they both default to the same thing. And then when changing the segment in the publish options, we update both. But when refreshing we lose that information and end up with the default!

@kevinansfield I haven't got a lot of context here - can we just return `this.post.emailSegment` if it exists here?

**Comment by kevinansfield** [comment]
Agreed, we should be using `this.post.emailSegment` in the publish options recipient filter if the post has it set.

Does `post.emailSegment` include the selected newsletter as part of its filter? If so then we'll need to think about how it's handled across [`publishOptions.recipientFilter`](https://github.com/TryGhost/Ghost/blob/main/ghost/admin/app/utils/publish-options.js#L207-L215) _and_ [`publishOptions.fullRecipientFilter`](https://github.com/TryGhost/Ghost/blob/main/ghost/admin/app/utils/publish-options.js#L207-L215)

**Comment by allouis** [comment]
@kevinansfield I took a look and it doesn't include the selected newsletter - which means that we should be able to just use the `post.emailSegment` if present! I've requested your review on this PR https://github.com/TryGhost/Ghost/pull/16197
