### ISSUE TITLE
Ghost Newsletter email includes ALL text when a paid-members newsletter is sent to free members, in plaintext only

### ISSUE THREAD

**Issue by cathysarisky** [TryGhost/Ghost#16131]
### Issue Summary

When an email is sent to all members with the access set to 'paid members only', the expected behavior is that free members would see only the preview text, followed by a CTA to subscribe.  That's exactly what happens for HTML email.  However, plain text email reveals the FULL text.  See images here: https://cathy.sarisky.link/newsletters-public-previews-and-more/ (post is not finished, but I think the images are revealing!)

### Steps to Reproduce

1- Create a post, add a public preview, put text above and below it.  Set it to paid members only.
2. Email the newsletter to both free and paid members.

Check the PLAIN TEXT of what free users receive.  (In Gmail, 'show original'.)

### Ghost Version

5.30.0

### Node.js Version

Ghost Pro.

### How did you install Ghost?

Ghost Pro.

### Database type

MySQL 8

### Browser & OS version

Ghost Pro / tested with a Gmail and Outlook addresses

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by ErisDS** [comment]
cc @55sketch
