### ISSUE TITLE
OG Image problem

### ISSUE THREAD

**Issue by gabrielpaivadev** [TryGhost/Ghost#16195]
### Issue Summary

The OG image doesn't work because the URL is being encoded when use https://wsrv.nl

### Steps to Reproduce

Example: [https://carro10.com.br/ekstrom-supera-schumacher-e-conquista-tetracampeonato-no-roc-2023/](https://carro10.com.br/ekstrom-supera-schumacher-e-conquista-tetracampeonato-no-roc-2023/)

URL: https://wsrv.nl/?w=720&h=720&fit=cover&q=100&we&url=https://www.grandepremio.com.br/wp-content/uploads/2023/01/Winner-Mattias-Ekstrom-SWE-celebrates-on-the-podium-during-the-Race-Of-Champions-2023-at-scaled.jpg

OG GRAPH: https://wsrv.nl/?w&#x3D;720&amp;h&#x3D;720&amp;fit&#x3D;cover&amp;q&#x3D;100&amp;we&amp;url&#x3D;https://www.grandepremio.com.br/wp-content/uploads/2023/01/Winner-Mattias-Ekstrom-SWE-celebrates-on-the-podium-during-the-Race-Of-Champions-2023-at-scaled.jpg

OG Test

### Ghost Version

5.33.0

### Node.js Version

v18.12.1

### How did you install Ghost?

Ubuntu 22.04 LTS

### Database type

MySQL 5.7

### Browser & OS version

All browsers

### Code of Conduct

- [x] I agree to be friendly and polite to people in this repository

**Comment by daniellockyer** [comment]
Hey @gabrielpaivadev 👋🏻 

When you say "OG image doesn't work", what exactly do you mean? Whilst the URL is encoded, if I dump it into an OG tags checker, it reports the image is fine.

For example, https://www.opengraph.xyz/url/https%3A%2F%2Fcarro10.com.br%2Fekstrom-supera-schumacher-e-conquista-tetracampeonato-no-roc-2023%2F
