### ISSUE TITLE
/gif bug

### ISSUE THREAD

**Issue by ever-blogger** [TryGhost/Ghost#16194]
### Issue Summary

/gif doesn't work anymore.

![](https://global.discourse-cdn.com/business4/uploads/ghost2/original/3X/c/e/ceed3d942d0fcb16a7a24052f47fdca7e6389905.gif)

### Steps to Reproduce

/gif

### Ghost Version

Ghost 5.33.0

### Node.js Version

v16.19.0

### How did you install Ghost?

Ubuntu 20.04

### Database type

MySQL 8

### Browser & OS version

Firefox Windows 11

### Relevant log / error output

```shell
https://global.discourse-cdn.com/business4/uploads/ghost2/original/3X/c/e/ceed3d942d0fcb16a7a24052f47fdca7e6389905.gif

https://forum.ghost.org/t/gif-might-be-bugging/31644
```

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by daniellockyer** [comment]
Hi @ever-blogger - have you configured Ghost with a Tenor API key? https://ghost.org/docs/config/#tenor

**Comment by ever-blogger** [comment]
> Hi @ever-blogger - have you configured Ghost with a Tenor API key? https://ghost.org/docs/config/#tenor

Thanks for help, I am able to use `/gif` now, I was thought it is a bug as this feature used to be by default.
