### ISSUE TITLE
Link in newsletter goes to ghost.org when file title is deleted

### ISSUE THREAD

**Issue by vitis586** [TryGhost/Ghost#16193]
### Issue Summary

We are sending out a presentation before an event. Everything was fine until now we deleted the file title field in the file snippet. The newsletter goes out fine but when you click on the file name in the email, it does not take you to the website but goes to ghost.org/?ref=_your-blog-name_. When you don't delete the file title then both links (file name link and file title link) take you to _example.com_.

I am selfhosting and I am only on 5.32.0 (5.33.0 is not yet available on docker hub), but I was able to reproduce it on two instances of Ghost. This was reported oginally from Safari/iOS but I managed to reproduce it on Firefox/Win10.

### Steps to Reproduce

1. Create a new post and give it some catchy title
2. Create a new file snippet in the post area and upload some file
3. The file title is filled in with the file name - delete the file title, it should look like the example below
![image](https://user-images.githubusercontent.com/55784861/215283691-7cd97462-7042-411c-9b38-a8ee8aaa8a9c.png)

4. Send this post as a newsletter
5. Now you will receive the newsletter and there will be link to the website (where you get the file). When you hover over it, it will show correct target - _example.com/r/id?m=id1_
6. Click the file name
7. And instead of ending on _example.com_ you will end on _ghost.org/?ref=your-blog-name_

### Ghost Version

5.32.0

### Node.js Version

16.19.0

### How did you install Ghost?

official docker container on Unraid

### Database type

MySQL 8

### Code of Conduct

- [x] I agree to be friendly and polite to people in this repository

**Comment by vitis586** [comment]
I am on 5.33.5 now and it got worse on my side. Now all links from the File snippet go to ghost.org no matter the changes done to it. All other links redirect well.

**Comment by vitis586** [comment]
I quickly spun up GhostPro instance and I am getting the same behavior - all links in the file snippet in the newsletter lead to ghost.org. I found out that the landing page is the same as when you click the "Powered by Ghost" image in the footer - but you guys probably knew that already. That is probably as far as I can help you.

PS: I was quite impressed with the onboarding to GhostPro. Nice!

**Comment by ErisDS** [comment]
This issue was fixed in https://github.com/TryGhost/Ghost/commit/4fad1986a092347969cc592b76651f049484911e and released in 5.33.6. 

It wasn't in any way related to titles, and affected audio cards too.
