### ISSUE TITLE
Member import problem: cancelled but not yet lapsed subscriptions do not import correctly

### ISSUE THREAD

**Issue by cathysarisky** [TryGhost/Ghost#16225]
### Issue Summary

My client had subscribers coming into Ghost from Stripe & Memberpress. We successfully imported everyone EXCEPT the 40 or so users who had cancelled their subscriptions but still had time remaining. They had Stripe customer IDs, which I successfully got into Ghost (as evidenced by later exporting the same members and being able to see the customer ID), but Ghost wouldn’t mark them as anything but free.

I tried removing and reimporting those users, with a disconnection from Stripe in the middle. No change.

### What did you expect to happen?

Newly imported members who have valid Stripe customer numbers and time remaining on a subscription should be imported as paid members, with that time remaining.  

### Steps to Reproduce

Get some subscribers into Stripe (I don’t think it’s Memberpress specific?)
Cancel their subscriptions.
Import them to Ghost (with their Stripe customer numbers)
Observe that they’re listed as free tier, not paid tier.

### Ghost Version

Ghost Pro / 5.30ish

### Node.js Version

Ghost Pro

### How did you install Ghost?

Ghost Pro / 5.30ish

### Database type

MySQL 8

### Browser & OS version

NA

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by daniellockyer** [comment]
Hi again @cathysarisky - I've confirmed this is a bug with the team and we've prioritised it to be fixed internally 🙂
