### ISSUE TITLE
Post oembed fails

### ISSUE THREAD

**Issue by AlexRoar** [TryGhost/Ghost#16232]
### Issue Summary

Cannot embed links to my website in posts. Bookmark card prints message "No provider found for supplied URL."

### Steps to Reproduce

1. Open a new post
2. Paste the link to the other post (or create a bookmarks card)
3. Link is pasted as a link after some loading, and bookmarks display "No provider found for supplied URL."

### Ghost Version

5.33.6

### Node.js Version

v18.14.0

### How did you install Ghost?

Ubuntu 20.04, Nginx reverse proxy

### Database type

MySQL 5.7

### Browser & OS version

Safari Version 16.2, macOS Monterey

### Relevant log / error output

```shell
## Oembed request
:method: GET
:scheme: https
:authority: alexdremov.me
:path: /ghost/api/admin/oembed/?url=https%3A%2F%2Falexdremov.me%2Fios-app-as-a-microservice-build-robust-app-architecture%2F&type=bookmark
Content-Type: application/json; charset=UTF-8
Accept: application/json, text/javascript, */*; q=0.01
Accept-Language: en-GB,en;q=0.9
Accept-Encoding: gzip, deflate, br
Host: alexdremov.me
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.2 Safari/605.1.15
Connection: keep-alive
Referer: https://alexdremov.me/ghost/
Cookie: `...`
X-Requested-With: XMLHttpRequest
App-Pragma: no-cache
X-Ghost-Version: 5.33

**Response**
:status: 422
Content-Type: application/json; charset=utf-8
Vary: Accept-Version, Accept-Encoding
Date: Mon, 06 Feb 2023 15:09:56 GMT
Content-Length: 337
Cache-Control: no-cache, private, no-store, must-revalidate, max-stale=0, post-check=0, pre-check=0
ETag: W/"151-omVDn3TR6eH/NM+3Dknll51OOIc"
Server: nginx/1.22.1
x-powered-by: Express
content-version: v5.33
```

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by daniellockyer** [comment]
@AlexRoar I can't seem to reproduce this. If I try on my own 5.33.6 site, I get the correct response:

![CleanShot 2023-02-07 at 09 35 57](https://user-images.githubusercontent.com/964245/217193718-dd9e1444-06fa-4cf3-940c-f8dcf69ae9ce.png)

Could there be something interfering with outgoing requests from Ghost to itself?

**Comment by AlexRoar** [comment]
@daniellockyer is it possible that self-linking is crucial to reproducing? Can you try to make a backlink to `test.ghost.io`?

If it still won't be reproduced, do you know if there are any tips on troubleshooting? Links to other websites are embedded correctly.

**Comment by AlexRoar** [comment]
journalctl logs

```
 Encountered error when fetching oembed
 Error ID:
     d8a2fdc0-a70c-11ed-b040-fff5c31149df
 Error Code:
     ETIMEDOUT
 ----------------------------------------
 TimeoutError: Timeout awaiting 'request' for 2000ms
     at OEmbed.fetchOembedDataFromUrl (/var/www/alexdremov.me/versions/5.33.6/node_modules/@tryghost/oembed-service/lib/oem>
     at ClientRequest.<anonymous> (/var/www/alexdremov.me/versions/5.33.6/node_modules/got/source/request-as-event-emitter.>
     at Object.onceWrapper (node:events:628:26)
     at ClientRequest.emit (node:events:525:35)
     at origin.emit (/var/www/alexdremov.me/versions/5.33.6/node_modules/@szmarczak/http-timer/source/index.js:37:11)
     at Immediate.timeoutHandler (/var/www/alexdremov.me/versions/5.33.6/node_modules/got/source/utils/timed-out.js:63:11)
     at process.processImmediate (node:internal/timers:478:21)

 [2023-02-07 17:28:33] ERROR "GET /ghost/api/admin/oembed/?url=https%3A%2F%2Falexdremov.me%2Fquick-guide-to-async-await-in->

 No provider found for supplied URL.
 "https://alexdremov.me/quick-guide-to-async-await-in-swift/"
 Error ID:
     d8a4ab70-a70c-11ed-b040-fff5c31149df
 ----------------------------------------
 ValidationError: No provider found for supplied URL.
     at OEmbed.unknownProvider (/var/www/alexdremov.me/versions/5.33.6/node_modules/@tryghost/oembed-service/lib/oembed-ser>
     at OEmbed.fetchOembedDataFromUrl (/var/www/alexdremov.me/versions/5.33.6/node_modules/@tryghost/oembed-service/lib/oem>
     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
     at async /var/www/alexdremov.me/versions/5.33.6/node_modules/@tryghost/api-framework/lib/http.js:64:28
```

**Comment by AlexRoar** [comment]
Checked out this issue https://github.com/TryGhost/Ghost/issues/11673

Seems like my problem is also related to node version as I recently upgraded to v18. Downgrading, then!
And closing the issue as it is not reproduced on node v16

**Comment by olivierlambert** [comment]
@alexdremov just to let you know: I had the exact same problem (Node 18 outdated), switched to Node 20 and now it works correctly. That's why reporting issues is great, because it helps others having similar problems to try a fix and being happy after :+1:
