### ISSUE TITLE
How can I implement a custom sitemap in Ghost CMS, including a priority sitemap and image sitemap? 

### ISSUE THREAD

**Issue by Digitalavdhesh** [TryGhost/Ghost#16235]
### Issue Summary

Is this possible to implement priority sitemap and image sitemap Basically asking how can I customise the sitemap in Ghost CMS?

### Steps to Reproduce

Im unable to set up this customised sitemap

### Ghost Version

Lates

### Node.js Version

Latest

### How did you install Ghost?

Latest

### Database type

MySQL 8

### Browser & OS version

asdasd

### Relevant log / error output

```shell
adjhaskjd
```

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by daniellockyer** [comment]
Hey @Digitalavdhesh - we have docs on creating a custom sitemap (albeit for Google News) here: https://ghost.org/tutorials/create-a-google-news-sitemap/

**Comment by Digitalavdhesh** [comment]
The solution you're offering is for Google News Sitemap, but it seems like you didn't fully understand the issue. 

The main problem is that I want to set priority in my sitemap to tell Google which URLs are the most important to index. Additionally, I have highly optimized images on my website that I want Google to index, but Ghost doesn't have flexible image optimization options, so I was considering adding an Image Sitemap to my main Sitemap directory, 

but I believe Ghost doesn't allow for custom sitemaps. Is there an alternative solution?
