### ISSUE TITLE
Browser logs ghost admin errors when opening public facing page

### ISSUE THREAD

**Issue by lvnilesh** [TryGhost/Ghost#16249]
### Issue Summary

Browser logs ghost admin errors when opening public facing page https://domain.com/ in an incognito window.
```
https://domain.com/ghost/api/admin/users/me/:1 | Failed to load resource: the server responded with a status of 403 ()

https://domain.com/:5 | TypeError: Cannot read properties of null (reading 'appendChild') 
at https://domain.com/ghost/auth-frame/:5:854 
at https://domain.com/ghost/auth-frame/:5:1449
```

### Steps to Reproduce

Open a public facing page https://domain.com/ in an incognito window.
See browser console

### Ghost Version

ghost:5.33.7-alpine

### Node.js Version

v16.19.0

### How did you install Ghost?

Linux machine 5.15.0-58-generic #64-Ubuntu SMP Thu Jan 5 11:43:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Database type

MySQL 8

### Browser & OS version

Chrome Version 109.0.5414.119 (Official Build) (arm64)

### Relevant log / error output

```shell
https://domain.com/ghost/api/admin/users/me/:1 | Failed to load resource: the server responded with a status of 403 ()

https://domain.com/:5 | TypeError: Cannot read properties of null (reading 'appendChild') 
at https://domain.com/ghost/auth-frame/:5:854 
at https://domain.com/ghost/auth-frame/:5:1449
```

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by daniellockyer** [comment]
@lvnilesh I can't seem to reproduce this, and I can't find where `appendChild` is even used in the relevant code here. Do you have a reproduction case I can follow from a clean instance of Ghost?
