### ISSUE TITLE
#has helper not working with pagination

### ISSUE THREAD

**Issue by securibee** [TryGhost/Ghost#16262]
### Issue Summary

Hi team,

[According to the documentation](https://ghost.org/docs/themes/helpers/has/), the following has statement should prevent {{pagination}} from rendering if there is none, and render it if there are multiple pages: `{{#has any="prev, next"}}`.

> The `any` comparison will return true if any one of the properties is set in the current context, with support for paths and globals

I also found [an older example](https://forum.ghost.org/t/conditionals-in-handlebars/1928/10) that indicates that this should work. However, the pagination never renders at all when using `has`.

References:

[Pagination docs](https://ghost.org/docs/themes/helpers/pagination/)
[Has helper docs](https://ghost.org/docs/themes/helpers/has/)
[Initial topic](https://forum.ghost.org/t/has-helper-not-working-for-pagination/35336)
[Old example](https://forum.ghost.org/t/conditionals-in-handlebars/1928/10)

### Steps to Reproduce

To ensure the context has access to `prev` and `next`, I logged their values. When on the first pagination page, I used `{{log prev}}` and `{{log next}}`, which returned `1` and `null` as expected.

```
{{log prev}}
{{log next}}
{{#has any="prev, next"}} 
  <nav class="pt-28 max-w-3xl mx-auto px-4 sm:grid grid-cols-3" role="navigation">
    {{#if prev}}
      <a class="col-start-1 ml-auto sm:rounded-l-lg flex items-center text-yellow-400 py-4 sm:py-8 px-4 bg-zinc-800 hover:bg-yellow-300 hover:text-zinc-900" href="{{page_url prev}}">
        <div class="w-10 h-10 flex items-center justify-center">{{> "icons/arrow-left"}}</div>
        <h4 class="text-base px-4">Newer posts</h4>
      </a> 
    {{/if}}
    <span class="col-start-2 bg-zinc-800 text-zinc-400 flex items-center justify-center py-4 sm:py-8">Page {{page}} of {{pages}}</span>
    {{#if next}}
      <a class="col-start-3 sm:rounded-r-lg flex mr-auto items-center text-yellow-400 py-4 sm:py-8 px-4 bg-zinc-800 hover:bg-yellow-300 hover:text-zinc-900" href="{{page_url next}}">
        <h4 class="text-base px-4">Older posts</h4>
        <div class="w-10 h-10 flex items-center justify-center">{{> "icons/arrow-right"}}</div>
      </a> 
    {{/if}}
  </nav>
{{/has}}
```

### Ghost Version

5.26.3

### Node.js Version

v16.13.0

### How did you install Ghost?

homebrew

### Database type

SQLite3

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by daniellockyer** [comment]
That doesn't look right! A PR to fix this would be welcome 🙂

**Comment by Pran-Ker** [comment]
Instead of : 
 `{{#has any="prev, next"}}` 

We could use this :
`{{#if (or prev next)}}`

This achieves the same effect as the {{#has}} statement, but using a different syntax. Let me know if I should work on this.
