### ISSUE TITLE
500 Error on Post Image Loading

### ISSUE THREAD

**Issue by EinfachRuwen** [TryGhost/Ghost#16293]
### Issue Summary

i uploaded an image for my post which is loaded in the admin panel under the URL `content/images/2023/02/Discord-2.png` but the post itself tries to get the image from `/content/images/size/w2000/2023/02/Discord-2.png` and this leads to the 500 error

### Steps to Reproduce

1. Create a New post with a Feature Image
2. Go to the public Post page
3. look into network analytics

### Ghost Version

4

### Node.js Version

docker image

### How did you install Ghost?

Docker

### Database type

SQLite3

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by daniellockyer** [comment]
Without any logs, it's difficult to debug this, but my guess given the different paths is that `sharp` failed to install on your system: https://github.com/docker-library/ghost/discussions/371, which points to it being an environment issue.
