### ISSUE TITLE
Excerpt not reaching Admin API

### ISSUE THREAD

**Issue by bramses** [TryGhost/Ghost#16291]
### Issue Summary

When POSTing to the admin API, the excerpt field fails to update on the dashboard.

### Steps to Reproduce

I posted to this url:

```js
// updating a current post on ghost, (I use POST for creation)
// version = v4
const result = await request({
		url: `${settings.url}/ghost/api/${version}/admin/posts/${id}/?source=html`,
		method: "PUT",
		contentType: "application/json",
		headers: {
			"Access-Control-Allow-Methods": "PUT",
			"Content-Type": "application/json;charset=utf-8",
			Authorization: `Ghost ${token}`,
		},
		body: JSON.stringify(htmlContent),
	});
```

This is what the POST sends from my app:

![Screenshot 2023-02-17 11-08-14](https://user-images.githubusercontent.com/3282661/219706215-1f33e744-62b3-448c-aae0-89e157175c40.png)

Everything sends correctly *except excerpt*:

![Screenshot 2023-02-17 11-13-20](https://user-images.githubusercontent.com/3282661/219706443-36ac968d-fddb-42d2-a461-480d2b72524c.png)

No error was thrown

### Ghost Version

v4 api

### Node.js Version

19.5

### How did you install Ghost?

Ghost Pro

### Database type

MySQL 5.7

### Browser & OS version

Safari

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by daniellockyer** [comment]
Hey @bramses - you probably want to use `custom_excerpt`, as that is the editable field.

The calculated field is called `excerpt`, which is the value of `custom_excerpt` or falls back to something automatically generated if the custom field is empty
