### ISSUE TITLE
Uploading an m4a file to an audio card fails when using Firefox on Windows

### ISSUE THREAD

**Issue by reupen** [TryGhost/Ghost#16301]
### Issue Summary

Hi,

I noticed that it's not possible to upload an m4a file to an audio card using Firefox on Windows. If you try to do so, the error 'Please select a valid media file.' is displayed.

There is no problem using Chrome.

The difference I can see is that Firefox specifies the MIME type `audio/mp4`, while Chrome specifies `audio/x-m4a`.

Perhaps `audio/mp4` is just missing from this list:

https://github.com/TryGhost/Ghost/blob/066db4c46fec15d998325f287a5b5056e13dc961/ghost/core/core/shared/config/overrides.json#L34-L45

### Steps to Reproduce

1. Create a draft post
2. Add an audio card
3. Upload an .m4a file using Firefox on Windows

A zipped sample file of silence is attached (but any m4a file should do).

[silence.zip](https://github.com/TryGhost/Ghost/files/10787960/silence.zip)

### Ghost Version

5.35

### Node.js Version

18.14.1

### How did you install Ghost?

Tested both native on Ubuntu 22.04 and using the container image

### Database type

MySQL 8

### Browser & OS version

Firefox 111 beta 2, Windows 10

### Relevant log / error output

```shell
[2023-02-20 21:36:24] ERROR "POST /ghost/api/admin/media/upload/" 415 25ms

Please select a valid media file.

Error ID:
    a0036130-b166-11ed-9f6d-e54eb9848d84

----------------------------------------

UnsupportedMediaTypeError: Please select a valid media file.
    at mediaUploadValidation (/var/lib/ghost/versions/5.35.0/core/server/web/api/middleware/upload.js:194:25)
    at Layer.handle [as handle_request] (/var/lib/ghost/versions/5.35.0/node_modules/express/lib/router/layer.js:95:5)
    at next (/var/lib/ghost/versions/5.35.0/node_modules/express/lib/router/route.js:144:13)
    at /var/lib/ghost/versions/5.35.0/core/server/web/api/middleware/upload.js:113:9
    at Immediate._onImmediate (/var/lib/ghost/versions/5.35.0/node_modules/multer/lib/make-middleware.js:53:37)
    at processImmediate (node:internal/timers:468:21)
```

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by daniellockyer** [comment]
@reupen That's strange! A PR to fix this is welcome 🙂
