### ISSUE TITLE
Automatic redirect after slug change

### ISSUE THREAD

**Issue by praalhans** [TryGhost/Ghost#16323]
### Issue Summary

After a post is published, it is still possible to change its slug. However, the old slug then is no longer accessible (and shows a `404 Not Found` error).

Expected behavior: the old resource should instead redirect the user to the place where the resource can be found, using a `302 Found` reply.

Workaround: using the `redirects.yaml` and manually add the 302 redirect.

### Steps to Reproduce

1. Create a post with a slug e.g. `abc`
2. Publish post.
3. Verify post is accessible: visit `site.com/abc`
4. Change slug after publication, e.g. `abcd`
5. Verify post is no longer accessible: now `site.com/abc` yields 404

### Ghost Version

5.35.1

### Node.js Version

Unknown

### How did you install Ghost?

Hosted by Ghost.io

### Database type

MySQL 5.7

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by daniellockyer** [comment]
@praalhans This is expected functionality, so I've labelled your issue as a feature request accordingly 🙂
