### ISSUE TITLE
Error of tag having the same white color as the background in the Post admin page.

### ISSUE THREAD

**Issue by al0xd** [TryGhost/Ghost#16474]
### Issue Summary

Hello,
Today I noticed an error occurred, which is that the background color of tags is the same as the color of the tag in Edit Post page. Similarly, this error also appears in the author selection section of the article.
When inspecting, I found that the style of the tag is:
```
.tag-token:not(.tag-token--internal) {
    position: relative;
    color: var(--accent-color);
    background: none;
}
```
The variable `var(--accent-color)` is set to white and `background` is set to `none`, so the tag part is no longer visible.

### Steps to Reproduce

1. Go to `ghost` -> `posts` -> `new post` or `edit post`
2. Click to **Post settings**

### Ghost Version

v5.39.0

### Node.js Version

v16.17.0

### How did you install Ghost?

Ubuntu 20.04.4 LTS (GNU/Linux 5.4.0-144-generic x86_64)

### Database type

MySQL 5.7

### Browser & OS version

user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36

### Relevant log / error output

```shell
No response
```

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by daniellockyer** [comment]
That doesn't look right! A PR to fix this would be welcome 🙂

**Comment by al0xd** [comment]
I encountered this error when using the light mode, when using the dark mode everything is completely normal!
![Light mode](https://i.ibb.co/nRzxqqJ/Screen-Shot-2023-03-25-at-10-13-04-AM.png)
![Dark node](https://i.ibb.co/VMz9PKn/Screen-Shot-2023-03-25-at-10-13-51-AM.png)

**Comment by daniellockyer** [comment]
@shikhar13012001 We don't assign issues but you're more than welcome to open a PR 🙂

**Comment by Amdadullah-Raihan** [comment]
Hello dear maintainers,

I'm trying to contribute to the Ghost project by fixing a bug in the /posts route. I've been looking for the file src/api/routes/posts.js, but I can't seem to find it.

I've tried searching for the file in the Ghost repository, but I can't find it. I've also tried looking for the file in the Ghost documentation, but I can't find it there either.

I'm not sure where else to look for the file. Could you please help me find it?

Thanks,
Amdadul Islam
