### ISSUE TITLE
Stripe VAT not showing up

### ISSUE THREAD

**Issue by mkschreder** [TryGhost/Ghost#16477]
### Issue Summary

When stripe vat is enabled on the price in the stripe product settings, it still does not show up on the checkout page. It seems ghost is not even passing tax_id_collection[enabled]"="true" to the checkout session.

How can this be enabled? 

### Steps to Reproduce

- Create a ghost plan
- Go to stripe dashboard and select the product, then set "tax collection" to exclusive (ie vat is excluded from the price and should appear as a separate line on the checkout)
- Reload the site and go to checkout - still no vat anywhere to be seen. 

### Ghost Version

5.4

### Node.js Version

18

### How did you install Ghost?

Docker image

### Database type

MySQL 5.7

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by daniellockyer** [comment]
Hey @mkschreder, this is currently expected but we're looking at the steps needed to support Stripe Tax internally, so keep an eye on our release notes for any updates 🙂
