### ISSUE TITLE
Can't successfully extend navigation URLs

### ISSUE THREAD

**Issue by bland328** [TryGhost/Ghost#16500]
### Issue Summary

Appending page names to URLs under `Settings` > `Navigation` _(i.e. changing_ `http://ghosttest:2386` _to_ `http://ghosttest:2386/about`_)_ doesn't work; changes don't stick when Save is clicked and the page is reloaded.

However, _replacing_ URLs with unrelated URLs that don't share the standard base _(i.e. changing_ `http://ghosttest:2386` _to_ `http://microsoft.com`_)_ _does_ work properly.

Put another way:
1. Any URL starting with `http://ghosttest:2386` is truncated to `http://ghosttest:2386` upon saving.
2. Any URL not starting with `http://ghosttest:2386` can be successfully saved as entered.

### Steps to Reproduce

1. Go to Settings > Navigation
3. Type a new Label
4. Add the name of an existing page to the end of the URL to the right of the new Label
5. Click Save
6. Reload the page and see that the item with the new Label still exists, but that the page name is missing from the URL

### Ghost Version

5.39.0

### Node.js Version

16.19.1

### How did you install Ghost?

Official Ghost Docker container under Unraid (Slackware Linux)

### Database type

Other

### Browser & OS version

Chrome 111.0.5563.64 under macOS Ventura 13.2.1

### Relevant log / error output

```shell
(no applicable output)
```

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by bland328** [comment]
I have some new information:

I put my installation behind a reverse proxy, accessed the site through the internet, corrected the URLs under `Settings` > `Navigation` to reflect the new base URL, then successfully added page names to several of them.

So, this new configuration fixes the problem.

It strikes me that for local testing I previously had the `url` variable set to `http://ghosttest:2386`--perhaps the trailing port wasn't necessary/appropriate, and caused the issue?

**Comment by daniellockyer** [comment]
I can't seem to reproduce this, and it seems you've found a fix/workaround for now, so I'm going to close this until we get more reports 🙂
