### ISSUE TITLE
Unable to upload image in general settings

### ISSUE THREAD

**Issue by Megpag** [TryGhost/Ghost#16538]
### Issue Summary

I'm unable to upload the cover image to set up my homepage - the button is unresponsive (doesn't open a folder to upload a picture from my computer)

I'm using chrome on a mac book air 2018

### Steps to Reproduce

1. click on the upload button
2. upload the cover image from my laptop

### Ghost Version

5.40.2+moya

### Node.js Version

no idea

### How did you install Ghost?

from the website, pro version

### Database type

MySQL 5.7

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by daniellockyer** [comment]
Hey @Megpag 👋🏻 I'm unable to reproduce the issue, so I'll need some more info from you:

1. what Chrome version are you using?
2. do you have any extensions that might interfere with this?
3. are there any errors logs in the browser console that could help with debugging?

**Comment by Megpag** [comment]
Hi - this issue got fixed! Although now (that I migrated the site to my
custom domain) when I try to go on my website it says "the connection is
not private"

Can you help me with this?

Thank you in advance

M

**This email was sent via mobile device. Please excuse brevity and style
