### ISSUE TITLE
Custom adapter error when importing zip

### ISSUE THREAD

**Issue by rpvsilva** [TryGhost/Ghost#16530]
### Issue Summary

I've integrated both adapters [ghost-storage-adapter-s3](https://github.com/colinmeinke/ghost-storage-adapter-s3), and [ghost-azurestorage](https://github.com/hvetter-de/ghost-azurestorage) and both throw the same error when I try to import my medium articles.

```bash
"Cannot read properties of undefined (reading 'split')"
```

I've debugged the problem and it's located in the file: 
https://github.com/TryGhost/Ghost/blob/main/ghost/core/core/server/data/importer/handlers/image.js#L18

I think this is expecting the stores to have the `staticFileURLPrefix` property but does it make sense for each custom adapter to have this property?
I am asking this because your `ghost-adapter-base` does not have the rule that this property must be defined.

The problem only happens when I use the importer feature, but when I add an image to an existing post it works and uploads correctly to the target.

### Steps to Reproduce

1. Integrate a custom adapter that implements following the [official documentation](https://ghost.org/docs/config/#creating-a-custom-storage-adapter)
2. Set the configuration following the [official documentation](https://ghost.org/docs/config/#storage-adapters)
3. Start ghost
4. Go to settings -> Labs and click import content, then select the zip file you want to import
5. There will be an error and you can check your logs

### Ghost Version

v5.40.2

### Node.js Version

v16.19.1

### How did you install Ghost?

Using local files

### Database type

MySQL 8

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by muratcorlu** [comment]
This issue still there with v5.82.1. I use [ghos3](https://github.com/laosb/ghos3) and I can not import zip file from importer because of this error.  We need a better/updated documentation for writing custom storage adapters.
