### ISSUE TITLE
Transactional email encoding problem on sites with an apostrophe / single quote in the name.

### ISSUE THREAD

**Issue by cathysarisky** [TryGhost/Ghost#16549]
### Issue Summary

A site called "Cathy's demo site" sends newsletters with the single quote / apostrophe encoded as &#39; in the subject line. 
See the second line of the image below for the current behavior using the single quote available on my keyboard:
![image](https://user-images.githubusercontent.com/42299862/229780860-a44d2b66-1bf7-4e9d-b7ef-3956465be998.png)

Workaround:  Switch site name to ’ (shown in the example above)
But of course my keyboard doesn't have that character (Windows 10, Chrome, US encoding, English, nothing weird), so it'd be nice if Ghost would silently make the apostrophe that IS on my keyboard work correctly.

### Steps to Reproduce

Create a site with an apostrophe of the type ' (The one on my keyboard right by enter.)
Sign up and check the subject of the transactional email.

### Ghost Version

5.30-something (on Ghost Pro last week)

### Node.js Version

Ghost Pro

### How did you install Ghost?

Ghost Pro

### Database type

MySQL 8

### Browser & OS version

Windows 10, Chrome, recent version.  Problem appears in both Outlook 365 and Gmail web client.

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by vikaspotluri123** [comment]
I think this issue was fixed in https://github.com/TryGhost/Ghost/commit/e95c531e8b4f3564d922b1ef93c91159afabbf53

**Comment by daniellockyer** [comment]
This has been fixed and released in https://github.com/TryGhost/Ghost/releases/tag/v5.42.0 🙂
