### ISSUE TITLE
.well-known/matrix/server not supported

### ISSUE THREAD

**Issue by zimbatm** [TryGhost/Ghost#16553]
### Issue Summary

After publishing the `.well-known/matrix/server` file through the template, it doesn't get served publicly.

### Steps to Reproduce

The current way to publish `.well-known/*` files is to add them to the template:

```
$ tree .well-known/
.well-known/
├── hello.txt
└── matrix
    ├── client
    └── server
$ cat .well-known/matrix/server 
{
  "m.server": "matrix.numtide.com:443"
}
```

Then publish the template with `TryGhost/action-deploy-theme@v1`. The logs show that the files are being added to the archive:
```
/usr/bin/zip -r numtide.zip . -x *.git* *.zip yarn* npm* node_modules* *routes.yaml *redirects.yaml *redirects.json
<snip>
  adding: .well-known/ (stored 0%)
  adding: .well-known/hello.txt (stored 0%)
  adding: .well-known/matrix/ (stored 0%)
  adding: .well-known/matrix/client (deflated 35%)
  adding: .well-known/matrix/server (stored 0%)
```

Then test that the file is getting served:
```
$ curl https://numtide.com/.well-known/hello.txt
Hello
```

Unfortunately, the matrix ones return a 404:
```
$ curl -LI https://numtide.com/.well-known/matrix/client
<snip>
HTTP/2 404 
<snip>
$ curl -LI https://numtide.com/.well-known/matrix/server
<snip>
HTTP/2 404 
<snip>
```

### Ghost Version

5.41.0+moya

### Node.js Version

unknown

### How did you install Ghost?

SaaS on ghost.io

### Database type

MySQL 5.7

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by zimbatm** [comment]
In case you are trying to reproduce the issue, I couldn't wait, so I slapped Cloudflare in front and now serve those files using a Cloudflare worker.

**Comment by daniellockyer** [comment]
That doesn't look right! A PR to fix this would be welcome 🙂
