### ISSUE TITLE
Change the spelling of the Kiev to Kyiv in the settings timezone picker

### ISSUE THREAD

**Issue by naz** [TryGhost/Ghost#16603]
The timezone picker shows a russian version of spelling "Kiev" and should be "Kyiv" to be more like Ukrainian spelling of Київ.

Screenshot of the Admin UI's `/settings/general` screen:
![Image](https://user-images.githubusercontent.com/675397/230929662-3d8fade0-9bae-4198-a9b0-acc27c8134ba.png)

A [similar issue in momenjs](https://github.com/moment/moment/issues/6008). We need to investigate first, which library the Admin UI is using to fetch the timezone data into the dropdown.

**Comment by Rahilsiddique** [comment]
so, the spelling of kiev just needs to be changed in the `ghost/admin/mirage/fixtures/timezones.js`,
if so can i work on this issue?
thanks
