### ISSUE TITLE
Page Headings not working

### ISSUE THREAD

**Issue by ananyatripathi** [TryGhost/Ghost#16602]
### Issue Summary

H1 and H2 tags in heading is not working when we click on Preview inside pages section.

![image](https://user-images.githubusercontent.com/72099168/230879297-b4b73bbc-16a4-44ce-a057-68fd2211c079.png)

### Steps to Reproduce

1. Open Pages from Side bar of the admin panel
2. Create a new page
3. Write anything with H1/H2 heading
4. Click on preview

(It wont show Heading text with heading style)

### Ghost Version

5.2.0

### Node.js Version

18.5

### How did you install Ghost?

Windows

### Database type

MySQL 5.7

### Browser & OS version

Browser : Chrome OS: Windows

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by RT-1904129** [comment]
Hi Team 
I want to work on this issue.

**Comment by daniellockyer** [comment]
@ananyatripathi What theme are you using? I can't reproduce with Casper.

Let me know how I can better reproduce this and I'll be happy to re-open the issue 🙂
