### ISSUE TITLE
Language not effective in "zh"

### ISSUE THREAD

**Issue by KangSpace** [TryGhost/Ghost#16641]
### Issue Summary

After setting the "zh" language, the new language on the website page will not take effect and will still be "en".

### Steps to Reproduce

1.  Settings > General > Publication Language
    Set "zh" and save.
2. Access website homepage, click "Sign In"  button, the text not change to 'zh' language.

### Ghost Version

 5.44.0

### Node.js Version

v16.19.1

### How did you install Ghost?

Centos7

### Database type

MySQL 5.7

### Browser & OS version

Chrome, macOs

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by QYG2297248353** [comment]
Setting zh has no effect, the file cannot find the login button still remains unchanged
```sh
ghost-ms  | [2024-08-06 05:33:39] [36mINFO[39m Ctrl+C to shut down
ghost-ms  | [2024-08-06 05:33:39] [36mINFO[39m Ghost server started in 0.286s
ghost-ms  | [2024-08-06 05:33:39] [36mINFO[39m Database is in a ready state.
ghost-ms  | [2024-08-06 05:33:39] [36mINFO[39m Ghost database ready in 0.389s
ghost-ms  | [2024-08-06 05:33:40] [35mWARN[39m Theme translations file locales/zh.json not found.
ghost-ms  | [2024-08-06 05:33:40] [35mWARN[39m Theme translations falling back to locales/en.json.
ghost-ms  | [2024-08-06 05:33:40] [36mINFO[39m Adding offloaded job to the queue
```

version: `image: ghost:5.89.0`
