### ISSUE TITLE
Broken link to i18n docs in settings

### ISSUE THREAD

**Issue by matvey00z** [TryGhost/Ghost#16642]
### Issue Summary

The link to documentation (https://ghost.org/docs/i18n/) in settings is broken

### Steps to Reproduce

1. Run a fresh install of ghost (using docker compose)
2. Go to <host>/ghost
3. Set up a user
4. Go to settings -> general
5. Find PUBLICATION INFO -> Publication Language
6. Find the line: Default: English (en); find out more about using Ghost in other languages
7. Click on the link
8. Find yourself on https://ghost.org/docs/i18n/ with "404 page not found"

### Ghost Version

5.43.0

### Node.js Version

-

### How did you install Ghost?

docker compose using https://hub.docker.com/_/ghost/

### Database type

MySQL 8

### Browser & OS version

Firefox 112.0 on Arch Linux

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by daniellockyer** [comment]
Thanks for the ping @matvey00z! Translations is currently in beta so not everything is currently wired up 🙂

**Comment by daniellockyer** [comment]
This is now fixed in 5.49.0 🙂
