### ISSUE TITLE
Images in galleries can't receive ALT text 

### ISSUE THREAD

**Issue by nk9** [TryGhost/Ghost#16640]
### Issue Summary

When you insert an image into a Ghost page, you get the ALT button which lets you add alt text to the image.

<img width="533" alt="Screenshot 2023-04-15 at 13 48 59" src="https://user-images.githubusercontent.com/3646730/232224726-6a188882-3411-4aad-95a3-6dd6bf6a21bc.png">

But when you insert one or more images using a gallery, there is no way to provide ALT text for the individual images. All you get is the caption for the whole gallery.

<img width="1086" alt="image" src="https://user-images.githubusercontent.com/3646730/232224742-f5612587-737f-4876-98a0-e345fd967c40.png">

### Steps to Reproduce

1. Insert a gallery
2. Add an image
3. Discover there is no way to provide ALT text for the image.

### Ghost Version

Current version on ghost.io

### Node.js Version

Current version on ghost.io

### How did you install Ghost?

ghost.io

### Database type

Other

### Browser & OS version

Firefox

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by anubhav1206** [comment]
Can I work on this issue?

**Comment by daniellockyer** [comment]
This is expected functionality right now, but a workaround would be to drag an image outside the gallery, add the alt text, and drag it back into the gallery 🙂

**Comment by nk9** [comment]
Thanks for the reply. What is the project's definition of done when it comes to accessibility? I appreciate that feature requests need to be added via discussions. However, many projects would consider this less of a "would be nice" enhancement request and more of a "the feature is broken right now for unsighted visitors" bug report.

Thanks also for the workaround! I can give that a try, although it sounds tricky enough that your average user won't be able to discover it themselves.
