### ISSUE TITLE
Sign Up Email gives different URL for the button and the link confirmation at the bottom of the email

### ISSUE THREAD

**Issue by designium** [TryGhost/Ghost#16655]
### Issue Summary

The confirmation email is sending different URLs for the "Confirm signup" button versus the Link in the "You can also copy & paste this URL into your browser:".

The button is sending a wrong url: "email.mail.[mydomain]". It's including the subdomain.

Interestingly, the link is sending the right domain  "[mydomain]", without the subdomain.

I checked the template code in "signup.js"

They both use :

     href="${url}"

     ${url}

So they should be sending the same URL. 

Version: 

Ghost-CLI version: 1.24.0
Ghost version: 5.44.0 (at /var/www/ghost)

### Steps to Reproduce

1. Configure a new blog
2. Configure Mailgun
3. Add transaction SMTP info
4. Sign up as a user
5. Receive the confirmation email
6. Click the green button, it leads to wrong URL
7. Click the link at the bottom of the email, it works.

### Ghost Version

5.44.0

### Node.js Version

v16.17.0

### How did you install Ghost?

Digital Ocean

### Database type

MySQL 5.7

### Browser & OS version

Ubuntu

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by daniellockyer** [comment]
@designium Can you paste relevant parts of your config (redacted of secrets) for email and setting the site URL?

**Comment by designium** [comment]
Where do I see the config file? Sorry for the basic question.

**Comment by designium** [comment]
config.product.json


    {
          "url": "https://******",
          "server": {
            "port": 2368,
            "host": "127.0.0.1"
          },
          "database": {
            "client": "mysql",
            "connection": {
              "host": "localhost",
              "user": "************",
              "password": "**************",
              "port": 3306,
              "database": "ghost_production"
            }
          },
          "mail": {
            "transport": "SMTP",
            "options": {
              "service": "Mailgun",
              "host": "smtp.mailgun.org",
              "auth": {
                "user": "*************",
                "pass": "**************"
              }
            }
          },
          "logging": {
            "transports": [
              "file",
              "stdout"
            ]
          },
          "process": "systemd",
          "paths": {
            "contentPath": "/var/www/ghost/content"
          }
        }

**Comment by designium** [comment]
I figure out the issue @daniellockyer.

Basically, I had the Mailgun's Tracking enabled. So it was rewriting the URL in the button, but not in the other URL. 

By disabling the tracking mode on Mailgun, the problem is resolved.
