### ISSUE TITLE
images added to posts in markdown are displayed differently than images added using the '+' button

### ISSUE THREAD

**Issue by nwandabridges** [TryGhost/Ghost#16685]
### Issue Summary

**Problem:**
Images added to posts in Markdown are left aligned instead of center aligned, and they do not display the caption underneath. This behavior differs from images added to posts using the '+' button in the editor.

**Expected Behavior:**
Images added to posts using Markdown are displayed the same as images added to posts using the '+' button in the editor. This means they should be center aligned and the caption should be displayed if a caption is provided.

### Steps to Reproduce

1. Add a Markdown element to a post.
2. Add an image to the Markdown element.
3. Add an image element to the post not using Markdown.
4. Compare how the two images are displayed when the post is published.

### Ghost Version

5.44.0

### Node.js Version

v16.20.0

### How did you install Ghost?

Docker (ghost:alpine image)

### Database type

SQLite3

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by asenseofpradhyu** [comment]
I attempted to reproduce the issue, but it appears that the images from both the markdown and the image '+' buttons look identical. If I am overlooking something, please do let me know. I am eager to contribute to resolving this issue.

Please review this post; I followed the steps exactly as mentioned👇

https://techwithpradhuman.ghost.io/bug-issue/

**Comment by nwandabridges** [comment]
Thanks for looking into this :)

In your example, it appears that both images are centered, which is the expected behavior. However, this is not the behavior on my blog, which is using the current Casper theme (v5.6.0). My blog left-aligns markdown images. You can see my example here: https://andrewbridges.org/ghost-issue-16685-2/

Additionally, neither example (yours or mine) shows a caption for the markdown image.

When an image is added via markdown, I would expect the text between the brackets to be added as a caption:
Example:
```markdown
![This is a caption](https://...)
```

Hopefully this is clear. Please let me know how I can help.

-Andrew

**Comment by asenseofpradhyu** [comment]
**1. Caption Issue:**

When an image is added via markdown, you won't be able to see the caption because it functions as alt text. The alt text is designed to enhance accessibility by providing a description of the image's content to users who may not be able to view the image.

Below are the features supported in markdown.
![Screenshot 2023-08-09 at 10 29 09 PM](https://github.com/TryGhost/Ghost/assets/24241624/4f659712-a753-4cd9-a59f-e8e402a46fda)


If you wish to include a caption with the image, I would recommend using an image with a '+' button."

**2. Image Center Align Issue:**

Yes, I have identified an issue with certain images that have small dimensions. I will work on resolving this problem and submit a pull request for it.

**Comment by nwandabridges** [comment]
Thanks for clarifying the caption behavior, and thanks for your work on the alignment issue :)

**Comment by asenseofpradhyu** [comment]
Please assign me to this bug @daniellockyer

**Comment by daniellockyer** [comment]
We don't assign issues to contributors but you're welcome to open a PR 🙂

**Comment by asenseofpradhyu** [comment]
As I was working into his issue I found that this issue is from https://github.com/TryGhost/Casper which is the default theme for Ghost. I also raised the same issue in the [Casper](https://github.com/TryGhost/Casper) repository.

**Comment by asenseofpradhyu** [comment]
@daniellockyer when will be this issue can be merge ?
