### ISSUE TITLE
Digital Ocean Marketplace CLI Link Issue

### ISSUE THREAD

**Issue by mackenly** [TryGhost/Ghost#16737]
### Issue Summary

Many users install Ghost via Digital Ocean's marketplace; however, there's a broken link in the getting started guide. Evidently, the CLI docs used to be here: https://docs.ghost.org/docs/ghost-cli but have since moved to here: https://ghost.org/docs/ghost-cli/

There appears to be a redirect solution in place, but it doesn't work right. https://docs.ghost.org/docs/ghost-cli redirects to https://ghost.org/docs/docs/ghost-cli which is a 404.

Ideally, the redirect logic should be fixed to redirect docs pages to the correct URL, and the marketplace link should be updated.

### Steps to Reproduce

1. Visit the [Ghost page](https://marketplace.digitalocean.com/apps/ghost) on DO's Marketplace
2. Scroll down to the "check out the Ghost-CLI docs" link and click

### Ghost Version

N/A

### Node.js Version

N/A

### How did you install Ghost?

N/A

### Database type

Other

### Browser & OS version

N/A

### Relevant log / error output

```shell
N/A
```

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by daniellockyer** [comment]
I've updated the link and sent it to DigitalOcean for review 🙂 Thanks for the note
