### ISSUE TITLE
Sitemap is not correct

### ISSUE THREAD

**Issue by razinj** [TryGhost/Ghost#16747]
### Issue Summary

The sitemap generated is not correct, posts and pages are not the same as the one reported in the sitemap.

### Steps to Reproduce

1. Visit: [https://razinj.dev/](https://razinj.dev/) and see how many posts are there,
2. Visit [https://razinj.dev/sitemap.xml and ](https://razinj.dev/sitemap-posts.xml) and see how many posts are reported.

### Ghost Version

5.46.1

### Node.js Version

16.20.0

### How did you install Ghost?

Installed on a VPS using Docker Compose (image: ghost:5-alpine) - Host has plenty of resources: 16 GB RAM + ~300 GB Storage + 6 CPU Cores

### Database type

MySQL 8

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by razinj** [comment]
It has been running just fine, one time on Google Search Console I noticed the sitemap issues (numbers didn't add up).
I tried un-publishing a page and a post and re-publishing them; but it didn't work, is there a way to re-generate the sitemap correctly!?

**Comment by RikoDEV** [comment]
I noticed that the sitemap is cleared when the docker container is restarted. After restart, it does not contain any data.

**Comment by razinj** [comment]
For me it doesn't change if I force restart/recreate the containers.

**Comment by razinj** [comment]
I don't really see how this improves SEO if GSC can't see the links in the sitemap, its a website index, it should list all URLs that matters.

Screenshot of my GSC:
<img width="1336" alt="screenshot 2023-05-11 at 19 43 21" src="https://github.com/TryGhost/Ghost/assets/37253974/6d039044-50a3-4400-9546-a484dd0c9ec4">

**Comment by daniellockyer** [comment]
Hmm, if a post has a canonical URL, we're essentially saying "this is the same as this other link", so we shouldn't include it in the sitemap. In which case, I believe this is working as expected 🙂
