### ISSUE TITLE
Scheduled post feature not available

### ISSUE THREAD

**Issue by phantomhell** [TryGhost/Ghost#16750]
### Issue Summary

I am new to Ghost, I've imported all my content from WP to Ghost. When I try to create a new post, there's no option for a scheduled feature, just publish time option. How to enable and activate scheduled feature?

### Steps to Reproduce

1. Go to Setting > General > Time setting: 07:00 GMT +7 Bangkok, Jakarta,
2. Go to post > Create new post > set time and date, then show a message: "Must be in the past".

### Ghost Version

5.4.70

### Node.js Version

16.20

### How did you install Ghost?

Installed Ghost using Ghost-CLI v1.24.0 on Ubuntu 22.04

### Database type

MySQL 8

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by designium** [comment]
it's not a problem, it's a UX issue. You have to post, then it will ask you if you want to post it now or later. 

I had the same issue as you had if you are running the latest version of Ghost.
