### ISSUE TITLE
Provide a nice message when missing content-type

### ISSUE THREAD

**Issue by K1D77A** [TryGhost/Ghost#16768]
### Issue Summary

When making a request to the admin API when missing the Content-Type header the returned info is not helpful at all.

### Steps to Reproduce

Make a request to the admin api without Content-Type (when you have json)

### Ghost Version

 5.47.0

### Node.js Version

18.3

### How did you install Ghost?

Ubuntu. Followed instructions on site.

### Database type

MySQL 8

### Relevant log / error output

```shell
"{\"errors\":[{\"message\":\"Validation error, cannot save post.\",\"context\":\"Validation failed for posts.\",\"type\":\"ValidationError\",\"details\":[{\"keyword\":\"required\",\"dataPath\":\"\",\"schemaPath\":\"#/required\",\"params\":{\"missingProperty\":\"posts\"},\"message\":\"should have required property 'posts'\"}],\"property\":\"posts\",\"help\":null,\"code\":null,\"id\":\"8bf362e0-ef27-11ed-ac4e-3fcc6b12757b\",\"ghostErrorCode\":null}]}"
(sorry its so ugly)
```

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by MMak1599** [comment]
I will give this a go.

**Comment by daniellockyer** [comment]
Do you have a reproduction case I can use?

**Comment by K1D77A** [comment]
> Do you have a reproduction case I can use?

Make a request to an admin endpoint that accepts a JSON body (for example creating a new post) and do not include the Content-Type header.
