### ISSUE TITLE
Can't render pt-br Portal Translations (beta)

### ISSUE THREAD

**Issue by sergiospagnuolo** [TryGhost/Ghost#16805]
### Issue Summary

In the new beta for Portal Translations, I am trying to use pt-br (Portuguese from Brazil) translations, but I keep getting pt (Portuguese from Portugal), which is somewhat different. I tried to wrap it up on quotes, but still get the same result. I think it might be some issue with the hyphen (I also tried without it).

There is a [pt-br translation in Github](https://github.com/TryGhost/Ghost/tree/main/ghost/i18n/locales/pt-br), and it looks fine to me.

### Steps to Reproduce

Portuguese from Portugal is `pt`, while Portuguese from Brazil is `pt-br`

1. I enabled Portal Translation (beta) in the Labs section
2. I went to the general section and wrote `pt-br` in the locales field
3. I am getting the `pt` translations, not `pt-br`

### Ghost Version

5.47.1

### Node.js Version

v16.19.1

### How did you install Ghost?

Digital Ocean droplet, with Ubuntu and Ghost CLI

### Database type

MySQL 5.7

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by daniellockyer** [comment]
I can also repro this issue, so I'll look into it 🙂

**Comment by daniellockyer** [comment]
Hey @sergiospagnuolo - I've found the issue and pushed a fix. It should be available in the next release 😀

**Comment by daniellockyer** [comment]
Yes apologies, we forgot to release a new version of Portal. Should be available this week 🙂
