### ISSUE TITLE
Filter menu for member activity behaves oddly

### ISSUE THREAD

**Issue by verement** [TryGhost/Ghost#16817]
### Issue Summary

Since 5.47.0, when viewing **Member activity**, the **Filter events** menu behaves oddly when the toggles are clicked. Each click causes the number of items in the menu to expand.

<img width="264" alt="Screen Shot 2023-05-17 at 3 42 27 PM" src="https://github.com/TryGhost/Ghost/assets/710176/7ee792b5-1277-48ca-837c-cd8c74017c97">
<img width="264" alt="Screen Shot 2023-05-17 at 3 43 09 PM" src="https://github.com/TryGhost/Ghost/assets/710176/2147c2de-2926-497b-9924-730fdc531693">

### Steps to Reproduce

1. Visit `/ghost/#/members-activity` in the admin area of the Ghost site.
2. Click on the **Filter events** menu button.
3. Click on any of the menu item toggles.
4. Observe the menu expand with dozens of duplicated items.

### Ghost Version

5.48.0

### Node.js Version

16.20.0

### How did you install Ghost?

Ubuntu 22.04.2

### Database type

MySQL 8

### Browser & OS version

Safari 16.4.1, macOS 12.6.5

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by daniellockyer** [comment]
Hey there, thank you so much for the detailed bug report.

That does look like something that shouldn't happen! A PR to fix this issue would be very welcome 🙂
