### ISSUE TITLE
Dark mode notice about Ghost(Pro) udpate has incorrect BG colour

### ISSUE THREAD

**Issue by stromfeldt** [TryGhost/Ghost#16819]
### Issue Summary

When in dark mode, the notice about Ghost(Pro) having been updated to the newest version has an incorrect background colour.

![Xnapper-2023-05-18-13 54 48](https://github.com/TryGhost/Ghost/assets/27488257/1071ea71-5394-47cc-b8b3-be50619ecb29)

### Steps to Reproduce

1. Set admin to dark mode
2. Wait for notice about update to come through

### Ghost Version

5.48.0+moya

### Node.js Version

Whatever Ghost(Pro) is using

### How did you install Ghost?

Ghost(Pro)

### Database type

MySQL 5.7

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by kasuncfdo** [comment]
Hi @minimaluminium the issue I found last month has been not fixed yet. 

In the Ghost admin panel's "Invite Staff Members" section, the contents of the hover box appear white in dark mode, and this issue still persists in the latest version, 5.49.0. It is crucial to address this problem and prioritize UI improvements for both dark and light modes.

![image](https://user-images.githubusercontent.com/84648368/230834285-6ce67879-77a7-410b-978a-52c85f062167.png)

**Comment by minimaluminium** [comment]
The fix for this has been included in [5.49.1](https://github.com/TryGhost/Ghost/releases/tag/v5.49.1). Thanks for the report @stromfeldt 🙂
