### ISSUE TITLE
Problem with filtering by tier visibility

### ISSUE THREAD

**Issue by fueko** [TryGhost/Ghost#16816]
### Issue Summary

Tiers are not rendered when filter="public" is used.

### Steps to Reproduce

Please use this sample code provided in [Ghost docs](https://ghost.org/docs/themes/helpers/get/#filtering-by-tier-visibility):

```
{{#get "tiers" filter="visibility:public"}}
    {{#foreach tiers}}
        <p>{{name}}</p>
    {{/foreach}}
{{/get}}
```

The result is no tiers rendered, then remove the filter and check again.

### Ghost Version

5.48.0

### Node.js Version

v16.13.0

### How did you install Ghost?

localhost

### Database type

SQLite3

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by daniellockyer** [comment]
This should now be fixed in https://github.com/TryGhost/Ghost/releases/tag/v5.48.1 🙂
