### ISSUE TITLE
Ghost very slow SQL query that breaks the website

### ISSUE THREAD

**Issue by alexandrucancescu** [TryGhost/Ghost#16829]
### Issue Summary

I setup Ghost on a VPS this week, and today I finished importing 100.000 posts from our old website expecting ghost not to struggle with this many posts. However after finishing the import I realised part of my website was not rendering, while the site was also loading very slow, min 5 seconds for every load. Even article pages are very slow.

I found in the ghost logs the initial problem. One of the helpers was triggering errors that I will attach in the **Relevant log / error output** section related to taking to much time. This error shows up on every single request. When the **get** helpers takes way too much to load there are sections on my homepage missing. I also uninstalled the theme I bought for my website ( Tripoli ) but there was no noticeable change.

I started to dig into the queries that Ghost does on the MySQL db, using performance schema and I found that two particular queries were very slow, one of them taking almost 3 seconds every time.

<img width="1140" alt="Screenshot 2023-05-18 at 21 28 52" src="https://github.com/TryGhost/Ghost/assets/26400994/4da37aa5-8c14-4913-944c-d4e67b8ad096">

This one takes 2.8 seconds to complete
```SQL
select count(distinct posts.id) as aggregate
from `posts`
where (`posts`.`status` = 'published' and (`posts`.`type` = 'post' and `posts`.`id` in
                       (select `posts_tags`.`post_id`
                                        from `posts_tags`
                                                 inner join `tags` on `tags`.`id` = `posts_tags`.`tag_id`
where `tags`.`slug` = 'eveniment')));

```
This one takes 1.8 seconds to complete.

```SQL
select `posts`.*
from `posts`
where (`posts`.`status` = 'published' and (`posts`.`type` = 'post' and `posts`.`id` in 
                                       (select `posts_tags`.`post_id`
                                        from `posts_tags`
                                                 inner join `tags` on `tags`.`id` = `posts_tags`.`tag_id`
                                        where `tags`.`slug` = 'sport')))
order by CASE WHEN posts.status = 'scheduled' THEN 1 WHEN posts.status = 'draft' THEN 2 ELSE 3 END ASC,
         CASE WHEN posts.status != 'draft' THEN posts.published_at END DESC, posts.updated_at DESC, posts.id DESC
limit 7;
```

And they are both triggered from the same HTTP request, so the wait time for a response is at least these 2 combined.

This led me to create a bigger MySQL instance on my provider, this helped a bit, it reduced the loading time of the homepage from 5-6 seconds to 3-4 seconds, which is still a very long loading time considering I have no traffic, my site is in private mode for now.

Even with the best cache, I risk caching a homepage that is broken if the helper takes to much to complete and some sections don't have data.

Is there any way I can solve this? Is ghost not supposed to be used for so many articles?

### Steps to Reproduce

Can't be easily reproduced

### Ghost Version

5.47.1

### Node.js Version

18.16.0

### How did you install Ghost?

Ubuntu 22 with auto generated SSL Nginx reverse proxy

### Database type

MySQL 8

### Browser & OS version

Irrelevant

### Relevant log / error output

```shell
[2023-05-18 18:20:05] WARN {{#get}} helper took 2087ms to complete
May 18 18:20:05 ghost-cms node[125467]:
May 18 18:20:05 ghost-cms node[125467]: {{#get}} helper took 2087ms to complete
May 18 18:20:05 ghost-cms node[125467]: Error ID:
May 18 18:20:05 ghost-cms node[125467]:     9d187510-f5a8-11ed-9797-bd314c9b7d7c
May 18 18:20:05 ghost-cms node[125467]: Error Code:
May 18 18:20:05 ghost-cms node[125467]:     SLOW_GET_HELPER
May 18 18:20:05 ghost-cms node[125467]: Details:
May 18 18:20:05 ghost-cms node[125467]:     api:          postsPublic.browse
May 18 18:20:05 ghost-cms node[125467]:     apiOptions:
May 18 18:20:05 ghost-cms node[125467]:       filter:  tags:eveniment
May 18 18:20:05 ghost-cms node[125467]:       context:
May 18 18:20:05 ghost-cms node[125467]:         member:
May 18 18:20:05 ghost-cms node[125467]:           uuid:          3a411d49-f098-438a-a104-422cf283db81
May 18 18:20:05 ghost-cms node[125467]:           email:         ***@gmail.com
May 18 18:20:05 ghost-cms node[125467]:           name:          ***
May 18 18:20:05 ghost-cms node[125467]:           firstname:     ***
May 18 18:20:05 ghost-cms node[125467]:           avatar_image:  https://www.gravatar.com/avatar/***?s=250&r=g&d=blank
May 18 18:20:05 ghost-cms node[125467]:           subscriptions:
May 18 18:20:05 ghost-cms node[125467]:             (empty array)
May 18 18:20:05 ghost-cms node[125467]:           paid:          false
May 18 18:20:05 ghost-cms node[125467]:           status:        free
May 18 18:20:05 ghost-cms node[125467]:     returnedRows: 15
May 18 18:20:05 ghost-cms node[125467]:
May 18 18:20:05 ghost-cms node[125467]: [2023-05-18 18:20:05] WARN {{#get}} helper took 2114ms to complete
May 18 18:20:05 ghost-cms node[125467]:
May 18 18:20:05 ghost-cms node[125467]: {{#get}} helper took 2114ms to complete
May 18 18:20:05 ghost-cms node[125467]: Error ID:
May 18 18:20:05 ghost-cms node[125467]:     9d1d08f0-f5a8-11ed-9797-bd314c9b7d7c
May 18 18:20:05 ghost-cms node[125467]: Error Code:
May 18 18:20:05 ghost-cms node[125467]:     SLOW_GET_HELPER
May 18 18:20:05 ghost-cms node[125467]: Details:
May 18 18:20:05 ghost-cms node[125467]:     api:          postsPublic.browse
May 18 18:20:05 ghost-cms node[125467]:     apiOptions:
May 18 18:20:05 ghost-cms node[125467]:       limit:   4
May 18 18:20:05 ghost-cms node[125467]:       include: tags,authors
May 18 18:20:05 ghost-cms node[125467]:       filter:  tags:social
May 18 18:20:05 ghost-cms node[125467]:       context:
May 18 18:20:05 ghost-cms node[125467]:         member:
May 18 18:20:05 ghost-cms node[125467]:           uuid:          3a411d49-f098-438a-a104-422cf283db81
May 18 18:20:05 ghost-cms node[125467]:           email:         ***@gmail.com
May 18 18:20:05 ghost-cms node[125467]:           name:          ***
May 18 18:20:05 ghost-cms node[125467]:           firstname:     ***
May 18 18:20:05 ghost-cms node[125467]:           avatar_image:  https://www.gravatar.com/avatar/***?s=250&r=g&d=blank
May 18 18:20:05 ghost-cms node[125467]:           subscriptions:
May 18 18:20:05 ghost-cms node[125467]:             (empty array)
May 18 18:20:05 ghost-cms node[125467]:           paid:          false
May 18 18:20:05 ghost-cms node[125467]:           status:        free
May 18 18:20:05 ghost-cms node[125467]:     returnedRows: 4
May 18 18:20:05 ghost-cms node[125467]:
May 18 18:20:05 ghost-cms node[125467]: [2023-05-18 18:20:05] WARN {{#get}} helper took 2205ms to complete
```

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by claptimes5** [comment]
I just had the same problem, without changing anything. For me, this was because my server's burst capacity as exhausted. I migrated my blog to a larger server and slow queries resolved.

**Comment by brvnnghi** [comment]
> I just had the same problem, without changing anything. For me, this was because my server's burst capacity as exhausted. I migrated my blog to a larger server and slow queries resolved.

May I know your server specs for such 100,000 post without lagging?

I have not approached that number, but [my photo site](https://www.hires.vn/) will soon reach that. Currently running on a Ghost(Pro) subscription, but I am going to migrate to a VPS instance for better database control.

Thanks.

**Comment by alexandrucancescu** [comment]
@cathysarisky I did try Casper, it also calls the slow queries. I also tries 3 server specs, now I switched to a 16GB RAM, 4 dedicated AMD Epyc Cores, and for now only Ghost and mysql run on it. Even with this setup it still takes over 5 seconds for the front page to load. 

In my opinion it is a bug, the front page breaks because I have a lot of articles, while there is no mention in any Ghost documentation that Ghost is not supposed to be used with such a large database.

**Comment by daniellockyer** [comment]
Hey @alexandrucancescu - thanks for the detailed bug report. We generally spec the performance of Ghost against a fewer number of posts, but we're constantly re-evaluating this given the size of sites we're starting to see. Performance is constantly on our radar but I can't give any guarantees as to when this specific issue will be improved

**Comment by alexandrucancescu** [comment]
Hi @daniellockyer! Thanks for your response. What would help most in my situation is a way to increase the time allowed for the helpers to complete their queries. That way I can be certain that the cached pages are not broken.

**Comment by daniellockyer** [comment]
@alexandrucancescu In that case, I can help you! You can add the following to your `config.production.json`:

```json
    "optimization": {
        "getHelper": {
            "timeout": {
                "threshold": 10000,
            }
        }
    },
```

or replace 10000 with whatever is appropriate for you 🙂

**Comment by alexandrucancescu** [comment]
Thanks!
