### ISSUE TITLE
Issue Building Tarball Archive

### ISSUE THREAD

**Issue by betschki** [TryGhost/Ghost#16835]
### Issue Summary

When I try to build Ghost from source (according to the [documentation](https://ghost.org/docs/install/source/#building-ghost-from-source)), I expect `yarn build` to produce a tarball archive, which can be installed with the CLI via the `--archive` flag.

As of recently (specifically [this commit](https://github.com/TryGhost/Ghost/commit/ed674981e6fb59cbcf2575cb3a694747fe1c57b3) in v5.47.0), the build script seems to have changed.

`yarn build` runs without issues, however, it does not produce the expected `ghost-<version>.tgz` archive anymore.

I have tried this in multiple different setups, with all releases since 5.47.0. Since the documentation has not changed, I assume that this is a bug (though this is my first bug report, so please let me know if I am doing something wrong).

### Steps to Reproduce

1. Clone repository onto local machine (`git clone --recurse-submodules https://github.com/TryGhost/Ghost.git`)
2. Switch to repository directory (`cd Ghost`)
3. Checkout current release branch (`git checkout v5.49.0`)
4. run `yarn setup`
5. run `yarn build`
6. build is successful, but no archive is produced

### Ghost Version

5.49.0

### Node.js Version

16

### How did you install Ghost?

from source on MacOS 13.1 (M1 Pro processor)

### Database type

SQLite3

### Relevant log / error output

```shell
yarn run v1.22.19
$ lerna run build
lerna notice cli v6.6.2

    ✔  @tryghost/post-revisions:build (4s)
    ✔  @tryghost/in-memory-repository:build (4s)
    ✔  @tryghost/collections:build (3s)
    ✔  @tryghost/portal:build (7s)
    ✔  @tryghost/admin-x-settings:build (7s)
    ✔  ghost:build (2s)
    ✔  @tryghost/announcement-bar:build (9s)
    ✔  @tryghost/sodo-search:build (11s)
    ✔  ghost-admin:build (1m)

 ——————————————————————————————————————————————————————————————————————————————————————————————————

 >  Lerna (powered by Nx)   Successfully ran target build for 9 projects (1m)
 
✨  Done in 83.33s.
```

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by daniellockyer** [comment]
Hey @betschki, good point! We had to change it to take into account some new requirements for building but I forgot that this worked for other things too.

A workaround you can do for now is to run `npm pack` from `ghost/core` (this is what all our internal tooling for releases and builds does)

**Comment by daniellockyer** [comment]
Hey @betschki 👋🏻 You can now run `yarn archive` and get the tarball back 🙂

**Comment by betschki** [comment]
@daniellockyer thank you for the update.

Just cloned a fresh version of v5.52.0, ran `yarn setup` and `yarn archive` – everything works, this is the final output I get:

```
...
npm notice === Tarball Details === 
npm notice name:          ghost                                   
npm notice version:       5.52.0                                  
npm notice filename:      ghost-5.52.0.tgz                        
npm notice package size:  8.9 MB                                  
npm notice unpacked size: 21.1 MB                                 
npm notice shasum:        d7fcbacf1c6586c6ac0d47ac519b49d20cd0b6f8
npm notice integrity:     sha512-kp6Lb9Dajwq/Z[...]x+WG1nZO2eU/Q==
npm notice total files:   1320                                    
npm notice 
ghost-5.52.0.tgz
✨  Done in 95.21s.
```

However, I cannot seem to find the actual `ghost-5.52.0.tgz` file anywhere. I searched all folders and subfolders.

Am I missing something or is there still an issue with this?

**Comment by muditjuneja** [comment]
Hi @daniellockyer, I am trying to make some changes in the admin UI, not the core. I tried 3 different tricks - 
1. ran npm pack inside the root ~~ `--archive` flag didn't work
2. ran npm pack from admin ui folder~~ `--archive` flag didn't work
3. ran npm pack from core ~~ `--archive` flag stuck the installation

Can you point me in the right direction?

**Comment by betschki** [comment]
@muditjuneja I have had a similar issue (fixed myself with a quick & dirty workaround), but saw that there were some recent changes in the package.json a in the 5.54.x releases.

I have now tried to make changes in the Ghost Admin, ran `yarn archive` in the root directory and got a tarball archive that can be installed via the Ghost CLI, including all the changes I have made.

So, seems to be fixed already :)
