### ISSUE TITLE
staff can create pages, but not save them

### ISSUE THREAD

**Issue by dm17** [TryGhost/Ghost#16876]
### Issue Summary

"Invite a new staff user" -> only lists priviledges related to posts, and there exist no page permissions in Ghost as far as I can see. Is this not essential for headless CMS functionality? If only the administrator can create pages, then each contributor, author, and editor needs to expressly ask the administrator to create the page they want to contribute before they can do anything.

It seems like relatively easy functionality for Ghost to add in the `Invite a new staff user` flow: to perhaps select if the permission applies to only posts (default) or pages as well (the point of this issue report).

### Steps to Reproduce

Invite anyone under a non-administrator permission. They add page. Then they experience the error: "Permission error, cannot save page. You do not have permission to add posts"

The second half of the error is incorrect because they are trying to add a page, not a post. The first half also kind of doesn't make sense because why can get create a page and then not be able to save it?

### Ghost Version

4.49 Docker Image

### Node.js Version

N/A

### How did you install Ghost?

Linux / Docker

### Database type

SQLite3

### Relevant log / error output

```shell
"Permission error, cannot save page. You do not have permission to add posts"
```

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by markstos** [comment]
Ghost is documented that Contributors and Authors can only create "posts". This appears to be a feature request to support "pages" for these categories as well. This is better submitted to "Ideas": https://forum.ghost.org/c/ideas/5

**Comment by dm17** [comment]
> Ghost is documented that Contributors and Authors can only create "posts". This appears to be a feature request to support "pages" for these categories as well. This is better submitted to "Ideas": https://forum.ghost.org/c/ideas/5
> 
> Ref: https://ghost.org/docs/staff/

1) Why? That seems unnecessarily inflexible and cumbersome
2) It is a bug because those staff can click page but never save them. At the very least that is confusing.
