### ISSUE TITLE
Staff should be available as authors before first login

### ISSUE THREAD

**Issue by dm17** [TryGhost/Ghost#16875]
### Issue Summary

As an admin, if you're setting up a staff member, for example, a contributor with a new account. Then the current process requires them to confirm before you can add them as an author, thus giving them access to edit the page.

This is a lot less convenient than it could be:
1) send invite
2) they login and see nothing
3) now you know they've accepted
4) now you can add them to pages they need to edit
5) now they can login and get to work

Even more ideal would be all staff getting access to published pages, but not necessarily access to edit them. If the pages are published, then it makes no sense that they have access to see them online but not within their ghost accounts - does it?

### Steps to Reproduce

Clear from summary above.

### Ghost Version

4.48.0

### Node.js Version

N/A

### How did you install Ghost?

Docker / Linux

### Database type

SQLite3

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by daniellockyer** [comment]
I'm closing this as a feature requests because this is currently working as expected. As the bot says, please post the idea on the forum and we'll take demand into consideration 🙂

**Comment by dm17** [comment]
@daniellockyer would you mind explaining your rational behind a useless button existing for all staff not being a bug? They can click new page, write on the new page, but will always get an error when trying to save it.
