### ISSUE TITLE
Hover Box Contents Visibility Issue in Dark Mode Admin Panel's "Invite a new Staff User" Popup

### ISSUE THREAD

**Issue by kasuncfdo** [TryGhost/Ghost#16882]
### Issue Summary

Hi, the issue I found last month has been not fixed yet. 

In the Ghost admin panel's "Invite Staff Members" section, the popup contents of the hover box appear white in dark mode, and this issue still persists in the latest version, 5.49.0. It is crucial to address this problem and prioritize UI improvements for both dark and light modes.

![image](https://user-images.githubusercontent.com/84648368/230834285-6ce67879-77a7-410b-978a-52c85f062167.png)
![image](https://github.com/TryGhost/Ghost/assets/84648368/46cfecde-0422-4fbf-bbad-b94976610f37)

### Steps to Reproduce

1. Set admin to the dark mode
2. Navigate to the "Invite Staff Members" section. This section is typically found in the settings on the staff of the admin panel.
3. Hover the icons next to the available options in the popup
4. Note that in dark mode, the content within the hover box appears white, making it difficult to read.

### Ghost Version

5.49.0

### Node.js Version

Latest

### How did you install Ghost?

Pikapods

### Database type

MySQL 8

### Browser & OS version

Chrome, Win 11

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by minimaluminium** [comment]
Hi @kasuncfdo, the fix for this has been included in 5.49.1. Make sure to update your Ghost site to that version.
