### ISSUE TITLE
Authors should not be allowed to create pages

### ISSUE THREAD

**Issue by EchoBilisim** [TryGhost/Ghost#16938]
### Issue Summary

Hello, people with author authority should not be allowed to create pages, if the author only has the option to add their content, it is sufficient if other administrators and editors have the ability to create pages.

When I add a user as an author, this added author has access to the page creation feature. This is a wrong event.

### Steps to Reproduce

![yazar](https://github.com/TryGhost/Ghost/assets/17055352/9d5708a9-5dfe-450c-bc97-1ac9e74a7ed9)

### Ghost Version

5.50.0

### Node.js Version

setup_16.x

### How did you install Ghost?

ubuntu 20.04

### Database type

MySQL 8

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by markstos** [comment]
Fixing this could also be considered a resolution for #16876 which notes that some roles can add a page but not save them.

**Comment by EchoBilisim** [comment]
> Fixing this could also be considered a resolution for #16876 which notes that some roles can add a page but not save them.

It is not correct for an author to add a page, the admin moderator can add it ok, but an author should not have an option to add a page, this is an incorrect process, the author just adds their content. This option is sufficient for an author.

**Comment by derek-adair** [comment]
Some people may want authors to be able to create pages.  Has there been any efforts/discussion regarding some kind of permissions module?

I am quite partial to how [django handles permissions](https://docs.djangoproject.com/en/4.2/topics/auth/default/#default-permissions). ([django.contrib.auth.models.Permission](https://github.com/django/django/blob/main/django/contrib/auth/models.py#L38)).  Something like this would allow developers to have fine-grained control over what users can do what.  Configurable [Groups](https://github.com/django/django/blob/main/django/contrib/auth/models.py#L38) would also be useful.

**Comment by EchoBilisim** [comment]
> Some people may want authors to be able to create pages. Has there been any efforts/discussion regarding some kind of permissions module?
> 
> I am quite partial to how [django handles permissions](https://docs.djangoproject.com/en/4.2/topics/auth/default/#default-permissions). ([django.contrib.auth.models.Permission](https://github.com/django/django/blob/main/django/contrib/auth/models.py#L38)). Something like this would allow developers to have fine-grained control over what users can do what. Configurable [Groups](https://github.com/django/django/blob/main/django/contrib/auth/models.py#L38) would also be useful.

It can be set as an option.  The sample author may have features such as what actions he can take.  Then everyone can set the authorization businesses as they want, this option will be more comprehensive and more useful.

**Comment by Pratik1603** [comment]
Please assign this to me

**Comment by derek-adair** [comment]
These action bots are awful.  WE KNOW @daniellockyer IS TRIAGING THE TICKET.  Beyond just annoying spam -- I've seen at least several valid issues or bug submissions closed erroneously.  Ya'll should really consider turning these off and appoint a community member to manually moderate this.  It is at a detriment to your project.

-------------------

@Pratik1603 if this is something you can contribute take initiative and submit a PR.
