### ISSUE TITLE
The [alt] button below featured images is no longer functional.

### ISSUE THREAD

**Issue by cathysarisky** [TryGhost/Ghost#16957]
### Issue Summary

After the latest Ghost updates, the button below featured images to put in alt text is no longer functional.

### Steps to Reproduce

Open the latest version of Ghost.
Add a post.
Add a featured image to the post.
Click the [alt] button next to the caption to switch to entering alt text.
Nothing happens.  I expected to be able to enter alt text.

The problem occurs in both the original and new beta editor.
The problem seems localized to featured images.  Other images are not impacted.

The problem is present in Chrome and Edge both.  No error messages are present in the browser console.

### Ghost Version

5.50-something

### Node.js Version

Ghost Pro

### How did you install Ghost?

Ghost Pro

### Database type

MySQL 8

### Browser & OS version

Chrome 114.0.5735.90 on Windows 10 AND Edge (recent version)

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by daniellockyer** [comment]
This is now fixed in v5.50.3 🙂
