### ISSUE TITLE
logo-loader.mp4 in dark mode has a white background

### ISSUE THREAD

**Issue by nyc-tinker** [TryGhost/Ghost#16974]
### Issue Summary

In the admin console there should be a different logo-loader.mp4 for dark mode since it uses the same one for both light mode and dark mode and so you have this white box around the logo as it plays while the background switches to dark mode.  Or have the light mode logo play and then stop playing and be removed from the screen just prior to when the dark mode background is loaded.

### Steps to Reproduce

Just go into the admin console and hit refresh.  The file seems to be located here:

ghost/admin/public/assets/videos/logo-loader.mp4

and locally at /var/www/[name-of-blog]/versions/5.50.4/core/built/admin/assets/videos/logo-loader.mp4

### Ghost Version

5.50.4

### Node.js Version

16.20.0

### How did you install Ghost?

local install.  on arch linux.  using nginx.

### Database type

Other

### Browser & OS version

chrome dev

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by hjain5164** [comment]
@daniellockyer I would like to work on this bug. Can I get started?

**Comment by minimaluminium** [comment]
The loading screen background color is white regardless of whether the Admin is in dark mode or not, so the background color of the video shouldn't be an issue.

If the issue reported here is same as https://github.com/TryGhost/Team/issues/3344, it's been fixed 🙂.
