### ISSUE TITLE
Broken counting of minutes to read when big base64 image on page

### ISSUE THREAD

**Issue by Dmitry-Lisichkin** [TryGhost/Ghost#16980]
### Issue Summary

I don't know how but on some of our pages was appear a several of images in base64 form:
`<img src="data:image/jpeg;base64 ......" alt="" />`
If image will be large enough (in our case it was just 2 images about 7Mb) then ghost can be completelly broken becouse it crash when try to count images for counting of minutes to read.
For now ghost tries to do it with this regex: `html.match(/<img(.|\n)*?>/g)`
Maybe this bug is related: #13278

### Steps to Reproduce

1. Add big base64 `<img>` as raw html
2. Publish article
3. Open main page or article.

### Ghost Version

5.49.3

### Node.js Version

v16.20.0

### How did you install Ghost?

docker ghost:5.49.3-alpine

### Database type

MySQL 8

### Relevant log / error output

```shell
RangeError: Maximum call stack size exceeded

at module.exports.prepareError (/var/lib/ghost/versions/5.49.3/node_modules/@tryghost/mw-error-handler/lib/mw-error-handler.js:92:19)
at String.match (<anonymous>)
at countImages (/var/lib/ghost/versions/5.49.3/node_modules/@tryghost/helpers/cjs/helpers.js:3593:18)
at readingMinutes (/var/lib/ghost/versions/5.49.3/node_modules/@tryghost/helpers/cjs/helpers.js:3623:22)
at Object.module.exports.forPost (/var/lib/ghost/versions/5.49.3/core/server/api/endpoints/utils/serializers/output/utils/extra-attrs.js:72:34)
at Object.module.exports [as posts] (/var/lib/ghost/versions/5.49.3/core/server/api/endpoints/utils/serializers/output/mappers/posts.js:35:16)
at Object.all (/var/lib/ghost/versions/5.49.3/core/server/api/endpoints/utils/serializers/output/posts.js:50:34)
at async sequence (/var/lib/ghost/versions/5.49.3/node_modules/@tryghost/promise/lib/sequence.js:16:22)
```

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by daniellockyer** [comment]
Hey there, thank you so much for the detailed bug report.

That does look like something that shouldn't happen! A PR to fix this issue would be very welcome 🙂

**Comment by luuu-xu** [comment]
@daniellockyer @Dmitry-Lisichkin Hi, I would like to work on this issue but I can't reproduce this bug on my local environment. What I did: created a new post, added a few pictures varying from 200Kb to 3Mb, format in png and jpeg, including dragging directly from Photos, and clicking on the plus icon when editing the post. The post preview at http://localhost:2368/ghost/#/editor/post/[postid] and the actual post at  http://localhost:2368/coming-soon/ do not have any <img> in base64 form.

**Comment by Dmitry-Lisichkin** [comment]
@luuu-xu Hey!. As i sayd I don't know how we had image in base64 form so on local environment I just add it as raw html block.
For convert bigger files you can use cli tools or converters based on javascript that run in browser (for example: https://stackoverflow.com/questions/17710147/image-convert-to-base64)
I'm not a javascript developer and have no much time but it seams that problem is only about regular expression, we do not need match group if we need only image count so this regular could be simplified to this: `/<img[^>]*>/` (not checked that it works).

**Comment by Dmitry-Lisichkin** [comment]
I think that I create issue on wrong repository. Related code placed in TryGhost/SDK https://github.com/TryGhost/SDK/blob/60ab3c7b73d1d7d92987b7eb3d8e73f920dd6800/packages/helpers/lib/utils/count-images.js#L15

**Comment by Dmitry-Lisichkin** [comment]
@luuu-xu I think that problem is about match group in regex so insted of several images use only one but with bigger size. In this case base64 in not need to be valid so just copypaste value in one src several times.
