### ISSUE TITLE
Code block's caption tags are escaped

### ISSUE THREAD

**Issue by E2RD0** [TryGhost/Ghost#17100]
### Issue Summary

When you include a caption for a code block in the new editor (haven't tried in the normal editor), even if you put only text, it is render with html tags escaped.

### Steps to Reproduce

1. Put a caption in a code block:
![imagen](https://github.com/TryGhost/Ghost/assets/20119863/afd0e3fc-4719-4ab6-82e8-4a0c29dcf3f4)
2. Then in the post it shows like this:
![imagen](https://github.com/TryGhost/Ghost/assets/20119863/ac469005-5899-4843-88ac-30d6e298ab9c)

### Ghost Version

5.52.2

### Node.js Version

16.17.0

### How did you install Ghost?

VM Ubuntu 22.04.1

### Database type

MySQL 8

### Browser & OS version

Firefox, Windows 11

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by RohitLakh** [comment]
This PR solved this issue.
PR: https://github.com/TryGhost/Koenig/pull/794

**Comment by kevinansfield** [comment]
@joeldesante, @RohitLakh Thanks for looking into this. Closing the issue as resolved via https://github.com/TryGhost/Koenig/pull/794
