### ISSUE TITLE
Newsletter clicks - update broken link not working for feedback links

### ISSUE THREAD

**Issue by disgustipated** [TryGhost/Ghost#17136]
### Issue Summary

updating a broken link works for the main header in newsletters, but the feedback links do not get updated.

### Steps to Reproduce

1. publish post that gets emailed
2. change post title and update "post url" on the post
3. both header link and the feedback links in the newsletter sent do not work resulting in a 404, but if you change the url manually in the browser they work
4. update the link by going to analytics on the post, then under newsletter clicks update the link to the corresponding post to the new link that was set in the "post url" on the post
5. in the same newsletter that was already emailed, clicking the header in the email will link to the new post url, but the feedback links at the bottom are not working in link to the old post url

### Ghost Version

5.53.1 docker latest

### Node.js Version

version included in 5.53.1 docker image

### How did you install Ghost?

docker

### Database type

MySQL 5.7

### Browser & OS version

chrome 114.0.5735.134

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by daniellockyer** [comment]
Hey there, thank you so much for the detailed bug report.

That does look like something that shouldn't happen! A PR to fix this issue would be very welcome 🙂

**Comment by disgustipated** [comment]
What is the functional usefulness of the ability to update the link in the analytics if it doesnt work?
