### ISSUE TITLE
Deleting a block cannot be properly undone if text is pasted in. Undo returns to the text replaced by the paste.

### ISSUE THREAD

**Issue by mfitzp** [TryGhost/Ghost#17130]
### Issue Summary

If you paste content into a block, e.g. /callout or \``` code blocks it doesn't seem to properly update the Undo history. Deleting the block & then immediately hitting Undo does not return the content of the block, but an earlier version of the block.

This can either result in returning to previous text (if any) or returning to an empty block, depending on what *has* ended up in the undo history. 

Below are two videos illustrating the two variants of the problem.

https://github.com/TryGhost/Ghost/assets/126239/ff322c75-a207-434c-b304-907bfd11d7c6

https://github.com/TryGhost/Ghost/assets/126239/2eb843bb-3d1c-4b6a-9d69-38f80969bec6

There is a risk here of losing/needing to rewrite content which isn't fun.

Thanks!

### Steps to Reproduce

1. Write some text
2. Add a callout on the next line and enter some text
3. Write some more text
4. Paste text into the callout block
5. Move to the beginning of the line after the callout and hit backspace, the callout will disappear
6. Undo (Ctrl-Z) the block will return but the content is not restored

### Ghost Version

Ghost Pro (hosted)

### Node.js Version

Unknown

### How did you install Ghost?

Ghost Pro (hosted)

### Database type

MySQL 5.7

### Browser & OS version

Chrome 12.0.5615.138 / Windows 11

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by mfitzp** [comment]
Having experimented a bit further, this behavior also affects code blocks.

**Comment by RohitLakh** [comment]
@mfitzp It would be helpful if you can specify if you are using the `beta editor` or the `old editor`.

**Comment by SamarthBagga** [comment]
@RohitLakh thank you ill start working on it.

**Comment by SamarthBagga** [comment]
It seems like there is no code to handle the undo behavior in the editor, thus it relies on the browser's native undo functionality. I am thinking of adding a custom undo function handler specifically for the callout and code blocks. Is this an acceptable fix ?

**Comment by mfitzp** [comment]
@RohitLakh this is on the old editor. I'd just set up on Ghost Pro so wasn't aware there were two options. 

Having tried it just now, the good news is I can't reproduce this in the beta editor.

**Comment by 9larsons** [comment]
We don't have much appetite to resolve this given we're working hard to move the beta editor out of beta. 

@SamarthBagga if you would like to submit a PR, I can take a look. However if you're just looking to contribute in some fashion - not specifically this issue - I'd recommend checking out another given that we're actively working to phase out mobiledoc.

**Comment by markstos** [comment]
I recommend closing this as wont-fix, given that there's a reasonable workaround of switching to the new editor.
