### ISSUE TITLE
CTRL+H key doesn't work in the new Editor (Chrome 114.0.5735.134 Win 11)

### ISSUE THREAD

**Issue by Marfa** [TryGhost/Ghost#17147]
### Issue Summary

CTRL+H key works fine in the old version of editor. But in the new version it opens Chrome's history instead of change headings.

### Steps to Reproduce

1. Select any text
2. Use CTRL+H key

### Ghost Version

Ghost(Pro)

### Node.js Version

-

### How did you install Ghost?

-

### Database type

MySQL 5.7

### Browser & OS version

Chrome 114.0.5735.134 Win 11

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by joeldesante** [comment]
Hi, I've tried to reproduce this issue using the latest version of Ghost on Chrome v114.0.5735.198 but was unsuccessful. I am on Mac, however, so I will try later on a Windows device. Are you still experiencing this issue? Have you tried any other browsers?

**Comment by Marfa** [comment]
I have same issue in Firefox 114.0.2.

**Comment by joeldesante** [comment]
> I have same issue in Firefox 114.0.2.

Hi, I was able to jump onto a windows device to try and replicate this issue on both Firefox and Chrome, but I was not able to do so. 

However, I did notice that Ctrl+H does open the history tab when the title field in the editor is focused. It makes sense that the title field would not handle the Ctrl+H shortcut however.

Can you please verify that you are not focused on the title field and are in fact focused on the content area of the editor? And if you are in the content area, maybe you can check your browsers settings to see if there is something causing this issue for you there?

**Comment by Marfa** [comment]
I'm sure that the focus is not on the title field. I have this issue in Chrome and Firefox in incognito mode. I use the default setting in FF.

Here's the video https://youtu.be/mEzMwsutgg8

**Comment by joeldesante** [comment]
> I'm sure that the focus is not on the title field. I have this issue in Chrome and Firefox in incognito mode. I use the default setting in FF.
> 
> Here's the video https://youtu.be/mEzMwsutgg8

This is very interesting. Maybe this is an issue relevant to Ghost Pro specifically. I don't have a Ghost Pro subscription so I can't try replicating the issue that way. Is there any way you can find the exact version of Ghost that you are running?

**Comment by joeldesante** [comment]
> Are you sure you tried this on the new editor https://ghost.org/changelog/editor-beta/? I'm on Version: [5.53.4+moya]

Ah! That was my issue! I enabled the new editor in the Labs area in the admin panel. However, I still can not replicate this issue. However, once again I am on Mac so I will try on Windows and then update this message with the results.
