### ISSUE TITLE
Plaintext field for signup cards needs work

### ISSUE THREAD

**Issue by cathysarisky** [TryGhost/Ghost#17168]
### Issue Summary

The new Lexical editor sign-up card has fairly poor/nonsensical output when converted to plaintext.  Here's what I get from the API when I ask for that post's plaintext:
`{"plaintext":"\n\n\n\n\n\n\n\nSign up for Demo Content\n\n\n\nThoughts, stories and ideas.\n\n\n\n\n\n\n\n\nSubscribe\n\n\n\n\n\n\n\n\n\n\n\n\n\nEmail sent! Check your inbox to complete your signup.\n\n\n\n\n\n\nNo spam. Unsubscribe anytime.\n\n\n\n\n\nYes, definitely in the beta editor now!\n\n\n"}`
(Everything before 'Yes' is the sign-up card.)

### Steps to Reproduce

Create a post with a sign-up card.  Request the text from the content API.

### Ghost Version

5.53.2+moya, Ghost Pro

### Node.js Version

on Ghost Pro

### How did you install Ghost?

Ghost Pro

### Database type

MySQL 8

### Browser & OS version

Chrome, Windows 10

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by Tisha211** [comment]
> ### Issue Summary
> The new Lexical editor sign-up card has fairly poor/nonsensical output when converted to plaintext. Here's what I get from the API when I ask for that post's plaintext: `{"plaintext":"\n\n\n\n\n\n\n\nSign up for Demo Content\n\n\n\nThoughts, stories and ideas.\n\n\n\n\n\n\n\n\nSubscribe\n\n\n\n\n\n\n\n\n\n\n\n\n\nEmail sent! Check your inbox to complete your signup.\n\n\n\n\n\n\nNo spam. Unsubscribe anytime.\n\n\n\n\n\nYes, definitely in the beta editor now!\n\n\n"}` (Everything before 'Yes' is the sign-up card.)
> 
> ### Steps to Reproduce
> Create a post with a sign-up card. Request the text from the content API.
> 
> ### Ghost Version
> 5.53.2+moya, Ghost Pro
> 
> ### Node.js Version
> on Ghost Pro
> 
> ### How did you install Ghost?
> Ghost Pro
> 
> ### Database type
> MySQL 8
> 
> ### Browser & OS version
> Chrome, Windows 10
> 
> ### Relevant log / error output
> _No response_
> 
> ### Code of Conduct
> * [x]  I agree to be friendly and polite to people in this repository

**Comment by cathysarisky** [comment]
Also seeing issues with the post excerpt generation pulling the signup text.  

This might have been fixed by a recent merge? https://github.com/TryGhost/Ghost/pull/17163 ,  Will retest once live.

**Comment by SimonBackx** [comment]
Hey @cathysarisky! Thanks for creating this issue. We removed the signup card from the plaintext and excerpt in `v5.53.3`. I think this fixes this issue, as there is probably no value to have it in the plaintext version of posts 😊
