### ISSUE TITLE
Posts created with Lexical editor are not editable after being imported - they end up with both mobiledoc and lexical fields set

### ISSUE THREAD

**Issue by cathysarisky** [TryGhost/Ghost#17167]
### Issue Summary

Posts created with Lexical editor are not editable after being imported - they end up with both mobiledoc and lexical fields set.

It looks like there's a problem with the Ghost import function.  Posts created in the new Lexical editor and exported contain lexical (and html and plaintext) fields, with mobiledoc set to null.  That looks correct.  HOWEVER, upon import of the Ghost-exported .json, those Lexical-created posts end up with both mobiledoc and lexical fields set.  

This is causing the posts to not display their {{content}} on the front end - the post is imported and title and featured image can be seen, but {{content}} cannot.  It also makes it impossible to edit the post, because the the error message "Validation error, cannot edit post. Posts can have either a mobiledoc or a lexical property, never both. Both the mobiledoc and lexical properties are set, one must be null" appears upon saving or autosaving.

### Steps to Reproduce

Switch to the lexical editor.  Create a post.
Export.
Import.
Attempt to view or edit that post.

**Correct export:**
```
"mobiledoc": null,
                        "lexical": "{\"root\":{\"children\":[{\"type\":\"signup\",\"version\":1,\"alignment\":\"left\",\"backgroundColor\":\"#F0F0F0\",\"backgroundImageSrc\":\"\",\"backgroundSize\":\"cover\",\"textColor\":\"#000000\",\"buttonColor\":\"accent\",\"buttonTextColor\":\"#FFFFFF\",\"buttonText\":\"Subscribe\",\"disclaimer\":\"<span>No spam. Unsubscribe anytime.</span>\",\"header\":\"<span>Sign up for Demo Content</span>\",\"labels\":[],\"layout\":\"wide\",\"subheader\":\"<span>Thoughts, stories and ideas.</span>\",\"successMessage\":\"Email sent! Check your inbox to complete your signup.\",\"swapped\":false},{\"children\":[{\"detail\":0,\"format\":0,\"mode\":\"normal\",\"style\":\"\",\"text\":\"Yes, definitely in the beta editor now!\",\"type\":\"text\",\"version\":1}],\"direction\":\"ltr\",\"format\":\"\",\"indent\":0,\"type\":\"paragraph\",\"version\":1},{\"children\":[],\"direction\":\"ltr\",\"format\":\"\",\"indent\":0,\"type\":\"paragraph\",\"version\":1}],\"direction\":\"ltr\",\"format\":\"\",\"indent\":0,\"type\":\"root\",\"version\":1}}",
```

**Export after importing and then exporting again (just to confirm that yes, both fields are populated)**
```
"mobiledoc": "{\"version\":\"0.3.1\",\"atoms\":[],\"cards\":[],\"markups\":[],\"sections\":[[1,\"h2\",[[0,[],0,\"Sign up for Demo Content\"]]],[1,\"h3\",[[0,[],0,\"Thoughts, stories and ideas.                                                      Subscribe                                                                                                                                .nc-loop-dots-4-24-icon-o{--animation-duration:0.8s} .nc-loop-dots-4-24-icon-o *{opacity:.4;transform:scale(.75);animation:nc-loop-dots-4-anim var(--animation-duration) infinite} .nc-loop-dots-4-24-icon-o :nth-child(1){transform-origin:4px 12px;animation-delay:-.3s;animation-delay:calc(var(--animation-duration)/-2.666)} .nc-loop-dots-4-24-icon-o :nth-child(2){transform-origin:12px 12px;animation-delay:-.15s;animation-delay:calc(var(--animation-duration)/-5.333)} .nc-loop-dots-4-24-icon-o :nth-child(3){transform-origin:20px 12px} @keyframes nc-loop-dots-4-anim{0%,100%{opacity:.4;transform:scale(.75)}50%{opacity:1;transform:scale(1)}}                                                                     Email sent! Check your inbox to complete your signup.\"]]],[1,\"p\",[[0,[],0,\"No spam. Unsubscribe anytime.\"]]],[1,\"p\",[[0,[],0,\"Yes, definitely in the beta editor now!\"]]]]}",
                        "lexical": "{\"root\":{\"children\":[{\"type\":\"signup\",\"version\":1,\"alignment\":\"left\",\"backgroundColor\":\"#F0F0F0\",\"backgroundImageSrc\":\"\",\"backgroundSize\":\"cover\",\"textColor\":\"#000000\",\"buttonColor\":\"accent\",\"buttonTextColor\":\"#FFFFFF\",\"buttonText\":\"Subscribe\",\"disclaimer\":\"<span>No spam. Unsubscribe anytime.</span>\",\"header\":\"<span>Sign up for Demo Content</span>\",\"labels\":[],\"layout\":\"wide\",\"subheader\":\"<span>Thoughts, stories and ideas.</span>\",\"successMessage\":\"Email sent! Check your inbox to complete your signup.\",\"swapped\":false},{\"children\":[{\"detail\":0,\"format\":0,\"mode\":\"normal\",\"style\":\"\",\"text\":\"Yes, definitely in the beta editor now!\",\"type\":\"text\",\"version\":1}],\"direction\":\"ltr\",\"format\":\"\",\"indent\":0,\"type\":\"paragraph\",\"version\":1},{\"children\":[],\"direction\":\"ltr\",\"format\":\"\",\"indent\":0,\"type\":\"paragraph\",\"version\":1}],\"direction\":\"ltr\",\"format\":\"\",\"indent\":0,\"type\":\"root\",\"version\":1}}",
```

### Ghost Version

5.53.2+moya, Ghost Pro

### Node.js Version

Ghost Pro

### How did you install Ghost?

Ghost Pro

### Database type

MySQL 8

### Browser & OS version

Chrome, Windows 10

### Relevant log / error output

```shell
Validation error, cannot edit post. Posts can have either a mobiledoc or a lexical property, never both. Both the mobiledoc and lexical properties are set, one must be null
```

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by cathysarisky** [comment]
Update from a little digging around:
I think the guilty party is here: https://github.com/TryGhost/Ghost/blob/main/ghost/core/core/server/data/importer/importers/data/PostsImporter.js

The problem is in the block of code starting at line 222.  There's a check for some very old import formats, but no mention of lexical at all.  Looks like someone missed adding lexical to this implementation when the beta editor went in?

Line 240: ```if (model.mobiledoc) { // a bunch of mobiledoc import stuff happens```
but then...
Line 275: ```} else if (model.html) { // converts the html to mobiledoc ```

Since lexical posts export with their html field populated, this results in posts getting imported that have both mobiledoc and lexical.

**Comment by daniellockyer** [comment]
This should now be fixed with https://github.com/TryGhost/Ghost/commit/fc7e150cc2537f8ed0545fd1e754382eb611b415 🙂
