### ISSUE TITLE
Premission to publish "Ghost" app in Umbrel App store

### ISSUE THREAD

**Issue by IMPranshu** [TryGhost/Ghost#17170]
### Issue Summary

Hi team,

I need your team's permission to try and host this app on the Umbrel App Store. I have given appropriate credits and mentions to your team as you are the sole Developer of the App I am just publishing it to the Umbrel App Store for free as I have done with a lot of other OSS applications.

It would be great to have a go-ahead from your team as I have already created a PR https://github.com/getumbrel/umbrel-apps/pull/268 for this but it has been closed as I was not the developer of this application

Thanks,
Pranshu

### Steps to Reproduce

NA

### Ghost Version

NA

### Node.js Version

NA

### How did you install Ghost?

NA

### Database type

MySQL 5.7

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by daniellockyer** [comment]
Hi @IMPranshu - we only use GitHub to track bugs within Ghost. I'd suggest you contact us via the email address on https://ghost.org/contact/ to get further with this 🙂
