### ISSUE TITLE
Typo in signup card error message

### ISSUE THREAD

**Issue by stromfeldt** [TryGhost/Ghost#17233]
### Issue Summary

Upon customising the new signup card in a local installation I inadvertently noticed while styling the error message(s) that there's a slight typo. I believe there should be a comma after "attempts".

![Xnapper-2023-07-07-10 55 38](https://github.com/TryGhost/Ghost/assets/27488257/bfd11282-81c9-400a-a760-64f371ccf6c5)

### Steps to Reproduce

1. In an installation improperly set up so that it won't send emails, keep trying sending out emails.
2. Eventually you'll be told that you've made too many attempts.
3. See typo.

### Ghost Version

5.53.4

### Node.js Version

-

### How did you install Ghost?

-

### Database type

MySQL 5.7

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by neshvig10** [comment]
fixed it

**Comment by luizfboss** [comment]
Hello! May I work on it?
