### ISSUE TITLE
Wrong email sender address when changing support email address in `Customize Portal`

### ISSUE THREAD

**Issue by wangx1ng** [TryGhost/Ghost#17244]
### Issue Summary

When changing the support email address in the Customized portal setting (Settings → Membership →Portal Settings[Customize portal])

![image](https://github.com/TryGhost/Ghost/assets/4630628/11a65a08-6069-48e3-8f99-2204dbb1e99e)

If you input an email address that has a different domain from your ghost site, say, your ghost site has a domain of `myghostsite.com` and you want to set `myblog@gmail.com` as the support email. this process needs an email confirmation so the ghost backend will send an email to the address you inputted, however, the sender address of this email will be set to a meaningless `noreply@gmail.com` while the correct one should be `noreply@myghostsite.com` which we set in the emailing service setting.

If you change the support email to another domain, say `myblog@hotmail.com`, you can observe in your email service log that the sender has been set to `noreply@hotmail.com`. It seems that the email sender domain name corresponds to the domain of the email address you input.

further info:
https://forum.ghost.org/t/wrong-email-sender-when-changing-support-email-address/39639

### Steps to Reproduce

1. Set up a normal ghost site and configure email service(don't change the email sender address config so it will by default be `noreply@myghostsite.com`).
2. Change the support email address in the Customized portal setting, input an email address that has a different domain name from your site, e.g. `myblogsupport@gmail.com`, and click save.
3. Observe the service log in the dashboard of your transactional email service provider, a wrong sender address of `noreply@gmail.com` should be observed in the activity log.

### Ghost Version

5.53.4

### Node.js Version

v18.16.1

### How did you install Ghost?

Ubuntu 22.04.2 LTS (GNU/Linux 5.15.0-76-generic x86_64)

### Database type

MySQL 8

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by bonik21** [comment]
in Docker image 5.54.0 (Last pushed 13 minutes ago) it's still not fixed
Use This File
https://github.com/TryGhost/Ghost/blob/5493c0fbbfcd163655a0d4797c8cf5853c82e9c6/ghost/core/core/server/services/mail/GhostMailer.js
path : /var/lib/ghost/current/core/server/services/mail/GhostMailer.js

docker-compose.yml example:
```
   volumes:      
      - './content:/var/lib/ghost/content'
      - './GhostMailer.js:/var/lib/ghost/current/core/server/services/mail/GhostMailer.js'
```

**Comment by MFYDev** [comment]
Do not know why everything related to this issue is closed, the issue is still happening https://github.com/TryGhost/Ghost/issues/21423
![image](https://github.com/user-attachments/assets/5c826d36-0a44-4ce5-8597-b21e135d77cc)
