### ISSUE TITLE
Blogging issue: Content disappearing on Safari when typing non-English

### ISSUE THREAD

**Issue by teddyfullstack** [TryGhost/Ghost#17277]
### Issue Summary

Content disappears when typing non-English characters on Safari using the Ghost editor, specifically on bullets and callouts.  The issue is not present on Google Chrome.

### Steps to Reproduce

1. Use the ghost editor to write a blog post on Safari.
2. Type in some Vietnamese letters (using MacOS's default **Simple Telex** input source).
3. Notice that the content on bullets and callouts disappears. If the auto-save process finishes, any lost content is permanently lost, so you need to quickly press "refresh" to prevent this from happening.

Expected:
3. The content on other sections of the page should stay the same, just like it works on Google Chrome.

### Ghost Version

5.2.3

### Node.js Version

Not sure

### How did you install Ghost?

My company set it up

### Database type

MySQL 5.7

### Browser & OS version

Safari 17.0

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by daniellockyer** [comment]
Ghost 5.2.3 is an old version of Ghost and I'd certainly suggest updating to the latest.

You also might want to consider switching to the beta editor: https://ghost.org/changelog/editor-beta/ 🙂

**Comment by teddyfullstack** [comment]
Thank you for replying 👍
