### ISSUE TITLE
Ghost throws notice of wrong email configuration while it's configured correctly and is working

### ISSUE THREAD

**Issue by damirissimo** [TryGhost/Ghost#17339]
### Issue Summary

The issue is described thoroughly at Ghost CMS Forum: https://forum.ghost.org/t/ghost-is-currently-unable-to-send-email-notification/38687

In short: Ghost admin shows:

> Update available!
> Ghost is currently unable to send email. See https://ghost.org/docs/concepts/config/#mail for instructions

There are two errors:
1. There is no Ghost CMS update available. I'm using 5.54.0, which is [the latest](https://github.com/TryGhost/Ghost/releases/tag/v5.54.0) as for now
2. Emails are configured correctly. I can send emails to my subscribers (via mailgun), i can receive ghost notices when I have new subscribers signing up, I can change newsletter from email, I can change portal support email. 

[This line of source code](https://github.com/TryGhost/Ghost/blob/6f47002f9de133661391c0d8588147991670f4a2/ghost/core/core/server/api/endpoints/mail.js#L18) assumes you're using Direct email service, which I am not using in my case.

```
"mail": {
    "from": "join@domain.com",
    "transport": "SMTP",
    "options": {
      "service": "Mailgun",
      "host": "smtp.eu.mailgun.org",
      "port": 465,
      "secure": true,
      "auth": {
        "user": "name@subdomain.domain.com",
        "pass": "passwordliveshere"
      }
    }
  },
```

### Steps to Reproduce

1. Configure Ghost emails correctly
2. Receive incorrect notice :)

### Ghost Version

5.54.0

### Node.js Version

18.16.1

### How did you install Ghost?

Ubuntu

### Database type

MySQL 8

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by phantomhell** [comment]
Ignore this notice if you're have correct configuration. I've often saw this notice and ignore it.

**Comment by markstos** [comment]
@damirissimo I see the line of code you linked to:

https://github.com/TryGhost/Ghost/blob/6f47002f9de133661391c0d8588147991670f4a2/ghost/core/core/server/api/endpoints/mail.js#L18

But I don't see why it assumes you are using direct mail. The call is using the Node Mailer API, which supports a number of different transports besides SMTP:

https://github.com/TryGhost/Ghost/blob/6f47002f9de133661391c0d8588147991670f4a2/ghost/core/core/server/api/endpoints/mail.js#L18

**Comment by daniellockyer** [comment]
Hey @damirissimo - did you see any other logs for this? I'm unsure why it thinks you're using Direct transport, unless we have a bug lingering around somewhere?
