### ISSUE TITLE
Download/delete theme buttons have white "border" in dark mode

### ISSUE THREAD

**Issue by stromfeldt** [TryGhost/Ghost#17342]
### Issue Summary

While in dark mode, if you try to download or delete a theme a white "border" exists at the top of the selection box as well as the bottom left and right corners.

![Xnapper-2023-07-13-10 34 37](https://github.com/TryGhost/Ghost/assets/27488257/df00d48b-735a-4478-8656-0b143f91e03a)

![Xnapper-2023-07-13-10 39 11](https://github.com/TryGhost/Ghost/assets/27488257/20f638d3-b413-4f67-a035-dc9ea242fb70)

### Steps to Reproduce

1. Switch to dark mode
2. Try to download or delete a theme
3. See white "borders"

### Ghost Version

5.54.0

### Node.js Version

?

### How did you install Ghost?

Ghost(Pro)

### Database type

MySQL 5.7

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by devvrat011** [comment]
sir plss assign this to me. I can resolve the bug and fix this.
thank you

**Comment by Pratik1603** [comment]
Please assign this to me

**Comment by LingpengXiao** [comment]
Hi, can I work on this issue?

**Comment by stromfeldt** [comment]
This issue has been obviated by the new editor, so I'm closing it.
