### ISSUE TITLE
Some image sizes created as 0 byte files

### ISSUE THREAD

**Issue by jlopp** [TryGhost/Ghost#17379]
### Issue Summary

I've published 100+ articles on my self hosted Ghost instance and this is the first time I've encountered this issue. Not sure how to easily reproduce it, nor have I managed to find any logged errors to indicate what went wrong.

The ultimate culprit is that **something** went wrong during the publication process that resulted in SOME of the image versions (at certain sizes) being created as 0 byte files:

```
# ls -la /var/www/ghost/content/images/size/w1600/2023/07/
total 664
drwxr-xr-x 2 ghost ghost   4096 Jul 15 14:57 .
drwxr-xr-x 4 ghost ghost   4096 Jul 15 14:56 ..
-rw-r--r-- 1 ghost ghost      0 Jul 15 14:58 buried_seed_vault.jpg
-rw-r--r-- 1 ghost ghost      0 Jul 15 14:58 clean_seed_vault.jpg
-rw-r--r-- 1 ghost ghost 448178 Jul 15 14:57 dirty_seed_vault.jpg
-rw-r--r-- 1 ghost ghost      0 Jul 15 14:58 opened_seed_vault.jpg
-rw-r--r-- 1 ghost ghost 219594 Jul 15 14:56 seed_plates.jpg
-rw-r--r-- 1 ghost ghost      0 Jul 15 14:58 tamper_evident_bag.jpg
```

I was able to manually resolve the issue by copying the original files over the 0 byte versions. But I haven't been able to find the root cause of this failure.

### Steps to Reproduce

Here's what happened today:

1. I had a ~1,000 word article with half a dozen fairly large images uploaded into it
2. I hit the publish button and it sent the newletter out to several thousand subscribers
3. Immediately upon publishing, the CPU usage on the machine spiked to 100% and nginx / the web site became unresponsive
4. This continued for 15 - 20 minutes before the issue resolved itself and the site came back online

After everything came back online I thought the post was fine because it rendered as expected in my laptop browser. However, I later noticed that half of the images were broken when viewing the email or viewing the site in a mobile browser.

### Ghost Version

5.44.0

### Node.js Version

14.21.3

### How did you install Ghost?

Ubuntu, v22.04.2 LTS

### Database type

MySQL 8

### Browser & OS version

Vanadium & Android, Safari & iOS

### Relevant log / error output

```shell
{"name":"Log","hostname":"localhost","pid":2452,"level":30,"version":"5.44.0","msg":"Adding one-off job to queue with current length = 0 called 'sendWebmentions'","time":"2023-07-15T14:56:51
.636Z","v":0}
{"name":"Log","hostname":"localhost","pid":2452,"level":30,"version":"5.44.0","msg":"[Webmention] Sending all webmentions for https://blog.lopp.net/how-bury-bitcoin-seed-phrase-backup/","tim
e":"2023-07-15T14:56:51.662Z","v":0}
{"name":"Log","hostname":"localhost","pid":2452,"level":30,"version":"5.44.0","msg":"Adding one-off job to queue with current length = 0 called 'batch-sending-service-job'","time":"2023-07-1
5T14:56:51.700Z","v":0}
{"name":"Log","hostname":"localhost","pid":2452,"level":30,"version":"5.44.0","msg":"Starting email job for email 64b2b3b38e3d8d0994477ef4","time":"2023-07-15T14:56:51.712Z","v":0}
{"name":"Log","hostname":"localhost","pid":2452,"level":30,"version":"5.44.0","req":{"meta":{"requestId":"9899fbe3-920f-4f7a-801e-d05a249a1d93","userId":"1"},"url":"/posts/64a2fc448e3d8d0994477cf4/?formats=mobiledoc%2Clexical&newsletter=default-newsletter&email_segment=all","method":"PUT","originalUrl":"/ghost/api/admin/posts/64a2fc448e3d8d0994477cf4/?formats=mobiledoc%2Clexical&newsletter=default-newsletter&email_segment=all","params":{"id":"64a2fc448e3d8d0994477cf4"},"headers":{"x-forwarded-for":"5.161.186.122","x-forwarded-proto":"https","x-real-ip":"5.161.186.122","host":"blog.lopp.net","connection":"close","content-length":"14456","sec-ch-ua":"\"Not.A/Brand\";v=\"8\", \"Chromium\";v=\"114\", \"Brave\";v=\"114\"","dnt":"1","sec-ch-ua-mobile":"?0","app-pragma":"no-cache","user-agent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36","content-type":"application/json; charset=UTF-8","accept":"application/json, text/javascript, */*; q=0.01","x-requested-with":"XMLHttpRequest","x-ghost-version":"5.44","sec-ch-ua-platform":"\"Linux\"","sec-gpc":"1","origin":"https://blog.lopp.net","sec-fetch-site":"same-origin","sec-fetch-mode":"cors","sec-fetch-dest":"empty","referer":"https://blog.lopp.net/ghost/","accept-encoding":"gzip, deflate, br","accept-language":"en-US,en;q=0.9","cookie":"**REDACTED**"},"query":{"formats":"mobiledoc,lexical","newsletter":"default-newsletter","email_segment":"all"}},"res":{"_headers":{"x-powered-by":"Express","content-version":"v5.44","vary":"Accept-Version, Origin, Accept-Encoding","cache-control":"no-cache, private, no-store, must-revalidate, max-stale=0, post-check=0, pre-check=0","access-control-allow-origin":"https://blog.lopp.net","x-cache-invalidate":"/*","content-type":"application/json; charset=utf-8","etag":"W/\"6f61-1X2mHp3ZWSs8ZR4AiFAYIE7WRRo\"","content-encoding":"gzip"},"statusCode":200,"responseTime":"203ms"},"msg":"","time":"2023-07-15T14:56:51.724Z","v":0}
{"name":"Log","hostname":"localhost","pid":2452,"level":30,"version":"5.44.0","msg":"Sending email 64b2b3b38e3d8d0994477ef4","time":"2023-07-15T14:56:51.737Z","v":0}
{"name":"Log","hostname":"localhost","pid":2452,"level":30,"version":"5.44.0","msg":"Getting batches for email 64b2b3b38e3d8d0994477ef4","time":"2023-07-15T14:56:51.746Z","v":0}
{"name":"Log","hostname":"localhost","pid":2452,"level":30,"version":"5.44.0","msg":"Creating batches for email 64b2b3b38e3d8d0994477ef4","time":"2023-07-15T14:56:51.756Z","v":0}
{"name":"Log","hostname":"localhost","pid":2452,"level":30,"version":"5.44.0","msg":"Creating batches for email 64b2b3b38e3d8d0994477ef4 segment null","time":"2023-07-15T14:56:51.765Z","v":0}
{"name":"Log","hostname":"localhost","pid":2452,"level":30,"version":"5.44.0","msg":"Fetching members batch for email 64b2b3b38e3d8d0994477ef4 segment null, lastId: 64b2b3b38e3d8d0994477ef4","time":"2023-07-15T14:56:51.765Z","v":0}
{"name":"Log","hostname":"localhost","pid":2452,"level":30,"version":"5.44.0","msg":"Creating batch for email 64b2b3b38e3d8d0994477ef4 segment null with 1000 members","time":"2023-07-15T14:56:51.785Z","v":0}
{"name":"Log","hostname":"localhost","pid":2452,"level":30,"version":"5.44.0","msg":"Inserting 1000 recipients for email 64b2b3b38e3d8d0994477ef4 batch 64b2b3b38e3d8d0994477ef5","time":"2023-07-15T14:56:51.800Z","v":0}
{"name":"Log","hostname":"localhost","pid":2452,"level":30,"version":"5.44.0","msg":"Fetching members batch for email 64b2b3b38e3d8d0994477ef4 segment null, lastId: 632478cbdecba4a2cdd609d7","time":"2023-07-15T14:56:52.213Z","v":0}
{"name":"Log","hostname":"localhost","pid":2452,"level":30,"version":"5.44.0","msg":"Creating batch for email 64b2b3b38e3d8d0994477ef4 segment null with 1000 members","time":"2023-07-15T14:56:52.228Z","v":0}
{"name":"Log","hostname":"localhost","pid":2452,"level":30,"version":"5.44.0","msg":"Inserting 1000 recipients for email 64b2b3b38e3d8d0994477ef4 batch 64b2b3b48e3d8d09944782de","time":"2023-07-15T14:56:52.238Z","v":0}
{"name":"Log","hostname":"localhost","pid":2452,"level":30,"version":"5.44.0","msg":"Fetching members batch for email 64b2b3b38e3d8d0994477ef4 segment null, lastId: 61759424d6f63073c231b2e9","time":"2023-07-15T14:56:52.651Z","v":0}
{"name":"Log","hostname":"localhost","pid":2452,"level":30,"version":"5.44.0","msg":"Creating batch for email 64b2b3b38e3d8d0994477ef4 segment null with 273 members","time":"2023-07-15T14:56:52.660Z","v":0}
{"name":"Log","hostname":"localhost","pid":2452,"level":30,"version":"5.44.0","msg":"Inserting 273 recipients for email 64b2b3b38e3d8d0994477ef4 batch 64b2b3b48e3d8d09944786c7","time":"2023-07-15T14:56:52.666Z","v":0}
{"name":"Log","hostname":"localhost","pid":2452,"level":30,"version":"5.44.0","msg":"Created 3 batches for email 64b2b3b38e3d8d0994477ef4 with 2273 recipients","time":"2023-07-15T14:56:52.807Z","v":0}
{"name":"Log","hostname":"localhost","pid":2452,"level":30,"version":"5.44.0","msg":"Sending 3 batches for email 64b2b3b38e3d8d0994477ef4","time":"2023-07-15T14:56:52.808Z","v":0}
{"name":"Log","hostname":"localhost","pid":2452,"level":30,"version":"5.44.0","msg":"Sending batch 64b2b3b38e3d8d0994477ef5 for email 64b2b3b38e3d8d0994477ef4","time":"2023-07-15T14:56:52.808Z","v":0}
{"name":"Log","hostname":"localhost","pid":2452,"level":30,"version":"5.44.0","msg":"Sending batch 64b2b3b48e3d8d09944782de for email 64b2b3b38e3d8d0994477ef4","time":"2023-07-15T14:56:52.808Z","v":0}
{"name":"Log","hostname":"localhost","pid":2452,"level":30,"version":"5.44.0","msg":"Sent message (569ms)","time":"2023-07-15T14:56:55.318Z","v":0}
{"name":"Log","hostname":"localhost","pid":2452,"level":30,"version":"5.44.0","msg":"Sending batch 64b2b3b48e3d8d09944786c7 for email 64b2b3b38e3d8d0994477ef4","time":"2023-07-15T14:56:55.422Z","v":0}
{"name":"Log","hostname":"localhost","pid":2452,"level":30,"version":"5.44.0","msg":"Sending email to 273 recipients","time":"2023-07-15T14:56:55.521Z","v":0}
{"name":"Log","hostname":"localhost","pid":2452,"level":30,"version":"5.44.0","msg":"Sent message (575ms)","time":"2023-07-15T14:56:55.534Z","v":0}


Errors seen when trying to request certain sizes of the images:

{"name":"Log","hostname":"localhost","pid":2452,"level":30,"version":"5.44.0","req":{"meta":{"requestId":"fef17c04-8cc1-4dd9-a581-9340af6a7345","userId":null},"url":"/content/images/size/w1600/2023/07/tamper_evident_bag.jpg","method":"GET","originalUrl":"/content/images/size/w1600/2023/07/tamper_evident_bag.jpg","params":{},"headers":{"x-forwarded-for":"188.93.56.127","x-forwarded-proto":"http","x-real-ip":"188.93.56.127","host":"blog.lopp.net","connection":"close","accept":"image/*,application/octet-stream;q=0.8,*/*; q=0.01","user-agent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko)","accept-language":"en-US,en;q=0.8,ru;q=0.6"},"query":{}},"res":{"_headers":{"x-powered-by":"Express","cache-control":"public, max-age=31536000","location":"https://blog.lopp.net/content/images/size/w1600/2023/07/tamper_evident_bag.jpg","vary":"Accept, Accept-Encoding","content-type":"text/plain; charset=utf-8","content-length":"112"},"statusCode":301,"responseTime":"1ms"},"msg":"","time":"2023-07-15T14:56:58.819Z","v":0}
```

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by markstos** [comment]
I used to manage a site that had 36 million images. One of them was of an innocent looking dog named Mindy. Mindy ruined my weekend.

Every time someone uploaded a photo of Mindy, the server would enter a death spiral and eventually crash. But I did not know someone was trying to repeatedly post Mindy. I only new the web site keep death spiraling.

It took hours, over the weekend, to track down that this wasn't a normal coding problem, but ultimately a bug in the ImageMagick library triggered by invalid JPEG data in Mindy's photo file. ( The fix: use the GraphicsMagick fork ).

Maybe you've encountered a variation of the Mindy bug. You can test to see if specific photos reliably trigger it. If you find one, try running it through a photo processing app that rewrites the file-- any app would do. I'll recommend https://squoosh.app/  

This laundering might clean out any triggering corruption inside the original image.  If you can /still/ trigger the issue, I'll wager that either:

   1. Ghost has some kind of validation failure and should be rejecting the image earlier (too big?)
   2. Indeed, Ghost as an image processing bug, or more likely the upstream image processing library it uses.

**Comment by jlopp** [comment]
Unfortunately I haven't been able to reproduce this issue, even if I publish another article with the same images. The only difference is that I'm not emailing out the post when I publish.

**Comment by markstos** [comment]
Zero-byte files might also happen  if the disk filled up, and that could explain when it's not reproducible now. Even if you check the disk now and it's not full, it's possible the some logs got rotated, the system was rebooted or something else happened to recover disk space. 

If you have monitoring setup on the disk space, this could help to observe trends. For example, you might see that a disk is coming close to filling up each day, and the automatic log rotation happens and recovers enough disk space.

**Comment by jlopp** [comment]
Don't think it's a disk space issue; this dedicated machine has 20 GB of free space and doesn't run any other software; looks like it only writes ~50MB of logs per day and logs get compressed once they're 2 weeks old, so a total of less than 1 GB of uncompressed logs.

**Comment by markstos** [comment]
@jlopp Does it have two partitions like "/" and "/home" or a single partition? If Ghost happens to write to  `/tmp` was mounted in memory as a RAM disk, that could fill up if a temp file was larger than memory. (I haven't checked Ghost if it caches uploads in tmp).

**Comment by jlopp** [comment]
@markstos only a single partition for /

**Comment by markstos** [comment]
@jlopp You mentioned at the time you sent your post that it had several images in it-- presumably you could see them before they were published and they looked fine. This indicates that the image were successfully uploaded and, at least then, not-zero-byte. 

Because this issue is not reproducible and because it has some indications of a "disk full" scenario, I recommend the issue be closed as Ghost bug. 

Sometimes disks can run out of inodes even when they have disk space or there can be "phantom" disk space filling up a disk if log rotation isn't configured correctly. 

Having graphs of the disk space and CPU could help better diagnosis an issue like this in the future.

**Comment by jlopp** [comment]
Yes, and I've published several posts since then without seeing the issue re-appear. Will re-open if it happens again and I can surface any commonalities.

**Comment by patabongo** [comment]
I just experienced what seems to be a repeat of this issue: Ghost user published a very image-heavy post (13 images) and some of the resized images were created as 0 byte files.

<img width="564" alt="Image" src="https://github.com/user-attachments/assets/b8e9a6de-bbcc-421f-9794-3b479e7e6c2e" />

and

<img width="566" alt="Image" src="https://github.com/user-attachments/assets/048b48b8-a55b-4f75-9649-872f39608f59" />

Similar to the OP, this is the first time we've experienced this issue and it doesn't seem like a disk space issue as / currently has 26G free. Also similar to OP, when the email showed up with missing images I tried to view the post in a browser and got a 502 error from Nginx. Around 20 seconds later I tried to reload the page and it loaded as expected. Like OP I resolved the issue by manually copying image files over the 0 byte versions.

**Ghost Version**

5.109.2

**Node.js Version**

18.20.6

**How did you install Ghost?**

DigitalOcean 1-Click droplet, Ubuntu 20.04.6 LTS

**Database type**

MySQL 8

**Browser & OS version**

Safari & MacOS

**Comment by markstos** [comment]
@patabongo Check your uptime of your Ghost service and your Ghost logs around the time this happened. You are looking to see if Ghost crashed and restarted around this time. For example, imagine this sequence:

1. Ghost starts an image resize, creating a target file name.
2. Ghost runs out of memory and crashes.
3. Zero-sized file results. 

> I tried to view the post in a browser and got a 502 error from Nginx. Around 20 seconds later I tried to reload the page and it loaded as expected. 

This symptom is consistent with a crash and an automated restart. The HTTP 502 status code indicates that Ghost was likely down when Nginx tried to contact it, because Ghost crashed. Then the fact that it 20 seconds later it works again indicates it automatically restarted.

WIthout knowing what's in your logs, it's impossible to know if the root case was resource exhaustion on your server or some bug in Ghost.

**Comment by patabongo** [comment]
Thanks! Okay, from the logs the bulk email sending job begins at Feb 07 22:52:09 and completes around 7 seconds later. Then about 50 seconds of GET requests. Then:

> Feb 07 22:53:06 amalelmohtar node[1419]: [2025-02-07 22:53:06] INFO "GET /favicon.ico" 302 11ms
> Feb 07 22:53:06 amalelmohtar node[1419]: [2025-02-07 22:53:06] INFO "GET /favicon.ico" 302 17ms
> Feb 07 22:53:43 amalelmohtar systemd[1]: ghost_tesh-xyz.service: Succeeded.
> Feb 07 22:53:43 amalelmohtar systemd[1]: ghost_tesh-xyz.service: Scheduled restart job, restart counter is at 1.
> Feb 07 22:53:43 amalelmohtar systemd[1]: Stopped Ghost systemd service for blog: tesh-xyz.
> Feb 07 22:53:43 amalelmohtar systemd[1]: Started Ghost systemd service for blog: tesh-xyz.
> Feb 07 22:53:46 amalelmohtar node[11769]: Love open source? We’re hiring JavaScript Engineers to work on Ghost full-time.
> Feb 07 22:53:46 amalelmohtar node[11769]: https://careers.ghost.org
> Feb 07 22:53:46 amalelmohtar node[11769]: - Inspecting operating system
> Feb 07 22:53:05 amalelmohtar node[1419]: [2025-02-07 22:53:05] INFO "GET /content/images/size/w1600/2025/02/IMG_7344-2.jpg" 200 8940ms
> Feb 07 22:53:05 amalelmohtar node[1419]: [2025-02-07 22:53:05] INFO "GET /content/images/size/w1600/2025/02/IMG_7344-2.jpg" 200 8967ms
> Feb 07 22:53:05 amalelmohtar node[1419]: [2025-02-07 22:53:05] INFO "GET /content/images/size/w1600/2025/02/IMG_7336.JPG" 200 8982ms
> Feb 07 22:53:05 amalelmohtar node[1419]: [2025-02-07 22:53:05] INFO "GET /favicon.ico" 302 7ms
> Feb 07 22:53:06 amalelmohtar node[1419]: [2025-02-07 22:53:05] INFO "GET /content/images/size/w1600/2025/02/Amal-El-Mohtar-IG-square.jpg" 200 9106ms
> Feb 07 22:53:06 amalelmohtar node[1419]: [2025-02-07 22:53:06] INFO "GET /content/images/size/w1600/2025/02/IMG_7338.JPG" 200 9116ms
> Feb 07 22:53:06 amalelmohtar node[1419]: [2025-02-07 22:53:06] INFO "GET /favicon.ico" 302 37ms
> Feb 07 22:53:06 amalelmohtar node[1419]: [2025-02-07 22:53:06] INFO "GET /favicon.ico" 302 11ms
> Feb 07 22:53:06 amalelmohtar node[1419]: [2025-02-07 22:53:06] INFO "GET /favicon.ico" 302 17ms
> Feb 07 22:53:43 amalelmohtar systemd[1]: ghost_tesh-xyz.service: Succeeded.
> Feb 07 22:53:43 amalelmohtar systemd[1]: ghost_tesh-xyz.service: Scheduled restart job, restart counter is at 1.
> Feb 07 22:53:43 amalelmohtar systemd[1]: Stopped Ghost systemd service for blog: tesh-xyz.
> Feb 07 22:53:43 amalelmohtar systemd[1]: Started Ghost systemd service for blog: tesh-xyz.
> Feb 07 22:53:46 amalelmohtar node[11769]: Love open source? We’re hiring JavaScript Engineers to work on Ghost full-time.
> Feb 07 22:53:46 amalelmohtar node[11769]: https://careers.ghost.org
> Feb 07 22:53:46 amalelmohtar node[11769]: - Inspecting operating system
> Feb 07 22:53:47 amalelmohtar node[11800]: [2025-02-07 22:53:47] INFO Ghost is running in production...

**Comment by markstos** [comment]
> Feb 07 22:53:43 amalelmohtar systemd[1]: Stopped Ghost systemd service for blog: tesh-xyz.
> Feb 07 22:53:43 amalelmohtar systemd[1]: Started Ghost systemd service for blog: tesh-xyz.

This is Ghost restarting, explaining the 502 like I thought.

You can also check:

```
journalctl | grep -E "Out of memory|Killed process"
```

If you get some hits related to Ghost, it could be that the "Out of Memory Killer" (oomkiller) detected that the system was dangerously close to crashing due to an out of memory condition an decided to kill Ghost to save the system overall.

I recommend graphing key vitals of servers over time, like memory. If you had or have such graphs, you would be able to see if your server was close to 2 GB and then suddenly recovered a bunch of memory, another sign that it ran out of memory and then self-recovered.

Hosting questions are best discussed at https://forum.ghost.org/
