### ISSUE TITLE
ghost install' command permission error because of the attempt to use 'mount'

### ISSUE THREAD

**Issue by Orygaw** [TryGhost/Ghost#17372]
### Issue Summary

Hello, I'm having a permission issue when trying to install ghost. I'm starting with:

> npm i -g ghost-cli@latest

It all goes well, no errors, neither warnings. The problem appears when I'm trying to use:

> ghost install --no-setup-nginx --port 10101

```
Love open source? We’re hiring JavaScript Engineers to work on Ghost full-time.
https://careers.ghost.org
✔ Checking system Node.js version - found v16.20.0
✔ Checking current folder permissions
✔ Checking memory availability
/bin/sh: mount: Permission denied
node:child_process:935
    throw err;
    ^
Error: Command failed: mount
/bin/sh: mount: Permission denied
    at checkExecSyncError (node:child_process:861:11)
    at execSync (node:child_process:932:15)
    at /usr/home/kacper-pr/.npm-global/lib/node_modules/ghost-cli/node_modules/systeminformation/lib/filesystem.js:143:11
    at processTicksAndRejections (node:internal/process/task_queues:78:11) {
  status: 126,
  signal: null,
  output: [
    null,
    Buffer(0) [Uint8Array] [],
    Buffer(34) [Uint8Array] [
       47,  98, 105, 110,  47, 115, 104,  58,
       32, 109, 111, 117, 110, 116,  58,  32,
       80, 101, 114, 109, 105, 115, 115, 105,
      111, 110,  32, 100, 101, 110, 105, 101,
      100,  10
    ]
  ],
  pid: 14451,
  stdout: Buffer(0) [Uint8Array] [],
  stderr: Buffer(34) [Uint8Array] [
     47,  98, 105, 110,  47, 115, 104,  58,
     32, 109, 111, 117, 110, 116,  58,  32,
     80, 101, 114, 109, 105, 115, 115, 105,
    111, 110,  32, 100, 101, 110, 105, 101,
    100,  10
  ]
}

```
I'm using FreeBSD 13.2 OS. The current version of npm is 9.6.6 and that of Node.js is 16.20.0. Can't install it using 'sudo' since I'm a mere user of the server.
It's pretty simple as to why the error occurs, but the question is: is it possible to run the installation without the ghost's need to use 'mount'. Thank you in advance.
Collapse

### Steps to Reproduce

npm i -g ghost-cli@latest
ghost install --no-setup-nginx --port 10101

### Ghost Version

latest

### Node.js Version

16.20

### How did you install Ghost?

I'm using FreeBSD 13.2 OS. The current version of npm is 9.6.6 and that of Node.js is 16.20.0. 

### Database type

MySQL 8

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by avkarenow** [comment]
I have a similar problem using shared hosting, system administrator said that mount isn't necesary for working of any user's application and contains important information about system.

I just have checked a few OSes and many of them have mount in /sbin or /usr/sbin (macOS, *BSD, Solaris, HP-UX...) 
It seems only Linux has it in /bin.

As far as I know there is no warranty for working programs from sbin for normal system users, isn't it?

Maybe is it better to replace mount with something else?
