### ISSUE TITLE
Discord webhook

### ISSUE THREAD

**Issue by LosBagros** [TryGhost/Ghost#17452]
### Issue Summary

I am unable to set up the integration for the Discord webhook.

### Steps to Reproduce

I was following this tutorial https://ghost.org/integrations/discord/

### Ghost Version

5.54.4

### Node.js Version

v16.20.1

### How did you install Ghost?

docker-compose, ubuntu arm

### Database type

MySQL 8

### Browser & OS version

Brave, WIn 11

### Relevant log / error output

```shell
[2023-07-21 22:27:56] ERROR The server has encountered an error.

The server has encountered an error.

"The slack service was unable to send a ping request, your site will continue to function."
"If you get this error repeatedly, please seek help on https://ghost.org/docs/."

Error ID:
    d74917e0-2815-11ee-98c8-03014a087a60

----------------------------------------

HTTPError: Response code 400 (Bad Request)
    at /var/lib/ghost/versions/5.54.4/core/server/services/slack.js:147:27
    at EventEmitter.<anonymous> (/var/lib/ghost/versions/5.54.4/node_modules/@tryghost/request/node_modules/got/source/as-promise.js:74:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by daniellockyer** [comment]
It seems the Discord endpoint has changed such that our Slack-compatible code no longer works

A PR to fix this would be welcome 🙂

**Comment by h2akim** [comment]
Hi 👋!

This might not be a bug. Just need documentation update.

For slack-compatible url, need to append `/slack` to discord webhook url.

Just did a test after the url append. Looks like working without a problem
![Screenshot 2023-09-11 at 2 33 05 PM](https://github.com/TryGhost/Ghost/assets/514048/6396772c-f7cc-4550-82dc-5207e8a0ce87)

Example: `https://discord.com/api/webhooks/<webhookId>/<webhhookToken>/slack`
Reference: https://discord.com/developers/docs/resources/webhook#execute-slackcompatible-webhook

Thanks

**Comment by LosBagros** [comment]
Thanks
