### ISSUE TITLE
Make this site private - not working in Chrome and Opera

### ISSUE THREAD

**Issue by joe-blocher** [TryGhost/Ghost#17514]
### Issue Summary

Change or delete the row 58:
versions/5.54.4/core/frontend/apps/private-blogging/lib/middleware.js

 ```
return session({
            name: 'ghost-private',
            maxAge: constants.ONE_MONTH_MS,
            signed: false,
            sameSite: 'lax'     <----- row 58: instead of 'none' or delete row
        })(req, res, next);

```
Or you can delete the row 58 because **sameSite: 'Lax' is the default value.**
You can't code 'secure' within an object - **secure: true** will not work.

Works now in Chrome and Opera.
See [https://web.dev/i18n/en/samesite-cookies-explained](https://web.dev/i18n/en/samesite-cookies-explained/#samesite=lax-by-default)
![x (1) Mark cross-site cookies as Secure to allow setting them in cross-site contexts](https://github.com/TryGhost/Ghost/assets/93246850/c3a11e60-8d16-45f2-8261-b889e074da71)

### Steps to Reproduce

See [https://forum.ghost.org/t/make-this-site-private-not-working/39938/1](https://forum.ghost.org/t/make-this-site-private-not-working/39938/1)

### Ghost Version

5.54.4

### Node.js Version

v18.15.0

### How did you install Ghost?

local, macos

### Database type

SQLite3

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by joe-blocher** [comment]
In core/frontend/apps/private-blogging/lib/middleware.js:

´´´
const privateBlogging = {
 
        …
        return session({
            name: 'ghost-private',
            maxAge: constants.ONE_MONTH_MS,
            signed: false,
      //      sameSite: 'none'    <——— replace this with 2 lines below 
              sameSite: urlUtils.isSSL(config.get('url')) ? 'none' : 'lax',
              secure: urlUtils.isSSL(config.get('url'))
        })(req, res, next);
    },
    
´´´

and all is fine!
Implement in the same way as you did in 
core/server/services/auth/session/express-session.js

**Comment by daniellockyer** [comment]
Hey there, thank you so much for the detailed bug report.

That does look like something that shouldn't happen! A PR to fix this issue would be very welcome 🙂

**Comment by joe-blocher** [comment]
I have made the PR

**Comment by hussainb** [comment]
Hi, I am facing the same issue in the latest version of Ghost, unable to login to the private site using Chrome based browsers.

**Comment by joe-blocher** [comment]
It's nearly three month later ... an nothing happened. But for me it closed, because I'm working locally  :-) 
https://forum.ghost.org/t/make-this-site-private-not-working/39938

**Comment by hussainb** [comment]
> It's nearly three month later ... an nothing happened. But for me it closed, because I'm working locally :-) https://forum.ghost.org/t/make-this-site-private-not-working/39938

yeah, they didn't care to merge it. but I appreciate you for your troubleshooting and the fix. 

I think just a rerun would be required to pass the build, otherwise the PR is already approved:

https://github.com/TryGhost/Ghost/actions/runs/6057836235/job/16821076886?pr=17938
![image](https://github.com/TryGhost/Ghost/assets/4962633/2abc6c33-ed0c-442d-9e81-9cdbd0e405cd)

**Comment by joe-blocher** [comment]
I have made my first PR. 
I think the 2. one failed: Merge branch 'main' into joe-blocher-patch-1 <https://github.com/TryGhost/Ghost/pull/17938/commits/ae0f64eb578f4aa43248da1b3e807a1f0c3b9bef>

I don't really know what is for and how I can delete this PR...

**Comment by hussainb** [comment]
Maybe @daniellockyer can help

**Comment by joe-blocher** [comment]
**You did't fix the error: Make this site private - not working not working in Chrome and Opera**

![Bildschirmfoto 2024-04-18 um 10 34 22](https://github.com/TryGhost/Ghost/assets/93246850/e9d5d56b-4c6d-43af-9f51-ae2661ca01c0)
![Bildschirmfoto 2024-04-18 um 10 35 30](https://github.com/TryGhost/Ghost/assets/93246850/27bf768b-6695-4d3f-92a1-616c86af08ee)


### SOLUTION - it told you in August 2023 and I have made the PR!

 **versions/5.82.2/core/frontend/apps/private-blogging/lib/middleware.js**

`const privateBlogging = { 
       ....

        return session({
            name: 'ghost-private',
            maxAge: constants.ONE_MONTH_MS,
            signed: false,

            sameSite:   urlUtils.isSSL(config.get('url')) ? 'none' : 'lax',  <------------ insert this
            secure: urlUtils.isSSL(config.get('url'))  <------------------------------ insert this
            //sameSite: 'none' <------------------------------------------  row 58: remove
        })(req, res, next);
    },`

**Comment by joe-blocher** [comment]
The pull request still not merged in version 5.82.2: 
[Fixed private mode cookie for local development #17938](https://github.com/TryGhost/Ghost/pull/17938)

**Comment by vikaspotluri123** [comment]
What makes you say the PR wasn't merged? The [commit](https://github.com/TryGhost/Ghost/commit/f303eee8a432291d5458aaa092920a06612d324c) shows that it's been in releases starting from 5.70.0.

**Comment by joe-blocher** [comment]
I've downloaded the code:
versions/5.82.2/core/frontend/apps/private-blogging/lib/middleware.js
But the code is still the same:
` return session({
        name: 'ghost-private',
        maxAge: constants.ONE_MONTH_MS,
        signed: false,
        sameSite: 'none' <------------------------------------------  why this?
    })(req, res, next);
},``

**Comment by vikaspotluri123** [comment]
The code being the same does not mean your PR was not merged. In this case it looks like this change ended up possibly breaking something else so it was reverted:

https://github.com/TryGhost/Ghost/pull/19298

**Comment by davedub** [comment]
> The code being the same does not mean your PR was not merged. In this case it looks like this change ended up possibly breaking something else so it was reverted:
> 
> #19298

OK so that means it is still a problem. I am running 5.79.6 (released Feb 26) and cannot make the site private because of this bug. What's the ETA on solving this?

**Comment by joe-blocher** [comment]
> > The code being the same does not mean your PR was not merged. In this case it looks like this change ended up possibly breaking something else so it was reverted:
> > #19298
> 
> OK so that means it is still a problem. I am running 5.79.6 (released Feb 26) and cannot make the site private because of this bug. What's the ETA on solving this?

My solution: 
I change always the code by myself, when I install an update. You have to change only 2 lines. 
The first time I reported the solution in August 2023. 
Maybe they will fix the bug sometimes ...

**Comment by TheLaurenBarger** [comment]
Hey guys, any update on this one? I couldn't access the links behind why the commit was reverted. So not sure on the details or complexity of the bug, is there any progress towards figuring it out? Thanks, and I'm a huge Ghost fan 😊

**Comment by joe-blocher** [comment]
**Downloaded version 5.89.1 - this bug still not fixed**

You have to change only 2 lines in your code. 
The first time I reported the solution in August 2023.
Why this is impossible?

**Comment by Grasume** [comment]
@daniellockyer  this is disappointing that this is still an issue exp with docker involved.

**Comment by kilmarnock** [comment]
I can confirm that I have no access via chromium, chrome and edge. Works with firefox. Will tell that to my customers not.

**Comment by ErisDS** [comment]
Hey, I'm sorry that it wasn't made clear when the related PR was reverted. Unfortunately the fix broke the theme preview in Ghost admin for private sites, when the admin and site URLs are configured differently (the recommended configuration).

We are clearly missing some test coverage there, as the PR looked good to merge.

In the meantime, whilst trying to understand this issue I wasn't able to reproduce it in Arc, Chrome or Chromium.

There's something really janky going on here, because whilst there are clearly a couple of people here on this issue experiencing the problem, there's not a lot of wider noise despite private sites being used widely very successfully.

Meanwhile, when we merged the PR and broke the theme preview for private sites, we heard about it instantly from many people.

So there has to be a caveat that's not being covered here in the reproduction steps. I have a feeling that is something to do with SSL, which shouldn't be impacting production sites.

I'm going to close this bug as it stands. If anyone has the detailed reproduction case, feel free to open a new issue and we can work through what cases should and shouldn't work & making sure that fixing this issue doesn't cause a more widespread issue for private site users.

**Comment by joe-blocher** [comment]
> I wasn't able to reproduce it in Arc, Chrome or Chromium.

You're right!
I've updated Chrome and the bug disappeared. 

It was a bug in Chrome with the error-message:
![x (1) Mark cross-site cookies as Secure to allow setting them in cross-site contexts](https://github.com/user-attachments/assets/1b2ed7d0-4035-414d-af63-b9fdc0125f66)
OK, many thanks

**Comment by joe-blocher** [comment]
Take a look at my comment:
[https://forum.ghost.org/t/private-mode-wont-accept-any-password-just-loops-prompt/58417](https://forum.ghost.org/t/private-mode-wont-accept-any-password-just-loops-prompt/58417)

**Comment by joe-blocher** [comment]
Better
https://forum.ghost.org/t/private-mode-wont-accept-any-password-just-loops-prompt/58417/2

**Comment by ErisDS** [comment]
@joe-blocher your last comment on here was that you also found that it was fixed after updating Chrome. I also explained very clearly that the fix caused a regression in our recommended setup.

It seems like something changed, but you haven't communicated what or when?

**Comment by joe-blocher** [comment]
No, it was an oversight: I had installed “https”. That's why “Chrome” didn't cause any problems.
The bug under “http” - the actual problem under “Chrome” - is still there. The ‘ghost-private’ cookie cannot be set. 

I think you also tested under “https” - see above:

_In the meantime, whilst trying to understand this issue I wasn't able to reproduce it in Arc, Chrome or Chromium._
...
_Unfortunately the fix broke the theme preview in Ghost admin for private sites ..._

I don't understand what a set ‘ghost-private’ cookie can have for side effects on “theme preview”.
You'll have to explain that to me in more detail. I can't understand it and haven't noticed anything.


My code change:

```line current/core/frontend/apps/private-blogging/lib/middleware.js```
```const privateBlogging = {
    checkIsPrivate: function checkIsPrivate(req, res, next) {
       ...
        return session({
            name: 'ghost-private',
            maxAge: constants.ONE_MONTH_MS,
            signed: false,
           // sameSite: 'none'
            sameSite: urlUtils.isSSL(config.get('url')) ? 'none' : 'lax',  //<-------------------
        })(req, res, next);
    },```

No difference to the code before under "https" -> "sameSite: none"
but under "http" -> "lax" instead of "none".
Thats all.
