### ISSUE TITLE
Unable to run VSCode debugger from launch.json

### ISSUE THREAD

**Issue by RohitLakh** [TryGhost/Ghost#17523]
### Issue Summary

When running `Full Offline Dev` or `Full Dev` from VSCode debugger there is an error about `dev.js` not found

<img width="748" alt="image" src="https://github.com/TryGhost/Ghost/assets/34619861/4380817b-39b6-4083-b74b-6831636b716a">

### Steps to Reproduce

1. Open VSCode debugger
2. Try running `Full Offline Dev` or `Full Dev` 

### Ghost Version

@

### Node.js Version

18.16.0

### How did you install Ghost?

Source

### Database type

MySQL 5.7

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by RohitLakh** [comment]
Creating a PR for this to solve this

**Comment by RohitLakh** [comment]
@daniellockyer I have created PR here: https://github.com/TryGhost/Ghost/pull/17525

There are some documentation change that needs to be done due to some global installation of external dependency which is `npm i -g nx`, not exactly sure where to do that, if you can point it out will update that as well

**Comment by daniellockyer** [comment]
This is already fixed on `main` 🙂
