### ISSUE TITLE
Unknown Global Helper Used

### ISSUE THREAD

**Issue by redsterns** [TryGhost/Ghost#17529]
### Issue Summary

Release: 5.56.0

I updated the CLI and created a fresh install of Ghost on my  devbox this morning, approx 2 hours after the relase.
After signing up and in, I received the following error message.

![image](https://github.com/TryGhost/Ghost/assets/7895675/9b211684-3192-4c9a-8a47-895da01e012a)

### Steps to Reproduce

1. Create Install folder
2. Upgrade Ghost CLI using NPM
3. `ghost install local`
4. Sign up as administrator
5.  Log into ghost admin with the default Caspar 

The error: page.hbs: {{@page.show_title_and_feature_image}} is not a known global helper appears

### Ghost Version

5.56.0

### Node.js Version

v18.15.0

### How did you install Ghost?

Pop_OS Linux, ghost install local

### Database type

MySQL 5.7

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by cathysarisky** [comment]
This appears to be specific to 5.56, and maybe to Casper on 5.56.  You may want to pin your version at 5.55.2 until the Ghost team can resolve it.  Discussion over here: https://forum.ghost.org/t/theme-errors-after-update-to-5-56/40128/8

**Comment by redsterns** [comment]
My purchased theme is also broken on 5.56.  Thanks for the link.  I managed to roll back to 5.55.2.  I don't know how to pin my version, would you be willing to put a link here with instructions, for posterity?  Thanks!

**Comment by ErisDS** [comment]
Hey @redsterns thanks for the bug report. 

Most important to repeat @royalfig on the [forum](https://forum.ghost.org/t/theme-errors-after-update-to-5-56/40128/10).

**This error won’t cause your site or Casper to stop working.**

It's a warning that the theme is using a helper that doesn't do anything (yet).

We have a new feature that we're working on releasing. As part of that work, we've rolled out a missing check in gscan (it was there but not wired up 🙈) that identifies any `@global` helpers used in a theme that don't exist. Ideally, that check would have been there for years, to help anyone who installs a too-up-to-date theme on an old Ghost install, the same as we have for helpers like `{{match}}`.

Meanwhile, we've done the prep work to launch the feature by updating Casper, the default theme. But we've not shipped these changes, or the new helper just yet.

However, the automated release of Ghost on Friday picked up the changes in Casper unexpectedly - which is a bug as it's meant to work off of the latest release.

We've implemented a fix for the broken release process, and a fixed release will be shipped soon.

**Comment by ErisDS** [comment]
- [Ghost 5.56.1](https://github.com/TryGhost/Ghost/commit/09d967a1975d47ea084144c05240cd8caa343ee8) resolves the issue with Casper being a few commits ahead. There are no related commits in Ghost because this was a problem with the build/release tooling grabbing the wrong version into the tar file.
- [Ghost 5.57.0](https://github.com/TryGhost/Ghost/pull/17544) adds the new [@page features](https://ghost.org/docs/themes/helpers/page/)
