### ISSUE TITLE
Ghost Redirect yaml broke my site

### ISSUE THREAD

**Issue by mikejones3** [TryGhost/Ghost#17531]
### Issue Summary

redirect.yaml is not working properly

### Steps to Reproduce

I was trying to make my home page for to a specific page in ghost. My home page was mysite.com and i wanted it to point to mysite.com/home

I went into the labs and upoaded a redirects/yaml that looked like this:

```
301:
    /:/home

302:
```

I then refreshed my ghost site and got this off bug where it redirect to:

https://mysite.com/home/home/home/home/home/home/home/home/home/home/home/home/home/home/home/home/home/home/home/

I then tried to revert and uploaded a new redirect.yaml that looks like this:

```
301:

302:
```

And my site is still redirecting to the bad url above.

### Ghost Version

5.56.0

### Node.js Version

N/A

### How did you install Ghost?

Digital Ocean 1 click 

### Database type

MySQL 8

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by RohitLakh** [comment]
@mikejones3 The regex that you are using for `/` will match for any url. 
URL home/ -> home/home/ -> home/home/home/ till infinite until the server stops redirecting. 

You can use regex here to implement the base route that you want to update

This would work just fine for you.

```
301:
  ^\/$: /home/
```

**Comment by mikejones3** [comment]
thanks!
