### ISSUE TITLE
Text customization bar shows up on top of the preview overlay

### ISSUE THREAD

**Issue by snowywaffles** [TryGhost/Ghost#17542]
### Issue Summary

This behavior **only occurred** in the beta editor. When highlighting a portion of text, and then pressing 'Preview', the text customization bar (what shows up when you highlight a portion of text) shows up OVER the preview. I don't think this is intended behavior.

### Steps to Reproduce

1. Highlighting some text
<img width="1434" alt="Screen Shot 2023-07-31 at 11 05 38 AM" src="https://github.com/TryGhost/Ghost/assets/94981010/1e2d0bac-7066-4687-a428-6c67b9b1dc24">
2. Pressing 'Preview'
<img width="1434" alt="Screen Shot 2023-07-31 at 11 09 08 AM" src="https://github.com/TryGhost/Ghost/assets/94981010/0a60f927-cbe8-4ca7-8445-1ff162f80f2d">
3. The text customization bar stays stuck at an absolute position, even when I scroll up and down. It also stays stuck even if I change the preview type (computer, phone, email, social) to something else.

### Ghost Version

5.55.2+moya

### Node.js Version

I use Ghost(Pro)

### How did you install Ghost?

n/a, I use Ghost(Pro). I don't know what database type I use

### Database type

Other

### Browser & OS version

Google Chrome Version 115.0.5790.114 (Official Build) (arm64)

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by vineetpradhan-dev** [comment]
Hi @daniellockyer, I would like to give it a try.

**Comment by kartikgothwal** [comment]
can you give a video or a link of this issue, i would like to solve it
