### ISSUE TITLE
Disappearing content on upgrade to 5.56.0

### ISSUE THREAD

**Issue by verement** [TryGhost/Ghost#17558]
### Issue Summary

Upon upgrading Ghost to 5.56.0, some of the content on our site has disappeared. Formerly working links return 404 errors, and formerly working tag index pages show a header image/summary but no content.

The problem persists in 5.57.0.

### Steps to Reproduce

1. Have a working site running Ghost 5.55.2.
2. Upgrade to 5.56.0 or 5.57.0.
3. Check that all formerly working content is still present and working.

### Ghost Version

5.56.0

### Node.js Version

16.20.1

### How did you install Ghost?

Ubuntu 22.04

### Database type

MySQL 8

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by sergiospagnuolo** [comment]
Got the same errors

**Comment by daniellockyer** [comment]
Would you be able to try v5.57.1 or above? I believe this is now fixed

**Comment by verement** [comment]
Thank you, this is confirmed fixed in 5.57.1.
