### ISSUE TITLE
Ghost doesn't support IPv6-only hosts for sending email

### ISSUE THREAD

**Issue by sybo-matthew** [TryGhost/Ghost#17627]
### Issue Summary

Nodemailer has a known issue where it will always prefer sending to IPv4 addresses, even if the host is IPv6 only and there are IPv6 AAAA records available. I'm attempting to connect to scaleway SMTP with Ghost as mailgun doesn't have an IPv6 DNS entry. The SMTP server hostname is: smtp.tem.scw.cloud

The specific error I get in Ghost is: Error: connect ENETUNREACH 51.159.99.81:587 - Local (0.0.0.0:0). I can reproduce this with the following script on Node.js v18.13.0 with the latest version of Nodemailer with the following script. 

``` "use strict";
const nodemailer = require("nodemailer");

const transporter = nodemailer.createTransport({
  host: "smtp.tem.scw.cloud",
  port: 587,
  secure: false,
  auth: {
    // TODO: replace `user` and `pass` values from <https://forwardemail.net>
    user: 'scaleway-user-name',
    pass: 'scaleway-password'
  }
});

// async..await is not allowed in global scope, must use a wrapper
async function main() {
  // send mail with defined transport object
  const info = await transporter.sendMail({
    from: '"Dead People 👻" <noreply@matduggan.com>', // sender address
    to: "mat@matduggan.com", // list of receivers
    subject: "Hello", // Subject line
    text: "Hello world", // plain text body
    html: "<b>Hello world?</b>", // html body
  });

  console.log("Message sent: %s", info.messageId);
}

main().catch(console.error); 
```

**Nodemailer has a recommended workaround**, which is to set the IP address as host and then set the domain name as tls hostname. It ends up looking like this: 

``` 
"use strict";
const nodemailer = require("nodemailer");

const transporter = nodemailer.createTransport({
  host: "2001:bc8:1201:21:d6ae:52ff:fed0:6aac",
  port: 587,
  secure: false,
  tls: {
    rejectUnauthorized: true,
    servername: "smtp.tem.scw.cloud"},
  auth: {
    user: 'scaleway-username',
    pass: 'scaleway-password'
  }
});

// async..await is not allowed in global scope, must use a wrapper
async function main() {
  // send mail with defined transport object
  const info = await transporter.sendMail({
    from: '"Test" <noreply@matduggan.com>', // sender address
    to: mat@matduggan.com", // list of receivers
    subject: "Hello ✔", // Subject line
    text: "Hello world?", // plain text body
    html: "<b>Hello world?</b>", // html body
  });

  console.log("Message sent: %s", info.messageId);
}

main().catch(console.error);
```

This works great, but I don't see a way to pass these options through Ghost to Nodemailer. Also it seems like the version of Nodemailer Ghost uses is quite old, so an upgrade to a more recent version is likely required before this workaround would function. However I haven't tested all the versions, so I'll defer to the maintainers on that. 

As cloud providers have raised the prices of IPv4 addresses, it is more likely that Ghost users will be attempting to run this on IPv6 only hosts and will encounter this problem. I believe upgrading Nodemailer and providing the ability to pass both a hostname AND a TLS servername is an easy workaround to this problem and should allow users to send emails with no problems. 

### Steps to Reproduce

1. Set up Ghost on an IPv6 only host
2. Attempt to send an email through SMTP to a server that supports IPv6

### Ghost Version

5.57.2

### Node.js Version

Node.js v18.13.0

### How did you install Ghost?

Docker

### Database type

MySQL 8

### Relevant log / error output

```shell
ENETUNREACH 51.159.99.81:587 - Local (0.0.0.0:0)
```

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by daniellockyer** [comment]
Hey there, thank you so much for the detailed bug report.

A PR to fix this issue would be very welcome 🙂

**Comment by chairulakmal** [comment]
Hi @sybo-matthew 👋
GhostMailer uses [nodemailer@6.6.3](https://github.com/TryGhost/Ghost/blob/b545f234b2f77a385b6a09ef5bb6b6a2a44aba9e/yarn.lock#L7080) which accepts the workaround you mention: set the IP address as host and set the domain name as tls hostname.

Have you tried using the workaround in `config.production.json`?
If `Direct` transport doesn't work, perhaps `SMTP` would:

```
"mail": {
    "transport": "SMTP",
    "options": {
      "host": "::",
      "port": 587,
      "secure": false,
      "auth": {
          "user": "username",
          "pass": "password"
      },
      "tls": {
        "rejectUnauthorized": true,
        "servername": "smtp.server.cloud"
      }
    }
}
```

I was going to test this on local instance until I realized my ISP doesn't support IPv6 yet 🥲

**Comment by sybo-matthew** [comment]
@chairulakmal So sorry for the late response but this worked like a charm. Thank you for the help. For anyone else who stumbles across this post in the future, let me leave you the tips you need to make this work. 

- set up the `config.production.json` as outlined above
- ensure that you have manually configured an IPv6 DNS server inside of /etc/docker/daemon.json. Mine is as follows:
```
"dns": [
	  "2001:4860:4860::8888",
	  "8.8.8.8",
	  "2001:4860:4860:0:0:0:0:8888"
  ]
```
Confirmed this works with all IPv6 compatible SMTP services I tested it with.

**Comment by imp1sh** [comment]
I vote for reopening this as there's only a workaround given. I consider this to be a bug as software should prefer using IPv6 over IPv4 instead of the other way around.

**Comment by arigit** [comment]
Just to confirm that this workaround still works. Tested with  smtp.gmail.com in an ip6-only server. Transactional emails work with it.
