### ISSUE TITLE
The "sign in" , "subscribe" and "sign up" button do not work

### ISSUE THREAD

**Issue by danielraffel** [TryGhost/Ghost#17638]
### Issue Summary

The "sign in" , "subscribe" and "sign up" button do not work when tapped on
Other buttons work just fine (search, nav/home, about)
Reproduced issue in a few themes (currently demoing showing Dawn-main but can repro in default)

### Steps to Reproduce

1. setup fresh ghost using podman and compose.yaml using ghost: image: ghost:5-alpine
2. wait for service to start
3. notice that sign up, subscribe and sign in buttons do not work

video demos issue

https://github.com/TryGhost/Ghost/assets/25807/c88356ae-6b7b-4c1b-bf65-00268b6904ff

### Ghost Version

Version: 5.58.0

### Node.js Version

v16.20.1

### How did you install Ghost?

Installed Alpine on Linux 5.15.26-gentoo x86_64 Linux

### Database type

MySQL 8

### Browser & OS version

Installed via compose.yaml which I passed into the log

### Relevant log / error output

```shell
Here's the compose yaml I used (wanted to store SQL db in case I reboot)

version: '3.1'

services:
  ghost:
    image: ghost:5-alpine
    restart: always
    ports:
      - 28340:2368
    environment:
      database__client: mysql
      database__connection__host: db
      database__connection__user: root
      database__connection__password: secret
      database__connection__database: ghost
      url: http://ghost.redacted.me
      #NODE_ENV: development

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - /home/username/ghost-sql:/var/lib/mysql
```

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by sybo-matthew** [comment]
What theme is that? Is it Casper? Are there any errors in the browser console? 

The reason I ask is I just ran a fresh docker-compose with default everything and the same version and there is no issue, which makes me wonder if its theme related.

**Comment by danielraffel** [comment]
thanks for following up. actually, I think we can close this. I noticed when I switched the URL to a https:// things worked fine. but, when it was setup with http:// the buttons didn't work.
