### ISSUE TITLE
cannot update page after editing code in the injection pane

### ISSUE THREAD

**Issue by derek-adair** [TryGhost/Ghost#17722]
### Issue Summary

The update button is still disabled after changing code in the injection pane.  I must edit content in the editor before I can publish changes.

### Steps to Reproduce

1. Add or update code in the injection pane
2. Update button is disabled
3. modify page
4. Update button is active

### Ghost Version

5.53.3

### Node.js Version

16.20.1

### How did you install Ghost?

docker ghost:5-alpine

### Database type

MySQL 8

### Browser & OS version

Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/116.0

### Relevant log / error output

```shell
n/a
```

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by shaunroselt** [comment]
This is actually not completely true.

I think the issue is worse than this.

It actually autosaves changes that you make in the "Code Injection" panel and that's why the "Update" button is disabled, because the changes are already saved (autosaved).

Here's a short video showing it:
https://github.com/TryGhost/Ghost/assets/5418178/ba02f083-eccc-4ca5-a40c-33a26ffc3edb

Notice that I never click on the "Update" button in my video. I simply make changes to the "Code Injection" panel and then refresh the page.

**Comment by shaunroselt** [comment]
It's also actually not just the "Injection Code", but also other things.

Such as the "Twitter Card" as can be seen in this video:
https://github.com/TryGhost/Ghost/assets/5418178/da55e410-7c3f-4da4-91f6-3f687a4c24a2

Again. Notice in the video that I never click on the "Update" button, but the changes are still being saved.

**Comment by derek-adair** [comment]
Yikes.  This is quite dangerous and not intuitive.  100% would recommend making an actual save button.

I was on the fence about disabling this feature -- but am no longer.  This i not something I am comfortable exposing to clients who don't know what they are doing.  The potential for this to break a live deploy is _huge_.  This isn't even considering the security implications.

**Comment by alfredlouisw8** [comment]
hi, i want to contribute to this issue. Can you assign this to me please? 

Also what's the expected behaviour? should I create an actual save button?

**Comment by shaunroselt** [comment]
Personally, I think it should simply work with the "Update" button top right. Same as with everything else on that page.

There shouldn't be a separate save button specifically for those items.

**Comment by derek-adair** [comment]
ANYTHING is better than auto save on keystroke.  The all-in-one update is what I would lean towards.
