### ISSUE TITLE
Substack Import Fails with "Invalid file type"

### ISSUE THREAD

**Issue by mgattozzi** [TryGhost/Ghost#17729]
### Issue Summary

I want to import users and posts from my old substack account, but I get an "Invalid File" error despite it being literally the zipfile I got from substack and it's not invalid as I can decompress and look at the content inside.

### Steps to Reproduce

1. Open the Substack Importer in the Labs section of Ghost
2. Enter a valid URL for a substack
3. Try to upload Zip File
4. Have it fail and look like this
![Screenshot 2023-08-15 130907](https://github.com/TryGhost/Ghost/assets/3514399/bcc81054-0501-456b-a63f-76d544767c15)

### Ghost Version

5.59.1

### Node.js Version

18.16.1

### How did you install Ghost?

Ubuntu v20.04.4 LTS, manually installed

### Database type

MySQL 5.7

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by daniellockyer** [comment]
Hi @mgattozzi - thanks for the report. We're looking at a fix for this and should get back to you soon 🙂

**Comment by PaulAdamDavis** [comment]
Hi @mgattozzi, I have just pushed a fix for this.

**Comment by daniellockyer** [comment]
@mgattozzi We pushed the fix to the separate project, so it should already be live. (It's not a feature within Ghost)

**Comment by mgattozzi** [comment]
Oh! Excellent thanks so much
