### ISSUE TITLE
srcset missing for header images in new editor

### ISSUE THREAD

**Issue by cathysarisky** [TryGhost/Ghost#17753]
### Issue Summary

Image content generated for the new split header layout does not include a srcset.  Huge images load by default.

### Steps to Reproduce

Create a new page with a header card with the new split layout.  
Be lazy and drag a huge image into the image blog, assuming Ghost will resize it.
Publish. Inspect the result.  Here's the outcome:

```
<div class="kg-header-card-content">
                
        <picture><img class="kg-header-card-image" src="https://www.spectralwebservices.com/content/images/2023/08/ghost-website-1.png" alt=""></picture>
    
                <div class="kg-header-card-text ">
                    <h2 id="take-your-ghost-blog-and-newsletter-to-the-next-level" class="kg-header-card-heading" style="color: #FFFFFF;" data-text-color="#FFFFFF"><span>Take your Ghost blog and newsletter to the next level.</span></h2>
                    <h3 id="let-our-team-handle-the-technology-while-you-focus-on-creating" class="kg-header-card-subheading" style="color: #FFFFFF;" data-text-color="#FFFFFF"><span>Let our team handle the technology while you focus on creating.</span></h3>
                    <a href="https://www.spectralwebservices.com/contact/" class="kg-header-card-button " style="background-color: #ffffff;color: #000000;" data-button-color="#ffffff" data-button-text-color="#000000">Contact Us</a>
                </div>
            </div>
```
Because there's no srcset on image, it loads at 2000px wide.  That's silly for anything less than a 4k screen, and really silly for the 1200px wide screen I prefer.  My browser actually rendered it at ~500px.

### Ghost Version

5.59.1

### Node.js Version

Ghost Pro and 16.something

### How did you install Ghost?

ghost-cli and ghost pro

### Database type

MySQL 8

### Browser & OS version

Chrome, recent, windows 10

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by witherScript** [comment]
@cathysarisky stoked to work on this issue, can you please assign this to me? If there are any specific guidelines or tasks you'd like me to follow outside of the contributions doc, please let me know.

**Comment by cathysarisky** [comment]
I’m not the Ghost core team, sorry. :)Sent from my iPhoneOn Aug 18, 2023, at 2:42 AM, Genesis ***@***.***> wrote:﻿
@cathysarisky stoked to work on this issue, can you please assign this to me? If there are any specific guidelines or tasks you'd like me to follow outside of the contributions doc, please let me know.

**Comment by witherScript** [comment]
@daniellockyer hey, would be stoked to work on this issue, can you please assign it to me? I don't intend to muddy the issue thread

**Comment by cathysarisky** [comment]
I'll add onto this one instead of opening another bug - these header images are also missing the lazy loading attribute that other body content gets automagically.
