### ISSUE TITLE
"@page.show_title_and_feature_image is not used" is displayed as an error

### ISSUE THREAD

**Issue by javierencalada** [TryGhost/Ghost#17777]
### Issue Summary

Hello!, hope you are doing well.

On a large amount of themes we are receiving this kind of error (probably 70 - 80% of themes in the Ghost marketplace, will get this as well):
![image](https://github.com/TryGhost/Ghost/assets/5891905/58aacda6-4b77-41ca-933a-bd25aecc864a)

Multiple customers are assuming the theme/platform do not work as expected, so we need to explain to every customer that is a beta feature and they can safely ignore it for the moment.

After checking the info about this error: https://ghost.org/docs/themes/helpers/page/ this setting is only available when **"beta editor setting" is "ON"**  from the Labs section, so this error shouldn't appear or at least should be displayed as a an "information tooltip" but not as an error.

I think a quick solution would be to remove it as a "critical error", but a good alternative would be to insert a new option into **"package.json"** to mark the theme as compatible or not **(similar to config -> "card_assets": true)**, and finally evaluate if the syntax is correct on the page.hbs file.

Other Ghost Authors as @fueko are getting similar issues on https://github.com/TryGhost/Ghost/issues/17745 that could be related.

Thank you very much!

### Steps to Reproduce

Upload any theme that do not include: 
`{{#match @page.show_title_and_feature_image}}
...content...
{{/match}}`

### Ghost Version

5.59.1

### Node.js Version

v18.16.1

### How did you install Ghost?

localhost

### Database type

SQLite3

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by benshaaw** [comment]
This being labeled as an error does feel misleading. In the past, an error would indicate the upload/activation of a theme has failed, whereas a warning could be raised by the upload/activation could still suceed.

Would it be possible to demote this error level, or better yet, only raise it if it is applicable to the current installation and/or theme? Our theme doesn't have a `page.hbs` partial, so doesn't seem relevant to us.

**Comment by benshaaw** [comment]
> The only errors displayed in Ghost admin (when not in dev mode) are errors. We've got two flavors of those, fatal and nonfatal. Fatal errors are what you mentioned - a warning where the theme cannot be activated - while nonfatal errors allow the user to still activate the theme.
> 
> We don't currently have a way to check for use of the `@page`-related features when activating a theme as theme activation only runs the theme through `gscan`.
> 
> The intent here was to call out _potential_ loss of functionality, as indicated in the message. We can be more clear about that in the error message that is displayed and I've updated `gscan` to specifically call out the beta editor for this case.
> 
> As theme devs update their themes to use the `@page` feature(s) we both ensure that the themes are up to date with Ghost development and that Ghost+theme users get the best experience. This is definitely our recommendation.
> 
> Also worth noting is that while this only impacts the beta editor at this moment in time, the new editor will not always be in beta.

Thank you for the clarification on the difference of errors - I wasn't aware that there was a sub-class of errors that were non-fatal - this is really helpful!

Would it be possible to more clearly differentiate between the two in the future?

On the `gscan` issue, would it be possible to check if the given theme has a `page.hbs` defined before throwing errors, or would the `@page` helper potentially be used outside of the `page.hbs` partial?

**Comment by 9larsons** [comment]
Fatal errors are rare and for the time being we don't see a need to change how they are handled, as we strictly do not allow the user to activate a theme with them.

For the `gscan` error originally posted, we aren't particular about the filename. It could check `page.hbs`, `post.hbs` (as a fallback), or related partials.

I've updated the error message to specifically call out the beta editor without requiring users to click into the docs to find more info. I think this is a reasonable and quick solution for the time being while themes are being updated.

**Comment by benshaaw** [comment]
Thanks for the clarification @9larsons - I think that sounds like a reasonable resolution

**Comment by 9larsons** [comment]
Glad that works for you. I'm hung up on what appears to be a `yarn` bug at the moment so I'm not certain this'll make it in this week's release, sorry.

**Comment by javierencalada** [comment]
Thank you very much @9larsons for all the information and fixes you shared here!

In our case, the customers first impression was: "the theme is not working". This is mainly related to the UI, is there any plan to change the wording and colors of that lightbox?

I remember in the past those warnings were marked with orange and some words as "info" or "warnings", so maybe is not a bad idea to work on that first impression for non-tech customers.

**Comment by 9larsons** [comment]
The `gscan` changes were incorporated a few weeks ago with that last commit. I'm going to close this and please open a new issue if you feel there's necessary changes yet.
