### ISSUE TITLE
Staff new sign ups email notifications has a wrong from email address

### ISSUE THREAD

**Issue by MFYDev** [TryGhost/Ghost#17799]
### Issue Summary

Explain roughly what’s wrong: 

the new sign up notification from email address is [ghost@myowndomain.com](mailto:ghost@myowndomain.com) but I have already set up all from email address as another address. Tested on comments notification and it works well but just new sign up is sending from the wrong address. It directly caused the email went to the spam folder

What did you expect to happen?
The new sign up notification email should have a from address at least same as the newsletter one or the one I set in the config.

### Steps to Reproduce

1. go to Settings → Staff → click into the owner → turn on new sign ups notification
2. a new user sign up, and the notification email will go into the spam, the email address is [ghost@myowndomain.com](mailto:ghost@myowndomain.com)

### Ghost Version

5.59.4

### Node.js Version

18

### How did you install Ghost?

Ubuntu npm production

### Database type

MySQL 8

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by markstos** [comment]
The same support request has been submitted on the Ghost Forum. I've asked the author there to delete this duplicate. 

https://forum.ghost.org/t/staff-new-sign-ups-email-notifications-has-a-wrong-from-email-address/40671
