### ISSUE TITLE
StaffServiceEmails.js (eventually) sends new member notifications with wrong styles

### ISSUE THREAD

**Issue by verement** [TryGhost/Ghost#17937]
### Issue Summary

Sometimes Ghost sends new member email notifications with incorrect styles, resulting in ugly blue backgrounds like this:

![Screenshot 2023-09-01 at 4 37 19 PM@0 5x](https://github.com/TryGhost/Ghost/assets/710176/6d714f87-d2b8-47ff-a839-feec46c6fc7f)

The `StaffServiceEmails` class sends new member email notifications that initially show no problem. However, at some point, it appears the `styles` Handlebars partial (from ghost/**staff**-service/lib/email-templates/partials/styles.hbs) gets overwritten with the styles from ghost/**email**-service/lib/email-templates/partials/styles.hbs. My guess is that they both use the same Handlebars instance, but the partials for `StaffServiceEmails` are only registered once in its constructor.

### Steps to Reproduce

1. Enable new member email notifications.
2. Wait for new sign-ups.
3. Initially the notification messages appear with correct styles.
4. Eventually the notification messages will show incorrect styles.

### Ghost Version

5.59.4

### Node.js Version

16.20.2

### How did you install Ghost?

Ubuntu 22.04

### Database type

MySQL 8

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by asenseofpradhyu** [comment]
@daniellockyer  how to setup magic link in local ?

**Comment by SimonBackx** [comment]
Thank you for reporting this issue! This is fixed and will be released in the next release of Ghost on Friday
