### ISSUE TITLE
Most icons in the editor's dark mode modals have the wrong shade

### ISSUE THREAD

**Issue by stromfeldt** [TryGhost/Ghost#17987]
### Issue Summary

While in dark mode, click on an image card, audio card, gallery card, etc., and you'll see that most of the icons in the modals are dark on dark rather than light on dark.

![Xnapper-2023-09-06-14 18 08](https://github.com/TryGhost/Ghost/assets/27488257/30cc77c3-9bbe-4dfd-a626-ec75bb89c296)

![Xnapper-2023-09-06-14 18 22](https://github.com/TryGhost/Ghost/assets/27488257/7fd45a6c-394f-4bbc-ab40-d3435c70b9bd)

![Xnapper-2023-09-06-14 18 40](https://github.com/TryGhost/Ghost/assets/27488257/33ef647f-46fa-4e34-812e-5023d6f14bf0)

![Xnapper-2023-09-06-14 19 21](https://github.com/TryGhost/Ghost/assets/27488257/1a595af8-8227-42f2-b005-06bb2d9cf61a)

I haven't looked, but I presume I've missed several others.

### Steps to Reproduce

1. Click on a card in dark mode to pull up its modal
2. See the dark on dark icons

### Ghost Version

5.61.1

### Node.js Version

Yes

### How did you install Ghost?

Ghost(Pro)

### Database type

MySQL 5.7

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by rishuraj1** [comment]
@stromfeldt  @daniellockyer  hello, I want to fix this issue. Can you please assign this to  me. also, can you give me a head start. How do I reproduce this issue ?

**Comment by shreshthmohan** [comment]
Some svg icons inside Koenig action bar have `.fill-white` and some others have `.fill-white-no-conflict`

In **light** mode, `.fill-white-no-conflict` applies `#ffffff` and the icons with `.fill-white` aren't affected as `.fill-white` does not add any styles in light mode. https://github.com/TryGhost/Ghost/blob/c6cf4fc2f30c81f867bd2933afaf20b3399d8584/ghost/admin/app/styles/spirit/_icons.css#L242-L243
https://github.com/TryGhost/Ghost/blob/c6cf4fc2f30c81f867bd2933afaf20b3399d8584/ghost/admin/app/styles/patterns/global.css#L28

In **dark** mode, `.fill-white-no-conflict` applies `#15171a`. This is what cause the reported problem.

https://github.com/TryGhost/Ghost/blob/c6cf4fc2f30c81f867bd2933afaf20b3399d8584/ghost/admin/app/styles/app-dark.css#L79

In **dark** mode, icons with `.fill-white` inside get `#e3e6e8` from:

https://github.com/TryGhost/Ghost/blob/c6cf4fc2f30c81f867bd2933afaf20b3399d8584/ghost/admin/app/styles/components/koenig-dark.css#L33-L36

**Comment by shreshthmohan** [comment]
@daniellockyer the fix I have added works. But I am curious if there's a plan to move to a utility-first CSS framework like Tailwind CSS?

**Comment by kevinansfield** [comment]
This was fixed in https://github.com/TryGhost/Ghost/commit/1b1d871374e88324c37b64e32ccbca6a1ed9116b and released in Ghost 5.63.0
