### ISSUE TITLE
Posts with visibility="members" are shown in search results

### ISSUE THREAD

**Issue by McLamy** [TryGhost/Ghost#18001]
### Issue Summary

We have the case that all member related posts are hidden unless you are logged in. But if you use the default ghost search the hidden posts are listed in the search results. The search results should differ whether you are logged in or not.

### Steps to Reproduce

1. Create a members only post
2. Hide it from your blog with visibility="members"
3. Logout
4. Type the title of your created post into the search input field

### Ghost Version

5.61.3+moya

### Node.js Version

Ghost Pro

### How did you install Ghost?

Ghost Pro

### Database type

MySQL 5.7

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by daniellockyer** [comment]
I believe this is working as intended, so I'm not inclined to call this a bug. Feature requests should be posted in the [forum](https://forum.ghost.org/c/ideas/5) 🙂
