### ISSUE TITLE
Slow dashboard query for large memberships

### ISSUE THREAD

**Issue by samrap** [TryGhost/Ghost#18044]
### Issue Summary

We are self-hosting Ghost on AWS and running into a scalability issue on the dashboard.

It looks like when loading the post editor, a handful of XHR requests are made to the back end to obtain additional data.

One of these hits the following API endpoint:

`/ghost/api/admin/newsletters/?status=active&limit=all&include=count.active_members`

In our case, there are over 100k members and this query takes >20s to load on average. Here is the query:

```
# Query_time: 21.560752  Lock_time: 0.000270 Rows_sent: 7  Rows_examined: 2778958
use prodghost;
SET timestamp=1694200263;
select `newsletters`.*, (select count(`members_newsletters`.`id`) from `members_newsletters` inner join `members` on `members`.`id` = `members_newsletters`.`member_id` where members_newsletters.newsletter_id = newsletters.id and `members`.`email_disabled` = false) as `count__active_members` from `newsletters` order by sort_order ASC, created_at ASC, id ASC;
```

The problem with this query taking unreasonably long is that the publish button and other features are disabled until this request completes. So our admin users are led to believe they "can't" publish their posts.

AFAICT this query exists to get the number of active users to be displayed in the messaging before publishing. 

Is there a reason for counting all active members other than UX? If not, might I suggest eliminating this query after a certain number of members is reached and changing the publisher messaging to suit? 

Alternative potential fixes: 

- Cache active member counts
- Improve query performance 
- Utilize progressive enhancement to make this API request non-critical for functionality 

I understand this is unique for just a few sites on Ghost at this time (we had no issues until passing the 100k member threshold) but this will likely cause issues for any platform with a large user base which will (hopefully) be more common as Ghost grows! 

### Steps to Reproduce

1. Have large number of members
2. Attempt to edit a post

### Ghost Version

5.60.0

### Node.js Version

16.18.0

### How did you install Ghost?

Ubutnu, AWS, RDS Aurora DB

### Database type

MySQL 8

### Browser & OS version

All

### Relevant log / error output

```shell
# Query_time: 21.560752  Lock_time: 0.000270 Rows_sent: 7  Rows_examined: 2778958
use prodghost;
SET timestamp=1694200263;
select `newsletters`.*, (select count(`members_newsletters`.`id`) from `members_newsletters` inner join `members` on `members`.`id` = `members_newsletters`.`member_id` where members_newsletters.newsletter_id = newsletters.id and `members`.`email_disabled` = false) as `count__active_members` from `newsletters` order by sort_order ASC, created_at ASC, id ASC;
```

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by samrap** [comment]
We're currently caching the endpoint (`/ghost/api/admin/newsletters/`, all query strings) for 15 minutes to alleviate some of the delays while this performance issue is worked out.

**Comment by markstos** [comment]
@samrap If you have MySQL 8.0.18 or newer, could you run this query and paste the result? It will help to understand how MySQL executing the query on such a table and using indexes.. or not. This is your query with "EXPLAIN ANALYZE " prefixed.

```
EXPLAIN ANALYZE select `newsletters`.*, (select count(`members_newsletters`.`id`) from `members_newsletters` inner join `members` on `members`.`id` = `members_newsletters`.`member_id` where members_newsletters.newsletter_id = newsletters.id and `members`.`email_disabled` = false) as `count__active_members` from `newsletters` order by sort_order ASC, created_at ASC, id ASC;
```

**Comment by samrap** [comment]
@markstos does this help?

```
-> Sort: newsletters.sort_order, newsletters.created_at, newsletters.id  (cost=0.95 rows=7) (actual time=0.095..0.124 rows=7 loops=1)
    -> Table scan on newsletters  (cost=0.95 rows=7) (actual time=0.047..0.064 rows=7 loops=1)
-> Select #2 (subquery in projection; dependent)
    -> Aggregate: count(members_newsletters.id)  (actual time=3144.770..3144.771 rows=1 loops=7)
        -> Nested loop inner join  (cost=24859.04 rows=4104) (actual time=502.030..3141.465 rows=42312 loops=7)
            -> Filter: (members.email_disabled = false)  (cost=10494.05 rows=9876) (actual time=0.019..75.984 rows=98226 loops=7)
                -> Table scan on members  (cost=10494.05 rows=98763) (actual time=0.018..64.572 rows=101275 loops=7)
            -> Filter: (members_newsletters.newsletter_id = newsletters.id)  (cost=1.04 rows=0) (actual time=0.030..0.031 rows=0 loops=687582)
                -> Index lookup on members_newsletters using members_newsletters_member_id_foreign (member_id=members.id)  (cost=1.04 rows=4) (actual time=0.029..0.030 rows=3 loops=687582)
```

**Comment by markstos** [comment]
Perfect @samrap. 

It shows what I suspected than an expensive full table scan is being used, in this case on members.email_disabled. 

If you are comfortable with doing so, you could try adding an index on that column and re-testing the SQL query, with and without EXPLAIN ANALYZE. If Ghost later adds an index there, you should remove the index before upgrading so it doesn't interfere with upgrade automation.

**Comment by samrap** [comment]
This is much better (~4.5s). Thanks for the help! @markstos

**Comment by markstos** [comment]
@samrap To confirm: Adding the index on `members(email_disabled)` solved the performance problem? 

That's great. I may see about making a PR to add that index for everyone.

**Comment by samrap** [comment]
It's a noticeable improvement. Here's my summary/thoughts:

- Adding an index reduced the execution time from ~22s to ~5s
- While this is a drastic improvement, it is still quite slow considering there are several XHR requests to the backend and this is just one of them
- All things considered, it's ~8s after initial render to have a fully functional post editor
- We'll continue to cache the HTTP response in addition to maintaining the index

Based on this I recommend adding that index as it is definitely an improvement 👍 

I wonder if you can look directly into the performance of your largest cloud users to get more insights? I'm genuinely curious since this issue only causes problems around 100k members.

**Comment by markstos** [comment]
@samrap There might be more opportunities for indexes that are harder to see without the big scale that you have. 

MySQL has an option to start the server with a "slow query" log enabled (https://dev.mysql.com/doc/refman/8.0/en/slow-query-log.html),  and the Ghost logs already log some slow queries.

If you see more indication of slow DB queries that might benefit, let us know. 

When EXPLAIN ANALYZE shows a table scan for more than 10,000 rows, that's a strong indicator than index would help.

**Comment by samrap** [comment]
I'll keep you posted. We enabled slow query logs last week and so far it was only showing this one. But we'll be monitoring and I'll definitely update you if we see any others. 

I don't expect this to be a huge priority for you guys and really appreciate the attention/help.

**Comment by markstos** [comment]
@kevinansfield Is a DB migration the best way to add a new index ( [like this one](https://github.com/TryGhost/Ghost/pull/12108/files)) the best way to add a new index or is there a better way?

**Comment by shalabhtayal** [comment]
`SELECT n.id, COUNT(mn.id) AS count_active_members
FROM newsletters n
LEFT JOIN (
    SELECT DISTINCT mn.newsletter_id, mn.member_id
    FROM members_newsletters mn
    JOIN members m ON mn.member_id = m.id
    WHERE m.email_disabled = false
) AS active_members ON n.id = active_members.newsletter_id
GROUP BY n.id
ORDER BY n.sort_order ASC, n.created_at ASC, n.id ASC;
`

In this query:

We use a subquery to select distinct pairs of newsletter_id and member_id from the members_newsletters table for members who have email_disabled set to false. This subquery filters the active members efficiently.

We then left join the newsletters table with this subquery on the newsletter_id to match newsletters with their active members. Using a LEFT JOIN ensures that newsletters without active members will still be included in the result.

We use the COUNT() function to count the number of active members for each newsletter.

Finally, we group the results by newsletter_id (renamed as id in the output) and order the result set as requested.

This query should perform more efficiently than the original one, especially when dealing with a large number of members, as it reduces the need for complex subqueries and calculations during the join operation.

**Comment by markstos** [comment]
@samrap Could you run both the old and new queries and see how the results and and execution time compare for you?

```sql

SELECT 
  `newsletters`.*, 
  (
    select 
      count(`members_newsletters`.`id`) 
    from 
      `members_newsletters` 
      inner join `members` on `members`.`id` = `members_newsletters`.`member_id` 
    where 
      members_newsletters.newsletter_id = newsletters.id 
      and `members`.`email_disabled` = false
  ) as `count__active_members` 
from 
  `newsletters` 
order by 
  sort_order ASC, 
  created_at ASC, 
  id ASC;

--------------------------------------

SELECT 
  n.id, 
  COUNT(mn.id) AS count_active_members 
FROM 
  newsletters n 
  LEFT JOIN (
    SELECT 
      DISTINCT mn.newsletter_id, 
      mn.member_id 
    FROM 
      members_newsletters mn 
      JOIN members m ON mn.member_id = m.id 
    WHERE 
      m.email_disabled = false
  ) AS active_members ON n.id = active_members.newsletter_id 
GROUP BY 
  n.id 
ORDER BY 
  n.sort_order ASC, 
  n.created_at ASC, 
  n.id ASC;
```

**Comment by samrap** [comment]
@markstos Apologies for the late reply

That query gives an error `Unknown column 'mn.id' in 'field list'`, so I tried the following instead:

```
SELECT 
  n.id, 
  COUNT(active_members.member_id) AS count_active_members 
FROM 
  newsletters n 
  LEFT JOIN (
    SELECT 
      DISTINCT mn.newsletter_id, 
      mn.member_id 
    FROM 
      members_newsletters mn 
      JOIN members m ON mn.member_id = m.id 
    WHERE 
      m.email_disabled = false
  ) AS active_members ON n.id = active_members.newsletter_id 
GROUP BY 
  n.id 
ORDER BY 
  n.sort_order ASC, 
  n.created_at ASC, 
  n.id ASC;
```

About the same time.
