### ISSUE TITLE
Custom CSS for Native Search

### ISSUE THREAD

**Issue by broksonic21** [TryGhost/Ghost#18088]
### Issue Summary

Currently Native Search is inside an iframe (sodo-search-root) so there's no exposed (as far as I can tell) way to override the css with hacky javascript

Is there a documented way to override native search popup CSS, or can an extra paremeter/configuration to pass in additional CSS be added?

### Steps to Reproduce

Turn on native search via #!/search

Try to write css in a theme to override search popup (say, max-width)

### Ghost Version

5.62.0

### Node.js Version

18.17.1

### How did you install Ghost?

docker

### Database type

MySQL 8

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by markstos** [comment]
This question is better suited for the Ghost forum:
https://forum.ghost.org/

If you don't get an answer from the community there, you can post the feature request in the Ideas category.
