### ISSUE TITLE
config.production.json portal disabled entirely by setting "url": false is invalid

### ISSUE THREAD

**Issue by JaydenForYou** [TryGhost/Ghost#18128]
### Issue Summary

config.production.json portal disabled entirely by setting "url": false is invalid

### Steps to Reproduce

1.config.production.json portal set url to false
2.ghost restart
3.
![image](https://github.com/TryGhost/Ghost/assets/53374430/f35a2845-6ba0-43b5-97b1-74fdd9559aba)

### Ghost Version

5.62.0

### Node.js Version

16.19.1

### How did you install Ghost?

GHOST CLI & UBUNTU

### Database type

MySQL 5.7

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by daniellockyer** [comment]
The correct way to disable Portal is to disable Members via the settings, or you can hide the Portal icon 🙂

**Comment by JaydenForYou** [comment]
> The correct way to disable Portal is to disable Members via the settings, or you can hide the Portal icon 🙂

tks. Problem fixed.
