### ISSUE TITLE
the page crased while searching "c++" keyword

### ISSUE THREAD

**Issue by JaydenForYou** [TryGhost/Ghost#18133]
### Issue Summary

the page crased while searching "c++" keyword

### Steps to Reproduce

1. the page crased while searching "c++" keyword
2. 
![image](https://github.com/TryGhost/Ghost/assets/53374430/d7f7965f-488f-486e-a634-2674b68b20d4)

### Ghost Version

5.62.0

### Node.js Version

16.19.1

### How did you install Ghost?

GHOST CLI & UBUNTU

### Database type

MySQL 5.7

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by JaydenForYou** [comment]
> ### Issue Summary
> the page crased while searching "c++" keyword
> 
> ### Steps to Reproduce
> 1. the page crased while searching "c++" keyword
> 
> ![image](https://user-images.githubusercontent.com/53374430/267916955-d7f7965f-488f-486e-a634-2674b68b20d4.png)
> 
> ### Ghost Version
> 5.62.0
> 
> ### Node.js Version
> 16.19.1
> 
> ### How did you install Ghost?
> GHOST CLI & UBUNTU
> 
> ### Database type
> MySQL 5.7
> 
> ### Browser & OS version
> _No response_
> 
> ### Relevant log / error output
> _No response_
> 
> ### Code of Conduct
> * [x]  I agree to be friendly and polite to people in this repository

search "+c" also crashed

**Comment by JaydenForYou** [comment]
> ### Issue Summary
> the page crased while searching "c++" keyword
> 
> ### Steps to Reproduce
> 1. the page crased while searching "c++" keyword
> 
> ![image](https://user-images.githubusercontent.com/53374430/267916955-d7f7965f-488f-486e-a634-2674b68b20d4.png)
> 
> ### Ghost Version
> 5.62.0
> 
> ### Node.js Version
> 16.19.1
> 
> ### How did you install Ghost?
> GHOST CLI & UBUNTU
> 
> ### Database type
> MySQL 5.7
> 
> ### Browser & OS version
> _No response_
> 
> ### Relevant log / error output
> _No response_
> 
> ### Code of Conduct
> * [x]  I agree to be friendly and polite to people in this repository

**Comment by JaydenForYou** [comment]
search "+c" "C}[" "C]/\" "+/N" also crashed

**Comment by JaydenForYou** [comment]
> search "+c" "C}[" "C]/" "+/N" also crashed

enther these keywords except for double quotation marks

**Comment by markstos** [comment]
Thanks for the report @JaydenForYou. There was a regular expression escaping bug that I was able to reproduce and have prepared a pull request to fix. I need another developer to test it before it is merged.

**Comment by JaydenForYou** [comment]
> Thanks for the report @JaydenForYou. There was a regular expression escaping bug that I was able to reproduce and have prepared a pull request to fix. I need another developer to test it before it is merged.

let's see if i can help you.i got someone with dev enviroment to test it.

**Comment by JaydenForYou** [comment]
> Thanks for the report @JaydenForYou. There was a regular expression escaping bug that I was able to reproduce and have prepared a pull request to fix. I need another developer to test it before it is merged.

passed.bug fixed.tks

**Comment by markstos** [comment]
Fix released: https://github.com/TryGhost/Ghost/releases/tag/v5.65.0
