### ISSUE TITLE
Audio Element Not Consistently Created When Adding to New Posts

### ISSUE THREAD

**Issue by Emporea** [TryGhost/Ghost#18192]
### Issue Summary

The problem arises during the process of adding an "Audio" Element when creating a new post. In certain instances, the file picker dialog appears, but its interaction does not seem to affect the outcome. Even when selecting a file through the file picker, the audio element is not created as expected on the initial attempt and its just empty like this:

![image](https://github.com/TryGhost/Ghost/assets/21969523/9770df0c-c162-4296-b95b-8893c7f680c6)

### Steps to Reproduce

1.     Navigate to the "Create New Post" section.
2.     Select the "Audio" Element option.
3.     Observe that the file picker dialog appears.
4.     Attempt to select a file or take note of the behavior.
5.     Check if the audio element is successfully added to the post on the first attempt.

### Ghost Version

5.63

### Node.js Version

18.17.1

### How did you install Ghost?

npm install ghost-cli -g

### Database type

Other

### Browser & OS version

Firefox Arch

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by markstos** [comment]
Hello fellow Arch user. Have you tried an alternate browser to see if the behavior is more consistent? Are you using the legacy editor or the beta editor? Please try the other.

**Comment by daniellockyer** [comment]
I'd suggest trying the beta editor (which isn't going to be in beta status for much longer). We're far more likely to fix issues in that vs the existing editor. Let me know if you can repro in that and we'll re-open the issue
