### ISSUE TITLE
Unable to Assign Tags in Post Settings After Installing Dependency

### ISSUE THREAD

**Issue by dipenappscrip** [TryGhost/Ghost#18202]
### Issue Summary

I have recently installed a dependency, and while checking the post settings in the editor, I noticed that there is no option available to assign tags. I followed the installation process as recommended for source-code.

### Steps to Reproduce

Installed the dependency according to the provided instructions.
Navigated to "posts -> editor -> post settings" section.

I have with  owner role

![image](https://github.com/TryGhost/Ghost/assets/82133137/ca30b584-32fb-46f6-aa9e-a5c7a6f159ce)
![image](https://github.com/TryGhost/Ghost/assets/82133137/5393f51f-d448-4d33-9dac-50669494eb25)

### Ghost Version

5.58.0

### Node.js Version

18.17.0

### How did you install Ghost?

ubuntu

### Database type

MySQL 5.7

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by dipenappscrip** [comment]
where I need to add ember-power-calendar-moment dependency ?
in admin/ or admin/lib/ember-power-calendar-utils
I tied both but still it give same error

**Comment by markstos** [comment]
When you said that you "recently installed a dependency", what was the command that you ran to do that, and what directory were you in at the time?

**Comment by yaizudamashii** [comment]
I'm also facing the same issue with our forked and modified branch, but ghost/admin/lib has ember-power-calendar-moment and ember-power-calendar-utils.  According to ChatGPT the folders are structured correctly, but I am still getting the same error as the poster of this issue.
