### ISSUE TITLE
Search bar closes forever if certain characters are typed

### ISSUE THREAD

**Issue by javamagiciancom** [TryGhost/Ghost#18272]
### Issue Summary

I just run into this bug on my own [site](https://javamagician.com/), and local environment. I tried to replicate it on other Ghost site (mostly, from Ghost official themes page, with several themes). My site is a modification of Dawn, but it also fails on Casper and probably others too. This might be a "themes" problem, but since it affects more than one, I'm posting it here

Version: [5.64.0](https://github.com/TryGhost/Ghost/releases/tag/v5.64.0)
    Environment: production
    Database: mysql8

### Steps to Reproduce

1. Open search bar
2. Type "(" followed by any other character alphanumeric character Example: "(s"
3. The search bar should instantly close and it wont open again unless the page gets reloaded.

One would expect to have the search bar accept the input and search the term or at least be able to reopen the search bar again.

### Ghost Version

5.64.0

### Node.js Version

18.17.1

### How did you install Ghost?

Local install on my dev environment on Windows. For production, I followed the official installation guide for Ubuntu 20.04

### Database type

MySQL 8

### Browser & OS version

At least Firefox 117.0.1, Google Chrome 116.0.5845.111, Microsoft Edge Version 116.0.1938.69 (Official build) (64-bit)

### Relevant log / error output

```shell
SyntaxError: unterminated parenthetical
    oe PopupModal.js:260
    ue PopupModal.js:273
    ie PopupModal.js:311
    React 7
    unstable_runWithPriority scheduler.production.min.js:18
    React 10
    unstable_runWithPriority scheduler.production.min.js:18
    React 14
    unstable_runWithPriority scheduler.production.min.js:18
    React 6
    value Frame.js:22
    <anonymous> Frame.js:10
    value Frame.js:6
    React 2
    unstable_runWithPriority scheduler.production.min.js:18
    React 4
    unstable_runWithPriority scheduler.production.min.js:18
    React 6
    clickHandler App.js:88
    value App.js:96
    value App.js:94
    value App.js:76
    value App.js:25
    React 2
    unstable_runWithPriority scheduler.production.min.js:18
    React 9
    <anonymous> index.js:36
    <anonymous> index.js:47
    Webpack 3
react-dom.production.min.js:216:199
```
```


### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by markstos** [comment]
This was recently fixed and will appear in the next release:

https://github.com/TryGhost/Ghost/pull/18151

**Comment by markstos** [comment]
Fix released: https://github.com/TryGhost/Ghost/releases/tag/v5.65.0

**Comment by daniellockyer** [comment]
😀
