### ISSUE TITLE
Error uploading image to admin-api (

### ISSUE THREAD

**Issue by Hailst0rm1** [TryGhost/Ghost#18284]
### Issue Summary

Regarding to the code at https://github.com/TryGhost/Ghost/blob/098f4353a7a50ced3b55acf569738731258cb30b/ghost/core/test/e2e-api/admin/images.test.js#L29:

```ts
/**
 *
 * @param {object} options
 * @param {Buffer} options.fileContents
 * @param {string} options.filename
 * @param {string} options.contentType
 * @param {string} [options.ref]
 * @returns
 */
const uploadImageRequest = ({fileContents, filename, contentType, ref}) => {
   const form = new FormData();
   form.append('file', fileContents, {
       filename,
       contentType
   });
   form.append('purpose', 'image');
   if (ref) {
       form.append('ref', ref);
   }
   return agent
```

To get around CORS for my plugin I instead use my own fetch function - however it complains that the data in `fileContents` is a buffer and not a blob (which is correct according to the code and admin-api documentation). My issue is therefore why this works (?) in your code but not mine.

### Steps to Reproduce

You can find the entire conversation on forums as well:
https://forum.ghost.org/t/uploading-images-to-ghost-admin-api/41348/7

Code:

```ts
			const fileContent = await fs.readFile(imagePath);
			const contentType = "image/png"
			const formData = new FormData();
			formData.append("file", fileContent, {
				filename,
				contentType
			});
			formData.append("purpose", "image");
			formData.append("ref", imagePath);

			try {
				const response = await fetch(`${settings.url}/ghost/api/admin/images/upload/`, {
					method: "POST",
					headers: {
						"Content-Type": "multipart/form-data",
						Authorization: `Ghost ${token}`,	
					},
					body: formData
				});
				// Error handling etc
```
imagePath = Full path to image

### Ghost Version

Ghost-CLI version: 1.24.2 Ghost version: 5.59.1

### Node.js Version

v18.13.0

### How did you install Ghost?

npm, I have it both on my windows and linux host

### Database type

MySQL 8

### Relevant log / error output

```shell
Uncaught (in promise) TypeError: Failed to execute 'append' on 'FormData': parameter 2 is not of type 'Blob'.
    at eval (VM1417 plugin:obsidian-ghost-publish:21562:18)
    at Generator.next (<anonymous>)
    at fulfilled (VM1417 plugin:obsidian-ghost-publish:50:24)
```

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by markstos** [comment]
As you pointed out, Ghost has related code that works, so this is not clearly a bug in Ghost. And the error you are reporting here is not in a Ghost module, but with the formData() module. As a support issue, this is better handled in the forum.
