### ISSUE TITLE
`page.deleted` Event Not Triggered When Page is Deleted Through Context Menu

### ISSUE THREAD

**Issue by ItzNotABug** [TryGhost/Ghost#18310]
### Issue Summary

The `page.deleted` event is not being triggered consistently. While the event is successfully fired when a page is deleted from the `Settings` option within the page, it does not work when the page is deleted using the context menu in the Pages list.

### Steps to Reproduce

1. Navigate to the Pages list.
2. Perform `Ctrl + Mouse Click` on a specific page.
3. From the context menu that appears, select Delete.
4. Observe that the `page.deleted` event does not get triggered.

Tested via `https://webhook.site`.

### Ghost Version

5.65.0

### Node.js Version

v18.18.0

### How did you install Ghost?

Hostinger VPS with CloudPanel on Ubuntu

### Database type

MySQL 8

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by ItzNotABug** [comment]
Update: `page.unpublished` also doesn't work via the context menu.

**Comment by ItzNotABug** [comment]
Not Sidebar inside the Editor.
Try performing the steps I've listed in the `Steps to Reproduce`.

Screenshot -
<img width="758" alt="Screenshot 2023-09-30 at 1 07 59 PM" src="https://github.com/TryGhost/Ghost/assets/20625965/462a64ad-7ebe-4573-903b-d8bc244dda22">

**Comment by ASCE-D** [comment]
The control + mouse click itself is not for working in my case, is this the issue?

**Comment by ItzNotABug** [comment]
> The control + mouse click itself is not for working in my case, is this the issue?

The menu shows up for me on Ctrl + Mouse Click, `Delete` or other options work as well but there's no event fired.

---
Can someone from the core team take a look at this as this doesn't seem to be fixed in `5.66.0`?

**Comment by Zelongczl** [comment]
I would like to work on it, may I be assigned?
