### ISSUE TITLE
Translation Issue

### ISSUE THREAD

**Issue by kriptoburak** [TryGhost/Ghost#18311]
### Issue Summary

Hi! There is translation issue (typo) on ghost/i18n/locales/tr/comments.json
It must be "Şimdi kayıt ol" instead of "Şimdi kaydıt ol"
Could you please fix it?

### Steps to Reproduce

Make it "Şimdi kayıt ol"

### Ghost Version

5.65.0

### Node.js Version

--

### How did you install Ghost?

Ghost.org Pro Membership

### Database type

MySQL 5.7

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by daniellockyer** [comment]
Will take a look at the PRs soon 🙂
