### ISSUE TITLE
If I change the name of the author in any post, I get this error.

### ISSUE THREAD

**Issue by pumpknman** [TryGhost/Ghost#18323]
Unhandled Runtime Error
One unhandled runtime error found in your files. See the list below to fix it:

Error in function eval in ./src/components/PostCard.tsx:80

Cannot read properties of null (reading 'name')

./src/components/PostCard.tsx:80
Open in Editor
  78 |             <span>
  79 |               {post.frontmatter.author.map((author, index) => (
> 80 |                 <React.Fragment key={author.name}>
     |                                            ^
  81 |                   <Link to={`/author/${kebabCase(author.name)}/`}>{author.name}</Link>
  82 |                   {post.frontmatter.author.length - 1 > index && ', '}
  83 |                 </React.Fragment>

**Comment by daniellockyer** [comment]
@pumpknman I think this is a bug in your theme. Do you have a `PostCard.tsx` file in your theme that isn't handling the code correctly?
