### ISSUE TITLE
Mailgun is no longer cheap.

### ISSUE THREAD

**Issue by Nyanana** [TryGhost/Ghost#18322]
### Issue Summary

At time of writing, MailGun does not offer a 'free' solution or indeed a pay as you go option. They only offer a trial after which you are automatically moved onto a 35USD/mo plan.

All I wanted to do was register a new author on my site, which requires an email to be sent (why..)

Needs a better solution

### Steps to Reproduce

n/a

### Ghost Version

n/a

### Node.js Version

n/a

### How did you install Ghost?

n/a

### Database type

MySQL 5.7

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by markstos** [comment]
Hello @Nyanana, supporting alternate email provides is a feature request, not a bug in Ghost. Consider voting for that feature here: https://forum.ghost.org/t/mailgun-alternative/29428

Mailgun is still documenting a free plan: https://help.mailgun.com/hc/en-us/articles/203068914-What-Are-the-Differences-Between-the-Free-and-Flex-Plans-

I'm using one these plans myself. Read the bottom of that page about the "Foundation Trail", which automatically converts a trial into a pay plan after a trial. Reading between the lines: what changes is now have to contact support convert your account to their "Flex" plan" before the trial runs out.

**Comment by psharma04** [comment]
Hi,
Mailgun now locks out flex plans from using anything but the sandbox domain. This is from an account with a linked card that worked 2 weeks ago, so all newsletters will no longer send unless a paid plan is added (minimum 35USD/month).

![CleanShot 2023-10-07 at 11 17 28@2x](https://github.com/TryGhost/Ghost/assets/22587474/3f0b74db-d4b0-4f8a-aae3-76e8bdca65c4)

**Comment by markstos** [comment]
@psharma04 I have a flex plan and it's working with a production domain. But as the comment said, this is better discussed on the forum.
