### ISSUE TITLE
Improve URL generation across the app

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#1833]
At the moment there are an awful lot of places where config().subdir is concatenated with a string to create a URL.

This should be done using a function which takes sensible arguments and generates the URL from a set of constants as mentioned in #1820 

Something like:

(adds subdir to any of these if needed)

`urlFor('signup')` -> `/ghost/signup/` 
`urlFor('editor', 3, true)` -> `http://localhost:2368/ghost/editor/3` 
`urlFor('rss')` -> `/rss/` 
`urlFor('rss', 2)` -> `/rss/2` 
`urlFor('home')` -> `/`
`urlFor('home', null, true)` -> `http://localhost:2368/` or similar
`urlFor('post', data)` -> `/:slug/` or `/:year/:month/:day/:slug/`

Where the first argument is the name of the url/route, the second is data, and the third is whether or not it should be absolute (always false by default).

We have the `pageUrl` helper which does something like this for `/page/2/` and the `config.paths.urlFor()` [function](https://github.com/ErisDS/Ghost/commit/bdf2d4821fd7f76d690096010972d34a6684bd55#diff-b6e891fa2317e86eb0f546a7431adf33R67) is currently a pending PR #1817 awaiting unit tests / further work which may take it closer to this.

The big issue we have right now is the need to be able to generate a url for a context from handlebars, which is what the existing urlFor is intended to do. i.e. we don't know if we're inside a post, a tag or a user, or inside nothing at all, but wherever we are we want this thing's url.

The other problem is the dependence on api.settings to get the permalink structure which means the url method has to be async.

**Comment by bnjbvr** [comment]
Interesting feature request. I think this is the one we'd need to port Ghost to run on [CozyCloud](http://cozy.io/), which expects apps to run under `/#apps/APP_NAME`. I saw there was a pull request to have Ghost being able to run under a sub-dir (but it would still plant a few things into the root URL, for instance the admin `/ghost` dir and `/assets`, if I've understood correctly). Is it correct that having this feature would allow the *entire Ghost app* to run under a given sub-path? Or is it supposed to work already this way, as of today, and I am not understanding this request clearly?
Thanks for your answers, and great project, people!

**Comment by novaugust** [comment]
Thanks for the compliments @bnjbvr =) 
Ghost already runs under a subdirectory. This is a fairly old issue you've dug up here; it's simply requesting that we have an application-wide helper function that makes it easy to make sure we're getting the correct url for any given endpoint. We definitely don't need to be porting Ghost anywhere, it works as intended ;)

**Comment by bnjbvr** [comment]
@novaugust Thank you for the answer and sorry for digging up an old thread (maybe I should start a new one?). My issue is that, while working on subdirs, some URLs are still accessing the root path of the website. For instance, my `config.js` file contains the following:
```
   url: 'http://localhost:2368/path/to/ghost',
```
And when I start the ghost server, it is still trying to load assets at `http://localhost:2368/assets`, while I would have expected it to try to load them at `http://localhost:2368/path/to/ghost/assets`. Am I doing something wrong? (should I open a new issue about this?)

**Comment by ErisDS** [comment]
Hi @bnjbvr If you're having trouble getting Ghost setup the way you want, please start a thread on our [support forum](https://ghost.org/forum/installation/) :)

**Comment by ErisDS** [comment]
Significant progress has been made on this, and there are currently no obvious areas which need looking at (there may be some - but none jump to mind). I think the remainder of this will be naturally improved as and when we need it. Closing as complete.
