### ISSUE TITLE
Hower effect not working

### ISSUE THREAD

**Issue by Saifullah00** [TryGhost/Ghost#18421]
### Issue Summary

Hower effect is either missing or not working in home page on **Get Started --- Free** button

### Steps to Reproduce

- go to https://ghost.org/
- Hower on Get Started--Free button,
- No effects user don't know where it clicked or not.
- Should have hower effect on btn.

### Ghost Version

5.66.1

### Node.js Version

14

### How did you install Ghost?

forking

### Database type

MySQL 5.7

### Browser & OS version

Chrome, windows

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by Saifullah00** [comment]
Please tag this under Hactoberfest.
I want to work on it.
Thank you

**Comment by siddoinghisjob** [comment]
Can I be assigned this issue if no one is working on it? I'd loved to work on it 😊

**Comment by sudhanshu042004** [comment]
Could you assign me to this issue if it's not already assigned?

**Comment by ayan-choradia** [comment]
@hacktoberfest i want to work on this issue , please assign me this issue
