### ISSUE TITLE
Text colour not inverted in about dialog in dark mode

### ISSUE THREAD

**Issue by viharm** [TryGhost/Ghost#18436]
### Issue Summary

The text colour in the about dialog stays dark in dark mode, so is unreadable due to lack of contrast.

### Steps to Reproduce

1. Go to settings
2. Switch to dark mode
3. Click on “About Ghost” on the top right corner

<img width="1039" alt="image" src="https://github.com/TryGhost/Ghost/assets/2663937/892e1b14-2df2-4f87-8adb-b286ece54c96">

### Ghost Version

5.66.1

### Node.js Version

N.A.

### How did you install Ghost?

Docker - Alpine variant

### Database type

MySQL 8

### Browser & OS version

Brave, Firefox, Safari on iOS, Windows & Linux

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by madjed-hue** [comment]
hello @viharm, can I work on this issue?

**Comment by Dydipanshu** [comment]
It worked fine on my local setup.
![Web capture_3-10-2023_184655_localhost](https://github.com/TryGhost/Ghost/assets/118823762/c86b03da-40ea-48cf-b34c-804057ba6bdf)

**Comment by Pratik1603** [comment]
Sir, I  like to work on this

**Comment by viharm** [comment]
> hello @viharm, can I work on this issue?

Hi, I don’t believe I am allowed to assign tasks. I have merely reported this issue, as a user.

**Comment by kevinansfield** [comment]
This was fixed in https://github.com/TryGhost/Ghost/pull/18523
