### ISSUE TITLE
Importing HTML with Lexical editor selected results in loss of images.

### ISSUE THREAD

**Issue by cathysarisky** [TryGhost/Ghost#18448]
### Issue Summary

Importing HTML that includes image links, using the Admin API.  (Images previously imported with the API images endpoint.)  
If I select the Lexical editor (in the admin interface), images get stripped out.  (They're not broken links - the img tag is totally missing.)
If I turn off the Lexical editor, images appear correctly.
No error messages are thrown on import, and the rest of the post imports intact.

### Steps to Reproduce

This is a regression for the new Lexical editor compared to the old Mobiledoc editor.
Please see comment below for full repro, demonstrated on Ghost Pro 5.68+moya.

### Ghost Version

Ghost Pro, as of 10/2/23

### Node.js Version

Ghost Pro, as of 10/2/23

### How did you install Ghost?

Ghost Pro, as of 10/2/23

### Database type

MySQL 8

### Browser & OS version

not relevant

### Relevant log / error output

```shell
no errors throw
```

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by kevinansfield** [comment]
> Importing HTML that includes image links, using the Admin API. (Images previously imported with the API images endpoint.)
If I select the Lexical editor (in the admin interface), images get stripped out. (They're not broken links - the img tag is totally missing.)
If I turn off the Lexical editor, images appear correctly.

Hi @cathysarisky, to clarify this point do you mean importing with the beta flag on vs off or do you mean after importing the beta flag has some effect?

Could you provide a short example of the HTML you are importing please?

**Comment by cathysarisky** [comment]
The beta flag seems to have an effect on import.  If I turn it on, the import fails.
Example HTML to follow.

**Comment by kevinansfield** [comment]
@9larsons was this with the latest release containing parser improvements?

@cathysarisky if you can, please try updating to the most recent release and try again to see if the issue has been fixed

**Comment by cathysarisky** [comment]
Sorry for the delay -- I didn't mean to open a report and abandon it.  My
import content was not Ghost-generated, so it's possible I've found an edge
case in html to lexical conversion.
I haven't had a chance to reproduce on the latest Ghost - too much client
work pending.  Will do ASAP! :)

**Comment by 9larsons** [comment]
Yes, this was using the most recent release - it's possible this was fixed with the changes I just pushed with that. I can't say for certain without knowing the html string. I don't feel it's likely it was resolved by the changes I made. Please just give the new release a shot and we'll find out!

**Comment by 9larsons** [comment]
@cathysarisky hey - did you get a chance to try this out again?

**Comment by cathysarisky** [comment]
OK, trying on Ghost Pro, so that's version: [5.68.0+moya](https://github.com/TryGhost/Ghost/releases/tag/v5.68.0+moya)

The beta editor slider is gone, and the problem occurs.

Here's a fairly minimalist repro case:

```
let ghostAPI=process.env.ghostAPI;
let ghostKey=process.env.ghostKey;

const api = new GhostAdminAPI({
    url: ghostAPI,
    version: "v5.0",
    key: ghostKey
});

let html = `
<html><head></head><body><p>Here is a post</p>
<p>Of course, it's a little complicated -- otherwise it wouldn't be so amusing.</p>

<p><img alt="Great Pyramid of Giza" class="asset  asset-image" src="https://demo.spectralwebservices.com/content/images/2023/10/Events-Page.png\" title="Random image from my work"></p>
</body></html>
`

api.posts
.add(
    {title: 'Hello World',
        tags: ['only testing'], 
        status: 'published', 
        html: html,
        slug: 'slug-it-out'
    }, {source: 'html'}
).then((response) => {console.log('response is', response)}).catch((error) => {console.log('error is', error)})
```

This API call happens correctly, but there's a problem somewhere.

Here's the lexical returned as part of the post object created above:
```
      lexical: `{"root":{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"Here is a post","type":"text","version":1}],"direction":null,"format":"","indent":0,"type":"paragraph","version":1},{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"Of course, it's a little complicated -- otherwise it wouldn't be so amusing.","type":"text","version":1}],"direction":null,"format":"","indent":0,"type":"paragraph","version":1},{"children":[{"type":"image","version":1,"src":"https://demo.spectralwebservices.com/content/images/2023/10/Events-Page.png","width":null,"height":null,"title":"Random image from my work","alt":"Great Pyramid of Giza","caption":"","cardWidth":"regular","href":""}],"direction":null,"format":"","indent":0,"type":"paragraph","version":1}],"direction":null,"format":"","indent":0,"type":"root","version":1}}`,
```

Upon viewing, the image is not present.  Here's the relevant HTML output upon visiting the post.
```
<section class="gh-content gh-canvas is-body">
            <p>Here is a post</p><p>Of course, it's a little complicated -- otherwise it wouldn't be so amusing.</p>
</section>
```
If I load the post in the Ghost post editor and republish it, then I get this:
```
<section class="gh-content gh-canvas is-body">
            <p>Here is a post</p><p>Of course, it's a little complicated -- otherwise it wouldn't be so amusing.</p><p></p><figure class="kg-card kg-image-card"><img src="https://demo.spectralwebservices.com/content/images/2023/10/Events-Page.png" class="kg-image" alt="Great Pyramid of Giza" loading="lazy" title="Random image from my work"></figure>
        </section>
```
... which is what I wanted in the first place!

With the removal of the old editor, I don't have a workaround for this bug.

**Comment by kevinansfield** [comment]
Thanks @cathysarisky. Looks like this issue is related to the parsing generating an invalid tree state with an image card node nested inside a paragraph node.

We've added transforms to rectify this state to the editor itself which is why opening the editor and re-publishing works but we're missing those transforms on the server-side html->lexical route. We were actually talking about this yesterday and have a plan so it should be resolved in the next Ghost release.

**Comment by kevinansfield** [comment]
Short-term workaround would be not wrapping images in paragraphs in the source HTML if that's possible.
