### ISSUE TITLE
All Social icons are not clearly visible on mobile Devices

### ISSUE THREAD

**Issue by crocmons** [TryGhost/Ghost#18454]
### Issue Summary

The social media icons are not easily visible when accessing the website from a mobile device. I want to fix this issue & make it responsive for all devices...kindly assign this issue to me!
![Screenshot (77)](https://github.com/TryGhost/Ghost/assets/106610322/eab91d8f-6899-45eb-ba49-5b8d2a212fb2)
 

### Steps to Reproduce

make it responsive for all devices

### Ghost Version

5

### Node.js Version

v16.17.0

### How did you install Ghost?

local

### Database type

Other

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by Dydipanshu** [comment]
How to recreate the issue ?

**Comment by RahulSoni2532** [comment]
I can fix this issue please assign me @crocmons

**Comment by crocmons** [comment]
> I can fix this issue please assign me @crocmons

Right now, I'm working on this issue @RahulSoni2532. If I can't complete it, I'll let you know so you can start working on this issue.

**Comment by RahulSoni2532** [comment]
ok no problem

**Comment by daniellockyer** [comment]
This is not part of the Ghost product, but thanks for the note 🙂
