### ISSUE TITLE
Support for Urdu language 

### ISSUE THREAD

**Issue by siddiqss** [TryGhost/Ghost#18507]
### Issue Summary

Add locale for urdu lanuage.

### Steps to Reproduce

NA

### Ghost Version

5.67.0

### Node.js Version

18.17.0

### How did you install Ghost?

Set-up development on my MacOS

### Database type

MySQL 5.7

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by daniellockyer** [comment]
If you're able to add the language, please read https://forum.ghost.org/t/help-translate-ghost-beta/37461 and submit a PR to do so 🙂

**Comment by siddiqss** [comment]
RTL languages are not support by Ghost yet. Urdu is an RTL lang so we might need to close this issue 😪
