### ISSUE TITLE
Post edit button not working on mobile

### ISSUE THREAD

**Issue by tmlmt** [TryGhost/Ghost#18511]
### Issue Summary

In the Admin interface, Posts tab, published posts have an analytics icon, and clicking on it brings us to stats on newsletter openings and clicks. But drafts have a pencil icon to edit, which is not working. Only clicking inside the div containing the text on the left brings to the editor. 

### Steps to Reproduce

On your mobile:
1. Go to admin, Posts tab
2. Try to click on the edit icon (✏️)

### Ghost Version

5.65.1

### Node.js Version

18

### How did you install Ghost?

CLI

### Database type

MySQL 8

### Browser & OS version

Chrome, Brave

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by daniellockyer** [comment]
Please update to the latest version 🙂

**Comment by tmlmt** [comment]
OK it was fixed in fa9960815070b72f12df4c46e954719f869f47b8 released in v5.66.1
May I suggest to be less laconic, less restrictive in the commits you choose to show in your release notes 🙏? `This release contains fixes for minor bugs and issues reported by Ghost users.` could be made more explicit. As I regularly get some issues when updating, I prefer not to update every release but keep track of the major things you introduce each time.
