### ISSUE TITLE
Social Icons are not visible

### ISSUE THREAD

**Issue by techmannih** [TryGhost/Ghost#18514]
### Issue Summary

Hello 
I found an issue in our website in which social icons are not visible for a small device.
please you can check it . it want to work on this issue please assign me 

### Steps to Reproduce

change size of all pixels 

### Ghost Version

2.0.2

### Node.js Version

20v.6.1

### How did you install Ghost?

npm install ghost-cli -g

### Database type

Other

### Relevant log / error output![2023-10-06_10-03](https://github.com/TryGhost/Ghost/assets/125847751/9bf6cb07-ecac-4d2c-a994-e6ff2101216a)
- [X] I agree to be friendly and polite to people in this repository
- 
![2023-10-06_10-04](https://github.com/TryGhost/Ghost/assets/125847751/2e1a092a-e9bc-4401-bfde-5400a55df97a)

**Comment by Chetax** [comment]
@techmannih Can i work on this issue,please assign it to  me.

**Comment by siddiqss** [comment]
Try using latest version of Ghost

**Comment by techmannih** [comment]
it is in your website in a UI

**Comment by techmannih** [comment]
yeah I also used 5.0

**Comment by daniellockyer** [comment]
This is not within the Ghost product
