### ISSUE TITLE
Missing Social Icons

### ISSUE THREAD

**Issue by techmannih** [TryGhost/Ghost#18519]
### Issue Summary

Hello
I found an issue in our website in which social icons are missing for a all  device.
In your Code i see 16 social icon but in display max tot max only 14 on large screen and for small device minimum show only 2 icon .

please you can check it . it want to work on this issue please assign me

![2023-10-06_10-04](https://github.com/TryGhost/Ghost/assets/125847751/9d921173-25a1-4d11-a0b9-b823dcd3220f)

![2023-10-06_16-56](https://github.com/TryGhost/Ghost/assets/125847751/1e3885e5-ecd0-4b25-92e7-5a819c338791)

### Steps to Reproduce

change only css 

### Ghost Version

5.0

### Node.js Version

20v.6.1

### How did you install Ghost?

npm install ghost-cli -g

### Database type

Other

### Browser & OS version

firefox

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by daniellockyer** [comment]
This is not within the Ghost product
