### ISSUE TITLE
Site Design Editor not rendering due to unsupported HTTP method

### ISSUE THREAD

**Issue by mccormickt** [TryGhost/Ghost#18530]
### Issue Summary

I'm currently using a self-hosted Ghost deployment to edit content and generate a static site. I've done so using the  https://github.com/TryGhost/eleventy-starter-ghost/ template as a starting point. Everything has worked great from generation to deployment, however, when attempting to use the Site Design editor, Ghost is failing to fetch the site due to the cloudflare pages site not supporting `POST` methods.

While looking at the [code](https://github.com/TryGhost/Ghost/blob/b868dd263d7f1800f140dad3ea0cde9f7c42c767/ghost/admin/app/services/theme-management.js#L209-L216), I was curious: Does this need to be a `POST` request? It appears to me that the requirement is to simply fetch the site's HTML, which could just as easily be a`GET` request that would ideally still be supported by all sites.

In this [commit](https://github.com/TryGhost/Ghost/commit/65495b528f0db09d544b4b5a35e86a12f75d4508), it appears this _may_ just be left over from the old method of supporting password-protected private sites. From my naive analysis, a `POST` request doesn't appear to be needed anymore, now that we have the `loginIfNeeded()` method. Just wanted to bring this up to see if we would we be able to modify this without adverse side-effects.

Thanks for looking into this and I really appreciate the community's diligent work on this project!

### Steps to Reproduce

1. Deploy generated static site to Cloudflare using https://github.com/TryGhost/eleventy-starter-ghost/
2. Use Ghost instance with `SITE_URL` pointed at deployed site.
3. Navigate to `Settings > Design` to view Site Design editor.
4. Observe empty design pane with 405 response code from deployed site.

### Ghost Version

5.66.1

### Node.js Version

20.5.1

### How did you install Ghost?

Public Docker image

### Database type

MySQL 8

### Relevant log / error output

```shell
Blank theme editor screen and the following http response visible in dev tools:


Request URL: https://example.org/
Request Method: POST
Status Code: 405 Method Not Allowed
Remote Address: 10.1.2.3:443
Referrer Policy: strict-origin-when-cross-origin
```

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by Ayush-Vish** [comment]
@mccormickt  I would like to work on this issue, Please assign it to me.

**Comment by kevinansfield** [comment]
The POST request is required because it bypasses caches and also sends data needed to generate previews of the changed settings without causing changes to the site for visitors before you save them.

If you're using a custom front-end the design settings aren't of any use anyway because they control theme settings which are irrelevant to a custom front-end because you're not using a Ghost theme.
