### ISSUE TITLE
Unable to Verify Ghost Event Using Webhook

### ISSUE THREAD

**Issue by bulgarian-beast** [TryGhost/Ghost#18551]
### Issue Summary

**Issue Title:** Unable to Verify Ghost Event Using Webhook

**Problem:**

I am currently working on integrating webhooks from my Ghost website into my server, and I'm having trouble understanding how to verify that the events received by my server are indeed from my Ghost website and not from a potential malicious source. 

**Context:**

I have set up webhooks in my Ghost website to notify my server of certain events such as new post creation, but I'm not sure how to implement authentication or headers to ensure that the incoming events are legitimate. 

**Request:**

I would greatly appreciate it if someone could provide guidance on how to properly verify the authenticity of Ghost events received via webhooks. It would be especially helpful if there are specific steps or code examples that can be shared to illustrate the process.

### Steps to Reproduce

Create a webhook
Send an  event

### Ghost Version

Version: 5.67.0 Environment: Production Database: mysql8 Mail: SMTP

### Node.js Version

Latest node version using alpine docker container

### How did you install Ghost?

Docker

### Database type

MySQL 8

### Browser & OS version

Safari

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by markstos** [comment]
This appears to be not a bug report but a feature request or support request. 

Please ask this question at https://forum.ghost.org/

I'll look for it there.

**Comment by bulgarian-beast** [comment]
You're right
