### ISSUE TITLE
Dynamic Circular Border for scroll-to-top button

### ISSUE THREAD

**Issue by SrishtiSonam** [TryGhost/Ghost#18567]
### Issue Summary

The problem of again scrolling to the top when navigating towards the footer in this quite a long page.

Expected behavior
In just one click move to top of the page.
While scrolling down knowing how much percentage of page is covered through dynamic circle around this button.

Screenshots
Create a design like the image below but customized for this website.
![image](https://github.com/TryGhost/Ghost/assets/113123593/043e9a3a-1e0a-4bfc-afcc-36bff7364aac)

Additional context
Could you please consider assigning me to this task as part of Hacktoberfest if it meets your requirements for this project?

### Steps to Reproduce

> Integrating a scroll-to-top button at the bottom-right of the page, 
> Implementing a dynamic colored border that gradually transforms into a full circle while the page is scrolled downward.

### Ghost Version

Ghost 5.x

### Node.js Version

v18.17.1

### How did you install Ghost?

ghost.org

### Database type

MySQL 5.7

### Browser & OS version

-

### Relevant log / error output

```shell
-
```

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by theavitw** [comment]
I can work on this @SrishtiSonam @kevinansfield @marcoow

**Comment by SrishtiSonam** [comment]
@theavitw 
I appreciate your willingness to help, but I believe I am well-equipped to handle this task on my own.
