### ISSUE TITLE
Pasting a link over selected text deletes the text

### ISSUE THREAD

**Issue by stromfeldt** [TryGhost/Ghost#18569]
### Issue Summary

Having had my Ghost(Pro) instance updated to 5.68 yesterday and thus tried out the new editor for the first time, I noticed that pasting links onto selected text doesn't apply the link to the text but rather deletes the text. In mobiledoc-days executing that action would in fact apply the link to the text, obviating one having to hover over the selected text, click on the link icon, pasting the text into the box, and hitting enter.

### Steps to Reproduce

1. Copy a link
2. Select some text in the editor
3. Attempt to paste the text
4. See the selected text disappear

### Ghost Version

5.68

### Node.js Version

Yes

### How did you install Ghost?

Ghost(Pro)

### Database type

MySQL 5.7

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by kevinansfield** [comment]
@stromfeldt unfortunately I’ve not been able to reproduce this and we haven’t run into it throughout the beta period which is a bit confusing. Would you mind expanding on the problem a bit?

1. Which browser/OS are you using?
2. Where are you copying the URL from?
3. Does this occur all of the time or only in some situations?

**Comment by kevinansfield** [comment]
I've been able to reproduce this in Firefox. A fix will be in the next release
