### ISSUE TITLE
Dark mode bug with header in AdminX v5.69.0 at narrower width

### ISSUE THREAD

**Issue by markstos** [TryGhost/Ghost#18579]
### Issue Summary

It seems a header div is missing some details to implement dark mode at narrower width, as seen here:

![image](https://github.com/TryGhost/Ghost/assets/25829/4a2223c8-5f08-4811-9733-eae49b51baa5)

Seems like the header box should have a dark background but has white instead. 

### Steps to Reproduce

1. Enable Dark mode for settings
2. Make browser narrower. 

### Ghost Version

5.69.0

### Node.js Version

16.20.1

### How did you install Ghost?

CLI

### Database type

MySQL 8

### Browser & OS version

Vivaldi and Qutebrowser (both Chromium-based)

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by Adarsh6xutz** [comment]
I think it should look like the image below, if yes I will create a PR for this, please acknowledge.

![image](https://github.com/TryGhost/Ghost/assets/58764152/4a9e1a24-e452-4322-b1ba-630e95abb3d0)

**Comment by markstos** [comment]
@Adarsh6xutz The Ghost core team member looking at this has finished their day, but as a fellow Ghost user, I can say that, yes, that matches the color scheme that is used if the page becomes a little wider.

**Comment by Adarsh6xutz** [comment]
hi, please review small [PR](https://github.com/TryGhost/Ghost/pull/18584), it fixes this issue
