### ISSUE TITLE
Links in the editor, in dark mode, don't have the site's accent colour

### ISSUE THREAD

**Issue by stromfeldt** [TryGhost/Ghost#18570]
### Issue Summary

Having had my Ghost(Pro) instance updated to 5.68 yesterday and thus tried out the new editor for the first time, I noticed that text with links don't have the site's accent colour to them but rather the standard #DDE1E5 HEX colour. The line down the side of blockquotes (in dark mode) does indeed have the accent colour, as does text with links in light mode.

### Steps to Reproduce

1. Switch to dark mode
2. Select some text
3. Apply a link to it
4. See that the linked-to-text doesn't change to the site's accent colour but rather stays as #DDE1E5

### Ghost Version

5.68

### Node.js Version

Yes

### How did you install Ghost?

Ghost(Pro)

### Database type

MySQL 5.7

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by git-init-priyanshu** [comment]
Can I work on this issue?

**Comment by Harshvar25** [comment]
can this issue be assigned to me ?

**Comment by kevinansfield** [comment]
This was an intentional change due to issues with some site's accent colours being unreadable in either light/dark mode, we don't intend to re-introduce the old behaviour.
