### ISSUE TITLE
Please merge #15989

### ISSUE THREAD

**Issue by samiy803** [TryGhost/Ghost#18590]
### Issue Summary

Sorry, this is not a bug or an issue. It's a request to merge #15989. This PR has been open for 10 months now, and it's a single line of code changed that fixes many issues for many users. It seems like it was neglected. Please merge ASAP

Again, sorry for abusing the issues tab, but this needs to be merged

### Steps to Reproduce

Not an issue, just calling attention to this PR #15989 

### Ghost Version

All

### Node.js Version

All

### How did you install Ghost?

.

### Database type

MySQL 5.7

### Code of Conduct

- [x] I agree to be friendly and polite to people in this repository

**Comment by itsAnuga** [comment]
Sadly an issue with this project, it looks good on the outside, but management is kind off all over the place.

**Comment by daniellockyer** [comment]
Duplicate of discussion in https://github.com/TryGhost/Ghost/pull/15989
