### ISSUE TITLE
Google AMP requires user consent

### ISSUE THREAD

**Issue by dschier-wtd** [TryGhost/Ghost#18592]
### Issue Summary

First of all, well done. I really like how ghost works and what it provides, even I don't have any use for most of the mail features. I also like the integrations a lot and I am using a couple of them already.

Digging into the "one click away" Google AMP integration, I stumbled over some issues with the GDPR. According to Google, one has to get the user consent, if AMP is enabled. To get this done, Google provides https://support.google.com/admanager/answer/11136005?hl=en.

I consider this to be a bug, since:

- The admin is never made aware that he needs a consent from the user
- The user may use Google AMP
- A ghost Admin might get in trouble (legally) for not providing the consent

### Steps to Reproduce

1. Navigate to "Settings -> Integrations -> AMP"
2. Enable AMP

![image](https://github.com/TryGhost/Ghost/assets/6490538/c4bceb43-390e-43c4-85f5-c3d58247195c)

### Ghost Version

5.68.0

### Node.js Version

v18.18.1

### How did you install Ghost?

docker

### Database type

MySQL 8

### Browser & OS version

Firefox

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by markstos** [comment]
But is the fix to add the consent pop-up or remove AMP support from Ghost core?

* [AMP is dead (for ranking)](https://forum.ghost.org/t/google-amp-is-dead/22827)
* [Why AMP is bad for your site and the web](https://medium.com/@danbuben/why-amp-is-bad-for-your-site-and-for-the-web-e4d060a4ff31)
* [Google AMP in 2022](https://torquemag.io/2022/03/google-amp-2022/) . Conclusion: *this project is no longer as important as it once was.*

With the Ghost Content API, it seems that some third-party tools could call the API and generate AMP pages for those who want them, but AMP is far from being considered important to web performance and SEO like it once was.

As a small team, should Ghost continue to support it?

By querying the across all of the websites hosted on Ghost(Pro), they should check how popular is among their customers.

**Comment by daniellockyer** [comment]
To confirm - your message specifically relates to Google Ads/whatever Google Admanager is? Or do you have a reference to say that you need consent for all AMP pages?

As Mark says, AMP is essentially a dead technology these days. We actually switched the default status from true to false for AMP, so new users won't have it enabled

**Comment by dschier-wtd** [comment]
Thank you for your response. It's not explicitly about ad sense only.

In Europe, a user must be made aware that a website is using third party services, no matter which these are. In most cases, a consent for the same is required. This does also apply to pictures from a third-party server, CDN services, etc.

Therefore, the configuration interface of Ghost should clarify that enabling a configuration (AMP for sure, but maybe even Unsplash) are reloading things from a third party website or even store cookies (which would require even a cookie consent). A statement explaining, that some countries may require the website owner to clarify this on a legal page/privacy page or imprint would be highly appreciated.

For reference:

You can find a couple of related articles and questions about this topic (also about google fonts or any other sideloaded content in general). Yes, it is a hassle to take care of the same. On the other hand, users not complying with the same are targeted by lawyers hunting for some quick wins.

- https://wordpress.org/support/topic/is-the-use-of-the-amp-plugin-gdpr-compliant/
-  https://ampforwp.com/ampforwp-is-now-gdpr-compliant-a-step-forward-towards-privacy/

I am not really sure how well this is handled today in Ghost. Maybe this is only an issue for the included amp-analytics tracking, as you stated.

In any case, thanks again for having a look. I would appreciate to support with the same, if I can support you with something.

**Comment by daniellockyer** [comment]
Whoops sorry @dschier-wtd, the bot went a bit wild 

That being said, I've spoken internally and we're planning on removing AMP support in the next major, especially given the comments above. I think it's unlikely we'll look at adding more to it before we eventually remove it, so I'm going to keep this closed 🙂

**Comment by dschier-wtd** [comment]
@daniellockyer no worries. I can handle wild bots, pretty well ^^

Thanks for investigating. In case there is anything else you need me for, please feel free to ping me.
