### ISSUE TITLE
Issue with Script Tag Generation Causing 404 Requests in Ghost 5.68.0

### ISSUE THREAD

**Issue by ZhelinCheng** [TryGhost/Ghost#18601]
### Issue Summary

**I tried version 5.6, and the issue persists. I'm not sure which version introduced this problem.**

After upgrading to Ghost version 5.68.0, I observed the generation of a script tag in the page with the following content:
```html
<script defer src="false" data-i18n="false" data-ghost="https://zhelin.me/" data-key="[delete]" data-api="https://zhelin.me/ghost/api/content/" crossorigin="anonymous"></script>
```
As per my Ghost configuration, I have set `portal.url`, `sodoSearch.url`, and `comments.url` to `false`. However, the src attribute of this generated script tag is set to `false`, leading to a 404 request to https://example.com/false.

### Steps to Reproduce

1. Upgrade Ghost to version 5.68.0.
2. Set `portal.url`, `sodoSearch.url`, and `comments.url` to false in the configuration file.
3. Visit the page and inspect the generated script tag.

The generated script tag has `src="false"`, causing a 404 request to https://example.com/false.

I have not been able to isolate the issue to a specific property, and I am using environment variables to set these properties. 

### Ghost Version

5.68.0

### Node.js Version

16.20.0

### How did you install Ghost?

Docker

### Database type

MySQL 8

### Browser & OS version

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36

### Relevant log / error output

```shell
<script defer src="false" data-i18n="false" data-ghost="https://zhelin.me/" data-key="[delete]" data-api="https://zhelin.me/ghost/api/content/" crossorigin="anonymous"></script>
```

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by ZhelinCheng** [comment]
After upgrading to version 5.69.0, the issue still persists.

**Comment by ZhelinCheng** [comment]
I tried version 5.6, and the issue persists.

**Comment by ltoinel** [comment]
A workaround found to avoid this 404 errors : https://github.com/TryGhost/Ghost/issues/12865
