### ISSUE TITLE
Search only searches posts, not pages

### ISSUE THREAD

**Issue by jdaviescoates** [TryGhost/Ghost#18622]
### Issue Summary

Search does not find text contained within pages.

### Steps to Reproduce

1. Search my site for words (or even titles) of core content that I have in my Pages
2. zero search results are shown

### Ghost Version

5.69.0

### Node.js Version

18.16.0

### How did you install Ghost?

I use Cloudron. It's on Ubuntu 22.04

### Database type

MySQL 8

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by markstos** [comment]
This is an accurate description of the behavior but Ghost is working as intended. The UI includes placeholder text to explain it searches posts specifically. 

![image](https://github.com/TryGhost/Ghost/assets/25829/817211db-b226-4d13-8ad0-ead0896eeb92)

Users would reasonably expect the search to span the whole site, though. 

I encourage you to open a feature request in the Ideas section of the forum, as this issue tracker is reserved for bugs.

https://forum.ghost.org

**Comment by jdaviescoates** [comment]
> Users would reasonably expect the search to span the whole site, though.

Absolutely!



> I encourage you to open a feature request in the Ideas section of the forum, as this issue tracker is reserved for bugs.

I maintain that this *is* a bug :stuck_out_tongue: 

But, good idea! Anyone reading this: If you would like Search to search pages (as it obviously should imho), please upvote here:

https://forum.ghost.org/t/include-pages-title-and-excerpt-in-search-results/34524

Thanks! :pray: :palms_up_together: :fist:

**Comment by daniellockyer** [comment]
I can see you've already posted on the forum, but really, the forum is the best place for feature requests. GitHub is for tracking bugs 🙂

**Comment by jdaviescoates** [comment]
> I can see you've already posted on the forum, but really, the forum is the best place for feature requests. GitHub is for tracking bugs 🙂

OK, but is there any way to move this forward? There are numerous feature request posts on the forum that have existed for [nearly 2 years](https://forum.ghost.org/t/include-pages-title-and-excerpt-in-search-results/34524) and yet this really rather quite basic feature (which would seemingly be relatively easy to add for you developers) is still in limbo 😭
