### ISSUE TITLE
Option to change theme is inaccessible in Safari on iOS

### ISSUE THREAD

**Issue by tomson** [TryGhost/Ghost#18627]
### Issue Summary

Accessing the option to change theme doesn't seem possible in Safari on iOS as it's hidden off-screen and won't allow window to scroll in to view. 

### Steps to Reproduce

![design](https://github.com/TryGhost/Ghost/assets/106274/feb48d2b-8231-4f27-954e-b1b86d28d47a)
1. Using Safari on iOS with iPhone Pro Max
2. Access Settings to edit Design
3. Accessing Change-Theme panel is not possible as it's offscreen. 
4. It does work in Brave on iOS.

### Ghost Version

5.69.0

### Node.js Version

Current

### How did you install Ghost?

Hosted independently 

### Database type

MySQL 5.7

### Browser & OS version

Latest iOS

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by markstos** [comment]
I reproduced this with an iPhone 12 mini and Safari. 

The settings modal height needs to be extended vertically to take into account the footer navigation bar overlay with Dashboard, Posts, Members, etc. 

The Change Theme option is hidden behind it.
