### ISSUE TITLE
Cutting and pasting items in an unordered list results in misplaced items

### ISSUE THREAD

**Issue by stromfeldt** [TryGhost/Ghost#18633]
### Issue Summary

When trying to cut and then paste an item from an unordered list to a different spot in the list, said item gets placed at the very bottom of the list.

https://github.com/TryGhost/Ghost/assets/27488257/18666d54-7c1f-4b67-8591-388e2f15ec97

### Steps to Reproduce

1. Create several items in an unordered list
2. Cut one of those items
3. Go to another spot in the middle of the list and paste that item in
4. See it gets placed at the bottom of the list

### Ghost Version

5.68

### Node.js Version

Yes

### How did you install Ghost?

Ghost(Pro)

### Database type

MySQL 5.7

### Browser & OS version

Firefox 118.0.2, macOS 13.6

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by kevinansfield** [comment]
Thanks for the report. This is an [upstream issue](https://github.com/facebook/lexical/issues/4723) that we're aware of and tracking.

**Comment by 9larsons** [comment]
This seems to persist even after resolving the upstream issue. The behaviour upstream isn't perfect as it still injects an empty `ListItem` node when using Shift+Up selection to not just grab the text... but it at least doesn't dump it at the end of the list like Koenig does, so we've got something to look in to at this point.
