### ISSUE TITLE
"Delete all content" modal doesn't automatically disappear upon deletion

### ISSUE THREAD

**Issue by stromfeldt** [TryGhost/Ghost#18631]
### Issue Summary

Upon deleting all of a site's content via the "Delete all content" modal the "All content deleted from
database" message appears down at the bottom-left, but the "Delete all content" modal doesn't disappear. In fact, one can keep clicking the Delete button and get the aforementioned message to reappear.

![Xnapper-2023-10-15-14 47 38](https://github.com/TryGhost/Ghost/assets/27488257/dca988d1-e540-4fe1-b524-a28bca9ca556)

### Steps to Reproduce

1. Click "Delete" on the "delete all content" modal
2. See the modal not disappear

### Ghost Version

5.69

### Node.js Version

16.15.0

### How did you install Ghost?

CLI

### Database type

MySQL 5.7

### Browser & OS version

Firefox 118.0.2, macOS 13.6

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by daniellockyer** [comment]
Fixed by https://github.com/TryGhost/Ghost/commit/31b3905f8d22d9c3c8cb8e43cea1da042107e297
