### ISSUE TITLE
We can have a brighter chip instead, as it is quite light and not visible properly

### ISSUE THREAD

**Issue by sahilrohera10** [TryGhost/Ghost#18658]
### Issue Summary

since, the chips opacity is 0.5 and the text is also very light, we can have a better and a brighter chip instead. as per the website, such a vibrant one, these this much lighter chips are not looking so good.

earlier : 
![Screenshot 2023-10-17 105719](https://github.com/TryGhost/Ghost/assets/90958499/b5a273c9-f8f2-4516-a086-e7ea2ba664bd)

expected :
![Screenshot 2023-10-17 105917](https://github.com/TryGhost/Ghost/assets/90958499/630d5111-25d5-4ba8-93c3-ce1a19fb9a47)

### Steps to Reproduce

1. go to ghost.org
2. navigate on navbar and click on "For Developers" under "Product"

### Ghost Version

5.68.0

### Node.js Version

I just gone through the Ghost website

### How did you install Ghost?

I just gone through the Ghost website

### Database type

MySQL 5.7

### Browser & OS version

Chrome, windows 11

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by daniellockyer** [comment]
This is not part of the open source Ghost product 🙂

**Comment by sahilrohera10** [comment]
@daniellockyer  Oh, thanks for informing

**Comment by sahilrohera10** [comment]
Hey @daniellockyer , can you please tell, what is open source Ghost product, as i want to contribute in Ghost.
Thanks
