### ISSUE TITLE
Can be a feature enhancement : On selecting the custom services by checking the boxes, this could highlight its background

### ISSUE THREAD

**Issue by sahilrohera10** [TryGhost/Ghost#18657]
### Issue Summary

This can be feature enhancement or may be a bug : that on checking out the boxes, we can change its background color, for better ux, it shows to user that yes this has been selected by me.

bug : 
![Screenshot 2023-10-17 095048](https://github.com/TryGhost/Ghost/assets/90958499/7a1e119d-670c-4580-9b4c-4ead7550d092)

Expected : 

![Screenshot 2023-10-17 095229](https://github.com/TryGhost/Ghost/assets/90958499/3b7343fa-e546-4045-a842-e52f0ca91dc8)

### Steps to Reproduce

1. go to ghost.org
2. navigate on the navbar and go to marketplace under resources
3. go down and select any from the experts 
4. go to bottom and there will a contect form

### Ghost Version

5.68.0

### Node.js Version

I just gone through the Ghost website

### How did you install Ghost?

I just gone through the Ghost website

### Database type

MySQL 5.7

### Browser & OS version

Chrome, Windows 11

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by sahilrohera10** [comment]
sorry, Ghost version is 5.68.0

**Comment by dev-palwar** [comment]
Can I work on this issue? It won't take log

**Comment by dev-palwar** [comment]
Can i work on this issue? It won't take long

**Comment by daniellockyer** [comment]
This is not part of the open source Ghost product 🙂
