### ISSUE TITLE
Logo loader video has white background also in dark mode

### ISSUE THREAD

**Issue by lorumic** [TryGhost/Ghost#18663]
### Issue Summary

When dark mode is selected for admin-x, the `logo-loader.mp4` video is played when loading pages (e.g. the settings page), but this video has a white background, making it look like this:

![image](https://github.com/TryGhost/Ghost/assets/56583786/5b80f351-69eb-4120-845b-b5eda2da3355)

Two possible solutions:

- Converting the MP4 to a GIF/WEBP/APNG so that you have transparency support. (recommended)
- Add a dedicated `logo-loader-dark.mp4` file, where the video has the same dark background as the page. (less future-proof)

### Steps to Reproduce

1. Open admin-x.
2. Switch to dark mode.
3. Open settings page - on first load, it shows the loader for a fraction of a second.
4. See the loader with the white background over the dark background of the page.

### Ghost Version

5.69.2

### Node.js Version

v18.18.2

### How did you install Ghost?

From source (Ubuntu)

### Database type

MySQL 5.7

### Browser & OS version

Google Chrome 118.0.5993.70, Ubuntu

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by Adarsh6xutz** [comment]
@kevinansfield I think it require some input as we can not just change the background of loader to dark because loader itself is dark in color

**Comment by lorumic** [comment]
Right, but I see there is already a couple of nice darkmode-compatible logos in the README of the GitHub repo, [here](https://user-images.githubusercontent.com/65487235/157849205-aa24152c-4610-4d7d-b752-3a8c4f9319e6.png) and [here](https://user-images.githubusercontent.com/65487235/157849438-79889b04-b7b6-4ba7-8de6-4c1e4b4e16a5.png).
