### ISSUE TITLE
Deletion of the final character of a link can delete the entire link

### ISSUE THREAD

**Issue by stromfeldt** [TryGhost/Ghost#18674]
### Issue Summary

Deleting the final character of a link can delete the entire link. Sometimes, but not always. Because as seen in the video below, when I successfully deleted (and then un-did) the deletion of characters within a link I was able to move the cursor to the final character and successfully delete it (and nothing else). But when I moved the cursor away from the link and then returned to the position enabling me to delete the final character of the link, doing so once again deletes the entire link.

https://github.com/TryGhost/Ghost/assets/27488257/6df571bd-612c-4f90-b72d-3cf02f5dee3c

### Steps to Reproduce

1. Place the cursor a few characters after the final character after a link, then move it to just after the final character of a link
2. Press the delete button
3. See the entire link disappear

### Ghost Version

5.69.2+ moya

### Node.js Version

Yes

### How did you install Ghost?

Ghost(Pro)

### Database type

MySQL 5.7

### Browser & OS version

Firefox 118.0.2, macOS 13.6

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by 9larsons** [comment]
Should be resolved with the next Ghost release - thanks for reporting this!
