### ISSUE TITLE
Unable to sign up locally

### ISSUE THREAD

**Issue by aditya-sodhiya** [TryGhost/Ghost#18688]
### Issue Summary

I have set up Ghost locally, followed the https://ghost.org/docs/install/source/.  Everything seems to be working but I am unable to sign up. the last command ran is `yarn dev`. 

More specifically, I wanted to get the onboarding done to a step wherein I would be entering some dummy site address for open-source contribution.

I tried searching for help at https://forum.ghost.org/  for help and did find relevant help. Would really be helpful if there was documentation for the same.addresses

### Steps to Reproduce

1. https://ghost.org/docs/install/source/
2. the last command ran - `yarn dev`
<img width="1706" alt="Screenshot 2023-10-18 at 4 50 34 PM" src="https://github.com/TryGhost/Ghost/assets/24322155/1adb8db9-38ea-4a12-ad90-888ea365b094">

### Ghost Version

Ghost core - "5.69.2"

### Node.js Version

v18.18.1

### How did you install Ghost?

MacOS

### Database type

MySQL 5.7

### Browser & OS version

Google Chrome 

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by ronaldlangeveld** [comment]
You'll have to add some email configuration into your `config.development.json` file. 
All config settings can be found in the [documentation](https://ghost.org/docs/config/).
Let me know if you run into any other issues.

**Comment by aditya-sodhiya** [comment]
@ronaldlangeveld , setting up SMTP server would require me to have domain (currently don't have one)? For development locally, do it need this as well? Is there a work around?

**Comment by ronaldlangeveld** [comment]
> @ronaldlangeveld , setting up SMTP server would require me to have domain (currently don't have one)? For development locally, do it need this as well? Is there a work around?

You don't need a domain if you use Mailgin sandbox SMTP / API for testing. It will essentially be something like postmaster@sandbox123.mailgun.org

**Comment by cathysarisky** [comment]
I'm surprised this support request is still open, but since it is, my favorite way to get email working enough to be able to develop locally is here: https://www.spectralwebservices.com/blog/ghost-developer-email/
