### ISSUE TITLE
Can't overwrite a snippet on top of a card

### ISSUE THREAD

**Issue by stromfeldt** [TryGhost/Ghost#18754]
### Issue Summary

I tried overwriting a snippet, but it appears that items in the snippet dropdown can't be selected if they appear atop of a card.

https://github.com/TryGhost/Ghost/assets/27488257/b22e695f-9533-4c81-991a-20365abd4e60

### Steps to Reproduce

1. Create an HTML card with some kind of card below it
2. Click on the create snippet button
3. Scroll down in the dropdown to try and overwrite a previously created snippet
4. See that the highlight disappears when trying to select an item in the dropdown that is above the card below

### Ghost Version

5.70.2+moya

### Node.js Version

Yes

### How did you install Ghost?

Ghost(Pro)

### Database type

MySQL 5.7

### Browser & OS version

Firefox 118.0.2, macOS 13.6

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by lalitkumawat1m** [comment]
Hello Team, I want to work on this issue please assign to me
