### ISSUE TITLE
Pressing Enter on a card after closing the Post settings side-panel re-opens the side-panel

### ISSUE THREAD

**Issue by stromfeldt** [TryGhost/Ghost#18752]
### Issue Summary

I went to add an empty line below an HTML card after having closed the Post settings side-panel, which re-opened the side-panel

### Steps to Reproduce

1. Close the Post settings side-panel
2. Click on any kind of card
3. Press enter/return
4. See the Post settings side-panel re-open and the empty line beneath the card not getting created

### Ghost Version

5.70.2+moya

### Node.js Version

Yes

### How did you install Ghost?

Ghost(Pro)

### Database type

MySQL 5.7

### Browser & OS version

Firefox 118.0.2, macOS 13.6

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by lalitkumawat1m** [comment]
Hello Team, I want to work on this issue please assign to

**Comment by 9larsons** [comment]
More generally, clicking on any card does not set the focus to the editor (`div.kg-prose`).

**Comment by 9larsons** [comment]
Because decorator nodes (cards) do not have carets, they do not update the selection. We need to manually update the selection when calling `$selectCard`. Working on a PR now.

**Comment by stromfeldt** [comment]
@9larsons With you having said "more generally", I'm wondering if this issue is related to another issue I've experienced. That is, copying and pasting HTML cards doesn't always work, and requires one to click into a text area or a header, and then re-select the HTML card which one is then able to copy for pasting elsewhere. [Others have also experienced this](https://forum.ghost.org/t/koenig-editor-bugs/42391/5). I haven't created a new issue for this just yet as it's more nuanced than the above and I'd have to test out a few things to nail it all down right.

Is it possible that your statement that "decorator nodes (cards) do not have carets" means that your PR will inadvertently address this, or should I create a separate issue?

**Comment by 9larsons** [comment]
This particular issue for any time you have focus outside the editor and are clicking on a card (not just the side panel). It sounds like that is possible to frustrate users when they clicked back into the editor, onto a card, and hit copy, as the editor wouldn't actually have focus and process the copy command.

If you clicked into a text area or header you'd certainly get focus back into the editor and you wouldn't encounter this issue. I'd say there's a fairly good chance this addresses what you're seeing - please give it a shot and let me know if you're still seeing it. You can open an issue and ping me directly 👍 .

**Comment by 9larsons** [comment]
I ref'd the issue incorrectly to be automatically picked up, but I attached the PR now and am going to close this one out.
