### ISSUE TITLE
Deleting the last character in a blockquote beneath an HTML card deletes the HTML card

### ISSUE THREAD

**Issue by stromfeldt** [TryGhost/Ghost#18753]
### Issue Summary

I tried deleting the last character in a blockquote beneath an HTML card, and while the character disappeared so did the HTML card above it (while the empty blockquote remained).

https://github.com/TryGhost/Ghost/assets/27488257/12a81ba8-09e8-4ef0-b612-23998a696c71

### Steps to Reproduce

1. Create an HTML card with blockquoted text below it
2. Delete the text in the blockquote
3. See the HTML card disappear when the last character in the blockquote is deleted

### Ghost Version

5.70.2+moya

### Node.js Version

Yes

### How did you install Ghost?

Ghost(Pro)

### Database type

MySQL 5.7

### Browser & OS version

Firefox 118.0.2, macOS 13.6

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by lalitkumawat1m** [comment]
Hello Team, I want to work on this issue please assign to me

**Comment by 9larsons** [comment]
Applies to both `AsideNode` and `QuoteNode`.
