### ISSUE TITLE
Dropped support for Node 16 make ghost update error database migrate

### ISSUE THREAD

**Issue by cuongtqtran** [TryGhost/Ghost#18783]
### Issue Summary

Dropped support for Node 16 on ghost v5.70 made ghost update database error.
Cannot rollback to old version as well.

### Steps to Reproduce

1. Update Nodejs 18.18.12 from Nodejs 16.20
2. Upgrade ghost with CLI `ghost update`

### Ghost Version

5.71.0

### Node.js Version

18.18.2

### How did you install Ghost?

Ubuntu, v22.04.3 LTS, 2CPU 2GB RAM NVMe SSD

### Database type

MySQL 8

### Relevant log / error output

```shell
Message: Ghost was able to start, but errored during boot with: connect ECONNREFUSED ::1:3306
Help: Unknown database error
Suggestion: journalctl -u ghost_domain-com -n 50
```

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by ugurcany** [comment]
same issue. @cuongtqtran did you find any solution?
