### ISSUE TITLE
Text Selection Color in Admin-X's darkmode is effectively transparent

### ISSUE THREAD

**Issue by stromfeldt** [TryGhost/Ghost#18784]
### Issue Summary

Highlighting any portion of text within Admin-X's darkmode in order to cut/copy/delete something is possible, but there is no Text Selection Color to the highlight.

### Steps to Reproduce

1. Select dark mode
2. Try to highlight any portion of text within Admin-X
3. See that there is no Text Selection Color

### Ghost Version

5.71

### Node.js Version

Yes

### How did you install Ghost?

Ghost(Pro)

### Database type

MySQL 5.7

### Browser & OS version

Firefox 119, macOS 13.6

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by minimaluminium** [comment]
Thanks @stromfeldt. This is now fixed in https://github.com/TryGhost/Koenig/commit/254150f12ab11d8ec028ed9b25034f390e20dc95
