### ISSUE TITLE
"Invalid Theme" when trying to add limit specification to {{recommendations}} helper

### ISSUE THREAD

**Issue by stromfeldt** [TryGhost/Ghost#18836]
### Issue Summary

I've integrated the `{{recommendations}}` helper into my theme locally, and have successfully uploaded that theme to Ghost(Pro). However, with mention of the new `{{recommendations}}` functionalities via the docs, and having amended `{{recommendations}}` to `{{recommendations limit="10"}}` (to use an example value given in the docs), the site works with the expected behaviour locally (without doing a restart) but the theme won't upload to Ghost(Pro).

![Xnapper-2023-11-02-12 17 13](https://github.com/TryGhost/Ghost/assets/27488257/05106cb1-a209-4cd1-bb06-1981a2b509ca)

GScan gives a similar message.

As expected, doing a restart on the local instance does in fact result in an error message being displayed (even though the actual local site continues to work fine).

![Xnapper-2023-11-02-12 55 07](https://github.com/TryGhost/Ghost/assets/27488257/cdef8362-0763-41d2-97d2-31422754a7ef)

### Steps to Reproduce

1. Add the limit specification to the `{{recommendations}}` helper (such as `{{recommendations limit="10"}}`).
2. Upload the zipped theme
3. See "Invalid Theme" message

### Ghost Version

5.71.0+moya

### Node.js Version

Yes

### How did you install Ghost?

Ghost(Pro)

### Database type

MySQL 5.7

### Browser & OS version

Firefox 119, macOS 13.6

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by daniellockyer** [comment]
Thanks for the report, this was fixed in https://github.com/TryGhost/Ghost/releases/tag/v5.71.2 🙂
