### ISSUE TITLE
Missing helper: "readable_url"

### ISSUE THREAD

**Issue by fueko** [TryGhost/Ghost#18834]
### Issue Summary

With the new recommendations feature, a helper called `readable_url `has been added. Unfortunately, using this helper results in a GScan error `Missing helper: "readable_url"`.

### Steps to Reproduce

Add this code `{{readable_url "https://google.com"}}` to any file, restart Ghost, and check the GScan message:

![Zrzut ekranu 2023-11-2 o 00 26 12](https://github.com/TryGhost/Ghost/assets/23366922/e523aba9-c428-42a9-b37f-2c3242dd71e2)

### Ghost Version

5.71.1

### Node.js Version

v18.17.0

### How did you install Ghost?

localhost

### Database type

SQLite3

### Browser & OS version

Any

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by daniellockyer** [comment]
Thanks for the report - this was fixed in https://github.com/TryGhost/Ghost/releases/tag/v5.71.2 🙂
