### ISSUE TITLE
Double-clicking causing poor user experience in dark mode

### ISSUE THREAD

**Issue by Akhi88S** [TryGhost/Ghost#18848]
### Issue Summary

Double-clicking in the vicinity of the parent div responsible for toggling between dark and light themes, accessing settings, and profile icons results in a background colour reset, consequently leading to hiding of settings icon.

- **Check bottom left, how it is before double click**
 <img width="1074" alt="Screenshot 2023-11-02 at 11 30 35 PM" src="https://github.com/TryGhost/Ghost/assets/39363939/757b6f66-a991-4e7b-a1c7-19b622a9888d">

- **After double click**
<img width="754" alt="Screenshot 2023-11-02 at 11 30 23 PM" src="https://github.com/TryGhost/Ghost/assets/39363939/3c10b078-bc94-46ec-8250-fa0dc2d4b21d">

### Steps to Reproduce

To replicate the issue:

1. Open the Ghost admin interface.
2. Locate and click on the parent div situated in the bottom left corner of the settings section.
3. Check the settings icon after double click, it must’ve been hidden because of the highlighted background

### Ghost Version

5.71.2

### Node.js Version

18.12.1

### How did you install Ghost?

MacOs

### Database type

MySQL 5.7

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by Akhi88S** [comment]
It could probably  be solved by adding  _**user-select none**_  to div container.
If it's considered as bug, please do assign will take it up.

**Comment by Akhi88S** [comment]
Hey @daniellockyer, can you assign the issue to me?

**Comment by asenseofpradhyu** [comment]
Hello @Akhi88S 

I attempted to replicate this issue, but unfortunately, I couldn't reproduce it. Could you please double-check and provide more details about the issue? Let me know if you encounter the issue again.
