### ISSUE TITLE
Pasting a link over selected caption text doesn't apply the link to the selected text but overwrites the text

### ISSUE THREAD

**Issue by stromfeldt** [TryGhost/Ghost#18866]
### Issue Summary

Unlike pasting a link over selected regular text in to apply the link to the text, doing so to text in a caption overwrites the selected text with the link itself.

**EDIT:** This also occurs within Callout cards, and presumably in other places as well.

### Steps to Reproduce

1. Copy a link
2. Select some text in a caption
3. Try and paste the link
4. See the entire link replace the selected text

### Ghost Version

5.71.2+moya

### Node.js Version

Yes

### How did you install Ghost?

Ghost(Pro)

### Database type

MySQL 5.7

### Browser & OS version

Firefox 119, macOS 13.6

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by Akhi88S** [comment]
@stromfeldt seems working ok for me. can you add supporting media(images) for the bug?

**Comment by 9larsons** [comment]
Can reproduce for any nested editor. Working on a PR now. Thanks for the report!
