### ISSUE TITLE
Descenders in the publisher name of bookmark cards in the editor get cut off

### ISSUE THREAD

**Issue by stromfeldt** [TryGhost/Ghost#18861]
### Issue Summary

If you take a look at the publisher name in bookmark cards in the editor it can be seen that their descenders get cut off. (Notice though that I added a `g` to Team Ghost, which did not get cut off.)

![Xnapper-2023-11-03-17 33 33](https://github.com/TryGhost/Ghost/assets/27488257/89702f97-9d60-4973-ba3c-7b8e77d37e7c)

Changing the following in my browser

```
.koenig-lexical :is(.leading-6) {
  line-height: 1.5rem;
}
```

to `1.6rem` fixes the problem.

![Xnapper-2023-11-03-17 33 54](https://github.com/TryGhost/Ghost/assets/27488257/a8452a22-aa4d-4f03-9a97-e14c213965cb)

Unfortunately, and [unlike the menial fix I contributed for the descenders of tags getting cut off](https://github.com/TryGhost/Ghost/commit/6757d984afe84f592b729351174b1f88c68ab50d), I can't decipher where that line-height change would be implemented in this case. That being so, I'm not submitting a PR but rather a bug report.

### Steps to Reproduce

1. Paste in the link to the new recommendations functionality into the editor in order to create a bookmark card
2. See that the `g`s in Changelog get cut off at the bottom

### Ghost Version

5.71.2+moya

### Node.js Version

Yes

### How did you install Ghost?

Ghost(Pro)

### Database type

MySQL 5.7

### Browser & OS version

Firefox 119, macOS 13.6

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by Abhishek7Tech** [comment]
Hello @kevinansfield I would like to work on this issue.

**Comment by asenseofpradhyu** [comment]
Hello @stromfeldt 

It seems that the images you've added appear identical, and I'm unable to replicate the issue in the editor. Could you please verify from your end and check if the issue still exists? If you encounter the problem, kindly share more detailed steps to help me replicate it.

**Comment by stromfeldt** [comment]
Hello @asenseofpradhyu. No, the images are not identical. Look at the word Changelog in both images. In the first, the bottom 1px or so of the letter **g** is cut off. Hence the need for extra line-height.
