### ISSUE TITLE
Staff token quick tasks button text lacking contrast in dark button

### ISSUE THREAD

**Issue by viharm** [TryGhost/Ghost#18867]
### Issue Summary

When the admin interface is in dark mode, the text colour of the quick action buttons (`Regenerate` & `Copy`) for the staff token appear with same colour as the button so seem illegible.

#### Dark Mode
![image](https://github.com/TryGhost/Ghost/assets/2663937/4990aa70-7580-42f4-9456-c57b7988c73f)

#### Light Mode
![image](https://github.com/TryGhost/Ghost/assets/2663937/6a1b4577-9292-432a-8750-c8e48b28c55e)

It appears that the button text correctly detects the contrast, but the button itself remains the same colour in both light and dark modes

### Steps to Reproduce

1. Go to settings
2. Switch to dark mode
3. Click on “My Profile” from the bottom left corner
4. Scroll down to Staff access token.

### Ghost Version

5.70.2

### Node.js Version

N.A.

### How did you install Ghost?

Docker - Alpine variant

### Database type

MySQL 8

### Browser & OS version

 Firefox 119.0 (64-bit) on Kubuntu 20.04

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by viharm** [comment]
This issue is similar to #18436

**Comment by nitishsaini706** [comment]
@viharm I would love to contribute and fix this issue, but I cannot find any installation guide as I'm facing issue while cloning and installing the dependencies. tried finding answer in the forum but no success. Awaiting your reply

**Comment by viharm** [comment]
> @viharm I would love to contribute and fix this issue, but I cannot find any installation guide as I'm facing issue while cloning and installing the dependencies. tried finding answer in the forum but no success. Awaiting your reply

@nitishsaini706 , I'm sorry I don't know how to setup the development environment, as I'm not a developer here. I've only reported this issue as a user.

**Comment by nitishsaini706** [comment]
@daniellockyer Can anyone help me with setup, so that I can contribute

**Comment by Akhi88S** [comment]
Appreciate your observation @viharm. It appears there's a discrepancy in the color property. Ideally, for a darker theme, the following property should be applied.

<img width="1080" alt="Screenshot 2023-11-11 at 5 16 42 PM" src="https://github.com/TryGhost/Ghost/assets/39363939/3318a932-eb5c-432d-aacb-b3c06e5b5f05">

@daniellockyer / @peterzimon , can you please assign the issue to me

**Comment by peterzimon** [comment]
Hey @nitishsaini706, thank you for your contribution. In the meantime this has been fixed with another commit so I'm closing the issue.
