### ISSUE TITLE
Scrollbars 2.0

### ISSUE THREAD

**Issue by JohnONolan** [TryGhost/Ghost#1892]
https://www.facebook.com/messages/ - hover around the different parts of the page and scroll. This is how scrollbars in Ghost should work.

There's some example very basic example implementations of this here: http://rocha.la/jQuery-slimScroll (NB: do _not_ want to use this, just a reference)

This is not a simple issue. We've already had a mess around with scrollbars in the past and totally failed. There are many tricky cross-browser (and mobile) implications which need to be tested.

The Facebook implementation is the best I've ever seen by a significant margin. It does OSX like interactions but with some additional features which make it more suited to browsers and other platforms. Very like.

I would love to see a PR for this with an initial prototype implementation and some thoughts / suggestions.

**Comment by kevinansfield** [comment]
@JohnONolan is this issue still relevant or can it be closed now?

**Comment by ErisDS** [comment]
In the interest of cleanliness, I'm gonna close this for now. If it becomes a priority or a nice solution surfaces we can always reopen :)
