### ISSUE TITLE
Performance: Youtube embed cause performance issue.

### ISSUE THREAD

**Issue by bugfixdev** [TryGhost/Ghost#18932]
### Issue Summary

![image](https://github.com/TryGhost/Ghost/assets/117451862/9ed284cb-0758-42fa-b95e-a660fb730584)

### Steps to Reproduce

Issue can reproduce by embedding youtube link in post and then test published blog on PageSpeed Insights.

### Ghost Version

v5.70

### Node.js Version

v16.20.0

### How did you install Ghost?

ubuntu 18 

### Database type

MySQL 8

### Browser & OS version

Chrome 119/windows 10

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by daniellockyer** [comment]
Thanks for the issue - I wouldn't necessarily call this a bug so I'd suggest opening a feature request on the forum with the request 🙂
