### ISSUE TITLE
Inline Code Formatting in Callout Card

### ISSUE THREAD

**Issue by 0xBEN** [TryGhost/Ghost#19129]
### Issue Summary

# Issue Synopsis

In previous versions of Ghost -- prior to upgrading to `5.74.3` -- inline code was formatted as expected in callout cards. Upon upgrading to the latest version, the inline code formatting still displays as expected in the editor view. However, when reading the published article, the formatting of the inline code is lost, and the inline code appears as plain text. This makes it difficult to emphasize and distinguish code and/or commands in callout cards.

Inline code formatting in callout cards was last known to be working for me in Ghost `5.59`.

# Screenshots

**Callout Card with Code in Ghost `5.74.3` Editor**

![image](https://github.com/TryGhost/Ghost/assets/26947869/837e67c9-0bfd-41e8-9606-dfa7734c04c3)

**Callout Card in Ghost `5.74.3` Published Article**

![image](https://github.com/TryGhost/Ghost/assets/26947869/e7a83f03-4b92-43b8-977c-88c44c8632e5)

**Callout Card in Google Cache (Ghost `5.59`)**

![image](https://github.com/TryGhost/Ghost/assets/26947869/8cd49210-4179-490b-82ca-a7b148cdae75)

### Steps to Reproduce

1. Create a new post or update an existing one
2. Add a new callout card or update an existing one
3. Add some text to the callout card, as well as one or many inline code blocks. Inline code blocks are created by wrapping text between backticks. \`inline code example\` == `inline code example`
4. Note that the inline code appears to be formatted correctly within the callout card
5. Publish or update the post, then open the published post
6. Note that the inline code formatting in the callout card does not match what's shown in the editor

### Ghost Version

5.74.3

### Node.js Version

18.17.1

### How did you install Ghost?

Followed self-hosting guidance, Ubuntu 22.04

### Database type

MySQL 8

### Browser & OS version

Google Chrome 119.0.6045.160

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by btme0011** [comment]
Can i work on this issue?

**Comment by 0xBEN** [comment]
Moving my original comment here;

> Kevin and team, thanks for your work on this issue and Ghost overall. Is there a recommended way to re-render all posts that I've modified in the past, such that the inline formatting is displayed as expected? In other words, should I republish posts one-by-one, or is there a batch way to have the content regenerated?

**Comment by 0xBEN** [comment]
Hello, I'm not sure if this is the proper workflow, or if you'd rather a new issue that references this one. However, this issue still seems to be ongoing. I've updated my Ghost instance to the latest version and still and not able to have inline code elements rendered within a callout card.

![image](https://github.com/TryGhost/Ghost/assets/26947869/fd23fea7-9bb9-43a4-8340-6d6e06cb9fcb)

**Comment by kevinansfield** [comment]
The fix hasn't been released yet. It will appear in the [release notes](https://github.com/TryGhost/Ghost/releases) when it's included
