### ISSUE TITLE
Content Security Policy (CSP)

### ISSUE THREAD

**Issue by CarlSinclair** [TryGhost/Ghost#19146]
### Issue Summary

Content Security Policy is very important for web security, and adoption needs to become more mainstream. Ghost, being a very popular CMS, currently stands in the way of that.

The discussion in #7206 is frankly embarrassing, and really indicative of much bigger problems with Ghost. The maintainers are very dismissive of requests in general, complaining that "ghost is for blogging, not for making complex websites" when the "complex websites" in question that they were referring to were two column layouts. It's generally very user-unfriendly to use, with the maintainers seemingly choosing the most complicated way possible of achieving any result and making it the ONLY way to accomplish that task in ghost. And even when simpler methods are possible, they only document the absolute worst ways possible. It almost seems like these barriers to entry are intentional.

And all of this pales in comparison to the attitude around security. In the issue where THE Scott Helme himself came here and not only urged them to support CSP with a very compelling argument accounting for all their concerns, he even volunteered his own time and efforts to personally help them with any challenges along the way to make this happen. The response? "You spoiled brats need to stop whining and understand that we don't have time for your favorite pet feature. Do you not understand how open-source works?", which is fair enough, and I'm not judging you for your horrible communication skills (your docs clearly are also indicative of that), except we're talking about SECURITY.

I created this issue not just to rant but also to address a couple of very specific points, and to provide some constructive feedback:

1. CSP is not anybody's "favorite pet feature". It's a security standard. It keeps the internet, your product and your users (and their users) safe. That's as absurd as saying SSL is somebody's favorite pet feature that you refuse to implement.
2. "it's not viable for inclusion in core". The fact that it would be difficult/inconvenient for you to include CSP in core is proof that you NEED to, because you are currently vulnerable to the security issues it protects against.
3. The reason this issue never goes anywhere is because of you. Because any implementation will be per-instance unless you include it globally for all instances. And until you do that, you will continue to receive requests for it from security-conscious users rightly identifying this flaw in your platform. And the fact that it's so complicated to implement is all the more reason for you to do it, rather than pass the buck to your inexperienced users for whom it would be impossible to implement without your help.
4. "it's not compatible with core". Well, good thing you had Scott Helme himself there to help you make it compatible. Oh wait, you drove him off after dismissing his input as the literal expert on the topic.

To reiterate and attempt to simplify what he said: It is possible (albeit inadvisable) to include a very permissive implementation of CSP in core that security-conscious users can harden and build on top of. The idea of including it in core would be to include at least basic security by default for all users, and to enable and facilitate the hardening of that security.

The only things you really need to do to implement good CSP are:
1. generate nonces somewhere on the backend
2. deploy scripts through <script> tags without including the script code in-line in the html file itself
3. include the "nonce" attribute within those script tags
4. set the following HTTP header: Content-Security-Policy: default-src 'self'
5. if this policy breaks anything on your website (visible in any browser's dev console), you know you either need to serve those elements locally or permit the access through CSP.
6. allow for the modification of the CSP headers through the admin console for any exotic configurations

And voila. That's literally all you have to do to have really good website security.

For documentation, (which you generally need a lot of help with) you should really open that up to submissions from the community, or approach those who have created guides for Ghost on their own websites asking them for permission to bring those guides in-house. As an Apache user, I'd love to document my struggles with Ghost to help others that are currently met with the boilerplate "we don't support Apache, use Nginx" official response.

As for how it would work on the site-owner side, it would depend on the implementation that you go with. With a permissive default policy, users won't need to do much. With a more hardened default policy, you'd be forcing site-owners to educate themselves about security in order to create custom CSP headers. Unless you go with a user-friendly implementation in the admin console with fields for including domains in each CSP directive. Regardless of how you approach it, the web would be a much safer place.

The fact that Ghost includes a richtext editor and allows for custom code injection are irrelevant to this. Scott already addressed the editor on that post, and injected code can also be worked around by allowing unsafe-inline scripts. Which again isn't ideal, but it's an option if you don't want your users to have to learn about security. Though you already force your users to learn all manner of unnecessarily complicated things like API calls, PHP templates, and gulp/yarn/scss for something as simple as modifying CSS, so I don't see why you draw the line at security.

If you have any additional questions I and many others (like Scott Helme) are available for assistance. What we can't do is keep waiting for someone both benevolent and technical enough in Ghost to not only implement this solution but also submit it as a PR only to be rejected by you.

I apologize if I came off as rude, but I really felt these issues needed to be addressed. Thank you for all the great work. If it wasn't appreciated I wouldn't be here trying to improve it.

### Steps to Reproduce

Listed above.

### Ghost Version

all

### Node.js Version

all

### How did you install Ghost?

all

### Database type

MySQL 5.7

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by CarlSinclair** [comment]
#11084 seems to have attracted volunteers but they have been ignored.
A pull request was made here #12707 but ultimately rejected.

**Comment by ErisDS** [comment]
Honestly, I feel like there's been a glitch in the matrix with this issue - which is critiquing and restarting a conversation which happened 7-5 years ago as if it happened last week, whilst totally missing the key points made in the [closing statement](https://github.com/TryGhost/Ghost/issues/7206#issuecomment-374878567). 

If you want to be a productive participant and restart this conversation then you need to show up that way, as someone productive and willing to contribute something of value. Showing up and being rude and aggressive creates an environment in which noone wants to listen to you or help you on your mission.

So I'm gonna close this again with some of the exact words from John from _**5 years ago**_

> People show up to github with the expectation that, if a reasonable case is made for the legitimacy of their pet feature then the maintainer's moral obligation is to acquiesce and build it for them.

> Everyone needs to understand that this is not how open source works.

> We build the product we want to build. We do our best to prioritise and make good decisions, but we're far from perfect. We give away the rights to everything we release, so that you can build on top of it. That's how open source works.

And again:

> If anyone wants to make a new proposal for functional and viable CSP support in Ghost, that's totally fine and very welcome - you can start with a new issue and a clean slate. (Even better: start the discussion with a PR)
