### ISSUE TITLE
About is out of view

### ISSUE THREAD

**Issue by ItzNotABug** [TryGhost/Ghost#19175]
### Issue Summary

The About menu tile in the settings goes out of the view on an iPad & cannot be scrolled to.
It is not even visible on a mobile phone [Safari], if thats where it is supposed to.

See: 
https://github.com/TryGhost/Ghost/assets/20625965/113e5a0b-828d-4ad8-aab2-bfd66abeac5f

### Steps to Reproduce

1. Go to Settings.
2. Attempt to Find and Click About.

### Ghost Version

5.74.5

### Node.js Version

18.18.0

### How did you install Ghost?

Self hosted, Ubuntu

### Database type

MySQL 8

### Browser & OS version

Whatever version of Safari that is shipped with iOS & iPadOS 17.1.1.

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by daniellockyer** [comment]
Would you be able to paste a new video showing what you're seeing?
