### ISSUE TITLE
Axios Error

### ISSUE THREAD

**Issue by tanayvaswani** [TryGhost/Ghost#19219]
### Issue Summary

Content API is throwing Axios error. 

### Steps to Reproduce

1. Setup Next.js App
2. Install @tryghost/content-api
3. New GhostContentAPI and setup env file
4. getPosts() function when called on the page.tsx or any server component, throws an error 
5. Throws an undefined object 

### Ghost Version

v5.x

### Node.js Version

v18.18.2

### How did you install Ghost?

npm install ghost-cli@latest -g

### Database type

SQLite3

### Browser & OS version

Chrome, Safari, Edge, Brave

### Relevant log / error output

```shell
AxiosError: There is no suitable adapter to dispatch the request since :
- adapter xhr is not supported by the environment
- adapter http is not available in the build
```

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by gauravruhela07** [comment]
Hey @tanayvaswani, I want to work on this issue, can you please assign it to me? Thank you.

**Comment by tanayvaswani** [comment]
> Hey @tanayvaswani, I want to work on this issue, can you please assign it to me? Thank you.

I don't have any link with Ghost team, nor I'm a part of it. If you still wanna work, go ahead and raise a PR with the required fix.
Thanks!

**Comment by dheerajmartpe** [comment]
Hey @tanayvaswani Could you help me find out the location of the file: page.tsx ? I might resolve the error.

**Comment by SushiWaUmai** [comment]
I'm getting the same error, all I do is
```ts
import GhostContentAPI from "@tryghost/content-api";
import { BACKEND_URL, BACKEND_API_KEY } from "./constants";

const api = GhostContentAPI({
  url: BACKEND_URL,
  key: BACKEND_API_KEY,
  version: "v5.0",
});

export async function getPost(slug: string) {
  return await api.posts.read({ slug }).catch((err) => {
    console.error(err);
  });
}
```

And importing the above function like this: 
```tsx
export default async function Page({ params }: PageProps) {
  const post = await getPost(params.slug);
  ...
}
```

**Comment by 20manas** [comment]
I was able to fix it with this:
```typescript
const api = new GhostContentAPI({
  url: ...,
  key: ...,
  version: ...,
  makeRequest: async ({url, method, params, headers}) => {
    const apiUrl = new URL(url);
    Object.keys(params).map(key => apiUrl.searchParams.set(key, params[key]));

    return fetch(apiUrl.toString(), {method, headers})
      .then(async res => {
        if (!res.ok) {
          throw new Error(`HTTP error! status: ${res.status}, response data: ${await res.text()}`);
        }

        return {data: await res.json()};
      })
      .catch(error => {
        console.error('Fetch error:', error);
      });
  },
});
```

**Comment by tanayvaswani** [comment]
@20manas is it working during prod build? with strict set to true
