### ISSUE TITLE
Highlighting image alt text with mouse makes drag/drop mini-image appear

### ISSUE THREAD

**Issue by stromfeldt** [TryGhost/Ghost#19244]
### Issue Summary

If one tries to highlight alt text of an image with the mouse the drag/drop mini image appears, which is not only confusing but also gets in the way of the highlighting.

https://github.com/TryGhost/Ghost/assets/27488257/44333019-4e39-403b-9b1d-906b729047af

### Steps to Reproduce

1. Add alt text to an image
2. Highlight a portion of the alt text with the mouse
3. See the drag/drop mini image appear

### Ghost Version

5.75.1+moya

### Node.js Version

Yes

### How did you install Ghost?

Ghost(Pro)

### Database type

MySQL 5.7

### Browser & OS version

Firefox 120.0.1, macOS 13.6

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by asenseofpradhyu** [comment]
Hello @kevinansfield 

can you me whats need to be done as per ghost team?
