### ISSUE TITLE
Pushed empty image (on docker hub) with tag "5.75.1"

### ISSUE THREAD

**Issue by Mark24Slides** [TryGhost/Ghost#19252]
### Issue Summary

Pushed empty images with tag "5.75.1" (+ alpine) oo docker repository, did not upgrade "latest" tag.

### Steps to Reproduce

1. Find and open ghost images repo: https://hub.docker.com/_/ghost
2. Check image with tag "5.75.1"

### Ghost Version

5.75.1

### Node.js Version

-

### How did you install Ghost?

-

### Database type

MySQL 8

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by daniellockyer** [comment]
The Docker image is not maintained by us, so you'll need to go and report it to them here: https://github.com/docker-library/ghost
