### ISSUE TITLE
Issue with rendering text in the Signup card

### ISSUE THREAD

**Issue by fueko** [TryGhost/Ghost#19253]
### Issue Summary

The Signup card does not receive the style with white text (as is the case with the header card) when the card background is set to dark. As a result, this makes the text illegible and inconsistent with contrast principles.

For example Header card:
![Zrzut ekranu 2023-12-6 o 10 06 06](https://github.com/TryGhost/Ghost/assets/23366922/d61eb9e7-719e-41f2-882d-d84fcfd4c30e)

### Steps to Reproduce

Add a Signup card and set a dark background color.

### Ghost Version

5.75.1

### Node.js Version

18.12.1

### How did you install Ghost?

localhost

### Database type

SQLite3

### Browser & OS version

All

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by jaswalsaurabh** [comment]
Hi @daniellockyer can I work on this.

**Comment by jaswalsaurabh** [comment]
I've found that there is an issue with the conversion of **lexical to html**.

**Comment by jaswalsaurabh** [comment]
I've cloned the repo of koenig-editor and found out that this issue is fixed by **Steve Larson on Dec 14**. But when I check the installed **@tryghost/kg-default-nodes** module, those changes are not reflected yet in this. But the version are same 1.0.3
