### ISSUE TITLE
Text blink during activation of native search

### ISSUE THREAD

**Issue by fueko** [TryGhost/Ghost#19291]
### Issue Summary

Upon clicking the search element in the Safari browser (Sonoma 14.1.2), there is a momentary blink of the unstyled input element:

![Zrzut ekranu 2023-12-8 o 11 02 01](https://github.com/TryGhost/Ghost/assets/23366922/45006bdc-a264-4ed7-a5aa-ebfb28c5136b)
![search](https://github.com/TryGhost/Ghost/assets/23366922/e35de79a-1799-47c7-aa9b-47228cec87bf)

Perhaps the same issue is also causing random incorrect loading of the search element in the mobile Safari browser (iPhone, iOS 17.1.2)

![mobile](https://github.com/TryGhost/Ghost/assets/23366922/4f902dda-b2ad-4425-b5c0-cc0a9653d2f2)

### Steps to Reproduce

Go to the [source.ghost.io](https://source.ghost.io) page and click on the search element.

### Ghost Version

5.75.1

### Browser & OS version

Safari (Sonoma 14.1.2)

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by daniellockyer** [comment]
Hey there, thank you so much for the detailed bug report.

That does look like something that shouldn't happen! A PR to fix this issue would be very welcome 🙂

**Comment by asenseofpradhyu** [comment]
Hello @fueko @daniellockyer 

I attempted to reproduce the reported issue in Mac Safari browser (Sonoma 14.1.2). However, everything seems to be working fine on my end. 

If I've missed anything or if there are specific steps I should follow, please let me know. I've also attached a video demonstrating how it looks.

![ezgif com-video-to-gif-converted](https://github.com/TryGhost/Ghost/assets/24241624/ecb2ff5f-feb3-48ca-8846-3ad1a4970ff0)

**Comment by btme0011** [comment]
Can i work on this issue?

**Comment by fueko** [comment]
Hi @asenseofpradhyu! 

In my case, the issue occurs on both mobile devices and when browsing with Safari on desktop (this is a completely new system installation). Unfortunately, I am unable to pinpoint the exact cause of this behavior. From what I have observed, it may be related to accessibility settings, as Safari briefly highlights the input for a fraction of a second, possibly triggering it before it is loaded correctly.
