### ISSUE TITLE
URLs of blogs changes to English even if I type the url in Hindi  or other languages

### ISSUE THREAD

**Issue by mukesh-kkkk** [TryGhost/Ghost#19397]
### Issue Summary
![ghost](https://github.com/TryGhost/Ghost/assets/139126333/b746d5cf-265e-4084-acc3-fdb789fab962)

I typed the url exactly as in the title of the blog. But it automatically converted to English.
I want the urls to be  exactly similar to the title.

### Steps to Reproduce

1. Go to ghost admin 
2. Try to write a new post with title in Hindi.
3. Paste the Hindi title in  the right side drawer for url creation.
4. You can see that it automatically converts that to English  

### Ghost Version

5.7

### Node.js Version

18

### How did you install Ghost?

cli

### Database type

SQLite3

### Browser & OS version

chrome

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by markstos** [comment]
This has been a recurring request and the latest web standards support non-latin characters in URLs. It is aligned with Ghost's goal to offer the platform in multiple languages now. Here's what I posted in the forum about this:

----
It used to be that such characters were not allowed in URLs, according to RFC 3986.

But according to the newer [WHATWG standard for URLS](https://url.spec.whatwg.org/), Unicode is allowed in URLs if the code points are in the range U+00A0 to U+10FFFD.

It appears the code points you tried to use were these two:

Hangul Syllable Hel (U+D5EC)
Hangul Syllable Ro (U+B85C)
It seems to me like they would be in the valid range.

To me, this seems like be a bug in Ghost if Ghost is still creating URLs based on the older RFC 3986 standard for URL formats and not the WHATWG URL spec.

Ghost might be able to replace it’s current URL building library based on the old standard with one based on the new standard, like [whatwg-url - npm 2](https://www.npmjs.com/package/whatwg-url)

That's from:  https://forum.ghost.org/t/can-i-not-use-english-on-post-url/40348

See Also:

* https://forum.ghost.org/t/to-turn-off-automatic-url-translation-into-latin/1817
* https://forum.ghost.org/t/how-to-use-multi-language-urls/33576
