### ISSUE TITLE
 TypeError: Cannot read properties of undefined (reading 'gscan_errors') 

### ISSUE THREAD

**Issue by mlushpenko** [TryGhost/Ghost#19400]
### Issue Summary

I am trying to change the theme to `Source` and getting a blank page after pressing `Activate Source` and this error in javascript console:

```
 TypeError: Cannot read properties of undefined (reading 'gscan_errors') 
```

### Steps to Reproduce

1. Go to `Settings > Design & branding > Customize`
2. Select `Source` theme and try activating it 

### Ghost Version

5.75.2

### Node.js Version

v18.19.0

### How did you install Ghost?

Bitnami ghost helm chart (kubernetes)

### Database type

MySQL 8

### Relevant log / error output

```shell
No logs, I'd actually appreciate some pointers on how to enable access and maybe configuration changes logs on ghost.
```

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by daniellockyer** [comment]
I can't seem to reproduce this - do you have the correct Source files in place?

**Comment by mlushpenko** [comment]
Good question, @daniellockyer, if I look at installed themes, I don't see the source theme there

<img width="987" alt="image" src="https://github.com/TryGhost/Ghost/assets/2006610/df65f593-6da0-4f12-905c-a195a70a48d3">

But if I click on the source theme, I only have the button to activate it, not to install it, not sure why:

<img width="1004" alt="image" src="https://github.com/TryGhost/Ghost/assets/2006610/4eb90bc9-b953-483b-bd0c-de6f20a33f89">

Please let me know if I can provide some debugging info and how to do it. It's not a critical issue for me, but seems like some sort of a bug.

**Comment by mlushpenko** [comment]
But I've replied. It's ok if it's closed, but it's some sort of a bug.

**Comment by jakerr** [comment]
I ran into the same issue today. I worked around it by manually copying the contents of the theme from the "current" simlink directory in contents into contents/themes. Then I could activate my copied "Source" theme from the "installed" tab, after restarting my docker container.

**Comment by jakerr** [comment]
@daniellockyer hello, I believe this was closed prematurely. Can you please take another look?
