### ISSUE TITLE
Wrong URL for Tag's `Learn More`

### ISSUE THREAD

**Issue by ItzNotABug** [TryGhost/Ghost#19448]
### Issue Summary

The edit tag [page](https://github.com/TryGhost/Ghost/blob/3c4b981674fb9483a63babc07229138076f04002/ghost/admin/app/components/tags/tag-form.hbs#L28) contains a legacy url on details for public & private tags, i.e. https://ghost.org/help/organising-content/#private-tags which redirects to a 404.

### Steps to Reproduce

Tags > Select any Tag > Click `Learn More` below the tag's name field.

### Ghost Version

5.75.2

### Node.js Version

v18.18.0

### How did you install Ghost?

Self hosted on Ubuntu.

### Database type

MySQL 8

### Browser & OS version

N/A

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by aileen** [comment]
Heya! Thanks for reporting this! It should be fixed now 😊
