### ISSUE TITLE
Default Amazon 2019 CA for RDS is deprecating

### ISSUE THREAD

**Issue by SilentEntity** [TryGhost/Ghost#19462]
### Issue Summary

While using Ghost there is an option to use Amazon RDS with ssl.
The option `ssl:"Amazon RDS"` will not be working if the CA is not updated in the `mysql2` package.
Ghost has a dependent package `knex` which has a dependent package mysql2. 

Ghost uses `knex` as an indirect dependency from [`knex-migrator`](https://github.com/TryGhost/knex-migrator)

- https://github.com/knex/knex/issues/5786
- https://github.com/sidorares/node-mysql2/pull/2131

For more info: https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.SSL.html

### Steps to Reproduce

Generic for all future releases

### Ghost Version

latest

### Node.js Version

NA

### How did you install Ghost?

Using Docker

### Database type

MySQL 8

### Browser & OS version

Any

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by SilentEntity** [comment]
Work Around: https://observhq.vercel.app/blog/ghost/ghost-ca-update-for-rds

**Comment by daniellockyer** [comment]
Unfortunately we're blocked by https://github.com/knex/knex/pull/5633 right now, but we can merge Knex once that is fixed
