### ISSUE TITLE
Admin-X metadata page shows icon incorrectly

### ISSUE THREAD

**Issue by cathysarisky** [TryGhost/Ghost#19531]
### Issue Summary

The metadata section of the Ghost admin panel doesn't show the user's site logo correctly. 
See below:
![image](https://github.com/TryGhost/Ghost/assets/42299862/9e0e21f6-b328-455f-b772-df22ffd49e87)
The logo is getting cropped (that's the top left corner of it), rather than sized to fit into the circle.
This component needs a background-size: contain in order to better predict what search engines will do.

This is only a display issue - no actual search problem, but it's confusing to users.

### Steps to Reproduce

Upload a logo bigger than 60x60 (my test logo is 100x100)

### Ghost Version

5.75

### Node.js Version

ghost pro

### How did you install Ghost?

ghost pro

### Database type

MySQL 8

### Browser & OS version

Chrome, Windows 10

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by jatinder14** [comment]
hi @cathysarisky please assign this issue to me

**Comment by cathysarisky** [comment]
> hi @cathysarisky please assign this issue to me

I'm not the core team and can't do this for you.  The core team has said elsewhere (no reference, sorry) that they don't assign issues to new contributors, but you can submit a PR for it.
