### ISSUE TITLE
Last item in history list gets cut off

### ISSUE THREAD

**Issue by stromfeldt** [TryGhost/Ghost#19546]
### Issue Summary

The last item in the history list gets cut off at the bottom.

![Xnapper-2024-01-23-15 52 32](https://github.com/TryGhost/Ghost/assets/27488257/337afd0b-faaf-49c6-b168-abd5817456c7)

### Steps to Reproduce

1. Open up the history tab
2. See that the last item in the list gets cut off at the bottom

### Ghost Version

5.76.1+moya

### Node.js Version

Yes

### How did you install Ghost?

Ghost(Pro)

### Database type

MySQL 5.7

### Browser & OS version

Firefox 121.0.1 and Safari 17.3 on macOS 14.3

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by shahid4003** [comment]
i want to fix this issue is this still open?
