### ISSUE TITLE
Pasting a link over text that contains text with italics duplicates a portion of the text

### ISSUE THREAD

**Issue by stromfeldt** [TryGhost/Ghost#19547]
### Issue Summary

Pasting a link over text works just fine, but when trying to paste a link over text that contains italicised text, part of the text gets duplicated (it would appear to be the italicised portion and whatever follows).

https://github.com/TryGhost/Ghost/assets/27488257/7fba7f6e-846c-4912-9073-e90ee5aef6bf

### Steps to Reproduce

1. Create a sentence, and italicise a portion of it (in the middle)
2. Highlight a portion of the sentence, including the italicised portion, and paste over the link
3. See that extra text is created

### Ghost Version

5.76.1+moya

### Node.js Version

Yes

### How did you install Ghost?

Ghost(Pro)

### Database type

MySQL 5.7

### Browser & OS version

Firefox 121.0.1 and Safari 17.3 on macOS 14.3

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by og118** [comment]
Hi, Can I contribute to this issue?

**Comment by kevinansfield** [comment]
Closed via https://github.com/TryGhost/Ghost/pull/19671
