### ISSUE TITLE
Styles are broken when video is inserted into the editor

### ISSUE THREAD

**Issue by mtane0412** [TryGhost/Ghost#19557]
### Issue Summary

When I insert an mp4 video into the editor, the style is severely out of place.
This did not change with drag and drop or with the slash command.
I have tried different videos and it reproduces the problem.

https://github.com/TryGhost/Ghost/assets/10510365/9a88435d-12aa-4b15-aa46-5655f67f4cc2

### Steps to Reproduce

1. Upload your video using `/video`

### Ghost Version

Ghost(Pro)

### Node.js Version

Ghost(Pro)

### How did you install Ghost?

Ghost(Pro)

### Database type

Other

### Browser & OS version

Google Chrome Version 120.0.6099.234 (Official Build) (arm64) / macOS Sonoma Version 14.2.1 (23C71)

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by SoldierCorp** [comment]
Hi @kevinansfield 

I have the latest Ghost version installed, but I am still seeing this issue in the editor.
