### ISSUE TITLE
🐛 Custom excerpts containing escaped characters are truncated inappropriately

### ISSUE THREAD

**Issue by 9larsons** [TryGhost/Ghost#19559]
### Issue Summary

ref dc7e2b9, https://ghost.slack.com/archives/CTH5NDJMS/p1706034566392689

Customers using custom excerpts containing quotes and other escaped characters were seeing the text cut short, sometimes in the middle of words. 

### Steps to Reproduce

1. Create a custom excerpt using quotes
2. Publish the post
3. View the excerpt from the home page

### Ghost Version

v5.76.1

### Node.js Version

18

### How did you install Ghost?

Mac Sonoma

### Database type

MySQL 5.7

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by 55sketch** [comment]
Closed as duplicate
