### ISSUE TITLE
Deleting a published post leaves you in the editor

### ISSUE THREAD

**Issue by danielraffel** [TryGhost/Ghost#19563]
### Issue Summary

Deleting a published post leaves you in the editor and tapping the back arrow to exit back to posts does not work. 

### Steps to Reproduce

1. Publish a post
2. go to editor and delete it
3. notice that you are not exited from the editor and that the button to exit to posts does not work

### Ghost Version

5.76.1

### Node.js Version

18

### How did you install Ghost?

npm install

### Database type

MySQL 8

### Browser & OS version

Safari 17.2.1 macOS Sonoma 14.2.1

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by daniellockyer** [comment]
Duplicate of https://github.com/TryGhost/Ghost/issues/19408

**Comment by danielraffel** [comment]
This is reproducible in ghost 5.79.0
