### ISSUE TITLE
Migration error (recommendations table)

### ISSUE THREAD

**Issue by javimosch** [TryGhost/Ghost#19682]
### Issue Summary

Error occurred while executing the following migration: 2023-10-06-15-06-00-rename-recommendations-reason-to-description.js

The error happens because the recommendations table doesn't exists in the DB.

### Steps to Reproduce

- I started a fresh install with docker-compose and ghost 5-alpine (5.3X) (Months ago)
- I changed the image to latest (5.7X)

### Ghost Version

5.76

### Node.js Version

18

### How did you install Ghost?

Docker-compose

### Database type

Other

### Browser & OS version

Ubuntu

### Relevant log / error output

```shell
ghost-1  | [2024-02-09 10:20:06] INFO Rollback was successful.
ghost-1  | [2024-02-09 10:20:06] ERROR ALTER TABLE `recommendations` RENAME COLUMN `reason` TO `description`; - You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'COLUMN `reason` TO `description`' at line 1
ghost-1  | 
ghost-1  | ALTER TABLE `recommendations` RENAME COLUMN `reason` TO `description`; - You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'COLUMN `reason` TO `description`' at line 1
ghost-1  | 
ghost-1  | {"config":{"transaction":false},"name":"2023-10-06-15-06-00-rename-recommendations-reason-to-description.js"}
ghost-1  | "Error occurred while executing the following migration: 2023-10-06-15-06-00-rename-recommendations-reason-to-description.js"
ghost-1  | 
ghost-1  | Error ID:
ghost-1  |     300
ghost-1  | 
ghost-1  | Error Code: 
ghost-1  |     ER_PARSE_ERROR
ghost-1  | 
ghost-1  | ----------------------------------------
ghost-1  | 
ghost-1  | Error: ALTER TABLE `recommendations` RENAME COLUMN `reason` TO `description`; - You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'COLUMN `reason` TO `description`' at line 1
ghost-1  |     at /var/lib/ghost/versions/5.79.0/node_modules/knex-migrator/lib/index.js:1032:19
```

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by javimosch** [comment]
Additional information:

I was able to solve the issue by doing a docker-compose up in a new database, then copying the missing tables (recommendation*) into the existing database, and running compose again.

**Comment by daniellockyer** [comment]
@javimosch I'm going to guess you're using MariaDB < 10.5.2? Support for `RENAME COLUMN` was only added in 10.5.2: https://mariadb.com/kb/en/alter-table/#rename-column

It's worth noting that we don't officially support MariaDB, and MySQL 8 is the only production database we do support
