### ISSUE TITLE
HTML Cards and embedded HTML is broken

### ISSUE THREAD

**Issue by pezi** [TryGhost/Ghost#19752]
### Issue Summary

https://forum.ghost.org/t/problem-with-html-cards-and-embedded-html-codes/44955

Sorry for opening an issue for a known problem  - but this problem is really annoying. I use Ghost for a development blog - and most code snippets are still broken. 

### Steps to Reproduce

See blog entry

### Ghost Version

5.79.4

### Node.js Version

v18.19.1

### How did you install Ghost?

manually

### Database type

MySQL 8

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by kevinansfield** [comment]
This was fixed in https://github.com/TryGhost/Ghost/pull/19728 and will be included in the next release.
