### ISSUE TITLE
Comment failed to initialize version: "0.15"

### ISSUE THREAD

**Issue by minovc3** [TryGhost/Ghost#19786]
### Issue Summary

Greetings,
I'd like to report an issue I've encountered. After upgrading from comments version "0.13" to version "0.15", there seems to be a problem with loading comments. This issue appears to be connected to an API request at:"https://site.com/members/api/comments/post/65be90c82bf1790001f68413/?limit=5&page=1"

Below is the error message displayed in the Chrome developer console:

![CleanShot 2024-03-01 at 14 04 28@2x](https://github.com/TryGhost/Ghost/assets/115098273/c32f459d-d346-4bda-81fe-ad2e97a3acf7)

Reproduced with self hosted latest ghost versions: 5.79.6, and 5.79.4 using the official Debian docker image built locally on ARM.

First, I have been loading comments from here  

`"comments": {
      "url": "https://cdn.jsdelivr.net/ghost/comments-ui@~{version}/umd/comments-ui.min.js",
      "version": "0.15"
    },`

Then, I attempted to rebuild the comments app from scratch and load it locally, but encountered the same problem.

`},
    "comments": {
      "url": "https://site.local/umd/comments-ui.min.js"
    },`

Returning to "version": "0.13" solves the problem of loading comments, whether from cdn.jsdelivr.net or when compiling them locally.

Tested on different browsers : Safari, Chrome and Firefox 

### Steps to Reproduce

1. Accessed a blog post using a web browser.
2. Inspected the comment section, which failed to load.
![CleanShot 2024-03-01 at 14 23 35](https://github.com/TryGhost/Ghost/assets/115098273/f0f2f0cc-4f95-42f3-b1e0-95e2eb4a0ee6)
3. Examined the errors in the Developer console:
![CleanShot 2024-03-01 at 14 25 57](https://github.com/TryGhost/Ghost/assets/115098273/71d25bd2-0dfb-4f89-9ee3-9df868f95604)

### Ghost Version

5.79.6

### Node.js Version

node:18

### How did you install Ghost?

Via docker on Ubuntu 

### Database type

MySQL 8

### Browser & OS version

Safari, Chrome, Firefox on Mac & Iphone

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by vikaspotluri123** [comment]
Can you try upgrading to 5.80.0 (that was released an hour ago)? My guess is either the comments-ui version picked up by older versions of Ghost is incorrectly selecting v0.15, or v0.15 needs to add a check for the Ghost version and switch its behavior - the endpoint that's 404'ing was added in 5.80.0.

Side note - Ghost doesn't officially support the Docker image, that's handled by the Docker Community/Docker.

**Comment by minovc3** [comment]
Understood! Appreciate it. I have builded the most recent 5.80.0 Ghost docker image with the updated comments app independently from the main repository, and that resolved the problem. 
Thanks once more for the prompt assistance.
