### ISSUE TITLE
Database suggestion from Planetscale

### ISSUE THREAD

**Issue by kmskrishna** [TryGhost/Ghost#19783]
### Issue Summary

I am using planetscale to host by ghost blog Database and it gave me this suggestion. Not sure if it helps.

![CleanShot 2024-03-01 at 15 39 46@2x](https://github.com/TryGhost/Ghost/assets/7846950/301df9d7-b54d-4ecf-bd57-cd307034495d)

### Steps to Reproduce

NA

### Ghost Version

Latest

### Node.js Version

20.*

### How did you install Ghost?

Docker

### Database type

MySQL 8

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by allouis** [comment]
Hey @kmskrishna thanks for the issue!

We'd love a pull request to fix this :relaxed:

We'd need to touch the `schema.js` file as well as a migration
