### ISSUE TITLE
Code Syntax highlighting is unpredictable

### ISSUE THREAD

**Issue by pulkitchhabra6** [TryGhost/Ghost#19787]
### Issue Summary

When I add code snippets to posts using ```cpp, the syntax highlighting for those pieces of codes is unpredictable. It sometimes is there, and sometimes isn't. The hack that I've found is that refreshing the article 2-3 times makes the syntax highlighting come, but this, in my opinion, is not a good enough fix for the users.

### Steps to Reproduce

1. Go to [this](https://read.learnyard.com/getting-a-hang-of-recursion/ ) article. (if you’re not able to reproduce it in this article, please try another article from the list)
2. Try to hard refresh (using cmd + shift + R) about 5-7 times, you'll probably see the syntax highlighting coming and going.

Watch [this](https://drive.google.com/file/d/1njCC9gEWHxOXO71HCeqNMPL0f8_jZ18w/view?usp=sharing) screen recording to see the issue.

### Ghost Version

5.68.0

### Node.js Version

16.20.1

### How did you install Ghost?

Host : AWS Lightsail, OS : Linux 11 (bullseye) .We installed following this doc - https://docs.aws.amazon.com/lightsail/latest/userguide/amazon-lightsail-quick-start-guide-ghost.html

### Database type

MySQL 8

### Browser & OS version

Chrome Version 122.0.6261.94 (MacOS)

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by vikaspotluri123** [comment]
This looks to be a problem with your theme, not with Ghost.

**Comment by royalfig** [comment]
@vikaspotluri123 is right. Syntax highlighting is part of the theme. Reach out to your theme designer for help or make a post on the [Forum](https://forum.ghost.org).
