### ISSUE TITLE
Node Version Requirement Not Declared Fine Enough

### ISSUE THREAD

**Issue by sushantshah-dev** [TryGhost/Ghost#19824]
### Issue Summary

![Screenshot 2024-03-08 003104](https://github.com/TryGhost/Ghost/assets/103421781/99a76ffb-75b6-47b6-ac01-f114e72b58dc)

### Steps to Reproduce

The first prompt tells us to install 18.0.0, next tells to install 18.12.1

### Ghost Version

v5.80.1

### Node.js Version

---

### How did you install Ghost?

CLI

### Database type

Other

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by vikaspotluri123** [comment]
The first line tells you what version was found. You need at least node 18.12.1 while you have 18.0.0. This is expected behavior.

**Comment by sushantshah-dev** [comment]
I think I forgot to attach another image... In that it said the requirement was different...

**Comment by vikaspotluri123** [comment]
Without seeing the image, it'll be hard to reproduce your issue 🙂

**Comment by daniellockyer** [comment]
Hi @sushantshah-dev - thanks for the report. We're going to be looking at updating our supported Node ranges soon, but the workaround is to use a supported Node version 🙂
