### ISSUE TITLE
Comments broken in latest release

### ISSUE THREAD

**Issue by cathysarisky** [TryGhost/Ghost#19841]
### Issue Summary

Clicking on the comments box causes the entire comments section to disappear.

The problem only occurs for NON-admin users trying to view comments.  

### Steps to Reproduce

Host a site on Ghost Pro, with comments enabled.  Click the box to type a comment.  The entire comments section vanishes, with the error message below.

### Ghost Version

Ghost Pro

### Node.js Version

Ghost Pro

### How did you install Ghost?

Ghost Pro

### Database type

MySQL 8

### Browser & OS version

Chrome, Windows recent.

### Relevant log / error output

```shell
react-dom.production.min.js:216 TypeError: Cannot set properties of null (setting 'current')
    at yte.setNode (IFrame.tsx:62:29)
    at mX (react-dom.production.min.js:259:307)
    at t.unstable_runWithPriority (scheduler.production.min.js:18:343)
    at ti (react-dom.production.min.js:122:325)
    at ri (react-dom.production.min.js:252:279)
    at hd (react-dom.production.min.js:243:371)
    at react-dom.production.min.js:123:115
    at t.unstable_runWithPriority (scheduler.production.min.js:18:343)
    at ti (react-dom.production.min.js:122:325)
    at Ug (react-dom.production.min.js:123:61)
```

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by cathysarisky** [comment]
Kevin, I can get it on both sites.  The trick is that you have to be logged in NOT as an admin user to see them.

**Comment by kevinansfield** [comment]
@cathysarisky if you refresh on one of your comments-enabled posts (pref with cache disabled in browser via developer tools in case you're within the 600sec cache window for the comments-ui script) you should be back in a working state. Let us know if you are still experiencing issues!

**Comment by cathysarisky** [comment]
> @cathysarisky if you refresh on one of your comments-enabled posts (pref with cache disabled in browser via developer tools in case you're within the 600sec cache window for the comments-ui script) you should be back in a working state. Let us know if you are still experiencing issues!

Confirmed working, and thanks!
