### ISSUE TITLE
Feature: Code injection to theme header/footer via blog settings

### ISSUE THREAD

**Issue by JohnONolan** [TryGhost/Ghost#1993]
This has been talked about vaguely in multiple places a few times, so I wanted to open an issue to centralise the discussion and get it on the historical record.

Several platforms have a feature which allows users to inject code into their user-facing site via an account settings panel. I have included one example screenshot implementation of this (Squarespace) below.

Personally - I think this would be great to have in Ghost. It's an instant, easy way to drop in code for analytics, site verification, meta attributes, 3rd party service integrations, and many other "quick things" which would be nice to be able to use without modifying a theme or writing a full app.

I believe, from memory, the arguments against revolved primarily around security concerns. (@erisds?)

---

![image](https://f.cloud.github.com/assets/120485/1960803/657d9f1a-825b-11e3-9aec-e4f49fcaa45a.png)

The "Click here for more help" link in the screenshot, goes here: http://help.squarespace.com/customer/portal/articles/438250

**Comment by ckib16** [comment]
Hey all - just wanted to say thanks for developing this feature. I was a SquareSpace user for a long time and can confirm they definitely got their code injection implementation right. SS was the first time I had ever used something like feature before, but found it very easy to use - just copy & paste.

I think you are on the right path to keeping it simple for the user!

**Comment by ErisDS** [comment]
@ckib16 Glad you like it :)

There are a few last pieces of the code injection puzzle to land before we can move it out of labs, the big one is here: #4995 + I have a [PR](#4932) with some text amends to sort out.

**Comment by amio** [comment]
For the icon part, how about build a gulp task for generating icon and example usage html?

I had made one like this:
https://github.com/baixing/baicons
For adding new icon, developer can simply place the svg file into `source` directory,
then excute `gulp build` to generate the full font set including ttf, woff, eot, and svg, and with a [demo page](http://baixing.github.io/baicons/icons-reference.html).
