### ISSUE TITLE
Handlebars special partial "@partial-block" gets reported as unknown global

### ISSUE THREAD

**Issue by miko007** [TryGhost/Ghost#19930]
### Issue Summary

The handlebars template engine provides an internal, special partial called [`@partial-block`][block-partial], that can be used when calling a partial in *"block style"*.

Instead of calling the partial regularly like `{{> my-partial}}`, it can be called in block form like

```handlebars
{{#> my-partial}}
  some fallback text
{{}/my-partial}
```

Inside the partial, the content passed inside the block can then be accessed using the special partial `{{@partial-block}}`. The feature itself works like expected inside of a ghost theme, the usage gets however reported as a theme error, specifically as *"`{{@partial-block}}` is not a known global"*. This should not be the case.

<img width="497" alt="image" src="https://github.com/TryGhost/Ghost/assets/1271957/3edb2a45-bbc5-4049-ab88-696f4509e51d">

[block-partial]: https://handlebarsjs.com/guide/partials.html#partial-blocks

### Steps to Reproduce

1. put a partial with the content
 ```handlebars
 <div>
    fancy partial
      {{#if @partial-block}}
	<article>
		{{> @partial-block}}
	</article>
      {{/if}}
</div>
 ```
in a theme.

2. call it like
```handlebars
{{#> my-partial}}
   this is a fallback text
{{/my-partial}}
```
3. check backend for theme errors

### Ghost Version

5.75.1

### Node.js Version

18.19.0

### How did you install Ghost?

docker

### Database type

MySQL 5.7

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by daniellockyer** [comment]
Hey there, thank you so much for the detailed bug report.

That does look like something that shouldn't happen! A PR to fix this issue would be very welcome 🙂
