### ISSUE TITLE
Plain text view

### ISSUE THREAD

**Issue by mallory** [TryGhost/Ghost#20015]
### Issue Summary

It appears that most Ghost themes aren't well designed for plain text views of email messages. I would suggest adding an option in composition of the post to modify the plain text rendering.

For example, the last post I sent was also sent as a newsletter and it added a ton of whitespace to the top of the post, such that my readers who read in plain text thought that the edition was empty. It wasn't, but one had to scroll and scroll in order to get to the body of the post.

I could have fixed this had I been able to see and modify the plain text version of my post before sending. Some other newsletter software allows for this.

Thanks for considering this feature.

### Steps to Reproduce

1. Send a newsletter
2. Open in email
3. View as plain text (often only an option in an email client like Thunderbird)

### Ghost Version

hosted

### Node.js Version

n/a

### How did you install Ghost?

hosted

### Database type

MySQL 5.7

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by markstos** [comment]
This feature request should be filed as an idea in the forum, not here: https://forum.ghost.org/c/ideas/5

It seems the amount of people reading email as plain text these days might hover around 1% or less, so I won't be surprised if it's not a core team priority.

I was one of the people who held on plain-text email longer than most, but I gave up on defaulting to that more than 10 years ago as such a large percentage of mail had shifted to HTML-only and the plain text version was poorly formatted in not only rare cases, but commonly. 

If you are interested in having Ghost produce awesome plain-text emails in some themes, I don't expect many people object if you want to contribute those improvements.

**Comment by mallory** [comment]
On the other hand that a dozen carriage returns appear at the top of a plaintext rendering of the email is probably a bug. I thought it was a theme issue-- perhaps assuming that this was due to title image padding in the HTML-- but the theme repo asked me to post it here.

In any case, I can't seem to figure out where these carriage returns are coming from.
