### ISSUE TITLE
Discussion: Error handling, logging and debugging improvements

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#2001]
As it stands, Ghost has errorHandling which is used throughout the system, leaving it reasonably consistent. We also have the nice red-white-green error messaging on the console to try to help people recover from issues.

Ghost is also reasonably good at recovering from problems, it has fall back and default behaviour in plenty of places... and we are improving that in other issues.

However, Ghost's log output is somewhat scarce when trying to debug problems. Ghost doesn't always tell people when something has gone a bit wrong... it can often just serve a non-OK response and sometimes the error can appear as a rendered 500 page but there's nothing in the log. We also don't log when we get empty responses from the DB etc.. we just carry on.

I want to look at how we can improve this without adding too much code. I'd like to add an extra level of logging information. 

My initial thought is to start using logWarn, and only output this when in development mode, or when debug is set to true in config.js.

I'm not sure if this is the right approach though, I'm concerned about adding lots of extra code, and I'm also concerned that the improvement will be minimal without some sort of verbose logging mode in the middleware that traces through how a request is handled - express's logging is only about access logging as far as I can tell and won't output any more info.

So.. is there a way to log where next() gets called each time etc?

Thoughts in comments please :)

**Comment by esatterwhite** [comment]
I think using a transport based logger for application logging would be best. something like [winston](https://www.npmjs.com/package/debug) or [bunyan](https://www.npmjs.com/package/bunyan) that support syslog-like logging level filtering would be best. This also will let people aggregate their logs to external sources much easier. End users may want logs to be sent to sentry or log stash, etc.

Then ghost would need to provide a default logger instances, the ability to configure it, and potentially a way to use a different logging instance provided it implements the same interface. Keeps the internal work to a minimum and if someone doesn't like the way Ghost does its logging, or already has a logging solution, then it is available to them to do so.

For `debug` mode, It kind of already exists. Most things in the express world use [Debug](https://www.npmjs.com/package/debug) already. Why not use that for low level stuff. `DEBUG=ghost:*`

**Comment by ErisDS** [comment]
We have been using bunyan very successfully internally, and I had been thinking about suggesting that we use it in Ghost as well, but likely only in production mode. I don't think the JSON output is useful for developing.

**Comment by esatterwhite** [comment]
Ya, The nice thing about winston is it will json-ify output if the transport isn't attached to a tty interface and format string & pretty print objects for output if it is.

so you can easily have easy human readable output for debugging, and json messages send else where.

And when #5047 gets merged in, it would very simple to expose many transports and explicit levels based on types. It might look something like

`ghost --logger=stdout --logger:stdout:level=debug --logger=file --logger:file:level=warning`

This `logger.info('Hello %s', 'world', {a: { util: { formated: object } } } )` would print

`[TIMESTAMP] info - Hello world - {a: { util: { formated: object } } }`

and log json to a file
`{date:TIMESTAMP, level:"warning", msg:"something went bad"}` 

This would allow a single interface/module to satisfy multiple duties with out a lot of work internally

**Comment by halfdan** [comment]
knex has started to use the `debug` module which seems to be adopted by more and more projects.

**Comment by esatterwhite** [comment]
Debug is great for local debugging and dev. But mostly useless in production environments or large deployments. No standard formatting, no log levels, no way to configure anything, 
No transports

It is not really good for producing well structured logs. Which means you end up including two different logging solution and trying to determine when to use which one and for what.

If the primary goals are to make ghost as robust as possible, debug probably isn't the right option. Bunyan or Winston are better options. Winston being better suited for humans. Bunyan for machines.

**Comment by ErisDS** [comment]
Is Winston still under active development? I thought the project had gone dark.

**Comment by esatterwhite** [comment]
The team is still involved. Addressing issues and merging pull requests. The project is largely based on adapters, and doesn't need much in the way of new features IMOP.

**Comment by ErisDS** [comment]
I'd love to get this moved forward, on two fronts:
1) easier debugging during development
2) better, more useful logging

Part of me is tempted to just shove [debug](https://github.com/visionmedia/debug) in as a dependency and start using it in key places - like the boot sequence & API, so that we can see what time gets spent on whilst we're building new things. That's the major feature of debug IMO - the millisecond diffs since the last message makes it really easy to spot slow code.

However, as great as debug is, and several of our dependencies including knex and express use it too, it really is ONLY good for debugging whilst building features, refactoring or bug fixing. The benefits would be minimal, and we'd probably have to replace it really quickly.

Ideally, we need to start thinking about putting extensible logging in place, and having a 'logging' adapter available, so that developers can configure their logs to go where they want. I think it would be easier to setup this sort of system with Bunyan, rather than Winston, but I'm not 100% sold either way.

So.. if we pull that together, the requirements list here is:

- Full logging (bunyan or winston) which outputs to stdout/stderr as we do now
- Logging in debug mode (i.e. info messages) auto-includes millisecond times as in debug
- Ability to provide an adapter in future, to customise the destination/output of the logging system

Bonus:
- Some thought around what to do with our existing errors system which does some logging and some throwing, especially with regard to i18n (see #6526)

**Comment by esatterwhite** [comment]
I've done this with a [winston wrapper](https://bitbucket.org/megadoomer/bitters/src)

* Supports all Syslog logging levels as methods ( `crit`,`emerge`, `error`, `warning` ,etc )
* includes an `http` log level 0 for request logging
* configurable transports
* ad-hoc transports via configuration ( `-l custom --log:custom:module=somthing/that/can/be/required` )
* supports multiple trainsports ( `-l stdout -l syslog -l papertrail -l custom` )
* can pretty print errors 
* transport specific log levels. i.e. all errors can go to `transport A` and everything else can go to `transport B`

```javascript
logger.error( logger.execption.getAllInfo( error ) );
```
I haven't done much work on this particular module in a while,  happy to dust it off, or you can just steal things of course.

**Comment by kirrg001** [comment]
I've added `later` label.
Closing in favour of #7116
