### ISSUE TITLE
Timeout for requests

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#2003]
Again, in an attempt to make sure that Ghost doesn't crash, and continues to perform it's job, would it be a good idea to add a timeout for requests, set to something high like 30/45seconds?

If a request isn't served in that time, it would be nice to just display a 500 error page with a timeout warning, rather than leaving the request hanging.

Thoughts in comments?

**Comment by ErisDS** [comment]
Don't think this is required, if we ever find a need for it we can add it but I think this issue was pre-optimisation.

**Comment by rodrigogoncalves** [comment]
@ErisDS, do you know why logins take so long in a Raspberry Pi + Raspian? I am running into this issue and I am having a hard time debugging its causes.

**Comment by ErisDS** [comment]
@rodrigogoncalves see https://github.com/TryGhost/Ghost/issues/1207 :)
