### ISSUE TITLE
Outdated version of string-width is causing the Docker image entrypoint loading to fail.

### ISSUE THREAD

**Issue by LaurentGoderre** [TryGhost/Ghost#20065]
### Issue Summary

The update to fix arm32 architecture (https://github.com/TryGhost/Ghost/commit/c2485af853f7b3b86f7f141b8496439cdc4881b4) introduce a regression in the way the Ghost package is launched. When running `node index.js` there is a module resolution error similar to this issue https://github.com/nrwl/nx/issues/19249. I managed to solve the issue locally by adding `"string-width": "4.2.3"` to the `resolutions` section.

Here is the Docker test showing the error: https://github.com/docker-library/ghost/actions/runs/8756974313/job/24034646549

I would like to contribute this fix but I am not sure which `package.json` to use because the packaged one seems to be generated from the source ones.

### Steps to Reproduce

There is probably an more streamlined reproducible but building the Docker image here then running it (https://github.com/docker-library/ghost/tree/master/5/debian)

```
docker build -t ghost .
docker run --rm ghost 
```

### Ghost Version

5.82.3

### Node.js Version

18.*, 20.*

### How did you install Ghost?

In Docker using the Ghost CLI

### Database type

MySQL 5.7

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by zac** [comment]
I'm also seeing this in my docker build. Let me know if I can help provide any more info 👍

**Comment by ngeorger** [comment]
Currently I'm using kubernetes and a different approach to the entrypoint. I'm using distroless node 20 debian 12 as the final stage, and the entrypoint is actually a nodejs script which moves the themes and then inits the main function to start ghost.
At the moment I'm not having any issue at least with arm64. If it suits you, you can test it out too, because anyways it's still based on the "official" image (at least in the logic and general workflow of the dockerfile)

[@sredevopsorg/ghost-on-kubernetes](https://github.com/sredevopsorg/ghost-on-kubernetes)

**Comment by tianon** [comment]
cc @acburdine :bow: :heart:

(this is currently blocking updates to the `ghost` Docker image :sob:)

**Comment by ngeorger** [comment]
> cc @acburdine 🙇 ❤️
> 
> (this is currently blocking updates to the `ghost` Docker image 😭)

Hope this helps  (and works 😂) https://github.com/docker-library/ghost/pull/414

**Comment by daniellockyer** [comment]
This is weird 🤔

We haven't been seeing this with our internal builds but I do know we've run into it a few times with local dev. I think yarn is hoisting different versions of string-width up to the root, but I'm not entirely sure why

**Comment by daniellockyer** [comment]
Potentially related to https://github.com/isaacs/jackspeak/issues/5

**Comment by daniellockyer** [comment]
Can people try using Yarn `v1.22.22`? Apparently they fixed the transitive dependencies bug in that: https://github.com/yarnpkg/yarn/releases/tag/v1.22.22

**Comment by daniellockyer** [comment]
In fact, I think I'll just add a `jackspeak` resolution, as that solves it for most people

**Comment by daniellockyer** [comment]
Let's give this a go 🙂 Let me know if it re-occurs

**Comment by LaurentGoderre** [comment]
We need to wait for the release (should have checked the history log before opening the PR)

**Comment by daniellockyer** [comment]
Yep sorry, next release (today)

**Comment by LaurentGoderre** [comment]
JackSpeak resolution was not enough unfortunately https://github.com/docker-library/ghost/actions/runs/9063454953/job/24899459788#step:7:33

**Comment by LaurentGoderre** [comment]
Latest version worked! Thanks all!

**Comment by daniellockyer** [comment]
Glad we could get it fixed! Lockfiles hey 🙄
