### ISSUE TITLE
Site version in API not showing patch

### ISSUE THREAD

**Issue by 7ritn** [TryGhost/Ghost#20066]
### Issue Summary

Hi,
when looking up the version of Ghost through the API, only the major and minor version, but not the patch is reported. For better comparision with released version, it would be nice if the patch could also be included.

### Steps to Reproduce

1. Visit API /ghost/api/admin/site/
2. Look up version
3. Find mismatch between release and displayed version (i.e. 5.82.2 vs 5.82)

### Ghost Version

5.82.2

### Node.js Version

18.20.2

### How did you install Ghost?

Podman (Docker Hub)

### Database type

Other

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by vikaspotluri123** [comment]
I think that's by design, as this endpoint doesn't require authentication. `/ghost/api/admin/config/` endpoint includes the actual version.

Please post any further questions on the forum 🙂

**Comment by 7ritn** [comment]
Well since the PATCH version is non security relevant (there are not many per release), I don't see the need to hide it.
