### ISSUE TITLE
Visitors on iOS prompted to download empty "auth-frame" file

### ISSUE THREAD

**Issue by molly** [TryGhost/Ghost#20091]
### Issue Summary

Visitors to my Ghost blog on iOS have been reporting being prompted to download a file titled "auth-frame" when they scroll to the comments section of an article, which is an empty 0KB file if downloaded. I've been able to reproduce on Safari on iPadOS 17.0.2, and some of the people were reporting the issue on Safari iOS, Firefox iOS, and Safari MacOS.

~Rolling back Ghost from 5.82.3 to 5.79.0 has resolved the issue for now, so it was presumably introduced somewhere in there.~ Now seeing it again on Ghost v5.87.2.

![image0](https://github.com/TryGhost/Ghost/assets/2487900/24589993-eb11-4919-aa8b-162727aa740e)

### Steps to Reproduce

1. Open a recent (v5.82.3) Ghost blog on an iOS device or Safari. I did not check other browsers on iPadOS, and did not check the Ghost versions released between 5.79.1 and 5.82.3, but I did try to reproduce on other browsers on MacOS (recent Chrome/Firefox) and could not.
2. Open any article on the blog.

### Ghost Version

5.82.3, 5.87.2

### Node.js Version

18.17.1

### How did you install Ghost?

Ubuntu 22.04.3 LTS, one-click install on DigitalOcean

### Database type

MySQL 8

### Browser & OS version

iPadOS 17.0.2 (and other iOS)

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by molly** [comment]
Nevermind, I think this has to do with a very specific issue on my end.

**Comment by molly** [comment]
I previously thought this was due to a configuration issue that was resolved when I updated Ghost, but now am seeing this behavior again with the most recent Ghost release.

**Comment by brvnnghi** [comment]
I can confirm this bug, and more specific details on my case:
- happen in post detail with at least 1 comment
- only show "download auth frame" when comment section become visible (scrolled to)
- on Safari iOS (not happen on Chrome or Safari on desktop)
- happened both with signed-out or logged-in member
Attached is a screenshot. I'm on Ghost 5.82.3.
![img 1](https://github.com/user-attachments/assets/e0fe78b0-052c-4d92-973f-f83078d01815)

**Comment by mike182uk** [comment]
Hey @molly @brvnnghi 👋

I have been able to reproduce this in iOS Safari when the HTTP header `X-Content-Type-Options: nosniff` is present on the response for requests to `/ghost/auth-frame`. I'm thinking this is an issue with how iOS Safari is handling `204` responses with this header

This isn't a standard header that gets set by Ghost so I believe it is possibly coming from somewhere higher in the stack (i.e nginx adding additional response headers)

I'm not sure how much control you have over your environment, but you could try tweaking your server configuration to not include this header for this path to prevent this from happening for now

**Comment by molly** [comment]
I've removed it for now, and it does seem to resolve the issue.

I'm using the default nginx configuration from the one-click Ghost install on DigitalOcean, so my guess is this is affecting others with the same. The line that needs to be removed is in `/etc/nginx/snippets/ssl-params.conf`.

**Comment by akalikbergenov** [comment]
@molly Hi! Please tell us how to do this in more detail. I'm not good at programming, but I really want to fix this auth-frame on my blog.

**Comment by molly** [comment]
> @molly Hi! Please tell us how to do this in more detail. I'm not good at programming, but I really want to fix this auth-frame on my blog.

1. Edit `/etc/nginx/snippets/ssl-params.conf` to remove the line containing `X-Content-Type-Options: nosniff`
2. Reload the nginx config: `sudo service nginx reload`

**Comment by sagzy** [comment]
Hey there 👋 

We just released a new version of Ghost CLI, which fixes the issue for new Ghost installs via the 1-click install on Digital Ocean ([change](https://github.com/TryGhost/Ghost-CLI/pull/1858)).

Thank you @molly for the report, and also for providing guidelines on how to adapt existing nginx configurations. Much appreciated!
