### ISSUE TITLE
Ghost language not changing to "fa"

### ISSUE THREAD

**Issue by amirsaam** [TryGhost/Ghost#20214]
### Issue Summary

Hello,

While I have added Persian translation in #19932 , but when I change publication language in the latest version of Ghost installed on my server it doesn't change.

### Steps to Reproduce

1. Install latest Ghost
2. Change publication language to fa
3. Refresh admin or go to the blog
4. Language is still English

### Ghost Version

5.82.8

### Node.js Version

18.20.2

### How did you install Ghost?

Bitnami Docker Image

### Database type

Other

### Browser & OS version

Safari/Firefox - macOS

### Relevant log / error output

```shell
No error log.
```

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by amirsaam** [comment]
Closing based on my #20219 PR.

**Comment by amirsaam** [comment]
while there is a translation and also i added the language code to to the file in my pr, ghost language is not changing at all.
publication language is set to "fa"
and portal translation is also on in the lab tab

**Comment by justinacolmena** [comment]
Obviously this is configurable from within ghost admin, but it does not seem to result in the translations actually being applied.

```
mysql> SELECT settings.value AS language FROM settings WHERE settings.key = 'locale';
+----------+
| language |
+----------+
| es       |
+----------+
1 row in set (0.00 sec)

mysql> _
```

**Comment by justinacolmena** [comment]
Server-side node.js caching issue. Set language and wait.
