### ISSUE TITLE
X profile rewrites X URL as twitter.com/xxxxx

### ISSUE THREAD

**Issue by flavianh** [TryGhost/Ghost#20227]
### Issue Summary

<img width="518" alt="image" src="https://github.com/TryGhost/Ghost/assets/5397842/9332aabc-cdce-42b6-9be0-822af74f2dbe">

When I write x.com/xxxxx, the URL gets rewritten as twitter.com/xxxxx

Also, the logo on the author profile is still the bird logo, not the X logo.

### Steps to Reproduce

1. Go to https://blog.taktique.com/ghost/#/settings/staff/[staffMemberName]
2. Change X URL

### Ghost Version

5.82.8

### Node.js Version

18

### How did you install Ghost?

DigitalOcean

### Database type

MySQL 5.7

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by flavianh** [comment]
?? where did it go? And that's not just an "improvement", the company's logo and main URL has changed

**Comment by vikaspotluri123** [comment]
It was fixed in https://github.com/TryGhost/Ghost/pull/20234 but not linked to this issue because the Ghost team is using Linear (a third-party) for project management

**Comment by flavianh** [comment]
Thanks! I notice that the profile's image has not been modified as part of this PR, was it done someplace else?

**Comment by vikaspotluri123** [comment]
I didn't see a PR but maybe I missed it - @peterzimon can you check?
