### ISSUE TITLE
Rich Preview for Link is not working for all websites

### ISSUE THREAD

**Issue by Ahmad-S792** [TryGhost/Ghost#20240]
### Issue Summary

Hi Team,

I just noticed that the rich preview link (copy paste link and it changes to beautiful container / box) is not working for all websites.

Appreciate if you can help into following.

Thanks!

### Steps to Reproduce

** Steps to Reproduce **

1) Go to ghost.org
2) Login to website
3) Open Post
4) Try to copy paste following: https://www.axs.com/uk

**Expected Result:**

Rich Preview link container

**Actual Result:**

Just link was pasted

**Other Information**

Test Browsers: Safari on iPad, Safari on macOS and Chrome Canary 127 on macOS

**Refererence Screenshot**

It looks like following:

<img width="907" alt="image" src="https://github.com/TryGhost/Ghost/assets/52317531/1d033f63-a148-4965-b9cd-8b9e6fff4d1b">

### Ghost Version

Online ghost.io free account

### Node.js Version

Online ghost.io free account

### How did you install Ghost?

Not Applicable

### Database type

Other

### Browser & OS version

Safari 17.5 on macOS, Safari 17.5 on iPadOS and Chrome Canary 127 on macOS

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by 9larsons** [comment]
I believe `https://www.axs.com/` is blocking requests that aren't coming from a browser. All requests from a node process at least are getting `403` responses. If you'v got other sites that you think are problematic, please open a new issue and we can look in to those.
