### ISSUE TITLE
Discord/Slack Webhook Integration

### ISSUE THREAD

**Issue by fritz-fritz** [TryGhost/Ghost#20304]
### Issue Summary

When using the native Slack integration with a Discord channel with no excerpt defined, the paywall feature is ignored in the snippet posted. This potentially leaks information that may be meant to keep from being public.

Additionally, the post's Author is not listed properly and is attributed to the blog itself.

![image](https://github.com/TryGhost/Ghost/assets/5253894/0d0214f7-3db8-4894-8709-3f498bb84458)
![image](https://github.com/TryGhost/Ghost/assets/5253894/f56c9b8a-52e6-4f20-a206-589d63d96fa6)

### Steps to Reproduce

1. Write a post with a paywall but without an excerpt.
2. Add the Slack integration to Discord by appending `/slack` to the end of the url and adding to Discord.
3. Publish the post.

### Ghost Version

5.82.8

### Node.js Version

18.19.1

### How did you install Ghost?

Digital Ocean droplet Ubuntu 24.04

### Database type

SQLite3

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by fritz-fritz** [comment]
It seems to be taking the first 3 sentences of the post for the excerpt regardless if it is supposed to be behind a paywall based on my testing. Ideally it would stop if it hits a paywall.

**Comment by mike182uk** [comment]
Hey @fritz-fritz 

This has been fixed in https://github.com/TryGhost/Ghost/pull/20328 and should go out in the next release

Thanks for reporting 🙌
