### ISSUE TITLE
Language does not apply (FA/Persian)

### ISSUE THREAD

**Issue by amirsaam** [TryGhost/Ghost#20300]
### Issue Summary

While I've added translations for Persian (#19932) and added its code to supported languages (#20219) but still it doesn't apply the language to Ghost website.

### Steps to Reproduce

1. Login to Ghost Admin
2. Change Publication language to "fa"
3. Go to website and reload
4. Language didn't applied

### Ghost Version

5.82.12

### Node.js Version

18.20.2

### How did you install Ghost?

Bitnami Docker Image

### Database type

Other

### Browser & OS version

Safari/Firefox - macOS 14.5

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by amirsaam** [comment]
I've also tested on 5.83.0, the issue is still there.

**Comment by mike182uk** [comment]
Hey @amirsaam 👋

Have you enabled `Portal Translation` in the settings? (see [here](https://ghost.org/docs/faq/translation/#ui-translations))

You can read a bit more on how translations work in Ghost [here](https://ghost.org/docs/faq/translation/)

**Comment by amirsaam** [comment]
@mike182uk hello there, yes i do have that enabled. and have read that article too. the issue is if i change language to fr or es they will get translated but not fa

**Comment by mike182uk** [comment]
🤔 Hmm, are seeing translations anywhere? 

When running locally (`yarn dev --portal`) I'm seeing the `fa` translated text

![CleanShot 2024-06-04 at 17 02 34@2x](https://github.com/TryGhost/Ghost/assets/991592/e2f26616-8b80-4163-9838-193929820a42)

![CleanShot 2024-06-04 at 17 04 55@2x](https://github.com/TryGhost/Ghost/assets/991592/1d229a32-fa7b-40f2-b24a-209a95adc074)

![CleanShot 2024-06-04 at 17 00 35@2x](https://github.com/TryGhost/Ghost/assets/991592/f8359f0d-f935-4487-a2a2-cc7e47aecbb0)

**Comment by amirsaam** [comment]
@mike182uk Unfortunately it does not work for me.
My Ghost is self-hosted, do I need to do the command you mentioned to make it work?
<img width="652" alt="Screenshot 1403-03-15 at 22 18 20" src="https://github.com/TryGhost/Ghost/assets/1331289/fbee95de-c49a-45a3-9f1c-3a22eaa9e4cb">
<img width="652" alt="Screenshot 1403-03-15 at 22 18 43" src="https://github.com/TryGhost/Ghost/assets/1331289/1d8cece7-f8a8-49a6-8225-1fa1ddb835f2">
<img width="547" alt="Screenshot 1403-03-15 at 22 18 56" src="https://github.com/TryGhost/Ghost/assets/1331289/f391f8bc-4951-417d-bc24-07deb6c7a7c9">

<img width="482" alt="Screenshot 1403-03-15 at 22 19 27" src="https://github.com/TryGhost/Ghost/assets/1331289/cb00bb43-326f-4bbe-b3e2-9a1fd2279808">

**Comment by amirsaam** [comment]
```bash
I have no name!@e1e91f16a8b6:/opt/bitnami/ghost$ yarn dev --portal
yarn run v1.22.22
warning Skipping preferred cache folder "/.cache/yarn" because it is not writable.
warning Selected the next writable cache folder in the list, will be "/tmp/.yarn-cache-1001".
error Couldn't find a package.json file in "/opt/bitnami/ghost"
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by mike182uk** [comment]
I've just published a new version of portal ([2.37.8](https://cdn.jsdelivr.net/ghost/portal@~2.37/umd/portal.min.js)) which should include the translations you added 🎉 (You may need to clear your browser cache to pull in the latest version)

**Comment by amirsaam** [comment]
@mike182uk Thanks buddy! But a funny thing, only the login and signup forms are now show translation! not the comment section.

**Comment by amirsaam** [comment]
A side effect question. I am trying to apply a Persian font to all of the website using code injection, but the comment section + portal signin and signup forms do not accept it, is this behaviour intended?
If yes can we add an option to the portal to accept Google Fonts as a override option?

**Comment by mike182uk** [comment]
My bad I also needed to release the comments-ui as well. That should be done now  (You may need to clear your browser cache to pull in the latest version)

As for your other question, you would be best reviewing our [documentation](https://ghost.org/docs/) or asking on our [forum](https://forum.ghost.org/c/help/6) as we use GitHub solely for bug-tracking and community-driven development 👍

**Comment by amirsaam** [comment]
@mike182uk thanks for your efforts! translation now works correctly.

about the other thing, it was actually a feature request.
