### ISSUE TITLE
Editor Description for Tag Code Injection is Ambiguous

### ISSUE THREAD

**Issue by alexma418** [TryGhost/Ghost#20342]
### Issue Summary

Ghost isn't rendering Code Injection snippets specified in Tag Header/Footer on posts/pages the tag is applied to.

### Steps to Reproduce

1. Spin up a `ghost:5.83.0` Docker container
2. Initialize the basic site data at `/ghost/`
3. Install a theme (Tested against Casper, Dawn, and Edition)
4. Assume that the "Coming soon" post is pre-populated with the "News" tag
5. Edit the "News" tag > Code injection
    a. Post header: `<style>.spoon{color:#FFF;}</style>`
    b.	Post footer: `<div class="spoon"></div>`
    c. Save
7. Inspect the source code for `/coming-soon/`
8. Eat a pint of ice cream to soothe away your tears. Except you can't, because there is no `spoon`

### Ghost Version

5.83.0

### Node.js Version

18.20.3

### How did you install Ghost?

Docker

### Database type

MySQL 8

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by kevinansfield** [comment]
Tag code injections are inserted on the respective tag page, not onto posts that have that tag attached.

If you need tag-specific changes on a post you'd need to do that manually in your theme.

**Comment by kevinansfield** [comment]
I've raised the issue with our Product/Design teams for consideration in future iterations and we'll continue monitoring feedback and support channels for other instances where there's confusion over tag settings behaviour. Thank you for raising.
