### ISSUE TITLE
Editor formatting broken

### ISSUE THREAD

**Issue by yohanderose** [TryGhost/Ghost#20391]
### Issue Summary

Hi team, I recently tried the beta editor on docker image version 5, and all the text in the editor was bold, italicised and unchangeable.
![image](https://github.com/TryGhost/Ghost/assets/38681260/c6965b22-c430-4c2a-a354-6106ec048d39)

### Steps to Reproduce

1. Try the version 5 beta editor.
2. Revert to the regular editor.
3. Pull the latest docker image and rebuild

### Ghost Version

5.85.0

### Node.js Version

18.14.2

### How did you install Ghost?

Docker on ubuntu server

### Database type

SQLite3

### Browser & OS version

Editors botched formatting on both recent chrome and firefox installs

### Relevant log / error output

```shell
None
```

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by kevinansfield** [comment]
@yohanderose I'm a bit confused as to what versions etc you're using here. Ghost hasn't had a "beta" editor since 5.68.0 released Oct 6th 2023 in which the old editor and beta switch was removed entirely.

Are you saying you have content that you created/edited in the beta editor that is now broken in the latest release? (Note that once you edited a post in the beta editor it wasn't possible to revert it to the old editor, even after disabling the beta switch).

**Comment by yohanderose** [comment]
@kevinansfield, thanks for replying. I didn't actually edit anything in the beta editor; I just wanted to check out the feature.

I was self-hosting an old docker image on a VPS, and even once I upgraded to the latest, the weird formatting persisted, and applying any bold or italics isn't working.
![Peek 2024-06-18 21-32](https://github.com/TryGhost/Ghost/assets/38681260/bbeb1d85-70c1-41e5-bc3d-1526b41a64ff)

**Comment by kevinansfield** [comment]
Is this occurring on every post or just with specific content?

**Comment by yohanderose** [comment]
Every post it looks like

**Comment by kevinansfield** [comment]
In that case it sounds like there's something in your browser that may be interfering with the editor. When you preview or view the published post is the content there italicised?

**Comment by yohanderose** [comment]
Hmm, that's weird. I've tried Firefox and Chrome, and they have the same issue. The previews and live posts look [fine](https://yohanderose.dev/nabunote-devlog-1/)

**Comment by kevinansfield** [comment]
Can you use the browser's dev tools to inspect some of the italicised text and post a screenshot of the elements tab?

**Comment by ngeorger** [comment]
Just a reccomendation: When you upograde any software, even more if it's important for you, try to do it stepby step,minor version by minor version until you get to the latest or desired one.

Example:

If you are un 4.0.0, don't jump directly into 5.xx.x, do it at least with a couple of versions in between, like 4.0 -> to 4.5 -> 4.9 -> 5.0

This way you'll ensure the lowest chances of breaking changes when upgrading.

**Comment by ngeorger** [comment]
BTW, you could try to export and import your content. There is a chance that migrations or database upgrades did something weird at some point.
BTW, do it into a dev environment, not directly into your main server.

**Comment by cmraible** [comment]
Hey @yohanderose  👋 

Our team needed some more info to get to the bottom of this, however we've not heard back from you. We're going to close this for now, but let us know if you manage to dig up some more info and we'll reopen.
