### ISSUE TITLE
I am getting TypeError: invalid 'instanceof' operand KeyObject error while adding member using Ghost Admin API

### ISSUE THREAD

**Issue by developervijay7** [TryGhost/Ghost#20409]
### Issue Summary

I am getting TypeError: invalid 'instanceof' operand KeyObject error while adding member using Ghost Admin API

### Steps to Reproduce

export async function addMember(email) {
    return await admin.members.add({"members":[{"email": email}]}, {send_email: true, email_type: 'subscribe'})
        .then(response => console.log(response))
        .catch(error => console.error(error))
}

### Ghost Version

5.84.1

### Node.js Version

18

### How did you install Ghost?

Local

### Database type

MySQL 8

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by kevinansfield** [comment]
It sounds like this may be related to jsonwebtoken usage based on this upstream issue https://github.com/auth0/node-jsonwebtoken/issues/950

However the version in question was updated in our Admin-API package over a year ago and we haven't had any other reports of issues. @developervijay7 your issue doesn't provide any details on the environment you're using the Admin-API package in or how you're instantiating it etc so it's difficult to reproduce or help.

As this sounds environment related please open a support topic on [our forum](https://forum.ghost.org). If there's a reproducible bug found after investigating then we can re-open an actionable issue. Thanks.
