### ISSUE TITLE
Single Export JSON File does not support custom images

### ISSUE THREAD

**Issue by vednig** [TryGhost/Ghost#20482]
### Issue Summary

When transferring data from one instance of ghost installation to another, with Single export JSON file images are not rendered when importing on new instance is complete

### Steps to Reproduce

1.Upload Custom Images to Post in Ghost Installation
2. Export JSON data
3. In new installation import JSON and view broken image.

### Ghost Version

5

### Node.js Version

-

### How did you install Ghost?

docker armv7 ubuntu

### Database type

MySQL 8

### Browser & OS version

any

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by betschki** [comment]
That is indeed expected behaviour in how the export is currently implemented in Ghost. Images always need to be exported separately: https://ghost.org/docs/migration/ghost/#images

If you want to migrate from Ghost to Ghost this tool might help: https://github.com/TryGhost/migrate

**Comment by vednig** [comment]
I believe a possible feature could be to implement conversion of image to base64 format and embed in JSON value. This would simply streamline the process of migration. Making sure no additional steps are required.

**Comment by vednig** [comment]
Because the idea of single glorious JSON fails when images crash. Also several services like Ghost (Pro) and digitalpress.blog do not provide ssh access in their services.

**Comment by betschki** [comment]
The idea of a managed hosting solution is that things are well…managed. SSH access always means that this "management" can be interfered with, potentially creating huge issues for the management processes of the hoster.
If you need access to the images, every Ghost hoster I know, will send you a zipped backup upon request.

Independent of that, I also believe that a full export function in Ghost would be great, though I am personally not sold on putting the images into the JSON itself. The .zip structure created by the [migrate](https://github.com/TryGhost/migrate) project makes a lot more sense, in my eyes.

**Comment by vednig** [comment]
If not to export post data, what is the purpose of export function in Ghost Admin ?

**Comment by betschki** [comment]
Sorry if I wasn't clear: I believe that tue export function _should_ include the images, though I would prefer a .zip file with all images as files in a dedicated folder, rather than a huge JSON.

**Comment by vednig** [comment]
Yeah, that makes sense. I still can't figure it out , product design wise, what function does two different methods of exporting data in different formats server ?
I mean, if there is complete tool for migration why not converge both in Ghost Admin Panel?
