### ISSUE TITLE
The problem with the background color for the bookmark card

### ISSUE THREAD

**Issue by fueko** [TryGhost/Ghost#20552]
### Issue Summary

Hi!

Probably in the last update, a 'background' color (`#fff`) was assigned to the bookmark card, causing issues for themes that use dark mode. Is there a specific reason for this change? 

Because of this change, all themes now need to go through an update process, which is always quite challenging for theme users, especially due to such a minor change. Therefore, is it possible to revert to the previous setting where the bookmark card did not have an assigned background color?

![Zrzut ekranu 2024-07-7 o 17 00 24](https://github.com/TryGhost/Ghost/assets/23366922/ceeca57c-af6c-4ede-92b0-15092c514359)

![Zrzut ekranu 2024-07-7 o 16 53 27](https://github.com/TryGhost/Ghost/assets/23366922/85b0585e-1599-44e8-b7b0-ec0ed767a9c6)

### Steps to Reproduce

Check the color assigned to the 'a.kg-bookmark-container' class using the browser console.

### Ghost Version

5.87.1

### Node.js Version

v18.12.1

### How did you install Ghost?

localhost

### Database type

SQLite3

### Browser & OS version

All

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by 9larsons** [comment]
Thanks for the report! Closed w/ a few commits for various themes:
https://github.com/TryGhost/Ghost/pull/20578
https://github.com/TryGhost/Source/commit/457397b4f17dd9eae2ec154667916d252b07527c
https://github.com/TryGhost/Casper/commit/6d8cc3ae664e149d41c0c35ac16d4126bcf376dd
https://github.com/TryGhost/Themes/commit/e8dd0f641964f2b7080f20fc58da69de19b77fce

**Comment by fueko** [comment]
Hi @9larsons! If I understand correctly, the background color will remain white, right? In my submission, I didn’t mean that there was an issue with the text color, but rather that the card should not have a white background as it did before. 

Could you please confirm this? I need to know if I must update all themes to have a dark background color. Also, will all other cards like 'product', 'audio', and 'file' now have a fixed white background color as well?

**Comment by minimaluminium** [comment]
Hi @fueko,

Yes, the background color will remain white. On top of the bookmark, we will also do the same for product, audio, and file cards to keep their "embedded" look consistently.

The change will take place on 23 Aug, and we sent email to theme developers last week regarding this.
