### ISSUE TITLE
Request not understood error, cannot read post. Could not understand request.

### ISSUE THREAD

**Issue by Coding-Kiwi** [TryGhost/Ghost#20596]
### Issue Summary

I cannot click on a recent post in the admin dashboard

the link href is "#/posts/analytics/668866d8b977900001b0e561"

when I click, the request made in the network tab is https://my.domain/ghost/api/admin/posts/668866d8b977900001b0e561/?formats=mobiledoc%2Clexical&include=tags%2Cauthors%2Cauthors.roles%2Cemail%2Ctiers%2Cnewsletter%2Ccount.conversions%2Ccount.clicks%2Csentiment%2Ccount.positive_feedback%2Ccount.negative_feedback

![image](https://github.com/TryGhost/Ghost/assets/5007641/511bc4f5-e59c-46fb-97a6-a4977bd22ecf)

### Steps to Reproduce

1. Go to dashboard an click on a post in the "Recent posts" list
2. Error page 404 and a red error bar on the top

### Ghost Version

5.87.0

### Node.js Version

18 I guess? I use the docker image

### How did you install Ghost?

docker container

### Database type

Other

### Browser & OS version

Brave 1.67.123 Chromium: 126.0.6478.126 Windows 11 (64-Bit)

### Relevant log / error output

```shell
Request not understood error, cannot read post. Could not understand request.

{
    "errors": [
        {
            "message": "Request not understood error, cannot read post.",
            "context": "Could not understand request.",
            "type": "BadRequestError",
            "details": null,
            "property": null,
            "help": null,
            "code": "ER_BAD_FIELD_ERROR",
            "id": "0c220b90-3fab-11ef-9091-5f9a268e6b82",
            "ghostErrorCode": null
        }
    ]
}
```

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by 9larsons** [comment]
@Coding-Kiwi Thanks for the report. Can you confirm that the post exists? Can you click on it and enter the editor? 

yourdomain.../ghost/#/editor/post/668866d8b977900001b0e561

**Comment by Coding-Kiwi** [comment]
> @Coding-Kiwi Thanks for the report. Can you confirm that the post exists? Can you click on it and enter the editor?
> 
> yourdomain.../ghost/#/editor/post/668866d8b977900001b0e561
> 
> This error suggests that the ID doesn't actually exist.

hi, yes if I enter the url manually https://my.domain/ghost/#/editor/post/668866d8b977900001b0e561 it works, or if I virst visit the posts page and then click on it in that list

**Comment by Coding-Kiwi** [comment]
> @Coding-Kiwi Thanks for the report. Can you confirm that the post exists? Can you click on it and enter the editor?
> 
> yourdomain.../ghost/#/editor/post/668866d8b977900001b0e561
> 
> This error suggests that the ID doesn't actually exist.

make sure to check the first comment I added, it suggests that there is an error in the SQL or more likely my database is somehow outdated but ghost does not migrate it

**Comment by Coding-Kiwi** [comment]
> The docker container will auto-run migrations when restarting Ghost. It seems likelier that this was interrupted. I cannot reproduce anything on my end, either in Ghost or within MySQL, even if I run the same query with a nonexistent post.
> 
> I would suggest trying to restore from a backup and see if that resolves the issue for this post. You can monitor the docker logs to see when the migrations and running and finish.

The problem seems to be my database, it is mariadb which is unsupported by ghost. Should have noticed the big red warning 

![image](https://github.com/TryGhost/Ghost/assets/5007641/315dbb1e-eced-4b3e-bb51-90281b1eb2fa)

The query

```sql
select posts.*, (
        with k as (
            select member_id from members_subscription_created_events where posts.id = members_subscription_created_events.attribution_id
            union select member_id from members_created_events where posts.id = members_created_events.attribution_id
        )
        select count(*) from k
    ) as count__conversions
    from posts where (
        posts.type = 'post'
        and posts.status in ('draft', 'published', 'scheduled', 'sent')
    )
    and posts.id = '668866d8b977900001b0e561'
    limit 1
```

does not work because `posts.id` seems to be undefined in the `with k as(` part

MariaDB handles common table expressions (CTEs) differently than MySQL.
I spinned up a plain mysql docker container, exported and imported the database and the query works, so we can close this I guess?

**Comment by Coding-Kiwi** [comment]
Relevant upgrade guide in the docs https://forum.ghost.org/t/how-to-migrate-from-mariadb-10-to-mysql-8/29575

**Comment by 9larsons** [comment]
Yep that's your best bet. Glad it's working for you now - surprised there wasn't more that wasn't working.
