### ISSUE TITLE
Dark Mode - Post editor - URL display is not readable

### ISSUE THREAD

**Issue by brandishwar** [TryGhost/Ghost#20595]
### Issue Summary

When the admin panel is set to dark mode, the URL viewer for a link presents as black text on a dark grey background. This is barely readable. It should, instead, be white text like after clicking the "edit" button .

![image](https://github.com/TryGhost/Ghost/assets/19864930/1d27d321-7b0b-4a99-97b4-ed01bef48682)

### Steps to Reproduce

1. Log into admin panel
2. Open a post with a link within any paragraph
3. Hover mouse over link

### Ghost Version

5.87

### Node.js Version

18.20.3

### How did you install Ghost?

Ubuntu 22.04, manual installation

### Database type

MySQL 8

### Browser & OS version

Brave 1.67.123 (Chromium: 126.0.6478.126) on Windows 11

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by PARVNEMA** [comment]
Can anyone assign me this issue

**Comment by brandishwar** [comment]
So this has been closed as completed, but there isn't a commit linked to this. And I'm not seeing this resolved in the latest release - 5.87.3. Can this be re-opened, as it seems like it got closed in error?
