### ISSUE TITLE
Documentation - WP Migrations

### ISSUE THREAD

**Issue by moates** [TryGhost/Ghost#20658]
### Issue Summary

Instructions are slightly out of date for migrations from Wordpress.

https://ghost.org/docs/migration/wordpress/

# Current content:
![image](https://github.com/user-attachments/assets/2e33162a-a950-486b-bfe5-73c5b75842f1)

# Suggested content:

## Importing your content to Ghost
After the download is complete you’ll be left with a zip file containing your data and images. The JSON data file can also be used in these steps. Images will need to be uploaded alongside a JSON data file in a zip file.

![image](https://github.com/user-attachments/assets/e9b18d52-af1c-4722-a7b7-5ba0b320a8ae)

Log into Ghost admin and navigate to **Import/Export** view. Click the **Universal import** file button and select your exported json or zip file, then click Import. All your content will then be imported into your Ghost site 🎉

### Steps to Reproduce

na

### Ghost Version

5.87.0

### Node.js Version

na

### How did you install Ghost?

ghost pro

### Database type

Other

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by PaulAdamDavis** [comment]
Hey @moates, thanks for raising this! The documentation has been updated.
