### ISSUE TITLE
Opening the recommendation popup only works with enabled subscription

### ISSUE THREAD

**Issue by SteffoSpieler** [TryGhost/Ghost#20771]
### Issue Summary

Trying to open the recommendation pop up (https://example.org/#/portal/recommendations) - e.g. through the URL, or through the "View all" button on the homepage - doesn't do anything when `Subscription access` is disabled / set to "nobody".

### Steps to Reproduce

1. Set the Subscription access to `Nobody` (https://example.org/ghost/#/settings/members)
2. Enable the `publication info sidebar` at https://example.org/ghost/#/settings/design/edit - in the Tab Homepage.
3. Recommend a site (https://example.org/ghost/#/settings/recommendations)
4. See the recommendation panel. (https://example.org)
5. Try to click on "View all".

### Ghost Version

5.89.1

### Node.js Version

v18.20.4

### How did you install Ghost?

Via Docker Compose

### Database type

MySQL 8

### Browser & OS version

Firefox 129.0.1 (64-Bit) on Windows 11 Pro

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by allouis** [comment]
I'm not able to replicate the issue with these instructions, is this with a fresh install of Ghost? If you could share reproduction steps using the latest version of Ghost & the Ghost CLI, that would be really helpful! 

I also noticed that you're installing with Docker Compose - which is not an officially supported install method, it's unlikely to be the cause, but to rule it out, could you try replicating with the recommended installation methods instead?

**Comment by allouis** [comment]
Thanks! I will look into this further!

**Comment by cathysarisky** [comment]
I'm able to confirm the behavior also, on 5.96.0.

**Comment by SteffoSpieler** [comment]
@cathysarisky As you can see in my demonstration above, I have recommendations.

**Comment by cathysarisky** [comment]
It's a little hard to tell - are you reloading the page after setting the recommendation?

**Comment by SteffoSpieler** [comment]
Yes, I am. If not, then the recommendations wouldn't show in the sidebar as well.
If you need a live example, I could send my blog here, as there I have membership disabled, but I have recommendations set - and the popup doesn't open. (Don't want to accidentally advertise if that's not allowed / not needed anyway.)

**Comment by cathysarisky** [comment]
Let me see if I can repro this again.  I found one error in the routing for recommendations, but I'm not sure I fully reproduced this case.

**Comment by SteffoSpieler** [comment]
I just replicated with a fresh local installation of ghost, like it's explained in the README of this repository (`ghost install local`). Here you can see the full replication: 

https://github.com/user-attachments/assets/40a6c2e5-97f5-4318-b527-831fcbdc0d7b

You can also test this setup on my blog - https://steffo.blog - it's the same settings. The only difference is that I use the (not official) docker image to host this - but this shouldn't be an issue, as it's the same ghost technically, I think. (Also, I can still reproduce it locally.)

**Comment by cathysarisky** [comment]
Ah. Interesting.  Your site doesn't appear to be loading the portal script, which does all the membership functionality AND recommendations. 

Looks like the bug is here:
```
    if (!settingsCache.get('members_enabled') && !settingsCache.get('donations_enabled')) {

```
(ghost_head.js, line 49).  That's preventing the portal script from loading recommendations.

Thanks for your patience on sorting out the repro.  I now see that the portal script is completely failing to load, which is why that button is not doing anything.  Will patch!
