### ISSUE TITLE
Problem after update 5.90.2 

### ISSUE THREAD

**Issue by LordRall** [TryGhost/Ghost#20847]
### Issue Summary

INFO Adding table: suppressions
[2024-08-28 09:45:39] ERROR alter table suppressions add constraint suppressions_email_id_foreign foreign key (email_id) references emails (id) - Referencing column ‘email_id’ and referenced column ‘id’ in foreign key constraint ‘suppressions_email_id_foreign’ are incompatible.

alter table suppressions add constraint suppressions_email_id_foreign foreign key (email_id) references emails (id) - Referencing column ‘email_id’ and referenced column ‘id’ in foreign key constraint ‘suppressions_email_id_foreign’ are incompatible.

### Steps to Reproduce

5.25.0 to update 5.90.2 

### Ghost Version

5.90.2

### Node.js Version

18.17.0

### How did you install Ghost?

update

### Database type

MySQL 8

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by allouis** [comment]
I'm having trouble replicating this error - could you share how you installed Ghost, as well as how you're updating Ghost?
