### ISSUE TITLE
spam

### ISSUE THREAD

**Issue by aigan** [TryGhost/Ghost#20861]
### Issue Summary

Critical security update available — please update Ghost as soon as possible. [Details here.](https://github.com/TryGhost/Ghost/security/advisories/GHSA-78x2-cwp9-5j42)

### Steps to Reproduce

opened my email.
Second time I got this. Plus other reminders.
Did not find the unsubscribe link in the email.

### Ghost Version

5.51.0

### Node.js Version

18

### How did you install Ghost?

cli

### Database type

Other

### Browser & OS version

Debian

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by allouis** [comment]
Please contact the sender of the email
