### ISSUE TITLE
Markdown issues with new lines.

### ISSUE THREAD

**Issue by Borkason** [TryGhost/Ghost#2093]
Line breaks are not always working. It's hard to describe what is happening, therefore I made a gif. I would expect the formatted (right) being the same as the input (left).

![markdown](https://f.cloud.github.com/assets/2971735/2058040/302747fa-8b5a-11e3-8a5b-fffecc97876c.gif)

I narrowed it down and changed a regular expression. I thought I got it working until I did a `grunt validate`. It starts failing at https://github.com/TryGhost/Ghost/blob/master/core/test/unit/client_showdown_int_spec.js. This is rather strange because if I [reconstruct that output manually in JSfiddle](http://jsfiddle.net/F4ZJP/23/), it perfectly matches the provided regular expression.

Take https://github.com/TryGhost/Ghost/blob/master/core/test/unit/client_showdown_int_spec.js#L75 for example. It fails with

```
6) Showdown client side converter should not treat pre blocks with pre-text differently:
   AssertionError: expected '<pre>\nthis is `a\\_test` and this\\_too and finally_this_is\n</pre>  ' to match /^<pre>\nthis is `a\\_test` and this\\_too and finally_this_is\n<\/pre>$/
```

Putting said input line that in my [modified JSFiddle](http://jsfiddle.net/43cNX/1/), the output of _Haunted Markdown_ and _Fixed Haunted Markdown_ is exactly the same. Also the [regular expression}(http://regex101.com/r/yP1gS7) matches.

I hope I didn't write this too complicated.

**Comment by ErisDS** [comment]
Reopening this as I think that it should be fixed by #5167, when I finish that off.
