### ISSUE TITLE
tips : edit link issue with uBlock Origin

### ISSUE THREAD

**Issue by mqu** [TryGhost/Ghost#21007]
### Issue Summary

- unable to edit link (internal and external) when editing page (https://ghost.org/help/using-the-editor/)

### Steps to Reproduce

1 - install Ghost,
2 - go to editing page,
3 - try to add a link to page.
4 - disable uBlock Origin
5 - try again to edit Link -> every thing is fine.

### Ghost Version

5.94.1

### Node.js Version

-

### How did you install Ghost?

docker

### Database type

MySQL 8

### Relevant log / error output

```shell
after having disabled uBlockOrigin, link editing is fine.
```

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by mqu** [comment]
ublockOrgin disabled, still having this issue ; when I select text, open menu, select "link" option, selection disappears.

**Comment by mqu** [comment]
Hello ; I have desactivated many of Firefox extensions without success. I will try to record a video.

I have an old Ghost installation for a blog ; I do not have this issue in this old version : 
```
56afa1f19d11:/var/lib/ghost# env | grep GHOST_VERSION
GHOST_VERSION=5.82.11
```

**Comment by mqu** [comment]
Here is my first screencast : https://www.swisstransfer.com/d/cc059268-07c2-4abe-8cfb-717c58395e14

**Comment by sagzy** [comment]
Thanks! And what extension is creating these blue checkmark / red errors? (See attached) <br><br>If you disable that extension, do you still run into that issue?

<img src="https://uploads.linear.app/9cdebf7c-d404-45ab-9ad6-b747e573c868/5a8a4e1c-5f04-44b9-b1de-91fd814150da/d8861cac-09db-4bb8-842c-eb97dfb67a40?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzljZGViZjdjLWQ0MDQtNDVhYi05YWQ2LWI3NDdlNTczYzg2OC81YThhNGUxYy01ZjA0LTQ0YjktYjFkZS05MWZkODE0MTUwZGEvZDg4NjFjYWMtMDlkYi00YmI4LTg0MmMtZWI5N2RmYjY3YTQwIiwiaWF0IjoxNzI2NTAwNzg3LCJleHAiOjMzMjk3MDYwNzg3fQ.3H66GuwxW6dz9-epxdXIr5xcYYFXdgpR6hqABGzNUwU " alt="CleanShot 2024-09-16 at 17.32.52@2x.png" width="204" height="876" />

**Comment by mqu** [comment]
new screencast with "no add-ons" Firefox instance (firefox -P "new profile") : https://www.swisstransfer.com/d/295b4e74-0d4c-4d81-9861-e0eb2073dbd8

**Comment by sagzy** [comment]
Thanks for the additional screencast!<br><br>I haven't been able to reproduce the bug by repeating the same steps with Ghost 5.94.1, on Firefox 130.0.1.<br><br>Is your browser up to date with the latest version available?

**Comment by sagzy** [comment]
@mqu 👋 

Given that we have not been able to find a clear reproduction of the bug and that it seems environment-specific, we suggest that you open a thread on the [Ghost forum](https://forum.ghost.org) to get more help, if you're still experiencing the issue.

**Comment by mqu** [comment]
Hello ; I am now using Firefox 128.3 on Debian Bookworm, manualy installed, without packages. I am not facing any more this issues.

Many thanks for your support !
