### ISSUE TITLE
Incorrect handling of German umlauts in permalink generation

### ISSUE THREAD

**Issue by noezdev** [TryGhost/Ghost#21006]
### Issue Summary

When creating a permalink for a post title containing German umlauts (ä, ö, ü), Ghost incorrectly translates these characters. Instead of using the proper transliteration (ä=ae, ö=oe, ü=ue), it simply removes the umlaut, resulting in incorrect permalinks. 

Expected Behavior
The permalink should be generated as:
"dies-wuerde-ein-test-sein-koennen"

Actual Behavior
The permalink is incorrectly generated as:
"dies-wurde-ein-test-sein-konnen"

Additional Information
This issue affects the readability and SEO of German-language content. The correct transliteration of umlauts is important for maintaining the meaning and searchability of the content.

### Steps to Reproduce

1. Create a new post in Ghost
2. Set the post title to "Dies würde ein Test sein können"
3. Observe the automatically generated permalink

### Ghost Version

5.94.0

### Node.js Version

20

### How did you install Ghost?

Selfhosted

### Database type

MySQL 5.7

### Browser & OS version

Firefox 130

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by sagzy** [comment]
Hey noezdev, thanks for raising the issue! 🙂 <br><br>The letters `ä, ö, ü` are not translated automatically to the German-equivalent `ae, oe, ue` as this would be incorrect for other languages that also make use of the same letters (e.g. Swedish, Finnish, Estonian, Turkish).<br><br>Instead, we recommend choosing the right permalink for your post by updating the permalink in the Post Settings directly (cf. demo attached).

[CleanShot 2024-09-16 at 17.55.42-converted.mp4](https://uploads.linear.app/9cdebf7c-d404-45ab-9ad6-b747e573c868/f490e631-5581-4793-8865-dce0ca20bad5/e304d4fa-7e09-407a-8923-0a6a602ed0b2?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzljZGViZjdjLWQ0MDQtNDVhYi05YWQ2LWI3NDdlNTczYzg2OC9mNDkwZTYzMS01NTgxLTQ3OTMtODg2NS1kY2UwY2EyMGJhZDUvZTMwNGQ0ZmEtN2UwOS00MDdhLTg5MjMtMGE2YTYwMmVkMGIyIiwiaWF0IjoxNzI2NTAyOTA0LCJleHAiOjMzMjk3MDYyOTA0fQ.ZQOKda6xRiQzqPT3Mo2FqWSEi1vcU3lAuaC7zxQ9tCY)

<br>Hope this helps. 🙂

**Comment by noezdev** [comment]
Thank you for your response to my issue. I understand your point that converting special characters in the URL can be a challenge. Interestingly, this used to be the case with WordPress, but was later changed. There are a few possible solutions:

* You could consider the set language of the page and adjust the conversion based on that. This way, the German rules would apply to German content.
* Alternatively, you could create a conversion table that defines how certain special characters are converted into URLs. This would enable consistent handling across languages.

Another point is that the conversion from “Ä” to “a” is also not optimal for all languages. In Swedish, for example, “ae” would be the preferred variant, not “a”. It would be great if Ghost could find a more flexible solution here that takes different languages and their particularities into account. Let me know if you have any further questions or ideas!
