### ISSUE TITLE
Footnotes covered up on iPad/Safari

### ISSUE THREAD

**Issue by elysdir** [TryGhost/Ghost#21016]
### Issue Summary

When I view this [article](https://www.lifeisasacredtext.com/colonialism/) in Safari on iPad, the footnotes get covered up by various bottom-of-page things.

### Steps to Reproduce

1. On iPad, in Safari, visit https://www.lifeisasacredtext.com/colonialism/
2. Tap a small grey ellipse to view a footnote.
—>The footnote appears at the bottom of the screen, but it’s mostly covered up by the “Listen to this article” bar, which is in turn mostly covered up by the social-media-sharing bar, which is in turn partly covered up by the Subscribe button.

I don’t know whether the author of the post could turn off some of the bottom-of-screen items to improve this reading experience, but even if they can, I feel like it would be good if Ghost prevented this from happening.

### Ghost Version

Unknown

### Node.js Version

Unknown

### How did you install Ghost?

Didn't install, I'm just reading.

### Database type

MySQL 5.7

### Browser & OS version

Safari under iPadOS 17.6.1

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by vikaspotluri123** [comment]
It looks like the site author intentionally hid the footnotes at the bottom of the page - at the bottom of the page, they have the following style (snippet)

```html
<style>
/* ... */@media not print{.littlefoot--print{display:none}}/* ...*
</style>
```

This translates to "only show the footnotes [at the bottom of the page] when the page is being printed"

Disabling the style in the developer tools reveals the footnotes. If I click the "go back" anchor for one of the footnotes, there's a grey box inline that shows a tooltip with the footnote:

![image](https://github.com/user-attachments/assets/44dfe321-c1a8-4f57-ac4d-d4250c07578a)

The author might want to add this CSS to hide the footnotes header:

```html
<style>@media not print{#footnotes{display:none}}</style>
```
