### ISSUE TITLE
Gallery images disappear, even though they're still there in the backend

### ISSUE THREAD

**Issue by petruut** [TryGhost/Ghost#21034]
### Issue Summary

![image](https://github.com/user-attachments/assets/f6f7081a-623e-4afa-afa8-1127bb814b00)

The website itself also omits them entirely. These were added just fine, displayed just fine, and are available just fine in the backend folder structure as expected.

### Steps to Reproduce

1. Add gallery + images successfully
2. Images eventually disappear (their placeholder remains, and the images are available in the back end, but the gallery does not display them anymore)

### Ghost Version

latest

### Node.js Version

?

### How did you install Ghost?

docker

### Database type

Other

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by sagzy** [comment]
Hey petruut, thanks for creating the issue.<br><br>I have just tried repeating the same steps on the latest Ghost version, and I haven't been able to reproduce the bug.<br><br>Could you provide a video recording of the bug you're experiencing? Any other information that could help us reproduce it?

**Comment by petruut** [comment]
thanks for the quick reply - is there any way for me to look at the code in the gallery/ logs on galleries already with this issue on the website?

(also, is there a way to relink images already in the /content folder on ghost, without always re-reuploading new copies?)

**Comment by sagzy** [comment]
In the browser, if can open your dev tools, then open the Network tab, you can see backend requests to `ghost/api/admin/images/upload/` for each image that is being uploaded in the Gallery card. <br><br>Relinking images from your content folder is unfortunately not supported at the moment.

**Comment by sagzy** [comment]
Once published on your website, you could inspect the source of the relevant `<img>` tags:

**Comment by petruut** [comment]
re the networking: I can only see assets for the 4 images that are actually displaying (even though the gallery is formed of 7 images, all available in the /content subfolder that ghost uploaded them to)

![image](https://github.com/user-attachments/assets/11e3fa4a-7813-44c6-8e46-e65a53de8ce7)

also, I can't see any errors etc. but then again, I don't know what I'm looking at.

re inspecting the source:

![image](https://github.com/user-attachments/assets/04ae1371-bd63-44a6-b8d9-66406f137a15)

so it looks like, by the time the website is rendering, it only renders the 4 images (as opposed to the 7)

**Comment by petruut** [comment]
> In the browser, if can open your dev tools, then open the Network tab, you can see backend requests to `ghost/api/admin/images/upload/` for each image that is being uploaded in the Gallery card.
> 
>  CleanShot.2024-09-18.at.13.07.09.mp4 
> 
> Relinking images from your content folder is unfortunately not supported at the moment.

my networking screenshot is from the published website. re the upload in the backend, I know that works because I can see the images in the file manager in the right /content folder

**Comment by sagzy** [comment]
Hm, unfortunately I'm not seeing how to help further with these elements, as I don't have a way to reproduce the bug at the moment. Does this happen for you with a new post as well?

**Comment by sagzy** [comment]
@petruut 👋 

Given that we have not been able to find a clear reproduction of the bug and that it seems environment-specific, we suggest that you open a thread on the [Ghost forum](https://forum.ghost.org/) to get more help, if you're still experiencing the issue.
