### ISSUE TITLE
Wrong translation in comments section for german

### ISSUE THREAD

**Issue by noezdev** [TryGhost/Ghost#21104]
### Issue Summary

The translation in the comments section for the German language is incorrect. The same phrases are being used for both "sign up" and "sign in."

"Sign up" is translated as "Jetzt anmelden," but the correct translation would be "Jetzt registrieren." "Sign in" is translated as "Anmelden."

![Bildschirmfoto 2024-09-25 um 00 17 46](https://github.com/user-attachments/assets/44b771ee-a364-469a-9dda-0d495e60c5e3)

### Steps to Reproduce

1. Install a Ghost CMS Blog
2. Select german as language
3. Create a Post
4. Navigate to the comments section

### Ghost Version

5.94.0

### Node.js Version

20

### How did you install Ghost?

Selfhosted

### Database type

MySQL 5.7

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by cathysarisky** [comment]
Hey @noezdev , thanks for the report!  Comment translations are a work in progress, and it sounds like the German ones might be coming up short here.  If you're able to put in a pull request for the wording, that'd be awesome.  Here's a link to the Ghost forum - the first post walks you through exactly how to do it, no software installs required. :) 

And while you're there, we're currently totally missing the translations for the Ghost's build-in search.  Can you help?  https://github.com/TryGhost/Ghost/blob/main/ghost/i18n/locales/de/search.json

**Comment by lsinger** [comment]
Just came across this and thought I'd add a quick fix in #21162. ☺️

**Comment by cathysarisky** [comment]
Hey @noezdev , if you have a moment to look over https://github.com/TryGhost/Ghost/pull/21165/files , that'd be great! :)
