### ISSUE TITLE
Dark-Light Mode Toggle Not Updating Page View Site

### ISSUE THREAD

**Issue by prajwaln07** [TryGhost/Ghost#21153]
### Issue Summary

The page view site does not update its styling when toggling between dark and light modes on the Ghost website
![Screenshot (58)](https://github.com/user-attachments/assets/fd1872a4-f8f5-4d9b-a7d1-6033bae27826)

### Steps to Reproduce

1.Navigate to the landing page of the Ghost website that contains the sidebar.
2.Use the theme toggle button to switch between dark mode and light mode.
3.Observe that while the sidebar and other pages update correctly, the view-site does not change its appearance and remains styled according to the previous theme.

### Ghost Version

5.92

### Node.js Version

18

### How did you install Ghost?

WSL2 using Ghost CLI

### Database type

MySQL 8

### Browser & OS version

Chrome on Windows 10

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by prajwaln07** [comment]
can i work on this ? @sagzy  @cmraible

**Comment by cathysarisky** [comment]
I'm not sure that toggle is meant to change the website colors.  (In fact, I'm pretty sure it isn't.)  It's to change the color of the admin panel, which it does correctly.

Changing theme colors depends on the theme.  If that's Source, you can change the background color by going to settings (gear icon) > themes > design & branding.

**Comment by prajwaln07** [comment]
@cathysarisky  thanks for clarification
