### ISSUE TITLE
Issue with UI

### ISSUE THREAD

**Issue by Shubh484** [TryGhost/Ghost#21194]
### Issue Summary

![Screenshot 2024-10-03 130935](https://github.com/user-attachments/assets/c41cdc8a-82d5-490c-aa3e-90fbd7cc4eb6)
![Screenshot 2024-10-03 130958](https://github.com/user-attachments/assets/869742aa-6fbc-434c-85d9-a3c6204f2c3e)

As can be seen the alignment of the canva and image below it is not proper. It need to be fixed as they overlap.

### Steps to Reproduce

UI will be more cleaner.

### Ghost Version

5.92

### Node.js Version

18

### How did you install Ghost?

WSL2/using Ghost-cli

### Database type

MySQL 5.7

### Browser & OS version

Brave / Windows 11

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by Priyanshu-su30** [comment]
Assign me the issue I will work on it

**Comment by Yadnyesh-Dashpute** [comment]
@Shubh484 I Interested to fixed the issue.
Could you please explain in detail on which page the canvas and image are overlapping so that we can easily identify and fix the issue?

**Comment by Shubh484** [comment]
<img width="442" alt="Screenshot 2024-10-03 200407" src="https://github.com/user-attachments/assets/6c3cdc17-8101-490d-a2b3-80ad746c4ab5">

assign me this issue .

**Comment by 9larsons** [comment]
This is intentional. This is not an issue with this repo, either.
