### ISSUE TITLE
sitemap-tags.xml not present in XML Sitemap

### ISSUE THREAD

**Issue by beardoggo** [TryGhost/Ghost#21296]
### Issue Summary

I'm not seeing sitemap-tags.xml generated in the root sitemap unlike other people's blogs.

![123](https://github.com/user-attachments/assets/52f77518-f6db-4a87-8680-09cb8327fd8b)

I want it generated as can be seen in Ghost.org's sitemap:

![456](https://github.com/user-attachments/assets/74610773-8cc5-4829-bdaf-83472a397067)

### Steps to Reproduce

1. Clean install Ghost

2. Install [Asona Theme](https://ghost.apalodi.com/asona/)

3. Create random pages, posts, and tags

4. No sitemap-tags.xml generated

### Ghost Version

5.95.0

### Node.js Version

N/A

### How did you install Ghost?

pikapods.com

### Database type

MySQL 5.7

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by cathysarisky** [comment]
Quick check - do you have tags that are public (do not start with #), and are those tags applied to at least one published post?

**Comment by cathysarisky** [comment]
There may be something 'quirky' about your setup.  I have a pikapods install, and once I added a published post with a public tag, the sitemap-tags.xml file appeared.  Have you changed your routes.yaml from the default?  If you don't have a tags collection, that might be to blame?

**Comment by beardoggo** [comment]
Oh I see, my routes.yaml looks like this. I'll try adding "tags" to "collections" and post the result again. Thanks!

`routes:

collections:
  /:
    permalink: /{slug}/
    template: index

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
`

**Comment by cathysarisky** [comment]
Sorry - my comment was unclear.  I meant taxonomies, and so what you have looks fine!

**Comment by cathysarisky** [comment]
Looking to see if I can replicate this real quick...

**Comment by allouis** [comment]
@beardoggo I only see this issue when all of my posts have zero tags attached to them. If that's the case then the tags don't actually have any content and so aren't included in the sitemap.

I'm going to close this issue for now - but if you are seeing that this is broken when the tags are being used, or if you think this behaviour is incorrect - please feel free to open a new issue detailing either reproduction steps or correct behaviour!
