### ISSUE TITLE
Fix: Remove Unnecessary Vertical Scrollbar

### ISSUE THREAD

**Issue by prajwaln07** [TryGhost/Ghost#21309]
### Issue Summary

There is an unnecessary vertical scrollbar appearing on the main page, even when the content fits within the viewport.

https://github.com/user-attachments/assets/31101719-2c47-4a9d-b71e-f1a3f3b6bc38

### Steps to Reproduce

just go to main page and scroll vertically 

### Ghost Version

1.26.1

### Node.js Version

v20.15.0

### How did you install Ghost?

ghost install

### Database type

MySQL 5.7

### Browser & OS version

Chrome 117.0.0.0 on Windows 10

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by savit0r** [comment]
Hi @prajwaln07 ,

I noticed the issue regarding the unnecessary scrollbar on the main page and I would love to work on fixing this. Could you please assign this issue to me?

Thank you!
savit0r

**Comment by prajwaln07** [comment]
> so you want the scroll bar to be completely removed from main page?

@Sourabh-km13 YES

**Comment by prajwaln07** [comment]
> Hi @prajwaln07 ,
> 
> I noticed the issue regarding the unnecessary scrollbar on the main page and I would love to work on fixing this. Could you please assign this issue to me?
> 
> Thank you! savit0r




> Hi @prajwaln07 ,
> 
> I noticed the issue regarding the unnecessary scrollbar on the main page and I would love to work on fixing this. Could you please assign this issue to me?
> 
> Thank you! savit0r

@savit0r NO,sorry
