### ISSUE TITLE
Navbar is getting Overlapped on the hero section in smaller devices

### ISSUE THREAD

**Issue by r7projects-shayan** [TryGhost/Ghost#21338]
### Issue Summary

The navbar is getting overlapped with the hero section in smaller devices. This is obstructing the hero section image from being visible which is lowering the user experience in mobiles. 

![Screenshot 2024-10-17 161202](https://github.com/user-attachments/assets/4384477a-c0c3-4ee9-ace3-46e9f613303a)
![Screenshot 2024-10-17 161209](https://github.com/user-attachments/assets/5053fa3d-db60-4e08-b341-e912fd70539d)
![Screenshot 2024-10-17 161215](https://github.com/user-attachments/assets/36665ebb-7a48-49c3-b476-532338ea2a3e)

### Steps to Reproduce

1. Right click on browser after visiting Ghost official website
2. Click on inspect element
3. Lower the screen size to that of mobile devices
4. Click on the hamburger menu on the top right corner

Navbar should not overlap with the hero section in any device and both must be visible at the same time, even if the hamburger is expanded. 

### Ghost Version

5.x or 5.94.1

### Node.js Version

v20.10.0

### How did you install Ghost?

npm install ghost-cli -g                                         My operating system is Windows 11. I also have WSL and Node js installed.

### Database type

MySQL 5.7

### Browser & OS version

Google Chrome, Version 129.0.6668.103 (Official Build) (64-bit)

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by Shahab-16** [comment]
I would love to fix this bug. Please assign this to me.

**Comment by cathysarisky** [comment]
The Ghost website isn't open source, afaik.  There's no way to put in a PR to fix it.

I recommend closing the issue, which isn't a Ghost CMS issue, but a Ghost website issue.

**Comment by dvdwinden** [comment]
Before I do – @r7projects-shayan, could you elaborate on the issue? You're saying the navbar is getting overlapped, but I think you mean the navbar overlaps the content? In which case: that's intentional, and does not break the experience on mobile.
