### ISSUE TITLE
Quirky search behavior

### ISSUE THREAD

**Issue by cathysarisky** [TryGhost/Ghost#21343]
### Issue Summary

I'm seeing some not-quite-right behavior from the sodo-search package, but having trouble coming up with a simple repro case.

Here's what I've got:
Run a search for 'fitness' at https://goodvibeswellness.com/ 
Scroll down.  There are posts that actually match 'fitness', but the ui seems to get stuck with a bunch of posts that just match 'F' at the top.
I can reproduce it for this site's content (when exported and imported locally), using sodo-search 1.3, and also 1.1.  (That probably rules out the CJK changes being to blame.)
I cannot reproduce it with another site running search at 1.1, nor on another site running search @1.3.

Leaving this here in case anyone else is seeing something similar.

![image](https://github.com/user-attachments/assets/193e392e-7bd8-467d-adfd-a2aad089e801)

### Steps to Reproduce

see above

### Ghost Version

search 1.1-1.3

### Node.js Version

varies

### How did you install Ghost?

local & ghost pro

### Database type

MySQL 8

### Browser & OS version

chrome, windows 10

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by STAR-173** [comment]
Hey @cathysarisky,
I'm not able to reproduce your issue. It's working completely fine for me.
Can you provide a screenshot of the issue if possible ?
