### ISSUE TITLE
Ghost Admin Profile Panel requesting 'null' URL for cover image

### ISSUE THREAD

**Issue by alexgmathews** [TryGhost/Ghost#21350]
### Issue Summary

The Ghost Admin dashboard is throwing a series of 301 redirects (in lieu of not finding the specified URL) when opening the [Profile] panel. Upon further inspection, the DOM shows the string "null" being escaped and printed inside `background-image: url()`.

### Steps to Reproduce

1. Start with fresh install
2. Open the Ghost admin
3. Click on the user-panel in the bottom-left corner of the screen
4. Click "Your Profile"

### Ghost Version

5.96.1

### Node.js Version

18.20.4

### How did you install Ghost?

Docker ghost:5-alpine

### Database type

MySQL 8

### Browser & OS version

Firefox 131.0.2

### Relevant log / error output

**DOM**
`<div class="flex min-h-[40vmin] flex-wrap items-end justify-between bg-cover bg-center" style="background-image: url(&quot;null&quot;);"> ... </div>`

**WEB DEVELOPER TOOLS > NETWORK TAB**
GET request to `https://[mydomain.foo]/ghost/null`, 301 redirect to `/ghost/null/`, 301 redirect to `/ghost/#/null/`

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by alexma418** [comment]
@mithelan - My apologies. I'd set NGINX to intercept non-front-end 301s and mark them as 404. I've updated my original Issue Summary and Error Output to reflect the 301 redirects.

Even though the redirect series [/ghost/null] > [/ghost/null/] > [/ghost/#/null/] technically resolves, I still think rendering "null" as a URL inside `background-image` wasn't intended.

Here are the screenshots you requested...

![screenshot-1](https://github.com/user-attachments/assets/f8510cac-f041-4d47-a212-5a8da4973a75)

![screenshot-2](https://github.com/user-attachments/assets/c236d800-b3c1-4aa3-be95-5ee21dd440ff)

**Comment by mithelan** [comment]
@alexma418 yes, I will check on this
