### ISSUE TITLE
Flash of error with newsletter sending problem, followed by 'success' screen?

### ISSUE THREAD

**Issue by cathysarisky** [TryGhost/Ghost#21432]
### Issue Summary

Publishing a post as a newsletter very briefly shows an error/results screen that then bounces over to the posts page with an overlay.  When Mailgun throws an error, that error message is missed, and the next screen implies a successful send, when it wasn't.

### Steps to Reproduce

How I noticed it: Hook Mailgun up in sandbox mode, and try to send a newsletter to a user who isn't on the allowed list.

### Ghost Version

5.97

### Node.js Version

18

### How did you install Ghost?

dev

### Database type

SQLite3

### Browser & OS version

Chrome, Windows 10

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by sagzy** [comment]
Thanks for raising the issue! Very valid, and linked to a recent publishing UX change. The team who has worked on the UX change will look into it 👍

**Comment by minimaluminium** [comment]
Thanks @cathysarisky — this is now fixed in https://github.com/TryGhost/Ghost/pull/21706
