### ISSUE TITLE
Text selection color non-existent for editing links in dark mode

### ISSUE THREAD

**Issue by stromfeldt** [TryGhost/Ghost#21450]
### Issue Summary

If you try and select a portion of a link in order to edit or delete it while in dark mode, the text selection colour is non-existent. It exists just fine in light mode.

https://github.com/user-attachments/assets/552034bd-7752-495e-9b17-f2f11021fd51

### Steps to Reproduce

1. Open the link editing box (while in dark mode)
2. Try to select a portion or entirety of the link
3. See that there is no text selection color

### Ghost Version

5.98.1-0-g2c7de4e+moya

### Node.js Version

Yes

### How did you install Ghost?

Ghost(Pro)

### Database type

MySQL 5.7

### Browser & OS version

Firefox 131.0.3 on macOS 15.0.1

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by dvdwinden** [comment]
Here's the fix. 

https://github.com/user-attachments/assets/a2adccea-a52e-461b-90b2-f3a97e68b04f
