### ISSUE TITLE
Enter breaks navigation editor

### ISSUE THREAD

**Issue by cathysarisky** [TryGhost/Ghost#21494]
### Issue Summary

Attempting to create a new navigation entry by pressing enter instead of clicking the green plus results in the new url being on the line below the new label.
Setup:
![image](https://github.com/user-attachments/assets/56dad03b-02b0-40e0-b38c-c0f162327864)
Then press enter (with the focus on the url field):
![image](https://github.com/user-attachments/assets/fc63ed2f-d182-48cc-9b09-74a445d490b4)

Pressing enter a second time triggers an error (makes sense) but also a render loop.
![image](https://github.com/user-attachments/assets/2ff0f564-138c-488e-b53b-2c7a8fa64b6c)

I'm leaving the render loop here with the first bug, in hopes that fixing the enter error will result in resolution of the render loop.

### Steps to Reproduce

Enter a label and url on the last line in the navigation editor.  
Press return instead of the green plus.

(The render loop is a lot more obvious with console logging added to line 11 of NavigationEditForm.tsx)

### Ghost Version

5.98 (Ghost pro)

### Node.js Version

Ghost pro

### How did you install Ghost?

Ghost Pro (also seen on dev setup)

### Database type

MySQL 8

### Browser & OS version

Chrome, Windows 10

### Relevant log / error output

```shell
None for the enter bug (see images).  An enormous amount of console spam for added logging. :)
```

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by cathysarisky** [comment]
This looks like a tricky react state bug of some sort. Having trouble putting my finger on it, but basically, setNewItem doesn't get called for changes in the URL field , only on blur.  The enter key does not trigger the necessary saving of the url before a new row gets added.  I think.

**Comment by cathysarisky** [comment]
Oh good, @dvdwinden , because I spent a couple hours looking for it, and it's got me stumped!

**Comment by dvdwinden** [comment]
@cathysarisky We've just reverted a previous change that caused this regression, which will go out with our next release, and have re-opened an internal issue to implement proper keyboard navigation for this bit of the Admin. 

I'm closing this issue for now.
