### ISSUE TITLE
Unable to Correctly Render Colored Text in Ghost 

### ISSUE THREAD

**Issue by imseanpan** [TryGhost/Ghost#21496]
### Issue Summary

Unable to Correctly Render Colored Text in Ghost 

#### Description

I am trying to extend the Ghost editor by adding a button that allows setting text color. However, I found that this functionality does not work as expected.

Specifically, when I set the text color and save the post, the `lexical` field correctly records the `<span>` tags with the `style` attribute, but the `html` and `plaintext` fields have the `<span>` tags with color removed.

#### Steps to Reproduce

1. Select some text in the editor.
2. Click the color button I added and set the text color (e.g., red).
3. Save the post.
4. Check the fields in the database and observe that the `lexical` field correctly records the `<span>` tags with the `style` attribute, whereas the `html` and `plaintext` fields have the `<span>` tags with the color removed.

#### Expected Behavior

After saving the post, the `html` and `plaintext` fields should retain the `<span>` tags with color styles, and the colored text should render correctly on the front end.

#### Actual Behavior

After saving the post, the `html` and `plaintext` fields have the `<span>` tags with color styles removed.

#### Additional Notes
<img width="1416" alt="20241101211723" src="https://github.com/user-attachments/assets/c10245cc-0e95-4b68-a3c3-a10148ae564f">
<img width="1398" alt="20241101211739" src="https://github.com/user-attachments/assets/515fdcd8-63cc-4a74-b230-f02e68d1cd9d">

#### DB Data 
```
lexical

{"root":{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"the black one. ","type":"extended-text","version":1},{"detail":0,"format":0,"mode":"normal","style":"color: rgb(204, 11, 11);","text":"the red color. ","type":"extended-text","version":1},{"detail":0,"format":0,"mode":"normal","style":"","text":"the other one. ","type":"extended-text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1}],"direction":"ltr","format":"","indent":0,"type":"root","version":1}}
```

```
html
<p>the black one. the red color. the other one. </p>
```

I would appreciate any guidance on how to retain the color styles in the `html` and `plaintext` fields, ensuring that the colored text is rendered correctly just like in the `lexical` field.

### Ghost Version

5.91.0

### Node.js Version

v20.17.0

### How did you install Ghost?

yarn

### Database type

MySQL 5.7

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by imseanpan** [comment]
### Update

After further debugging, I found that the saved HTML used the `render` method from the `kg-lexical-html-renderer` package. Fortunately, I found the `render(): string` method in the `utils->TextContent.ts` file and discovered that the `node` object does have the `__style` property. However, the `LexicalNode` defined in TypeScript does not include this property.

To verify this issue, I added the following experimental code:

```typescript
// imseanpan add test code
if (node.__style !== '') {
    const span = document.createElement('span');            
    span.setAttribute('style', node.__style);
    span.textContent = node.getTextContent();
    currentNode.append(span);            
    continue;
}
```
It appears to be working successfully. Although my code ran successfully, it is not rigorous. Therefore, I'm just identifying the issue and confirming the problematic code location. If possible, I hope the official team can quickly fix this issue and add support for changing text color so that we can happily use Ghost. 

<img width="1350" alt="20241103180642" src="https://github.com/user-attachments/assets/5c315108-5c0c-40da-91b8-8d49dc6e58da">

<img width="878" alt="20241103181511" src="https://github.com/user-attachments/assets/b18bc8bb-27c2-4924-b8bd-df5a29fd0781">

<img width="825" alt="20241103181708" src="https://github.com/user-attachments/assets/67775cc2-cecd-4e8e-9b3c-1f0a2e8723ab">

Thank you!

**Comment by kevinansfield** [comment]
Style support for text was intentionally left out. I thought we also had a transform to strip style properties on the Lexical side of things too but I can't find that now.

It's a design decision for our editor to provide minimal routes to creating poorly designed content and text color was a big part of that, not just for design but because of the accessibility issues that can create across light/dark mode and ensuring content displays correctly across different themes. On top of that, style attributes can leak across copy/paste into the editor which then creates a whole lot of other issues because there's no real way to undo that unless you add in support for editing all of the different styles that can be attached.

As such I wouldn't consider this a bug. If you're looking to make changes in your own fork then the forum ([I see you've already duplicated your question there](https://forum.ghost.org/t/unable-to-correctly-render-colored-text-in-ghost/52144/1)) is a better place to get support.
