### ISSUE TITLE
GIF upload not working: "Request not understood error"

### ISSUE THREAD

**Issue by migu0** [TryGhost/Ghost#21500]
### Issue Summary

I use GIFs in my technical "how to" [guides](https://www.michaelimstepf.com/how-to-run-llms-on-your-computer/) on Ghost Pro.  Uploading is really a hit and miss, sometimes it works, mostly it doesn't. Sometimes I can get the upload working if I try 10+ times but many times I don't success. I found that successful uploads are more likely with smaller files but sometimes I need to show something that is represented in a GIF larger than 1MB.

I usually get the this error:

<img width="751" alt="Screenshot 2024-11-02 at 12 05 33" src="https://github.com/user-attachments/assets/abb4db4b-23e1-4f71-b373-730117143bc3">

Here is the GIF that I was trying to upload: 

![Untitled design-8](https://github.com/user-attachments/assets/2dec345d-0699-4d56-a91f-f7b44a48b5c7)

### Steps to Reproduce

1. Create a new post
2. Click on +
3. Select Image
4. Try and upload the GIF I linked above

### Ghost Version

5.98.1-0-g2c7de4e+moya

### Node.js Version

Pro

### How did you install Ghost?

Pro

### Database type

Other

### Browser & OS version

Safari 18.1, Firefox 132

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by cathysarisky** [comment]
I was able to confirm there's a problem (on paid Ghost Pro, Creator level plan), using the file linked above.  The error message is:
```
{message: "Request not understood error, cannot upload image.",…}
code
"Image processing failed Unable to manipulate image."
```
The file in question is 1.44 MB, so not near the upload limit.

Not all gifs are broken.  I tried with a smaller one, 84KB, and it uploaded fine.  I also tried a 2MB animated webp (from giphy) that uploaded fine. 

It might make sense to reach out to the Ghost Pro support folks - they're in the best position to check server logs for any hints about what's going on here.
