### ISSUE TITLE
There is an incompatible cmd command in Powershell. Please make it compatible with Powershell.

### ISSUE THREAD

**Issue by Super1Windcloud** [TryGhost/Ghost#21501]
### Issue Summary

There is an incompatible cmd command in Powershell. Please make it compatible with Powershell.

### Steps to Reproduce

![图片](https://github.com/user-attachments/assets/38adae6f-04f4-47ef-a122-ba53e89dfb9a)

### Ghost Version

latest

### Node.js Version

22

### How did you install Ghost?

win11 

### Database type

MySQL 5.7

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by cathysarisky** [comment]
Hey @Super1Windcloud , thanks for the report.  I suspect this is actually coming from the yarn dependency, not ghost-cli itself.  (Yarn includes a script with that syntax, but ghost-cli does not.)

I'm commenting to make a suggestion, not offer a fix for this bug, sorry.  

I do all of my development work (both theme and core) on a Windows laptop, but I do it with WSL2.  That lets you run a Linux environment (without dual booting), and support for Linux is going to be a lot more consistent than support for Windows.  There just aren't as many people developing on Windows, and so the bugs tend to persist longer.  

Related issue (probably the same bug?) here:
* https://github.com/yarnpkg/yarn/issues/8796

**Comment by Super1Windcloud** [comment]
Maybe, WIndows+scoop makes my work more comfortable, a perfect replacement for macOS

**Comment by vikaspotluri123** [comment]
@Super1Windcloud it looks like you're trying to install Ghost using the CLI. For support on this, the [forum](https://forum.ghost.org) is the best place to get help 🙂

**Comment by Super1Windcloud** [comment]
Maybe I can install it normally using cmd, but I only like Powershell7, so I have given up the idea of ​​using ghost for the time being.
