### ISSUE TITLE
Breaking Change to Embeddable Signup Form - Integrity Token

### ISSUE THREAD

**Issue by lnhrdt** [TryGhost/Ghost#21527]
### Issue Summary

Hey Ghost team,

Just wanted to flag an issue with the recent change that introduced an integrity token requirement for the embeddable signup form (#20836, in 5.91.0). This update broke our one-click subscribe setup on external sites, as it seems to have impacted the externally hosted JavaScript (included in the generated Embed signup form) without a major version bump.

The change hit unexpectedly—our signup form just stopped working even though we were on a fairly recent version, which caused a bit of a fire drill. Going forward, it’d be great if changes impacting critical pieces like this (especially anything hosted externally) could align with a major version release, so there’s a heads-up to make any necessary adjustments. As it is, I believe embeddable signup forms are currently broken for anyone running less than 5.91.0.

Thanks for considering this!

### Steps to Reproduce

- run a 5.x version < 5.91.0, with an embeddable signup form, since this change was made
  - specifically, we were running 5.87.2
- have an embeddable signup form
- try to submit an embeddable signup form
- see the error message "Something went wrong, please try again."
- in your browser's developer console, see that the integrity token request has an error (because you're not running at least 5.91.0 and it just doesn't exist)

### Ghost Version

5.x < 5.91.0

### Node.js Version

any

### How did you install Ghost?

containerized

### Database type

N/A

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by sagzy** [comment]
Hey @lnhrdt, thanks for raising the issue!

You're absolutely right, this was a breaking change and should not have been released as a patch.

We've now corrected the issue, by publishing a new patch version of the signup form, v.0.1.8. Publications running Ghost < 5.91.0 now have a functional embedded signup form again, without having to upgrade to a later version of Ghost.

**Comment by dsebastien** [comment]
I also bumped into this. I upgraded to Ghost v6 a while ago and never saw a mention about this change. My subscription forms were broken and I didn't know. Woops ^^

**Comment by dsebastien** [comment]
For those who stumble upon this, I've updated my example project with the new approach: https://github.com/dsebastien/ghost-subscribe/tree/main
