### ISSUE TITLE
The js file cannot be correctly loaded

### ISSUE THREAD

**Issue by hogger0** [TryGhost/Ghost#21578]
### Issue Summary

https://cdn.jsdelivr.net/ghost/sodo-search@~1.5/umd/sodo-search.min.js
https://cdn.jsdelivr.net/ghost/portal@~2.46/umd/portal.min.js
The above js file cannot be correctly loaded due to dns pollution, how to customize and modify the address of this js?

### Steps to Reproduce

empty

### Ghost Version

5.99.0

### Node.js Version

18.20.4

### How did you install Ghost?

docker

### Database type

MySQL 8

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by vikaspotluri123** [comment]
Please create a topic on the [forum](https://forum.ghost.org) with more details 🙂

**Comment by ronaldlangeveld** [comment]
Hi @hogger0  👋 

To override the configurations, you can add the following to your config.production.json (or config.development.json, depending on your environment):

```
    "portal": {
        "url": "https://cdn.jsdelivr.net/ghost/portal@~{version}/umd/portal.min.js",
        "version": "2.46"
    },
    "sodoSearch": {
        "url": "https://cdn.jsdelivr.net/ghost/sodo-search@~{version}/umd/sodo-search.min.js",
        "styles": "https://cdn.jsdelivr.net/ghost/sodo-search@~{version}/umd/main.css",
        "version": "1.5"
    },
```

For more details on configuration files, check out our documentation here: [Ghost Configuration Guide](https://ghost.org/docs/config/).
