### ISSUE TITLE
Schedule for Later Calendar highlights the wrong date

### ISSUE THREAD

**Issue by ShrootBuck** [TryGhost/Ghost#21634]
### Issue Summary

When selecting a date in the publish page (after selecting "schedule send for later"), the date in the date picker is shown as one day prior to the day actually selected.

Easier to see it: [https://youtu.be/-ptojectxBY](https://youtu.be/-ptojectxBY)

### Steps to Reproduce

See above

### Ghost Version

5.99.0

### Node.js Version

18.something

### How did you install Ghost?

Ubuntu

### Database type

MySQL 8

### Browser & OS version

Chrome & macOS Sequoia

### Relevant log / error output

```shell
N/A
```

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by ShrootBuck** [comment]
Why did Linear close as completed? The issue isn't fixed yet

**Comment by vikaspotluri123** [comment]
I think it was fixed in https://github.com/TryGhost/Ghost/pull/21657 but not linked
