### ISSUE TITLE
Tags doesn't seem to work and redirected to 404 page

### ISSUE THREAD

**Issue by zinkohlaing** [TryGhost/Ghost#21633]
### Issue Summary

Hi,

I have recently set up my Ghost blog at zinkohlaing.com and it is self-hosted via Pikapods.

Here's an example URL that contains the tag "OMSA"
https://www.zinkohlaing.com/my-experience-with-georgia-tech-omsa-program-part-4/

![image](https://github.com/user-attachments/assets/a57565da-6ab7-4f19-befc-80d63d223196)

I can see from Inspect Element that it should be redirected to https://www.zinkohlaing.com/tag/omsa/

But when I open this link or click on the tag, it is redirected to 404.

Based on my research, it seems that my Route file needs to be updated/changed. But the thing is I haven't made any modifications since the setup. This is what the Route file looks like.
![image](https://github.com/user-attachments/assets/b8b4fa62-84d5-43f1-a0b1-50fd2f6179b9)

I have already deleted / re-added the tags and it is happening to all tags so far.

### Steps to Reproduce

1. Visit the post that contains a tag (like this: https://www.zinkohlaing.com/my-experience-with-georgia-tech-omsa-program-part-4/)
2. Click on the tag
3. 404 happens

### Ghost Version

5.100.1

### Node.js Version

Not sure

### How did you install Ghost?

Via Pikapods

### Database type

Other

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by zinkohlaing** [comment]
🙌yes!

**Comment by 9larsons** [comment]
Glad you got it sorted 👍 .
