### ISSUE TITLE
"Schedule for Later" Calendar highlights the wrong date

### ISSUE THREAD

**Issue by ShrootBuck** [TryGhost/Ghost#21660]
### Issue Summary

When selecting a date in the publish page (after selecting "schedule send for later"), the date in the date picker is shown as one day prior to the day actually selected.

Already made this issue as #21634, but linear bot closed it for some reason.

### Steps to Reproduce

See above

### Ghost Version

5.101.2

### Node.js Version

18

### How did you install Ghost?

Ubuntu 22.04 LTS

### Database type

MySQL 8

### Browser & OS version

Chrome & macOS Sequoia

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by vikaspotluri123** [comment]
I think it was fixed in https://github.com/TryGhost/Ghost/pull/21657

**Comment by sagzy** [comment]
Hey @ShrootBuck, thanks for the report! Confirming what @vikaspotluri123 said, we've had multiple reports of this issue and it has now been fixed in https://github.com/TryGhost/Ghost/pull/21657. The fix will be part of the next Ghost release, planned for Friday 22, Nov 2024

**Comment by ShrootBuck** [comment]
ah ok, my bad
