### ISSUE TITLE
The slide-out panel inside Ghost's admin on mobile lacks intuitive close triggers

### ISSUE THREAD

**Issue by alexgmathews** [TryGhost/Ghost#21698]
### Issue Summary

*This is a user-interface design issue. It's less than a bug but neither is it a new feature request.*

There's not an intuitive way to close the slide-out panel inside Ghost's admin on mobile. For instance, if you open the panel by clicking the [More] button in the bottom panel while the [Dashboard] section is loaded, the only way to close the slide-out panel is to click one of the remaining buttons in the bottom panel, in this case [Posts] or [Members].

My first instinct, if I open the slide-out panel by clicking the [More] button, is to close the slide-out panel by clicking the [More] button again. (B) My second instinct, if I want to go back to the [Dashboard] section loaded underneath, is to click the [Dashboard] button. (A) Neither action closes the slide-out panel.

(A third close-point could be a close icon added at the top-right corner of the slide-out panel.)

![mockup](https://github.com/user-attachments/assets/8ddb8c8e-d452-4761-b5cc-8508cafa7049)

### Ghost Version

6.101.1

### Node.js Version

18.20.4

### How did you install Ghost?

Docker ghost:5-alpine

### Database type

MySQL 8

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by dvdwinden** [comment]
Thank you for flagging this, @alexgmathews — a solution is in the works. We'll update you here once it's out.

**Comment by dvdwinden** [comment]
A fix for this has merged and will be included in our next release. With this change, you can now also tap the 'More' button or any other menu item to have the menu close itself again. You can also tap outside of the menu (on the background) to dismiss it. 


https://github.com/user-attachments/assets/f0508ecf-9f38-4ba5-8fb5-8fab2d53743a
