### ISSUE TITLE
Fixing URL Structure Issue: From 'domain.com/title' to 'domain.com/page/title

### ISSUE THREAD

**Issue by FaraLyla** [TryGhost/Ghost#21785]
### Issue Summary

Hi there. 

Previously, my URLs were fine, showing as domain.com/title-of-article, but suddenly they are now showing as domain.com/page/title-of-article. How can I fix this? 

Currently I'm using free plan to see how it goes first but seems like got problem. Can fix? 

Appreciate your help, thank you.

### Steps to Reproduce

Nothing. this happened in sudden while i was updating my page.

### Ghost Version

Free Plan

### Node.js Version

not sure

### How did you install Ghost?

I just login via google chrome

### Database type

MySQL 5.7

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by allouis** [comment]
Hey! If you're having trouble with a Ghost(Pro) site, please email us at support@ghost.org and we'll help you out there!
