### ISSUE TITLE
Post email test is blocked by UI when Mailgun is not configured

### ISSUE THREAD

**Issue by markdon** [TryGhost/Ghost#21882]
### Issue Summary

![image](https://github.com/user-attachments/assets/cd61cc75-580a-41ff-9f55-22b41e962006)

### Steps to Reproduce

1. Configure ghost with non Mailgun smtp provider as per https://ghost.org/docs/config/#mail
1. Write a post
2. Preview email
3. Send test email
4. Observe instant "Please verify your email settings" message

### Ghost Version

5.104.1

### Node.js Version

22

### How did you install Ghost?

ghost:5-alpine 68c3efe223b2c8750470fd0e7bb02f27e1fe3a6d4a01c0e4e1f28a2b1b3304c8

### Database type

MySQL 8

### Browser & OS version

Chrome

### Relevant log / error output

See https://github.com/TryGhost/Ghost/blob/fd8759a3a8e5c9311dbb08230abcd8631b94018e/ghost/admin/app/components/editor/modals/preview/email.js#L110 
that explicitly blocks this in the UI when Mailgun is not configured.

This is quite concerning when preparing for the first post of a Ghost deployment. I'm guessing though it's just this one feature that's not going to work unless Mailgun is being used. 

The environment section of my docker-compose:
```shell
    environment:
      # see https://ghost.org/docs/config/#configuration-options
      database__client: mysql
      database__connection__host: db
      database__connection__user: root
      database__connection__password: BazredactedKaKx
      database__connection__database: ghost
      url: https://streetspeoplelovehobart.au
      mail__from: "'Streets People Love Hobart' <perci@lentsnotmakeittooeasyforthebots.au>"
      mail__transport: SMTP
      mail__options__service: SES
      mail__options__host: email-smtp.ap-southeast-2.amazonaws.com
      mail__options__secure: true
      mail__options__port: 465
      mail__options__auth__user: AredactedO
      mail__options__auth__pass: BFTredactedsx
```

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by vikaspotluri123** [comment]
This seems reasonable since sending newsletters requires [bulk email](https://ghost.org/docs/newsletters/) to be configured in the admin panel

**Comment by markdon** [comment]
Oh damn, thanks for the link. Mailgun really is required, and is the only option, for bulk email!

As far as I understand, Amazon SES should be suitable for bulk email via SMTP. I went with Amazon SES because it's familiar and appears to be FAR CHEAPER than Mailgun if you have 101+ subscribers. Mailgun free tier is limited to 100 emails/day, then USD$15/month for any more.

I found a [forum thread on this topic](https://forum.ghost.org/t/sending-emails-without-using-mailgun/26554/15) that you, @vikaspotluri123, contributed to. Love your work. 

I'm probably going to have to go down this path from https://ghost.org/docs/faq/mailgun-newsletters/

### I still want to use a different provider to send email newsletters, why can’t I do that?
You can. There is no requirement to use Ghost’s built in newsletter delivery feature. Before we released this feature, thousands of people sent their newsletter using all sorts of other services such as Mailchimp, Sendgrid, Convertkit, and many others. You can easily sync your members database to an external newsletter provider via [Zapier](https://ghost.org/integrations/zapier/), or by following our [detailed integration guides](https://ghost.org/integrations/?tag=email).
