### ISSUE TITLE
Problem with ./partials/navigation.hbs

### ISSUE THREAD

**Issue by joe-blocher** [TryGhost/Ghost#21894]
### Issue Summary

Sometimes the override in navigation.hbs works, sometimes not ... when I do ghost restart.

### Steps to Reproduce

**1.  It's not working - the override will not be used, only the default navigation is visible**
![# search-toggle hbs](https://github.com/user-attachments/assets/3967a0b1-533e-4b8a-bf52-1df2c19d8751)
![Pasted Graphic 16](https://github.com/user-attachments/assets/ede712d4-5d64-4b6e-ba4f-e4e31349e15b)

**2. When replace with a `partial/nav.hbs` with the only line {{navigation}} it works!**
I can even run `ghost restart`.
![Pasted Graphic 14](https://github.com/user-attachments/assets/024b151b-4c25-4658-acbd-74b27a2e5a74)

![Pasted Graphic 12](https://github.com/user-attachments/assets/ca1f40df-2a01-4f7f-ac4e-46636add14d7)

![Pasted Graphic 17](https://github.com/user-attachments/assets/17aeac14-2c8f-4bf3-8076-634bab668915)

**3. When used both in `default.hbs` in works: displays twices.**
![Pasted Graphic 10](https://github.com/user-attachments/assets/f0d97431-549f-4908-b081-743b22b823ed)
![» About](https://github.com/user-attachments/assets/5c2e622e-eea0-47ff-9ede-9510d5a75034)

**4. If I remove the `{{> nav}}`: It works! All fine!**
![# search-toggle hbs](https://github.com/user-attachments/assets/607f9cbf-1e06-4038-be58-b46407db1b35)

![Pasted Graphic 17](https://github.com/user-attachments/assets/bb01188d-2965-4560-bd01-5aa378475ddd)

**5. If I run `ghost restart`:  It's not working - the override will not be used, only the default navigation is visible**
See Step 1.
![Pasted Graphic 18](https://github.com/user-attachments/assets/e9d8f6f6-7289-4eb1-95c5-fdf1a1c658c1)

### Ghost Version

5.105.0

### Node.js Version

v18.19.0

### How did you install Ghost?

ghost install local / MacOS Sequoia 15.1.1

### Database type

SQLite3

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by ErisDS** [comment]
Can you provide me with the contents of your `navigation.hbs` file so I can try to reproduce please?

**Comment by joe-blocher** [comment]
Thank you for your efforts.
In source theme is no problem. I think is my theme with all the components around (tailwind, ...) that is responsible for the error. I will do it with `partial/nav.hbs`, this works. 

**But another problem is the bug I reported in July 2023.** 
It's still is open. But I made a pull request with an easy solution. 
[https://github.com/TryGhost/Ghost/issues/17514](https://github.com/TryGhost/Ghost/issues/17514)

It was merged and reverted: 
[https://github.com/TryGhost/Ghost/pull/19298](https://github.com/TryGhost/Ghost/pull/19298)
I don't no why... I send a message to [ronaldlangeveld](https://github.com/ronaldlangeveld) without a anwers.

I need it not only for development. Even in production mode on a server this is a big problem.
I use it as maintenance mode when the website is in progress.
Other user had the same problem.

Please fixed the bug. 
I always had to change the two line of code when I have a new installation...
Thank you

**Comment by ErisDS** [comment]
OK `partial/nav.hbs` should be unnecessary, there's probably a bug somewhere and I'd want to track it down in case it's worse in production.

I'll close this for now but happy to have a look if you have more reproduction info.
