### ISSUE TITLE
Required API version for Apps

### ISSUE THREAD

**Issue by sebgie** [TryGhost/Ghost#2213]
To ensure that an app is compatible with the installed Ghost version  apps should provide the expected API version. App installation then checks if the required api version matches the available api version and provides feedback if the installed version of Ghost is not compatible.

I would propose that available and required api version are stored in `package.json`:

App `package.json`:

```
{
	"ghost": {
		...
  		"required-api-version": "0.1.0",
  		...
	}
}
```

Ghost `package.json`:
```
{
    "name"        : "ghost",
    "version"     : "0.4.1",
    "api-version" : "0.1.0",
    ...
}
```

After introducing a version for the API we need to make sure that we do not introduce breaking changes to the API and keep legacy/deprecated versions of changed interfaces for some time.

**Comment by ErisDS** [comment]
Temporarily closing all of the `app` specific issues (tagged with `later`). Will review & reopen those that are still relevant when we kick off that project, which should be shortly after Zelda lands.
