### ISSUE TITLE
App version/updates

### ISSUE THREAD

**Issue by sebgie** [TryGhost/Ghost#2214]
From seeing some references to an app version number in different issues, I assume that it would be the best to store the app version in `package.json` and treat it like any other version number.

When the app ecosystem comes to life we'll need to provide an update path for developers to update Ghost relevant information/settings when releasing an update of an app. I think that the following values would need to be updated:

- permissions, if stored in the database
- default app settings

In addition to `install`, `activate`, `deactivate` and `delete` I would vote for introducing an `update` method to update apps with a higher (changed?) version number?

**Comment by ErisDS** [comment]
Temporarily closing all of the `app` specific issues (tagged with `later`). Will review & reopen those that are still relevant when we kick off that project, which should be shortly after Zelda lands.
