### ISSUE TITLE
Remove the deprecated helper pageUrl

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#2217]
In #2216 `pageUrl` is being renamed to `page_url`, but the original name is being left in as an alias with a deprecated warning message.

We've left that in for a Ghost version to give theme developers time to update their themes, after #2216 is complete, and we have shipped 0.5, we need to clean up after ourselves and remove the deprecated `pageUrl` alias.

**Comment by jonwgeorge** [comment]
@ErisDS I see one PR, but it looks like there are more references to PateUrl in the Ghost core, does this still need to be tackled?

**Comment by ErisDS** [comment]
Not for a while yet.

**Comment by ErisDS** [comment]
This should be finally removed in 1.0.0
