### ISSUE TITLE
First Run Process: auto-configure URL

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#2240]
Probably requires #2164 to be merged first

It would be great if we could try to handle the setting of blog_url in a nicer way than having to edit a config.js file.

Ideally: check if the URL has been set to something other than "my-ghost-blog.com" in config.js 

 - if so, do nothing 
 - if not write the blog_url in config.js with the base url from wherever example.com/ghost/setup/ is run.

This is pretty complex as we will need to first check to see if Ghost can write to the file. Then we need to read and parse the file, before modifying some part and writing again.

It is probably best to only configure the URL for the current environment, but perhaps doing it for both dev and prod would be easier?

**Comment by kevinvangelder** [comment]
I agree with both above. I used a one-click installer on WebFaction and while it's easy enough to change the config file I can't figure out what command they ran to compile the site, so the setting isn't taking and "local" links are going to `my-ghost-blog.com`.

An alternative solution would be to make this a user-configurable setting in the site's administrative panel.

**Comment by ErisDS** [comment]
Closing this in favour of #7414, which will (for alpha-builds does already) solve this.
