### ISSUE TITLE
Feature Request: Bulk Actions Menu for Admin Content Pane

### ISSUE THREAD

**Issue by gotdibbs** [TryGhost/Ghost#2309]
I think it would be great to have the ability to apply actions to multiple posts/pages in the content pane of the admin interface. For me personally this has come about with testing imports and wanting to delete a series of posts quickly. However, I do not think that is the only reason for such a menu to exist. Perhaps someone might want to bulk flip post status, or turn posts into pages. I would think that in the future there might be a use case coming out of apps.

I've honestly gone back and forth on this one being part of core so I'm looking to see what others think.

**Comment by ErisDS** [comment]
I think this is something that likely belongs on the [wishlist](http://ideas.ghost.org). It's sat here for a long time not getting traction - that's not to say it's not something we might do one day, but it's not high priority right now.

**Comment by ayyilmaz** [comment]
I think this is essential feature for blog system. Especially we need this bulk funciton on migrations. For instance we migrate tags with categories when we migrate from Wordpress and  we get hundreds tags. We have to enter each tag's edit page to remove them. These operations also apply to members and posts. I think bulk actions processing is important and icrease efficiency.
