### ISSUE TITLE
Reduce/Remove Circular Dependencies

### ISSUE THREAD

**Issue by hswolff** [TryGhost/Ghost#2455]
There are a couple of locations throughout the code base at the moment that suffer from circular dependencies.

I feel confident we'll (eventually) be able to remove all of these CI.  I doubt it'll be easy, but definitely doable.

If anyone notices a circular dependency could you please add it as a comment here.  As we collect known circular dependencies it'll be easier to resolve them.

**Comment by ErisDS** [comment]
Closing as done for now.
