### ISSUE TITLE
Add API endpoints for Apps

### ISSUE THREAD

**Issue by sebgie** [TryGhost/Ghost#2465]
The following API end points are intended to manage Apps using the GUI.

- `GET /ghost/api/v0.1/apps/`: get a list of all available apps
- `GET /ghost/api/v0.1/apps/<id or app-name>`: get app details using id or app-name
- `DELETE /ghost/api/v0.1/apps/<id or app-name>`: delete app using id or app-name
- `PUT /ghost/api/v0.1/apps/<id or app-name>`: edit app using id or app-name, currently needed to activate/deactivate Apps

**Comment by ErisDS** [comment]
Temporarily closing all of the `app` specific issues (tagged with `later`). Will review & reopen those that are still relevant when we kick off that project, which should be shortly after Zelda lands.
