### ISSUE TITLE
Add API end points for App fields

### ISSUE THREAD

**Issue by sebgie** [TryGhost/Ghost#2505]
With the first release of Apps it'll be possible to store data associated with `posts`, `tags` or `users`. To access these app fields I would like to suggest the following API end points.

- `GET /ghost/api/v0.1/apps/<app-name>/<relatable_type>/<relatable_id>/`: get a list of all available fields for given ID
- `GET /ghost/api/v0.1/apps/<app-name>/<relatable_type>/<relatable_id>/<app_fields.id or app_fields.key>`: get a field by ID or key
- `POST /ghost/api/v0.1/apps/<app-name>/<relatable_type>/<relatable_id>/`: add a new field
- `DELETE /ghost/api/v0.1/apps/<app-name>/<relatable_type>/<relatable_id>/`: delete a field
- `PUT /ghost/api/v0.1/apps/<app-name>/<relatable_type>/<relatable_id>/<app_fields.id or app_fields.key>`: edit a field

Example Kudos App:
**Add new Kudos counter for post with id: 1**
```
Post /ghost/api/v0.1/apps/kudos/posts/1/
{
    kudos = [{
        count: 0
    }]
}
````

**Get Kudos for post with id: 1**
```
GET /ghost/api/v0.1/apps/kudos/posts/1/
```
returns:
```
{
    kudos = [{
        count: 0
    }]
}
````

**Increment Kudos counter by one**
I think that the correct way to increment a counter would be PATCH with an increment operation. I have opened a proposal to add `increment` operations to JSON API (https://github.com/json-api/json-api/issues/214) which does not comply to the PATCH specification. Does anyone know of a nice and clean way to realize a counter while still complying to the specifications?

```
PATCH /ghost/api/v0.1/apps/kudos/posts/1

[
  { "op": "increment", "path": "/kudos/0/count", "value": 1 }
]
```

**Comment by ErisDS** [comment]
Temporarily closing all of the `app` specific issues (tagged with `later`). Will review & reopen those that are still relevant when we kick off that project, which should be shortly after Zelda lands.
