### ISSUE TITLE
Add API end points for App settings

### ISSUE THREAD

**Issue by sebgie** [TryGhost/Ghost#2506]
To manage settings for Apps the I would suggest to add the following API end points. Similar to Ghost settings, App default settings are added using a json-file (#2139):

- `GET /ghost/api/v0.1/apps/<id or app-name>/settings/`: get a list of all available settings
- `GET /ghost/api/v0.1/apps/<id or app-name>/settings/<id or name>`: get setting using id or name
- `PUT /ghost/api/v0.1/apps/<id or app-name>/settings/<id or name>`: edit setting

**Comment by ErisDS** [comment]
Temporarily closing all of the `app` specific issues (tagged with `later`). Will review & reopen those that are still relevant when we kick off that project, which should be shortly after Zelda lands.
