### ISSUE TITLE
[Discussion] Filter context information

### ISSUE THREAD

**Issue by halfdan** [TryGhost/Ghost#2567]
As shortly discussed in #2554 filters should provide contextual information. #2560 implements an additional `context` parameter that can be passed to `doFilter`.

A filter might decide to render a post differently when rendered for an RSS feed or for an email. An additional named context parameter would help to make context based decisions when filtering.

In this issue I’d like to discuss a way to let the filter know in which context it is applied. `prePostRender`  is applied both to render posts for the frontend and for rss feeds.

1. Do we need to define named contexts like `rss`, `homepage`, `single` (which would match the controller methods and could be probably be auto-applied)?
2. Should they be auto-applied? 
3. How are named contexts passed (key-wise)? `doFilter('prePostRender', post, { context: 'rss' })` seems viable, but would end up looking like `function filter(data, context) { console.log(context.context); }` 

----

Example use case: For [Ghostalk](http://talk.ghost.io) I’m developing an app that will display the `<audio>` player when the post is rendered in the browser, but not when it is rendered for the RSS feed (where `itunes:enclosure` is used).

**Comment by ErisDS** [comment]
Temporarily closing all of the `app` specific issues (tagged with `later`). Will review & reopen those that are still relevant when we kick off that project, which should be shortly after Zelda lands.
