### ISSUE TITLE
[Discussion] Apps - the best approach to commenting systems

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#2584]
One of the most popular modifications people make to their Ghost blog, is to add comments. This is a relatively straightforward amend to make to a theme at present, but when Apps become available we expect it to become a matter of a few clicks.

Here is a list of some of the commenting systems that can be integrated with Ghost at present (if you know of others please leave a comment and I will add it to the list):

* [Disqus](http://disqus.com)
* [LiveFyre](http://web.livefyre.com/)
* [Moot](https://muut.com/)
* [Facebook](https://developers.facebook.com/docs/plugins/comments/) 
* [Google+ Comments](http://bioselemental.com/ghost-adding-google-comments/)
* [Annote](http://annote.in/)
* [NodeBB](http://blog.nodebb.org/nodebb-v0-3-2-released/)
* [Isso](http://posativ.org/isso/)
* [Intense Debate](http://intensedebate.com/)
* [Juvia](https://github.com/phusion/juvia)

These solutions all have slightly different approaches to how they can be integrated, but it almost always requires embedding some extra code into the blog page. Therefore we need to make sure there is a simple way to integrate between the app and any theme. That is, there needs to be an easy way for themes to support the addition of comments with minimal impact or effort on everyone's part.

At present we have `{{ghost_foot}}` which enables us to embed code in every page. This will likely be augmented by code injection #1993, however this isn't a suitable solution for comments for two related reasons: firstly, because most comment systems require the code to be injected at the point where the comments should appear, and secondly because comments are usually only wanted on blog posts, i.e. only in `post.hbs` not anywhere else.

Therefore, I propose a new helper:

`{{comments}}`

This can be placed by theme developers wherever comments should appear, and can be leveraged by comment app authors to output their code via an api method something like:

```
var code = '<script....</script>';
this.ghost.registerComments(code);
```

The upside to this suggestion is that `{{comments}}` can be added to themes long before it does anything. In fact, we can get theme developers to do something like this for added flexibility:

```
{{#if comments}}
  {{comments}}
{{else}}
... current comment solution goes here...
{{/if}}
``` 

The downside to this is that it requires theme authors (or users) to do some work in order to get comments working. Not all themes are kept up to date. So it's worth considering whether we can add a fall back for where comments get inserted if `{{comments}}` doesn't exist.

This begs a second question about how to tell if a theme supports certain features... can we detect them? Or should we get theme authors to declare their feature support in `package.json` somewhere? This is probably a different discussion though.

Another downside to this helper is that it is very, very specific. This is good in some regards, comments are a very common piece of functionality so it's probably not a superfluous helper... but comment systems have one other common feature that isn't supported by this helper, which is displaying a comment count. So do we also add `{{comment_count}}`? Or do we get comment apps to implement that helper if they support it? Adding 2 helpers seems a lot, but getting individual apps to implement a helper means they probably won't do it consistently.

So, I'm throwing this open to discussion. Is there a better way?

**Comment by segmentationfaulter** [comment]
I have not tested it, but the developer says it is built for inline comments in ghost http://ouija.io/

**Comment by HLFH** [comment]
@segmentationfaulter Ouija has been discontinued since September 2014. It's now released as open source. We need to solve these issues to get it working on Ghost: https://github.com/ouija-io/ouija/issues/74 and https://github.com/ouija-io/ouija/issues/76

**Comment by P3lUZa** [comment]
Add Isso and Juvia!!!!

**Comment by ErisDS** [comment]
Temporarily closing all of the `app` specific issues. Will review & reopen those that are still relevant when we kick off that project, which should be shortly after Zelda lands.

**Comment by 23W** [comment]
@ErisDS Is it realized in the version 0.11 LTS or will be in the version 1.0 ?
