### ISSUE TITLE
Remove the old body classes

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#2597]
**Note:** This must only happen once we have shipped 2 releases in which the new, replacement `paged` and `page-{{slug}}` classes are available.

The new classes should become available with the closure of issue #1967, which should happen in the release after 0.5.0.

Once we are ready we need to remove the `archive-template` body class and also the `page-template-{{slug}}` classes. This is done in the `body_class` core helper.

**Comment by alecho** [comment]
Was this taken care of in #4903?

**Comment by ErisDS** [comment]
Ashamedly, we never updated Casper to match the new requirements. That work is being done by @AileenCGN. Once the Casper updated is complete, we will remove the body classes.
