### ISSUE TITLE
Post Filter Menu

### ISSUE THREAD

**Issue by JohnONolan** [TryGhost/Ghost#2640]
Time to implement the post filter UI - which has been around in some form or another since v0.1 - but hidden from view.

This should use the standard/existing dropdown menu styles in order to filter posts by a few different attributes. In future this will be more comprehensive, this is a first pass solution to allow some very basic sorting of the post management screen.

When a menu item is clicked on, the post list heading, and the posts loaded below, should update accordingly.

![image](https://cloud.githubusercontent.com/assets/120485/2768194/75c9d2c0-ca41-11e3-84c0-0d71d13ac128.png)

**Comment by ErisDS** [comment]
@LevelbossMike / @pangratz just wanted to check in again to see if you guys could possibly wrap this up? If not, could you please push up whatever you did on the hack day as reference material and link it here? It'd be a shame to lose all of that work and experience.

**Comment by LevelbossMike** [comment]
@ErisDS Sorry for not updating this. I will have a look at this at the weekend. Pretty busy right now.

**Comment by morkeleb** [comment]
The filters look great, but some feedback.
I recently imported 240ish blogposts into ghost (from wp) and the list makes them hard to work with. I'd like to be able to filter on title and or tags.

That said, being able to separate pages from posts would be alot!

**Comment by ErisDS** [comment]
Closing this issue, because although we definitely do want and need to add this sort of feature, the spec here is completely wrong in light of the new [Zelda UI](https://github.com/TryGhost/Ghost/pull/5273).

Will respec and reopen, in the meantime it's still on the [roadmap](https://trello.com/c/7GUDsl3J/48-post-filter-menu).
