### ISSUE TITLE
Feature Request: Auto scroll in mobile editor while typing

### ISSUE THREAD

**Issue by ThaWeatherman** [TryGhost/Ghost#2815]
I wrote a post up on my Galaxy S4 yesterday and noticed that while I typed once the text got below where the keyboard was on the screen I could keep typing but the editor wouldn't move up so I could see it. I would have to manually scroll down to see my text then continue typing. I'm not sure if there is a way to change this, and if not manually scrolling really is not a big deal, but it would be great if the mobile editor auto scrolled while writing just like the web editor.

**Comment by ErisDS** [comment]
I believe this issue was resolved some time ago.
