### ISSUE TITLE
[Ember.js] [API] status code for HTTP API delete responses

### ISSUE THREAD

**Issue by jaswilli** [TryGhost/Ghost#2871]
In working on #2849, I've run into an issue where Ember wants to call `.set()` operations on post model objects after they have been deleted (i.e., had `destroyRecord()` called on them), and this causes Ember to throw exceptions.

I believe this is because Ghost is currently returning status `200` and the JSON for the object in response to `DELETE` requests to the HTTP API.  According to http://www.w3.org/Protocols/rfc2616/rfc2616-sec9.html#sec9.7/ I feel like we should be returning `204` with an empty response body.

I've changed the API response locally and confirmed that everything works as expected with a `204` response.

Thoughts?

(refs #2187)

**Comment by ErisDS** [comment]
I believe the reasons why we couldn't do this before are now gone? 

The cache invalidation code no longer needs to know what was deleted and I think that it should be possible to output deletion notifications from Ember without having to return the details of the deleted post from the API?

Wondering if it's worth revisiting this and getting it done now, as it would simplify some code as well as result in a more standard API?

**Comment by jaswilli** [comment]
I have a branch that does some refactoring and optimization of post deletion and tag relations. I'll open a PR for that and then build the changes for this on top of it.
