### ISSUE TITLE
[Ember.js] Unit Tests

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#2990]
Testing Ember with Casper.js #2989 will give us an overview of whether the admin is functioning as we expect. However, Ember apps also lend themselves well to unit testing, and there are certain sections of the admin which would benefit from being tested in this way.

Standard Ember unit tests use qunit, but Ghost makes heavy use of mocha, so it is preferable if the unit tests can be run using mocha.

**Comment by jaswilli** [comment]
There are now a bunch of unit tests for models, controllers, and components that can be used as a reference when adding more tests: https://github.com/TryGhost/Ghost/tree/master/core/test/client/unit

**Comment by rwjblue** [comment]
@jaswilli - Awesome!!

**Comment by ErisDS** [comment]
Going to consider this done. The system is in place and there is a set of tests that could do with expanding but we should write explicit issues for that.
