### ISSUE TITLE
[Ember.js] Feature Request: Modal Title

### ISSUE THREAD

**Issue by novaugust** [TryGhost/Ghost#3009]
Playing around in the Ember Settings General, I tabbed away and came back and had forgotten just which modal I had up and was playing with.

The settings screen pops up two modals for images, one for the blog cover, and one for the blog logo. It'd be great if those words could be at the top of the modal itself to remind the user just what they're up to.

![image](https://cloud.githubusercontent.com/assets/1207005/3340927/4931720c-f883-11e3-9086-9eadf3b2ca94.png)
*Great cover, bad logo*

**Comment by ErisDS** [comment]
We're going to be revisiting all of the image uploading UX somewhere in the near future, so closing these two issues (#3009, #3517) in favour of an overhaul.
