### ISSUE TITLE
Content Security Policy

### ISSUE THREAD

**Issue by cgiffard** [TryGhost/Ghost#332]
I know this probably isn't a huge priority for 0.3, but we should think about incorporating [content-security policy](https://developer.mozilla.org/en/docs/Security/CSP) headers, at least for the admin panel, and possibly for the user theme too (although we'll probably need to give them the ability to turn it off for the theme — can't protect users from themselves!)

**Rationale:** CSP is widely supported by modern browsers and is totally ignored by those which don't — meaning it can't damage the experience for substandard UAs. While CSP won't stop us from falling victim to XSS vulnerabilities, it will dramatically limit their scope and severity.

Implementation, once we've agreed on what policy we want to establish, is trivial —only requiring the creation of an express middleware function which simply sets the relevant headers headers (possibly read out of config.)

While 0.3 is probably out the window for CSP, we should think about incorporating it before too much development on Ghost (which might not play so well with CSP if not planned for) is undertaken.

**Comment by ErisDS** [comment]
Going to close this for now with the label `later` to reopen when CSP becomes more widely supported.
