### ISSUE TITLE
Create functional tests for MU

### ISSUE THREAD

**Issue by novaugust** [TryGhost/Ghost#3350]
**Updated**

>So the problem is that we want to test the interface when there are multiple users, there is a lot of MU stuff to test with CasperJS:
>
> * settings/users page
> * PSM
> * the interface changes when logging in with different roles.
>
>In order to be able to test those things, we need to be able to create at least 1 user with each role in the system, perhaps more.

-- ErisDS

**Comment by ErisDS** [comment]
We're going to radically overhaul how we do testing, don't think this issue is needed anymore.
