### ISSUE TITLE
Bug: Random Weird Icons

### ISSUE THREAD

**Issue by dbalders** [TryGhost/Ghost#3515]
### Issue Summary

Device: All

Sometimes after a fresh update I would get weird icons. Like I would get Roses or Thumbs Up icons instead of the mail icon or whatever. I have not been able to pinpoint when exactly it is getting triggered cause it has only happened a few times and I cannot reproduce it on the fly. But here is what it looks like:

![img_0121](https://cloud.githubusercontent.com/assets/4715098/3774909/2f760146-1937-11e4-88ae-e1c3bec81c78.jpg)

Sorry for the vague issue. I will update if I can figure out how to reproduce it consistently, but right now I can't.

### Technical details:

Ghost Version: 0.5.0RC
Client OS: iOS 6
Server OS: Ubuntu 12.04
Browser: Safari
Database: SQLite
Using DigitalOcean

**Comment by PaulAdamDavis** [comment]
Reopening due to a report from a user who did see emoji replacing the proper icons.

At some point in the past, new icons were added and the prefix for unicode references were changed back to `\e` instead of `\f`.
