### ISSUE TITLE
Add validation on blog logo

### ISSUE THREAD

**Issue by andyboutte** [TryGhost/Ghost#3517]
Summary of Issue 
------------------------------- 

This is not really a bug but more of a feature request.  When adding a blog logo via URL there is no validation that what is being added is some sort of image.  http://www.google.com is accpeted which results in the broken image icon.

Additional Information 
-------------------------------

Client OS: Mac OS X 10.9.4
Server OS: Mac OS X 10.9.4
Node Version: v0.10.21
Ghost Build Number: 0.5.0 rc1
Latest Commit:
Ghost Database: SQLite3
Browser: Chrome 36.0.1985.125

**Comment by ErisDS** [comment]
We're going to be revisiting all of the image uploading UX somewhere in the near future, so closing these two issues (#3009, #3517) in favour of an overhaul.
