### ISSUE TITLE
Locking of accounts should be based on IP + username

### ISSUE THREAD

**Issue by ghost** [TryGhost/Ghost#3545]
## Summary of Issue 

This is not a bug but more of a feature request.  The company I work for used to do IP based locking of accounts.  We quickly switched to IP + username after several of our internal employees fat fingered their passwords and locked the whole company out.  :) 
## Additional Information 

Client OS: Mac OS X 10.9.4
Server OS: Mac OS X 10.9.4
Node Version: v0.10.21
Ghost Build Number: 0.5.0 rc1
Latest Commit:
Ghost Database: SQLite3
Browser: Chrome 36.0.1985.125

**Comment by ErisDS** [comment]
Closed by #7579
