### ISSUE TITLE
Abstract Admin Transitions

### ISSUE THREAD

**Issue by rwjblue** [TryGhost/Ghost#3584]
I believe that we can significantly improve our our animations by abstracting them a bit (and avoiding `jQuery.animate`).

Take a look at [this demo of liquid-fire](http://ef4.github.io/ember-animation-demo/#/route-transition) a relatively new ember-cli-addon that makes this trivial with Ember CLI (and I'm sure we could leverage this without moving to Ember CLI first).  Liquid Fire uses [Velocity.js](http://julian.com/research/velocity/) (which replaces `jQuery.animate` with a MUCH faster implementation).

IMHO, with a more abstract setup we can handle things (like the bug fixed in https://github.com/TryGhost/Ghost/pull/3535) quite a bit better.

**Comment by ErisDS** [comment]
Is this still an issue post-zelda?

**Comment by kevinansfield** [comment]
There's nothing that's being animated using jquery now as far as I'm aware. If we run into deeper animation requirements (maybe once settings panes are route-driven?) then liquid-fire is a good solution.

**Comment by ErisDS** [comment]
Cool, then I'm gonna close it for now.
