### ISSUE TITLE
Ember route based bodyclasses

### ISSUE THREAD

**Issue by JohnONolan** [TryGhost/Ghost#3792]
We need some special bodyclasses for various view states on the settings ui. Details as follows:

* If route = `/settings/` bodyclass should be `.settings-main`
* If route = `/settings/[thing]/` bodyclass should be `.settings-view`
* If route = `/settings/[thing]/[thing]/` bodyclass should be `.settings-subview`

*See https://github.com/TryGhost/Ghost/issues/3792#issuecomment-53401253 for more specifications*

**Comment by ErisDS** [comment]
@JohnONolan can we close this for now and reopen if we decide it's needed again?

**Comment by JohnONolan** [comment]
yes
