### ISSUE TITLE
First pass on new importer UI

### ISSUE THREAD

**Issue by Ghost-Slimer** [TryGhost/Ghost#3927]
<a href="https://github.com/JohnONolan"><img src="https://avatars.githubusercontent.com/u/120485?v=2" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [JohnONolan](https://github.com/JohnONolan)**
_Wednesday Jun 25, 2014 at 10:39 GMT_
_Originally opened as https://github.com/TryGhost/Ghost-UI/issues/47_

---

This probably needs more discussion / spec. Just a starting point for the UI.

Sketch3 file - http://cl.ly/WFFg

![image](https://cloud.githubusercontent.com/assets/120485/3384127/a9d2e9d6-fc54-11e3-81b1-867aee9de41e.png)

![image](https://cloud.githubusercontent.com/assets/120485/3384132/b333fae2-fc54-11e3-9e68-005aa3db6e7c.png)

![image](https://cloud.githubusercontent.com/assets/120485/3384136/c04693c0-fc54-11e3-92b3-0177572800ec.png)

![image](https://cloud.githubusercontent.com/assets/120485/3384144/d286cde8-fc54-11e3-95dc-8c94b2cbe4db.png)

**Comment by ErisDS** [comment]
Closing this until we decide to prioritise the importer.
