### ISSUE TITLE
Accessibility Testing of Content Editor Page Results 

### ISSUE THREAD

**Issue by JamieKnight** [TryGhost/Ghost#3964]
Hiya Chaps,

I promised Paul a while ago i would take a look at ghost in voiceover to see how it faired. I took a look this evening and it did alright but not too great. I would say its possible to use Ghost in VO (once you figure out the patterns at play) but its not easy. 

I have brain dumped my findings for the content editing page below, i have also done a review of the ghost site account page where you name your account etc.  ~~Where would you like to put those notes?~~ i have emailed those notes directly to Paul.

I'm happy to help fix some of the issues below. Many of them can be fixed with a bit of rejigging and  offscreen text for extra context. If you let me know which issues you want help with, then I will use the time I have to help you tackle those (possibly making a pull request if i can).

Pages:  https://accessibility-test.ghost.io/ghost/editor/1/

- Navigation does not indicate current selected page, so page has not obvious title
- Menu on left if Read as “Avatar {Username}” no indication its an menu for account settings. 
- Focus works correctly when menu is opened, however menu interaction is non obvious. Consider adding ARIA states. 
- Leaving menu into main content does not indicate that editing panel is open. However edit input is read. so the functionality can be guessed at. Consider labelling the the input and hiding the label offscreen.
- “MARKDOWN” text needs more context. Consider writing an off screen introduction to the editor layout / usage. (or a link to a guide which only appears on focus)
- Tags and Post Setting are read correctly and interaction works well.
- Menu on the “Update post” button is not being picked up by voiceover. I'm not entirely sure why, could do with more poking!

The notes above are far from complete, they are just the big things i noticed during about a 30 minute test. I can spend longer looking if you need more input. 

Hope that helps,

Cheers,

Jamie + Lion

**Comment by ErisDS** [comment]
This issue and it's sibling #4010 are now a year old and in that time we have completely rebuilt the UI. I've had a go with voiceover myself and fixed a few issues with skip links, but this isn't my strong suit.

It would be great to have a fresh audit done, and PRs with improvements would also be welcome, but as these particular two issues are now quite out-of-date I'm going to close them.
