### ISSUE TITLE
Open user menu on hover

### ISSUE THREAD

**Issue by JohnONolan** [TryGhost/Ghost#4007]
Top right corner - user menu - let's open that on hover. Should still open on tap for mobile users. I see this as being a common use-case, so a open-on: hover/click option might be best baked into the global dropdown component directly so that it can be re-used. I think click should be the default, and hover the option.

**Comment by peterblazejewicz** [comment]
I'd propose to postpone that feature - it is not a `beginner` task.
The menu in subject has significant importance in user interface - but contrary to other items - it cannot be accessed via keyboard, does not have tabindex feature. __On desktop it probably can be activated only with a mouse - am I correct on this?__ 
https://github.com/twbs/bootstrap/blob/master/js/dropdown.js#L57-L87
If we want to offer a quick way to open it - give it a shortcut for power users via global acceskey attr or keyboard shortcut via JS. (accesskey has a blocker - as this is not interactive element yet as pointed)

**Comment by JohnONolan** [comment]
This has been sitting around for so long without getting traction - time to die, I think.
