### ISSUE TITLE
Mobile Menu Accessibility Improvements

### ISSUE THREAD

**Issue by JamieKnight** [TryGhost/Ghost#4010]
Menu's in general should use ARIA states to indicate when it is open too assistive technology. 

States that may fit are:

* aria-controls, 
* aria-lebelledby
* aria-expanded. 

You can see an example here: http://heydonworks.com/practical_aria_examples/

The new Post Settings Menu should also probably:

* Esc -> close menu, or move back a submenu.
* Focus should move only within the panel (effectively, i think it should be treated like a model box focus wise, see this: http://www.smashingmagazine.com/2014/09/15/making-modal-windows-better-for-everyone/)
* Focus should be pushed to the container which contains the menu when the settings button is clicking
* The settings button should probably have alt text equivalent to "open post settings menu" rather than "settings or cog" etc.

See discussion in #3954 and https://github.com/TryGhost/Ghost/pull/4042 for more details.

Kind regards,

Jamie + Lion

**Comment by ErisDS** [comment]
This issue and it's sibling #3964 are now a year old and in that time we have completely rebuilt the UI. I've had a go with voiceover myself and fixed a few issues with skip links, but this isn't my strong suit.

It would be great to have a fresh audit done, and PRs with improvements would also be welcome, but as these particular two issues are now quite out-of-date I'm going to close them.
