### ISSUE TITLE
Emberify the remaining left over bits of old-admin

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#4019]
In [core/client/assets/lib](https://github.com/TryGhost/Ghost/tree/master/core/client/assets/lib) there are two files which remain as somewhat unloved remnants of the old admin.

These 2 bits of JS need to find new homes inside the ember client, and the `assets/lib` folder needs to die.

Assigning to @novaugust as he expressed an interest in laying these 2 to rest.

**Comment by felixrieseberg** [comment]
Friends, in about a week I wanted to start a boyish journey and fight the evil that is the uploader. Since the issue is fairy old - is everyone (especially @ErisDS & @novaugust) fine with me just getting rid of the lib file and replacing it with a clean ember component?

**Comment by novaugust** [comment]
That is exactly the intention sir!

**Comment by jaswilli** [comment]
Yes, that would be amazing.

**Comment by ErisDS** [comment]
For sure! My one tip to you would be - make sure you do plenty of testing with chrome's throttling turned on. A lot of the crazy stuff in the old uploader was to handle edge-cases on slow connections.

**Comment by felixrieseberg** [comment]
Short update: I'm making serious progress and expect to have a PR out next week.

**Comment by novaugust** [comment]
!

**Comment by jaswilli** [comment]
Nice!  Can't wait.

**Comment by ErisDS** [comment]
I think we can close this now. He remaining uploader component is probably going to be redesigned to suit different workflows better before it gets rebuilt :)
