### ISSUE TITLE
PhantomJS crash during functional tests

### ISSUE THREAD

**Issue by jaswilli** [TryGhost/Ghost#4046]
PhantomJS is crashing every time the functional tests are run in my local development environment which is the Ghost-Vagrant VM, node 0.10.30, and phantomjs 1.9.7.  I've seen one report of it also crashing in a Travis instance, so it's not as frequent in that environment, but it's still an issue.

![screen shot 2014-09-16 at 8 54 00 am](https://cloud.githubusercontent.com/assets/214142/4288217/1d390220-3daa-11e4-878c-453256e8216c.png)

The above is an example of the crash, although it doesn't always occur in the same place.

I've narrowed it down to coming in from #3954, specifically these two lines where listeners are attached to `MediaQueryList` objects:

https://github.com/TryGhost/Ghost/blob/master/core/client/views/application.js#L24
https://github.com/TryGhost/Ghost/blob/master/core/client/views/application.js#L52

**Comment by ErisDS** [comment]
Is this still crashing for people locally?

**Comment by ErisDS** [comment]
Going to close this one for now as not heard of it happening recently.
