### ISSUE TITLE
API endpoints for clients

### ISSUE THREAD

**Issue by sebgie** [TryGhost/Ghost#4175]
This belongs to the OAuth Epic: #4004 - please read this for the big picture of what this issue is for :)

---

Requires #4176

The following API endpoints are needed to make BREAD operations available for clients. These methods are needed for implementing the client management screen (see #4177). The endpoints are very similar to our other implementations and should follow the best practice used there.

- `GET /ghost/v0.1/clients`
- `GET /ghost/v0.1/clients/<id>`
- `GET /ghost/v0.1/clients/slug/<slug>`
- `POST /ghost/v0.1/clients/`
- `DELETE /ghost/v0.1/clients/<id>`
- `PUT /ghost/v0.1/clients/<id>`

Expected response format:
```
{
    clients:[
        {...}
    ]
}
```

**Comment by sgoodwin** [comment]
@javorszky #4174 will be done as soon as it the hold is lifted. If there's anything I can do to help with this one, please let me know?

**Comment by javorszky** [comment]
Wow, I added this comment AGES ago. As the what is lifted though? I didn't catch that, @sgoodwin :)

**Comment by sgoodwin** [comment]
I have a PR to add the necessary table rows that is on hold until later this week or some such: https://github.com/TryGhost/Ghost/pull/4785

**Comment by javorszky** [comment]
Gotcha

**Comment by Deborah-Digges** [comment]
@sgoodwin @javorszky Is someone working on this right now?

**Comment by ErisDS** [comment]
No one is working on this just yet, feel free to pick it up.

**Comment by Deborah-Digges** [comment]
Are there any dependencies for this issue that are still in the pipeline?

**Comment by ErisDS** [comment]
The issue mentioned as required, #4176 - but this can be worked on in tandem.

**Comment by Deborah-Digges** [comment]
Awesome! I'm a little new to the codebase, so could you give me just a few pointers to get started ?

**Comment by ErisDS** [comment]
@Deborah-Digges I recommend swinging by the #dev channel in the Ghost [slack](https://ghost.org/slack) team - that's where contribs hang out - it's much easier to do this sort of thing in chat form :)

**Comment by Deborah-Digges** [comment]
sure @ErisDS - I'll swing by and ask around. Thank you :)!

**Comment by ErisDS** [comment]
This issue is now very much needed - if anyone fancies having a stab. Would be happy to accept partial PRs for one or another endpoint. Being able to browse, edit and add new clients would be great.

**Comment by delgermurun** [comment]
If no one is working on it, I want to give a shot.

Thanks. /cc @ErisDS

**Comment by delgermurun** [comment]
I've just started working on it. Prepared tools and starting dive into code.

**Comment by johnrickman** [comment]
How is this coming along?

**Comment by ErisDS** [comment]
I'm closing all OAuth and most API issues temporarily with the `later` label. 

RE: OAuth, for the next 2-3 months we'll be implementing an official Ghost OAuth login system, providing global access to all Ghost blogs with a single login. We'll be opening issues around this system soon, and I don't want to cause confusion with OAuth for the API.

JSON API Overhaul & OAuth access are currently scheduled next on the [roadmap](https://trello.com/b/EceUgtCL/ghost-roadmap)
