### ISSUE TITLE
Client API permissions

### ISSUE THREAD

**Issue by sebgie** [TryGhost/Ghost#4176]
This belongs to the OAuth Epic: #4004 - please read this for the big picture of what this issue is for :)

---

It is allowed for every authenticated user to add, browse, edit and delete clients. This is similar to what Slack does for integrations and will allow every user to use third party clients. The access to the restful API of Ghost is protected by the individual permissions of each user.

JSON API | Admin | Editor | Author | NoAuth
---------|-------|--------|--------|-------
clients.browse | y | y  | y |  
clients.read   | y | y  | y |  
clients.edit   | y | y  | y | 
clients.add    | y | y  | y | 
clients.destroy | y | y  | y | 

This issue depends on #3910 for adding new permissions to the database.

**Comment by ErisDS** [comment]
Labelling all the open permissions related issues (there are several) with both `permissions` and `later` as I'm working on a spec to solve the immediate issues as well as a long term plan, which will replace all of these issues.

Note: I am aware this is required for OAuth #4004, I am working on a solution that will allow us to resolve this in the short term - at the moment there is no way forward. I'll reopen this as soon as we're able to progress with it.

**Comment by ErisDS** [comment]
I'm not 100% sure about the permissions here.

- `ghost-admin` is supposed to be uneditable as described here: https://github.com/TryGhost/Ghost/issues/4177#issuecomment-162603221
- `ghost-frontend` is editable, but not deletable. It should be edited by admins+ only IMO.

So I'd imagine if I was an admin and I logged in, I'd see a client (connections) screen in my menu and I could click on it. When I click on it, I see an uneditable entry for ghost-admin and an editable entry for ghost-frontend. I can add new entries.

If I'm an editor or author, I can login and see the client (connections) screen, but when I click on it, it is empty. I can add new entries. 

Admins will have access to entries made by editors/authors, but not vice versa.

This allows anyone to connect a 3rd party app, but means that admins have final control.

The resulting permissions table is something more like

JSON API | Admin | Editor | Author | NoAuth
---------|-------|--------|--------|-------
clients.browse | y | y  (created_by == self) | y (created_by == self) |  
clients.read   | y | y (created_by == self)  | y (created_by == self) |  
clients.edit   | y (slug != ghost-admin) | y (created_by == self)  | y (created_by == self) | 
clients.add    | y | y (created_by == self)  | y (created_by == self) | 
clients.destroy | y (slug != ghost-admin || ghost-frontend) | y (created_by == self)  | y (created_by == self) | 

Note: atm created_by === owner. At some point we want to be able to define the concept of "owner" for a particular object, but that's a bigger part of our need to create a whole new permissions system one day.

**Comment by ErisDS** [comment]
I'm closing all OAuth and most API issues temporarily with the `later` label. 

RE: OAuth, for the next 2-3 months we'll be implementing an official Ghost OAuth login system, providing global access to all Ghost blogs with a single login. We'll be opening issues around this system soon, and I don't want to cause confusion with OAuth for the API.

JSON API Overhaul & OAuth access are currently scheduled next on the [roadmap](https://trello.com/b/EceUgtCL/ghost-roadmap)
