### ISSUE TITLE
Make Ember admin work with new access control

### ISSUE THREAD

**Issue by sebgie** [TryGhost/Ghost#4182]
This belongs to the OAuth Epic: #4004 - please read this for the big picture of what this issue is for :)

---

The changes for making OAuth work for external clients are going to cause some updates to how we use OAuth with Ember admin. Ghost admin is a special application as it is the only application that is allowed to use username and password to login directly using the `Resource Owner Password Credentials Grant` (RFC 6749 - 4.3).

To keep the Ember admin working correctly, we will need to update the values for new fields created in #4174:

- `client_id`: generated random number
- `redirection_uri`: null
- `trusted_domains`: null (if the client is of type `Ghost Admin` the url from config.js should be used)
- `logo`: Ghost admin logo
- `status`: enabled
- `type`: Ghost Admin
- `description`: tbd

In addition to that, the `client_id` needs to be available to the admin. This could be done similar to how we make fileStorage settings available. Authentication needs to be updated to use the new `client_id` as well.

**Comment by ErisDS** [comment]
This is already complete
