### ISSUE TITLE
Default client entry for Ghost frontend

### ISSUE THREAD

**Issue by sebgie** [TryGhost/Ghost#4184]
This belongs to the OAuth Epic: #4004 - please read this for the big picture of what this issue is for :)

---

This requires #4180 in order to work. 

To make life for theme developers a bit easier it would be nice to add a default entry into the `client` table for the Ghost front end. A theme developer would be able to use the pre populated `client_id` to implement custom JavaScript functionality. 

To allow JavaScript access out of the box for themes a new client entry would have to be added during migration.

**Comment by patrickdbakke** [comment]
Potential implementation [here](https://github.com/patrickdbakke/ghost-angular).
This implements the casper theme on an angular app. Because open oauth isn't yet available, it does depend on [some workarounds](https://github.com/patrickdbakke/ghost-spa/tree/feature/public_REST_API).

**Comment by ErisDS** [comment]
@patrickdbakke I think you may have misunderstood what this issue is about? I've updated it to make it a little clearer.

**Comment by ErisDS** [comment]
This was completed by d215983 / #5706
