### ISSUE TITLE
Filter Posts by Title

### ISSUE THREAD

**Issue by Juev** [TryGhost/Ghost#4215]
[Post Filter Menu](https://github.com/TryGhost/Ghost/issues/2640) considering the possibility of filtering on the status of the article (published, draft). 

I propose to implement the ability to filter the articles by title. 

At the moment I have more than 200 articles, and if there is a need to make changes, it is difficult to find the desired article. If, however, will be able to filter according to the title, it would greatly simplify the work in the Ghost Admin.

**Comment by ErisDS** [comment]
I'm going to close this issue in favour of [this item on the wishlist](http://ideas.ghost.org/forums/285309-wishlist/suggestions/7185549-admin-search-with-advanced-operators). Adding search and filtering to the admin are something we fully intend to work on in the future although it is stuck on #306 (one of the oldest open issues) - and when we come to getting stuck in we'll open spec issues here on GitHub.

**Comment by Juev** [comment]
Ok, Thank you!
