### ISSUE TITLE
Offer to unpublish welcome post after a period of time

### ISSUE THREAD

**Issue by JohnONolan** [TryGhost/Ghost#4284]
One thing I see very often with Ghost blogs around the web (WordPress blogs too, actually) is that people are happily blogging away, but they never actually delete the initial "Welcome!" post. So it just sits there at the bottom of their feed, looking all ugly and shit.

It would be great UX if we could help the user out by nudging them towards getting rid of this post after a certain period of time. Eg:

**If the user has published at least 1 post, and their blog was created more than 1 week ago, but the welcome post still exists:**

Pop up a notification saying:

> Hey! It looks like you still have the "Welcome to Ghost" post cluttering up your blog. Would you like to convert it to a draft, so it's no longer public? [[Yep, unpublish it]](#)

**Comment by ErisDS** [comment]
@JohnONolan would you like to prioritise this or shall we close?

**Comment by kirrg001** [comment]
I've quickly talked to @JohnONolan. People can delete the welcome post. Closing 🙃
