### ISSUE TITLE
Make /settings/user adapter hit /api/users/:slug to fetch a user

### ISSUE THREAD

**Issue by novaugust** [TryGhost/Ghost#4350]
From `core/client/routes/settings/users/user.js`
```js
// TODO: Make custom user adapter that uses /api/users/:slug endpoint
// return this.store.find('user', { slug: params.slug });

//What we're doing instead is..
 // get all the users and then manually find by slug
 return this.store.find('user').then(function (result) {
     var user = result.findBy('slug', params.slug);
     return user;
 }
```

And actually, if you have a large number of users and haven't loaded all of them when you go to users/user, default pagination (15?) means that this perhaps won't find the user? Is this a bug waiting to happen?

**Comment by ErisDS** [comment]
Closing this as there was no consensus on what to do: https://github.com/TryGhost/Ghost/pull/4440#issuecomment-84379109
