### ISSUE TITLE
Drop CodeMirror from the Editor

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#4368]
With reference to the [Split Screen Editor Epic (#1294)](https://github.com/TryGhost/Ghost/issues/1294)

--- 

The Ghost editor undeniably needs some :heart:. No matter how you consider what the editor might look like in the future, there is one underlying problem - to ship improvements like spellcheck, we need to build a completely custom editor, that's an enormous undertaking, and it would detract from all the other features we want to ship :-1:.

That is, unless we drop formatting/syntax highlighting from the left side of the editor :boom: 

**yep**... I'm talking about dropping CodeMirror in favour of a plain textarea.

CodeMirror currently has two main jobs: 1) it formats/syntax highlights the markdown and 2) provides an API for interacting with the entered text. However, what it does under the bonnet is generate a completely custom representation of the document which is neither markdown or HTML. This breaks the [browser spellcheck](https://github.com/TryGhost/Ghost/issues/1240), doesn't work reliably [on mobile/touch](https://github.com/TryGhost/Ghost/issues/960) (which meant we had to remove it from mobile/touch devices), and the way it interprets markdown is quite different to our HTML conversion, which causes [weird](https://github.com/TryGhost/Ghost/issues/959) [bugs](https://github.com/TryGhost/Ghost/issues/1909) and adds complexity.

If we strip out CodeMirror, we will lose formatting, but what we get instead will be an editor with working **spellcheck**, working **mobile uploads** and significantly reduced complexity: because we only have two document representations - markdown and HTML, and we are in control of them both. This means we can focus on making the conversion between them better (i.e. adding advanced markdown features).

In the future, we'll be able to bring back formatting if we want it using contenteditable, but in the meantime we can more easily focus on the features we want to bring to the editor, the markdown we want to support, and creating our own way of modelling documents - because the editor is so significantly less complicated.

I've been working on a prototype testing out how to interact with selections in the textarea to make sure that image uploads will still work (on ALL devices) etc and to me this feels like taking back control, and I'm REALLY, _**ridiculously**_ excited about it.

**Comment by nhannb** [comment]
Could you consider [medium-editor](https://github.com/daviferreira/medium-editor)? It basically has all the common features to replace CodeMirror (except syntax highlighting), plus it's easy to use while still maintain the clean look of the current design
