### ISSUE TITLE
[Discussion] Improving our development process

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#4396]
Lately, we've been trying out new things with our development process in order to get a bit more fluid (agile) and move towards releasing little-and-often instead of dropping great big releases every few months. Some of this has gone really well (we're releasing more stuff faster) and some of it hasn't necessarily (I don't feel like the process is particularly clear). So I'd like to get some feedback on ideas on how to get better at doing what we do.

I have the following goals:

- Make sure the what and why of our short and mid-terms priorities are clear
- Ensure that our current contributors are happy that our processes are working well
- Encourage more new contributors to get stuck in & make it easier for them to do so

To aid the conversation, below is a little bit of an overview of the way we work:

---

- We have a public meeting in the #ghost IRC channel on Tuesday every week at 5:30pm London time, to discuss progress and what's next.
- Our **public roadmap** is on [Trello](https://trello.com/b/EceUgtCL/ghost-roadmap) and is 100% feature-focused. The `Backlog` column is a list of things we want to do one day (for v1.0), `Next` is for things that are ready to work on and we want to get into a release, and `In Progress` is for things which are actively being worked on.
- We have 3 [GitHub milestones](https://github.com/TryGhost/Ghost/milestones) we use as **issue backlogs**: `Current` which contains the 'top 10' priority items for the next release, `Next` which contains everything else that is ready to be picked up and worked on, and `Future` which contains other tasks we're tracking but that are blocked on something else.
- The roadmap and backlog are curated by those with admin access (Ghost Foundation + Core Team members), but mostly by @JohnONolan and me, based on a mix of user demand and what is technically possible / ready to implement.
- We don't *really* have a long term plan of when things should ship, just a general idea of what we need to do to get to 1.0
- We have a **blocker** tag which we use when we start thinking about doing a release for anything preventing a release going out, or anything super-duper high priority to get fixed.
- We have a **beginner** tag to mark issues suitable for developers who are new to the Ghost codebase
- We have a **help wanted** tag to mark issues we'd love someone to come and get involved with
- We **release** whenever we feel ready, and I usually give an indication of when that will be in the dev meeting & blog post (currently I'm still the only person able to do this).

---

Some ideas to get us started:

- Overhaul the contribution guidelines with a TL;DR, more links to wiki pages on process and how to get started (I've started this a couple of times and not been happy with the results.)
- Overhaul the Ghost wiki to focus (even) more on being a contributors/developers manual
- Figure out the best approach to documenting the code base and push forward with making it a reality
- Start publishing job spec type listings on Ghost.org advertising for contributors to certain areas (like OAuth, Search, i18n)
- Revitalise the wiki Roadmap page to have more detail about high priority items which are not features so are not on the public roadmap, but are blocking features (like permission migrations) 
- Have a 'Road to 0.6' type write up either in the roadmap or in an Epic issue itemising the bare minimum features / refactors / bugs / etc we'd like to get in before we're ready to call Ghost 0.6, their dependencies and any other relevant info
- Do a big write up of the long term plan for Ghost 1.0

---

I'm very, VERY interested to hear feedback and new ideas. This is going to be pretty much all personal opinion, so in the interest of keeping the discussion positive, productive and awesome, please try to qualify your ideas and concerns by telling us about your workflow and how the processes do or don't fit in.

**Comment by raulfelix** [comment]
In terms of process I have often worked within variations of agile. I have used Jira as an issue tracking tool many times and one of the great things about it is that it really easy to see tasks that are in progress.

I have been trying to get started/involved and managed to find out about the beginner label being used through reading the getting started guide but where I have spent a lot of time confused now is knowing if an issue has been started on by someone. Perhaps a rule that you must **assign** the issue to yourself once you begin on it is in store to clearly show progress? An example of this would be this issue #4596

**Comment by novaugust** [comment]
The problem with assigning people is, they have to be a member of the
TryGhost organization. We can't assign issues to just anyone who comes
along, unfortunately :/

**Comment by raulfelix** [comment]
Ohhh right... of course. It then becomes a management issue for someone then.

**Comment by ErisDS** [comment]
I'm gonna close this now as feedback has dried up. I'm working on cleaning up the issue list, using the tags `beginner`, `fix wanted` and `in progress` to try to make it easier to find stuff that can be worked on and closing all the issues which have been around and stuck for ages.

We have since moved our community from IRC to slack and there you can find both a #dev channel for discussing core development issues, including getting help with contributing and also a #help channel for general Ghost issues. There's also an #i18n channel for discussing that project and a #themes channel for sharing themes and talking about theme development.

I'm always interested in feedback on how we can improve the contributor process so if anyone has ideas please post here or come chat in [slack](https://ghost.org/slack)!
