### ISSUE TITLE
HTTPS + Subdirectory mount causes Ghost to be inaccessable

### ISSUE THREAD

**Issue by JoshWillik** [TryGhost/Ghost#4434]
# Problem Code
```
// Check to see if we should use SSL
// and redirect if needed
function checkSSL(req, res, next) {
    if (isSSLrequired(res.isAdmin)) {
        if (!req.secure) {
            var forceAdminSSL = config.forceAdminSSL,
                redirectUrl;

            // Check if forceAdminSSL: { redirect: false } is set, which means
            // we should just deny non-SSL access rather than redirect
            if (forceAdminSSL && forceAdminSSL.redirect !== undefined && !forceAdminSSL.redirect) {
                return res.sendStatus(403);
            }

            redirectUrl = url.parse(config.urlSSL || config.url);
            return res.redirect(301, url.format({
                protocol: 'https:',
                hostname: redirectUrl.hostname,
                port: redirectUrl.port,
                pathname: req.path,
                query: req.query
            }));
        }
    }
    next();
}
```
# Reproducing conditions
In order to get to the problem code, `isSSLRequired` must return true. This will happen if `config.url` includes `https`.
Next, req.secure must be false. This can happen when the blog is set up behind a reverse-proxy. Without a few configuration lines, express does not trust that the connection is secure. See fix 2 below.

Then you get to this line:
```
            redirectUrl = url.parse(config.urlSSL || config.url);
            return res.redirect(301, url.format({
                protocol: 'https:',
                hostname: redirectUrl.hostname,
                port: redirectUrl.port,
                pathname: req.path, //<- PROBLEM
                query: req.query
            }));
```

If the site is mounted on a subdirectory, like `/blog`, the `req.path` for `/blog/ghost` is just `/ghost`.
To fix this, just substitute `req.path` for `redirectUrl.path`.

**HOWEVER**, this causes another problem if the nginx misconfiguration still exists. In that case, the request will end up back in this handler, and the whole thing will loop again.

# The Solution
## Fix 1
Set the `pathname` correctly on the problem line (pull request coming soon)
## Fix 2
The parent app of the Ghost Instance **must** trust the reverse proxy, so set `app.set( 'trust proxy', 'localhost' )`. (or the IP of the reverse proxy)
Once that is done, make sure the proxy is setting `X-Forwarded-Proto: https` when the request is passed to the NodeJS app.

**Comment by panchr** [comment]
I have a similar issue.

When using Ghost as an NPM module in Express, I have the following code (simplified):

```js
ghost({config: path.join(__dirname, "settings", "ghost.config.js")})
.then(function (ghostServer) {
app.use("/blog", ghostServer.rootApp);
ghostServer.start(app);
});
```

However, I reverse-proxy to my Express website using Nginx. If `config.production.url` is set to use something like `https://domain.com/blog`, I get a permanent redirect to `domain.com`. Changing it to just use `http://domain.com/blog` works fine, though. Not really sure why.

**Comment by CallumHemsley** [comment]
@panchr I have exactly the same problem right now. Any fix since then?

**Comment by Egrace** [comment]
@CallumHemsley I have the same problem and working on a solution. If you found it, please, share it here.
