### ISSUE TITLE
Build the permalinks UI as an ember component

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#4484]
This is split from the permalinks epic: #1631

---

The custom permalink UI has been built out in HTML, CSS with some mock JS which you can [find here](https://github.com/TryGhost/Ghost/blob/master/core/client/html/permalinks.html).

![](https://cloud.githubusercontent.com/assets/120485/2731445/bef43b3e-c62c-11e3-979f-9afc39bfd3ff.png)

**Please note:** As this is a complex feature depending on a couple of issues to wrap it up, the UI should be added behind a config flag, something like `permalinksUI: true`.

## How this UI should work

(Taken From https://github.com/TryGhost/Ghost/issues/1631#issuecomment-63340350)

* With certain keys such as a comma (final to be determined), the current value of the input is taken and added to the permalink structure
* Pressing backspace in an empty input deletes the last parameter
* gif's are worth a thousand words

![permalinks](https://cloud.githubusercontent.com/assets/390392/5073973/2eab79d4-6e7e-11e4-9e2e-0a84be63338d.gif)

## In detail

We need to be able to interact with this component in a few different ways:

* typing url-valid chars (a-z, A-Z, 0-9, _ and -) should result in them being added to the current 'url part'
* typing a terminator (space, comma, `/`, tab or enter) should result in the current url part being ended and a new one begun (please note this needs to be done in a [locale-sensitive](https://github.com/TryGhost/Ghost/issues/4356) way.
* typing a special tag should allow users to enter an item of dynamic data such as `:slug`, `:id`, `:year`, `:month`, `:day` or `:author`. What the special tags will be (i.e. will it be `%y` or `:year` or something else) is still to be tested out and decided so this ought to be easily configurable in the code.
* pressing backspace should delete the entirety of the current url part as shown in the gif.
* typing any other character not supported by the component should probably result in nothing happening?
* The component should stop allowing input once 5 url parts have been added (see #1631 for full details of what is valid)

Also, the URL in the component should be the blog's real URL

**Comment by ErisDS** [comment]
Closing along with #1631 (https://github.com/TryGhost/Ghost/issues/1631#issuecomment-146625068) - we will revisit this in future in line with demand / priority.

**Comment by Tyriar** [comment]
@ErisDS Any movement on this issue? Seems pretty essential for those who want to migrate from Blogger without losing their page rank.

**Comment by ErisDS** [comment]
@Tyriar there are ways to work around the lack of UI. Custom permalinks are possible by editing the DB / emailing Ghost(Pro) support if you're a customer. The remaining bits that aren't supported like `.html` on the end of a URL can be mitigated with 301 redirects without loss of pagerank. If you need help migrating, pop into the #help channel on [slack](https://ghost.org/slack) and we can walk you through the process :smile:
