### ISSUE TITLE
RSS feed incompatible with readers

### ISSUE THREAD

**Issue by ledestin** [TryGhost/Ghost#4524]
Hi,

Just upgraded to 0.5.5 and checked rss feed in Readkit and Miro. Both don't show any content.
Here's feed: http://isntabook.mooo.com/rss/

Ghost version: 0.5.5
Client OS: OSX 10.9.5
Server OS: Debian 7.7
Node version: v0.10.29

**Comment by ErisDS** [comment]
I'm going to close this against #3993 and more importantly #2263 for now, as there is no clear indication of what's wrong here, we just know we need to start over with our RSS :)
