### ISSUE TITLE
Manage the Navigation Menu Setting / Data

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#4539]
This is part of the Navigation epic: #4535, and requires #4537 

--- 

![image](https://cloud.githubusercontent.com/assets/120485/5228785/917b5448-7717-11e4-9b1d-1e24a48e5729.png)

The list of navigation items should be stored as a JSON object in the settings table. 

This means creating a new [default setting](https://github.com/TryGhost/Ghost/blob/master/core/server/data/default-settings.json) called `navigation` with the type `blog`.
It should have one default item: "Home" - pointing at the root URL, which will be stored as just `/`.

On save, the values from the interface should be serialized into a JSON object and saved via the settings API.

The JSON object needs to contained ordered name and url pairs, something like:

```
{[
    {name: 'Home', url: '/'}
]}
```

* Pressing the `+` button should add another new row / item
* Pressing the save button should save all the rows which are not blank 
* Pressing the trash icon should remove the row / item
* Drag and drop reordering is dealt with in  #4540

I think the base URL should be stripped from the start of each URL when it is stored, so that we only store relative paths (and the navigation continues to function if the URL changes). If the URL doesn't start with the base URL, then we store and use the absolute URL.

**Comment by jaswilli** [comment]
@ErisDS 

I was just re-reading this issue and realized that I (mis)read "Pressing the + button should add another new row / item" to mean that the `+` **key** should add a new row.  I think your well-known love for keyboard shortcuts must have influenced me :wink: 

Anyway, just wanted to note this here since it might not be the desired behavior.

**Comment by novaugust** [comment]
Ha, it's pretty fun behaviour though ;) Would be nice to have "enter" work
as well eh?

**Comment by jaswilli** [comment]
Definitely.  `Enter` makes more sense to me than `+`.  It's not like "but what if I want a "+" in my label/url didn't occur to me, either. Oh well.

**Comment by lemur3** [comment]
Having a + would be good within the URL/label as I do add links to my google+ pages on some sites.
