### ISSUE TITLE
Post Settings Menu: Cmd/Ctrl + S doesn't save date or slug

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#4556]
There are still a few bugs with the post settings menu saving with cmd/ctrl + s. 

This is because (I think) the properties aren't explicitly set in the editor controller's save method? I believe it would be good to do something to make this behaviour require less manual wiring. Perhaps implement a save method on the PSM controller that gets called by the editor controller.

It might be good to abstract out the concept of 'scratch' properties as well, again to reduce the amount of manual wiring.

### Steps to Reproduce

1. Open the PSM
2. Change the date or slug, but don't focus out of the field
3. Press cmd/ctrl + s
4. Reload the editor
5. Notice your changes are lost

### Technical details: 

* Ghost Version: master

**Comment by ErisDS** [comment]
This is still an issue in Ghost 0.7.1 - it'd be great to look at resolving it, perhaps along with #5777 and #5062. @kevinansfield is it perhaps worth putting together a plan for an overhaul of the PSM?

**Comment by kevinansfield** [comment]
Just had a quick look at this. I think short-term solution is to capture <kbd>Ctrl-S</kbd> in those inputs and perform the necessary actions. If we call those actions on the main `save` action then any resulting validation errors will be hidden if the PSM isn't visible when they are called which isn't a good user experience.

Long-term I think both the current PSM concept and the `scratch` values/general data flow in the editor need overhauling. The PSM as it stands strikes me as a bit odd as it's in a bit of a weird middle-ground where changing image, slug, author, or meta data all immediately save but publish date, tags and feature toggles are only saved when the main Save button is hit.

**Comment by ErisDS** [comment]
This sounds sane to me. I agree that the PSM is a bit of a mix-and-match for how it works and needs to be unified / overhauled to work in a consistent way.

The short term fix also sounds like a good plan, I run into this one quite often, but not sure if it's just cos I'm a cmd+s-aholic
