### ISSUE TITLE
Remove findAll where findPage exists

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#4577]
This is a cleanup task. Following on from #4573, findPage supports `limit=all` and therefore the findAll methods can be removed from the models where findPage is present (posts, tags and users).

This will involve refactoring the [delete all content](https://github.com/TryGhost/Ghost/blob/master/core/server/models/index.js#L44) feature and anywhere else where those methods are being used.

**Comment by delgermurun** [comment]
I sent PR on it #5909
