### ISSUE TITLE
Allow multiple underscores inside a code block

### ISSUE THREAD

**Issue by givanse** [TryGhost/Ghost#4592]
If I do this indside a **code block**:

```
____
&#95;&#95;&#95;&#95;
```

The output is:

```
&#95;&#95;&#95;&#95;
&#95;&#95;&#95;&#95;
```

Might be related: https://github.com/TryGhost/Ghost/pull/1552

**Comment by anavarre** [comment]
To make sure I understand this issue, is what's happening such as below:

```
[my_link](https://mylink.tld)
```

Displays as `mylink` instead of `my_link`?

The only I've found to overcome that is to escape the underscore.
