### ISSUE TITLE
[Feature] Post Preview Links

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#4595]
This is partly a follow on from a discussion that was originally had on PR #4398.

----

To start with, the problem we want to solve. There are two slightly different use cases here:

1. Users commonly want to view a version of their post that has their theme and all of their embeds enables so that they can see what the finished product is going to look like.
2. Users commonly want to share a post with a few trusted people to get feedback before publishing.

My suggestion for how to solve both of these cases is to make draft posts visible on the frontend of the blog by accessing a URL something like <blogurl>/preview/:uuid: - the UUID is a 36 character random id which is globally unique and **completely unguessable**. 

This URL should only work whilst the post is a draft, once published this URL should 301 to the proper URL. The preview route should add the private cache control header rule that we use for the admin and API, so that this page is never, ever cached as well.

This is the same as how previews work on many publishing platforms, including: https://draftin.com/, https://exposure.co/ and https://roon.io/. 

The main argument that has been raised against this is that if you or someone you share the preview with accidentally post the link somewhere public, then anyone can see the post, which may not be desirable. I believe that the kind of complex sharing system we'd need to build to combat this would be an enormous pre-optimisation for a limited edge-case. Anyone who really doesn't want the previews can turn them off by modifying their theme, and eventually via apps.

However, I do suggest that we clearly mark previews as previews using something like a ribbon, red bar or red icon which warns the user they are reading a preview.

**Comment by balintant** [comment]
By default, our drafts should not have preview links. We should set them up under the url menu in Post Settings with the following options:
- Copy Link
- Generate Link / Regenerate Link
- Revoke Access

After that if the post have been published, it would reset the link automatically to `null` and it is not accessible anymore

**Comment by tidyui** [comment]
Another way of implementing this (slightly more complex) is to add a new "reviewer" role to the admin. You could then add users that you want to review your unpublished content, send them the link to your page with some form of flag (i.e `?mode=preview` or something) and force them to log in before viewing the preview.

The downside to this approach would of course be that it would take more effort to send a one-time preview link to a person that you might not send a preview to again.

**Comment by nuclearpengy** [comment]
I don't think I'd(*personally*) opt for the "reviewer" role method, as I feel it ads a bit more complexity to the workflow; I would not be adding additional users to my blog just to take a sneak peak at one of my posts.

It might have some valid use cases in the online magazine industry or when it comes to journalists, but in those cases the users reviewing the content would probably have other roles like "editor" within the system anyway.

My personal take is having an extra step in the workflow which users could choose to skip if they wanted: 'draft' => '**preview**' => 'published'

All draft posts = 100% private - login required
All preview posts = visible to users who know the unique UUID based URL
All published posts = 100% public - no login required, post appears in the sitemap.

**Comment by tidyui** [comment]
I like that approach @nuclearpengy. The `status` field is a varchar anyway so adding another status wouldn't require any data changes, and it simplifies the workflow. The only reason for using the role-based approach would be if you wanted to continue building an advanced review workflow where reviewers could comment on unpublished posts and you would like to know who is actually reviewing (if you have several reviewers). But this feels like total overkill.

**Comment by nuclearpengy** [comment]
@tidyui yeah, when you put it that way, it would be possible to emulate the workflow in place on *Medium* (cough).

Author writes post, enables preview mode, reviewers are then able to comment on the posts or sections within the post, spot typos etc and provide feedback. The Author can then action these comments prior to publishing.

Reviewers could then be "credited" in the footer of the posts as "contributors" or something like that.

That would be quite cool for business blogs or even larger publications.

**Comment by tidyui** [comment]
Exactly @nuclearpengy, that was the future functionality I was thinking about. But then again, it's quite an advanced workflow and your suggestion does the trick until something more advanced is desired. 

Even then, the workflow with three different states applies, you could just add the validation functionality to the preview mode and add functionality in the admin where you would invite reviewers to comment on your post.

**Comment by nuclearpengy** [comment]
Authentication for "preview" URLs could probably be enabled/disabled as a labs feature.

So the code could ship with "preview" requires authentication(secure by default) or it could be shipped as "preview" does not require authentication(visible by default) and allow the users to adjust this as a global setting.

I don't think I'd go so far as to say each post should have "public preview" or "private preview".

Although, it could be that we have the three post states and the author can invite people do be "contributors". (using contribute as "comment" should probably be reserved for what readers would do once it's published).

Then if the contributor get's an invite they would need to sign up and create an account.

They would only be able to contribute to posts they were invited to contribute to, so it would be:

* does user have permission to contribute to this post?
* does user have the UUID based URL to access the post in the first place?
   * if yes to both => allow contribution

This workflow might be better suited to a plugin/app though, as it could start to get super complex in terms of variations and options also the "contributions" received would need to be channelled to the author in a logical way that make it easy to process and action.

**Comment by chilts** [comment]
I'm +1 on the `/preview/<uuid>` for previews (for all draft posts). Also +1 on redirecting from there to the real post once published. I was also going to suggest the ability to regenerate the `uuid` if a user accidentally pastes their preview URL to a public forum (same as @balintant ).

I'm -1 on the ability for a reviewer role/editor to auth in and suggest changes - there are already better ways to collaborate on text markup.

**Comment by ErisDS** [comment]
The discussion on this issue lead us to rethink the always-on public preview URL. I'm now closing this in favour of #5097, which is essentially the same thing but which defaults to private and has a public/private switch.
