### ISSUE TITLE
Expired editor session 401 on save has unhelpful error message

### ISSUE THREAD

**Issue by novaugust** [TryGhost/Ghost#4596]
## Issue Summary

If your session expired on the editor and you attempt a save, the error is reported as Unknown Error. Worse, you're going to be prompted to leave/stay because of the unauthed redirect. Staying, however, won't let you save your work.

## Reproduction Steps

1. Edit a post
2. Expire your token (could someone with more DB knowledge than me give steps for this? @sebgie)
3. Save your post
4. Worthless error

## Specs

Latest Chrome,
Ghost Pro 0.5.6

I'm not sure much can be done about the modal; I'd consider this issue solved if the 401 just showed a more helpful "You aren't logged in" error message. Because of that, I'd call this a beginner issue, eh?

**Comment by ErisDS** [comment]
I don't think this is a problem now that #3492 is in? Seems like the reauthentication flow is working quite nicely now.
