### ISSUE TITLE
Create Settings-Menu-Component to DRY up settings menu interactions

### ISSUE THREAD

**Issue by novaugust** [TryGhost/Ghost#4642]
The settings menu outlet is currently used by the post-settings-menu and tags editor. They're sharing a large amount of code between them to manage its state, and there's a lot of duplicated html to properly draw things out.

This needs drying up with a component!

More details to come; just wanted an issue to ref from the master issue.

**Comment by ErisDS** [comment]
*cough*

**Comment by novaugust** [comment]
Is this... did I... is this assigned to someone? AHEM

**Comment by novaugust** [comment]
ErisDS, have you heard of this new zelda thing that is happening? this should probably be closed until that happens :D
