### ISSUE TITLE
Test coverage reports

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#4644]
For a while we had working a working `grunt test-coverage` task, which produced a nice test coverage report using blanket.js. I think I might have been the only person who used it, and now it doesn't work :( It makes it very hard to see where tests are missing, which is a shame because adding a missing test is a great way for new contributors to get stuck in.

All I want for Christmas, is working test coverage :santa: 

I don't mind whether it uses blanket or another tool.
I don't mind whether it only works via grunt, or whether it's also wired up to Travis.

I would like it to work for as much of our test suite as possible. I don't expect it to work for the casper tests, but everything in `test/unit/`, `test/integration/`, `test/functional/module/` and `test/functional/routes/` uses mocha so should hopefully be ok. `test/client/` also uses ember-mocha - not sure if this can use the same coverage tool though.

It is also important that the wiring in the Gruntfile is done so that the `grunt test-coverage` command will execute on Windows (but requiring globally installed npm modules is OK - mocha is required I think).

**Comment by ErisDS** [comment]
Hey @jat850 how is it going? 

I've been playing with [istanbul](https://github.com/gotwarlost/istanbul) and [grunt-mocha-istanbul](https://github.com/pocesar/grunt-mocha-istanbul). In my opinion the reports generated by istanbul are a little more intuitive to use, I think that's probably quite subjective, but grunt-mocha-istanbul is very very easy to configure and has a nice event hook we can use to send the data to CodeClimate (see #2029).

Might be worth switching over?

I realise there are underlying problems in the tests that need fixing first though :)

**Comment by jat850** [comment]
@ErisDS - I was actually evaluating the same thing myself, before I rabbit holed into tests themselves :) I think it's a great idea to implement them.

I have 2 more tests (making 3 out of the 4) passing now, and with the 4th, we should have a working coverage report in blanket, but that'll free up conversion to istanbul very easily. I fuddled with a pull request towards the end of this week but couldn't quite get it figured, so tomorrow I may need your help (or if/when available).

**Comment by ErisDS** [comment]
@jat850 hit me up in IRC whenever :)

**Comment by jaswilli** [comment]
For what it's worth, the errors you're seeing are because the `ensureConfig` task needs to be run before the tests are kicked off.

**Comment by jat850** [comment]
@jaswilli That seemed to make a difference, but in recent testing I'd been using the Gruntfile with test-coverage and it (at least on inspection) seems to run the ensureConfig task. I continue to get timing related results that appear to maybe expose race conditions of some kind.

**Comment by ErisDS** [comment]
@jat850 Can you update us on what you've found? I know you've looked into this extensively, and at one point I think you had a fix for at least some of the problems? It'd be great to get this resolved :)

**Comment by ErisDS** [comment]
@jat850 wanted to ask again if you could please report back on the work you did? I'm looking into this and would rather not start from scratch if there is something I can pick up and work with
