### ISSUE TITLE
Whitespaces at the end of codeblocks

### ISSUE THREAD

**Issue by programster** [TryGhost/Ghost#4659]
It appears that if one uses three lots of the tack quote to enter a code block

```
sudo apt-get install \
python2.7 \
python-imaging \
python-mysqldb \
python-setuptools \
python-simplejson \
-y
```

and then copy the code from the rendered page, many of the lines have trailing whitespaces. This "breaks" the multiline command which is meant to be executed in BASH. However, if you wrap the code with "pre" and "code" tags then it works fine but looks messy as you have to start and end the code on the same line. I have checked that the whitespaces appear in the html when one clicks "view source" which appears to be the issue.

In case it's related, I am using a [customized Vapor theme](https://github.com/programster/Vapor).

**Comment by Dids** [comment]
Any news on this issue?
