### ISSUE TITLE
Publish Options not shown on Windows Phone Lumia 520 

### ISSUE THREAD

**Issue by rahulmr** [TryGhost/Ghost#4713]
Publish Options not shown on Windows Phone Lumia 520 
Environment:
Ghost 0.5.7
Self Hosted
Nokia Lumia 520
Website: http://rrahul.ga (may not be useful :) )
Scenario:
1. Login with user
2. Create new post and write some content and title.
3. Publish button is not available, can only see tag icon. Menu is available and also message when user tries to leave the page is available.
Save Draft, Publish Post, etc and other post options like make page, featured, etc are not available.

**Comment by ErisDS** [comment]
@PaulAdamDavis is this something that can be fixed, or does it reasonably count as using an out of date browser?

**Comment by rahulmr** [comment]
Update : I recently updated my  Windows Phone OS to latest version and the issue is no more reproducible

**Comment by PaulAdamDavis** [comment]
Thanks for the update @rahulmr :) Good to know it's not reproducible now.

I think we can close this for now. If there's any more reports like this, we can reopen this issue and investigate.
