### ISSUE TITLE
Bug: Editor Interface word count includes comments & Markdown syntax

### ISSUE THREAD

**Issue by Z1MM32M4N** [TryGhost/Ghost#4714]
### Issue Summary

The editor interface's word counter doesn't count words accurately. It measures the number of space-delimited tokens instead of the number of actual words.

### Steps to Reproduce

1. Create a new new, blank post
2. Enter the following text

   ```markdown
   <!-- This is a comment -->
   ## This is a test header
   ```
3. Observe the text "12 words" in the editor panel
4. Observe that there are only 5 words in the post.

This is a bug because especially in posts with large HTML comments (i.e., when leaving notes between editor and author), this count is incredibly skewed. Also, the Markdown "##" is being counted as a word in this example, which also skews the word count.

**Comment by jaswilli** [comment]
Closed via #4877
