### ISSUE TITLE
Feature: Dashboard

### ISSUE THREAD

**Issue by PaulAdamDavis** [TryGhost/Ghost#4736]
The Dashboard will eventually be the first screen you see when you log into your blog. It will show stats, trends and anything else you want to be there, enabled by apps. In the [initial visual concepts](https://cloud.githubusercontent.com/assets/390392/5580277/0a729a0a-9040-11e4-903d-91ca6966973f.jpg) of the Dashboard had Apps in mind, but we’re not there yet.

The first steps towards having a fully functioning dashboard are creating the foundations. It looks deceptively simple, but behind the scenes, there’s lots happening. Though we don’t need all of these in the first steps, they should be accounted for to ease development when there’s more happening.

* Drag & drop widgets (which includes touch screens)
* Display a settings screen for individual widgets
* Be vertically *and* horizontally flexible
* Show dynamic data (text, graphs, images)

I have done an experimental WIP PR #4382 which is a first pass as the base markup structure with drag & drop, but it’s by no means perfect. [It doesn't look great either.](https://cloud.githubusercontent.com/assets/390392/5580280/1e603108-9040-11e4-857c-94ff1a74a71a.png)

## The First Version

The first version of the Dashboard that’ll ship will be simplified, only showing a set number of standard widgets. What goes there, how it looks and how it works is all up for discussion.

**Comment by ScottSmith95** [comment]
I think we can safely close this issue and remove the [related Trello card](https://trello.com/c/FznXvPBJ/29-dashboard-v1), following [today's announcement](http://blog.ghost.org/year-2/#thedashboard).

**Comment by Chris92de** [comment]
Rest in peace :(
