### ISSUE TITLE
Open Graph data URLs are using "http" protocol always

### ISSUE THREAD

**Issue by JuanKRuiz** [TryGhost/Ghost#4739]
Open Graph data URLs are using **"http"** protocol doesn't matter that website is over **"https"**.

I have my Ghost blog published on [https://juank.io](https://juank.io) but when I look at OG meta tags they are linking to **http://** Urls.

I have configured iisnode (Azure) to redirect http request to https without problem. But redirections are bad indicators for twitter cards or facebook posts causing (sometimes) images won't be loaded.

Specially in facebook this redirect issues could rank down the post on timeline.

I'm not sure if this issue is related to Ghost or Azure related. Temporarily I have tweaked 
ghost-head.js to construct OG data using https insted of http.

**Comment by cobbspur** [comment]
Hi Juan,

So far I have not been able to reproduce this. It may be related to azure which I will investigate further but first can I just check one thing with you. In your config.js file have you set url to https?

**Comment by JuanKRuiz** [comment]
Hi @cobbspur and @ErisDS EriDS ,
I've been reviewing this a little bit more.

My site is already configured in **https** but browser is getting TOO_MANY_REDIRECTS because there are a infinite redirection loop caused by this code in 
core/server/middleware/index.js
````
function isSSLrequired(isAdmin) {
    var forceSSL = url.parse(config.url).protocol === 'https:' ? true : false;
    
    var forceAdminSSL = (isAdmin && config.forceAdminSSL);
        
    if (forceSSL || forceAdminSSL) {
        return true;
    }
    return false;
}

// Check to see if we should use SSL
// and redirect if needed
function checkSSL(req, res, next) {
    if (isSSLrequired(res.isAdmin)) {
        if (!req.secure) {
            var forceAdminSSL = config.forceAdminSSL,
                redirectUrl;

            // Check if forceAdminSSL: { redirect: false } is set, which means
            // we should just deny non-SSL access rather than redirect
            if (forceAdminSSL && forceAdminSSL.redirect !== undefined && !forceAdminSSL.redirect) {
                return res.sendStatus(403);
            }

            redirectUrl = url.parse(config.urlSSL || config.url);
            return res.redirect(301, url.format({
                protocol: 'https:',
                hostname: redirectUrl.hostname,
                port: redirectUrl.port,
                pathname: req.path,
                query: req.query
            }));
        }
    }
    next();
}
```` 

Looks like

````
var forceSSL = url.parse(config.url).protocol === 'https:' ? true : false;
```` 
Is **returning true** when site is already running on **https**, but if ghost  is already configured to run over **https** and IIS is redirecting http traffic to https there's no need to redirect again.

I suggest the right valitation could be.

```` 
//if site is already running over https there is no need to forceSSL
var forceSSL = url.parse(config.url).protocol === 'https:' ? false:true;
```` 

On IIS you configure a website to run over https with this rule in web.config file:

```` 
        <rule name="Force HTTPS" enabled="true">
          <match url="(.*)" ignoreCase="false" />
          <conditions>
            <add input="{HTTPS}" pattern="off" />
          </conditions>
          <action type="Redirect" url="https://{HTTP_HOST}/{R:1}" appendQueryString="true" redirectType="Permanent" />
        </rule>
```` 

So because of that my current blog **config.js** is configured `forceAdminSSL: false`
----
Actually **isSSLrequired** method execution looks like
````
function isSSLrequired(isAdmin) {
//forceSSL = true;
var forceSSL = url.parse(config.url).protocol === 'https:' ? true : false;
//forceAdminSSL = false;
//true && false = false
var forceAdminSSL = (isAdmin && config.forceAdminSSL);

//true || false = true
if (forceSSL || forceAdminSSL) {
    ///TRUE    
    return true;
    }
    return false;:
}
````

That method reponse is causing that `checkSSL` method redirect url over **https** even if url is already over **https**.

For test purposes I've changed the code in my own repository and looks everything is working ok.

I don't know Ghost blog deeper in code, so my solution couldn't the best one any lights?
