### ISSUE TITLE
Excerpt on front page omits/cuts off sentences with links

### ISSUE THREAD

**Issue by jbfriedrich** [TryGhost/Ghost#4741]
It looks like the excerpt of blog posts on the front page gets confused and omits/cuts off words after it encounters a link. This is the text I wrote in my latest blog post: 

![Blog post editor](https://cloud.githubusercontent.com/assets/1968991/5590794/47d52754-9140-11e4-84e8-e08fee1fdfa4.png)

The excerpt on the front page looks like this:

![Front page excerpt](https://cloud.githubusercontent.com/assets/1968991/5590798/654a8234-9140-11e4-9034-5a2a3e12ee99.png)

If I remove the link from the first sentence in the first paragraph, everything works as expected. I am using Ghost 0.5.7, self-hosted, NodeJS 0.10.33.

**Comment by aminozuur** [comment]
Hello, I have this issue. Links are not displayed on the front page, only on the post page. I am not sure which steps to take to fix this. Any help is welcome :)
