### ISSUE TITLE
Unicode Url ends in loop

### ISSUE THREAD

**Issue by wzrdtales** [TryGhost/Ghost#4751]
Hi there,

 I just tried to setup ghost on an url that use punycode.
It ends up in redirecting for forever.

Is there an option to disable the url redirect?

**Comment by wzrdtales** [comment]
Ok I have looked a bit into the code and found the following test:

https://github.com/TryGhost/Ghost/blob/8df98b4f7dbb635c44834ad516db7ae3e5a97a32/core/test/functional/routes/admin_test.js#L114

Next looked up the documentation for this config parameter.
http://support.ghost.org/config/

Ok...

First I looked if setting forceAdminSSL to { redirect: false } has any effect.
Yes it has, but now I can't access the blog and get forbidden, so I tried setting urlSSL manual in some variants. With punycode, without punycode, with \u for unicode chars. Nothing made it to work.

Finally I discovered if set the url to http:// instead there is no redirecting and nginx will do the redirect instead.

**Comment by ErisDS** [comment]
Hey there @wzrdtales, Sounds like you got this working? Sorry that no one replied, but for future reference, the [forum](https://ghost.org/forum) and irc are often better for getting answers to support-type questions.

**Comment by wzrdtales** [comment]
@ErisDS 

More or less. 

If you have an URL like "xn--myoddchrs-12a2ra.com", ghosts ends up in an infinite redirection loop. My solution was more like abusing some configuration tweaks.

So I've got this working for me by the following way.

First I define in the config of thost the url only without https like:

    url: 'http://test.xn--hohnerklnge-marl-2nb.de',

Then I setup nginx to redirect all http to the equivalent https address.

This is working, but it's far from a solution as it can be.

**Comment by wzrdtales** [comment]
@ErisDS And acutally I think this is a bug in ghost, not only a support case.

**Comment by ErisDS** [comment]
@wzrdtales in that case, could you please provide us with detailed info on how to reproduce the problem? There's a handy bug template in our [contributing guidelines](https://github.com/TryGhost/Ghost/blob/master/CONTRIBUTING.md#bug-reports) that provide some tips.

At the moment it's not clear to me whether this is a punycode issue, or one of the SSL issues that we recently fixed (0.5.9 I think)?

**Comment by wzrdtales** [comment]
It's a punnycode issue. 

```
GET / HTTP/1.1
Host: xn--myoddchrs-12a2ra.com
User-Agent: Mozilla/5.0 (Windows NT 6.2; rv:30.0) Gecko/20100101 Firefox/30.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Connection: keep-alive

HTTP/1.1 301 Moved Permanently
Server: nginx/1.6.2
Date: Sun, 22 Mar 2015 10:48:16 GMT
Content-Type: text/html; charset=utf-8
Content-Length: 138
X-Powered-By: Express
Location: https://xn--myoddchrs-12a2ra.com/
Vary: Accept, Accept-Encoding
X-Firefox-Spdy: 3.1
```

Ghost is not able to recognize that it has the real url and keeps relocating, I suspect it is not handling the unicode url right. 

I will upgrade to the latest version and see if this still happens.

**Comment by wzrdtales** [comment]
Yes it does still happen.

To reproduce, setup a punnycode url in your /etc/hosts file, or the windows one. For example  `xn--myoddchrs-12a2ra.com`

Setup ghost and use a https url together with the punnycode url, like the following:

    url: 'https://xn--myoddchrs-12a2ra.com',

Try visiting the ghost blog and getting redirected forever.

**Comment by ErisDS** [comment]
HTTPS only works if you have the proper configuration using something like nginx: http://support.ghost.org/setup-ssl-self-hosted-ghost/.

Does it work without HTTPS?

**Comment by wzrdtales** [comment]
I'm aware of this...

https is working fine, if it wouldn't I wouldn't be even able to get the answere on the https url which is redirecting.
Also for non punny code urls https works fine. And as described above, the only way to "fix" is yet to tell ghost it should use non https in the configuration and let nginx redirect instead.

**Comment by wzrdtales** [comment]
@ErisDS 
Also to take a look at the code:
https://github.com/TryGhost/Ghost/blob/00ec9e569f5b60a4d16cbf486f0e0a0e9fcb392b/core/test/functional/routes/admin_test.js#L110-L124

There is a possibility to disable redirection, but only for the admin area.

Fortunately I had some time right now, to debug this with the following result. This seems to be an upstream failure with express.

The following property is always false, if we're using a punny code url:
https://github.com/TryGhost/Ghost/blob/00ec9e569f5b60a4d16cbf486f0e0a0e9fcb392b/core/server/middleware/middleware.js#L310


Debug log:

```javascript
debug> watch("req.secure");
debug> cont
< - - - [22/Mar/2015:12:38:23 +0000] "GET / HTTP/1.0" 301 138 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:36.0) Gecko/20100101 Firefox/36.0"
break in core/server/middleware/middleware.js:309
Watchers:
  0: req.secure = false

 307     // and redirect if needed
 308     checkSSL: function (req, res, next) {
>309         if (isSSLrequired(res.isAdmin, config.url, config.forceAdminSSL)) {
 310             if (!req.secure) {
 311                 var response = sslForbiddenOrRedirect({
```

**Comment by wzrdtales** [comment]
@ErisDS Also this issue should be reopend as it is still an existing bug?
