### ISSUE TITLE
Why can't I use / in a permalink?

### ISSUE THREAD

**Issue by RoderickLindsberg** [TryGhost/Ghost#4756]
Hi! I switched to ghost from wp and my old link is something like this:
http://domain.com/31-12-2014/post
and I don't wanna break it so I created a new post on ghost, copy the content, and finally entered "31-12-2014/post" at "post URL" for the permalink of this post. However, I got http://domain.com/31-12-2014post.
It automatically removed the "/". How can I use a "/"?
Thanks!

**Comment by iBotPeaches** [comment]
Because `/` has special meaning. In WP it seems you did `/date/title` for your permalinks. You can include dates in the permalinks via Ghost settings & then title the post as "post". I don't know why you would call the post "post", but then it would have the structure of `http://domain.com/04-01-2014/post`.

**Comment by RoderickLindsberg** [comment]
Thanks for the reply!
The name "post" is just a example, actually my url is http://roderick.lindsberget.se/2014-05-07/the-untapped-power-of-redefining-a-book-review-of-twilight/
And with ghost I can only compromise it like http://roderick.lindsberget.se/2014/05/07/... Thus it would break the formal link.
I just used Nginx to implement a redirect and now the new url is SEO friendly

**Comment by iBotPeaches** [comment]
Yes for now, nginx/apache redirects are required to maintain the redirect from old to new. Glad you got it working. The roadmap shows "Custom Permalinks" In Progress here: https://trello.com/c/kwiC3ljz , so in the future you will be able to do so.

**Comment by RoderickLindsberg** [comment]
Thanks for your help!
