### ISSUE TITLE
Change Request: Bring "themePath" into config.

### ISSUE THREAD

**Issue by rchrd2** [TryGhost/Ghost#4760]
I found the need to separate the `themes` directory (or `themePath` in the code) from the `content` directory. In my case, I am installing Ghost via NPM, and my project directory looks like this:

```
/themes
   /casper
config.js
index.js
package.json
```

I don't want to keep `content` in my repository, because that is dynamically updated on the server, but I do want to keep `themes` in my repository, because that is where I edit the ui of my site.

I found that this change was pretty easy to implement, and I already have it working in a fork. You can see a comparison of the branches here <https://github.com/rchrd2/Ghost/compare/TryGhost:master...master>. I only modified three lines.

While, I found it useful to customize `themePath`, it might be even better to allow all paths to be configured (ie `apps`, `data`, `images`). I can't think of a specific use case, but why not solve this in a general way?

Either way, I can submit a pull request for my `themePath` if that seems okay. I think others might want to make this same change. What do others think?

### Example Config.js
```
...
      url: 'http://example.com',
      mail: {},
      database: {
          client: 'sqlite3',
          connection: {
              filename: path.join(__dirname, '/shared/content/data/ghost.db')
          },
          debug: false
      },

      server: {
          host: '0.0.0.0',
          port: '5000'
      },
      paths: {
          contentPath: path.join(__dirname, '/shared/content/'),
          themePath: path.join(__dirname, '/themes')
      }
  },
...
```

**Comment by miskun** [comment]
Yes, please!

**Comment by jaswilli** [comment]
I'm going to close this as there doesn't seem to be much going on either for or against this.  If anyone has more to add to the discussion we can re-open.

**Comment by craig-mulligan** [comment]
@jaswilli I've forked `0.11.4` and applied changes as @rchrd2 has done. My use case is similar. I want scale-able docker instances of the blog that share a common volume (where `data`, `images`,  `apps` are stored and then themes are kept in normal source control. 

I think it makes sense to make all paths configurable with sane defaults. I considered submitting a PR but I see there is a lot of rework in related to the config module in `1.x` pre-release, so wanted to check in first.

**Comment by kevinansfield** [comment]
> I want scale-able docker instances of the blog

@craig-mulligan ghost is not designed to run across multiple instances, there is quite a bit of in-memory state and you'll run into weird issues if you are attempting to load balance across multiple instances. The best thing to do is to have the single blog instance and have a proxy/cache in front that can handle the origin server being unavailable by sending the cached content.
