### ISSUE TITLE
Infinite scroll in Posts list dead on large monitors

### ISSUE THREAD

**Issue by martinnormark** [TryGhost/Ghost#4764]
Posts list infinite scroll dead on large monitors. Discovered on a 30" monitor running 2560x1600 resolution.

### Issue Summary

Unable to load next batch of posts in the posts list inside admin, when browser is larger than the initial 15 items.

### Steps to Reproduce

1. Make sure there's more than 15 posts in the list. I tested with 20. It doesn't matter if they're all draft.
2. Resize your browser to a window height greater than 1500px
3. Go to [http://localhost:2368/ghost](http://localhost:2368/ghost) to see the posts list 
3. Try to scroll the posts list

When trying to scroll the posts list, nothing happens.
I would expect the list to load the next batch of posts into the list.

![posts-list-dead-scroll](https://cloud.githubusercontent.com/assets/67565/5637891/a1251d40-9600-11e4-9661-348608c6cd46.gif)

A workaround is to resize the browser windows for vertical scroll to appear, and then scroll the list again to load up the next batch of posts.

![workaround-posts-list-dead-scroll](https://cloud.githubusercontent.com/assets/67565/5637898/b0799b18-9600-11e4-82af-eeee216ec78d.gif)

### Technical details:

* Ghost Version: master (latest commit: 04180bc83b5e99947d1c3820e3032c62e82a08c2)
* Client OS: Mac OS X 10.10.2
* Server OS: Mac OS X 10.10.2
* Node Version: 0.10.35
* Browser: 39.0.2171.96 & Chrome 41.0.2251.0 dev
* Database: SQLite

**Comment by novaugust** [comment]
An easier way to reproduce this is to just zoom out as far as possible; that way you don't need the massive screen :) Thanks for the great writeup @martinnormark

**Comment by martinnormark** [comment]
@novaugust You're welcome!

I never thought about zoom. I guess you can also change display mode on retina macs to the scaled option, or whatever it's called. Although, it might still be short of the required 1500px height.
