### ISSUE TITLE
User signup validation is broken

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#4766]
If you try to signup an invited user on master, you get a bunch of validation errors as if you didn't fill out the form:

![](http://puu.sh/ec3X1.png)

### Steps to Reproduce

1. Log in to Ghost and invite a new user
2. Log out of Ghost
3. Click the link in the new user invite email
4. Fill out the form and hit Create Account

### Technical details: 

* Ghost Version: master , introduced since 0.5.7

**Comment by ErisDS** [comment]
This is an odd one - it is not affecting `setup` or `signin` - I was thinking it might have something to do with #4748 but I can't see what's different on this one controller.

**Comment by jaswilli** [comment]
It's #4748.  The `ValidationEngine` mixin assumes it's being used with things that are no longer directly "gettable" once those controllers are no longer proxying. There are also a few other bugs related to shuffling that data around stemming from the same change.

I'll fix it up.

**Comment by ErisDS** [comment]
If this is not simple to fix, perhaps it would be worth reverting to use a ObjectController for the signup controller until we can resolve it in a better way?

**Comment by jaswilli** [comment]
It's not too bad. A little bit of fixing one thing causes another issue to pop up but it's manageable.

Mostly I just haven't looked at it since that first day, but I'll wrap it up this weekend.

**Comment by ErisDS** [comment]
Cool, just thinking if it does turn out to be a rabbit hole it's worth PRing the quick revert-fix for now. Really hoping to ship a release before the next meeting :)
