### ISSUE TITLE
Bug: Imports from a Ghost installation: Imported 'Owner' account login not permitted, gives incorrect error message.

### ISSUE THREAD

**Issue by lemur3** [TryGhost/Ghost#4778]
### Issue Summary
When importing data from a Ghost installation (Blog Old) to a different install of Ghost (Blog New) and then logging out of the Blog New admin account on Blog New a user attempting to log back in to Blog New with the (different) account details for the imported "Owner" account from Blog Old is given an error message saying that the account is "Locked due to too many login attempts.", urging them to use the Forgotten Password link, even though this account has never attempted a log in before on this new installation of Ghost. When user follows through with password reset the account works fine.

### Steps to Reproduce

Export Ghost settings and data from one Ghost install, import into a different installation.

Log out of Ghost on the installation which the data was imported into.

Attempt log in with account credentials contained in imported data and settings, see incorrect error message.

![screen](https://cloud.githubusercontent.com/assets/7681885/5681762/3c897f94-97e9-11e4-86cc-84ef5b1d0a2a.png)

### Expected behavior 

User is given correct error message explaining why they are unable to log in. Or, user is able to log in to imported accounts without any issues when importing from another Ghost installation. If password reset is required on import, a call to action.

### Technical details

* Ghost Version: Release 0.5.7
* Node Version: 0.10.25

**Comment by ErisDS** [comment]
@lemur3 Thanks for the bug report. When an import is performed, any imported user account is locked. Although the message isn't quite accurate with regard to there being 'too many login attempts', it is correct in so much as the user needs to use the reset password flow to gain access.

However, it sounds like the main bug here is something slightly different. Can you please clarify the following details:
- Are you logging out of, and then logging back into the same account?
- Was there only one account on Blog New when you performed the import?
- Does Blog Old contain a user with the same email address as the owner on Blog New? If so, is the user on Blog Old also the Owner?

**Comment by lemur3** [comment]
* One account on both blogs, each with a different email address and password, both 'Owner'
* Logging out of the 'Owner' account created upon install of the 'New' blog (destination of import).
* Logging to import destination in using imported user account details from the 'Old' blog.

**Comment by ErisDS** [comment]
Ok cool, that's exactly how I would expect it to work. You're creating a new account through an import, so it will require you to do the password reset. 

The only thing is the message saying 'due to too many login attempts.'  - we can remove that part of the message and it should work for all forms of account locking.

**Comment by lemur3** [comment]
Good to know that this is the expected way for it to work. I hadn't noticed it in any documentation so I wasn't sure.

Though, perhaps not a bug, and more of a general change request, notifying users (in some way) that imported accounts may be locked by default on import would be good. Informing them that their account is locked only when they try to log in is not as graceful as I imagine Ghost should be.

**Comment by ErisDS** [comment]
@lemur3 that's a very valid point, but is also the exact reason why this feature lives on the labs page, and doesn't have it's own home yet - it isn't up to the same standard as other parts of Ghost just yet ;)
