### ISSUE TITLE
RTL Languages

### ISSUE THREAD

**Issue by Rezaaa** [TryGhost/Ghost#4791]
Can i translate ghost to rtl languages? like farsi?

**Comment by ErisDS** [comment]
Hi Rezaa, welcome to Ghost's GitHub. We use GitHub as an issue tracker for features and issue with the software itself. We have a [forum](https://ghost.org/forum) for general questions.

Ghost doesn't have any support for being translated into any language yet. You can find details on our [roadmap](https://trello.com/c/YomMBGO2/47-localisation-multi-lang-i18n).

**Comment by Rezaaa** [comment]
@ErisDS when ghost want add rtl style support? can i do that?

**Comment by ErisDS** [comment]
@Rezaaa you may find this interesting: https://ghost.org/contribute/i18n-lead/
