### ISSUE TITLE
Error 255 when upgrade the ghost

### ISSUE THREAD

**Issue by vinllen** [TryGhost/Ghost#4795]
Hi, all:
I upgrade the ghost from 0.3.3 to 0.5.8 according the document given by http://support.ghost.org/how-to-upgrade/
1.Download the latest version of Ghost from Ghost.org
2.Extract the zip file to a temporary location
3.Delete existing index.js and package.json then copy new index.js and package.json files to the same directory.
4.Next, delete the old core directory completely, and then put the new core directory in its place.
5.For releases which include update to Casper (the default theme), delete the old content/themes/casper directory and put the new one its place
6.Run npm install --production
7.Finally, Restart Ghost so that the changes take effect

Then, when i use "npm start" to start my ghost, there is an error happen, here is log:

ghost@0.5.8 start /home/xiaohuolu/blog
node index
Migrations: Database upgrade required from version 000 to 003
Migrations: Creating database backup
Migrations: Database backup written to: /home/xiaohuolu/blog/content/data/vinllen-chens-blog.ghost.2015-01-13.json
Migrations: Running migrations
Migrations: Creating table: permissions_apps
Migrations: Creating table: apps
Migrations: Creating table: app_settings
Migrations: Creating table: app_fields
Migrations: Creating table: clients
Migrations: Creating table: accesstokens
Migrations: Creating table: refreshtokens
Migrations: Adding column: tags.image
Migrations: Adding column: tags.hidden
Migrations: Updating fixtures
Migrations: Upgrading fixtures
Migrations: Adding client fixture
Migrations: Adding owner role fixture
Migrations: Upgrading permissions
Migrations: Populating permissions
Migrations: Removing old permissions
Migrations: Converting admin to owner
Migrations: Populating default settings
Migrations: Complete

ERROR: (Code: EACCES) 
There was an error starting your server. 
Please use the error code above to search for a solution.

npm ERR! weird error 255
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm ERR! not ok code 0

Thanks for anyone's reply

**Comment by ErisDS** [comment]
Hi there @vinllen, sorry to hear you're having trouble. As this is an installation / upgrade question, please could you move it to our [forum](https://ghost.org/forum/installation/)?  We use GitHub as an issue tracker for developers.

Thank you :+1:

**Comment by vinllen** [comment]
OK,sorry
