### ISSUE TITLE
{{next_post}} and {{prev_post}} helpers

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#4799]
This requires #4262 (there is an open PR #4772)

---- 

With the addition of the ability to fetch the next and previous post via the API, we need to make it possible for theme developers to access this functionality.

The [{{#get}}](https://github.com/TryGhost/Ghost/issues/4439) helper provides one avenue for doing this, something like:

```
{{#get "posts" id="current-post-id" include="next,prev"}}
    {{#prev}}<a href="{{url}}">{{title}}</a>{{/prev}}
    {{#next}}<a href="{{url}}">{{title}}</a>{{/next}}
{{/get}}
```

However, that's a little unintuitive for a feature like this (which is highly requested and likely to be used by a large number of people). So it makes sense to provide a slightly nicer set of helpers.

`{{next_post}}` and `{{prev_post}}`

As each of these will fetch all of the properties of a post, they'll need to work as a block helper:

i.e. `{{#next_post}}}<a href="{{url}}">{{title}}</a>{{/next_post}}` and `{{#prev_post}}}<a href="{{url}}">{{title}}</a>{{/prev_post}}`. 

Each helper will need to determine the current post ID, make a query to the API to fetch the data, and then ensure the data is provided such that helpers like `{{title}}` and `{{url}}` will work correctly inside the block.

**Comment by ErisDS** [comment]
See https://github.com/TryGhost/Ghost/issues/4439#issuecomment-74743522 for a note on why this issue is currently blocked.

**Comment by mankittens** [comment]
Would like to hear your thoughts on making `include =  'next,previous'` the *default* behavior.

ref: https://github.com/TryGhost/Ghost/blob/master/core/server/controllers/frontend.js#L352

```javascript
-   postLookup.include = 'author,tags,fields';
+   postLookup.include = 'author,tags,fields,next,previous';
```

Would allow theme creators to address next and previous posts like so:

```handlebars
{{#post}}
...
    {{#next}}
        <a class="next-post" href="{{url}}">Next: {{title}}</a>
    {{/next}}
    {{#previous}}
        <a class="prev-post" href="{{url}}">Previous: {{title}}</a>
    {{/previous}}
...
{{/post}}
```

**Comment by cobbspur** [comment]
Hi @mankkittens,

Thanks for asking the question, this goes back to open discussion from ages ago, if I can pick out the issue I will post it up here for you to take a look. The general feeling was that is would not be right to force this into default behaviour.

We have been waiting for a change with express handlebars to enable us to handle this the way we want. Now that has happened I have a PR waiting in the wings, just adding tests at the moment but it's nearly there and you will then be able to use {{#prev_post}}{{title}}....etc{{/prev_post}} inside the post template much as you show there :)

**Comment by mankittens** [comment]
Makes sense. Thanks for the explanation!
