### ISSUE TITLE
Bug: Strange behaviour for User Roles

### ISSUE THREAD

**Issue by MitchOnAStick** [TryGhost/Ghost#4800]
### Issue Summary

Hi. Apologies if this has been fixed in the master branch - I skimmed the search results and couldn't see a matching issue posted.

So, every time I go into Settings > Users, the Role will always default to Administrator, even if they are saved as something else. Yet, if I make an amendment to another field and save, it doesn't pick up the Administrators selection on the Users page.

### Steps to Reproduce

1. Log into Admin.
2. Go to Settings, then Users.
3. Choose any user (ideally a non-admin) and click.
4. Note their Role compared to what displays on the User page.
5. Make amendments. Save.
6. Recheck Users page.
7. Repeat 4-6.

### Animated Proof

![ghost bug final](https://cloud.githubusercontent.com/assets/9639417/5731382/9db63930-9b7a-11e4-812f-86201fac624d.gif)

### Technical details

* Ghost Version: 0.5.8 Release
* Client OS: OSX Yosemite 10.10
* Server OS: CentOS7
* Browser: Chrome 39.0.2171.95 / Firefox 35.0

**Comment by halfdan** [comment]
I can confirm this. Will PR a fix in a few.
