### ISSUE TITLE
Upgrade to 0.5.8 breaks autofill of date in new post?

### ISSUE THREAD

**Issue by benheb** [TryGhost/Ghost#4803]
I upgraded to 0.5.8 yesterday and now the date input is empty on new post creation instead of auto populating to current date/time. Anyone else seeing this? Or an issue with my update? 

![editor_-_weather5280](https://cloud.githubusercontent.com/assets/910495/5741620/74d8904a-9bc9-11e4-8202-1943515e48bb.png)

**Comment by halfdan** [comment]
The published date doesn't seem to show up even for published posts. I'll look into it.

**Comment by benheb** [comment]
:+1: Thank you.

**Comment by Trendy** [comment]
**_Just a note:_**

It doesn't appear that a new installation is affected. This might be related to upgrading.

**Comment by halfdan** [comment]
Ok. I don't really know how that happened but it seems to work now.

 @benheb Can you try clearing your browser cache? I am assuming that an old version of ghost.js was still in your cache.

**Comment by benheb** [comment]
Appears to have done the trick. Thanks! Closing.
