### ISSUE TITLE
is the valid url check too fussy?

### ISSUE THREAD

**Issue by gilesbradshaw** [TryGhost/Ghost#4805]
in config.js if i have a url of for example http://acomputernamer:81/ it kicks it out.
I commented out the url validate check in core/server/config/index.js and it seems to work fine with that url (it''s just running on my pc in a home network). so could it be relaxed so as not to need a .com or whatever?

**Comment by ErisDS** [comment]
Hi @gilesbradshaw, this has been discussed before, have a read of #4481 and feel free to join the conversation there :)
