### ISSUE TITLE
Github README.md content renders differently within Ghost

### ISSUE THREAD

**Issue by conradwt** [TryGhost/Ghost#4806]
Hi, I created a step by step tutorial here:

```
https://github.com/conradwt/cassandra-example-using-rails
```

However, when I copy the text of the README.md, it doesn't render similar to the Github.com.  The most noticeable thing that I noticed is that code blocks are not using a bigger block when they are the content of a list item.  Is there an easy way to resolve this issue?

**Comment by ErisDS** [comment]
Hi @conradwt - I'm sorry, I don't really understand what you're saying here. It sounds like you might be talking about a difference between markdown in GitHub and Ghost?

Please can you update this issue to explain step-by-step how to reproduce your problem? You can find a handy template for bug reports here: [contributing guidelines](https://github.com/TryGhost/Ghost/blob/master/CONTRIBUTING.md#bug-reports)

**Comment by ErisDS** [comment]
I'm going to close this for now, but it can always be reopened if someone can provide a reproduction case that shows this is a problem with Ghost.
