### ISSUE TITLE
Add support for io.js

### ISSUE THREAD

**Issue by stojanovic** [TryGhost/Ghost#4811]
At this moment Ghost works only with Node v0.10.x.

    "engines": {
        "node": "~0.10.0"
    },

**Comment by jgable** [comment]
What is the status of Travis CI supporting io.js?  I'd vote for waiting to put it in until it was able to be tested with the same rigor as the node engine.

**Comment by jaswilli** [comment]
> What is the status of Travis CI supporting io.js

Support for io.js needs to land in nvm before it can be used on Travis-CI.

Extending what @jgable said, io.js is (obviously) really new, and there's going to have to be a bit of lag while tooling catches up and the dust settles.  At the point when we can easily install it we'll be able to give it a shakedown and see what kind of issues we have with our dependencies, ES6 feature conflicts, etc.

**Comment by halfdan** [comment]
As it stands right now the sqlite3 dependency won't build with io.js. Unless the dependencies work properly with io.js there's barely anything we on Ghost can do to support io.js.

**Comment by stojanovic** [comment]
@halfdan You're right, but it seems it'll be fixed soon mapbox/node-sqlite3#385.

**Comment by vohof** [comment]
:+1:

**Comment by tiefenb** [comment]
+1

**Comment by halfdan** [comment]
Supposedly travis is going to ship a new version of nvm with io.js support on Tuesday. Happy to pick this up and add io.js to the builds. Which, I think, for now should be an allowed failure. Suggestions?

**Comment by stojanovic** [comment]
@halfdan it seems travis is ok now: http://docs.travis-ci.com/user/build-environment-updates/2015-02-03/#io.js-support.
What about node-sqlite3? It works with io.js fine, but travis and appveyor needs to be updated and of course they need to merge pull request etc.

**Comment by Julyyq** [comment]
+1

**Comment by halfdan** [comment]
Sadly they rescheduled the update. Got the PR ready just waiting for Travis to push the change again.

**Comment by vohof** [comment]
:+1:
