### ISSUE TITLE
Rendering Tweet url

### ISSUE THREAD

**Issue by RuiAAPeres** [TryGhost/Ghost#4813]
On medium when I am writing a blog post and I leave a tweet link, when I preview the post, the link will render a tweet will all its information, does Ghost have the same?

**Comment by Trendy** [comment]
It does not. I think this functionality lands in the realm of an add-on, though.

**Comment by felixrieseberg** [comment]
The good news is that even without addons, embedding a tweet is fairly simple, since Ghost/Markdown fully support HTML. Click on "Embed Tweet" in Twitter and simply copy the HTML into your post.

![image](https://g.twimg.com/dev/documentation/image/embedded-tweet-menu-item.jpg)

**Comment by RuiAAPeres** [comment]
Excellent point @felixrieseberg thanks! :+1:

**Comment by runspired** [comment]
This "works" in that you will see the tweet as a block quote, but you won't get the twitter card or media.
