### ISSUE TITLE
Bug: Input Area is too small, doesn't scroll in mobile

### ISSUE THREAD

**Issue by Trendy** [TryGhost/Ghost#4814]
### Issue Summary
When editing a post on mobile (see technical details for my specific use case) the input area becomes small and does not scroll properly. This causes the input text to become hidden under the action bar, and makes it difficult to author anything on mobile. Related to #2815 and still present in #4373.

![screenshot_2015-01-17-08-52-17](https://cloud.githubusercontent.com/assets/3655670/5789068/097937fc-9e29-11e4-9c0b-47069d1be589.png)

![screenshot_2015-01-17-08-54-57](https://cloud.githubusercontent.com/assets/3655670/5789067/0978c646-9e29-11e4-845e-3023ab06159d.png)

### Steps to Reproduce

1. Login to ghost from your mobile phone.
2. Create a new post
3. Input more than 2 lines of text

This is a bug because it makes mobile editing difficult and cumbersome.

### Technical details

* Ghost Version: 0.5.7 & 0.5.8 (with new editor http://editordemo.ghost.io)
* Client OS: Nexus 5 - Android 5.0.1
* Browser: 39.0.2171.93 (Android)

**Comment by josenberg** [comment]
How this could be solved?

**Comment by lyonz** [comment]
We should make the text input decrease after you have inserted the header text.

**Comment by ErisDS** [comment]
I'm going to close this for now, as I think it's more likely that the interface will be reworked before we have a chance improve this. Plus it's very device dependent - my iPhone 6 gives me the whole text area as a screen.
