### ISSUE TITLE
update nodemailer to v1.x ?

### ISSUE THREAD

**Issue by davehorton** [TryGhost/Ghost#4817]
For my own purposes I am intending to update my fork to use nodemailer 1.0.  Any reason that I should consider not doing so?  Alternatively, any interest in a PR if I do so?

**Comment by ErisDS** [comment]
Hey there @davehorton: take a peek here #4125 :wink:

**Comment by davehorton** [comment]
ah thx!

**Comment by jaswilli** [comment]
@davehorton 

I closed that issue because we didn't really need an open issue just sitting there in case someone wanted to upgrade to nodemailer 1.x, not because we're not interested in upgrading.

If you'd like to do the work that upgrading requires by all means open a PR for it. :+1:
