### ISSUE TITLE
Using insecure Urls despite forceAdminURL being set

### ISSUE THREAD

**Issue by markstos** [TryGhost/Ghost#4819]
This comment considers the near-identical logic which appears in these three places:

```
core/server/api/authentication.js:49:                var baseUrl = config.forceAdminSSL ? (config.urlSSL || config.url) : config.url,
core/server/api/users.js:48:        var baseUrl = config.forceAdminSSL ? (config.urlSSL || config.url) : config.url;
core/server/api/mail.js:88:                siteUrl: config.forceAdminSSL ? (config.urlSSL || config.url) : config.url
```

In all cases, if `forceAdminSSL` is set but `urlSSL` is not, an insecure Url will be used, when the configuration option clearly requested to force SSL. 

Why not update the validation of `config.forceAdminSSL` to require that  `config.urlSSL` also be set if `config.forceAdminSSL` is set?  Then all three locations above could be simplified to definitely  use `config.urlSSL`  when `config.forceAdminSSL` is set, instead of returning an insecure Url when the config requested that secure one be forced.

**Comment by jaswilli** [comment]
But if `forceAdminSSL` is set, a redirect will be issued in the event that a request comes in on a non-https link.  The "forcing" of SSL isn't necessarily by way of providing an SSL URL, it's in forcing the connection itself to be SSL.

I believe the intended use for `urlSSL` is if the secure URL differs from the non-secure URL, e.g., `http://my-ghost-blog.com/` vs. `https://secure.my-ghost-blog.com/`.  If the only difference is in the protocol, a standard redirect will suffice and `urlSSL` isn't needed.

I'm going to close this but if anyone has more to add feel free to do so and I'm happy to re-open.
