### ISSUE TITLE
Wish: Better diagnostics when unsupported NODE_ENV is set

### ISSUE THREAD

**Issue by markstos** [TryGhost/Ghost#4825]
If `NODE_ENV` happens to already be set to an unsupported value, several `grunt` command will fail to work, with no indication of what the problem is. This could happen to potential contributors who checking out the project, but happen to have a different `NODE_ENV` value already set via `.bashrc`. (That was my case). 

Here's what the failure looks like:

```
$ grunt express:dev
Running "express:dev" (express) task
Starting background Express server
Stopping Express server
```

You you can try explicitly setting `NODE_ENV=boom` to see what happens.

Ideally a diagnostic would be printed in this case like `NODE_ENV=boom` is not supported.`

**Comment by jaswilli** [comment]
Agreed.

The code to output an error in this situation is actually already in place.  I think it stopped working at some point as a result of a side-effect in how the error logging module is configured, combined with some refactoring of the Ghost bootstrapping process.

The error handling in the bootstrap process as well as the filtering in those logging methods should probably given a once-over to fix up issues like this.

**Comment by ErisDS** [comment]
After trawling the codebase a bit today, I have all this in my brain reasonably clearly. Therefore I took the opportunity to write this up as a more detailed issue: #5358 

Going to close this one in favour of it.
