### ISSUE TITLE
I just updated from 4.0 to 5.8 and my update broke the site

### ISSUE THREAD

**Issue by sp90** [TryGhost/Ghost#4827]
I have the full install from 4.0 saved

but now i tried to enter the new install in another folder and then import the old database then i get a failure in return:

"Cannot read property 'uuid' of undefined", and red box en lower left corner says "import failed"

What can i do about this, is there a json converter which convert this old db into the new version of the database?

**Comment by marcusway** [comment]
@sp90 how did you resolve this? I'm having the same issue.

**Comment by sp90** [comment]
@marcusway can't really remember, but im pretty sure i took the DB file, converted it into json and installed a new instance of ghost, fx 0.6.2 and then used the import json file on that :)
