### ISSUE TITLE
Redirection 301 from naked domain

### ISSUE THREAD

**Issue by Danjavia** [TryGhost/Ghost#4832]
Discover issues when I try to make a redirection form http://example.com to http://www.example.com.

**Comment by markstos** [comment]
Could you be more specific what your did in Ghost that triggered the issue and what that problem was with your attempted redirect?

**Comment by ErisDS** [comment]
Hi @Danjavia if you're setting up a blog on Ghost(Pro), please contact support@ghost.org where our team can help you get setup. For self-hosted blogs, you can get help from our community on the [forum](http://ghost.org/forum).

From what you've written, I'm not able to determine if there's a bug we need to fix, but it seems unlikely as redirection is usually handled by a DNS service or web server. So for now I'm going to close this, but will happily reopen again if you have further details of a problem with the Ghost software.

**Comment by Danjavia** [comment]
Thanks! @ErisDS , I will to check it again.
