### ISSUE TITLE
Cannot send invitation mail.

### ISSUE THREAD

**Issue by truonguit2010** [TryGhost/Ghost#4843]
I run ghost-0.5.8 on MacOSX, and I am trying to send invitation mail, but It cannot.

Here is the log:
Warning: Error sending email: AuthError: Invalid login - 534-5.7.14 <https://accounts.google.com/ContinueSignIn?sarp=1&scc=1&plt=AKgnsbvkW
534-5.7.14 zMesb5OwysiZL_WsnMdXFyqAZtL3vs3GAiIUSnmocUj5zeqzr6kQetwdlgDJygMar-HpHW
534-5.7.14 HT846r9OpoRuJ3mucrWVVGYT1TlM-d4GzkmAdwIbKnitTyfV2OhA9Tfz8dNSyAvBTqjhsD
534-5.7.14 R0B8TykI4i4QpnBM7WoSCmlAZEsQRtsw3IxarF7AzlRFazYr0Ia1JfFTR6yjVwAauoRGm0
534-5.7.14 2fRr0jg> Please log in via your web browser and then try again.
534-5.7.14 Learn more at
534 5.7.14 https://support.google.com/mail/bin/answer.py?answer=78754 yq5sm1477619pac.15 - gsmtp Please check your email settings and resend the invitation.

**Comment by jaswilli** [comment]
Hi @truonguit2010,

It sounds like you either don't have your gmail credentials entered correctly, or there's something wrong with your the `mail` section in `config.js`.  Here's a link to the gmail setup:  http://support.ghost.org/mail#gmail

I'm going to close this as I don't think it's a problem with Ghost itself.

**Comment by truonguit2010** [comment]
Hi @jaswilli,
It is the new gmail. I can login in web mail. Are there any other email configurations? I follow your link to config, but it don't work.
1. Create a Gmail.
2. Set username, password to config.js file.
3. Start application.
4. It cannot send mail.

**Comment by Baudin999** [comment]
I also have the same problem. 
New Gmail account....no dice

**Comment by skynet047** [comment]
Check here:
https://www.digitalocean.com/community/questions/ghost-can-t-send-mail-using-gmail-google-apps

You should set Allow less secure apps: ON, On https://myaccount.google.com/security#connectedapps

**Comment by decarola** [comment]
I also have the same problem (already read and did all things above)

**Comment by dennis-tra** [comment]
The option suggested by @skynet047 solved it for me! Initially the option "allow less secure apps" was not listed. The (super)admin had to allow the users to change this security setting. Have a look [here](https://help.crucial.com.au/hc/en-gb/articles/214180837-Enabling-Less-Secure-Apps) for more information

**Comment by suliman317** [comment]
I have had the same issue, I have done all of the above to no avail. I think I may have to reset something in sqlite

**Comment by rodolfoviolac** [comment]
+1
