### ISSUE TITLE
fs.exists is being deprecated

### ISSUE THREAD

**Issue by markstos** [TryGhost/Ghost#4847]
`fs.exists` is used a few places in the code base, but is being deprecated by [node](https://github.com/joyent/node/pull/8418) and [io.js](https://github.com/iojs/io.js/issues/103) and is not recommended by the current official [Node.js docs](http://nodejs.org/api/fs.html#fs_fs_exists_path_callback).

Alternatives include using `fs.stat` or just skipping the check, trying a file action, and handing the error if it doesn't exit.

Refactoring to avoid `fs.exists` now would provide a bit of future-proofing.

**Comment by ErisDS** [comment]
@markstos thanks for the headsup :) 

I think the places where we use `fs.exists` (namely image storage) will need to switch to use `fs.stat` as the pre-check is used to generate a unique filename before saving.

**Comment by jomahoney** [comment]
I'm aware it's not super urgent but I wouldn't mind jumping in on this.
