### ISSUE TITLE
Can't install from "stable" branch on Ubuntu Trusty

### ISSUE THREAD

**Issue by nottrobin** [TryGhost/Ghost#4854]
I'm trying to run Grunt locally for the first time on a fairly clean install (without even `nodejs` previously installed) of Ubuntu 14.04 (the most recent LTS edition), by cloning the github repository and switching to the `stable` branch.

Grunt installed fine (`sudo npm install -g grunt`), but then, `npm install` failed because my `~/tmp` directory was owned by `root`, but I guess that's the fault of how `npm` (or maybe `grunt`) installs on trusty, 'cos I don't think that `~/tmp` directory existed before. I just fixed the permissions (`sudo chown -R robin:robin ~/tmp`) and then `npm install` succeeded.

But then when I ran `grunt init`, I got these errors:

```
Loading "docker.js" tasks...ERROR
>> Error: Cannot find module 'watchr'
Loading "jscs.js" tasks...ERROR
>> Error: Cannot find module 'vow-fs'
Loading "sass.js" tasks...ERROR
>> Error: Cannot find module 'each-async'

Running "shell:bower" (shell) task

Running "update_submodules:default" (update_submodules) task

Running "concat:dev" (concat) task
File core/built/scripts/vendor-dev.js created.

Running "copy:dev" (copy) task
Copied 2 files
Warning: Task "sass" not found. Use --force to continue.

Aborted due to warnings.
```

Now knowing how to fix this (I checked `ruby-sass` was definitely installed) I just continued with `grunt init --force`.

Then when I type `npm start` I get this:

```
> ghost@0.5.8 start /home/robin/projects/Ghost
> node index


module.js:340
    throw err;
    ^
Error: Cannot find module 'sax'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/robin/projects/Ghost/node_modules/nodemailer/node_modules/aws-sdk/node_modules/xml2js/lib/xml2js.js:8:9)
    at Object.<anonymous> (/home/robin/projects/Ghost/node_modules/nodemailer/node_modules/aws-sdk/node_modules/xml2js/lib/xml2js.js:283:4)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
npm ERR! weird error 8
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! not ok code 0
```

Any ideas?

**Comment by jaswilli** [comment]
Hi @nottrobin,

This sounds like a problem with one of the packages in your `node_modules` folders that occurred when you were having environment issues.  My recommendation would be to `rm -rf node_modules` and then run `npm install` again.

**Comment by nottrobin** [comment]
Aye you're right. Thanks.
