### ISSUE TITLE
[Future] Need edit link on post page

### ISSUE THREAD

**Issue by ytzong** [TryGhost/Ghost#4857]
It's hard to find the post to edit.

**Comment by sebgie** [comment]
Hi @ytzong and welcome to Ghost!

If I understand your issue correctly you are looking for a way to get to the edit screen when you are visiting the published version of a post? This is already implemented by simply adding `/edit` at the end of the URL.

Example:
Post: `http://www.your-domain.com/post-name`
Edit:  `http://www.your-domain.com/post-name/edit`

If I understood wrong, please update your issue with more information about the behaviour you are looking for and I'm happy to reopen the issue.

**Comment by ytzong** [comment]
That's my want, thank you very much.
