### ISSUE TITLE
Website: hosting provider page

### ISSUE THREAD

**Issue by pierreozoux** [TryGhost/Ghost#4863]
Hi,

(Do you have a repo for the public site ?)

I think it would be a great idea to have a page with all the hosting providers out there.
Wordpress does the same, and I believe it's good practice:
https://wordpress.org/hosting/
https://wordpress.com

Cheers!

Pierre

**Comment by ErisDS** [comment]
Hi @pierreozoux, thanks for the suggestion - I've shared this with our team internally and we'll consider the idea in the near future when we will be making changes to Ghost.org.

**Comment by pierreozoux** [comment]
:+1:
