### ISSUE TITLE
Accessibility attributes for tag and cover images 

### ISSUE THREAD

**Issue by raulfelix** [TryGhost/Ghost#4867]
As part of Ghost Admin when uploading an image to a tag or the blog cover image there is no way to add **alt** values or **title** values.
 
This would be a valuable feature for non technical blog users as well as theme developers to help reach good accessibility levels. I did not see mention of a task to cover this as part of the [Advanced Tag Management](https://github.com/TryGhost/Ghost/issues/4798) feature.

I have witnessed some work arounds being used such as using the "meta_title" field under the tag settings panel which is very bad so suspect this may come up as a requested feature.

**Comment by JohnONolan** [comment]
This may be something we come back to when we have a far more advanced image handling library - but for the foreseeable future there isn't going to be any UI workaround to support this at present.
