### ISSUE TITLE
Mobile navigation does not close when going form mobile to desktop sized viewport

### ISSUE THREAD

**Issue by PaulAdamDavis** [TryGhost/Ghost#4871]
When resizing the browser from a mobile sized width to desktop with the mobile navigation open, the navigation should close. Right now, it doesn't. The class `global-nav-expanded` on `<body>` is not removed when resizing. It works correctly when clicking to close though.

### Steps to Reproduce

1. Resize your browser down to 900px or less
2. Open the navigation
3. Resize to more than 900px
4. See error in the console and broken layout

### Technical details:

* Ghost Version: 43f2be4d798d57d0e9170f142cd15e4d2799ec1c (also present in 0.5.8)
* Client OS: Mac OS X 10.10.1
* Browser: Chrome 40

![bug](https://cloud.githubusercontent.com/assets/390392/5980657/abb55f06-a8aa-11e4-950f-25128bfbf0d8.gif)

**Comment by jaswilli** [comment]
Nice find :+1: 

Coincidentally, I was working on an "ember cleanup" PR this morning and this bug is fixed in it.

**Comment by ErisDS** [comment]
@jaswilli has that PR landed, or is it still to come?

**Comment by jaswilli** [comment]
@ErisDS I have it in a big "ember clean-up" branch which I've been holding back in consideration of the ember-cli work.  I'll separate out just the fix for this issue and push it up.

**Comment by novaugust** [comment]
> which I've been holding back in consideration of the ember-cli work

<3
