### ISSUE TITLE
Incorrect error "Published Date cannot currently be in the future"

### ISSUE THREAD

**Issue by arangas** [TryGhost/Ghost#4873]
I'm manually transferring content from my old WordPress then static HTML blog, to a new Ghost blog.

As I transfer each post, I am setting the date in the Ghost meta data panel to when it was originally published. On the left I then get the message "Published Date cannot currently be in the future". Somehow I get Ghost to accept it but it's a bit tricky. There shouldn't be any issues with entering a publish date of the past.

**Comment by novaugust** [comment]
Hi @arangas, thanks for the report. This isn't something we've seen before, and it sounds a bit like some sort of environment issue - you're definitely correct in stating that entering a past published date shouldn't cause any issues. Can you check out our [bug report](https://github.com/TryGhost/Ghost/blob/master/CONTRIBUTING.md#bugs) guidelines and update your issue with a description of how we can recreate this problem? 
The only thing I can think of without being able to reproduce it right now is that you may have a strange date setting (ie, it's set to a past date) on either your computer or server.

**Comment by arangas** [comment]
I set up LiceCap to record a demo for you and of course, now I can't repro. (I have rebooted the server since so maybe related.) Thanks for letting me know how to submit a bug report - if this happens again i'll follow these steps!
