### ISSUE TITLE
Workflow enhancement: Make edit button position fixed

### ISSUE THREAD

**Issue by PabloSichert** [TryGhost/Ghost#4875]
Just a tiny enhancement: It would be nice if the "EDIT" button on a post would be positioned fixed. I find myself proofreading a post and then need to scroll up all to way just to hit this button.

**Comment by subic** [comment]
The same should also apply to "SAVE" button under Settings/General. Current situation is a bit annoying  especially on a smaller screen when you are for example switching themes as you have to scroll back up after each change.

Sorry to piggyback this issue but the two seem related, UI-wise at least

**Comment by ErisDS** [comment]
I'm not sure that this is going to be changed in the very near future, but in the meantime it's worth noting that you can navigate around the admin using keyboard shortcuts.

When you're half-way down a post on the content screen, both `enter` and `o` will open the post for editing. 

On any screen that can be saved, `ctrl/cmd + s` works.

Here's the [documentation](http://support.ghost.org/shortcuts/).
