### ISSUE TITLE
Include Post Cover Images in RSS

### ISSUE THREAD

**Issue by philipithomas** [TryGhost/Ghost#4888]
Cover images get added as meta tags, e.g. opengraph and twitter cards. However, they are not getting pushed to RSS feeds using the <image> element: 

http://www.w3schools.com/rss/rss_tag_image.asp

A practical reason to do this is to use the IFTTT "Post to twitter with an image" formula.

**Comment by halfdan** [comment]
Hi @philipithomas,
I like the idea of having the cover images embedded in the RSS feed. The element you linked to however is only for channel images (a single image for the feed).

http://stackoverflow.com/questions/483675/images-in-rss-feed

It seems to be possible to use the `enclosure` or `media:content` element or use CDATA to have post specific rss images but there doesn't seem to be an agreement on which to use. Suggestions?

**Comment by felixrieseberg** [comment]
I also like the idea - in fact, *I'd be happy to implement it*. @halfdan already mentioned CDATA and it seems like most other blog systems are going with that. Medium for instance uses a small HTML snippet inside the description tag, which I think is a neat solution. What do you guys think?

```
<![CDATA[
<div class="medium-feed-item"><p class="medium-feed-image"><a href="https://medium.com/tech-talk/everything-is-boring-421f8c2f927a"><img src="https://d262ilb51hltx0.cloudfront.net/fit/c/600/200/1*hKUcix4SD-dngKU9aNGg7A.png" width="600" height="200"></a></p><p class="medium-feed-snippet">I found myself lost in the depths of advertisement hell searching for some deal that would rekindle my inner-American sense to shop&#8230;</p><p class="medium-feed-link"><a href="https://medium.com/tech-talk/everything-is-boring-421f8c2f927a">Continue reading on Medium »</a></p></div>
]]>
```

**Comment by philipithomas** [comment]
The motivating problem was using the IFTTT RSS->Tweet recipe, which supposedly pulls an image from the RSS. Do you know anybody at IFTTT who can comment on their preferred RSS image format?

I'll poke around more and see if I can find anybody to comment on the best practices for this. I bet that following the format of a major RSS provider (feedburner, wordpress.com, twitter itself, etc) might be best.

**Comment by felixrieseberg** [comment]
I checked with IFTTT - they're pulling the image from the description tag (or use the first available one in  the content tag). I can go and see if this is easy to implement.

**Comment by chirox** [comment]
Image src attribute need remove last / character. Here is my rss output <img src="http://localhost:2368/content/images/2015/02/picjumbo-com_IMG_8868.jpg**/**"

**Comment by JohnONolan** [comment]
^ Verified

**Comment by felixrieseberg** [comment]
On it.
