### ISSUE TITLE
Include example privacy options in config.example.js

### ISSUE THREAD

**Issue by goody1989** [TryGhost/Ghost#4889]
As far as I understand from reading through the available user documentation, we can add privacy options to the config.js file, but I haven't seen anything explain where in the config.js file they should be added.  It's easy to make the mistake of adding these into the wrong block.  Could we have a commented example added to the config.example.js file?

    privacy: {
        useTinfoil: true,
        useUpdateCheck: true,
        useGoogleFonts: true,
        useGravatar: true,
        useRpcPing: true
    }

**Comment by ErisDS** [comment]
Hi @goody1989, welcome to Ghost :) 

The example config file deliberately only demonstrates the required options. If we updated it to include privacy, then we would reasonably need to include all possible options and that would make the file  unweildy.

The [Ghost config docs](http://support.ghost.org/config/) explain how [environments work](http://support.ghost.org/config/#about-environments) and all config options have to be added to the root level of an environment.

If you have some suggestions for how we can make this clearer in the documentation, let us know. I don't think adding more things to the config.example.js file is the right solution here though.
