### ISSUE TITLE
Edit cursor sits at start of line when cursor should be at end

### ISSUE THREAD

**Issue by venantius** [TryGhost/Ghost#4890]
Title is pretty self-explanatory, I hope.

Gif for recreation:
![cursor_bug](https://cloud.githubusercontent.com/assets/1824859/6056111/5420a960-acc1-11e4-96cc-b87eaa2a3434.gif)

** Technical details:**
OS X 10.10.1
Chrome 40.0.2214.94 (64-bit)
Ghost v0.5.5
Database SQLite

**Comment by matohawk** [comment]
I have the same problem.

**Comment by ErisDS** [comment]
Hi @venantius & @matohawk - I've also experienced this issue, I realise it's quite annoying - and I'm not sure what's causing it. However there's little point anyone spending time on fixing it as we intend to release a new version of the editor very soon (see #4373) - and spending time on that is more worthwhile ;)

Therefore I'm going to close this as a won't fix.
