### ISSUE TITLE
Application development - accessing config

### ISSUE THREAD

**Issue by milosh012** [TryGhost/Ghost#4899]
Hello,

I asked question here also https://github.com/TryGhost/Ghost-App/issues/21 but still no answer, so I would like to ask here again... 

I want to access config inside my custom application. Is that possible and how? I looked over your wiki, but no luck with finding that information... 

Thanks in advance,
Milos

**Comment by ErisDS** [comment]
Closing as a duplicate of TryGhost/Ghost-App#21 - someone will get to answering you when they have time ;)
