### ISSUE TITLE
Admin console not loading after fresh install from stable

### ISSUE THREAD

**Issue by mathewballard** [TryGhost/Ghost#4904]
Today I have made several attempts to setup a brand new instance of Ghost locally from stable. After going through the initial setup:

`npm install -g grunt-cli`
`npm install`
`grunt init`
`npm start`

The initial page will load at http://localhost:2368. When I navigate to http://localhost:2368/ghost the redirect to http://localhost:2368/ghost/setup occurs, but a blank page loads. After using Chrome Dev Tools with Ember diagnostics it appears that there is an issue within Ember itself. However, I don't have the knowledge to dig further myself.

![screen shot 2015-02-10 at 6 41 55 pm](https://cloud.githubusercontent.com/assets/1480881/6138994/aa77c52c-b154-11e4-9401-107f90e56faa.png)

**Comment by jaswilli** [comment]
Hey @mathewballard,

Sorry you're having trouble!  I think the one step you're missing is running `grunt prod` after `grunt init` finishes.  That will "build" all of the front-end assets, which is required if you're running Ghost from the GitHub repository instead of the .zip file.

**Comment by mathewballard** [comment]
Unfortunately that doesn't resolve the issue. Single uses of `grunt init`/ `grunt prod` or running them both yields the same results.

**Comment by jaswilli** [comment]
Yeah, sorry about that, I edited my comment above.

**Comment by mathewballard** [comment]
Error: Cannot read property 'template' undefined.

Wanted to get that up while I try out your suggestion.

**Comment by davidolrik** [comment]
Current stable depends on Ember 1.9.0, and the error above is from trying to call `Ember.HTMLBars.template()` which isn't available in Ember prior to 1.10.

Changing all calls to `Ember.HTMLBars.template()` to `Ember.Handlebars.template()` will let you start Ghost.

**Comment by davidolrik** [comment]
The real culprit is `grunt-ember-templates` which now defaults to using HTMLBars.

```diff
diff --git a/Gruntfile.js b/Gruntfile.js
index 86c8853..df95b16 100644
--- a/Gruntfile.js
+++ b/Gruntfile.js
@@ -382,6 +382,7 @@ var _              = require('lodash'),
                     options: {
                         templateBasePath: /core\/client\//,
                         templateFileExtensions: /\.hbs/,
+                        templateNamespace: 'Handlebars',
                         templateRegistration: function (name, template) {
                             return grunt.config.process('define(\'ghost/') +
                                 name + '\', [\'exports\'], function(__exports__){ __exports__[\'default\'] = ' +
```

Adding `templateNamespace` to the Gruntfile will build everything properly.

**Comment by jaswilli** [comment]
Yeah, I see that there was a breaking change from `0.5.0-alpha` to `0.5.0`.  That's not ideal but I'm sure they had reasons.

@mathewballard Probably the easiest thing to do is just `npm uninstall grunt-ember-templates && npm install grunt-ember-templates@0.5.0-alpha` and then you'll end up with the version that works.

We've switched to HTMLBars on master, so in the next stable release this won't be an issue.

**Comment by mathewballard** [comment]
Thanks everyone, I got it up and running by following @davidolrik's suggestion.

**Comment by mathewballard** [comment]
One last thing for future reference. Here are the steps I followed leading up to the issue:

The only thing that I can think of that happened is me pulling down the repo shortly after the update for the Ember namespace change was made - I had noticed at the time that there were a lot of Ember related commits which sent me down this road during debugging. I then switched to stable and ran the 

`npm install -g grunt-cli`
`npm install`
`grunt init`
`npm start`

I'm wondering if because I started with master and then switched to stable if something was left behind that caused the issue in stable.

**Comment by jaswilli** [comment]
No, the problem you were having was caused by the `grunt-ember-templates` module changing its behavior between `0.5.0-alpha` and `0.5.0`.  There really shouldn't have been a breaking change like that   without moving to something like `0.6.0` but it happens sometimes, especially when packages are still in version 0.x.x.

**Comment by davidolrik** [comment]
Nope, I had the same problem and I started with stable@0.5.8.

The problem is as @jaswilli stated, grunt-ember-templates changed defaults between 0.5.0-alpha and 0.5.0 and `package.json` has its version specified as `~0.5.0-alpha` which means its ok for `nom` to get any 0.5.x version.

**Comment by davidolrik** [comment]
There shouldn't be any braking changes with out changing the major version number, but pre 1.0.0 anything can happen.

**Comment by mathewballard** [comment]
Yeah, everything built on node is so fragile that things like this happen. It is odd though, because I had pulled it down a day before and it ran fine, then the next day that wasn't the case.

With all that said, what is the ETA on the next stable release?

**Comment by ErisDS** [comment]
Making changes to the stable branch is undesirable, but I have added an `npm-shrinkwrap.json` which should, I believe, resolve this problem with the loosely-bound dev dependencies without actually changing the code. 

I have been thinking about including the fully built assets on stable, but I'm not sure if that's warranted or desirable.

The shrinkwrap file seems to me to be a happy medium, we probably ought to include it in all releases. I will update the release scripts to include this file I think.

**Comment by TomFreudenberg** [comment]
Hi Hannah ( @ErisDS )

For me I can NOT confirm that the `npm-shrinkwrap.json` content on stable is working. Still the blank error caused by the wrong calls for HTMLBars and Handlebars in generated templates.js. 

What I can see so far, if you wish to solve it via `npm-shrinkwrap.json` you should or have to add dependencies for grunt-ember-templates as well.

But still I prefer #4920 suggestion for stable fix.

Tom
