### ISSUE TITLE
Error: /usr/lib64/libstdc++.so.6: version `CXXABI_1.3.5' not found

### ISSUE THREAD

**Issue by twtww** [TryGhost/Ghost#4905]
CentOS 6.5 with nodejs 1.4.28 installed.

When I use npm install to install Ghost it says
```
Error: /usr/lib64/libstdc++.so.6: version `CXXABI_1.3.5' not found (required by /home/www/domains/Ghost/node_modules/grunt-sass/node_modules/node-sass/vendor/linux-x64/binding.node)
```

**Comment by ErisDS** [comment]
Hey there @twtww, this is an issue with node-sass. 

It depends on what you're trying to do, but you don't need to install node-sass if you use the zip file from GitHub/Ghost.org or the npm package - just run `npm install --production`. If you want to install from git stable or for dev purposes, you can find out more about how to get node-sass installed here: https://github.com/sass/node-sass/issues/517#issuecomment-69072917

It would be great if you could update this issue to contain the details of what you're doing - what install process you're using, which version of Ghost etc. You can find a handy template in our [contributing guidelines](https://github.com/TryGhost/Ghost/blob/master/CONTRIBUTING.md#bug-reports), thanks.

**Comment by ErisDS** [comment]
Going to close this for now.
