### ISSUE TITLE
Can i configure the images path only?

### ISSUE THREAD

**Issue by borisyu** [TryGhost/Ghost#4906]
I know that it can be change the "contentPath" through configuring the "paths" object, but i wanna only change the 'images' path, how can i do that ?

I try to configuring as below:
config = {
    production: {
        paths: {
            imagesPath: CUSTOM_PATH
        }
    }
}

but it seems not working.

**Comment by ErisDS** [comment]
Hi @borisyu, sorry but that isn't possible at present - only contentPath is configurable.

**Comment by borisyu** [comment]
@ErisDS Thank you so much!
