### ISSUE TITLE
Reauthenticate fails 

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#4907]
I saw this reported recently in IRC, and I have also had a report of this via email from a Ghost(Pro) user.

It seems that the form won't submit. I have not yet tried to reproduce it, and don't have full details of the blog. However, I do have this screencast of it occurring, which I think is enough to confirm it's definitely a thing :wink: 

![](http://puu.sh/fMDml.gif)

It seems to me that there's either a console error blocking submission, or perhaps it's something to do with password manager type issues again?

### Technical details: 

* Ghost Version: 0.5.8

**Comment by avsd** [comment]
I can confirm - it happened to me twice on GhostPro. If I see it again, will check the JS console :)
