### ISSUE TITLE
Slugs of deleted posts cannot be used again

### ISSUE THREAD

**Issue by ruvido** [TryGhost/Ghost#4918]
If you have a post with a slug

example.com/mytitle

and then delete the post, you cannot re-use that slug again. The system forces you to use:

example.com/mytitle-2

as the old post was still there. 
I also tried to export and re-import the json but no success, got:

Import failure

**Comment by ErisDS** [comment]
Hi @ruvido, welcome to Ghost :)

Please could you update your issue with full details of your Ghost install and a step-by-step breakdown of how to reproduce your problem? You can find a handy template in our [contributing guidelines](https://github.com/TryGhost/Ghost/blob/master/CONTRIBUTING.md#bugs).

The problem as you have described it here - not being able to re-use a slug from a deleted post - is not reproducible on master.

**Comment by ruvido** [comment]
Sorry that was a mistake from my side, it was confusing that saving (command-S) the post with the new slug (with the cursor still in the slug box) does not update the name. Once the cursor is moved away to some other field, saving works as expected. Thanks for the prompt reply.
