### ISSUE TITLE
White page for config after clean installation - templates(-dev).js

### ISSUE THREAD

**Issue by TomFreudenberg** [TryGhost/Ghost#4920]
I tried a clean installation from GIT CLONE today using branch stable as well as tag 0.5.8.

After running

````
git clone -b stable https://github.com/TryGhost/Ghost.git
cd ghost
npm install
grunt init
grunt prod
npm start
````

I got a white page when trying to access `http://127.0.0.1:2369/ghost/setup`

This is same, when I install GHOST via NPM `npm install ghost`

After a few tries, I downloaded the `ghost-0.5.8.zip` and this worked.

When using diff to find out what may differ, I got differences in files:

`core/built/scripts/templates(-dev).js`.

---

NOT WORKING WHEN GENERATED FROM GIT CLONE:

````
Ember.HTMLBars.template
````

INCLUDE IN GHOST-0.5.8.zip

````
Ember.Handlebars.template
````

![diff-ember-templates-js](https://cloud.githubusercontent.com/assets/410087/6206349/12f1fd7a-b588-11e4-8703-58f78d21e7e2.png)

My question is now, why are the templates generated with a wrong Ember funtion call? Did I miss something?

Thanks for hint or help

Tom

**Comment by TomFreudenberg** [comment]
FIX:

I added new config to my Gruntfile.js for the templateNamespace:

````
            emberTemplates: {
                dev: {
                    options: {
                        templateNamespace: 'Handlebars',
                        ...

                prod: {
                    options: {
                        templateNamespace: 'Handlebars',
                        ...

````

This fixes the Ember.call to Ember.Handlebars

**Comment by jonblack** [comment]
So others are aware, after applying the fix above, you need to re-run `grunt init`.

**Comment by mikedevita** [comment]
another one here chiming in that @TomFreudenberg suggestion fixes this issue. Thanks for the hotfix @TomFreudenberg.

**Comment by TomFreudenberg** [comment]
@jonblack and others

At least you have to run:

````
grunt emberTemplates
````

after adding the above fix to `Gruntfile.js`

**Comment by ErisDS** [comment]
To clarify a few things here:

If you install from anywhere other than git clone - i.e. a zip from the release page or Ghost.org or from npm, you should **not** be running `grunt init`, as all of the assets are pre-built.

If you are installing from git, the stable branch ought to be ok. However one of the dependencies recently experienced a breaking change which I believe was fixed here: #4904 

On master, I am not able to reproduce this problem at all, which has me very confused -  is it just the stable branch which is having problems again?

**Comment by TomFreudenberg** [comment]
Hi Hannah ( @ErisDS )

> If you install from anywhere other than git clone - i.e. a zip from the release page or
> Ghost.org or from npm, you should not be running grunt init, as all of the assets are pre-built.

I had not run any grunt when using NPM or ZIP installation

> On master, I am not able to reproduce this problem at all, which has me very confused
> is it just the stable branch which is having problems again?

This is clear, because on master the `bower.json` defines a new version for ember

````
"ember": "1.10.0",
````

in stable and tags 0.5.8 the definition in `bower.json` is

````
"ember": "1.9.0",
````

as well as some other changes.

---

So, from my opinion, fixing the stable has two options:

a. define a fix version for grunt-ember-templates like 0.5.0-alpha as was described in ticket #4904 

OR 

b. (as I prefer) change:

1. `templateNamespace` in `Gruntfile.js`
2. change `package.json` to

````
"grunt-ember-templates": "~0.5.0",
````

In the above case you can stay with ember 1.9.0 as stable and you not have to change too much on stable release.

Greetings from germany
Tom

**Comment by ErisDS** [comment]
To clarify, I was confused because you said:

> This is same, when I install GHOST via NPM npm install ghost

This shouldn't be affected?

**Comment by TomFreudenberg** [comment]
Ähem ... Hannah ( @ErisDS )

Calling myself a bit confused ...

I tried this last night several times via NPM  INSTALL GHOST

and I am absolutely sure that it was NOT WORKING ... tried this 5 minutes ago again ....

and everything is fine ???

So we put this away as some another very mystic computer behavior.

---

So for now ... still the problem when installing via git clone and using branch "stable" or tag "0.5.8".

Tom

**Comment by tchapi** [comment]
Same issue here, @TomFreudenberg 's suggestion fixes it, nothing else works. I've tried to install from stable a few times, either cloning the repo or downloading the release zip, and with every possible combination of `grunt init` and the like.

Thanks @TomFreudenberg !

**Comment by ErisDS** [comment]
Stable branch has been updated now, so this should no longer be a problem.

**Comment by TomFreudenberg** [comment]
Hi Hannah, sounds good. Do you know the commit hash for the fix? Thanks, Tom

**Comment by ErisDS** [comment]
We had already upgraded to the newer version of ember in master before this problem occurred, so there isn't really one. 

Stable now has an npm-shrinkwrap.json generated during the release so that this sort of issue shouldn't occur again in future.
