### ISSUE TITLE
URLs used in embedded JavaScript within posts get parsed

### ISSUE THREAD

**Issue by JoseTomasTocino** [TryGhost/Ghost#4922]
I'm trying to add a snippet of JavaScript in a page post and there's a url as a variable. It gets automatically detected by the markdown parser and it gets unfortunately converted to an anchor tag.

Is that expected behavior?

**Comment by ErisDS** [comment]
Hi @JoseTomasTocino, welcome to Ghost! 

Please could you update this issue to include full details of how you're embedding the snippet? We have a template for bug reports in our [contributing guidelines](https://github.com/TryGhost/Ghost/blob/master/CONTRIBUTING.md#bugs) that should provide some handy tips on what to include.

The short answer is no, that's not expected, but we're not able to know for sure unless we can see what you're trying ;)

**Comment by JoseTomasTocino** [comment]
Cloned the repo, set it up, ran `npm start`, everything works ok.

Opened the _Welcome to ghost_ post in the admin panel, added this:

    <div id="output"></div>
    <script>
    document.getElementById("output").innerHTML = 'http://google.com';
    </script>

Saved the post. Went to the post. Checked the source code. It looks like this:

    <div id="output"></div>  
    <script>  
    document.getElementById("output").innerHTML = '<a href="http://google.com">http://google.com</a>';  
    </script>

That's it.

**Comment by ErisDS** [comment]
That makes it much clearer thanks - the auto-linking has protection to prevent it from changing code snippets inside `<pre>` or `<code>` tags, but not `<script>` tags.
