### ISSUE TITLE
Markdown editor gets slower with longer text

### ISSUE THREAD

**Issue by bobzsj87** [TryGhost/Ghost#4926]
I am using self deployed v0.5.8 and Chrome on a Macbook Pro.

The real time preview is really good, but it renders the preview every time the textarea changes on the left and you can feel obvious performance issue when you type in long texts (1000 words +). 

It is better to hide preview or provide a "full-screen" writing mode, and open preview whenever wanted (usually before submit or add an image).

**Comment by ErisDS** [comment]
Hi @bobzsj87, whilst it's not perfect, we've made massive improvements to the performance of the editor in #5030, enough that I think it's safe to close this issue for the time being.

We have plans to improve it further in the future, but I think you'll find if you try out master, or wait for the next release of Ghost, that it is much better at handling long posts.
