### ISSUE TITLE
Navigation - delete not behaving correctly after a re-order

### ISSUE THREAD

**Issue by jaswilli** [TryGhost/Ghost#4928]
Steps to reproduce:

* Open Navigation.
* Make sure there are at least two items in the list.
* Move the bottom item up in the list.
* Try to delete the item that was just moved and nothing happens.
* Try to delete one of the items that is now below the moved item and everything above it is deleted.

**Comment by PaulAdamDavis** [comment]
I tried to figure this one out, but was unsuccessful. It's an odd bug though.

The `item` passed to `removeObject` is correct, before and after being repositioned.

> Try to delete one of the items that is now below the moved item and everything above it is deleted.

It looks like this is caused when trying to delete an item higher up in the list. A new order property is set – ignoring the item which should've been deleted – meaning we get 2 items with the same `order` number.

It's increasingly looking like the way I built the reordering is _less than optimal_. As @novaugust has said elsewhere, they're "complex interactions" and there's no reason they should be. :weary:
