### ISSUE TITLE
Changelog, and latest version online demo

### ISSUE THREAD

**Issue by pensierinmusica** [TryGhost/Ghost#4929]
Hi,

I've been using Ghost for a couple of months now, and love it.

Wanted to check what new features have been implemented in the meantime, but couldn't find where a changelog is published. Could you point me in the right direction, or if it doesn't exist would it be possible to create one?

It'd also be nice to have a demo online where anyone can go and see a live example of the latest version, if not for editing, at least to check out new features introduced to Casper.

What do you think? Thanks, cheers!

**Comment by tparkin** [comment]
A great place to start is the Ghost Roadmap on Trello: https://trello.com/b/EceUgtCL/ghost-roadmap

The Ghost Dev Blog is another place to follow and recaps the weekly public meetings (which you can attend in IRC): http://dev.ghost.org/

**Comment by ErisDS** [comment]
Hi @pensierinmusica, welcome to Ghost's GitHub :) 

It's great to hear from people who are interested in the project :) This sort of question is much better suited to our [forum](https://ghost.org/forum) - GitHub is where the developers keep track of of issues and work on the software. 

As @tparkin pointed out, the [dev blog](http://dev.ghost.org) has details of the meetings and also notes on each [release](http://dev.ghost.org/tag/releases/) or there is also the [releases](https://github.com/TryGhost/Ghost/releases) page here on GitHub.

As for a demo - it takes a few seconds to create a trial blog on Ghost.org which you can play with for free for 2 weeks - no credit card required, so you can always check out the latest version :)

**Comment by nuclearpengy** [comment]
Perhaps off topic - For quite some time I've been thinking, having a 'dev' or 'test' site would be pretty cool.

Not a personal demo, but rather a publicly accessible instance of the latest in development version of Ghost for non-technical users to test on and perhaps contribute towards cross-browser testing prior to a release.

This could be invite only so as to keep the circle of non-tech commentators reasonably small and/or controlled.

**Comment by pensierinmusica** [comment]
@nuclearpengy makes sense to me  :)

**Comment by pensierinmusica** [comment]
@ErisDS thanks for the feedback! I think it'd be useful to have a link to the changelog at the bottom of readme. I'll do a PR for that, let me know your thoughts, cheers  :)
