### ISSUE TITLE
Inadequate monospace font definition (Ghost Markdown Editor on OS X)

### ISSUE THREAD

**Issue by mankittens** [TryGhost/Ghost#4936]
The default (monospace) font for the Ghost Markdown Editor is defined [here](https://github.com/TryGhost/Ghost/blob/master/core/client/assets/sass/modules/variables.scss#L37) as:
```scss
$font-family-mono: monospace;
```

## Problem

On OS X, `monospace` defaults to `Courier` for basic characters, but outside of basic characters, the system is inconsistent in choosing a fallback. This is the result:

![ghost-editor-right-and-left-arrows](https://cloud.githubusercontent.com/assets/6647355/6317031/555693dc-ba0c-11e4-8c6a-293dc824d18f.png)

### Chrome & Safari

In Chrome and Safari, we can see that Lucida Grande and Monaco are used:

![screen shot 2015-02-21 at 21 04 35](https://cloud.githubusercontent.com/assets/6647355/6317044/9450129c-ba0d-11e4-8ac2-00cb759e7155.png)

### Firefox

Firefox uses a different font, but I'm not sure how to get it to cough up which font is actually being applied.

![screen shot 2015-02-21 at 21 23 43](https://cloud.githubusercontent.com/assets/6647355/6317102/f67fef6c-ba0f-11e4-9172-96d41bdc0a55.png)

## Possible Solutions

Increase specificity of monospace font definition. I recommend adding `Menlo`.

```scss
$font-family-mono: Courier, Menlo, monospace;
```

OR 

```scss
$font-family-mono: Menlo, monospace;
```

**NOTE**: Monaco should not be used since it doesn't even cover the left arrow glyph.

**Comment by mankittens** [comment]
Here are the characters that appear in the photos, for reference (U+2190) & (U+2192):

```
←
→
```

Taken from [this website](http://www.amp-what.com/unicode/search/arrow).

Also, here is the monospace definition used on GitHub's pages, for reference. And Menlo ends up being the font applied on OS X.

```
font-family: Consolas, "Liberation Mono", Menlo, Courier, monospace;
```

**Comment by JohnONolan** [comment]
@mankittens Fantastically written issue, and totally agree with your suggested change and the basis for it. :+1:

**Comment by mankittens** [comment]
Would you like me to submit a PR with the suggested monospace definition?
