### ISSUE TITLE
Mixed Content Warning on Admin Dashboard

### ISSUE THREAD

**Issue by drewolson** [TryGhost/Ghost#4938]
I'm serving my ghost blog with nginx. I serve the admin paths (`/ghost/*`) via SSL. I receive a mixed content warning when visiting the admin dashboard for the file `user-image.png`. Please see the attached screenshot.

![blurred_screen_shot](https://cloud.githubusercontent.com/assets/3536/6319886/c476fffe-ba93-11e4-9a46-0119ebc16413.png)

**Comment by novaugust** [comment]
Hi @drewolson, a quick guess is that even though your nginx is serving over ssl, Ghost hasn't been configured to use SSL. Can you check that you've set the `forceAdminSSL` flag in your config.js?

Ref: http://support.ghost.org/setup-ssl-self-hosted-ghost/

I don't believe this is an issue with ghost, but just your config. As such I'm closing the issue to keep things tidy - by all means leave more comments if I'm mistaken :)

**Comment by drewolson** [comment]
Hi @novaugust, thanks for the quick response. I've used both those pages in setting up SSL for my blog and I believe all is configured correctly. Interestingly, I don't see these mixed content warnings on the `/ghost/editor/` path, but I do see it on the paths `/ghost/<post number>/` and `/ghost/settings/general/`.

I have set `forceAdminSSL` to `true` in my config as well.

**Comment by drewolson** [comment]
Oops, I take that back. I've simplified my nginx config and all is working now. Sorry for the noise!
