### ISSUE TITLE
Bug: Default options for model being discarded?

### ISSUE THREAD

**Issue by rodrigogoncalves** [TryGhost/Ghost#4939]
Dear developers, I suppose the parameters of Lodash's `extend` method are switched in [/core/server/models/post.js#L359](https://github.com/TryGhost/Ghost/blob/master/core/server/models/post.js#L359).

Shouldn't it be `_.extend(options, defaultOptions)` instead of the reverse?

[Lodash docs](https://github.com/lodash/lodash/blob/2.4.1/doc/README.md#_assignobject-source-callback-thisarg)

**Comment by felixrieseberg** [comment]
Good catch - thanks!

**Comment by 1pete** [comment]
I guess you both misunderstand. 
The code is already correct.
```_.extend(defaultOptions, options)```
Or you can alternatively use ```_.defaults(options, defaultOptions)```.

**Comment by felixrieseberg** [comment]
Huh, didn't see that the linked doc was actually for a different method. Guess we can close this then.
