### ISSUE TITLE
Encoding Bug

### ISSUE THREAD

**Issue by codertx** [TryGhost/Ghost#4941]
I face the same problem like this.https://github.com/TryGhost/Ghost/issues/4705 The posts is in chinese too.I'm sure that my wordpress database use utf-8 encoding. 

Thank you.

**Comment by ErisDS** [comment]
Hi @codertx, sorry to hear you're having problems. I recommend opening a thread on the [forum](https://ghost.org/forum) with the full details of your setup so that you can get some help migrating to Ghost.
