### ISSUE TITLE
Feature: Post Notes

### ISSUE THREAD

**Issue by JohnONolan** [TryGhost/Ghost#4956]
Opening for discussion.

Here's a really simple feature which we could ship with extremely minimal work required: Post Notes.

Use case: When writing or researching an article it's common to gather together source material and ideas, before slowly forming them into a coherent post. Not all material is always used, and not everything needs to go into the final post.

Post Notes would allow you to have a simple free-form "scratch pad" of sorts to store additional data alongside each post, which is only visible within admin.

Only additional UX note: This would require modification to the post settings menu to open *alongside* the editor rather than on top of the editor. Which is to say that you would be able to write in the editor while keeping the post settings menu open.

![image](https://cloud.githubusercontent.com/assets/120485/6390858/a7d424c6-bdb8-11e4-88d0-26a6e74cfa2e.png)

**Comment by avsd** [comment]
Maybe it's worth implementing comments in markdown, and put some information as an example when a new post is created? Not sure if it's easier though :)

**Comment by nuclearpengy** [comment]
This is a rad idea. Dig it!

**Comment by nuclearpengy** [comment]
This also solves an issue relating to 'draft/preview' posts. You could use the 'notes' section to hack out 100% private, never to be published thoughts so even if people do manage to stumble upon the UUID of the post and get to see the preview, they will never see your private notes.

This could also be used for 'editors' to provide feedback to authors in private without having an impact on the content of the actual post.

With this in mind, I also like the idea of 'notes' supporting markdown.

**Comment by brennick** [comment]
I really would like to get started on working on Ghost and contributing to the source code, could someone maybe point me in the right direction on where I would start to do something like this? It doesn't seem too complicated and I think I have the skills to do it.

**Comment by brennick** [comment]
@JohnONolan I can't seem to get the tab-manager to work. My current code can be found here: https://github.com/brennick/Ghost/blob/master/core/client/templates/post-settings-menu.hbs

The attached image is what it is showing up as.
![screen shot 2015-02-27 at 11 51 01 am](https://cloud.githubusercontent.com/assets/8314655/6420004/29bc4cac-be77-11e4-81a7-4653d4c500d0.png)

**Comment by novaugust** [comment]
@brennick I doubt anyone can debug your code by looking at a screenshot. Feel free to throw up a PR if you want feedback or help debugging (just keep in mind, this feature's in discussion - no guarantee a PR will get merged even if it's a great PR :smile: )

**Comment by novaugust** [comment]
derp, totally missed the "and here's my code" link. sorry

**Comment by brennick** [comment]
No worries, let me know what you think. I might be editing the wrong file? Not sure yet.

**Comment by adamcooke** [comment]
:-1: Unfortunately, this issue has caused me to lose the game and I am required by the rules to announce such a loss. This is that announcement.

**Comment by JohnONolan** [comment]
:joy:

**Comment by ErisDS** [comment]
Closing this in favour of implementing true collaboration features somewhere in the not-too-distant future... near enough that there's no need to do this as a stop-gap :wink:
