### ISSUE TITLE
Feature: Reading Time Helper

### ISSUE THREAD

**Issue by JohnONolan** [TryGhost/Ghost#4957]
Opening for discussion.

This one has been requested many many times in one form or another. I want to get a sense of whether it's worth pursuing.

Essentially this would be a simple `{{reading-time}}` helper available both in admin and in themes which would output the estimated average reading time based on the length of your post.

I think this feature is generally useful, and wouldn't add much overhead anywhere.

**Comment by novaugust** [comment]
This doesn't seem like something that needs to make it into ghost core to me. If people want to add reading time to their blog, it's as simple as adding something [like this](https://github.com/michael-lynch/reading-time) to their code-injection box, et voila. 
Not to mention, I doubt something like that works well with non-roman languages

**Comment by JohnONolan** [comment]
> it's as simple as adding something like this to their code-injection box

It's actually not - that implementation only works when applied to content on the current page. The most common implementation and use-case for reading time is to display the estimated reading time before someone decides to click through and open the post (eg. index.hbs) where only an `{{excerpt}}` is available.

> I doubt something like that works well with non-roman languages

That's a valid consideration, but it is absolutely secondary to English - which is our primary audience - and not a reason to omit this (or any) feature. Put another way: Translation is a progressive enhancement rather than a baseline requirement.

One alternative that might be worth considering is that the only thing reading-time estimates are based on is wordcount. So if there was a helper to make post word-count available to themes, it might have multiple use-cases including this one?

**Comment by nuclearpengy** [comment]
I would dig it if Reading time was part of Admin and displayed on posts, I'm not 100% sure if it's applicable to a page as a page is a slightly different animal to a post.

From an end user perspective, I often use reading time if a site(like medium) displays it, to help me triage which articles to read if I have a gap in my day.

Having this info available in the backend would be great from an author's perspective, getting some insight into how long it might take someone to read a post.

**Comment by isaaki** [comment]
+1

**Comment by dbalders** [comment]
While I think it is a good feature that will get used, I am kinda leaning towards agreeing with novaugust that I dont know if it should be built into core. On the one hand, It would be nice to have that feature and I am sure it would get used, but on the other hand, I do not think it would get used by the majority of users. Just based on my experience, I do not see this used on a large percentage of blogs. I would guess than less than 50% of users would use this feature and dont think it falls into the 'core principles'. I could be totally wrong and it might get used a ton, but in my experience, I don't see it very often.

While it might not be as easy as just throwing some JS into the code-injection, I think it should be more than do-able as an app. If you can double it into a word count helper like you suggested John, then that might be perfect and could have multiple uses. But, as a standalone only read time, I am leaning towards it being app territory.

**Comment by halfdan** [comment]
I do like the idea but considering that at some point there will also be post statistics it might make more sense to abstract this into a `{{statistic "name"}}` helper. This could then be easily extended by apps and later be used to provide other post statistics/metrics.

**Comment by nuclearpengy** [comment]
@halfdan that's an interesting take.

Average post reading time X min
Average time user spends on a post/page Y min
etc...

**Comment by RaoHai** [comment]
@halfdan +1

**Comment by JohnONolan** [comment]
@halfdan very good point

**Comment by JohnONolan** [comment]
Will come back to this at some point

**Comment by guidiego** [comment]
@JohnONolan @halfdan @nuclearpengy I'm really interesting in help on this part! I implement a simple helper (linked on this), and @ErisDS request me to read the discussion to understand how my PR can supply the problem, and I want to know more about the `statistics` helper :)
