### ISSUE TITLE
Blog logo upload button missing after uploading svg

### ISSUE THREAD

**Issue by frantzypants** [TryGhost/Ghost#4959]
### Issue Summary

![missing upload button](http://puu.sh/geNq4/2baf72eed8.png)

After you upload an SVG image as a logo to Ghost, you lose the ability to upload/remove a blog logo, even though the logo will still display on the frontend of the blog. 

### Steps to Reproduce

1. Access `/ghost/settings/general/`
2. Upload a .SVG image as a blog logo
3. Save settings
4. Blog logo upload button is no longer there, nor the logo (see screenshot above)

I believe the SVG image should display in the settings section, as well as the upload button, as it does with any other jpg, gif, png file type. 

### Technical details:

* Ghost Version: 0.5.8
* Client OS: Windows 8
* Browser: Chrome 40.0.2214.115 m

**Comment by PaulAdamDavis** [comment]
I have tested an SVG found online, and that works as expected. I also obtained a file which appears to disappear. Though the image itself is there in the markup – it just has no width or height. I've traced the cause to this.

The `svg` element inside an SVG file should have `width` & `height` attributes, like so.

```html
<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" 
    xmlns:xlink="http://www.w3.org/1999/xlink"
    viewBox="0 0 220 220" width="220" height="220" xml:space="preserve">
```

Without them, the file doesn't show. Validating the SVG without the width & height attributes shows that it is valid, but markup validators are stupid. so I'm not sure if those width & height attributes are required.

A possible fix is to set a min height & width on the image. That makes the broken file show as expected. But it's not a cure.

```
#blog-logo[$="svg"] {
    min-height: 80px;
    min-width: 80px;
}
```

**Comment by PaulAdamDavis** [comment]
Upon further investigation, it appears that an SVG without those `width` & `height` attributes won't appear properly in a `<button>` element which is what's happening here.

I think the fix here is to not use a button element to wrap the blog logo (and cover image, for goos measure). PR incoming.
