### ISSUE TITLE
App docs appear to be wrong

### ISSUE THREAD

**Issue by simonh1000** [TryGhost/Ghost#4963]
The [proxy section](https://github.com/TryGhost/Ghost/wiki/Apps-Getting-Started-for-Ghost-Devs) includes this example
```
this.app.api.posts.read(1).then(function (post) {
    console.log(post.title);
});
```
This did now work for me, and after some experimentation, I resulted in
```
      this.app.api.posts.read(1).then(function (data) {
        console.log(data.posts[0].title);
      });
```
But this gives me the first post, not the latest one which was my aim. Tweaking the `1` doesn't change anything. I would make an edit, but I'm too confused so far to dare.

**Comment by ErisDS** [comment]
Hi @simonh1000 - I think that this is a misunderstanding: 

`this.app.api.posts.read(1)`

Is asking the API to return the post with ID 1 - it's the equivalent of doing

`GET /ghost/api/v0.1/posts/1`

The wiki documentation you're reading is aimed at Ghost contributors who are interested in helping us build the app features, as apps aren't really a working thing yet.

Hopefully this explains what's going on :)
