### ISSUE TITLE
Invalid url from ghost_head helper 

### ISSUE THREAD

**Issue by cobbspur** [TryGhost/Ghost#4967]
On paginated tag and author pages an extra / is added to prev/next url from the ghost_head helper

![image](https://cloud.githubusercontent.com/assets/4405395/6426868/3b023b9e-bf66-11e4-9306-e47e20b44aac.png)

Steps to reproduce.
Ensure {{ghost_head}} helper is being used by your theme.
Write enough posts with one author or with a particular tag to require pagination.
Navigate to second page and view page source (in the head section).

**Comment by felixrieseberg** [comment]
I can take this one.

**Comment by cobbspur** [comment]
Sorry I meant to add, there is a second part to this problem which means we have to handle those links a little better.

At the moment the context is also lost in that when you are on the first page of author or tag archives, e.g. the next link is just page/2/ not /tag/cat/page/2/

http://puu.sh/gtaHQ/a79c30ec56.png

Also there is a rather nasty ternary operator in there with multiple 'prev=' (not your code but if you are happy to continue on this it would be good to clean up)

**Comment by novaugust** [comment]
@cobbspur isn't there another issue open for taht?

**Comment by felixrieseberg** [comment]
I did fix the context loosing issue, but I'll leave the code as it is right now (I'm lazy, I know).

**Comment by cobbspur** [comment]
quite possibly @novaugust it was something else I noticed when I was looking into the issue - not cross referenced it here among the other issues so :+1:  for the PR if that is the case

**Comment by cobbspur** [comment]
looks good to me

**Comment by novaugust** [comment]
@cobbspur comment on the PR, not the issue goof :D
