### ISSUE TITLE
Unable to place caret on certain lines in Markdown editor

### ISSUE THREAD

**Issue by matthewgertner** [TryGhost/Ghost#4974]
Quite frequently when editing a blog post, I am not able to click on a line to place the caret there. If I place the caret at the beginning of the line, hitting the right arrow causes it to skip straight to the next line. The only way to get the caret to where I want is to step backwards from the very end of the line. I'm wondering if I'm doing something wrong since otherwise I imagine the others would have reported such a serious problem.

I'm using Chrome on OS X.

**Comment by schuer** [comment]
Same here. Thx for reporting, Matthew.
