### ISSUE TITLE
Bug: PSM breaks when using keyboard navigation

### ISSUE THREAD

**Issue by JohnONolan** [TryGhost/Ghost#4978]
Steps:

- Open PSM
- Click on URL field
- Keep pressing TAB until it breaks

![psm-bug](https://cloud.githubusercontent.com/assets/120485/6443926/27019df8-c103-11e4-9603-ad1f7ceb5ebd.gif)

**Comment by novaugust** [comment]
Yay! I've run into that a few times, but never reproducibly - i always thought it was me being goofy. Nice

**Comment by felixrieseberg** [comment]
Dibs.
