### ISSUE TITLE
Invited users: default notification::browse permission missing

### ISSUE THREAD

**Issue by letsjustfixit** [TryGhost/Ghost#4979]
*Version: 0.5.9*

I've invited two users with admin:
 - alterego   : Author
 - alterego2 : Editor

After the successful signup -> login I've seen error 403 xhrs for the
>/ghost/api/v0.1/notifications/

>[{"message":"You do not have permission to browse notifications.","type":"NoPermissionError"}]

I guess the default permissions for those roles should include 
```
"permissions": {
      "notification":   ["browse"]
  }
```

**Comment by letsjustfixit** [comment]
to clarify its just the normal notification check after login but it should only be called if user role suggests its relevant

**Comment by jaswilli** [comment]
Hi @letsjustfixit,

Server/persistent notifications are currently used to display "system" type messages that an author or editor likely wouldn't have the ability to deal with anyway, so the permissions are correct.

An argument could be made for checking the role on the client and selectively checking the server notifications but at least for the time being just letting the API deny access to users that don't need to see the messages doesn't seem to be doing any harm so I'm inclined to leave it as is until it either becomes a problem or we're doing some other work on the notifications system at which point we could revisit this.
