### ISSUE TITLE
Wrong version of node-SQLite3 used

### ISSUE THREAD

**Issue by seanahrens** [TryGhost/Ghost#4980]
I'm quoting Dane, a developer of node-SQLite3:

"You need at least version 3.0.5 for node v0.12.0 support (which is the node version you are running). Please raise an issue with the ghost developers as they should be using node-sqlite3 v3.0.5 now.

Dane"

He wrote this reply in response to ghost install failure happening on my machine, erroring around sqlite3.

**Comment by iBotPeaches** [comment]
There is more needed for node v0.12 support as seen here - https://github.com/TryGhost/Ghost/pull/4955

**Comment by ErisDS** [comment]
Ghost doesn't support v0.12 yet, the issue linked above tracks progress, compatibility is written everywhere we can think of!

**Comment by seanahrens** [comment]
Ah, then the friction is in the ghost mac installation guide (http://support.ghost.org/installing-ghost-mac/).
Maybe I can help by making a small helpful edit to it to prevent other users running into the same problem I did?

The guide brings the novice user down the path of installing the latest Node.js version: Step 1 is "On http://nodejs.org press install, a ‘.pkg’ file will be downloaded". Since that will install v0.12.0 as of the time of this post, if users follow step one lock-in-step (what I did), they will install Node v0.12.0 and then run into subsequent installation errors.

[Yes, there is a banner that says Ghost recommends 0.10.x, but that didn't stop me from following Step 1 directly as it says (click and download the latest Node.js version).]

I'm happy to help with an edit to that guide to clarify one should only install the latest supported Node version, and not the latest, if I'm linked to a means of how to edit it.

Thanks.

**Comment by letsjustfixit** [comment]
@seanahrens 
Guide: https://ghost.org/about/contribute/
You should follow the translation one i guess and then send a pullrequest with the details..

**Comment by ErisDS** [comment]
The support.ghost.org site is not open source - I have now updated it to reflect the current state of affairs :)

**Comment by JohnONolan** [comment]
> The support.ghost.org site is not open source

Yet

**Comment by letsjustfixit** [comment]
I'm sorry my bad..

**Comment by seanahrens** [comment]
Thanks @ErisDS for updating that install guide. 

Incidentally, I still ran into install problems I couldn't get around (which I generated a new ticket for here: https://github.com/TryGhost/Ghost/issues/4981). In the meantime, I moved to the Bitnami installer to get things running, but wanted to report that roadblock as well in case I will install directly again or if it can help out other people.
