### ISSUE TITLE
Ghost Installation Error. Missing Handlebars/bin directory?

### ISSUE THREAD

**Issue by seanahrens** [TryGhost/Ghost#4981]
Following the installation guide at http://support.ghost.org/installing-ghost-mac/, I ran into the following problems on the step of installing ghost:

```
Seans-MacBook-Pro:ghost-0.5.9 Sean$ npm install --production
npm WARN package.json handlebars@2.0.0 No README data
npm ERR! Error: ENOENT, chmod '/Users/Sean/ghost-0.5.9/node_modules/handlebars/bin/handlebars'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Darwin 14.1.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "--production"
npm ERR! cwd /Users/Sean/ghost-0.5.9
npm ERR! node -v v0.10.36
npm ERR! npm -v 1.4.28
npm ERR! path /Users/Sean/ghost-0.5.9/node_modules/handlebars/bin/handlebars
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/Sean/ghost-0.5.9/npm-debug.log
npm ERR! not ok code 0
...
Seans-MacBook-Pro:node_modules Sean$ cd handlebars
Seans-MacBook-Pro:handlebars Sean$ ls
LICENSE		coverage	package.json	runtime.js
```

It appears there is a missing bin directory in the handlerbars npm_module directory. But as I'm green to Node, my searches online for a resolution to this came up empty.

**Comment by letsjustfixit** [comment]
I might be wrong -again- but it smells like an npm issue to me. Based on
http://stackoverflow.com/questions/15482658/mac-npm-erroring-with-enoent
npm cache clean
or if installed under su
sudo npm cache clean

**Comment by novaugust** [comment]
@letsjustfixit Does that mean you've resolved this on your own then? I'm going to close it under that assumption, just let me know if I'm mistaken :+1:
