### ISSUE TITLE
Bug: Cursor Stays on the Right Side for the First Character on New Line

### ISSUE THREAD

**Issue by dbalders** [TryGhost/Ghost#4983]
### Issue Summary

When typing up a post, the cursor will stay on the right side for just one character as you move to a new line. This does not seem to happen on the first 2 lines of the post, but happens on everyone since then.

![screen shot 2015-03-02 at 2 39 49 pm](https://cloud.githubusercontent.com/assets/4715098/6452394/58f07366-c0ea-11e4-9b11-181a1984f6cb.png)
![screen shot 2015-03-02 at 2 42 34 pm](https://cloud.githubusercontent.com/assets/4715098/6452403/65b301ae-c0ea-11e4-9bc2-fa2fd46c12e8.png)
![bug cursor](https://cloud.githubusercontent.com/assets/4715098/6452423/877e7912-c0ea-11e4-84ed-c964384627ce.gif)

### Steps to Reproduce

Open up a new post, type a few lines, when the first character moves to the next line, the cursor will stay on the right. Only seems to happen when it is one letter, not a word moving down to the next line.

### Technical details:

* Ghost Version: 0.5.9
* Client OS: Mac
* Server OS: Mac
* Browser: Chrome
* Database: SQLite

**Comment by novaugust** [comment]
dup of #4974 ?

**Comment by dbalders** [comment]
looks like it might be a little bit different symptoms with where the cursor is moving, but highly possible it is the same bug and the same problem. I would guess fixing one fixes the other
