### ISSUE TITLE
API: testing & development: soapui project

### ISSUE THREAD

**Issue by letsjustfixit** [TryGhost/Ghost#4985]
Hy,
Based on the current document: 
https://github.com/TryGhost/Ghost/wiki/%5BWIP%5D-API-Documentation#permissions-1
I've created a soapui project. it would be a LOT easier to do so if you have/could generate a WADL lurking around..
Thanks!

https://gist.github.com/letsjustfixit/94ad11eb09d37842d9a9

**Comment by novaugust** [comment]
Hi @letsjustfixit, I'm not really sure what soap/wsdls have to do with ghost (and it's json rest api). Maybe you'd like to be more explicit about what you're trying to do? 
I don't think it's up to the Ghost repo to maintain files for tools we don't use. Things'd get bloated around here pretty quick.

**Comment by letsjustfixit** [comment]
I'm sorry I tought WADL-s are stroct standard formats so there is no confusion and checking in trillion issues how/where/what the api sends/consumes. Seems I was wrong sorry.
