### ISSUE TITLE
Navigation URL validation is too strict

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#4989]
The test for whether or not a URL `isRelative` in the new `gh-navitem-url-input` component  is supposed to check if the url is a relative one, and prepend the base URL if so, to make the URL absolute.

However, it ends up checking if the URL is a valid url as it is, and if not it appends the base URL, meaning any invalid URL ends up with the base URL appended.

This has a positive side effect in that it prevents the field from being potentially misused to save unsafe urls like `javascript:alert(1)`.

It also has a negative side effect in that it prevents users from using valid URIs which are not URLs like `mailto:me@myaddress.com`.

I think that the `isRelative` check needs to be updated to do a better job of checking for what is or isn't a relative URL.

We also then need to add correct validation/santisation to prevent the URL field from being misused.

**Comment by karloscarweber** [comment]
Could I add that the logic in the new navigation.js controller is too strict in assuming that all URL's should end in `/`. For example, if I wanted to end a url in a hashtag like so: `http://kow.fm/#blog-index` then It would append a slash on the end thus breaking the hash link.

The check for a slashless ending starts on line 130 of `core/client/controllers/settings/navigation.j` : 
```
                    // if the last char is not a slash, then add one,
                    // this also handles the empty case for the homepage
                    if (url[url.length - 1] !== '/') {
                        url += '/';
                    }
```

Obviously some of us don't want our urls to have a slash at the end.

**Comment by p-e-w** [comment]
Another issue is that the current UI does not allow protocol relative URLs, so properly serving a blog both via HTTP and HTTPS is impossible. Phone number links using `tel:...` URIs also do not work.

Perhaps I'm missing something, but how is allowing arbitrary strings "misuse"? Users are already able to include arbitrary JavaScript in any post. What is the difference between that and entering any navigation URI? It seems to me that by far the best option would be to allow the user to enter any string and put that in the `href` attribute without any processing whatsoever. As a courtesy to the user, Ghost might indicate a malformed URL as such in the UI, but that should not prevent saving. This issue is by far the biggest weakness of the navigation system at the moment.

**Comment by p-e-w** [comment]
Skype's `callto:` URIs are also unsupported by the current validator.

**Comment by TZer0** [comment]
It also seems to have an issue with with things that have the following format:
`http://example.com:535`
This is changed to:
`http://example.com/:535/`

**Comment by heidiv** [comment]
My ghost installation is located at example.com/writing and I'd like to link to "Home" at example.com in the navigation but am unable to as /writing always gets appended. Not sure if this is a bug or a limitation? Thanks!

**Comment by ErisDS** [comment]
@heidiv this sounds like a bug very much related to this issue, thanks

**Comment by CraigyDavi** [comment]
@heidiv Yes I'm having the same issue as you are. My blog is at `example.com/blog/` and I want to link to `example.com/projects/` but unfortunately the limitations mean it gets set to `example.com/blog/projects` instead.

**Comment by trendsetter37** [comment]
@davisonio I am encountering the same as well. We have ```example.com/blog/``` hosting ghost but would like to use ```example.com/``` and ```example.com/events```. However, ghosts automatically appends the base url which is unwanted.

**Comment by ErisDS** [comment]
Thanks for providing more examples. The validation & url handling logic in the navigation UI does need revisiting, providing examples is really helpful as we can start to add a bunch of test cases that need to work, and then figure out how to solve them.

**Comment by kevinansfield** [comment]
I may be mistaken but I think all of the issues mentioned in this discussion have now been resolved and have tests to avoid regressions. Are we ok to close this in favour of new issues for any specific bugs that pop up?

**Comment by ErisDS** [comment]
Yep cool 👍
