### ISSUE TITLE
Why open graph meta tags are not being render in root url?

### ISSUE THREAD

**Issue by wcalderipe** [TryGhost/Ghost#4991]
There's a good reason for open graph meta tags are not being render in root url?

I was showing my blog to a colleague in Facebook then I notice a strange description for it when I pasted the root url (that you can see below).

> We've put together a little post to introduce you to the Ghost editor and get you started. You can manage your content by signing in to the admin area at <​your blog URL>/ghost/.

I noticed that in `core/server/helpers/ghost_head.js` line 90 there's an if statement checking for post pages and just adding structuredData if it is!

**Ghost version 0.5.8**

**Comment by JohnONolan** [comment]
Hi there, this is currently intentional - yes - in short, because there is no clear answer to the question:

If open graph tags are included on the home page, what content should they contain?

**Comment by wcalderipe** [comment]
In my point of view let a placeholder/alert message is worse than nothing or just the blog description.

What do you think about an edit section like post meta tags?

The only workaround I can see for this is using code injection or editing the default.hbs  but both will need some url validation that could not be so friendly for non developer people that just want a description when pasting their blogs/pages on facebook!

**Comment by wcalderipe** [comment]
I created a new partial called home_meta.hbs

```language-markup
<meta property="og:title" content="{{meta_title}}" />
<meta property="og:description" content="{{meta_description}}" />
<meta property="og:type" content="website" />
<meta property="og:site_name" content="{{@blog.title}}">
<meta property="og:url" content="{{@blog.url}}{{url}}"/>
<meta property="og:image" content="{{@blog.cover}}" />
<meta name="twitter:title" content="{{meta_title}}" />
<meta name="twitter:description" content="{{meta_description}}" />
<meta name="twitter:url" content="{{@blog.url}}{{url}}" />
{{#if @blog.cover}}
  <meta name="twitter:card" content="summary_large_image" />
  <meta name="twitter:image:src" content="{{@blog.url}}{{@blog.cover}}" />
{{else}}
  {{#if @blog.logo}}
    <meta name="twitter:card" content="summary_large_image" />
    <meta name="twitter:image:src" content="{{@blog.url}}{{@blog.logo}}" />
  {{/if}}
{{/if}}
```

Then I include it in the default.hbs after the `{{ghost_header}}` checking if post exists.

```language-markup
{{ghost_head}}
{{#unless post}}{{> home_meta}}{{/unless}}
```

This isn't a pretty solution but well it will resolve the problem for a while. If you guys did a different way please tell me.

**Comment by wcalderipe** [comment]
I went to https://developers.facebook.com/tools/debug/og/object/ to test it and this fixing works fine.

**Comment by ErisDS** [comment]
I think this question has been answered, so closing.

**Comment by waldemarnt** [comment]
Sorry but it's very frequent question,over the internet have people with the same problem, i have the same problem, and i can't saw a answer here, can you guys explain a way to fix that?
Tnx
