### ISSUE TITLE
Why Ghost use doubleclick.net?

### ISSUE THREAD

**Issue by waqaskhan137** [TryGhost/Ghost#4994]
Hi, 
I have Disconnect extension and It shows that ghost uses some information collection sites 

* google-analytics.com
* double-click.net 
* wordpress.com
* gravatar.com

Why you are using those any good reason ?
How can I stop those?
Thnaks,

**Comment by ErisDS** [comment]
Hi @waqaskhan137,  all information about any privacy-related issues in the Ghost software can be found explained in detail in our [PRIVACY.md](https://github.com/TryGhost/Ghost/blob/master/PRIVACY.md) file.

It explains the use of gravatar and the usage info collection mechanism and how to turn it off.

The Ghost software does not use google analytics, double-click or wordpress.com (although gravatar is owned by the same people as WordPress).

If you're seeing other things in your extension then it must be something to do with either your theme or your host, not the software itself, and you will need to contact the theme developer / your host to find out more.

**Comment by waqaskhan137** [comment]
Thanks @ErisDS but I am not using any theme and still it shows those results? (I have updated the Snapshot too )

**Comment by letsjustfixit** [comment]
Hy,
If I'm right you are converting your wordpress blog.
I think during the convert there are static objects that are linked from the database (in your posts) like images and all sorts of scripts. 

gravatar.com is surely called because ghost uses your gravatar connected to your email account (if available) by default.
If you have problems with that you should read the link @ErisDS provided for your.
It's all explained in detail. If you would like to only get rid of the integrations ghost has by default you can check all the setup instructions here:
http://support.ghost.org/config/#privacy
Good luck :pray:

**Comment by waqaskhan137** [comment]
Thanks for reply, 
Hmmm yes you are right about converting my Wordpress here and I have images linked but still that doesn't explain the double-click.net, And The link she provided doesn't say anything about google-analytics  or double-click.net

**Comment by letsjustfixit** [comment]
Hy,
Well I'm also running quite a few ghost instances as I'm trying to get to its inner workings but there is no reference what so ever to those two. Are you quite sure about that your blog posts/plugins etc. doesnt contain anything realted to those?
If I were you I'd just do a quick grep -R  on the db file you've imported...
On the other hand make sure you are running a vanilla ghost instance downloaded from ghost.org without any custom themes etc which might add stuff like that. ghost core doesnt conain anything like that you can be sure about it :)

**Comment by shindakun** [comment]
@waqaskhan137 The Disqus plugin will call Google Analytics. Not sure about the double-click call it could be coming from one of the other browser add-on's you have installed.

**Comment by gotdibbs** [comment]
@waqaskhan137 The doubleclick interaction is likely due to Google Analytics, see: https://support.google.com/analytics/answer/2444872?hl=en

**Comment by HLFH** [comment]
Btw, I got doubleclick.net on Ghost because of the missing Chromecast extension. http://stackoverflow.com/questions/24490323/google-chrome-cast-sender-error-if-chrome-cast-extension-is-not-installed-or-usi
