### ISSUE TITLE
Code Injection: Line numbers and syntax highlighting

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#4995]
We currently have the lovely [code injection](#1993) feature, which is accessible via the labs page.

In order to get this ready to be fully shipped and no longer classed as a 'labs' feature, we want to upgrade the textarea to have nice syntax highlighting and line numbers for the HTML/JS/CSS code that will likely be pasted in.

There are three main things to do to complete this:

1. decide on what editor library to use to add the new functionality, this could be CodeMirror or suggestions are welcome (CodeMirror is being dropped from the main Ghost editor, so there's no longer a requirement that it be that) 
2. make sure the syntax highlighting and line numbers are styled to look like they fit in the Ghost admin, this might take a bit of toing and froing with the core team 
3. wrap the fancy textarea functionality up into a little ember component so we can reuse it elsewhere in the admin

This might be a bit of a punt for a `beginner` issue, but I'm confident it suits someone new to the Ghost codebase as it's mostly a wiring job :)

**Comment by acburdine** [comment]
@ErisDS One code editor that I've experimented with in the past is [Ace](http://ace.c9.io). It has a pretty good interface. It might require some custom theme work, but I think it could be made into a decent Ember component. I found one [here](http://hbrysiewicz.github.io/2014-04-22-ace-ember-editor.html).

**Comment by PaulAdamDavis** [comment]
I think [PrismJS](https://github.com/PrismJS/prism) might be a good choice here? It's probably the most lightweight and easiest to style. ([Examples](http://prismjs.com/))

Only issue is, PrismJS is only a highlighter. It's used as an editor on http://dabblet.com, but to the best of my knowledge, there's no guide anywhere on how that's done. The [code is available](https://github.com/LeaVerou/dabblet/tree/master/code) though, so it should be possible to work it out form there.

**Comment by CWSpear** [comment]
I'll second my support for Ace. It's powerful and widely used, and not terribly difficult to set up and has reasonable defaults, but is also very customizable. It has a very Sublime-y feel. It's used on GitHub (gists, for one), Plunker, Codeacademy and Khan Academy and many other places. It's part of the Cloud9 Web IDE. Not really relevant to this use case, but it's performs *very* well for what it is. It is sizeable, but no hard dependencies like jQuery.

Demo: http://ace.c9.io/#nav=about
License: BSD
GitHub: https://github.com/ajaxorg/ace

**Comment by acburdine** [comment]
I'll pick this one up.

**Comment by ErisDS** [comment]
:+1: - just for context I think it was agreed in this week's meeting that ace is probably the right approach?

**Comment by acburdine** [comment]
Yeah. I'm almost done with it, just working out a few styling things.

**Comment by acburdine** [comment]
For context, Ace has been scrapped in favor of CodeMirror, mainly because CodeMirror is a lot smaller in file size. I will work on getting a component for CodeMirror done as soon as I can.
