### ISSUE TITLE
Accessibility: Spacebar/Enter doesn't activate focused link on `/ghost`

### ISSUE THREAD

**Issue by novaugust** [TryGhost/Ghost#4996]
## Issue Summary

Using tab to navigate around the main menu, I'm unable to activate any of the links using spacebar (no effect) or enter (opens post for editing)

![tabbing](https://cloud.githubusercontent.com/assets/1207005/6511535/c0aa9238-c32a-11e4-9289-e6afbbee9a70.gif)

## Repro Steps

1. Go to `/ghost`
2. Tab until you get to the settings button
3. Hit enter

## Issue Summary

- Chrome 41.0.2272.76
- Ghost master
- Max OSX yosemite

**Comment by felixrieseberg** [comment]
This is actually important for accessibility, too. I'll take this one.

**Comment by novaugust** [comment]
Closed by magical ember-cli merge? Can no longer reproduce
