### ISSUE TITLE
Tags sometimes disappear on post save

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#4999]
I've seen this happen on at least one occasion. As I tend to have one-tag-per-post I thought I was imagining it and simply hadn't added my tag yet... but alas, this is seems to be an ongoing issue.

### Steps to Reproduce

This is as yet unknown, I've had a play around and not yet seen it happen whilst I was looking for it.

It does appear to happen whilst the editor is open. i.e it doesn't require a refresh to notice that the tags are missing. I have a sneaking suspicion it may be related to an action in the PSM but I haven't found out what yet.

### Technical details: 

Seen in 0.5.8 & 0.5.9, not sure before then

**Comment by ErisDS** [comment]
Possibly related, tags also go blank/empty on occasion, and cause save errors:

![](http://puu.sh/h3MVs.png)

**Comment by Jean85** [comment]
I can confirm this. I have a blog hosted by Ghost(pro) itself, so we're using the last version... 0.6.3 maybe?

I've seen al my tags disappear, and I have a lot of previous published articles that now are without tags, but the tags are showing in the Tag section, with a 0 article count.

**Comment by ErisDS** [comment]
We have significantly changed the way that tags are added and saved, moving them into the post settings menu. This bug has not been seen on master - and any similar issues occurring in future are likely new bugs rather than the same one.
