### ISSUE TITLE
Semantic versioning guidelines say build info is after a + plus, not a - minus

### ISSUE THREAD

**Issue by jaysonminard** [TryGhost/Ghost#5000]
For tools that want to support semantic versioning and identify compatibility of upgrades, suggest updates, etc.  They need to follow a standard.  You almost follow Semantic versioning other than you use -buildInfo instead of +buildInfo ... so your software could be seen as "prerelease" because of that usage.

**Comment by ErisDS** [comment]
Hi @jaysonminard. Could you please explain where you are seeing this? Except for release candidates, where we correctly use `-`, none of our official releases use `-`?

**Comment by jaysonminard** [comment]
Sorry, it is only  from your readme:

>>>

For transparency and insight into our release cycle, along with striving to maintain backward compatibility, Ghost will be maintained according to the Semantic Versioning guidelines as much as possible.

Releases will be numbered with the following format:

<major>.<minor>.<patch>-<build>

Constructed with the following guidelines:

A new major release indicates a large change where backwards compatibility is broken.
A new minor release indicates a normal change that maintains backwards compatibility.
A new patch release indicates a bugfix or small change which does not affect compatibility.
A new build release indicates this is a pre-release of the version.

**Comment by ErisDS** [comment]
> A new build release indicates this is a pre-release of the version.

So when we have done release candidates, E.g. 0.5.2-rc2 this was a prerelease of 0.5.2, as seen here:  https://github.com/TryGhost/Ghost/releases

This is the correct usage of semver.

**Comment by jaysonminard** [comment]
Yes is correct, only your description of what you do from readme is wrong. All good.
