### ISSUE TITLE
Provide links in shortcut UI to insert MarkDown

### ISSUE THREAD

**Issue by thedannywahl** [TryGhost/Ghost#5006]
#4368 enables mobile uploads kind of paving the way for mobile authoring.  I think the shortcut help UI should provide links (maybe around the shortcut entry) that returns the MarkDown to the editor as if the user had used the key command.

![shortcut with link](https://cloud.githubusercontent.com/assets/743499/6551134/b3a4fdfc-c66e-11e4-8205-41c73d4fb5dd.png)

I think it would be easier for a mobile user to tap `?` -> `Ctrl/⌘ + Shift + I` to insert image code than it is to type the image code using the onscreen keyboard.

**Comment by felixrieseberg** [comment]
I like that idea. I'm boarding a plane in a minute and I'll see if there isn't an elegant way to implement this.

**Comment by novaugust** [comment]
Huh, very cool idea. 

@felixrieseberg shouldn't be too hard to do with actions... actually, i lied. it will be hard, because I don't think that modal is opened within the context of the editor (the modal lives at application scope, so its actions won't hit the editor) 
Maybe if/when we start using liquid-fire for modals, we'll be able to do this easy

**Comment by felixrieseberg** [comment]
@novaugust: Thoughts on just going with `{{action "foo" target="view.targetView"}``?

**Comment by novaugust** [comment]
It'd be a hack either way. `view` in that context will refer to the
application view

**Comment by felixrieseberg** [comment]
I know - this is shocking, but the above should work (according to Ember's Luke). I'll give it a spin.

**Comment by felixrieseberg** [comment]
Okay, it is difficult - :cookie: for @novaugust. We have a mobile codemirror, which we should probably get rid of at some point - and components are indeed flying all over the place. Plus, I don't actually know how one would launch the help menu in our mobile view right now. In summary, :+1: on the idea, but this one might be too much work for feature right now.

**Comment by ErisDS** [comment]
This should (possibly) be much easier now there is no more codemirror?

**Comment by ErisDS** [comment]
This didn't get traction, and I think the upcoming editor overhaul will solve this in a different way, meaning it's probably not worth doing just now.
