### ISSUE TITLE
shortcut UI should pass through shortcuts

### ISSUE THREAD

**Issue by thedannywahl** [TryGhost/Ghost#5007]
When user has the shortcut help UI open if they press a shortcut combination it should pass that through to the editor, and possibly close the modal.

This would require cursor position to be remembered for the markdown to be returned.

**Comment by novaugust** [comment]
I think it's unintuitive for you to be able to type into / effect the editor when you can't see it behind a modal

**Comment by jaswilli** [comment]
Agreed.  Going to close this but if anyone wants to comment further please do and it can always be revisited.
