### ISSUE TITLE
Better post image meta data

### ISSUE THREAD

**Issue by JohnONolan** [TryGhost/Ghost#5009]
Unlike in the post content - when a user uploads a featured post image, we don't provide any way to set alt text. So, as a default we simply make the alt text "Post image"

Here's a quick win for bloggers who are keen on Pinterest, which could be a really nice progressive enhancement - http://www.gimmesomeoven.com/one-thing-must-every-image-uploaded-blog/

By default if you try to Pin a Ghost - our OG tags will send the post image as the image to be pinned for the article, as well as the post title and the source URL. So we could optimise that slightly further by generating a really good set of alt text to go with it, simply by using `{{meta_description}}` as the alt text for the post image.

![image](https://cloud.githubusercontent.com/assets/120485/6554172/7f0af31a-c661-11e4-9bdd-948a2268d1db.png)

## Bonus Step

after `{{meta_description}}` output a space and then `#{{tag}}` - based on the tags of the post, but never more than 1. Pinterest - unlike other social networks - is extremely fussy about the use of tags and the general consensus is to keep it minimal.

**Comment by ErisDS** [comment]
Related: #4867

**Comment by JohnONolan** [comment]
I'm a silly fool. The {{image}} helper only outputs the image URL, the tag and alt text is defined by the theme. This is a Casper issue.
