### ISSUE TITLE
Bug: Admin/Setup page not loading on 0.5.9

### ISSUE THREAD

**Issue by SxDx** [TryGhost/Ghost#5010]
### Issue Summary

Fresh install of ghost 0.5.9 from zip, index page is loading fine but the admin/setup pages display only empty pages with the following errors in the javascript console:
```
[Error] Viewport argument key "minimal-ui" not recognized and ignored. (setup, line 12)
[Error] SyntaxError: Unexpected end of script (anonymous function) (vendor.min.js, line 16)
[Error] ReferenceError: Can't find variable: define global code (ghost.min.js, line 1)
```

### Steps to Reproduce

1. Download and unzip ghost 0.5.9
2. run `npm install --production`
4. setup nginx 
```
    server {
       listen 80;
       server_name url.com;
       access_log /home/deploy/logs/url.com/access.log;

        location / {
           proxy_set_header X-Real-IP $remote_addr;
           proxy_set_header HOST $http_host;
           proxy_set_header X-NginX-Proxy true;

           proxy_pass http://127.0.0.1:2368;
           proxy_redirect off;
       }
    }
```
3. run `npm start --production`
4. Visit http://url.coml/ghost

### Technical details

* Ghost Version: 0.5.9
* Client OS:  OSX 10.10.2
* Server OS: Ubuntu 14.04
* Node Version:  0.10.33
* Browser: Chrome
* Database: sqlite

**Comment by ErisDS** [comment]
Hi @SxDx can you please clarify where you downloaded the zip from & how you installed it? This is not reproducible for me using the build zip from GitHub & the install instructions here: http://support.ghost.org/installing-ghost-linux/

**Comment by SxDx** [comment]
Hello @ErisDS,
I followed the instructions on http://support.ghost.org/installing-ghost-linux/, they are pretty straightforward so I think i installed everything correctly.

**Comment by ErisDS** [comment]
In that case, I recommend checking that the site works without nginx, and then if that works, re-adding nginx using our [recommended config](http://support.ghost.org/basic-nginx-config/). If it doesn't work, I recommend reinstalling again from scratch.

As part of the release process and in response to you raising this issue, I've successfully installed Ghost 0.5.9 multiple times, therefore I'm very certain this is not a bug, but rather a setup issue.

**Comment by komocode** [comment]
Spent hours trying to fix the same issue. The recommended config does not work. The .js file is too big and nginx does some special handling with big requests. You need to add "proxy_buffering off;". Here's what mine looks like:

```     server {
       listen       80;
       server_name  www.blah.com;
        

       location / {
          proxy_buffering off;
          proxy_set_header   X-Real-IP $remote_addr;
          proxy_set_header   Host      $http_host;
          proxy_pass         http://127.0.0.1:2368;
       }
     }
