### ISSUE TITLE
'Enter' keystroke behavior when editing blog logo and cover

### ISSUE THREAD

**Issue by pgrunwald** [TryGhost/Ghost#5018]
When changing the URL of the blog logo and blog cover with `fileStorage: false`, pressing enter after typing the URL does not add the image, but behaves like the "Cancel" button was clicked. Clicking "Save" adds the image as expected.

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.111 Safari/537.36

**Comment by felixrieseberg** [comment]
I can take a look at this.

**Comment by iainjp** [comment]
Hi! I'm currently working on a fix for this just now. Should be with you as an MR shortly :smile:

**Comment by ErisDS** [comment]
:+1:
