### ISSUE TITLE
Bug: Post save/update button sometimes cut off in Firefox

### ISSUE THREAD

**Issue by frau-sma** [TryGhost/Ghost#5023]
[I really, really hope this is not a duplicate of an existing issue again! I’ve both searched and browsed the existing issues and haven’t been able to find anything related.]

### Issue Summary

In the Ghost editor, for some of my posts, the save draft/update post button is cut off in Firefox. It is pushed so far to the right that the dropdown menu button isn’t there. (See screenshots below for clarification of how this looks.) So if a post is still a draft, I can’t publish it from within Firefox, I have to open the editor in another browser and publish my post from there; if a post is already published, I can’t unpublish it; and I can’t delete posts with the issue.

### Steps to Reproduce

I’ve had this issue for quite a while, but haven’t reported it yet because I tried to find out _when exactly_ it appears, so that I would be able to tell you how to reproduce it. I’m really sorry that I can’t seem to nail it down. It happens on some of my posts and does not happen on others. I can’t find any obvious difference between the posts on which it happens and the posts on which it doesn’t. It does not have anything to do with the post’s status, it happens for some draft posts and not others, and for some published posts and not others. It doesn’t have anything to do with the size of my browser window, it even happens in fullscreen mode.
It might have something to do with the number of tags on the post, though the relation is definitely not as simple as “posts with a lot of tags have the issue”. I can’t currently find a post with very few tags that has the issue, but I don’t write posts with few tags very often. For some of the posts with a lot of tags (so that I have to scroll them), the issue is there; for some with just as many tags, it is not. For the posts with the issue, deleting a few tags can fix the issue, but adding them again brings it back.

I’ve finally decided to report the issue even though I can’t tell you exactly how to reproduce it. Perhaps someone else has experienced it as well and has some more clues. If you have any ideas which characteristics I might want to compare between the broken posts and the ones that are fine, or if you need any more data about the issue or about my system or anything, please let me know!

Screenshot of a broken post:
![Broken save/publish button in Firefox](https://cloud.githubusercontent.com/assets/1026511/6575251/6a7d4e80-c72d-11e4-9bdb-599f82926168.png)

Screenshot of a post with the button intact:
![Intact save/publish button in Firefox](https://cloud.githubusercontent.com/assets/1026511/6575258/7586f84e-c72d-11e4-8bae-d5ceb96e8508.png)

I’ve removed the actual tag names from both screenshots because I found them distracting and irrelevant to the issue, but I’ve left the tag bubbles and the X symbols as they were. As you can see, both posts have enough tags that they have to be scrolled. On the broken screenshot, it looks as if the whole black tag bar is too wide for my browser window, for some reason. You can see that the little tag symbol and the first tag are cut off at the left edge, and the button is cut off at the right edge.
I’ve only taken screenshots of draft posts, but it looks exactly the same, only with the “update post” button instead of the “save draft” button, on published posts.
The amount by which the black bar seems to be too wide is different for different posts, so there can be more or less of the button cut off, and sometimes there’s even a little part of the dropdown button left that I can still click.

### Technical details

* Ghost Version: currently 0.5.10, but this has been an issue since … about 0.5.3 or 0.5.4, I think, though I’m afraid I don’t remember exactly when it first happened to me; it wasn’t always an issue, it appeared with an update to some 0.5.x version
* Client OS: OS X Yosemite (10.10.2)
* Server OS: FreeBSD 9.3
* Node Version: 0.10.35
* Browser: Firefox (always the latest version, currently 36.0.1)
* Database: Postgres

**Comment by novaugust** [comment]
hi @frau-sma, thanks for the incredibly detailed issue report! Very much appreciate you nailing the format like that.
We'll get looking into this, but in the meantime, I want to save you the work of having to publish from another browser - if keyboard shortcuts are your thing, `alt+cmd+p` will publish your post on oxs :)

**Comment by frau-sma** [comment]
Thank you, Matt! I tried hard to be as close as possible to the suggested format without actually, you know, telling you how to reproduce the issue. (;
I’ll try to memorise the keyboard shortcut for now, thanks! It isn’t much of a hardship to publish posts from another browser, but it isn’t quite the ideal workflow, so if you can figure out what causes my issue, that would be splendid!

**Comment by PaulAdamDavis** [comment]
Hi @frau-sma, this is an brilliant bug report!

I spent a bit of time looking into this after reproducing the issue, and unfortunately it's not a quick fix.

To fix this, the publish bar CSS needs to be rewritten, but I think the effort isn't worth it. There are plans to do something with tags which would mean rewriting much of this, so it's not worth rewriting twice.

I'm going to close this as it won't be an issue forever. :)

**Comment by frau-sma** [comment]
Thanks for looking into this and identifying the issue, Paul! I’ll keep my fingers crossed that you’ll get around to rewriting the other tag stuff in the foreseeable future! (:
