### ISSUE TITLE
No RSS description field

### ISSUE THREAD

**Issue by FatEd11** [TryGhost/Ghost#5025]
When looking at the rss feed for my blog [here](http://blog.lumbrjack.com/rss/), it looks as if the entire post content is output between the `<description></description>` tags.

It's my understanding that the `<description>` tags should be used for a summary of the content? As proof, when trying to create a RSS driven mailchimp campaign for my ghost blog I have the whole content of articles being put into the email.

When I look at a WP blog, it appears they put all the content above the `---Read more---` more line into the description.

The description could be: another field in the post editor (like a subtitle); or it could pull from the META description (I imagine easier as this already exists); or just use the first paragraph?

I'm aware they may be some more intelligent reason not to do this that I haven't thought of. But I couldn't find any issues relating to this specifically, nor anything in the epics. Please close though if this has been addressed elsewhere!

**Comment by ErisDS** [comment]
Hi @FatEd11, you're entirely correct that our RSS feed is a bit weird. We have issues #3993 and specifically #2263 open at the moment, as we know that we need to audit our RSS feeds and effectively start over. 

I'm going to close this issue as I don't think we need another one open against the RSS, but we do know we need to fix these problems.
