### ISSUE TITLE
Markdown conversion assumes `<pre>`

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#5028]
A lot of the places where we do special handling in our markdown conversion, we pull out `<pre>` blocks so that they are kept as-is.

However, in much of the code, it is assumed that the tag will appear without any attributes, i.e. it assumes that there will be exactly `<pre>`. This doesn't account for the fact that all html tags can have attributes, and that it may appear something like: `<pre class="my-class">`.

This causes some small, subtle, and annoying bugs with the special rules like underscore handling, footnotes, highlighting etc = all of which will incorrectly affect whatever appears inside the `<pre>` tag.

**Comment by willard1218** [comment]
How can I specific attribute in <pre>  ?
I'm using Prism [line-highlight](http://prismjs.com/plugins/line-highlight/)  feature 
```data-line=2
var a ;
a = 1;
a ++;
```
it will be translate to
<pre class=" language-data">
   <code class="-line=2 language-data">
  var a ;  
  a = 1;  
  a ++;  
</code>
</pre>

**Comment by kirrg001** [comment]
The new `markdown-it` renderer (#8451), which was merged into master master, supports this.
