### ISSUE TITLE
Bug: url helper breaks subdomain URLs (navigation issue)

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#5033]
[Original report](https://ghost.org/forum/bugs-suggestions/18510-navigation-links-with-a-subdomain-of-the-base-url-do-not-work-in-the-menu/)

Using a subdomain of your blog's main URL in the navigation helper results in the base url being output on the frontend. The url is correctly stored as an absolute URL in the settings table, therefore the problem must lie in the handling of the URL in `config/url.js`. 

In short, the input is correct but the `{{url}}`` helper's output is incorrect.

### Steps to reproduce

Example:
My blog is `hannah.wf` 
I host a GitHub project at `mycode.hannah.wf`
I enter the following into the navigation settings page:

![](http://puu.sh/gzCGx.png)

What gets output by the navigation helper:

```
<ul class="nav">
    <li class="nav-code" role="presentation"><a href="http://hannah.wf//">Code</a></li>
</ul>
```

### Technical details: 

* Ghost Version: master / 0.5.10

**Comment by jillesme** [comment]
I'd like to take this on, can I?

**Comment by ErisDS** [comment]
@jillesme sure thing :)

**Comment by ianlopshire** [comment]
The issue is in `config/url.js` [here](https://github.com/TryGhost/Ghost/blob/master/core/server/config/url.js#L159-164)
