### ISSUE TITLE
Namespace Table Names

### ISSUE THREAD

**Issue by esatterwhite** [TryGhost/Ghost#5035]
With Ghost being used more and more as a dependency it is increasingly likely that collisions in table names may arise. names like `user` and `permission` are rather common.

Table Name should be changed to include a general namespace, preferably one that indicates that the table is used by ghost, or relates to the general functional component the table is used for. 

For example:

* ghost_core_setting
* ghost_core_app
* ghost_core_app_setting
* ghost_core_post
* ghost_core_tag 
* ghost_auth_user
* ghost_auth_role
* ghost_auth_permission

This is also a good set up for standard naming conventions when pluggable apps are a thing. 
table names can follow `ghost_[APP]_[MODEL]`

**Comment by esatterwhite** [comment]
Also, and this might be more of a problem with bookshelf, but the generated many-to-many tables are created with foriegn keys, they are just integer fields set to NOT NULL. The columns should be FKs ( indexed w/ constraint ).

**Comment by letsjustfixit** [comment]
even better it *should* be configured via a config.js param..

**Comment by esatterwhite** [comment]
I don't think table names should be exposed to via configuration. Somethings just need to be known, and things in the database tend to be one of them. Especially when the ORM is not a part of the project. Making migration tools, and the ability to deploy direct SQL with applications become exceptionally brittle. 

I'm a fan of making most things driven by configuration. Aside from connection settings, the database has to be one of the things you can count on.

**Comment by letsjustfixit** [comment]
I'm sorry I havent been clear enough: I tought talbe name **prefix** *should* be configurable.
Thus avoiding collisions of multiple ghost blogs in the same db etc.

**Comment by jaswilli** [comment]
Hi @esatterwhite,

Third party development shouldn't really be taking place inside the Ghost database.  If someone really decides to throw caution to the wind and hijack it for their own development the burden should be on them to prevent collisions.
