### ISSUE TITLE
[Question] What is the recommended way to get Syntax Highlighting?

### ISSUE THREAD

**Issue by carlosbaraza** [TryGhost/Ghost#5038]
First of all, congratulations for this amazing blogging platform that I am glad and proud to use for my blog.

I saw multiple ways to get Syntax Highlighting with Prism.js and Highlight.js (what I am currently using). However, I would like to know if there is some plugin/recommended way to integrate the embedded GitHub markdown using ````<language>` to highlight the code.

Regarding this markdown syntax highlight, I found the plugin [ghost-prism-plugin](https://github.com/francescolaffi/ghost-prism-plugin/) and two closed issues: #1091 and #1431. However, everything seems to be really old, leaving me with the only option of using some custom JS library instead of something integrated with the markdown.

Thank you,
Carlos.

**Comment by carlosbaraza** [comment]
By the way, I open a new issue on purpose and aware of the recommendation of using IRC/Forum to ask questions. I open it to request the integration of the syntax highlighter in Ghost itself. I could participate on such integration submitting a pull request if accepted such idea.

**Comment by ErisDS** [comment]
Hi @carlosbaraza :)

As you mentioned, Ghost already supports the markdown for getting syntax highlighting as you can use ````language` to trigger highlighting.

Including a library to do the highlighting itself is a job for your theme. Many themes come with something like prism built in, and some don't. The default theme [Casper](https://github.com/TryGhost/Casper) does not include it. 

However, if the theme you're using doesn't support it, and you want to add highlighting without editing the theme you can use the [code injection](http://support.ghost.org/use-code-injection/) feature to add it by linking to [prism via a cdn](http://cdnjs.com/libraries/prism).

There are also some people voting for this feature on the [wishlist](http://ideas.ghost.org/forums/285309-wishlist/suggestions/7193111-markdown-syntax-highlighting) but I'm really not sure what we'd do if it gets a lot of votes - maybe add it to Casper, but it seems unnecessary seeing as it's already so easy to do and effectively supported by Ghost itself.

I'm going to close this issue because there's nothing to do here - the only place we could add support would be Casper, which is in a different repo.

**Comment by carlosbaraza** [comment]
Hi @ErisDS ,

Thank you for the quick answer and my apologies for opening a non-sense issue.

**Comment by andy1247008998** [comment]
@ErisDS Sorry for replying such an old issue.

Is **```language`** still available in the latest version?
I googled a lot, but a built-in highlight feature is what I want. I would like to avoid any injected css or js if possible.

Thank you!

**Comment by kevinansfield** [comment]
@andy1247008998 ```language is supported markdown but you will need to add a client-side syntax highlighting library to your theme or through the Code Injection screen to get syntax highlighting, there's no built-in support for that as it's very much a theme-level concern.
