### ISSUE TITLE
Github flavoured Markdown can't handle Github flavoured Markdown

### ISSUE THREAD

**Issue by JohnONolan** [TryGhost/Ghost#5039]
Whenever you place certain markdown inside triple back-tick fences, GFM (both in editor and on front-end) still tries, and fails, to render it.

So far for me it breaks spectacularly when placing the following inside code-fences:
- Images
- Code fences
- Strikethrough text (doesn't work with 4 spaces, either)

---

![image](https://cloud.githubusercontent.com/assets/120485/6663301/ff90b094-cbcd-11e4-9b77-37c607e9cc57.png)

Works fine when 4 spaces used

![image](https://cloud.githubusercontent.com/assets/120485/6663483/b9e2431c-cbcf-11e4-909b-76355568e925.png)

**Comment by ErisDS** [comment]
This is an issue that we keep running into time and time again - where fenced codeblocks are not correctly removed before running certain parts of the markdown conversion.

We also often run into similar issues with `<pre>`, `<code>` and inline code snippets across various features. 

I'm in the process of moving our custom extensions out of Ghost core and into our showdown fork, and once that is done I intend to resolve this issue once-and-for-all - therefore self-assigning.

**Comment by unwitting** [comment]
God speed, @ErisDS - this is becoming more of an issue now that ES6 has brought in template strings :) Backtick death

**Comment by ErisDS** [comment]
@unwitting can you clarify what you mean with regard to ES6 and how this affects our markdown handling please?

**Comment by unwitting** [comment]
Yep - I'm trying to put together a reproducible failure, but I encountered this when trying to share code blocks involving ES6's template strings - they use the backtick instead of either single or double quotes, and don't seem to play nicely at all with ```- or <code>-blocks.

**Comment by unwitting** [comment]
Aha, so here we go (in all the following, where you see: \\\`, replace with just a \` - this is by definition hard to paste into a markdown-d comment). The following displays as intended:

```
Blah

\`\`\`javascript
var myString = \`Hello World!\`;
\`\`\`

Blah 2 \`with inline\`

\`\`\`javascript
var myString2 = \`Hello World 2!\`;
\`\`\`
```

However, add a single backtick after the first Blah:

```
Blah \`

\`\`\`javascript
var myString = \`Hello World!\`;
\`\`\`

Blah 2 \`with inline\`

\`\`\`javascript
var myString2 = \`Hello World 2!\`;
\`\`\`
```

And the bottom of the two code blocks duplicates itself to the output of the first as well. Try it in the Ghost editor to see for yourself, remember to remove slashes.

**Comment by unwitting** [comment]
My initial reaction to the above was to escape the stray backticks (the ones I didn't want to influence creation or termination of code blocks / inline blocks) with backslashes, but they don't seem to honour that - you can escape the new backtick in the second example and nothing different happens.

**Comment by ErisDS** [comment]
@unwitting excellent, thanks for all the details. Unfortunately the issue with backticks is deep in showdown, but I'm working on a fix and hopefully it will be able to encompass this. 

The poor handling of escape characters is a secondary issue which just compounds things - I'm looking into this as well, although not sure where the root of the problem here is yet.

**Comment by unwitting** [comment]
@ErisDS awesome - let me know if I can help out more, sounds like you're on the case :)

**Comment by ErisDS** [comment]
@unwitting our fork of showdown lives over at https://github.com/erisds/showdown and PRs are more than welcome :)

**Comment by unwitting** [comment]
:) Might take a look if I get some time!

**Comment by unwitting** [comment]
I raised https://github.com/ErisDS/showdown/issues/2 since I think it's a better place for it?

**Comment by tivie** [comment]
This issue doesn't seem to affect showdown (tested with Showdown v1.0.0 and onward).

[You can test in our live preview](http://showdownjs.github.io/demo/)

![ss1](https://cloud.githubusercontent.com/assets/1608730/8825288/e6cdc30a-3075-11e5-94ab-444c28b923b5.JPG)

**Comment by zjjott** [comment]
Ghost have no handle `diff` gfm like this:
```diff
3,4c3,4
<     String, ForeignKey
< from sqlalchemy.orm import Session, relationship, backref
---
>     String, ForeignKey, and_
> from sqlalchemy.orm import Session, foreign, relationship, backref
```
