### ISSUE TITLE
[Feature Request] Improving Accessibility With Notification Sounds

### ISSUE THREAD

**Issue by LTheobald** [TryGhost/Ghost#5041]
I was wondering what people thought about adding some sound to the notifications in Ghost to improve their accessibility a little.

I'm visually impaired & amongst other things, have a low field of vision.  The way the notifications in Ghost are displayed often causes me to miss them.  Let me give you an example using the login screen.  When I look at that login screen, I tend to only be able to see clearly the thing I am looking at. So for example, when looking at the password input field, I can only really see that password input clearly. If I enter an incorrect password, a notification pops up but it's in the bottom left, out of my field of vision. As nothing I am looking at (the controls themselves) update, I have no idea something has gone wrong.  Most system tend to put the alerts above the inputs, causing the page to shift down a bit. That would give me feedback that something has changed because things have moved. Ghost doesn't do that.

One simple solution to this without moving the notifications, could be to add a simple sound when the notification pops up.

What do people think? I've created a pull request to illustrate what I'm getting at (run it & raise a notification by entering rubbish into the login fields). But that code would need some tiding before it's accepted. There's also the question of what sounds to use if it is accepted.

Lee,

**Comment by jaswilli** [comment]
I'm going to close this but if anyone has anything further to add we can re-open.
