### ISSUE TITLE
Navigation does not support partial syntax

### ISSUE THREAD

**Issue by writeline** [TryGhost/Ghost#5043]
Not sure if this is a bug. `Navigation.hbs` is working fine with Casper. Casper uses 
```
{{navigation}}
```
in `default.hbs`. My theme was using
```
{{>navigation}}
```
partial handlebars syntax in `default.hbs` which is not working.

**Comment by dbalders** [comment]
@writeline if you change your theme to use `{{navigation}}` does it work? `{{navigation}}` is the correct syntax, `{{>navigation}}` is not.

**Comment by dbalders** [comment]
Closing for now, but let me know what happens

**Comment by writeline** [comment]
Yes my theme is working with `{{navigation}}`. So, `{{> xyz }}` is not valid partial syntax in handlebars?

**Comment by dbalders** [comment]
Cool, glad you got it working! I think you need to remove the space after 'xyz'. So, it should look like this: `{{> xyz}}`. But, for the navigation, you should use `{{navigation}}` because it is its own handlebars helper if that makes sense.

**Comment by ErisDS** [comment]
Just wanted to quickly follow this one up quickly, @writeline it's not 100% clear what you mean by 'not working' in your original issue, so there is a lot of assumptions that have to made about what you're talking about.

If you reference a partial in your theme using partial syntax `{{> partial-name}}`, handlebars will load in a file from the `/partials` folder with the same name. So if you have a partial called `navigation.hbs` and call it with `{{> navigation}}` your partial will be rendered.

The navigation helper, which looks like `{{navigation}}` does a tonne of stuff to fetch & process the data from the navigation UI, and then hands that data to a partial called `navigation` to be displayed. If there isn't a `navigation.hbs` partial in the theme, then it will fall back to the default one in Ghost core.

Casper makes use of this functionality, using the `{{navigation}}` helper to tie the navigation data and navigation partial together. You can completely override the special navigation behaviour by using `{{>navigation}}` and specifying a partial that does something else, but you should not expect to get the special behaviour of the `{{navigation}}` helper if you don't use the helper. 

Hope this makes sense of what's going on?

**Comment by writeline** [comment]
Yes, thanks for the explanation.
