### ISSUE TITLE
Issues setting up ghost in DigitalOcean

### ISSUE THREAD

**Issue by seekshiva** [TryGhost/Ghost#5045]
I was trying to set up ghost by following [these instructions](https://www.digitalocean.com/community/tutorials/how-to-use-the-digitalocean-ghost-application). But I'm facing the following issues:

I had updated config.js and sites-available/ghost with my host name. I set up a Mailgun account, and updated those details to config.js as well.

But I get this following message after finishing set up:
![screen shot 2015-03-17 at 9 25 25 am](https://cloud.githubusercontent.com/assets/484349/6681181/32e6e250-cc88-11e4-94dd-c023cfecc0af.png)

It didn't recognise the domain name or the Mailgun configuration.

Now, when I configured CloudFlare to enforce https to that subdomain, the home page keeps going on in an infinite loop and the page never loads (but the admin pages at `/ghost/1` load fine with https).

**Comment by shakna-israel** [comment]
* Did you restart nginx after modifying it's config?
* Did you set the name and email under development or production? (Posting the config, or parts of, it might help.)

**Comment by seekshiva** [comment]
Even though I am accessing the site using https, CloudFlare would be contacting my server via http to fetch the data. So when CloudFlare accessed the http version of the site, ghost replied with a 302 to the https uri which caused the infinite loop.

Now I set the production url in config.js to use http and not https. After a `service ghost restart`, it is working fine now. I'm able to access the site via https.
