### ISSUE TITLE
Images are not deleted after deleting

### ISSUE THREAD

**Issue by online** [TryGhost/Ghost#5052]
Hi!

If you attach a picture to post, after removing it remains on FTP folder.

Sorry if the problem described not clear.

**Comment by javorszky** [comment]
Hi @online, and welcome to Ghost's github!

This question has been answered by this thread: https://github.com/TryGhost/Ghost/issues/4311 :)

**Comment by online** [comment]
Hi @javorszky, thank you for prompt reply. In that case I close this issue, because it duplicates a previously created — #4311.
