### ISSUE TITLE
Settings UI looks broken and with strange icons

### ISSUE THREAD

**Issue by Chris2Brooks** [TryGhost/Ghost#5057]
I tried searching for open/ closed issue regarding this but couldn't find any, if duplicate I apologise.

Since upgrading to Ghost v0.5.10 the Ghost backend has strange icons or "whitespace" where I think there should be icons. See screenshot:

![screenshot - 20032015 - 17 45 52](https://cloud.githubusercontent.com/assets/2293301/6755205/1a1a6bc6-cf2a-11e4-8466-ba4114deb370.png)

The navigation settings screen also cuts of the button next to navigation items:

![screenshot - 20032015 - 17 56 19](https://cloud.githubusercontent.com/assets/2293301/6755298/b5f7fdf6-cf2a-11e4-97c4-f64ff10217dd.png)

Running on Digital Ocean and upgraded using https://allaboutghost.com/updateghost-digitalocean

**Comment by novaugust** [comment]
Hey @Chris2Brooks, we use github to track bugs with Ghost; the [forums](http://forum.ghost.org) are a more appropriate place for troubleshooting. No worries though :) This looks like a caching issue like #5034 . I'm going to close against that - if you think this is a bug, let me know and I'll reopen

**Comment by aruizca** [comment]
I have the same problem and I don't think it is caching issue
