### ISSUE TITLE
Tag for rendering meta description content in post list / individual post

### ISSUE THREAD

**Issue by georgerichmond** [TryGhost/Ghost#5067]
I want to be able to use the meta description field in the context of a post on the index page, so that there can be a little strapline under each headline. Excerpt doesn't really work for this, as I don't want the content to be at the start of the post content and it needs to be a standout sentence, not just the first few words of the article.

**Comment by novaugust** [comment]
Hi @georgerichmond, we have a fix for that in the works (someone already reported this issue at #4850), it'll hopefully be out in the next release =)

**Comment by ErisDS** [comment]
Just FYI, there is a workaround for this issue, as although `{{meta_description}}` is getting incorrectly overridden, you can reference the property directly stil with `{{this.meta_description}}` and the value will be output as expected.
