### ISSUE TITLE
Roles and drafts not showing on production

### ISSUE THREAD

**Issue by bretthayes** [TryGhost/Ghost#5072]
### Issue
We currently have a node js production environment set up with AWS OpsWorks. For some reason when you save a draft on local or production in the Ghost Admin, it doesn't show up at all on production. However it shows up on local as a draft. I've confirmed that the drafts save to our RDS MySQL instance/database just fine.

Role types/permissions also don't show beside a user account in the ghost admin under the users tab on production. On local they show just fine.

### Setup
- Our node version is: `v0.10.33`
- We are running on: `Ubuntu 14.04 LTS`
- We have the production env variable set: `NODE_ENV=production` in OpsWorks
- We are running Ghost version: `v0.5.9`
- Currently using Chrome version: `41.0.2272.104`

### Our Config

Our `dbconfig` comes from a required file that has set database connection values based on our node environments. Both local and prod load the same database.

We have our production environment behind an nginx proxy and debug is set to true for testing purposes to see detailed logs.

```javascript
config = {
  production: {
    url: 'https://ourdomain.com/blog/',
    forceAdminSSL: false,
    database: {
      client: 'mysql',
      connection: {
        host     : dbconfig.db.host,
        user     : dbconfig.db.username,
        password : dbconfig.db.password,
        database : dbconfig.db.database,
        charset  : 'utf8'
      },
      debug: true
    },
    server: {
      // Ubuntu needs host to be zero's
      host: '0.0.0.0',
      port: '80'
    }
  },
  development: {
    url: 'http://localhost:2368',
    forceAdminSSL: false,
    database: {
      client: 'mysql',
      connection: {
        host     : dbconfig.db.host,
        user     : dbconfig.db.username,
        password : dbconfig.db.password,
        database : dbconfig.db.database,
        charset  : 'utf8'
      },
      debug: true
    },
    server: {
      host: '127.0.0.1',
      port: '2368'
    },
    paths: {
      contentPath: path.join(__dirname, '/content/')
    }
  }
};

module.exports = config;
```

### Screenshots of Draft Issues

This is a screenshot of the draft shown on local.
![This is a screenshot of the draft showing on local](https://cloud.githubusercontent.com/assets/1733936/6837643/259618e8-d325-11e4-8e5a-7bfbbf6269ce.png)

This is a screenshot of the draft not shown on production.
![This is a screenshot of the draft not shown on production](https://cloud.githubusercontent.com/assets/1733936/6837647/33f517ea-d325-11e4-9470-62f4995d7ed0.png)

### Screenshots of User Role Issues

This is a screenshot of the user roles shown on local.
![This is a screenshot of the user roles shown on local](https://cloud.githubusercontent.com/assets/1733936/6837751/aac0e1d2-d326-11e4-8f5c-2cd35299122d.png)

This is a screenshot of the user roles not shown on production.
![This is a screenshot of the user roles not shown on production](https://cloud.githubusercontent.com/assets/1733936/6837755/b5e7ab5e-d326-11e4-89c6-213a345b676b.png)

This is a screenshot of the gear icon/actions button under a specific user profile only shown on local. This does not show on production.
![user role actions](https://cloud.githubusercontent.com/assets/1733936/6837773/ed182608-d326-11e4-8b46-fa155e5ea876.png)

Any help would be greatly appreciated. Hopefully these details help solve the issue.

**Comment by ErisDS** [comment]
Hi @bretthayes, I'm sorry to hear you're having problems with Ghost. Your setup sounds pretty unique! 

This GitHub repo is used as an issue tracker - it hosts our developer community, who are focused on building Ghost rather than providing support. For that reason we ask that support issues like this be raised on the [forum](https://ghost.org/forum). If you hit [post a new topic](https://ghost.org/forum/installation/new/) in the installation forum, you'll see a list of things that are useful to include so that people can help you debug your issue.

In the majority of cases, these sorts of things are tracked down to nginx configuration issues, or other details of your setup. If a bug in Ghost is identified, please provide the reproduction case and we'll reopen the issue and get it fixed.
