### ISSUE TITLE
[Zelda] Private blogs login form & settings design

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#5073]
Main issue: https://github.com/TryGhost/Ghost/issues/4993

---

The password protected blogs feature has two pieces of design work needed to complete it: 

1) The design for the login page, which is going to live at `/private/`
2) The spec/design for the location of the password and message inputs somewhere in the settings panel.

**Comment by JohnONolan** [comment]
## 1.

Centered horizontally and vertically. Should be able to re-use some styles from new install screen. 36px heading. Wrapper max-width 400px.

![image](https://cloud.githubusercontent.com/assets/120485/7003712/cd3c0012-dc67-11e4-810b-3f8a59d8d050.png)

## 2.

![image](https://cloud.githubusercontent.com/assets/120485/7003903/d8392ece-dc6a-11e4-91c1-55e059268dac.png)

![image](https://cloud.githubusercontent.com/assets/120485/7003904/e2e892e2-dc6a-11e4-997f-198d2f4f7fc7.png)

^ Generate simple random password each time this feature is switched on/off

**Comment by acburdine** [comment]
@ErisDS @JohnONolan Do you want me to take care of this in #4993?

**Comment by JohnONolan** [comment]
Styles up in #5255 - couple of other small changes:

- [ ] This can go straight into the bottom of settings/general and out of labs
- [ ] Currently it breaks if you press "enter" instead of save (it should just work)
- [ ] It would be cool to generate a random, pronounceable password by default (it should change each time the feature is turned on/off)

**Comment by acburdine** [comment]
I'll get right on that @johnonolan

**Comment by acburdine** [comment]
@ErisDS @JohnONolan I just realized something. There needs to be some documentation on how to customize the password.hbs file in themes, given that it needs a form that sends info back to the server in specific format.

**Comment by ErisDS** [comment]
@acburdine with regards to documentation, I opened #5265 which makes some small changes to how the `password.hbs` template works, including renaming it to `private.hbs` to match the route. I'll update the theme docs for 0.6.3 to cover how all this works :)

**Comment by ErisDS** [comment]
Reopening this as it needs the design fixed up for Zelda.
