### ISSUE TITLE
Markdown improvement: A blank line doesn't separate block quotes

### ISSUE THREAD

**Issue by diihunts** [TryGhost/Ghost#5077]
In the Ghost editor,

    > foo
    
    > bar

and

    > foo
    >
    > bar

both result in something like:

    <blockquote>
    <p>foo</p>
    <p>bar</p>
    </blockquote>

But according to the CommonMark specification, which makes a lot of sense, it should produce something like:

    <blockquote>
    <p>foo</p>
    </blockquote>
    <blockquote>
    <p>bar</p>
    </blockquote>

I'm not saying you guys should make a blank line in between to indicate separation of two consecutive block quotes, since there's no definite Markdown standard yet. But there should be a way to separate consecutive block quotes right?

**Comment by javorszky** [comment]
Hi @diihunts,

Ghost's built in editor does not conform to CommonMark, nor it is expected to, so the behaviour you're experiencing is correct. There's a discussion on whether the editor should adhere to CM spec here: https://github.com/TryGhost/Ghost/issues/3959, started by me, but that's fairly stale. At the moment the decision is that it does not.

Hope this helps.

**Comment by ErisDS** [comment]
For reference, Babelmark: http://johnmacfarlane.net/babelmark2/?normalize=1&text=%3E+foo%0A%0A%3E+bar

This is how showdown and many other markdown libraries interpret the markdown for blockquotes. We depend on showdown, so if you wanted to start a discussion around changing to use the commonmark version, it would be better to start it on the showdown repo :)

**Comment by diihunts** [comment]
Thanks @javorszky @ErisDS for the replies. You're right, I shouldn't bring it up here.

I'm still not sure. Do I have to switch back to HTML to write consecutive block quotes?

By the way, great job with Ghost, really appreciate it :)

**Comment by ErisDS** [comment]
@diihunts you can use an invisible character between block quotes:

```
> foo
  
&nbsp;

> bar
```

**Comment by diihunts** [comment]
@ErisDS thanks, that kind of does the job, but it also results in an extra empty paragraph right? I guess I'll just use html in those circumstances.
