### ISSUE TITLE
Navigation not working inside a conditional tag

### ISSUE THREAD

**Issue by matohawk** [TryGhost/Ghost#5088]
### Issue Summary

When I use a conditional tag `#if @blog.navigation` with global variable and `#foreach navigation`, the navigation it's not render. 

### Steps to Reproduce

1. Write a navigation.hbs with this code : 
```
    {{#foreach navigation}}
    <li class="nav-{{slug}}{{#if current}} nav-current{{/if}}" role="presentation"><a href="{{url absolute="true"}}">{{label}}</a></li>
    {{/foreach}}
```
2. Inside your Index.hbs call the navigation partial and wrap the call with this conditional code :
```
{{#if @blog.navigation}}
    {{navigation}}
{{/if}}
```
3. Go to your ghost dashboard and add some navigations : `/ghost/settings/navigation/`
4. Go to your blog home page and see if your navigation it's outputted

If I remove the `if @blog.navigation` it's working.
Do I need to use this conditional `if navigation` instead of the global variable?
I think this is a bug because we need to be able to use if statement to remove some unnecessary html tags around the navigation output if the navigation is not there.

### Technical details:

* Ghost Version: 0.5.10
* Client OS: Ubuntu 14.10
* Server OS: Ubuntu 14.10
* Node Version: 0.12.1
* Browser: Chrome  42.0.2311.60
* Database: SQLite

I also try in the hosting ghost version in [www.powmas.com](www.powmas.com) ,  I have same behaviour. Now on my blog I remove the if to output correctly the navigation.
Maybe it's related to this bug fix #5080

**Comment by ErisDS** [comment]
Hi @matohawk, thanks for taking the time to report this issue, unfortunately I'm not able to reproduce it from the information provided. Can you please update us with a little more information? There is a handy bug template in our [contributing guidelines](https://github.com/TryGhost/Ghost/blob/master/CONTRIBUTING.md#bug-reports) that shows the kind of information it's useful to include and in your case what I'm most interested in is what version number of Ghost you are using, as well as more details around what context you're seeing the issue in. Your top screenshot looks like default.hbs - so does the navigation disappear on all pages of the blog or just some?

If we're able to figure out the reproduction case then this will need to be fixed, however it is also worth noting that you're using an unexpected pattern here. You can move the wrapping elements into the `navigation.hbs` template, which is only rendered in the case that navigation exists, and remove the if statement entirely.

**Comment by matohawk** [comment]
Hi Eris,
I updated my first post with your guidelines I hope it will be useful.

**Comment by ErisDS** [comment]
Ok great thanks! So you are using Ghost 0.5.10, rather than master - and that means that #5080 has fixed the issue already :)

Just for clarity though, this is an anti-pattern, and not recommended use of the helper:

```
{{#if @blog.navigation}}
    {{navigation}}
{{/if}}
```
This is because the `{{navigation}}` helper already does this conditional for you before rendering the template, and renders nothing if there is no navigation.

**Comment by matohawk** [comment]
Thanks for the anti pattern explanation I will refactor my code
