### ISSUE TITLE
URL markdown bug

### ISSUE THREAD

**Issue by yxshawn** [TryGhost/Ghost#5090]
When the link contains double equal symbols, it will be incorrectly replaced with "<mark>" or "</mark>" For example:

```
[My Error Link](http://myweb.com/s?__biz=MzA3Nzg3NDcyNg==&mid=204174320)
```

**Comment by ErisDS** [comment]
Hi @yxshawn, this issue is already raised here: https://github.com/TryGhost/Ghost/issues/4627

Closing this one as a duplicate

**Comment by yxshawn** [comment]
@ErisDS Thanks!
