### ISSUE TITLE
Cannot send invitation

### ISSUE THREAD

**Issue by lexpierce** [TryGhost/Ghost#5095]
Cannot send mail from `http://blog.mydomain.com:2368/ghost/settings/users/` to user with newer TLD. (in this case, .rocks)

```
/home/ghost/ghost/core/server/mail.js:95
                if (data.error.errno === 'ENOTFOUND') {
                              ^
TypeError: Cannot read property 'errno' of null
    at EventEmitter.<anonymous> (/home/ghost/ghost/core/server/mail.js:95:31)
    at EventEmitter.g (events.js:180:16)
    at EventEmitter.emit (events.js:95:17)
    at DirectMailer.<anonymous> (/home/ghost/ghost/node_modules/nodemailer/node_modules/directmail/lib/mailer.js:138:30)
    at asyncCallback (dns.js:68:16)
    at Object.onanswer [as oncomplete] (dns.js:147:9)
```

**Comment by novaugust** [comment]
cc @javorszky

**Comment by javorszky** [comment]
Ohkay... right, sooo... that's the validator plugin throwing errors. I'll have a 4 day weekend, and will update the email module from 0.7.2 to whatever the latest version it is currently. Thanks for the bug report @lexpierce, and @novaugust for the cc. :)

**Comment by javorszky** [comment]
Just a heads up, Mandrill is being difficult: https://github.com/andris9/Nodemailer/issues/412 and https://twitter.com/javorszky/status/584738416564244480

If anyone can tell me what I'm doing wrong, and point me in the right direction, it'd be appreciated. :)

**Comment by javorszky** [comment]
Hey all,

So I've done a bit of research involving buying http://javorszky.rocks, setting that up as a domain alias in google apps, and configuring the email on that domain.

After that I invited myself on my new email address, and this is the result:

![invitation in Ghost](https://cldup.com/1Xi9D-XAxZ.png)

![invitation email](https://cldup.com/a72rTI_N3w.png)

This is on latest `master` of Ghost, with zero modifications to anything. Latest commit at the moment is https://github.com/TryGhost/Ghost/commit/5525d0ea3420dd2b3b4f343ffad16913e8a0a566.

@lexpierce, I think it has more to do with DNS setup / propagation time than the email modules.

**Comment by jaswilli** [comment]
I'm going to close this, as if there's a mail sending problem it's not clear what it is at this point.  If anyone has anything else to add we can re-open.
