### ISSUE TITLE
Swipe left and right through posts.

### ISSUE THREAD

**Issue by digitalextremist** [TryGhost/Ghost#5100]
It would be very nice to swipe left and right to go forward and backward in the available posts, when reading an individual post on touch screen.

**Comment by dbalders** [comment]
Hey @digitalextremist. Thanks for taking the time to open the issue and having a suggestion for Ghost! This could be a pretty awesome feature. If you wouldn't mind, could you put your suggestion over on http://ideas.ghost.org/? We like to keep GitHub for current bugs or issues being worked on. Thanks!

**Comment by digitalextremist** [comment]
Will do! Sorry about that, I'm new to Ghost. Won't happen again.
