### ISSUE TITLE
Urdu font in ghost ? 

### ISSUE THREAD

**Issue by waqaskhan137** [TryGhost/Ghost#5110]
I have been trying to write blog in my own language( http://rmwaqas.com/lkhh-skht-hwn-blog-khy-myn-rdw-kh/ ) and I cant seem to get it working on ghost blogger even I have installed the fonts on my system still I see the Arabic font(While urdu font looks like 
![sample-nastaleeq](https://cloud.githubusercontent.com/assets/4752256/7002383/28c23fe6-dc63-11e4-94ce-ef38c8910cbe.gif)
). Is there anyway ghost can support [Jameel Noori Nastaleeq Urdu Fonts](http://www.urdujahan.com/urdu-fonts/Jameel%20Noori%20Nastaleeq.zip) ?

**Comment by ErisDS** [comment]
Hi @waqaskhan137, at this point in time, Ghost only really supports latin-extended fonts in the editor. In future we plan to make it possible to install a language pack that would both add the necessary fonts and translate Ghost into your language. 

In the meantime, to add support for your language to Ghost you could try using the privacy setting to disable Google fonts, [documented here](http://support.ghost.org/config/#privacy) - this may cause the editor to default back to a native font which has support for your language. Alternatively, you'd need to maintain your own fork of Ghost which changes the font used in the admin [here](https://github.com/TryGhost/Ghost/blob/master/core/client/app/index.html#L39).
