### ISSUE TITLE
Display current static page

### ISSUE THREAD

**Issue by suenot** [TryGhost/Ghost#5113]
How to modify template to display in index.hbs some specific (or all) static pages?
I want create landing page with:
- content from static page: 'about',
- list of news (in slider),
- content from static page: 'team',
- content from static page: 'contacts'.
I found landing template in store: http://themeforest.net/item/the-great-adventure-full-screen-responsive-theme/full_screen_preview/6768611

**Comment by ErisDS** [comment]
Hi @suenot please could you ask questions like this over on our [forum](https://ghost.org/forum)? Thanks!

**Comment by suenot** [comment]
Nobody reply at this question on forum.
https://ghost.org/forum/themes/18105-list-all-pages-without-posts/
https://ghost.org/forum/themes/15615-access-a-static-page-directly/
