### ISSUE TITLE
[npm version] Won't Install on io.js

### ISSUE THREAD

**Issue by CWSpear** [TryGhost/Ghost#5126]
I see in #4811 that you added support for io.js, and I see that it's added to the `package.json`, but if I try and install `ghost@~0.5.10`, I get an error:

```
☃ [ghost@cameronspear] ~/blog/ [master] node -v
v1.6.4
☃ [ghost@cameronspear] ~/blog/ [master] rm -Rf node_modules 
☃ [ghost@cameronspear] ~/blog/ [master] npm install
npm ERR! Linux 3.2.0-24-virtual
npm ERR! argv "/usr/local/bin/iojs" "/usr/local/bin/npm" "install"
npm ERR! node v1.6.4
npm ERR! npm  v2.7.5
npm ERR! code ETARGET

npm ERR! notarget No compatible version found: ghost@'>=0.5.10 <0.6.0'
npm ERR! notarget No valid targets found.
npm ERR! notarget Perhaps not compatible with your version of node?
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of 'cameronspear.com'
npm ERR! notarget 

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ghost/blog/npm-debug.log
```

[Full `npm-debug.log` contents](https://gist.github.com/CWSpear/b720542b5fde5496eee6)

I tried `npm install -g npm` as per npm/npm#4984, but it didn't make a different.

I should note that if I use Node `0.10.x` or `0.12.x`, it works.

**Comment by CWSpear** [comment]
I should note that if I use Node `0.10.x` or `0.12.x`, it works.

**Comment by ErisDS** [comment]
Hi @CWSpear, our support for io.js extends to v1.2.0 only (this is mentioned in the README and package.json). 

Unfortunately, io.js moves too quickly for most of our dependencies to keep up, and the amount of testing and fiddling around with our build that is needed for each release is not something the core team can commit to doing.

If you want to do the testing work to figure out if we can now support more versions of io.js, that would be welcomed, but this needs to be community driven.

**Comment by CWSpear** [comment]
Ah yes, I got `~` and `^` confused again.

That does seem to be a common issue for `io.js` at this time, and there doesn't seem to be any really great solutions other than just adding it and letting people go wild (i.e., I thought had misinterpreted the `package.json` as `"iojs": "^1.2.0"`). So I was just gonna try and install and see what happens.

I think ultimately, `io.js` will hopefully plateau and minor patches will be a lot farther and few in between.
