### ISSUE TITLE
Secondary autosave wired to never fire?

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#5132]
The original spec for autosave was to have two triggers:
- one would fire after 3 seconds if the user stops typing in the editor
- one would fire every 60 seconds if there was something to save

It seems from reading the code & testing, that the two have been conflated together such that they both only fire in the case that the user stops typing in the editor, and given that whenever a save happens, both autosave timers are cleared, it seems that the secondary autosave can and will never fire.

The difference between the two is that the first should be saving incremental updates to the post, and the second is there as a background save, and would also fire if any of the meta information for the post had changed (i.e if I had edited a tag or uploaded an image).

Autosaving meta data is less important than ensuring we keep the changes to the post, so this isn't critical, however it seems the current setup needs a little work for it to work as intended.

**Comment by jaswilli** [comment]
I tested the "secondary" auto-save and if you're in the editor typing frequently enough where the "no typing for 3 seconds" auto-save doesn't kick in, it will save no matter what after 60 seconds.

However, the auto-save is entirely driven off changes to the post's content (i.e. things that happen in the editor itself), so manipulating tags in the tag input will not queue an auto-save event... In order to do that we'd have to set up something so that the editor gets notified by the tag input that a change has occurred.

**Comment by ErisDS** [comment]
> I tested the "secondary" auto-save and if you're in the editor typing frequently enough where the "no typing for 3 seconds" auto-save doesn't kick in, it will save no matter what after 60 seconds.

Perfect :+1: 

> In order to do that we'd have to set up something so that the editor gets notified by the tag input that a change has occurred.

Do the other changes not mark the model as isDirty, such that it would fire after 60 seconds and get saved?

**Comment by jaswilli** [comment]
> Do the other changes not mark the model as isDirty, such that it would fire after 60 seconds and get saved?

The auto-saves are triggered by changes to the `scratch` property on the Post model, so only when the content of the post is changed.  The PSM handles saving when metadata changes, so it's really just tags I think that don't trigger any sort of auto-save behavior.

**Comment by ErisDS** [comment]
> so it's really just tags I think that don't trigger any sort of auto-save behavior.

Given that component will be moved into the PSM shortly, I think we can close this. 

Thanks @jaswilli  :+1:
