### ISSUE TITLE
Base-level rules cannot contain the parent-selector-referencing character '&'.

### ISSUE THREAD

**Issue by noamcore** [TryGhost/Ghost#5133]
I just get this issue when trying to compile with ruby scss 3.4.13.

I've got this:
```
error components/navigation.scss (Line 383: Base-level rules cannot contain the parent-selector-referencing character '&'.)
```

Ghost uses some custom configuration to compile the sass on `core/client`?

**Comment by ErisDS** [comment]
Hi @noamcore, what exactly are you trying to do here?

Ghost doesn't use Ruby scss, we are 100% javascript :wink: so we use node-sass. To build Ghost, use grunt, as explained in the [readme](https://github.com/TryGhost/Ghost#developer-install-from-git).
