### ISSUE TITLE
Safari try's to load ghost.min.css.map that doesn't exist

### ISSUE THREAD

**Issue by arianf** [TryGhost/Ghost#5135]
In ghost [0.5.9](http://ghost.org/zip/ghost-0.5.9.zip) and ghost [0.5.10](http://ghost.org/zip/ghost-0.5.9.zip), inside of the css file `/core/client/assets/css/ghost.min.css` there contains a line at the end of the file:

```css
/*# sourceMappingURL=ghost.min.css.map */
```

Safari will try to load this source mapping resource:
```
http://blog.example.com/ghost/css/ghost.min.css.map
```
But inside of the `/core/client/assets/css/` folder, there is no `ghost.min.css.map`!!

Removing the hashtag `#` will tell safari that this is an actual comment, for a temporary fix (until you guys updated the zip to include the `ghost.min.css.map`).
```css
/*# sourceMappingURL=ghost.min.css.map */
  ^--- here
```

### Screen shots
![screen shot 2015-04-12 at 1 05 55 pm](https://cloud.githubusercontent.com/assets/7397857/7107428/f84533e4-e119-11e4-87c5-579253357b9f.png)

![screen shot 2015-04-12 at 1 05 31 pm](https://cloud.githubusercontent.com/assets/7397857/7107425/ebeb536c-e119-11e4-8101-6c6acca30533.png)

![screen shot 2015-04-12 at 1 45 59 pm](https://cloud.githubusercontent.com/assets/7397857/7107447/cd10a554-e11a-11e4-9186-93195a1944c9.png)

### Steps to Reproduce

1. Load admin page in Safari

### Technical details:

* Ghost Version: 0.5.9+
* Client OS: Mac OS X 10.10.3 (14D131)
* Server OS: Ubuntu 14.04 LTS
* Node Version: v0.10.38
* Browser: Safari 8.0.5 (10600.5.17)
* Database: SQLite

**Comment by PaulAdamDavis** [comment]
Hi @arianf, thanks for reporting this :) And thanks for the screenshots!

On 0.5.10, I can see that the map file doesn't exist, but for me it doesn't error like yours, which is weird.

I can't see any source maps on the master branch, which now uses a slightly different method of comping Sass (and therefor sourcemaps) via Ember-CLI. So I'm wondering if the next release of Ghost will fix this.

**Comment by novaugust** [comment]
Thanks for the nice writeup @arianf. Sourcemaps aren't included in the release package, and I'm not sure where that line of code is coming from or why safari feels the need to be odd about it ;)
Ultimately, that line of code doesn't exist in master, wherever it came from, so this isn't an issue anymore.

**Comment by arianf** [comment]
@novaugust 
Sorry I must have not made this clear in my original post, but this issue isn't for the master branch... but the actual release zip.

download: 
https://ghost.org/zip/ghost-0.5.10.zip
http://ghost.org/zip/ghost-latest.zip

and look here: `/core/client/assets/css/ghost.min.css` on line 2... that is where the line exists, but no source map files.

**Comment by novaugust** [comment]
No worries, you were clear, and I understood. It's just not an issue anymore, so I closed this :)
