### ISSUE TITLE
Static page functionality is buried

### ISSUE THREAD

**Issue by toastyghost** [TryGhost/Ghost#5141]
It took me forever to find where to do this. Rather than the "All Posts" text under Content, why not have Posts and Pages as sub-navigation, allowing you to manage these content types separately? Screenshot attached to illustrate what I'm envisioning.

![content-types](https://cloud.githubusercontent.com/assets/204219/7138399/2b4b265c-e28e-11e4-8178-e61ee753d18a.png)

**Comment by novaugust** [comment]
Hi @toastyghost, we use github for tracking bugs and implementation details. We've got a lovely wishlist for feature requests [here](http://ideas.ghost.org/forums/285309-wishlist). 
Additionally, what you're requesting already has an issue, #2640 :)

**Comment by toastyghost** [comment]
My search-fu was weak. One thousand apologies. And JohnONolan already pointed me toward the wishlist for a separate ticket. Thank you!
