### ISSUE TITLE
Multilevel navigation menu

### ISSUE THREAD

**Issue by toastyghost** [TryGhost/Ghost#5142]
Would love to be able to drag nav items horizontally to hierarchize them, along with some kind of sensible default styling on the public-facing side.

**Comment by JohnONolan** [comment]
Hey @toastyghost - thanks for stopping by! Please could you check out our [contributing guidelines](https://github.com/TryGhost/Ghost/blob/master/CONTRIBUTING.md) and submit feature requests to the the publish [wishlist](http://ideas.ghost.org). Hierarchical navigation is generally complicated and breaks easily - it also makes theming considerably harder. This is the main reason we haven't looked at it in any serious way yet. That being said, you can still create hierarchical menus right now by simply coding them into your theme rather than using the navigation helper.

**Comment by toastyghost** [comment]
Thanks for pointing me in the right direction, just discovered this today so hadn’t really gotten too deep into supplementary content like those guidelines. Someone already made a wishlist item for hierarchical nav, so I put some votes into that instead of duplicating it.

 

Philosophically, I think this is a no-brainer if your team’s intended direction is toward websites rather than just single-page blogs. (Which it seems to be based on the inclusion of features like static pages and a nav editor, but I may be misreading.) I’d really love to see Ghost as an eventual alternative to WordPress for churning out a quick site for a pet project or a client with a limited budget. Hierarchical nav is a little too ubiquitous to skip if it’s ever going to be viable for such scenarios, and having to hard-code the nav myself in a situation like that would just make me wonder why I was using a site manager to begin with.

 

I’m not an Express guy, so I can’t speak to the server-side implementation, but I really don’t understand why you say it would make theming difficult if you generate standard nested markup. And for base themes, I think it’d be an extremely safe assumption that anyone going deeper than a third level is making a complex enough site that they were probably already planning on a lot of custom CSS.

 

Thanks again for your time and I’m looking forward to seeing the evolution of this project!

**Comment by ErisDS** [comment]
Just wanted to chime in here and clarify that the navigation menu, as well as the static page feature that you mentioned in your other issue are both very deliberately basic. They're only intended to support adding simple pages, like about or privacy to your blog or publication. Ghost isn't intended to be a WP clone, it's just a blogging platform :wink:

**Comment by oscarmorrison** [comment]
@JohnONolan sorry to comment on an old issue, I was hoping you might be able to expand on this a little:
> you can still create hierarchical menus right now by simply coding them into your theme rather than using the navigation helper

I am reasonable fresh to the [theme aspect](https://github.com/oscarmorrison/oscar-ghost) but I can't see how its currently possible https://themes.ghost.org/docs/navigation

Really I just want to have a second menu with tag categories.
e.g have a secondary nav with tags: photos, opinions, tutorials, etc. (4 -8 tags)
but I dont want to display all my tags. (and I dont want to use hidden tags)

**Comment by JohnONolan** [comment]
@oscarmorrison You'd need to code that into the theme statically, eg:

```HTML
<ul class="main-nav">
  <li>thing</li>
  <li>thing</li>
  <li>thing
    <ul>
      <li>subthing</li>
    </ul>
  </li>
  <li>thing</li>
</ul>
```

**Comment by juan-g** [comment]
For multilevel navigation, a related feature is hierarchical tags (which is usually implemented with a "Parent" field for tags):

- [Tags 101: Hierarchy - TryGhost/Ghost Wiki](https://github.com/TryGhost/Ghost/wiki/Tags-101#hierarchy) - In "Advanced features" section: "With basic tag management out in the wild, here are the details of the advanced features we plan to ship."
- [Nested tags – Feedback & Ideas](http://ideas.ghost.org/forums/285309-wishlist/suggestions/13187040-nested-tags) - Status: "Planned".

**Comment by impactcolor** [comment]
Any way to achieve this with the secondary menu option now?
