### ISSUE TITLE
Allow to set Ghost configuration in main script, when using npm module

### ISSUE THREAD

**Issue by pensierinmusica** [TryGhost/Ghost#5145]
Hi,

I'm using Ghost as an npm module to run different blogs on the same server. Each blog has its own script. I think it's unconvenient though to be forced to have the configuration in a separate file.

I would like to be able to have this code:

```javascript
var ghost = require('ghost');
var path = require('path');

// Configuration parameters
var conf = {
  production: {
    url: 'http://myblog.com', // Blog url
    server: {
      host: '127.0.0.1', // Port that the server instance will be listening to
      port: '3000'
    },
    database: {
      client: 'sqlite3',
      connection: {
        filename: path.join(__dirname, '/content/data/ghost.db') // Database storage path
      },
      debug: false
    },
    paths: {
      contentPath: path.join(__dirname, '/content/') // Content storage path
    }
  }
};

// Start Ghost server
ghost({config: conf}).then(function (ghostServer) {
  ghostServer.start();
});
```

If I do it this way though I get this error: `Possibly unhandled TypeError: path must be a string`, which I think originates from the fact that the `config` property of the object passed to `ghost()` needs to be a string representing a path to the config file. Why not allowing though to directly pass the config object itself? Having both options would be the best imho.

Even better I'd like this API:

```javascript
// Start Ghost server
ghost(conf).then(function (ghostServer) {
  ghostServer.start();
});
```

Where `conf` is the object defined in the first example.

Any chance this could be changed to avoid being forced to create multiple files when it's not needed?

If you'd like I can create a pr for this  :)

Thanks for putting together this awesome project!

**Comment by ErisDS** [comment]
Hi there @pensierinmusica, this issue is already raised here: #4731 and has 2 open pull requests: #4732 & #5047. Closing this as a duplicate, but please join the discussion on the other threads :+1:

**Comment by pensierinmusica** [comment]
@ErisDS thanks!
