### ISSUE TITLE
grunt init failed

### ISSUE THREAD

**Issue by Duan112358** [TryGhost/Ghost#5148]
![screen shot 2015-04-16 at 17 05 56](https://cloud.githubusercontent.com/assets/1957818/7177795/2bca78ec-e45c-11e4-8b9c-8cae700564d8.png)

**Comment by ErisDS** [comment]
Hi @Duan112358, it looks like npm install didn't complete properly, but there's not enough info here to see for sure. I recommend using the [forum](https://ghost.org/forum) or popping into the #help channel on [slack](https://ghost.org/slack) for getting help with environment issues like these. 

Closing as it's not an issue with Ghost itself.
