### ISSUE TITLE
API: Add `featured` filter option to posts.browse

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#5152]
Currently the `api.posts.browse` endpoint takes the [following options](https://github.com/TryGhost/Ghost/blob/master/core/server/api/posts.js#L48):

> page, limit, status, staticPages, tag

There is an open issue to swap [`page` for `offset`](https://github.com/TryGhost/Ghost/issues/5093)

And another issue to swap [`staticPages` for `page`](https://github.com/TryGhost/Ghost/issues/5151) as well as add generally better support for querying pages.

It would also be good to be able to filter posts by whether or not they are featured: 

`api.posts.browse({featured: true})` or `api.posts.browse({featured: false})` 

Making this work involves adding this as an allowed option in the model.

**Comment by edsadr** [comment]
Taking care of this one :)

**Comment by ErisDS** [comment]
@edsadr let us know if you need a hand - you know where to find us :)

**Comment by edsadr** [comment]
@ErisDS changes are done but... just one test failing.. I will work on it today to send the PR ...  and we will have to discuss some stuff but lets do it after push the code

**Comment by edsadr** [comment]
@ErisDS here is what I would like to propose with https://github.com/TryGhost/Ghost/issues/5093 you are requesting to stop using page as a parameter, but I implemented to support the current format and also to support the `offset`/`limit` format pager, however if `page` is a boolean then it will get just static pages replacing `staticPages` parameter.

I wanted to do it this way as I think is a way more flexible and will also support the new `offset` `limit` approach ... if you guys don't like this then I will change to any other approach you decide =) 

Let me know
