### ISSUE TITLE
Potential Bug/ talking point: Authors and 'about' page

### ISSUE THREAD

**Issue by cobbspur** [TryGhost/Ghost#5154]
Authors can navigate to settings/about (which seems good) but there is do direct link from what I can see. Could just be me but I would be in favour of all users having access to that page and if not then they shouldn't be able to access it all.

**Comment by acburdine** [comment]
Personally, I would agree with the authors having access to the about page. It would give them links to the blog and documentation, which would be useful if the author needs help with some feature of Ghost. Also, there's not anything that can be modified settings-wise from the about page (unless there's some hidden feature I'm not aware of).

If not, then I agree with having consistency in not letting them get to it by entering the URL.

Although I don't have a great idea on how to give them the about link, should we chose to grant them access.

**Comment by ErisDS** [comment]
This problem is resolved by [Zelda](https://github.com/TryGhost/Ghost/pull/5273). It was confusing in the current admin because of the way about was nested under settings, but now it will live in the dropdown menu:

![](http://puu.sh/hTcNn.png)
