### ISSUE TITLE
Ghost admin should not error if the currently active theme is missing.

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#5155]
If you try to start Ghost and access the admin panel when the currently active theme is not present in the `content/themes` directory, the following error is thrown

![](http://puu.sh/hgiY1.png)

The admin panel should function 100% without a theme present, so that you can change theme to one that is present. This is a regression.

The frontend should show the error "The currently active theme casper is missing.", this also appears to have lost some styling.

### Steps to Reproduce

1. Run Ghost at least once
2. Stop Ghost, remove the active theme
3. Start Ghost, try to access `/ghost/` to change the theme

### Technical details: 

* Ghost Version: master

**Comment by GNima** [comment]
Any ideas how to fix this without updating ghost? I've deleted a theme after trying it out and now I can't get to the admin panel.

**Comment by JamesJosephFinn** [comment]
Wow. You can't access the admin panel on a fresh install if you delete the `casper` directory?! I've even re-uploaded the entire casper directory that I deleted from the server, and the darn thing won't stop throwing `500`.
