### ISSUE TITLE
Opening PSM breaks editor's mouse scrolling

### ISSUE THREAD

**Issue by novaugust** [TryGhost/Ghost#5163]
Not sure what's going on here, but I've had this happen to me a few times without figuring out how to reproduce it - now I can!

## Issue
My mouse scroll doesn't work in the editor after opening the PSM.

## Repro

1. Focus on the editor
1. Open the PSM
2. Close the PSM (clicking off of it, or X, either does the same)
2. try to scroll the editor - you can't

You can unbreak the scroll by unfocusing the editor (click on the title input, for example)
(Long gif showing all these things...)
![broken-scroll](https://cloud.githubusercontent.com/assets/1207005/7219187/011efdcc-e694-11e4-94e7-d590f14ec37d.gif)

## Specs

OSX 10.10.2
Chrome 42.0.2311.90
0.6.0 (Ghost Pro)
Using two-finger gesture mouse-pad scroll

**Comment by ErisDS** [comment]
Nice bug report sir!

**Comment by ErisDS** [comment]
Ok, maybe I spoke to soon. I cannot reproduce this on mac os 10.10, chrome 42.0.2311.90 :(

Can anyone else?

**Comment by novaugust** [comment]
Updated with more speccy specs & what sort of scrolling I'm attempting, in case that helps for repro.

**Comment by ErisDS** [comment]
Sorry, still no dice for me!

**Comment by PaulAdamDavis** [comment]
This is weird. I can reproduce every other try when Chrome is on the a 2x retina screen, but not once a 1x screen. I can't see how the screen should make _any_ difference at all, but that's how it is for me.

**Comment by novaugust** [comment]
I still have it happening but... haven't noticed it on Zelda. Going to close against that, maybe it'll get reopened someday
