### ISSUE TITLE
Is Support for Asciidoc possible to imagine ?

### ISSUE THREAD

**Issue by jamroks** [TryGhost/Ghost#5164]
Hi,

 everything is in the title, i'm very comfortable with asciidoc syntax that's why i would like to know if this is something that can be implemented ?   if yes , then is it via a plugin system or extension of some sort ?

i'm not aware of the way ghost can handle this type of integration since i'm new to ghost .

By the way , this integration could be done maybe with the asciidoctor.js (javascript)  port of asciidoctor (ruby)

Thanks

**Comment by ErisDS** [comment]
Hi there @jamroks, welcome to Ghost's GitHub! Our writing system is based very heavily around markdown at the moment. There aren't any extension points to change that, and it would be pretty tricky to make that possible. 

Nonetheless, if you want to see it the best place to put your idea & build traction for it is on the [wishlist](http://ideas.ghost.org) :)
