### ISSUE TITLE
Allow flushing of access tokens from the UI

### ISSUE THREAD

**Issue by d4nyll** [TryGhost/Ghost#5165]
Let's say I'm logged in somewhere public and forgot to log out, I'd like to have a feature where I can log myself out of all sessions. Currently, I am simply running `sqlite> delete from accesstokens;` to flush the `accesstokens` table and then logging in again.

It would be good if this feature is implemented as part of the UI.

**Comment by ErisDS** [comment]
Hi @d4nyll, welcome to Ghost's GitHub! We recently setup a [wishlist](http://ideas.ghost.org) where you can make suggestions like these (this link is available from inside the admin panel too). The wishlist allows people to vote, which GitHub doesn't - making it a much better way to get traction for ideas and gauge priority :)

**Comment by dayuloli** [comment]
Thanks @ErisDS I wasn't aware of the wishlist. I have created an [entry](http://ideas.ghost.org/forums/285309-wishlist/suggestions/7643373-sign-out-everywhere).

**Comment by d4nyll** [comment]
Thanks @ErisDS I wasn't aware of the wishlist. I have created an [entry](http://ideas.ghost.org/forums/285309-wishlist/suggestions/7643373-sign-out-everywhere).
