### ISSUE TITLE
posts object sort order?

### ISSUE THREAD

**Issue by rwboyer** [TryGhost/Ghost#5166]
Trying to make a ghost theme that uses the tag-{slug}.hbs feature. Wondering if there's a way/best practice to alter the posts object sort order on those tag specific pages. IE. instead of new->old sort old->new

?

Thanks

**Comment by ErisDS** [comment]
Hi there @rwboyer, it's not yet possible to change the order of posts. You'll find a spec over in this issue #889 - it's one of the oldest here in the repo and hasn't been looked at yet due to lack of demand.

Maybe you'd like to have a go? Closing this as a duplicate.
