### ISSUE TITLE
Welcome Tour: Add triggers to tour system

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#5170]
This issue is part of the [welcome tour feature](https://github.com/TryGhost/Ghost/issues/5168) and should be implemented behind a config flag (not labs) to start with. An example of how to do this exists in [this PR](https://github.com/TryGhost/Ghost/pull/5115).

---

![](http://puu.sh/hmaUn.gif)

Description:

Further to getting the positioning and interactions working for the icon and tip in issue #5169, we also need to wire up the triggers that will cause the icons to show at the right time. These triggers may be based on user interactions, time delays, criteria being met or a combination of all of them. 

Spec:

As yet there is no definite spec for what triggers will look like, rather some loose ideas of the kind of events we want to base tour items on. The triggers are likely to be based on a criteria that needs to be met as well as events. 

Some items may appear at the same time (e.g an initial set that appear once the user is logged in) and others may happen after another tour item is closed, after a certain amount of time has passed, or after the user completes an action like publishing a post.

Some example rules:
- After the user logs in, their user data is loaded (session.user is ready) and they visit the content screen, the content tour item shown in the image above should be present. It should remain present in that location until it is closed/marked as seen.
- Show a tour item on the help menu X amount of time after the user was created and after the initial tour item(s) are marked as seen
- Show a tour item on the post setting menu X minutes after the user enters the editor screen for the first time. It should appear immediately every subsequent time the user visits the editor until it is dismissed.

Recording the information for how to trigger each item may be quite tricky. It may be necessary to hardwire in some triggers to specific interactions using sendAction calls. That's perfectly fine :)

It may also be necessary to persist whether or not an item has been triggered yet. The won't be properly possible without # so it's fine if the trigger state doesn't persist with this issue.

The result of this issue should be the implementation of a couple of example triggers for the two demo items with at least one of them having complex rules to show how it can be done.

**Comment by kevinansfield** [comment]
Closed via https://github.com/TryGhost/Ghost-Admin/pull/527
