### ISSUE TITLE
Welcome Tour: Persist the state of tour items in the client

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#5172]
This issue is part of the [welcome tour feature](https://github.com/TryGhost/Ghost/issues/5168) and should be implemented behind a config flag (not labs) to start with. An example of how to do this exists in [this PR](https://github.com/TryGhost/Ghost/pull/5115). 

This issue requires other parts of this feature to be built before it can be done.

---

![](http://puu.sh/hmaUn.gif)

Description:

When a tip, or the whole tour is dismissed in the client, we need to persist this data to the server by updating the user's tour settings. Note that if the user skips the full tour, this should mark all items as 'seen'. This way we can still add new tour items later when additions are made.

Spec:

Each tour item will need to at least persist when it is marked as seen. Due to the complex triggering rules explained in #5170 some or all items may also need to persist the fact that they have been triggered and should now be shown. The `tour` field for a user will be empty by default, and populated as and when tour items need to save some data about themselves. 

Using JSON, this might look something like:

{
  "content": {
     "seen": true
  },
  "editor": {
     "triggered": true,
     "seen": true
  },
  "help": {
     "triggered": true
   }
}     

If a property doesn't exist or isn't set, then it is considered false. 

If a user hits the 'opt out' option, then all of the tour items which currently exist in the client should be marked as seen. 

By treating each tour item individually in this way, we will be able to add new tour items in the client in future and they will be shown to the user because they will not yet exist in the `tour` field. This means we can create a completely new tour in future if the admin UI significantly changes, or add new tour items for important new features.

The result of this issue should be that refreshing the page no longer brings closed tour items back and persists the 'trigger' state.

**Comment by nightfox** [comment]
@ErisDS Would it be okay if I pick this issue up?

**Comment by nightfox** [comment]
@ErisDS is the Tour feature scrapped/put on the back burner?

**Comment by ErisDS** [comment]
There is no css/html for this feature at present and this particular issue requires other issues to be done first. It is kind of on hold just because the html/css is needed first.

**Comment by kevinansfield** [comment]
Closed via https://github.com/TryGhost/Ghost-Admin/pull/527
