### ISSUE TITLE
Welcome Tour: Migration rules for tour items

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#5173]
This issue is part of the [welcome tour feature](https://github.com/TryGhost/Ghost/issues/5168) and should be implemented behind a config flag (not labs) to start with. An example of how to do this exists in [this PR](https://github.com/TryGhost/Ghost/pull/5115).

---

![](http://puu.sh/hmaUn.gif)

There is a decision to be made about whether existing Ghost users are shown the tour, or whether we should default the items to 'seen' for exising users. 

By far and away the easiest option from a technical perspective would be to show the tour to all existing users. There's always a chance they'll find something they didn't know about, and it only takes two clicks to dismiss them all. If this is considered OK then this issue can be closed as there's nothing to do here.

If it's decided this would be too annoying and we need to ensure existing users don't see the tour, then we need to implement a migration similar to the one that exists for [permissions fixtures](https://github.com/TryGhost/Ghost/blob/master/core/server/data/fixtures/index.js#L159) which checks if the database migration is upgrading to or through the relevant version, and inserts a piece of JSON marking each item as seen into the user table for each user.

**Comment by acburdine** [comment]
@ErisDS if we want to go ahead with the "don't show users the new tour," I could get something working for #6302 -> although that might hold it back a bit.

Honestly, given the mockup, and the fact that just clicking "opt out of these tips" will not show any tips anymore, I don't think it's that big of a deal to just show them to everyone. Even some old users might learn something :smile:

**Comment by ErisDS** [comment]
@acburdine that sounds sane to me. @JohnONolan what do you think: is it ok to show a welcome tour to all existing users providing it's possible to dismiss it with a single click, or do we need to make sure we only ever show it to new users setting up a blog for the first time?

**Comment by JohnONolan** [comment]
Defo all users. Including ones who are invited to Ghost (rather than setting up a blog for the first time)

Though presumably we should ship a database modification with the release of this feature which sets the value of "tour-done" (or whatever) to "true" ?

**Comment by ErisDS** [comment]
Cool! That database update is already done, all users have a tour field, intention is to store more than just true/false, so we can add new tour items in future to go with new features and show these: Spec here: https://github.com/TryGhost/Ghost/issues/5172

Should be able to move forward with this @acburdine ?

**Comment by acburdine** [comment]
Yeah I think so. Only thing now is if you want me to get the tour feature done before db migration 005 lands so that the migration can go there.

**Comment by ErisDS** [comment]
@acburdine the migration is already done. https://github.com/TryGhost/Ghost/blob/a3f107da8e33a79ad311717248fa76bd9966a1ac/core/server/data/schema.js#L41

**Comment by acburdine** [comment]
No I meant the modification to auto-hide all the new tours for existing users :smile:

**Comment by ErisDS** [comment]
I'm totally lost! We don't want to auto-hide all the new tours for existing users.

**Comment by acburdine** [comment]
> Though presumably we should ship a database modification with the release of this feature which sets the value of "tour-done" (or whatever) to "true" ?

That led me to assume we'd hide the tours for existing users, but if not then i misunderstood :smile:

**Comment by acburdine** [comment]
So, given that we've established to show the tour to everyone, regardless of whether they're new or old, this issue should be able to be closed I think?

**Comment by ErisDS** [comment]
:+1:
