### ISSUE TITLE
prev / next not appearing after updating to 0.6.1

### ISSUE THREAD

**Issue by cwonrails** [TryGhost/Ghost#5177]
Issue: prev/next no longer appears at the bottom of posts. Present in all browsers. Reverting to Casper 1.2.0 _does not_ fix the issue.

![broken prev-next](https://cloud.githubusercontent.com/assets/4729979/7281013/7b4ced70-e8ec-11e4-989d-987dc2893142.png)

Theme: Casper 1.2.1
Ghost version: 0.6.1
OS: Ubuntu 14.04 server
node version: 12.02
npm version: 2.7.6

**Comment by hkalant** [comment]
Issue confirmed. It doesn't work for my blog as well.

Theme: Modified version of Casper 1.2.0
OS; Windows 8.1
node version: 10.36

**Comment by ErisDS** [comment]
This is an absolute beauty of a bug.
