### ISSUE TITLE
process name

### ISSUE THREAD

**Issue by seinolab** [TryGhost/Ghost#5186]
Just a simple request.  To make easier monitoring processes or other operations, I suggest that Ghost has a own process name in `ps` command.

For example, add the following line into index.js:
```javascript
process.title = 'ghost';
```

Best regards,

**Comment by novaugust** [comment]
hey @seinolab, Ghost can be run as an npm module within a larger application, where doing a global change like that would be a mean thing. if you've got more feature requests, we have [a special site](http://ideas.ghost.org/forums/285309-wishlist) just for that - we like to keep github limited to implementations and bug reports :)
cheers
