### ISSUE TITLE
Missing mail section in development mode of config.example.js

### ISSUE THREAD

**Issue by booyaa** [TryGhost/Ghost#5188]
Just a minor nitpick, would it be okay to update the comments to mention ghost will crash out if mail section is missing or to add an empty one i.e. `mail{},`?

If it's okay I'll raise the PR.

**Comment by ErisDS** [comment]
This should not be happening, so if it is its a bug that needs fixing :)

**Comment by novaugust** [comment]
Hi @booyaa, I responded to you in slack as well, like so:
>sounds like an issue with your environment
>if transport isn't configured, nodemailer falls back to direct mail, which might go boom for you: https://github.com/andris9/Nodemailer#use-direct-transport (edited)

So, a PR to fix things is welcome if it turns out to not be specific to your environment, but I don't see any need to modify default config in `config.example.js`

**Comment by booyaa** [comment]
so in the absence of mail section it fallbacks to nodemail?

**Comment by javorszky** [comment]
Hi @booyaa. No, if there is no configuration for mail in config.js, Ghost should use direct mail method which is part of the nodemailer version Ghost is using.

What error messages do you get when you experience it crashing?

**Comment by booyaa** [comment]
Here's the stack trace (happens just after I hit OK LET'S DO THIS button) during setup phase:

Running in development mode and config.js (can attach if you want is a copy of config.example.js)

    /usr/src/ghost/core/server/mail.js:95
                    if (data.error.errno === 'ENOTFOUND') {
                                  ^
    TypeError: Cannot read property 'errno' of null
        at EventEmitter.<anonymous> (/usr/src/ghost/core/server/mail.js:95:31)
        at EventEmitter.g (events.js:180:16)
        at EventEmitter.emit (events.js:95:17)
        at DirectMailer.<anonymous> (/usr/src/ghost/node_modules/nodemailer/node_modules/directmail/lib/mailer.js:138:30)
        at asyncCallback (dns.js:68:16)
        at Object.onanswer [as oncomplete] (dns.js:147:9)

    npm ERR! Linux 3.18.11-tinycore64
    npm ERR! argv "node" "/usr/local/bin/npm" "start"
    npm ERR! node v0.10.38
    npm ERR! npm  v2.7.3
    npm ERR! code ELIFECYCLE
    npm ERR! ghost@0.5.10 start: `node index`
    npm ERR! Exit status 8
    npm ERR!
    npm ERR! Failed at the ghost@0.5.10 start script 'node index'.
    npm ERR! This is most likely a problem with the ghost package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     node index
    npm ERR! You can get their info via:
    npm ERR!     npm owner ls ghost
    npm ERR! There is likely additional logging output above.
    npm ERR! Linux 3.18.11-tinycore64
    npm ERR! argv "node" "/usr/local/bin/npm" "start"
    npm ERR! node v0.10.38
    npm ERR! npm  v2.7.3

    npm ERR! Uncaught, unspecified "error" event.
    npm ERR!
    npm ERR! If you need help, you may report this error at:
    npm ERR!     <https://github.com/npm/npm/issues>

    npm ERR! Please include the following file with any support request:
    npm ERR!     /usr/src/ghost/npm-debug.log

I'm assuming direct mail means it's looking for the sendmail or something similar (a bit like how php's mailer works?)

**Comment by javorszky** [comment]
Thanks for that. No, direct mail is just that. Direct. It sends the message to the MX server of the recipient. We've removed sendmail a while ago.

**Comment by booyaa** [comment]
I think I've shed some ligh on this problemt, and apologies for not mentioning this upfront. I'm using docker, furthermore my dev docker engine is using the virtual box boot2docker image (a super light weight linux distro). I was able to avoid a crash by explicitly declaring a dns server using `--dns 8.8.8.8`

    Ghost is running in development...
    Listening on 0.0.0.0:2368
    Url configured as: http://localhost:2368
    Ctrl+C to shut down
    GET /ghost 303 12.955 ms - -
    *snip*
    GET /ghost/api/v0.1/authentication/setup/ 200 30.511 ms - 28

    ERROR: Email Error: Failed sending email.
     Unable to send welcome email, your blog will continue to function.
     Please see http://support.ghost.org/mail/ for instructions on configuring email

Investigating the crashing out exception on nodemailer issues confirms this is a DNS issue: andris9/Nodemailer/issues/409

Is it worth trying raising a bug report for the crashing version of the exception? I don't mind if it's deemed specific to my environment, hopefully this issue will help others trouble.

**Comment by ErisDS** [comment]
This is sounding more and more like it is the same as this bug: #5095 

Are we perhaps just not handing errors from nodemailer quite right? cc @javorszky :wink:

**Comment by javorszky** [comment]
That may be the case. I'll look into it over the weekend. Also backporting things. And allowing fancy domains. :)

**Comment by novaugust** [comment]
And picking people up from airports.
I'd also fancy a boat, if you wouldn't mind.

**Comment by javorszky** [comment]
That's not the weekend :P

**Comment by jaswilli** [comment]
I'm going to close this against #5243.

As discussed above, this isn't really an error specific to sending mail, but rather a DNS-related error that propagates through nodemailer and then our error handling code incorrectly assumes that an error object exists when it may not.
