### ISSUE TITLE
Frontend controller refactor

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#5192]
It's always hard to spec a refactoring issue, as it's always more art than science ;)

This refactor is one of the key parts of the work we need to do to refactor the [entire frontend](https://github.com/TryGhost/Ghost/issues/5091) of Ghost (that is the blog rendering part) so that we can make [Channels](https://github.com/TryGhost/Ghost/wiki/Channels-101) a reality.

---

The frontend controller is currently made up of 3 functions that are almost identical for each of the [index](https://github.com/TryGhost/Ghost/blob/master/core/server/controllers/frontend.js#L127), [tag](https://github.com/TryGhost/Ghost/blob/master/core/server/controllers/frontend.js#L164) and [author](https://github.com/TryGhost/Ghost/blob/master/core/server/controllers/frontend.js#L218) routes. 

This hardcoded, duplicated logic makes it hard to extend Ghost or make these routes behave more dynamically. We need to abstract this logic out a bit to make it easier to work with.

The aim of this issue is to refactor these three functions into a single rendering function and a set of configuration properties for each route/channel. It can all continue to live in the same file, but we should end up with a more abstracted controller, ready to move this into a separate system.

The document on [channels](https://github.com/TryGhost/Ghost/wiki/Channels-101) explains the kind of configuration properties we expect to have for each route/channel. It will all remain hardcoded at the moment - it won't yet become configurable or extensible - that's another step.

There is one goal for this issue, of deduplicating logic and determining exactly what bits of information, like the url, or the number of postsPerPage, we need to customise for each one to make it work exactly as it does now.

**Comment by acburdine** [comment]
@ErisDS I'll take a crack at this this weekend and see what I can come up with :)

**Comment by acburdine** [comment]
@ErisDS before I rewrite this, I have a question about channels. I read through the documentation on the wiki, and I saw that the author and tag behavior is/should be identical with regards to templating. However, the current controller allows specific tag templates, but not specific author templates.

My question is, which one is correct? Personally, I would vote for both tags and authors being able to have specific templates.

**Comment by ErisDS** [comment]
Definitely both, I thought that was already implemented!!!

**Comment by acburdine** [comment]
@ErisDS I created a bit of test documentation for the channel options being passed in here:
https://gist.github.com/acburdine/69ac2a281dcccfc66318

 Can you take a look at let me know if I'm on the right track?
