### ISSUE TITLE
Update "Welcome to Ghost" post to remove/update "Quoting" paragraph (re. spell check)

### ISSUE THREAD

**Issue by jpelgrom** [TryGhost/Ghost#5194]
When you do a fresh install of Ghost, the "Welcome to Ghost" post still includes the following paragraph:

![welcome-to-ghost](https://cloud.githubusercontent.com/assets/8148535/7350390/48bd456e-ecff-11e4-9b5c-ed71206ec000.png)

Since spell check is now built in to the editor/supported, this paragraph doesn't make much sense anymore.

### Steps to reproduce

 1. Download Ghost from https://ghost.org/download/
 2. Install and start Ghost locally
 3. Go to `localhost:2368`

The post created has the paragraph from the screenshot about spell check.

### Technical details

Ghost version: 0.6.2, download from https://ghost.org/download/

---

<sub>And it looks like wisdomous isn't an actual word</sub>

**Comment by novaugust** [comment]
@jpelgrom, I want to hug you. Thanks for a great writeup on your first go - we'll get this fixed up by the next release thanks to you - and if you'd like, you could even [be the person who PRs the fix](https://github.com/TryGhost/Ghost/blob/master/CONTRIBUTING.md#pull-requests) ;)
Cheers!

**Comment by novaugust** [comment]
>And it looks like wisdomous isn't an actual word

Just want to reiterate that hugging.

**Comment by jpelgrom** [comment]
Thank you for the compliment, @novaugust :). My creative writing skills aren't that good, though, so unless someone else rewrites the paragraph for me (since we obviously still need something about quoting), I'm not planning on fixing it myself.

**Comment by JohnONolan** [comment]
lmao this is awesome

**Comment by nuclearpengy** [comment]
ROFL! :-D

**Comment by jpelgrom** [comment]
I'm sorry, but I don't understand why this is so funny all of a sudden. Is there some inside joke I don't know about?

**Comment by jschaich** [comment]
this is just great!
