### ISSUE TITLE
No indentation when embedding Gist from GitHub - [Casper theme - Chrome]

### ISSUE THREAD

**Issue by alexellis** [TryGhost/Ghost#5195]
### Issue Summary

While using Chrome 42 on Windows 7 64-bit including an embedded gist from GitHub results in no indentation for the code example. Casper theme.

### Steps to Reproduce

1. Write a blog post
2. Include gist from following location with this code:
```<script src="https://gist.github.com/alexellis/0bb982253f3619e29f18.js"></script>```
3. Publish and review. 

Working example at:
http://quad.ae24.space/nasa-earth-imagery-api/

Any other information you want to share that is relevant to the issue being
reported. Especially, why do you consider this to be a bug? What do you expect to happen instead?

Indentation works fine with IE 11

There appears to be some CSS conflict between the embedded example and the base/Casper theme.

### Technical details:

* Ghost Version: Ghost 0.5 Casper theme
* Client OS: Windows 7
* Server OS: Linux quad 3.18.10-1-ARCH #1 SMP PREEMPT Wed Mar 25 20:03:15 MDT 2015 armv7l GNU/Linux
* Node Version: v0.12.2
* Browser: Chrome 42
* Database: SQLite

![image](https://cloud.githubusercontent.com/assets/6358735/7370631/5526e0a8-edb3-11e4-91a8-df6b982618b9.png)

**Comment by JohnONolan** [comment]
Thanks for reporting! Would you mind moving this to https://github.com/TryGhost/Casper please?

**Comment by JohnONolan** [comment]
Please also ensure that you're using the latest version of Ghost and Casper before reporting
