### ISSUE TITLE
Menu button is in a box on a blogpost with Casper

### ISSUE THREAD

**Issue by jschaich** [TryGhost/Ghost#5199]
### Issue Summary

When opening a blogpost an a small screen or mobile device the menu button gets suddenly a box around itself.

### Steps to Reproduce

1. Visit i.e. https://thejester.at
2. Open a random post
3. See the change of the Menu button:

![screenshot_2015-04-30-00-41-33](https://cloud.githubusercontent.com/assets/11455444/7409239/fcf29c56-ef24-11e4-87df-17f763e01c51.png)

This is a bug because it looks kind of odd to me and does not fit to the rest of the experience.

### Technical details

* Ghost Version: 0.6.2
* Casper Version: 1.2.2
* Client OS: Android 5.1 
* Server OS: Ubuntu 14.04
* Node Version: 
* Browser: Chrome
* Database:

**Comment by novaugust** [comment]
Hey @jschaich, thanks for the writeup and screenshot. This issue should actually be on tryghost/casper, as ghost isn't responsible for generating what you're seeing there :) I'm going to close this and move the issue over for you, cheers

**Comment by novaugust** [comment]
Actually @jschaich, after looking into it a bit more, I think this may be an issue with whatever customizations you've done to casper. Check out [demo.ghost.io](http://demo.ghost.io) to see that it is working as it should be in Casper.

**Comment by novaugust** [comment]
Right! Sorry for the runaround - you probably just need to update your theme to the latest casper :)

**Comment by jschaich** [comment]
thanks, sorry for the troubles!
