### ISSUE TITLE
Static-page titles are not handled by core/server/helpers/meta_title.js

### ISSUE THREAD

**Issue by JNeitzel** [TryGhost/Ghost#5205]
Can we change it to address this issue please? Thanks in advance!

I have fixed it for my blog, which is currently running the zip-file-released version of ghost-0.6.2. The fix in my synced Ghost master branch is available via - https://github.com/JNeitzel/Ghost/commit/21ea94149d445fb9b2395fa1824fa0a81c6e037e .

Please ask if you've any questions, feedback, etc. Cheers :)

**Comment by ErisDS** [comment]
Hi @JNeitzel - could you take a few minutes to explain what you're reporting? There's a handy bug template in our [contributing guidelines](https://github.com/TryGhost/Ghost/blob/master/CONTRIBUTING.md#bugs) that shows the kind of info to include.

Thanks :+1:

**Comment by JNeitzel** [comment]
Hi @ErisDS, I just did a pull request ( https://github.com/TryGhost/Ghost/pull/5206 ). Sorry, I'm an issue reporting newbie. In any case, the issue should be labelled as a bug, but I didn't see how to add the label when opening the issue.

The explanation is the diff and commit message. In short,

`
-        title = this.post.meta_title || this.post.title;
+        /*
+         * XXX: Not reached for static pages using (page|post).hbs template(s).
+         *      "_.contains(context, 'post') && " breaks it / them.
+         */
+        title = this.post.meta_title || this.post.title + pageString + ' - ' + blog.title;
     } else {
-        title = blog.title + pageString;
+        /*
+         * XXX: The following workaround satisfies my needs.
+         *      I omit this.post.meta_title here since I never use it.
+         */
+        if (this.post) {
+            title = this.post.title + pageString + ' - ' + blog.title;
+        } else {
+            title = blog.title + pageString;
+        }
`

I hope this helps.

**Comment by ErisDS** [comment]
Only admins can add labels but anyone can file a bug report :wink: 

Please can you take a few minutes to read the [contributing guidelines](https://github.com/TryGhost/Ghost/blob/master/CONTRIBUTING.md)? There's tonnes of advice in there about both bug reports and raising PRs that will help you get your fix merged.

**Comment by JNeitzel** [comment]
Gotcha on the only admins can add labels thing. Sure thing. I'm working through the https://github.com/TryGhost/Ghost/blob/master/CONTRIBUTING.md now. Thanks a mil.
