### ISSUE TITLE
Unknown file with long name

### ISSUE THREAD

**Issue by dayuloli** [TryGhost/Ghost#5207]
I have in my application root directory a file with a long name.

    -rw-r--r--  1 root   root   41093 Apr 10 18:09 1428689398435233713dac7997ecaa3196fd34a033cb1

With the following content

```
%PDF-1.7
3 0 obj
<</Type /Page
/Parent 1 0 R
/MediaBox [0 0 1190 841]
/Resources 2 0 R
/Annots [
]
/Contents 4 0 R>>
endobj
4 0 obj
<</Filter /FlateDecode /Length 40216>>
stream
```

What is this file and is it safe to get rid of it?

**Comment by novaugust** [comment]
Hey @dayuloli, we use github for tracking bugs and implementing features. Something like this is more suited for the [forums](https://ghost.org/forum) or slack.
Just the same, Ghost definitely didn't put that file there; feel free from that perspective :)
