### ISSUE TITLE
Bug: The arrow on the "Update post/page" button spins a lot

### ISSUE THREAD

**Issue by thomasclausen** [TryGhost/Ghost#5209]
### Issue Summary
When I hover the button to update a post or page the arrow does a 900&deg; spin - from -360&deg; to 540&deg;.
I don't know if this is on purpose, but it seems like a lot of rotations.

![ghost-arrow-superspin](https://cloud.githubusercontent.com/assets/756516/7441462/201b74ee-f0e9-11e4-9943-5ec788654104.gif)
This gif isn't the best example because of the low framerate. It shows the many rotations at least when the mouse leaves the button.

### Steps to Reproduce

1. Log in to the Ghost admin
2. Edit a post/page
3. Hover the button to "Update post/page"

It seems a bit too much to spin 900&deg;.

### Technical details

* Ghost Version: 0.6.2
* Client OS: Windows 7
* Server OS: localhost
* Node Version: v0.10.26
* Browser: Chrome & Firefox
* Database: ?

**Comment by JohnONolan** [comment]
This is intended behaviour :+1:
