### ISSUE TITLE
Chrome never remembers my password from the /ghost/signin page

### ISSUE THREAD

**Issue by Soares** [TryGhost/Ghost#5211]
This bug is a bit strange. Google Chrome never remembers (or offers to remember) a password entered on the /ghost/signin page of my blog, which is a ghost 0.6.0 site. I'm not entirely sure that this is ghost's problem, but that's the *only* page I frequent where chrome fails to recognize a password form, and it's fairly irritating. (And yes, I checked to make sure that I hadn't accidentally given a "never remember my password" for that site in the past.)

**Comment by ErisDS** [comment]
Hi @Soares, you're not alone. This is a known issue which is tracked in #4651. Unfortunately there are not yet any good workarounds for making pure-JS forms play nicely with password managers, but the issue remains open in the hope that we will find one soon.
