### ISSUE TITLE
Invitation link not working if ghost is being used as part of another express app on a sub-folder

### ISSUE THREAD

**Issue by dgonzalez** [TryGhost/Ghost#5212]
When using Ghost inside an already existing express app:
```
var ghost = require('./path/to/ghost');
app.use('/blog', ghost);
```
(very basic use case)

When a user is invited the link is pointing to the root of the website ignoring ```/blog```.

**Comment by dgonzalez** [comment]
I might submit a pull request in a couple of days. This is something that we need and I know exactly where it is.

**Comment by dgonzalez** [comment]
I have a fix for it. Just testing and writing the test coverage/ amending the existing ones.

**Comment by sebgie** [comment]
@dgonzalez welcome to Ghost!

Good catch :fish:! Would you mind updating your PR to conform to our [contribution guidelines](https://github.com/TryGhost/Ghost/blob/master/CONTRIBUTING.md#pull-requests)? It would be great if you could move the `fixes ...` to the first line of the description, add a short explanation,  and remove the `console.log` from the PR :).

**Comment by dgonzalez** [comment]
Yes of course. I was in a rush this morning this is why the code smells so badly. I am doing it right now.

**Comment by dgonzalez** [comment]
Reopened: https://github.com/TryGhost/Ghost/pull/5217. Need to get better with interactive rebase...

**Comment by ErisDS** [comment]
I'm sorry, I don't think this a bug at all. I believe you're missing the subdirectory in the URL in your config.js file. Once that's there it will work.
