### ISSUE TITLE
Notifications on editor overlaps tag suggestion popover

### ISSUE THREAD

**Issue by letsjustfixit** [TryGhost/Ghost#5213]
### Issue Summary

The "bottom" notification (if there is any open at a time) overlaps with the suggested tag popver dialogs. 
![Notification overlap 1](http://i.imgur.com/k2xNl93.png)
![Notification overlap 1](http://i.imgur.com/vGIQXkw.png)

### Steps to Reproduce

1. Have a blog setup with a reason for notification window (first login, direct email etc)
2. Open the editor
3. Start adding tags which you've already used in other posts so the suggestion window should appear

Other method:

1. Open the editor
2. Save post
3. Try adding tag which you've already used in other posts so the suggestion window should appear

(4. if needed click save again to have a notification pop up again)

/* I did a search any only come up with #3592 but seemed like a different problem (about the tag insertation line overlap) */

### Technical details:

* Ghost Version: stable 0.6.2 
* Client OS: Debian 8.0 Jessie
* Server OS: Ubuntu 14.04.2 LTS, Trusty Tahr
* Node Version: 0.12.0
* Browser: Firefox 37.0.2
* Database: SQLite

**Comment by Artie18** [comment]
Well, I see couple of solutions here, we can hide all notifications if any tags are suggested or we can move them up on X pixels (depending on the height of the suggestion box). Second solution does not look pretty .

![notification area up with tags suggestion](https://cloud.githubusercontent.com/assets/2828920/7484107/c62f462a-f38d-11e4-8d2c-8daeda6ff9af.png)

It looks more like a design bug. Should it even be fixed?

**Comment by harryhope** [comment]
Generally in operating systems or applications with popovers or menus, they appear on top of other ui elements.

I think the most intuitive solution would be to just have the popover appear over the notifications.

**Comment by JohnONolan** [comment]
+1 for what @harryhope said - relatively simple z-index issue

**Comment by harryhope** [comment]
Cool, I can take this one then.

**Comment by jaswilli** [comment]
Closed via 0ec3bde
