### ISSUE TITLE
Loop Partial Producing 500 Error on Static Pages

### ISSUE THREAD

**Issue by sgiovanni** [TryGhost/Ghost#5228]
I'm building a new theme and would like to get posts to display on a static page using `{{> "loop"}}`. I'm receiving the following error: (500 [page-insights.hbs] pagination data is not an object or is a function). 

It seems strange that `{{> "loop"}}` works without error on the `home.hbs` file I created, but the error comes up on any `page-xxxx.hbs` file. If I remove lines with `{{pagination}}` from the `loop.hbs` partial, the page loads but there is no post data getting displayed.

I took great care making sure all the necessary files are present (based on Casper), and the static pages without the `{{> "loop"}}` are loading as intended.

Details:

Ghost v0.6.2
Mac OSX 10.10.3
Node v0.12.0

**Comment by ErisDS** [comment]
Hi there @sgiovanni! That  error message is telling you exactly what is wrong - there is no pagination available on a static page.

I recommend dropping by our [slack team](https://ghost.org/slack) or the [forum](https://ghost.org/forum)  if you have any more questions :wink:
