### ISSUE TITLE
(BUG): Post Editor intermittently auto-publishes

### ISSUE THREAD

**Issue by acburdine** [TryGhost/Ghost#5235]
When clicking the "publish now" link on a draft on the popup menu triggered by the spinning arrow, the post sometimes auto-publishes.

### Issue Summary

After creating multiple post drafts, going back to one of them to publish it and clicking on the "publish now" option in the popup doesn't change the button from "save draft" to "publish now" like it should. Instead, the post automatically publishes (not triggering the "saved" notification like it should) and the button is changed to "update post". As far as I could tell, going to the blog frontend and then back to admin (thus force-reloading Ember) seems to reset it; however, after correctly publishing one post and then immediately going to the next one, the irregular behavior again happens.

### Steps to reproduce

1. Clone the ghost repository
2. `npm install`, `grunt init`, `grunt dev` (or `npm start` if you prefer)
3. Setup the ghost blog and login
4. Create a bunch of test posts, one after the other (don't refresh Ember)
5. Go back to the first post and click on the "publish now" link on the popup menu
6. If the behavior works as expected (see "expected behavior" below), either return it to draft status or go ahead and publish it.
7. Go to the next post and attempt to publish it using the same method as described in step 5.
8. After one or two times the behavior should start to happen.

### Expected Result
Normally, the post save button should change from "save draft" to "publish now" when the "publish now" button is clicked in the popup menu. **Unless** you then click "publish now" once the button has changed correctly, the button should **not** change to "update now"

### Technical Details
* Ghost Version: master (latest commit)
* Client OS: Mac OS X Yosemite (10.10.3)
* Server OS: Same (local installation)
* Node Version: 0.12.2
* Browser: Chrome 42.0.2311.135
* Database: Sqlite

While the node version and sqlite don't represent the ideal situation, I'm fairly certain this is an Ember issue, and thus not related to the node server part at all.

**Comment by acburdine** [comment]
@rwjblue might also have some ideas on this as well as it's an Ember-related issue

**Comment by jaswilli** [comment]
This doesn't sound like a bug with the editor save button but rather that, depending on timing, the post auto-save happens to fire after "publish now" has been chosen.

**Comment by acburdine** [comment]
@jaswilli the button change that I talked about was just the effect of the bug. Sorry I should have phrased it better. :)

**Comment by jaswilli** [comment]
I'm not sure what bug you're talking about.  There's a timed auto-save in the editor, and if you can make it from whatever you're doing down to the save button and change it to "publish" before the save fires, it's going to save the post like that.  It's not dependent on creating and interacting with multiple posts or whether or not the app has been reloaded.

I'm going to close this as it doesn't accurately describe the behavior.  It does show that, intuitively, the published status of a post should probably not be changed via a "background" save event, though.

**Comment by acburdine** [comment]
ah okay. I wasn't sure what was causing that behavior to happen. Makes sense though. Thanks!
