### ISSUE TITLE
Tags listed as sentence string, similar to Jekyll filter

### ISSUE THREAD

**Issue by jasonsturges** [TryGhost/Ghost#5236]
One of the things I like about Jekyll is the [`array_to_sentence_string`](http://www.rubydoc.info/github/mojombo/jekyll/Jekyll/Filters:array_to_sentence_string) filter, which displays tags as a list with an Oxford comma and the word '_and_' for the final tag.

```
array_to_sentence_string(["apples", "oranges", "grapes"])
# => "apples, oranges, and grapes"
```

In Jekyll, mustache template is implemented as:

```
{{ page.tags | array_to_sentence_string | prepend: 'on ' }}
```

This issue logged as a feature request for consideration.

**Comment by ErisDS** [comment]
Hi there @jasonsturges!

This is possible using a combination of the existing helpers:

```
{{#foreach tags}}
  {{#if @last}} and {{else}}{{#unless @first}}, {{/unless}}{{/if}}{{name}}
{{/foreach}}
```

If you're keen on the idea of having a specific helper or option for this, I recommend adding it as a suggestion to our [wishlist](http://ideas.ghost.org).

**Comment by jasonsturges** [comment]
@ErisDS Hi, this is appreciated; although, tags are not anchors to collections - only text.

Even a utility to create the tag link (such as found within tags.js `utils.linkTemplate`) would be cool, if interest in adoption of this idea is minimal.

Not particularly fond of the wishlist functional implementation, I'll consider it.  Thanks.

**Comment by ErisDS** [comment]
I left the tags as text to keep the example brief - it's simple enough to turn them back into links, just change `{{name}}` to `<a href="{{url}}">{{name}}</a>`. All of this information can be found in the [theme documentation](http://themes.ghost.org/v0.6.0/docs/tags).

I'm not sure what you mean about the wishlist - this is the place where feature requests for Ghost belong, that way we can measure traction, which github does not allow us to do :wink:
