### ISSUE TITLE
CSS Tweak: .dropdown-toggle Button Doesn't Lost Focus When Clicked on Mobile

### ISSUE THREAD

**Issue by dbalders** [TryGhost/Ghost#5240]
### Issue Summary

Device: iPhone 6

When you click on the `^` next to 'Update Post', it focuses that element and spins just fine. But when you click it again, it doesn't lose focus. Kind of tricky because by clicking you are giving it focus, but I think that it should lose focus if it already has it when clicked to set it back to its original state

![update post off focus](https://cloud.githubusercontent.com/assets/4715098/7553258/7d229a82-f6a2-11e4-9f1b-40af25fe050e.gif)

### Steps to Reproduce

1. Log into the admin interface on an iPhone\
2. Open a post to edit
3. Click on the `^` next to the update post
4. Click on it again

### Technical details:

* Ghost Version: 0.6.2
* Client OS: Mac 10.10
* Server OS: Mac 10.10
* Browser: Safari Mobile
* Database: SQLite

**Comment by georgestephanis** [comment]
On desktop (Mac Chrome 44.0.whatever) the little side arrow never flips from bottom to top in the first place.

The dark blue focus indicator on that side remains until you click elsewhere on the page -- it's just indicating that focus is applied, not that it's active.  A different focus style may be merited here.

**Comment by georgestephanis** [comment]
Just confirmed on mobile.  Tapping a second time leaves it dark because it still has focus, even if no longer active and toggled.
