### ISSUE TITLE
Unhelpful error message, "Something went wrong" when Editor uploads image

### ISSUE THREAD

**Issue by dandv** [TryGhost/Ghost#5245]
An `editor` user on my blog can't upload images, but I can. The error message doesn't help.

They *can* upload the same image to their profile avatar.

Further investigation revealed a bunch of files in `/var/www/ghost` (not in `/var/www/ghost/content/images/2015/05/`) with apparently timstamped/autogenerated names:

```
14312721709005e543256c480ac577d30f76f9120eb74
14312721718315e543256c480ac577d30f76f9120eb74
14312721721165e543256c480ac577d30f76f9120eb74
14312721723655e543256c480ac577d30f76f9120eb74
14312721726485e543256c480ac577d30f76f9120eb74
14312721728885e543256c480ac577d30f76f9120eb74
14312721731545e543256c480ac577d30f76f9120eb74
14312721736035e543256c480ac577d30f76f9120eb74
14312721736485e543256c480ac577d30f76f9120eb74
```

**Comment by jaswilli** [comment]
Hi,

Here's a link to our bug reporting tips:  https://github.com/TryGhost/Ghost/blob/master/CONTRIBUTING.md#bugs

There may very well be a bug that your user is hitting, it's just from the information supplied I'm not able to reproduce what you're seeing.  Logged in as an Editor I'm able to upload images just fine.

It'd be great if you could provide some additional information (such as the request details from the network tab in the debug console, or any stack traces from node when this happens).

**Comment by ErisDS** [comment]
This sounds more like an environment/hosting issue than a bug in Ghost to me. Will reopen if a clear reproduction case comes to light.

**Comment by k-j-kleist** [comment]
Image uploading has failed for me several times for no obvious reason. After restarting Ghost, the same image has always uploaded fine.

Relevant info from stdout:

`"POST /ghost/api/v0.1/uploads/ HTTP/1.1" - - "http://EXAMPLE.COM/ghost/editor/" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:41.0) Gecko/20100101 Firefox/41.0"

Error Something went wrong uploading the file { [Error: ENOENT, open '/tmp/mLeH5o/14452301129173a5da5d4881da0c2c8d47ef2df4a4ee6']

errno: -2,

code: 'ENOENT',

path: '/tmp/mLeH5o/14452301129173a5da5d4881da0c2c8d47ef2df4a4ee6' }`
