### ISSUE TITLE
Use progressive reduction to let users upload images easily

### ISSUE THREAD

**Issue by dandv** [TryGhost/Ghost#5246]
I've been using Markdown for at least 6 years now. I know how to insert images.

But for the life of me, I couldn't figure out how to upload an image into a Ghost post, until I googled that. Having to type `![]` is easy enough, but very few new users will think that way about inserting an image. First they'll want to *upload the actual image*. 

Minimalism is nice but I suggest using [progressive reduction](http://layervault.tumblr.com/post/42361566927/progressive-reduction) instead of bewildering the user as to how in the world they might go about uploading a new image.

**Comment by jaswilli** [comment]
Hi,

Users can certainly upload an image via the image placeholder that's inserted into the preview.

I'm not entirely sure what you're looking to have happen by opening this issue.  I can appreciate that you had some trouble figuring out how to upload an image--perhaps you could open a PR against the "Welcome to Ghost" post that ships with all new blogs that made the steps more clear.

Anyway, we try to keep issues in GitHub limited to things that are directly involving development so I'm going to close.

**Comment by dandv** [comment]
I'm [not the only one who wants to upload multiple images](http://ideas.ghost.org/forums/285309-wishlist/suggestions/7204924-upload-multiple-images-at-once). Agree that this request is better suite for UserVoice though.
