### ISSUE TITLE
Document exactly how to setup Ghost on a path, e.g. at /blog

### ISSUE THREAD

**Issue by dandv** [TryGhost/Ghost#5247]
http://support.ghost.org/config/#url should be updated with a bit about setting up Ghost to expect the blog at a custom path, e.g. `/blog`. Here's another [request for this](https://ghost.org/forum/using-ghost/5067-routing-to-index-to-blog-path/).

No need to document proxying webserver configs, though linking to the nginx docs would be nice.

**Comment by jaswilli** [comment]
Thanks for the feedback.
