### ISSUE TITLE
Problems setting the post date

### ISSUE THREAD

**Issue by dandv** [TryGhost/Ghost#5248]
Entering a date in the past for my post has been pretty painful. Here are some things that don't work:

* Typing a single-digit day, as 
![image](https://cloud.githubusercontent.com/assets/33569/7556051/49dfb1a4-f72f-11e4-93cf-2c98cab4de2b.png) shows doesn't work - Ghost thinks the date is in the future
* typing anything invalid resets the date to what it was before I typed a valid string
 

![date entry problems](https://cloud.githubusercontent.com/assets/33569/7556047/2a772068-f72f-11e4-8c2d-00c570b0fc0b.gif)

**Comment by jaswilli** [comment]
There's definitely some weirdness in the way that input field behaves.  I think single digit days are okay, it's just something about when the change/validation is being triggered (and with what value).

**Comment by hex337** [comment]
Bah, sorry, was having merge issues, can ignore all of those except the last one :P
