### ISSUE TITLE
Add a calendar widget for entering the post date

### ISSUE THREAD

**Issue by dandv** [TryGhost/Ghost#5249]
There's a [calendar icon when entering the post publish date](https://github.com/TryGhost/Ghost/blob/master/core/client/app/templates/post-settings-menu.hbs#L31), but clicking it does nothing.

I wouldn't complain about this if it weren't for #5248.

**Comment by ErisDS** [comment]
Hi there @dandv! Could you please take a couple of minutes to read through our [contributing guidelines](https://github.com/TryGhost/Ghost/blob/master/CONTRIBUTING.md)? I appreciate the enthusiasm to improve things but it would really help us if you could take some time to familiarise yourself with the project :) We have a [wishlist](http://ideas.ghost.org) which is much better suited to feature requests.
