### ISSUE TITLE
"Blog title" is interpreted as a company

### ISSUE THREAD

**Issue by dandv** [TryGhost/Ghost#5251]
I've tried a few themes so far, and many interpret the `Blog title` setting from General as a sort of company, and display Copyright messages in the footer:

![image](https://cloud.githubusercontent.com/assets/33569/7556092/3d254080-f731-11e4-82a0-baf9d05894aa.png)

This *sort of* includes Casper:

![image](https://cloud.githubusercontent.com/assets/33569/7556094/5a8b22c0-f731-11e4-9da2-e476074d334a.png)

Obviously the responsibility [lies with the themes](https://github.com/fabienwang/Ghost-Flat/issues/1), but perhaps the meaning of the Blog title field can be communicate more clearly, or perhaps there should be a separate `copyright line` field like in Wordpress.

**Comment by jaswilli** [comment]
As you said yourself, if a theme developer chooses to display a blog title in a fashion that does not please you, you'll have to take it up with the theme developer or change the theme yourself.

This isn't really an issue that's appropriate for this repository.  As I mentioned earlier, we try to reserve GitHub issues for things that directly concern the development of Ghost, i.e., the software development process.

Random musings, issues with themes, and concerns about documentation not hosted in this repository are better suited for elsewhere.

**Comment by aidan-fitz** [comment]
We should be able to change the copyright notice in the settings. That way we can add things like a Creative Commons license.
