### ISSUE TITLE
In Settings, add a copy of the Save button at the bottom

### ISSUE THREAD

**Issue by dandv** [TryGhost/Ghost#5252]
Currently, the ergonomics of changing themes could use a little improvement:

1. Go to `ghost/settings/general/`
2. Scroll down to the bottom
3. Change the theme
4. Scroll back up
5. Click Save
6. Refresh /blog in another tab
7. Go back to the Settings tab
8. Scroll back down to the bottom and repeat from step 3.

Copying the Save button to the bottom would get rid of a lot of scrolling.

**Comment by ErisDS** [comment]
The current UI is a stepping stone towards something better. Closing as a wontfix.
