### ISSUE TITLE
Memory usage has been higher

### ISSUE THREAD

**Issue by Hi-Rube** [TryGhost/Ghost#5254]
Memory usage has been higher And increasing.
![image](https://cloud.githubusercontent.com/assets/4507462/7558769/996ab34a-f7de-11e4-8149-63cd187f3f2d.png)
![image](https://cloud.githubusercontent.com/assets/4507462/7558775/af4163a8-f7de-11e4-80bb-b7d1dc0ac824.png)

**Comment by ErisDS** [comment]
Hi there @Hi-Rube, I appreciate that memory consumption is a serious concern, but there isn't enough information here for anyone to work out what's going on. There are many possibilities for what could be happening here:

- the version of Ghost being used could be old or modified
- the monitoring software could be interfering with the metrics (this has [happened before](https://github.com/TryGhost/Ghost/issues/3980))
- the blog could be under high load (and therefore correctly using more memory)
- the theme being used could be memory intensive
- the garbage collection may not have run in the time monitored
- there might be an issue with the version of node, or other software used in conjunction with Ghost
- there might be an issue with your server
- there might be a memory issue with Ghost

We need extensive and detailed information to rule out all of the things at the top of the list before we get as far as trying to debug a memory issue in Ghost itself. Therefore I'd suggest treating this as an environment issue until such time as there's information & evidence which points to a problem with Ghost, as we have had recent detailed reports that memory usage in Ghost is [improving and stable](https://github.com/TryGhost/Ghost/issues/1914#issuecomment-96809436).

For help with your environment, I recommend using the [forum](https://ghost.org/forum), [slack](https://ghost.org/slack) or even stackoverflow.
