### ISSUE TITLE
Switch from using colors.js to chalk

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#5259]
This is a straightforward dependency swap & cleanup issue. It's a low priority, nice-to-have.

It seems colors.js has fallen out of favour, and [chalk](https://www.npmjs.com/package/chalk) is the new kid in town. It works in a slightly nicer way, meaning we can get rid of the lines of code which are pure workarounds:

https://github.com/TryGhost/Ghost/blob/3d5fe130c2dcbb0901f7d71da2d68b3c52348da0/core/server/errors/index.js#L24

The resulting output ought to be the same as we have now, with orange warnings, and red-white-green errors. Just using a different library to create the colors.

**Comment by acburdine** [comment]
@ErisDS just so there's not confusion, I don't see the color orange in either colors.js or chalk. Do you by chance mean yellow?

(Not that I'm picking up this one, but for anyone who wants to work on it in the future)

**Comment by ErisDS** [comment]
Yes.. that's what I meant :wink:, thanks!

**Comment by josephwegner** [comment]
I'm picking this up.

@acburdine can you provide any context on why jsHint requires the rainbow theme? Removing that line, for me, still has the correct colors when running `grunt jshint`.

I'll continue googling around for this, but if you have context I'd appreciate it.

**Comment by ErisDS** [comment]
That line of code is purely because jshint doesn't understand requiring things you don't call directly - it assumes it's not needed. Chalk works differently so it won't have the same problem :)

**Comment by josephwegner** [comment]
makes sense - thanks!

This will be a lot of grepping around, but I'd imagine I'll have a PR in soon enough.
