### ISSUE TITLE
Installing 0.6.2 on Node v0.12 causes warning about html-to-text

### ISSUE THREAD

**Issue by k-j-kleist** [TryGhost/Ghost#5264]
```
$ npm install --production
npm WARN engine html-to-text@1.2.0: wanted: {"node":">= 0.8.0 <0.12"} (current: {"node":"0.12.2","npm":"2.7.4"})
```
This is using CentOS release 6.6.

**Comment by jaswilli** [comment]
Hi @k-j-kleist,

That message can safely be ignored, as it's coming from one of Ghost's dependencies, not Ghost itself, and the package seems to work fine.  I do see that there's a newer version where they changed the allowed versions of node to include 0.12, so we should probably update to that so nobody has to see that warning message :smile:

**Comment by k-j-kleist** [comment]
Impressing turnaround time, guys!
