### ISSUE TITLE
Post publishing/retreiving API for self-hosted Ghost installatons?

### ISSUE THREAD

**Issue by iglvzx** [TryGhost/Ghost#5276]
I found information on the Ghost API here: https://github.com/TryGhost/Ghost/wiki/%5BWIP%5D-API-Documentation but it is not clear if this is only for a public API, for blogs hosted on Ghost's servers.

Will the API work locally, with self-hosted Ghost installations? Are there plans to create an API for communicating from local Node JS scripts/apps to the local Ghost installation?

**Comment by ErisDS** [comment]
Hi @iglvzx, thanks for your question - it's great that you're interested in working with Ghost. 

Questions like these are much more suited to our [slack](https://ghost.org/slack) community (or stackoverflow if you prefer) as GitHub is for tracking issues with the software.

Hopefully see you in slack :)
