### ISSUE TITLE
Import post max length

### ISSUE THREAD

**Issue by hadrienl** [TryGhost/Ghost#5279]
Hi,

I'm trying to import a blog from another platform for which I'm making a convert script. My new json file contains some posts with very long content. When I try to import it with "ghost/settings/labs/" if one post `markdown` or `html` attribute is longer than 5656 caracters, I got an error. Before trying on 0.6.x, I was playing on a 0.5.10 which was on my localhost and I didn't had the problem. It appears on the fresh 0.6.3 I installed on my prod server.

**Comment by cobbspur** [comment]
Hi hadrienl. 

I have tried to replicate this locally and couldn't. Perhaps there is something else going on here. If you can provide more details that would be useful, please see our [contributing guidelines](https://github.com/cobbspur/Ghost/blob/master/CONTRIBUTING.md#bugs) for details on what to include.

**Comment by hadrienl** [comment]
I've look deeper and I have not found precisely what is the cause of the fail. I have a big json. It doesn't import in 0.6.3. It does in 0.5.10. Then I've been able to copy the database of the 0.5.10 to the 0.6.3 and it finally worked. If you can give me a private email, I can send you my json to make some tests.

**Comment by cobbspur** [comment]
At least you have it working now, could you please the json file to david[at]ghost.org

**Comment by hadrienl** [comment]
I've tried with a Docker install of 0.6.3 and it worked nice. Maybe the problem is on my server side :/
