### ISSUE TITLE
Bug: "add tag image" displacement on mobile phone

### ISSUE THREAD

**Issue by CaiJimmy** [TryGhost/Ghost#5280]
![wp_ss_20150517_0001](https://cloud.githubusercontent.com/assets/5889006/7671105/b164813a-fcbe-11e4-932c-a8bc313ed73f.png)

Phone: Lumia 620
Navigator：IE11
Ghost 0.6.2

**Comment by ErisDS** [comment]
This issue was resolved by the UI changes in Ghost 0.7.
