### ISSUE TITLE
Use gravatar cache

### ISSUE THREAD

**Issue by schuer** [TryGhost/Ghost#5285]
If gravatar.com isn't available or doesn't perform well, a ghost blog stumbles. At least until the 2000 ms timeout is reached.

Wouldn't it be good to cache the gravatar images in a local cache folder and check for the lastModified before sending out a new request to gravatar.com? It could save from a lot of external requests and speed up the blog.

**Comment by JohnONolan** [comment]
It should be async as far as I know, anything beyond that is up to Gravatar to optimise - or for blog owners to upload a photo to Ghost rather than relying on Gravatar

**Comment by schuer** [comment]
Sry, you're right. Gravatar loads async and won't slow down the blog.
Thx for clearing up the issue!
