### ISSUE TITLE
Ghost logo / view blog link should be absolute

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#5288]
The Ghost logo icon in the top left corner of the Ghost admin UI is intended to be a link to the frontend of the blog:

![](http://puu.sh/hSL0g.png)

This is soon to be the 'view blog' link in [Zelda](https://github.com/TryGhost/Ghost/pull/5273) (new Ghost UI design: 

![](http://puu.sh/hSLqy.png)

This link is currently sporting a relative URL, but should be absolute. Using a relative URL causes problems with blogs served with mixed protocols or where a different secure URL is used for the admin compared to the front of the blog.

### Technical details: 

* Ghost Version: master

**Comment by hex337** [comment]
So, I took a look on the master branch, and was unable to find any reference to the "View blog" link. Is this issue referring to the top left logo link, or the "View blog" link?

**Comment by ErisDS** [comment]
Issue updated to reference that Zelda is a branch/PR

**Comment by ErisDS** [comment]
@hex337 are you working on this?

**Comment by hex337** [comment]
I was going to, but realized I don't understand enough about ember and routing. If anyone else wants to take it, go ahead. I'm learning about ember for today.
