### ISSUE TITLE
Dev Install requires PhantomJS to be installed

### ISSUE THREAD

**Issue by josephwegner** [TryGhost/Ghost#5291]
This is super minor, but the README section for a dev install should be updated to reflect the `phantomjs` requirement. The ember specs can't run if you don't have phantomjs installed globally.

**Comment by ErisDS** [comment]
I get why this was confusing, but the README is for people installing Ghost to use, whereas the instructions for contributors, which have extra requirements are in CONTRIBUTING.md instead: https://github.com/TryGhost/Ghost/blob/master/CONTRIBUTING.md#working-on-ghost-core

I think including phantomjs in the readme will confuse people as you only need that to run the tests.
