### ISSUE TITLE
Add a way to start ghost with non-default config file

### ISSUE THREAD

**Issue by ePirat** [TryGhost/Ghost#5312]
I need a way to start ghost with a specific config file rather than the default one.
I know that there is a environment variable to use (`GHOST_CONFIG`) but that is not a good solution when starting up multiple ghost instances in an automated way. Please let me know if there is a different way to start up ghost with a specific config path, if not, it would be great to consider adding this possibility.

**Comment by ePirat** [comment]
Additionally, `GHOST_CONFIG` has a confusing execution location as it is execute in some subdirectory where the ghost config module is so paths like `./config` won't behave as expected.

**Comment by ErisDS** [comment]
Hey @ePirat please ask questions in [slack](https://ghost.org/slack) not here :wink:

**Comment by ePirat** [comment]
So, the answer is: It is only possible by using [Ghost as an npm module](https://github.com/TryGhost/Ghost/wiki/Using-Ghost-as-an-NPM-module).
