### ISSUE TITLE
Min/max control broken during Zelda merge

### ISSUE THREAD

**Issue by JohnONolan** [TryGhost/Ghost#5313]
The min/max control (bottom left corner of nav menu) broke during the Zelda merge, I'm not sure why. This needs to either be fixed or replaced by the Ember version which @acburdine was working on

**Comment by acburdine** [comment]
My PR fixes it and works as it should.

**Comment by jaswilli** [comment]
@john As far as I can see it's working on master.  I have caching disabled and just rebuilt all assets so I think it should be ok.

**Comment by ErisDS** [comment]
It works intermittently for me in master - it seems to require a refresh to kick in after signin, will look at @acburdine's PR in a sec ;)

**Comment by jaswilli** [comment]
> it seems to require a refresh to kick in after signin

Ah, that makes sense as those elements that are getting event handlers bound to them won't exist when `didInsertElement` fires and you're not authenticated, and the only time it will re-fire is if the application is reloaded.

**Comment by jaswilli** [comment]
Closed via #5319.
