### ISSUE TITLE
User Onboarding - Flow navigation component

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#5317]
This issue relates to the 'Wiring & navigation behaviour'  part of the User Onboarding epic #5315

![](http://puu.sh/hXTug.png)

In #5316, I've dirtily re-hashed the `gh-activating-list-item` to do the flow navigation. The `gh-activating-list-item` component was originally used for the left hand settings menu on the settings screen, which no longer exists. Therefore it can likely be repurposed / converted into a specific component for handling the flow navigation. 

I imagine there's a much smarter way to code up this set of steps, with back and forward links, and where certain items are disabled when you're in a particular step - e.g. step 3 should be disabled if you're on step 1. 

Additionally, the back button is only supposed to appear when not on screen 1, and should take the user to the previous step.

**Comment by lukaszklis** [comment]
Why do you want to have a back button in the setup process? How is it supposed to work once you click "Back" on the third step after the owner's account has been created already?

**Comment by ErisDS** [comment]
@lukaszklis What happens when you go back is covered in #5339 and the related #5342
