### ISSUE TITLE
Can not load theme asset (script and font), Got a 500 server internal error

### ISSUE THREAD

**Issue by bugushi** [TryGhost/Ghost#5323]
hi,

I made a theme, in the theme assets folder, I added three files

`themes/guyu/assets/css/solarized_light.css `
`themes/guyu/assets/fonts/iconfont-tag.svg `
`themes/guyu/assets/js/highlight.pack.js`

In my local environment, All these three files can ben load successfully
In my website `guyustudio.com` , I can only load the css file,  but fail to load the svg and js file.

I have tried these below and not work:
1. restart ghost
2. restart nginx
3. power off & power on vps
4. rename `highlight.pack.js` to `highlight.js`

nginx `error.log` has no error when fail access to `highlight.pack.js`
the `highlight.pack.js` source code is in `https://highlightjs.org/`

please help me, thank you

-----------------------

and here is the request infomation:
```
Remote Address:127.0.0.1:33333 
Request URL:http://guyustudio.com/assets/js/highlight.pack.js?v=7d697b40bc 
Request Method:GET 
Status Code:500 Internal Server Error

Response Headers

Accept-Ranges:bytes 
Cache-Control:no-cache, private, no-store, must-revalidate, max-stale=0, post-check=0, pre-check=0 
Content-Encoding:gzip 
Content-Type:application/javascript; charset=utf-8 
Date:Sun, 24 May 2015 17:15:36 GMT 
ETag:W/"8c2a-1440189216" 
Last-Modified:Fri, 22 May 2015 10:09:32 GMT 
Server:nginx/1.4.6 (Ubuntu) 
Vary:Accept-Encoding 
X-Cache:MISS from 23.pages.googol.gl 
X-Cache-Lookup:MISS from 23.pages.googol.gl:7231 
X-Powered-By:Express
```

**Comment by ErisDS** [comment]
Hi @bugushi, we ask that you please do not use GitHub for personal support requests. GitHub is an issue tracker, it's where we keep tabs on issues with the Ghost software. For support requests, please use [slack](https://ghost.org/slack) or if you prefer [stackoverflow](http://stackoverflow.com/questions/tagged/ghost-blog).
