### ISSUE TITLE
Provide a simple docker file making it easy for other to start developing themes and features

### ISSUE THREAD

**Issue by mastoj** [TryGhost/Ghost#5335]
If there was a simple dockerfile in the repo it would be really simple for anyone to get started on OSX, linux or Windows developing themes etc. This would be a really nice addition if you ask me :)

**Comment by ErisDS** [comment]
Hey @mastoj Unfortunately, every hosting platform out there has it's own file that has to go in the root of the repo - making for a mess. Therefore we have a separate repository for those sorts of files: https://github.com/TryGhost/Ghost-Config

There isn't a Dockerfile there at the moment, but maybe you'd like to add one?

**Comment by mastoj** [comment]
make sense. I just have to get comfortable enough with Docker, than I might
give it a try.

**Comment by sebgie** [comment]
@mastoj if you are interested you can look at these 3rd party resources for setting up ghost with docker:
- https://allaboutghost.com/deploying-ghost-with-docker/
- https://registry.hub.docker.com/_/ghost/

**Comment by darklow** [comment]
For dokku: http://lightweight.no/ghost-deployed-with-dokku/

**Comment by Ferrari** [comment]
> https://allaboutghost.com/deploying-ghost-with-docker/
> https://registry.hub.docker.com/_/ghost/
> For dokku: http://lightweight.no/ghost-deployed-with-dokku/

Is there a new way to do these after Ghost 1.0? It's too hard to do customize install under ghost-cli. Can we do this with Docker or just install core only?

**Comment by AileenCGN** [comment]
Hey @Ferrari! We're using GitHub strictly for bug reports. If you have a question, please swing by to our [slack community](https://slack.ghost.org) where you can find many users with maybe similar questions and get help way faster and better.
