### ISSUE TITLE
User Onboarding - Invite users

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#5338]
This is required as part of the User Onboarding epic: #5315 

----

Screen 3 of the new onboarding flow (see PR #5316) has a text area for listing out email addresses of users you want to invite to your blog. This screen is currently accessible by clicking the '3' icon at the top of the screen - if you submit the form on the 2nd page you will miss this screen!

![](http://puu.sh/hXFht.png)

The emails are split up and basically validated at present, but there is no handling of displaying errors, or actually inviting the users. This can all be handled in the client side, but it may be preferable to update the API to be able to do multiple user invites in one go, and return success/failures for each address individually. 

Prior to submission, any validation issues should appear on the form page - using the new red text under the field style shown [here](https://github.com/TryGhost/Ghost/issues/5336) to indicate if any of the addresses are invalid emails.

After submission, the user should be logged in and success or failure should be indicated by a normal notification. Clicking on that notification should take you to the team page so you can review the invites.

**Comment by ErisDS** [comment]
Not 100% sure on whether the multiple invites should be handled client or server side here. It wouldn't be an enormous task to make the API endpoint support multiple creates, but that would make it different to all of the other `POST` endpoints.

Also it seems like it might be just creating a nice API endpoint for sending tonnes of spam invites. Handling the multiple invites on the client doesn't make that much of a difference in that regard, but this screen is a one-time accessible thing. I'm tempted to say leave it client side until there's a clear reason to move it.

**Comment by josephwegner** [comment]
I'll pick this up. I'll leave it on the client side for now, and if we have other use cases for a multi-user invite API, we can rethink this.

**Comment by josephwegner** [comment]
Unless someone has a better idea, for now I'm going to use the old error system, for validation errors. That will have to be reconsidered once #5336 gets done.

**Comment by ErisDS** [comment]
That sounds totally sane ;)
