### ISSUE TITLE
Some helpers are broken if used in {{#next_post}} & {{#prev_post}}

### ISSUE THREAD

**Issue by msiemens** [TryGhost/Ghost#5346]
Let's say I use this code in my theme:

```html
{{#next_post}}
<div class="left">
    <div class="read-next-label">Next Article</div>
    <h3 class="read-next-title"><a href="{{url}}">{{tags suffix=":"}} {{meta_title}}</a></h3>
</div>
{{/next_post}}
```

The result of the `tags` helper is always empty and the result of `meta_title` is the title of the blog, not of the post. I suspect that nested helpers somehow get a wrong context. It seems like the `url` and `image` helpers work because they use `config.urlFor` to fetch their data, but I haven't investiaged this further yet.

**Comment by ErisDS** [comment]
Hi @msiemens, thanks for the report. This bug is already tracked [here](https://github.com/TryGhost/Ghost/issues/5150 (I've updated the title to make that clearer).
