### ISSUE TITLE
Using custom data in post context

### ISSUE THREAD

**Issue by gowthamgts** [TryGhost/Ghost#5352]
Hello, I'm planning for migrating my blog in Jekyll to Ghost and I am wondering how can I add custom metadata to each post and render it with a format like `{{content.my_custom_data}}`. In Jekyll, I can do that via `{{page.my_custom_data}}`. So, how can I do that in Ghost, may be with Handlerbars?

**Comment by ErisDS** [comment]
Hi there @gowthamgts, it's great to hear you want to switch. We ask that you please do not use GitHub for questions and support - this where we keep track of issues and bugs in the software. We have a [slack](https://ghost.org/slack) community or alternatively you can always use [stackoverflow](http://stackoverflow.com/questions/tagged/ghost-blog) when you need help.

**Comment by gowthamgts** [comment]
@ErisDS Thanks I don't know about slack. I asked in SO but I didn't got any attention, so I came here. Thanks.
