### ISSUE TITLE
Improve Ghost's startup checks & diagnostics

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#5358]
Ghost has a number of checks that it performs when starting up to try to give useful and clear information about what is going wrong if Ghost fails to boot up properly. Here's an example:

![](http://puu.sh/i3GLJ.png)

Overtime some of those checks have been moved around and refactored so that they don't always fire at the most useful time. Meanwhile some other checks have made their way to our really nifty `/core/utils/startup-checks.js` file, which happens before absolutely anything else.

Here are some examples:

- There is a node version check in [core/server/ghost-server.js](https://github.com/TryGhost/Ghost/blob/f26179ae6a26e277d5dd3a5b9538b1c89f1254e8/core/server/ghost-server.js#L49), which happens way too late to be really useful. This can be moved into `startup-check.js`.

- There is an upgrade warning message in the same [ghost-server.js](https://github.com/TryGhost/Ghost/blob/f26179ae6a26e277d5dd3a5b9538b1c89f1254e8/core/server/ghost-server.js#L108) file which can now be removed.

- There is a whole bunch of validation which happens inside of [core/server/config/index.js](https://github.com/TryGhost/Ghost/blob/f26179ae6a26e277d5dd3a5b9538b1c89f1254e8/core/server/config/index.js#L344), but none of this seems to fire. For example if you try `NODE_ENV=rubbish npm start` you ought to get a clear message `Cannot find the configuration for the current NODE_ENV`, but instead nothing is output. 

   The NODE_ENV check can be moved into `startup-check.js` with the following logic: if the config.js file can't be found (because Ghost hasn't been started before) assume we're going to use config.example.js, in which case the NODE_ENV must be one of those referenced in that file.

The result of this should be that startup performs the following checks:
- node version is supported
- NODE_ENV can be understood
- npm packages are installed
- content path can be accessed and has the correct permissions
- sqlite3 database has correct permissions if it is configured

From this point:
- the config system will correctly validate that the config file can be read, and has valid values.
- GhostServer will do checks around it being possible to start a server

**Comment by kowsheek** [comment]
These checks seem to be there already in `startup-check.js`, is there anything else we'd like to add to these checks?

* npm packages are installed
* content path can be accessed and has the correct permissions
* sqlite3 database has correct permissions if it is configured

**Comment by jomahoney** [comment]
@kowsheek Working on this at the moment, I think Hannah was more outlining the file should do those things when complete, perhaps in that order. I can stand to be corrected.
