### ISSUE TITLE
Bug: Login Field CSS Broken

### ISSUE THREAD

**Issue by josephyoon** [TryGhost/Ghost#5363]
![screen shot 2015-05-29 at 17 53 37](https://cloud.githubusercontent.com/assets/7097891/7886675/f4a1ad30-062b-11e5-871d-307045f4e879.png)
The login buttens are misaligned suddenly. It used to be in one line. Please fix this issue.

**Comment by novaugust** [comment]
Thanks for the report Josephyoon, this has already been fixed in master as we've completely redone the login interface
