### ISSUE TITLE
[themes] "has" helper confused by ampersand in tag name

### ISSUE THREAD

**Issue by k-j-kleist** [TryGhost/Ghost#5369]
Just overheard in the #help slack channel (haven't verified this myself):

> roxana [02:21] 
> looking for some help with the `{{#has}}` helper. i’m trying to target posts that have the tag _products & design_ but the helper isn’t letting me. can this be used with tags that include more than one word and an ampersand?
> roxana [03:05] 
> nvm it seems like i can’t use the ampersand. i replaced it with a `+` and everything works well

**Comment by k-j-kleist** [comment]
see also https://github.com/TryGhost/Ghost/issues/2115#issuecomment-34713964

**Comment by ErisDS** [comment]
Had no interest in this in 2 years, closing.
