### ISSUE TITLE
Add events to settings model

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#5370]
A little while back, I did a PR which added events to the post, tag and user models, and used these for generating sitemaps, rather than direct method calls.

See the changes here: https://github.com/TryGhost/Ghost/pull/5069/files#diff-e05bf798b07f40dd2e22a828f86eee13R10

It would be great to also wire up these sorts of events whenever a setting is added, edited or deleted. 

The tag model is probably the [best example](https://github.com/TryGhost/Ghost/blob/master/core/server/models/tag.js#L25) to follow on from. 

Events are included from the centralised event system, a new `emitChange` method is added to the model, and the events are wired up to be fired when the model's events from bookshelf fire.

Finally, there'll need to be [some tests](https://github.com/TryGhost/Ghost/pull/5069/files#diff-f588c5c6615f7ef7a9b2876d55e59f93R31) in the settings model tests to check that the events fire at the right times :)

**Comment by kowsheek** [comment]
I'm taking a stab at this.

Further to knowing that some setting was changed, do we care which setting (by Key maybe)? Or we want to keep simple it like the tag model?

**Comment by ErisDS** [comment]
@kowsheek I think it would be good to throw a general updated event and one which includes the key name. That way we could subscribe to things like `activeTheme.updated`.

**Comment by kowsheek** [comment]
I'll be adding the key-based events soon @ErisDS.

**Comment by halfdan** [comment]
This can be closed. PR by @kowsheek is merged.

**Comment by ErisDS** [comment]
It's not finished - there are still named events to add ;)

**Comment by ErisDS** [comment]
Also I believe from the comment on the original PR that @kowsheek plans to come back and finish that off.
