### ISSUE TITLE
API: add support for GET `/tags/slug/:slug/`

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#5371]
Both Posts and Users support getting a resource by the slug. This endpoint is missing for tags!

The endpoint should be added to the [api routes](https://github.com/TryGhost/Ghost/blob/master/core/server/routes/api.js#L19), support should be added to the tag model (it seems it's added at the API level) by ensuring that the option can be passed through and gets used by bookshelf to select the right thing.

It should also be tested both at the [model](https://github.com/TryGhost/Ghost/blob/master/core/test/integration/model/model_posts_spec.js#L259) and [api](https://github.com/TryGhost/Ghost/blob/master/core/test/integration/api/api_posts_spec.js#L41) level to make sure it's definitely working.

The result should be that doing an HTTP Get request to `/tags/slug/:slug/` or doing a call to `api.tags.read({slug: ':slug'}) should return the single tag that matches the slug.

**Comment by augbog** [comment]
I would like to try and take on this task. Just clarifying, the tests for the model and api level should be written in the `api_tags_spec.js` and `model_tags_spec.js` correct?

**Comment by ErisDS** [comment]
Correct!
