### ISSUE TITLE
Fastclick library for better mobile support

### ISSUE THREAD

**Issue by jaswilli** [TryGhost/Ghost#5375]
During the transition from Backbone to Ember, the fastclick library was never brought back into the app.  It's still a dependency (https://github.com/TryGhost/Ghost/blob/master/core/client/bower.json#L12), so this issue just covers bringing it back into the fold so it's run as a part of the Ember admin app, which in all likelihood just involves the bootstrap index.html file (but bonus points for researching the best way to integrate it).

**Comment by acburdine** [comment]
There's this library that seems like it would work: https://github.com/ember-mobile/ember-cli-fastclick
