### ISSUE TITLE
/admin redirect to /ghost is volatile

### ISSUE THREAD

**Issue by Swaagie** [TryGhost/Ghost#5393]
Using a custom `/blog` route. Set up like this:

```js
//
// Run ghost blog under /blog path.
//
require('ghost')({
  config: path.join(__dirname, 'ghost.js')
}).then(function (blog) {
  blog.config.paths.subdir = '/blog';

  app.use(blog.config.paths.subdir, blog.rootApp);
  blog.start(app);
})
```

Hitting `/blog/admin` will redirect to `/ghost` however in stead of `/blog/ghost`. In addition other paths (assets etc) seem to be scrambled in the process. It seems the references to the original config object are destroyed when that faulty redirect happens. If I missed something in the configuration, please let me know :)

**Comment by ErisDS** [comment]
Hi @Swaagie, this looks like a mis-configuration to me. As shown in the [example](https://github.com/TryGhost/Ghost/wiki/Using-Ghost-as-an-NPM-module#mount-ghost-on-a-subdirectory) there's no need to set the subdir directly, this is generated for you from the `url` setting in config.js.

As long as your URL is configured correctly, you should find it all works exactly as expected.

**Comment by Swaagie** [comment]
I'll try setting that route directly in the config

**Comment by Swaagie** [comment]
I'm still concerned by the fact that an arbitrary redirect can somehow alter the already configured paths, even though this might only be a side-effect of the direct config edit.

**Comment by ErisDS** [comment]
`subdir` is a computed property, which is updated from config.url, rather than a config option that can be set. Also if you want to set a config option after you've initialised Ghost, you need to use the `.set()` method. I think those two things combined explain the behaviour you were seeing?

**Comment by Swaagie** [comment]
Now directly included the subdir in the config and now it is not working anymore, e.g. 

```
{
  production: {
    paths: {
      subdir: '/blog'
 ....
}
```

Should it be configured differently? I can try `set` in stead of the direct appointing I did earlier

**Comment by Swaagie** [comment]
As far as `set` goes, it's not really clear from the docs. Alternatively seems to suggest any valid string is ok, so would `app.use('/blog', blog.rootApp);` work?


```
ghostServer.config.paths.subdir contains the subdirectory specified via the URL in config.js 
alternatively you can pass in any valid path string.
```

**Comment by Swaagie** [comment]
None of the things i've suggested so far is even working, that was why I opted to use the direct appointing iirc

**Comment by Swaagie** [comment]
Ok, got it working after a code-dive, from `.config.set` I derived it is simply extracted from the `url` property of the config. It extracts the path from the url, improving the wiki and remove the config leak would be 2 good improvements.

**Comment by Swaagie** [comment]
Ow lol sorry I just see you also mentioned `subdir` being computed from `config.url`

**Comment by ErisDS** [comment]
The wiki is open - you can edit it however you think it would be clearer - I obviously didn't do a good job :wink:

The line you copied:

> ghostServer.config.paths.subdir contains the subdirectory specified via the URL in config.js 
alternatively you can pass in any valid path string.

is also intending to explain that `subdir` comes from `url`. You don't ever need to set the `path.subdir` property directly, you set the URL property. This is the same as a standard install of Ghost, and is why `url` is documented in http://support.ghost.org/config and `subdir` isn't. 

Please do improve the documentation - that's why it's still on the wiki :+1:

**Comment by Swaagie** [comment]
Sure, your totally right, it's open source after all. I'll try to see if I can chip in some effort this afternoon

**Comment by Swaagie** [comment]
Made a small change, https://github.com/TryGhost/Ghost/wiki/Using-Ghost-as-an-NPM-module/_history replacing the `alternatively` with an example

**Comment by ErisDS** [comment]
Awesome, thanks :+1:
