### ISSUE TITLE
Startup bookshelp-knex failure

### ISSUE THREAD

**Issue by anlawande** [TryGhost/Ghost#5396]
Get the following error when starting up for the first time

```script
ERROR: Cannot read property 'VERSION' of undefined
```

The line which it originated from  
Bookshelf.initialize (d:\Workspace\node\ghost-0.6.4\node_modules\bookshelf\bookshelf.js:45:29)
```javascript
 if (!semver.satisfies(knex.VERSION, range)) {
```

**Comment by ErisDS** [comment]
Hi @anlawande, sorry to see you're having trouble. GitHub is our issue tracker for the software. Please use either [slack](https://ghost.org/slack) or if you prefer [stackoverflow](http://stackoverflow.com/questions/tagged/ghost-blog) to get support with your install.
