### ISSUE TITLE
Vertical scrolling in the backend settings doesn't work anymore

### ISSUE THREAD

**Issue by bulletinmybeard** [TryGhost/Ghost#5401]
Hey guys,

since I pulled the latest master update, the vertical scrolling in the backend settings doesn't work anymore. Maybe it's the nested flexbox which is responsible for that.

## Hotfix ##
Use a browser extension to delete in the `.gh-app` css class the attribute **overflow: hidden;** or rewrite it with **overflow: scroll;**

## Additional Information ##
OS: Debian Wheezy Linux version 7.8
Browser (64bit): Latest Chrome Canary, Firefox (stable) and Opera (stable)
Node Version: 0.12.2
Ghost Build Number: 0.6.4

**Comment by acburdine** [comment]
I can confirm this happens on Firefox.

**Comment by ErisDS** [comment]
Just to quickly clarify, this is a Zelda (redesign in latest master) issue, not a bug in the released 0.6.4.

**Comment by josephwegner** [comment]
boo. It works in Chrome :(

I'll pick this up.

**Comment by josephwegner** [comment]
ack - seems like there might be a lot of flexbox weirdness... The sidebar footer is gone in Firefox as well.
