### ISSUE TITLE
A too long blog title overlap the right content field in the backend

### ISSUE THREAD

**Issue by bulletinmybeard** [TryGhost/Ghost#5402]
For the blog details in backend you're using `white-space: nowrap;`. I would recommend to wrap longer text parts because it looks better for my opinion.

![](https://rschu.me//1-nowrap.png)

![](https://rschu.me//2-nowrap.png)

## Additional Information ##
OS: Debian Wheezy Linux version 7.8
Browser (64bit): Latest Chrome Canary, Firefox (stable) and Opera (stable)
Node Version: 0.12.2
Ghost Build Number: 0.6.4

**Comment by jasonblancas** [comment]
Is this something that can be worked on? Looking to get my feet wet.

**Comment by JohnONolan** [comment]
This has been resolved

**Comment by jabs83** [comment]
yeah, i deleted my comment when i realized the related PR. thanks.
