### ISSUE TITLE
Notifications Refactor

### ISSUE THREAD

**Issue by JohnONolan** [TryGhost/Ghost#5409]
Pre-Zelda Ghost had one type of notification, and two locations (top and bottom).
- **Top notifications** were a coloured bar across the top of the screen
- **Bottom notifications** were a coloured bubble in the bottom left hand corner of the screen

In Zelda these components have been renamed to Alerts and Notifications.
- **Alerts** are a coloured bar across the top of the screen
- **Notifications** are a coloured bubble in the bottom left hand corner of the screen

While the use of top/bottom notifications was fairly arbitrary (based on loosely priority), the use of alerts/notifications is far more explicit.
- **Alerts** are for errors, and important show-stopping information which the user needs to be aware of permanently until it is either resolved or dismissed.
- **Notifications** are passive indications that something has happened, and always have an _action_ which takes you to view what has happened.
### Test Cases
- If the user cannot do anything until the event is resolved: It should be an alert
- If the information affects security/privacy/stability: It should be an alert
- If something has happened and has a "view this" action leading to a different screen: It should be a notification
- If something has happened and has NO action: It should not be anything
### Examples
- Connection error: Alert
- Your mail config is whacked out: Alert
- New version of Ghost: Alert
- Post published: Notification _(Click to view post)_
- User signed up: Notification _(Click to view user)_
- Settings saved: Nothing
- Tag added: Nothing
- Post featured: Nothing
## Required Changes
1. Existing alerts (previous top-notifications) are mostly correct. I don't think any need to change.
2. Errors (previously bottom-notifications) need to move to alerts
3. Generic success messages (previously bottom-notifications) need to die
4. Validation messages (previously bottom-notifications) need to be inline where possible, otherwise alerts
5. Any messages which don't fall into the above categories should be documented

**Comment by acburdine** [comment]
@JohnONolan There also needs to be different color support added back in. When I re-did the notifications code back in the Zelda PR, I didn't add the different colors back in because I wasn't sure which mapped to which (e.g. 'success' -> 'green', 'error' -> 'red'). It might be helpful to have something in the spec that shows which old colors (success, error, info) map to the new ones (green, red, blue).

Also, the old notifications had a "passive" aspect which allowed them to disappear after a certain time. Is that going away?

Lastly, I will probably take care of the moving to inline-errors in #5399 or a subsequent pr associated with #5336, so IMO doing that shouldn't be part of this spec.

Sidenote: I'm not necessarily taking this on, so anyone feel free to do it :smile: Just wanted to clarify a couple of spec things.

**Comment by JohnONolan** [comment]
> There also needs to be different color support added back in.

There already is colour support, but it's probably going to go away.

> Also, the old notifications had a "passive" aspect which allowed them to disappear after a certain time. Is that going away?

Definitely not, should be exactly the same as before

**Comment by kevinansfield** [comment]
>> Also, the old notifications had a "passive" aspect which allowed them to disappear after a certain time. Is that going away?

> Definitely not, should be exactly the same as before

By "disappear after a certain time" is it meant that the previous passive notifications would disappear after a set time of being on-screen or that they would disappear when another action occurs such as a transition?

**Comment by kevinansfield** [comment]
Does it make sense to change the `persistent`/`passive` statuses to `alert`/`notification` to keep naming consistent or is it preferable to stick with the current naming?

**Comment by ErisDS** [comment]
> By "disappear after a certain time" is it meant that the previous passive notifications would disappear after a set time of being on-screen or that they would disappear when another action occurs such as a transition?

The old 'passive' notifications disappeared on the next action or transition, unless they were 'success' notifications in which case they faded out after 5 seconds or disappeared on the next action/transition depending on what happened first.

I think it makes a lot of sense to change the naming now as we're no longer conflating lots of concepts together.

**Comment by JohnONolan** [comment]
To be clear:

All notifications should stay for 5 seconds, then fade out, unless they are hovered, in which case the timer is reset. This is roughly the same as how facebook notifications work (for reference) and the same as we had this working before.

Alerts should always be visible until manually dismissed, or programmatically resolved. Eg. Clicking on the "x" or fixing an error in a form submission.

**Comment by kevinansfield** [comment]
> There already is colour support, but it's probably going to go away.

In the CSS we currently have the following...

Notifications:
* red
* green

Alerts:
* red
* green
* blue
* black
* yellow

In the client notifications code we currently have the following types in use (but colours aren't working in the UI as @acburdine pointed out):

* success
* error
* warn

Which colours do you want to map to different types? Or.. if colour support is going away shall we just have notifications == green and alerts == blue as they are at the moment?

**Comment by JohnONolan** [comment]
Notifications should have no colours by default. I would totally ignore the additional available CSS classes here. All notifications should just have the default styling except under exceptional circumstances (none of which exist in core right now)

Alerts should have access to all colours depending on the context:

Success => Green
Error => Red
Warn => Yellow

**Comment by kevinansfield** [comment]
> Settings saved: Nothing

Testing this after removing the 'Settings successfully saved' notification it jumps out that there's no indication that anything actually happens when clicking save.

http://g.recordit.co/mE7dPbelbl.gif

Are we switching to some other method to indicate a save action has completed?

**Comment by ErisDS** [comment]
I believe the main thing left to do here is to add actions/destinations to certain success notifications?

If that's true, and we're happy with this for now, is it ok if I move this into a 'Post-Zelda' milestone? cc @JohnONolan

**Comment by JohnONolan** [comment]
yup

**Comment by kevinansfield** [comment]
There has been quite a bit of work done on the notifications/alerts, I think from this point it will be easier to open a new issue when we have a concrete example of something that needs fixing or implementing.
