### ISSUE TITLE
Zelda mobile nav fixup

### ISSUE THREAD

**Issue by JohnONolan** [TryGhost/Ghost#5410]
New mobile nav styles went in #5368 -- this is pretty broken right now and needs some love.

There are 3 states that the main nav menu can be in:

1. Desktop: Expanded
2. Desktop: Collapsed
3. Mobile: Collapsed

## 1. Desktop Expanded

![image](https://cloud.githubusercontent.com/assets/120485/8056625/f22793de-0ea1-11e5-808b-a859c16592a6.png)

This is the default navigation state. No special notes. It works.

## 2. Desktop Collapsed

![image](https://cloud.githubusercontent.com/assets/120485/8056644/205c75f8-0ea2-11e5-9dcd-ed6de2ff3383.png)

The navigation can also be collapsed for more space. 

When in a collapsed state, the navigation menu opens when the mouse enters the nav-menu area, and closes when the mouse enters the gh-main area. It works deliberately this way (rather than on :hover) so that the action of opening and closing the menu is less error-prone when the cursor moves around.

This is currently working exactly as expected in master.

## 3. Mobile Collapsed

![image](https://cloud.githubusercontent.com/assets/120485/8056787/7367ebc8-0ea3-11e5-89b8-c81794c68be0.png)

When the viewport is 800px wide or smaller, the navigation menu disappears entirely. A Ghost logo is injected into the current page title, which can be tapped/clicked to open the menu.

The mobile menu open/close should function exactly like the PSM. Slides *over* content, tap/click anywhere outside it to close.

This whole thing is super broken in master.

## Changes Needed

- [ ] Ghost should remember (localstorage?) whether desktop menu is expanded or collapsed
- [ ] Mobilemenu button is missing from `content` and `editor` views
- [ ] Mobilemenu pane slides entire content over, should expand over-top-of-content
- [ ] Mobilemenu can't be closed
- [ ] There is weird behaviour with mobile menu when changing from big=>small=>big viewport sizes where sometimes it can't be opened or closed. Or the Desktop:collapsed state gets stuck-open.

(incomplete list)

**Comment by novaugust** [comment]
Closed by #5414
