### ISSUE TITLE
`Error: SQLITE_BUSY: database is locked` in importer tests

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#5411]
On node 0.12 & io.js 1.2 (but not node 0.10) we're regularly seeing this error occurring during the importer integration tests. It happens something like 2 times in 3 on the SQLite builds. After switching my local dev environment to 0.12.4, I can reproduce it fairly regularly, although adding a bunch of console logs seemed\* to make it less reproducible.

I've spent some time trying to track down what's going on. It's tricky because although it definitely points to something to do with sqlite3 on recent node versions, it could still be that this version of sqlite3 is more susceptible to (or better at reporting errors with) timing/async issues caused by the tests doing lots of things very fast. Plus many of our test-related dependencies have been updated recently and could have caused some sort of conflict.

It seems to mostly get thrown during the `safely imports data from 00X` tests - that is the first test in each group. From doing a bit of console logging, it seems to get through the import and commit the results, and then get tripped up by the select block:

```
return Promise.all([
   knex('users').select(),
   knex('posts').select(),
   knex('settings').select(),
   knex('tags').select()
 ]);
```

Only .map and .filter have `concurrency` as an option, but it may be worth trying to refactor to run the promises to use our sequence util and see if that helps. I tried wrapping each select in a function just to add a console log to see if it was one specific thing - and again adding the console logs seemed\* to reduce the frequency of the failures.

The real issue is that I'm not even sure where the error is coming from. Ideally we should be handling it properly by waiting for SQLite to not be busy and then sending the queries? I'm not sure whether this should be handled in node-sqlite, or knex, or whether we ought to be doing something with it... it's all a bit strange.

\* I ran the tests many times without seeing an error.

**Comment by josephwegner** [comment]
Here's a link to to a build that failed with that error: https://travis-ci.org/TryGhost/Ghost/jobs/66796180

**Comment by ErisDS** [comment]
Note: I also commented on a similar issue on mapbox/sqlite3 in bare desperation: https://github.com/mapbox/node-sqlite3/issues/372#issuecomment-110297818
