### ISSUE TITLE
Zelda settings routes don't redirect to signin

### ISSUE THREAD

**Issue by novaugust** [TryGhost/Ghost#5412]
## Issue Summary

Going to `/settings/general` without being logged in shows a 401 error, rather than redirecting to `/signin`. The redirect works correctly for the posts route (`/`)

## Repro

1. Sign out
2. Navigate to `/ghost/settings/general`
3. See 401

## Specs

- Latest master (3f9560f11f186d585ab613ee1c2c92b506ad9858)
- Chrome 43.0

**Comment by lukaszklis** [comment]
I can try to take care of this if no one is working on it at the moment.

**Comment by novaugust** [comment]
It's yours :+1: Hit us up in [slack](http://ghost.org/slack) if you run into any problems
