### ISSUE TITLE
Ubuntu 15.04

### ISSUE THREAD

**Issue by di48l069** [TryGhost/Ghost#5413]
Hi, Can ghost run on Ubuntu 15.04

**Comment by novaugust** [comment]
Hey @di48l069, this is something better asked on our [slack](https://ghost.org/slack/) channel or perhaps on stackoverflow. We use Github for tracking feature implementation and bugs, not so much for support
But the answer is yes :)

**Comment by di48l069** [comment]
Sorry about that @novaugust  Thanks thou :+1:
