### ISSUE TITLE
Add both cyrillic and latin Open Sans to Ghost

### ISSUE THREAD

**Issue by alexbagirov** [TryGhost/Ghost#5439]

**Comment by ErisDS** [comment]
Just going to close this as there's no description. Best thing would be to vote for this on [the wishlist](http://ideas.ghost.org/forums/285309-wishlist/suggestions/7413160-fonts-in-admin-panel-should-have-support-for-more).

**Comment by alexbagirov** [comment]
I was talking about font that is added from Google Fonts. It seems to support only latin. What about adding cyrrilic?
