### ISSUE TITLE
Persist nav menu state between sessions

### ISSUE THREAD

**Issue by novaugust** [TryGhost/Ghost#5440]
Add a feature that tracks user preferences with the menu (open or in autonav) between sessions via localstorage.

Essentially, stop this from happening

![autonav](https://cloud.githubusercontent.com/assets/1207005/12272337/38c9bd50-b91d-11e5-8119-424e8dfb1ad3.gif)

**Comment by novaugust** [comment]
relevant repo: stefanpenner/ember-state-service

**Comment by halfdan** [comment]
@novaugust Actually not that simple since we can have different users logged in on the same computer/browser. Not sure how ember-state-services helps as it doesn't persist state between reloads - it simply creates a private state.

**Comment by novaugust** [comment]
> Actually not that simple since we can have different users logged in on the same computer/browser. Not sure how ember-state-services helps as it doesn't persist state between reloads - it simply creates a private state.

I'm not sure how it helps either. That was half a year ago! Everything was different! Stop pointing fingers at me!

Yeah, it seems like the PR to this would be the slow transition into more offline stuff. I think it would be reasonable to use user-based keys for the localstorage info, kind of like how you added that localstorage based on subdir for the different-blog problem you solved just recently (#6327)

**Comment by novaugust** [comment]
Who knows, somewhere down the line, this same localstorage could be used to do offline editing ;)

**Comment by halfdan** [comment]
@novaugust The issue I see here is that it leaks user information - for now just a preference, but with an offline mode this might leak unpublished post content. Anyway, I'll try to come up with a solution.

**Comment by novaugust** [comment]
> for now just a preference, but with an offline mode this might leak unpublished post content.

Ah well, just solve the "now" issue for now eh ;)

**Comment by ErisDS** [comment]
Don't think I've ever seen anyone ask for this or complain about it? Closing for now and we can revisit when we have more stateful things to keep track of?
