### ISSUE TITLE
RSS 404?

### ISSUE THREAD

**Issue by brunocascio** [TryGhost/Ghost#5443]
Hi!

I see this code:

```
// No negative pages, or page 1
    if (isNaN(pageParam) || pageParam < 1 || (req.params.page !== undefined && pageParam === 1)) {
        return res.redirect(baseUrl);
    }
```

and

```
 // If page is greater than number of pages we have, redirect to last page
        if (pageParam > maxPage) {
            return res.redirect(baseUrl + maxPage + '/');
        }
```

It would be better to throw a 404 error?

I trying to paginate rss results, but if always return to last page, i can't do it.

Can I add a pull request?

**Comment by ErisDS** [comment]
Hi @brunocascio, I'm sorry but I don't follow what you're doing here at all. Ghost's RSS feeds are paginated already. Perhaps it would be easier to drop by our [slack](https://ghost.org/slack) channel and chat about what's going on?

**Comment by brunocascio** [comment]
I have e.g 20 blog posts, so i have 2 pages. If url is `/rss/3` the server must respond 404 don't a redirect to last page of rss.

**Comment by sebgie** [comment]
`/rss` has the same behaviour as posts. If you choose a page number that doesn’t exist it sends you to the highest existing page.

Example:
If you have 3 pages in your RSS feed and go to `/rss/30/` it’ll send you back to `/rss/3/`.
If you only have 1 page it'll always send you back to `/rss/`

I think you are looking for something like previous/next links in the rss feed but I don't know if this is supported or wanted.

**Comment by brunocascio** [comment]
Yes @sebgie, pagination links. Will be implemented?

**Comment by ErisDS** [comment]
The currently plan is to kill RSS pagination after the API is made publicly available.

**Comment by brunocascio** [comment]
ok, thanks!
