### ISSUE TITLE
Bug: corrections erase by cache ?

### ISSUE THREAD

**Issue by toblerone1963** [TryGhost/Ghost#5450]
### Issue Summary
Hello, we are three journalists using Ghost for our blog. We correct each other papers, but some times our corrections are erase by cache, if another writer don't reload the Content page before clicking the edit button. (sorry, bad english)

### Steps to Reproduce

1. Joe writes an article and goes to Content.

2. On another computer, Bob opens that article and makes some corrections (save and quit).

3. Joe doesn't reload Content and just click on Edit. => Bob's corrections are gone

This is a bug because… well, Ajax is great, but if many people edit a post, we gonna lost many corrections.

### Technical details

* Ghost Version: 0.6.4
* Client OS: Mac OS X, Debian Jessie
* Server OS: not sure, some Linux I think. it's a simple host on Gandi
* Node Version: 0.10
* Database: mongoDB

**Comment by ErisDS** [comment]
Hi @toblerone1963, thanks for the detailed bug report. 

I *think* that we need to be reloading the post in the edit route? Ember Data has a reload method, I tried it very quickly but it didn't seem to have the desired impact. Still I think it does make sense to implement some sort of force refresh on the edit route.

**Comment by ErisDS** [comment]
Clever stuff on how to fix this from @jaswilli: https://ghost.slack.com/archives/ghost/p1434644483003699
