### ISSUE TITLE
Grunt init results in unterminated string constant error

### ISSUE THREAD

**Issue by jomahoney** [TryGhost/Ghost#5454]
### Issue Summary

Running `grunt init` in windows 8 with node version 0.12.4 results in an error and the command aborts.

Error:
```
Build failed.
File: ghost/templates/setup/three
Unterminated string constant (140:105)
SyntaxError: Unterminated string constant (140:105)
    at Parser.pp.raise (C:\Users\john\Code\Ghost\core\client\node_modules\ember-cli\node_modules\broccoli-es6modules\node_modules\esperanto\node_modules\acorn\dist\acorn.js:1745:13)
    ...
Warning: Command failed: C:\Windows\system32\cmd.exe /s /c "C:\Users\john\Code\Ghost\core\client\node_modules\.bin\ember build"
 Use --force to continue.

Aborted due to warnings.
```

### Steps to Reproduce

1. `npm install` (should pass successfully)
2. `grunt init`
3. See failure in all its glory

### Technical details:

* Ghost Version: master
* Client OS: Windows 8.1
* Node Version: 0.12.4

**Comment by novaugust** [comment]
regarding the repro, this seems to be specific to windows builds. I have seen a few other people bring it up in slack as well

**Comment by jomahoney** [comment]
@novaugust I figured as much. If this was happening on OSX and *nix builds I think there would've been more commotion.

Changing it to just one user no longer demos the functionality but it does remain written that you can add multiple users so we ok with that fix?
