### ISSUE TITLE
User Profile > Edit Picture stuck on loadingcat.gif

### ISSUE THREAD

**Issue by arvoim** [TryGhost/Ghost#5460]
Just installed a fresh 0.6.4 on a server that also has a working 0.5.10

When I go to update my profile picture on the 0.6.4 version, it seemingly uploads fine (I see the progress bar fill) but then I see a loadingcat.gif that never goes away so I can not save my profile image. I do not have this issue on 0.5.10

Looking deeper, I am having this issue while writing/editing a post as well.

Am I forgetting a folder permission somewhere?

Apologies if this was already brought up, I'm not too familiar with github.

**Comment by ErisDS** [comment]
Hi @arvoim, this sounds like a problem with your setup - why not come chat to us in [slack](https://ghost.org/slack) or if you prefer post on [stackoverflow](http://stackoverflow.com/questions/tagged/ghost-blog). GitHub is for tracking issues with the software.
