### ISSUE TITLE
BUG: Lost Tags on Modification

### ISSUE THREAD

**Issue by FaSan** [TryGhost/Ghost#5461]
Hello,
when I going to modify an article, or only simple add a "feature" with click on the star, not always, but usually, the article lost the tags. I must to re-add manually.

I use ghost 0.6.4 with mysql db and nodejs v. 0.12.x

Thank you in advance

FaSan

**Comment by FaSan** [comment]
I tried now with  a clean DB and one article and issue not happen. I've DB coming from the version 6.2 and count many articles.

**Comment by ErisDS** [comment]
Hi @FaSan, thanks for the bug report! I know this is a particularly annoying bug - it is already being tracked in #4999, which is being fixed in master.

**Comment by lomza** [comment]
Thanks a lot, @ErisDS ! I was experiencing this bug now and then, and was going to report it, but then saw this topic. Great job ;)
