### ISSUE TITLE
Install Error:unexpected eof

### ISSUE THREAD

**Issue by CDog34** [TryGhost/Ghost#5462]
I got some troubles when I run `npm install -production`.
 Here is the Output:
```
npm ERR! tar.unpack untar error /tmp/npm-1734-420cb1ad/registry.npmjs.org/mocha/-/mocha-2.2.5.tgz
npm ERR! tar.unpack untar error /tmp/npm-1734-420cb1ad/registry.npmjs.org/bluebird/-/bluebird-2.9.25.tgz
npm ERR! tar.unpack untar error /tmp/npm-1734-420cb1ad/registry.npmjs.org/extract-zip/-/extract-zip-1.0.3.tgz
npm ERR! tar.unpack untar error /tmp/npm-1734-420cb1ad/registry.npmjs.org/sqlite3/-/sqlite3-3.0.8.tgz
npm ERR! tar.unpack untar error /tmp/npm-1734-420cb1ad/registry.npmjs.org/bookshelf/-/bookshelf-0.7.9.tgz
npm ERR! tar.unpack untar error /tmp/npm-1734-420cb1ad/registry.npmjs.org/istanbul/-/istanbul-0.3.14.tgz
npm ERR! tar.unpack untar error /tmp/npm-1734-420cb1ad/registry.npmjs.org/moment/-/moment-2.10.2.tgz
npm ERR! Linux 3.13.0-32-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-production"
npm ERR! node v0.12.4
npm ERR! npm  v2.10.1

npm ERR! unexpected eof
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /node/npm-debug.log
```
The whole `npm-debug.log` file is here: http://i.just.wanna.test.cdog.me/p/npm-debug.log

And my environment is : 
  * Ubuntu 14.04 x86
  * Node.js 0.12.4
  * npm 2.10.1
  * ghost 0.6.4

I've tried re-download the source code of ghost, but it doesn't work.
and I also tried node.js v.0.10.36 with npm v1.4.28 ,but doesn't work too....

So, what should I do ？

**Comment by ErisDS** [comment]
Hi there @CDog34, we have a [slack](https://ghost.org/slack) community where you can get support in our #help channel. Alternatively if you prefer there is always [stackoverflow](http://stackoverflow.com/questions/tagged/ghost-blog) for asking questions. GitHub is for issues with the software itself.

**Comment by halfdan** [comment]
Apart from what @ErisDS pointed out: The command is `npm install --production` (double dash)
