### ISSUE TITLE
Can't disable the Published Date in the future validation

### ISSUE THREAD

**Issue by julianonunes** [TryGhost/Ghost#5469]
I removed these lines from the post-settings-menu.js file but the validation still occurs. What am I missing?

```javascript
if (newPublishedAt.diff(new Date(), 'h') > 0) {
    errMessage = 'Published Date cannot currently be in the future.';
}
```

**Comment by ErisDS** [comment]
Hi there @julianonunes, it sounds like you didn't re-build the JavaScript. If you have more questions like these, please come and chat to us in our [slack](https://ghost.org/slack) community - GitHub is for tracking issues with the software :octocat:
