### ISSUE TITLE
Unable to delete users or posts despite being admin

### ISSUE THREAD

**Issue by bread-man** [TryGhost/Ghost#5482]
I created a Ghost blog recently, hosted on the my friend's Digitalocean server. When I initially created the blog and logged in, I was unable to remove the default post that comes with it. The error message read: `Your post could not be deleted. Please try again.`. This happened as many times as I tried. So I invited a friend as an admin and asked him to check if he was able to delete it, and he was. I can still make posts and add new users, but cannot remove either of them. 

When I used my friend's account instead to try and delete posts, it again failed to delete both users as well as posts.

Update: I also tried this with my friend's blog (he sent me an invite on my both my emails) and it gave me the same error (on both).

Update 2: I *also* tried to make a new email, had my friend send an invite on said email (on his blog). Made a new draft post: success. Tried to delete post: `Your post could not be deleted. Please try again.`. I also tried it on mobile but to no avail, yet again.

Update 3: I used my Github student pack's Digitalocean code to get myself a droplet and host a new blog on my own server. I created and used the email I used for the first blog. Upon signing in, I tried to remove the default post and bam, same error again.

Update 4: I did another install, this time manually. I got the same error. Upon doing an inspect element in Chrome, under the Console tab, it gives me a 401 and 403 error. When visiting the URL for the 403 error, I got this:

```
{"type":"error","message":"Please Sign In","status":"passive"}
```

Final update: It seems to be something to do with my IP. Upon using a 3G dongle, I was able to successfully delete the post.

**Comment by ErisDS** [comment]
Hi there @bread-man, sorry to hear you've had problems with your environment. If you're ever looking to get support for Ghost you'll find we have an active community over on our [slack](https://ghost.org/slack) channel, but we use GitHub purely as an issue tracker. If you're able to find a bug in Ghost which is causing this, please let us know how to reproduce it, but it sounds like something your ISP or network settings might be blocking.
