### ISSUE TITLE
Make post excerption more flexible

### ISSUE THREAD

**Issue by alexbagirov** [TryGhost/Ghost#5485]
For example, if I ask Ghost to cut first 50 symbols then it will do so. I think that it will be more logical to excerpt 50 +- to the nearest end of the nearest phrase.

Because I, for example, use MailChimp to send emails when it checks my RSS. It takes this excerpted part. If it ends with "," then the last symbol in my letter will be ",". That's not very good.

**Comment by acburdine** [comment]
There's already an issue out for this: #5060.
