### ISSUE TITLE
Group mail-related functionality together

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#5489]
Ghost only sends 4 types of emails at present:

- welcome
- forgotten password
- user invite
- test email

The code used for sending these emails + the templates is currently quite spread out in the codebase.

I recommend doing something like the following:

- [x] moving mail.js to mail/index.js
- [x] moving  the `email-templates` directory into the new `mail` directory
- [ ] reviewing the test coverage and seeing if it can be improved easily.

It would also be nice to (maybe?) move the logic around sending each individual email into the Mail API, e.g. moving the `sendInviteEmail` function from `api/users.js` into `api/mail.js` and doing similar for the welcome and forgotten password emails. Note that this requires changing API calls inside those functions to use the dataProvider directly, otherwise there would be circular dependencies api/mail.js -> api/user.js -> api/mail.js. 

There might be another way to do this, the goal being to reduce complexity in the user and authentication api files, and keep all mail related stuff together.

See also #5350

**Comment by ErisDS** [comment]
The remaining part of this issue is looking to improve test coverage for the mail lib. There are some existing tests which are skipped, and some missing coverage:
![](http://puu.sh/kE5jh.png)

**Comment by damsonn** [comment]
@ErisDS happy to work on the tests, if that is ok ?

**Comment by ErisDS** [comment]
Cool 👍
