### ISSUE TITLE
Add Google authorship support

### ISSUE THREAD

**Issue by blackxored** [TryGhost/Ghost#5494]
https://blog.kissmetrics.com/google-authorship/

**Comment by ErisDS** [comment]
Please see #1994, Google Authorship was discontinued a while ago.

**Comment by blackxored** [comment]
That's right. Thanks for the prompt response!

On Sun, Jun 28, 2015 at 12:56 AM, Hannah Wolfe <notifications@github.com>
wrote:

> Closed #5494 <https://github.com/TryGhost/Ghost/issues/5494>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/TryGhost/Ghost/issues/5494#event-342114391>.
>



-- 
Best Regards,

Adrian Perez
Twitter: @blackxored | Skype: blackxored | Phone: +1 (415) 212-8666
