### ISSUE TITLE
private password is unencrypted

### ISSUE THREAD

**Issue by longcang** [TryGhost/Ghost#5512]
without md5 encryption ?

**Comment by kevinansfield** [comment]
Passwords hare hashed with [bcrypt](https://en.wikipedia.org/wiki/Bcrypt) before being inserted into the database. You can see the implementation in the User model - https://github.com/TryGhost/Ghost/blob/master/core/server/models/user.js#L28

**Comment by longcang** [comment]
I means the settings password.  access  from  http://sample-ghost/private.

**Comment by ErisDS** [comment]
Hi @longcang, this is entirely deliberate. As the password is intended to be shared, it cannot be considered secure. Encryption would only serve to give an illusion of security where there is none. The password protected blogs feature is there to provide privacy, anyone needing a secure blog should setup their own security.

It does say "This password is stored in plaintext." underneath the password field to make it clear there is deliberately no encryption.
