### ISSUE TITLE
Emoji (or Unicode in general) doesn't get imported

### ISSUE THREAD

**Issue by blackxored** [TryGhost/Ghost#5519]
I've exported my settings since I recently migrated from SQLite to RDS and emojis didn't get imported back. 

Update: hmm is not only about the importing, it's also when I save them back, I wonder if there's a misconfiguration on my end? I've tried setting `charset` in the connection config, no luck.

**Comment by ErisDS** [comment]
Hi @blackxored, sorry to hear you've had some trouble with exports & imports :disappointed:. Can you please help us to fix the issue by providing a bit more detail? There's a bug report template in our [contributing guidelines](https://github.com/TryGhost/Ghost/blob/master/CONTRIBUTING.md#bugs) - it would be good to have the full details of the export & import environments, as well as an example JSON file that doesn't report properly. 

If you can make it as easy as possible to reproduce the issue, it's far more likely to get fixed quickly. Thanks :smile_cat:

**Comment by blackxored** [comment]
Hi, I think they might be an issue with my MySQL config, as I tried inserting an emoji to my about section and then saving, and while it seems to be in memory works, but as soon as I refresh a couple of times I'm back to `????`, any clues?

**Comment by Kikobeats** [comment]
@blackxored I have the same issue under Ghost@0.7 using twemoji (and MySQL as well)
