### ISSUE TITLE
Inline validation errors for valid fields aren't cleared if other fields are invalid

### ISSUE THREAD

**Issue by kevinansfield** [TryGhost/Ghost#5520]
Only observed so far when the validation engine is mixed in to a model rather than a controller. It's working ok with controller-based validations as evidenced by it's use in the setup/two controller.

From initial checks it appears the validation check for the individual field is failing which results in the error message not being cleared.

**Comment by kevinansfield** [comment]
This may be a separate issue but I have just noticed that for fields which have multiple different errors depending on the value, previous error messages aren't cleared when re-validating.

From a UX perspective it can be a bit confusing as it results in a randomly selected error being selected on each focus-out. I've made a screen recording demonstrating the issue here http://recordit.co/DfpdlfVtpe

**Comment by acburdine** [comment]
I think this can be closed per #5548?

**Comment by kevinansfield** [comment]
Yep, thanks!
