### ISSUE TITLE
API Permissions: Owner role should only be editable by itself

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#5521]
The original spec for the owner role was that it should be different from an admin in the following ways:

- there can only be one owner
- the owner cannot be deleted (there must always be one owner)
- only an owner can transfer ownership

However, this leaves a gap in that it is possible for an admin to modify the credentials of an owner account. Admins are trusted users, so this shouldn't be a problem. However, after further thought it seems this doesn't really reflect the original intent of the Owner role in that the Owner was supposed to be privileged enough to maintain overall control until they decided to surrender it to another user. 

Therefore, I think it makes sense to change the permissions around the Owner role, such that the user with this role can only be edited by itself.

**Comment by nuclearpengy** [comment]
:+1:

**Comment by ErisDS** [comment]
This ought to be relatively straightforward. We need to update the `permissible` method on the [user model](https://github.com/TryGhost/Ghost/blob/9114889fd6e927fe8547ce890023750e814dd9b1/core/server/models/user.js#L468) to check that both the user being edited and the user doing the editing have the `Owner` role and there is similar code already.

This makes the most challenging part updating the tests to reflect the new spec - there are [plenty of examples](https://github.com/TryGhost/Ghost/blob/9114889fd6e927fe8547ce890023750e814dd9b1/core/test/integration/api/api_users_spec.js#L196) in the existing tests, and I'd recommend changing these first TDD style in this case (I don't advocate that all the time, but this is a good use of it) :smiling_imp: 

Given that this is a straightforward-ish change to existing code, I think it's safe to mark with the `beginner` label.
