### ISSUE TITLE
Implement meta referrer tag

### ISSUE THREAD

**Issue by JohnONolan** [TryGhost/Ghost#5522]
With the advent of HTTPS as the new standard for the web, referrer data has started to fall through the cracks. In order to combat this, we can implement an extremely simple meta tag which will bring them back. Moz have a fantastic write-up on [how and why this is a good idea](https://moz.com/blog/meta-referrer-tag).

This issue is to implement a default output of exactly:

```HTML
<meta name="referrer" content="origin" />
```

within `{{ghost_head}}` - output on the next line after the `rel="canonical"` tag.

**Comment by jomahoney** [comment]
Really hoping this was as easy as it sounded...

**Comment by ErisDS** [comment]
Just thought - is this supposed to output on any particular page? Or all of them?

**Comment by JohnONolan** [comment]
All of them - come on now, my spec writing isn't THAT abysmal ;)

**Comment by ErisDS** [comment]
Sorry :flushed: just wanted to be :100: % sure. :bow:

**Comment by JohnONolan** [comment]
:trollface:
