### ISSUE TITLE
Unable to complete Invite User process

### ISSUE THREAD

**Issue by kevinansfield** [TryGhost/Ghost#5525]
Steps to reproduce:

1. Invite a new user through the team page
2. Click the link in the e-mail
3. Fill in the form
4. Click 'Create Account'

Nothing happens when clicking the Create Account button. No visual indication or any network activity.

**Comment by MichielDeMey** [comment]
Anything missing for this task?
I believe a PR was merged for this issue?

**Comment by ErisDS** [comment]
This was closed by f3c4df3
