### ISSUE TITLE
User profile image component - validation & improvements

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#5528]
The user profile image component was added in https://github.com/TryGhost/Ghost/pull/5355. 

![](http://puu.sh/iQsST.png)

There are a couple of finishing touches to wrap up:

- if an invalid image is uploaded, we should use a gh-alert to notify the user it failed
- currently, once you add an image there is no way to remove it again, e.g. if you decide you want to go back to having your gravatar - @JohnONolan does this need to be possible?

I also noticed that the email field is auto-focused, meaning if you go straight to upload an image, you get an inline error about the email address being invalid (should be an error saying it's empty, that's a quick change). Do we want to prevent the auto focus or is this error showing up OK?

**Comment by JohnONolan** [comment]
> currently, once you add an image there is no way to remove it again, e.g. if you decide you want to go back to having your gravatar - @JohnONolan does this need to be possible?

Not important for now - you can always edit/remove the image once logged in anyway

**Comment by acburdine** [comment]
> Do we want to prevent the auto focus or is this error showing up OK?
IMO we should prevent auto-focus on the first input field, just because it makes it somewhat cleaner not to have the error show up until you've actually visited that field.

**Comment by JohnONolan** [comment]
Errors should only show up on *de*focus anyway?

**Comment by acburdine** [comment]
> Errors should only show up on defocus anyway?

Yeah they do, but with the field auto-focused, clicking on the profile image component to upload an image de-focuses the field and shows the error.

**Comment by JohnONolan** [comment]
Can we prevent showing an inline-error if a field is empty?

**Comment by acburdine** [comment]
In theory yes, but there are some validation rules that check for emptiness, and with no indication that certain fields are required/not required, it might be confusing.

**Comment by acburdine** [comment]
> NB: Many/most people won't upload an image at this stage, the flow is very much intended to begin with email address and allow adding/editing of an image if desired.

That makes more sense, so I'll just leave it for now. I've updated the validation rule to say 'please enter an email' instead of 'invalid email' if the field is empty.
