### ISSUE TITLE
Update signup screen to use new profile image upload component

### ISSUE THREAD

**Issue by kevinansfield** [TryGhost/Ghost#5544]
The signup screen (seen by invited users when they click to activate their account) currently has no way of uploading the profile image. We should use the new `gh-profile-image` upload component to add the functionality.

Example implementation can be found in the setup/two controller and template.

**Comment by acburdine** [comment]
Also, don't know if this needs to be in the same issue or a different issue, but maybe adding the profile image upload component to the profile editing page might be a good idea as well?

**Comment by hoxoa** [comment]
Will take a look at this. 

What do you think of putting inline validation/errors and the new `form group` in it, too?

@acburdine :+1: can do this in the same PR or another, just like you want.

**Comment by kevinansfield** [comment]
I'm already taking care of the inline validations in #5458

**Comment by acburdine** [comment]
@hoxoa I think @jomahoney is taking care of the signup screen one? I would confirm that with him but if you want to do one and he do the other I think that would work.

**Comment by jomahoney** [comment]
@hoxoa I can confirm that I'm in the midst of doing this. I should probably start commenting issues before I start working on them.

**Comment by jomahoney** [comment]
Just an update, busy week so only getting around to this now. Was blocked by #5564 for a while. Hopefully PR by Sunday.
