### ISSUE TITLE
User onboarding - blog title does not update until refresh

### ISSUE THREAD

**Issue by jomahoney** [TryGhost/Ghost#5545]
### Issue Summary

When going through the onboarding process, if the blog title has been set; it is not reflected once the user finishes the process. It will load on refresh or if the user logs out and back in.

### Steps to Reproduce
1. Set blog title on onboarding process:

<img src="https://cloud.githubusercontent.com/assets/1396009/8619172/7f5fec06-270c-11e5-9a55-f53de3b236a6.PNG" width="300">
2. Finish the onboarding process and proceed to the editor pane. Note the `<title>` of the page and Title on the page both reflect the default "Ghost" title:

<img src="https://cloud.githubusercontent.com/assets/1396009/8619210/cee7217c-270c-11e5-898a-399b7b002563.PNG" width="200">
3. Refresh and note that title has been changed:

<img src="https://cloud.githubusercontent.com/assets/1396009/8619290/b747e50a-270d-11e5-8779-ef7458595dda.PNG" width="200">

### Technical details:

* Ghost Version: master
* OS: Windows 8.1
* Node Version: v0.12.4
* Browser: Chrome 43.0.2357.130
* Database: SQLite

**Comment by acburdine** [comment]
I fixed a similar issue a couple of weeks ago. I'll take care of this one
