### ISSUE TITLE
Pagination not working on tags endpoint.

### ISSUE THREAD

**Issue by jaswilli** [TryGhost/Ghost#5551]
The new `fetchPage` method does not construct a working `count()` query for tags.  Probably because the tags query it starts with already contains a group-by and an aggregate function (for the posts count field).

**Comment by ErisDS** [comment]
Good catch. This goes hand in hand with the fact that the count query doesn't take into account whether the posts are public or private. Need to solve counts in a different way.

**Comment by novaugust** [comment]
I was looking to see if anyone's reported that infinite scroll on `/settings/tags` is broken - I'm going to assume it's this :)

**Comment by jaswilli** [comment]
Indeed.
