### ISSUE TITLE
How can use the latest version of showdown?

### ISSUE THREAD

**Issue by Sophie-OS** [TryGhost/Ghost#5552]
The latest version of [showdown](https://github.com/showdownjs/showdown/releases/tag/1.2.0) fixes some nagging issues such as consecutive lists misbehaving and in word underscores. It also supports tables and other interesting features, such as github tasklists.

I've tried to update showdown in ghost v0.6.4 but some of ghosts extensions broke. I've asked this in showdown's issue tracker https://github.com/showdownjs/showdown/issues/173 and they said ghost is using a fork that broke compatibility with main project.

So, is there a way to make showdown latest version work with ghost?

**Comment by acburdine** [comment]
@Sophie-OS I'm not sure what the status is, but I know @ErisDS was working on a PR (#5167) to update certain showdown extensions.

**Comment by ErisDS** [comment]
Hi @Sophie-OS, Ghost's fork can be found here: https://github.com/erisds/showdown

The two projects are unfortunately incompatible with each other, so where the bug fixes can be brought into Ghost's fork the major changes cannot without causing serious headaches. At the moment, the fork is in an undocumented broken state (my fault, sorry). However, if you'd like to help out bringing the list or underscore fixes into the fork - please do submit PRs against it :)

**Comment by Sophie-OS** [comment]
I see. Do you have an ETA on this? 

I don't think I have the necessary skills to fix those issues. Maybe a joint effort between showdown team and ghost? I will bump the issue in showdown's tracker.

IMHO, proper markdown support is one of the biggest selling points of ghost and what made me switch from wordpress.

**Comment by ErisDS** [comment]
It's not something the showdown team should be expected to do, ghost's showdown is different - think of it as 'ghost-down'.

As an open source project we don't really work with etas :wink:

**Comment by tivie** [comment]
Hi. Hope you don't mind me barging in here.

I've checked showdown-ghost fork is too far behind to backport all features and bugfixes in showdown "main". 

However, I took a good look at Ghost's source code and @ErinDS improvements made to showdown and it shouldn't be too hard to apply them to v1.2.0.

**Comment by ErisDS** [comment]
@tivie Be very careful with my fork, it's currently very very broken ;) (There are issues open about it). If there's a particular change you want me to push back to showdown feel free to raise an issue on the main repo and tag me into it. I'm happy to contribute backwards.
