### ISSUE TITLE
Wrong，stack Error: "pre" versions of node cannot be installed, use the --nodedir flag instead

### ISSUE THREAD

**Issue by KingHanWen** [TryGhost/Ghost#5571]
gyp ERR! configure error 
gyp ERR! stack Error: "pre" versions of node cannot be installed, use the --nodedir flag instead
gyp ERR! stack     at install (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:66:16)
gyp ERR! stack     at Object.self.commands.(anonymous function) [as install] (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/node-gyp.js:66:37)
gyp ERR! stack     at getNodeDir (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:163:20)
gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:106:9
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:744:7)
gyp ERR! stack     at ChildProcess.emit (events.js:112:17)
gyp ERR! stack     at maybeClose (child_process.js:1017:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1089:5)
gyp ERR! System Linux 2.6.32-431.20.3.el6.x86_64
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/root/ghost/node_modules/sqlite3/lib/binding/node-v0.13.0-pre-linux-x64/node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=/root/ghost/node_modules/sqlite3/lib/binding/node-v0.13.0-pre-linux-x64"
gyp ERR! cwd /root/ghost/node_modules/sqlite3
gyp ERR! node -v v0.13.0-pre
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/root/ghost/node_modules/sqlite3/lib/binding/node-v0.13.0-pre-linux-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/root/ghost/node_modules/sqlite3/lib/binding/node-v0.13.0-pre-linux-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/root/ghost/node_modules/sqlite3/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:112:17)
node-pre-gyp ERR! stack     at maybeClose (child_process.js:1017:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1089:5)
node-pre-gyp ERR! System Linux 2.6.32-431.20.3.el6.x86_64
node-pre-gyp ERR! command "node" "/root/ghost/node_modules/sqlite3/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /root/ghost/node_modules/sqlite3
node-pre-gyp ERR! node -v v0.13.0-pre
node-pre-gyp ERR! node-pre-gyp -v v0.6.7
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/root/ghost/node_modules/sqlite3/lib/binding/node-v0.13.0-pre-linux-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/root/ghost/node_modules/sqlite3/lib/binding/node-v0.13.0-pre-linux-x64' (1)
npm ERR! Linux 2.6.32-431.20.3.el6.x86_64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--production"
npm ERR! node v0.13.0-pre
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE

npm ERR! sqlite3@3.0.8 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sqlite3@3.0.8 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! This is most likely a problem with the sqlite3 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls sqlite3
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/ghost/npm-debug.log

**Comment by KingHanWen** [comment]
Error “npm install” arise

**Comment by halfdan** [comment]
Hi @KingHanWen and welcome to Ghost,

Ghost only supports node v0.10 and v0.12 at the moment. It seems like you're trying to install it with v.0.13.0-pre which is probably causing the error. Please revert back to a supported version of node.

**Comment by KingHanWen** [comment]
THX  
My English is bad, look at some of the technical documentation general look at the code section. Very sorry

**Comment by KingHanWen** [comment]
@halfdan 
However, I encountered a new problem
Warning: Command failed: /bin/sh -c /root/Ghost/core/client/node_modules/.bin/ember build
/bin/sh: /root/Ghost/core/client/node_modules/.bin/ember: No such file or directory
 Use --force to continue.

**Comment by KingHanWen** [comment]
Running "shell:ember:dev" (shell) task
/bin/sh: /root/Ghost/core/client/node_modules/.bin/ember: No such file or directory

**Comment by ErisDS** [comment]
Hi @KingHanWen, if you need help getting started with Ghost, please join our [slack](https://ghost.org/slack) community, or use [stackoverflow](http://stackoverflow.com/questions/tagged/ghost-blog) if you prefer. GitHub is for tracking problems with the software itself. Thanks :+1:
