### ISSUE TITLE
[Thought] Use the rendering engine that the theme depence on.

### ISSUE THREAD

**Issue by aroneiermann** [TryGhost/Ghost#5579]
I think about providing a patch that add the ability to use different rendering engines and activates the rendering engine that is needed by the activated theme.

Would such a patch get in the core?

Related to #1131.

**Comment by ErisDS** [comment]
Hi @aroneiermann, our theme API, which is built on top of handlebars, is integral to our theme developer community and to providing a consistent experience to all of our users. The comments I wrote on #1131 and the related, but much more in depth #3419 still stands 100%. Therefore, such a patch would not be accepted.

**Comment by aroneiermann** [comment]
Thanks for the response. I can understand the reasons.
