### ISSUE TITLE
Access user information outside of post context

### ISSUE THREAD

**Issue by jonblack** [TryGhost/Ghost#5583]
I'm writing a theme where the sidebar, visible on most pages, will contain an about section. I'd like the about section to contain the blog owners profile information, such as the image, but the `{{author}}` helper is only available in the `post` and `author` contexts.

I can still achieve what I want by hard-coding it into the theme, but that's a hassle if the author changes their profile.

Perhaps an `@owner` helper could be used for this, or extending `@blog` to include owner information?

**Comment by cobbspur** [comment]
Hi @jonblack, 

I think the `{{get}}` helper which will be coming soon will enable you to do exactly this sort of thing. You can read [some information](https://github.com/TryGhost/Ghost/issues/4439) on how this is developing. 

The `{{get}}` helper will enable you to query any additional data you want whereas the blog owner is very limited and will not always be able to provide users with the exact information they want.

**Comment by jonblack** [comment]
You're right, the `{{get}}` helper will solve this and it's also more flexible. Thanks.
