### ISSUE TITLE
Prepare for npm3

### ISSUE THREAD

**Issue by halfdan** [TryGhost/Ghost#5584]
npm3 will change how peerDependencies are handled:

```
npm WARN peerDependencies The peer dependency mocha@>=1.x.x included from grunt-mocha-istanbul will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN peerDependencies The peer dependency istanbul@0.x.x included from grunt-mocha-istanbul will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
```

We need to explicitly depend on mocha and istanbul in the future.

**Comment by jaswilli** [comment]
`grunt-mocha-cli` has already removed peerDependencies in its latest version, and there's an issue open at `grunt-mocha-istanbul` to do the same.

I don't think there's any need to add these dependencies directly right now as it should be sorting itself out on its own.

**Comment by halfdan** [comment]
Fair points. For reference here's he grunt-mocha-istanbul issue: https://github.com/pocesar/grunt-mocha-istanbul/issues/38
