### ISSUE TITLE
Issue running the grunt init on Ghost

### ISSUE THREAD

**Issue by uvirk** [TryGhost/Ghost#5586]
This is my full error text:

BuildingBuilding.Build failed.                                                                                 
ENOENT, no such file or directory 'C:\Users\Uday\Documents\GitHub\uvelop.io\core\client\node_modules\ember-cli-
ic-ajax\node_modules'                                                                                          
Error: ENOENT, no such file or directory 'C:\Users\Uday\Documents\GitHub\uvelop.io\core\client\node_modules\emb
er-cli-ic-ajax\node_modules'                                                                                   
    at Error (native)                                                                                          
    at Object.fs.readdirSync (fs.js:761:18)                                                                    
    at C:\Users\Uday\Documents\GitHub\uvelop.io\core\client\node_modules\broccoli-merge-trees\index.js:32:21   
    at Array.map (native)                                                                                      
    at mergeRelativePath (C:\Users\Uday\Documents\GitHub\uvelop.io\core\client\node_modules\broccoli-merge-tree
s\index.js:30:29)                                                                                              
    at C:\Users\Uday\Documents\GitHub\uvelop.io\core\client\node_modules\broccoli-merge-trees\index.js:23:5    
    at lib$rsvp$$internal$$tryCatch (C:\Users\Uday\Documents\GitHub\uvelop.io\core\client\node_modules\rsvp\dis
t\rsvp.js:489:16)                                                                                              
    at lib$rsvp$$internal$$invokeCallback (C:\Users\Uday\Documents\GitHub\uvelop.io\core\client\node_modules\rs
vp\dist\rsvp.js:501:17)                                                                                        
    at lib$rsvp$$internal$$publish (C:\Users\Uday\Documents\GitHub\uvelop.io\core\client\node_modules\rsvp\dist
\rsvp.js:472:11)                                                                                               
    at lib$rsvp$asap$$flush (C:\Users\Uday\Documents\GitHub\uvelop.io\core\client\node_modules\rsvp\dist\rsvp.j
s:1290:9)                                                                                                      
Warning: Command failed: C:\Windows\system32\cmd.exe /s /c "C:\Users\Uday\Documents\GitHub\uvelop.io\core\clien
t\node_modules\.bin\ember build"                                                                               
 Use --force to continue.                                                                                      
                                                                                                               
Aborted due to warnings.                                                                                       

any ideas?

**Comment by ErisDS** [comment]
Hi @uvirk, please don't ask for help on GitHub - it is for tracking issues with the software itself. We have a #help channel in our [slack](https://ghost.org/slack) team, where you can come and chat real time with our community members. Thanks :+1:

**Comment by JanSichula** [comment]
Hello @ErisDS,

thanks for the prompt answer. Truly, as you expressed, it is so much more easier now than before. I am not sure whether this is right place to ask, but I have a follow-up question whether it is possible in Ghost to achieve a URL behavior as for example on qz.com, where there is a unique sequential number before a URL slug and the same content can be reached simply by number in URL path as with full URL. This is great as it eliminates any need to URL shortening services while keeping the branding intact. Just try it at URL bellow to experience what I mean.

http://qz.com/663944/dramatic-drone-footage-of-earthquake-damage-on-japans-kyushu-island/
http://qz.com/663944/

Besides channels, this is something I would love to see implemented in Ghost if it is not yet there.

**Comment by ErisDS** [comment]
@JanSichula That is not currently possible. To request a feature for Ghost you can add your idea (or vote on a similar one) over on our [wishlist](http://ideas.ghost.org). We use this list to help determine what goes into the roadmap and how to prioritise features. You can also access the wishlist any time from inside the Ghost admin:
![](http://puu.sh/jXKwm.png)
