### ISSUE TITLE
Annoying ctrl-h shortcut in markdown editor

### ISSUE THREAD

**Issue by dai-shi** [TryGhost/Ghost#5594]
Looks like this issue has never raised before, so let me post one.

Some users like me often use ctrl-h instead of backspace.  This shortcut is usually effective in OS X and Linux editors.  Everytime I try to delete a char, I see '##' added.  Ctrl-b is similar, but I could say it's emacs specific.

My hope is to customize the shortcut to either disable it or change it to ctrl-shift-h.

(I just realized OS X users don't have this issue, as the shortcut is command-h.)

I would be happy if there were any workaround for this. Any browser extension to bypass this?

**Comment by JohnONolan** [comment]
dai-shi, this is not a bug. If you'd like to look for and/or discuss workarounds that's totally fine, but you'll have a better time over on our [Slack community](https://ghost.org/slack/) - than in a bug tracker.

**Comment by dai-shi** [comment]
@JohnONolan, thanks for your quick reply.

My apologies for the confusion.  I didn't mean it's a bug.  My point was a feature request about "customizable shortcuts".  I should have changed the title as such.  It would be great if it's in a future roadmap.

In any case, my workaround for now is to fork and just modify a line or two. https://github.com/dai-shi/Ghost
