### ISSUE TITLE
Use `updated_at` to prevent overwriting new data with old data.

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#5599]
Ghost's editor is not yet collaborative, which is a sizeable issue that we want to resolve properly in the not too distant future. However, I think in the short-term we could be preventing issues like #4999 and #5450 by preventing overwrites of data when we know we already have a newer version in the database.

When a PUT request is made, it is made with a complete resource that includes the `updated_at` timestamp. With our Ember admin, that data is returned from the server, and simply resent with the next save - the timestamp is not modified by the client (and nor should it be).

On the server, we could use this information to determine whether or not it is safe to save. If the `updated_at` timestamp is the same or newer than the one currently in the table, then we can safely save the data, however, if the `updated_at` timestamp is older than the one in the table then we have a more recent version of the data in the database and should not overwrite it with the data that was sent to the API. 

It is also possible to implement a slightly smarter version of this which also checks if any of the other data in the table is different. If the two versions are the same, there's no need to do anything.

The request to lookup what is in the table, and the request to update it, if safe, should be contained within a transaction, to ensure that we don't end up with race conditions.

I believe the correct thing to do, in the case that the `updated_at` timestamp is out of date and the data cannot be saved, is to return a `409 Conflict` error. The recommendation is to return enough data to resolve the conflict, but I'm not aware of any recommendations on the form of the response. I think using our normal error format is fine. 

Short term, there's no need to do fancy conflict resolution handling, as long term we will hopefully solve all of this with a more advanced solution like Operational Transforms. 

For now, showing an error and warning the user to save their version elsewhere and then refresh is one option, perhaps a slightly nicer option is showing the warning in a modal and giving the user the option to save anyway. This would require adding a force save flag to the PUT request.

This is a slightly dirty short term solution, but my thought is that it is better to prevent overwrites, than to mask that they are happening by doing them blindly.

Although this mostly applies to posts, I think it makes sense to implement it in such a way that overriding `updated_at` is prevented across all models by default.

**Comment by psvet** [comment]
@ErisDS — if this is still necessary, I'd like to take it on myself!

**Comment by ErisDS** [comment]
@psvet For sure it's still needed :+1:

**Comment by psvet** [comment]
@ErisDS, a few questions:

I have the basic `409 Conflict` working by checking `updated_at`, but so far not checking which information has changed. For that implementation, which attributes do you want to be checked? The priority is probably the actual post text, but what about other editable content (`status`, `title`, `slug`, etc.)? And in the case of multiple conflicting attributes, how detailed should the error message be? Right now it's pretty simple: `409 Conflict. Back up newest changes in separate document before refreshing page.`

Also, I added the functionality to `models/base` thinking it would work with all models, but as far as I can tell, the only ones whose `edit` method interacts with the base edit are `post` and `user`. What do you suggest regarding that and implementing it across all models?

**Comment by ErisDS** [comment]
@psvet looks like you've updated your PR since that comment - sorry for the slow reply. I think the key thing to check is always the markdown content which is edited and we definitely shouldn't count the `updated_at`key - but you seem to have quite a smart version implemented ;)
