### ISSUE TITLE
Helper for filtering arrays/collections (e.g. posts)

### ISSUE THREAD

**Issue by denyskoch** [TryGhost/Ghost#5603]
Imagine you want create an index layout like this:

```
|      page header      |
+-----------------------+
|                       |
|  first featured post  |
|                       |
+-----------------------+
| post2 | post3 | post4 |
+-----------------------+
|  ..................   |
```

Show first featured post in one row. Show all other posts in multiple rows in multiple columns (also other featured post but not the first featured post).

Current release cant serve this. Possible solutions:

1. create a handlebars helper for filtering arrays (posts) e.b {{#filter posts where="featured" is=true}}
2. create global object called something like firstFreaturedPost and ability for skipping first featured post

I have implemented a filter helper in a ghost app, which can handle this issue, but I think, this kind of functionality should be part of the core.

sample usage: `{{#filter posts where="featured" is=true max=1}}`

see this Gist for implementation and a sample loop.hbs: https://gist.github.com/denyskoch/8cb294c81ea39c878dd4

**Comment by ErisDS** [comment]
Hi @denyskoch, this is a work in progress - see the issues #4439 and #5463 :) I'll be raising an issue with an in depth spec for filtering shortly.

**Comment by ErisDS** [comment]
P.S. really recommend swinging by our slack: http://ghost.org/slack this is where the dev discussion goes on ;)
