### ISSUE TITLE
Redirect to trailing Slash

### ISSUE THREAD

**Issue by russelltaylor05** [TryGhost/Ghost#5607]
Is there a way to redirect a ghost url to include a trailing slash

`https://example.com/blog/post` -> `https://example.com/blog/post/`

Default behavior seems to be that ghost serves a page for both the slashed and non-slashed URL. This is causing problems for us and we need a way to choose one or the other. 

Is there a configuration option for this somewhere?

**Comment by ErisDS** [comment]
Hi @russelltaylor05, I'm not sure what you're seeing but Ghost does not serve a page at both, it always [enforces the trailing slash](https://github.com/TryGhost/Ghost/blob/master/core/server/middleware/index.js#L261). If you've got a configuration problem and need support, please use our [slack](https://ghost.org/slack) community or [stackoverflow](http://stackoverflow.com/questions/tagged/ghost-blog). GitHub is for tracking issues with the software.
