### ISSUE TITLE
Markdown Engine does not support  「ToC」(Table of Content)

### ISSUE THREAD

**Issue by boolean93** [TryGhost/Ghost#5618]
I'd appreciate if you can support ToC. It really takes a lot of time to make the TABLE manually while writing a long blog. Thx!

**Comment by ErisDS** [comment]
Hi @boolean93,

To request a feature for Ghost you can add your idea (or vote on a similar one) over on our [wishlist](http://ideas.ghost.org). We use this list to help determine what goes into the roadmap and how to prioritise features. You can also access the wishlist any time from inside the Ghost admin:
![](http://puu.sh/jkkFd.png).

**Comment by boolean93** [comment]
:-) OK

**Comment by gam-phon** [comment]
Created the idea. Every one pass to this issue please vote for it. Thanks
http://ideas.ghost.org/forums/285309-wishlist/suggestions/10481094-table-of-content-toc

**Comment by xulz** [comment]
the ideas subdomain is unreachable(redirected).
Find one solution at https://github.com/idiotWu/jQuery-TOC

**Comment by horenmar** [comment]
The wishlist does not seems to exist anymore, links from various blogposts are dead and redirect to https://ghost.com/

Anyway, +1 for this request

**Comment by kevinansfield** [comment]
@horenmar the wishlist has been moved to our new forum. An existing idea for this feature can be found here https://forum.ghost.org/t/add-toc-aka-table-of-contents-for-markdown-engine/655/2
