### ISSUE TITLE
[themes] "#has" helper unable to process variable named "tag".

### ISSUE THREAD

**Issue by DanielTamkin** [TryGhost/Ghost#5622]
The "#has" helper isn't currently able to determine if a variable is true or not right now.
here's a very simple example:

##### tag.hbs

``` handlebars
{{!< default}}
{{#tag}}
  {{> "tt-tag" tag=name}}
{{/tag}}
```
This makes sense, right? your passing the name(which is the tag to the "#has" helper) to `tag`.
Okaaay, so far so good.

##### tt-tag.hbs
``` handlebars
{{#has tag="!note"}}
  {{> "tag-note"}}
{{else}}
  {{> "tag-default"}}
{{/has}}
```
So whats happening here is just me asking: 
> hey does tag(which contains the tag name) equal '!note'?
This should work right?

*NOPE*, for some reason the "#has" helper doesn't recognize the very obvious parameter "tag".
It'd be great to see the "#has" tag be able to handle a situation like this.

**Comment by halfdan** [comment]
I'm not exactly sure what you are trying to achieve here. If you want to render a different template for a specific tag you should just create the `tag-{$tagName}.hbs`. The tag helper is not available in this context - you can use it when rendering a post (and ask whether the post has a specific tag). I'm also not sure whether passing arguments to a partial actually works.

**Comment by DanielTamkin** [comment]
Passing arguments to a partial works, 
What im trying to accomplish here is have the "#has" helper be tricked to process an argument.
and i think you've missed my point, i HAVE made the tag helper available in this context by creating an argument named "tag". but the has helper does not recognize it.
``` handlebars
{{!< default}}
{{#tag}}
  {{> "tt-tag" tag=name}}
{{/tag}}
```

**Comment by ErisDS** [comment]
Hi @DanielTamkin - glad you found an alternative solution  :+1:. The `{{#has}}` helper is working as expected here - it may be improved in future and if that's something you're interested in I recommend adding it to/voting for it on our [wishlist](http://ideas.ghost.org). As this isn't a bug, I'm going to close it. If you need further help with your use case, please use the #themes channel on [slack](https://ghost.org/slack)

The tag templates are described in the documentation here: http://themes.ghost.org/docs/templates
