### ISSUE TITLE
0.4 Release Notes have been destroyed

### ISSUE THREAD

**Issue by liamdawson** [TryGhost/Ghost#5623]
https://github.com/TryGhost/Ghost/wiki/Release-Notes:-0.4.0/_history

I was confused when I was linked there and got a page with "Testing" - for some reason, the page has been destroyed (but is still available via revisions).

**Comment by acburdine** [comment]
@liamdawson, that page was deleted by Hannah a while back (last October), and shouldn't have been re-added. I just destroyed it again, so it should be good now. Also - this issue tracker is used for issues with the software itself, not necessarily the wiki :smile: Thanks for the heads up though!

**Comment by ErisDS** [comment]
If you visit the release page, you'll find links to all the available info: https://github.com/TryGhost/Ghost/releases/tag/0.4.0
