### ISSUE TITLE
Date Check Doesn't Take Year into Account

### ISSUE THREAD

**Issue by Sneagan** [TryGhost/Ghost#5629]
Trying to manually add old Markdown posts to the system and when I set the date on a post to a date in 2014 I get a "Published Date cannot currently be in the future." error. Looks like it's not taking the year into account when validating the date.

**Comment by halfdan** [comment]
How do you enter the date?

**Comment by cobbspur** [comment]
Hi @Sneagan,

Thank you for raising a bug report. We have previously used the importer for posts which span multiple years including 2014 and 2015 without any issues. 

This means there could be an issue with your environment or your import data format. It is also possible that there is a real edge-case bug in Ghost somewhere. To help us investigate this further would you mind providing us with a few more details. 

There is some useful information on what information to include our [contributing guidelines for bugs](https://github.com/TryGhost/Ghost/blob/master/CONTRIBUTING.md#bugs).

Additional to the information in those guidelines it may be useful to provide your import file or a snippet from it that shows the dates of the posts. 

We have a guide to [Ghost's import JSON file structure](https://github.com/TryGhost/Ghost/wiki/Import-format) that you may also find useful

**Comment by Sneagan** [comment]
I'm trying to avoid the importer because conforming to the JSON requirements will take longer than creating new posts manually.

### Steps to Reproduce

1. Create a new post
2. Click the gear icon
3. Set a date in 2014

### Technical details:

* Ghost Version: master (latest commit: 7897a2dfd4c6258b369815dabdb17a6e6963d1c0)
* Client OS: Mac OS X 10.10.4
* Node Version: 0.12.7
* Browser: Safari 8.0.7

**Comment by cobbspur** [comment]
Hey, if you are using this for production purposes we would you advise you against you using the master branch as this is constantly changing and can contain bugs. You could use the stable branch for production. 

Can you confirm that when you edit a post you see something along these lines:
 ![](http://puu.sh/jnXbi/be7dc3e159.png)

Could you also try changing the date to 03 Aug 14 in a differentbrowser such as chrome.

**Comment by Sneagan** [comment]
Yes that's what I see. I was wrong about my version. It's the one I downloaded from the website the day I created this issue. I've tried on other browsers. Same issue. Can you not reproduce?

**Comment by Sneagan** [comment]
Haha. Figured it out. The system uses no more than 3 characters for months abbreviations, so Sept doesn't work, but Sep does.

**Comment by cobbspur** [comment]
:+1:
