### ISSUE TITLE
'npm start' ERR! Please HELP!!!!!

### ISSUE THREAD

**Issue by jacob0823** [TryGhost/Ghost#5631]
This is what happens when I enter 'npm start'. I closed the original terminal tab to see if it would work in a new tab and I received the same Error message. That's why this terminal log doesn't show the installation of npm. Please help!

TERMINAL:

Jacobs-MacBook-Pro:~ Jacob$ /Users/Jacob/Downloads/ghost-0.6.4 npm install --production
-bash: /Users/Jacob/Downloads/ghost-0.6.4: is a directory
Jacobs-MacBook-Pro:~ Jacob$ npm start
npm ERR! Error: ENOENT, open '/Users/Jacob/package.json'
npm ERR! If you need help, you may report this entire log,
npm ERR! including the npm and node versions, at:
npm ERR! http://github.com/npm/npm/issues

npm ERR! System Darwin 14.3.0
npm ERR! command "node" "/usr/local/bin/npm" "start"
npm ERR! cwd /Users/Jacob
npm ERR! node -v v0.10.36
npm ERR! npm -v 1.4.28
npm ERR! path /Users/Jacob/package.json
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR! /Users/Jacob/npm-debug.log
npm ERR! not ok code 0

**Comment by acburdine** [comment]
@jacob0823 as it appears, you are in your home directory and not in the directory in which ghost is installed. The easiest way to fix this is to try this:
```bash
cd /Users/Jacob/Downloads/ghost-0.6.4
npm install --production
npm start
```

Also, the Ghost issue tracker is more for issues with the software itself. If you have issues with installing ghost, please use the Slack channel. http://ghost.org/slack/ :smile:

**Comment by jacob0823** [comment]
@acburdine I still get the same error
