### ISSUE TITLE
Support fenced code block in list.

### ISSUE THREAD

**Issue by vilic** [TryGhost/Ghost#5632]
It would be great if we can do something like this:
- A list item with some code sample
  
  ```
  console.log('hello, world.');
  ```

**Comment by minwe** [comment]
Why do not use marked? It should better than showdown.

**Comment by tomekr** [comment]
:+1:

@vilic Have you found a decent workaround for this in the meantime?

**Comment by vilic** [comment]
@tomekr sadly no.

**Comment by jgillich** [comment]
Unless I'm wrong, this is https://github.com/showdownjs/showdown/issues/208 and there's an easy solution.

**Comment by JohnWestlund** [comment]
@jgillich I cant get the work around you posted to work on http://showdownjs.github.io but not in Ghost. The best I've been able to manage is:
<pre>1. item one
    ```code 1
    code 2
    ```
2. item two</pre>

Which creates a what looks like a code block broken in half over two lines:
![capturemd](https://cloud.githubusercontent.com/assets/5503935/11056810/4f8cfaa8-873a-11e5-9637-ab27501a1969.PNG)

**Comment by kevinansfield** [comment]
@JohnWestlund I believe the workaround doesn't used "fenced" code blocks, rather relies on the indentation to indicate a code block. e.g.:

![screen shot 2015-11-10 at 12 00 47](https://cloud.githubusercontent.com/assets/415/11061967/d8797676-87a2-11e5-9927-aa894b908d57.png)

**Comment by gchandrasa** [comment]
@kevinansfield yes, the indentation work but how do you use syntax highlight without fenced code blocks

     ```language-javascript
     [...]
     ```

**Comment by minwe** [comment]
How about this?

<img width="1123" alt="2016-04-11 5 02 55" src="https://cloud.githubusercontent.com/assets/4370770/14422134/b2733ed4-0007-11e6-8317-e821ad8aa4d5.png">

Code blocks nested in blockquote are not rendered correctly. It should be a `<pre><code>...</code></pre>`, but in Ghost got just `<code>`。

Take below as example:

```
> Note:
>
> Some code in blockquote.
>
> ```javascript
> function() {
>   consoel.log('hello world!');
> }
> ```
```

These markup is rendered to:

```html
<blockquote>
  <p>Note:</p>
  
  <p>Some code in blockquote.</p>
  
  <p><code>javascript
  function() {
    consoel.log('hello world!');
  }
  </code></p>
</blockquote>
```

**The correct result should be**:

```html
<blockquote>
  <p>Note:</p>
  
  <p>Some code in blockquote.</p>

<pre><code class="javascript language-javascript">function() {
  consoel.log('hello world!');
}</code></pre>
</blockquote>
```

The [official demo of Showdown](http://showdownjs.github.io/demo/#/You%20can%20also%20use%20other%20markdown%20syntax%20inside%20them.%0A%0A%3E%20Note%3A%0A%3E%0A%3E%20Some%20code%20in%20blockquote.%0A%3E%0A%3E%20%60%60%60javascript%0A%3E%20function()%20%7B%0A%3E%20%20%20consoel.log('hello%20world!')%3B%0A%3E%20%7D%0A%3E%20%60%60%60) works well.

<img width="881" alt="2016-04-11 5 11 59" src="https://cloud.githubusercontent.com/assets/4370770/14422359/04014592-0009-11e6-8fb7-a3969177d1af.png">

Marked works well, too.

So why do not use the official version of Showdown, the [Ghost fork](https://github.com/erisds/showdown) is out of date and bugly.

**Comment by Draveness** [comment]
I really wanna know when will this issue be fixed

**Comment by icymind** [comment]
need fixed + 1

**Comment by Draveness** [comment]
When will fenced code block be supported in Ghost? Have been waiting for this for a long long time
