### ISSUE TITLE
User Flows: On submit / server error message

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#5635]
On the various user flows:
- login flow
- password reset flow (form you get to from reset email)
- user signup (form you get to from invite email)
- setup 

There is a red error message that is shown below the submit button which currently reads 'The password fairy does not approve'

![](http://puu.sh/jq8Lr.png)

This error is the intended location for any error message which occurs on submit - e.g. if a user submits the form with inline errors uncorrected or if the call goes off to the server and gets a server side message like incorrect password.

The language of the message is an indicator that we wanted to update the messages to be friendlier / more fun, but that can/will be done separately.

The first change that needs to be made here, is to use something like a `showFlowError` function to display errors that come back from the server in this location, rather than as a big-red-alert. 

The second change is to be able to show some sort of message that summarises the errors if there are still inline errors when submit is pressed. This could be a generic, boring 'please complete the form' message to start with. 

Ideally, it might pick one from a set of random generic error messages, or be able show something specific to the field that is incorrect. I'm not sure what information is available or what is possible here, so it would be interesting to get some suggestions for what can be done.

The aim is to inject a little bit more personality into the flows & improve the user experience when things aren't going to plan.

**Comment by cobbspur** [comment]
Everything here is done other than the random messages. IIRC there is a decision still to be made as to whether or not this is still wanted

**Comment by ErisDS** [comment]
@JohnONolan any further thoughts on this? Shall I close & we can revisit later, or did you want to look at adding randomised or friendlier messages?

**Comment by ErisDS** [comment]
Alternatively can raise a separate issue for that for a later milestone

**Comment by JohnONolan** [comment]
Can revisit later
