### ISSUE TITLE
support withknown.com and other indiewebcamp.com sites.

### ISSUE THREAD

**Issue by dissolve** [TryGhost/Ghost#5637]
I was wondering if there was any interest in beginning work on federating Ghost with other blogs.  At an initial level it would just be a matter of adding microformats-2 structure to the themes  and maybe go on to being able to pull in comments from other blogs.

**Comment by ErisDS** [comment]
The best way to find an answer to this question (whether there is interest) is to suggest it on our [wishlist](http://ideas.ghost.org). That page is accessible from inside the Ghost admin, and allows you to build traction for a feature request in a way that is not possible with a GitHub issue :wink:
