### ISSUE TITLE
Section to add tag a post is missing

### ISSUE THREAD

**Issue by SoldierCorp** [TryGhost/Ghost#5638]
I can't edit or add tags of my post because the section is not there.

![screen shot 2015-08-06 at 6 05 28 pm](https://cloud.githubusercontent.com/assets/1775881/9125374/cd00c052-3c65-11e5-84ce-717c01c69c65.png)

**Comment by acburdine** [comment]
@SoldierCorp This looks like the github master branch of Ghost. Currently the master branch is not production ready, and thus some things are nonexistent/broken (including the tag input field). If you are wanting to use Ghost as an actual production blog, try using the `stable` branch on Github or download the official release zip from the ghost website [here](https://ghost.org/zip/ghost-0.6.4.zip). :smile:

**Comment by SoldierCorp** [comment]
I will do, thanks :)
