### ISSUE TITLE
Ghost login in Mac

### ISSUE THREAD

**Issue by HoddzDJ** [TryGhost/Ghost#5641]
When loading the login page in Safari on Mac, it looks great. One thing lets it down though.

![screen shot 2015-08-07 at 11 03 02](https://cloud.githubusercontent.com/assets/5874012/9133749/eed5f4dc-3cf5-11e5-813a-2603fbc62095.png)

This very ugly tool that Apple decided to add to password boxes. Whilst this is more a problem really from Apple, it doesn't look great. Not sure if there is a way to get over that other than moving the forgot link?

**Comment by jomahoney** [comment]
This also stands as an issue for anyone using a Password Manager a-la LastPass.

**Comment by ErisDS** [comment]
Hi @HoddzDJ I cannot reproduce that on Safari on my machine, can you clarify what version you're on? We have a [template for raising bug reports](https://github.com/TryGhost/Ghost/blob/master/CONTRIBUTING.md#user-content-bug-template) which outlines what information to include, and is particularly important when raising browser bugs: 

Not reproducible:
 Ghost Version: master (latest commit: f1a602e)
* Client OS: Mac OS X 10.10.4
* Server OS: Mac OS X 10.10.4
* Node Version: 0.10.40
* Browser: Safari 8.0.7 (10600.7.12)
* Database: SQLite

**Comment by kevinansfield** [comment]
I see it on mine:

- Ghost version: master (latest commit: f1a602e)
- Client OS: Mac OS X 10.11 Beta (15A234d)
- Server OS: Mac OS X 10.11 Beta (15A234d)
- Node Version: 0.12.4
- Browser: Safari 9.0 (11601.1.41)
- Database: SQLite

**Comment by kevinansfield** [comment]
Adding some `padding-right` to that field pulls the key icon away from the "forgot" link and so fixes this issue however it also highlights another aspect to this issue - long passwords will also appear under the forgot link, something which sufficient padding will also fix.

**Comment by HoddzDJ** [comment]
Sorry @ErisDS, only just seen your reply (d'oh)! Yeah it's on Safari 9 which is available to testers. Soon to be shipped with OS X 10.11. Totally forgot to format the post correctly, not reported anything in a long time so that's my bad.
