### ISSUE TITLE
Bug: Publish button dropdown incorrectly positioned

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#5644]
When you open the dropdown menu for the save button, it's appearing in the wrong place:

![](http://puu.sh/jufYW.png)

Not 100% whether these are correct, so including images to be sure:

![](http://puu.sh/jugaq.png)

![](http://puu.sh/jugdN.png)

This is happening on master. It was OK back when this was merged: #5406 not yet found the point at which it changed.

**Comment by jaguerra** [comment]
On current master using latest Mac Chrome and FF seems to work properly:

![pic1426](https://cloud.githubusercontent.com/assets/516524/9278567/f2426562-42b1-11e5-9e0c-947ff93bd947.png)

### Technical details:

* Ghost Version: master (latest commit: 2a9299d)
* Client OS: Mac OS X 10.10.4
* Server OS: Mac OS X 10.10.4
* Node Version: 0.10.40
* Browser: Chrome 44.0.2403.130 and Firefox 39.0.3
* Database: SQLite

**Comment by ErisDS** [comment]
This was closed by #5662 / 7969d06
