### ISSUE TITLE
How can I insert an indent when using the markdown editor

### ISSUE THREAD

**Issue by Jecvay** [TryGhost/Ghost#5645]
when i hit the `tab` in the editor, the editor will not inset 4 spaces for me.
how can i do that?

i also want to select multilines and then hit the `tab` to make all the line selected indent 4 spaces.

thanks!

**Comment by ColtraneNadler** [comment]
you have to manually add 4 whitespaces. The second want of yours is not possible to my understanding. I know you can do that with sublime text though.

**Comment by ErisDS** [comment]
Hi @Jecvay, If you're inserting code snippets into Ghost, you're best off formatting the code in your editor first, and then pasting it into Ghost when you're ready.

If you're keen to see this feature added to Ghost, you can vote on various suggestions on the wishlist [here](http://ideas.ghost.org/forums/285309-wishlist/suggestions/7564533-ctrl-cmd-shortcut-for-indent-unindent) or [here](http://ideas.ghost.org/forums/285309-wishlist/suggestions/7777170-using-tab-button-when-write-in-the-markdown-editor).

**Comment by santiiim** [comment]
Shift enter does just that, respecting the tabulated space from the preceding paragraph.
