### ISSUE TITLE
Tag component behaviour bugs

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#5648]
Typing naturally in the new tag component doesn't always give a nice UX at the moment. Certain actions can result in duplicate tags. It also seems that the tag component loses focus after some actions, which means (for example) if you hit backspace after doing the wrong thing you can end up navigating 'back' away from the editor.

Here are a couple of reproduction cases:

- [ ] Duplicate tag entry

Reproduction steps 1:
- Start typing a tag that exists
- halfway through typing the tag, press the `TAB` key
- the existing tag is entered twice

![](http://puu.sh/jwsp3.gif)

**Note:** if you press `ENTER` or `,` halfway through instead, the correct thing happens. That is the half-written tag gets added as a tag, and added just the once:

![](http://puu.sh/jwsE9.gif)

Reproduction steps 2:

- Start typing a tag that exists
- once the tag is written in full, complete the tag by pressing the `TAB`, `ENTER` or `,` key
- the existing tag is entered twice

![](http://puu.sh/jwsFj.gif)

**Note:** clicking on the tag will result in just one tag being entered

- [ ] Lost focus

Reproduction steps 1:

- fill out the tag component with 2 tags using one of the methods which causes duplication above
- place the cursor at the end
- press backspace twice to delete the tag
- the component loses focus and pressing backspace again to delete the other tag will cause the `back` navigation to fire

Reproduction steps 2:

- start typing an existing tag
- complete the tag 
- the component loses focus

![](http://puu.sh/jwt2l.gif)

Whenever I'm typing in the component, adding or removing tags, the component should retain focus.

Whilst I'm raising things here, I think the intention is to get the `x` icon back for removing tags?

- [ ] Re-add `x` icon for removing tags

**Comment by acburdine** [comment]
The first one is related to typeahead and is similar to one of the bugs reported on the original PR. I'll investigate this soon. 

The second one is also possibly a typeahead issue, and I can look into it as well. 

The third is something I believe @JohnONolan said he would take a look at, as well as a styles audit of the entire thing.
