### ISSUE TITLE
Bug: signing up with another user's email breaks flow

### ISSUE THREAD

**Issue by cobbspur** [TryGhost/Ghost#5653]
### Issue Summary

Clicking on a user invitation email takes you to the signup form. Here you can change your email address. If you change your email address to be the same as an existing user then you will correctly receive an error that the email address is in use:

![](http://puu.sh/jxulM/c85aa6e26a.png) 

After this, clicking on the `Create Account` button does not allow you to change email address and does not transition user to admin. From the console you can see that the validation token is now invalid and the user has been created. You can now log in using the original email address and password provided.

![](http://puu.sh/jxupC/5383db65bd.png)

Possible solutions include:
1) API change - Not invalidating token or saving user if user.email is not unique
2) On `ERROR: SQLITE_CONSTRAINT: UNIQUE constraint failed: users.email` error - continue with  authentication and transition to user's profile page. Possibly show the error as alert or notification at this point.
3) Lock out email address for signup page
### Technical details:
- Ghost Version: master (latest commit: 0f9f0dd69f8c85569b087f70170de930bfb30511)
- Client OS: Win 7 Ultimate x64
- Node Version: 0.12.5
- Browser: Chrome Version 44.0.2403.130 m
- Database: SQLite

**Comment by cobbspur** [comment]
I am going to raise a PR using the 3rd solution idea as a quick fix for now but won't close this issue as it probably warrants further discussion as to the best approach.

**Comment by ErisDS** [comment]
I think not allowing users to change their email on signup was a totally sane fix for this. We've not had a single complaint about the restriction. Closing this as fixed.
