### ISSUE TITLE
Ghost Truck Factor

### ISSUE THREAD

**Issue by gavelino** [TryGhost/Ghost#5657]
As part of my PhD research on code authorship, we calculated the Truck Factor (TF) of some popular GitHub repositories.

As you probably know, the [Truck (or Bus) Factor](https://en.wikipedia.org/wiki/Bus_factor) designates the minimal number of developers that have to be hit by a truck (or quit) before a project is incapacitated. In our work, we consider that a system is in trouble if more than 50% of its files become orphan (i.e., without a main author).

More details on our work in this preprint: https://peerj.com/preprints/1233

We calculated the TF for **Ghost** and obtained a value of **6**.

The developers responsible for this TF are:

Hannah Wolfe - author of 30% of the files
Jason Williams - author of 16% of the files
Matt Enlow - author of 11% of the files
Harry Wolff - author of 10% of the files
Sebastian Gierlinger - author of 10% of the files
Paul Adam Davis - author of 9% of the files

To validate our results, we would like to ask **Ghost** developers the following three brief questions:

(a) Do you agree that the listed developers are the main developers of **Ghost**?

(b) Do you agree that **Ghost** will be in trouble if the listed developers leave the project (e.g., if they win in the lottery, to be less morbid)?

(c) Does **Ghost** have some characteristics that would attenuate the loss of the listed developers (e.g., detailed documentation)?

Thanks in advance for your collaboration,

Guilherme Avelino
PhD Student
Applied Software Engineering Group (ASERG)
UFMG, Brazil
http://aserg.labsoft.dcc.ufmg.br/

**Comment by JohnONolan** [comment]
No.
