### ISSUE TITLE
Zelda: Errors in console

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#5659]
This is about to be the worst bug report ever:

![](http://puu.sh/jxPLd.png)

I've seen this in the console quite a bit. The closest I can get to a reproduction case is 'click around a lot really fast' - in particular between the editor and content screen. It doesn't seem to break anything, but still it seems like it's probably not a good thing :wink:

On one or two occasions I have also seen the editor not load with an error to do with `getValue` or `height` not being defined. I haven't recorded these errors, but will keep an eye out to take a screenshot & figure out a reproduction case. Thought it was worth mentioning soemwhere.

**Comment by ErisDS** [comment]
I've not seen the error mentioned in this issue for a while now, however over the past 2 days I've had this 3 times:

> Uncaught Error: Assertion Failed: Unable to add "ember-application" class to rootElement. Make sure you set rootElement to the body or an element in the body.

![](http://puu.sh/jPvY1.png)

The entire admin is blank when this happens, and it often takes a couple of refreshes / server restarts to get it back :disappointed:

**Comment by ErisDS** [comment]
Has anyone else experienced this? I had it a couple of times in one afternoon and not since. Thinking it's probably safe to close?

**Comment by kevinansfield** [comment]
That last one is a really weird error, no idea what situation would result in Ember not being able to add a class to the body tag 😕. Haven't seen anything like that so far or the original issues since the fixes were merged.

**Comment by MatTheCat** [comment]
Maybe it's related to this? https://github.com/ember-cli/ember-cli/issues/530#issuecomment-76948070

**Comment by ErisDS** [comment]
I bet it's whilst I'm both running the ember tests AND testing in dev mode?

**Comment by ErisDS** [comment]
`/me checks`

**Comment by ErisDS** [comment]
I haven't reliably confirmed it - but it makes sense that the two env vars might conflict? Going to punt this to post-zelda as I don't think it will affect production envs.

**Comment by ErisDS** [comment]
Got a new one :disappointed: cc @kevinansfield 

![](http://puu.sh/jXrOx.png)

**Comment by kevinansfield** [comment]
Np, I thought I'd fixed that but I guess I only fixed a symptom and the problem has simply moved up a level. Pretty confident the root cause is not tearing down the event handler on the resize service in https://github.com/TryGhost/Ghost/blob/master/core/client/app/components/gh-content-view-container.js

**Comment by kevinansfield** [comment]
Can this one be closed now? I haven't seen any of the console errors lately other than the `rootElement` one which we know is caused by running the ember tests at the same time.

**Comment by ErisDS** [comment]
:+1:
