### ISSUE TITLE
Unsupported version of Node

### ISSUE THREAD

**Issue by theboyWhoCriedWoolf** [TryGhost/Ghost#5665]
Node support seems pretty old and outdated ```Ghost needs Node version ~0.10.0 || ~0.12.0 you are using version 1.7.1```

**Comment by sebgie** [comment]
Hey @theboyWhoCriedWoolf and welcome to Ghost issue tracker on GitHub. I think there is some confusion between the different versions of Node.js. Node.js (https://nodejs.org/) currently lists 0.12.7 and 0.10.40 as the latest releases.

From the version number it looks like you are using io.js (https://iojs.org). Where the latest version would be 3.0 btw. As you can see it is quite hard to keep up with the rapid release cycles of io.js and we are currently not able to keep all our dependencies up to date to fully support io.js (see https://github.com/TryGhost/Ghost/issues/5271#issuecomment-102131042).

Ghosts issue tracker is more for issues with the software itself. If you have issues with installing Ghost or selecting a supported Node version, please head over to our Slack channel. http://ghost.org/slack/ :)

**Comment by leotm** [comment]
My mistake was grabbing http://nodejs.org/dist/node-latest.tar.gz which was v4.1.1, rather than from https://nodejs.org/dist/latest-v0.12.x/.
