### ISSUE TITLE
Add support for HSTS

### ISSUE THREAD

**Issue by bmintz** [TryGhost/Ghost#5668]
I'd like to set up HTTP Strict Transport Security for my blog, but I don't know how to do so, and I don't think there's any documentation for it.

I think it can be done using [Helmet](https://github.com/helmetjs/helmet), but I wouldn't know how, anyway.

**Comment by sebgie** [comment]
Hey @bmintz and welcome to the Ghost issue tracker on GitHub. Ghost doesn't support SSL termination and HSTS out of the box. We recommend a proxy server (Nginx/Apache/...) that does that for you. You can find various instructions of how to enable HSTS for [these servers](https://raymii.org/s/tutorials/HTTP_Strict_Transport_Security_for_Apache_NGINX_and_Lighttpd.html).

Our issue tracker is more for issues with the software itself. If you have issues with installing Ghost or setting up a proxy, please use the Slack channel. http://ghost.org/slack/ :)
