### ISSUE TITLE
Ability To Access Posts object in any context.

### ISSUE THREAD

**Issue by DanielTamkin** [TryGhost/Ghost#5669]
I'd be great to be able to loop through the posts anywhere, not just in `index.hbs`.

A great example is @TrentWalton 's website, [check it out](http://www.trentwalton.com). When you click on "Articles" It shows All his available posts. It'd be powerful(and super useful) if ghost could preform this feature as well.

This was [asked Quite a while ago](https://ghost.org/forum/using-ghost/15653-how-to-access-all-posts-within-post-hbs/) on the blog.

**Comment by ErisDS** [comment]
This is in progress, see the issue here: https://github.com/TryGhost/Ghost/issues/4439 and related PRs.

**Comment by DanielTamkin** [comment]
Glad to hear @ErisDS 
Hope backlog gets pushed soon
