### ISSUE TITLE
Support pattern matching for both posts with and without a date in the URL

### ISSUE THREAD

**Issue by diogogmt** [TryGhost/Ghost#5673]
Ghost already gives the option to pre-pend the date in the post URL, eg; http://myblog.com/2014/12/31/mypost as a configuration setting in the control panel. However, the URL pattern matching does not support both URL with and without dates.

I'll explain why supporting both would be a useful feature.
I initially had a blog being hosted in the free version of wordpress with the domain diogogmt.wordpress.com. I then moved to a self hosted version of ghost on digital ocean with the domain diogogmt.com
My blog was up and running for about 4 years on wordpress and I didn't want simply to shutdown. I then enabled the [site redirect feature](https://en.support.wordpress.com/site-redirect/) offered by wordpress.
The issue with the site redirect feature is that it doesn't allow the full post URL to be configured, only the domain and the slug can be changed but the date is part of the URL and can't be removed.

So my wordpress blog was redirecting to my ghost blog with the following URLs:
* http://diogogmt.wordpress.com/2014/02/05/mypost -> http://diogogmt.com/2014/02/05/mypost

The issue is that my ghost blog wasn't configured to pre-pend the date in the post URL so the redirects were unsuccessful.
I know I could enable the setting to pre-pend the date in the URL. However, I already published some posts in the new ghost blog without the date in URL and enabling that setting would break the URLs for them.

My proposed solution to the problem is to check for posts slug both with and without the date in the URL so if somebody access http://diogogmt.com/mypost or http://diogogmt.com/2014/05/15/mypost it would fetch the same post.

I've already have a patch with a fix and would appreciate some comments or even if there is a different solution for this problem.

Thanks.

**Comment by diogogmt** [comment]
I also have a [patch](https://github.com/diogogmt/Ghost/commit/dac5dd5d908dd02b6f1b7f370e9c14e7a4838673) against the stable branch

The URL http://diogogmt.wordpress.com/2014/02/05/cloudstack-4-2-x-loadbalancer-stickness-policies/ will be redirected to http://diogogmt.com/2014/02/05/cloudstack-4-2-x-loadbalancer-stickness-policies/

It is also possible to access the same post without the date in the URL: http://www.diogogmt.com/cloudstack-4-2-x-loadbalancer-stickness-policies/

**Comment by ErisDS** [comment]
Hi @diogogmt, I fully understand where you're coming from with wanting to be able to migrate, however, there are serious issues with the approach you've outlined. 

Firstly, serving duplicate content at multiple URLs is undesirable (even though Ghost mitigates this by including a canonical URL) and secondly, this approach assumes that the `/:slug/` & `/:year/:month/:day/:slug/` are the only possible URL patterns, when in fact Ghost supports many, many more. Alternatives are not accessible via the UI, but can be setup by modifying the DB. 

I think a much better solution is to add the extra rule you need to either apache or nginx - whichever you are using to host Ghost. It should be relatively straightforward to create a single pattern matching rule which finds URLs which include the date, and redirect to the version without the slug. If you need a hand doing this, why not drop by the #help channel on our [slack](https://ghost.org/slack) community?

**Comment by diogogmt** [comment]
@ErisDS can you please elaborate on why "serving duplicate content at multiple URLs is undesirable" ?

**Comment by kevinansfield** [comment]
https://moz.com/learn/seo/duplicate-content highlights a number of issues that search engines face with duplicate content and https://support.google.com/webmasters/answer/66359?hl=en lists a number of reasons details some ways to alleviate the issues.

On top of SEO problems, duplicate content will also play havoc with any analytics you may set up as traffic will be spread out across all of duplicate pages. Other problems may also arise further down the line as you now have more URLs to take care of whenever your site structure or underlying software changes.

**Comment by ErisDS** [comment]
Content duplicated across multiple URLs can cause confusion for search engines, social media & analytics... and then I saw @kevinansfield had already replied.

**Comment by diogogmt** [comment]
@kevinansfield @ErisDS so your suggestion is to set up a proxy in front of the ghost instance and apply some redirects rules based on the URL fomat?
Do you have an example to share?

**Comment by ErisDS** [comment]
@diogogmt if you are self-hosting Ghost & using a custom domain, you should already have a proxy setup in front of Ghost. The documentation is here: http://support.ghost.org/getting-started/#step-4:-advanced-configuration. 

If you need help, please visit the #help channel in Slack. GitHub is our issue tracker and we are not able to provide support here.
