### ISSUE TITLE
Bug: Setup breaks with invalid mail config

### ISSUE THREAD

**Issue by sebgie** [TryGhost/Ghost#5675]
### Issue Summary

Invalid mail configuration breaks setup at step 2.

### Steps to Reproduce

Prerequisite: Fresh Ghost installation, invalid mail settings
1. Go to `/ghost/setup/two`
2. Insert email, username, password and blog name
3. Press `Last Step: Invite ...`
4. Request times out and you are stuck in the setup process (pressing the button again says that the setup is already finished)

Console output:
```
ERROR: Error: connect ETIMEDOUT 
 Unable to send welcome email, your blog will continue to function. 
 Please see http://support.ghost.org/mail/ for instructions on configuring email. 
```

I assume that step three will show the same behaviour?
### Technical details

* Ghost Version: master - latest commit:  24b8605c5208c2fbdefb68fceb7db3662225ed4f
* Client OS: OSX
* Server OS: Vagrant
* Node Version: 0.10.36
* Browser: Chrome
* Database: Sqlite

**Comment by kevinansfield** [comment]
What details did you use for the invalid mail config? I tried this:

```
mail: {
    transport: 'SMTP',
    options: {
        service: 'Mailgun',
        auth: {
            user: '', // mailgun username
            pass: ''  // mailgun password
        }
    }
},
```

However that succeeded at step 2 then on step 3 I saw this:

<img width="836" alt="screen shot 2015-08-19 at 19 25 25" src="https://cloud.githubusercontent.com/assets/415/9365182/154f6c90-46a8-11e5-81ee-f0ffc6381d6a.png">

**Comment by acburdine** [comment]
I've seen this error sometimes too. The way I've been able to reproduce it is to simply not have a mail config exist. There seems to be an issue with direct mailing on my laptop, which might be what's causing the error.

At any rate, I think there should still be a check for it or something like that. I can take a look at this soon.

**Comment by sebgie** [comment]
My mail config is:

```
mail: {
        from: 'mail@email.org',
        transport: 'SMTP',
        options: {
              host: '10.0.0.1'
        }
},
```

There is no mail server on 10.0.0.1 so it times out. The issue is not reproducible with Mailgun because the service responds with an authentication error immediately.

@acburdine I think it has to do with waiting for a promise somewhere during setup?

**Comment by ErisDS** [comment]
I'm pretty sure it's this promise here?

https://github.com/TryGhost/Ghost/blob/master/core/server/api/authentication.js#L272

Removing the `return` statement prevents the mail sending from blocking setup, which makes sense I think? 

The default timeout for nodemailer's SMTP setup is pretty long, so if mail is misconfigured, this is pretty much expected. It may be possible to configure the timeout, but that would need to be part of the mail configuration you provide... catch 22.

If we remove the `return` from the mail sending on step 2, then you will run into the problem at step 3 if you try to invite any users. However, at that point setup is effectively complete & after the timeout a red alert does show an 'unable to invite user' error. Skipping the invite stage will work.

So it only gets you a little bit further, but that is a significantly better outcome & I don't see a downside?
