### ISSUE TITLE
Bug: Editor crashes in Safari OSX

### ISSUE THREAD

**Issue by JohnONolan** [TryGhost/Ghost#5676]
In Safari on OSX:

* New post
* Paste some text in as a title
* Click on main editor area

Whole editor view goes white / nothing happens until whole app is refreshed.

Console says: https://www.dropbox.com/s/egh3nt7piuv2smz/Screenshot%202015-08-17%2012.18.30.png?dl=0

**Comment by JohnONolan** [comment]
Seems to also happen inexplicably sometimes when editing a post

**Comment by kevinansfield** [comment]
I haven't managed to reproduce this, not sure if it's because I'm running Safari 9.0 (El Capitan) or because I'm not triggering it correctly.

![editor crashes in safari osx](https://cloud.githubusercontent.com/assets/415/9364795/feb25788-46a5-11e5-9ed4-37ad25378551.gif)

**Comment by ErisDS** [comment]
This sounds exactly the same as my last note in #5659, I couldn't find a way to reliably reproduce it. Now that some speculative fixes have been applied I'm keen to know if @JohnONolan can still reproduce?

**Comment by ErisDS** [comment]
Not been reproduced in a while, going to close for now.
