### ISSUE TITLE
Replace multiple spaces with a single one

### ISSUE THREAD

**Issue by markogresak** [TryGhost/Ghost#5677]
I have noticed that Ghost's markdown engine will leave all spaces as they are. Was this a conscious decision? I'm asking this because GitHub's markdown engine doesn't leave multiple spaces.

For example: 
```
I'm   a   :monkey:   typing   some   text.
```
Turns into: I'm   a   :monkey:   typing   some   text. 

When writing this post I've learned that this also happens when writing `inline   code`. The only case  where spaces stay as they are is in a code block.

**Comment by jillesme** [comment]
If this is an issue I'd love to fix it!

**Comment by markogresak** [comment]
It's actually a quite simple to fix it:

*I haven't checked the code, so I decided to use `postText` as a variable in the example.*
``` js
postText = postText.trim().replace(/\s{2,}/g,' ');
```

 - Trim to remove *all* leading and trailing whitespace. 
 - Replace all occurrences of 2 or more spaces with a single space.  

It's important to do perform this on markdown text, since it would otherwise break "4 spaces for code block syntax" (not sure how this is called).

**Comment by JohnONolan** [comment]
Yo, the editor is a hairy mess and things like this - while seemingly simple - tend to throw up a boatload of edge-cases when tested in concert with all of the other editor features (read: bugs). Bad news: We're very unlikely to address this specific issue in the current editor. Good news: We're starting work on a much larger editor overhaul soon which should eliminate this issue completely! :dancer:
