### ISSUE TITLE
Add article categories

### ISSUE THREAD

**Issue by guovz** [TryGhost/Ghost#5678]
Article category seems to be necessary,hope it will be contained future :smile:

**Comment by acburdine** [comment]
@guovz You can do article categories with tags :smile: 

Also, feature requests are better suited to ideas.ghost.org . The Github issue tracker is for issues with the software itself, not necessarily feature requests. Also, if you do submit an idea to the wishlist, you might want to describe a little more what seems to be necessary. :wink:
