### ISSUE TITLE
Symlinked config.js

### ISSUE THREAD

**Issue by src386** [TryGhost/Ghost#5679]
Hi,
Ghost is installed in /home/www/blog/app and works fine.
But I want to move config.js in /home/www/blog/conf/ :

    mv config.js ../conf/
    ln -s ../conf/config.js .

But when I want to run Ghost : 

    $ npm start --production
    > ghost@0.6.4 start /home/www/ghost/app
    > node index
    Migrations: Database initialisation required for version 003
    Migrations: Creating tables...
    Migrations: Creating table: posts
    ERROR: SQLITE_CANTOPEN: unable to open database file 
    Error: SQLITE_CANTOPEN: unable to open database file

It's not a permission problem, I can cat config.js.
Config.js is the only thing I moved.

Thanks.

**Comment by JohnONolan** [comment]
Hello! If you need help, please head on over to slack - https://ghost.org/slack/ - and post in the #help channel. This is a bug tracker for ongoing development of the Ghost software, and we're not able to do support here!
