### ISSUE TITLE
Cannot run the server

### ISSUE THREAD

**Issue by brunocascio** [TryGhost/Ghost#5686]
Hi!

I'm trying to run ghost, but i got this output:

```
npm start --production

> ghost@0.6.4 start /srv/celerative.com
> node index

ERROR: Ghost is unable to start due to missing dependencies:
  Cannot find module 'bluebird'
  Cannot find module 'lodash'
  Cannot find module 'sqlite3'

Please run `npm install --production` and try starting Ghost again.
Help and documentation can be found at http://support.ghost.org.
```

I ran `npm install --production` before, but doesn't work

Nodejs version: 0.12.7
NPM version: 2.11.3

**Comment by sebgie** [comment]
Hi @brunocascio and welcome to the Ghost issue tracker on GitHub!

It looks like `npm install` didn't work and you are missing some important dependencies.

Our issue tracker is more for issues with the software itself. If you have issues with installing Ghost or your environment, please use our Slack channel. http://ghost.org/slack/ :).
