### ISSUE TITLE
Regression: production build is not outputting the correct files

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#5695]
The `grunt` & `ember-cli` build tools are no longer generating all of the files needed to create a fully built version of Ghost.

`grunt init` should result in `ghost.css`, `vendor.css`, `ghost.js` and `vendor.js` being output to `/built/assets/`

`grunt prod` should result in minified versions of the same files: `ghost.min.css`, `vendor.min.css`, `ghost.min.js` and `vendor.min.js` being output to `/built/assets/` in addition to the non-minified versions

Currently, it seems that `grunt prod` is doing 2 things wrong:

1. it creates `ghost.css` instead of `ghost.min.css`
2. it completely overwrites all the other files in `/built/assets/`

The end goal is to end up with all 8 files so that these can be bundled into the release zip without the sources.

**Comment by ErisDS** [comment]
I have tracked the second part of this down to the changes made in #5382, specifically the addition of [these lines](https://github.com/TryGhost/Ghost/pull/5382/files#diff-61c1a4f257bf1d2f0858dbc2ae55d404R9) to remove the `/built/assets` directory before copying the files over. 

This means that we only ever get the files for either dev or production, and there's no way to do a release :wink: 

I see that if I comment out those lines I get errors about the files already existing, so I guess that's due to a change in how ember-cli works? It wasn't clear from reading through the thread on #5382 what changes there were or why - so if anyone has any hints I'd be grateful cc @acburdine @jaswilli @rwjblue 

As for the missing ghost.min.css, it seems the mythOptions aren't getting picked up properly, I'll continue investigating to figure out why.

**Comment by rwjblue** [comment]
I believe I have a fix for both issues, testing locally now to confirm.

**Comment by ErisDS** [comment]
:+1: :dancers:

**Comment by nicekiwi** [comment]
This is still an issue in v0.7.4. Following the instructions form the README, the quick-start does not work.

**Comment by ErisDS** [comment]
@nicekiwi, if you have questions about Ghost or need help, please head on over to slack - https://ghost.org/slack/ - and post in the #help channel (with plenty of details about the problem you're running into). There you can get help & support from the Ghost community.

**Comment by nicekiwi** [comment]
>_> helpful..

**Comment by ErisDS** [comment]
@nicekiwi saying "I have the same problem" as a bug fixed 6 months ago with no details gives us nothing to go on, and you're pinging everyone on this ticket. Come into slack and tell us what's wrong and we'll help.
