### ISSUE TITLE
Bug: Alerts are not displayed consistently

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#5707]
Whilst playing around with the new 'jQuery has been moved' notification, I noticed that alerts don't seem to appear consistently when navigating around.

Steps to reproduce:

1. Add a privacy setting to your dev config, something like:
     privacy: {
         updateCheck: false
     },
2. Checkout PR #5706, ensure your assets are built
3. Run `FORCE_MIGRATION=true npm start` to force run the migrations consistently - You should see `Migrations: Adding privacy notification` in the output
5. Login to your blog, you should see a blue alert
6. Navigate around, the alert disappears (it should stay)
7. Refresh on the content screen, it doesn't reappear
8. Refresh on the editor, it does reappear but with a flash
9. Dismiss the alert, it correctly never comes back again

Expected behaviour:

The alert remains at the top of the screen until such time as it is dismissed. Once dismissed it should not appear again.

**Comment by kevinansfield** [comment]
Ohh, this is quite likely a regression due to https://github.com/TryGhost/Ghost/commit/cbb106e12e72b8ccc9f6834098f395a534aad0f9

Should be a simple fix of changing https://github.com/TryGhost/Ghost/blob/master/core/client/app/routes/application.js#L43 from `notifications.closeAll()` to `notifications.closeNotifications()`. I'll add it to my todo list for today.

**Comment by ErisDS** [comment]
:+1:

**Comment by kevinansfield** [comment]
Now that notifications auto-close unless hovered and aren't filled with validation errors - do we need to force close any notifications/alerts here? Removing that line completely would alleviate side-effects where notifications may be displayed just before a transition has completed and then wiped out before the user has a chance to see them.

**Comment by ErisDS** [comment]
Very good point, I'd suggest not - the main reason for removing them on transition was to clear validation messages. @JohnONolan thoughts?

**Comment by JohnONolan** [comment]
Sounds good
