### ISSUE TITLE
Bug: Scrolling Gets Weird on Field Selects

### ISSUE THREAD

**Issue by dbalders** [TryGhost/Ghost#5716]
### Issue Summary

Device: iPhone 6

In the admin interface, if you open up a page, like menu, or general, when you select a text field and try to scroll, it is very eratic, the cursor moves with the page, and bottom of page is cut off.

![scrolling on field select](https://cloud.githubusercontent.com/assets/4715098/9456662/5c28be06-4a8f-11e5-9eeb-2fb8c9ebcd90.gif)

### Steps to Reproduce

1. Log into the admin interface on an iPhone\
2. Open a any setting menu, like general
3. Select a text field, and then try to scroll

### Technical details:

* Ghost Version: Master
* Client OS: Mac 10.10
* Server OS: Mac 10.10
* Browser: Safari Mobile
* Database: SQLite

**Comment by JohnONolan** [comment]
Looks like a bug in safari when using fixed position elements to me
