### ISSUE TITLE
Post-Zelda checkbox review

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#5728]
Two issues from the Zelda Audit, related to checkboxes, are considered non-blocking & therefore being punted to be looked at after Zelda is shipped (or after everything else has been fixed up):
- [ ] When checking/unchecking "use dated post urls" on settings/general - the scroll position changes - there is a space (padding/margin?) at the bottom of the page which appears and disappears. This is hard to debug because once you own developer tools, the problem goes away. Need to keep them open the whole time.

Mobile:
- [ ] Some janky behaviour with checkboxes - checking and unchecking boxes on settings/general occasionally renders all checkboxes on the screen unresponsive / in the wrong state

**Comment by kevinkucharczyk** [comment]
Is this still an issue? I can't reproduce these bugs.

**Comment by ErisDS** [comment]
Not seen any of these in ages, closing.
