### ISSUE TITLE
Support current versions of io.js

### ISSUE THREAD

**Issue by aexmachina** [TryGhost/Ghost#5734]
Is there any reason why `engines.iojs` in `package.json` contains such and old version of io.js? I'm happy to submit a PR which sets this to something more sensible like `"iojs": "~1.2.0 || ~2.0.0 || ~3.0.0"` if there's no reason why not.

**Comment by aexmachina** [comment]
I've just tested with iojs-v2.5.0 and it seems to be working perfectly.

**Comment by JohnONolan** [comment]
The answer to your question is but a single search away https://github.com/TryGhost/Ghost/issues/5271

**Comment by aexmachina** [comment]
Thanks. I did look BTW!
