### ISSUE TITLE
Sourcemap URLs are incorrectly given a trailing slash

### ISSUE THREAD

**Issue by oliverturner** [TryGhost/Ghost#5737]
### Issue Summary

The following declaration in CSS

```
/*# sourceMappingURL=screen.css.map */
```

Is being routed to '/assets/css/screen.css.map/' which obviously doesn't resolve since its a file not a directory.

### Technical details:

* Ghost Version: master (commit: 3a03f8fda90b16ccfcb62c20ac0bd6b22639e25a)
* Client OS: Mac OS X 10.10.5 (14F27)
* Server OS: Mac OS X 10.10.5 (14F27)
* Node Version: 0.10.40
* Browser: Chrome Version 44.0.2403.157 (64-bit)
* Database: SQLite

**Comment by ErisDS** [comment]
I'm not 100% on what's going on here - where are you seeing this source map URL?  Seems like it's related to a custom theme?

Ghost's redirect-to-slash behaviour happens after it has attempted to locate the original file and failed, e.g. it tried looking for an asset called `/assets/css/screen.css.map`, got a 404, so looked for `/assets/css/screen.css.map/` failed again and then returns a 404.

**Comment by oliverturner** [comment]
Hey @ErisDS it's ~~possible~~ certain that this is an artefact of my inexperience: yes, it's a custom theme I'm developing.

I assumed that path resolution is done at the router level - i.e. that specifying the theme in admin would cause its `assets` folder to be added to routes when resolving paths. If that isn't how it works - then that would explain a lot!
