### ISSUE TITLE
Escaped chars causing slug to be cut off

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#5746]
Had a [report in slack](https://ghost.slack.com/archives/general/p1440705186000825) that when entering the title 'Die deutsche Übersetzung von John Harpers Lasers & feelings ist fertig!' the slug being output was getting cut off at the ampersand, so was `die-deutsche-ubersetzung-von-john-harpers-lasers` instead of `die-deutsche-ubersetzung-von-john-harpers-lasers-feelings-ist-fertig`.

Same cut off happening with shorter strings and other chars like `?`, `%`, `$`.

Screenshot from network tab:

![ghost_screeny_title-slug-problem_chrome-console_network](https://cloud.githubusercontent.com/assets/101513/9534045/e2837718-4d0d-11e5-9f20-c8b39ac9a94c.png)

Shows that a second slug request gets set to type `octet-stream` instead of `xhr`

### Reproduction

Reproduction steps are unknown. Could not reproduce this on a Ghost(Pro) blog using mac or windows 7. Tried using a german keyboard layout as well.

### Technical details: 

* Ghost Version: 0.6.4
* Client OS: Win 10 & Antergos (Arch) Linux
* Server: uberspace hosting
* Node Version: 0.10.36
* Browser: Win 10 was Fx 41b, Linux is Fx 40.0.2 and Chrome

**Comment by thpanknin** [comment]
The report was by me. As agreed upon I'll try and reproduce the situation on other computers/devices. I have a tablet on which I can test this, too.

**Comment by thpanknin** [comment]
I tested this on my Android tablet which resulted in the same cut off slug, sadly. Asking a friend to test it on his computer, too, but I have the feeling that the problem lies somewhere within my installation.

**Comment by ErisDS** [comment]
No reproduction case has been found for this, suggesting it's specific to the environment of this blog. I'm going to close this for now and we can reopen if more people experience the issue or if some idea of how to reproduce outside of this blog is found.
