### ISSUE TITLE
Sessions randomly expire

### ISSUE THREAD

**Issue by sebgie** [TryGhost/Ghost#5751]
Somewhere during implementing 0.7 sessions started to expire earlier than before. I think I have track this down to access tokens not being refreshed. I have opened an issue for ember-simple-auth and it would be great if anyone who has experience with ember/authentication could please have another look at our implementation.

Issue on ember-simple-auth: https://github.com/simplabs/ember-simple-auth/issues/644

Relevant Ghost PRs:
- https://github.com/TryGhost/Ghost/commit/e9326f6f6e02ddd770d6fdee12f6b963cedb9200
- https://github.com/TryGhost/Ghost/commit/5e7ff4031803935a44553d276c6f8b71a23064c1

**Comment by ErisDS** [comment]
Fixed by #5751/ 62684df - closing
