### ISSUE TITLE
Revisit bulk user invites in step 3 of onboarding flow

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#5753]
Currently, our API doesn't support bulk user invites. Therefore, the invites functionality has been implemented using ember store to create one user at a time.

This works OK, except we currently don't seem to get full access to the errors from the server to give the user a good indication of why the invite failed.

It may be that a slightly different approach in Ember will work better, it may be that we need to implement bulk invites at the API level to get this working nicely.

There are, in short, two main reasons why an invite would fail: 1) email configuration error (all invites failed) and 2) incorrect email addresses bouncing back, resulting in a some of them failing. We need to receive enough information from the server to determine which of these cases has occurred & let the user know.

**Comment by cwonrails** [comment]
Replicated. Invited three valid emails, no invites sent or received. Testing environment: node v0.12.7, OS X 0.11, Chrome Version 44.0.2403.157 + Ubuntu Vagrant VM in Arch Linux.

![terminal output after team email onboarding](https://cloud.githubusercontent.com/assets/4729979/9562692/24374b2c-4e39-11e5-9417-0b13060ccb94.png)

Users could very well not know about the failure until checking with team members to confirm.

**Comment by cwonrails** [comment]
Exact steps:

1. `npm start` after standard install from master branch
2. Opened at `localhost:2368`, went through first two steps of onboarding successfully.
3. During third step added three correctly formatted email addresses.
4. Told that the invites failed.
5. Logged in, made a few posts. Emails still not sent.
6. Halted local server.
7. Edited config.js to include my own email setup.
8. Restarted server.
9. Went to team section, email invites listed as having failed.
10. Clicked resend to all three addresses, emails received quickly.
11. Time where invitations were sent listed incorrectly in the UI (in this case '24 minutes ago.')

**Comment by ErisDS** [comment]
I think this can be left as is for now, we can revisit this if it becomes an issue.
