### ISSUE TITLE
Add review post state

### ISSUE THREAD

**Issue by jonblack** [TryGhost/Ghost#5765]
A post can be in one of two states: `draft` or `published`. I'd like to propose adding an additional `review` state. I have two rough use cases below:

* As a writer I'd like to mark a post as being ready for review by an editor so that the editor is aware the post has been finished.
* As an editor, I'd like to see a list of posts that are ready for review so I can easily find posts that need to be reviewed.

Even in situations where the editor and writer are the same person, this still helps organise posts in my opinion. I'm interested to know what the Ghost team thinks.

**Comment by HoddzDJ** [comment]
I could see this being really useful, just by the two use scenarios you have applied. No doubt there will be even more though! I have so many draft posts, and most are already finished it's just a pain to find them to publish them, so I myself would use this for sure.

**Comment by ErisDS** [comment]
@jonblack & @HoddzDJ - really appreciate your suggestions. Could you please submit them to the [wishlist](http://ideas.ghost.org) instead of GitHub? There we can measure traction across a wider audience - you can access the wishlist direct from the admin panel.

**Comment by jonblack** [comment]
I've added this to the wishlist: http://ideas.ghost.org/forums/285309-wishlist/suggestions/9596856-add-review-post-status
