### ISSUE TITLE
Regression: Post editing shortcuts broken

### ISSUE THREAD

**Issue by JohnONolan** [TryGhost/Ghost#5767]
No longer working on content mgmt:

* Double click to edit post
* [Enter] to edit post

I would guess, related to #5752. Do we not have tests for these?

Tested both latest safari/chrome for Mac

**Comment by ErisDS** [comment]
Yeah I noticed this over the weekend & added it to the Zelda audit. I think it's a simple oversight on my part - I didn't read through #5752 closely enough & a bit of code was removed that ought not to have been. Got it working again locally just need to test across mobile

**Comment by kevinansfield** [comment]
Sorry, I'd taken those actions out as I couldn't get them to trigger - the {{link-to}} inside was swallowing the clicks whilst I was testing unless that was a hangover from some other methods I was trying out.

**Comment by ErisDS** [comment]
Hmm, if I put them back in, double-click works, `cmd+backspace` works, but not `enter, o`

**Comment by JohnONolan** [comment]
Possible that enter was already broken before... it should work though, ideally

**Comment by ErisDS** [comment]
Yeah I just tested a version from a while back - enter & o have been broken for a while - looking at why.

**Comment by kevinansfield** [comment]
From a quick check I'd suggest it may be because the `o, enter` shortcut doesn't pass a model through to the `openEditor` action.

Changing `openEditor` in `routes/post.js` to use `this.get('model')` instead of a passed in post object should work.

**Comment by ErisDS** [comment]
Good shout
