### ISSUE TITLE
User search dropdown doesn't appear on mobile

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#5774]
User search added in #5759 is working fabulously on desktop, but on mobile I don't see the dropdown.

The tag component dropdown works fine, so I'm guessing this is a css z-index style issue?

Tested on safari & chrome on my iPhone 6

**Comment by kevinansfield** [comment]
I'll test this out, if it's not css there may be some relation to #5772.

**Comment by kevinansfield** [comment]
Unable to reproduce on my iPad running iOS 9 in either portrait or landscape. I don't think it's a css issue either as I can't replicate the problem when resizing desktop browsers to mobile widths.

![img_0521](https://cloud.githubusercontent.com/assets/415/9601029/b1d2a03a-5096-11e5-80e1-d5503f31e2cb.PNG)
![img_0522](https://cloud.githubusercontent.com/assets/415/9601030/b1f7e854-5096-11e5-9143-532f7b1c8519.PNG)

**Comment by JohnONolan** [comment]
Cannot reproduce. Only issue I see is that the search results can't be scrolled on mobile, which is an edge case I can live with for this release

**Comment by kevinansfield** [comment]
Tested on my ancient iPhone 4 running iOS 7 and the search works but I don't get the mobile menu and I can't close the normal nav menu.

**Comment by JohnONolan** [comment]
nah we're definitely not supporting iOS7 with iOS9 a few days away

**Comment by ErisDS** [comment]
Upgraded my phone to the latest 8.4.1 and the issue is gone. Closing.
