### ISSUE TITLE
Ubuntu ghost init 

### ISSUE THREAD

**Issue by tomhowson** [TryGhost/Ghost#5781]

**Comment by tomhowson** [comment]
Hi,

On unbuntu 12.04 the upstart script crashes seeming once a day. I can't understand why. All suggestions welcome.

**Comment by ErisDS** [comment]
Hi @tomhowson, sorry to hear you're having trouble. If you need help, please head on over to slack - https://ghost.org/slack/ - and post in the #help channel. This is a bug tracker for ongoing development of the Ghost software, and we're not able to do support here!

**Comment by tomhowson** [comment]
Hi @ErisDS,

Thanks for your reply. I will get myself setup on slack. As it happens I found the issue, I did not have a swap partition setup. I wrote a general guide for anyone who setups ghost manually and hits a similar issue in the future. http://www.howson.me/2015/09/06/adding-a-swap-partition/

Thanks,

Tom.
