### ISSUE TITLE
Implement subresource integrity checking on all third party assets.

### ISSUE THREAD

**Issue by SushiDude** [TryGhost/Ghost#5787]
As of Chromium version 45, the subresource integrity mechanism has been implemented.

Please read: https://googlechrome.github.io/samples/subresource-integrity/index.html

Use SHA-512 as it is not only more secure than SHA-256 but also significantly more performant on 64 bit processors. It is also listed as the preferred algorithm in the specification.

This report also applies to Casper.

**Comment by ErisDS** [comment]
I think the only 3rd party asset linked in Ghost is jQuery and that has effectively been removed. Therefore I don't think this is really relevant to Ghost?
