### ISSUE TITLE
Modals refactor

### ISSUE THREAD

**Issue by kevinansfield** [TryGhost/Ghost#5798]
During the Zelda release we ran into issues with modals and their interaction with validations and spin-buttons. One of the main problems is that hitting the confirm button will raise an action and then close the modal immediately, not taking into consideration async tasks or allowing the close to be halted.

- [x] Review of modal usage and desired behaviour
- [x] Switch to closure-actions and return promises from modal controller actions so that closing of modals can happen after async tasks and be dependent on success/failure
- [ ] #6061 re-instated the re-authentication modal but I realised there's an issue with it not saving the post after re-authenticating. It would be good to add that feature if the improved control structure allows it.
- [ ] Modals should switch the keymaster scope to disable globals shortcuts and provide a way to register their own shortcuts (currently always switches to 'modal' scope - can we offer a way to customise?)

**Comment by ErisDS** [comment]
Note: once the refactor is complete it should be possible to revisit #5650

**Comment by acburdine** [comment]
Did this get fixed by #6088?

**Comment by ErisDS** [comment]
Closing for now - if there's any work left to do maybe open a fresh issue?
