### ISSUE TITLE
{{current}} Helper in Navigation doesn't work as intended with absolute links

### ISSUE THREAD

**Issue by yyli** [TryGhost/Ghost#5801]
If in the navigation admin you type the url as:

``TestPage - https://blog.site/testpage/``

instead of 

``TestPage - /testpage/``

Then in https://github.com/TryGhost/Ghost/blob/master/core/server/helpers/navigation.js where the line (48 in the current master):

```javascript
out.current = e.url === currentUrl;
```

``currentUrl`` is ``/testpage/`` where as the stored database entry is ``https://blog.site/testpage/`` resulting in ``e.url`` being ``https://blog.site/testpage/``. which ends up with ``out.current`` being false.

While reading the documentation I didn't find anywhere that said we had to use ``/slug/`` convention. This is problem number 1.

Problem 2 comes when the admin site for navigation will change the ouput of ``/slug`` to look like `` https://blog.site/slug/``. The problem here is that if you click on this text box and make no changes, and click save (the situation is if I click on an old menu link and edit a different one and save it), then it will store ``TestPage - https://blog.site/slug/`` into the database causing the comparison the the current url to fail.

I'm not sure if this is a real problem or if it somehow is only manfesting in my system, however with my limited this is as much as I can dig into the problem. It is probably due to ``currentUrl`` being assigned by ``options.data.root.relativeUrl``.

It seems that the check should be more than a single ``==`` however I'm not sure how to improve it. My current fix is to just change back the navigation ones that do not work (which is frustrating because you can't tell from the navigation admin menu which ones would be problematic).

**Comment by ErisDS** [comment]
This was fixed by #5843 / 5208970
