### ISSUE TITLE
Feature: Quick edit

### ISSUE THREAD

**Issue by ConnorKrammer** [TryGhost/Ghost#5806]
It's currently very action-intensive to change anything about a post. This is an issue if you're doing something that, while simple in theory (e.g. add tags to all posts about cuisine), instead turns out to take at least 6 clicks/post. Here's the current process, using the tag example for reference:

**Select post > Edit > Gear icon > Select tag field > Enter new tag > Hide sidebar > Update post**

Six of those seven steps require the user to click, excepting the case where the desired post was already selected which saves a step. To use another example, even just publishing a draft takes quite a few actions:

**Select draft > Edit > Change action to "publish" via dropdown > Publish**

I imagine something like the quick edit feature from WordPress would be very useful in cutting down how many steps are involved in making changes like the above.

**Comment by HoddzDJ** [comment]
You can cut down the Select post > Edit step straight away. Just double click the post. Something I only recently found out mind you.

**Comment by ConnorKrammer** [comment]
@HoddzDJ Ah, you're right about that. It does reduce the minimum number of actions by one, though it doesn't reduce the number of clicks required.

**Comment by ErisDS** [comment]
Hi @ConnorKrammer, please can you put this feature request on the [wishlist](http://ideas.ghost.org), rather than here on GitHub. That allows us to measure traction and prioritise accordingly, thanks :)

**Comment by ConnorKrammer** [comment]
@ErisDS Will do. The contribution guidelines [left it somewhat open](https://github.com/TryGhost/Ghost/blob/master/CONTRIBUTING.md#features) whether I should put it here or on the wishlist, so I put it here because it seemed somewhat relevant to the recent Zelda UI changes. I'll post this on the wishlist.
