### ISSUE TITLE
Bug: Error 500 for author/tag with illegal character

### ISSUE THREAD

**Issue by sebgie** [TryGhost/Ghost#5808]
### Issue Summary

Trying to visit the tag (`/tag/<tag>`) or author (`/author/<author>`) page with a slug value that contains an invalid character ($, ", §, ...) results in 500 internal server error.

### Steps to Reproduce

1. Visit `<your blog url>/tag/<existing tag>/` -> tags page is shown
2. Visit `<your blog url>/tag/<non existing tag>/` -> 404 page is shown
3. Visit `<your blog url>/tag/<non existing tag with $ character in it>/` -> 500 page is shown

This is a bug because step 3 shouldn't return a 500 internal server error. I would assume a 4** error since the error page is triggered by a faulty user input. There are 2 option to handle that error in my opinion.

1) return 422 validation error
2) remove the illegal characters and redirect to 404 if the tag doesn't exist

### Technical details

* Ghost Version: 0.7.0
* Client OS: OSX
* Server OS: Vagrant
* Node Version: 0.10.40
* Browser: Chrome
* Database: SQLite

**Comment by Gargol** [comment]
Would love to tackle this one if that's ok. Think returning 404 makes the most sense for this scenario.

**Comment by ErisDS** [comment]
@gargol, sorry for not replying to this - I missed your comment. If you're able to figure out a fix for this then I'd love a PR - we're aiming to get all the bugs marked `blocker` fixed before next week's meeting (22nd).

**Comment by Gargol** [comment]
Hi @ErisDS, this one just needs some more e2e tests and maybe some discussion about what the best way to handle it is. current version 'just works', but maybe somebody has better ideas. Will try to find some time to push it somewhere this week.

**Comment by ErisDS** [comment]
I've raised a PR which fixes the validation being too strict - just a note that this does need to be fixed at the API level, I'm not sure if that's clear from the issue :)
