### ISSUE TITLE
Ghost Marketplace: Dead Themes

### ISSUE THREAD

**Issue by agh** [TryGhost/Ghost#5809]
I was just browsing through the Ghost Marketplace, and happened upon quite a lot of themes where the links (click through) simply don't work. This appears to apply to both free and paid categories.

  http://marketplace.ghost.org/themes/paid/

This one in particular I thought would be worth a look:

![](http://i.imgur.com/L8jQ5Pc.png)

So you click on [the link hoping to learn more](http://ducentis.ghost.io) and you're bounced through to a "Suspended" (https://ghost.org/suspended) page, which is the best case, in many others you are taken away from the Ghost ecosystem and hosting to a third-party which also doesn't give you a theme.

This feels like a somewhat suboptimal user experience.

I'd propose that at a minimum we should consider:

 * [ ] Following all the links on Ghost Marketplace to look for HTTP 404.
 * [ ] Where the follow-on site is hosted on Ghost, make sure it isn't suspended.
 * [ ] Support reporting functionality ("This doesn't work!") with an element of human review.

If a link is found which doesn't seem to work any more, or if reports come in claiming that to be the case, there should be a means to retain the entry in the catalogue for a period of time (i.e. 90 days) but have it disappear from the Ghost Marketplace. Reinstatement would occur if the original issue was fixed and without needing to go through any submission process again.

**Comment by JohnONolan** [comment]
@agh thanks for reporting this. The marketplace is a massive project which requires far more than just thew few things listed here. If you want to go through an compile all the dead links for some cleanup, by all means, but beyond that I'm afraid we're not going to track this in the ghost repo as we don't have resources to work on it at the moment.
