### ISSUE TITLE
When trying to upgrade, I get this error : ERROR: SQLITE_ERROR: too many SQL variables

### ISSUE THREAD

**Issue by THPubs** [TryGhost/Ghost#5810]
I tried to upgrade ghost to the latest version and got an error when trying to start the service :

    leafh8kfns@leafymain:~/techhamlet.com$ sudo npm start --production

    > ghost@0.7.0 start /home/leafh8kfns/techhamlet.com
    > node index

    Migrations: Database upgrade required from version 003 to 004
    Migrations: Creating database backup
    Migrations: Database backup written to: /home/leafh8kfns/techhamlet.com/content/data/tech-hamlet.ghost.2015-09-07.json
    Migrations: Populating default settings
    Migrations: Complete
    Migrations: Updating fixtures
    Migrations: Upgrading fixtures to 004
    Migrations: Update isPrivate setting
    Migrations: Update password setting
    Migrations: Update ghost-admin client fixture

    ERROR: SQLITE_ERROR: too many SQL variables 
     
     Error: SQLITE_ERROR: too many SQL variables
        at Error (native) 

    leafh8kfns@leafymain:~/techhamlet.com$

**Comment by ErisDS** [comment]
For anyone else coming across this, there is a patch sat in #5817 which appears to resolve the issue, although it is very slow.
