### ISSUE TITLE
Documentation for Frontend API

### ISSUE THREAD

**Issue by VitaliyR** [TryGhost/Ghost#5811]
Hello.

When I developed a theme for ghost I want to load blog posts in some container (div) via ajax calls. I've not found any of articles how to do that. 

What I have right now - I'm making a query to /page/@page_number and pass it to semi-shadow-DOM where I'm query for articles and put them into real DOM. 

I've found only the link to API which is describing some routes which are starts from /ghost - so requires an auth. 

But what if I just need to 'grab' public data which is doesn't requires auth? Is there some way to do it? Or maybe there are some docs for that?

**Comment by ErisDS** [comment]
Hi @VitaliyR, this is our bug tracker for issues with the Ghost software. If you have questions and want to talk about how to do things with themes, please use the #themes channel in our [slack](https://ghost.org/slack) community.
