### ISSUE TITLE
0.7.0 change url starting with hyphen

### ISSUE THREAD

**Issue by toblerone1963** [TryGhost/Ghost#5812]
Hi,

Yesterday I upgrade Ghost, but some problems force me to back up and reinstall all. 0.7.0 is very nice (thank you very much !), but the [new url builder](https://github.com/TryGhost/Ghost/commit/2700bfa) modify url starting with hyphen (example from my blog : http://epris-de-justice.info/-si-elle-se-tient-a-carreaux-je-veux-bien-rester/ is 404 and the new url is http://epris-de-justice.info/si-elle-se-tient-a-carreaux-je-veux-bien-rester/). It's not a problem for new article, but for the old ones it' breaks all links from the outside (social media & all).

Can it be possible to add one hyphen manually ?

Thanks for all,
Cosme

**Comment by ErisDS** [comment]
Hi @toblerone1963, this is a pretty hairy bug. Can you provide some more details about how the slug (the end part of that url) got changed? Did you edit the slug or just the post?

**Comment by toblerone1963** [comment]
Sorry, I forget.

I imported (via Lab) the back up (0.6.4) on my new server (0.7.0)
(totaly my bad u_u")

Le mardi 08 septembre 2015 à 11:01:25, Hannah Wolfe a écrit :
> Hi @toblerone1963, this is a pretty hairy bug. Can you provide some more
> details about how the slug (the end part of that url) got changed? Did you edit
> the slug or just the post?
> 
> —
> Reply to this email directly or view it on GitHub.*
> 

-- 

Cosme Buxin
06 95 39 68 85
@cosme_buxin

**Comment by toblerone1963** [comment]
Hi,

I may have find a solution.

First I thought using [this technique](http://knolleary.net/2014/01/26/changing-ghost-permalinks-without-breaking-everything/), a bit long and crafty.

But a better solution seems to use [this middleware](https://github.com/saulshanabrook/custom-redirects) to automatically redirect slug starting with new forbidden characters to the new slug.

Sorry, I don't have the time at the moment to test that, so… best luck ! :)

**Comment by ErisDS** [comment]
closed by c0b5de6 / #5866
