### ISSUE TITLE
Sometimes post editor stops writing

### ISSUE THREAD

**Issue by Galaxy42** [TryGhost/Ghost#5813]
I just updated my blogs to Ghost 0.7. You'll have done a great job with this version, congratulations!

I'm here because while I was writing a few post sometimes, a letter doesn't work, like if my keyboard doesn't have enough battery(its a ghost bug, I've checked it), for example if the "o" gets wrong you can write any one. So you have to refresh the page.

**Comment by kevinansfield** [comment]
This sounds like the keyboard shortcuts for the content management screen (`c` creates a new post, `o` or `enter` opens the selected post, etc) are sometimes not being disabled correctly when transitioning to the editor.

Have you noticed any particular routes through the admin area or sequence of actions that cause the problem?

**Comment by kevinansfield** [comment]
This has just been reported again in Slack.

I have a feeling it's related to the search bar. I've not been able to prove it yet but I think the issue may be that occasionally when leaving the content management screen whilst the search bar is focused the `removeShortcuts` method is being called before keymaster has been switched back to the default scope.

**Comment by Galaxy42** [comment]
Great! The problem that I'm talking about was caused while I'm writing the post. I've to install the new version to see if the bug is solved. But I hope so :)
