### ISSUE TITLE
Bug: Editor Crashes

### ISSUE THREAD

**Issue by cobbspur** [TryGhost/Ghost#5822]
### Issue Summary

The editor crashes if you have an image with a relative url in markdown form followed on the same line by a URL in brackets.
### How to Reproduce

Go to editor 
Add `![]()` to bring up an image dropzone and add image of your choice - some cats perhaps...
After this - on the same line add a link to something in brackets

Like this:

![](http://puu.sh/k5qLB/2dbb649680.png)
_The editor crashes when you add the closing parenthesis_

This is a bug because... although the markup may not be valid it should not be so easy to completely break the editor and if a post is imported you cannot edit the post without directly editing the database.
### Technical details
- Ghost Version: master - latest commit:  c8dd095
- Client OS: Mac and windows 7x64

**Comment by lcamacho** [comment]
This is a problem with the regexp that showdown-ghost uses, @ErisDS are you going to change to showdownjs in the near future?

**Comment by ErisDS** [comment]
Yep, working on it

**Comment by narayand4** [comment]
Hi, @ErisDS Same issue with me but after add a carriage return it's working fine. It happens only if we continue without any carriage return.
