### ISSUE TITLE
Ghost Theme dev : Question

### ISSUE THREAD

**Issue by di48l069** [TryGhost/Ghost#5827]
Hi there, sorry if im posting this question in the wrong place, how would i go by testing a ghost theme will i have to install ghost on my local machine and develop my them or does someone know any other way?

**Comment by stpe** [comment]
Yes, this is the wrong place. See http://support.ghost.org/ for the right place - Slack or Forum.

The answer to your question is here: http://themes.ghost.org/docs/getting-started
