### ISSUE TITLE
Bug: Unable to delete, save draft or access post settings on smaller size screens.

### ISSUE THREAD

**Issue by cbanowsky** [TryGhost/Ghost#5832]
### Steps to Reproduce

1. Make your screen 15 inches or less

This incident makes it impossible to delete a  post or access post settings including  saving drafts.
### Technical details

* Ghost Version: 0.70
* Client OS: Ubuntu 14.04
* Server OS: Ubuntu 14.04
* Node Version: 0.10.33
* Browser: Chrome

It appears the latest UI changes have had an effect on the responsiveness of the client application.

**Comment by kevinansfield** [comment]
Hi @cbanowsky, are you able to provide a screenshot at all? Chrome version and actual screen resolution would also be useful too, thanks.

I always work with non-maximised windows on a 1440x900 screen and have had no trouble in chrome/safari at any window size from mobile widths to full-screen. Firefox does have an issue if you are editing a post with very large images but we have a fix ready for the next release.

**Comment by cbanowsky** [comment]
I will have to replicate on my laptop later.  That is where the issue 
occurred.

Best,
Cameron

**Comment by ErisDS** [comment]
I am also unable to reproduce this, except with the open `<pre>` tag bug mentioned [here](https://github.com/TryGhost/Ghost/issues/5804#issuecomment-139917580)

There may be another similar case, whereby this is specific to the content in the editor. @cbanowsky please can you see if you can narrow it down?

**Comment by cbanowsky** [comment]
Yes. I need to get it on my laptop's smaller screen. Let me work on this today and I'll have detailed instructions on how to reproduce. Sorry I went awol. Been busy with the projects. 

Ghost has been important from the start and want to make sir it's solid. 

Cameron

**Comment by ErisDS** [comment]
ping @cbanowsky :wink: 

There's a bit discussion around a similar issue to this over here: https://github.com/TryGhost/Ghost/issues/5804 Hopefully we've captured the problem and have a fix coming, but without your repro steps we can't be sure. Would be great to hear back from you about this.

**Comment by cbanowsky** [comment]
I was running Canary Chrome, since then installed Ubuntu to avoid the 
headache of Windows.  I have yet to reproduce and will work on doing so.

**Comment by ErisDS** [comment]
I'm going to assume this was fixed along with #5804. If that's incorrect please post reproduction steps and we'll reopen.
