### ISSUE TITLE
Admin UI: Featured posts

### ISSUE THREAD

**Issue by ConnorKrammer** [TryGhost/Ghost#5833]
Before the Zelda update, featured posts were clearly marked with a star in the admin UI and were easy to find. This aspect of the UI appears to have been removed, making it impossible to tell which posts have been featured without going through **Select Post > Edit > Gear Icon > Featured Posts** for each post until they're all found. (Alternatively, if your theme treats featured posts differently than normal ones, they can be discovered through the frontend -- but it seems odd that that's easier than using the specifically-designed backend.)

I'd also like to propose that featured posts be pinned to the top of the admin content list, either by default or through preference; it's obviously not a highly necessary change, but it's nice to see them all in one place. If not that, then making featured posts searchable through the new admin search bar would be very helpful.

**Comment by novaugust** [comment]
Thanks for pointing that out Connor. I'm pretty confident the removal was an accident, and am looking into it :)

------------

The `.featured` class is still being appropriately applied to the `<li>` representing the post, looks like the css referencing it got cleared out though.

**Comment by JohnONolan** [comment]
This was removed intentionally as the featured-post UI was largely very unhelpful clutter (it's not a feature which is used very much atm). Will be reviewing this again in future to come up with a more comprehensive approach.
