### ISSUE TITLE
Upgrade from 0.6.4 to 0.7.0 issue with login

### ISSUE THREAD

**Issue by MunGell** [TryGhost/Ghost#5837]
Hey guys,

Just a quick note, I got an issue with logging in into admin interface after I upgraded my blog to 0.7.0 from 0.6.4.

I am not sure if it is a legit bug or specific issue of my installation, but just in case anyone gets the same problem:

The solution is to change `secret` field in `clients` table in database to be `not_available` for both admin and frontend.

If this change is intentional, can we put some script, so it will be done automatically on upgrade?

Many thanks!

**Comment by ErisDS** [comment]
Hi @MunGell, sorry to hear you ran into this bug. It's already known and has an open PR: #5815 - you should not change your secret to be `not_available` - it should be a random 12 digit hex string.

**Comment by MunGell** [comment]
Thank you, waiting for the resolution then

**Comment by cdupoiron** [comment]
+1 for the fix :)

**Comment by cdupoiron** [comment]
Hi again,
I tried to change 'secret' field in clients table in database to be 'not_available' for both admin and frontend but I can't login anymore either. What could i do to fix it? I just received an 401 unauthorized.

**Comment by ErisDS** [comment]
One of 3 things:

- change your secret to a valid 12 digit hex string
- apply the patch linked to the original issue #5815 - patch: #5818
- wait for us to release a new version of Ghost and then upgrade again (coming soon).

If you need further support, please drop by our [slack](https://ghost.org/slack) team.
