### ISSUE TITLE
Add ZenHub to readme?

### ISSUE THREAD

**Issue by feluraschi** [TryGhost/Ghost#5846]
Hey, I'm on the ZenHub.io team. I noticed this repo uses ZenHub task boards to organize issues.

To help contributors know to check the task boards for current priorities, what do you think about adding the ZenHub badge to your ReadMe (or adding a mention to your contributor guidelines)? I'm happy to create a PR. A lot of people don't know ZenHub is free for open-source users :smile:

Thoughts?

**Comment by ErisDS** [comment]
Hi @feluraschi, I'm afraid we're not actually using it. I tested out the new version for about 10minutes the other day and have it installed, but we haven't used it properly in over a year.  Worth noting, I scoured the site the other day looking for info on whether it was free for OSS and couldn't find that info :wink:
