### ISSUE TITLE
Dependencies out of date.

### ISSUE THREAD

**Issue by envygeeks** [TryGhost/Ghost#5847]
Ghost still seems to request a very outdated version of node that no longer uses the current semantic version scheme (4.1.0) which results in a warning upon install and SQLite3 is broken on 4.1.0 which can result in a bad build on Alpine Linux.

**Comment by novaugust** [comment]
NodeJS 4.0.0 was released ten days ago. I wouldn't quite go so far as to say that makes 0.12 "very outdated"

Anyhoo, this is a duplicate of #5821. Please do a search before creating an issue to avoid creating duplicates. Thanks!

**Comment by envygeeks** [comment]
If it's not the latest version it's very outdated.  Rapid development is rapid, slow development is slow.
