### ISSUE TITLE
i found some err in "Ghost/core/client/app/html/themes.html"

### ISSUE THREAD

**Issue by dolonfly** [TryGhost/Ghost#5855]
the stylesheet location you use a absolutely path:
file:///Users/John/Sites/Ghost/core/built/assets/vendor.css
and 
file:///Users/John/Sites/Ghost/core/built/assets/ghost.css

**Comment by ErisDS** [comment]
Those files are used as the basis to build out other pages in Ember - the asset paths don't need to be correct :wink:
