### ISSUE TITLE
Utilize Transactions in Data Operations

### ISSUE THREAD

**Issue by gotdibbs** [TryGhost/Ghost#586]
SQLite has to open a file every time it does a single transaction thus anywhere we do any chaining of operations we should probably be doing them inside of one single transaction to increase performance. This should significantly improve performance of our migrations at the very least.

Bookshelf/Knex appears to provide this functionality already (see: http://bookshelfjs.org/#Bookshelf-Transaction).

**Comment by jberkus** [comment]
SQLite's transactional DDL supports multistatement DDL, if that's what you're asking.

**Comment by ErisDS** [comment]
This issue has never gotten traction, going to close it for now. If anyone has ideas for specific changes that would be great.
