### ISSUE TITLE
Upgrading to 0.7.0 leading to 404ing posts

### ISSUE THREAD

**Issue by benheb** [TryGhost/Ghost#5860]
Hello – I'm wondering if something fundamental changed about how posts are retrieved from the db in 0.7.0? I did the update locally, and everything works great, except when I click to go to an individual post page. The new admin UI works, the homepage list of posts work, /tag works, etc. 

However, when I visit /month/day/year/:post I get a 404. 

In my configuration, I changed the sqlite3 db "settings" table "permalink" record to include "/blog" before the slug. So it's: `www.domain.com/blog/month/day/year/some-post-id`. This has always worked, and is the only thing that I can think of that may be causing issues as I've changed nothing else. 

![404_ _page_not_found](https://cloud.githubusercontent.com/assets/910495/10026372/a57e5cfa-611e-11e5-91c0-613712a043e0.jpg)

Looking at core/server/api/posts.js, it looks like things changed here in how the lookup is made, now using modelQuery (which at a tertiary glance appears to be successfully retrieving the post from the db). Is this the right place to go looking? Or what would cause the "Page not found" error. It appears as though if the post itself was not found, the error "Post not found" would be thrown? 

Here is a look at the db, first showing the posts table with the post "one-more" showing (404 image above) and below the settings table where i've added the "/blog" to the permalink, the only manual edit I've made to the db. 

![1__sqlite3](https://cloud.githubusercontent.com/assets/910495/10026505/647e74fa-611f-11e5-8d48-3c4da57771bb.jpg)

Lastly, I've done several version updates before (currently on 0.6.4) and this has never been an issue. 

Any help / ideas would be MUCH appreciated. Really want to get the new admin interface up and going. 

Thanks.

**Comment by ErisDS** [comment]
Hi @benheb I'm sorry to hear you're having trouble. I'm not able to reproduce the issue you're describing - I set my permalink setting to `/blog/:year/:month/:day/:slug/` my url in config.js is `http://localhost:2368` and navigating around the blog is working as expected. I even tried reproducing with a post that has the same month & day as shown in your example and am still not getting a 404. 

There must be some other factor involved here, I'd recommend swinging by the #help channel in [slack](https://ghost.org/slack) where it's easier to provide direct support and I'll reopen this if there does turn out to be a bug in Ghost.

**Comment by sysforensics** [comment]
Was there a solution to this?  Having the same issue.  Went from 0.6.4 -> 0.7.0 and now getting 404s.  If I revert to 0.6.4 it works fine.

**Comment by benheb** [comment]
@sysforensics did you configure custom permalinks as I did? I can't remember exactly... but the I _think_ resolution might have been that my original permalink was `/blog/:year/:month/:day/:slug` but when updating to 0.7.0 it needed a trailing slash, otherwise it 404'd: `/blog/:year/:month/:day/:slug/`. If that doesn't help you maybe I can look a little closer and try to remember if there was something else too...

**Comment by sysforensics** [comment]
I have some custom permalinks as a result of porting issues.  I also have a lot of rewrites in the nginx sites-enabled because porting issues.  A lot of my posts are linked to in books, other blogs, etc. with the full .html path so I need to keep it and decided to use rewrites.  Likewise, I had to create the custom dates because of porting. 

Example: rewrite /2015/05/blah-blah.html http://www.domain.org/2015/05/blah-blah redirect;
Example: http://domain.org/2015/09/blah-blah/

I'll give it a look and report back if I end up fixing it.
