### ISSUE TITLE
Ghost listener SIGINT

### ISSUE THREAD

**Issue by gsantome** [TryGhost/Ghost#5861]
Hello, I'm using ghost like npm module but I just notice ghost is removing all the listeners for SIGINT and SIGTERM so I need to listen that events too from process... Could some one explain why Ghost remove the listeners and how to solve this?

Thanks

**Comment by ErisDS** [comment]
Hi @gsantomesorry to hear you're having trouble. If you have questions about Ghost or need help, please head on over to slack - https://ghost.org/slack/ - and post in the #help channel. This is a bug tracker for ongoing development of the Ghost software, and we're not able to do support here!
