### ISSUE TITLE
Editor Preview Is Hidden with Open <pre> Tag

### ISSUE THREAD

**Issue by NelsonScott** [TryGhost/Ghost#5868]
Took me a little while to figure out why the preview was hidden while editing one of my posts, turns out it was because of an unclosed pre tag.  

Reproduce: 
On a Mac, Google Chrome
Start editing, then write a pre tag but don't close it.  The preview on the right side will oddly disappear.

**Comment by ErisDS** [comment]
Hi @NelsonScott, thanks for raising this - the issue was already discovered & discussed over in https://github.com/TryGhost/Ghost/issues/5804#issuecomment-139917580 - and there is an open PR with a fix #5857 - it would be great if you could test that fix works for you.

**Comment by NelsonScott** [comment]
That solved it, thanks!
