### ISSUE TITLE
Ghost.org Download Url

### ISSUE THREAD

**Issue by ericrange** [TryGhost/Ghost#5869]
Hey why is the ghost download page reachable under:

[https://ghost.org/download+"*></](https://ghost.org/download+"*></)

?

**Comment by sebgie** [comment]
Hey, it works for me ... maybe use https://ghost.org/download/ if the special characters cause problems ;-).

**Comment by ericrange** [comment]
i just was wondering that the site appears even though the special characters in the url?
why is there no 404?

**Comment by sebgie** [comment]
I see, I'll raise this issue internally :+1:.
