### ISSUE TITLE
Postgres is fully supported; update docs?

### ISSUE THREAD

**Issue by jberkus** [TryGhost/Ghost#5878]
Currently the Config doc has the following to say:

> Ghost can also be used with PostGreSQL. Support for Postgres is currently second class compared to SQLite & MySQL – there is a build run against it, but very minimal manual testing. At present we are considering downgrading support to ‘community’ ...

Ghost works fine with PostgreSQL, 100% of functionality works, and all tests pass.  I run two sites on Ghost/Postgres, so I'll notice pretty quickly if it breaks.  Can we update the documentation?

**Comment by ErisDS** [comment]
This was discussed very recently in [slack](https://ghost.slack.com/archives/dev/p1441702359000075), and the docs were updated to clarify our position as a result of that discussion, just a few weeks ago.

No member of the core team, or aspect of Ghost's infrastructure depends on postgres in production, meaning it is not tested or even understood to the same level. This is particularly a problem given that postgres has a different interface to that of sqlite3 & mysql, meaning familiarity with its differences and quirks are necessary to provide support and fixes.

In addition, providing support for postgres is time-consuming and gets in the way of us shipping new things, as it adds an order of magnitude to the amount of testing we have to do for data-related features.

At the moment, we don't have enough community involvement or engagement around postgres to make up for the lack inside the core team (or to bring someone new into the core team who has the necessary knowledge). E.g. whenever anyone in Slack gets stuck with a postgres issue, there is no response from any community member. There do seem to be edge-case bugs, but they'e not understood well nor fixed.

As it says in the docs, I'm strongly considering classifying postgres support as 'community' and allowing the build to fail. It will then be up to the community to ensure that postgres failures are fixed.

**Comment by jberkus** [comment]
Well, what can I do?  I'm happy to look at GH issues and answer questions, but I don't generally log into Slack on a daily basis, so I can't promise to field questions there.

**Comment by ErisDS** [comment]
> I'm happy to look at GH issues and answer questions

That would be great :) The more the merrier always.

**Comment by jberkus** [comment]
Feh, looks like logging into Slack is a PITA because of conflicting Slack accounts I have with clients.  I don't suppose you could open up the Slack-to-IRC gateway?

Regardless, searching issues now ...

**Comment by ErisDS** [comment]
I use slack with multiple teams - once you have them logged in it should be straightforward to switch between them. We would love to turn on the IRC gateway, but slack doesn't allow us to do that with guest accounts - dropping them an email and adding your voice to the list of many people who have asked for that may be a good idea.

**Comment by jberkus** [comment]
The problem isn't multiple teams, it's multiple *accounts*.  That's unsupported, except via the IRC gateway.

**Comment by jberkus** [comment]
Anyway, in the meantime, please tag me on any PostgreSQL issues which I might miss.

**Comment by jberkus** [comment]
Oh, I suppose this isn't open for the time being.
