### ISSUE TITLE
the gravatar placeholder still shows up if the image has transparency

### ISSUE THREAD

**Issue by tonyeung** [TryGhost/Ghost#5882]
I'm not sure if this is the case on the hosted version, but the self hosted version shows my gravatar superimposed on top of the placeholder image.
![capture](https://cloud.githubusercontent.com/assets/1285514/10121300/b7dfb2b0-64aa-11e5-8892-ad85d69183b3.PNG)

**Comment by tonyeung** [comment]
might be related to this issue: https://github.com/TryGhost/Ghost/issues/5797

**Comment by ErisDS** [comment]
A PR which fixes this would be welcome, although I'm not sure how easy it will be as the functionality depends on layering one image on top of the other.

**Comment by program247365** [comment]
@tonyeung I'm trying to re-create this on ghost@0.7.1.

Can you provide some more information?
* Can you attach the image you used, so we can try?
* What browser is this happening?
* What version of Ghost are you on?

**Comment by tonyeung** [comment]
I'll get the info to you guys over the weekend.

**Comment by program247365** [comment]
Thanks!

**Comment by tonyeung** [comment]
http://www.gravatar.com/avatar/28bcf6437597e1049ce63f2623a93a9e?s=90&d=blank
chrome 46.0.2490.71m
ghost 0.7.0
doesn't happen on profile or team, http://localhost/ghost/setup/two/

**Comment by program247365** [comment]
@tonyeung Did you upload the photo, or did it just appear when you entered your email address? 

When I uploaded it:

![screen shot 2015-10-15 at 10 26 28 pm](https://cloud.githubusercontent.com/assets/13910/10532400/e4afed7e-738b-11e5-9a19-5881d58ae63d.png)

**Comment by tonyeung** [comment]
Appeared when the email was entered.

On Thu, Oct 15, 2015 at 9:28 PM, Kevin Ridgway < notifications@github.com [notifications@github.com] > wrote:
@tonyeung [https://github.com/tonyeung] Did you upload the photo, or did it just appear when you entered your email
address?

When I uploaded it:

screen shot 2015-10-15 at 10 26 28 pm
[https://cloud.githubusercontent.com/assets/13910/10532400/e4afed7e-738b-11e5-9a19-5881d58ae63d.png]
[https://cloud.githubusercontent.com/assets/13910/10532400/e4afed7e-738b-11e5-9a19-5881d58ae63d.png]

—
Reply to this email directly or view it on GitHub
[https://github.com/TryGhost/Ghost/issues/5882#issuecomment-148578239] .[https://github.com/notifications/beacon/ABOdiortESyviNyN3t3QUCsLJI--luA0ks5o8FgygaJpZM4GEb0h.gif]

**Comment by program247365** [comment]
Got it! I was able to recreate. Working on a fix now...

**Comment by kevinansfield** [comment]
There are some additional complexities to take into account for anyone who wishes to tackle this, please see my notes here https://github.com/TryGhost/Ghost/pull/5958#issuecomment-148637278
