### ISSUE TITLE
when i use forever start,the process not start and this log

### ISSUE THREAD

**Issue by YY030913** [TryGhost/Ghost#5883]
[31mERROR: Cannot find the configuration for the current NODE_ENV: production forever start index.js[0m

error: Forever detected script exited with code: 0

**Comment by ErisDS** [comment]
Hi @YY030913, sorry to hear you're having trouble, sounds like your config.js file is missing. If you have questions about Ghost or need help, please head on over to slack - https://ghost.org/slack/ - and post in the #help channel. This is a bug tracker for ongoing development of the Ghost software, and we're not able to do support here!

**Comment by YY030913** [comment]
oh no,i fix it,i use 
set NODE_ENV=production
clear the NODE_ENV var,then the forever start index.js success
pre is 
set NODE_ENV=production forever start index.js
but i still unknow what happened when i set NODE_ENV=production forever start index.js
