### ISSUE TITLE
Manage loop. Get first post, and start loop from second..

### ISSUE THREAD

**Issue by mikeyakimenko** [TryGhost/Ghost#5893]
Hello. I want create my own design, but don't know how. 

by first, i want create on index page 1st post full text, and 5 next posts titles only and archive url. Also live example: http://macgera.name/ 

But i did't find in documentation how do this. Can i do something like foreach posts[1] or foreach posts[2:6] ?

**Comment by halfdan** [comment]
Hi @macgera 
The theme docs show how to do this: http://support.ghost.org/ghost-built-helpers/#@first-&-@last

We use Github for tracking issues and cannot provide support here. For future support please head over to our Slack community: https://ghost.org/slack/
