### ISSUE TITLE
{{#if featured}} does not render post that is both featured and a static page

### ISSUE THREAD

**Issue by willthefirst** [TryGhost/Ghost#5898]
I'm trying to display a featured post that also happens to be a static page:

![2015-09-29 at 10 07 am](https://cloud.githubusercontent.com/assets/1113314/10166423/eedd1aee-6691-11e5-9650-1fa80290d64a.png)

and using the following code in `index.hbs`:

    {{#foreach posts}}
        {{#if featured}}
            {{content}}
        {{/if}}
    {{/foreach}}

Nothing gets rendered, but as soon as I uncheck "Turn this post into a static page", my stuff shows up. This is unexpected behavior.

**Comment by willthefirst** [comment]
I've learned that `#foreach posts` does not search through static pages. I'll try to find another way.

**Comment by Kikobeats** [comment]
I have the same issue.

The point is, this is a expected behavior? and if is expected, what strategy use to resolve it?

@willthefirst are you discover something?

**Comment by willthefirst** [comment]
@Kikobeats: I worked around it by filtering for posts with a specific tag (in my case, "homepage"), where I know that I should only ever have one post with that tag. In `index.hbs`

    {{#is "home"}}
      {{#foreach posts}}
        {{#has tag="homepage"}}
          {{content}}
        {{/has}}
      {{/foreach}}

**Comment by Kikobeats** [comment]
In mi case I discover that I was using a different HTML tag for `{{post_class}}` helper in `post.hbs` and `page.hbs`, so is fixed :-)

**Comment by ErisDS** [comment]
With the new `{{#get}}` helper, you can do:

```
{{#get "posts" filter="featured:true+page:true"}}
  {{#foreach posts}}
  ... do something with all featured pages...
  {{/foreach}}
{{/get}}
```

The `{{#foreach}}` helper only loops through the data that is available, so once the post gets old enough to not be shown on page 1, you'll no longer see the post if you use `{{#foreach}}` + `{{#has}}`.

The `{{#get}}` helper does a query to fetch the exact data you want, and then you can loop over it using the `{{#foreach}}` helper.

In the example above, the query is `filter="featured:true+page:true"` - "get all posts where featured is true and page is true".

Equally, to get a post with a particular tag you could use: `filter="tag:homepage"` note that the value for the tag should be the slug value, if you want to use the tag's name, then change to `filter="tag.name:'Home Page'"`. 

- Get helper docs: http://themes.ghost.org/docs/get
- Filtering docs: http://api.ghost.org/docs/filter (WIP)

**Comment by lazercaveman** [comment]
The {{get}} helper is the traditional way of doing this.

However there is also the recently added dynamic routing feature which may cover more to stuff like fully separating blog posts (yoursite.com/blog/) from portfolio posts (yoursite.com/portfolio/) for example.

https://docs.ghost.org/docs/dynamic-routing
