### ISSUE TITLE
Question: is there an online course plugin?

### ISSUE THREAD

**Issue by azat-co** [TryGhost/Ghost#5904]
If not, how hard is it to hack one together similar to CoursePress for WP?

**Comment by novaugust** [comment]
Hey @azat-co, we use GitHub issues for tracking development (features, bugs) on Ghost. Your question is more suited to our [slack community](https://ghost.org/slack/). Please use it for any future questions!

I can go ahead and answer this easy enough though: Ghost doesn't support plugins at this time (beyond a rudimentary prototype, anyways) and so no, there is no online course plugin

**Comment by azat-co** [comment]
no plugins? WAT? ;-(
