### ISSUE TITLE
[docs] Themes docs lack information about {{id}}

### ISSUE THREAD

**Issue by k-j-kleist** [TryGhost/Ghost#5910]
The theming documentation at http://themes.ghost.org is excellent. However, it does not cover the `{{id}}` helper, which renders the numeric id of a posting.

In line with `http://themes.ghost.org/docs/title`, it could be made available at `http://themes.ghost.org/docs/id`.

**Comment by novaugust** [comment]
There isn't actually an `{{id}}` helper. You're actually just accessing the data directly, presumably with a `{{#with post}}` block. Check the first line here on [post attributes](http://themes.ghost.org/docs/post-context#section-post-object-attributes)

**Comment by ErisDS** [comment]
Hi @k-j-kleist, thank you for the feedback! The reason there is no documentation for the `{{id}}` under helpers, is that it isn't a 'helper' but rather just a piece of data - an attribute. Helpers are like functions that execute some logic, data attributes are more like variables they just output data directly - there are many of them, but they each belong to an object - `{{id}}` exists for posts, users, tags etc/

You can find `{{id}}` and the other data attributes for post documented here: http://themes.ghost.org/docs/post-context#section-data. This is also a link here for convenience: http://themes.ghost.org/docs/post#section-post-attributes.

The various types of handlebars expressions are explained in full here: http://themes.ghost.org/docs/handlebars

If you'd like to make changes to the documentation, you can submit these using the 'suggest edits' feature on each page, and if you have more questions about Ghost themes and the various bits of our theme API please drop by the #themes channel on [slack](https://ghost.org/slack).

**Comment by k-j-kleist** [comment]
Wow, that was quick. Thanks!
