### ISSUE TITLE
Bug: deleted entries not removed from sitemap

### ISSUE THREAD

**Issue by oddjobz** [TryGhost/Ghost#5913]
### Issue Summary

When I delete entries (or make posts static) these URL's cease to work (as expected) but are still included in the sitemap.

### Steps to Reproduce

1. Create a page
2. View sitemap
3. Delete the page
4. View sitemap - page index is still visible
5. Attempt to click on link and visit page results in 404

1. Create port
2. View sitemap
3. Convert post to static page
4. View sitemap - static page still visible as a post
5. Attempt to click on legacy post results in a 404

The sitemap should not include objects know to result in a 404.

### Technical details

* Ghost Version: 0.7.0
* Client OS: Ubuntu 15.04
* Server OS: Ubunti 15.04
* Node Version: v0.10.25
* Browser: Chrome
* Database: Sqlite3

**Comment by ErisDS** [comment]
@oddjobz Thanks for the bug report, this is expected to work & seems like a regression to me.

A bug fix, including a broken test case, would be great here.

**Comment by olsio** [comment]
@ErisDS While looking into this I found that you by accident disabled all but one test for the post model.

https://github.com/TryGhost/Ghost/commit/0462607296f2a1a5b3ac3a3d98eb254e5fdfd605#diff-64e60e2e79e27d0a8c66873904f62de2

When I re-enable the test it is failing one tests. I hope to raise a PR soon to fix both issues.

**Comment by ErisDS** [comment]
derp :flushed: thanks!
