### ISSUE TITLE
Permalinks problem

### ISSUE THREAD

**Issue by Faber73** [TryGhost/Ghost#5915]
Hello to everyone,
I've customized the permalinks of my blog, like "/:id/:slug.html", manually on DB and I've set "false" the slashes in the middleware.

Now all working fine, except the admin panel link. Admin working if I going manually to set the full link, like "/ghost/signin/", but not if i wrote simple "/ghost/". In the logs I find a redirect ping-pong :

```
"GET /ghost HTTP/1.1" 303 - "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:41.0) Gecko/20100101 Firefox/41.0"
"GET /ghost/ HTTP/1.1" 301 - "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:41.0) Gecko/20100101 Firefox/41.0"
"GET /ghost HTTP/1.1" 303 - "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:41.0) Gecko/20100101 Firefox/41.0"
"GET /ghost HTTP/1.1" 303 - "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:41.0) Gecko/20100101 Firefox/41.0"
"GET /ghost/ HTTP/1.1" 301 - "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:41.0) Gecko/20100101 Firefox/41.0"
"GET /ghost HTTP/1.1" 303 - "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:41.0) Gecko/20100101 Firefox/41.0"
"GET /ghost/ HTTP/1.1" 301 - "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:41.0) Gecko/20100101 Firefox/41.0"
"GET /ghost HTTP/1.1" 303 - "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:41.0) Gecko/20100101 Firefox/41.0"
```

how to fix it ?

thank you in advance

**Comment by ErisDS** [comment]
Hi @Faber73 - I've replied to you in #help on [slack](https://ghost.org/slack) which is a better place to discuss this as it isn't a bug in Ghost but rather a side-effect of changes you have made.
