### ISSUE TITLE
Highlight non-breaking spaces in editor

### ISSUE THREAD

**Issue by toblerone1963** [TryGhost/Ghost#5919]
Hi,

It could be a good idea to highlight non-breaking spaces when you edit a post. It's very useful in french, especially for angle quotes and numbers (we write 35&nbsp;000 and not 35.000). 

I may have found [a solution on stackoverflow](http://stackoverflow.com/questions/29730535/highlight-non-breaking-spaces-in-html-page-or-wordpress-editor).

Thanks for all

**Comment by ErisDS** [comment]
Hi @toblerone1963, 

We're going to be overhauling the editor soon, so I recommend adding this over on our [wishlist](http://ideas.ghost.org). We use this list to help determine what goes into the roadmap and how to prioritise features. This is not something we would fix in the existing editor as it would likely be lost in the overhaul.

Note: You can also access the wishlist any time from inside the Ghost admin:
![](http://puu.sh/jXKwm.png)
