### ISSUE TITLE
Animated text is not being rendered properly

### ISSUE THREAD

**Issue by camilodelvasto** [TryGhost/Ghost#5924]
On Chrome (and possibly Safari too) the animated text and other H2/H3 elements are not being properly rendered on the default theme (Casper). We fixed this for our site using:
`html { -webkit-font-smoothing: antialiased; }`
I suggest adding this line to Casper.

**Comment by kevinansfield** [comment]
@camilodelvasto would you mind opening this on the [Casper](https://github.com/TryGhost/Casper/issues) repo? The Ghost repo is for core dev. Thanks!

**Comment by camilodelvasto** [comment]
@kevinansfield sure, silly me.
