### ISSUE TITLE
Storage abstraction

### ISSUE THREAD

**Issue by vdemedes** [TryGhost/Ghost#5926]
After reading discussions and issues related to file storage abstraction (#4600, #2852), I decided to put up a proposal to solve current issues.

# Goals

1. Standard API for file storage adapters to implement
2. Simple adapter installation and configuration
3. Store any type of data in a file storage (images, backups, themes, apps)

# Issues with the current implementation

- Storage adapters are suited only for saving & serving images
There are currently 2 main methods: `save` and `serve`. But there's no easy way to get one specific file from the storage.
There's `serve` method, which returns a *middleware* for express to fetch files on request.
Adapter should not be responsible for responding to HTTP requests, it must stick to its job only - saving and getting files.
`serve` middleware should be one and only middleware for all adapters.

- Complicated installation
To install a new storage adapter, user needs to copy-paste adapter's files to `content/storage` and set `storage.active = 'my-adapter'` in a config.
This way has the following disadvantages:

1. Manual copy-paste of files (adapters can also have many files/folders)
2. To update an adapter, user needs to repeat the same process and follow adapter's repository for updates
3. Adapters have npm dependencies 99% of the time, user needs to look them up and `npm install --save` manually. Take https://github.com/kimar/ghost-aws-s3 as an example. It is kind of a step back from the package manager era
4. A need to provide and maintain ["Using a custom storage module"](https://github.com/TryGhost/Ghost/wiki/Using-a-custom-storage-module) documentation

# Solution

Each adapter should be a separate npm module with its own repository. Advantages:

- Simplest installation there is: `npm install ghost-storage-s3 --save`
- To update, just `npm install` again
- Adapter's dependencies are installed automatically
- Widely adopted practice to install complementary functionality (for example: gulp, grunt, yeoman, etc)
- We can create a yeoman generator to easily scaffold new storage modules
- If adapter modules are tagged with `ghost-storage` (inspired by yeoman & grunt), we can assemble a complete list of adapters existing on npm

### Custom storage module installation

Here's the complete flow of setting up a custom storage module (for example, `ghost-storage-s3`):

1. `npm install ghost-storage-s3 --save`
2. `config.js`: 
```js
config = {
	// ...
	storage: {
		// set storage module for each type of data
		active: {
			images: 'ghost-storage-s3',
			themes: 'some-other-storage',
			apps: 'another-storage'
		},
		
		// or set one module for everything
		active: 'ghost-storage-s3',
		
		'ghost-storage-s3': {
			bucket: 'some bucket',
			secret: 'some secret',
			key: 'some key'
		}
	}
}
```
3. Restart Ghost
4. Done!

### Build custom storage modules

Each adapter should extend `ghost-storage-base` module and implement required methods: `get` and `put`.
Overview of complete storage adapter API:

- `get(String remotePath)` *required*
- `put(String localPath, String remotePath)` *required*
- `exists(String remotePath)` *optional*

There's one thing, that still needs resolution - the `put` method.
I am a big fan of how [knox](https://npmjs.org/package/knox) handles the situation.
It gives a lot of freedom: `putFile`, `putBuffer` and `putStream`.

- `putFile(String localPath, String remotePath)` - reads file and saves it
- `putBuffer(Buffer data, String remotePath)` - saves provided buffer
- `putStream(String remotePath)` - creates a stream, which you can `pipe()` to

It would make adapters little harder to implement for developers, but it is well worth it for sure. I think this needs to be discussed, what method needs to be chosen. In terms of performance and memory consumption, `putFile` and `putStream` are the best ones, since they stream data and don't store the whole data in memory (unlike `putBuffer`).

### Using storage adapters

Storage adapters should be easily swappable, so there must be a single entrypoint with a stable API to access storage.

*core/server/storage/index.js*:

```js
var config = require('/path/to/config');

// get active storage module name
var activeModuleName = config.storage.active;

// get configuration for it
var options = config.storage[activeModuleName];

// require, initialize and expose module
module.exports = require(activeModuleName)(options);
```

That way, you can access currently active storage module from anywhere:

```js
var storage = require('./core/server/storage');

storage.get();
storage.put();
// etc..
```

# Feedback

Let's discuss this proposal! If anything is unclear in this proposal, please point it out ;)

**Comment by sethbrasile** [comment]
@vdemedes I disagree with your points about a complicated installation. Take a look at my Cloudinary storage module: https://github.com/sethbrasile/ghost-cloudinary-store

Installation:

1. Run npm install ghost-cloudinary-store --save

2. Create file `content/storage/ghost-cloudinary-store/index.js`

3. Put `module.exports = require('ghost-cloudinary-store');` into this file

4. Follow the instructions below for editing config.js

And the instructions for editing config.js are basically adding:

``` js
storage: {
    active: 'ghost-cloudinary-store'
}
```

**Comment by sethbrasile** [comment]
`¯\_(ツ)_/¯` Did I kill the conversation?

**Comment by colinmeinke** [comment]
I've just come unstuck on this, and would like to throw my support behind this proposal and get this conversation rolling.

I'm trying to get Ghost deployed on [now](https://zeit.co/now). It is not a persistent server. In fact only the `/tmp` directory is writable. See #7359 for a related issue. Heroku is similar.

I have RDS and S3 configured, and hoped that would be enough to mean there would be no local writes.

I noticed today when I upgraded from 0.10 to 0.11 I had database backups writing locally also.

Currently storage adapters are image specific. Backups are still written locally. This is also relevant for [logging](https://github.com/TryGhost/Ghost/issues/7116).

Ghost absolutely needs a well abstracted storage architecture that can write any required files to external resources using storage adapters.

@ErisDS @vdemedes Is this in progress? I'd be very happy to pick this up.

**Comment by colinmeinke** [comment]
cc @kirrg001

**Comment by ErisDS** [comment]
@colinmeinke it is not in progress right now, but we will be making some major changes to how adapters work very soon. We are working on communication around our current roadmap. In the meantime, I recommend either hanging fire until our codebase stabilises or implementing your own hacks for the "now" platform.

I'm going to close this issue for now, as I'm not sure that the spec matches up with our plans anymore. We'll get an up-to-date spec released soon. If you want to talk to us about developing core, you can join us in the #dev channel in [slack](https://ghost.org/slack) :)
