### ISSUE TITLE
<pre> and <code> replaced within code blocks by {gfm-js-extract-pre-1}

### ISSUE THREAD

**Issue by dlecina** [TryGhost/Ghost#5939]
Writing a code block containing the following:

```
<pre>test</pre>

<code>test</code>
```

Will produce:

```
{gfm-js-extract-pre-1}

{gfm-js-extract-pre-2}
```

![Screenshot](https://cloud.githubusercontent.com/assets/1137825/10441489/9e020400-7149-11e5-9149-4603cda1b810.png)

**Comment by ErisDS** [comment]
Good find, thanks for the report.

**Comment by acburdine** [comment]
@ErisDS I found where this is occurring, and it's a bug in showdown-ghost. `<pre>` and `<code>` blocks are parsed before code fence blocks, leading to this error. Should I submit a PR in your showdown fork or no?

[Bug area](https://github.com/ErisDS/showdown/blob/master/src/showdown.js#L272-L282) (at least as far as I was able to tell)

**Comment by ErisDS** [comment]
Sorry @acburdine I should have assigned this to myself - there's no point submitting fixes to my branch as I'm working on switching back to normal showdown ;)

**Comment by eexit** [comment]
Hi there, any update on this one?

**Comment by PedroEsperanca** [comment]
My solution is to add a space in the closing element like so:

````
</pre >
````

A bit wierd but still works if copy+pasted
