### ISSUE TITLE
Ember Simple Auth 1.0 upgrade

### ISSUE THREAD

**Issue by kevinansfield** [TryGhost/Ghost#5951]
ESA 1.0 is now pretty much code-complete and is only waiting on documentation to be finished before release. ESA is currently our main (only?) blocker for upgrading to Ember 2.x, as such I would like to get the upgrade moving forward in a PR so that we can find any blockers/implications/issues early on.

Discussion around 1.0 can be found in the pull request at https://github.com/simplabs/ember-simple-auth/pull/602 and latest code is in the [jj-abrams](https://github.com/simplabs/ember-simple-auth/commits/jj-abrams) branch.

**Comment by kevinansfield** [comment]
@acburdine I know you expressed interest in working on this before, are you still up for that?

**Comment by acburdine** [comment]
Sure! I should have some time later today to work on it.
