### ISSUE TITLE
If statements in Handlebars

### ISSUE THREAD

**Issue by kaiserhase** [TryGhost/Ghost#5966]
I want to add an if statement to check if the navigation label equals a certain ...label... Is this possible? (The idea is if it equals a specific static post in the navigation, it would add a dropdown menu).

I assumed something like {{#if navigation.label === "value"}} would work, but that's more of javascript logic than handlebars.

**Comment by kaiserhase** [comment]
This is what i have right now to do what I want:

'{{#foreach navigation}}
        <script>if ("{{label}}" === "+learn tech") {document.write("<li class=\"nav-item\" role=\"presentation\"><a class=\"nav-link\" href=\"{{url absolute="true"}}\">{{label}}</a></li>");} else {document.write("<li class=\"nav-item\" role=\"presentation\"><a class=\"nav-link\" href=\"{{url absolute="true"}}\">{{label}}</a></li>");}</script>        
                {{/foreach}}'

I am hoping there is a more elegant way to do this...

**Comment by blehMgowano** [comment]
can i see into this one

**Comment by halfdan** [comment]
What is your use case for this? Handlebars very intentionally comes without
if helpers.

**Comment by kaiserhase** [comment]
![snippet](https://cloud.githubusercontent.com/assets/10073651/10564283/01b25f50-757c-11e5-8597-1d0f944fff81.JPG)

I attached a jpg with the code. It essentially allows me to shiv a sub-menu into the Ghost populated navigation. Since Ghost doesn't do it natively (or archiving, listing of blogs, etc except RSS), I had to find a way to get it to work.

It works live www.builtbygoat.com (albeit the CSS was a pain to finagle).

**Comment by kaiserhase** [comment]
It isn't a pretty solution. I was hoping for a better alternative. I haven't really played with handlebars as much yet, just the few snippets Ghost uses.

**Comment by topaxi** [comment]
I'm not sure where to register helpers in Ghost, but in Handlebars this can be solved with a `eq` helper like this:

```javascript
Handlebars.registerHelper('eq', function(a, b) {
  return a === b;
});
```

And then in your template with Handlebars use subexpressions:

```handlebars
{{#if (eq a b)}}
  ...
{{else}}
  ...
{{/if}}
```

**Comment by kaiserhase** [comment]
Good call topaxi.

We would have to add to ghost/core/server/helpers/ to create this kind of functionality. Aka, get it into the repo (or every time we'd upgrade, we'd have to redo it). 

Lemme see how to go about fiddling with the helpers.

**Comment by kaiserhase** [comment]
Yeah, looks like the only real thing would be to add a helper that would allow you to do:

{{#foreach navigation}} 
    {{#if (eq a b)}}
        subnav
    {{/if}}
{{/foreach}}

**Comment by ErisDS** [comment]
Hi @kaiserhase, this sort of logic is, as you have discovered, not possible with handlebars. The Ghost theme documentation is here: http://themes.ghost.org and the handlebars documentation is here: http://handlebarsjs.com/ 

In the short term your best bet is to use JavaScript, the way you have done. Ghost's navigation menu exists to serve the majority of use cases for blogs - which is a very simple flat menu. If that's not what you need, then the expectation is you would hard code your own menu that fits your needs.

If you have any further questions, please join the #themes channel of our [slack](https://ghost.org/slack) community. GitHub is for tracking bugs & issues with the Ghost software.

**Comment by kaiserhase** [comment]
*sigh*

**Comment by blehMgowano** [comment]
I was considering replacing the if statements with case statements, I was
once in that kind of situation
