### ISSUE TITLE
Performance : increase requests per second.

### ISSUE THREAD

**Issue by maxbook** [TryGhost/Ghost#5968]
Hi, firstly i use ghost on new project and is incredible, good work ! 
however, i have observed that it works in single thread , so out of curiosity I moved to a node worker (TCP connexions with node/express is ok for multithreading) and launch it on multi thread (8 exactly), and WOOOH, 7 time more requests per second, longest request 133% faster...

Here copy of my siege test on ghost with 4 core xeon processor and 8 thread, url is masked (for security)

siege -b -t30S -n 100 -c 200 URL

SIMPLETHREADING

Transactions:		        1208 hits
Availability:		      100.00 %
Elapsed time:		       29.81 secs
Data transferred:	        2.90 MB
Response time:		        1.19 secs
Transaction rate:	       40.52 trans/sec
Throughput:		        0.10 MB/sec
Concurrency:		       48.19
Successful transactions:        1208
Failed transactions:	           0
Longest transaction:	        2.21
Shortest transaction:	        1.01

MULTITHREADING

Transactions:		        4310 hits
Availability:		      100.00 %
Elapsed time:		       29.25 secs
Data transferred:	       10.36 MB
Response time:		        0.34 secs
Transaction rate:	      147.35 trans/sec
Throughput:		        0.35 MB/sec
Concurrency:		       49.52
Successful transactions:        4310
Failed transactions:	           0
Longest transaction:	        1.66
Shortest transaction:	        0.06

**Comment by ErisDS** [comment]
Hi @maxbook, mebbe I'm wrong but it kinda feels like you hit enter before you finished here?! I'm not sure what sort of response or outcome you were looking for?

Clearly the speed increase is impressive, however you're likely to encounter bugs with things which are stored in memory, like settings & sitemaps.

Perhaps you'd like to look at resolving those issues somehow?

**Comment by olsio** [comment]
I think the standard setup of nginx handling the multi threading part and node just occasionally delivering a new cache version is preferable to a multi threaded node application. A blog is more on the static content side of web apps and can be cached very nicely.

**Comment by maxbook** [comment]
Hi, thank for your answers, my post is just a ascertainment, @ErisDS it's true that I do not know where to post it ^^, i'm ok for nginx, it offers the best performance to provide cache (although after several tests the difference is not so impressive). But I do not use nginx everywhere, and perhaps some users are like me, in this case, the multithreading maybe is a good option ;)

**Comment by ErisDS** [comment]
Ok in that case, I'm going to close this. 

I don't recommend scaling Ghost this way due - you'll likely run into issues as explained above, instead I'd recommend scaling Ghost by placing CloudFlare, Varnish or any other cache in front of it.

With regards to improving the rps, perhaps there are some indicators in #6023 that show ways we could improve Ghost in order to optimise performance.

**Comment by Faber73** [comment]
Hello,
how do it ?

> I moved to a node worker (TCP connexions with node/express is ok for multithreading) and launch it on multi thread (8 exactly),


Thanks
