### ISSUE TITLE
Export content is not working

### ISSUE THREAD

**Issue by delgermurun** [TryGhost/Ghost#5973]
Here is server log:
```
ERROR: Please Sign In 
 
GET /blog/ghost/api/v0.1/db/?access_token=undefined 401 17.155 ms - 73
```

Commit: 5d7ca080c9938ad55f87d57825dd5727f381f141
OS: Ubuntu 15.04 64bit
Browser: Chrome

**Comment by acburdine** [comment]
Good catch! I must have missed that one (:sheep:ish :grin:)
