### ISSUE TITLE
Bug: When Editing Post, Tab Shows Hidden Menu

### ISSUE THREAD

**Issue by dbalders** [TryGhost/Ghost#5986]
### Issue Summary

When you are inside a post and have the content area in focus and hit tab, it shows a hidden menu.

![tab](https://cloud.githubusercontent.com/assets/4715098/10645341/1fb8cc38-77e2-11e5-986a-291a73af8718.gif)

### Steps to Reproduce

1. Open or create a post
2. Click in the content area
3. Press Tab

### Technical details:

* Ghost Version: 0.7.1
* Client OS: Mac OS X 10.10.3
* Server OS: DO Droplet Ubuntu
* Browser: Chrome

**Comment by adam-beck** [comment]
This might be an accessibility thing? If you try doing this on Github itself you will get the same sort of hidden menu.

**Comment by ErisDS** [comment]
It's the skip-link so that users with screen readers don't have to hear the menu read out every time they navigate to a new page. It might be better to tweak the CSS so it doesn't push the content down though.

**Comment by sirugh** [comment]
This is certainly for a11y, however it is probably not supposed to occur after tabbing from the content.

First, I'd make sure it's supposed to be the next focusable element after the element that is currently focused. If that functionality is expected, then the next step is to maybe update the CSS as @ErisDS suggested.

**Comment by sp90** [comment]
@ErisDS I think you can set the tabindex="-1" then it shouldn't be tabable

Mozilla desciption: "a negative value means that the element should be focusable, but should not be reachable via sequential keyboard navigation;" reference link: https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/tabindex

**Comment by ErisDS** [comment]
@sp90 pretty sure that defeats the object of it being an accessibility link?

**Comment by sp90** [comment]
@ErisDS then what is the wanted behavior?

**Comment by kevinansfield** [comment]
It would be possible to capture the <kbd>tab</kbd> key when the editor has focus but is that desired? I don't see much point for inserting a `\t` character as it will be treated as normal whitespace by the markdown parser and may break users' expected keyboard navigation behaviour.

**Comment by kevinansfield** [comment]
Github no longer has the same issue that was pointed out above, their css for the accessibility link is now the following:

```css
.accessibility-aid {
    height: 1px;
    width: 1px;
    clip: rect(1px, 1px, 1px, 1px);
    overflow: hidden;
    position: absolute;
    margin: 0;
}

**Comment by ErisDS** [comment]
Sounds like a good solution :+1:

**Comment by acburdine** [comment]
Closed via #6563

**Comment by rogerpence** [comment]
It seems like this issue came back with Ghost 0.8.0. Tab key press in post editor focuses "skip to main content" box when attempting to indent code for markdown.

**Comment by acburdine** [comment]
@rogerpence I don't think the issue was pressing tab makes it appear, rather that the skiplink was pushing the page down.
