### ISSUE TITLE
Build failing, Move all dependencies to dynamic versions

### ISSUE THREAD

**Issue by Anfa-am** [TryGhost/Ghost#5992]
The dependencies are outdated, would these updates break some codes? 

"blueimp-md5": "1.1.0" to "blueimp-md5": ">1.1.0" 

Should I make a pull request?

**Comment by anonrig** [comment]
It is not recommended to use tildas, because a module that doesn't bump its versions using semver may broke the build process. Individual bumps should be done with proper tests for outdated dependencies.

**Comment by ErisDS** [comment]
I'm not sure what you're referring to by 'build failing' - our travis build is OK and building Ghost is also working ok as far as I am aware. If you need help & support getting Ghost running please reach out in the #help channel of our Slack community. 

You can also use the zip files provided which contain pre-built versions of the software.
