### ISSUE TITLE
Ghost not starting when re-starting Azure web site

### ISSUE THREAD

**Issue by eaardal** [TryGhost/Ghost#6003]
I installed Ghost from the Marketplace in Azure and the installation itself works fine, but when I restarted the web app in Azure it's not able to start Ghost up again. All requests return 500.1002 from IIS. I replicated this by making another site the same way and stopped it, then started it in azure. Same result. 

![ghosterror](https://cloud.githubusercontent.com/assets/2316274/10715288/b4d987ee-7b11-11e5-9503-8fb63790b7f9.png)

**Comment by ErisDS** [comment]
Hi @eaardalsorry to hear you're having trouble. For help with Azure you'd need to contact their support. For questions about Ghost or if you need help and support, please head on over to slack - https://ghost.org/slack/ - and post in the #help channel. This is a bug tracker for ongoing development of the Ghost software, and we're not able to do support here!
