### ISSUE TITLE
Bug: Content management items

### ISSUE THREAD

**Issue by JohnONolan** [TryGhost/Ghost#6006]
Two minor bugs on content mgmt at the moment:
1. When you delete a post, expected behaviour is that the next post below the current one will be selected. (Same as an email inbox) – Currently, the very first/most-recent post is selected at the top of the list when a post is deleted.
2. ~~Deleting a bunch of posts in a row breaks loading, leaves a big empty gap with no way to load in any new posts (see below).~~ closed by #6387 (#6390)

![image](https://cloud.githubusercontent.com/assets/120485/10728242/c163cff6-7be8-11e5-9672-27db4d5fae67.png)

**Comment by JohnONolan** [comment]
RE point 2, I'm beginning to wonder if it would make more sense to have a "load more posts" button, as is becoming a common UX trend (cc @kevinansfield ) – Our infinite-scroll implementation has always been quite nasty.

**Comment by novaugust** [comment]
Moving 2) into its own issue so these can be addressed separately

**Comment by kevinansfield** [comment]
Closing and adding a reference to the [content screen overhaul](https://github.com/TryGhost/Ghost/issues/6006) issue.
