### ISSUE TITLE
Ghost wont show the installed Theme and cant post any posts pls HELP

### ISSUE THREAD

**Issue by fitgeekpaul** [TryGhost/Ghost#6013]
Hi,

I have installed ghost on the a2hosting.com servers by using their ghost platform.
Logging in on the ghost cms went fine on www.jonathanklaassen.com . 
and uploaded the bought theme to through Filezilla in the themes map. 
Logged into the Ghost template and changed the template.
Checked the site again... I am not seeing the new template at all. 
And when i want to post a new item i dont even see that as well it just stays Blank..
This is maybe a beginner problem but i really cant seem to figure this out!

Please help

this is an email generated by the Ghost template:
De installation of Ghost 0.7.1 is done. 
Path : /home/jonathanklaassen/public_html
URL : http://jonathanklaassen.nl
Admin URL : http://jonathanklaassen.nl/ghost Data Directory: /home/jonathanklaassen/nodejs

**Comment by vdemedes** [comment]
Issue resolved in Slack's #help - https://ghost.slack.com/archives/help/p1445936037001701.
