### ISSUE TITLE
Ellipsis after post excerpt

### ISSUE THREAD

**Issue by nickfoerster** [TryGhost/Ghost#6022]
More of a feature request than an issue. I noticed with themes that use post excerpts on the front page are ended abruptly without any use of punctuation. I suggest an option to place an ellipsis [...] before the closing </p> tag to remind readers that there is a continuance.

If there is a feasible hack for this, I'd definitely like to know. Thanks!

**Comment by halfdan** [comment]
@nickfoerster Yes, the simple hack is `{{excerpt}}[..]`. Just add the [...] to your theme after the excerpt helper.

**Comment by JohnONolan** [comment]
You can see this in action on the Casper theme, where there's a "read more" link rather than an ellipses. But either works! https://github.com/TryGhost/Casper/blob/master/partials/loop.hbs#L13 :)

**Comment by adamcooke** [comment]
Wouldn't it be nice if the {{excerpt}} helper added the `...` only if truncation has occurred?
