### ISSUE TITLE
Better workflow support (publishing permissions)

### ISSUE THREAD

**Issue by adamkdean** [TryGhost/Ghost#6035]
Now, I may be missing something in which case please tell me and close this issue, but I think that Ghost could benefit from better workflow support with regards to publishing permissions.

I want to allow authors to write posts and put them into a state where they are ready to be published but must be approved and published by an editor/admin user, not unlike the way a pull request works. As I understand it, at the moment, authors can publish straight to the blog even without the editors approval.

Is this something which has been mentioned before? Is there already a solution?

**Comment by ErisDS** [comment]
Hi @adamkdean,

You can vote for this feature on our [wishlist](http://ideas.ghost.org/forums/285309-wishlist/suggestions/7193351-contributor-author-account) or add your own feature request there if you feel your idea is significantly different.

This idea is one that we are very much looking into, however the existing permissions system in Ghost doesn't support the level of granularity that would be required. We're planning a major overhaul of the permissions system in the near future that will allow us to provide more controls like this, as well as to provide things like the ability to grant access to another author to edit your post.

Hopefully that explains where we are in terms of adding those sorts of features - we prioritise features based on traction on the [wishlist](http://ideas.ghost.org) so I definitely recommend voting on the things you want to see 😊

**Comment by adamkdean** [comment]
Thanks for the feedback and the information. I wasn't aware of the wishlist but I'll do that.

**Comment by paulmaunders** [comment]
Hi, I would also like this feature. I've tried to click through to the wish list, but ideas.ghost.org is no longer available. Where is the preferred place to vote on ideas now?

**Comment by paulmaunders** [comment]
Actually, I've just spotted this: https://github.com/TryGhost/Ghost/issues/9314
