### ISSUE TITLE
Feature request: Post image attribution

### ISSUE THREAD

**Issue by 2moveit** [TryGhost/Ghost#6054]
It would be great to have a function to add attribution informations for the post image in the settings of the blog post. So you can add the attribution of an image that is for example under the Creative Common License easily. The attribution then might be displayed as an overlay in the image on the site.

**Comment by acburdine** [comment]
Hey @2moveit! Thanks for contributing! However, we ask that feature requests be submitted via http://ideas.ghost.org/ . That way, others can up vote your idea if they agree.

The github issue tracker is for actual issues with the software :)

**Comment by 2moveit** [comment]
Ahh, sorry. Thought it will be just a flag. But good to know, will do it there. Thx.
