### ISSUE TITLE
Filter contents by tag in admin panel

### ISSUE THREAD

**Issue by juanpaulo** [TryGhost/Ghost#6066]
Sort of related to #5321.

In Content tab (admin panel), show tag names in each content to visually categorize contents by tag. This will be useful as the number of contents grow.
As an enhancement, it would be great if clicking on the tag name filters the contents with the same tag.

**Comment by ErisDS** [comment]
Hi @juanpaulo, 

To request a feature for Ghost you can add your idea (or vote on a similar one) over on our [wishlist](http://ideas.ghost.org). We use this list to help determine what goes into the roadmap and how to prioritise features. You can also access the wishlist any time from inside the Ghost admin:
![](http://puu.sh/jXKwm.png).

**Comment by juanpaulo** [comment]
I see, thanks!
