### ISSUE TITLE
npm WARN EPEERINVALID grunt-mocha-istanbul@2.4.0 requires a peer of istanbul@0.x.x but none was installed.

### ISSUE THREAD

**Issue by devurandom** [TryGhost/Ghost#6079]
When I run `npm install`, I get the following warning:
```
npm WARN EPEERINVALID grunt-mocha-istanbul@2.4.0 requires a peer of istanbul@0.x.x but none was installed.
```

I am using latest Git with NodeJS 5.0.0 and following patch:
```diff
diff --git a/core/client/package.json b/core/client/package.json
index 2f3013c..c403362 100644
--- a/core/client/package.json
+++ b/core/client/package.json
@@ -20,7 +20,7 @@
   "license": "MIT",
   "devDependencies": {
     "broccoli-asset-rev": "^2.1.2",
-    "ember-cli": "1.13.8",
+    "ember-cli": "^1.13.12",
     "ember-cli-app-version": "0.5.0",
     "ember-cli-babel": "^5.1.3",
     "ember-cli-content-security-policy": "0.4.0",
diff --git a/package.json b/package.json
index d899e08..8207866 100644
--- a/package.json
+++ b/package.json
@@ -22,7 +22,7 @@
     "test": "grunt validate --verbose"
   },
   "engines": {
-    "node": "~0.10.0 || ~0.12.0",
+    "node": "~0.10.0 || ~0.12.0 || ~5.x",
     "iojs": "~1.2.0"
   },
   "dependencies": {
```

The former is required, because certain dependencies of Ember 1.13.8 do not compile against the V8 version included in NodeJS 5.0.0. The latter simply adds NodeJS 5.0.0 as an allowed NodeJS version.

**Comment by jgillich** [comment]
`npm install istanbul -g` should make it go away. See https://docs.npmjs.com/files/package.json#peerdependencies

**Comment by devurandom** [comment]
So this is not an issue of Ghost, but an unnecessarily alarming message by NPM?

**Comment by jgillich** [comment]
Yep it's just a warning, you can ignore it if you don't want to generate the coverage report.

**Comment by devurandom** [comment]
Ok. I've added the patch to #5821 and will close this.
