### ISSUE TITLE
Custom markdown

### ISSUE THREAD

**Issue by flip111** [TryGhost/Ghost#6085]
It would be nice if the user can define his own custom markdown, either blog wide or specific per post. I find myself writing a blog where i want to color things red and blue in the middle of the text, and having to use `<font color="red">foo</font> <font color="blue">bar</font>` all the time. It would be nice if i define my own custom markdown, some thing like `red*foo* blue*bar*`

**Comment by ErisDS** [comment]
Hi @flip111, 

To request a feature for Ghost you can add your idea (or vote on a similar one) over on our [wishlist](http://ideas.ghost.org). We use this list to help determine what goes into the roadmap and how to prioritise features. You can also access the wishlist any time from inside the Ghost admin:
![](http://puu.sh/jXKwm.png)
