### ISSUE TITLE
Checkbox labels can be cut off on mobile

### ISSUE THREAD

**Issue by kevinansfield** [TryGhost/Ghost#6089]
I noticed new Public API labs flag description is cut off on mobile (screenshot 1). Checkbox labels have `white-space: nowrap` which means that it's necessary to keep labels short in case they overrun screen edges at mobile sizes.

I'm assuming this is because letting them wrap means that the wrapped text appears directly under the checkbox (screenshot 2)

What is the desired display of checkboxes if the label is wrapped? Should the left edge of wrapped text be aligned instead of wrapping underneath?

screenshot 1 (cut off label):
![img_1433](https://cloud.githubusercontent.com/assets/415/11247705/256db190-8e15-11e5-9c5e-269b69e359ae.PNG)

screenshot 2 (wrapped label):
![img_1434](https://cloud.githubusercontent.com/assets/415/11247710/29b44408-8e15-11e5-9788-6db7d1078f49.PNG)

**Comment by kevinkucharczyk** [comment]
In my opinion the left edge of the wrapped label should be aligned.

**Comment by JohnONolan** [comment]
Forgot about this. It's set to not wrap cause there's no easy way to make the indentation work properly. Perhaps "For full instructions ... " should be in a <p> beneath this checkbox - for now

**Comment by kevinkucharczyk** [comment]
Removing the `white-space: nowrap;` rule and adding `overflow: auto;` to the `p` (inside the checkbox label) tag seems to work well (on Chrome at least):

![screenshot-localhost 2368 2015-11-19 14-37-56](https://cloud.githubusercontent.com/assets/3127419/11272189/60676f46-8ecb-11e5-9c4d-7331eac0f8be.png)
