### ISSUE TITLE
share on linkedin

### ISSUE THREAD

**Issue by ackepenek** [TryGhost/Ghost#6093]
I am using 0.7.1 version of Ghost. There are facebook, twitter and gplus sharing button. But I can not see linkedin sharing button.

![image](https://cloud.githubusercontent.com/assets/1234305/11270282/3b8dc4a4-8ec6-11e5-97ff-3cc73dd02505.png)

**Comment by ErisDS** [comment]
Hi @ackepeneksorry to hear you're having trouble. The screen shot you've included here shows Ghost's custom theme [Casper](https://github.com/TryGhost/Casper). Ghost themes are 100% customisable so you can make it show whatever you like. You can find a guide and the full documentation on our [support site](http://support.ghost.org/ghost-themes-overview/).

If you have further questions about Ghost themes or need help, please head on over to slack - https://ghost.org/slack/ - and post in the #themes channel. There you can get help & support from the Ghost community, which we're not able to do here in the GitHub bug tracker.
