### ISSUE TITLE
Accessing unknown tag shows 500 instead of 404

### ISSUE THREAD

**Issue by kevinansfield** [TryGhost/Ghost#6094]
Steps to reproduce:

1. Visit http://localhost:2368/ghost/settings/tags/unknown/ (making sure you don't already have a tag with the slug `unknown` :wink: )
2. You are shown the 500 error screen

Expected result:

- 404 response from the API is handled gracefully
- You are shown the 404 "not found" screen

![screen shot 2015-11-19 at 16 08 29](https://cloud.githubusercontent.com/assets/415/11276039/5694080a-8ed8-11e5-80e1-b031c0fc9225.png)

**Comment by acburdine** [comment]
@kevinansfield of note: this happens with editor routes as well

**Comment by kevinansfield** [comment]
@acburdine Good point, I had tried it with the content screen which also exhibits weird behaviour (no error, just shows an existing post and doesn't redirect) but missed the `/editor/x` route

**Comment by acburdine** [comment]
I can pick this one up. The team route is the only one that works correctly at the moment.

**Comment by kevinansfield** [comment]
Yeah, that's because it loads the user in a really roundabout way (see #6095) so doesn't hit the problem. We should definitely be handling 404s in a generic manner.

You _should_ be able to use the `error` action on the `application` route.

**Comment by acburdine** [comment]
Ok. I can take care of both of those then.
