### ISSUE TITLE
commit 55564e3 has dependency that is too new for node.js

### ISSUE THREAD

**Issue by lazzarello** [TryGhost/Ghost#6096]
I just cloned the git repo and I'm building against master.

`grunt init` results in this exception

```
/Users/lazzarello/src/ghost/node_modules/request/node_modules/hawk/node_modules/boom/lib/index.js:5
const Http = require('http');
^^^^^
Loading "Gruntfile.js" tasks...ERROR
>> SyntaxError: Use of const in strict mode.
Warning: Task "init" not found. Use --force to continue.

Aborted due to warnings.
```

Which is caused by the use of the `const` keyword in the "boom" library. This keyword is used all over the place, as the the `'use strict'` declaration. This results in ghost not building on OS X 10.11.1 and node v0.10.13

Do I have to upgrade node? V8? Not sure how deep I should go down this rabbit hole.

Halp plz.

**Comment by ErisDS** [comment]
Have you got one of those modules installed globally? I cannot reproduce the issue on OSX 10.10.4 & node v0.10.13. I do recommend updating to the latest node in 0.10, 0.10.40 to take advantage of security patches, but otherwise 0.10 is fine.

**Comment by ErisDS** [comment]
Ignore that, I have managed to reproduce this and track down what's wrong, looking for a fix.

**Comment by ErisDS** [comment]
Not sure if a fix is going to be possible. Have raised this against [request](https://github.com/request/request/issues/1921) and [hawk](https://github.com/hueniverse/hawk/issues/157). 

I think it's possibly more to do with the very old version of npm than of node, but updating to >0.10.25 should fix it, and 0.10.40 is best (again, there are security patches).

**Comment by lazzarello** [comment]
I figured it would be an upstream thing. I might just try s/const /var /g on that file and see if I get lucky  :)

Thanks for your help. It does look like there's a low level change in the JavaScript language that ads some new types, namely the `const` data type.

**Comment by lazzarello** [comment]
OH boy, now I have to figure out version pinning in homebrew. I just did `brew install node

**Comment by lazzarello** [comment]
Okay, I realize this isn't really a *ghost issue* in terms of the application source code but it's a build pipeline thing so I'm gonna keep talking.

I'm using homebrew for package management. I had to install a "tap" of an older version of node, like so

```
$ brew update
$ brew unlink node
$ brew install homebrew/versions/node010
$ node --version
v0.10.40
```

ALL BETTER.

So the moral of this story is the node.js version requirement for ghost is **strict**. Though the inclusion of the `'use strict'` operational mode along with the inclusion of the `const` data type seems to be okay with 0.10.40 but not a point lower.

Thanks for listening!

**Comment by ErisDS** [comment]
The issue in the dependency tree has been fixed.
