### ISSUE TITLE
Unable to access Ghost over wifi network

### ISSUE THREAD

**Issue by dufia** [TryGhost/Ghost#6097]
Usually when I develop something responsive, I connect my phone to the wifi and simply access it via ip address like http://192.168.0.8:3000/. Super easy.

I start ghost:

Ghost is running in development... 
Listening on 127.0.0.1:2368 
Url configured as: http://localhost:2368 

http://127.0.0.1:2368/ nothing
Tried http://192.168.0.8:2368/ nothing

Any idea? Thanks!

**Comment by ErisDS** [comment]
Hi @dufiasorry to hear you're having trouble. If you have questions about Ghost or need help, please head on over to slack - https://ghost.org/slack/ - and post in the #help channel. There you can get help & support from the Ghost community, which we're not able to do here in the GitHub bug tracker.
