### ISSUE TITLE
Trying to load admin, crashes with blank screen (RegExp sticky)

### ISSUE THREAD

**Issue by keithamus** [TryGhost/Ghost#6102]
### Issue Summary

When I try to visit my ghost blog admin (https://keithamus.ghost.io/ghost/) from Chrome 48 I get a blank page. The console reports a stack trace.

### Steps to reproduce

1. Visit https://keithamus.ghost.io/ghost/ in Chrome 48

### Technical details

```
Uncaught TypeError: RegExp.prototype.sticky getter called on non-RegExp object
  (anonymous function) @ vendor.min.js?v=cd1ced3087:42
  (anonymous function) @ vendor.min.js?v=cd1ced3087:42

Uncaught Error: Could not find module `ember-resize/services/resize` imported from `ghost/initializers/resize`
  o @ vendor.min.js?v=cd1ced3087:1
  i @ vendor.min.js?v=cd1ced3087:1
  r.state @ vendor.min.js?v=cd1ced3087:1
  e @ vendor.min.js?v=cd1ced3087:1
  requireModule @ vendor.min.js?v=cd1ced3087:1
  (anonymous function) @ vendor.min.js?v=cd1ced3087:19
  default @ vendor.min.js?v=cd1ced3087:19
  (anonymous function) @ ghost.min.js?v=cd1ced3087:1
  r.state @ vendor.min.js?v=cd1ced3087:1
  e @ vendor.min.js?v=cd1ced3087:1
  requireModule @ vendor.min.js?v=cd1ced3087:1
  (anonymous function) @ ghost.min.js?v=cd1ced3087:17
```

Cleared cache a few times but no dice. 

Chrome 48.0.2560.0 dev (64-bit)
Mac OSX 10.11.1

Firefox 44.0a2 works fine.

**Comment by ErisDS** [comment]
Hi @keithamus. This sounds to me like a Chrome 48 bug rather than something we can resolve?  I am unable to reproduce on Chrome 46 (stable) or Chrome 49 (canary). Ghost only officially provides support for the latest (stable) and one previous version in each major version.

The only other thing I can think of is if you have some content in a post causing errors. Very unlikely, but worth checking if you can reproduce in Chrome canary.

**Comment by kevinansfield** [comment]
I've likewise been unable to reproduce with 46 (stable), 47 (beta), or 49 (canary). Chrome 48 doesn't seem to be available on any of the official channels right now.

**Comment by keithamus** [comment]
Chrome 48 is the dev channel btw. I'm also able to reproduce on Chrome Canary 49 in guest most (incognito+no extensions).

<img width="961" alt="screen shot 2015-11-20 at 11 40 16" src="https://cloud.githubusercontent.com/assets/118266/11299071/85ca8db2-8f7b-11e5-83d7-0ec6c9fe57cc.PNG">

**Comment by keithamus** [comment]
FYI the offending line is calling the code `RegExp.prototype.sticky` which throws the error. Try pasting that into a Chrome console, e.g. canary, and you get the same eror.

**Comment by kevinansfield** [comment]
It sounds like this may be something to do with your particular setup because `Version 49.0.2569.0 canary (64-bit)` in incognito with no extensions is working fine here on OS X 10.11.1.

![screen shot 2015-11-20 at 11 46 54](https://cloud.githubusercontent.com/assets/415/11299179/6c2fff80-8f7c-11e5-8252-f778ce9ada03.png)

**Comment by keithamus** [comment]
I looked a little further and I have `Enable Experimental JavaScript` enabled which seems to be causing the issue.

I'll close this, enjoy the rest of your day!

**Comment by magikMaker** [comment]
I am experiencing a similar problem, when I look at the MDN docs for `RegExp.prototype.sticky`, it seems it's not supported in any browser. I am using Chrome 48 on OSX and get an error when trying to view the source of files in stash/bitbucket (self hosted)
https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/RegExp/sticky

`Uncaught TypeError: RegExp.prototype.sticky getter called on non-RegExp object(anonymous function) @ batch.js?analytics-enabled=true&locale=en-US&nps-not-opted-out=true&supportedApplication=true:forma…:4212(anonymous function) @ batch.js?analytics-enabled=true&locale=en-US&nps-not-opted-out=true&supportedApplication=true:forma…:4606
batch.js?locale=en-US:11 Uncaught Error: No bitbucket/internal/widget/sidebarv @ batch.js?locale=en-US:11g @ batch.js?locale=en-US:13require @ batch.js?locale=en-US:17(anonymous function) @ bower.json:39
bower.json:39 Uncaught TypeError: Cannot read property 'load' of undefined(anonymous function) @ bower.json:39(anonymous function) @ bower.json:39
batch.js?locale=en-US:11 Uncaught Error: No bitbucket/internal/layout/basev @ batch.js?locale=en-US:11g @ batch.js?locale=en-US:13require @ batch.js?locale=en-US:17(anonymous function) @ bower.json:39
batch.js?locale=en-US:11 Uncaught Error: No bitbucket/internal/layout/repositoryv @ batch.js?locale=en-US:11g @ batch.js?locale=en-US:13require @ batch.js?locale=en-US:17(anonymous function) @ bower.json:39
batch.js?locale=en-US:11 Uncaught Error: No bitbucket/internal/layout/branchv @ batch.js?locale=en-US:11g @ batch.js?locale=en-US:13require @ batch.js?locale=en-US:17(anonymous function) @ bower.json:39
batch.js?locale=en-US:11 Uncaught Error: No bitbucket/internal/layout/filesv @ batch.js?locale=en-US:11g @ batch.js?locale=en-US:13require @ batch.js?locale=en-US:17(anonymous function) @ bower.json:39
batch.js?locale=en-US:11 Uncaught Error: No bitbucket/internal/page/sourcev @ batch.js?locale=en-US:11g @ batch.js?locale=en-US:13require @ batch.js?locale=en-US:17(anonymous function) @ bower.json:39
batch.js?locale=en-US:11 Uncaught Error: No bitbucket/internal/layout/base/menu/recent-reposv @ batch.js?locale=en-US:11g @ batch.js?locale=en-US:13require @ batch.js?locale=en-US:17(anonymous function) @ bower.json:39
batch.js?locale=en-US:11 Uncaught Error: No graphs/feature/recent-peoplev @ batch.js?locale=en-US:11g @ batch.js?locale=en-US:13require @ batch.js?locale=en-US:17(anonymous function) @ bower.json:39
batch.js?locale=en-US:242 Failed to run init function: TypeError: b.require is not a function
function (){var e=b.data.claim("com.atlassian.plugins.atlassian-nps-plugin:nps-acknowledgement-resources.analytics-enabled-data-provider");if(e==="true"){a()}else{c.bind("analytics-policy-acknowledged",function(){a()})}}`

**Comment by ErisDS** [comment]
That error is coming from bitbucket, not from Ghost :wink:

**Comment by magikMaker** [comment]
ooops, sorry my bad.

**Comment by EdwardBeckett** [comment]
@keithamus I had `chrome://flags enable-experimental` enabled for ES6 and apparently it breaks several chrome apps...  Thanks for the notice... helped fix a bunch of broken $4i7

**Comment by magikMaker** [comment]
@EdwardBeckett Awesome!!! This helped me so much, I reset all flags to defaults. (I had made changes so long ago, I didn't even remember)...

:+1:  I'm glad I posted here after all (despite wasting some people's time)

**Comment by corinna000** [comment]
This helped me too. Thank you!

**Comment by timruffles** [comment]
@kevinansfield would be worth bumping the version of XRegExp to fix this, and avoid future problems. https://github.com/slevithan/xregexp/issues/121

**Comment by ErisDS** [comment]
@timruffles a PR would be very welcome :wink: :+1:

**Comment by ErisDS** [comment]
Gonna reopen this with the fix wanted label, seeing as there's a nice fix.

**Comment by kevinansfield** [comment]
This also crashes in Apple's new "[Safari Technology Preview](https://developer.apple.com/safari/technology-preview/)" that has added a lot more es6 compatibility.
