### ISSUE TITLE
Bookshelf & Knex upgrade

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#6103]
Bookshelf & knex did not get upgraded at the start of this release cycle. This was because there was a reasonable amount of work to do, and I got carried away with other work before I completed it. I very much regret this, as several of the filter, include, etc features I've been building into our model layer would have been simpler had I had access to the newer features.

I did try out upgrading to bookshelf@0.8.2 & knex@0.8.6, it did not cause any test regressions (and iirc I ran the old casper.js test suite against this). The current versions are bookshelf@0.9.1 and knex@0.9.0, and so there's been another significant update which warrants testing.
- [x] Update bookshelf
- [x] Update knex

At the start of the next release cycle, I want to get this upgrade done ASAP.  I'll be using this issue to document everything that I know can or needs to be changed as a result of the upgrade.
- [ ] Bookshelf now has a [serialize](http://bookshelfjs.org/#Model-instance-serialize) method that is called by `toJSON`. It should be possible to use the new structure to override `serialize` instead of `toJSON` in places in our codebase, and simplify our code.
- [ ] Bookshelf now has count methods which may be useful
- [ ] Knex has a new [modify](http://knexjs.org/#Builder-modify) method that should make it easier to construct complex query builders from pre-defined parts.
- [ ] Knex should be getting a new `countDistinct` method we can use to replace some horrible `knex.raw` code in the pagination plugin (should be in knex 0.9.1)
- [ ] Knex now supports nested transactions, may be useful for improving our post & tag saving code
- [ ] Knex has had significant improvements to the join syntax which we may be able to leverage

Even newer:
- [ ] Bookshelf has got a pagination plugin and a `fetchPage` method that we can use instead of our own.

Things to be aware of:
- The pool handling software has changed completely in knex since 0.7. There are some open issues around pools and so some significant testing might be in order.

**Comment by brightbits** [comment]
Really need this, with a non-perfect PG connection, current version of `knex` just crashes the whole app any time a connection dies, instead of closing it and reconnecting. This is now handled nicely in `0.8.6`

**Comment by ErisDS** [comment]
The library updates are done, but none of the code changes / potential improvements are done yet.

**Comment by ErisDS** [comment]
Bookshelf 0.9.5 (merged by #6836) has its own pagination plugin (finally!) it may be worth looking at dropping ours in favour of theirs.

**Comment by ErisDS** [comment]
Can close this. Bookshelf is actively maintained again, and at some point we'll look into catching up again. When we do, this information is here. Right now the built in `fetchPage` doesn't seem stable, so should stick to our own implementation for a bit longer probably.
