### ISSUE TITLE
File upload by type

### ISSUE THREAD

**Issue by lazzarello** [TryGhost/Ghost#6111]
I would like to upload files to my blog. It appears the only method to upload files is through the markdown tag `![]()` and the drag + drop or URL copy + paste event. When I try and upload a file which is not a raster or vector image, but a different type of file, I get an error that "The image type you uploaded is not supported. Please use .PNG, .JPG, .GIF, .SVG" but the file I'm uploading is not an image. Is it impossible to upload a file that isn't an image?

**Comment by acburdine** [comment]
At the moment, yes. If you're looking to put a file in and access it from a theme, you should just be able to put the file in the theme folder and reference it via the 'asset' helper.

**Comment by lazzarello** [comment]
I was thinking more of something like a file of source code from an application to be delivered as the mime type application/octet-stream

My goal is to distribute files through my own hosting provider, not a cloud service. I feel old fashioned.

**Comment by acburdine** [comment]
Currently because of the way Ghost works, you would have to modify core in order to support any type of uploading/downloading.

**Comment by lazzarello** [comment]
Interesting. Not impossible (I work as a software engineer) though I'm just tryna blog for now. I'll check out the source. Thanks! Leaving this open if I make some progress.

**Comment by ErisDS** [comment]
Hi @lazzarello - Ghost intentionally works this way. If you want to upload files other than images, these should be added to a CDN or you could run your own file service which is tailored & optimised for serving files. I believe it is beyond the scope of Ghost to be a file service, but you can also add/vote for this feature on the [wishlist](http://ideas.ghost.org).

**Comment by alexgleason** [comment]
I too would like to see this feature. ideas.ghost.org linked above redirects to the Ghost homepage.

I think it's a reasonable argument that file uploads are out of scope, but I also think there are legitimate use cases for it that make sense. Ghost is not a file storage tool, it's a publishing platform; but what if file uploads are part of the narrative? Ghost *does* do a good job of offering embeds for third-party platforms. For example, if you're writing about a genre of music you might embed SoundCloud tracks in the post to help serve the narrative. But if you don't have a SoundCloud account and don't want to upload there for whatever reason, you'll need to fall back on a homegrown solution.

There are ways to work around it. You can upload the file directly into Ghost's data directory yourself, then either link to it inline or create an HTML block for a nice download button. But this is just an inconvenience, and it would be nice if Ghost would just put the file on the server for me.

Personally, I'd be happy if a setting in Ghost's config file could be enabled to let us drop in a file of any type. It uploads into the same directory as images and just creates an inline piece of text with the filename and a link. I think this would only require letting the config variable override the file type check, and then defining the on-drop behavior for a non-image file.
