### ISSUE TITLE
Recommendation for insecure installation guide

### ISSUE THREAD

**Issue by joepie91** [TryGhost/Ghost#6112]
Since there doesn't seem to be a repository for the documentation, and I don't currently have the time to figure out how to work with readme.io, I'm filing the issue here.

The [deployment documentation](http://docs.ghost.org/pl/installation/deploy/) currently suggests [this guide](http://0v.org/installing-ghost-on-ubuntu-nginx-and-mysql/), amongst a few others - however, following said guide will result in Ghost running as root, which is __extremely insecure__.

I would suggest that this guide be removed from the list of guides, so as to prevent any further insecure setups. It would perhaps also be wise to post an announcement somewhere to people who have followed said instructions, encouraging them to review their setup and ensure that Ghost does not run as root.

EDIT: It also runs `npm install` as root, which is both unnecessary and a significant security risk.

**Comment by killswitch** [comment]
# Update November, 21 2015
> These instructions are years out of date. If you want to self-host Ghost you should be finding another tutorial

**Comment by dbalders** [comment]
I do not believe you can get to those docs anymore without a direct link. The updated docs are now [here](http://support.ghost.org/getting-started/), so closing the issue.
