### ISSUE TITLE
Changing Post date Resets to Current Time Every Minute

### ISSUE THREAD

**Issue by JohnWestlund** [TryGhost/Ghost#6114]
I've only tested this in Chrome [Mac Version 46.0.2490.86 (64-bit)]. But if you start typing in a post's date field the time gets switched to 'now', and if you happen to cross over into the next menu while still updating it resets to that time.

**Comment by kevinansfield** [comment]
Thanks for reporting. Closing this as the bug is already being tracked in #5777
