### ISSUE TITLE
Bug:ghost start fail with big mysql (out off memory)

### ISSUE THREAD

**Issue by globetour** [TryGhost/Ghost#6120]
### Steps to Reproduce

1. I use ghost with mysql,if the mysql database have small article,it is start right.
2. but i have 250,000 articles in mysql,then i run npm start,it tips "out off memory" after a long time .
3.i think ghost check something when start,and it is not necssary.

### Technical details

* Ghost Version: master - latest commit:  INSERT COMMIT REF
* Client OS: WINDOWS 10
* Server OS: CENTOS 7.0
* Node Version: 
* Browser:

**Comment by globetour** [comment]
it is display the erro from debug:
sql: 'update `settings` set `created_at` = ?, `created_by` = ?, `id` = ?, `key` = ?, `type` = ?, `updated_at` = ?, `updated_by` = ?, `uuid` = ?, `value` = ? where `id` = ?' }

**Comment by globetour** [comment]
[root@VM_87_97_centos hsdhwcom_news]# npm start --production -d
npm info it worked if it ends with ok
npm info using npm@1.4.28
npm info using node@v0.10.40
npm info prestart ghost@0.7.1
npm info start ghost@0.7.1

> ghost@0.7.1 start /data/wwwroot/hsdhwcom_news
> node index

{ __cid: '__cid1',
  sql: 'select * from information_schema.tables where table_schema = ? and table_name = ?',
  output: [Function],
  bindings: [ 'hsdhwcom_news', 'settings' ] }
{ __cid: '__cid2',
  method: 'select',
  options: undefined,
  bindings: [ 'databaseVersion', 'currentVersion' ],
  sql: 'select `value` from `settings` where `key` = ? or `key` = ?' }
Migrations: Up to date at version 004
{ __cid: '__cid1',
  method: 'select',
  options: undefined,
  bindings: [ 'not_available' ],
  sql: 'select `clients`.* from `clients` where `secret` = ?' }
{ __cid: '__cid2',
  method: 'select',
  options: undefined,
  bindings: [],
  sql: 'select `settings`.* from `settings`' }
{ __cid: '__cid1',
  method: 'select',
  options: undefined,
  bindings: [],
  sql: 'select `settings`.* from `settings`' }
{ __cid: '__cid2',
  method: 'select',
  options: undefined,
  bindings: [],
  sql: 'select `permissions`.* from `permissions`' }
{ __cid: '__cid1',
  method: 'select',
  options: undefined,
  bindings: [ true, 'published' ],
  sql: 'select count(`posts`.`id`) as `aggregate` from `posts` where `page` = ? and `status` = ?' }
{ __cid: '__cid2',
  method: 'select',
  options: undefined,
  bindings: [ false, 'published' ],
  sql: 'select count(`posts`.`id`) as `aggregate` from `posts` where `page` = ? and `status` = ?' }
{ __cid: '__cid1',
  method: 'select',
  options: undefined,
  bindings: [ 'active', 'warn-1', 'warn-2', 'warn-3', 'warn-4', 'locked' ],
  sql: 'select count(`users`.`id`) as `aggregate` from `users` where `status` in (?, ?, ?, ?, ?, ?)' }
{ __cid: '__cid3',
  method: 'select',
  options: undefined,
  bindings: [],
  sql: 'select count(`tags`.`id`) as `aggregate` from `tags`' }
{ __cid: '__cid4',
  method: 'select',
  options: undefined,
  bindings: [ 'active', 'warn-1', 'warn-2', 'warn-3', 'warn-4', 'locked' ],
  sql: 'select `users`.* from `users` where `status` in (?, ?, ?, ?, ?, ?) order by `users`.`last_login` DESC, `users`.`name` ASC, `users`.`created_at` DESC' }
{ __cid: '__cid5',
  method: 'select',
  options: undefined,
  bindings: [],
  sql: 'select `tags`.* from `tags`' }
{ __cid: '__cid6',
  method: 'select',
  options: undefined,
  bindings: [ 'permalinks', 1 ],
  sql: 'select `settings`.* from `settings` where `settings`.`key` = ? limit ?' }
{ __cid: '__cid7',
  method: 'select',
  options: undefined,
  bindings: [ 'permalinks', 1 ],
  sql: 'select `settings`.* from `settings` where `settings`.`key` = ? limit ?' }
{ __cid: '__cid1',
  method: 'select',
  options: undefined,
  bindings: [ 'installedApps', 1 ],
  sql: 'select `settings`.* from `settings` where `settings`.`key` = ? limit ?' }
{ __cid: '__cid3',
  method: 'select',
  options: undefined,
  bindings: [ true, 'published' ],
  sql: 'select `posts`.* from `posts` where `page` = ? and `status` = ? order by `posts`.`status` ASC, `posts`.`published_at` DESC, `posts`.`updated_at` DESC, `posts`.`id` DESC' }
{ __cid: '__cid4',
  method: 'select',
  options: undefined,
  bindings: [ false, 'published' ],
  sql: 'select `posts`.* from `posts` where `page` = ? and `status` = ? order by `posts`.`status` ASC, `posts`.`published_at` DESC, `posts`.`updated_at` DESC, `posts`.`id` DESC' }
{ __cid: '__cid5',
  method: 'update',
  options: undefined,
  bindings: 
   [ Sat Nov 21 2015 10:57:28 GMT+0800 (CST),
     1,
     18,
     'installedApps',
     'app',
     Tue Nov 24 2015 10:28:03 GMT+0800 (CST),
     1,
     'db7b4f54-aa45-40e4-9878-91f1a41d87fe',
     '[]',
     18 ],
  sql: 'update `settings` set `created_at` = ?, `created_by` = ?, `id` = ?, `key` = ?, `type` = ?, `updated_at` = ?, `updated_by` = ?, `uuid` = ?, `value` = ? where `id` = ?' }
FATAL ERROR: CALL_AND_RETRY_2 Allocation failed - process out of memory
Aborted (core dumped)

**Comment by jgillich** [comment]
*250 000* articles? I don't think Ghost is designed for that. Increasing your server's RAM might help, but why do you have so many articles?

**Comment by globetour** [comment]
yes,i have very much articles...

**Comment by ErisDS** [comment]
Hi @globetour, GitHub is an issue tracker - it is not the place to get personal support. If you need help with your install of Ghost, please come by the #help channel in [slack](https://ghost.org/slack).

Going to close this and your other issue as they seem to be very related & both very specific to your situation. In this case, [disabling the update check](http://support.ghost.org/config/#update-check) may help. Adding indexes to your databases is the best approach, but this is not something that would be done in code (as you mention in #6135), but in the database itself.
