### ISSUE TITLE
Use gender neutral or abstract default user image

### ISSUE THREAD

**Issue by boennemann** [TryGhost/Ghost#6124]
Hey all,

I noticed that the default image that is used for every new user is showing a man, or at least has characteristics like a broad back and a short hairstyle, that are usually associated with men.

![](https://raw.githubusercontent.com/TryGhost/Ghost/a7a14fac228466acbc3f4a876753ab7f8830d7e3/core/shared/img/user-image.png)

I think that software shouldn't make these assumptions about what a default user looks like, what is normal or not. Replacing this image by either a gender neutral version, or using an abstract one ([like before](https://github.com/TryGhost/Ghost/blob/7193f05376d6ad621327fc9c8b88c92e10988d17/core/shared/img/user-image.png)) could help make more people feel comfortable using Ghost.

This suggestion is inspired by Lena Reinhard's ["A talk about everything"](https://youtu.be/CZx7rYoq1Uw?t=16m13s). I've linked to the relevant position where she talks about male defaults in software. I'd recommend watching the whole talk though :)

Best,
Stephan

**Comment by ErisDS** [comment]
@boennemann Totally :+1: on this, just need to come up with a plan for the replacement. I started looking to see if there was a node module that would generate us a random (but not gross) background colour + 2 letters (i.e. initials) or something similar as you may have seen elsewhere. This is the closest I've found so far: https://github.com/MatthewCallis/avatar

Also whilst we're at it, it'd be good to replace the placeholder name/email on signup and setup. I picked John H. Watson as a bit of fund and a play on the common John Smith, but something gender neutral (Cameron Howe or Jamie Curtis?!) would be much better.

**Comment by nuclearpengy** [comment]
Background colour with initials sounds like a cool idea. :)

**Comment by cwonrails** [comment]
@boennemann @ErisDS What do you think of Jamie Watson for the placeholder name/email?

**Comment by kirrg001** [comment]
I'm going to close this issue. This issue is very old and if this pops up again, we can reopen it.
