### ISSUE TITLE
How to serve files using ghost in my blog?

### ISSUE THREAD

**Issue by adamcavendish** [TryGhost/Ghost#6132]
How to serve files using ghost in my blog? I'd like to share a file in one of my posts.

**Comment by ErisDS** [comment]
@adamcavendish please see my comment on #6111. If you have more questions about Ghost or need help, please head on over to slack - https://ghost.org/slack/ - and post in the #help channel. There you can get help & support from the Ghost community, which we're not able to do here in the bug tracker.
