### ISSUE TITLE
Blog content deleted after reboot

### ISSUE THREAD

**Issue by robcalcroft** [TryGhost/Ghost#6134]
I did some maintenance to my server, kernal upgrade, reboot and i noticed my Ghost blog content is now gone when i rebooted the node server :fearful:

**Comment by ErisDS** [comment]
It sounds like you restarted Ghost in the wrong environment, see http://support.ghost.org/config#about-environment.

If you need further help, please drop by the #help channel in [slack](https://ghost.org/slack/), GitHub ishuge software bugs/issues.

**Comment by robcalcroft** [comment]
Thats it! thanks :smile:
