### ISSUE TITLE
how add force index to tags article list pages sql

### ISSUE THREAD

**Issue by globetour** [TryGhost/Ghost#6135]
my tags article list pages is slowly because i have 250,000 posts,
so i want to add force index to the sql like that: 
select * from XX force index(AAA) on B=C where.......
but i found that the ghost tags page sql like that(\core\server\models\base\utils.js):
        if (filterObjects.tags) {
            itemCollection
                .query('join', 'posts_tags', 'posts_tags.post_id', '=', 'posts.id')
                .query('where', 'posts_tags.tag_id', '=', filterObjects.tags.id);
        }
where can i add the force index in it?
anyone can help me ? thanks

**Comment by ErisDS** [comment]
Closing as explained here: https://github.com/TryGhost/Ghost/issues/6120#issuecomment-160288424
