### ISSUE TITLE
Uncaught TypeError: Cannot read property 'map' of undefined issue

### ISSUE THREAD

**Issue by Jonasyao** [TryGhost/Ghost#6137]
when I was changing the admin profile image, I see the following error in chrome console.

Ember.Mixin.create.serializeHasMany	@	vendor.min.js?v=a093de001e:24

**Comment by ErisDS** [comment]
Hi @Jonasyao, I'm sorry to hear you're having problems but there's not enough information here for us to reproduce the problem. Please can you update this bug report with details about your environment? There is a [bug report template](https://github.com/TryGhost/Ghost/blob/master/CONTRIBUTING.md#bugs) in our [contributing guidelines](https://github.com/TryGhost/Ghost/blob/master/CONTRIBUTING.md) that should give you a good idea what sorts of info to include.

**Comment by ErisDS** [comment]
This is possibly a CloudFlare or nginx file size configuration issue. Closing for now, will reopen if a non-config reproduction case is found.
