### ISSUE TITLE
Access Denied from url

### ISSUE THREAD

**Issue by littleStudent** [TryGhost/Ghost#6138]
I just upgraded ghost from 0.7.0 to 0.7.2. The blog is running, but i can not access the admin panel because of the following error:
`Access Denied from url: www.myURL.com. Please use the url configured in config.js.`
I did not change any of the settings, neither did the domain change.

in config.js the following url is configured: `url: 'http://myURL.com'

Am I missing something?

**Comment by ErisDS** [comment]
The URL you login from must exactly match that in your config.js file as of 0.7.2. `www.` is a subdomain and is not the same as the root domain. The error message is documented & explained here: http://support.ghost.org/config/#url.

Please update your config.js file (or log in from the correct URL).

**Comment by littleStudent** [comment]
perfect thx! 
changing config.js to `url: "http://www.myURL.com"` fixed this.
