### ISSUE TITLE
Theme with no package.json warning for .git directory

### ISSUE THREAD

**Issue by JonathanPerkins** [TryGhost/Ghost#6140]
Ghost 0.7.2 now emits the following warning at startup:

   Warning: Found a theme with no package.json file 
     Theme name: .git 
   This will be required in future. Please see http://docs.ghost.org/themes/ 

Ghost should ignore a content/themes/.git directory if present.

**Comment by sebgie** [comment]
Hey @JonathanPerkins that's a good catch!

Would you mind providing a bit more details about your environment by using our [bug template](https://github.com/TryGhost/Ghost/issues/new?title=Bug%3A&body=%23%23%23%20Issue%20Summary%0A%0A%23%23%23%20Steps%20to%20Reproduce%0A%0A1.%20This%20is%20the%20first%20step%0A%0AThis%20is%20a%20bug%20because...%0A%0A%23%23%23%20Technical%20details%0A%0A*%20Ghost%20Version%3A%20master%20-%20latest%20commit%3A%20%20INSERT%20COMMIT%20REF%0A*%20Client%20OS%3A%20%0A*%20Server%20OS%3A%20%0A*%20Node%20Version%3A%20%0A*%20Browser%3A%20%0A*%20Database%3A)? Knowing the content of your theme directory would be also helpful (how many themes, location of the `.git` folder, ...).

**Comment by JonathanPerkins** [comment]
Sorry, hadn't spotted the bug template!

### Issue Summary

### Steps to Reproduce

1. This is the first step

This is a bug because...

### Technical details

* Ghost Version: 0.7.2 release
* Client OS: Mac OS X 10.11.1
* Server OS: Mac OS X 10.11.1 
* Node Version: 4.2.2
* Browser: Safari
* Database: Sqlite 3.1.1

This is on my test setup, I have just have one of my own themes and casper, so the the content/themes directory has the following directories/files in it:

.git/
.gitignore
casper/
jonathan/

HTH,
Jonathan
