### ISSUE TITLE
Ghost with contentful

### ISSUE THREAD

**Issue by ishandutta2007** [TryGhost/Ghost#6142]
Is there any customized version of Ghost app using using contentful-management.js APIs
Or do people use  https://github.com/sdepold/contentful-ghost-importer to copy data to contentful.

**Comment by ErisDS** [comment]
Hi @Ishandutta2007, if you have questions about Ghost or need help, please head on over to slack - https://ghost.org/slack/ - and post in the #help channel. There you can get help & support from the Ghost community, which we're not able to do here in the GitHub bug tracker.
