### ISSUE TITLE
Cannot upload user profile cover

### ISSUE THREAD

**Issue by garyc40** [TryGhost/Ghost#6146]
This happens on Safari and Chrome.

### Steps to Reproduce

1. Go to Admin -> Team -> Click on a team member.
2. Click on Change Cover
3. Upload a file

The file appears to be uploaded but nothing happens on the front-end. There's an error message in dev console:
Uncaught TypeError: this.complete is not a function

Screen cap:
![upload](https://cloud.githubusercontent.com/assets/52500/11491932/fe98b668-9829-11e5-9185-05b1d86fbec2.gif)

### Technical details:
* Ghost Version: master (latest commit: c884e67)
* Client OS: Mac OS X 10.11
* Node Version: 0.10.40
* Browser: Chrome 46.0.2490.86

**Comment by ErisDS** [comment]
@garyc40 Thank you for taking the time to write an awesome bug report :+1:
