### ISSUE TITLE
Fresh Install fails on grunt init

### ISSUE THREAD

**Issue by framerate** [TryGhost/Ghost#6156]
Following the new readme, grunt init gets me:

```Warning: Command failed: /bin/sh -c /home/ubuntu/_www/framerate/ghost/node_modules/.bin/bower --allow-root install
bower                                      ECONFLICT Unable to find suitable version for ember```

during the shell:bower task

I'm using node 4.2.2. I'm not an ember guy, nor do I use bower anymore. Any suggestions?

**Comment by kevinansfield** [comment]
Hi @framerate, it sounds like you'll need to clear your existing bower cache first. Try `grunt clean` followed by `npm install` and then `grunt init`.

I'm closing this as Github is for tracking bugs and product development issues rather than help requests. We have a #help channel on our [https://ghost.org/slack/](slack team) for support, if you're still having issues please pop by! :smile:

**Comment by framerate** [comment]
No problem @kevinansfield 

I might go as far that this *is* a bug. If so, I see two fixes:

- Update the readme to include the options listed above (unless I missed them)
- change grunt init script to include cleaning caches?

I'm a pretty heavy node user so I would imagine I'm the key demographic for installing via README, so one of these might be in the best interest?

Let me know your feels, I can probably fix either of them myself to give back!

**Comment by kevinansfield** [comment]
@framerate sorry, I missed the fact that you said "fresh install" - I've only seen that error appear when I already have something in my `core/client/bower_components` directory which is what `grunt init` clears (along with the two `node_modules` directories). I've just tried to reproduce with a fresh install and have been unable to force the error.

> Update the readme to include the options listed above (unless I missed them)

`grunt clean` definitely shouldn't be part of the fresh install instructions as it's a developer tool to clean up from existing installations either when switching between branches with different dependencies or just to ensure a clean setup before an upgrade.

It is mentioned in the [troubleshooting guide](http://support.ghost.org/troubleshooting/#fix-for-general-npm-install-errors) but it could probably be more prominent for problems with the `bower install` part of installing client dependencies.

> change grunt init script to include cleaning caches?

That's not something `grunt init` should be doing - in the *vast* majority of cases there is no need to nuke and re-build the app's dependency tree but only to install new/updated packages and re-build the client files.

**Comment by framerate** [comment]
Yeah it's odd. This is on a fresh micro-instance on AWS if that helps.

I did the steps you suggested and got a different error about ember during grunt init, but I think this one is due to AWS and not you guys:

```FATAL ERROR: Malloced operator new Allocation failed - process out of memory
Aborted
Warning: Command failed: /bin/sh -c echo Installing client dependencies... && npm install
npm WARN deprecated lodash-node@2.4.1: This package is no longer maintained. See its readme for upgrade details.
npm WARN deprecated find-file@0.1.4: Use the globby package instead
npm WARN deprecated lodash-node@3.10.1: This package is no longer maintained. See its readme for upgrade details.
npm WARN deprecated lodash@2.4.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^3.0.0.
FATAL ERROR: Malloced operator new Allocation failed - process out of memory
Aborted
 Use --force to continue.```

I just kept cleaning/init-ing and finally it seemed to go through. That first one though was odd. It was definitely stuck on a fresh install until I did the grunt clean.

Maybe it's just a "broke on my machine" type issue and I'll let it die for now :)

Thanks for the info!

**Comment by kevinansfield** [comment]
Yeah that error message points to memory issues (the WARN lines can be ignored), `npm` is notoriously memory hungry when installing but I'm not sure about `bower`.

I know with the cheapest digital ocean servers we recommend setting up a swap partition to avoid memory errors - it may be something that's needed for AWS micro instances too: https://www.digitalocean.com/community/tutorials/how-to-add-swap-on-ubuntu-14-04
