### ISSUE TITLE
Arabic titles are made using grave accents '`' in url slugs

### ISSUE THREAD

**Issue by cartove** [TryGhost/Ghost#6163]
giving an article an Arabic title containing chars that doesn't exist in English replaces it with '`' grave accent.. which make issues with nginx and requires extra configurations. and for Arabic speaker, it doesn't make any sense to use them.

**Comment by halfdan** [comment]
Can you give a specific example of a text that shows this behaviour?

**Comment by cartove** [comment]
I made few things actually with the latest release of ghost

this title For ghost this is a test post :
 عشان جوست.. ده بوست تجربة : http://manegm.com/%60shn-jwst-dh-bwst-tjrb/
I discovered this too in tags,
http://manegm.com/tag/%60syrmkh/
looks like it replaces the letter Ain ' ع' with '`'.

If Arabic Ain is doing this probably Hebrew Ayin 'ע' has the same issue.


I reviewed the whole Arabic Alphabet, and it seems like it translate the Letter Alef to nothing...
Given a title full of Alef it generates no slug. letter Alef " ا " , Alef With Hamza " أ "

**Comment by ErisDS** [comment]
This is likely a bug in https://github.com/FGRibreau/node-unidecode. We are also starting to get a lot of requests to not do transliteration in slugs. This whole area needs revisiting by someone with good knowledge of what the best practices are.

E.g. should Ghost transliterate by default, but have an option to disable it by default? Or should it transliterate for all punctuation chars but not all letter/word chars?

Is there a better module out there we could be using to generate slugs? A quick google turned up this: https://github.com/sbtoledo/node-url-slug but it is based on iconv which is going to cause install problems.

**Comment by cartove** [comment]
I think yes @ErisDS  you're right the bug is from node-unidecode, I even saw few forks trying to work around this issue in the repo.

I am speaking about Arabic and possibly Hebrew as they're very similar, First of all the transliteration isn't readable, for example يلعب means to play in transliteration it's yl'b but it should be yalaab or as we do when we're don't have Arabic support yal3ab, so anyone who reads the slug it won't make sense to him. which means urls with numbers will do the same job.

Also I think for SEO using the original title in the url makes it ranked higher in localized search.

I think what's important now is at least making ghost bug free, removing the '`' from slugs will make it work as we can have much more time discussing the best practices.

**Comment by ErisDS** [comment]
Happy to see a PR for a fix either here or on unidecode :+1:

**Comment by cartove** [comment]
I made a quick fix and a pull request to fix only this case in unidecode , but I am still not very satisfied, after taking a look at the Arabic unicode data on the project, I found many mistakes that makes it unreadable, I'll take a look later. but this should fix this issue for now, waiting for someone with write access to merge it to the main repo.

https://github.com/FGRibreau/node-unidecode/pull/12

Also, I found many grave accents in many unicode files, I may dig deeper in this later.

**Comment by FGRibreau** [comment]
@cartove hello! I am the maintainer of unidecode, I will happily merge any PR related to Arabic unicode :)

**Comment by ErisDS** [comment]
@cartove as someone who is both comfortable on GitHub and understands the arabic language, you're invaluable to projects like node-unidecode ;) Please go through and fix as many issues as you can :+1: - Ghost and other projects will benefit enormously. For now I can fix this particular bug by upgrading to the latest version of unidecode which includes the fix you added.
