### ISSUE TITLE
is it possible to use {{content characters="x"}} counting from other than the first character?

### ISSUE THREAD

**Issue by tyranni** [TryGhost/Ghost#6164]
Hello ghosts :)
I'm working on a template to post some upcoming music events. The event's date should have an other style then the rest of the content. My idea is to allways start the post content with the date in a specific format (ie 8 characters -> 03.12.15). In the template I use {{excerpt characters="8"}} and style it as I like. 
Now I'd like to get the rest of the post and style it in another way. Is there any way to get {{content}} starting from the 9th character?
Thanks for any help!!!

**Comment by halfdan** [comment]
Hi @tyranni,
is there any reason you can't use the `published_at` field that every post has?

We use Github only for tracking bugs with Ghost and have a separate help channel in our Slack: https://ghost.org/slack/

**Comment by tyranni** [comment]
Hi @halfdan ,
Oh yes, there is ;). The music event's dates are mostly in the future and not at the date the post is published ;). 
Thanks for the Slack-hint ;). I'll try to get some help there.
Thanks again and sunny greetings :)!

**Comment by ErisDS** [comment]
If you want to request this as a feature, you can do so on the [wishlist](http://ideas.ghost.org) 😉
