### ISSUE TITLE
Ghost haven't support on NodeJS 5.x yet

### ISSUE THREAD

**Issue by thakerng** [TryGhost/Ghost#6169]
I got an installation error  
``Ghost needs Node version ~0.10.0 || ~0.12.0 || ~4.2.0 you are using version 5.1.0``

**Comment by ErisDS** [comment]
The error message would have said this:

```
ERROR: Unsupported version of Node
Ghost needs Node version ~0.10.0 || ~0.12.0 || ~4.2.0 you are using version 5.1.0
Please see http://support.ghost.org/supported-node-versions/ for more information
```

Please read the linked document http://support.ghost.org/supported-node-versions/

**Comment by iamchairs** [comment]
Wow. And we're supposed to "Try Ghost" ?
