### ISSUE TITLE
Convert "feature" controller to a service

### ISSUE THREAD

**Issue by kevinansfield** [TryGhost/Ghost#6170]
We are currently using this [feature controller](https://github.com/TryGhost/Ghost/blob/master/core/client/app/controllers/feature.js) to provide access to various feature/labs flags throughout the app. Our use of feature flags has been limited so far so we haven't run into many issues but increased use of labs settings will mean more and more areas will have logic involving feature flags.

There are a couple of issues that I can see with the current setup:

1. Controllers cannot be injected into components which means that the `feature` controller needs to be injected into a parent controller and then passed in through the template
2. [Reading/saving feature flags](https://github.com/TryGhost/Ghost/blob/master/core/client/app/controllers/settings/labs.js#L14-L42) is distributed between both the `labs` controller and the `feature` controller

I propose converting the `feature` controller into a service (fixes issue 1) and expanding that service to handle both reading and writing of labs/feature flags (fixes issue 2).

**Comment by acburdine** [comment]
This sounds like a good idea. I can take a crack at implementing it over the next couple of days (in between writing acceptance tests :stuck_out_tongue:)
