### ISSUE TITLE
Select component raises error on change

### ISSUE THREAD

**Issue by kevinansfield** [TryGhost/Ghost#6171]
Steps to reproduce:

1. Log in as an admin
2. Load a user page for a non-admin user
3. Use the select box to change the user role
4. Click save
4. Reload page

Expected result: User now has their new role

Actual result: Upon selecting a new role with the select box, the following error is generated and the subsequent save does not update the role:

![screen shot 2015-12-04 at 16 00 39](https://cloud.githubusercontent.com/assets/415/11594161/551a49f2-9aa0-11e5-8460-08dcfba1b18a.png)

**Comment by kevinansfield** [comment]
This was probably introduced when switching to `es6` syntax, should be quite a simple fix.

**Comment by chris-yoon90** [comment]
Hi Kevin,

I also see the same error when I try to select different themes in the admin panel.

Thanks,
Chris

**Comment by kevinansfield** [comment]
Yeah, it's an issue in our select component. I'll change the title to be more generic. Thanks for the additional report :smile:
