### ISSUE TITLE
Get all tags and show in index .

### ISSUE THREAD

**Issue by martinop** [TryGhost/Ghost#6175]
How i can get all tags createds without repeat, and show in index.hbs?
I try with:
{{#foreach tags}}
{{#if tags}}
{{tags separator=" | "}}
{{/if}}
{{/foreach}}
but dont show nothing.

I read and i think that i want can work with Get helper, but I have the version 0.7.1

**Comment by ErisDS** [comment]
Hi @martinop - you are correct, you need the get helper. For questions about Ghost or if you need help, please head on over to slack - https://ghost.org/slack/. GitHub is our bug tracker and we are not able to do support here.

**Comment by martinop** [comment]
Thanks and sorry.
