### ISSUE TITLE
Can't embed code for contest gallery in blog post

### ISSUE THREAD

**Issue by theasoko** [TryGhost/Ghost#6177]
I'm trying to embed javascript code from the Woobox platform into a blog post to use it as a host for my photo contest gallery. Ghost doesn't recognize or implement the code. This is what it looks like:

<div id='woobox-root'></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//woobox.com/js/plugins/woo.js";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'woobox-sdk'));</script>

**Comment by ErisDS** [comment]
Hi @theasoko, I see you found our #help channel in [slack](https://ghost.org/slack). That is the correct place for getting support for your blog :+1:
