### ISSUE TITLE
Tags with non-latin characters are not recognized

### ISSUE THREAD

**Issue by mspanc** [TryGhost/Ghost#6180]
Tags with non-latin characters seem not to be recognized by Ghost.

While this works:

https://wojciechkozmic.herokuapp.com/tag/obwod-luganski/

this gives 404 Not Found:

https://wojciechkozmic.herokuapp.com/tag/chark%C3%B3w/

ghost 0.7.0

**Comment by ErisDS** [comment]
Tags should not have non-latin characters in their slugs, the same as posts, these should be transliterated. Can you please update this bug report to contain the full steps of how you managed to get into this state? There is a bug report template in our [contributing guidelines](https://github.com/TryGhost/Ghost/blob/master/CONTRIBUTING.md#bugs) that will give you an idea what to include.

**Comment by mspanc** [comment]
Surprisingly I am unable to reproduce this - it transliterates this correctly for me, and it's another user who made this. Closing for now.
