### ISSUE TITLE
Improve SEO & structured data generation

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#6186]
For more context see the frontend refactor epic: #5091

----

At the moment, the generation of SEO data (like the meta title and description), and structured data e.g. the og and twitter meta tags, and schema.org/JSON LD data is all buried deep within the theme helpers `meta_title`, `meta_description` and `ghost_head`.

The data that is output depends on a number of factors, such as whether the structured data has been disabled via a privacy flag. However, the most important factor which determines what data is output, is the context:

E.g. are we outputting data for a single post or page, or is this the first page of a particular channel (index, tag or author), or something else?

Moving forward, I would like for the SEO & Structured data generation to be moved into its own, highly configurable and dynamic module - it would probably live happily inside of `/server/data/xml/` for now along with the rss and sitemap functions as these things are all quite heavily related. 

The aims of doing this are:
1. to make it possible & easy to output structured data for new contexts, e.g. custom channels
2. to make the helpers as simple as possible. Ideally, we'd like to be able to change `meta_title` and `meta_description` to be output by `ghost_head` to resolve #4424. 
3. to vastly improve the level of configurability / customisation possible

The majority of the code which needs moving is that in `ghost_head`. 

The calculations for what the full `meta_title` & `meta_description`also need to be moved. Ideally the 'pattern' used for the `meta_title` would become part of the configuration for a context. 

On getting a request, Ghost should be able to easily determine the meta title and description for the context, and then pass down that information to all further middleware / rendering / helpers. Grabbing the structured data to output should become a function call.

Right now, we're just at the point where we have a concept of "channel config" in the frontend controller. Slowly but surely we're moving towards the entirety of the frontend being dynamically-generated from configuration (ref #5091). As that progress happens, progress on this issue should be able to happen alongside.

**Comment by jtwebman** [comment]
@ErisDS I can start on this one.

**Comment by ErisDS** [comment]
Cool :+1: 

It's one of the major blockers for [channels](https://github.com/TryGhost/Ghost/wiki/Channels-101), I have a branch lying around that I work on every time I have 5mins which has dynamic channels working with the exception that the contexts & meta data are all still hard coded. Getting this done would be a boon.

**Comment by jtwebman** [comment]
@ErisDS I am close to done on the first phase for this one. This is the code so far. I still have about 8 more methods that need tests written for them. https://github.com/TryGhost/Ghost/compare/master...jtwebman:meta_data_to_functions
