### ISSUE TITLE
Filter content list by tag

### ISSUE THREAD

**Issue by kevinansfield** [TryGhost/Ghost#6190]
I've been working on a spike of the filtering functionality of #6165 but it's shown that there are a number of issues that conflate to make this more than a small job.

My current thinking of how this will all eventually come together:
- [ ] Use query params to filter content list, e.g. `http://localhost:2368/ghost/?filter=tags:getting-started` (limited to `tags:` for now)
  - [ ] Initial model loading and pagination control will need to be moved into the controller as routes don't have access to query-params in ember at the moment (I believe that will be changing with routable-components)
- [ ] Modify the auto-complete search to recognise `tag:` or `tags:` then show a list of all tags that can be further filtered as you type, e.g. `tags:get` would only show tags that match the term `get`
  - [ ] On selecting one of the "filter" tags, the URL changes to include relevant query params and the `tag:selected-tag` filter is shown as a token in the search field
  - [ ] Manually visiting a filtered posts list via `http://localhost:2368/ghost/?filter=tags:getting-started` should automatically fill in the `tag:getting-started` filter token
  - [ ] Leaving the filtered posts screen should clear the search box so that it returns to it's previous functionality
  - [ ] On screens that support filtering, change the search box's placeholder to `Search / Filter`
- [ ] Add links to tags list on tags management screen that link back to the posts list with the relevant filter

This would also be laying the groundwork for additional filter params e.g. `page:true` and filtering other screens such as being able to filter the tags management list with `hidden:true`.

---

One potential pain point is our current reliance on `ember-cli-selectize` for the auto-complete search - the addon is internally complicated/limited due to it's need to translate all-things-ember in to/out of `jquery-selectize` compatible structures and it's reliance on selectize's search methods. Our planned move to `ember-power-select` should open a lot more power and flexibility in this regard but as that's a fair job in itself it may be necessary to come up with a half-way house in terms of features/ease of use in the meantime.

**Comment by ErisDS** [comment]
I think clicking a tag in the content screen might also be a good way to trigger a filtered list?

My ideal v1 is just having a way to get to the filtered list and a way to get back out again. Could be click tag in list -> filtered, click 'content' button again -> unfiltered? It's going to be behind a flag for now :grin:

**Comment by kevinansfield** [comment]
:+1: I have that more-or-less working already but it needs some work to pull the posts loading and pagination from the route down into the controller in order to smooth over the rough edges. I'll see what I can do with that tomorrow, I'm hoping the existing pagination mixin can be repurposed easily enough.

My only concern is somehow indicating that the posts list is filtered - unless the URL changing is enough for now?

**Comment by ErisDS** [comment]
I think the URL changing might be enough, would be good to see it in action. 

Alternatively perhaps there's a way to indicate that there is a removable filter in the content title block:
![](http://puu.sh/lOXd0.png)

It depends really on how it feels with no indicator & also how hard it would be to hack in the filter into the autocomplete bar. I'm not sure what the challenges there are.

I'm thinking perhaps even just having the word 'filtered' with an x as an item in there whenever the content list is filtered, would be enough, if that is easier than making it specific to the filter that is in action. 

As long as all this sits behind a labs flag, there's room to play with it a bit :grin:

**Comment by kevinansfield** [comment]
Closing and adding a reference to the [content screen overhaul](https://github.com/TryGhost/Ghost/issues/7860) issue.
