### ISSUE TITLE
Add `limit`, `from` and `to` attributes for `{{tags}}` and `{{#foreach}}` helpers

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#6205]
Both the `{{#foreach}}` and `{{tags}}` helpers are used to loop through collections of data in Ghost themes.

`{{#foreach}}` allows for looping over any collection and executing a template block for each item in the collection. `{{tags}}` automatically loops through a tag collection if there is one in the current scope / context, and outputs a link for each tag in a comma separated list. 

Both of these loops are a little bit limited in that they loop over all the data, without much control, beyond things like the `@first` or `@odd` properties available inside the `{{#foreach}}` list.

To give theme developers more control over their templates, this proposal is to add `from`, `to` and `limit` as attributes to both of these helpers.

The rules are as follows:

- `limit` allows for setting how many items to loop over. If there are not enough items, the loop will have to stop early ;)
- `from` determines the first item that should be output
- `to` determines the last time that should be output. 
- As `from` and `to` are explicit, they take precedence over `limit`, and if both are set, `limit` will be ignored.
- The default value for `from` is the beginning of the collection
- The default value for `to` is the end of the collection

The result will allow for the following:

`{{tags limit="1"}}` - output just one tag
`{{tags from="1" to="1"}}` - also outputs just the first tag

`{{#foreach "posts" from="1" to="3"}}` - outputs the first, second and third post
`{{#foreach "posts" from="4" limit="3"}}` - outputs 3 posts starting from the 4th post
`{{#foreach "posts" from="3"}}` - outputs all posts starting from the third post until the end of the list
`{{#foreach "users" to="5"}}` - outputs posts until and including the 5th post - the same as `limit="5"`
`{{#foreach "posts" from="4" to="5" limit="3"}}` - outputs just the 4th and 5th post

Note: I'm proposing`from` and `to` are both 1-indexed, not 0-indexed, that is, we start at item 1, not at item 0. I started writing examples with a 0-index, which is normal for a loop in JS and it made a lot less sense and started to confuse me just as I was writing examples - that's not a good sign, so I switched! E.g. With a 1-index, `to="5"` and `limit="5"` are equivalent, with a 0-index `limit="5"` becomes equivalent to `to="4"`.

This is consistent with the first item being called `@first` and not `@zeroth`. Additionally, we recently added a `@number` property which is 1-indexed because the default handlebars `@index` property was 0-indexed which is not that useful. However, I'm very open to hearing arguments for the alternative version.

- [x] Add `limit` to `{{tags}}`
- [x] Add `limit` to `{{foreach}}`
- [x] Add `from` to `{{tags}}`
- [x] Add `from` to `{{foreach}}`
- [x] Add `to` to `{{tags}}`
- [x] Add `to` to `{{foreach}}`
- [x] Fix `@last` when using `limit` with `{{#foreach}}`
- [ ] Support negative indexes in `from` and `to` on both `{{tags}}` & `{{foreach}}`

**Comment by twanlass** [comment]
@ErisDS this is looking good. Agreed on the 1 based index as well (just document this!).

Thoughts on how you could grab the last X items of a resource? Negative indexes?
`{{#foreach "posts" from="-1" to="-5"}}`

Something else?

**Comment by ErisDS** [comment]
@twanlass That's an interesting question. Negative indexes make sense, I think?

**Comment by twanlass** [comment]
Yea, just an easy way to get posts from the end as well. Granted there's not a huge use case I'm sure so it may not be needed. I think w/ the new get helper and filtering you can do just about anything now :-D

**Comment by ErisDS** [comment]
Limit has shipped in 0.7.3, but whilst writing documentation, it occurred to me that my implementation did not account for making `{{@last}}` work when using `{{#foreach}}` and `limit`. Whoops. That'll need resolving when this gets tackled.

**Comment by johnny94** [comment]
Hello, I am new to this project. I think I can help to add these attributes to the helpers. May I take this?

**Comment by KyleSevenoaks** [comment]
When outputting multiple foreach loops, each with a {{#has tag...}} helper, one limit attribute applies to all the foreach loops, is this by design? :)

**Comment by ErisDS** [comment]
@KyleSevenoaks interesting, could you provide an extended example? It doesn't sound correct but it would be helpful to have a full reproduction case to be sure.

**Comment by ErisDS** [comment]
@KyleSevenoaks I've not been able to reproduce what you're describing. If you can provide an example that breaks that would be great.

This issue has been sat open with the intention of potentially adding reverse/negative indexes, but I'm struggling to think of a clear use case for this behaviour. If anyone has one please post here, and we'll consider reopening but for now I'm going to close this issue as complete.
