### ISSUE TITLE
[OS X] Unable to type letter 'Ż' in editor

### ISSUE THREAD

**Issue by tomob** [TryGhost/Ghost#6209]
On keyboard mapping for Polish language on OS X, the letter Ż is typed with alt-shift-z. Ghost's editor captures this combination for some reason.

The bug occurs in text fields in Post Settings. It **does not** occur in the tab editor.

Behavior tried in Firefox, Chrome and Safari.

**Comment by acburdine** [comment]
@tomob if you are using ghost 0.7.2, this is a known regression and a fix will be included in the next release.

**Comment by tomob** [comment]
Actually I use 0.7.1. If the fix is on the way, I'll close the issue, since a simple workaround is possible (copy-paste).

Thank you.
