### ISSUE TITLE
Unable to directly load a post that's not in the first page

### ISSUE THREAD

**Issue by kevinansfield** [TryGhost/Ghost#6215]
Steps to reproduce:
1. Ensure you have enough posts to require infinite scrolling on the content list (> 15)
2. Scroll to the bottom of the content list and select a post that is only shown after infinite scroll has loaded more (eg. http://localhost:2368/ghost/1/)
3. Reload the page or visit the URL for the selected post manually
4. You should see that the selected/visible post is the first post in the list, not the post that was requested. If you scroll down and select the post that you tried to load you will be unable to view it

Expected outcome:
- The requested post is shown
- The requested post is selected and visible in the posts list
- Scrolling up/down will load in the pages before/after the currently selected post

**Comment by ErisDS** [comment]
Part of me thinks this might be a known limitation? @novaugust might remember or be quicker at finding the related issues, I remember this went back and forth a bit.

**Comment by novaugust** [comment]
I definitely remember an issue that devolved into a huge debate and ended up going nowhere ;) I'll go fishing

**Comment by kevinansfield** [comment]
Yeah, it's a limitation of how our pagination currently works. I'll see if I can dig up some old code where I had to solve this for loading the middle of a long message stream into an infinite scroll area.

**Comment by novaugust** [comment]
I really couldn't dig anything up, but I'd swear we ran into this before.
At the very least, it should be possible to query for exactly the post on the route and add it to the store so that it can be viewed, but beats me if that'll screw up later pagination (don't think so?)

**Comment by kevinansfield** [comment]
Yeah, I think querying and adding it to the list should work. For the few times it will occur, having additional entries load in above the bottom post shouldn't be much of an issue - however if we want to auto-scroll so that the selected post is visible in the list then it will keep looping until all pages before that post have loaded.

**Comment by ErisDS** [comment]
This is the closes thing I could find to a conversation about this: https://github.com/TryGhost/Ghost/pull/4346

**Comment by kevinansfield** [comment]
Closing and adding a reference to the [content screen overhaul](https://github.com/TryGhost/Ghost/issues/7860) issue.
