### ISSUE TITLE
Bug: Setting up Ghost admin user

### ISSUE THREAD

**Issue by desiredpersona** [TryGhost/Ghost#6226]
I just installed Ghost 0.7.2 locally on my mac.

When going through the install at `127.0.0.1:2368/ghost` on step 3 i decided to click the back button to change the blog title.

Then when i tried to go from step 2 page to step 3 page i got the error "You are not logged in" when i clicked the green button "Last Step: Invite Your Team"

<img width="818" alt="screen shot 2015-12-15 at 13 11 49 error" src="https://cloud.githubusercontent.com/assets/2799922/11811890/2657ebcc-a330-11e5-9764-97cd3e8e2e77.png">

The only way to get back to step 3 was to click on the green 3 at the top of the step 2 page which is not obvious to end user.

**Comment by Jameskmonger** [comment]
+1, can reproduce in a clean install

**Comment by Jameskmonger** [comment]
The `NoPermissionError` is being thrown in `core/server/api/authentication.js` in `updateSetup(object, options)`
