### ISSUE TITLE
Password reset doesn't complete

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#6229]
The password reset form isn't completing it's job of resetting your password and logging you in with your new password.

Filling out the form and hitting submit seems to send the data to the `submit()` function on the controller, but it gets stuck somewhere after. There doesn't seem to be an ajax call, and there's no redirect.

**Comment by ErisDS** [comment]
Seems to me that the call to `validate()` is not working somehow. There are no errors and that code doesn't get executed.

The only thing I could spot so far were double parenthesis here: https://github.com/TryGhost/Ghost/blob/master/core/client/app/controllers/reset.js#L40

Stumped :/

**Comment by kevinansfield** [comment]
Yeah, it was a bit of a strange one. We were swallowing errors in the `.catch` which is always helpful when trying to debug :grimacing:

Inspecting the error raised showed that the validation engine was failing with the error `model.get is undefined` which also seemed very strange until realising that we were actually depending on that route not having a `model` - something that I broke when during the `this._super` PR :blush: as `setupController`s default method is to take the model and attach it to the controller.

**Comment by ErisDS** [comment]
I swear I tried logging out the error in all sorts of ways inc arguments, this.get('errors') etc but I never once saw an error message. That was half my bafflement.

I got as far as realising that the only thing it was getting for the model was the `token` in the validation engine validate method, but I had no powers to discern why. Very glad one of us knows this stuff :grin:
