### ISSUE TITLE
Bug: forgot password

### ISSUE THREAD

**Issue by Foutchy** [TryGhost/Ghost#6235]
### Issue Summary
Reset password form is not working (enable to submit) - Clean install

### Steps to Reproduce

1. This is the first step
Filling the form ghost/reset after clicking the link received by email
Clicking reset password button

### Technical details

* Ghost Version: master - 55045ae (0.7.2)
* Client OS: OSX 10.11.2
* Server OS:  Ubuntu 14
* Node Version: 4.2.0
* Browser:  Chrome Version 47.0.2526.80 (64-bit)
* Database:  Postgres

**Comment by novaugust** [comment]
Hey @Foutchy, this is a known (and fixed) issue #6229. Thanks for the detailed report
