### ISSUE TITLE
Bug: About new restful API

### ISSUE THREAD

**Issue by frankxin** [TryGhost/Ghost#6239]
### Issue Summary
ok ， I try our new API , And I found there is some wrong when i use ajax twice continually

### Steps to Reproduce

1. This is my code
```javascript
          ghost.init({
            clientId: "ghost-frontend",
            clientSecret: "8919dc8debd1"
          });

          jQuery(document).ready(function() {
            $.get(
              ghost.url.api('posts', {
                limit: 3
              })
            ).done(function(data) {
              var $result = $('#blog-posts');
              $.each(data.posts, function(i, post) {
                $result.append(
                  '<li>' + post.title + '</li>'
                );
              });
            });

            $.get(
              ghost.url.api('posts', {
                limit: 3
              })
            ).done(function(data) {
              var $result = $('#blog-posts');
              $.each(data.posts, function(i, post) {
                $result.append(
                  '<li>' + post.title + '</li>'
                );
              });
            });
          });
```
2. The first request is right , and the second one return with an error
![image](https://cloud.githubusercontent.com/assets/6349036/11889059/767627b2-a57f-11e5-8ecc-4762dd70941a.png)
![image](https://cloud.githubusercontent.com/assets/6349036/11889067/94629594-a57f-11e5-8dc9-9d21b3d7266b.png)

**I think this is a bug** because two times use one ghost api closure , In the ghost-url code 
![image](https://cloud.githubusercontent.com/assets/6349036/11889096/12bef34c-a580-11e5-8b60-3d69c38ede1d.png) , they use the same apiUrl variable ，and the second time I call ghost.url.api , they use the same variable.

### Technical details

* Ghost Version: master - latest commit:  INSERT COMMIT REF
* Client OS:  mac
* Browser: chrome latest

**Comment by chripf** [comment]
Have the same issue - tried doing a re-init before using the helper again, but this does not help.

**Comment by frankxin** [comment]
@chripf  Thank you for your reply . I totally agree with your method . And I think i can change the ghost-url.js for my project . Because in one context , if you want to get user after get posts , it would be wrong , the url will be like this `//www.frankxin.com/ghost/api/v0.1/posts/users` . So I want to check if this kind of API is by designed or it's a mistake.

**Comment by halfdan** [comment]
Confirmed, I'm working on a fix.

**Comment by ErisDS** [comment]
This will be closed automatically when the fix is merged.
