### ISSUE TITLE
Redirect Loop appears when visit /ghost/ on HTTPS port other than 443

### ISSUE THREAD

**Issue by bohanyang** [TryGhost/Ghost#6245]
Config.js:
 - url: http://example.com
 - urlSSL: https://example.com:12222
 - forceAdminSSL: true

Visiting http://example.com/ghost/ will redirect me to https://example.com:12222/ghost/

And then https://example.com:12222/ghost/ will redirect me to https://example.com:12222/ghost/

That's the LOOP...

**Comment by ErisDS** [comment]
Hi @bohanyang, sorry to hear you're having trouble. This sounds like a duplicate of #2796 (there's lots of info on that issue), please make sure you have setup your webserver configuration correctly: http://support.ghost.org/setup-ssl-self-hosted-ghost/.

If you need more help, please head on over to slack - https://ghost.org/slack/ - and post in the #help channel. There you can get help & support from the Ghost community, which we're not able to do here in the GitHub bug tracker.

**Comment by bohanyang** [comment]
Nginx: `proxy_set_header       X-Forwarded-Proto $scheme;`
