### ISSUE TITLE
Hardcoded environments prevent customization

### ISSUE THREAD

**Issue by tunylund** [TryGhost/Ghost#6246]
Hi,

As a feature the https://github.com/TryGhost/Ghost/blob/master/config.example.js-file seems to support named environments as in:

```
production: {...},
staging: {...},
'some-custom-env': {...}
```

Unfortunately the codebase seems to be riddled with hardcoded environment configurations: https://github.com/TryGhost/Ghost/blob/0.7.3/core/server/errors/index.js#L124
(As a result no error logging will occur if the environment-name differs from the default 3 environments.)

This prevents users having any other named environment besides 'development', 'staging' or 'production'. Is there any plan on supporting named environments or is the design of ghost such that it allows only those 3 environments?

**Comment by ErisDS** [comment]
No plan to change this as it's never been questioned before & I'm not sure what the use case would be. The concept of development and production modes are pretty standardised. Feel free to raise feature request on our [wishlist](http://ideas.ghost.org).

**Comment by tunylund** [comment]
Sure. Thanks for the reply!

**Comment by cookiejest** [comment]
hey, does staging actually work? I do not think it does.
