### ISSUE TITLE
500/422 error on tags started with number and hyphen

### ISSUE THREAD

**Issue by fengkaijia** [TryGhost/Ghost#6247]
After 0.7.1 (which worked), when accessing the page of a tag begin with number and a hyphen, whatever the tag exist or not, for example: https://example.com/tag/2016-election/ a 500 (or 422 using the Ghost demo) error is returned:

```
Parse error on line 1:
tags:2016-election
---------^
Expecting 'OR', 'AND', 'RPAREN', 'RBRACKET', got 'NOT'
```

When there's no hyphen, everything worked. For example https://example.com/tag/24hour/ And after remove the number and hyphen part, everything works again.

**Comment by ErisDS** [comment]
@fengkaijia, thanks for the clear bug report. I've seen this error a couple of times and not known what was causing it, the only way I could reproduce was with badly formatted API calls. Now I know the cause I should be able to get it fixed up pretty quickly.

**Comment by ErisDS** [comment]
I've got a PR in for a quick fix. The underlying issue is the same as this: https://github.com/TryGhost/GQL/issues/3 and is going to require a bit of a redesign of GQL's lexer, I think
