### ISSUE TITLE
Repeated 401s on the editor report back as Server Not Available, rather than offering another login

### ISSUE THREAD

**Issue by novaugust** [TryGhost/Ghost#6249]
### Issue Summary
The password reauth that pops up on the editor after a session expires only gives you one chance to get it right. If you typo your password, rather than coming up again with "Password invalid, give it another go", Ghost just gives up and shows a "Server unavailable" error on the repeated 401s

### Repro

1. go to ze editor
2. kill your session
3. hit save
4. enter an incorrect password in the reauth modal
5. hit save
6. be sad, you have to reload the page now

### Specs
- ghost 0.7.3
- chrome 47

**Comment by kevinansfield** [comment]
I believe this has been mostly fixed in #6088

**Comment by ErisDS** [comment]
@novaugust This is working nicely for me now, can you confirm?

**Comment by novaugust** [comment]
@ErisDS buenos!
