### ISSUE TITLE
Non-latin characters

### ISSUE THREAD

**Issue by pimka** [TryGhost/Ghost#6250]
Hello!
I use Ghost as an npm module.
I want to create post with non-latin characters. It's looks good when I open the post page.
But when I go to db (MySQL), there are weird symbols in the title, markdown and html fields. 
Because of this, i can't show this data nowhere except Ghost app. For example, I want to show last n posts on the main page of my site.
DB is in utf8 encoding, charset  : 'utf8' in config.js.
Is there a way to fix it?

**Comment by ErisDS** [comment]
Please read this issue, which describes what is occurring: https://github.com/TryGhost/Ghost/issues/5945.

**Comment by pimka** [comment]
Thank you.
