### ISSUE TITLE
{{#has tag='value'}} not working

### ISSUE THREAD

**Issue by mwo44** [TryGhost/Ghost#6252]
Hi,
I'm running Ghost 0.7.3 and I've tried to add a custom menu based on tags, however the helper #has doesn't seem to be working as described in themes.ghost.org/docs/has 
{{#has tag='value'}}custom code here{{/has}}
I've tried the above snipped within #post both in the page.hbs and post.hbs templates with no success.

**Comment by ErisDS** [comment]
Hi @mwo44, sorry to hear you're having trouble. As mentioned in the readme & contrib guide, if you have questions about Ghost or need help, please head on over to slack - https://ghost.org/slack/ - and post in the #help channel. There you can get help & support from the Ghost community, which we're not able to do here in the GitHub bug tracker.
