### ISSUE TITLE
Setup/two fails with fileStorage:false config

### ISSUE THREAD

**Issue by kevinansfield** [TryGhost/Ghost#6253]
Steps to reproduce:

1. Change your `config.js` so that you have `fileStorage: false`
2. Delete (or rename) your dev database then start/restart the ghost server
3. Start the setup process
4. Fill in and submit step 2
5. You should see an infinite spinner and the error `Uncaught TypeError: Cannot read property 'blueimp-fileupload' of undefined` originating from `gh-profile-image`'s `willDestroyElement` method

**Comment by kevinansfield** [comment]
@ErisDS I have a quick-fix for this but wanted to check what the desired behaviour is for the `gh-profile-image` component when `fileStorage:false` is set. It seems that at the moment there's no way to set the image if you have fileStorage disabled, is that right or a separate issue?

**Comment by ErisDS** [comment]
@kevinansfield when `fileStorage:false` is set, it should only be possible to set a URL not upload an image. So the gravatar part should work but there shouldn't be an option to upload your own, I think.
