### ISSUE TITLE
Redirect from non-www to www

### ISSUE THREAD

**Issue by ZengineAlex** [TryGhost/Ghost#6256]
Hey guys,

I'm pretty new in working with Ghost and Node.js apps in general.

Is there an easy way to set a redirect from the non-www url to the www-url ?

Thanks a lot!

**Comment by sebgie** [comment]
Hi @ZengineAlex,

it would be best to add the redirect to your proxy server (Nginx/Apache). It is recommended to use a proxy server for running Ghost and therefore a simple redirect in your configuration would solve that for you.

If you need more help, please head on over to slack - https://ghost.org/slack/ - and post in the #help channel. There you can get help & support from the Ghost community, which we're not able to do here in the GitHub bug tracker.
