### ISSUE TITLE
Missing post tags when searching content via Ghost admin

### ISSUE THREAD

**Issue by vislamov** [TryGhost/Ghost#6257]
### Issue Summary:

Tags are missing when searching content, which leads to a problem when re-saving the post. Tags need to be re-created each time. 

### Steps to Reproduce: 

- Go to admin `/ghost`
- Search for the post, e.g. node 

![image](https://cloud.githubusercontent.com/assets/5131554/11943061/cd3e2ffa-a7ef-11e5-85c1-3419f4b5d2e9.png)

- Click on the post
- Open tags section, all tags are missing except a `node` tag. 

#### Actual result:

![image](https://cloud.githubusercontent.com/assets/5131554/11943102/1691e7e6-a7f0-11e5-849e-01de0d5ec3f4.png)

#### Expected result:

![image](https://cloud.githubusercontent.com/assets/5131554/11943092/07f2fee6-a7f0-11e5-91ed-df7990f544ac.png)

#### Additional observations:

Once post editor page (`/ghost/editor/:id/`) is re-loaded or search repeated the issue is gone, tags appear as expected. 

### Technical details:

Platforms where the issue observed:

* Ghost Version: 0.7.3 / 0.7.1
* Client OS: Mac OS X 10.11.1
* Server OS: Ubuntu 14 / Mac OS X 10.11.1
* Node Version: 0.10.41 / 0.10.38 
* Browser: Chrome Version 47.0.2526.106 (64-bit)
* Database: MySQL / SQLite

**Comment by acburdine** [comment]
Hi @vislamov!

What version of Ghost are you using? I just tried to reproduce this on master and wasn't able to get what you are seeing.

**Comment by ErisDS** [comment]
@vislamov here is a [bug report template](https://github.com/TryGhost/Ghost/blob/master/CONTRIBUTING.md#bugs) in our [contributing guidelines](https://github.com/TryGhost/Ghost/blob/master/CONTRIBUTING.md) that shows the info that it's useful to include with a bug report.

**Comment by ErisDS** [comment]
I was able to reproduce this on 0.7.3 quite easily.

I believe it only happens for posts not yet loaded on the content screen, so posts older than the first 15 you see there.

**Comment by ErisDS** [comment]
Update: I reproduced it a couple of times and am now not able to again.

**Comment by acburdine** [comment]
@ErisDS I can try and work on a fix. I have some idea as to what's causing this.

**Comment by kevinansfield** [comment]
I've just been having a look into this too but haven't been able to find anything yet.

The search itself shouldn't be causing any problems as it doesn't touch the store at all, it simply passes an ID to the edit route as do all other transitions/links to the edit route. The edit route itself should always hit the API as it's using `store.query` which to me suggests it's one of three things:

1. The adapter is sometimes failing to add the `include=tags` param
2. The tags input is sometimes not picking up/reacting to the model tags list properly
3. The server is sometimes not returning all the tags

I've not been able to reproduce yet so haven't been able to narrow it down any further.

**Comment by vislamov** [comment]
@acburdine just updated tech details, it happens on both my dev env (Mac/SQLite) and production (AWS/Ubuntu 14/MySQL). And once  search is performed I can't reproduce it anymore on the same post at least for some time. The only posts I can reproduce it are the ones I haven't opened for a while.

**Comment by ErisDS** [comment]
@acburdine did you get anywhere with this? You said you had an idea what it was but didn't elaborate :wink:. 

@kevinansfield I reproduced this a couple of times, and then couldn't anymore. Is there anything we can do to try to sure up the code without reproduction?

**Comment by kevinansfield** [comment]
> Is there anything we can do to try to sure up the code without reproduction?

Not really, I've been through the relevant code paths and haven't been able to spot anything that may be causing it. Even a sometimes-reproducible case would be very useful, I've not managed to observe the behaviour at all locally so haven't been able to inspect the various object/component states yet.

**Comment by ErisDS** [comment]
@vislamov are you able to reproduce this on Ghost 0.7.4? I did originally but am no longer able to reproduce at all.

**Comment by ErisDS** [comment]
I've tried a couple of quirky things to try to reproduce this including searching from the labs page after loading that page directly, and searching from the tag page after loading that page directly.

I'm testing using a copy of the data from the Ghost blog. I've added a new tag 'kerouac' to the first post (ghost 0.3 - kerouac). This means I have a single tag which pulls up a tag and a post which are definitely not loaded yet. 

I also tried testing the exact same example (post & tag names combo) in the original bug report, both with that post loaded in the first 15 posts, and not loaded. I cannot reproduce :(

**Comment by vislamov** [comment]
@ErisDS yes, I was able to this morning:

![image](https://cloud.githubusercontent.com/assets/5131554/12117311/dda43c0a-b374-11e5-8919-f005dfdedbac.png)

Opened /ghost and searched for "android", clicked on post and got this:

![image](https://cloud.githubusercontent.com/assets/5131554/12117333/037c3d7e-b375-11e5-9eac-0101b3e20f68.png)

Opened new tab did the same thing and got this:

![image](https://cloud.githubusercontent.com/assets/5131554/12117359/2cc412f6-b375-11e5-8e46-1bd3392ca211.png)

**Comment by vislamov** [comment]
Also when I'm trying to leave the page with **missing tags** Ghost thinks that it has been edited:

![image](https://cloud.githubusercontent.com/assets/5131554/12117445/aeec90aa-b375-11e5-9494-4e5186067283.png)

**Comment by kevinansfield** [comment]
@vislamov thanks, that last bit of detail points to there being an issue with the tags input component rather than something lower level. Possibly a race condition somewhere, still difficult to diagnose without being able to replicate locally but at least we're narrowing the potential candidates! :+1:

**Comment by vislamov** [comment]
Also if it helps, the "Stay/Leave" popup appears only when I'm clicking on links like "New Post" or "Content". If I continue search and select different search result, it let's me to switch to it, In this case I don't see the popup.

**Comment by vislamov** [comment]
I can reproduce now on my local box, what can I look into to give you more info?

**Comment by ErisDS** [comment]
@vislamov are the posts which it happens to in the top 15 - the ones that are shown without scrolling when you're on the content page?

**Comment by vislamov** [comment]
@ErisDS yes I can reproduce for the post that shown in the top 15.

To reproduce I have to find posts that can trigger this behavior. In my case on my local box I found two posts: "Java Enterprise" and "Vanilla JavaScript", both shown in top 15. I search for "java" and first click on "Java Enterprise" post. Then I search for "java" again and click on "Vanilla JavaScript" which is missing tags and flagged as changed (I can't leave page w/o popup shown unless I search for other post).

**Comment by vislamov** [comment]
Tags for "Java Enterprise" post:

![image](https://cloud.githubusercontent.com/assets/5131554/12123220/866e216a-b394-11e5-85a9-d20badfd7717.png)

Tags for "Vanilla JavaScript" post:

![image](https://cloud.githubusercontent.com/assets/5131554/12123251/bcec60b2-b394-11e5-9f70-ff6eed15ce44.png)

When tags missing for "Vanilla JavaScript" post I see only one tag:

![image](https://cloud.githubusercontent.com/assets/5131554/12123238/a80c853c-b394-11e5-8b4d-d035e277da24.png)

**Comment by ErisDS** [comment]
Ooooy! I can now reliably reproduce it as well. 

I have a tag 'node' I have 2 posts with titles which also match for the search 'node'.
It always happens on the second search, when I search from the editor, when I'm already on a post which matched for the search.

**Comment by vislamov** [comment]
Yes!

**Comment by ErisDS** [comment]
Proper repro steps: 

I have a tag `node`
I have a post called `Node.js` with the tags `node`, `quick-guide`, `platform` `sdk` (as per the example)
I have a second post called `Magnodetude` with the tags `nodetude`, `Another tag` and `quick-guide`

Note, only Node.js has the node tag, but both have the tag `quick-guide`.
Both posts are published (if they aren't published, the tags disappear forever because they get autosaved and it makes it harder to diagnose/reproduce)

- I start on the content screen
- I search for 'node'
- I open the `Node.js` post in the editor
- I check the tags, they are all there
- I search for 'node' again
- I open the `Magnodetude` post in the editor
- I check the tags, and the shared tag, `quick-guide` is missing.
