### ISSUE TITLE
Breakage after reinstalling node modules

### ISSUE THREAD

**Issue by blfr** [TryGhost/Ghost#6265]
I was running a Ghost blog and it had a minor issue with sending email through Mailgun. I tried troubleshooting, deleted the node_modules directory, and reinstalled with `npm install --production`. After this, the blog became completely unusable. Every page except the post listing returns an error. 

    TypeError: [post.hbs] Expected a SourceNode, string, or an array of SourceNodes and strings. Got function push(source, loc) {
    this.source.push(this.wrap(source, loc));

Even the error page returns the error. 

    Error whilst rendering error page 
    Error template has an error 
    TypeError: [../../../core/server/views/user-error.hbs] Expected a SourceNode, string, or an array of SourceNodes and strings. Got function push(source, loc) {
    this.source.push(this.wrap(source, loc));

I tried a fresh install and it has all the same issues. Here's a [more complete log](https://gist.github.com/blfr/0d0ad07f207a815c388f). 

I'm using the LTS ARM8 build of node v4.2.4 with npm 2.14.12 on Ubuntu 14.04. What might be the problem? What can I do to fix it? 

On the upside, the admin panel loads after a few attempts and email is being sent correctly.

**Comment by blfr** [comment]
I recovered from backup, even upgraded to 0.7.4 without removing existing node_modules, and it works (sans email). 

I cannot however install a fresh 0.7.4 Ghost. It starts but fails as soon as it receives the first request with

    Segmentation fault (core dumped)

and creates this log. 

    0 info it worked if it ends with ok
    1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start', '--production' ]
    2 info using npm@2.14.12
    3 info using node@v4.2.4
    4 verbose run-script [ 'prestart', 'start', 'poststart' ]
    5 info prestart ghost@0.7.4
    6 info start ghost@0.7.4
    7 verbose unsafe-perm in lifecycle true
    8 info ghost@0.7.4 Failed to exec start script
    9 verbose stack Error: ghost@0.7.4 start: `node index`
    9 verbose stack Exit status 139
    9 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:214:16)
    9 verbose stack     at emitTwo (events.js:87:13)
    9 verbose stack     at EventEmitter.emit (events.js:172:7)
    9 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:24:14)
    9 verbose stack     at emitTwo (events.js:87:13)
    9 verbose stack     at ChildProcess.emit (events.js:172:7)
    9 verbose stack     at maybeClose (internal/child_process.js:818:16)
    9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
    10 verbose pkgid ghost@0.7.4
    11 verbose cwd /srv/bloghost/blogdir
    12 error Linux 4.2.0-cavium05-03380-g1d827ad6
    13 error argv "/usr/bin/node" "/usr/bin/npm" "start" "--production"
    14 error node v4.2.4
    15 error npm  v2.14.12
    16 error code ELIFECYCLE
    17 error ghost@0.7.4 start: `node index`
    17 error Exit status 139
    18 error Failed at the ghost@0.7.4 start script 'node index'.
    18 error This is most likely a problem with the ghost package,
    18 error not with npm itself.
    18 error Tell the author that this fails on your system:
    18 error     node index
    18 error You can get their info via:
    18 error     npm owner ls ghost
    18 error There is likely additional logging output above.
    19 verbose exit [ 1, true ]

Occasionally, it survives the first request but this just leads to same errors as before and eventually to a segmentation fault.

**Comment by ErisDS** [comment]
Hi @blfr, I saw you pop up in slack, and then here - I replied to you in slack and didn't hear back from you. We keep GitHub just for bugs/issues with the software and this is very likely an issue with your environment. 

I'm not able to do anything beyond googling for the error codes that you've pasted here, as ARM is a bit off the beaten path, you'd need to debug where the segmentation violation is coming from. If you need a hand chatting through various things to try, then please pop back into slack.

**Comment by akatasonov** [comment]
Having the same problem on arm64, Ubuntu Xenial. node v4.2.6, npm  v3.5.2
