### ISSUE TITLE
Blog title in admin panel as decimal number

### ISSUE THREAD

**Issue by 0xCD** [TryGhost/Ghost#6266]
### Issue Summary
Blog title in admin panel interpreted as a number, if a prefix is "0x"
### Steps to Reproduce
1. Change the name of the blog to "0xCD" (205 in decimal) for example
2. Refresh the page

### Screenshot
![ghost](https://cloud.githubusercontent.com/assets/16162622/12009267/6128e818-acb4-11e5-928f-6097b6bb7b96.png)

**Comment by halfdan** [comment]
Hi @0xCD,
what version are you on? I just tried to reproduce this on master but failed to do so.

**Comment by 0xCD** [comment]
@halfdan, tired with 0.7.4 latest release on OS X and Windows with Node.js v4.2.4.

**Comment by acburdine** [comment]
@halfdan @0xCD I can reproduce it. It doesn't happen right after you change the blog title, you have to refresh the page. Probably due to some sanitation errors.

**Comment by acburdine** [comment]
Figured out what is causing this, and am somewhat at a loss as to how to fix it. Or rather, I know how to fix it, but I'm not sure if there's a better way.

The cause: A while back there was a bug where the ghost-admin client secret (used for admin OAuth) was being interpreted as infinity. To fix it, the admin checks config values to see if they are numbers (which infinity is not). Unfortunately however, it regards "0xCD" (or any other hexadecimal notation) as an actual number, and treats it as such until it is overridden by the saving of the General Settings page.

Possible fixes: It could be hardcoded into the config to explicitly treat the blogTitle as a string. It could also be hardcoded to treat the client secret (the cause of the previous bug) as a string. However, the problem with the second is I believe this bug would still exist.

/cc @kevinansfield

**Comment by ErisDS** [comment]
Hi @acburdine everything you've said made sense, I think it's worth rewriting the code in the [config service](https://github.com/TryGhost/Ghost/blob/3d6856614f019f8fc66248751a15d48f8c1a0b73/core/client/app/services/config.js#L9-L9) to have an explicit type set for each key.

**Comment by acburdine** [comment]
@ErisDS thinking about this too -> would it be perhaps cleaner to specify in the server helper that generates the config meta tags something akin to a type (e.g. say `<meta name='env-blogTitle' content='...' data-type='string'>`

**Comment by ErisDS** [comment]
Also sounds like a good solution :)
