### ISSUE TITLE
Stubborn Navigation Menu

### ISSUE THREAD

**Issue by justinboden** [TryGhost/Ghost#6267]
I'm unable to rearrange the order of menu items in the navigation sidebar.

### Steps to Reproduce

1. Create a new menu item in Navigation settings and approve it to make it draggable
2. Drag the item to a fresh position, say second-from-top
3. Hit save. After the refresh, the item is back in its initial position

First noticed the issue in 0.7.4.

**Comment by acburdine** [comment]
@justinboden I can confirm this, thanks for reporting! Will work on a fix later today.

**Comment by Faber73** [comment]
Applied this modification, no change, not fixed to me.

**Comment by kevinansfield** [comment]
@Faber73 I've double checked and the issue is definitely fixed on master. How did you apply the change?

**Comment by Faber73** [comment]
Like the other, my fault. Sorry.
