### ISSUE TITLE
Import JSON from old ghost blog failed

### ISSUE THREAD

**Issue by Nolski** [TryGhost/Ghost#6271]
I seem to be unable to import a json blog from an old Ghost blog that I had laying around. When uploading the json file all I get is a prompt saying that the import failed and a message displaying `validator is not defined`.

I'm running the blog inside of a [sandstorm](https://sandstorm.io) instance and it is version 0.5.8

**Comment by ErisDS** [comment]
Hi @Nolski, sorry to hear you're having trouble. As mentioned in the readme & contrib guide, if you have questions about Ghost or need help, please head on over to slack - https://ghost.org/slack/ - and post in the #help channel. There you can get help & support from the Ghost community, which we're not able to do here in the GitHub bug tracker. In the meantime, I recommend upgrading your blog to the latest version of Ghost where the issue may already be fixed.
