### ISSUE TITLE
Javascript freezing the browser

### ISSUE THREAD

**Issue by brightbits** [TryGhost/Ghost#6274]
I have a weird problem - when I play around in the back end, the javascript becomes unresponsive and I can’t do anything

it got t the point that when I was updating a few articles, I had to use the quick search in 1 browser, get the edit url, open that url in a different browser, edit the article, then close the tab and start again.

Can anyone suggest a solution or the best way I can track it down - never come across this kind of problem before!

**Comment by nuclearpengy** [comment]
I noticed admin was freezing up today, I'm on Ghost(Pro) so I'm running the latest stable release.

**Comment by brightbits** [comment]
thanks for the info @nuclearpengy nice to know its not just me :)

**Comment by istek** [comment]
my ghost's admin was freezing up. i found when i try to search something ,it would be freezing up.

**Comment by brightbits** [comment]
that was where I noticed the majority of freezing coming from - using the search box

**Comment by Faber73** [comment]
Freezing too sometimes, after searchbox use

**Comment by kevinansfield** [comment]
Hey guys, this definitely sounds like it's an issue for some people so would you mind providing a bit more info about your setups and what the exact symptoms you experience are? We have a [template](https://github.com/TryGhost/Ghost/issues/new?title=Bug%3A&body=%23%23%23%20Issue%20Summary%0A%0A%23%23%23%20Steps%20to%20Reproduce%0A%0A1.%20This%20is%20the%20first%20step%0A%0AThis%20is%20a%20bug%20because...%0A%0A%23%23%23%20Technical%20details%0A%0A*%20Ghost%20Version%3A%20master%20-%20latest%20commit%3A%20%20INSERT%20COMMIT%20REF%0A*%20Client%20OS%3A%20%0A*%20Server%20OS%3A%20%0A*%20Node%20Version%3A%20%0A*%20Browser%3A%20%0A*%20Database%3A) for bug reports that may be useful.

Additional to what's in the bug report template it would be handy to know how many blog posts, tags, and users you have in your blog as that may be a source of the slowdown.

At the moment the auto-complete search is a rather naive client-side only approach that's not suited to very large blogs or memory constrained clients - something we're definitely aware of and that will change once we have server-side search availability.

**Comment by Faber73** [comment]
Kevin, it's looking like the search engine start to search from the first char, and if your blog is full of posts, going to freeze for a X time.

Maybe start to search after thirt char can be a good solution.

**Comment by brightbits** [comment]
I think we have about 137 posts

**Comment by Faber73** [comment]
Me over 400 at this moment. But search a single char it's always a bad job.

**Comment by kevinansfield** [comment]
I've located the main culprit and implemented a fix in #6285 - it would be great if any of you are able to test against that PR using a copy of your production data.

**Comment by Faber73** [comment]
Tested right now. Working great. No freeze anymore ;-)

Thank you !

**Comment by kevinansfield** [comment]
@Faber73 would you mind detailing the process you've used to test that PR branch and exactly what issue you are seeing and which interactions cause it whilst you test?

I'm currently testing against a blog with 273 posts and 49 tags and have been unable to reproduce the freezing behaviour with the mentioned fix in place but it's possible I'm still not testing against enough data or we're looking at different issues.

**Comment by Faber73** [comment]
I've add your modification manually and lunch the grunt after it, restart cache services (I used nginx with varnish), close browser, open back, clean all data, open only the ghost admin interface, going on "Content" try to do a search, working fine. Try again with another search and working great (before start to freeze from the second search). Change page, going on General, come back to Content click on search bar, all frozen for few minutes, afetr it I'm able again to do a search.

**Comment by kevinansfield** [comment]
Which grunt task are you running? From the description of the problem you are seeing it sounds as though the change isn't being picked up.

**Comment by Faber73** [comment]
I working on my ghost code sometimes, I use it in development enviroment. 

`
grunt --development
Running "shell:ember:dev" (shell) task
DEPRECATION: Node v0.10.41 is no longer supported by Ember CLI. Please update to a more recent version of Node
undefined
version: 1.13.13
BuildingBuilding.Building..Building...BuildingBuilt project successfully. Stored in "dist/".

Done, without errors.
`

**Comment by kevinansfield** [comment]
To run Ghost in development the command is `grunt dev` which will build and launch the server in development mode. The `--development` flag will be ignored as it's not tied to anything, instead the `default` grunt task will be run which just builds the development JS files.

It sounds as though you may be building the dev files but using the production files when going through nginx. How are you booting the ghost instance that nginx talks to?

**Comment by Faber73** [comment]
Oh mhhh maybe you right. I start ghost with a init.d script and I see now that have a "production" enviroment set into it.

Let me to set it right and test again.

**Comment by Faber73** [comment]
Yeah ! My fault. Working great, sorry

**Comment by kevinansfield** [comment]
No problem, glad the fix is working for you now :smile:

**Comment by brightbits** [comment]
This did not fix my issue unfortunately. Even without touching the search box, I can cause it to freeze, by just playing around, no specific action I can see that is starting it. Jumping around articles in the editor is doing it too.

**Comment by ErisDS** [comment]
@brightbits could you use something like [licecap](http://www.cockos.com/licecap/) to make a quick screencast showing what you're seeing? Sounds like it may be a second, separate issue and any help you can provide in tracking it down would be awesome :+1:

**Comment by kevinansfield** [comment]
I've found a reproducible case when you have a lot of posts loaded in the infinite scroll list. With ~270 posts loaded, navigating between posts in the content list causes a noticeable freeze - I'm looking into what's causing that.

If the content list has a lot of loaded articles going back to the content screen from another screen also causes a momentary freeze. I think this is a rendering issue, it would be solved by using a better pagination system that only renders part of the list and re-uses dom elements on scroll.

**Comment by brightbits** [comment]
@ErisDS I just spent a while trying to keep causing it some more, click around randomly and stuff.. it does seem to happen either directly after touching auto complete, or at some point after while clicking on other things.. I'm starting to become confident its all related to it.

**Comment by nuclearpengy** [comment]
@kevinansfield that sounds exactly like what was happening to me. I was reviewing some older posts. My workflow was basically, scroll right down to the bottom(oldest) of the list, open post, implement change, save, go back to content screen, scroll down to second oldest post and repeat the cycle.
