### ISSUE TITLE
Images with "//"-URLs don't show in the editor

### ISSUE THREAD

**Issue by uppfinnarn** [TryGhost/Ghost#6277]
For example, the following two show up properly:

```
![](http://i.imgur.com/U0Lv7dJ.jpg)
![](https://i.imgur.com/U0Lv7dJ.jpg)
```

This does not:

```
![](//i.imgur.com/U0Lv7dJ.jpg)
```

It works fine on the actual page, just not in the editor; it shows the default placeholder, likely due to not recognizing it as a valid URL.

**Comment by ErisDS** [comment]
Hi @uppfinnarn, this is a known issue. Closing in favour of #5625.
