### ISSUE TITLE
Installing ghost locally. Node version Error.

### ISSUE THREAD

**Issue by anderskitson** [TryGhost/Ghost#6279]
I am using nvm for my node version manager, I read here http://support.ghost.org/supported-node-versions/ that the 0.10.40 is the reccomended version. Installed that and set it nvm to that version `nvm install 0.10.40` & `nvm use 0.10.40` 

I cloned the git repository and grunt cli installs fine `npm install -g grunt-cli`
When I try to install ghost with `npm install`
<code>

Anderss-MacBook-Pro-2:ghost anderskitson$ npm install

ghost@0.7.4 preinstall /Users/anderskitson/sites/ghost
npm install semver && node -e "require('./core/server/utils/startup-check.js').nodeVersion()"

semver@5.0.3 node_modules/semver
npm WARN deprecated lodash@0.9.2: lodash@<2.0.0 is no longer maintained. Upgrade to lodash@^3.0.0
npm WARN deprecated lodash@1.0.2: lodash@<2.0.0 is no longer maintained. Upgrade to lodash@^3.0.0
npm WARN engine escodegen@1.7.1: wanted: {"node":">=0.12.0"} (current: {"node":"0.10.40","npm":"1.4.28"})

typechecker@2.0.8 preinstall /Users/anderskitson/sites/ghost/node_modules/grunt-docker/node_modules/docker/node_modules/watchr/node_modules/bal-util/node_modules/typechecker
node ./cyclic.js

utf-8-validate@1.2.1 install /Users/anderskitson/sites/ghost/node_modules/testem/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/utf-8-validate
node-gyp rebuild

CXX(target) Release/obj.target/validation/src/validation.o
SOLINK_MODULE(target) Release/validation.node
SOLINK_MODULE(target) Release/validation.node: Finished

utf-8-validate@1.2.1 install /Users/anderskitson/sites/ghost/node_modules/testem/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/node_modules/utf-8-validate
node-gyp rebuild

CXX(target) Release/obj.target/validation/src/validation.o
SOLINK_MODULE(target) Release/validation.node
SOLINK_MODULE(target) Release/validation.node: Finished

bufferutil@1.2.1 install /Users/anderskitson/sites/ghost/node_modules/testem/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/node_modules/bufferutil
node-gyp rebuild

CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
SOLINK_MODULE(target) Release/bufferutil.node
SOLINK_MODULE(target) Release/bufferutil.node: Finished

bufferutil@1.2.1 install /Users/anderskitson/sites/ghost/node_modules/testem/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/bufferutil
node-gyp rebuild

CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
SOLINK_MODULE(target) Release/bufferutil.node
SOLINK_MODULE(target) Release/bufferutil.node: Finished

sqlite3@3.1.1 install /Users/anderskitson/sites/ghost/node_modules/sqlite3
node-pre-gyp install --fallback-to-build

[sqlite3] Success: "/Users/anderskitson/sites/ghost/node_modules/sqlite3/lib/binding/node-v11-darwin-x64/node_sqlite3.node" is installed via remote
npm ERR! Error: ENOENT, open '/Users/anderskitson/sites/ghost/node_modules/fs-extra/package.json'
npm ERR! If you need help, you may report this entire log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Darwin 15.0.0
npm ERR! command "/Users/anderskitson/.nvm/v0.10.40/bin/node" "/Users/anderskitson/.nvm/v0.10.40/bin/npm" "install"
npm ERR! cwd /Users/anderskitson/sites/ghost
npm ERR! node -v v0.10.40
npm ERR! npm -v 1.4.28
npm ERR! path /Users/anderskitson/sites/ghost/node_modules/fs-extra/package.json
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! not ok code 0

</code>

**Comment by ErisDS** [comment]
Hi @anderskitson, sorry to hear you're having trouble. As mentioned in the readme & contrib guide, if you have questions about Ghost or need help, please head on over to slack - https://ghost.org/slack/ - and post in the #help channel. There you can get help & support from the Ghost community, which we're not able to do here in the GitHub bug tracker.

**Comment by pedro380085** [comment]
This is a really bad idea after all, a lot of knowledge gets lost in Slack.

**Comment by anderskitson** [comment]
@pedro380085 @ErisDS I agree this is a bad Idea. I feel stack-overflow or Github issues is way easier to maintain, no one even acknowledged my issue on slack. I just ended up downloading the ghost zip directly from the site https://ghost.org/download/ instead of cloning the Github repository and it is working locally now.

**Comment by pedro380085** [comment]
My solution was to use `npm install --production`, I missed the options at first.

**Comment by anderskitson** [comment]
@pedro380085 Yes i think that is the correct solution, I didn't realize I was supposed to install production and then run in development mode my by just running `npm start` after.
