### ISSUE TITLE
ERROR: Cannot find module '.../node_modules/sqlite3/lib/binding/node-v14-linux-x64/node_sqlite3.node'

### ISSUE THREAD

**Issue by JohnChance** [TryGhost/Ghost#6280]
When I restarted my VPS and tried to start Ghost with 'npm start --production', I got this error. I tried remove node_modules and reinstall them, but didn't fix it. I can only find node-v11-linux-x64 but not node-v14-linux-x64. 

Any suggestion?

**Comment by ErisDS** [comment]
Hi @JohnChance, sorry to hear you're having trouble. As mentioned in the readme & contrib guide, if you have questions about Ghost or need help, please head on over to slack - https://ghost.org/slack/ - and post in the #help channel. There you can get help & support from the Ghost community, which we're not able to do here in the GitHub bug tracker.
