### ISSUE TITLE
[Suggest] Admin - Filter Content Section Pages/Posts

### ISSUE THREAD

**Issue by Faber73** [TryGhost/Ghost#6284]
In Admin Section, separate posts from pages. When your blog coming to be big, not simple to find old static pages for upgrade.

**Comment by ErisDS** [comment]
Hi @Faber73, to request a feature for Ghost you can add your idea (or vote on a similar one like [this one](http://ideas.ghost.org/forums/285309-wishlist/suggestions/7205951-static-pages-get-mixed-into-blog-posts-in-admin-me)) over on our [wishlist](http://ideas.ghost.org). We use this list to help determine what goes into the roadmap and how to prioritise features. There is also already a 'filter menu' item on the [roadmap](https://trello.com/b/EceUgtCL/ghost-roadmap).

You can also access the wishlist any time from inside the Ghost admin: ![](http://puu.sh/jXKwm.png)

**Comment by Faber73** [comment]
I don't have this menu in my ghost !

Interesting place this whishlist :+1:
