### ISSUE TITLE
Tag & Author RSS feeds still available in private mode

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#6290]
When a blog is in private mode, all of the RSS feeds should be disabled. 

At present, the main `/rss/` route is disabled, and is correctly showing a 404. 
However the tag and author RSS feeds are both still working. 

E.g. if you have a tag 'getting-started' and navigate to `/tag/getting-started/rss/` this is expected to 404 but is currently displaying the RSS feed.

**Comment by halfdan** [comment]
Dibbedidibs

**Comment by ErisDS** [comment]
Assigned but fair warning - I want this in the next release ;)

**Comment by halfdan** [comment]
@ErisDS You'll have a PR tomorrow :)

**Comment by novaugust** [comment]
@halfdan I want this *yesterday* :straight_ruler:

**Comment by halfdan** [comment]
@novaugust This isn't Star Trek. OTOH if I get up early enough I might be able to submit it early in the morning which will be yesterday for you. I win.

**Comment by halfdan** [comment]
@ErisDS Well, this turns out to be much more fun than I thought. In addition to author / tag rss feed still being available, current implementation prevents viewing any post that starts with rss or sitemap (which are protected keywords - but `/sitemap-xml-is-great` is not).

**Comment by ErisDS** [comment]
Nice find :cookie: :)
