### ISSUE TITLE
Tag sitemap.xml doesn't include images

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#6292]
I think this is actually a throwback to the fact that the sitemap was added before tags had the ability to have images added to them. 

They now do (and have done for some time) so the sitemap code needs updating to include the image for tags. 

I think there is also an opportunity here to simplify the `createUrlNodeFromDatum` method which exists in the base generator plus the post, page and user generator. As they all have images now, I think there is some small amount of duplicated code that can be moved back to the base generator.

**Comment by ErisDS** [comment]
cc @jgable this might be an excellent opportunity to get your name back on the contrib list if you fancy it :wink:

**Comment by jgable** [comment]
I am amazed how much of my code you guys still tolerate in the code base. I
should make it a new year's resolution to start committing again. Actually,
I should sit down and ask myself why I stopped, but that's another story
entirely.

I'd actually love to take this small thing on if nobody else snatches it up.

**Comment by ErisDS** [comment]
> I am amazed how much of my code you guys still tolerate in the code base.

Oh we could _tolerate_ a lot, lot more :wink: :grin: :doughnut:
