### ISSUE TITLE
Unable to reorder new menus

### ISSUE THREAD

**Issue by vegasbrianc** [TryGhost/Ghost#6303]
## Issue Summary
After a new menu is created under the navigation screen, users are unable to reorder this new menu above menus that already exist.

## Steps to reproduce
1. Create 3 menus and save your changes
2. Create 1 additional menu
3. Try to move this menu above the initial 3 menus

## Expected result
A user should be able to reorder new or existing menus into any order

## Technical Details
Ghost version 0.7.4
Self hosted
Chrome Browser Version 47.0.2526.106 (64-bit)

**Comment by halfdan** [comment]
Hi @vegasbrianc,
thanks for your report! Unfortunately this is a duplicate of #6281 and ##6267. This is fixed on current master and will be in the next released (currently scheduled for next week).

**Comment by vegasbrianc** [comment]
Doh. i thought I searched through everything but I guess not well enough. Thanks for the clarification.
