### ISSUE TITLE
Get ghost_head and ghost_foot to ignore / remove handlebars comments

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#6308]
I've noticed a bunch of times that people copy snippets which include handlebars comments into the `ghost_foot` and `ghost_head` blocks in code injection.

The code injection blocks are currently treated as HTML, and simply included inline.

We could add some magic to strip out / ignore handlebars comments quite easily

Alternatively we could treat ghost_head and ghost_foot as templates and attempt to compile them as handlebars. Not sure what the pros/cons could be here (what do we do with errors?) but it may be worth exploring.

**Comment by halfdan** [comment]
So apart from rooting for my PR, here's my reasoning for voting to remove those comments:

- Code Injection is in the user domain while handlebars is mainly used by the theme dev.
- Code Injection was introduced to avoid requiring the average user to have to manually edit (and understand) theme files
- Advanced logic like conditionally change what is in the head (e.g. based on the availability of a `post` object) seems to be the responsibility of a theme 

Obviously that's not a full discussion and I'm interested in hearing other opinions.

**Comment by ErisDS** [comment]
I have reconsidered this and I think it might be a bad idea / preoptimisation. Going to close and will reopen if we get lots of complaints or requests about this not working from users.
