### ISSUE TITLE
Can't log in to fresh instance

### ISSUE THREAD

**Issue by mariusz** [TryGhost/Ghost#6311]
After installing Ghost on a brand new Debian server (through Nginx proxy, as a service running as `ghost`), I'm getting following when trying to log in:

    [Error] Failed to load resource: the server responded with a status of 401 (Unauthorized) (token, line 0) http://[my blog]/ghost/api/v0.1/authentication/token

Any ideas how to fix it? I'm guessing something doesn't get passed through Nginx but searching through existing issues didn't bring any decent solutions yet.

**Comment by jtwebman** [comment]
Can you get to it without using Nginx? Also any chance I can see you Nginx config file?

**Comment by ErisDS** [comment]
Hi, @mariusz :)

Our recommended nginx config is here: http://support.ghost.org/basic-nginx-config/. There's not much that can be done to help without seeing a lot of config and as mentioned in the readme & contrib guide, if you have questions about Ghost or need help, we ask that you use slack - https://ghost.org/slack/ - and post in the #help channel. 

I recommend posting your nginx config file and as much output from the server and explanation about the issue you're having as you can there.
