### ISSUE TITLE
Ember not recognized, and "JavaScript files have not been built."

### ISSUE THREAD

**Issue by cdvillard** [TryGhost/Ghost#6313]
I'll preface this with the fact that I'm new to Node and npm, and this is the most I've delved into using these tools. That said, I'm using Node 4.2.4 and I've followed the steps in Getting Started, but with no success in starting Ghost. Whether I run 'grunt init', 'grunt prod', 'grunt dev', or use the '--force' option with any of them, I'm always returned this specific error at this specific step:

```
Running "shell:ember:prod" (shell) task
'C:\Users\cdvillard\Projects\sandbox-2\ghost\core\client\node_modules\.bin\ember' is not recognized as an internal or external command,
operable program or batch file.
Warning: Command failed: C:\WINDOWS\system32\cmd.exe /s /c "C:\Users\cdvillard\Projects\sandbox-2\ghost\core\client\node_modules\.bin\ember build --environment=production --silent"
'C:\Users\cdvillard\Projects\sandbox-2\ghost\core\client\node_modules\.bin\ember' is not recognized as an internal or external command,
operable program or batch file.
```

I bring this here as I'm not sure if this is an issue with ghost, npm, ember, grunt, or otherwise. I have the full output of these commands here: https://gist.github.com/cdvillard/e961767bb74de49fbc9d. Any thoughts?

**Comment by ErisDS** [comment]
Hi @cdvillard, I'm pretty sure I've seen you on slack already, which is the place to get help & support with your env :+1:  I saw you posted about having install trouble, so I recommend posting the full steps & output from your install process in a gist there, as it's likely the install failed and is why ember isn't installed properly for you.
