### ISSUE TITLE
'Are you sure you want to leave this page' message appearing unneccessarily

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#6315]
There is an easy to reproduce case in which the 'Are you sure you want to leave this page?' message which indicates you have unsaved changes is appearing and should not be.

### Steps to Reproduce

1. Go to the Ghost admin
2. Hit 'New Post'
3. Do nothing, except open the post settings menu
4. Hit 'Content'
5. Get the message

No typing has occurred and no settings have been manually changed, so as far as the user is concerned there should be nothing to change at this point.

Note, the following steps do not reproduce the message:

1. Go to the Ghost admin
2. Hit 'New Post'
3. Do nothing, don't even open post settings menu
4. Hit 'Content'

### Technical details: 

* Ghost Version: master

**Comment by kevinansfield** [comment]
Interesting. To extend on the reproduction steps a little, the first time you go through the above steps you won't see the modal but on subsequent tries you will see it.
