### ISSUE TITLE
Minor usability improvements for editor screen

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#6318]
At the bottom of the editor screen in the Ghost admin panel, there are 2 sections with the titles `Markdown` and `Preview`:

![](http://puu.sh/mrPde.png)

These are effectively the names of the sections above - the left pane is where you type markdown, and the right pane is a preview of how the markdown will look.

Recently, we carried out some user testing and found new users clicked on those titles expecting something to happen. Also, the markdown icon doesn't make much sense if you don't know what it is, and the current sharable preview link is hidden in the PSM.

So, as a short term improvement, the following two changes would be great:

#### 1. Make the 'Markdown' text open the markdown help modal, exactly the same as the markdown icon:

![markdown modal](http://puu.sh/mrPrz.png)

#### 2. Make the 'Preview' text open the sharable preview in a new window, exactly the same as the preview link inside the post settings menu:

![preview link](http://puu.sh/mrVm7.png)

**Comment by kevinansfield** [comment]
One thing to be aware of here is that at mobile screen sizes that text is clickable and used to toggle screens so we may want to look at adding a different way to provide the help/open preview links in that situation:

![screen shot 2016-01-11 at 17 53 15](https://cloud.githubusercontent.com/assets/415/12241628/3646a50c-b88c-11e5-89ed-268330c5806c.png)
![screen shot 2016-01-11 at 17 54 03](https://cloud.githubusercontent.com/assets/415/12241668/5c941bb8-b88c-11e5-88b8-02bdb3bf9c8f.png)

**Comment by ErisDS** [comment]
I think in mobile view they should stay the same as they are now, and only have these actions if we're in full view? 

Makes it much trickier to do though I guess?

**Comment by kevinansfield** [comment]
> Makes it much trickier to do though I guess?

No, that should be pretty simple, the desktop and mobile elements are both separate in the HTML so behaviour can be attached to each individually. :+1: for keeping the mobile view as-is for now then.

**Comment by JohnONolan** [comment]
yup they should be the same - on mobile those labels trigger tab changes, can't add a second action to them or it'll break everything:tm:

**Comment by ErisDS** [comment]
:+1:
