### ISSUE TITLE
Add number of views per post

### ISSUE THREAD

**Issue by claudiutraistaru** [TryGhost/Ghost#6323]
This requires a new views(or any other name) field in database and the action to update views every time a single post page is rendered (I managed to add the view in database and on post creation as 0, but I cannot find how to update number of views when the post page is rendered). 
This is useful to create a "Most popular posts" top which is a must for a blogging and publishing platform.

Thank you.

**Comment by kashev** [comment]
https://github.com/TryGhost/Ghost/blob/master/CONTRIBUTING.md

**Comment by ErisDS** [comment]
Hi @claudiutraistaru,

To request a feature for Ghost you can add your idea (or vote on a similar one [like this](http://ideas.ghost.org/forums/285309-wishlist/suggestions/7181786-post-analytics)) over on our [wishlist](http://ideas.ghost.org). We use this list to help determine what goes into the roadmap and how to prioritise features. You can also access the wishlist any time from inside the Ghost admin:
![](http://puu.sh/jXKwm.png)

Counting posts on render wouldn't be a good solution, as any cached page wouldn't be counted.
