### ISSUE TITLE
Multiple ghost instances interfere with each other's authentication (v0.7.4)

### ISSUE THREAD

**Issue by JuanCaicedo** [TryGhost/Ghost#6326]
My company runs two separate instances of ghost, served under the same domain by nginx. After upgrading to v0.7.4 from v0.6, we noticed a strange behavior where if you open both blogs, each in a separate tab but in the same browser, it's impossible to log in to both. You stay logged in for a second, but then get immediately logged out. 

After taking a look, we were able to find that ghost remembers authentication by adding an entry into local storage. In v0.6, the key of this entry includes the url ghost is served at, for example:

Url of instance | Local storage key
-------------------|--------------------------
www.spanishdict.com/blog | ghost-blog
www.spanishdict.com/blog/traductor | ghost-blog-traductor

However, in v0.7, this key becomes just `ghost`. The effect is that if both blogs are open at once, they override each other's auth entry, having the effect of always giving that entry the default value `{"authenticated":{}}`.

If it's helpful in figuring out how to fix/recreate this, I can provide access to our test environment with v0.7.4 deployed.

Thanks for maintaining this project!

cc/ @carsonbanov @sandinmyjoints

**Comment by halfdan** [comment]
Hola Juan,
thanks for the detailed bug report. I'll take a look at fixing this.

**Comment by JuanCaicedo** [comment]
Awesome, gracias @halfdan!

**Comment by halfdan** [comment]
This is a regression, introduced in https://github.com/TryGhost/Ghost/commit/87e54c0d54696af6361b8704de1049298f2ff935#diff-647be943e1d5223ba4d913e869b2ef12L14
