### ISSUE TITLE
Revisit post-i18n preinstall script

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#6332]
Following on from #6070 and the [discussion here](https://github.com/TryGhost/Ghost/pull/6070#issuecomment-170977126) we need to consider whether it's the correct approach to have so many dependencies installed via the preinstall script.

The existing preinstall script has already lead to some interesting install issues, and I'd like to make installing Ghost easier rather than trickier :)

Additionally, as these errors are output to the console, not in the UI, I think it's safe to leave them untranslated. In future we can ensure that the error codes and error messages lead to translated docs and troubleshooting guides.

**Comment by halfdan** [comment]
After looking into this I agree that, if the goal is to reduce the number of initial dependencies, i18n in the startup check is a no go. The i18n module depends on `lodash` (in multiple lines), `chalk` (one call) and completely on `intl` and `intl-messageformat`. While chalk can potentially be removed we're still left with the other three dependencies. I'm going to create a PR that reverts the i18n changes to the startup check and the preinstall hook (and remove the strings with it).

**Comment by halfdan** [comment]
I also agree with the point @kevinkucharczyk has raised in the discussion - debugging translated errors from the command line will become difficult - especially once we support some less often encountered languages. Here I definitely see the need to have clear error codes that can be looked up in the docs.
