### ISSUE TITLE
Different result of npm start --production & service ghost restart

### ISSUE THREAD

**Issue by jerryling315** [TryGhost/Ghost#6338]
Wired enough, my blog runs well when starting with `npm start --production` but yielding `502 Bad Gateway` when starting with `service ghost restart`.

What do these two commands do differently?

**Comment by jerryling315** [comment]
What do I need to paste here in order to make the issue solvable?

**Comment by halfdan** [comment]
Hi @jerryling315, 
this sounds like an environment issue and not a bug within Ghost. We use Github for tracking bugs and for development. Please join our [Slack community](http://ghost.org/slack) where we are happy to provide help.

As for formatting an issue, we have a bug template at: https://github.com/TryGhost/Ghost/blob/master/CONTRIBUTING.md#reporting-an-issue

**Comment by jerryling315** [comment]
@halfdan Thank you!

**Comment by jerryling315** [comment]
The trick is that, I upgraded node to a newer version with `n` which changed location of node (can check by `which node`) to `/usr/local/bin/node` instead of what's for DAEMON: in `/etc/init.d/ghost`
