### ISSUE TITLE
Pasting comma-separated list of tags into web UI is very slow

### ISSUE THREAD

**Issue by Tyriar** [TryGhost/Ghost#6342]
Pasting a comma separated list, for example `"a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p"` is slow (5+ seconds) and does not scale. My guess as to why is that there is no bulk entry code that splits and adds the tags and instead for each bookmark entry (or character?) the dropdown is created, displayed and then destroyed.

I would expect pasting into the tag textbox to do something like this:
1. Diff text with previous text (in order to get pasted text)
2. If there are commas in the pasted text, split it and add all split entries as new tags

This should be near instant barring async calls to add them to the DB which don't need to be observed by the user.

Ghost v0.7.5

**Comment by kevinansfield** [comment]
Thanks for the report. Which browser/operating system are you using?

Attached is a screen cap of pasting the full alphabet repeated twice on OS X/Safari (apologies for the watermark, I had to grab an app quickly to show when the keys were pressed). As you can see there is very little delay on that configuration.

There is an amount of processing that is needed for each tag that is added - checking against existing tags, creating new tag objects, attaching to the post object, etc. The dropdown component itself does not create/display/destroy at all when pasting so it is likely that it's the tag checking/creation process that is causing the slowdown, something that may be more apparent on sites that already have a lot of tags created. That's not to say that there are no performance gains to be made but pasting long lists of tags is an edge case.

`a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z`

![tags-paste](https://cloud.githubusercontent.com/assets/415/12351169/8b482ad2-bb73-11e5-8a04-962e26245ada.gif)

**Comment by Tyriar** [comment]
Chrome v46 on Debian 8 on a ~6 year old laptop. It also happens on my desktop at home which is a lot faster running Ubuntu 15.04 and chrome v46. One my desktop I did not test it using single letter tags, so maybe the issue only shows for single letter tags on slow computers?

**Comment by ErisDS** [comment]
As this wasn't reproducible and only has one report, I'm going to close it as a won't fix. If we get more reports we can reopen :)
