### ISSUE TITLE
Markdown editor select line above on wrapped lines doesn't work

### ISSUE THREAD

**Issue by Tyriar** [TryGhost/Ghost#6343]
Not sure if it's the hyphen character or something else that's causing this issue. (Ghost v0.7.5, Chrome v46)

**Steps to reproduce**

1. Open a new post and paste something like this:

    ```
    ![](http://somebig.url.com/aaaaaaaaaaaaa-bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb-ccccccccccccccccccccccc-dddddddddddddddddddd)
    ```

2. Ensure that the line is wrapped such that the last line is longer than the line before the the line before ends with `-`. For example:

    ```
    ![](http://somebig.url.com/aaaaaaaaaaaaa-
    bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb-
    ccccccccccccccccccccccc-dddddddddddddddddddd)
    ```

3. Place the cursor after the `)`
4. Hold shift and press up to select from the `-` after the b's to after the `)`
5. Hold shift and press up

**Expected**

The line containing the b's is highlighted

**Actual**

Nothing. Holding shift and pressing left to select the hyphen before doing a shift+up will work as expected.

**Comment by kevinansfield** [comment]
@Tyriar the markdown editing area is a normal textarea and so any text selection abilities are provided by the browser/operating system, ie. not something that we want to mess with as it will break user expectations and be impossible to produce a consistent experience across all possible platforms.

On OSX/Safari you'll see the same behaviour here in the github message textarea.

**Comment by Tyriar** [comment]
Maybe it's a webkit and blink bug then, will investigate and report if so. Thanks.

**Comment by kevinansfield** [comment]
Sorry if I wasn't clear, it's not a browser issue but an OS-level aspect of text selection. Here's an example of the behaviour inside Apple Mail:
![text selection bug example](https://cloud.githubusercontent.com/assets/415/12364946/96079aec-bbc9-11e5-8951-879f698609c6.gif)
