### ISSUE TITLE
`/page/1` made available when `home.hbs` is presented?

### ISSUE THREAD

**Issue by zachguo** [TryGhost/Ghost#6344]
Current documentation said `home is a special context which is only set on the home page`. But, what's the difference between `home` and `index`? It seems right now (v.0.7.5) that `home` behaves exactly the same as `index`, only a naming difference. 

I think `/page/1` should be, instead of a redirection to `/`, made accessible(and rendered by `index.hbs`) when `home.hbs` is presented, so that the existence of `home.hbs` makes more sense. See related use cases [here](http://stackoverflow.com/questions/34801107/how-can-i-get-access-to-index-hbs-if-i-had-home-hbs-set-up) and [here](http://mordaszewski.com/ghost-add-home-page-hack/).

Your thoughts?

**Comment by halfdan** [comment]
Hi @zachguo, as explained by @dbalders at http://stackoverflow.com/questions/34801107/how-can-i-get-access-to-index-hbs-if-i-had-home-hbs-set-up - `home` is only used on `/` while `index` is used on `/` (if `home.hbs` doesn't exist`) and on all subsequent pages. `/page/1`. Ghost deliberately does not support a static home page.

**Comment by zachguo** [comment]
@halfdan Thx for reply. After digging into source codes, I think I'd better serve ghost in a subdirectory. However, the docs & existence of `home.hbs` confused me and made me think that `home.hbs` can be used for a static homepage..

**Comment by halfdan** [comment]
I think that's the best course of action: Serve ghost in a subdirectory - this way you can use `/` for serving a static homepage that links to your blog.
