### ISSUE TITLE
Add possibility of template configuration

### ISSUE THREAD

**Issue by aholbreich** [TryGhost/Ghost#6346]
Say i would like to build a tamplate that can accept some parameters
-  E.g General parameters for the whole blog 
like "google analytics id" or DISQUS id.

-  Additionally per post parameters that template could react to. 
   e.g switch color or with.

I there any workaround for this now?

**Comment by ErisDS** [comment]
Hi @aholbriech, 

To request a feature for Ghost you can add your idea (or vote on a similar one) over on our [wishlist](http://ideas.ghost.org). We use this list to help determine what goes into the roadmap and how to prioritise features. You can also access the wishlist any time from inside the Ghost admin:
![](http://puu.sh/jXKwm.png)

The normal way to offer this sort of configuration in a theme is either with a single file like config.js or with a variable that can be customised via code injection.

**Comment by aholbreich** [comment]
Thank you didn't know. But is there any workaround for this now?

**Comment by halfdan** [comment]
@aholbreich Those two exact use cases are covered by code injection as @ErisDS mentioned

**Comment by aholbreich** [comment]
@halfdan @ErisDS Oh sorry overlloked last part.

> The normal way to offer this sort of configuration in a theme is either with a single file like config.js or with a variable that can be customised via code injection.

1)Does it mean i can somehow read variables of config.js? How?

2) How to wire code injectiron to varible? How to access it in the template?

**Comment by ErisDS** [comment]
Both of these mechanisms use standard JavaScript - you can include your own js configuration file, and script blocks from code injection into your theme. Either or both can provide global variables which can then be accessed in your themes. 

If you're looking for step-by-step help please checkout the #help & #themes channels on our [slack](https://ghost.org/slack) team.

**Comment by aholbreich** [comment]
@ErisDS Thank you very much

**Comment by donmccurdy** [comment]
For anyone looking for this feature, I recommend upvoting [Theme settings](http://ideas.ghost.org/forums/285309-wishlist/suggestions/7503136-theme-settings-json-file-like-shopify-s-settings) in the Ghost Wishlist.
