### ISSUE TITLE
Changes to feature flags are never reflected across concurrent sessions

### ISSUE THREAD

**Issue by kevinansfield** [TryGhost/Ghost#6359]
### Issue Summary

If User A and User B are using the admin area simultaneously and User A changes a feature flag, that change is never reflected in User B's admin area unless they manually refresh/reload the admin page. This is also true if single user has multiple tabs open.
### Steps to Reproduce
1. Log in to the admin as usual
2. Open an incognito/private browser window and log in again, keeping both windows open
3. On the standard window, visit the Labs section and then go back to the content screen
4. On the incognito window, visit the Labs section and change the Public API setting
5. On the standard window, visit the Labs section and note that the change is _not_ shown, you can continue using the admin area on this window and the change will never be reflected

Right now we only have the Public API labs flag so this isn't too much of an issue but as the use of feature flags increases it may become more troublesome as the settings will be loaded earlier in the session and have effects that entail deeper UI/functionality changes. For example with the New Editor flag, a user may enable it in one tab but and then wonder why they never get the new editor in another tab they have open.

The lack of realtime push of changes in other areas of the app is mitigated by reloading the relevant data whenever we change screen. With labs settings this is more difficult because the state is loaded once and held in a singleton (currently a controller, soon to be a service) for the duration of the session. The Labs screen itself is easy to fix by reloading the settings any time that screen is accessed but labs settings are different to content-based screens in that a feature flag can have app-wide effects, simply updating feature flags when loading the labs screen doesn't fix the bigger issue.

Without some other means of pushing feature flag changes from the server to the client we're left with either:

a. Requesting the latest settings on every major screen change
b. Requesting the latest settings each time we check a feature flag

Unfortunately both options have performance issues as they introduce additional network requests, option B especially.
### Technical details
- Ghost Version: master

**Comment by halfdan** [comment]
May I suggest something like https://medium.com/all-about-feathersjs/using-feathersjs-as-an-open-source-alternative-to-firebase-b5d93c200cee#.aoxad8pgj

**Comment by ErisDS** [comment]
@halfdan Can you provide some context with that link? How do you think it will help?

**Comment by halfdan** [comment]
Apologies - I should've elaborated on that link. Firebase/Featherjs provides a real-time websocket based updating mechanism. Updates pushed to a resource - like `/features` would be automatically pushed to all other clients. 

I've been working with Firebase and it's ember addon emberfire the past year at $dayJob. Emberfire provides an ember data adapter that allows you to interact with models (whatever they may be - in this case e.g. features) and syncs changes to its backend (Firebase is also a data store) and all connected clients. I realise this is probably more than this issue is asking for in terms of realtime syncing ability but it would provide a nice setting stone for more advanced features like collaborative editing.

I'm not sure if that would be scalable on Ghost(Pro) though.

**Comment by kevinansfield** [comment]
I've had a very quick look, feathers.js seems like more of framework to use in place of roll-your-own express that makes it easier to build REST APIs as well as having a sockets layer rather than just offering a sockets and messaging service to hook into.

In my opinion the holy grail would be a node.js version of phoenix's channels but I haven't seen anything in my casual searches so far. It seems like https://github.com/primus/primus is a good building block.

In any case, this issue may be better suited to a simpler solution until we're ready to implement a full sockets/push system.

**Comment by kevinansfield** [comment]
I'm going to close this and mark as `later`. It's an edge case that no-one has complained about and will be be solvable once we have a general web-sockets implementation that's likely to be introduced for higher-priority features.
