### ISSUE TITLE
Ghost {{@blog.url}} appends :2368

### ISSUE THREAD

**Issue by xetryj** [TryGhost/Ghost#6369]
Hello, I have set up a Ghost blog on nginx, which runs three more sites (on Digitalocean). Everything works fine, except the link to {{@blog.url}}.
It replaces from evgn.co to evgn.co:2368 and leads to error.
I just don't know where to watch a problem.

Maybe you have had such experience?

http://evgn.co

Just clic on logo in left top corner.

/etc/nginx/sites-available configured, as:

server {
listen 0.0.0.0:80;
server_name evgn.co;
access_log /var/log/nginx/evgn.co.log;
location / {
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header HOST $http_host;
proxy_set_header X-NginX-Proxy true;
proxy_pass http://127.0.0.1:2368;
proxy_redirect off;
}
}

Production environment in config.js set up:

production: {
url: 'http://evgn.co',
mail: {
transport: 'SMTP',
options: {
service: 'Gmail',
auth: {
user: 'xxx@yyy',
pass: 'zzz'
}
}
},
database: {
client: 'sqlite3',
connection: {
filename: path.join(__dirname, '/content/data/ghost.db')
},
debug: false
},

server: {
host: '127.0.0.1',
port: '2368'
}
},

I have even more to say, that it don't depends from theme, the stock Casper shows the same.
I tried to power off, then power on my droplet. Restarted ghost and nginx, but nothing helps.

**Comment by ErisDS** [comment]
Hi @xetryj, sorry to hear you're having trouble. As mentioned in the readme & contrib guide, if you have questions about Ghost or need help, please head on over to slack - https://ghost.org/slack/ - and post in the #help channel. There you can get help & support from the Ghost community, which we're not able to do here in the GitHub bug tracker.
