### ISSUE TITLE
node_modules + core/client/node_modules are enormous

### ISSUE THREAD

**Issue by uppfinnarn** [TryGhost/Ghost#6371]
On my machine, `node_modules` is 309MB and `core/client/node_modules` is 331MB. This seems… rather excessive?

I'm not sure if this is by design on Node's end, but 700MB of disk space is *a lot*. Especially since we're running two Ghost blogs on the same machine, that's 1.5GB (of 30GB) right there…

Can anything be done to reduce this?

**Comment by halfdan** [comment]
Hi @uppfinnarn, we use Github for tracking bugs with Ghost. You seem to have questions about Ghosts disk usage - please come and join us in our Slack community over at http://ghost.org/slack where we're happy to discuss this further.

As quick feedback, it seems you are running Ghost in development / off of Github. Running Ghost as an npm module or even from the release zip gives me a node_modules directory with just over 160mb. (core/client isn't part of a released Ghost version).

**Comment by ErisDS** [comment]
If space is your primary concern, the [npm module](https://github.com/TryGhost/Ghost/wiki/Using-Ghost-as-an-NPM-module) is probably the way to go. Down side is you need to write your own start scripts, but 2 small scripts & 2 configs should be able to share the same npm module code.
