### ISSUE TITLE
Words with the letters "fi" appearing as just "i" in a post page.

### ISSUE THREAD

**Issue by zsck** [TryGhost/Ghost#6375]
I noticed this bug while I was reading a blog post written by a friend of mine.  Words that contain the letters "f" and "i" in that order, such as "figure" and "horrific" are appearing without the "f".  That is, "figured" becomes "igured" and "horrific" becomes "horriic". Interestingly (perhaps unsurprisingly), the page actually does *contain* the letter "f", and the browser can find the words when searching the page for the correctly spelled versions.

You can see in this screenshot of my own blog post that the word "horrific" appears as "horriic" but searching the page for "fi" highlights part of the word.

![Ghost blog post in Chrome](https://i.imgur.com/NxDMkXi.png)

For your reference

* My friend's post: http://blog.jrmiller.co/what-ive-been-up-to-lately/
* My own blog post: http://zsck.co/2016/01/01/onward-to-2016/

My friend was able to verify this behavior in Chrome on Debian 8.2 and I was able to observe it in both the latest Chrome and the latest Firefox on the latest version of OS X. 

We've both found that changing the text's `font-family` using the Chrome Developer Tools to something like Ariel results in the letter "f" becoming visible, shown in the image below.

![Letter f is visible when font is Ariel](https://i.imgur.com/xqicIGl.png)

**Comment by rwboyer** [comment]
I've noticed this too. I believe there's something wrong with the Merriweather font. Anyone else out there that can confirm

**Comment by nuclearpengy** [comment]
This was discussed on Slack earlier this evening.

**Comment by nuclearpengy** [comment]
https://ghost.slack.com/archives/atrium/p1453511622000004

**Comment by LukeHostetler** [comment]
My posts are acting in exactly the same manner, using the standard Ghost font.

Strangely enough, my blog tagline doesn't act quite the same. It only eliminates the letter "f" if it starts a word and is immediately followed by "i" or "l".

**Comment by calekennedy** [comment]
https://bug-demonstration.herokuapp.com/final-bug-demonstration/

**Comment by nmhuy** [comment]
Changing the font-family from Merriweather to Open Sans for the body selector in screen.css does not exhibit the problem : 
```
body {
    font-family: "Open Sans", serif;
}
```

**Comment by k-j-kleist** [comment]
Note the recent "improvement" of "Merriweather" mentioned here: https://www.google.com/fonts/specimen/Merriweather

**Comment by Wonderfall** [comment]
I had the same weird problem, thank you all for figuring out what the problem is and where it comes from.
I applied @nmhuy's suggestion.

**Comment by ErisDS** [comment]
This is a bug in the [merriweather font](https://github.com/EbenSorkin/Merriweather/issues/16) itself, which affects the [Casper theme](https://github.com/TryGhost/Casper/issues/235). The Merriweather team released an update to Google Fonts on Friday, which caused this. 

If it is not going to be fixed tomorrow (Monday) we will push out a new release of Casper.

**Comment by rwboyer** [comment]
@ErisDS curious as to the "fix" you propose in Casper to deal with an issue in Merriweather ???

**Comment by halfdan** [comment]
A different font.

**Comment by JohnONolan** [comment]
https://github.com/google/fonts/issues/8 - Google are pushing a fix tomorrow. This is a Casper bug being tracked here: https://github.com/TryGhost/Casper/issues/235

**Comment by davelab6** [comment]
The update to Merriweather was made in advance of the Firefox 44 launch on Tuesday that will mean the old files will just stop working. 

The bug with fi/fl ligatures has a workaround - you can turn ligatures off with CSS to work around this until then:

    -webkit-font-feature-settings: 'liga' 0, 'onum' 1, 'kern' 1;
    -moz-font-feature-settings: 'liga' 0, 'onum' 1, 'kern' 1;
    -o-font-feature-settings: 'liga' 0, 'onum' 1, 'kern' 1;
    font-feature-settings: 'liga' 0, 'onum' 1, 'kern' 1;

**Comment by davelab6** [comment]
The fix is now pushed all the way through the Fonts API
