### ISSUE TITLE
Image upload gives 401 access denied on master branch

### ISSUE THREAD

**Issue by jtwebman** [TryGhost/Ghost#6377]
On the master branch you now get a 401 access denied which posting to the /ghost/api/v0.1/uploads/ endpoint. It is because jQuery-File-Upload is not adding the Authorization header onto the post. My guess is Ember uses a different method to make the requests that adds it but jQuery-File-Upload isn't using the same. I am looking into it now but I have only worked on one other Ember app so I am no expert.

After about an hour of looking at it it looks like we need to store the token someplace so that we can add the header on this request here: https://github.com/TryGhost/Ghost/blob/master/core/client/app/assets/lib/uploader.js#L59

**Comment by shennan** [comment]
Could Ember support for Node versions be anything to do with it? I remember getting an Ember deprecation warning when installing this branch a couple of hours ago.

Looking back, it reads:

```
DEPRECATION: Node v0.10.35 is no longer supported by Ember CLI. Please update to a more recent version of Node
```

The install didn't botch though. But I can confirm I'm getting the same problem hitting that endpoint.

**Comment by kevinansfield** [comment]
This has likely become an issue after the recent switch to ember-ajax from ic-ajax. I'll look into it, should hopefully be a quick fix.

**Comment by ErisDS** [comment]
Is this present in 0.7.5 or just master?

**Comment by kevinansfield** [comment]
Should only be in master. I've not seen any reports of it occurring in 0.7.5 yet.

**Comment by shennan** [comment]
I've only seen this in master. 0.7.5 did not do this for me.
