### ISSUE TITLE
Feature to log out other users.

### ISSUE THREAD

**Issue by loskiq** [TryGhost/Ghost#6383]
There should be a button - Exit on all devices. Otherwise, changing password, other devices are not forwarded to the authorization.

**Comment by ErisDS** [comment]
Hi @loskiq, 

To request a feature for Ghost you can add your idea (or vote on a similar one [like this](http://ideas.ghost.org/forums/285309-wishlist/suggestions/7643373-sign-out-everywhere)) over on our [wishlist](http://ideas.ghost.org). We use this list to help determine what goes into the roadmap and how to prioritise features. You can also access the wishlist any time from inside the Ghost admin:
![](http://puu.sh/jXKwm.png)
