### ISSUE TITLE
Can't update multi-post

### ISSUE THREAD

**Issue by Mediaoueg** [TryGhost/Ghost#6393]
Hi, i'm update to 0.7.5 but now i can't edit two or more post of a blog in same time (one post per windows for example).

**Comment by ErisDS** [comment]
Hi @mediaoueg, sorry to hear you're having trouble. As mentioned in the readme & contrib guide, if you have questions about Ghost or need help, please head on over to slack - https://ghost.org/slack/ - and post in the #help channel. There you can get help & support from the Ghost community, which we're not able to do here in the GitHub bug tracker.
