### ISSUE TITLE
How to get global parameters for number of posts, tags, authors ?

### ISSUE THREAD

**Issue by chasekafei** [TryGhost/Ghost#6394]
It seems theme cannot get how many posts or tags in total I've created ?

I can only get the number of posts when viewing a page with `pagination` by `{{pagination.total}}`. But it's the number of the posts for selected tags or conditions, not a global one. And it cannot be get when no `pagination` on page.

So I have trouble when setting up a statistics page.

BTW: I've post this on the [wishlist](http://ideas.ghost.org/forums/285309-wishlist/suggestions/11568447-global-parameters-for-number-of-posts-tags-autho) .

**Comment by ErisDS** [comment]
Hi @chasekafei, sorry to hear you're having trouble.

Seems like you might need this: http://themes.ghost.org/docs/get. As mentioned in the readme & contrib guide, if you have questions about Ghost or need help, please head on over to slack - https://ghost.org/slack/. There's both a #help and a #themes channel where you can get help & support from the Ghost community, which we're not able to do here in the GitHub bug tracker :octocat:
