### ISSUE TITLE
Incorrect comment suggestion regarding port configuration in config.js

### ISSUE THREAD

**Issue by PMas551** [TryGhost/Ghost#6402]
When deploying Ghost on IIS 7.5 with IISNode, it is recommended in a comment in config.js to set port to 'process.env.PORT'. 

This is misleading and incorrect, it should be set to process.env.PORT (no quotes).

Setting the port to 'process.env.PORT' results in the following error in the browser: ERROR: (Code: EACCES) There was an error starting your server.

**Comment by ErisDS** [comment]
I'm not quite sure what to do with this issue. The symbols you're referring to aren't quotes, they're back ticks - e.g. the markdown for inline code.

The config.example.js has quite a bit of markdown in the comments, as we use this for generating docs but this isn't really used.

So, I can see how this caused confusion, but if the backticks are going to be removed from this place, they should probably be removed in other places as well.

**Comment by novaugust** [comment]
> So, I can see how this caused confusion, but if the backticks are going to be removed from this place, they should probably be removed in other places as well.

I think it's pretty standard developer talk to use backticks to separate out *exactly* which parts of a document can be copy/pasted into code, and that it shouldn't be changed. Expecting some level of knowledge (or else debugging skills) is acceptable for people doing self installs, eh?

**Comment by ErisDS** [comment]
I agree, but am more than willing to be proven wrong. Going to close this for now but if other people run into issues with the back ticks being confusing, let us know and we'll change it.

**Comment by PMas551** [comment]
I didn't even notice they were backticks (I really did think they were quote marks - they do look similar don't they :o)) and I'm not familiar with the use of backticks to demarcate code snippets for pasting in.

I'm from the .Net world and I've never seen backticks used in this manner before. Since the IISNode port suggestion is for .Net people I can possibly see this happening to other people. It was my first Ghost install.

I had a look at the markdown guide and I can see that backticks are listed there for putting code into your ghost blog posts, and I can see from the config.js that the markdown notation has been adopted as the convention for annotating comments in javascript code.

I don't know if using a proprietary notation in javascript comments is best practice?

**Comment by AustinPaquette** [comment]
As per @novaugust 

> I think it's pretty standard developer talk to use backticks to separate out exactly which parts of a document can be copy/pasted into code, and that it shouldn't be changed.

I agree with this. I don't think it's worth changing, it's down to interpretation, I personally wouldn't have included the ticks with a copy-paste solution, I wouldn't mind either way but preference is _with_ back ticks.

**Comment by PMas551** [comment]
@AustinPaquette @novaugust 

Can you point us at any links saying it's best practice to use back ticks? 

I've never seen backticks used in javascript comments anywhere else.

**Comment by AustinPaquette** [comment]
@PMas551 Never suggested it was best practice, just preference.

Enter in yourdomain.com

vs

Enter in `yourdomain.com`

That's just emulated in the comments.

**Comment by PMas551** [comment]
@AustinPaquette Personal preference is moot. Best practices help people who are new to the project get up to speed and installed quickly. I'm in the position of having made a newbie error and I want to help stop other people making similar newbie errors by suggesting adherence to best practice.

**Comment by AustinPaquette** [comment]
@PMas551 if you can guide me towards articles that suggest the alternative is best practice then we can make a discussion out of it, otherwise we're both bickering about preferences which

> is moot.

Newbie errors happen, veterans make them every now and again. I haven't seen _anything_ that suggests lack of quotes is best practice. But I'm all for reading an article that would argue it if you have one on hand.

**Comment by mherzig** [comment]
I've used node on IIS; to me I think the confusion is more likely if you are new to node in general, otherwise most likely you would know what `process.env.PORT` is supposed to mean. But I also see how it can be a bit confusing in the comment. Maybe do something like this:

```
server: {
  // Host to be passed to node's `net.Server#listen()`
  host: '127.0.0.1',
  // Port to be passed to node's `net.Server#listen()`
  port: '2368'
  // ...or for iisnode comment out the line above and use one this instead:
  //port: process.env.PORT
},
```

My instructions could be better, but maybe this is more obvious if you are new to node?
