### ISSUE TITLE
Searching a blog with many posts and tags is painfully slow

### ISSUE THREAD

**Issue by Tyriar** [TryGhost/Ghost#6408]
Chrome locks up when I initiate a search through the admin UI, sometimes for 30+ seconds (the issue is significantly worse on my laptop). The blog has around 130 posts, with each post having up to 20 tags.

Looking at a Chrome timeline of the issue, it seems to be to do with observing an array and performing many dom manipulations. resulting is an awful lot of layout thrashing. I would expect all the work to be done with the DOM nodes being added to a document fragment which is added when it's ready.

Here's a screenshot of the timeline after searching for "l":
![timeline](https://cloud.githubusercontent.com/assets/2193314/12635825/2fd34e16-c53c-11e5-963a-44c476af1217.jpg)

I'm on Ghost 0.7.5.

**Comment by kevinansfield** [comment]
Hey @Tyriar, are you sure you're on 0.7.5? Your timeline looks like it's showing code paths that were removed in that release in order to fix this issue.

To be sure you click visit http://yourblog.com/ghost/about which will list the currently running version.

**Comment by Tyriar** [comment]
@kevinansfield Ah I'm 0.7.3 actually, didn't know about the about page so I looked at DigitalOcean's droplet version which must have been updated shortly after deploying. I'll upgrade, thanks!
