### ISSUE TITLE
Markdown Editor

### ISSUE THREAD

**Issue by ericrange** [TryGhost/Ghost#6410]
Hey today github published a new blog post, presenting a new markdown editor.

wouldnt it be also a nice feature for ghost?

https://github.com/blog/2097-improved-commenting-with-markdown

**Comment by ErisDS** [comment]
Hi @ericrange, I recommend you check out https://github.com/TryGhost/Ghost/pull/6255.

If you just want to chat with us about this sort of thing please join our [slack](https://ghost.org/slack), or you can also suggest features on our [wishlist](http://ideas.ghost.org). GitHub is our issue tracker.
