### ISSUE TITLE
Post Scheduling: Cron Adapter

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#6413]
For a full overview of the spec, please see [Post Scheduling 101](https://github.com/TryGhost/Ghost/wiki/Post-Scheduling-101) and the epic (parent) issue: https://github.com/TryGhost/Ghost/issues/6399.

----

The role of [The Cron](https://github.com/TryGhost/Ghost/wiki/Post-Scheduling-101#the-cron) is to be responsible for keeping time in a reliable way. This should be implemented as a pluggable/replaceable adapter so that different environments can drop in their own implementations based on their requirements.

## Adapter Layer

**Messages from the Scheduler**

The adapter layer needs to define the set of methods that a cron adapter must implement. These should provide a simple API for scheduling, rescheduling and unscheduling 'jobs'. The Cron can expect to be passed the following information:

- the time the job is scheduled for (datetime, or cron time)
- the API URI to call at the given time

The URI to call passed from the scheduler will be unique to a job, such that it's possible to determine which item is being [re|un]scheduled. The adapter will need to receive the details of the client id and secret it should use to authenticate its calls to the API URI. 

**Retrieving info from The Scheduler**

The Scheduler also provides a way for The Cron to retrieve information about scheduled jobs in the form of an API endpoint [see here](https://github.com/TryGhost/Ghost/wiki/Post-Scheduling-101#providing-information). This is so that it can do some initial processing when it is first started, or recover from failure. 

It may make sense for this endpoint + the client id and secret to be provided to The Cron when it is constructed. Note that Ghost API endpoints can be used via method call or HTTP.

**Defining the active adapter** 
In a very similar way to the storage adapter, we need a way to determine which adapter is in use and to pass any configuration that the adapter needs. Configuration should follow the same pattern as [storage](https://github.com/TryGhost/Ghost/wiki/Using-a-custom-storage-module#configjs).

Ideally, we'd also have a way to check that a provided adapter implements all of the required methods, or otherwise falls back to the default.

We're looking at moving towards having adapters be true npm modules. There was also a plan to refactor the storage adapter so that the base file was an npm module that would be required by any implementation of it [see example implementation](https://github.com/vdemedes/Ghost-Storage-Base). I think it's worthwhile considering this approach for the cron adapter, even though it's not as complex as the storage adapter. 

## Default Cron Implementation

The intention for the default cron is to make use of the [node-cron](https://github.com/ncb000gt/node-cron) module to handle scheduling jobs using the [hybrid strategy](https://github.com/TryGhost/Ghost/wiki/Post-Scheduling-101#strategy-e-hybrid). 

E.g. run a job at a regular interval, which asks the scheduler for items which were missed (Scheduled in the past) or are due before the job runs again. The items returned will then be scheduled to happen at the right time. The interval should be 5minutes by default, but this should ideally be configurable in config.js.

As part of an initial implementation, it would be useful to test out how node-cron works when used with 100s/1000s of jobs and if it can handle that sort of scale.

The default cron should send requests to the scheduler URIs at the correct time, and listen for the response. If it gets a 200 or a 404, we can consider the job 'done'. If the response is an error, it would be preferable to retry 3 times, at a sensible interval, before giving up.

**Comment by jtwebman** [comment]
@ErisDS Are you ok with me starting a new repo in Ghost organization for this?

**Comment by jtwebman** [comment]
# My proposed Post Scheduling change

Why the change? To help out with the Heroku's and systems that are not always running. With little extra work we can get a system that covers 99% of all use cases. With the current proposal the Heroku's will have to setup a scheduler that calls the API to get all the events and do their own work to making the calls. I think if we move a few things around like my proposal below the same code can be called for both a default local always running blog and the Heroku’s not always running blogs.

So with that said here is my proposed change.

We would have 2 adapters built into Ghost, default and self calling below. If those two ways don’t work for you you can npm install your own adapter and reference it in the config.js, see custom npm module below.

## Default: 
### Adapter 
Runs a simple setInterval and every 5 minutes (configurable) that calls the service (really just a function with a callback) below to run. This adapter would not implement add, update, remove and sets notify = false as the service will handle it by getting all the events each time. Will only work if you are Ghost blog is self hosted and you know it will always be running.

### Service 
Will get all the events in the system and run any missed events and schedule any new events that are about to happen out till the next run time. This is [Strategy e](https://github.com/TryGhost/Ghost/wiki/Post-Scheduling-101#strategy-e-hybrid) and what you called the [Default cron](https://github.com/TryGhost/Ghost/wiki/Post-Scheduling-101#default-cron).

## Self Call: 
### Adapter
Does nothing on init. Doesn’t implement add, update, remove and sets notify = false.

### Service
Same service as Default above but will be called through an API endpoint. You could setup a Heroku service to call the API or an aws lambda or even run your own cron job. It will be up to you to call the api at whatever interval you want and will run all events that were missed. The API will not schedule future events as Heroku or your host might shut you down. This is [Strategy a](https://github.com/TryGhost/Ghost/wiki/Post-Scheduling-101#strategy-a-always-late).

## Custom NPM Module
### Adapter
You will probably want to turn notify on and you will be calling your own service or services for add, update remove but this is totally up to you. You could use this to add events to some other service to track or post social media about the new blog post as well. The sky's the limit.

### Service
Your own.

# Adapter API
The adapters API will be a single function that returns an object with the proper values and functions.

**function(config)** - This is the function that is called when ghost starts. It will take a config object from the config.js and should return an object with the following properties:

**name:** _string_ - Just a string value for the name.

**notify:** _boolean_ - Set to true to have the system call add, update, and remove functions when event happen.

**add:** _function(event, callback)_ - The event object we pass from Ghost can be different based on the type of event. For the first version we will have the following two events.

**One-time Webhook Event**
**id:** _string_ - An unique id for this domain and type. For posts we will use Post ID as a string.
**domain:** _string_ - The site domain.
**type:** _string_ - ‘OneTimeWebhook’
**callOn:** _string_ - Date time iso 8601 format string (As it might be used for JSON or XML API)
**method:** _string_ - The http method ‘GET’, ‘POST’, ‘PUT’, ‘DELETE’, ‘HEAD’, ‘OPTIONS’.
**uri:** _string_ - The url to use to make the call.
**data:** _string_ - A string of data to include in the body like json or xml.

**Cron Webhook Event** 
**id:** _string_ - An unique id for this domain and type. For the queue we will use just ‘post-queue’.
**domain:** _string_ - The site domain.
**type:** _string_ - ‘CronWebhook’
**cron:** _string_ - The cron config string to tell when this should run.
**method:** _string_ - The http method ‘GET’, ‘POST’, ‘PUT’, ‘DELETE’, ‘HEAD’, ‘OPTIONS’.
**uri:** _string_ - The url to use to make the call.
**data:** _string_ - A string of data to include in the body like json or xml.

These two type events I think will cover almost anything, as you can put them on webhooks, but we will leave it open for possibly more.

The callback argument will be a function that you will call passing either an error or nothing if you processed successfully.

**update:** _function(event, callback)_ - This is just like add you will get the same event object. It will be up to your implementation on what you do with it. The callback argument will be a function that you will call passing either an error or nothing if you processed successfully.

**remove:** _function(event, callback)_ - This event object will only have the id, domain, and type as nothing else should be needed to remove. The callback argument will be a function that you will call passing either an error or nothing if you processed successfully.

# Ghost API
`GET /ghost/api/v0.1/schedules/run` - This is the api service I talked about above for the self calling adapter. Will return 200 unless you don’t have access then it will return 401. Will only run missed events not future events.

`GET /ghost/api/v0.1/schedules/post/:id` - This is the endpoint to publish a single data scheduled post. Return 200 if published or already published, 401 if you don’t have access, 404 if is is not a valid post, or 500 if there was some hard error. If it is a hard error retry a few times with a backoff.

`GET /ghost/api/v0.1/schedules/queue` - This would be the endpoint to call to publish the next queued post. Return 200 if published, 401 if you don’t have access, 404 if there is nothing in the queue to publish, or 500 if there was some hard error. If it is a hard error retry a few times with a backoff.

`GET /ghost/api/v0.1/schedules/` - This would be the endpoint to call to get all the currently scheduled events. It would return 200 with an array with all the same values that get passed on add on the adapter API above. Will return 401 if you don’t have access to call it. If there is nothing it will still return 200 with just an empty array.

**Comment by halfdan** [comment]
> Runs a simple setInterval and every 5 minutes (configurable) that calls the service (really just a function with a callback) below to run.

node-cron already does that for you and is smarter about setting the timeout (based on when it expects the next event to run).

**Comment by jtwebman** [comment]
It does have its limits though. You can't schedule any farther out then 24.3 days as setTimeout has that limit but I will stick with Hannahs original spec for now.

**Comment by ErisDS** [comment]
This issue can be picked up & worked by someone else. I know that @jtwebman worked on it for a while, but I believe he is now busy moving house. 

This is the progress if someone wants to work from it: https://github.com/TryGhost/Ghost/compare/master...jtwebman:scheduling

I know that some experimentation was done with node cron and it was discovered it wasn't performant when managing lots and lots of jobs, so it probably makes sense to implement time management & perhaps split this out into our own node module if it works well.

**Comment by kirrg001** [comment]
will take care 👯

**Comment by kirrg001** [comment]
- [ ] trigger scheduled, unscheduled, rescheduled events and care about all kinds of cases
- [ ] create new endpoints for updating scheduled post/page
- [ ] create basic post scheduling module (active adapter, base functions, consume events)
- [ ] implement public ghost core adapter
- [ ] implement ghost pro adapter
