### ISSUE TITLE
Multilingual/Translation/Language Pack support.

### ISSUE THREAD

**Issue by zhang96** [TryGhost/Ghost#6414]
I am currently running a blog under two languages, it will be really useful if there is a multilingual/translation/language pack feature.

**Comment by kevinansfield** [comment]
Hey @zhang96, thanks for reaching out, however this is the bug/issue tracker for on-going development of Ghost and we can't track/respond to feature requests here. We have a [wishlist](http://ideas.ghost.org) where you can add or vote for feature requests and we actively track it and try to implement the most-requested ideas :smile:

**Comment by zhang96** [comment]
Thanks for the information!
