### ISSUE TITLE
shortcut for choose tag

### ISSUE THREAD

**Issue by bannychen1983** [TryGhost/Ghost#6419]
if i have 9 tags and when editing new post and need to choose tag which shortcut should i use?

**Comment by novaugust** [comment]
Hey @bannychen1983, we use github for tracking issues with Ghost. For help using it, check out the [support guides](http://support.ghost.org/) or ask questions in the [slack community](https://ghost.org/slack/).
If you're asking about keyboard shortcuts for opening the tag menu, there aren't any currently
