### ISSUE TITLE
fliter within 3 tables

### ISSUE THREAD

**Issue by markstock7** [TryGhost/Ghost#6420]
i am using you gql and i got a problem of using it. i am building a small document platform as practice，
i have three tables like these：
Schema[prefix + 'documents'] = {
    id: {type: 'increments', nullable: false, primary: true},
    created_at: {type: 'dateTime',  nullable: false},
    created_by: {type: 'integer',  nullable: false},
    updated_at: {type: 'dateTime',  nullable: true},
    updated_by: {type: 'integer',  nullable: true}
};

Schema[prefix + 'attributes'] = {
    id: {type: 'increments', nullable: false, primary: true},
    attr_name: {type: 'string', 'maxlength': 60, nullable: false},
    type: {type: 'string', maxlength: 150, nullable: false, defaultTo: 'text'},
    created_at: {type: 'dateTime',  nullable: false},
    created_by: {type: 'integer',  nullable: false},
    updated_at: {type: 'dateTime',  nullable: true},
    updated_by: {type: 'integer',  nullable: true}
};

Schema[prefix + 'attributes_documents'] = {
    id: {type: 'increments', nullable: false, primary: true},
     post_id: {type: 'integer', nullable: false, unsigned: true, references: 'posts.id'},
    document_id: {type: 'integer', nullable: false, unsigned: true, references: 'documents.id'},
    attributes_id: {type: 'integer', nullable: false, unsigned: true, references: 'attributes.id'},
    value: {type: 'text', maxlength: 16777215, fieldtype: 'medium', nullable: true},
    role: {type: 'string' ,maxlength: '20', default: ''},
    sort_order: {type: 'integer',  nullable: false, unsigned: true, defaultTo: 0}
};
what if i want to find documents which its 'a' attribute's value is like "value", hot to do with filter

**Comment by halfdan** [comment]
Hi @markstock7,
we use Github to track issues with Ghost. We have community support over in our [Slack community](http://ghost.org/slack).

**Comment by markstock7** [comment]
sorry, i am new to github

**Comment by halfdan** [comment]
No problem at all :)
