### ISSUE TITLE
Bug: nav-current misses trailing slashes

### ISSUE THREAD

**Issue by JohnONolan** [TryGhost/Ghost#6422]
https://blog.ghost.org/tag/inspiration/ -- inspiration should receive a class of `nav-current` (as all the other tags do, when selected), but for some reason: it does not :bug:

**Comment by halfdan** [comment]
It is missing a trailing slash. You need to add it in the navigation menu settings.

**Comment by JohnONolan** [comment]
If *I* didn't notice that, I think it's fairly safe to say that others won't either and we should do a better job of handling it :dancer:
