### ISSUE TITLE
Regression: Unable to reset password

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#6423]
When trying to reset your password, Ghost shows the message "Your password must be at least 8 characters long." regardless of whether the password field is filled in or not.

### Steps to Reproduce

1. Go to `/ghost/` sign out if you're already signed in
2. Fill out your email address, but not password
3. Hit 'Reset'
4. The button spins and then you get the error "Your password must be at least 8 characters long."
5. Try entering an incorrect 8+ char password, still get the same error

![](http://puu.sh/mSVph.png)

### Technical details: 

* Ghost Version: master

**Comment by kevinansfield** [comment]
The client side appears to be fine, the error is originating from the API. I had a quick check and I think we're missing server-side tests for the password reset flows.

I'll leave this for someone with more experience with the node app to pick up, they'll probably be much quicker at fixing it than I will be! :smile:

**Comment by halfdan** [comment]
The issue here is that a PUT request is sent where it should be a POST.

**Comment by kevinansfield** [comment]
Oh, good :fishing_pole_and_fish:! Ran into that when putting the mirage config but didn't put two and two together and get had it respond to the PUT request :disappointed:
