### ISSUE TITLE
Standardize admin client error handling

### ISSUE THREAD

**Issue by acburdine** [TryGhost/Ghost#6431]
One of the problems that has been causing more issues recently is that there isn't much of a standard for errors throughout the app. This is problematic (see #6207) because in tests, there isn't much of a way to determine from where an error is being thrown.

In the transition to ember-ajax (see #6243) part of this was completed.

Ember has a built in error object that can be extended to suit these purposes. It may also be helpful to add some things in to support il8n.

As a result of this issue too, it would be good to update tests that check for errors to make sure that the proper errors are being returned.

**Comment by acburdine** [comment]
Sorry, shouldn't type out issues on my phone :stuck_out_tongue:

**Comment by kevinansfield** [comment]
Closing as this has been mostly resolved via https://github.com/TryGhost/Ghost-Admin/pull/65 (and related PRs) and will be further standardised with #7014.
