### ISSUE TITLE
Adding navigation urls with no protocol is not handled gracefully

### ISSUE THREAD

**Issue by kevinansfield** [TryGhost/Ghost#6433]
![another-nav-bug](https://cloud.githubusercontent.com/assets/415/12791336/a5699a38-ca9e-11e5-8d10-83768ce30324.gif)

As you can see from the screen cap, entering `foo.com/bar` as a navigation url results in that url being rewritten as `http://yourblog.com/foo.combar`.

Should we have some level of detection for a domain-like string and if found prefix it with `http://`? My reasoning for defaulting to `http` is that it's the first protocol that would be tried if that same string was typed into a browser address bar and I believe that pretty much website that requires `https` will have a http->https redirect in place.

**Comment by halfdan** [comment]
> some level of detection for a domain-like string

I guess this is the tricky part. When entering `foo.svg` vs. `foo.com` I would expect the first to be replaced with an absolute URL (since it's a file) and the latter to just get the protocol prepended. This however seems very difficult to do without having a list of all valid TLDs stored somewhere in Ghost.

Another approach would be to look for a string with n-`.`'s and at least one slash.

Something like http://rubular.com/r/JvMAHoL7Un

**Comment by ErisDS** [comment]
As per the discussion in Slack - I see a validation error, which I think makes sense:

![](http://puu.sh/mUw7P.png)

The case that @kevinansfield shows with a slash should definitely not be modified to remove the slash. 

As per the comments in [slack](https://ghost.slack.com/archives/dev/p1454521334001013) it seems there might be a crack where there is different behaviour between focus and save which needs investigating.

**Comment by halfdan** [comment]
@ErisDS How did you get that validation error (what version of Ghost)? I see the validation code but even on 0.7.5 the input is replaced with '${url}/foo.combar` before the validation is run. Seems like a regression that dates back to at least 0.7.3

**Comment by kevinansfield** [comment]
There's definitely issues here somewhere, I can sometimes get what looks like an empty url to be added without triggering validation.

**Comment by kevinansfield** [comment]
Closing as these issues have been resolved now.
