### ISSUE TITLE
Underscores are being stripped from posts!

### ISSUE THREAD

**Issue by samdeman22** [TryGhost/Ghost#6434]
I want to use Mathjax on my blog, and so far it has worked, except some thing like this $$\prod_{i=1}^{d} \int_{-\infty}^{\infty} dxi e^{-x_i^2}=(\sqrt{\pi})^d= \sqrt[d]{\pi}$$ doesn't seem to work, because the underscores are being stripped away! (This is using Ghost 0.7.4 from the digital ocean one-click app)

I believe it has something to do with italics... is there a way I can ignore italics for underscores? I really don't need this given that emphasize with * already exists.

**Comment by samdeman22** [comment]
Well, I'm a dumb, sort of: I realised that you can use backslashes to escape markdown, so anywhere I need to use an underscore I can just type \_ instead; this is a little awkward though. Before this is closed, does anyone know if the markdown can be customized at all, such that I could disable _ providing emphasis?

**Comment by acburdine** [comment]
@samdeman22 not at the moment, but the editor is undergoing a major overhaul that should make this kind of customization possible :smile:

**Comment by AustinPaquette** [comment]
> the editor is undergoing a major overhaul

@acburdine If I could like posts on here I would. I look forward to seeing the improvements. The Ghost editor is wonderful but it certainly lacked a couple of key things I think would really improve blogging in general. Curious to see the result :+1:

**Comment by samdeman22** [comment]
@acburdine well, that's good to know!
