### ISSUE TITLE
Code syntax in markdown

### ISSUE THREAD

**Issue by Lyken17** [TryGhost/Ghost#6441]
text below cannot rendered by ghost properly, is there a way fix it ?
```
1. hello
    ```prettyprint lang-python
    code here
    ```
2. world
```

**Comment by MrBoolean** [comment]
Hmmmm... gh also dont render this. What's the expected output?

**Comment by Lyken17** [comment]
<img width="909" alt="screen shot 2016-02-05 at 14 36 47" src="https://cloud.githubusercontent.com/assets/7783214/12861121/e7243186-cc15-11e5-8068-61b2cf6f169a.png">
I think expected out should be like this picture

**Comment by ManuelRauber** [comment]
Just use the correct markdown for it:

1. hello

    ```lang-python
    for i in xrange(10):
        print(i)
    ```
2. world

```
1. hello

    ```lang-python
    for i in xrange(10):
        print(i)
    ```
2. world
```

You just need one more break to start a new block level. :)

**Comment by egru** [comment]
I'm having the same issue. Ghost is not rendering the code blocks in nested lists. I used the correct markdown, which I verified in other editors, but it just doesn't want to display correctly in Ghost.

**Comment by ManuelRauber** [comment]
@egru Can you provide a code sample?

**Comment by egru** [comment]
Here are two examples.

```
1. hello

    ```lang-python
    for i in xrange(10):
        print(i)
    ```
2. world
```


![untitled2](https://cloud.githubusercontent.com/assets/381117/13911780/da6a9b82-ef02-11e5-8b9c-8a19e2e349b1.png)

```
1. hello

        ```language-python
        for i in xrange(10):
        print(i)
        ```
2. world
```

![untitled](https://cloud.githubusercontent.com/assets/381117/13911790/f3ec9628-ef02-11e5-8910-28dfecb48c16.png)

**Comment by ErisDS** [comment]
The problem here is specifically to do with trying to have fenced code blocks inside lists & therefore indented: https://github.com/TryGhost/Ghost/issues/5632 the indent results in the fences not working

If you have:


    **1. List item that's bold or a header**
   
    ```language-python
    code block
    ```

That is a workaround for the time being

**Comment by egru** [comment]
Alright. I'll have to hold off on migrating from wordpress for the moment then. I have a lot of content with code blocks in lists.

**Comment by d0u9** [comment]
This issue bothers a lot. It is hard to copy-paste documentation from github README.md to Ghost. The syntax difference between Ghost and GFM tastes disgusting.
