### ISSUE TITLE
Running grunt init causes stderr maxBuffer exceeded error

### ISSUE THREAD

**Issue by sudheesh001** [TryGhost/Ghost#6443]
STR:

1. git clone
2. npm install -g grunt-cli
3. npm install
4. grunt init

This threw an error
```log
...
npm http GET https://registry.npmjs.org/lodash._isiterateecall
npm http 304 https://registry.npmjs.org/component-emitter/1.1.2
npm http 304 https://registry.npmjs.org/lodash._createpadding
npm http 304 https://registry.npmjs.org/lodash._basetostring
npm http GET https://registry.npmjs.org/lodash._getnative
npm http GET https://registry.npmjs.org/process-nextick-args
Warning: stderr maxBuffer exceeded. Use --force to continue.

Aborted due to warnings.
```

#### System information

OS: Mac OS X El Capitan v 10.11
Memory: 16GB RAM

**Comment by ErisDS** [comment]
Hi @sugeesh001, sorry to hear you're having trouble. 

As mentioned in the readme & contrib guide, if you have questions about Ghost or need help, please head on over to slack - https://ghost.org/slack/ - and post in the #help channel. There you can get help & support from the Ghost community, which we're not able to do here in the GitHub bug tracker.

In this particular instance though, the issue you're seeing is with npm, not with Ghost. `npm` is a resource hog! I recommend searching their repository and documentation for solutions.
