### ISSUE TITLE
Upgrade should.js dev dep to the latest version

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#6448]
We're currently on version 6.0.3 of [should.js](https://github.com/shouldjs/should.js). 

Version 7.0.0, which is the next version, has [breaking API changes](https://github.com/shouldjs/should.js/blob/master/History.md#700--2015-06-18). 

These mean that all assertions, such as `should.be.true` must now be function calls: `should.be.true()`, this is to prevent false positives.

Instructions on how to upgrade the codebase for 7.0.0 and 8.0.0 can be found [on the should wiki](https://github.com/shouldjs/should.js/wiki/Breaking-changes). (I don't think there are any changes in 8.0.0 that affect us).

The work to check through and make sure all of our tests use the same correct is a fairly big task. The should docs say there's no real need to migrate a live project, but I think we could benefit from the newer version of the API being more consistent.

**Comment by cameronviner** [comment]
Hey @ErisDS id like to have a go at fixing up this issue if its still free?

**Comment by ErisDS** [comment]
@cameronviner yes it's free for anyone to pick up :wink:

**Comment by victorddiniz** [comment]
@ErisDS , was this assigned to @cameronviner or is it still free?
