### ISSUE TITLE
Bug with reordering+deletion in Navigation page

### ISSUE THREAD

**Issue by nicwaller** [TryGhost/Ghost#6457]
I found a reproducible bug in the Navigation page that could potentially allow a user to delete more entries than they intended.

Actual results:
After some combinations of list-reordering steps, the list gets into a bad state where attempting to delete a single row actually ends up deleting multiple rows.

Expected results:
Clicking the delete icon for a row should delete only the intended row, nothing more or less.

Steps to reproduce:
- Create five entries ("Aardvark", "Bat", "Cat", "Dog", "Elephant")
- Move "Dog" into the second position (above "Bat")
- Move "Elephant" into the third position (above "Cat")
- Delete the fourth item ("Bat")
(At this point three rows have been deleted instead of one.)

Reproducibility:
100%. I can consistently reproduce this with the steps described.

Other details:
I'm using the hosted blogging platform on ghost.io, not the self-hosted distribution. I can't tell what version is running. The meta `ghost/config/environment` shows version "0.0.0 26ea9ad8" but that doesn't match up with a commit in this repo.

**Comment by kevinansfield** [comment]
Hey @nicwaller, thanks for the report! I have an in-progress PR that replaces `jquery-ui.sortable` for nav items drag-n-drop with `ember-sortable` so I'll ensure the fix makes it into that.

> I can't tell what version is running.

If you are on Ghost(Pro) then you are always on the latest release. To see the current version you can click the drop-down button in the top left of the admin screen and select "About Ghost".

**Comment by nicwaller** [comment]
I am using Ghost(Pro) but I don't see "About Ghost" in the list of options.
 
![screen shot 2016-02-08 at 1 03 37 am](https://cloud.githubusercontent.com/assets/2850248/12881594/e92e18ca-cdff-11e5-9afb-7e6c44ee025c.png)

**Comment by nicwaller** [comment]
Aha, there it is! I kept looking in the bottom-left corner where the help/support options are. The about page (and application version) seems more relevant to support activities than to my user profile and login status.

I'm using Ghost(Pro) version 0.7.6. (Just adding this here for completeness.)
