### ISSUE TITLE
Update server side validator.js dependency, and fix deprecation warnings

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#6462]
Once we update to the latest version of validator, it will start outputting deprecation notices for all the places where we are incorrectly passing validator a non-String value.

Validator only validates strings [see here](https://github.com/chriso/validator.js#strings-only).

The warnings output during the tests look like this (there are quite a few):

`validator deprecated you tried to validate a number but this library (validator.js) validates strings only. Please update your code as this will be an error soon. core/server/data/validation/index.js:159:39`

This is an indicator of something we're doing very wrong, the deprecation notices will be very helpful for locating all the places it is happening and getting rid of them. However, I don't think we should upgrade without also fixing the issues, as this will result in lots of extra output in the test/server console that is just confusing if you don't know what it is.

Please note: we use a special convention for the title line in a commit message changing a dependency:

```
deps: validator@x.x.x

closes #6462

- Summary of 
- things that were 
- changed
```

**Comment by aalsi** [comment]
@ErisDS : I can work on deprecation warnings, new version of validator.js is **4.7.1**

**Comment by ErisDS** [comment]
:+1:

**Comment by yash14123** [comment]
Is this one still open?
