### ISSUE TITLE
Ghost admin redirecting to old URL on azure

### ISSUE THREAD

**Issue by kdpuvvadi** [TryGhost/Ghost#6479]
I've installed ghost on Azure and with default url `site.azurewebsites.net` and added custom domain name and when i try to visit `example.com/ghsot` it is actually redirecting to  `site.azurewebsites.net/ghost`. In `config.js` 

`var path = require('path'),
    websiteUrl = process.env.websiteUrl,
    config;
if (!websiteUrl || websiteUrl === '' ||  websiteUrl.length === 0) {
    websiteUrl = 'http://' + process.env.siteName + '.azurewebsites.net';
    console.log(websiteUrl);
}`

When i removed `azurewebsites.net` in the if block entire site giving me black pages and i'm unable to add anything in the navigation with the custom domain.

**Comment by ErisDS** [comment]
Hi @kdpuvvadi, sorry to hear you're having trouble. 

This seems like an azure specific environment problem. As mentioned in the readme & contrib guide, if you have questions about Ghost or need help, please head on over to slack - https://ghost.org/slack/ - and post in the #help channel. There you can get help & support from the Ghost community, which we're not able to do here in the GitHub bug tracker, however in this case I'd recommend reaching out to azure support first.
