### ISSUE TITLE
Bug: Unable to transition from new post to Tags screen

### ISSUE THREAD

**Issue by kevinansfield** [TryGhost/Ghost#6483]
### Steps to Reproduce

1. Click the New Post link in the sidebar
2. Click the Tags link in the sidebar
3. Nothing happens, this error is shown in the console: `Uncaught Error: Assertion Failed: When ember-selectize is in multiple mode, the provided selection must be an array.`

This is a bug because you should be able to transition to the Tags screen from the editor screen. It also puts you in a state where it's not possible to add new tags via the PSM's tags input.

### Technical details

* Ghost Version: master - latest commit:  c9e0a70
* Client OS: OS X
* Browser: Chrome 48.0.2564.103 (64-bit)

**Comment by ErisDS** [comment]
FYI: (not sure if this is helpful or if you already know) this only occurs if you have tags.

If you delete all content, it's fine. Once you add a single tag, not fine :)

**Comment by ErisDS** [comment]
I've added the fix-wanted label here. I'm kinda guessing the thought is that as the underlying dependencies are being replaced this bug will get auto-squashed, but I think it may need a quick fix short term?

I can't judge ember issues, but if it's simple, adding the `beginner` tag is always good for encouraging fixes :grin:

**Comment by acburdine** [comment]
Figured out a fix :tada:
