### ISSUE TITLE
Can't not send mail to reset password/invite members

### ISSUE THREAD

**Issue by kenzaburo** [TryGhost/Ghost#6485]
I read your introduction page about how to setup config.js to send mail to other member. 
I tried Gmail and MailGun but I didn't send successfully. 
My config.js as below. Could anyone help me?

config = {
    // ### Production
    // When running Ghost in the wild, use the production environment.
    // Configure your URL and mail settings here
    production: {
        url: 'http://www.ma-pi-leng.com',
	mail: {	transport: 'SMTP',
    		options: {
        		service: 'Mailgun',
        		auth: {
            			user: 'postmaster@sandbox130c3feefa144e92a08a7af017846bbd.mailgun.org',
           			 pass: 'xxxx'
        		}
    		}
},
        database: {
            client: 'sqlite3',
            connection: {
                filename: path.join(__dirname, '/content/data/ghost.db')
            },
            debug: false
        },

        server: {
            host: '128.199.128.234',
            port: '80'
        }
    },

**Comment by ErisDS** [comment]
Hi @kenzaburo, sorry to hear you're having trouble. As mentioned in the readme & contrib guide, if you have questions about Ghost or need help, please head on over to slack - https://ghost.org/slack/ - and post in the #help channel. There you can get help & support from the Ghost community, which we're not able to do here in the GitHub bug tracker.
