### ISSUE TITLE
Move `builtFilesExist` check into utils/startup-check.js

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#6493]
I think that the `builtFilesExist` check should be moved out of the server index / boot flow, and into the startup checks, which live in `server/utils/startup-check.js`. I can't see any reason why this needs to live in `core/server/index.js`, it depends on a single key from the config, but so do other startup checks.

It also makes sense to me to do this particular check quite early on - if the files aren't present there's not much point trying to do anything else :wink: So placing it after the `contentPath()` checks makes sense IMO.

This will also result in it not needing to be translated, which as a console warning I don't think it should be anyhow.

**Comment by javorszky** [comment]
Dibs! I might actually be able to do this! :)

**Comment by halfdan** [comment]
Go go go @javorszky
