### ISSUE TITLE
[Feature] Additional theme search paths

### ISSUE THREAD

**Issue by kravemir** [TryGhost/Ghost#6498]
I would prefer to have a more control about paths. 

Especially, I don't like that themes are under content directory, because themes aren't content of the blog. Content is data with meaning (posts, images, additional user content... ). Themes are just resources used by software to render the content, they are not content itself.

Also, I would like to have the possibility to specify more paths, ie:

```
themePaths : [ 
    blog_local, 
    user_local / organization_local,
    shared_default_themes
];
```

Where there would be priorities of searching, ie. first path containing a theme wins.

**Comment by acburdine** [comment]
Hey @kravemir, thanks for your request! Unfortunately, the Github issue tracker is for issues with Ghost itself (i.e. bugs, optimization, implementation tracking, etc.). However, you can request your feature over at ideas.ghost.org and people can vote on it. If enough people want this as a feature, then we can implement it :smile:
