### ISSUE TITLE
Admin error instead of 404 for post not found, when no posts are available

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#6503]
If you try to view a post by ID, when there are no posts available, an error appears in the console and Ghost displays a 500 error.

### Steps to Reproduce

1. Delete all your content
2. Try to view a valid post id, e.g. /ghost/200/
3. See a 500 error and the following in the console: 

![](http://puu.sh/n7O6G.png)

This is pretty edge case, but would be nice to fix

### Technical details: 

* Ghost Version: master (latest commit: 7c47249)

**Comment by acburdine** [comment]
I can fix this today :smile:

**Comment by acburdine** [comment]
Just looking at this, it appears to be a bug with ember-data. I can build in a workaround for the moment, but will open an issue there as well.
