### ISSUE TITLE
Clean up tests etc, now that should.js has been upgraded

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#6505]
In https://github.com/TryGhost/Ghost/pull/6464, should.js was upgraded to a new version, with a better API.

As a result of this change, there are some extra lines which can be removed:
- [ ] The first is the jshint declaration which appears at the top of many files ([example](https://github.com/TryGhost/Ghost/pull/6464/files#diff-4fdea5016a3fba533bd0f17df90299bcR2)), which looks like `/*jshint expr:true*/` - this was because the should expressions looked weird & jshint complained. The new syntax solves this, so the declaration isn't needed.
- [ ] The second is the `should.equal(true, true);` line ([example](https://github.com/TryGhost/Ghost/pull/6464/files#diff-4fdea5016a3fba533bd0f17df90299bcR8)), which was also another fix for jshint & should's weird syntax.

There's one other clean up task to do as well:
- [ ] update [greenkeeper ignores](https://github.com/TryGhost/Ghost/blob/master/package.json#L109) to remove `should`.

**Comment by cameronviner** [comment]
Sorry @ErisDS this completely slipped my mind, I'll take a look at this now if thats okay.
