### ISSUE TITLE
ember-resolver couldn't load in certain Chrome version

### ISSUE THREAD

**Issue by sanddudu** [TryGhost/Ghost#6511]
### Issue Summary
When accessing admin sign in page, the whole page could't load and threw these messages in console:
```
Uncaught TypeError: RegExp.prototype.sticky getter called on non-RegExp @vendor.js?v=1a4d11d9bf:174368

Uncaught Error: Could not find module `ember-resolver` imported from `ghost/app` @vendor.js?v=1a4d11d9bf:144
```

But it works fine in Chrome 50.0.2651.0 canary (32-bit).
Also tested in Internet Explorer 11.103.10586.0.

### Technical details:
* Ghost version: 0.7.6 (Release)
* Client OS: Windows 10 Pro 10586.104
* Server OS: Ubuntu 12.04 LTS
* Browser Version: Chrome 48.0.2564.109 m (64-bit)
* Node version: 0.10.26
* Database: SQLite

**Comment by acburdine** [comment]
So to fix this you have to disable experimental JavaScript in Chrome. If that doesn't work try heading over to our [slack channel](http://slack.ghost.org) and we can investigate this further.

**Comment by sanddudu** [comment]
@acburdine It works. Thank you.

**Comment by ErisDS** [comment]
Note this is a duplicate of https://github.com/TryGhost/Ghost/issues/6102
