### ISSUE TITLE
Authors cannot see their own posts

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#6512]
If you log in as an author on Ghost master, it always says "You haven't written any posts yet!" even if you have...

### Steps to Reproduce

1. Make sure that your blog has an author user with at least 1 post
2. Log in as the author
3. Notice you can't see your posts!

This issue has been introduced since 0.7.6. I've tested it out and have determined that the server is sending the correct response, but that `this.get('authorId')` is undefined here: https://github.com/TryGhost/Ghost/blob/9eac05e082b7e488fa160ca967c7ec6e8925a613/core/client/app/models/post.js#L84.

I'm not sure what's causing it to be undefined.

I also noticed a second minor issue with the filter query, as it adds the author statement over and over again each time you visit the content screen:

Request 1:

http://localhost:2368/blog/ghost/api/v0.1/posts/?page=1&limit=15&status=all&staticPages=all&filter=author%3Anot&include=tags

Request 2:

http://localhost:2368/blog/ghost/api/v0.1/posts/?page=1&limit=15&status=all&staticPages=all&filter=author%3Ahannah%2Bauthor%3Ahannah&include=tags

Although undesirable, this does not cause any errors or incorrect data to be shown and so is not urgent.

I think at some point there needs to be some sort of small util for building the queries, as ideally the whole query should be using filter rather than the `status` and `staticPages` params like this (currently there are no 'all' aliases'):

`filter=page:[true,false]+status:[draft,published]+author:hannah`

### Technical details: 

* Ghost Version: master (latest commit: 3c5c5ad) Not present in 0.7.6

**Comment by acburdine** [comment]
*raises hand* I'll take a look at this later today.
