### ISSUE TITLE
Cleanup client side query usage to use filter when possible

### ISSUE THREAD

**Issue by acburdine** [TryGhost/Ghost#6515]
Taken from #6512:

> I think at some point there needs to be some sort of small util for building the queries, as ideally the whole query should be using filter rather than the status and staticPages params like this (currently there are no 'all' aliases'): "filter=page:[true,false]+status:[draft,published]+author:hannah"

This utility should be built, and all places in the codebase that use `query` or `queryRecord` calls converted to use the filter parameter as much as possible.

**Comment by ErisDS** [comment]
This should also fix the  issue with the filter query, whereby it adds the author statement over and over again each time you visit the content screen:

Request 1:

http://localhost:2368/blog/ghost/api/v0.1/posts/?page=1&limit=15&status=all&staticPages=all&filter=author%3Anot&include=tags

Request 2:

http://localhost:2368/blog/ghost/api/v0.1/posts/?page=1&limit=15&status=all&staticPages=all&filter=author%3Ahannah%2Bauthor%3Ahannah&include=tags

etc

**Comment by ryrych** [comment]
@acburdine do you mean that, for example:

```js
// https://github.com/tryghost/ghost/blob/39dfb2c09a95f04a01300b4216cf2798b160ee2f/core/client/app/routes/editor/edit.js#L27-L33
query = {
    id: postId,
    status: 'all',
    staticPages: 'all'
};

return this.store.query('post', query).then((records) => {
    let post = records.get('firstObject');
},
```

should use this utility? I've found like 70 ocurrences of `query` (`ag query -w core/client`). I suppose that the refactor should not be difficult.

More info is welcome.

**Comment by acburdine** [comment]
@ryrych That's definitely a place, yes. I'm not sure if _every_ instance of store.query should be refactored to use a filtering utility => some don't have complex ones. If you want to pick this up go right ahead :smile:

**Comment by ryrych** [comment]
@acburdine I can pick it up and will start the work during the weekend.

**Comment by ryrych** [comment]
Is there a public Postman config? @acburdine

**Comment by acburdine** [comment]
What do you mean by that?

**Comment by kevinansfield** [comment]
I think this can probably be closed? We only have complex queries for posts on the content screen now and since adding the redesign posts list and filters we use the `filter` param.

Maybe once we have additional use cases we can look at extracting some logic into a util.

/cc @ErisDS
