### ISSUE TITLE
Add markdown formatting to the Blog Description text area

### ISSUE THREAD

**Issue by auermi** [TryGhost/Ghost#6522]
This would allow for the inclusion of links and other general formatting.

**Comment by novaugust** [comment]
Hey @auermi, thanks for your enthusiasm for making Ghost better. However, Github's not the place for feature requests - you're looking for the [ideas page](http://ideas.ghost.org/forums/285309-wishlist). We use Github exclusively for bug tracking and ongoing implementation work.
