### ISSUE TITLE
Any solutions for large size image shows in mobile devices

### ISSUE THREAD

**Issue by echoloyuk** [TryGhost/Ghost#6523]
Hi everyone~ It is Awesome!! when I setup ghost and run it at first time.

The problem is about the image. It seems that Ghost have not any image processing for a large size files. 

For example, I upload an picture from my camera for my blog cover. The picture size over 3M. It is accessible for PC's browser to download 3M pic through network. But for mobile device (my iphone .eg), It is a horrible experience, not only waiting much time to render but also costing much money of data traffic. So is there are any solutions to solve this problem? Compress image when upload large image? Or show the abstract image when the agent is mobile device? Or any other solutions?

I m not good at English, say sorry for any syntax error.

**Comment by novaugust** [comment]
Hey @echoloyuk, glad you're excited about Ghost. Like you've noticed, there's no support for image processing in Ghost, but you're not alone in desiring it - just check out the [features wishlist](http://ideas.ghost.org/forums/285309-wishlist). Feature requests live over on that wishlist. 
We use Github exclusively for tracking bugs and ongoing feature implementation, so I'm going to close this

**Comment by echoloyuk** [comment]
@novaugust Thank you for your reply. Github issue is the only way I v known to contact ghost team, soooo sorry.

And now, I m already Ghost user.
May Ghost better than best!!!
