### ISSUE TITLE
[Labs]: idea: have an easy import from WordPress option under Labs because WP API

### ISSUE THREAD

**Issue by javorszky** [TryGhost/Ghost#6528]
So now that the WP REST API is a thing, and it's in core, we can potentially point Ghost at the necessary URL (user gives URL, auto-discovery), and Ghost would siphon all the content needed for that.

I'm going to be spending time discovering whether / how this is possible.

**Comment by nuclearpengy** [comment]
Cool! :)

**Comment by ErisDS** [comment]
I'm super interested in seeing an implementation of this, however I'm going to close the issue for now as it doesn't have traction :)
