### ISSUE TITLE
Putting paths option in production config throws error on heroku

### ISSUE THREAD

**Issue by andela-eashikodi** [TryGhost/Ghost#6529]
```
 [Error: ENOENT: no such file or directory, scandir '/app/content/apps']
```

This works fine already in development mode. 

If removed from production config, works fine but how do user , for example, add a theme to themes folder

**Comment by ErisDS** [comment]
Hi @andela-eashikodi, sorry to hear you're having trouble. As mentioned in the readme & contrib guide, if you have questions about Ghost or need help, please head on over to slack - https://ghost.org/slack/ - and post in the #help channel. There you can get help & support from the Ghost community, which we're not able to do here in the GitHub bug tracker.

**Comment by john-doherty** [comment]
What was the solution to this problem?

**Comment by andela-eashikodi** [comment]
The problem is that you have nothing in your folder, which means the folder gets ignored and doesn't get pushed to the repository. Try put a .gitkeep file or a README.md
