### ISSUE TITLE
Bug: Importer no longer imports.

### ISSUE THREAD

**Issue by cobbspur** [TryGhost/Ghost#6530]
### Issue Summary

If you try to import a file via labs, the Importing label shows on button but nothing happens.
There are no errors in node terminal but web browser says 'Uncaught TypeError: Cannot read property 'post' of undefined'

### Steps to Reproduce

1. Go to labs '/ghost/labs'
2. Create export
3. Attempt to load the exported file or some other valid ghost.json file if you have one

### Technical details:

* Ghost Version: master (latest commit: 2166c378ed2d5234e8123a5fe79f550ed36ed2c3)
* Database: SQLite

**Comment by acburdine** [comment]
Found a fix.
