### ISSUE TITLE
Bug: WordPress plugin wrong info

### ISSUE THREAD

**Issue by eidmantas** [TryGhost/Ghost#6549]
Hello,

The current WordPress plugin states:
Next up spin up your Ghost installation, create a user, or sign in, if you already have an account, navigate to http://yourblogadress/ghost/debug/, and import the posts from the file.

This is not correct and should point out that you need to use 'Labs' within the admin panel.

**Comment by acburdine** [comment]
Hey @eidmantas!

The wp2ghost converter isn't part of Ghost itself, and because this is the issue tracker for Ghost itself; you should open an issue on that repo instead :smile:
