### ISSUE TITLE
{{#get}} tag filtering excludes wrong subset

### ISSUE THREAD

**Issue by ryanmrubin** [TryGhost/Ghost#6568]
I'm running ghost 0.7.8 on Ubuntu Trusty with Node 0.10.25, connected to a mysql db. I'm using the following helper to filter my posts in index contexts:

`{{#get "posts" filter="tags:-news-releases" limit="5" page=pagination.page}}`

The filter works fine for removing News Releases posts from the page, but only if the posts have only the News Releases tag. So, if I have a post with just the excluded tag, it will be removed as expected. However, if I add another tag (or more) to that same post, it re-appears in the query results. I would have expected that the above syntax work to exclude any posts with the specified tag, rather than exclude posts that have *only* that tag.

**Comment by ErisDS** [comment]
Hi there @ryanmrubin, the filtering logic for the helper is still under construction as it were, and  this is a known issue #6309.

**Comment by ryanmrubin** [comment]
Ah, whoops! I tried to find an existing report but didn't search long enough, I suppose. Thanks!
