### ISSUE TITLE
Canonical URL is always http

### ISSUE THREAD

**Issue by robincsamuel** [TryGhost/Ghost#6582]
Canonical url is always http. Since my site redirects http to https, it's creating redirect loops for search engines.

### Steps to Reproduce
Just check https://robinz.in/csrf-token-session-error-with-laravel-on-ie-edge/

**Comment by jasonrwang** [comment]
How did you resolve this?

**Comment by robincsamuel** [comment]
Haven't resolved yet :(

**Comment by ErisDS** [comment]
Hi @robincsamuel, sorry to hear you're still having trouble. You appear to be running an extremely old version of Ghost. Please upgrade and ensure that the url configured in config.js is https. 

If you need further help, please head on over to slack - https://ghost.org/slack/ - and post in the #help channel. There you can get help & support from the Ghost community, which we're not able to do here in the GitHub bug tracker.

**Comment by jasonrwang** [comment]
I double checked my nginx configuration and my config.js file and resolved the issue!

http://support.ghost.org/setup-ssl-self-hosted-ghost/
