### ISSUE TITLE
Simple Post-to-Slack Integration

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#6584]
Integrations are something we have wanted to start experimenting with for a while. One of the most simple integrations we can offer (no complex auth requires) is a slack integration. This will post a nicely formatted message to a slack channel whenever a post is published.

## User Interface

The new integration settings page is going to live in a new admin section, called Apps (see the note on apps at the end of the issue):

![](http://puu.sh/nczOX.png)

The slack integration will use slack's incoming webhook integrations, so it will have very similar settings to what is available there. To make the integration work you'll need to setup an [incoming webhook](https://ghost.slack.com/apps/new/A0F7XDUAZ-incoming-webhooks) and copy your webhook URL into Ghost.

In slack's settings it is possible to configure a channel, a name and an icon for the integration. These are the defaults, so if only the URL is configured in Ghost the defaults will be used. However, Ghost will also provide a channel, name and icon (emoji) interface so that the defaults can be overridden.

![](http://puu.sh/nczNx.png)

For now, it will only be possible to setup a single integration, however in future this may be extended to provide multiple integrations which differ based on things like tags - depending on what users would find useful.

## Backend Implementation

For now, the settings for the slack integration should be stored in the settings table, in a similar fashion to the `labs` or `navigation` setting.  Although the intention is that the first iteration should only allow for a single slack integration, I recommend storing the settings in an array so that this can be easily extended, something like: 

```
[{
    "url": "<webhook_url>",
    "channel": "#general",
    "name": "ghost_bot",
    "icon": "ghost",
}]
```

If a webhook url is configured (this is the only required field), then whenever a new post is published to the blog, a request should be sent to slack containing a payload of what to display. Ghost has an internal event system which can be used to find out when a post is published, much like the xmlrpc ping uses. The request format for sending a message to slack is described in the [incoming webhooks docs](https://api.slack.com/incoming-webhooks). 

*Note, the `request` module which is common for making http/https requests was recently removed from Ghost. There are lots of slack bot node modules, and modules like `request` or `needle` can be used to simplify http/https requests. I think that the slack messages are simple enough that it should be possible using just the basic node https library, without the need for an additional dependency.*

Ghost posts have lots of meta data, and Slack is very good at unfurling URLs. When a Ghost link is pasted into slack,  this is what it looks like:

![](http://puu.sh/ng2j3.png)

The title is a link, there's a description, published date, author and tag info, as well as an image if a cover image is provided for the post.

The simplest and most consistent message may be to just send the URL, and let slack unfurl the URL. However, I'm not 100% if this will work via the webhook. 

Alternatively, it's possible to send [attachments](https://api.slack.com/docs/attachments) which provide a lot of control over what slack displays, including the colour of the bar next to the message, fallback text, and fields which should be displayed.

Quicklinks: 
- [incoming webhooks docs](https://api.slack.com/incoming-webhooks) 
- [attachments docs](https://api.slack.com/docs/attachments)

---

A note on Apps:

For the longest time, we've had an idea of an App system for Ghost that lets users extend, customise and integrate with Ghost. However, the concept is so broad and all encompassing that we've never gotten close. To try to move forward with this, the intention is to start building things into core that we originally thought would be apps, to see how they get used and to figure out exactly what extension points we need. Over time, we'll likely move many bits of functionality out into apps, which would be automatically installed for those who use the feature.

**Comment by ErisDS** [comment]
@JohnONolan can you confirm that the slack message should look the same as / similar to a Ghost post URL unfurl, or is there some other display format we should look to use?

**Comment by JohnONolan** [comment]
> The simplest and most consistent message may be to just send the URL, and let slack unfurl the URL. However, I'm not 100% if this will work via the webhook.

IMO this is :+1: - and I'm reasonably sure the unfurl will still work!

**Comment by THook** [comment]
The simplest step forward would let us register lambda function urls, to be used with AWS Lambda or Webtask. See how https://www.graph.cool is handling mutation callbacks :

![capture d ecran 2017-03-17 a 15 27 14](https://cloud.githubusercontent.com/assets/6568065/24047524/48a84d20-0b26-11e7-83c0-e6a8b80be78a.png)
