### ISSUE TITLE
Bug: typo in how-to-upgrade#command-guide

### ISSUE THREAD

**Issue by Arthur2e5** [TryGhost/Ghost#6585]
### Issue Summary

http://support.ghost.org/how-to-upgrade/#command-guide shows a trailing comma (,) after `index.js` in the `cp index.js, *.json` step.

### Steps to Reproduce

1. Open The Page
2. Ctrl-F or Command-F
3. Input `.js,`

This is a bug because there is no such file in the zip archive.

**Comment by acburdine** [comment]
Hey @Arthur2e5! Would you mind emailing support@ghost.org or letting someone know in Slack? This issue tracker is for issues with Ghost itself, not the support website :)

**Comment by Arthur2e5** [comment]
Hmm… Added to my TODO.

**Comment by acburdine** [comment]
@Arthur2e5 I went ahead and did it :smile: it's taken care of. Thanks for reporting!

**Comment by Arthur2e5** [comment]
Ah, great. Thanks for sending the email :)
