### ISSUE TITLE
IPv4+IPv6 Support at same time.

### ISSUE THREAD

**Issue by dasbillgh** [TryGhost/Ghost#6590]
### Issue Summary

I want that Ghost will listen on IPv4+IPv6 so i edited my config.js
but it will listen only on IPv6.

### Steps to Reproduce

I changed the server block in the config.js to:   

server: {
host: '::',
port: '80'
}

The output of netstat:
root@testvm:/var/ghost# netstat -an | grep 80
tcp6       0      0 :::80                   :::*                    LISTEN

### Technical details:

* Ghost Version:0.7.6
* Node Version: 0.10.29
* Browser/OS: Chrome
* Database: sqlite3

Thanks for your great work!

**Comment by ErisDS** [comment]
Hi @dasbillgh, 

I agree with @kevinansfield, who you spoke to in slack, this is the job of your reverse proxy. There's no need to add this sort of feature to Ghost as the connection between your proxy and Ghost is a hidden implementation detail.

To request a feature for Ghost you can add your idea over on our [wishlist](http://ideas.ghost.org). We use this list to help determine what goes into the roadmap and how to prioritise features. You can also access the wishlist any time from inside the Ghost admin:
![](http://puu.sh/jXKwm.png)
