### ISSUE TITLE
keyword bug about ghost

### ISSUE THREAD

**Issue by Army-U** [TryGhost/Ghost#6594]
Hi, I used Ghost for a while. And i found a keyword bug about Ghost.That is $`;We use this word in JavaScript. But i cant render markdown if i insert this keyword twice in my article. eg:

* 2、变量名称是 $&: 替换成匹配到的子串.

```
const string2 = 'abc123abc';
console.log( string2.replace(/\w+?(^\d+)\w+?/g, '$&') ); //abc123abc
```

* 3、变量名称是 $`: 替换成当前匹配子串左边的内容.

```
const string3 = 'abc123abc';
console.log( string3.replace(/(\d+)/g, '$`') ); //abcabcabc
```

* 4、变量名称是 $`: 替换成当前匹配子串右边的内容.

```
const string4 = 'abc123abcd';
console.log( string4.replace(/(\d+)/g, "$'") ); //abcabcabcd
```

markdown cant work above them.thks!

**Comment by ErisDS** [comment]
Hi @Army-U, sorry to hear you're having trouble. I'm afraid I'm not able to reproduce the issue you describe. The examples you've pasted work the same in Ghost as they do here on GitHub:

![](http://puu.sh/nGCNt.png)

Duplicating the snippets with and without fenced code blocks (triple backticks) doesn't reveal an issue: 

![](http://puu.sh/nGD75.png)

If you do need to include 2 backticks in plaintext, you can escape them using backticks:

![](http://puu.sh/nGDdo.png).

If I've misunderstood, please reply with a screenshot showing the issue and I'll reopen this :+1:
