### ISSUE TITLE
ghost project that can be like ember.js packaged into a static item?

### ISSUE THREAD

**Issue by ubuntuvim** [TryGhost/Ghost#6603]
For `ember.js` project can use the command` ember build --prod` packaged into static files directly, no longer need to run `npm start` to run the project, I would like to ask whether` ghost` support to do so, I looked at the official website tutorial did not find the relevant instructions.

**Comment by ErisDS** [comment]
Hi @ubuntuvim!

This sounds like a question about development / contributing? We have a #dev channel in our [slack](https://ghost.org/slack) team, as well as a #help channel for general questions, which are both far more suited to questions than GitHub. The issue tracker here on GitHub is used by devs for keeping tabs on what's going on with development of the software: bugs and work in progress issues.

If you head over to [slack](https://ghost.org/slack) I'm sure someone can help you :+1:

**Comment by ubuntuvim** [comment]
@ErisDS thanks.
