### ISSUE TITLE
update doc: mailgun ghost.mailgun.com is down for a long time

### ISSUE THREAD

**Issue by fredguth** [TryGhost/Ghost#6607]
Ghost documentation suggest using Mailgun for sending email and there is a link for a "config generator", but it is down.  

By the way, it is quite annoying to HAVE to setup email just to add team members.

**Comment by acburdine** [comment]
@fredguth thanks for reporting this but the issue tracker is for issues with Ghost itself, not any of the support docs :smile:

Plus, it seems this may be more of an issue to take up with Mailgun? Either way, if you have further questions/issues please visit our [Slack](http://ghost.org/slack/) channel and you can get help there.

**Comment by fredguth** [comment]
Does the support docs have a github repo?  Because I believe this is pretty important for anyone trying to follow the current documentation.

**Comment by acburdine** [comment]
No it doesn't; however you can email support@ghost.org and ask. I understand how it's important but it's not necessarily Ghost's fault on this one. :smile:

**Comment by chinciusan** [comment]
What happened to the Slack channel?

**Comment by acburdine** [comment]
@chinciusan it's now at https://slack.ghost.org :)
