### ISSUE TITLE
Disable the version check issue

### ISSUE THREAD

**Issue by jafarovr** [TryGhost/Ghost#6608]
Downloaded Ghost v0.7.8 and tried installing using following command: 
``GHOST_NODE_VERSION_CHECK=false && npm install --production``

It should ignore the Node.js version and install it, but I am getting this output:

``ERROR: Unsupported version of Node Ghost needs Node version ~0.10.0 || ~0.12.0 || ^4.2.0 you are using version 5.8.0``

**Comment by acburdine** [comment]
Hey @jafarovr I'm pretty sure you have to export the env variable first e.g. `export GHOST_NODE_VERSION_CHECK=false && npm install --production`.

At any rate, if you have any further issues please visit our [Slack](https://ghost.org/slack/) channel and someone should be able to help you there.

**Comment by ErisDS** [comment]
Haha @acburdine you just beat me to it :wink: 

This is actually a documentation error, which I have now fixed - you need to run

`GHOST_NODE_VERSION_CHECK=false npm install --production` 

Without the ampersands.

**Comment by jafarovr** [comment]
Thanks for that @ErisDS.

Even though I have ``GHOST_NODE_VERSION_CHECK`` set up globally, it does give me same output if I just try ``npm install --production``. But it worked with ``GHOST_NODE_VERSION_CHECK=false npm install --production`` - This is what I wanted!
