### ISSUE TITLE
Don't mutate `process.env.NODE_ENV`

### ISSUE THREAD

**Issue by bioball** [TryGhost/Ghost#6629]
I'm working on an Express app that builds Ghost into a subroute, and am having issues with Ghost mutating `process.env.NODE_ENV`.

I'd like to suggest that something like this be done instead:

```js
// stage.js
module.exports = process.env.NODE_ENV || "development";
```

Then anywhere that needs to know the current env would just do

```js
var stage = require('./stage');
```

This way, consumers of Ghost don't get weird side effects.

**Comment by ErisDS** [comment]
By all means send a PR, but please, just call it `env` or `node-env`. Stage is confusing IMO.

**Comment by bioball** [comment]
Ok, sure thing. I can send over a PR for this.

**Comment by emars** [comment]
Isn't the only instance of NODE_ENV mutation in core/index.js?

That appears to use: `process.env.NODE_ENV || "development";`

**Comment by ErisDS** [comment]
@emars yes, that's the only place that mutates the `process.env.NODE_ENV` property - we do it just once.

But if you change this to export a module, everywhere which checks `process.env.NODE_ENV` (of which there are many) would also need to be updated to check the new module.

**Comment by bioball** [comment]
Sorry for the delay on the PR. I'll submit one soon.

**Comment by emars** [comment]
I was looking into this issue it I found that ~20 or so tests end up failing when I refactored to use the module because they depend on the fact that NODE_ENV changes throughout the test. 

Is this a good workaround?

```js
// env.js
module.exports = function() {
    return process.env.NODE_ENV || "development";
}
```
