### ISSUE TITLE
Static Page doesn't pass fb opengraph validators and twitter card validators

### ISSUE THREAD

**Issue by vasinl124** [TryGhost/Ghost#6632]
It works with a regular post which just grab my post's cover image when I share it on facebook or twitter

but if I turn it to a static page. I got errors both from facebook debugger and twitter card validator

> Warnings That Should Be Fixed
Inferred Property    The 'og:url' property should be explicitly provided, even if a value can be inferred from other tags.
Inferred Property    The 'og:title' property should be explicitly provided, even if a value can be inferred from other tags.
Inferred Property    The 'og:description' property should be explicitly provided, even if a value can be inferred from other tags.
Inferred Property    The 'og:image' property should be explicitly provided, even if a value can be inferred from other tags.

this is from the facebook debugger
and this from Twitter card validator 

> The card for your website will look a little something like this!
Unable to render Card preview
Log
INFO:  Page fetched successfully
INFO:  14 metatags were found
WARN:  Not whitelisted

**Comment by ErisDS** [comment]
Hi @vasinl124,

Thanks for taking the time to raise this. We are aware of the issue - it's being tracked in #6534.
Not sure anyone is working on that particular task at the moment, so it's free to pick up.
