### ISSUE TITLE
Remove Select-All on Click for the PSM Slug Input

### ISSUE THREAD

**Issue by dbalders** [TryGhost/Ghost#6655]
### Issue Summary

Currently when clicking in the slug input field in the post settings menu, it will automatically select the entire input. This causes problems when trying to select parts or make edits in the middle. This select all feature should be removed entirely.

[Slack Conversation](https://ghost.slack.com/archives/dev/p1459262331000731)

**Comment by acburdine** [comment]
closed by #6812
