### ISSUE TITLE
Save draft post after editing title

### ISSUE THREAD

**Issue by kevinansfield** [TryGhost/Ghost#6656]
refs #6631, #5062 

If a post is in the `draft` state, we should save the post when the title input loses focus and the title has changed.

- saving will run through the code added in #6631 which will then auto-update the slug in the PSM because the new slug is returned from the server
- the title input will now more closely match the slug input saving behaviour

[Slack discussion](https://ghost.slack.com/archives/dev/p1459264724000761)

**Comment by eddieduro** [comment]
I am a beginner to contributing to open source projects but I would definitely like to try and tackle this!

**Comment by kevinansfield** [comment]
@eddieduro :+1: go for it! :smile: If you get stuck or want to talk through the process we're always happy to help over in the #dev channel on our [slack team](https://ghost.org/slack)

**Comment by eddieduro** [comment]
@kevinansfield Okay awesome, thank you! :+1:
