### ISSUE TITLE
Upgrade to Node 6.x LTS

### ISSUE THREAD

**Issue by tomByrer** [TryGhost/Ghost#6662]
https://github.com/nodejs/LTS#lts_schedule
You have only 6 months left of support from Node for 0.10; weighs in heavy for consideration for any new projects I want to base on Ghost.  Besides cutoff date, I'd prefer to use ES2016/7 natively.  I'd recommend using the [node v6 beta (near bottom)](https://nodejs.org/download/nightly/) to refactor; should be released in a month anyhow.

I know it won't be a simple switch, but figured others would be wondering also :)
TIA

**Comment by jaswilli** [comment]
Hi @tomByrer,

node 4 LTS is already supported, so there's no need to use v0.10. 

I'd imagine there won't be any rewriting of server code using ES6 features until all supported versions of node have language feature parity.

**Comment by tomByrer** [comment]
OK ty; I didn't find the link to [supported node versions](http://support.ghost.org/supported-node-versions/).
