### ISSUE TITLE
Get the current post URL inside the view

### ISSUE THREAD

**Issue by fmmsilva** [TryGhost/Ghost#6664]
It would be nice if we have some util variables like that exposed to the view

**Comment by acburdine** [comment]
Hey @fmmsilva!

I think you should be able to figure out the post url by using some JavaScript window.location/origin/etc. manipulation.

Also, the Github issue tracker is for issues with the software itself. We have a [wishlist](http://ideas.ghost.org) where you can submit your ideas :smile:

**Comment by fmmsilva** [comment]
No way to get it server-side?

**Comment by acburdine** [comment]
You _can_ get it server side, but that isn't the point. I'm saying you should be able to get it without having to modify the Ghost server to expose it as a theme variable. :smile: 

The reason I mentioned the wishlist is that's how we determine what features to work on in Ghost. If there's enough people that want these kind of utils, then we can build them.

**Comment by jaswilli** [comment]
The URL is available by way of the `{{url}}` helper.

**Comment by fmmsilva** [comment]
Thanks! @jaswilli 
That's what i've been looking for!!
