### ISSUE TITLE
Sitemap is not generating

### ISSUE THREAD

**Issue by evanmrose** [TryGhost/Ghost#6675]
### Issue Summary

My sitemap isn't being generated properly. Nothing shows up and google seems to think it is serving HTML not XML.

### Steps to Reproduce

See sitemap here--> [RD Sitemap](http://blog.rosedigital.co/sitemap.xml)

### Technical details:

* Ghost Version: 0.7.2
* Node Version: 4.3.2
* Browser/OS: Mac, Chrome
* Database: sqlite3

**Comment by kevinansfield** [comment]
Hey @evanmrose, you need to configure your site's URL in `config.js`, other than that it looks as though the sitemap is working correctly.

Github is used for tracking issues and feature development, if you need further support we have a [community slack channel](http://slack.ghost.org).
