### ISSUE TITLE
Empty href on editor preview-pane link

### ISSUE THREAD

**Issue by JohnONolan** [TryGhost/Ghost#6681]
![image](https://cloud.githubusercontent.com/assets/120485/14338029/25c85506-fc28-11e5-9138-36c4ea451811.png)

The word "preview" here is supposed to link to the post preview - but seems to just have an empty href.

Discovered on latest Ghost via Ghost(Pro) / Latest Chrome, Mac

**Comment by acburdine** [comment]
Fixed on master by #6624
