### ISSUE TITLE
images doesn't get deleted

### ISSUE THREAD

**Issue by miyurusankalpa** [TryGhost/Ghost#6692]
### Issue Summary

When I upload an image and delete, it doesn't get deleted from the server. When I check the server,  old images I deleted are still on the server.

### Steps to Reproduce

1. add an image to the post (upload one) 
2. remove the image using the 🗑 icon

### Technical details:

* Ghost Version: 0.7.8 
* Node Version: v0.10.25
* Browser/OS: Win10; Linux
* Database: sqlite3

**Comment by ErisDS** [comment]
Hi @miyurusankalpa, this is expected behaviour. If you want to delete an image you should do so manually. This is also covered in  #5052 and #4311.
