### ISSUE TITLE
Caching Blogs and Tags in Memory

### ISSUE THREAD

**Issue by ramandhingra** [TryGhost/Ghost#6698]
Does Ghost support caching blogs, tags, and other things for fast retrieval? If not, I'd like to request the team to add this feature.

**Comment by acburdine** [comment]
@ramandhingra with the exception of settings, there's no explicit caching, but there is a fair amount of optimization that goes on regarding that. In my opinion, Ghost does enough for speed that implementing any additional caching is somewhat overkill.

However, there is the [wishlist](http://ideas.ghost.org) where you can submit your caching idea if you so choose. Again though, ghost does optimize a fair amount.
