### ISSUE TITLE
Slug Uniqueness Error: Can't invite/create both users having the ids abc@gmail.com and abc@hotmail.com respectively

### ISSUE THREAD

**Issue by ramandhingra** [TryGhost/Ghost#6699]
The system created a user successfully having the id: abc@hotmail.com. But when it tried to create another user by the same email user name (abc) at a different domain (gmail.com), i.e. abc@gmail.com the following error is reported.

ERROR: insert into `users` (`accessibility`, `bio`, ...) values (NULL, NULL, NULL, '2016-04-01 15:38:23.989', 1, 'abc@gmail.com', NULL, 'en_US', NULL, NULL, NULL, 'abc', ...) - 
ER_DUP_ENTRY: Duplicate entry 'abc' for key 'users_slug_unique' 

This happened when I tried to invite two users having these two email ids: abc@gmail.com and abc@hotmail.com

Probably, the answer is to generate the slugs like this: abc1, abc2, and so on

**Comment by ErisDS** [comment]
Hi @ramandhingra can you please update this to include full reproduction steps, version & env information as per the issue template? I haven't been able to reproduce this by inviting two users as you suggested.

Ghost already does produce incremental slugs, and as far as I can tell that behaviour is working as expected when inviting people.

**Comment by ErisDS** [comment]
@ramandhingra as far as I can tell from testing, this issue is not present in the current version of Ghost. I'm going to close this for now, but will reopen if further information is provided showing how to reproduce it.
