### ISSUE TITLE
Unable 'npm start' locally 

### ISSUE THREAD

**Issue by alvaraj2** [TryGhost/Ghost#6707]
I have searched for a couple hours and just cant get around this issue. The server always returns this message with exit status 237. I Tried searching the troubleshooting page of Ghost as well and just cant seem to run it. I am using windows 7:

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@1.4.28
3 info using node@v0.10.40
4 verbose node symlink C:\Program Files\nodejs\\node.exe
5 verbose run-script [ 'prestart', 'start', 'poststart' ]
6 info prestart ghost@0.7.8
7 info start ghost@0.7.8
8 verbose unsafe-perm in lifecycle true
9 info ghost@0.7.8 Failed to exec start script
10 error ghost@0.7.8 start: `node index`
10 error Exit status 237
11 error Failed at the ghost@0.7.8 start script.
11 error This is most likely a problem with the ghost package,
11 error not with npm itself.
11 error Tell the author that this fails on your system:
11 error     node index
11 error You can get their info via:
11 error     npm owner ls ghost
11 error There is likely additional logging output above.
12 error System Windows_NT 6.1.7601
13 error command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
14 error cwd C:\Users\Jesse\Desktop\www\ghost.com
15 error node -v v0.10.40
16 error npm -v 1.4.28
17 error code ELIFECYCLE
18 verbose exit [ 1, true ]

**Comment by ErisDS** [comment]
Hi @alvaraj2, sorry to hear you're having trouble. As mentioned in the readme & contrib guide, if you have questions about Ghost or need help, please head on over to slack - https://ghost.org/slack/ - and post in the #help channel. There you can get help & support from the Ghost community, which we're not able to do here in the GitHub bug tracker.
