### ISSUE TITLE
Ghost 0.7.9 on Nodejs 4.4.3

### ISSUE THREAD

**Issue by loskiq** [TryGhost/Ghost#6723]
> 0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@2.15.1
3 info using node@v4.4.3
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart ghost@0.7.9
6 info start ghost@0.7.9
7 verbose unsafe-perm in lifecycle true
8 info ghost@0.7.9 Failed to exec start script
9 verbose stack Error: ghost@0.7.9 start: `node index`
9 verbose stack Exit status 255
9 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:217:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:827:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid ghost@0.7.9
11 verbose cwd /opt/ghost1
12 error Linux 4.2.0-35-generic
13 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
14 error node v4.4.3
15 error npm  v2.15.1
16 error code ELIFECYCLE
17 error ghost@0.7.9 start: `node index`
17 error Exit status 255
18 error Failed at the ghost@0.7.9 start script 'node index'.
18 error This is most likely a problem with the ghost package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     node index
18 error You can get information on how to open an issue for this project with:
18 error     npm bugs ghost
18 error Or if that isn't available, you can get their info via:
18 error
18 error     npm owner ls ghost
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]

Why?

**Comment by acburdine** [comment]
@loskiq If you're still having trouble with this, head on over to our [Slack](https://ghost.org/slack) channel :smile:
