### ISSUE TITLE
JSHint doesn't actually know javascript.

### ISSUE THREAD

**Issue by GusCaplan** [TryGhost/Ghost#6730]
These are just a few examples of the sloppy work that JShint is doing. It doesn't seem to understand things like variables being declared in for loops are NOT already defined, and I don't even know why i++ is unexpected. JSHint is good at yelling about how many spaces after a comment, but it seems to lack a proper backend. I suggest you change your linter.

`for (var i = 0; i < periods.length; i++) {`
` ----------------^ [W004] 'i' is already defined.`
     `17 |    for (var i = 0; i < periods.length; i++) {`
`------------------------------------------^ [W016] Unexpected use of '++'.`

**Comment by ErisDS** [comment]
These things are standard across our projects and have been for a long time. They're not up for discussion.

If you need help with developing for Ghost, then please come and chat to use in the #dev channel in [slack](https://ghost.org/slack).
