### ISSUE TITLE
Stop recommending node 0.10

### ISSUE THREAD

**Issue by feross** [TryGhost/Ghost#6731]
Hey there!

I just noticed this in your readme:

```
# Node v0.10.x - recommended
# Node v0.12.x and v4.2+ LTS - supported
```

Just a suggestion: You might want to stop recommending 0.10 and 0.12 because those are going to be completely unsupported by the end of the year. That includes security updates.

**Comment by sebgie** [comment]
Hey @feross!

We have a more elaborate explanation of supported versions on http://support.ghost.org/supported-node-versions/. The change to a new recommended version will happen in the near future and definitely before Oct 2016 ;-).

Closing as this is already in progress.

**Comment by feross** [comment]
Sounds good.
