### ISSUE TITLE
Short URLs with a distinctive sequential number

### ISSUE THREAD

**Issue by JanSichula** [TryGhost/Ghost#6736]
Hello,

I am not entirely sure whether this is right place to ask, but I have a question (or feature proposal) whether it is possible in Ghost to achieve a URL behavior as for example implemented on qz.com, where there is a unique sequential number before a URL slug and the same content can be reached simply by number in URL path as with full URL. This is great as it eliminates any need to URL shortening services while keeping the branding intact. Just try it at URL bellow to experience what I mean.

http://qz.com/663944/dramatic-drone-footage-of-earthquake-damage-on-japans-kyushu-island/
http://qz.com/663944/

Besides channels, this is something I would love to see implemented in Ghost if it is not yet there.

**Comment by ErisDS** [comment]
Hi @JanSichula, 

To request a feature for Ghost you can add your idea (or vote on a similar one) over on our [wishlist](http://ideas.ghost.org). We use this list to help determine what goes into the roadmap and how to prioritise features. You can also access the wishlist any time from inside the Ghost admin:
![](http://puu.sh/jXKwm.png)
