### ISSUE TITLE
client_trusted_domains and authenticated requests

### ISSUE THREAD

**Issue by jaswilli** [TryGhost/Ghost#6740]
As it stands now I don't think authenticated requests (i.e., requests containing an `Authorization: Bearer xxx`) header will get `client_trusted_domains` attached to them.

Need to verify and if true rework where `trustedDomains` gets attached to the request object.

**Comment by ErisDS** [comment]
I'm closing all OAuth and most API issues temporarily with the `later` label. 

RE: OAuth, for the next 2-3 months we'll be implementing an official Ghost OAuth login system, providing global access to all Ghost blogs with a single login. We'll be opening issues around this system soon, and I don't want to cause confusion with OAuth for the API.

JSON API Overhaul & OAuth access are currently scheduled next on the [roadmap](https://trello.com/b/EceUgtCL/ghost-roadmap)
