### ISSUE TITLE
Image preview does not show when spaces are after ![]

### ISSUE THREAD

**Issue by Tyriar** [TryGhost/Ghost#6743]
### Steps to Reproduce

Type into editor `![]` Including the trailing space:

![image](https://cloud.githubusercontent.com/assets/2193314/14699277/5ceb5000-074b-11e6-8d05-2726e1941fbc.png)
### Technical details:
- Ghost Version: master
- Node Version: v4.2.0
- Browser/OS: Chrome

**Comment by kevinansfield** [comment]
Closed via https://github.com/TryGhost/Ghost-Admin/pull/682 and https://github.com/TryGhost/Ghost-Admin/pull/685 - there is no longer a preview shown, instead uploads are achievable via drag-n-drop or clicking the Image toolbar button
