### ISSUE TITLE
Sensitive data (smtp password) in config file.

### ISSUE THREAD

**Issue by marcinant** [TryGhost/Ghost#6750]
### Issue Summary

Ghost stores sensitive data in config file.

I would like to configure email account to use with Ghost instance. I got it up and working however I have to keep my password to smtp server in config file as open text.

### Steps to Reproduce

1. see 'config.example.js'
2. mail -> options -> auth -> pass

This is plain wrong. Ghost should allow to keep such data in safe place such as external file (.netrc, .authinfo) and support encryption or use sysem wide password managers such as 'seahorse' on linux.

### Technical details:

* Ghost Version: 0.7.5
* Node Version: 4.2.0
* Browser/OS: any
* Database: sqlite

**Comment by jaswilli** [comment]
`config.js` should be protected via appropriate filesystem permissions, just like private key files, or the auth-related files you mentioned above.

If storing smtp credentials in `config.js` directly doesn't work for you, you're free to pull it in via an environment variable.

**Comment by marcinant** [comment]
1. I got development environment to develop themes. I use ghost as NPM module in a way similar to what's described here https://github.com/TryGhost/Ghost/wiki/Using-Ghost-as-an-npm-module

So, my theme is just a git repository and it contains gulpfile.js and predefined Ghost config.
With current solution I cannot share this config with my coworkers as I don't want to publish my email password. I still think that password should be external.

2. Password in environment variable? This is pretty interesting case for all security specialist. However I cannot see any documentation for such solution. Could you be more elaborate on this topic?

Anyway I see you colosed this issue while it's not resolved in any way. Are you going to ignore this problem?

**Comment by jaswilli** [comment]
> So, my theme is just a git repository and it contains gulpfile.js and predefined Ghost config.
> With current solution I cannot share this config with my coworkers as I don't want to publish my email password. I still think that password should be external.

That's not a problem with Ghost, it's a problem with your workflow.

> Password in environment variable? This is pretty interesting case for all security specialist. However I cannot see any documentation for such solution. Could you be more elaborate on this topic?

Sure. `config.js` is a javascript file that gets pulled into your Ghost instead via node's `require` command. When that happens everything in the file is evaluated, so in `config.js` you can replace `pass: <your password>` with `pass: process.env.SMTP_PASSWORD` (or whatever variable name you choose), and then Ghost will pull that value from the environment variable at runtime.

So either `export set SMTP_PASSWORD=mypassword` or `SMTP_PASSWORD=mypassword npm start` will work.

> Are you going to ignore this problem?

It's not really a problem. Certainly configuration values could be handled differently but much like you shouldn't make your database publicly available you shouldn't make your `config.js` file available to others either.

**Comment by marcinant** [comment]
1.This is a problem with Ghost as it also affects all self hosted instances of Ghost.
Email is required to manage users. As there is no way to manage users without email, it's more problem with Ghost workflow than with mine.

2. Storing passwords as env variable is dangerous. For me it's not a solution. It's workaround. It's also undocumented. You should provide this information to users. They should know they have an alternative.

3. Password to email account is very sensitive. It's safe to make 'config.js' available to others (developers, server users) as long as it doesn't contain password to smtp server.

**Comment by jloh** [comment]
You shouldn't be using your own email account (IMO) for this purpose anyway. You should have a dedicated account using something like (mailgun)[https://www.mailgun.com/].

To get around the other issue of exposing the password, most providers allow app specific passwords and allow you to also lock it down to certain IP addresses. If it does get exposed, chances are people won't be able to use it if you lock it down.

Remember, ghost is opensource, if you want to change something you can always submit a pull request with some code!
