### ISSUE TITLE
Upgraded ghost to 0.7.8 > 0.7.9: Failed to lookup view "default" in views directory

### ISSUE THREAD

**Issue by anyong** [TryGhost/Ghost#6755]
I'm hooking ghost into an existing express app at `/blog`, and this has always worked fine even with node 5 (I have a fork that simply removes the semver check because of the installation issue). I recently rebased to master and after installing ghost 0.7.9 I am now getting this error when I try to load the admin page:

```
Error: Failed to lookup view "default" in views directory "d:\dev\node_modules\ghost\core\server\views\"
    at EventEmitter.render (d:\dev\node_modules\express\lib\application.js:579:17)
    at ServerResponse.render (d:\dev\node_modules\express\lib\response.js:961:7)
    at renderIndex (d:\dev\node_modules\ghost\core\server\controllers\admin.js:29:21)
```

The blog itself works fine, but I'm very confused because indeed there is no file named `default.hbs` in `core/server/views`. Any ideas?

**Comment by ErisDS** [comment]
Hi @anyong, sorry to hear you're having trouble. I've seen you have also posted in the #help channel on [our slack team](https://ghost.org/slack/) - that's the correct place to get support from our community so closing this.

**Comment by khalidhoffman** [comment]
For anyone coming across this issue, I believe the solution is to run `grunt init`.
