### ISSUE TITLE
Remove cwd from .bowerrc

### ISSUE THREAD

**Issue by ksketo** [TryGhost/Ghost#6761]
### Issue Summary

When trying to do bower install inside a theme folder I get the error: 
`bower ENOENT        No bower.json present`

I found the answer here https://github.com/bower/bower/issues/1849#issuecomment-150714620 , which describes how bower concatenates the config files and results in that error. Removing cwd from the .bowerrc in the ghost root directory, fixes the error. 

Also, according to the description https://github.com/bower/spec/blob/master/config.md#cwd , cwd should be used only via programmatic API or CLI arguments, so I think it should be removed from the .bowerrc in the ghost root directory.

Seems that this issue appeared since Bower 1.4 release.

### Technical details:

* Ghost Version: 0.7.4
* Node Version: v0.12.13
* Bower Version: 1.7.9
* OS: OS X El Capitan 10.11.4

**Comment by ErisDS** [comment]
This was closed by #6882 / 30b3ccc
