### ISSUE TITLE
Install ghost via npm for node 6

### ISSUE THREAD

**Issue by anyong** [TryGhost/Ghost#6763]
Just leaving this here in case anyone else is interested and doesn't want to go through the whole rigmarole I just did, because ghost seems to work quite fine on node version 6.

- [fork](https://github.com/anyong/Ghost)
- [npm](https://www.npmjs.com/package/ghost-node6)

**Steps:**

1. `npm install ghost-node6` (removed version check entirely, no need for flags or environment variables, installs fine with npm 3.x)
2. Replace any `require('ghost')` with `require('ghost-node6')`
3. Done.

**Warnings:**

This is not "officially supported", I just made it because I use ghost as middleware in an express app that I'm working on upgrading to node v6 and ghost was a stumbling block in that process.

(Feel free to close this issue or leave it open or whatever - I just assume people will start Googling for "ghost node 6" pretty soon so this is an option for people who want to do that.)

**Comment by ErisDS** [comment]
I strongly recommend reforking / publishing from the stable branch. In its current state this fork should not be used for a production blog as it is forked from master and does not represent a complete or stable version of Ghost.

Specifically the fork from master has happened half way through a database upgrade which means you will have to run extra commands or perhaps even update the database manually in order to upgrade again.

**Comment by anyong** [comment]
Ah the npm published build is from stable not master, so it should be fine.
On Apr 28, 2016 9:13 AM, "Hannah Wolfe" <notifications@github.com> wrote:

I strongly recommend reforking / publishing from the stable branch. In its
current state this fork should not be used for a production blog as it is
forked from master and does not represent a complete or stable version of
Ghost.

Specifically the fork from master has happened half way through a database
upgrade which means you will have to run extra commands or perhaps even
update the database manually in order to upgrade again.

—
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub
<https://github.com/TryGhost/Ghost/issues/6763#issuecomment-215278937>

**Comment by ErisDS** [comment]
@anyong Afraid not - all of the commits you added were to the [master branch](https://github.com/anyong/Ghost/commits/master) and you even added a commit [removing the warning](https://github.com/anyong/Ghost/commit/7756a8d44abf3bb121d2f9707aa357a4c718908c) which explained you were on the wrong branch 😨

The code you get when installing this module is definitely > 0.7.9 as evidenced by the fact that validator is at 5.2.0, which only happened [last week](https://github.com/TryGhost/Ghost/commit/e21640a7e5fe1ccbc02e0c332596ec5bb1f5ebcc):
![](http://puu.sh/oyxNh.png)

I'm going to remove this advice from GitHub for the exact same reason you stated in your post. 

Anyone googling using Node 6 with Ghost needs to read our [supported node version guide](http://support.ghost.org/supported-node-versions/) to understand that we will support v6 once it goes into LTS. It is also worth reading the open issue about [the bug in npm v3](https://github.com/TryGhost/Ghost/issues/6691) which is causing the problem with the install process that you ran into.

**Comment by anyong** [comment]
Uh oh. Thought I had built/pushed the stable branch yesterday but I guess not.

Anyway I rebuilt and republished from stable, and replaced the readme with a [warning](https://github.com/anyong/Ghost).
