### ISSUE TITLE
manifest.json files are blocked on server

### ISSUE THREAD

**Issue by marcinant** [TryGhost/Ghost#6769]
### Issue Summary

Chrome supports extension in JSON format.

Described [here](https://developer.chrome.com/extensions/manifest)

I created such file and added to theme. Unfortunately this file is not hosted. Returns 404.

### Steps to Reproduce

1. Create manifest.json in theme root
2. Update theme and reload. See 404 in inspector.

manifest.json should be supported by Ghost as part of theme or generated dynamically by Ghost.

**Comment by ErisDS** [comment]
@marcinant Can you explain the use-case for needing a manifest.json in a theme? We require the inclusion of a package.json file in order to specify data that Ghost needs and this file definitely should not be served, hence the block on *.json files.

**Comment by marcinant** [comment]
It's well documented [here](https://developers.google.com/web/fundamentals/getting-started/push-notifications/step-05?hl=en) and [here](https://developer.chrome.com/webstore/get_started_simple).

*manifest.json* replaces some `link` and `meta` items in html head to deliver application icon on Android devices. If your blog has *manifest.json* file with icon and short name then you can click on **"add to homescreen"** and you get shortcut there with your **custom** icon. You can also use manifest.json to more advanced things such as notifications about new articles or finally it's required to use with serviceworkers (to make your blog available offline).

**Comment by marcinant** [comment]
See also [w3c working draft](https://www.w3.org/TR/appmanifest/)

With *manifest.json* you make Ghost more mobile friendly.

**Comment by jaswilli** [comment]
I don't have an Android device to verify this but it seems as though you should be able to reference your manifest file by an arbitrary name, e.g., `<link rel="manifest" href="manifest.webmanifest">`.

**Comment by sakulstra** [comment]
@marcinant: did you find a working solution?

**Comment by marcinant** [comment]
@sakulstra Nope. I'm not Ghost developer. So, as long as it's blocked I don't see any good workaround.

**Comment by jloh** [comment]
@marcinant @sakulstra manifests can be loaded from separate domains. There isn't a reason you can't host the manifest file off-site somewhere else outside of Ghost.

**Comment by krokofant** [comment]
I'm used to the npm module of Ghost in which I think it would pretty easy to add the manifest at the desired route.

**Comment by krokofant** [comment]
Something like:
```
var ghost = require('ghost'),
    express = require('express'),
    parentApp = express(),
    path = require('path');

parentApp.get('/manifest.json', function(req, res, next) {
  res.send("serve manifest");
});

ghost({
  config: path.join(__dirname, 'config.js')
}).then(function (ghostServer) {
    parentApp.use(ghostServer.config.paths.subdir, ghostServer.rootApp);

    ghostServer.start(parentApp);
});
```

Just need to be tweaked to load the manifest file for the desired location

**Comment by sakulstra** [comment]
Would be nicer if could make it somehow dynamic and bundle it with a theme. So we could have a native "add to homescreen" popover. I'll wait till apps are a bit more advanced and give it another try then.

**Comment by ErisDS** [comment]
The code which implements the blacklist is here: https://github.com/TryGhost/Ghost/blob/f14910fa8e1520b39d88d62977c38b9ac6530be4/core/server/middleware/static-theme.js#L7-L7

It works based on file extension. Whilst it makes sense to serve a `manifest.json` from the theme root, no other `.json` file can be considered safe to serve. Therefore we cannot remove `.json` from the blacklist.

However, it should be pretty straightforward to add a whitelist to cover `manifest.json` and allow this whilst still not allowing any other `.json` file.

I would be interested to hear from anyone who thinks this is a bad idea though.

**Comment by sakulstra** [comment]
So it could be as easy as(not yet tested):
```js

function isBlackListedFileType(file) {
    var blackListedFileTypes = ['.hbs', '.md', '.json'],
        ext = path.extname(file);
    return _.includes(blackListedFileTypes, ext);
}

function isWhiteListedFile(file){
    var whiteListedFiles = ['manifest.json'];
    return _.includes(whiteListedFiles, path.basename(file));
}

function forwardToExpressStatic(req, res, next) {
    if (!req.app.get('activeTheme')) {
        next();
    } else {
        express.static(
            path.join(config.paths.themePath, req.app.get('activeTheme')),
            {maxAge: utils.ONE_YEAR_MS}
        )(req, res, next);
    }
}

function staticTheme() {
    return function blackListStatic(req, res, next) {
        if (!isWhiteListedFile(req.path) && isBlackListedFileType(req.path)) {
            return next();
        }
        return forwardToExpressStatic(req, res, next);
    };
}
```
If there's no objection I'll add some tests and do a pr the coming days.

**Comment by ErisDS** [comment]
Yeah that looks like the right approach to me 👍
