### ISSUE TITLE
Bug: Editor not always loading!

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#6779]
This has happened to me twice recently, although I'm switching branches a lot and it could be that something isn't built correctly in the process.

I've seen it on both a new editor and opening an existing post:

![](http://puu.sh/oC8E2.png)

I believe that the xregexp dependency was dropped in favour of our own regular expression, and this is probably related to that.

**Comment by kevinansfield** [comment]
Interesting, definitely seems to be related to the regexp that we pulled out of XRegExp, although quite why it only fails occasionally. I've not seen it yet but will keep an eye out for it.

**Comment by ErisDS** [comment]
Yeah I need to keep an eye on when it is happening - E.g. if I've properly built all the things. I just wanted to get it raised to flag it up for now.

**Comment by ErisDS** [comment]
Going to close this in favour of the user reports in #6914
