### ISSUE TITLE
Ghost is dead as a solution! (not supported)

### ISSUE THREAD

**Issue by MariasStory** [TryGhost/Ghost#6782]
I don't understand the point of maintaining a project if you cannot use it!

There is no easy way for users to install ghost through npm. I used it for some time now. It was a reasonable solution until I decided to update it. Now I am busy solving problems!
Is it so complicated to maintain a solution? I am not asking too much am I?

Why in the world do you need sqlite3@3.0.5?
(npm ERR! sqlite3@3.0.5 install: `node-pre-gyp install --fallback-to-build`)

I can easily install sqlite3@3.1.3, is there a problem with this one?

Can someone simply remove unneeded stuff and make this relatively simple solution work?

PS: It is not about amount of commits, more about their quality!

**Comment by ErisDS** [comment]
Please read this https://ghost.org/about/guidelines before posting here again.

**Comment by MariasStory** [comment]
Now I know why there is not much going on in this repository. It seems like ErisDS is busy closing issues instead of solving the problems :-)

If you have a problem, better ask for help instead of pointing me to your "Guidelines".
