### ISSUE TITLE
in-content shortcodes

### ISSUE THREAD

**Issue by stevenvachon** [TryGhost/Ghost#6785]
... like in WordPress:
```
Welcome to my [shortcode]. It will [shortcode attr="value"]do some stuff[/shortcode].
```
Does Ghost currently support this feature? If not, we definitely need it, especially with interesting things like [shortcake](https://github.com/wp-shortcake/shortcake)

**Comment by ErisDS** [comment]
Hi there @stevenvachon, Ghost does not support shortcodes and we will not be adding support, very sorry.

**Comment by stevenvachon** [comment]
What's the reason?

**Comment by ErisDS** [comment]
Google "WordPress shortcode problem" - it is a nightmare feature that causes constant compatibility issues. There's no built-in consideration for importing/exporting content, or what happens if the plugin that adds the shortcode stops being maintained. 

The same thing can easily be achieved by installing something like [textexpander](https://textexpander.com/), but without impacting on your data.

**Comment by stevenvachon** [comment]
What if Ghost shortcodes were mustache/handlebars syntax? They wouldn't look like [sic], making it easier to search for them in a migration.

**Comment by ErisDS** [comment]
Changing the syntax really doesn't solve any of the underlying problems I described. As I said, textexpander solves the same problem without affecting your data. Editor extensions are something on our radar, but they will be taking a different form. Shortcodes are categorically not something we're going to add, sorry again.

**Comment by stevenvachon** [comment]
TextExpander is just local snippets and not dynamic on the server.

**Comment by stevenvachon** [comment]
Perhaps shortcodes/helpers could be a plugin created. Is the plugin API going to be v0.8?

**Comment by ErisDS** [comment]
No, there's not going to be a plugin API for the editor any time soon - again, all the same problems apply. 

If this is the killer feature for you, then Ghost is not the tool for the job.
