### ISSUE TITLE
Sticky invalid state for Twitter/Facebook inputs

### ISSUE THREAD

**Issue by kevinansfield** [TryGhost/Ghost#6826]
### Issue Summary

The "invalid" state of the twitter/facebook inputs is sticky if a valid URL is entered which doesn't need the auto-rewrite

### Steps to Reproduce

1. Visit the settings page
2. Enter `https://twitter.com/testing` into the Facebook input
3. Click out of the input, you should see an error message
4. Click back into the input and change the text to `https://www.facebook.com/testing`
5. Click out of the input, you'll still see the error message even though it's a valid URL

The bug only appears if the value entered in step 4 exactly matches the URL format that we expect, if the value needs re-writing in any way then the validation passes.

This occurs for the Twitter and Facebook inputs on both the Settings and Team/User pages.

**Comment by acburdine** [comment]
#6647 should be a long term solution for this.
