### ISSUE TITLE
How the heck do I turn preview content off in the editor?

### ISSUE THREAD

**Issue by IAlwaysBeCoding** [TryGhost/Ghost#6833]
Basically, ghost is becoming super slow on my browser when editing posts that are long(1000 words or more). I can't even type anymore because the preview part of the post is making my browser slow, I don't understand how a simple feature such as turn on/off the **preview** content can't be inside ghost.

How am I supposed to write long posts when my browser can't handle it. Did I miss the setting of how to turn it off, because I looked everywhere and I can't turn the preview off on the editor. It is so annoying because it is making me go back to a simple static site generator to write my blog If I can't find a way to turn that feature off.

**Comment by acburdine** [comment]
@IAlwaysBeCoding sorry to hear you're having trouble! Ghost version 0.8.0 (which will be released in a couple of days) contains a number of bugfixes related to the editor preview performance, which should help a decent amount with your issue 😄 

If it's still a problem after that, this can be re-opened or re-formatted to be a proper issue.

**Comment by IAlwaysBeCoding** [comment]
@acburdine  Perfect then, I will wait for Ghost version 0.8.0 . Really great news, and thanks for the quick reply.Keep up the good work guys!
