### ISSUE TITLE
Canonical URL is always http

### ISSUE THREAD

**Issue by gps13** [TryGhost/Ghost#6844]
hi to all...

Just changed my site from http to https. I noticed that the Canonical url is always http. I though that was fixed. no?

**Comment by acburdine** [comment]
I haven't tried to reproduce this locally yet, but from a look at the relevant code it appears that this shouldn't happen. Have you tried restarting your Ghost blog after you changed to https?

**Comment by ErisDS** [comment]
The `url` field in config.js is how you control what Ghost uses as the "external" url, i.e. the URL that points to your blog. Whatever that is set to is therefore what's used for the canonical url, any other urls output in the head e.g schema urls, the urls used in the RSS feed and in the emails sent out. 

You need to make sure that you have set the url in the correct section of the config.js file (development or production) and then restart Ghost. Once you've restarted, refreshing the page will result in the canonical URL updating, unless you have either 1) configured the wrong url or 2) got a cache in front of your blog which is serving you old content.

Hopefully this helps. I'm very certain there is no bug here so going to close this issue, will reopen if we find out something different 👍

**Comment by gps13** [comment]
@ErisDS Thank you :100:  ! My bad that I missed it!
@acburdine thanks for your input (I tried that :+1: )

**Comment by abhay803** [comment]
Hi guys,

Can anyone help me on how to control the canonical url in my blog site with ghost config ?
I want it to be https all the time now it is http...
Help

**Comment by gargol** [comment]
@abhay803 would suggest posting on https://forum.ghost.org/ for 'help' kind of questions :smiley: Ghost team is trying to keep Github issues for bug tracking mostly.
