### ISSUE TITLE
"Last seen" date for active users on the team page is misleading

### ISSUE THREAD

**Issue by shawntoffel** [TryGhost/Ghost#6845]
### Issue Summary

The "Last seen" date on the team page is based on the lastLogin user field. This field is only updated when the credentials are checked. If the user's auth is stored in session wont the "Last seen" date technically contain stale data? A user could potentially remain signed in for several days without the "Last seen" date ever updating. I think the "Last seen" date should be based on a different/new field, or "Last seen" should be re-labeled to more accurately represent the data it displays. 

### Steps to Reproduce

1. Login and go to /ghost/team. Note the "Last seen" date.
2. Maintaining the same session, return to /ghost/team at a later date. Note that the "Last seen" date is unchanged. 

### Technical details:

* Ghost Version: 0.7.9
* Node Version: 0.10.29
* Browser/OS: Chrome/Windows
* Database: mysql

**Comment by ErisDS** [comment]
@shawntoffel thanks for the bug report, we used to have a 1 day session length, so this was pretty accurate, but now that we've increased the session length you're spot on that the "last seen date" is no longer a good reflection of reality.

We need to find a new way to update this, which keeps the balance of not updating the user model too frequently (because it's just not that useful at the moment) but also accurately reflects that the user has been online. 

Perhaps token refreshes (which happen once per hour, I believe) would be a good option?

**Comment by nuclearpengy** [comment]
Not sure how to approach it technically but what about if as long as the user is logged in and has admin open in a tab, the site considers the user as "being seen".

**Comment by shawntoffel** [comment]
Okay. So I think the first step is to define one or more scenarios in which the last seen date will be updated. 

I can think of a few different approaches:

1. The obvious and expensive _update on every action_. This provides to most accurate results, however since the data isn’t particularly important the cost isn’t necessarily justified. 
2. Update on specific actions. We define a set of relatively infrequent yet unavoidable actions that count towards user activity. This seems like a good balance between accuracy and write-frequency. The caveat here is that actions will need to be carefully chosen such that a change in user flow will not lead to potential inaccuracies in the last seen date.  This might be what @nuclearpengy is suggesting. 
3. On events that occur at regular intervals. This is the token refresh approach suggested by @ErisDS.  This is also a good balance between accuracy and write-frequency. This also seems like the easiest to implement. A potential caveat here is that the accuracy of our data has a direct dependency on the token refresh frequency. If the frequency were to change it would impact the data, which may put us in a situation similar to the session timeout adjustment. We might also want to introduce custom messages, such as “Last seen: Less than an hour ago”.

Personally I’m leaning towards option 2. This provides a decent balance between accuracy, write-frequency, control, and a lack of dependencies.  The difficulty here lies in defining the actions and creating a middleware or such to manage the data. I'm not yet familiar enough with the code to call out the specific actions. 

These are my thoughts anyway. Open to feedback and suggestions.

**Comment by nuclearpengy** [comment]
I assume the _token refresh_ is what is used to keep the user session alive? If yes, then I guess that might be the simplest approach.

As far as I can tell, all the "last seen" is doing is telling us when last a person was in the backend/admin.

I like this:

> “Last seen: Less than an hour ago”.

**Comment by shawntoffel** [comment]
Thank you!
