### ISSUE TITLE
Unable to drag & drop to upload 

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#6850]
On the current master, I've run `grunt clean && npm install && grunt init && grunt dev` 😉 

Dragging & dropping to upload doesn't appear to work in any of the uploaders, be that image or file.

### Steps to Reproduce

Image:
1. Download an image
2. Load the editor
3. Hit cmd+shift+i to get an image upload box
4. Drag the image from the download bar at the bottom of chrome, onto the upload box
5. Nothing happens?

File:
1. Go to labs
2. Enable subscribers
3. Go to the new subscribers screen
4. Hit export, to get a csv file
5. Hit import to get the upload modal
6. Drag the file from the chrome downloads bar onto the upload modal

### Technical details:

* Ghost Version: master
* Browser/OS: Chrome 50.0.2661.102

**Comment by kevinansfield** [comment]
Strange, this seems specific to dragging from the downloads bar, I've not been able to reproduce by dragging a normal file. Looking into what makes the downloads bar different.
