### ISSUE TITLE
Large posts render too frequently and freeze up during edits

### ISSUE THREAD

**Issue by rorosaurus** [TryGhost/Ghost#6859]
### Issue Summary

I have a large post on my Ghost blog (about 18,000 characters), which is a complex list of bullets and hyperlinks.  Recently, when I've gone to edit it, I notice that it will freeze up while I type.  My CPU usage for Chrome also spikes.  I have to wait for it to catch up, which can take several seconds.  It's frustrating to edit my page this way.

### Steps to Reproduce

1. Make a post with lots of markdown (18,000 characters+)
2. Try to edit the post by adding additional markdown

We should verify that the editor does not become unresponsive while trying to render.

### Technical details:

* Ghost Version: 0.7.8
* Node Version: unsure
* Browser/OS: Chrome/Windows
* Database: sqlite3

**Comment by rorosaurus** [comment]
Other bloggers I've seen (HubPress.io for example) allows a configurable interval to schedule a timer that does the refresh.  Right now, it almost seems like we're re-rendering the page on each keypress, which is excessive.

**Comment by acburdine** [comment]
@rorosaurus the ghost editor has gone through a number of performance improvements which will be released in 0.8.0 (next day or two). If the problem still persists after that we can reopen this :smile:

**Comment by rorosaurus** [comment]
You are correct!  0.8.0 addresses this issue adequately. :smile: Thank you!
