### ISSUE TITLE
subscribe page has font loading issues on ghost pro

### ISSUE THREAD

**Issue by novaugust** [TryGhost/Ghost#6864]
### Issue Summary

An `Access-Control-Allow-Origin` header issue is prevent fonts from being loaded (on Ghost Pro pages? all blogs?)
### Steps to Reproduce
1. http://demo.ghost.io/subscribe/
2. "Back" button is missing font glyph
3. error in inspector pane
### Technical details:
- Ghost Version: 0.8.0
- Browser/OS: Chrome 50.0.2661

**Comment by novaugust** [comment]
Noticed I never put what the actual error was.


>Font from origin 'https://novaugust.ghost.io' has been blocked from loading by Cross-Origin Resource Sharing policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://blog.novaugust.net' is therefore not allowed access.

**Comment by ErisDS** [comment]
I believe this is actually a different incarnation of the same issue as #6922 - it should be solved in Ghost 1.0
