### ISSUE TITLE
"aSyNcId" text is sometimes inserted before header and after footer

### ISSUE THREAD

**Issue by rorosaurus** [TryGhost/Ghost#6866]
### Issue Summary

I see some weird text injected into my pages sometimes, which is **visible** above and below my expected content.

* It always seems to mention "aSyNcId".
* Repro is inconsistent.
* Doesn't seem to be part of my theme.
* Only started after upgrading to Ghost 0.8.0 today.
 * I also ran ````npm install --production```` per the [Ghost upgrade doc](http://support.ghost.org/how-to-upgrade).

### Screenshot of the source
![image](https://cloud.githubusercontent.com/assets/908662/15412293/3c4ccda0-1ddb-11e6-8004-422ea7d12182.png)

My theme's default file is [viewable on the github repo](https://github.com/rorosaurus/crisp-ghost-theme/blob/master/default.hbs).
* There is nothing between the open body tag and header, yet there is content being served there.
* I only see ````{{ghost_foot}}```` before the close body tag (nothing set in this field in admin panel).

### Steps to Reproduce

1. Load a Ghost page and compare the content with expected content

Notes:
* I first saw this repro on one of my post pages, but it didn't persist after a refresh or retracing my steps (click through to post page from home page).
* After this repro'd on my home page after a cold load, I decided to open this issue.

### Technical details:

* Ghost Version: 0.8.0
* Node Version: 4.3.4
* Browser/OS: Chrome/Windows
* Database: sqlite3

**Comment by rorosaurus** [comment]
I do have a Google Analytics script in ````{{ghost_head}}````.
Browser extensions: Adblock Plus, Privacy Badger, and HTTPS Everywhere. (trying to repro with extensions disabled now)

**Comment by rorosaurus** [comment]
I found this reference, so perhaps this is expected behavior after all!
https://themes.ghost.org/docs/faq#why-do-i-see-__asyncid_-on-my-page

Time to go through my theme and determine what conditions I'm using nested async helpers.

I guess some of the theme changes for 0.8.0 made some slight change that made this relevant to me now.

**Comment by ErisDS** [comment]
Did you upgrade from 0.7.9 or from an earlier version? Is your theme exactly the same as the one in the repo?

I don't see anything that would cause this in the repo you linked to, but I also don't see the issue on your site so mayhaps you already fixed it?

**Comment by rorosaurus** [comment]
I'm still not quite sure what causes it, but I also haven't seen it since my first two repros.  *shrug*

**Comment by ErisDS** [comment]
Well that's pretty weird in and of itself - but as you're not nesting any of the async helpers it would have been even weirder if this was easily reproducible!

I can only assume it was an artefact of the upgrade - something cached somewhere and getting confused, although I can't think what. 

I'll keep an eye out for similar issues.

**Comment by rorosaurus** [comment]
I updated the number of posts to see per page in Ghost settings, and when refreshing my main page, saw this issue again.  It appears to have disappeared since, however.  :)
