### ISSUE TITLE
Plain HTTP URL appears in some parts even when using urlSSL and HTTPS

### ISSUE THREAD

**Issue by alanfranz** [TryGhost/Ghost#6879]
I'm trying to configure Ghost to work both on plain http (which would be accessible only to me via an SSH tunnel, for debugging purposes) and https (for general access)

I'm using the latest stable at commit 8312e36cf6acbe1a49a4561449fbcfe10a96f2a5

I have configured the URLs this way in config.js:

```
 url:'http://localhost:2368',
 urlSSL: 'https://www.franzoni.eu',
```

I would expect that, for a request that was made via https to the urlSSL, all the links would refer to that urlSSL value; this is **almost** the case, expect for a few elements:

This is an example from index.html rendering:

```
<link rel="canonical" href="http://localhost:2368/" />
    <meta name="referrer" content="origin" />
    
    <meta property="og:site_name" content="A software professional&#x27;s homepage" />
    <meta property="og:type" content="website" />
    <meta property="og:title" content="A software professional&#x27;s homepage" />
    <meta property="og:description" content="Thoughts, stories and ideas." />
    <meta property="og:url" content="http://localhost:2368/" />
    <meta name="twitter:card" content="summary" />
    <meta name="twitter:title" content="A software professional&#x27;s homepage" />
    <meta name="twitter:description" content="Thoughts, stories and ideas." />
    <meta name="twitter:url" content="http://localhost:2368/" />
```

it seems that link rel="canonical", og:url, and twitter:url, always refer to "url" whatever is the scheme that gets employed by the client.

Other system info:
Ubuntu 14.04 64 bit
node 0.10.45
nginx configured as reverse proxy for ssl, exactly like shown in configuration examples at http://support.ghost.org/setup-ssl-self-hosted-ghost/

**Comment by ErisDS** [comment]
Hi @alanfranz, the behaviour you're describing is working exactly as expected.

Ghost needs to have one true URL to use as the canonical URL for posts etc to prevent duplicate content issues with search engines. This URL is calculated based on what what is configured in the `url`field. The `url` field should be configured to be the URL you'd expect outsiders to use to access your blog, as it's also what is used in RSS, and emails sent from the platform.

The urlSSL field is only used if the request is made via HTTPS and therefore logically the URL provided via `urlSSL` cannot be the canonical URL, as the canonical URL for a post must not change based on the request. 

I'm afraid the use-case you're describing isn't one that Ghost supports, nor one that I'd expect it to. It would be more usual to run a second version of Ghost in development mode for debugging purposes.
