### ISSUE TITLE
SMTP over SSL or TSL not working

### ISSUE THREAD

**Issue by vrghost242** [TryGhost/Ghost#6892]
### Issue Summary

Not certain this is a bug, but fairly certain it is. 

Can not get the SMTP functionality to work at all, and as far as I can tell, it is set correctly. 
Settings currently
```        
options: {
                host: 'smtp.webfaction.com',
                from: 'blog@someplace.me,
                port: 465, 
                secure: true, //Should give me SSL
                auth: {
                        user: 'blog_me',
                        pass: 'WouldntULikeToKnow'
                },
        },
```
Every time I start the application I get the following message in the log
```
WARNING: Ghost is attempting to use a direct method to send email.
It is recommended that you explicitly configure an email service.
Help and documentation can be found at http://support.ghost.org/mail.
```
But there is no real information on support.ghost.org/mail on how to get ghost to use SMTP over SSL. 

I also get this error message
```
Warning: Error sending email: Error: Message could not be sent
More info: connect ETIMEDOUT Please check your email settings and resend the invitation.
```

Tried SSL, TSL and no security
The mail server responds on all ports.

Is there any way to debug the mail attempt, or does anyone know why this is failing?

### Technical details:

* Ghost Version: 0.8.0
* Node Version: v0.10.45
* Browser/OS: centos-release-7-2.1511.el7.centos.2.10.x86_64
* Database: N/A

**Comment by ErisDS** [comment]
Hi @vrghost242, this is definitely a configuration issue and not a bug. If you swing by our [slack](https://ghost.org/slack) community someone will help you work through the correct config 👍
