### ISSUE TITLE
urlFor "nav" does the wrong thing when passed a port as a relative URL

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#6893]
If you setup a navigation item with a url that's just a port number on the same domain as configured in config.js, `urlFor` treats this like a relative path and starts adding slashes where there shouldn't be one. 

### Steps to Reproduce

1. Configure the url in `config.js` to be a URL that doesn't have a port number (it doesn't have to be right :wink: ) e.g. `http://ghost.dev`
2. In navigation, add an item which points at a port number on the same url e.g. `http://ghost.dev:3000`
3. Save the navigation item, everything will look fine in the admin panel
4. Open your theme, view the source, and see the url is output with an extra slash in the middle as well as at the end e.g. `http://ghost.dev/:3000/`

This is a bug with the logic here: https://github.com/TryGhost/Ghost/blob/c549914ae867cb3f185b159e0a11ac713e0218c3/core/server/config/url.js#L204

In the case that there's a port number which isn't included in config.js, this is effectively pointing at an external site.

### Technical details:

* Ghost Version: 0.8

**Comment by sakulstra** [comment]
Damn sry didn't see there was already another pr for this. Feel free to close mine again.
