### ISSUE TITLE
Drag and drop image upload in markdown editor

### ISSUE THREAD

**Issue by kevinansfield** [TryGhost/Ghost#6897]
We would like to implement the ability to hide the preview when editing to give a more distraction-free editing experience. However, that feature is currently blocked by the inability to upload images without using the upload component that is rendered inside the preview.

The basic implementation should take the lead from Github's markdown editor, which follows this  process:
1. Place cursor where you would like to insert an image
2. Drag and drop an image onto the markdown editor
3. The image tag is added and indicates that it's uploading
4. Saving is disabled whilst uploading is in progress
5. Once uploaded the uploading text is replaced with the image url

![github-upload](https://cloud.githubusercontent.com/assets/415/15583149/79de3f32-236c-11e6-83a4-940414ef10e8.gif)

Github's implementation is fairly naive, if for example you place the cursor in the middle of an existing image tag it will simply insert another image tag exactly where the cursor is, breaking the original image tag. I believe this is acceptable for the initial implementation.

Another aspect of the Github editor is the bottom status bar which provides upload instructions and status info - I think we can ignore that initially but it's worth thinking about when looking at the preview-only design.

![github-upload-2](https://cloud.githubusercontent.com/assets/415/15583427/accee0ee-236d-11e6-99a1-61f96d107bd6.gif)

Other things to consider:
- Conveying error responses (invalid file type, file too large, etc)
- Dragging to the markdown editor should also be possible when the preview is displayed, the preview needs to behave sensibly in that situation
- Github appears to use the filename as a unique identifier, are there any situations where it's possible to upload multiple images with the same filename? If so, how should that be handled?
- Much of the code will likely be re-usable for handling the pasting of images (#4753)

**Comment by pascalandy** [comment]
Multi image upload would be huge for many users.

Cheers!

**Comment by KennethAshley** [comment]
Working on this now

**Comment by ErisDS** [comment]
I think it makes sense to close this and #4753 in favour of #7429 (the epic issue for the new editor). We can reopen them once the new editor is shipped, if these features don't make it into the first iteration.
