### ISSUE TITLE
Have tags input autocomplete on Tab instead of Return

### ISSUE THREAD

**Issue by dbalders** [TryGhost/Ghost#6912]
Currently, when you are typing in a tag, as it starts to autocomplete with the existing tags, if you press tab, it does not auto complete, but creates a new tag with what was typed in. If you press return, then it auto completes.

I think this should be switched to having tab be the auto complete, and return being the creating a tag functionality. This is the way auto complete on google, facebook, and twitter work, so I think it makes sense for the tags functionality to work this way as well.

What do you think?

**Comment by ErisDS** [comment]
@dbalders this sounds like it makes sense to me? If we're doing the opposite of what everyone else is doing then we should very probably change ours.

That probably explains why I seem to battle the tag input!

**Comment by acburdine** [comment]
This may unfortunately have to wait until the tags input is converted to ember-power-select. It's easy to do there, but it doesn't seem like it's possible in selectize (See selectize/selectize.js#335) 😞

**Comment by nickgoodliff** [comment]
This option does exist in selectize settings object: selectOnTab

`.selectize({ selectOnTab : true })`

**Comment by dbalders** [comment]
In messing around with this, adding the ability to select on tab was as easy as stated above. Just add the option in. The problem then is that selectize is now selecting on tab and on return. There doesn't seem to be an option and I couldn't figure out a way to not have it auto-complete on return. If anyone actually knows a way to do this, I can finish the PR for it. If not, might not be worth the time with power-select in the pipeline.

**Comment by aeolingamenfel** [comment]
Looking through the current master for Selectize, it looks like there's no current way to disable the auto-complete on return functionality:

```
case KEY_RETURN:
    if (self.isOpen && self.$activeOption) {
	    self.onOptionSelect({currentTarget: self.$activeOption});
	    e.preventDefault();
    }
    return;
```

There's also no issue open for that enhancement at the moment.

**Comment by kevinansfield** [comment]
Closing as I have added this as a sub-task to the issue proposing to replace `selectize` for the tags input - #6458
