### ISSUE TITLE
Ghost doesn't send posts to subscribers

### ISSUE THREAD

**Issue by rawsh** [TryGhost/Ghost#6913]
### Issue Summary

Ghost doesn't send posts to subscribers after they are posted.
I'm hosting ghost on digitalocean with their 1 click ghost.

### Steps to Reproduce

1. Set up email and send test emails
2. Add your many test emails as subscribers
3. Write a post and publish

This should send an email to all subscribers but does not.

### Technical details:

* Ghost Version: 0.8
* Node Version: Default
* Browser/OS: Chrome/Linux hosted on Ubuntu/Digitalocean
* Database: Default

**Comment by sakulstra** [comment]
@rawsh: i think 0.8 doesn't support this yet. https://dev.ghost.org/ghost-0-8-0/ For now you can only "collect emails" the scheduled email notifications will come in a future release as far as i know.

**Comment by rawsh** [comment]
Hmm. Thats pretty lame to have subscribers with no emails. 
Is there any way I could forcibly add mailchimp or something?
At least have it update a mailchimp list so I can send the posts.

**Comment by sakulstra** [comment]
@rawsh I think not without hacking the core, right now. Subscriptions are only two weeks old an still in early beta. I'd suggest to just wait a few more weeks and use the csv import/export till it leaves beta state ;)

**Comment by kirrg001** [comment]
Hey @rawsh . We already work on this feature. The deadline is around the 10th of June. And in the first version it will only support mailgun. I will close this issue for now. If you have any questions to this feature, join us at https://ghost.slack.com. Especially in the next 10 days there will be open discussions.

**Comment by evil-shrike** [comment]
Hi,
should it work in v0.11.2 ?
I set up subscribers and mail config works fine (sent invites), but I don't see any notifications email on posting page/blogpost..

**Comment by kevinansfield** [comment]
@evil-shrike e-mail sending is not implemented yet which is why the feature is still in `beta` under labs.

Implementation has been put on hold temporarily whilst we [push towards 1.0](https://dev.ghost.org/lts/), once that is out then we'll be re-prioritising our backlog which includes the subscribers feature.

**Comment by evil-shrike** [comment]
Ok. 
>which is why the feature is still in beta under labs.
Actually it's not under labs, it's in its own Subscribers section. Also there's input in public UI (in main menu) for subscribing which leads to /subscribe/ page. I can't see anywhere "beta" tags in that UIs. 
But I'm grumbling.. Anyway, thanks for clarification.

What about Slack notifications? They work in some way - at least "Send test notification" publishes a message. But again there's no notifications on new posts.

**Comment by rawsh** [comment]
@evil-shrike What I did to get around the subscribers notification was to run a separate nodejs express server on the same machine as my blog (ubuntu on digitalocean). 

I use the mailgun api because they have a newsletter option, and I use zapier to listen for new posts (rss) and send them to subscribers.

If you would like the code for the subscriber bot, you can [see it here](https://github.com/rawsh/devpygrunt).

Also, here is the code for the [subscribe.hbs page](https://gist.github.com/rawsh/554d3aa0d8519816c891ac4021ffc11f).

[Try it here](http://www.devpy.me/subscribe/)

**Comment by jgirdner** [comment]
Absolutely ridiculous that you have not implemented emailing subscribers yet.

**Comment by rawsh** [comment]
Pretty lame. Who wants to gather subs, export, and email every time they post? I don't...

**Comment by jgirdner** [comment]
So lame lol. This post is from 2016. 2 freaking years of collecting subscribers and not emailing them. What is the point. Also when I update my blog it removes all my dang integrations for Mail Chimp. Starting to regret selecting Ghost Blog

**Comment by seonwoolee** [comment]
Two years later and this feature STILL isn't implemented! Come on guys!

**Comment by ErisDS** [comment]
The subscribers feature was an experimental feature. It is possible to hook it up to send mail using Zapier, if you so desire. Otherwise, we have no intention of extending the feature in its current form, rather it will be reimagined as part of [memberships & subscriptions](https://forum.ghost.org/t/memberships-subscriptions/377).

To the last few angry commenters here, I refer you all to our [5 year anniversary blog post](https://blog.ghost.org/5/) and particularly the section on [open source development](https://blog.ghost.org/5/#opensourcedevelopmentislargelymorebrokenthanever).
