### ISSUE TITLE
Ghost Editor is blank, uncaught syntax error ghost.min.js on chrome

### ISSUE THREAD

**Issue by rawsh** [TryGhost/Ghost#6914]
### Issue Summary

Occurs in chrome stable on ubuntu. Works in firefox but not in chrome.

### Steps to Reproduce

1. Install stable ghost
2. Make admin
3. Check if normal settings work (e.g. general labs, they do for me)
4. Edit an existing post

Screenshot:
![](http://i.imgur.com/rU3CQXz.png)

Chrome console spouts this beautiful error:

```
ghost.min.js?v=7461cbf0ad:25 Uncaught SyntaxError: Invalid regular expression: /[^\s\dA-Za-zÂªÂµÂºÃ€-Ã–Ã˜-Ã¶Ã¸-ËË†-Ë‘Ë -Ë¤Ë¬Ë®Í°-Í´Í¶Í·Íº-Í½Í¿Î†Îˆ-ÎŠÎŒÎŽ-Î¡Î£-ÏµÏ·-ÒÒŠ-Ô¯Ô±-Õ–Õ™Õ¡-Ö‡×-×ª×°-×²Ø -ÙŠÙ®Ù¯Ù±-Û“Û•Û¥Û¦Û®Û¯Ûº-Û¼Û¿ÜÜ’-Ü¯Ý-Þ¥Þ±ßŠ-ß .................... ect
```

### Technical details:

* Ghost Version: 0.8 stable
* Node Version: stable
* Browser/OS: chrome
* Database: default

**Comment by ErisDS** [comment]
@rawsh I have experienced this error, but only whilst swapping around between branches. Please make sure that your Ghost file are built correctly, and then restart it, clear your chrome cache and refresh the page. That should get it fixed.

If not, let us know.

**Comment by zkanda** [comment]
Hello, I'm using the [docker-ghost](https://hub.docker.com/_/ghost/) version `0.8.0` and it's the same issue for me. I've been experiencing this for days and a reload usually just fix it, however I just updated to the latest google-chrome(51) and the error is now persistent. Clearing the cache doesn't seem to fix it. I assume the Ghost files are built already in the docker container. I'm not so sure how to debug this, let me know if you need any information.

**Comment by kevinansfield** [comment]
That's interesting, the docker image does use the pre-built files which kinda rules out build issues.

**Comment by ErisDS** [comment]
Here's the full error as I get it, the important piece (I think) being the end:

> Range out of order in character class.

![](https://camo.githubusercontent.com/e68120a210555600b6b51cf7c1a051ecafc0108b/687474703a2f2f7075752e73682f6f433845322e706e67)

I did some googling around the error and I cannot say it makes any sense - it suggests one of the characters is out of order, e.g. you're asking for `z-a` instead of `a-z`. I still get the error frequently, but so far a re-run of grunt dev, open dev tools with the cache disabled & refresh my browser has always worked.

Using the docker image rules out the rebuild, but it does not rule out a cache error? I know @zkanda said they were clearing their cache, but perhaps this is something as crazy as an overflow in the cache e.g. the regex is too long?

**Comment by patriziotufarolo** [comment]
Same issue as @zkanda with the docker image

**Comment by ErisDS** [comment]
We are seeing reports of this on Ghost(Pro) and with Ghost-Desktop - so it seems like a more extensive issue than a build error for sure.

However, it does seem to be weirdly intermittent. If it happens for someone, they don't seem to be able to get out of it however every time I've seen it locally (which is a lot) a rebuild and restart has fixed it.

On Ghost-Desktop, this got [reported](https://github.com/TryGhost/Ghost-Desktop/issues/159) in tandem with seeing a weird character in code injection.

I have also noticed, on occasion weird characters appearing in Ghost admin. I am able to reproduce it now, having just started Ghost without having run any of the grunt tasks:

![](http://puu.sh/pr9a0.png)

I'm not sure if these issues are related or just two weird things which seem to appear intermittently 😉

**Comment by AustinPaquette** [comment]
A quick gander on stackoverflow led me to [this](http://stackoverflow.com/questions/17727884/range-out-of-order-in-character-class-in-javascript/17728040#17728040).

It seems as though the regex needs to be adjusted.

I'd also like to point out that I got this error on the live version of my site but did not have any issues at all on a local install which only further supports what @ErisDS said:

> seem to appear intermittently

**Comment by jewei** [comment]
Hi, I'm using 0.8.0 from https://ghost.org/zip/ghost-0.8.0.zip and facing the same issue. Restart ghost and clearing the browser cache doesn't help. Only happens in lastest Chrome browser. Firefox and Safari are not affected. Symptoms are the same as @ErisDS described above, "Range out of order in character class" error and weird characters in code injection.

**Comment by sakulstra** [comment]
I just got the same error, but @ErisDS solution helped me fixing it (also on chrome 51).
As this is probably related to #6663 (merged on 31.03 - first bug report on 01.05) it would probably help to reintroduce the xregexp dependency until XRegExp has native support the supported browsers?
63kb isn't that bad.

**Comment by ErisDS** [comment]
I haven't seen this issue for at least a month now. 

The behaviour I experienced was intermittent but persistent. The editor would work for me for a while, and then suddenly not work. Once it didn't work, no amount of refreshing would fix it. Either rebuilding the files (e.g. generating a new file and causing the cache to clear) or restarting the browser would fix it.

Therefore, I suspect it was some sort of error in chrome itself, perhaps a memory overflow. 

I'm going to close this for now, assuming it is resolved somewhere in Chrome. If anyone experiences it again, please comment here so we can reopen and investigate further.

**Comment by zkanda** [comment]
I'm not experiencing this anymore. Most likely it's a bug in Chrome, sigh(Technology) ¯\\\_(ツ)_/¯
