### ISSUE TITLE
Admin panel button text bigger than expected

### ISSUE THREAD

**Issue by ttimasdf** [TryGhost/Ghost#6916]
### Issue Summary

the "Save draft" button when creating new draft and the "new post" button in "Content" menu have a bigger font in Chrome (14px) vs other browsers(10px).

I installed the open sans font family but it's no help.

the misbehaved page in screenshot below.

![](https://img.vim-cn.com/d0/b220323724cbbc57e91332dd9e88869cd90c77.png)

vs good one:

![](https://img.vim-cn.com/66/242da5ac970dfbaf7747e14f0f758d247fe188.png)

Browsers having this issue:(which i tested)
Chrome Canary 53.0.2746.0 canary (64-bit)
Chrome 51.0.2704.79 (64-bit)

browsers display correctly:
Firefox 40.0.3
Safari 9.1 (11601.5.17.1)
### Steps to Reproduce
1. Login to the admin dashboard, using Chrome
2. Click `New Post` in the menu.

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?
- stated above
  ### Technical details:
- Ghost Version: 0.8.0
- Node Version: 4.4.5
- Browser/OS: Chrome Canary 53.0.2746.0 canary (64-bit) / OSX 10.11
- Database: SQLite

**Comment by ttimasdf** [comment]
a dirty workaround.
add `max-height` to in ghost.css:
```
.btn-sm {
  padding: 7px 10px;
  border-radius: 2px;
  font-size: 1rem;
  line-height: 1.5;
  max-height: 31px;
}
```

**Comment by dbalders** [comment]
Huh, I am unable to reproduce this in Canary (54.0.2804.0) or Chrome (52.0.2743.82) on mac. Could it be some plugin you have or something?

**Comment by dbalders** [comment]
@ttimasdf just following up again. Is this still happening to you?

**Comment by ttimasdf** [comment]
![screenshot](https://cloud.githubusercontent.com/assets/2762704/17360568/d1ac29f0-599e-11e6-85bf-29f2e515b9f1.png)

Yeah, still present in Ghost 0.9.0. Tried going incognito but the result remains.

I guess it has something to do with my locale(chinese), but I didn't find options to change the display languages in the latest version of canary, so not tested.

**Comment by ErisDS** [comment]
I think this is an edgecase for the chinese locale. If it's still an issue we can reopen however I know the buttons are about to have an overhaul.
