### ISSUE TITLE
Node version is outdated in documentation

### ISSUE THREAD

**Issue by Josecc** [TryGhost/Ghost#6918]
### Issue Summary

Ghost version is outdate in the documentation for installing (for developers). I haven't tried it yet in Node 6, but it incorrectly states now that the latest version is 0.10.4.

### Steps to Reproduce

1. Navigate to http://support.ghost.org/installation/
2. Scroll to the overview section, second paragraph
3. Check Node's website for the latest (current) version recommended for most users

### Technical details:

* Ghost Version: 0.8.0
* Browser/OS: Chrome

**Comment by ErisDS** [comment]
Updated 👍
