### ISSUE TITLE
robots.txt is blocking some CSS

### ISSUE THREAD

**Issue by alexbagirov** [TryGhost/Ghost#6922]
### Issue Summary

I was seeking the Google Webmaster report when noticed that it is saying I have a blocked resource on subscribe page (a new feature to leave email addresses located at `ghost.com/subscribe/`. Actually we have a CSS there which has the following link: `ghost.com/ghost/ghost.min.css` but our **robots.txt** has this rule:

```
Disallow: /ghost/
```

Means that we are blocking our CSS and Google for example is unable to locate it.

P.S.: Also used **View as Googlebot** function now and it really sees this page without any styles.
### Technical details:
- Ghost Version: 0.8.0

**Comment by tlyman** [comment]
If I'm not mistaken, Google strongly discourages blocking CSS and JS that is used to render web pages, as it has a negative impact on search rankings.

Does anyone know the reason everything in the /ghost/ directory is being disallowed?

**Comment by nuclearpengy** [comment]
@tlyman `/ghost` is the admin directory. It should not be indexed as your site content is not hosted or published at this URL.

**Comment by ErisDS** [comment]
Correct - the problem is not that the robots.txt is blocking the file - it's doing the right thing ✅ 

The problem here is that we need to register these assets to be served over a shared URL where they are needed for the blog. There is a similar problem with the icons being served when the admin panel is set to be served over https but the blog is not.

**Comment by sakulstra** [comment]
I tried to fix this but I couldn't really find a solution :/
I think I basically have to do the same than middleware/index.js does with the favicon - the problem is, that ghost.css isn't in the shared folder - could someone give me a hint where to look at?
Regards and thanks in advance.

**Comment by ErisDS** [comment]
In Ghost 1.0.0 we no longer serve the admin CSS for the frontend of the blog - so I think this issue should be resolved.
