### ISSUE TITLE
sqlite3/test env: raw knex queries can cause inconsistency with dates

### ISSUE THREAD

**Issue by kirrg001** [TryGhost/Ghost#6930]
**I’ve noticed an issue with dates and our test env.** 

Our test utils offer a way to insert data into the database without using the model layer (raw knex queries like `db.knex('posts').insert(...)`). Especially in case of dates our model date hook is not triggered (`fixWhenSave`). This hook takes care of inserting dates in the correct format.

It can happen in the test env (using raw knex queries) that for `sqlite3` timestamps are stored instead of our new date format `YYYY-MM-DD HH:mm:ss`. 
##### Here is an example where it can cause heavy bugs:
- you add posts via the test env with a specific date
- they are stored in sqlite3 as timestamps
- you add an endpoint which queries posts with from/to
- because your dates are stored as timestamps, you would filter something like `filter = 'created_at>moment(date).valueOf())`
- you add a test and your test is green
- now you start your server in production using sqlite3, but it doesn't work
- why?because in production the model layer is used and the `fixWhenSave` model hook converts every date into the format `YYYY-MM-DD HH:mm:ss` and also stores it like this into sqlite3

---
##### One solution could be: getting rid of raw knex queries.

Advantage:
- everything (especially dates) is normalized

Disadvantage:
- it's harder to insert data because the whole model logic (validation etc) is involved
##### Another solution could be: extend the test utils to normalize dates

Advantage:
- we can still insert data fast without the model layer

Disadvantage:
- unneeded complexity in the test env
##### Third solution could be: keep as is and developer needs to be aware of this fact

Advantage:
- no code change at all

Disadvantage:
- can cause trouble

These are just three spontaneous solutions, i am happy and open for more ideas.
For now everyone who test with dates should use the model layer. (like `models.Post.add(...)`).

**Comment by ErisDS** [comment]
I think both this issue and #6898 are pointing to us needing to upgrade our test fixtures framework a bit.

In the case where we are using knex to insert fixture data really fast, we need to be more careful about creating objects which match the behaviour of the models.

We have lots and lots of utils atm for creating data, many tests need the DB initialised into a particular state. Some grab the raw JS objects to use during the tests, but some want data for inserting via knex (direct inserts) some want data for models and some want data for the API. 

I think we need to work on cleaning up the way in which this data can be accessed to use a cleaner API, and then making sure that the data provided via the API is in the correct state.

i.e.  if you ask the data generator for data to insert into the db, the date should be correctly prepared for you.

**Comment by ErisDS** [comment]
This seems very similar to #7196 @acburdine / @kirrg001 maybe close one or the other?

**Comment by kirrg001** [comment]
Closing in favour of #7196, but we have to consider this issue in. Added as sub task.
