### ISSUE TITLE
0.9.0 Beta 1 - Ready for testing

### ISSUE THREAD

**Issue by kevinansfield** [TryGhost/Ghost#6933]
# Beta Release Notes

There is now an [initial beta of 0.9.0](https://github.com/TryGhost/Ghost/releases/tag/0.9.0-beta.1) published and ready for testing.

If you are able to do some testing, this would be much appreciated. *REMEMBER:* Make a backup first!

If you find any bugs, please raise them as separate issues according to the contributing guidelines

If you complete successful testing, please let us know by adding a comment here detailing what you tested and on what environment, covering relevant things like OS, browser, prod/dev mode, database (sqlite, mysql, postgres), server timezone, blog timezone etc.

## Some important areas for testing:

Aspects of Ghost not often used during development:

- production environment
- MySQL, Postgresql
- Ghost as npm module
- the upgrade process

Important things that have changed:

### Migration to convert all datetimes in the database to UTC

In order to support customisable timezones and post scheduling this release contains a migration that will update all datetimes stored in the database to UTC. If your server timezone is already set to UTC there should be no change.

Please check your database before and after upgrading to ensure that the migration is successful.

- **sqlite3:** should already use UTC timestamp, after the migration you should see the same times but in `YYYY-MM-DD HH:mm:ss` format
- **postgres:** the migration script is not executed at all, you should see no change in the stored times
- **mysql:**  you should see the times change to UTC. For example if your server timezone is set to EST (UTC -5) then the times in your database after the migration should be 5 hours later.

### Timezone support

It's now possible to set the timezone of your blog - this should finally fix the "I posted at 3AM this morning but my post says says it was published yesterday" bugs.

There is now a dropdown in the general settings screen of the admin where you can choose the timezone you want your blog to be in. Please test changing this and ensuring that the dates/times displayed on your blog front-end and in the admin content screen/editor are what you expect.

**Comment by jloh** [comment]
I don't know whether this is a bug, so posting as a comment.
Some of the Australian cities seem to be listed as incorrect timezones.
Canberra, Hobart, Melbourne, Sydney, Vladivostok are all GMT +10 but are listed as +11. At the same time Adelaide is listed as +10:30 when it is in fact +9:30.
Brisbane however (listed as +10) is correct.
I don't know whether its because majority of the above (Brisbane certainly doesn't) do daylight saving and this muddles with things but my expectation living in Australia is for the ones listed as +11 to be +10 and so forth.

**Comment by kevinansfield** [comment]
@AileenCGN was the list of timezones taken from moment-timezone or from some other source? It would be good to double-check them to make sure they are accurate/up to date.

**Comment by AileenCGN** [comment]
Hi @jloh, 

I checked some other timezones lists, and they all show the same result:
Tumblr:
![image](https://cloud.githubusercontent.com/assets/8037602/15885781/bb6c48da-2d59-11e6-8d7c-31e4e9af01c5.png)
WD MyCloud:
![image](https://cloud.githubusercontent.com/assets/8037602/15885793/cf85e588-2d59-11e6-833e-c4f3ff1be150.png)

Obviously, there are a few timezones, which change the GMT offset in june and december. See here:
https://github.com/moment/moment-timezone/

I will dig into that and see, what we can do, to show it correctly. Luckily, it's only the label. The offset calculation should be right!

@kevinansfield: the timezone list is created manually.

**Comment by kevinansfield** [comment]
Closing this as [beta.2](https://github.com/TryGhost/Ghost/issues/6997) has now been released.
