### ISSUE TITLE
Bug: Warning: a promise was created in a handler but was not returned from it

### ISSUE THREAD

**Issue by juanpaco** [TryGhost/Ghost#6935]
### Issue Summary

If the `NODE_ENV` environment variable is set to `'development'`, then Ghost gives the above warning on startup.

### Steps to Reproduce

I'm embedding Ghost into another application, so I've only tested it with that path.  Understanding the issue though, I think this would happen even with Ghost standalone.

1. Run an app that embeds Ghost with `NODE_ENV=development <command that starts your app>`
2. Observe the following in the console output: `Warning: a promise was created in a handler but was not returned from it`

This is a bug because Ghost should not give this warning when run.

### Technical details

Bluebird throws this error if the condition is triggered and either `NODE_ENV` is set to `'development'` or `BLUEBIRD_DEBUG` is set to something other than `0`.  If the user does not set `NODE_ENV` explicitly, Ghost will do so in `/core/index.js`, but only *after* Bluebird has already checked its environment values.

* Ghost Version: 0.8.0 release
* Client OS: Ubuntu 16.04
* Server OS: Ubuntu 16.04
* Node Version: 4.2
* Browser: n/a
* Database: n/a

**Comment by JohnONolan** [comment]
I don't know if this is worth reopening - but FWIW this is happening again for me. Fixed by removing env var for now.
