### ISSUE TITLE
"http://builtwith.com/yourblog.com" style URLs do not work on the front-end

### ISSUE THREAD

**Issue by kevinansfield** [TryGhost/Ghost#6939]
### Issue Summary

The front end does not respect navigation URLs where the blog URL forms part of the URL such as with http://builtwith.com/yourblog.com 

### Steps to Reproduce

1. In the Navigation section of the admin area, add a new entry `http://builtwith.com/localhost:2368` (change the `localhost:2368` to match your blog URL), then save
2. Open the front-end of your blog, note that the `href` for the newly added navigation link is `http://localhost:2368` (or your blog URL) not the full `http://builtwith.com/x` URL

**Comment by sakulstra** [comment]
The problem is located in config/url.js

```js
urlPath = data.nav.url; // http://url.org/localhost:2368/
            secure = data.nav.secure || secure;
            baseUrl = getBaseUrl(secure); // http://localhost:2368
            hostname = baseUrl.split('//')[1] + ghostConfig.paths.subdir; // localhost:2368
            if (urlPath.indexOf(hostname) > -1 // hostname not at start
                && urlPath.indexOf('.' + hostname) === -1 // hostname not behind subdomain
                && urlPath.indexOf('mailto:') !== 0) { // no mailto
                // make link relative to account for possible
                // mismatch in http/https etc, force absolute
                // do not do so if link is a subdomain of blog url
                urlPath = urlPath.split(hostname)[1]; // [ 'http://url.org/', '/' ] --> '/'
                if (urlPath.substring(0, 1) !== '/') {
                    urlPath = '/' + urlPath;
                }
                absolute = true;
            }
```

**Comment by cerkit** [comment]
I have a workaround that I am using until Ghost pro is updated with the fix.

When setting the domain after the first domain, url encode the period, like so:

`http://builtwith.com/domain%2Ecom`

This has the desired result.
