### ISSUE TITLE
Ember CLI error when running `grunt dev` on node 0.10.45

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#6953]
I keep seeing this:

![](http://puu.sh/pmnhJ.png)

Not sure if it's actually affecting anything. I had thought that ember-cli was keeping node 0.10 support until October, so not sure what we can do here. Just raising it because it keeps cropping up.

**Comment by Turbo87** [comment]
> I had thought that ember-cli was keeping node 0.10 support until October

That is the official plan, but obviously it's getting harder if sub-sub-sub-dependencies decide to drop support :-/

/cc @nathanhammond @stefanpenner

**Comment by nathanhammond** [comment]
The first notice is a deprecation warning. That's not as clear as it should be, but per every proposed plan we had support for 0.10 and 0.12 until they were end-of-life.

The second note is an error thrown by `istextorbinary`. Somebody has to open a PR against that package to make it 0.10 compatible again. This is the commit which broke it: https://github.com/bevry/istextorbinary/commit/422e043cdf5f5117f929261858fba4abab9f7ce0

Alternatively we can not depend on it here: https://github.com/stefanpenner/async-disk-cache ... something inside of our community.

**Comment by stefanpenner** [comment]
@ErisDS we still support 0.10, although that dep seems to be cause visual noise it does appear to work.

**Comment by stefanpenner** [comment]
> The second note is an error thrown by istextorbinary. Somebody has to open a PR against that package to make it 0.10 compatible again. This is the commit which broke it: bevry/istextorbinary@422e043

it seems to work just fine though no?

**Comment by stefanpenner** [comment]
new async-disk-cache released, istextorbinary is lazily loaded and only when required (not something ember-cli uses)

**Comment by ErisDS** [comment]
To confirm - this wasn't breaking anything, but the message is gone now thank you all for the super fast reactions 👍
