### ISSUE TITLE
Refactor date properties to contain `UTC`

### ISSUE THREAD

**Issue by AileenCGN** [TryGhost/Ghost#6985]
Date properties in Ghost-Admin are named like `publishedAt` at the moment. After implementing timezones, all dates are in UTC time and will be sent back to the server, using the `moment-utc` custom transform. To make it more clear, that we are dealing with UTC-dates, we want to rename them to contain the word `UTC`, e. g. `publishedAtUTC`.

------------

**The following date properties are affected:**

- `publishedAt` in `post` model 
- `createdAt` in `post`, `role`, `subscriber`, `tag` and `user` model
- `updatedAt` in `post`, `role`, `subscriber`, `tag` and `user` model
- `unsubscribedAt` in `subscriber` model
- `lastLogin` in `user` model

**Using the serializers to match the renamed client properties with the server properties:**

This should be added to `serializers/application.js`:

```
attrs: {
    createdAtUTC: 'createdAt',
    updatedAtUTC: 'updatedAt',
    unsubscribedAtUTC: 'unsubscribedAt'
 }
```

This to `serializers/post.js`:

```
attrs: {
    publishedAtUTC: 'publishedAt'
 }
```

and this to `serializers/user.js`:

```
attrs: {
    lastLoginUTC: 'lastLogin'
 }
```

------------

**ToDos:**

- [x] Every property listed above should be renamed in the codebase to end with `UTC`.
- [x] Update the serializers to match the properties between client and server

**Comment by kevinansfield** [comment]
👍 LGTM, the only minor thing is that I think `unsubscribedAtUTC: 'unsubscribedAt'` would go in `serializers/subscriber.js` as it's only used for that model?

**Comment by AileenCGN** [comment]
So in that case, we have to make a new file for `servializers/subscriber.js`? I wasn't sure about that, that's why I put it in the `application` serializer.

**Comment by kevinansfield** [comment]
Yeah, new serialiser file. `ember g serializer subscriber` will do it for you and also create the associated test file 😄

In general don't be afraid of creating new files, t's much better to have more small specific files than fewer large abstract ones. Also, once Ember's [module unification](https://github.com/dgeb/rfcs/blob/module-unification/text/0000-module-unification.md) lands the model, adapter, and serializer files would all be in the same `models/subscriber` folder so it's better to be specific now as it would only get split out later.

**Comment by AileenCGN** [comment]
Having the properties listed in `serializers/application` results in lots of warning messages, as Ember is expecting the `createdAtUTC` and `updatedAtUTC` properties all over the application. But they are not used in `setting`. Therefore I created a `serializers/tag`-file additional to the `serializers/subscriber` and specified only the properties, that are used for the certain models.
