### ISSUE TITLE
Investigate use of babel's `includePolyfill` option

### ISSUE THREAD

**Issue by kevinansfield** [TryGhost/Ghost#6989]
Inside [ember-cli-build.js](https://github.com/TryGhost/Ghost-Admin/blob/master/ember-cli-build.js#L22) we are currently telling babel to include it's polyfill. This adds a 98kb minified payload to our JS.

Originally this was added to fix problems that we were seeing with `phantomjs` however we are no longer using that for our tests.

Some addons such as `ember-power-select` use generators and require the Regenerator Runtime, however there is now [ember-maybe-import-regenerator](https://github.com/machty/ember-maybe-import-regenerator) that can include that separately. This takes a 98kb payload down to a 4kb payload.

I believe the hypothetical browser that babel targets is somewhere around the IE10 level which matches our "last 2 versions" browser support so we should be able to get away with not including the full polyfill. I propose that we test our supported browsers without the polyfill and drop it if possible.

TODO:
- [x] Test last version of Edge
- [x] Test last 2 versions of Firefox
- [x] Test last 2 versions of Chrome
- [x] Test last 2 versions of Safari
- [x] Test IE11

**Comment by acburdine** [comment]
Even though it isn't working for pull requests, we could run a custom test using Saucelabs on master.

**Comment by kevinansfield** [comment]
In testing Chrome, Firefox, Safari, and Edge are all capable of running without the polyfill. IE11 requires it as there is no native `Promise` support.

It should be possible to remove the polyfill as soon as we drop IE11 support.

**Comment by ErisDS** [comment]
Noticed this has all of its tasks ticked off, can it be closed or is there one missing?

**Comment by kevinansfield** [comment]
Closing this with `later` as it's not actionable at the moment. Something to look at when we drop IE11 support and can properly use ember cli's new targets feature.
