### ISSUE TITLE
Access denied

### ISSUE THREAD

**Issue by bhua** [TryGhost/Ghost#6994]
i upload image, i can upload 11 images, i get the error `Access denied` when i upload the 12th image.

![screen shot 2016-06-15 at 17 29 45](https://cloud.githubusercontent.com/assets/535675/16074798/c7c77b2a-331e-11e6-8072-1743dd84f4fc.png)

**Comment by kevinansfield** [comment]
Closing as a duplicate of #6884.

This should be fixed in the upcoming 0.9 release. If you still have trouble after upgrading please come back and re-open. Thanks.

**Comment by bhua** [comment]
@kevinansfield ok, i will check it in 0.9 release, many thanks

**Comment by 1beb** [comment]
+1 for 0.9.0 happening to me with ghost:latest and ghost:0.9.0

**Comment by 1beb** [comment]
Logged out and back in, and was able to post images again. This issue still exists though. Recommend reopening.
