### ISSUE TITLE
config.js in docker container

### ISSUE THREAD

**Issue by linxyfe** [TryGhost/Ghost#6995]
I am currently running a ghost in a docker container, what I need to solve is that, 
a docker container is designed as an one-time-use instance, so I mounted a folder in the docker host for ghost contents, while the config.js file is in the root folder of ghost, it means I need to config the mail settings every time I runs a new ghost docker instance, that's foolish.....
So I wander if there is any means we can switch the config.js file to content folder (there is a config.js file there too...don't know why) for ghost to use as every setting running ?

**Comment by kevinansfield** [comment]
The `config.js` file is in a fixed location and can't be changed, however there are a number of ways to provide config to docker applications, the simplest is using your Dockerfile to move/copy the config file into the right place or to write the config. `config.js` is also a standard JS file so you are free to read ENV vars or do anything else to obtain config info that is stored elsewhere. A google search for "docker application config" should return a number of useful resources.

If you need any further help please head over to #help on our [community slack channel](https://ghost.org/slack/), we use Github for tracking bugs and core development and so don't offer support or installation help here.
