### ISSUE TITLE
0.9.0 Beta 2 - Ready for testing

### ISSUE THREAD

**Issue by kevinansfield** [TryGhost/Ghost#6997]
# Beta Release Notes

There is now a [second beta of 0.9.0](https://github.com/TryGhost/Ghost/releases/tag/0.9.0-beta.2) published and ready for testing.

If you are able to do some testing, this would be much appreciated. *REMEMBER:* Make a backup first!

If you find any bugs, please raise them as separate issues according to the contributing guidelines

If you complete successful testing, please let us know by adding a comment here detailing what you tested and on what environment, covering relevant things like OS, browser, prod/dev mode, database (sqlite, mysql, postgres), server timezone, blog timezone etc.

*Upgrade note:*
*If you are upgrading from any previous version of Ghost and you use `npm@2.x` you will need to delete your `node_modules` directory before running `npm install` - see the [comment below](https://github.com/TryGhost/Ghost/issues/6997#issuecomment-226190914) for more details.*

## Some important areas for testing:

Aspects of Ghost not often used during development:

- production environment
- MySQL, Postgresql
- Ghost as npm module
- the upgrade process

Important things that have changed:

### Scheduled Posts

It's now possible to set a future publish date when creating a post and schedule it to be published at that time. When a scheduled post is published it triggers all of the usual publish workflow so Slack notifications and so on will all work as if you clicked Publish at the scheduled time.

Please test all aspects of this and let us know if it works, doesn't work, if there's UI that's confusing, etc.

### Internal Tags

Internal Tags have been added as a new labs feature. If you create a tag that is preceded by a `#` (e.g. `#needs-review`) then it will be marked as "internal".

- Internal tags will not be output anywhere on the front-end and they will not have a tag page
- Posts in the admin content screen will have their internal tags highlighted, this is useful for building some basic workflow where you could use tags such as `#WIP`, `#needs-review`, `#ready-to-publish`, etc.
- It's possible to request internal tags via the API and the `{{get}}` helper so that you can use them in the front-end to apply different formatting or behaviour to posts with an internal tag

### Migration to convert all datetimes in the database to UTC

In order to support customisable timezones and post scheduling this release contains a migration that will update all datetimes stored in the database to UTC. If your server timezone is already set to UTC there should be no change.

Please check your database before and after upgrading to ensure that the migration is successful.

- **sqlite3:** should already use UTC timestamp, after the migration you should see the same times but in `YYYY-MM-DD HH:mm:ss` format
- **postgres:** the migration script is not executed at all, you should see no change in the stored times
- **mysql:**  you should see the times change to UTC. For example if your server timezone is set to EST (UTC -5) then the times in your database after the migration should be 5 hours later.

### Timezone support

It's now possible to set the timezone of your blog - this should finally fix the "I posted at 3AM this morning but my post says says it was published yesterday" bugs.

There is now a dropdown in the general settings screen of the admin where you can choose the timezone you want your blog to be in. Please test changing this and ensuring that the dates/times displayed on your blog front-end and in the admin content screen/editor are what you expect.

**Comment by acburdine** [comment]
Something to note is that if you are upgrading from anything below this, and you use npm@2, you will likely have to clear out your node_modules folder. This is due to a bug where Ghost's pinned version of lodash is at version 4, and Bookshelf's is at version 3. On `npm install`, unless the node_modules folder doesn't exist, bookshelf will be forced to use lodash 4, which breaks it.

This should be fixed in the actual release; however, it can at the moment cause issues.

**Comment by kevinansfield** [comment]
Thanks @acburdine, I've updated the issue and release text to mention that.

**Comment by qianduan** [comment]
```
<aside class="read-next">
    {{#next_post}}
    <a class="read-next-story {{#if image}}" style="background-image: url({{image}}){{else}}no-cover{{/if}}" href="{{url}}">
        <section class="post">
            <h2>{{title}}</h2>
            <p>{{excerpt words="19"}}&hellip;</p>
        </section>
    </a>
    {{/next_post}}
    {{#prev_post}}
    <a class="read-next-story prev {{#if image}}" style="background-image: url({{image}}){{else}}no-cover{{/if}}" href="{{url}}">
        <section class="post">
            <h2>{{title}}</h2>
            <p>{{excerpt words="19"}}&hellip;</p>
        </section>
    </a>
    {{/prev_post}}
</aside>

```

the `prev_post` and the `next_post` does not works, it output the last article in any post by `next_post`, the `prev_post` output nothing.

yeah, I use the default casper template.

**Comment by gdjam** [comment]
how to upgrade from 0.7.8 the 0.9.x ? 

i've tried to import the data of 0.7.8 to this version, but failed~

thanks~

**Comment by kevinansfield** [comment]
@gdjam you should follow the usual upgrade procedure outlined in http://support.ghost.org/how-to-upgrade/

**Comment by gdjam** [comment]
@kevinansfield still failed the same~

**Comment by ErisDS** [comment]
@gdjam Could you please post some details of what you did and how it failed? Thanks 👍

**Comment by gdjam** [comment]
[my site](http://www.pickvox.com)  is running in the `0.7.8`, and i export the data, download `0.9.0 Beta 2`, use `npm install --production` to install the modules, and `npm start --production` running the same config like `0.7.8`, then try to import the data, but show `Import Fail`~

thanks~

**Comment by kevinansfield** [comment]
@gdjam you'll need to follow the [upgrade instructions](http://support.ghost.org/how-to-upgrade/) rather than exporting from an old version and importing into a new version. The upgrade process itself runs database migrations to ensure that your data is updated correctly

**Comment by kirrg001** [comment]
@gdjam I've tried to reproduce why your import failed, but i couldn't so far.

This is what i did (maybe you can see a difference to what you did)
1. started a Ghost blog with version `0.7.8`
2. exported blog as `json` file
3. download `0.9.0 Beta 2`
4. ensure i have a config file from Ghost version `0.7.8`
5. `npm install --production`
6. start Ghost blog with version `0.9.0 Beta 2` `npm start --production`
7. navigate to `/ghost` to signup (because database is empty)
8. click labs on the same browser tab and import the `json` file

Here are some questions, which could maybe help us to figure out why your import failed:
1. What database are you using?
2. When you start Ghost `0.9.0 Beta 2` with `npm start --production` are you able to copy the error here when your import fails?

**Comment by gdjam** [comment]
@kirrg001 yes, these were what i did before, and i use sqlite in local dev-env, and the browser show the error message: `Failed to load resource: the server responded with a status of 413 (Request Entity Too Large)     http://localhost/ghost/api/v0.1/db/`

**Comment by kirrg001** [comment]
@gdjam Do you have a nginx running?

**Comment by gdjam** [comment]
@kirrg001  yes, the nginx was running for the proxy~

**Comment by kirrg001** [comment]
@gdjam Ok then the error is served from nginx. You need to configure nginx to allow bigger file uploads.
[example how to increase nginx filesize upload](http://www.cyberciti.biz/faq/linux-unix-bsd-nginx-413-request-entity-too-large/)

**Comment by gdjam** [comment]
@kirrg001 yes yes, i've made it work! thanks very much !!! 👍

**Comment by kevinansfield** [comment]
Closing now that [0.9.0 has been released](https://github.com/TryGhost/Ghost/releases/tag/0.9.0).
