### ISSUE TITLE
{{url}} prints "Invalid date" on preview

### ISSUE THREAD

**Issue by mmiszy** [TryGhost/Ghost#6999]
### Issue Summary

When I open preview of a post, the `{{post.url}}` contains very weird string eg.:
`/Invalid date/Invalid date/Invalid date/dsadsa/`. The `{{url}}` helper also prints the same.

I've discovered this because I had some troubles with invalid URLs in Disqus. Apparently once the post preview is opened, Disqus caches this invalid URL and uses it even after the post is published.

I've managed to overcome this problem by conditionally excluding Disqus when post is not published: `{{#if published_at}}`, however I'm sure this is a bug and it should be fixed somehow.

### Steps to Reproduce

1. Add `{{post.url}}` somewhere in your post template Handlebars file.
2. Create a new post, don't publish, just click "preview".
3. There you go.

Expected output: Not really sure about that, either empty string or a link to the post preview (UUID). Up for discussion.

### Technical details:

* Ghost Version: 0.8.0.
* Node Version: 4.3.1
* Browser/OS: OS X / any browser
* Database: sqlite3

**Comment by kirrg001** [comment]
Hey @mmiszy
Thanks for the bug report - I will fix this bug next week. 

If date permalinks are enabled and no published date available, we could generate the url based on today.

**Comment by mmiszy** [comment]
Thanks for quick response! This will certainly fix unexpected output from `{{url}}`.

However, the URL-caching issue still remains. Currently I'm using conditional `{{#if published_at}}` but it doesn't feel right – do you think it would be possible to add some kind of a Handlebars helper to detect whether post is being previewed or is published?

**Comment by kevinansfield** [comment]
@mmiszy the preview is designed to be as close to real-life as possible so there are no easy hooks to manipulate the output when in preview mode at the moment. For now I would suggest if you have external services that will cache things when you visit pages that you block them from doing that on `/p/*` urls

**Comment by mmiszy** [comment]
Sounds reasonable. Thanks a lot!
