### ISSUE TITLE
Sandstorm Vagrant Package

### ISSUE THREAD

**Issue by MVprobr** [TryGhost/Ghost#7011]
Good afternoon,

Today I would like to present the Sandstorm, since I met I realized that would be the future. Sandstorm is an open source operating system for personal and private clouds, easy to deploy and manage apps.
And I believe that with community efforts can easily launch the package.

Some interesting links:
Link to the Sanstorm - https://sandstorm.io/
Link to the Sandstorm Vagrant SPK documentation - https://docs.sandstorm.io/en/latest/vagrant-spk/packaging-tutorial/

Some tasks need to be completed to function. As:
- Unique Login with Sandstorm ( https://docs.sandstorm.io/en/latest/developing/auth/ )
And some others that we can start to discussion here.

In return Sandstorm offers Ossis which is the Sandstorm hosted on their server, we can use to center the community.

What do you think about?

**Comment by acburdine** [comment]
Hey @mvprobr, this isn't the place for this :smile:. This issue tracker is for problems with the Ghost blog software.
