### ISSUE TITLE
Use `ember-ajax` mixin to replace Ember Data networking

### ISSUE THREAD

**Issue by kevinansfield** [TryGhost/Ghost#7014]
Now that https://github.com/ember-cli/ember-ajax/pull/114 has been merged it looks like we will soon be able to rely on [ember-ajax](https://github.com/ember-cli/ember-ajax/) for both Ember Data networking as well as one-off ajax requests. This is quite exciting as it will open the doors for unified error handling across all areas of the client.

This is a provisional issue to act as a reminder to look at this once a new `ember-ajax` release is available.

- [ ] use the [ajax-support mixin](https://github.com/ember-cli/ember-ajax/blob/master/addon/mixins/ajax-support.js)
- [ ] ensure that our auth headers work across the board
- [ ] re-visit all of our error handling to unify/simplify wherever possible

**Comment by Baltazore** [comment]
I am curious, why it's better than standard EmberData networking?

**Comment by kevinansfield** [comment]
They are both wrappers around jQuery's `ajax` function but they both have different error handling methods and error objects plus you need to hook into both if you want to do anything with the requests/responses (e.g. inject auth headers).

We use `ember-ajax` because we make quite a few requests outside of Ember Data, by using `ember-ajax` inside Ember Data we'll avoid duplication and the need to handle the two types of error objects.

**Comment by acburdine** [comment]
Once TryGhost/Ghost-Admin#198 is merged this issue is unblocked 😄
