### ISSUE TITLE
Proxy with mod_proxy not working as expected.

### ISSUE THREAD

**Issue by bweston92** [TryGhost/Ghost#7024]
### Issue Summary

A summary of the issue and the browser/OS environment in which it occurs. 

Read steps to reproduce you'll get the gist.

### Steps to Reproduce

1. Install blog at version `0.8.0`
2. Change configuration url to https://domain.co.uk/blog/ 
3. Run blog.
4. Setup apache proxy.
5. Goto https://domain.co.uk/blog/ 
6. Redirects you to https://domain.co.uk/

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

I expected to see the web page.

### Technical details:

Logs:
```
Your blog is now available on https://domain.co.uk/blog/ 
Ctrl+C to shut down
192.168.106.2 - - [22/Jun/2016:14:07:12 +0000] "GET /blog/ HTTP/1.1" 301 100 "https://domain.co.uk/previous" "Mozilla/5.0 (X11; Fedora; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.79 Safari/537.36"
```

Apache proxy config:
```
RewriteCond %{HTTPS} !=on
RewriteRule ^/?(.*) https://%{SERVER_NAME}/$1 [R,L]

ProxyRequests On
ProxyPreserveHost On

ProxyPass /blog http://127.0.0.1:2368/blog
ProxyPassReverse /blog https://domain.co.uk/blog
```

* Ghost Version: 0.8.0
* Node Version: 4.4
* Browser: Chrome 51
* Server OS: Debian
* Database: Not relevant.

**Comment by acburdine** [comment]
Hey @bweston92, sorry to hear you're having trouble!

If you wouldn't mind looking, there's [this article](https://www.allaboutghost.com/how-to-proxy-port-80-to-2368-for-ghost-with-apache/) which might have a solution to your issue. (I think you may have an issue with your rewrite rules).

However, if that doesn't work, would you mind dropping by our [slack](https://ghost.org/slack/) channel and asking this there? We can provide better support there than in the github issue tracker, which is for tracking issues with Ghost itself. Thanks! 😄
