### ISSUE TITLE
Bug: text automatically dissapears or change when edit tag description

### ISSUE THREAD

**Issue by manhhailua** [TryGhost/Ghost#7031]
### Issue Summary

I'm trying to edit my tab description but my Ghost Blog keep make some letters of my text dissapeared or transformed.

### Steps to Reproduce

1. Go to http://your.blog/ghost/
2. Access `Tags` menu
3. Create a new tag with description:
- _"{input}" => "{result}"_
- "Mảng là một tập hợp các phần tử cố định có cùng kiểu, được lưu trữ liên tiếp trong các ô nhớ. Kiểu của phần tử có thể là: ký tự, số, chuỗi ký tự" => "Mảng là một tập hợp các phần tử cố định có cùng kiểu, được lưu trữ liên tiếp trong các ô nhớ. Kiểu của phần tử có thể là: ký tự, số, chuỗi ký t"
- "Câu lệnh điều kiện hay biểu thức điều kiện (khoa học máy tính) là câu lệnh nhận một giả thuyết có thể đúng (true) hoặc sai (false) để thực hiện hệ quả" => "Câu lệnh điều kiện hay biểu thức điều kiện (khoa học máy tính) là câu lệnh nhận một giả thuyết có thể đúng (true) hoặc sai (false) để thực hiện hệ qu��"
- "String là một thuật ngữ tin học, có nghĩa là "chuỗi", một kiểu dữ liệu trong ngôn ngữ lập trình - định nghĩa các giá trị chứa các ký tự mô phỏng chữ viết" => "String là một thuật ngữ tin học, có nghĩa là "chuỗi", một kiểu dữ liệu trong ngôn ngữ lập trình - định nghĩa các giá trị chứa các ký tự mô phỏng chữ vi��"

### Technical details:

* Ghost Version: 0.8.0
* Node Version: 4.4.5
* Browser/OS: Chrome
* Database: MySQL 5.5.50

**Comment by kirrg001** [comment]
Hey @manhhailua. Sorry to hear you are having trouble.
I've tried to reproduce it, but i wasn't able to. 

Maybe it's related to #5945, but it's just an assumption.

**Comment by dbalders** [comment]
@manhhailua hey, I haven't been able to reproduce this either. Is it still happening for you? Do you have any ohter details that may help?

**Comment by manhhailua** [comment]
@kirrg001 @dbalders : Sorry you guys for my late reply. The prolem may be caused by my language. I tried to reproduce it several times but the problem was gone. I have no idea why!
