### ISSUE TITLE
access_token not successful

### ISSUE THREAD

**Issue by wangtubs** [TryGhost/Ghost#7037]
### Issue Summary

I try to get the access_token of ghost，but always failed.
```
import requests
url = 'http://45.32.56.57:2368/ghost/api/v0.1/authentication/token'
param = {
	"Content-Type":"application/x-www-form-urlencoded",
	#"grant_type":"password",
	"username":"",
	"password":"",
	"client_id":"ghost-admin",
}
d = requests.post(url,data=param)
print d.content
```
output:
{"errors":[{"message":"No username.","errorType":"BadRequestError"}]}

* Ghost Version: 0.8.0
* Node Version: 0.12.14
* Browser/OS: windows 7

**Comment by sebgie** [comment]
The error says that the username is missing from your request which I can confirm by looking at the code? In addition to that, `grant_type` and `client_secret` have to be sent to successfully request an access token. See http://api.ghost.org/docs/client-authentication for details.

Github is our bug tracker, if you have trouble after sending a correct request, please swing by our [slack](https://ghost.org/slack) channel and ask there. We can provide better support and figure out what is going on there :).
