### ISSUE TITLE
Need a `stop` method defined in package.json, missing for systemctl stop (systemd)

### ISSUE THREAD

**Issue by davidmcl** [TryGhost/Ghost#7046]
### Issue Summary
No `stop` method defined in package.json

### Steps to Reproduce

1. Use systemd for starting Ghost as a service
2. use the sample service definition from your 
[ghost.service](https://github.com/TryGhost/Ghost-Config/blob/master/systemd/ghost.service) as a template

The service definition indicates a stop method;
`ExecStop=/usr/bin/npm stop --production`

running `systemctl stop ghost` *will* stop the service -- but that's due to the command failing because it's missing and abnormally terminates the service.

![ghost_fail](https://cloud.githubusercontent.com/assets/2047925/16417272/9b82d5c8-3d0a-11e6-806f-1a503f01ae4e.PNG)

### Technical details:

* Ghost Version: 0.8.0
* Node Version: 4.4.6
* Browser/OS: CentOS 7
* Database: sqllite

**Comment by acburdine** [comment]
@davidmcl The inherent issue with this is that any sort of stop command is dependent on what you use to run Ghost.

Example: If you just run `npm start --production` inside of a shell, then ghost will run until you hit ctrl-c or exit the terminal. If you run Ghost using `pm2`, the stop command is `pm2 stop <ghost name>`. Using forever, it's similar to PM2 I believe.

The way Ghost, and the way Node works in general, doesn't really allow for this sort of command. If you swing by our [slack channel](http://ghost.org/slack) there might be someone who has gotten it working with systemd.

**Comment by acburdine** [comment]
**EDIT** If you want to, open an issue on the Ghost-Config repository. It belongs there IMO, because that's where the issue lies.
