### ISSUE TITLE
Broken permalink with markdown back-ticks

### ISSUE THREAD

**Issue by ajzawawi** [TryGhost/Ghost#7054]
### Issue Summary
Post title allows markdown back-ticks which ends up breaking the permalink

### Steps to Reproduce
1. Click on "New Post"
2. Include markdown back-ticks in post title such as - `this` is a blog post
3. Click on "Publish Now"
4. The new post will be published
5. Click on the post's link, it will give a 404

### Live Example
http://selftaughtdeveloper.io/%60this%60-is-an-example-of-the-markdown-issue/

### Suggestion
Inexperienced users may not understand why the post is not displaying
Perhaps, sanitize the post title or add a warning message

### Technical Details
Ghost version: 0.7.1
Browser/OS: Chrome 51.0.2704.103 (64-bit) on Mac OS X

**Comment by kirrg001** [comment]
@ajzawawi Thanks for reporting and taking time. This bug is already fixed in `0.8.0`.
You could update your Ghost Version: http://support.ghost.org/how-to-upgrade/
