### ISSUE TITLE
The letters are disappearing when mouse over on dashboard [font-color same as the bg;simple css fix]

### ISSUE THREAD

**Issue by abdullah2891** [TryGhost/Ghost#7065]
Username button. When I am moving the mouse over the button, the letters are disappearing in the button(because  :hover is set to blue which is identical to the color of the button). 

May be just change the button color? 

1) Browser Mozilla Firefox/windows 10

**Comment by ErisDS** [comment]
Hi @abdullah2891, sorry to hear you're having trouble. Could you provide a screenshot to explain what it is you're seeing?

**Comment by abdullah2891** [comment]
Notice top right button. the letters are disappearing when mouse over
![signinpage](https://cloud.githubusercontent.com/assets/6827586/16789649/6c184ca4-487d-11e6-9f95-c05ace683f51.png)

**Comment by ErisDS** [comment]
Hey @abdullah2891 thanks for providing the screenshot. Super helpful 👍 

What you're looking at is Ghost.org - that's our marketing website and not part of the Ghost software. It's in the process of being completely replaced, so we're not going to look at fixing this just now. Instead, you should see a shiny new version very soon 😁
