### ISSUE TITLE
[Proposal] Content path separation

### ISSUE THREAD

**Issue by hiendv** [TryGhost/Ghost#7067]
I think that `apps`, `data`, `images` and `themes` should be separated. From my point of view, it would be greate if `apps`, `data`, and `images` could be moved outside while keeping the `themes` directory.

**Comment by acburdine** [comment]
Hey @hiendv, it would be great if you could provide some reasoning as to why you think the folders should be split out :smile: Making that kind of decision requires lots of changes and it would be good to have more to this request.

Closing this for now as we try to keep the GitHub issue list specifically for actual bugs with the software. If there is more reasoning or more people desire this, it can be re-opened later :wink:

**Comment by hiendv** [comment]
Thank you @acburdine for spending time on this. I'm not an English native speaker so it may sound confusing. Sorry mate :smile: 
I think `contentPath` should be divided into `resources` and `storage` because of their nature and functionality.
- `storage` : `apps, data, images`
- `resources`: `themes`

People tend to move the `storage` outside of Ghost while `resources` often remains inside.
I feel a little awkward to update the `git submodules` e.g. `Casper`,  just because of moving my data somewhere.

I know it would be a breaking change.
