### ISSUE TITLE
Ghost API misreads specific types of get requests

### ISSUE THREAD

**Issue by Goldsmith94** [TryGhost/Ghost#7075]
### Issue Summary

I'm using node.js with require http on an Ubuntu 14.04 to do my get requests and found that on the blog I'm transferring from wordpress where we have slugs of articles such as 2010-fund and 12-hours-in-abu-dhabi etc. I got an error when querying the Ghost API. When paginating weirdly enough some pages were rendering fine, while some weren't, and this I ended up identifying was because it was only on some pages I had this specific type of request.

It is when I use filter=slug:2010-fund, but in general filter=slug:{number}-{any text what so ever}

I will get the query error that it expected an and, or, right parenthesis or right bracket, but got a not (the dash '-' is the not operator).

### Steps to Reproduce

It seems like you can reproduce it with any query of the pattern above, but for a specific, you can write a query with the parameter 
filter=slug:123-text
and it will give you an error while changing it to
filter=slug:123_text or filter=slug:123text
or something similar where the first bit is not a pure number and the next bit is a hyphen '-'.

### Technical details:

* Ghost Version: 0.8.0
* Node Version: Fails both with 0.10.45 and 5.0.0
* Browser/OS: Linux Ubuntu 14.04
* Database: Default database, SQLite

**Comment by dbalders** [comment]
I was able to replicate this

**Comment by kirrg001** [comment]
Hey @Goldsmith94 
Can you try to escape the whole string?
`'slug:\'123-test\''`

**Comment by Goldsmith94** [comment]
Thanks that works.

If I may ask, is this the correct syntax I should've been using anyway? Or is it something Ghost should support. I'm a fairly new web developer so just curious. I'll of course use this now as it'll make my code work, but I guess I'm also just curious if this is just a temporary fix or if it's something the Ghost API will support in the future.

**Comment by kirrg001** [comment]
Closing in favour of https://github.com/TryGhost/GQL/issues/19.
