### ISSUE TITLE
Cannot install 

### ISSUE THREAD

**Issue by etiennea** [TryGhost/Ghost#7079]
33624 error ghost@0.8.0 preinstall: `npm install semver && node -e "require('./core/server/utils/startup-check.js').nodeVersion()"`
    33624 error Exit status 254

What could be the problem?

**Comment by sakulstra** [comment]
I think it's related to #6691 - are you running npm v3?

**Comment by kevinansfield** [comment]
Hey @etiennea, sorry to hear you are having trouble installing. Unfortunately we can't offer support here on Github - it's used only for tracking bugs and current feature development.

Please head over to our [slack channel](https://ghost.org/slack/) where it's possible to get community support.
