### ISSUE TITLE
Is there any way to enable showdown extensions?

### ISSUE THREAD

**Issue by adamcavendish** [TryGhost/Ghost#7080]
I know that you might hope to refine the editor before enabling any of the extensions not supported by Ghost right now.

However, it seemed that some users, including me, really need some of the features like TOC and markdown tables. We might not really need a refined editor for the combo key strokes for generating markdown tables or one hit update for the TOC. We just need that it'd be rendered :cry: .

Is there any way to just enable the rendering?

**Comment by kirrg001** [comment]
Hey @adamcavendish, Unfortunately we can't offer support here on Github - it's used only for tracking bugs and current feature development.

Please head over to our [slack channel](https://ghost.org/slack/) where it's possible to get community support.
