### ISSUE TITLE
Can't admin after pull changes in theme/ and config.js on Droplet+Ghost 

### ISSUE THREAD

**Issue by galarchenko** [TryGhost/Ghost#7082]
When I git pull changes in theme/ and config.js considering that all folders are untouchables ( content/data/, etc ). I get http://mydomain.com/ghost/signin/ with my user and password and I can't get in. It shows me this:

`insert into "accesstokens" ("client_id", "expires", "token", "user_id") values (1, 1468130777880, 'qWYHWE1c6bR1tVH2wg4oi7XHk9fVyej4iHEgfElwGRxF6abr1DMA6xcCFfTIJfmyZPoZNv2oagY77YcV7fbB3dztruIDeyq1g5i4SCVzdCblreizpJ0qF2jUNJi2D1QWnKnOvBT4Up9o2lPkwL9fCYL4spWgU4SG7d3lhp7UoNFHLr52ne4ZVrebTFoxI2jBlIDMtYdztixJI8BfUS0KLnhuw9bYLrJ0Zyi3pMFG0msRwxeYtEuq3MknZAQ5L8k', 1) - SQLITE_READONLY: attempt to write a readonly database`

But I didn't touch the content/data/*.db files

Before I pull these changes I had register my email and password admin.

So what's the problem?

### Technical details:

* Ghost Version: 0.8.0
* Node Version: 4.4.4
* Browser/OS: 51.0.2704.103 (64-bit)
* With One Click App in Digital Ocean

**Comment by ErisDS** [comment]
Hi @galarchenko, sorry to hear you're having trouble. 

The best way to get support for Ghost is to head on over to slack - https://ghost.org/slack/ - and post in the #help channel (in fact I think I've seen you there). The Ghost community is on hand there and able to provide help, which we're not able to do here in the GitHub bug tracker.
