### ISSUE TITLE
Text in Casper antialiased sometimes, but sometimes not

### ISSUE THREAD

**Issue by kostyakoz** [TryGhost/Ghost#7085]
### Issue Summary

Sometimes text in my blog based on default non-modified Casper theme is antialiased, and sometimes not. There are difference in browsers, I want to finally remove antialiased text.

### Steps to Reproduce

I think picture on page will reproduce this problem, pages without images display text normal, without antialiasing.

![screen shot 2016-07-11 at 16 30 36](https://cloud.githubusercontent.com/assets/1935229/16732439/3ea4f244-478e-11e6-89f6-ac52c43d5052.png)
![screen shot 2016-07-11 at 16 30 46](https://cloud.githubusercontent.com/assets/1935229/16732441/415e4f26-478e-11e6-811e-331359857ed0.png)
![screen shot 2016-07-11 at 16 31 27](https://cloud.githubusercontent.com/assets/1935229/16732442/42a25562-478e-11e6-812a-4d64b65d0ef1.png)

### Technical details:

* Ghost Version: 0.8
* Node Version: 4.2.6
* Browser/OS: Chrome, Safari on OS X 10.11
* Database: SQLite, default

**Comment by acburdine** [comment]
@kostyakoz would you mind opening up this issue on the https://github.com/TryGhost/Casper repository? I feel like this belongs there.... :smile:
