### ISSUE TITLE
Switch recommended Node.js version from 0.10x to v4 LTS (argon)

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#7098]
Since Ghost-ception, we have recommended running with Node.js version 0.10. We've always tried to recommend using the very latest 0.10.x, but always the 0.10 branch.

There was good reason for this: it is what we use in production on Ghost(Pro) and therefore we know, categorically, that it works and is stable for production use for 10000s of blogs and large volumes of traffic 😁 

Node.js v4 has been in LTS since 1st October 2015, however we originally had concerns about upgrading as there were mixed reports in the Node.js community around speed & memory changes. In short, from what was reported it seemed that Ghost would not benefit from the speed improvements, and would likely suffer increased memory footprints due to the changes in the way the garbage collector works - i.e. we'd lose out twice 😞 

Nonetheless, Node.js 0.10.0 will [no longer be supported from 1st October 2016](https://github.com/nodejs/LTS#lts_schedule), and so we need to upgrade and figure out these issues if they exist. Therefore, over the last few months, we have been switching all of our internal systems over to use Node.js v4 LTS (argon), currently v4.4.7, and monitoring the impact.

We're extremely happy to report that all Ghost(Pro) blogs are now running Node.js v4 LTS, are stable, fast, and we are seeing reduced memory footprints 🚀 💃 

At this point, we are ready to switch our **recommendation** from Node.js 0.10.x to v4 LTS (argon).

This means we need to:
- [x] Use Node.js v4 as the default environment for tests on travis
- [x] Update all of our support docs on support.ghost.org
- [x] Update the README and any other references in GitHub
- [x] Publish a blog post documenting this change & outlining our commitment to Node.js LTS

## Ghost's commitment to LTS:

Note, this issue is talking about switching our **recommended** version. NOT dropping support for 0.10.x.

Ghost is committed to following the Node.js LTS schedule: https://github.com/nodejs/LTS#lts_schedule and our intention is to follow it as closely as possible.

We will drop support for running Ghost with Node.js 0.10 on 1st October 2016. At the same time, we will add official support for the new v6 LTS. We will continue to support Node.js 0.12 until 31st December 2016. We intend to publish releases which add/remove support for LTS on or as close to the scheduled date as we can.

As part of our commitment to supporting Node.js v6 when it goes into LTS in October, I recommend that at the same time as we switch to using Node.js v4 as our default test environment, we should also add Node.js v6 as an allowed failure:

- [x] Add Node.js v6 to the build as an allowed failure

**Comment by halfdan** [comment]
May I dibs the technical part here?

**Comment by ErisDS** [comment]
@halfdan sorry I've already done it! Just raising the issue to mark the PRs against and to explain the significance 😉

**Comment by halfdan** [comment]
@ErisDS Well, my job here is done then :D

**Comment by ErisDS** [comment]
All done now 😁 
https://dev.ghost.org/node-4/
