### ISSUE TITLE
Unable to setup ghost on ubuntu desktop 16.04 x64 

### ISSUE THREAD

**Issue by kskarthik** [TryGhost/Ghost#7105]
I tried installing ghost on my pc. I followed the steps here>. I got the following error. Please help.

![ghost](https://cloud.githubusercontent.com/assets/11899221/16917577/c9d37138-4d1f-11e6-943e-05f9d7dbc1aa.png)

**Comment by ErisDS** [comment]
Hi @kskarthik, sorry to hear you're having trouble. As mentioned in the readme & contrib guide, if you have questions about Ghost or need help, please head on over to slack - https://ghost.org/slack/ - and post in the #help channel. There you can get help & support from the Ghost community, which we're not able to do here in the GitHub bug tracker.

**Comment by kskarthik** [comment]
I am unable to login to slack :(
