### ISSUE TITLE
Cannot join slack for discussion 

### ISSUE THREAD

**Issue by manV** [TryGhost/Ghost#7109]
### Issue Summary

Cannot join slack for discussion 

### Steps to Reproduce

1. Go to https://ghost.org/slack/ with logging in.
2. Click on open slack button

The spinner just keep spinning
checking in network tab in devtools, it is making two request repeatedly,
one is POST-/slack/invitation which results in {"message": "User already invited."}
other is GET-/slack/invitation/?_{some number} which results in {"message": "Slack token not found"}

### Technical details:
* Browser/OS:  firefox 47.0/Ubuntu 16.04

**Comment by dbalders** [comment]
@manV hey, can you send an email over to support@ghost.org? They can help you with getting into the slack. This is for tracking the issues of the actual Ghost product, so I am going to go ahead and close, but they can help you out.
