### ISSUE TITLE
Invite user modal: Field focus and tabbing

### ISSUE THREAD

**Issue by kevinansfield** [TryGhost/Ghost#7132]
### Issue Summary

When the Invite New User modal opens the Email field does not automatically get focus, also when the email field has focus pressing <kbd>Tab</kbd>  does not select the Role field that is the next logical input.
### Steps to Reproduce
1. Visit the Team page and click the Invite People button
2. Note that the email input is not automatically focused
3. Click on the Email field to give it focus
4. Press <kbd>Tab</kbd>
5. Note that the Role field does not receive focus (if it had focus, pressing <kbd>up arrow</kbd> or <kbd>down arrow</kbd> would cycle through the roles)
### Technical details:
- Ghost Version: master

**Comment by jtordgeman** [comment]
On it

**Comment by iamsk9** [comment]
can i contribute to this issue?

**Comment by isaeef** [comment]
@kevinansfield I am on it .To submit as my first pr

**Comment by whmii** [comment]
Was able to identify the select object has a wrapper `span` element that was given a `tabindex` property for… some reason. What is occurring is the text input is selected, tab is pressed, and the browser focusses on the `span` instead of the select object.

**Comment by Avasse** [comment]
Working on it.

**Comment by Lecodeurfou** [comment]
The line : focusOut=(action "validate" "email"). seems to be the problem here. When we delete it, the tab action goes right to the Email--->Role--->Validation.

**Comment by Lecodeurfou** [comment]
The line : focusOut=(action "validate" "email"). seems to be the problem here. When we delete it, the tab action goes right to the Email--->Role--->Validation.

**Comment by m1guelpf** [comment]
@kevinansfield https://github.com/TryGhost/Ghost-Admin/pull/1020 was merged, can this be closed?
