### ISSUE TITLE
Multiple duplicate server-side alerts are displayed

### ISSUE THREAD

**Issue by kevinansfield** [TryGhost/Ghost#7133]
### Issue Summary

If duplicate errors are provided by the server they are all displayed at once in the client:

![screen shot 2016-07-25 at 11 47 39](https://cloud.githubusercontent.com/assets/415/17099020/960f2264-525d-11e6-94d7-e194df21a8f3.png)

### Steps to Reproduce

1. Visit the team page
2. Invite a user with an e-mail address that is not deliverable, e.g. "test@example.com"
3. Click "Resend" a few times on the new invite
4. Refresh the page

Either we should be preventing duplicate alerts being generated on the server or filtering on the client-side so that we only display one alert instead of many stacked alerts.

### Technical details:

* Ghost Version: master

**Comment by kirrg001** [comment]
I will fix that on the server side.
