### ISSUE TITLE
"Posts per Page" validation causes endless spinner

### ISSUE THREAD

**Issue by kevinansfield** [TryGhost/Ghost#7139]
### Issue Summary

If you set the "Posts per Page" setting to an invalid value and try to save the save button becomes an endless spinner.
### Steps to Reproduce
1. Visit the general settings page
2. Enter `0` as the number of posts per page
3. Press save

No inline-validation is displayed and the save button never stops spinning
### Technical details:
- Ghost Version: master

**Comment by ErisDS** [comment]
Closing as we no longer have this component 😁
