### ISSUE TITLE
Focusing URL field of the "edit nav item" row causes validation errors when saving

### ISSUE THREAD

**Issue by kevinansfield** [TryGhost/Ghost#7140]
### Issue Summary

When editing the blog's navigation, if you click in the URL field of the last/new item and then try to save that entry is marked as invalid meaning you need to fully fill it in before saving.

### Steps to Reproduce

1. Visit the navigation settings screen
2. Add some items or edit existing items
3. Click in the URL field of the last item
4. Click save

Validation is now triggered for the apparently "empty"/"new" item meaning you need to fully fill it in before you can save your other changes.

![nav-validation](https://cloud.githubusercontent.com/assets/415/17109938/18124546-5292-11e6-99aa-4f6691ce376a.gif)

### Technical details:

* Ghost Version: master

**Comment by kevinansfield** [comment]
This should be solvable by checking if the item is new and if it's label is blank with a URL that matches the base url - if all of those are true then don't mark the anything as invalid.

**Comment by acburdine** [comment]
So the fix here has introduced another bug 😞 

After clicking into an existing nav item url field, not changing anything, and then trying to save, the error "you must specify a URL or relative path" appears.

Repro steps:
- Settings > Navigation
- Click into the "Home" URL field that's already there
- Without editing the field, press ctrl/cmd+s or click the "save" button
- Observe: the row you just clicked now has a validation error for the URL field

This only happens with already saved items.
