### ISSUE TITLE
Hidden validation errors in tag's meta screen disguises failed saves

### ISSUE THREAD

**Issue by kevinansfield** [TryGhost/Ghost#7141]
### Issue Summary

A summary of the issue and the browser/OS environment in which it occurs. 
### Steps to Reproduce
1. Visit the tags screen
2. Create or edit a tag and switch to the Meta Data panel
3. Enter a title that is > 150 chars
4. Click the `<` arrow to go back to the main tag form
5. Change the tag title and then click in another field, note that everything appears to have worked and the tag is updated
6. Click the content screen or another settings screen
7. Click back to the Tags screen, note your Title change appears to have stuck
8. Refresh the page
9. Note that your Title has changed back to what it was previously

The problem is that the invalid data on the hidden Meta Data screen is preventing all saves from working but there is no indication that a save has failed or where the error is occurring. The local data stays in the updated state in the Ember Data store and so it appears that your save worked until something triggers a refresh of all the tags.
### Technical details:
- Ghost Version: master

**Comment by kevinansfield** [comment]
A quick-fix that shouldn't require looking at the design of saving/error notification would be to reset the values of invalid fields when navigating from the Meta Data panel back to the general panel. It may also be beneficial to do the same when switching between tags as that also has the effect of making changes look permanent when they have not been saved.

**Comment by kirrg001** [comment]
As far as i can see, this was fixed for the LTS branch, but not yet for master branch. I moved this issue back to the backlog.

**Comment by ErisDS** [comment]
Is this also only fixed in LTS?

**Comment by kevinansfield** [comment]
Yes, it looks like it was only "fixed" in LTS but the fix wasn't great. It removes the error on the model but doesn't do anything to resolve the UX problem where it looks like a save occurred when it didn't.

There are two options here:
1. Implement a proper fix for the current UI
2. Resolve this as part of the tags screen overhaul that is underway for nested tags

**Comment by ErisDS** [comment]
Closing with `later`, will be reprioritised and reopened later.
