### ISSUE TITLE
Uploading a non-csv file when importing subscribers hangs Ghost

### ISSUE THREAD

**Issue by kevinansfield** [TryGhost/Ghost#7144]
### Issue Summary

The file selector is initially set to CSV-only files but it's easy to override (at least it is in OSX). If you select an image and upload that then the ghost service near enough hangs, each subsequent request takes approx 18sec to respond.

### Steps to Reproduce

1. Enable subscribers in Labs if it's not already enabled
2. Visit the subscribers screen
3. Click the "Import CSV" button
5. Click the upload area to trigger the file select dialog
4. Change the "Format" option from `comma-separated-values` to `All Files` (OSX-only, Windows may have something similar?)
5. Select an image and click "Open"
6. Upload will finish at which point the ghost service will hang, all subsequent requests take a _long_ time to respond

I think there are two parts to solving this:
- [x] Validate file mime type / extension client-side before uploading (https://github.com/TryGhost/Ghost-Admin/issues/214)
- [x] Validate file mime type / extension on the server before trying to process (prevents easy DOS)

### Technical details:

* Ghost Version: master
* Node Version: 4.4.7
* Browser/OS: Chrome/OSX
* Database: sqlite

**Comment by twalling** [comment]
I have a server PR for this but still have to review a couple things regarding the project's guidelines for submitting them since this is my first one. Wanted to mention it in case was going looking to start on this.

**Comment by kirrg001** [comment]
🎉
