### ISSUE TITLE
import fails on many articles 

### ISSUE THREAD

**Issue by jalogisch** [TryGhost/Ghost#7154]
### Issue Summary

When try to import big json files with over 1000 articles it just displays "failed". No meaningful Error is give and no idea how to fix this.

### Steps to Reproduce

1. use https://github.com/weblancaster/nodejs-jekyll-to-ghost to create json from https://github.com/jalogisch/jalogisch.github.com 
2. import the generated in a fresh 0.9 ghost.

### Technical details:

* Ghost Version: 0.9
* Node Version: v4.4.7
* Browser/OS: Safari Version 9.1.2 (11601.7.7)
* Database: sqlite

**Comment by vkandy** [comment]
I just followed the steps to reproduce the issue. It looks like one of your posts has an empty title? Import fails due to a validation error. See details below. 

I was able to import successfully after setting `title` to a non-empty string.

```
{ id: 247,
  uuid: 'e91645a5-947c-4cdd-bcb5-90e8571a9448',
  title: '',
  slug: '268',
  markdown: '\nder pessimist sagt:\n\n> ich sehe immer nur das negative, mir geht es schlecht und die welt ist\ndunkel, böse und gemein\n\nder optimist sagt:\n\n> ich bin gerade sehr nachdenklich, das macht vielleicht das wenige tageslicht\nund die fehlende sonne\n\n{% include JB/setup %}\n\n\n\n\n',
  html: '<p>der pessimist sagt:</p>\n\n<blockquote><p>ich sehe immer nur das negative, mir geht es schlecht und die welt ist\ndunkel, böse und gemein</p></blockquote>\n\n<p>der optimist sagt:</p>\n\n<blockquote><p>ich bin gerade sehr nachdenklich, das macht vielleicht das wenige tageslicht\nund die fehlende sonne</p></blockquote>\n\n<p>{% include JB/setup %}</p>',
  image: null,
  featured: 0,
  page: 0,
  status: 'published',
  language: 'en_US',
  meta_title: '',
  meta_description: null,
  author_id: 1,
  created_at: 1131062400000,
  created_by: 1,
  updated_at: 1131062400000,
  updated_by: 1,
  published_at: 1131062400000,
  published_by: 1 }

ERROR: Value in [posts.title] cannot be blank. 

```

**Comment by jalogisch** [comment]
@vkandy thank you - i had found this by building little chunks to import. As the import was per month ghost was able to display that a title was empty and i found the issue (just a few minutes before!)

thank you, can be closed now

**Comment by vkandy** [comment]
Glad to hear that.
