### ISSUE TITLE
Uploading an image with the same filename as a pre-existing image uploaded during the same month/year results in preview glitch

### ISSUE THREAD

**Issue by kz26** [TryGhost/Ghost#7155]
### Issue Summary

Let's say you upload an image called Capture.PNG in July 2016 (2016/07/Capture.PNG) as part of a post. If you create a second post afterwards in the same month and also upload an image with the same filename, the preview is of the FIRST uploaded image, not the one you just uploaded. If you click delete and re-upload, the preview is correct again.
### Steps to Reproduce

See above.
### Technical details:
- Ghost Version: 0.9.0
- Node Version: 4.4.7
- Browser/OS: Chrome 52
- Database: sqlite

**Comment by ErisDS** [comment]
Really appreciate the detailed report here, however this bug is a bit of an edge-case that hasn't been experienced by enough people to warrant fixing. We're now looking at replacing the editor (See #7429) so I think this can be closed.
