### ISSUE TITLE
Phishing warning

### ISSUE THREAD

**Issue by tuannvm** [TryGhost/Ghost#7156]
### Steps to Reproduce

Ghost v0.7.8 contain this URL, and it's marked as phishing site by Google:
[Image](https://i.imgur.com/U5bRolZ.jpg)
[infected link](https://s3.amazonaws.com/f.cl.ly/items/3I0g431b2b3q00253K1V/d16dc430c9c4f5c09d6ca09be3e5c72fdb21c1ac.png)

### Technical details:

* Ghost Version: 0.7.8
* Node Version:0.10.40
* Browser/OS: Chrome / OSX 10.11

**Comment by X0nic** [comment]
I am also seeing this on 0.7.1

**Comment by infinitysgame** [comment]
I just experienced this too. v0.7.8.

**Comment by acburdine** [comment]
@tuannvm Where did this image show up?

**Comment by tuannvm** [comment]
@acburdine Admin landing page, I suppose. Right after the login I saw that.

**Comment by acburdine** [comment]
@tuannvm ok. Can you try updating Ghost and see if it's still occurring? There was a logo in the nav menu that linked to an AWS image in 0.7 that was removed somewhere down the line.

**Comment by X0nic** [comment]
I think this is the problem line in 0.7.8 https://github.com/TryGhost/Ghost/blob/0.7.8/core/client/app/html/apps.html#L21

Though it still seems to be present in the newer extracted admin client here: 
https://github.com/TryGhost/Ghost-Admin/blob/0.9.0/app/html/apps.html#L21

**Comment by tuannvm** [comment]
Yes, it disappeared after updating to latest version.

**Comment by acburdine** [comment]
@X0nic that apps.html file isn't present in the built client. That apps file is only there for wireframe purposes. It has been removed in the ember raw files 😄 

Closing this as it has been fixed in later versions of Ghost

**Comment by acburdine** [comment]
@X0nic In case you're curious, the line is here: https://github.com/TryGhost/Ghost/blob/0.7.8/core/client/app/templates/components/gh-nav-menu.hbs#L2

and was removed in 0.7.9: https://github.com/TryGhost/Ghost/blob/0.7.9/core/client/app/templates/components/gh-nav-menu.hbs#L2

**Comment by X0nic** [comment]
Thanks for the info @acburdine Ill do an upgrade. :)

**Comment by infinitysgame** [comment]
@acburdine Thanks. :+1:
