### ISSUE TITLE
v0.9.0: {{#get "tags" ...}} stopped returning url and count.posts

### ISSUE THREAD

**Issue by uqee** [TryGhost/Ghost#7170]
### Issue Summary

This code worked well on the ghost v0.8.0:
```
{{#get "tags" limit="all" fields="name,url" include="count.posts" order="count.posts desc"}}
  {{#foreach tags}}
    <li>
      <a href="{{url}}">
        <span>{{name}}</span>
        <sup>{{count.posts}}</sup>
      </a>
    </li>
  {{/foreach}}
{{/get}}
```

Now it returns only tag names. I've read the [summary of valid fields](https://themes.ghost.org/docs/get#section--fields-), which seems to not include urls anymore, but `url` is still included in the [list of attributes](https://themes.ghost.org/v0.9.0/docs/tags#section-list-of-attributes). Also, `count.posts` should work as explicitly mentioned in the [corresponding section](https://themes.ghost.org/v0.9.0/docs/get#section--include-).

### Technical details:

* Ghost Version: 0.9.0
* Node Version: 4.4.3
* Database: sqlite

**Comment by kirrg001** [comment]
Hey @uqee Sorry to hear you're having trouble.

`{{url}}` is a separate template helper. Tag doesn't have a `url` field. So you can simplify this `fields="name,url"` to `fields=name`.

I can confirm there is a bug. The url template helper does no longer return the tag url, because this https://github.com/TryGhost/Ghost/blob/master/core/server/data/schema/checks.js#L6 is no longer true, because the api layer only returns the requested fields (in this case `name`).

**Comment by uqee** [comment]
Thanks for the reply @kirrg001 !
I confirm that `{{url}}` works if `fields="name,slug,description,parent"` is used. Okay, hopefully, it's not a huge overhead, but what about `count.posts`?

**Comment by kirrg001** [comment]
@uqee i can confirm there is another bug for `count.posts`. A quick fix for you is not defining `fields` at all, then you should receive the count.

**Comment by uqee** [comment]
Yep, seems to work fine. Thanks for your help!

**Comment by ErisDS** [comment]
The `url` for a tag page is based on the slug, so if you don't fetch that from the API, the url helper you are using cannot function. 

It is also not possible to fetch any joined data if you restrict the data returned via `fields`. This is expected for now. Supplying `fields` is only for very particular cases where you really only need a limited set of data (e.g. our internal search in the admin panel).
