### ISSUE TITLE
Ghost allows uploading of non-image files in editor

### ISSUE THREAD

**Issue by dungba88** [TryGhost/Ghost#7178]
### Issue Summary

Ghost allows uploading of non-image files in markdown editor, if we rename the image to .png

### Steps to Reproduce

1. Create new post and add an image placeholder
2. Rename a file of any kind (even executable files) to xyz.png and use the placeholder to upload it
3. Verify that the uploaded file is successfully copied to Ghost content folder

I think it's not safe to allow this, as it can cause security breach if combined with other vulnerabilities.

**Comment by kevinansfield** [comment]
Client-side mime type validation was added in https://github.com/TryGhost/Ghost-Admin/pull/214. Some server-side checks were also added in https://github.com/TryGhost/Ghost/pull/7185 but only for the subscribers CSV import.

When we re-visit media management we should probably take a look at a more blanket approach to mime type validation.

**Comment by ErisDS** [comment]
I think we can close this now? 

@dungba88 Best practice for reporting security issues is to follow our security policy as explained here: https://github.com/TryGhost/Ghost/blob/master/SECURITY.md

**Comment by kevinansfield** [comment]
> I think we can close this now?

Agreed, if a vulnerability exists that allows code to be executed then mime checks aren't going to help in any way as it's very possible to embed executable code inside of an image file.
