### ISSUE TITLE
Internal tags are showing up in sitemap.xml

### ISSUE THREAD

**Issue by kevinansfield** [TryGhost/Ghost#7186]
### Issue Summary

After adding internal tags the tag pages for those tags are listed in yoursite.com/sitemap-tags.xml but will return 404s as they do not have public pages.

### Steps to Reproduce

1. Enable internal tags labs feature
2. Add some internal tags
3. Check http://localhost:2368/sitemap-tags.xml
4. See that the internal tag pages are listed

### Technical details:

* Ghost Version: 0.9.0

**Comment by me-benni** [comment]
Do I unterstand correctly that you want to remove the internal tags from the sitemap-page, rather than resolve the 404s?

**Comment by kirrg001** [comment]
@me-benni correct, internal tags shouldn't appear in the sitemap-tags.xml

**Comment by mwakerman** [comment]
Solved here: https://github.com/TryGhost/Ghost/pull/7199#partial-pull-merging

**Comment by kirrg001** [comment]
Need to reopen.

Start the server, go to `tags`, create a new internal tag, navigate to `http://localhost:2368/sitemap-tags.xml` and see the internal tag.

When i restart the server, the internal tag disappears. The xml doesn't get refreshed. I can see a `refreshAll` fn in the Base generator, but this function does not get called.
