### ISSUE TITLE
ghost site crashing 502 BAd Gateway

### ISSUE THREAD

**Issue by xiolo** [TryGhost/Ghost#7190]
Hi

Since I upgraded to Ghost 0.9.0, my site keeps crashing every 16-24h, output of npm-debug.log below:

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'start',
1 verbose cli   '--production' ]
2 info using npm@2.14.12
3 info using node@v4.2.4
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart ghost@0.9.0
6 info start ghost@0.9.0
7 verbose unsafe-perm in lifecycle true
8 info ghost@0.9.0 Failed to exec start script
9 verbose stack Error: ghost@0.9.0 start: `node index`
9 verbose stack Exit status 134
9 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:214:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:818:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid ghost@0.9.0
11 verbose cwd /var/www/redacted/ghost
12 error Linux 3.13.0-71-generic
13 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "start" "--production"
14 error node v4.2.4
15 error npm  v2.14.12
16 error code ELIFECYCLE
17 error ghost@0.9.0 start: `node index`
17 error Exit status 134
18 error Failed at the ghost@0.9.0 start script 'node index'.
18 error This is most likely a problem with the ghost package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     node index
18 error You can get their info via:
18 error     npm owner ls ghost
18 error There is likely additional logging output above.

Restarting the service works fine for a while, and then same crasha  few hours later.

**Comment by acburdine** [comment]
@xiolo Sorry to hear you're having trouble!

Can you please swing by our [slack channel](https://ghost.org/slack) and ask for help there? We can provide better support there than in the Github issue tracker, and if this turns out to be an actual issue with Ghost this issue can be reopened.

Thanks! 😄
