### ISSUE TITLE
posts in front order

### ISSUE THREAD

**Issue by hzb** [TryGhost/Ghost#7192]
ghost version 
0.9 lastest

issues
posts showed in front are order by the time last modified, not by the post date.

**Comment by acburdine** [comment]
@bhua Can you please provide a bit more information about this bug? Are you talking about the post order in the admin client or on the actual frontend of ghost?

Not saying this isn't an issue, but it would be helpful to have more information so we know where to look for the problem 😄

**Comment by ErisDS** [comment]
I can't reproduce this with published posts in the backend, or on the blog. 

My only guess is this is something to do with scheduled posts appearing at the top of the list.  

Just wanted to confirm that posts on blogs are NOT appearing out of order as far as I can tell.

**Comment by bhua** [comment]
@acburdine @ErisDS sorry, i can't reproduce it again, i can tell you the steps i do.

1. there're some posts in my database.
2. in /ghost/24/(the content url), all posts order by post date in backend.
3. update some old posts, such as modify their content.
4. refresh the frontend of ghost, you will see the posts are ordered by modify date, not its post date.

but I try this again, it can't be reproduced again, i will try more, and reopen this issue if it happens again. 

Thanks.

**Comment by kosssi** [comment]
I have the same issue.
How can I change it, you can see here : http://zebra.life 😟

**Comment by kosssi** [comment]
I understand the bug.

All post must be update and after is ok.
I think is date post change on 0.9.0 I migrate my blog last evening ;)

**Comment by hzb** [comment]
@kosssi ok.

**Comment by kirrg001** [comment]
@kosssi does the published date of the old post change?

**Comment by ErisDS** [comment]
@hzb & @kosssi We need more information to understand and reproduce the issue.

As I understand, you're reporting that editing an existing post results in the published date changing? 

To help us reproduce:
- What timezone does your server use?
- What timezone is set in your blog admin panel? Did you change this after upgrading?
- Are dates set correctly when creating new posts?

To help us further, it would be great if you could do some debugging:
- Do the dates look correct for old content in your database?

**Comment by kirrg001** [comment]
@hzb @kosssi It would be great if you could answer the questions above. Thank you!

**Comment by hzb** [comment]
@ErisDS here are answers

- What timezone does your server use?
GMT+8

- What timezone is set in your blog admin panel?
GMT+8

- Did you change the timezone setting after upgrading?
NO, it shows GMT+8 in admin CP

- Are dates set correctly when creating new posts?
YES.

- Do the dates look correct for old content in your database?
Sorry, I can't check it now, because I can't reproduce it again.

Any thing more needs I do?

**Comment by kirrg001** [comment]
Good to hear that you can't reproduce this issue anymore.
We will wait for further steps until someone experiences this issue again.

**Comment by reupen** [comment]
I'm actually having this problem as well. All posts were created pre-0.9.0. I updated a post that was about seventh down on the front page after the 0.9.0 upgrade and it moved to the top of the list on the public blog only (not in the admin section).

The publish date of the post did not change.

The server uses the UTC, time zone the blog uses London (changed from UTC, after the post edit).

**Comment by kirrg001** [comment]
@reupen Sorry to hear that. 
Sounds like the database migration wasn't successful. 
Do you remember if you had an error while updating from `0.8.0` to `0.9.0`?

**Comment by reupen** [comment]
Hi,

I don't recall any errors, but could check the logs later.

I saw in the 0.9.0 beta 2 release notes it said that:
> In order to support customisable timezones and post scheduling this release contains a migration that will update all datetimes stored in the database to UTC. If your server timezone is already set to UTC there should be no change.

My server is set to UTC, but from the above it looks like the timestamps do indeed need migrating.

I had a look at the code and came across this:
https://github.com/TryGhost/Ghost/blob/master/core/server/data/migration/fixtures/006/01-transform-dates-into-utc.js#L41

I'm not familiar with the codebase, but if the migration is skipped if the server is set to UTC that would explain it.

**Comment by reupen** [comment]
In the end I manually fixed my database using some UPDATE queries, but I imagine there will be other people with their databases in inconsistent states.

**Comment by kirrg001** [comment]
Hey @reupen yeah true! If your server is UTC and you are using sqlite, then the migration file is skipped and your dates remain in integer format - thanks for noticing. 

@ErisDS should we add a migration in `0.10.1`, which saves all posts if your server TZ is UTC and you are using sqlite?or is it enough to tell the people here to update each post?

**Comment by kirrg001** [comment]
I will fix this issue today/tomorrow and come back with a workaround.
