### ISSUE TITLE
Refactor test fixture utilities

### ISSUE THREAD

**Issue by acburdine** [TryGhost/Ghost#7196]
As part of the upgrade to knex 0.11 (see #7195), a flag was added to the sqlite test config that uses "null" as the default value (for inserts that don't have a default?).

This fixed the tests in the short-term; however, the test fixture utilities need to be evaluated and refactored so that this work-around is not needed.

This issue exists as a place for potential discussion as to how to refactor the tests, as well as a reminder that the tests need to be refactored 😄 

- [ ] https://github.com/TryGhost/Ghost/issues/6930

**Comment by ErisDS** [comment]
I haven't been able to find a good fixture library in the npm-world yet. Seems like one that works specifically with bookshelf/knex would be ideal?

**Comment by acburdine** [comment]
Note: Knex does have a `seed` api: http://knexjs.org/#Seeds-API which might work well for this, given that it is built into knex.

**Comment by ErisDS** [comment]
@kirrg001 do you have any thoughts about this?

**Comment by ErisDS** [comment]
I am gonna close this, I don't think we're going to be doing this anytime soon. It'll likely happen whenever we really need it 😁
