### ISSUE TITLE
Impact core inside theme?

### ISSUE THREAD

**Issue by chris-brown** [TryGhost/Ghost#7202]
How do I go about adding a tag helper inside a theme, or extending an existing helper. I dont really want to diverge too far from master. I have the helper on a branch for you to view but the existing behavior isnt ideal.

https://github.com/TryGhost/Ghost/compare/master...chris-brown:time-to-read

Would appreciate a suggestion.

**Comment by kirrg001** [comment]
Hey @chris-brown

Can you please swing by our [slack channel](https://ghost.org/slack/) and ask for help there? We can provide better support there than in the Github issue tracker, and if this turns out to be an actual issue with Ghost this issue can be reopened.
