### ISSUE TITLE
Make post edit button static

### ISSUE THREAD

**Issue by trnglina** [TryGhost/Ghost#7210]
### Issue Summary

Currently, the button to edit a post scrolls with the page. It would be better if it remained fixed. This is especially bothering with very long posts, where scrolling back to the top to edit a typo or something is an unnecessary bother.
### Solution

From my testing, simply adding

`.icon-edit {
  position: fixed;
  transform: translate(-20px, -10px);
}`

to the admin css fixes this, and keeps the button in (roughly) the same place.

**Comment by kevinansfield** [comment]
@trnglina you can also press <kbd>e</kbd> at any time whilst previewing a post in the content screen to start editing it.

**Comment by trnglina** [comment]
that's good to know, but hardly made clear. In the end, this is a small little thing that helps UX and doesn't really hurt anything.

**Comment by jameskolce** [comment]
I agree with @trnglina, I saw the same issue a couple of days ago.

**Comment by kevinansfield** [comment]
Closing and adding a reference to the [content screen overhaul](https://github.com/TryGhost/Ghost/issues/7860) issue.
