### ISSUE TITLE
Glitch: Where does this title coming from ?

### ISSUE THREAD

**Issue by pascalandy** [TryGhost/Ghost#7212]
### Issue Summary

I just upgraded to Ghost 0.9 and this title "Ghost at wallisblog.firepress.org" pop in in the banner loop page !?!? It is clearly generated by some logic.

<img width="807" alt="screen shot 2016-08-17 at 12 15 47 am" src="https://cloud.githubusercontent.com/assets/6694151/17724569/311e6fac-6411-11e6-8791-0e9ac908d7a9.png">

Also,  the blog title & description is empty

<img width="789" alt="screen shot 2016-08-17 at 12 15 54 am" src="https://cloud.githubusercontent.com/assets/6694151/17724624/9f96993c-6411-11e6-8f7f-8886cf3c7909.png">

### Steps to Reproduce

-

### Technical details:

* Ghost Version: 0.9
* Node Version: v4.4.7
* Browser/OS: firefox, safari and chrome Mac 10.11.x
* Database: pg

**Comment by AileenCGN** [comment]
Hey @pascalandy,

sorry to hear that you're having trouble with the upgrade. I am not able to reproduce it atm (meybe somebody else is), unfortunately. But I caught a glimpse of this one 
![image](https://cloud.githubusercontent.com/assets/8037602/17735649/aec935aa-6483-11e6-81b8-ae7f129004bf.png)
and was wondering, if you could tell me, what's written there. Also, did you try to override the blog title and then delete it again?

Cheers, Aileen

**Comment by pascalandy** [comment]
I should have thought about it !!! This fixed it :) Thanks @AileenCGN 

> did you try to override the blog title and then delete it again?

---

This is still a Glitch IMO.

**Comment by pascalandy** [comment]
It's just that it add a pain point went upgrading ... I will have to remember to do this process ...

**Comment by kirrg001** [comment]
https://github.com/TryGhost/Ghost/blob/master/core/server/mail/GhostMailer.js#L33
There we set the `config.theme.title`. 

And here we use it https://github.com/TryGhost/Ghost/blob/master/core/server/api/configuration.js#L38

**Comment by pascalandy** [comment]
Thanks for caring :)

**Comment by AileenCGN** [comment]
@pascalandy: I completely forgot to ask: Has there not been a blog title before, or was it empty only after you migrated to 0.9?

**Comment by pascalandy** [comment]
I was running on 0.7.9
The title was empty because it's done via infography in the banner
I upgraded to 0.9
Then the title appear automatically. 

Cheers!

**Comment by AileenCGN** [comment]
Thanks, @pascalandy!

Here's a way to reproduce the issue, even without migrating:

1. Remove `Blog Title` in `settings/general` and save
2. Have a `from` mail address **without** custom name in `config.js`: 
```        
mail: {
   from: 'myemail@address.com'
},
```
3. Send invitation mail or test mail
4. See blog title appear on home page after refresh

**Comment by pascalandy** [comment]
Love 😇
