### ISSUE TITLE
top-gh-contribs missing error on running grunt

### ISSUE THREAD

**Issue by anashalb** [TryGhost/Ghost#7218]
Hi,

I'm trying to run grunt but I'm getting a "top-gh-contribs package missing" error. Checked package.json and indeed, it's missing.

### Technical details:

* Ghost Version: 0.9.0
* Node Version: 4.4.2
* Browser/OS: N/A
* Database: Postgres

**Comment by kirrg001** [comment]
That is a Ghost-Admin dependency. Can you run `grunt init`?

**Comment by ErisDS** [comment]
Going to close this as it's a setup/ missing command issue. @anashalb drop by our [slack](https://ghost.org/slack) #help channel if you need any more help getting setup.
