### ISSUE TITLE
Safari doesn't show dragged-over state for file uploads

### ISSUE THREAD

**Issue by kevinansfield** [TryGhost/Ghost#7221]
### Issue Summary

Dragging a file over the drop-zone in file uploads does not show the highlighted border in Safari:

Safari:
<img width="579" alt="screen shot 2016-08-18 at 13 57 23" src="https://cloud.githubusercontent.com/assets/415/17774540/0b9c68b0-654c-11e6-9e1f-d3c696ba5984.png">

Chrome:
<img width="584" alt="screen shot 2016-08-18 at 13 56 28" src="https://cloud.githubusercontent.com/assets/415/17774541/0fe53424-654c-11e6-81e3-1ea6b0bcd99e.png">

### Technical details:

* Ghost Version: master
* Browser/OS: Safari 9.1.2

**Comment by KennethAshley** [comment]
Fixed with https://github.com/TryGhost/Ghost-Admin/pull/288

This is because safari doesn't allow classes that start with double hyphens.

**Comment by kevinansfield** [comment]
Closed via https://github.com/TryGhost/Ghost-Admin/issues/288
