### ISSUE TITLE
Custom SMTP Issue

### ISSUE THREAD

**Issue by Urriel** [TryGhost/Ghost#7236]
### Issue Summary

Hello,

I am using the docker container of ghost on my server. After the installation I change the config.js to add my mail smtp.

But keep getting `Greeting never received`.

my config:
```
mail: {
            transport: 'SMTP',
            options: {
                host: 'ssl0.ovh.net',
                secureConnection: true,
                port: 465,
                auth: {
                    user: '****',
                    pass: '****'
                }
            }
        }
```

doing a `openssl s_client -brief -connect ssl0.ovh.net:465` from the container get me the greeting message, but nodemailer does not.

### Technical details:

* Ghost Version: 0.9.0
* Node Version: 4.5.0
* Database: sqlite3

**Comment by kirrg001** [comment]
Can you please swing by our [slack channel](https://ghost.org/slack/) and ask for help there? We can provide better support there than in the Github issue tracker, and if this turns out to be an actual issue with Ghost this issue can be reopened.

**Comment by Urriel** [comment]
Sorry I figure it out yesterday evening. The docker is using the development config instead of the production one. None of my changes were used by ghost when restarted.

**Comment by FataPlex** [comment]
> @Urriel Are you using docker-compose?
> If so, can you please share it?
> because i'm unable to make the mail work using docker-compose

Sure, this works perfectly ! ;)
You can easily bind a local config.json file into your container !
Add this in your docker-compose file
```
[...]
volumes:
      - /opt/docker_compose/ghost/config.json:/var/lib/ghost/config.production.json
[...]
```
And here is the config for custom smtp host usage !
```
[...]
  "mail": {
    "from": "ghosttest@company.com",
      "transport": "SMTP",
      "options": {
         "host": "$ip",
         "port": $port_number
        }
[...]
```
