### ISSUE TITLE
Text field cursors jump to end of input

### ISSUE THREAD

**Issue by kevinansfield** [TryGhost/Ghost#7245]
`ember-one-way-controls` has [introduced a regression](https://github.com/DockYard/ember-one-way-controls/issues/102) where starting to type in the middle of a text field will cause the cursor to jump to the end of the input. The proposed fix in 1.0.1 also appears to have issues.

I've confirmed the bug affects us with at least the PSM's slug and publish date fields.

As we have a very imminent release I would suggest reverting to 0.9.2 to get back to a working state.

**Comment by martndemus** [comment]
This should now be fixed in `1.0.2`
