### ISSUE TITLE
Theme upload via custom storage adapter

### ISSUE THREAD

**Issue by kirrg001** [TryGhost/Ghost#7246]
With #7209 we made it possible uploading, downloading and deleting themes via Ghost.
This implementation has the restriction that theme uploads will use our default `local-file-store` for storing the themes on disk.

Uploading and downloading files in general is implemented by using a storage adapter (see https://github.com/TryGhost/Ghost/blob/master/core/server/middleware/index.js#L126) - in this case we are using the/your configured storage adapter to serve images.

To make it possible using a custom storage adapter for themes, we need to change how we `browse` available themes. Right now we read all available themes hardcoded from disk on bootstrap (see https://github.com/TryGhost/Ghost/blob/master/core/server/config/index.js#L81). With this hardcoded piece of code, configuring custom storage adapters for theme uploads is impossible. That's why it is restricted in #7209 (see https://github.com/TryGhost/Ghost/pull/7209/files#diff-198522c016d444fe14bb9882f7614d2dR201)

In https://github.com/TryGhost/Ghost/pull/7241 we already made the improvement choosing a specific storage adapter - `getStorage('themes')`. So each type (images, themes, apps) can have its own adapter.

If we would add a required storage function like `browse`, we could use that function to get all available themes. (`storage.getStorage('themes').browse(..)`).

The challenge is to define how a storage adapter should browse and what it should return.
Imagine you could plugin **any**  valid storage adapter and the behaviour must be always the same. 

We are happy if somebody could pick that issue up 🎉 

----

Helpful documentation to read: https://github.com/TryGhost/Ghost/wiki/Using-a-custom-storage-module

**Comment by ErisDS** [comment]
Similarly to https://github.com/TryGhost/Ghost/issues/5926#issuecomment-247947321, I'm going to close this issue for now.

Not that we don't need to implement something like this, rather that we need to review this change in the context of other changes that we intend to make and ensure we have a clear plan for how adapters and in particular storage adapters will work in future.
