### ISSUE TITLE
Sometimes the next post is the same as the current one

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#7248]
Originally reported here: https://github.com/TryGhost/Casper/issues/266

Sometimes it appears that the post that is being pulled from the DB as the next post, is actually the same post we are already on. 

### Steps to Reproduce

Unknown, assumed that the issue is caused by timezone configuration.

I think this line is the culprit: https://github.com/TryGhost/Ghost/blob/master/core/server/models/post.js#L573

We possibly need to do something to normalise the timezones in this query, or else exclude the post with the same ID.

**Comment by AileenCGN** [comment]
I'm not able to reproduce this issue so far. I tried with different timezones (blog as well as my local machine), but for me this issue doesn't show up. 

Will try some more way, but having more information about your setup @norsasono would be very helpful!

**Comment by kirrg001** [comment]
FYI: not able to reproduce as well. tested with different databases (pg, mysql) and different timezones.

**Comment by norsasono** [comment]
Big sorry for my late answer. 

FYI: I'm using Openshift.
Openshift quickstart https://github.com/openshift-quickstart/openshift-ghost-quickstart (0.7.5)

which is the same as https://github.com/MunGell/openshift-ghost-quickstart/ this one (updated version. 0.9.0)

* Ghost Version: 0.9.0
* Node Version: Node.js 0.10
* Browser/OS: Firefox/Ubuntu 16.04
* Database: Postgre

I'm in Indonesia (GMT +7)
The blog is running in aws-us-east-1

**Comment by AileenCGN** [comment]
Hey @norsasono,

You're running on Node.js v0.10? Ghost [support only versions > 0.10.*](http://support.ghost.org/supported-node-versions/). Not sure, if this could be a reason, but thanks for supplying for information. I will try to reproduce it with your settings.

**Comment by norsasono** [comment]
Yes, @AileenCGN. 0.10.

**Comment by ErisDS** [comment]
I believe the reason this bug is hard to track down is because it is a post-migration bug. Therefore it requires that you have content created pre 0.9 in a non-UTC timezone and then upgrade to 0.9.

As a quick fix, we should ensure that the next/previous post is never the same post as the current one.

There needs to be a separate investigation into what is happening with the migration itself and what is not correct with the dates post-migration. I believe this bug and #7192 likely have the same underlying cause.

**Comment by ErisDS** [comment]
Closed by #7323 (https://github.com/TryGhost/Ghost/commit/774a662fb2806e6639470e43f120689f4408cf90)
