### ISSUE TITLE
Support configuration of cache-control max-age

### ISSUE THREAD

**Issue by discordianfish** [TryGhost/Ghost#7273]
Hi,

as of this writing, ghost doesn't seem to support customizing the cache control headers.

It would be great if I could configure that somehow, just in config.js would be fine. This is especially useful since / and the individual posts set max-age=0, which always requires revalidation and might completely disable caching (at least cloudflare with default settings).

**Comment by ErisDS** [comment]
This is an interesting proposition, we're currently in the middle of entirely refactoring and then auditing Ghost's configuration, and so it's a good time to propose changes.

I am not sure that a generic max-age config is enough, do you have an idea what configuration options you wanted/needed?

**Comment by discordianfish** [comment]
Yes, more sophisticated cache settings would probably make sense. I'm personally most interested in cache settings for the dynamic, non-admin content like / and posts. Right now I setup some rules in CloudFlare to apply cache settings on a per path basis.

**Comment by ErisDS** [comment]
Could you be a bit more specific, maybe share the CloudFlare rules you're using?

**Comment by discordianfish** [comment]
I simply set 2h TTL for everything except /ghost/*

**Comment by ErisDS** [comment]
I've added this as an item for review in #7488. Going to close this as we don't need both issues open for the same task. It will be reviewed before the end of the alpha phase.

**Comment by breerly** [comment]
FWIW, we should think about setting `no-cache` on 4xx and 5xx range responses - we don't want edge caches storing these. At the very least, fine grained control might be in order.

**Comment by nodesocket** [comment]
I'd also like to be able to set the `Cache-Control` header max-age that comes back on static assets. It currently seems to be hardcoded at `31536000`one year from Express.

I purpose this should be a configuration option in `config.js`.

    cache: {
        # this would modify the header to Cache-Control: public, max-age=3600
        maxAge: 3600
    }

**Comment by nodesocket** [comment]
See my pull-request https://github.com/TryGhost/Ghost/pull/7916
