### ISSUE TITLE
Prevent sending notification to Slack when importing blog data

### ISSUE THREAD

**Issue by AileenCGN** [TryGhost/Ghost#7275]
When importing blog posts and having an incoming webhook configured in `apps/slack`, Ghosts sends a notification to the webhook for every single post that got imported. This can lead to a lot of unwanted notifications in slack. 

Slack is listening to the event `post.published`, so I assume this is something where we have to start looking. 
### Technical details:
- Ghost Version: pre-release 0.10.0
- Database: mysql

**Comment by halfdan** [comment]
I feel like instead of changing this hook, there should be an option to deactivate/skip apps when a bulk import happens.

**Comment by AileenCGN** [comment]
Me neither 😉  I also don't think we need to change the webhook. It just gets triggered by this event and therefore I reckon, that we need to look there first. Use a different event maybe for imported posts but without interfering on other processes that are depending on this event.
