### ISSUE TITLE
add option to auto-increment slugs

### ISSUE THREAD

**Issue by dwhieb** [TryGhost/Ghost#7276]
myblog.com/1
myblog.com/2
...

**Comment by halfdan** [comment]
Hi @dwhieb and welcome to Ghost. This issue tracker is used for development and to plan new features. If you'd like to request a new feature for Ghost please head over to https://ideas.ghost.org. 

It usually helps if you add a brief description of why you want a certain feature and what problem it solves.

**Comment by dwhieb** [comment]
Will do - thanks!
