### ISSUE TITLE
nodejs not listening on localhost

### ISSUE THREAD

**Issue by compengi** [TryGhost/Ghost#7279]
I'm trying to run ghost behind an apache proxy. So I want to proxy the request for example from http://example.com/blog -> http://localhost:2368 this is my script:

```
        ProxyPass /blog http://localhost:2368 nocanon
        ProxyPassReverse /blog http://localhost:2368
        <Proxy http://localhost:2368*>
                Order deny,allow
                Allow from all
        </Proxy>
```

and my config is:

```
production: {
        url: 'http://example.com/blog', // dummy url
        mail: {},
        database: {
            client: 'sqlite3',
            connection: {
                filename: path.join(__dirname, '/content/data/ghost.db')
            },
            debug: false
        },

        server: {
            host: '127.0.0.1',
            port: '2368'
        }
    },
```

but it's not working as supposed to. I'm always getting **Cannot GET /** when I navigate to http://example.com/blog and I get the same thing when calling **curl http://localhost:2368** from server's terminal. But when I set the **url** in the config to **http://localhost:2368** everything works.

Nodejs v4.4.7
Apache 2.2.22
Stable Ghost branch since commit: 55b65a52d17fb8fc6444aa0c1f2f28ad72b6e88a

**Comment by Elder-of-Ozone** [comment]
I had the same problem. I had to ensure everything was consistent. So in your apache config replace localhost with 127.0.0.1

**Comment by compengi** [comment]
That didn't help... I'm still getting **Cannot GET /** using **curl http://localhost:2368**

**Comment by acburdine** [comment]
hey @compengi, sorry to hear your're having trouble!

My guess is that you'll need to change the host in your config file to `0.0.0.0` instead of `127.0.0.1`.

However, if that doesn't work, please swing by our [slack](https://ghost.org/slack) channel and get help there. We're able to provide better support there than in the Github issue tracker, which we use for issues with Ghost itself.

Thanks!
