### ISSUE TITLE
Issue with ghost.api.url

### ISSUE THREAD

**Issue by guyzmo** [TryGhost/Ghost#7280]
### Issue Summary

I'm running ghost v0.9.0 with [ghosthunter rev 268346](https://github.com/jamalneufeld/ghostHunter/tree/268346509620279e28c8fd47b6520bc41152525b) that has been shipped with a paid theme, the following search form:

```html
<form role="search" method="get" class="search-form" action="/api/v0.1/#">
    <label>
        <span class="screen-reader-text">Search for:</span>
        <input class="search-field" placeholder="Search …" value="" name="s" title="Search for:" type="search">
    </label>
    <input class="search-submit" value="Search" type="submit">
</form>
```

always returns `Number of posts found: 0`.

### Steps to Reproduce

So I tried to understand the issue, and the best way was to look at the source. Within [ghostHunter's source](https://github.com/jamalneufeld/ghostHunter/blob/268346509620279e28c8fd47b6520bc41152525b/jquery.ghostHunter.js#L100):

```javascript
$.get(ghost.url.api('posts', {limit: "all", include: "tags"})).done(…)
```

I then looked at the documentation, and it matches usage as described and [shown in the examples](http://themes.ghost.org/docs/ghost-url-api#section-basic-examples):

```javascript
ghost.url.api('posts', {limit: 5, include: 'tags,author'});
```

But, then I tried running this function in my browser, and it returned:

```javascript
» ghost.api.url('posts')
"posts/?client_id=ghost-frontend&client_secret=XXXXXXXXXXXX"
```

And I checked the network exchanges between my browser client and the server, and got:

```
https://mydomain.tld/posts/?limit=all&include=tags&client_id=ghost-frontend&client_secret=XXXXXXXXXXXX
```

When I looked at the [API documentation](http://api.ghost.org/docs/client-authentication), I found out that the expected path for API requests is supposed to be:

```
/ghost/api/v0.1/posts?client_id=ghost_frontend&client_secret=123456abcdef
```

Finally to make sure *that* was the issue, I copied that and tried to open the following URL:

```
https://mydomain.tld/ghost/api/v0.1/posts/?limit=all&include=tags&client_id=ghost-frontend&client_secret=XXXXXXXXXXXX
```

I had the expected JSON output!

So I believe there's a bug in the way the `apiUrl` value is setup, and ends up empty instead of containing the full API path.

### Technical details:

* Ghost Version: v0.9.0
* Node Version: v0.10.29
* Browser/OS: Debian 7.11
* Database: mysql

**Comment by guyzmo** [comment]
I have tried all that with the default theme, and had the same issues. I also tried with `NODE_ENV="development"`, and the issue was still there.

**Comment by guyzmo** [comment]
ATM my temporary bandage (I wouldn't even call that a patch) has been to replace `ghost.url.api('posts',…)` within ghosthunter for `ghost.url.api('/ghost/api/v0.1/posts',`.

**Comment by guyzmo** [comment]
BTW, there's an [unanswered SO question about this issue](http://stackoverflow.com/questions/33553326/ghosthunter-number-of-posts-found-0-issue), so it looks like I'm not the only one to stumble upon this.

**Comment by guyzmo** [comment]
N.B.: Even though I'm running the blog in private mode, I did check that with the private mode disabled, and the issue was still there.

**Comment by acburdine** [comment]
@guyzmo I just tried this on master and couldn't reproduce 😕. Can you try your theme with master and see if the issue still exists?

**Comment by guyzmo** [comment]
I do not think it's related to the theme, as it's happening as well with the casper theme and in development mode… 

That being said, of course I'd be happy to try, though I think it'd be interesting to dig up what can break the api url and what stupid/wrong thing did I do to break it up. I only followed documentation and did not try anything awry.

I won't have time today, but I'll give it some time tomorrow, cheers!

**Comment by Windyo** [comment]
Hey, just jumping in here because I seem to recall helping someone put ghosthunter in place, and they had the same sort of problem. If I remember correctly it came from their config.js file.

I tested ghosthunter on a couple of 0.9.0 instances myself with no issue - let me know if I can help in some way.

**Comment by guyzmo** [comment]
I actually kinda solved this by hacking all calls to `ghost.api.url()` and adding the full path to the resource, instead of just the resource. It's dirty and bad, but works ☺

So, I'll double check their config.js file, and try to figure what could be wrong. If you have any hints on what to check, please, tell me so ☺

**Comment by Windyo** [comment]
If I remember correctly it was the URL of the blog specified in the config.js that was wrong, whe=ich lead Ghost to erronuously try to construct the URL.

The only other time I has a strange behavior on the API calls GhostHunter makes is when I tried to update a ghost install without shutting it down first. Strangely enough it succeeded, but as you can imagine there were some... complications.

if all else fails I would go with @acburdine's solution and try to update Ghost to the latest master, see if that solves it.

**Comment by ErisDS** [comment]
I'm not sure what's causing this, but I don't have enough information to reproduce it. I'm guessing that it probably is something to do with config.js. If some more information about what the url in `config.js` is set to, then we can look into this further.

Otherwise, we're massively reworking our configuration and how these things work, so I think it will resolve itself/be easier to debug in future.
