### ISSUE TITLE
AMP iframe position

### ISSUE THREAD

**Issue by kirrg001** [TryGhost/Ghost#7283]
When your iframe is not 600px away from the top, it does not get rendered, because of an AMP error.

See:
![pasted image at 2016_08_29 09_44](https://cloud.githubusercontent.com/assets/1160712/18044643/1dedf50c-6dcf-11e6-97f8-e45d9331d5e4.png)

Reproduce:
- create a post
- insert iframe on top
- go to the AMP page of this post and see error
- if you add content before the iframe and the iframe is min 600px from top away, it gets rendered

See official amp description:
https://www.ampproject.org/docs/reference/extended/amp-iframe.html

There is a restriction in amp for this kind of use case, but it is solvable by adding a placeholder image. We could for example always add a placeholder image to the iframe.

**Comment by AileenCGN** [comment]
Adding a default placeholder - something like 'Loading ...' would fix this issue.

**Comment by AileenCGN** [comment]
Shall we close this, @kate? In favour of the discussion on slack?

**Comment by kirrg001** [comment]
sure 🎉

**Comment by AgentME** [comment]
I'm seeing this issue today. Was this issue reintroduced?

**Comment by kirrg001** [comment]
cc @AileenCGN

**Comment by AileenCGN** [comment]
Looking into it

**Comment by AileenCGN** [comment]
I wish I would've linked to the actual Slack convo. Can reproduce it. Searching for solution.

**Comment by AileenCGN** [comment]
Alright, found the conversation. We decided to close this issue and not do anything about this, as it's a 0,00001% edge case. See [here](https://ghost.slack.com/archives/C1T10THSM/p1472459637000002)
