### ISSUE TITLE
💄 Rethink usage of meta description

### ISSUE THREAD

**Issue by AileenCGN** [TryGhost/Ghost#7284]
Google cuts off the meta description in the search results, due to printing the publish date first and including it in the total of 160 characters, we're using at the moment:

![image](https://cloud.githubusercontent.com/assets/8037602/18047569/e15105a8-6ddd-11e6-8911-29a0cec80687.png)

### Suggestion:
Set the new character limit in meta description field in the post settings menu to 145 characters instead of 160 and avoid descriptions being cut off:
![image](https://cloud.githubusercontent.com/assets/8037602/18047608/0cb8f9bc-6dde-11e6-844d-16677a772937.png)

**Comment by ErisDS** [comment]
This contradicts https://github.com/TryGhost/Ghost/pull/4126#issuecomment-56632903

As far as I understand this is a visual-only optimisation which may in fact be negative for SEO?

**Comment by uditgoenka** [comment]
@ErisDS No, Meta Title and Meta Descriptions are two standard way to tell Google what your content are all about. If you overstuff your keywords, then it becomes negative for your SEO. 

For example:
If my content is about How to install Ghost then I won't write how to complete my homework faster in my meta description. 

Google relies on these text elements including your meta title and meta description and your entire article.

**Comment by ErisDS** [comment]
Can someone provide a reference or source that shows we should reduce the length of the meta description please?

Again, Google adds the date in it's DISPLAY of the search engine results. This is not necessarily anything to do with the ranking algorithm. Again, according to https://github.com/TryGhost/Ghost/pull/4126#issuecomment-56632903 we are meant to be, and will shortly be, increasing the length of the meta description. This is making the opposite suggestion but it seems to be purely aesthetic.

**Comment by AileenCGN** [comment]
Yes, I agree 100% with you @ErisDS. It's just a visual thing. I would love to see some sources for that. 

Increasing the length of the meta description would result in having better structured data for Twitter and Facebook. And as we can see, that Google is already testing longer meta descriptions, there might be no sense in cutting them down.

I did some more research on that topic and Google seems to output the description in the SERPS just how it thinks, it's suitable:

https://yoast.com/meta-descriptions/

I'm not sure how to proceed with this _"issue"_ now. Close it? Wait for more resources and opinions?

**Comment by uditgoenka** [comment]
@AileenCGN I think it's too early to close it. 

Google only pulls different description in the SERPs if they find the description is irrelevant to the contents posted on the website. 

Regarding Google testing longer meta description, this is a test, doesn't mean they will implement it.  

Regarding Social Media, Facebook doesn't reply on Meta Description, it relies on the Open graph and allows up to 300 characters in the OG: meta description. I think Ghost should allow a way where the Meta Details are separated by Open Graph Details.

http://ideas.ghost.org/forums/285309-wishlist/suggestions/15852541-control-over-open-graph-title-description-for-fa

For now, I am sticking with 142-145 character long description for all my posts on Ghosts until we get an option to disable dates in the meta description.

**Comment by AileenCGN** [comment]
I changed the title, as this seems to needs more research. Also, this issue would be related to #7207.

**Comment by uditgoenka** [comment]
@AileenCGN That's a much better title because we are not asking to force change, instead work towards a way to make things better. 

One thing I have to say, Ghost has way better support than any other CMS community out there :)

**Comment by AileenCGN** [comment]
As we're thinking of refactoring a big part of the way, we build the meta data, I'm closing this for now in favour of #7207.
