### ISSUE TITLE
Could not read config from meta tag with name "ghost/config/environment"

### ISSUE THREAD

**Issue by dalanmiller** [TryGhost/Ghost#7288]
### Issue Summary

Running on Ubuntu 14.04 after upgrading from 0.8.0 to 0.10.0. When attempting to load the admin panel, I just get a blank screen and this in the console:

```
ghost.min.js?v=a3e352156b:25 Uncaught Error: Could not read config from meta tag with name "ghost/config/environment".
```

### Steps to Reproduce

1. Start with 0.8.0
1. Remove `core`, `package.json`, `npm-shrinkwrap.json`, `index.js` 
1. Move 0.10.0 equivalents into `ghost` directory
1. Remove `node_modules`
1. Run `npm install --production`
1. Run `npm start --production` 

All pages will load fine, but when I navigate to `mywebsite.com/ghost` I just get a blank page. 

### Technical details:

* Ghost Version: Now 0.10.0
* Node Version: v4.5.0
* Browser/OS: Linux 14.04 on Chrome 52
* Database: Sqlite

**Comment by kirrg001** [comment]
Hey @dalanmiller When i follow http://support.ghost.org/how-to-upgrade/, i don't get this error. 

Can you please swing by our [slack channel](https://ghost.org/slack/) and ask for help there? We can provide better support there than in the Github issue tracker, and if this turns out to be an actual issue with Ghost this issue can be reopened.

**Comment by michaeljkchoi** [comment]
Not sure if you were able to fix this issue @dalanmiller but I got it working after I killed the node instance.

```
> sudo netstat -lp
tcp  0 0 *:2368 *:* LISTEN 11111/node

> sudo kill -9 11111
```

Then restarting got everything working.

**Comment by llv22** [comment]
the same as me... from 0.7.9 to 0.11.0

**Comment by andrewlock** [comment]
FYI, For anyone finding this - I ran into this issue when migrating to a new server 0.79 to 0.11.7. I hadn't installed the SSL certificate on the new server, but was using CloudFlare in front of Ghost. Switching CloudFlare from Full to Flexible SSL mode enabled me to login to the admin panel.
