### ISSUE TITLE
Ghost NPM Module does not Contain Required .min Files

### ISSUE THREAD

**Issue by Silvenga** [TryGhost/Ghost#7289]
### Issue Summary

The Ghost NPM module (v0.10.0) is missing several files, e.g. `core\built\assets\vendor.min.js`. This is causing 301 responses directing to incorrect pages. 

### Steps to Reproduce

Extract: https://registry.npmjs.org/ghost/-/ghost-0.10.0.tgz
Navigate to `package\core\built\assets\`

![image](https://cloud.githubusercontent.com/assets/2753330/18075409/2b558c62-6e3a-11e6-877d-8e4de51b7f58.png)

Running the server shows the following in logs:

`127.0.0.1 - - [30/Aug/2016:03:24:30 +0000] "GET /ghost/vendor.min.js?v=4449a3835e HTTP/1.1" 301 - "http://127.0.0.1:2368/ghost/setup/" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36"`

### Technical details:

* Ghost Version: 0.10.0
* Node Version: v4.2.0
* Browser/OS: Chrome/Windows
* Database: MySQL

**Comment by Silvenga** [comment]
Looks related to #6676. Files normally created by grunt are not in the NPM package.

**Comment by Silvenga** [comment]
To prevent any environment settings impacting this issue, I tried unzipping `https://ghost.org/archives/ghost-0.10.0.zip` over `node_modules/ghost`. This fixes the issue, although #7286 is then shown.

**Comment by kirrg001** [comment]
Hey @Silvenga . Sorry to hear you are having trouble. I can confirm, the `.min` files are missing. Thanks for reporting. I published a `0.10.0-rc1` to npm. You can reopen this issue, if it's not resolved 👍

**Comment by halfdan** [comment]
@kirrg001 Did you yank 0.10.0? Why is the new version an rc1?

**Comment by kirrg001** [comment]
`0.10.0-rc1` is temporary, we have contacted the npm support. The minified files were present at upload time.

**Comment by Silvenga** [comment]
Confirmed resolved.
