### ISSUE TITLE
Bug: Json Import doesn't work in Chrome, Opera 0.10.0

### ISSUE THREAD

**Issue by jozic** [TryGhost/Ghost#7295]
### Issue Summary
Json Import doesn't work

### Steps to Reproduce

1. Go to Labs
2. Click Import => Import window opens with zip extension preselected
![image](https://cloud.githubusercontent.com/assets/124249/18114086/5f379584-6f02-11e6-9808-df9b93cb426b.png)
3. Select all files in extension filter
4. select json file exported from 0.9.0 installation
5. click Import => import doesn't work
![image](https://cloud.githubusercontent.com/assets/124249/18114130/bc41f1b6-6f02-11e6-85b4-90eb9109a487.png)

### Technical details:

* Ghost Version: 0.10.0
* Node Version: 4.4.7
* Browser/OS: 
  Opera 39.0.2256.48
  Chrome Version 52.0.2743.116 (64-bit)
  OS: Ubuntu 14.04.4 LTS (x86_64; MATE)
* Database: default

**Comment by kirrg001** [comment]
Hey @jozic Sorry to hear you are heaving trouble. I assume this bug is related to #7293

**Comment by ErisDS** [comment]
The extension filter should be allowing both json and zip files here.

@jozic can you see in the developer tools if the file is actually uploaded or ignored?

**Comment by jozic** [comment]
for me extension filter only has zip and All files
![image](https://cloud.githubusercontent.com/assets/124249/18133956/a0718664-6f6a-11e6-9614-1f69c797adc3.png)

also i see in debugger that uploaded file has type '', which fails type check
![image](https://cloud.githubusercontent.com/assets/124249/18134926/1bee2bb4-6f6e-11e6-962c-ae044931d034.png)

**Comment by jozic** [comment]
it happens that import works properly in firefox 48.0

**Comment by jozic** [comment]
this looks relevant 
http://stackoverflow.com/questions/27518238/why-cant-firefox-or-chrome-determine-a-json-files-type
looks like chrome and opera can't recognize type of *.json file and set it to empty string, additional extension check can help

**Comment by jsinh** [comment]
Facing similar issue here.
Windows / Ghost 0.10.0 / Node v4.4.7 / NPM v2.15.8
JSON is from 0.7.1 version of ghost blog.

![2016-09-01_02-11-01](https://cloud.githubusercontent.com/assets/1277539/18145813/61f12c2a-6fea-11e6-9c00-1948f49e218e.png)

**Comment by jsinh** [comment]
This bug practically makes it impossible to migrate to v0.10.0

**Comment by jozic** [comment]
@jsinh have you tried latest firefox? as it works for me. i have firefox 48.0

**Comment by jsinh** [comment]
Yup tried on 48.0 and does not work for me there. @jozic

**Comment by jsinh** [comment]
@kevinansfield Seems fixed but not sure how to use the fixed version. Do we need to wait for a new version stable release or same fix is applied and available in current lastest ghost version 0.10.0?

**Comment by ErisDS** [comment]
The fix will be released as a new version shortly.

**Comment by jsinh** [comment]
@ErisDS - Tested and upgraded to v0.10.1 release today (based on new update notification received). Import works fine now. Thanks!
