### ISSUE TITLE
Direct upgrade from 0.7.x -> 0.10 does not work

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#7297]
In the past, we have been pretty good at supporting upgrades from any version to any version. However, we _do_ state in the docs that minor updates should be done one-at-a-time ([see here](http://support.ghost.org/how-to-upgrade/#3.-consider-the-version-jump)). 

Currently, when upgrading from 0.7.x -> 0.10 you'll see the following errors:

```
Migrations: Creating database backup

ERROR: select count(distinct posts.id) as aggregate from "posts" where "posts"."visibility" = 'public' and "posts"."page" = true and "posts"."status" = 'published' - SQLITE_ERROR: no such column: posts.visibility 

Error: select count(distinct posts.id) as aggregate from "posts" where "posts"."visibility" = 'public' and "posts"."page" = true and "posts"."status" = 'published' - SQLITE_ERROR: no such column: posts.visibility 
at Error (native)
```

I believe that this is caused by the sitemap trying to generate when Ghost boots into maintenance mode whilst the migrations run. This is an oversight, as the API calls should fail (but don't because they are internal rather than HTTP which triggers the middleware). The updates to the sitemap to use `visibility` in 0.10 are the reason why this is suddenly causing a problem and wasn't before. The sitemap should not initialise until after maintenance mode is finished.

I am not sure that this is a bug that warrants fixing. The workaround is to properly upgrade through the minor versions, from 0.7.x to 0.8 and then 0.9 and 0.10. This is a pain, but we are already working on alternative upgrade strategies for the future. For now, this is probably worth a short investigation to see if there is a quick fix.

**Comment by kirrg001** [comment]
will look into quickly

**Comment by kirrg001** [comment]
as @ErisDS  has guessed, sitemap generation requests the database before the migration has finished. will create a PR with a fix on sunday/monday. sorry for trouble!

**Comment by fxlv** [comment]
Just hit this exact problem when upgrading from 0.7.1 to 0.10.
As a workaround, upgrading 0.7.1 -> 0.9.0 -> 0.10 worked for me.

**Comment by ErisDS** [comment]
Just to reiterate, our official recommendation is always to upgrade through each minor version one at a time (so 0.7.1 -> 0.8 -> 0.9 -> 0.10) 
Even more importantly, it is recommended to manually run Ghost using `npm start --production` the first time, so that you can monitor the progress of each upgrade.
