### ISSUE TITLE
Question: Addition for service worker support

### ISSUE THREAD

**Issue by amilajack** [TryGhost/Ghost#7298]
Will ghost ever add Service Worker support? That would be a complementary addition to AMP support.

**Comment by AileenCGN** [comment]
Hey @amilajack, thanks for your question. We didn't discuss this yet. You can always supply ideas or wishes here: https://ideas.ghost.org

Anyway, for those simple questions, it would be much faster and easier if you pass by our [slack channel](https://ghost.org/slack) and ask them there. 

Cheers, Aileen
