### ISSUE TITLE
Try adding Snyk CI support for vulnerability detection

### ISSUE THREAD

**Issue by petems** [TryGhost/Ghost#7300]
### Issue Summary

Ghost currently has a number of node package vulnerabilities, I only noticed because I run Ghost in a Docker container and my container scanner noticed them.

I've opened a few PRs to fix some of the vulnerabilities:
https://github.com/TryGhost/gscan/pull/21
https://github.com/TryGhost/gscan/pull/20

There are services like Snyk that can provide CI for security vulnerabilities in packages, making it easy to update them.

Snyk seems the best one to do this, as it checks dependancies down the chain for vulnerabilities, whereas https://nodesecurity.io/ only checks the dependancies listed in the `package.json`, when they're normally two or three packages downstream.

It's free for open-source projects 👍 

## Example

https://snyk.io/test/npm/ghost/0.10.0

Snyk can also be run as a command line job, so could be added to `.travis.yml` if full API access is problematic.

**Comment by ErisDS** [comment]
@petems Thanks for the note & for the PRs to gscan 👍  We already have several different services like this enabled including Snyk and bithound, sending us regular notifications. When it matters, we take notice & act accordingly. The vulnerabilities deep in the dependencies of gscan were not exposed to Ghost - only to the gscan website.

We take security extremely seriously. I have commit access to many of our dependencies just so I am able to do these sorts of updates when necessary 😉
