### ISSUE TITLE
First drag-n-drop of a file results in error (Safari)

### ISSUE THREAD

**Issue by kevinansfield** [TryGhost/Ghost#7310]
### Issue Summary

Using Safari, the very first drop of a file on a file upload drop zone results in an error due to the file not being passed through, subsequent drag-n-drops work ok.

![file-upload-error](https://cloud.githubusercontent.com/assets/415/18168914/dca5f85a-704f-11e6-8619-74b4f4c5d18a.gif)
### Steps to Reproduce
1. Go to a a file upload screen (subscribers import and theme upload both confirmed so far)
2. Drag a file onto the drop zone
3. Note the error in the console (slightly different depending on the validation method of the file upload chosen in step 1 but always results from `file` being `undefined`)
4. Drag the file onto the drop zone again
5. Note the validation/upload worked ok
### Technical details:
- Browser/OS: Safari

**Comment by KennethAshley** [comment]
Fixed with: https://github.com/TryGhost/Ghost-Admin/pull/288

This is due to safari not allowing double hyphens at the start of a class.

**Comment by KennethAshley** [comment]
@kevinansfield Excuse me, I misreferenced the wrong issue in my PR. My PR ([228](https://github.com/TryGhost/Ghost-Admin/pull/288)) fixes issue [#7221](https://github.com/TryGhost/Ghost/issues/7221) and not this issue.

Although I could not reproduce this issue in Safari on my machine.

**Comment by kevinansfield** [comment]
Oops, closed due to wrong issue reference, re-opening. Thanks for pointing it out @KennethAshley!

**Comment by KennethAshley** [comment]
@kevinansfield No problem. Sorry about that! Ok on to fixing another issue ahaha 😁

**Comment by JohnONolan** [comment]
@kevinansfield this seems to be resolved in Ghost 1.0? Cant reproduce

**Comment by kevinansfield** [comment]
I can still see the issue in the theme uploader, it doesn't seem to be a problem anywhere we expect image uploads.

**Comment by kevinansfield** [comment]
I can no longer reproduce with Safari 11 for both the theme and subscriber uploads, assuming this was a bug in Safari that's been fixed or a refactor somewhere along the way has fixed the original issue.
