### ISSUE TITLE
CSS in AMP template is not minified

### ISSUE THREAD

**Issue by ScottHelme** [TryGhost/Ghost#7314]
### Issue Summary

The CSS served in the new AMP templates is not minified, missing out on a considerable reduction in size.
### Steps to Reproduce
1. Load a page using AMP and observe the inline style near the top of the document.
### Technical details:
- Ghost Version: 0.10.0

The style is 19.63 KB in size and when minified is only 8 KB. This represents a considerable saving, especially given the purpose of AMP. 

I have minified this style in my AMP template, example here: https://scotthelme.co.uk/securityheaders-io-updates/amp/

**Comment by JonathanMH** [comment]
For development it's a big plus that the core file is not minified, I think that's something your theme should take care of, when built.
