### ISSUE TITLE
AMP doesn't work on preview links

### ISSUE THREAD

**Issue by ScottHelme** [TryGhost/Ghost#7315]
### Issue Summary

Adding `/amp/` to the end of a preview link results in a 404. 

### Steps to Reproduce

1. Visit a preview link for a post and add `/amp/` to the end.

    https://example.com/p/abc123/amp/

### Technical details:

* Ghost Version: 0.10.0

I'm not sure if this is intended to work or not but it could be handy to view the AMP version of a post prior to publishing the post.

**Comment by acburdine** [comment]
It was definitely not intended to work - meaning the code to handle amp on preview links doesn't exist (so it's not a bug necessarily). However, I'm not sure as to whether that was due to a direct decision or just an oversight.

/cc @AileenCGN

**Comment by ErisDS** [comment]
As explained, this was not intended to work. Feel free to raise this as a suggestion on ideas.ghost.org :)
