### ISSUE TITLE
Ghost npm package for 0.10.0 release not available

### ISSUE THREAD

**Issue by donovanmuller** [TryGhost/Ghost#7319]
### Issue Summary

It doesn't seem like the [[release] NPM package](https://www.npmjs.com/package/ghost) for 0.10.0 is available yet.
The latest release in the registry is `0.10.0-rc1` as of now.

### Steps to Reproduce

1. Try to use `0.10.0` as the npm version:

```
{
...

  "devDependencies": {
    "ghost": "~0.10.0",

...
```

results in:

```
$ npm install
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/Cellar/node4-lts/4.4.7/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v4.4.7
npm ERR! npm  v2.15.8
npm ERR! code ETARGET

npm ERR! notarget No compatible version found: ghost@'>=0.10.0 <0.11.0'
npm ERR! notarget Valid install targets:
npm ERR! notarget ["0.6.0","0.6.1","0.6.2","0.6.3","0.6.4","0.7.0","0.7.1","0.7.2","0.7.3","0.7.4","0.7.5","0.7.6","0.7.7","0.7.8","0.7.9","0.8.0","0.9.0-beta.1","0.9.0-beta.2","0.9.0","0.10.0-rc1"]
npm ERR! notarget
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
...
```

### Technical details:

* Ghost Version: 0.10.0
* Node Version: -
* Browser/OS: OSX 10.11.6
* Database: -

**Comment by ErisDS** [comment]
This is a known issue. Unfortunately, when publishing the `0.10.0` package, there was some issue with npm which meant some files were missing. We have asked npm to republish the proper version with all the necessary files. In the meantime, 0.10.0-rc1 is the exact same package.

**Comment by kirrg001** [comment]
We got an answer from NPM, there is no way to force a republish of the version `0.10.0`. 
As @ErisDS said, `0.10.0-rc1` is the same version. Closing this issue now, we will release `0.10.1` in a couple of days.
