### ISSUE TITLE
Sitemap Blocked When Loaded As WWW.

### ISSUE THREAD

**Issue by html5andblog** [TryGhost/Ghost#7325]
I've just transferred my WordPress blog to Ghost with TSO Host, and everything is working as I'd hoped. The sites a lot faster, but there is one issue. The sitemap isn't loading when I try and access it through:

https://www.html5andbeyond.com/sitemap.xml

It's giving me the console error:

`Unsafe attempt to load URL https://html5andbeyond.com/sitemap.xsl from frame with URL https://www.html5andbeyond.com/sitemap-pages.xml. Domains, protocols and ports must match.`

Whereas when I access it through:

https://html5andbeyond.com/sitemap.xml

It's loading correctly. I'm just concerned that this sitemap without the www. prefix will lead to Google listing links to my site like this. When I've always used www.

Is there anything that can be done to fix this?

Thanks,
Simon

**Comment by html5andblog** [comment]
I've also noticed that all the post links within the sitemap, https://html5andbeyond.com/sitemap-posts.xml, are non secure links. Naturally I want all these links to be HTTPS.

**Comment by nuclearpengy** [comment]
You'll need to change your base path to include WWW and HTTPS.

It's best to move this conversation over to the help channel on Slack: https://ghost.org/slack/

**Comment by html5andblog** [comment]
Thanks, I'll close this issue and move it over to Slack.
