### ISSUE TITLE
insert into sqlite3 error

### ISSUE THREAD

**Issue by wwwshishd** [TryGhost/Ghost#7330]
INSERT INTO "posts" VALUES(10161,'48b65c34-17b5-46d1-ba82-5a64488a0369','first ghost post','first-ghost-post','hello ghost!','<p>hello ghost!</p>',NULL,0,0,'published','en_US',NULL,NULL,1,'2016-09-04 15:56:55',1,'2016-09-04 16:18:17',1,'2016-09-04 15:57:40',1,'public',NULL);

I insert into sqlite3, but it show a error:
Error: near line 3: NOT NULL constraint failed: posts.language

the posts.language is 'en_US', who can tell me where error?

**Comment by ErisDS** [comment]
@wwwshishd please use [slack](https://ghost.org/slack) for help & support.
