### ISSUE TITLE
s3fs and docker image

### ISSUE THREAD

**Issue by aarongundel** [TryGhost/Ghost#7334]
### Issue Summary

I am attempting to run the (latest) docker ghost image using s3fs to access a bucket as a docker volume.  My container starts and dies with the message...

**chown: changing ownership of '/var/lib/ghost': Input/output error**

my run command looks like this...

`docker run --name blog -d -p 80:2368 -v /opt/ghost:/var/lib/ghost ghost`

where /opt/ghost is an s3fs mounted volume on the host.  I think this issue is related to https://github.com/docker-library/ghost/issues/19 but I don't see a way from there to resolve.  my mounted volume already has 1000 as user/group.   

Also interesting to note; ghost appeared to create files in the volume on first run just fine, but crashed just after that.

**Comment by kirrg001** [comment]
Hey @aarongundel Sorry to hear you are having trouble. Can you please swing by our [slack channel](https://ghost.org/slack/) and ask for help there?

**Comment by ErisDS** [comment]
Also please be aware the docker image is not maintained by us, but by docker 😉
