### ISSUE TITLE
Empty Sitemap.xml 

### ISSUE THREAD

**Issue by sebgie** [TryGhost/Ghost#7341]
### Issue Summary

I see an issue with sitemap.xml not being generated every time it gets requested. The issue is not really reproducible. For failed requests Ghost returns an empty response with status code 200.

### Steps to Reproduce

1. go to /sitemap.xml
2. hope that it's empty

### Technical details:

* Ghost Version: 0.10.1
* Node Version: 4.4.7
* Browser/OS: Chrome
* Database: Mysql

**Comment by CairoLee** [comment]
And the support page may need update(content is out of date):
http://support.ghost.org/faq/generate-sitemap-blog/
