### ISSUE TITLE
Remove internal tags from meta data

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#7348]
As originally reported here: https://github.com/TryGhost/Ghost/issues/6165#issuecomment-244651301, we need to remove the internal tags from our meta data.

This is done in just one place: https://github.com/TryGhost/Ghost/blob/master/core/server/data/meta/keywords.js

Instead of a simple `.map()` on the post tags, we need to reduce or filter to remove all the internal tags. 

There is already code which does this here: https://github.com/TryGhost/Ghost/blob/master/core/server/helpers/tags.js#L31.

Inside the helper, the reduce method is also applying the correct formatting (escape & wrap with a link) to each tag.

Quick fix version here is to duplicate the reduce logic into the `meta/keywords.js` file. 

Ideal solution would be to split out the reduce logic into a utility which both can make use of in their own way. E.g. have a filtering function which takes an  optional formatting function to call on each tag which will actually be returned.

**Comment by jmeischner** [comment]
hejhej,

is the options object in 
https://github.com/TryGhost/Ghost/blob/master/core/server/helpers/tags.js#L17
accessible in 
https://github.com/TryGhost/Ghost/blob/master/core/server/data/meta/keywords.js
?

So should this object be a function argument for the reduce method?

Could this be an idea:
```javascript
function reduceTags(tags, options, formatting) {
	options = options || {};
	options.hash = options.hash || {};

	var visibility = utils.parseVisibility(options);

	return _.reduce(tags, function(tagArray, tag) {
		// If labs.internalTags is set && visibility is not set to all
        // Then, if tag has a visibility property, and that visibility property is also not explicitly allowed, skip tag
        // or if there is no visibility property, and options.hash.visibility was set, skip tag
        if (labs.isSet('internalTags') && !_.includes(visibility, 'all')) {
            if (
                (tag.visibility && !_.includes(visibility, tag.visibility) && !_.includes(visibility, 'all')) ||
                (!!options.hash.visibility && !_.includes(visibility, 'all') && !tag.visibility)
            ) {
                // Skip this tag
                return tagArray;
            }
        }

        var tagFormatted = formatting(tag);
        tagArray.push(tagFormatted);

        return tagArray;
	}, []);

}
```

**Comment by ErisDS** [comment]
Hi @jmeischner, the options object in the helper is part of handlebars, and isn't available in the metadata I'm afraid.
