### ISSUE TITLE
AMP doesn't work when blog is in a subdirectory

### ISSUE THREAD

**Issue by acburdine** [TryGhost/Ghost#7352]
### Issue Summary

Was reported in Slack, tested and verified that this is indeed a bug 😞 
AMP pages don't work when the blog is in a subdirectory. A redirection occurs to the post slug without the subdirectory.

e.g. visiting `localhost:2368/blog/welcome-to-ghost/amp` -> `localhost:2368/welcome-to-ghost/`

### Steps to Reproduce

1. Setup ghost blog in subdirectory
2. Run Ghost
3. Go to any post, add `/amp` to end of url
4. Observe a redirection and a subsequent "Cannot GET <url> error`

### Technical details:

* Ghost Version: 0.10.1
* Node Version: 4.5.0
* Browser/OS: Chrome 53
* Database: SQLite

**Comment by caloon** [comment]
I think this issue needs to be re-opened for Ghost 1.0. 

Example: 
https://www.cora.health/de/ratgeber/puls-normalwerte/amp redirects you to https://www.cora.health/puls-normalwerte/amp

**Comment by kirrg001** [comment]
@caloon Sorry to hear you are heaving trouble, but I am unable to reproduce on my blog.

If i serve https://www.cora.health/de/ratgeber/puls-normalwerte/amp/ it works, if i go to https://www.cora.health/de/ratgeber/puls-normalwerte/amp it doesn't work. Please swing by our [slack channel](https://slack.ghost.org) for further help.
