### ISSUE TITLE
upload theme.zip error 

### ISSUE THREAD

**Issue by colynxu** [TryGhost/Ghost#7357]
### Issue Summary

when i upload a theme by theme.zip, I meet the error, "The file type you uploaded is not supported".

### Steps to Reproduce

1. I use the "Upload a theme" model to upload theme.zip
2. i got the error message "The file type you uploaded is not supported."

### Technical details:

* Ghost Version: 0.10.1
* Node Version: 4.5.0
* Browser/OS: Ubuntu 16.04 LTS x64

**Comment by acburdine** [comment]
Hey @colynxu - this is most likely related to #7292. Going to close this as a duplicate for now, but could you please swing by our [slack channel](https://ghost.org/slack) so we can debug this further?
