### ISSUE TITLE
ghost 0.10.1 can't use qiniu storage

### ISSUE THREAD

**Issue by QingShui23** [TryGhost/Ghost#7358]
please update plugin
qiniu sdk http://developer.qiniu.com/code/v6/sdk/nodejs.html

thks！

**Comment by acburdine** [comment]
hey @QingShui23, this isn't an issue with Ghost itself 😄  There's already an open issue (minwe/qn-store#7) for the Qiniu storage adapter to be updated.

Thanks!

**Comment by minwe** [comment]
Fixed in v1.1.0: https://github.com/minwe/qn-store/commit/a1d4831fdbe06aa4bf894d17a09e305f72e598bd.
