### ISSUE TITLE
validate returned content in frontend_spec

### ISSUE THREAD

**Issue by disordinary** [TryGhost/Ghost#7361]
Currently when running our test suite content validates if the server returns the expected HTTP status code and a few header values match. We've been caught out by Ghost returning valid status codes and expected header values but no content.

In `core/test/functional/routes/frontend_spec.js` we should not only check that valid status codes are returned but that the result from the query is as expected.

**Note:** the code contains a TODO comment: `// TODO: Other pages and verify content` so this issue may already exist, a quick search didn't show it up however.

**Comment by kirrg001** [comment]
Going to close this one. I am pretty sure nobody will pick this up. We can re-open a new issue if we are concerned.
