### ISSUE TITLE
Downgrade asset helper to warning + Upload UI changes

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#7362]
Noting this down as a potential change(s) for 0.11.0 if, and only if we think there is time: 

I could downgrade the asset helper to a warning in gscan and return warnings from the endpoint on the server side of Ghost.

With this change, we'd want to communicate the warnings to the user in the upload modal. For this particular warning, it would be nice to supply the information that the cache may not clear properly unless this is done. i.e. I think Ghost can detect the warning, and do something custom with it?

In a similar vein, it'd be good if we could output the size of the file being uploaded. 

Finally, probably taking a bit too much artistic liberty here as I cannot find any reference material, however I was thinking file sizes, although useful, are not contextual so maybe displaying an indicator is nice?

* < 1mb - "5kb (small)" 
* < 10mb - "3mb (medium)"
* > 10mb "12mb (large)"

This is basically a brain dump because I remembered it, probable will have to wait.

**Comment by kevinansfield** [comment]
✋ I'm working on the client-side changes for this

**Comment by ErisDS** [comment]
This was closed by https://github.com/TryGhost/Ghost-Admin/pull/262 & https://github.com/TryGhost/gscan/pull/30
