### ISSUE TITLE
Search box in admin panel does not allow to use space

### ISSUE THREAD

**Issue by 6bytes** [TryGhost/Ghost#7369]
### Issue Summary

When using search box in the admin panel (top left corner) I can only search for one word phrases.

### Steps to Reproduce

1. Click on the search box in admin panel.
2. Try searching for a two word sentence.
3. If the first word returns any results, pressing "space" will load currently selected result thus ending your search.
4. If the first word does not return any result, pressing space will just clear the search box.

### Technical details:

* Ghost Version: 0.10.1
* Node Version: v0.10.46
* Browser/OS: Google Chrome 52, Win10 64bit with touch screen
* Database: sqlite3

**Comment by jloh** [comment]
I can reproduce this on my Ghost(Pro) blog using Google Chrome 52 on OSX 10.10.5
