### ISSUE TITLE
Long theme names break themes table layout

### ISSUE THREAD

**Issue by kevinansfield** [TryGhost/Ghost#7373]
### Issue Summary

Themes that result in very long names in the themes list break the button layout at desktop sizes.

<img width="537" alt="screen shot 2016-09-14 at 10 32 41" src="https://cloud.githubusercontent.com/assets/415/18507071/aaa5f2e4-7a66-11e6-9a12-f4b95cf867fe.png">
### Steps to Reproduce
1. Inspect a theme name element in web inspector and modify the text in the HTML to give it a long name.
### Technical details:
- Ghost Version: 0.10.1
- Browser/OS: Chrome 53

**Comment by KennethAshley** [comment]
I started working on this.

**Comment by ralph9** [comment]
By changing the margin-right property from 20px to 10px you can avoid the collapsing when a name is too long, but that also changes slightly the appereance of the options. Should I change the code even if it interferes with the UI guidelines? Thank you in advance and sorry for my english and  if the question isn't appropiate, it's my first (kind of) contribution to open source and I haven't found much material on that matter.

**Comment by kevinansfield** [comment]
@ralph9 thank you for taking the time to look into this 😄 in the future it's work checking the events list on an issue to see if anyone else has submitted PRs against the issue. In this case we have a couple of potential fixes, you can see the discussion in the PR - https://github.com/TryGhost/Ghost-Admin/pull/274

**Comment by ErisDS** [comment]
@kevinansfield can this be closed now?

**Comment by kevinansfield** [comment]
👍 Yep
