### ISSUE TITLE
Stub Amperize module to improve tests 

### ISSUE THREAD

**Issue by AileenCGN** [TryGhost/Ghost#7376]
At the moment, we're using [Amperize](https://github.com/jbhannah/amperize) in our `{{amp_content}}` helper to make our HTML AMP conform. 

Amperize should be stubbed to return values or errors we want. This would improve our tests and we would actually be able to test for error handling on our side and use fake image-sources instead of real one.

See comment [here](https://github.com/TryGhost/Ghost/pull/7374/files#diff-cb1a2ecaa2b4410972af26d4629db069R124)

**Comment by kirrg001** [comment]
Closing. I doubt anybody will work on this. We will try to optimise unit tests when continuing with #9178.
