### ISSUE TITLE
Internal tags showing up in RSS feed

### ISSUE THREAD

**Issue by cobbspur** [TryGhost/Ghost#7381]
Issue Summary

After adding internal tags to a post, the internal tag shows up in the RSS feed

Steps to Reproduce

Enable internal tags labs feature
Add some internal tags to a post
Check http://localhost:2368/rss
See that the internal tag pages are listed

Technical details:
OS: Windows 7
Browser: Chrome

Ghost master: commit b598656

**Comment by ErisDS** [comment]
Closed by #7385 / 23f57f5
