### ISSUE TITLE
DB zip import on Windows 7 fails client checks 

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#7387]
This probably has never worked and is rarely used, so low priority 😉 

Some work has been [done recently](https://github.com/TryGhost/Ghost-Admin/pull/256) to allow zip uploads for themes, and that now works, but the zip upload for the importer is still failing. 
### Steps to Reproduce
1. Export a json file
2. zip up the json file
3. Try to import the zip
### Technical details:
- Ghost Version: 0.11.0
- Node Version: 4.4.x
- Browser/OS: Windows 7 Chrome

**Comment by sh4d0wst0rm** [comment]
Hi I am new to open source contribution  . Need some help in starting with this issue ?

**Comment by ErisDS** [comment]
Hi @sh4d0wst0rm it's not clear from your message whether you're asking if this issue is free for you to work on, or whether you are asking for help?

If you need help, please swing by our [slack team](https://slack.ghost.org) - the #core-dev channel is for discussing contributions. If you're asking if this issue is available to be worked on then the answer is yes 😊

**Comment by ErisDS** [comment]
Going to close this, it's almost a year old and we've had no further reports or interest in fixing this. Can reopen if Windows 7 has a resurgence 😁
