### ISSUE TITLE
Post URL should not have trailing slash

### ISSUE THREAD

**Issue by kirkas** [TryGhost/Ghost#7391]
I understand the use of trailing slash for _category / tag_ as they somewhat represent a _parent_, but a _post_ is a _child_ url and shouldn't require slash (or at least being given the option not to have a slash).

`www.blog.com/category/` is a directory / parent
`www.blog.com/category/my-first-post` is a file / child

It create issue with social crawler https://github.com/TryGhost/Ghost/issues/4828
And someone already did a PR: https://github.com/TryGhost/Ghost/pull/1028

Argument: http://stackoverflow.com/questions/5948659/when-should-i-use-a-trailing-slash-in-my-url

**Comment by halfdan** [comment]
Hi @kirkas,
as mentioned in #4828, this is an issue with the crawler - not with Ghost. 

I don't think the traditional file vs. directory comparison makes sense in today's web anymore and especially in Ghost where a blog post does not map to an actual file. There's e.g. also `www.blog.com/category/my-first-post/edit` which is an action on the post (and something that doesn't suddenly turn the "file" into a "directory"). 

All in all I think it is a matter of opinion and Ghost decided to go with trailing slashes.

**Comment by acburdine** [comment]
@kirkas we use the Ghost issue tracker for issues with Ghost itself, and this is technically more of a feature request....for those we use https://ideas.ghost.org. If you like, please submit this feature request there.

Like @ErisDS [said in the older issue](https://github.com/TryGhost/Ghost/pull/1028#issuecomment-26267500) - doing this would not likely benefit a lot of users. That being said, if you put it on the wishlist I linked above, and enough people vote on it with a desire to change it, then we can re-think this.

Personally, I agree with @halfdan's comment.

**Comment by kirkas** [comment]
Yes it is a matter of opinion, and there's fair arguments on both side. the point is the config option is fairly easy to add, so why not having it and let people choose?

**Comment by acburdine** [comment]
@kirkas see the above response. Also, the technical requirements of adding a config option like that are not trivial at the moment, which is why it needs to be a feature request on the wishlist first 😄

**Comment by kirkas** [comment]
Fair!

**Comment by benwoodward** [comment]
This also breaks anchor links:

`<a href="#example">Example headline</a>` => `domain.com/page-url/#example` (should be: `domain.com/page-url#example`)

**Comment by kevinansfield** [comment]
@benwoodward that is not a "broken" anchor link, it's the correct anchor link for a page with a trailing slash.
