### ISSUE TITLE
line 10 of index.js disallows execution of node when running various node versions in nvm

### ISSUE THREAD

**Issue by cbanowsky** [TryGhost/Ghost#7394]
Recently upgraded to node, but the start-up check script kept invalidating the new upgrade.  I am running node 4.4.5 via nvm.  after commenting line 10 of index.js out I was able to finally get my install back up and running.

**Comment by ErisDS** [comment]
Hi there @cbanowsky,

From your [message in slack](https://ghost.slack.com/archives/help/p1474068009001522) (which contains way more info than you posted here btw, I'd have no idea what you were talking about if I hadn't also read that 😉 ), I can see that it's actually [this line](https://github.com/TryGhost/Ghost/blob/c7448c46bd20585a505d0b342f91b07021a68ded/core/server/utils/startup-check.js#L36-L36) that's causing you an error:

```
/var/www/ghost/core/server/utils/startup-check.js:36
            !semver.satisfies(process.versions.node, packages.engines.node)) {
                                                                     ^

TypeError: Cannot read property 'node' of undefined
    at Object.checkNodeVersion [as nodeVersion] (/var/www/ghost/core/server/utils/startup-check.js:36:70)
    at Object.check (/var/www/ghost/core/server/utils/startup-check.js:21:14)
    at Object.<anonymous> (/var/www/ghost/index.js:10:46)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3
```

It's not clear whether it's `process.versions` which is undefined, or `package.engines`, however `package.engines` is provided by Ghost in the package.json file, and `process.versions` is part of the [Node API](https://nodejs.org/api/process.html#process_process_versions).

Therefore, I'd suggest you either have a problem with the `package.json` file, or you need to raise a bug against `nvm`? I'd be interested to know which one is causing the problem, but I'm confident this is not a bug in Ghost.
