### ISSUE TITLE
Confusing production message

### ISSUE THREAD

**Issue by JohnONolan** [TryGhost/Ghost#7395]
When running in production:

![image](https://cloud.githubusercontent.com/assets/120485/18607997/203b7ed4-7cdd-11e6-88d5-88982f4d45b0.png)

This is literally *never* true, and is a silly thing to output. If blog_url is currently set as "http://my-ghost-blog.com" then it would make more sense to display a warning saying "blog url is not set" and instructions for how to set it

**Comment by ErisDS** [comment]
Gonna flag this up to @acburdine and close this. The new install process should make this problem go away :)
