### ISSUE TITLE
Google AMP: Invalid structured data element

### ISSUE THREAD

**Issue by julianxhokaxhiu** [TryGhost/Ghost#7396]
### Issue Summary

After Google started to index my blog ( https://blog.julianxhokaxhiu.com ), AMP results stated that there are two errors in the AMP markup. First let me show an example:

```
<script type="application/ld+json">
{
    "@context": "https://schema.org",
    "@type": "Article",
    "publisher": {
        "@type": "Organization",
        "name": "A Developer&#x27;s Blog",
        "logo": "http://blog.julianxhokaxhiu.com/content/images/2016/04/8bitme.png"
    },
    "author": {
        "@type": "Person",
        "name": "Julian Xhokaxhiu",
        "image": {
            "@type": "ImageObject",
            "url": "//www.gravatar.com/avatar/b5617bc9e7be91f93110e323d2f70e09?s=250&d=mm&r=x",
            "width": 250,
            "height": 250
        },
        "url": "http://blog.julianxhokaxhiu.com/author/julian/",
        "sameAs": []
    },
    "headline": "How to setup an SSH server on ZyXEL NSA320",
    "url": "https://blog.julianxhokaxhiu.com/how-to-setup-an-ssh-server-on-zyxel-nsa320/",
    "datePublished": "2013-06-29T16:45:03.000Z",
    "dateModified": "2013-06-29T16:45:03.000Z",
    "keywords": "Modding",
    "description": "Hi there, some days ago I bought a very kind NAS for myself after the (terrible) adventure with WD My Book World Edition II. Not that it was so bad but...after three years it was very old (Kernel 2.6.24) and not so much apps were supported nowadays.",
    "mainEntityOfPage": {
        "@type": "WebPage",
        "@id": "http://blog.julianxhokaxhiu.com"
    }
}
    </script>
```

The first error detected is:
- _*The attribute logo.itemtype has an invalid value.*_ As you see `publisher.logo` should be a Dictionary with `@type` entry, but currently is just a string ( URL path ).
- _*A value for the image field is required.*_ As you see there is no `image` entry in the root of the Dictionary.

Is it possible to fix them autonomously? Even better, can you streamline the fix?

Thank you in advance!

### Steps to Reproduce

1. Click https://search.google.com/structured-data/testing-tool?url=http%3A%2F%2Fblog.julianxhokaxhiu.com%2Fhow-to-setup-an-ssh-server-on-zyxel-nsa320%2Famp%2F#url=http%3A%2F%2Fblog.julianxhokaxhiu.com%2Fhow-to-setup-an-ssh-server-on-zyxel-nsa320%2Famp%2F
2. See the output on the right

Currently: two errors appears.

Expected: no errors.

### Technical details:

* Ghost Version: 0.11 ( lastest Docker image https://hub.docker.com/_/ghost/ )
* Node Version: The one inside the Docker
* Browser/OS: Doesn't matter.
* Database: The one inside the Docker

**Comment by alexbagirov** [comment]
+1
Had this for a long time.

**Comment by AileenCGN** [comment]
Hey @julianxhokaxhiu, this is not an issue with AMP in particular. The same errors will be shown for a regular blog post in [Google's structured data testing tool](https://developers.google.com/structured-data/testing-tool/). 

>The attribute logo.itemtype has an invalid value. As you see publisher.logo should be a Dictionary with @type entry, but currently is just a string ( URL path )

This is a warning and it results from a blog logo. Ghost will output a 100% valid `ImageObject` for `publisher.logo`, as soon as you provide a logo, which fits the [requirements](https://developers.google.com/search/docs/data-types/articles#amp-logo-guidelines) (< 60px height and <600px width). This is a workaround for now, until we implement full image handling in Ghost.

>A value for the image field is required. As you see there is no image entry in the root of the Dictionary

Google wants a blog picture lately. As soon, as you add an image to your blog post, this error will be gone. I know, this is not perfect, but that's what Google wants obviously. And as I said, the same error and warning will be show for your regular blog post.

We will close this issue for now. If you need any further assistance in optimising your JSON-LD data, please feel free to pass by in our [slack help channel](https://ghost.slack.com/).

**Comment by kirrg001** [comment]
http://ideas.ghost.org/forums/285309-wishlist/suggestions/7191829-image-optimization

**Comment by julianxhokaxhiu** [comment]
Thank you very much for the clarification. It helped me a lot!

Best regards, Julian

**Comment by air** [comment]
> As soon, as you add an image to your blog post, this error will be gone.

I don't quite understand what the fix is. My individual blog posts have images in them. My blog has a logo (set in Ghost Settings -> General).

Does the general blog logo have to be resized to a tiny (60px height) image?

**Comment by AileenCGN** [comment]
Hey @air,

> Does the general blog logo have to be resized to a tiny (60px height) image?

At the moment, I'm afraid it has to, if you want to have a 100% valid AMP post. But the `publisher.logo` errors are just warnings, so it might be ok to live without it. 

Please pass by in our [Slack channel](https://ghost.org/slack) for further questions. That's the place where you can get more help, rather than Github issues...

**Comment by asadisandhu** [comment]
Some Example for amp pages
http://2017movies.online/watch
