### ISSUE TITLE
"Theme name - 1.0.1" uploaded successfully but some warnings were generated... The helper {{ghost_foot}} should be present.

### ISSUE THREAD

**Issue by Lekhrajmehta** [TryGhost/Ghost#7398]
When i am uploading my theme this warning message i am getting "Theme name - 1.0.1" uploaded successfully but some warnings were generated... The helper {{ghost_foot}} should be present.

Please share with me its solution.

Thanks

**Comment by kirrg001** [comment]
Hey @Lekhrajmehta Can you please swing by our [slack channel](https://ghost.org/slack/) and ask for help there? We can provide better support there than in the Github issue tracker, and if this turns out to be an actual issue with Ghost this issue can be reopened.

**Comment by ErisDS** [comment]
@Lekhrajmehta Your theme has a warning, this means it is doing something that is considered wrong, but it will still work. You can choose to activate your theme and it will work, however any features powered by `{{ghost_foot}}` will not work.

If you're a user just wanting to upload a theme, you can pretty much ignore this for now - just remember if some advanced feature doesn't work later on, this may be the reason why. 

If you fancy having ago at fixing the error, see the documentation for  [ghost_foot](http://themes.ghost.org/docs/ghost_foot) and as @kirrg001 said, you can visit our [slack](https://ghost.org/slack) channel to get help.

If you're a theme developer you can use http://gscan.ghost.org to test out your themes. We'll add more detailed messaging there on how to fix each thing and why it is important.
