### ISSUE TITLE
Feature: Ghost CLI - new install & upgrade process

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#7414]
Ghost is currently really quite hard to install, and a pain to upgrade 😭

There is no standardised process for installing, with users installing it on different platforms and in different scenarios. Supporting all of these custom installations is time-consuming, and due to the varying environments, the error messages can be widely different (this is also a result of NPM's widely varied error handling).

Updating Ghost is at the moment a similarly varied process. A common feature request is for automatic updates, however due to the complexities of a continuously running process in Node, installation errors, and other such issues, this is at the very least incredibly difficult and at most impossible 🚫

To reduce the number of installation & upgrade issues that occur, and to enable implementation of automatic updates, it is necessary to develop a standard for installing, running and upgrading Ghost.

---
## Considerations for a standardised install:
- As there are so many environments that people choose to run Ghost in, it is going to be impossible to cover everyone's use case with one install tool.
- Instead, we should provide one, single, optimised, recommended environment in which Ghost runs well & is easy to setup & maintain. 
- Deviations and flexibility should be possible, but require the knowledge needed to successfully run & maintain Ghost outside of the recommended setup.

The recommended environment will be something along the lines of:

Ubuntu LTS + nginx + systemd + MySQL + Node.js v4 + SSL (+ Varnish?)

---
## Ghost CLI Overview

https://github.com/TryGhost/Ghost-CLI

Ghost CLI is our shiny new tool for providing a standardised install & upgrade process :tada:.

The new process for installing Ghost in a production environment will be:
- `npm install -g ghost-cli`
- `ghost install`

_(It already works, give it a go!)_

The installer will use various sub commands to check the environment is compatible (`ghost doctor`) and for setting up configuration (`ghost config`). There will also be `ghost start` and `ghost stop` commands. The installer will be interactive (with prompts) for all required information such as your blog URL, meanwhile Any configuration options which deviate from the standard install (such as switching databases) will be provided via command line flags.

The install process will default to production mode, and so will include requesting & configuring your blog URL. We'll also be working towards adding as much tooling around helping to configure nginx, systemd, setup ssh and so on as is possible.

We'll be adding one special install command `ghost install local`, which will do a quick-install using sqlite3 and assume no url etc is needed. This'll be a useful tool for theme and app developers to quickly get a development environment setup.

Upgrading Ghost will be a single command: `ghost update`. Long term we aim to turn this into a single click, and eventually an automatic process.

Bonus: By providing a CLI tool, we are also able to offload some of the burden of configuration management, environment checks, migrations etc which is currently in Ghost core, allowing us to streamline the startup time for Ghost (important for automatic updates :wink:).

---

This issue provides just a high-level overview of the new cli tools. For more details, keep an eye on the issues over on the Ghost-CLI repo: https://github.com/TryGhost/Ghost-CLI/issues.

**Comment by nuclearpengy** [comment]
Sounds rad, is the idea for this to require users to install from scratch or would a user running the latest release for example 0.11.0 be able to upgrade to this version?

Also would this cater for running multiple instances of Ghost on one server?

**Comment by acburdine** [comment]
@nuclearpengy This would definitely cater to running multiple Ghost instances 😄  (although each blog would be in its own isolated environment to some degree).

As far as upgrading from 0.11.0 - this would require users to install Ghost (the software) from scratch. Migrating DBs to the 1.0 version hasn't been discussed yet afaik - but I'm assuming there would be some sort of tool to do it :)

**Comment by nuclearpengy** [comment]
Ah, ok cool. Thanks @acburdine.

It'd be interesting/cool if one could use the same DB config settings when switching to the new version and maybe just install the new instances over existing ones (for example into /var/www/site1 and /var/www/site2), so that not too much additional NGINX/Apache and SSL changes need to be implemented if multiple site were already running on one machine.

Keen to follow along as this evolves. 😄

**Comment by sp90** [comment]
Are this still gonna support using ghost as a middleware?

**Comment by J-Siu** [comment]
Can we also have ghost support SSL config, so we don't need to use a front end proxy server(eg. nginx, apache) ?

**Comment by ErisDS** [comment]
@J-Siu The ghost-cli tool will help you to setup both Nginx and SSL. A web server is required for more than just SSL.

**Comment by QzSG** [comment]
It would be awesome if other than this 

> The recommended environment will be something along the lines of:
Ubuntu LTS + nginx + systemd + MySQL + Node.js v4 + SSL (+ Varnish?)

We could have support for docker containers or cloud deployments too.

**Comment by ErisDS** [comment]
> We could have support for docker containers or cloud deployments too.

This misses the point of this issue. From Ghost 1.0 there will be **one official way to install Ghost**. If you want to use docker or something else, that's your choice of course, but it won't be the officially supported way to do it.

**Comment by J-Siu** [comment]
What is the specific/technical reason to have a front end web/proxy server? Ghost is using expressjs and should be easy to introduce the ssl parameters.

**Comment by ErisDS** [comment]
Ghost is a publishing application which runs on port 2368. It is not a web-server, nor do we have any intention of adding features that a web server would or should have because nginx already does that stuff really, really well. 

If you want more of an answer than this, [there](https://www.quora.com/Should-I-host-a-node-js-project-without-nginx) is [plenty](http://stackoverflow.com/questions/16770673/using-node-js-only-vs-using-node-js-with-apache-nginx) of [content](http://blog.argteam.com/coding/hardening-node-js-for-production-part-2-using-nginx-to-avoid-node-js-load/) around about why you should use a web server in front of node/express. 

If you have more questions about this sort of thing, please swing by our [slack](https://ghost.org/slack) team rather than leading this issue further down a tangent 😉

**Comment by QzSG** [comment]
If it is indeed a publishing application, it should easily be platform agnostic, I was under the impression that a standard install for an application means supporting the bare minimal way to make it run without any problems. Wouldn't the standard "Official" supported install introduce added redundancy which will make configuration for other environments difficult?

**Comment by ErisDS** [comment]
>  it should easily be platform agnostic

That's a really flippant statement. We've been trying to be platform agnostic for 3 years. It is not easy, that's why this issue exists:

> There is no standardised process for installing, with users installing it on different platforms and in different scenarios. Supporting all of these custom installations is time-consuming, and due to the varying environments, the error messages can be widely different (this is also a result of NPM's widely varied error handling).

We've tried it one way, it didn't work for us. Now we're going to try something different ;)

> Wouldn't the standard "Official" supported install introduce added redundancy which will make configuration for other environments difficult?

That's kind of the point. We want everyone to install it the same way to reduce our support overhead. This is so that we can spend our time on adding useful new features instead of triaging issues on various platforms.

**Comment by pascalandy** [comment]
> Ubuntu LTS + nginx + systemd + MySQL + Node.js v4 + SSL (+ Varnish?)

Will be awesome to have a best practice stack :)

**Comment by kirrg001** [comment]
FYI: Ghost-CLI release is managed via https://github.com/TryGhost/Ghost-CLI/projects/1

Any general should happen in our #dev channel in [slack](https://slack.ghost.org) 👍

**Comment by kirrg001** [comment]
The basic functionality is in place. Thanks to @acburdine. 
We are still optimising some use case and flows for production usage.
You can follow the process [here](https://github.com/TryGhost/Ghost-CLI/issues).

We have added a new wiki page, which guides you how to install Ghost with the CLI locally.
See https://github.com/TryGhost/Ghost/wiki/Developer-(Local)-Install

If you hit a bug with the Ghost-CLI, please raise here https://github.com/TryGhost/Ghost-CLI
Swing by our [slack channel](https://slack.ghost.org) if you need help or if you would like to share your feedback, thoughts or ideas.

Closing now.
