### ISSUE TITLE
Missing information in REAMDE.md that developer needs to install Bower and Ember CLI first

### ISSUE THREAD

**Issue by evolic** [TryGhost/Ghost#7416]
### Issue Summary

As a newbie in Ghost world I wanted to run it on my Windows 7.
I installed Node.js server also today, so it was fresh copy for both: the project and the server

I have an e-book called "Getting Started with Ghost" written by Kezz Bracey, David Balderston, Andy Boutte and went to Installing Ghost on Windows (local), where I can find following list of steps:
1. npm install --production
2. Inside the Ghost folder, there is a file called config.example.js
3. npm start --production

In the browser I got an error message that there was no template in themes (I realized that after some time - Google didn't help):
> ghost ERROR: Failed to lookup view "default" in views directory

I started digging and came to README.md file in project main directory.

I was doing steps described in this file, but also encountered some problems with missing commands.

A summary of the issue and the browser/OS environment in which it occurs. 

### Steps to Reproduce

*Initial requirement*
Have a fresh Node.js setup without Bower and Ember CLI

*Steps*
1. Follow in steps described in README.md so:
2. Install Grunt
`npm install -g grunt-cli`
3. Install Ghost
`npm install`
4. Build the things
`grunt init`

I think every fresh Ghost user should be guided what to do if this is also her/his first approach to Node.js world.

### Technical details:

* Ghost Version: master branch
* Node Version: v6.6.0
* Browser/OS: Mozilla Firefox 48.0.2 (but it can be skipped in this issue)
* Database: default (but it can be skipped in this issue)

**Comment by acburdine** [comment]
Going to close this as it's not an issue - see my comment in the PR.
