### ISSUE TITLE
Where is located config.example.js, which was present in version 0.11.0, but not present in master

### ISSUE THREAD

**Issue by evolic** [TryGhost/Ghost#7418]
### Issue Summary

By following some texts, in a book called "Getting Started with Ghost" written by Kezz Bracey, David Balderston, Andy Boutte and went to Installing Ghost on Windows (local), I wanted to adjust `config.js` and found that I can make a copy of `config.example.js`, but I cannot find it in the repository.

I don't know why this file is not present and if it was made intentionally or just by some mistake?

### Steps to Reproduce

not available

### Technical details:

* Ghost Version: master
* Node Version: v6.6.0
* Browser/OS: not applicable
* Database: not applicable

**Comment by halfdan** [comment]
Hi @evolic,
Ghost is undergoing a massive rewrite as we prepare for 1.0. The book you mention hasn't caught up with recent changes yet, so expect some deviations. It is also not a good idea to work off of Ghost master nor node v6.6. The currently recommended version is node4.2 and you should probably just download a recent Ghost release from http://ghost.org/download

**Comment by halfdan** [comment]
It is http://support.ghost.org/supported-node-versions/

**Comment by acburdine** [comment]
Going to close this as it's not an issue.

**Comment by ErisDS** [comment]
@evolic If you need help, the best place to go is to our [slack](https://ghost.org/slack) channel
