### ISSUE TITLE
Google - AMP errors

### ISSUE THREAD

**Issue by jsinh** [TryGhost/Ghost#7425]
### Issue Summary

See this warning mails from Google, not sure how to fix it
Screenshot attached

### Steps to Reproduce
See APM Errors takes me to list of my blog's pages (almost all of them are listed there)

![2016-09-22_01-48-19](https://cloud.githubusercontent.com/assets/1277539/18727609/0a392a72-8067-11e6-860a-4cc6c85a68ce.png)

### Technical details:

* Ghost Version: 0.10.1
* Node Version: v4.5.0
* Browser/OS: N/A
* Database: MySQL

**Comment by acburdine** [comment]
Hey @jsinh! So there were a couple of amp bug fixes in Ghost 0.11, can you update to that version and see if the errors are fixed?

Also, without seeing the actual erorrs themselves we can't actually debug this :smile: that screenshot doesn't actually say what's wrong.

**Comment by QzSG** [comment]
Another one reporting in:

Googel just cached my amp pages

Using the Structured data testing tool. It seems to output an error under the publisher logo being a url

```json
"publisher": {
        "@type": "Organization",
        "name": "QzSG",
        "logo": "https://i.imgur.com/nDwEReeg.jpg"
    }
```

The above outputs a 
`warning https://i.imgur.com/nDwEReeg.jpg (The attribute logo.itemtype has an invalid value.)`
 I thought this was fixed when the AMP feature was merged into master a month ago where json-ld would be using imageobject for all images? Im using bluemix to host with imgur as my "image store"

The only error I got was that the test checker wants an image for my "article" which I did not have.
`image	A value for the image field is required.`

I wonder if @jsinh have the same or worse errors?

My technical details:
Ghost Version: 0.11.0
Node Version: v4.5.0
Database: MySQL
External Image Store: imgur

**Comment by AileenCGN** [comment]
Hey @QzSG, 

the publisher logo will be a 100% valid `ImageObject` when it fit it the image dimension requirements: https://github.com/TryGhost/Ghost/issues/7095

As long as we don't have image handling implemented, you will have to do this workaround and provide a logo, which fits in these dimensions (<60px height and <600px width). Also, the `publisher.logo` error is just a warning and not a real error. 

Plus: this is not an AMP specific issue, as you will get exactly the same errors and warnings for your regular blog post equivalent. It just seems that Google is more pedantic about the structured data on AMP sites.

Hope, I could help you. Feel free to pass by in our [Slack channel](ghost.slack.org), if you have any further questions!

Cheers, Aileen

**Comment by jsinh** [comment]
More info as above screenshot does not suffice as per @acburdine 

![2016-09-22_18-01-15](https://cloud.githubusercontent.com/assets/1277539/18748292/351b7b4a-80ef-11e6-8371-8882399388c6.png)

![2016-09-22_18-04-54](https://cloud.githubusercontent.com/assets/1277539/18748296/3c3fe85c-80ef-11e6-86aa-8271896524a9.png)

![2016-09-22_18-04-23](https://cloud.githubusercontent.com/assets/1277539/18748300/410aadae-80ef-11e6-9466-b62d9425ee51.png)

![2016-09-22_18-05-15](https://cloud.githubusercontent.com/assets/1277539/18748305/466660c2-80ef-11e6-8afa-66eeed766d83.png)

@kirrg001 - I don't understand why this issue was closed. Please provided more insight on how can I fix it or make it work!

**Comment by jsinh** [comment]
@kirrg001 My bad - read @QzSG @AileenCGN 's comments quickly.

Yes so I too have a publisher.logo error. That logo is of size 256x256px - should I upload a 159x159px instead and see if that helps?

**Comment by AileenCGN** [comment]
Hey @jsinh, I can help you here.

The errors and warnings are exactly the ones I'm talking about.

The first one is `publisher.logo`. That means, you'll have to use a blog logo which fits in the size requirements of Google (<60px height and <600px width). Also, this is just a warning.

The error you're getting is not AMP specific as well. Again, you'll get exactly the same output in the structured data testing tool with your regular blog post.

Lately, Google wants to have an article picture. That means: without a post image, you'll get this error. As soon as you supply one, the structured data testing tool will give you a 👍

We have this Google request on our radar and will work on a solution for it soon.

Hope I could help you! Feel free to join our [Slack channel](slack.ghost.org) for any further question.

Cheers, Aileen

**Comment by AileenCGN** [comment]
Your logo has to be maximum 60px high!

Read here: https://developers.google.com/search/docs/data-types/articles#amp-logo-guidelines

**Comment by jsinh** [comment]
@AileenCGN - I understand that. I resized the blog logo to 60x60px now and replaced the previous one in content / images / xx / xx folder.

On my blog, I do not use the post image feature at the moment and I do not have any post that contains a post image. How can I fix the AMP error where I do not have a post image?

Thanks!

**Comment by AileenCGN** [comment]
@jsinh There is no solution other than using post images. You could try and convince Google, tho... 

![image](https://cloud.githubusercontent.com/assets/8037602/18749224/1ed410b8-80d6-11e6-8c35-4ad7044bee59.png)

**Comment by jsinh** [comment]
@AileenCGN - So this will in future plans to be fixed for ghost releases, not asking dates 😉 ?

Based on above screenshot, in case I add post images to all my post (not sure when I will be done with that) - the recommended size should be atleast 696px in width and no constraints on height? please confirm?

**Comment by jsinh** [comment]
@AileenCGN - Knock knock, any comments on above question? (referring last comment I posted), thanks!

**Comment by AileenCGN** [comment]
Hello @jsinh, 

>So this will in future plans to be fixed for ghost releases, not asking dates 😉 ?

We're working on image-optimisation very soon and will find a solution for Google's demand to always have a post image.

If you add post images to all your blog posts, this should fix it.

Please pass by in our [slack channel](https://ghost.slack.com) for any further questions. This is an issue tracker, and not made for support questions. On slack, we're able to help you faster and much better.

**Comment by jsinh** [comment]
@AileenCGN Thanks for the info!
