### ISSUE TITLE
Validation (isIn) failed for visibility

### ISSUE THREAD

**Issue by devrchancay** [TryGhost/Ghost#7438]
### Issue Summary

This happens when I go up the main image posts and when I change the date of publication scheduled to leave the post.

![pasted](https://cloud.githubusercontent.com/assets/4138285/18839835/099d3eaa-83d2-11e6-8ec2-c867b810afc3.png)

### Technical details:

* Ghost Version: 0.11.0
* Node Version: 4.2.3
* Browser/OS:  Ubuntu 14.02
* Database:  Mysql

**Comment by kirrg001** [comment]
Hey @devrchancay Sorry to hear you are having trouble.
Could you please write down the steps to reproduce this bug more detailed?
Then we can investigate and maybe tag as a bug. Thank you 👍

**Comment by devrchancay** [comment]
Hello @kirrg001 

## Error with used the image of the post

* 1 Select and upload the image of the post
* 2 Apparently load (I did not and verified in the archives)
* 3 the error occurs

## Error when trying to leave the post scheduled
* 1 Change the date of publication at a later date to the current
* 2  The error occurs

**Comment by kirrg001** [comment]
I am not able to reproduce.

1. Are you able to send the request body values?For example with Chrome Developer console or something similar.
2. Does this error appear on a fresh new post without tags?

**Comment by devrchancay** [comment]
### Only by creating the new post no problems after not let me edit :sob: 
when sending this data. 422 http
![pasted 1](https://cloud.githubusercontent.com/assets/4138285/18850721/56a8eb5a-83fe-11e6-8782-d996d83b22ab.png)

**Comment by kirrg001** [comment]
@devrchancay can you also show the failed request payload?(the red one)

**Comment by devrchancay** [comment]
@kirrg001 :eyes: 

![pasted 2](https://cloud.githubusercontent.com/assets/4138285/18878435/29b1b81e-8496-11e6-915b-9fb0ca00eefa.png)

### Payload

![pasted 3](https://cloud.githubusercontent.com/assets/4138285/18878449/354672be-8496-11e6-8e1b-882678986db7.png)


I thought it was a problem with the date and time of the server.

Can you give me give a hint that it might be?

**Comment by kirrg001** [comment]
@devrchancay Thanks. Are you able to write me a message in [slack channel](https://ghost.org/slack/)?I am online.

I need to see your database values of a post. 
If this turns out to be an actual issue with Ghost, this issue can be reopened.
