### ISSUE TITLE
Ghost RSS Issue

### ISSUE THREAD

**Issue by uditgoenka** [TryGhost/Ghost#7445]
### Issue Summary

After I upgraded to Ghost 0.11, I have been having trouble with my RSS feed as it's throwing all kinds of error as you can see below in the screenshot:

![image](https://cloud.githubusercontent.com/assets/1478769/18867376/99aa37ce-84c1-11e6-9080-a573628229dc.png)

Here is the direct RSS Feed Link:
[https://gopbn.com/blog/rss/](https://gopbn.com/blog/rss/)

How do I go about sorting this issue?

### Technical details:

* Ghost Version: 0.11
![Char Details](https://cloud.githubusercontent.com/assets/1478769/18900758/56b45444-8562-11e6-8380-9188c8d9ddaf.png)

**Comment by ErisDS** [comment]
Hi @uditgoenka, this is nothing to do with the encoding of your database ;) 

0x0C is a Form Feed character http://www.numberplanet.com/number/0c/index.html
This is not allowed in RSS feeds. It's not a normally typed character so  I'd guess you copy and pasted something?

 For more information you can see this similar comment](https://github.com/TryGhost/Ghost/issues/6774#issuecomment-216666444) which links to the [bug open here](https://github.com/dylang/node-rss/issues/49).

**Comment by uditgoenka** [comment]
Got this resolved! Thanks :)
