### ISSUE TITLE
Feature: Ghost OAuth login system

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#7452]
Since launching Ghost, 3 years ago, we've struggled with several issues related to being a distributed, decentralised system with individual logins:
- Each user is unique, meaning that every time a user creates a blog or is invited to a blog, they have to setup and manage another email & password combo.
- The user system is not flexible or extensible, meaning that we can't add support for other types of login (like with facebook) or extensions like Two-factor authentication.
- The two issues above combined means we don't have single-sign on for Ghost(Pro). This generates a very high % of our support requests for Ghost(Pro) because you need separate logins for each blog, and Ghost.org itself, with settings scattered everywhere.
- Being decentralised leaves us unable to integrate external tooling into Ghost, like support or a marketplace.
- There's no good way for us to provide integrations with other OAuth services (like twitter & facebook) because they all require a domain at the point of app registration.

These issues are only loosely related, however in all of these cases, the independent nature of each Ghost install and each Ghost user gets in the way of us being able to the provide powerful tools with a great user experience, that we've been dreaming of since day one. 

So we've hatched a plan.
### GhostAuth

From Ghost v1.0 the default way to create an account on a new Ghost install will be to "Login with Ghost". We're going to be providing a centralised global authentication system via Ghost.org, so that you can seamlessly login to Ghost.org, multiple blogs, and any other services we offer, with a single account.

This will be provided via a new "GhostAuth" service running an OAuth2 provider. 

Account creation, user login, password resets and user invites will all go through the GhostAuth system. GhostAuth will also provide several global profile fields, so that, for exmaple, if you update your avatar, it'll automatically update across all blogs.

GhostAuth will act as a single global login for all your blogs. This will provide a smoother experience for all Ghost users, who will only have one login across any Ghost blog or native application.

For blogs connected to GhostAuth, we'll be able to seamlessly integrate with other OAuth providers, like facebook and twitter, without needing each individual blog to register clients with those providers. 

**What if I don't want to use GhostAuth?**

No worries, there will be a config option to switch to using traditional local auth instead of GhostAuth. From this point forward GhostAuth will be the new default authentication mechanism for Ghost, as it allows us to provide far-and-away the best end user experience.

We’re really excited about all of the possibilities this opens up for Ghost as a platform, and all of the new integrations and services that we can now build as a result!

**Comment by disordinary** [comment]
I you have to register during the login process you don't get the option to allow the Ghost to access your account, you have to close the popup window and login again.

**Comment by nuclearpengy** [comment]
Is the idea that existing Ghost (Pro) installs will be switched across to GhostAuth or will each Ghost (Pro) user be able to enable/disable this functionality on a per domain basis?

**Comment by ErisDS** [comment]
Ghost(Pro) users will need to use GhostAuth as this will be "the" login system for Ghost.org. Billing & management is moving inside of Ghost, and there will no longer be the need to use 2 different login systems - that's the beauty of what we're building 😄

**Comment by nuclearpengy** [comment]
Ah ok. Just wondered, thanks.

Will the user profiles still be managed within the blog instance itself (even though authentication is centralised) or will those also be centralized. For example if someone has two Ghost(Pro) instances, one for work and one for personal/play and currently uses different cover/header images and different profile pictures on each blog, would that still work or would a user with this type of use case need to register additional Ghost.org accounts with different email accounts in order to maintain the different "personalities" across the different Blogs.

**Comment by kirrg001** [comment]
Closing. The feature was implemented. If we hit any bugs or missing functionality, we can raise new issues 🐩
