### ISSUE TITLE
Drop support for Node.js v0.10, add support for v6 LTS

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#7466]
According to the Node.js Foundation Official [LTS Schedule](https://github.com/nodejs/LTS), tomorrow (1st October) is the end of support for Node.js v0.10 and the start of LTS support for v6.

In accordance with that schedule and our own [commitment to the Node.js LTS schedule](http://support.ghost.org/supported-node-versions/), we will be dropping support for Node v0.10 and adding support for v6.

We are currently in the process of releasing Ghost 0.11.1, which is a maintenance release with bug fixes and dependency updates. This will be the final version which officially supports Node.js v0.10.

Ghost 0.11.3 will be released as soon as the following conditions are met:
- [x] We've shipped 0.11.1
- [x] The Node Foundation have new v6 LTS version number
- [x] The Node Foundation have announced EOL for v0.10 (should be Oct 31st)
- [x] I have the time to create & publish the release

**Comment by ErisDS** [comment]
Note: the EOL for Node 0.10 is now happening on the 31st, instead of the 1st October. LTS for v6 will be declared somewhere mid-October. We'll update our plan as and when these announcements come, based on how close together they're going to be :)

**Comment by tlhunter** [comment]
Node v6 should become LTS on the 18th fwiw:

https://twitter.com/thealphanerd/status/786106360677142528

**Comment by postblue** [comment]
v6 became LTS this 2016-10-18 https://nodejs.org/en/blog/vulnerability/october-2016-security-releases/

**Comment by ErisDS** [comment]
I'm well aware. The LTS release will happen asap.

**Comment by ErisDS** [comment]
FYI, Node v6 support was merged in this week, however a bug deep on our Ghost-Admin dependency tree made releasing tricky. That is now resolved, however with Node v0.10 EOL happening early next week, I'm holding off from releasing until that has happened now.

Better news: we're vastly improving our internal release processes for Ghost v1.0, with the intention of releasing far more regularly than we ever have with pre 1.0 Ghost.

**Comment by ErisDS** [comment]
Ghost's Node version support has been updated in 0.11.3, and the [supported version guide](support.ghost.org/supported-node-versions/) has been updated to match.
