### ISSUE TITLE
📝 Add links to Node.js in README.md

### ISSUE THREAD

**Issue by catleeball** [TryGhost/Ghost#7482]
### Issue Summary

Small improvement to the README file: added links to Node.js downloads page in the installation instructions. I'm sure people can find it on their own, but having a link right there will save them a tiny bit of hassle. Sending the pull request shortly!

### Steps to Reproduce

1. View the readme file
2. Cry when you have to google "node.js download" on your nodeless machine

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

- Just a convenience link to make the documentation a little more friendly

**Comment by ErisDS** [comment]
Ah, I didn't spot there was an issue, closing for the same reasons outlined in the PR.
