### ISSUE TITLE
opening ghost error

### ISSUE THREAD

**Issue by JCappucc** [TryGhost/Ghost#7486]
### Issue Summary

Getting an error on opening the application.  This build worked a few days ago, I made no config changes

### Steps to Reproduce

I'm doing a git pull to jenkins(locally).  npm install npm start , errors on opening 
 http://localhost:2368  and shuts the build down as a failure

Same error occurs if I download and drop the project files into jenkins workspace

### Technical details:

* Ghost Version: ghost master, most recent master on git
* Node Version: v 4.5.0
* Browser/OS: Chrome
* Database: n/a

[debugfile.docx](https://github.com/TryGhost/Ghost/files/509698/debugfile.docx)

**Comment by ErisDS** [comment]
Hi there @JCappucc!

I have to admit, I'm confused. Why are you using Jenkins to run tests against our alpha software? It's under active development and we run our own tests on Travis. If you care that much about what we're doing, why not join our [slack](https://ghost.org/slack) team and talk to us 😕

You're also running tests on the source code, without running any build steps, which is what is creating the error in your case. I'm not sure how it ever worked, but again, alpha software :)

Highly recommend swinging by slack and chatting to us about whatever it is you're trying to do.

**Comment by JCappucc** [comment]
Hi Hannah,

So much appreciation for a speedy response, I know how valuable your time
is.  I totally understand your confusion, this was actually for a school
project.  We were to familiarize ourselves with jenkins (specifically with
pulling from GIT), and the professor actually recommended using the ghost
application.  No testing really needed to be done, just a deployment of an
application.  I have forwarded your comments to the professor in hopes that
he does not recommend this (the git version) in the future for the
project.  The next part of the project does not require the git pull, so
I'll be able to use the most recent release.

Again, appreciation for all that you do.  Keep on coding!

J

**Comment by ErisDS** [comment]
@JCappucc Ah, that makes a lot more sense. As much as I love that we got a mention, it wasn't a great recommendation as our repos contain source code only 👍
