### ISSUE TITLE
TypeError: [default.hbs] Expected a SourceNode, string, or an array of SourceNodes and strings. Got function push(source, loc)

### ISSUE THREAD

**Issue by akatasonov** [TryGhost/Ghost#7496]
### Issue Summary

Installed Ghost 0.11.1 and tried to open the home page (browser doesn't matter). Got HTTP 500 with the error message in the log:

ERROR: [default.hbs] Expected a SourceNode, string, or an array of SourceNodes and strings. Got function push(source, loc) {
Oct  5 18:33:59 katasonov ghost[25671]:     this.source.push(this.wrap(source, loc));
Oct  5 18:33:59 katasonov ghost[25671]:   }
Oct  5 18:33:59 katasonov ghost[25671]:  Rendering Error Page
Oct  5 18:33:59 katasonov ghost[25671]:  Ghost caught a processing error in the middleware layer.
Oct  5 18:33:59 katasonov ghost[25671]:  TypeError: [default.hbs] Expected a SourceNode, string, or an array of SourceNodes and strings. Got function push(source, loc) {
Oct  5 18:33:59 katasonov ghost[25671]:     this.source.push(this.wrap(source, loc));
Oct  5 18:33:59 katasonov ghost[25671]:   }

### Steps to Reproduce

1. Install ghost
2. Open home page in Chrome

### Technical details:

* Ghost Version: 0.11.1
* Node Version: 4.2.6 (arm64)
* Browser/OS: Chrome  53.0.2785.143 m on Windows 10
* Database: sqlite

Full stack trace is below:

Oct  5 18:33:50 katasonov ghost[25671]: ERROR: [default.hbs] Expected a SourceNode, string, or an array of SourceNodes and strings. Got function push(source, loc) {
Oct  5 18:33:50 katasonov ghost[25671]:     this.source.push(this.wrap(source, loc));
Oct  5 18:33:50 katasonov ghost[25671]:   }
Oct  5 18:33:50 katasonov ghost[25671]:  Rendering Error Page
Oct  5 18:33:50 katasonov ghost[25671]:  Ghost caught a processing error in the middleware layer.
Oct  5 18:33:50 katasonov ghost[25671]:  TypeError: [default.hbs] Expected a SourceNode, string, or an array of SourceNodes and strings. Got function push(source, loc) {
Oct  5 18:33:50 katasonov ghost[25671]:     this.source.push(this.wrap(source, loc));
Oct  5 18:33:50 katasonov ghost[25671]:   }
Oct  5 18:33:50 katasonov ghost[25671]:     at SourceNode_add [as add] (/home/ghost/node_modules/express-hbs/node_modules/handlebars/node_modules/source-map/lib/source-map/source-node.js:183:13)
Oct  5 18:33:50 katasonov ghost[25671]:     at SourceNode.<anonymous> (/home/ghost/node_modules/express-hbs/node_modules/handlebars/node_modules/source-map/lib/source-map/source-node.js:174:14)
Oct  5 18:33:50 katasonov ghost[25671]:     at Array.forEach (native)
Oct  5 18:33:50 katasonov ghost[25671]:     at SourceNode_add [as add] (/home/ghost/node_modules/express-hbs/node_modules/handlebars/node_modules/source-map/lib/source-map/source-node.js:173:14)
Oct  5 18:33:50 katasonov ghost[25671]:     at /home/ghost/node_modules/express-hbs/node_modules/handlebars/dist/cjs/handlebars/compiler/code-gen.js:86:14
Oct  5 18:33:50 katasonov ghost[25671]:     at Object.each (/home/ghost/node_modules/express-hbs/node_modules/handlebars/dist/cjs/handlebars/compiler/code-gen.js:93:7)
Oct  5 18:33:50 katasonov ghost[25671]:     at Object.merge (/home/ghost/node_modules/express-hbs/node_modules/handlebars/dist/cjs/handlebars/compiler/code-gen.js:85:10)
Oct  5 18:33:50 katasonov ghost[25671]:     at Object.mergeSource (/home/ghost/node_modules/express-hbs/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:314:24)
Oct  5 18:33:50 katasonov ghost[25671]:     at Object.createFunctionContext (/home/ghost/node_modules/express-hbs/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:249:23)
Oct  5 18:33:50 katasonov ghost[25671]:     at Object.compile (/home/ghost/node_modules/express-hbs/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:142:19)
Oct  5 18:33:50 katasonov ghost[25671]:     at Object.compileChildren (/home/ghost/node_modules/express-hbs/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:794:49)
Oct  5 18:33:50 katasonov ghost[25671]:     at Object.compile (/home/ghost/node_modules/express-hbs/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:97:10)
Oct  5 18:33:50 katasonov ghost[25671]:     at Object.compileChildren (/home/ghost/node_modules/express-hbs/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:794:49)
Oct  5 18:33:50 katasonov ghost[25671]:     at Object.compile (/home/ghost/node_modules/express-hbs/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:97:10)
Oct  5 18:33:50 katasonov ghost[25671]:     at compileInput (/home/ghost/node_modules/express-hbs/node_modules/handlebars/dist/cjs/handlebars/compiler/compiler.js:516:53)
Oct  5 18:33:50 katasonov ghost[25671]:     at ret (/home/ghost/node_modules/express-hbs/node_modules/handlebars/dist/cjs/handlebars/compiler/compiler.js:523:18)
Oct  5 18:33:50 katasonov ghost[25671]:     at Object.templates.execute (/home/ghost/core/server/helpers/template.js:23:42)
Oct  5 18:33:50 katasonov ghost[25671]:     at Object.navigation (/home/ghost/core/server/helpers/navigation.js:71:21)
Oct  5 18:33:50 katasonov ghost[25671]:     at Object.eval (eval at createFunctionContext (/home/ghost/node_modules/express-hbs/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:254:23), <anonymous>:18:166)
Oct  5 18:33:50 katasonov ghost[25671]:     at main (/home/ghost/node_modules/express-hbs/node_modules/handlebars/dist/cjs/handlebars/runtime.js:173:32)
Oct  5 18:33:50 katasonov ghost[25671]:     at ret (/home/ghost/node_modules/express-hbs/node_modules/handlebars/dist/cjs/handlebars/runtime.js:176:12)
Oct  5 18:33:50 katasonov ghost[25671]:     at ret (/home/ghost/node_modules/express-hbs/node_modules/handlebars/dist/cjs/handlebars/compiler/compiler.js:525:21)
Oct  5 18:33:50 katasonov ghost[25671]:     at renderTemplate (/home/ghost/node_modules/express-hbs/lib/hbs.js:483:13)
Oct  5 18:33:50 katasonov ghost[25671]:     at _stackRenderer (/home/ghost/node_modules/express-hbs/lib/hbs.js:524:9)
Oct  5 18:33:50 katasonov ghost[25671]:     at /home/ghost/node_modules/express-hbs/lib/hbs.js:503:7
Oct  5 18:33:50 katasonov ghost[25671]:     at Function.Waiter.done (/home/ghost/node_modules/express-hbs/lib/async.js:68:12)
Oct  5 18:33:50 katasonov ghost[25671]:     at renderTemplate (/home/ghost/node_modules/express-hbs/lib/hbs.js:494:11)
Oct  5 18:33:50 katasonov ghost[25671]:     at render (/home/ghost/node_modules/express-hbs/lib/hbs.js:531:5)
Oct  5 18:33:50 katasonov ghost[25671]:     at renderIt (/home/ghost/node_modules/express-hbs/lib/hbs.js:593:18)
Oct  5 18:33:50 katasonov ghost[25671]:     at /home/ghost/node_modules/express-hbs/lib/hbs.js:603:11
Oct  5 18:33:50 katasonov ghost[25671]:     at ExpressHbs.cacheLayout (/home/ghost/node_modules/express-hbs/lib/hbs.js:121:31)
Oct  5 18:33:50 katasonov ghost[25671]:     at parseLayout (/home/ghost/node_modules/express-hbs/lib/hbs.js:465:12)
Oct  5 18:33:50 katasonov ghost[25671]:     at /home/ghost/node_modules/express-hbs/lib/hbs.js:582:7
Oct  5 18:33:50 katasonov ghost[25671]:     at getSourceTemplate (/home/ghost/node_modules/express-hbs/lib/hbs.js:556:16)

**Comment by ErisDS** [comment]
Hi @akatasonov :) Sorry to hear you're having trouble.

This sounds very much like a local / env issue. I've downloaded 0.11.1 fresh and then run `npm install --production && npm start --producton`, then visited `http://localhost:2368` in a browser, and I don't encounter this.

A couple of quick questions: 
- how did you install Ghost exactly?
- what theme are you using?
- by "homepage" did you mean / or /ghost/ ?

**Comment by akatasonov** [comment]
Hi @ErisDS!

I have installed it using [this Ansible role](https://github.com/javaguirre/ghost-ansible). But I have inspected its code and it doesn't seem to do anything unusual: it creates a separate ghost user, creates a service (which is basically npm start --production), downloads and extracts ghost, installs dependencies with (npm install --production), copies config to ghost dir and launches the service.

I do have a custom theme installed (Odin) but it is not active. Both /ghost and / is giving me that error.

**Comment by ErisDS** [comment]
Hi there @akatasonov. I guess you have a few options:

- raise an issue against that ansible repository
- try our [slack](https://ghost.org/slack) community or stackoverflow to see if you can find someone who understands ansible to help you
- use one of the normal install processes (install from zip is preferred, but npm or git + build yourself also work).

I'm afraid I don't know anything about ansible, or why that might be causing this. If you get this same error when using one of the standard install processes then let me know and I will reopen.

**Comment by akatasonov** [comment]
@ErisDS this seems to be the same issue as #6265. I have installed Ghost manually using the manual but get the same error

**Comment by ErisDS** [comment]
In that case I recommend swinging by [slack](https://ghost.org/slack) so we can chat through what might be causing it. Same as I said on the other issue, I can't do much else than Google the error for you ;)

**Comment by akatasonov** [comment]
@ErisDS apparently the problem was caused by a buggy Node shipped with Ubuntu Xenial. Updated to the latest version from node source and the issue is gone

**Comment by ErisDS** [comment]
Hey @akatasonov thanks for letting us know what the problem was, will be able to provide a better answer next time 👍

**Comment by vielmetti** [comment]
@akatasonov - is there a bug report or issue for the problem with Node on Ubuntu Xenial? I am on a similar system now & want to make sure that I understand it.

**Comment by akatasonov** [comment]
@vielmetti I haven't created the issue for Ubuntu Xenial. However to me it seems as a bug in the arm64 version of the node shipped with Xenial. Feel free to open an issue if you like.
