### ISSUE TITLE
Potential Memory Leak added back in 0.11.1?

### ISSUE THREAD

**Issue by benbrandt** [TryGhost/Ghost#7507]
### Issue Summary

I upgraded to 0.11.1 last night and since the upgrade, it looks like the memory leak that was fixed in 0.10.1 has been reintroduced (or some other cause). Usually the memory on my server stays even, but whenever there is a memory leak the memory usage keeps creeping up.

![screen shot 2016-10-06 at 10 44 33 am](https://cloud.githubusercontent.com/assets/2111074/19163771/28c96046-8bb2-11e6-8997-a3e0e3af9c39.png)

### Technical details:

* Ghost Version: 0.11.1
* Node Version: 4.6.0
* Browser/OS: Ubuntu 16.04 
* Database: SQLite

**Comment by ErisDS** [comment]
@benbrandt the memory leak was, as far as our testing showed, identified and fixed in bookshelf 0.10.2: https://github.com/TryGhost/Ghost/pull/7402

I don't know how you installed or upgraded Ghost, but my recommendation would be to do the following just to rule out any dependency issues:
- stop Ghost
- `rm -rf node-modules` 
- `npm cache clear`
- `npm install --production`
- start Ghost again

Continue tracking and let us know if you still see the problem.

**Comment by benbrandt** [comment]
It looks like the npm-shrinkwrap.json for 0.11.1 is still referencing bookshelf at 0.10.1. Could that be the issue?

```
~  338  "bookshelf": {
~  339    "version": "0.10.1",
~  340       "from": "bookshelf@0.10.1",
~  341       "resolved": "https://registry.npmjs.org/bookshelf/-/bookshelf-0.10.1.tgz",
```

**Comment by ErisDS** [comment]
Oh fuck. Bookshelf is still marked as 0.10.1 in the package.json as well both on master and lts 😩  Death by typo.

I recommend upgrading manually for now. You will need to delete the `npm-shrinwrap.json`, then either edit the `package.json` and run `npm install --production`, or just run `npm install bookshelf@0.10.2`

 I'll ship a new LTS asap (probably Monday)

**Comment by benbrandt** [comment]
Awesome yeah I tried `npm install bookshelf@0.10.2` first and it said `invalid` which led me to dig into the shrinkwrap file. I'll keep my eye on it, but hopefully that fixed it.

Thanks for the help and all you do to make ghost awesome! 👍

**Comment by ErisDS** [comment]
@benbrandt Thanks 😁  It would be super awesome if you could let me know in a day or two (or on Monday) if that did in fact fix the issue. Gives me a strong data point for an LTS release 😉

**Comment by benbrandt** [comment]
Can do!

**Comment by benbrandt** [comment]
Holding steady for the last 6 hours (usually would show up by) so I think we're in the clear. Will check again in a day or so and let you know if anything has changed.

![screen shot 2016-10-07 at 2 08 31 pm](https://cloud.githubusercontent.com/assets/2111074/19205491/a99ea3f8-8c97-11e6-9528-2208e0f14635.png)

**Comment by benbrandt** [comment]
All is still good after the weekend. Looks like that solved the issue!

**Comment by ErisDS** [comment]
Cool @benbrandt, we will release the `lts` branch (which already has the fix) asap this week.
