### ISSUE TITLE
localhost:2368 hard coded?

### ISSUE THREAD

**Issue by dysinger** [TryGhost/Ghost#7512]
### Issue Summary

Links contain "localhost:2368" even though I'm behind a proxy and have site the site url correctly in my config.js

### Steps to Reproduce

1. This is the first step

Set up a site for yourself on any domain. Set the url in your config.js to this domain. Take for example "https://www.kh6e.org" (real example & site running)

2. This is the second step, etc.

The logo link, the sharing links at the bottom of the article & the default tag url is "localhost:2368" instead of the "https://www.kh6e.org" root. This breaks a bunch of things.

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

I expect it to be aware of the public URL & use that instead of localhost:2368 which I don't even have anywhere in my configuration file (I have 127.0.0.1 2368 in there)

### Technical details:

* Ghost Version: 0.11.1 - from the official docker image
* Node Version: 4.x - from the official docker image
* Browser/OS: chrome/linux
* Database: sqlite3

**Comment by dysinger** [comment]
user error

**Comment by chandwki** [comment]
@dysinger well, what was the solution?

**Comment by kevinansfield** [comment]
Hey @chandwki 👋 Typical problems that will cause this are:

1. not restarting ghost after making changes to the config file
2. setting the `url` in the `development` section of the config when ghost is running in `production` (or vice-versa)

If you need help with a ghost install please check out the [slack community](https://slack.ghost.org) where there's always someone willing to help 😄 We use GitHub for bug tracking and on-going development only and so don't offer support here.

**Comment by codingkapoor** [comment]
Has anyone found a solution to this problem, yet?

**Comment by codingkapoor** [comment]
I solved this problem by following the suggestion mentioned here: https://github.com/TryGhost/Ghost/issues/8966#issuecomment-326746476

**docker-compose.yml**
```           
environment:
      - url=http://www.shivamkapoor.com/blogs/technology
```

**config.production.json**
```
  "url": "http://localhost:2368/blogs/technology",
  "server": {
    "port": 2368,
    "host": "0.0.0.0"
  }
```
