### ISSUE TITLE
Cannot read property 'zone' of undefined

### ISSUE THREAD

**Issue by Kibos** [TryGhost/Ghost#7514]
In centos 7 ,I have this Issues:

Cannot read property 'zone' of undefined

**Comment by ErisDS** [comment]
This is a duplicate of https://github.com/TryGhost/Ghost/issues/7449. 

When raising issues, deleting the template and not including the information we ask for makes it pretty hard for us to help ;) Swing by teh #help channel in slack and maybe someone can help you figure the problem out.

**Comment by aid414944** [comment]
You can try change fourth line text, from "moment = require('moment')" to "moment = require('moment-timezone')" in /ghost/core/server/data/validation/index.js file.
