### ISSUE TITLE
New Save Button component

### ISSUE THREAD

**Issue by JohnONolan** [TryGhost/Ghost#7515]
![image](https://cloud.githubusercontent.com/assets/120485/19186676/b3708794-8c87-11e6-84d2-5465be5afff2.png)

Updated design for save button component, with 4 states:
### 1. Default
- Button appears normal, and reads "Save"
- When button is clicked, go to `saving`
### 2. Saving
- Button gets animated SVG loading spinner, and still reads "Save"
- Button automatically transitions to either `success` or `fail`
### 3. Success
- Button gets SVG check icon, which animates-in, and reads "Saved"
- Button **Remains in this state**
- When button is clicked, go to `saving`
### 4. Fail
- Button gets SVG x icon, which animates-in, and reads "Retry"
- Button **Remains in this state**
- When button is clicked, go to `saving`
### Notes
- Colours and button style are unimportant / just for reference. The important thing is the icons and the behaviour.
- I found an SVG loading spinner generator [here](http://loading.io/)
- I don't have an animated check or X icon, we'll need to either find or make them
- Button should not change width between states
- This issue isn't a priority that needs doing right now, just creating it so that it exists!

**Comment by kevinansfield** [comment]
Do we want to have the spinner displayed for a certain period or can the switch to the `Saved` state be nearly instantaneous?

**Comment by Saytuamin** [comment]
This idea would definitely be welcome, The current save button is rather basic and it would be good to update it to a more responsive design.

**Comment by kevinansfield** [comment]
The functionality for this has been added via https://github.com/TryGhost/Ghost-Admin/pull/566. We still have some design work left, namely the animated icons and a review of how the fixed-width should work if the success/failure message is longer than the default message.

There are still a few places where we are not yet using the save-state button, these are being tracked in https://github.com/TryGhost/Ghost/issues/7865

**Comment by kevinansfield** [comment]
Closing as complete. The fixed-width requirement still needs some work/discussion so I've opened a new issue for that https://github.com/TryGhost/Ghost/issues/8341
