### ISSUE TITLE
Where is the config.js file.

### ISSUE THREAD

**Issue by jamrizzi** [TryGhost/Ghost#7521]
Where is the config.js file????? You took it away!!!!

**Comment by acburdine** [comment]
@jamrizzi The config.js file is only gone in the new Ghost 1.0 alpha releases. It has been replaced by a json-only configuration system based on [nconf](https://github.com/indexzero/nconf). The LTS version of Ghost still uses config.js 😄 

Also, in the future please visit our [slack](https://ghost.org/slack) channel for questions like this. Thanks!
