### ISSUE TITLE
Post pages not responding when using CORS https post image

### ISSUE THREAD

**Issue by blatinier** [TryGhost/Ghost#7525]
### Issue Summary

When running in https, adding a post image via an URL which is not in the same domain but also in https, post visualisation page time out (after 120s) with no logs, no data send etc… brower end up issuing a 502 proxy error.

### Steps to Reproduce

1. Set up ghost with https on domain X
2. Create post
3. Go in the post parameters to set up image
4. Do not upload an image but use a link instead
5. Choose an image which is on another site using https too (i.e. https://Y/my-image)
6. Go to your post page, and wait for your browser to do nothing and then 502.

Notes:
- This doesn't happen for pages (which seems odd to me but why not).
- I didn't tried to set up the image from the same domain so I don't know if it's just the https or the https + cross-domain which fails, however, simple cross domain works.

### Technical details:

* Ghost Version: 0.11.1
* Node Version: 0.10.29
* Browser/OS: Debian 8 (Jessie) for the server, Archlinux + firefox
* Database: sqlite

**Comment by ErisDS** [comment]
@blatinier thank you for the detailed bug report 👍  we are investigating the issue & will post again when we have more info.

**Comment by ErisDS** [comment]
@blatinier could you possibly provide a url for an image that fails for you? We've attempted to reproduce this under HTTPS on Ghost(Pro) and in local dev environments and have not been able to.

**Comment by blatinier** [comment]
I change the image from http to https here : https://www.melmelboo-voyage.fr/blog/2016/05/21/qui-sommes-nous-2/
Any other post from https://www.melmelboo-voyage.fr/blog/ works just fine.

Another thing: my ghost is on a subdomain (/blog) I don't know if it matters but maybe…

**Comment by ErisDS** [comment]
Hey @blatinier your blog doesn't load for me at all! Maybe the best thing to do would be to swing by the #help channel in [slack](https://ghost.org/slack) as this is seeming more and more like an environment issue rather than a bug in Ghost.

Going to close for now as we cannot reproduce and the behaviour you're reporting is different to what we see, if we find a bug, we'll reopen 👍
