### ISSUE TITLE
Docker/RPi - ERROR: Javascript files have not been built.

### ISSUE THREAD

**Issue by alexellis** [TryGhost/Ghost#7552]
This is the Dockerfile I use to successfully build 0.10.0 and earlier on a Raspberry Pi with Docker. The base image is Debian with Node.js 4.4. 

It now gives me an error when starting nodejs:

```
WARNING: Ghost is attempting to use a direct method to send email. 
It is recommended that you explicitly configure an email service.
Help and documentation can be found at http://support.ghost.org/mail.

ERROR: Javascript files have not been built.

Please read the getting started instructions at:
https://github.com/TryGhost/Ghost#getting-started
```

Originally I didn't have to invoke grunt separately but it appeared to be necessary in 0.10x.

Please could you offer some guidance?

Alex

```
FROM alexellis2/nodejs-armv6:4.4

USER root
WORKDIR /var/www/
RUN mkdir -p ghost

RUN apt-get -qy update && \
    apt-get -qy install --no-install-recommends \
      curl ca-certificates && \
    curl -sSLO https://github.com/TryGhost/Ghost/archive/0.11.2.tar.gz && \
    tar -xvf ./0.11.2.tar.gz -C ./ghost --strip-components=1 && \
    rm *.tar.gz && \
    rm -rf /var/lib/apt/lists/*

RUN useradd ghost -m -G www-data -s /bin/bash
RUN chown ghost:www-data .
RUN chown ghost:www-data ghost
RUN chown ghost:www-data -R ghost/*
RUN npm install -g pm2

USER ghost
WORKDIR /var/www/ghost
RUN /bin/bash -c "time (npm install sqlite3)"
RUN npm install

EXPOSE 2368
EXPOSE 2369
RUN ls && pwd

ENV NODE_ENV production
USER root
RUN apt-get update && apt-get -qy install --no-install-recommends git
WORKDIR /var/www/ghost
RUN chown ghost:www-data -R ./*
RUN git init
RUN npm i -g grunt-cli
USER ghost
RUN grunt init --force
RUN sed -e s/127.0.0.1/0.0.0.0/g ./config.example.js > ./config.js

CMD ["pm2", "start", "index.js", "--name", "blog", "--no-daemon"]
```

**Comment by kirrg001** [comment]
Hey @alexellis Why don't you use the release zip?
https://github.com/TryGhost/Ghost/releases/download/0.11.2/Ghost-0.11.2.zip
The difference is that the release zip contains a ready built client - so you don't need grunt.

Can you please swing by our [slack channel](https://ghost.org/slack/) and ask for help there?Thanks!

**Comment by alexellis** [comment]
Is there a possibility that you might consider distribution of the release as a tar.gz in the future? It sucks to have to install unzip just to consume the software on a system - particularly in a minimal Docker container. Thanks
