### ISSUE TITLE
Invalid AMP data

### ISSUE THREAD

**Issue by SeanHayes** [TryGhost/Ghost#7557]
### Issue Summary

I got an email from Google with the subject "Fix errors on your AMP pages". I opened the link to the Google Search Console and looked at the validator: https://search.google.com/structured-data/testing-tool/u/0/?url=https://www.tenor.co/blog/introducing-tenor-add-tone-to-your-conversation/amp/#url=https%3A%2F%2Fwww.tenor.co%2Fblog%2Fintroducing-tenor-add-tone-to-your-conversation%2Famp%2F

1 Warning:

> logo	
> https://media.tenor.co/blog/2016/10/TENOR_png-1.png (The attribute logo.itemtype has an invalid value.)

1 Error:

> image	
> A value for the image field is required.

### Steps to Reproduce

1. Visit: https://search.google.com/structured-data/testing-tool/u/0/?url=https://www.tenor.co/blog/introducing-tenor-add-tone-to-your-conversation/amp/#url=https%3A%2F%2Fwww.tenor.co%2Fblog%2Fintroducing-tenor-add-tone-to-your-conversation%2Famp%2F

### Technical details:

* Ghost Version: 0.11.1
* Node Version: 4
* Database: MySql

**Comment by AileenCGN** [comment]
This is the same like #7425 and #7396. It's not an AMP issue in particular.
