### ISSUE TITLE
Token refresh returns 401 when using Ghost OAuth provider

### ISSUE THREAD

**Issue by kevinansfield** [TryGhost/Ghost#7562]
### Issue Summary

When using centralised OAuth authentication, refreshing the `access_token` fails due to Ghost returning a `401 Unauthorised` error.

### Steps to Reproduce

1. Sign in to Ghost using the centralised auth provider
2. Wait for the `access_token` expiry timeout to trigger (it's probably useful to [temporarily change this](https://github.com/TryGhost/Ghost/blob/06151ef5acd8725ee95c94bd8248efe9e170f638/core/server/api/authentication.js#L160) to less than one hour)
3. Note that we get a 401 back from the API despite a well-formed refresh request and so we get logged out of the client

The `/authentication/ghost` behaviour should be as per the `/authentication/token` endpoint. I see two solutions:

1. Fix the `/authentication/ghost` endpoint to fully cover the token endpoint behaviour
2. Override the [default Ember Simple Auth behaviour](https://github.com/simplabs/ember-simple-auth/blob/1.1.0/addon/authenticators/oauth2-password-grant.js#L266-L285) so that we can provide separate token and token refresh endpoints.

### Technical details:

* Ghost Version: master (alpha)
* Node Version: 4.4.7
* Browser/OS: all/macOS
* Database: sqlite

**Comment by kevinansfield** [comment]
I think ESA's `_refreshAccessToken` method will need overriding in Ghost-Admin in any case as it's error handling no longer matches the error type that it will get back so I could certainly add the distinct endpoint configuration as proposed in `2.` at the same time.

I wonder if we should be consistent with token endpoints on the server - do we need the two separate endpoints or should we only have `/authentication/token` and the change it's behaviour depending on the configured authentication type. /cc @ErisDS

**Comment by kirrg001** [comment]
So when the access token expires, Ghost returns `401` on the current request, as you said.
Then ember sends `/ghost/api/v0.1/authentication/revoke`, which also ends in `401`.

**Password & Ghost auth types, for both the refresh token logic does not work right now**. 
Both get logged out. The logic for this is the same, because for both auth types, we use local tokens.

what does ember expect to refresh the token?

**Comment by kevinansfield** [comment]
> So when the access token expires, Ghost returns 401 on the current request, as you said.

No, before the `access_token` expires the client pings `/authentication/(token|ghost)` with a refresh grant request in order to get a new `access_token`. However the behaviour on the server is differing between the two different token endpoints:

`/authentication/token` = successful request, new `access_token` back 👍
`/authentication/ghost` = 401 response 👎 The client then treats that as a fully invalid session (which is wrong) so attempts to revoke the token before clearing it's local session details

**Comment by kirrg001** [comment]
Ok understand. Can you please double-check why password auth type was not working for me?

--

`/authentication/ghost` was until now not designed to offer oauth functionality like exchange a new access token with a refresh token. I agree we need some kind of consistency here.

I would suggest. I will work tomorrow on a solution for:
How we can provide only one endpoint (for example `/authentication/token`) and this endpoint changes it's behaviour depending on the auth type. I'll notify you when my PR is ready, so you can adapt changes in Ghost-Admin as well.
@ErisDS

**Comment by kirrg001** [comment]
Ghost will use `grant_type` authorization_code and forwards the code to Ghost.org.
Creating a PR soon 👍

**Comment by kirrg001** [comment]
closed via #7571 and https://github.com/TryGhost/Ghost-Admin/pull/335
