### ISSUE TITLE
Wording on update notice is misleading as what clicking the link will do

### ISSUE THREAD

**Issue by OscarSwanros** [TryGhost/Ghost#7563]
### Issue Summary

When a new update is available, a notice is shown with the following text: 

> Ghost 0.11.2 is available! Hot Damn. Click here to upgrade.

Which makes you think that clicking the link would trigger an auto-update.

### Steps to Reproduce

1. Install an older version of Ghost in a server.
2. Open the Ghost dashboard.

The wording should be updated to reflect that clicking the "Click here" link will take you to the instructions page, not actually upgrade Ghost. This has happened for a while, when I'm excited that Ghost finally can auto-update itself.

**Comment by ErisDS** [comment]
Hi there @OscarSwanros :) Sorry for the slow reply, and for the misplaced excitement. 

You'll be pleased to know that Ghost v1.0 comes with a CLI tool, which manages the process of updating Ghost. So, whilst the first iteration will probably need you to run a command, we'll be iterating on it until we have a button, and eventually, background auto-updates.

Therefore, the update notifications are going to be reworked before we ship Ghost 1.0 👍

**Comment by OscarSwanros** [comment]
@ErisDS Thanks for the response. That sounds really exciting! Looking forward to it.
