### ISSUE TITLE
Licenses status

### ISSUE THREAD

**Issue by franciscop** [TryGhost/Ghost#7570]
Hi, I thought on updating this 3-years old issue:

> [Verify License of All Ghost Dependencies](https://github.com/TryGhost/Ghost/issues/518)

I created a small tool for this same thing called [legally](github.com/franciscop/legally). Running it for `ghost` brings after waiting a while:

```bash
legally ghost -lr
```

![ghost](https://cloud.githubusercontent.com/assets/2801252/19386527/b429a01c-924f-11e6-8528-5fea35b2b10b.png)

If you have it locally, you can just do this to check them from the current package:

```bash
legally
```

It will also bring a list of all the node_modules and sub-modules installed if you want the details of them.

For instance, there seems to be 1 GPL license and 6 unlicensed packages, which looking at it seem to be:

- **[punycode](http://npmjs.com/package/punycode)**: double-licensed as `BSD + GPL` as specified in the `package.json`. Nothing else on the LICENSE or the README:

![punycode](https://cloud.githubusercontent.com/assets/2801252/19386926/1d6c8cc2-9252-11e6-9f97-87a679a41bc6.png)

- **[colors](https://github.com/Marak/colors.js)**: now it has the MIT License, but `legally` couldn't find it in the one installed inside `ghost` which [apparently it was inside MIT-LICENSE.txt originally](https://github.com/Marak/colors.js/tree/8e55ca411cee1d02ba51c3ad0bcdfc0844d81511). So no big problem here. Also, now it has the license on both `package.json` and `LICENSE`.

- **[jison-lex](https://github.com/zaach/jison-lex)** has the license inside a code block [in the README](https://github.com/zaach/jison-lex/blob/master/README.md) and it just states `MIT`.

- **[nomnom](https://github.com/harthur/nomnom)** now has the LICENSE as MIT, but the version you depend on doesn't have any.

- **[regexp-quote](https://github.com/dbrock/node-regexp-quote)** again it has the license inside a file called `MIT-LICENSE`, so it wasn't correctly parsed.

- **[require-all](https://github.com/felixge/node-require-all)** now has the MIT license but apparently the one you depend on didn't have any license.

- **[require-dir](https://github.com/aseemk/requireDir)** the same as above, it seems the version you depend on didn't have the license properly formatted but now it is MIT.

**It seems (disclaimer: none of this is legal advice and I am not a lawyer) that the only package that you have to check for license compatibility is punycode and that the rest have compatible licenses.**

Any improvement/missing bit you find in `legally` or if you want to add any feature to make it easier for using it to check Ghost's licenses is welcome.

PS, thanks for a great blogging platform!

**Comment by JohnONolan** [comment]
First of all - this is an awesome tool! Really really cool :)

As far as I can tell - punycode is now fully MIT - so no more issues: https://github.com/bestiejs/punycode.js
