### ISSUE TITLE
Feature: Attachments per blog post

### ISSUE THREAD

**Issue by gsollazzo** [TryGhost/Ghost#7593]
### Attachment feature
Add feature to attach arbitrary files to blog post.

### Proposal details

Attached files should appear at the end of the blog post with a standardised icon for common file types (eg. PDF).

### Examples

File access could be implemented like Gmail:

![image](https://cloud.githubusercontent.com/assets/12738685/19495487/e05e1028-9583-11e6-853d-e7909b5a4a47.png)

**Comment by acburdine** [comment]
Hey @gsollazzo, would you mind taking this idea to https://ideas.ghost.org ? We don't really do feature requests on the issue tracker as it is more of a place for bugs and ongoing work with the software.

Thanks!
