### ISSUE TITLE
Delete post does not work

### ISSUE THREAD

**Issue by kirrg001** [TryGhost/Ghost#7599]
I can't delete a post 🕵🏻

Getting this error in Ghost-Admin:
`Cannot read property '0' of undefined`. 

Looks like Ghost-Admin expects a response Ghost does not return?

Steps to reproduce:
1. create a post
2. delete a post

Ghost: Master

**Comment by kirrg001** [comment]
The post get's deleted, there is no error in Ghost.

**Comment by Kartikkh** [comment]
hey , it would be great for me to try this out ? 
so should I ?

**Comment by kirrg001** [comment]
@Kartikkh sure!Thank you!

**Comment by ivantedja** [comment]
@Kartikkh any update on this one? If not, I'm interested to work on this
