### ISSUE TITLE
Getting into Slack chat is very unclear

### ISSUE THREAD

**Issue by evil-shrike** [TryGhost/Ghost#7602]
I have an issue with setting up Ghost. I tried to get into Slack char to ask for help. 
I failed. 
At the same time I'm using Slack every day in several teams. 
Here's the problems:
* the page https://ghost.org/slack/ contains button "Open Slack". It doesn't work. Just nothing happens. I'm in Firefox.
* the page doesn't contain the team name anywhere! I guest it's "ghost" but is it hard to write it?
* the page says that I need to use "<my_ghost_account>@slack.ghost.org" address instead of my real email. Ok, but it says nothing about how to login with that address. How? I tried to use my Ghost account's password, tried to sending magic link. No luck.
I really can't understand how to log in your team.

**Comment by kevinansfield** [comment]
Hi @evil-shrike, sorry to hear that you're having trouble logging in to Slack. I've just tested it with a new account and clicking the button in Firefox did successfully take me to the Slack sign-up screen but it appears Slack is being slow at the moment - it took around 30 seconds for the page to display.

I'm going to close this as it doesn't appear to be a bug but rather some slowness on Slack's end. If you are still having issues after re-trying please e-mail support@ghost.org.

The current Slack setup is not ideal but now that Slack has made it possible to hide user's email addresses we will be looking at addressing the usability issues - the @slack.ghost.org email setup was in place to protect our user's privacy and not leak their e-mail address on a public Slack team, unfortunately it does make the process a little confusing at times.
