### ISSUE TITLE
Sending envitation via SMTP doesn't work

### ISSUE THREAD

**Issue by evil-shrike** [TryGhost/Ghost#7604]
### Issue Summary

I have simple mail config:
```
        mail: {
            transport: 'SMTP',
            options: {
                port: 25,
                host: 'smtp.lab.example.org',
                secure: false,
                from: 'robot@example.org'
            }
        },
```

I checked that the config is correct with a test script using nodemailer directly:

```
var nodemailer = require('nodemailer');
var transport = {
                port: 25,
                host: 'smtp.lab.example.org',
                secure: false,
                from: 'robot@example.org'
            };
var transporter = nodemailer.createTransport("SMTP", transport);
function sendMail() {
	var mailOptions = {
	    from: 'robot@example.org', 	// sender address
	    to: 'user@example.org', 	// list of receivers
	    subject: 'test',		// Subject line
	    text: 'Hello world', 	// plaintext body
	    html: '<b>Hello world</b>' // html body
	};
	transporter.sendMail(mailOptions, function(error, info){
	    if(error){
        	return console.log(error);
	    }
	    console.log('Message sent: ' + info.response);
	});
}
sendMail();
```

This script sends me a mail.
So the config is correct.
But Ghost is not sending anything. It reports no errors, saying "Invitation sent" but nothing happens.

### Steps to Reproduce

1. Just send an invitation

### Technical details:

* Ghost Version: 0.11.2
* Node Version: 6.9.1
* Browser/OS: Windows 2008 R2 Std SP1

Node is running via iisnode under IIS. IIS AppPool is running under NetworkService account. 

Is it expected to work? For some reason the doc doesn't contain info on direct SMTP usage. 
If it should how can I debug what is going on?

**Comment by kevinansfield** [comment]
Hi @evil-shrike, yes this is expected to work and was working when I tested just now which suggests it's possibly a configuration or setup issue - the best place to get help with those type of things is on our [Slack channel](https://ghost.org/slack/) as we don't provide support through Github issues.

If after working through the problem there it's found that a bug exists then we can re-open. Thanks!

**Comment by evil-shrike** [comment]
@kevinansfield could you take a look at my finding (as it looks like a bug)?

**Comment by ErisDS** [comment]
This is not a bug, but a configuration issue: http://support.ghost.org/mail/#from-address

**Comment by evil-shrike** [comment]
Moving `from` from `mail.options` up to under `mail` solved my issue, thank you!

It's a bit confused to see `from` under `mail` as nodemailer has that same option and it's ignored/overwritten in Ghost.
