### ISSUE TITLE
PR/Discussion: Yarn Support

### ISSUE THREAD

**Issue by amilajack** [TryGhost/Ghost#7610]
Would a PR for adding yarn support be welcome?

**Comment by kevinansfield** [comment]
@amilajack we've been testing it and are watching the yarn project but it's not ready for use yet, I've experienced issues around pulling dependencies from github pinned to specific commits for example. It also currently has issues with bower and `ember-cli` on the Ghost-Admin project is currently tied to npm. Once the problems are ironed out and there is enough support across all of our tooling that we can use it consistently everywhere we will re-evaluate it's viability for our needs.

That said, it's aim is to be compatible with npm's `package.json` so there's nothing to stop anyone who checks out Ghost using yarn to manage their dependencies.

**Comment by ErisDS** [comment]
Also, for the record, this sort of question belongs in [slack](https://ghost.org/slack) - where this is already being discussed.
