### ISSUE TITLE
Add Spanish version

### ISSUE THREAD

**Issue by heticor915** [TryGhost/Ghost#7611]
Hi Ghost comunity I'm working in the spanish translation of **core/server/translations**, I would like to support this in ghost, and this is a personal goal to achieve a contribution in any project in this hacktoberfest.

**Comment by ErisDS** [comment]
HI @heticor915, Ghost is not yet ready to be translated. I strongly advise you against doing any work on translations as they will not be accepted into the project.

To find out more, see the issues labeled [i18n](https://github.com/TryGhost/Ghost/issues?q=is%3Aopen+is%3Aissue+label%3Ai18n) or read the backlog in the #i18n channel on [slack](https://ghost.org/slack).

**Comment by heticor915** [comment]
Hi @ErisDS, 
Thanks for point me to the reference,  I check the backlog and understand this, but Hope in the future to have a multilang support. Ghost is pretty amazing, anyway I haven't started yet.
