### ISSUE TITLE
Support multiple errors inside of one Error

### ISSUE THREAD

**Issue by kirrg001** [TryGhost/Ghost#7627]
> One of the fiddly bits we have at the moment, is the idea that we might return multiple Validation errors. That's a cool idea and super useful for returning nice API responses to our clients. However, it's a PITA from an implementation perspective. Also, Bluebird now throws warnings if you try to call Promise.reject() with a non-error, e.g. if you call it with an array of errors. With themes, we wrap multiple errors inside a ThemeValidationError. For validation errors, I think it might be a good idea to wrap multiple errors inside an AggregateValidationError or to support multiple errors inside of one ValidationError? In short, lets always pass 1 error around, even if it contains many errors.
> I think this will simplify the code, whilst letting us still return super smart JSON error responses via the API.

This was the original comment: https://github.com/TryGhost/Ghost/issues/7116#issuecomment-252231809

To sum up: we would like to support multiple errors in one Error instead of having an error as single instance or as array.

Example:

```
var err = new errors.ValidationError({
    children: [new errors.GhostError(), new errors.GhostError()]
}):
```

@ErisDS I've deleted this task from #7116 and added this issue here.

**Comment by kirrg001** [comment]
Right now we are using `validation.validateSchema` in the Base Model to validate incoming properties. This function can return an Array with errors. This also needs to be changed. So the caller can always expect to get one single error back.

**Comment by kirrg001** [comment]
`Promise.reject(Array)` does not work with `bluebird`.
That's why we are seeing lot's of warnings when running the tests.

```(node:22866) Warning: a promise was rejected with a non-error: [object Array]```

Most of them are coming from [here](https://github.com/TryGhost/Ghost/blob/master/core/server/data/validation/index.js#L103).

**Comment by ErisDS** [comment]
I don't see this ever happening or really being useful, @kirrg001 suggest we close?

**Comment by kirrg001** [comment]
Yeah let's close it 👍It might be useful for some cases e.g. return a set of validation errors, but i doubt somebody will work on it in the future 😁
