### ISSUE TITLE
Can't access Public API

### ISSUE THREAD

**Issue by martinoj2009** [TryGhost/Ghost#7645]
I've got to be doing something wrong. I went into settings and enabled the Public API; however, when I try to access a URL like: https://(blog)/ghost/api/v0.1/posts/ I get:
{"errors":[{"message":"Access denied.","errorType":"UnauthorizedError"}]}

I've looked through the API documentation and tried a lot of different URL's to access the REST API so that I can parse JSON data and they all give me the same thing. I just want to be able to read the data, not change anything. Does this require authentication??? If so, why can't I have an option for accessing post data without authentication? It's not like people are getting data they don't already see on the website.
### Technical details:
- Ghost Version: 0.11.2
- Node Version: v4.6.1
- Browser/OS: Chrome Linux
- Database: sqlite3

**Comment by disordinary** [comment]
@martinoj2009 you need to include the client_id and client_secret parameters in your query. 

For instance, https://(blog)/ghost/api/v0.1/posts/?client_id=ghost-frontend&client_secret=abcd1234567

The secret itself can be found within the database or by viewing the source of any rendered ghost page. Just search for `ghost.init` within the source and you'll find them.

More information on authentication is available here: https://api.ghost.org/docs/client-authentication

As this isn't a bug I will recommend that it's closed.

**Comment by kirrg001** [comment]
@disordinary Thanks!
@martinoj2009 If you need any help, please swing by our [slack channel](https://ghost.org/slack/).

**Comment by Developer-Amit** [comment]
Hello I have Tried to access all posts from front like this 
https://(blog)/ghost/api/v0.1/posts/?client_id=ghost-admin&client_secret=abcd1234567

And this is response:


{
errors: [
{
message: "Please Sign In",
errorType: "NoPermissionError"
}
]

}

Client secret found on admin login time server response :--
![image](https://cloud.githubusercontent.com/assets/19202042/24320688/1de298bc-1160-11e7-9f42-677ee9bd74ef.png)

Any one can help please where is mistake?

**Comment by Developer-Amit** [comment]
Okay thanks Guy's this is required for access api to enable from the admin section
![image](https://cloud.githubusercontent.com/assets/19202042/24320731/ef2432b4-1160-11e7-8606-b54ebfbca973.png)

Resolved!!!!

**Comment by AmirTugi** [comment]
@Developer-Amit Thanks! I tried for a while to get the secrets by an admin request.
