### ISSUE TITLE
"Delete all content" doesn't actually delete everything

### ISSUE THREAD

**Issue by alexbagirov** [TryGhost/Ghost#7646]
### Issue Summary

When you try to wipe all the data of your blog, you meet the situation when posts disappear from your blog but not from the database.

### Steps to Reproduce

1. Write some posts (their IDs will be f.e. **1**, **2**, **3**).
2. Go to Labs and remove everything.
3. Add some more posts. Their IDs are **4**, **5** and etc.

### Technical details:

* Ghost Version: 0.11.2
* Node Version: 4.6.1
* Browser/OS: Chrome/Ubuntu
* Database: sqlite3

**Comment by kevinansfield** [comment]
Hi @alexbagirov that behaviour is expected as the the content deletion facility doesn't do anything to reset auto-increment IDs in the database after deleting the content rows - the posts are still gone from both the blog and the database despite the IDs not being reset.

If you really want to delete everything and start over the best solution is to delete the database and start again with a fresh DB. Alternatively if you are using SQLite or Postresql and want to keep some data but also care about the IDs of records starting again then you'll need to find the right SQL commands to run to reset the auto-increment ID indexes. If you are using MySQL then it's not possible to reset auto-increment indexes and you would need to start over with a fresh DB - this is the main reason the content deletion feature doesn't do anything with IDs, it's very specific to each database server and can cause problems elsewhere in the system depending on the database setup.

Starting with Ghost 1.0 we'll be moving away from auto-increment IDs and using object IDs instead so there won't be any sequential IDs in the database.

**Comment by alexbagirov** [comment]
Hello again.

I can confirm that I still have posts after deletion.

**Comment by kevinansfield** [comment]
@alexbagirov would you mind posting some more detailed reproduction steps including how you are verifying that there are still posts in your database? I've been unable to replicate post data still being present after using the "delete all content" feature
