### ISSUE TITLE
Extend/Change public client registration properties

### ISSUE THREAD

**Issue by kirrg001** [TryGhost/Ghost#7654]
We have to add and change some properties for public client registration.

- [x] add blog_uri
- [x] use blog title and blog description of config/settings
- [x] update blog_uri, update blog title, update blog description
- [x] change clientName to name
- [x] passport-ghost updates: clientName, description and updateClient
- [x] deprecate updateCallbackURL

**Comment by ErisDS** [comment]
@cobbspur is it possible to change the blog_uri?

**Comment by kirrg001** [comment]
changed the issue title and added more TODO's

**Comment by ErisDS** [comment]
Closed by #7690
