### ISSUE TITLE
GhostAuth redirect uri mismatch error for urls with a trailing slash.

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#7656]
If you are using GhostAuth, and have the url in your config.development.json file configured with a trailing slash on the end. E.g. `http://localhost:2368/blog/` you will not be able to sign in, instead getting a redirect URI mismatch error.

### Steps to Reproduce

1. Make sure you have a config.development.json in the root of your Ghost dev env
2. Inside the config.development.json make sure that you have 2 things:
   1. a URL that **ends in a trailing slash**, and 
   2. an auth config that results in **GhostAuth** rather than password auth.
3. Delete your DB file & run `knex-migrator init` to ensure you're working with a fresh DB
4. Start Ghost, navigate to `/ghost/` to get the setup screens
5. On screen 2, hit "sign in with Ghost"
6. See a redirect URI mismatch error

### Technical details:

* Ghost Version: 1.0.0-alpha.7
* Node Version: 4.4

**Comment by choicky** [comment]
Newly installed 1.0.0-alpha.9 today with Node Version: 4.2.0.

Unable to sign in due to the same problem:

422 ValidaitonError
Redirect URI mismatch
ID:

**Comment by kirrg001** [comment]
@choicky Hey! Can you try to reset your database and test again?
You can use the newest version of `knex-migrator` to reset your database.

```
$ knex-migrator -v
0.2.0

$ knex-migrator reset
$ knex-migrator init
$ gulp dev
```

**Comment by choicky** [comment]
@kirrg001 failed in resetting the mysql database.

$ knex-migrator -v
0.2.0

$ knex-migrator reset
[Sun, 20 Nov 2016 00:21:13 GMT] ERROR       DROP DATABASE undefined; - ER_DB_DROP_EXISTS: Can't drop database 'undefined'; database doesn't exist

$ knex-migrator init
[Sun, 20 Nov 2016 00:21:39 GMT] ERROR       MigrationPath is wrong: /home/choicky/blog.fei-xing.com/core/server/data/migrations/init

**Comment by choicky** [comment]
@kirrg001 I stopped ghost , manually dropped the whole ghost database, removed the whole folder and reinstalled ghost alpha again.

Now "knex-migrator reset" works fine.  However:

$ knex-migrator init
[Sun, 20 Nov 2016 00:33:25 GMT] ERROR       MigrationPath is wrong: /home/..../core/server/data/migrations/init

$ NODE_ENV=production knex-migrator init
[Sun, 20 Nov 2016 00:35:38 GMT] ERROR       MigrationPath is wrong: /home/...../core/server/data/migrations/init

**Comment by choicky** [comment]
@kirrg001 I cd to "current" folder and now "knex-migrator init" works fine.

However, "$ gulp dev" told me:
[00:48:16] No gulpfile found

I'm just a tester not a developer.  I installed ghost according to the teaching of:
http://support.ghost.org/v1-0-alpha/#testing-ghost-alpha-with-the-new-installer

There is few teaching for non-developer to install and testing the alpha ghost.

Anyway, thanks for you help.

**Comment by ErisDS** [comment]
If you installed ghost using the cli, you would need to use `ghost stop` and `ghost start` instead of `gulp dev`, which is a developer tool for building the project from git. It always helps if you include how you installed Ghost when reporting an issue 😉 

We are aware that there is very little documentation - it is a little bit on purpose because things are changing quickly, so it makes little sense to write docs that will change again next week :) 
If you keep an eye on dev.ghost.org we're posting regular updates on progress.
