### ISSUE TITLE
Image upload Error 0 in version 0.11.2

### ISSUE THREAD

**Issue by EnFlight** [TryGhost/Ghost#7664]
### Updated to Ghost Version 0.11.2

I updated to the newest version and I'm running into error code 0 when I try to upload an image. Can someone tell me how to resolve or what the error code means?

I'm using S3 as a database for my photos. I suspect that during the update, a file pointing to S3 might have been over written or it is an issue with my node version.

I was using node v0.12.14 before and am now using v4.2.3 locally. Does this affect how my website is being pushed to github > heroku? 

Has anyone ran into this issue before and could they point me in the right direction?

### Technical details:

* Ghost Version: 0.11.2
* Node Version: 4.3.2 
* Browser/OS: Chrome
* Database: Github, Heroku, S3

![screen shot 2016-11-02 at 1 57 06 pm](https://cloud.githubusercontent.com/assets/9838591/19917955/0fa1cb1c-a10b-11e6-874b-2dc13b315604.png)

**Comment by kirrg001** [comment]
Hey @EnFlight Sorry to hear you are having trouble. Closing this issue as it does not look like a Ghost bug. Can you please swing by our [slack channel](https://ghost.org/slack/) and ask for help there?We can provide better support there than in the Github issue tracker.
