### ISSUE TITLE
Audit & Overhaul of the URL utilities

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#7666]
This is an audit & overhaul issue. We could spend forever on it, the idea is to spend a small amount of time and significantly reduce the number of issues. The long tail of edgecases get cleaned up over time.

The audit centres around the `utils/url.js` file & how the utilities inside it are structured and used.

First, there are one or two known issues:

## Audit:

Review & fix the following bugs:
- [x] Fix GhostAuth redirect uri mismatch error for urls with a trailing slash. #7656
- [ ] Canonical vs logo blog URLs being output differently i.e. one has a trailing slash and one doesn't  (reported in slack, could have been a theme issue).
- [ ] Audit the codebase for use of the `urlJoin` and `urlFor` functions:
    - where they are used, are they used correctly? Consider how they are used to try to identify any small improvements
    - is there anywhere that they should be used and are not? All internal Ghost urls should be either fetched from `urlFor` or concatenated using `urlJoin` never `+`.
- [ ] Review recent url & subdirectory related issues, and check to see if the changes in 1.0 have caused any regressions
- [ ] Check the test coverage for the utilities, and any places in the codebase where the utilities are heavily used.

## Overhaul:
- [ ] if test coverage is found to be lacking, improve this
- [ ] make any small improvements that have been identified
- [ ] summarise findings & write a new issue to cover any larger changes that you'd like to make

**Comment by kirrg001** [comment]
I would like to limit this issue to the following tasks.

- [ ] review the existing PR https://github.com/TryGhost/Ghost/pull/7689
- [ ] reconsider using `urlJoin` for social urls  https://github.com/AileenCGN/Ghost/commit/cdc1c552e8ec580604691b9c07452c548770356c#diff-3b9516dc9764f7652261f9383f883d20R5
- [ ] QA: ensure we have one true place for url handling and use it everywhere

**Comment by AileenCGN** [comment]
Regarding this
>reconsider using urlJoin for social urls AileenCGN@cdc1c55#diff-3b9516dc9764f7652261f9383f883d20R5

I think this has to be removed again, as we won't use `urlJoin` for external urls. I will revert this change and update the PR.
