### ISSUE TITLE
Cloud storage can not be used yet?

### ISSUE THREAD

**Issue by 960339491** [TryGhost/Ghost#7685]
Cloud storage is not supported now? This is a very good service, am I use the wrong way, or cancel the service?

**Comment by acburdine** [comment]
@960339491 I'm not sure what your question actually is 😕 Cloud storage for images is supported through various storage adapters (see [here](https://github.com/TryGhost/Ghost/wiki/Using-a-custom-storage-module)). 

Going to close this as this really isn't an issue with Ghost itself. For further questions please swing by our [slack](//ghost.org/slack) and ask there. Thanks! 😄

**Comment by 960339491** [comment]
development: {
            url: 'http://qianxunclub.com/',
	    mail: {
            transport: 'SMTP',
            host: 'smtp.qq.com',
            options: {
                port: 465,
                service: 'QQ',
                auth: {
                    user: '960339491@qq.com', // mailgun username
                    pass: 'ckjleyaposjpbedc'  // mailgun password
                }
            }
        },
        database: {
            client: 'mysql',
            connection: {
                host     : 'db.qianxunclub.com',
                user     : 'zhangbin',
                password : '123456',
                database : 'ghost',
                charset  : 'utf8'
            },
            debug: false
        },
	storage: {
            provider: 'qiniu',
            bucketname: 'ghost',
            ACCESS_KEY: 'XCxIttem0qPEB48mNmGLNIm92PjsI5ipVrFUfHgJ',
            SECRET_KEY: 'zRSaGSFT1r5pR0WxPYKumrxPME7X1CrKGzjW0ii7',
            root: '/qianxun/',
            prefix: 'http://ofbphtmkb.bkt.clouddn.com'
        },
        server: {
            host: '127.0.0.1',
            port: '2368'
        },
        paths: {
            contentPath: path.join(__dirname, '/content/')
        }
    }



my config.js,
storage: {
            provider: 'qiniu',
            bucketname: 'ghost',
            ACCESS_KEY: 'XCxIttem0qPEB48mNmGLNIm92PjsI5ipVrFUfHgJ',
            SECRET_KEY: 'zRSaGSFT1r5pR0WxPYKumrxPME7X1CrKGzjW0ii7',
            root: '/qianxun/',
            prefix: 'http://ofbphtmkb.bkt.clouddn.com'
        },

storage  qiniu cloud can not be used，Upload in local。
config.example.js Sample configuration files are also not related to configuration

**Comment by acburdine** [comment]
@960339491 please take this to our [slack channel](//ghost.org/slack) - we're able to provide better support there than we can in the github issue tracker. Thanks!
