### ISSUE TITLE
Adapter improvements

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#7687]
When we added theme uploads to Ghost, the image adapter was changed to also support themes. We would like to rework this. Themes must be read from disk, there is no other way. That's why we would like to extract the theme functionality out of the local storage adapter. 

Also, there is currently no need to read a file, which we will need in the near future in order to support better icon/favicon behaviour.

- [x] add read to the storage adapter
- [x] move content/storage to content/adapters (content/adapters/scheduling content/adapters/storage)
- [x] static theme adapter (in themes/storage)
- [x] source out base adapter

**Comment by mz103** [comment]
I'm dying for this, commenting here so it keeps me updated. 😃

**Comment by kirrg001** [comment]
I've changed the issue title to: **Adapter improvements**. This issue is a collection of all adapter improvements we would like to do for Ghost `1.0`. There are no more open issues regarding adapters.
