### ISSUE TITLE
Trying to use meta_title for filter

### ISSUE THREAD

**Issue by carloscarvallo** [TryGhost/Ghost#7693]
### Context 

I have a tag with the slug "escuelasquecaen" and I'm in the context of a page where his `meta_title` is "escuelasquecaen" too

this is working
```
	{{#is "page"}}
		{{#get "tags" slug="escuelasquecaen"}}
			{{#foreach tags}}
				<title>{{id}}</title>
			{{/foreach}}
		{{/get}}
	{{/is}}
```
but this is not working
```
	{{#is "page"}}
		{{#get "tags" slug="{{meta_title}}"}}
			{{#foreach tags}}
				<title>{{id}}</title>
			{{/foreach}}
		{{/get}}
	{{/is}}
```
but if I do this, I see the `meta_title`
```
	{{#is "page"}}
		{{#get "tags" slug="{{meta_title}}"}}
			{{#foreach tags}}
				<title>{{id}}</title>
			{{/foreach}}
		{{/get}}
        <title>{{meta_title}}</title>
	{{/is}}
```
but I can't use the `meta_title` as "filter" in to the tag

### Technical details:

* Ghost Version: 0.11.0
* Node Version: 4.4.7
* Browser/OS: Google Chrome
* Database: sqlite3
* SO: Ubuntu Linux 14.04

**Comment by ErisDS** [comment]
Hi @carloscarvallo, sorry to hear you're having trouble. We have a #themes channel in our [slack](https://slack.ghost.org) community, which is the perfect place for asking questions like this.

In this case, you're trying to use a handlebars helper function inside another handlebars helper function, this is not valid syntax. The correct syntax for this is called "subexpressions": http://stackoverflow.com/questions/23787586/subexpressions-in-handlebars

If you need more help, I recommend swinging by our slack community :)
