### ISSUE TITLE
Bump node-postgres version for compatability

### ISSUE THREAD

**Issue by rlindner81** [TryGhost/Ghost#7708]
### Issue Summary

This issue occurs on my server running Ubuntu 16.04, but it would occur anywhere. I'm using the latest stable Ghost 0.11.x with Postgres 9.6.x. The optional dependency maintained in your package.json is "pg": "4.1.1", which is about 2 years old. Using this old driver with a recent Postgres results in failed authentications, meaning Ghost cannot even start. 

Bumping "pg" to the latest release "6.1.0" fixed this issue for me.

### Steps to Reproduce

1. Run Ghost with any recent Postgres release. It will not be able to connect.

### Technical details:

* Ghost Version: 0.11.3
* Node Version: 6.9.1
* Browser/OS: Ubuntu 16.04
* Database: Postgres 9.6.1

**Comment by ivantedja** [comment]
I believe Ghost no longer support pg in its latest version :(

here is the link: https://dev.ghost.org/dropping-support-for-postgresql/

**Comment by rlindner81** [comment]
@ivantedja I had not come across that... ok that's their call. I will close this then.
