### ISSUE TITLE
Getting internal server error 500 when saving post on server

### ISSUE THREAD

**Issue by eashish93** [TryGhost/Ghost#7711]
Hye,
I am getting this error when saving a post or when ghost auto save a post. Sometime this error also occur when I published a post. I'm using nginx behind a ghost for mapping port only.
Here's the full error which appear on admin panel notification bar.
```
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
 <html>
 <head>
 <title>732</title>
 <meta http-equiv="Cache-Control" content="no-cache"/>
 </head>
 <body>
 <p>
 Internal Server Error 
 </p>
 </body>
 </html>
```

**Comment by ErisDS** [comment]
Hi @eashish93, sorry to hear you're having trouble. As mentioned in the readme & contrib guide, when you have questions about Ghost or need help, please head on over to slack - https://ghost.org/slack/ - and post in the #help channel. There you can get help & support from the Ghost community, which we're not able to do here in the GitHub bug tracker.
