### ISSUE TITLE
npm install --production error！

### ISSUE THREAD

**Issue by dlmufei** [TryGhost/Ghost#7714]
npm WARN cannot run in wd ghost@0.11.3 node core/server/utils/npm/preinstall.js (wd=/data/node/ghost)

my nodejs version is v4.4.4

**Comment by ErisDS** [comment]
Hi @dlmufei, sorry to hear you're having trouble. As mentioned in the readme & contrib guide, if you have questions about Ghost or need help, please head on over to slack - https://ghost.org/slack/ - and post in the #help channel. There you can get help & support from the Ghost community, which we're not able to do here in the GitHub bug tracker.
