### ISSUE TITLE
ECONNRESET - connection error (screen shots)

### ISSUE THREAD

**Issue by pascalandy** [TryGhost/Ghost#7715]
### Issue Summary

From time to time, Ghost shows two errors then, reloads normally.

### Steps to Reproduce

![01 screen shot 2016-11-14 at 9 45 23 am](https://cloud.githubusercontent.com/assets/6694151/20272377/acf91038-aa5b-11e6-8e50-dceeb70d3a68.png)

Of course, I click on _Go to the front page_. Then ...

![02 screen shot 2016-11-14 at 9 45 33 am 2](https://cloud.githubusercontent.com/assets/6694151/20272406/c403aa04-aa5b-11e6-98b9-65c7d80488a4.png)

I click again on _Go to the front page_. Then it loads normally.

### IMHO

It looks like it's a node issue - http://stackoverflow.com/questions/17245881/node-js-econnreset

### Technical details:

* Ghost Version: 0.11.00
* Node Version: 4.6
* Browser/OS: Chrome Version 54.0.2840.71 (64-bit)
* Database: mysql 5.7

Cheers!

**Comment by kirrg001** [comment]
Hey @pascalandy Sorry for late response. 

Your error looks like a connection error to your mysql database.

Can you please update to Ghost version `0.11.3`?
We have updated `knex` to `0.12.x`. 

https://github.com/tgriesser/knex/issues/975 - maybe this issue is somehow related.

**Comment by pascalandy** [comment]
Yes I'm trying but I have issues with the S3 storage adaptor as well ... Please keep this open. I'll follow.

**Comment by kirrg001** [comment]
Hey @pascalandy Is it resolved?

**Comment by kirrg001** [comment]
I am going to close this issue now. Can you please swing by our [slack channel](https://ghost.org/slack/)?

If this is a bug, we can reopen :)

**Comment by pascalandy** [comment]
Thanks for asking!
I agree it's not an Ghost issue but an issue with install a storage adaptor. 

Cheers!
