### ISSUE TITLE
“tags“ attribute can't use it？

### ISSUE THREAD

**Issue by 960339491** [TryGhost/Ghost#7717]
{{#foreach tags}}
    <a href="{{url}}" class="tags">{{name}}<span class="post-count">{{post_count}}</span></a> 
{{/foreach}}

The above code is not valid

**Comment by ErisDS** [comment]
Hi @960339491, sorry to hear you're having trouble. Please head on over to slack - https://ghost.org/slack/ - and post information about what you are trying to do and what doesn't work in the #themes channel. There you can get help & support from the Ghost community, which we're not able to do here in the GitHub bug tracker.
