### ISSUE TITLE
Truncate tables when running tests

### ISSUE THREAD

**Issue by kirrg001** [TryGhost/Ghost#7718]
Please read original suggestion, see https://github.com/TryGhost/Ghost/pull/7495#issuecomment-260587338

Current state of our test env is: in each test (especially integration tests) we are resetting and initialising the database completely (!). That means, we are recreating the database and removing/adding all tables for each test, which is not necessary. It slows our tests down, especially for mysql.

It would be great to use knex truncate (http://knexjs.org/#Builder-truncate) instead to clean the database. This has the advantage of not removing all the tables or recreating the database.

Some references:
- teardown function tests are using: https://github.com/TryGhost/Ghost/blob/master/core/test/utils/index.js#L629
- setup function tests are using: https://github.com/TryGhost/Ghost/blob/master/core/test/utils/index.js#L531

Happy about help :)

**Comment by ErisDS** [comment]
@kate isn't this done now?
