### ISSUE TITLE
gulp rather than grunt ?

### ISSUE THREAD

**Issue by jpca999** [TryGhost/Ghost#7727]
I see that you do have gulp file , so why don tyou have it on the readme page ?

**Comment by kevinansfield** [comment]
Hi @jpca999, thanks for noticing! The gulp tooling is in alpha state at the moment as part of our move towards 1.0 - http://support.ghost.org/v1-0-alpha/

I'm going to close this as documentation will be added in the run-up to 1.0 coming out of alpha.
