### ISSUE TITLE
why is ghost faster ?

### ISSUE THREAD

**Issue by jpca999** [TryGhost/Ghost#7728]
Is there a post which explains what Ghost does to make it faster than any other blogging stuff out there ?  

what measures are taken to not load areas of the site that aren't even required for 90% of the page visitors ?

**Comment by kevinansfield** [comment]
Hi @jpca999, the best place to ask these questions is over on our [slack team](https://ghost.org/slack). We use Github solely for bug tracking and on-going feature development so we avoid support request and general questions here to keep the noise down. Thanks!
