### ISSUE TITLE
Failed to lookup view "index" in views directory "/Users/jay/content/themes/casper"

### ISSUE THREAD

**Issue by jpca999** [TryGhost/Ghost#7729]
I followed the instructions - Do i have to install the theme  seperate ?

Stack Trace

Failed to lookup view "index" in views directory "/Users/jay/Dropbox/Life_Changing_Mentoring_Program/CODE/MEANJS-0.4.2/DOCKER/ghost/content/themes/casper"

![image](https://cloud.githubusercontent.com/assets/1026325/20401956/cb29e3e2-acc8-11e6-9cfa-05f17690137b.png)

**Comment by ErisDS** [comment]
Hi @jpca999 - I appreciate that you're just getting stuck into Ghost, however to reiterate what @kevinansfield has already said and what it says in the issue template you have now deleted 3 times: this is an issue tracker for bugs - it is not for questions, help or support. Please, please come chat to us in [slack](https://ghost.org/slack) instead.
