### ISSUE TITLE
Support for newer versions of node (7.0.0)

### ISSUE THREAD

**Issue by Alykoff** [TryGhost/Ghost#7731]
### Issue Summary
`Ghost` wasn't installed.
Should add support of node v7.0.0.

### Steps to Reproduce
1. install node v7.0.0
2. run install command:
```
npm install --production
```
3. See error message:

> ERROR: Unsupported version of Node
> Ghost supports LTS Node versions: ~0.12.0 || ^4.2.0 || ^6.9.0
> You are currently using version: 7.0.0

### Technical details:

* node v7.0.0
* npm  v3.10.8
* ghost-0.11.3
* macOS 10.12.1

Thanks

**Comment by acburdine** [comment]
@Alykoff please see [this article](http://support.ghost.org/supported-node-versions/) for an explanation of why Node 7 isn't supported, as well as how to override that check.

Please visit our [slack channel](https://ghost.org/slack) for any further questions. Thanks! 😄

**Comment by Alykoff** [comment]
@acburdine: Thanks for you answer.
I will switch to node 6 :)
