### ISSUE TITLE
Importing database results in HTTP error 413

### ISSUE THREAD

**Issue by vshulev** [TryGhost/Ghost#7734]
### Issue Summary

I am trying to migrate from SQLite to MySQL. I export data from the existing blog and then try to import it into a new copy of the blog which is connected to an empty MySQL database. The exported JSON file is 2.43 MB. When I click on Import I get an "Import Failed" error message and the request to `/ghost/api/v0.1/db/` fails with code `413`.

### Steps to Reproduce

1. Export from a blog with sufficiently large SQLite db
2. Import in a blog connected to an empty MySQL db

The data limit may have been intentional, therefore I'm not sure this is a bug. However, it would be nice to be able to configure this upload limit, so that migration can be done easily via the web UI.

### Technical details:

* Ghost Version: 0.11.2
* Node Version: 4
* Database: MySQL

**Comment by vshulev** [comment]
Apologies, I had a closer look at the code and found this `blogApp.use(bodyParser.json({limit: '1mb'}));` in `server/middleware/index.js`. What's your take on making this configurable?

**Comment by vshulev** [comment]
Turned out to be an nginx issue not a Ghost issue.

**Comment by kirrg001** [comment]
@vshulev Thanks for coming back and letting us know!
