### ISSUE TITLE
Bio character counter validator measuring is wrong

### ISSUE THREAD

**Issue by Myrronth** [TryGhost/Ghost#7739]
When you add a bio to a team member that includes special characters—german umlauts (ä, ü, ö) but also (language independent and used in english) correct typographic quote signs (“” instead of the inch signs "")—the validator that ghost uses to validate and truncate the text is behaving unexpected.

It seems like the validator is counting the multibyte chars which is not visible for me as an user of the admin interface as the live-counter on the page counts “correct”—in terms of a human.

#### Before saving:
![special-chars-before-save](https://cloud.githubusercontent.com/assets/75341/20517288/b2393aec-b09a-11e6-9753-3ab2023e703b.png)
#### After saving:
![special-chars-after-save](https://cloud.githubusercontent.com/assets/75341/20517289/b3b3ea3e-b09a-11e6-8c3d-2cf04be7c013.png)

#### Before saving:
![non-special-chars-before-save](https://cloud.githubusercontent.com/assets/75341/20517295/bb6a4e80-b09a-11e6-946a-761d5681397a.png)
#### After saving:
![non-special-chars-after-save](https://cloud.githubusercontent.com/assets/75341/20517296/bc2a239a-b09a-11e6-90f4-e97ab364cd83.png)

### Technical details:

* Ghost Version: Hosted by Ghost.org

**Comment by kevinansfield** [comment]
Hey @Myrronth, I confirmed the issue by using emoji's, I attempted to use the special characters you mentioned above but I think those depend more on how the input is generated - they can be represented both by a single character or a single character+modifier but I couldn't get my OS to generate the latter.

I have a PR open with a fix, this should hopefully make it into the upcoming maintenance release. Thanks for the report!
