### ISSUE TITLE
Browser No error message when invalid data entered

### ISSUE THREAD

**Issue by Saytuamin** [TryGhost/Ghost#7746]
### Issue Summary

Hi i'm using the browser version of ghost on a Windows 7 / Windows 10 PC on Google chrome

On the general settings on the webpage you can change the number of posts per page to 0 and you aren't able to save these changes as expected however there is no clear error message that tells you why you aren't able to save.

### Steps to Reproduce

1. login and edit your blog
2. Go to the General tab in settings
3. Change the number of posts per page to 0
4. Try to save

I expected some warning letting me know it's unable to save and a red text error to pop up below, like when you make your description too long it's a small bug but it can save some frustration if you were to accidentally tab in change the post number unknowingly.

![ttas](https://cloud.githubusercontent.com/assets/22790920/20557734/9c6c34ec-b164-11e6-8d74-92bcdfd0440f.jpg)

In the image you can see that the description has an error message but the posts per page has invalid data but no error message.

**Comment by kirrg001** [comment]
I can confirm: if you set posts per page to 0, it does not send a HTTP request to the server.
So it's not possible to save 0 posts per page.

**Comment by tsvisimcha** [comment]
Alright I'll try to fix this one. This is my first time contributing to an open source project though so I might mess up

**Comment by Huanzhang89** [comment]
Hi there, 

I'm trying to take a look at this issue but have hit an error at the `grunt dev` stage. Its my first ever time contributing to this project so thanks in advance for your patience. 

Here is the error message I get when trying to run `grunt dev`

```
grunt dev
Running "bgShell:client" (bgShell) task

Running "express:dev" (express) task
Starting background Express server
Running "subgrunt:watch" (subgrunt) task
Warning: Task "watch" not found. Use --force to continue.

Aborted due to warnings.
Warning: Failed running "grunt bgShell:ember watch" in "core/client". Use --force to continue.

Aborted due to warnings.
>> Error: Command failed: grunt subgrunt:watch
Welcome to the Ghost 1.0.0 Alpha - this version of Ghost is for development only.
Ghost is running in development... 
Listening on 127.0.0.1:2368 
Url configured as: http://localhost:2368 
Ctrl+C to shut down

Running "watch" task
```

It seems that the `subgrunt:watch` is not found, but I'm not sure what that is exactly.

**Comment by Huanzhang89** [comment]
Heya,

I've managed to get an error message to show, but I'm having trouble getting the `error` class added to the postsPerPage form group. 

Here is the new code for `postsPerPage` after my edit, I can't seem to spot any mistakes but the `error` class refuses to get added when there is an error...

```
{{#gh-form-group errors=model.errors hasValidated=model.hasValidated property="postsPerPage" class="postsPerPage-container"}}
                    <label for="postsPerPage">Posts per page</label>
                    {{! `pattern` brings up numeric keypad allowing any number of digits}}
                    {{gh-input model.postsPerPage id="postsPerPage" name="general[postsPerPage]" focus-out="checkPostsPerPage" min="1" max="1000" type="number" pattern="[0-9]*" update=(action (mut model.postsPerPage))}}
                    {{gh-error-message errors=model.errors property="postsPerPage"}}
                    <p>How many posts should be displayed on each page</p>
                {{/gh-form-group}}
```

Any help is greatly appreciated as I have never used Ember before...

**Comment by acburdine** [comment]
@Huanzhang89 sorry you're having trouble getting the fix to work!

The first issue is because `gulp dev` is the new command to use during development. The documentations is not complete yet because the new developer tooling isn't fully complete yet.

I'm not sure what's causing the second issue, but there's actually already a PR for this open on the Ghost-Admin repository: TryGhost/Ghost-Admin#419 . Apologies if you spent a ton of time on this! It's sometimes hard to see if an issue is already being worked on. I'll go through and see if any issues on the Ghost repo are good for beginners to Ember - look for any with the "Beginner" label and see if anyone's worked on those.

Final note - if you have issues with development, it's probably a good idea to swing by our [slack channel](https://slack.ghost.org), where you can get more real-time help 😄

**Comment by Huanzhang89** [comment]
Thanks for the reply Austin. No worries it was a good learning experience anyways and I can see from the PR that I was very close, just needed to remove the checkPostsPerPage action. 

Nice to see that you guys are moving to gulp, I definitely find it much preferred to grunt! I'll definitely hop onto the slack channel next time I encounter any problems!
