### ISSUE TITLE
Import of backup JSON does not restore subscribers.

### ISSUE THREAD

**Issue by donmccurdy** [TryGhost/Ghost#7748]
### Issue Summary

For full blog JSON backup. I have not tried the subscribers-only CSV export/import feature.

### Steps to Reproduce

1. Before upgrading Ghost, I exported a .JSON backup of my data.
2. After a clean install of Ghost.
3. Import the backup JSON.
4. Posts are restored, but subscribers are not.

Here's a redacted screenshot of my backup:

![sublime text - don-mccurdy ghost 2016-11-27 json - screen shot nov 26 2016 11 33 09 pm](https://cloud.githubusercontent.com/assets/1848368/20645616/a00a0bc2-b431-11e6-8f97-c9f6b11e6315.png)

### Technical details:

* Ghost Version: 0.11.3
* Node Version: v6.9.1
* Browser/OS: Ubuntu 14.04.4 LTS (GNU/Linux 3.13.0-68-generic x86_64)
* Database: ?

**Comment by kirrg001** [comment]
Confirmed. Thanks for reporting 👍
