### ISSUE TITLE
Initial user setup is failing in 0.11.3 due to improper object construction

### ISSUE THREAD

**Issue by maddenf** [TryGhost/Ghost#7752]
Welcome to Ghost's GitHub repo! 👋🎉

Do you need help or have a question? Please come chat in Slack: https://ghost.org/slack 👫. Got an idea for a new feature? Please add it to our wishlist: http://ideas.ghost.org 🌟. Found a bug? Please fill out the sections below... thank you 👍

### Issue Summary

I am running ghost as an npm module in an existing Node Express app.  Ghost is running on the URL http://localhost:8080/blog.

Everything seems fine until I attempt to run the first time initial setup to add a user.  On step two I get the following error:  `ERROR: No root key ('setup') provided `

Stack trace is:
```
ERROR: No root key ('setup') provided. 
 
 Error
    at Error.BadRequestError (/foo/node_modules/ghost/core/server/errors/bad-request-error.js:6:18)
    at Object.checkObject (/foo/node_modules/ghost/core/server/api/utils.js:280:45)
    at validateData (/foo/node_modules/ghost/core/server/api/authentication.js:60:22)
    at runTask (/foo/node_modules/ghost/core/server/utils/pipeline.js:19:25)
    at /foo/node_modules/ghost/core/server/utils/pipeline.js:26:20
    at tryCatcher (/foo/node_modules/ghost/node_modules/bluebird/js/release/util.js:16:23)
    at Object.gotValue (/foo/node_modules/ghost/node_modules/bluebird/js/release/reduce.js:157:18)
    at Object.gotAccum (/foo/node_modules/ghost/node_modules/bluebird/js/release/reduce.js:144:25)
    at Object.tryCatcher (/foo/node_modules/ghost/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/foo/node_modules/ghost/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/foo/node_modules/ghost/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromiseCtx (/foo/node_modules/ghost/node_modules/bluebird/js/release/promise.js:604:10)
    at Async._drainQueue (/foo/node_modules/ghost/node_modules/bluebird/js/release/async.js:143:12)
    at Async._drainQueues (/foo/node_modules/ghost/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues (/foo/node_modules/ghost/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:574:20) 
```

**After further investigation I found the following:**
In utils.js
```
276     checkObject: function (object, docName, editId) {¬                           
277         console.log(object);¬                                                    
278         console.log('docname is ',docName);¬
279         console.log('is object empty? : ',_.isEmpty(object));¬                   
280         console.log('is object[docName] empty? : ',_.isEmpty(object[docName]));¬ 
281         console.log('object["setup[0][name]"]', object['setup[0][name]']);¬      
282         console.log('is object[docName][0] empty? : ',_.isEmpty(object[docName][0]));¬
283         if (_.isEmpty(object) || _.isEmpty(object[docName]) || _.isEmpty(object[docName][0])) {¬
284             return errors.logAndRejectError(new errors.BadRequestError(i18n.t('errors.api.utils.noRootKeyProvided', {docName: docName})));¬
285         }¬                                                                       
286 ¬       
```

And the results from these logs:
```
{ 'setup[0][name]': 'Foo Bar',
  'setup[0][email]': 'bob@foo.com',
  'setup[0][password]': 'XXXXXXXXXXXXXXXX',
  'setup[0][blogTitle]': 'Whats new for Foo' }
docname is  setup
is object empty? :  false
is object[docName] empty? :  true
object["setup[0][name]"] Foo Bar

ERROR: Cannot read property '0' of undefined 

```

**It appears to me that** the object being passed into `checkObject` is improperly constructed.

### Steps to Reproduce

0. Setup config.js to use `url: 'http://localhost:8080/blog'`  
0.1 Configure default 404 handler for express to ignore '/blog' or comment out 404 handler all together.
1. Go to http://localhost/blog/ghost
2. Follow to step 2.
3. Fill out form
4. Submit form

### Technical details:

* Ghost Version: 0.11.3
* Node Version: 6.9.0
* Browser/OS: Mac OSX Yosemite
* Database: sqlite3

**Comment by maddenf** [comment]
When Ghost is setup to run on http://localhost:8080/, the object that is passed to authentication->setup is ```
{ setup: 
   [ { name: 'Foo Bar',
       email: 'foo@bar.com',
       password: 'foobarfoobar',
       blogTitle: 'Foo' } ] }
```

When Ghost is running on http://localhost:8080/blog, the object set is ```
{ 'setup[0][name]': 'Foo Bar',
  'setup[0][email]': 'foo@bar.com',
  'setup[0][password]': 'foobarfoobar',
  'setup[0][blogTitle]': 'Foo' }
```

**Comment by ErisDS** [comment]
I've double-checked that the node module setup still works with a subdirectory with Ghost 0.11.3.

Also, there's no way that Ghost can be causing the issue here - it sends the data in the first correct format as you can [see here](https://github.com/TryGhost/Ghost-Admin/blob/03096936f5d24a577c6dd70d6946c531eaea3e89/app/controllers/setup/two.js#L107). The only way that I can think of, that it might get corrupted, is if there is middleware mounted on your express app that causes the body to be handled differently.

This is, in my opinion, definitely a setup error, same as #5037, and I will continue to provide help when I can in [slack](https://ghost.org/slack).

**Comment by maddenf** [comment]
app.use(bodyParser.urlencoded({ extended: true }));     **SOLVED** my problem!!

In the default express setup, *extended* was set to *false*.  Setting it to *true* solved the problem.  The urlencoded string passed by the form was not being parsed correctly.
