### ISSUE TITLE
Lots of high res images 502 an article

### ISSUE THREAD

**Issue by rawsh** [TryGhost/Ghost#7753]
### Issue Summary

I'm running Ghost on a Digital Ocean 512mb server.
I have a popular article with about 25 high res images (2560p).
When I have those images on the article, it crashes. 
I've managed to fix the issue by replacing the images with an imgur album link.

### Technical details:

* Ghost Version: 0.11.3
* Node Version: 4.4.5
* Database: Default

**Comment by disordinary** [comment]
Hi @rawsh,

I tried to replicate the issue by uploading 100 high res photos to a blog running on a virtual machine with 128mb of RAM and couldn't cause ghost to crash, I couldn't even get memory usage to become a problem. Of course there are plenty of factors not considered in any of my experiments.

I was wondering if you could provide more detail to help us debug the problem.
- Is it a custom install or did you choose the digital ocean ghost application? 
- What format are the images in and how many mb are they? 
- I know you've worked around this problem but have you got any logs from Ghost or the server to show what's gone wrong?
- Does it happen instantly or is it something that happens after a while, if so can you guess how long?

Thanks

- Ryan

**Comment by kevinansfield** [comment]
Random thought but was this in any way related to AMP? The `amperize` module will fetch each image in order to obtain the dimensions and image type if the HTML doesn't already include a width/height/layout attribute

**Comment by disordinary** [comment]
That's a good call, I can't get it to crash for me though.

Regardless, this problem will probably be fixed when we implement srcset support and I know there is work to be done on the AMP front, so unless @rawsh comes back with more information I suggest we put this on ice and see if upcoming and scheduled changes fix it for him.

**Comment by rawsh** [comment]
@disordinary I'm sorry I did not reply earlier, the thread went to spam for some reason.

- Ghost application on DO
- All the images were screenshots at 2560p, [here is a sample](http://www.devpy.me/content/images/2016/06/Screenshot-from-2016-06-01-11-28-59.png)
- I will try to get some logs and come back later, my blog is running in production so I don't really want to take the post offline
- As soon as I add the image the post 502's. This might be cloudflare but I doubt it, I will test.

**Comment by rawsh** [comment]
Ok, so I got it to crash again. @disordinary 
I'm getting [a 502](http://www.devpy.me/10-of-the-best-linux-themes-compared/) by adding some images back, I turned off cloudflare and I still have the issue.

For some reason the ghost log (/var/logs/upstart/ghost.log) thinks things are fine and dandy and tells me

`166.170.15.52 - - [07/Jan/2017:01:37:00 +0000] "GET /10-of-the-best-linux-themes-compared/ HTTP/1.0" 200 - "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:50.0) Gecko/20100101 Firefox/50.0"
`

200 even though I get a 502.

**Comment by rawsh** [comment]
@disordinary @kirrg001 still 502ing... no error... newest ghost. I think it might be related to high traffic.

**Comment by kirrg001** [comment]
If Ghost returns 200, could you monitor your nginx logs?
Maybe you can find something useful.

**Comment by rawsh** [comment]
@kirrg001 I have tried it, nothing returns other than the normal code.

**Comment by rawsh** [comment]
@kirrg001 I think this should be reopened, still getting the error with the latest 0.11 release. Here is a gif:
![peek 2017-09-01 17-57](https://user-images.githubusercontent.com/7035671/29990325-fcf7e726-8f3e-11e7-8c07-19a0c4ce9d8c.gif)
