### ISSUE TITLE
How to reorder posts?

### ISSUE THREAD

**Issue by pointcache** [TryGhost/Ghost#7755]
Please tell me how to reorder posts.

**Comment by acburdine** [comment]
@pointcache If you're talking about reordering posts in the admin interface, that's currently not possible - they are (mostly) ordered by last updated/publish date iirc.

At any rate, going to close this as it isn't really a bug. If you have further questions, please visit our [slack channel](https://ghost.org/slack) 😄 Thanks!

**Comment by pointcache** [comment]
is there any way to hack the system to make a post appear on top?

**Comment by acburdine** [comment]
@pointcache I'm unclear as to whether or not you're talking about the frontend or the admin interface. Like I said, please head over to the slack channel and continue the conversation there 😄
