### ISSUE TITLE
[Documentation] SES region option

### ISSUE THREAD

**Issue by tomasz-tomczyk** [TryGhost/Ghost#7757]
### Issue Summary

SES default configuration with Access Key / Secret assumes the region to be us-east-1 - the documentation has no mention of this option. Took me a few attempts to get it right :)

See http://support.ghost.org/mail/

Original:

```
mail: {
    transport: 'SES',
    options: {
        AWSAccessKeyID: "AWSACCESSKEY",
        AWSSecretKey: "/AWS/SECRET"
    }
}
```

Should be:

```
mail: {
    transport: 'SES',
    options: {
        region: 'AWSREGION',
        AWSAccessKeyID: "AWSACCESSKEY",
        AWSSecretKey: "/AWS/SECRET"
    }
}
```

**Comment by kirrg001** [comment]
@tomasz-tomczyk Thanks a lot :) We will update our documentation.
