### ISSUE TITLE
can not start ghost

### ISSUE THREAD

**Issue by piggsoft** [TryGhost/Ghost#7759]
download latest version
npm install & node index
cause a error

0 info it worked if it ends with ok
1 verbose cli [ 'D:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'D:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@3.10.8
3 info using node@v6.9.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle ghost@0.11.3~prestart: ghost@0.11.3
6 silly lifecycle ghost@0.11.3~prestart: no script for prestart, continuing
7 info lifecycle ghost@0.11.3~start: ghost@0.11.3
8 verbose lifecycle ghost@0.11.3~start: unsafe-perm in lifecycle true
9 verbose lifecycle ghost@0.11.3~start: PATH: D:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;F:\ghost\node_modules\.bin;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;D:\Program Files\Git\cmd;D:\Program Files\Git\mingw64\bin;D:\Program Files\Git\usr\bin;D:\Program Files\TortoiseSVN\bin;D:\Program Files\nodejs\;D:\Go\bin;C:\Users\Administrator\AppData\Roaming\npm;D:\Program Files\gradle-2.11\bin;D:\apache-maven-3.3.9\bin;D:\Python27;D:\Python27\Scripts;D:\Go\bin;D:\Program Files (x86)\Microsoft VS Code\bin;C:\Users\Administrator\AppData\Local\atom\bin
10 verbose lifecycle ghost@0.11.3~start: CWD: F:\ghost
11 silly lifecycle ghost@0.11.3~start: Args: [ '/d /s /c', 'node index' ]
12 silly lifecycle ghost@0.11.3~start: Returned: code: 1  signal: null
13 info lifecycle ghost@0.11.3~start: Failed to exec start script
14 verbose stack Error: ghost@0.11.3 start: `node index`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (D:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (D:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid ghost@0.11.3
16 verbose cwd F:\ghost
17 error Windows_NT 6.1.7601
18 error argv "D:\\Program Files\\nodejs\\node.exe" "D:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
19 error node v6.9.1
20 error npm  v3.10.8
21 error code ELIFECYCLE
22 error ghost@0.11.3 start: `node index`
22 error Exit status 1
23 error Failed at the ghost@0.11.3 start script 'node index'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the ghost package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node index
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs ghost
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls ghost
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

### Technical details:

* Ghost Version:0.11.3 
* Node Version:6.9.1
* Browser/OS: 
* Database:

**Comment by callmelanmao** [comment]
you should install with `npm install --production` and start dev mode with `npm start`  and production mode with `npm start --production`

**Comment by disordinary** [comment]
Hey @piggsoft, we try and keep this Github issues list free of support requests. 

If the answer from @callmelanmao doesn't work then I highly recommend you checkout the help channel in the Ghost Slack: https://ghost.org/slack/ 

😀

**Comment by piggsoft** [comment]
@callmelanmao i already use `npm install --production` and `npm start --production` 

@disordinary thks

**Comment by acburdine** [comment]
Going to close this per @disordinary's comment. Please visit the slack channel for more help. Thanks!
