### ISSUE TITLE
ghostServer.restart() not working

### ISSUE THREAD

**Issue by c0d0g3n** [TryGhost/Ghost#7760]
### Issue Summary

When running Ghost as a node module ([as described here](https://github.com/TryGhost/Ghost/wiki/Using-Ghost-as-an-NPM-module)), the `.restart()` method throws an error. The gulpfile, ghost settings and terminal output are in [this gist](https://gist.github.com/c0d0g3n/acef9273422dbea2f81f0d2b610c9709). After installing ghost and gulp locally, you should be able to recreate the bug by running `gulp test`.

I'm not familiar with the software ghost is built upon, but given that running `.stop()` and `.start()` in sequence works, I thought this has to be a bug.

I'm working on a Linux Mint 18 system, running Node.js 6.9.1. I'm using Ghost 0.11.3 (latest stable).

**Comment by vivekannan** [comment]
Newbie here. Be kind....

_GhostServer.restart_ calls _GhostServer.stop_ which returns a promise. When the promise is resolved, it does so with **self**. **self** is then passed to _GhostServer.start_ as the **externalApp** and there begins the downfall. :(

__GhostServer.start__ ends up doing __externalApp.listen__ which in this case is **self** ergo the instance itself. GhostServer doesn't have a __listen__ method.......hope I am right. Fix should be

`
    // Inside GhostServer.restart, replace this.......
    return this.stop().then(this.start.bind(this));
    // with this.....
    return this.stop().then(function(ghostServer) {
        return ghostServer.start(); // for chaining....
    });
`

**Comment by kirrg001** [comment]
Hey @c0d0g3n ! Sorry for late response and sorry to hear you are having trouble. I can confirm this bug, thanks for reporting.

@vivekannan The fix you have suggested works perfectly. A PR is very welcome.

**Comment by vivekannan** [comment]
When I run `grunt validate`, all the tests pass but the command ends with
an error about my Chrome browser version being incorrect or something...Can
I still make the pull request?

**Comment by kevinansfield** [comment]
@vivekannan that error is coming from the Ghost-Admin tests so I don't think it's relevant to this issue. It's fine to submit your PR in any case, the tests are re-run on Travis and the PR will be reviewed and tested before merging so nothing to worry about 😄
