### ISSUE TITLE
Brute: check if the brute key's are correct

### ISSUE THREAD

**Issue by kirrg001** [TryGhost/Ghost#7766]
It could be that the brute key's for globalReset are not correct.
It would be great to check it 👍
Only affects Ghost alpha/master.

**Comment by vivekannan** [comment]
https://github.com/TryGhost/Ghost/blob/master/core/server/middleware/api/spam-prevention.js#L77

Not sure if I am making much sense, but shouldn't this,

```
}, _.pick(spamGlobalBlock, spamConfigKeys))
```

be this,

```
}, _.pick(spamGlobalReset, spamConfigKeys))
```
