### ISSUE TITLE
Filtering unneeded tags on a post

### ISSUE THREAD

**Issue by shystruk** [TryGhost/Ghost#7767]
Hi, guys!
Could you please find out how not to display unneeded tags on a post ?
For e.g. I don't need "photo" tag to display.

Thanks!

```javascript
{{#foreach posts}}
      {{#tags}}
           {{#has tag="photo"}}
           {{else}}
                {{name}}
           {{/has}}
      {{/tags}}
{{/foreach}}
```

**Comment by acburdine** [comment]
@shystruk Ghost has the concept of "internal tags" which are tags that aren't shown in the tags list. This should be good for your use case. (see more information on internal tags [here](https://help.ghost.org/hc/en-us/articles/224169868-Internal-Tags-Beta))

If not, please swing by our [slack channel](https://ghost.org/slack) and ask this question there - the Github issue tracker is for bugs and ongoing feature work. Thanks! 😄

**Comment by shystruk** [comment]
@acburdine thank you for the response! 
Internal tags are really helpful :)
