### ISSUE TITLE
AMP should be opt-in

### ISSUE THREAD

**Issue by FiloSottile** [TryGhost/Ghost#7769]
Hello Ghost team! I'm very happy to run blog.filippo.io on Ghost, I love AMP, and working where I work (even if this is 100% a personal opinion) I know how awesome it feels to turn something new on by default for everyone.

However, I really think there should be a switch to turn AMP off (if there isn't one already I couldn't find), and that it should be off by default.

AMP is great, but it's a tradeoff. Turning it on gives up:

* customization (unless the theme has a matching AMP mode, which most blogs don't have)
* analytics (~~unless using one of the supported centralized services~~ [[fixed](https://github.com/ampproject/amphtml/blob/master/extensions/amp-analytics/amp-analytics.md)], and without manual configuration)
* revenue (if the blog was relying on ads, unless using one of the supported centralized services, and without manual configuration)
* control (from an ideological point of view, which the owner might or might not care about)

Most of these can be corrected for, but that requires a conscious action by the blog owner, which they can't take if it's enabled by default on them.

There's nothing wrong with tradeoffs, but I think this is one that shouldn't be made for all Ghost blog owners without their consent and without giving them the occasion to compensate. And definitely shouldn't be enforced.

Thanks for listening ✨

**Comment by jchampemont** [comment]
Totally agreed!

I updated my blog a few weeks ago, and today I got a mail from Google webmaster tools saying that there was some issues with my AMP pages. I had no idea what AMP is. 

I am very surprised that you added this functionality to Ghost without a (documented) way of disabling it.

**Comment by AileenCGN** [comment]
Hey @FiloSottile & @jchampemont!

Yes! We will look into that and build it into Ghost (LTS and alpha) probably within the next weeks. You should be able then to opt-out for AMP. Unfortunately, AMP requires some stuff (like article pictures for *every* blog post) and produces errors in Google webmaster tools, which we didn't expect. Hence, it's causing some headache for a few users.

Cheers,

Aileen

**Comment by kirrg001** [comment]
closed via #7842

**Comment by julianlam** [comment]
... so for those who got here via Google, how do you disable AMP? Has a version with these changes been released?

**Comment by AileenCGN** [comment]
@julianlam You can disable it in Apps!

**Comment by julianlam** [comment]
Thanks @AileenCGN :smile:
