### ISSUE TITLE
Minor responsive issue on Subscribers page in the backend.

### ISSUE THREAD

**Issue by surdaft** [TryGhost/Ghost#7773]
**Issue:** Sidebar is showing and cramping the list.
**Expected:** Sidebar is toggle-able, allowing space for the list on mobiles (?)

![screenshot_20161210-131351](https://cloud.githubusercontent.com/assets/8268249/21073607/24997c2a-bedb-11e6-99e0-b8293cad28be.png)

**Comment by kevinansfield** [comment]
@surdaft thanks for the report. The subscribers interface was hacked together pretty quickly as it's currently a beta feature, it will likely go through some pretty major changes after 1.0 is released.

I'll leave the issue open as a reminder for future work and if anyone from the community feels affected by this enough to fix it we're always open to PRs 😁

**Comment by margemcm** [comment]
we (@baldwinjj, @sarandford, and myself) are going to try our hand at this one, expect to hear from us soon!

**Comment by margemcm** [comment]
it looks like the most recent release resolved this issue by changing the layout.  the subscribers table still has a responsiveness issue but that's a separate issue from the sidebar. is there any reason to keep this open?

**Comment by JohnONolan** [comment]
Subscribers UI is due a complete overhaul, this won't be fixed before the design is re-written and nobody has shown any interest in 6 months so going to close for now :)
