### ISSUE TITLE
Mixed timestamp and text values for posts published_at, updated_at...

### ISSUE THREAD

**Issue by komanaki** [TryGhost/Ghost#7778]
### Issue Summary

I've got mixed values on database since a few months, new posts got "2015-11-12 17:55:00" value for their date and old posts still have timestamps like "1473875427167"
If you decided to change the value type on an update, why don't you applied a migration on the database ?
Now my homepage have its posts display broken and I should fix the database by hand to resolve it, hurray.

### Steps to Reproduce

1. Have an old database that uses timestamps (which version of Ghost ? you should know better than me)
2. Edit and old post and update it
3. See the broken database and posts display on the blog homepage

### Technical details:

* Ghost Version: 0.11.0
* Node Version: NodeJS 4.2.6 ARM
* Browser/OS: Windows 10
* Database: sqlite3

**Comment by kirrg001** [comment]
Hey @komanaki Can you update to `0.11.1` and report back?

In `0.11.1` we have pushed a fix to force running the date migration for sqlite users.
See https://github.com/TryGhost/Ghost/releases/tag/0.11.1

**Comment by komanaki** [comment]
Updated to 0.11.1 and it's fixed now. Thanks a lot.
Despite being very old issues, maybe it's a good idea to post a comment on #234 and #1742 as they're the first results that we found while searching the issue on a search engine ?

**Comment by kirrg001** [comment]
@komanaki Glad to hear it works :) 

You already added issue references. So if somebody experiences wrong post order, they can see the linked issue from now on 👍 Thank you
