### ISSUE TITLE
Session hijacking through malicious JavaScript

### ISSUE THREAD

**Issue by rochax** [TryGhost/Ghost#7780]
### Issue Summary

Through malicious JavaScript in Ghost current version I can hijacking session from any user. I have been tried follow the process to make a responsible disclosure, as yours recommendation: [https://github.com/TryGhost/Ghost/blob/master/SECURITY.md](url).

I sent my first email at 11/03/2016, after four days (11/07) Hannah answered me requesting more details to reproduce internally, I sent at 09/11 and since then I waiting some position. I have already been sent others two emails asking if she reproduced this issue, but I didn't receive any response.

How should I proceed to disclose this issue?

**Comment by ErisDS** [comment]
I will reply, please be patient. We are a very small team with many things to juggle.
