### ISSUE TITLE
Blank admin page

### ISSUE THREAD

**Issue by ourmaninindia** [TryGhost/Ghost#7789]
Hi

I have a site that works so I copied and renamed the complete ghost folder to be used for another site. I deleted the database. The new site works though it complains about missing all the files in the assets folder.

It also generated a blank database but... I get a bank page for the setup (admin) page. I can see that the browser complains that the vendor and ghost files (css and js) are missing and as a result the logs confirms this.

2016/12/18 01:04:09 [error] 13711#0: *7597 open() "/home/alfred/webapps/ghost/ghost/vendor.min.css" failed (2: No such file or directory), client: 179.43.176.98, server: blog.summertimegoa.com, request: "GET /ghost/vendor.min.css?v=34bc3163b7 HTTP/1.1", host: "blog.summertimegoa.com", referrer: "http://blog.summertimegoa.com/ghost/setup/"
2016/12/18 01:04:09 [error] 13711#0: *7599 open() "/home/alfred/webapps/ghost/ghost/ghost.min.css" failed (2: No such file or directory), client: 179.43.176.98, server: blog.summertimegoa.com, request: "GET /ghost/ghost.min.css?v=34bc3163b7 HTTP/1.1", host: "blog.summertimegoa.com", referrer: "http://blog.summertimegoa.com/ghost/setup/"
2016/12/18 01:04:09 [error] 13711#0: *7600 open() "/home/alfred/webapps/ghost/ghost/vendor.min.js" failed (2: No such file or directory), client: 179.43.176.98, server: blog.summertimegoa.com, request: "GET /ghost/vendor.min.js?v=34bc3163b7 HTTP/1.1", host: "blog.summertimegoa.com", referrer: "http://blog.summertimegoa.com/ghost/setup/"
2016/12/18 01:04:09 [error] 13711#0: *7597 open() "/home/alfred/webapps/ghost/ghost/ghost.min.js" failed (2: No such file or directory), client: 179.43.176.98, server: blog.summertimegoa.com, request: "GET /ghost/ghost.min.js?v=34bc3163b7 HTTP/1.1", host: "blog.summertimegoa.com", referrer: "http://blog.summertimegoa.com/ghost/setup/"

Again the missing files are very much present in the core:

[alfred]$ ls core/built/assets/
codemirror/     ghost.js        img/            vendor.js
fonts/          ghost.min.css   tests.js        vendor.min.css
ghost.css       ghost.min.js    vendor.css      vendor.min.js

Why would it work for one site (ourmaninindia.com) but not for another (http://blog.summertimegoa.com)

I did the above as I had problems installing Ghost on another aws instance using the instructions in http://support.ghost.org/installing-ghost-linux/  These are very simple yet also here I got a bank setup page. So I thought if the above site works then a copy of that in the same home directory should also work. It did not. 

Any ideas as I wasted a day on this but did not get anywhere.

Node: 4.5.0 
Browser: chrome as well as mozilla
OS: AWS linux

regards, Alfred

**Comment by kevinansfield** [comment]
Hi @ourmaninindia, sorry to hear you are having troubles 😞 My first guess would be file permissions, does the user that ghost is running as have sufficient permissions to read your copied files?

I'm going to close this issue as we use github solely for bug tracking and feature development. If you need further support please come say hello on our slack team where you can get help from the community as well as the Ghost devs, it's definitely an easier and faster way to talk through problems such as the one you are experiencing!

**Comment by twinkleM** [comment]
@kevinansfield I have same issue on my blog setup
`GET XHR 
http://localhost:2368/ghost/api/v0.1/settings/ [HTTP/1.1 400 Bad Request 187ms]
GET 
XHR 
http://localhost:2368/ghost/api/v0.1/users/me/ [HTTP/1.1 400 Bad Request 186ms]
Transition #0: signin: transition was aborted  vendor.js:65598:7
EmberError@http://localhost:2368/ghost/vendor.js?v=4fadc2a47b:30213:15
AdapterError@http://localhost:2368/ghost/vendor.js?v=4fadc2a47b:185586:5
handleResponse@http://localhost:2368/ghost/vendor.js?v=4fadc2a47b:186867:14
handleResponse@http://localhost:2368/ghost/vendor.js?v=4fadc2a47b:202722:14
superWrapper@http://localhost:2368/ghost/vendor.js?v=4fadc2a47b:36827:17
handleResponse@http://localhost:2368/ghost/ghost.js?v=4fadc2a47b:64:20
superWrapper@http://localhost:2368/ghost/vendor.js?v=4fadc2a47b:36827:17
ajax/</hash.error@http://localhost:2368/ghost/vendor.js?v=4fadc2a47b:186958:21
fire@http://localhost:2368/ghost/vendor.js?v=4fadc2a47b:7912:11
fireWith@http://localhost:2368/ghost/vendor.js?v=4fadc2a47b:8042:7
done@http://localhost:2368/ghost/vendor.js?v=4fadc2a47b:13484:5
callback/<@http://localhost:2368/ghost/vendor.js?v=4fadc2a47b:13848:9`
