### ISSUE TITLE
Must restart ghost to take affect from change/edit theme

### ISSUE THREAD

**Issue by yabeow** [TryGhost/Ghost#7804]
I use Ghost Blog and I see it very useful and fast, but when I custom my theme, I must restart ghost and it take more than 60 seconds to take effects. I want Ghost to add a feature to fix this troubling thing.

**Comment by JimmehCai** [comment]
Hi, 
I think that's because you're running Ghost in production mode, which uses cache(I guess?) to improve the speed.

In production mode, you don't have to restart Ghost, to made the changes effective. Just go to the admin panel, active another theme, then switch back. In that way the theme will be reloaded.

Or you can run Ghost in development mode to disable cache.

Hope it helps.

**Comment by paulmaunders** [comment]
I just noticed this issue too. It is a bit frustrating to have to restart npm everytime you make a change to a theme, is there a better way?

**Comment by kevinansfield** [comment]
@paulmaunders sorry to hear you've also run into this bug, there's an open issue for it here https://github.com/TryGhost/Ghost/issues/7812

For now, if you are developing a theme I would suggest keeping web inspector open with the "disable cache option checked.

![screen shot 2017-01-25 at 16 46 54](https://cloud.githubusercontent.com/assets/415/22300020/09009a18-e31e-11e6-90ea-f51515ec31cb.png)

**Comment by yabeow** [comment]
I've got reply from Ghost Team. Hope it can help you.
> Hi,
> I think that's because you're running Ghost in production mode, which uses cache(I guess?) to improve the speed.
> 
> In production mode, you don't have to restart Ghost, to made the changes effective. Just go to the admin panel, active another theme, then switch back. In that way the theme will be reloaded.
> 
> Or you can run Ghost in development mode to disable cache.
> 
> Hope it helps.

**Comment by JimmehCai** [comment]
@yabeow
I had made that reply. (And then I deleted it cuz I thought I was wrong.)

> I've got reply from Ghost Team.

I'm not a Ghost developer. 😅

**Comment by dbauszus-glx** [comment]
That does not seem to work.

I run ghost in development.

I don't cache with the dev tools open and I almost always have them open.

I call 'ghost buster' in the local ghost install.

I stop and start ghost. I also tried to restart ghost.

The changes made in the page.hbs template of the default casper theme are not coming through.

**Comment by kevinansfield** [comment]
@dbauszus-glx if you need support please use https://forum.ghost.org
