### ISSUE TITLE
Modify the RSS Feed content output to fit the Facebook Instant Article

### ISSUE THREAD

**Issue by hinablue** [TryGhost/Ghost#7810]
https://github.com/TryGhost/Ghost/blob/master/core/server/data/xml/rss/index.js#L138

Modify to,
```
htmlContent('p').first().before('<img src="' + imageUrl + '" alt="' + post.title +'" />');
```

https://github.com/TryGhost/Ghost/blob/master/core/server/data/xml/rss/index.js#L139

Modify to,
```
            // Change RSS content output
            // Remove <p><img> tags and replace with <figure><img...><figcaption>...</figcaption></figure>
            htmlContent('img').map(function (index, element) {
                var img = htmlContent(element);

                if (img.parent().is('p')) {
                    return img.parent().replaceWith(element).end().wrap('<figure></figure>')
                        .after('<figcaption>' + img.attr('alt') + '</figcaption>');
                } else {
                    return img.wrap('<figure></figure>')
                        .after('<figcaption>' + img.attr('alt') + '</figcaption>');
                }
            });
```

Cause `<p><img>` in the Instant Article will be force remove that Instant Article told you there is an empty paragraph.

So, replace with `<figure><img>` is good for Instant Article.

**Comment by ErisDS** [comment]
Hi @hinablue thanks for raising this issue :) Do you have any reference material from facebook which explains this?

I would be happy to accept a PR to fix this, but would also like to understand why it is necessary.

**Comment by jomahoney** [comment]
https://developers.facebook.com/docs/instant-articles/guides/format-overview is a good jumping off point. There is mention of using `<figure><img>` but haven't dived into it.

**Comment by redgenie** [comment]
For now, you can just wrap the `<img>` or `<figure>` in a `<div>`.

**Comment by regalstreak** [comment]
Can someone help? Settings cache was brought in sometime between this time and the time when the changes to the xml/rss/index.js were posted. Could you please tell us how it could be done now @hinablue ? thanks in advance

**Comment by constantx** [comment]
I'm running into this issue as well:

<img width="900" alt="_34__chopp_vn" src="https://cloud.githubusercontent.com/assets/113969/25798746/98e7d242-340c-11e7-861d-38cc674443df.png">

**Comment by JohnONolan** [comment]
This is a feature request - not a bug report. We don't currently support FB instant articles and (as yet) don't plan to, but you can vote on the idea here if it's something that you'd like to see in Ghost http://ideas.ghost.org/ :)

**Comment by swshelper** [comment]
Hi,

I have been trying to modify my instant article feed with no success. My author byline is showing up with the name and the bio. I only want it to show up with the name. In the example provided, how do I get rid of the author bio, but keep the author name? The FB instant article and the html provided is not for the same article (just an example of how it's transforming)

![output](https://user-images.githubusercontent.com/32230829/30859773-fe5643e4-a292-11e7-9274-44319721708d.png)

![screenshot-business facebook com-2017-09-26-08-10-28-923](https://user-images.githubusercontent.com/32230829/30859603-6ac60f7e-a292-11e7-905d-2231756bd712.png)
