### ISSUE TITLE
Remove meta generator data from ghost_head

### ISSUE THREAD

**Issue by jbspeakr** [TryGhost/Ghost#7813]
### Issue Summary

The {{ghost_head}} output includes information about the used Ghost version. This should be removed as it does not add any useful value for me as a blog owner, but discloses valuable information for possible attackers. 

By e.g. knowing version-dependent open issues or security vulnerabilities this version information removes the trail-and-error from an possible attack scenario and in that way helps attackers.

You simply can expect every blog out there to be updated after a security issue patch was released.

### Steps to Reproduce

Take a look at the {{ghost_head}} output. The feature was introduced with [#383](https://github.com/TryGhost/Ghost/issues/383)

`<meta name="generator" content="Ghost 0.11" />`

### Technical details:

* Ghost Version: 0.11
* Node Version: arbitrary
* Browser/OS: arbitrary
* Database: arbitrary

**Comment by disordinary** [comment]
Hi @jbspeakr,

Removing `{{ghost_head}}` would only give us a false sense of security, there are numerous other ways that a malicious agent can use to find out the version of Ghost or any hosted app of any complexity. Furthermore, the metrics which we can access with that metadata is very important for the project.

We do take security very seriously, so thank you for the bug report. 

The way we're approaching issues like this is to make messaging around security vulnerabilities and the need to upgrade clearer, and simplifying the upgrade process itself.

**Comment by fritz-fritz** [comment]
I would suggest reconsidering this decision. While security through obscurity is an outdated and misguided approach, advertising the version of a service in page content or response headers is typically a bad idea. It should not matter that there are other ways to identify the deployed version of the service, we simply don't want to make it easy. While I have no qualms about attributing ghost as the generator, your need for metrics does not trump security best practices.

**Comment by fritz-fritz** [comment]
For anyone that doesn't want to fork and maintain the codebase, a simple workaround is with an nginx reverse proxy to use a substitution filter. Something like:

```nginx
    location / {
        proxy_pass            http://127.0.0.1:2369;
        proxy_set_header Host $host;
        proxy_set_header Accept-Encoding "";

        # Using official sub_filter (no regex make sure to update when you update ghost)
        sub_filter                  '<meta name="generator" content="Ghost 5.84">' '<meta name="generator" content="Ghost">';
        sub_filter_last_modified    on;
        
        # Using third party subs_filter (regex capable but clears Last Modified aka caching might not work)
        subs_filter     (\<meta\sname\=\"generator\"\scontent\=\"Ghost)(.*?)(\"\>) $1$3 r;
    }
 ```
    
 subs_filter appears to suit my needs.
