### ISSUE TITLE
Amp posts have no images

### ISSUE THREAD

**Issue by rawsh** [TryGhost/Ghost#7816]
Amp pages have no images. I'm using Android with chrome. E.g:

http://www.devpy.me/your-guide-to-a-practical-linux-desktop-with-i3wm/amp/
http://www.devpy.me/your-guide-to-a-practical-linux-desktop-with-i3wm/

### Technical details:

* Ghost Version: 0.11

**Comment by rawsh** [comment]
@AileenCGN I think that the error (blocked by client) is my ads (carbonads).
I don't see how the error is my customized amp, it is practically the same as the default and the images are part of {{amp_content}}.

[Here is the code I use for amp.hbs though.](https://github.com/devpytech/theme/blob/master/amp.hbs)

Thank you for your help!

**Comment by AileenCGN** [comment]
Hey @rawsh,

the order of your AMP scripts and the CSS is not correct:

https://github.com/devpytech/theme/blob/master/amp.hbs#L18

^ these components need to be loaded **after** the AMP boilerplate. Maybe try this and see if it helps.

**Comment by rawsh** [comment]
@AileenCGN No luck.

**Comment by ErisDS** [comment]
@rawsh This discussion would be much better served in [slack](https://slack.ghost.org).
