### ISSUE TITLE
npm install --production

### ISSUE THREAD

**Issue by Jackzhangpan** [TryGhost/Ghost#7817]
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "D:\\nodejs\\node.exe" "C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\
\npm\\bin\\npm-cli.js" "install" "--production"
npm ERR! node v6.9.1
npm ERR! npm  v4.0.5
npm ERR! code ELIFECYCLE
npm ERR! ghost@0.7.4 preinstall: `npm install semver && node -e "require('./core/server/utils/startu
p-check.js').nodeVersion()"`
npm ERR! Exit status 231
npm ERR!
npm ERR! Failed at the ghost@0.7.4 preinstall script 'npm install semver && node -e "require('./core
/server/utils/startup-check.js').nodeVersion()"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ghost package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm install semver && node -e "require('./core/server/utils/startup-check.js').nodeVers
ion()"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ghost
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ghost
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\ghost\npm-debug.log

**Comment by jloh** [comment]
A quick look suggests you aren't on a [supported version of Node.js](http://support.ghost.org/supported-node-versions/)?

This bug tracker isn't for support requests anyway, you'll have better luck asking it on [the Ghost slack](https://slack.ghost.org).

**Comment by Jackzhangpan** [comment]
my version is node v6.9.1
npm v4.0.5, I think it is right, do you think ?
@jloh

**Comment by ChasonTang** [comment]
@Jackzhangpan ghost 0.7.4 doesn't support node6

**Comment by acburdine** [comment]
@Jackzhangpan as has been said, this error occurs because Ghost 0.7.4 doesn't support Node v6. If you want node v6 support, please upgrade to the latest version of Ghost :)

If you have any further issues please drop by our [slack channel](https://slack.ghost.org), where we can provide better support, which we're not able to do in the Github issue tracker.
