### ISSUE TITLE
"=" in navigation bar url replaced with &#x3D;

### ISSUE THREAD

**Issue by kevingil** [TryGhost/Ghost#7826]
### Issue Summary
Using a link in the navigation bar that includes a `=` is replaced with `&#x3D;`
This only happens in the navigation bar.
This is not a duplicate of issue #4627 as the url doesn't need to have double `=` and it is not translated to `<marker>`

edit:
`&` is being replaced with `&amp`

### Steps to Reproduce
In `http://your-domain.com/ghost/settings/navigation/` add a link that includes a `=`.

### Technical details:
* Ghost Version: 0.11.3

**Comment by kevingil** [comment]
also, `&` is being replaced with `&amp`

**Comment by kevinansfield** [comment]
Thanks @kevingil, I've confirmed the issue. Working on a fix, should hopefully be resolved the next release 😄

**Comment by kirrg001** [comment]
closing. fixed via #7836
