### ISSUE TITLE
Could not install 

### ISSUE THREAD

**Issue by reihor** [TryGhost/Ghost#7843]
Knex: run
$ npm install sqlite3 --save

Error: Cannot find module '/root/horsttop/ghost/node_modules/sqlite3/lib/binding/node-v46-linux-x64/node_sqlite3.node'

Linux 4.4.0-57-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! ghost@1.0.0-alpha.9 start: `node index`
npm ERR! Exit status 1

**Comment by kirrg001** [comment]
Hey @reihor 👋

Sorry to hear you are having trouble.

We have a troubleshooting guide, see http://support.ghost.org/troubleshooting
There are many related issues for example https://github.com/TryGhost/Ghost/issues/5911 or https://github.com/TryGhost/Ghost/issues/7578.

If you can't solve it or you have any further problems, please head on over to slack - https://slack.ghost.org - and post in the #help channel. This is a bug tracker for ongoing development of the Ghost software, and we're not able to do support here!
