### ISSUE TITLE
Upgrade notification copy

### ISSUE THREAD

**Issue by JohnONolan** [TryGhost/Ghost#7849]
![image](https://cloud.githubusercontent.com/assets/120485/21972180/4e712bfc-dbea-11e6-84c1-40e607aa9ead.png)

In: Latest stable release.

This should read "Ghost" - rather than "Ghost Core". We don't need to pass the burden of understanding what "Core" means onto the end-user.

**Comment by acburdine** [comment]
Closing and moving to Ghost-Desktop.
