### ISSUE TITLE
💅🏼 Take care that blog starts faster if you have too many themes

### ISSUE THREAD

**Issue by kirrg001** [TryGhost/Ghost#7854]
On bootstrap, Ghost validates all themes in your content folder.
It can happen that the Ghost server starts very, very slow. 

We should only check the active theme and not every theme.

**Comment by jomahoney** [comment]
I'm going to jump on this. Will let you know if I need help

**Comment by jomahoney** [comment]
I ran some tests with `console.time()` and got the following results: 
`loadthemes: 42.598ms` - with 13 themes, some quite heavy (14mb) ones
`loadthemes: 26.714ms` - with casper.

Up to you if you really want to proceed with saving ~16ms

**Comment by kirrg001** [comment]
closes via #7970 - will be released in `0.11.5`.
