### ISSUE TITLE
Hardcoded URL in Slack integration

### ISSUE THREAD

**Issue by dominictayloruk** [TryGhost/Ghost#7856]
When creating the slack integration the webhook has to be like;

`https://hooks.slack.com/services/<your personal key>`

This doesn't allow using [Mattermost](https://about.mattermost.com/) which is slack compatible. The webhook format for Mattermost is like;

`https://mattermost.myhost.co.uk/hooks/5nm4v8r77bvdpdycxsf4g49nf8`

Maybe if the requirement wasnt for a hardcoded slack URL then this would be another integration with a simple fix.

I've tried but the only referance i can find is [core/test/unit/slack_spec.js](https://github.com/TryGhost/Ghost/blob/master/core/test/unit/slack_spec.js)

**Comment by ErisDS** [comment]
Hi @dominictayloruk this is hard coded into the admin panel - so you'll find the references in https://github.com/TryGhost/Ghost-Admin if you want to update Ghost for your usecase.

Long term, we hope to have lots of pluggable apps, short term I don't think this is something we'd support, however please submit it as a feature request to ideas.ghost.org as we use that to gauge interest and help us decide what to work on next.

**Comment by kevinansfield** [comment]
The 1.17.3 release has a fix for this, you are able to put any valid URL into the Slack app webhook field so it will work for Discord, Mattermost, and any others 👍

**Comment by dominictayloruk** [comment]
Nice, thanks.
