### ISSUE TITLE
Update the Wiki Roadmap "General Focus" text

### ISSUE THREAD

**Issue by julianfoad** [TryGhost/Ghost#7862]
The "Roadmap" Wiki page

https://github.com/TryGhost/Ghost/wiki/Roadmap#general-focus

ends with a section called "General Focus" which is two years out of date and needs a quick update, please. (Or perhaps remove the section if preferred.)

It currently refers to the "Road to 0.6" and the plan "up until early 2015".

**Comment by ErisDS** [comment]
Yeah, wiki content gets out of date - we don't use that page anymore :)

If you want to follow what we're up to, it's much better to follow along with dev.ghost.org and blog.ghost.org, which are regularly updated 👍

**Comment by julianfoad** [comment]
So is it OK if I delete that page and the references that led me to it?

**Comment by ErisDS** [comment]
Please don't, someone else will come along and raise an issue that it 404s ;)

**Comment by julianfoad** [comment]
What solution do you prefer? Shall I delete the reference to it (which is at the top of the Wiki home page) and insert a note at the top of the Roadmap page saying "Obsolete -- see dev.ghost.org and blog.ghost.org instead" ?

**Comment by julianfoad** [comment]
Or is it mostly still valid and I should just delete the "General Focus" section at the bottom?

Seriously, I want to improve the out-of-dateness situation one way or another. Please advise.
