### ISSUE TITLE
Importer: LTS -> Alpha loses posts_tags relationships etc

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#7866]
Note: We don't yet have a concrete plan for how we're going to do the migration path from LTS to Alpha. It may or may not involve Ghost's export & import functions.

Today I tried out importing an export generated via the LTS into the latest alpha. It mostly worked, and so I think this issue is probably somewhere between a "not considered yet" and a "bug". 

All posts, users, tags, subscribers & settings are imported and updated as I'd expect (barring any known issues: https://github.com/TryGhost/Ghost/labels/importer).

However, after importing, posts don't have any tags associated with them.

### Steps to Reproduce

1. Export a JSON file from an LTS blog, I did this from blog.ghost.org
2. Clear all data on your local blog
3. Import the JSON file
4. Check posts, and see that even though tags were imported, no post has a tag associated with it!

I believe this is likely something to do with the change to ObjectIDs and the complexities of the importer and the post -> tag relationships. 

Note: this bug is NOT present when exporting and importing on the alpha, only with exports from LTS that are imported on the alpha.

Bonus: this should be much easier to re-implement with the use of ObjectIDs?

### Technical details:

* Ghost Version: master (4a4b2f6)
* Node Version: 4.4.7
* Database: Sqlite3

**Comment by vivekannan** [comment]
[Here.](https://github.com/TryGhost/Ghost/blob/master/core/server/data/import/utils.js#L124)

The strict comparison returns false for '1' === 1. This is what happens when LTS JSON is imported as the ids are integers in LTS db. Changing it to non-strict comparison fixes the issue.

**Comment by kirrg001** [comment]
@vivekannan Thanks for getting involved.

https://github.com/TryGhost/Ghost/blob/master/core/server/data/import/utils.js#L118

The `post_id` is an integer originally, but it get's auto converted into a string, because `postsWithTags` is an object.

We could either change the id comparison (convert to strings) or we fix the underlying problem and use `map`, and this is my preferred solution. `map` does not convert number to string by default.

**Comment by vivekannan** [comment]
> we fix the underlying problem and use map

I am sorry, but I don't follow. `map` as in Array's map or underscore's map? Either way, not sure how it will solve the problem.

**Comment by kirrg001** [comment]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map

Something like:

```
postsWithTags = new Map()

each postTags
  postsWithTags.set(...)

each postsWithTags (postId, tagIds)
  ...
  return post.id === postId; // should be true, because post.id is Integer and postId was not converted

**Comment by vivekannan** [comment]
JavaScript has Map now? Did not know that! Will soon make a pull req.

**Comment by vivekannan** [comment]
Using Map does indeed solve the problem but unfortunately, jsHint complains that `Map` is undefined in `new Map();` statement. I had to add an `/*globals Map */` directive to get it to shut up. Is that OK?

**Comment by kirrg001** [comment]
@vivekannan 
We need to update our `.jshintrc` file to support ES6 notation.

`esversion`: `6`

I will push an update to LTS and master branch. If you rebase against the update, your jshint check should be successful.

**Comment by vivekannan** [comment]
OK.

On Mon, Jan 30, 2017 at 4:30 PM, Katharina Irrgang <notifications@github.com
