### ISSUE TITLE
Trailing space in post title deleted when using backspace

### ISSUE THREAD

**Issue by kevinansfield** [TryGhost/Ghost#7886]
@javorszky raised this issue over here https://github.com/TryGhost/Ghost/issues/7754#issuecomment-274882574. I've opened this issue in order to track it separately for the LTS branch.

### Issue Summary

> If you have a title with spaces in it, and you start deleting the last word, as soon as the cursor would delete the first letter of the last word, it also automatically deletes the trailing space, which can be annoying if all you want to do is retype a word. See below.

![broken_title_delete](https://cloud.githubusercontent.com/assets/1196299/22259672/224a2220-e25e-11e6-9266-ded4814e2949.gif)

### Steps to Reproduce

1. Edit or create a post with multiple words in the title
2. Use the <kbd>Backspace</kbd> key to delete the last word in the title, leaving the final space
3. Start typing again, note that the trailing space has been removed

We shouldn't be removing trailing spaces until the input field loses focus.

A recent change to the alpha branch does fix this behaviour, the specific change can be seen here https://github.com/TryGhost/Ghost-Admin/pull/475/files#diff-c92558c8ecbfb99450d1e16549e418b2

### Technical details:

* Ghost Version: 0.11.4

**Comment by acburdine** [comment]
Closed in TryGhost/Ghost-Admin#522
