### ISSUE TITLE
Invite button jumps when "Invite User" modal is shown

### ISSUE THREAD

**Issue by kevinansfield** [TryGhost/Ghost#7890]
### Issue Summary

After clicking the "Invite User" button on the team page the button jumps towards the centre of the screen.

![screen shot 2017-01-25 at 11 58 41](https://cloud.githubusercontent.com/assets/415/22289902/d92f09e6-e2f5-11e6-8db9-a2cf0e0c3a92.png)

### Steps to Reproduce

1. Visit the Team screen with a user who has permissions to invite users
2. Click the "Invite User" button in the top-right
3. Note that the button position jumps

The button should always stay in the same position

### Technical details:

* Ghost Version: master
* Browser/OS: Chrome 55.0

**Comment by radekxrandom** [comment]
I have just checked and cannot find this issue.
<img src="https://puu.sh/tAt7C/e3b691dbf1.png"> </img>

**Comment by kevinansfield** [comment]
@radekxrandom from your screenshot it doesn't look like you are using the alpha (master branch)?

**Comment by vivekannan** [comment]
I can confirm that the issue is present in master. A 'liquid wormhole' container div is inserted into the header causing the button to jump.

**Comment by andreborud** [comment]
#512 & #513

**Comment by andreborud** [comment]
Reference
https://github.com/TryGhost/Ghost-Admin/pull/512

https://github.com/TryGhost/Ghost-Admin/pull/513
