### ISSUE TITLE
Error when URL set as subfolder

### ISSUE THREAD

**Issue by jamrizzi** [TryGhost/Ghost#7900]
### Issue Summary

When a subfolder is set as the ghost url, it gives the following error.

```
Cannot /GET
``` 

### Steps to Reproduce

1. Set the blog url to a url with a subfolder. (https://mywebsite/myblog)
2. Visit the blog and you will get the error

### Technical details:

* Ghost Version: v0.11.4
* Node Version: v4.7.2
* Browser/OS: Chrome/Linux
* Database: MariaDB

**Comment by kirrg001** [comment]
@jamrizzi Hey 👋

If the url contains a subdirectory e.g. www.example.com/blog, then your blog is only available on www.example.com/blog. A request to www.example.com would show the error you have described.

**Comment by kirrg001** [comment]
@jamrizzi 

Can you please swing by our [slack channel](https://ghost.org/slack/)? We can provide better support there than in the Github issue tracker, and if this turns out to be an actual issue with Ghost this issue can be reopened 😬
