### ISSUE TITLE
Custom error messages ignored for known error types

### ISSUE THREAD

**Issue by kevinansfield** [TryGhost/Ghost#7905]
### Issue Summary

Generic error messages are shown for known error types rather than relaying the message received from the server.

![screen shot 2017-01-26 at 11 11 12](https://cloud.githubusercontent.com/assets/415/22329259/66a4d464-e3b8-11e6-8ed8-8d516445d023.png)

### Steps to Reproduce

1. Go to the general settings page
2. Click the "Upload Image" button for the blog icon
3. Upload an image larger than 100kb
4. Note that an error about largest size the server allows is shown rather than the more icon-specific error that we received from the API

If we receive an error message from the API we should show that rather than a generic error message.

### Technical details:

* Ghost Version: master

**Comment by vivekannan** [comment]
Change has to be done [here](https://github.com/TryGhost/Ghost-Admin/blob/767cd7511a84fbc6ed2f8a8cef4fc1e0f30cda3c/app/components/gh-image-uploader.js#L185).

Also its allowing me to 'save' without selecting a file.

**Comment by kevinansfield** [comment]
Note: [ember-ajax v3.0](https://github.com/ember-cli/ember-ajax/releases/tag/v3.0.0) has some simplification of error normalisation that could help here

**Comment by kevinansfield** [comment]
This is no longer a problem, both the error handling and our uploaders have been refactored since this issue was opened.
