### ISSUE TITLE
Ghost 1.0 alpha cannot login when https enabled

### ISSUE THREAD

**Issue by choicky** [TryGhost/Ghost#7907]
please check https://us4-test1.fei-xing.com/ghost/setup/two/ . Https always 422 error.
http works but https doesn't.

**Comment by kevinansfield** [comment]
@choicky you'll only use http or https as the full URL is validated in the oauth redirect - it sounds like you've got the url configured in ghost config as http?

**Comment by choicky** [comment]
@kevinansfield 
If Ghost configure is set to https, Ghost won't start. I don't know why.  therefore I have to set it as http and enable https in Nginx.

**Comment by letsjustfixit** [comment]
My 2 cents: I dont think ghost works as an ssl terminator, you need a webserver to do that for you in front of it. I dont even remember config properties to configure the keys etc....

**Comment by kevinansfield** [comment]
@choicky can you provide an excerpt of your log when you attempt to start Ghost with a https URL?

@letsjustfixit is correct, you will need to terminate the SSL connection in Apache/Nginx but you should still be able to configure ghost with the `url` config option set to a `https://foo` URL. Make sure that in your web server config that you pass on the `X-Forwarded-Proto` header - there's more info with an example nginx config here http://support.ghost.org/setup-ssl-self-hosted-ghost/

**Comment by choicky** [comment]
@kevinansfield @letsjustfixit @kirrg001 

Nginx config of the test ghost is as follows:

```
server {
    listen 80;
    server_name us4-test1.fei-xing.com;
    return 301 https://$server_name$request_uri;
}

server {

    # SSL configuration

    listen 443 ssl http2;
    listen [::]:443 ssl http2;

    server_name us4-test1.fei-xing.com www.us4-test1.fei-xing.com;

    ssl_certificate /etc/letsencrypt/live/us4-test1.fei-xing.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/us4-test1.fei-xing.com/privkey.pem;

    include snippets/ssl-params.conf;

    location / {
        proxy_set_header   X-Real-IP $remote_addr;
        proxy_set_header   Host      $http_host;
        proxy_pass         http://127.0.0.1:2368;
    }
}
```
When Ghost url is set as `"url": "http://us4-test1.fei-xing.com",` Ghost 1.0 alpha cannot login (422 error).

When Ghost url is set as  `"url": "http://us4-test1.fei-xing.com",` I can not access Ghost.  Chrome says `ERR_TOO_MANY_REDIRECTS`.

**Comment by kevinansfield** [comment]
@choicky the problem with 422 errors when using https whilst the url is configured as http has been fixed in master and will be part of the next alpha release.

Regarding the too many redirects problem (I'm assuming you meant to write when the url is set to `https://us4...`) you need to set the `X-Forwarded-Proto` header in your nginx config so that Ghost knows it's a https request and doesn't send a redirect from http->https back. There's an example nginx config here http://support.ghost.org/setup-ssl-self-hosted-ghost/

**Comment by kirrg001** [comment]
@kevinansfield Thanks!

@choicky 
If you need further help, could you please swing by our [slack channel](https://ghost.org/slack/) and ask in the #help channel?

Thanks for your report. 
Closed via https://github.com/TryGhost/Patronus/issues/125
