### ISSUE TITLE
Custom post template - Inconsistent documentation and not working if implemented

### ISSUE THREAD

**Issue by sudeepmandal** [TryGhost/Ghost#7910]
### Issue Summary

This section of documentation states that Ghost supports custom post templates if you create a `post-{{slug}}.hbs` theme file:

http://themes.ghost.org/docs/templates

However, this same page then refers you to this link for more information: [post-context](http://themes.ghost.org/v0.11.4/docs/post-context)

This page states:

> The post context always uses the `post.hbs` template. This template is required in all Ghost themes. At present there is no support for custom post templates as there is for pages.

So I'm confused as to whether this is currently supported or not?
### Steps to Reproduce

1. I currently have a post titled "Test" with a post-slug of `test`. 
2. I adapted `post.hbs` to include a couple of extra scripts in the page
3. I published the page

When I inspect the html for the page, it is clear that the default post template is still being used. 
info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

**Comment by kirrg001** [comment]
Hey @sudeepmandal 

Adding a custom template works. If you have a post called `test` and a template `post-test.hbs`, it will render this template and not the default one.

If you have further questions, can you please swing by our [slack channel](https://ghost.org/slack/)?
We can provide better support there than in the Github issue tracker, and if this turns out to be an actual issue with Ghost this issue can be reopened.

**Comment by cookiejest** [comment]
Hey I would like to confirm this does not work.

I am using ghost 0.11.4

**Comment by kirrg001** [comment]
Will look into tomorrow.
Thanks 👍

**Comment by cookiejest** [comment]
Ok, I realised there is a couple of things -

First it should be 'page-[slug].hbs
The documentation says 'post-[slug].hbs

Secondly I needed to enable Public API in the labs settings.

**Comment by sudeepmandal** [comment]
@kirrg001 - I see this was closed again. Does this mean that you were able to get the `post-[slug].hbs` custom template to work for custom posts with the latest version of Ghost? @cookiejest 's note above doesn't really apply I don't think since he is talking about custom page templates, which is separate from custom post templates.

Could you clarify whether

a) Only custom pages are supported at this time (in which case docs should likely be updated)

or

b) Custom posts do in fact work using `post-{slug}.hbs` in the latest version of Ghost. 

I could not get b) to work, but I'm not sure if that's just isolated to my install.

**Comment by ErisDS** [comment]
This feature doesn't need the Public API to be enabled and it does work in both 0.11.4 and the latest master. I've tested out both.

You *do* need to restart Ghost when adding new templates via the file system though - not sure if that's what's tripping folks up here.

**Comment by sudeepmandal** [comment]
Thanks a lot for replying. The restart may have been the issue in my case. I'll test it out later today. Cheers

**Comment by cookiejest** [comment]
I was not able to create a page with multiple posts data on it without the API feature turned on.

**Comment by kirrg001** [comment]
> Also I am pretty sure 'post-[slug].hbs' is not working even after restart.

Could you please share your steps?Thanks 👍

**Comment by kaelifa** [comment]
Hi, Just to revisit this issue.

I'm trying to make a custom _post_ template.

I can make a custom _page_ template using the ```page-{{slug}}.hbs``` but it's unsuccessful when trying to make a ```post``` version.

Is this expected functionality or should it be possible to recreate both types of custom template _page_ and _post_?

Thank you

**Comment by kirrg001** [comment]
@kaelifa This works fine for me. I have added a post with the slug "test" and added a `post-test.hbs` file in my active theme. The post renders automatically with my new template. Please restart your blog if your blog is running in production mode.

Please use our [forum](https://forum.ghost.org) for further help. Thanks!

**Comment by kaelifa** [comment]
Hi @kirrg001 

Thank you for responding.

I've also realised that I can create a template that appears in a drop-down in the admin settings. Which does the same thing.

But I will also persevere with getting the ```post-{{slug}}``` to work as well.

Thanks again

**Comment by kaelifa** [comment]
@kirrg001 I just have a quick question that I'm a little unclear on.

Do the ```post-{{slug}}.hbs``` files live in the root of the theme or in the partials directory? (I'm trying both, and restarting Ghost, but it's still not working as an override to ```post.hbs``` which is what I'm expecting.

**Comment by kirrg001** [comment]
> Do the post-{{slug}}.hbs files live in the root of the theme or in the partials directory? 

In the root folder. Please double check that you are editing the correct theme.

Please open a [forum topic](https://forum.ghost.org) to get further help. We can re-open this issue if there is a bug in Ghost.

**Comment by sday** [comment]
Interesting. New to ghost but just hit this same issue which required a restart.

Version 2.25.4
Environment development
Database sqlite3
Mail Direct

After ghost install local
In casper  theme did a yarn install and yarn dev

Added a page-test.hbs in Casper which compiled into the "current" directory. Other theme changes did appear to work correctly but this did not.

Did a ghost restart local and boom the page-test.hbs started working.
fwiw

**Comment by ErisDS** [comment]
That's expected behaviour - in development mode changes to existing files are picked up, but new files require a restart.
