### ISSUE TITLE
Lots of "A promise was created in a handler but not returned from it" warnings logged

### ISSUE THREAD

**Issue by acburdine** [TryGhost/Ghost#7911]
### Issue Summary

Seeing lots of "A promise was created in a handler but not returned from it" warnings when running Ghost.

One occurs on startup, [here](https://github.com/TryGhost/Ghost/blob/master/core/server/index.js#L149).
Another one that got logged as I was using Ghost locally (visiting pages, etc.) - [here](https://github.com/TryGhost/Ghost/blob/master/core/server/controllers/frontend/render-channel.js#L42)

### Steps to Reproduce

1. Download Ghost 1.0.0-alpha.10 (I did it using the CLI, but shouldn't matter)
2. Start Ghost
3. Watch logs
4. Notice the one logged on startup, then see others shown as you play around.

### Technical details:

* Ghost Version: 1.0.0-alpha.10
* Node Version: 4.6.0
* Browser/OS: Chrome 55
* Database: SQLite

**Comment by acburdine** [comment]
Note to whoever wants to take this on:

This is an _excellent_ issue for beginners to tackle, as it involves simply adding a `return` to the line that gets logged (see above comment for two specific places).

However, I only did very minimal usage to try and spot any of the promise errors. Whoever fixes this should do some more in-depth hitting of Ghost endpoints to try and spot any more 😄

**Comment by acburdine** [comment]
This also probably occurs in the LTS version of Ghost as well, probably not a bad idea to check there too 😉

**Comment by letsjustfixit** [comment]
fyi
#6935

**Comment by acburdine** [comment]
Ah. Ok then :)
