### ISSUE TITLE
RSS feed improperly formatted (not UTF-8)

### ISSUE THREAD

**Issue by mrnoisytiger** [TryGhost/Ghost#7914]
### Issue Summary

The Ghost RSS feed is showing:

    This page contains the following errors:
    error on line 1 at column 1586: Input is not proper UTF-8, indicate encoding !
    Bytes: 0x10 0x54 0x68 0x65
    Below is a rendering of the page up to the first error.

Instead of a proper RSS feed. The content below the error message shows http://pastebin.com/GU7Hswxe

The first paragraph of my article is here:
http://pastebin.com/WBn1eJ5r

You can find the RAW RSS here:
http://www.inksandpens.com/rss/

Because I use MailChimp's RSS to send emails to my subscribers, I'm at a loss without the RSS feed.

### Additional Testing

After some additional testing, I have found that unpublishing my last post does fix the RSS issue. However, removing all the text/content from that post and saving does not. I have tried changing the title, removing the content, removing the thumbnail image, changing the author, changing the publish date, removing the Metadata, changing the URL, and featuring the post. None of these actions have solved the issue.

Similarly, unpublishing the last post also does not change anything. Upgrading all distribution packages yielded similar results. A reinstall of Ghost also failed to fix the problem. 

### Steps to Reproduce

1. Go to http://example.com/rss

### Technical details:

* Ghost Version: 0.11.4
* Node Version: 4.7.2
* Browser/OS: Any
* Database: MySQL

**Comment by kirrg001** [comment]
Hey @mrnoisytiger Sorry to hear you are having trouble.

Using a rss validator shows, that you have non utf-8 characters in your post. http://www.validome.org/rss-atom/validate 

![rss](https://cloud.githubusercontent.com/assets/1160712/22418768/ae30e9b0-e6da-11e6-95d6-4b4f11a27f16.png)

Deleting these characters should solve the problem. I'm going to close this issue as we use github solely for bug tracking and feature development. If you need further help, please swing by our [slack channel](https://ghost.org/slack/). Thank you 👍

**Comment by alexellis** [comment]
Hi @kirrg001 - I have the same issue generated by my Ghost blog - http://blog.alexellis.io/rss/

Without warning it stopped being parsed by all of the people syndicating/subscribing to my content.
