### ISSUE TITLE
Missing Options for Content Helper

### ISSUE THREAD

**Issue by CCHiggins** [TryGhost/Ghost#7931]
### Issue Summary

I noticed when you use words or characters options to limit the output of the content helper, it's mainly a wrapper around the [downsize package](https://www.npmjs.com/package/downsize). The downsize package offers 2 additional options that would be useful to theme developers

- **Round** would round content cutoff to the end of the next paragraph.
- **Append** would add content after the cutoff.

I think adding round should be an easy fix (allow round to be selected in truncateOptions). Append could be handled in the same way but would limit append option to be used in conjunction with either words or characters.

**Comment by ErisDS** [comment]
Hi @CCHiggins, thanks for popping by!

There are (of course) reasons why support for those attributes weren't added. In fact they were largely added with Ghost in mind but have issues that caused us to rethink adding support.

There is a whole heap of discussion around the content & excerpt helpers in three currently open issues: https://github.com/TryGhost/Ghost/issues/5060, https://github.com/TryGhost/Ghost/issues/3846 and https://github.com/TryGhost/Ghost/issues/2163.

I'm going to close this, as we don't need another issue, however by all means please contribute to those issues or pop by our [slack](https://slack.ghost.org) channel to discuss moving them forward!
