### ISSUE TITLE
OAuth login doesn't work in Edge

### ISSUE THREAD

**Issue by kevinansfield** [TryGhost/Ghost#7936]
### Issue Summary

Clicking the "Sign in with Ghost" button immediately shows a "failed to authenticate" error before opening the login form in a full window. After logging in you're shown a dialog asking if the site can close the window before landing back on the ghost blog but not being logged in.

![edge-sign-in](https://cloud.githubusercontent.com/assets/415/22556700/ff344ae6-e95f-11e6-9980-87164aa4da3d.gif)

### Technical details:

* Ghost Version: master
* Browser/OS: Edge / Windows 10

**Comment by letsjustfixit** [comment]
_Also confirmed for Edge mobile 38.14393.693.0_

**Comment by kevinansfield** [comment]
I have opened an issue on the Torii library we use for the OAuth popup flow https://github.com/Vestorly/torii/issues/335
