### ISSUE TITLE
still cannot login, Ghost 1.0 alpha 10

### ISSUE THREAD

**Issue by choicky** [TryGhost/Ghost#7940]
I've opened an issue https://github.com/TryGhost/Ghost/issues/7907 before, which is currently closed.

I've updated the previous Ghost 1.0 alpha 9 to alpha 10.  I still cannot login.

I reinstalled Ghost 1.0 alpha 10, and I found I still can not login, whatever `"url": "http://us4-test1.fei-xing.com"` or `"url": "https://us4-test1.fei-xing.com"`

Testing url: https://us4-test1.fei-xing.com/ghost

```
server {
    listen 80;
    listen 443 ssl http2;
    listen [::]:443 ssl http2;

    server_name us4-test1.fei-xing.com;

    ssl_certificate /etc/letsencrypt/live/us4-test1.fei-xing.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/us4-test1.fei-xing.com/privkey.pem;

    include snippets/ssl-params.conf;

    location / {
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $http_host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_pass         http://127.0.0.1:2368;
    }
}

```

**Comment by kirrg001** [comment]
Hey @choicky 

You don't have to open a new issue - you can still comment on a closed issue.

As Ghost `1.0.0` is still in alpha, we are resetting the database of our OAuth server time by time.
I looked up your blog and it's not registered.

Also, we did not release `alpha.11` yet, which will contain a related fix in our Ghost-Admin code base, see https://github.com/TryGhost/Ghost-Admin/commit/5383fb18a2d1fab3e55cff6753970d22810c8c9c

My suggestion to you is: wait until `alpha.11` is out (will be released tomorrow), reset your database with `knex-migrator reset` and start from stretch. 

Please use #7907 for further questions or reports, thank you 👍
