### ISSUE TITLE
No root key ('invitation') provided.

### ISSUE THREAD

**Issue by Lewis65** [TryGhost/Ghost#7942]
I'm having trouble inviting new team members from the Ghost admin area.

I'm using Mailgun, and the emails are being sent correctly. However, the invite links to the localhost IP rather than the domain name Ghost is hosted on (i.e., 0.0.0.0/blog/ghost rather than mydomain.com/blog/ghost). Following the invite URL and replacing the domain properly does lead to a signup page, however, entering all information and attempting to create an account results in the error
`No root key ('invitation') provided.`

Ghost 0.2.0
Node 4.4.4
Chrome/Windows 7
MySQL

I'm not sure if it's a bug or something I'm doing wrong, but I couldn't find any other instances of this error ('invitation' missing). Thanks in advance for any help.

**Comment by kirrg001** [comment]
Hey @Lewis65 Sorry to hear you are having trouble.

If this error happens, something went wrong when installing Ghost.
The client sent a wrong data structure to the server. 

I recommend updating Ghost to the latest version by following our [how to upgrade Ghost guide](http://support.ghost.org/how-to-upgrade/)?

If you have further problems, could you please swing by our [slack channel](https://ghost.org/slack/) and ask for help there? Thanks :)

**Comment by Lewis65** [comment]
Hey @kirrg001 - I should have thought of that myself. Apologies.

For anyone reading in the future, updating Ghost and changing app.use(bodyParser.urlencoded({ extended: false })); to true in index.js fixed the issue. (as per https://github.com/TryGhost/Ghost/issues/7752)

Thanks again.
