### ISSUE TITLE
Uploading a new image for a team member triggers an "email already in use" error

### ISSUE THREAD

**Issue by javorszky** [TryGhost/Ghost#7981]
### Issue Summary

See title

### Steps to Reproduce

1. Install Ghost from the ground up (so no upgrades, no reinstall, no existing data)
2. Use an email address that has no gravatar attached to it to sign up
3. Once you're in admin, go to Team members and click into your account
4. Click on the "edit picture" placeholder
5. upload an image and click "save" in the modal
6. observe the red bar about email on top
7. try to click "save" in top right corner
8. observe the second red bar about email on top
9. be sad because your changes weren't saved

I don't expect an unchanged email to trigger the error.

I would love to try to reproduce these steps on `master`, but I can't get Ghost started. Any help would be appreciated about that...

### Technical details:

* Ghost `lts` branch (last commit at the moment: https://github.com/TryGhost/Ghost/commit/e11feea1be47a586830dd99bf585f914ab508573)
* node 6.9.2
* npm 3.10.9
* yarn 0.19.1
* macOS 10.12.3
* Chrome Version 56.0.2924.87 (64-bit)
* sqlite (whatever comes out of the box with this version)

**Comment by javorszky** [comment]
Potentially related: https://github.com/TryGhost/Ghost/issues/6491

**Comment by kirrg001** [comment]
@javorszky Thanks for your report.

I will push a fix tomorrow 👍

**Comment by acburdine** [comment]
Fixed in #7987 and #7986(lts)
