### ISSUE TITLE
Ghost setup on current master using oAuth opens devauth.ghost.org via http, and not https

### ISSUE THREAD

**Issue by javorszky** [TryGhost/Ghost#7983]
### Issue Summary

It's an oAuth scheme, where you authenticate. You put in username and password. The LEAST it could do is be on SSL...

### Steps to Reproduce

1. Start Ghost on `master` (somehow...)
2. Open browser on `localhost:2368`
3. Navigate to `/ghost`
4. Disregard the fact that it throws a 500 error after navigating to `/ghost/setup`, and refresh the page
5. Meet with the "connect to ghost" button, and click it
6. Observe the popup window that's on devauth.ghost.org
7. Try to use 1password or something similar to paste your usernames / password
8. 😮 as you realise that it's Not Secure

<img width="1595" alt="screen shot 2017-02-11 at 12 38 16" src="https://cloud.githubusercontent.com/assets/1196299/22853479/96d32590-f057-11e6-807f-f2ab72b1a46d.png">

### Technical details:

* Ghost Version: `master` at https://github.com/TryGhost/Ghost/commit/196d6d02c0dee1b1321da1e71748f6e0fdd752b0
* Node Version: 6.9.2
* Browser/OS: macOS 10.12.3 / Chrome Version 56.0.2924.87 (64-bit)
* Database: sqlite

**Comment by kevinansfield** [comment]
Hey @javorszky, devauth.ghost.org is explicitly set up without ssl to indicate that it's strictly for development purposes 😉 The database there is wiped every now and then when changes are made to the oauth system, it's only purpose is for temporary access to local development setups for alpha dev and testing - the primary oauth system lives at https://auth.ghost.org and is what is behind the ghost.org login and https://my.ghost.org.

Once these moving parts have settled down and we're ready to come out of alpha the defaults will be revised and there will be a lot more documentation around all of this.

**Comment by javorszky** [comment]
Ah, good to know :). Documentation about it would be ace ;)
