### ISSUE TITLE
Can't upload images on preview screen in mobile form factor

### ISSUE THREAD

**Issue by novaugust** [TryGhost/Ghost#7997]
### Issue Summary

I'm writing a post with a narrow screen and just focusing on the text. When I wanted to insert some images, I wrote the markdown tag, then clicked "preview" to switch to the preview panel. When I drag-and-dropped an image onto the image zone it fired off the "uploading" effects, but when they completed nothing happened.

Only when I widened my screen enough to see both markdown+preview did the image upload box work normally.

### Steps to Reproduce

1. Edit post
2. narrow-ify your screen until the media queries kick in and the preview disappears
3. write `![]()`
4. click preview
5. drag and drop an image onto the image box you created

### Technical details:

* Ghost Version: 0.11.4
* Node Version: (pro)
* Browser/OS: Chrome 56
* Database:  (pro)

**Comment by kirrg001** [comment]
@kevinansfield

**Comment by kevinansfield** [comment]
I'm unable to reproduce this on current LTS, I think a fix may have gone in at some point. Closing for now.
