### ISSUE TITLE
uid function in core/server/utils/index.js for loop is implemented wrong

### ISSUE THREAD

**Issue by sahand12** [TryGhost/Ghost#7998]
### Issue Summary 

uid function in core/server/utils/index.js  accepts a len argument to return a uid with the given length. But its for loop starts from 1 instead of 0 so the returned string length is (len - 1);

**Comment by kirrg001** [comment]
Hey 👋

Yeah this is correct - thanks for your report.
Would you like to push a PR to master?

**Comment by sahand12** [comment]
yeah, sure.
