### ISSUE TITLE
Custom helpers when using as an npm module?

### ISSUE THREAD

**Issue by craig-mulligan** [TryGhost/Ghost#8000]
Hi 👋 , 

I'm using ghost as an npm module and looking to add custom hbs helpers. Express template engines only export a `__express` render method. So is there a way to access the `express-hbs` reference to register helpers? 

Cheers!

**Comment by kirrg001** [comment]
Hey @craig-mulligan 👋

There are some tutorials out there, how to add custom hbs helper.
Maybe this helps: https://zackehh.com/safely-creating-custom-handlebars-helpers/

I'm going to close this issue as we use github solely for bug tracking and feature development.
If you need further help, please come say hello on [our slack team](https://slack.ghost.org) 😄
