### ISSUE TITLE
Handle setup steps and re-work how we activate the owner user

### ISSUE THREAD

**Issue by kirrg001** [TryGhost/Ghost#8003]
Right now Ghost determines the status of the blog setup via the status of the owner user.
See https://github.com/TryGhost/Ghost/blob/master/core/server/api/authentication.js#L510
This route is requested by Ghost-Admin to figure out if the blog setup was completed.

So this is what's happening:
1. You start a fresh blog with a clean database
2. You go to e.g. `localhost:2368/ghost/`, which redirects to you to `/setup/one/`
3. You click create account, which redirects to you `/setup/two/`
4. Now there are two different cases:
4.1 You are using remote auth login, you sign in and proceed by clicking the button 
`Last Step...`, which [activates your user via the token endpoint](https://github.com/TryGhost/Ghost/blob/master/core/server/auth/auth-strategies.js#L124), you are redirected to `/setup/three/`
4.2 You are using local password login, you fill out the form and proceed by clicking the button `Last Step...`, this will trigger a POST to `/ghost/api/v0.1/authentication/setup/`, which [activates your user](https://github.com/TryGhost/Ghost/blob/master/core/server/api/authentication.js#L77), you are redirected to `/setup/three/`

### So there are two problems

1. Status of blog setup depends on owner user status.
2. The user is activated in two different ways.

#### 1) Status of blog setup depends on owner user status

In particular, Ghost-Admin is not able to know which step was the last step you were on.
e.g. you finish step 2, this redirects you to step 3 and you close the browser. You open it again and go to your blog, you will never see step 3, because the setup is already finished, because user is activated. 

I'd suggest, _as the user is not logged in on each step_, we remember the steps in the local storage in Ghost-Admin. We just need to ensure Ghost-Admin cleans the entry if the user completed the blog setup. If we do so, we can remove https://github.com/TryGhost/Ghost/blob/master/core/server/api/authentication.js#L506.
By this, we decouple activating user and remembering the setup steps in Ghost-Admin. The setup steps are anyway a pure Ghost-Admin feature - has nothing todo with the server.

#### 2) The user is activated in two different ways.

We should combine how the user is activated for local password and remote auth login.

**Remote login:** user is activated via `POST /authentication/token` route and blog title and blog description are pushed via settings endpoint update.

**Local password:** user is activated via `POST /authentication/setup` route and blog title and blog description are set via this endpoint as well.

For local password strategy we need to ensure that the email and password get's stored. This happens right now via the `POST /authentication/setup` endpoint.

I'd suggest we add a type parameter to the token route.
e.g. `ghost_type`

So both strategies call `POST /authentication/token` on the second step with `grant_type=authorization_code` or `grant_type=password` and the `ghost_type=setup`.
This signals the server that we are in the setup stage. 

For local password strategy instead of comparing the password, we are adding the email and password to the user. And return a pair of tokens.
For remote auth strategy everything stays as is - we can only improve reusing model functions e.g. create `User.activateOwner`. 

Blog title and blog description should be updated via settings endpoint, as we do for remote login strategy - after Ghost-Admin has received the token pair.

By doing this we are getting rid of all the setup logic and endpoints in Ghost.

Regarding: debugging onboarding issues, I'd suggest we should connect Pro blogs to e.g. sentry and send critical errors to it.

**Comment by kevinansfield** [comment]
I'm not sure we've ever been too worried about step 3? With either auth method you can refresh the page after step 2 and go straight to your blog as setup is "complete", step 3 was just an added extra and is always able to be skipped.

One difference with the Ghost OAuth flow is that setup is marked as complete as soon as you have connected your user even though you haven't set your blog title yet - this was an issue for a while but I think we've circumvented that with syncing to the auth server? In any case I think it may be useful to hold off on setting the "setup complete" flag until we know that step 2 has been submitted? That should mean that we can at detect the state where an owner has connected but not submitted any setup step and direct them back to step 2.

**Comment by kirrg001** [comment]
> I'm not sure we've ever been too worried about step 3

This was just an example. The main goal of this issue is to 1. remember setup steps 2. re-work user activation 3. combine logic for both auth types. Because these three topics are connected.

> One difference with the Ghost OAuth flow is that setup is marked as complete as soon as you have connected your user even

This is true. The token request is triggered directly after your account is connected. But does this make any difference?

> In any case I think it may be useful to hold off on setting the "setup complete" flag...That should mean that we can at detect the state where an owner has connected but not submitted any setup step and direct them back to step 2.

Can't we remember this in Ghost-Admin?Same as Ghost-Admin remembers stuff for the welcome tour. The only thing the server need's to know is when is the first time Ghost-admin requests a token pair. Either via email/password exchange or remote auth token exchange.

**Comment by ErisDS** [comment]
I think this can be closed. There is no need to refactor this anymore? @kirrg001 if I am wrong please reopen.
