### ISSUE TITLE
Importing JSON database with wrong date format throws deprecation warning

### ISSUE THREAD

**Issue by kirrg001** [TryGhost/Ghost#8015]
If you import a database as JSON file into your blog and your dates are formatted like 
`Fri, 18 Oct 2013 23:58:44 +0000`, then Ghost throws a deprecation warning.

```
> moment('Fri, 18 Oct 2013 23:58:44 +0000')
Deprecation warning: value provided is not in a recognized ISO format. 
moment construction falls back to js Date(), which is not reliable 
across all browsers and versions. Non ISO date formats are discouraged and 
will be removed in an upcoming major release. 
Please refer to http://momentjs.com/guides/#/warnings/js-date/ for more info.
```

The date even though get's imported correctly.
The warning occurs if the `hasDateChanged` helper get's called. 
https://github.com/TryGhost/Ghost/blob/lts/core/server/models/base/index.js#L228

I'd suggest, instead of fixing the `hasDateChanged` helper, we should consider updating the database importer to transform dates into proper ISO format.

Ghost: lts|master

**Comment by janvt** [comment]
I pushed a fix for this (https://github.com/TryGhost/Ghost/pull/8052). However, as mentioned there, this only validates the 3 date fields on the post. There are many other date fields in an import that potentially could have the same issue. Should these also be parsed / validated?
