### ISSUE TITLE
spawn yarn ENOENT

### ISSUE THREAD

**Issue by loskiq** [TryGhost/Ghost#8033]
### Issue Summary

What is this?

```
root@ghost:/opt/test# ghost install
 ✖ Checking for latest Ghost version
   → spawn yarn ENOENT
   Running system checks
   Setting up install directory
   Downloading and installing Ghost
   Moving files
spawn yarn ENOENT
```

### Technical details:

* Ghost Version: ghost installer
* Node Version: 6.9.5
* Browser/OS: Debian Jessie x86_64
* Database: SQLite

**Comment by ErisDS** [comment]
@loskiq would you mind raising this on the Ghost-CLI repo: https://github.com/TryGhost/Ghost-CLI instead of here please?

**Comment by loskiq** [comment]
@ErisDS Okay
