### ISSUE TITLE
Apps -> AMP shows Slack icon

### ISSUE THREAD

**Issue by jlelse** [TryGhost/Ghost#8038]
### Issue Summary

The wrong icon is shown on Apps -> AMP. It shows the Slack icon.

### Steps to Reproduce

1. Go to the Admin panel
2. Go to Apps
3. Click on AMP

### Technical details:

* Ghost Version: 0.11.5
* Node Version:
* Browser/OS: 
* Database:

**Comment by kevinansfield** [comment]
Thanks @jlelse and good spot, we'd totally missed that!

**Comment by jlelse** [comment]
No problem 😂

**Comment by kevinansfield** [comment]
Closed via https://github.com/TryGhost/Ghost-Admin/issues/544
