### ISSUE TITLE
Version check fails for Node.js v6.10.0

### ISSUE THREAD

**Issue by hinderaker** [TryGhost/Ghost#8040]
### Issue Summary

Ghost pre-install version check fails for Node.js v6.10.0. To complete the installation you have to disable version checking all together.

### Steps to Reproduce

1. Install Node.js v6.10.0.
2. Install Ghost.

As Node.js v6.10.0 is the latest LTS release, Ghost should accept it.

### Technical details:

* Ghost Version: 0.11.3
* Node Version: 6.10.0
* Browser/OS: Debian 8.7 (jessie)
* Database: SQLite 3.10.10

**Comment by kevinansfield** [comment]
FYI, anyone looking to pick this up I believe the offending code is here https://github.com/TryGhost/Ghost/blob/lts/core/server/utils/npm/preinstall.js#L34. My guess is that string sorting is failing us here because "10" comes before "9"

**Comment by ajeffrey** [comment]
checking versions using string comparison? oo-er.

**Comment by fillipvt** [comment]
Found this today, how can I bypass this error?

**Comment by hinderaker** [comment]
[http://support.ghost.org/supported-node-versions/](http://support.ghost.org/supported-node-versions/)

> To disable the startup check in Ghost, set the environment variable GHOST_NODE_VERSION_CHECK to be false.
> 
> E.g. GHOST_NODE_VERSION_CHECK=false npm install --production.
> 
> E.g. GHOST_NODE_VERSION_CHECK=false npm start --production.

**Comment by paulomcnally** [comment]
http://www.nodenica.com/error-al-instalar-ghostjs-version-0-11-5-en-heroku/ #spanish

**Comment by kirrg001** [comment]
closes via https://github.com/TryGhost/Ghost/pull/8046
