### ISSUE TITLE
Cover Image slows down requests

### ISSUE THREAD

**Issue by sebgie** [TryGhost/Ghost#8041]
### Issue Summary

When an image from an external source is included as cover image for a post the image size is calculated when the post is first loaded. This works quite well under normal circumstances. If the external image is loading slowly or not at all the request is stuck while the image is loading.

### Steps to Reproduce

1. Create a new post with a cover image that is loading slowly
2. Publish
3. Visit the post
4. Observe the first request being slowed down by loading the image while rendering

Short term fix would be to set the already existent timeout to an acceptable value (https://github.com/TryGhost/Ghost/blob/master/core/server/utils/image-size-from-url.js#L33).

Long term we should store the image size at the time when the image is added.

### Technical details:

* Ghost Version: master & 0.11.4
* Node Version: LTS 4
* Browser/OS: Chrome
* Database: SQLite & MySQL

**Comment by kirrg001** [comment]
@AileenCGN Could you PR the fix to master as well?Thanks :)

**Comment by ErisDS** [comment]
@kirrg001 can you please copy over this change before the next release?

**Comment by kirrg001** [comment]
👍

**Comment by ErisDS** [comment]
This was closed by #8044 and #8189. We can revisit a longer term fix later if we need to.

**Comment by ErisDS** [comment]
This is not fixed, reopening
