### ISSUE TITLE
Wrong font on macOS

### ISSUE THREAD

**Issue by Kuzoin** [TryGhost/Ghost#8042]
### Issue Summary

Wrong font on macOS.

![ghost](https://cloud.githubusercontent.com/assets/23366922/23259313/c578bfb2-f9cc-11e6-885c-e24b2777925b.png)

Should be:

![ghost-content-1152x](https://cloud.githubusercontent.com/assets/23366922/23259343/ec5d4260-f9cc-11e6-99c7-19de65069d17.png)

### Technical details:

* Ghost Version: 0.11.3 / 0.11.4 / 0.11.5
* Node Version: v6.9.4
* Browser/OS: Safari, Chrome / macOS Sierra 10.12.3
* Database: SQLite

**Comment by kevinansfield** [comment]
Hi @Kuzoin, thanks for reporting the issue. For clarification are you referring to the header font in the side-by-side preview not matching the content screen preview?

**Comment by Kuzoin** [comment]
Hello @kevinansfield yes, this issue affects only editor (all text).

![zrzut ekranu 2017-02-23 o 13 44 44](https://cloud.githubusercontent.com/assets/23366922/23259722/c524b14a-f9ce-11e6-8621-ac8ff56e2fb1.png)

Seem to be missing Open Sans

**Comment by Kuzoin** [comment]
@kevinansfield iOS (10.2.1 / Safari) the same problem:

![img_2828](https://cloud.githubusercontent.com/assets/23366922/23260053/552815c4-f9d0-11e6-80cf-384cb6a4e71a.PNG)

**Comment by kirrg001** [comment]
@kevinansfield Is this a bug?

**Comment by kevinansfield** [comment]
Not sure. The fonts are correct as far as I can tell. @JohnONolan may have more insight

**Comment by JohnONolan** [comment]
Looks right to me
