### ISSUE TITLE
Failed to upgrade

### ISSUE THREAD

**Issue by mskian** [TryGhost/Ghost#8045]
Hey did u check the Download package version when I try to Upgrade My Ghost version via Digitalocean it downloads 0.11.4 only please update latest download package URL 

### Technical details:

* Ghost Version: 0.11.4
* Node Version: 6.10.0
* Browser/OS: Ubuntu
* Database:

**Comment by kevinansfield** [comment]
Hey @mskian, thanks for reporting. Our cache hadn't updated properly, the download url points at the correct version now! 😄
