### ISSUE TITLE
Need upload static files in Markdown Editor

### ISSUE THREAD

**Issue by evolutionjay** [TryGhost/Ghost#8048]
### Issue Summary

Ghost 0.11.5
Safari 10.x

### Steps to Reproduce

1. New post
2. upload zip, psd  or pdf file

### my request

Add an upload static files plug-ins  Plz

**Comment by kevinansfield** [comment]
Hey @evolutionjay, thanks for taking the time to make this feature request, however we only use Github for bug tracking and on-going development work. For feature requests please add them or upvote existing requests on our wishlist https://ideas.ghost.org. Thanks! 😄

**Comment by kevinansfield** [comment]
FYI, the workaround is to upload your files to a static file host, e.g. Amazon S3 or similar and link to them directly in your post.

**Comment by evolutionjay** [comment]
@kevinansfield  Yes , I knew.  But, I am in China.... China people can't use Google,  Amazone
 s3 and Dropbox... Bcz the fu*k internet Great Wall...

So the static file only can be host in local server.

If has any plugin like this:
<img width="1252" alt="wx20170228-110408 2x" src="https://cloud.githubusercontent.com/assets/4468540/23389893/c892a4c4-fda5-11e6-91b3-153115b57bfd.png">

**Comment by nuclearpengy** [comment]
You could FTP the file up to the local server or to another one and reference it directly by pasting in the URL.

**Comment by evolutionjay** [comment]
@nuclearpengy  If the article is relatively small and only one user can do so, but if I have thousands of articles, I do not know that the corresponding file is not needed, and if it is multi-user, you can not guarantee each The author knows ftp

**Comment by nuclearpengy** [comment]
Maybe you could link to a resource hosted on Dropbox or a similar service?

**Comment by evolutionjay** [comment]
@nuclearpengy I am in China...Maybe someday someone the same situation like me in Chian can't use google dropbox

**Comment by nuclearpengy** [comment]
If you can, jump into the Slack group - there are lots of helpful people there who might be able to contribute ideas.

**Comment by evolutionjay** [comment]
In any case, I use wordpress to solve my problem, but the Ghost is still my favorite program, and yes i am going to slack see you there

**Comment by nuclearpengy** [comment]
Cool, see you there. 😄
