### ISSUE TITLE
Image in meta data

### ISSUE THREAD

**Issue by shystruk** [TryGhost/Ghost#8051]
Hi!

How can I add an image in metadata info?

**Comment by kevinansfield** [comment]
Hey @shystruk, I'm not sure I'm following what you are trying to do, sorry. The best place to get help is on our [slack channel](https://slack.ghost.org) where the community can also get involved and the real-time communication makes things a lot easier 😄 

I'm going to close this issue as we don't offer support on Github, we try to keep it solely for tracking bugs and on-going development work.
