### ISSUE TITLE
Admin panel search bug

### ISSUE THREAD

**Issue by emilgoldsmith** [TryGhost/Ghost#8053]
### Issue Summary

Chrome on Ubuntu 16.04, ghost admin panel when you try searching for an article. Some keys like for example space don't write a space in but instead then work as a "return" outside of the search bar or something like that. What happens exactly anyway is that the search bar will clear and sometimes the screen changes to something else, which seems to be maybe what menu item was marked before. So right now I can't search for anything with a space.

### Steps to Reproduce

Yeah to reproduce you should just write anything with a space in the search bar.

### Technical details:

* Ghost Version: 0.10.0
* Node Version: 4.2
* Browser/OS: Chrome/Ubuntu
* Database: MySQL (MariaDB)

**Comment by kevinansfield** [comment]
@emilgoldsmith I've not been able to reproduce this on the latest version, could you try upgrading from 0.10.0 to 0.11.5 and see if this is still an issue?

**Comment by emilgoldsmith** [comment]
Hmm.... Just updated locally and it seems to fix it. I'll put the upgrade live when there's less traffic on the site and close it if it fixes the problem, thanks.

**Comment by emilgoldsmith** [comment]
Hi, put it live and it fixed it, thanks :). Closing the issue.
