### ISSUE TITLE
Bug, Blog shows 500 error for large themes

### ISSUE THREAD

**Issue by cobbspur** [TryGhost/Ghost#8056]
### Issue Summary

Blog shows 500 error when using a theme with many files in it (>100).

### Steps to Reproduce

1. Create a theme with many files in it.
2. Upload and activate theme.
3. Load blog in browser.

### Technical details:

* Ghost Version: Current LTS

**Comment by kirrg001** [comment]
@ErisDS Can this be closed or is there anything left for alpha here?
