### ISSUE TITLE
0.11.6 broke static page template

### ISSUE THREAD

**Issue by krokofant** [TryGhost/Ghost#8082]
### Issue Summary

Updated from 0.11.4 to 0.11.6 at which point all my static pages used the non-static page template. 

### Steps to Reproduce

I have no reproduction step as of now.

### Technical details:

* Ghost Version: 0.11.6
* Node Version: 6.9.5
* Browser/OS: Chrome Canary
* Database: SQLite

Ghost installed via npm module and mounted in express.

**Comment by ErisDS** [comment]
Thanks for raising 👍  we are aware of this issue and working as fast as we can to push out 0.11.7.

See #8081

**Comment by krokofant** [comment]
Haha, I'm a bit amazed and intrigued to see you working so fast 🥇

**Comment by ErisDS** [comment]
Fix for LTS is merged, will now do a similar fix for master, which will close this issue.
