### ISSUE TITLE
502 error after alpha update

### ISSUE THREAD

**Issue by joepierce** [TryGhost/Ghost#8098]
Welcome to Ghost's GitHub repo! 👋🎉

Do you need help or have a question? Please come chat in Slack: https://ghost.org/slack 👫. Got an idea for a new feature? Please add it to our wishlist: http://ideas.ghost.org 🌟. Found a bug? Please fill out the sections below... thank you 👍

### Issue Summary

A summary of the issue and the browser/OS environment in which it occurs. 

### Steps to Reproduce

1. This is the first step
2. This is the second step, etc.

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

### Technical details:

* Ghost Version:
* Node Version:
* Browser/OS: 
* Database:

**Comment by kevinansfield** [comment]
Hey @joepierce, sorry to hear you're having installation issues. A 502 error means that ghost is likely not running or failing to start.

We don't provide support on Github as we try to keep it clear for bugs and on-going development only but we do have a very helpful community over on our [Slack channel](https://slack.ghost.org). If a verifiable bug is found we can re-open this or open a new issue for the specific problem. If you ask for help on Slack be sure to provide as much info as possible - any errors you're seeing in the Ghost logs etc, it'll make it a lot easier to help track down what's wrong 😄
