### ISSUE TITLE
Card Menu UI

### ISSUE THREAD

**Issue by JohnONolan** [TryGhost/Ghost#8106]
![image](https://cloud.githubusercontent.com/assets/120485/23705158/66b00630-0443-11e7-8d14-bc50c2b7a52b.png)

Markup output for card menu UI now exists on Labs page - needs to be moved into editor. Ideally should also be able to use keyboard-arrows to move autocomplete selection (just previous/next nav is fine, don't need full directions) -- but this can also be punted if a PITA

One weird thing that I'm not sure about:

There are two ways to trigger this menu, one is by typing `/` and the other is by pressing the `+` icon.

If you press the `+` icon, then it makes sense that there is a search-box contained within the card menu.

but if you type `/` then the expectation would be that you continue typing after that slash to filter/trigger autocomplete, eg `/ image`

Not sure how to handle this? Maybe show the saerchbox inside the card-menu, only if it is triggered from the `+` icon?

**Comment by JohnONolan** [comment]
![image](https://cloud.githubusercontent.com/assets/120485/23956820/59077780-09a6-11e7-86f7-56ad06dc6b85.png)

Can we remove this "active" styling? from the text element

**Comment by JohnONolan** [comment]
I also have a bug w/ + icon disappearing, just click on it twice - when the card menu closes it also gets rid of the + icon

**Comment by disordinary** [comment]
@JohnONolan, sure.

It's not an 'active' state though, it's a prompt to show the user which item is selected for keyboard selection, this is more important for the '/' menu than the '+' menu. Maybe we disable keyboard selection? Or visually show another prompt?

**Comment by disordinary** [comment]
Just a note, in the '+' card menu the key-change event handler is fired multiple times making the cursor move erratically, this doesn't happen in the '/' menu.

**Comment by JohnONolan** [comment]
> it's prompting the user as to what the current element is, it's a prompt to show the user which item is selected for keyboard selection

That's makes sense. Could we make it select nothing to begin with? Then on the first key press it selects the first item.

**Comment by JohnONolan** [comment]
I'm also noticing a 0.3s delay between clicking on "upload an image" once an image card is inserted, and the browser upload dialog being triggered. Not sure if these little things should have their own issues or if I should just continue to add them in here. Let me know what's preferred
