### ISSUE TITLE
 SecurityHeaders.IO score for ghost.org: F, missing security headers!

### ISSUE THREAD

**Issue by SecurityHeadersIO** [TryGhost/Ghost#8113]
[SecurityHeaders.IO score for ghost.org: **F**](https://securityheaders.io/?q=ghost.org&followRedirects=on).

Missing security headers:

1. [Strict-Transport-Security](https://scotthelme.co.uk/hsts-the-missing-link-in-tls/)
2. [Content-Security-Policy](https://scotthelme.co.uk/content-security-policy-an-introduction/)
3. [Public-Key-Pins](https://scotthelme.co.uk/hpkp-http-public-key-pinning/)
4. [X-Frame-Options](https://scotthelme.co.uk/hardening-your-http-response-headers/#x-frame-options)
5. [X-XSS-Protection](https://scotthelme.co.uk/hardening-your-http-response-headers/#x-xss-protection)
6. [X-Content-Type-Options](https://scotthelme.co.uk/hardening-your-http-response-headers/#x-content-type-options)
7. [Referrer-Policy](https://scotthelme.co.uk/a-new-security-header-referrer-policy/)

**Comment by ErisDS** [comment]
Closing this and reporting unsolicited bot activity.
