### ISSUE TITLE
How can I remove tags links from the sitemap.xml?

### ISSUE THREAD

**Issue by pedrommuller** [TryGhost/Ghost#8120]
I noticed two XML sitemaps one for tags and the other for authors, I like to remove both, how can I prevent these files to be part of the mail XML structure?

http://site.tld/sitemap-authors.xml
http://site.tld/sitemap-tags.xml

**Comment by kevinansfield** [comment]
Hey @pedrommuller, as far as I'm aware it's not currently possible to disable author or tag pages and they'll always be output in the sitemap as well. What is your use case for preventing the files from being output in sitemap.xml?

If you want to edit core files I think you should be able to modify this line to remove the authors and tags links from the main sitemap https://github.com/TryGhost/Ghost/blob/master/core/server/data/xml/sitemap/index-generator.js#L9

**Comment by pedrommuller** [comment]
@kevinansfield thanks for the quick reply, in my case, it doesn't bring to much value from the SEO perspective I like to use tags to include some keywords in my content but not to generate another URL, most of the tags landing pages are giving me a high bounce rate.

For authors, it is a personal blog but I do have another person that double checks grammar and the spelling of the post that I don want to be listed on the authors page.

It would be great to have the option so customize the sitemap in the admin panel or any flat file
anyway, I'll look at the code and modify it.

thanks,
Pedro.

**Comment by nuclearpengy** [comment]
@pedrommuller I also have someone review my (personal) posts. In my case, what I did was set up a Google doc for editing and reviewing. When the content is ready, I copy it into my blog. This way I don't need an additional author profile.

**Comment by pedrommuller** [comment]
@nuclearpengy yeah makes sense, actually, I kind of do the same, sometimes I just want some small editions on the posted content for this person to do and I don't like to share my ghost account.

some small details, nothing that it couldn't been fixed with a workaround outside of the ghost platform as you mentioned.

Thanks for sharing!

**Comment by kevinansfield** [comment]
FYI, it's also possible to remove the auto-generated author and tag pages by editing the [channels config file](https://github.com/TryGhost/Ghost/blob/stable/core/server/controllers/frontend/channel-config.js#L12-L43)

I'm going to close this issue as the current behaviour is expected, we also have roadmap plans to expand the channels config and make it configurable without editing core files. May I also suggest https://ideas.ghost.org? We use that to keep track of feature requests and gauge support/gather the differing requirements for each feature, it's always helpful to have ideas put forward/voted on/use cases explained! Thanks 😄

**Comment by pedrommuller** [comment]
Thanks for the follow-up @kevinansfield I just posted the issue because I wanted some attention to my "question" which is not an issue at all, I didn't know about ideas.ghost I'll check it out, just is there any channel just for questions?

regards,
Pedro.

**Comment by nuclearpengy** [comment]
Best place for general Q&A is https://ghost.slack.com, you can invite yourself here: https://slack.ghost.org/

**Comment by pedrommuller** [comment]
awesome @nuclearpengy thanks for the help!
