### ISSUE TITLE
Calling the public API from external website

### ISSUE THREAD

**Issue by aimanbaharum** [TryGhost/Ghost#8130]
### Issue Summary

Hey guys, I'm trying to grab 4 of my recent posts from my blog to another website of mine. I've followed the guide on Ghost API [docs](http://api.ghost.org/docs/ajax-calls-from-an-external-website) about ajax calling from an external website, but there is this one part I don't seem to get correctly because my ghost.db doesn't seem to have `client_trusted_domains` table.

Also, after running `select * from clients;`, there is only one row which is the `ghost-admin` but there is no `ghost-frontend`.

I've just upgraded my Ghost blog from version 0.6, iirc. Could it be because it didn't do the migration during the upgrade? Or I missed something here?

Anyway, I jumped straight to [section 2](http://api.ghost.org/docs/ajax-calls-from-an-external-website#2-adding-the-api-utility-to-your-site) of the doc, it seems to be working on my localhost, but not on live site.

Any guidance?

### Technical details:

* Ghost Version: 0.11.7
* Node Version: 0.10.37
* Browser/OS: Ubuntu 14.04 (Hosted)
* Database: Sqlite3

**Comment by ErisDS** [comment]
@aimanbaharum sorry to hear you're having trouble. This kind of support issue belongs in our [slack channel](https://slack.ghost.org/) please.

**Comment by aimanbaharum** [comment]
This issue is now fixed. As for my own reference, I will keep a note here.

---

> because my ghost.db doesn't seem to have `client_trusted_domains` table
>
> running `select * from clients;`, there is only one row which is the `ghost-admin` but there is no `ghost-frontend`

The issue is because I ran my blog in development mode. Instead, it should be run as `--production`. Then the migration of the new tables will happen. Now I have both issue fixed.

> it seems to be working on my localhost, but not on live site.

Fixed this issue by changing the `clientSecret` to the production one.
