### ISSUE TITLE
0.11.7 Setting->General only show active theme after Ghost restart when using ghostServer.rootApp

### ISSUE THREAD

**Issue by J-Siu** [TryGhost/Ghost#8135]
### Issue Summary

0.11.7 Setting->General only show active theme after Ghost restart. Express app `rootApp` returned by `ghost()` is not fully functional if not using`ghostServer.start()`.

### Steps to Reproduce

1. Install Ghost 0.11.7
2. Put a theme into the themes directory
3. Test with a minimal `index.js` :

```
let
	ghost = require('./core'),
	http = require('http')

ghost().then((ghostServer) => http.createServer(ghostServer.rootApp).listen(2368, '0.0.0.0'))
```

4. Upload a theme using Setting->General, both manually copied theme and the upload theme will show. Activate one of the theme.
5. Restart Ghost, again, only the active theme is shown in Setting->General.

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

`ghostServer.rootApp` returned by `ghost()` should be fully functional.

### Technical details:

* Ghost Version: 0.11.7
* Node Version: v6.9.5
* Browser/OS: FF/Safari
* Database: sqlite

**Comment by oliverbenns** [comment]
Did you have a package.json in your theme folder?

**Comment by J-Siu** [comment]
I do. The theme I use is a fork of Casper. GitHub: https://github.com/J-Siu/casper-js

**Comment by ErisDS** [comment]
Hi @J-Siu did this still occur after refreshing the admin panel? Do you have a lot of themes? Were there any errors in the server output? 

Only the active theme is loaded on first boot, the remaining themes are loaded after the server has started. It would be possible to do a request between the time of first boot when the themes are loaded. Refreshing would resolve this issue.

The theme loading is working correctly for me on the latest LTS with Node 6.9.5, which suggests there must be some other factor of your setup causing the issue.

If you can dig out an error that would be very helpful.

**Comment by J-Siu** [comment]
Hi @ErisDS , I just confirmed this issue is specific to my environment setup. I will close this issue now. Sorry for the confusion.

**Comment by ErisDS** [comment]
Hey @J-Siu that's good to hear :) Maybe you could post a few details of what the problem was so anyone else who finds this issue knows what to check?

**Comment by J-Siu** [comment]
@ErisDS I wasn't using the standard https setup, but instead a modified `index.js` I posted it [here](https://github.com/J-Siu/ghost-https-indexjs). It was working in 0.11.4, but issue come up in 0.11.7.

The problem properly due a new even emitter in the ghost server start function, which was not in 0.11.4.

The issue go away after I modify the index.js using http-proxy and the issue go away. Not perfect, but at least it is working.

**Comment by J-Siu** [comment]
@ErisDS Please reopen this issue. I change my test base on information https://github.com/TryGhost/Ghost/wiki/Using-Ghost-as-an-NPM-module, and still getting the same issue.

**Comment by J-Siu** [comment]
@ErisDS I am reopening this issue. I change my test base on information https://github.com/TryGhost/Ghost/wiki/Using-Ghost-as-an-NPM-module, and still getting the same issue.

**Comment by J-Siu** [comment]
Closing. Not an issue anymore.
