### ISSUE TITLE
Redirected to my-ghost-blog.com on first prod run

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#8152]
I was recently testing the new admin split code and I needed to test production mode.

After switching to production mode, I was redirected from http://localhost:2368/ghost -> http://my-ghost-blog.com.

This is a problem because of the following common case:

1. I install Ghost on my server using ghost-cli 
2. As part of that, I tell Ghost I want my URL to be http://hannah.wf. I haven't set my DNS up yet though, I'm just getting Ghost installed and will configure my DNS later.
3. I try to go through the ghost setup flow

Note: if I don't add a url, I get sent to my-ghost-blog. If I do add one, e.g. if I configure http://hannah.wf locally, I get redirected to my Ghost(Pro) admin panel.

This issue is something that was changed as part of the [work to simplify our url config](https://github.com/TryGhost/Ghost/pull/7937) and then revisited after we discovered this issue in https://github.com/TryGhost/Ghost/pull/7956

It seems like it is working correctly until I try to visit `/ghost/`. I don't have a special admin URL configured, so I think it is wrong that a redirect is happening?

### Steps to Reproduce

1. Run `grunt prod`
2. Don't edit the production config url, but do make sure you've got valid DB credentials
3. Run `npm start --production`
4. Try to visit your blog

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

### Technical details:

* Ghost Version: master + #8142 + TryGhost/Ghost-Admin#574
* Node Version: 4.4.7

**Comment by kirrg001** [comment]
If we allow to navigate via localhost to the admin panel, you will get a redirect mismatch from the auth service 😐

The problem with this case is, that Ghost registers a public client on bootstrap. Ghost sends as redirect url either the configured admin url (which is not present for the default production setup) or the blog url as fallback (`my-ghost-blog.com/ghost` or your custom blog url you have configured via the CLI). The admin url in Ghost is optional. So even if we register the public client with the redirect url `localhost:2368/ghost`, you will get a mismatch if your DNS is setup and you navigate to `my-ghost-blog.com/ghost`. The redirect url get's only updated in the auth service if the url changes. This is only the case if you either change your blog url or you add the custom admin url. So if you set your custom blog url via the CLI directly, you won't change the config anymore.

I am not sure how to support this case. What we could do is making the use case more visible to the user, that he has to setup his DNS first?

**Comment by ErisDS** [comment]
Hmm - this seems like a deeper problem to me. 

Usecase: I'm moving my blog from my other server that's running wordpress. What do I do now?

**Comment by kirrg001** [comment]
**Different server:** The new server has a public ip. You can use this public ip to login to the admin panel. If you later switch DNS, you update the blog url in the config and restart. Ghost will auto update the remote auth service.

**Same server:** Your wordpress url is "example.com" and you set "example.com:2000" for your blog url in ghost. So you are running two processes on 80 and 2000. If are finished with porting, then you can change the blog url in the config and restart. Ghost will auto update the remote auth service.

**Comment by kirrg001** [comment]
What we would like to do here is to make some actual testing on a live server to figure out problems and real use cases. And then we'll decide.
