### ISSUE TITLE
Editor freaks out when highlighting large blocks of text

### ISSUE THREAD

**Issue by JohnONolan** [TryGhost/Ghost#8153]
When highlighting text from bottom to top of screen, editor freeks out trying to scroll up / jumping back (can't really tell from the gif due to FPS, but it flickers and goes nuts). Then when cursor is released, toolbar appears in an odd place

![uh](https://cloud.githubusercontent.com/assets/120485/23894526/1c925fd2-08ab-11e7-9896-1f74276fcba9.gif)

**Comment by disordinary** [comment]
The Toolbar appears in the middle because as far as the browser is concerned multi line selections are full width, there's not much we can do about that (unless we do some expensive text measuring). Medium has the same behaviour. 

We can do something about the scrolling though.
