### ISSUE TITLE
Convert PSM unit tests to integration tests

### ISSUE THREAD

**Issue by kevinansfield** [TryGhost/Ghost#8154]
In [this commit](https://github.com/TryGhost/Ghost-Admin/commit/a2c389e18d849daf071beba760dd7d847f8c150d) the PSM (post settings menu) unit tests were temporarily disabled. The new PSM component is dependent on a number of services that are difficult to test in the limited unit test environment, creating integration tests will allow for much better coverage and real-world testing.

TODO:
- [ ] convert existing unit tests to integration tests
- [ ] improve coverage for things such as the meta pane switch, validation, etc
- [ ] remove old unit tests file

**Comment by TienSFU25** [comment]
can I sign up for this?

**Comment by TienSFU25** [comment]
I'm trying to get an "it renders" test to run. This was what I tried

`it('renders', function() {
    const dummyUser = {
        name: "someone"
    };

    const storeStub = Service.extend({
        query(str) {
            return new Promise((resolve, reject) => {
                resolve(dummyUser)
            });
        };
    });

    this.register('service:store', storeStub);
    this.inject.service('store', {as: 'store'});

    var myModel = {
        slug: "bar"
    };

    this.set('closeNavMenu', function () {});
    this.set('closeMenus', function () {});
    this.set('model', myModel);

    this.render(hbs`
        {{gh-post-settings-menu
            model=myModel
            showSettingsMenu=false
            closeNavMenu=(action closeNavMenu)
            closeMenus=(action closeMenus)
        }}
    `);

    // expect(this.$()).to.have.length(1);
});`

What's the correct way to stub the `store` service? I get this error

`TypeError: Cannot read property 'then' of undefined
    at Class.didReceiveAttrs`

I think I can use some more direction on this task

**Comment by ErisDS** [comment]
Closing this issue as it isn't really needed - PSM code needs revisiting and a lot of the tests are in acceptance tests already.
