### ISSUE TITLE
Hanging editor on double clicks

### ISSUE THREAD

**Issue by JohnONolan** [TryGhost/Ghost#8155]
Getting lots of hanging/delay behaviour when double clicking around the editor to select different areas (Chrome/Mac)

![uh](https://cloud.githubusercontent.com/assets/120485/23898172/c1144be4-08b8-11e7-8868-f4a3798081c6.gif)

**Comment by disordinary** [comment]
This was an issue a little while ago so it is interesting that it re-appeared. It was to do with ember runloops.

I'll have to dig into it further as i'm not seeing the same locally.

**Comment by disordinary** [comment]
I think this issue can be closed?

**Comment by kevinansfield** [comment]
I can't reproduce on master either, closing.
