### ISSUE TITLE
Invalid / unbalanced HTML in the embed card won't save.

### ISSUE THREAD

**Issue by disordinary** [TryGhost/Ghost#8165]
The HTML parser used by the `embed` card doesn't respond well to malformed HTML.

To reproduce:
1. Create an HTML card
2. Type in `<h1>TEST`
3. Save

We either need to find a new HTML parser or save broken HTML as plain text.

**Comment by ErisDS** [comment]
To play DA here, why do we need to parse the HTML?

**Comment by disordinary** [comment]
I really wish we didn't have to.

Because the `mobiledoc-html-renderer` was deprecated we've switched to the `mobiledoc-dom-renderer` which uses the Ember simple-dom library, although it has just occurred to me that we can pass in any library which simulates the DOM so should be able to use `jsdom` directly and not as a middle man 🤦‍♂️.

If we don't want to parse the HTML we need to revert to `mobiledoc-html-renderer`.

For our light weight use case for cards on the frontend the HTML renderer is the better option, I'll find out why it was deprecated.

**Comment by ErisDS** [comment]
OK cool, cos parsing HTML just to render a blog post is total overkill IMO 👍

**Comment by disordinary** [comment]
I agree.

**Comment by disordinary** [comment]
I've left it using the mobiledoc-dom-renderer as recommended by the mobiledoc project, if this starts causing problems then we can move back to the unsupported mobiledoc-html-renderer.

My main reason for doing this is because Mobiledoc is moving to 1.0, and while the features haven't been finalised yet we can expect some breaking changes.
