### ISSUE TITLE
url post problem on google search

### ISSUE THREAD

**Issue by ubuntutest** [TryGhost/Ghost#8168]
I wrote my first post,
The link to my post is http://example.com/post_1/
When I search it on google I find http://example.com/DATE/post_1/
If i click on it i get 404 page not foud, why?

http://imgur.com/a/Ysd2L

Why Google find the post with date-url, a broken url?

EDIT:
"Dated Permalinks
Include the date in your post URLs"
IS DISABLED 

Why google add it ?

**Comment by kirrg001** [comment]
Hey @ubuntutest 👋 Sorry to hear you are having trouble.

This is definitely not a Ghost bug. If the date permalinks were enabled once and Google cached your page, then one option is to permanently redirect the old url to the new url. This could be done via our redirects feature. See http://support.ghost.org/redirects/

Please swing by our [slack channel](https://ghost.org/slack/) next time and ask in the  #help channel. Thanks!
