### ISSUE TITLE
Cards need unique classes

### ISSUE THREAD

**Issue by JohnONolan** [TryGhost/Ghost#8179]
Can we have our own global card class? Eg. `.koenig-card` or maybe `.kg-card` rather than `.__mobiledoc-card` ?

More importantly though, definitely need card-type classes, eg. `.kg-card-image` / `.kg-card-markdown` / `.kg-card-html` etc

**Comment by disordinary** [comment]
I started a refactor of mobiledoc-kit to allow custom classes but it turned out to be a bigger PITA than I was expecting and so I put it on hold, we can definitely insert class names at runtime though.

It is on my list to replace the existing mobiledoc classes though.
