### ISSUE TITLE
PSM position update

### ISSUE THREAD

**Issue by JohnONolan** [TryGhost/Ghost#8180]
Discussed previously but adding here to track:

Editor PSM should now push in from the right, alongside the editor, rather than overlapping it. So you can open the PSM, and keep using the editor, and then close the PSM later.

**Comment by kevinansfield** [comment]
Will the behaviour be dependent on screen size? Animating the push-in if it will reduce the editor width will likely be very janky if there's much content as there will be a ton of reflow going on.

**Comment by JohnONolan** [comment]
yeah... I guess it should still be "over" when on narrow screen. Not sure how easy/hard it is to toggle between the two?

**Comment by kirrg001** [comment]
@JohnONolan @kevinansfield 

Can we close this or label with `later` + add a reason?
Thanks 🙃
