### ISSUE TITLE
Google Page speed and ghost-url.min.js

### ISSUE THREAD

**Issue by naymaeu** [TryGhost/Ghost#8183]
Hi.

I have question how to move file:

`/shared/ghost-url.min.js`

To footer to make quicker page speed on google test. I got issue if this file block rendering and need to move to footer.

Thanks for any advice.

### Technical details:

* Ghost Version: 0.11.7
* Node Version: 6.10.0
* Database: MySQL

**Comment by ErisDS** [comment]
For questions, please use our [slack channel](https://slack.ghost.org) in future. This file is part of the Public API beta, you can remove it by disabling the beta.
