### ISSUE TITLE
Issues navigating between the new title and the editor body.

### ISSUE THREAD

**Issue by disordinary** [TryGhost/Ghost#8191]
The multi line title has bugs when navigating between the title and editor.
- [x] Tab stops not working.
- [x] ~Split title into content when enter is pressed (required to create a paragraph if a card is the first element)~
- [ ] ~Combine the first paragraph into the title if backspace is pressed in the editor.~
- [x] When you press down and are on the first character of the line in the title the cursor moves to the end of the line in the title rather than the first character in the editor.
- [ ] ~When you press right from the last character of the title or left from the first character of the editor you don't navigate from the title to the body or vice versa.~
- [x] When you press up from the editor the cursor moves to the first character of the title. The code is in there but each browser has different issues so it's commented out.

**Comment by ErisDS** [comment]
The tab key doesn't work to get me from the title to the editor.

I personally would have thought the use case for this was much, much stronger than arrow keys?

**Comment by disordinary** [comment]
I spent longer than I care to admit on 

> When you press up from the editor the cursor moves to the first character of the title. The code is in there but each browser has different issues so it's commented out.

It works fine in isolation but doesn't work in ghost-admin for some reason. The cursor is supposed to be positioned at the character that is closest to the character selected in the body when you press the "up" arrow. In chrome it just goes to the start of the title, in firefox it goes to the correct position but then you can't edit the title afterwards. Investigation needs to be done to see if it's something to do with ember / ghost-admin or mobiledoc, but it's an edge case so investigation will stop until after the first beta.

**Comment by disordinary** [comment]
I've been experimenting with this over the last day and I think functionality needs to be removed.

If you press enter the title splits into the body, and in reverse pressing backspace in the body combines the first body paragraph with the title. 

This works well, however because the title is not integrated in the editors undo queue and won't be without a large re-write of mobiledoc (which is planned in the medium term for other reasons), then the behaviour doesn't work as expected.

Pressing enter on the title to create a new paragraph in the editor is a necessary evil because the first element may be a card, however I think that it's better to just create a new empty paragraph rather than split the title. This behaviour may be a little odd but not as odd as having a broken undo system.

This means that this issue is now simply about navigation between the title and body with either the up and down keys (I don't think left and right should be used so that we clearly have different fields), the enter key, and the tab key.
