### ISSUE TITLE
HTML errors from API requests display HTML in the alert

### ISSUE THREAD

**Issue by kevinansfield** [TryGhost/Ghost#8203]
### Issue Summary

When an API request fails and a service between the client and the Ghost service (e.g. a proxy/CDN returning a timeout screen) returns HTML, that content gets displayed in the error alert rather than a sensible message.

![48d27740-0260-11e7-916c-5cc4d8f79093](https://cloud.githubusercontent.com/assets/415/24153684/0e2209c4-0e47-11e7-8b15-9a67e2cf5fef.png)

### Steps to Reproduce

T.B.D

### Technical details:

* Ghost Version: LTS (possibly master, needs replication)

**Comment by cobbspur** [comment]
FYI: Ran into a similar issue today when trying to perform a password reset from email (LTS).
