### ISSUE TITLE
Mac 10.12/node 6.10/ ghost master init fail 

### ISSUE THREAD

**Issue by 8dspaces** [TryGhost/Ghost#8231]
i tried to use ghost as the step listed in readme page, but it fails in step2, could you help check it? 

1. git clone git@github.com:TryGhost/Ghost.git ghost
2. npm run init  --->**get issue (details list below)**
3. knex-migrator init 
4. grunt dev

### Technical details:

* Ghost Version: ghost@1.0.0-alpha.17
* Node Version: node v6.10.1
* Browser/OS: 
* Database: 

```
npm ERR! Darwin 16.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/lib/node_modules/cnpm/node_modules/.bin/npm" "--userconfig=/Users/xxx/.cnpmrc" "--disturl=https://npm.taobao.org/mirrors/node" "--registry=https://registry.npm.taobao.org" "run" "init"
npm ERR! node v6.10.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! ghost@1.0.0-alpha.17 init: `npm install -g knex-migrator ember-cli grunt-cli && npm install && grunt init`
npm ERR! Exit status 3
npm ERR!
npm ERR! Failed at the ghost@1.0.0-alpha.17 init script 'npm install -g knex-migrator ember-cli grunt-cli && npm install && grunt init'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ghost package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm install -g knex-migrator ember-cli grunt-cli && npm install && grunt init
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ghost
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ghost
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/xxx/Downloads/ghost/npm-debug.log
```

**Comment by kevinansfield** [comment]
@8dspaces sorry to hear the install has failed for you. Are you able to put the contents of `/Users/xxx/Downloads/ghost/npm-debug.log` in a Gist or similar and link it here? Unfortunately the output that you've provided above doesn't include any information about what's failed

**Comment by kirrg001** [comment]
@8dspaces Also, could you please re-run `npm run init` and share all the output you are getting?
Thanks so much 👍

**Comment by 8dspaces** [comment]
Thanks for your checking, i added the information i got in [Gist](https://gist.github.com/8dspaces/9b5f6961bcaa3d1a9f07b1200e3f85ac)

**Comment by kevinansfield** [comment]
@8dspaces thanks. The error seems to be saying that your `Ghost-master` directory isn't a git repository - do you remember what commands you used to download ghost?

**Comment by 8dspaces** [comment]
i tried both clone and download directly,both get error, the debug log from a cloned repo list in [gist](https://gist.github.com/8dspaces/e0b0ff55c4af72ea69ce5ad86f8f8c1e)

test step: 

1. git clone git@github.com:TryGhost/Ghost.git ghost
2. (cd to ghost folder)npm run init

**Comment by kevinansfield** [comment]
@8dspaces your latest gist has a different errors in it:

`fatal: unable to access 'https://github.com/TryGhost/Casper.git/': Proxy CONNECT aborted`
`fatal: unable to access 'https://github.com/TryGhost/Ghost-Admin.git/': Proxy CONNECT aborted`

This suggests that you are behind some a proxy/firewall of some description that is blocking access to GitHub via https, is there anything you know about that may be causing that error?

**Comment by 8dspaces** [comment]
Sorry,  it's my fault, i set http.proxy for my git which cause the fail 
after remove the proxy setting, it works now, many thanks for your help~
