### ISSUE TITLE
Project website element spacing on mobile

### ISSUE THREAD

**Issue by carlosvigil** [TryGhost/Ghost#8242]
### Issue Summary

Certain content is touching the edges of the screen or the navigation bar 

### Steps to Reproduce

1. Go to https://ghost.org/
2. Tap on "Find out" https://ghost.org/features/

The spacing triggers my feelings. 

### Technical details:

* Ghost Version: \-
* Node Version: \-
* Browser/OS: mobile safari, iOS 10.3, SE (US)
* Database: \-

### Screenshots
![img_0498](https://cloud.githubusercontent.com/assets/18217279/24520919/2afa1f24-1558-11e7-9233-efd7405c1620.PNG)
![img_0499](https://cloud.githubusercontent.com/assets/18217279/24520920/2b11dec0-1558-11e7-9493-d53bdc7dc911.PNG)
![img_0500](https://cloud.githubusercontent.com/assets/18217279/24521018/9031d4f4-1558-11e7-8f50-a0043d68181c.PNG)

**Comment by kevinansfield** [comment]
Hey @carlosvigil, thanks for reporting! 😄 In this case we're aware of the mobile issues and are tracking them internally, if you happen to notice any other broken functionality we're always welcome to bug reports 🐛
