### ISSUE TITLE
Themes: get helper, querying by slug not working

### ISSUE THREAD

**Issue by thorsten-panknin** [TryGhost/Ghost#8245]
### Issue Summary

The get helper doesn't seem to work with the find-by-slug example from the docs.

`{{#get "posts" slug="welcome-to-ghost"}} {{#post}} <h2><a href="{{slug}}">{{title}}</a></h2> <div class="post-content"> {{content}} </div> {{/post}} {{/get}}`

### Steps to Reproduce

1. Enable the public API
2. Open index.hbs and paste the find-by-slug example from the docs
3. Edit the slug to match a published post
4. Restart the Ghost service
5. Reload browser page

Nothing is output. I tried the tag cloud example from the docs which worked fine.

### Technical details:

* Ghost Version: 0.11.7, self-hosted
* Node Version: 4.7.3
* Browser/OS: Firefox 52 on Android
* Database: SQLite

**Comment by kirrg001** [comment]
Hey @thorsten-panknin 👋

This doesn't work for me neither. Sorry for trouble.

A workaround for you would be to use the following syntax:
```
{{#get "posts" slug="welcome-to-ghost"}}
  {{#foreach posts}}
    <h2><a href="{{slug}}">{{title}}</a></h2>
  {{/foreach}}
{{/get}}
```

There is no problem with the result of the api response, the post is there, just the `#post` notation does not work. The `#get` result does not contain a post attribute. I will keep the issue open, will figure out why.

**Comment by ErisDS** [comment]
As I put in Slack, I did a quick investigation and am pretty baffled. This has NEVER worked.

It seems I confused myself. Section 4.1 of this issue: https://github.com/TryGhost/Ghost/issues/5993 explains the problem correctly. The documentation is totally not correct :disappointed:

If you use a blockParam like `as |post|` it would work:

```
{{#get "posts" slug="welcome-to-ghost" as |post|}} 
{{#post}}
   <h2><a href="{{slug}}">{{title}}</a></h2> 
   <div class="post-content"> {{content}} </div>
{{/post}} 
{{/get}}
```

Although it does switch between doing either a read or browse request as the docs suggest, the response format is identical. Both return an array, even though the read request only returns a single item. 

There is no flattening or extra handling, so unless you use a block param as described above, you would need to use `{{#foreach}}` unlike what the docs say.

I am absolutely not sure how I managed to confuse myself here, but this is effectively an error in the documentation - all responses from the get helper are entirely consistent so the documentation is just confusing things! 

Gonna count this as a docs bug & fix the docs to say that all results are the same.

**Comment by thorsten-panknin** [comment]
@kirrg001 Thanks, the workaround works fine. 

@ErisDS Thanks for your efforts as well.

**Comment by Dreyfuzz** [comment]
Same problem with querying by id in the documentation. Should be updated.

**Comment by kirrg001** [comment]
I have updated http://themes.ghost.org/docs/get and http://themes.ghost.org/v0.11.9/docs/get 👍 

Thanks again for the report 😎
