### ISSUE TITLE
editor - images in markdown cards

### ISSUE THREAD

**Issue by kevinansfield** [TryGhost/Ghost#8248]
### Issue Summary

When using the markdown card there's no way to upload images whilst editing and after switching to the preview an image upload form is shown but it doesn't do anything.

### Steps to Reproduce

1. Add a markdown card to a post
2. In the markdown content add empty image code `![]()` (note there's no way to upload at this point)
3. Click the `Save` button for the markdown card
4. The empty image code is now converted to a file upload form but uploading doesn't work/save

![markdown images](https://cloud.githubusercontent.com/assets/415/24613604/aa3d3dd6-1880-11e7-9143-a54660d3a9b2.gif)

**Comment by kevinansfield** [comment]
Do we have any plans to make images uploadable in markdown cards? Considering the migration path will likely involve putting existing post markdown into a markdown card I expect it's something that will come up pretty often?

**Comment by disordinary** [comment]
Thanks @kevinansfield, you can currently upload an image by dragging and dropping it into the markdown, similar to how github works. We also have plans to extend the toolbars for each card but not for the first beta.

**Comment by JohnONolan** [comment]
> upload an image by dragging and dropping it into the markdown

this is more than enough for markdown cards imo 👍

**Comment by disordinary** [comment]
- [ ] Remove useless upload form in preview.
- [ ] Indicate to the user on drag that the markdown card is a drop target.
- [ ] Fix the drop problems in Firefox.
- [ ] Add an image upload tool into the markdown card toolbar (probably after the first beta).

**Comment by disordinary** [comment]
I have a feeling that the drop issue in firefox is because the editor also accepts image drops and the event is being caught at the root rather than the drop target that we want.

**Comment by ErisDS** [comment]
Closing in favour of https://github.com/TryGhost/Ghost/issues/8314
