### ISSUE TITLE
some bugs with showdown-ghost

### ISSUE THREAD

**Issue by imzhengfei** [TryGhost/Ghost#8253]
### Issue Summary

some bugs with **showdown-ghost**:

* **`>`**:

">" always compiled to the quote, even I want to show ">=", it was compiled to

> =

I think the ">" may be compiled only when a space behind it, like "> "

* **`-` in table syntax**

Showdown supports table syntax, but Ghost didnot turn on. So I added the "table" support by myself, but came across a bug:

My code:

```html
| a | a |
| ----- | ----- |
| - | a |
```

I want to show:

| a | a |
| ----- | ----- |
| - | a |

But ghost show:

| a | a |
| ----- | ----- |
| · | a |

"-" was compiled to list item.

### Technical details:

* Ghost Version: 0.11.7
* Node Version: 4.x
* Browser/OS: chrome/56
* Database: sqlite3

**Comment by kirrg001** [comment]
@imzhengfei Thanks for your report 👍

**Comment by ErisDS** [comment]
Re the first issue with blockquotes, this is exactly the same as how it works here on github:

>= something

As far as I am aware, there's nothing in the markdown spec saying exactly how this should work, however Ghost's showdown markdown is at least consistent with major players.

With regards to table markdown - Ghost does not support this, therefore this is not an issue we would fix. If you really need a table, the expectation is that you would use HTML, e.g. `<table>`.

**Comment by kevinansfield** [comment]
@imzhengfei the correct way to fix the quote problem in markdown is to escape the markdown characters, e.g. `\>=`

\>= this works because the quote char is escaped with a `\`
