### ISSUE TITLE
The article does not support EMOJI?

### ISSUE THREAD

**Issue by haiwx** [TryGhost/Ghost#8256]
### Technical details:

* Ghost Version: 0.11.7
* Node Version: 6.9.0
* Browser/OS: all
* Database: mysql

Will support emoji ? I really hope it will.

**Comment by kirrg001** [comment]
Hey @haiwx 👋 

Full Emoji support is coming in Ghost `1.0` with `utf8mb4` encoding. 
Ghost < `1.0` suffers from an encoding bug, see #5945 and #5519. But if you set your default character set in MySQL to `latin1`, it should be possible to display Emojis. This can be done by editing your `my.cnf` (the MySQL config file).

For further questions, please swing by our [slack channel](https://slack.ghost.org), we can provide better support there. Thank you!
