### ISSUE TITLE
Error when editing pages

### ISSUE THREAD

**Issue by MonoCow** [TryGhost/Ghost#8257]
### Issue Summary
Browser: firefox
OS: CentOS
Getting a very long error string when trying to edit a page:
The errors: 
https://cummies.pro/v/EnSIUrrHim/57VP7C6sQdxbJNzIEks4F7ePIKWC4goc
https://cummies.pro/v/LQR23D819j/n0QvZpPicBCucVoA1LqsPBodXrSzB2j4
The page: https://cummies.pro/v/2XiLgI3bdw/ysW270oHOn34F6Rpei80lBnDHnFeovwK

It might have something to do with conflicting javascript with liberapay

### Steps to Reproduce

1. Enter ghost admin
2. Go to this certain page
3. Edit the page
4. Save draft/unpublish/delete
5. Get this error

I think it has something to do with conflicting javascript

### Technical details:

* Ghost Version: 0.11.6
* Node Version: v6.9.0
* Browser/OS: Firefox/Ubuntu
* Database:

**Comment by MonoCow** [comment]
I figured out it's a problem with liberapay's js. Updated to the latest ghost, same problem.
<script src="https://liberapay.com/Freech/widgets/receiving.js"></script> seems to break it. What's the best solution to this?

**Comment by kirrg001** [comment]
Hey @MonoCow 👋

Can you please swing by our [slack channel](https://ghost.org/slack/) and ask for help there? We can provide better support there than in the Github issue tracker, and if this turns out to be an actual issue with Ghost this issue can be reopened. Thanks!
