### ISSUE TITLE
Change last_login to last_seen

### ISSUE THREAD

**Issue by kirrg001** [TryGhost/Ghost#8258]
From #7432

The last_login field in the DB is used to store a timestamp whenever a new token is added and is used to show a "last seen" field:

![68747470733a2f2f7075752e73682f76383031492e706e67](https://cloud.githubusercontent.com/assets/1160712/24645326/f9a8ed60-1917-11e7-95e0-2a235c24c4b8.png)

We would like to:
- [x] rename the field to last_seen because it does not represent the last time the user physically logged in (e.g. entered their password) and is confusing
- [x] to check if this behaviour still works in a reasonable way in Ghost 1.0 with GhostAuth.

**Comment by ErisDS** [comment]
Closed by #8259
