### ISSUE TITLE
Content screen evolution

### ISSUE THREAD

**Issue by kevinansfield** [TryGhost/Ghost#8264]
(Adding this as a note to come back to at some point in the future)

Every time you visit the content screen Ghost-Admin performs a request to fetch the first page of results and starts from scratch each time - it does this to ensure that any changes by other users are made visible. This works but it causes unnecessary slow down and doesn't make use of the data we already have stored locally in memory.

I've been thinking of how to avoid this and I think I have an outline of a plan:
- [x] add an API endpoint that will return all posts that have been created/updated since a supplied timestamp (this may need an escape valve if there are too many results but that should be rare)
- [ ] update the activities table so that it can be queried for post id's that have been deleted since a supplied timestamp
- [ ] adjust Ghost-Admin to pull from the Ember Data store and use the new API endpoint to refresh in the background - this would allow the content screen to be displayed immediately, we could add a loading indicator somewhere to indicate that the display may change once the loading is finished
- [ ] Ghost-Admin would keep track of the last page requested for each combination of filters so that infinite scroll is still possible
- [ ] make use of [vertical-collection](https://github.com/html-next/vertical-collection) so that we're only rendering what's on the screen to avoid the rendering issues that would be present if we tried to render all of the posts that are stored in memory

If we can adopt this practice across the app (use in-memory data, refresh in the background) I think we'd be better utilising the framework that we're building on top of and get a more app-like experience, especially on slower connections. It would also go some way to working around the lack of real-time push data from the server which we've previously cited as being a reason for the loading screen refresh every time a new screen is accessed - if we can handle the background reloads in this way then it's laying the groundwork for when real-time push updates are available.

**Comment by ErisDS** [comment]
> Add an API endpoint that will return all posts that have been created/updated since a supplied timestamp (this may need an escape valve if there are too many results but that should be rare)

It's totally possible to do date filtering on the posts API, e.g. `posts?filter=updated_at:>'2017-06-03 00:00:00'`. As far as I know, the date needs to be in ISO8601 format. I personally have tested 2017-06-03 00:00:00' and '2017-06-03T00:00:00', both worked.

Does this help?

**Comment by kirrg001** [comment]
> Adding this as a note to come back to at some point in the future

@kevinansfield Is that something you would like to work on in the **near** future? Otherwise we could keep the later label and close this with a little note?

**Comment by kevinansfield** [comment]
Yes, this is on my radar at the moment to be looked at shortly.

**Comment by kevinansfield** [comment]
After a brief investigation it doesn't look like this will be quite as simple as it first seems:

1. We're using `ember-infinity` for infinite loading but that uses `store.query` under the hood - Ember Data currently does no caching for query calls because the server is the source-of-truth for what gets returned and in what order for queries
2. We'd need to implement our own cursor based pagination using the `filter` param but we'll still run into the same `store.query` issue as above
3. We need our own cache system, this could be as simple as storing a list of IDs for each set of query params along with min/max `updated_at` values for pagination and refresh. Main issue will be when a post that's in the cache gets updated - where do we then put it in the list? We'd need to ensure the client implements the same ordering algorithm as the server

**Comment by ErisDS** [comment]
Suggest this is closed as it's now almost 2 years old.

**Comment by kevinansfield** [comment]
@JohnONolan asked me about this just before the christmas break. It sounds like this is still desired but it needs prioritising if so.

**Comment by JohnONolan** [comment]
I think this should be broken up into smaller individual issues, then close this one and properly prioritise the new ones. The overall goal is definitely still very much desired

**Comment by kevinansfield** [comment]
Not stale

**Comment by JohnONolan** [comment]
Not stale, but @kevinansfield maybe we should break this into a few smaller issues that are more realistic to be picked up.
