### ISSUE TITLE
[alpha.18] Admin dropdown menu links persist

### ISSUE THREAD

**Issue by PaszaVonPomiot** [TryGhost/Ghost#8269]
### Issue Summary

Admin drop-down menu disappears but links are still clickable. It should not be possible to click menu links when menu is closed.

### Steps to Reproduce

1. Install clean ghost alpha.18
2. Log in with OAuth to admin panel
3. Click to open admin drop down menu
4. Click again to close the menu
5. Move your cursor near right side of search box to see hyperlink

### Technical details:

Ghost Version: alpha.18
ghost-cli Version: 1.0.0-alpha.16
Node Version: v6.10.0
OS: Debian 3.16.39-1+deb8u1
Database: MariaDB 10.0.29
Browser: Comodo Dragon & Firefox

### Screenshots

Opening menu for the first time:
![image](https://cloud.githubusercontent.com/assets/5560454/24673872/fcb5c00c-1979-11e7-9ac4-8271056eea74.png)

On following screenshot cursor indicates that there is a link which works after clicking:
![image](https://cloud.githubusercontent.com/assets/5560454/24673973/46bb938e-197a-11e7-974a-5eb8898b8c78.png)

### And...
Thank you so much for your dedication!

**Comment by kevinansfield** [comment]
@PaszaVonPomiot I'm not able to reproduce this in Chrome or Firefox. Are you able to provide a screencap? That might highlight what the problem is a little better. We typically use [LICEcap](http://www.cockos.com/licecap/) although I'm not sure if there is anything similar available for Linux.

**Comment by kirrg001** [comment]
If i open and close the menu and hover with my mouse above the search box, i can open the menu from there.

**Comment by kevinansfield** [comment]
I've been able to see that behaviour once now but I can't replicate consistently. I have an idea for a fix anyway so I'll give that a go.
