### ISSUE TITLE
[alpha.18] Top area of editor disabled by header

### ISSUE THREAD

**Issue by PaszaVonPomiot** [TryGhost/Ghost#8271]
### Issue Summary

When writing a post and you try to select text that is on top of page it won't be possible. It will confuse bloggers.

### Steps to Reproduce
 
1. Create new post
2. Try to select post text that is in top area of editor

### Technical details:

Ghost Version: alpha.18
ghost-cli Version: 1.0.0-alpha.16
Node Version: v6.10.0
OS: Debian 3.16.39-1+deb8u1
Database: MariaDB 10.0.29
Browser: Comodo Dragon

### Screenshot

![image](https://cloud.githubusercontent.com/assets/5560454/24679541/bc362256-198d-11e7-8c44-630c5dbc05e0.png)

Thanks!

**Comment by disordinary** [comment]
@kevinansfield or @JohnONolan any ideas? We want the UI to sit above the editor but the editor to sit above that div which is holding them.

**Comment by kevinansfield** [comment]
There is also a visual problem at smaller window sizes...

![screen shot 2017-04-06 at 14 15 30](https://cloud.githubusercontent.com/assets/415/24755961/fb6d7086-1ad3-11e7-9ffb-f50346873960.png)

**Comment by disordinary** [comment]
It gets worse the smaller the screen gets.
![image](https://cloud.githubusercontent.com/assets/73181/24898756/0de83026-1ef2-11e7-88c2-b88464b65200.png)

**Comment by kevinansfield** [comment]
Closed via https://github.com/TryGhost/Ghost-Admin/pull/653. If there are still issues at mobile sizes in particular browsers they should have their own issues opened.
