### ISSUE TITLE
Post API: formats & new plaintext field

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#8275]
In certain cases, we need to have a plain text version of a post. This means adding a new field to the DB of `plaintext` and converting the HTML on save. 

As an additional consideration, we added the amp field (which does much the same thing) without really thinking about the additional overhead to the API - the AMP html is only useful in the case that we are rendering AMP. Equally, only the editor will need the mobiledoc content, and a blog really only needs HTML. 

This leads to the idea of adding a `?formats=html,plaintext` parameter to the API. The default would be `html`, but html, amp, mobiledoc & plaintext would all be available. 

The tasks are as follows:

Required for beta:

- [x] Add a new `plaintext` field to the posts table
- [x] ~~Remove the `markdown` field?~~ see #8479 
- [x] Auto-fill `plaintext` with a full plaintext version of the post on save
- [x] Add `?formats` to the API & return just html by default
- [x] editor requests mobiledoc/plaintext
- [ ] rename amp field to comment_id (tracked here https://github.com/TryGhost/Team/issues/42)

Post-beta improvements
- [ ] Auto-fill `amp` on save as well! (This is not done yet!)
- [ ] Update the amp code to request AMP specifically

**Comment by ErisDS** [comment]
With regard to the markdown field, I've changed my thinking a bit, based on some future concerns.

I think we should keep the field.

Essentially, Ghost will support two "base" formats: markdown and mobiledoc, and 3 output formats: html, plaintext and amp.

The new editor will only handle the mobiledoc field. Therefore, if you use the new editor, your base format will be "mobiledoc" even if you only use the markdown card. Any post created or updated using the new editor will store mobiledoc + the output formats.

However, if you wish to use the API (which currently has no "proper" write access, but we want to change this), you will be able to choose to write either markdown or mobiledoc. This will allow people to use their own desktop editors. 

If you push markdown to the API, Ghost will convert to HTML, and then to plaintext and AMP.

If you then try to open that post in the editor, it would be blank. Any content written here would, by default, override the markdown content, therefore we probably want to disable the editor in this case (not urgent until we have API write access).

Essentially mobiledoc > markdown. If there is mobiledoc content available, Ghost will default to using that as the base format and ignore markdown.

Also, from this perspective, HTML is a transitional format, and also can act as a base format. E.g. a user could write HTML directly to the API, and in that case we would still need to generate plaintext and AMP from this. We will serve the HTML as-is, with no ability to edit.

Over time, we could add options to the editor to "convert" the format on the fly, so if a user wants to edit a post originally created in markdown, they could do the same thing the importer would do and convert it to a mobiledoc document. However, this is again not at all urgent until we have write access and even then is probably an edgecase.

The importer should, IMO convert markdown posts to mobiledoc.

The remaining question is whether to remove the markdown content on import or keep it. I would suggest keeping it - this is non destructive, and we already state that mobiledoc > markdown - so the markdown will be ignored by Ghost if mobiledoc is available.

It just means the content is still there if the import needs tweaking.

@disordinary you talked about creating a lib to do the markdown -> mobiledoc conversion. Is that still on your radar?

**Comment by disordinary** [comment]
Yes, it's on my radar but I've not started it yet.

Mobiledoc-kit already has the capability to import HTML through the paste handler so this can be a good starting point for an intermediate format. 

The other option is if there isn't a mobiledoc format and the user opens it in the editor it will generate a mobiledoc with either a markdown or HTML card on the fly.

I'm guessing the write API is going to be PUT/POST with entire documents only?

**Comment by ErisDS** [comment]
>> Over time, we could add options to the editor to "convert" the format on the fly, so if a user wants to edit a post originally created in markdown, they could do the same thing the importer would do and convert it to a mobiledoc document. However, this is again not at all urgent until we have write access and even then is probably an edgecase.

> The other option is if there isn't a mobiledoc format and the user opens it in the editor it will generate a mobiledoc with either a markdown or HTML card on the fly.

The problem with doing that is it changes the user's base format, and further writes via the API to the markdown or HTML field would have no effect. Therefore I think it's confusing & very much an edge case not worth optimising for.

> I'm guessing the write API is going to be PUT/POST with entire documents only?

Yes it's the same API we already have - we need to add client-based OAuth2 flows to make it accessible.

**Comment by ErisDS** [comment]
The main thing that's still bugging me here, is whether or not we should change AMP content to be generated on post save & stored or not :/

@kirrg001 any thoughts?

**Comment by ErisDS** [comment]
@kirrg001 FYI I agree, let's rename the amp field and then close this. We can think about optimising amp later if needed.

**Comment by kirrg001** [comment]
I've added a subtask and added this issue to our project board.

**Comment by kirrg001** [comment]
> rename amp field to comment_id

This is tracked in https://github.com/TryGhost/Team/issues/42.

If we now rename the amp column to comment_id, the field would be always empty except you did an import of content to remember the old comment id. This is because the comment_id is always the post id. That is somehow weird and not really clean.

A thought. If we would import post including the ID field, we don't need to remember the old comment_id anymore. Object ID's are time and random based, i guess it's okay to import posts including the ID field. The only edge case i can think of, is importing a post twice with the same ID, but this post would get ignored.

This is just a thought or let's say, an easier and different approach. That's why i would like to tackle this in the next major and give this topic a little more attention.

> Right now if you have AMP enabled and you request the AMP format via the API, you would receive nothing. This is definitely a bug. That means, the AMP generation has to be triggered

Let's wait till it get's raised as a bug. Not critical in my opinion.

Closing.
