### ISSUE TITLE
Card unexpectedly deleted when removing empty paragraph

### ISSUE THREAD

**Issue by kevinansfield** [TryGhost/Ghost#8308]
### Steps to Reproduce

1. Add a card (i added an image) at the top of the document
2. Click in the title and press <kbd>enter</kbd> to add a new paragraph
3. Type something in the new paragraph then delete all the text
4. Pressing <kbd>backspace</kbd> or <kbd>Cmd+backspace</kbd> will now delete the empty paragraph but also the first card which I wasn't expecting

Secondary issue:
1. After the card was deleted I pressed <kbd>Cmd+Z</kbd> to get it back but it did nothing
2. Click on the editor then press <kbd>Cmd+Z</kbd> again and the lost card comes back
3. The cursor is now in the space just above the card but I'm unable to type

### Technical details:

* Ghost Version: https://github.com/TryGhost/Ghost-Admin/commit/2ed58d52538fb60af362ed468485cc1566234df1

**Comment by disordinary** [comment]
@kevinansfield 

I just tried this and it appears as though the editor is behaving as expected with the exception that when the card is deleted the cursor disappears from the editor? 

Can you confirm that the paragraph is there but just not selected?

It seems like an upstream issue, will need to investigate more.

**Comment by kevinansfield** [comment]
Screengrab with key capture to illustrate the problem - interestingly in my quick test I could replicate on the default "welcome" post but not on another post I had...

![editor-card-deletion](https://cloud.githubusercontent.com/assets/415/24915448/0c803026-1ecf-11e7-877f-e4416af40a9c.gif)

**Comment by disordinary** [comment]
I've fixed the cursor disappearing on card delete, I couldn't replicate the not being able to type issue but I hope that's fixed as well.

The cursor not-reappearing on undo seems like a mobiledoc issue, is there anything in the console?
