### ISSUE TITLE
Question about codebase

### ISSUE THREAD

**Issue by villander** [TryGhost/Ghost#8309]
Guys, how works the codebase?

It was not clear from the [wiki](https://github.com/TryGhost/Ghost/wiki/Codebase-Overview) if the desktop app reuses the web app through a modular architecture using addons or engines. Can someone please clarify?

**Comment by ErisDS** [comment]
@villander This is not the place for such questions. If you want to talk to us, come to [slack](https://ghost.org/slack). Deleting our issue template to ask a question is not going to encourage anyone to want to talk to you.

**Comment by villander** [comment]
Thanks
