### ISSUE TITLE
Editor - HTML Card doesn't launch in edit mode

### ISSUE THREAD

**Issue by disordinary** [TryGhost/Ghost#8310]
## Issue summary
When created the HTML Card doesn't launch in edit mode. This is because codemirror has an issue with the cursor when focused this way.

![codemirror add](https://cloud.githubusercontent.com/assets/73181/24958631/15570984-1fe4-11e7-898b-46ba95c71de1.gif)
 
## Steps to reproduce
1. Add an Embed card

## Expected Results
The card should be added in edit mode like the markdown card is.

![screenflick movie 6](https://cloud.githubusercontent.com/assets/73181/24958717/66f23052-1fe4-11e7-88a5-fc9e81f35c89.gif)

**Comment by kevinansfield** [comment]
I'll take a stab at this one unless you've already started @disordinary? As it's Codemirror related I'll see if I can spot anything that may help with random test failures we have with our Code Injection screen as well

**Comment by disordinary** [comment]
Sure.

And no, I haven't started it.

The issue is that if we tell codemirror to focus the cursor appears but it doesn't accept any inputs. There are quite a few bugs relating to the cursor in and around the editor but I have yet to dig deep enough to know if it's mobiledoc related or not.
