### ISSUE TITLE
[alpha.19] Unable to switch to theme when .git folder is present.

### ISSUE THREAD

**Issue by hissingpanda** [TryGhost/Ghost#8330]
### Issue Summary

Unable to switch to theme when .git folder is present in content/theme/yourtheme/ directory.

### Steps to Reproduce

1. Clone theme into the content/theme directory
2. Restart ghost site
3. Try to switch to the cloned theme in the admin menu

When removing the git folder, switching to the theme, and then re-adding the git folder a 500 error occurs on the site.

### Technical details:

* Ghost Version: Alpha-19
* Node Version: v4.5.0
* Browser/OS: Firefox
* Database: MySQL

### Screenshots
![screen shot 2017-04-13 at 14 13 21](https://cloud.githubusercontent.com/assets/7660115/25025042/88561ac6-2055-11e7-8a09-49bb8f0dd7c2.png)
![screen shot 2017-04-13 at 14 11 39](https://cloud.githubusercontent.com/assets/7660115/25025037/85efbd8c-2055-11e7-91fa-edb31059248b.png)

### Console.log
`Request was rejected due to server error
EmberError@https://dev.konkret.la/ghost/assets/vendor-c1c9bf3c958d9652097c61f83e2237f4.js:38575:19
AjaxError@https://dev.konkret.la/ghost/assets/vendor-c1c9bf3c958d9652097c61f83e2237f4.js:178696:5
ServerError@https://dev.konkret.la/ghost/assets/vendor-c1c9bf3c958d9652097c61f83e2237f4.js:178809:5
handleResponse@https://dev.konkret.la/ghost/assets/vendor-c1c9bf3c958d9652097c61f83e2237f4.js:179511:16
handleResponse@https://dev.konkret.la/ghost/assets/ghost-02f0bed201803c2dc2c17cdac9b78f8a.js:16993:20
superWrapper@https://dev.konkret.la/ghost/assets/vendor-c1c9bf3c958d9652097c61f83e2237f4.js:61523:17
_makeRequest/</hash.error@https://dev.konkret.la/ghost/assets/vendor-c1c9bf3c958d9652097c61f83e2237f4.js:179259:24
jQuery.Callbacks/fire@https://dev.konkret.la/ghost/assets/vendor-c1c9bf3c958d9652097c61f83e2237f4.js:13714:11
jQuery.Callbacks/self.fireWith@https://dev.konkret.la/ghost/assets/vendor-c1c9bf3c958d9652097c61f83e2237f4.js:13844:7
done@https://dev.konkret.la/ghost/assets/vendor-c1c9bf3c958d9652097c61f83e2237f4.js:19671:5
.send/callback/<@https://dev.konkret.la/ghost/assets/vendor-c1c9bf3c958d9652097c61f83e2237f4.js:19911:9`

**Comment by kirrg001** [comment]
Hey @hissingpanda 👋 Thanks for your report and sorry for trouble.
This is a known issue, see https://github.com/TryGhost/gscan. We are already working on a solution for the next release.

**Comment by kirrg001** [comment]
Should be fixed via https://github.com/TryGhost/Ghost/pull/8344.
