### ISSUE TITLE
Image fallbacks for `og:image` and `twitter:image`

### ISSUE THREAD

**Issue by whmii** [TryGhost/Ghost#8334]
### Issue Summary

Currently if a post does not contain a featured image, the attributes of `og:image` and `twitter:image` will not be added to `ghost_head `. This *could* be changed to fall back to the blog logo scaled to fit a [summary card](https://dev.twitter.com/cards/types/summary).

> Images for this Card support an aspect ratio of 1:1 with minimum dimensions of 144x144 or maximum of 4096x4096 pixels. Images must be less than 5MB in size. The image will be cropped to a square on all platforms. JPG, PNG, WEBP and GIF formats are supported. Only the first frame of an animated GIF will be used. SVG is not supported.

### Steps to Reproduce

Her's an example of the current behavior for a post with no featured img. https://twitter.com/WHMII/status/852627465419853824

<img width="631" alt="screen shot 2017-04-14 at 10 17 28 am" src="https://cloud.githubusercontent.com/assets/2489247/25045758/d6ced732-20fb-11e7-896e-4e8170694084.png">

And here's what it could look like.

![screen shot 2017-04-14 at 10 17 28 am](https://cloud.githubusercontent.com/assets/2489247/25045787/f662f6dc-20fb-11e7-983e-7b15de956ee4.jpg)

### Technical details:

* Ghost Version: Ghost pro v 0.11.7
* Node Version: - 
* Browser/OS: n/a 
* Database: mysql

**Comment by AileenCGN** [comment]
This issue is one idea to solve the related #7558 issue.

**Comment by whmii** [comment]
Yep, resolved. Can confirm

**Comment by whmii** [comment]
Yep, resolved. Can confirm
