### ISSUE TITLE
Firefox CSS Issues

### ISSUE THREAD

**Issue by hissingpanda** [TryGhost/Ghost#8337]
### Issue Summary

CSS in Firefox appears slightly off in various sections:

- [ ] Timezone appears outside of textbox in both Post Settings and Publish menus
- [ ] Browse icon partially hidden in labs section
- [x] Save animation text/icon layout

![timezone](https://cloud.githubusercontent.com/assets/7660115/25065470/77cddbdc-21c5-11e7-9733-166fdeb0020b.png)
![browse](https://cloud.githubusercontent.com/assets/7660115/25065472/7abb11d4-21c5-11e7-85ab-e9c9c001b692.png)
![saveanimation](https://cloud.githubusercontent.com/assets/7660115/25065473/7d557fb0-21c5-11e7-862d-e7310b0088ea.gif)

### Technical details:

* Ghost Version: Alpha-19
* Node Version :v4.5.0
* Browser/OS: Firefox/Windows 10, Firefox/Mac
* Database: MySQL

**Comment by kevinansfield** [comment]
@hissingpanda thanks! I've verified the first two issues, the save button icon issue is already fixed in `master`.
