### ISSUE TITLE
Image field naming & new img_url helper

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#8348]
This is sort of a subtask of #7432 that didn't get a decision until very late 😳 .

Having fields in the database called simply "image" presents a real challenge for further naming, extensibility and the theme API. We've been trying to figure out how to resolve it, and now we have a plan:

*  `⁠⁠⁠⁠{{@blog.logo}}` ⁠⁠⁠⁠- stays the same
*  ⁠⁠⁠⁠`{{@blog.icon}}`⁠⁠⁠⁠ - stays the same
*  `⁠⁠⁠⁠{{@blog.cover}} ⁠⁠⁠⁠ -> `⁠⁠⁠⁠{{@blog.cover_image}}`
*  `⁠⁠⁠⁠{{post.image}}` -> `{{post.feature_image}}`
*  ⁠⁠⁠⁠`{{author.image}}` -> `{{author.profile_image}}`
*  ⁠⁠⁠⁠`{{author.cover}}` -> `{{author.cover_image}}`
*  ⁠⁠⁠⁠`{{tag.image}}`⁠⁠ -> `⁠⁠⁠⁠{{tag.feature_image}}`

These changes break the theme API and so they work best if they can be done as part of Ghost 1.0. They lay the ground work for the future addition of a new `{{img}}` tag which will be part of our image manipulation feature set (which is coming post 1.0 :grin:).

For now, to cope with the new names of the fields, we also need to update our existing `{{image}}` helper. At the moment, this outputs the url for the image called "image", that's it. Two problems: 1 it's called "image" which is weird seeing as it outputs a url and 2 it can only output a very specific thing. To fix this we need to make 2 small adjustments:

1. rename it to `{{img_url}}`
2. require that the name of the image to be output be passed in as the helper context, e.g. `{{img_url feature_image}}` - this is the same as `{{date published_at}}` but with no default.

All of this together, leaves us with the following potential tasks for beta:

- [x] change the image field names in the schema.js & update tests etc
- [x] fixup the old `{{image}}` helper to be the new `{{img_url}}` helper
- [x] update internal references to these fields (meta data)
- [x] update ghost admin references to these fields 
- [x] change Casper to use the new names
- [x] adapt gscan

Post beta:
- [ ] additional theme documentation updates

**Comment by kirrg001** [comment]
I have moved the last subtask ("additional theme documentation updates") to our `1.0` documentation issue, see #7421. This issue must happen before the launch. Closing 😎
