### ISSUE TITLE
Blog setup: fetch owner by role

### ISSUE THREAD

**Issue by kirrg001** [TryGhost/Ghost#8355]
There is a little inconsistency in how we fetch the owner user on blog setup.
The inconsistency is between local password authentication and remote authentication.

https://github.com/TryGhost/Ghost/blob/master/core/server/api/authentication.js#L81
^ We fetch the owner via the role.

https://github.com/TryGhost/Ghost/blob/master/core/server/auth/auth-strategies.js#L135
^ We fetch the owner via the slug.

I think fetching the owner by role is less error prone. 
Because as soon as there is one update to the owner user, it might happen that the owner slug changes.

**Comment by ErisDS** [comment]
Closed by #8784
