### ISSUE TITLE
"Date must be in the past" error shows up in the publish menu

### ISSUE THREAD

**Issue by kirrg001** [TryGhost/Ghost#8359]
I was used to change the publish date for scheduling in the PSM. I found a little bug while playing with both menus to change the publish date.

![mustbeinthepast](https://cloud.githubusercontent.com/assets/1160712/25171022/c3555358-24ec-11e7-9570-2630b95f749f.gif)

When i add a date in the future in the PSM and then navigate to the publish menu, i am getting this "Date must be in the past" error message. I can see the same error message, even that the publish date is in the future.

Ghost: master

**Comment by kevinansfield** [comment]
The error you're seeing in the sidebar seems correct - we don't allow future dates to be set there any more, the only way to schedule is via the publish menu. 

I can't quite tell what's happening in your screen cap wrt the publish menu, are you able to demonstrate it without clicking outside to close the menu? When closing the menu everything gets reset and unfortunately at the moment the bindings will update immediate and there can be a flash of an error based on the new state before the animation finishes even though there isn't really an error. I need to see if there's a way to reset at the end of the animation.

**Comment by kirrg001** [comment]
> The error you're seeing in the sidebar seems correct - we don't allow future dates to be set there any more, the only way to schedule is via the publish menu.

yeah 👍 

> I can't quite tell what's happening in your screen cap wrt the publish menu, are you able to demonstrate it without clicking outside to close the menu

Then it won't show the error message. The error message only shows if i leave the publish menu.

>  I need to see if there's a way to reset at the end of the animation.

Yeah sounds like a good idea 👍

**Comment by markstos** [comment]
User experience here could be improved in two ways:

1. Update the blog post on scheduling posts. It's the number one SEO result for "ghost blog schedule post". It's an official Ghost publication, and it says the way to schedule a post is by setting a  future date. https://ghost.org/changelog/scheduled-posts/
2. Add a tooltip or something to the "Must be in the past" error that that clarifies: "To schedule a post, use the Publish menu."
