### ISSUE TITLE
Schedule date is not reset when closing publish menu

### ISSUE THREAD

**Issue by kevinansfield** [TryGhost/Ghost#8360]
### Issue Summary

Changes in the publish menu are supposed to be reset if it's closed without saving. For most changes this is true but if you have a scheduled post and you change the schedule time in the publish menu, that time is set on the model and not reset when it's closed leading to the next autosave unexpectedly changing the scheduled time.

### Steps to Reproduce

1. Schedule a post
2. Whilst editing the scheduled post open the publish menu and change the time in the date/time picker
3. Close the publish menu without saving (Cancel button or click outside)
4. Note that the scheduled time shown in the PSM now shows the new time you selected
5. Open the publish menu - the new time is also shown there
6. Refresh the page - the original scheduled time should now be shown

When closing the publish menu, any unsaved changes should be reset.

### Technical details:

* Ghost Version: https://github.com/TryGhost/Ghost-Admin/commit/08edc266d18ec0cf99867f96964d5c08dd20dc7d

**Comment by AileenCGN** [comment]
@kevinansfield I am not able to reproduce this. When I follow the steps above, the date is always being reset to what is was...

**Comment by kevinansfield** [comment]
Sorry if the steps weren't very clear, I've made a screencap to demonstrate...

![scheduled-date-reset](https://cloud.githubusercontent.com/assets/415/26095684/5c51e8f8-3a16-11e7-8288-a58e0544c2d0.gif)

After closing the publish menu without saving the scheduled time should be reset so that it reads 8:06 in the PSM rather than 8:20
