### ISSUE TITLE
Can't import my backup

### ISSUE THREAD

**Issue by pascalandy** [TryGhost/Ghost#8365]
### Issue Summary

Can’t import my backup.

### Steps to Reproduce

1. Export
2. Delete all content
3. Import the file
4. “Import failed” error. I see also “
Attempting to import data linked to unknown user id 2”

Screenshot: https://cl.ly/0r0n3u2u3u0S

I did this in the past and my backups were imported successfully. 

### Technical details:

* Ghost Version: 0.11.8
* Node Version: 4.8.1
* Browser/OS: Chrome Version 57.0.2987.133 (64-bit).
OSX 10.11.6
* Database: mysql 5.7
* I also have the same result in Ghost desktop 1.2.1

**Comment by pascalandy** [comment]
Katharina jumped on slack and we troubleshooted the issue. Here are our findings. Below are the highlight of our conversation:

---

**pascalandy**: I think there is a glitch with previous users than do not exist anymore.

On blog 1, there is only one user at the moment. But there were 4 previously.

So for now I decide to copy-paste everything manually on blog 2 and test how it will react if I do the same operation on blog 3 
So when re-importing the bkp on blog 2, Ghost is trying to associate posts with users than are deleted.

**kate**
There is a post

```{ id: 3,
  uuid: 'cccfa1d5-8361-43cb-9bec-47c4a3af9756',
  name: 'portfolio',
  slug: 'portfolio',
  description: 'An overview of the project I realized over the years.',
  image: 'https://raw.githubusercontent.com/firepress-org/theme-assets/master/professionnal-services/martine-nadall/images/light-sky-blurry.jpg',
  parent_id: null,
  visibility: 'public',
  meta_title: null,
  meta_description: null,
  created_at: '2017-04-02T22:36:50.000Z',
  created_by: 2,
  updated_at: '2017-04-19T17:15:39.000Z',
  updated_by: 1 }
```

Which has no author_id. Also has no status.
But if you fix this post in your json, then it should work.

Not sure why this happened. I have to investigate and see if i can reproduce this case - to ship a fix.

There are a few
`created_by:2`
`published_by: 2`

Please update them with:

`created_by:1`
`published_by: 1`

**pascalandy**
Kaboom !!
works here as well :)

**kate**
oh i am happy it works :smile:
i will care about a fix.

**Comment by kirrg001** [comment]
@pascalandy 👋 Thanks for the update!

What we have to ensure is that if a user get's deleted, we either update the related posts or we allow this when importing.

**Comment by pascalandy** [comment]
Make perfect sense! Thank you for everything :)

**Comment by kirrg001** [comment]
This error won't happen with Ghost `1.0` anymore. (see #8473)
We allow the import of unknown user id's. e.g. you import a post with `published_by:2`, but this user was deleted. The admin UI can handle unknown user id's and `published_by` or `author_id` fields can be updated. @kevinansfield Do you have any concerns?

This is still an `LTS` issue, a fix is welcome 🙃

**Comment by pascalandy** [comment]
Sounds great!

**Comment by kevinansfield** [comment]
> @kevinansfield Do you have any concerns?

None that I can think of, we may want to add some smoke tests in Ghost-Admin to ensure that the posts list and editor will load without error if the referenced user is missing.

**Comment by kirrg001** [comment]
> None that I can think of, we may want to add some smoke tests in Ghost-Admin to ensure that the posts list and editor will load without error if the referenced user is missing.

Thanks. I did a couple some smaller tests already, nothing crashed for me. Everything behaved okay.
I will assign you to #8473 later as well - so you could do some special testing regarding the UI 👍

**Comment by kirrg001** [comment]
I am going to close this issue, because we've overhauled the importer in Ghost 1.0. If you experience this problem, please migrate to 1.0 👍 😬
