### ISSUE TITLE
[Error Display] Import file with no right server upload limit

### ISSUE THREAD

**Issue by cristiandley** [TryGhost/Ghost#8370]
### Issue Summary

Having a server Nginx/Apache with no right file upload size limit and trying to import a file with more than the default allowed wont display any error. The partial of the file exist on "content/data".

### Steps to Reproduce

1. Set up nginx default conf
2. Try to import Ghost data (+5Mb).
3. No error display

Shouldnt Ghost tell at least "File corrupted" or something like that ?

### Technical details:

* Ghost Version: 0.11.7
* Node Version: 6.9.0
* Browser/OS: Chrome
* Database: MySQL
* Eyes color: Brown

**Comment by kevinansfield** [comment]
Hey @cristiandley 👋 

There should be code in place to display an error when this happens, I'm not sure why it's not showing for you. Are you able to try this again whilst you have the Network tab of Chrome's Web Inspector open (right-click on the page and click `Inspect` then click on the `Network` tab)? You should see an entry appear in red, click on that then take a screenshot. Any errors that you see in the `Console` tab will also be very useful. Thanks!

**Comment by cristiandley** [comment]
Noob Issue. The issue is Nginx... sorry the delay. Just adding the file size limit does the trick.

Thanks @kevinansfield
