### ISSUE TITLE
Triple-click results in unexpected card deletion

### ISSUE THREAD

**Issue by kevinansfield** [TryGhost/Ghost#8379]
### Issue Summary

If you triple click a paragraph to select all the text then press <kbd>Backspace</kbd> the following card will also be deleted.

### Steps to Reproduce

1. Open or edit a post
2. Ensure there is a plain paragraph with a card directly after it
3. Triple-click on the plain paragraph text to select all of it
4. Press <kbd>Backspace</kbd>
5. Note that the following card is deleted along with the selected text
6. <kbd>Cmd+Z</kbd> doesn't immediately work, you need to click on another plain text paragraph then hit it twice to get the card then the paragraph back

Rather than the unexpected deletion the card should not be deleted or when triple-clicking the card should be highlighted to show that it's part of the selection.

![triple-click-card-delete](https://cloud.githubusercontent.com/assets/415/25340936/29b102c6-28ff-11e7-9fb1-b5128c253761.gif)

### Technical details:

* Ghost Version: https://github.com/TryGhost/Ghost-Admin/commit/097f37ea02641632f194b597eea66ad96fea1853
* Browser/OS: Chrome/MacOS

**Comment by novaugust** [comment]
related: If you're in a markdown card and hit backspace the card will be deleted.

**Comment by disordinary** [comment]
The triple click delete is most likely upstream in mobiledoc.

The adding of a markdown card and deleting of it using backspace is definitely an issue with Ghost though, I'll add a seperate issue.
