### ISSUE TITLE
Notifications are not auto-clearing

### ISSUE THREAD

**Issue by kevinansfield** [TryGhost/Ghost#8391]
### Issue Summary

Notifications are supposed to automatically remove themselves after a few seconds but they are currently very sticky.

### Steps to Reproduce

1. Publish or force-save a post (<kbd>Cmd+S</kbd>)
2. Note the notification in the bottom left, wait for a while and see that it doesn't disappear

Notifications should fade after a short time unless hovered in which case the fade timer should be reset.

### Technical details:

* Ghost Version: https://github.com/TryGhost/Ghost-Admin/commit/d70ea177969e4e940a1acc6af1f3f35a3cd103a4
* Browser/OS: Chrome/MacOS

**Comment by rabbihossain** [comment]
I was unable to reproduce it. On my installation, notifications disappears as it should. If you hover over it, it becomes sticky. After you hover out it disappears after a few second.

**Comment by ErisDS** [comment]
I had this issue, but can't reproduce it now either - wonder if it's only in certain cases 😕

**Comment by AileenCGN** [comment]
I can somehow recall that I had this issue once as well. But also failing to reproduce it currently. Tested in Chrome, Safari and Firefox.

**Comment by kevinansfield** [comment]
I can't reproduce it either, I'm wondering if it was something to do with the mobiledic editor. I think it can be closed for now, we can re-open if we see the sticky notifications again.
