### ISSUE TITLE
Auto-markdown block behaviour

### ISSUE THREAD

**Issue by kevinansfield** [TryGhost/Ghost#8392]
### Issue Summary

I've run into a few issues when using the ``` triggered markdown card

1. I expected the triple-backtick to create a new markdown card immediately, instead you need to enter text between two sets of triple-backticks, using <kbd>Shift+Enter</kbd> to insert newlines
2. Typing `````` to create a markdown card inserts the six backticks into the new card (I actually did this by accident which was how I discovered you could create markdown cards after I tried the single set of ``` mentioned above and nothing happened)
3. If you already have text in a paragraph when you type `````` (with or without internal text) everything in the paragraph is lost
4. If you add a multi-line ``` ... ``` block, when the code is auto-converted to markdown the newlines are lost

### Technical details:

* Ghost Version: https://github.com/TryGhost/Ghost-Admin/commit/d70ea177969e4e940a1acc6af1f3f35a3cd103a4
* Browser/OS: Chrome/MacOS

**Comment by disordinary** [comment]
This is a tricky one, the behaviour is consistent with the rest of the markdown style shortcuts, for instance `**` doesn't create an empty strong tag, you need to write `**this is strong**`.

The way the regex works is also only on a single block, going backwards through multiple blocks is probably possible.

What does work is placing soft returns (shift+enter) in between back tick boxes, which isn't intuitive.

The solution would appear to be either:
1. Create an empty markdown card whenever \``` is entered without waiting for the closing backticks which is different from the behaviour of the other markdown style short cuts but probably isn't that big a deal.
2. When a \``` is entered go backwards through the rest of the document to try and find an earlier one. This could be confusing to the user though.

I'm leaning towards 1. Their may be an issue if the user keeps typing, and of course if they just wanted to enter \``` and not create a card.

**Comment by kevinansfield** [comment]
> This is a tricky one, the behaviour is consistent with the rest of the markdown style shortcuts, for instance ** doesn't create an empty strong tag, you need to write **this is strong**.

I think the difference is that the other markdown style shortcuts are inline rather than block level? Option 1 is definitely what I expected, that way I can type ``` then immediately start typing my code into the markdown card. Option 2 sounds like it could be confusing and/or have weird edge cases.

If it's possible to <kbd>Cmd-Z</kbd> as soon as the markdown card is added to remove the card and go back to plain ``` text I think that would be fine? I don't think triple-backticks are widely used, probably why MD chose that for their fenced code blocks 😄

**Comment by disordinary** [comment]
I'm kind of leaning towards getting rid of the \``` shortcut altogether.

I'm worried if there is a delay in inserting a card into the DOM that not all keystrokes will register in the card.

The `Ctrl+Z` functionality won't work as is because the focus will be on the textarea within the card. We'd have to manually trap that key combination (within a certain time frame or while the markdown card is empty) and then manually force the editor to undo. Probably not a big deal but is it worth it?
