### ISSUE TITLE
Cards at bottom of editor make adding new content tricky

### ISSUE THREAD

**Issue by kevinansfield** [TryGhost/Ghost#8398]
### Issue Summary

I had an empty paragraph at the end of a post into which I dropped an image file - the image card was created ok but there is no new paragraph underneath and no way to use cursor navigation to get a cursor under the image card to continue writing.

### Steps to Reproduce

1. Use <kbd>Enter</kbd> to add a blank paragraph at the bottom of the editor
2. Drag an image file onto the editor to upload & create an image card
3. Note that <kbd>↓</kbd> or <kbd>→</kbd> will not get you a cursor to continue writing but instead jump the cursor to the title input.

_Edit:_ I eventually found that if you got a hard-selection on the bottom image card by clicking or using the keyboard cursor navigation then press <kbd>Enter</kbd> a new paragraph is added underneath which works but wasn't particularly intuitive.

### Technical details:

* Ghost Version: https://github.com/TryGhost/Ghost-Admin/commit/d70ea177969e4e940a1acc6af1f3f35a3cd103a4
* Browser/OS: Chrome/MacOS

**Comment by disordinary** [comment]
When adding a card with the markdown shortcuts the card isn't added with a following paragraph either.
