### ISSUE TITLE
Nested lists don't work

### ISSUE THREAD

**Issue by kevinansfield** [TryGhost/Ghost#8402]
### Issue Summary

After creating a list, I expected <kbd>Tab</kbd> to further indent list items but it only adds a tab to the list item text.

Pasting a nested list doesn't flatten the list but collapses the text...

<img width="178" alt="screen shot 2017-04-26 at 10 28 24" src="https://cloud.githubusercontent.com/assets/415/25427638/1ffbba9c-2a6b-11e7-91c0-8f314c275db8.png">

becomes: 
<img width="221" alt="screen shot 2017-04-26 at 10 28 31" src="https://cloud.githubusercontent.com/assets/415/25427671/33c6d12e-2a6b-11e7-95f3-d1799a038609.png">

### Workaround:
Add the nested list is via a markdown card.

### Related mobiledoc issues:
- https://github.com/bustlelabs/mobiledoc-kit/issues/482
- https://github.com/bustlelabs/mobiledoc-kit/issues/189

**Comment by disordinary** [comment]
There's a chance that nested lists will also be included in the 1.0 release of mobiledoc as well.

**Comment by vCillusion** [comment]
I am not able to use Nested lists in latest Casper 2.3.0. Is it fixed

**Comment by axle07** [comment]
[It sounds like this should work in mobiledoc if the list is child of a list-item](https://github.com/bustle/mobiledoc-kit/issues/189 ), but that is not the behavior I'm seeing in Koenig.
