### ISSUE TITLE
Spinner invisible

### ISSUE THREAD

**Issue by sebgie** [TryGhost/Ghost#8412]
### Issue Summary

The spinner in Labs -> Test Email configuration is invisible because it's white on white.

### Steps to Reproduce

1. Go to Labs
2. Test Email configuration
3. Press send

![settings_-_labs_-_blog-test](https://cloud.githubusercontent.com/assets/539213/25438723/a68d3ef8-2a9a-11e7-941d-2502eb1ea57d.png)

### Technical details:

* Ghost Version: Alpha.20
* Node Version:
* Browser/OS: Chrome 57.0.2987.133 (64-bit)
* Database:

**Comment by JohnONolan** [comment]
This is fixed
