### ISSUE TITLE
"add card button" makes me nervous

### ISSUE THREAD

**Issue by sebgie** [TryGhost/Ghost#8413]
### Issue Summary

Probably OCD

- Chrome:
![editor_-_blog-test](https://cloud.githubusercontent.com/assets/539213/25440655/5e1d3564-2aa0-11e7-83c6-1c19e083b700.png)

- Safari:
![editor_-_blog-test](https://cloud.githubusercontent.com/assets/539213/25440734/97b46414-2aa0-11e7-86a1-cbbe7924ff83.png)

### Technical details:

* Ghost Version: Alpha.20
* Node Version:
* Browser/OS: Chrome 57, Safari 10.1
* Database:

**Comment by PaszaVonPomiot** [comment]
Firefox is ok.

**Comment by JohnONolan** [comment]
This is going to be revisited from the ground up - don't need to track
