### ISSUE TITLE
Can't save navigation link changes

### ISSUE THREAD

**Issue by gomesphoto** [TryGhost/Ghost#8414]
### Issue Summary

Can't save navigation changes. Ghost api settings returns 404. "Problem finding setting: cover_image"

`
  ERROR [2017-04-26 14:39:38] "PUT /ghost/api/v0.1/settings/" 404 59ms
  NAME: NotFoundError
  MESSAGE: Problem finding setting: cover_image
`

### Steps to Reproduce

1. Go to Design tag
2. Make changes or add navigation tabs
3. Save changes
4. Error message shown "Problem finding setting: cover_image"

### Technical details:

* Ghost Version: 1.0.0-alpha20
* Node Version: 7.9.0
* Browser/OS:  Chrome 57 / macOS 10.12.4
* Database: development (sqlite)

**Comment by kirrg001** [comment]
Hey @gomesphoto 😎

Thanks for testing the alpha version 👋

`1.0.0-alpha.20` contains breaking database changes. We have renamed a couple of schema properties. If you reset your database, it should work again. If you have any further questions, come say hello on [slack](https://slack.ghost.org).

**Comment by skyFi** [comment]
I can't save navigation link change.

* when i changed link:
![image](https://user-images.githubusercontent.com/12740180/52038462-5ccb4880-256d-11e9-8408-e67f392221f6.png)

* it's request data:
![image](https://user-images.githubusercontent.com/12740180/52038387-0f4edb80-256d-11e9-9413-50e47b15af39.png)

**No Error**

Run `ghost version`, got this:
```
Ghost-CLI version: 1.9.9
Ghost version: 2.13.1
```

**Comment by skyFi** [comment]
Should I create a new issue ?

**Comment by kirrg001** [comment]
I cannot reproduce.

**Comment by skyFi** [comment]
![image](https://user-images.githubusercontent.com/12740180/52042510-59898a00-2578-11e9-840d-928fc356318a.png)

BaseUrl is `http://fangyongle.online.` (has dot);

if i change domain to `http://fangyongle.online`(no dot) , it can be changed.

**Comment by kevinansfield** [comment]
@skyFi yes, it looks like the trailing dot in your URL is the problem as it's not a valid URL. Please update the `url` value in your config. If you need further support please use [the forum](https://forum.ghost.org), thanks! 🙂
