### ISSUE TITLE
Ghost 1.0 development installation

### ISSUE THREAD

**Issue by juan-g** [TryGhost/Ghost#8421]
About the Ghost 1.0 (currently alpha) development installation instructions at: 

Working with Ghost - How to install & develop with Ghost 1.0 (Wiki)
https://github.com/TryGhost/Ghost/wiki/Working-with-Ghost

they are already useful, but I think could be improved and completed, as detailed below.

Currently they are, in summary:
```
git clone git@github.com:TryGhost/Ghost.git ghost
cd ghost
npm run init
grunt dev
```
Later it's also mentioned:
```
knex-migrator init
```
etc.

Some details to improve, in my opinion:
1. It should be mentioned that the Yarn dependency manager must be installed before running `npm run init`.
2. A workaround for a current [Yarn bug](https://github.com/yarnpkg/yarn/issues/648#issuecomment-294160808) would be useful to mention. That bug can give: `error We don't have permissions to touch the file "/usr/bin/ember"`. What worked for me was to run: `export PATH="$PATH:$HOME/.config/yarn/global/node_modules/.bin"` after installing Yarn. This path addition works at least for Linux and Mac.
3. It would be useful to mention that `knex-migrator init` should be run during the installation, to init the database before starting Ghost with `grunt dev`.
4. A better and more common Git workflow is mentioned at [Git workflow · TryGhost/Ghost Wiki](https://github.com/TryGhost/Ghost/wiki/Git-workflow), and I think it should be also used in the Ghost 1.0 dev install instructions: _"Each developer should fork the core Ghost repo into a repo of their own and clone this as their local repo. Remember to add the main repo as a remote"_ That is, cloning locally our fork on GitHub (for pull requests, etc.) as remote origin, and setting the official Ghost repo as remote upstream.

After these changes, the Ghost 1.0 dev install works well.

**Comment by juan-g** [comment]
About #3, I've just seen that in other Ghost 1.0-alpha dev install instructions on the [README.md](https://github.com/TryGhost/Ghost/blob/master/README.md), `knex-migrator init` appears already correctly before `grunt dev`, as in my opinion should be also on the Wiki. The other details are similar, they could also be completed.

**Comment by cobbspur** [comment]
Thanks for the suggestions, we are moving all development and self-hosting docs to docs.ghost.org rather than using the wiki as this has become rather confusing. This is still in progress so let us know if you notice anything else missing :)
