### ISSUE TITLE
Adding a Tag to Post with a null `updated_at` will fail

### ISSUE THREAD

**Issue by jcmorrow** [TryGhost/Ghost#8426]
### Issue Summary

 If you attempt to add a tag to a post with an `updated_at` of `null` then [this line](https://github.com/TryGhost/Ghost/blob/master/core/server/models/plugins/collision.js#L57) will return `true` because `serverUpdatedAt` will be `NaN` and the user will get the error message:

> Saving failed! Someone else is editing this post.

### Steps to Reproduce

- Import a post (or manually set its `updated_at` to `null` in the DB)
- Add a tag to that post via the admin edit UI and hit `Update Post`
- You should see the error message `Saving failed! Someone else is editing this post.`

### Technical details:

* Ghost Version: 0.11.8
* Node Version: 4.1.2 (I know, I know)
* Browser/OS: MacOSX 10.12.4 (16E195)
* Database: SQLite3 & MySQL (I didn't try Postgres)

**Comment by kirrg001** [comment]
@jcmorrow Thanks for your report 🙃
