### ISSUE TITLE
Author & Pub Date in Article tag in Casper Theme Causes Strange Search Results

### ISSUE THREAD

**Issue by mattferderer** [TryGhost/Ghost#8427]
### Issue Summary

The Casper theme (which many other themes use as a starter) includes the title of the post and the publish date within the article tag. It appears that this causes issues in Bing & Google's search results. See photo:
![capture](https://cloud.githubusercontent.com/assets/2480667/25545250/8c776590-2c23-11e7-875e-702f140bc3b6.JPG)

In my theme, which was based on Casper, it seems that by removing these out of the article tag it fixes the issue. Since they're at the top of the article tag, I just made a separate div tag above the article tag for that info to live. 

### Technical details:

* Ghost Version: 0.11.8

**Comment by kirrg001** [comment]
Hey @mattferderer 

Thanks for your report. Would you mind opening up this issue on the https://github.com/TryGhost/Casper repository? Thanks so much!
