### ISSUE TITLE
please add code highlight support

### ISSUE THREAD

**Issue by cloverzrg** [TryGhost/Ghost#8429]
i am a programmer

**Comment by kevinansfield** [comment]
Hi @cloverzrg, this is not a good use of Github - the default message that you didn't read and then deleted has instructions about what constitutes a useful bug report and where you should be asking for support or opening feature requests, please take the time to a read project's community guidelines or the issue template before opening issues! 😉 

In this case a quick search would have shown that syntax highlighting is readily available - https://www.google.com/search?q=ghost+syntax+highlighting.

If you need help integrating syntax highlighting into your theme swing by our [Slack channel](https://slack.ghost.org) where there's a great support community.

If you want to open feature requests there's https://ideas.ghost.org.

**Comment by acburdine** [comment]
Hey @cloverzrg, thanks for dropping by!

Going to close this as we use Github issues to track bugs and ongoing work with Ghost itself, not feature requests. If you wish to submit a feature request, please use our [wishlist](http://ideas.ghost.org).

It is fairly easy to add code highlighting to posts in your theme using something like Prism ([here's a post explaining how to add it](http://blog.weareevermore.com/add-syntax-highlighting-to-ghost-with-prism-js/)).

**Comment by cloverzrg** [comment]
thank you
