### ISSUE TITLE
Bug: Invite email template not sanitising/escaping values

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#8436]
If your blog title contains a `"` you will not be able to send an invite email.

### Steps to Reproduce

1. Add a `"` character to the title of your blog
2. Try to send an invite, you will get an "Invite not sent, please try again" message.

In the logs you will see:

> Warning: Error sending email: SenderError: Mail from command failed - 501 Syntax error Please check your email settings and resend the invitation.

The " character is somehow causing a syntax error when sending email.

As well as checking this case, we should ensure that the fix is applied to all values passed to all email templates.

### Technical details:

* Ghost Version: 0.11.8
* Node Version: 4

**Comment by kirrg001** [comment]
Note: The error only happens because the blog title is used for the `from` field.
If you pass any quotes for the email template e.g. `invitedByName: katharina"`, it doesn't matter.

**Comment by kirrg001** [comment]
Closed via #8453
