### ISSUE TITLE
Upgrade notice banner appears multiple times

### ISSUE THREAD

**Issue by BlueHatbRit** [TryGhost/Ghost#8441]
### Issue Summary

Not a huge bug but I've noticed when I slip behind by a few versions on Ghost it'll create a new banner for each newer version release as shown below.

![screenshot](https://i.gyazo.com/f5fdc0576ea6bb314553c4688287a2ff.png)

### Steps to Reproduce

1. Install Ghost 0.11.5 or earlier.
2. Open the publishing console as a site owner.
3. Observe multiple upgrade banners.

It would be really great if a notice saying something like:

> Ghost 0.11.8 is available! Hot Damn. Click here to upgrade from {{currentVersion}}

This way a user can easily see how out of date they are, and if they've slipped behind by multiple versions they can easily go back and read the release notes for each version they've missed. I might be an outlier with this issue but it's one I've noticed a couple of times as I don't tend upgrade for each release simply due to time.

**Comment by acburdine** [comment]
Can confirm, although it only seems to have happened since 0.11.7? I see 0.11.7 and 0.11.8 on my blog as well (which is currently on 0.11.4)

**Comment by BlueHatbRit** [comment]
I was going to take a dive into but I'm bogged down with uni work right now. If the issue is still unresolved in a few weeks then I'll take a look into it and see if I can PR a fix for it.

**Comment by kirrg001** [comment]
I can't reproduce 🤔

**Comment by BlueHatbRit** [comment]
@kirrg001 I'll check I got my current ghost version correct and get back to you.

**Comment by BlueHatbRit** [comment]
@kirrg001 Huh interesting, it's now changed and is only showing Ghost 0.11.8. It was showing both versions for a good few weeks when I took the screenshot. I guess it's all good now though if @acburdine can confirm?

**Comment by acburdine** [comment]
Yup can confirm as well that it's resolved 👍

**Comment by BlueHatbRit** [comment]
Just wanted to re-activate this, I've not upgraded at all (though I will be today) and I've got several banners once more.

Here's a new screenshot:

![Multiple Update Banners](https://d26dzxoao6i3hh.cloudfront.net/items/0V1C2b1D0C3k2S2g2O1V/Image%202017-07-16%20at%205.03.00%20pm.png)

Before I run my update, is there any diagnostics I can grab? This may not be an issue in the most recent versions.
