### ISSUE TITLE
Duplicate content SEO

### ISSUE THREAD

**Issue by RobinHerzog** [TryGhost/Ghost#8444]
Hi guys,

This isn't a big issue. 

Did you know that tags, and author page are source of duplicate content for SEO ?

https://yoast.com/duplicate-content/

What I did on my blog is setting tags and author as no-index meta.

Think about it for ghost blog :)

**Comment by kirrg001** [comment]
Hey @RobinHerzog 👋

Thanks for your report. We use github solely for bug and issue tracking.

[We collect all ideas and feature requests](http://ideas.ghost.org/forums/285309-wishlis) from our community and we try to include the highest rated into our development cycle time by time. There are already some ideas raised regarding SEO and duplicate content detection.  

I'm going to close this issue. If you have any further questions, can you please swing by our [slack channel](https://ghost.org/slack/)? Thank you so much!
