### ISSUE TITLE
restructured text

### ISSUE THREAD

**Issue by nebulousdog** [TryGhost/Ghost#8456]
I'm currently converting from using Pelican to Ghost and a majority of my files are formatted as [restructured text](http://docutils.sourceforge.net/rst.html), would be really nice to add support. Thanks!

**Comment by kevinansfield** [comment]
Hey @nebulousdog 👋 We use GitHub solely for bug tracking and current development, if you'd like to open a feature request please see https://ideas.ghost.org. Thanks 😄
