### ISSUE TITLE
Collision detection error after a scheduled post is published

### ISSUE THREAD

**Issue by kevinansfield** [TryGhost/Ghost#8458]
### Issue Summary

Saving after a post transitions from scheduled->published results in a collision error.

### Steps to Reproduce

1. Schedule a post to be published in 2-3 mins in the editor
2. Stay on the editor screen until the post is automatically published
3. Try to save the post after making some edits
4. See an alert saying someone else is editing the post

This is happening because the client never gets the new `updated_at` from the server, it's only faking the change in post status.

Quick-fix may be to update the `updated_at` property when we "fake" the transition from scheduled->published.

![collision-error-after-publish-opt](https://cloud.githubusercontent.com/assets/415/26096873/8bbca598-3a1a-11e7-89d0-fe60c5ca3f50.gif)

### Technical details:

* Ghost Version: master

**Comment by kevinansfield** [comment]
We should also investigate why the `updated_at` property was not updated when saving - we should probably always update that if we're now checking against it on the server.

Previously it never mattered because the server would always update it and send it back to us so the client treated it as per any other property where the server was source-of-truth.

**Comment by kirrg001** [comment]
This needs investigation for LTS 👍 Added it to `0.11.9` milestone for now, so we won't forget before releasing.

**Comment by kirrg001** [comment]
As far as i can see, this was fixed for the LTS branch, but not yet for master branch. I moved this issue back to the backlog.

**Comment by ErisDS** [comment]
Is this still only fixed in LTS?!

**Comment by kevinansfield** [comment]
I don't think so, I can't replicate on master.
