### ISSUE TITLE
Word count for Chinese and Japanese

### ISSUE THREAD

**Issue by Jack-Kingdom** [TryGhost/Ghost#8467]
No space between words  in Chinese and Japanese. Word count function cannot work correctly on it.
This function will count a sentence into a word on those language.

###  Technical details:
Ghost Version: alpha.20
ghost-cli Version: 1.0.0-alpha.16
Node Version: v6.10.0
OS: Ubuntu 17.04
Database: MySQL

### Screenshot
![screenshot from 2017-05-18 20-36-13](https://cloud.githubusercontent.com/assets/10584772/26202337/ae935b84-3c09-11e7-9607-63414b4ce31f.png)

**Comment by kevinansfield** [comment]
Hey @Jack-Kingdom, thanks for reporting. I've marked this as `later` as it's relating to an editor that is no longer in use in the alphas but will hopefully be picked up again sometime after the 1.0 release.

**Comment by cliier** [comment]
The above problem has not been solved.
Ghost Version:1.0.0-rc.3
ghost-cli Version: 1.0.0-alpha.16
Node Version:v6.9.0
OS: centos 7

**Comment by AileenCGN** [comment]
Hey @cliier! Yes, it is not solved yet and that's the reason why this issue is still open.

It is also labeled with `later` which means, that we will take care of this at some point, but even later.

We highly depend on open source contributions and welcome every PR that solves this issue!

**Comment by weizeng** [comment]
1.6 close this issue?

**Comment by kevinansfield** [comment]
@weizeng no, it's not planned to be fixed by the core team but if any community members want to raise PRs to improve word count for chinese/japanese we're more than happy to accept them 😄
