### ISSUE TITLE
Ghost crashed with 'unhandled 'error' event'

### ISSUE THREAD

**Issue by ice-queen** [TryGhost/Ghost#8469]
### Issue Summary
Ghost crashed with the following error, without any warning:
![](https://i.imgur.com/8lRbrtX.png)
Restarted as normal afterwards.

### Steps to Reproduce
Unable to reproduce.

### Technical details:

* Ghost Version:0.11.2

**Comment by kirrg001** [comment]
Hey @ice-queen 👋

Thanks for your report.

Could you please share your node version?

Thanks 👋

**Comment by ice-queen** [comment]
Node version is v4.8.2

Many thanks

**Comment by kirrg001** [comment]
Could you please update to `v4.8.3` and report back?

See https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V4.md#2017-05-02-version-483-argon-maintenance-mylesborins

I can see some bug fixes related to `tls`.

**Comment by kirrg001** [comment]
@ice-queen ping 🙃

**Comment by kirrg001** [comment]
If you have any news, please come back here and let us know. I'm closing this issue for now. Thanks!
