### ISSUE TITLE
Email account details are stored in plaintext

### ISSUE THREAD

**Issue by vesnikos** [TryGhost/Ghost#8470]
### Issue Summary

I'm self-hosting ghost for a personal blog for myself and friends

Noticed that config.js stores the email details, username and password in plaintext which could lead to security issues.

### Steps to Reproduce

1. This is the first step
2. This is the second step, etc.

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

### Technical details:

* Ghost Version: 0.11
* Node Version:
* Browser/OS: 
* Database:

**Comment by kevinansfield** [comment]
Hey @vesnikos, we don't consider this to be a bug. If you want to use practices that you consider more secure then you're free to follow any practices you want, the `config.js` file is JS after all so you can grab ENV vars or fetch the values from a secure store, etc.

Bear in mind that the `config.js` file in question should always have the correct file permissions and ownership and it should never be checked in to source control as per standard practice with potentially sensitive config files. If you're following those best practices but your server has been compromised to the point where the file is readable then no amount of additional hashing/encrypting of the usernames or passwords is going to offer any additional help.
