### ISSUE TITLE
coerce Ghost to use specific Node version?

### ISSUE THREAD

**Issue by nebulousdog** [TryGhost/Ghost#8472]
if using `nvm`, how can I coerce Ghost into using the currently used Node version?

for example if I do `node -v` it looks like the current version should be kosher.

```
$ nvm use 6.9.0
Now using node v6.9.0 (npm v3.10.8)
$ node -v
v6.9.0
$ sudo npm start --production

> ghost@0.11.8 start /var/www/ghost
> node index

ERROR: Unsupported version of Node
Ghost needs Node version ^4.2.0 || ^6.9.0 you are using version 7.8.0

...
```

**Comment by wan-qy** [comment]
export GHOST_NODE_VERSION_CHECK=false
plz read [Supported Node Versions](http://support.ghost.org/supported-node-versions/)

**Comment by kirrg001** [comment]
Hey @nebulousdog ✌🏻

We use github solely for bug and issue tracking.

@wan-qy Thanks, correct.
http://support.ghost.org/supported-node-versions/#disable-the-version-check

I'm going to close this issue. If you have any further questions, can you please swing by our [slack channel](https://slack.ghost.org)? Thank you!

**Comment by nebulousdog** [comment]
thanks @wan-qy!
