### ISSUE TITLE
[Alpha.21] Firefox CSS Issues

### ISSUE THREAD

**Issue by hissingpanda** [TryGhost/Ghost#8496]
### Issue Summary

Select drop-down menu arrows appear slighty off in Firefox:

![test1](https://cloud.githubusercontent.com/assets/7660115/26626337/cd039402-45ab-11e7-87da-76a1058c506c.png)
![test2](https://cloud.githubusercontent.com/assets/7660115/26626340/cefcddae-45ab-11e7-8f0a-dde08025bede.png)

### Technical details:

* Ghost Version: Alpha-21
* Node Version :v4.8.2
* Browser/OS: Firefox/Windows 10
* Database: MySQL

**Comment by kevinansfield** [comment]
This no longer appears to be an issue with the latest Firefox, closing for now. If anyone runs into particular display issues whilst using Firefox please open new issues with screenshots, thanks! 😄

**Comment by stromfeldt** [comment]
@kevinansfield This is still occurring for me on a Windows 7 version of Firefox 57.04, although not on my (Ubuntu 16.04-derived) elementary 0.4.1 version of Firefox 57.04:

![firefox 57 04](https://user-images.githubusercontent.com/27488257/34911945-aebb6232-f928-11e7-940a-5891e72004a5.png)

![author](https://user-images.githubusercontent.com/27488257/34911954-d2e456f0-f928-11e7-990e-9bfc47f84ea1.png)
