### ISSUE TITLE
Subscribers table alignment

### ISSUE THREAD

**Issue by JohnONolan** [TryGhost/Ghost#8503]
Subscribers table needs some basic alignment. The icon shouldn't be on a new line. There's no padding around the empty state like there is around the populated state. Doesn't need any special design, just needs cleaning up

![image](https://cloud.githubusercontent.com/assets/120485/26645160/1a4c857e-462f-11e7-8208-94cad92bbf93.png)

**Comment by isabelgm** [comment]
Hi @JohnONolan. I'd love to help out with this.

**Comment by isabelgm** [comment]
I've made the changes on a branch and am ready to make the pull request. 
I'm having trouble committing the changes though. It looks like it has something to do with the submodules. 

This is the error I get. Any tips on how to solve it? 
![screen shot 2017-06-09 at 12 09 36 pm](https://user-images.githubusercontent.com/4932361/26984220-8e6475dc-4d0c-11e7-9517-fc4c17dc456e.png)

**Comment by kevinansfield** [comment]
Hey @isabelgm, we have a guide for [working with the admin client](https://docs.ghost.org/docs/working-with-the-admin-client). In this case it looks like you're attempting to use the top-level Ghost repo, however you need to `cd core/client` and run your git commands etc from there as submodules are essentially their own git repo. The guide has a section about the [git setup](https://docs.ghost.org/docs/working-with-the-admin-client#git-setup) with instructions for adding the [Ghost-Admin](https://github.com/TryGhost/Ghost-Admin) remotes and so on.

If you have any trouble pop by [our slack community](https://slack.ghost.org) and say hi in the #core-dev channel, we'll be happy to help 😄

**Comment by isabelgm** [comment]
Hi @kevinansfield, thanks for the help. I'll take a look at the links. :)

**Comment by JohnONolan** [comment]
This will be revisited as a part of a larger re-work of the subscribers screen
