### ISSUE TITLE
Code injection styles

### ISSUE THREAD

**Issue by JohnONolan** [TryGhost/Ghost#8504]
- Erroneous double border
- Wrong border color
- Erroneous padding/gap

Looks like globals have changed which need code-injection or code-mirror specific overrides. Assume colors are wrong because they aren't using the correct variables

![image](https://cloud.githubusercontent.com/assets/120485/26645260/5c66159c-462f-11e7-8004-503a7d54f22a.png)

**Comment by kevinansfield** [comment]
Hmm, this should already been fixed in master via https://github.com/TryGhost/Ghost-Admin/pull/715 - are you on master and seeing the same problem?

**Comment by JohnONolan** [comment]
padding is fixed, border color still wrong, and now seem to have lost all codemirror styles? 

![image](https://cloud.githubusercontent.com/assets/120485/26646898/5c4f9bb8-4635-11e7-9686-9542781b0249.png)
