### ISSUE TITLE
[i18n] Multi-lingual Content Publishing (Mockups)

### ISSUE THREAD

**Issue by hissingpanda** [TryGhost/Ghost#8509]
In the spirit of the exciting work being done on #8437 I thought I would take a stab at mocking up a design for publishing content in multiple languages. The purpose of this is merely to mockup a workflow for a user to create multi-lingual content.

Below are the preliminary designs, mess around with the XD link to see the design in action.

Adobe XD mockup: https://xd.adobe.com/view/bfec5bf4-85bf-4d3a-b78b-67c19cc963f8/

## Concept

![screen shot 2017-05-31 at 15 54 51](https://cloud.githubusercontent.com/assets/7660115/26657627/d49bd81e-4619-11e7-9742-79fc5ed93e93.png)

Here you can see the that nothing has changed on the current admin interface (Alpha.17) with the exception of an added "translations" box in the post settings.

![screen shot 2017-05-31 at 15 55 04](https://cloud.githubusercontent.com/assets/7660115/26657630/da89e068-4619-11e7-847f-902a8e507a9d.png)

Upon selecting that box, the user would be taken to a settings screen (just like the meta data box functionality) where they can see all of the languages they've added for this post, as well as add additional languages.

![screen shot 2017-05-31 at 15 55 18](https://cloud.githubusercontent.com/assets/7660115/26657634/de20813c-4619-11e7-9e66-8b4dc53d3060.png)

After selecting a language (in this example the user selects Spanish), they would be taken to a new/existing content post where you can create a custom permalink, metadata, tags, and add a translator. It might be better to have both the author and translator fields present across all translated posts.

The approach I've taken here is akin to Drupal 8's translation workflow which ties translated content nodes to the original node using the same node ID in the database.

In the Stories section, each post in a different language could appear as a separate content post with an additional language filter added at the top for sorting, or, alternatively, a translated post could be linked with the original post and listed together with a marker/link to indicate that the current post has been translated in another language(s).

#### Benefits to this approach
- Easy to manage as a user
- Intuitive
- Streamlined with minimal clutter
- No need to mess with tags
- Allows custom permalinks
- Allows custom metadata (could default to include `<html lang="?">`)
- Ability to reference the same post in different languages when theming
- Flexibility
   - some posts can be translated in multiple languages, while others can remain in only one language

I would love to hear feedback on this, and I hope to work on the implementation once a workflow has been decided on.

## Features and Support
Taken from #3801. I've crossed out features that would immediately be solved with this workflow. 

The following is a list of things we know we need to do / make possible / add support for:
#### Publishing
- Level 1: blog language setting
- ~~Level 2: post language~~
- ~~customisable permalinks where english words are used~~
- ~~set `<html lang="?">`~~
- add language output in JSON/LD
- non-latin chars in slugs
- non-latin chars in urls
- non-latin chars when uploading files
- non-latin chars handled by words and characters features of excerpt/content helpers
- non-latin chars in generated heading id attributes
- non-latin chars supported fully in editor
- customisable permalinks for /tag/, /author/, and /page/ urls
- locale dates in themes (moment.js language support)
- different plural structures in the {{plurals}} helper
- extensible rules for what constitutes paragraphs and words in the excerpt and content helpers
- extensible rules for what constitutes paragraphs and words in the editor

**Comment by juan-g** [comment]
> The approach I've taken here is akin to Drupal 8's translation workflow which ties translated content nodes to the original node using the same node ID in the database.

That seems a good possibility, ID + language, to e.g. go directly from a page or post to the same one in another language.

> I would love to hear feedback on this, and I hope to work on the implementation once a workflow has been decided on.

It looks good. The team probably is super-busy right now preparing the launch of Ghost 1.0 Beta, but I think they will like to have community cooperation for internationalization tasks.

**Comment by PaszaVonPomiot** [comment]
Functionally is okay from my point of view. Like in Polylang there should be some kind of indication that the same post exists in another language.

**Comment by DaniloPolani** [comment]
Is there a branch for this to contribute?

**Comment by juan-g** [comment]
@DaniloPolani, not yet. However, since multi-language is a high-demand functionality, I think probably after the next i18n stage is launched, surely soon (translatable Ghost's frontend and themes, #8437).

**Comment by DaniloPolani** [comment]
Oh, well ok. Is there nothing we can do to help with the multi-lang posts/pages feature?

**Comment by juan-g** [comment]
That would mean [installing Ghost locally for development](https://docs.ghost.org/docs/working-with-ghost), and preparing a [pull request](https://docs.ghost.org/docs/contributing/#working-on-ghost-core), all with [Git](https://docs.ghost.org/docs/git-workflow).

However, I would wait for a little while until #8437 is released, and continue from there. Or talk directly to the team, for example on the Ghost's [#i18n](https://ghost.slack.com/messages/C03Q63A9Z) Slack channel.

**Comment by kirrg001** [comment]
Note: If you are interested in leading this project, then please contact us first in slack.

Each project has to go through certain steps (research, review, ui, approval, development). No pull requests accepted before getting an approval. 

And keep in mind, that the Ghost developers are quite busy, so you would have to be patient for feedback loops 🙈 😎

**Comment by edpichler** [comment]
Hello people, is this going on? I really need it.

**Comment by Mindsers** [comment]
@edpichler Hi, I am not a maintainer of this project but I'm glad to see that this issue interests you and that you "really need it", may be it'll be done soon ! 

The open source community needs motivated developers — just like you — to contribute.  😉

**Comment by kevinansfield** [comment]
@edpichler, @Mindsers there is no on-going project by the core team to implement this. I would suggest opening a topic on our [Ideas board](https://forum.ghost.org/c/Ideas/l/votes) and voting 😄 

For the community to help it really needs a champion for this project that can see it through from start-to-finish. The Slack team mentioned above no longer exists but has been replaced by [our forum](https://forum.ghost.org) which is the best place to reach out.

**Comment by mprinc** [comment]
Question from the core developers. Can you provide at least some architectural hints what, how and how complex multi-lingual content extension would be? And also some directions for someone who wants to get involved.

**Comment by mprinc** [comment]
In the meantime, what is the best workaround? Any links, best practice, ...?

**Comment by juan-g** [comment]
> In the meantime, what is the best workaround? Any links, best practice, ...?

@mprinc Not a core developer but, about this point, there is for the time being the workaround of installing several Ghost sites, one for each language (e.g. example.com/es, example.com/fr, etc.). See [Set Up Multilingual Ghost.org Blog](https://irensaltali.com/en/set-up-multilingual-ghost-org-blog/).

On the other hand, of course this issue's goal is multi-language with just one Ghost site, still to be developed.

**Comment by andrewanswer** [comment]
@kevinansfield @mprinc I have an interesting idea - what if Ghost platform will translate the site content on the fly using AWS.Translate/Yandex.Translate API? We can use power of machine learning this way.

We can talk about this. Please contact me through my site answe.ru - you can find my Skype in header.

**Comment by JackNSnake** [comment]
Hi Sir. , Im Jack French Canadian, Quebec near Montreal, justvtold me exactly how to make it ans can translate english tout french, have a nice day

**Comment by sakulstra** [comment]
hello, was just looking at this and found: https://forum.ghost.org/t/multi-lingual-content-publishing/1413 which seems to be closed, but the feature isn't implemented yet, is it? As i get the linked ghost 2.0 release post we can now localize the theme, but the content itself is still mono lingual or did i get this wrong?

**Comment by juan-g** [comment]
@sakulstra Currently, there are a couple of ways to have multilingual sites, both with limitations:

1. The old workaround of installing several Ghost sites, one for each language (e.g. example.com/es, example.com/fr, etc.). See [Set Up Multilingual Ghost.org Blog](https://irensaltali.com/en/set-up-multilingual-ghost-org-blog/) (this link has a recently expired https certificate right now).
2. The new workaround using dynamic routing: [Creating multi-language sites with Ghost – Tutorials](https://docs.ghost.org/tutorials/multi-language-content/), which has its problems, such as no date translation, and for example: [Multilanguage blog with a multilanguage theme - Help - Ghost Forum](https://forum.ghost.org/t/multilanguage-blog-with-a-multilanguage-theme/2602).
3. A third solution could be one like those proposed on this issue, a dedicated solution for multi-language sites, which is not yet developed.

For now, I personally still prefer the first one, which is compatible with easily translatable and easily updatable [themes](https://blog.ghost.org/theme-translations/), automatically translatable dates, etc.

**Comment by ErisDS** [comment]
Closing this as there are now ways to achieve multilingual content. We're interested in any new proposals for making this easier at the API level, or improvements to dynamic routing. 

Note that we intend to add Nested Tags and custom taxonomies to dynamic routing, and those will provide more avenues for structured content like multilingual content.

**Comment by YoranBrondsema** [comment]
We're trying to set up a multi-language blog using Ghost as a headless CMS. We use Gatsby as our site generator, and pull the posts from Ghost with GraphQL at build time.

Unfortunately, none of the workarounds are really great, or at least they make the CMS part really unnatural. Ideally, there would be a way to indicate "these three posts are really just the same post but in different languages". The language could be saved as a tag on the post or something. I realize this impacts the data model quite a bit so I understand this is not an easy feature to develop.

We're now looking into other options like Contentful or Craft CMS but an open-source solution like Ghost would have our preference.

Note that I don't want to criticize Ghost or anything. You guys are doing great work and the fact that it's all open-source is great. I just thought it would be useful to document our use case to further advance the discussions.

**Comment by joallard** [comment]
Hey @ErisDS, I understand what you're saying here:

> Closing this as there are now ways to achieve multilingual content. [...]

But I'm not finding what you're referring to. Are you able to clarify? 

The only thing I can see from read-skimming this long thread is @juan-g's comment. The solutions he stated aren't things I'm willing to do in good conscience as I want to avoid the potential nightmares ahead.

I understand the circumstances, but I'm also kind of sad that I read "Multi-language" on the features page before installing, and now with some fresh install enthusiasm and some searching I land on this closed issue.

As to potential solutions, I'm trying to figure out the current state on this because I'd like to share the UI proposal I've made on netlify/netlify-cms#716, which pretty much applies here:

> 
> Here's what I'd like to see in an L10n interface.
> 
> <img width="400" alt="PNG image" src="https://user-images.githubusercontent.com/949482/73131241-8890db00-3fd5-11ea-9144-714cb131ddf6.png">
> 
> * **Side by side view**: This is a life saver for any kind of localization. I have on my left the content already populated in one language, and on the other, the one to fill in. I can quickly look side to side what to translate.
> 
> * **Quick language switcher**: I can select what is the language I see on each side. Selecting a language will not make me lose my changes, all data is in local memory. This allows me to translate between more than 2 languages, with the one I want for reference. If I'm not sure of what to write in a third language, I can consult both the first and second.
> 
>   (DatoCMS does this kinda well, but no side-by-side last I checked)
> 
> * **Save button**: The Save button saves all languages. (Linkedin's interface is really clunky about this) It should be part of the contract that switching a language does not throw your work away!

I'm happy to help if there's a need.

**Comment by madhums** [comment]
Are there any examples of any themes that do multi language support? Any links other than https://ghost.org/tutorials/multi-language-content/ is appreciated!

**Comment by JackNSnake** [comment]
I no in Guns of Glory have or and work very great translate

**Comment by pengu10** [comment]
Is multilanguage in the roadmap? Can we get a official response?

**Comment by ErisDS** [comment]
This is the official response: 

https://ghost.org/tutorials/multi-language-content/

**Comment by pengu10** [comment]
> This is the official response:
> 
> https://ghost.org/tutorials/multi-language-content/

ok, so its semi supported with code hack at the moment and there are no plans to integrate this officially in the future. Got it.

**Comment by ErisDS** [comment]
It's not a hack, but thanks for making me regret taking the time to reply to you. I recommend having a read of this: https://ghost.org/faq/open-source-etiquette/

**Comment by alevals** [comment]
> It's not a hack, but thanks for making me regret taking the time to reply to you. I recommend having a read of this: https://ghost.org/faq/open-source-etiquette/

That article is misleading.
There are many essential multilanguage features that are not supported by Ghost and that are not even mentionend in that article. 
Just a few: 
- translating theme labels in a decent way (via j.son file, or po file) for multiple languages
- different navigation for each language
- language attribute for tags and authors
.....

**Comment by alevals** [comment]
> It's not a hack, but thanks for making me regret taking the time to reply to you. I recommend having a read of this: https://ghost.org/faq/open-source-etiquette/

That article is misleading.
There are many essential multilanguage features that are not supported by Ghost and that are not even mentionend in that article. 
Just a few: 
- translating theme labels in a decent way (via j.son file, or po file) for multiple languages
- different navigation for each language
- language attribute for tags and authors
.....

**Comment by alevals** [comment]
> This is the official response:
> 
> https://ghost.org/tutorials/multi-language-content/

> It's not a hack, but thanks for making me regret taking the time to reply to you. I recommend having a read of this: https://ghost.org/faq/open-source-etiquette/

That article is misleading.
There are many essential multilanguage features that are not supported by Ghost and that are not even mentionend in that article. 
Just a few: 
- translating theme labels in a decent way (via j.son file, or po file) for multiple languages
- different navigation for each language
- language attribute for tags and authors
.....

**Comment by headkit** [comment]
<img width="444" alt="Bildschirmfoto 2023-01-13 um 13 15 26" src="https://user-images.githubusercontent.com/359542/212318296-7aaeae8e-ec5e-4c87-891e-3f9573bab32e.png">

https://ghost.org/tutorials/multi-language-content/ is down...

**Comment by a0m0rajab** [comment]
@headkit you can find it in the archive: https://web.archive.org/web/20201216021255/https://ghost.org/tutorials/multi-language-content/

**Comment by baloo1687** [comment]
okay, but how I can translate the strings? 

For example:
I have index and index-de. And I need to translate text in header as well. How I can do it?

en version:
<li class='c-nav__item'><a href='site.com/get-a-demo' class='c-btn c-btn--small c-btn--action'>{{t 'Book a Demo' }}</a></li>

de version:
<li class='c-nav__item'><a href='site.com/get-a-demo' class='c-btn c-btn--small c-btn--action'>{{t 'Buchen Sie eine Demo' }}</a></li>
