### ISSUE TITLE
IE11 has incorrect publish menu date/time input sizes

### ISSUE THREAD

**Issue by kevinansfield** [TryGhost/Ghost#8514]
### Issue Summary

The date/time picker inputs in the publish menu break out of the container and screen in IE11.

<img width="1030" alt="screen shot 2017-06-01 at 12 56 42" src="https://cloud.githubusercontent.com/assets/415/26678936/d407cf96-46ca-11e7-8560-ffa3baf86187.png">

### Technical details:

* Ghost Version: 1.0.0-alpha.21
* Browser/OS: IE11 / Windows 8.1

**Comment by lailavinson** [comment]
I will try to fix this

**Comment by berliners1** [comment]
I think I have a solution to this. I'll put up a pull request.
