### ISSUE TITLE
Mismatched placeholder/used post title font-weight

### ISSUE THREAD

**Issue by JohnONolan** [TryGhost/Ghost#8516]
Haven't been able to track down what's doing this. But both should be bold

Empty title:

![image](https://cloud.githubusercontent.com/assets/120485/26684371/b14840bc-46de-11e7-8094-f2a73af6f309.png)

Populated title: 

![image](https://cloud.githubusercontent.com/assets/120485/26684377/bad2bcd4-46de-11e7-971b-3ac592d5a49d.png)

**Comment by kevinansfield** [comment]
Placeholders need to use `::placeholder` instead of `:placeholder` as they are a pseudo element rather than a pseudo class/content. I'll push a quick fix.
