### ISSUE TITLE
Importer: support special/edge cases

### ISSUE THREAD

**Issue by kirrg001** [TryGhost/Ghost#8517]
We collect edge cases for the importer here, where the import fails.
These edge cases are not critical, they are detected by the importer and people get a clear message why the import failed. But on Ghost(Pro), if we migrate the blogs, no import should fail, because this would mean we have to modify the affected JSON files. 

## export contains user with two roles
> Only one role per user is supported at the moment.

I'm not sure why Ghost exported two roles, but i found this edge case.

## import models with missing fields
e.g. import a user without the `email field` - the error looks a bit weird. The server doesn't handle the error correct, unhandled. No idea why yet.

## 2 roles attached

- see #8756
- looks like an older Ghost release has caused this bug when switching roles for a user
- the 1.0 importer can already handle this,  but need's another investigation why it happened

## Check password length if we skip generating a random password
We had the case that someone was able to import a password hash with the length of 2. This has thrown an error, which is good. But we need to add a protection for that.

Ghost: master

**Comment by gargol** [comment]
> e.g. import a user without the email field - the error looks a bit weird. The server doesn't handle the error correct, unhandled. No idea why yet.

This behavior looks OK on the current master  (2.18.2). When tried importing from an import file build by hand without filled out `email`:
```
    "data": {
        "users": [{
            "name": "Bobby Tables",
            "slug": "bobby"
        }]
    }
```

got this error:
![Screenshot from 2019-03-22 14-00-43](https://user-images.githubusercontent.com/675397/54803563-f29c6d80-4caa-11e9-84ec-8263b977d724.png)

But when I added `email` field it has created a user. 

TODO: Reproduce on latest master the roles issue.

**Comment by gargol** [comment]
>export contains user with two roles
>2 roles attached

The scenario of creating a user with multiple roles wasn't reproducible on master neither with normal usage of Ghost 1.0. One other reference to this issue I found was https://github.com/TryGhost/Ghost/pull/8722, but it doesn't explain when such situation might happen.

Assuming we can ignore this issue. But will continue with some digging around real-world data.

**Comment by gargol** [comment]
> Check password length if we skip generating a random password

Was able to import a user with a short password, example hash of `ab` string used in import file: `$2a$10$rTX4xiNk4bJ5VK.omjh7yO6nhmhWn96tPRjtK3U0hxZ5LCt0Tw/bi`. The regular import flow didn't throw any errors or warnings and substituted provided hash with a random one+made user `locked` which forces the reset password flow.

The only case when such a short password can land in the database is when importing using `importPersistUser` mode. In this case, we only check if it's a bcrypt password and don't check anything else. We allow such users to log in, and there are no further checks for password length.
