### ISSUE TITLE
IE 11 Login Input Icon Dislocation

### ISSUE THREAD

**Issue by JimmehCai** [TryGhost/Ghost#8518]
### Issue Summary

SVG icon dislocation on login page. 
![image](https://cloud.githubusercontent.com/assets/5889006/26761420/27d76742-492f-11e7-8fb4-54934abe21c0.png)

Works fine if I add `width: 14px` to `.gh-input-icon svg` (Was `width: auto;`)
![image](https://cloud.githubusercontent.com/assets/5889006/26761430/7dd0f942-492f-11e7-980b-809278ba7526.png)

### Technical details:

* Ghost Version: 1.0 Alpha 21
* Node Version: 6.10.3
* Browser/OS: IE11/ Windows 10
* Database: SQLite

**Comment by kirrg001** [comment]
Hey @JimmehCai! 👋

Thanks for taking the time to create this bug report and thanks for following our guidelines.

The IE11 icon bug was already reported, see #8384. 

And it was already fixed via https://github.com/TryGhost/Ghost-Admin/commit/43a18115ba12b825295b6f363cb1fe9a2b44dc2f. The fix will be available in the next release 🎊
