### ISSUE TITLE
Installation error "Failed to create symlink"

### ISSUE THREAD

**Issue by seanfuture** [TryGhost/Ghost#8519]
### Issue Summary

On Windows when running `yarn run init` from a newly cloned instance of Ghost the command fails with the message `Failed to create symlink`

### Steps to Reproduce

1. `git clone git@github.com:TryGhost/Ghost.git ghost`
2. `cd ghost`
3. `yarn run init`

Resulting output:
```
yarn run v0.24.5
$ yarn global add knex-migrator ember-cli grunt-cli && yarn install && grunt symlink && grunt init || true
yarn global v0.24.5
warning No license field
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Installed "knex-migrator@2.0.16" with binaries:
      - knex-migrator
      - knex-migrator-init
      - knex-migrator-health
      - knex-migrator-migrate
      - knex-migrator-reset
success Installed "ember-cli@2.13.2" with binaries:
      - ember
      - 🐹
success Installed "grunt-cli@1.2.0" with binaries:
      - grunt
warning No license field
Done in 7.10s.
yarn install v0.24.5
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
Done in 84.78s.
Running "symlink:githooks" (symlink) task
>> Error: EPERM: operation not permitted, symlink '..\..\.github\hooks\pre-commit' -> 'C:\Users\seanfuture\Home\Canvas\Platform\ghost\.git\hooks\pre-commit'
Warning: Failed to create symlink: (file) .git/hooks/pre-commit -> ..\..\.github\hooks\pre-commit. Use --force to continue.

Aborted due to warnings.
'true' is not recognized as an internal or external command,
operable program or batch file.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Technical details:

* Ghost Version:  master / a61e6e7cc2e0bee11c69aab64fee9d375959eb3e
* Node Version: v7.10.0
* Browser/OS: Chrome Version 58.0.3029.110 (64-bit) .. Windows 10 v1607 Build 14393.1198
* Database: sqlite3

**Comment by kirrg001** [comment]
Hey @seanfuture 👋

> EPERM: operation not permitted

You don't have enough permissions to create the symlink.
Try and open the terminal as admin.

If you need any help, come say hello on our [slack channel](https://slack.ghost.org). 
We use github solely for bug and issue tracking. I'm going to close this issue.

Thanks 👋

**Comment by kakaluote444** [comment]
> e use github solely for bug and issue tr

谢谢，解决了我的问题
