### ISSUE TITLE
Markdown tags not being rendered on front-end or preview

### ISSUE THREAD

**Issue by cmivxx** [TryGhost/Ghost#8520]
I have numerous instances of markdown tags that are not being interpreted and rendered correctly on the front-end.  I'm not sure if this is a theme issue or a system issue, but I am leaning toward the latter as the theme works when I hardcode the tag in.

Here's the first example: (look in the update header near the top of the article)
https://www.chrisrmiller.com/use-letsencrypt-ssl-certs-with-heroku/
( - or, screenshot - )
http://api.cmivxx.com/cmimg/ghost_markdown-ss2.png

Here's how it looks in the admin panel:
http://api.cmivxx.com/cmimg/ghost_markdown-ss1.png

* This is Ghost 0.11.9.  Been running this since 0.11.3 with all current upgrades.
* Node Version: 6.10.3 (that's all I could get to build on Heroku)
* NPM 3.10.10
* DB Postgres

Thanks for the help!  Love Ghost, it is SOOOOOO much better than WordPress!

--Chris

**Comment by JimmehCai** [comment]
Markdown's link syntax is **`[title](http://)`**. As I see, you had typed `(title)[http://]`

**Comment by cmivxx** [comment]
Wow...   I can't believe I missed that.  Thanks for pointing it out.  I think I need more sleep.
