### ISSUE TITLE
Move default focus to content

### ISSUE THREAD

**Issue by JohnONolan** [TryGhost/Ghost#8525]
On a new post in the editor, can we move default focus to the body instead of the title? Also change placeholder to `Now begin writing your story...`

Idea being that when you start a new post, you begin by writing [something] rather than coming up with a title. This seems to be the default way-around for most of the newer writing apps these days

**Comment by kirrg001** [comment]
Re-open for revert, see https://github.com/TryGhost/Ghost-Admin/pull/755.
This issue caused a [bug](https://github.com/TryGhost/Ghost/issues/8604), which we can't fix right now. Postponed for post 1.0.

**Comment by AileenCGN** [comment]
Even after reverting https://github.com/TryGhost/Ghost-Admin/pull/748 we faced a related - and already existing issue - where autosave is not triggered, when the user skips entering a post title either by clicking into the content area or using tab to jump there:

![autosave](https://user-images.githubusercontent.com/8037602/27382015-3397839a-56af-11e7-8a5d-5f5fd4e1b3d4.gif)

As this seems to be related and needs to be fixed together with this issue, I'll leave this here. We can still open a new issue for it if needed.

**Comment by kevinansfield** [comment]
Not sure how this got closed 😕 Must have been an errant click/keypress
