### ISSUE TITLE
Inconsistent Validation on Theme Activation

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#8530]
We have 3 different activation routes:

- boot
- activate button
- upload

I've been testing with a few themes, namely Casper LTS (current master) and [ghostium](https://github.com/oswaldoacauan/ghostium) which is one of the most popular themes, but which still uses `pageUrl`!

I'm seeing some odd behaviour. Screenshots are linked to make this easier to read:

Casper LTS @ 2334ca8
- boot => lots of cli warning output
- activate  => no popup
- upload => [popup with "errors"](https://puu.sh/wcpX7.png)

Ghostium @ a7baa9e  (current master) 
- boot => lots of cli error output
- activate => [popup with word "Failed"](https://puu.sh/wcq5i.png)
- upload => [popup with "Fatal errors" and "errors"](https://puu.sh/wcq7D.png)

I think the underlying cause here is the difference between "fatal" errors and errors + the concept of warnings all resulting in confusion / inconsistency?

- Activation popups seem to show for warnings and fatal errors, but not errors.
- Upload popup shows "errors" where cli shows a "warning"
- Upload popup shows "fatal errors" and "errors" where cli shows it all as an error
- Upload popup and activation popup are inconsistent

----

I suggest, although I'm not sure how much work it would be, to have the levels in gscan be the same as we have them in logging: info, warn, error, fatal. Rather than having recommendation, warning, error and then an error with a fatal flag? 

That would map cleanly to what logger to use to output an error, and be easier / more consistent to handle in Ghost-Admin.

----

In Ghost-Admin, I think the upload and activation popups need to be consistent?

----

Note: The current CLI messages when there is a non-fatal error do not include the name of the theme, which I found quite confusing. Got a PR for that.

**Comment by kirrg001** [comment]
Error messages on theme activation were improved in the admin panel via https://github.com/TryGhost/Ghost-Admin/pull/756. 

I've talked to @AileenCGN in the morning, she was not able to discover any inconsistencies in the shell. 

I will keep the issue open for now and label it with `post 1.0.0`. We might find more things we would like to optimise.

**Comment by ErisDS** [comment]
I have two last small changes I'd like to have made here and then close this:

![](https://puu.sh/wYGtt.png)

When activating a theme with warnings, E.g. Casper, which uses `{{id}}` in a get helper filter, the modal says:

"Activated successful with warnings/errors".

- [ ] The first 2 words should be either "Activation successful" or "Activated successfully"
- [ ] Then it should say "with [max level]", i.e. if there are only warnings it should say "with warnings", if there are only errors, "with errors" and if both warnings and errors "with errors". Same in the body text with the phrase "warnings/errors".

I'm also hmming and aahing about whether it should indicate that warnings can be ignored. Probably fine as-is for now.

**Comment by AileenCGN** [comment]
I adapted those ^ changes also for the upload theme flow and wording.
