### ISSUE TITLE
Incorrect theme errors

### ISSUE THREAD

**Issue by JohnONolan** [TryGhost/Ghost#8543]
Ghost: Master
---

This

![image](https://user-images.githubusercontent.com/120485/26916865-370dc904-4c2c-11e7-9c7b-d74051c7c730.png)

but

![image](https://user-images.githubusercontent.com/120485/26916875-428eec68-4c2c-11e7-9404-5f85a67354b7.png)

I'm actually using

![image](https://user-images.githubusercontent.com/120485/26916892-579efc6a-4c2c-11e7-96c5-2a5d6d1b8015.png)

still get the same error in the terminal when using

![image](https://user-images.githubusercontent.com/120485/26916993-bc613d34-4c2c-11e7-8998-4d0a921944e0.png)

and both `{{author_image}}` and `{{author.profile_image}}` both render correctly within the theme. So. 

¯\_(ツ)_/¯

So many variables here I don't even know what's wrong.

**Comment by AileenCGN** [comment]
👀

**Comment by AileenCGN** [comment]
Looks like the regex is not working 100%...

`{{author_image}}` shouldn't actually work. When I use it, it doesn't render for me. 

Anyway, looks like a bug. Will fix it.

**Comment by JohnONolan** [comment]
Followup: `{{author_image}}` doesn't work - I was looking at the wrong thing in the browser
