### ISSUE TITLE
Image uploads failing

### ISSUE THREAD

**Issue by JohnONolan** [TryGhost/Ghost#8545]
Ghost: master

Keep ending up in a state where cover image uploads fail, nothing in the console or the terminal. Happens after deleting / adding new image / repeat

![uh2](https://user-images.githubusercontent.com/120485/26920273-c313c5c8-4c38-11e7-9ce7-e7317469c0a0.gif)

**Comment by JohnONolan** [comment]
When I refresh - there is an image there. Not sure if it's the old one or the new one

**Comment by AileenCGN** [comment]
I can confirm this bug. I wasn't able to reproduce in intentionally yet, but I got this issue a couple of times.

**Comment by AileenCGN** [comment]
## Steps to reproduce this issue:

1. Make sure, no image file is uploaded, needs to be in the saved state where you see the `Upload image` button.
2. Upload an image (icon, logo or cover) and *don't save*
3. Delete the uploaded image immediately (again, *don't save*)
4. Upload the image (or a different one, but same 'category' as the one deleted before) again and see, how it doesn't update

**Comment by AileenCGN** [comment]
Doing some more research on this, it seems that uploading the same image twice is causing this issue. I found this

https://github.com/thefrontside/emberx-file-input#resetting-the-input

which sounds like a possible solution, but wasn't able to implement it/test it successfully.
