### ISSUE TITLE
Suspended user status styling

### ISSUE THREAD

**Issue by cobbspur** [TryGhost/Ghost#8546]
### Issue Summary
The status 'Suspended' for a user needs some CSS tweaks else it is squashed up against the user's name

https://puu.sh/wdsk3/99224b0d6b.png

### Steps to Reproduce

Add a new user
Suspend User
View User Profile 

### Technical details:

* Ghost Version: 1.0.0-alpha.21
* Browser/OS: Chrome

**Comment by kirrg001** [comment]
closed via https://github.com/TryGhost/Ghost-Admin/commit/521748bf9cf90c54b911b11cc73cb0d89f0948ad
