### ISSUE TITLE
Possible Bug when uploading images instead of theme.

### ISSUE THREAD

**Issue by cobbspur** [TryGhost/Ghost#8549]
### Issue Summary
Not sure if this is a valid bug so feel free to close if not.

If you accidentally upload a zip with lots of images when trying to upload a theme, there is no way to cancel the request. Clicking the 'Cancel' Button or 'X' does nothing.

### Steps to Reproduce

1. Go the Design tab and upload a zip full of images.

### Technical details:

* Ghost Version: 1.0.0-alpha.21
* Browser/OS: Chrome

**Comment by ErisDS** [comment]
Closing this due to age and lack of traction.
