### ISSUE TITLE
Positioning of loading spinner is off

### ISSUE THREAD

**Issue by AileenCGN** [TryGhost/Ghost#8556]
### Issue Summary

When the internet connection is not super fast, you'll actually get the chance to see the loading spinner in the admin client. The spinner seems to be off (way to far on top of the page) for most of the pages in Ghost admin. See gif below.

### Steps to Reproduce

1. Use Ghost not local!
2. Go to Design, Team or Subscribers
3. See the loading spinner spinning along on top of the page rather than centered

![spinner_position](https://user-images.githubusercontent.com/8037602/26936104-e0c78956-4c97-11e7-8a7e-2e5d39d7ab5e.gif)

### Technical details:

* Ghost Version: Ghost 1.0 beta
* Node Version: 4.5.0
* Browser/OS: Chrome/Safari

**Comment by kevinansfield** [comment]
> Use Ghost not local!

This should also be testable locally by using the network throttling option in Chrome's Web Inspector.
