### ISSUE TITLE
Bug: Tags keyboard navigation 

### ISSUE THREAD

**Issue by cobbspur** [TryGhost/Ghost#8557]
### Issue Summary

If you are creating a new tag in tags menu and you keep pressing tab on keyboard. The meta data gains focus but display is incorrect and you cannot return to main tag menu

![tag menu](https://puu.sh/wevpO/ceb338dbe7.png)

### Steps to Reproduce

1. Go to Tags page in admin
2. Create a new tag then start pressing tab until you reach meta data fields

### Technical details:

* Ghost Version:1.0.0-alpha.21
* Browser/OS: Chrome

**Comment by kennethlarsen** [comment]
One key issue here is that the button element has outline set to none and I'm not sure why since this makes Ghost less accessible.

**Comment by ErisDS** [comment]
Closing due to age and lack of traction.
