### ISSUE TITLE
Fix README.md link content

### ISSUE THREAD

**Issue by kevinansfield** [TryGhost/Ghost#8558]
There are two links in the README file that need final content:

- [ ] "upgrading ghost" - upgrade guide needs adding to 1.0 docs and updated for Ghost-CLI installs
- [ ] "many hours per month" - needs deep FAQ linking to be implemented on ghost.org

**Comment by kirrg001** [comment]
> "many hours per month" - needs deep FAQ linking to be implemented on ghost.org

Could you please raise an issue on the ghost.org repository? I would like todo it, but i am not sure what this means.

> "upgrading ghost" - upgrade guide needs adding to 1.0 docs and updated for Ghost-CLI installs

I've added this to #7421

**Comment by kevinansfield** [comment]
> Could you please raise an issue on the ghost.org repository? I would like todo it, but i am not sure what this means.

Issue already exists here https://github.com/TryGhost/Ghost.org2/issues/131
