### ISSUE TITLE
Black theme requires more CSS

### ISSUE THREAD

**Issue by jloh** [TryGhost/Ghost#8560]
### Issue Summary

Apologies if there is already an issue for this! I did some searching but couldn't find anything. There are still several areas in the admin interface that aren't themed for the dark theme fully. The most blatant one is the editor.

Editor:

![image](https://user-images.githubusercontent.com/3689532/26956522-c4a00126-4d01-11e7-84fc-0a6b326f3d5b.png)

![image](https://user-images.githubusercontent.com/3689532/26956534-d8160c82-4d01-11e7-9bad-e24513997649.png)

Stories list:

![image](https://user-images.githubusercontent.com/3689532/26956531-d03e2846-4d01-11e7-836e-0a96096bff5b.png)

Code injection panel:

![image](https://user-images.githubusercontent.com/3689532/26956579-1ece5fa8-4d02-11e7-80a5-9a6e1af5f6c7.png)

### Technical details:

* Ghost Version: v1.0.0-beta.1
* Node Version: lts/argon
* Browser/OS: 58.0.3029.110 (64-bit)/ OSX
* Database: local/sqlite

**Comment by nuclearpengy** [comment]
Night mode is looking cool! :)

**Comment by Vatsalgarg1617** [comment]
May I contribute in this?
