### ISSUE TITLE
UX: Clicking off Markdown Guide should close it

### ISSUE THREAD

**Issue by jloh** [TryGhost/Ghost#8561]
Happy for this to be closed if people don't agree, but as an end user when using the new editor (trying out the 1.0.0 beta) when I click on the `?` icon for Markdown help I expect clicking off the help box (in the darkened area) to close it.

Hitting the escape key and the X in the corner work currently however.

### Technical details:

* Ghost Version: 1.0.0-beta.1
* Node Version: lts/argon
* Browser: Chrome 58.0.3029.110 (64-bit) on Mac OS X 10.11.6
* Database: SQLite

**Comment by NathanSMB** [comment]
I agree with you and I decided to take a look but when I click the background area the modal closes as expected.

Is there anything in your browsers console that may help solve this? Are there any extensions that may be affecting it?

### Technical Details

* Ghost Version: 1.0.0-beta.1
* Node Version: tested on both argon and boron
* Browser: Chrome 59.0.3071.86 (64-bit) on Ubuntu 16.04
* Database: SQLite

**Comment by jloh** [comment]
Yeah, I can't repeat this either anymore :(

I did change Chrome versions though, now on 59.0.3071.86. Will try and repeat it again on Chrome 5.8

**Comment by kevinansfield** [comment]
I've not been able to reproduce this at all across multiple browsers. Closing for now, if we get any more reports we can re-open.
