### ISSUE TITLE
showing error when save the post

### ISSUE THREAD

**Issue by hzb** [TryGhost/Ghost#8563]
### Steps to Reproduce

1. New a post

2. Click the setting icon, and change the `Post URL`, cause the 

3. Sometimes, you will get the following error, not often

```
Attempted to handle event `becameError` on <ghost-admin@model:post::ember1696:97> while in state root.loaded.saved.
````

### Technical details:

* Ghost Version: 

    Version:  0.11.9 production

* Node Version:

    Version 7.0 

* Browser/OS:

    Chrome with version 58.0.3029.110 (64 bit)  on macOS Serria
 
* Database: 

    sqlite 3

**Comment by AileenCGN** [comment]
Hey @hzb! Thanks for the report. This issue was reported already with #8551, so I'm closing this issue here as it's a duplicate.
