### ISSUE TITLE
Disable spell-check by default

### ISSUE THREAD

**Issue by kevinansfield** [TryGhost/Ghost#8566]
Unfortunately the CodeMirror based spell-check isn't great and can be rather annoying when it's highlighting a lot of perfectly fine words, especially for non-english writers. As such we think it will be best to leave it disabled by default, allowing users to enable it when they want to review.

We're still actively looking for a better spell-check solution, especially one that will allow the native OS/browser spellcheck to function.

**Comment by Wonderfall** [comment]
>We're still actively looking for a better spell-check solution, especially one that will allow the native OS/browser spellcheck to function.

When will this be possible? This is the only thing I miss from Ghost 0.x. I write in french, and most of my articles reach more than 3000 words. It's painful to correct (I have to copy/paste my article in another editor so I can correct it...). The spellchecker toggle is only working in English, and I can't use my extension "Grammalecte".

**Comment by kevinansfield** [comment]
> When will this be possible?

When one is found ;-) At the moment it's not looking likely, browsers don't offer any API to access native spellcheck solutions so unless you are using plain text fields it's very difficult to have decent spellcheck. Any ideas, solutions, PRs, etc, are all very much welcome 😄

We're still planning to pick up our mobiledoc based editor (which does have native spellchecking) again at some point in the future but there's no timeline for that yet.

**Comment by jloh** [comment]
This currently makes authoring on mobile a real pain (on iOS at least) as Safari seems to create the text box as code or something else. None of the auto suggestions seem to work. (Auto space after period etc).

**Comment by kevinansfield** [comment]
@jloh that isn't related to this issue but more an problem with CodeMirror in general, those iOS issues won't be resolved until the Mobiledoc based editor returns

**Comment by Angristan** [comment]
> We're still actively looking for a better spell-check solution, **especially one that will allow the native OS/browser spellcheck to function.**

Any news on this? Using a custom spell-check software is one thing, but disabling the native one without any way to re-enable it is another...

**Comment by kevinansfield** [comment]
@Angristan you will need to look upstream on the [CodeMirror](https://github.com/codemirror/codemirror) repo for an answer to that. The Ghost core team isn't pursuing it's own spellcheck solution for the markdown editor, we are however working on an [entirely new rich-text, block based editor](https://github.com/TryGhost/Ghost/issues/9311) which will have native spellcheck for rich-text areas

**Comment by Angristan** [comment]
Thanks for your answer @kevinansfield

**Comment by dandv** [comment]
#9311 should solve this.
