### ISSUE TITLE
Scheduling api url is not correctly composed.

### ISSUE THREAD

**Issue by sudosu** [TryGhost/Ghost#8568]
### Issue Summary
When I debugged your scheduling process, I noticed that api requests from post-scheduling adapter goes with double-slash part in url (see screenshot https://cl.ly/2K2a1P2N1Q0t).
That's happened cause here https://cl.ly/352p1K1f3Z3Z in your code, apiUrl is already with trailing slash.

I had a problem with that, cause my NGINX configured to remove double(tripple ..) slashes, and your scheduling doesn't works properly. 

Thanks

**Comment by AileenCGN** [comment]
Hey @sudosu! Thanks for reporting this. I can confirm this bug and will work on a fix for it.

**Comment by kirrg001** [comment]
@AileenCGN The double slashes should exist on LTS as well.

**Comment by AileenCGN** [comment]
I didn't see them. But this might we due to a missing trailing slash in the config. Will push a fix for LTS as well.
