### ISSUE TITLE
HTTPS for images

### ISSUE THREAD

**Issue by rawsh** [TryGhost/Ghost#8571]
Something that really annoys me when trying to get my posts to work with https is that dragging an image into the ghost editor will automatically point to the http version of the image. This means that my page is only partially secure, and to fix it I have to go through every image.

**Comment by AileenCGN** [comment]
Hey @rawsh! Sorry to hear that you're having trouble.

Are you experiencing this with Ghost 0.11.x or 1.0?

**Comment by rawsh** [comment]
@AileenCGN Sorry, that should have been in the first post.
0.11.7

**Comment by chanssl** [comment]
I encountered a similar problem. Ghost version：1.0 beta

I have configured the SSL certificate, but found that the ghost backstage page include HTTP resources.` http://mydomain.com/content/images/2017/06/icon.ico?t=1497630662935 ` 
Icon.ico is the Publication icon that I uploaded, and the default  favicon.ico is also HTTP resources.

**Comment by AileenCGN** [comment]
I'm wondering, if this is related to https://github.com/TryGhost/Ghost/issues/8372

**Comment by PaszaVonPomiot** [comment]
I've got the same after logging in to admin panel:
```
Mixed Content: The page at 'https://www.mydomain.pl/ghost/#/signin' was loaded over HTTPS, but requested an insecure image 'http://mydomain.pl/favicon.ico?t=1498124680075'. This content should also be served over HTTPS.
```

**Comment by AileenCGN** [comment]
Hey @PaszaVonPomiot! 

I'm not able to reproduce your issue. Would you mind, sharing some further information about this?

**Comment by kirrg001** [comment]
@AileenCGN Can confirm. Seeing this warning as well.

**Comment by kirrg001** [comment]
> I will investigate and open a different issue eventually, if this turns out to be not related to this issue.

@AileenCGN Could you find out anything?

**Comment by kirrg001** [comment]
In Ghost `1.0` i don't see any warnings anymore, not for adding images to a post, nor for the favicon request. All images are served via https.

@rawsh I can't reproduce what you are experiencing with the latest LTS release. Can you please update to the latest LTS release and report back?

**Comment by kirrg001** [comment]
FYI: For Ghost 1.0, this happens if the frontend is served via HTTP, but the admin panel is served via HTTPS.

**Comment by kevinansfield** [comment]
> If you configure this right, you won't see the warning anymore. The warning can't be avoided for running the frontend on HTTP i guess, because the admin panel requests the favicon from the Ghost frontend.

Correct, I think this is one of those situations which we can't easily prevent - we can't force the request to be HTTPS because whether HTTPS works or not for the frontend is outside of Ghost's control. There _may_ be a workaround where we don't rely on `favicon.ico` and use the settings api with fallback to a Ghost-Admin asset but I think that deserves it's own issue if it's something we want to pursue.

For now if anyone runs into `favicon.ico` mixed-content warning and they want to fix it the correct solution is configure the front-end to be served over HTTPS.

**Comment by PaszaVonPomiot** [comment]
I can confirm that this solution works. Previously (in one of betas) when I put https in "url" ghost didn't work properly. Now it does. Thanks!

**Comment by ErisDS** [comment]
I don't think there's anything to fix here. Will reopen if anyone can provide an example of a broken case in 1.0.
