### ISSUE TITLE
Force author profile images to be square

### ISSUE THREAD

**Issue by JohnONolan** [TryGhost/Ghost#8576]
Currently author profile pictures can be any dimension, which leads to some dodgy hacks. Most notably: Anywhere profile pictures appear in themes, they need to be set as `<div>` tags with background images rather than `<img>` tags - in order to ensure that an author profile picture is always square / fits into the design.

We now have validation for image dimensions applied to `@blog.icon` -- it would be great if we could also validate author profile images to ensure they're always square, when uploading. Would make theming a lot easier

**Comment by rishabhgrg** [comment]
Closed with https://github.com/TryGhost/Ghost-Admin/commit/c8ea3a42d960ea0f57e7cd33e8605347987431fa
