### ISSUE TITLE
DatabaseIsNotOkError when running Ghost as npm-module

### ISSUE THREAD

**Issue by riyaz-ali** [TryGhost/Ghost#8579]
### Issue Summary
I am getting a `Unhandled rejection DatabaseIsNotOkError: Please run knex-migrator init` while trying to run Ghost as an npm-module using the instructions provided [on docs site](https://docs.ghost.org/v1.0.0/docs/using-ghost-as-an-npm-module)

### Steps to reproduce:
1.  Create a new npm project - `npm init`
2.  Install Ghost as a dependency - `npm install ghost --save`
3.  Then create an index.js file with following content:
```
// Ghost CMS
var ghost = require('ghost')

ghost().then(function(server){
    server.start()
});
```
4. Serve with `node index.js`

### Technical details:

* Ghost Version: 1.0.0-beta.1
* Node Version: 6.9.1
* Browser/OS: Google Chrome / Windows 10
* Database: sqlite3

**Comment by AileenCGN** [comment]
Hey @riyaz-ali! Thanks for the report and sorry to hear you're having trouble!

Our docs for running Ghost as `npm` module are currently not updated for Ghost 1.0 beta and we disabled it for now (you saw the document for `0.11.9`, even though the URL says different). It seems that you need to run `knex-migrator init` which is part of the Ghost setup process.

Whilst we're updating the docs, I will close this issue for now. We can reopen it anytime, when it turns out to be an issue indeed.

In the meantime, please swing by in our [Slack community](https://slack.ghost.org) where it's easier and more effective to get this running for you!

**Comment by devmetal** [comment]
Not working. I try to run knex-migrator init but its missing the config file from project root. I also tried to write a script like in the documentation and put the config file manually but also not working.

```JavaScript
var KnexMigrator = require('knex-migrator');
const path = require('path');

const config = path.join(__dirname, 'node_modules', 'ghost', 'MigratorConfig.js');

var knexMigrator = new KnexMigrator({
    knexMigratorFilePath: config,
});

// check your database health
knexMigrator.isDatabaseOK()
  .then(function() {
     // database is OK
  })
  .catch(function(err) {
     // err contains a specific code, based on that code you decide (err.code)
     
     // database is not initialised?
     knexMigrator.init();
     
     // database is not migrated?
     knexMigrator.migrate();
  });
```

Error output:
```bash
/home/adam/works/nodejs/meetup-feed-blog/node_modules/knex-migrator/lib/index.js:20
            throw new errors.KnexMigrateError({
            ^
InternalServerError: Please provide a file named MigratorConfig.js in your project root.
    at new KnexMigrateError (/home/adam/works/nodejs/meetup-feed-blog/node_modules/knex-migrator/lib/errors.js:7:26)
    at new KnexMigrator (/home/adam/works/nodejs/meetup-feed-blog/node_modules/knex-migrator/lib/index.js:20:19)
    at Object.<anonymous> (/home/adam/works/nodejs/meetup-feed-blog/migrate.js:8:20)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:504:3
```

Also the documentations are very poor. Sorry for that but i followed the steps and its constatntly not working and the messages are not helping.

Can i use the not npm package version in my heroku? We want to host it ourselfs. It seems to me a nice project but not well documented.

**Comment by ErisDS** [comment]
As it says in the previous comment, the documentation is for Ghost LTS, there is no documentation for using the latest beta as an npm module.

**Comment by ulayera** [comment]
I also got this error after editing config with my mysql connection parameters. Ran knex-migrator and npm start and it worked (with version 1.2.0).
