### ISSUE TITLE
Enter key doesn't submit sign-in form

### ISSUE THREAD

**Issue by kevinansfield** [TryGhost/Ghost#8588]
### Issue Summary

Pressing <kbd>Enter</kbd> whilst the email/pass fields have focus does not submit the sign-in form. This works in LTS.

### Steps to Reproduce

1. Load the admin sign-in screen
2. Enter an e-mail address and password
3. With the cursor still in the password field press <kbd>Enter</kbd>
4. Note that nothing happens, clicking the submit button will submit the form

### Technical details:

* Ghost Version: 1.0.0-beta.1
* Browser/OS: Chrome 59 / macOS

**Comment by NotGrm** [comment]
Hi Ghost folks !

I have been working on this issue, and I think I found what is causing this bug.

In `app/mixins/text-input` there is a hook to prevent default ENTER behaviour if there is a keyEvent for it. The test is done by looking at **keyEvents.13** property but this property is set in one-way-input component which is extended by **gh-trim-focus-input** component used in signin template.

```
    keyPress(event) {
        // prevent default ENTER behaviour if we have a keyEvent for it
        if (event.keyCode === 13 && this.get('keyEvents.13')) {
            event.preventDefault();
        }

        this._super(...arguments);
    },
```
If I remove this hook signin form submit is called on enter, tests seems green; but I am not sure if it not breaks something elsewhere.

Should I remove the **keyPress** method (tests seems green without it, but I am not sure if it not breaks something elsewhere) ? Or is there a way to skip preventDefault for signin components ?

**Comment by zce** [comment]
+1

**Comment by kirrg001** [comment]
@kevinansfield this needs a little feedback when you are back.

**Comment by kevinansfield** [comment]
Hey @NotGrm 👋 thanks for taking a look at this 😄

Unfortunately simply removing the `keyPress` handler will break some behaviour in the [editor title input](https://github.com/TryGhost/Ghost-Admin/blob/master/app/templates/editor/edit.hbs#L63).

I think one potential solution here would be to extend the `keyEvents.13` conditional to check that it's value is a function before preventing the default behaviour which will always be the case when we pass in an action on the keyevents hash.

An alternative (and possibly better) solution may be to drop the tab/enter keyevents behaviour from the text input mixin and add it to a new editor title component as it's the only place that behaviour is used at the moment.
