### ISSUE TITLE
Enable Public API labs flag by default

### ISSUE THREAD

**Issue by JohnONolan** [TryGhost/Ghost#8601]
Casper 2.0 has some features which depend on the `{{#get}}` helper, which needs the Public API flag to be enabled in order to work. I think it might make sense for 1.0 to take the next step of moving the Public API flag to being checked-by-default in `/ghost/settings/labs/` ?

A secondary issue to this is that it would be really good to rename the file which is injected into `{{ghost_head}}` - currently `ghost-url.js` to something that makes a bit more sense, like `ghost-api.js` or `ghost-sdk.js`.

However the latte issue may be better suited to post-1.0?

- [x] enable public api access by default
- [x] rename ghost-url.js -> raise a new issue for post 1.0.0

**Comment by JohnONolan** [comment]
Hannah on Slack:
> facebook uses `sdk.js` - medium uses `medium-sdk`

So `ghost-sdk.js` sounds like a winner

**Comment by jloh** [comment]
It would be good (IMO) if this file was included by default in `{{ghost_head}}`. Quite a few themes use it in the back end but don't use it on the front end at all and it just ends up being another file for the browser to download and not end up using.

**Comment by kirrg001** [comment]
@jloh Hey 🙃 Thanks for your feedback. 
Could you please move your comment to #8605?
Thank you!

**Comment by ErisDS** [comment]
I ran into an issue today with a use case that wasn't covered by my initial implementation of this.

If you import from LTS, and didn't already have the public API enabled, it will be disabled after import.

The desired behaviour is that the Public API flag be enabled in 1.0.0 unless a user manually disables it.
