### ISSUE TITLE
Content screen sort order changing

### ISSUE THREAD

**Issue by JohnONolan** [TryGhost/Ghost#8603]
There's some weird sorting happening here:

![image](https://user-images.githubusercontent.com/120485/27295357-8703d3cc-5514-11e7-93f2-87372fb2a45d.png)

"Welcome to Ghost" was the first post in the list, then I edited the post and the only thing I changed was the author from Kevin=>John, and then saved. When I went back to content screen, now the post is at the bottom of the screen.

Then I did the same thing with the "using the editor" post, and it went to 2nd-last post on the screen. No idea what the sort order is here, or why it's changing

Ghost 1.0 beta-1

**Comment by kirrg001** [comment]
Admin ignores seconds.
So if you have a post published at `09:00:01` and edit the post, the admin sends `09:00:01`.
