### ISSUE TITLE
Connection Refused using RDS

### ISSUE THREAD

**Issue by wassimseif** [TryGhost/Ghost#8606]
### Issue Summary

- AWS EC2 instance
- Ubuntu 14.04 
- Node 6.5.0
- Ghost 1.0.0 beta  1 
- Nginx

### Steps to Reproduce

1. This is the steps i'm using to install ghost 
```
$ sudo apt-get update 

$ sudo apt-get upgrade

$ curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.2/install.sh | bash

$ nvm install 6.5.0

$ npm install -g ghost-cli

$ npm install -g bower

$ npm install -g gulp-cli

$ ghost install 

//Configure the database  to use RDS instance 
```
Everything is working and the tables are being created by ghost

`ghost start `

> root@ip-172-31-3-206:/home/ubuntu/test-blog# ghost start
 ✔ Validating config
The 'systemd' process manager will not run on this system, defaulting to 'local'
✔ Starting Ghost
You can access your blog at http://ec2-34-228-39-81.compute-1.amazonaws.com:2368

`curl` from my laptop would give this 

` curl -I http://ec2-34-228-39-81.compute-1.amazonaws.com:2368/`

> curl: (7) Failed to connect to ec2-34-228-39-81.compute-1.amazonaws.com port 2368: Connection refused

 However,`curl` from the EC2 instance itself would give this 

` curl -I localhost:2368`

> HTTP/1.1 200 OK
X-Powered-By: Express
Cache-Control: public, max-age=0
Content-Type: text/html; charset=utf-8
Content-Length: 8644
ETag: W/"21c4-b6aBWRt/1/iBKpG6MAz5Zu+gm1Y"
Vary: Accept-Encoding
Date: Tue, 20 Jun 2017 05:33:53 GMT
Connection: keep-alive

All ports on the security group for the instance are open 
i tried a simple Nodejs app just to test

```
var http = require('http');

var server = http.createServer(function(req, res) {
res.writeHead(200);
res.end('Hi everybody!');
});
server.listen(8080);
```
and it worked
### Technical details:

* Ghost Version: 1.0.0 beta 1 
* Node Version: 6.5.0
* Browser/OS:  ubuntu 14.04
* Database: RDS MySQL

**Comment by kirrg001** [comment]
Hey @wassimseif ✌🏻

Sorry to hear you are having trouble, but this is not a Ghost issue.

It looks like your AWS container can't be served from outside. This is usually caused by a missing configuration in the AWS console. Please double check your security groups, your VPC internet gateway, your attached public subnet and your rule table. AWS has lot's of good tutorials e.g. [this one](http://docs.aws.amazon.com/AmazonVPC/latest/UserGuide/VPC_Scenario1.html).

Please swing by our [slack channel](https://slack.ghost.org) if you need further help! Thanks 🙃

**Comment by wassimseif** [comment]
Hey @kirrg001 For some reason it's a problem in the configuration file in ghost 
```
{
   "url":"http://0.0.0.0:2368/",
   "pname":"localhost-1",
   "server":{
      "host":"0.0.0.0",
      "port":2368
   },
   "process":"systemd",
   "database":{
      "client":"mysql",
      "connection":{
         "host":"rds-hostname",
         "user":"ghostroot",
         "password":"password",
         "database":"ghost_production"
      }
   },
   "logging":{
      "transports":[
         "file",
         "stdout"
      ]
   }
}
```
i had to add the host tag in the server object

**Comment by kirrg001** [comment]
Thanks for letting us know 🙃 Happy if it works now!
