### ISSUE TITLE
JSON-LD on pages

### ISSUE THREAD

**Issue by NistorCristian** [TryGhost/Ghost#8609]
### Issue Summary

I created a page and I checked to see what is the json-ld for that page. Apparently is still an Article type. Shouldn't it be a WebPage? Or something else ?

### Steps to Reproduce

Create a page.
View source of that page.
Find `<script type="application/ld+json">`
The `"@type"` is [Article](http://schema.org/Article). Maybe [WebPage](http://schema.org/WebPage) ?

### Technical details:

* Ghost Version: Ghost 1.0.0 beta.1

**Comment by JohnONolan** [comment]
Not at the moment. People use pages in a variety of ways and the distinction isn't clear enough to warrant the technical complexity required to differentiate between the two without certainty of it being correct :)
