### ISSUE TITLE
Post updated notifications stuck

### ISSUE THREAD

**Issue by JohnONolan** [TryGhost/Ghost#8610]
Ghost 1.0-beta1, in production

![image](https://user-images.githubusercontent.com/120485/27424996-3cef8572-5737-11e7-8ea2-542a7635d85e.png)

These notifications get stuck / never disappear. Doesn't happen in latest master - and I don't remember it happening before in development env. Nothing in the console / anywhere

**Comment by PaszaVonPomiot** [comment]
I can replicate the same.

**Comment by kirrg001** [comment]
@AileenCGN Try to spend 1 -2 hours on this maximum and if you can't fix it, assign it to @kevinansfield please 👍
