### ISSUE TITLE
useGravatar privacy flag is not respected

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#8612]
Ghost admin fetches a bunch of configuration from the server, of which one flag is `useGravatar`.
If this is set to false, there should be no attempt to fetch a gravatar for a user.

On the server side, this flag is honoured. Although this flag is passed to the admin client, the`gh-profile.image.js` component doesn't make use of this flag currently.

This is hopefully a small issue, and good for a beginner 😄

**Comment by TomKeyte** [comment]
Hey, I think I'll take a look at this :)

**Comment by kirrg001** [comment]
@TomKeyte Cool, Thanks 👍

**Comment by letsjustfixit** [comment]
@TomKeyte are you working on this?

**Comment by TomKeyte** [comment]
@letsjustfixit Yes, sorry I just took a bit of time getting things set up and getting to know the project.

**Comment by TomKeyte** [comment]
in gh-profile-image, within the imageBackground property declaration I am accessing the configuration variable via 

    this.get('config.useGravatar');

Is that correct? It is returning undefined in gh-profile-image-test but true during normal usage

**Comment by letsjustfixit** [comment]
@TomKeyte I think so, at least [I did it the same way](https://github.com/letsjustfixit/Ghost-Admin/commit/3a2c320e17645983bcc198c952f58a5a03d0fb06) :)

**Comment by TomKeyte** [comment]
I guess I'll leave this as @letsjustfixit has a solution which is pretty much identical to what I had done
