### ISSUE TITLE
Be able to delete the initial fixture posts easily

### ISSUE THREAD

**Issue by kirrg001** [TryGhost/Ghost#8620]
If you install the `beta.2` release and you setup a brand new blog, you will see 5 blog posts, which explain how Ghost works. To be able to delete them easily, we would like to create them with a different user e.g. `Ghost`. The blog owner is then able to delete the `Ghost` user and all the fixture posts are deleted as well.

Note: We have to share this feature with a new customer e.g. extending the welcome tour. Double check with @JohnONolan.

**Comment by PaszaVonPomiot** [comment]
Hey @kirrg001 I would advise against this behavior "when you delete user you delete all their posts". The solution is to either make those posts unowned (this I recommend) or display extra warning message that informs admin what happens after user is deleted.

**Comment by kirrg001** [comment]
> The solution is to either make those posts unowned

There is no concept of unowned posts.

> display extra warning message that informs admin what happens after user is deleted.

We do display a warning that the posts are getting deleted if you are deleting the user.

**Comment by JohnONolan** [comment]
> Note: We have to share this feature with a new customer

Yep, good point - I think would probably make sense as a note *in* the welcome post

**Comment by AileenCGN** [comment]
@JohnONolan you can add the little note in the welcome post now!
