### ISSUE TITLE
🍭   *opinionated*👽 post excerpt ✂️  after fix amount of characters

### ISSUE THREAD

**Issue by letsjustfixit** [TryGhost/Ghost#8621]
### Issue Summary

I'm writing this as per the suggestion after discussion about it on *slack* ..

*This is only a usability question for larger viewports:*
The post listing page (Content) is supposed to show a sneak-peak of the posts. However the summary is clipped after a fix amount of characters.

The result is a kind of funny screen without any real use to the excerpts. (maybe the titles would be enough then? )

![screenshot from 2017-06-16 17-35-02](https://user-images.githubusercontent.com/9042757/27480014-9f19672e-5816-11e7-804f-4b602426927e.png)

### Steps to Reproduce

1. Open the content listing screen
2. Check out the ✂️ed excerpt

### Technical details:

* Ghost Version: 1.0.0-beta.2
* Node Version: 6.11.0
* Browser/OS: Firefox 52.2.0 (ESR) & GoogleChrome 59.0.3071.109  / Debian 9 Stretch
* Database: sqlite3

**Comment by JohnONolan** [comment]
This is not a bug, not a question, and not a suggestion.

**Comment by letsjustfixit** [comment]
Suggestion then: It would be nice if the length of the excerpt would be context-aware ( mobile / desktop ) ie. a parameter for either mobile / desktop or max sensible char length.
