### ISSUE TITLE
🔑 Setup UX: (default) password managers save full name instead of email

### ISSUE THREAD

**Issue by letsjustfixit** [TryGhost/Ghost#8622]
### Issue Summary

During the setup process the password managers offer to store the previously given credentials. However the defaults saved this way are the 
- Full Name
- password

instead of
- Email address
- password

This is going to cause a problem the next time the owner would like to log in.
I recognize that it won't affect most users after ghost-auth is turned on by default but will remain a usability issue for those using password auth

#### Firefox
![Firefox](http://i.imgur.com/P170WKO.png)
*🔥 fox at least allows the user to adjust the data before being saved*

#### Chrome

![Chrome](http://i.imgur.com/XJb62Yf.png)

### Steps to Reproduce

1. Set up a fresh blog from scratch
2. Observe the offered credentials

### Possible solution

*There seems to be only one solution to this issue. Renaming id="email" to id="username" doesn't resolve the issue either. It seems like it doesn't matter about the id or the label, browsers use the field immediately preceding the id="password" field as the username and so I have moved the two fields together[..]*
[Relevant stackoverflow resolution](https://stackoverflow.com/a/27536519/4241444)

### Technical details:

* Ghost Version: 1.0.0-beta.2
* Node Version: 6.11.0
* Browser/OS: Firefox 52.2.0 (ESR) & GoogleChrome 59.0.3071.109  / Debian 9 Stretch
* Database: sqlite3

**Comment by letsjustfixit** [comment]
sorry about the confusing title: "Full Name" instead of email..

**Comment by acburdine** [comment]
@letsjustfixit I went ahead and changed the title to reflect that :)

**Comment by JohnONolan** [comment]
> There seems to be only one solution to this issue ... browsers use the field immediately preceding the id="password" field as the username

We are not going to change the order of fields, and injecting hidden inputs is completely OTT for an edge-case - which means there's nothing to track or change in Ghost. 

This is a password manager bug. Report it to the password manager or use a better password manager (1password works great)

**Comment by letsjustfixit** [comment]
It is the default behaviour for Firefox & Chrome 's "internal" / by-default password manager and as such affects a great deal of users having a browser as it is.  ( the mass of un-interested &/ non-techie &/ lazy ppl: like me 🙂 )
Going to test the default behaviour with IE / Edge later on..

**Comment by kirrg001** [comment]
If this is about **default** password managers in Chrome/Firefox, i do think we should consider fixing that.

**Comment by PaszaVonPomiot** [comment]
Here are some recommendations from [LastPass](https://lastpass.com/support.php?cmd=showfaq&id=3385)

**Comment by letsjustfixit** [comment]
@kirrg001 yepp these are the defaults

**Comment by letsjustfixit** [comment]
Both IE & Edge provided the same result: they do not even offer to store the credentials by default. 
- Microsoft Edge 40.15063.0.0
- IE11
![IE 11](https://user-images.githubusercontent.com/9042757/27518348-199de39e-59de-11e7-8cd1-dba76fa8b215.png)
OS: W10 1703 ( build 15063.413)
