### ISSUE TITLE
Bottom toolbar on logon page

### ISSUE THREAD

**Issue by PaszaVonPomiot** [TryGhost/Ghost#8625]
### Issue Summary

I believe the toolbar should never be visible on signin page.

### Steps to Reproduce

1. Open signin page
2. Make browser window small engough for bottom toolbar to appear

### Technical details:

* Ghost Version: beta.2
* Node Version: 6
* Browser/OS: Chrome / Centos 7 + nginx + SSL
* Database: MariaDB

### Screenshot
![image](https://user-images.githubusercontent.com/5560454/27503752-b8e80d40-587f-11e7-80e0-74e61cc2eb68.png)

**Comment by kirrg001** [comment]
Hey @PaszaVonPomiot 👋

I can confirm this bug. Thanks for your report 👍
