### ISSUE TITLE
How to use process.env.port in Ghost v1

### ISSUE THREAD

**Issue by rakshans1** [TryGhost/Ghost#8629]
Can't able to get a dynamic port from process.env.port

config.production.json
`
{
"url": "http://localhost:8080",
    "adminUrl": "/admin",
    "server":{
        "port": process.env.port
    },
`
Not able to get port and database info from env without hardcoding it to json file.

### Technical details:

* Ghost Version: v1.0.0-beta.2
* Node Version: 6.11.0
* Browser/OS: Chrome/Linux
* Database: Mysql

**Comment by kirrg001** [comment]
Hey @rakshans1!

As already said in slack, you can pass env variables with two underscores `__` e.g. `DATABASE__CONNECTION__HOST`.

Documentation for this will follow before we release `1.0`!
