### ISSUE TITLE
mail-config docs and json format

### ISSUE THREAD

**Issue by PaszaVonPomiot** [TryGhost/Ghost#8633]
In [docs](https://docs.ghost.org/docs/mail-config) you provide example email configuration. Unfortunately json does not accept apostrophes surrounding value fields and gives error: 
```
Error: Parse error on line 23:
...       "transport": 'SMTP',        "opt
-----------------------^
Expecting 'STRING', 'NUMBER', 'NULL', 'TRUE', 'FALSE', '{', '[', got 'undefined'
```

So eg. for Mailgun you need to replace all `'` with `"` like below:

```
mail: {
transport: "SMTP",
    options: {
        service: "Mailgun",
        auth: {
            user: "",
            pass: ""
        }
    }
}
```

At least that worked for me. I'm using beta2.

**Comment by kirrg001** [comment]
@PaszaVonPomiot Thanks! We will update the docs. I will close this issue and reference it here #7421.
