### ISSUE TITLE
Invite users on setup step 3 doesn't allow linebreaks

### ISSUE THREAD

**Issue by AileenCGN** [TryGhost/Ghost#8639]
### Issue Summary

When you setup a new Ghost blog and arrived at setup step 3 where you can invite other users, it's not possible to add more than one user, as linebreaks don't work anymore and comme/semicolon separation doesn't work.

### Steps to Reproduce

1. Setup fresh Ghost install
2. Enter data until you reached step 3 "Invite your team"
3. Enter first email adress
4. Press <kbd>enter</kbd> to try adding more users and see that it doesn't work

### Technical details:

* Ghost Version: Ghost 1.0-beta-2
* Node Version: v6.0
* Browser/OS: Chrome

**Comment by kevinansfield** [comment]
This has the same cause as https://github.com/TryGhost/Ghost/issues/8588, the fix for that should also resolve this issue.
