### ISSUE TITLE
Artifact under linked image after upgrading Ghost from 0.11.8 to 0.11.10

### ISSUE THREAD

**Issue by TedLeRoy** [TryGhost/Ghost#8640]
Welcome to Ghost's GitHub repo! 👋🎉

Do you need help or have a question? Please come chat in Slack: https://ghost.org/slack 👫. Got an idea for a new feature? Please add it to our wishlist: http://ideas.ghost.org 🌟. Found a bug? Please fill out the sections below... thank you 👍

### Issue Summary

There is an artifact under a linked image after upgrading Ghost from 0.11.8 to 0.11.10

Ghost 0.11.10 is running on Ubuntu 16.04.2 LTS with all updates applied.

The issue occurs in all browsers I've tried (Chrome, Firefox, Internet Explorer) on both Windows 10 and MAC OS X.

### Steps to Reproduce

1. Enter a linked image with markdown similar to the following:
`![[node.js Supported Versions](https://image.ibb.co/dBaniQ/Supported_Versions1.png)](https://docs.ghost.org/v1.0.0/docs/supported-node-versions)`

2. Look below the image in either preview or in a browser and the alt text will appear underneath. 
`node.js Supported Versions" title="" />`

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?
[edit] I expected the graphic to display without the code snippet underneath as with all other graphics.

### Technical details:

* Ghost Version:
0.11.10

* Node Version:
4.5.0

* Browser/OS: 
The issue occurs in all browsers I've tried (Chrome, Firefox, Internet Explorer) on both Windows 10 and MAC OS X.

* Database: 
mysql

![artifact1](https://user-images.githubusercontent.com/1678965/27594425-b68a24d4-5b27-11e7-9047-a45462df4d75.PNG)

![artifact2](https://user-images.githubusercontent.com/1678965/27594440-bfa5214a-5b27-11e7-96c3-8622ead2d5d2.PNG)

**Comment by TedLeRoy** [comment]
[Link](https://infosec.theos-blog.com/upgrading-ghost/) to affected page. It happens to be a blog post about upgrading Ghost. :-)

**Comment by letsjustfixit** [comment]
There is a 🐛 in your markdown code:
```
[![node.js Supported Versions](https://image.ibb.co/dBaniQ/Supported_Versions1.png)](https://docs.ghost.org/v1.0.0/docs/supported-node-versions)
```
Which evaluates to:
[![node.js Supported Versions](https://image.ibb.co/dBaniQ/Supported_Versions1.png)](https://docs.ghost.org/v1.0.0/docs/supported-node-versions)
And yours is:
```
![[node.js Supported Versions](https://image.ibb.co/dBaniQ/Supported_Versions1.png)](https://docs.ghost.org/v1.0.0/docs/supported-node-versions)
```
Which github treats as:
![[node.js Supported Versions](https://image.ibb.co/dBaniQ/Supported_Versions1.png)](https://docs.ghost.org/v1.0.0/docs/supported-node-versions)

**Comment by TedLeRoy** [comment]
Wow,

That really sucks! I don't know how many times I looked at that.

Sorry to take up your time with such a lame mistake on my end.

Thanks for getting back to me though!

**Comment by letsjustfixit** [comment]
No biggie I've done worse 🙊 . Happy ✍️
