### ISSUE TITLE
A issue from installation of Ghost 

### ISSUE THREAD

**Issue by Huang9495** [TryGhost/Ghost#8642]
Welcome to Ghost's GitHub report! 👋🎉

Can you help me to resolve this problem about installation of Ghost? 

Operation procedure

### Issue Summary

When i operation procedure of Ghost from official website,this phenomenon as the picture will take place.the procedure is keep in Downloading all the time.

### Steps to Reproduce

1. cd blog
2. ghost install local

### Technical details:

* Ghost Version:1.0.0-alpha.19
* Node Version:v6.11.0
* Browser/OS: Chrome
* Database:

**Comment by ErisDS** [comment]
@Huang9495 I think this is an attempt to use google translate 😊

This issue does not contain enough information to determine if this is a bug or environment problem. 
Please can you go to https://slack.ghost.org and talk to us in the #help channel? 
There we can ask lots of questions.

It is also helpful to provide screenshots, even if they are not English 😊

**Comment by Huang9495** [comment]
Hi! @ErisDS   Thanks for your help! This issue is a environment problem, I think.Because I try to install ghost in another time quantum ,it successful.So I think so that! And I try this way many time ,its success. Thank you for you help again! But I have another issue about Nginx for Ghost now,I hope you can help me!

**Comment by ErisDS** [comment]
[Slack](https://slack.ghost.org) is the correct place to get help with Ghost.

**Comment by Huang9495** [comment]
Hi! @ErisDS  Thanks for you help! I have been in Slack now!
