### ISSUE TITLE
Error 404 for non-existent gravatar

### ISSUE THREAD

**Issue by PaszaVonPomiot** [TryGhost/Ghost#8650]
### Issue Summary

On "Create your account" page when you enter email address that does not correspond to any gravatar you will ger error 404. You can label it "later".

### Steps to Reproduce

1. Invite user whose email address is not in gravatar database
2. Invited user needs to click activation link from email to open "Create your account" page
3. Check the error in developer tools

Will probably produce the same error if you crate new blog and make first login to admin panel.

### Technical details:

* Ghost Version: beta2
* Node Version: 6
* Browser/OS: chrome
* Database: mariadb
* password authentication

### Screenshot

![image](https://user-images.githubusercontent.com/5560454/27769022-2e455960-5f21-11e7-884e-89916b0cc407.png)

https://www.gravatar.com/avatar/0a1e5b26fb907cf79382414dbf82e187?s=180&d=404

**Comment by kevinansfield** [comment]
This isn't a bug but standard gravatar behaviour.
