### ISSUE TITLE
No link option for post image

### ISSUE THREAD

**Issue by theDustRoom** [TryGhost/Ghost#8653]
### Issue Summary

Within **Post Settings** we used to be able to specify a link to an image instead of adding/uploading one. This is useful for when we want to use our "standard" post image or re-use another post image.

### Steps to Reproduce

1. Create a new Story or edit an existing one.
2. Under **Post Settings** there's no option to link to a **Post image** - just **Add post image** is available.

### Technical details:

* Ghost Version: 10.0 Beta 2
* Node Version: 6.11.0
* Browser/OS: N/A
* Database: sqlite3

**Comment by kevinansfield** [comment]
Hey @theDustRoom 👋 URL inputs for image uploads were intentionally removed. See https://github.com/TryGhost/Ghost/issues/8032
