### ISSUE TITLE
robots.txt not served from active theme

### ISSUE THREAD

**Issue by kevinansfield** [TryGhost/Ghost#8654]
### Issue Summary

In LTS if a theme contains a `robots.txt` file that should be served in place of the default [robots.txt](https://github.com/TryGhost/Ghost/blob/master/core/server/public/robots.txt), this is currently broken in `1.0.0-beta.2`

### Steps to Reproduce

1. Add a custom `robots.txt` file to your active theme
2. Start (or restart) Ghost
3. Load http://localhost:2368/robots.txt
4. Note that the default content is served instead of the theme override

### Technical details:

* Ghost Version: 1.0.0-beta.2
* Node Version: 6.10.1
* Database: SQLite

**Comment by kevinansfield** [comment]
https://github.com/TryGhost/Ghost/pull/8648 fixes this but it has no tests and I'm not sure if it's the right fix 😄

**Comment by kirrg001** [comment]
I will take a look at the pull request before the next release 👍

**Comment by kirrg001** [comment]
Closed via https://github.com/TryGhost/Ghost/pull/8648.
