### ISSUE TITLE
REST API (POST) ?

### ISSUE THREAD

**Issue by shubhank008** [TryGhost/Ghost#8655]
Wanted to know if the REST API to post (create new posts) is available yet ? I checked the API documents and could only find READ/GET APIs for post data.
We are thinking to migrate a blog of ours from Wordpress to Ghost for its simplicity but our blog depends on a PHP bot/script to add some content to it each week, thus asking about the API.

**Comment by ErisDS** [comment]
@shubhank008 We ask that you respect our project and don't post questions like this on GitHub. GitHub is for bug reports, [slack](https://ghost.org/slack) is for questions and help.

The API is still a WIP and therefore only partially documented. The community on slack can help you.
