### ISSUE TITLE
Can't set post title nor access PSM or publish menu on mobile view

### ISSUE THREAD

**Issue by AileenCGN** [TryGhost/Ghost#8657]
### Issue Summary

When trying to add a new post on mobile (either using ngrok or Chrome device toolbar), I get a lot of error messages when attempting to add a post title. See image for more information:

![image](https://user-images.githubusercontent.com/8037602/27848085-9df3699e-616c-11e7-9586-7182a37148b9.png)

### Steps to Reproduce

1. Start Ghost and tunnel it with ngrok to your mobile phone or use Chrome device toolbar
2. Click on new post
3. See that you're able to add text in the content area
4. Try to add a post title or access the PSM or the publish menu
5. See loads of error messages and the client crashing
6. After a forced refresh you might see that a post title was saved

### Technical details:

* Ghost Version: current master branches
* Node Version: v6.11.0
* Browser/OS: Chrome
* Database: sqlite3

**Comment by bianle** [comment]
This cause by ,there is no "side-by-side" button on mobile mode.
`gh-markdown-editor.js` Line 99 **className:no-mobile**
```
{
           name: 'side-by-side',
           action: () => {
                this.send('toggleSplitScreen');
           },
           className: 'fa fa-columns no-disable no-mobile',
           title: 'Toggle Side-by-side Preview'
},
```

Line 231 **"sideBySideButton" got "undefind"**
```
// mark the split-pane/full-screen/spellcheck buttons active when they're active
    _updateButtonState() {
        if (this._editor) {
            let sideBySideButton = this._editor.toolbarElements['side-by-side'];
            let spellcheckButton = this._editor.toolbarElements.spellcheck;

            if (this.get('_isSplitScreen')) {
                sideBySideButton.classList.add('active');
            } else {
                sideBySideButton.classList.remove('active');
            }

            if (this._editor.codemirror.getOption('mode') === 'spell-checker') {
                spellcheckButton.classList.add('active');
            } else {
                spellcheckButton.classList.remove('active');
            }
        }
    },
```
