### ISSUE TITLE
Can Ghost help me change the title too of a page instead of just “og:title”?

### ISSUE THREAD

**Issue by amitashwinibhagat** [TryGhost/Ghost#8658]
![view-source_www_cognitiveclouds_com_insights_cloud-strategies-that-reduce-costs-and-increase-efficiencies_](https://user-images.githubusercontent.com/8210904/27877870-f1a8d156-61d9-11e7-9527-b26d8b557e38.jpg)

```
<title>Title1</title>
<meta property='og:title' content='Title2' />
```

I am seeing that Google is using the webpage <title>Title1</title> for all of my blog posts on SERP instead of og:title that ghost creates. The problem is, as a result all of my blog posts have the same duplicate titles. Is there no way I can make changes to the posts' titles within Ghost, without having to reach out to my developers?

**Comment by ErisDS** [comment]
Hi @amitashwinibhagat what you're showing here is not the behaviour of Ghost with the default theme Casper. Therefore, it seems like a problem with your particular theme.

There is a #themes channel in [slack](https://ghost.org/slack) where you can get help from the community to debug your theme. You can also view the [default theme](https://github.com/TryGhost/Casper) and the [documentation](http://themes.ghost.org/) to get information on how to build a theme.

Closing this as it is not an issue with Ghost.
