### ISSUE TITLE
Tiny icons

### ISSUE THREAD

**Issue by JohnONolan** [TryGhost/Ghost#8665]
These icons have gone tiny again - which I have fixed 2 or 3x now and it keeps being broken and regressing. 

Width should be not defined at all, or set to auto - SVG icons are not all square

https://github.com/TryGhost/Ghost-Admin/blob/master/app/styles/components/power-select.css#L10

1.0-beta2

![image](https://user-images.githubusercontent.com/120485/27964491-5b3acb5e-6330-11e7-87af-9127aebca2f4.png)

**Comment by kevinansfield** [comment]
This was broken with the [IE11 fixes](https://github.com/TryGhost/Ghost-Admin/pull/724) and hasn't been resolved/fixed yet. It's on my list, I thought an issue had been opened but search is failing me.
