### ISSUE TITLE
Importer fails to complete (UI console errors)

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#8666]
When importing content, I see the button change to "importing" and never change back.

The data _is_ imported, but the UI doesn't update.

Opening the console, I see this:

![](https://puu.sh/wEDG7.png)

John reported this was working well in the last beta using the same file as I am. Not sure whether something has broken or if its a browser difference?!

I tried on a completely fresh DB just to be sure as well. Happened the same as on my slightly older DB.

### Technical details:

* Ghost Version: master 
* Browser/OS: Chrome 59.0.3071.115 on Mac OS 10.11.6 
* Database: SQLite3

**Comment by kevinansfield** [comment]
We've been unable to reproduce this. Closing for now, if anyone runs into this again or sees it in #help or similar please comment and we can re-open.

**Comment by ErisDS** [comment]
😟  I have this cropping up again locally. I've blown away my node modules & bower components folders and rebuilt Ghost this evening, and had the problem with multiple import files.

I think this is sufficiently hard to reproduce that we can wait until after 1.0.0 to investigate further, however @kirrg001 I strongly suggest running a manual import test on the 1.0.0 build once generated & before release to ensure it's not a build related error.

**Comment by kirrg001** [comment]
@ErisDS 👍  Did you get the same error in the debug console you initially reported?

**Comment by ErisDS** [comment]
Yes identical, these look the same but are from different imports:

![](https://puu.sh/wOM8Y.png)
![](https://puu.sh/wOMq2.png)

**Comment by ErisDS** [comment]
This hasn't been reported again. Closing until it is.
