### ISSUE TITLE
[Feature] Post primary tag

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#8668]
One of the features that was outlined in [Tags 101](https://github.com/TryGhost/Ghost/wiki/Tags-101) and the [Advanced Tag Mgmt](https://github.com/TryGhost/Ghost/issues/4798) issue many moons ago, was the concept of a post having a primary tag.

The idea here, is that the first tag associated with a post is the canonical or main tag - a bit like a category - or main taxonomy - and that additional theme, url and channel features may be built on top of this concept.

Originally Ghost had no concept of tag order in relation to a post, and it could change and not be controlled. This was fixed in Ghost 0.7.0, meaning the first tag of a post is now preserved & tags can be reordered in the UI.

With this, we are able to do things in handlebars like `{{tags.[0].slug}}` to get the slug of the first tag. Casper 2.0 makes use of this a looot, but it is not very readable.

----

New features:

**1. "primary tag" concept in the API and themes**

The driving use case here, is being able to do something like `{{primary_tag.slug}}` in the theme API instead of `{{tags.[0].slug}}`, to make themes more readable & easier to implement.

We _could_ use a helper of some sort, but having looked through the use cases in Casper 2.0, it became clear that would be complex to implement such that it worked in get helper filters as well as it does in standard handlebars.

This would also only provide this feature for themes, and not when accessing content via the API, or internally, meaning we'd still have array indexing code around in other places.

Therefore, I propose that we add this at the API level, always returning an object called `primary_tag` if it is available.

**2.  "primary tag" in the URL**

In the UI, Ghost supports 2 permalink formats - plain:`/:slug/`& dated: `/:year/:month/:day/:slug/`. Via the DB, it is possible to set the permalink to a wide range of formats, including the author slug, post id, or custom strings (e.g. `/post/:slug/`).

Now that we have a concept of a primary tag, this can be expanded to also support `/:tag/:slug/`. This is fairly straight forward to do, but there is one caveat:

Unlike all the other pieces of data we can use in permalinks, primary tag is not absolutely required, and therefore could be null. In this case we need a fallback, E.g. `/none/my-post/`, the fallback can be a route keyword, such that ostensibly it will become configurable at some point in the future, when we choose to expose that functionality (see #8492). 

------

Naming confirmations needed from @JohnONolan:

1. `{{primary_tag.x}}` in handlebars? This is how Casper 2.0 would look: https://github.com/ErisDS/Casper/commit/c613c0bac957dc3552d6d7aa1a51642d6e4048e4
2. Permalink setting in the DB could accept `/:primary_tag/:slug/` or even `/:tag/:slug/` to make it shorter if preferred. I can't think of any other way that `:tag` could be used in the context of a permalink, but am not sure if it should be kept to `:primary_tag` for consistency.
3. What should the default fallback be in the URL if a post doesn't have a primary tag? E.g. `/unknown/:slug/` or `/none/:slug/`? Note: I realise that falling back to `/:slug/` might be desirable, but this is x100000 in terms of technical difficulty (I tried).

**Comment by JohnONolan** [comment]
{{primary_tag.x}} sounds good / clear. I wonder if `{{tag}}` would also make sense. Singular for when you want the primary tag, plural for when you want all of them? Not sure

No desire to affect post permalinks at this stage - but something that would be potentially nice as a config option further down the road?

**Comment by ErisDS** [comment]
> Singular for when you want the primary tag, plural for when you want all of them? Not sure

Maybe? I find `primary_tag` long, but I think `tag` vs `tags` are so similar as to cause confusion. 

> No desire to affect post permalinks at this stage

Cool, I can definitely split out the implementation of this (both features are already done, bar tests).

Handlebars: 3 lines
Permalinks: 4 lines

😅

**Comment by ErisDS** [comment]
Updates following chats with John:

1. `{{primary_tag}}`
2. `/:primary_tag/:slug/`
3. `/all/:slug/`

**Comment by ErisDS** [comment]
Closed by 353e11d

**Comment by ErisDS** [comment]
Temporarily reopening this as we also want to implement the ability to filter based on primary tag, e.g.

`filter="primary_tag:{{primary_tag.slug}}"` to find all posts which explicitly have the same primary tag, as opposed to `filter="tag:{{primary_tag.slug}}"` which looks for all posts that have the same tag anywhere.
