### ISSUE TITLE
ghost setup fails on Alpine

### ISSUE THREAD

**Issue by noahwhite** [TryGhost/Ghost#8670]
### Issue Summary

ghost production setup fails on Alpine with the following error:

Error occurred running command: '/bin/sh -c lsb_release -a' 

### Steps to Reproduce

1. Install ghost-cli on alpine 6.11. I used a docker container and can supply the Dockerfile if needed.
2. Run ghost install local
3. Run ghost setup

Observe the error above is produced. lsb_release is not present on Alpine. Ghost needs to use an alternate method of obtaining this info on Alpine.

### Technical details:

OS: Alpine 6.11
Debug Information:
    Node Version: v6.11.0
    Ghost-CLI Version: 1.0.0-beta.6
    Environment: production
    Command: 'ghost setup'

**Comment by acburdine** [comment]
@noahwhite hey! this is actually a bug with https://github.com/TryGhost/Ghost-CLI, would you mind opening this issue there?
