### ISSUE TITLE
Make lts themes forward compatible

### ISSUE THREAD

**Issue by cobbspur** [TryGhost/Ghost#8679]
Recently in Gscan, the {{image}} errors were changed from non-fatal errors to fatal errors

To enable a smoother transition to 1.0 we want to make it possible to use {{feature_image}}, {{cover_image}} and {{profile_image}} on lts blogs 

This involves registering the helpers in lts as an alias of {{image}} and adding fake attrs to the various post, tag and author model to enable conditionals checks to function correctly.

**Comment by AileenCGN** [comment]
@cobbspur is there a reason why this issue is not closed yet?

**Comment by kirrg001** [comment]
@AileenCGN No, this happens sometimes.

Closed via https://github.com/cobbspur/Ghost/commit/2fc0ba42afce56d34df96c436dfe61d207accceb.
