### ISSUE TITLE
👓 Nightshift UX: warning message partially unreadable (white on yellow)

### ISSUE THREAD

**Issue by letsjustfixit** [TryGhost/Ghost#8680]
### Issue Summary

If nightshift is turned on the *warning* message (about ghost currently unable to send email) is unreadable. The alert has the the *class* `gh-alert-yellow` with 

- `background:` `#fdffb6`
and inherited
- `color:` `#e5eff5`

Note: without Nightshift the `color` would be `#343f44` inhereted from body.ember-application

![Nighshift with warning](http://i.imgur.com/9EEXZXN.png)

### Steps to Reproduce

1. Install ghost 1.0.0 rc 1 with default settings
2. Navigate to the labs section
3. Turn on nightshift theme
4. Force-reload CTRL-F5

I think it is a *minor 🐛  as it is*, however *if* there is *anything* else *using the same warning level* alert *message* it is going to be *hard to read*.

// Of course the still visible link might shed some light on what the rest of the message might be :) .

## Possible fix:

1.  Change `gh-alert-yellow` 's `color` property to something darker prehaps brown `#5d4037` ?
![would look like with brown text](http://i.imgur.com/0zGucYF.png)

2.  To the deafult inhereted `color` for `gh-alert-yellow` `#343f44` ?
![would look like with the default css text color](http://i.imgur.com/iDsE7R0.png)

## Possible workaround:
3. Change the email warning message to another level maybe info? so `gh-alert-yellow` > `gh-alert-blue`
![would look like with info level](http://i.imgur.com/6RYO2G2.png)
### Technical details:

* Ghost Version: 1.0.0-rc1
* Node Version: v6.11.0
* Browser/OS: Firefox 55.0b8 & Chrome  59.0.3071.115  / Windows 10
* Database: sqlite3

**Comment by JohnONolan** [comment]
> Change the email warning message to another level maybe info? so gh-alert-yellow > gh-alert-blue

I think this is the correct fix 👍 

That yellow has always been horrible at the best of times

**Comment by kirrg001** [comment]
If Ghost is unable to send an email, the notification **type** is still a warning? I wondern, if we should change the color for warnings in the admin panel in general? 🤔

**Comment by kevinansfield** [comment]
> I wondern, if we should change the color for warnings in the admin panel in general?

Agree, rather than changing warning types if we want warnings to display the same as info alerts then the styles should be updated to reflect that - it also has the benefit of making sure that all warnings are covered not just this particular one.
