### ISSUE TITLE
@blog cover image documentation is incorrect

### ISSUE THREAD

**Issue by staus** [TryGhost/Ghost#8685]
Sorry if this is the wrong place for documentation issues

### Issue Summary

I was looking for the blog cover image and the documentation says it's property is **@blog.cover_image** while in reality it's just **@blog.cover**

### Steps to Reproduce

1. Read the @blog documentation: https://themes.ghost.org/docs/blog

**Comment by kevinansfield** [comment]
Hey @staus 👋 It sounds like you are looking at the 1.0 docs but using 0.11.x? The relevant 0.11.x doc is  [here](https://themes.ghost.org/v0.11.9/docs/blog), when you are on the docs sites you should see a version dropdown at the top that allows you to switch.

We also have a [theme api changelog](https://themes.ghost.org/docs/changelog) which can be useful in these instances 😄

**Comment by staus** [comment]
Oh shoot! Didn't see that! Thanks!
But why is it that the main download button isn't getting the 1.0 version? :)
https://ghost.org/developers/

**Comment by staus** [comment]
Ah because it's not the final version yet. Gotcha
