### ISSUE TITLE
Alt+L in editor triggers numbered list

### ISSUE THREAD

**Issue by PaszaVonPomiot** [TryGhost/Ghost#8687]
### Issue Summary

Numbered list should be triggered by Ctrl+Alt+L but they are also triggered by Alt+L
I need to use Alt+L to type "Ł" letter.

### Technical details:

* Ghost Version: rc1
* Node Version: 6
* Browser/OS: Chrome
* Database: MariaDB

**Comment by PaszaVonPomiot** [comment]
Begging for fix in rc2 :D

**Comment by kevinansfield** [comment]
@PaszaVonPomiot I'm not able to replicate this - for me <kbd>Cmd-L</kbd> toggles unordered list and <kbd>Cmd-Alt-L</kbd> toggles ordered list.

<kbd>Alt-L</kbd> outputs `¬`
<kbd>Alt-Shift-L</kbd> outputs `Ò`

Are you on Windows per chance?

**Comment by PaszaVonPomiot** [comment]
@kevinansfield yes, I'm a Windows 10 user.

**Comment by kevinansfield** [comment]
Hmm, I've just checked on windows 10 Chrome and can't reproduce, it's possible that's related to how my keyboard is mapped via my VM though. <kbd>Ctrl-L</kbd> and <kbd>Ctrl-Alt-L</kbd> worked fine for the list toggles 🤔

**Comment by PaszaVonPomiot** [comment]
@kevinansfield the problem is that RAlt-L should not toggle list for selected paragraph.
I've checked on Firefox and Edge - the same issue. Then I've checked with different keyboard settings as normally I use "Polish (programmers)" keyboard layout 
![image](https://user-images.githubusercontent.com/5560454/28425374-63941702-6d70-11e7-9b44-bfcda0c7d441.png)

On English RAlt-L does not enable the list but on Polish it does.

**Comment by ErisDS** [comment]
@PaszaVonPomiot I fully understand that for you this is an incredibly annoying bug, however it appears to be very specific to your language/environment.

We're now only fixing urgent bugs before the release of 1.0.0, if you'd like to submit a fix, we can review and merge it for the first post 1.0.0 bugfix release :) Otherwise we'll get to it as soon as we can.

**Comment by PaszaVonPomiot** [comment]
The same issue is with Romainan keyboard ALT-L and ALT-P (this one publishes the post instead of inserting "§") character.

**Comment by kevinansfield** [comment]
The editor content shortcuts are handled in our fork of simplemde https://github.com/kevinansfield/simplemde-markdown-editor/blob/ghost/src/js/simplemde.js.

Definitely open to PRs with fixes or research/links to show how it's possible to deal with different keyboard layouts in JS key event handlers.

**Comment by PaszaVonPomiot** [comment]
I won't be able to help with js as I'm not a programmer but hopefuly this will be useful. It appears that SimpleMDE has the same issue. First we have to understand that in JavaScript we use two parameters to determine which modifier key has been pressed and those are:

* `key`
  * `Ctrl`
  * `Alt`
  * `AltGr` (right alt)

* `Location`
  * `Left`
  * `Right`

If we press AltGr using standard English (US) keyboard then all browsers will detect:
Key '`Alt`' is down. Location: `Right`

However if we press AltGr using Polish (programmers) or Romanian keyboards then js will detect:
* In Edge and Firefox
Key '`Control`' is down. Location: `Left`
Key '`Alt`' is down. Location: `Right`
* In Chrome 
Key '`Control`' is down. Location: `Left`
Key '`AltGraph`' is down. Location: `Right`

So the solution I think will be to check not only for key that is being pressed but also for its location. In our case the numbered list should be triggered by:

Ctrl + Alt (only left) +L

### Useful links
[Snippet ](https://stackoverflow.com/questions/8562528/is-there-a-way-to-detect-which-side-the-alt-key-was-pressed-on-right-or-left) to test keypresses
Numeric key [locations](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/location)

Thanks!

**Comment by JohnONolan** [comment]
Copied proposed solution to simplemde repo - this isn't something to track here

**Comment by PaszaVonPomiot** [comment]
@JohnONolan it is unfortunate that you are closing this even for tracking as it is blocker for Poland and Romania. I mean we can't just stop using "ł" character and I see no resonable workaround so far.

**Comment by kevinansfield** [comment]
@paszavonpomiot it's tracked in [your issue](https://github.com/sparksuite/simplemde-markdown-editor/issues/616) in SimpleMDE which is where this needs to be fixed, keeping multiple issues open means that communication gets split and comments such as yours above don't end up in the right place. Core team monitors our 3rd party deps as well as the core repos

**Comment by PaszaVonPomiot** [comment]
It appears that upstream markdown editor development has halted. Any ideas where to go from here?

**Comment by JohnONolan** [comment]
Yep. You could fix it and open a pull request to SimpleMDE.
