### ISSUE TITLE
Missing lock icons on password reset

### ISSUE THREAD

**Issue by JohnONolan** [TryGhost/Ghost#8688]
On password reset screen there are icon-inputs with space for an icon, but no icon. These should either both have lock-icons (preferable) - or not have space for icons at all (acceptable)

Ghost 1.0-beta2

![image](https://user-images.githubusercontent.com/120485/28220685-5557a21a-68b8-11e7-86f8-de7cfbe1e1f8.png)

**Comment by JohnONolan** [comment]
Also the page title seems to be broken

![image](https://user-images.githubusercontent.com/120485/28220787-ba6da06e-68b8-11e7-9e3a-dc2ebd3e26bf.png)

**Comment by JohnONolan** [comment]
Also when submitting the form, the button goes loading => flashes a red error => then redirects successfully to admin

**Comment by kevinansfield** [comment]
Re-opening, I'd missed the red/retry flash before the redirect 😞 I'll PR a second fix shortly.
