### ISSUE TITLE
Importer does not keep correct authors

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#8691]
I have just setup a new 1.0.0-rc1 blog and imported data from an older 1.0.0-beta2 blog. Both blogs were installed with ghost-cli.

When I import the content from the old blog to the new blog, the wrong user is assigned as the author of all the content.

### Steps to Reproduce

First setup: 
1. Create a blog, fill out the setup with a user e.g. Bob, log in as Bob and create some posts where Bob is definitely the author. 
2. Export the content from this blog and keep it around.
2. Create a second blog, this time fill out setup with a second user Rachel.

3 different tests:

1. Do an import as Rachel, note that all of Bobs posts now belong to Rachel
2. Delete all content, make Bob the owner, and try the Import again (as Rachel), Bobs posts still belong to Rachel.
3. Delete all content, log in as Bob, do an import, Blog posts still belong to Rachel

The blog posts should belong to Bob after importing.

### Technical details:

* Ghost Version: rc1
* Database: MySQL

**Comment by kirrg001** [comment]
Good catch 👍 

I know what the problem is, see https://github.com/TryGhost/Ghost/blame/master/core/server/data/importer/importers/data/base.js#L171.

Fix is coming 🚓
