### ISSUE TITLE
Publish menu saving states have incorrect text

### ISSUE THREAD

**Issue by kevinansfield** [TryGhost/Ghost#8696]
### Issue Summary

The "in progress" text of the publish menu button seems to jump between different status instead of flowing across the states of the same status.

![publish-menu](https://user-images.githubusercontent.com/415/28232403-698a8b50-68e8-11e7-9d0e-08aae5d21851.gif)

Current:
`Publish -> Update -> Published`
`Un-publish -> Publish -> Un-published`

Desired:
`Publish -> Publishing -> Published`
`Un-publish -> Un-publishing -> Un-published`

(scheduling needs testing too)

### Steps to Reproduce

1. Work against a remote server or configure heavy throttling in Chrome to simulate long network requests so that the "saving" state is visible
2. Use the publish menu to move between post statuses

### Technical details:

* Ghost Version: 1.0.0-rc.1
* Browser/OS: Chrome/macOS

**Comment by PaszaVonPomiot** [comment]
A detail really about word "unpublished". It appears that in dictionary it is in fact "unpublished"  rather than "un-published". Currently there are both versions being used in blog.
https://en.oxforddictionaries.com/definition/unpublish
