### ISSUE TITLE
Ghost does not respect Gravatar settings

### ISSUE THREAD

**Issue by PaszaVonPomiot** [TryGhost/Ghost#8697]
### Issue Summary
According to [docs](https://docs.ghost.org/docs/configuring-ghost#section-privacy) it should be possible to disable Gravatar. So I tried:

```
[ghost@strefadysk strefadysk_prd]$ ghost config privacy.useGravatar
false
```
But failed:
![image](https://user-images.githubusercontent.com/5560454/28234762-caf8ea42-6903-11e7-990b-477c9685308e.png)

### Steps to Reproduce

Add to your config:
```
  "privacy": {
    "useGravatar": "false"
  }
```
or alternatively:
```
"privacy": {
    "useTinfoil": true
}
```

Restart ghost. 
Check avatar.

### PS
By the way in docs there's comma at the end of the line which should be removed:
```
"privacy": {
    "useTinfoil": true,
}
```

### Technical details:

* Ghost Version: rc1
* Node Version: 6
* Browser/OS: Chrome
* Database: MariaDB

**Comment by PaszaVonPomiot** [comment]
Nor the `maintenance.enabled` flag is respected.

**Comment by kevinansfield** [comment]
Hmm, this issue was already resolved in https://github.com/TryGhost/Ghost/issues/8612.

Where did you see the gravatar request? Was it when signing up or is it from a user that had a saved gravatar image before you enabled the flag? (the latter is not affected by the flag as it only prevents gravatar from being called when entering email addresses in the setup/invite forms)

**Comment by PaszaVonPomiot** [comment]
I've seen it on authors page. So what you are saying is that it does not deactivate all gravatar links but disables initial gravatar setup when user is added? I guess it makes sense. Let me check that.
While we are in this topic let me ask you @kevinansfield how to restore gravatar without reinviting that user when gravatars are enabled in config? I tried to select manual photo upload and paste the gravatar link but got error about incorrect file type.

**Comment by kevinansfield** [comment]
> So what you are saying is that it does not deactivate all gravatar links but disables initial gravatar setup when user is added?

Exactly, it disables automatic gravatar lookup when entering e-mail addresses in the admin client on `/setup/two` and `/signup` and on the server when saving user models with a new e-mail address.

> While we are in this topic let me ask you @kevinansfield how to restore gravatar without reinviting that user when gravatars are enabled in config? I tried to select manual photo upload and paste the gravatar link but got error about incorrect file type.

I'm not sure I'm following you here. Maybe move this to #help and we can go through the steps that you're trying? If there are bugs there it sounds like a completely separate issue.

**Comment by AileenCGN** [comment]
@kevinansfield can we close this issue?

**Comment by kevinansfield** [comment]
Yeah, I think this can be closed for now, there's no actionable issue left here that I can see.
