### ISSUE TITLE
Please remove 'must-fix to activate theme' error.

### ISSUE THREAD

**Issue by HelloWorld017** [TryGhost/Ghost#8698]
### Issue Summary

I am a theme developer and I am using {{#if}} to theme work on Ghost 0.11.x as well as Ghost 1.0.0 like this:
```
{{#if image}}overlay{{else if feature_image}}overlay{{/if}}
```

But, the ghost says I should change image to feature_image to activate my theme.
Could you fix it to warning?

### Steps to Reproduce

1. Enter the code which contains deprecated tags in if-statement.
2. Active the theme

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

### Technical details:

* Ghost Version: 1.0.0-rc1
* Node Version: 6.5.0
* Browser/OS: Chrome 59.0.3071.115 / Ubuntu 16.04
* Database: sqlite3

**Comment by ErisDS** [comment]
Hi @HelloWorld017 "image" no longer exists in Ghost 1.0.0, and feature_image is being added to the LTS to make it forwards compatible.

Therefore, you really do need to make the change.

**Comment by ErisDS** [comment]
To be clearer here: if we downgraded this to a warning only, the many many many people who need to update their themes wouldn't have clear information on whether or not the theme will work with 1.0. 

For theme developers, as the next LTS version of ghost will be forwards compatible, there should be no need to make themes backwards compatible with older versions. Users can choose to keep the 0.11.x version of Ghost but must still upgrade to the latest in this track for security reasons.
