### ISSUE TITLE
Pagination Bug

### ISSUE THREAD

**Issue by PhoenixPeca** [TryGhost/Ghost#8700]
Hi,

**I am here to report an issue about a broken pagination.**

Apparently, the current pagination for ghost looks like this `https://blog.ghost.org/page/7/`, but if you add any character(s) prior to the trailing slash like this `https://blog.ghost.org/page/7abcd/`, it doesn't show up the expected 404 error page. Instead, the pagination ignores the character(s) after the integer page numbers and shows the 7th page as defined in the integer before the invalid characters.

This bug, in turn, breaks the `{{page_url prev}}` and `{{page_url next}}` helpers. Such that opening this url `https://blog.ghost.org/page/7abcd/` would have the following:
PREVIOUS PAGE: `https://blog.ghost.org/page/7abcd/page/6/`
NEXT PAGE: `https://blog.ghost.org/page/7abcd/page/8/`

which obviously does not exist.

**Comment by AileenCGN** [comment]
Hey @PhoenixPeca! Thanks for the report!

I can confirm this behaviour on our LTS release. It is fixed in current master, tho.

**Comment by PhoenixPeca** [comment]
Hi @AileenCGN,

I have noticed that the new casper theme is using infinite-scroll feature so this bug would not be noticeable in casper. BUT, in other themes which still uses pagination. I can see that this is still an issue. this bug is still in Ghost 1.0.2

**Comment by AileenCGN** [comment]
Yes, @PhoenixPeca, I can confirm this bug with Ghost 1.0.2! Thank you for the report!

**Comment by ErisDS** [comment]
This was closed by 5551099, it's fixed in already in the 1.0 stream, and will also be fixed in the next LTS release.
