### ISSUE TITLE
Multiple Filter Not Working In API

### ISSUE THREAD

**Issue by Rubel-hossain** [TryGhost/Ghost#8706]
Welcome to Ghost's GitHub repo! 👋🎉

Do you need help or have a question? Please come chat in Slack: https://ghost.org/slack 👫. Got an idea for a new feature? Please add it to our wishlist: http://ideas.ghost.org 🌟. Found a bug? Please fill out the sections below... thank you 👍

### Issue Summary

A summary of the issue and the browser/OS environment in which it occurs. 

### Steps to Reproduce

1. This is the first step
2. This is the second step, etc.

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

### Technical details:

* Ghost Version:
* Node Version:
* Browser/OS: 
* Database:

**Comment by Rubel-hossain** [comment]
```javascript

$.get(ghost.url.api("posts", {
            filter: "tags:national,international",
            limit: recent_post_number
        })).done(function(news) {});
```

Here Multiple Filter Not Working But Single Filter Working , link filter: national.
please solve the problem.

**Comment by ErisDS** [comment]
@Rubel-hossain the syntax you are using is not valid. 

You can either use an OR (comma `,`) to join two tag clauses: `tags:national,tags:international` or you can use a group: `tags:[national,international]`.

If you need any more help with the theme API please come and join us in the #themes channel on [slack](https://ghost.org/slack).

**Comment by Rubel-hossain** [comment]
Thanks
