### ISSUE TITLE
Reset password errors

### ISSUE THREAD

**Issue by JohnONolan** [TryGhost/Ghost#8716]
Ghost 1.0-rc1

- Went to https://retreatplans.io/ghost/#/signin and tried to log in, didn't work.
- Thought maybe hannah reset users during an upgrade, so clicked on forgot password.
- Received password reset email and clicked on the link:

![image](https://user-images.githubusercontent.com/120485/28418100-95e25f02-6d6b-11e7-800b-02942988c540.png)

Somehow I am now logged in, without resetting password at all, and the error message still has the broken formatting which Austin listed in another issue (don't know if that was pre or post RC)

Nothing in the client console. Don't know if there might be something in server logs, but Hannah should have access to those

**Comment by JohnONolan** [comment]
ok I think I know what the problem is - I was logged in the whole time - but https://retreatplans.io/ghost/#/signin still loads fine if I'm logged in.

If I'm logged in it should be redirecting to `https://retreatplans.io/ghost`

**Comment by kevinansfield** [comment]
> I was logged in the whole time - but https://retreatplans.io/ghost/#/signin still loads fine if I'm logged in

Interesting, I can't replicate that locally or on my production blog, if I try to load the signin page whilst logged in the admin app always transitions me to https://myblog/ghost/#/. Can you send me an invite so I can see if it's something specific to that blog?

**Comment by kevinansfield** [comment]
> and the error message still has the broken formatting which Austin listed in another issue (don't know if that was pre or post RC)

Are you referring to the yellow alert? That was raised in https://github.com/TryGhost/Ghost/issues/8680

**Comment by kevinansfield** [comment]
We've tracked this down to an unfinished custom domain setup, if you're logged in on one domain and access the admin on another domain that is CNAME'd (but not configured in Ghost) you will see the login screen as auth details are per-domain.

Closing for now but useful info if anyone else runs into a similar issue!
