### ISSUE TITLE
No importer duplicate detection for posts

### ISSUE THREAD

**Issue by JohnONolan** [TryGhost/Ghost#8717]
When importing, Ghost detects and ignores duplicate authors, but doesn't do the same for posts:

It would be great if we could ignore any posts with a slug which already exists?

![image](https://user-images.githubusercontent.com/120485/28421705-03b268b4-6d77-11e7-8e6e-540c72e195c6.png)

Ghost 1.0-rc1

**Comment by kevinansfield** [comment]
We're also using UUIDs now so we should be able to detect when we're importing duplicates that way?

**Comment by kirrg001** [comment]
We detect duplicated posts **within** the file to import, but we don't compare e.g. post slugs or uuid's with the existing posts in the database. Slugs are regenerated if a duplicate is detected. 

So the common use case for a migration is having an empty 1.0 blog and importing the LTS export, which does not result in any duplicated posts. 

We can definitely add a protection to ignore a post when either slug or the uuid exists in the database - but after the the 1.0 release.

**Comment by letsjustfixit** [comment]
@kirrg001 I have such a case when the import processing hits a timeout and the admin client re-tries the process, the result is that all the lts posts are imported again..

**Comment by kirrg001** [comment]
@letsjustfixit Hmm it shouldn't retry the import if a timeout occurs? cc @kevinansfield

**Comment by kevinansfield** [comment]
> I have such a case when the import processing hits a timeout and the admin client re-tries the process

@letsjustfixit, @kirrg001 there is no retry mechanism built into the client so I'm not sure what's being referred to here.

@letsjustfixit if this is a reproducible case for you it would be useful to have some logs from both client (web inspector console/network tab) and server

**Comment by kirrg001** [comment]
Re-opening.

If we would like to add naive slug duplication detection, we might also want to add a simply UI to choose if duplication should be detected. 

The alternative to slug duplication detection is ID detection. Both strategies have pros/cons. 

Right now we keep the current behaviour and avoid a behaviour change.

Conversation started [here](https://ghost.slack.com/archives/C02G9E68C/p1514975805000181) and describes some use cases.

**Comment by ErisDS** [comment]
I think the first pass of duplication detection should be object-ID based. If a post is imported with the same ObjectID as an existing post, we should give the option to override.

Ideally, a dialogue which says:

“The current import contains 2 new posts and 34 duplicates - if you continue, existing posts will be replaced.”

[Cancel]  [Continue & replace existing posts]

----

Further iterations would be to de-duplicate on further properties like slug, title etc.

**Comment by ErisDS** [comment]
We will be revisiting the importer after the ongoing API work.

**Comment by Ashika08** [comment]
@ErisDS I just noticed that I have duplicate posts since I imported twice using the json file! 
I see that the post ids are unique, but the uuids are exactly the same. And the slug gets appended with a "-version" for the duplicate. How are the duplicates being checked and is this feature already implemented?
