### ISSUE TITLE
Importer file is cached

### ISSUE THREAD

**Issue by kirrg001** [TryGhost/Ghost#8721]
If i import a database file and the import fails for some reason, i try another one, but the admin panel always uploads the old importer file. After refresh it's okay.

Steps to reproduce:
1. choose a file (i can provide a file which fails because of multiple roles import)
2. see that the import failed
3. choose a different import file, which succeeds (do not refresh in between)
4. you will get the same error, because the old file was used

Browser: Latest Chrome
Ghost: master

@kevinansfield I guess this is a admin bug, but let me know if not.

**Comment by kirrg001** [comment]
This must be a server caching problem, because i had this on Pro as well and only after restarting my droplet i was able to import a different file. Weird, not sure why this happens suddenly.

**Comment by kirrg001** [comment]
This was caused by a importer crash. So as soon as the importer crashes, it somehow remains in this state.

If you experience this, please restart your server. Will investigate this later.

**Comment by kirrg001** [comment]
I can't reproduce this anymore. @kevinansfield Can you? Otherwise let's close this 🙃

**Comment by kevinansfield** [comment]
Hmm, this would have been fixed in https://github.com/TryGhost/Ghost-Admin/pull/912, I must have missed this issue when adding the commit refs 😄
