### ISSUE TITLE
Lost focus and words when typing post title during autosave

### ISSUE THREAD

**Issue by AileenCGN** [TryGhost/Ghost#8723]
### Issue Summary
Maybe a super edge case, but when I start a new story and enter a post title after I typed some content, the focus on the title gets lost and also the last word that I typed just before the autosave kicked in.

See here:

![autosave_focus](https://user-images.githubusercontent.com/8037602/28447704-bfdb977e-6dfc-11e7-8fd2-6b81a8330954.gif)

### Steps to Reproduce

1. Start a new story
2. Start typing some content
3. Switch (quickly) to the post title and start typing a title
4. See how in between title the focus gets lost and already typed words disappear

### Technical details:

* Ghost Version: 60558a776fa76d8567dce5a226baf9d9baa208a4
* Node Version: 6.11.1
* Browser/OS:  Chrome 59.0.3071.115
* Database: MySQL

**Comment by kevinansfield** [comment]
I think this is another one of those things that would be solved by the `new->edit transition` refactor that I'd like to do (outlined in https://github.com/TryGhost/Ghost/issues/8287).

Quick fix pre 1.0 could be to cancel the autosave tasks when the title gets focus - it should save anyway when the title field loses focus again.

**Comment by ErisDS** [comment]
This particular issue was resolved, and I think we can close this in favour of the new -> edit transition refactor issue: #8287
