### ISSUE TITLE
Disable `save` button when image upload process not finished

### ISSUE THREAD

**Issue by AileenCGN** [TryGhost/Ghost#8724]
### Issue Summary

Uploading an image with the old image uploader modal allows you to click `save` even tho the upload process is not finished yet. This causes the image to be blank.

_Note:_ this also happens in General settings when using the new uploader in general settings. But is not as confusing imo as there's no modal that closes after saving.

### Steps to Reproduce

1. Go to your user profile
2. Throttle the internet connection or use a particularly large image so you'll see the progress bar for a bit
3. Upload either profile or cover image
4. Click `save` before the upload is finished
5. See that no image is saved

### Expected behaviour
I would expect the `save` button to be disabled until the upload process is finished.

### Technical details:

* Ghost Version: 60558a776fa76d8567dce5a226baf9d9baa208a4
* Node Version: v 6.11.1
* Browser/OS: Chrome 59.0.3071.115 / macOS Sierra
* Database:  sqlite3

**Comment by kevinansfield** [comment]
> Note: this also happens in General settings when using the new uploader in general settings. But is not as confusing imo as there's no modal that closes after saving.

What we could do there is prevent leaving the settings screen whilst an upload is in progress by displaying a similar "Are you sure?" modal to the one used when leaving the editor with unsaved changes. This could be rolled up as part of https://github.com/TryGhost/Ghost/issues/8483
