### ISSUE TITLE
Find Method Not Working Inside The API

### ISSUE THREAD

**Issue by Rubel-hossain** [TryGhost/Ghost#8725]
Welcome to Ghost's GitHub repo! 👋🎉

Do you need help or have a question? Please come chat in Slack: https://ghost.org/slack 👫. Got an idea for a new feature? Please add it to our wishlist: http://ideas.ghost.org 🌟. Found a bug? Please fill out the sections below... thank you 👍

### Issue Summary

A summary of the issue and the browser/OS environment in which it occurs. 

### Steps to Reproduce

1. This is the first step
2. This is the second step, etc.

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

### Technical details:

* Ghost Version:
* Node Version:
* Browser/OS: 
* Database:

**Comment by Rubel-hossain** [comment]
```javascript

    top_news_function: function() {

        $.get(ghost.url.api("posts", {
            limit: 10

        })).done(function(data) {

            var postData = data.posts;

           var test = postData[0].html;

            var iframe_url = test.find("iframe");

            console.log(test);

  });

```

showing the error message 

> "Uncaught TypeError: test.find is not a function"

but why find method is not working ? i am trying to get the video url from the content. please solve the problem.

**Comment by AileenCGN** [comment]
Hey @Rubel-hossain!

This, again (like in the other issue you opened a couple of days ago), a syntax error. 

Please don't open issues on GitHub for questions you have. We're using GitHub issues strictly for the purpose of issue tracking. This is not an issue with Ghost and neither with the Ghost API. Again, please use the [slack #help channel](https://slack.ghost.org) first when you have problems and if they turn out to be issues, feel free to open them.
