### ISSUE TITLE
Loading spinner on subscriber table is wrong positioned

### ISSUE THREAD

**Issue by AileenCGN** [TryGhost/Ghost#8727]
### Issue Summary

The loading spinner when changing the order on the subscribers table is wrong positioned. Possibly due to old Ghost classes.

![loading_spinner](https://user-images.githubusercontent.com/8037602/28459239-df4a1024-6e36-11e7-99ec-2208b3134784.gif)

### Steps to Reproduce

1. Enable subscribers feature and add some subscribers
2. Throttle internet connection
3. See that the spinner is at the wrong position

### Technical details:

* Ghost Version: master 60558a776fa76d8567dce5a226baf9d9baa208a4
* Node Version: v.6.11.x
* Browser/OS: Chrome 59.0.3071.115 / macOS Sierra
* Database: sqlite

**Comment by ErisDS** [comment]
As per #8503, this will be revisited as a part of a larger re-work of the subscribers screen
