### ISSUE TITLE
Adding tag via PSM creates duplicate in tags filter

### ISSUE THREAD

**Issue by kevinansfield** [TryGhost/Ghost#8728]
### Issue Summary

If a new tag is created via the tags input in post settings the tag will be duplicated in the tags filter on the stories screen. 1 of the duplicated tags will work when selected, the other will filter to `?tag=undefined`

![tags-bug](https://user-images.githubusercontent.com/415/28462550-a02b138e-6e13-11e7-8e57-232943adba70.gif)

### Steps to Reproduce

1. Open or create a new post and add a new slug via the post settings menu
2. Save the post
3. Click on the Stories link then open the tags filter
4. Note that the new tag is duplicated
5. Refresh the admin client, note that the duplicate is gone

### Technical details:

* Ghost Version: 1.0.0-rc.1
* Browser/OS: Chrome / macOS

**Comment by kirrg001** [comment]
I saw this once, but couldn't reproduce anymore. So can confirm 👍
