### ISSUE TITLE
Scheduling posts, doesn't work

### ISSUE THREAD

**Issue by acko-kolosek** [TryGhost/Ghost#8732]
I get this one strange bug. Scheduling of posts, works on my local machine, but on server it doesn't. Post gets scheduled, but after that, it doesn't appear in list of all posts, when looking it in list of all stories in admin panel it has label "scheduled", but when it is opened, it gives me two options, 
Update > (Update post status) 
  - Unpublished 'Revert this post to a private draft',
  - Published 'Display this post publicly' (Selected option).

I looked through logs and found interesting thing, each time when I schedule post, at exactly that minute logs show error (I extracted few details)

```
{"name":"Log","hostname":"[CONFIDENT]","pid":1906,"level":50,"req":{"meta":{"requestId":"8a2cc1c0-6e1f-11e7-9238-d3d0349d56d8","userId":null},"url":"/schedules/posts/5971ffd8ad1076508717ea48?client_id=ghost-scheduler&client_secret=6a1ce7051df6","method":"GET","originalUrl":"/ghost/api/v0.1/schedules/posts/5971ffd8ad1076508717ea48?client_id=ghost-scheduler&client_secret=6a1ce7051df6","params":{},"headers":{"x-real-ip":"[CONFIDENT]","host":"[CONFIDENT]","x-nginx-proxy":"true","connection":"close","accept-encoding":"gzip","cf-ipcountry":"[CONFIDENT]","x-forwarded-for":"[CONFIDENT]","cf-ray":"[CONFIDENT]","x-forwarded-proto":"https","cf-visitor":"{\"scheme\":\"https\"}","user-agent":"node-superagent/3.5.2","cf-connecting-ip":"[CONFIDENT]"},"body":{},"query":{"client_id":"ghost-scheduler","client_secret":"6a1ce7051df6"}},"res":{"_headers":{"x-powered-by":"Express","cache-control":"no-cache, private, no-store, must-revalidate, max-stale=0, post-check=0, pre-check=0","content-type":"application/json; charset=utf-8","content-length":"73","etag":"W/\"49-UixP/ZkQHp6PWUGBAe+AVdPmw7I\"","vary":"Accept-Encoding"},"statusCode":404,"responseTime":"8ms"},"err":{"id":"8a2d5e00-6e1f-11e7-9238-d3d0349d56d8","domain":"[CONFIDENT]","code":null,"name":"NotFoundError","statusCode":404,"level":"normal","message":"Resource not found","stack":"NotFoundError: Resource not found\n    at new NotFoundError (.../node_modules/ghost-ignition/lib/errors/index.js:87:23)\n    at resourceNotFound (.../core/server/middleware/error-handler.js:106:10)\n    at Layer.handle [as handle_request] (.../node_modules/express/lib/router/layer.js:95:5)\n    at trim_prefix (.../node_modules/express/lib/router/index.js:317:13)\n    at .../node_modules/express/lib/router/index.js:284:7\n    at Function.process_params (.../node_modules/express/lib/router/index.js:335:12)\n    at next (.../node_modules/express/lib/router/index.js:275:10)\n    at .../node_modules/express/lib/router/index.js:635:15\n    at next (.../node_modules/express/lib/router/index.js:260:14)\n    at Function.handle (.../node_modules/express/lib/router/index.js:174:3)\n    at router (.../node_modules/express/lib/router/index.js:47:12)\n    at Layer.handle [as handle_request] (.../node_modules/express/lib/router/layer.js:95:5)\n    at trim_prefix (.../node_modules/express/lib/router/index.js:317:13)\n    at .../node_modules/express/lib/router/index.js:284:7\n    at Function.process_params (.../node_modules/express/lib/router/index.js:335:12)\n    at next (.../node_modules/express/lib/router/index.js:275:10)\n    at cacheControlHeaders (.../core/server/middleware/cache-control.js:33:9)\n    at Layer.handle [as handle_request] (.../node_modules/express/lib/router/layer.js:95:5)\n    at trim_prefix (.../node_modules/express/lib/router/index.js:317:13)\n    at .../node_modules/express/lib/router/index.js:284:7\n    at Function.process_params (.../node_modules/express/lib/router/index.js:335:12)\n    at next (.../node_modules/express/lib/router/index.js:275:10)"},"msg":"Resource not found","time":"2017-07-21T14:18:59.943Z","v":0}
```

Can someone please check this? I tried to debug this, but I was unsuccessful, and the fact that it works on local machine and doesn't on my server doesn't make it any easier.

**Comment by AileenCGN** [comment]
Hey @acko-kolosek!
Could you please provide more information here? Which version of Ghost are you using? Which database and environment?

**Comment by acko-kolosek** [comment]
@AileenCGN Sure, Ghost version "1.0.0-alpha.19", database is mysql, running on Ubuntu 14.04.3 LTS, I just realized that on my local machine is newer ghost version, (beta.3), I'll try updating version on server. I'm having little trouble with that right now, `npm install -g ghost-cli` doens't update version, I'll try to figure that out, and will hope that update of ghost version will resolve that scheduling problem I have

**Comment by ErisDS** [comment]
@acko-kolosek ghost-cli will not perform upgrades between alpha -> beta or beta -> rc. 

You will need to upgrade ghost-cli and then create a fresh ghost install. There are some notes on this here: https://docs.ghost.org/docs/how-to-upgrade-ghost#section-upgrading-ghost-cli

At this point, seeing as this is a report for an old alpha version, and you yourself scheduling working on a newer version (albeit a different env) I'm going to make an assumption that this either fixed or environmental.

If you are able to reproduce the problem on the latest version of Ghost, please come back and update this issue with all of the details of how you configured your environment.

**Comment by antonydandrea** [comment]
I have the same issue on v0.11 Ghost. It used to work but now it doesn't post a scheduled post until I go back to Edit and click Update after the schedule time.

**Comment by kirrg001** [comment]
@antonydandrea Sorry to hear that. 

Could you please provide more context? Otherwise we can't figure out if this is a bug. 

Which blog timezone, steps to reproduce (screencast) and server error logs etc. (as much as you can provide)

**Comment by antonydandrea** [comment]
Sorry for the delay in replying, I was away on holiday.
The server timezone is BST (UTC+1). 

Steps to reproduce:
1) Set the post date to a future date.
2) Click the Schedule Post button.
3) Return many hours later to see that it has not been published.
4) Click Update Post to force the publish.

I have screenshots of an example yesterday. The publish time was "18 Aug 17 @ 09:00", and I saw it hadn't published at 19:46.
