### ISSUE TITLE
Edge styling bugs

### ISSUE THREAD

**Issue by kevinansfield** [TryGhost/Ghost#8734]
### Issue Summary

Edge has a number of styling bugs:

- [ ] calendar icon positioning in date input
<img width="310" alt="screen shot 2017-07-21 at 17 38 11" src="https://user-images.githubusercontent.com/415/28473226-962e93b0-6e3b-11e7-9d1d-f6f2f8e8005a.png">
<img width="276" alt="screen shot 2017-07-21 at 17 38 40" src="https://user-images.githubusercontent.com/415/28473227-9631364c-6e3b-11e7-83c9-571aa2dcc338.png">

- [ ] animated checkmark is invisible (applies to success buttons and the setup steps)
<img width="115" alt="screen shot 2017-07-21 at 18 08 51" src="https://user-images.githubusercontent.com/415/28474234-bafe8f02-6e3f-11e7-9951-f51b0579251e.png">

- [ ] file input styles
<img width="362" alt="screen shot 2017-07-21 at 18 12 32" src="https://user-images.githubusercontent.com/415/28474339-3ab96528-6e40-11e7-806e-59fefff40586.png">

### Technical details:

* Ghost Version: master
* Browser/OS: Microsoft Edge 38.14393.1066.0 (Microsoft EdgeHTML 14.14393) / Windows 10

**Comment by sanchitbansal10** [comment]
I would like to work on it..waiting for the confirmation

**Comment by ErisDS** [comment]
Closing because Edge is dead 😬
