### ISSUE TITLE
Markdown card - Undo shortcut (ctrl + z) creates inconsistencies with other shortcuts

### ISSUE THREAD

**Issue by acburdine** [TryGhost/Ghost#8735]
### Issue Summary

Using the cmd/ctrl+Z (undo) shortcut can lead to some inconsistencies. I came across one whilst testing TryGhost/Ghost-Admin#799, but there might be others that I didn't run into.

Basically, doing the fenced code block keyboard shortcut then undoing it then doing the shortcut _again_ results in different output. I was also intermittently getting into a state where backspace wouldn't actually delete content, although that was less frequent.

![bugz](https://user-images.githubusercontent.com/5167581/28481967-49c3bdcc-6e34-11e7-8c03-c1d12b5472a6.gif)

### Steps to Reproduce

1. open the editor
2. create a fenced code block by pressing cmd/ctrl+alt+c
3. undo changes with cmd/ctrl+z
4. use the cmd/ctrl+alt+c shortcut again - inconsistencies ensue

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

Shortcut behavior should probably be consistent.

### Technical details:

* Ghost Version: master (commit ref: https://github.com/TryGhost/Ghost-Admin/commit/f176171c01c238f2954fbd94221d85939e44be17)
* Node Version: 6.11.1
* Browser/OS: Chrome 59
* Database: Sqlite3

**Comment by kevinansfield** [comment]
As of Ghost 2.0 this is in relation the the markdown card rather than the primary editor. For reference the code block shortcut is <kbd>Cmd+Alt+C</kbd>

**Comment by kevinansfield** [comment]
Closing this as `wontfix` as it's an edgecase in what is no longer the primary input method.

If anyone does want to tackle this then the the [`_replaceSelection`](https://github.com/kevinansfield/simplemde-markdown-editor/blob/ghost/src/js/simplemde.js#L803-L834) method in SimpleMDE is a good place to start (it's called in the [`toggleCodeBlock` ](https://github.com/kevinansfield/simplemde-markdown-editor/blob/ghost/src/js/simplemde.js#L328) function among others).
