### ISSUE TITLE
Bug: Slug is not updating on drafts

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#8736]
This old chestnut has reared its head again. If you don't enter a title and it gets set to untitled, changing the title to something sane doesn't update the slug.

### Steps to Reproduce

1. Open the editor (pre or post Ghost-Admin#798)
2. Do not enter a title
3. Ensure the post get saved (cmd+s)
4. Enter a title
5. Check your slug

Afaik the logic is meant to be that published posts don't get updated slugs, but that drafts do.

**Comment by kevinansfield** [comment]
LTS has the same issue

**Comment by kevinansfield** [comment]
Fixed in 1.0 via https://github.com/TryGhost/Ghost-Admin/pull/800 so that the first time the title is set the slug is automatically updated - after the first title edit we have a slug so unless we compare the slug to the title to see if it matches our automatic slug generation we don't know if the user has set a custom slug so we don't automatically update. This matches the old LTS behaviour that is currently broken.

Not sure if we want to change this behaviour so that the slug is updated more reliably for drafts?

**Comment by ErisDS** [comment]
Afaik the behaviour should be:

Whilst in draft state, if the title is changed and the user has not set a custom slug, then the slug should be updated.

If either the user has set a custom slug, or the post is not a draft (i.e. is published, scheduled or any possible future state) then we no longer make changes to the slug when the title changes.

The server side code has logic to handle this here: https://github.com/TryGhost/Ghost/blob/master/core/server/models/post.js#L289

It seems like something that perhaps never got ported to Ghost-Admin to match the original server side behaviour?

**Comment by BartMassey** [comment]
Just got bit by this bug. Accidentally typed my content into the title field and then hit Save Draft, generating a too-long slug. Nothing would regenerate the slug after that, so had to copy the content out, delete the draft, and start a new one. (The error message was also completely non-intuitive. I didn't even remember what a slug *was* in Ghost until after I'd looked at some other stuff.)

@ErisDS seems to have the right of it. Unless a custom slug has been set, the slug needs to be updated each time the title changes. Also, it would be nice to change the error messages involving slugs to have some explanation of or link to what a slug is.

**Comment by kevinansfield** [comment]
> Nothing would regenerate the slug after that, so had to copy the content out, delete the draft, and start a new one. (The error message was also completely non-intuitive. I didn't even remember what a slug was in Ghost until after I'd looked at some other stuff.)

@BartMassey were you unable to set the slug using the slug field in the PSM? The automatic re-generation not working after a save is expected at the moment until this issue is closed.

**Comment by BartMassey** [comment]
@kevinansfield I didn't even find the slug field in the PSM. (What's the PSM?) My bad.

**Comment by kevinansfield** [comment]
Sorry, PSM is the Post Settings Menu, it's accessed by clicking the ⚙️ icon in the top right - it has fields for the slug, featured image and all the meta data.

**Comment by kevinansfield** [comment]
The [server-side element](https://github.com/TryGhost/Ghost/blob/master/core/server/models/post.js#L289) to this needs some research - if that is being run on post saves then the logic shouldn't be duplicated in the client, any save of a draft with a new title should be returning the new slug which will automatically update on the client.

**Comment by ErisDS** [comment]
We're dropping LTS support on 31st December. The only fixes that will happen between now and then are any major security issues. Closing this as wontfix.
