### ISSUE TITLE
Cmd + H cycles through headings 1-6

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#8737]
In LTS the behaviour of cmd + H was designed to cycle between h2 and h3. In Ghost 1.0 it cycles from H1 to h6. 

### Steps to Reproduce

1. Select some text in the editor
2. Press cmd + h
3. Note that the first change is to h1
4. Keep pressing and it will cycle all the way to h6

This issue is just to flag up a behaviour change, and determine if it needs to be addressed further later.

**Comment by JohnONolan** [comment]
I think this is fine unless anyone complains
