### ISSUE TITLE
Markdown outputs <br></br>

### ISSUE THREAD

**Issue by wangqiliang** [TryGhost/Ghost#8743]
### Issue Summary

In Ghost 1.0, the markdown parser outputs `<br></br>` instead of `<br />`. That causes the issue.

### Steps to Reproduce
1. Create a post like this. Notice that there are three spaces after the "Example1"
```markdown
Example1   
Example2
``` 
2. Save and publish it.
3. View the post. It outputs just like this:
```html
<p>Example1<br></br>
Example2</p>
```
I expect if it could output like this:
```html
<p>Example<br />
Exmaple</p>
```
For Example, Please look at this post (https://wangqiliang.com/yong-lai-ti-dai-guan-fang-tong-ji-jiao-ben-de-ga-js/).
### Technical details:

* Ghost Version:1.0
* Node Version:v6.11.1 LTS
* Database: MySQL 5.7
![tim 20170724114522](https://user-images.githubusercontent.com/3102114/28507474-9647a72a-7065-11e7-98f2-26e295360346.png)

**Comment by kevinansfield** [comment]
Thanks @wangqiliang. I've tracked down the issue to our mobiledoc rendering and opened a PR to fix it (https://github.com/TryGhost/Ghost/pull/8749)
