### ISSUE TITLE
Mail configuration document improvements

### ISSUE THREAD

**Issue by pupboss** [TryGhost/Ghost#8748]
It seems Ghost 1.0.0 is still using nodemailer 0.7, please replace this link (https://github.com/nodemailer/nodemailer/tree/0.7) in the document.

Or users may configure mail settings as the newest nodemailer documents show.

And, the Ghost 1.0.0's config file is in JSON format, all the keys and values should be quoted, the document may cause misunderstanding.

### Technical details:

* Ghost Version:1.0.0
* Node Version:v6
* Browser/OS: N/A
* Database: N/A

**Comment by acburdine** [comment]
Documentation has been fixed. 😄 

In the future, please use the "Suggested Edits" feature of docs.ghost.org, as that's what it's there for - Github issues should be used for bug reports and ongoing feature work 😉

**Comment by pupboss** [comment]
@acburdine Noted with thanks :)

**Comment by pupboss** [comment]
@acburdine One more typos, according to the source code of Ghost, (https://github.com/TryGhost/Ghost/blob/master/core/server/mail/GhostMailer.js#L22), 

```
"mail": {
    "from": "myemail@address.com",
}
```

should be 

```
"mail": {
    "fromaddress": "myemail@address.com",
}
```

I have submitted a suggested edit on the site, maybe you could approval it later

the configuration has been tested on my own blog and passed.

**Comment by acburdine** [comment]
I merged it and then realized that `from` works as well, and is probably simpler. If you look at that line `from` is also accepted as a valid key.

**Comment by ErisDS** [comment]
`from ` is correct. `fromaddress` should really be removed from the code as well as documentation.

**Comment by kirrg001** [comment]
The documentation was already updated for 1.0, i guess @acburdine did it. 

I will delete the `fromaddress` config key support from the code base later, because it's a really quick thing.
