### ISSUE TITLE
2 roles attached to one user

### ISSUE THREAD

**Issue by kirrg001** [TryGhost/Ghost#8756]
This is not supported, maybe it was in the past.

We should figure out what is the reason that some blogs have multiple roles attached to one user.
This was discovered while testing LTS -> 1.0 migrations, only 2 blogs so far had two roles attached. 

**If you experience this, the importer won't accept this file, because we can't know which role we should decide for.**

There are no steps to reproduce at the moment. I am just tracking this issue to 

Ghost: LTS & Master

**Comment by ErisDS** [comment]
@kirrg001 Do we need this issue and https://github.com/TryGhost/Ghost/issues/8517? They seem very related 👻

**Comment by kirrg001** [comment]
Not really, i will reference this one in #8517 👍 Closing.
