### ISSUE TITLE
Images wrapped in <figure> do not work

### ISSUE THREAD

**Issue by JohnONolan** [TryGhost/Ghost#8758]
This outputs markdown as plaintext, and does not render an image

```
<figure>
![Ghost Desktop](/content/images/2016/05/ghost-desktop.png)
<figcaption style="margin-top:-24px;color:#888;font-style:italic;"><small>Ghost Desktop, released just <a href="https://blog.ghost.org/desktop/">last week</a>.</small></figcaption>
</figure>
```

**Comment by kevinansfield** [comment]
For anyone running into this, a workaround is to ensure the markdown image tag is not directly after the opening HTML tag, e.g.:

```markdown
<figure>

![Ghost Desktop](/content/images/2016/05/ghost-desktop.png)
<figcaption style="margin-top:-24px;color:#888;font-style:italic;"><small>Ghost Desktop, released just <a href="https://blog.ghost.org/desktop/">last week</a>.</small></figcaption>
</figure>
```

**Comment by kevinansfield** [comment]
It's a deviation from the pre-1.0.0 behaviour (which didn't fully conform to any markdown spec) but this is in accordance with the CommonMark spec (see [explanation and examples](http://spec.commonmark.org/0.26/#example-152)).
