### ISSUE TITLE
Disqus comments don't load after migration to 1.0.0

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#8760]
After migrating a blog which had Disqus comments to Ghost 1.0.0, the Disqus comments will no longer load on old posts.

### Steps to Reproduce

1. Setup an LTS blog with Disqus comments, using the code given on Disqus or [help.ghost.org](https://help.ghost.org/hc/en-us/articles/115000440851-Disqus)
2. Migrate your blog to 1.0.0
3. Try to view comments on an old post.

This occurs because Ghost 1.0.0 uses different ids to Ghost LTS. In order to workaround the problems of viewing previews triggering a new Disqus thread, we have always recommended our users to set the disqus identifier to be `ghost-{{id}}`. However, `{{id}}` changes between LTS and 1.0, meaning the comment threads for old posts cannot be found by Disqus.

### Technical details:

* Ghost Version: 1.0.0

**Comment by ErisDS** [comment]
Unfortunately, Disqus doesn't provide good tools for handling this case. The `/threads/update.json` endpoint that should allow us to tell Disqus about new IDs throws 500 errors. 

To mitigate this issue in the short term, we're going to keep old post IDs around after importing. So that we don't have to do a crazy-ass database migration right now, we're going to solve this in a slightly dirty way - by using the currently unused `amp` field on posts.

Short term, we'll store old post ids in the `amp` field, and provide a computed, or virtual property on posts called "comment_id". `comment_id` will return the old ID from the `amp`field if it is available, or the new ID from the `id` field if not. We'll ship this as a bug fix release. 

All themes that include Disqus embeds will need to change their embed code.

E.g.

Modern embed must change from `this.page.identifier = 'ghost-{{id}}';` to `this.page.identifier = 'ghost-{{comment_id}}';`

Older embed code must change from `var disqus_identifier = 'ghost-{{id}}';` to  `var disqus_identifier = 'ghost-{{comment_id}}';`

In order to help catch this issue, we'll update gscan to run two new checks.

The first check will be for disqus embed code, and will trigger a fatal error if the disqus embed code with `{{id}}` is located, telling users that they must replace this with `{{comment_id}}`.

The second check will be for `{{id}}` and will throw a warning to users advising them that depending on their use-case they _may_ need to replace this with `{{comment_id}}`.

We will also update our own themes (Casper & Blog) to reflect these changes.

This will be released as a patch release.

----

Long term, we will add a database migration that will move the old post id to a more appropriately named field (`lts_id` or `comment_id`?) 

The computed property of `{{comment_id}}` will continue to work, despite the underlying storage of the data changing.

This will be released as a minor or major release, depending on how we decide to treat database migrations in future.

**Comment by jloh** [comment]
Whilst not nearly as critical, it should be noted since the ID in the RSS feed changes as well RSS readers see all the posts as "new".

I only noticed since I saw blog.ghost.org is now on 1.0!

**Comment by kirrg001** [comment]
@jloh Interesting point. `guid` is the rss identifier, which has to reflect the old post id as well.

@Windfarer `id` and `comment_id` are never in conflict. Importing **two**  blogs with disqus comments won't work, because LTS model id's are auto incremental. That was one reason Ghost has [switched to ObjectId's](https://github.com/TryGhost/Ghost/issues/7494). Plus every **single** blog should have one unique disqus client id/shortname.

**Comment by Oliv4945** [comment]
Hi.  
I still have an issue after the migration from 0.11 to 1.0, following is my previous code. 
I tried first to replace `{{id}}` by `{{comment_id}}` as recommended by gscan, then `{{post.id}}` and any combination of them but my comments never shows.
I also tried to replace all my code by the procedure in [the doc](https://help.ghost.org/hc/en-us/articles/115000440851-Disqus) but it does not work neither. Do you have any hint ?

Thank you
```
<section id="dynacomments" data-backuseid="{{id}}"></section>

<div id="disqus_thread"></div>
<script type="text/javascript">
  var disqus_shortname = '*****';
  var disqus_identifier = "{{post.id}}";
  
  (function() {var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true; dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js'; (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq); })();
  
  </script><noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>

  <a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a> 
```

**Comment by ErisDS** [comment]
HI @Oliv4945 I'm assuming that your disqus snippet is outside of the `{{#post}}{{/post}}` block. That's what makes your version different to what's stated in the documentation you link to.

So, where you have `{{post.id}}` you need to have `{{post.comment_id}}`. If you were inside the `{{#post}}{{/post}}` block, then `{{id}}` or `{{comment_id}}` would work as documented, as your snippet is outside it, you need to add `post.` with is the path to reference the post.

**Comment by Oliv4945** [comment]
@ErisDS , thank you for your answer.
Unfortunately the snippet I post is inside `{{#post}}{{/post}}` . I tried without `post.`, also with it and moving the block outside it did not work :/
I must admit that I copy/paste a code from the internet when it was not on Ghost's website without taking time to understand it, but I might have messed something up :/
