### ISSUE TITLE
Field focus when adding navigation items

### ISSUE THREAD

**Issue by JohnONolan** [TryGhost/Ghost#8764]
If you add a new nav item and press [enter], the focus moves to the "url" field on a new line. It should move to the "label" field

![image](https://user-images.githubusercontent.com/120485/28661735-b38900e4-72c8-11e7-825f-576d50525a1b.png)

**Comment by ErikCH** [comment]
I can look at this. I think I can just use some jQuery and set the focus on the last gh-blognav-line input. After adding a new nav item.
