### ISSUE TITLE
Can't change role for locked users

### ISSUE THREAD

**Issue by kirrg001** [TryGhost/Ghost#8766]
We guess that this is an admin behaviour. 

Steps to reproduce:

1. Import a database or lock a user
2. Try to change a role of a locked user

**If you unlock the user, you can change the role.**

Ghost: master (maybe also LTS)

**Comment by ErisDS** [comment]
I'm pretty sure that this is another incarnation of https://github.com/TryGhost/Ghost/issues/8602?

**Comment by kevinansfield** [comment]
@ErisDS at first glance this looks to be related more to Ghost-Admin as it's the dropdown that is broken rather than getting any errors back from the server.

**Comment by ErisDS** [comment]
I have investigated this a little bit more. It is another incarnation of the need-to-refresh-after-import bug. I am only unable to change a role directly after importing (the role drop down is empty).

After refreshing, I am able to change the role.

**Comment by ErisDS** [comment]
Probably also closely related to #5947?

**Comment by ErisDS** [comment]
Closing due to age & lack of traction.
