### ISSUE TITLE
Ghost Start error

### ISSUE THREAD

**Issue by PhoenixPeca** [TryGhost/Ghost#8769]
Can somebody please tell me why this is happening in my Ubuntu 16.04.2 droplet?

![image](https://user-images.githubusercontent.com/9730242/28723598-d6017a9e-73e9-11e7-9dd2-1a5fe92a1909.png)

On `ghost intall` it works perfectly, but if I restart the server this error shows.

`ghost run` is working well though.

Is this a bug or something?

As for the log:
````
Debug Information:
    Node Version: v6.11.1
    Ghost-CLI Version: 1.0.0
    Environment: production
    Command: 'ghost start'
Error occurred running command: '/bin/sh -c sudo systemctl start ghost_www-spud-cf'

Exit code: 1
````

**Comment by ErisDS** [comment]
Hey there @PhoenixPeca could you please post this over on the https://github.com/TryGhost/Ghost-CLI repository? 

You can also join our [slack](https://ghost.org/slack) channel to talk to someone about what might have happened.

Thanks!
