### ISSUE TITLE
Naviagation issue if Blog URL is set with Upper and Lower case letters

### ISSUE THREAD

**Issue by spieglio** [TryGhost/Ghost#8772]
### Issue Summary

If blog URL is set with upper and lower case letters (e.g. https://MakeItYour.LIFE) the Naviation settings in the Design menu do not work properly.

### Steps to Reproduce

1. Set blog url in config file to be with multiple cases
2. Try to create or change a navigation setting
3. Weird things get appended and replaced

### Technical details:

* Ghost Version: 1.0.2

### Other

Not too serious of a bug. But something that was unexpected for me and could be handled internally I think.

**Comment by ErisDS** [comment]
Hmm... I think the only thing to do here is to validate the url is lowercase when entered in `ghost config`. 

Uppercase domains aren't really a thing - I think this is the first of many problems you'd be likely to encounter configuring your blog this way.

**Comment by spieglio** [comment]
Validating this (or forcing it to be lowercase automatically somewhere) would be fine I think.

**Comment by ErisDS** [comment]
Closing if favour of https://github.com/TryGhost/Ghost-CLI/issues/399
