### ISSUE TITLE
Potential admin panel authentication bypass

### ISSUE THREAD

**Issue by gszathmari** [TryGhost/Ghost#8774]
### Issue Summary

I would like to raise an issue that may have certain security implications as well. 

Long story short, I have migrated to 1.x from 0.99.x by following the instructions in the documentation. When I finished with a fresh install, I visited /admin to create an initial user. Because I already had a `.json` file backup I made with 0.99.x and I already have my own users in the `.json` file. So, I created a dummy user that I was going to delete later once the `.json` file is imported.

So I logged in with the dummy user, imported the .json file and everything was all good. Then I transferred the ownership from the first user (the one I created during the initial setup of 1.x) to my admin user from 0.99.x. I logged in with the owner and removed the first user.

What I was expecting is the dummy user removed and the old user (from 0.99.x) being the owner and having super-administrator privileges.

What happens instead when I visit /admin is that I am redirected to the "Welcome to Ghost" page again instead of the login window to enter my username and password - and I am asked again to create a new user. Now the security implication is that I can create a new user with my chosen password, and then I am allowed to log in as the new user with owner privileges.

Because I still had a valid cookie, I did not notice this behaviour for a day or so, as I was automatically redirected to the admin panel with my valid session in my cookie. Once my session expired, I was supposed to be forwarded to the login page, but I was redirected to the "Welcome to Ghost" page instead. Essentially my blog was left wide-open for a day allowing anyone to register a new user with owner privileges.

### Steps to Reproduce

1. Export config in a .json format from 0.99.x 
2. Install 1.x in a new directory, copy /contents/images as instructed by the documentation
3. Go to /admin and create your first user
4. Log in to the /admin panel
5. Import .json configuration file
6. Transfer ownership from user created at Step 3. to user featuring in the .json file
7. Log in with the new owner in a separate browser window
8. Delete the previous owner created at Step 3 with user from the .json file
9. Log out
10. Visit /admin page
11. Get redirected to /ghost/#/setup/one
12. Create a new user again
13. Voila! You are now logged in as an owner

### Technical details:

* Ghost Version: 1.1 (1.0 had the same issue)
* Node Version: v6.11.1
* Browser/OS: Ubuntu 16.04.2 LTS
* Database: MySQL

**Comment by ErisDS** [comment]
Security issues should be submitted following our security policy listed in the security.md file. irresponsible disclosure is a serious issue and we do not take it lightly.

Further still your report makes no sense, there is no ghost version 0.99 nor a /admin.

Closing this as it should not be on the public repo.

**Comment by gszathmari** [comment]
Wow leave the security vulnerability open then

**Comment by ErisDS** [comment]
No one said that - nor is this a confirmed vulnerability - I'm just not leaving it advertised at the top of our repo whilst we figure it out.

**Comment by ahmad32** [comment]
halah kontol
