### ISSUE TITLE
Using Ghost v1.1.0 with Plesk Onyx

### ISSUE THREAD

**Issue by nilsbrychzy** [TryGhost/Ghost#8777]
I tried to install Ghost to my Plesk Onyx server, but this isn't possible without changing the permissions from the folder where it should be installed. That's a problem when you use a shared Plesk server or your own with others because with the permission change other could access my Ghost installation.

So I tried some times and I did it. Now I posted a blog post on my Ghost v1.1.0 application on Plesk Onyx with a step by step tutorial for installing Ghost on Plesk Onyx.

Perhaps this could be useful for others or even it can be included as a "manual install".

Blog post: https://blog.nls.li/install-ghost-on-plesk/

**Comment by ErisDS** [comment]
@nilsbrychzy, GitHub is for tracking bugs. This really isn't appropriate content. 

See also: https://docs.ghost.org/docs/hosting#section-choose-a-hosting-provider
