### ISSUE TITLE
Issue with Footnotes in Ghost 1.1.0, Casper 2.0.1

### ISSUE THREAD

**Issue by johnnyb2good** [TryGhost/Ghost#8779]
### Issue Summary

In Ghost 1.1.0 with the default Casper 2.0.1 theme, there appears to be issues using footnotes.  I'm not sure if this is more a Ghost issue or a Casper theme issue, so I'll start by posting this here.  The issues are:
* Footnotes using [^n] get created as [1], then subsequently [1:1], [1:2], [1:3], etc, in the body
* Footnotes using explicit numbering, such as [^1], [^2], etc, don't work -- that text is interpreted and shown literally in the body of the article rather than as [1], [2], [3] superscript footnote markers.
* The footnotes for either method ([^n] or [^#]) used in the body of the article don't appear in the footer as they should.

### Technical details:

* Ghost Version: 1.1.0
* Theme: Casper 2.0.1
* Node Version: 6.11.1
* Browser/OS: Ubuntu Linux 16.04
* Database: MySQL 14.14

**Comment by JohnONolan** [comment]
@johnnyb2good 

This is the way to use footnotes in Ghost:

![image](https://user-images.githubusercontent.com/120485/28768079-66b49fb8-75e7-11e7-8a16-52919c9a7e2f.png)

and this is how they render:

![image](https://user-images.githubusercontent.com/120485/28768094-7273ad62-75e7-11e7-8420-5c7e36c7ead0.png)

We use 3rd party Markdown parsers so we pretty much rely on them in terms of what the supported formats are - so not every variation of Markdown (and there are many) will work. If you still think there's a bug do let us know

**Comment by johnnyb2good** [comment]
Hi John.  Thanks for the response.  Should the markdown format for footnotes still be the one described at the Ghost Markdown article that is linked to from within the markdown editor (https://help.ghost.org/hc/en-us/articles/224410728-Markdown-Guide)?  If so there is a bug with the new version of Ghost/Casper.  I have several articles from Ghost 0.11.9 which I've brought over and the footnotes are all not being rendered properly.  If I only use a direct numbering scheme as you have done in your example above, things look like they may be ok -- I'll test that more tonight.  But if I use the [^n] format as described on that Markdown guide and which worked fine in 0.11.x for all my articles, things seems to break.  See a simple [^n] only example that follows in the images but does not render properly.  I've also removed all code injection just in case some JS package was interfering, but the result is still the same.  Thanks for taking a look at this.  John.

![image](https://user-images.githubusercontent.com/20143009/28776594-3e959fc2-75c5-11e7-9a24-30305f2efed1.png)

![image](https://user-images.githubusercontent.com/20143009/28776613-535d1354-75c5-11e7-96a4-6ce73b830a4b.png)

**Comment by johnnyb2good** [comment]
Hi @JohnONolan -- please see the updated comment above.  I think there is a bug.  Do I need to re-open this under a different ticket number, or are these new comments sufficient?
