### ISSUE TITLE
Ghost admin: Deleting initial owner makes initial setup run again

### ISSUE THREAD

**Issue by PhoenixPeca** [TryGhost/Ghost#8781]
As I have mentioned in the title, when you transfer ownership of the blog and delete the initial owner that you have created while first setting up ghost admin, the ghost admin shows the setup page again.

---

This page shows on log-out after I have transferred ownership of my blog to another user and delete the previous/original owner:
![image](https://user-images.githubusercontent.com/9730242/28752561-5883999a-7555-11e7-946c-4ee198e159cd.png)

**Comment by jloh** [comment]
Same as #8774
