### ISSUE TITLE
When activating themes, GScan should be optional to use custom handlebars helper

### ISSUE THREAD

**Issue by seungha-kim** [TryGhost/Ghost#8794]
First of all, I appreciate your awesome works!

### Issue Summary

I wanted to use custom handlebars helper, so installed Ghost via NPM and registered helpers in my index.js. But I can't activate my theme due to fatal error: "Templates must contain valid Handlebars". The error message comes from GScan as I know, so I used that word in title above.

### Steps to Reproduce

Simply use non-ghost helper in template files.

### Technical details:

* Ghost Version: 1.2.0
* Node Version: 6.11.1
* Browser/OS: Manjaro
* Database: SQLite3

**Comment by ErisDS** [comment]
This is not a bug. GScan protects Ghost users from invalid themes. If you hack Ghost, you need to also hack GScan. We're not going to add support in GScan for something we don't support in Ghost!

We'd love it if you came by our #themes channel in [slack](https://ghost.org/slack) and talked to us about your use case for needing a custom helper. That way we can consider whether we're missing a feature and everyone can benefit.
