### ISSUE TITLE
Issue with Footnotes in Ghost 1.1.0, Casper 2.0.1

### ISSUE THREAD

**Issue by johnnyb2good** [TryGhost/Ghost#8802]
Issue Summary

(More of less a copy of #8779 -- screenshots and additional comments added)

In Ghost 1.1.0 with the default Casper 2.0.1 theme, there appears to be issues using footnotes. I'm not sure if this is more a Ghost issue or a Casper theme issue, so I'll start by posting this here. The issues are:

Footnotes using [^n] get created as [1], then subsequently [1:1], [1:2], [1:3], etc, in the body
The footnotes used in the body of the article don't appear in the footer as they should.  I'm following the notation given at the Markdown Guide for Ghost (https://help.ghost.org/hc/en-us/articles/224410728-Markdown-Guide) where [^n] is used for auto-numbering the footnotes.  Several articles I have using footnotes with the [^n] notation from 0.11.9 don't work in 1.1.0 after migration.  I can adapt, but probably the referenced Markdown documentation should be updated if [^n] auto-footnote numbering no longer works as expected.

Technical details:

Ghost Version: 1.1.0
Theme: Casper 2.0.1
Node Version: 6.11.1
Browser/OS: Ubuntu Linux 16.04
Database: MySQL 14.14

See screenshots below:

![](https://user-images.githubusercontent.com/20143009/28776594-3e959fc2-75c5-11e7-9a24-30305f2efed1.png)

![](https://user-images.githubusercontent.com/20143009/28776613-535d1354-75c5-11e7-96a4-6ce73b830a4b.png)

Thanks!

Johnny

**Comment by kevinansfield** [comment]
I believe our documentation needs updating, 1.0 does not have support for auto-numbered footnotes. Supported footnote syntax includes numbered, named, and inline styles:

**Normal footnote:**
```
Here is a footnote reference,[^1] and another.[^longnote]

[^1]: Here is the footnote.

[^longnote]: Here's one with multiple blocks.

    Subsequent paragraphs are indented to show that they
belong to the previous footnote.
```

**Inline footnote:**
```
Here is an inline note.^[Inlines notes are easier to write, since you don't have to pick an identifier and move down to type the note.]
```

We're using the official markdown-it [footnotes plugin](https://github.com/markdown-it/markdown-it-footnote)

**Comment by kevinansfield** [comment]
The [Markdown Guide](https://help.ghost.org/hc/en-us/articles/224410728#footnotes) has been updated to reflect the supported syntax.

**Comment by ErisDS** [comment]
We've updated the markdown guide and added a warning in the migration guide. Think that's all we can do for now :)

**Comment by johnnyb2good** [comment]
Thanks!
