### ISSUE TITLE
2 typos in fixtures.json (omellete and sleak)

### ISSUE THREAD

**Issue by hayley** [TryGhost/Ghost#8806]
https://github.com/TryGhost/Ghost/blob/43336044801c2f31f3bf7929ed73d6338b77edd9/core/server/data/schema/fixtures/fixtures.json#L79

In the sample article on using the ghost editor:

> 3. Make an omellete

omellete should be **omelette**.

Later on:

> Dropping --- on a new line will create a sleak divider, anywhere you want it.

sleak should be **sleek**.

**Comment by kevinansfield** [comment]
Thanks @hayley, good catches! We'll get those fixed in the next release 😄
