### ISSUE TITLE
ghost start fails on Windows

### ISSUE THREAD

**Issue by softcraftsman** [TryGhost/Ghost#8811]
### Issue Summary

After working through the basic installation issues on installing on Windows using "ghost install local", I keep getting these errors when running "ghost start"

### Steps to Reproduce

1. Windows 10  using Administrator command prompt.
2. npm install ghost-cli -g
3. ghost install local
4. ghost start (as part of the install or afterwards)

### Technical details:
C:\Ghost\ghost3>ghost install local
√ Checking system Node.js version
√ Checking current folder permissions
i Checking operating system [skipped]
i Checking MySQL is installed [skipped]
√ Checking for latest Ghost version
√ Setting up install directory
- Downloading and installing Ghost v1.2.0 > Installing dependencies > [4/4] Building fresh packages.\ Downloading and installing Ghost v1.2.0 > Installing dependencies > [4/4] Building fresh packages.| Downloading and installing Ghost v1.2.0 > Installing dependencies > [4/4] Building fresh packages./ Downloading and installing Ghost v1.2.0 > Installing dependencies > [4/4] Building fresh packages.- Downloading and installing Ghost v1.2.0 > Installing dependencies > [4/4] Building fresh packages.\ Downloading and installing Ghost v1.2.0 > Installing dependencies > [4/4] Building fresh packages.| Downloading and installing Ghost v1.2.0 > Installing dependencies > [4/4] Building fresh packages./ Downloading and installing Ghost v1.2.0 > Installing dependencies > [4/4] Building fresh packages.- Downloading and installing Ghost v1.2.0 > Installing dependencies > [4/4] Building fresh packages.\ Downloading and installing Ghost v1.2.0 > Installing dependencies > [4/4] Building fresh packages.| Downloading and installing Ghost v1.2.0 > Installing dependencies > [4/4] Building fresh packages./ Downloading and installing Ghost v1.2.0 > Installing dependencies > [4/4] Building fresh packages.- Downloading and installing Ghost v1.2.0 > Installing dependencies > [4/4] Building fresh packages.\ Downloading and installing Ghost v1.2.0 > Installing dependencies > [4/4] Building fresh packages.| Downloading and installing Ghost v1.2.0 > Installing dependencies > [4/4] Building fresh packages./ Downloading and installing Ghost v1.2.0 > Installing dependencies > [4/4] Building fresh packages.- Downloading and installing Ghost v1.2.0 > Installing dependencies > [4/4] Building fresh packages.√ Downloading and installing Ghost v1.2.0
√ Finishing install process
√ Configuring Ghost
√ Setting up instance
√ Running database migrations
√ Validating config
× Starting Ghost
A GhostError occurred.

Message: Ghost process exited with code: 1

Debug Information:
    Node Version: v6.11.1
    Ghost-CLI Version: 1.0.3
    Environment: development
    Command: 'ghost install local'

Additional log info available in: C:\Users\John\.ghost\logs\ghost-cli-debug-2017-08-01T14_11_46_230Z.log

Debug Information:
    Node Version: v6.11.1
    Ghost-CLI Version: 1.0.3
    Environment: development
    Command: 'ghost install local'
Message: Ghost process exited with code: 1
Stack: Error: Ghost process exited with code: 1
    at ChildProcess.cp.on (C:\Program Files (x86)\Nodist\bin\node_modules\ghost-cli\lib\utils\local-process.js:47:24)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)

**Comment by acburdine** [comment]
Hey @softcraftsman -> this is actually an issue with [Ghost-CLI](https://github.com/TryGhost/Ghost-CLI). Can you re-open this issue there?
