### ISSUE TITLE
Pagination error

### ISSUE THREAD

**Issue by PhoenixPeca** [TryGhost/Ghost#8814]
This is a follow up issue for PR #8129. I am relatively new to node js programming, and I still cant figure things out as was stated in the recommended approach. I would rather leave the issue for you to solve rather than creating multiple PRs that wouldnt be deemed acceptible otherwise. 😬😬😂

**Comment by ErisDS** [comment]
Hi @PhoenixPeca, I'm going to close this for two reasons: 1. It's a serious edgecase, in 4 years you're the only person who has reported it. 2. This issue isn't a proper bug report, anyone reading it wouldn't be able to understand what it's here for, so there's no point me putting the community "fix-wanted" label on it. 

If other people run into this, we can always reopen, but it's highly likely that anyone encountering this as a problem would ever turn up this particular issue with search.
