### ISSUE TITLE
"sendmail" mail.transport isn't working with ghost-cli 1.0.3

### ISSUE THREAD

**Issue by lexpierce** [TryGhost/Ghost#8818]
Ghost 1.0.3 is not validating my existing node mailer config:

```
  "mail": {
    "from": "my@nonsense.email",
    "transport": "sendmail",
    "options": {}
  },
```

This worked for all of ghost, through the beta's and RCs, but is now generating the following error:

[ghost@bananastand ghost]$ ghost start
✖ Validating config
A ConfigError occurred.

Error detected in the production configuration.

Message: false
Configuration Key(s): mail.transport
Current Value(s): sendmail

Help:  Run `ghost config <key> <new value>` for each key to fix the issue.

Debug Information:
    Node Version: v6.11.1
    Ghost-CLI Version: 1.0.3
    Environment: production
    Command: 'ghost start'

Please refer to https://docs.ghost.org/docs/troubleshooting#section-cli-errors for troubleshooting.

**Comment by acburdine** [comment]
as shown here: https://github.com/TryGhost/Ghost-CLI/blob/master/lib/commands/config/advanced.js#L121, if you capitalize "Sendmail", it should work.

I'm pretty sure that list was generated from the NodeMailer 0.7 code, but we can definitely take a look and see if it would work lowercased.

**Comment by acburdine** [comment]
Closed this mainly because this is an issue with Ghost-CLI and not with Ghost itself.
