### ISSUE TITLE
Import content "Choose File" button not working

### ISSUE THREAD

**Issue by Robinyo** [TryGhost/Ghost#8819]
### Issue Summary

The "Choose File" button is not working on Chromium. If I click on the button nothing happens.
Chromium version 59.0.3071.109 (Developer Build) Built on Ubuntu , running on elementary OS 0.3.2 (64-bit)

### Steps to Reproduce

1. Go to Settings > Labs (Import content)
2. Try to click the "Choose File" button

![image](https://user-images.githubusercontent.com/12203540/28855896-1188cee0-7783-11e7-860b-0dfe7d71924d.png)

### Technical details:

* Ghost Version: 1.3.0
* Node Version: v6.11.2
* Browser/OS: Chromium version 59.0.3071.109 (Developer Build) Built on Ubuntu , running on elementary OS 0.3.2 (64-bit)
* Database: MySQL 5.7

**Comment by ErisDS** [comment]
Hi @Robinyo, sorry to hear this isn't working for you, however I think this is likely something extremely specific to your environment. Do other file dialogues work for you? Does your OS understand the mime types specified in the accept attribute?

I'm on Mac OS with Chrome 59.0.3071.115 and the button is working as expected. As your environment is something very rare and extremely difficult to reproduce, it's not something that we would prioritise investigating and fixing. However we would be happy to accept a pull request with a suggested fix.

My preference here is to close this. If there are more reports across more environments we can of course reopen and investigate further.

**Comment by pascalandy** [comment]
I have the same exact issue.

## Technical details:

Ghost Version: 1.5.2
Node Version: v6.11.2
Browser/OS: Chrome  version Version 59.0.3071.115 (Official Build) (64-bit) on mac

**Comment by pascalandy** [comment]
Just re-installed Ghost from scratch. 
It works now on Safari but not in Chrome.

**Comment by Robinyo** [comment]
It's definitely an issue when running Chromium on Elementary OS. As a work around, I just downloaded Firefox and Ghost works as expected :)
I was able to migrate from Ghost 0.x to Ghost 1.x -> https://robferguson.org/blog/

**Comment by SherlockStd** [comment]
Hi !
I have the same issue, here is my setup:
Ghost Version: 1.5.2
Node Version: v6.11.1
Browser: Version 60.0.3112.78 (Official Build) (64-bit)
OS: Linux Ubuntu 17.04
