### ISSUE TITLE
Version checks are too restrictive

### ISSUE THREAD

**Issue by kevinansfield** [TryGhost/Ghost#8821]
With the more frequent releases we've started running into issues with Ghost-Admin development because branches, PRs etc will quite often be on an older minor version which results in `400 Bad Request` errors because the client/server versions don't match.

I think within minor version ranges we should be more permissive. My suggestion:

- no error when client is on an earlier minor version than server (server should only have additions to API which the client can ignore)
- error when client is on a later minor version than server (client will be expecting fields that the server isn't providing)
- always error when the major version is different

**Comment by vivekannan** [comment]
Can use `semver` to enforce the conditions? Also, [here](https://github.com/TryGhost/Ghost/blob/137b8bf973249174984e814e36988f0377bf0e9d/core/server/utils/ghost-version.js#L4-L7)....can I use the `full` version during validation? The `safe` version isn't a valid version as per semver specifications (I believe).
