### ISSUE TITLE
Excerpt words attribute

### ISSUE THREAD

**Issue by NistorCristian** [TryGhost/Ghost#8823]
This isn't an issue ... More like a suggestion/question.

Excerpt's **words** attribute also applies to the new Excerpt field that can be manually added from admin. Would it be a good idea to ignore the **words** attribute when Excerpt is manually added?

### Technical details:

* Ghost Version: 1.3.0

**Comment by ErisDS** [comment]
@NistorCristian Thanks for the report - it was planned that the words and characters attributes should **not** apply when there is a custom excerpt set. The custom excerpt should always be output in its entirety and then fallback to using the words/characters attributes to calculate an automatic excerpt if not set.

A fix for this is being added now :)
