### ISSUE TITLE
upgrade notification link points to install instructions instead of upgrade instructions

### ISSUE THREAD

**Issue by hayley** [TryGhost/Ghost#8825]
https://github.com/TryGhost/Ghost/blob/f5ef8dbb527e2167884bcb22b76c500ce9324493/core/server/admin/controller.js#L30

When there's a new version of ghost, the link at the top of the page points to:
https://docs.ghost.org/v1.0.0/docs/installing-ghost-via-the-cli
but imho, it would be far more helpful if it pointed to:
https://docs.ghost.org/docs/upgrade

**Comment by kirrg001** [comment]
Hey @hayley 👋 

Thanks for your report. Your discovery is definitely correct, we will care about the wrong link as soon as possible.

**Comment by kirrg001** [comment]
Closing. This was fixed in master. 

This is no LTS issue, the link in LTS was correct. Notifications are getting improved via #8871 right now. Thanks again for your report 👋!
