### ISSUE TITLE
Some issues while installing and starting v1.5.0

### ISSUE THREAD

**Issue by ndaidong** [TryGhost/Ghost#8839]
### Issue Summary

I got 3 issues as below:

1, It looks like the process of installation was ended without expectation

![](http://i.imgur.com/yVJN1KD.png)

2, It said "casper" theme is missing out, but that's not true. This theme already exists.

![](http://i.imgur.com/ptEXHgo.png)

3, Default page returns 500 error

![](http://i.imgur.com/S31skUe.png)

### Steps to Reproduce

1. git clone https://github.com/TryGhost/Ghost.git
2. cd Ghost
3. npm run init
4. yarn
5. npm start

Note that, I can go to admin dashboard and do some stuff there as normal. 

### Technical details:

* Ghost Version: v1.5.0, v1.4.0
* Node Version: v8.2.1, v7.6.0, v6.9.0, v6.8.0
* Browser/OS: Linux Mint 18.1, Ubuntu 16.04, Ubuntu 17.10, Alpine 3.6
* Database: SQLite 3

**Comment by ErisDS** [comment]
Ghost doesn't support Node v8: https://docs.ghost.org/docs/supported-node-versions. You need to downgrade and then reinstall. Please follow the correct install guide for your use case: https://docs.ghost.org/docs/getting-started-guide

**Comment by ndaidong** [comment]
Nope. I tested on 4 versions of node.
