### ISSUE TITLE
Syntax errors in minified ghost and vendor javascript files (1.5.0)

### ISSUE THREAD

**Issue by peterhuene** [TryGhost/Ghost#8840]
### Issue Summary

The minified versions of ghost.js and vendor.js contain syntax errors that do not appear to be in the original source files.

### Steps to Reproduce

1. Upgrade to Ghost 1.5.0.
2. Navigate to `http://<blog>/ghost`.

### Expected Behavior

Expected the administration UI to load.

### Actual Behavior

A busy spinner displays and the administration UI never loads due to syntax errors in the javascript files.

Chrome's console displays the following errors:

```
Uncaught SyntaxError: Unexpected string vendor.min-ef57d9aa96a4e5a314d97158a9adc339.js:23
Uncaught SyntaxError: Unexpected string ghost.min-64de773f4ee0a0157a4c58644682d13e.js:150 
```

The source at these locations have unexpected string literals in the middle of the expressions.  For example, the following is the error in the above ghost.min:

```javascript
{var e=this._editor.codemirror"spell-checker"===e.getOption("mode")? ...
```

Note the unexpected `"spell-checker"` string literal in the middle of the expression.

I've downloaded the [1.5.0 zip file](https://github.com/TryGhost/Ghost/releases/download/1.5.0/Ghost-1.5.0.zip) and found the corresponding syntax errors present in the specified files.

Is there a reason why there are two different minified versions of both ghost.js and vendor.js in `core/built/assets`?

### Technical details:

* Ghost Version: 1.5.0
* Node Version: 6.10.3
* Browser/OS: Chrome 60.0.3112.90 (64-bit), Arch Linux
* Database: MySQL

**Comment by vikaspotluri123** [comment]
It's probably because you're using cloudflare - check out the [Ghost Admin not loading](https://docs.ghost.org/docs/troubleshooting#section-ghost-admin-not-loading) section in the troubleshooting docs

**Comment by peterhuene** [comment]
Exactly right.  Thanks for the info, I'll close in favor of following the documentation.

**Comment by peterhuene** [comment]
Still, I do wonder if there's a way to minifiy this *without* relying on implicit semicolons on newlines so if CDNs do modify it (for whatever reason) it doesn't break.

**Comment by ErisDS** [comment]
@peterhuene that'd require going through every dependency using that pattern and submitting patches upstream, getting them merged and hoping there are no regressions So, there is a way, but it's not something we're going to do or what I would call realistic.

The other way to look at this is, when you enabled Cloudflare's performance feature, you enabled a set of tools that are designed for improving the performance of websites. Works great and _highly_ recommended for your publication, but `/ghost/` is a fully-fledged web application, and CloudFlare's tools are not suitable for this case.

**Comment by peterhuene** [comment]
Is the production of the minified javascript assets not under Ghost's control?  I am ignorant of Ghost's build process, but given that the minified assets exist in the release .zip, I assume it is Ghost's build process producing these assets.

This particular issue arises because it seems the minified versions omit semicolons in places where it can, resulting in files that, when minimized again by a CDN, produce syntax errors.  Presumably if the original minification did not omit the semicolons, the CDNs modifications would not introduce syntax errors.

**Comment by ErisDS** [comment]
> when minimized again by a CDN

Optimising for people re-minifying our already minified files is not a use case that the Ghost team is going to spend time on right now. If you're feeling inclined to work through the problem, please do - we're more than happy for PRs.

**Comment by peterhuene** [comment]
I completely understand not prioritizing an issue like this one and I'll see if I can work on the issue if I get a spare cycle (low confidence of that happening at the moment, though).

I very much appreciate your time and the clear and concise documentation, so it's definitely not hard to work around this issue.
