### ISSUE TITLE
Help! :D can't login to ghost after update 

### ISSUE THREAD

**Issue by Darklight11** [TryGhost/Ghost#8842]
I update on the ghost cli, all fine and then when I want to go to www.treipuncte.info/gost is showing a infinite loop and not able to enter admin's page :(( pls help.

1. This is the first step update from 1.1.0
2. This is the second step, etc. update on with putty, thru cli ghost on my 1gb vds 3 cores.

* Ghost Version: 1.5.0
* Node Version:6
* Browser/OS: chrome, all, windows 7 and android phone 6 vers.
* Database: mysql

**Comment by vikaspotluri123** [comment]
- `/ghost/` should be whitelisted from caching on cloudflare ([ref](https://docs.ghost.org/docs/troubleshooting#section-ghost-admin-not-loading))
- It's working fine for me!

**Comment by Darklight11** [comment]
No, not working tryed with cloud flare , hm ? What else :(( ... :D ... can I do? Thnaks for answear :D ...

**Comment by vikaspotluri123** [comment]
I don't want to have a conversation via issues - As the issue template says...

> Do you need help or have a question? Please come chat in Slack: https://ghost.org/slack 👫.

**Comment by Darklight11** [comment]
Ok, thanks , I did it, I SO happy it works after a while, with a freash browser install of firefox, I was on the chrome, on chrome not working the admin on firefox did :)), Thanks a lot , Sir! Well done!

**Comment by acburdine** [comment]
Going to close this as it seems to be a browser-specific caching issue - it can be reopened if something's actually going wrong with Ghost itself 🙂
