### ISSUE TITLE
Postgres unsupported on Ghost 1.x?

### ISSUE THREAD

**Issue by ImKcat** [TryGhost/Ghost#8844]
In the lastest version Ghost 1.5, the package.json has include MYSQL and sqlite3 dependencies already, but not include postgres
Ghost 0.11.x is support postgres, why Ghost 1.x not support?

**Comment by AileenCGN** [comment]
Closing this, as it's not an issue. @ImKcat you can read [here](https://dev.ghost.org/dropping-support-for-postgresql/) about the reasons PostgresSQL is not supported anymore.

**Comment by ImKcat** [comment]
@AileenCGN Thanks, not read that post before :)

**Comment by jalberto** [comment]
the link is dead

**Comment by ErisDS** [comment]
Fixed.
