### ISSUE TITLE
In the Stories view relative paths are not rendered correctly

### ISSUE THREAD

**Issue by Robinyo** [TryGhost/Ghost#8845]
### Issue Summary
In the **Stories** view relative paths are not rendered correctly:

![image](https://user-images.githubusercontent.com/12203540/28993303-8cd1b07e-79f6-11e7-8ad5-6c98ae0736fd.png)

For example: /blog/blog/2017/03/23/getting-started-with-apache-sling/

In the Editor:
![image](https://user-images.githubusercontent.com/12203540/28993371-0d3b3838-79f8-11e7-8804-74b035378ae7.png)

For example: /blog/2017/03/23/getting-started-with-apache-sling/

### Technical details:

* Ghost Version: 1.5.0
* Node Version: v6.11.2
* Server OS: Ubuntu 16.04
* Client OS: Elementary OS 0.3.2 (64-bit)
* Client Browser: Firefox 54.0 (64-bit)
* Database: MySQL 5.7

**config.production.json**:

```
{
  "url": "http://robferguson.org/blog",
  ...
  "paths": {
    "contentPath": "/var/www/ghost/blog/content"
  }
}
```

**nginx config**:

```
server {
  listen 80;
  listen [::]:80;

  ...

  location ^~ /blog {
    proxy_set_header HOST $host;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-NginX-Proxy true;

    proxy_pass       http://127.0.0.1:2368;
    proxy_redirect   off;
  }
}
```

**Comment by ErisDS** [comment]
Picked this up as I know what is causing it. The output in Ghost-Admin is being generated from the new plaintext format. When I setup the html-to-text conversion, I added a line that tries to handle URLs, but it's adding the subdirectory to the path, which the content already has otherwise it wouldn't be a working URL.

PR incoming
