### ISSUE TITLE
Ghost Restart Hangs

### ISSUE THREAD

**Issue by effinspiders** [TryGhost/Ghost#8846]
Issue Summary

"Ghost Restart" command hangs and does not complete.

Steps to Reproduce

From the installation directory of Ghost - run the "ghost restart" command.
The following message will display:
"Running sudo command: systemctl restart ghost_www-xxxxxxxxxxxx
☱ Restarting Ghost"

Technical details:

Ghost version: v1.5.0
Node Version: v6.11.2
Browner/OS: Ubuntu 16.04.2 (Digital Ocean Droplet)
Database: Mysql

Apologies in advance if this isn't a bug but caused by another issue with my droplet.

**Comment by effinspiders** [comment]
**Issue Summary**

"Ghost Restart" command hangs and does not complete.

**Steps to Reproduce**

1. From the installation directory of Ghost - run the "ghost restart" command.

The following message will display:
"Running sudo command: systemctl restart ghost_www-xxxxxxxxxxxx
☱ Restarting Ghost"

Technical details:

Ghost version: v1.5.0
Node Version: v6.11.2
Browner/OS: Ubuntu 16.04.2 (Digital Ocean Droplet)
Database: Mysql

Apologies in advance if this isn't a bug but caused by another issue with my droplet.

**Comment by PhoenixPeca** [comment]
Hi @effinspiders!

Maybe were facing the same issue? I have installed ghost in a bock storage but it kind of fails on restart too.

**Comment by ErisDS** [comment]
Hi @effinspiders, please visit the https://github.com/TryGhost/Ghost-CLI repo, search the issues there and if your problem doesn't look like one of the open issues, then re-open this there.
