### ISSUE TITLE
/ghost admin page doesnt load

### ISSUE THREAD

**Issue by kaiserhase** [TryGhost/Ghost#8849]
### Issue Summary

Can't get login page at /ghost . All I get is a continuous loading circle.

### Steps to Reproduce

1. www.builtbygoat.com/ghost ... Can't really explain any other way to reproduce

### Technical details:

* Ghost Version: Started 1.3.0 (upgraded 1.5.0 issue still persists)
* Node Version: 3.10.10 (ran npm -update as well to verify latest)
* Browser/OS: Windows 10 (RS3)
* Database: MySql 14.14 Distrib 5.7.19

Cleared Cloudflare cache, cleared browser cache, ran CCleaner, restarted server, restarted ghost. Originally installed Ghost on a fresh Digital Ocean droplet (with all recommendations/steps followed in install docs). Ghost error log only shows 404 errors from bots trying to crawl pages that were deleted long ago.

**Comment by ErisDS** [comment]
Please use [slack](https://ghost.org/slack) for support https://docs.ghost.org/docs/troubleshooting#section-ghost-admin-not-loading
