### ISSUE TITLE
How to completely disable all logs?

### ISSUE THREAD

**Issue by loskiq** [TryGhost/Ghost#8852]
How to completely disable all logs?

### Technical details:

* Ghost Version: 1.5.0
* Node Version: 6.11.2
* Browser/OS: Google Chrome
* Database: MySQL

**Comment by ErisDS** [comment]
@loskiq Please stop with the 1-line issues. Read our [contributing guide](https://github.com/TryGhost/Ghost/blob/master/.github/SUPPORT.md) and respect the rules.
