### ISSUE TITLE
Error migrating

### ISSUE THREAD

**Issue by yaglol** [TryGhost/Ghost#8853]
Im currently trying to migrate my blog from Ghost 0.11.xx to 1.5.0 using the Ghost-CLI, wich worked fine setting up and installing  with yarn. 

Im currently running Debian 8 on my webserver, with the latest version of Ghost CLI and Ghost. 

This is the error i get after passing all other sequences of the "Ghost setup" command. 

> ✔ Running database migrations
> ? Do you want to start Ghost? Yes
> ✔ Validating config
> Running sudo command: systemctl start ghost_yaglol-com
> ✔ Starting Ghost
> Running sudo command: systemctl enable ghost_yaglol-com --quiet
> ☱ Starting GhostFailed to execute operation: No such file or directory
> ✖ Starting Ghost
> A ProcessError occurred.
> 
> Error occurred running command: '/bin/sh -c sudo systemctl enable ghost_yaglol-com --quiet'
> 
> Exit code: 1
> 
> 
> Debug Information:
>     Node Version: v6.11.2
>     Ghost-CLI Version: 1.0.3
>     Environment: production
>     Command: 'ghost setup'
> 
> Additional log info available in: /home/yag/.ghost/logs/ghost-cli-debug-2017-08-06T11_53_53_472Z.log
> 

The error log just says the same thing as above. 

Also when going to my site, i get a 500 error. 

> 500 — select count(distinct posts.id) as aggregate from &quot;posts&quot; where &quot;posts&quot;.&quot;status&quot; &#x3D; &#x27;published&#x27; and &quot;posts&quot;.&quot;page&quot; &#x3D; false - SQLITE_ERROR: no such table: posts

**Comment by ErisDS** [comment]
Please **do not** use GitHub for support. Read our [support guide](https://github.com/TryGhost/Ghost/blob/master/.github/SUPPORT.md).
