### ISSUE TITLE
Unable to access the admin page

### ISSUE THREAD

**Issue by Fleey** [TryGhost/Ghost#8860]
Unable to access the admin page

![img-1](http://images-10010175.file.myqcloud.com/QQ%E6%88%AA%E5%9B%BE20170809200309.png)

![img-2](http://images-10010175.file.myqcloud.com/QQ%E6%88%AA%E5%9B%BE20170809200845.png)

## Server environment

System : Debain 8
Node  : 6.11.2
Ghost : 1.5.1
Browser : chrome  60.0.3112.78

**Comment by ErisDS** [comment]
Please **do not** use GitHub for support. Read our [support guide](https://github.com/TryGhost/Ghost/blob/master/.github/SUPPORT.md).
