### ISSUE TITLE
Safely 404 for images

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#8868]
As a result of https://github.com/TryGhost/Ghost/commit/147ec911620148ad735a629849907cc9910ae35b, if an image that is referenced in your error template 404s, you will get infinite 404 errors.

Similarly, if you have lots of resource-based 404 errors and are using Casper, which uses the {{#get}} helper on the error page, you'll end up with a really large number of database requests all of a sudden.

Reproduction Case 1 - Infinite 404s

- Set your blog logo to a content/images path that doesn't exist
- Use a theme that calls `ghost_head` in error.hbs (or modify casper to add this)
- Visit a page that 404s
- See the endless 404 errors in your stdout

Plan of action:

- [x] put guards in place to not render templates as a 404 response to a 404ing resource request
- [x] change Casper to have an explicit 404 error template, and less fancy fallback error template
- further improvements to the image size utilities, to try to guard against multiple requests:
    - [x] the image size utility has been upgraded to support ICO, so we should upgrade as well
    - [x] add got as a dependency for network requests. 
    - [x] we really need to only do network requests for things that aren't in local storage
    - [ ] ideally, if a request is already being made, we need a way to wait for that request, rather than making multiple requests for the same file - not 100% on the best approach for that.
- [x] improve logic around theme error templates:
      - split our HTML error renderer into a "theme error renderer" and a "general error renderer"
- [ ] rework guard to use extensions
- [ ] look at adding more cases of explicit fallthrough of static resources
- [ ] if "code" in error templates is meant to be deprecated, actually deprecate it (remove it from the default theme, mention this in the docs)
- [ ] document error templates properly in themes.ghost.org

**Comment by kirrg001** [comment]
> As a result of 147ec91, if an image that is referenced in your error template 404s, you will get infinite 404 errors.

The behaviour is not caused by https://github.com/TryGhost/Ghost/commit/147ec911620148ad735a629849907cc9910ae35b, it was there before.

**Comment by ErisDS** [comment]
>  further improvements to the image size utilities, to try to guard against multiple requests

Have looked at how to approach this, however I think it would need a deeper rework. 

@AileenCGN some things to add into your planning around refactoring meta data:
- the image size utility has been upgraded to support ICO, so we should upgrade as well
- it's OK in my opinion to add [got](https://github.com/sindresorhus/got) as a dependency for network requests. See https://github.com/TryGhost/Ignition/issues/41 - if we use `got` in a few places, we may be able to abstract out a generalised util into ignition, but I'm not sure if it makes sense to start there 🤔 
- we really need to only do network requests for things that aren't in localStorage, for localStorage we should use .read() if possible at all 🤔 🤔 
- ideally, if a request is already being made, we need a way to wait for that request, rather than making multiple requests for the same file - not 100% on the best approach for that.

**Comment by AileenCGN** [comment]
Thanks for the info, @ErisDS! Will look into these issues and include them in the refactor spec.

**Comment by ErisDS** [comment]
The bug part of this is resolved, so I've changed the labels & title to reflect what's left.

**Comment by ErisDS** [comment]
There's a really horrible bug here at the moment - if your admin hasn't been built recently, or at all, you'll get heaps of errors like:

> MESSAGE: Failed to lookup view "error-404" in views directory 

This happens because the default theme has an error-404 template, and the error renderer gets confused thinking it can render this for the admin panel, which it cannot.

**Comment by kirrg001** [comment]
@ErisDS can't reproduce 🤔

**Comment by kirrg001** [comment]
@ErisDS never mind, just saw https://github.com/TryGhost/Ghost/commit/bcf6e9f5174fff0a5fc3a79adde167efc99c7df7 👍
