### ISSUE TITLE
Subscribers table is broken on mobile

### ISSUE THREAD

**Issue by triestpa** [TryGhost/Ghost#8894]
### Issue Summary

On narrow screens, the table of subscribers in the admin UI is unreadable.  The problem seems to be that no minimum-width is set for the "Email Address" column, so as the screen gets narrow the "Subscription Date" column collapses into the "Email Address" column, and the text becomes overlayed.

I would usually post a screenshot to demonstrate, but it seems best to not reveal private email addresses, even if they are mostly obscurred by the date column.

### Steps to Reproduce

1. Open the Admin UI on a smaller screen (under 600px wide)
2. Make sure that the "Subscribers" feature is enabled in Labs, and that the site has a few subscribers.
2. Navigate to the "Subscribers" page from the side menu.

### Technical details:

* Ghost Version:  1.5.2
* Node Version: 6
* Environment: production
* Browser/OS: Ubuntu 16.04
* Database: sqlite3

**Comment by kevinansfield** [comment]
Hi @triestpa 👋 Thanks for the report, however there are a number of known minor issues with subscribers layout, especially with mobile. We're not currently tracking them as the entire screen will be revisited as part of a larger re-work of subscribers.
