### ISSUE TITLE
Code Injection input renders double scrollbar and hides text

### ISSUE THREAD

**Issue by mariangibala** [TryGhost/Ghost#8896]
### Issue Summary

Code Injection input area has some rendering issues. It does not display full text and creates two horizontal scrollbars. 

![ghost-textarea-scroll-bug](https://user-images.githubusercontent.com/6449605/29294124-171a422e-814e-11e7-94da-ada838e78d63.jpg)

### Technical details:

* Ghost Version: 1.5.2
* OS: Windows 10 Home
* Browser: Firefox 54.0.1, Chrome 60.0.3112.90, Microsoft Edge 40.15063.0.0

**Comment by kkavita92** [comment]
Happy to work on this!

**Comment by bdbch** [comment]
I'll also take a look and figure out if I can fix it.
