### ISSUE TITLE
Focus does not move to https:// when link shortcut used

### ISSUE THREAD

**Issue by frantzypants** [TryGhost/Ghost#8904]
### Issue Summary

When highlighting text within the editor to link, then using the shortcut to insert a link on the highlighted text, Ghost does not shift the highlight focus to the `http://`, but remains on the highlighted text.

### Steps to Reproduce

1. Copy the text to be linked
2. Do shortcut to insert link (Ctrl/⌘ + K)
3. Focus does not move to http://, but stays on highlighted text

### Technical details:

* Ghost Version: 1
* Browser/OS: Any browser/OS

**Comment by kevinansfield** [comment]
Closing as the primary editor has been replaced.
