### ISSUE TITLE
body_class is not a proper value

### ISSUE THREAD

**Issue by ktabori** [TryGhost/Ghost#8907]
### Issue Summary

Since I upgraded to the latest Ghost 1.6.0 the {{body_class}} is not a proper value longer.

### Steps to Reproduce

1. Navigate to author or tags page 
2. Check the class of the body (it should be ".tag-template, .tag-:slug" or ".author-template, .author-:slug")

### Technical details:

* Ghost Version: 1.6.0
* Node Version: v6.11.1
* Browser/OS: Chrome latest
* Database: MySQL

**Comment by ErisDS** [comment]
Sorry about this, it's actually the same as #8908. A fix has been prepared, and will be released very soon.
