### ISSUE TITLE
{{#is}} helper bug - invalid "index" context evaluation

### ISSUE THREAD

**Issue by zblesk** [TryGhost/Ghost#8908]
### Issue Summary

After upgrade to Ghost 1.6.0, the #is helper doesn't interpret the "index" context properly.

### Steps to Reproduce

1. Update Ghost to 1.6.0
2. Reload the page

Up until 1.5.2, my theme worked well. The code in its entirety in a .hbs file looks like this:

```
<link
  rel="stylesheet"
  type="text/css"
  {{#is "index, tag"}}
    href="{{asset 'css/index.css'}}"
  {{/is}}
  {{#is "post, page"}}
    href="{{asset 'css/post.css'}}"
  {{/is}}
 />
<link href='https://fonts.googleapis.com/css?family=Raleway:300' rel='stylesheet' type='text/css'/>
<link type="text/css" rel="stylesheet" href="{{asset 'css/fontello.css'}}"/>
<link type="text/css" rel="stylesheet" href="{{asset 'css/prism.css'}}"/>
```

Relevant are these lines:

```
  {{#is "index, tag"}}
    href="{{asset 'css/index.css'}}"
  {{/is}}
```

According to [spec](https://themes.ghost.org/docs/is), `index` is *"true for the main post listing, including the home page"*. After update to 1.6.0, CSS on my home page no longer rendered. (Posts rendered fine, no change there.)

After examining the generated HTML, I found the "href" attribute remained empty. That made me think maybe the #if expression didn't match anything. 
After I'd explicitly added `home', the expression matched correctly. I.e. the fix looked like this: 

```
  {{#is "home, index, tag"}}
    href="{{asset 'css/index.css'}}"
  {{/is}}
```

**Why I think it's a bug:** According to the spec, it seems `index` should also cover `home`, and adding it explicitly should not be necessary.

### Technical details:

* Ghost Version: 1.6.0
* Node Version: 6.11.2
* Browser/OS: irrelevant
* Database: MySQL (irrelevant, presumably)

**Comment by oschade** [comment]
The context "author" doesn't work either.

**Comment by ErisDS** [comment]
Sorry about this, it's actually the same as #8907. A fix has been prepared, and will be released very soon.
