### ISSUE TITLE
Change adminUrl

### ISSUE THREAD

**Issue by jacinto123** [TryGhost/Ghost#8913]
### Issue Summary

Trying to change the adminUrl, as described in the docs on this page:
https://docs.ghost.org/docs/config

### Steps to Reproduce

1. add adminUrl
2. try going to that adminUrl
3. shows 404 and the /ghost url still works

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

### Technical details:

* Ghost Version: 1.6.1
* Node Version: v6.11.2
* Database: mysql

**Comment by ErisDS** [comment]
Hi @jacinto123, this sounds like a misunderstanding of what adminUrl does, or else a misconfiguration. I've updated the configuration docs with a bit more information, hopefully this helps. If you need further support please follow our [support guide](https://github.com/TryGhost/Ghost/blob/master/.github/SUPPORT.md).

**Comment by jacinto123** [comment]
Thanks @ErisDS for the clarification. Is this something planed?
