### ISSUE TITLE
issues with production install

### ISSUE THREAD

**Issue by leonhatori** [TryGhost/Ghost#8914]
**guys, I am having the following issue when I try to install on my EC2 instance.  ANY IDEAS?**

/var/www/ghost# npm install --production
npm WARN deprecated nodemailer@0.7.1: All versions below 4.0.1 of Nodemailer are deprecated. See https://nodemailer.com/status/
npm WARN deprecated mimelib@0.2.19: This module is deprecated
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead

> dtrace-provider@0.8.5 install /var/www/ghost/node_modules/ghost-ignition/node_modules/bunyan/node_modules/dtrace-provider
> node scripts/install.js

sh: 1: node: Permission denied
npm WARN optional dep failed, continuing dtrace-provider@0.8.5

> jsonpath@0.2.12 postinstall /var/www/ghost/node_modules/jsonpath
> node lib/aesprim.js > generated/aesprim-browser.js

sh: 1: node: Permission denied
-
> sqlite3@3.1.8 install /var/www/ghost/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

/usr/bin/env: ‘node’: Permission denied
npm WARN optional dep failed, continuing sqlite3@3.1.8

> bookshelf@0.10.3 postinstall /var/www/ghost/node_modules/bookshelf
> node ./scripts/build.js lib "npm run build"

sh: 1: node: Permission denied
npm ERR! Linux 4.4.0-1022-aws
npm ERR! argv "/root/.nvm/versions/node/v4.8.4/bin/node" "/root/.nvm/versions/node/v4.8.4/bin/npm" "install" "--production"
npm ERR! node v4.8.4
npm ERR! npm  v2.15.11
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! jsonpath@0.2.12 postinstall: `node lib/aesprim.js > generated/aesprim-browser.js`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the jsonpath@0.2.12 postinstall script 'node lib/aesprim.js > generated/aesprim-browser.js'.
npm ERR! This is most likely a problem with the jsonpath package,

**Comment by vikaspotluri123** [comment]
Looks like a question for the [slack channel](https://slack.ghost.org) according to the [support guidelines](https://github.com/TryGhost/Ghost/blob/master/.github/SUPPORT.md)
