### ISSUE TITLE
Published date missing from content list

### ISSUE THREAD

**Issue by frantzypants** [TryGhost/Ghost#8917]
In Ghost 1.x there is no way to see the date of a published post or draft unless you actually click into the post itself. You can only see when a post was 'last edited.'

![screen shot 2017-08-17 at 1 21 55 pm](https://user-images.githubusercontent.com/6034248/29424815-13111434-834f-11e7-8f4c-2b15c05171e0.png)

**Comment by parkerproject** [comment]
This is very important because editors or writers should be able to list on the list at a glance the dates of each post. It was there on the previous version.

**Comment by parkerproject** [comment]
I think this should to both publish and scheduled stories

**Comment by parkerproject** [comment]
If you are using moment to format the date, I believe you currently using this format `moment(date).startOf('day').fromNow();`
change it to something like `moment(date).format("MMM Do YYYY")`

**Comment by sethlilly** [comment]
@kevinansfield I'm happy to take a shot at designing and implementing this.

**Comment by kirrg001** [comment]
cc @JohnONolan

**Comment by parkerproject** [comment]
@kevinansfield any update

**Comment by JohnONolan** [comment]
This is a bug. Correct behaviour is:

- **Draft** by **Sarah Frantz** — Last edited `$draftDate`
- **Scheduled** by **Sarah Frantz** — Will go live `$scheduledDate`
- **Published** by **Sarah Frantz** — `$publishedDate`

### $draftDate possible values

- 2 minutes ago (if under 1 hour)
- 3 hours ago (if under 24 hours)
- yesterday (if under 48 hours)
- 12 Aug 2017 (else)

### $scheduledDate possible values

These values should always be `color: var(--green);`

- in **2 minutes** (less than 15 mins)
- at 13:32 **Today** (more than 15 mins away, date = today)
- at 13:32 **Tomorrow** (date = tomorrow)
- at 13:32 on **12 Sep 2017** (date > tomorrow)

### $publishedDate possible values

- 2 minutes ago (less than 15 mins)
- 13:32 **Today** (more than 15 mins away, date = today)
- 13:32 **Yesterday** (date = yesterday)
- 12 Sep 2017 (else)

**Comment by parkerproject** [comment]
@kirrg001 @acburdine it looks like your fix as affected the "Last seen date" on the team members page in the admin

**Comment by acburdine** [comment]
@parkerproject I don't know if this fix specifically affected that - it may have been broken before. I'll investigate it.

**Comment by parkerproject** [comment]
@acburdine thanks
