### ISSUE TITLE
Knex-migrator could not be found

### ISSUE THREAD

**Issue by Ugarz** [TryGhost/Ghost#8926]
Hello,

### Issue Summary
Ghost does not seems to find `knex-migrator` wich is installed in global mode with node 6.9.0 (according to the Ghost documentation).

### Steps to Reproduce
Be on Windows with WSL (Windows Subsystem Linux, also named as "Bash on Ubuntu on Windows").
1. Download a Ghost package
2. `cd` in root project directory and `npm install && npm run dev`

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?
I expected `knex-migrator` to be in `dev-dependencies` not a global dependency. Futhermore, I was expecting to run Ghost without this error with it installed globally.

### Technical details:

* Ghost Version: 1.5.1
* Node Version: 6.2
* Browser/OS: Chrome (60.0.3112.101)
* Database: none yet (but sqlite3 i guess)

**Comment by kevinansfield** [comment]
Hey @Ugarz 👋 this is not a bug, `knex-migrator` is intentionally not in the dev dependencies and should be installed as a global package.

`npm install && npm run dev` is missing a number of install steps if you are attempting to install from a package zip (no longer the recommended install procedure), for install instructions please see https://docs.ghost.org/docs/getting-started-guide and choose the install type you want to use.
