### ISSUE TITLE
Inline code block `code` in footer notes ends up emitting undefined in HTML

### ISSUE THREAD

**Issue by VivekRagunathan** [TryGhost/Ghost#8929]
### Technical details:

* Ghost Version: 0.11.9
* Node Version: 6.11.2

Try this in the editor

```
[^1]: Using `try`-`catch` and everything does silent .....
```

and check in the browser. You should be seeing `undefined` on a new line in place of `try`-`catch`.

Is this a known issue? If so, is there a workaround? Or an upgrade to newer version fixes this?

**Comment by kevinansfield** [comment]
Hey @VivekRagunathan unfortunately this is a known issue with the markdown parser in 0.x.x. It's fixed in 1.x.x.
