### ISSUE TITLE
Can't override the default location of the config.production.json file

### ISSUE THREAD

**Issue by commanderfun** [TryGhost/Ghost#8931]
There doesn't seem to be any way to tell Ghost where to look for the **config.production.json** file other than in it's default location at the root of the ghost installation directory.

I'm running Ghost in Docker. The official Ghost Docker image exposes a volume that maps to the content directory. I need a way to put my config file in that directory so my configuration can be stored in a GitHub repo instead of "baked" into the Docker image. i.e. the only way to change something like the database connection now is to SSH into the docker container and manually edit the config file.

**Comment by kevinansfield** [comment]
@commanderfun if you have an environment where config files don't make sense then the recommended approach is to use [env variables](https://docs.ghost.org/docs#section-running-ghost-with-config-env-variables), I believe this is the approach others have been using with Docker.

Note that the "official" Docker image has just been named that by someone at Docker - it's not supported by us and is not the recommended way to run Ghost.

If you have any questions about installing or running Ghost please use our [Slack channel](https://slack.ghost.org) - we use GitHub solely for bug tracking and feature development. Thanks! 😄
