### ISSUE TITLE
Deliver content payload to slack webhook

### ISSUE THREAD

**Issue by JohnONolan** [TryGhost/Ghost#8936]
Currently if you integrate a "private" blog w/ Slack - then it will post the URL to your slack channel. Problem is that if the blog is private, there will be no unfurl, cause the URL has no publicly accessible data.

Would it be possible / make more sense - for the Webhooks which Ghost sends to Slack to include the usual unfurl content? So image / desc / author / etc?

If it's an easy enhancement, think it would be nice. If it's not, feel free to close.

**Comment by sethlilly** [comment]
@JohnONolan, I'm working on this.

**Comment by sethlilly** [comment]
Hi all! Just wanted to drop in with a quick update. The work on this is coming along, I'd say about 70 -75% done.

Still remaining:

- [ ] Author data for the post
- [ ] Privacy reminder (I'll explain with the PR)
- [ ] Unit tests

I intend to finish this in the next couple days.

**Comment by sethlilly** [comment]
Hello everyone! Work got a little busy and we just had Labor Day weekend in the US, so I'm a bit behind but this is still coming. Didn't want to let the day pass without an update. Thanks for your patience!

**Comment by JohnONolan** [comment]
@sethlilly Did you ever get any further with this? Would love to use it 🤓

**Comment by kirrg001** [comment]
@sethlilly Thanks for your help 🙌🏻

**Comment by lunaticmonk** [comment]
@JohnONolan If it is okay, should I send the pull request? I have completed partial work on it.

**Comment by JohnONolan** [comment]
lgtm 👍

**Comment by lunaticmonk** [comment]
Cool. Will open a PR for this one.
