### ISSUE TITLE
Internal tags are not marked as "internal" when added via the PSM

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#8943]
If you add a tag which starts with a hash via the PSM, it does not get marked "internal". Instead, it gets marked as public. 

If you add a tag which starts with a hash via the tag settings page, or if you the name of a tag which should have been internal, it gets correctly marked as internal.

### Steps to Reproduce

1. Open any post
2. Add a brand-new tag which starts with a hash
3. Visit the tag settings page, and see that your new tag is not internal
4. Edit the name of the tag on the tag settings page, see the internal label pop up
5. Try adding a new internal tag on the tag settings page, see the internal label appear

Note: The UI is accurately reflecting the database. The problem is that the tag's visibility property is not being set to "internal" before being sent to the server.

We probably need to consider adding logic to both the client AND server to make sure this behaves as expected. Originally I believe it was only implemented client side?

### Technical details:

* Ghost Version: master

**Comment by kevinansfield** [comment]
We probably need to consider adding logic to both the client AND server to make sure this behaves as expected. Originally I believe it was only implemented client side?

@kirrg001 the client-side fix is done, there's still no server-side logic for making new #tags "internal" when they are created. Shall we keep this issue open or open a new one with details of the server-side changes required?

**Comment by kirrg001** [comment]
> @kirrg001 the client-side fix is done, there's still no server-side logic for making new #tags "internal" when they are created. Shall we keep this issue open or open a new one with details of the server-side changes required?

Yeah let's keep it open. Will look into a server side protection asap.
