### ISSUE TITLE
Frequent high CPU usage

### ISSUE THREAD

**Issue by tejasjadhav** [TryGhost/Ghost#8944]
I've using Ghost since the non-CLI version and was quite content. A month back, I installed Ghost CLI and updated to the new version (1.3.0). It was all fine until one day I got an email from my VPS as I was using excessive CPU and when I checked, Ghost was the culprit. It had frequent 100% CPU spikes. I upgraded to the newer version yesterday (1.7.0) but the problem still persists.

Can you explain what might be causing this high CPU spike? Tell me if you need more details which I can provide.

**Ghost version:** 1.7.0
**Ghost CLI version:** 1.1.1.
**Database:** SQLite3
**Operating system:** Ubuntu 16.04
**Node version:** 6.11.0

**Comment by acburdine** [comment]
The only things I could think from a CLI perspective that could cause such a CPU spike are:

1) The SSL dhparam generation - if you use the CLI to set up SSL it generates a 2048-bit "dhparam" encryption key. This process is highly CPU intensive _but_ only happens once, when you initially set up SSL. (meaning updating your ghost version wouldn't trigger this)
2) updating runs `yarn install` to get the latest version of ghost - I'm not 100% sure if yarn eats up a lot of CPU, I know it uses a decent amount of RAM but I'd have to investigate further into that.

**Comment by tejasjadhav** [comment]
The problem seems to have gone all of a sudden. If it pops up again, I'll post a screenshot of the `top` command.

**Comment by AileenCGN** [comment]
Closing this for now. If this issue turns up again, please feel free to reopen it again with more information (if available), @tejasjadhav

**Comment by ErisDS** [comment]
I meant to reply to this last week sorry. We manage many blogs internally and have not seen this behaviour. That doesn't mean it doesn't exist, but does point to a very blog-specific environment or traffic problem. If it does come back, you'll need to do enough debugging from the logs etc to figure out what is causing it or what the spikes correlate or coincide with. 

Unfortunately without a reproduction case, given that we don't see this behaviour, it's almost impossible for us to do anything about it.
