### ISSUE TITLE
Ghost stories don't handle embedded code correctly

### ISSUE THREAD

**Issue by tgeek77** [TryGhost/Ghost#8946]
Welcome to Ghost's GitHub repo! 👋🎉

Do you need help or have a question? Please come chat in Slack: https://ghost.org/slack 👫. Got an idea for a new feature? Please add it to our wishlist: http://ideas.ghost.org 🌟. Found a bug? Please fill out the sections below... thank you 👍

If your issue is with Ghost CLI, please report it on the CLI repo ➡️ https://github.com/TryGhost/Ghost-CLI/issues/new.

### Issue Summary

Blog posts don't handle embedded code correctly

### Steps to Reproduce

You should be able to use the backtick key to denote code being using in a story. However it often fails to read carriage returns properly and misses entire lines.

Just put these example in a ghost story using the backtick delimiters and then preview the output to see what I'm talking about.

Example 1.  

ALPINE 2.20   MAIN MENU      Folder: INBOX      No Messages

    ?     HELP               -  Get help using Alpine

    C     COMPOSE MESSAGE    -  Compose and send a message

    I     MESSAGE INDEX      -  View messages in current folder

    L     FOLDER LIST        -  Select a folder to view

    A     ADDRESS BOOK       -  Update address book

    S     SETUP              -  Configure Alpine Options

    Q     QUIT               -  Leave the Alpine program

               For Copyright information press "?"
             [Folder "INBOX" opened with 0 messages]
? Help                              P PrevCmd              R RelNotes
O OTHER CMDS       > [ListFldrs]    N NextCmd              K KBLockH

Example 2:

virt-install \
 --connect qemu+ssh://jsevans@10.0.1.35/system \
 --name leap42 \
 --ram 2048 --disk path=/workspace/VM/opensuse42.2.qcow2 \
 --vcpus 1 \
 --os-type linux --os-variant generic \
 --network network=default \
 --graphics none \
 --console pty,target_type=serial \
 --location 'http://download.opensuse.org/distribution/leap/42.2/repo/oss/' \
 --extra-args 'console=ttyS0,115200n8 serial' 

In the first example, ghost doesn't display the first or last few lines as code. In the second example, the carriage returns are not show.

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

If ghost is using markdown, it should use the standard markdown commands properly.

### Technical details:

* Version 1.7.1 (Official Docker Image)
* Environment production
* Database sqlite3
* Browser/OS: Firefox 52.3.0

**Comment by kevinansfield** [comment]
@tgeek77 from GitHub's issue output above it would seem that GitHub's markdown parsing is also failing, which suggests the markdown you are trying to use is invalid.

Are you able to post the raw markdown code somewhere that won't try to format it? A [public gist](https://gist.github.com) would be useful

**Comment by tgeek77** [comment]
Per the official markdown documentation, "To specify an entire block of pre-formatted code, indent every line of the block by 4 spaces or 1 tab. Just like with code spans, &, <, and > characters will be escaped automatically."

So it looks like in my example from Alpine, markdown is getting confused between the spaces in the example and the backticks that I am using. So, maybe this is more of a feature request than a bug.

**Comment by b4dnewz** [comment]
Hi, I can assume that the error is inside the markdown code since your example is parsed wrongly even from github markdown parser (which I guess could be the same used from ghost), after some text cleaning it works:
Example 1:
```
ALPINE 2.20 MAIN MENU Folder: INBOX No Messages

?     HELP               -  Get help using Alpine

C     COMPOSE MESSAGE    -  Compose and send a message

I     MESSAGE INDEX      -  View messages in current folder

L     FOLDER LIST        -  Select a folder to view

A     ADDRESS BOOK       -  Update address book

S     SETUP              -  Configure Alpine Options

Q     QUIT               -  Leave the Alpine program


For Copyright information press "?"
[Folder "INBOX" opened with 0 messages]
? Help P PrevCmd R RelNotes
O OTHER CMDS > [ListFldrs] N NextCmd K KBLockH
```
Example 2:
```
virt-install 
--connect qemu+ssh://jsevans@10.0.1.35/system 
--name leap42 
--ram 2048 --disk path=/workspace/VM/opensuse42.2.qcow2 
--vcpus 1 
--os-type linux --os-variant generic 
--network network=default 
--graphics none 
--console pty,target_type=serial 
--location 'http://download.opensuse.org/distribution/leap/42.2/repo/oss/' 
--extra-args 'console=ttyS0,115200n8 serial'
```

I'm not sure if this is what you want, but I ensure to you it works if markdown is properly constructed, you can double check with this [tool](https://dlaa.me/markdownlint/)

**Comment by kevinansfield** [comment]
@tgeek77 there are two ways to create code blocks in markdown:

One, wrap everything in triple backticks (<code>```</code>):
<pre><code>```
All your code can go here

on as many lines as you want
```
</code></pre>

Two, indent every line with 4 spaces or a tab - this is less reliable because any break in the indentation (e.g. on a blank line) will end the code block:

```
    All your code can go here
    
    on as many lines as you want
    
    as long as *every* line has 4 spaces
```

I'm going to close this as it doesn't sound like a bug, rather incorrect markdown usage.
