### ISSUE TITLE
ghost doctor fails to recognize alternate SES settings

### ISSUE THREAD

**Issue by alikuru** [TryGhost/Ghost#8952]
I noticed this error when I wanted to test my config after I upgrading to 1.8.0.

```
✖ Validating config
A ConfigError occurred.

Error detected in the production configuration.

Message: Invalid mail transport
Configuration Key(s): mail.transport
Current Value(s): SES

Help: Run `ghost config <key> <new value>` for each key to fix the issue.


Debug Information:
    Node Version: v6.9.2
    Ghost-CLI Version: 1.1.1
    Environment: production
    Command: 'ghost doctor startup'
```

My SES config is as follows;

```
"mail": {
  "from": "'John Doe' <john@doe.com>",
  "transport": "SES",
  "options": {
    "AWSAccessKeyID": "AWSACCESSKEY",
    "AWSSecretKey": "/AWS/SECRET"
  }
}
```

I'm using `pm2` to run Ghost and everything, including emails, seem to work. So, I assume this must be an issue with the `doctor`.

**Comment by vikaspotluri123** [comment]
I think a temporary workaround would be to specify the transport as SMTP and configure it based on to the [docs](https://docs.ghost.org/docs/mail-config#section-amazon-ses-a-id-ses-a-), although it looks like you need a different set of keys

@acburdine based on [nodemailer's transport file](https://github.com/nodemailer/nodemailer/blob/0.7/lib/transport.js) it looks like there's also support for `SES`, `Stub`, and `Pickup`, in addition to the cli-supported `smtp`, `sendmail`, and `direct` transports. It looks like the only additional transports the CLI should support are `ses` and possibly `pickup`

**Comment by alikuru** [comment]
@vikaspotluri123 thanks for the input but I don't think a workaround needed for passing `doctor`'s warning. My setup is listed as an alternate in docs, so it conforms. Ghost starts and runs just fine. Even emails are working.

This seems to be a false alarm issue.

**Comment by acburdine** [comment]
Hey, sorry for not responding to this sooner. @alikuru would you mind re-opening this issue in the Ghost-CLI [repository](https://github.com/TryGhost/Ghost-CLI)? It belongs there rather than here 😄

**Comment by adriaan-pelzer** [comment]
Is there any way ghost can be started without running ghost doctor?
I want to use SES, and it works, but I can't start ghost because of this issue.
