### ISSUE TITLE
Allow multiple `ghost-sdk.js` files to be used simultaneously

### ISSUE THREAD

**Issue by kevinansfield** [TryGhost/Ghost#8961]
### Issue Summary

Currently, if you want to use client-side JS to make API requests to multiple Ghost publications you're unable to use the `ghost-sdk.js` helper file each publication provides.

The `ghost-sdk.js` code [puts it's functions on `window`](https://github.com/TryGhost/Ghost/blob/master/core/server/public/ghost-sdk.js#L64-L68) meaning each file will override the previous files functions. It's also wrapped in an IIFE and doesn't expose any other method to access it's variables or functions.

### Notes

- Any solution will need to keep the existing `window.ghost.*` behaviour to avoid breaking changes (we may be able to clean that up in a later 2.x release)
- My first thought for a solution would be to add a `window.ghost.urls` array which contains the `url` method keyed by `{{apiUrl}}`. The `init` function could then be adapted to use `url` to generate it's `ghost` object in the normal fashion but also return it, that way you could do:
    ```
    var site1 = ghost.init({url: 'https://site1.com/ghost/', clientId: 'x', clientSecret: 'y'});
    var site2 = ghost.init({url: 'https://site2.com/ghost/', clientId: 'a', clientSecret: 'b'});

    site1.url.api('posts', {limit: 3});
    ```

**Comment by kevinansfield** [comment]
If anyone else runs into this, to work around the current limitations it's possible to use `ghost.init` in sequence, e.g.:

```html
<script type="text/javascript" src="https://my-ghost-blog.com/public/ghost-sdk.min.js"></script>
<script type="text/javascript">
ghost.init({
  url: 'https://my-ghost-blog.com/ghost/',
  clientId: "ghost-frontend",
  clientSecret: "<letters-and-numbers>"
});

// whatever is needed to get the data from site 1
// $.get(ghost.url.api('posts', {limit: 3})

ghost.init({
  url: 'https://my-second-ghost-blog.com/ghost/',
  clientId: "ghost-frontend",
  clientSecret: "<letters-and-numbers>"
});

// whatever is needed to get the data from site 2
// $.get(ghost.url.api('posts', {limit: 3})

ghost.init({
  url: 'https://my-third-ghost-blog.com/ghost/',
  clientId: "ghost-frontend",
  clientSecret: "<letters-and-numbers>"
});

// whatever is needed to get the data from site 3
// $.get(ghost.url.api('posts', {limit: 3})
</script>
```

**Comment by ErisDS** [comment]
Closing as ghost-sdk.js is being deprecated along with the v0.1 of the API in favour of the new v2 content API and content-sdk tools.

More info about this coming soon 😬

**Comment by ErisDS** [comment]
For anyone coming across this `ghost-sdk.js` is the old v0.1 way of talking to the API. The new v2 SDK is documented here: https://docs.ghost.org/api/helpers/ and the v2 API is documented here: https://docs.ghost.org/api/content/
