### ISSUE TITLE
iOS Admin panel: Main left panel getting stuck when clicking more

### ISSUE THREAD

**Issue by piotrekkmt** [TryGhost/Ghost#8962]
### Issue Summary

Admin panel on an iOS browser (tested Chrome and Safari) getting stuck after opening. Nothing happens when I try to close it. Tapping outside or pressing the **More** button on the bottom of the screen don't do anything for the first couple of times, and eventually make the layer below move right leaving the panel open and the whole screen moved to the side.

Also, there's no way of uploading inline images any more as in Ghost < v1 

### Steps to Reproduce

1. Open the Admin panel by going to your Ghost website [website.domain]/ghost in Dark Mode.
2. Tap on a post to edit.
3. In edit mode for a post click the **More** button in the bottom drawer. 

![image](https://user-images.githubusercontent.com/1800333/29965946-9dab79ea-8f07-11e7-8b7b-32eacca1dcb7.png)

### Technical details:

* Ghost Version: 1.7.1
* Node Version: v6.11.2
* Browser/OS: iOS 10.3.3 - Both Chrome and Safari
* Database: sqlite

**Comment by kevinansfield** [comment]
Confirmed. The same issue is present with normal as well as Night shift styles.

**Comment by nithindavid** [comment]
Fixed @kevinansfield 
It's an issue with iOS, It won't click/touch events bound to elements, added after DOM load. The known quick fix is to add "cursor:pointer;" to it's css
![kapture 2017-09-27 at 19 54 04](https://user-images.githubusercontent.com/1277421/30918940-a32a2068-a3bd-11e7-88b3-c7add6224900.gif)



https://github.com/TryGhost/Ghost-Admin/pull/873

**Comment by piotrekkmt** [comment]
Great stuff, thanks for resolving this guys!
