### ISSUE TITLE
Post "comment_id" lost when migrating content to new instance

### ISSUE THREAD

**Issue by triestpa** [TryGhost/Ghost#8963]
### Issue Summary

As a workaround for a breaking issue with the Ghost-CLI (https://github.com/TryGhost/Ghost-CLI/issues/461), I recently attempted to migrate my blog to a new server.

Importing the JSON content from the old instance to the new one resulted in the `comment_id` property for each post changing.  The themes on both instances are identical; both are initializing the Disqus config with -
```javascript
this.page.identifier = 'ghost-{{comment_id}}';
```

The resulting comment ID, however, is different in each instance.  For example, the post which has a `comment_id` of `15` in the old instance has a `comment_id` of `59a935ae0718612fce6740b0` on the new instance.  

**This is a major issue since it results in the Disqus comment threads becoming dissociated from their corresponding posts**.  I still have access to the old instance, is there any way to transfer the blog content without losing the comment ids?

### Technical details:

* Ghost Version: v1.8
* Node Version: v6.11.2
* Browser/OS: Ubuntu 16.04
* Database: SQLite

**Comment by acburdine** [comment]
@triestpa based on how the importer is currently configured, I can see why this would occur. Definitely still a bug, but your issue makes sense 👍 

In the meantime though, you can workaround this issue by manually copying the sqlite database file from one server to the other - this should retain the same data without exporting/importing.

**Comment by triestpa** [comment]
@acburdine Thanks for the quick reply!  And thanks for the workaround suggestion, copying the sqlite file to the new instance allowed for a successful migration.
