### ISSUE TITLE
word.word results in a link

### ISSUE THREAD

**Issue by alznyc** [TryGhost/Ghost#8964]
The other day I noticed when missing a space after a '.' ghost will create a link out of those words.

For example, we have this snippet:

administrative details and the other who can stay with the patient.In most cases having a relative or a professional caregiver...

the editor won't show "patient.In" as a link, but when saved the resulting html will make "patient.In" a link.

Testing this, if we type, for example, Asd.gh, will result in a link when saved.

Is this behavior expected?

### Technical details:

* 1.8.0:
* Node Version: 6.9.1
* Browser/OS: Chrome/MacOS Sierra
* Database: mySQL

**Comment by vikaspotluri123** [comment]
This behaviour is expected - as long as whatever is after the period is a valid [top level] domain, Ghost will automatically convert the text to a link. You should be able to see what ghost do by viewing the preview (either click the eye in the bottom toolbar [preview], or click the button next to it [side-by-side preview])

**Comment by kevinansfield** [comment]
As @vikaspotluri123 pointed out, this behaviour is expected. Closing as this isn't a bug 😄
