### ISSUE TITLE
ghost on Azure. Invitation email was not sent. Please try resending

### ISSUE THREAD

**Issue by Leonerdy** [TryGhost/Ghost#8971]
I'm trying invite friends to blog but I have this error "Invitation email was not sent. Please try resending.", I configure in azure like in tutorial https://docs.ghost.org/docs mail config, emailService: Mailgun, emailUserName: postmaster@sandbox... and emailPassword: ****, I can send email test in aba Labs for my e-mail but I couldnt resolve this problem, some help please. I deploy ghost on Azure.

**Comment by kirrg001** [comment]
Hey @Leonerdy!

Sorry to hear you are having trouble with sending emails.

I'm going to close this issue as we use github solely for bug tracking and feature development. Please swing by our [slack channel](https://slack.ghost.org) and ask in the `#help` channel. Furthermore, please read our [contributing rules](https://github.com/TryGhost/Ghost/blob/master/.github/CONTRIBUTING.md), thanks 🙏🏽

**Comment by ch-hristov** [comment]
Guys, it's not working on 0.11.11 and not using to track issues github only can cause lack of information and transparency. @kirrg001
