### ISSUE TITLE
Feature to disable auto-generating links/anchors

### ISSUE THREAD

**Issue by frederikaalund** [TryGhost/Ghost#8987]
### Issue Summary

When I write something like "Martin holds a M.Sc. degree in", this gets converted into "Martin holds a [M.Sc](m.sc). degree in". This is wrong, as "M.Sc." is referring to a title and not a website. I'd like to be able to disable this feature.

### Technical details:

* Ghost Version: 1.8.0
* Browser/OS: Chrome/Windows
* Database: MySQL

**Comment by kevinansfield** [comment]
We wouldn't implement a toggle or config for this but I am considering changing or removing the auto-link behaviour entirely.

There are a number of options:
1. Add exceptions such as M.Sc as they come up.
2. Disable only the fuzzy linking. Full urls will still automatically be linked, any other links will need to be wrapped in `<>`'s (e.g. `<google.com>`) or created manually with full markdown syntax - see the [linkify-it](http://markdown-it.github.io/linkify-it/) demo for an example of full vs fuzzy auto linking
3. Remove auto linking completely so authors will always need to use `<site.name>` or `[site.name](https://site.name)`

**Comment by ErisDS** [comment]
> Disable only the fuzzy linking. URLs will still automatically be linked if they contain a protocol, any other links will need to be created manually with full markdown syntax (e.g. [google.com](https://google.com)) - see the linkify-it demo for an example of full vs fuzzy auto linking

I think this is the best option?

**Comment by kevinansfield** [comment]
👍 Agreed. Should be a quick change.

**Comment by cleversprocket** [comment]
If I want a link I'll write it in Markdown or click the link button in the GUI. This autoconversion to anchors is fighting the inherent nature of markdown.
