### ISSUE TITLE
404 error page leaks blog post information in private blog

### ISSUE THREAD

**Issue by mtrainham** [TryGhost/Ghost#8990]
### Issue Summary

A blog's 404 page, using the casper theme, shows a summary of the last 3 blog posts at the bottom of the page. If your blog is password protected, you can still get this 404 page to show up without entering the password, thus leaking the blog's private information to the public.

### Steps to Reproduce

1. In your blog _https://{blog}.ghost.io/ghost_ make your blog private in settings by entering a password.
2. Also make sure your blog is using the casper theme, and that you have published posts.
2. Open a different browser and goto your blog (_https://{blog}.ghost.io_) to ensure you get a password protected page.
2. Try appending _/rss_ to the end of your blog's url. _https://{blog}.ghost.io/rss_. This should show the casper theme's 404 page, in which you will see three of your blog posts.

If you can't reproduce it, here's an example: https://infinity-3.ghost.io/rss

The expected behavior is up to you, but you should definitely not be able to see blog posts that are supposed to be private. I would think that no matter what path you are trying to access inside a private blog, whether the path exists or not, you would be redirected to the password screen.

> **Note:** Although the code for this 404 page is in the casper repo, I think this is an issue for the main ghost application, because a theme should not be able to inadvertently leak a private blog's information.

https://github.com/TryGhost/Casper/blob/d1d0bca2d8be6e93c38283e9fa37e2070f9c65bb/error-404.hbs

```html
{{#get "posts" limit="3"}}
<aside class="outer">
    <div class="inner">
        <div class="post-feed">
            {{#foreach posts}}
                {{> "post-card"}}
            {{/foreach}}
        </div>
    </div>
</aside>
{{/get}}
```

### Technical details:

* Ghost Version: ghost.io
* Node Version: N/A
* Browser/OS: Chrome/Windows 10
* Database: N/A

**Comment by kirrg001** [comment]
Hey @mtrainham!

Thanks for your report.

It's true, Casper fetches 3 posts on the 404 error page, which exposes data from your private blog. But you are unable to click on the post - it will redirect you to add to enter the password.

If you request `/rss` or `/sitemap` we serve a 404 if your blog is private. 
I agree, we shouldn't fix on the theme level.

Possible solution: The `get` theme helper must be able to figure this out and return nothing.

**Comment by kirrg001** [comment]
We are going to fix asap 👍  

Probably a better approach for this is to remove [this condition](https://github.com/TryGhost/Ghost/blob/master/core/server/apps/private-blogging/lib/middleware.js#L54). But i wasn't sure why it was added cc @ErisDS

**Comment by ErisDS** [comment]
@kirrg001 the logic was added, to satisfy the requirement that private blogs do not have RSS feeds and sitemaps, because they make no sense in a private blog :) See the [original issue](https://github.com/TryGhost/Ghost/issues/4993).

However, providing that those routes still require the cookie to be in place or redirect, I think we can reasonably allow them to render on those routes - this will prevent a number of issues we get raised asking why these routes return a 404.

**Comment by ErisDS** [comment]
Also related: #8947
