### ISSUE TITLE
Add release notes to update notification

### ISSUE THREAD

**Issue by JohnONolan** [TryGhost/Ghost#8992]
> Can @TryGhost put a change log link here so I can determine if I need to stop what I am doing and update right this moment? @JohnONolan 

![image](https://user-images.githubusercontent.com/120485/30226185-f30d3b76-9489-11e7-99b2-677bd628a929.png)
https://twitter.com/pbmarcano/status/905855313575849984

Pretty good point.

Double update notification bug - I think that's fixed already, right? 

---

Anyway I think it would make sense to tweak the notification to:

> Update available! [Ghost 1.8.4](https://github.com/TryGhost/Ghost/releases) has been released, [click here](https://docs.ghost.org/docs/upgrade) to upgrade

Link `Ghost x.x.x` to https://github.com/TryGhost/Ghost/releases - so the release notes are always visible. We could programmatically deep link to exact release, but I don't think it's worth it - static link would prob be fine?

**Comment by syhily** [comment]
Auto upgrade from the dashboard, no more operation on terminal would be better.

**Comment by letsjustfixit** [comment]
@syhily if you need an auto-upgade just sign up for ghost Pro :).
Otherwise I'd strongly object against any auto-update behaviour thats barely managable on desktop apps...

**Comment by kirrg001** [comment]
> Double update notification bug - I think that's fixed already, right?

This is resolved. There was a little gap between having the [notifications refactoring](https://github.com/TryGhost/Ghost/issues/5071) in place and knowing which version of Ghost will contain this refactoring.

> Anyway I think it would make sense to tweak the notification

I've improved the wording in our internal service.

Closing.

**Comment by ErisDS** [comment]
FYI:
I accepted an invite on a blog recently that was running a few versions behind, and I saw this:
![](https://puu.sh/xtdtV.png)

When I refreshed it changed to just the latest one. Not sure if there is a bug?

**Comment by kirrg001** [comment]
> When I refreshed it changed to just the latest one. Not sure if there is a bug?

Yeah this is one of the old problems we had with our notification logic. Saw this reported already a couple of times in the past. This is unrelated to the new notification logic. Somehow Ghost or Admin has an old bug which does not detect duplicates.

As soon as we merge #5071 into LTS and 1.X, this should be gone.

**Comment by pbmarcano** [comment]
Sorry, curious to see if this was closed because of the double notification bug or because you've already changed the text in the notification to include the change log?

Or maybe you aren't changing the text to include the change log?
