### ISSUE TITLE
Move metadata fetching & processing out of ghost_head

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#8995]
The `ghost_head` helper is async, meaning we are able to do all kinds of data fetching and processing inside it before ultimately rendering the data.

In this case, the data that is being fetched and processed doesn't _need_ to wait until render time, as it will always be the same based on the URL, config and settings that are available much earlier.

To try to reduce page render time, to improve access to metadata and to to improve the route -> to -> render logic inside of Ghost, we really need to move the metadata fetching and processing out of ghost head and into somewhere more fitting.

The top priority is moving everything that is an async call (`getClients()` and `getImageDimensions`) out of the helper. 

----

There are a few challenges with this refactor:

`getImageDimensions` requires us to already have 4 pieces of data: the url's for cover image, author image, og image and logo for any given route. There is no standardised point at which we have that data available.

`ghost_head` is a global helper, called for every page that gets rendered during the rendering process - which means this was the ideal location as we have all the data and just one place to make the call.

Elsewhere in Ghost the "controllers" that handle rendering a piece of content are spread around - as can be determined by doing a search for `setResponseContext` - and there's no clear point when the route's main data has been fetched.

In order to make sure meta data is calculated for all routes, for now we'd have to call a function just after `setResponseContext` in each case. Ideally long term we want to move to more of a middleware structure, where each route has separate steps with some shared functions, e.g. pre-fetch, fetch data, post-fetch and render.

----

- [x] change `ghost_head` to explicitly use `options.data.root._locals.` instead of `this.` for context, safeVersion, client etc
- [x] move `getClient()` out of ghost_head into middleware, using res.locals to store the client
- [ ] try to move the remaining `getMetaData` processing into psuedo-middleware like `setResponseContext` 
- [ ] try to get route processing to be separated out into middleware steps, and change `setResponseContext`, and `getMetaData` into real middleware

**Comment by ErisDS** [comment]
I have an active spike where I did some small work towards this to see how it might play out.

As a result I have basic commits for the first two items:

https://github.com/TryGhost/Ghost/compare/master...ErisDS:towards-8995?expand=1

However, the first commit which achieves explicitly using data.root requires some reworking of the ghost_head tests. The second commit also requires test updates. I would like to leave this here to have some time spent on it with the tests being updated and maybe improved plus also manual testing to make sure this doesn't break things.

**Comment by jochenkirstaetter** [comment]
Hi,
thanks for the refactoring. I would like to add the following consideration when changing the code:
The output of `structured_data.js` cascades the value for the description field compared to the meta tag.

```
        // CASE: metaData.excerpt for post context is populated by either the custom excerpt,
        // the meta description, or the automated excerpt of 50 words. It is empty for any
        // other context and *always* uses the provided meta description fields.
        'og:description': metaData.ogDescription || metaData.excerpt || metaData.metaDescription,
```

I understand that the recommended length of meta description should be around 156 characters. Nonetheless, I would expected that there is a meta tag for description given the use of custom_excerpt. Could the following change in `ghost_head.js` be of interest? 

```
                // head is our main array that holds our meta data
                if (metaData.metaDescription && metaData.metaDescription.length > 0) {
                    head.push('<meta name="description" content="' + escapeExpression(metaData.metaDescription) + '" />');
                } else if (metaData.excerpt && metaData.excerpt.length > 0) {
                    head.push('<meta name="description" content="' + escapeExpression(metaData.excerpt) + '" />');
                }
```

Thanks, JoKi

**Comment by ErisDS** [comment]
All issues tagged with `routing` have been tagged with `later` and closed until we prioritise working on the Routing feature again.

**Comment by KajKandler** [comment]
I just tried to integrate 11ty for a static site generation with Ghost. I noticed that the schema.org metadata is not part of the API layer. 

Is schema.org metadata not a first-class citizen of the document?
