### ISSUE TITLE
Cannot `ghost update` 

### ISSUE THREAD

**Issue by chrisdlangton** [TryGhost/Ghost#9005]
### Issue Summary

This is at least the 5th time this has happened. I use a docker image and I attempt to update and the `ghost update` tool has never worked for MANY versions - today i'm letting you know.

How did I stay updated until now? I took an export, build the latest docker image, imported the export to the new image, attach the new image to my load balance, connection drain the old image, shutdown and remove old image.

Although I can do the above steps to remedy the utterly useless and broken cli - last time i lost data because i .tar.gz the export and didn't verify its integrity before continuing and losing all my data when i tore down the old docker image.. Yeah, my fault, but i want to just friggin update ghost and frankly dont care to do the steps above ever again (considering abandoning ghost too so maybe this issue is pointless...)

### Steps to Reproduce

1. docker run -d --name ghost -p 80:2368 ghost:1.8.1-alpine
2. enter a shell and type `ghost update`

### Technical details:

```
bash-4.3# ghost update
✔ Checking for latest Ghost version
✔ Downloading and updating Ghost to v1.8.5
ℹ Stopping Ghost [skipped]
✔ Linking latest Ghost and recording versions
✖ Running database migrations
A ProcessError occurred.

Error occurred running command: 'undefined'


Debug Information:
    Node Version: v6.11.2
    Ghost-CLI Version: 1.1.1
    Environment: production
    Command: 'ghost update'

Additional log info available in: /root/.ghost/logs/ghost-cli-debug-2017-09-13T00_32_12_803Z.log

Please refer to https://docs.ghost.org/v1/docs/troubleshooting#section-cli-errors for troubleshooting.
bash-4.3# cat /root/.ghost/logs/ghost-cli-debug-2017-09-13T00_32_12_803Z.log
Debug Information:
    Node Version: v6.11.2
    Ghost-CLI Version: 1.1.1
    Environment: production
    Command: 'ghost update'
Error occurred running command: 'undefined'

bash-4.3#
```

**Comment by AileenCGN** [comment]
Hey @chrisdlangton! Sorry to hear that you're having trouble updating Ghost. I will close this issue and ask you to reopen it in the correct repository, as it's not an issue with Ghost itself.

So please go ahead and reopen it on the [Ghost-CLI](https://github.com/TryGhost/Ghost-cli/issues) repository, but please also check out the existing [Docker image for Ghost](https://github.com/docker-library/ghost) (if you didn't already) and see, if this issue belongs there.

**Comment by acburdine** [comment]
@chrisdlangton ghost-cli is not intended to work _inside_ of the docker image, simply based on how the CLI is intended to be used and the fact that it does not work well with how Docker is intended to be used. The recommended way to update if you _are_ using Docker is to swap out the container. This _can_ cause issues if you are using sqlite3 as your database rather than mysql, but you can also mount the content directory into the docker instance to mitigate that issue.
