### ISSUE TITLE
Cursor doesn't work well with Bopomofo IME

### ISSUE THREAD

**Issue by hungys** [TryGhost/Ghost#9012]
### Issue Summary

For Chinese IME Bopomofo (either macOS built-in or third-party), the cursor doesn't display correctly when the user is correcting the word before pressing Enter. The experience is not really friendly for users using this kind (typing->correcting->pressing Enter) of IME.

![](https://media.giphy.com/media/l1J9rf6tAwss4EGR2/giphy.gif)

### Steps to Reproduce

1. Typing in Ghost editor using Bopomofo IME.
2. Use arrow key to correct the words.

### Technical details:

* Ghost Version: 1.8.4
* Node Version: 6.9.4
* Browser/OS: Safari/macOS
* Database: MySQL

**Comment by ErisDS** [comment]
@hungys Thanks for raising this issue. I'm afraid there isn't anyone on our team who uses Chinese or Japanese alphabets, so it is very difficult for us to understand these problems.

Can you explain what "Chinese IME Bopomofo" is? Is it something like pinyin? 

Also, can you possibly explain in more detail what exactly is wrong with the cursor position?

I'm going to mark this as "fix wanted", which means we'd like the community to fix it, as I think it is unlikely that we will be able to understand well enough to create a fix.

However, this may end up getting closed by @kevinansfield as he will be able to confirm whether or not it's a problem with the underlying technology - that is [SimpleMDE](https://github.com/sparksuite/simplemde-markdown-editor) which in turn is based on [CodeMirror](https://github.com/codemirror/CodeMirror) - it may be that this needs to be raised on one of those repositories instead.

**Comment by kevinansfield** [comment]
@hungys this is almost certainly an issue to be raised with [CodeMirror](https://github.com/codemirror/codemirror), can you confirm that you see the same behaviour if you try typing in the [demo on their homepage](https://codemirror.net)?

If you [search their repo for "IME"](https://github.com/codemirror/CodeMirror/search?utf8=✓&q=ime&type=Issues) you'll see a number of related issues, it may be that they are already aware of the problem and are waiting for a community fix.

**Comment by hungys** [comment]
@ErisDS Yes, it's something like Pinyin. We type the words based on their pronunciation and when the IME is not smart enough, sometimes we need to use arrow keys (left/right key for moving the cursor, and bottom key for choosing the words) to correct the words.

@kevinansfield You are right. The issue also happens on their demo so this is exactly an upstream issue.

**Comment by ErisDS** [comment]
I think this can be closed, as it is an upstream issue, there's nothing we are able to do in Ghost itself.

**Comment by hungys** [comment]
Here is the related upstream issue: https://github.com/codemirror/CodeMirror/issues/4096

Seems that It also affects Japanese user.
