### ISSUE TITLE
Post API: Excerpts

### ISSUE THREAD

**Issue by karai17** [TryGhost/Ghost#9018]
I think it would be very useful to be able to request a plaintext excerpt via the public api. The main use case for this would be adding the first little bit of a blog post to a site for people to click through to the full post.

```js
ghost.url.api('posts', {
   limit: 3,
   excerpt: {
      type: "words",
      limit: 50
   }
});
```

**Comment by kevinansfield** [comment]
@karai17 if you're using the API it's assumed that the API consumer is completely responsible for any display logic, we won't be adding any display-specific parameters to API endpoints
