### ISSUE TITLE
A ProcessError occured when ghost install

### ISSUE THREAD

**Issue by iaade** [TryGhost/Ghost#9026]
When trying to install ghost onto a digital ocean VPS I get the following error. I replaced my url and email with [My_URL] and [My_Email_Address]

✔ Checking system Node.js version
✔ Checking current folder permissions
✔ Checking operating system
✔ Checking MySQL is installed
✔ Checking for latest Ghost version
✔ Setting up install directory
✔ Downloading and installing Ghost v1.8.7
✔ Finishing install process
? Enter your blog URL: https://[My_URL]
? Enter your MySQL hostname: localhost
? Enter your MySQL username: root
? Enter your MySQL password: [hidden]
? Enter your Ghost database name: ghost_production
✔ Configuring Ghost
✔ Setting up instance
Running sudo command: chown -R ghost:ghost /var/www/ghost/content
✔ Setting up "ghost" system user
? Do you wish to set up Nginx? Yes
✔ Creating nginx config file at /var/www/ghost/system/files/[My_URL].conf
Running sudo command: ln -sf /var/www/ghost/system/files/[My_URL].conf /etc/nginx/sites-available/[My_URL].conf
Running sudo command: ln -sf /etc/nginx/sites-available/[My_URL].conf /etc/nginx/sites-enabled/[My_URL].conf
Running sudo command: service nginx restart
✔ Setting up Nginx
? Do you wish to set up SSL? Yes
? Enter your email (used for Let's Encrypt notifications) [My_Email_Address]
✖ Setting up SSL
A ProcessError occurred.

Error occurred running command: '/bin/sh -c /home/ghost/.acme.sh/acme.sh --issue --domain [My_URL] --webroot /var/www/ghost/system/nginx-root --accountemail [My_Email_Address]'

Exit code: 1

Debug Information:
    Node Version: v6.11.3
    Ghost-CLI Version: 1.1.1
    Environment: production
    Command: 'ghost install'

Please refer to https://docs.ghost.org/v1/docs/troubleshooting#section-cli-errors for troubleshooting.

### Issue Summary

A summary of the issue and the browser/OS environment in which it occurs.

### Steps to Reproduce

1. This is the first step
2. This is the second step, etc.

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

### Technical details:

* Ghost Version:
* Node Version:
* Browser/OS:
* Database:

**Comment by acburdine** [comment]
@iaade Most likely you didn't configure your URL to point at your server's IP address before running `ghost install`. Regardless, I'm going to close this because we use Github for bugs with the actual software, not support requests. Please swing by our [slack channel](https://slack.ghost.org) if you need more help 😄

**Comment by iaade** [comment]
You were right. Thanks for the assistance and sorry for posting in the wrong location
