### ISSUE TITLE
More possibilities of image formatting

### ISSUE THREAD

**Issue by MaluNoPeleke** [TryGhost/Ghost#9032]
### Issue Summary

I would like to have more flexibility regarding image formatting in a post.
Currently it is only possible to add single images to a post without any options.
For things like size, gallery or caption you have to use HTML or special markdown code.
It should be possible to have several options like https://www.computerbase.de/2017-08/sony-xperia-touch-test/ for example.
On my blog I have already impemented automatic lightbox effect to all images (https://www.peleke.de/portfolio/) but for the rest I cannot see an easy solution currently.

### Steps to Reproduce

1. Add an image to a post
2. Try to format it

Feature request

### Technical details:

* Ghost Version: 1.8.6
* Node Version: 6
* Browser/OS: Chrome
* Database: MariaDB

**Comment by acburdine** [comment]
@MaluNoPeleke This sounds like something that should be possible once the full mobiledoc implementation of the ghost admin editor is completed, but I'm closing this issue because we use Github issues for bugs and ongoing work with the software, not for feature requests.
