### ISSUE TITLE
Cli won't install

### ISSUE THREAD

**Issue by MishUshakov** [TryGhost/Ghost#9033]
### Summary

Hey guys, I was trying to install ghost-cli and got some errors, it looks like https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.11/node-v48-linux-arm.tar.gz is down or something is wrong with it, how to fix it?

### Steps to Reproduce

1. npm i -g ghost-cli

### Technical details:

* Ghost Version: latest
* Node Version: 6.11.3
* Browser/OS: Raspbian on Raspberry Pi
* Database: sqlite

<img width="850" alt="screen shot 2017-09-20 at 23 32 47" src="https://user-images.githubusercontent.com/10400064/30668945-c9079ad8-9e5c-11e7-9348-5b587b60494d.png">

**Comment by acburdine** [comment]
@MishUshakov that should only affect you if you want to use sqlite3 with ghost-cli - if you use mysql it should work fine. Also, if the s3 place for sqlite binary builds is down then there's nothing Ghost can do about it :/

Closing as this is not an issue with Ghost, or Ghost-CLI.

**Comment by MishUshakov** [comment]
@acburdine is there some other way to get the binary builds? any mirrors?

**Comment by MishUshakov** [comment]
trying to install it using package manager...

**Comment by ErisDS** [comment]
You would need to report this to https://github.com/mapbox/node-sqlite3 who are the maintainers of the node-sqlite3 project, but it's an amazon s3 bucket, if it's down, there's nothing much that can be done. The only way to get a binary if the amazon is down would be to build it yourself - instructions are on that repo.
