### ISSUE TITLE
Suggestion: More control over tags via tag types

### ISSUE THREAD

**Issue by mohoff** [TryGhost/Ghost#9044]
Hi, I would like to have more control over my tags. On my photo blog I tag photos with city, country, and sometimes region. It would be nice if these type of tags would always appear in the same order, let's say city-tag > region-tag > country-tag. In the future I might color the country-tags differently but for that I need to check for the tag-type in my handlebars.

To my knowledge, tags are sorted by their incremented ID which means sorted by date of creation of the tag. A bit more customizability - if it doesn't exist already - would be much appreciated :)

Thanks in advance!

EDIT: Example on blog.mohoff.de

**Comment by acburdine** [comment]
@mohoff this is already possible - in each post you can drag the tags to re-order the per post, and if you use the `{{tags}}` helper in your theme they will be output in the order they are put in in the admin panel.

Going to close this issue though as we use Github issues for bugs and ongoing work with the software, not for feature requests 😄

**Comment by mohoff** [comment]
Oh great, didn't realize that! Thanks!
For the future: Where do the feature request go?
