### ISSUE TITLE
Spellcheck is unreadable in dark-mode (red marker over misspellings).

### ISSUE THREAD

**Issue by iamsanteri** [TryGhost/Ghost#9056]
### Issue Summary

As written in the title of this issue. Should be fairly simple to fix.

### Steps to Reproduce

1. Dark mode on
2. Toggle spellcheck (when writing a post)

### Technical details:

Latest ghost version.

**Comment by kevinansfield** [comment]
Thanks @iamsanteri! Fix is implemented in https://github.com/TryGhost/Ghost-Admin/pull/874, should go out in the next release tomorrow.
