### ISSUE TITLE
Set Promise to be Bluebird globally

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#9064]
In Ghost, we make heavy use of Bluebird for promises and in particular Bluebird's [filtered catch](http://bluebirdjs.com/docs/api/catch.html#filtered-catch) feature. In conjunction with our error handling, this works really nicely to help us deal with various cases, e.g. handling a not found error vs a permissions or server error differently.

Using bluebird means that we often have to wrap or re-wrap functions that we import from external modules. There was a discussion about this problem [on this PR](https://github.com/TryGhost/Ghost/pull/9051) which lead to the proposal that we set Promise to be bluebird globally. 

As described & discussed on the [fs-extra repo](https://github.com/jprichardson/node-fs-extra/issues/425#issuecomment-305633342), setting `global.Promise = require('bluebird');` at the entry point to Ghost would mean that all Promises are automatically bluebird promises.

Some downsides to this are: 
1. setting globals are generally frowned upon
2. you have to do it early enough to catch all promises
3. it means that you create an implicit dependency between modules that are imported their usage with bluebirds custom features (spread is another example).

Ghost already has an overrides.js file, which explicitly gets called at the start of execution and overrides some moment behaviour. Therefore we already have a well understood correct location for globals to mitigate issue 2.

When it comes to issue 3, as explained in the original discussion, it is my feeling that we suffer more because we forget that some promises are not Bluebird promises and lose time to catch predicates that won't work etc, than we would do if we globally set Bluebird. A recent example is the image-size refactor project, where we knew we had to wrap the promises but didn't quite do it properly, and lost a lot of time to figuring out why the code wasn't working.

The proposal is to try out adding the global override and seeing if it makes our lives easier. We're leaving this here as an opportunity for our community members to raise concerns we might not have thought of.

**Comment by anajavi** [comment]
I am running Ghost as part of express application. Does this force me to use bluebird everywhere?

**Comment by ErisDS** [comment]
It would mean that anywhere you don't explicitly set `Promise` to be something else, then the promises would be bluebird promises.  You might be interested in an ongoing discussion here: https://github.com/TryGhost/Ghost/pull/8841 in which we propose removing the ability to use Ghost as part of another express app.

**Comment by kirrg001** [comment]
@ErisDS I would say, let's try it out and learn from it.
