### ISSUE TITLE
Missing X-Cache-Invalidate header on redirects upload response

### ISSUE THREAD

**Issue by kevinansfield** [TryGhost/Ghost#9065]
### Issue Summary

When uploading redirects via `/redirects/json/` we need to send the `X-Cache-Invalidate` header so that any intermediate cache systems can clear their caches.

I believe [this method](https://github.com/TryGhost/Ghost/blob/master/core/server/api/index.js#L68-L109) needs updating to return `INVALIDATE_ALL` for the `POST /redirects/json/` endpoint.

**Comment by kirrg001** [comment]
> I believe this method needs updating to return INVALIDATE_ALL for the POST /redirects/json/ endpoint.

Correct 👍
