### ISSUE TITLE
Login session not persistent when using MS Edge. on ghost.io

### ISSUE THREAD

**Issue by radcastro** [TryGhost/Ghost#9066]
Welcome to Ghost's GitHub repo! 👋🎉

Do you need help or have a question? Please come chat in Slack: https://ghost.org/slack 👫. Found a bug? Please fill out the sections below... thank you 👍

If your issue is with Ghost CLI, please report it on the CLI repo ➡️ https://github.com/TryGhost/Ghost-CLI/issues/new.

### Issue Summary

When logged in as the primary owner/creator of multiple ghost blogs under ghost.io, I should be able to switch without having to login into each blog. This issue does not occur with other browsers.

### Steps to Reproduce

1. Fire up MS Edge > Log in ghost.org > Publications > 
2. Select any Ghost (Pro) blog
3. Watch the URL redirect to the login

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

I expect the login to stay persistent instead of having to login as the author for each blog.

### Technical details:

* Ghost Version: Hosted at Ghost.io
* Node Version: Hosted at Ghost.io
* Browser/OS: MS Edge / Win 10
* Database: Hosted at Ghost.io

**Comment by kevinansfield** [comment]
Hey @radcastro 👋  I'm afraid I'm not following/not able to reproduce here.

I've tested with MS Edge on Win 10 and the authentication is persisted for all blogs that I log into - after logging in to multiple blogs I can open the admin screen of each and I'm immediately logged in, even after browser or computer restarts. The only time the login isn't persistent is when I choose "Sign out" in the admin app which is to be expected.

Your https://my.ghost.org login is completely separate to any owner/admin/author logins for individual blogs - this is expected and is not a bug, the auth is intentionally separate, you can't use your my.ghost.org credentials to log into any blog's admin app. Is that what you are referring to?

**Comment by ErisDS** [comment]
I'm very certain that this is a misunderstanding of the difference between Ghost.org (hosting control panel) and individual blogs as there is no shared login system. 

Can reopen if it turns out to be something else.
