### ISSUE TITLE
Posts can lose published status when leaving editor

### ISSUE THREAD

**Issue by kevinansfield** [TryGhost/Ghost#9072]
### Issue Summary

After making a change to a published post's content, leaving the editor triggers a save instead of the "Are you sure you want to leave?" modal and resets the post status to draft.

![posts-lose-status](https://user-images.githubusercontent.com/415/30926593-8f36ddc2-a3ad-11e7-9316-78a28baa90b0.gif)

### Steps to Reproduce

1. Open a published post in the editor
2. Make a change to the content
3. Click on a main menu link to leave the editor
4. Note the lack of a confirmation modal and that the post is now marked as a draft

### Technical details:

* Ghost Version: 1.9.1
* Browser/OS: Chrome/macOS

**Comment by kevinansfield** [comment]
@stefanovazzocell moving the conversation on https://github.com/TryGhost/Ghost/issues/8495#issuecomment-333288526 here as that's an unrelated issue.

Have you re-published the post that is now a draft? Upgrading won't do that for you.

**Comment by stefanovazzocell** [comment]
Yes, no result from that. I have not figure out why but sometimes the issue seems to solve itself (?) I do not know how.
Also, the article was created on 1.10.0 (and remained a draft)

To note: I'm using Cloudflare. Caching the pages except for the "example.com/ghost/*" pages.
