### ISSUE TITLE
Deleting search query causes error

### ISSUE THREAD

**Issue by AileenCGN** [TryGhost/Ghost#9075]
### Issue Summary

When entering a search query and using <kbd>←</kbd> to delete it again, search input loses focus and an error is thrown in the console.

![error_search](https://user-images.githubusercontent.com/8037602/30951735-af001e74-a44e-11e7-83ae-c2257bcc7ddd.gif)

I think, this might be cause within this conditional: https://github.com/TryGhost/Ghost-Admin/blob/master/app/components/gh-search-input-trigger.js#L22

### Steps to Reproduce

1. Type anything in the search input
2. Use <kbd>←</kbd> to delete whatever was typed until the last character, so the input field is empty again
3. See that the input field loses focus and throws this error in the console:
![image](https://user-images.githubusercontent.com/8037602/30951732-abfc1516-a44e-11e7-9bf7-8faa7854981c.png)

### Technical details:

* Ghost Version: current master a6d57d6
* Node Version: 6.11.3
* Browser/OS: Chrome
* Database: sqlite

**Comment by nithindavid** [comment]
Added a validation to search term before invoking search 

https://github.com/TryGhost/Ghost-Admin/pull/882
