### ISSUE TITLE
Permission Error for uploading themes

### ISSUE THREAD

**Issue by MertcanGokgoz** [TryGhost/Ghost#9083]
### Issue Summary

It gives an error when installing themes, I have not changed any permissions, downloaded and edited my old theme files but I can not install theme

I tried Chrome and Firefox the result has not changed

### Steps to Reproduce

1- Login ghost admin panel
2- Select design area
3- upload theme
4- finally error 

### Technical details:

* Ghost Version: 1.10.0
* Node Version: 6.11.3
* Browser/OS: Firefox 57b4
* Database: Mysql

```
EACCES: permission denied, open '/tmp/a9d80229-4b37-469f-b612-a1464218c9f6/casper-mg/partials/icons/facebook.hbs'
```

![capture](https://user-images.githubusercontent.com/8042604/31076066-37a0d54a-a781-11e7-8fb5-1695084924ba.PNG)

**Comment by ErisDS** [comment]
Hi @MertcanGokgoz, for support questions like these, please use [slack](https://ghost.org/slack).

You can also find our docs at docs.ghost.org. The documentation for this issue can be found here: https://docs.ghost.org/docs/troubleshooting#section-error-eacces-permission-denied

**Comment by MertcanGokgoz** [comment]
I checked the procedure, and as I mentioned, I have no permission problems

![capture](https://user-images.githubusercontent.com/8042604/31076227-e3a9e160-a781-11e7-8426-ea0b9f5e7e6c.PNG)
