### ISSUE TITLE
Private API - POST a Post

### ISSUE THREAD

**Issue by stephen-walsh** [TryGhost/Ghost#9098]
As per the document that i can get a bearer key for use when pushing a Post via the Private API.
the format of the push is

`curl -i \
-H "Authorization: Bearer <KEY>" \
-H "Content-Type: application/json" \
-X POST -d @file.json \
http://<SERVER>/ghost/api/v0.1/posts/`

where file.json is as follows... (I cant upload a json file to this ticket)
`{
  "posts": [
    {
      "id": "553719880000000000000000",
      "uuid": "f710fa6c-9254-2630-e3fa-f31e667a1eca",
      "title": "test",
      "slug": "test",
      "html": "<div class='kg-card-markdown'>test</div>",
      "feature_image": "image.jpg",
      "featured": false,
      "page": false,
      "status": "published",
      "locale": null,
      "visibility": "public",
      "meta_title": null,
      "meta_description": null,
      "created_at": "2017-10-04T09:50:55.736Z",
      "created_by": "1",
      "updated_at": "2017-10-04T09:50:55.736Z",
      "updated_by": "1",
      "published_at": "2017-10-04T09:50:55.736Z",
      "published_by": "1",
      "custom_excerpt": null,
      "codeinjection_head": null,
      "codeinjection_foot": null,
      "og_image": null,
      "og_title": null,
      "og_description": null,
      "twitter_image": null,
      "twitter_title": null,
      "twitter_description": null,
      "author": "1",
      "primary_tag": null,
      "url": "http://test.com",
      "comment_id": ""
    },
    {
      "id": "121708453100000000000000",
      "uuid": "4578dfae-d732-5199-46e8-581fbfc4ba7d",
      "title": "test2",
      "slug": "test2",
      "html": "<div class='kg-card-markdown'>test2</div>",
      "feature_image": "image.jpg",
      "featured": false,
      "page": false,
      "status": "published",
      "locale": null,
      "visibility": "public",
      "meta_title": null,
      "meta_description": null,
      "created_at": "2017-10-04T09:50:55.737Z",
      "created_by": "1",
      "updated_at": "2017-10-04T09:50:55.737Z",
      "updated_by": "1",
      "published_at": "2017-10-04T09:50:55.737Z",
      "published_by": "1",
      "custom_excerpt": null,
      "codeinjection_head": null,
      "codeinjection_foot": null,
      "og_image": null,
      "og_title": null,
      "og_description": null,
      "twitter_image": null,
      "twitter_title": null,
      "twitter_description": null,
      "author": "1",
      "primary_tag": null,
      "url": "http://test2.com",
      "comment_id": ""
    }
  ]
}`

The bug is that only the first post is taken and the remaining posts are ignored. I manually need to parse the json file and create new files for each post to then POST.

**Comment by ErisDS** [comment]
Hi @stephen-walsh, this is not a bug, it is the intended design of the API. Please read our [support guide](https://github.com/TryGhost/Ghost/blob/master/.github/SUPPORT.md) and refrain from using GitHub for support requests. If you need help with the API, please use [slack](https://ghost.org/slack).
