### ISSUE TITLE
Private API - POST a Post

### ISSUE THREAD

**Issue by stephen-walsh** [TryGhost/Ghost#9099]
as per bug #9098 once a post is pushed to the ghost server, you cannot edit the content.
The "html" tag of the REST POST call is filled correctly. After the POST the 'html' & 'plaintext' column are correctly shown in the database.

However, i believe because the column 'mobiledoc' is empty after the REST POST that the editor in ghost is unable to see the content to edit. Any edit here will override the REST POST content.

**Comment by ErisDS** [comment]
Hi @stephen-walsh, this is not a bug, it is the intended design of the API. Please read our [support guide](https://github.com/TryGhost/Ghost/blob/master/.github/SUPPORT.md) and refrain from using GitHub for support requests. If you need help with the API, please use [slack](https://ghost.org/slack).

**Comment by stephen-walsh** [comment]
Thanks @EricDS I'll have to admit that I'm surprised that these are design intent (missing values in the database and incorrect handling of json arrays)  
But I'm also aware that the API is v0.1 and its not going to right first time. 
But what ever process you guys want to take I hope you take some of the these comments onboard in an aid to better Ghost.
