### ISSUE TITLE
API accepts non-ObjectID id's when creating posts

### ISSUE THREAD

**Issue by kevinansfield** [TryGhost/Ghost#9100]
### Issue Summary

It's possible to POST to the `/posts/` endpoint including a numeric `id` attribute which is successfully saved to the database. When later trying to edit that post the server raises a `422 ValidationError` with the message:

```
Saving failed: Validation (matches) failed for id
```

### Steps to Reproduce

1. Use Postman or similar to send a `POST /posts/` request with a numeric ID property in the post's JSON
2. Open the new post in the admin area's editor
3. Attempt to save it

We should be ignoring (ideally) or at least validating ID attributes when creating posts via the API.

### Technical details:

* Ghost Version: 1.11.0

**Comment by mdornseif** [comment]
I would suggest that forbidding is better than ignoring. So better send an  `400 Bad Request` (or 422) status back then silently drop the parameter.

**Comment by kirrg001** [comment]
PR is welcome 😬

**Comment by acburdine** [comment]
I'm looking into this one 😄

**Comment by kirrg001** [comment]
I'll take that over for the next week.

**Comment by kirrg001** [comment]
This needs discussion first: https://github.com/TryGhost/Ghost/pull/9112#discussion_r143395136

**Comment by grantwinney** [comment]
I didn't want to open a whole new issue for something that's most likely related, so I'll post this here.

I was creating tags via the API this morning, and specifying a custom ID in the request body like this:

```json
{ "tags" : [{ "id": "willthiswork", "name": "maybe", "slug": "aslug" }] }
```

When I do a GET via the API to get the tag, I can see that the ID is still "willthiswork".

But when I do a DELETE via the API (or try to delete the tag in the Ghost admin area), I get the same error reported above.

The admin area shows an orange bar with _"Validation (matches) failed for id"_.

Postman displays:

```json
{
    "errors": [
        {
            "message": "Validation (matches) failed for id",
            "errorType": "ValidationError"
        }
    ]
}
```

**Comment by kirrg001** [comment]
@grantwinney Thanks. Yeah this issue is about missing validations. It shouldn't be allowed to set custom identifiers via the API, except there is a very good reason allowing this.

Happy about any help 👍

**Comment by gargol** [comment]
With JSON Schema validations landing in master for [posts](https://github.com/TryGhost/Ghost/pull/10488) and [tags](https://github.com/TryGhost/Ghost/pull/10486) Admin API endpoints, `id` fields are now stripped from the input and ignored during validation phase :+1:

**Comment by sliterok** [comment]
I have same sort of trouble when i'm trying to edit manually created user.
![image](https://user-images.githubusercontent.com/12751644/55680992-a0aa4780-593a-11e9-9d63-73e6744bdaad.png)
Id of the user should be fine, but seems that ghost is having some problems with that.
![image](https://user-images.githubusercontent.com/12751644/55681002-b3248100-593a-11e9-8180-5d248be234bd.png)
I couldn't find any code describing, what user id should be. Or any validation code.
Mine version of ghost is coming from [bitnami docker image](https://hub.docker.com/r/bitnami/ghost/)

**Comment by gargol** [comment]
Hey @sliterok. The only numerical id that is supported in Ghost is `1` and is reserved for internal usages. All other `id` fields are generated, unique [bson object ids](https://github.com/williamkapke/bson-objectid)https://github.com/TryGhost/Ghost/blob/e109c54/core/server/models/base/index.js#L630. Ideally you should not be editing these manually in the database :smiley:

**Comment by theinfosecguy** [comment]
Hey @naz ,

How to use BSON Object to create ID for users?
