### ISSUE TITLE
Editor cursor disappears at bottom of screen

### ISSUE THREAD

**Issue by kevinansfield** [TryGhost/Ghost#9105]
### Issue Summary

When typing with the cursor at the bottom of the editor, when you press <kbd>Enter</kbd> or otherwise cause the cursor to drop down the editor does not do a good job of keeping the cursor on screen.

### Steps to Reproduce

1. Edit or start a new post
2. Write content until the cursor is at the bottom of the editor
3. Keep typing or pressing <kbd>Enter</kbd>
4. Note how the cursor will disappear for a while until it drops far enough for the editor to detect and scroll it back into view

We should always ensure that the cursor is on screen when typing. There is a similar situation if you use <kbd>⬆</kbd> to move the cursor to the top of the screen.

![editor-cursor](https://user-images.githubusercontent.com/415/31236847-2940337e-a9ed-11e7-9f99-2b7534e76f71.gif)

### Technical details:

* Ghost Version: 1.12.0
* Browser/OS: Chrome/macOS

**Comment by volodymyrlut** [comment]
Working on this.

**Comment by toblerone1963** [comment]
Same problem here. But I would like to add that the cursor disappears also at the top of the screen.

**Comment by kevinansfield** [comment]
Closing as the editor was replaced in Ghost 2.0
