### ISSUE TITLE
Ghost blog main url link config issue

### ISSUE THREAD

**Issue by morandalex** [TryGhost/Ghost#9106]
I am configuring the main url in ghost blogging platform with the install on a local server.

One month ago I set as a main url wewone.net, but then I decided to change it. Now the main url is set as "blog.morandi.services" with the related Nginx configuration.

I noticed that if now I click on the link of the main page , it doesn't load the "blog.morandi.services" , but the old "wewone.net".

Infact , in the navigation setting page I can see that the default link is "wewone.net" not blog.morandi.services. 

![uyt](https://user-images.githubusercontent.com/9484568/31270224-bdc4e97c-aa83-11e7-812a-620270ffcf95.PNG)

The "production.config.js" is already set with the "url: https://blog.morandi.services " and the blog is running, all it seems ok, apart for the main url.

How could I fix?

Really thanks.

**Comment by ErisDS** [comment]
Please **do not** use GitHub for support. Read our [support guide](https://github.com/TryGhost/Ghost/blob/master/.github/SUPPORT.md).
