### ISSUE TITLE
IMPOPRTANT!!! In the zip of release 1.12 is a config.production.json file

### ISSUE THREAD

**Issue by larsauswsw** [TryGhost/Ghost#9108]
That's an critical error. Will mess up all self hosted instances of ghost!

**Comment by ErisDS** [comment]
Confirmed, it also contains sensitive information ☹️ 

Need to re-release

**Comment by kirrg001** [comment]
We have releases [1.12.1](https://github.com/TryGhost/Ghost/releases/tag/1.12.1). Thanks for reporting @larsauswsw 👋

**Comment by larsauswsw** [comment]
Your welcome.
