### ISSUE TITLE
Implement security.txt

### ISSUE THREAD

**Issue by crepererum** [TryGhost/Ghost#9110]
### Abstract
Consider implementing [security.txt](https://securitytxt.org/). This would be great for ghost.org as well as for self-hosted blogs.

### Sub-Tasks

- [ ] Add settings workflow (UI and backend) to store option to actually provide this feature, security mail address, PGP key, acknowledgements, and disclosure policy.
- [ ] Render and serve `security.txt` based on the settings

### Misc
I know that the mentioned standard just came out recently. I don't think this is a rather urgent feature to implement, but I want you to know that this could be helpful. Also it seems to be good to file this "RFC-like" issue before anyone starts to work on this feature, so misconceptions are less likely. Thank you :)

**Comment by ErisDS** [comment]
Hi @crepererum,

Thanks for bringing this new standard to our attention. We'll keep an eye on adoption. 
However, in the meantime it would be possible to add a `security.txt` file to your theme, and Ghost will serve it 😎

Closing this, as this isn't the kind of thing that Ghost tends to add UI for. We're not preventing users from implementing the standard as its easy enough to add the file to a theme.

In terms of Ghost.org, we'll consider this separately 😊
