### ISSUE TITLE
Accidental change of settings cache object

### ISSUE THREAD

**Issue by sahand12** [TryGhost/Ghost#9115]
### Issue Summary

file name: /core/server/settings/cache.js
line number: 111

In the cache wrapper object, we have 4 methods: get, set, getAll, and init. In the getAll function we first deep clone the `settingsCache` and then return it from the function to avoid the possibility of unwanted mutation. However, in the init method, in the end, we return the reference of the `settingsCache` not the clone of it. Shouldn't we clone it here too and then return?

```javascript 
return _.cloneDeep(settingsCache); // instead of 'return settingsCache;'
```

### Technical details:

* Ghost Version: 1.8.7

**Comment by kirrg001** [comment]
> However, in the init method, in the end, we return the reference of the settingsCache not the clone of it. Shouldn't we clone it here too and then return?

First of all, if you raise a bug issue, please describe or proof a broken behaviour. Just raising random questions about the code base is not really useful. Second, 
the return value from the init fn is not used at the moment and there is no need to pre-optimise things.

If you have any questions about the code base in the future, please use our `#contributing` channel in slack.
