### ISSUE TITLE
Possible bug in error-handler middleware

### ISSUE THREAD

**Issue by sahand12** [TryGhost/Ghost#9117]
### Issue Summary

filename: core/server/middleware/error-handler.js
line number: 117

```javascript
_private.BasicErorRenderer = function BasicErrorRenderer(err, req, res, next) {
    return res.send(res.statusCode + ' ' + err.message); // res.statusCode or err.statusCode ?
}
```
first, Error is spelled wrong in the first line (not such a big deal).
second, I think it should be ```err.statusCode``` instead of ```res.statusCode```.

### Technical details:

* Ghost Version: 1.8.7

**Comment by kirrg001** [comment]
Hey 👋

There is no bug. Take a look at [the call stack](https://github.com/TryGhost/Ghost/blob/master/core/server/middleware/error-handler.js#L139) and [the error preparation](https://github.com/TryGhost/Ghost/blob/master/core/server/middleware/error-handler.js#L52). 

If you have any questions about the code base in the future, please use our `#contributor` channel in slack.
