### ISSUE TITLE
Disable permalink UI when it has been overridden

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#9125]
In Ghost's UI we have a checkbox for permalink.

This allows us to support two main permalink structures: `/:slug/` and `/:year/:month/:day/:slug/`.

However, by overriding this setting in the database, it is possible to have a wide range of different slug settings.

At the moment the logic for the permalink UI works as follows:

Case 1: The default state is unchecked, which means permalinks are `/:slug/`.

![](https://puu.sh/xUAPs.png)

Case 2: If you tick the checkbox, you get dated permalinks in the format `/:year/:month/:day/:slug/`.

![](https://puu.sh/xUAP0.png)

Case 3: If you override the permalink setting in the database, to for example `/:primary_tag/:slug/`, the UI thinks that you have the dated permalinks set, and shows the box ticked, the same as case 2: 

![](https://puu.sh/xUAP0.png)

I propose that instead of looking like dated permalinks are in use, case 3 should appear as an unticked checkbox greyed out, in a similar fashion to how the custom post template dropdown is greyed out if you have an explicit slug template for that post.

**Comment by kevinansfield** [comment]
> I propose that instead of looking like dated permalinks are in use, case 3 should appear as an unticked checkbox greyed out, in a similar fashion to how the custom post template dropdown is greyed out if you have an explicit slug template for that post.

We'll need a new style for the checkbox as we don't currently have styles for disabled checkboxes.

As the permalink value is exposed to the client we probably also want to add a message here saying that it's been overridden and show what the value is.

**Comment by bnqtoan** [comment]
By the way, why do we need the trailing slash after every url?

I tried to add .html extension to the url, so I changed permalink to /:slug.html but it cause redirect loop. "/:slug.html/" works, but I (and my client) don't want the last "/" to show up.

**Comment by kevinansfield** [comment]
Closing because permalink UI was removed in Ghost 2.0. Permalinks are now controlled via [Dynamic Routing](https://docs.ghost.org/docs/dynamic-routing)
