### ISSUE TITLE
Apache2 redirecting to 127.0.0.1:2368

### ISSUE THREAD

**Issue by ilicmarko** [TryGhost/Ghost#9131]
### Issue Summary

I am having a problem where, when I access the domain I get redirected to `127.0.0.1:2368`. This happened when I tried to 'enable' SSL.

The blog worked when I entered `https` manually, so I changed the URL in the config to the secure one, also added the header and it won't work.

### Steps to Reproduce

1. Have apache2
2. Config:
```
<VirtualHost *:80>
    ServerName ilic.ninja 
    ServerAlias www.ilic.ninja

    Redirect permanent / https://ilic.ninja/
</VirtualHost>

<VirtualHost *:443>
    ServerName ilic.ninja
    ServerAlias www.ilic.ninja

    ProxyPass / http://localhost:2368/
    ProxyPassReverse / http://localhost:2368/
    ProxyPreserveHost   On
    ProxyRequests off

	SSLEngine on
	SSLCertificateFile "******/ilic_ninja.crt"
	SSLCertificateKeyFile "******/ilic.ninja.key"
	SSLCACertificateFile ******/ilic_ninja.ca-bundle"

    RequestHeader set X-Forwarded-Proto "https"
    ErrorLog ${APACHE_LOG_DIR}/ghost_error.log
    CustomLog ${APACHE_LOG_DIR}/ghost_access.log combined
</VirtualHost>
```
### Technical details:

* Ghost Version: 1.12.0
* Node Version: 4.7.3
* Browser/OS: Debian GNU/Linux 8 (jessie)
* Database: MariaDB 10.0.29

**Comment by ErisDS** [comment]
Hi @ilicmarko, 

Please **do not** use GitHub for support. Read our [support guide](https://github.com/TryGhost/Ghost/blob/master/.github/SUPPORT.md). You can use [slack](https://slack.ghost.org/) if you're not able to find the answer in the [docs](https://docs.ghost.org/).
