### ISSUE TITLE
AMP generation breaks  in-page anchor URLs

### ISSUE THREAD

**Issue by kevinansfield** [TryGhost/Ghost#9136]
### Issue Summary

As part of the AMP generation we attempt to make all URLs absolute however this is partly breaking in-page anchor tags so that clicking them leaves the AMP page.

### Steps to Reproduce

1. Add the following markdown to a post:
    ```markdown
    [test](#test)

    ... content ....

    <a name="test"></a>
    ```
2. Save and/or publish the post then open the AMP version
3. Click on the <a href="#test">test</a> link
4. Note that you are taken to `/:slug/#test` instead of staying on the page at `/:slug/amp/#test`

If we have `href` attributes that reference in-page anchors we should be leaving them alone rather than trying to make them absolute.

### Technical details:

* Ghost Version: 1.13.0

**Comment by AileenCGN** [comment]
The only other place where the `make-absolute-urls.js` util is used, is for the RSS feed. I'm highly in favour of not converting any `href` attribute that starts with `#`, marking an internal anchor link.

I tested the behaviour of not converting those links (starting with `#`) with Feedly, which is the most popular RSS reader, and Feedly actually converts those links automatically. I therefore see no benefit of converting these links at all and will submit a PR which changes this behaviour.

If you can think of any other reason, why those links **should** be converted, please let me know.

**Comment by AileenCGN** [comment]
The only question mark I still have is for links like e. g. `/about#something`. It would be possible to convert these links - when in `amp` context - into `/about/amp#something`, but it would need further information (is it a page or a post?), because this link *could* refer to a page which is currently not rendered as AMP page.

**Comment by kevinansfield** [comment]
> the only question mark I still have is for links like e. g. /about#something.

I think those should be left alone, anything that doesn't start with a # is an external link. In the above case, what's to say the `/about#something` link is actually outside of Ghost (if Ghost is on `/blog` for example), we can't assume that `/about/amp#something` exists.
