### ISSUE TITLE
Ordered list item in between

### ISSUE THREAD

**Issue by NistorCristian** [TryGhost/Ghost#9139]
It would be nice when you have an ordered list and add an item in the middle of the list to reset the list counter. Right now we need to edit all the next items to be ok.

![final](https://user-images.githubusercontent.com/12628663/31502199-0feb8594-af75-11e7-8e71-0801f0489910.gif)

* Ghost Version: 1.10

**Comment by kevinansfield** [comment]
@NistorCristian this would be best opened as a feature request/issue on [CodeMirror's repository](https://github.com/codemirror/CodeMirror)

When our [mobiledoc](http://bustle.github.io/mobiledoc-kit/demo/) based editor lands this will be supported outside of markdown cards.
