### ISSUE TITLE
ghost.url.api error when filtering multi word tags

### ISSUE THREAD

**Issue by bobthemac** [TryGhost/Ghost#9146]
Welcome to Ghost's GitHub repo! 👋🎉

Do you need help or have a question? Please come chat in Slack: https://ghost.org/slack 👫. Found a bug? Please fill out the sections below... thank you 👍

If your issue is with Ghost CLI, please report it on the CLI repo ➡️ https://github.com/TryGhost/Ghost-CLI/issues/new.

### Issue Summary

When using ajax for loading posts using `ghost.url.api` to load posts with specific tags. The code works fine with tags that are a single word such as `ghost.url.api("posts", {limit: pagination, include: 'tags', filter: "tag:test", page: nextPage})` the problem comes when tags have more than one word such as the "Getting Started" tag used in the posts ghost comes with like `ghost.url.api("posts", {limit: pagination, include: 'tags', filter: "tag:Getting Started", page: nextPage})` you get an error in the log on the browser an error 422 (Unprocessable Entity).  This happens on Chrome and Linux as well as Windows.

### Steps to Reproduce

Make an ajax request using the ghost.url.api and filter by tags and a two letter tag such as "Getting Started" like this `ghost.url.api("posts", {limit: pagination, include: 'tags', filter: "tag:Getting Started", page: nextPage})`

### Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?
There are two possible things that I could expect to happen the first is that you are not allowed to enter multi word tags in the first place or second that they work the same as single words that currently work.

### Technical details:

* Ghost Version: 1.14.0
* Node Version: v6.11.4
* Browser/OS: Chrome/Debian
* Database: MySQL

**Comment by ErisDS** [comment]
Hi @bobthemac 

Please do not use GitHub for support. Read our [support guide](https://github.com/TryGhost/Ghost/blob/master/.github/SUPPORT.md). You can use [slack](https://slack.ghost.org/) if you're not able to find the answer in the [docs](https://docs.ghost.org/).

**Comment by bobthemac** [comment]
This isn't support it's a bug
