### ISSUE TITLE
Some chars can't be typed in Unsplash search on Tags screen

### ISSUE THREAD

**Issue by MertcanGokgoz** [TryGhost/Ghost#9147]
### Issue Summary

Some keys do not work. Like "k" and "c"

### Steps to Reproduce

1. Login ghost admin area
2. Left menu and click tags
3. click any tags
4. I click to upload photos via Unsplash
5. I tried to write "c" and "k" containing sentences
6. I could not

### Technical details:

* Ghost Version: 1.14.0
* Node Version: 6.11.4
* Browser/OS: Firefox Quantum 57.0b8 and Chrome Version 61.0.3163.100 
* Database: Mysql

**Comment by mellisdesigns** [comment]
I tried to replicate this on local and was unable. Any more info you can give. Maybe a GIF? I was using `chrome 61.0` and `ghost 1.14`. Any more replication steps would be ace!

**Comment by MertcanGokgoz** [comment]
I'm using a Turkish keyboard layout, there is just such a situation in the field of tags and no problem in other parts(stories etc) I can not write "macbook" 🗡  k and c do not print :)

**Comment by kevinansfield** [comment]
I've not been able to replicate this but I only have a UK English keyboard layout.

It's possible that this may be resolved as part of the on-going work in https://github.com/TryGhost/Ghost-Admin/pull/892 - we'll be swapping the 3rd party component that is used for tags input.

If anyone with a non-english keyboard layout cares to take a look at this issue we'll be glad to accept any PRs 😄

**Comment by vikaspotluri123** [comment]
I'm able to replicate this in 1.14.0 w/ a US English keyboard layout. It occurred in Chrome, FireFox and Edge.

1. Go to tags page. The instance I'm testing with is a production install specifically for testing, so there's only the getting-started tag. Therefore, the URL updates to `/#/settings/tags/getting-started`
2. Click the camera icon in the tag settings sidebar to set the image. The unsplash search pops up. URL stays the same
3. Type any key in the search field - I tested a-z, and c, j, k were dropped
    - The j / k keys didn't do anything noticeable. Since gMail and other apps use j / k for previous and next, I added 2 tags and tried again which showed pressing `j` advanced the url to `/#/settings/tag/test-tag-2` and pressing `k` moved it back to `/#/settings/tag/test-tag-1`
    - The `c` key updated the url to `/ghost/#/settings/tags/new` which seems unexpected - from what I understand I was editing the getting-started tag

Based on this, and my limited knowledge of exactly how the admin interface works, my guess is the keyboard shortcuts aren't disabled when the unsplash screen is rendered in the tags page

**Comment by kevinansfield** [comment]
👍 confirmed the behaviour, sorry I misread initially as the tags input rather than tags screen.

**Comment by mellisdesigns** [comment]
From what I have found the `gh-unsplash` component is rendered into a wormhole. Because of this, the tags route does not lose it's scope and the shortcuts continue you to be active.

The shortcuts set on the tags route are as follows. `k`, `j` and `c` cannot be entered into the search field on the `gh-unsplash` template.

```
shortcuts: {
  'up, k': 'moveUp',
  'down, j': 'moveDown',
  left: 'focusList',
  right: 'focusContent',
  c: 'newTag'
},
```

- [ ] wormhole templates need to disable or override the current routes keyboard shortcuts when active.
