### ISSUE TITLE
Changelog in main repository

### ISSUE THREAD

**Issue by Tim15** [TryGhost/Ghost#9148]
Is there a reason the changelog is in a Gist? Could you put it in a CHANGELOG.md or similar?

**Comment by kevinansfield** [comment]
@Tim15 Ghost's primary audience is non-technical end users who will very rarely interact with the git repo. All user-facing changes for are summarised for each release and visible at https://github.com/TryGhost/Ghost/releases for the entirety of the project across the parallel release, LTS, and beta branches (when they are running).

The gists attached to the changelogs are just git commit logs, you can see the same thing going back for the entirety of the project by looking at the [Ghost](https://github.com/TryGhost/Ghost/commits/master) and [Ghost-Admin](https://github.com/TryGhost/Ghost-Admin/commits/master) commit logs.
