### ISSUE TITLE
Deprecated modules

### ISSUE THREAD

**Issue by MaluNoPeleke** [TryGhost/Ghost#9151]
I have to update Ghost manually because my hoster doesn't support using/installing the cli so I just updated to 1.14 ([with my script](https://www.peleke.de/ghost-1-0-aktualisierung-bei-uberspace/)) and got the following warning messages:

```npm WARN deprecated nodemailer@0.7.1: All versions below 4.0.1 of Nodemailer are deprecated. See https://nodemailer.com/status/
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated mimelib@0.2.19: This module is deprecated
npm WARN prefer global jison@0.4.13 should be installed with -g
```

Nonetheless everything is working as expected but I just wanted to let you know about it.

**Comment by kevinansfield** [comment]
Hey @MaluNoPeleke 👋 Those warning messages are fine, we're aware of them as we get them during development too 😉 They'll be resolved as our dependencies/sub-dependencies get updated.
