### ISSUE TITLE
something goes wrong with by ghost admin-client 1.4 cause by the header name:authorization

### ISSUE THREAD

**Issue by Tomihaohao** [TryGhost/Ghost#9155]
something gose wrong with my ghost-client
when i login the admin system

### describe
when i login the system the chrome send this request
ghost/api/v0.1/users/me/?include=roles

### the http header like this
Accept:application/json, text/javascript, */*; q=0.01
App-Pragma:no-cache
Authorization:Bearer Uy8Sd6Gx3fx7m36ARRvOFwbU6htogBYMExHUtgJpxekFJrfPx8hHkmsCvFXNTAH4ohabxB01jUIuQrv23p752G3OpJN0H5iRZEp64OQUDHCDHJDka1uZk9D5HkEmctESLtjnqhhpmSPtRk2Uq1Y4872OSHzaNakwjMXXS1Zt0nFk6QgnJlAyet0BOGDSsdDS
Content-Type:application/json; charset=UTF-8
User-Agent:Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36
X-Ghost-Version:1.14
X-Requested-With:XMLHttpRequest

however the server crash
### the error is 
NAME: UnauthorizedError
MESSAGE: Access denied.

i found the problem is here 
when the nginx proxy this request the header name  Authorization is lost
###the header request get by server like this
 'x-abc': '1234',
  'x-nginx-proxy': 'true',
  connection: 'close',
  'app-pragma': 'no-cache',
  'content-type': 'application/json; charset=UTF-8',
  accept: 'application/json, text/javascript, */*; q=0.01',
  'x-requested-with': 'XMLHttpRequest',
  'x-ghost-version': '1.14',
  'user-agent': 'Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36',
  referer: 'http://xxx.xxxx.xxx/ghost/',
  'cache-control': 'max-age=1800' }

so i used the fiddler try again,however this time i change the Authorization to X-Authorization
opps the server get this header named X-Authorization but the Authorization  is still lose ,

so the server can't get the bearer token  authUtils.getBearerAutorizationToken(req) returns false 
i can't login in the admin-client 
how to fix it ?
hope soon

### nginx conf
http {
    include       mime.types;
    default_type  application/octet-stream;

    #log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
    #                  '$status $body_bytes_sent "$http_referer" '
    #                  '"$http_user_agent" "$http_x_forwarded_for"';

    #access_log  logs/access.log  main;
    access_log off;
    sendfile        on;
    #tcp_nopush     on;

    #keepalive_timeout  0;
    keepalive_timeout  65;
    #gzip  on;
    underscores_in_headers on;
    server {
        listen       80;
        listen [::]:80;
        server_name  helloGhost; 
        #charset koi8-r;
        #access_log  logs/host.access.log  main;

        location / {
             proxy_set_header    X-Real-IP           $remote_addr;
             proxy_set_header    X-Forwarded-For     $proxy_add_x_forwarded_for;
             proxy_set_header    Host                $http_host;
             proxy_set_header    X-NginX-Proxy       true;
             proxy_http_version  1.1; 	
	         proxy_pass http://127.0.0.1:2368/; 
	  	              #root   html;
            #index  index.html index.htm;
	    
        }
	location ~ /.well-known { 
        allow all;
    	}
         client_max_body_size 50m;
	send_timeout 500;
        proxy_read_timeout 500;
        proxy_connect_timeout 500;

        #error_page  404              /404.html;

        # redirect server error pages to the static page /50x.html
        #
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   html;
        }

**Comment by kevinansfield** [comment]
Hey @Tomihaohao. Please do not use GitHub for support, our [support guide](https://github.com/TryGhost/Ghost/blob/master/.github/SUPPORT.md) was linked in the GitHub notification above the issue creation form and has details about what issues you should raise here and which issues should be handled elsewhere. (Many projects have their own support guidelines and GitHub highlights them for you, please read them before opening issues 😄)

You can use [slack](https://slack.ghost.org) to get community support if you're not able to find the answer in the [docs](https://docs.ghost.org).
