### ISSUE TITLE
How to add an image url to a post cover?

### ISSUE THREAD

**Issue by zhangshuzhen** [TryGhost/Ghost#9156]
How to add an image url to a post cover?

**Comment by AileenCGN** [comment]
Hi @zhangshuzhen

Please **do not** use GitHub for support. Read our [support guide](https://github.com/TryGhost/Ghost/blob/master/.github/SUPPORT.md). You can use [slack](https://slack.ghost.org/) if you're not able to find the answer in the [docs](https://docs.ghost.org/).

**Comment by zhangshuzhen** [comment]
OK
