### ISSUE TITLE
Json Import: Unexpected end of JSON input

### ISSUE THREAD

**Issue by austriancoder** [TryGhost/Ghost#9167]
### Issue Summary

It is impossible to import Json Backup from 0.11.12.

@4000000059ebc0960339fb2c INFO [2017-10-21 21:47:56] "DELETE /ghost/api/v0.1/db/" 204 1143ms
@4000000059ebc0ac2c2b1f0c Unhandled rejection SyntaxError: Unexpected end of JSON input
@4000000059ebc0ac2c2b26dc     at Object.parse (native)
@4000000059ebc0ac2c2b2ac4     at onSaving (/home/cgmeiner/ghost/core/server/models/post.js:237:67)
@4000000059ebc0ac2c2b2ac4     at onSaving (/home/cgmeiner/ghost/core/server/models/base/index.js:117:50)
@4000000059ebc0ac2c2b2eac     at /home/cgmeiner/ghost/node_modules/bookshelf/lib/base/events.js:176:25
@4000000059ebc0ac2c2b2eac     at tryCatcher (/home/cgmeiner/ghost/node_modules/bluebird/js/release/util.js:16:23)
@4000000059ebc0ac2c2c3c34     at MappingPromiseArray._promiseFulfilled (/home/cgmeiner/ghost/node_modules/bluebird/js/release/map.js:61:38)
@4000000059ebc0ac2c2c401c     at MappingPromiseArray.PromiseArray._iterate (/home/cgmeiner/ghost/node_modules/bluebird/js/release/promise_array.js:114:31)
@4000000059ebc0ac2c2c4404     at MappingPromiseArray.init (/home/cgmeiner/ghost/node_modules/bluebird/js/release/promise_array.js:78:10)
@4000000059ebc0ac2c2c672c     at MappingPromiseArray._asyncInit (/home/cgmeiner/ghost/node_modules/bluebird/js/release/map.js:30:10)
@4000000059ebc0ac2c2c672c     at Async._drainQueue (/home/cgmeiner/ghost/node_modules/bluebird/js/release/async.js:138:12)
@4000000059ebc0ac2c2c6b14     at Async._drainQueues (/home/cgmeiner/ghost/node_modules/bluebird/js/release/async.js:143:10)
@4000000059ebc0ac2c2c9224     at Immediate.Async.drainQueues (/home/cgmeiner/ghost/node_modules/bluebird/js/release/async.js:17:14)
@4000000059ebc0ac2c2c9224     at runCallback (timers.js:672:20)
@4000000059ebc0ac2c2c960c     at tryOnImmediate (timers.js:645:5)
@4000000059ebc0ac2c2c960c     at processImmediate [as _immediateCallback] (timers.js:617:5)
@4000000059ebc0bd2ea4067c INFO [2017-10-21 21:48:35] "POST /ghost/api/v0.1/db/" 200 60120ms

The Json backup looks valid

### Steps to Reproduce

1) Fresh 1.15.0 setup
2) Try to import https://christian-gmeiner.info/tmp/chaos-computing.ghost.2017-08-26.json

### Technical details:

* Ghost Version: 1.15.0
* Node Version: v6.11.1
* Browser/OS: Chrome 62/Linux
* Database: MySQL

**Comment by AileenCGN** [comment]
I am not able to reproduce this. You're `json` export works fine for me as an import...

@kirrg001 is this something, you've seen before?

**Comment by austriancoder** [comment]
Is there any setting to influence the max upload size? I have the feeling that the Json-file is not fully uploaded.

**Comment by kevinansfield** [comment]
@austriancoder Ghost itself doesn't have an upload size limit. You may have an upload size limit at the web server or proxy level - if you've used Ghost-CLI to configure nginx then the [max upload size is set to 50MB](https://github.com/TryGhost/Ghost-CLI/blob/master/extensions/nginx/templates/nginx.conf#L21)

**Comment by AileenCGN** [comment]
Hmm... not sure if that's really the issue. The file size of the linked export file is only 330kb... That shouldn't usually be an issue, right?

**Comment by austriancoder** [comment]
I am not using Ghost-CLI as it is not supported by my hoster. In the end I start ghost like this:
`exec /bin/env NODE_ENV=production node /home/cgmeiner/ghost/index.js`

I tried to enable extra debug output but there is not much information. Is there a way to debug this?

**Comment by ErisDS** [comment]
We're sorry to hear you're having problems, however this looks like a problem with how you're using Ghost rather than a bug. We only keep Github issues open for bugs and in-progress feature work, please read our [support guide](https://github.com/TryGhost/Ghost/blob/master/.github/SUPPORT.md). You can always use our [slack](https://slack.ghost.org/) community - https://slack.ghost.org, if you're not able to find the answer in our [documentation](https://docs.ghost.org/) - https://docs.ghost.org.

Can re-open if there's any indication that this is a bug, but seems like a config/environment issue to me.
