### ISSUE TITLE
Chat bot integration

### ISSUE THREAD

**Issue by gauthamzz** [TryGhost/Ghost#9168]
Is there any plans of integration with messenger chatbot services such as chatfuel or wit.ai  or others in the future. Bots are a great way to engage users.

**Comment by JohnONolan** [comment]
Kind of :) We're working on a Zapier integration which will open up 750+ different possible integrations. We only keep Github issues open for bugs and in-progress feature work, but always happy to chat about future ideas over on our slack community - https://slack.ghost.org
