### ISSUE TITLE
Can shedule publish article on other time that CEST

### ISSUE THREAD

**Issue by Dryusdan** [TryGhost/Ghost#9169]
Hi
Today I surprising : If you want shedule a publication, it in CEST time, but where liviing int UTC+1 time, we make conversion... 
It's possible to change the shedule timezone ?

regard :)

**Comment by AileenCGN** [comment]
Hey @Dryusdan 👋 

The scheduler will always use the timezone that is set in Settings - General.

Please do not use GitHub for support. Read our [support guide](https://github.com/TryGhost/Ghost/blob/master/.github/SUPPORT.md). You can use [slack](https://slack.ghost.org/) if you're not able to find the answer in the [docs](https://docs.ghost.org/).

Closing this, as it's not an issue with Ghost.

**Comment by Dryusdan** [comment]
>  The scheduler will always use the timezone that is set in Settings - General.

!(My setting is "GMT+1")[https://img4.hostingpics.net/pics/373595Capture.png] and !(shedule publish date is "CEST" )[https://img4.hostingpics.net/pics/742576Capture2.png]

So, I think is a bug ^^  
If is not, don't anwser but is not normal, I think

**Comment by AileenCGN** [comment]
@Dryusdan `CEST` mean Central European Summer Time, which is currently the same as `GMT+1`.
You can also see this by the time shown to you: `14:04` in Settings and `14:09` and earliest time to schedule, which is set to a minimum of 5 minutes from now.

**Comment by Dryusdan** [comment]
Ho, I'm stupid. I confused with Pacific time...

But, I shedule an article to publish 7 hours later (9:30am) and not publish himself... Hum... I'm make some test and I became if I found problem ^^

I'm so sorry for disturbing 😶
