### ISSUE TITLE
⚡ Support for amp-twitter component

### ISSUE THREAD

**Issue by southrop** [TryGhost/Ghost#9172]
### Issue Summary

According to [A complete guide to ⚡AMP templates in Ghost](https://dev.ghost.org/custom-amp-themes/), the `{{amp_components}}` block detects and automatically includes any scripts for extended [components](https://www.ampproject.org/docs/reference/components). However, this does not seem to work on tweets, perhaps because embedded tweets use the `blockquote` element which is allowed in AMP.

For example, this is what the "Embed tweet" button on Twitter gives you to paste on your site:

```html
<blockquote class="twitter-tweet" data-lang="en">
    <p lang="en" dir="ltr">It is finally sinking through. 46% OF PEOPLE BELIEVE MAJOR NATIONAL NEWS ORGS FABRICATE STORIES ABOUT ME. FAKE NEWS, even worse! Lost cred.</p>
    &mdash; Donald J. Trump (@realDonaldTrump) <a href="https://twitter.com/realDonaldTrump/status/922072236592435200?ref_src=twsrc%5Etfw">October 22, 2017</a>
</blockquote>
<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>
```

### Steps to Reproduce

1. Create a post that embeds a tweet
2. View the AMP version of the post
3. Observe that the plain `blockquote` is displayed rather than the tweet.

The desired behaviour here would be to detect the `blockquote` is a tweet (perhaps using the `class="twitter-tweet"`?), and replace it with an [amp-twitter](https://www.ampproject.org/docs/reference/components/amp-twitter.html) element.

When I first viewed the AMP page of a blog post I wrote on Ghost, I was disappointed with how poor it looked because of how many tweets I had embedded in my post.

### Technical details:

* Ghost Version: 1.15.0
* Node Version: 6.11.4
* Browser/OS: N/A
* Database: MySQL

**Comment by AileenCGN** [comment]
Hi @southrop

Thanks for the idea!

We only keep Github issues open for bugs and in-progress feature work, but always happy to chat about future ideas over on our  [slack](https://slack.ghost.org/) community - https://slack.ghost.org.

**Comment by southrop** [comment]
Hi Aileen,

Thanks for the feedback. I did a quick search and noticed that someone had actually mentioned something similar just over a year ago now, and it seems nothing developed from that afterwards. Would it perhaps be better to go upstream with this idea, seeing as Ghost seems to be using the amperize library for AMP conversion?
