### ISSUE TITLE
Node Version 8.8.1 unsupported?

### ISSUE THREAD

**Issue by danger89** [TryGhost/Ghost#9185]
### Issue Summary

Trying to install Ghost with Node version 8.8.1.
But only 8.8.0 is supported?

https://docs.ghost.org/v1/docs/supported-node-versions

Why is 8.8 supported but 8.8.1 not?

### Steps to Reproduce
1. curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
2. sudo apt-get install -y nodejs (installs 8.8.1)
3. ghost install

### Technical details:

* Ghost Version: ?
* Ghost CLI version: 1.1.3
* Node Version: 8.8.1
* Browser/OS:
* Database: MySQL / sqlite

**Comment by vikaspotluri123** [comment]
The CLI doesn't currently support 8.x, but ghost does. To get around this, you need to set the env var `GHOST_NODE_VERSION_CHECK` to anything but false so the CLI won't check for you

**Comment by kevinansfield** [comment]
Thanks @vikaspotluri123 👍 

@danger89 node 8 support has only just (yesterday) landed in Ghost and hasn't been officially announced yet. You can use the workaround for Ghost-CLI installs mentioned above or wait for the next version of Ghost-CLI which should be out in a few days.
