### ISSUE TITLE
Upgrading to 0.11.3

### ISSUE THREAD

**Issue by krumjahn** [TryGhost/Ghost#9195]
### Issue Summary

I'm upgrading my ghost hosted on digital ocean. When I run npm start --production, I get this error:

<img width="922" alt="screen shot 2017-10-29 at 4 21 12 pm" src="https://user-images.githubusercontent.com/505516/32228217-9c73bbcc-be88-11e7-9e8e-c23806b9cecc.png">

* Browser/OS: chrome

I'm using their 1 click deploy image here: https://www.digitalocean.com/products/one-click-apps/ghost/

**Comment by kirrg001** [comment]
Hi @krumjahn!

We're sorry to hear you're having problems, but ask that you do not use our GitHub repo for support. Please read our [support guide](https://github.com/TryGhost/Ghost/blob/master/.github/SUPPORT.md). You can always use our [slack](https://slack.ghost.org/) community - https://slack.ghost.org, if you're not able to find the answer in our [documentation](https://docs.ghost.org/) - https://docs.ghost.org.
