### ISSUE TITLE
Reading time helper

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#9200]
A common feature on publications nowadays is an indication of how long content will take to read.

This is usually based on a word count divided by an average reading rate, with some modifier based on the number of images.

A good reference is: https://blog.medium.com/read-time-and-you-bc2048ab620c
jQuery plugin as ref: https://github.com/michael-lynch/reading-time (this requires the content to be on the page)

These things all pretty much assume English, but should work okish for other latin languages. 

For now (v1):

- Word count: can be calculated from the content (see [Ghost-Admin's version](https://github.com/TryGhost/Ghost-Admin/blob/4a604ce64ff7936dca9ec0210870193b6dc87ce3/app/utils/word-count.js)
- image count: use 1 if there's a featured image for the post, 0 if not
- average reading rate: 275, hardcoded

Implementation should live in the theme layer, e.g. we only do this calculation when the reading time helper is used. If we find more use cases for including statistics, we can do more of this at the API layer & optimise how it works later.

- The helper itself should be `{{reading_time}}`. 
- It _must_ work in post listings as well as on the post page, i.e. when the content isn't written out anywhere.

_Thanks to @erikstern-r7 for the use case & reference material._

-----

Potential improvements for later include:

- Grab the real number of images
- Allow the reading rate to be configured
- Allow word count function to be replaced for other languages

------

_Got a use case for themes? If you have a use case that you can't solve with the existing theme tools, please come tell us about it in [#themes](https://slack.ghost.org)._

**Comment by AileenCGN** [comment]
I added the `later` label, to keep in mind, that we still wanna build a v2 for it:

> Potential improvements for later include:
> - Grab the real number of images
> - Allow the reading rate to be configured
> - Allow word count function to be replaced for other languages
