### ISSUE TITLE
Ability to enable AMP per post

### ISSUE THREAD

**Issue by martgnz** [TryGhost/Ghost#9202]
### Issue Summary

For certain content, as interactive graphics embedded into a story, AMP is quite hostile. Now that Twitter has started to [redirect to AMP](https://searchengineland.com/twitter-ramps-amp-278300) these posts look broken for a normal user, which doesn't realize what's wrong with the missing content.

A way to solve this would be a checkbox on the post settings page to enable AMP per post, overriding the global setting. This way users would be redirected to the real URL on interactive or art-directed content.

### Steps to Reproduce

1. Make a cool graphic and add it to your Ghost post.
2. If you arrive to the post via Google or Twitter the content will be missing and the page will appear broken.

**Comment by kirrg001** [comment]
Hi @ @martgnz 

Thanks for the idea!

We only keep Github issues open for bugs and in-progress feature work, but always happy to chat about future ideas over on our  [slack](https://slack.ghost.org/) community - https://slack.ghost.org.
