### ISSUE TITLE
How to delete useless images from /path/to/ghost/content/images

### ISSUE THREAD

**Issue by billypon** [TryGhost/Ghost#9204]
How to delete useless images from /path/to/ghost/content/images, include content's image and feature image, after I update post.

**Comment by AileenCGN** [comment]
Hi @billypon,

We're sorry to hear you're having problems, but ask that you do not use our GitHub repo for support. Please read our [support guide](https://github.com/TryGhost/Ghost/blob/master/.github/SUPPORT.md). You can always use our [slack](https://slack.ghost.org/) community - https://slack.ghost.org, if you're not able to find the answer in our [documentation](https://docs.ghost.org/) - https://docs.ghost.org.
