### ISSUE TITLE
Using http://server:port for url during ghost install ignores port #

### ISSUE THREAD

**Issue by awbacker** [TryGhost/Ghost#9208]
When installing and using a URL with a port in it, the port is seen but the value is replaced with 2368 in both the URL and the `port` setting in the config.  

Steps performed:
----
* Create directory `/opt/ghost-v1/`, and `chown ghost:ghost` that thing
* Run ghost install on a fresh install as root
* Enter "https://somesite.co:4000" as the url

Results:
----
* Config contains `url = https://somesite.co:4000`
* Config contains `port = 2368`

Desired Results:
----
Not really sure what is the right/easy/common way to go.  It would be nice to have 2 settings, one for port and one for url, though I could just edit the config file after and remove the `:4000` from the blog url, since its fronted by nginx.  But if its there they should at least be the same.

Install Output:
----
```bash
root@linode:/opt/ghost-v1# ghost install --db=sqlite3
✔ Checking system Node.js version
✔ Checking current folder permissions
✔ Checking operating system
ℹ Checking MySQL is installed [skipped]
✔ Checking for latest Ghost version
✔ Setting up install directory
✔ Downloading and installing Ghost v1.16.2
✔ Finishing install process
? Enter your blog URL: http://somesite.co:4000
✔ Configuring Ghost
✔ Setting up instance
Running sudo command: chown -R ghost:ghost /opt/ghost-v1/content
✔ Setting up "ghost" system user
? Do you wish to set up Nginx? No
ℹ Setting up Nginx [skipped]
Task ssl depends on the 'nginx' stage, which was skipped.
ℹ Setting up SSL [skipped]
? Do you wish to set up Systemd? No
ℹ Setting up Systemd [skipped]
Running sudo command: /usr/lib/node_modules/ghost-cli/node_modules/.bin/knex-migrator-migrate --init --mgpath /opt/ghost-v1/current
✔ Running database migrations
? Do you want to start Ghost? No
```
```
root@linode:/opt/ghost-v1# cat config.production.json
{
  "url": "http://somesite.co:2368/",
  "server": {
    "port": 2368,
    "host": "127.0.0.1"
  },
```

**Comment by awbacker** [comment]
Should I move these issues to the `ghost-cli` repo? I didn't notice I was in the wrong one, have them both open!

**Comment by ErisDS** [comment]
@awbacker yes please 👍
