### ISSUE TITLE
Read RSS Post Description from Excerpt

### ISSUE THREAD

**Issue by rambii** [TryGhost/Ghost#9210]
### Issue Summary

I was expecting the post excerpt to appear in the rss content field. It currently only pulls the value from the meta_description and will show 50 words from the full content otherwise. 

Maybe adding another fallback in [here](https://github.com/TryGhost/Ghost/blob/2941932ebe869e3dab4ada06eb689628263b9665/core/server/data/xml/rss/index.js#L94) would be a simple option?

Like that the excerpt does not need to be copied to another text field preventing duplicates.

### Steps to Reproduce

1. Insert (a short) excerpt for a post without inserting a meta description
2. Check RSS feed and the <description> will have 50 words (more than the excerpt)

### Technical details:

* Ghost Version: 1.16.2

**Comment by kevinansfield** [comment]
@rambii 👍 good catch, we should probably be using the custom excerpt in place of the meta description if one is available.
