### ISSUE TITLE
Public API negatively impacts CSP

### ISSUE THREAD

**Issue by karai17** [TryGhost/Ghost#9212]
Ghost's public API injects inline JavaScript which forces users to weaken their X-Content-Security-Policy to use it.

When placing the `{{ghost_head}}` tag in my theme, it injects several `<script>` tags. Some of these have a `src` to a file, others are simply inline code. This has a negative affect on securing a website via CSP as you have to open your blog up to potential XSS attacks to use the public API.

The CSP I want to use is:

```
add_header X-Content-Security-Policy "default_src https:";
```

The CSP I have to use is:

```
add_header X-Content-Security-Policy "default_src https: 'unsafe-inline' 'unsafe-eval'";
```

Using [securityheaders.io](https://securityheaders.io), my rank gets downgraded from `A+` to `A`.

### Technical details:

Docker Image: `ghost:latest`

**Comment by jloh** [comment]
Duplicate of #7299
