### ISSUE TITLE
v0.11 docs: links give 404s, download .zip gives newer ghost version

### ISSUE THREAD

**Issue by awbacker** [TryGhost/Ghost#9216]
The documentation for v0.11, mostly the links, is broken right now:

Examples pulled from `https://docs.ghost.org/v0.11/docs/installing-ghost-on-linux`:

* Links use `v0.11.9`, as in `https://docs.ghost.org/v0.11.9/..` which gives a 404  
 * Change to `ghost.org/v0.11/` and they work

* Install links to `ghost-latest.zip` which isn't v0.11.x, its 1.16.2 (as of now).  
 * Needs to link directly to the last v0.11 release

Similar issues in the mac install page, but I think the gist is clear.  I can work around the issues by manually changing the links (copy + paste!)  but I'm not sure how to handle the issue with the zipfile dowloads.

**Comment by vikaspotluri123** [comment]
If you want to, you can suggest these edits! Click the suggest edits button at the top right of the page 😄

**Comment by awbacker** [comment]
Got it.  I'm looking at it now :) I've not used readme.io before (but we may start!) and didn't even see or recognize the importance of that little think.  In fact, I went back and kept looking for it at the bottom of the page.  Had to re-read your comment twice.  

This `flat` style where links don't look like links is frustrating :) I thought that was just a header, like "table of contents"!

**Comment by awbacker** [comment]
Most of the links have been suggested as fixes now.  One thing I can't really do is change the download link listed, since I don't know what it should be:

```
# this should point to v0.11.x?  9? 10?
curl -L https://ghost.org/zip/ghost-latest.zip -o ghost.zip 
```

**Comment by vikaspotluri123** [comment]
My thoughts are [the latest 0.x release](https://github.com/TryGhost/Ghost/releases/tag/0.11.12) - if it's the right one, then there's no issue; otherwise, this will be brought to the reviewer's attention and they can perform the necessary fixes.

**Comment by kevinansfield** [comment]
Thanks for bringing that to our attention and submitting the suggested edits @awbacker! I'm going through and updating the docs now, sorry it wasn't caught sooner

**Comment by kevinansfield** [comment]
Docs and download links have been updated
