### ISSUE TITLE
Custom Post Templates referred as no supported in Documentation

### ISSUE THREAD

**Issue by Playrom** [TryGhost/Ghost#9222]
### Issue Summary

According the Themes Docs [here](https://themes.ghost.org/docs/post-context#section-templates) the custom post templates are not currently not supported, but the #9073 has been merged with the last major release.

The Page Context doc is instead updated

**Comment by kevinansfield** [comment]
@Playrom thanks! [Post context docs](https://themes.ghost.org/docs/post-context#section-templates) have been updated 😄
