### ISSUE TITLE
Features page filter / label

### ISSUE THREAD

**Issue by tpiros** [TryGhost/Ghost#9234]
It'd be great if in the Ghost Admin panel we would have an option to filter for posts that are marked as 'featured' - and maybe have an indicator for featured posts as well in the list of stories (in the same way how 'pages' have a little label)

**Comment by kevinansfield** [comment]
Thanks @tpiros 👍 This was actually something I was looking at adding just yesterday 😄

**Comment by tpiros** [comment]
Sweet! Happy to help in any way @kevinansfield just ping me! :)
