### ISSUE TITLE
Mobile responsive issues in admin area

### ISSUE THREAD

**Issue by kevinansfield** [TryGhost/Ghost#9239]
"Epic" issue for collecting any bugs with the responsive CSS at mobile sizes (down to iPhone 6)

- [ ] password validation for "too short" message
<img width="376" alt="screen shot 2017-11-09 at 12 14 43" src="https://user-images.githubusercontent.com/415/32740167-f61c22ca-c899-11e7-8301-1cb52ef869dc.png">

- [ ] stories screen filters
<img width="376" alt="screen shot 2017-11-09 at 12 15 52" src="https://user-images.githubusercontent.com/415/32740169-f631c3d2-c899-11e7-9728-79e1f38cb8a5.png">

- [ ] scheduled post countdown message
<img width="376" alt="screen shot 2017-11-09 at 12 19 23" src="https://user-images.githubusercontent.com/415/32740170-f64e24be-c899-11e7-95db-47754289aa46.png">

**Comment by martgnz** [comment]
I would like to work on this issue! ✨

**Comment by kevinansfield** [comment]
@martgnz 👍 awesome 😄 If you have any questions or issues drop by the #contributing channel in [Slack](https://slack.ghost.org)

**Comment by PedramMarandi** [comment]
I'll give it a shot too, looks amazing for my first PR

**Comment by NayRomo** [comment]
Hi @kevinansfield  I would like to work in this issue please!

**Comment by CriticalRespawn** [comment]
Left this issue for a couple of weeks as I really didn't want to step on anyones toes, as it's been over 4 months since the last comment on here I've created a PR with what I hope are the fixes to all 3 issues here.

https://github.com/TryGhost/Ghost-Admin/pull/994

**Comment by kevinansfield** [comment]
@jawn the issues listed in here are all still open and free to work on. As stated in the comment you linked to, a separate PR per issue is preferred

**Comment by dmitrycy** [comment]
Hey, I'm new to contributing to OSS projects, but this looks like something I can handle technically. Is this issue still up for grabs?

**Comment by kevinansfield** [comment]
I'm going to close this issue for now. There needs to be design input for the mobile version of post filters and the editor header design has diverged since the scheduled post screenshot. If appropriate separate issues will be opened with the desired mobile designs.
