### ISSUE TITLE
[FEATURE REQUEST] Discord compatibility with Slack webhook or new Discord integration in Ghost

### ISSUE THREAD

**Issue by ScarletWolf275** [TryGhost/Ghost#9246]
### Issue Summary

This is a feature suggestion, and an issue. Right now, I don't use Slack, I use Discord. Discord's webhook implementation is the same as slack. For Gitlab, they don't have Discord but I can put my discord webhook followed by a /slack and it will work normally in Gitlab's slack service. I wish the same could happen here, I try to paste my discord web hook followed by /slack in Ghost and it is limiting how the URL is. It is restricting it to be https://hooks.slack.com. I need an easy way of using that option with Discord to notify my community about the new blog posts.

### Steps to Reproduce

1. Create a Discord webhook and copy its URL
2. Try to paste it in the Slack app in Ghost following the URL by a /slack

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

### Technical details:

* Ghost Version: 1.17.1
* Node Version: 8
* Browser/OS: Safari on macOS High Sierra
* Database: SQL

**Comment by kirrg001** [comment]
Hey @ScarletWolf275 👋

Thanks for your interest and suggestion. 

In general feature requests should be suggested and discussed in [slack](https://slack.ghost.org), however in this case your suggestion sounds like a simple enhancement of the existing slack url validation. cc @kevinansfield

**Comment by jloh** [comment]
This has been raised previously, see #7856

**Comment by kevinansfield** [comment]
@ScarletWolf275 there's a few missing pieces of information here.

1. Can you provide an example discord webhook URL?
2. It wasn't clear from your explanation, is the `/slack` postfix something unique to GitLab or is it something to do with Discord?

**Comment by ScarletWolf275** [comment]
Discord requires a postfix for every service. It can receive messages from slack. But that can be manipulated. For example I have `https://discordapp.com/api/webhooks/XXXXXXXXXXXX/YYYYYYYYYY` as the webhook. That just won't work alone... I need to add the service it is being used for so I add /slack at the end. So then I add `https://discordapp.com/api/webhooks/XXXXXXXXXXXX/YYYYYYYYYY/slack` to the slack team and it would work. What I'm trying to point out here is, Discord has support for Slack's embed format. Ghost has support for Slack's embed format. That's the one thing in common and you can use that in a way where you can put in the Discord webhook into Ghost followed by /slack and it would work just fine.

**Comment by kevinansfield** [comment]
@ScarletWolf275 in case you didn't see the 1.17.3 release has a fix for this, you are able to put any valid URL into the Slack app webhook field so it will work for Discord, Mattermost, and any others 👍

**Comment by ScarletWolf275** [comment]
Alright. Thanks!
