### ISSUE TITLE
Manually setting date

### ISSUE THREAD

**Issue by FeroVolar** [TryGhost/Ghost#9254]
Please return to the option to enter the date of the post, not just select from calendar.
It 's horrible set date back in time more than one year :/

I move my old sites to Ghost and set date at 10-15 year olds posts is Hell...
Thanks!

**Comment by kirrg001** [comment]
Sorry, but you have to be a *little bit* more specific. Where do you move your sites from and why do you have to fix your dates manually when [importing content into Ghost](https://docs.ghost.org/v1/docs/the-importer)?

**Comment by ltgreer** [comment]
Agreed. With Wordpress import broken since Ghost 2.0, the only way to move to Ghost is to manually import posts. To be required to click a zillion times in the calendar selector is super inconvenient.
