### ISSUE TITLE
Unable to manually type date in post setting menu

### ISSUE THREAD

**Issue by frantzypants** [TryGhost/Ghost#9256]
### Issue Summary

Before, one could manually enter a date into the date field on the post settings menu. Since Ghost 1.0, you are only able to select a date by using the calendar. This is tedious for entries that have dates in the past (e.g. 2005). 

### Steps to Reproduce

1. Create a new story
2. Open the post settings menu
3. Click on the date field, you are forced to use a calendar.

When clicking on the date field, one would expect to be able to manually enter in the date if needed, or select a date using the calendar. 

### Technical details:

* Ghost Version: 1.17.3

**Comment by kirrg001** [comment]
FYI: A similar report came into today, see https://github.com/TryGhost/Ghost/issues/9254. 

If you want to add and publish a single post in the past via the editor, then yes, you need to use the calendar and go back in time. 

I can definitely see a problem with the calendar picker, you *can only navigate through months and not years.* Either this can be improved (if the picker allows navigating through years directly) or the date field could accept a manual input.

In general, is it a common use case to add multiple posts and change the year to very old one? 

cc @kevinansfield.

**Comment by fehwalker** [comment]
I'm also experiencing this pain with Ghost 1.21.6 -- I have a Nikola blog, which doesn't have a migration tool that I've seen, and to complicate it's partly older posts imported from WordPress to Nikola ages ago (which used a weird two-file metadata/HTML format) and partly newer single file reStructuredText posts.

There are only a couple of hundred posts, so it didn't seem worth writing/debugging two scripts to munge the two post types into Ghost input format. And I'm also taking the opportunity to do some content curation.

But the posts go back to 2006. So in many cases I'm spending more time clicking on the left arrow on the calendar than copy/paste/reformatting/editing the content.

**Comment by FeroVolar** [comment]
This issue is also in version 2.x
Is somehow hack how to change it, for example over browser Inspect tool? Directly in DB?

I waiting with 2k posts (from years 2008-2012), clicking 100x for setting date is pain  :(

**Comment by kirrg001** [comment]
@FeroVolar Yeah you could use the DB. I'd suggest to ask in the [forum](https://forum.ghost.org) :)

**Comment by telefonosuci** [comment]
I would remove the readonly attributes from gh-date-time-picker input. In wich brench can I commit the change ?

**Comment by kscott5** [comment]
Hi @telefonosuci, 

advice. look at localization or cultural date format validation. 


jQuery localization.

**Comment by seanhamlin** [comment]
This is very much impacting my ability to migrate in around 50 or so posts from as far back as 2012. Why are we not just using the [default date HTML element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date)?

**Comment by ltgreer** [comment]
Agreed. With Wordpress import broken since Ghost 2.0, the only way to move to Ghost is to manually import posts. To be required to click a zillion times in the calendar selector is super inconvenient.
