### ISSUE TITLE
Heading auto-ID generation creates illegal duplicates

### ISSUE THREAD

**Issue by giles-v** [TryGhost/Ghost#9260]
### Issue Summary

When Ghost renders markdown to HTML in the page, it automatically creates `id` attributes for headings for easier linking – which it does by processing the heading content to a lowercase string. Thus:
```
### Issue Summary
```
becomes
```
<h3 id="issuesummary">Issue Summary</h3>
```

However, if you have more than one heading with the same text on the page, Ghost will generate the same ID, which is illegal HTML (IDs should be unique within the document). 

Thus:
```
### Issue Summary
### Issue Summary
```
becomes
```
<h3 id="issuesummary">Issue Summary</h3>
<h3 id="issuesummary">Issue Summary</h3>
```

The Ghost markdown renderer should maintain a list of generated IDs, and append an incremented number to the end of duplicates, so that the example above becomes something like:
```
<h3 id="issuesummary">Issue Summary</h3>
<h3 id="issuesummary-2">Issue Summary</h3>
```
This behavior is documented in the Gitlab markdown rendering documentation:
https://github.com/gitlabhq/gitlabhq/blob/master/doc/user/markdown.md#header-ids-and-links

### Compatibility Considerations

Cosmetic issue reports like [this one](https://github.com/TryGhost/Ghost/issues/8878) have been rejected due to maintenance of compatibility: the Ghost team quite correctly does not want existing hyperlinks to break. I agree with this. The above suggestion would also change _every_ header ID across the ecosystem. 

I think this case is a bit different. Such a change will only affect a minority of headings. It will resolve a more concrete issue (illegal HTML). Existing hyperlinks to headings are _already_ messed up; the browser could target the first or the second unpredictably. So I don't see any particular downside to doing this.

**Comment by ErisDS** [comment]
@kevinansfield is there any realistic way to solve this or should we close as wontfix?

**Comment by kevinansfield** [comment]
It's been complicated a bit further due to the move to the full mobiledoc editor 🤔 If a post only uses rich-text headings than its fixed because we have working deduplication of rich-text auto header ids. If a post mixes rich-text content with markdown or html then you can still end up with duplicate ids but it's now a bit trickier to deal with because the markdown parser is not aware of content outside of the markdown card.

Closing as wontfix. Workaround is to use the rich-text editor for headings.

**Comment by meleu** [comment]
@giles-v @ErisDS @kevinansfield 
I've posted a "feature request" in the forums that, if implemented, can probably solve this issue.
You can check it here:
https://forum.ghost.org/t/extended-markdown-card-in-the-editor/11146
