### ISSUE TITLE
Incorrect error message is used with scheduled posts when time format is wrong

### ISSUE THREAD

**Issue by frantzypants** [TryGhost/Ghost#9262]
### Issue Summary

When scheduling a post in the future using UTC-8h (with the incorrect time format, e.g. 3:30), the wrong error is returned: `Must be at least 2 mins in the future`. Expected error should be the `Must be in format "15:00`. 

![](https://puu.sh/ypTIb/d4b5c9ec88.png)

### Steps to Reproduce

Using UTC-8h, try to schedule a post with 3:30 (or whatever time). It shows the error that you can't schedule a post under 2 minutes, but it's under 2 minutes - the format is just wrong. As soon as you set 03:30, it works.

Expected result should be the proper error message for format when the time is entered incorrectly.

### Technical details:

* Ghost Version: 1.17.2
* Browser/OS: Any
* Database: mysql

**Comment by tagawa** [comment]
Instead of changing the error message, is it possible to accept 3:30 as a format please? I.e. if the number before the colon is a single digit, the software adds the zero in the background. This would make the software adapt to user behaviour rather than users having to adapt to the software's behaviour.

**Comment by JohnONolan** [comment]
> Instead of changing the error message, is it possible to accept 3:30 as a format please? I.e. if the number before the colon is a single digit, the software adds the zero in the background. This would make the software adapt to user behaviour rather than users having to adapt to the software's behaviour.

Agree 100% this makes much more sense

**Comment by tagawa** [comment]
Fix looks good - thank you!
