### ISSUE TITLE
Support for universal emojis

### ISSUE THREAD

**Issue by ScarletWolf275** [TryGhost/Ghost#9263]
### Issue Summary

The Slack app in Ghost used to send notifications to Slack is now possible to use to send to Discord and other services supporting slack webhooks. This is great! But, I noticed that when I sent a test notification to Discord, the emoji `:simple-smile:` was not shown. This is because Discord has it as `:smile:`. This can easily be fixed if you use the universal form of the emoji, in this case the notification could send `:)` and Discord would translate it to `:smile:` while Slack would do its thing and translate to `:simple-smile:`. Also any chance for supporting emojis in the stories?

### Steps to Reproduce

1. Add a Discord webhook (followed by the postfix /slack) into Ghost.
2. Send a test notification.
3. Notice that the emoji is not shown because the emoji name is wrong.

### Technical details:

* Ghost Version: v1.17.3
* Node Version: 8.9.0
* Browser/OS: Safari on macOS High Sierra
* Database: SQLite3

**Comment by ScarletWolf275** [comment]
Maybe? No one?

**Comment by AbijeetP** [comment]
@ScarletWolf275 - I'll take it up sometime next week.

**Comment by AileenCGN** [comment]
@AbijeetP It should be a fairly simple change just here:

https://github.com/TryGhost/Ghost/blob/master/core/server/services/slack.js#L101

**Comment by AbijeetP** [comment]
@AileenCGN  - Thanks! But that's only the test ping, isn't there a smiley somewhere in the post publish slack message itself?

Also testing would involve setting up a slack connection and checking whether the message appears properly as described here - https://help.ghost.org/hc/en-us/articles/115000449692-Slack. Correct?

**Comment by ScarletWolf275** [comment]
Yea. All you gotta do is change all the emojis to their universal from. Ex: change :simple-smile: to :)
That change will be best since the slack app now is no longer limited and can also be used for discord which is what I do. Also the ability of putting emojis into articles would be good

**Comment by AileenCGN** [comment]
> Also the ability of putting emojis into articles would be good

@ScarletWolf275 It is already possible to use emojis in articles. Would also be a separate issue, if it turns out to be an issue.
