### ISSUE TITLE
Primary Tags are not available in the Sitemap

### ISSUE THREAD

**Issue by guill3m** [TryGhost/Ghost#9272]
When changing the permalinks in the database to be `/:primary_tag/:slug/`, the sitemap will always show `all` instead of the slug for the primary tag of that post.

This seems to be a very similar issue to https://github.com/TryGhost/Ghost/issues/8494 but with tags instead of authors.

### Steps to reproduce

1. Set the permalinks in the database to include the Primary Tag, example: `/:primary_tag/:slug/`
2. Create a post with a primary tag that is not internal.
3. Go to the posts sitemap

All posts are shown with the url as `/all/:slug`.

### Live example

https://guillemandreu.com/sitemap-posts.xml

![screen shot 2017-11-26 at 11 23 45](https://user-images.githubusercontent.com/1526816/33239168-7df5ce10-d29c-11e7-934e-f71d6cb41ec8.png)

All the posts should have the url as `/work/:slug` (I'm using the same primary tag for all of them at the moment).

### Technical details:

* Ghost Version: 1.18.0
* Node Version: 6.11.2 / 8.9.1
* OS: macOS 10.13.1 / Ubuntu 16.04.3
* Database: Sqlite / MySQL

### Pull Request for the fix

* #9273 for master
* #9274  for LTS

**Comment by ErisDS** [comment]
Quick note that the new code for sitemaps added for #9192 in PR #9247 has this fix, so this shouldn't regress when we switch over.
