### ISSUE TITLE
Sign-in on ghost.org broken

### ISSUE THREAD

**Issue by thekyriarchy** [TryGhost/Ghost#9286]
### Issue Summary

Using Firefox, Epiphany, and Chrome on Fedora 27 ghost.org/signin says to enter an email address, even when an email address is entered, making it impossible to sign in.

**Comment by acburdine** [comment]
Not sure how you got to that url, but the url to sign in to the administration panel _should_ be https://auth.ghost.org/signin/

If you go to https://my.ghost.org (the ghost(pro) administration panel) you should be redirected to the correct signin page.

Going to close this issue as it's not related to Ghost itself - questions about Ghost(Pro) should be instead emailed to support@ghost.org 😄

**Comment by thekyriarchy** [comment]
1. Why does the page exist if it shouldn't be used? 
2. This page points there: https://ghost.org/pricing/

**Comment by acburdine** [comment]
Not sure why the page exists, and that's a good catch; however, the point still stands that this isn't the proper place for a bug report on ghost(pro).

I'll forward this on to the ghost(pro) team.

**Comment by AileenCGN** [comment]
Hey @thekyriarchy 👋 

Even tho, this is the wrong repository, it is indeed a bug, that you found! Thank you very much for reporting it. I'll push out a fix in a minute!

Cheers,
Aileen
