### ISSUE TITLE
Incorrect Japanese IME popup position

### ISSUE THREAD

**Issue by kosukem** [TryGhost/Ghost#9289]
When I input Japanese text in the editor, the candidates display appear on the inputting text, so I cannot see the inputting text.
The below animation shows this behavior.

![weird-ime-behavior](https://user-images.githubusercontent.com/18656476/33374939-876e8ca0-d54b-11e7-8d5a-fd302d3c46e2.gif)

The candidates display should appear under the inputting text.

In this case, IME is Google Japanese IME, and browser is Chrome on Windows 10. Each software version is latest. I tried Microsoft IME with Chrome, Google IME with Edge, and I get the same trouble.
Other websites's editor (CodeMirror demo, etc) is OK, no trouble like this.

On these days, I upgraded the Ghost 1.18.0 and this trouble is happened.

**Comment by kevinansfield** [comment]
Hey @kosukem 👋 Sorry you're having issues. We're aware of the IME difficulties but this is a problem with the upstream CodeMirror library so any issues should be opened/tracked there instead.

A list of open issues can be found here https://github.com/codemirror/CodeMirror/search?q=ime&type=Issues&utf8=%E2%9C%93

Closing this because it's an upstream issue and should be tracked in the relevant project.

**Comment by kevinansfield** [comment]
Sorry, I missed this part:

> Other websites's editor (CodeMirror demo, etc) is OK

I'll re-open but the core team are not likely to look at this because we don't have any IME tools or any experience using them. It sounds like a CSS issue so if you have any CSS experience or know someone who might be able to help PRs are always welcome 😄

**Comment by kosukem** [comment]
But, individual working on CodeMirror has no problem. How... oh, you re-open.

**Comment by tamurashingo** [comment]
I think this problem cause of `textarea` css.


```html
<div class="gh-markdown-editor-pane">
  <textarea placeholder="Post Title"></textarea>
  <textarea placeholder="Begin writing your story..."></textarea>
  <div class="CodeMirror">
    <div style=".....">
      <textarea></textarea> <!-- IME suggestion is shown here -->
```

The `textarea` has style `height: 1em`,  but defines `min-height: 10rem` in forms.css, so it has 100px height.

<img width="739" alt="2017-12-18 17 55 30" src="https://user-images.githubusercontent.com/1601198/34098036-70c695d8-e41e-11e7-8ac3-97683cf998b7.png">

It seems that IME Suggestion is shown on top of textarea.

<img width="516" alt="2017-12-18 17 55 56" src="https://user-images.githubusercontent.com/1601198/34098096-9f24a208-e41e-11e7-859e-9ca2b51e082e.png">


so, removed `min-height: 10rem` in forms.css.

<img width="366" alt="2017-12-18 18 24 11" src="https://user-images.githubusercontent.com/1601198/34098736-b8151eda-e420-11e7-9ab3-8fdab7906f11.png">

IME Suggestion.

<img width="405" alt="2017-12-18 18 22 46" src="https://user-images.githubusercontent.com/1601198/34098759-c7b384c6-e420-11e7-85aa-8458f171b8f4.png">

**Comment by tamurashingo** [comment]
original CodeMirror's height is 1em;

<img width="316" alt="2017-12-19 14 23 19" src="https://user-images.githubusercontent.com/1601198/34142065-777a383a-e4c8-11e7-93a4-eb17536ec8a7.png">

![2017-12-19 14 24 42](https://user-images.githubusercontent.com/1601198/34142075-825ce2fc-e4c8-11e7-9a08-ef02af5eea7a.png)

suggestion position is OK.

<img width="304" alt="2017-12-19 14 26 00" src="https://user-images.githubusercontent.com/1601198/34142090-9c106624-e4c8-11e7-9ba2-83e4cd565e5c.png">

**Comment by kosukem** [comment]
To disable `min-height: 10rem` makes the popup position correct on my Chrome / Windows 10.
Cool !!

**Comment by tamurashingo** [comment]
I fixed the hidden textarea position.

- remove `bottom: -1em` (on my Chrome, `-1em`  doesn't work well)
- add `top: 0`
- add `min-height` and `height`, to the CodeMirror's default text height.
- add `margin-bottom` to negative margin.


## Chrome on mac
**popup position**
<img width="433" alt="fix-chrome" src="https://user-images.githubusercontent.com/1601198/34553235-bd1857e8-f169-11e7-8c5d-f4accea77b13.png">

**hidden textarea**
<img width="433" alt="hiddentextarea-chrome" src="https://user-images.githubusercontent.com/1601198/34553249-cd10aeca-f169-11e7-9c62-4eb8aa8420ef.png">

## Firefox on mac
**popup position**
<img width="388" alt="fix-firefox" src="https://user-images.githubusercontent.com/1601198/34553293-f70adade-f169-11e7-813b-5e7a2176e903.png">

**hidden textarea**
<img width="400" alt="hiddentextarea-firefox" src="https://user-images.githubusercontent.com/1601198/34553313-180ebd86-f16a-11e7-8f41-1f52e21e33a9.png">
