### ISSUE TITLE
next/prev post display missing when post slug contains `null` first

### ISSUE THREAD

**Issue by frantzypants** [TryGhost/Ghost#9290]
### Issue Summary

Next/prev posts fail to render when the post slug's first word is `null`. For example, `yourdomain.com/null-island`. There were no console errors to report with this. It looks as though everything except the next/prev post is functioning as expected.

### Steps to Reproduce

1. Create a new post
2. Set post slug to include the first word as `null`, e.g. `null-island`.
3. Publish the post
4. View the post; next/prev posts are missing 

![](https://puu.sh/yvSSU/9e35cccf95.png)

What one might expect to see is a preview of the next and previous post, e.g.

![](https://puu.sh/yvT2e/13733ae188.png)

The next/prev posts display if the post slug is changed so that `null` is not the first word used.

### Technical details:

* Ghost Version: 1.17.2 / 1.17.3
* Browser/OS: Tested in Chrome, Safari / MacOS El Capitan
* Database: mysql

**Comment by kirrg001** [comment]
That is a bug in [GQL](https://github.com/TryGhost/GQL). I think this is related to https://github.com/TryGhost/GQL/issues/3.

> slug:-null-islands+published_a
----------^
Expecting 'OR', 'AND', 'RPAREN', 'RBRACKET', got 'NOT'
node_modules/ghost-gql/dist/parser.js:320

**Comment by ErisDS** [comment]
Will take a look at this as part of the GQL re-work.

**Comment by kirrg001** [comment]
This is still an issue in [NQL](https://github.com/NexesJS/NQL).

If #10105 get's merged & released, we will ensure that the outstanding bugs are tracked on the NQL repository.

**Comment by kirrg001** [comment]
> If #10105 get's merged & released, we will ensure that the outstanding bugs are tracked on the NQL repository.

It's already tracked, [see](https://github.com/NexesJS/NQL-Lang/issues/1).

**Comment by ErisDS** [comment]
Closing as it is tracked here: https://github.com/NexesJS/NQL-Lang/issues/1
