### ISSUE TITLE
Unable to upload image in general settings

### ISSUE THREAD

**Issue by rymccue** [TryGhost/Ghost#9292]
I am running ghost 1.18.1 and just booted up a server with Digital Ocean Ghost one-click image. After following the defaults and getting the blog up and running I created a blog post with an image and published it. I next went to my general settings to add a publication cover and the Upload Image button was unresponsive. I checked the console and there are no errors and I have not seen any similar errors after searching around on Google.

Not really sure where to go from here, I tried deleting the droplet and installing a new one with the same results.

**Comment by abaustin1** [comment]
I just came here to report the exact same issue. Clicked any of the three upload buttons... no response whatsoever. I am running 1.18.1 on Google Cloud Platform. Brand new install.

![Affected Buttons](https://goo.gl/VmCrUp)

**Comment by kevinansfield** [comment]
@rymccue, @abaustin1 which browser + browser version are you using?

**Comment by ankh2054** [comment]
sorry daft question, how do we get the fix, since I can't see the files mentioned to apply fix?

app/controllers/settings/general.js
app/controllers/settings/lab.js

**Comment by AileenCGN** [comment]
@ankh2054 the fix will be in the release later today ;)

**Comment by abaustin1** [comment]
Not sure if you still need this info since the question is closed, but I initially tried with Firefox 57. Was able to replicate the issue on the latest versions of Chrome, Edge, Chrome Android, and the Ghost Desktop Client.

**Comment by phyrexian** [comment]
Re: #9300 #9295 

This bug APPEARS to still be present in the admin editor; the "Upload Image(s) button does not function. 

Tried a fresh SQLITE install of 1.18.2;  posted details + a gif in #9295 and for sure is still happening.  (looks like the button asks for the filepicker;  but after selecting a file never makes the request to the server)

**Comment by kevinansfield** [comment]
@phyrexian that is a different issue to this one, it's being tracked in #9300
