### ISSUE TITLE
Keyboard shortcut "Ctrl/⌘ + Alt + P" publishes post and also toggles side-by-side preview

### ISSUE THREAD

**Issue by smoolman** [TryGhost/Ghost#9296]
### Summary of issue
While editing a post (or draft) and using the "Ctrl/⌘ + Alt + P" shortcut keystroke to preview the post, the post is published due to the same global keystroke for publishing a post.

### Steps to Reproduce
1. Edit an existing post/draft (within ghost-admin).
2. Toggle the split screen view using the "Ctrl/⌘ + Alt + P" keystroke.

### Observed results
- The post being edited is published and the split screen mode is toggled.

### Expected results
- The post should not be published (since the post is being edited) and should only toggle the split screen mode (as noted by the icon's hover text/behavior when clicked)
![image](https://user-images.githubusercontent.com/34152623/33471863-48aef73c-d63d-11e7-8b16-2f63b43ba56f.png)

- The shortcut is also listed here and does not mention anything regarding publishing - https://help.ghost.org/hc/en-us/articles/225095208-Ghost-Shortcuts#ghost-editor-shortcuts):
> Ctrl + Alt + P - Toggle side-by-side preview mode

### Technical details
* Ghost Version: 1.18.2
* Client OS: Windows 10
* Browser: Chrome 62.0.3202.94 / Firefox 57.0.1

**Comment by AileenCGN** [comment]
I am not able to reproduce this, but also can't test it with a Windows machine...

**Comment by smoolman** [comment]
I just tried it on a Mac and am also not able to reproduce the issue since Ctrl+Alt+P correctly toggles the side-by-side view (without publishing) and ⌘+Alt+P publishes the post.  So it appears to be an issue specific to Windows key bindings.

**Comment by StevieJayCee** [comment]
It's an issue with any platform that isn't OSX due to the CmdOrCtrl util module. I've suggested a quick fix below, but ultimately, it may be that the behaviour needs modified to check if it's the super key of any platform being pressed.

This combo is possible in ubuntu, would need to test win10 tomorrow.

https://github.com/TryGhost/Ghost-Admin/pull/924
