### ISSUE TITLE
İmage upload button not working any more

### ISSUE THREAD

**Issue by MertcanGokgoz** [TryGhost/Ghost#9300]
### Issue Summary

not upload while trying to upload images

### Steps to Reproduce

1- Login Ghost admin area
2- Select any draft stories
3- continue writing and try image upload
4- see that the image is not loaded ant not uploaded

### Technical details:

* Ghost Version: 1.18.2
* Node Version: 6.12.0
* Browser/OS: Safari, Chrome and Firefox Latest Release
* Database: MySQL

**Comment by kevinansfield** [comment]
Sorry about this, bug is confirmed and there's a fix is ready for the next release. In the meantime a workaround is to drag and drop images onto the editor to upload them as that method still works.
