### ISSUE TITLE
Random Ghost-Admin test failures

### ISSUE THREAD

**Issue by kevinansfield** [TryGhost/Ghost#9301]
Ghost-Admin tests on Travis have started failing very often and it's becoming increasingly frustrating trying to get the build to pass due to failures unrelated to the build's changes. This issue is for collecting a list of the tests that randomly fail so that we can dig into why they fail and find ways to increase their reliability.

- [ ]
    ```
    not ok 1593 Firefox 57.0 - Integration: Component: gh-psm-tags-input exposes all tags as options
    ---
        message: >
            expected 0 to equal 4
    ```

**Comment by kirrg001** [comment]
@kevinansfield Can't we re-use https://github.com/TryGhost/Ghost/issues/8805?

**Comment by kevinansfield** [comment]
👍 I didn’t realise that one was still there!

**Comment by kirrg001** [comment]
Closing, [see](https://github.com/TryGhost/Ghost/issues/8805#issuecomment-349327848).
