### ISSUE TITLE
NaNundefined in lists

### ISSUE THREAD

**Issue by PaszaVonPomiot** [TryGhost/Ghost#9302]
### Issue Summary

When I press enter to add another item to the list I get `NaNundefined` error in the editor. 

### Steps to Reproduce

1. Move cursor to the end of line on one of the item from list
2. press enter

### Technical details:

* Ghost Version: 1.18.2
* Node Version: v6.11.0
* Browser/OS: Chrome/W10
* Database: MariaDB

### Screencast
![list](https://user-images.githubusercontent.com/5560454/33532311-e028718a-d898-11e7-8b44-26bf7df42a87.gif)

**Comment by AileenCGN** [comment]
I can confirm this bug.
