### ISSUE TITLE
Feature: Contributor Role

### ISSUE THREAD

**Issue by acburdine** [TryGhost/Ghost#9314]
One of the popular questions / feature requests in Ghost is for adding a restriction that prevents certain users from publishing posts. Due to some recent improvements in Ghost's permissions layer, this is now a possibility!

In the interests of backwards compatibility, we will _not_ be updating the Author role to restrict publishing ability. Instead, there will a new "Contributor" role added that is functionally equivalent to the Author role, with two notable exceptions:

- Contributors _may not_ publish (or schedule) posts
- Contributors _may not_ edit or delete published posts
- Contributors _may not_ create, edit, or delete tags

This leads to two significant Ghost-Admin UI differences

- Tag input field will not appear in the Post Settings Menu
- Publish button and Menu will be replaced with a "Save" button

Eventually, we want to be able to allow contributors to add existing tags to a new post, however in the interest of simplicity the initial version of the contributors role will prevent modifying the tags of a post altogether.

**Comment by jloh** [comment]
> Tag input field will not appear in the Post Settings Menu

Can it not just appear read-only / greyed out? I imagine the contributor will still want to see the tags that are applied to a post. Especially for internal tags which aren't necessarily exposed on the front end.

**Comment by ErisDS** [comment]
This issue contains an agreed specification for the feature that will be implemented by @acburdine.  

@jloh your suggestion makes sense, but this is the kind of fine tuning that can come after the feature lands & is being used in anger :) This is a first iteration aimed at getting the main piece of work done.

**Comment by paulmaunders** [comment]
Can the contributors edit other people's posts? I think it would make sense to only let them edit their own posts. We are using Ghost for our magazine [happiful.com](happiful.com) and we would really like to be able to have lots of contributors sign up, but we don't want them editing each others posts.

**Comment by kevinansfield** [comment]
@paulmaunders the Contributor is a more restricted Author role, Authors are already unable to view (in the admin) or edit any posts other than their own.

**Comment by paulmaunders** [comment]
That's fantastic, do you know when this will be available for Ghost(Pro) hosted customers?

**Comment by kevinansfield** [comment]
As with everything, when it's ready 😉

You can follow this issue if you want and you'll be notified when it's closed. From that point it will be available in the next public release (most Tuesdays + Thursdays) then available on Ghost(pro) shortly after (rollouts on pro are run once a week).

**Comment by chrisalley** [comment]
Will contributors be able to edit or delete their own posts after their posts are published? If so, this seems open to abuse if the contributor is not trusted.

**Comment by ErisDS** [comment]
> Will contributors be able to edit or delete their own posts after their posts are published? If so, this seems open to abuse if the contributor is not trusted.

No, contributors will not be able to edit or delete any published posts. I have updated the issue to reflect this.

**Comment by paulmaunders** [comment]
Is this issue being worked on currently? 

We've upgraded to Ghost Pro v1.0 now so looking forward to seeing this go live!

**Comment by kirrg001** [comment]
@paulmaunders We are currently working on it 👍  Thanks for your interest.
