### ISSUE TITLE
error while updating: migration is pending

### ISSUE THREAD

**Issue by luizkowalski** [TryGhost/Ghost#9324]
I updated to Ghost 1.18.4 and during update, it failed due to migrations...I got an error like `task.execution is not a function`. Now it seems like the update didn't worked properly, seems like it leave the ghost in a invalid state although it says I'm running 1.18.4.

```

[2017-12-12 12:34:31] ERROR

NAME: DatabaseIsNotOkError
CODE: DB_NEEDS_MIGRATION
MESSAGE: Migrations are missing. Please run knex-migrator migrate.

level:normal

If knex-migrator is not installed, please run "npm install -g knex-migrator"
Read more here: https://github.com/TryGhost/knex-migrator
DatabaseIsNotOkError: Migrations are missing. Please run knex-migrator migrate.
    at DatabaseIsNotOkError.KnexMigrateError (/var/www/ghost/versions/1.18.4/node_modules/knex-migrator/lib/errors.js:9:26)
    at new DatabaseIsNotOkError (/var/www/ghost/versions/1.18.4/node_modules/knex-migrator/lib/errors.js:21:26)
    at /var/www/ghost/versions/1.18.4/node_modules/knex-migrator/lib/index.js:1067:27
```

what could be causing this?

**Comment by kirrg001** [comment]
Hi @luizkowalski 

We're sorry to hear you're having problems, but before you raise an issue, please check if [our troubleshooting guide](https://docs.ghost.org/docs/troubleshooting#section-task-execute-is-not-a-function) offers any help for your problem. Thanks!

You can always use our [slack](https://slack.ghost.org/) community - https://slack.ghost.org, if you're not able to find the answer in our [documentation](https://docs.ghost.org/) - https://docs.ghost.org.
