### ISSUE TITLE
hope Ghost-Admin more easily to start, i can even to run it in local

### ISSUE THREAD

**Issue by henryatman** [TryGhost/Ghost#9330]
hope Ghost-Admin more easily to start, i can even to run it in local,

it's toooo not friendly, for example, config file Bower.json in project, it's too lazy not set default right directory, i run ```bower install``` always tell me sucess or nothing, but cli check alway tell me lack some file,

even i run bower install, yarn, more more operate, but finally it still not work, in my local, 

now, i can even play ```Working with Ghost``` some like 'static' page in my local,

even i want to use total, 

thought zip or git to run it's so hard, i think this is why it can not popular like wordpress in china,

china is huge market, 14 billion people and lots of money, give up is so regrettable,

hope Ghost more easy to start like wordpress, 

** high learn curve is not good thing for any product.**

```
ps:
i know have a ghost-cli version, but it's like blackbox and untotal version, 

we don't like use them, we like to use pull git or download zip to run them,

i think it can be popular in china if still hard to start,

hope your improve it :), just like wordpress style.
```

**Comment by kevinansfield** [comment]
Hey ___ 👋 Please do not use GitHub for support, our [support guide](https://github.com/TryGhost/Ghost/blob/master/.github/SUPPORT.md) was linked in the GitHub notification above the issue creation form and has details about what issues you should raise here and which issues should be handled elsewhere. (Many projects have their own support guidelines and GitHub highlights them for you, please read them before opening issues 😄)

Ghost-Admin is not runnable by itself, it's part of the overall application. If you want to get Ghost installed there's a [getting started guide](https://docs.ghost.org/docs/getting-started-guide), if you want to hack on the core then there's a [contributing guide](https://docs.ghost.org/docs/contributing).

You can use [slack](https://slack.ghost.org) to get community support if you're not able to find the answer in the [docs](https://docs.ghost.org).
