### ISSUE TITLE
Why two Ghost-sites share same data ?

### ISSUE THREAD

**Issue by Messiahhh** [TryGhost/Ghost#9331]
### Issue Summary

I've two Ghost-sites in my ubuntu16.04, i hope they are Separated so i setup two different databases for them when i use 'ghost install'
However, i found they are sharing a same data.Especially when i create the second admin panel account, the first account was locked!

How can i own two different and separated sites?
Thanks!

### Technical details:

* Ghost Version: v1.19.0
* Node Version: v8.9.3
* Browser/OS: chrome
* Database: MYSQL

**Comment by kevinansfield** [comment]
Hey @Messiahhh 👋 Please do not use GitHub for support, our [support guide](https://github.com/TryGhost/Ghost/blob/master/.github/SUPPORT.md) was linked in the GitHub notification above the issue creation form and has details about what issues you should raise here and which issues should be handled elsewhere. (Many projects have their own support guidelines and GitHub highlights them for you, please read them before opening issues 😄)

You can use [slack](https://slack.ghost.org) to get community support if you're not able to find the answer in the [docs](https://docs.ghost.org).
