### ISSUE TITLE
Double Opt-In for subscribers

### ISSUE THREAD

**Issue by larsauswsw** [TryGhost/Ghost#9345]
Is it possible to add a double opt-in option for subscribers?
I have a self-hosted ghost blog with german content and not much traffic (one visitor per day). In the subscribers list are over 400 subscribers (no visitors on December 16th but 6 new subscribers on this day). Also the majority of the email addresses don't look legit and are from poland, UK, france, japan, ...

For now i will disable the subscribe-option.

**Comment by NistorCristian** [comment]
Exactly the same thing for me too. 400 subscribers. All of them fake. Usually 5-6 subscribers/day.

**Comment by AileenCGN** [comment]
Hi @larsauswsw 

The subscribers feature is something we're still working on and will be improved soon.

We only keep Github issues open for bugs and in-progress feature work, but always happy to chat about future ideas over on our  [slack](https://slack.ghost.org/) community - https://slack.ghost.org.

**Comment by kirrg001** [comment]
See also https://github.com/TryGhost/Ghost/issues/9351#issuecomment-353171120.
