### ISSUE TITLE
Migrating from 0.11.11 to 1.19.4 import problem

### ISSUE THREAD

**Issue by yaroslavgribov** [TryGhost/Ghost#9348]
### Issue Summary
Hi guys, I'm trying to migrate to ghost@1.19.0 but whenever I try to import json data from the previous version(~35mb of data) I run into
`
Failed to load resource: net::ERR_EMPTY_RESPONSE
 Error: Server was unreachable`
on the frontend and `FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory` from `ghost run` output after 2.2 min of stall time according to Network tab in Chrome
tried both win10 and High Sierra, node@6, 8, 9, ghost@1.19.0, 1.18.4, 1.17.2
Although I can export/import inside of 0.11.11 perfectly fine within ~20sec according to Network tab

Upd: so I ran it with --max-old-space-size=8192 and it took it ~30min to fail.

### Steps to Reproduce

1. ghost install
2. import content from previous version

I could try to attach JSON I'm trying to import if it's needed.

### Technical details:

* Ghost Version: 1.19.0, 1.18.4, 1.17.2
* Node Version: 6.12.2, 8.9.3, 9.3.0_1
* Browser/OS: High Sierra, Win10
* Database: mysql, sqlite

**Comment by yaroslavgribov** [comment]
For anyone who comes across a similar issue - solution was introduced by @vikaspotluri123 

> instead of running `ghost...` run `node --max_old_space_size=4096 --optimize_for_size --max_executable_size=4096 --stack_size=4096 current/index.js`

**Comment by cobbspur** [comment]
Re-opening this as large imports are failing where they previously passed, the above solution of increasing the Blog's stack capacity shouldn't really be necessary.

Part of the the stack trace includes:
```
Security context: 0x68ccfacf781 <JS Object>
    1: /* anonymous */(aka /* anonymous */) [/Users/cobbspur/GHOST/Ghost/node_modules/bookshelf-relations/lib/relations.js:202] [pc=0x2bcd866cfff5] (this=0x68ccfa04381 <undefined>,_existingTargets=0x3c1f50048dc9 <JS Object>)
    2: tryCatcher(aka tryCatcher) [/Users/cobbspur/GHOST/Ghost/node_modules/bluebird/js/release/util.js:16] [pc=0x2bcd86822805] (this=0x68ccfa04381 <undefined>)
    3: argum...
```

It looks as though bookshelf-relations is playing a part here and this was added in v1.17.3 if that is of help
