### ISSUE TITLE
Keep post-slug in native language when It's not latin character

### ISSUE THREAD

**Issue by baram204** [TryGhost/Ghost#9349]
### Issue Summary

I tried set slug in my mother language. but, It translate it english.

It's sad. 

1. It takes my language.
2. SEO disadvantage.

I want to use my mother language on post-slug (and tags URL).

Please, Let me know how can i stop force translate slug features.

### Steps to Reproduce

1. just type non-latin character inside post-slug or tag URL field.
2. It's converted latin character, especially english.

That's not a bug. Just Users needs.

### Technical details:

* Ghost Version: 1.19.0
* Node Version: 6.12.2
* Browser/OS: Any(chrom, opera, etc ..)
* Database: sqlite3

**Comment by AileenCGN** [comment]
Hi @baram204 

Thanks for the idea!

We only keep Github issues open for bugs and in-progress feature work, but always happy to chat about future ideas over on our  [slack](https://slack.ghost.org/) community - https://slack.ghost.org.
