### ISSUE TITLE
Facebook and Twitter in Structured data markup

### ISSUE THREAD

**Issue by NistorCristian** [TryGhost/Ghost#9350]
Ghost adds an Organization application/ld+json in the head.
It would be nice to add the Social profile structured data markup to this if it is set in General -> Social accounts.

https://developers.google.com/search/docs/data-types/social-profile

* Ghost Version: 1.19.0

**Comment by AileenCGN** [comment]
Hi @NistorCristian 

Thanks for the idea!

We only keep Github issues open for bugs and in-progress feature work, but always happy to chat about future ideas over on our  [slack](https://slack.ghost.org/) community - https://slack.ghost.org.
