### ISSUE TITLE
Feature Request: subscription integration with other websites

### ISSUE THREAD

**Issue by makeitcount** [TryGhost/Ghost#9351]
I'm not sure about development on subscription feature and was looking for this functionality and it seems like it's not there yet.

> There should be a way to integrate subscription form with other websites (either through an inline html/javascript code or through API integration)

Is there any roadmap planned on this feature?

**Comment by kevinansfield** [comment]
Hi @makeitcount! Subscriber integration with Zapier (and therefore almost every mailing list service) is [currently in beta](https://zapier.com/apps/ghost), it works with Ghost 1.19.0 or higher.

Further development of subscribers will arrive as part of our work on subscriptions and memberships next year.
