### ISSUE TITLE
Duplicate initial of parentApp with root directory's index

### ISSUE THREAD

**Issue by jeesyn** [TryGhost/Ghost#9353]
https://github.com/TryGhost/Ghost/blob/4cca2353e0c36c10c385deb624729bd6ab624811/core/server/index.js#L74

The parentApp intial here is useless if ghosts start from CLI ```node start``` etc, the parentApp is replaced by ghostServer.start()method, thus the initial code for Auth middleware followed has no effect.
I guess @kirrg001 has done some reactor and forgot to synchronize the update into node startup entrance.

**Comment by kirrg001** [comment]
Hey @jeesyn!

Thanks for your interest. 

https://github.com/TryGhost/Ghost/blob/7a98c99cba7e7f86cd314b33913c36f21d859ba1/index.js#L22

The core express app get's mounted into the outer express app (**ghostServer.rootApp**).

This is definitely working, doesn't matter if you are using the CLI or you are doing local development. 

Please swing by our [slack channel](https://slack.ghost.org) for further discussions. Thanks!
