### ISSUE TITLE
[Feature Request] Option to have navigation links open in a new window

### ISSUE THREAD

**Issue by ivoilic** [TryGhost/Ghost#9354]
I have a couple external links in my blogs navigation. It would be great if there was a checkbox on the admin side that would add target="_blank" to those <a>.

**Comment by AileenCGN** [comment]
Hi @ivoilic 

Thanks for the idea!

We only keep Github issues open for bugs and in-progress feature work, but always happy to chat about future ideas over on our  [slack](https://slack.ghost.org/) community - https://slack.ghost.org.
