### ISSUE TITLE
Can't make multiword tag

### ISSUE THREAD

**Issue by novaugust** [TryGhost/Ghost#9357]
### Issue Summary

Hitting space automatically creates the tag, making it impossible to have multi-word tags.

### Steps to Reproduce

1. Enter a word in the tag editor
2. Hit space to add another word...

### Technical details:

* Ghost Version: 1.19.0
* Node Version: (ghost pro)
* Browser/OS: chrome 63.0.3239.108
* Database: (ghost pro)

**Comment by AileenCGN** [comment]
I can confirm this bug. Seems to be related to the changes in https://github.com/TryGhost/Ghost-Admin/pull/892
