### ISSUE TITLE
Allow to export images

### ISSUE THREAD

**Issue by Kaligule** [TryGhost/Ghost#9361]
To this point it is not possible for a user to export images from Ghost (pro or not pro).

This was anoying until now, but with the upcomming [General Data Protection Regulation (article 20)](https://en.wikipedia.org/wiki/General_Data_Protection_Regulation#Data_portability) (which ) this might become a legal problem (especially for ghost pro).

**Comment by ErisDS** [comment]
The complexity of creating a mechanism to transfer such large amounts of data is left, correctly IMO, to the operating system. This is not a task for a piece of publishing software.

In the case of self-hosters that is done however you like. For Pro users, you contact support and a suitable mechanism is arranged depending on the size of that data.

**Comment by Kaligule** [comment]
What is complex about giving the user a list of links to download the images?
