### ISSUE TITLE
XSS Vulnerable and how to resolve?

### ISSUE THREAD

**Issue by squadramunter** [TryGhost/Ghost#9362]
Hi I tested my website on XSS vulnerables and these are the results.

My question now for this:

Is it safe? and can this be resolved?

I scan my site using nikto a vulnerable security scanner.

And is the output not false positive?

_______________________________________________________________________________________________________________

+ Uncommon header 'x-content-type-options' found, with contents: nosniff
+ OSVDB-27071: /phpimageview.php?pic=javascript:alert(8754): PHP Image View 1.0 is vulnerable to Cross Site Scripting (XSS).  http://www.cert.org/advisories/CA-2000-02.html.
+ OSVDB-4598: /members.asp?SF=%22;}alert(223344);function%20x(){v%20=%22: Web Wiz Forums ver. 7.01 and below is vulnerable to Cross Site Scripting (XSS). http://www.cert.org/advisories/CA-2000-02.html.
+ OSVDB-2946: /forum_members.asp?find=%22;}alert(9823);function%20x(){v%20=%22: Web Wiz Forums ver. 7.01 and below is vulnerable to Cross Site Scripting (XSS). http://www.cert.org/advisories/CA-2000-02.html.
+ 6544 items checked: 0 error(s) and 5 item(s) reported on remote host
+ End Time:           2017-12-31 01:11:07 (GMT1) (34 seconds)
---------------------------------------------------------------------------
+ 1 host(s) tested

**Comment by yiip87** [comment]
As you can see in the URIs (/phpimageview.php, /members.asp, /forum_members.asp), this has noting to do with Ghost, but with some other application (Forum?) on your server.
Also, you should really read [SECURITY.md](https://github.com/TryGhost/Ghost/blob/master/SECURITY.md) to learn how to responsibly disclose possible security issues.
