### ISSUE TITLE
Date helpler timezone bug

### ISSUE THREAD

**Issue by zce** [TryGhost/Ghost#9381]
### Issue Summary

The time zone is not set when the `date` helper is on the specified date not default.

### Steps to Reproduce

1. Update `post.hbs` file in `casper` theme:

```hbs
{{!-- line 22 --}}
 <time class="post-full-meta-date" datetime="{{date published_at format="YYYY-MM-DD HH:mm"}}">{{date format="YYYY-MM-DD HH:mm"}}</time>
```

2. Set the time zone to any non UTC:

![image](https://user-images.githubusercontent.com/6166576/34708550-438d9684-f54e-11e7-80ff-2412e39dd549.png)

3. Open any post page to compare the display of two times

  - `{{date published_at format="YYYY-MM-DD HH:mm"}}` timezone setting not working

I have found is the [date helper](https://github.com/TryGhost/Ghost/blob/master/core/server/helpers/date.js#L16) logical error, I will try to fix it.

### Technical details:

* Ghost Version: 1.19.2

**Comment by AileenCGN** [comment]
I can confirm this bug. As soon as the date helper is called with 'published_at', the timezone gets ignored. There was indeed a logical issue, which will get fixed with the supplied PR.
