### ISSUE TITLE
Show non-breaking spaces in the editor

### ISSUE THREAD

**Issue by toblerone1963** [TryGhost/Ghost#9384]
Hi,

In french, non-breaking spaces are mandatory. I notice that CodeMirror (if I'm not mistaken, Ghost use it, no?)  propose [to highlight those](https://github.com/codemirror/CodeMirror/commit/f0610e60c3b220814d80c133326adebc7339a35f). It should be easy to include this option [here](https://github.com/TryGhost/Ghost-Admin/blob/master/app/components/gh-cm-editor.js). I'm not in a situation where I can try to test that, sorry (and I think it's far from my actual capacity). 

Thanks!

**Comment by kevinansfield** [comment]
Hi @toblerone1963 👋 We are already highlighting special chars but the non-breaking-space is not part of CodeMirror's default list of special chars.

I'll add it to the list, thanks for bringing it to our attention! 😄
