### ISSUE TITLE
Dashboard doesn't load

### ISSUE THREAD

**Issue by luizkowalski** [TryGhost/Ghost#9387]
Since a couple weeks I noticed that I can't load my dashboard (`/ghost`). I tried update today to the latest version, but all I got is the loading animation and two errors:

```
Uncaught SyntaxError: Unexpected string (vendor.min-e4752403ddd4346488f8dcc53e06ff42.js:17)

Uncaught SyntaxError: Unexpected string (ghost.min-99ce2169542a4fe064a7ac5f6caba4c4.js:151) 
```

you can see it happening [here](https://luizkowalski.net/ghost/)

I think that might be related to the fact I'm running under Cloudflare maybe?

**Comment by kevinansfield** [comment]
Hey @luizkowalski 👋 Sorry you're having trouble, if you need help troubleshooting an install please head over to our [Slack channel](https://slack.ghsot.org). We use GitHub solely for tracking bugs and on-going feature work so this issue will be closed.

I would also suggest checking the troubleshooting section of the docs for this problem https://docs.ghost.org/docs/troubleshooting#section-ghost-admin-not-loading
