### ISSUE TITLE
The function `Schedule it for later` never works

### ISSUE THREAD

**Issue by hzb** [TryGhost/Ghost#9397]
### Issue Summary

The function `Schedule it for later` never works.

### Steps to Reproduce

1. New a story
2. Select `Schedule it for later`, and choose a time, and click `Schedule`
3. You will find it never works.
4. Look at this picture

![screen shot 2018-01-14 at 5 44 02 pm](https://user-images.githubusercontent.com/535675/34914711-3442141c-f953-11e7-891f-e0101cf9bf06.png)

I wrote this post two days ago, and I scheduled it to be published at 10:37 today, but It's 17:50 now, it's still in schedule.

### Technical details:

* Ghost Version: 1.19.0
* Environment development
* Browser/OS: google chrome on macOS high Serria, and the server is centOS 7
* Database: sqlite3

**Comment by hzb** [comment]
BTW, I set the size timezone under General menu, it's GMT+ 8.

**Comment by kirrg001** [comment]
@hzb Hey! I can't reproduce what you are experiencing.

> I scheduled it to be published at 10:37 today

Yes, but in the timezone GMT+8 and not in your timezone.

I suggest to schedule a post +3mins and watch the [server logs](https://docs.ghost.org/docs/cli-log). If you have any further problems, please swing by our [slack channel](https://slack.ghost.org) - we don't offer support in Github! We can always re-open this issue if it turns out to be a problem with Ghost.

**Comment by hzb** [comment]
@kirrg001 First GMT + 8 is my current timezone, second I will try later, and watch the server log.

**Comment by hzb** [comment]
@kirrg001 I think this issue should be opened again, I try this again, and I can reproduce this

1. New a story, and set its schedule.

![screen shot 2018-01-15 at 9 26 10 am](https://user-images.githubusercontent.com/535675/34923620-8fa34878-f9d8-11e7-9a3c-55b504b26c81.png)

2. Check it later, I get this.

![screen shot 2018-01-15 at 9 41 54 am](https://user-images.githubusercontent.com/535675/34923648-b6964818-f9d8-11e7-83fd-501cb17b92bd.png)

Yes, it doesn't work. And I check the log, I get this.

![screen shot 2018-01-15 at 9 41 02 am](https://user-images.githubusercontent.com/535675/34923684-fe418bf0-f9d8-11e7-987d-6500beec5146.png)

The log has no errors.

**Comment by kirrg001** [comment]
@hzb Can you please swing by our slack channel? Thanks!

> We can always re-open this issue if it turns out to be a problem with Ghost.

**Comment by hzb** [comment]
@kirrg001 I don't care that you will re-open this issue or not, and also I don't care you will fix it or not, I have submitted all that I met. I only submit issue in GitHub, if you don't like, I will submit the issue to this project, that's fine.
