### ISSUE TITLE
Feuture Request: Native No Follow Links

### ISSUE THREAD

**Issue by danielperez9430** [TryGhost/Ghost#9400]
### Why are the links No Follow important?

No Follow Links are Important for Web Positioning. Include in your SEO Strategy the use of Backlinks with No Follow Attribute

Now in Ghost:
`<a href="https://example.com">Web Link</a>`

I request this feature:
`<a href="https://example.com" target="_blank" rel="nofollow noreferrer">Web Link No follow</a>`

Could it be a native ghost function?

**Comment by kevinansfield** [comment]
Hey @danielperez9430 👋  This is already a native feature; Markdown supports inline HTML because it's not possible to encapsulate the entirety of the HTML spec in a pared down syntax, if you want to add extra attributes to links you can fall back to using inline HTML, eg:

```
This is a [standard link](http://example.com) and this is an <a href="http://example.com" target="_blank" rel="nofollow noreferrer">advanced link</a>
```

In your theme everything is HTML so you can override any links with `target="_blank"` or `rel` attributes as you see fit.

**Comment by danielperez9430** [comment]
Um, but in flarum using markdown. All links are native no follow link

**Comment by danielperez9430** [comment]
Um, but in flarum using markdown. All links are native no follow link

**Comment by danielperez9430** [comment]
I do not understand because it could not be native in Ghost. To avoid having to writing html attributes manually

**Comment by kevinansfield** [comment]
I don't know what flarum is but we won't be changing the behaviour in Ghost. `nofollow` is anti-user and anti-web, it has it's place (comments, user-generated content, embeds, etc) but not as a general attribute for all links. If you have specific links that you don't want to "endorse" as far as search engines are concerned then you are able to use HTML to add whichever attributes you want.

**Comment by kevinansfield** [comment]
I had a quick look at Flarum - it's a forum so the content is user-generated and untrusted so it's correct to use `rel="nofollow"` on links there, that's not the case for blog or general site content that Ghost is built for.

If we were to add comment functionality to Ghost then again any links in those comments would have `rel="nofollow"` added.

**Comment by danielperez9430** [comment]
Mark down editor in flarum:
<img src="http://i63.tinypic.com/2h8a17b.png></img>

Source code:
<img src="http://i68.tinypic.com/66yzcg.png" border="0" alt="Image and video hosting by TinyPic"></img>

Link test: https://foro.tecnonucleous.com/d/1-test/3

**Comment by AlejandroAkbal** [comment]
Is this still not a feature? Are really all links dofollow?
