### ISSUE TITLE
Update Documentation - Troubleshooting

### ISSUE THREAD

**Issue by mbullock1986** [TryGhost/Ghost#9401]
Sorry if this is the wrong place to paste

https://docs.ghost.org/v1.0.0/docs/troubleshooting

there is a section Cloudflare. When I was adding images/uploading images. 

> "Request was rejected because user is not permitted to perform this operation." 

was being shown

I was triggering the WAF.

<img width="789" alt="screen shot 2018-01-16 at 16 36 07" src="https://user-images.githubusercontent.com/24452374/35000104-66efdda2-fadb-11e7-8625-1fd251037969.png">

Cloudflare customers using the WAF (Pro, Bus and Ent) will have to add to the page rule to disable firewall:

<img width="465" alt="screen shot 2018-01-16 at 16 32 26" src="https://user-images.githubusercontent.com/24452374/34999909-e343467e-fada-11e7-985f-bf7d58e7606b.png">

or safe whitelist the IP they are editing the blog from. If the IP is Dynamic then option one may be needed.

**Comment by kirrg001** [comment]
Hey @mbullock1986 

Thanks for your help!

You can suggest an edit on each page. In the top right corner of https://docs.ghost.org/docs/troubleshooting, there is a button called `SUGGEST EDITS`. This will trigger an e-mail to the Ghost team. 

![editssuggest](https://user-images.githubusercontent.com/1160712/35053136-98bb2c1e-fba9-11e7-8438-5ed599f75c9a.png)
