### ISSUE TITLE
 bug with permission checking in `can-this.js`?

### ISSUE THREAD

**Issue by cotko** [TryGhost/Ghost#9406]
### Issue Summary

This is regarding *app* permission checking. I know apps are not officially supported but I'm trying to overcome some of current limitations using the app and I found a bug.

I checked out [this guide](https://github.com/TryGhost/Ghost/wiki/Apps-Getting-Started-for-Ghost-Devs) and tried to get posts using `browse`:

```js
// this works
proxy.api.posts.browse().then(/*...*/)

// while this is throwing a permission error
proxy.api.posts.browse({limit: 1}).then(/*...*/)

```
After debugging the code in *core* I've also added the app in the app table and added a permission relation for browsing. So now my [app is now loaded](https://github.com/TryGhost/Ghost/blob/master/core/server/services/permissions/can-this.js#L143) and browse permission check is correctly passed [in this part of code](https://github.com/TryGhost/Ghost/blob/master/core/server/services/permissions/can-this.js#L88)

But the whole permission check still fails [because of this](https://github.com/TryGhost/Ghost/blob/master/core/server/services/permissions/can-this.js#L98)

```js

                // ...

                if (hasUserPermission && hasAppPermission) {
                    return;
                }

```

If I understand the naming of `canThis(context)...` correctly, the context represents *app* / *user* / .. which makes me [think that this](https://github.com/TryGhost/Ghost/blob/master/core/server/services/permissions/can-this.js#L79)

```js

if (loadedPermissions.user && _.some(loadedPermissions.user.roles, {name: 'Owner'})) {
   hasUserPermission = true;
 } else if (!_.isEmpty(userPermissions)) {
   hasUserPermission = _.some(userPermissions, checkPermission);
}

```

should be changed to

```js

if (context.user === null) {
  hasUserPermission = true;
} if (loadedPermissions.user && _.some(loadedPermissions.user.roles, {name: 'Owner'})) {
   hasUserPermission = true;
 } else if (!_.isEmpty(userPermissions)) {
   hasUserPermission = _.some(userPermissions, checkPermission);
}

```

since can`This` relates to app and there is no user involved, also there is no user bound to the app at all and this part of code makes sure that [user is never loaded at all](https://github.com/TryGhost/Ghost/blob/master/core/server/services/permissions/can-this.js#L124). 

Or do you plan for apps to have owners and that both, owner's permissions and app's permissions will be checked in the future when app will try to access a resource?

**Comment by kirrg001** [comment]
@cotko Hey! 

Apps are not a thing yet und unsupported - the only purpose of [the wiki](https://github.com/TryGhost/Ghost/wiki/Apps-Getting-Started-for-Ghost-Devs) is to **build demo apps.**

Fetching public data (posts, tags) should work for sure (`this.ghost.api.posts.browse`). Anything else is not designed or implemented yet. Please re-read through our app guides or look at existing examples on Github.
