### ISSUE TITLE
CPU usage has been 100%. 

### ISSUE THREAD

**Issue by KISSMonX** [TryGhost/Ghost#9410]
I`m Sorry, Slack can not visit. 

### Technical details:

* Ghost Version:   v6.12.3
* Node Version: 1.4.2
* Browser/OS: chrom/ Ubuntu 16.04
* Database: mysql

**1GB  RAM, 1 Core.**
Thanks. 

![20180119223354](https://user-images.githubusercontent.com/2876745/35156226-2c677ffe-fd6b-11e7-9236-7a1faf78fb4f.png)

**Comment by KISSMonX** [comment]
So much Node and Ghost process

**Comment by KISSMonX** [comment]
![image](https://user-images.githubusercontent.com/2876745/35156432-c7c711d0-fd6b-11e7-9588-5d7e3df5ca0e.png)

**Comment by kirrg001** [comment]
Hi @KISSMonX 

We're sorry to hear you're having problems, but i can't help you here in Github.
Please swing by our [slack channel](https://slack.ghost.org). I am then able to help you looking into this further. If it turns out there is a problem in Ghost, we can always re-open this issue.
