### ISSUE TITLE
Ghost says upgrade is available, but I'm already on this version

### ISSUE THREAD

**Issue by koyuawsmbrtn** [TryGhost/Ghost#9411]
![](https://i.koyu.space/eu58alzt.png)

What I did? I ran `ghost update`
What I expected: Ghost shouldn't be complaining about new upgrades
What it actually does: It does complain about a new upgrade

### Technical details

Ghost 1.20.2 (but details are in the screenshot above)
Node: 8.9.0 via NVM (because I'm running different Node versions on this machine)
Browser: Chome OS 63.0.3239.116
Database: MySQL
Environment: Production
Mail Server: Google SMTP

### Steps to reproduce

Upgrading with Ghost CLI via `ghost update` inside the Ghost root directory

**Comment by kirrg001** [comment]
Hey!

This was fixed in master already, see https://github.com/TryGhost/Ghost/commit/357ea3dffd8a434c01ad4be9c877de98d07fea9b.
Will be released next week.
