### ISSUE TITLE
Re-work asset hashes

### ISSUE THREAD

**Issue by kirrg001** [TryGhost/Ghost#9414]
# Current State and problems

## Asset hash url

Ghost currently uses the concept of adding an asset hash as query parameter in Ghost.

e.g. `/public/ghost-sdk.min.js?v=12345` (built assets)
e.g. `/assets/built/main.css.min?v=123456` (theme assets)

This allows us to invalidate an asset if the file was changed.

Using query params get's marked as [complain](https://kinsta.com/knowledgebase/remove-query-strings-static-resources/) by performance tools. The reason is that most caching software won't cache urls with query parameters.

## Asset hash for core built files?

The Ghost JS SDK almost never changes, but the [SDK is dynamic](https://github.com/TryGhost/Ghost/issues/9436). Read more about this in the issue. 

We have to take care that if the admin url changes, we have to regenerate the asset hash for the Ghost SDK. If we fix #9436, we can ignore this requirement.

## Asset logic

Currently we remember the `assetHash` [as configuration value](https://github.com/TryGhost/Ghost/blob/1.20.2/core/server/data/meta/asset_url.js#L44). Not persistent, only kept in process. On every restart, the config value is null and forces a regeneration.

We use only one `assetHash` for both core build and theme assets. If you change a theme, the core build files get a new url as well. Which sucks 😎 , because the amount of requests for built assets increases as soon as the asset hash changes.

# How do others deal with endpoints?

## Require endpoint/host

Many SDK's require you to configure the endpoint/host on SDK initialisation.

Examples:
- https://docs.treasuredata.com/articles/javascript-sdk
- https://shopify.github.io/js-buy-sdk/

We also [allow you to configure your own url](https://github.com/TryGhost/Ghost/blob/1.20.2/core/server/public/ghost-sdk.js#L61), but as said, the fallback is the embedded admin url into the SDK.

It's not really easy to find more good examples, because Ghost is special. It can be used for self hosters and on Pro. Plus you can configure a custom domain etc.

## Static CDN url

This is a common approach for a single product. Not really useful for Ghost, where every blog has a different domain.

Examples:
- Facebook, AWS etc.

# Solutions

## Hashed file path for theme assets

e.g. `/assets/built/main.1234.css`

The hash should be regenerated as soon as the file content has changed (for development env) and on theme change (for development+production env).

**We should not write theme files to disk.** Every time a theme asset changes or you activate a different theme, we won't build a different min file from the original. Ghost should handle this in process. e.g. keep a theme hash in the settings table.

## CSS built asset

Simply stick with asset hashes. If the file get's changed for the next release, the file content changed, the file path get's regenerated. 99% of the cases, the SDK asset hashed url stays the same over a long period of time.

### Option A

Use a versioned url e.g. `/public/1.0/ghost-sdk.min.js`. This has the disadvantage that if the SDK get's changed in a release, then we have to remember changing the URL. This option sounds like manual maintenance?

### Option B

Simply stick with asset hashes. If you modify the SDK for the next release, the file changes, the file path get's regenerated. 99% of the cases, the SDK asset hashed url stays the same over a long period of time. If you reconfigure your admin url, we have to ensure yourself that you invalidate the cache - this needs documentation.

### Option C

Inline SDK JS into the page. Some performance tools also complain about `Blocking JS request to render the page` for the SDK. This complain is not really serious or important, because the minified version of the SDK is very small < 1KB. It's in theory blocking the page to render, because we have to request the JS file before rendering. But the size is so, so small. Nothing we have to focus on.

But it's still an option. That would mean, we don't need any asset hashing for the SDK. For self hosters, if they update Ghost to a newer version with the CLI and they don't have a page cache, the site simply get's served including the SDK changes. When using a page cache, it get's invalidated on release. But i am in favour of sticking to `Option B`, because also the CSS core built has to be served. Consistency reason.

**Comment by jloh** [comment]
Why not do a sha1 hash of the file contents as opposed to generating a random one? This means more cache hits/less requests when Ghost is restarted since, if the content is the same, the hash doesn't change?

Whilst gulp specific something like this https://www.npmjs.com/package/gulp-hash
