### ISSUE TITLE
Reduce bootstrap time

### ISSUE THREAD

**Issue by kirrg001** [TryGhost/Ghost#9416]
We tried to optimise the bootstrap time of the Ghost server already in the past. But this was mostly done by requiring dependencies on runtime and not on server start. This was the easiest approach for the beginning. But we really need to rewrite our [core bootstrap file](https://github.com/TryGhost/Ghost/blob/1.20.2/core/server/index.js) to get an overview of:

1. What is really required for a server start?
2. What can happen after server start?

Currently i have the feeling almost everything get's required, except of some third party dependencies.

Current bootstrap on my MacBook (16gb memory i7): **1,8s**
- ~1,2second to require Ghost and it's dependencies
- ~600-700ms to bootstrap Ghost (initialise modules etc.)

My setup is quite powerful. Other devs experienced bootstrap times of ~2/3seconds. Definitely not acceptable.

Possible instruments:
- [ ] research other big JS platforms
- [ ] rewrite core bootstrap file and get an overview
- [ ] make a list of required modules to bootstrap
- [ ] figure out which of these modules are slow and come up with ideas
- [ ] play with magic getters
- [ ] more usage of events
- [ ] ...?

I'll have to research a bit more. This is just a first draft. I'll report back with comments.

**Comment by tiborsaas** [comment]
On my small DigitalOcean droplet it's around 6 sec on average :)
