### ISSUE TITLE
Subscribing open to spamming

### ISSUE THREAD

**Issue by bartt** [TryGhost/Ghost#9418]
### Issue Summary

Subscribing to a Ghost blog that has enabled the experimental subscription feature is open to spamming. Spammers will submit the subscription form with _just_ the email addresses filled out. Ghosts accepts these. My small blog (https://thecodemill.biz) receives about half a dozen fake subscriptions a day. 

Combined with the new Zapier integration this could lead to a rather unpleasant situation when these addresses are subscribed to a Mailchimp email list and start receiving email. 

### Steps to Reproduce

Assuming Ghost is running on port 80 on `localhost`.

1. Subscribe with just an email address:
```curl -d "confirm=&location=&referrer=&email=spam@example.com" http://localhost/subscribe/```
2. Observe that `spam@example.com` is among the subscribers in `http://localhost/ghost/#/subscribers`.
3. Check the subscribers table in the DB and you'll notice that `spam@example.com` was registered without `subscribed_referrer` or `subscribed_url`. 

### Technical details:

* Ghost Version: 1:20 official docker image
* Node Version:
* Browser/OS: N/A
* Database: SQLite from official docker image

**Comment by kevinansfield** [comment]
> Combined with the new Zapier integration this could lead to a rather unpleasant situation when these addresses are subscribed to a Mailchimp email list and start receiving email.

Not a direct response to this issue but if you are funnelling Ghost subscribers through to MailChimp via Zapier you should probably have the double opt-in option enabled so that MailChimp sends a confirmation e-mail before the e-mail address is added to the list.

The subscribers feature is intentionally _very_ limited in Ghost at the moment (one of the main reasons it's still in beta 😉) with the idea being that it's a gateway for deeper integrations via Zapier. The feature will be become more fleshed out as work on members progresses.

**Comment by kirrg001** [comment]
Email Verification (double opt-in) can be done via the Zapier integration - as @kevinansfield pointed out. 

There are multiple cases where the referrer can be empty. So requiring it and throwing an error is in my opinion not the right solution here. You can always delete all subscribers with an empty referrer from your database or from your exported CSV.

**Comment by bartt** [comment]
Yes, the referrer can be empty and should not be required. Though a the POST to /subscribe should have a referrer, namely the URL of the page where the user filled out the form. I'll amend the pull request. 

That doesn't mean that the form shouldn't have better protection against fake signups. Prevent bogus signups at the gateway from making it into the database, don't leave it up to the downstream pipeline to handle.

As I mention in the pull request, it is a stop gap measure. And a necessary one.

**Comment by kirrg001** [comment]
> Wouldn't adding CSRF protection solve part of this issue?

https://www.owasp.org/index.php/Cross-Site_Request_Forgery_(CSRF)
> Cross-Site Request Forgery (CSRF) is an attack that forces an end user to execute unwanted actions on a web application in which they're currently authenticated

CSRF does not prevent spam. 

> The subscribers feature is intentionally very limited in Ghost at the moment (one of the main reasons it's still in beta 😉) with the idea being that it's a gateway for deeper integrations via Zapier. The feature will be become more fleshed out as work on members progresses.

Some techniques for spam protection:
1) email validation - in place
2) enable double opt in (email confirmation) - possible using Zapier
3) brute force protection for the ip address (but it won't avoid spam completely, it just reduces spam)
4) captcha for the form (proof human, ux downside)
5) honeypot fields to trick spam bots (does not protect against manual attack)

I'll re-open this issue for now to add **(3)** and maybe (5). Any other suggestions are welcome.

**Subscribers is a beta feature. Any help is appreciated 👍 Thank you!**

**Comment by kevinansfield** [comment]
Token-based CSRF and possibly Captcha will require a fairly large change to how the subscriber form works because it's typically included on every page and will be heavily cached (meaning no dynamically generated token).

If we want to use such techniques it's likely we would need to have an endpoint that only serves the form so that it can be included on cached pages via JS.

**Comment by kirrg001** [comment]
As the [upcoming members feature](https://github.com/TryGhost/Ghost/issues/10213) will and should replace subscribers, the Ghost team won't improve the spam protection for subscribers.

---

But we might need spam protection for members if there is no auto double opt-in available. cc @allouis here to share that this issue exists.

**Comment by dlford** [comment]
For anyone that is still getting subscriber spam, my workaround is to change the `subscribed_url` column in the MySQL database to `NOT NULL`, this will silently drop subscription requests that don't include a `subscribed_url` value.  It's not a particularly elegant solution but an effective one for the time being.

MySQL command:

```sql
ALTER TABLE subscribers MODIFY subscribed_url varchar(2000) NOT NULL;
```

To revert this change if needed:

```sql
ALTER TABLE subscribers MODIFY subscribed_url varchar(2000) DEFAULT NULL;
```

**Comment by curiositry** [comment]
@dlford Do you happen to have a version of your solution that would work in 2024? 

I'm getting hit with a tonne of spam signups that are hurting my sending reputation just from the confirmation emails, and this looks like it could be just what I need.

Thanks!

**Comment by dlford** [comment]
@curiositry sorry, I stopped using Ghost, I've seen too many issues "closed as completed" on here without even being addressed.

If you're looking for a better subscription handler though Listmonk is fantastic, open source of course.

**Comment by curiositry** [comment]
Thanks for your quick reply @dlford! If I find a solution I will post it here.
