### ISSUE TITLE
Navigation slug comparison to post's primary_tag

### ISSUE THREAD

**Issue by kezfran** [TryGhost/Ghost#9420]
Hello here!
I want to compare the navigation slug to the current post's primary_tag in the navigation.hbs file so that I can add the nav-current class in this context but I don't know how to access the primary_tag.

I tried with this: 
> {{#if slug === 'primary_tag'}} nav-current{{/if}}

but it doesn't work.

How do I do this?
Thank you

**Comment by kevinansfield** [comment]
Hey @kezfran  👋 Please do not use GitHub for support, our [support guide](https://github.com/TryGhost/Ghost/blob/master/.github/SUPPORT.md) was linked in the GitHub notification above the issue creation form and has details about what issues you should raise here and which issues should be handled elsewhere. (Many projects have their own support guidelines and GitHub highlights them for you, please read them before opening issues 😄)

You can use [slack](https://slack.ghost.org) to get community support if you're not able to find the answer in the [docs](https://docs.ghost.org).

**Comment by kezfran** [comment]
Thank you @kevinansfield and sorry for that.
