### ISSUE TITLE
i18n: Problem with Placeholders with subexpressions

### ISSUE THREAD

**Issue by couchsoft** [TryGhost/Ghost#9422]
### Issue Summary

I am trying to use the new t-helper (which is GREAT to have now) within my theme!
I try to use Placeholders with subexpressions as described here: https://themes.ghost.org/docs/i18n#section-placeholders-with-subexpressions.

Thanks very much for your help!

### Steps to Reproduce

I am doing the following, in `partials/author.hbs`:

```hbs
<span class="lead">{{t "More posts by {author}" author=(name)}}</span>
```

In `locales/en.json` I have only one line:

```json
{
  "More posts by {author}": "More posts by {author}"
}
```

I get the following message:

```
500
[post.hbs] ((helpers.name || (depth0 && depth0.name)) || alias2).call is not a function
```

### Technical details:

* Ghost Version: 1.20.2
* Node Version: v6.9.5
* Browser/OS: Firefox 57.0.4, Windows 10
* Database: sqlite

**Comment by kirrg001** [comment]
Hey 👋

`author.name` is not a subexpression, because `name` is not a helper. It's a data attribute.

I think this should work:

```
{{#author}}
<span class="lead">{{t "More posts by {author}" author=name}}</span>
...
```

**Comment by couchsoft** [comment]
Thanks, this way it works!
