### ISSUE TITLE
Add support for markdown-it-center-text 

### ISSUE THREAD

**Issue by andrewmur** [TryGhost/Ghost#9424]
### Issue Summary

It would be great to be able to use `->Centered Text<-` markdown syntax instead of _html_ to center the text

### Steps to Add
1. [Add markdown-it-center-text plugin](https://www.npmjs.com/package/markdown-it-center-text)
2. `.use` it during *md* initialization
3. update user info

### Technical details:

* Ghost Version: 1.4.1
* Node Version: 6.10.0
* Browser/OS: All

**Comment by andrewmur** [comment]
**Actual:**

```
<p style="text-align: center;">this text should be centered via `p`</p>

<p align="center">this text should be centered via `p attribute`</p>
```

**Expected:**

`->this text should be centered by markdown<-`

**Comment by kevinansfield** [comment]
@andrewmur the idea with our markdown support is to be as cross-compatible as possible. Adding extra features that start to deviate from the CommonMark spec (especially when there is a very valid workaround via HTML that will work for multiple different use-cases) is not something that we're likely to do, especially as it's the start of a slippery slope to all sorts of esoteric "enhancements" to markdown.

**Comment by andrewmur** [comment]
I understand. Then it would be great to have this automated via Dedicated button like on Medium, so people would not need to write this HTML part manually, cause not everyone is familiar with it.

**Comment by 1014670860** [comment]
Has it been solved now? can the text be centered?
