### ISSUE TITLE
Bug: Ghost data not persisting in docker container

### ISSUE THREAD

**Issue by scoobster17** [TryGhost/Ghost#9429]
### Issue Summary

Ghost data does not persist when in a docker container, even when mounting a volume. This is reproducible in newer versions of Ghost (v1.20.2, v1.20.3) however rolling back to an older version (v0.11.12) everything works fine with no other changes.

The result of this is that every time the docker container is started, I need to re-create the user(s) and all article content from scratch.

### Steps to Reproduce

1. Run command `docker run -d -p 5555:5555 -v $PWD/ghost-data:/var/lib/ghost/content ghost:1.20.3` to start a docker container for ghost.
2. Go to `http://localhost:5555/signin` and register a new user
3. Create some articles
4. Run `docker ps` to find the container ID
5. Run `docker stop <containerId>` to stop the container
6. Re-run step 1, to find that no article content exists and you have to register a new user/re-register the same user.

**This is a bug because it works with older version(s) of Ghost, but not newer versions**, which leads me to believe it is a problem with ghost and not docker.

E.g. running the command `docker run -d -p 5555:5555 -v $PWD/ghost-data:/var/lib/ghost ghost:0.11.12` with v0.11.12 works fine (and without `/content`, as the documentation also says is necessary for the newer version).

### Technical details

* Ghost Version: latest v1.20.3, and previous
* Client OS: MacOS High Sierra v10.13.1
* Server OS: Docker Ubuntu
* Node Version: 9.4.0
* Browser: Content added in Chrome / checked in Chrome
* Database: sqlite3

**Comment by kirrg001** [comment]
Hi @scoobster17 

You should definitely raise this issue first in the docker repository. Maybe the database name is renewed on container start, but just an assumption. 

You can always use our [slack](https://slack.ghost.org/) community - https://slack.ghost.org.

**Comment by scoobster17** [comment]
FYI This works as of yesterday using the command `docker run -d -p 2368:2368 -v $PWD/ghost-data:/var/lib/ghost/content/data ghost:latest`.

I assume the latest version of ghost being used is `1.21.7`, the docker version I am using is `18.03.0` and the node version I have running currently is `8.7.0`.

**Comment by kirrg001** [comment]
@scoobster17 Thanks for sharing!
