### ISSUE TITLE
Ghost-Admin - Upgrade ember-cli-mirage

### ISSUE THREAD

**Issue by kevinansfield** [TryGhost/Ghost#9433]
We're currently sitting on a pretty out-of-date version of `ember-cli-mirage`, mostly because of the time required to go through the upgrade process to move everything and update for the latest APIs.

Upgrading will mean one less package bringing in old babel versions and speeding up our yarn install.

**Comment by kevinansfield** [comment]
This is a requirement for #9478 now that [v0.4.2](https://github.com/samselikoff/ember-cli-mirage/releases/tag/v0.4.2) has added support for Ember's new test helpers.

**Comment by acburdine** [comment]
Cool - I’ll make sure to get this done this weekend.
