### ISSUE TITLE
Ghost SDK Dynamic

### ISSUE THREAD

**Issue by kirrg001** [TryGhost/Ghost#9436]
# Current State and goal

The Ghost SDK almost never changes, but the **SDK is dynamic**, because we currently auto-insert the admin url, [see](https://github.com/TryGhost/Ghost/blob/1.20.2/core/server/public/ghost-sdk.js#L4). This requires us to regenerate the asset hash on server restart. 

And if you are using a page cache, we serve your SDK with your configured admin url with a specific asset hash. The SDK asset get's cached in the browser and in the page cache. Now you change the admin url in your `config.[env].json`. You restart Ghost. The asset hash get's regenerated, fine. But the page is not invalidated. So the served page contains the old path to the SDK. That means you are responsible to invalidate the cache manually?

**If we are able to get rid of the dynamic behaviour of the SDK, we only need to generate a new asset hash on a release if the file was modified.**

# How do others deal with this problem?

Most serve their SDK via a CDN, which won't change. 

Some require you to pass the domain e.g. [shopify](https://shopify.github.io/js-buy-sdk/). The SDK throws an error if you don't pass the target domain.

More examples?

# Two ways of access

## SDK on your blog frontend

You use the Ghost SDK on your blog frontend. 

e.g. http://kirrg.win is the blog frontend.

You request `http://kirrg.win/ghost/api/v0.1/configuration`, the requests get's automatically redirected to `https://kirrg001.ghost.io/ghost/api/v0.1/configuration`, because you try to access the API.

*No endpoint/domain would be required.* 

The default script embed is currently:

> <script type="text/javascript" src="/public/ghost-sdk.min.js?v=23b8f86366"></script>

It fetches the SDK from the current domain. No endpoint required.

The blog frontend domain is whitelisted for API requests.   We just need to ensure that requests are redirected including the CORS information. If we loose them, you will run into a CORS error.

## SDK on a different domain

If you request your blog API/domain from an external domain using the SDK, you have to use an explicit endpoint/domain, because you are operating from a different domain.

The default script embed for external usages:

> <script type="text/javascript" src="https://my-ghost-blog.com/public/ghost-sdk.min.js"></script>

External access must already define the blog endpoint when fetching the SDK.

Currently we allow you to pass the blog endpoint to the SDK, but we don't require it. Because we fallback to the admin url we passed in into the SDK. 

# Possible solution A

Read the script tag value from the HTML head and parse the endpoint/domain.

# Possible solution B

Make the endpoint/domain required in the next major release.

More ideas? They are welcome!

**Comment by m1guelpf** [comment]
Is this fixed?

**Comment by kirrg001** [comment]
@m1guelpf No. It's still open and tracked in our backlog.

**Comment by kirrg001** [comment]
@ErisDS I guess we can close this issue too, because of the new Ghost SDK.

**Comment by ErisDS** [comment]
Yep
