### ISSUE TITLE
Many small tooling cleanup tasks

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#9441]
This issue contains a list of mostly small cleanup tasks for our tooling.

Aim is to move towards consistency between repos (both public and private) to lean on package.json scripts more heavily where possible, simplify grunt & essentially make this repo neater & easier to use 😁 

- [x] Switch eslint to use eslint-plugin-ghost (OK this isn't that small)
- [x] Use .js files rather than .json for eslint config
- [x] Remove grunt-eslint, use `grunt run` or `grunt shell` instead cos it's more generic, and we can do other things this way
- [x] Add `lint` as a script in package.json
- [x] Swap .gitignore for standardised file + customisations at end
- [x] Fix .gitignore so we don't have tracked files in in the ignore:
```
content/data/README.md
content/themes/casper/
content/apps/README.md
content/images/README.md
content/logs/README.md
core/server/public/ghost-sdk.min.js
core/server/web/admin/views/.gitkeep
```
- [x] Review .npmignore file
- [x] `grunt release` creates a zip with contents which do not equal .tgz (e.g. https://github.com/TryGhost/Ghost/commit/0db01a02374bfddcca08fb9ecd2286d078f9a74c)
- [x] Refactor Gruntfile.js so it isn't so indented
- [x] We aren't using greenkeeper - cleanup ignores from package.json
- [x] Why is minimist a dev dep?! 
- [x] Fix brute-knex dependency
- [x] Consider moving coverage out of grunt into a script in package.json
- [x] Consider tests: can we restructure them so they are easier to run? 🤔 
- [x] Let `grunt master` fail when working tree is not clean

**Comment by ErisDS** [comment]
Some of this is outdated, but I'm sure there are plenty more small tasks like this that have cropped up in the year since I wrote this.

**Comment by allouis** [comment]
https://github.com/TryGhost/Ghost/commit/bdd57b36cfc382f4d1df872834a8e99b4a4ba359 Removed a layer of indentation from the Gruntfile, I don't think we can remove much more due to the way grunt injects itself, e.g.

```js
module.exports = function (grunt) {
    // Do stuff w/ grunt here, nested one level
}
```

**Comment by ErisDS** [comment]
Note the `grunt master` command is currently broken - if you try to run it when the submodules are out of date it errors, rather than updating them, which is its job!

**Comment by allouis** [comment]
@ErisDS I'll take a look at that

**Comment by JohnONolan** [comment]
Broken for me too

![image](https://user-images.githubusercontent.com/120485/53961947-89392e00-40f2-11e9-9f02-dbe192448d8a.png)

**Comment by JohnONolan** [comment]
Ok I ran it 3 more times and it timed out in different places each time and then eventually completed

**Comment by allouis** [comment]
^ looks this was a network/yarn issue rather than the grunt task :relaxed:

**Comment by allouis** [comment]
> grunt release creates a zip with contents which do not equal .tgz 

After creating a release zip and using `npm pack` to create a tarball, I extracted them to a `zip` and `tgz` directory respectively.

```
 >> diff -r tgz/ zip/
Only in tgz/content/themes/casper/assets/css: .csscomb.json
Only in zip/content/themes/casper: config.example.json
Only in tgz/content/themes/casper: .yarnrc
Only in zip/core/server/lib/members/static/auth: dist
Only in zip/core/server/lib/members/static/auth: index.html
Only in zip/core/server/lib/members/static/gateway: index.html
Only in tgz/core/server/web/admin/views: .gitkeep
Only in tgz/: .eslintignore
Only in tgz/: .eslintrc.json
Only in tgz/: .npmignore
```

Will work on resolving these differences

**Comment by allouis** [comment]
The output tars/zipz of `grunt release` and `npm pack` now unpack to the same directories, apart from these two files:

```
>> diff -r tgz/ zip/
Only in zip/core/server/lib/members/static/auth: dist
Only in zip/core/server/lib/members/static/auth: index.html
```

This will be fixed when members has been moved into it's own monorepo.which is tracked here: https://github.com/TryGhost/Ghost/issues/10701

Closing this now :tada:
