### ISSUE TITLE
Support filtering RSS by author+tag

### ISSUE THREAD

**Issue by kustodian** [TryGhost/Ghost#9442]
Ghost currently supports RSS feeds by tags (e.g. https://blog.ghost.org/tag/tag1/rss/) or authors (e.g. https://blog.ghost.org/author/john/rss/), but it doesn't support filtering RSS feeds by tag and author, so that you can list RSS feeds which were written by `john` and have a tag `tag1`.

Concrete example where this is needed is for blog aggregation platforms, e.g. https://planet.postgresql.org/ where you need to submit an RSS feed of articles about Postgres and they need to be submitted for each author separately.

WordPress (and many other platforms) support this out of the box. In WP you can use an URL like:
```
https://mywpblog.com/author/john/feed/?tag=postgres
```

Ghost could probably do the same thing.

**Comment by kirrg001** [comment]
Hi @kustodian!

Thanks for the idea! We already collected some RSS ideas from customers internally - I've added yours. 

We only keep Github issues open for bugs and in-progress feature work.
