### ISSUE TITLE
encode url absolute true

### ISSUE THREAD

**Issue by DilionsCode** [TryGhost/Ghost#9443]
So I'm wondering why you can't encode like this?
`{{encode url absolute="true"}}`
Instead I have to write it like this 
`{{encode @blog.url}}{{encode url}}`

This kinda makes it crazy to encode the whole URL

**Comment by kirrg001** [comment]
Hey @DilionsCode.

We're sorry to hear you're having problems, but ask that you do not use our GitHub repo for support. Please read our [support guide](https://github.com/TryGhost/Ghost/blob/master/.github/SUPPORT.md). You can always use our [slack](https://slack.ghost.org/) community - https://slack.ghost.org, if you're not able to find the answer in our [documentation](https://docs.ghost.org/) - https://docs.ghost.org.
