### ISSUE TITLE
Ghost-CLI 1.5.1 time-out causes installs / updates on Raspberry Pi to fail

### ISSUE THREAD

**Issue by raspberrycoulis** [TryGhost/Ghost#9447]
### Issue Summary

Whilst it is now the supported stack, Ghost does run on Raspbian on Raspberry Pi with some minimal adjustments. However, the latest CLI tool breaks the install and update process on Raspbian due to timeout issues causing Ghost to give up when restarting.

### Steps to Reproduce

1. Running Ghost Update in the install directory advises to update the CLI tool.
2. Updated the CLI tool.
3. Ghost Update again
4. Install works, but restarting Ghost fails.
5. Error logs show a timeout issue.
6. Slack community recommended tweaking the port-polling.js file to increase the timeout (in milliseconds)
7. Doubling the MS from 1000 to 2000 and the 30 to 60 fixes issue as when reattempting the update or install works just fine.

Only a minor tweak to reinclude Raspbian \ Raspberry Pi users would be appreciated to avoid manual changes like this. Ghost works with some minor changes to the base OS, so why exclude Raspbian users over a few milliseconds? 😁

### Technical details:

* Ghost Version: 1.21.1
* Node Version: 6.12.3
* Browser/OS: Raspbian v9.1
* Database: MySQL

**Comment by acburdine** [comment]
@raspberrycoulis feel free to recreate this issue/submit a PR in the Ghost-CLI [repo](https://github.com/TryGhost/Ghost-CLI) - that’s where it belongs 😄
