### ISSUE TITLE
No support for webp images

### ISSUE THREAD

**Issue by Leoooob** [TryGhost/Ghost#9448]
### Admin panel support for webp images

I think it's important to support the webp image format by allowing ghost bloggers to use the post editor to upload webp images, rather than manually uploading to your server and then using embedded html tags.

This means that some considerations will have to be taken when embedding the image in-site, to support older browsers. Not sure how this should be handled e.g. once you've uploaded a jpeg, all users to add a webp version for clients that support it?

### Steps to Reproduce

1. Open Ghost admin panel
2. Open a post/new post
3. Add an image and try to upload webp

### Technical details:

* Ghost Version: master (commit: bfd3286b61fe724206b94d441036019c03122a64)

**Comment by kevinansfield** [comment]
Hey @Leoooob 👋 Until Ghost has an [image processing pipeline](https://github.com/TryGhost/Ghost/issues/4453) we'll only be supporting image formats that are fully supported across browsers.

**Comment by juandosimple** [comment]
Hi,
There was any advancement in this subject? Thanks!

**Comment by sreerajnova** [comment]
is there any possibilities ?

**Comment by MaskyS** [comment]
@kevinansfield, Looks like image processing is here! Do you think Ghost will support WebP images in the near future? (say, 1 year?)

**Comment by Leoooob** [comment]
any update on this now that there **is** an image processing pipeline?

**Comment by fluse** [comment]
why is there a problem to check if webp then skip processing?

**Comment by abdilra7eem** [comment]
> why is there a problem to check if webp then skip processing?

This will lead to images not showing on incompatible browsers (Not all browsers support WebP, *cough* Apple).

But it would be very nice if I could use it at my own risk

**Comment by Leoooob** [comment]
it's easy enough to use [picture](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/picture) to embed a number of formats to serve both modern and legacy browsers. 

@kevinansfield is there a process for reopening an issue/getting it reviewed?

**Comment by mbedded** [comment]
Yes, a repoen of this issue would be great. Many images could be half-size of their current size but the web UI won't let me use the webp image.. :(

**Comment by jdcauley** [comment]
PR https://github.com/TryGhost/Ghost/pull/12057 would provide a clear bath forward for this issue

**Comment by andreborud** [comment]
It looks like Safari 14 will support it, once Safari does all major browsers will support webp, so its probably time to reopen this one! ;)

[https://caniuse.com/#search=webp](https://caniuse.com/#search=webp )

**Comment by ochronus** [comment]
@kevinansfield any chance of reopening this? Browser compatibility is not an issue, you can wrap multiple <srcset>s in a <picture> tag with separate types each (jpeg, webp etc.) WebP has some serious wins in size. AVIF also just landed...

**Comment by jdcauley** [comment]
@ochronus 

Ghost is open source but not really developer friendly. I wouldn't count on this anytime soon.

**Comment by sklinkert** [comment]
I think this topic is becoming more important due to the Google's Core Web Vitals coming around spring 2021.

Page Speed Insights is already complaining about Ghost's image format:

**Serve images in next-gen formats**
Image formats like JPEG 2000, JPEG XR, and WebP often provide better compression than PNG or JPEG, which means faster downloads and less data consumption. [Learn more](https://web.dev/uses-webp-images/?utm_source=lighthouse&utm_medium=unknown).

**Comment by jdcauley** [comment]
@sklinkert 

I managed to start getting somewhere by pairing Ghost with Eleventy and Netlify. 

I think it's going to be the only option for a pretty out of the box perf capable solution.

Or you could put cloudflare with polish in front of your Ghost install.

I'm working on getting my eleventy build to work with my thumbor install.

**Comment by ikamet** [comment]
Is there any update on this as it's more than overdue. Thanks
