### ISSUE TITLE
Improve docs on Configuration

### ISSUE THREAD

**Issue by sr229** [TryGhost/Ghost#9449]
### Issue Summary

Ghost is a great blogging platform, however, I saw some issues regarding documentation:

- Documentation regarding config should be improved a little (for example, person X has knowledge on the basic config settings, but they don't know how to apply the config object for ``mail`` via env vars).

- Remote database connections are somehow not visible in the documentation.

**Comment by acburdine** [comment]
> mail via env vars
[This section](https://docs.ghost.org/v1/docs/config#section-running-ghost-with-config-env-variables) details how to configure something via environment variables - including nested properties. It can be inferred from that section how to configure mail via environment variables.

> Remote database connections are not visible
See [here](https://docs.ghost.org/v1/docs/config#section-mysql) -> it contains the configuration for a local mysql instance, which should be exactly the same as a remote database instance if the host (and possible the port) is changed.

If you have future suggestions for documentation - please use the "Suggest Edits" button on https://docs.ghost.org 😄
