### ISSUE TITLE
bad link on site

### ISSUE THREAD

**Issue by boneskull** [TryGhost/Ghost#9457]
I couldn't find the site repo, but wanted to let you know that on this page:

https://ghost.org/developers/

The "Support" link in the upper-right points to https://help.ghost.org/hc, which is a 404

**Comment by boneskull** [comment]
this seems to affect the landing page at https://ghost.org as well.

**Comment by kevinansfield** [comment]
@boneskull thanks for reporting! This should be fixed now, it may take a little while until all caches clear but we'll be adding a redirect too so that there's no chance of a 404.
