### ISSUE TITLE
Ghost API: Post content not showing

### ISSUE THREAD

**Issue by vavdagic** [TryGhost/Ghost#9460]
### Issue Summary
When using Ghost API to send post data, using field "plaintext" shows content text in text snippet (visible from admin page), but when you open the post itself, it shows just "null".

### Steps to Reproduce

1. Add post using Ghost API.
2. Send data using "plaintext" field.

**Comment by vavdagic** [comment]
@acburdine that is not very intuitive. Nevertheless thanks for your explanation!

I have one more question, how do you upload media files (images) using API?

**Comment by acburdine** [comment]
> that is not very intuitive

That's why it's private API and not yet officially public 😉

> how do you upload media files

Can't remember the endpoint offhand, but if you look at the network request Ghost-Admin sends when uploading an image you should be able to see what that endpoint is and what to send to it 😄

**Comment by vavdagic** [comment]
@acburdine  thanks! 👍

**Comment by AileenCGN** [comment]
Closing this as it's not an issue with Ghost itself.
