### ISSUE TITLE
Not able to upload image using API to Ghost CMS

### ISSUE THREAD

**Issue by vavdagic** [TryGhost/Ghost#9462]
When sending this request using Python's requests module:

```
    files = {'media': open("test_image.jpg", 'rb')}
    response = requests.post(
        headers={'Authorization': 'Bearer %s' % auth},
        url=url + '/uploads/',
        files=files
    )
```

I get 500 Internal Server Error

Also, I have tried this:

```
    image_file = "test_image.jpg"
    image_data = open(image_file, 'rb').read()

    response = requests.post(
        url=url + '/uploads/',
        data=image_data,
        headers={
            'Authorization': 'Bearer %s' % auth,
            "Content-Disposition": 'form-data; name="uploadimage"; filename="test_image.jpg',
            "Content-Type": "multipart/form-data",
        }
    )
```

what am I doing wrong?

**Comment by ErisDS** [comment]
Hi @vavdagic,

We're sorry to hear you're having problems, but ask that you do not use our GitHub repo for support. Please read our [support guide](https://github.com/TryGhost/Ghost/blob/master/.github/SUPPORT.md). You can always use our [slack](https://slack.ghost.org/) community - https://slack.ghost.org, if you're not able to find the answer in our [documentation](https://docs.ghost.org/) - https://docs.ghost.org.

**Comment by ilyaLibin** [comment]
@vavdagic Check [this post](https://blog.picpipe.io/how-to-upload-photos-to-ghost-using-private-api/)

**Comment by vavdagic** [comment]
@ilyaLibin thanks. I did it trough python's requests module "files" parameter.

**Comment by huangyanxiong01** [comment]
@vavdagic can you tell me resolve this problem?
