### ISSUE TITLE
Server error while login over cloudflare ssl

### ISSUE THREAD

**Issue by maharudra108** [TryGhost/Ghost#9467]
I am facing error on login on ghost admin over ssl provided by cloudflare flexible ssl. (Also if i change flexible ssl to full ssl on cloudflare then i can't access my site too. Saying too many redirects only.)

Please help me

**Comment by FrankV01** [comment]
You're probably better off trying to Slack channel for this type of help...

**Comment by maharudra108** [comment]
Well there is no one who reply.. All are dead there.

**Comment by kirrg001** [comment]
Hi @maharudra108 

We're sorry to hear you're having problems, but ask that you do not use our GitHub repo for support. Please read our [support guide](https://github.com/TryGhost/Ghost/blob/master/.github/SUPPORT.md). You can always use our [slack](https://slack.ghost.org/) community - https://slack.ghost.org, if you're not able to find the answer in our [documentation](https://docs.ghost.org/) - https://docs.ghost.org.
