### ISSUE TITLE
Not able to login and Unable to Post Update

### ISSUE THREAD

**Issue by Whizkevina** [TryGhost/Ghost#9469]
Good day, @TryGhost-Travis @TryGhost-Jenkins @Ghost-Slimer,

I created a blog with your app and hosted it with Heroku and Amazon S3 Bucket....
Have update it with like 90 articles, you can check it here (nairasense.investnaira.com) but has not been able to update more content and unable to login into my account, the error i got is "unknown error", I attached the screenshot of me signing to the Admin page.
Thanks for Helping out.
![screencapture-nairasense-investnaira-ghost-1519399135303](https://user-images.githubusercontent.com/15619012/36604603-6ffc0cd0-18be-11e8-8aef-171f95762420.png)

**Comment by kirrg001** [comment]
Hi @Whizkevina 

We're sorry to hear you're having problems, but ask that you do not use our GitHub repo for support. Please read our [support guide](https://github.com/TryGhost/Ghost/blob/master/.github/SUPPORT.md). You can always use our [slack](https://slack.ghost.org/) community - https://slack.ghost.org, if you're not able to find the answer in our [documentation](https://docs.ghost.org/) - https://docs.ghost.org.
