### ISSUE TITLE
Unlink  ../.eslintrc.json permission denied

### ISSUE THREAD

**Issue by alznyc** [TryGhost/Ghost#9470]
### Issue Summary

Recently, after running ghost update after 1.20, the updater will give the following message:

Message: 'EACCES: permission denied, unlink '/var/www/XXXX/versions/1.19.0/.eslintrc.json''

Debug Information:
    OS: Ubuntu, v16.04
    Node Version: v6.9.1
    Ghost-CLI Version: 1.5.2
    Environment: production
    Command: 'ghost update'

However, the actual update completed and everything works fine (the version is correct in ghost admin).  Ghost doctor yields nothing negative. Most likely nothing to worry about, but concerned it may compound into something later?

### Technical details:

* Ghost Version: current
* Browser/OS: Ubuntu 16.04.3 LTS
* Database: MYSQL

**Comment by acburdine** [comment]
Hey @alznyc, this is actually an issue for https://github.com/TryGhost/Ghost-CLI - would you mind reopening this issue there? Thanks 🙂
