### ISSUE TITLE
If night-shift is enabled, checkbox has to be clicked three times to disable

### ISSUE THREAD

**Issue by kevinansfield** [TryGhost/Ghost#9471]
### Issue Summary

If Night Shift is enabled when the admin is loaded then to disable it you need to uncheck the checkbox, then check and uncheck it again before the setting has a visible effect (if you refresh after clicking the first time then you can see it has successfully disabled in the background). 

### Steps to Reproduce

1. Enable night shift mode in labs
2. Refresh the admin app
3. Click the night shift checkbox to disable
4. Note that you still see the night shift styles.
5. Check then uncheck the night shift checkbox
6. Note that the styles have now switched back

The first click to uncheck the night shift checkbox should have a visible effect.

### Technical details:

* Ghost Version: 1.21.3-master
* Browser/OS: Chrome / MacOS

**Comment by hey24sheep** [comment]
Hi @kevinansfield ,
I have fixed this issue in this [PR](https://github.com/TryGhost/Ghost-Admin/pull/965). Kindly, check it and let me know if there is anything. 

Thank You
