### ISSUE TITLE
"Are you sure" modal shown after toggling private mode

### ISSUE THREAD

**Issue by kevinansfield** [TryGhost/Ghost#9472]
### Issue Summary

If you toggle private mode on/off on the general settings screen then try to leave the page you get a warning about not saving changes despite the appearance that you haven't made any changes.

### Steps to Reproduce

1. Open the general settings screen
2. Check the "Make this site private" checkbox
3. Uncheck the "Make this site private" checkbox
4. Try to navigate to a different screen
5. Note that you are shown a warning about unsaved changes

I expect this is because we're detecting the randomly generated password as a change whereas we should be ignoring the password value if private mode is not enabled.

### Technical details:

* Ghost Version: 1 21.3-master
* Browser/OS: Chrome / MacOS

**Comment by hey24sheep** [comment]
Hi @kevinansfield ,
I have created a [PR](https://github.com/TryGhost/Ghost-Admin/pull/964) fixing this issue, Kindly have a look. I don't know a lot about the code structure and I mostly work on Dot net and Angular, so I fixed it in the best possible way I understood the issue. Let me know if there is anything.

Thank You
