### ISSUE TITLE
Preview Theme From Marketplace

### ISSUE THREAD

**Issue by ebauger** [TryGhost/Ghost#9473]
Another feature that will very cool it's to add preview themes like Shopify do.In Shopify, customers can preview the theme and work with it : (add pages, menus and customize the theme). It will be a good feature for Theme Saler and bring big name in the UI/Designer in the Ghost Community.

[See Shopify Themes](https://themes.shopify.com/) : You need a Shopify account to see what I am talking about.

**Comment by kirrg001** [comment]
Hi @ebauger!

Thanks for the idea!

We only keep Github issues open for bugs and in-progress feature work, but always happy to chat about future ideas over on our  [slack](https://slack.ghost.org/) community - https://slack.ghost.org.
