### ISSUE TITLE
Add Ghost To Shopify Apps Marketplace

### ISSUE THREAD

**Issue by ebauger** [TryGhost/Ghost#9474]
Another feature that will be very interesting it's to add Ghost to the Shopify Apps Marketplace. The reason it's the default blog in Shopify it very poor in features and the WYSIWYG it's very immature. I think it's not a big deal to create a bridge between Ghost and [Shopify](https://apps.shopify.com) (and maybe [BigCommerce](https://www.bigcommerce.com/)).

**Comment by kirrg001** [comment]
Hi @ebauger!

Thanks for the idea!

We only keep Github issues open for bugs and in-progress feature work, but always happy to chat about future ideas over on our  [slack](https://slack.ghost.org/) community - https://slack.ghost.org.
