### ISSUE TITLE
Theme upload error message is unreadable in Night Shift

### ISSUE THREAD

**Issue by kevinansfield** [TryGhost/Ghost#9476]
![image](https://user-images.githubusercontent.com/415/36777481-88b6d2a4-1c61-11e8-9ffc-138d42abfecd.png)

**Comment by hey24sheep** [comment]
I have created a here [PR](https://github.com/TryGhost/Ghost-Admin/pull/962) fixing this issue. Kindly check it and let me know if there is anything I need to do. Thanks.
