### ISSUE TITLE
Ghost-Admin - Remove ember-invoke-action

### ISSUE THREAD

**Issue by kevinansfield** [TryGhost/Ghost#9477]
The `ember-invoke-action` package is [no longer maintained](https://github.com/martndemus/ember-invoke-action) so we should look at removing it.

We currently have three different ways of triggering closure actions (thankfully, we _should_ be completely clear of passing action names around now):
1. using [`ember-invoke-action`](https://github.com/TryGhost/Ghost-Admin/blob/master/app/components/gh-cm-editor.js#L55)
2. using `let closureAction = this.get('closureAction')` along with a conditional `if (closureAction) { closureAction(arg); }` (examples [with conditional](https://github.com/TryGhost/Ghost-Admin/blob/master/app/components/gh-image-uploader-with-preview.js), [without conditional](https://github.com/TryGhost/Ghost-Admin/blob/master/app/components/gh-date-time-picker.js#L93))
3. specifying closure actions at the top of components with `myClosureAction() {}` then calling it directly any time we need to with `this.myClosureAction(arg)` ([example](https://github.com/TryGhost/Ghost-Admin/blob/master/lib/koenig-editor/addon/components/koenig-plus-menu.js))

My preference is to standardise on example 3 because it gives a clear indication of the expected closure actions up-front and means that we don't need to put conditionals everywhere as the default behaviour is a no-op unless a closure action was passed in.

**Comment by hey24sheep** [comment]
#9393 Same

**Comment by acburdine** [comment]
Can take care of this one too 😄

**Comment by acburdine** [comment]
@kevinansfield there are a few actions which have hyphenated names that conflict with component event handlers ([example](https://github.com/TryGhost/Ghost-Admin/blob/master/app/components/gh-cm-editor.js#L120)) - how do you think those instances should be handled?
