### ISSUE TITLE
ghost running but don't visit

### ISSUE THREAD

**Issue by callmesoul** [TryGhost/Ghost#9482]
`
0|blog     | [2018-03-02 04:11:38] WARN Theme's file locales/en.json not found. 
0|blog     | [2018-03-02 04:11:39] INFO Ghost is running in development... 
0|blog     | [2018-03-02 04:11:39] INFO Listening on: 127.0.0.1:8080 
0|blog     | [2018-03-02 04:11:39] INFO Url configured as: http://localhost:2368/ 
0|blog     | [2018-03-02 04:11:39] INFO Ctrl+C to shut down 
0|blog     | [2018-03-02 04:11:39] INFO Ghost boot 4.835s
 `
but i don't visit  http://myip:8080
why?

**Comment by AileenCGN** [comment]
Hi @callmesoul 

We're sorry to hear you're having problems, but ask that you do not use our GitHub repo for support. Please read our [support guide](https://github.com/TryGhost/Ghost/blob/master/.github/SUPPORT.md). You can always use our [slack](https://slack.ghost.org/) community - https://slack.ghost.org, if you're not able to find the answer in our [documentation](https://docs.ghost.org/) - https://docs.ghost.org.
