### ISSUE TITLE
Document how to rebuild CSS assets

### ISSUE THREAD

**Issue by dandv** [TryGhost/Ghost#9490]
I've edited my theme's CSS on the sever, but even after `ghost restart`, I don't see the modifications in production. https://themes.ghost.org/docs/structure should document how to force the assets in `built` to be rebuilt, without uploading the theme.

**Comment by kevinansfield** [comment]
@dandv asset building isn't related to Ghost but the theme that you are using. Eg, for Casper the docs are in the [theme readme](https://github.com/TryGhost/Casper).

We don't offer support on GitHub as it's used solely for bug tracking and on-going feature work so I'm closing this issue. If you need any further help please head over to our [Slack team](https://slack.ghost.org) as detailed in the default issue text and our [contributing guide](https://github.com/TryGhost/Ghost/blob/master/.github/CONTRIBUTING.md).
