### ISSUE TITLE
data migration and images are not shown

### ISSUE THREAD

**Issue by lsqswl** [TryGhost/Ghost#9491]
server A's Domin is:     blog.AAAA.com 
server B's Domin is:     www.BBBB.com/blog

when migrate data from A to B, the images are not shown.

Only the old path “/content/images/2018/01/getimgdata.jpeg” is replaced to  "/blog/content/images/2018/01/getimgdata.jpeg", the image is shown.

 How to fix it？Help！

If the server B's domain is modified to "www.BBBB.com", the images are shown normal.

**Comment by kirrg001** [comment]
Hi @lsqswl!

We're sorry to hear you're having problems, but ask that you do not use our GitHub repo for support. Please read our [support guide](https://github.com/TryGhost/Ghost/blob/master/.github/SUPPORT.md). You can always use our [slack](https://slack.ghost.org/) community - https://slack.ghost.org, if you're not able to find the answer in our [documentation](https://docs.ghost.org/) - https://docs.ghost.org.
