### ISSUE TITLE
Bug: Ghost upgrade to 1.21.4 prevented scrolling down to older stories

### ISSUE THREAD

**Issue by ss4344** [TryGhost/Ghost#9493]
### Issue Summary
Upgrade to 1.21.4 (was running 1.21.3) breaks scroll down to older stories in the admin client for me.

### Steps to Reproduce
Was running 1.21.3
...$ ghost update
In admin client: Scrolling fails to load the next set of stories in the list with an endlessly spinning throbber
...$ ghost update --rollback
Everything back to normal in admin on 1.21.3 again
...$ ghost update --force
Back in admin scrolling the story list again fails to load next set of old stories

### Technical details

* Ghost Version: master 1.21.4
* Client OS: Windows 10
* Server OS: Ubuntu 16.04.4 LTS 
* Node Version: v6.13.0
* Browser: Chrome 64.0.3282.186 and Firefox 58.0.1 (64-bit)
* Database: MySQL

**Comment by AileenCGN** [comment]
I am able to reproduce this with current master:

![image](https://user-images.githubusercontent.com/8037602/37268242-79384584-25f7-11e8-8c6b-7cd6362ae700.png)


1.21.3 also works fine for me and doesn't show this issue.
