### ISSUE TITLE
Admin panel not scrollable on iPhone

### ISSUE THREAD

**Issue by andreaswwjd** [TryGhost/Ghost#9494]
### Issue Summary
Issue 1: The admin panel scroll gets locked in x-direction on smaller devices like iPhone SE. 
Issue 2: And also, the scrolling motion is not smooth on iOS Safari which gets really annoying!

### Example
![ghost_admin_scroll_issue](https://user-images.githubusercontent.com/22644456/37236742-15e11634-240b-11e8-8c69-5f13c752af3d.gif) 

### Clues
1. Appears only on smaller devices (320px wide).
2. Does not appear on Safari 11.0.3 macOS when set to emulate Safari iOS 11.0 iPhone SE in developer-mode. 
3. Issue 1 might have to do with long words not wrapping in the post description, or elipsis `...` hanging outside the `.gh-posts-list-item`-element.
4. I have seen issue 2 before, and then it was related to scrolling not set to the body-element and should also be solvable with some css. It first appeared with a iOS update some months ago.

### Possible solutions
```
.gh-posts-list-item {
    word-wrap: break-word;
    overflow-wrap: break-word;
}
```

### Technical details:

* Ghost Version: 1.21.1
* Node Version: 8.9.1
* Browser/OS: Safari iOS 11.2.6 iPhone SE

**Comment by kirrg001** [comment]
@kevinansfield

**Comment by kirrg001** [comment]
@kevinansfield Could you please either label this issue or close? Thanks :)

**Comment by KrisKodira** [comment]
I think this style:
`-webkit-overflow-scrolling: touch;`
on the parent element could fix the problem.

I had a similar problem with a web application once and this is what solved it.
I would be willing to help.
