### ISSUE TITLE
Enable automatic redirects for AMP urls if the AMP is disabled.

### ISSUE THREAD

**Issue by love2dishtech** [TryGhost/Ghost#9495]
### Issue Summary

Disabling AMP feature, does not automatically redirect or serve the existing AMP url's that have been served on various sites like Twitter.

### Steps to Reproduce

1. Enable AMP and share one of the posts on twitter.
2. Disable AMP on Ghost and invoke the URL from twitter post again.

### Technical details:

* Ghost Version: 1.21.3
* Node Version: 6.13.0
* Browser/OS: Chrome
* Database: MySQL.

**Comment by AileenCGN** [comment]
@kirrg001 I think that's something we should look into?

**Comment by kirrg001** [comment]
Sure 👍Help is also very welcome. 

See [this line of code](https://github.com/TryGhost/Ghost/pull/7830/files#diff-43deb5c339ff13d1334eaf46c6e4f446R67).
