### ISSUE TITLE
How can i install Ghost in cPanel?

### ISSUE THREAD

**Issue by Cavain** [TryGhost/Ghost#9498]
Hello,

I wanna install Ghost in my cPanel server. I have full root access and i didn't found any information about Ghost installation in cPanel.

Thanks

**Comment by kirrg001** [comment]
Hi @Cavain!

We're sorry to hear you're having problems, but ask that you do not use our GitHub repo for support. Please read our [support guide](https://github.com/TryGhost/Ghost/blob/master/.github/SUPPORT.md). You can always use our [slack](https://slack.ghost.org/) community - https://slack.ghost.org, if you're not able to find the answer in our [documentation](https://docs.ghost.org/) - https://docs.ghost.org.
