### ISSUE TITLE
Html BR element is doubled on AMP page

### ISSUE THREAD

**Issue by freddy8787** [TryGhost/Ghost#9499]
Html `<br>` element is doubled on AMP page if I using html instead of markdown in CMS. This causing one more new line displayed by browser.

Example:
```
<p class="nice-class">
    some text goes here
    <br>
    another line is here
</p>
```
Ghost creates a HTML which contain `<br></br>` on AMP page. Each browser I tried, displays extra new line (as a space between lines). In specific example when I need paragraph with class, I am using html and need manually add new line. On AMP page Ghost adds 2 new lines instead of 1.

Ghost Version: 1.21.1

**Comment by AileenCGN** [comment]
I can confirm this behaviour. This happens in one of our dependencies (`sanitize-html`) which thinks, that the `<br>` tag needs to be closed and adds a `</br>` to it. But browsers interpret it as two `<br>` tags. Adding `br` to the self closing tags solves this.

**Comment by CriticalRespawn** [comment]
@AileenCGN 

I had a go at this one too - https://github.com/TryGhost/Ghost/pull/9502
