### ISSUE TITLE
SSL Problem

### ISSUE THREAD

**Issue by Cavain** [TryGhost/Ghost#9510]
### Issue Summary

I have been trying to fix SSL issue from last 7 days and i still didn't figured it out how i can fix it. I already found hundreds of articles in Google but all the articles have same information none of article helpful for my solution.

I have been trying to install SSL on my blog where i install Ghost version mentioned below. When i open open website without https it works fine. But when i try to open it in https it shows me error 404 not found.

I tested it in multiple settings to be sure i am not missing anything, So after trying from last few days i am completely tired of this issue.

Nginx Config - Located In / etc/nginx/sites-enabled

` server {
    listen 80;
    server_name example.com;
    return 301 https://example.com$request_uri;
}

server {
    listen 443 ssl http2;
    server_name example.com;

    ssl on;
    ssl_certificate /home/abc/ssl/certs/certs.pem;
    ssl_certificate_key /home/abc/ssl/keys/privatekey.pem;

    if ($http_host = example.com) {
            return 301 https://example.com$request_uri;
    }

    location / {
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-NginX-Proxy true;
            proxy_pass http://127.0.0.1:2375;
            proxy_ssl_session_reuse off;
            proxy_set_header Host $http_host;
            proxy_cache_bypass $http_upgrade;
            proxy_redirect off;
    }
} `

### Config.js Settings
`production: {
        url: 'http://example.com',
        urlSSL: 'https://example.com',
        forceAdminSSL: true,`

I used it without urlSSL as well but it didn't worked. I didn't found any error in while starting production.

I used these Digitalocean settings for without SSL and it worked fine. http://do.co/2pnihtN

I appreciate any helpful information.

Thank you!

### Technical details:

* Ghost Version: 0.11.12
* Node Version: 6x
* Browser/OS: Chrome/Linux Centos7
* Database: Sqlite

**Comment by ErisDS** [comment]
Hi @Cavain 

We're sorry to hear you're having problems, but ask that you do not use our GitHub repo for support. Please read our [support guide](https://github.com/TryGhost/Ghost/blob/master/.github/SUPPORT.md). You can always use our [slack](https://slack.ghost.org/) community - https://slack.ghost.org, if you're not able to find the answer in our [documentation](https://docs.ghost.org/) - https://docs.ghost.org.
