### ISSUE TITLE
Feature request: automatically resize images

### ISSUE THREAD

**Issue by BartWillems** [TryGhost/Ghost#9518]
I would like to be able to set a maximum width for images in blog posts. 
If an image that is bigger than the maximum allowed size is uploaded, ghost could resize it to the maximum width & scale the height automatically.

**Comment by kevinansfield** [comment]
Hey @BartWillems 👋 I've added your request to our internal feature tracker however I'm closing this as a duplicate of https://github.com/TryGhost/Ghost/issues/4453
