### ISSUE TITLE
can't go to /ghost

### ISSUE THREAD

**Issue by mlescaudron** [TryGhost/Ghost#9522]
Hi, 

I don't know why I can't access to http://localhost:2368/ghost/, it's a blank page, my vendors are not loaded... 

### Steps to Reproduce

```
git clone git@github.com:TryGhost/Ghost.git && cd Ghost
yarn global add knex-migrator grunt-cli ember-cli bower
yarn setup
yarn dev
# http://localhost:2368 is working, not  http://localhost:2368/ghost
```

**Comment by kevinansfield** [comment]
@mlescaudron that's not the correct way to install Ghost. Follow the [install docs](https://docs.ghost.org/docs/install) for a production or local theme dev install, or the [contributing guide](https://docs.ghost.org/docs/working-with-ghost) for a core dev install.

If you need support please head over to our [Slack channel](https://slack.ghost.org) - we use GitHub solely for bug tracking and on-going feature work, any issues asking for support/help will be closed.

**Comment by ErisDS** [comment]
Just throwing this out there - I think this is ye olde ember hasn't finished building problem? There's no indication in the CLI that it's still happening & no mention in the docs of the need to wait.
