### ISSUE TITLE
Misspelled schema.org type for WebSite.

### ISSUE THREAD

**Issue by rmuratov** [TryGhost/Ghost#9525]
### Issue Summary

According to http://schema.org/WebSite schema type should be `WebSite` instead of `Website`

Not a big deal, but for example, [Yandex Structured data validator](https://webmaster.yandex.com/tools/microtest/) throws an error:

```
ERROR: https://schema.org/Website type unknown for the specification http://schema.org. Perhaps you meant https://schema.org/WebSite
```

I don't have enough expertise, but I believe it should be changed in these files:

1. https://github.com/TryGhost/Ghost/blob/master/core/server/data/meta/schema.js#L110
2. https://github.com/TryGhost/Ghost/blob/master/core/test/unit/data/meta/schema_spec.js#L359
3. https://github.com/TryGhost/Ghost/blob/master/core/test/unit/helpers/ghost_head_spec.js#L106

### Technical details:

* Ghost Version: Latest
* Node Version: 8
* Browser/OS: Firefox 58/Linux Mint
* Database: MySQL

**Comment by AileenCGN** [comment]
Thanks for the report! 👍

**Comment by CriticalRespawn** [comment]
Just opened a PR with these changes in - https://github.com/TryGhost/Ghost/pull/9526

Also had a look round for any other usages but couldn't find any. Happy to edit my PR if I missed any though!
