### ISSUE TITLE
YAML Settings Beta

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#9528]
In working towards making Ghost more customisable, we want to roll out a new YAML settings feature that will allow more control over how Ghost works.

Ghost will get a new `settings` folder inside the existing `content` folder, so that the settings can live along side other user-provided content. Inside here we will grow a set of files, that will take over from some things that are currently config, some things that are currently settings in the UI, and some brand new customisations.

The `content/settings` folder will be required, as with the themes, images etc folders. Inside it will be the default file for each new file we add, even if this is an empty file with no settings until it is edited.

Inside of Ghost, there will be a copy of the default version of these files, e.g. in `core/settings` or `core/services/settings`. If the files go missing, they will be replaced. At some point we will probably need to offer a mechanism for replacing these files if they get corrupted, e.g. with a Ghost CLI command.

Each file inside the content/settings folder needs to be read, parsed as YAML, and if it's valid, loaded as available settings for the services inside of Ghost.

If the file is not valid YAML, Ghost should not start. There should be an error message which makes it clear which file is not valid, and if possible why, but without any fancy handling. The message should link to documentation, and probably also point to where the default file can be found.

## YAML file behaviour

- The file must always be present in the `content/settings/` folder
- We also keep track of the default template inside of Ghost core e.g. in `core/settings`
- If the file is missing from `content/settings/` we should put the default back in place

**Why behave this way?**

- It should always be clear to the user how Ghost is behaving by viewing the files in `/content/settings/`
- The user should never need to go searching in core to find the defaults, they are for Ghost

**Why YAML?**
It's common amongst similar software. It's better than JSON for humans whilst still easy to read with machines. It's forgiving, it's simple and it's powerful. All the right things.</small>

Outstanding questions:

- Where should the collection of default files live?
- For the behaviour that ensures the `content/settings` folder and the files inside it always exist, what of this behaviour belongs in Ghost vs Ghost CLI?

**Comment by AileenCGN** [comment]
> For the behaviour that ensures the content/settings folder and the files inside it always exist, what of this behaviour belongs in Ghost vs Ghost CLI?

I created a PR that takes care of the folder structure already: https://github.com/TryGhost/Ghost-CLI/pull/681

**Comment by AileenCGN** [comment]
Writing down some notes that I took from a [Slack conversation](https://ghost.slack.com/archives/C02G9E68C/p1522137574000278):

- The YAML settings feature is a settings service
- The YAML settings parser needs to be generic. It will return what it's asked for. This could e. g. look like this: `settings.get('routes')` and then returns the (in this example) `routes` object. It is easily (with just some minor code/config changes) expandable.
- Reading **all** settings files from `content/settings` is probably not necessary, but should be possible to add later.
- The service needs to run in bootstrap as the routes need to be available for the url service. Running the service before the settings cache seems fine.
- If we couldn't read the file in `content/settings`, we log an error, but we fallback to the default.
- If the file does not exist, we have to ensure that it exists.

**Comment by ErisDS** [comment]
> If we couldn't read the file in content/settings, we log an error, but we fallback to the default.

IMO this should be an error, no falling back. 

> If the file does not exist, we have to ensure that it exists.

In this case, we put the default back in place

**Comment by kirrg001** [comment]
> The service needs to run in bootstrap as the routes need to be available for the url service. Running the service before the settings cache seems fine.

Exactly. The `settingsSrvc` will be later triggered during the bootstrap process. e.g. `settingsSrvc.get('routes').then...` - as you already suggested. A post optimisation could be that the service reads the files async as early as possible. And if you ask for the routing object, it's either already available or you have to wait till the service finished.

But as said earlier, the PR won't modify the bootstrap file yet. I'll connect the pieces later together. The goal is to merge a new piece of code, which is 

- not connected, not called in the bootstrap process
- tested
- returns a routing object if you ask for it
- is generic, so we can add more yml files
- handles all the edge cases for the yml routing file

**Comment by AileenCGN** [comment]
> A post optimisation could be that the service reads the files async as early as possible

I think I made it pretty generic, that we would be easily able to write it in a little cache file on bootstrap, which the getter can than read from then when needed. Similar to the settings cache.

Nothing is connected yet, but I wrote tests (even for very very unusual edge cases, like the file not being there). I think the part with the YAML parser is done. I will submit a second PR, that deals with the existence of the settings files.

**Comment by AileenCGN** [comment]
> I will submit a second PR, that deals with the existence of the settings files.

Correction: I put it all in one PR, as it was too much tight into each other. Still generic enough (I hope 🤞 )

**Comment by marcj** [comment]
Is there somewhere a reference/documentation about how the content should look in that file `settings/routes.yaml` and what each setting means? I'm not able to find what the definition of `collections` for example is and how to utilise it.

**Comment by kirrg001** [comment]
We have not announced Dynamic Routing Beta yet. Docs will be published with [Ghost 2.0](https://github.com/TryGhost/Ghost/issues/9742).

**Comment by marcj** [comment]
Mh, but it is already in the code, right? I use `ghost:1.25.3-alpine` and the file `/var/lib/ghost/content/settings/routes.yaml` already exists. When I edit it, it will change the behaviour of the system, even throws errors when I enter crap. Just to understand it completely: `routes.yaml` is already handled, but the usage is not recommended and documented? I'm very new to ghost, so please excuse me for asking a noob question, but is the documentation for v2 in Github as well? Would appreciate a link to the not-yet-published routes.yaml documentation, if available.

**Comment by kirrg001** [comment]
> routes.yaml is already handled, but the usage is not recommended and documented?

Not documented exactly.

**Comment by marcj** [comment]
Ok easy, I found the code https://github.com/TryGhost/Ghost/blob/07c72d735e8326be8aa633239b7fb782dba17ba6/core/server/services/routing/CollectionRouter.js used in https://github.com/TryGhost/Ghost/blob/07c72d735e8326be8aa633239b7fb782dba17ba6/core/server/services/routing/bootstrap.js#L49, which should help me and others to understand what's going on with those settings.
