### ISSUE TITLE
Has helper updates for multi-author

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#9530]
In order to support theming of multi-author, we need to add a couple of new features to our `{{#has}}` helper.

## 1. allow checking the primary_tag/author for a match:

`{{#has primary_tag="news"}}`, `{{#has primary_author="fran"}}`

This should use the same logic as the existing `{{#has [tag/author]=""}}` syntax, which is a hybrid check for slug/name.

## 2. support counting tags/authors:

`{{#has author="count:>1"}}`, `{{#has author="count:<1"}}` `{{#has author="count:1"}}` 
`{{#has tag="count:>1"}}`, `{{#has tag="count:<1"}}` `{{#has tag="count:1"}}` 

This syntax is similar to the `{{#has number="nth:3"}}` syntax and also our filter syntax. It allows the theme developer to compare against the number of tags, and do something different in each case, e.g:

```
{{#has author="count:0"}}
   ... case no author (not supported yet, but will be)
{{else has author="count:1"}}
  ... case exactly 1 author
{{else}}
  ... more than 1 author
{{/has}}
```

For both author & tags, `count:0` should be supported by the has helper.

- [x] add count functionality (https://github.com/TryGhost/Ghost/pull/9426/commits/f479ef942489834720528b6b3d5cc14468ceebf7)
- [ ] add {{#has primary_tag="news"}}

**Comment by kirrg001** [comment]
> {{#has author="count:>1"}}

Isn't it `{{#has authors="count:>1"}}`? 🤔

**Comment by ErisDS** [comment]
No, it is an extension of the existing attribute: https://github.com/TryGhost/Ghost/blob/master/core/server/helpers/has.js#L10

Ref: [Slack convo](https://ghost.slack.com/archives/C02G9E68C/p1521630993000273)
