### ISSUE TITLE
Yandex turbo pages support

### ISSUE THREAD

**Issue by ameshkov** [TryGhost/Ghost#9531]
This is not an issue, but more of a question:)

Yandex has recently added support for so-called "Turbo" pages:
https://yandex.com/support/webmaster/turbo/

The purpose of these pages is the same as of Google AMP, but the implementation is quite different. 

Basically, it is an extension to the RSS 2.0 protocol (unfortunately, it is not backward compatible):
https://yandex.com/support/webmaster/turbo/feed.html

**The question is: do you mind if we create a pull request adding Turbo RSS feed support to Ghost?**

**Comment by kevinansfield** [comment]
Hey @ameshkov 👋 I appreciate that this is something you'd like to make available however we won't be accepting PRs for any specific feed formats. We are currently working on ways to make it possible for blog owners to modify the default RSS feed output and add any other feeds they want via config+theme files, once this lands you'll be able to create a Yandex specific feed for your site.
