### ISSUE TITLE
Dead link on "How to use Ghost" in admin panel

### ISSUE THREAD

**Issue by SixBytesUnder** [TryGhost/Ghost#9536]
### Issue Summary

On a self hosted Ghost I clicked on "How to Use Ghost" link in admin panel, which links to [https://ghosthelp.zendesk.com/hc/en-us/categories/203268947-Ghost-Pro-](https://ghosthelp.zendesk.com/hc/en-us/categories/203268947-Ghost-Pro-) but it results in "Oops! This help centre no longer exists" error page on Zendesk.
Even [https://ghosthelp.zendesk.com](https://ghosthelp.zendesk.com) result in the same "oops" page.

### Steps to Reproduce

1. Log in to admin panel.
2. Click the down arrow in top left corner of the screen, next to your blog name.
3. Click "How to Use Ghost" link.

Not sure if this is something specific to my installation or it came with an update. Maybe the link is correct, but the page on Zendesk was moved or disabled.

### Technical details:

* Ghost Version: 1.21.7 (self hosted)
* Node Version: v6.12.3
* Browser/OS: Google Chrome / Windows 10
* Database: mysql

**Comment by kevinansfield** [comment]
👍 Thanks @SixBytesUnder, fixed link will be available in the 1.22.0 release shortly
