### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by Cavain** [TryGhost/Ghost#9538]
Hello,

First of all thank you for this incredible blogging platform. I am fall in love with ghost, since i started using it its easy and lot better then WordPress. I have been facing one issue their is no images management menu like WordPress has Media when we click on it we can see our images which we uploaded. So, for example if i wanted to publish same post multiple time with different dates in title so i should upload same image multiple time because i don't have link for my previous image.
That would be great if you add this media managing feature so we can check our old uploaded images instead of going all the time in directory to look or take their links.

Thank you.

**Comment by kevinansfield** [comment]
Hey @Cavain 👋 A media library is on our internal feature tracking board although not yet on our development roadmap. I've added an extra vote for the feature for you 😄
