### ISSUE TITLE
can't type in 'k' in editor

### ISSUE THREAD

**Issue by AdairStone** [TryGhost/Ghost#9543]
In both Desktop Client editor and chrome editor , can't type in 'k' with keyboard. little k not work.

Environment:
version: 1.22.1
os-version: 10.13.3 (17D102)

**Comment by AileenCGN** [comment]
I am not able to reproduce this on my Mac. Neither in the browser nor in the Desktop client. Are you getting any error message?

**Comment by AdairStone** [comment]
Sorry for that, this just happened in ghost version 1.22.0
I login in client desktop after my server upgrade and I dit not relogin the system from client desktop and after that, I didn't test it in Chrome browser in version 1.22.1.

After I upgrade my ghost version to 1.22.1 , everything ok.

**Comment by kevinansfield** [comment]
This probably needs more testing, it’s likely that shortcut keys are not being released properly in one area so there will be a multi-step reproduction case which is why appeared to come and go. Re-opening to remind me to check.

**Comment by CriticalRespawn** [comment]
Just jumping in here to say I can replicate this issue, I can leave my version running 1.22.0 if needed for the time being. Interestingly, I cannot replicate this on my local version running 1.22.0, only on one of my remote setups.

Upon further testing, this is also breaking the `j` character. In my browser console, I get the following errors:

For `j`:
>r {stack: "Error: Nothing handled the action 'moveDown'. If y….min-4758f86ab1e40db6daf7ff7935a6dcb9.js:2441:13)", description: undefined, fileName: undefined, lineNumber: undefined, message: "Nothing handled the action 'moveDown'. If you did …er in a controller, causing the action to bubble.", …}

For `k`:
>Uncaught r {stack: "Error: Nothing handled the action 'moveUp'. If you….min-4758f86ab1e40db6daf7ff7935a6dcb9.js:2441:13)", description: undefined, fileName: undefined, lineNumber: undefined, message: "Nothing handled the action 'moveUp'. If you did ha…er in a controller, causing the action to bubble.", …}

The only bit of related code I could find, is the below block which is in `app/routes/settings/tags.js`:

```
    init() {
        this._super(...arguments);
        this.shortcuts = {
            'up, k': 'moveUp',
            'down, j': 'moveDown',
            left: 'focusList',
            right: 'focusContent',
            c: 'newTag'
        };
    },
```

Hope this helps!

**Comment by kevinansfield** [comment]
@CriticalRespawn thanks for the investigation, my guess was that it was the Tags route not resetting the `keymaster` shortcuts as we'd seen similar reports of `moveUp`/`moveDown` errors on the Stories screen.

First thought is that this was introduced in https://github.com/TryGhost/Ghost-Admin/pull/976. Fix is planned for next Monday ready for Tuesday's release.

**Comment by rndm-stranger** [comment]
@kevinansfield Thanks for the info.

**Comment by kevinansfield** [comment]
For anyone experiencing this, if you refresh the admin page the problem will disappear until you next visit the Tags screen.

**Comment by L2Program** [comment]
@kevinansfield Thanks for the work around in the meantime.
