### ISSUE TITLE
Import content failed - Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by MichaelCaraccio** [TryGhost/Ghost#9547]
### Issue Summary

Content exportation from my server worked. But when I imported the JSON file on my computer, the following error appears.

<img width="1086" alt="screen shot 2018-04-04 at 23 15 15" src="https://user-images.githubusercontent.com/7326386/38335298-2911d3e4-385e-11e8-93ca-6886ca6b1396.png">

### Technical details:

**Dev configuration (my computer) :** 
* Ghost Version: **1.22.1**
* Node Version: 8.9.0
* Environment development

**Prod configuration (my server with Docker) :** 
* Ghost Version : **1.22.1**
* Node Version : 6-slim (image)
* Environment production

**Comment by kirrg001** [comment]
@MichaelCaraccio Hey!

Can you please share either the file to import or the exact error message from the server?
Thanks!

**Comment by MichaelCaraccio** [comment]
Hello! The error from the server is the following : 

<img width="1242" alt="screen shot 2018-04-05 at 00 08 05" src="https://user-images.githubusercontent.com/7326386/38337438-84832820-3865-11e8-9c7f-de5c2b654c81.png">

**Comment by kirrg001** [comment]
@MichaelCaraccio Is it possible to share this file with me?
I'll treat it with respect and i'll remove it afterwards. Because i can't see where the error starts. It would take me longer to figure it out without the file.

You can send it to kate@ghost.org.

**Comment by kirrg001** [comment]
@MichaelCaraccio The file you've send me, imports fine for me. No error?
Did you use the CLI to install Ghost?

**Comment by ubuntutest** [comment]
Hi, I have the same problem.
I have exported my content from the blog in production.

I installed a new blog locally on windows with **ghost install local**
I first deleted all the default contents with the **Delete all content*" button
So I tried to import the json, I get this error:

```
Import failed
Can not read property 'id' of undefined
```


Before installing a clean version of local ghost I tried to update the old version I already had to run tests. **ghost update** did not work.
Here you can find the log:
https://pastebin.com/HDkti8bJ

**Comment by kirrg001** [comment]
@ubuntutest Thanks for sharing. Is it possible to share your file with me? kate@ghost.org.

> Before installing a clean version of local ghost I tried to update the old version I already had to run tests. ghost update did not work.
Here you can find the log:
https://pastebin.com/HDkti8bJ

This was already reported in https://github.com/TryGhost/Ghost/issues/9539, also on Windows.

@MichaelCaraccio You are not on Windows right?

**Comment by MichaelCaraccio** [comment]
@kirrg001 

I installed my dev local version with CLI : 
 $ ghost install local

Then I think that I "delete all content" before to import my data.

**Comment by kirrg001** [comment]
@MichaelCaraccio Is your dev local on Windows?

**Comment by MichaelCaraccio** [comment]
@kirrg001 dev local on MacOS (10.13.4)

**Comment by kirrg001** [comment]
@MichaelCaraccio @ubuntutest 

I am unable to reproduce 😩
Are you able to reproduce this problem all the time?

If yes, can you please share detailed steps with as many information as possible. That would help us a lot!!!

**Comment by ubuntutest** [comment]
I was able to replicate the problem after many test installations.

Windows 10 (but I think it is indifferent) -> ghost install local ->localhost:2368/ghost/ create the admin account exactly with the same information of the account in the json that you're going to import, including the same password -> labs -> delete all contents -> import json -> error

**Comment by MichaelCaraccio** [comment]
@kirrg001 Hello! 

I updated npm from version 5.5.1 to 5.8.0. I reproduced the steps (ghost install local, delete all content, import content) and the problem occurred again. I did a "ghost stop" but it seems that a process on port 2368 was still running. So I killed it, redo all the steps and then I could import the file without any problem! No more problem.

It rollback to npm version 5.5.1 to be sure that the problem did not come from npm. And it worked! No more problem.

 I can't give you more information. I think we can close the issue.

**Comment by MichaelCaraccio** [comment]
@kirrg001 I think @ubuntutest is right. It's all about the information you give when you create the website for the first time.

If I fill the form with the same "Full name" as the JSON file, it will fail. Same email seems to work without any problem.

**Comment by kirrg001** [comment]
@MichaelCaraccio @ubuntutest Thank you so much. I was able to track this down 👻

**Comment by kirrg001** [comment]
@ubuntutest 

I am still not sure why you were running into

> RollbackError: delete from `posts_authors` - SQLITE_ERROR: no such table: posts_authors

Ghost `1.22` contains two migration scripts. One to add the new multiple authors table (`posts_authors`) and one to update all the posts. And this looks like the table was never created.
Maybe the migration tasks are read from disk in different order? 🤔I can't really help with Windows, because i have not set up a VM and i currently don't have time for that 😖But if you figure out anything, let me know :)

**Comment by ErisDS** [comment]
@kirrg001 wouldn't it make sense to at least number these files correctly? https://github.com/TryGhost/Ghost/tree/master/core/server/data/migrations/versions/1.22

**Comment by kirrg001** [comment]
@ErisDS Yeah we could do that, but then we also need to migrate existing databases, because some of the them will hold the old filename and some the new file name. I think trying to keep consistency with the migrations table is very important.

But to be honest, i wanted to reproduce the problem first before doing anything. 

It would be better if we could identify the files based on a unique id instead of the file names.
