### ISSUE TITLE
`user.activated.edited` event triggered on post update

### ISSUE THREAD

**Issue by kirrg001** [TryGhost/Ghost#9548]
### Issue Summary

`user.activated.edited` event triggered on post update.
This is wrong. Should only be triggered if the author changes.

### Steps to Reproduce

1. Add a console.log in the user model (emitEvent)
2. Save any post.
3. You will see that `user.activated.edited` got triggered.

I assume that relations are detected (`post.authors`) and the author is changed without reasons.
Probably a bug in bookshelf-relations. I guess introduced in multiple authors.

### Technical details:

* Ghost Version: master
* Node Version: any
* Browser/OS: any
* Database: any

**Comment by kirrg001** [comment]
> { id: '1',
  slug: 'katharina',
  visibility: 'public',
  updated_at: 2018-04-03T07:06:05.000Z,
  created_at: 2018-04-03T07:03:37.000Z }

> { id: '1',
  slug: 'katharina',
  visibility: 'public',
  updated_at: '2018-04-03T07:06:05.000Z',
  created_at: '2018-04-03T07:03:37.000Z' }

Somehow the date is not a string. I know that bookshelf did updates for `updated_at` + `created_at` in the last release. Not sure it's related.

**Comment by kirrg001** [comment]
Same behaviour for tags.

**Comment by kevinansfield** [comment]
Hmm, I wasn't aware of it doing this before, maybe a dependency update changed the behaviour 🤔 Will it be best to not send those attributes to the server at all? They should only be updated by the server after all

**Comment by kirrg001** [comment]
> They should only be updated by the server after all

The server has a protection against this.

But yeah sure, `updated_by` and `created_by` can be removed from being sent to the server.

**Comment by kirrg001** [comment]
> The server should actually throw an error if somebody tries to send a different data type, but it doesn't currently. Will add. We can't/shoulnd't do convertion, it's only an edge case for id 1.

This is a bigger underlying problem, will be solved in https://github.com/TryGhost/Ghost/issues/9299#issuecomment-379001882.
