### ISSUE TITLE
Share new posts from Ghost to Buffer using Zapier

### ISSUE THREAD

**Issue by Luen** [TryGhost/Ghost#9551]
### Issue Summary

The Zapier Zap is being triggered every time you edit and update an old post. 
Ghost Trigger: 
- New Story - Triggered when a new story is added.
- Status (Which status this should trigger on): published

### Steps to Reproduce

1. Link Ghost with Zapier
2. Create Zap with trigger when a new story is added (status = published) and turn on zap
3. Edit old posts and wait 15min
4. Zap will then push recently edited but previously published stories to Buffer

This should only be triggered when a draft is published - not when editing already published content. 

### Technical details:

* Ghost Version: 1.22.1
* Node Version: 8.9.4
* Browser: Chrome 65.0.3325.181
* OS environment: Ubuntu 16.04 LTS
* Database: Default MySQL

**Comment by kevinansfield** [comment]
Thanks for the report @Luen 👍 I'll investigate this and fix if I can reproduce on Monday

**Comment by kevinansfield** [comment]
Thinking about this a little more, Ghost doesn't trigger any events for new stories. The way the "New story" trigger works is that we tell Zapier how to fetch the posts list via the API, it's then up to Zapier and their [deduplication](https://zapier.com/developer/documentation/v2/deduplication/) to only trigger zaps when necessary.

It sounds like Zapier's own functionality has failed to cache the post IDs properly and so re-triggered an event for the same post 🤔

@Luen is this consistently reproducible for you?

**Comment by Luen** [comment]
I've tested it a little bit more and it seems to not be behaviouring the same way as it was before. Now there's no duplicate being created when editing already published posts. Great!
