### ISSUE TITLE
Meta Descriptions shown Post Excerpt

### ISSUE THREAD

**Issue by mskian** [TryGhost/Ghost#9553]
Hey,

I adding Post Excerpt & Custom Meta Description for My Blog Post
But Post Excerpt is Shown on all  Facebook, Twitter, Schema Markup meta tags
if I remove Post Excerpt It shown My Custom Meta Description

**Comment by AileenCGN** [comment]
Hi @mskian 

This is desired behaviour and not a bug. The order for the description is

1. dedicated description for each twitter and facebook
2. custom post excerpt
3. meta data description
4. fallback post excerpt

We're sorry to hear you're having problems, but ask that you do not use our GitHub repo for support. Please read our [support guide](https://github.com/TryGhost/Ghost/blob/master/.github/SUPPORT.md). You can always use our [forum](https://forum.ghost.org/) - https://forum.ghost.org, if you're not able to find the answer in our [documentation](https://docs.ghost.org/) - https://docs.ghost.org.
