### ISSUE TITLE
iOS Safari on-screen keyboard covers editor text

### ISSUE THREAD

**Issue by dzaikos** [TryGhost/Ghost#9560]
### Issue Summary

When entering text in the editor on an iPad (tested on 12.9" and 9.7" without content blockers) if the post contains text that spans more than half the screen height the on-screen keyboard covers the text and it is not possible to scroll the text further up the screen. Only the last half-screen of text is hidden, but it makes it impossible to accurately edit text, move the cursor, or see what one's typing.

### Steps to Reproduce

1. Start a new article.
2. Type 1.5-2.0 pages worth of content.
3. Observe how the end of the post is not visible when the on-screen keyboard is active.

### Expected Behavior

The editor window should allow the text area to be scrolled up so the hidden content is visible. When using an external keyboard this is not an issue at all, but the on-screen keyboard makes writing pretty difficult. As a workaround one can add half a page of blank lines to the end of the post so the actual content becomes visible but there really should be some type of padding at the bottom so this workaround isn't necessary.

### Technical details:

* Ghost Version: 1.22.1
* Node Version: 6.13.1
* Browser/OS: Safari/iOS 11.3
* Database: MySQL 5.7.21 (Ubuntu 16.04)

**Comment by AileenCGN** [comment]
@kevinansfield ping

**Comment by nathfreder** [comment]
This seems to be a Safari related issue, as this happened to me everywhere on iOS 12.

**Comment by nathfreder** [comment]
I think that this issue is due to a change in the operating system; after doing some research I concluded that [this may be the solution](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoViewIfNeeded) to our issues. I am a new user of Ghost and would be happy to make a pull request if this works.

**Comment by dzaikos** [comment]
Well definitely an iOS Safari issue, but I'm not sure `scrollIntoViewIfNeeded()` would work because **I** cannot even manually scroll the text into view. So I'm sure this would trigger a scroll but it probably still wouldn't be able to bring the text into view because there's no space below the editor.

I know @kevinansfield has said that [mobile browsers are not supported](https://forum.ghost.org/t/koenig-editor-beta-release/1284) so I can't imagine this is a high priority. Nonetheless, I'm pretty much iPad-only these days and I love Ghost so I do wish the editor were more reliable.

You could always try a patch in your local environment and post back if it works.

**Comment by kirrg001** [comment]
@kevinansfield Could you please either label this issue or close? Thanks :)

**Comment by kirrg001** [comment]
@kevinansfield ping

**Comment by kevinansfield** [comment]
Mobile browsers are not currently supported so I'll close this for now. That said, we're always open to PRs for this type of issue.
