### ISSUE TITLE
Admin in another language

### ISSUE THREAD

**Issue by juandosimple** [TryGhost/Ghost#9562]
I wanted to know if there's a plan to work this out. I found some issues that talk about it but nothing clear.

Thanks!

**Comment by AileenCGN** [comment]
Hi @juandosimple 

We ask that you do not use our GitHub repo for support or questions. Please read our [support guide](https://github.com/TryGhost/Ghost/blob/master/.github/SUPPORT.md). You can always use our [forum](https://forum.ghost.org/) - https://forum.ghost.org, if you're not able to find the answer in our [documentation](https://docs.ghost.org/) - https://docs.ghost.org.
