### ISSUE TITLE
SUGGESTION: Include picture’s path in the backup.json under General tab

### ISSUE THREAD

**Issue by pascalandy** [TryGhost/Ghost#9564]
Hi @kirrg001 

You previously helped me via Slack regarding a glitch I found when we do import/export the `backup.json` file for our content. I found something else. 

Under general setting, there are 3 pictures and their paths are not part of the `backup.json` file. As I manage a lot of ghost instances, I would like to suggest this user story to make my life easier.

**USER STORY** - As a user when I export/import my `backup.json` file, I want the system to include the path of the pictures in the general tab.

That would save me a lot of time as I set up many blogs from existing configurations/assets.

Thanks in advance!
Pascal

P.S. Let me know if I should use the new forum instead. 

![screen shot 2018-04-11 at 5 05 45 pm](https://user-images.githubusercontent.com/6694151/38643725-2209e87c-3dac-11e8-8f5c-bff4ee09a222.jpg)

**Comment by kirrg001** [comment]
@pascalandy Hey, Hey!

So, if you create a backup or an export of your blog's content, your blog settings will be included in the JSON file.

If you then import this JSON file into a new/fresh blog instance **and the images** are available in your content folder, everything should work fine. Ghost imports your settings.

> P.S. Let me know if I should use the new forum instead.

Yeah this would makes sense 👍 And, please share your Ghost version! Thanks 🤠

**Comment by kirrg001** [comment]
> I did that but it's breaking and I have to re-upload the pictures.

So you can either put the images into the file to import (a zip file containing the images and the JSON) or you have to upload the images manually to your server again.

First option works already with Ghost.
