### ISSUE TITLE
Bug: Casper 2.2.0 post preview 500 error ([post.hbs] Cannot read property 'length' of undefined)

### ISSUE THREAD

**Issue by ss4344** [TryGhost/Ghost#9567]
### Issue Summary
Upgrading to Ghost 1.22.2 works fine with my old Casper-based theme. But when I replace that modified theme (based on casper 2.1.9) with the new Casper 2.2.0 default theme it breaks post preview in Ghost editor, returning http 500 [post.hbs] Cannot read property 'length' of undefined.

"Page" preview does not seem to be impacted, just "Post".

### Steps to Reproduce
Upgrade to Ghost latest and use Casper 2.2.0.

### Technical details

* Ghost Version: master - latest commit:  1.22.2
* Server OS: Ubuntu 16.4 LTS
* Node Version: v6.14.1
* Browser: Chrome, also breaks with Firefox
* Database: MySQL

**Comment by kirrg001** [comment]
Thanks for the report 👍 

Fix will be released on Tuesday.

**Comment by kirrg001** [comment]
Fixed via https://github.com/TryGhost/Ghost/commit/5d21ce0644475bfd2e62e0f91d3490ab91034443
