### ISSUE TITLE
Update Reading time helper

### ISSUE THREAD

**Issue by JohnONolan** [TryGhost/Ghost#9569]
![image](https://user-images.githubusercontent.com/120485/38807053-93bee454-417b-11e8-967a-6336dbd83dcf.png)

We don't really want to distinguish between posts which take 1 minute to read and posts which take less than 1 minute to read. The minimum reading time for a post should simply be 1 minute.

https://github.com/TryGhost/Ghost/blob/master/core/server/helpers/reading_time.js

This needs a very small refactor to make that change.

**Comment by rkalis** [comment]
I've implemented some stuff for the reading time helper before, I'll pick this up tonight.

**Comment by rkalis** [comment]
We currently have the following usage for reading time i18n:
```
{{reading_time seconds=(t "< 1 min read") minute=(t "1 min read") minutes=(t "% min read")}}
```

If we make the min read time 1 minute, the seconds option becomes obsolete. I would say we still want to differentiate between singular and plural minutes for i18n, do we want to keep their names as 'minute' and 'minutes' or rename them to something like 'singular' and 'plural'? I'm guessing for backwards compatibility it's better to leave the names as-is, but do we just altogether remove the 'seconds' option?

**Comment by AileenCGN** [comment]
> but do we just altogether remove the 'seconds' option?

Exactly my question as well.
cc @kirrg001

**Comment by kirrg001** [comment]
> I'm guessing for backwards compatibility it's better to leave the names as-is

Yeah please keep naming as is. We don't want to break themes.

> but do we just altogether remove the 'seconds' option?

Yeah. It only changes a tiny detail of the reading time helper's output - probably comparable to what we did with the meta title in the past, [see](https://github.com/TryGhost/Ghost/commit/0b5de149009fc1ced6b8e6b07a1999e074788325). People can still pass `seconds`, but it won't modify the output anymore.

We should shout on https://themes.ghost.org, so people can update their theme locales.

**Comment by AileenCGN** [comment]
@kirrg001 The docs on https://themes.ghost.org are updated, we just need to remember to add a shout out on the changelog for the next release!
