### ISSUE TITLE
Is there anyway to separate the static files domain from the html?

### ISSUE THREAD

**Issue by jaggerwang** [TryGhost/Ghost#9576]
### Issue Summary

I'd like to provide the static files (like js, css and images) by domain A, and provide the html by domain B. Domain A is a CDN domain, so the static files will be cached and speed up. I don't see any config about this.

### Technical details:

* Ghost Version: 1.21
* Node Version: 9.0
* Browser/OS: Chrome
* Database: SQLite

**Comment by AileenCGN** [comment]
Hi @jaggerwang 

We're sorry to hear you're having problems, but ask that you do not use our GitHub repo for support. Please read our [support guide](https://github.com/TryGhost/Ghost/blob/master/.github/SUPPORT.md). You can always use our [forum](https://forum.ghost.org/) - https://forum.ghost.org, if you're not able to find the answer in our [documentation](https://docs.ghost.org/) - https://docs.ghost.org.
