### ISSUE TITLE
private blogging: 404 on short urls

### ISSUE THREAD

**Issue by kirrg001** [TryGhost/Ghost#9578]
### Issue Summary

Ghost returns a 404 for short urls if private blogging is enabled.
Was raised in the forum: https://forum.ghost.org/t/short-url-s-returning-404/911/3

### Steps to Reproduce

1. Enabled private blogging.
2. Publish a post with e.g. 2 characters
3. Serve the post
4. 404

### Technical details:

* Ghost Version: latest
* Node Version: any
* Browser/OS: any
* Database: any

I have not investigated. We appreciate any help 🤠

**Comment by Tiendq** [comment]
I could reproduce it, it's likely still untouched so I'd like to try this one :)

**Comment by Tiendq** [comment]
@kevinansfield can you review my PR? Thanks.

**Comment by kirrg001** [comment]
@Tiendq I'll take a look asap. Thanks for your time!
