### ISSUE TITLE
ghost requesting unsafe http url via ajax causing the browser to block request

### ISSUE THREAD

**Issue by tamodocsapp** [TryGhost/Ghost#9579]
### Issue Summary

I have setup a ghost blog for my company. I have hosted the ghost application in an Amazon EC2 instance(infact 2 instances in 2 regions) and attached it with a ELB load balancer of classic type for load balancing requirements. Both http and https requests to the domain is being forwarded as a http request to the EC2 instance along with X-Forwarded Headers which is being consumed by nginx and being forwarded properly to the ghost application. This is my nginx conf

`

    server {
        listen 80;
        listen [::]:80;

        server_name blogtest.example.com;

        if ($http_x_forwarded_proto = 'http') {
             return 302 https://$server_name$request_uri;
        }

        root /var/www/ghost/system/nginx-root;

        location / {
            proxy_cache ghostcache;
            proxy_cache_valid 60m;
            proxy_cache_valid 404 1m;
            proxy_ignore_headers Set-Cookie;
            proxy_hide_header Set-Cookie;
            proxy_cache_use_stale error timeout invalid_header updating http_500 http_502 http_503 http_504;
            proxy_ignore_headers Cache-Control;
            add_header X-Cache-Status $upstream_cache_status;

            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto https;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header Host $http_host;
            proxy_buffering off;
            proxy_pass http://127.0.0.1:2369;

        }

        location ^~ /assets/ {
            root /var/www/ghost/content/themes/simply;
        }

        location ^~ /content/images/ {
            root /var/www/ghost;
        }

        location ~ /.well-known {
            allow all;
        } 
          
        location ^~ /ghost/ {
            proxy_set_header Host $http_host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto https;
            proxy_buffering off;
            proxy_pass http://localhost:2369;
        }

        client_max_body_size 50m;
    } 

`
Please ignore top parts and proxy_cache settings. They are for nginx caching of pages and auto-redirect from http to https.
Now the problem that is coming is that ghost is trying to call a http api in browser and browser is throwing an error(Mixed Content).

Question :- How to tell ghost via headers to make all api calls and other asset calls via https.

### Technical details:

* Ghost Version: latest
* Node Version: 8.11.1
* Browser/OS: chrome/safari/etc which blocks mixed content
* Database: MySQL

**Comment by kevinansfield** [comment]
Hey @tamodocsapp 👋 

> I have hosted the ghost application in an Amazon EC2 instance(infact 2 instances in 2 regions) and attached it with a ELB load balancer of classic type for load balancing requirements

First, this won't work, please see the warning about docker/node and other clustering setups here https://docs.ghost.org/docs/install

Second, if you want Ghost to use `https` urls then you need to configure a `https` URL via the [config](https://docs.ghost.org/docs/config#section-url).

Closing this issue because it's for installation support and we do not offer any form of help/support on Github, we use Github solely for bug tracking and on-going feature work. If you need further help please swing by our [forum](https://forum.ghost.org) where you can get community support.
