### ISSUE TITLE
Malformed markup on team page

### ISSUE THREAD

**Issue by JohnONolan** [TryGhost/Ghost#9581]
Noticed this very large gap between active users and suspended users

![image](https://user-images.githubusercontent.com/120485/38870402-fbaeca3e-424d-11e8-9a22-30ff72c90223.png)

The markup seems to be pretty wrong

![image](https://user-images.githubusercontent.com/120485/38870430-14ee1180-424e-11e8-82fb-948828f7a385.png)

- Not in the correct place, should be inside .gh-team
- Absolutely shouldn't be .apps-grid-container / apps-grid-title / apps-grid ....
- Definitely shouldn't be .gh-active users 
- All the user images are broken...

Needs a little tidying

**Comment by IceDune** [comment]
@JohnONolan , can i take this issue?

**Comment by kirrg001** [comment]
@IceDune Somebody PR'd this already, [see](https://github.com/TryGhost/Ghost-Admin/pull/1007).

**Comment by IceDune** [comment]
oh okay.

**Comment by JohnONolan** [comment]
That PR has been stagnant for 2 months though - so if you want to refresh it or do a new version then feel free

**Comment by isaac-philip** [comment]
Should this issue be closed ?

**Comment by m1guelpf** [comment]
@JohnONolan Now that https://github.com/tomkr/Ghost-Admin/commit/167636587a216b14cba14ba5bc38e11ac610638c was pulled in, can we close this?
