### ISSUE TITLE
Broken loading state in editor

### ISSUE THREAD

**Issue by JohnONolan** [TryGhost/Ghost#9582]
![image](https://user-images.githubusercontent.com/120485/38871988-7ca1e5e6-4252-11e8-9370-9ac1f02dfd31.png)

Ghost 1.21.6

- Open Editor to edit a post
- Use search box to find a different post
- Click on it
- Loading state breaks layout

**Comment by evexoio** [comment]
@JohnONolan removing `app/templates/editor/edit-loading.hbs` from Ghost-Admin fixed it,

will create a PR ASAP
