### ISSUE TITLE
Importer warns about "not able to resolve the following user" for all owner references

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#9584]
When exporting and importing into Ghost 1.0, the importer outputs tonnes of warnings along the lines of 

> Subscriber: Entry was imported, but we were not able to resolve the following user references: created_by, updated_by. The user does not exist, fallback to owner user.

> Post: Entry was imported, but we were not able to resolve the following user references: published_by. The user does not exist, fallback to owner user.

I see these warnings for created_at, updated_at and published_at on the post model, but not the author_id.

### Steps to Reproduce

1. Export any 1.0 blog, e.g. blog.ghost.org
2. Import the content into a new location

According to #9299, the Owner is always user ID 1 (except for if the [ownership was transferred!](TryGhost/Ghost#9583)). 

The owner user is **always** present in the import file. It is present when testing this.

It makes no sense to me that the id can't be resolved?

### Technical details:

* Ghost Version: 1.22.2
* Node Version: 8
* Database: Sqlite3 & MySQL

**Comment by kirrg001** [comment]
> Post: Entry was imported, but we were not able to resolve the following user references: published_by. The user does not exist, fallback to owner user.

So the post is a draft. And the importer just checks if if any user reference is null. It does not differentiate if a post is draft. Confusing, i agree. We should add exceptions for the post being a draft. I would say low priority.

> Subscriber: Entry was imported, but we were not able to resolve the following user references: created_by, updated_by. The user does not exist, fallback to owner user.

This is a bug in our models layer. The base model auto fills `created_by` and `updated_by`, but if you subscribe on your blog frontend, the context user is external. But it falls back in [here](https://github.com/TryGhost/Ghost/blob/master/core/server/models/base/index.js#L395) too early. This results in user references being the resource id. The importer works correct, it can't resolve the user references. As far as i can see, only the subscribers app makes use of the external context.

I will push a quick fix on Monday. Good catch 👍 

Note: external access currently uses `id:0`, but 0 is not a valid ObjectID. This is also needs cleanup part of #9299. We should probably get rid of this concept for now.

**Comment by dnguneratne** [comment]
I'd like to work on this. Any tips on where to get started?

**Comment by kirrg001** [comment]
@dnguneratne 

> Post: Entry was imported, but we were not able to resolve the following user references: published_by. The user does not exist, fallback to owner user.
> So the post is a draft. And the importer just checks if any user reference is null. It does not differentiate if a post is draft. Confusing, i agree. We should add exceptions for the post being a draft. I would say low priority.

This is a good small use case to start with.
You can easily reproduce this, if you

1. Create a draft post
2. Export your database in labs
3. Delete all your content
4. Import the file
5. You should see the warning from above. But it should not throw a warning, because `published_by` is null.

The importer should  not try to resolve `published_by` in this case.

**Comment by kirrg001** [comment]
> This is a bug in our models layer. The base model auto fills created_by and updated_by, but if you subscribe on your blog frontend, the context user is external. But it falls back in here too early. This results in user references being the resource id. The importer works correct, it can't resolve the user references. As far as i can see, only the subscribers app makes use of the external context.

This is not resolved yet.

**Comment by ErisDS** [comment]
This is going to be worked on shortly
