### ISSUE TITLE
ES6 migrations

### ISSUE THREAD

**Issue by vikaspotluri123** [TryGhost/Ghost#9589]
This is something ~I plan on working on in the middle of May~ a bunch of people are helping out on! 😄 

- `var` -> `let` / `const`
- `_.includes(array)` -> `array.includes` (dropping v4 support at the end of April makes this possible)
- `_.each(array)` -> array.forEach
- `_.isArray(array)` -> `Array.isArray(array)` - Only if it removes the necessity of requiring lodash in a specific file
- `_.isEmpty(array)` -> `array.length === 0` (or `!array.length`)
- Remove other lodash dependencies as needed on a file-specific basis (the goal isn't to purge lodash, it's to reduce unnecessary requires of the large library)
  -  In that note, use [Object destructuring](http://es6-features.org/#ObjectMatchingShorthandNotation) to import required components as needed
  - Use [you might not need lodash](https://github.com/you-dont-need/You-Dont-Need-Lodash-Underscore) but don't go overboard
- remove usage of `var self = this` (arrow functions instead)
- Use defaults (I'm not sure if this is applicable) (i.e. `(a = 2, b = 2) => a + b`)
- Use template literals when possible

---

Checklist:

 - [ ] Arrow functions do not replace named functions
 - [ ] var -> const / let
 - [ ] Array.(includes / each / isEmpty / isArray) lodash usage minimized
 - [ ] Template literals
 - [ ] Import specific lodash modules instead of entire library

**Comment by karaggeorge** [comment]
Hello, I'd like to try this. I'm really comfortable with es6 syntax and I think I could use this to get more familiar with the code base. 

Could you please help me with what you are looking for exactly?
- Should the entire project be migrated? Or just a specific part (server?).
- Is babel used? or should only syntax that is available in the current Node version be migrated?

**Comment by vikaspotluri123** [comment]
Hey @karaggeorge 👋 I was planning on migrating the entire Ghost repo (so specifically [TryGhost/Ghost](/TryGhost/Ghost)) after I get done with my semester, but I'm definitely not opposed to getting help 😉

@kirrg001 how would you suggest multiple people working on the same thing? I was thinking @karaggeorge PRs into my repo and enables `allow edits from maintainers` so I can push commits as well  🤔

**Comment by kirrg001** [comment]
Thanks for interest and help 😎

Multiple people is fine, but please only very small pull requests - 1-2 files per PR. Otherwise this can heavily conflict with existing pull requests and takes too much time to review. It also means, if multiple people would like to help, this needs communication here, who takes over which folder. And please do not rewrite logic, only ES6 style changes 👍

If you want to rewrite logic, please argue in this issue and wait for confirmation. After confirmation, you can submit this rewrite as separate PR.

e.g. changing `_.includes(array) -> array.includes` is absolutely fine and does not need confirmation

e.g. rewriting a whole function needs confirmation

---

Please do after we've dropped Node v4 🙌🏻

> Should the entire project be migrated? Or just a specific part (server?).

Only the server and test folder.

> Is babel used?

No

**Comment by karaggeorge** [comment]
@vikaspotluri123 @kirrg001 

> Please do after we've dropped Node v4 🙌🏻

Do you mean, start working on it after Node v4 is deprecated? Or it's ok to create PRs now, but they won't get merged until it's deprecated?

Sounds good. I'm planning on working on it now (in the next few days) so it shouldn't cause conflicts. I'll keep every PR small 1-2 files.

**Comment by vikaspotluri123** [comment]
> Sounds good. I'm planning on working on it now (in the next few days) so it shouldn't cause conflicts. I'll keep every PR small 1-2 files.

This sounds good - can you let me know what folder you plan on migrating first? I know I probably won't have time right now to work on it, but if I somehow find it, I don't want to be stepping on your toes 😃

**Comment by karaggeorge** [comment]
I'll start with `core/server/api/` 😄

**Comment by kirrg001** [comment]
> Do you mean, start working on it after Node v4 is deprecated?

After Ghost has dropped it.

**Comment by vikaspotluri123** [comment]
Checklist:

If anyone knows of a way to make it less obtrusive, that would be great 😏 

 - [ ] adapters
   - [ ] /scheduling
   - [ ] /scheduling/post-scheduling
   - [ ] /storage
 - [ ] api
 - [ ] apps
   - [ ] /amp
   - [ ] /amp/lib/helpers
   - [ ] /amp/lib
   - [ ] /amp/lib/views
   - [ ] /private-blogging
   - [ ] /private-blogging/lib/helpers
   - [ ] /private-blogging/lib
   - [ ] /private-blogging/lib/views
   - [ ] /subscribers
   - [ ] /subscribers/lib/helpers
   - [ ] /subscribers/lib
   - [ ] /subscribers/lib/views
 - [ ] config
   - [ ] /env
 - [ ] controllers
   - [ ] /frontend
 - [ ] data
   - [ ] /db
   - [ ] /export
   - [ ] /importer/handlers
   - [ ] /importer/importers/data
   - [ ] /importer/importers
   - [ ] /importer
   - [ ] /meta
   - [ ] /migrations/hooks/init
   - [ ] /migrations/hooks/migrate
   - [ ] /migrations/init
   - [ ] /migrations/versions/1.13
   - [ ] /migrations/versions/1.18
   - [ ] /migrations/versions/1.19
   - [ ] /migrations/versions/1.20
   - [ ] /migrations/versions/1.21
   - [ ] /migrations/versions/1.22
   - [ ] /migrations/versions/1.3
   - [ ] /migrations/versions/1.4
   - [ ] /migrations/versions/1.5
   - [ ] /migrations/versions/1.7
   - [ ] /migrations/versions/1.9
   - [ ] /schema
   - [ ] /schema/clients
   - [ ] /schema/fixtures
   - [ ] /validation
   - [ ] /xml/sitemap
 - [ ] helpers
   - [ ] /tpl
 - [ ] lib
   - [ ] /common
   - [ ] /fs
   - [ ] /fs/package-json
   - [ ] /image
   - [ ] /mobiledoc/atoms
   - [ ] /mobiledoc/cards
   - [ ] /mobiledoc/converters
   - [ ] /mobiledoc
   - [ ] /promise
   - [ ] /security
   - [ ] /social
 - [ ] models
   - [ ] /base
   - [ ] /plugins
   - [ ] /relations
 - [ ] public
 - [ ] services
   - [ ] /apps
   - [ ] /auth
   - [ ] /channels
   - [ ] /mail
   - [ ] /mail/templates
   - [ ] /mail/templates/raw
   - [ ] /permissions
   - [ ] /route
   - [ ] /rss
   - [ ] /settings
   - [ ] /themes
   - [ ] /themes/config
   - [ ] /url
 - [ ] translations
 - [ ] views
 - [ ] web
   - [ ] /admin
   - [ ] /admin/views
   - [ ] /api
   - [ ] /middleware
   - [ ] /middleware/api
   - [ ] /middleware/validation
   - [ ] /site

**Comment by karaggeorge** [comment]
@vikaspotluri123 

I guess I'll wait until Ghost drops it before working on this 😄

**Comment by kirrg001** [comment]
Yeah please wait 2 weeks minimum, because of the Node v4 drop and we will merge dynamic routing in a 1-2 weeks, which moves some files around. It's quite a big feature. I'll give the go here if you want :)

**Comment by karaggeorge** [comment]
@kirrg001 sounds good!

**Comment by kirrg001** [comment]
FYI: We also have a couple of dependencies, which would need an ES6 update. I am not sure how much ES6 updates are required, but worth double checking.

e.g. 
- [gscan](https://github.com/TryGhost/gscan)
- [bookshelf-relations](https://github.com/TryGhost/bookshelf-relations)
- [knex-migrator](https://github.com/TryGhost/knex-migrator)
- [GQL](https://github.com/TryGhost/GQL)
- [Ignition](https://github.com/TryGhost/Ignition)

Let me know if you are interested in helping out there as well 🤠

---

Regarding the ES6 updates in Ghost. [Dynamic routing](https://github.com/TryGhost/Ghost/pull/9596) was not merged yet and i would love to wait with the ES6 updates till then. As said, i'll let you know, when you can start with ES6 PR's for Ghost.

**Comment by Tiendq** [comment]
I'd like to try this too :). It's likely done file by file but how can we prevent same modification from happening? Can we break it down to many small issues each have its own PR later? Once an item is picked from @vikaspotluri123 list, for example, it'll be crossed out and added an issue number so others can simply ignore it.

**Comment by billfienberg** [comment]
I'd like to help.

**Comment by vivekannan** [comment]
I would like to be involved in this as well.

**Comment by mikkqu** [comment]
I'd be glad to work on this too. Subscribing to a thread to not miss the updates.

**Comment by kirrg001** [comment]
Sorry. I was three weeks off. As soon as https://github.com/TryGhost/Ghost/pull/9596 get's merged, you can start with the ES6 migrations. Thanks :)

**Comment by hkd987** [comment]
currently working on this as well.     
Have a pull request in on ./helpers/asset.js
Will start working on the smaller files in this folder when I have time.

https://github.com/TryGhost/Ghost/pull/9662

**Comment by vikaspotluri123** [comment]
@hkd987 I've updated the checklist and marked you as working on `helpers/*`

**Comment by tiendq** [comment]
If no one picked it, I could start with `controllers` or `apps` tomorrow :)

**Comment by vikaspotluri123** [comment]
@tiendq starting is still on hold for now; see [#9662 (comment)](https://github.com/TryGhost/Ghost/pull/9662#issuecomment-394342741)

**Comment by kirrg001** [comment]
https://github.com/TryGhost/Ghost/pull/9596 was merged 🚓

**Comment by tiendq** [comment]
@vikaspotluri123 `controllers` has been disappeared :D, so I'd like to give another try with `apps` :)

**Comment by mandeepm91** [comment]
Hi @vikaspotluri123 I would like to help with this. Let me know which directory I can pick up. 
Thanks!

**Comment by vikaspotluri123** [comment]
@mandeepm91 Feel free to pick any folder that isn't checked off or has WIP to the right of it!

**Comment by kevinansfield** [comment]
FYI, for anyone working on this there are numerous codemods available to automate a lot of the es6 transformation work. This article is a nice introduction to codemods https://medium.com/airbnb-engineering/turbocharged-javascript-refactoring-with-codemods-b0cae8b326b9

**Comment by tiendq** [comment]
@kirrg001 @kevinansfield  I see many named callback functions, and function names are not used anywhere. Obviously I will replace them with arrow functions but I'm not sure if it's right decision :)

**Comment by mandeepm91** [comment]
@vikaspotluri123 it's my first contribution so if I am making any mistakes in following the process, please let me know.
Thanks

**Comment by mandeepm91** [comment]
@vikaspotluri123 @kirrg001 @kevinansfield 

The linter is showing some issues which aren't really issues in my opinion. For example, consider the code:

      .then(() => _private.readRedirectsFile());

It raises the issue that `_private.readRedirectsFile()` should be inside a block. So, consequently I am changing this to:

      .then(() => { return _private.readRedirectsFile(); });

But I think the former approach is more concise and more readable. What do you think ?

**Comment by mandeepm91** [comment]
@kirrg001 Sorry I missed your comment regarding including small PRs with only 1 or 2 files in a PR. I was earlier planning on converting the entire `core/server/api` directory and then raising a PR. I have already converted 12 files so far. Will it be ok if I raise a PR for those 12 files?

**Comment by tiendq** [comment]
@mandeepm91 Agree, linter is strict more than enough in certain situations. I have also noticed another case: `.then((result) => ...)`, parentheses are must while `.then(result => ...)` is fine.

**Comment by vikaspotluri123** [comment]
wrt linting... @kirrg001 is there any plan to use the Ghost eslint plugin for this repo? If so, we might be able to add another npm / grunt script (i.e `lint:bleeding`) which uses an eslintrc file based on the plugin. Then, for PRs related to ES6, there would be an additional requirement that `yarn lint:bleeding` passes which would allow for the gradual migration to the new rules 🤔

**Comment by Huc91** [comment]
I also would like to help you out, can I still refer to the checklist posted by @vikaspotluri123 as a reference to what still need to be done?

**Comment by vikaspotluri123** [comment]
Yep, @Huc91! I think I've notated all the PRs, but the assignments are up to date. @ everyone else - if a PR doesn't get added to the list after a day or two feel free to ask me to add it 😄

**Comment by vikaspotluri123** [comment]
As mentioned in [#9689 (comment)](https://github.com/TryGhost/Ghost/pull/9689#issuecomment-397017533), @billfienberg is working on the `adapters` folder

**Comment by Huc91** [comment]
@vikaspotluri123 Thanks, I'm gonna take a look

**Comment by larsnolden** [comment]
@vikaspotluri123 I am working on everything inside server/web. [More to come](https://github.com/TryGhost/Ghost/pull/9729)

**Comment by kirrg001** [comment]
You can automate the ES6 migration using https://github.com/esnext/esnext. I have recently used it just to try it out and it worked okay. I think the module is definitely not compatible with everything, but wanted to share if somebody wants to try it out 🤠

**Comment by mandeepm91** [comment]
Sorry about that long list of commit messages. My old branch got messed up while syncing my fork with the upstream. I have kept that old branch aside for now and created a new one. I will be creating small PRs with 2 files in each PR from now onwards

**Comment by iamclaytonray** [comment]
I'm new but it would be super easy to use TypeScript to access ES6+ features even if you didn't type anything, though, that's always a great idea. I'd be happy to refactor to TS or help with the ES6+ refactor. It would also be great to use named exports with destructured imports. This helps a lot with future contributors because of auto-complete. Also, would classes be on this list instead of prototypes?

(named exports instead of default exports are better, IMO. With defaults, someone could:

```js
import Something from './something';
import something from './something';
```

**Comment by rishabhgrg** [comment]
Update: API folder(`server/web/api`) is now being updated by Ghost team.

**Comment by gargol** [comment]
Update: `/web` folder being worked on by Ghost team :tada:

**Comment by m1guelpf** [comment]
s the migration complete? The checkboxes seem outdated...

**Comment by vikaspotluri123** [comment]
I think with the exception of API everything should be up to date 🤔

**Comment by kirrg001** [comment]
It's not finished. e.g. the `data/` folder was not transformed into ES6.

**Comment by vikaspotluri123** [comment]
@Jgriebel1990 feel free to pick something from the checklist and let us know! I'll probably update the list w/ a more in depth status next week

**Comment by ashish-r** [comment]
Hi, What's the status. I would like to contribute too.

**Comment by gargol** [comment]
Hey @ashish-r , the honest answer is "you would need to check yourself" :smile: Most of the codebase seems to have been updated, but as @kirrg001 pointed out earlier the `data/` folder hasn't been touched, also see that parts of `models/` are still on older syntax. 

I would suggest updating the [list on top](https://github.com/TryGhost/Ghost/issues/9589#issuecomment-383177370) first, and then approaching it one piece at a time, so it's easy and fast to merge.

**Comment by vikaspotluri123** [comment]
Not stale

**Comment by ErisDS** [comment]
Always really happy to accept PRs that ES6ify the code at any point, but don't think it needs the issue - file structure changes a lot and I think this possibly makes it seem harder?
