### ISSUE TITLE
Errors with grunt init

### ISSUE THREAD

**Issue by umaar** [TryGhost/Ghost#9594]
### Issue Summary

Errors with `grunt init`

### Steps to Reproduce

1. Follow steps here: https://docs.ghost.org/v1/docs/working-with-ghost until the `yarn setup` task
2. Run `yarn setup` or `grunt init`

Notice these errors:

```
➜  Ghost git:(master) grunt init
Running "update_submodules:pinned" (update_submodules) task

Running "subgrunt:init" (subgrunt) task
yarn install v1.6.0
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
[3/5] 🚚  Fetching packages...
warning Pattern ["glob@latest"] is trying to unpack in the same destination "/Users/umarhansa/Library/Caches/Yarn/v1/npm-glob-7.1.2-c19c9df9a028702d678612384a6552404c636d15" as pattern ["glob@^7.0.5","glob@^7.0.5","glob@^7.1.0","glob@^7.0.4","glob@^7.1.2","glob@^7.0.3","glob@^7.0.3","glob@7.1.2","glob@^7.0.4"]. This could result in non-deterministic behavior, skipping.
error eslint-plugin-ghost@0.0.23: The engine "node" is incompatible with this module. Expected version "^4.5.0 || ^6.9.0 || ^8.9.0".
error Found incompatible module
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
Warning: Failed installing node modules in "core/client". Use --force to continue.

Aborted due to warnings.
```

### Technical details:

* Ghost Version: 1.22.3
* Node Version: v9.9.0
* Browser/OS: macOS High Sierra

**Comment by kevinansfield** [comment]
Hey @umaar 👋 Thanks for the report. This is an issue in Ghost's [eslint-plugin-ghost](https://github.com/TryGhost/eslint-plugin-ghost) package where the supported node versions are restricted to [Ghost's supported Node.js versions](https://docs.ghost.org/docs/supported-node-versions) which is probably too restrictive for a developer-oriented package.

I've [opened an issue](https://github.com/TryGhost/eslint-plugin-ghost/issues/5) on the appropriate repo and this should be looked at next Monday. In the meantime the workaround would be to use Node.js 8.

**Comment by umaar** [comment]
Thanks! It could also be worth having an integration test which verifies Ghost can be setup, installed, and viewed on http://localhost:2368/ on the latest stable node

**Comment by paynezhuang** [comment]
same question

```
yarn run v1.17.3
warning ghost@2.25.9: The engine "cli" appears to be invalid.
$ yarn install && knex-migrator init && grunt symlink && grunt init || true
[1/5] 🔍  Validating package.json...
warning ghost@2.25.9: The engine "cli" appears to be invalid.
[2/5] 🔍  Resolving packages...
success Already up-to-date.
$ cpy node_modules/@tryghost/members-theme-bindings/build/members-theme-bindings.js core/server/public/
[2019-07-27 07:47:58] INFO Finished database init!
Running "symlink:githooks" (symlink) task
>> Destination .git/hooks/pre-commit already exists.
>> Created 0 symbolic links.

Done.
Running "update_submodules:pinned" (update_submodules) task

```

node -v -> v10.15.3
Ghost Version: 2.25.9
