### ISSUE TITLE
Mouse cursor is hard to find when editing a post

### ISSUE THREAD

**Issue by steveblue** [TryGhost/Ghost#9597]
Welcome to Ghost's GitHub repo! 👋🎉

Do you need help or have a question? Please come chat in our forum: https://forum.ghost.org 👫.

Found a bug? Please fill out the sections below... thank you 👍

If your issue is with Ghost CLI, please report it on the CLI repo ➡️ https://github.com/TryGhost/Ghost-CLI/issues/new.

### Issue Summary

The mouse cursor is hard to see in the editor. Ghost has a brilliant blinking white cursor to mark the current place I am typing, but when I move the mouse the mouse cursor is quite difficult to see especially with the screen brightness of my laptop turned down. I expect the cursor to be brighter especially considering the background of the editor is quite dark.

### Steps to Reproduce

1. Open a new story
2. Type a paragraph in the editor
3. Turn screen brightness down or look at a slight angle on any screen
4. Hover over the paragraph and notice the cursor is hard to find

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

I expect the mouse cursor to be subdued compared to the blinking cursor but still noticeable. The current color of the cursor makes it difficult for some users to see it. 

### Technical details:

* Ghost Version: 1.22.1
* Node Version: 8.9.4
* Browser/OS: Safari
* Database: ?

**Comment by kevinansfield** [comment]
Hey @steveblue 👋 It took me a while to work out what you were referring to until I realised you were probably talking about the beta Night Shift mode. Unfortunately browsers don't offer a way to change the colour of the pointer in the same way they do for caret so it's up to the OS to adjust it or add highlights and so on. Unfortunately OS X doesn't do a particularly good job of this, you can see an example of Atom, Chrome's DevTools, and Ghost in the screen cap below that shows this is a universal problem with dark backgrounds:

![dark cursor example](https://user-images.githubusercontent.com/415/39117134-26287082-46de-11e8-92be-4c3001a3e269.gif)

All I can suggest for now is that if you're having trouble with the cursor color on dark backgrounds with your monitor then you disable Night Shift.

**Comment by steveblue** [comment]
@kevinansfield I was not in Night Shift mode. I was on a flight, crammed in a seat and could not look dead on to the monitor and I had the brightness on the monitor down to conserve battery life so at angle the cursor was lost. 

FYI it is possible to change the cursor with a SVG when hovering over the text editor. https://css-tricks.com/using-css-cursors/

**Comment by steveblue** [comment]
<img width="1440" alt="screen shot 2018-04-23 at 4 36 48 pm" src="https://user-images.githubusercontent.com/1171943/39158397-a8557164-4714-11e8-9f35-da51e0e59624.png">
Works pretty good in the title, but the description is gonna make it tougher.

**Comment by steveblue** [comment]
<img width="1435" alt="screen shot 2018-04-23 at 4 36 48 pm" src="https://user-images.githubusercontent.com/1171943/39158419-cec5cad8-4714-11e8-87e0-01bbb3f86593.png">
It is very easy to change the cursor in the title, but not the description ATM.

**Comment by kevinansfield** [comment]
@steveblue those screenshots are showing Night Shift mode, you can disable it on the Labs screen.

"Dark" mode apps on OS X all show the same problem with a caret cursor, if you don't have the monitor brightness up then the cursor can be difficult to see. There are a few workarounds but they all require fine tuning for different OS's (we do not want to interfere with default OS behaviour) and for various screen DPIs so it would need careful consideration.
