### ISSUE TITLE
Bug: post.hbs will not display author.name if used in post preview

### ISSUE THREAD

**Issue by ss4344** [TryGhost/Ghost#9598]
### Issue Summary
post.hbs will not display author.name in post preview, however the author name does show for published posts.

I lightly modify the Casper theme to feature the author name at the top of the post, so this issue would likely not be obvious using a stock Casper theme.

This is a snip of my modified post.hbs code:

`            <section class="post-full-content">
                {{#author}}
                <section class="author-card">
                    <section class="author-card-content">
                        <h4 class="author-card-name">By <a href="{{url}}">{{name}}</a>
                    </section>
                </section>
                {{/author}}
                <p>
                {{content}}
            </section>
`

### Technical details
* Ghost Version installed: master 1.22.3
* Slightly customised Casper theme

**Comment by CriticalRespawn** [comment]
Hi @ss4344 😃 

I've added a Pull Request [here](https://github.com/TryGhost/Casper/pull/452) which sorts this for the Casper theme. Ghost now allows multiple authors for posts so {{author}} is deprecated.

**Comment by AileenCGN** [comment]
I can confirm this behaviour.

**Comment by kirrg001** [comment]
Fixed via https://github.com/TryGhost/Ghost/commit/f63de38f36c62f59c2254b680039ae1ecb1c794d. 

Somehow the `closes` statement in the commit is missing, but i have added it. Super weird.
