### ISSUE TITLE
Instagram Support for Ghost

### ISSUE THREAD

**Issue by tjh2822** [TryGhost/Ghost#9599]
### Issue Summary

Many of the sites that Ghosst supports are adding media links to sites other than faebook and twitter. It would greatly improve the versitality of Ghost to expland the availble options. Other sites would include GitHub, YouTube. I am aware that themes exist to fix this but those solutions are "janky" at best. Alot of Ghost users are not as tech savy as others and this would halp improve the platform for those users.

### Steps to Reproduce

1. Notify theme creators.
2. Add the option in the ghost admin pannel
3. Add it to the Ghost API.
4. Make sure this new type of theming is backwards compatable with old themes

### Technical details:

Feature to improve ease of access for many Ghost users.

**Comment by ErisDS** [comment]
Hey @tjh2822  👋 Please do not use GitHub for feature requests. We use GitHub solely for bug-tracking and on-going feature development so we try to keep it noise free.

You can vote on this idea on the forum here: https://forum.ghost.org/t/additional-social-accounts-in-general-settings/750

FYI: Many projects have their own support guidelines and GitHub will highlight them for you, or the project owners will use issue templates to point you in the right direction, please read them before opening issues

**Comment by mansona** [comment]
Hey folks 👋 just in case anyone comes across this issue I added another idea to vote for in the forum https://forum.ghost.org/t/additional-social-accounts-for-authors/13725

It's specifically about authors but it might be what you were looking for @tjh2822 👍
