### ISSUE TITLE
Command failed: /bin/sh -c sudo -S -p '#node-sudo-passwd#'  systemctl is-active ghost_localhost

### ISSUE THREAD

**Issue by 1c7** [TryGhost/Ghost#9607]
I was trying to upgrade Ghost, and now my blog is down, I can't `ghost start`
here is my `ghost doctor` report
Thanks for helping!

### Issue Summary
Debug Information:
    OS: Ubuntu, v16.04
    Node Version: v6.14.1
    Ghost-CLI Version: 1.7.1
    Environment: production
    Command: 'ghost doctor'

### Steps to Reproduce
1. run `ghost doctor`

![image](https://user-images.githubusercontent.com/1804755/39364323-2f36fbfa-4a60-11e8-85b3-31660211d977.png)

**Comment by ErisDS** [comment]
Hey @1c7  👋 We ask that you please do not use GitHub for help or support, the default issue template pointed you to our [forum](https://forum.ghost.org) for this type of question 😄 We use GitHub solely for bug-tracking and on-going feature development so we try to keep it noise free.

Many questions can be answered by reviewing our docs for [self-hosters](https://docs.ghost.org), our [theme API](https://themes.ghost.org), or our [public API](https://api.ghost.org). If you can't find an answer then our [forum](https://forum.ghost.org) is a great place to get community support, plus it helps create a central location for searching problems/solutions.

FYI: Many projects have their own support guidelines and GitHub will highlight them for you, or the project owners will use issue templates to point you in the right direction, please read them before opening issues

**Comment by 1c7** [comment]
any help is appreciate!

**Comment by 1c7** [comment]
@ErisDS understood, thanks

**Comment by 1c7** [comment]
problem fix: https://forum.ghost.org/t/fixed-problem-after-ghost-update-command-failed-bin-sh-c-sudo-s-p-node-sudo-passwd-systemctl-is-active-ghost-localhost/1102

**Comment by VinayakDeshpande11** [comment]
I get this error 

> Failed to issue method call: Unit ghost_localhost.service failed to load: No such file or directory. See system logs and 'systemctl status ghost_localhost.service' for details.

on calling 

`sudo systemctl start ghost_localhost`

does anybody knows how to resolve thos?

Thanks in advance.

**Comment by kirrg001** [comment]
@VinayakDeshpande11 Please use our [forum](https://forum.ghost.org).

**Comment by DpangD** [comment]
> I get this error
> 
> > Failed to issue method call: Unit ghost_localhost.service failed to load: No such file or directory. See system logs and 'systemctl status ghost_localhost.service' for details.
> 
> on calling
> 
> `sudo systemctl start ghost_localhost`
> 
> does anybody knows how to resolve this?
> 
> Thanks in advance.

Change 'localhost' to the IP you set.
