### ISSUE TITLE
Drop Node 4 support

### ISSUE THREAD

**Issue by kirrg001** [TryGhost/Ghost#9609]
It's time to drop Node 4, see release schedule: https://github.com/nodejs/Release.
The support ends today.

We are dropping Node v4 for master (1.0) and LTS.

- [x] drop 4 on master (https://github.com/TryGhost/Ghost/pull/9610)
- [x] drop 4 on LTS (https://github.com/TryGhost/Ghost/pull/9612)
- [x] drop Node v4 from the CLI (tryghost/ghost-cli#695) @acburdine @vikaspotluri123 
- [x] drop Node v4 from Knex-Migrator (https://github.com/TryGhost/knex-migrator/pull/102)
- [x] drop Node v4 from Ghost-Ignition (https://github.com/TryGhost/Ignition/commit/c0690030b964854855995e5b62e8c4aa67bcf8c4)
- [x] drop node v4 bookshelf-relations (https://github.com/TryGhost/bookshelf-relations/pull/2)
- [x] drop node v4 in GQL
- [x] drop node v4 in gscan master (we ignore 0.x branch)
- [x] drop node 4 on brute-knex

We would like merge the changes today and release them tomorrow 💫

**Comment by kirrg001** [comment]
@acburdine You can reference the Node v4 drop in the CLI to this issue. Thanks!

**Comment by vikaspotluri123** [comment]
tryghost/ghost-cli#695 is the related PR for the CLI 😄

**Comment by kirrg001** [comment]
@vikaspotluri123 Ah nice. Have not seen this one. Thanks so much 😀
