### ISSUE TITLE
Unable to upgrade to 1.22.x, ER_CANNOT_ADD_FOREIGN on table posts_authors

### ISSUE THREAD

**Issue by cmilanf** [TryGhost/Ghost#9613]
### Issue Summary

A very similar problem to the one described at #9539 (definitely related to #9426), but this time with MySQL database and Linux as host OS (running Ghost as a Docker container). Trying to upgrade Ghost 1.21.x to Ghost 1.22.x will result on a database migration error.

```
[22:35:20] Running database migrations [started]
[22:35:33] Running database migrations [failed]
[22:35:33] The database migration in Ghost encountered an error.
A ProcessError occurred.

Message: The database migration in Ghost encountered an error.
Help: https://docs.ghost.org/v1/docs/troubleshooting#section-general-update-error
Suggestion: ghost update --rollback
--------------- stderr ---------------
[2018-05-01 22:35:33] ERROR

NAME: MigrationScriptError
CODE: ER_CANNOT_ADD_FOREIGN
MESSAGE: alter table 'posts_authors' add constraint 'posts_authors_post_id_foreign' foreign key ('post_id') references 'posts' ('id') - ER_CANNOT_ADD_FOREIGN: Cannot add foreign key constraint
```

### Steps to Reproduce

1. Run `ghost update -V` on a version 1.21.x blog. In this case it was version 1.21.2.
2. Error will show up.

I also tried to run `knex-migrator` manually to get more detail about why the problem is happening and it looks like the database table `post_authors` gets created and immediately deleted, so when the `ALTER TABLE` query is sent, there is actually no table where it could be applied. I'm attaching the knex log to this issue.

### Technical details:
Debug Information:
    OS: linux, v4.13.0-1011-azure
    Node Version: v6.13.0
    Ghost-CLI Version: 1.7.2
    Ghost version: 1.21.2
    Database: MySQL 5.7
    Environment: production
    Command: 'ghost update -V'

Logs:
[ghost-cli-debug-2018-05-01T22_35_33_311Z.log](https://github.com/TryGhost/Ghost/files/1965403/ghost-cli-debug-2018-05-01T22_35_33_311Z.log)
[knex-migrator.log](https://github.com/TryGhost/Ghost/files/1965405/knex-migrator.log)

**Comment by kirrg001** [comment]
Hey @cmilanf!

Sorry for having trouble. I am unable to reproduce this. 

> I also tried to run knex-migrator manually

Can you please try again and run knex-migrator with `DEBUG=knex:query,knex-migrator:*`? That might give use some more details.

> A very similar problem to the one described at #9539

I don't think this is related.

**Comment by cmilanf** [comment]
You were right, it was not related. Thanks to the debug information I was able to see that the `--init` parameter was sliping into my script when the database already existed. Removing it made the migration work as expected:

```
2018-05-02T10:15:31.682854081Z ************started migration***********
2018-05-02T10:15:39.927877974Z [2018-05-02 10:15:39] INFO Creating database backup 
2018-05-02T10:15:40.454413947Z [2018-05-02 10:15:40] INFO Database backup written to: /home/site/wwwroot/data/1.ghost.2018-05-02.json 
2018-05-02T10:15:40.483938395Z [2018-05-02 10:15:40] INFO Adding table: posts_authors 
2018-05-02T10:15:44.575474387Z [2018-05-02 10:15:44] INFO Adding `posts_authors` relations 
2018-05-02T10:15:46.074203163Z [2018-05-02 10:15:46] INFO Finished database migration! 
2018-05-02T10:15:46.098487307Z ************migration ended***********
```

I still wonder why `ghost-cli` didn't work though... But the problem is solved and the issue can be closed.

Thanks for your help @kirrg001

**Comment by kirrg001** [comment]
@cmilanf Thanks for coming back and happy you sorted it out!

> I still wonder why ghost-cli didn't work though

I wonder too. I'll re-test migrating from 1.21 to 1.22.5, because we have updated one of our dependencies.

**Comment by cmilanf** [comment]
Thank you @kirrg001 for the additional help offer, but I am not able to hand over the whole database, even if I know it is just for testing and bug hunting purposes :)

I will try again in next upgrade with `ghost-cli` to see if I have the problem again. `knex-migrator` worked as expected.
