### ISSUE TITLE
NodeJS 6 no more active LTS 

### ISSUE THREAD

**Issue by nabbar** [TryGhost/Ghost#9614]
Hi, 

The current active LTS is nodejs v8 since 30 April 2018.
The nodejs 6 is just passed as maintenance active.

Please update to allow nodejs 8 compatible.

cf https://github.com/nodejs/Release

Thanks in advance.

**Comment by kirrg001** [comment]
Node v6 and v8 is supported, [see](https://docs.ghost.org/docs/supported-node-versions). We are currently work on recommending v8 for everyone.

If you have any questions, please use our [forum](https://forum.ghost.org) - we do not offer any support in GitHub. Thanks!

**Comment by flip111** [comment]
What about NodeJS 10 support ?

**Comment by vikaspotluri123** [comment]
v10 was released April 24 and will remain the active version for 6 months until it reaches LTS status in October. Checkout [nodejs/Relase](https://github.com/nodejs/Release) for more info

**Comment by flip111** [comment]
@vikaspotluri123 i've read that. I was asking for *ghost* support for NodeJS 10. Will it be there on the day of the LTS release? maybe sooner? maybe later?

**Comment by vikaspotluri123** [comment]
@flip111 It will be around when v10 reaches LTS. Ghost node version support [follows LTS](https://docs.ghost.org/docs/supported-node-versions) so there might be a few days delay while upstream dependencies release updates and Ghost itself is updated to support v10.
