### ISSUE TITLE
Subexpression inside limit does not work

### ISSUE THREAD

**Issue by ejamesc** [TryGhost/Ghost#9626]
### Issue Summary

In the documentation for @config, the following example is given:

```
{{#get "posts" filter="featured:true" limit="{{@config.posts_per_page}}"}}
```

This does not work because there is no special logic in the `limit` parameter to handle the subexpression. Instead, attempting to use this code will result in 

```
NAME: ValidationError
MESSAGE: Validation (matches) failed for limit
```

### Steps to Reproduce

1. Get a theme
2. Add {{@config.posts_per_page}} to the limit parameter for a `get` query.
3. You'll see the following error:

```
NAME: ValidationError
MESSAGE: Validation (matches) failed for limit
```

Suggestion: this should work. Specifically the special subexpression logic in the `filter` parameter should also be applied to the `limit` parameter for `get` queries

### Technical details:

* Ghost Version: 1.22.2
* Node Version: 8.11.1
* Browser/OS: Chrome
* Database: SQLite

**Comment by kevinansfield** [comment]
Hey @ejamesc 👋 Unfortunately you ran into a typo in our docs (now fixed) that showed the value being used inside quotes. The correct usage for the limit param would have been:

```
{{#get "posts" filter="featured:true" limit=@config.posts_per_page}}
```

The `limit` parameter doesn't support the custom `"id:{{data.property}}"` data-access syntax that the `filter` param does because it only supports a single integer or number string.

Closing this because it was a docs issue that has been resolved. Sorry for the confusion!

**Comment by ejamesc** [comment]
Alright then, thank you for the fast response! 
		
		

		Sent from a mobile device. 
	




On Fri, May 11, 2018 at 10:11 PM +0800, "Kevin Ansfield" <notifications@github.com> wrote:












Hey @ejamesc 👋 Unfortunately you ran into a typo in our docs (now fixed) that showed the value being used inside quotes. The correct usage for the limit param would have been:
{{#get "posts" filter="featured:true" limit=@config.posts_per_page}}



The limit parameter doesn't support the custom "id:{{data.property}}" data-access syntax that the filter param does because it only supports a single integer or number string.


Closing this because it was a docs issue that has been resolved. Sorry for the confusion!

**Comment by ejamesc** [comment]
Alright then! Thank you for the quick response!
