### ISSUE TITLE
Text get's automatically selected in Firefox

### ISSUE THREAD

**Issue by jlelse** [TryGhost/Ghost#9627]
### Issue Summary

I'm experiencing a weird bug since the last release and it's just happening in Firefox. Whenever I type a few keys in the editor or move around the mouse cursor, the text get's automatically selected. I also tried it in Opera, it isn't happening there. It's also just since the last release (1.22.7). It could also be a bug in my Firefox version (I'm using Solus Linux) or some misbehavior due to some plugins (I use just 3).

### Steps to Reproduce

1. Create a new draft
2. Write some text
3. Move around the cursor

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

The text shouldn't be selected without manually selecting it.

### Technical details:

* Ghost Version: 1.22.7
* Node Version:
* Browser/OS: Firefox, Solus Linux
* Database: SQLite

**Comment by kevinansfield** [comment]
Hey @jlelse 👋 Unfortunately I'm not able to reproduce this with Firefox 60 on macOS or Ubuntu 16 so it sounds like it's an environment issue, as such I'm going to close for now.

If you can reproduce on other computers then we can re-open but it may require input from the community as it will need someone with the same environment and reproducible issue to be able to solve it.
