### ISSUE TITLE
/edit/ redirects with custom admin URL fail in Safari

### ISSUE THREAD

**Issue by kevinansfield** [TryGhost/Ghost#9633]
### Issue Summary

Safari doesn't respect # params in redirects across domains so if your admin domain is different to your blog domain you can't use https://example.com/post-slug/edit/ to open the post in the editor.

### Steps to Reproduce

1. Configure your blog to have a different admin domain (different port also shows issue)
2. Open a post in safari
3. Add `/edit/` to the end of the URL in the address bar and press <kbd>Enter</kbd>
4. Note that you're redirected to the admin home screen instead of the post editor

I think a fix here could be to initially redirect to the non-hash admin URL because Ghost will then automatically redirect that to the hash-url. Eg:

https://example.com/post-slug/edit/ ->
https://admin.example.com/ghost/editor/post-id/ ->
https://admin.example.com/ghost/#/editor/post-id/

Safari should then respect the #-param redirect because the second redirect happens on the same domain. This _should_ work because we know that signup works in Safari and the signup e-mails include the non-hash URL but it's untested as part of a larger redirect chain.

### Technical details:

* Ghost Version: 1.22.8
* Node Version: n/a
* Browser/OS: Safari/macOS
* Database: n/a

**Comment by ololoken** [comment]
Hi, any ideas why tests on travis are failing with db lock problem? as locally everything is fine.

**Comment by kevinansfield** [comment]
Hey @ololoken 👋 It's just a random Travis failure. I've restarted it for you.

FYI, there's no need to close a PR and re-open to update it, you can just force-push to overwrite if you've changed the code.

I'll be reviewing your PRs on Monday, thanks for opening them! 😄

**Comment by ololoken** [comment]
yeah, thanks, I'm a new in contributing so don't pay attention to my a little strange activity
