### ISSUE TITLE
Editor is broken on mobile browser

### ISSUE THREAD

**Issue by psycholyzern** [TryGhost/Ghost#9641]
### Issue Summary

Editor layout on my Android phone is broken. There is no publish button.
I am using Chrome and Firefox on my OnePlus 5T running Android 8.1.

### Steps to Reproduce

Make a new or edit any existing story.
The current editor is not responsive and unusable on my phone. I couldn't edit old posts using Android app, so I am left with browser, but it is not usable.
![](https://i.imgur.com/gGpKtRH.jpg)

### Technical details:

* Ghost Version: 1.22.8
* Node Version: 6.14.2
* Browser/OS: Chrome and Firefox on Android 8.1
* Database: MySQL

**Comment by JohnONolan** [comment]
The publish button is visible when you close the post settings menu - the android app will provide a more stable experience

**Comment by psycholyzern** [comment]
@JohnONolan  that is the problem. Close (X) button is not clickable on mobile browser. Meaning that it can't be closed and making the editor conpletely unsuable.

Also android app is useful for new posts, but not the old one because it can't load old post.

**Comment by kevinansfield** [comment]
@psycholyzern I'm also unable to replicate this, it seems like something very specific to your setup.

> Also android app is useful for new posts, but not the old one because it can't load old post.

The android app can definitely load old posts. If it's not loading posts for you then you should open an issue on the android app repo https://github.com/TryGhost/Ghost-Android. If you need help or support tracking down a problem with your particular ghost instance or mobile setup please head over to our [forum](https://forum.ghost.org) 😄

**Comment by vickychijwani** [comment]
@kevinansfield the app currently loads the last 30 posts, with drafts sorted to the top. There is an open issue about it here: https://github.com/TryGhost/Ghost-Android/issues/15 :slightly_smiling_face:

**Comment by psycholyzern** [comment]
@kevinansfield can you screenshot how it looks like to have the publish button? I'm not sure where I'm doing wrong because I have tried Chrome and Firefox and still couldn't close the post setting menu on the right.

**Comment by psycholyzern** [comment]
I still couldn't close the post setting menu on the right. [X] button does nothing. Anyone who doesn't have this issue, can you tell me if you are using browsers on Android too?

**Comment by arno01** [comment]
I am having the same issue. The [X] button in not clickable in the Chrome browser on my Android device Samsung Galaxy Tab S4.

I am using desktop mode in Chrome.

Not sure why this issue is closed, can it be reopened?
I would still like to be using the browser on Android for editing the pages instead of using the android app.

**Comment by arno01** [comment]
Meanwhile the workaround would be:

1. Edit the page while in the Desktop mode;
2. Disable Desktop mode, the Ghost will warn you about losing the changes, so click Cancel;
3. Voila! The post settings menu is closed and you can now see Update / Publish post buttons.

**Comment by psycholyzern** [comment]
I am surprised this issue stayed this long. I switched to Wordpress at the end and I am happy since then. 
Sadly Ghost is not fully working for mobile user like me due to this issue. That workaround is so ugly even it is working. But still, thanks for the tip!
