### ISSUE TITLE
Misaligned footer on posts in Firefox

### ISSUE THREAD

**Issue by hsand** [TryGhost/Ghost#9646]
The post-full-footer element is misaligned when viewed in Firefox. It creates a huge white space between the end of the post and the bottom of the page. This occurs in latest version of Firefox, but not Chrome.

This seems to be caused by a large, empty avatar-wrapper element to the left.

## Chrome
<img width="890" alt="chrome" src="https://user-images.githubusercontent.com/14326961/40407783-d96cd00e-5e65-11e8-90e5-4aac926a0ff9.PNG">

## Firefox
<img width="669" alt="ff" src="https://user-images.githubusercontent.com/14326961/40407871-07e14e2e-5e66-11e8-9e41-f53897eede33.PNG">

**Comment by kevinansfield** [comment]
Hey @hsand 👋 I think this issue belongs on the [Casper](https://github.com/TryGhost/Casper) (Ghost's default theme) repo. Please open it there, thanks 😄
