### ISSUE TITLE
Koenig editor's initial auto-save clips a few letters

### ISSUE THREAD

**Issue by javorszky** [TryGhost/Ghost#9649]
### Issue Summary

When I start a New Story, and start typing fast, the first auto-save will clip a few letters. My hunch is that the characters I've written since the save request got sent (and the saved state returned) are discarded.

### Steps to Reproduce

1. Open admin
2. Click on New Story
3. Start typing fast in the body
4. See that some characters are discarded.

Video: http://j7y.co/rnhf

For context, I am not using any other key besides letter keys.

#### Why do I think it's a bug?

Because it breaks the flow.

#### What I expect to happen

Characters are not discarded.

### Technical details:

* Ghost Version: 1.23.0
* Node Version: whatever is on Ghost(pro)
* Browser/OS: Firefox Quantum 60.0.1 (64bit) macOS 10.13.4
* Database: Ghost(pro)

**Comment by JohnONolan** [comment]
All details on Koenig beta feedback here: https://forum.ghost.org/t/koenig-editor-beta-release/1284
