### ISSUE TITLE
Just use one DatePicker for setting post's publication date

### ISSUE THREAD

**Issue by hmobius** [TryGhost/Ghost#9651]
### Issue Summary

There are two datepickers to set a post\ story's publication date in the story editor. 
One can be accessed by clicking the cog in the top right of the editor but it only allows you to set dates in the past. The other is found by clicking publish but it only allows you to set dates in the future.  I think I understand the reasoning but it seems more complex than it needs to be.

Please consider either having just one datepicker or having both datepickers allowing you to set publication dates in both past and future. The number of times I have wanted to set a date and gone to the wrong datepicker is really frustrating and the first couple of times I hit this issue I thought the actual editor was broken or had hung because there's no indication or message saying "you need to go here to set a date in the past \ future".

**Comment by AileenCGN** [comment]
Hi @hmobius 

Thanks for the idea!

We only keep Github issues open for bugs and in-progress feature work. Please check out [our forum](https://forum.ghost.org) to see if your suggested idea already exists, so you can upvote it, or post this idea in the features section for other users to see and upvote.
