### ISSUE TITLE
Image Caption not aligning to center when added using latest Koenig Editor

### ISSUE THREAD

**Issue by vCillusion** [TryGhost/Ghost#9652]
Image Caption not aligning to centre when added using latest Koenig Editor in Chrome Browser.

### Steps to Reproduce
1. Add image with caption
2. Image caption not centred

### Technical details:
Adding style in code injection solves the issue
```
<style>
    figcaption {
        display: block;
        text-align: center;
    }
</style>
```

**Comment by lbguilherme** [comment]
Are you using casper 2.3.0?

**Comment by vCillusion** [comment]
I am using Casper Version 2.2.1

**Comment by lbguilherme** [comment]
Styling for Koenig is on Casper 2.3+

**Comment by vCillusion** [comment]
@lbguilherme As per your suggestions, I upgraded to Casper 2.3, and adding the styling only centers the text.

**Comment by vikaspotluri123** [comment]
Hey @vCillusion :wave: could you please post this to the catch-all [forum topic](https://forum.ghost.org/t/koenig-editor-beta-release/1284)	(there's also some info on reporting issues w/ Koeing!)
