### ISSUE TITLE
Pasting (Ctrl + V) in new Markdown Block pastes value twice

### ISSUE THREAD

**Issue by vCillusion** [TryGhost/Ghost#9653]
### Issue Summary
Pasting (Ctrl + V) in new Markdown Block pastes value twice in Koenig Editor.

### Steps to Reproduce

1. Use latest Koenig Editor and write dynamic Text
2. Click + to add a new Markdown
3. Paste any value in new Markdown text box places it in the original as well as new markdown editor
4. Creating two copies of the pasted text

**Comment by vCillusion** [comment]
I am using Casper Version 2.2.1

**Comment by AileenCGN** [comment]
All details on Koenig beta feedback here: https://forum.ghost.org/t/koenig-editor-beta-release/1284
