### ISSUE TITLE
Disable Koenig Editor option from Labs in Ghost not working

### ISSUE THREAD

**Issue by vCillusion** [TryGhost/Ghost#9654]
### Issue Summary
I am not able to disable Koenig Editor Beta version

### Steps to Reproduce

1. Enable Koenig Editor Beta version
2. Use the feature
3. Disable the Editor Beta version

**Comment by vCillusion** [comment]
I am using Casper Version 2.2.1

**Comment by AileenCGN** [comment]
All details on Koenig beta feedback here: https://forum.ghost.org/t/koenig-editor-beta-release/1284
