### ISSUE TITLE
Ghost outputs duplicate log entries in production mode

### ISSUE THREAD

**Issue by acburdine** [TryGhost/Ghost#9656]
(Copied from https://github.com/TryGhost/Ghost-CLI/issues/741, as it was determined to be a Ghost issue rather than a CLI issue)

### Issue Summary

`ghost log -f` shows every log entry twice. After looking deeper, it looks like the lines in the logfile generated by Bunyan are duplicated.
This was also mentioned in the forum: https://forum.ghost.org/t/scheduled-posts-dont-publish/1179/28

### Steps to Reproduce

1. Install Ghost
2. Run Ghost in production mode
3. Look at the contents of the production logfile
4. Notice that lines are repeated

### Technical details:

* Ghost Version: 1.7.3
* Node Version: 6 & 8
* Browser/OS: macOS/Ubuntu
* Database: n/a

**Comment by evexoio** [comment]
@acburdine @kirrg001 I couldn't reproduce this, here's what I've done:

1. install Ghost *version 1.23.1*
2. run ghost in production mode
3. look at the contents of the production logfile
4. logs exist with no duplicate lines

then I tried the same on version 1.7.1, since @acburdine's bug report have `Ghost Version: 1.7.3`
got logs without duplicates

then I tried on version 1.8.0 just in case, and couldn't reproduce the issue there too,

can it be dependent on some other party, like database for example, I'm using sqlite on production mode

**Comment by kirrg001** [comment]
@evexoio Thanks for testing. 

> can it be dependent on some other party? like database for example, I'm using sqlite on production mode

No i don't think so, this is unrelated to the database.

---

Did you try to restart your server a couple of times? 🤔 Plus, which logging configuration have you used?

I only found:

- https://github.com/trentm/node-bunyan/issues/340
- maybe there are more issues, needs a little research :)

**Comment by evexoio** [comment]
@kirrg001 I did restart the server when I changed versions,

here is my logging config
```
    "logging": {
        "level": "info",
        "rotation": {
            "enabled": true,
            "count": 1,
            "period": "100000ms"
        },
        "transports": ["file", "stdout"]
    }
```

I'm down to solving this if I can reproduce it :)

**Comment by kirrg001** [comment]
@evexoio Hm i think it's related/caused by the rotation configuration.

```    
"logging": {
        "level": "info",
        "rotation": {
            "enabled": true
        },
        "transports": ["file", "stdout"]
    }
```

This configuration shows duplicated entries.

**Comment by evexoio** [comment]
@kirrg001 Thanks! I could reproduce using your config,

turned out the bug was in Ignition, when rotation was enabled, it was creating 2 logging streams other than the regular ones,

you can see my PR [here](https://github.com/TryGhost/Ignition/pull/59)
