### ISSUE TITLE
Installed Ghost but getting error 404 like nothing is there?

### ISSUE THREAD

**Issue by jsbyw** [TryGhost/Ghost#9659]
My site is: http://jsbyw.me 
Ive installed Ghost both through the CLI which was unsuccessful and manually which has worked and over SSH it says it is running but i only get a error 404 as if ghost isn't there. No errors at all now. Im confident it is installed correctly.
Anyone any ideas?

* Ghost Version: Latest
* Running Plesk on the server.

**Comment by kevinansfield** [comment]
Hey @jsbyw  👋 We ask that you please do not use GitHub for help or support, the default issue template pointed you to our [forum](https://forum.ghost.org) for this type of question 😄 We use GitHub solely for bug-tracking and on-going feature development so we try to keep it noise free.

Many questions can be answered by reviewing our docs for [self-hosters](https://docs.ghost.org), our [theme API](https://themes.ghost.org), or our [public API](https://api.ghost.org). If you can't find an answer then our [forum](https://forum.ghost.org) is a great place to get community support, plus it helps create a central location for searching problems/solutions.

FYI: Many projects have their own support guidelines and GitHub will highlight them for you, or the project owners will use issue templates to point you in the right direction, please read them before opening issues
