### ISSUE TITLE
Code injection - Request was rejected because user is not permitted to perform this operation.

### ISSUE THREAD

**Issue by TAiS46** [TryGhost/Ghost#9660]
I am trying to add google tag manager code but getting `Request was rejected because user is not permitted to perform this operation.`

It only happens when I wrap something in javascript code `<script></script>`

**Comment by kevinansfield** [comment]
Hey TAiS46  👋 This sounds like something environment-specific. Ghost itself doesn't do any filtering on request bodies but perhaps you have a security module in your web server config or there's something else between your ghost instance and web browser that is blocking certain POST requests. 

I'm going to close this as we use GitHub solely for bug-tracking and on-going feature development so we try to keep it noise free. Please ask on [our forum](https://forum.ghost.org) if you need further help 😄
