### ISSUE TITLE
Dynamic Routing vs. gAnalytics

### ISSUE THREAD

**Issue by tobiasboyd** [TryGhost/Ghost#9668]
### Issue Summary

Dynamic Routing redirects any post urls that have utm tagging for gAnalytics before the GA.js can load and notice them.

### To Reproduce

1. `ghost update`

version 1.24.0 will now redirect urls like

`https://myghostblog.net/a-post/?utm_term=example`

to

`https://myghostblog.net/a-post/`

before GA loads, so no more tracking for you!

### Technical details:

* Ghost Version: 1.24.0
* Node Version: v6.14.2
* Browser/OS: FF 61.0b11
* Database: sqlite

**Comment by zce** [comment]
It seems to have been solved 😀

https://github.com/TryGhost/Ghost/releases/tag/1.24.1
https://github.com/TryGhost/Ghost/commit/839d82b39

**Comment by kevinansfield** [comment]
Closed via https://github.com/TryGhost/Ghost/commit/839d82b3980fb931767b4a8d07c1769231723563
