### ISSUE TITLE
Test fixture dates don't use the right format in sqlite3

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#9670]
### Issue Summary

When running tests, dates get inserted into the SQLite3 database as a time stamp, E.g. "1436054400000". When working normally the same date would be inserted as "2015-07-05 00:00:00". This prevents any integration tests that do date comparison from working as expected.

### To Reproduce

Easy way to see what I mean

1. Run a test that inserts fixtures, but disable teardown
2. Inspect the dates in the DB

This is the real reason that [test 6 here](https://github.com/TryGhost/Ghost/blob/master/core/test/integration/api/advanced_browse_spec.js#L319) fails, and why I always thought date comparisons didn't work in our API. We know that [they do](https://github.com/TryGhost/Ghost/commit/fe0197b22676b52bc4db3c63c1dc4a3f9dea1814) if you get the format right, but the tests never worked properly.

It's because the input format in the DB is wrong!

I think we need a function in the test fixtures that handles inserting dates in UTC with the correct format? 

The goal is to be able to easily test that real date comparisons in SQL work.

### Technical details:

* Ghost Version: latest
* Node Version: 8
* Database: sqlite3

**Comment by lunaticmonk** [comment]
@ErisDS Is this issue still present? I see the test 6 that you linked in the description passes now.

**Comment by kirrg001** [comment]
I can't see dates being in timestamp format for SQLite3 🤔 

Any insert/update/fetch in the test env [runs through our model layer](https://github.com/TryGhost/Ghost/commit/e23fd511eb34f741dfdf9c4b8866f41671f5366a#diff-085888ce4e458820a35b19844ba3d990). And the model layer formats any dates [from and to the database.](https://github.com/TryGhost/Ghost/blob/2.9.1/core/server/models/base/index.js#L320)

I'm closing this issue for now. @ErisDS Feel free to re-open if you still encounter your observation :)
