### ISSUE TITLE
 Problem with {{#is}} helper

### ISSUE THREAD

**Issue by Kuzoin** [TryGhost/Ghost#9674]
### Issue Summary

Helper {{#is "home"}}{{/is}} it works the same as {{#is "index"}}{{/is}}

### Technical details:

* Ghost Version: 1.24.1
* Node Version: 8.11.1
* Browser/OS: Safari/macOS
* Database: sqlite3

**Comment by kirrg001** [comment]
Hey @Kuzoin!

Thanks for your report.

Could you please provide a little more information?
Steps to reproduce would be helpful 🙂

**Comment by Kuzoin** [comment]
Hello :)

### Steps to Reproduce

For Ghost 1.24.1 (localhost) 

1. Create home.hbs
2. In default.hbs create {{#is "home"}} `code` {{/is}}
3. Restart
4.  `code` is in the home page (its ok) but it is also on "paged".

Also {{body_class}} for "home" page is `home-template`, for "paged" is `home-template paged`

For Ghost 1.23.0 (localhost) 

1. Create home.hbs
2. In default.hbs create {{#is "home"}} `code`{{/is}}
3. Restart
4.  `code` is in only the home page.

{{body_class}} for "home" page is `home-template`, for "paged" is `paged`

**Comment by kirrg001** [comment]
@Kuzoin Will be released asap in 1.24.2. Thanks for your report 🙂

**Comment by Kuzoin** [comment]
@kirrg001 

Hello!

In 1.24.2 {{#is "home"}}{{/is}} works perfectly, but {{#is "index"}}{{/is}} not working :/
I tested at 1.23.0 - {{#is "index"}}`code`{{/is}} and it works correctly.

**Comment by kirrg001** [comment]
Will look at this again 👍
