### ISSUE TITLE
in the editor, the preview link leads to a bad path

### ISSUE THREAD

**Issue by pascalandy** [TryGhost/Ghost#9675]
### To Reproduce

1. create a new post "test", save it
2. click the link at the bottom left

my blog is at: `mrgreen.com/blog`

when I click the link, it goes to the wrong link:
`mrgreen.com/blog/blog/test`

### Technical details:

* Ghost Version: 1.24.1
* CLI version: 1.8.1
* Node Version: 8.10.2
* Browser/OS: chrome 66, osx 10.13.4
* Database: sqlite

Cheers!

**Comment by kirrg001** [comment]
Hey @pascalandy!

I can confirm this bug. Will be fixed on Monday and released on Tuesday 🙂

Thanks for the report!

**Comment by pascalandy** [comment]
Cool :-p
