### ISSUE TITLE
SVG Banner image

### ISSUE THREAD

**Issue by aniquetahir** [TryGhost/Ghost#9678]
### Issue Summary

Setting the banner image to an SVG image causes the banner to disappear

### To Reproduce

1. Create SVG banner
2. Upload in the administration panel
3. Go to the homepage to view banner image but its 0px by 0px

This can probably be resolved by setting min-width css property on the banner image?

### Technical details:

* Browser/OS: Firefox/Mac OS High Sierra
* Database: sqlite3

**Comment by kevinansfield** [comment]
Hey @aniquetahir 👋 This isn't a bug in Ghost itself but rather a theme issue. If you're using [Casper](https://github.com/TryGhost/Casper) then you can open an issue there, otherwise [our forum](https://forum.ghost.org) is a good place to get help with customising themes to match your requirements.
