### ISSUE TITLE
Static pages aren't shown on the tag page

### ISSUE THREAD

**Issue by thepluralistsorg** [TryGhost/Ghost#9680]
Static pages can be tagged in that admin interface but they aren't shown on the tag list. Maybe this is normal behaviour but I couldn't find any documentation to confirm that.

http://DOMAIN/tag/xxxx doesn't show the static pages that are tagged with xxxx

As a real world example: https://thepluralists.org/tag/open-culture should show a number of static pages but it does not.

**Comment by kevinansfield** [comment]
Hi @thepluralistsorg 👋 This is expected, static pages are removed from all post lists as they are intended to be separate pages on your site that are linked to within the navigation or directly in your theme.

The only way you can pull static pages out as part of a post list is when using the [`{{#get}}`](https://themes.ghost.org/docs/get) helper with the appropriate filters.

Closing as this isn't a bug. If you need any further help, [our forum](https://forum.ghost.org) is the best place to ask 😄
