### ISSUE TITLE
Lowercase slug values before sending the query to the database

### ISSUE THREAD

**Issue by AileenCGN** [TryGhost/Ghost#9695]
As MySQL is not case sensitive, but Sqlite3 is, some database queries fail when used in a case sensitive context.

We need to transform values to lowercase before sending the query to the database, to make sure it works correctly in both env.

Edited by @kirrg001
```
{{#get "posts" filter="tag:TEST"}}
```

**Comment by tiendq** [comment]
Don't we make URL to lowercase for all requests as soon as possible in routers?

**Comment by kirrg001** [comment]
> {{#get "posts" filter="tag:TEST"}}
> {{#get "posts" filter="slug:TEST"}}

It's not only about relational slugs, it's about **any slug query using uppercase notation**.
