### ISSUE TITLE
Update docs about `gscan` for Ghost devs

### ISSUE THREAD

**Issue by i8ramin** [TryGhost/Ghost#9699]
There is a bunch of documentation and blog posts floating around the internet about extending Ghost using custom Apps (ie, https://github.com/TryGhost/Ghost/wiki/Apps-Getting-Started-for-Ghost-Devs, https://www.triplet.fi/blog/using-ghost-apps-to-add-custom-handlebars-helpers-to-your-theme/)

What they all fail to inform you about (and something that took me days of frustration and head banging to finally pinpoint) is that you **cannot** add a new custom handlebar helper to Ghost using the custom apps feature (or even hacking at the Ghost core files), because the `gscan` template scanner will keep failing with the following error message (the custom helper I am trying to add is called `imgix_url`): 

```
NAME: ThemeValidationError
MESSAGE: The currently active theme "casper" is invalid.

level:normal

ERROR DETAILS:
    """
      [
      	{
      		"fatal": true,
      		"level": "error",
      		"rule": "Templates must contain valid Handlebars",
      		"details": "Oops! You seemed to have used invalid Handlebars syntax. This mostly happens, when you use a helper that is not supported.<br>See the full list of available helpers <a href=\"https://themes.ghost.org/docs/helpers\" target=_blank>here</a>.",
      		"failures": [
      			{
      				"ref": "post.hbs",
      				"message": "Missing helper: \"imgix_url\""
      			}
      		],
      		"code": "GS005-TPL-ERR"
      	}
      ]
    """
```

And this error message comes from the following linked node module:
https://github.com/TryGhost/gscan/blob/master/lib/spec.js#L9

There is also not a single mention of `gscan` anywhere in the stacktrace, so it was really difficult to track this one down. To the Ghost devs reading this, please please help make this a little easier to find and maybe also modify `gscan` to allow for **custom helpers** to be added to Ghost. 

For anyone else who is reading this, a workaround that I am going to try is to form both projects (Ghost and gscan) and modify them to allow for my custom helper functionality (which is btw, to have some [image resizing/processing capabilities](https://github.com/TryGhost/Ghost/issues/4453).)

**Comment by i8ramin** [comment]
For anyone else who finds this and wants to add a custom helper, below is the approach that I took:

- fork https://github.com/TryGhost/gscan
- modify `knownHelpers` in `lib/spec.j` and add your custom helper to the list
- modify the `package.json` file in your Ghost project and add the following section (I believe this only works with Yarn)

```
"resolutions": {
  "gscan": "github:<your name/org>/gscan"
}
```

Now your project should use the forked/modified `gscan` vs the one linked in the main Ghost package.json file.

**Comment by kirrg001** [comment]
Hey @i8ramin!

We will be creating a way to add custom helpers in future with apps - it's already tracked on our internal feature board. But for now: apps are not a thing yet and that' why you are running into this issue.

You can suggest a theme helper in our [forum](https://forum.ghost.org). We are open for any suggestions. By this we can collect together information on what helpers developers would find useful and potentially add them to core, as we did with the [reading time helper](https://github.com/TryGhost/Ghost/issues/9200) recently.

> There is also not a single mention of gscan anywhere in the stacktrace

Our theme docs has a [full page](https://themes.ghost.org/docs/gscan) for GScan.

---

I've added a note about custom theme helpers in our [theme helper docs](https://themes.ghost.org/docs/helpers).

**Comment by i8ramin** [comment]
Understood, but is there a reason to validate all custom handlebar helper and reject the built-in ones? A warning may suffice vs throwing an error and not allowing the app to build

**Comment by kirrg001** [comment]
@i8ramin Which built-in handlebars helper get's rejected?
