### ISSUE TITLE
Server was unreachable when saving posts

### ISSUE THREAD

**Issue by jsxzljx** [TryGhost/Ghost#9702]
### Issue Summary

Hi, I'm currently migrating my ghost blog to a new server.  I can visit my site normally, but **fail to save my posts** in the admin panel(domain.com/ghost). When I press `Ctrl + S`, it tells **Server was unreachable** or **missing EOF**(sometimes). The F12 interface in Chrome says 

```
PUT http://domian.com/ghost/api/v0.1/posts/5b30dd394fa567e5ab3c2d69/?include=authors,tags,authors.roles 200 (OK)
```

If I click into the URL above, it says
```
{"errors":[{"message":"Access denied.","context":"Client credentials were not provided","errorType":"UnauthorizedError"}]}
```

In my debugging process, I have tried visit my site directly through the ip address, everything works fine. However, it always fails to save posts when visiting through the domain name. I hava checked that the domain resolution is correct.

### Technical details:

* Ghost Version: 1.24.5
* Node Version: v8.11.2
* Browser/OS: Chrome 67.0
* Database: sqlite3

**Comment by ErisDS** [comment]
Hey ___  👋 We ask that you please do not use GitHub for help or support, the default issue template pointed you to our [forum](https://forum.ghost.org) for this type of question. We use GitHub solely for bug-tracking and on-going feature development so we try to keep it noise free.

Many questions can be answered by reviewing our docs for [self-hosters](https://docs.ghost.org), our [theme API](https://themes.ghost.org), or our [public API](https://api.ghost.org). If you can't find an answer then our [forum](https://forum.ghost.org) is a great place to get community support, plus it helps create a central location for searching problems/solutions.

FYI: Many projects have their own support guidelines and GitHub will highlight them for you, or the project owners will use issue templates to point you in the right direction, please read them before opening issues
