### ISSUE TITLE
home.hbs used on paged template

### ISSUE THREAD

**Issue by jloh** [TryGhost/Ghost#9708]
### Issue Summary

This seems to have happened between v1.23.0 and v1.24.5 and I assume is to do with the new dynamic routing stuff.

For some reason, if I have a `home.hbs` template in my theme and I visit a paginated page (blog.com/page/2/) instead of Ghost using `index.hbs` `home.hbs` is still rendered.

### To Reproduce

 1. Switch Ghost to use a theme that has a `home.hbs` template
 1. Have enough posts that cause Ghost to paginate
 1. Visit the second page and see `home.hbs` is still used to render everything

### Technical details:

* Ghost Version: v1.24.5 (Ghost(Pro))
* Node Version: Unsure
* Browser/OS: N/A
* Database: MySQL

**Comment by kirrg001** [comment]
@jloh This was fixed in 1.24.6. I have upgraded your blog. Let us know if it is resolved now. Thanks :)
