### ISSUE TITLE
Writing your own auth plugin

### ISSUE THREAD

**Issue by beefon** [TryGhost/Ghost#9709]
I can see there's a [auth service](https://github.com/TryGhost/Ghost/tree/192ebb1739d12c3df64188ae1470ab4b1ee71483/core/server/services/auth). Is it the one that is used to perform authentication of the existing user? I want to auth against LDAP, so if user exists in LDAP database, Ghost would let it login and create account if necessary. Are there any documentation you could provide, any hints to help with this?

**Comment by kirrg001** [comment]
Hi @beefon!

We ask that you please do not use GitHub for help or support, the default issue template pointed you to our [forum](https://forum.ghost.org) for this type of question 😄 We use GitHub solely for bug-tracking and on-going feature development so we try to keep it noise free.

Many questions can be answered by reviewing our docs for [self-hosters](https://docs.ghost.org), our [theme API](https://themes.ghost.org), or our [public API](https://api.ghost.org). If you can't find an answer then our [forum](https://forum.ghost.org) is a great place to get community support, plus it helps create a central location for searching problems/solutions.

FYI: Many projects have their own support guidelines and GitHub will highlight them for you, or the project owners will use issue templates to point you in the right direction, please read them before opening issues
