### ISSUE TITLE
Arabic translation

### ISSUE THREAD

**Issue by atefBB** [TryGhost/Ghost#9717]
When I choose the Arabic translation to display the website with, I found that the translation is not Arabic but it's Persian or Urdu (or other language written with Arabic letters).
![capture](https://user-images.githubusercontent.com/10966925/42305523-3714b396-8023-11e8-9873-046c4abe9dd1.PNG)

**Comment by AileenCGN** [comment]
Hey @atefBB 👋 

The translations are crowdsourced and there might be mistakes in there. The language code for this translations is `fa_AF`, which is indeed Farsi (Persian). See [here](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes).

You are always welcome to help us translate this correctly https://blog.ghost.org/translate-ghost-org/. I will update the language selector to show "فارسی", which should be correct now. Thanks for pointing this out!

If you have further questions, please swing by in our [forum](https://forum.ghost.org), as we keep GitHub issues only for bug tracking.

**Comment by atefBB** [comment]
Thank you.
