### ISSUE TITLE
`grunt dev` has high CPU usage when idle

### ISSUE THREAD

**Issue by kevinansfield** [TryGhost/Ghost#9718]
### Issue Summary

`grunt dev` consistently uses around 20% CPU (as measured by Activity Monitor) when idle without a Ghost restart or Ember rebuild happening.

This isn't particularly noticeable unless developing whilst on battery power.

### To Reproduce

1. Run `grunt dev`
2. Wait for the ember build to finish and everything to settle
3. Observe the `grunt` task in Activity Monitor

The same CPU usage is evident when running `grunt dev --server` which doesn't start a background ember process.

Commenting out the [express watcher](https://github.com/TryGhost/Ghost/blob/master/Gruntfile.js#L78-L85) drops idle CPU usage to 0.5% or less.

### Technical details:

* Node Version: 8.10.0
* Browser/OS: macOS
* Database: SQLite

**Comment by ErisDS** [comment]
Today https://github.com/TryGhost/Ghost/commit/26d567b948d7a89cdabcac27d730e93b3239a57a was done, which is related to this.

I think this issue needs prioritising. Every time I run `grunt dev` my laptop cooks.

**Comment by gargol** [comment]
In case the issue with high CPU usage resurfaces next optimization would be switching to [proposed above ](https://github.com/TryGhost/Ghost/issues/9718#issuecomment-402661845)watchman for file change tracking. Possible candidate for this - https://github.com/BuddyBuild/bb-grunt-watch
