### ISSUE TITLE
Safari "Post Settings" panel position bug when selecting text

### ISSUE THREAD

**Issue by fueko** [TryGhost/Ghost#9721]
### Issue Summary

The "Panel Settings" bugs when text is selected in "Post URL"

### To Reproduce

1. Open a "Post Settings"
2. Click the "Post URL" area
3. Click to select the text and drag-select to the right.

![ghost_dashboard](https://user-images.githubusercontent.com/23366922/42341639-06f16ad0-8094-11e8-8682-533dfebb701d.gif)

### Technical details:

* Ghost Version: 1.24.7
* Node Version: 8.11.1
* Browser/OS: Safari / macOS 10.13.5
* Database: SQLite

**Comment by Cavain** [comment]
@fueko That issue was not appearing on my blog. I have Version 1.24.6, I would suggest you test it on different browsers like Firefox or Opera if you're using Chrome.

**Comment by Cavain** [comment]
@fueko I just upgraded my Ghost Version: 1.24.7 to make this test again and it works fine on my blog.

**Comment by Luen** [comment]
Works fine on my blog (1.24.7) also. I'm using Google Chrome Version 67.0.3396.99 (Official Build) (64-bit)

**Comment by kevinansfield** [comment]
@Cavain / @Luen this is a Safari-specific bug. Please take note of the browser mentioned in the "Technical details" section of bug reports when trying to reproduce 🙂

**Comment by jtwebman** [comment]
I just tried to re-create the issue on Ghost version 2.0.3 in the latest Safari with no issues.
