### ISSUE TITLE
Markdown http instead of https

### ISSUE THREAD

**Issue by TigPT** [TryGhost/Ghost#9723]
### Markdown show http instead of https

The web is going pedal to the metal to https and I think http is becoming deprecated (or we should try to), so it make sense that in the code editor and shortcuts templates it show https instead of http for Ctrl/⌘ + K [title](http://) and Ctrl/⌘ + Shift + I ![alt](http://)

What do you guys think?

**Comment by kevinansfield** [comment]
@TigPT as explained in the issue templates all feature requests should be directed to the [Ideas category on the forum](https://forum.ghost.org/c/Ideas/l/votes).

That said, the editor is [being replaced](https://forum.ghost.org/t/koenig-editor-beta-release/1284) and those shortcuts will be disappearing or working in a very different way.
