### ISSUE TITLE
Federate over ActivityPub

### ISSUE THREAD

**Issue by drequivalent** [TryGhost/Ghost#9731]
With ActivityPub protocol being accepted a W3C standard, I don't see a reason why a self-hosted blogging platform wouldn't implement it.
Implementing ActivityPub in Ghost will bring following benefits to its users:

1) it will interconnect all Ghost instances into a cohesive network - self-hosted instances will no more be lonely places!;
2) it will allow Ghost to become a part of a wide social network of free and open-source self-hosted applications (like Mastodon, Pleroma, PeerTube, Plume, Hubzilla, soon GNUSocial and Friendica and a lot of others). Mastodon alone brings at least 1000000 (a million) of users with its at least 4801 instances (as seen on https://mnm.social/);
3) Ghost itself will become more popular in consequence of 1 and 2.

Come join the fun!

**Comment by kirrg001** [comment]
Hi @drequivalent!

Thanks for the idea!

We only keep Github issues open for bugs and in-progress feature work. Please check out [our forum](https://forum.ghost.org) to see if your suggested idea already exists, so you can upvote it, or post this idea in the features section for other users to see and upvote.

**Comment by herbsmn** [comment]
Looks like this was done recently? https://github.com/TryGhost/Ghost/pull/15812

**Comment by Reedyn** [comment]
@herbsmn posting to an account is not the same as federating over ActivityPub
