### ISSUE TITLE
Has statement not evaluating correctly

### ISSUE THREAD

**Issue by philskents** [TryGhost/Ghost#9732]
I have the following in my header.hbs partial

```
<header id="masthead">
{{#post}}
    {{#has slug=../menu}}
        <div id="masthead-title"><a href="/"><h1>{{@blog.title}}</h1></a></div>
        <div id="masthead-menu"><a href="/menu"><h1>X</h1></a></div>
    {{else}}
        <div id="masthead-title"><a href="/"><h1>{{@blog.title}}</h1></a></div>
        <div id="masthead-menu"><a href="/menu"><h1>Menu</h1></a></div>
    {{/has}}
{{/post}}
</header>
```

However when I visit the /menu page in my dev site (http://localhost:2368/menu/) it presents me with the second set of div's, not the first set as it should be.

**Comment by kirrg001** [comment]
Hi @philskents!

We ask that you please do not use GitHub for help or support, the default issue template pointed you to our [forum](https://forum.ghost.org) for this type of question 😄 We use GitHub solely for bug-tracking and on-going feature development so we try to keep it noise free.

Many questions can be answered by reviewing our docs for [self-hosters](https://docs.ghost.org), our [theme API](https://themes.ghost.org), or our [public API](https://api.ghost.org). If you can't find an answer then our [forum](https://forum.ghost.org) is a great place to get community support, plus it helps create a central location for searching problems/solutions.

FYI: Many projects have their own support guidelines and GitHub will highlight them for you, or the project owners will use issue templates to point you in the right direction, please read them before opening issues
