### ISSUE TITLE
Headless Ghost

### ISSUE THREAD

**Issue by MishUshakov** [TryGhost/Ghost#9734]
Hi, I have a feature request: can you please add Labs option, which will disable templates and instead redirect to a external website
We want to make a news website based on Ghost, but we doesn't want to write templates for it, instead, just use it as API for our Apps & Websites. Would be really handy, thanks!

**Comment by AileenCGN** [comment]
Hi @MishUshakov 

Thanks for the idea!

We only keep Github issues open for bugs and in-progress feature work. Please check out [our forum](https://forum.ghost.org) to see if your suggested idea already exists, so you can upvote it, or post this idea in the features section for other users to see and upvote.
