### ISSUE TITLE
Use local jQuery instead of CDN

### ISSUE THREAD

**Issue by theel0ja** [TryGhost/Ghost#9745]
All other scripts are downloaded locally (such as jquery.fitvids.js), so why not jQuery itself?

Advantages:
* Works offline
* No requests to third-parties
* Maybe privacy?

**Comment by acburdine** [comment]
@theel0ja I'm assuming you're talking about jQuery that's used in Casper, making this issue more appropriate for the [Casper repo](https://github.com/TryGhost/Casper); therefore, I'm going to close this.

For what it's worth, there's already an [issue open](https://github.com/TryGhost/Casper/issues/409) there about replacing jQuery & fitvids with an approach that doesn't require jQuery at all.
