### ISSUE TITLE
[feature request] Allow ghost to sort posts reversed (oldest = first) or sort posts in any way for teh matter

### ISSUE THREAD

**Issue by Prozi** [TryGhost/Ghost#9758]
[feature request]

* Allow ghost to sort posts reversed (oldest = first)

* or sort posts in any way for teh matter

plz plz would it be possible in any easy way?

**Comment by kevinansfield** [comment]
Hey @Prozi 👋 We ask that you please do not use GitHub for feature requests, the default issue templates pointed you to our [forum](https://forum.ghost.org) for this type of question - the [Ideas](https://forum.ghost.org/c/Ideas) topic will let you propose features and let others vote on them 😄. We use GitHub solely for bug-tracking and on-going feature development so we try to keep it noise free.

FYI: Many projects have their own support guidelines and GitHub will highlight them for you, or the project owners will use issue templates to point you in the right direction, please read them before opening issues.

**Comment by Prozi** [comment]
thanks I will ask on forum <3
