### ISSUE TITLE
Ajax call from external website - Response 200 but no posts

### ISSUE THREAD

**Issue by c0derabbit** [TryGhost/Ghost#9760]
### Issue Summary

I’d like to fetch blog posts into my website client-side.
When I fetch posts, I get this response, and no response body:

```
ok: true
redirected: false
status: 200
statusText: "OK"
type: "cors"
url: "http://my_website/ghost/api/v0.1/posts/?limit=3&client_id=ghost-frontend&client_secret=MY_SECRET
```

### To Reproduce

1. Follow this guide: https://api.ghost.org/docs/ajax-calls-from-an-external-website
2. Try to fetch posts from an external website.

Expected behaviour is to get a list of posts. When I `curl` it works fine.

### Technical details:

* Ghost Version:  1.25.1
* Node Version: 6.14.3
* Browser/OS: Chrome 67.0.3396.99 on the client, backend running on Ubuntu 16.04.5 (aws ec2 t2.micro)
* Database: mysql

Thanks for looking into it :)

**Comment by kevinansfield** [comment]
Hey @c0derabbit 👋 We ask that you please do not use GitHub for help or support, the default issue template pointed you to our [forum](https://forum.ghost.org) for this type of question 😄 We use GitHub solely for bug-tracking and on-going feature development so we try to keep it noise free.

Many questions can be answered by reviewing our docs for [self-hosters](https://docs.ghost.org), our [theme API](https://themes.ghost.org), or our [public API](https://api.ghost.org). If you can't find an answer then our [forum](https://forum.ghost.org) is a great place to get community support, plus it helps create a central location for searching problems/solutions.

FYI: Many projects have their own support guidelines and GitHub will highlight them for you, or the project owners will use issue templates to point you in the right direction, please read them before opening issues

**Comment by c0derabbit** [comment]
Hi @kevinansfield, I started there but no response, also it seems to me more like a bug than a question, as I did follow the instructions, and I suspect it's either not working as it should, or there's a missing step in the docs.
