### ISSUE TITLE
Cannot send email via SES unless it has been verified

### ISSUE THREAD

**Issue by kash** [TryGhost/Ghost#9770]
**Issue Summary**
Inviting a teammate when using AWS SES does not work as expected. Ghost expects me to add every user's email to the list of verified emails in the AWS SES dashboard. If I don't, I get this error message when I try to invite someone: `Error sending email: Failed to send email. Reason: Email address is not verified. The following identities failed the check in region US-EAST-1: teammate@example.com. Please check your email settings and resend the invitation.`

**To Reproduce**
1. Set up Ghost on a Digital Ocean Ubuntu server
2. Add SES mail configuration to /var/www/ghost/config.production.json
```
  "mail": {
      "from": "'Example' <test@example.com>",
      "transport": "SES",
      "options": {
           "AWSAccessKeyID": "xyz",
           "AWSSecretKey": "xyz"
      }
  },
```
3. Restart ghost
4. Go to team settings and invite teammate via email
5. Get this error: `Error sending email: Failed to send email. Reason: Email address is not verified. The following identities failed the check in region US-EAST-1: teammate@example.com. Please check your email settings and resend the invitation.`

Note: This was the case when I tried to send myself a test email under the Labs tab. It said your email is not verified. I added my email to the AWS SES dashboard and it was able to send the email.

**Expected Behavior**
Only the email that I will be sending emails _from_ should need to be verified. Any email that I'm sending _to_ shouldn't have to be verified.

**Technical details:**
* Ghost Version: 1.8.1
* Node Version: 6.14.3
* Browser/OS: Chrome/macOS
* Database: MySQL

**Comment by kirrg001** [comment]
This looks like a restriction of amazon SES sandbox. See [link](https://docs.aws.amazon.com/ses/latest/DeveloperGuide/request-production-access.html).

**Comment by kirrg001** [comment]
Please us our [forum](https://forum.ghost.org) for further questions. 
If it turns out there is a bug in Ghost, we can re-open this issue.
