### ISSUE TITLE
Fixture adjustments

### ISSUE THREAD

**Issue by JohnONolan** [TryGhost/Ghost#9774]
Couple of additions to the default settings fixtures:

## Social Accounts
- `{{@blog.twitter}}` - `https://twitter.com/tryghost`
- `{{@blog.facebook}}` - `https://www.facebook.com/ghost`

## Design/Navigation
- **Home** - `{{@blog.url}}` _(already exists)_
- **Tag** - `{{@blog.url}}/tag/getting-started/`
- **Author** - `{{@blog.url}}/author/ghost/`
- **Help** - `https://help.ghost.org`

## Ghost User
- `{{author.twitter}}` - `https://twitter.com/tryghost`
- `{{author.facebook}}` - `https://www.facebook.com/ghost`
- `{{author.location}}` - `The Internet`
- `{{author.website}}` - `https://ghost.org`
- `{{author.bio}}` - `You can delete this user to remove all the welcome posts` _(already exists)_

(Optional, but would be nice:)

Set default `{{author.profile_image}}` for Ghost user - should look like https://demo.ghost.io/author/ghost/ - it's fine to add this image file to Ghost core, don't need to load remotely, if that's easier.

![image](https://user-images.githubusercontent.com/120485/43906054-4458f854-9bea-11e8-80ae-e57f4d9dc5fd.png)

**Comment by kirrg001** [comment]
Closed via https://github.com/TryGhost/Ghost/commit/f4e9563f94e70e53e51fc789406c9424bfe54063. This is part of the Ghost 2.0 branch.
