### ISSUE TITLE
Incorrect use of meta description in content management screen

### ISSUE THREAD

**Issue by JohnONolan** [TryGhost/Ghost#9775]
On the content management overview screen in Ghost Admin, the excerpt for each post is populated by a cascade of:

`Meta Description` => `Auto Excerpt`

it _should_ be using

`Custom Excerpt` => `Auto Excerpt`

**Comment by damanm24** [comment]
Hey, I'm a newbie to the ghost platform, but I'd love to take a look at this issue! Would you be able to provide me with a little more context for this issue? For example, how I can recreate the issue or observe the behavior that you pointed out.

**Comment by wdifruscio** [comment]
hi there, attempting to fix this in https://github.com/TryGhost/Ghost-Admin/pull/1038
The build is failing but I believe it was like this before me

**Comment by TonnyORG** [comment]
@JohnONolan Fixing this one here: TryGhost/Ghost-Admin#1052 😄
