### ISSUE TITLE
Koenig - Open links in new tab

### ISSUE THREAD

**Issue by tomkerkhove** [TryGhost/Ghost#9776]
Is there a way to configure to open links in a new tab when using the new Koenig editor?

**Comment by kirrg001** [comment]
Hi @ @tomkerkhove 👋

We ask that you please do not use GitHub for help or support, the default issue template pointed you to our [forum](https://forum.ghost.org) for this type of question 😄 We use GitHub solely for bug-tracking and on-going feature development so we try to keep it noise free.

**Comment by tomkerkhove** [comment]
Well from what I've seen it's not there hence the feature request, but maybe the wording was wrong.

Will post it over there and create a new issue if need be.

**Comment by ErisDS** [comment]
As stated in the issue template picker, and in the issue template which you deleted when you originally wrote your issue, and already explained by Kate, we use GitHub solely for bug reports. Feature requests belong on https://forum.ghost.org/c/ideas.
