### ISSUE TITLE
Koenig - Full markdown view

### ISSUE THREAD

**Issue by tomkerkhove** [TryGhost/Ghost#9777]
Is there a way to get a full markdown view/editor experience in Koenig?

**Comment by kirrg001** [comment]
Hi @ @tomkerkhove 👋

We ask that you please do not use GitHub for help or support, the default issue template pointed you to our [forum](https://forum.ghost.org) for this type of question 😄 We use GitHub solely for bug-tracking and on-going feature development so we try to keep it noise free.

**Comment by tomkerkhove** [comment]
Well from what I've seen it's not there hence the feature request, but maybe the wording was wrong.

Will post it over there and create a new issue if need be.
