### ISSUE TITLE
breadcrumbs feature?

### ISSUE THREAD

**Issue by turalus** [TryGhost/Ghost#9783]
it might seem a bit off topic but, I couldn't find any other place to ask my question.

Is there any breadcrumbs feature available or will it be in future?

**Comment by ErisDS** [comment]
The issue template that you deleted to write this mentioned https://forum.ghost.org multiple times. Please use the forum. Github is for bug reports only.

**Comment by warlockeg** [comment]
@ErisDS This is a bug honey, it is a blog script that does not have breadcrumbs, that is a bug, very big bug, bigger than your CTO position at Ghost!
Stop hiring white people please!
