### ISSUE TITLE
Editor: Link toolbar position is unreachable for wrapped links

### ISSUE THREAD

**Issue by kevinansfield** [TryGhost/Ghost#9792]
### Issue Summary

If you have a multi word link that wraps across two lines, the link hover toolbar can be positioned too far away from the mouse cursor for it to be reachable because it will disappear when the cursor leaves the link.

<img width="769" alt="screen shot 2018-08-16 at 14 00 42" src="https://user-images.githubusercontent.com/415/44210122-8f1ef000-a15d-11e8-8fe6-e3fe85b673bf.png">

This might be a tricky one to resolve because the browser only exposes a rectangle that covers all parts of the link. It may be that we need to position the toolbar based on the cursor position but that position will need to be shared between the hover and link input toolbars to avoid jumping UI when switching states.

### Technical details:

* Ghost Version: 2.0.0

**Comment by kevinansfield** [comment]
Not stale

**Comment by kevinansfield** [comment]
Not stale

**Comment by tvld** [comment]
Maybe use a two step approach? Whenever the cursor hovers the link, show a small "pencil" icon at the end of the link, always reachable as it is directly connected to the div. Clicking on that pencil would show a persistent popup, that you need to close by clicking a [x] or an edit action.

**Comment by kevinansfield** [comment]
> show a small "pencil" icon at the end of the link

This is the problem, there's no "end of the link" for wrapped links, the DOM only gives you a measurable rectangle that is the full width of the editing canvas with a height that covers how ever many lines the link breaks across. However, as soon as the mouse is moved off of the text (not the rectangle) the associated mouse events fire which clears the popup.

Positioning based on the cursor position I think is the only workable route here without getting into a lot of complex text measuring.

Happy to hear about alternative ways of solving that though!

**Comment by tvld** [comment]
Yeah... tricky.
Maybe use a css ``:after`` selector on the link and accept the click on the div _only_ if the cursor is above this selector?

**Comment by kevinansfield** [comment]
I'm not sure how that helps? The bounding box for the link doesn't change, it's still a full-width multi-line height rectangle so you don't get any better positioning with an `:after` element. Pseudo elements are also invisible to JS because they are not in the DOM so they don't buy you anything on the interaction side.

**Comment by tvld** [comment]
Maybe like this?:  https://jsfiddle.net/jwuh0xpy/12/

**Comment by kevinansfield** [comment]
@tvld I discovered `element.getClientRects()` which gives you a collection of rectangles representing each line of the link range. Not sure how I missed that before 🤔 Anyway, it helped a lot with being able to position the toolbar based on the mouse position within the link. Fix pushed to master

**Comment by tvld** [comment]
@kevinansfield   That's a good find. At least there are some options to explore a solution... )
