### ISSUE TITLE
Editor: Intermittent embed card loading issues

### ISSUE THREAD

**Issue by kevinansfield** [TryGhost/Ghost#9796]
### Issue Summary

Sometimes 3rd party scripts in embeds do not load correctly. The issue is intermittent, sometimes occurring immediately on insertion or when the embed component is re-rendered. Typically the embed that has failed will work when re-opening the post.

The issue has been most noticeable with Instagram and Twitter embeds.

![](https://user-images.githubusercontent.com/120485/43796868-673f5142-9a7d-11e8-86d7-af1412aaa77c.png)

![](https://user-images.githubusercontent.com/120485/43797214-904e87dc-9a7e-11e8-8b7f-120fbe6fb8d0.png)

### To Reproduce

1. Use instagram or twitter embeds heavily, the problem should show up at some point

### Technical details:

It's possible that our [image resize mutationobserver](https://github.com/TryGhost/Ghost-Admin/blob/master/lib/koenig-editor/addon/components/koenig-card-embed.js#L204-L272) is interfering with the 3rd party scripts.

* Ghost Version: 2.0.0
* Browser/OS: Chrome / macOS

**Comment by lunaticmonk** [comment]
@kevinansfield Seems the embeds stabilize after some time. I am not sure if in your case they remain as shown in the screenshots. However, I tried throttling the internet speed. With slow internet speed, it may happen that the embeds appear as shown in screenshots at first and stabilize in a moment and appear fine. Plus I don't see any errors in console. Can you confirm?

**Comment by kevinansfield** [comment]
@lunaticmonk as mentioned in the issue this is intermittent, it may/may not happen on each render of the embed card. My current hypothesis is that there's a timing issue somewhere in the render which is causing the scripts in the iframe not to run, or that they are running but Ember's rendering replaces the contents that have been modified by the scripts, in either case I wouldn't expect there to be an error in DevTools console.

**Comment by kevinansfield** [comment]
> With slow internet speed, it may happen that the embeds appear as shown in screenshots at first and stabilize in a moment and appear fine.

This is expected, it's how the embeds works and is unrelated to this issue. HTML that we get from the oembed endpoint is displayed in an iframe, for services such Instagram, Facebook posts, etc this includes a `<script>` tag that recognises the HTML and transforms it into a full embed in the same way as when you copy/paste the embed HTML directly from the 3rd party sites.
