### ISSUE TITLE
Support for Cloudinary in new editor

### ISSUE THREAD

**Issue by tpiros** [TryGhost/Ghost#9797]
As a feature request, it'd be great to see a support for Cloudinary in the new Koenig editor. Cloudinary is a cloud based image / video (media) management solution - it'd be great if we could easily add images from Cloudinary to the blog posts. Cloudinary also delivers images and video in an optimised way so there's no need to manually crop/resize/transform/optimise images.

**Comment by kevinansfield** [comment]
Hey @tpiros 👋 We ask that you please do not use GitHub for feature requests, the default issue templates pointed you to our [forum](https://forum.ghost.org) for this type of question - the [Ideas](https://forum.ghost.org/c/Ideas/l/votes) topic will let you propose features and let others vote on them 😄. We use GitHub solely for bug-tracking and on-going feature development so we try to keep it noise free.

FYI: Many projects have their own support guidelines and GitHub will highlight them for you, or the project owners will use issue templates to point you in the right direction, please read them before opening issues.
