### ISSUE TITLE
Unable to load all available themes

### ISSUE THREAD

**Issue by zce** [TryGhost/Ghost#9799]
### Issue Summary

![](https://user-images.githubusercontent.com/6166576/44300179-60f40880-a335-11e8-9905-c61ee6bb3dbe.png)

Unable to load all available themes. 

I found that `GhostServer.announceServerStart()` was not invoked when `dbState != 4`, Cause the `server.start` event not to emit.

### To Reproduce

1. Using Ghost as an NPM module
2. Add a validated theme `creative`
3. GhostAdmin → Design → Themes

### Technical details:

* Ghost Version: v2.0.0 (as npm module)
* Node Version: v8.11.3
* Database: SQLite3

**Comment by zce** [comment]
I know why.

I finished my `index.js` according to the [ghost docs](https://docs.ghost.org/docs/using-ghost-as-an-npm-module#section-create-an-index-js-file).

```js
const ghost = require('ghost')

ghost().then(server => server.start())
```

so `GhostServer.announceServerStart()` was not invoked.

I think the ghost docs should be updated.

**Comment by kirrg001** [comment]
Thanks for your report!

I have updated the Ghost 2.0 docs for "Using Ghost as an npm module" for now. The updated docs should make it possible to install Ghost 2.0 via NPM.

We will ship a better way to announce the server start asap. I am closing this issue for now and i'll raise a new issue tomorrow morning.
