### ISSUE TITLE
SVG Image Upload to Stored Cross-site scripting

### ISSUE THREAD

**Issue by snoopysecurity** [TryGhost/Ghost#9800]
### Issue Summary

Ghost platform is vulnerable to Stored Cross-site scripting via SVG file uploads.

Scalable Vector Graphics (SVG) can be used to define vector-based graphics within a webpage. SVG can be mixed with HTML content, as well as XML namespaces. SVG can be used to create interactivity within a webpage and perform animations.
It should be noted that even though the MIME type for an SVG image is image/svg+xml. It is possible to store JavaScript code within an SVG document and execute it if viewed directly within a web browser. An example proof on concept for this can be seen below
```
<svg version="1.1" baseProfile="full" xmlns="http://www.w3.org/2000/svg">
    <circle cx="50" cy="50" r="40" stroke="black" stroke-width="3" fill="red" />
   <script type="text/javascript">
      alert(document.domain);
      alert(document.location);
   </script>
</svg>
```
### To Reproduce

1. Create a new post within you Ghost blog
2. Instead of uploading a jpeg file, upload the above SVG document as a .svg file and then publish the new post
3. Once published, go to your post and copy the image location of rendered SVG file

![alt text](https://snoopysecurity.github.io/6.PNG "Logo Title Text 1")

Cross Site Scripting (XSS) allows clients to inject arbitrary scripting code into aapplication and have the server return the script to the client in the response. This occurs because the application is taking untrusted data (in this example, as form of a SVG file) and storing it without performing any validation or encoding.

**Comment by vikaspotluri123** [comment]
This isn't the correct method to report security vulnerabilities. Please take a look at the [security documentation](https://github.com/TryGhost/Ghost/blob/master/SECURITY.md)

**Comment by vikaspotluri123** [comment]
If you can, please edit the issue to hide the vulnerability, and remove the edit Github stores

**Comment by abdilahrf** [comment]
thanks for this issue i know the vuln 👍 haha
