### ISSUE TITLE
Editor: Move markdown editor into Koenig, lazy load dependencies

### ISSUE THREAD

**Issue by kevinansfield** [TryGhost/Ghost#9804]
In Ghost 2.0 the SimpleMDE based markdown editor is only used by the markdown card in the new Koenig editor.

We can use this opportunity to move the markdown related components into the `koenig-editor` in-repo-addon and also to lazy-load the SimpleMDE dependency to speed up initial admin loading time.

Components:
- [gh-markdown-editor](https://github.com/TryGhost/Ghost-Admin/blob/master/app/components/gh-markdown-editor.js)
- [gh-simplemde](https://github.com/TryGhost/Ghost-Admin/blob/master/app/components/gh-simplemde.js)
- [modal-markdown-help](https://github.com/TryGhost/Ghost-Admin/blob/master/app/components/modal-markdown-help.js)

Utils:
- [format-markdown](https://github.com/TryGhost/Ghost-Admin/blob/master/app/utils/format-markdown.js)

For the first iteration it would be good to only lazy-load the SimpleMDE dependency rather than also the `markdown-it` dependency - we'd like for the rendered markdown content to be displayed immediately whereas the SimpleMDE load can be triggered when first switching to the edit view of a markdown card.

Lazy-loading could be achieved either through our existing [lazy-loader](https://github.com/TryGhost/Ghost-Admin/blob/master/app/services/lazy-loader.js) service or possibly using the dynamic loading functionality of [ember-auto-import](https://github.com/ef4/ember-auto-import).

TODO:
- [ ] move all associated components into `koenig-editor`
- [x] lazy-load simplemde using existing `lazy-loader` service

**Comment by NoobTW** [comment]
Is there an option to make Markdown as a default editor? Default Markdown editor is the first reason I migrated to Ghost.
