### ISSUE TITLE
Editor: <video> element size is not constrained

### ISSUE THREAD

**Issue by kevinansfield** [TryGhost/Ghost#9808]
### Issue Summary

When using `<video>` elements in a HTML card their width is not constrained to the editor width.

![image 1](https://user-images.githubusercontent.com/415/44398361-7fc3ec00-a53b-11e8-8cbd-346c90bae8fe.png)

### To Reproduce

1. Use a html card to add a `<video>` element with a large video

### Technical details:

* Ghost Version: 2.0.2
* Browser/OS: Chrome / macOS

**Comment by lunaticmonk** [comment]
@kevinansfield 
![image](https://user-images.githubusercontent.com/17925669/44415994-69e01680-a58f-11e8-932b-1b76e3395096.png)

Did you mean something like this?

**Comment by kevinansfield** [comment]
Yes, it just needs a `max-width: 100%` applied but this needs to occur in our Spirit CSS library which isn't public yet. We'll tackle this issue before the next release.

**Comment by kevinansfield** [comment]
Closed via https://github.com/TryGhost/Ghost-Admin/pull/1039
