### ISSUE TITLE
Editor: Add Gist embedding support

### ISSUE THREAD

**Issue by championswimmer** [TryGhost/Ghost#9817]
Currently using the Github embed snippet works, but it would be awesome if we could just paste the Gist URL into the editor and it embedded it. 

Embed.ly supports Gists, and this Medium works like this (just paste and it works). 
It will be awesome if Ghost 2.0 supported this too.

**Comment by kirrg001** [comment]
Hi @championswimmer!

Thanks for the idea!

We only keep Github issues open for bugs and in-progress feature work. Please check out [our forum](https://forum.ghost.org) to see if your suggested idea already exists, so you can upvote it, or post this idea in the features section for other users to see and upvote.
