### ISSUE TITLE
Typo in the docs about using ghost as npm module

### ISSUE THREAD

**Issue by nehalist** [TryGhost/Ghost#9823]
There's a colon instead of a semicolon in the example `index.js` on https://docs.ghost.org/docs/using-ghost-as-an-npm-module:

```
const ghost = require('ghost');

ghost()
    .then(function (ghostServer) {
        return ghostServer.start();
    }):
//    ^
```

**Comment by kirrg001** [comment]
Thanks! I'll fix that!

You can suggest edits next time - there is a button on top right 👍
