### ISSUE TITLE
Low-weight fonts in ghost admin are unreadable

### ISSUE THREAD

**Issue by KopfKrieg** [TryGhost/Ghost#9824]
I've got the same problem that is mentioned in [issue #8136](https://github.com/TryGhost/Ghost/issues/8136) already, but with the Cantarell font.

It seems Cantarell features a separate light/low-weight font, which is nearly unreadable if used with a font-weight <= 300. Removing the Cantarell font from the list of fonts solves the problem for me (Droid Sans is then used as fallback).

Technical details:
 - Ghost Version: 2.0.3
 - Browser/OS: Firefox 61 on Arch Linux
 - Display: LG Flatron W2361V @ 1920x1080 / 24" (92 dpi)
 - Font family used: Cantarell

**Comment by pascalandy** [comment]
Screenshot? 
Which OS are you running on?

**Comment by KopfKrieg** [comment]
Operating System is Arch Linux, Desktop Environment is Gnome Shell (which uses Cantarell as default font).

Here's a screenshot showing a barely readable Cantarell font (other applications using Cantarell are fine):

![cantarell](https://user-images.githubusercontent.com/5047813/45367053-a3310280-b5e0-11e8-9728-0b67a0638127.png)

And disabling Cantarell in favour of Droid Sans:

![droid-sans](https://user-images.githubusercontent.com/5047813/45367108-c65bb200-b5e0-11e8-9468-06c3e2b0b220.png)

I think the contrast is, in general, to low, but using Cantarell as font makes it nearly unreadable on my system.

**Comment by kevinansfield** [comment]
@peterzimon do you have any objections to removing Cantarell from our font stack?

**Comment by KopfKrieg** [comment]
FYI: Switching Cantarell and Droid Sans would be enough for me (so that Droid Sans is preferred)

**Comment by peterzimon** [comment]
@kevinansfield I'm okay with removing Cantarell

**Comment by peterzimon** [comment]
ref. https://github.com/TryGhost/Ghost-Admin/commit/8f4246e3b661759de4d776bcd33dc16a20f89521

**Comment by KopfKrieg** [comment]
Thank you :)
