### ISSUE TITLE
Getting the "Saving failed! Someone else is editing this post." error but no-one else is editing. 

### ISSUE THREAD

**Issue by chrissainty** [TryGhost/Ghost#9841]
### Issue Summary
Since upgrading to Ghost 2.x everytime I am writing a post have had the editor open for over 30mins I start to get the above error message. I then have to copy everything I have written and navigate back to the Stories list and then back to my blog post and re-paste my work. 

The dev tools in chrome show the following error:

```
Failed to load resource: the server responded with a status of 409 ()
``` 
When I click on the link attached to the error I get the following JSON:

```
{"errors":[{"message":"Access denied.","context":"Client credentials were not provided","errorType":"UnauthorizedError"}]}
```

### To Reproduce

Seems to happen whenever I'm in the post editor for greater than 30 minutes.

### Technical details:

* Ghost Version: 2.0.3 (docker image)
* Browser/OS: Chrome 68.0.3440.106 / macOS High Sierra
* Database: Sqlite 3

**Comment by kirrg001** [comment]
I am closing this issue. It's 3 months old.

Feel free to re-open or leave a comment here if it's still a problem.

**Comment by zdimension** [comment]
Ghost 5.1.0, SQLite 3 on Debian 10, having this problem too. Open a post for too long, and you can't save anymore. Restarting Ghost doesn't fix, only way around this is to copy-paste the content in a notepad, refresh, and paste. Really annoying.

**Comment by ErisDS** [comment]
The logic that determines this is the case, is if the post on the server has a newer updated_at timestamp than your local copy. So if you opened a new tab and edited a detail of the post, or if someone else has edited the post and closed it, then this error will occur.

The reason it happens is to prevent your save from overwriting the changes. You're correct that the only solution is to open a fresh tab with the latest copy of post, and copy across your changes.

Please note: as of Ghost 5.0 sqlite3 is no longer a supported DB in production.

**Comment by zdimension** [comment]
The logic is sound, however it doesn't handle the (rare, but possible) case where the server timeouts on the update request. What happens in my case is that the update is indeed saved, but the requests timeouts for the client, so the client doesn't get the updated timestamp. If this happens (and it happens), all the changes after the initial request (which, since it timed out, can be tens of seconds or even minutes in the past) are lost. The new fix I found is to simply replay the request with CURL, and manually changing the timestamp to match the server's.

**Comment by kimadactyl** [comment]
ive had this happen twice on my ghost 5 site - not sure how to report it properly as its happening to non-technical authors?
