### ISSUE TITLE
Pre-fetching all resources slowing down Ghost a lot

### ISSUE THREAD

**Issue by doanchu** [TryGhost/Ghost#9842]
Is there any way to disable pre fetching resources at bootstrap? My Ghost setup has 1 million posts and it is very slow to start and there is just not enough memory to store all those resources.
--------------^ Click "Preview" for a nicer view!

We use GitHub only for bug reports 🐛

Anything else should be posted to https://forum.ghost.org 👫.

🚨For support, help & questions use https://forum.ghost.org/c/help
💡For feature requests & ideas you can post and vote on https://forum.ghost.org/c/Ideas

Alternatively, check out these resources below. Thanks! 😁.

- [Forum](https://forum.ghost.org/c/help)
- [Theme Support](https://forum.ghost.org/c/themes)
- [Theme Docs](http://themes.ghost.org/)
- [API Docs](https://api.ghost.org/)
- [Feature Requests / Ideas](https://forum.ghost.org/c/Ideas)
- [Contributing Guide](https://docs.ghost.org/docs/contributing)
- [Self-hoster Docs](https://docs.ghost.org/)

**Comment by ErisDS** [comment]
Closing as this belongs on the forum and was raised here: https://forum.ghost.org/t/why-is-ghost-pre-fetching-all-the-resources-at-bootstrap/2823
