### ISSUE TITLE
Admin prompts for 2.0 upgrade even after upgrade to 2.1

### ISSUE THREAD

**Issue by martygriffin** [TryGhost/Ghost#9844]
### Issue Summary

I upgrade/migrated my site from 1.x to 2.x recently. When I login to my ghost admin, it still says I need to upgrade. When I check the version using the ghost cli, it says 2.1

### To Reproduce

1. Migrate a site from ghost 1.x to 2.x
2. Open the ghost admin client

Expected Result: The user is taken to the new ghost 2.x admin client

Actual Result: The user is taken to the 1.x admin with an upgrade message

<img width="1413" alt="screen shot 2018-09-02 at 4 57 07 pm" src="https://user-images.githubusercontent.com/2836347/44962206-835b5980-aed1-11e8-8016-de2d8ed107c8.png">

### Technical details:

* Ghost Version: 2.1
* Node Version: 8.9
* Browser/OS: Chrome/OSX
* Database: SQLite

**Comment by martygriffin** [comment]
n/a, caching issue.

**Comment by ohpreis** [comment]
How did you resolve that? I have the same issue.

**Comment by martygriffin** [comment]
I cleared my browser cache and clicked the "x" on the upgrade message. I have the new editor so the upgrade was successful.

**Comment by ohpreis** [comment]
Thanks I will give this a try. Appreciated!
