### ISSUE TITLE
Unable to start Ghost after adding NewRelic

### ISSUE THREAD

**Issue by blueelvis** [TryGhost/Ghost#9845]
### Issue Summary

I have the Ghost v2.0.2 and installing NewRelic doesn't seem to work. After following the below steps, I start getting 502 and ghost cli stays in "Starting Ghost".

### To Reproduce

1. `cd` to ghost directory
2. `cd` to `current`
3. `npm install newrelic`
4. `cp node_modules/newrelic/newrelic.js newrelic.js`
5. Add Newrelic license key in newrelic.js
6. Add `require('newrelic.js');` to `index.js`
7. Run `ghost restart`

### Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?
I expected that Ghost will start running and I am able to view metrics in NewRelic

### Technical details:

* Ghost Version: 2.0.2
* Node Version: 8.11.3
* Browser/OS: Ubuntu 16.04 LTS
* Database: sqlite3

**Comment by ErisDS** [comment]
Hey @blueelvis  👋 We ask that you please do not use GitHub for help or support, the default issue template pointed you to our [forum](https://forum.ghost.org) for this.  We use GitHub solely for bug-tracking and on-going feature development so we try to keep it noise free.

FYI: Many projects have their own support guidelines and GitHub will highlight them for you, or the project owners will use issue templates to point you in the right direction, please read them before opening issues

**Comment by blueelvis** [comment]
@ErisDS - Hey Hannah! My bad on this. I was able to resolve this issue but couldn't figure if this is a bug or a support request.

I fixed this issue by reinstalling the modules. Although, I noticed that in case of damaged modules, the above holds true that is "Starting Ghost" stays there without any error. Not sure if this is categorized as bug.

Thanks!

**Comment by blueelvis** [comment]
@acburdine - Thanks Austin for the clarification! Yea, I am aware that whenever I update my Ghost installation, I would have to add the NewRelic configuration again. 

Is there any plan to add NewRelic by default?
