### ISSUE TITLE
Use Duo Authentication to add to login

### ISSUE THREAD

**Issue by currentinfo1** [TryGhost/Ghost#9861]
1. Would you consider adding 2FA and/or Duo (Preferred) to protect the admin page?

- Duo authentication works really well with wordpress

Reference - https://duo.com/

**Comment by gargol** [comment]
Hey @currentinfo1 👋 We ask that you please do not use GitHub for feature requests, the default issue templates pointed you to our [forum](https://forum.ghost.org) for this type of question - the [Ideas](https://forum.ghost.org/c/Ideas/l/votes) topic will let you propose features and let others vote on them 😄. We use GitHub solely for bug-tracking and on-going feature development so we try to keep it noise free.

FYI: Many projects have their own support guidelines and GitHub will highlight them for you, or the project owners will use issue templates to point you in the right direction, please read them before opening issues.
