### ISSUE TITLE
Regression: Invitation signup form

### ISSUE THREAD

**Issue by JohnONolan** [TryGhost/Ghost#9868]
Ghost 2.x on Pro

When signing up by invitation, pressing enter in the password box does nothing. (also nothing in console)

Aside: When you eventually do click on the button manually - the form doesn't correctly trigger 1Password. So now I have no idea what password I set :( 

![image](https://user-images.githubusercontent.com/120485/45485344-908d0980-b757-11e8-987a-39d77586929f.png)

**Comment by kevinansfield** [comment]
Re-opening. Attempted signup in latest Safari and two passwords were saved - one with my e-mail (wrong password) and one with my name (right password) so auto login didn't work later on because it's the e-mail one which is used.

Possibly related to the old code related to Chrome's broken auto-fill here https://github.com/TryGhost/Ghost-Admin/blob/master/app/templates/signup.hbs#L10-L12

Also need to investigate whether form order has any bearing on password managers - do the name and e-mail fields need swapping?

**Comment by JohnONolan** [comment]
Not stale

**Comment by kevinansfield** [comment]
A fix for Safari has been pushed to master. I tried a hundred different combos with Chrome (even their experimental credentials APIs) but I couldn't get it to store anything except the Name field as the username _unless_ the e-mail field is placed immediately before the password field, it's editable, and you actually type something in it which kind of precludes having it automatically filled in from the invitation.

**Comment by JohnONolan** [comment]
@kevinansfield Let's just swap the fields? At this point I'm ready to give up on alternatives

**Comment by JohnONolan** [comment]
Forgot we already swapped the fields on initial site setup anyway. 

I think they were this way around for email invites because the `email` field is already populated when reaching this page, so didn't want it to get in the way. But it doesn't matter really. 

![image](https://user-images.githubusercontent.com/120485/52173713-3d762a80-27bc-11e9-9ab5-e95ab5e05fc9.png)

**Comment by kevinansfield** [comment]
If we swap the fields we need to not populate the email field and make it editable - chrome only recognises it if it’s manually typed in 🤯

Does it matter if someone accepts an invite with a different email address?

**Comment by JohnONolan** [comment]
> Does it matter if someone accepts an invite with a different email address?

I think it's fine. Even if someone signed up without being able to change their email, the second they're signed up they're able to change it - so seems pointless to try and prevent it

**Comment by JohnONolan** [comment]
Just accepted another invite and didn't get prompted to save details by 1pass when submitting form. Signed out, then logged back in again and still didn't get prompted to save the details from the login screen. 

(Latest chrome)
