### ISSUE TITLE
Incorrect Ghost Out Of Date Message

### ISSUE THREAD

**Issue by fishcharlie** [TryGhost/Ghost#9875]
### Issue Summary

When going to the Ghost admin dashboard there is an alert at the top that says I need to upgrade my version of Ghost. But as you can see in the screenshot linked below I'm running the latest version of Ghost.

### To Reproduce

1. Go to Ghost admin dashboard

### Technical details:

* Ghost Version: 2.1.2
* Node Version: v6.11.1
* Browser/OS: Safari
* Database: mysql

<img width="1600" alt="screen shot 2018-09-14 at 3 17 08 pm" src="https://user-images.githubusercontent.com/860375/45575647-7b84a900-b831-11e8-8e08-c64561b26e74.png">

**Comment by gargol** [comment]
Hey @fishcharlie :wave: Looks like your issue is similar to the one discussed on Ghost forum - https://forum.ghost.org/t/ghost-2-0-3-upgrade-notification/2684 . Is your case similar? Have you tried following the steps there?

**Comment by kirrg001** [comment]
This looks like a server side improvement.

The custom message should not be returned to the client if the target version range does not match **anymore**.

e.g. Ghost receives a custom message with the version range `^1`. You migrate to Ghost 2.0. The message is still in the database and appears on the client. The server side could remember the version range and re-compare before serving.

**Comment by gargol** [comment]
After the investigation concluded that the main problem here is determining in which stage of application lifecycle to remove version notification from notifications queue. There are a couple of possible places:

1. The most straight forward is checking for update notifications during `GET api/v2/admin/notifications/` request and removing such notifications permanently. 
**Cons**:
   - dirty solution (such logic should not live on controller layer)
2. There should have been a migration released for v2.0 which should have removed these notifications. We can add such migration to the latest version. 
**Cons**: 
    - need a minor version bump for not too big of a change
    - migrations need extra care/reviews
3. Ideally, this specific notification removal should happen on Ghost upgrade event proposed [here](https://github.com/TryGhost/Ghost/issues/10236). 
**Cons**:
    - the proposed event has to be implemented first 

Think the best way to do it is going with 3rd option.

**Comment by gargol** [comment]
The solution from pt.1 was implemented as a temporary solution and the solution from pt.3 will follow once #10236 is implemented.
