### ISSUE TITLE
get rid of extraAllowedProperties in models

### ISSUE THREAD

**Issue by allouis** [TryGhost/Ghost#9881]
currently we pass `extraAllowedProperties: ['id']` to `filterOptions` in the post model, which is weird because `id` is not really an option. We should think about unifying it /cc @kirrg001

**Comment by kirrg001** [comment]
👍 Yeah there is an inconsistency.

[See user model:](https://github.com/TryGhost/Ghost/blob/2.1.2/core/server/models/user.js#L336)

> findOne: ['withRelated', 'status']

We allow the status to be forwarded as `option` e.g. `options.status = 'all'`.

**But we have treat `options.id` differently and use `extraAllowedProperties`** - [see](https://github.com/TryGhost/Ghost/blob/2.1.2/core/server/models/post.js#L633).

We could unify this for now and use `permittedOptions` for `options.id` too. And maybe we come up with a better idea in the future of "how to differentiate allow options and allow properties to be passed".
