### ISSUE TITLE
Squirrely tag creation

### ISSUE THREAD

**Issue by JohnONolan** [TryGhost/Ghost#9885]
Not sure what to title this. Latest Ghost on Pro:

- Edit post which has existing tags
- Added new tag `#test` - pressed enter
- Tag deleted itself
- Repeated the same thing a few more times
- Noticed blank/empty items in the autocomplete dropdown
- Clicked on two:

![image](https://user-images.githubusercontent.com/120485/45709153-96358580-bb83-11e8-9b83-12d57f2d591c.png)

(Nothing in console)

Pressed cmd S

![image](https://user-images.githubusercontent.com/120485/45709168-a3eb0b00-bb83-11e8-852a-6d65a039619d.png)

Went to tags screen (nothing there)

Went back to edit post, this time see an "add this?" message (wasn't there before)

![image](https://user-images.githubusercontent.com/120485/45709219-c5e48d80-bb83-11e8-8e3d-ee33cd5081e8.png)

Now I can't reproduce at all. Not sure if this is helpful. Feel free to close if nobody can reproduce

**Comment by rishabhgrg** [comment]
I tried to reproduce this with different scenarios but was unable to end up reaching this state. 😞 Closing for now.
