### ISSUE TITLE
what is it i have to do to translate the backend/admin area

### ISSUE THREAD

**Issue by divramod** [TryGhost/Ghost#9898]
Hey,

i read, that the i18n-service is currently not available for the backend/admin-area, but i need it in german.

i am searching for the easiest way to translate the backend into german.

i am ok with the standard template and some manual work.

can anyone give me a hint on where to start with that task.

thx in advance for any hint and for the awesome software you built!

**Comment by kirrg001** [comment]
Hey @divramod   👋 Friendly reminder: help or support is not available on Github. Our default issue templates pointed you to our [forum](https://forum.ghost.org) for this type of question 😄 We use GitHub solely for bug-tracking and on-going feature development so we try to keep it noise free.

Many questions can be answered by reviewing our docs for [self-hosters](https://docs.ghost.org), our [theme API](https://themes.ghost.org), or our [public API](https://api.ghost.org). If you can't find an answer then our [forum](https://forum.ghost.org) is a great place to get community support, plus it helps create a central location for searching problems/solutions.

FYI: Many projects have their own support guidelines and GitHub will highlight them for you, or the project owners will use issue templates to point you in the right direction. Reading the guidelines or issue templates before opening issues can save you and other project maintainers some valuable time.
