### ISSUE TITLE
Error: SQLITE_ERROR: table posts has no column named comment_id

### ISSUE THREAD

**Issue by pascalandy** [TryGhost/Ghost#9900]
### To Reproduce

Hi,

I manage a lot a Ghost instance in Docker. I found a random issue I'd like to share.

One website that was running smoothly for months had this error. So I thought it was a random data corruption. Shit happen.

Then the issue happens again. This time, I started a new website from scratch. I rebooted the container about 8 times in 20 minutes. I didn’t touch the content or log in the admin panel. I was just looking at the logs and see if I could see any glitches.

I can’t explain why this error appears the comment_id is suddenly disappearing !?

```
NAME: RollbackError
CODE: SQLITE_ERROR
Error: SQLITE_ERROR: table posts has no column named comment_id
```

See the [full log here](https://gist.github.com/pascalandy/8a18172090f743b46e15fbff9015f4fe).

### Technical details:

* Ghost Version: 2.1.1
* CLI version: 1.9.4
* Node Version: 8.11.4
* Browser/OS: chrome 66, osx 10.13.4
* Server-side: Alpine:3.8 in Docker [using this image](https://travis-ci.org/firepress-org/ghostfire/jobs/428717032)
* Database: sqlite

Cheers!

**Comment by pascalandy** [comment]
Actually, I'll re-test using 2.1.3

**Comment by kirrg001** [comment]
> Error: SQLITE_ERROR: table posts has no column named comment_id

This is a migration error. Happens only if you trigger migrations or if migrations needs to be executed.

> One website that was running smoothly for months had this error. So I thought it was a random data corruption. Shit happen.

This error looks like you migrated from Ghost 1.x to Ghost 2.x, but you were not on the latest Ghost 1.x release.

Let me know 👍

**Comment by pascalandy** [comment]
I confirm I was running a fresh Ghost 2.1.1 install. I don't see why a trigger migrations happened.

**Comment by kirrg001** [comment]
Can you pls share detailed steps to reproduce? Thanks :)

**Comment by kirrg001** [comment]
And: Can you double check if you don't select an existing 1.x database on fresh installation?

**Comment by pascalandy** [comment]
I did the same process using Ghost 2.1.3. It's all good now. My guess is that v2.1.1 had some bug triggering the migration process. 

Step to reproduce:

> This time, I started a new website from scratch. I rebooted the container about 8 times in 20 minutes. I didn’t touch the content or log in the admin panel. I was just looking at the logs and see if I could see any glitches.

I'll close this issue. Thanks!

**Comment by pascalandy** [comment]
Re-opening :( I got the same issue under 2.1.3. I fear this is a weird bug. 

In this case:

- the blog was updated from 1.25.4 to 2.1.3
- ran perfectly for few days
- I was editing the Code Injection section and blog crashed
- Tried the restart the container without success.
- I had the same error as described above

**My 5 cents**: I would like to know what are the scenarios that trigger the migration process.

- Why is ghost wants to migrate a DB that is actually running under 2.1.3?
- Could the system suddenly thinks that one file from the backup DB( from 1.25.4) needs to be migrated?

**Comment by kirrg001** [comment]
@pascalandy

**Comment by pascalandy** [comment]
It was the exact same error as https://gist.github.com/pascalandy/8a18172090f743b46e15fbff9015f4fe
mentioned above. but no I didn't track the log this time.

**Comment by kirrg001** [comment]
The migrations are only triggered if you

A: never executed them, but you said you have installed a fresh blog
B: you *delete* the migration entries from the database manually

Something must be weird on your container, which i can't explain. 
This blog must be on < 1.25 and tries to migrate to 2.0.

**Comment by kirrg001** [comment]
How many blogs are installed on your container?

**Comment by pascalandy** [comment]
There is only one per container.

**Comment by kirrg001** [comment]
Can you reproduce this on a fresh container?
If so, please share the exact steps. Thanks :)

**Comment by pascalandy** [comment]
That's the whole challenge, it's random at this point. 

**Idea** - Could the backup DBs (made of V1.xx) trigger the migration behavior?

**Comment by kirrg001** [comment]
As long you don't restore the backup, no.

If it happens again, can you pls share `ghost ls` and log into mysql and run `select * from migrations;`.
Furthermore the log you've provided, i need some more lines *before* the actual migration starts.

**Comment by kirrg001** [comment]
It's the same SQL query, you just need to login using sqlite3.
`sqlite3 path-to-db-file` and then `select * from migrations;`

**Comment by pascalandy** [comment]
Good to know! Will if I encounter this issue again.

**Comment by kirrg001** [comment]
@pascalandy Any news? I am not rly sure what else to test. Let me know :)

**Comment by pascalandy** [comment]
I didn't had the issue since. I'll close this for the moment. Thank you for caring :)

**Comment by pascalandy** [comment]
RE-OPENING

In this case:

- the blog was updated from 1.25.4 to 2.2.4
- the blog does not run on 2.2.4 after trying to migrate :((
- Tried the restart the container without success.
- See logs here: https://gist.github.com/pascalandy/0492231e4c88f0b5e742d868c94d0b41

I'm so curious about all these warnings
![screen shot 2018-10-21 at 3 15 14 pm](https://user-images.githubusercontent.com/6694151/47271201-67288000-d544-11e8-8439-2f08bd91a485.jpg)

**Comment by pascalandy** [comment]
I upgraded another blog successfully. 

Here are the warning from the container:

```
0236d8dea9af / docker logs --follow 0236d8dea9af
[2018-10-22 02:55:38] WARN knex-migrator is skipping 2.3
[2018-10-22 02:55:38] WARN Current version in MigratorConfig.js is smaller then requested version, use --force to proceed!
[2018-10-22 02:55:38] WARN Please run `knex-migrator migrate --v 2.3 --force` to proceed!
```

**Comment by kirrg001** [comment]
@pascalandy 

> I upgraded another blog successfully.
> There are three warnings from the container:

Thanks for sharing. You can ignore the warning. We will release Ghost `2.3.0` today 👍

**Comment by pascalandy** [comment]
**EDIT**, I was using Ghost 1.25.5 and 2.2.4. From Travis:

- devmtl/ghostfire:2.2.4-ff50fdc-20181022_03H0121
- devmtl/ghostfire:1.25.5-9e38cf2-20180820_20H0205

**Comment by pascalandy** [comment]
I still can't re-create the issue :-(
Closing

**Comment by kirrg001** [comment]
@pascalandy urgh frustrating :( Would love to help, but not sure how!
