### ISSUE TITLE
Clean up passing of objects in `context` property to errors

### ISSUE THREAD

**Issue by gargol** [TryGhost/Ghost#9902]
The issue ia a follow up to: https://github.com/TryGhost/Ignition/issues/63 . During the investigation there were multiple places found in the codebase that are passing an object in `context` property to the error:

- [theme validation](https://github.com/TryGhost/Ghost/blob/2.1.0/core/server/services/themes/validate.js#L35)
- [webhooks](https://github.com/TryGhost/Ghost/blob/2.1.0/core/server/api/webhooks.js#L39)
- [request](https://github.com/TryGhost/Ghost/blob/2.1.0/core/server/lib/request.js#L11)

Proposed convention would be to try and pass strings only when using `context` and pass in limited amount of relative data into `errorDetails` property as an object. 

Related issue https://github.com/TryGhost/Ghost/issues/10571, check if cases described here haven't been solved by it.

**Comment by kirrg001** [comment]
> Proposed convention would be to try and pass strings only when using context and pass in limited 

If Ignition normalises the data type, why do we have to update the usages? 🤔
