### ISSUE TITLE
Malformed RSS error

### ISSUE THREAD

**Issue by JohnONolan** [TryGhost/Ghost#9905]
Some RSS feeds are getting malformed, seemingly due to content which isn't fully escaped, eg:

https://blog.cloudflare.com/rss/

![image](https://user-images.githubusercontent.com/120485/46046156-48d78c00-c120-11e8-9ed2-e4f95a0cd1a2.png)

Source: https://gist.github.com/JohnONolan/ca3b3bbff071f3b18c0d7da5171248f3

**Comment by allouis** [comment]
The bytes `0x00 0x49 0x74 0x20` are `NULIt ` in utf8. So it looks like that broken character seems to be the NUL byte - which is valid utf8.

**Comment by allouis** [comment]
Aaaand ofc the RSS spec doesn't include the NUL character - this issue raised by @ErisDS gives more information: https://github.com/dylang/node-rss/issues/49

**Comment by kirrg001** [comment]
@allouis This issue sounds like a duplicate of https://github.com/TryGhost/Ghost/issues/8442

**Comment by JohnONolan** [comment]
Agreed
