### ISSUE TITLE
Feature Request: Single Sign On (SSO) using third party application like keycloak

### ISSUE THREAD

**Issue by pandeybk** [TryGhost/Ghost#9919]
Do we have any plan to support SSO features in Ghost blog using third party application like keycloak. I wonder if this feature already exist and I am missing it.

**Comment by kevinansfield** [comment]
Hey @pandeybk 👋 Friendly reminder: we don't track feature requests on GitHub. Our default issue templates pointed you to our [forum](https://forum.ghost.org) for this type of question - the [Ideas](https://forum.ghost.org/c/Ideas/l/votes) topic will let you propose features and let others vote on them 😄. We use GitHub solely for bug-tracking and on-going feature development so we try to keep it noise free.

FYI: Many projects have their own support guidelines and GitHub will highlight them for you, or the project owners will use issue templates to point you in the right direction. Reading the guidelines or issue templates before opening issues can save you and other project maintainers some valuable time..

**Comment by SimonKlausLudwig** [comment]
Would love to see this as well
