### ISSUE TITLE
Code injection missing from the Subscribe page

### ISSUE THREAD

**Issue by RadoslavGatev** [TryGhost/Ghost#9935]
### Issue Summary
The code injection does not work on the "Subscribe" page.
Therefore tracking Goals/Conversions is impossible.
### To Reproduce
Not applicable
### Technical details:
* Ghost Version: 2.1.0
* Node Version: 8.11.1
* Browser/OS: Chrome/Windows
* Database: SQLite

**Comment by kirrg001** [comment]
Hey @RadoslavGatev   👋 Friendly reminder: help or support is not available on Github. Our default issue templates pointed you to our [forum](https://forum.ghost.org) for this type of question 😄 We use GitHub solely for bug-tracking and on-going feature development so we try to keep it noise free.

Many questions can be answered by reviewing our docs for [self-hosters](https://docs.ghost.org), our [theme API](https://themes.ghost.org), or our [public API](https://api.ghost.org). If you can't find an answer then our [forum](https://forum.ghost.org) is a great place to get community support, plus it helps create a central location for searching problems/solutions.

FYI: Many projects have their own support guidelines and GitHub will highlight them for you, or the project owners will use issue templates to point you in the right direction. Reading the guidelines or issue templates before opening issues can save you and other project maintainers some valuable time.

**Comment by RadoslavGatev** [comment]
Hey @kirrg001,
Friendly reminder: That's not a question and I can perfectly read and understand templates pointed to me😄
That's an issue with your system as it says the following about **Code injection**
> Code here will be injected into the {{ghost_head}} tag **_on every page of your blog_**

Thank you so much!

**Comment by kirrg001** [comment]
@RadoslavGatev Yes the code will be injected into the {{ghost_head}} on any page, **if the ghost_head is used**. The subscriber app does not use the head by default.

If you want to use it, you can override the subscribe.hbs and put it in your theme.
