### ISSUE TITLE
"Site changed" webhook

### ISSUE THREAD

**Issue by kevinansfield** [TryGhost/Ghost#9942]
Alongside the [API v2](https://github.com/TryGhost/Ghost/issues/9866) and new [auth mechanisms](https://github.com/TryGhost/Ghost/issues/9865) we'll be exposing our webhooks functionality via the admin UI and adding a new "site changed" webhook.

Brief feature outline:
- allow registration of webhooks via the admin UI
- add a new "site changed" webhook that can be used to trigger rebuilds when using static site generators such as gatsby.js with Netlify

**Comment by jloh** [comment]
It'd be great to have webhooks validated like GitHub's are! https://developer.github.com/webhooks/securing/#validating-payloads-from-github

Apologies if this has already been considered, I can't see anything hinting towards it.

**Comment by kirrg001** [comment]
@rishabhgrg Can we close this issue?

**Comment by rishabhgrg** [comment]
@kirrg001 Keeping it open till the UI is enabled for this, will close after.
