### ISSUE TITLE
Leaving ghost now.

### ISSUE THREAD

**Issue by rgarrigue** [TryGhost/Ghost#9968]
Hi

I've been using Ghost for a while now. I'll be looking for an alternative now. I though I owe you this feedback.

Ghost was for me a simple and clean solution for a markdown blog where I could just write down notes on technical stuff, put a picture once in a while, with either a text only editor, a dual panel with text editor and preview. 

Then you updated the editor, I don't remember the detail but a WYSIWYG editor became the default at some point, with a button to switch back to the dual panel, something like that. I don't mind a new editor but I wish I could say "text mode is the default for me". Wasn't happy but well, I can click on a button. 

Then you updated the editor again. I can't even access a raw text editor mode anymore, I have this weird "+ to add a panel" system, gotta add a markdown panel, ending up with a so 2010' phpBB kinda WISYWIG editor. 

But some some people just want to focus on writing down content, then deal with presentation in a simple rational way (aka markdown or adoc) with a simple helper for the occasional image. You could have kept a simple editor and a fancy one, allowing people to choose. So, I'm off. Fare well.

**Comment by kevinansfield** [comment]
@rgarrigue Ghost's 2.0+ editor accepts all markdown formatting without adding a markdown card so you're still free to focus on your content and format later using the markdown you're used to. 

Thank you for the feedback and sorry that Ghost is no longer a perfect fit for you 😄

**Comment by ilyapuchka** [comment]
@kevinansfield I'm on a 2.9.0 and unfortunately experience the same inconveniences with the editor. Can you suggest how it can be used with raw Markdown? For instance starting a post in the web editor and then copy-pasting its content in the app, i.e MacDown looses code blocks and all the formatting (like `###` headers)
